Nuke the syndicate base
tgstation/tgstation pull request #20471
Opened 2016-09-12 07:21 UTC by KorPhaeron

I'm not sure how often this will ever happen but it will be fun if it does.

2016-09-12 07:21 UTC, kevinz000 commented
:3c

2016-09-12 07:21 UTC, Ultimate-Chimera commented
wat

2016-09-12 07:24 UTC, Jalleo commented
Wasnt there a old bug report about it breaking the server?

2016-09-12 07:25 UTC, KorPhaeron commented
That got fixed by tkdrg or incoming, one of the two

2016-09-12 15:16 UTC, ExcessiveUseOfCobblestone commented
does this not encourage people to """""find""""" the syndicate ship and try to counter raid it for OMEGA-REDTEXT

2016-09-12 15:51 UTC, KorPhaeron commented
probably

2016-09-12 17:00 UTC, Durkel commented
pls don't encourage the meta shitters who would go look for the ship.

2016-09-12 18:46 UTC, GunHog commented on code/game/gamemodes/nuclear/nuclear.dm
> +		feedback_set_details("round_end_result","loss - syndicated nuked - disk secured")
syndicate*

2016-09-13 14:55 UTC, InsaneHyena commented
Do normies even have access to syndicate navigation computer?

2016-09-13 15:41 UTC, KorPhaeron commented
@InsaneHyena 

No, but every once in a while an op fucks up spectacularly and you take his ID card

2016-09-13 17:36 UTC, PKPenguin321 commented
I think I've actually done this before so :+1:

2016-09-14 07:02 UTC, kilkun commented
whats to stop the nuke ops from collaborating with the station to blow up the syndicate fob and secede from the syndicate?

2016-09-15 06:58 UTC, AnturK commented on code/game/gamemodes/nuclear/nuclear.dm
> +	if(nuke_off_station == 3)
Please turn these into defines while you're here.

2016-09-15 07:00 UTC, AnturK requested changes

2016-09-20 01:31 UTC, KorPhaeron commented
>conflicts

antur betrayed me

2016-09-20 01:42 UTC, closed without merging