Adds some visual effects when ammo casings are fired and when projectiles hit things
tgstation/tgstation pull request #20508
Opened 2016-09-14 00:59 UTC by phil235

:cl: optional name here
add: Added new things
imageadd: added some icons and images
/:cl:

2016-09-14 00:59 UTC, PKPenguin321 commented
pics

2016-09-14 01:02 UTC, ChangelingRain commented on code/game/objects/effects/overlays.dm
> +	var/splatter_type = "splatter"
:+1:
might want to rename the path, though

2016-09-14 01:04 UTC, RemieRichards commented
tl;dr:
* support for muzzle flashes/effects when a bullet is fired
* mobs make a little blood splatter when they're hit (xenos have a sprite for this too)

2016-09-14 01:04 UTC, ChangelingRain commented on code/modules/projectiles/firing.dm
> +		new firing_effect_type(get_turf(src), firing_dir)
`PoolOrNew(firing_effect_type, list(get_turf(src), firing_dir))` though I still have no idea if it's performance efficient.

2016-09-14 01:05 UTC, ChangelingRain commented on code/modules/projectiles/projectile.dm
> +			new impact_effect_type (target_loca, target, src)
`PoolOrNew(impact_effect_type, list(target_loca, target, src))` though see above

2016-09-14 01:05 UTC, ChangelingRain commented on code/modules/projectiles/projectile.dm
> +			new impact_effect_type (target_loca, target, src)
etc etc you get the idea

2016-09-14 01:58 UTC, WJohn commented
More visual feedback is always good :+1:

2016-09-14 07:27 UTC, MrPerson commented
Great changelog entry you got there

Neato effect

2016-09-14 19:44 UTC, Tacolizard commented
goon lighting when

2016-09-14 20:12 UTC, ChangelingRain reviewed
Oh hey this is new, summary;
AAAA USE PoolOrNew() AAAA

2016-09-14 20:26 UTC, ChangelingRain commented on code/game/objects/effects/overlays.dm
> +	density = 0
Both this and the above var are already set like this on the parent type.

2016-09-14 20:27 UTC, ChangelingRain commented on code/game/objects/effects/overlays.dm
> +	density = 0
Both this and the above var are already set like this on the parent type.

2016-09-14 20:28 UTC, ChangelingRain requested changes
Use the inheritance phil

2016-09-14 21:54 UTC, Razharas approved these changes
Im Razharas and i approve this message

2016-09-15 17:04 UTC, GunHog commented
This is cooler than cool!

2016-09-15 17:26 UTC, phil235 commented
Alright, I did the requested changes.

2016-09-15 19:06 UTC, ChangelingRain approved these changes

2016-09-16 00:27 UTC, merged