Tweaks for Readability/Usability for the anomalous crystal
tgstation/tgstation pull request #20531
Opened 2016-09-15 03:19 UTC by Ergovisavi

:cl:
add: Added a nightvision toggle to Shadowpeople
tweak: Made several anomalous crystal variants more easily identified/easier to see the effects thereof, and removed the "magic" activation possibility (replaced with the "bomb" flag)
/:cl:

### Anomalous Crystal tweaks

- Made several crystals have visible effects upon activation to remove the ambiguity a little bit
- Removed the "magic" activation requirement as a possible option, replaced with "bomb" (KA's/Crushers can proc this, as can actual explosions)
- Added medical huds to Lightgeists
- Lightgeists can now be spawned properly by admins if they are into tentacles
- Added Bows & Quivers to the jungle variant of the theme_warp crystal as the Jungle variant itself just wasn't particularly interesting
- Gave shadowpeople a nightvision toggle because not being able to tell where shadows are is just the worst when playing as one
- Fixed some issues with the possessor artifact, it shouldn't render people comatose if they are in a mob that dels on death
- Fixed the ghost link when the lightgeist crystal is activated

Other stuff

- Fixed a bug with emp pulse overlays not showing up due to a typo

2016-09-15 07:38 UTC, AnturK commented on code/modules/mob/living/carbon/human/species_types.dm
> +	var/datum/action/innate/shadow/darkvision/D = new /datum/action/innate/shadow/darkvision()
Make this /species/shadow variable

2016-09-15 07:39 UTC, AnturK commented on code/modules/mob/living/carbon/human/species_types.dm
> +	for(var/A in C.actions)
Then you can just refer to it here instead of looping through the actions

2016-09-15 07:39 UTC, AnturK commented on code/modules/mob/living/carbon/human/species_types.dm
> +		H << "<span class='notice'>You adjust your vision recognize the shadows.</span>"
missing "to" ?

2016-09-15 07:41 UTC, AnturK commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +				var/turf/T = i
You don't really need to cast it here.

2016-09-15 07:43 UTC, AnturK commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +			if(istype(i, /obj/item) && !istype(i, /obj/item/weapon/storage) && !(i in affected_targets) && !istype(i, /obj/item/weapon/implant) && !istype(i, /obj/item/weapon/implanter) && !istype(i, /obj/ite
This whole line could use  compressing to typecache check

2016-09-15 07:44 UTC, AnturK commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	return
Return not needed here.

2016-09-15 07:45 UTC, AnturK requested changes
Minor issues

2016-09-16 04:09 UTC, Ergovisavi commented
Github confuses me, all the above comments should have been addressed, but they don't go away.

2016-09-16 06:32 UTC, AnturK approved these changes

2016-09-16 06:33 UTC, AnturK commented
Yeah, seems approving doesn't hide it either.

2016-09-17 01:47 UTC, merged