Officer's Sabre Tweaks
tgstation/tgstation pull request #20565
Opened 2016-09-17 10:21 UTC by TechnoAlchemisto

:cl: Papa Bones
tweak: You can now quick-draw the officer's sabre from its sheath by alt-clicking it.
/:cl
Allows for quickdrawing the sabre.
Also changes the attack text since it's no longer a rapier, and it doesn't make sense that it can dismember with point lunges and thrusts.

2016-09-17 11:48 UTC, alphaaBeta commented
How about adding something similar to the shoulder holster?

2016-09-17 15:55 UTC, Lexorion commented
Nice

2016-09-17 16:19 UTC, RemieRichards commented on code/game/objects/items/weapons/storage/belt.dm
> +	return
trailing return, remove it please.

2016-09-17 16:20 UTC, RemieRichards commented on code/game/objects/items/weapons/storage/belt.dm
> +		update_icon(I)
```update_icon()``` for the sabre BELT (which is the one you're calling with this line) takes no arguments, so don't pass it  ```I```

2016-09-17 16:21 UTC, RemieRichards commented on code/game/objects/items/weapons/storage/belt.dm
> +		update_icon(I)
```update_icon()``` for the sabre BELT (which is the one you're calling with this line) takes no arguments, so don't pass it  ```I```

2016-09-17 16:21 UTC, RemieRichards commented on code/game/objects/items/weapons/storage/belt.dm
> +	return
trailing return, remove it please.

2016-09-17 16:21 UTC, RemieRichards requested changes

2016-09-17 17:38 UTC, Jalleo commented on code/game/objects/items/weapons/storage/belt.dm
> +	if(contents.len)
You just made a possible error all ghosts may be able to pick this up.

2016-09-17 19:06 UTC, PKPenguin321 commented on code/game/objects/items/weapons/storage/belt.dm
> +	desc = "An ornate sheath designed to hold an officer's blade. Alt-Click to quickly draw the sheathed blade."
we really need to standardize this kind of thing, i tried to do something like that in https://github.com/tgstation/tgstation/pull/17050 but got lazy, please do something like that thanks

2016-09-17 19:25 UTC, WJohn commented
Frankly the holster should really just be something you can click on to pull the gun out of, no alt clicking required. If you want to remove the holster, click drag it off like you do backpacks or belts.

2016-09-17 20:15 UTC, TechnoAlchemisto commented on code/game/objects/items/weapons/storage/belt.dm
> +	desc = "An ornate sheath designed to hold an officer's blade. Alt-Click to quickly draw the sheathed blade."
This is basically only for the sabre, if I was making quickdraw a thing for multiple items i'd probably standardize it, also I don't really know how to get into it.

2016-09-17 20:22 UTC, TechnoAlchemisto commented on code/game/objects/items/weapons/storage/belt.dm
> +	if(contents.len)
I'm not entirely sure how to go around fixing this, any advice?

2016-09-17 21:38 UTC, Jalleo commented on code/game/objects/items/weapons/storage/belt.dm
> +	if(contents.len)
if(!alien() |& (incapacitated() || lying)
        Return //This isnt indented properly
Then rest of the altclick code afterwards in current setup.
at the start should catch some of the things BUT i highly suggest you test to see if morphs or anything like ghosts or simple mobs which you think shouldn't handle this are able to ineract after adding this check with a return to the start of the proc

2016-09-17 21:59 UTC, TechnoAlchemisto commented on code/game/objects/items/weapons/storage/belt.dm
> +	if(contents.len)
code\game\objects\items\weapons\storage\belt.dm:435:error: missing left-hand argument to &.

2016-09-18 06:57 UTC, Core0verload commented
>Frankly the holster should really just be something you can click on to pull the gun out of, no alt clicking required. 

Then just remove holsters and make sabres fit in belt slot.

2016-09-18 08:44 UTC, Jalleo commented on code/game/objects/items/weapons/storage/belt.dm
> +	if(contents.len)
Cant really help today until about nine hours from now. I shall try and see what the issue is then.

2016-09-19 12:52 UTC, Jalleo commented
Because nobody approved the pending pr message
Okay my fault because I was on my phone before going to sleep I wrote the check wrong entirely.
if(isalien(user) || user.incapacitated() || user.lying)
return //not properly indented
if rest of the proc
That is how it should be. But the issue is due to another bug which is in the issue reports all mobs can pickup objects via altclick interactions at the moment. (Including corgis)

2016-09-19 20:41 UTC, TechnoAlchemisto commented
Is it possible to make it so only humans (and other human-like races) can use it?

2016-09-19 22:23 UTC, Thunder12345 commented
ishuman()

2016-09-20 00:45 UTC, optimumtact commented
@RemieRichards can you check if the required changes are done and approve this?

2016-09-20 01:00 UTC, TechnoAlchemisto commented
Ghost and Alien checks are in, so a review from someone would be fantastic!

2016-09-21 21:07 UTC, optimumtact commented
perhaps use

    user.canUseTopic(src)

Instead of re adding all the checks for humans being able to use things?

2016-09-21 22:44 UTC, TechnoAlchemisto commented
Is that used the same way the is human check works?

2016-09-21 22:48 UTC, optimumtact commented
I mean in the form

    is_human(user) && user.canUseTopic(src)

2016-09-21 23:22 UTC, TechnoAlchemisto commented
Oh, that makes sense, I'll try to make this work.

Thanks!

2016-09-22 22:25 UTC, merged