Adds pizza delivery from another unamed station
tgstation/tgstation pull request #20643
Opened 2016-09-22 23:34 UTC by optimumtact

:cl: oranges
add: It looks like a pizza delivery from an un-named station got misplaced
/:cl:

#20642

2016-09-22 23:38 UTC, Incoming5643 commented
https://www.youtube.com/watch?v=DEStdShMRKs

2016-09-23 01:00 UTC, PKPenguin321 commented on code/modules/events/shuttle_loan.dm
> +			SSshuttle.centcom_message += "Pizza delivery for Spacestation 13"
Pizza delivery for Spacestation 13****!****

2016-09-23 01:00 UTC, PKPenguin321 reviewed
shit i accidentally clicked start review

2016-09-23 01:04 UTC, Supermichael777 commented on code/modules/events/shuttle_loan.dm
> +				if(prob(10))
do an else with another kind of pizza so the power-gamers can't tell

2016-09-23 01:08 UTC, Supermichael777 commented
ad an else with another piza so they can't count

oh and make sure its sprite has writing

2016-09-23 01:57 UTC, Iamgoofball commented on code/modules/events/shuttle_loan.dm
> +			if(PIZZA_DELIVERY)
should datumize these

2016-09-23 01:57 UTC, Iamgoofball requested changes

2016-09-23 03:18 UTC, Cheridan commented on code/modules/events/shuttle_loan.dm
> +			priority_announce("Cargo: It looks like a neighbouring station accidentally delivered their pizza to you instead","Centcomm Spacepizza Division")
Centcom

2016-09-23 03:18 UTC, Cheridan commented on code/modules/events/shuttle_loan.dm
> +			SSshuttle.centcom_message += "Pizza delivery for Spacestation 13"
Should make it use the station name

2016-09-23 19:19 UTC, ShadowDeath6 commented on code/modules/events/shuttle_loan.dm
> +			priority_announce("Cargo: It looks like a neighbouring station accidentally delivered their pizza to you instead","Centcomm Spacepizza Division")
I think it's actuallh centcomm since command has 2 "m"s

2016-09-23 23:15 UTC, lordpidey commented on code/modules/events/shuttle_loan.dm
> +					shuttle_spawns.Add(/obj/item/pizzabox/bomb)
Small suggestion:  add an else to this prob, that way people can't meta "There's seven boxes!  One of them's a bomb!"

Also, for readability's sake, add identical pizza types in adjacent lines.

2016-09-24 03:38 UTC, Jordie0608 commented on code/modules/events/shuttle_loan.dm
> +			priority_announce("Cargo: It looks like a neighbouring station accidentally delivered their pizza to you instead","Centcomm Spacepizza Division")
No it's Centcom, see two lines above this.

2016-09-24 22:55 UTC, merged