Reduces damage of surgery tools
tgstation/tgstation pull request #20641
Opened 2016-09-22 23:15 UTC by pudl

:cl:
del: Surgery tools now do less damage.
/:cl:

Scalpel and surgical drill do 3 damage, circular saw does 5.

Mapping is annoying when surgery has to be isolated to avoid tools being looted. I'm hoping this change will make people less keen on immediately stealing them whenever they're in sight.

This will make fucking surgery up less risky, but I think that that's actually a good change, and even when it was dangerous, people could immediately patch the person up since the tools were only really used by medical doctors.

2016-09-22 23:16 UTC, WJohn commented
That's a little bit overkill.

2016-09-22 23:16 UTC, pudl commented
@WJohn Even at 10 damage people would want to loot them.

2016-09-22 23:16 UTC, Incoming5643 commented
A saw is a saw. It SHOULD hurt.

2016-09-22 23:16 UTC, TehZombehz commented
You hit me once with a circular saw on accident while doing surgery! Reasonable escalation, you're valid! *kill stab murder death valid*

2016-09-23 01:09 UTC, PKPenguin321 commented
fucking awful PR

2016-09-23 01:10 UTC, PKPenguin321 commented on code/modules/surgery/tools.dm
> +	force = 3
what are you some kinda fuckin nerd

2016-09-23 01:10 UTC, PKPenguin321 requested changes
this pr would be better if it was closed and not merged

2016-09-23 01:39 UTC, nullbear commented on code/modules/surgery/tools.dm
> +	force = 3
wow. I'm better off using the medical wrench.

2016-09-23 02:57 UTC, pudl commented
Alright, i made the values higher, hopefully this is good

2016-09-23 02:58 UTC, pudl commented on code/modules/surgery/tools.dm
> +	force = 3
changed

2016-09-23 05:22 UTC, PKPenguin321 commented
You literally just made the 3 into a 5. This is complete hugbox I ded garbage

2016-09-23 06:02 UTC, kevinz000 commented
pudl being pudl
also, nerfing surgery implants before they even get added to R&D.

2016-09-23 13:00 UTC, GunHog commented
Killing people with the saw while pretending to do surgery on them is fun! :(

2016-09-23 16:11 UTC, Aloraydrel commented
Horrible.

2016-09-23 16:47 UTC, pudl commented
@PKPenguin321 Read the op, i put my reason for making the PR right there

2016-09-23 17:29 UTC, PKPenguin321 commented
It's shitty reasoning

2016-09-23 17:34 UTC, chickenboy10 commented
I can maybe understand if it was help intent did less damage.
Like "whoops i meant to use a scapel to sever muscle not a saw ouchies"
But comon these values are way to low for what the items actually are.

2016-09-23 19:47 UTC, nullbear commented
> surgery in the open

not only is that unsanitary but it's a private room for a reason, not just because 'surgical tools hurt lots'
It's also very useful for traitor doctors as it's quite hidden away.

2016-09-24 02:50 UTC, pudl commented
@PKPenguin321 No, it isnt. Look at the way surgery is set up on goon:

![](http://i.imgur.com/2fjVJdf.png)

Personally i like this set up, and if we reduced the damage of surgery tools then that would give the freedom to map shit like this, giving surgery more than one table or centralizing it more, since the tools arent stuff that everyone immediately wants to loot. I am about to start mapping again and i SERIOUSLY want to go for a centralized surgery design like this (maybe having stuff like sleepers, cryo and surgery all collected in one central room) and i think its HELLA cool.

@chickenboy10 The point isnt really to make surgery less dangerous, thats just a side effect. The reason i made the pr is to make surgery tools less desirable for stealing.

@nullbear This is purely for new maps, no one is going to remap box surgery to be somewhere else. And regardless, there are cooler ways to give traitors a nice cranny tucked away. Metastation has an auxiliary storage for medbay thats super duper chic, for example. Or even the patient rooms that no one on earth looks at.

2016-09-24 03:27 UTC, GunHog commented
You should not force this change on everyone just for the sake of your own ambitions. _Var edit the tools on your own map to have a different name and force._ This will fulfill your wish to have tools in the common area of your map, but without disrupting other maps.

2016-09-24 03:41 UTC, Bawhoppen commented
allura go away

2016-09-24 03:53 UTC, pudl commented
@GunHog I said for future maps as well, this would be a good change for any future mapper, and it could also be moved to box if someone has the time to remap it. If someone actually thinks medbay needs a redesign then i would love to do it, i just dont like dedicating time to changes that dont get accepted (aka all of my changes)

2016-09-24 04:13 UTC, PKPenguin321 commented
does goon also have fucking 5 force saws because if so that's fucking dumb like this pr

2016-09-24 04:18 UTC, pudl commented
@PKPenguin321 theyre 3 force there

2016-09-24 05:10 UTC, PKPenguin321 commented
abysmal

2016-09-24 07:58 UTC, nullbear commented
the fact that people don't break into chemistry to steal saws kind of shows how invalid this point is. Every time i've gone to surgery, the saw has been right where i expected it to be.

2016-09-24 15:54 UTC, LaharlMontogmmery commented
I'm having a hard time picturing the point of this PR.

And I agree - a saw is a saw. It should hurt as much as a welder- which is by the way, commong enough.

2016-09-24 17:20 UTC, jughu commented
The only benefit of the saw is that it can knockdown and its not like cargo/science can make a infinite supply anyways BUT DONT TOUCH MY EMERGENCY SURGERY COMBAT GAMEPLAY

2016-09-24 17:21 UTC, jughu commented
And goonstation has a deeper bleed damage adventage to make up for it they do less brute but they do more bleeddanage which auctally can kill you faster then just plain brute even if you survive gotta stop the bleeding in the time

2016-09-24 19:51 UTC, KorPhaeron commented
The saw and drill have some of the most satisfying hit sounds in the game and it'd be sad if they weren't worth hitting people with anymore

2016-09-24 19:52 UTC, KorPhaeron commented on code/modules/surgery/tools.dm
> +	force = 3
Welding tools have no knockdown, saws are definitely better

2016-09-24 23:40 UTC, Cheridan commented
sorry; universally disliked

2016-09-24 23:40 UTC, closed without merging

2016-09-24 23:41 UTC, PKPenguin321 commented
sorry my words were so harsh youre not a bad dude pudl but this pr is bad

2016-09-25 06:16 UTC, pudl commented
@pkpenguin321 fuck off

2016-09-25 06:28 UTC, Bawhoppen commented
@pudl you're on thin ice as it is, it would be unwise for you to act like this

2016-09-25 18:33 UTC, pudl commented
@bawhoppen no im not

2016-09-25 18:36 UTC, pudl commented
![](http://i.imgur.com/Lr910QMl.jpg)