IMMENSE BUFF TO SECURE BRIEFCASES/WALLSAFE
tgstation/tgstation pull request #20668
Opened 2016-09-24 23:00 UTC by ExcessiveUseOfCobblestone

:cl: Cobby
tweak: Nanotrasen has buffed the electronic safety devices found in Secure Briefcases and Wallsafes, making them... well... more secure. In Particular, we added more wires that do absolutely nothing to hinder the use of the multitool, along with remove the ID slot only used by syndicates to emag the safe.
/:cl:

**TRIGGER WARNING: HIGHLY CONTROVERSIAL**

SAY GOODBYE EMAG USERS! THE AGE OF THE MULTITOOL IS UPON US!

In Short: Removes Emag Function [aka Requiring a multitool], and has a lower chance to successfully hack [from 40% to 33%]

It doesn't make sense that something that has no place for an ID can be swiped with an over glorified ID. Git gud and use the multitool. Now when someone puts secure items in the secure safe, people won't laugh at them [i mean they probably still will, but it's ok].

2016-09-24 23:15 UTC, lordpidey commented on code/game/objects/items/weapons/storage/secure.dm
> +		if(!emagged)
Remove the whole emagged variable, it doesn't do anything now anyway.

2016-09-24 23:21 UTC, ShadowDeath6 commented
change remove to removing in your cl

also this is pretty good, now cap can put the disk into his secure safe without being called a dumbshit as often

2016-09-24 23:21 UTC, lordpidey commented
Noo!  Keep the sassy messages!  They're hilarious!

2016-09-24 23:28 UTC, optimumtact commented
code/game/objects/items/weapons/storage/secure.dm:75:error: src.emagged: undefined var
   code/game/objects/items/weapons/storage/secure.dm:77:error: src.emagged: undefined var
   code/game/objects/items/weapons/storage/secure.dm:96:error: src.emagged: undefined var
   code/game/objects/items/weapons/storage/secure.dm:104:error: src.emagged: undefined var

2016-09-24 23:33 UTC, ExcessiveUseOfCobblestone commented
CRAWLING IN MY SKIN

2016-09-24 23:34 UTC, Cheridan commented
will probably be too strong a deterrent against nuke ops, who generally don't have time to fuck around with tools

2016-09-24 23:39 UTC, PKPenguin321 commented
yeah this is kind of a pointless nuke op nerf, also is there any actual delay to using a multitool on this because if not probs dont really matter

2016-09-24 23:45 UTC, ExcessiveUseOfCobblestone commented
I think you can bypass it all with a c4 though.

2016-09-25 00:00 UTC, PKPenguin321 commented
can it though? actually test because last i checked C4 cant be planted on storage items, it tries to put the C4 in them

2016-09-25 00:04 UTC, ExcessiveUseOfCobblestone commented
yes I just checked. It MAY not let you c4 it when it's unlocked, but uh.... what's the point in that.

2016-09-25 00:09 UTC, PKPenguin321 commented
it's not a meme for nuke ops though, 99% of them do not carry multitools and getting one when the crew is out to rape you constantly is not as easy as you'd imagine

2016-09-25 00:36 UTC, kevinz000 commented
i see that clusterbang line underneath
would be lovely if you could fix it and maybe uncomment it.

2016-09-25 00:39 UTC, ExcessiveUseOfCobblestone commented
Then prepare better? You already get a toolbox in the ship, and it isn't exactly hard to raid engineering when a majority of ops go near engineering to bomb tcomms. You can even use your emag there on the locker to get a locker-full of multitools [and screwdrivers since you have to open up the wires]. With that said, c4 WILL cuck the safe, so just keep a c4 handy which you should do anyways.

The Elusive Emag being a one-hit-wonder on nearly every item that remotely deals with electricity is silly.

2016-09-25 01:46 UTC, ExcessiveUseOfCobblestone commented
ok my brainfart is over, i'm retarded, and now it should compile without the emag var

2016-09-25 02:49 UTC, AdamElTablawy commented
there are multitools on the god damn ship i'm fairly certain a nukeop team well armed enough to get past the initial tide and into the cap's office with a captain stupid enough to leave it in the safe can actually multitool it open

not to mention this makes the safe WAY easier to open instead of harder-the secure safe is now stupid easy to open instead of 'have emag or DIE'.

so yes, in favor

2016-09-25 04:44 UTC, PKPenguin321 commented
there's like 1 multitool on the ship iirc, in the syndie toolbox, that's it

2016-09-25 04:45 UTC, RemieRichards commented on code/game/objects/items/weapons/storage/secure.dm
> +	return
trailing return, remove it please.

2016-09-25 04:46 UTC, RemieRichards requested changes

2016-09-25 05:09 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/weapons/storage/secure.dm
> +	return
done

2016-09-25 05:11 UTC, RemieRichards approved these changes

2016-09-25 05:14 UTC, ExcessiveUseOfCobblestone commented
>there's like 1 multitool on the ship iirc, in the syndie toolbox, that's it

couple that with the grenade, the syndicate beacons, and not to mention their own TC pool, there should be ZERO reason why they can't bust a static object.

2016-09-25 05:54 UTC, PKPenguin321 commented
honestly i would just remake these things so that they're just like personal lockers. if you have high enough ID access you can open them no matter what, otherwise they're only unlockable by whoever swipes their ID in them first (or by emags/EMPs)

2016-09-25 06:28 UTC, Bawhoppen commented
a PR we can all get behind :+1:

2016-09-25 07:04 UTC, ExcessiveUseOfCobblestone commented
> instead of taking the emag portion away and keeping the unique portion of the safes, try to rework them entirely so they thematically make sense to use the emag to the point where they're no different from the other storage units outside of aesthetics.

No more memes please.

2016-09-25 07:20 UTC, PKPenguin321 commented
I don't really understand the necessity of making it emag proofed anyways

>inb4 realism argument

2016-09-25 10:07 UTC, Ultimate-Chimera commented
rip memes

2016-09-25 15:23 UTC, xxalpha commented
Stop telling whole fucking stories in your changelogs, everyone.

2016-09-25 17:54 UTC, ExcessiveUseOfCobblestone commented
It's hip to make roleplay oriented changelogs.

2016-09-25 18:28 UTC, JJRcop commented on code/game/objects/items/weapons/storage/secure.dm
> +	if(istype(W, /obj/item/weapon/card/emag))
So this exists only to insult people who try to use the emag

2016-09-25 23:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/weapons/storage/secure.dm
> +	if(istype(W, /obj/item/weapon/card/emag))
yes

2016-09-25 23:54 UTC, nullbear commented
There is also a multitool right on the bridge.

2016-09-26 01:38 UTC, PKPenguin321 commented
supposing that the disk is placed in a secure briefcase that is then moved that is really irrelevant

removing emag vulnerability is a pointless nerf to ops

2016-09-26 01:43 UTC, ExcessiveUseOfCobblestone commented
you could just pull the case instead of saying "HOLD UP VALIDHUNTERS, I GOTTA HACK THIS CASE REEEEAALLLL QUICK"

2016-09-26 16:25 UTC, AdamElTablawy commented
honestly this is a pointless nerf to the briefcase making it far easier to hack

2016-09-26 17:10 UTC, ExcessiveUseOfCobblestone commented
> honestly this is a pointless nerf to the briefcase making it far easier to hack

It's not a nerf, the probability to successfully hack one has been lowered from 40% to 33%.

2016-09-27 20:51 UTC, optimumtact commented
I'm convinced

2016-09-27 20:51 UTC, merged