[WIP] Devicecrafting
tgstation/tgstation pull request #20684
Opened 2016-09-26 01:11 UTC by Iamgoofball

smash shit together

get finished device
![giphy 1](https://cloud.githubusercontent.com/assets/4081722/18819761/5bf36788-834b-11e6-9b70-6f599bdd77fa.gif)

2016-09-26 01:13 UTC, optimumtact commented on code/modules/research/devicecrafting/device.dm
> +/obj/item/devicecrafting/device/trigger/tesla // tiles surrouding my tile
Funny but lose the comments

2016-09-26 01:16 UTC, optimumtact commented on code/modules/research/devicecrafting/obj_stuff.dm
> +/obj
why does every single object need to hold devices for crafting?

They're just creating the final device in a frame? why is this so high in the typepath?

2016-09-26 01:16 UTC, Razharas commented on code/game/objects/items.dm
> +		devicecrafting_holder.on_attackby(W,user)
WHy not just call ..()

2016-09-26 01:16 UTC, optimumtact requested changes

2016-09-26 01:16 UTC, optimumtact commented on code/modules/research/devicecrafting/obj_stuff.dm
> +/obj
also this violates the codebase standard

2016-09-26 01:17 UTC, optimumtact commented on tgstation.dme
> +#include "_maps\testmap.dm"
can u not

2016-09-26 01:18 UTC, ma44 commented
http://imgur.com/gallery/Br00TCn

2016-09-26 01:20 UTC, optimumtact commented on code/modules/research/devicecrafting/device.dm
> +/obj/item/devicecrafting/device/proc/on_afterattack(atom/target, mob/user, proximity_flag)
why are you overriding these if they do nothing? just leave them undefined

2016-09-26 01:23 UTC, Iamgoofball commented on tgstation.dme
> +#include "_maps\testmap.dm"
whooops

2016-09-26 01:23 UTC, Iamgoofball commented on code/modules/research/devicecrafting/device.dm
> +/obj/item/devicecrafting/device/proc/on_afterattack(atom/target, mob/user, proximity_flag)
what do you mean by overriding

it's setting up the framework for devices

2016-09-26 01:24 UTC, Razharas commented
Explain what the fuck is this how it works and what for

2016-09-26 01:25 UTC, Iamgoofball commented
@Razharas goofR&D

you print a device frame

you print devices

you attach trigger/effect/misc devices and they make the device do different things

2016-09-26 01:28 UTC, optimumtact commented
how do they actually trigger actual items though, have you just not got to that point?

2016-09-26 01:28 UTC, Razharas commented
If this is new r&d than it surely lacks the r part of it

2016-09-26 01:29 UTC, Iamgoofball commented
@Razharas youre gonna research it by making your own devices and finding your favorites
@optimumtact that's where the hook-ins come in

2016-09-26 03:09 UTC, Iamgoofball commented on code/modules/research/devicecrafting/obj_stuff.dm
> +/obj
it's so I can have a structure/machine device frame and a handheld frame without snowflaking/copypaste

what the fuck we don't absolute path vars

2016-09-26 03:09 UTC, Iamgoofball commented on code/modules/research/devicecrafting/device.dm
> +/obj/item/devicecrafting/device/trigger/tesla // tiles surrouding my tile
these ones are actually important so no

2016-09-26 13:59 UTC, LaharlMontogmmery commented
>Goof reworking RnD

It BEGINS.

And I'm surprisingly OK with this.

2016-09-27 00:12 UTC, Shadowlight213 commented
Wait, so does this replace the shitcode that is assemblies?

2016-09-27 01:19 UTC, optimumtact commented
completely different thing

2016-09-27 01:47 UTC, Core0verload commented
\>assemblies
\>shitcode 

Did you ever saw the _old_ assemblies?

2016-09-27 04:46 UTC, Shadowlight213 commented
They were made not shit?
The old ones I guess are what I was thinking of.

2016-09-29 16:06 UTC, Supermichael777 commented
>it doesn't compile

GOOOOOOOOOF

2016-10-02 06:06 UTC, Bawhoppen commented
branchnameaccurate

2016-10-02 14:59 UTC, GunHog commented
Are you still working on this, Goof?

2016-10-02 17:40 UTC, Iamgoofball commented
yeah let me finish it up with triggers

2016-10-06 17:07 UTC, KorPhaeron commented
Stale

2016-10-06 17:07 UTC, closed without merging

2016-10-06 17:53 UTC, GunHog commented
# GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOF