Ties the new lawyer speech bubble to the attorney's badge [Needs icon]
tgstation/tgstation pull request #20733
Opened 2016-09-28 00:03 UTC by Incoming5643

So lawyers can disguise as non-lawyers and visa versa

Additional/replacement badges are found in the law closet

Needs an icon, badly. I tried to make my own and well... it was just not even salvageable.

![d10_icon](https://cloud.githubusercontent.com/assets/4176358/18896141/3fdf5dec-84ed-11e6-8b4a-5f2794a893c8.png)
(I know there's no shading, I _gave up_)

reference: <img src=http://vignette1.wikia.nocookie.net/aceattorney/images/f/fd/Aa5badge.png>

2016-09-28 01:06 UTC, WJohn commented
God that sprite is bad let me make one for you:
![](http://i.imgur.com/tURbxpt.png)

2016-09-28 01:18 UTC, PKPenguin321 commented
wj comes through

2016-09-28 01:19 UTC, lordpidey commented on code/modules/clothing/under/ties.dm
> +	user.bubble_icon = "lawyer"
Uhh, couple of problems I notice about this.

1.) You need to cast and check if user is null.
2.) Won't this change the voice bubble of the person who pins, not the person who is pinned (usually the same person, but not always)
3.) What if the shirt is pinned while not equipped?

2016-09-28 01:20 UTC, Incoming5643 commented on code/modules/clothing/under/ties.dm
> +	user.bubble_icon = "lawyer"
There's work to be done yes, I just lost hope until a sprite came throguh. I'll now go finish the pull.

2016-09-28 04:25 UTC, RemieRichards commented on code/modules/clothing/under/ties.dm
> +/obj/item/clothing/tie/lawyers_badge/process()
No, absolutely not.

2016-09-28 04:25 UTC, RemieRichards requested changes

2016-09-28 04:25 UTC, RemieRichards commented on code/modules/clothing/under/ties.dm
> +	var/obj/item/clothing/under/U = loc
No, absolutely not.

2016-09-28 05:11 UTC, optimumtact commented on code/modules/clothing/under/ties.dm
> +	user.bubble_icon = "lawyer"
if user is null at this point then something very bad has happened, as there are no sleeps between this and the parent call, which should be checking this

2016-09-28 05:37 UTC, Incoming5643 commented on code/modules/clothing/under/ties.dm
> +	var/obj/item/clothing/under/U = loc
99% of the time it will short out right below this line, is it really so costly? Accessory code isn't exactly amazing here.

2016-09-28 05:38 UTC, Incoming5643 commented on code/modules/clothing/under/ties.dm
> +	user.bubble_icon = "lawyer"
this code is already gone, don't panic about it.

Thanks github for showing it anyways,

2016-09-28 06:22 UTC, WJohn commented
Hold on I've gone and improved the sprite a bit since then. Would you mind using this version before I end up replacing it myself not a week later when I do over the bureaucracy dmi?
![](http://i.imgur.com/VIH3mlA.png)

2016-09-28 15:23 UTC, Incoming5643 commented
You got it

2016-09-30 17:02 UTC, Incoming5643 commented
@RemieRichards Removed the process() requirement a few days ago

2016-09-30 17:02 UTC, RemieRichards approved these changes

2016-09-30 17:08 UTC, Incoming5643 commented
Build fails but not due to this. Master is not compiling due to competing changes

2016-09-30 17:37 UTC, ChangelingRain commented on code/modules/clothing/under/ties.dm
> +	var/mob/living/L = U.loc
You're missing a line, here.

2016-09-30 17:40 UTC, Incoming5643 commented on code/modules/clothing/under/ties.dm
> +	var/mob/living/L = U.loc
Good catch. Somehow the terminal line was lost in the merge resolution. Been fixed.

2016-09-30 17:50 UTC, merged

2016-09-30 17:50 UTC, ChangelingRain commented
I hope this handles burning off and suchlike, hmmmmmmm

2016-09-30 17:53 UTC, Incoming5643 commented
Items don't traditionally burn from the inventory of a person. There's a few tricky ways to get a burning item in your hand but doing ANYTHING to it invites burn damage and drops it. In any case a burning uniform should be handled alright.

 A burning accessory that managed to be attached to a nonburning uniform might not be, but again this is a situation we don't actually allow.