Replaces OBLIGATION_DRINK with a much more appropriate fiddle reference
tgstation/tgstation pull request #20770
Opened 2016-09-30 21:53 UTC by lordpidey

:cl:
add: There is a new potential obligation for devils to have.  Musical duels.  Ask your nearest devil for a musical duel, there's a 14% chance he's obligated to do it.
del: Removed the old offering a drink obligation for devils, it overlapped too much with the food obligation.
tweak: Trying to clone people who've sold their soul now results in FUN.
tweak: Devils can no longer spam ghosts with revival contracts.
/:cl:

This changes a few minor things about devils.  Nothing gamechanging, but minor annoyances/glitches have been fixed.

Replaces OBLIGATION_DRINK with a much more appropriate fiddle reference
Attempting to clone soulsellers no longer works.  Fun things happen if you try.
Fireproof paper no longer becomes unreadable on burning.
Made a generic "Conjure item" spell as a superclass for the summon pitchforks.  These spells summon/unsummon an item directly into your hand.
You can no longer spam ghosts with the infernal revival contract.
Admins can now un-devil a devil, even AFTER they've become a third stage devil.

2016-10-01 08:29 UTC, lordpidey commented
Whoops, I've forgotten to include the new sprites for the fiddle.  I'll add those in the morning, don't merge until then.

2016-10-03 00:38 UTC, optimumtact commented on code/game/machinery/cloning.dm
> +	spawn(0)
just use add timer(0, "horrifyingsound", src) wherever you're calling this proc

2016-10-09 22:35 UTC, optimumtact commented on code/game/machinery/cloning.dm
> +	spawn(0)
hello

2016-10-09 22:41 UTC, lordpidey commented
Sorry, I've moved recently and not had a lot of free time.  I'll try to get to fixing the stuff.

2016-10-15 16:05 UTC, AnturK commented
@lordpidey Is this ready besides the conflicts ?

2016-10-15 18:46 UTC, lordpidey commented
Yeah, it's ready.  Sorry for taking so long with this.

2016-10-17 08:57 UTC, AnturK requested changes
Minor issues

2016-10-17 08:57 UTC, AnturK commented on code/game/machinery/cloning.dm
> +		user << "It's filled with blood and vicerea. You swear you can see it moving..."
viscera

2016-10-17 08:57 UTC, AnturK commented on code/modules/paperwork/paper.dm
> +/obj/item/weapon/paper/fire_act()
Keep the arguments consistent with the parent proc even if you're not using them please.

2016-10-17 08:57 UTC, AnturK commented on code/modules/spells/spell_types/devil.dm
> +	item_type = /obj/item/weapon/twohanded/pitchfork/demonic/
Remove the / at the end of the path please.

2016-10-17 22:12 UTC, optimumtact commented on code/game/machinery/cloning.dm
> +		user << "It's filled with blood and viscrea. You swear you can see it moving..."
viscera

2016-10-17 22:13 UTC, optimumtact commented on code/game/machinery/cloning.dm
> +		user << "It's filled with blood and viscrea. You swear you can see it moving..."
viscera

2016-10-17 22:45 UTC, PKPenguin321 commented on code/game/machinery/cloning.dm
> +		user << "It's filled with blood and viscrea. You swear you can see it moving..."
viscereal

2016-10-18 05:20 UTC, KingPhilipIII commented
Definitely approve with the pitchfork. I'd always summon it, then lose it for one reason or another, and it's gone.

2016-10-18 06:30 UTC, AnturK approved these changes

2016-10-18 06:45 UTC, merged

2016-10-18 11:00 UTC, lordpidey commented
That's how it worked before?  Press button -> It appears.  Press it again, it dissappears, press it again, it appears.

2016-10-18 11:08 UTC, KingPhilipIII commented
No. before if you lost it it never despawned until you changed form. Id lose my pitchfork as an arch devil and it would just be gone.

2016-10-18 11:12 UTC, KingPhilipIII commented
Another thing Pidey. If you're tweaking your antag, I personally love playing as a devil. It's loads of fun, and I've had some meaningful role play (I've convinced the HoS to sell his soul. No criminals can hide from X-ray cops.) but when the devil becomes a true or arch devil, they need to be able to control the spawn of imps or banish their imps with a command. Every time I ascend I have a horde of imps slaughtering everyone while asking for promotions even when I order them not to attack anyone who sold their souls, or on the occasion I promised not to harm the crew everyone. It's somewhat ridiculous.

2016-10-18 11:33 UTC, lordpidey commented
`/obj/effect/proc_holder/spell/targeted/summon_pitchfork/cast(list/targets, mob/user = usr)`
 	`if (pitchfork)`
 		`qdel(pitchfork)`
 	`else`
 		`for(var/mob/living/carbon/C in targets)`
 			`if(C.drop_item())`
 				`pitchfork = new pitchfork_type`
 				`C.put_in_hands(pitchfork)`

That's the old code.  Unless something is going wrong with the qdel, it SHOULD work.  If the pitchfork exists, destroy it, if it does NOT exist, put it in your hands.  THe only reason it should have failed before is if somehow both of your hands can't drop something.  I'll look into it.  But what you're describing isn't intended behavior.

2016-10-18 11:34 UTC, KingPhilipIII commented
I rarely summoned before becoming a true devil, at which point the crew becomes aggressive and I need to defend myself. Might have something to do with it.

2016-10-18 11:36 UTC, KingPhilipIII commented
I'd just lose it for some reason, resort to fireballing my attackers, and someone would charge me with my own pitchfork at which point I kill them and take it back or I click the button and it summons to my hand. I have no idea how it worked.

2016-10-18 13:09 UTC, lordpidey commented
I looked at the old code some more, and the new code is pretty similar, but it MIGHT fix the bug you are talking about.

I wasn't able to reproduce the bug on the old, or the new code, but I think adding the `item = null` line might fix it.  Time will tell.

2016-10-18 14:27 UTC, KingPhilipIII commented
Would the fact I was never actually a natural devil matter? Code makes zero sense to me, so it's probably irrelevant, Admins always made me one though.

2016-10-18 14:39 UTC, lordpidey commented
No.

Now that I think about it, the bug will only occur when the server is stressed, and the qdel system is delayed, which would explain why local tests didn't find it.

2016-10-18 15:46 UTC, KingPhilipIII commented
So. With my limited understanding of what you just said. The server relegated destruction of the pitchfork to a time where it was less stressed, and it basically ceased to exist. And then it searched for the wrong criteria onto whether or not it had destroyed the pitchfork?

2016-10-18 16:51 UTC, lordpidey commented
Yes, that's exactly it.

2016-10-18 16:52 UTC, KingPhilipIII commented
When I think about it. Four of the five times I ascended the station was on fire or half blown up or the engine had escaped. So that's a pretty logical conclusion.