Player simple animals no longer count as traitors
tgstation/tgstation pull request #20835
Opened 2016-10-05 19:38 UTC by ChangelingRain

IAN IS NOT A TRAITOR

2016-10-05 19:54 UTC, AnturK commented
Was going to revamp this anyway, i guess saves me work. Nothing checks for the special role on the constructs ?

2016-10-05 19:59 UTC, Supermichael777 commented
constructs are not followers and should not count for escape.

2016-10-05 20:38 UTC, AdamElTablawy commented
but now constructs can't use runes

2016-10-05 20:39 UTC, ChangelingRain commented
what the fuck are you talking about they're still cultists

2016-10-05 21:16 UTC, AdamElTablawy commented
you made their minds not cultist

2016-10-05 21:26 UTC, ChangelingRain commented
They're still cultists

2016-10-05 21:28 UTC, AdamElTablawy commented
doesn't this mean rat'var will win even more against nar'sie since constructs aren't initially ocunted as cult or

2016-10-05 21:29 UTC, ChangelingRain commented
theyre still cultists

2016-10-05 21:29 UTC, AdamElTablawy commented
but how

2016-10-05 21:30 UTC, ChangelingRain commented
their still cult

2016-10-05 21:47 UTC, AdamElTablawy commented
so just to clarify they're still cultists right

2016-10-05 22:01 UTC, ChangelingRain commented
yes

2016-10-05 23:22 UTC, PKPenguin321 commented
hi just popping in here to make sure this leaves constructs as cultists?

2016-10-05 23:23 UTC, ChangelingRain commented
ye

2016-10-05 23:31 UTC, AdamElTablawy commented
are you sure this leaves constructs as cultists because i don't think it leaves constructs as cultists

2016-10-05 23:31 UTC, ChangelingRain commented
y

2016-10-05 23:33 UTC, AdamElTablawy commented on code/datums/mind.dm
> -	mind.special_role = "Blob"
okay but more to the point does this leave constructs as cultists

2016-10-06 00:21 UTC, AdamElTablawy commented on code/datums/mind.dm
> -	mind.special_role = "Blob"
i'm assuming it doesn't

2016-10-06 03:11 UTC, Militaires commented
wait does this leave constructs as cultists?

i dont think so

2016-10-06 13:35 UTC, ghost requested changes
you should probably make constructs count as cultists

2016-10-06 13:35 UTC, AdamElTablawy commented on code/datums/mind.dm
> -/mob/living/simple_animal/hostile/construct/mind_initialize()
why did you make constructs not count as cultists again?

2016-10-07 12:11 UTC, Militaires commented on code/datums/mind.dm
> -/mob/living/simple_animal/hostile/construct/mind_initialize()
huh why dont they count as cultists they should count as cultists

2016-10-07 22:27 UTC, Supermichael777 commented
__**Test**__ if constructs need to count as cultists to fire runes, otherwise they should not.

The round should end when the last human cultist dies to avoid a juggernaut artificer pair bitching out in space.
Plus its extremely unlikely the cult can pull back with zero tomes and no good way to get them.

2016-10-08 19:51 UTC, AdamElTablawy commented
@Razharas constructs don't count as cultists tag please

2016-10-09 22:30 UTC, optimumtact commented
I'm merging this before someone adds more meme tags

2016-10-09 22:30 UTC, merged