Moves breathing from species to the lung organ
tgstation/tgstation pull request #20869
Opened 2016-10-08 23:03 UTC by Shadowlight213

:cl:
experiment: Breathing has been moved from species to the lung organ
add: Lung transplants are now possible!
/:cl:

2016-10-08 23:26 UTC, PKPenguin321 commented
Slightly related, we really really really need to refactor eye damage/color to be dependent on an eyes organ

2016-10-08 23:32 UTC, WJohn commented
Does this make it so if you transplant ashwalker lungs into yourself, you'll be able to breathe on lavaland without equipment?

2016-10-08 23:38 UTC, RemieRichards requested changes

2016-10-08 23:38 UTC, RemieRichards commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
false.

the ```H.internal_organs``` list will never contain the path ```/obj/item/organ/lungs```, or any paths at all for that matter!
It's a lit of objects.

2016-10-08 23:44 UTC, Shadowlight213 commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
Oh. I didn't know that didn't work with objects.

2016-10-08 23:45 UTC, RemieRichards commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
Well ```/obj/item/organ/lungs``` and an instantiated lung object are completely different.
that lung object's ```.type``` variable however is a 100% match for ```/obj/item/organ/lungs```

paths != objects

2016-10-08 23:46 UTC, Shadowlight213 commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
It would be `if(locate(/obj/item/organ/lungs) in H.internal_organs)` then, right?

2016-10-08 23:47 UTC, RemieRichards commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
yep yep

2016-10-08 23:50 UTC, Shadowlight213 commented
@WJohn actually, no.
Ash walkers have NOBREATH, which is still part of the species. I'm not sure if they even have lungs due to that.
I'm planning on adding N2 to the list of breathable gasses and have ashwalkers breath lavaland airmix in a later pr.
That was actually the original purpose of the pr (hence the branch name), but @phil235 asked me to move breathing to lungs, so I did that instead.

2016-10-09 00:51 UTC, GunHog commented
What lung types are there? Could I give a guy Xeno lungs for breathing plasma and removing the need for oxygen? Cybernetic lungs for immunity to toxic gasses? Plasmaman lungs for FORCING people to breathe plasma?

2016-10-09 02:33 UTC, Shadowlight213 commented
@GunHog 
If you made subtypes, yes.
At the moment, the lungs set their vars based off of the species where they originated from.
Also, I don't think xeno lungs work with this system. They have separate breathing code.

2016-10-09 16:58 UTC, FantasticFwoosh commented
If you steal ashwalker/golem lungs, and aug a body, then suppliment a heat gene you are effectively space proof when revived from practically any condition of death with strange reagent.

This is a slightly better alternative to reattaching to a ashwalker torso, and will fuel my surgeon experiments.

2016-10-09 17:32 UTC, PKPenguin321 commented
You don't need augs to space proof, cold res handles pressure resistance

2016-10-10 02:44 UTC, Shadowlight213 commented on code/modules/station_goals/dna_vault.dm
> +			if(/obj/item/organ/lungs in H.internal_organs)
@RemieRichards k. I fixed it.

2016-10-10 02:46 UTC, RemieRichards approved these changes

2016-10-10 09:29 UTC, FantasticFwoosh commented
Double checked, ashwalkers and NOBREATHE related races have their lungs qdeleted in the code.

So no-breathe transplanted lungs are currently impossible without badminnery to restore said lungs and assign them to the owner.

2016-10-10 12:33 UTC, coiax commented
I specifically did the NOBREATH species having no lungs, because it made no sense for golems and skeletons to have a set of lungs. If ashwalkers are being switched to a lavaland gas mixture, then they won't be NOBREATH anymore.

2016-10-10 13:42 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +		if(istype(L,/obj/item/organ/lungs))
people can have an organ in the lung slot that isn't /obj/item/organ/lungs ??

2016-10-10 15:41 UTC, Shadowlight213 commented on code/modules/mob/living/carbon/human/life.dm
> +		if(istype(L,/obj/item/organ/lungs))
Badmins? Idk.
I just like to do an istype before casting stuff, just in case.
Should I remove this check then?

2016-10-10 16:12 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +		if(istype(L,/obj/item/organ/lungs))
Well, I don't really see what admins could use a non lung organ in the lung slot for. But I guess it prevents potential runtimes, so let's keep it.

2016-10-11 01:14 UTC, nullbear commented
I cant wait for the entire server to die of suffocation within 3 minutes of starting the round if this bugs out.

2016-10-11 02:08 UTC, Shadowlight213 commented
I tested it. it works fine

2016-10-11 02:26 UTC, PKPenguin321 commented
famous last words

2016-10-12 01:24 UTC, Razharas commented
>First step in porting all the species behaviour to organs

Wonderful

2016-10-12 01:25 UTC, RemieRichards commented
>First Step
>Probably the 3 or 4th time functionality has been moved to an organ


HMMMMMMM.

2016-10-12 01:25 UTC, Razharas approved these changes
Moving stuff from mobs\species to organs is the goal

2016-10-12 01:26 UTC, Razharas commented
Thats the first one i see so its first for me

2016-10-12 02:44 UTC, optimumtact commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
there's no point in checking this because NOBREATH species will have no lungs and this line will never be reached if that is the case.

2016-10-12 12:19 UTC, Anonmare commented
I'm hopeful for this PR

2016-10-12 15:17 UTC, Shadowlight213 commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
removed

2016-10-12 15:55 UTC, phil235 commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
what if you insert lungs into a human with NOBREATH?

2016-10-12 17:08 UTC, Shadowlight213 commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
I dunno. Haven't tested it post check removal yet.
I'd assume either the check in the species would make them still not breath, or they would need to breath.

2016-10-12 18:24 UTC, Razharas commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
Things with nobreath shouldnt even try to call their lungs procs
Thus inserting lungs into them should be as impactful as inserting a bike horn into their cavity

2016-10-12 19:53 UTC, optimumtact commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
Well there is what *should* happen and then what the code actually does, so you would need to check.

2016-10-19 16:29 UTC, Shadowlight213 commented on code/modules/surgery/organs/organ_internal.dm
> +	if(breath && !(NOBREATH in specflags))	// If there's some other shit in the air lets deal with it here.
Ok, tested it. If the species has nobreath, they basically skip breathe(), and don't call check_breath() which is where the lung code is.
So they don't breathe if you transplant lungs into them.

2016-10-20 02:49 UTC, Shadowlight213 commented
@phil235 I did the change you suggested, but now the lungs aren't spawning in humans.
I cant figure out what I did wrong, ahhhhhhhh!

2016-10-20 11:24 UTC, phil235 commented on code/modules/mob/living/carbon/human/human.dm
> +			internal_organs += new /obj/item/organ/lungs
()

2016-10-20 11:25 UTC, phil235 commented on code/modules/mob/living/carbon/human/human.dm
> +			internal_organs += new /obj/item/organ/lungs
()

2016-10-20 11:26 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +			else if(S.breathid = "co2")
==

2016-10-20 11:26 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +			else if(S.breathid = "tox")
==

2016-10-20 11:26 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +			if(S.breathid = "o2")
==

2016-10-20 11:28 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +			else if(S.breathid = "tox")
==

2016-10-20 11:28 UTC, phil235 commented on code/modules/mob/living/carbon/human/life.dm
> +			if(S.breathid = "o2")
==

2016-10-20 15:40 UTC, Shadowlight213 commented
Compiles now. lungs still not spawning ;_;
So confused as to what I'm doing wrong.

2016-10-20 17:29 UTC, phil235 commented
Manually calling create_internal_organs() gives lungs, and adminspawned humans correctly have lungs. So it's only happening when players are first spawned by the game, or when they join the game.

2016-10-21 16:34 UTC, merged