Hardlight Bows
tgstation/tgstation pull request #20944
Opened 2016-10-12 09:33 UTC by kevinz000

Adds hardlight bows and hardlight quivers.
Does 20 brute, and 10 burn on hit.
The quivers regenerate one arrow every few seconds and is worn on the back.
Arrows disintegrate on hit and are destroyed after 20 seconds if it is dropped to prevent spam.
http://imgur.com/a/932lN 
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=8163&sid=12160c77258df6679a0f36e9ce38d692#p217519
Sprites by the amazing @Lexorion 
:cl:
rscadd: Adds a hardlight bow and hardlight quiver that do 20 brute and 10 burn on impact, and regenerates an arrow every few seconds for the quiver.
\:cl:

2016-10-12 09:34 UTC, optimumtact commented
GET ON THEME

2016-10-12 09:45 UTC, AnturK requested changes

2016-10-12 09:45 UTC, AnturK commented on code/modules/projectiles/guns/projectile/bow.dm
> +		spawn(draw_time)
This does nothing here so probably not what you intended to do. Ideally use do_after here so the bar shows up.

2016-10-12 09:45 UTC, AnturK commented on code/modules/projectiles/guns/projectile/bow.dm
> +		spawn(draw_time)
Same as above.

2016-10-12 09:45 UTC, AnturK commented on code/modules/projectiles/guns/projectile/bow.dm
> +	addtimer(src, "Destroy", 200)
We have a helper for this. qdel_in(src,200)

2016-10-12 11:00 UTC, Lexorion commented
![tw1yrcm](https://cloud.githubusercontent.com/assets/13591098/19307643/dd57f248-907b-11e6-9059-642489d21c73.png)
Pic from the forum

2016-10-12 12:52 UTC, kevinz000 commented on code/modules/projectiles/guns/projectile/bow.dm
> +		count++
Uh, for quivers as a whole? Because the normal one has no need to track arrow amounts

2016-10-12 14:45 UTC, phil235 commented on code/modules/projectiles/guns/projectile/bow.dm
> +		count++
make it use a var, we're not going to do an istype on every single arrow in the quiver to count them, it's tedious.

2016-10-12 16:11 UTC, Iamgoofball commented on code/modules/projectiles/guns/projectile/bow.dm
> +		count++
or contents.len

2016-10-12 18:20 UTC, xxalpha commented
>get on theme

Remove bone spears and medieval bows, first. At least this pretends to be sci-fi.

2016-10-12 22:48 UTC, Cheridan commented
This isn't scifi at all you mong, it's horrible sci-fantasy shit like Jupiter Ascending.

2016-10-12 23:20 UTC, TechnoAlchemisto commented
hardlight is apex pseudo sci-fi and I fully support it

2016-10-12 23:36 UTC, Cheridan commented
![sci fantasy](https://cloud.githubusercontent.com/assets/3827314/19331459/910ffb18-90aa-11e6-9b20-056e76a1fbdd.jpg)

WHEE MR RABBIT LETS RIDE THE SHLOCK BIKE OFF TO WORST-FUCKING-GENRE-EVERVILLE 
WE CAN TALK TO GEORGE FUCKING LUCAS ALONG THE WAY

2016-10-12 23:37 UTC, optimumtact commented
I'm with cheridan

2016-10-12 23:39 UTC, TechnoAlchemisto commented
how does she breath underwater

2016-10-13 01:06 UTC, Cheridan commented
how do you shoot an arrow with a laser?? who cares, it's fantasy!

2016-10-13 04:12 UTC, kevinz000 commented on code/modules/projectiles/guns/projectile/bow.dm
> +	addtimer(src, "Destroy", 200)
fixed

2016-10-13 04:12 UTC, kevinz000 commented on code/modules/projectiles/guns/projectile/bow.dm
> +		spawn(draw_time)
removed

2016-10-13 04:12 UTC, kevinz000 commented on code/modules/projectiles/guns/projectile/bow.dm
> +		spawn(draw_time)
removed

2016-10-13 04:58 UTC, Lexorion commented
But it's not laser, it's hardlight and cold , in games like Halo you can walk over bridges made out of it without any problems.

2016-10-13 07:16 UTC, kevinz000 commented
Requesting testmerge. :3

2016-10-13 18:22 UTC, Durkel commented
I don't like this, it just seems silly, no one in their right mind is going to use a bow and arrow in the future when you can just pull a trigger. We're also going down a dangerous path if we start including "hardlight" shit, because you can make literally anything out of that and bullshit it off as it being the "future".

2016-10-13 19:06 UTC, Lexorion commented
Why "dangerous path"? We already have e-(cross)bows,e-swords and e-shields but a different approach on something quite similar is suddenly bad and 100% not fitting? I mean yes,you *could* make a hardlight variant for that sort of stuff but I can't think of anything else plus they are not that different,e.g. the "energy" shield doesn't burn you/others and is solid so wouldn't that basically make it hardlight or atleast something fairly similar to it?

2016-10-13 20:19 UTC, optimumtact commented
We have previous mistakes, but you don't keep crashing your car into things just because you have a few previous dents.

2016-10-14 00:37 UTC, kevinz000 commented
... that's a really harsh way to put it @optimumtact

2016-10-14 04:35 UTC, Bawhoppen commented
only problem with this is that its available for syndicks

2016-10-14 05:59 UTC, nullbear commented
I see nothing wrong with the 'hardlight' aspect of this (and in other PR's). It has good gameplay applications. If you want to argue that it's not hard-sci-fi, you can pretty easily pull-shit-out-of-your-ass to explain that away anyways. 

(IE. it is made up of: compressible ferrous semiconductive aerogel particles with electric and electromagnetic properties. IE: The particles can be held in a specific magnetic field, causing it to fluoresce, and making it appear to hold a solid form in unique and useful shapes + it's ultralight + it doesn't take up any space when inactive + it's ultrasharp/forceful + self-healing/immune to damage (since it's made up of particles which are NOT chemically bonded to eachother.))

Having the BOW as a weapon is no better or worse than the pneumatic cannon. It's a gimmick weapon who's only purpose is to fill a role as a weapon through interesting/unique mechanics. Should it be seen frequently in the game? No. It fits much better in the sci-fi role than your uh... medieval bows. And appears to be quite a bit more fleshed out as well. 

I personally see it as kind of the same way as hunters who use compound bows. It's a modernized archaic weapon that is 'worse' than the modern weapon (guns.) but offers an alternative method of hunting which is definitely more interesting, and challenging. IRL: bows are silent, and the projectiles arc. 

The only basis i can see this PR being denied on is on HOW the bow is introduced and made available. Should it be available to syndicates? No. Would it make an interesting ruin/megafauna loot? For sure, and it's better than angel wings or drake blood in regards to the theme to boot.

2016-10-14 06:18 UTC, AnturK approved these changes

2016-10-14 17:54 UTC, xxalpha commented
We added caveman bone spears and medieval wooden bows not that long ago, I just want to point out that again.

2016-10-15 16:08 UTC, KorPhaeron commented
>spears aren't realistic or scientific for tribal people to be using

?

2016-10-15 18:15 UTC, Durkel commented
Bows shouldn't have been added, the pneumatic cannon is a balance nightmare and can crit someone in one hit, Just because dumb shit slips by doesn't mean we should keep adding more. And pointy sticks are always going to be a thing, not even the future can change that. Just because something is coded and can be added to the game doesn't mean it should be, you should ask the questions of : "what will this do", "what will its impact be" and "Do we really need this". 

Traitor items are already bloated with gimmick shit that's rarely picked if not for a surplus crate, Do we really need more?

2016-10-16 04:46 UTC, kevinz000 commented
good thing this is a viable weapon and not a gimmicky shit right
Oh yeah, should I make this deal full damage to lavaland mobs
Might be useful for lavaland if somehow this doesn't make it into traitor stuff :^)

2016-10-17 13:25 UTC, Cheridan commented
Gritty tribal weapons are more on-theme for SS13 than laserstring tekbows.

2016-10-17 21:22 UTC, ExcessiveUseOfCobblestone commented
that bunny is pretty cute though cheri...

2016-10-25 19:46 UTC, Hatfish commented
Why are demons and magical bullshit allowed but this is somehow going over the line?

2016-10-26 05:06 UTC, optimumtact commented
because the source for this particular lore is garbage

2016-10-26 20:56 UTC, xxalpha commented
So is Dead Space tbh.

2016-10-27 00:44 UTC, KorPhaeron commented
@Hatfish 

A wizard getting a new magical whatever makes sense for the wizard, thats internal consistency and theme for the faction.

The captain suddenly getting a magic wand would be silly.

And similarly, it's a bit odd that the syndicate, which relies on old solid projectile weapons, would have something way more advanced than NT does

2016-10-27 01:36 UTC, PKPenguin321 commented
Maybe swap out R&D energy crossbow with this?

2016-10-27 03:16 UTC, kevinz000 commented
^ that'd honestly nerf R&D as this 1. can't stunlock 2. has to be back-worn or inhand-held because it's a large item.

2016-10-27 06:36 UTC, PKPenguin321 commented
Sounds good, do it

2016-10-27 07:49 UTC, optimumtact commented
sounds okay to me

2016-10-27 12:10 UTC, Bawhoppen commented
I vote for nerfing R&D while also giving it a more thematic and unique weapon whilst removing a duplicate mechanic weapon simultaneously

2016-10-27 15:41 UTC, nullbear commented
Why is this still open geez it's been like a month

2016-10-27 16:50 UTC, xxalpha commented
@KorPhaeron can't use that as an argument as we have let security have bullets already.

2016-10-27 19:58 UTC, optimumtact commented
Replace the R&D energy crossbow with this and I will pull it.

2016-10-28 00:22 UTC, kevinz000 commented
Oh
Man
You're driving a hard bargain sir
UHHHh how about if this is attachable to the quiver so you don't have to hold it and wear the quiver and instead you can wear both on your back?

2016-10-28 00:26 UTC, PKPenguin321 commented
>it's a science item now

>okay uh how about we buff it?

l o l

2016-10-28 00:27 UTC, optimumtact commented
OOC: Dutch Blitz: Tell oranges he can have my hardlight

2016-10-28 00:28 UTC, kevinz000 commented
WTF

2016-10-28 00:30 UTC, optimumtact commented
No buffs kevzzzzzzzz it's fine as it is

2016-10-28 01:01 UTC, PKPenguin321 commented on code/modules/research/designs/weapon_designs.dm
> +/* Fruits won.
ooc in code ban he

2016-10-28 01:16 UTC, merged