Adds a new contraband crate to cargo
tgstation/tgstation pull request #21178
Opened 2016-10-24 19:50 UTC by Tacolizard

:cl: 
add: Added a new contraband crate to cargo, the ATV crate.
/:cl:

the new crate requires and emagged/multitooled cargo console and costs 2000 credits.
it contains an ATV and a key.

2016-10-24 19:51 UTC, TehZombehz commented
Only 2000?

2016-10-24 20:00 UTC, Tacolizard commented
@TehZombehz most contraband crates are pretty expensive, and considering the fact that only one person can use the atv, i settled on 2000. i am open to suggestions.

2016-10-24 21:10 UTC, ExcessiveUseOfCobblestone commented
does the atv even do anything?

2016-10-24 21:11 UTC, PKPenguin321 commented
It is basically a faster scooter that needs a key I think

2016-10-24 22:23 UTC, ExcessiveUseOfCobblestone commented
didn't it have a use for a certain tile on the snow mission?

2016-10-25 14:48 UTC, Tacolizard commented
so uh merge or no merge @Cheridan @optimumtact

2016-10-25 15:13 UTC, Shadowlight213 commented
@Tacolizard the minimum amount of time a pr needs to be open before a merge is 24 hours. It's only been 19.

2016-10-25 16:52 UTC, Tacolizard commented
ok i literally didnt even know that was a rule, thanks @Shadowlight213

2016-10-25 18:05 UTC, ExcessiveUseOfCobblestone requested changes

2016-10-25 20:00 UTC, Tacolizard commented on code/modules/cargo/packs.dm
> +	cost = 2000
i really wanna keep it cheap because it only has one ATV and greytiders everywhere will foam at the mouth when they see it.

2016-10-25 20:02 UTC, Tacolizard commented
ok it's done. 3000 credits is the new cost.

2016-10-25 23:37 UTC, MimicFaux commented
Cargonia bikergangs when?

2016-10-26 03:03 UTC, Tacolizard commented
@optimumtact @Shadowlight213 @Cheridan 

**merge my meme ples?**

2016-10-26 03:17 UTC, optimumtact commented
stop mergebegging, it only makes us hold your pr until even more time has elapsed.

We'll get to it when we can

2016-10-26 04:23 UTC, Tacolizard commented
@optimumtact thats mean

2016-10-26 05:41 UTC, AdamElTablawy commented
i cant wait to drive around on my atv as a gangster pulling drivebys on the hos with my uzi

but also you might wanna consider how relatively cheap this is, it'd be a staple order for any antag cargo

2016-10-26 05:43 UTC, optimumtact commented
Every time you ping me I'm adding 24 hours to before I even bother looking at this.

This is a volunteer project, people will get to your pr when they can, hounding them about it will not help

2016-10-26 14:56 UTC, Shadowlight213 commented
Closed for mergebegging meme

2016-10-26 15:03 UTC, Iamgoofball commented
Just wait for the first merge conflict THEN fix and merge beg

2016-10-26 16:36 UTC, Cheridan commented
of all the dumb crap cargo can buy, THIS is super-expensive and contraband? 
can't you make a scooter that does the same thing for free?

2016-10-26 17:45 UTC, Iamgoofball commented
This is faster

2016-10-26 17:46 UTC, Iamgoofball commented
And it negates slowdown from damage

2016-10-26 23:35 UTC, Tacolizard commented
@Cheridan the price was at 2000, i could put it back if this is too expensive. it's only contraband because it would be weird for stations to be able to buy atvs for no reason.

2016-10-27 20:12 UTC, Cheridan commented
I guess that makes sense

2016-10-27 20:12 UTC, merged