WIP Hatchet = navajo tomahawk
tgstation/tgstation pull request #21185
Opened 2016-10-25 15:18 UTC by Tacolizard

this is my first pr involving real coding and i need to go in a sec so wip and the code is probs shite

2016-10-25 15:52 UTC, XDTM commented
Botanists can finally show off their true roots

2016-10-25 15:55 UTC, ma44 commented
_Deep breathing_

2016-10-25 16:03 UTC, XDTM commented
Status is a var to check if stunbatons are on, you shouldn't check for it in hatchets.

2016-10-25 16:45 UTC, Tacolizard commented
i had an idea. I wanna make it so you can set a warcry like the explosive lance.

2016-10-25 17:21 UTC, TechnoAlchemisto commented
Giving these a weaken is way too good considering how easy they are to snag

2016-10-25 18:07 UTC, ExcessiveUseOfCobblestone commented
Sprite?

2016-10-25 18:14 UTC, ExcessiveUseOfCobblestone requested changes

2016-10-25 18:14 UTC, ExcessiveUseOfCobblestone commented on code/modules/hydroponics/hydroitemdefines.dm
> +	origin_tech = "materials=2;combat=3"
excuse you

2016-10-25 18:27 UTC, PKPenguin321 commented
Thrown weakens are already too widespread as it is. :-1: Way too huge of a buff

2016-10-25 18:28 UTC, PKPenguin321 commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(3)
I'm not sure you realize how fucking ridiculous this is

2016-10-25 19:27 UTC, ExcessiveUseOfCobblestone commented
botany powercreep 😉

2016-10-25 19:32 UTC, Tacolizard commented
@PKPenguin321 i know it's powerful. i willing to compromise to get this merged. if you would like this nerfed, please suggest an alternative.

2016-10-25 19:49 UTC, Tacolizard commented
@PKPenguin321 according to [https://tgstation13.org/wiki/Guide_to_Combat#Defense](url) there aren't many thrown weakens. and the stunbaton only has a 35 percent chance of a thrown weaken.

2016-10-25 19:50 UTC, Tacolizard commented
also i have lowered all the stuns and damage a bit

2016-10-25 19:58 UTC, Tacolizard commented
kek. i just fixed it f

2016-10-25 20:00 UTC, TechnoAlchemisto commented
They shouldn't have a stun at all, really.

2016-10-25 20:01 UTC, optimumtact commented
This is unlikely to get merged as it is a ranged stun, and please stop closing and reopening your pr's

2016-10-25 20:03 UTC, Tacolizard commented
@optimumtact sorry i was making a comment and accidentally clicked the close and comment button.  
also when you and @TechnoAlchemisto say no stun at all do you mean no stun or no weaken?

2016-10-25 20:06 UTC, optimumtact commented
they acheive the same goal really

2016-10-25 20:50 UTC, XDTM commented
Use weaken so they fall down, instead of standing stunned on foot.
I think you could raise embedded_impact_pain_multiplier a bit, it's basically removing your weapon when you embed it after all. For reference, the spear has it at 3, which multiplied by the w_class (4) deals 12 extra damage and requires no autolathe to make.

2016-10-25 20:53 UTC, TechnoAlchemisto commented
Except spears can't be stored in your pocket or in your backpack, easily accessible pocket stuns are bad

2016-10-25 22:47 UTC, Tacolizard commented
@XDTM i really couldn't agree with you more, this is not overpowered at all

@TechnoAlchemisto you can literally build a spear in the permabrig, they're so easy to make. And that's a weapon with the power to break down doors and destroy shit. Only two hatchets spawn on box roundstart, others would need to be autolathed. And the hatchet would still be less powerful than the spear.

2016-10-25 22:51 UTC, Tacolizard commented
new changes:

force lowered from 12 to 10
throwforce increased from 18 to 20
embed chance lowered from 75 to 50 (still unsure where exactly this should be set)
embed pain multiplier increased from 2 to 4

2016-10-25 23:07 UTC, TechnoAlchemisto commented
Last time I checked there weren't cable coils in perma, but whatever.

The stun is the problem, if you want to make hatchets better just up their force, it makes sense for them to be good weapons.

2016-10-25 23:44 UTC, Tacolizard commented
@TechnoAlchemisto cultivator to break reinforced glass pane, use metal rod to break machinery such as seed harvestors, collect coil.

2016-10-26 00:31 UTC, PKPenguin321 commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
this absolutely needs to not weaken. this is way, way too good. thrown shit bypasses any defense including shields, dual eswords, etc and is super hard to dodge.

2016-10-26 00:50 UTC, Iamgoofball commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
You see how it checks shields above

2016-10-26 00:52 UTC, PKPenguin321 commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
still its ridiculously good, this and a bola for example is basically a free kill with minimal effort in collecting weapons

2016-10-26 01:49 UTC, Tacolizard commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
well you loose the weapon when it embeds so you can only stun once

2016-10-26 02:11 UTC, PKPenguin321 commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
it's free as in with other stuns they require some effort to acquire, i think one or two of these are in the garden roundstart for literally any powergamer to pocket and botanists have like 4 in the back for free

2016-10-26 02:11 UTC, PKPenguin321 commented
Very strongly opposed

2016-10-26 03:02 UTC, Tacolizard commented on code/modules/hydroponics/hydroitemdefines.dm
> +	L.Weaken(2)
only one is in the garden and the botanists only have two

2016-10-26 04:45 UTC, drynwyn commented
With PK on this. A thrown stun is way too powerful. Just make it do good damage with a high embed chance.

2016-10-26 05:39 UTC, AdamElTablawy commented
oh boy another good reason not to buy a throwing weapon kit because hatchets will basically do the same job and aren't illegal

Hmmmm

Tbh i'd say lower damage and change any form of stun to increased bleeding

Perhaps have it do more damage on targets in red health when thrown, so that you can finish off a fleeing enemy with a thrown hatchet, but not use them as a default god tier weapon

2016-10-26 09:01 UTC, FantasticFwoosh commented
***cough*** ashwalker navajo viva 2k16 bone tomahawks when? ***cough***

2016-10-26 15:05 UTC, Iamgoofball commented
Yeah, focus more on the embed

2016-10-26 15:15 UTC, ExcessiveUseOfCobblestone commented
at what point does the sexy [but frowned upon] native american costumes come out?

2016-10-26 16:52 UTC, Cheridan commented
Don't merge this as long as it stuns

2016-10-26 23:32 UTC, Tacolizard commented
@Cheridan what about if the the weaken is replaced with a one second stun. (you stay standing)

2016-10-26 23:57 UTC, Iamgoofball commented
Sounds good

2016-10-27 01:36 UTC, PKPenguin321 commented
Stun is just a weaken with less visual feedback that doesn't make you immune to lasers being shot over you

2016-10-27 02:12 UTC, Tacolizard commented
@PKPenguin321 yeah but it only lasts 1 second so it's just for dramatic effect, dosn't really do much

2016-10-29 00:42 UTC, closed without merging