Your periodic grammar PR
tgstation/tgstation pull request #21198
Opened 2016-10-26 05:12 UTC by bgobandit

Fixes https://github.com/tgstation/tgstation/issues/21193.

2016-10-26 06:04 UTC, Cyberboss requested changes

2016-10-26 06:04 UTC, CyberbossJHCB commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
Excuse me?

2016-10-26 06:24 UTC, bgobandit commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
what

2016-10-26 06:25 UTC, CyberbossJHCB commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
dat backslash

2016-10-26 06:38 UTC, bgobandit commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
http://www.byond.com/docs/guide/chap11.html#TextMacros

2016-10-26 17:33 UTC, bgobandit commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
based on the issue previously, it obviously doesn't

2016-10-26 20:38 UTC, PKPenguin321 commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
In my experience, calling src in a message either includes "the" or doesn't depending on the object. \the covers both cases and appends a the if one doesn't exist in src, but excludes it if one does. This should work fine.

2016-10-27 04:40 UTC, ShadowDeath6 commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
aren't you supposed to put /improper before the item's name in the actual item's define for it to say the Capitalized Item?

2016-10-27 15:41 UTC, ChangelingRain commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
if it's capitalized, [src] doesn't add a 'the' but that's because it observes PROPER GRAMMAR RULES FOR PROPER NOUNS

2016-10-27 18:18 UTC, CyberbossJHCB commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
Then the real issue is the tool should be named '*The* Jaws of Life' right?

2016-10-27 18:22 UTC, ShadowDeath6 commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
/improper Jaws of Life

2016-10-28 01:09 UTC, ChangelingRain commented on code/game/objects/items/weapons/tools.dm
> +	user.visible_message("<span class='suicide'>[user] is wrapping \the [src] around [user.p_their()] neck. It looks like [user.p_theyre()] trying to rip [user.p_their()] head off!</span>")
or not capitalized if it's not actually proper, because we near-universally don't capitalize items

2016-10-28 22:32 UTC, merged