Adds a new lobby sound.
tgstation/tgstation pull request #21304
Opened 2016-10-31 04:41 UTC by Iamgoofball

It's a surprise! I'm gonna go make a sandwich now. Thanks a lot, bye-bye.

2016-10-31 04:48 UTC, PKPenguin321 commented
[i_did_not_grief_them.ogg](http://puu.sh/s1qJc/02ed6c6ce6.mp3)

2016-10-31 04:57 UTC, JJRcop requested changes
You added it to the round end sounds instead of the lobby sounds. I do like the music, though.

2016-10-31 04:57 UTC, JJRcop commented on code/world.dm
> +			world << sound(pick('sound/AI/newroundsexy.ogg','sound/misc/apcdestroyed.ogg','sound/misc/bangindonk.ogg','sound/misc/leavingtg.ogg', 'sound/misc/its_only_game.ogg', 'sound/misc/i_did_not_grief_th
Wrong list.
[/code/controllers/subsystem/ticker.dm:61](https://github.com/tgstation/tgstation/blob/aac8757b644414514fc1053d758d2fbc587d05a8/code/controllers/subsystem/ticker.dm#L61)

2016-10-31 04:57 UTC, Iamgoofball commented on code/world.dm
> +			world << sound(pick('sound/AI/newroundsexy.ogg','sound/misc/apcdestroyed.ogg','sound/misc/bangindonk.ogg','sound/misc/leavingtg.ogg', 'sound/misc/its_only_game.ogg', 'sound/misc/i_did_not_grief_th
sdfasdfsdfjasdfhsdfa

2016-10-31 13:23 UTC, Bawhoppen commented
Make a changelog and use the rare sound tag ❕ ❕ ❕ ❕ ❕ ❕ ❕ ❕ ❕

2016-10-31 22:04 UTC, lordpidey commented
I've heard this before, but can't remember where for the life of me.

2016-10-31 23:47 UTC, Dorsisdwarf commented
eh

2016-11-01 00:41 UTC, PKPenguin321 commented
not super fond of this myself, too ambient

2016-11-01 15:18 UTC, ExcessiveUseOfCobblestone commented
> Not muting the lobby sound so you can hear the midi of the round

2016-11-02 03:18 UTC, optimumtact commented
Copyright status?

2016-11-02 06:03 UTC, Iamgoofball commented
@optimumtact The record company listed as the label (TPW Records) doesn't seem to actually exist. I've got no fucking clue.

2016-11-02 08:24 UTC, merged