Fixes transit tubes
tgstation/tgstation pull request #21342
Opened 2016-11-03 01:33 UTC by phil235

Fixes #21137

2016-11-03 02:03 UTC, duncathan requested changes
About time somebody freed us from the awful practice of using icon states as types

2016-11-03 02:03 UTC, duncathan commented on code/game/machinery/pipe/pipe_dispenser.dm
> +				if(7)
defines

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +//phil235 remember to update the maps!
To-do? Forgot to remove?

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +//				create_decorative_tube(direction ^ 3, SOUTH)
Why not just remove?

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +					create_decorative_tube(direction ^ 12, EAST)
Are these two lines indented once too many?

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +					create_decorative_tube(direction ^ 12, EAST)
Are these two lines and the `else` below indented once too many?

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +	dir = 8
Use the cardinal defines

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube_construction.dm
> +	icon_state = "straight" //icon_state decides which tube will be built
This comment is no longer accurate

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube_construction.dm
> +			cur_flip = !cur_flip
could condense these three lines into `var/cur_flip = initial(flipped) ? !flipped : flipped` but it's not a big deal

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube_construction.dm
>  	else
You can remove the else since it returns in the if

2016-11-03 02:03 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
>  	//  SS13.
I should probably update this lol
Want me to make a pr to your branch for this? It'll be quick and simple

2016-11-03 02:12 UTC, phil235 commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +//				create_decorative_tube(direction ^ 3, SOUTH)
forgot to remove it.

2016-11-03 02:12 UTC, phil235 commented on code/game/objects/structures/transit_tubes/transit_tube.dm
> +					create_decorative_tube(direction ^ 12, EAST)
no, it's intentional

2016-11-03 02:13 UTC, phil235 commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
>  	//  SS13.
update the comment? Sure go ahead.

2016-11-03 02:16 UTC, duncathan commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
>  	//  SS13.
sorry I meant update the gas sharing cuz this one decided to go super snowflake for no reason

2016-11-03 04:28 UTC, kevinz000 commented
Please make diagonal tubes with crossing AKA doesn't block the way when I try to make diagonals in hallways.

2016-11-03 06:26 UTC, XDTM commented
If they're not horrible anymore could we have them on the RPD?

2016-11-03 17:31 UTC, phil235 commented on _maps/map_files/PubbyStation/PubbyStation.dmm
> +	network = list("MiniSat")
whyyyy, I didn't touch this...

2016-11-03 18:15 UTC, phil235 commented on code/game/objects/structures/transit_tubes/transit_tube_construction.dm
> -/obj/structure/c_transit_tube/verb/rotate_ccw()
removed the ccw rotate verb, we don't need two verbs...

2016-11-03 18:43 UTC, phil235 commented
>If they're not horrible anymore could we have them on the RPD?

For another PR

2016-11-04 18:14 UTC, phil235 commented
PR is ready, except for the changes @duncathan wants to make themself.

2016-11-05 22:21 UTC, merged