disposal unit now uses a tgui
tgstation/tgstation pull request #21702
Opened 2016-11-23 08:18 UTC by Mervill

:cl: Mervill
imageadd: Disposal units now use a tgui instead of plain html
/:cl:

![](http://i.imgur.com/re2N2ue.png)

![](http://i.imgur.com/JkymseQ.png)

2016-11-23 10:40 UTC, GunHog commented
Lovely! Btw, can I still engage the handle while I am in the process of climbing in, thus allowing me to flush myself? It is akin to pushing the handle down with your foot before jumping in completely.

2016-11-23 11:08 UTC, AnturK commented on code/modules/recycling/disposal-unit.dm
> +	if(user.loc == src)
You might want to use the specific ui_state instead here.

2016-11-23 11:08 UTC, AnturK commented on code/modules/recycling/disposal-unit.dm
> +	data["si"] = issilicon(user) && !iscyborg(usr)
usr => user

2016-11-23 12:23 UTC, Niknakflak commented
Just another to lag as I try to open it

2016-11-23 16:37 UTC, Mervill commented
@GunHog Yes

2016-11-23 16:38 UTC, Mervill commented on code/modules/recycling/disposal-unit.dm
> +	data["si"] = issilicon(user) && !iscyborg(usr)
Good catch

2016-11-23 16:46 UTC, Mervill commented on code/modules/recycling/disposal-unit.dm
> +	if(user.loc == src)
I'm not sure what you mean?

2016-11-23 17:00 UTC, Cyberboss requested changes

2016-11-23 17:00 UTC, Cyberboss commented on code/modules/recycling/disposal-unit.dm
> +	data["si"] = issilicon(user) && !iscyborg(usr)
isAI(user)

2016-11-24 00:11 UTC, Incoming5643 commented
I agree with niknak, these are too important in a time sensitive situation (self disposaling in a fight) to be laggy.

2016-11-24 00:16 UTC, Mervill commented
@Incoming5643 I doubt this will introduce any noticeable latency. Compare to the fire alarm (also a t-gui)

2016-11-24 00:17 UTC, Mervill commented on code/modules/recycling/disposal-unit.dm
> +	if(user.loc == src)
are you referring to `datum/ui_state/state = default_state`?

2016-11-24 21:04 UTC, Mervill commented
reeeeee (et cetera)

Will resolve when I get home

2016-11-25 02:54 UTC, merged

2016-11-25 02:54 UTC, optimumtact commented
The people with toasters from 2001 will be left to die