Lollipops, gumballs, and a cyborg module that shoots them out!
tgstation/tgstation pull request #21782
Opened 2016-11-27 05:41 UTC by kevinz000

Gives medical cyborgs and service cyborgs lollipop guns.
Has 3 modes
1. dispense lollipops
2. throw lollipops
3. shoot gumballs

Lollipops and gumballs do 5 damage on throw if the cyborg is emagged and can be shot a bit faster then normal projectiles for a bonus.
And the best part? Both have RANDOMIZED COLORS!!!
Sprites from @TehZombehz 

Updates cyborg hug module. :^)

:cl: Mekhi
rscadd: Medical and Service cyborgs now have LOLLIPOP AND GUMBALL SYNTHESIZERS.
experimental: Both of the sugary treats have randomized colors.
experimental: Intensifies the cyborg hugbox modules.
\:cl:

2016-11-27 05:46 UTC, RandomMarine commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	list_reagents = list("sugar" = 5, "bicardine" = 2, "kelotene" = 2)	//Kek
kelotane*

2016-11-27 05:57 UTC, RandomMarine commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	list_reagents = list("sugar" = 5, "bicardine" = 2, "kelotane" = 2)	//Kek
Forgot the bicaridine too.

2016-11-27 05:59 UTC, PKPenguin321 commented
Should be added to the cookie dispenser module

2016-11-27 06:00 UTC, kevinz000 commented
>giving pkborgs all teh fun

2016-11-27 10:38 UTC, FantasticFwoosh commented
50/50 not sure what to think, on one hand its pretty novel.

> Module bloat on silly meme that do _terrible_ damage when instead the med (has poison pricks) & the service has stuff like trayspam & guitars etc depending on the specific type.

Not to mention the missed opportunity for a gum into -> rubber plant for hydro

2016-11-27 10:53 UTC, kevinz000 commented
thanks @FantasticFwoosh

2016-11-27 10:54 UTC, kevinz000 commented
i dont like botany, it's primary purpose isn't shooting at people.

2016-11-27 11:00 UTC, FantasticFwoosh commented
@kevinz000 unless you count gatfruit, poison laced eggs & explosive lemons to be relevant.

2016-11-27 12:41 UTC, TehZombehz commented
>Balance discussion around simple children's candy

2016-11-27 12:58 UTC, kevinz000 commented
Yes.
Also @FantasticFwoosh I meant the borg module, botany has their fun already . If you want to add it to botany, feel free, I already made the code for the foods themselves and the randomized color for you man. It's just that this PR is focused on adding them to medical and service cyborgs, modules that don't have enough love.
*honks*

2016-11-27 13:15 UTC, Cebasiz commented
give it to peacekeeper and make emag allow full auto

wew

2016-11-27 13:16 UTC, Cebasiz commented
also medical is actually the best module in the game my man so don't add more things it doesn't need

add something so it can help people with blood and remove service cyborg from the game instead thx

2016-11-27 13:17 UTC, ChangelingRain commented on code/modules/food_and_drinks/food/snacks_other.dm
> +/obj/item/weapon/reagent_containers/food/snacks/lollipop/New()
you need to call ..() in New() procs

2016-11-27 13:17 UTC, ChangelingRain commented on code/modules/food_and_drinks/food/snacks_other.dm
> +/obj/item/weapon/reagent_containers/food/snacks/gumball/New()
same here

2016-11-27 21:45 UTC, jughu commented
Only if walking on gumbals make you tril

2016-11-28 01:47 UTC, kevinz000 commented
@Cebasiz Engiborg is.  :^)

2016-11-28 08:05 UTC, jughu commented
Tfw kevinz doesnt asd a emagged function for gumballs where you mass dispense gumballs all over the floor which will slip(trip) people

2016-11-28 11:56 UTC, TehZombehz commented
One thing at a time, jughu. Soon(TM)

2016-11-29 04:02 UTC, optimumtact submitted a review, later dismissed
Needs work

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +		return 0
use the DEFINES PLEASE I BEG OF YOU, PLEASE PLEASE PLEASE SIR I BEG OF YOU

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(!candy)
what if get's set to less than zero, use <= 0 instead

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(!candy)
same again

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +				return 0
DEFINES

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	click_cooldown_override = 2
why have you put this here, please make a comment explaining

2016-11-29 04:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +/obj/item/projectile/bullet/reusable/gumball/handle_drop()
remember what happened last time you made reusable bullets?

please test this

2016-11-29 04:44 UTC, kevinz000 commented on code/game/objects/items/robot/robot_items.dm
> +/obj/item/projectile/bullet/reusable/gumball/handle_drop()
i did it works

2016-11-29 04:44 UTC, kevinz000 commented on code/game/objects/items/robot/robot_items.dm
> +	click_cooldown_override = 2
for rapid firing of candy everywhere as normal click delay is too slow? :)

2016-11-29 04:45 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +/obj/item/projectile/bullet/reusable/gumball/handle_drop()
:worried:

2016-11-29 06:11 UTC, kevinz000 commented
@optimumtact  should be fixed
damage lowered to 3 per shot. shots now take 20 energy regardless.

2016-11-29 07:18 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(candy >= 0)
if candy is greater than or equal to zero, tell the user there are no lollipops left in storage ??

2016-11-29 07:18 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
>  		return 0
PLEASE I BEG OF YOU

2016-11-29 07:18 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +			return 0
AHHHHHHHHHHHH

2016-11-29 07:21 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(candy >= 0)
you want less than or equal to zero, not greater than or equal to zero

2016-11-29 07:21 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +		return 0
PLS

2016-11-30 02:59 UTC, kevinz000 commented on code/game/objects/items/robot/robot_items.dm
> +	if(candy >= 0)
....fuck

2016-11-30 23:58 UTC, optimumtact commented
YOu reverted mso's config changes, don't do that

2016-12-01 00:18 UTC, kevinz000 commented
wait WHAT HOW

2016-12-01 00:18 UTC, kevinz000 commented
"Fuck"

2016-12-01 01:07 UTC, Jordie0608 commented
Config names are still incorrect

2016-12-01 04:32 UTC, kevinz000 commented
fixed

2016-12-01 05:43 UTC, optimumtact requested changes
some final changes that can be made

2016-12-01 05:43 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(isturf(A))
replace this if check chains with

     var/turf/T =  get_turf(A)
     if(!T || !istype(T))
        return FALSE
     new /obj/item/weapon/reagent_containers/food/snacks/lollipop(T)
    
It should work exactly the same and be much cleaner

2016-12-01 07:59 UTC, kevinz000 commented
Added delayed deletion to delete the shot ones unless someone picks it up as they can be shot extremely quick, and I don't want to be responsible for gumball station 13.

2016-12-01 08:01 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +		charging = 1
TRUE FALSE DEFINES PLEASE

2016-12-01 08:01 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +		charging = 1
PLEASE WHY DO I HAVE TO KEEP ASKING I BEG OF YOU KEVIN

2016-12-01 08:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +	if(!T || !istype(T) || !isopenturf(T))
why are you checking for openturfs specifically?

2016-12-01 08:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +				return 0
PLEASE I BEG OF YOU

2016-12-01 08:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +				return 0
return FALSE

2016-12-01 08:02 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +		dropped = 1
dropped = TRUE

2016-12-01 08:03 UTC, optimumtact commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	var/spamchecking = 1
spamchecking = TRUE

2016-12-01 08:03 UTC, optimumtact commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	spamchecking = 0
spamchecking = FALSE

2016-12-01 08:03 UTC, optimumtact commented on code/modules/food_and_drinks/food/snacks_other.dm
> +/obj/item/weapon/reagent_containers/food/snacks/gumball/New()
@ChangelingRain what is thsi about?

2016-12-01 08:08 UTC, optimumtact commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	..(user, slot)
it's good practice to do . = ..(user, slot) 

even if you know the return value isn't used, it makes it easier for future developers if they refactor the proc

2016-12-01 08:12 UTC, kevinz000 commented on code/modules/food_and_drinks/food/snacks_other.dm
> +	..(user, slot)
K

2016-12-01 08:31 UTC, optimumtact commented on code/game/objects/items/robot/robot_items.dm
> +					playsound(loc, 'sound/weapons/thudswoosh.ogg', 50, 1, -1)
why type this twice?
it's played no matter if the if or else is checked, just unindent it and leave it at the bottom like it was before

2016-12-01 08:35 UTC, kevinz000 commented
aaannnnd fixed :^)

2016-12-01 09:29 UTC, optimumtact approved these changes

2016-12-01 10:59 UTC, kevinz000 commented on code/game/objects/items/robot/robot_items.dm
> +	if(!T || !istype(T) || !isopenturf(T))
So people can't inject lollipops into walls?

2016-12-01 11:16 UTC, kevinz000 commented on code/game/objects/items/robot/robot_items.dm
> +	if(!T || !istype(T) || !isopenturf(T))
because otherwise you end up with lollipops inside walls?

2016-12-02 02:42 UTC, merged