[READY]FLIGHTPACK PATCH 1: Crashing rework, drifting tweaks and fixes, DataHUDs, and slight price decrease!
tgstation/tgstation pull request #21855
Opened 2016-11-30 12:39 UTC by kevinz000

:cl: Mekhi Anderson
rscadd: Flightpacks are now easier to handle and use.
experimental: Flightpacks now respect directional momentum
experimental: Flightpacks now have a minimum speed before starting to drift
experimental: Flightsuit helmets now contain an omni-HUD
experimental: Flightpacks now check directions when crashing...
experimental: Flightpacks no longer instantly crash when crashing into living things
experimental: Flightpacks can now have their handling scrambled from EMP blasts
experimental: A flightpack crashing into the ground is now violent enough to disorient their user.
bugfix: Flightpacks can no longer multi-crash.
bugfix: Flightpack examining is now fixed
experimental: Flightpacks now cost slightly less to make, but having the shoes is critical for handling...
\:cl:
@GunHog Modules/stock parts coming in a later update, or you could try to do them. Honk. Anyways this PR was long overdue as there's some fixes to unintentionally done things.

2016-11-30 12:57 UTC, GunHog commented on code/modules/research/designs/mechfabricator_designs.dm
> +	materials = list(MAT_METAL=16000, MAT_GLASS = 80000, MAT_DIAMOND = 200, MAT_GOLD = 3000, MAT_SILVER = 3000, MAT_TITANIUM = 16000)	//This expensive enough for you?
I am sure you forgot to remove a 0 for the glass cost.

2016-11-30 18:23 UTC, XDTM commented
IMO, omnihud shouldn't be included in this. Omni-HUD glasses could be a late rnd item on their own.

2016-11-30 18:41 UTC, kevinz000 commented
Shadowlight's recommendation when I suggested letting them hold backpacks in sit storage

2016-12-01 00:03 UTC, GunHog commented
Looks like you botched your merge!

2016-12-01 03:27 UTC, kevinz000 commented
;-;

2016-12-01 07:40 UTC, Shadowlight213 commented
Omnihud seems like it fits thematically pretty well. Plus, it's an improvement that doesn't make the flight suit flat out better than integrated thrusters, since thrusters still have the advantage of having the back slot open.

2016-12-01 11:14 UTC, kevinz000 commented
thrusters also don't cost anything but are limited.
:honk:

2016-12-03 12:49 UTC, AnturK requested changes

2016-12-03 12:49 UTC, AnturK commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	switch(V)
This switch and V is redundant as far as i can tell. Just use the if blocks.

2016-12-03 12:49 UTC, AnturK commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	for(var/hudtype in datahuds)
Needs to call the parent.

2016-12-03 12:49 UTC, AnturK commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	for(var/hudtype in datahuds)
Same as above

2016-12-04 17:26 UTC, AnturK commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	if(V == "y")
I mean the whole intermidate V variable is redundant, it's not used anywhere but here so you might as well use the if(crashdir) blocks.

2016-12-04 20:18 UTC, optimumtact commented on code/controllers/subsystem/timer.dm
> +			stack_trace("Invalid arguments in call to addtimer! thingToCall:[thingToCall] procToCall:[procToCall] timeToRun:[world.time + wait].")
can you not

2016-12-04 21:02 UTC, GunHog commented
Please have a look at https://github.com/tgstation/tgstation/issues/21940 when you can.

2016-12-05 13:23 UTC, kevinz000 commented
@optimumtact fixed :)

2016-12-05 13:24 UTC, kevinz000 commented
@GunHog should be fixed

2016-12-05 14:34 UTC, RemieRichards commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/V = ""
why not just use crashpower, instead of using this to find which crashpower to use?

2016-12-06 11:45 UTC, kevinz000 commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/V = ""
Had the problem of people crashing when they clipped a mob perpendicular to their axis of movement, this fixes that far as I can tell...

2016-12-06 12:31 UTC, RemieRichards commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/V = ""
I mean swap the V = Y and then checking if it's Y, with just setting crashpower under that check.
it's identical functionality, cleaner code.

2016-12-06 12:57 UTC, AnturK approved these changes

2016-12-06 13:47 UTC, merged