DeltaStation (Playtest Version)
tgstation/tgstation pull request #22028
Opened 2016-12-08 02:01 UTC by Okand37

Test merge PR for DeltaStation (PlayTest Version)

2016-12-08 02:02 UTC, ChangelingRain commented
WOO!
It's always nice to see new, well-made maps.

2016-12-08 02:03 UTC, Anonmare commented
Got an image of the completed station?

2016-12-08 02:04 UTC, kevinz000 commented
M-merging F-from M-master!~

2016-12-08 02:05 UTC, ExcessiveUseOfCobblestone commented
is there a genetics section on the map? I think Mekhi has a stuttering disability.

2016-12-08 02:06 UTC, Cyberboss requested changes

2016-12-08 02:06 UTC, Cyberboss commented on _maps/deltastation.dm
> +	#warn a map has already been included, ignoring MetaStation.
>MetaStation

2016-12-08 05:33 UTC, GunHog commented
Pictures please?

2016-12-08 06:39 UTC, Okand37 commented
As to those asking; I don't have a stitched picture setup because this was just a pr to testmerge it on the server for a round to get immediate bug reports on what needs fixing, adding, changing, etc. Not much use spending 10-20 minutes stitching a big picture together when you're bound to be editing and tweaking things all over the map then just have to do it again. A stitch picture will be included when I actually make a full PR for the completed map, however.

2016-12-09 00:22 UTC, Okand37 commented
Going to close this and put up one more updated version of a testmerge. Forgive me, still figuring out all the tips and tricks of git.

2016-12-09 00:22 UTC, closed without merging