Fixes captains hardsuit heat protection
tgstation/tgstation pull request #22024
Opened 2016-12-08 01:09 UTC by Cyberboss

Fixes #22021

2016-12-08 20:11 UTC, KorPhaeron commented
One line fix, not a balance change, can't break anything

2016-12-08 20:12 UTC, imtakingabreakdontatme requested changes

2016-12-08 20:12 UTC, KorPhaeron commented on code/modules/clothing/spacesuits/hardsuit.dm
>  	max_heat_protection_temperature = FIRE_IMMUNITY_HELM_MAX_TEMP_PROTECT
You forgot to add heat protection to the helmet

2016-12-10 10:45 UTC, imtakingabreakdontatme requested changes

2016-12-10 10:45 UTC, KorPhaeron commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
And now the helmet covers everything except the head

2016-12-10 10:47 UTC, KorPhaeron commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
Covers body instead of head

2016-12-10 10:47 UTC, KorPhaeron commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
Wrong line, but you get the idea

2016-12-10 20:14 UTC, merged