GOOFMOS: Chemical Gas + Minor Goofmos Tweaks
tgstation/tgstation pull request #22058
Opened 2016-12-08 22:13 UTC by Iamgoofball

![2016-12-08_14-06-00](https://cloud.githubusercontent.com/assets/4081722/21029752/10cdd466-bd50-11e6-87c4-6489f4bb9bb5.gif)

:cl: Iamgoofball
add: Chemical Gas has been added to the game.
add: Add chems to a Chemical Gas Canister by hitting it with a beaker with the chemicals you want to add in it!
tweak: Freon is now colder, but no longer bypasses temperature protections.
/:cl:

where doin it

where makin it hapen

2016-12-08 22:15 UTC, bgobandit commented
ok but what about reagent reactions in the air

2016-12-08 22:16 UTC, RemieRichards requested changes

2016-12-08 22:16 UTC, RemieRichards commented on code/datums/gas_overrides.dm
> +/datum/proc/chem_gas_act(var/datum/reagents/gas)
you've been told about ```var/``` in proc arguments.
No more.

2016-12-08 22:16 UTC, RemieRichards commented on code/modules/atmospherics/environmental/LINDA_turf_tile.dm
> +	var/list/reagent_gas_memes = air.reagents.reagent_list
no.

2016-12-08 22:16 UTC, RemieRichards commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +		var/mathmemes = QUANTIZE((RA.volume / reagents.total_volume) * amount)
come on.

2016-12-08 22:16 UTC, Iamgoofball commented
they should react

2016-12-08 22:16 UTC, Iamgoofball commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +		var/mathmemes = QUANTIZE((RA.volume / reagents.total_volume) * amount)
what, it's temp vars and atmos memes

2016-12-08 22:16 UTC, Iamgoofball commented on code/modules/atmospherics/environmental/LINDA_turf_tile.dm
> +	var/list/reagent_gas_memes = air.reagents.reagent_list
it's for cacheing to improve speed

2016-12-08 22:17 UTC, PKPenguin321 commented
Truly airborne viruses was one of the most requested features when I first joined. Legend. :+1:

2016-12-08 22:23 UTC, MrStonedOne commented on code/modules/reagents/chemistry/holder.dm
> +	if(reagent_list)
don't place an entire proc inside of an if. do `if(!reagent_list) return`

https://github.com/tgstation/tgstation/blob/master/CONTRIBUTING.md#use-early-return

2016-12-08 22:25 UTC, MrStonedOne commented on code/modules/reagents/chemistry/holder.dm
>  	var/list/cached_reagents = reagent_list
We have the lazy init list macros in helpers/list.dm for this.

Also, you should be checking lengths any time you remove stuff from a list and if it gets back to empty again, remove the list.

there is a macro in helpers/list.dm for that too.

2016-12-08 22:27 UTC, MrStonedOne commented on code/modules/reagents/chemistry/holder.dm
> +			R.on_tick()
this entire if isn't needed.

for treats null lists as if they were an empty list.

2016-12-08 22:28 UTC, Iamgoofball commented on code/modules/reagents/chemistry/holder.dm
> +	if(reagent_list)
Will do

2016-12-08 22:28 UTC, MrStonedOne commented on code/modules/reagents/chemistry/holder.dm
> +		. = locate(type) in cached_reagents
I'd test if this if is even needed, iirc locate(type) in list will treat a null list the same as an empty list.

2016-12-08 22:57 UTC, FantasticFwoosh commented
Time to replace all the air with mercury or chlorine gas.

> Besides i have a especially evil gas in mind.

2016-12-08 22:57 UTC, Cebasiz commented
we really need an industrial sized machine that takes massive amounts of power to synthesize enormous amounts of reagents so we can fill the whole air supply with wonderdrugs

thanks goof i expect it in a week

2016-12-08 23:07 UTC, BeeSting12 commented
so can i fill medbay with tricord and noone will OD on it?

2016-12-08 23:08 UTC, Iamgoofball commented
@BeeSting12 nah, they'll OD if they hang in it too long, so be careful with that

2016-12-08 23:26 UTC, SgtxRootbeer commented
Wait, what about miner's salve, does it cause cramps if taken this way? 
Because, one option is to flood the air supply with charcoal and miners salve instead of tricordazine

2016-12-08 23:37 UTC, TechnoAlchemisto commented
How much gas would a 50u beaker release?

2016-12-08 23:38 UTC, Iamgoofball commented
@TechnoAlchemisto It hangs out around 2.5u a tile, so it depends on how much chem gas you actually have,

2016-12-08 23:54 UTC, GunHog commented
Is there a way to tell what reagents are contained within the gas?

2016-12-08 23:59 UTC, Iamgoofball commented
breathe it in and scan yourself with a medical analyzer

2016-12-09 00:00 UTC, GunHog commented
So, basically, "No". Should add it to air alarms and analyzers.

2016-12-09 00:09 UTC, FantasticFwoosh commented
Just use your PDA air analyser (or the analyzer tool)

Scrubbers are issue number 2, could we have a generic (chem gas) scrubber active without listing off some odd 30+ options?

2016-12-09 00:28 UTC, DorfGuy1 commented
oh boy, this is going to be gr8

2016-12-09 00:36 UTC, KorPhaeron commented
Didn't we turn this down already for being horrendously op and killing everyone every round

2016-12-09 00:37 UTC, Iamgoofball commented
@KorPhaeron No, it got turned down due to issues with lists going batshit on the memory and killing the server from memory overuse

2016-12-09 00:52 UTC, Cebasiz commented
it shouldn't be too bad, though you should definitely give the engineering sec outpost access to atmos on most maps because otherwise this is going to be a little crazy

2016-12-09 01:08 UTC, lordpidey commented
Is there something to prevent using reagents that already have a gas?  It'd be kind of weird to have oxygen reagent gas.

2016-12-09 01:14 UTC, MrStonedOne commented on code/modules/atmospherics/environmental/LINDA_turf_tile.dm
> +				if(reagent_gas.len)
needs a null check (or just use lazylen or just use length())

2016-12-09 01:16 UTC, MrStonedOne commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +	reagents.set_reacting(FALSE) // no
This is the kind of thing that might have to be lazyinit'ed also, it's a datum not a list so we don't have the macros for that, but every gas mixture doesn't need a reagent datum, only ones with reagents

2016-12-09 01:20 UTC, Iamgoofball commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +	reagents.set_reacting(FALSE) // no
Reagents datums aren't really supposed to stop existing after they start existing on an object. I can look into it, but no guarantees

2016-12-09 05:27 UTC, optimumtact commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +	reagents.set_reacting(FALSE) // no
they dont' even do anything goof, they just hold fukken reagents

2016-12-09 05:33 UTC, Shadowlight213 commented
@Iamgoofball does the admin message/logging actually WHAT chemicals are in the gas this time instead of "X has opened a canister containing the following: Chemicals"

2016-12-09 06:16 UTC, Iamgoofball commented
@Shadowlight213 i guess I could but you can just jump to the tile and VV -> air -> reagents

2016-12-09 06:18 UTC, drynwyn commented
Not if you're investigating something after the fact.

2016-12-09 06:18 UTC, Iamgoofball commented
i guess
i'll look into it but if you just check it right off the bat you should be good
i can just make it log inserting chems into chem gas containers to save from opening-spam

2016-12-09 18:30 UTC, AdamElTablawy commented
The possibility of bar neuro gas is a terrifying prospect. How will chemgas be available and what's the unit of reagent to gas content levels? 

Honestly, it might be better if smoke reactions made chemgas instead of having a snowflake canister available in weird spots because chemgas could very easily become much much worse than a plasmaflood (especially if some shitter release potassium and water gas. Explosions on every tile jfc)

2016-12-09 18:32 UTC, AdamElTablawy commented
Also maybe analyzers should give feedback on what chems are in the gas?

I mean, initro gas or clf3 gas will be fairly obvious but lexorin chemgas might leave people confused.

Also does this apply in a touch, ingest, or inject reaction or are the chems just added

2016-12-10 06:41 UTC, Firecage commented
Thanks for breaking the server goof.

2016-12-10 07:10 UTC, Iamgoofball commented
i'm getting really fucking tired of "edge case that when I test for it locally using the exact instructions from the players the crash doesn't occur" game

2016-12-10 07:10 UTC, closed without merging