[DNM] EMPs cause chameleon clothing to flicker
tgstation/tgstation pull request #22086
Opened 2016-12-09 23:31 UTC by coiax

:cl: coiax
add: Chameleon clothing produced by the syndicate has been found to
react negatively to EMPs, randomly switching forms for a time.
/:cl:

- EMPing them when they're in the box is fine, but when they're being
worn, the game slows down a LOT, which I assume is the constant spamming
of the regenerate_icons() proc on the mob every time the chameleon
clothes change, which if they're wearing all 10 of them, that's a lot of
redundant calls.

2016-12-10 00:12 UTC, XDTM commented
It would probably save you the issue if it locked in a random disguise for a while, instead of flickering. Maybe even make clothes nodrop while theyre haywire.
It would make camo clothing stand out instead of basically screaming "this guy is wearing camo".

2016-12-10 02:08 UTC, optimumtact commented
I'm sorry but what? You'll have to solve the issue you mentioned first, we're not going to merge something that can cause the game to slow down like that. Especially if it was noticeable with just one player on.

Investigate an overlay that follows the player using the effects system and make that an animation instead.

2016-12-10 02:35 UTC, coiax commented
Oranges, DNM is in the title... I put this code up for help, not to get it merged.

2016-12-10 05:06 UTC, optimumtact commented
oh, sorry I somehow missed that

2016-12-14 07:57 UTC, optimumtact commented
I will leave this open for one more day, but it doesn't seem you are getting much help

2016-12-14 08:06 UTC, Cyberboss requested changes

2016-12-14 08:06 UTC, Cyberboss commented on code/modules/clothing/chameleon.dm
> +	START_PROCESSING(SSprocessing, src)
Don't use SSprocessing, it just means you're trying to update basically every tick.

Use a timer set to go off every 3 seconds

2016-12-14 20:23 UTC, Cyberboss commented
@coiax Merge coiax/-tg-station#5

2016-12-14 23:10 UTC, coiax commented
The issue isn't processing, the issue is that we're regenerating all icons 10 times every time it changes, because of the camo clothing taking the lazy option

2016-12-14 23:12 UTC, optimumtact commented
cache as much as possible, use overlays for the flickering affect so you're only stripping out a single overlay at a time (i.e the icons below are unchanged)

2016-12-17 21:15 UTC, coiax commented
@optimumtact REMOVE DNM, WIP AND STALE TAGS PLZ <3

2016-12-18 06:46 UTC, merged