Adds DeltaStation's emergency shuttle to the shuttle file list
tgstation/tgstation pull request #22106
Opened 2016-12-10 22:48 UTC by Okand37

Adds DeltaStation's emergency shuttle to the shuttle file list. First proper PR to add anything to the game, lets see how it goes.
![](http://i.imgur.com/IK8pox8.png)

:cl: Okand37
add: DeltaStation's emergency shuttle
/:cl:

2016-12-10 23:38 UTC, PKPenguin321 commented
yuge

2016-12-11 00:53 UTC, Supermichael777 commented
Should call it big bertha

2016-12-11 01:07 UTC, ExcessiveUseOfCobblestone commented
the escape shuttle is a station in itself jesus

2016-12-11 03:44 UTC, Jordie0608 commented
This PR has commits including Deltastation itself, not just the shuttle file.
Also you'll want to add a datum for this shuttle to `https://github.com/tgstation/tgstation/blob/master/code/datums/shuttles.dm` to have it actually usable.

2016-12-11 10:09 UTC, Arianya commented
What price point did you see for this shuttle? Currently the highest cost (I think?) is the Lepton Violet which is sizably smaller then this one. Admittedly asteroid is probably larger, but its also a ~meme shuttle~

2016-12-12 16:12 UTC, Okand37 commented
Oh right, I should fix this today shouldn't I! Its a large shuttle as its meant to contain a highpopulation for, respectably, a highpopulation station. If I am unmistaken, however, its roughly 18x30 and should fit into most docks (will need to put the docking point down an airlock so that it works with boxstation ports.)
Will make sure to fix the commit and remove the magnetic pull that is dragging the station along with the shuttle into the PR.

I'll probably place it roughly around boxstation/metastation's shuttles but slightly higher, as it is just a standard station 'usable shuttle' but you also need to weigh in the size of what it can carry and obviously at that its slight edge on durability just due to sheer mass.

2016-12-13 05:27 UTC, Okand37 commented
Right, fixing this now. It'll be placed at 7500 credits, as box/meta are only around 2000 or so.

2016-12-13 06:20 UTC, Jordie0608 requested changes

2016-12-13 06:20 UTC, Jordie0608 commented on code/datums/shuttles.dm
> +	suffix = "airless"
`suffix = "delta"`

2016-12-13 06:33 UTC, Jordie0608 commented
I forgot I can just change it myself.

2016-12-13 06:33 UTC, Jordie0608 approved these changes

2016-12-13 06:42 UTC, merged

2016-12-13 07:53 UTC, jughu commented
I want this to crash into the station

2016-12-13 21:43 UTC, Okand37 commented
Works for me.