Internally track shifts since containment failure
tgstation/tgstation pull request #22166
Opened 2016-12-13 14:47 UTC by coiax

Since I don't want to add a full item without sprites, here is the code
work to tally the number of shifts since an engine was created loose, or
containment failed while an engine was active. (Note that the detection
isn't exact, so I've just piggybacked on the admin messages.)

Then later, we can actually have a X SHIFTS SINCE CONTAINMENT FAILURE
sign, and use this number.

2016-12-13 14:59 UTC, Cheridan commented
0 0 0 0 0 0 0

2016-12-13 15:04 UTC, PKPenguin321 commented
Does this properly ignore adminspawned singulos

2016-12-13 15:52 UTC, Cyberboss commented
@PKPenguin321 doesn't look like it

Also I find the loose sing detector to be pretty buggy in general, plenty of false positives

2016-12-13 17:29 UTC, lzimann commented
remember when we didn't have any kind of persistance

2016-12-13 18:57 UTC, Incoming5643 commented
#10663

2016-12-13 20:16 UTC, optimumtact commented
@lzimann oh my god yes because this is so going to hurt the game and be such a huuuuuuuuuuuge issue

2016-12-13 20:58 UTC, Cyberboss requested changes
This is not going to work. The way loose sings are detected needs to be changed (Maybe define an area that is valid for sings to be in?), and sings not created by PAs (aka badmins) need a flag set that will exclude it from the check.

Currently the check will fail ANY time ANY field generator turns off for ANY reason

Good enough for admins, not for this

2016-12-13 21:08 UTC, lzimann commented
Isn't there an admin-spawned check already? Or is it megafauna only?

2016-12-13 21:16 UTC, Iamgoofball commented
This is going to conflict with my PR, I have an idea on how to implement this properly, mind if I absorb this PR?

2016-12-13 21:46 UTC, coiax commented
Well luckily accuracy isn't THAT important given this is a silly bit of fun, rather than serious statistical tracking.

@Iamgoofball I am fine with you absorbing this PR, provided you can get it and your librarian PR merged.

2016-12-13 21:46 UTC, closed without merging

2016-12-13 21:49 UTC, MrStonedOne commented
The proper way to detect loose sings is to make an item in engineering and define singulo_pull on it and make that count as a loose sing.

2016-12-13 22:46 UTC, coiax commented
Except we also want to detect teslas and supermatter failures. And does someone setting up a PA elsewhere and making an engine count?

2016-12-13 23:31 UTC, MrStonedOne commented
make it a tesla target and trigger if it's zapped

and supermatters could be done some other way.

basically the idea is to make it revolve around the notice board being acted on by the engines.

2016-12-13 23:35 UTC, coiax commented
Hmm, that's not a bad idea. Like some sort of basic engine sensor close to the engine field.

2016-12-14 00:29 UTC, Iamgoofball commented
yeah that's how I was goinng to do it, noticeboard in the PA room saying "Days since last accident" and make the WMDs hitting it cause it to reset