Hijacking a shuttle diverts it to the syndicate base
tgstation/tgstation pull request #22184
Opened 2016-12-13 23:15 UTC by coiax

No changelog, because it's a SURPRISE.

If the shuttle meets the qualification for a "hijack", then instead of Centcom, it'll dock at the Syndicate base, landing in the fresh white snow instead. The base has a small extension to allow this.

- [ ] Test with multiple clients that everything behaves as expected
- [ ] Put in checks making it only happen if the shuttle is full of traitors and/or nukies, given that diverting a ship full of Ratvar Servants wouldn't make that much sense thematically?
- [ ] Produce a screenshot of the REALLY UNEXCITING map changes, because people will ask for them anyway

2016-12-13 23:32 UTC, ShadowDeath6 commented
this is pretty nice

2016-12-13 23:58 UTC, TechnoAlchemisto commented
Cool

2016-12-14 00:19 UTC, kevinz000 commented on code/controllers/subsystem/ticker.dm
> +			news_message = "During routine evacuation procedures, the emergency shuttle of [station_name()] had its navigation protocols corrupted, and was hijakced to an unknown location."
hijakced

2016-12-14 00:19 UTC, ShadowDeath6 commented on code/controllers/subsystem/ticker.dm
> +			news_message = "During routine evacuation procedures, the emergency shuttle of [station_name()] had its navigation protocols corrupted, and was hijakced to an unknown location."
:+1:

2016-12-15 03:34 UTC, Supermichael777 commented on code/controllers/subsystem/ticker.dm
> +			news_message = "During routine evacuation procedures, the emergency shuttle of [station_name()] had its navigation protocols corrupted, and was hijakced to an unknown location."
would nt ever admit this though?

2016-12-15 04:29 UTC, kilkun commented on code/controllers/subsystem/ticker.dm
> +			news_message = "During routine evacuation procedures, the emergency shuttle of [station_name()] had its navigation protocols corrupted, and was hijakced to an unknown location."
no but lore consistency isnt our strong suit either

2016-12-15 04:54 UTC, MimicFaux commented
I wouldn't worry about the asteroid shuttle, but make sure there's enough room to accommodate some of the larger ones.

2016-12-15 14:11 UTC, karlnp commented on code/controllers/subsystem/ticker.dm
> +			news_message = "During routine evacuation procedures, the emergency shuttle of [station_name()] had its navigation protocols corrupted, and was hijakced to an unknown location."
suggest: "...had its navigation protocols corrupted and went off course, but was recovered shortly after."

Lying instead of admitting weakness.

2016-12-15 14:23 UTC, jughu commented
I hope the syndiecate are happy that i haijcked a asteroid with engines strapped to them right trough their base

2016-12-15 16:25 UTC, coiax commented
I have allocated a very large snowy field for the shuttle landing, but the asteroid shuttle is still bigger than that. But it's the asteroid shuttle, who cares

2016-12-16 21:50 UTC, Cyberboss requested changes

2016-12-16 21:50 UTC, Cyberboss commented on code/controllers/subsystem/ticker.dm
> +				news_report = SHUTTLE_HIJACKED
You mean `SHUTTLE_HIJACK`

2016-12-17 18:38 UTC, dannno commented
making it safe for the asteroid is counter intuitive to the very nature of the asteroid. 👎

2016-12-17 18:40 UTC, coiax commented
The asteroid is not supposed to crush Centcom, so it doesn't crush the syndicate base either.

2016-12-18 06:48 UTC, merged