Clock Cult items that suffered off station penalties no longer work off station.
tgstation/tgstation pull request #22190
Opened 2016-12-14 06:13 UTC by Iamgoofball

:cl: Iamgoofball
fix: You can't work off-station as clock cult anymore.
/:cl:

>CLOCK CULT ROUND
>Step 1. Go to off station point ASAP
>Step 2. Wait out the grind to get resources to build
>Step 3. Come back to the station an hour later and win the game

>oh let's double the time it takes them that'll work

>Step 4. Wait a bit extra for your free greentext because instead of actually fixing the problem(clockcult spends entire round off station circlejerking instead of being an active antag force), we applied a bandaid and let the extended-until-5-minutes-before-end rounds continue.

2016-12-14 07:12 UTC, Cyberboss commented
This really is the only solution tbh

2016-12-14 07:12 UTC, jughu commented
Goofball being a hero like always

2016-12-14 07:13 UTC, jughu commented
Altough i want ratvar to warn you with big yellow text like his powers only work on the syayion

2016-12-14 08:15 UTC, ExcessiveUseOfCobblestone commented
> Altough i want ratvar to warn you with big yellow text like his powers only work on the syayion

`usr << "<span class='ratvar'> What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Ratvarian Monastery, and I’ve been involved in numerous secret cultist raids, and I have over 300 confirmed converts. I am trained in geising and I’m the top cultist in the entire Ratvarian Cult. You are nothing to me but just another spear training target. I will taunting tirade you the fuck out with precision the likes of which has never been seen before on this galaxy, mark my fucking words. You think you can get away with saying that shit to me over the telecomms? Think again, fucker. As we speak I am contacting my secret network of engineering cultists and triangulating your position with the telecommunications system as we speak. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my clockwork slab. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the Ratvarian cult and I will use it to its full extent to wipe your miserable ass off the face of the universe, you little shit. If only you could have known what divine, ratvarian retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo. </span>"`

2016-12-14 10:06 UTC, Arianya commented
I'd vote to still allow it on lavaland, as bloodcult are afforded the same privilege.

2016-12-14 12:00 UTC, Grazyn commented
@Arianya 
Nah, clockult is already much more powerful than bloodcult and barring one cult from lavaland makes it for more interesting "blood vs clock" rounds since they would have time to evolve without having to fisticuff each other from the start for the control of lavaland.

2016-12-14 12:28 UTC, jughu commented
But bloodcult is litteraly grab some plasteel and have free armor/weapons/shuttle extenders a minute when clockcult requires more time

2016-12-14 14:03 UTC, Arianya commented
Bloodcult also has a much stronger reason to lay claim to mining (easy access to plasteel) and leaving them unopposed in cult vs cult seems questionable.

The whole point of blood vs clock is that clock has more fancy toys but being able to use them is based solely on random component generation and teamwork (depositing in caches, etc), where blood has less fancy toys but can get access to them much easier.

I'd be more tempted to ban blood from making runes on lavaland then I would be to give the ability to clock though, since having a (generally) single access point autism fort isn't very conductive to fun gameplay, especially considering the shuttle can be sabotaged at which point your only options are to take a pod which drops you somewhere random in lavaland while blood can use tele runes.

2016-12-14 14:53 UTC, ChangelingRain commented
>goof complains about not fixing the problem, THEN DOESN'T FIX THE PROBLEM

ironic, isn't it?
Like, come on, you didn't actually PREVENT them from doing stuff off-station, you just made them unable to use a proselytizer, which isn't even strictly necessary.

2016-12-14 14:55 UTC, francinum commented
@Grazyn 
Can I get a bit of what your on, because it seems like some good shit.

2016-12-14 15:03 UTC, Grazyn commented
Try to get into xenobio after clockult spent all round turning it into a clock fortress (I'm not talking about additional walls and generic reinforcement, just regular clock items), now do the same but on lavaland, where you have ashstorms, fauna and generally hostile terrain. And most of the time you won't even notice until they storm the station straight from their base.

However I see your point @Arianya, Bloodcult with telerunes is much more mobile and can have several small hidden bases around the station, so it's probably the one that should be banned from lavaland.

2016-12-14 22:04 UTC, ExcessiveUseOfCobblestone commented
Since when has Cult v cult been implemented?

2016-12-14 22:48 UTC, ChangelingRain requested changes
Also, I hate this, and will deny it.

2016-12-14 22:48 UTC, ChangelingRain commented on code/game/gamemodes/clock_cult/clock_items/clockwork_proselytizer.dm
> +	if(!Y || Y.z != ZLEVEL_STATION)
Don't prevent use on centcom or when ratvar is alive.

2016-12-14 22:49 UTC, PKPenguin321 commented
>Also, I hate this, and will deny it.

Well of course *you* do

2016-12-14 23:33 UTC, Iamgoofball commented
Explain why you hate it and are closing it.

2016-12-14 23:33 UTC, Iamgoofball commented on code/game/gamemodes/clock_cult/clock_items/clockwork_proselytizer.dm
> +	if(!Y || Y.z != ZLEVEL_STATION)
Okay.

2016-12-14 23:52 UTC, KorPhaeron commented
>Also, I hate this, and will deny it.

No point in having this open then

2016-12-14 23:52 UTC, Iamgoofball commented
I'm reopening this until Joan provides a reason why they "hate it and will deny it". 

>I think the burden is often on maintainers to prove a PR is bad, rather than than the person making it to prove it is good, and this might help shift things slightly.

2016-12-14 23:53 UTC, optimumtact commented
I agree with goof, explain your reason to close it or go away

2016-12-14 23:53 UTC, coiax commented
Guys, please don't have open close/wars, it makes us look bad.

2016-12-14 23:54 UTC, optimumtact commented
Don't tell me how to drive this bus, I'm turning it around right now

2016-12-14 23:54 UTC, KorPhaeron commented
We already look bad by playing SS13, it's okay

2016-12-15 00:25 UTC, ChangelingRain commented
I don't think goof watches clockcult as much as I do, but I don't see clockcults go offstation often, and when they do, they tend to fail because they get caught and can't actually defend their base(which is always the hotel for some reason) because all their scripture is slow as hell.
Simply put, they're already fucked if they're offstation, and this doesn't significantly make them more fucked

2016-12-15 00:26 UTC, optimumtact commented
see that was easy

2016-12-15 00:26 UTC, closed without merging

2016-12-15 00:51 UTC, Iamgoofball commented
@ChangelingRain Then why do you let them go off station in the first place??? If they aren't supposed to go off station, make them unable to go off station.