adds black gloves to fire fighting closets and crate
tgstation/tgstation pull request #22227
Opened 2016-12-15 13:21 UTC by jughu

Firefighting gear without FIRE RESISTANT GLOVES?? YOU WILL HURT YOUR HANDS WHILE FIGHTING THE FIRE!!!

:cl:  Hyena
add: Black gloves to firefighting closets/crate
/:cl:

2016-12-15 14:24 UTC, Cyberboss commented
No, let's not give everyone access to something that can both remove lights and hide fingerprints

2016-12-15 14:26 UTC, jughu commented
I mean tachnically they can craft them by using cloth and cut up bedsheets and paint them

2016-12-15 14:28 UTC, jughu commented
Gloves are already common as fuck i dont see a problem with this you can litteraly cut up bedsheets and make black gloves

2016-12-15 14:33 UTC, jughu commented
@Cyberboss 1 cut bedsheet with wirecutters = 3 cloth 3 cloth = 1 pair of black gloves so a bedsheet equals black gloves why would this be a problem them if theres litteraly bins full of bedsheets

2016-12-15 19:25 UTC, Cyberboss commented
Then let them make it. Less hugbox and the heat resistance from gloves is negligible anyway

2016-12-15 19:29 UTC, jughu commented
then whats the big problem fire resistant gloves protect your hand from fire ok

2016-12-15 21:14 UTC, ShadowDeath6 commented
Don't even bullshit the fact that you should get heat resistant gloves in firefighting crates

Closets have the shitty knockoff brand emergency firesuits that don't even protect from fire fully so that might be something to talk about

2016-12-15 22:08 UTC, ExcessiveUseOfCobblestone commented
> create fire-resistant gloves using cloth from torn bedsheets

what

2016-12-16 06:12 UTC, jughu commented
Yes you can cut up bedsheets for 3 cloth and you can make black gloves with 3 cloth

2016-12-16 12:38 UTC, Mervill commented
make fire gloves that can't remove lights and leave behind prints but resist heat, like cheap insulated gloves

2016-12-16 13:38 UTC, Cyberboss commented
Yeah, black gloves aren't your average assistant item.

On Dec 16, 2016 7:38 AM, "Mervill" <notifications@github.com> wrote:

make fire gloves that can't remove lights and leave behind prints but
resist heat, like cheap insulated gloves

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/22227#issuecomment-267585839>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHywehLmmdpazww3Z1PIt5B2AreDBw4Zks5rIoZTgaJpZM4LOFqG>
.

2016-12-16 13:41 UTC, jughu commented
Oke but i will remove black gloves from bedsheets them and make them grey instead k?

2016-12-16 16:15 UTC, Cyberboss commented
@Mervill Removing lights is tied to fire resistance

The one thing I'm worried about is the potential for greyshits to constantly "le advanced darkness" the station. I am one of those greyshits

2016-12-16 16:17 UTC, Cyberboss commented
Go ahead with this though. I think I'll make lightbulbs require a screwdriver to remove (Not counting the light re-placer)

2016-12-16 16:21 UTC, Cyberboss requested changes
DRY it out

2016-12-16 16:21 UTC, Cyberboss commented on code/modules/clothing/gloves/color.dm
>  	var/can_be_cut = 1
Remove lines 42-48, 50, and 51. They are all inherited from black

2016-12-16 22:14 UTC, Mervill commented
> Go ahead with this though. I think I'll make lightbulbs require a screwdriver to remove (Not counting the light re-placer)

Screwdriver notwithstanding the light replacer is a good idea since it give you good incentive to actually use the damn replacer

2016-12-16 22:46 UTC, KorPhaeron commented
Uneeded buff

2016-12-16 22:46 UTC, closed without merging

2016-12-16 22:59 UTC, jughu commented
Kor wrecking my dreams like a wrecking ball