Allows the biogenerator in Hydroponics to print paper and fake space cash
tgstation/tgstation pull request #22263
Opened 2016-12-16 21:56 UTC by ma44

**FAKE CASH IS NOT WORTH ANYTHING**

:cl: ma44
add: The biogenerator can now print paper and fake space cash
add: In response to this, the Centcomm in your sector has upgraded the ATM to prevent the fake space cash being used as money, exported money will also be checked to make sure they are not fake. 
/:cl:

This change is good

1. You can print dosh which doesn't effect game balance
2. Antags can use this to bribe or trade for items if the crew can roleplay
3. You can make a fun economy
4. Makes ma44 satisfy his space cash fetish

2016-12-16 21:59 UTC, ExcessiveUseOfCobblestone commented
what's the point of it then

2016-12-16 22:00 UTC, Mindustry commented
Should require the biogenerator to be hacked to print the fake money. Doesn't seem like something that would come standard with a machine.

Number 2 isn't really a good example because traitors can already purchase briefcases full of REAL money

2016-12-16 22:00 UTC, ma44 commented
Trick people into thinking it's real money, also making your own crappy economy

2016-12-16 22:04 UTC, Armhulen commented
what's the point of it then

2016-12-16 22:07 UTC, jughu commented
A economy with fake money is basically a economy with real money

2016-12-16 22:07 UTC, ma44 commented
So you can spend the thousands of biomatter on something that makes you feel rich

2016-12-16 22:18 UTC, coiax commented
Modify the Service borg cash fabricator to make fake cash then.

2016-12-16 22:22 UTC, jughu commented
No keep service borg cash real so i can murderbone as qm and make a cash printery and ship it

2016-12-16 22:22 UTC, jughu commented
Or make it real when emagged

2016-12-16 22:23 UTC, Mindustry commented
also merging from master ayy

2016-12-16 22:23 UTC, ma44 commented
The service borg produces 20 credit bills, nothing to worry about

2016-12-16 22:25 UTC, jughu commented
Thats 20 points per produced dosh

2016-12-17 00:09 UTC, jughu commented
Yay now i can make more paper which get rarely used anyways!

2016-12-17 01:23 UTC, Cruix commented
But what about the biogenerator in perma?

2016-12-17 02:02 UTC, ma44 commented
What would you do with fake cash and paper?

2016-12-17 02:26 UTC, Aurantiaco commented
Bribe the security officer to be let out.

2016-12-17 02:29 UTC, Mindustry commented
They'll just meta-know the cash is fake.

2016-12-17 02:44 UTC, ma44 commented
If it was real, that possible cash could be used for some fun WT550s or tasers

2016-12-17 04:15 UTC, ExcessiveUseOfCobblestone commented
you don't just have normal stacks of cash in perma...

2016-12-17 05:17 UTC, francinum requested changes

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
Duplicate Definition.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
And here.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
And here.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
And here.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
And here.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
And here.

2016-12-17 05:17 UTC, francinum commented on code/game/objects/items/stacks/cash.dm
> +	value = 0
You get the point.

2016-12-17 10:55 UTC, jughu commented
When is paper gonna be able to be stacked

2016-12-17 21:13 UTC, kevinz000 commented
ur not worth anything lolol












 jk ily man.

2016-12-20 02:37 UTC, closed without merging