[WIP] Stellar engine; bringing the power of BURNING, BLINDING sunlight to the station
tgstation/tgstation pull request #22422
Opened 2016-12-24 02:09 UTC by coiax

Background Changes:
- Silicons can now turn on field generators
- PA admin messages now use the standard #21889 
- The supermatter now only stuns (by staring blankly) if you are conscious, and correctly copes if someone is wearing protective eyewear

WIP:
- [ ] Field generators now understand what area they have demarcated, for more accurate singularity-in-field tracking

---

Adds the stellar engine, a miniature sun that provides mega energy to any solar panels it can see. It blinds anyone who can see it without protective eye wear, although the level of eye protection does vary depending on its temperature/energy.

A loose miniature sun will drift towards the centre of gravity of the station (approximately the middle, based on a simple calculation of all the turfs and walls, which can be changed by construction and destruction). It heats anything it can see, increasing air temperature and melting machinery, walls, floors and people. (And I guess cooking meat and heating beakers of reagents). It has no gravitational pull, but direct contact is lethal (or at least very hot).

2016-12-24 02:09 UTC, xxalpha commented
:sunglasses:

2016-12-24 02:11 UTC, ChangelingRain commented on code/modules/power/singularity/generator.dm
> +	desc = "An odd device which produces a gravitational singularity \
no.

2016-12-24 02:12 UTC, xxalpha commented on code/modules/power/singularity/generator.dm
> +	desc = "An odd device which produces a gravitational singularity \
Every \
time.

2016-12-24 02:12 UTC, ChangelingRain commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		message_admins("PA Control Computer increased to [strength] by \
_screaming_

2016-12-24 02:12 UTC, PKPenguin321 commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		message_admins("PA Control Computer increased to [strength] by \
why does he even do this? genuine OCD?

2016-12-24 02:13 UTC, ChangelingRain commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		message_admins("PA Control Computer decreased to [strength] by \
follow the goddamn guidelines; `Code where one line of code is split across mutiple lines (except for strings and comments and in those cases existing longer lines must not be split up)`

2016-12-24 02:13 UTC, ChangelingRain commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +	message_admins("PA Control Computer turned [active ?"ON":"OFF"] by \
line break hell

2016-12-24 02:13 UTC, xxalpha commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		message_admins("PA Control Computer increased to [strength] by \
They're on linux using vi or something and their screen isn't wide enough, so they break line to fit in their screen.

2016-12-24 02:13 UTC, PKPenguin321 commented
Sounds really cool. Obtainable in-game?

2016-12-24 02:15 UTC, ChangelingRain commented on code/modules/power/singularity/singularity.dm
> +					H << "<span class='notice'>You look directly into \the \
i'm going to throw you and your linebreaks into the goddamn star you're trying to pr

2016-12-24 02:17 UTC, ChangelingRain commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		message_admins("PA Control Computer increased to [strength] by \
their screen must be like 500 pixels wide, then, because that's how long this line is

2016-12-24 02:17 UTC, coiax commented
@PKPenguin321 that's the plan. Shouldn't require too much modification from a standard singularity/tesla engine apart from solar panels being put in instead of tesla coils.

2016-12-24 02:18 UTC, coiax commented
@xxalpha Having it eat the gravity generator is a little predictable and unfun, given how it's not rebuildable. Also, the gravity generator isn't heavy per se, it just magically makes gravity across the station.

2016-12-24 02:20 UTC, xxalpha commented
No no no, gravitational attraction is related to mass, but if the gravity generator is generating gravitational attraction for the entire station then I think it should be the beacon for the star.

Otherwise have it float towards the AI Core because that shit's the densest.

2016-12-24 02:21 UTC, coiax commented
I will experiment with various modes of attraction, see which one I like the best.

2016-12-24 02:48 UTC, Anonmare commented
Not sure I like attraction to the grav gen and AI sat, the AI sat is pretty far out of the way and Boxi s the only map I can think of that has its grav gen in a central location, others tend to have it right next to engineering itself.

2016-12-24 03:53 UTC, Armhulen commented
it should be extremely hot

like rods turn red when near it

2016-12-24 03:54 UTC, Kromgar commented
The issue of having it drift towards the grav gen is in every map other than box the grav gen is in engineering.

So it destroys grav gen and then drifts to the center of the station every time

2016-12-24 05:45 UTC, Jordie0608 commented
Requesting Slip Slop Slap meme

2016-12-24 05:46 UTC, dannno commented
UN. THE SUN. THE SUN. THE SUN. THE SUN.

2016-12-24 06:34 UTC, Cyberboss requested changes

2016-12-24 06:34 UTC, Cyberboss commented on code/modules/power/singularity/field_generator.dm
> +	if(state != FG_WELDED)
Merge this with attack hand

2016-12-24 06:34 UTC, Cyberboss commented on code/modules/power/singularity/generator.dm
> +	desc = "An odd device which produces a gravitational singularity \
https://github.com/tgstation/tgstation/blob/master/CONTRIBUTING.md#L295

BAN HE!!!

2016-12-24 06:34 UTC, Cyberboss commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		[usr ? ADMIN_LOOKUPFLW(usr) : "outside forces"] in \
1000 lashings per backslash

2016-12-24 11:20 UTC, kevinz000 commented on code/modules/power/singularity/field_generator.dm
> +
Borgs can already turn fieldgens on, just AIs can't.

2016-12-24 12:44 UTC, coiax commented on code/modules/power/singularity/field_generator.dm
> +	if(state != FG_WELDED)
The difference is that it's not visible if an AI turns it on remotely.

2016-12-24 12:44 UTC, coiax commented on code/modules/power/singularity/particle_accelerator/particle_control.dm
> +		[usr ? ADMIN_LOOKUPFLW(usr) : "outside forces"] in \
S-senpai~

2016-12-24 19:39 UTC, Iamgoofball commented
Freon Engine next

2016-12-24 21:00 UTC, swindly commented on code/modules/power/stellar/generator.dm
> +/obj/machinery/the_singularitygen/minature_star
miniature

2016-12-27 17:32 UTC, dannno commented
ummmmm you cant have an engine powered by cold, "goofball".

2016-12-29 02:34 UTC, ExcessiveUseOfCobblestone commented
the anti-turbine

2016-12-29 02:37 UTC, ExcessiveUseOfCobblestone commented
yet another roundending engine for people to ignore in the quest for long rounds.

2016-12-29 18:02 UTC, kilkun commented
What if power was just removed from the game amirite cobby 😏

2016-12-29 18:58 UTC, jughu commented
may the sun be with you!
![image](https://cloud.githubusercontent.com/assets/14280283/21552333/30fb9cfc-ce01-11e6-9de8-2872c0726571.png)

2016-12-29 23:12 UTC, Anonmare commented
TEG roundstart engine when?

2017-01-10 18:43 UTC, KorPhaeron commented
Stale

2017-01-10 18:43 UTC, closed without merging