The real slips rewrite
tgstation/tgstation pull request #22490
Opened 2016-12-27 04:39 UTC by Cyberboss

Slipping and meathooking now use /datum/forced_movement which is more refined than the shitty for-spawn that slips used to use

Also fixed a bug in forceMove that caused Entered and Exited to be called even if the atom was moved to the same loc

2016-12-27 04:42 UTC, Cyberboss commented on code/datums/forced_movement.dm
> +/datum/forced_movement/proc/TryMove(recursive = FALSE)
Any better way to do diagonal movement?

2016-12-27 04:54 UTC, ChangelingRain commented on code/datums/forced_movement.dm
> +	src.victim = victim
avoid having to do src.var by renaming the arguments for New()

2016-12-27 04:54 UTC, ChangelingRain commented on code/datums/forced_movement.dm
> +/datum/forced_movement/proc/TryMove(recursive = FALSE)
Couldn't you just step_towards(vic, tar)?

2016-12-27 04:55 UTC, Iamgoofball requested changes

2016-12-27 04:55 UTC, Iamgoofball commented on code/datums/forced_movement.dm
> +		for(var/i = 0, i < steps_to_take, ++i)
Nope, wrong type of loop

2016-12-27 04:57 UTC, ChangelingRain commented on code/game/objects/structures.dm
> +	density = 0
Are there any climbable objects with a density of 0? You should at least account for them

2016-12-27 04:59 UTC, Cyberboss commented on code/game/objects/structures.dm
> +	density = 0
This is just a refactor of /obj/structures climb code so forced_movement can use it. Should be fine if it was before

2016-12-27 06:08 UTC, optimumtact commented
Why not use the same subsystem as spacemovement, or roll them together?

2016-12-27 06:11 UTC, Cyberboss commented
This does some very basic obstacle avoidance. Also it's a lot faster than
space drift.

On Dec 27, 2016 1:08 AM, "oranges" <notifications@github.com> wrote:

> Why not use the same subsystem as spacemovement, or roll them together?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/22490#issuecomment-269275159>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywehYm6njaKS1qyB-djjdgDDcMoaGcks5rMKtngaJpZM4LWBkL>
> .
>

2016-12-27 06:47 UTC, Armhulen commented
wher the fuck id it?

2016-12-27 07:22 UTC, Iamgoofball commented
IT'S HERE

2016-12-27 09:30 UTC, MrPerson commented on code/datums/forced_movement.dm
> +/datum/forced_movement/proc/TryMove(recursive = FALSE)
Lots of ways to do this: See shooting for an example that's actually straight

2016-12-27 10:55 UTC, MrStonedOne commented
You know, you might be able to merge throwing into this... meaning you could absorb my pr.

It seems like it could be expanded enough to also do space drift, using a subtype of forced move.

So could throwing.

I like this system much better than my low effort merge of throw_at into a subsystem.

2016-12-27 10:57 UTC, MrStonedOne commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
I must say, i'd really rather prefer something like src.victim = avictim. adding a to the front just makes it harder to read at a glance.

up to you.

2016-12-27 11:00 UTC, optimumtact commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
use a _

2016-12-27 11:01 UTC, optimumtact commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
>aallow_tabling
aaaaaaaa

2016-12-27 13:30 UTC, RemieRichards commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
yeah :+1: to what mso said.

2016-12-27 13:35 UTC, RemieRichards commented on code/datums/forced_movement.dm
> +	if(force_moving && force_moving.allow_tabling && istype(A,/obj/structure))
should rename ```allow_tabling``` to ```allow_climbing``` or ```do_climbing``` or something.

2016-12-27 13:38 UTC, RemieRichards commented on code/datums/forced_movement.dm
> +				C.spin(1,1)
make this a movable proc, ```dirSpin()```, and then generalise the use here to movable.

2016-12-27 13:40 UTC, RemieRichards commented on code/datums/forced_movement.dm
> +	. = . && vic.loc != tar.loc
paranthesis, for readability.

2016-12-27 13:43 UTC, RemieRichards commented on code/datums/forced_movement.dm
> +	if(!avictim.force_moving)
you can't replace an existing ```force_movement```?

2016-12-27 13:43 UTC, RemieRichards commented
I don't see these getting cleaned up anywhere, are you supposed to hold a lingering ref to a finished forcemove?

2016-12-27 14:18 UTC, ChangelingRain commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
or use new_ as a prefix

2016-12-27 17:08 UTC, Cyberboss commented on code/datums/forced_movement.dm
> +/datum/forced_movement/New(atom/movable/avictim, atom/atarget, asteps_per_tick = 0.5, aallow_tabling = FALSE, aspin = FALSE)
>opinions

2016-12-27 17:09 UTC, Cyberboss commented on code/datums/forced_movement.dm
> +				C.spin(1,1)
I'll just replace this with a per-step callback once those are in

2016-12-27 17:10 UTC, Cyberboss commented
You can qdel it to stop it early or it will qdel itself when it finishes/can't go further. It handles its own references

2016-12-27 17:30 UTC, Cyberboss commented
Is there a good reason SSfastprocess isn't 1 tick?

2016-12-27 19:52 UTC, optimumtact commented
Well it's not supposed to be that fast, just faster than the normal obj subsystem.

But the more things you put on it the slower it will get.

2016-12-27 20:08 UTC, Iamgoofball commented
Fast process is like fastmos. It runs as fast as possible.

2016-12-27 20:18 UTC, optimumtact commented
>wait = 2

2016-12-27 20:27 UTC, Iamgoofball commented
It doesn't use that wait.

2016-12-27 20:40 UTC, MrStonedOne commented
Is there a good reason SSfastprocess isn't 1 tick?

Ticker subsystems run first every tick. If it ran every tick and called something that didn't tick check then the mc wouldn't be able to do anything else

2017-01-03 18:27 UTC, optimumtact commented
Callbacks?

2017-01-03 18:42 UTC, Cyberboss commented
Yeah I'll take care of it when I get home

On Jan 3, 2017 1:27 PM, "oranges" <notifications@github.com> wrote:

> Callbacks?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/22490#issuecomment-270185575>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHyweimOt-Pa19FLITDeqWxKj8R2eQZBks5rOpMLgaJpZM4LWBkL>
> .
>

2017-01-09 18:25 UTC, Cyberboss commented
Testmerbeg

2017-01-09 21:14 UTC, optimumtact commented
Will chase for test merges

2017-01-11 01:20 UTC, PKPenguin321 commented
hahahaha

2017-01-12 00:15 UTC, Cyberboss commented
![](https://m.popkey.co/78b29a/rzvvX.gif)

2017-01-12 00:56 UTC, optimumtact commented
Did this get test merged?

2017-01-12 00:57 UTC, Cyberboss commented
It has been for a while now

2017-01-12 00:57 UTC, merged