GUNCRAFTING: this was opened before the freeze, grandfathered in stop closing it
tgstation/tgstation pull request #22654
Opened 2017-01-02 07:56 UTC by Iamgoofball

original PR with the old comments located at #19250, opened this one due to the mass amount of outdated review stuff lagging down browsers

![dreamseeker_2016-12-29_12-30-28](https://cloud.githubusercontent.com/assets/4081722/21554340/bee0b964-cdc3-11e6-8d71-224f26b41a36.png)

# HOW TO QUICKLY ASSEMBLE A GUN:
1. PRINT FRAME, **PROJECTILE** OR **ENERGY**
2. ATTACH A **BARREL**, **HANDLE**, AND **BASE**
3. **OPTIONAL**: ATTACH A **SCOPE**, **UNDERBARREL**, AND **BULLET MODIFICATION**
4. **SHOOT SHIT**

TODO:
- [x] Attachment Bases
- [x] Handles
- [x] Bases
- [x] Barrels
- [x] Frames
- [x] Attachments(1st Wave)
- [x] Way to get parts
- [x] Codersprites

STAGES:
- [x] Proof of Concept
- [x] Feature Fulfillment/Testing
- [x] Cleanup
- [x] SPRITES (thanks bman)

:cl:
experimental: Guncrafting has arrived. Please contact your local warden.
experimental: Assemble a gun with a Frame, Firing Pin, Barrel, Base, Handle, and any additional attachments from the Gunlathe in the Armory.
/:cl:

2017-01-02 08:00 UTC, Iamgoofball commented
this is ready for merge at the 24 hour mark

2017-01-02 08:30 UTC, Iamgoofball commented
@optimumtact please delete this shitposting

2017-01-02 08:36 UTC, Haevacht commented
Oh don't have one of these in this thread yet, inhands yet?

2017-01-02 08:50 UTC, juanototo2 commented
# TODAY GOOF TAKES OVER THE WORLD AND MAKES BALANCE CRY

2017-01-02 10:14 UTC, Firecage commented
>Claims PR is ready to merge.
>The inhands of every gun still looks the fucking same. Huge balance issue.

2017-01-02 11:14 UTC, Iamgoofball commented
hi can this PR get pruned of shitposts by people not reviewing code

@Razharas @Cheridan @KorPhaeron @Jordie0608 @AnturK @optimumtact

2017-01-02 11:40 UTC, Firecage commented
Goofball, stop being so salty. No proper inhands is a VERY legitimate concern and a big balance issue, especially since currently we can see whether someone pulls out a taser, laser, or disabler on us.

And yes, me stating that you are once again opening a feature PR during the Feature Freeze despite that this PR got closed previously due to the same thing, is also a valid statement.

2017-01-02 13:39 UTC, kevinz000 commented
Come on goof finish your feature...

2017-01-02 16:03 UTC, GunHog commented
Goof, immediately upon starting the round, I am spammed with these three runtimes:

runtime error: 
[10:01:24]list index out of bounds
[10:01:24]proc name: update ammo types (/obj/item/weapon/gun/energy/proc/update_ammo_types)
[10:01:24]  source file: energy.dm,47

runtime error: 
[10:01:24]list index out of bounds
[10:01:24]proc name: recharge newshot (/obj/item/weapon/gun/energy/recharge_newshot)
[10:01:24]  source file: energy.dm,91

runtime error: 
[10:01:24]list index out of bounds
[10:01:24]proc name: update icon (/obj/item/weapon/gun/energy/update_icon)
[10:01:24]  source file: energy.dm,124

2017-01-02 20:11 UTC, Supermichael777 commented
could you assemble in-hands from layers?

2017-01-02 20:25 UTC, Militaires commented
@Supermichael777 modular inhands seems like a huge waste of layers.

@Iamgoofball just use the current inhands for the egun and taser and stuff it's not like you can get much fucking detail with inhands

2017-01-03 02:12 UTC, MrPerson commented
What do you mean, waste of layers? We have a ton of them

2017-01-03 09:20 UTC, Grazyn commented
At the very least have the inhands have a couple red, yellow, green or blue pixels depending on the energy base used. And regular black stick for ballistic base.

2017-01-03 10:32 UTC, Haevacht commented
Without inhands this is not, infact, finished or ready for merge at the 24 hour mark. Back off.

2017-01-03 16:59 UTC, Militaires commented
@mrperson yeah but reserving layers for this one niche inhand of a feature seems kind of fucked doesnt it

2017-01-03 17:19 UTC, KorPhaeron commented
Has this changed at all from last time or is it still triple burst disabler pistols for security every round

2017-01-03 18:03 UTC, Iamgoofball commented
There's been nerfs and buffs, I'm waiting to collect more data on burst fire because I was told by one party it's UP and useless, and another party told me it was OP.

2017-01-03 20:53 UTC, dannno commented
???
I've only ever seen/heard that it was very, very clearly broken.
How exactly would firing multiple shots in a single click NOT be stronger than firing one shot
i'm telling you man, 1:1 is the way to do this

2017-01-03 22:53 UTC, Grazyn commented
IIRC burst fire makes the gun deplete faster. Meaning that you get ~3 bursts before the gun is empty.

2017-01-03 23:08 UTC, Iamgoofball commented
Yeah, fire control.

2017-01-03 23:10 UTC, KorPhaeron commented
Who said it was useless I bet it was startoad

2017-01-04 01:08 UTC, Tacolizard commented
+1 to the guncrafting itself, but giving sec unlimited and exclusive access to it is way overpowered. burst fire disablers are not good roundstart

2017-01-05 12:49 UTC, RemieRichards commented
@Militaires we have infinite layers, and you can actually reuse the inhands layer itself, since I added a system for inhand overlays to have their own overlays easily (```worn_overlays()```), this allows us to have an infinite amount of layers WITHIN the inhand layer, so there's no weirdness.

tl;dr goof should use ```worn_overlays()``` to  built his gun's inhands dynamically.

2017-01-07 03:57 UTC, Iamgoofball commented
conflicts fixed and burst fire disabled

@Razharas @Cheridan @KorPhaeron @Jordie0608 @AnturK @optimumtact

2017-01-07 04:37 UTC, Iamgoofball commented
please god i want to move on to goof-AI but this needs done first

2017-01-07 09:40 UTC, Cheridan commented
i got killed by spread-disablers earlier now it's never getting in

2017-01-07 19:15 UTC, Iamgoofball commented
I removed burst fire though

2017-01-07 20:36 UTC, Firecage commented
Did you add the inhands yet?

2017-01-07 21:35 UTC, Iamgoofball commented
Did you stop abusing periods?

2017-01-07 21:45 UTC, Iamgoofball commented
reasons I CBA to add inhands:
1. now adding new parts is even fucking harder when it's supposed to be easy since it goes from 1 sprite to 9 per part
2. making sure all new sprites fit all other parts and sprites
3. making sure that sprites all overlay properly and don't overlap any other sprites
4. there's hardly any real estate for spriting

>just make the sprites yourself

did you see the original sprites from this PR when I tried making them myself

2017-01-07 22:13 UTC, Firecage commented
Mmm, using the existing inhands for now is actually a pretty good idea. +1

2017-01-07 22:19 UTC, Firecage commented
@Iamgoofball Also, by spreading, I don't think Cheridan means burst firing. Think of how that Disabler Shotgun on the Space Hotel works, or how shotgun shots works, they spread their projectiles infront of you. That is possibly what they mean.

2017-01-07 22:39 UTC, dannno commented
>Did you stop abusing periods?

LOL SAVAGE

2017-01-08 02:39 UTC, Iamgoofball commented
# inhands done

2017-01-08 02:39 UTC, Iamgoofball commented
@Razharas @Cheridan @KorPhaeron @Jordie0608 @AnturK

now that inhands are done, we're ready for merge release me from my suffering

2017-01-08 02:50 UTC, MrStonedOne commented
lets do another test merge

2017-01-08 03:17 UTC, Armhulen commented
HYPE

2017-01-08 03:56 UTC, kevinz000 commented
Roundstart decloners
Roundstart ballistics.
roundstart radiation bullets
That is all.

2017-01-08 03:58 UTC, sawrge commented
just laughs, tears streaking down my tired face

2017-01-08 04:04 UTC, dannno commented
You blew it

2017-01-08 04:05 UTC, Iamgoofball commented
@kevinz000 you know it, i fix one issue and you guys find a new one this is why we testmerge

2017-01-08 04:06 UTC, kevinz000 commented
That's not an issue that's something you put in intentionally, how do you not know what values you're putting in the console? Also what the fuck is with roundstart assault rifles? Even if they don't do that much damage this is bull.

2017-01-08 04:07 UTC, Iamgoofball commented
you need to land every single shot with an AR to crit someone just like any old laser gun

2017-01-08 04:08 UTC, Iamgoofball commented
also it's almost like you don't realize I figured it'd be fine but baalnce testing shows it needed changed, I'd be on the server but I can't collect info because I'm ooc banned

2017-01-08 04:08 UTC, kevinz000 commented
Maybe if you actually played the game you could collect info yourself, huh.

2017-01-08 04:08 UTC, Iamgoofball commented
uranium reqs on Decloners and Polonium rounds

2017-01-08 04:13 UTC, kevinz000 commented
Other things:
Automatic laser weapons are absolutely positively bullshit, does the same amount of damage in half the time, no reason to go semi-auto.
Ballistics are REALLLY weak compared to lasers but I'm not complaining as they have other benefits like piercing shielding/inflicting bleeding/rads with certain mods

2017-01-08 04:16 UTC, Iamgoofball commented
1. try doing your long distance shots with them, the spread will fuck you, I could always up the spread though
2. working as intended

2017-01-08 04:18 UTC, kevinz000 commented
Why would I do that when your barrels ruin the point of long distance shots anyways? :^)

2017-01-08 04:20 UTC, Iamgoofball commented
i upped the range on barrels recently, it's up to:
short: 14(2 screens)
medium: 28(4 screens)
long: 50(just under 8 screens)

2017-01-08 04:22 UTC, kevinz000 commented
Ruined my snipes, shit change.
Also, I gotta say, I love being able to snipe people down hallways with a 50 tile taser again.

2017-01-08 04:24 UTC, kevinz000 commented
everything i'm bitching about now i told you the last time it was testmerged.

2017-01-08 04:40 UTC, MrsTonedOne requested changes

2017-01-08 04:40 UTC, MrStonedOne commented on code/modules/research/rdconsole.dm
> +	name = "Guncrafting Console"
Change the name gunlathe console

Including the type

Stop breaking my emursions

2017-01-08 04:48 UTC, MrStonedOne commented
goofball, the best way to get feedback is to watch (without interacting or taking part in the convo) deadchat and ooc's reactions to them.

You do feedback gathering in a very hands on way, but that one, just leads to them trolling you, tainting the feedback, and you defending things, tainting the feedback because you now control the direction the conversion goes rather then let that evolve naturally.

If you need very specific feedback, the best way to gather that is to ask in deadchat or ooc if you weren't banned, a "I wonder if...." question and watch as somebody tries to find out next round.

Hands on feedback gathering taints the feedback, if they know you are a part of the convo they will either hold back their stronger criticisms or just troll you by reacting in the extremes.

Its how i do it.

2017-01-08 04:56 UTC, Iamgoofball commented on code/modules/research/rdconsole.dm
> +	name = "Guncrafting Console"
i don't want to edit 5 maps again, I'll do the name change for you though

2017-01-08 04:56 UTC, Iamgoofball commented
that's a good idea, I'll give it a try

2017-01-08 05:43 UTC, Iamgoofball commented
>Oh yeah, you can still use scopes without holding the gun.

cannot be fixed without serious rework of action verbs, this exists with the sniper rifle too but it's masked by being locked to hands

>Charge indicators are still not a thing

cannot be fixed without a massive amount of sprites from bman, and he's MIA at the moment, I'll add a shift click charge indicator in the mean time

>Taser sprites are once again, shit.

that's your opinion, if your gun is weak looking take it to the gym aka the warden and buff up those sprites with some better parts.

>Things like polonium rounds not logging and just saying bullet is going to give some edge cases in admin investigations.

Can you elaborate on "not logging"

>Giving security huge amounts of available ballistic weapons will change the balance quite a bit for thigns like deswords and shielding.

We'll see how it plays out then. People have been complaining about dual eswords.

2017-01-08 07:40 UTC, HankMoodyExperience commented
if this removes the regular guns **_again_** you better believe the servers will descend into shit
also the only people who complain about dual eswords are the ones who dont think to use a syringe gun, combat shotgun, or chuck spears instead of "spamclick stun baton free traitor loot"

2017-01-08 08:33 UTC, Iamgoofball commented
@HankMoodyExperience When was the last time you played during a guncrafting testmerge?

2017-01-08 11:59 UTC, Militaires commented
bman here.
@kevinz000 
on the tasers:

when spriting this you have multiple factors to have in mind.

1. that it fits with ALL other parts (meaning it has to have a conventional shape)

2. you have a size limit so that it doesnt override other parts (meaning it has to have a conventional shape)

this means that you can have a large detailed taser base or it looks fucked when you add ANY barrel.
spriting this isnt art school, you have to make sure it fits with literally all possible combinations and with that you cant be creative.

@Iamgoofball 
ill do the charge meters as soon as i can.

2017-01-08 15:16 UTC, Firecage commented
Well, now that it has proper inhands, I guess the only real issue is small balancing or small bug issues which can eventually be resolved as they pop up. If I knew how the heck to make a thumbs up in comments, I would.

2017-01-08 16:34 UTC, ma44 commented
Also kids, the assault rifle does 3 damage per bullet, with FMJ it's 6. 

The pistol on the other hand can do 24 damage per bullet with a mag size of 8 and with FMJ. Without FMJ it's 12 damage per bullet.

2017-01-08 17:04 UTC, Iamgoofball commented
God bless bman

2017-01-08 18:15 UTC, dannno commented
I mean the sprites are practically objectively a downgrade
and that's not a jab at bman or anything, we just have really good taser sprites and shit.

2017-01-08 23:04 UTC, XDTM commented on code/modules/projectiles/guncrafting/magazines.dm
> +	damage = 3
>3 damage
>30 max ammo base

Am i missing something or does unloading a full mag of an assault rifle not even do enough damage to crit a person

2017-01-08 23:10 UTC, Durkel commented
Yesterday I gave a traitor a bee gun frame for him to use and upon completion he fired two bees, one of which of intripolidol which completely ignored the five people around him and stung him instead killing him almost instantly. 10/10, best feature.

2017-01-08 23:15 UTC, Iamgoofball commented
Good man

2017-01-09 00:37 UTC, kilkun commented
we need more calibers and ammos and shit needs to make more sense.

thats my only criticism.

2017-01-09 05:40 UTC, Iamgoofball commented
we got shotguns and revolvers boys

2017-01-09 09:14 UTC, Ausops commented
im crying

2017-01-09 12:17 UTC, calzilla1 commented
Tested for a round and besides ALL OF FUCKING SEC RUSHING AT ME TO MAKE MEME GUNS its pretty fun. Only gripes I have is 1. Parts need more discription 2.more visual variaty(same gun different look) 3. The laser tazer toggle should have a color difference

2017-01-09 13:59 UTC, RemieRichards requested changes
surprisingly ok for goof.

2017-01-09 13:59 UTC, RemieRichards commented on code/modules/projectiles/gun.dm
> +	var/list/attachments = list()
lazy init this.

2017-01-09 13:59 UTC, RemieRichards commented on code/modules/projectiles/guncrafting/attachment.dm
> +/obj/item/weapon/gun_attachment/proc/can_attach(var/obj/item/weapon/gun/owning_gun) // Sorry but if I don't put a var in front of these it gives me duplicate definition errors pointing to here
No, we wen't over this, ```obj/item/weapon/gun/owning_gun``` your comment is wrong because you left a ```/``` at the beginning.

2017-01-09 14:00 UTC, RemieRichards commented
@Iamgoofball
>there's hardly any real estate for spriting

I made this system, see, to allow for overlays of larger sizes to fit onto 32x32 (but any size really!), ```center_image()```, if you need guns to be 64x32 then just -do it-

2017-01-09 14:02 UTC, RemieRichards commented on code/modules/projectiles/gun.dm
> +	var/uses_internal = 0
FALSE, etc.

2017-01-09 14:03 UTC, Iamgoofball commented
Then it takes up more than one hand slot

2017-01-09 14:05 UTC, RemieRichards commented
ok that's a fair concern time for 64x memes again.

2017-01-09 14:10 UTC, Iamgoofball commented on code/modules/projectiles/guncrafting/attachment.dm
> +/obj/item/weapon/gun_attachment/proc/can_attach(var/obj/item/weapon/gun/owning_gun) // Sorry but if I don't put a var in front of these it gives me duplicate definition errors pointing to here
I forgot to update this post conversation

2017-01-09 14:20 UTC, MrStonedOne commented
byond fixed the compile time issue from 64x, the primary issue now is the map editor fucking up randomly, but we could use fastdmm for that, and /vg/ reporting rsc corruption memes but i wasn't able to get that to reproduce on /tg/ like i was able to get the map editor fucking up to reproduce.

2017-01-09 15:24 UTC, RemieRichards commented
@MrStonedOne <i>it continues</i>

ignore the fact I was totally against 64x64 before it's definitely not that I've decided 32x32 is too cramped to sprite in.

Thought i definitely don't want the cute aspect of 32x32 to be lost.

2017-01-09 17:25 UTC, Firecage commented
Goof, would it be possible to make a build guns name automatically update when you construct it so we don't see people shooting eachother with Projectile Gun Frame and Energy Gun Frame?

Like, if you add the Shotgun bit, the gun is renamed to Shotgun, if you add the Automatic bit, it is renamed Automatic Shotgun. But it only counts if it hasn't been renamed via a pen yet. If it has been renamed already, it keeps that snowflake name.

2017-01-09 17:26 UTC, GunHog commented
Seconding Firecage here, I also suggested this once before!

2017-01-09 17:27 UTC, Militaires commented
@dannno yeah the original sprites are objectively better but this is as good as i can get it to be when you have size constraints to have everything fit together

2017-01-09 17:38 UTC, Firecage commented
Another tiny nitpick. Can you perhaps change some of the gun parts to have more informative descriptions? Them being silly is all and good, but it doesn't exactly help when building a gun. Like I still have no idea what the actual difference between the barrel lengths are except that they determine where the gun fits(And guns with long barrels should probably be restricted to either the back or to suit storage slots, and not be easily put on your belt slot.)

2017-01-09 17:40 UTC, Militaires commented
@Firecage range

2017-01-09 18:12 UTC, Militaires commented
@kevinz000 @Firecage @dannno AUSOPS IS HERE AND GAVE GOOF  a shitton of actually good sprites i no longer need to do ths thank you and goodbye

2017-01-09 19:06 UTC, dannno commented
oh shit

2017-01-09 20:08 UTC, KorPhaeron commented
<Mrs_Sybil> AUTOMATIC ANNOUNCEMENT : Reply: | saulmyers Alright. Detective got new gun. The fancy, from lathe. How to reproduce the bug: use gun in hand to unload, screwdriver to disassemble it, assemble it back. Gun is loaded again. Infinite bullets. Also it doesn&#39;t fit in sholder holster.

2017-01-09 20:10 UTC, dannno commented
lets see those new sprites fucker

2017-01-09 20:27 UTC, KorPhaeron commented
Iamgoofball: Aside from bugs like that how are people enjoying it


Guncrafting aka "goofguns"
I enjoy it: 7
I do not enjoy it: 0
Stop merging or testmerging goof code have we not suffered enough?: 17

2017-01-09 20:32 UTC, Iamgoofball commented
Is that a meme poll

2017-01-09 21:40 UTC, GunHog commented
Ausops sprites? This just got **_INTERESTING._**

2017-01-09 21:59 UTC, dannno commented
post the FUCKING SPRITES

2017-01-09 22:12 UTC, Iamgoofball commented
I'm at work fuck

2017-01-09 23:14 UTC, KorPhaeron commented
HELP: Apeh/(Braydon Waldron) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): bugs in this update: shotguns can't be sawn off, tasers cant have flashlights added, if you remove armour gun(?|F) stays in suit storrage, detective revolver no longer fits in his holster...

2017-01-10 00:00 UTC, Iamgoofball commented
Sawing off has been replaced by just replacing the barrel with a short barrel, I could add a function to do that with a saw I guess

I need to add a flashlight attachment, yeah.

I don't know what's up with the suit storage thing, I'll see if I can reproduce it

I'll fix the holster

2017-01-10 01:58 UTC, Ausops commented
https://file.house/43Tz.dmi

goof can you add code for suppressors, preferably ones that pixel-shift since long barrel guns have no room left

2017-01-10 06:01 UTC, kilkun commented
eguns and tasers now fit in boxes and pockets. 

dont merge until goof fucking fixes it.

2017-01-10 06:03 UTC, Iamgoofball commented
When were you last playing because I fixed that

2017-01-10 06:32 UTC, kilkun commented
literally this round.

2017-01-10 14:27 UTC, Iamgoofball commented
How the fuck

2017-01-10 16:28 UTC, calzilla1 commented
Are these the new sprites? If so they are fucking awesome, maybe even better than the original

2017-01-10 17:33 UTC, Militaires commented
@calzilla1 ausops is a much better spriter than me.

much

2017-01-10 17:49 UTC, GunHog commented
Ausops is the best spriter we have ever had, period. (Sorry WJ, you are still great :heart:) Those sprites are amazing! Once Goof gets charging and state colors working, they will be fantastic!

2017-01-10 17:49 UTC, Firecage commented
@Militaires Dude, while Ausops sprites are better, your sprites were still pretty good, and I did like them.

2017-01-10 17:51 UTC, GunHog commented
Agreed with Firecage. We went from pure codersprite garbage (originals), to good stuffs (Militaries), to absolute amazeballs!

2017-01-10 17:57 UTC, Firecage commented
Anyway, whether it is Militaries's sprites, or Ausops's sprites. I do like how energy weapons actually now looks like something humans would design. Aka looking more like the design of Ballistic weaponry, instead of looking like something which aliens would design.

@Iamgoofball Would it be to unbalanced if you made the Gunlathe able to mmake an Advanced Energy Gun frame, providing R&D did some research? Since it is quite a pity when the armory used to have Energy Guns, and now they don't anymore, and also no way to make them.(Also wouldn't mind if you began removing most gun types, like the Laser Cannon, from the normal Protolathe and instead moved parts to make one over to the Gunlathe.)

2017-01-10 19:01 UTC, Iamgoofball commented
Science might murder me

2017-01-10 19:01 UTC, bgobandit commented
sprites don't update when changing modes from disable to kill or w/e, noticed it on the e-gun hos starts with

2017-01-10 19:02 UTC, Firecage commented
@bgobandit I think Goof is already solving it, since it is a known issue.

2017-01-10 20:51 UTC, Iamgoofball commented
Wait it's busted on the default guns too? That's odd.

2017-01-11 02:49 UTC, kilkun commented
shotguns werent dropping shells. the ones in the armory, i dont know about hand made ones

2017-01-11 15:37 UTC, calzilla1 commented
Can you please add the new gun sprites to the body

2017-01-12 04:51 UTC, ma44 commented
Goofbalance in progress.

2017-01-12 05:22 UTC, Iamgoofball commented
new sprites in OP

2017-01-12 06:14 UTC, Ninja137 commented
Is this available to people other than sec?

2017-01-12 06:56 UTC, Signmark commented
@Ninja137 you violated the NAP bye
*nuclear explosion*

2017-01-12 07:52 UTC, Mervill commented on tgstation.dme
> +#include "_maps\runtimestation.dm"
Can't do that in a christian ~~manga~~ repository

2017-01-12 08:21 UTC, dannno commented
it's unreal how much more palatable this PR is with these new sprites

2017-01-12 18:33 UTC, unusualcrow commented
I'd like to see makeshift parts, extra parts on away missions and mining,  and different magazine sizes

2017-01-12 20:24 UTC, GunHog commented
One step at a time!!

2017-01-12 21:53 UTC, calzilla1 commented
Also CAN SEC FINALLY MAKE SHIT GUN SHELLS?!

2017-01-12 22:29 UTC, calzilla1 commented
Shot*

2017-01-13 01:42 UTC, Iamgoofball commented
Yeah

2017-01-13 16:52 UTC, Firecage commented
@Iamgoofball Mmm, tiny issue with inhands. When you switch, like, an energy gun between laser and disable, it doesn't update the inhand to respect that.

2017-01-13 17:36 UTC, Iamgoofball commented
I'll look into it, that's so dumb

2017-01-13 17:36 UTC, Iamgoofball commented
The inhands is going to be tough to solve

2017-01-13 17:57 UTC, Firecage commented
@Iamgoofball Interestingly, at both the Robotics and Core sections, the Experimentation lab's R&D console ALSO lacked download access. I could swear it had it previously, this is weird.

2017-01-13 19:43 UTC, Firecage commented
@Iamgoofball I might just have noticed a major balance issue, where even an admin, @Durkel , PM'ed asking me 'How many shots does that fucking gun have'. Basically, I build a gun using a super energy gun frame. Not even the highest level of energy gun frames. I emptied 100 disabler shots into Smells I believe when he PM'ed me, and it was about a quarter the way yet if the charge indicator is to be believed. Only after a fuckload more shots did it look like it was reaching nearly halfway....maybe.

2017-01-13 21:35 UTC, KorPhaeron commented
>disablers with 100 ammo

goof why

2017-01-13 21:57 UTC, Firecage commented
@KorPhaeron And the disabler wasn't even quarter way after like a 100 shots. Rough estimate though.

2017-01-13 22:11 UTC, Iamgoofball commented
i guess I can make better frames cost diamond stacks

2017-01-13 22:16 UTC, Firecage commented
Mmm, Perhaps, though I think that wouldn't be enough, since a few hundred shots for a frame which isn't even the best one is a bit much.

2017-01-13 22:36 UTC, PKPenguin321 commented
Hundreds of shots in one gun without any kind of charging is like admin only shit

2017-01-13 22:36 UTC, PKPenguin321 commented
Hundreds of shots in one gun without any kind of charging is like admin only shit

2017-01-13 23:28 UTC, dannno commented
What is the actual purpose of that?
Like. What were you thinking when you added a thing that has estimated 400-500 shots?
What's the point? In what scenario would that be a fine thing to have? 
Making it more expensive doesn't help anything. There's no point in that kind of thing being in the game.

2017-01-13 23:55 UTC, KorPhaeron commented
ma44: with FMJ, its 120 damage for a slug

ma44: 180 damage if a victim gets hit with all 6 pellets

Firecage: KorPhaeron: Know whats a fun Goofgun? Automatic Laser Gun doing 2x the normal damage with a few hundred shots worth of ammo

This is turning into a trainwreck

2017-01-13 23:58 UTC, Anonmare commented
Yeah the max ammo for energy guns should not exceed 30 at the very most (Pulse Destroyers are an admin-only exception). Energy weapons should have poor ammo capacity but are easy to "reload" (I.E. Rechargers), it's alright for a ballistic weapon to have 100 bullets (within reason, I'll raise my eyebrows if you make a 100 magazine 50. cal sniper rifle) since ballistic guns can only be reloaded by you carrying extra ammo, or manufacturing from materials from a specific machine.

2017-01-14 00:21 UTC, Firecage commented
@Iamgoofball Yah, the last round just proved that, well, the energy frames gives to much capacity. Imagine single handedly shredding 3 blobs to death without a sweat.

2017-01-14 01:00 UTC, kevinz000 commented
For anyone who thinks this thing is a good, well balanced idea
1. https://gyazo.com/5877bb07076a2fcdbd5f666788cdfadd
2. You can spam a bluespace energy frame with lasers for about 2.5 minutes
3. If you add energy collapsers to it it doesn't change enregy cost so it just became a full auto laser cannon
4. KAs are completely redundent just get one of those and you're golden
5. roundstart explosive/meteorshot/hemorrage/incendiary assaultrifles/shotguns

2017-01-14 07:25 UTC, Iamgoofball commented
Do you just want all the guns to be 1:1 with existing guns with no modification potential or what because it seems like you hate anything that isn't 1:1

yeah sure some of it is dumb but that's **exactly why we testmerge**

2017-01-14 07:27 UTC, Iamgoofball commented
also I'll just remove the upgraded frames, they were an iffy idea and I threw them in for testing purposes

2017-01-14 08:03 UTC, Firecage commented
@Iamgoofball  Or you could rebalance said frames instead of removing them. Add specialized cell types to be used in those frames which isn't overpowered. Like the normal powercell has a charge of 1k. Then the next upgrade, gives a cell worth 10k, aka the high once. That is a massive leap.

So why not add specialized cells to be used in these frames?
Base: 1000
High: 1500
Super: 2000
Hyper: 2500
Bluespace: 4000 (Since, you know, bluespace tech. And it would make it worth it to research for it, and get the mats to build it.)

Then we can keep the upgraded frames, but they aren't OP, and give you a few more shots each upgrade, with the bluespace one giving you 4x more shots, instead of where the current bluespace one gives you 40x more shots

2017-01-14 09:11 UTC, dannno commented
Goof, for the love of god.
Are you actually unable to conceive of modifications that AREN'T JUST BATSHIT CRAZY?
Did you really make modifiers that give guns functionally unlimited ammo and think "Yeah this is going to be sweet, people are going to LOVE this"
What did you actually expect with some of this??

>Do you just want all the guns to be 1:1 with existing guns

Yes. Gun balance as it is now is in, IMO, one of the best places it's ever been. Maybe the best. Shaking that boat for gimmick bullshit and unlimited ammo is simply a bad idea.

>with no modification potential 

only if you can't come up with any intelligent modification ideas. 
Guncrafting is nice on paper. But you're going to have to think harder to make it actually feasible and not awful in practice.

2017-01-14 09:12 UTC, dannno commented
ideally this should be expanding on and at least TRYING to improve gun balance
but you're just throwing it all up in the air, man

2017-01-14 09:18 UTC, KorPhaeron commented on code/modules/research/designs/guncrafting_designs.dm
> +	materials = list(MAT_METAL = 800, MAT_GLASS = 900, MAT_GOLD = 120, MAT_SILVER = 150, MAT_GLASS = 160, MAT_DIAMOND = 160, MAT_TITANIUM = 300)
Man they dont even cost a single sheet either

2017-01-14 09:19 UTC, KorPhaeron commented
I feel like we have hit that point in a PR where the balance is too insane to ever get merged but too much work has been put in to ever get closed

2017-01-14 11:12 UTC, kevinz000 commented
So miners being good is now an excuse for roundstart explosive and meteor shells that before took the cooperation of 3 departments for the former? Automatic shotguns? Not even gated behind the most easy thing to get in the game, R&D levels? I'm not asking to make it 1:1 with existing guns, but making it completely overpowered is just as shit, and tasers are going to be even more GGNORE when you make them move 2x speed full accuracy with a 50 tile range, which is worse than before as atleast in the old days before paptasers they weren't as fast. How is "You're able to get the materials after 5 minutes" ever a good excuse to make everything roundstart, and how is "stuns exist anyways" a good excuse to make the lethal alternative be insane?

2017-01-14 11:13 UTC, kevinz000 commented
Oh, and if you bugtested a little you'd notice projectiles curving MID FLIGHT instead of being spread before  firing. What the fuck?

2017-01-14 11:16 UTC, kevinz000 commented on code/modules/research/designs/guncrafting_designs.dm
> +	materials = list(MAT_METAL = 800, MAT_GLASS = 900, MAT_GOLD = 120, MAT_SILVER = 150, MAT_GLASS = 160, MAT_DIAMOND = 160, MAT_TITANIUM = 300)
Why am I getting yelled at for buffing science when goofball is allowed to make 40x capacity guns that take clickspamming/automatic fire for more then 2 full minutes to drain and let someone take three blobs down in a row solo?

2017-01-14 12:04 UTC, kevinz000 commented
Nice job making science weapons useless, with your 50 tile security stun snipers, and all that other unbalanced crap.

2017-01-14 12:14 UTC, kevinz000 commented
Something else: Easily obtained projectile weapons.
Weren't autorifles removed from delta because traitor/antags were balanced with energy weapons or something in mind? This is even worse as you can print out AUTOMATICS and SHOTGUNS that stun. Oh yeah, and uh, if you bugtested revolvers/shotguns you'd notice ammo loading bugs.

2017-01-14 13:51 UTC, Haevacht commented
THere WAS a consensus that your balance attempts were shithouse and it was OP.

2017-01-14 13:54 UTC, kyrahabattoir commented
On a sidenote, is there a reason why bullets aren't tied into the chem reaction code?

2017-01-14 15:00 UTC, Ausops commented
i don't really care if the sprites never get used

however goof, properly taking your time to balance these would be really beneficial to you, not just the server

2017-01-14 15:53 UTC, ma44 commented
Good thing you can put FMJ into a .357 as a traitor, so you get 120 damage .357s. Same with slug shotgun ammo.

2017-01-14 18:31 UTC, MrStonedOne commented
This right here, is the fucking issue with 2x/3x/4x memes on tech levels. 

it has to be more moderated then that, other wise you have the case where a hypercap becomes op.

2017-01-14 20:56 UTC, Iamgoofball commented
Why don't you cunts balance it

2017-01-14 20:57 UTC, MrStonedOne commented
I've been raising the alarm on 2x,3x,4x RnD since you added bluespace parts.

I remember mentioning something about either in the pr or in coderbus.

2017-01-14 21:15 UTC, dannno commented
>Why don't you cunts balance it

😄

2017-01-14 21:39 UTC, Firecage commented
@Iamgoofball Uhhhhh, no. It was your job to originally make it balanced, it isn't the job of other people to rebalance things which you failed to balance, so you can't complain about that. Besides, I remember a lot of people telling you bluespace stock parts was highly unbalanced.

2017-01-14 22:06 UTC, dannno commented
how you gonna be like "yeah i'm gonna add this guys its gonna be really cool" and then throw a pile of stuff on the ground and say "YOU figure it out"

2017-01-14 23:14 UTC, Iamgoofball commented
@Firecage you have all stated my balance is shit, you give it a shot

2017-01-14 23:20 UTC, Firecage commented
Why would I want to spend time fixing simple balance issues of yours where a test merged wasn't even needed to notice them? Besides, you rarely even listen when someone points something out, or only look at one of those points, and ignore the rest.

Honestly, Kor made an excellent point. At the state this PR is currently in, its doubtful it would be permamerged any time soon, if ever. Yet to much work has gone into it to just close it. Well, if it does end up closed, perhaps someone else can pick up the pieces and make a working system, where they atleast try to fix the balance and bug issues which can easily be spotted testing on a local repo. And then fix the issues which pops up on a test merge.

Heck, it wouldn't even matter if you removed the more advanced energy frames. As stated previously, this is just one of the many issues which causes this incarnation of guncrafting to break the game in every concievable way. You somehow made Ebows and Double Eswords and Wizards and such seem like extremely well balanced things.

2017-01-14 23:20 UTC, Iamgoofball commented
wizards aren't supposed to be balanced

2017-01-14 23:21 UTC, Firecage commented
Of course not. Yet this entire system is so broken it makes wizards seem perfectly well balanced and not OP.

2017-01-15 00:27 UTC, ma44 commented
https://github.com/Iamgoofball/-tg-station/pull/8

Some pretty big changes, please discuss here :)

2017-01-15 05:00 UTC, kevinz000 commented
HEY GOOFBALL
IF YOU TESTED YOUR SHIT
YOU'D NOTICE THAT GUNCRAFTING IS COMPLETELY BROKEN NOW.
Don't even bother saying that you tested shit when the printers dont' even work on this testmerge. If you so much as touched it you'd see that it was broken but no, you had it testmerged and now people are complaining. Good job.

2017-01-15 05:02 UTC, GunHog commented
T E S T I N G

2017-01-15 08:26 UTC, Iamgoofball commented
why are you complaining

2017-01-15 10:33 UTC, Firecage commented
Oh, I don't know. Perhaps people complain something is broken when, I don't know, its broken as fuck?

2017-01-15 10:48 UTC, Iamgoofball commented
if you cant print the parts it means it's not unbalannced

2017-01-15 13:03 UTC, kevinz000 commented
>if security can't get any guns from the armory it's balanced

2017-01-15 18:29 UTC, dannno commented
gun balance as we know it is the culmination of like all of the years that the game has been in work
i'm not sure that pawning it all off on one guy to rebalance it all entirely around some stupid gimmick shit is going to work out so good

2017-01-15 18:31 UTC, GunHog commented
Danno, the concept is great, it is just the poor implementation.

2017-01-15 19:24 UTC, dannno commented
the concept of what
the concept of modular guns? because yeah sounds cool
the concept of burst fire and infinite ammo guns and shit is terrible

2017-01-15 19:56 UTC, GunHog commented
Modular weapons. Upgrades are nice, they just need to not be so powerful. More shots at high tech levels, with the highest level (bluespace) being maybe twice the roundstart default, and the upgrades taking something away (range in exchange for power, for instance) is idea. It needs tweaking natrually, but the idea itself is fine.

2017-01-15 20:04 UTC, ma44 commented
Pawning it off to one guy is better than getting goof to balance it

2017-01-15 20:40 UTC, kevinz000 commented
You broke it so uh.

2017-01-15 20:45 UTC, Firecage commented
@Iamgoofball In IRC, MSO said he had testmerged it without either you or ma44 telling him to. So I don't know why you claim you had logs of him having it testmerged.

2017-01-15 21:33 UTC, GunHog commented on code/modules/research/rdconsole.dm
> +		if (!(being_built.build_type & PROTOLATHE) && !(being_built.build_type & GUNLATHE))
There HAS to be a better fix for this...

2017-01-15 21:53 UTC, Iamgoofball commented
huh

i swear ma44 mergebegged it

maybe he just picked it up later

2017-01-15 21:53 UTC, Iamgoofball commented
fuck it i'm goig to work on animal farm

2017-01-16 00:26 UTC, Firecage commented
@Iamgoofball Okay, animal farm is something I 100% support you on.

2017-01-16 00:52 UTC, Haevacht commented on code/modules/research/rdconsole.dm
> +		if (!(being_built.build_type & PROTOLATHE) && !(being_built.build_type & GUNLATHE))
Yeah probably. This was just what worked at the time.

2017-05-21 10:19 UTC, Steelpoint commented
This idea has merit and I think should be revived. However it needs a lot of balance work. The idea is fine but the balance is shit, I'm sorry to say.

-----

Right off the bat, security should, at round start, be only able to make Energy weapons. No Shotguns, no Revolvers, no Pistols and no Assault Rifles. To list the problems, at round start sec can pump out automatic shotguns akin to Combat Shotguns, powerful Revolvers (that don't work), robust Pistols that deal 20 damage per bullet, and automatic rifles that not only deal 20 damage but also fire on automatic. All this being cheap to produce en mass.

Restricting round start sec to making disable, stun or laser rifles is a good start. 

I like how the higher tech stuff requires security to go to RnD, get a data disk, upload the research and then manually put it into the gun crafting machine, I think this should stay.

Station research should allow sec to customise their energy weapons in a balance way, maybe more energy cell power but at the expense of accuracy or how far your projectile can go.

--------

I think the only way sec should be able to make ballistics is if they level up illegal tech research. This would incentivise sec to capture and turn over Syndi tech to RnD so they can then produce ballistic weapons. 

-------

Everything base the most basic, round start, equipment also needs to be more expensive minerals wise.

-------

Don't give up on the idea Goof, if this is balanced out well it can be great addition. But having round start weapons that put the Syndicate to shame is never going to work.

2017-05-21 16:37 UTC, GunHog commented
Well, Steelpoint, you will have to take over the code and balancing! Completely, 100%. Do not let anyone but a maintainer, MSO, or Cyberboss touch it.

2017-05-21 17:25 UTC, Steelpoint commented
Implying I have not even a 1/10th of the skills necessary to even start resurrecting this. 

I'm simply stating how I feel that this concept was blown up simply due to it having non-existent balancing done to it, and that if it got some attention to balance and round interaction that it can fit in well with the game.

2017-05-21 17:36 UTC, Iamgoofball commented
>maybe more energy cell power

This isn't a good idea, we tried it and it went over badly.

>E: Also the sprite need to look black like the current Egun.
You can just do a field strip and spraypaint it if you want it to look black.

2017-05-21 17:50 UTC, Steelpoint commented
The sprites more a separate issue I brought up as a minor point.

I'm no Captain of Balance but the gist of what I'm saying is that round start sec can make Laser Guns, Disablers or Tasers. With minor variations based on attachments and what not, maybe a sniper stock can increase range and damage but at the cost of rate of fire and your shots "missing" targets at less than three tiles, or similar.

Later round stuff can be more interesting but should still be balanced around the stock Energy Gun and similar.

I think the forums serve better as a discussion for balancing, 

The point is, keep ballistics to illegal tech (sans basic shotgun ammo) and keep the end game lasers somewhat balanced.

2017-11-10 07:55 UTC, Jordie0608 commented
You're drunk goober go to sleep.

2017-11-10 07:55 UTC, closed without merging

2023-02-07 21:31 UTC, Overuseddart commented
Perhaps if costs were increased dramatically, this becoming late game and tied in with sci, this could be balanced. Anomaly cores used to make special ammo, and rnd making more guns acessable. Then perhaps an emag effect to unlock more guns and more dangerous guns. Maybe then this cool idea could be balanced.