Squashing cockroaches now makes a mess
tgstation/tgstation pull request #22974
Opened 2017-01-12 14:59 UTC by coiax

Fixes #22951.

:cl: coiax
bugfix: Squashing cockroaches now leaves a mess.
/:cl:

2017-01-12 17:25 UTC, ChangelingRain commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
>  	new /obj/effect/decal/cleanable/deadcockroach(get_turf(src))
but what if the cockroach has more than 1 health?

2017-01-12 18:33 UTC, coiax commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
>  	new /obj/effect/decal/cleanable/deadcockroach(get_turf(src))
That's intentional. I considered the case of a human-level intelligence cockroach that has 200 health. It seems unfair to just get suddenly crushed, so if a cockroach gets more than 1 health, it survives fine. See https://youtu.be/L7W2HKtdWRo

2017-01-12 19:06 UTC, Core0verload commented
Removing cockroaches would be a better fix.

2017-01-12 19:19 UTC, RemieRichards commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
>  	new /obj/effect/decal/cleanable/deadcockroach(get_turf(src))
but they'll poop out gibs everytime they're stepped on?
200 HP is 200 gibs.

2017-01-12 19:21 UTC, coiax commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
>  	new /obj/effect/decal/cleanable/deadcockroach(get_turf(src))
Well don't step on them then

2017-01-12 20:40 UTC, ChangelingRain requested changes
>Well don't step on them then

This is not acceptable reasoning please fix your shit

2017-01-12 20:45 UTC, coiax commented
I'm confused, stepping on a sentient cockroach is rude anyway, and it's a rare event?

This is not a janitor friendly codebase

2017-01-13 22:57 UTC, optimumtact commented on code/modules/mob/living/simple_animal/friendly/cockroach.dm
>  	new /obj/effect/decal/cleanable/deadcockroach(get_turf(src))
Come on, make it only gib when they actually die, this is lazy work and only I get to do that

2017-01-18 20:57 UTC, ChangelingRain commented
All you had to do was fix the issue! #23117

2017-01-18 20:57 UTC, closed without merging