Fixes syndicate commandos not leaving gibs
tgstation/tgstation pull request #23050
Opened 2017-01-16 05:08 UTC by Iamgoofball

Fixes #22865

2017-01-16 05:14 UTC, Haevacht commented
This actually tested?

2017-01-16 05:23 UTC, Iamgoofball commented
yes

2017-01-16 05:32 UTC, Jordie0608 commented
This makes the type identical to its parent: https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/hostile/syndicate.dm#L75
Which means it's kinda pointless, make it a blank type or change the portal storm spawn types to the parent and remove the `/noloot` sub.
Either way you'll also need to do this change for the ranged syndicate commando as they're also spawned by this event: https://github.com/tgstation/tgstation/blob/master/code/modules/events/portal_storm.dm#L11

2017-01-16 05:54 UTC, KorPhaeron commented
This doesn't fix the problem

2017-01-16 05:57 UTC, Iamgoofball commented
I just spawned a syndicate commando and he exploded into gibs

You clarified the lack of gibs was a bug in the issue report yourself

2017-01-16 12:30 UTC, AnturK commented
Change the commit message.

2017-01-16 12:45 UTC, XDTM commented on tgstation.dme
> +#include "_maps\runtimestation.dm"
forgot the map on, although i guess this definitely proves you tested

2017-01-16 18:17 UTC, ma44 commented
Just make the gibs of a body the loot instead of making them drop energy shields ya donk

2017-01-16 22:07 UTC, Iamgoofball commented
That's literally what I did here

2017-01-16 22:50 UTC, Mervill commented
Does this really fix the referenced 56 issues?

2017-01-16 22:53 UTC, MrStonedOne commented
This does not fix those issues, this is goof ball trying to meme his way out of the freeze

2017-01-16 22:54 UTC, Iamgoofball commented
all those issues are either 1. super fucking old and no longer exist, or 2. issues with a since-refactored system

2017-01-16 22:55 UTC, Mervill commented
![](https://pbs.twimg.com/profile_images/2349507011/damn.gif)

2017-01-17 01:52 UTC, MrStonedOne commented
![image](https://cloud.githubusercontent.com/assets/7069733/22004963/7bc50b76-dc14-11e6-937b-3bc1bb5f6e9d.png)

2017-01-17 01:53 UTC, Cyberboss requested changes
> Commit message

2017-01-17 01:58 UTC, closed without merging

2017-01-17 02:11 UTC, KorPhaeron commented
Does that actually work?

2017-01-17 02:23 UTC, ChangelingRain commented
Yes

2017-01-17 02:26 UTC, Iamgoofball commented
you can use it on PRs too

2017-01-17 03:49 UTC, Jordie0608 commented
Hah, this would be funny enough to pass if it wasn't completely scummy.