Autism Fort Patch - Emitters and Tesla coils can now be used for DEFENDING YOUR TURF!
tgstation/tgstation pull request #23238
Opened 2017-01-22 03:32 UTC by kevinz000

Gives emitters and tesla coils a wire that when pulsed will make emitters fire a shot and tesla coils to send out lightning. Both have cooldowns reliant on the stock part rating inside them!
:cl:
rscadd: Emitters and Tesla Coils now have activation wires!
rscadd: Emitters will shoot out an emitter bolt when pulsed, regardless of it is on.
rscadd: Tesla coils will shoot lightning when pulsed, if it is connected to a cable that has power.
/:cl:

2017-01-22 04:15 UTC, kilkun commented
interesting idea

2017-01-22 04:19 UTC, jughu commented
But mekhi before we run in any intresting bugs... does it converse power?

2017-01-22 04:20 UTC, jughu commented
Because if it dont i tottaly can make a paper plane V2  with a prox/signaller assembly and a signaller and a monkey disposal system

2017-01-22 05:49 UTC, kilkun commented
stfu dude dont tell the coders how to fix the game

2017-01-22 05:49 UTC, kilkun commented
do you hate fun???

2017-01-22 08:47 UTC, PKPenguin321 commented
This is the opposite of what a tesla coil does :thinking:

2017-01-22 09:55 UTC, Core0verload requested changes

2017-01-22 09:55 UTC, Core0verload commented on code/modules/power/tesla/coil.dm
> +	tesla_zap(src, 10, power/shock_coeff)
Tesla coil would create INFINITE POWER again, like the paper engine. Make sure to fix it, then double-check the fix.

2017-01-22 09:55 UTC, Core0verload commented on code/modules/power/singularity/emitter.dm
> +			A.xo = 0
Looks like new shitcode, but it's a copypaste of old shitcode. How about fixing it anyway?

2017-01-22 11:00 UTC, kevinz000 commented on code/modules/power/singularity/emitter.dm
> +			A.xo = 0
It's the same thing that I moved over for the proc.

2017-01-22 11:00 UTC, kevinz000 commented on code/modules/power/tesla/coil.dm
> +	tesla_zap(src, 10, power/shock_coeff)
HMMMMMMMMMMMMMMMMMMMMMMMMMMM
How do I fix this.. Eh, I'l check my math later, see if I can balance it out.

2017-01-22 12:00 UTC, XDTM commented
Hey can you instead make two tesla coils properly rigged form a wall of light like in dishonored?

2017-01-22 20:34 UTC, optimumtact commented on code/modules/power/tesla/coil.dm
> +	tesla_zap(src, 10, power/shock_coeff)
Just use more power than it gives dummy

2017-01-22 21:31 UTC, Iamgoofball commented on code/modules/power/tesla/coil.dm
> +	tesla_zap(src, 10, power/shock_coeff)
tesla coils already drop half the power

2017-01-22 21:39 UTC, Kromgar commented
>Disintrigrating walls


Balanced

2017-01-22 21:54 UTC, jughu commented
@kevinz000 also does the emitter pulse firing have a cooldown so i dont can create some super blob remover by spam pressing  a remote

2017-01-22 22:08 UTC, Iamgoofball commented
@XDTM just use shield generators to do that

2017-01-23 00:48 UTC, ExcessiveUseOfCobblestone commented
![spectrum tower](http://vignette2.wikia.nocookie.net/cnc/images/3/34/Spectrumtower.JPG/revision/latest?cb=20100727085051)

2017-01-23 00:56 UTC, Anonmare commented
@PKPenguin321 Do you mean in real life? Because I'm pretty sure that is how they work

2017-01-23 18:52 UTC, dannno commented
sounds funny

2017-01-27 23:44 UTC, merged

2017-01-28 16:44 UTC, CPTANT commented
emitters fire without even being bolted to the ground or being powered when pulsed.....

2017-01-28 18:40 UTC, PKPenguin321 commented
Mekhi code back at it again