Fixes lube slipping people when they are buckled
tgstation/tgstation pull request #23246
Opened 2017-01-22 18:47 UTC by Sometinyprick

It doesn't really make sense to slip while buckled
:cl:
fix: you can no longer slip while buckled
/:cl:

2017-01-22 21:59 UTC, PKPenguin321 commented
Not sure how I feel about vehicles being a lube shield. Stuff like scooters and skateboards would definitely still bail out.

2017-01-22 22:06 UTC, lzimann commented
make the vehicles slip maybe instead of the mob

2017-01-22 22:54 UTC, Sometinyprick commented
it doesn't really make any sense for someone being buckled in on a chair or something to slip when pushed over lube, but i'll try make it so certain vehicles slip i guess.

2017-01-24 15:16 UTC, Sometinyprick commented
I tried making vehicles slip but it turned out odd, although I guess it makes sense for scooters and skateboards to slip the user since i would assume they are powered by your feet.

2017-01-26 12:34 UTC, AnturK requested changes

2017-01-26 12:34 UTC, AnturK commented on code/game/turfs/open.dm
> +			if(!(istype(C.buckled,/obj/vehicle/scooter) && lube))
Make this vehicle property at least, or better a atom/movable function.

2017-01-26 12:56 UTC, jughu commented
ATV should be immune to lube only because all terrain memes

2017-01-29 20:54 UTC, optimumtact commented on code/game/turfs/open.dm
> +			if(!(istype(C.buckled,/obj/vehicle/scooter) && lube))
Yeah do this

2017-01-31 22:20 UTC, Sometinyprick commented on code/game/turfs/open.dm
> +			if(!(istype(C.buckled,/obj/vehicle/scooter) && lube))
at some point sure, i have to redownload everything. i guess i will get around to doing it at some point

2017-02-04 03:30 UTC, closed without merging