Adds test merged PR title and author to the revision data
tgstation/tgstation pull request #23359
Opened 2017-01-26 17:00 UTC by Cyberboss

:cl: Cyberboss
add: Test merged PRs are now more detailed
/:cl:

2017-01-26 18:10 UTC, coiax commented
WE SHOULD TEST MERGE THIS

2017-01-26 18:11 UTC, Cyberboss commented
Muh recursions...

On Jan 26, 2017 1:10 PM, "coiax" <notifications@github.com> wrote:

WE SHOULD TEST MERGE THIS

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/23359#issuecomment-275464569>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHywel_ZRXvHSI_c-yzaeCpt5nO1iCQ3ks5rWOF5gaJpZM4Lu4Hh>
.

2017-01-26 22:12 UTC, Cyberboss commented
DNM bugs

2017-01-26 23:35 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
This is unlikely to be something i'll allow. As it is, right now you've given anybody with vv rights the ability to run remote code on the server, and i don't want to be playing games trying to do shell escaping in byond if we can avoid it.

There MUST be some way to get this info natively in byond.

If you believe you can not, I want a detailed explanation as to why you have to run cmd to run powershell to run curl to get a simple web page.

2017-01-26 23:40 UTC, coiax commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
Isn't test merging some sort of script you run on the server? Can't we have that script populate the place where it puts the testmerge information with the title and author as well?

2017-01-26 23:44 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
I'm not even entertaining that idea until i fully understand why `world`.`Export()` won't work.

2017-01-26 23:46 UTC, Cyberboss commented
@MrStonedOne World.Export won't work because the GitHub API requires HTTPS
which, of course, BYOND doesn't support.

On Jan 26, 2017 6:44 PM, "Kyle Spier-Swenson" <notifications@github.com>
wrote:

> *@MrStonedOne* commented on this pull request.
> ------------------------------
>
> In code/datums/helper_datums/getrev.dm
> <https://github.com/tgstation/tgstation/pull/23359>:
>
> > +		//warning, here be dragons
> +		/*
> +			                |  @___oo
> +			      /\  /\   / (__,,,,|
> +			     ) /^\) ^\/ _)
> +			     )   /^\/   _)
> +			     )   _ /  / _)
> +			 /\  )/\/ ||  | )_)
> +			<  >      |(,,) )__)
> +			 ||      /    \)___)\
> +			 | \____(      )___) )___
> +			  \______(_______;;; __;;;
> +		*/
> +		var/url = "https://api.github.com/repositories/[config.githubrepoid]/pulls/[line].json"
> +		var/temp_file = "prcheck[line].json"
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
>
> I'm not even entertaining that idea until i fully understand why world.
> Export() won't work.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/23359>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywevos6PtHdk_1f7iCq1xbN1PKgEpGks5rWS_GgaJpZM4Lu4Hh>
> .
>

2017-01-26 23:47 UTC, RemieRichards commented
@Cyberboss so why not:
```Byond -> Something that can HTTPS -> Github -> Something that can HTTPS ->Byond```?

2017-01-26 23:58 UTC, MrStonedOne commented
remie, the word you are looking for is http proxy.

Also, i strongly remember there being a way to tell github to not redirect the https connection.

but first, can you actually confirm you tried the http version in `world`.`Export()`.

2017-01-26 23:59 UTC, RemieRichards commented
@MrStonedOne who cares about the name I still got the concept right it's midnight and I have to go to bed gosh.

2017-01-27 00:00 UTC, Cyberboss commented
Yep it's github enforcing the HTTPS

On Jan 26, 2017 6:58 PM, "Kyle Spier-Swenson" <notifications@github.com>
wrote:

> remie, the word you are looking for is http proxy.
>
> Also, i strongly remember there being a way to tell github to not redirect
> the https connection.
>
> but first, can you actually confirm you tried the http version in world.
> Export().
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/23359#issuecomment-275552166>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywesXEndIT6m9NlBozq-WElLsw1V-Oks5rWTM2gaJpZM4Lu4Hh>
> .
>

2017-01-27 00:01 UTC, MrStonedOne commented
What did you get when you tried it?

2017-01-27 01:42 UTC, MrStonedOne commented
also, what's up with that powershell bit?

2017-01-27 03:36 UTC, Cyberboss commented
Http attempts just return null. The powershell is a workaround to just curl the page and save it to a file that we then read.

2017-01-27 04:17 UTC, MrStonedOne commented
but... why is powershell needed?

2017-01-27 05:54 UTC, Cyberboss commented
Cause basically CMD is so bad it doesn't have basic meet tools

On Jan 26, 2017 11:17 PM, "Kyle Spier-Swenson" <notifications@github.com>
wrote:

> but... why is powershell needed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/23359#issuecomment-275585738>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywemOwZxhGV7g4cGwIxujXZnFXSeZqks5rWW_WgaJpZM4Lu4Hh>
> .
>

2017-01-27 17:45 UTC, MrStonedOne commented
oh wait. curl is included in ps?

2017-01-27 17:46 UTC, Cyberboss commented
Yep

On Jan 27, 2017 12:45 PM, "Kyle Spier-Swenson" <notifications@github.com>
wrote:

> oh wait. curl is included in ps?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/23359#issuecomment-275727011>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywegzSX68EZv8U1UkSvKgzcITP9U37ks5rWi1GgaJpZM4Lu4Hh>
> .
>

2017-01-28 09:27 UTC, MrsTonedOne requested changes

2017-01-28 09:27 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		var/url = "https://api.github.com/repositories/[config.githubrepoid]/pulls/[line].json"
You need to validate that both config.githubrepoid and line are numbers (and/or text of numbers) or trialmins, AdminCanidates, etc could abuse this to take control of the server and make it execute raw code.

2017-01-28 21:51 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		world.log << "Invalid github repo id: [config.githubrepoid]"
What if somebody wants to just disable this feature

2017-01-28 21:52 UTC, MrStonedOne commented on code/controllers/configuration.dm
> +	var/githubrepoid = "3234987"  //default github
Don't have a default in here, have it in the config. that way somebody can disable the feature by commenting this out.

Giving server ops the ability to control if the game decides to access third party apis or run shell() commands is important enough, and making them have to define the config as a blank string is wasteful.

2017-01-28 21:53 UTC, MrStonedOne commented on code/controllers/configuration.dm
> +					config.githuburl = value
convert to a number here, then check isnum below, its cheaper and how most things do it.

2017-01-28 21:54 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		world.log << "Invalid github repo id: [config.githubrepoid]"
Make this a isnum() (like above) but add a if (!config.githubrepoid) above this if with just a simple return.

2017-01-28 21:55 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		. += "<a href='[config.githuburl]/pull/[line]'>#[line][details]</a><br/>"
Needs html sanitation or somebody could inject html into the chatbox by putting it in the title.

2017-01-29 18:46 UTC, Cyberboss commented on code/controllers/configuration.dm
> +					config.githuburl = value
We can't convert it to a num here because then it becomes an exponential and the url won't work properly

2017-01-29 22:55 UTC, MrStonedOne commented on code/controllers/configuration.dm
> +					config.githuburl = value
http://www.byond.com/docs/ref/info.html#/proc/num2text

2017-01-29 22:56 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +		. += "<a href='[config.githuburl]/pull/[line]'>#[line][details]</a><br/>"
http://www.byond.com/docs/ref/info.html#/proc/html_encode

2017-01-31 08:58 UTC, optimumtact commented
what is the state of this

2017-01-31 09:48 UTC, MrStonedOne commented
I'll test merge it to see.

2017-01-31 11:55 UTC, MrStonedOne commented
```
The following pull requests are currently test merged:
>#23493 
>#23494 
>#23359 
># 
>

```

2017-01-31 11:57 UTC, MrStonedOne commented
```
The following pull requests are currently test merged:<br/><a href='3234987/pull/23493'>#23493</a><br/><a href='3234987/pull/23494'>#23494</a><br/><a href='3234987/pull/23359'>#23359</a><br/><a href='3234987/pull/'>#</a><br/></div><br>
```

2017-01-31 11:59 UTC, MrsTonedOne requested changes

2017-01-31 11:59 UTC, MrStonedOne commented on code/controllers/configuration.dm
> +					config.githuburl = value
You kept the varname the same when you copy and pasted this!

2017-01-31 14:33 UTC, AnturK commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
🐧 🔫

2017-01-31 15:34 UTC, coiax commented
![image](https://cloud.githubusercontent.com/assets/609465/22471601/c479fc7a-e7ca-11e6-8d34-31699a4b3ea8.png)

PLEASE FINISH THIS PR

2017-02-04 09:59 UTC, MrStonedOne commented
Test merged on both servers

2017-02-05 11:12 UTC, Iamgoofball commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
:+1:

2017-02-05 20:09 UTC, AnturK commented
Any issues left with this ?

2017-02-05 20:26 UTC, MrStonedOne commented
most likely, every time it's been test merged it's done nothing.

2017-02-05 20:34 UTC, JJRcop commented on code/datums/helper_datums/getrev.dm
> +		var/command = "powershell -Command \"curl -O [temp_file] [url]\""
https://github.com/PowerShell/powershell/ ⚡️🐚 ➡️ 🐧

2017-02-05 22:13 UTC, Cyberboss commented
Still not working, but just realized I may be making an assumption about the contents of prtest.lk. Mind sharing one?

2017-02-06 00:21 UTC, MrStonedOne commented on code/datums/helper_datums/getrev.dm
> +	. = "The following pull requests are currently test merged:<br><br/>"
stop with the `/>`

Byond doesn't recognize it and the chatbox is not a real browse window, its byond fake html window.

2017-02-06 16:46 UTC, coiax commented
WHEN IS THIS GOING TO GET MERGED

2017-02-06 17:11 UTC, Cyberboss commented
WHEN IT WORKS

2017-02-06 20:27 UTC, Cyberboss commented
```
PR details download failed: shell exited with code: 1
```

2017-02-08 16:05 UTC, Cyberboss commented
This is the wrong approach and hacky. It needs to be something done from the testmerge tools. It's also holding up a fix so I'm gonna close this.

2017-02-12 18:32 UTC, Cyberboss commented
Gonna try something else

2017-02-12 19:57 UTC, PKPenguin321 commented on code/__HELPERS/unsorted.dm
> +//kevinz000 if you touch this I will hunt you down
:ok_hand:

2017-02-12 23:23 UTC, Cyberboss commented
It finally fucking works! This can be merged with MSO's permission.

2017-02-14 12:25 UTC, optimumtact commented
it's conflicting, but can @MrStonedOne approve this so I can finally merge it

2017-02-14 18:30 UTC, MrsTonedOne approved these changes
I see no glaring security issues.

2017-02-15 08:48 UTC, merged

2017-02-15 22:09 UTC, JJRcop commented
Hey did you know that powershell is actually cross-platform now? https://github.com/PowerShell/PowerShell