Improved Zombie Revive
tgstation/tgstation pull request #23601
Opened 2017-02-01 18:08 UTC by Robustin

Zombies are a little underwhelming in their current form, part of the cause is the long resurrection timer and lack of notice (most people don't realize they've been infected with Romerol) means that players simply close the game and you're left with rooms full of catatonic zombies. 

This improvement notifies that player that they aren't down for the count, and shorten the resurrection time to ~60s and reduces the "resurrection stun" by a couple seconds (its not fun to awaken just to be killed before you can even move again). This should help keep players in the game and make the zombies feel like a little more of a threat.

2017-02-01 18:09 UTC, jughu commented
This is a oldman "zombies" episode

2017-02-01 18:10 UTC, TehZombehz commented
Ugh.

2017-02-01 18:16 UTC, ChemicalRascal requested changes

2017-02-01 18:16 UTC, ChemicalRascal commented on code/modules/zombie/organs.dm
> +				convulses, as they gain a ravenous hunger in their \
Probably worth replacing they and their with [owner.p_they()] and [owner.p_their()]. For the sake of consistency. Simiarly above, on L59.

2017-02-01 18:16 UTC, RemieRichards commented
this is a revert.
and a badly done one at that.

2017-02-01 18:16 UTC, ChemicalRascal commented on code/modules/zombie/organs.dm
> +				convulses, as they gain a ravenous hunger in their \
Urgh, this wasn't meant to be a code-review review, just a comment but whatevs you're stuck with it.

2017-02-01 18:17 UTC, Robustin commented
Yea I fucked up and somehow managed to grab an old version of the file in my new repo, should be fixed.

2017-02-01 18:18 UTC, RemieRichards commented on code/modules/zombie/organs.dm
> +owner << "<span class='alertalien'>You are now a zombie!</span>"
no.

2017-02-01 19:04 UTC, XDTM commented on code/modules/zombie/organs.dm
> +		not even death can stop! You will rise again!!!</span>"
Multiple exclamation marks are the sure sign of an insane mind.

2017-02-01 20:30 UTC, KingPhilipIII commented
Why are zombies even attacking. Not like there are any brains for a few lightyears on this godforsaken station.

2017-02-02 04:59 UTC, Kromgar commented
Zombies should heal and move faster from eating brains... only issue is beheading would fuck over zombie spawn... i think?

2017-02-02 19:00 UTC, jughu commented
@KingPhilipIII everyone has a brain but they are in most cases empty

2017-02-04 01:43 UTC, merged