Buffs the valentines event
tgstation/tgstation pull request #23639
Opened 2017-02-02 19:20 UTC by KorPhaeron

:cl: Kor
add: Valentines day will now randomly pair up crew members on dates. The paired crewmembers will get an objective to protect each other at all costs.
/:cl:

The valentines holiday event will pair up crew members, giving them objectives to protect each other above all other loyalties.

If there is an odd one out with no valentine they get the martyr objective

I think randomly assigning crew to each other like this will lead to some memorable stories, especially if the nuke op is paired with the captain or something. It will be silly, but will only last a couple days a year.

2017-02-02 19:21 UTC, Shapsy commented
Cute!

2017-02-02 19:33 UTC, ShadowDeath6 commented
Make sure you can't force redtext by giving a traitor with a kill objective a protect objective on the same person

2017-02-02 19:38 UTC, KorPhaeron commented
@ShadowDeath6 

Falling in love with your assassination target is classic /tg/ culture

2017-02-02 20:01 UTC, PKPenguin321 commented
I've definitely used that tactic to kill a lizard assassination target when ERP was legal

2017-02-02 20:26 UTC, kevinz000 commented
This does not respect gender
Kek.

2017-02-02 20:27 UTC, optimumtact commented
\>currentyear + 1555

\>respecting gender

2017-02-02 20:32 UTC, ShadowDeath6 commented
>current year being 2557 
>implying the current year is 3572

2017-02-02 20:42 UTC, anconfuzedrock commented
tfw somebody undeniably has confirmed that oranges was wrong once

2017-02-02 21:17 UTC, JJRcop commented
how about a cuck version where two people get assigned the same date but that date is only assigned one of them

2017-02-02 21:31 UTC, jughu commented
70% of this valentine be gay

2017-02-02 21:59 UTC, JJRcop commented
KorPhaeron/kortg#28

2017-02-02 22:07 UTC, optimumtact commented
I will close the pr if any mention of the word cuck enters it's code

2017-02-02 22:26 UTC, KingPhilipIII commented
Captain+Nukie
Clearly the result of faking info on your online dating profile. 

And you must be really desperate if this supersedes all loyalties. 

What do I do if my assassination target is my date?

2017-02-02 22:31 UTC, PKPenguin321 commented
Anything for love

2017-02-02 22:37 UTC, KorPhaeron commented
@KingPhilipIII 

https://1d4chan.org/wiki/Story:Love_Can_Bloom

2017-02-02 23:16 UTC, KorPhaeron commented
For some reason people are getting multiple dates, and sometimes getting a date + martyr

2017-02-02 23:18 UTC, KorPhaeron commented
@tgstation/commit-access 

Can anyone who can actually code see what might be causing that?

2017-02-02 23:34 UTC, Cyberboss commented
Prolly bc you're fucking with the list while in the loop

2017-02-02 23:35 UTC, Cyberboss requested changes

2017-02-02 23:35 UTC, Cyberboss commented on code/modules/events/holiday/vday.dm
> +		if(valentines.len)
Try this
```
while(valentines.len)
    var/mob/living/L = pick(valentines)
    valentines -= L
```
etc...

2017-02-02 23:38 UTC, lzimann commented on code/modules/events/holiday/vday.dm
> +		if(valentines.len)
pick_n_take will do the removal for you

2017-02-03 00:11 UTC, KingPhilipIII commented
@KorPhaeron

How dare you link such heresy.

2017-02-03 00:13 UTC, JJRcop commented
I guess I'll just PR the thing if this gets merged either way

2017-02-03 01:02 UTC, Robustin commented
>Toss hardsuit and gloves to my crush
>Release Tesla

AT

ALL

COSTS

2017-02-03 01:08 UTC, Anonmare commented
>Be Syndicate Elite Nucl-
>Nah I'm just playing ya
>Be John Intern, Syndicate coffee boy turned Nuclear Operative
>Get assigned an objective to detonate a nuclear device stolen from NT on one of Nanotrasen's top secret research facilities
>Lol this gon b ez
>Blast our way onto the station, gunning down security officers, assistants, clowns etc.
>See Captain
>Notice she has the most biggest pair of... Eyes you've ever seen
>Seriously, did this station research anime?
>Gazes locked, you feel a soulbound connection and know you cannot harm your true love
>Turn your sights on your fellow Operatives and gun them down 
>Embrace your beloved
>Renounce your ties to the Syndicate, damn the consequences
>Ride with them to CentCom on the Emergency Shuttle
>Take off your hardsuit, mask and Night Vision Goggles
>Close your eyes and lean in for a kiss...

>Get tased and lased by the jealous HoS, setting off your macrobomb implant and destroying the shuttle
>No survivors
>Love_Can't_Bloom.JPEG

2017-02-03 01:10 UTC, KingPhilipIII commented
Hm. I can either fulfill my contract with the company threatening to murder me if I don't comply.
Or I might get laid if the date goes well.

Obvious choice.

2017-02-03 01:24 UTC, RandomMarine commented
Or just desperately plea with the other ops to plan to capture the captain alive.

2017-02-03 02:12 UTC, calzilla1 commented
ERP should be unbanned, but only for the couple

2017-02-03 14:18 UTC, KorPhaeron commented
@Cyberboss 

Thanks

2017-02-03 15:45 UTC, Robustin commented
Plz remove postround spam.

2017-02-03 16:41 UTC, KorPhaeron commented
@Robustin 

Too much work for something that will only be seen three days a year

2017-02-04 10:53 UTC, merged

2017-02-04 10:54 UTC, TehZombehz commented
>Get paired with meme lords
Thanks for giving me more reasons to suicide in a round.