Unpopularity contest
tgstation/tgstation pull request #23917
Opened 2017-02-09 23:12 UTC by Supermichael777

I'm considering adding anti borer but think that it may be use as a validing tool insted of truest ARR-PEE.

:cl: NT department of gender studies
add: Added the red-pill and a recipe.  It swaps your gender and cannot be used on others.
/:cl:

> We don't need memes at this time
Leave it for a couple of weeks.

Now literally volunteer only. 

![AHHHHHHHHH!](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQtUiQgeQXhxRiU3TeABpQe_X2EW3jAIxf5a_o8cSvKgXcbFAWQZA)

And 100% less clinical rape
![Better living through chemistry](http://pressblog.uchicago.edu/wp-content/uploads/dupont46.jpg)

Note this does affect your dna so it is PERMANENT THROUGH CLONING AND GENETICS.

2017-02-09 23:21 UTC, optimumtact commented
For what purpose or reason are you adding this?

2017-02-09 23:45 UTC, ShadowDeath6 commented
this can be used to meta whether or not they were male or female before being redpilled, hmmm....

2017-02-09 23:47 UTC, Thunder12345 commented
@optimumtact memes

2017-02-09 23:49 UTC, anconfuzedrock commented
you realise this is HARDER to make than the one in xenobio that works on others instantly, right? speaking of which you can literally run up to somebody and click them with the potion

2017-02-09 23:57 UTC, ExcessiveUseOfCobblestone commented
The joke about the gender surgery argument is that no one actually ever used the surgery.

2017-02-10 01:01 UTC, coiax commented on code/modules/reagents/reagent_containers/pill.dm
> +		M.visible_message("<span class='notice'>[user] swalows the [src] and morphs into a [newgender]!</span>")
swalows

2017-02-10 02:13 UTC, optimumtact commented
This already exists through slime potions and you haven't justified why you think we need another method

2017-02-10 02:15 UTC, Supermichael777 commented
>xenobiology ever doing their job.

This restores it to where it rightfully should be: med-bay

2017-02-10 02:16 UTC, optimumtact commented
But it's not medbay, it's chemistry

2017-02-10 02:21 UTC, Supermichael777 commented
Chemistry is a part of medbay no mater what the chemist says
1. chemistry has a crew facing window and can  whip this shit up quick/provide that one missing ingredient.
2 xenobio is an armored bunker isolated by at least 3 airlocks and a long hallway and it takes 10~ minnutes unless they already had it.

2017-02-10 02:22 UTC, optimumtact commented
So basically you're dumbing the game down by making it easier to do something that was previously requiring a little bit of effort and skill?

2017-02-10 02:30 UTC, Supermichael777 commented
No.

 I'm making an obscure cure for a isolated condition that barley affects game-play but makes people feel uncomfortable easier to access for people who aren't going to grief with it.  This can be safely handed out to any old shitler.  This still requires quite a bit of processing for a single use cosmetic. I wouldn't say its easier or safer, setting off teslium by mistake is fairly deadly.

2017-02-10 02:40 UTC, bgobandit commented
this only exists because of a shitty meme

2017-02-10 02:42 UTC, ShadowDeath6 commented
also is there a reason it's not actually a mutation toxin

2017-02-10 02:43 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/pill.dm
> +		qdel(src)
why does it delete itself if you try to feed it to someone else, just have it not work

2017-02-10 02:51 UTC, ExcessiveUseOfCobblestone commented on code/modules/reagents/reagent_containers/pill.dm
> +		qdel(src)
along with make it blue to fit the alleged lore

2017-02-10 03:01 UTC, Supermichael777 commented on code/modules/reagents/reagent_containers/pill.dm
> +		qdel(src)
its to prevent spamming

2017-02-10 03:05 UTC, ShadowDeath6 commented on code/modules/reagents/reagent_containers/pill.dm
> +		qdel(src)
how would this spam, this is the else to the `M == user` check

2017-02-10 03:12 UTC, optimumtact commented
Okay so to even get this considered to be merged you have to make it an actual reagent pill

this random snowflake item will not pass go and will not receive 200 dollars

2017-02-10 03:14 UTC, Cyberboss requested changes
I have no comment on the feature itself

But, fuuuuuck your implementation! Make it a proper reaction of the horomone reagent

2017-02-10 03:51 UTC, Supermichael777 commented
Well seeing as the whole point of it not being a chemical was to prevent turbonerds from using for griff.

2017-02-10 03:51 UTC, closed without merging

2017-02-10 03:58 UTC, ShadowDeath6 commented
how is making it a chemical going to make it grief usable