Admin tool, the life candle!
tgstation/tgstation pull request #23955
Opened 2017-02-11 01:27 UTC by coiax

:cl: coiax
add: Added an admin only tool, the life candle. Touch the candle, and
when you die, you'll respawn shortly afterwards. Touch it again to stop.
Used for testing, thunderdome brawls and good old fashioned memery.
/:cl:

Requested.

2017-02-11 01:30 UTC, coiax commented
@Aloraydrel

2017-02-11 01:47 UTC, Durkel commented
make it a bonfire for memes

2017-02-11 02:20 UTC, Aloraydrel commented
Finally I can make ss13 pudge wars

2017-02-11 03:48 UTC, coiax commented
@Aloraydrel if you want to suggest some presets, I can make some convenience subtypes.

2017-02-11 12:53 UTC, FantasticFwoosh commented
Something fixed to the floor that can't be destroyed or picked back up again. (to stop people running away from your checkpoint or otherwise destroying it) without admin privileges.

Pulling the sword from the stone so to speak.

2017-02-11 17:04 UTC, coiax commented
@FantasticFwoosh it just looks like a candle, it's an anchored structure.

2017-02-11 19:50 UTC, Cyberboss requested changes

2017-02-11 19:50 UTC, Cyberboss commented on code/modules/admin/life_candle.dm
> +/obj/structure/life_candle
Wrong location. Put it in code/game/objects/structures

2017-02-13 08:12 UTC, optimumtact commented
What could possibly go wrong

2017-02-13 08:12 UTC, merged

2017-02-13 19:18 UTC, coiax commented
If anyone goes wrong, it's the admins fault