His Grace is a better item and less globally-announced
tgstation/tgstation pull request #23951
Opened 2017-02-10 22:41 UTC by ChangelingRain

:cl: Joan
rscdel: His Grace no longer globally announces when He is awakened or falls to sleep.
rscdel: His Grace is not a toolbox, even if He looks like one.
experiment: His Grace no longer requires organs to awaken.
tweak: His Grace how gains 5 force for each victim consumed, always provides stun immunity, and will, generally, take longer to consume His owner.
experiment: His Grace must be destroyed to free the bodies within Him.
rscadd: His Grace becomes highly aggressive after consuming His owner, and will hunt His own prey.
/:cl:

Notably, even if you allow His Grace to sleep, He will still gain bloodlust and have force for each person consumed. Dropping Him or throwing Him into a group of people may sometimes be a wise decision.

2017-02-10 22:42 UTC, coiax commented on code/datums/status_effects/buffs.dm
> +	owner.adjustToxLoss(-grace_heal)
Owner could be TOXINLOVING. We really need some sort of standard proc or flag for ignoring this sort of stuff. Tbh, I've never been a fan of TOXINLOVING, it makes no sense.

2017-02-10 22:43 UTC, coiax commented on code/game/objects/items/weapons/his_grace.dm
> +/obj/item/weapon/his_grace
/weapon/ is an empty datum class, plz remove

2017-02-10 22:43 UTC, coiax commented
Another @Xhuis feature eaten by @ChangelingRain.

2017-02-10 22:44 UTC, Xhuis commented
NO. YOU AREN'T TAKING THIS FROM ME. I ALREADY HAVE A PR HALFWAY THROUGH. I WILL MAKE IT.

2017-02-10 23:18 UTC, Fox-McCloud commented on code/datums/status_effects/buffs.dm
> +	id = "his_grace"
Side note, what's up with the awfully displayed tabbing on TG these days?

2017-02-10 23:39 UTC, lzimann commented on code/datums/status_effects/buffs.dm
> +	id = "his_grace"
uh what?

2017-02-11 01:13 UTC, Robustin commented
This could make it insanely OP but id rather see it be usable and then nerfed down than basically an elaborate suicide item.

2017-02-11 01:21 UTC, Armhulen commented
to be fair it is a fun suicide item

2017-02-11 06:27 UTC, Xhuis commented
The original premise of His Grace was kind of to be insanely OP, honestly (on Goon, that is). That's the best part.

2017-02-11 10:29 UTC, Steelpoint commented
I'm pretty sure Goonstation removed 'His Grace' because it become way too powerful, even by Goon standards.

I don't personally mind if His Grace is a powerful item, considering its a 20 TC item, but it should not be powerful enough to wipe out the station.

2017-02-11 14:10 UTC, ChangelingRain commented
Well, yes, His Grace should be extremely powerful. All you need to do to kill His owner is run away and wait a bit.

2017-02-11 16:30 UTC, Xhuis commented
@Steelpoint Goon removed His Grace because it was even sillier than what we have now. Whenever someone examined it, they became a _slave_ to it and got an objective to feed it, so people would kill its owner, examine it, and go on a rampage; thus the cycle continued.

2017-02-11 16:37 UTC, Steelpoint commented
That was also a contributing factor to its removal. 

Overall I'm fine with this item buff, even though its really more you choosing a long, drawn out, suicide.

2017-02-11 16:38 UTC, Xhuis commented
Long, drawn out, _hilarious_ suicide.

2017-02-11 17:10 UTC, Armhulen commented
it's an abstract kind of suicide

2017-02-11 17:52 UTC, Supermichael777 commented on code/datums/status_effects/buffs.dm
> +	id = "his_grace"
por que?

2017-02-13 13:00 UTC, Alek2ander commented
This looks like something that could do with logs and extended fingerprinting.

2017-02-14 12:06 UTC, optimumtact commented
I don't know about the stun immunity

2017-02-14 12:21 UTC, AnturK requested changes
CSS mutilation needs to stop at some point.

2017-02-14 12:21 UTC, AnturK commented on interface/stylesheet.dm
> +.his_grace				{color: #15D512;	font-size: 3; font-family: "Courier New", cursive, sans-serif; font-style: italic;}
Please use just use multiple classes instead of this copypaste

2017-02-15 19:23 UTC, Militaires commented
:-1: to making his grace a not-toolbox :(

2017-02-16 14:18 UTC, AnturK approved these changes

2017-02-16 14:18 UTC, merged

2017-02-16 15:26 UTC, Xhuis commented
Joan steals my code and makes it better again. Oh, well. I'm excited to see this on the server. An AI still completely shuts it down, though, but if it proves a problem even with resisting it's influence we can look into it. Thanks, Joan, but I still hate you. >:C