Fixes mmis not working properly with mechas
tgstation/tgstation pull request #23972
Opened 2017-02-11 16:26 UTC by lzimann

:cl: Lzimann
fix: MMIs/posibrains works with mechas again
/:cl:

This part of the code mentally exhausted me.

2017-02-11 16:26 UTC, lzimann commented on code/game/mecha/mecha.dm
> +	var/mob/living/carbon/human/occupant = null
This was accidental(althought the type here really doesn't matter except when trying to grab the DNA).

2017-02-11 18:29 UTC, Cyberboss requested changes

2017-02-11 18:29 UTC, Cyberboss commented on code/game/mecha/mecha.dm
> +			world << "occupant.loc"
.

2017-02-11 18:30 UTC, Cyberboss commented
Maybe I didn't cause this bug... This is way more complicated than what I touched

2017-02-11 18:48 UTC, PKPenguin321 commented
Fixes https://github.com/tgstation/tgstation/issues/23718

2017-02-12 02:44 UTC, lzimann commented on code/game/mecha/mecha.dm
> +			world << "occupant.loc"
i just added to see if it was this check that was triggering

2017-02-12 16:58 UTC, merged