Forces hardware rendering for all connecting clients.
tgstation/tgstation pull request #24052
Opened 2017-02-13 08:00 UTC by MrStonedOne

:cl:
experiment: the game will now force hardware rendering on for all clients.
/:cl:

2017-02-13 08:53 UTC, SgtxRootbeer commented
No, one time, I had an issue with the latest gfx drivers not liking /tg/ code. My only solution was to disable hardware rendering temporarily.

2017-02-13 09:50 UTC, optimumtact commented
if you disable hardware rendering the game will literally fail to render Rootbeer

2017-02-13 10:07 UTC, MrStonedOne commented
and it can be abused to disable some parts of darkness

2017-02-13 14:28 UTC, Cyberboss approved these changes

2017-02-14 00:01 UTC, JJRcop commented on code/modules/client/client_procs.dm
> +
yuck

2017-02-14 00:01 UTC, JJRcop requested changes

2017-02-14 00:01 UTC, JJRcop commented on code/modules/client/client_procs.dm
> +
Pointless whitespace

2017-02-14 03:26 UTC, MrStonedOne commented on code/modules/client/client_procs.dm
> +
no where near as pointless as the commit to remove it would be.

2017-02-14 12:33 UTC, optimumtact commented on code/modules/client/client_procs.dm
> +
bitch you added it in the first place

2017-02-14 18:04 UTC, MrStonedOne commented on code/modules/client/client_procs.dm
> +
Ya, i meant to copy paste the line to here, but when i tabbed back i put it elsewhere.

It happens,

2017-02-16 20:52 UTC, optimumtact commented
maybe a test merge?

2017-02-17 08:20 UTC, merged