Minor implants refactor
tgstation/tgstation pull request #24378
Opened 2017-02-23 16:16 UTC by coiax

Fixes #24375.

Implant cases and implanters now have an `imp_type` var for making the
implant in New(), rather than individually creating the implant in
New(), which would have worked fine except when you try to create
subclasses of implanters.

Gang implants are special, and thus untouched.

2017-02-23 16:39 UTC, Cyberboss requested changes

2017-02-23 16:39 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implantcase.dm
> +		imp = new imp_type(src)
`Initialize`

2017-02-23 16:39 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implanter.dm
> +		imp = new imp_type(src)
Again

2017-02-23 16:40 UTC, coiax commented on code/game/objects/items/weapons/implants/implanter.dm
> +		imp = new imp_type(src)
explain to me the difference please? <3

2017-02-23 17:02 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implanter.dm
> +		imp = new imp_type(src)
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#prefer-initialize-over-new-for-atoms

2017-02-25 01:38 UTC, optimumtact commented on code/game/objects/items/weapons/implants/implantcase.dm
> +		imp = new imp_type(src)
^

2017-02-25 01:38 UTC, optimumtact commented on code/game/objects/items/weapons/implants/implanter.dm
> +		imp = new imp_type(src)
^

2017-02-28 20:40 UTC, coiax commented
@optimumtact done.

2017-03-01 00:51 UTC, merged