Adds a new arcade prize
tgstation/tgstation pull request #24399
Opened 2017-02-24 02:08 UTC by Supermichael777

:cl:
add: Added fake pits. Get them from the arcade machine.
/:cl:

Honk.

2017-02-24 02:54 UTC, ChangelingRain commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	name = "chasm"
remove this so you can tell it's fake by the name, same as the space tile

2017-02-24 04:52 UTC, GunHog commented
I want to put these **ALL OVER THE MINING BASE.**

2017-02-24 05:10 UTC, Supermichael777 commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	name = "chasm"
there is already a tell. plus you can just toss a pen or something on it to check.

2017-02-24 05:11 UTC, Supermichael777 commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	name = "chasm"
but FIIIIIINNEEEEE

2017-02-24 07:40 UTC, Iamgoofball commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	name = "chasm"
yeah the description rats it out, it's fine as-is

2017-02-24 13:43 UTC, XDTM commented on code/game/turfs/simulated/floor/fancy_floor.dm
> +	name = "chasm"
Yeah the toy singulo only reveals itself with the description

2017-02-24 16:03 UTC, RandomMarine commented
If you place these around a real chasm will they smooth with each other?

2017-02-24 18:49 UTC, Kromgar commented
You sick fuck

2017-02-24 21:44 UTC, Supermichael777 commented
@RandomMarine probably not. But I could make it

2017-02-24 22:40 UTC, RandomMarine commented
DEVILISH

2017-02-25 18:52 UTC, imtakingabreakdontatme requested changes

2017-02-25 18:52 UTC, KorPhaeron commented on code/game/machinery/computer/arcade.dm
> +		/obj/item/stack/tile/fakepit/loaded					= 2,
fix your spacing its triggering me

2017-02-27 02:13 UTC, kilkun commented
emagging it should turn it into a real chasm

2017-03-02 06:34 UTC, optimumtact commented
Taking too long to respond to maintainers

2017-03-02 06:34 UTC, closed without merging

2017-03-02 06:57 UTC, PKPenguin321 commented
Noooo

2017-03-02 06:59 UTC, optimumtact commented
You can pick up this pr yourself by cloning his repo and the branch and then pushing to your own repo and making the required changes.

2017-03-02 06:59 UTC, PKPenguin321 commented
How to clone repo

2017-03-02 07:01 UTC, optimumtact commented
git add remote supermichael https://github.com/Supermichael777/tgstation

git fetch supermichael

now you can work with it like the origin or upstream repos for tg

2017-03-02 07:04 UTC, PKPenguin321 commented
Neat, I'll have a look later