Syndiebeacon now tracks engine, no more sanic tesla
tgstation/tgstation pull request #24419
Opened 2017-02-24 22:22 UTC by Robustin

1) Syndiebeacon calling out distance and direction of the engine is just a QOL feature for an underused item. After messing around with it I just found it too frustrating when the tesla/sing can destroy it or pull it from the edge of your screen, you simply don't get enough time to move this device and use it to its full potential.

2)

>Hear tesla noise
>Well at least ive got this hardsuit and insulated gloves, as long as I move out of the...
>Tesla teleports behind you
>Nothing personnel kid
>Become ash

So apparently nobody reads the code because I'm convinced no sane individual would sign off on an engine that can move 2+ screens at a time while instakilling anyone it chains to. The effect of extra energy balls should be increase destruction (that remains unchanged) but currently 2 energy balls = 3 extra move chances, that has been scaled down significantly. 

:cl: Robustin
add: The syndicate power beacon will now announce the distance and direction of any engines every 10 seconds.
tweak: Tesla now moves more slowly and movement scales significantly lower with the number of energy balls.
/:cl:

2017-02-24 22:22 UTC, Armhulen commented
yay

2017-02-24 22:40 UTC, Iamgoofball commented
>>>tweak: Tesla no longer scales up movement with number of energy balls.

stop

2017-02-24 22:40 UTC, Iamgoofball commented on code/game/machinery/syndicatebeacon.dm
> +				for(var/obj/singularity/singulo in world)
this will call out each individual energy ball btw

2017-02-24 22:41 UTC, Robustin commented on code/game/machinery/syndicatebeacon.dm
> +				for(var/obj/singularity/singulo in world)
why are energy balls classified as singulos reeeee

2017-02-24 22:44 UTC, Robustin commented
Goof you're delusional if you don't think Tesla movement isn't cancer at high energy, it takes very little effort to stack up 20+ balls and get the singularity taking 35+ moves at a time. In no way shape or form does that resemble healthy gameplay when the tesla also kills everything on screen instantly along with a mid-sized explosion and ashing anything on the 35 tiles it just moved across.

2017-02-24 22:48 UTC, KorPhaeron commented
Atomize your PRs please

2017-02-24 22:54 UTC, Robustin commented
This is my "Makes Beacons usable again" PR, teslas moving across the station in 10 seconds makes the beacon unusable.

2017-02-25 02:56 UTC, Iamgoofball commented on code/game/machinery/syndicatebeacon.dm
> +				for(var/obj/singularity/singulo in world)
so they dont copypaste you fuk

2017-02-25 02:56 UTC, Iamgoofball commented
@Robustin 
have you considered only slowing down their movement speed if there is a beacon

2017-02-25 03:46 UTC, Robustin commented
No, because when I did my local tests for this and watched a big-ball tesla warping around so fast it was making me dizzy I realized one of the reasons I hate the Tesla so much. Absolutely no reason Tesla to be anywhere near as fast as it is.

2017-02-26 11:09 UTC, Iamgoofball commented
Then it's not about the beacon.

2017-02-26 18:53 UTC, Robustin commented
I'll cut you a deal, you give me the code for it and ill do it.

2017-02-26 22:04 UTC, Jordie0608 commented
You're more likely to get either of these changes merged if they're atomized in different PR like Kor asked.

2017-02-27 15:58 UTC, Robustin commented
Fine, both changes just seem completely intuitive as a pair though.

2017-02-28 09:17 UTC, AnturK requested changes

2017-02-28 09:17 UTC, AnturK commented on code/game/machinery/syndicatebeacon.dm
> +	say("Process")
Debug remnant i suppose.

2017-02-28 09:17 UTC, AnturK commented on code/game/machinery/syndicatebeacon.dm
> +				for(var/obj/singularity/singulo in world)
Use poi_list instead of world, solves the problem and makes this faster. Singularities could probably use their own list.

2017-03-01 03:19 UTC, Robustin commented
What exactly is poi_list and how would it be used?

if(cooldown <= poi_list.time)?

for(var/obj/singularity/singulo in poi_list?)

2017-03-01 07:35 UTC, AnturK commented
The latter, poi_list is a list of points of interest (non-mob things on the observe list) it includes singularities.

2017-03-02 06:58 UTC, merged