gives weapons a chance to knock away other weapons when targeting the arms
tgstation/tgstation pull request #24438
Opened 2017-02-25 08:29 UTC by PKPenguin321

So if you target the left arm and they're holding a thing in their left hand, you have a %chance (equal to the force of the weapon you are using) to knock away their weapon 3 to 5 tiles away.

Inspired by https://github.com/tgstation/tgstation/pull/24293

DNM for now since it doesn't appear to actually work upon testing, no runtimes but the checks never pass(?) and the items are never thrown away.

🆑
add: Targeting the arms when attacking with a melee weapon now has a chance to knock whatever your opponent may be holding in that arm out of their hand.
/:cl:

2017-02-25 08:54 UTC, davidchan13 commented
Doesn't this just make (dual)e-swords even stronger?

2017-02-25 09:02 UTC, PKPenguin321 commented
They can already just cut off your arm in one hit which does the same thing already

2017-02-25 09:11 UTC, XDTM commented
I like it, since it gives an alternative to targeting the head/chest for knockdowns. I think it should work regardless of the targeted arm, though, in a fast combat situation it's usually hard to check which hand your target is using, and you pretty much always want to disarm their active hand.

2017-02-25 09:14 UTC, XDTM commented
If you want to go with the arm targeting anyway, though, you should probably use 
`/mob/proc/get_held_items_for_side(side = "left", all = FALSE)`
since it accounts for multihands.

2017-02-25 13:20 UTC, AnturK commented
It's "secondary effects scaling by force" meme again. Can we not.

2017-02-25 15:59 UTC, KorPhaeron commented
>It's "secondary effects scaling by force" meme again. Can we not.

This also completely misses the point of the original PR which was to nerf guns

2017-02-25 16:01 UTC, ChangelingRain commented
Maybe a chance to delay the enemy's attack if you hit the arm they're holding their weapon in while they're able to attack?
With the chance being higher for lower-force items, so it's kind of a parry thing.

2017-02-25 16:27 UTC, Anonmare commented
Does this knockout things that are no-drop?

2017-02-25 18:46 UTC, ShadowDeath6 commented
this applies to all items in your hands though, not just weapons

2017-02-25 19:33 UTC, davidchan13 commented
"Hurr durr, toolboxed disarmed a dsword out of a nukies hands"

2017-02-25 20:50 UTC, PKPenguin321 commented
@ChangelingRain so effectively like a stun but it doesn't cause them to drop anything?

interesting idea

2017-02-25 20:52 UTC, PKPenguin321 commented
@davidchan13 you can already do that if you aim for the chest but it stuns them as well

@Anonmare no

@KorPhaeron it was inspired by your PR but doesnt necessarily share the same goal

@AnturK what would be a better value to scale this by?

@XDTM you'll have to elaborate i really have no idea how i would use that. also i want it to be specific to each arm. playing with weapons that can delimb easily has shown me that this kind of thing can work, even with having to target specific arms.

2017-02-26 06:06 UTC, Cyberboss requested changes

2017-02-26 06:06 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species.dm
> +				if(H.stat == CONSCIOUS && armor_block < 50)
check `!H.incapacitated` instead

2017-02-26 06:06 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species.dm
> +				if(H.stat == CONSCIOUS && armor_block < 50)
See below

2017-02-26 15:45 UTC, KorPhaeron commented
All this will really do is buff melee weapons that are already strong, and make melee more frustrating, I don't think the change is really needed right now

2017-02-26 15:45 UTC, closed without merging