Continues to add default sql indexes and table optimisations
tgstation/tgstation pull request #24456
Opened 2017-02-26 07:37 UTC by Jordie0608

See #24345 and #24277 since I really shouldn't be messing up upstream branches in the first place.
@MrStonedOne

2017-02-26 23:32 UTC, MrsTonedOne requested changes

2017-02-26 23:32 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +UPDATE `feedback`.`ban`
?

2017-02-26 23:32 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +UPDATE `feedback`.`ban`
?

2017-02-26 23:32 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +UPDATE `feedback`.`ban`
?

2017-02-26 23:32 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +UPDATE `feedback`.`ban`
?

2017-02-26 23:35 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> + SET `ipTEMP` = INET_ATON(`ip`);
Should maybe use the single query method you figured out for the ips in other tables on this one too.

2017-02-26 23:57 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +, CHANGE COLUMN `name` `name` VARCHAR(32) NOT NULL
`#1406 - Data too long for column 'name' at row 3570`

2017-02-26 23:58 UTC, MrStonedOne commented on SQL/optimisations_2017-02-19.sql
> +, CHANGE COLUMN `name` `name` VARCHAR(32) NOT NULL
longest name is 67 characters.

2017-02-27 00:04 UTC, Jordie0608 commented on SQL/optimisations_2017-02-19.sql
> +, CHANGE COLUMN `name` `name` VARCHAR(32) NOT NULL
i blame badmins

2017-02-27 11:44 UTC, merged