Readds secborgs (as a traitor item)
tgstation/tgstation pull request #24628
Opened 2017-03-02 20:01 UTC by InsaneHyena

:cl: 
add: Added a roboticist-specific traitor item - O.V.E.R.S.E.E.R. upgrade board
/:cl:

[]: # (Adds a board that can hack cyborgs and turn them into secborgs. Babby's first code that likely doesn't even work. :)

2017-03-02 20:06 UTC, coiax commented
FEAR THE BLOODHOUND

2017-03-02 20:07 UTC, InsaneHyena commented
That's a good point, maybe it should be called Bloodhound upgrade module instead.

2017-03-02 20:18 UTC, PKPenguin321 commented
Hmm. I was skeptical of this on the forums because I assumed it would be infinite use, but one secborg might not be as bad. 

Either way, I'm extremely cautious of this, secborgs are really really strong and since they're a hard traitor tell now they'll be used exclusively to murderbone, and if they can take out the ion rifle/robotics console(s) and have a human to stick with them they're basically unstoppable. Overall a :-1: from me, but not as strong as I was initially going to give it.

2017-03-02 20:20 UTC, RemieRichards commented on code/game/objects/items/robot/robot_upgrades.dm
> +	A.transform to(/obj/item/weapon/robot_module/security)
_

2017-03-02 20:20 UTC, RemieRichards commented on code/modules/uplink/uplink_item.dm
> +	desc = "An illegal cyborg upgrade module that both hacks the cyborg and activates it's hidden security module."
its

2017-03-02 20:24 UTC, InsaneHyena commented on code/game/objects/items/robot/robot_upgrades.dm
> +	A.transform to(/obj/item/weapon/robot_module/security)
What?

2017-03-02 20:25 UTC, RemieRichards commented on code/game/objects/items/robot/robot_upgrades.dm
> +	A.transform to(/obj/item/weapon/robot_module/security)
notice your code doesn't work, then notice what I posted.

2017-03-02 20:47 UTC, InsaneHyena commented
It being one use wasn't actually my intention. I think it should be two or three uses, so I'll work on that.

2017-03-02 20:52 UTC, Supermichael777 commented
obviously the order is hack > console and spare > ion > wipe rd > upgrade

2017-03-02 20:55 UTC, anconfuzedrock commented
I'm gonna be honest, the main reason i didnt do this myself is because I thought people would hate it and it was too complicated and I am too stupid to do this, good on ya cuz I didnt know how to do this myself.

2017-03-02 21:36 UTC, Cyberboss commented on code/game/objects/items/robot/robot_upgrades.dm
> +/obj/item/borg/upgrade/afterattack(atom/target, mob/user, proximity)
Is no one going to comment on the fact that this is a one click transform??

2017-03-02 22:01 UTC, InsaneHyena commented
I have no idea what I'm doing.

2017-03-02 22:09 UTC, Kraseo commented
try merging with upstream

2017-03-02 22:12 UTC, Quardbreak commented
From master branch, aaaaaaaaaaaaaaaaa

2017-03-02 22:13 UTC, InsaneHyena commented
I actually intended to include all of those commits. I'm referring to the code itself.

2017-03-02 22:41 UTC, ShadowDeath6 commented
for future reference, don't directly do stuff from your master branch, it gets irritating to clean up when you want to make different prs

2017-03-02 22:51 UTC, JJRcop requested changes
Please fix the indentation issues, and not properly using proc arguments.

2017-03-02 22:51 UTC, JJRcop commented on code/game/objects/items/robot/robot_upgrades.dm
> +        name = "Bloodhound upgrade module"
All of these spaces should be tabs, this tab should only have one indentation.

2017-03-02 22:51 UTC, JJRcop commented on code/game/objects/items/robot/robot_upgrades.dm
> +       wiresexposed = TRUE
All of these lines should have only one level of indentation, and these wiresexposed lines should be R.wiresexposed

2017-03-02 22:51 UTC, JJRcop commented on code/game/objects/items/robot/robot_upgrades.dm
> +        A.emag_act(user)
`A` should be `R`

2017-03-02 22:51 UTC, JJRcop commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	/obj/item/weapon/storage/box/syndie_kit/traitorsec_boards/New()
This should have no identation, remove this tab.

2017-03-02 22:53 UTC, JJRcop commented on code/game/objects/items/robot/robot_upgrades.dm
> +       wiresexposed = TRUE
There is an exception in the `return 0` line, it should have two levels of indentation.

2017-03-02 23:55 UTC, InsaneHyena commented
I thank all of those brave souls (Antur, Haev, JJRCop) who helped me with this trash code.

2017-03-03 00:10 UTC, ExcessiveUseOfCobblestone commented
If you make them one use, you can make them 7 a piece, meaning 1) you'll only get 2 unless you can befriend a traitor bro [see: kill them with PDA/Radio/Pen unlocked] and 2) you'll have /just enough/ [intentional] to get an emag but nothing else because you have 2 killing machines.

Tada, B A L A N C E

2017-03-03 00:13 UTC, PKPenguin321 commented
>now it has three

Even two is enough to hijack, I know this by experience. One was already too much if you ask me because you have to remember that not only is the secborg already ridiculous, it also has a guaranteed teammate (the guy that hacked it) to repair it, drag it from stuns, change its battery, etc. and vice versa

I'm serious when I say this isn't a good idea, if you thought dual eswords were too good for murderbone you'll hate secborgs

2017-03-03 00:17 UTC, InsaneHyena commented
I disagree, since we're talking about borgs who are essentially giant VALID signs. But I'm open to idea of 7tc for one board.

2017-03-03 00:20 UTC, Incomptinence commented
PKP i find it making hijack super easy unlikely. As soon as the bloodhounds are out the traitor is super loud. If they get spotted it is going to be malf level panic mode without a ton of set up using regular borgs to nab ai dissable coms etc. Slightly better finisher perhaps.

Now onto how much of a facetious pile of excrement you are my dear penguin. Double eswords provide exceptional protection against all manner of damaging projectiles. Sec borg has defense against no damaging projectiles.

2017-03-03 00:28 UTC, PKPenguin321 commented
I'm sure I've told this story a thousand times before of the time I hijacked as traitor robo two rounds in a row on high pop as traitor robo with actually 0 subtlety involved. It doesn't matter if you know the secborg is a traitor, it's too strong for you to do anything about it. When I hijacked twice, I didn't even have to close thr robotics shutters, and everybody on the radio kept saying I was killing everybody and to just avoid robotics. One secborg and I were able to take out two sec officers plus the captain with his laser gun plus the HoS with the ion rifle all at the same time.

As for your stupid comment at the end there, secborgs actually do have a defense against that. It's called moving away and shooting, or just closing and bolting doors behind them. They have just as much range as anybody else with a gun, and don't take slowdown from damage, so even if you somehow shoot them to 1 health before they just tase you or whatever they can just go through a door that you can't and go back to their roboticist to get healed (this is all assuming that there isn't already a roboticist nearby to fight you while you're shooting the borg). Again, I am talking from experience. I don't know why you're in such denial.

2017-03-03 00:56 UTC, InsaneHyena commented
If bloodhounds prove to be too strong/too weak, we can always adjust the price later. Are you fine with 7tc for one board as a compromise for now?

2017-03-03 00:57 UTC, PKPenguin321 commented
That is probably worse since you could stack it with an ebow

2017-03-03 15:57 UTC, ExcessiveUseOfCobblestone commented
To cull the fears, it will probably be best to make it 14. I rather it be garbo first, buffed later than OH GOD SAVE ME first, nerfed to uselessness right after implementation.

2017-03-03 17:27 UTC, InsaneHyena commented
Perfectly valid point.

2017-03-03 18:23 UTC, GunHog requested changes
See my line comments. Remove the changes to the wires var, and swap the order of the module change and emagging.

2017-03-03 18:23 UTC, GunHog commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.wiresexposed = TRUE
Remove this. The borg's panel must be open in order for you to insert the upgrade in the first place, and `wiresexposed` is incorrect anyway.

2017-03-03 18:23 UTC, GunHog commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.wiresexposed = FALSE
Remove this one as well. Not needed.

2017-03-03 18:23 UTC, GunHog commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.module.transform_to(/obj/item/weapon/robot_module/security)
Put this **BEFORE** the `emag_act()`.

2017-03-03 18:24 UTC, GunHog commented
I have taken the liberty of testing this for you (Because I like the feature and want to see it added). Please make the attempt to test your code before you upload it. Never touch the github web editor, you should have Git set up on your computer so you can compile and run your own code yourself.

2017-03-03 18:25 UTC, PKPenguin321 commented
To people who want this: Why?

2017-03-03 18:42 UTC, ChangelingRain commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.emag_act(user)
you need to also return 1 after this

2017-03-03 18:43 UTC, GunHog approved these changes

2017-03-03 18:44 UTC, GunHog commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.emag_act(user)
Oh well, I cannot catch *everything*!

2017-03-03 18:53 UTC, Iamgoofball commented
1. Lock it to 1, please.
2. Make sure it's a proper syndieborg and not a normal secborg. If it's a normal secborg this will just become the new "friendly traitor lol" meme or the new "HoS-but-with-traitor-gear" setup ala holoparas

2017-03-04 02:16 UTC, Anonmare commented
Give it the Syndie black paintjob so it's an immediately obvious "Valid me" sign, even to players off the server.

2017-03-04 02:19 UTC, InsaneHyena commented
I think it can be done, but I'm not a spriter. Should I just use the syndieborg sprites? In that case, wouldn't a whole new cyborg module almost identical to security be created? I'll try to figure it out.

2017-03-05 09:02 UTC, AdamElTablawy commented
Meanwhile on PKP circlejerks about how overpowered a cyborg any other server can deal with is :^)

2017-03-05 09:24 UTC, PKPenguin321 commented
Meanwhile on "not one person has given a good reason for adding this," not one person has given a good reason for adding this

2017-03-05 22:21 UTC, InsaneHyena commented
Okay, I'm done. I've tested it, and it works perfectly. Had to make bloodhounds a daughter module to secborgs in order to make animations look and work nice.

2017-03-05 23:44 UTC, Iamgoofball commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Ilegal upgrade board that unlocks banned security module"
:+1:

2017-03-06 01:07 UTC, PKPenguin321 commented on code/game/objects/items/robot/robot_upgrades.dm
> +	desc = "Ilegal upgrade board that unlocks banned security module"
fix this and also put punctuation

2017-03-06 02:06 UTC, JJRcop reviewed
The code is fine now but I don't approve or disapprove of the concept.

2017-03-07 22:55 UTC, optimumtact commented
This is on hold until I can ask the headmins for their opinion because this sidesteps the config that disables secborgs.

2017-03-08 01:05 UTC, PKPenguin321 commented
Not one person has said why they want this aside from one guy memeing about spiting me

2017-03-08 03:36 UTC, Ausops commented
I'd be willing to testmerge this if the price were increased. Also try re-skinning it into syndiborg-lite or the '''''wargiver''''''' borg and I bet no one will ever screech about secborgs.

2017-03-08 04:38 UTC, InsaneHyena commented
> If the price was increased
Fine, I guess.
> Reskin it into syndiborg-lite
I already did.

2017-03-08 16:52 UTC, Anonmare commented
@PKPenguin321 Because it might be fun

2017-03-11 03:54 UTC, optimumtact commented
This is better left for a full seccborg verhaul if such a thing can even work

2017-03-11 03:54 UTC, closed without merging