Glowshrooms now have colored light
tgstation/tgstation pull request #24743
Opened 2017-03-06 18:22 UTC by ChangelingRain

:cl: Joan
rscadd: Glowshrooms now have colored light.
tweak: Tweaked the potency scaling for glowshroom light; high-potency shrooms no longer light up a huge area, but are slightly brighter.
/:cl:

Fixed a bug where the first glowshroom planted wouldn't have light properly based on potency.

Max potency shrooms
![](http://puu.sh/uwR0m/b13102b45b.png)
This is actually less wide-ranging than it used to be; light_range at 100 potency from 10 to 2, light_power from 1 to 5

2017-03-06 18:41 UTC, GunHog commented
You should include the part where you are nerfing them in your title.

2017-03-06 18:42 UTC, PKPenguin321 commented
Looks super fucking cool, I'm down for nerfing them for this aesthetic

2017-03-06 18:43 UTC, GunHog commented
Eh, I guess. I admit that they do look RAD. (As in radioactive)

2017-03-06 20:41 UTC, Dorsisdwarf commented
there. 


👍

2017-03-06 23:07 UTC, Supermichael777 commented
are the red ones RED?

2017-03-06 23:50 UTC, bobdobbington commented
Can you please split this PR into one for the nerf and one for the new lighting? The new lighting is very good and the 80% range nerf is way too much. I understand that now that the light is colored it'll be more jarring to have wide ranges but there's gotta be a better option than 2 at max potency. I'd just make glowberries instead.

2017-03-07 00:47 UTC, ChangelingRain commented
It's actually 2.5 whoops
But uh, 10 is super hilarious because one shroom lights up the entire screen and then some, like, I can get you a picture of that

2017-03-07 00:52 UTC, ChangelingRain commented
Also do account for the fact that I made the actual glowshroom item glow as well, so it works as basically a flashlight in addition to lighting.

2017-03-07 01:04 UTC, bobdobbington commented
Glowshrooms already glowed as a result of their having the Bioluminescent trait, so that's not a buff. I agree that 10 doesn't make sense with colored lights but even going from a radius 10 down to a radius 5 range would mean going from ~300 potentially covered tiles down to more like ~80. Dropping it to 2.5 drops the covered area down to ~20 tiles, giving these less than a tenth the effective range of pre-nerf levels.

2017-03-07 01:19 UTC, Cyberboss requested changes

2017-03-07 01:19 UTC, Cyberboss commented on code/game/objects/effects/glowshroom.dm
> +/obj/structure/glowshroom/proc/setup()
Remove the timer and use Initialize

2017-03-07 01:34 UTC, ChangelingRain commented on code/game/objects/effects/glowshroom.dm
> +/obj/structure/glowshroom/proc/setup()
Doesn't work, smart guy; it can't set the vars before set_light and the addtimer is called.

2017-03-07 01:36 UTC, ChangelingRain commented
Tweaked it to be a maximum of 4 range, 4 brightness, which should be more than enough given how many of these you can produce and that they spread somewhat if planted.

![](http://puu.sh/uxnY4/7da538d65c.png)

2017-03-07 01:44 UTC, bobdobbington commented
Alright, I can live with that compromise. Can we bump Strong to 0.06 so it's an exact double of regular again? That's enough for me to be happy with this PR.

2017-03-07 02:24 UTC, ChangelingRain commented
Due to how lights scale, increasing the light range by 2 has a major effect on the brightness and increasing it to that would mean it'd be full screen light at max potency. I think that's kind of a bit much.

2017-03-07 02:29 UTC, bobdobbington commented
Yeah, the idea is that at max potency, a glowberry should light up the whole screen. That's what they do now. This glowshroom change shouldn't impact the usefulness of pocket glowberries as maint/mining lights.

2017-03-07 04:44 UTC, ExcessiveUseOfCobblestone commented
A T O M I Z E 

Also you shouldn't be using a plant as a replacement for the light, you should be using it's ability to spread + light, so I think the balance change not being a full screen is ok.

2017-03-07 04:49 UTC, ChangelingRain commented
You can't spread glowberries but they've got huge fucking range compared to basically every other item light in the game even with this one-tile nerf

2017-03-07 05:00 UTC, bobdobbington commented
Glowberries aren't glowshrooms. I can see the relevance between changing the color of glowshroom lights and nerfing the range but this glowberry nerf seems just tacked on because you feel that botany should have less powerful lights? It has no relevance whatsoever to the change that is the reason for this PR.

2017-03-07 22:23 UTC, bobdobbington commented
Changing the title doesn't make it any more related. The impetus for all this was that you changed the color of glowshrooms, which resulted in them needing to be tweaked. Why are you so insistent on nerfing this? You haven't given a reason beyond "huge fucking range" and "that's kind of a bit much". I want to be able to see the entire screen as plantpod on lavaland with a max potency glowberry. That's not unreasonable at all. Why do you think glowberries are a balance issue, and why are you lumping a glowberry nerf into an unrelated glowshroom PR?

2017-03-07 22:58 UTC, XDTM commented
Glowberry genes can be transferred to glowshrooms, i'm pretty sure.

2017-03-08 00:41 UTC, bobdobbington commented
Shouldn't impact the spreading glowshrooms on the ground, I believe. At most by genemodding you'd be able to get a glowshroom with equivalent pocket brightness, not spreading glowberries.

2017-03-08 08:30 UTC, Cheridan commented
jesus bob lay off

2017-03-08 08:30 UTC, merged