the LORE was WRONG
tgstation/tgstation pull request #24753
Opened 2017-03-06 20:48 UTC by Iamgoofball

Fixes the lore on the Russian Glowcaps.

2017-03-06 20:49 UTC, coiax commented on code/modules/hydroponics/grown/mushrooms.dm
> +	reagents_add = list("teslium" = 0.1, "nutriment" = 0.04, "mindbreaker" = 0.01)
doo dee doo undeclared change

2017-03-06 20:49 UTC, Cheridan commented
since when are they russian

2017-03-06 20:52 UTC, Incoming5643 commented
The meme lore isn't wrong. Paramedic says they're bioluminescent but whatever the hell snake ate were generating electricity, that's not bioluminescences.

That's part of the joke.

2017-03-06 20:53 UTC, Incoming5643 commented
@Cheridan Gloomshrooms aren't Russian, Glowcaps are.

Again refer to the reference. https://www.youtube.com/watch?v=VFfHmxJbEJc

2017-03-06 20:56 UTC, Cheridan commented
oh

closed for violating reference policy

2017-03-06 22:19 UTC, Supermichael777 requested changes

2017-03-06 22:19 UTC, Supermichael777 commented on code/modules/hydroponics/grown/mushrooms.dm
> -	desc = "<I>Mycena Ruthenia</I>: This species of mushroom glows in the dark, but aren't bioluminescent. They're warm to the touch..."
its not bioluminescent.  its radioluminescent.

2017-03-06 22:20 UTC, Iamgoofball commented
@Incoming5643 He was hallucinating the battery recharge, they go over this with Signit and Paramedic chatting. She confirms they're bioluminesent in the same codec call.

2017-03-06 22:21 UTC, Iamgoofball commented on code/modules/hydroponics/grown/mushrooms.dm
> +	reagents_add = list("teslium" = 0.1, "nutriment" = 0.04, "mindbreaker" = 0.01)
part of the LORE

2017-03-07 01:39 UTC, Haevacht commented
What is it with you and abhorrent PR titles.

2017-03-07 02:38 UTC, Incoming5643 commented
It's not a hallucination though, it actually recharges his batteries. Snake's faith in the mushrooms defied reality.

2017-03-07 02:42 UTC, Iamgoofball commented
let's just break even and add both

2017-03-07 08:04 UTC, MrPerson commented
Always going to downvote misleading PR titles until you get your shit together

2017-03-07 08:05 UTC, AnturK commented
Please give this PR title that indicates the content or it will have to be closed.

2017-03-07 13:39 UTC, Militaires commented
do they recharge your batteries

2017-03-07 20:44 UTC, optimumtact commented
Your PR has been closed due to having a misleading or incorrect title, adjust the title and ping me to reopen it or make a new PR with a properly descriptive title and body content.

2017-03-07 20:44 UTC, closed without merging

2017-03-07 22:32 UTC, Iamgoofball commented
K