Adds Colored Lights for Energy Swords
tgstation/tgstation pull request #24765
Opened 2017-03-07 00:56 UTC by TalkingCactus

:cl: TalkingCactus
add: Energy swords (and other energy melee weapons) now have a colored light effect when activated.
/:cl:

Also, generalized color code for energy melee weapons to make it easier to add new colored weapons in the future.

![image](http://image.prntscr.com/image/ab61560742474b21ba7eac29bdb77c22.png)

2017-03-07 00:56 UTC, PKPenguin321 commented
But rainbow?

2017-03-07 00:56 UTC, Cyberboss requested changes

2017-03-07 00:56 UTC, Cyberboss commented on code/game/objects/items/weapons/melee/energy.dm
> +/obj/item/weapon/melee/energy/New()
INITIALIZE!!!

2017-03-07 00:56 UTC, ChangelingRain commented
The red and green are really oversaturated compared to the blue and purple

2017-03-07 00:57 UTC, Kromgar commented
I like oversaturated

2017-03-07 00:58 UTC, TalkingCactus commented
Rainbow eswords will change color randomly every time they're processed, didn't want to go overboard and break something with it. Also, need to handle dual sabers.

2017-03-07 01:01 UTC, TalkingCactus commented
The colors are ripped directly from the blade colors. I can saturate the blue and purple a bit more if you want.

2017-03-07 01:04 UTC, GunHog commented
Time for a murdering lights party!

2017-03-07 08:52 UTC, RemieRichards commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/list/possible_colors = list()
null by default

2017-03-07 08:52 UTC, RemieRichards commented on code/game/objects/items/weapons/melee/energy.dm
> +	var/random_color = 0
remove this, simply check if ```possible_colors``` exists and has elements, (```LAZYLEN(possible_colors)```)

2017-03-07 08:53 UTC, RemieRichards commented on code/game/objects/items/weapons/melee/energy.dm
> +	if(random_color && possible_colors.len)
just ```if(LAZYLEN(possible_colors))```

2017-03-07 09:32 UTC, jughu commented
RAVE MURDERBONE!!!

2017-03-08 00:58 UTC, TalkingCactus commented
![bzzt](http://image.prntscr.com/image/dc854d4e96574e43af61f3a86bbeefea.png)

2017-03-08 08:34 UTC, merged