[DNM] Atmospherics just got more autistic - Ports /VG/station multi-layer piping
tgstation/tgstation pull request #24883
Opened 2017-03-09 14:22 UTC by kevinz000

Description/images from testing/Changelog to come when I'm not deprived of sleep.
TL;DR:
![Autismos](https://i.redd.it/3g1jqytoysjy.png)

2017-03-09 14:27 UTC, Cyberboss commented
Why tho?

2017-03-09 14:27 UTC, ma44 commented
Engineering points powergaming

2017-03-09 14:27 UTC, kevinz000 commented
@Cyberboss More compact autismospherics, and players get to screw around more when their creations aren't limited to using one tile per pipe.

2017-03-09 14:30 UTC, Supermichael777 commented
pipes are light tiles are expensive

2017-03-09 14:30 UTC, GunHog commented
I am afraid of the insane contraptions that will spring up from this!

2017-03-09 14:36 UTC, kevinz000 commented
Ok let me put this in a different way
Why.. NOT? :^)

2017-03-09 14:36 UTC, Kraseo commented
ehhehheeehheheeeee

2017-03-09 15:14 UTC, Dorsisdwarf commented
It looks a little messy but I've wanted this for ages

2017-03-09 15:16 UTC, Incoming5643 commented
Air is already the most expensive thing on the station, I don't think we can really afford to make it more costly.

2017-03-09 15:18 UTC, RemieRichards commented
No offence, but you are not the person I would trust to do this.

2017-03-09 15:26 UTC, Supermichael777 commented
How does it react to ventcrawling?

2017-03-09 15:30 UTC, RemieRichards commented
@Supermichael777 Amusingly, both multipipes and ventcrawling were both written by the same /vg/ dev, ComicIronic. so they should work fine together.

2017-03-09 15:33 UTC, Dorsisdwarf commented
I think they meant like, "how do you steer down the five-way junction" remie

2017-03-09 15:35 UTC, RemieRichards commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +		/*
dont include commented code.

2017-03-09 15:36 UTC, RemieRichards commented
My response still works, the developer wrote both, and considered it.
What happens is you have the ventcrawling layer of the pipe you're in, and when you go through one of these multi-layer things, you take its layer, I'm not sure how this allows you to choose which one to go through though.

2017-03-09 15:42 UTC, DanteRU0312 commented
Finally. I'm so sick of the situations like when you want to lay pipes for some project, and you can't because there are scrubber pipes under the floor.

2017-03-09 15:46 UTC, FantasticFwoosh commented
This'll be fun when i buckle someone to four different pipes across a single tile

**laughs in pipe**

2017-03-09 15:50 UTC, RemieRichards commented
@FantasticFwoosh you can only be buckled to one thing, regardless of pipes.

2017-03-09 16:10 UTC, kevinz000 commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +		/*
Wip

2017-03-09 16:32 UTC, SgtxRootbeer commented
I can now add an absurd amount of scrubbers to my art-closet supermatter engine

2017-03-09 16:33 UTC, FantasticFwoosh commented
Well that is until somebody makes handcuffs localised to all limb slots to some extent to be chained by arms & legs to pipes wriggling out of each individually.

2017-03-09 16:36 UTC, Anonmare commented
**Fear**

2017-03-09 16:38 UTC, CPTANT commented
Do we really need 5 pipes on a tile though?

I think setting the limit to 3 would still provide greatly improved compactness for atmos projects, while also reducing the clutter immensely (compared to 5 pipes per tile).

2017-03-09 16:53 UTC, GunHog commented
Let them have all five! Make it look like an ENGINE!

2017-03-09 18:53 UTC, kevinz000 commented
@CPTANT it only gets cluttered if players make it as I doubt mappers will use give tiles per tile much. However if this is merged after I finish it this would be an invitation to make distribution and waste lines share a tile :P

2017-03-09 19:56 UTC, CPTANT commented
Just curious, but how do you determine what your pipe connects to when you wrench it in place?

2017-03-09 19:57 UTC, Cyberboss commented
I'll be alright with this as long as we promise to never map these into stations

2017-03-09 20:10 UTC, PKPenguin321 commented
This is cool but you picked the worst possible example image

2017-03-09 20:11 UTC, PKPenguin321 commented
Like I know what this is so I like it but the uninitiated would look at that and think "gross I don't want that"

2017-03-09 22:22 UTC, optimumtact commented on code/game/machinery/pipe/construction.dm
> +	src.pixel_x = (new_layer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_X
src

2017-03-11 11:24 UTC, Shadowlight213 commented
When can we do a config option to switch atmos mode between linda and zas? :^)

2017-03-11 13:22 UTC, RemieRichards commented
Never, because LINDA > ZAS

2017-03-11 13:53 UTC, kevinz000 commented
@Shadowlight213 when you code it :3c

2017-03-11 21:21 UTC, Shadowlight213 commented
@RemieRichards is it even possible to do zas explosive decompression with linda though?

2017-03-12 03:46 UTC, kevinz000 commented
This is not dead I'll update in a bit.

2017-03-13 22:05 UTC, kevinz000 commented
so apparently pipes are connecting to other layers and other bullshit
time to see what's up...

2017-03-14 08:17 UTC, kevinz000 commented
ignore the laser stuff wrong branch

2017-03-14 17:41 UTC, kevinz000 commented
This is not dead I'm just to busy RN

2017-03-14 17:48 UTC, PKPenguin321 commented
Screee

2017-03-18 09:30 UTC, kevinz000 commented
SHOULD work properly this time, but don't fullmerge yet!

2017-03-19 10:18 UTC, MrStonedOne commented
Suggestion: allow multiple pipes on a tile with this, but only allow one component

2017-03-19 10:29 UTC, CPTANT commented
Perhaps introduce new components that allow multi pipe input/output?

2017-03-19 13:40 UTC, PJB3005 commented
> He didn't even ping Comic

@ComicIronic look at this heresy tbh.

2017-03-19 13:42 UTC, RemieRichards commented
@PJB3005 of course he didn't? I doubt Kevinz even knows who Comic is.

2017-03-19 13:48 UTC, ComicIronic commented
You navigate the manifold layer using the directions the manifold doesn't point in i.e. in a (west) 1-5 (east) manifold, north makes you move up a layer, and south makes you move down.

You should be able to change the number of layers by just editing PIPING_LAYER_MIN, PIPING_LAYER_DEFAULT, and PIPING_LAYER_MAX (and the manifold sprite). Everything else assumed only those defines, last I remember. 

Could do single-tile components using pipeflags, but I never set it up. You'd have to ask the current admins about what effect that has on the game.

2017-03-19 13:49 UTC, ComicIronic commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
My commit was from before to_chat was a thing. Don't forget to change this.

2017-03-19 13:52 UTC, PJB3005 commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
TG doesn't have `to_chat`

2017-03-19 13:52 UTC, RemieRichards commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
we do.

2017-03-19 13:53 UTC, ComicIronic commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
From a quick ctrl+F, I believe they do.

2017-03-19 13:55 UTC, PJB3005 commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
Oh, since 9 days ago.

2017-03-19 15:02 UTC, Cyberboss commented
Not to be a Debbie Downer but I feel like this is just gonna make pipes 10x
more broken than they already are.

On Mar 19, 2017 9:55 AM, "Pieter-Jan Briers" <notifications@github.com>
wrote:

> *@PJB3005* commented on this pull request.
> ------------------------------
>
> In code/modules/atmospherics/machinery/pipes/layermanifold.dm
> <https://github.com/tgstation/tgstation/pull/24883#discussion_r106807132>:
>
> > +		front_nodes[I] = null
> +	if(reference in back_nodes)
> +		var/I = back_nodes.Find(reference)
> +		back_nodes[I] = null
> +	if(reference)
> +		reference.build_network()
> +	findAllConnections()
> +
> +/obj/machinery/atmospherics/pipe/layer_manifold/relaymove(mob/living/user, dir)
> +	if(initialize_directions & dir)
> +		return ..()
> +	if((NORTH|EAST) & dir)
> +		user.ventcrawl_layer = Clamp(user.ventcrawl_layer + 1, PIPING_LAYER_MIN, PIPING_LAYER_MAX)
> +	if((SOUTH|WEST) & dir)
> +		user.ventcrawl_layer = Clamp(user.ventcrawl_layer - 1, PIPING_LAYER_MIN, PIPING_LAYER_MAX)
> +	user << "You align yourself with the [user.ventcrawl_layer]\th output."
>
> Oh, since 9 days ago.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/24883#discussion_r106807132>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHyweroIBEnBkzGIzEoZqDtHBD9rx63lks5rnTPZgaJpZM4MYJJE>
> .
>

2017-03-19 21:22 UTC, kevinz000 commented
@ComicIronic oh yeah pipes keep runtiming because somehow their parent pipenet datum gets deleted, and I'm in pain because I don't know atmoscode so I'm trying to decipher it . reee.

2017-03-20 07:02 UTC, MrStonedOne commented
@kevinz000 me, @Aranclanos and @duncathan have worked hard to keep atmo pipes a symphony of carefully placed checks and creations and deletions of parents.

The runtimes are usually from pipes and or pipenets getting deleted that are still referenced by other pipe(nets) or something not being initialized correctly at the correct moment. (there are two points of initialization for pipes, when they are created, and when they are connected, and different things happen at different times.)

The best way to debug issues is giving pipes a log variable, outputting text to it for operations that mess with the parent value(s), (explaining whats going on and why) and then putting an if by the runtime location and outputting that log so you can see where the breakdown in logic is.

(Infact, I should make this a system that is built into the runtime tracking system)

2017-03-20 14:19 UTC, GunHog commented
**Atmos slays yet another coder!**

2017-03-21 09:20 UTC, Jalleo commented
Not really slay just produce a headache.

2017-03-27 11:21 UTC, kevinz000 commented
MWAHAHAHAHA ok the pipenets work fine now I just need to fix the fucking pipe overlays as they keep showing up as unconnected visually when they're conencted.

2017-03-27 15:44 UTC, SgtxRootbeer commented
Get ready, get set... And freeze!

2017-03-27 16:00 UTC, GunHog commented
> Get ready, get set... And freeze!

This is a pre-freeze PR.

2017-03-27 16:15 UTC, SgtxRootbeer commented
Yeah, but the maintainers will prolly look at it and think "work on this was stopped pre-freeze, and resumed post-freeze". So I will be surprised to see how the fuzzy logic works out.

2017-03-27 16:41 UTC, kevinz000 commented
@SgtxRootbeer they let goof put guncrafting on the list last time.

2017-03-27 21:37 UTC, ExcessiveUseOfCobblestone commented
>  players get to screw around more when their creations aren't limited to using one tile per pipe.

Obvious Non-Atmos Player detected!!!

2017-03-30 05:47 UTC, kevinz000 commented
alright finally this shit is done unless i missed some critical runtime...

2017-03-30 05:48 UTC, MrStonedOne commented
`""""""""""""""""ready for review""""""""""""""""`

2017-03-30 07:51 UTC, kevinz000 commented
OK I FIXED MY SHIT BRING THE REVIEW HAMMER IM READY.

2017-04-01 12:04 UTC, PJB3005 commented
This is the best April's fools PR.

2017-04-02 07:30 UTC, duncathan commented
I disagree the way this is currently set up
I will do a full review later

2017-04-09 21:07 UTC, optimumtact commented
I just don't know about this, piping is already quite a complex system that runtimes consistently and we're gonna go on and add more complexity?

@duncathan I guess if you're happy with it then I'm happy to consider it but it is concerning.

2017-04-10 00:10 UTC, ComicIronic commented
The actual complexity from the layering system isn't very high, unless your pipe connection code isn't particularly robust. The only special behaviour comes from the layer manifold, and it's nothing more special than a 4-fold with 2 more connections. Actual piping code is about the same.

2017-04-10 12:13 UTC, kevinz000 commented
@ComicIronic @duncathan @optimumtact when I did this the only hard part was the pipe layer manifold, as it took a long time for me to figure out how to get it to not fuck up pipenets. Now I just basically copypasted the normal code to nullify and connect nodes, only it does so with up to 10 connections (5 on each side) instead of just 1. The only other code that was runtiming was with components but I fixed that when I realized I accidently removed initialize directions checking, but yeah, the layer manifold is just a regular pipe but its code does whatever on 10 pipes instead of up to 4.

2017-04-12 23:24 UTC, optimumtact commented
admitting you did copypaste code is not a way to make me positive about the pr

2017-04-12 23:32 UTC, optimumtact requested changes
Style nits and some functionality questions

2017-04-12 23:32 UTC, optimumtact commented on code/game/machinery/pipe/construction.dm
> +		user << "<span class='warning'>You need to fasten it to a pipe!</span>"
to chat

2017-04-12 23:32 UTC, optimumtact commented on code/game/machinery/pipe/construction.dm
> +	for(var/obj/machinery/atmospherics/pipe/P in src.loc)
\>src

2017-04-12 23:32 UTC, optimumtact commented on code/game/machinery/pipe/construction.dm
> +	new/obj/machinery/meter( src.loc , pipe)
src

2017-04-12 23:32 UTC, optimumtact commented on code/game/objects/items/weapons/RPD.dm
> +			piping_layer = text2num(href_list["setlayer"])
check is num again and bail if it's still not a valid number

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +		return 1
true

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +				user.forceMove(target_move)
:heart:

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/other/meter.dm
> +		for(var/obj/machinery/atmospherics/pipe/pipe in src.loc)
src

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/other/meter.dm
> +	src.pixel_x = (new_layer - PIPING_LAYER_DEFAULT) * PIPING_LAYER_P_X
src

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	for(var/obj/machinery/atmospherics/A in needs_nullifying)
can this carry any other type? if not just do a typeless loop please

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	for(var/obj/machinery/atmospherics/I in front_nodes)
if these are always going to be the same type please typeless loop

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	for(var/obj/machinery/atmospherics/I in front_nodes)
or a subtype of that type

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +/obj/machinery/atmospherics/pipe/layer_manifold/update_icon()	//HEAVILY WIP FOR UPDATE ICONS!!
if it's WIP why have you marked this pr as ready?, remove this comment

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/layermanifold.dm
> +	while(reference in get_all_connected_nodes())
uhm why not get this as a list once and then loop over it? this is rebuilding a list over and over which is pretty ugly, is there no better way to do this?

why not book keep an allnodes list (updated whenever somethign is added/remove to nodes/frontnodes or backnodes) and then use that

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/pipes.dm
> +		qdel(parent)
QDEL_NULL

2017-04-12 23:32 UTC, optimumtact commented on code/modules/atmospherics/machinery/pipes/pipes.dm
> +		user.drop_item(meter, src.loc)
src src everywehre

2017-04-13 22:28 UTC, duncathan commented
I have spoken with Kevinz about this. This PR will not go through but multipipes will be redone from scratch sometime after the freeze after I finish rewriting pipenets.

2017-04-13 22:28 UTC, closed without merging