Planetstation: RCD Rewrite
tgstation/tgstation pull request #25154
Opened 2017-03-16 01:49 UTC by Iamgoofball

Rewrites how RCDs interact with shit for future Planet Station development.

## For players:
RCDs will try to RCD something, but won't do anything if you can't RCD it.
Costs and delays have been standardized to cost 20 to remove and takes 2 seconds.

## For developers;
You can add RCD effects by just adding an rcd_act() to your atom.
Return 1 if the RCD effect succeeds, return 0 otherwise.

2017-03-16 01:49 UTC, Armhulen commented
Goofball is the hero planetstation needs

2017-03-16 01:51 UTC, Iamgoofball commented on code/game/objects/items/weapons/RCD.dm
> -				var cost = 0
NEVER GONNA DANCE AGAIN

2017-03-16 01:59 UTC, PKPenguin321 commented
Pretty cool, I could imagine some uses for this even outside planetstation

2017-03-16 02:00 UTC, PKPenguin321 commented on code/game/atoms.dm
> +/atom/proc/rcd_act(mob/user, var/obj/item/weapon/rcd/the_rcd)
only complaint that i can foresee is that this might be pathed too far up but im not sure if thats a real issue anyways

2017-03-16 02:00 UTC, Iamgoofball commented on code/game/atoms.dm
> +/atom/proc/rcd_act(mob/user, var/obj/item/weapon/rcd/the_rcd)
never an issue

2017-03-16 02:05 UTC, lzimann commented on code/game/atoms.dm
> +/atom/proc/rcd_act(mob/user, var/obj/item/weapon/rcd/the_rcd)
Well it can allow for even more RCD interactions(and probably less snowflake istypes!)

2017-03-16 07:41 UTC, AnturK commented
Why did you drop the varied costs/times ? It's going to very annoying to build floors with this now.

2017-03-16 07:58 UTC, AnturK commented on code/game/atoms.dm
> +/atom/proc/rcd_act(mob/user, var/obj/item/weapon/rcd/the_rcd)
No var/ in parameters, please

2017-03-16 08:12 UTC, RandomMarine commented
>RAPID construction device
>it's faster to build floors by hand than to use this thing

2017-03-16 14:25 UTC, coiax commented
In an ideal world, I'd have reworked RCDs to use real materials, but just be super fast about it. Probably at around the same time as removing borg "metal synthesisers" and giving them limited specific inventory slots.

2017-03-16 14:27 UTC, RemieRichards commented on code/game/objects/items/weapons/RCD.dm
> -				var cost = 0
GUILTY FEET HAVE GOT NO RHYTHM

2017-03-16 14:28 UTC, lzimann commented on code/game/machinery/doors/airlock.dm
> +			return 1
use TRUE/FALSE for all the returns

2017-03-16 14:47 UTC, Iamgoofball commented
Antur, there was no way to work it in without snowflake and still fit the design doc.

2017-03-16 14:48 UTC, Iamgoofball commented on code/game/machinery/doors/airlock.dm
> +			return 1
Ok

2017-03-16 17:09 UTC, RandomMarine commented
Then this planetstation thing should be separate from the codebase if it's truly impossible. This kills the RCD's usefulness in patching up bombings.

2017-03-16 17:16 UTC, Iamgoofball commented
@RandomMarine Get magboots and internals and just click the tiles. You can run all actions at once.

2017-03-16 17:49 UTC, GunHog commented on code/modules/mining/aux_base_camera.dm
> -	walldelay = 10
Set the general delay to 10 or 25 please, it is intended to be for fast building.

2017-03-16 17:52 UTC, Iamgoofball commented on code/modules/mining/aux_base_camera.dm
> -	walldelay = 10
Sure

2017-03-16 17:53 UTC, Iamgoofball commented on code/game/atoms.dm
> +/atom/proc/rcd_act(mob/user, var/obj/item/weapon/rcd/the_rcd)
ok

2017-03-16 18:27 UTC, Qbopper commented
I agree with the "too slow" considering it's a RAPID construction device, but otherwise good change

2017-03-16 19:28 UTC, ChangelingRain commented
Costs should scale with the amount of materials in the object being constructed; they shouldn't be flat for everything.

2017-03-16 19:40 UTC, KorPhaeron commented
@Iamgoofball 

You could do a delay modifier var on turfs I guess? And then if isturf delay=+ turf.delay_modifier

2017-03-16 19:55 UTC, Iamgoofball commented
Seems snowflake

2017-03-16 19:55 UTC, Iamgoofball commented
Joan, not in the design doc

2017-03-16 20:00 UTC, ChangelingRain requested changes
Not in the design doc, hmm? RCD is mentioned nowhere in the thread, and I'm saying:
Costs should scale with the amount of materials in the object being constructed; they shouldn't be flat for everything.

2017-03-16 20:09 UTC, Iamgoofball commented
Oh fuck you kor told me directly to code this

2017-03-16 20:14 UTC, ChangelingRain commented
If kor told you to make the cost not scale I'll set KOR on fire, too!

2017-03-17 00:07 UTC, Iamgoofball commented
Here's why I'm not doing this:
1. There's no way to do it without snowflake.
2. There's no standardized materials system to figure out whats "in" something, and that's way out of scope here.
3. The copypasta required to do this would get the PR closed.

Requesting an override by @Cheridan or @KorPhaeron unless @ChangelingRain is willing to code what they requested or provide an exact specification on how to do it because I've been sitting here for 3 hours and can't figure out how I'd do this without snowflake.

2017-03-17 01:43 UTC, ChangelingRain commented on code/game/objects/items/weapons/RCD.dm
> +	if(do_after(user, delay, target = A))
This will trigger on everything, regardless of if it's a valid target.

2017-03-17 01:45 UTC, ChangelingRain commented on code/game/turfs/space/space.dm
> +		if(RCD_FLOORWALL)
I mean you're kind of copying this mode switching thing all over; all you need to do is have a proc like `can_rcd(mob/user, obj/item/weapon/rcd/the_rcd)` that returns a list with assoc values that you check, and any other checks you need.
Like the clockwork proselytizer, in fact. Look at that and do what it does for RCDs instead.

2017-03-17 02:33 UTC, ChangelingRain approved these changes

2017-03-17 02:55 UTC, lzimann commented on code/game/objects/structures/window.dm
> +			return 1
true/false

2017-03-17 02:56 UTC, lzimann commented on code/game/objects/items/weapons/RCD.dm
> +				return 1
TRUE

2017-03-17 02:56 UTC, lzimann commented on code/game/objects/structures/grille.dm
> +			WD.anchored = 1
true/false for all

2017-03-17 02:57 UTC, lzimann commented on code/game/turfs/simulated/floor.dm
> +			A.autoclose = 1
true

2017-03-17 02:57 UTC, lzimann commented on code/game/turfs/simulated/floor.dm
> +			G.anchored = 1
true

2017-03-17 03:22 UTC, merged

2017-03-18 22:13 UTC, optimumtact commented
This is awful

2017-03-18 22:16 UTC, Iamgoofball commented
No it's not?