Fixes oversight resulting in ALLCAPS traitor codewords; expands corpus
tgstation/tgstation pull request #25300
Opened 2017-03-20 02:21 UTC by bgobandit

See title, it really explains it all

2017-03-20 02:21 UTC, coiax commented on strings/ion_laws.json
> +	"BLOODY",
inconsistent indentation

2017-03-20 02:27 UTC, bgobandit commented on strings/ion_laws.json
> +	"BLOODY",
fug

2017-03-20 02:40 UTC, ExcessiveUseOfCobblestone commented
If you actually allcaps your codewords you are a dumbo to begin with.

2017-03-20 02:59 UTC, lordpidey commented on strings/ion_laws.json
> +	"SUPERMATTER SHARDS",
Switch this one to just supermatter

2017-03-20 02:59 UTC, lordpidey commented on strings/ion_laws.json
> +        "GREENTEXT",
Let's not have OOC terms in this list please.

2017-03-20 03:47 UTC, bgobandit commented
no, like, it pulls from the ion storm list, which is always UPPERCASE. but I forgot that the locations list failsafes to drinks. which results in all caps

2017-03-20 08:43 UTC, bgobandit commented on strings/ion_laws.json
> +        "GREENTEXT",
it's not OOC, there is an item called "greentext"

2017-03-20 08:43 UTC, bgobandit commented on strings/ion_laws.json
> +	"SUPERMATTER SHARDS",
the ion law this list is used for requires plurals

2017-03-20 09:22 UTC, RemieRichards commented on strings/ion_laws.json
> +	"SUPERMATTER SHARDS",
supermatter is plural and singular, it's like "sheep"
"get me the supermatter"
"pass me some supermatter"
"oh god, supermatter!"

2017-03-20 09:35 UTC, jughu commented
Does anyone have SUPERMATTER SHARDS in their POCKETS!?

2017-03-20 16:43 UTC, bgobandit commented on strings/ion_laws.json
> +	"SUPERMATTER SHARDS",
no I mean like, the generated ion laws will be like "THERE ARE THREE BAWDY SUPERMATTER ON THE STATION" so it doesn't work in that sense

2017-03-21 03:23 UTC, Cheridan commented on strings/ion_laws.json
> -        "BANDITS",
bias detected whoop whoop

2017-03-21 04:07 UTC, bgobandit commented on strings/ion_laws.json
> -        "BANDITS",
it was there before mr. cherry dan

2017-03-21 04:39 UTC, Cheridan commented on strings/ion_laws.json
> -        "BANDITS",
WHOOP WHOOP

2017-03-21 08:25 UTC, Militaires commented on strings/ion_laws.json
>          "AHHHPERATIVES",
wrong

AWWWPERATIVES

2017-03-21 13:52 UTC, coiax commented on strings/ion_laws.json
>          "AHHHPERATIVES",
also there's some indentation issues here

2017-03-21 15:02 UTC, lzimann requested changes
fix the identation on the json(i can even do it for you if you don't want to touch every line manually)

2017-03-21 15:47 UTC, bgobandit commented on strings/ion_laws.json
>          "AHHHPERATIVES",
it's ahhhh

short o rhymes with cop, not with law

2017-03-21 15:48 UTC, bgobandit commented
@lzimann I've tried fixing it but idk what's fucking up

2017-03-21 21:48 UTC, optimumtact commented
You're using tabs when all the JSON files are formatted with spaces as per the JSON spec.

2017-03-22 09:06 UTC, optimumtact commented
swampbandit please

2017-03-22 10:49 UTC, lzimann approved these changes

2017-03-22 10:50 UTC, merged