EngiMarket 6: Prototype Emitter
tgstation/tgstation pull request #25308
Opened 2017-03-20 04:45 UTC by Robustin

Another demo video: https://www.youtube.com/watch?v=cENkm3iDGLQ&feature=youtu.be

The Intergalactic Safety and Health Administration (ISHA) would like to remind engineers that emitters are for power generation purposes only. Any rumors that these devices may be effective against certain biohazard infestations is totally unfounded. 

This emitter works like the others at a fundamental level. What makes it unique is that the emitter can be "manned" to provide custom aiming solutions, and as it fires normally it charges up a reserve battery. That reserve charge can be used to fire the emitter manually like you would any other weapon until the reserve charge is depleted. When switched back to "default" status, the emitter will continue to direct emitter fire at your last target. 

:cl: Robustin
add: The Prototype Emitter. It can be manually aimed and fired to provide a custom targeting solution for advanced engine setups and certain unspeakable infestations. 
/:cl:

2017-03-20 05:20 UTC, Armhulen commented
these have been getting cooler and cooler

2017-03-20 05:24 UTC, PKPenguin321 commented
Axe the view range expansion but other than that neat o

2017-03-20 05:29 UTC, Armhulen commented
y

2017-03-20 05:30 UTC, PKPenguin321 commented
It's buggy and unnecessary

2017-03-20 05:30 UTC, Armhulen commented
fair

2017-03-20 05:58 UTC, Robustin commented
This was is hot off the presses so it's def got some tweaks coming, I'll consider removing the view range but I want to experiment with a smaller range first.

2017-03-20 07:32 UTC, FantasticFwoosh commented
I disagree with this PR, seems too weaponized even for a 'prototype' and trivialises the schematics & planning that goes into engines, rather than building a finely tuned & timed system to be disrupted.

> Just seems to be a anti-blob grudge cannon.

2017-03-20 11:57 UTC, kevinz000 commented
did i mention this looks like absolute ass because of it not being pixel projectiles? i'd highly recommend making custom emitters not legacy. to make it work with reflectors just make reflectors force set its direction on impact and switch it back to legacy because jesus fuck this looks like shit.

2017-03-20 12:26 UTC, Robustin commented
It is pixel projectile?

2017-03-20 12:48 UTC, jughu commented
Can i put it on a mulebot and mount it as a improvised weapon

2017-03-20 14:29 UTC, Robustin commented
Like emitters it must be wrenched+welded over a powered wire, so no crazy hijinx, though now that I've tested this manned turret code you can expect me to add it elsewhere. 

However, the reserve battery does not require a wire to fire but it can only store 10 shots before it has to be secured/repowered, so... maybe?

2017-03-20 16:05 UTC, kevinz000 commented
It isn't. Is legacy

2017-03-20 16:53 UTC, YotaXP commented
Shouldn't normal emitters be able to be aimed in any direction?  Other than technical reasons, I don't see why they can only be aimed orthogonally.

2017-03-21 08:49 UTC, Militaires commented on code/modules/power/singularity/emitter.dm
> +	var/datum/riding/riding_datum = null
pretty sure this will runtime you never initialized this

2017-03-21 12:04 UTC, kevinz000 commented
@Robustin these are NOT pixel projectiles. Pixel projectiles have the legacy var set to FALSE on the projectile. Those are the ones which have visual diagonal movement instead of step_towards or whatever the bullshit with normal projectiles are. However, they don't work with reflectors.

2017-03-21 15:41 UTC, jughu commented
@kevinz000 didnt some vg nerd post a fix that could be ported on the reflector issue thing

2017-03-21 15:45 UTC, jughu commented
https://github.com/HippieStationCode/HippieStation13/pull/3179

2017-03-21 21:17 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +	var/datum/riding/riding_datum = null
Yea I need to remove that, it was a brief experiment to see if it was easier to make these into non-mobile vehicles.

2017-03-21 21:18 UTC, Robustin commented
So pixel projectiles don't work with reflectors? I'm confused.

2017-03-22 06:07 UTC, jughu commented
It doesnt work yea

2017-03-24 00:17 UTC, lzimann requested changes

2017-03-24 00:17 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	..()
this needs to be `. = ..()`

2017-03-24 00:17 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	var/obj/machinery/power/emitter/prototype/PE
Name these variables something that makes more sense, please.

2017-03-24 00:17 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	if(PE.manual == TRUE)
Just `if(PE.manual)`

2017-03-24 00:17 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	if(PE.manual == FALSE)
Just `else` will work.

2017-03-24 00:17 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +		for(var/V in U.held_items)
Ff you want to drop everything he is helding, you can use `U.drop_all_held_items()` and then try to put in U's hands(with `put_in_hands(TC, TRUE)`, and only change the button's variables if the put in hands was true.

2017-03-24 20:34 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +			src.shot_number ++
A lot of these were there originally and are only "added" because I had to cut and paste a lot of code around, but im cutting them.

2017-03-24 20:43 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +	if(PE.manual == FALSE)
there was a reason I didnt use else but I can't remember and it might not be relevant anymore so...

2017-03-24 20:44 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +		for(var/V in U.held_items)
Wouldn't that cause some fuckiness with no-drop abstract weapons?

2017-03-24 21:05 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +	var/obj/machinery/power/emitter/prototype/PE
Done

2017-03-25 02:09 UTC, Bawhoppen commented
I will add reflector functionality back when I return don't worry bout it

2017-03-25 17:21 UTC, Robustin commented on code/modules/power/singularity/emitter.dm
> +	var/view_range = 12
What exactly? I actually took the view_range code from the riding datums

2017-03-25 21:03 UTC, Robustin commented
Ok I think thats it

2017-03-26 02:38 UTC, kevinz000 commented
What the fuck happend to your files changed

2017-03-26 15:41 UTC, Robustin commented
So before I make this any worse, what is the best way to deal with the sudden 200 commits out of nowhere?

2017-03-26 21:51 UTC, kevinz000 commented
Holy fucking shit.

2017-03-28 18:32 UTC, closed without merging