[FROZEN]
tgstation/tgstation pull request #25466
Opened 2017-03-24 18:40 UTC by Cyberboss

Cause 0K freezes nothing by itself right?

2017-04-26 10:12 UTC, duncathan reviewed
I still hate freon as a whole but this is doesn't actually call freon_gas_act() anywhere else so I don't mind

2017-04-26 10:12 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +		var/list/freon_cache = cached_gases["freon"]
what's the point of this? it's already cached as a proc var. is the list access overhead actually significant enough that another read+write here is faster?

2017-04-26 10:12 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +		if(temperature < FREEZE_TEMPERATURE)
this means freon has no effect unless temperature is below `FREEZE_TEMPERATURE`, doesn't it? is this intended?

2017-04-26 10:13 UTC, duncathan requested changes

2017-04-26 10:13 UTC, duncathan commented on code/__DEFINES/atmospherics.dm
> +#define FREEZE_TEMPERATURE 150
Instead of doing it like this, you should just activate reaction datum maximum limits and make this a maximum temperature limit on the freon reaction

2017-04-26 16:10 UTC, Cyberboss commented on code/__DEFINES/atmospherics.dm
> +#define FREEZE_TEMPERATURE 150
But then this wouldn't apply to all gases

2017-04-26 16:10 UTC, Cyberboss commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +		if(temperature < FREEZE_TEMPERATURE)
No it's all gases

2017-04-26 16:21 UTC, Iamgoofball commented on code/game/turfs/open.dm
> +	if(real_freon)
please apply this to all cold if you're going to nerf muh freon to just be "plasma but starts cold"

2017-04-26 16:22 UTC, Iamgoofball commented
:-1: not even going to pretend this isn't just a plan of "make it super common so I can completely nerf the effects into the ground

2017-04-26 16:30 UTC, Cyberboss commented
That is the opposite of what I am doing, freon is what introduced me to SS13. But, I can't do the freon status effect on this bit because of dissipation memes.

Honestly, I'd freon to just be a gas with a stupid high heat cap and have all the other effects in every gas. But, it'll need work as it stands.

2017-04-29 19:49 UTC, duncathan requested changes

2017-04-29 19:49 UTC, duncathan commented on code/__DEFINES/atmospherics.dm
> +#define FREEZE_TEMPERATURE 150
this define is still not necessary

2017-04-29 19:49 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	. = NO_REACTION	//we don't need to garbage collect anything
If a reaction occurs, it just return `REACTING`. No exceptions

2017-04-29 19:49 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		"TEMP" = FREEZE_TEMPERATURE
Freon doesn't even change air temperature, does it? Changing this means that freon does basically nothing. Releasing it won't actually freeze things any more. I don't agree with that; even though I don't like freon you're removing its primary function. If you're gonna do this just remove the gas all the way

2017-04-30 18:36 UTC, Cyberboss commented
Some other day

2017-04-30 18:36 UTC, closed without merging