[DNM]Admin sound tweaks
tgstation/tgstation pull request #25537
Opened 2017-03-27 12:03 UTC by kevinz000

Moves admin sound channel to defines, moves it up too.

2017-03-27 15:10 UTC, Cyberboss requested changes

2017-03-27 15:10 UTC, Cyberboss commented on code/__DEFINES/sound.dm
> +#define SOUND_CHANNEL_ADMIN 1023
Just CHANNEL_ADMIN

2017-03-28 04:44 UTC, Iamgoofball commented on code/__DEFINES/sound.dm
> +#define CHANNEL_ADMIN 1023
this is not how bitflags work

2017-03-28 11:37 UTC, AnturK commented on code/__DEFINES/sound.dm
> +#define CHANNEL_ADMIN 1023
These are not bitflags. [Ref](http://www.byond.com/docs/ref/info.html#/sound/var/channel)

2017-03-28 11:37 UTC, merged