Fixes simplemob wizards from being able to leave the gateway
tgstation/tgstation pull request #25784
Opened 2017-04-01 23:49 UTC by kevinz000

fixes #14202

2017-04-02 09:04 UTC, coiax commented on code/modules/awaymissions/gateway.dm
> +			return
Instead of this, why not implant the simple mob wizards with exile implants? You can put implants in simple animals now.

2017-04-03 02:13 UTC, ChangelingRain requested changes
Do what coiax said; put exile implants in them.

2017-04-03 02:47 UTC, kevinz000 commented
done

2017-04-03 03:01 UTC, ChangelingRain approved these changes

2017-04-03 03:49 UTC, merged