Using TK on Supermatter now burns your head off.
tgstation/tgstation pull request #25873
Opened 2017-04-04 12:35 UTC by RemieRichards

REALLY Fixes #25870.
dumb coiax #25871 

:cl: Remie
fix:U sing TK on the supermatter will burn your head off violently, don't do this.
/:cl:

2017-04-04 12:37 UTC, Razharas commented
I actually like this idead

2017-04-04 12:38 UTC, RemieRichards commented
so do I but I just know people will miss the joke and think it's a real typo (which it originally was but oh well)

2017-04-04 12:39 UTC, Razharas commented
Arent we in freeze though?

2017-04-04 12:39 UTC, RemieRichards commented
It's a fix. (technically it's elevating a bug to a feature, which is "fixing" the bug)

2017-04-04 22:25 UTC, Jalleo requested changes
I suggest making it possible for TK silicons to get burned too

2017-04-04 22:25 UTC, Jalleo commented on code/modules/power/supermatter/supermatter.dm
> +	if(iscarbon(user))
Not supporting silicon TK

2017-04-04 22:49 UTC, lzimann commented
silicons can't have TK

2017-04-05 07:41 UTC, RemieRichards commented
silicons don't have DNA, so they can't have mutations, so they can't have TK.

2017-04-05 12:07 UTC, merged