Atom/Destroy now operates on contents
tgstation/tgstation pull request #25913
Opened 2017-04-05 15:51 UTC by Cyberboss

Fixes #18346

Give me a good reason not to...

2017-04-05 19:29 UTC, coiax commented
This is going to expose/cause a number of odd bugs. But it's probably for the best.

2017-04-05 21:16 UTC, xxalpha commented
I thought it already did, in order to qdel correctly?

2017-04-05 21:45 UTC, Cyberboss commented
Loc isn't a variable that prevents gcing I BELIEVE

On Apr 5, 2017 5:16 PM, "xxalpha" <notifications@github.com> wrote:

> I thought it already did, in order to qdel correctly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/25913#issuecomment-291999841>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywepDSknL6XshwX_-2tRGfpfyebb3Pks5rtATFgaJpZM4M0cvv>
> .
>

2017-04-05 21:46 UTC, RemieRichards commented
your beliefs are odd, ```loc``` is the PRIMARY EXAMPLE of doing garbage collection in DM.
very basic "gc" in DM is usually just a proc that does ```loc = null```, it's literally a requirement to GC.

2017-04-05 21:49 UTC, Cyberboss commented
I meant in reverse order. Eg. If a closet is qdeld and didn't dump it's
shit, the loc vars of the contents won't prevent it from being gc'd. Unless
I am mistaken

On Apr 5, 2017 5:46 PM, "Remie Richards" <notifications@github.com> wrote:

> your beliefs are odd, loc is the PRIMARY EXAMPLE of doing garbage
> collection in DM.
> very basic "gc" in DM is usually just a proc that does loc = null, it's
> literally a requirement to GC.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/25913#issuecomment-292007035>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywenPoaoJqzBoKwhGqqhfo5s3xlU8Iks5rtAvDgaJpZM4M0cvv>
> .
>

2017-04-05 21:50 UTC, RemieRichards commented
in that respect I believe loc is just a normal reference, thus preventing GC.
typically we deleted things inside other things in the container's Destroy() anyway, which is why it went largely unnoticed.

2017-04-05 23:04 UTC, optimumtact commented
The reason is you can't just change something so fundamental and expect everything to respect it and work properly, there's no way to tell if there is anything incorrectly relying on this behaviour for reasons that are not clear.

2017-04-06 10:40 UTC, coiax commented
This definitely would need test merging, because I bet a whole bunch of weird bugs would immediately crop up.

2017-04-06 15:09 UTC, duncathan requested changes

2017-04-06 15:09 UTC, duncathan commented on code/game/atoms.dm
> +		qdel(I)
after this loop is finished you need to do `contents.Cut()` so that the references to these atoms get removed

2017-04-06 15:16 UTC, xxalpha commented on code/game/atoms.dm
> +		qdel(I)
Once the object is deleted those references go away.

2017-04-06 15:21 UTC, Cyberboss commented on code/game/atoms.dm
> +		qdel(I)
Yeah, atom/movable/Destroy sets `loc` to null, so the list will be cleared by itself

2017-04-06 15:34 UTC, duncathan commented on code/game/atoms.dm
> +		qdel(I)
oh ya duh

2017-04-06 15:34 UTC, duncathan commented on code/game/atoms.dm
> +		qdel(I)
I forgot about the automatic connection between loc and contents

2017-04-06 15:43 UTC, duncathan commented
I'm gonna merge this - any issues that arise will only be symptoms of existing issues being uncovered and can be fixed on a case by case basis

2017-04-06 15:43 UTC, merged

2017-04-06 15:50 UTC, Cyberboss commented
O.o

2017-04-06 22:04 UTC, optimumtact commented
@duncathan what were you thinking? this should have been test merged at least once before being merged

/me slaps wrist