Wizard spell logging now uses the actual name of the spell
tgstation/tgstation pull request #26009
Opened 2017-04-08 22:51 UTC by ChangelingRain

Adds logging for wizard spell upgrades
Closes #25985

2017-04-08 22:55 UTC, LanCartwright commented
Thank you for this Joan; I hope this will make tracking spell usage easier in the future and less confusing.

2017-04-08 23:04 UTC, XDTM commented
Why was it like that in the first place

2017-04-08 23:04 UTC, XDTM commented
And why would it close #25985

2017-04-08 23:05 UTC, ChangelingRain commented
it conflicts and it's easier to steal the changes and do it myself.

2017-04-09 00:20 UTC, XDTM commented
Oh i missed the change in the diff

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
"[name]"

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
^

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
^

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
^

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
^

2017-04-09 00:37 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	feedback_add_details("wizard_spell_learned", name)
^

2017-04-09 00:38 UTC, ExcessiveUseOfCobblestone commented
WAIT IM RETARDED HAHAHA

2017-04-09 00:39 UTC, ExcessiveUseOfCobblestone approved these changes

2017-04-09 06:49 UTC, Cheridan commented
oops shit

2017-04-09 06:52 UTC, Shadowlight213 commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 0
Isn't this a balance change more than a fix?

2017-04-09 16:41 UTC, ChangelingRain commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 0
See the linked pr in the OP.

2017-04-09 19:34 UTC, Shadowlight213 commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 0
No idea why coiax thought it cost 0 points originally. I looked at the original pr adding it, and it clearly cost 2 points at the time.

2017-04-09 19:36 UTC, Shadowlight213 requested changes

2017-04-09 19:36 UTC, Shadowlight213 commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 2
This is pointless. The parent spellbook_entry has the cost set to 2. There is no reason to set it again.

2017-04-09 19:43 UTC, ChangelingRain commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 2
I just copied coiax's changes~

2017-04-09 20:02 UTC, Shadowlight213 commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 2
\>blindly copying others changes.
smh

2017-04-09 20:24 UTC, ExcessiveUseOfCobblestone commented on code/game/gamemodes/wizard/spellbook.dm
> +	cost = 2
Coiax of all people!

2017-04-10 21:11 UTC, merged