Changes /obj/machinery to have atom/movable occupants
tgstation/tgstation pull request #26140
Opened 2017-04-12 19:33 UTC by coiax

Currently `occupant` in /obj/machinery is a /mob/living type. I have
changed it to /atom/movable, and made a type cache to determine what to
"look for" when `close_machine()` is called.

This means that machines can have non-mob occupants. I have some design
ideas for this, but that's after the freeze.

2017-04-12 22:05 UTC, Jalleo requested changes
I approve of these changes if there arent any bugs discovered.

2017-04-12 23:18 UTC, xxalpha commented
This is like a feature almost?

2017-04-13 07:55 UTC, RemieRichards commented on code/game/machinery/Sleeper.dm
> +		var/mob/living/mob_occupant = occupant
this does not guarantee they are a mob.

2017-04-13 07:56 UTC, RemieRichards commented on code/game/machinery/Sleeper.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
```istype(mob_occupant) && ...```

2017-04-13 07:57 UTC, RemieRichards commented on code/game/machinery/Sleeper.dm
> +		var/mob/living/mob_occupant = occupant
actually, why does most of the code do isliving checks? shouldn't the typecache be enough? if admins break it, fuck admins.

2017-04-13 14:15 UTC, ExcessiveUseOfCobblestone commented on code/game/machinery/Sleeper.dm
> +		var/mob/living/mob_occupant = occupant
fuck you shitty admin

2017-04-15 17:36 UTC, duncathan commented
@coiax

2017-04-17 06:06 UTC, MrPerson commented
Can I ask what kind of stuff you were intending?

2017-04-17 09:47 UTC, coiax commented
Put brains and heads in the cloning scanner.

2017-04-18 23:11 UTC, optimumtact commented
are you planning on responding to any of the maintainer comments?

2017-04-19 14:38 UTC, coiax commented on code/game/machinery/Sleeper.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
so Remie, should I do type checking constantly, or just assume that we're not badminned?

2017-04-19 14:39 UTC, RemieRichards commented on code/game/machinery/Sleeper.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
assume not badminned.

2017-04-22 11:10 UTC, coiax commented
I'm working on removing the checks currently.

2017-04-22 17:24 UTC, coiax commented
@RemieRichards I have removed all the checks. Also I made VR pods human only.

2017-04-26 22:21 UTC, optimumtact commented
conflicted

2017-04-29 02:01 UTC, optimumtact commented
rip conflicting again sorry

2017-05-01 18:03 UTC, duncathan commented
will reopen when no longer stale

2017-05-01 18:03 UTC, duncathan commented
JK LOL

2017-05-01 20:58 UTC, merged

2017-10-16 23:36 UTC, MrStonedOne commented
This pr increased the server's memeory usage on box station by 220MB

2017-10-17 00:02 UTC, duncathan commented
oops

2017-10-17 05:37 UTC, optimumtact commented
thanks for the update sport