Afk fixup
tgstation/tgstation pull request #26181
Opened 2017-04-13 14:59 UTC by Cyberboss

New configs: 
inactivity_period time until soft afk
afk_period time until hard afk and kick
kick_inactive changed to bool

2017-04-13 15:05 UTC, Davidj361 commented
Hardcoded values make my peepee hard

2017-04-13 15:08 UTC, Jordie0608 commented on code/controllers/configuration.dm
> +	var/inactivity_period = 600	0		//time in ds until a player is considered inactive
![](https://upload.wikimedia.org/wikipedia/en/1/14/Space_rogue_cover.jpg)

2017-04-13 15:08 UTC, Jordie0608 commented on code/controllers/configuration.dm
> +					kick_inactive = text2num(value) * 10 // ^^^
This is meant to be the boolean.

2017-04-13 15:08 UTC, Jordie0608 commented on code/controllers/configuration.dm
> +					inactivity_period = text2num(value)
And this should be the `* 10`

2017-04-13 15:08 UTC, Jordie0608 commented on config/config.txt
> +# INACTIVITY_PERIOD 300
You've mixed around this and `AFK_PERIOD`'s values.

2017-04-13 15:18 UTC, Cyberboss commented on config/config.txt
> +# INACTIVITY_PERIOD 300
fixed in config

2017-04-15 17:35 UTC, duncathan requested changes

2017-04-15 17:35 UTC, duncathan commented on code/controllers/subsystem/server_maint.dm
> +					to_chat(C, "<span class='danger'>You have been inactive for more than [config.afk_period / 60] minutes and have been disconnected.</span>")
shouldn't this be /600 since it's stored as ds?

2017-04-15 19:11 UTC, merged