Standardizes subsystem Shutdown order
tgstation/tgstation pull request #26228
Opened 2017-04-14 23:04 UTC by Cyberboss

Someone will want this in the future, maybe.

2017-04-15 00:48 UTC, Iamgoofball commented on code/__HELPERS/_lists.dm
> -/*
Why was this commented out anyways?

2017-04-15 00:48 UTC, Iamgoofball commented on code/__HELPERS/_lists.dm
>  	for(var/i = input.len; i >= 1; i--)
Update this for the standards

2017-04-15 07:42 UTC, Jordie0608 commented on code/__HELPERS/_lists.dm
> -/*
Because we have `reverseRange()` instead. https://github.com/tgstation/tgstation/blob/master/code/__HELPERS/_lists.dm#L394

2017-04-16 20:40 UTC, duncathan requested changes

2017-04-16 20:40 UTC, duncathan commented on code/controllers/master.dm
> +	subsystems = reverselist(subsystems)
use `reverserange()` instead and just remove the commented out proc from lists.dm

2017-04-17 05:21 UTC, merged