Adds new debug verb for highlighting roundstart ATs
tgstation/tgstation pull request #26492
Opened 2017-04-23 15:41 UTC by coiax

Debug -> Debug Verbs enable
then
Mapping -> Show roundstart AT markers

Will highlight AT turfs, for easier location and comprehension rather
than looking at the list of coords. List of coords still works fine
though.

2017-04-23 15:47 UTC, Cyberboss requested changes

2017-04-23 15:47 UTC, Cyberboss commented on code/modules/admin/verbs/mapping.dm
> +		dat += "[T.x], [T.y], [T.z]\n"
Use ADMINJUMPCOORD or whatever the macro is

2017-04-23 15:48 UTC, coiax commented on code/modules/admin/verbs/mapping.dm
> +		dat += "[T.x], [T.y], [T.z]\n"
Does that work if we embed it in the HTML window?

2017-04-23 15:49 UTC, Cyberboss commented on code/modules/admin/verbs/mapping.dm
> +		dat += "[T.x], [T.y], [T.z]\n"
yeah, it's just an href

2017-04-23 17:45 UTC, lzimann commented on code/modules/admin/verbs/mapping.dm
> +		dat += "[T.x], [T.y], [T.z]\n"
Yup, works fine in popups.

2017-04-28 15:03 UTC, lzimann commented
coiax pls

2017-04-28 15:58 UTC, merged