Ports goonchat
tgstation/tgstation pull request #26542
Opened 2017-04-25 01:16 UTC by lzimann

This time without changing 1k files.

Regex used to convert `\icon[icon]`: `\\icon\[(\w*)\]`

I might have to do an overall look in case I forgot something, but it works.

2017-04-25 01:18 UTC, Ultimate-Chimera commented
why

2017-04-25 03:15 UTC, IlyaIU commented
Utf-8 and emojis, thats why

2017-04-25 04:14 UTC, bgobandit commented
h a p p e n i n g

the absolute madman

2017-04-25 06:03 UTC, Bawhoppen commented
wtf is goonchat

2017-04-25 07:12 UTC, Core0verload commented
It's a HTML-based chat. It supports UTF-8, custom fonts, custom RMB actions (adminpanel on name RMB anyone?) and all kinds of fancy HTML.

2017-04-25 14:23 UTC, Aloraydrel commented
no more stuck text screens is good

2017-04-25 16:06 UTC, YotaXP commented
Holy crap, really?  So much potential in this.

2017-04-25 16:53 UTC, Tacolizard commented
CHANGEABLE FONTS AND FONT SIZE YESSSSS

2017-04-25 17:21 UTC, Iamgoofball commented
# Welcome to RuneScape!

2017-04-26 00:21 UTC, Incoming5643 commented
One big problem I've already noticed is that the system where you could click on the playing area to steal focus from the text box does not seem to work with this system, you HAVE to tab in an out of hotkey mode.

Another is that verbs that generate a lot of lines of local text are extremely slow (Show Server Revision is a good example here)

2017-04-26 09:50 UTC, duncathan commented
Nice

2017-04-28 19:41 UTC, lzimann commented
This is on hold until I can figure out why sometimes it won't load.

2017-04-30 03:45 UTC, bgobandit commented
mush mush lziclown

2017-05-01 14:41 UTC, lzimann commented
And this branch makes linux go crazy(only the branch and on linux)
```
[09:28:49] Runtime in globals.dm,57: undefined proc or verb /datum/controller/global_vars/InitGlobaladmins().

  proc name: Initialize (/datum/controller/global_vars/Initialize)
  src: Global Variables (/datum/controller/global_vars)
  call stack:
  Global Variables (/datum/controller/global_vars): Initialize()
  Global Variables (/datum/controller/global_vars): New()
  Master (/datum/controller/master): New()
  world: ()
```
Resulting in everything that relies on global lists fail.

2017-05-01 15:30 UTC, Cyberboss requested changes

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +var/savefile/iconCache = new /savefile("data/iconCache.sav") //Cache of icons for the browser output
This and chat resources need to use GLOB

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +	. = ..()
remoof

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +	set hidden = 1
TRUE

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +/var/list/bicon_cache = list()
GLOB

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +	var/list/connectionHistory = list() //Contains the connection history passed from chat cookie
Init the lists in New

2017-05-01 15:30 UTC, Cyberboss commented on goon/code/datums/browserOutput.dm
> +/var/list/bicon_cache = list()
Also chat resources and iconCache

2017-05-01 16:22 UTC, AnturK commented
All good but this gets a giant ⛔️ from me as long it's using the retarded /goon directory split for primary ui component of the game.

2017-05-01 17:04 UTC, Cyberboss commented
I smell BYOND fuckery

2017-05-01 17:06 UTC, duncathan commented
isn't the goon directory required for licensing memes

2017-05-01 17:11 UTC, Cyberboss commented
he can just make a module/goonchat and we'll be good

2017-05-01 17:28 UTC, lzimann commented
Moving away from `goon/code` fixed the linux runtimes.

2017-05-01 18:21 UTC, Raschert0 requested changes

2017-05-01 18:21 UTC, Raschert0 commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		if (window.XMLHtpRequest) {
This part is broken. Really. E.g., here must be XMLH**tt**pRequest, not XMLHtpRequest.

2017-05-01 18:21 UTC, Raschert0 commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		xmlHttp.send();
Synchronous ajax isn't working. Use asynchronous ajax. Or jQuerry.

2017-05-01 18:21 UTC, Raschert0 commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		saved += '<style>'+xmlHttp.responseText+'</style>';
Styles in body? Doesn't work.

2017-05-01 18:21 UTC, Raschert0 commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		saved = saved.replace(/</g, '&lt;');
These two replaces break markup.

And so on...

2017-05-01 18:24 UTC, Cyberboss commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		if (window.XMLHtpRequest) {
w e w

2017-05-01 18:33 UTC, Raschert0 commented on code/modules/goonchat/browserassets/js/browserOutput.js
> +		if (window.XMLHtpRequest) {
Aaand, goonchat is not supporting IE older than 8 (IMO). You do not need this "if". Just put here
`xmlHttp = new XMLHttpRequest();`
(and yes, xmlHttp is still undefined)

2017-05-01 21:15 UTC, hornygranny commented
get rid of this garbage and port goonsay

2017-05-01 21:41 UTC, lzimann commented
The chat not loading bug doesn't seem to be happening anymore.

2017-05-01 23:08 UTC, Cyberboss commented
:shipit:

On May 1, 2017 5:41 PM, "Leo" <notifications@github.com> wrote:

> The chat not loading bug doesn't seem to be happening anymore.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/26542#issuecomment-298440449>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywesZ5kywt53hn0HHQanspp-Jn3CC8ks5r1lGVgaJpZM4NG474>
> .
>

2017-05-02 20:37 UTC, lzimann commented
Well, this is pretty much dead since I have no clue on why it fails to load the JS sometimes, there is no runtime error or anything.

2017-05-02 20:43 UTC, Iamgoofball commented
@wirewraith ?

2017-05-02 20:44 UTC, Cyberboss commented
Dont give up screee!

2017-05-02 20:46 UTC, Wirewraith commented
I can help debug tonight via IRC

2017-05-02 20:49 UTC, Iamgoofball commented
god bless

2017-05-02 20:49 UTC, Iamgoofball commented
hang on is the debug output anything about stolen trees?

2017-05-02 20:49 UTC, Iamgoofball commented
it should tell you how many of your trees have been stolen

2017-05-02 20:50 UTC, lzimann commented
The biggest problem is that I can't reproduce this bug locally(I even tried in a VM to simulate a server lag), so it gets really hard to figure it out.

2017-05-02 20:51 UTC, Iamgoofball commented
have you tried methamphetamines? those usually support software devs

2017-05-03 14:27 UTC, Cyberboss requested changes

2017-05-03 14:27 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +/datum/chatOutput/proc/pingLoop()
We have our own ping system, isn't needed.

2017-05-03 14:27 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +		sleep(30)
This should be called by the server_maint subsystem, but, like I said, it's not needed

2017-05-03 14:27 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +	if (!obj)
Can you rename this to NOT obj

2017-05-03 14:27 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +	if (!obj)
Same

2017-05-03 14:31 UTC, lzimann commented on code/modules/goonchat/browserOutput.dm
> +		sleep(30)
Yea I have plans to change to our own ping(or even remove this entirely) later on.

2017-05-03 14:33 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +	if (istype(message, /image) || istype(message, /sound) || istype(target, /savefile) || !(ismob(target) || islist(target) || istype(target, /client) || istype(target, /datum/log) || target == world))
Clients and world are a very valid target for chat output. What happens to those messages?

2017-05-03 14:36 UTC, Cyberboss requested changes
Try putting all chat resources in the rsc with `''` and throw on a testmerge. See if that fixes it

2017-05-03 15:11 UTC, Wirewraith commented on code/modules/goonchat/browserOutput.dm
> +	if (istype(message, /image) || istype(message, /sound) || istype(target, /savefile) || !(ismob(target) || islist(target) || istype(target, /client) || istype(target, /datum/log) || target == world))
On goonstation I have since added a condition to check for target == world and trigger an output loop if so.

2017-05-03 16:51 UTC, lzimann commented
Alright, so Wire hooked me up with a javascript error handler. This should help in figuring out the problem.

2017-05-04 06:02 UTC, duncathan commented on code/modules/goonchat/browserOutput.dm
> +	if (!obj)
IMO make these take atom/A as argument and then adjust their code to account for that

2017-05-05 01:36 UTC, closed without merging

2017-05-05 01:37 UTC, lzimann commented
The bug keeps happening, no runtime, no JS error, no indication what it could be or how to even reproduce, so if anyone else wants to give it a try, feel free.

2017-05-05 03:04 UTC, Iamgoofball commented
What is the bug

2017-05-05 03:06 UTC, PKPenguin321 commented
>Well, this is pretty much dead since I have no clue on why it fails to load the JS sometimes, there is no runtime error or anything.

Sad this is stopped for now

2017-05-05 03:22 UTC, lzimann commented
@Iamgoofball People fail to load the chat after a random period of time, and if anyone reconnects they fail to load aswell.

2017-05-05 16:51 UTC, Iamgoofball commented
@PJB3005 ?

2017-05-05 17:29 UTC, PJB3005 commented
No clue sorry.

2017-05-05 17:29 UTC, Iamgoofball commented
@lzimann get their system info and windows(internet explorer) versions

2017-05-05 17:30 UTC, lzimann commented
Happens with everyone

2017-05-05 17:30 UTC, Cyberboss commented
I'll take over this when I finish #26534

2017-05-05 17:30 UTC, Iamgoofball commented
everyone at the same time consistently doesn't load?

it's possible these are our "im on a windows xp VM with the cid scrambler for PRIVACY I SWEAR" folks

2017-05-05 17:37 UTC, PJB3005 commented
Actually shit I think I know what it might be.

It's actually really simple to fix. You need to send a file to the client with the following data (as base64):

```
cmVtYWtlIHdoZW4=
```

2017-05-05 17:38 UTC, Iamgoofball commented
don't fuck with the poor guy he's been trying to do goonchat for half a year now

2017-05-05 17:38 UTC, Wirewraith commented
It didn't take me this long to make goonchat from scratch :|

2017-05-05 17:40 UTC, Cyberboss commented
PJB PLEASE

2017-05-05 17:41 UTC, Cyberboss commented
Also, I'm thinking I may just re-implement it at this point

2017-05-05 17:42 UTC, Iamgoofball commented
@Wirewraith none of us have any understanding about BYOND and html/javascript so we're basically just pissing in the dark hoping we hit something

2017-05-05 17:42 UTC, Wirewraith commented
That's about what I figured.

2017-05-05 17:43 UTC, PJB3005 commented
Jesus how hard can it be. I'm even considering rewriting /vg/ goonchat in TypeScript just to learn the language.

2017-05-05 17:44 UTC, PJB3005 commented
Actually I just realized how hard it could be considering this is where tgui came from...

2017-05-05 17:46 UTC, Iamgoofball commented
tgui is once again another case of "UI guy pops out of thin air, drops his hot mixtape, leaves behind minimal instruction and some build tools, then disappears"

2017-05-05 18:10 UTC, Incoming5643 commented
UI devs never stick around. They just dump their vision then run away into the night.

Never trust Front Ender, never ever.

2017-05-05 21:44 UTC, optimumtact commented
speak for yourself goof