Gas reaction micro optimizations
tgstation/tgstation pull request #26619
Opened 2017-04-26 16:45 UTC by Cyberboss

@duncathan

2017-04-27 19:50 UTC, Jalleo commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
This confuses me. 
If temp is less than min_req temp it continues.

2017-04-27 19:53 UTC, Jalleo commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
Also if we go with minimum and maximum req temps and energy we can use TO instead.  I believe its faster. (Maintainer would have to confirm.

2017-04-28 11:18 UTC, lzimann commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
Can you make this not be in two lines? It's awful to read like this.

2017-04-29 09:37 UTC, duncathan requested changes
Has this been profiled? I'm not convinced that these small changes are actually faster. List accesses are very fast; the reason we cache vars elsewhere is because datum var accesses are very slow. Please do an effective profile to prove that these work, otherwise I don't want to see this merged.

2017-04-29 09:37 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +				var/list/cgi = cached_gases[id]
I don't think this is appropriate, since in most cases (requirements not being met is the most common case) this check will short circuit

2017-04-29 09:37 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
What doesn't make sense? It continues looping through the reactions if this one's temperature is too low. What do you mean by TO?

2017-04-29 09:37 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
I respectfully disagree; splitting it up makes it very clear that there are two overall parts and also makes sure that the line doesn't get obnoxiously long. I'd prefer it be split into two whole if blocks for readability than condense it into one line

2017-04-29 09:37 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			min_reqs -= temp_and_energy
Please profile this change separately from the others. I am more inclined to believe this one will make a difference than the other changes here

2017-04-29 14:59 UTC, lzimann commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
The line is not even long. I just have the opinion that multilines are cancer and should be avoided as much as possible.

2017-04-30 14:20 UTC, Jalleo commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			if((!isnull(min_temp) && temp < min_temp) \
Yeah I was tired at the time Cyberboss explained.

2017-04-30 18:29 UTC, Cyberboss commented
Too lazy

2017-04-30 18:29 UTC, closed without merging

2017-04-30 18:34 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +			min_reqs -= temp_and_energy
I'm gonna profile this one myself and if it makes a difference I'll pr it. Not the others tho