Revert "When jumpsuits take severe damage, their suit sensors break."
tgstation/tgstation pull request #26638
Opened 2017-04-27 07:44 UTC by coiax

Reverts tgstation/tgstation#26601

:cl: coiax
del: Suit sensors are no longer disabled by jumpsuits taking damage.
/:cl:

> xxalpha: So when you actually need them they won't work?

I mean, come on, this is a fairly major balance change, merged on the 24 hour mark.

2017-04-27 07:44 UTC, optimumtact commented
no knee jerk reverts please

2017-04-27 07:45 UTC, optimumtact commented
@Cheridan @KorPhaeron

2017-04-27 15:34 UTC, KorPhaeron commented
I am torn because I dont really like suit sensors in the first place but having something meant to report damage being turned off by damage just seems so counterintuitive.

It's like a smoke detector that gets turned off by smoke.

2017-04-27 15:37 UTC, ChangelingRain commented
it seems very counterintuitive, yes.

2017-04-29 01:53 UTC, optimumtact commented
I was hoping for a more definitive answer than that

2017-04-29 18:48 UTC, KorPhaeron commented
Everyone is talking about it in the last PR anyway and coiax asked to post something here

2017-04-29 23:29 UTC, bgobandit commented
ok since this is unlocked I forget who suggested this:

"I suggest a compromise: a damaged suit sensor will never stop working no matter how much it is damaged, but if it's severely damaged (to the point you want it to be disabled in this PR) it will provide information with a certain degree of error."

first off clothes only have one tier of damage before they break, IIRC (it's the point where the sprite changes). that said I am willing to do this, however, I am not sure how to do it without it being a coding nightmare

2017-04-30 21:17 UTC, optimumtact commented
I still think it's fine and neither Joan or Kor were clear on where they wanted so I'm just going to decide to leave it as is.

2017-04-30 21:29 UTC, ChangelingRain requested changes
you understand

2017-04-30 21:29 UTC, ChangelingRain commented on code/__DEFINES/misc.dm
> -#define LOCKED_SENSORS 2
keep these defines and the other fixes, but remove sensors actually breaking

2017-05-01 18:03 UTC, closed without merging

2017-05-01 18:04 UTC, coiax commented
I'm gonna change it without reverting the whole PR