Fixes Set Round End Sound.
tgstation/tgstation pull request #26841
Opened 2017-05-03 05:52 UTC by bgobandit

Fixes https://github.com/tgstation/tgstation/issues/26467.

note: world.dm is some high-level clownery, I tested this but please let me know if I fucked up regardless

2017-05-03 16:56 UTC, Cyberboss requested changes

2017-05-03 16:56 UTC, Cyberboss commented on code/world.dm
> +	if(SSticker && SSticker.round_end_sound)
There is no way for SSticker to not exist, remove the check

2017-05-03 18:05 UTC, bgobandit commented on code/world.dm
> +	if(SSticker && SSticker.round_end_sound)
I assumed it was some kind of sanity thing

2017-05-04 18:33 UTC, lzimann commented on code/world.dm
> +	if(SSticker && SSticker.round_end_sound)
If SSticker doesn't exist, something is very, very wrong

2017-05-04 19:42 UTC, merged