Adds Sticks of Butter, Mayonnaise, and Mix function to grinder
tgstation/tgstation pull request #27098
Opened 2017-05-09 16:16 UTC by TehZombehz

:cl: TehZombehz
add: Sticks of butter and liquid mayonnaise can now be produced via a new 'mix' function on the grinder. Please eat responsibly.
/:cl:

![butter](https://cloud.githubusercontent.com/assets/15373249/25860964/d9b2f2d8-34a8-11e7-8e74-486830ae23df.png) ![mayo](https://cloud.githubusercontent.com/assets/15373249/25860965/d9b5083e-34a8-11e7-805b-4837b5b0fe46.png)
A new 'mix' function on the grinder can be used to make sticks of butter and liquid mayonnaise. Sticks of butter require 15 units of milk, and egg yolk is made into mayonnaise in a 1-to-1 ratio. 
There are currently no uses for either in cooking recipes ~~aside from frying them and being a fat slob~~, but I plan to add some in the future.
I believe butter makes for the cornerstone of much cooking, and mayonnaise is great for many creamy recipes. I figure space could benefit from their addition. 
It's been a while since I've made a new PR and I'm a little wary about messing with the grinder, so please tell me of any erroneous work.

2017-05-09 16:17 UTC, InsaneHyena commented
I am Ivan Ivanovich, and I approve of this PR.

2017-05-09 16:17 UTC, Pascal125 commented
10/10 Merge this right now.

2017-05-09 16:18 UTC, kevinz000 commented
Yay :D

2017-05-09 16:22 UTC, Repukan commented
Cyka blyat drink de fuggin mayonez

2017-05-09 16:46 UTC, Tacolizard commented
_**d E e P f R i E d B u T t E r**_

2017-05-09 17:01 UTC, Anonmare commented
To add: Adidas tracksuit, squatting and bandit radio

2017-05-09 17:01 UTC, Armhulen commented
fuck I was gonna do the deep fried butter joke

2017-05-09 17:02 UTC, FantasticFwoosh commented
Don't forget slavic milkmaids for churning like that live butter churning demo they did at eurovision.

2017-05-09 21:43 UTC, Supermichael777 commented
remove mayo worst spread

2017-05-10 00:46 UTC, bgobandit commented
I approve of bandit radio

2017-05-10 02:02 UTC, PopNotes commented
You want _another_ butterbar..?

2017-05-10 03:00 UTC, Armhulen commented
ROD + BUTTER = BUTTER ON A STICK

then you deepfry it

2017-05-10 03:00 UTC, Armhulen commented
make that also stop your heart

2017-05-10 08:24 UTC, Razharas commented
mayo needs oil, lemon juice and mustard besides the eggs

2017-05-10 09:01 UTC, TehZombehz commented
Throwing eggs in a machine and getting mayo works for games like harvest moon, it'll work for spess.

2017-05-10 09:21 UTC, Razharas commented
We are above games which simplify their gameplay to appease filthy casuals

2017-05-10 10:32 UTC, TehZombehz commented
Should I rework all cake to require butter?

2017-05-10 17:23 UTC, lzimann requested changes
Some small things.

2017-05-10 17:23 UTC, lzimann commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		operating = 1
`TRUE`

2017-05-10 17:23 UTC, lzimann commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		spawn(50)
Use `addtimer` here, spawns are bad!

2017-05-10 17:23 UTC, lzimann commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +				operating = 0
`FALSE`

2017-05-10 17:23 UTC, lzimann commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +						if (beaker.reagents.has_reagent("milk", 15))
You can just do
```
while(beaker.reagents.remove_reagent("milk", 15)
    new /obj/item/weapon/reagent_containers/food/snacks/butter(get_turf(src))
```

2017-05-10 17:44 UTC, TehZombehz commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +						if (beaker.reagents.has_reagent("milk", 15))
This is the only part of this that is actually my code. The rest of this is changes you're asking me to make to pre-existing grinder code.

2017-05-10 19:00 UTC, Iamgoofball commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +						if (beaker.reagents.has_reagent("milk", 15))
whoa man reagent code isnt set up for while()s @lzimann

2017-05-10 19:01 UTC, lzimann commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +						if (beaker.reagents.has_reagent("milk", 15))
Ugh, why nothing works like I assume they do?

2017-05-10 20:47 UTC, lzimann approved these changes

2017-05-10 20:47 UTC, merged