Gives the clown a pie cannon
tgstation/tgstation pull request #27114
Opened 2017-05-10 11:59 UTC by kevinz000

Honk!

2017-05-10 12:00 UTC, The-clown-known-as-Pepe commented
# _**honk**_

2017-05-10 12:00 UTC, GunHog commented
I am cool with this, as long as it does not stun people!

2017-05-10 12:02 UTC, kevinz000 commented
@GunHog only if you use a banana cream pie, lol.

2017-05-10 12:02 UTC, RemieRichards commented
This was foretold in the legends.

2017-05-10 12:04 UTC, RemieRichards commented on code/game/objects/items/weapons/clown.dm
> +/obj/item/weapon/pie_cannon
this is kind of disgusting tbh.

It should really just be a special pneumatic cannon that only takes pies (then you don't need this projectile nonsense)

2017-05-10 12:05 UTC, AnturK commented
Can only load one pie 👎

2017-05-10 12:06 UTC, RemieRichards commented
Fixing it so it subtypes from pneumatic cannons would allow it to hold multiple pies :^)

2017-05-10 12:08 UTC, kevinz000 commented
@RemieRichards I kinda did it on purpose because projectiles are better in terms of aiming and otherwise, as pneumatic cannons are throwcode and that's way less accurate than projectiles...

2017-05-10 12:09 UTC, RemieRichards commented
@kevinz000 make it a pneumatic cannon or it's a tablin' for you.

2017-05-10 12:11 UTC, kevinz000 commented
:(

2017-05-10 12:14 UTC, kevinz000 commented
wip while i make the targetting not shit

2017-05-10 12:15 UTC, FantasticFwoosh commented
Im not sure the clown needs more incentive than what they already have in dragging the cream pie locker/bag purely full of pies around with them fully stocked & stun locking people by throwing as it is.

2017-05-10 12:25 UTC, kevinz000 commented
@FantasticFwoosh fun hater

2017-05-10 12:29 UTC, AnturK commented
How about you fix pneumatic cannons instead of making snowflake type

2017-05-10 12:30 UTC, RemieRichards commented
Uhhhh, @AnturK

2017-05-10 12:31 UTC, AnturK commented
I'm too slow with refreshing pages.

2017-05-10 12:31 UTC, kevinz000 commented
lul

2017-05-10 14:41 UTC, Bawhoppen commented
wasn't this a joke in the ideas subforum description at one point?

2017-05-10 14:42 UTC, RemieRichards commented
@Bawhoppen 
>This was foretold in the legends.

2017-05-10 14:49 UTC, Bawhoppen commented
I saw your comment but I couldn't be sure if that we were on the same page

2017-05-10 14:50 UTC, RemieRichards commented
fair enough, I was referring to that yes.

2017-05-10 15:43 UTC, FantasticFwoosh commented
This would be as powerful as a HONK mech weapon, why hasn't this PR been closed down already?

2017-05-10 23:38 UTC, kevinz000 commented
@Bawhoppen i did this because i witnessed a bagil round where the clown got sued for cream pieing someone
now imagine if he had a roundstart cannon to do it with?

2017-05-11 07:47 UTC, RemieRichards commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +			for(var/i = 0, i < throw_amount, i++)
You know what's wrong here.

2017-05-11 11:15 UTC, kevinz000 commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +			for(var/i = 0, i < throw_amount, i++)
is it the two modes having nearly the exact same code and still being separated?

2017-05-11 11:26 UTC, RemieRichards commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +		for(var/i = 0, i < throw_amount, i++)
and this

2017-05-11 11:26 UTC, kevinz000 commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +		for(var/i = 0, i < throw_amount, i++)
........ uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh im assuming its a bad thing that i can't tell what's wrong..

2017-05-11 11:27 UTC, RemieRichards commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +		for(var/i = 0, i < throw_amount, i++)
in to, loop please.

2017-05-11 11:51 UTC, kevinz000 commented
whoop it has runtimes =v

2017-05-11 12:02 UTC, RemieRichards commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	for(var/i = 0, i < amount, i++)
*cough*

2017-05-11 12:03 UTC, kevinz000 commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	for(var/i = 0, i < amount, i++)
wooops

2017-05-11 12:03 UTC, RemieRichards commented
Due to the clumsy check, the clown will hit themselves with the pies 75% of the time.

2017-05-11 12:07 UTC, kevinz000 commented
oh woops let me fix that

2017-05-11 12:08 UTC, RemieRichards commented
Also, one thing about ```X in Y to Z``` loops is that they're INCLUSIVE, meaning they match ```<=```'s not ```<```'s like you had before, just give them a once over to make sure they're still doing what you wanted.

2017-05-11 12:08 UTC, kevinz000 commented
Alright, thanks.

2017-05-11 15:49 UTC, Tacolizard commented
the sprite sux

2017-05-11 22:59 UTC, kevinz000 commented
@Tacolizard feel free to give me new ones.

2017-05-12 03:22 UTC, Haevacht commented
that sprite is not garish enough for a clown weapon

2017-05-12 14:24 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	var/clumsyCheck = TRUE
Badmin verbs detected

2017-05-12 14:29 UTC, Cyberboss requested changes

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	if(I.w_class > src.w_class)
remove src

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	loadedItems.Add(I)
+=

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	I.loc = get_turf(src)
forcemove

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +	loadedItems.Remove(I)
-=

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +			return TRUE
You need to qdel I if this check fails

2017-05-12 14:29 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +			var/obj/item/I = loadedItems[1]
Put this assignment in the else of the if on the next line

2017-05-12 14:32 UTC, Cyberboss requested changes

2017-05-12 14:32 UTC, Cyberboss commented on code/game/objects/items/weapons/pneumaticCannon.dm
> +		return ..()
Two refactors are needed add a `CanLoadItemProc` and remove this attackby.
ALSO the parent's attackby doesn't check for harm intent

2017-05-13 15:01 UTC, merged