Adds a new steal objective, the Supermatter Sliver.
tgstation/tgstation pull request #27137
Opened 2017-05-11 01:04 UTC by bgobandit

:cl: bandit
add: The Syndicate has been observed with supermatter technology. Nanotrasen is investigating potential tampering with its supermatter devices.
add: Traitors can steal supermatter slivers now. It works much like the plutonium core.
/:cl:

Traitors have a new steal objective, to extract a sliver of a supermatter crystal. This works much like stealing the plutonium core:

- Use a special scalpel (different fluff is welcome) to slice a sliver off. Like the plutonium core, this sliver will periodically emit radiation if not stored.
- Pick the sliver up with tongs, also provided. If you or anything else touches the crystal, then it dusts. If you use the tongs to attack a person, the resulting force will dust you as well (so you can't go around instakilling people). The sliver will also be destroyed, to prevent a chain reaction of people dusting people.
- Use the tongs to put it in the container, provided as well.
- Once you extract a sliver, the supermatter will gain energy, requiring you to have protection. The exact amount of energy can be tweaked, the idea is that delamination will not happen immediately but that it is serious, noticeable sabotage and the traitor should probably get out fast.

What this adds to the game: Steal objectives should be more difficult than they are. No one gives a shit about, say, the blueprints. The supermatter also lacks a meaningful traitor interaction that is not just releasing a singularity. This provides that. 

This is a work in progress and there are still bugs, but I wanted to get the idea and basic functionality down.

**TO DO:**
- Finish the tongs-dusting interactions, including properly getting rid of the sliver if you dust something with it (it is microscopic, after all)
- Prevent people from dragging the sliver
- Prevent infinite slivers from being made, turning the SM into a radiation deathtrap (or do I want this?)
- You can only extract a sliver of an active supermatter crystal? possibly?
- Enabling people to open the container, and by extension the nuke core container?
- Make this all work with shards from cargo too, if tators want to do that

2017-05-11 01:07 UTC, PKPenguin321 commented
>The sliver will also be destroyed, to prevent a chain reaction of people dusting people.

Lame!

2017-05-11 01:18 UTC, Tokiko1 commented
Consider making the sliver not dust and disappear, but rather burn off a random bodypart from both people but stay around.

2017-05-11 01:56 UTC, swindly commented on code/game/objects/items/theft_tools.dm
> +	desc = "A tiny receptacle that releases an inert freon mix upon sealing, allowing a sliver of a supermatter crystal to be safely stored.."
..

2017-05-11 02:04 UTC, Bawhoppen commented
lore: eswords are powered by supermatter slivers

2017-05-11 02:31 UTC, RandomMarine commented
We already have tons of traitors bungling at stealing the nuke core and dying from radiation.

If this gets merged I'll look forward to watching all the tots dust themselves.

2017-05-11 04:05 UTC, Armhulen commented
Make it a supermatter shard instead of sliver

2017-05-11 04:06 UTC, bgobandit commented
we already have supermatter shards and they are not items

2017-05-11 04:10 UTC, octareenroon91 commented
Got something against slivers?
Maybe you'd like splinters or dust or flakes?

Consider syndie whisk-broom and dust pan for stealing supermatter dust.

2017-05-11 05:55 UTC, Armhulen commented
It's a giant crystal, be creative

2017-05-11 11:41 UTC, fludd12 commented
"The syndicate cannot bypass the Nanotrasen engine core monopoly. Harvest and deliver the Supermatter crystalline growth seed by extracting it from an active Supermatter."

2017-05-11 13:02 UTC, kevinz000 commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [tongs] is stuck to your hand!</span>")
How will the tongs being stuck to your hand prevent you from operating it while in your hand to release the sliver..?

2017-05-11 15:17 UTC, bgobandit commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [tongs] is stuck to your hand!</span>")
sanity check I guess

2017-05-11 15:18 UTC, cebutris commented
The special tongs should be a special hemostat, just to keep the surgery vibe going. Also, they should replace the special supermatter scalpel/hemostat (or tongs) should come in the syndicate surgery dufflebag, like how the nuke screwdriver comes in the fully loaded toolbox

2017-05-11 15:18 UTC, bgobandit commented
they're not really a hemostat, the sprite is just similar (actually I think I even used the retractor sprite)

2017-05-11 15:28 UTC, cebutris commented
Well yeah, I'm just suggesting that it be a hemostat (or a retractor, I guess) instead of tongs. I was thinking is if one step is a surgery tool, why not have another step use another surgery tool? The hemostat works well for this, because it's good at picking up small things.

2017-05-11 15:43 UTC, bgobandit commented
but... they are as much a hemostat as the scalpel is??

2017-05-11 15:46 UTC, Tacolizard commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [tongs] is stuck to your hand!</span>")
edward tongerhands

2017-05-11 15:46 UTC, Tacolizard commented
the tongs should be called supermatter salad tongs

2017-05-11 15:47 UTC, Tacolizard commented
you know tong is a really weird word like is that even a real word or is it slang

2017-05-11 15:48 UTC, cebutris commented
New recipe: Supermatter salad. Looks and is crafted like a regular salad, but with supermatter sliver. Dusts anyone who eats it.

2017-05-11 15:50 UTC, Tacolizard commented
it must be made with the supermatter tongs though

2017-05-11 15:50 UTC, Tacolizard commented
@WJohn come make a salad tongs sprite we need it for the lore

2017-05-11 15:51 UTC, cebutris commented
All chefs now get salad tongs to make salads. Syndicate cooking set contains supermatter salad tongs.

2017-05-11 15:55 UTC, Tacolizard commented
im gonna crash this pr with no survivors

salad tongs
salad tongs
salad tongs
salad tongs

2017-05-11 20:22 UTC, Anonmare commented
Gonna be difficult to harvest anything from the SM if competent engies are in charge (>inb4 "Competent" engies)
Still doable though

2017-05-11 21:18 UTC, ExcessiveUseOfCobblestone commented
> Supermatter tongs should be makeshift hemostats

fund it.

2017-05-12 00:11 UTC, swindly commented
Engineers shouldn't get this objective.

2017-05-12 00:15 UTC, bgobandit commented
why not? they have the same problems everyone else does (other engies being around). we don't prevent HoPs from getting steal objectives or the CMO from the hypospray, etc

2017-05-12 00:32 UTC, swindly commented
CMOs are excluded from stealing the hypospray in line 54 of objective_items.dm.

2017-05-12 02:06 UTC, optimumtact commented
bog bandit opening a work in progress pr so they can sit on the tracker for five weeks taking forever to respond.

2017-05-12 04:12 UTC, bgobandit commented
it's a work day you fruit

2017-05-12 10:49 UTC, YakumoChen commented
going to be the devil's advocate and disapprove any objective that encourages delaminating the engine. It's hard enough for the engineers to keep maintained, much less fix it, and we've just started to improve from it blowing up literally every round only recenrly

2017-05-12 10:51 UTC, YakumoChen commented
Also keep in mind that an active supermatter will have all the problems of space wind and a supercooled chamber, requiring gear checks much more focused and difficult then stealing the nuke core.

2017-05-12 14:11 UTC, Cyberboss requested changes

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	var/obj/item/nuke_core/core = null
No `= null`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		playsound(loc, 'sound/items/Deconstruct.ogg', 60, 1)
playsound(src, ...

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	return 1
TRUE

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		return 0
FALSE

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		src.forceMove(tongs)
remove src

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	var/obj/item/nuke_core/supermatter_sliver/sliver = null
remove the `= null`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	var/obj/item/nuke_core/supermatter_sliver/sliver = null
You also need to QDEL_NULL this in `Destroy()`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [tongs] is stuck to your hand!</span>")
`\The`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +			return
This is a trailing return, remove it

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	qdel(sliver)
QDEL_NULL

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	var/obj/item/nuke_core/supermatter_sliver/sliver = null
remove the `= null`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	var/obj/item/nuke_core/supermatter_sliver/sliver = null
QDEL_NULL it in `Destroy()`

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	return 1
TRUE

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		return 0
FALSE

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	ded.dust()
play the supermatter consume sound

2017-05-12 14:11 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +/obj/item/weapon/hemostat/supermatter/proc/Consume(atom/movable/AM, mob/user)
play the supermatter consume sound

2017-05-12 14:11 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +	else if(user.drop_item(W))
user.dropItemToGround(W)

2017-05-12 14:11 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +		playsound(loc, W.usesound, 100, 1)
playsound(src, ...

2017-05-12 14:11 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +			to_chat(user, "<span class='notice'>You extract a sliver from [src]. [src] begins to react violently!</span>")
The text entries should probably be prefixed with \the

2017-05-12 14:11 UTC, Cyberboss commented on tgstation.dme
> -#include "code\controllers\subsystem\language.dm"
What?

2017-05-12 14:11 UTC, Cyberboss commented on tgstation.dme
> -#include "code\modules\admin\adminmenu.dm"
What?

2017-05-12 14:11 UTC, Cyberboss commented on tgstation.dme
> -#include "code\modules\mob\living\simple_animal\hostile\jungle_mobs.dm"
What?

2017-05-12 14:11 UTC, Cyberboss commented on tgstation.dme
> -#include "code\modules\shuttle\elevator.dm"
What?

2017-05-12 16:15 UTC, bgobandit commented on tgstation.dme
> -#include "code\controllers\subsystem\language.dm"
I don't know how any of these came about. I pulled to master and based this off the new master branch, and I had to re-check a bunch of shit. wtf do I do, commit the DME?

2017-05-12 23:18 UTC, bgobandit commented on code/modules/power/supermatter/supermatter.dm
> +			to_chat(user, "<span class='notice'>You extract a sliver from [src]. [src] begins to react violently!</span>")
oops

2017-05-13 01:56 UTC, Anonmare commented
Does this have TK checks?

2017-05-13 02:16 UTC, bgobandit commented
not yet, that said, I don't know how to handle TK because, like, if you telekinetically grab supermatter, that isn't the same thing as coming into physical contact

2017-05-13 03:53 UTC, Cyberboss commented
We added a gib for tk sm touches recently

On May 12, 2017 10:16 PM, "bgobandit" <notifications@github.com> wrote:

not yet, that said, I don't know how to handle TK because, like, if you
telekinetically grab supermatter, that isn't the same thing as coming into
physical contact

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/27137#issuecomment-301219281>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AHyweiiyXbpPuCqeyWbNbhR1seNs7g4pks5r5RJigaJpZM4NXZdd>
.

2017-05-13 08:14 UTC, bgobandit commented
@Cyberboss can you address my comment about the includes please it is kind of critical for testing

2017-05-13 12:27 UTC, optimumtact commented on tgstation.dme
> -#include "code\controllers\subsystem\language.dm"
pull the DME from our latest master and replace yours

2017-05-14 05:35 UTC, Bawhoppen commented
make it so you have to use the special surgery tools to extract the core of the SM which beats like a heart BECAUSE IT'S ALIVE

2017-05-14 05:44 UTC, fludd12 commented
Actually the SM being a living organism with a pulsing crystal heart sounds awesome and metal as frick

2017-05-14 06:38 UTC, bgobandit commented
if someone wants to sprite that feel free

2017-05-16 01:28 UTC, bgobandit commented
btw this is not stale i'm just having problems testing it because my dream daemon is not registering my client, causing hella runtimes.

2017-05-16 16:34 UTC, Tacolizard commented on tgstation.dme
> -#include "code\controllers\subsystem\language.dm"
secret plot to remove lizard language confirmed?

2017-05-16 16:34 UTC, Tacolizard commented on tgstation.dme
> -#include "code\modules\admin\adminmenu.dm"
why?

2017-05-16 16:34 UTC, Tacolizard commented on tgstation.dme
> -#include "code\modules\mob\living\simple_animal\hostile\jungle_mobs.dm"
how?

2017-05-16 16:34 UTC, Tacolizard commented on tgstation.dme
> -#include "code\modules\shuttle\elevator.dm"
when?

2017-05-17 15:48 UTC, Jalleo commented
@bgobandit @Cyberboss maybe able to help.

2017-05-17 21:31 UTC, optimumtact commented
That's not lore friendly

2017-05-19 00:48 UTC, AdamElTablawy commented
It doesn't dust people when thrown, right?

2017-05-19 00:58 UTC, octareenroon91 commented
>It doesn't dust people when thrown, right?

That might be OK if it destroys itself and costs your greentext?

2017-05-21 19:26 UTC, lzimann commented
@bgobandit

2017-05-21 21:19 UTC, bgobandit commented
I've said like 50000 times I cannot test this because my client is runtiming and no one has suggested a cause or a solution

2017-05-24 16:17 UTC, Jalleo commented
I think its the cleanbot bug. Try updating your Repo and turn on testing. If that does not solve it talk to @Cyberboss or @MrStonedOne. Preferably on IRC.

2017-05-24 17:33 UTC, Cyberboss commented
Wouldn't be the cleanbot bug if he's not running linux

2017-05-24 18:51 UTC, MrStonedOne commented
I was able to connect just fine when i launched a test server.

Hmmmmmmmmm

2017-05-24 21:52 UTC, lzimann commented
Ping whenever you keep going with it.

2017-05-24 21:52 UTC, closed without merging