Gangs now start with 3 leaders
tgstation/tgstation pull request #27145
Opened 2017-05-11 17:14 UTC by Robustin

Promotion is a problematic mechanic. It allows people like me to immediately metagame the best players online and make sure they're my lieutenants. Within 5 minutes the game is already snowballing in my favor.

Meanwhile the inexperienced boss barely understands the implications of promoting and when they do promote its generally whoever happens to be standing in front of them, even if they're just as clueless as they are.

The result is that Gangs remain very snowbally. The best players get the best lieutenants and the best lieutenants then make sure to use points intelligently, recruit other key players, etc. 

Randomly assigning the leadership roles will still produced unbalanced outcomes, but less often than the current system. It makes it more likely that a robust gang boss doesn't get his two metabuddies as lieutenants or that the newbie boss isn't doomed from the moment the round starts. 

Also I'm streamlining the whole gang round to hopefully get to the fun stuff faster and resolve the conflict in a reasonable time period - the promotion phase only serves as a window for sec to crush the gangs in their infancy and start stockpiling more implants than there are gangsters on the station. 

There is still a designated "boss" and two lieutenants. The gang tool code should automatically prevent promotions once 3 leaders exist.

2017-05-11 17:15 UTC, ma44 commented
Security should be the 3rd leader

2017-05-11 17:19 UTC, Robustin commented
Security is almost certainly on its way out for Gang War, but I'm making these changes incrementally.

Sec or not, the leadership mechanic is a huge source of snowballing. If sec is gone I only see the problem getting worse since sec can't put the brakes on a gang that's ahead of the pack.

2017-05-11 17:50 UTC, GunHog commented
Seeing this from the same guy who make the argument from the other side in regards to Cult Master feels a bit odd.

2017-05-11 18:02 UTC, BeeSting12 commented
what gunhog said really. i like this mechanic and it should stay.

2017-05-11 18:59 UTC, Nabski89 commented
Gunhog, the difference here is that any cultist can get gear and convert people. 

Could the starting number of leaders scale with population. You've got a minimum mode size of 20, that leaves 1/3 of the crew starting off in a gang.

2017-05-11 19:02 UTC, bgobandit commented
>security out for gang war

how the hell do you propose to do this without metagaming

2017-05-11 19:29 UTC, XDTM commented
Lore wise it could be an experiment from NT to let people police themselves and it resulted in rampant mafia gangs instead of sec.

We don't have to keep all gamemodes secret.

2017-05-11 20:11 UTC, Robustin commented
@bgobandit 

My lore solution was that NT has removed security from certain stations as a cost-saving experiment. This decision has drawn vigorous criticism from the worker unions, which have resorted to criminal activity and forcible recruitment as a way to compel NT into providing proper security and simultaneously to give the unions an upper hand over their rivals at the next contract negotiations.

The players could immediately identify a Gang War round, but without security to rush implants and start randomly searching the impact is limited. The only tricky part is giving the loyalists something to do. I don't want everyone screaming to be converted at roundstart. I think that giving loyalists their own faction as "Vigilantes", which would basically function as a 4th gang with no leadership, recruitment, dominator, or identification - with the goal of simply stopping the other gangs and escaping.

2017-05-11 22:29 UTC, XDTM commented
I think that people wanting in on the protection racket would be fine, while others may stick to independence without the need for an incentive. Depends if people'd rather powergame or not be subordinates.

2017-05-11 22:56 UTC, kevinz000 commented
metagangs lmao

2017-05-12 11:47 UTC, KorPhaeron commented
@Robustin 

I was going to just make security straight up explode roundstart and say it was a syndicate attack or something

I'm kind of worried that without a security buffer to encourage stealth for the first few minutes the round will move way too fast though

2017-05-12 13:56 UTC, Cyberboss requested changes

2017-05-12 13:56 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +				title = "Boss"
I'd rewrite this for to be more like this:
```
var/list/available_ranks = list("Boss" = 1, "Lieutenant" = 2)
for(var/I in available_ranks)
    for(var/J in 1 to available_ranks[I])
        assign_rank_to_candidate(I)
```
And move the stuff inside to for to a new assign_rank_to_candidate proc

2017-05-12 15:38 UTC, Robustin commented
@KorPhaeron 

We saw gang war falter and ultimately fail under a system which probably produced the longest rounds of any mode. I'm moving incrementally now but with the sec change I hope that we can try swinging the pendulum completely in the other direction and have compact rounds that don't push past 30 minutes. 

To be clear I don't think this is how every mode should go, but when the theme of the mode is lots of guns and lots of antag conversion, I don't see a reason to stretch things out. 

I would like to have a vigilante faction that people can either volunteer for early in the round (ive got decent lore for this), or they all non-gangsters would be vigilantes by default. It basically functions as a decentralized gang who wants to stop the gangs and escape. They would get points only for cleaning tags (and having that territory stay clean when the next influence check goes through) and destroying contraband. 

Or we could just blow up security. But my biggest concern isn't fast rounds, there's always ways to slow them down again, but the loss of any tension between regular and gangster crew. Without some kind of vigilante mechanism that incentivizes people to resist the gangs, people might as well start volunteering for gang recruitment at roundstart.

2017-05-12 15:51 UTC, KorPhaeron commented
Something like

Minute 0: Security explodes

Minute 3: You've decided to take charge of the situation and form a gang. X and Y are your ganghead friends [syndicate company] has offered an uplink to help you take over, it will be delivered in five minutes.

Minute 8: You get your uplink and hopefully made up a plan in that time. 

Delays might be a bit long, just throwing random numbers out but it might stop the stetchkin rush we'd get otherwise.

2017-05-12 16:18 UTC, Robustin commented
I'll think about it. My biggest concern with that is that Minute 0 would immediately trigger mass-griefing/looting because there's no security AND people know they're probably going to get antag'd soon anyway. While any variation of "no sec" will inevitably see more department looting, giving gangsters something to do besides loot at roundstart (convert, tag, coordinate). 

I'm about to open a PR that will change the gang meta significantly anyway. I think with that change you will see more people thinking about the long-game because gang leaders see their income cut significantly (its decentralized). I don't see a serious risk of stechkin rushing becoming a common tactic.

2017-05-15 16:02 UTC, lzimann commented
@tgstation/commit-access

2017-05-15 20:52 UTC, optimumtact commented
@lzimann it's not like the gang mode is any good so you may as well feel free to merge any pr's that fuck with it and then see what happens

2017-05-15 20:54 UTC, KorPhaeron commented
Good PR

2017-05-15 23:11 UTC, merged