MultiZ WIP/Staging
tgstation/tgstation pull request #27189
Opened 2017-05-12 19:01 UTC by RemieRichards

Help me/Motivate me to finish this.
TODO:
-[ ] Fix Merge errors/reverts due to @coiax thinking it was a good idea to rename ```/Cleanable``` to ```/cleanable``` thus ruining git on windows OS.
-[ ] Pipes - @duncathan 
-[ ] Fix atmos neighbours calculation (run twice atm) - @duncathan / @MrStonedOne / @Cyberboss 
-[ ] Power
-[ ] Explosions
-[ ] Climbing
-[ ] Looking up/down as a mob

I'm still gonna work on this anymore just yet, but feel free to PR to this PR if you want to help.

2017-05-12 19:10 UTC, duncathan commented
ooo multiz pipes sounds fun

2017-05-12 19:10 UTC, Iamgoofball commented
why did you rename the folder back? the codebase standard is lowercase folder names

2017-05-12 19:12 UTC, RemieRichards commented
@Iamgoofball literally wouldn't commit otherwise, every commit attempt reported the files as being "staged in the index", which is git terms for "fucked", they're super-reverted, but just for now, it'll be fixed before merge (though someone else might have to PR that to this PR for me since git is unhappy)

2017-05-12 19:13 UTC, Iamgoofball commented
i love git

2017-05-12 19:18 UTC, GunHog commented
# HEAVY BREATHING

I want this. I want this now. YES YES YES YES YES YES ALL THE YES!! If I could help in any way, I would certainly like to try! A multi-Z station, even if PlanetStation were to fail, would be AMAZEBALLS!

2017-05-12 19:38 UTC, Cyberboss requested changes
I don't know if this will need special rules in the map loader. But if not...

Add a multiz_test.json in _maps like this
```
{
    "map_name": "MultiZ Station",
    "map_path": "map_files/debug",
    "map_file": "multiz_test.dmm",
    "minetype": "lavaland",
    "transition_config":
    {
        "MAIN_STATION": "UNAFFECTED"
    }
}
```

2017-05-12 19:38 UTC, Cyberboss commented on _maps/multiz_test.dm
> +#if !defined(MAP_FILE)
This entire file should be just #define FORCE_MAP "multiz_test.json"

2017-05-12 19:38 UTC, Cyberboss commented on code/controllers/subsystem/multiz.dm
> +	NEW_SS_GLOBAL(SSz)
Remove these two lines

2017-05-12 19:38 UTC, Cyberboss commented on code/controllers/subsystem/multiz.dm
> +/datum/subsystem/z_levels
Replace these three lines with SUBSYSTEM_DEF(z_levels)

2017-05-12 19:38 UTC, Cyberboss commented on code/game/objects/effects/decals/Cleanable/humans.dm
>  	..()
;(

2017-05-12 19:38 UTC, Cyberboss commented on code/game/objects/effects/decals/Cleanable/humans.dm
>  	..()
Seems you need to revert this entire file to upstream

2017-05-12 19:38 UTC, Cyberboss commented on code/game/objects/effects/decals/Cleanable/misc.dm
> -/obj/effect/decal/cleanable/ash/Initialize()
This one too

2017-05-12 19:38 UTC, Cyberboss commented on code/game/objects/effects/decals/Cleanable/robots.dm
>  	..()
Same

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/atmospherics/environmental/LINDA_system.dm
> +	for(var/direction in atmos_dirs)
Remove the cardinal line. GLOB.atmos_dirs

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/atmospherics/environmental/LINDA_system.dm
> +		for (var/checkDirection in atmos_dirs)
GLOB

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +		for(var/D in atmos_dirs)
GLOB

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/atmospherics/machinery/other/zvent.dm
> +		for (var/ddir in list(DOWN,UP))  //change this list if a fancier system of z-levels gets implemented //meow
Static list

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/atoms.dm
> +	var/atom/movable/zshadow/zshadow
move it to atoms.dm

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/atoms.dm
> +	SetupZShadow(mapload)
This is gonna add overhead to every atom, just call it from atoms.dm

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/atoms.dm
> +/turf/Initialize(mapload)
Same here

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/atoms.dm
> +	..()
Same

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/atoms.dm
> +	..()
The rest are fine, just these 3 are performance critical

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/turfs.dm
> +	..()
Another performance worry

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/z_helpers.dm
> +		L = list()
LAZYINITLIST(L)

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/z_helpers.dm
> +		L = list()
again

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/zshadows.dm
> +	..()
. = ..()

2017-05-12 19:38 UTC, Cyberboss commented on code/modules/multiz/zshadows.dm
> +	if(!QDELETED(owner)) //Nothing destroys these if their owner exists, they *ARE* their owner as far as we're concerned
check the `force` param

2017-05-12 19:39 UTC, RemieRichards commented on code/modules/multiz/atoms.dm
> +	SetupZShadow(mapload)
I swear I left a //TODO to move these.
this file is temporary.

2017-05-12 19:40 UTC, RemieRichards commented on code/modules/multiz/z_helpers.dm
> +		L = list()
old branch.

2017-05-12 19:42 UTC, RemieRichards commented on code/modules/multiz/zshadows.dm
> +	if(!QDELETED(owner)) //Nothing destroys these if their owner exists, they *ARE* their owner as far as we're concerned
Isn't ignoring force bad? that annoys me because I want to ignore force here.

2017-05-12 19:42 UTC, Cyberboss commented
For explosions, might just be as easy as reducing all power levels by 1 for every level up/down

2017-05-12 19:42 UTC, RemieRichards commented
@Cyberboss yes, it's something like that, as I said however, I've just not worked on it in a while (was ensuring the "core" was solid first)

2017-05-12 20:08 UTC, Cyberboss commented on code/modules/multiz/zshadows.dm
> +	if(!QDELETED(owner)) //Nothing destroys these if their owner exists, they *ARE* their owner as far as we're concerned
Almost nothing uses force atm, but we should support it in case we ever do decide we need it

2017-05-12 20:17 UTC, coiax commented
@RemieRichards maybe you could shout at me in IRC?

2017-05-12 20:52 UTC, duncathan commented on code/modules/atmospherics/machinery/other/zvent.dm
> +*/
By that I mean that cross-z connections should only happen between nodes. Making that work shouldn't be too difficult, but having a vent like this is unnecessary complexity for a redundant gain (pipe up connected to a vent is basically the same)

2017-05-13 10:41 UTC, RemieRichards commented on code/modules/atmospherics/machinery/other/zvent.dm
> +*/
sure I guess, it just seemed cruel to kill it when it survived, semi-working, for such a long time.
rip zvent.

2017-05-13 12:14 UTC, optimumtact commented
staged in the index just means the files have been git added, but not yet committed, there's absolutely no reason to revert that change

2017-05-13 12:19 UTC, RemieRichards commented
I didn't revert it, technically.
I renamed my Cleanable folder to cleanable (because it DIDNT come in the merge commit), and committed that, so they never got updated because they're not the same files (if you look at the cleanable folder's history for example, as far as git is concerned, it only has 2 commits, the rename and MrPerson's mutable appearance changes)

It was quite literally the only thing I could do to commit it, and as I have said, it will be sorted before merge time.

2017-05-13 12:25 UTC, optimumtact commented
ok

2017-05-13 13:11 UTC, RemieRichards commented on code/controllers/subsystem/air.dm
> +	//Recalculated, for Multi-Z (In an ideal world I'd move setup_allturfs() here
this got moved during the merge, woops.
explains the comment.

2017-05-13 13:11 UTC, Razharas commented
@RemieRichards please return to coderbus its much easier to discuss things there

2017-05-13 13:14 UTC, RemieRichards commented on code/modules/atmospherics/machinery/other/zvent.dm
> +		for (var/ddir in list(DOWN,UP))  //change this list if a fancier system of z-levels gets implemented //meow
No point, dunc wants the file murdered.

2017-05-13 13:19 UTC, duncathan commented on code/modules/atmospherics/machinery/other/zvent.dm
> +*/
I do appreciate the respect you had for this poor piece of oldmos

2017-05-13 13:19 UTC, RemieRichards commented on code/modules/atmospherics/machinery/other/zvent.dm
> +*/
;_;7

2017-05-13 13:21 UTC, duncathan commented on code/__DEFINES/atmospherics.dm
> +#define CANATMOSPASS(A, O) ( A.CanAtmosPass == ATMOS_PASS_PROC ? A.CanAtmosPass(O) : ( A.CanAtmosPass == ATMOS_PASS_DENSITY ? !A.density : A.CanAtmosPass ) )#define CANATMOSPASS(A, O) ( A.CanAtmosPas
What's up with this

2017-05-13 13:22 UTC, RemieRichards commented on code/__DEFINES/atmospherics.dm
> +#define CANATMOSPASS(A, O) ( A.CanAtmosPass == ATMOS_PASS_PROC ? A.CanAtmosPass(O) : ( A.CanAtmosPass == ATMOS_PASS_DENSITY ? !A.density : A.CanAtmosPass ) )#define CANATMOSPASS(A, O) ( A.CanAtmosPas
fixed, originally GLOB.atmos_dirs was ```#define ATMOS_DIRS ...```, but that would have meant the list operation happened every time (not good for hot code like atmos), so I swapped it to glob.

It was just for lazy testing, THIS exact line is a result of fucking that up in the merge is all.

2017-05-13 14:02 UTC, RemieRichards commented on code/modules/multiz/atoms.dm
> +	SetupZShadow(mapload)
I did actually, line 40.

2017-05-13 14:02 UTC, RemieRichards commented on code/modules/multiz/turfs.dm
> +	var/z_open = FALSE //are we see the Z below us through this turf? (true/false)
am gud att engrish

2017-05-13 14:12 UTC, RemieRichards commented
Right, cleanup is done.
Fixing, Features, Improvements can begin (eg: @duncathan zpipes)

2017-05-14 17:13 UTC, BeeSting12 commented
@RemieRichards 
I'm working on a map for this right now which is loosely based on baystation's torch. I should be okay making the different zlevels and I can connect them up later right?

2017-05-14 17:14 UTC, RemieRichards commented
yes, though if you put a "zopen" turf on a zlevel, it will automatically connect it's Z level with the one below, which if you're mapping a multiz station you're likely to use zopens for like, balconies and things.

2017-05-14 23:45 UTC, vcordie commented
this is an uninformed and wrong opinion, even though there is no such thing as a wrong opinion. In other words: fuck you oranges

2017-05-15 08:42 UTC, coiax commented
Bay's multiz explosion code is not very complex, if you want to look at that.

2017-05-15 08:44 UTC, RemieRichards commented
No need, I already have it planned (And I think Razharas is tackling it, I know he's been messing around with it atleast)

2017-05-15 12:04 UTC, Razharas commented
For now i only pr the 3d vines
Check em //

2017-05-15 15:05 UTC, RemieRichards commented on code/controllers/subsystem/air.dm
> +	//Recalculated, for Multi-Z (In an ideal world I'd move setup_allturfs() here
Was originally in ```StopLoadingMap()```

2017-05-15 15:09 UTC, RemieRichards commented on code/modules/multiz/atoms.dm
> +		if(GetAboveConnectedTurf(src))
This is meant to be ```GetZOpenAbove(src)``` (so that Zshadows lazy-create (the creation of a hole above them is already covered))

2017-05-15 20:49 UTC, BeeSting12 commented
@RemieRichards 
Gravity?

2017-05-15 20:52 UTC, Razharas commented
https://github.com/RemieRichards/-tg-station/pull/19

2017-05-28 09:02 UTC, Ausops commented
*motivates remie

2017-05-29 21:36 UTC, lzimann commented
Just reopen when this keeps going

2017-05-29 21:36 UTC, closed without merging

2017-05-30 16:03 UTC, duncathan commented
maybe we should make this a branch on the main repo

2017-05-30 16:04 UTC, lzimann commented
That also works.

2017-05-30 16:09 UTC, GunHog commented
That is a good idea, this is a long project and seeing it closed could be discouraging to the people working on it!

2017-05-30 16:11 UTC, Cyberboss commented
You can also PR a branch

On May 30, 2017 12:09 PM, "GunHog" <notifications@github.com> wrote:

> That is a good idea, this is a long project and seeing it closed could be
> discouraging to the people working on it!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/27189#issuecomment-304928232>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywesKcmCQLrF4OT7M8OYKTQnBgduyKks5r_D87gaJpZM4NZqk6>
> .
>

2017-05-30 16:13 UTC, GunHog commented
I am aware.