Job assign at roundstart now favors empty positions first
tgstation/tgstation pull request #27197
Opened 2017-05-12 20:48 UTC by Crexfu

:cl: 
None
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

Currently in low pop rounds multiple players can be put into the same job leaving other jobs empty that they would otherwise be happy to roll. This change seeks to improve the user experiance in these situations  but better distributing players. It may be worth having a preference for wanting to be filled into empty roles  first so that the social butterflies can opt out and more likely be grouped with others in low pop rounds.

2017-05-12 20:50 UTC, Jalleo commented
This may need testing to make sure it works properly and does not unbalance things like Revolution rounds.

2017-05-12 21:03 UTC, Cyberboss requested changes

2017-05-12 21:03 UTC, Cyberboss commented on code/controllers/subsystem/job.dm
> +							break;
no need for semicolons outside defines

2017-05-12 21:03 UTC, lzimann commented on code/controllers/subsystem/job.dm
> +						if (job.current_positions == 0)
just `!job.current_positions` will do

2017-05-12 21:03 UTC, lzimann commented on code/controllers/subsystem/job.dm
> +							break;
no commas, please

2017-05-12 21:03 UTC, Cyberboss commented
Does this account for selection priority? because that should come first

2017-05-12 21:03 UTC, Cyberboss commented on code/controllers/subsystem/job.dm
> +							break;
>commas

2017-05-12 21:04 UTC, lzimann commented on code/controllers/subsystem/job.dm
> +							break;
\>english words

2017-05-12 21:04 UTC, lzimann commented
IIRC this is in the select a random job part. It should not throw off any job priority.

2017-05-12 22:56 UTC, Crexfu commented
yes it is within the priority loop from high to low

2017-05-13 20:02 UTC, Crexfu commented on code/controllers/subsystem/job.dm
> +							break;
corrected

2017-05-13 20:02 UTC, Crexfu commented on code/controllers/subsystem/job.dm
> +						if (job.current_positions == 0)
done

2017-05-14 12:34 UTC, merged

2017-05-15 13:42 UTC, coiax commented
This appears to be fucking with people's job priorities big time.

2017-05-15 13:48 UTC, francinum commented
Absolutely fucking broken.