Gives gangs new surplus rifle, mounted machine gun, and more
tgstation/tgstation pull request #27195
Opened 2017-05-12 20:40 UTC by Robustin

We're pretty overdue for a gun that isn't design to kill you in under 2 seconds. The new surplus rifle (8 points) requires two hands to fire, is very bulky, and it take a few seconds between each shot. Its a cheap way for people to defend a gang's turf without giving them a murderbone tool. Uses 10mm rounds (30 damage a shot). 

The mounted machine gun (50 points) is something I've had sitting around. I wanted to make gang gunfights a little more tactical which is why I added stuff like the sniper rifle. The mounted machine gun is something you buckle into and makes both hands unusable while using. It fires a volley of 10 rounds of 20 damage bullets with moderate spread over 2 seconds, then requires 2.5 seconds to "cool off" before another volley can be fired. The machine gun never runs out of ammo and extends sight range by 3, so its an excellent suppression weapon, but its spread and low damage per bullet means you aren't going to be blowing people away either. Its stationary status mean that the gun is almost useless in open spaces (if you can flank the gunner after their initial volley you have almost 5 seconds to put them down before they can fire again) or any position where someone can fire on you from cover.

I'm also giving gangs access to a sawn-off improvised shotgun (6 points) that fires only one shell at a time.

This PR also adds my previously added gear to the item list I overlooked, which should allow them to be purchased now. 

🆑 Robustin
add: The new surplus rifle is a semi-automatic rifle that is very bulky and has a very low rate of fire. Gangs can buy this gun for just 8 influence.
add: The machine gun turret unleashes a volley of bullets with an extended view range. It does not run out of ammo, but a significant delay between shots and its stationary nature leaves the gunner vulnerable to flanking and return fire. It will cost gangs 50 influence. 
add: The sawn-off improvised shotgun is now available to gangs for 6 influence. With buckshot shells being easy to produce or purchase, this gun gives the most "bang for your buck" but its single-shell capacity will leave you vulnerable during a pitched gunfight. 
/🆑

2017-05-12 20:42 UTC, coiax commented
> doesn't run out of ammo

Oh boy.

2017-05-12 20:46 UTC, FantasticFwoosh commented
Imminent wall of death coming when  people build a solid wall of these, it'll just be 3 gangs sitting on different ends of the station in a stalemate because they've built a tower defence course.

> I can atleast count on 1 shitter camping the arrivals shuttle with it.

2017-05-12 20:51 UTC, ma44 commented
Throw a grenade or gas, something like clf3 + smoke is most likely to kill anything that decides to stand still.

2017-05-12 20:51 UTC, Robustin commented
I believe its underpowered right now but you guys can prove me wrong.

MG = 50TC
Sniper rifle = 40TC

Since the gunner can't manipulate the cooldown, you can wait between volleys and easily dunk the gunner with any ranged weapons. The gunner can't turn the gun after it starts firing either so it someone is blitzing your position and runs around your cone of fire, you pretty much have to abandon ship.

Also anyone who gets rid of the gunner can easily steal these.

2017-05-12 20:56 UTC, Repukan commented
>Adding guns when RnD can just print them or cargo can order
>Adding stationary defenses when toxins exist

2017-05-12 21:00 UTC, Iamgoofball commented
>tachanka turret

when do gangs get fuze charges too?

2017-05-12 21:01 UTC, Cyberboss requested changes

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +		buckled_mob.pixel_y = 0
Is this not set by the base proc?

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +			buckled_mob.client.change_view(world.view)
Use reset_perspective

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +	M.loc = get_turf(src)
forceMove

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +		user.client.change_view(view_range)
I swear theres a proc for this

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +			E.layer = 3.9
Use the define for whatever layer 4 is and the +/- 0.1 to it

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +		playsound(src.loc, 'sound/weapons/sear.ogg', 100, 1)
remove .loc

2017-05-12 21:01 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +		playsound(src.loc, 'sound/weapons/Gunshot_smg.ogg', 50, 1)
remove .loc

2017-05-12 21:10 UTC, Robustin commented
@Repukan 

Those things will be changed very soon - and even then its a stupid argument to say "well we shouldn't give people guns because cargo can get cheap guns" when the whole idea is to not make cargo the exclusive gun store for the station.

2017-05-12 21:48 UTC, FantasticFwoosh commented
Its probably put down to the factor that ballistic guns are generally more reliable & damaging (everyone grabs combat shotties probably more in favour than grabbing laser rifles)

Gang mode guns can be devastating en-mass because of bullets, lasers run out & and need to recharge while guns just keep going with ammo to spare. And with gang points in the tank to just buy more/virtually unlimited ammo its strong.

2017-05-12 21:54 UTC, Robustin commented
Gang is losing access to the armory and cargo guns, they need something to fill the gap and I'm adding guns that aren't just mass-murder devices. The sniper, sawn-off, surplus, MG, etc. are all really bad for just running down the hall and killing anything that moves.

This helps add depth so that defenses aren't just wallspam and uzis.

2017-05-13 12:31 UTC, Ausops commented
if we allow gang we can try this

2017-05-13 17:36 UTC, kevinz000 commented
why do i get yelled at for gunbloat when robustin gets all the fun ;-;

2017-05-13 17:59 UTC, Bawhoppen commented
gunbloat isn't a real thing don't listen to those people

2017-05-13 18:10 UTC, Robustin commented
Nothing is gunbloat if it fills a significant role in ranged combat that isn't filled by anything else.

Low DPS non-stunning ranged weapon? We literally have none. 

Weapon focused on suppressing chokepoints and enemy groups instead of outright killing them? Zip.

2017-05-14 21:20 UTC, BeeSting12 commented
all hail lord tachanka

2017-05-15 16:03 UTC, lzimann commented
@tgstation/commit-access

2017-05-15 16:41 UTC, Steelpoint commented
Seems fair, gang get access to firearms but they are not OP monster weapons that have the most invisible gun sprite in the game, can hide in your backpack, and kill someone in under two seconds.

I'm also interested in the idea of cutting off gangs access to cargo and armoury guns, look forward to seeing Robustin's further work on gang.

2017-05-15 19:05 UTC, Robustin commented on code/game/machinery/porta_turret/portable_turret.dm
> +			buckled_mob.client.change_view(world.view)
Didn't remove zoom, changing it back

2017-05-16 00:12 UTC, Robustin commented
I overhauled the machine gun to be a lot more responsive than just "vomits bullets at a location for a couple seconds then cools down".

Thanks to being egged on by a certain maintainer I have made the machine gun (and its new admin only counterpart) into autoclicker weapons with a behavior revamp. What does this mean? The weapon will now begin firing upon you depressing the mouse button and it will track your mouse's movement as you depress the mouse. As long as the gun is firing it will constantly be updating to your mouse's location. The weapon's spread prevents this from being too OP. I also reduced the gun's integrity to 100 from the default 200 so that it can more easily be dispatched by hostile gunfire. While the gunfire window is now doubled to around 4 seconds, you also now have a 5 second window to attack the gun while it cools off.

2017-05-16 16:30 UTC, Tacolizard commented
>Low DPS non-stunning ranged weapon? We literally have none.

hmm my pipe pistol would've filled that niche huh imagine that

2017-05-16 16:39 UTC, Robustin commented
I think your pipe pistol was doing fine but coding and drama derailed it.

2017-05-16 21:32 UTC, Robustin commented
How the fuck do I have 2 turret icon conflicts in 2 days.

2017-05-16 21:44 UTC, Dorsisdwarf commented
because i changed turrets.dmi twice in two days

2017-05-17 15:27 UTC, ChangelingRain commented on code/game/gamemodes/gang/gang_items.dm
> +	spawn_msg = "<span class='notice'>The mounted machine gun features enhanced responsiveness. Hold down on the trigger while firing to control where you're shooting."
</span>

2017-05-18 08:45 UTC, kevinz000 commented
wtf i like robustin now?

2017-05-18 10:21 UTC, Steelpoint commented
Having a lot of low damage, low rate of fire, weapons would make combat a more drawn out affair which I think would be of benefit.

It would also make the Uzi (if you decide to keep it) far more valuable but also something rare to see. Considering one Uzi is worth six rifles you can argue that six guys with crappy guns is better than one guy with a good gun.

2017-05-18 15:14 UTC, Robustin commented
@Steelpoint I agree, I'm excited about the opportunity to have a mode that doesn't have much in the way of reliable stuns (the biggest thing I'm worried about once sec is gone is the power of telescopic batons). As far as gun balance I agree that encouraging "ambush" gameplay where the focus is destroying your opponent before they can react is bad, but its not the Uzi that I'm primarily worried about.

I have mixed feelings about the Uzi. I think its the best all-around gun for the Gang but I don't think its that strong. 

Its 32 rounds with a 2-shot burst that does 20 damage per shot. The gun costs 60 influence and each mag costs 40 influence.

Meanwhile the stechkin, I increased the cost to 30 from 25 but that's still 50% of the uzi's cost and it does 30 damage per shot. I fear the stechkin becoming everyone's default weapon and I think the DPS is high enough to allow you to flatten most people before they realize you've got a couple black pixels in your hand. I'm considering increasing the ballistic armor on gang outfits but I'm also thinking about changing the stechkin to a "Gang variant" that is has a more noticeable icon, or adding more ballistic armor to the gang outfit so that gunfights aren't about "kill your opponent in under a sec".

I'm leaning toward the latter. I don't think a guy with an Uzi could even hope to take on 6 guys with surplus rifles. I would honestly feel comfortable taking on an Uzi user solo with a surplus if I could keep my distance and take cover between shots. If the game proves otherwise then sure I'll increase the price more.

2017-05-18 15:50 UTC, Steelpoint commented
I do think the Surplus Rifle is a strong enough weapon, it won't hold up long against guys with Lasers and Riot Shields but since sec is MIA in this mode that is no issue.

If anything I suggest just removing the UZI or allowing one to be in existence at any time for each gang.

2017-05-18 16:31 UTC, Steelpoint commented
Perhaps look to changing the Sketchin to a different name but make its MOB sprite very large and obvious.

2017-05-18 17:17 UTC, Steelpoint commented
Now that I think about it, I think we should remove the higher tier weapons above the surplus rifle. Keep it to the surplus rifle, one shell shotgun and the machine gun. 

The reason I say this is due to your other proposed change of making influence accumulate on an individual basis, not a group basis. If I accumulate influence individually I'm more incentivised to save my influence to buy a Sketchin or a UZI.

2017-05-18 21:59 UTC, Robustin commented
Since Gang War is entering a very experimental state I'd rather keep the list as open as possible and then shave it down based on real experiences and/or data than start small and then fight people on hypotheticals.

2017-05-19 00:45 UTC, AdamElTablawy commented
Could you not theoretically just place a bunch of these in a hallway/around a corner and make a wall of death? 

Remember that shotgun buckshot had 'spread' too but it was pretty good at hurting like shit even at long range, and that's only a few pellets that do low damage.

This is a 20-bullet stream. While the shotgun is portable and not destroyable like this is, spread means little in this sort of scenario.

2017-05-19 01:15 UTC, Bawhoppen commented
@Adam some shotgun pellets always go forwards, the spread for shotguns isn't that random

2017-05-19 01:17 UTC, Bawhoppen commented
Also sorry for pinging you random guy

2017-05-19 02:58 UTC, Robustin commented
If you place them anywhere obvious someone can just return fire down the hall. The guns only have 100hp (most machines have 200) so you cant really afford to put them somewhere in the open. I would imagine that if 4 stechkin rounds trash your 50 influence machine gun, that you would avoid making "walls of death" in the future.

But who knows. My experience is that standing still is a death sentence in this game, a single cooked grenade could killed 3 gunners and 3 guns. Also with the gang uniform each MG bullet does ~13 damage, each tile will get roughly 33% of the gunfire from the MG, so any given tile is looking at ~40 damage per second from a machine gun at range - which is still less than someone just plugging you with a stechkin.

2017-05-19 11:23 UTC, lzimann commented
@tgstation/commit-access This is just adding, once again, more traitor gear to gang. I'll close this in 24h if no one merges.

2017-05-19 11:29 UTC, Steelpoint commented
None of this is traitor gear, its all unique and all worse than the standard of gear Traitors get.

2017-05-19 11:31 UTC, lzimann commented
Doesn't matter, I still dislike.

2017-05-19 11:43 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +			buckled_mob.client.change_view(world.view)
```reset_perspective()``` is the wrong proc for this, that's to do with client eye positioning.
```change_view()``` is correct.

2017-05-19 11:44 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +	layer = 4.2
Defines please, for example, I'm sure 4 is like, ```OBJ_LAYER``` or something, so you'd do ```layer = OBJ_LAYER + 0.2``` so people are aware it's "0.2 layers above the Object layer"

2017-05-19 11:45 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +	layer = 4.1
same again

2017-05-19 11:46 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +			E.layer = BELOW_MOB_LAYER
See, you did it here!

2017-05-19 11:48 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/machinery/manned_turret/proc/fire_helper(var/target_turf)
no ```var/``` in proc arguments

2017-05-19 11:48 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +	var/target_turf
typecast this as a turf

2017-05-19 11:51 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +	turret = MT
Should delete itself if it doesn't get a turret (eg: admin spawning these abstract-dontspawnpls-hand objects)

2017-05-19 11:51 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/item/gun_control/New(var/obj/machinery/manned_turret/MT)
no ```var/``` in proc arguments

check the rest of your PR.

2017-05-19 11:51 UTC, RemieRichards commented on code/game/machinery/porta_turret/portable_turret.dm
> +		addtimer(CALLBACK(src, /obj/machinery/manned_turret/.proc/fire_helper, target_turf), i*rate_of_fire)
why do you pass ```target_turf``` as an arg? it's already on the gun...

2017-05-19 11:56 UTC, RemieRichards commented
I want my review addressed, and I'd like to see this tested.

2017-05-19 14:30 UTC, Robustin commented
I love the dialogue between Steelpoint and LeoZ, classic argument with LeoZ.

"I dont like because [strawman]"
"But there's no [strawman]"
"Yea I still dont like it"

2017-05-19 14:33 UTC, Robustin commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/item/gun_control/New(var/obj/machinery/manned_turret/MT)
been doing this as a precaution since I've seen it all over, thanks for clarifying

2017-05-19 14:35 UTC, Robustin commented on code/game/machinery/porta_turret/portable_turret.dm
> +		addtimer(CALLBACK(src, /obj/machinery/manned_turret/.proc/fire_helper, target_turf), i*rate_of_fire)
I think this proc used to be in the controls and didn't have the var or something

2017-05-19 14:37 UTC, lzimann commented
At least it's not an essay telling the story of your life that no one bothers to read.

2017-05-19 22:55 UTC, Robustin commented
Raviolio Ravioli give me the mergioli

2017-05-21 22:25 UTC, merged