Adds Bonfire Grills
tgstation/tgstation pull request #27250
Opened 2017-05-14 06:37 UTC by fludd12

Using metal rods on a bonfire will now give you the option of adding a stake or a grill. Adding a grill lets you cook things on the bonfire, but not with the same level of control as a microwave.

:cl: fludd12
add: You can now add grills to a bonfire, letting you cook things on top of them.
/:cl:

2017-05-14 08:24 UTC, FantasticFwoosh commented
Sounds good.

2017-05-14 10:13 UTC, Grazyn commented
We don't have marshmallows though. I don't care if it's codersprites, someone please add them

2017-05-14 11:00 UTC, FantasticFwoosh commented
Does this heat up to a 1000c? because that's the amount of heat you need to cook a goliath steak and also the max (the ability to put reagent holding beakers onto on it too would be nice) heat that the microwave cooks at.

Might make a arguement to remove the bonfires O2 restrictions as well as remove throwing goliath steaks onto lava to cook in favour of having a BBQ.

2017-05-14 18:25 UTC, Kromgar commented
Wait.... how do you light on fire if there is no oxygen on lavaland?

2017-05-14 19:02 UTC, Jazaen commented
Space magic. People can be caught on fire on lavaland.

2017-05-14 20:46 UTC, FantasticFwoosh commented
See in reference  `/obj/structure/bonfire/proc/CheckOxygen()` at towercap.dm where the bonfire code is kept, there were references to make everything else that burns on lavaland respect those rules too (torches, cigarettes etc), ill find the PR if i can.

2017-05-14 21:28 UTC, fludd12 commented
To answer the questions, I was thinking about making it able to cook goliath steaks, but decided that it would make sense for something that slow-cooks to not be able to accomplish the same effect as a quick dip in lava.
As for how it cooks, it calls each `obj/item`'s `microwave_act` on a random timer, so while it can cook things, it can also _over_cook things if you aren't careful.
Mostly, I wanted this so that podpeople can prepare banquets for when they finally meet their masters.

2017-05-15 16:21 UTC, lzimann requested changes

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +		if(choice == "Stake")
Use a switch

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +			can_buckle = 1
`TRUE`

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +			buckle_requires_restraints = 1
`TRUE`

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +			grill = 1
Repeating grill here

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +				return 1
`TRUE`

2017-05-15 16:21 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +	for(var/obj/item/O in current_location)
Just include this 2nd loop in the first with a typecheck + typecasting. 
```
else if(istype(A, /obj/item) && prob(20))
    var/obj/item/O = A
    O.microwave_act()
```

2017-05-15 16:22 UTC, lzimann commented on code/modules/hydroponics/grown/towercap.dm
> +			if(user.drop_item())
@Cyberboss What is the proper inventory proc for this again?

2017-05-15 16:37 UTC, Cyberboss requested changes

2017-05-15 16:37 UTC, Cyberboss commented on code/modules/hydroponics/grown/towercap.dm
> +			to_chat(user, "<span class='italics'>You add a rod to [src].")
\the [src]

2017-05-15 16:37 UTC, Cyberboss commented on code/modules/hydroponics/grown/towercap.dm
> +			if(user.drop_item())
use user.temporarilyRemoveItemFromInventory(W)

2017-05-15 16:37 UTC, Cyberboss commented on code/modules/hydroponics/grown/towercap.dm
> +				W.Move(get_turf(src))
W.forceMove(get_turf(src))

2017-05-15 22:20 UTC, fludd12 commented
Heh, is it obvious that I salvaged a lot of this code from other sources? Thanks for all the help.

2017-05-15 22:42 UTC, fludd12 commented
Alright, that should do it, unless anyone else has any items of note?

2017-05-16 14:26 UTC, lzimann approved these changes

2017-05-16 14:27 UTC, merged