SM speaks on engineering channel, now with 100% less freeze
tgstation/tgstation pull request #27261
Opened 2017-05-14 16:22 UTC by Qbopper

:cl: Qbopper
tweak: The supermatter crystal now sends its warning messages to the engineering channel. (if it's in critical condition the message will be sent to both common and engineering channels)
/:cl:

TL;DR: Supermatter messages now go to the engineering channel. Emergency alert messages will still broadcast to general radio.

A little old, but: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=10445#p275368

I PR'd this during the freeze like a dope, here it is again, I hope it didn't break again. A few people said to make the messages transmit to general around 40% instability or so, but others say this is fine, so I'll PR this as is and if people really want lower %s on general chat I can look into doing that

2017-05-14 16:24 UTC, obscolene commented
>no engineers >someone sabotages the SM >70% instability before anyone knows

2017-05-14 16:24 UTC, Cyberboss requested changes

2017-05-14 16:24 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +				SPEAK("[emergency_alert] Instability: [stability]%", radio_channel)
If it's being broadcast on common here, no need to also say it on engineering

2017-05-14 16:25 UTC, Qbopper commented
that's a valid complaint, actually, but I'm not sure if it's possible to, say, send it to general if there's no engineers

also AI/captain can see engineering and warn people? I dunno, if there's no engineers and someone sabotages it then you're kinda fucked anyways

2017-05-14 16:25 UTC, Qbopper commented on code/modules/power/supermatter/supermatter.dm
> +				SPEAK("[emergency_alert] Instability: [stability]%", radio_channel)
I know - I wasn't sure if I wanted to do it that way or not. It's easy to miss shit in the common channel sometimes so I figured the redundant message would be helpful for engineers, but it's nbd either way

2017-05-14 16:26 UTC, Qbopper commented
oh my fucking god i broke it again

2017-05-14 16:39 UTC, kevinz000 commented
Not really as if I get notified I'll run to fix it instead of leaving my fate to the engineers

2017-05-14 16:41 UTC, Qbopper commented
I don't see why encouraging people to do their job is a bad thing

2017-05-14 18:04 UTC, Aloraydrel commented
I always had this on my mind why this wasn't on the engineering.

2017-05-14 18:14 UTC, Qbopper commented
well I managed to fuck something up and the code that worked previously now does not, so give me a minute to find the problem here (it's not sending the message to common anymore)

2017-05-14 18:40 UTC, Qbopper commented
fixed compile issues (on my end) and it actually works as intended now

2017-05-15 03:24 UTC, Penguaro commented
Oh the number of engineers who will ignore this initially thinking it's just Poly...

2017-05-15 03:50 UTC, kevinz000 commented
engineers are encouraged to do their job by the alert on common telling everyone they've been fucking up
if it's just on engineering, what happens if the engineers ignore it?
no one will know until it's too late, ruining any kind of crew response to it that isn't "lets hope the engineers aren't traitors or garbage"
i'm probably exaggerating here but this just seems like it'll make engine delaminations more stealthy..

2017-05-15 03:51 UTC, Cyberboss approved these changes

2017-05-15 16:10 UTC, merged