4th Attempt at 60% shuttle recall gang murderbone thing
tgstation/tgstation pull request #27414
Opened 2017-05-19 04:15 UTC by Robustin

Still very important, still a victim of Github memes.

Tried to push to Militairies version but it had like a million commits so fuck that

2017-05-19 05:08 UTC, Steelpoint commented
While its been said to death but I think this is a good way to end bad stalemates that can occur in Gang War.

2017-05-19 07:42 UTC, kevinz000 commented
how many hours

2017-05-19 14:20 UTC, Robustin commented
1.50 hours of testing

2017-05-19 16:01 UTC, Cyberboss requested changes

2017-05-19 16:01 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	if((alive < LAZYLEN(GLOB.joined_player_list) * 0.4) && (SSshuttle.emergency.timeLeft(1) < (SSshuttle.emergencyCallTime * 0.4)))
no need for lazylen, just .len

2017-05-19 16:01 UTC, Cyberboss commented on code/modules/shuttle/emergency.dm
> +	if(SSshuttle.emergencyNoRecall == TRUE)
no == TRUE

2017-05-19 16:01 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +/datum/game_mode/proc/shuttle_check()
Nothing is calling this proc...

2017-05-19 17:46 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +/datum/game_mode/proc/shuttle_check()
oh something call its but because of fucking commit memes I have to rewrite the line

2017-05-19 17:47 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +	if((alive < LAZYLEN(GLOB.joined_player_list) * 0.4) && (SSshuttle.emergency.timeLeft(1) < (SSshuttle.emergencyCallTime * 0.4)))
Maintainers have asked me to replace .len with LAZYLEN in the past

2017-05-19 17:47 UTC, Robustin commented on code/modules/shuttle/emergency.dm
> +	if(SSshuttle.emergencyNoRecall == TRUE)
?

2017-05-19 17:56 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	if((alive < LAZYLEN(GLOB.joined_player_list) * 0.4) && (SSshuttle.emergency.timeLeft(1) < (SSshuttle.emergencyCallTime * 0.4)))
You use LAZYLEN when you're not sure if the list exists or not. Otherwise use list.len. joined_player_list always exists

2017-05-21 14:36 UTC, Uqualm commented
I predict you losers incorporating this in every single game mode.

2017-05-22 17:04 UTC, Robustin commented
@Jordie0608 

This PR was made to specifically address the concerns you had in #27228 but I couldn't push to his branch without a commit flood.

2017-05-24 04:39 UTC, Robustin commented
Joooordie.

Or anyone else really.

This is an important milestone in resolving some of the worst metagame for Gang War.

2017-05-25 00:20 UTC, merged