Engineers can get a vaporizing breath mask to cure Hallucinations (and also ports vapes to Initialize())
tgstation/tgstation pull request #27449
Opened 2017-05-20 05:28 UTC by Expletive

:cl: 
add: The gas masks in the Engineer's Lockers have been replaced with Vaporizing Breath Masks. They come loaded with Synaptizine for when you stare at the engine without wearing your mesons (you idiot).
/:cl:

I wanted to make these, and I'm giving them to engineering because MSO told me to, under the reasoning that "they don't get anything". Also, I made sprites. This time, the sprites I made only suck a little bit, because I based them on an existing sprite.

2017-05-20 05:31 UTC, swindly commented on config/admins.txt
> +Expletives = Game Master
k

2017-05-20 05:43 UTC, kevinz000 commented
why give them a crutch for it? also synap is an anti stun chemical you goofnerd

2017-05-20 05:56 UTC, francinum commented
@kevinz000 No. it's both.

2017-05-20 13:14 UTC, coiax commented on code/modules/clothing/masks/breath.dm
> +	name = "Vaporizing Breath Mask"
All lowercase.

2017-05-20 13:29 UTC, octareenroon91 commented on code/modules/clothing/masks/breath.dm
> +	if(istype(O, /obj/item/weapon/reagent_containers) && (O.container_type & OPENCONTAINER))
Maybe get the mask back to processing here in case it has been empty, so it's very safe to refill in space.

2017-05-20 13:58 UTC, octareenroon91 commented on code/modules/clothing/masks/breath.dm
> +	if(istype(O, /obj/item/weapon/reagent_containers) && (O.container_type & OPENCONTAINER))
If allowable, I guess that could mean re-calling `equipped()` against the slot it's currently on.

2017-05-20 15:35 UTC, Really-Good-Soda-Flavor commented
Dumb

2017-05-20 16:44 UTC, Repukan commented
Hugbox

2017-05-20 16:52 UTC, Expletive commented
Okay, since everyone seems to think giving these to engineers is a bad idea, who should get them instead?

2017-05-20 16:53 UTC, Repukan commented
Big red letters roundstart that say wear mesons you fucknugget

2017-05-20 17:22 UTC, Cyberboss requested changes

2017-05-20 17:22 UTC, Cyberboss commented on code/game/objects/items/weapons/cigs_lighters.dm
> +		to_chat(user, "<span class='notice'>You empty [src] of all reagents.</span>")
\the

2017-05-20 17:22 UTC, Cyberboss commented on code/game/objects/items/weapons/cigs_lighters.dm
> +			to_chat(user, "<span class='notice'>You start inhaling from the [name].</span>")
\the [src]

2017-05-20 17:22 UTC, Cyberboss commented on code/game/objects/items/weapons/cigs_lighters.dm
> +					equipped(user,slot_wear_mask)
Don't call equipped, refactor what's in equipped into a common proc and then call that instead

2017-05-20 17:22 UTC, Cyberboss commented on code/game/objects/items/weapons/cigs_lighters.dm
> +	var/param_color = null
Remove the `= null`

2017-05-20 17:22 UTC, Cyberboss commented on config/admins.txt
> +Expletives = Game Master
He's taking the fruit's spot, a bold strategy cotton...

2017-05-20 17:37 UTC, BeeSting12 commented
Noone should get them. Engineers need to git gud.

2017-05-20 17:51 UTC, QualityVan commented on code/game/objects/items/weapons/cigs_lighters.dm
> +					itstimetovape()
Would it be better to make toggling the mask an action?

2017-05-20 17:59 UTC, Cyberboss requested changes

2017-05-20 17:59 UTC, Cyberboss commented on code/game/objects/items/weapons/cigs_lighters.dm
> +/obj/item/clothing/mask/vape/itstimetovape()
proc/

2017-05-20 18:10 UTC, Expletive commented on code/game/objects/items/weapons/cigs_lighters.dm
> +					itstimetovape()
I'm not entirely sure how actions work, but being able to toggle the mask's vaporizer would probably be neat.

2017-05-21 06:21 UTC, chaoko99 commented
Would it be cool with you if I ported this to Bay? I like the concept a lot.

2017-05-21 07:01 UTC, octareenroon91 commented
>Noone should get them. Engineers need to git gud.

The vape-mask is a really neat concept that tragically doesn't have any clear niche to serve. It could make sense for infusions in medbay, I guess.

2017-05-21 14:17 UTC, Jalleo commented
Actually it serves a lot of things. We just have to work out what it serves.

2017-05-21 15:33 UTC, Cyberboss approved these changes

2017-05-22 01:13 UTC, octareenroon91 commented
>Actually it serves a lot of things. We just have to work out what it serves.

I was trying to say that but you seem to have said it better.

2017-05-22 16:47 UTC, Expletive commented
So what should I do about this PR? I can give the mask to some other job, or even no job and let the maintainers figure out what to do with it.

2017-05-22 16:48 UTC, Repukan commented
Any department except RnD

2017-05-22 16:53 UTC, QualityVan commented
I'd kind of like to see them in the medical vending machines. Maybe two or three per?

2017-05-22 17:22 UTC, Expletive commented
Any thoughts on what reagents it should contain by default, if any? I suppose in medbay it makes sense for it to be empty, since chemistry is right there. What if I added a variant that appears rarely, say 3-7%, to emergency o2 closets with something like a mixture of perfluorodecalin and leporazine? I could have a modified sprite, maybe yellow and blue instead of gray.

2017-05-22 19:00 UTC, octareenroon91 commented
Even starting with salbutamol or epinephrine would probably be fine.

2017-05-22 19:34 UTC, QualityVan commented
If they're going to start with something in them, they should probably have a way to empty them. I don't know if they do right now. That being said, starting with a small amount of salbut could be good.

2017-05-22 19:44 UTC, Expletive commented
@QualityVan They inherit from vapes, so yeah. You empty them by using them in hand.

2017-05-22 23:13 UTC, octareenroon91 commented on code/modules/clothing/masks/breath.dm
> +	create_reagents(chem_volume)
create and fill happen in `vape/Initialize()`. At present the mask would start full of nicotine...

2017-05-22 23:20 UTC, QualityVan commented on code/modules/clothing/masks/breath.dm
> +	create_reagents(chem_volume)
To fix this, give the vapormask a list_reagents. Look at cigarette variants.

2017-05-22 23:24 UTC, octareenroon91 commented on code/modules/clothing/masks/breath.dm
> +	create_reagents(chem_volume)
OK. It looked redundant

2017-05-22 23:25 UTC, Cyberboss approved these changes

2017-05-22 23:26 UTC, Cyberboss commented
Oh wait, i already did whoops

2017-05-22 23:56 UTC, Expletive commented on code/modules/clothing/masks/breath.dm
> +	create_reagents(chem_volume)
Just tested it. It starts empty.

2017-05-23 03:23 UTC, Expletive commented
Okay, I have an action button. Press it to toggle the mask's vaporizer on or off.

2017-05-24 21:57 UTC, duncathan commented
If another maintainer cares to merge this feel free

2017-05-24 21:57 UTC, closed without merging