Removes the mess added with recalling with a message
tgstation/tgstation pull request #27450
Opened 2017-05-20 05:33 UTC by lzimann

2017-05-20 09:24 UTC, coiax commented
I don't know why you hate msglog_admins so much

2017-05-20 09:25 UTC, coiax commented
The codebase is FULL of the two procs with identical contents, differing only in a link or two.

2017-05-20 09:44 UTC, Jordie0608 commented
It's a lazy 3 lines of snowflake used in one place to save having to write a whole nother line in the rare circumstance have the same text for both `message_admins` and `log_admin`

2017-05-20 13:09 UTC, coiax commented
Duplicating strings is bad, it's double the strings to maintain.

2017-05-20 17:12 UTC, Cruix commented
Removing duplicate code is the opposite of snowflake and should always be encouraged.

2017-05-20 17:28 UTC, Cyberboss requested changes

2017-05-20 17:28 UTC, Cyberboss commented on code/modules/admin/verbs/randomverbs.dm
> +	if(!holder)
check_rights(R_ADMIN, TRUE)

2017-05-20 17:29 UTC, Cyberboss commented
I agree there' needs to be a common log/msg admin proc but just hamfisting the two together isn't the way to do it

2017-05-21 12:56 UTC, merged

2017-05-30 04:54 UTC, optimumtact commented
you broke it good job