Fixes jetpacks working indoors/in areas with gravity
tgstation/tgstation pull request #27488
Opened 2017-05-21 05:24 UTC by kevinz000

1. @Cyberboss these were your changes that caused it, were they on purpose? I'm assuming not because people shouldn't be hyperspeed indoors with jetpacks that aren't even using any good amount of gas due to being indoors. 
2. I ded pls nerf, @Robustin robusted me with jetpack abuse so I'm taking it off the table boys :^)

2017-05-21 05:24 UTC, obscolene commented
it's a feature

2017-05-21 05:25 UTC, kevinz000 commented
it's an exploit B)

2017-05-21 05:59 UTC, Sligneris commented
>I ded pls nerf, @Robustin robusted me with jetpack abuse so I'm taking it off the table boys :^)

Let's put you on the table instead

2017-05-21 06:50 UTC, Steelpoint commented
I asked admins and coders in game a few days ago and they agreed it was a intentional feature.

2017-05-21 07:21 UTC, kevinz000 commented
@Steelpoint why is it on the issue tracker?
i was joking, I don't even care that much but since it's an issue and I just happened to run through it while fucking with gravity pr again, why not?

2017-05-21 08:10 UTC, optimumtact commented
This is an obvious bug

2017-05-21 10:18 UTC, KorPhaeron commented
Bug

2017-05-21 13:19 UTC, Cyberboss requested changes
This recreates the bug where having an active jetpack doesn't prevent conveyor belts from moving you

2017-05-21 20:30 UTC, KorPhaeron commented
Thats a pretty edge case vs constant max speed

2017-05-21 20:31 UTC, KorPhaeron commented
Merging this early because its a huge balance issue and kevinz has a fix up for the conveyor thing

2017-05-21 20:31 UTC, merged

2017-05-23 05:57 UTC, evsey9 commented
I'm fucking triggered
Well time to disable gravgen each round as CE because I want to GO FAST and I don't fucking care if YOU can't go fast everywhere, get some magboots