Adds proc to return list of fields active on a turf
tgstation/tgstation pull request #27573
Opened 2017-05-23 11:17 UTC by kevinz000

going to need this soon (tm)

2017-05-23 11:18 UTC, RemieRichards commented on code/modules/fields/turf_objects.dm
> +	fro(var/obj/effect/abstract/proximity_checker/advanced/part in T)
fro fro, fight the power!

2017-05-23 11:22 UTC, kevinz000 commented on code/modules/fields/turf_objects.dm
> +	fro(var/obj/effect/abstract/proximity_checker/advanced/part in T)
aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

2017-05-23 13:00 UTC, lzimann commented
Why add a proc that is not being used? Even if you will it's a simple thing, you can easily add it together with whatever you want to do.

2017-05-23 13:31 UTC, kevinz000 commented
@lzimann mostly so I don't have to change that many files in one PR so it's easier to review I guess.

2017-05-23 14:14 UTC, Cyberboss requested changes

2017-05-23 14:14 UTC, Cyberboss commented on code/modules/fields/turf_objects.dm
> +			ret |= part.parent
Do ret[part.parent] = TRUE

2017-05-24 05:16 UTC, Jordie0608 commented
One more file changed on a PR doesn't sound like a hassle.

2017-05-25 13:19 UTC, Really-Good-Soda-Flavor commented
Please just put this in whatever pull request will _actually use it_.

2017-05-25 14:49 UTC, lzimann commented
Just add this whenever you are actually using it.

2017-05-25 14:49 UTC, closed without merging