Closes bold tag in bombing list secret
tgstation/tgstation pull request #27586
Opened 2017-05-23 14:50 UTC by lzimann

2017-05-23 14:57 UTC, Cyberboss requested changes

2017-05-23 14:57 UTC, Cyberboss commented on code/modules/admin/secrets.dm
> +			var/dat = "<B>Bombing List</B><HR>"
Make it a list and use dat.Join()

2017-05-23 14:59 UTC, lzimann commented on code/modules/admin/secrets.dm
> +			var/dat = "<B>Bombing List</B><HR>"
\>effort to change this wonderful piece of code

2017-05-24 13:37 UTC, Cyberboss commented on code/modules/admin/secrets.dm
> +			var/dat = "<B>Bombing List</B><HR>"
Do it reee

2017-05-24 21:18 UTC, merged