fixes infinite creampie stacking
tgstation/tgstation pull request #27826
Opened 2017-05-29 04:44 UTC by kevinz000

NO FUN ALLOWED
:cl:
bugfix: You can no longer have mutliple creampies on your face.

2017-05-29 05:04 UTC, Cyberboss requested changes

2017-05-29 05:04 UTC, Cyberboss commented on code/modules/food_and_drinks/food/snacks_pie.dm
> +				H.add_overlay(creamoverlay)
This is not the way to do this, absolutely nothing aside from SSoverlays should be using the overlays var. Make a different var instead

2017-05-29 08:48 UTC, xxalpha commented
Change title to "breaks infinite creampie stacking".

2017-05-29 11:40 UTC, kevinz000 commented
can't be assed to do this

2017-05-29 11:40 UTC, closed without merging

2017-05-29 11:50 UTC, FantasticFwoosh commented
Congratulations you backed out of your fix for a weapon that'll be removed because of infinite creampie stacking.

2017-05-29 12:22 UTC, Ausops commented
someone was getting multiple creampies on their face huh

2017-05-29 12:51 UTC, Cyberboss commented
FIX IT YOU NERD

On May 29, 2017 8:22 AM, "Ausops" <notifications@github.com> wrote:

> someone was getting multiple creampies on their face huh
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/27826#issuecomment-304648524>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHyweiBMyJrI6QaN7kY1cBnfbuulpnXsks5r-riKgaJpZM4No5VH>
> .
>

2017-05-29 22:39 UTC, Anonmare commented
>Local coder gets tabled and creampied over and over: Aheago edition

2017-05-30 05:50 UTC, xxalpha commented
Sounds like rape