Gang Machinegun Mouse Tracking + Projectile Source Fix
tgstation/tgstation pull request #27868
Opened 2017-05-30 12:15 UTC by kevinz000

1. Moves Gang Machineguns to its own file. It's not a goddamn portable turret and it's not even something that uses power!
2. Gang Machineguns now track the mouse location of the first buckled person (For those who don't code, that means the person using it)
3. Gang Machineguns will automatically aim and turn towards whatever that person is pointing at.. However, to make it target something specifically instead of a direction, you still have to hold your mouse down while firing.
4. Gang machineguns will no longer cause the user to shit out bullets if they unbuckle during firing :^)

# SOME REFACTORS TO PIXEL PROJECTILES ARE INCLUDED...

2017-05-30 14:06 UTC, GunHog commented
**DEATH BLOSSOM MODE ENGAGED!**

2017-05-30 14:32 UTC, Robustin commented
Good fixes but permanent autotracking is not an improvement. I need to be able to examine stuff without necessarily wanting to point my gun at/shoot at it. 

But holding down mouse isn't the most intuitive aiming choice either so meh.

2017-05-30 15:04 UTC, kevinz000 commented
Why would you not turn your gun around to examine something if it's behind you though

2017-05-30 15:12 UTC, ChangelingRain commented
the turning is so jerky aaaaaaaaa

2017-05-30 15:15 UTC, Thunder12345 commented
Can you make the fire sound a var by any chance?

2017-05-30 17:27 UTC, kevinz000 commented
@ChangelingRain I'm too burned out to make it smooth 360 degrees right now maybe later :3

2017-05-30 17:27 UTC, kevinz000 commented
@GunHog that'd be a balance thing bug @Robustin

2017-05-30 19:42 UTC, evsey9 commented
GIVE IT A LASER BEAM AIM

2017-05-30 19:48 UTC, GunHog commented
Just do it, it is fine, Kev. It is an advantage in that the user can see where he aims, but the disadvantage is that everyone else can see it as well!

2017-05-30 20:10 UTC, Cyberboss requested changes

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +		var/client/C = controller.client
Swap these 2 lines and do if(C)

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +		qdel(src)
Replace this whole proc with:
```
/obj/item/gun_control/Initialize()
    . = ..()
    turret = loc
    if(!istype(turret))
        return INITIALIZE_HINT_QDEL
```

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +	var/obj/machinery/manned_turret/turret
Add a Destroy() to null this

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +				var/obj/item/gun_control/TC = new /obj/item/gun_control(src)
Just `= new(src)`

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +			var/obj/item/gun_control/TC = new /obj/item/gun_control(src)
Just `= new(src)`

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +			if(M.dropItemToGround(I))
They should just be unbucklable if they're holding something

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +		return
these 2 lines -> return PROCESS_KILL

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +		return
Remove these lines

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +	process()						//REFRESH MOUSE TRACKING!!
Seperate what you need in process into a unique proc. Don't call it directly

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +/obj/item/gun_control
Move all these definitions below the manned_turret stuff

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +	loc = targets_from
forceMove

2017-05-30 20:10 UTC, Cyberboss commented on code/modules/projectiles/projectile.dm
> +	loc = get_turf(user)
forceMove

2017-05-30 20:10 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +	var/atom/target
Null this in Destroy()

2017-05-30 21:34 UTC, evsey9 commented
and make all vigiliantes on screen turn into facehuggers for the person on the mounted machinegun turret

2017-05-31 06:10 UTC, kevinz000 commented on code/game/objects/structures/manned_turret.dm
> +	var/obj/machinery/manned_turret/turret
done

2017-05-31 06:10 UTC, kevinz000 commented on code/game/objects/structures/manned_turret.dm
> +			if(M.dropItemToGround(I))
@Robustin

2017-05-31 06:10 UTC, kevinz000 commented on code/game/objects/structures/manned_turret.dm
> +	var/atom/target
done

2017-06-01 00:10 UTC, merged