Mapped active shieldgens
tgstation/tgstation pull request #27864
Opened 2017-05-30 10:15 UTC by AnturK

Fixes #27747

2017-05-30 13:06 UTC, WJohn commented
Thank you!

2017-05-30 13:14 UTC, AnturK commented
I'll add wall shield later to this.

2017-05-30 20:13 UTC, Cyberboss requested changes

2017-05-30 20:13 UTC, Cyberboss commented on code/game/machinery/shieldgen.dm
>  	var/list/deployed_shields = list()
Move the instantiation to Initialize

2017-05-31 10:14 UTC, AnturK commented on code/game/machinery/shieldgen.dm
>  	var/list/deployed_shields = list()
Sure.

2017-05-31 13:55 UTC, merged