Fixes admiral recall
tgstation/tgstation pull request #27861
Opened 2017-05-30 07:05 UTC by Shadowlight213

Fixes #27787 

@ChangelingRain You removed a bit more than the mess~

2017-05-30 07:05 UTC, optimumtact commented
kick me would you eh

2017-05-30 07:06 UTC, kevinz000 commented
WTF METAGRUDGE

2017-05-30 09:21 UTC, lzimann commented
My fault, meant to remove the timer and probably forgot to readd the proc cal. Speaking of which, get rid of this nonsense timer

2017-05-30 20:11 UTC, Shadowlight213 commented
@lzimann done

2017-05-30 20:14 UTC, Cyberboss requested changes

2017-05-30 20:14 UTC, Cyberboss commented on code/controllers/subsystem/shuttle.dm
> +	emergency.cancel(new /area/centcom)
Use locate(/area/centcom) in GLOB.sortedAreas

2017-05-30 20:15 UTC, Shadowlight213 commented on code/controllers/subsystem/shuttle.dm
> +	emergency.cancel(new /area/centcom)
@Cyberboss there is no actual centcom area. There's only the children. I checked when debugging this.

2017-06-01 00:22 UTC, optimumtact commented on code/controllers/subsystem/shuttle.dm
> +	emergency.cancel(new /area/centcom)
I would just leave it null

2017-06-03 17:00 UTC, AnturK commented on code/controllers/subsystem/shuttle.dm
> +	emergency.cancel(new /area/centcom)
Please change this, creating empty areas actually has side-effects so avoid this please.

2017-06-04 02:41 UTC, merged