Adds traitor steal objective: the Supermatter Sliver. (Fixed)
tgstation/tgstation pull request #27913
Opened 2017-05-31 20:11 UTC by bgobandit

#:cl: bandit
add: The Syndicate has been observed with supermatter technology. Nanotrasen is investigating potential tampering with its supermatter devices.
add: Traitors can steal supermatter slivers now. It works much like the plutonium core.
/:cl:

New PR, changes requested by @Cyberboss made, merge conflicts resolved, test issues resolved

Traitors have a new steal objective, to extract a sliver of a supermatter crystal. This works much like stealing the plutonium core:

- Use a special scalpel (different fluff is welcome) to slice a sliver off. Like the plutonium core, this sliver will periodically emit radiation if not stored.
- Pick the sliver up with tongs, also provided. If you or anything else touches the crystal, then it dusts. If you use the tongs to attack a person, the resulting force will dust you as well (so you can't go around instakilling people). The sliver will also be destroyed, to prevent a chain reaction of people dusting people.
- Use the tongs to put it in the container, provided as well.
- Once you extract a sliver, the supermatter will gain energy, requiring you to have protection. The exact amount of energy can be tweaked, the idea is that delamination will not happen immediately but that it is serious, noticeable sabotage and the traitor should probably get out fast.
- Both the scalpel and tongs do burn instead of brute damage, because they are made of SEARING COLD FREON THIS IS GREAT FLUFF sigh

What this adds to the game: Steal objectives should be more difficult than they are. No one gives a shit about, say, the blueprints. The supermatter also lacks a meaningful traitor interaction that is not just releasing a singularity. This provides that. 

Other changes:

- In order to prevent the sliver from being dragged added a can_be_pulled proc to movable atoms, and moved some of the start_pulling checks into that proc.

2017-06-01 17:03 UTC, bgobandit commented
WHY IS THE DME DOING THIS SHIT

2017-06-01 17:48 UTC, loqoman commented
I dig this. New traitor interaction with the new engine.

+1

2017-06-01 18:09 UTC, RandomMarine commented
The container should be disguised as a super matter bin.

2017-06-01 19:33 UTC, octareenroon91 commented
I guess that's a decent pun.

2017-06-02 15:13 UTC, Cyberboss requested changes

2017-06-02 15:13 UTC, Cyberboss commented on code/game/gamemodes/objective_items.dm
> +	special_equipment += /obj/item/weapon/storage/box/syndie_kit/supermatter
Call ..()

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	QDEL_NULL(core)
return ..()

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	START_PROCESSING(SSobj, src)
STOP_PROCESSING in Destroy

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +			to_chat(loc, "<span class='warning'>[src] is permanently sealed, [core]'s radiation is contained.</span>")
\The [src]

\the [core]

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [core] is stuck to your hand!</span>")
\The

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		to_chat(user, "<span class='notice'>You carefully pick up [src] with [tongs].</span>")
\the [src]

\the [tongs]

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	QDEL_NULL(sliver)
return ..()

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +			to_chat(loc, "<span class='warning'>[src] is permanently sealed, [sliver] is safely contained.</span>")
\The [src]

\the [sliver]

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		playsound(loc, 'sound/items/Deconstruct.ogg', 60, 1)
playsound(src, ...

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +		playsound(get_turf(user), 'sound/effects/supermatter.ogg', 50, 1)
playsound(src, ...

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	QDEL_NULL(sliver)
return ..()

2017-06-02 15:13 UTC, Cyberboss commented on code/game/objects/items/theft_tools.dm
> +	playsound(get_turf(user), 'sound/effects/supermatter.ogg', 50, 1)
playsound(src, ...

2017-06-02 15:13 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +		if(do_after(user, 60*W.toolspeed,target=src))
`do_after(user, 60 * W.toolspeed, TRUE, src)`

2017-06-02 15:13 UTC, Cyberboss commented on tgstation.dme
> -#include "code\controllers\subsystem\language.dm"
You broke the fuck out of the dme

2017-06-05 13:08 UTC, RemieRichards commented on code/game/objects/items/theft_tools.dm
> +			to_chat(loc, "<span class='warning'>[src] is permanently sealed, [core]'s radiation is contained.</span>")
no. it's automatic we've told you thiiiis.

2017-06-05 13:08 UTC, RemieRichards commented on code/game/objects/items/theft_tools.dm
> +			to_chat(user, "<span class='warning'>The [core] is stuck to your hand!</span>")
^ see above cyber

2017-06-05 13:08 UTC, RemieRichards commented on code/game/objects/items/theft_tools.dm
> +		to_chat(user, "<span class='notice'>You carefully pick up [src] with [tongs].</span>")
^ see above cyber

2017-06-05 13:09 UTC, RemieRichards commented on code/game/objects/items/theft_tools.dm
> +			to_chat(loc, "<span class='warning'>[src] is permanently sealed, [sliver] is safely contained.</span>")
^ see above cyber

2017-06-05 14:49 UTC, lzimann commented
Know you are busy and all of that, but cmon

2017-06-05 19:37 UTC, bgobandit commented
don't close this I'm trying to fix the dme issue

2017-06-05 21:26 UTC, lzimann commented
Just revert the DME to match the one in upstream, then you just tick your file again.

2017-06-06 14:57 UTC, DoctoreMad commented
Guys lets have an traitor objective that requires you to destabilize the station's power generator for the meme

2017-06-07 07:10 UTC, octareenroon91 commented
Self-wrecking engine is just as much a return to form.

The issue of actual risk has already been discussed too.

2017-06-07 19:25 UTC, lzimann commented on code/game/objects/items/theft_tools.dm
> +	<li>???</li>"
Missing a `</ul>` tag

2017-06-07 19:25 UTC, lzimann commented on code/game/objects/items/theft_tools.dm
> +	<li>???</li>"
Same here.

2017-06-07 19:40 UTC, bgobandit commented
all comments upthread should be addressed idk why they still show up

2017-06-08 10:53 UTC, AnturK commented on code/game/atoms_movable.dm
> +	if(isliving(src))
No no, move this to living level /can_be_pulled

2017-06-12 08:10 UTC, AnturK commented
@bgobandit  Merge conflicts.

2017-06-14 00:45 UTC, lzimann commented
@bgobandit

2017-06-16 00:46 UTC, bgobandit commented
@AnturK I literally have no idea what the fuck you are asking, the entire point of moving it was so it would be under the object, not mob/living

2017-06-17 19:41 UTC, Cyberboss requested changes
You deleted the tgstation-server submodule

2017-06-17 22:45 UTC, Cyberboss requested changes

2017-06-17 22:45 UTC, Cyberboss commented on code/game/atoms_movable.dm
> +			return FALSE
Do what @AnturK said: Remove these 4 lines. Create `/mob/living/can_be_pulled()` in `code/modules/mob/living/living.dm` and fill it out like this:

```
/mob/living/can_be_pulled()
    return ..() && !(buckled && buckled.buckle_prevents_pull)
```

2017-06-18 02:21 UTC, Cyberboss approved these changes

2017-06-18 02:32 UTC, merged