Dominator colors are now directly determined by the gang's color
tgstation/tgstation pull request #27947
Opened 2017-06-01 19:31 UTC by ChangelingRain

Fixes #27603
Looks 200% better

2017-06-01 20:27 UTC, lzimann commented on code/game/gamemodes/gang/dominator.dm
>  		countdown.color = gang.color_hex
Won't this countdown look really bad having the same color as the dom?

2017-06-01 20:51 UTC, Cyberboss requested changes

2017-06-01 20:51 UTC, Cyberboss commented on code/game/gamemodes/gang/dominator.dm
> +		name = "[gang.name] Gang [name]"
src instead of name

2017-06-01 20:59 UTC, ChangelingRain commented on code/game/gamemodes/gang/dominator.dm
> +		name = "[gang.name] Gang [name]"
Tunnel Gang the dominator, sure

2017-06-01 20:59 UTC, ChangelingRain commented on code/game/gamemodes/gang/dominator.dm
>  		countdown.color = gang.color_hex
It already does sooooo I don't think so no

2017-06-02 00:05 UTC, MrPerson commented on code/game/gamemodes/gang/dominator.dm
>  		countdown.color = gang.color_hex
Changing it to not colorize the text would be trivial if someone wants to do that

2017-06-03 07:25 UTC, merged