Gangmageddon: Hell March Edition
tgstation/tgstation pull request #27954
Opened 2017-06-02 04:56 UTC by Robustin

So I git meme'd my last PR #27695.

The latest updates bring significant nerfs to gang influence and the machine gun. Reinforcements are now very active for all parties and gangs will be notified if they fail to place a gateway after a few minutes. All in all this update contains a ton of changes and fixes to the previous iteration that should address some of the bigger issues. The brig also no longer explodes and instead all of the problematic equipment is deleted (Cap's ID and laser, all roundstart guns and stun weapons, etc.), the brig is now "abandoned" with no power or weaponry but with a little work can serve as a nice hideout for Gangs or Vigilantes. 

Tons of tweaks for various mechanics. The crisis shuttle will trigger sooner, as will backup vigilantes. Ultimately I'm aiming for about a 30m-40m round length, similar to what you'd see in other "chaos" rounds like summon guns or Warops - but hopefully with engaging gameplay from start to finish and with a more coherent conflict. Anti-snowball measures are amp'd up too some I'm hoping the next test will see rounds that are in serious contention up until the very end. I've vigorously tested this version (though far short of 150 hours) so I think some tests this weekend will help decide if No-Sec is the way to go. Hopefully I'll be able to get a poll at the end to decide whether to leave GW as-is, go with the no-sec route, or just throw it out of rotation again. Even if it does end up in rotation I'd be aiming for about 5% round weight at the expense of Wizard, Revolution, or Nukeops.

2017-06-02 05:06 UTC, obscolene commented
Imagine Gang. Take that image, make it 10 times worse. Now think of a gamemode that is literally antags vs. validhunters. Merge that image with the old one. Now make it 10 times worse. Try to picture the WORST possible gamemode you can think of. Think of a station where the gamemode is announced at roundstart, security is blown up at roundstart, and validhunters are given syndicate uplinks. Think of a system where validhunters are rewarded for killing antags, and get more good boy points to buy things like rocket launchers and centcomm adminspawn-only mechs that are stronger than durands. Take that image, and make it 10 times worse. Think of gangs, but with infinite free revives, asspulled reinforcement portals that spew out gangsters. Think of a station where everyone is encouraged to validhunt, people are rewarded for validhunting, and it's literally the basis of the whole gamemode. Take that thought, merge it with TDM, and make it 10 times worse. It's becoming a shit singularity, exponentially and infinitely growing beyond what anyone previously thought to be possible. 

If you have never seen this gamemode in action, consider yourself lucky. I wish I had never witnessed this literal garbage fire of a roundtype. I would rather gouge my fucking eyes out with a homeless person's rusty fork than ever have to endure another minute of this absolute disaster. Robustin, I don't know what was going through your fucking head when you thought (((THIS))) would be a good idea, but it should have been a bullet. If I ever have to play through this call of duty bootleg again, I'm going to promptly overdose on amphetamines and hang myself in a hotel bathroom.

2017-06-02 05:22 UTC, kevinz000 commented
Obscolene that was the most beautiful post I've seen on github.

2017-06-02 05:26 UTC, ChangelingRain commented
if I testmerge this, then, is it murder?

2017-06-02 05:29 UTC, ChangelingRain commented
wrong!

2017-06-02 05:30 UTC, obscolene commented
i'd rather permanently take every single gamemode out of the rotation except for blob and revolution than play a single round of this

2017-06-02 05:44 UTC, Robustin commented
Well make sure to be on tomorrow night with a hotel reservation and your meds on hand.

Its fitting that your shitpost is all about IMAGINATION because that's all it is. Still though, you got a chuckle out of me so good job. The only thing you've said that was true is rewarding validhunters but that was already and always the case. Literally 95% of the shit you can loot off traitors can be 100% utilized by the validhunter. Every round has its antagonist and every mode gives players a reason to resist those antagonists. Without security and the AI to bail you out, there's absolutely no reason to risk getting killed unless you're going to get something out of it. Vigilante v. Gang gameplay offers unique dynamics that "Centcom Alert: TRAPS ARE NOT GAY *NUKE NOISES*" and "lol errybody has gun and is antag *MAGIC NOISES*" don't offer. 

The rounds where people have no reason to give a shit end up like Clock Cult and Shadowlings, where you basically just sit around hoping for someone to convert you because unless you started as security then you've got absolutely no reason to get involved.

The fact that @ChangelingRain "accidentally" left up a testmerge - that even I advocated pulling after a round revealed some of the bugs - that forced the mode, and forced it to Delta, every round for almost an entire day, then used player resentment to justify closing it, is just beyond fucking stupid. 

Judging by the shit @obscolene posted about infinite revives it sounds like he's a traumatized victim of that series of events, but it also sounds like he's the kind of person who thinks security force-implanting everyone and then requiring them to validhunt some dude hiding in a maint locker for 30 minutes just to end the damn round is a superior design concept. A new mode, let alone a revived gang mode, was never going to please everyone. I'll just do my fixes and some kind of poll this weekend will tell me whether this approach is worth sticking to or if we just want Rev w/Guns, or if we don't want this at all - I'm tired of being the only person willing to fix our "lost" modes and then getting shit on for it.

2017-06-02 06:04 UTC, obscolene commented
Robustin, if you honestly cannot see a single fucking flaw that I pointed out with this gamemode, then I don't know what I can tell you. If you cannot do anything but try to redeem this mess by comparing it to other gamemodes, then I don't know what I can tell you. If you can't think of  l i t e r a l l y   a n y t h i n g   e l s e   that isn't "lol war ops is tdm. summon guns is tdm xd" then I don't know what I can tell you. If war ops is TDM, then gang is a fucking free-for-all. This gamemode brings out the worst in people, and displays just how garbage you can truly make this game just with a simple gamemode. If you can't realize the multitude of things that are absolutely wrong with this abomination of a roundtype you've created, then you'd be better off playing on traitor deathmatch. Because that's literally what this is. Only instead of having 20 telecrystals, you can just keep getting more by killing antags.

2017-06-02 06:43 UTC, Robustin commented
@obscolene 

I see a whole lot of fucking flaws but that's the case for every fucking mode and there's never going to be improvements when the only thing I get to work with is cynics, shitposts, and platitudes. 

You bitch about FFA, TDM, V A L I D H U N T I N G but then I stare at shit like #27872 and wonder how much of these are honest sentiments and how much of it is kneejerk shitposting. You claim that this is some FFA shitshow but there are still teams with a hierarchy and strategy, the vigilantes have to abide by all the server rules, but when we try to remove the absolute lowest threshold for gameplay, a round that has infinite revives, absolutely no coherence, and literally gives half the crew an fucking OBJECTIVE to murder random crew and steal their shit - I lose faith that anything people like you say is sincere and not just regurgitated memes. 

So yes I'm AWARE of the issues, I've spent less than a week testing this mode and the vast majority of it has been bug fixing. I've seen 0 rounds to date where all of the core mechanics were working properly, but that's what happens when you've got someone with no coding background trying to rebuild a mode from the ground up without a single maintainer chipping in with guidance. I've sat around for WEEKS patiently waiting for help, literally the ONLY coherent advice I've gotten is from @KorPhaeron and @kevinz000  who felt that removing security and the implant spam was possibly the only salvation for this mode. I actually made the effort of making their ideas into reality and you can see all the sweet dividends I'm reaping. Gang War is not my "baby", I didn't create this mode, I didn't resist its removal, and I wasn't a part of any movement or vote that got it back into rotation - I just figured if the god damn players felt that it had potential, and I saw some obvious room for improvement, that it wouldn't be hard to experiment with some new concepts for a mode that was already sitting on Death Row. 

I've been behind every Gang War PR so far and I haven't heard anyone argue that the original mode was superior to my changes thus far. Yet I wasn't satisfied upgrading a mode from "death row" to "retirement home" status so I was willing to try more bold ideas based on the slivers of feedback that I've gotten. I'm sorry that's so upsetting to you, I hate myself for the bugs thus far more than anyone else, but I've always felt that it never hurts to try something new and see how it flies. All I ask for my endless hours of hard work, headache, and heartache is an open mind and intelligent feedback - yet even that modest request has left me sorely disappointed.

2017-06-02 07:18 UTC, kevinz000 commented on code/game/gamemodes/gang/gang.dm
> +	sleep(80)
addtimer

2017-06-02 07:20 UTC, kevinz000 commented on code/game/gamemodes/gang/gang.dm
> +/datum/game_mode/gang/proc/gangpocalypse()
i hope you've tested this for lag

2017-06-02 08:59 UTC, Tacolizard commented
@Robustin, this whole situation really sucks. I can see the amount of effort you've put into this, I had no idea you had no coding background. That's really impressive.

I don't really know what to say except that what you said really hits home. I've worked on a bunch of smaller PRs, which required no where near as much effort as you put into this one, only to have people make stupid, unhelpful comments. Even with small PRs, it's frusturating to have hours of work thrown away (I haven't posted anything made in more than an hour, but I have worked on scrapped ideas for much longer). 

Robustin, I think you're owed an apology from a lot of people.

2017-06-02 09:48 UTC, Repukan commented
You know tacolizard I think Robustin is getting truly shacted but you had it coming with the stupid gun engraving stunt.

2017-06-02 11:29 UTC, YakumoChen commented
>A lot of players just like to complain in OOC or on the forums without giving any real feedback, and without giving it where it matters, on github.

Half the time I'm forced to shitpost to get any sort of opinion heard because every time I go on github I get told to use the forums, and coders barely look at the forums, so it feels like a lose-lose. Complaining about shitty PRs never seems to help, mostly because whoever made it always seems completely autistic and unwilling to handle any sort of criticism anyway (goofball)

2017-06-02 11:48 UTC, RemieRichards commented on code/game/gamemodes/gang/gang.dm
> +		for(var/turf/T in area_contents(target_captain))
you should ```CHECK_TICK``` these outer loops (the ones going over turfs, the ones going over items should probably be fine)

2017-06-02 11:51 UTC, RemieRichards commented on code/game/gamemodes/gang/gang.dm
> +		character.key = spoo.key
very clever. 👏

2017-06-02 11:54 UTC, RemieRichards commented on code/game/gamemodes/gang/vigilante.dm
> +	switch(I.type)
holy heck no.

2017-06-02 11:55 UTC, RemieRichards commented on code/game/objects/items/weapons/clown_items.dm
> +		M.slip(slippyness, slippyness, src)
4, 2 -> 4, 4
HMMM.

2017-06-02 11:56 UTC, RemieRichards commented on code/game/objects/items/weapons/clown_items.dm
> +			if(istype(src, /obj/item/weapon/soap/vigilante) && istype(target, /obj/effect/decal/cleanable/crayon/gang))
>istype(src)

No.

2017-06-02 14:21 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +	sleep(80)
Fun Fact: I used the sleeps from Cyberboss's original intro

2017-06-02 14:22 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +/datum/game_mode/gang/proc/gangpocalypse()
150 hours son

2017-06-02 14:24 UTC, Robustin commented on code/game/gamemodes/gang/vigilante.dm
> +	switch(I.type)
Cyberboss said you could show me the light on this.

2017-06-02 14:26 UTC, Kromgar commented
But yeah atleast Robustin is the only one trying to fix gang you can't say anything about clockcult it just becomes more convoluted and bullshit

2017-06-02 14:27 UTC, Robustin commented on code/game/objects/items/weapons/clown_items.dm
> +		M.slip(slippyness, slippyness, src)
The two arguments on slip have been a meme for a long time. I figured out last year that literally only the larger of the two matter when I was doing my SLIP-SANITY pr. If youre stunned for 4 and weakened for 2, you're down for 4. Same vice-versa. 

As far as I can tell the stun itself is redundant, it doesn't do anything unless its longer than the weaken - in which case you might as well just set the weaken longer.

2017-06-02 14:44 UTC, Robustin commented
My only agenda is making shit that people like. I feel a great deal of satisfaction when I add stuff that's really fun or improves the game and I'll go to great lengths to deliver the best content I can. I have no background in coding or art but I sat around for hours a couple weeks ago working over hundreds of frames (The final concept wasnt the first, there was a lot of deleting and redoing), ones at a time, trying to figure out how to make a cult cinematic that wasn't utter trash - obsessing over every last pixel. 

I always have to confront my own bias towards my work, of course I want to BELIEVE that everything I code is great but I know that I've been wrong before and there's been more than one change I've supported or opposed and realized I had it wrong. Anyway what I'm trying to say is that every negative comment on this affects me, every slung insult stings, I read every last word of every comment because I want it to be better.

So when someone trashes the idea, I'm happy if I can at least learn something from it - get a better sense of what the community wants out of a mode, but its equally frustrating when the feedback is just someone screaming "ITS SHIT YOU SUCK". But at the end of the day, just like with the Engineering rewards, all I ever ask for, for all of my work, is a fair shake. At least this PR got to see the light of day but I admit I underestimated the amount of work it would take to get a mode without security into something decent, but the point is I'm willing to do that work and take on that challenge just so that if it does fail, I can at least rest easy knowing I did all I could and it was the community who made that decision and not just some maintainer whose tastes I've offended.

2017-06-02 16:35 UTC, InsaneHyena commented
Oldman, I've always encouraged your enterprise
And I've been hopeful that you would succeed!
But in the face of these powerful arguments
I see no choice but for you to concede.

2017-06-02 17:17 UTC, Robustin commented on code/game/objects/items/weapons/clown_items.dm
> +			if(istype(src, /obj/item/weapon/soap/vigilante) && istype(target, /obj/effect/decal/cleanable/crayon/gang))
I see this in several areas of our code, are you saying I should omit the first argument?

2017-06-02 17:23 UTC, Cyberboss commented
I really don't see why people are putting so much hate towards the only person interested in developing a mode

2017-06-02 17:23 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
> +			if(istype(src, /obj/item/weapon/soap/vigilante) && istype(target, /obj/effect/decal/cleanable/crayon/gang))
No, she want's you to put whatever you did here in a child proc

2017-06-02 17:24 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		character.key = spoo.key
I'm unclear of the correct way to do this myself. Mind transfers?

2017-06-02 17:38 UTC, Cyberboss requested changes

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		character.loc = D
from line 449 to here. You'll probably want to use SSjob.SendToLateJoin once my PR is merged: #26647

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	sleep(80)
Yeah, that was before MSO schooled me on sleeps. Go ahead and use timers

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +					qdel(I)
Refactor these loops into a proc. And each of them should be like this
```
var/list/L = T.GetAllContents()
for(var/obj/item/weapon/W in L)
    qdel(L)
for(var/obj/item/clothing/C in L)
    qdel(C)
```

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	for(var/mob/living/M in GLOB.player_list)
use mob/living/carbon/human

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +/proc/vigilize(mob/living/M)
gang gamemode proc

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
> +
else
    return INITIALIZE_HINT_QDEL

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
> +	linked_action.Remove(M)
if(istype(M))

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
>  	var/dat
Make this a list

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
>  	popup.set_content(dat)
dat.Join()

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	if(ismob(loc))
. = ..()

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +
else
return INITIALIZE_HINT_QDEL

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	var/list/vigilante_items = list(
static list

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +		return
Remove this check, timers do it for you

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +		addtimer(CALLBACK(src, .proc/earnings), 1500)
TIMER_UNIQUE

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	var/dat
list

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	popup.set_content(dat)
dat.Join()

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	if(usr.restrained() || usr.lying || usr.stat || usr.stunned || usr.weakened)
if(usr.incapacitated())

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	if(!I)
if(QDELETED(I))

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	attack_self(usr)
don't call attack_self, refactor what's in attack_self into a unique proc and call that

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +			if(I.type == G.outer_outfit && I.armor["bullet"]>=35)
istype

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +			to_chat(user, "<span class='notice'>[I] has been processed for [value] influence.")
Unclosed span

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +		if(I)
replace these two lines with if(do_after(user, 30, TRUE, I))

2017-06-02 17:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	VT.attack_self(owner)
Make a unique proc like I said above

2017-06-02 17:38 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
> +		M.slip(slippyness, slippyness, src)
I agree, this proc is fucking stupid, should always just use weaken

2017-06-02 17:38 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
>  	else if(ishuman(target) && user.zone_selected == "mouth")
I think we have a define for "mouth" somewhere

2017-06-02 17:38 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +			buckled_mob.client.change_view(world.view)
Please explain this change

2017-06-02 17:51 UTC, ChangelingRain commented on code/game/objects/structures/manned_turret.dm
> +			buckled_mob.client.change_view(world.view)
YOU SHOULD KNOW WHY, `reset_perspective()` DOESN'T RESET VIEW

2017-06-02 17:54 UTC, Iamgoofball commented on code/game/gamemodes/gang/gang.dm
> +		character.key = spoo.key
lmao :+1: robustin

2017-06-02 17:55 UTC, Iamgoofball commented on code/game/objects/items/weapons/clown_items.dm
> +		M.slip(slippyness, slippyness, src)
r e c o d e s l i p s

2017-06-02 17:57 UTC, Robustin commented
Mode debates bring out the worst in this community. Most of the maintainers would've preferred it never got developed in the first place and see no path to its redemption. Some people are also really triggered by the concept of a Gang War creating anarchy and chaos.

I'm just in shrug mode at this point. Hopefully testing this weekend will be mostly bug-free and people can get a feel for the mode and a poll will settle the rest.

2017-06-02 18:02 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +			buckled_mob.client.change_view(world.view)
...Why

2017-06-02 18:02 UTC, InsaneHyena commented
Oldman, when you think "gang war", do you really imagine people noscoping and delimbing each other with sniper rifles, or mounted miniguns? Or much of the other things you've included? I'm all for some elements of your vision, but you need to scale down a lot of shit here. By a lot.

2017-06-02 18:22 UTC, ChangelingRain commented on code/game/objects/structures/manned_turret.dm
> +			buckled_mob.client.change_view(world.view)
because that's literally not its function and it resetting on reset_perspective would reset view changes on any forceMove

2017-06-02 18:23 UTC, Robustin commented
The intention was always to have that stuff only show up late into the game, but early versions gave gangsters too much influence. 

Both the weapons you referenced will only appear later and both have seen significant nerfs. I enjoy the mode more too when it sticks to lighter weaponry for the first ~20m but I also appreciate the depth that comes from specialized weaponry later on. I didn't just want the lategame to be UZI WARS.

2017-06-02 18:55 UTC, kevinz000 commented
Between robustin and tacolizard robustin is better atleast he doesn't spam dumb meme PRS that doesn't compile. 
Tacolizard just got shot with his own engraved gun

2017-06-02 19:34 UTC, ChangelingRain commented
>Ticket #11: i think i found a bug, the advanced recruitment pen deconverts your own gang members

2017-06-02 20:19 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +					qdel(I)
Once I'm sure that weapon+clothing covers it all.

2017-06-02 20:37 UTC, Bawhoppen commented
Why does gang have to be ultimate TDM? 
Traitor is by far the most popular mode, and that doesn't completely turn the round into a shitmatch.
What if you showed restraint with the mode, instead of going over the top instantly?

2017-06-02 20:38 UTC, ChangelingRain commented on code/game/gamemodes/gang/vigilante.dm
>  	to_chat(H, "<span class='notice'>You have received 4 influence for your continued loyalty, [newpoints] for keeping the station tag-free.")
3

2017-06-02 20:38 UTC, ChangelingRain commented on code/game/gamemodes/gang/vigilante.dm
>  		to_chat(H, "<span class='notice'>You have also received 4 influence for possessing a mindshield implant.</span>")
3

2017-06-02 20:57 UTC, ChangelingRain commented on code/game/gamemodes/gang/vigilante.dm
> +		to_chat(H, "<span class='notice'>You have also received 4 influence for possessing a mindshield implant.</span>")
3!

2017-06-03 09:37 UTC, RemieRichards commented on code/game/gamemodes/gang/vigilante.dm
> +	switch(I.type)
you can make a variable on ```/obj/item```
```
/obj/item
    var/gang_contraband_value = 0

/obj/item/weapon/implanter/gang
    gang_contraband_value = 12

//etc.
```

2017-06-03 09:37 UTC, RemieRichards commented on code/game/gamemodes/gang/gang.dm
> +		character.key = spoo.key
@Cyberboss SPOO.KEY
SPOOKY.

2017-06-03 09:38 UTC, RemieRichards commented on code/game/objects/items/weapons/clown_items.dm
> +		M.slip(slippyness, slippyness, src)
@Robustin fair enough

2017-06-03 09:40 UTC, RemieRichards commented on code/game/objects/items/weapons/clown_items.dm
> +			if(istype(src, /obj/item/weapon/soap/vigilante) && istype(target, /obj/effect/decal/cleanable/crayon/gang))
@Robustin ```istype(src), istype(src, some_path)``` will never be accepted, it is a CLEAR hint that you've done something wrong. Checking the type of src is a huge violation of OOP.

2017-06-03 09:42 UTC, RemieRichards commented on code/game/objects/structures/manned_turret.dm
> +			buckled_mob.client.change_view(world.view)
@Cyberboss perspective refers to the ```perspective``` variable of ```/client```, and of its eye object.
It has no relation to view size.

2017-06-03 13:47 UTC, Robustin commented on code/game/gamemodes/gang/vigilante.dm
> +	popup.set_content(dat)
Like last time, I get an error when I do this.

2017-06-03 13:49 UTC, RemieRichards commented on code/game/gamemodes/gang/vigilante.dm
> +	popup.set_content(dat)
you have to look at his previous comment, which is to make ```dat``` a list.
We don't allow making strings piece by piece like this without using lists now we have ```.Join()```

2017-06-03 16:46 UTC, Grazyn commented
If you latejoin but you have gang preference off, you won't get vigilante. This means you are as good as dead because both gangers and vigilantes will shoot at you.

2017-06-03 19:09 UTC, Tacolizard commented
@kevinz000 you'll never let that go, will you?

2017-06-03 20:54 UTC, Robustin commented on code/game/gamemodes/gang/vigilante.dm
> +	popup.set_content(dat)
I could've sworn I did it in conjunction with making it a list last time, ill have to try again I guess.

2017-06-05 15:46 UTC, Robustin commented
I've asked @ChangelingRain to put up a server poll. Asking for the players preference, to either remove GW, stick with current (security) GW, switch to this PR's GW, or to mix security and vigilante GW based on RNG at roundstart. 

If any choice surpasses 50% then that's what I'll support. If not then I'll move ahead with whatever makes sense based on the relative popularity of the options. Example: If #2 sits at 40% and #3 and #4 sit at 42% combined, then vigilante would only make a small fraction of an already lightly weighted mode (probably around 30% chance for vigilante mode to trigger during GW).

2017-06-05 22:25 UTC, Anonymous583 commented
Dead chat has summed it up at its finest.

"The CereStation of gamemodes."

I appreciate all the hard work that went into this, but it's just not fun at all.

2017-06-07 23:09 UTC, Tacolizard commented
Yes it is the CereStation of gamemodes. It has potential, and is even fun sometimes.

2017-06-08 01:39 UTC, Uqualm commented
You fell for the Democracy meme. Don't let the mob of morons determine how it is things should be run. They say they want one thing but have no idea what the consequences of that thing are. They are like a bunch of high school aged Bernie Sanders supporters screaming for "free" college. The data is useless, it comes from the players who have no clue what they are talking about. Find people who know what they are talking about, and ask them what they think. Of course identifying those people means that you need good judgment, which you may or may not have. 

Actually I remember one time you literally lasered me to death for slipping floors with water as a Botanist which the admins said was A-OK. In all likelihood your judgment is terrible. You're not capable of fixing anything, just messing things up further.

2017-06-08 05:06 UTC, Tacolizard commented
![](https://file.house/kp8b.png)

After unbuckling from the turret, i still had the increased view range. Then, someone else buckled to it while i was on it, pushed me off, and shot me while i was defenseless because my hands were filled with the turret controls still

2017-06-08 19:43 UTC, Robustin commented
Was this on the testmerged version? Kev pushed a machine gun "fix" that broke vision, I dunno if he fixed but the testmerged PR should have solved this.

2017-06-09 01:03 UTC, Robustin commented
The poll appears to be largely settings, I will be doing a 40/60 mix of sec/nosec for Gang War. After I fix all these Kev-flicts I'll address Remie's review and should be good from there.

In case anyone's curious:
Remove Gang War from rotation	70	28%	
Gang War in its current state with security	43	17%	
Gang War in its test-merge state with vigilantes but no security	30	12%	
Gang War includes Option #2 AND #3 but with ONE randomly picked at roundstart	 109	43%

2017-06-10 17:38 UTC, Iamgoofball commented on code/game/gamemodes/gang/gang_datum.dm
> +	for(var/datum/mind/MG in bosses|gangsters)
this works?

2017-06-11 19:08 UTC, lzimann commented on code/game/gamemodes/gang/gang_datum.dm
> +	for(var/datum/mind/MG in bosses|gangsters)
yea

2017-06-12 15:48 UTC, Robustin commented
Poll is finished with over 350 votes. The results clearly support a sec and no-sec mix, I believe 40% nosec and 60% sec is an accurate reflection of the voter's wishes. I will be adapting to Kev's mindpoints, debugging, and addressing Remie's review today but I sincerely hope I won't have to spend too much time convincing a maintainer to move forward with this. We already shut down a maintainer's efforts to kill the mode against player wishes, it would be even worse to bait me into investing all this time, holding another poll affirming the direction, only to try and kill it through inaction instead.

2017-06-13 04:24 UTC, meeeeme commented
You better update the wiki page if this gets merged.

2017-06-13 04:41 UTC, optimumtact commented
if you look at it another way, 47% voted for no change or removal and 53% voted for change

2017-06-13 05:14 UTC, Bawhoppen commented
well that vote was fundamentally flawed considering it didn't include an option for a whole different gang mode

2017-06-13 05:21 UTC, Iamgoofball commented
You're retarded baw

2017-06-13 05:29 UTC, Bawhoppen commented
that's alot coming from you

2017-06-13 14:45 UTC, Robustin commented
@optimumtact 

Well if we are allowed to make up our own assumptions then sure, we can also argue that 87% want this PR merged on the condition that its renamed "Robustin's Raucous Ride".

This PR  is mostly going with the "current state" option, just with some basic balance and fixes thrown in - its absurd to argue those voters, or the "remove from rotation" ones, are all 100% against a PR that smooths a lot of the edges of the mode out, even if they'd rather see it gone its just self-defeating logic. 

I'm also pretty frustrated that this PR has been in a "test ready" state for the last week, all while the poll was running, and yet it wasn't testmerged once. Early in the PR when it was riddled with bugs and some pretty drastic ideas I had Joan testmerging every evening, even when I wasn't around. Now that much more limited in scope and effect on the round I can't even continue to get player feedback. I'm not veering into MUH CONSPIRACY territory yet but like I said, its frustrating.

@Bawhoppen 

Nobody is saying you can't try that after the freeze, we made 2 cults after all. Feel free to code "Gang Disagreement" as a less violent alternative.

2017-06-13 20:58 UTC, optimumtact commented
I'm gonna start a betting pool

2017-06-13 21:37 UTC, KorPhaeron commented
Poll had too many options

Gang turret alone has required 10 fix PRs so it's understandable maintainers are hesitant to touch a game modes worth of similar code

2017-06-13 21:57 UTC, optimumtact commented
If only there was some maintainer willing to make big decisions

2017-06-13 22:55 UTC, KorPhaeron commented
I think the decision making is less the issue in this case than that nobody wants to review 1k+ lines of robustins code

2017-06-13 22:57 UTC, optimumtact commented
If only there was some dedicated maintainer who would do it

2017-06-13 22:58 UTC, Cyberboss commented
I'll do it, let me sober up first

On Jun 13, 2017 6:57 PM, "oranges" <notifications@github.com> wrote:

> If only there was some dedicated maintainer who would do it
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/27954#issuecomment-308272064>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywegz0uNlUu0Rk_Ccjjty8l2h-4v6rks5sDxO_gaJpZM4Nt1Fv>
> .
>

2017-06-13 23:03 UTC, KorPhaeron commented
Not sure this is something you want to be sober for

2017-06-14 01:08 UTC, VeryRealAccount commented
Why are we testmerging this with the freeze?

2017-06-14 01:12 UTC, Repukan commented
Grandfathered in

2017-06-14 01:14 UTC, VeryRealAccount commented
Player reactions are....fairly poor.  Not sure if that was a smart plan.

2017-06-14 01:16 UTC, optimumtact commented
wait a minute, you mean the people who hated it before still hate it now?

I'm shocked! Shocked! It's not like the poll was strongly divided either! :open_mouth:

2017-06-14 15:32 UTC, Robustin commented
Between Remie, Cyberboss, and test merges we've already reviewed most of this. 

Also:

>Put up a finished version for review
>Joan puts up a Stale and WIP tag a half-day later

Wat. Bonus points to oranges for using a poll that supports this PR against this PR. I've got No-Security at around 1% of our games at this point. I could sit around bitching that @ChangelingRain ran more test rounds in the first 24 hours than in the entire week of the poll combined, so people have more exposure to the most bug-ridden versions - often not understanding that implications that the bugs had on the round. At this point the PR is mostly a balance + fix pass.

2017-06-14 16:03 UTC, Steelpoint commented
We just had a game on this.

The game was buggy to all hell, vigilianties could not buy anything and many gang leaders did not have implants. Also the stale "take over cargo and win" meta is still in full force.

Despite that I think more people enjoyed the round than dislike it, and I did like the round for the short time I was alive.

2017-06-14 16:03 UTC, Repukan commented
Time to blow up cargo

2017-06-14 16:18 UTC, Robustin commented
@Steelpoint 

Did vigilantes take over cargo or was it security? Were there vigilantes in the security version?

2017-06-14 16:38 UTC, Cyberboss requested changes

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +			if(C != /area/crew_quarters/heads/captain/private)
This one is fine though

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		priority_announce("Excessive costs associated with lawsuits from employees injured by Security and Synthetics have compelled us to re-evaluate the personnel budget for new stations. Accordingly, th
Use a timer

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	if((alive <= (GLOB.joined_player_list.len * 0.5)) && (SSshuttle.emergency.mode == SHUTTLE_RECALL || SSshuttle.emergency.mode == SHUTTLE_IDLE || (SSshuttle.emergency.timeLeft(1) > (SSshuttle.emergenc
Could you explain this change please

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	var/list/mob/dead/observer/candidates = pollGhostCandidates("Would you like be a part of a Vigilante posse?", "pAI", null, FALSE, 100)
>pAI

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		if(SSshuttle.arrivals)
You can remove this check, it's a bug if it is missing

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		var/mob/living/carbon/human/character = new(src)
Why are you using the game_mode as a parameter?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		character.equip_to_slot_or_del(new /obj/item/clothing/suit/armor/vest/alt(character),slot_wear_suit)
Use outfits

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		SSticker.mode.shuttle_check() // See if its time to start wrapping things up
Isn't this already called somewhere else?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +			SSticker.mode.auto_declare_completion_gang(G)
Ticker/declare_completion already does this

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
>  			SSticker.force_ending = TRUE
force_ending isn't the right way to do this, use mode/check_finished

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	qdel(gangtool)
QDEL_NULL

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	var/obj/item/device/gangtool/O = new /obj/item/device/gangtool/spare/lt(user.loc)
get_turf(user)

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	if(confirm_final == "No")
`No` isn't a button

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	var/list/mob/dead/observer/queue = list()
New vars after parent vars

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	var/list/mob/dead/observer/queue = list()
You can init this list in Initialize

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +		qdel(M)
atom/movable/Destroy does this already. You can remove this proc

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +			final_guard = FALSE
Just use obj_break instead of take_damage and set integrity_failure to 300

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +/obj/machinery/gang/backup/proc/reinforce(var/repeat = TRUE)
Remove var/

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +/obj/machinery/gang/backup/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1)
sound_effect = TRUE

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +		return
Remove this check

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	reinforcement.transfer_to(H)
See the guidelines for using minds, mainly this bit: https://github.com/tgstation/tgstation/blob/master/code/datums/mind.dm#L21

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +		if(H.stat == DEAD && icon_state == "implanter1")
Do not use icon_state to denote a state

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +			if (H.suiciding || (H.disabilities & NOCLONE) || !H.getorgan(/obj/item/organ/heart) || !H.getorgan(/obj/item/organ/brain) || !H.mind)
Remove the mind check

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +			if(!H.key)
Check client instead

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +				var/list/mob/dead/observer/candidates = pollGhostCandidates("Would you to play the role of a revived [identity]?", "pAI", null, FALSE, 100)
This will make the proc sleep, make it a seperate proc with waitfor = FALSE

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +			var/overall_damage = total_brute + total_burn + H.getToxLoss() + H.getOxyLoss()
Why are you halfandhalfing it like this?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +			icon_state = "implanter0"
use update_icon()

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	..()
Intialize and . = ..()

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	operation_req_access = list()
init this list in initialize

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +	bumpsmash = 0
Is this a bool? if so, FALSE

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
>  /obj/item/device/gangtool/soldier/New(mob/user)
Initialize, remove user param

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
> +	linked_action.Grant(user, src, gang)
use loc instead of user

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	var/list/tags = list()
create the list in initialize

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	if(ismob(loc))
reorganize the if so the majority of the function isn't indented.

```
if(!ismob(loc))
    return INITIALIZE_HINT_QDEL

...
```

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	M.update_icons()
Why is update_icons needed?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
> +	M.update_icons()
Why is update_icons needed?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	var/dat
list

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	attack_self(usr)
See my previous comment

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	var/dat
See my previous comment

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	popup.set_content(dat)
See my previous comment

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +		if(/obj/item/weapon/gun/ballistic/automatic/pistol)
what you'll have to do is create a proc on obj/item called ContrabandValue() and have it return 0 by default. Then populate it for each of these items

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +			if(I.type == G.outer_outfit && I.armor["bullet"]>=35)
istype

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	user.update_icons()
update_icons why?

2017-06-14 16:38 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	VT.attack_self(owner)
See my previous comment

2017-06-14 16:38 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
> +	to_chat(user, "<span class='notice'>You scrub \the [scum.name] out.</span>")
just [scum]

2017-06-14 16:38 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implant_gang.dm
> +/obj/item/weapon/implant/gang/implant(mob/living/target, mob/user, silent = 1)
TRUE

2017-06-14 16:52 UTC, Steelpoint commented
The round I was in was a Vigilante only game mode. There were only Vigilante's and two Gangs.

One gang took over cargo and held it. They called a very early (at least by my standards) Dominator (around the ten to fifteen minute mark if I have to guess) and were unassailable, they had access to some RCDS, plasteel and basic Gang Rifles.  They also had a Reinforcement Gateway up. Amusingly it took them a lot longer to Dominate the station as people kept placing Rwalls around the dominator (on that note, make it unviable to place any walls next to the dom).

When they started it took them 180 seconds to win, but again that was delayed. 

At first it was the rival gang that assault cargo. Eventually reinforcement Vigilante's took over the assault.

2017-06-14 16:54 UTC, Steelpoint commented
The issue is that its too easy for a gang to just RCD/Wall off entire areas to delay a assault long enough to win. Cargo is just a strong place to defend but even if cargo blows up the gangs will just move elsewhere.

2017-06-14 20:11 UTC, Cyberboss requested changes

2017-06-14 20:11 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	if((alive <= (GLOB.player_list.len * 0.45)) && (SSshuttle.emergency.mode == SHUTTLE_RECALL || SSshuttle.emergency.mode == SHUTTLE_IDLE || (SSshuttle.emergency.timeLeft(1) > (SSshuttle.emergencyCallT
Still want to know why you added `SSshuttle.emergency.mode == SHUTTLE_IDLE`

2017-06-14 20:11 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
> +			to_chat(user, "<span class='notice'><b> The [tag.territory] is no longer under gang control. Keep this area clean for additional influence.</b></span>")
\The

2017-06-14 23:39 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +			break
This is your code REEEEE

2017-06-14 23:41 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +		priority_announce("Excessive costs associated with lawsuits from employees injured by Security and Synthetics have compelled us to re-evaluate the personnel budget for new stations. Accordingly, th
>Timer for a single text announcement a few seconds later

2017-06-14 23:41 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +	var/list/mob/dead/observer/candidates = pollGhostCandidates("Would you like be a part of a Vigilante posse?", "pAI", null, FALSE, 100)
I dunno I saw this used frequently for other modes so I figured pAI ban = ghost role ban

2017-06-14 23:43 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +		SSticker.mode.shuttle_check() // See if its time to start wrapping things up
The one and only

2017-06-14 23:52 UTC, Robustin commented on code/game/gamemodes/gang/gang_items.dm
> +		qdel(M)
The bodies I saw sticking around seem to disagree

2017-06-14 23:54 UTC, Robustin commented on code/game/gamemodes/gang/gang_items.dm
> +			if (H.suiciding || (H.disabilities & NOCLONE) || !H.getorgan(/obj/item/organ/heart) || !H.getorgan(/obj/item/organ/brain) || !H.mind)
I put it there because nobody likes wasting a revive on catatonics

2017-06-14 23:55 UTC, Robustin commented on code/game/gamemodes/gang/gang_items.dm
> +			var/overall_damage = total_brute + total_burn + H.getToxLoss() + H.getOxyLoss()
Its how defibs handled it, so that you get some of your original damage back (i.e. severe burns if you burnt to death)

2017-06-14 23:58 UTC, Robustin commented on code/game/gamemodes/gang/recaller.dm
> +	M.update_icons()
To remove the associated action button

2017-06-14 23:59 UTC, Robustin commented on code/game/gamemodes/gang/vigilante.dm
> +	attack_self(usr)
Not clear about which comment

2017-06-15 00:21 UTC, Robustin commented on code/game/gamemodes/gang/vigilante.dm
> +			if(I.type == G.outer_outfit && I.armor["bullet"]>=35)
but a lot of these aren't a unique type, they're ordinary clothes that got their armor modified when they popped out of the gangtool

2017-06-15 00:24 UTC, Robustin commented on code/game/gamemodes/gang/gang.dm
> +	if((alive <= (GLOB.player_list.len * 0.45)) && (SSshuttle.emergency.mode == SHUTTLE_RECALL || SSshuttle.emergency.mode == SHUTTLE_IDLE || (SSshuttle.emergency.timeLeft(1) > (SSshuttle.emergencyCallT
That's an uncalled shuttle right? The issue before this PR was that it would only trigger if someone had already called the shuttle.

2017-06-15 17:14 UTC, Steelpoint commented
I've come to really dislike the Gang varient with Security.

Vig Gang is fine since its just a team death match with but Sec Gang is just a far worse varient of Rev. It quickly turns into Revs but with more guns and the ability for the gangs to convert security officers and the captain.

2017-06-15 18:22 UTC, Robustin commented
@Steelpoint 

That was the idea with the original PR but a botched rollout turned plenty of people off.

I think leaving it split is a good idea so people can get a feel for the two types and then after sufficient tweaks and Kev's changes, after a few months maybe we can revisit.

2017-06-15 18:45 UTC, KorPhaeron commented
I would rather just remove gang than have another mode about security running internment camps in the rotation

2017-06-15 18:55 UTC, Robustin commented
Well at this point a single variable can decide that, players preferred a mix, you want sec gone period.

Going against you AND the gang-hater maintainers seems like suicide so I'll change it back to vigilantes being 100% if that's how you feel. 

I was open to mixing them because I felt decentralized influence allowed the average foot soldier a chance to fight back against security whereas before your only option was hoping nobody competent signed up for sec or relying on slips to get you sec weapons/access and snowballing from there.

2017-06-15 21:14 UTC, optimumtact commented
those damn gang hating maintainers

2017-06-16 02:29 UTC, Cyberboss commented
Oranges uses sarcasm, but it's true

On Jun 15, 2017 6:54 PM, "oranges" <notifications@github.com> wrote:

> those damn gang hating maintainers
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/27954#issuecomment-308867631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywem24X9LpDY3PBWYmPPXTIf8q_lXZks5sEZ7EgaJpZM4Nt1Fv>
> .
>

2017-06-16 04:07 UTC, Robustin commented
I'm not hating on them its just a fact of life. Nobody is going to merge this against Kor's wishes.

2017-06-16 06:04 UTC, octareenroon91 commented
The Automated Announcement System is announcing latejoiners' jobs as 'Vigilante':
![screenshot_2017-06-16_01-01-35](https://user-images.githubusercontent.com/12420976/27213994-b41bf6f6-522f-11e7-9b2b-b8993358c1f2.png)

2017-06-16 12:58 UTC, Cyberboss requested changes

2017-06-16 12:58 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +	if(prob(100)) // 100% chance for Vigilantes to appear in place of security
Remove this

2017-06-16 12:58 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		target_armory = locate(/area/ai_monitored/security/armory in GLOB.sortedAreas)
I don't understand how this is compiling but what I meant was: `target_armory = locate(/area/ai_monitored/security/armory) in GLOB.sortedAreas`

2017-06-16 12:58 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	tags = list()
Minor thing, move this 2 lines down, after the qdel check

2017-06-16 12:58 UTC, Cyberboss commented on code/game/objects/items/weapons/clown_items.dm
> +			to_chat(user, "<span class='notice'><b> \The [tag.territory] is no longer under gang control. Keep this area clean for additional influence.</b></span>")
There's a space at the beginning of the line

2017-06-16 12:58 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> -		M.forceMove(get_turf(src))
This should have stayed as-is, you never know why someone was failed to be buckled, what if they were buckled to a chair? They'd be forceMove'd out of it

2017-06-16 12:58 UTC, Cyberboss commented on code/modules/mob/dead/new_player/new_player.dm
> +/mob/dead/new_player
Fix this file, I know it's stupid

2017-06-16 17:58 UTC, Robustin commented on code/game/objects/structures/manned_turret.dm
> -		M.forceMove(get_turf(src))
Them not being on the proper turf was causing . = FALSE and so nobody could mount the gun

2017-06-17 00:06 UTC, Kholdgrave commented
Really loving the new gang with vigilantes and non-sec, it's much more different then what we have in every other round and is a breath of fresh air in what feels like stagnant game modes. 

Only thing I'd like to add suggestion wise, is giving Vigilantes some kind of B&E tool that they could purchase. Unlike gang members who can just murder whoever for access, Vigilantes have to rely on what their department access can get them or what they get off a gang member, which leaves them very limited when it comes to options for attacking gang strongholds without proper access or tools.

Nothing major, maybe something like a syndie toolbox with gloves and tools, or C4 if you're feeling generous. Other then that, I think mode is pretty great, only major issue I have is the gang's no longer obtaining influence at certain points but that's not a balance issue.

2017-06-17 20:05 UTC, Cyberboss commented on code/game/gamemodes/gang/vigilante.dm
> +	attack_self(usr)
don't call attack_self, refactor what's in attack_self into a unique proc and call that

2017-06-17 20:06 UTC, Cyberboss commented on code/game/gamemodes/gang/recaller.dm
> +	M.update_icons()
Does linked_action.Remove(M) not do that? because it should

2017-06-17 20:08 UTC, Cyberboss commented on code/game/gamemodes/gang/gang_items.dm
> +		qdel(M)
https://github.com/tgstation/tgstation/blob/master/code/game/atoms_movable.dm#L206 if that's happening you need to figure out why

2017-06-17 20:50 UTC, octareenroon91 commented on code/game/gamemodes/gang/vigilante.dm
> +			if(I.type == G.outer_outfit && I.armor["bullet"]>=35)
You can still do `istype(I, G.outer_outfit)` for the first condition, instead of pulling the relevant typepath vars.

2017-06-18 02:44 UTC, Cyberboss requested changes
Address the issue in #27985

2017-06-19 17:26 UTC, Cyberboss commented on code/game/gamemodes/gang/gang.dm
> +		priority_announce("Excessive costs associated with lawsuits from employees injured by Security and Synthetics have compelled us to re-evaluate the personnel budget for new stations. Accordingly, th
do it

2017-06-23 14:13 UTC, Cyberboss requested changes
Do what I said about attack_self

2017-06-26 05:05 UTC, Cyberboss commented
@Robustin

2017-06-26 14:20 UTC, KorPhaeron commented
Let me know when you're back

2017-06-26 14:20 UTC, closed without merging

2017-06-26 14:27 UTC, Cyberboss commented
Let ME know

2017-06-26 20:57 UTC, calzilla1 commented
Baby come back, any kind of fool could see
There was something in everything about you
Baby come back, you can blame it all on me
I was wrong, and I just can't live without you