Adds some more syndicate equipment.
tgstation/tgstation pull request #28046
Opened 2017-06-03 21:18 UTC by WJohn

Fancy syndicate combat attire with TONS OF TACTICAL POCKETS (designer clothing, these are not actual pockets).
![](http://i.imgur.com/YKmiuiI.png)

These are not possible to get by normal means, and are purely cosmetic.

Also tweaks a bit of flavor text and equipment for upcoming battlecruiser fun.

2017-06-03 21:24 UTC, ChangelingRain commented on code/game/objects/structures/ghost_role_spawners.dm
> +	flavour_text = "<font size=3>You are a crewmember aboard the syndicate flaship: the SBC Starfury. <span class='danger'><b>Your job is to follow your captain's orders, maintain the ship, and keep the
flaship

2017-06-04 00:54 UTC, PKPenguin321 commented
they look like they're crouching

2017-06-04 01:19 UTC, Durkel commented
Now all you need is a fedora and a flame t-shirt to go will all those pockets.

2017-06-04 02:40 UTC, ShadowDeath6 commented
Bend those knees

2017-06-04 03:07 UTC, CosmicScientist commented
Big chest? High hips? That top is weird.

2017-06-04 03:09 UTC, WJohn commented
The one on the left is a girl so it looks a bit off, but the chest/legs are at the same height as any typical pants/shirts are.

2017-06-04 03:26 UTC, KingPhilipIII commented
If you're doing these sprites, you should really give nukies something like this instead of making the chest rig the same thing as the explorers webbing.

2017-06-04 03:42 UTC, WJohn commented
I'm not even the one who did the chest rig recolor, that was kor, then either kevinz or steelpoint who made a grey version.

2017-06-04 05:38 UTC, Tacolizard commented
t o p h e a v y o r b o t t o m h e a v y

2017-06-04 06:34 UTC, CosmicScientist commented
>one on the left is a girl
>beard
The autogenerator is not conforming to my views!

2017-06-05 16:23 UTC, Cyberboss requested changes
DME

2017-06-05 18:24 UTC, WJohn commented
IT FINALLY WORKED.

2017-06-05 18:50 UTC, merged