[WIP] Makes overload respect override immunity and broken +  potentially adding to the blacklist
tgstation/tgstation pull request #28314
Opened 2017-06-10 17:33 UTC by Supermichael777

:cl:
balance: Machine overload now has a blacklist shared with override. Both can no longer act on broken machines.
fix: The override blacklisting now actually works.
/:cl:

Currently machine overload and machine override can target every type of obj/machine bar one: the cover of the portable turret. Overload can even target that. Now this might sound like working as intended but a long list of things are machines, including rather ubiquitous pipes and holo-pads. This pr will act as a list of things it shouldn't be able to blow up by community suggestion. I'm almost certainly going to add transit tubing and most of the atmos/disposals equipment but I want some feedback on what else should go in as well as HEALTHY DEBATE about whether each suggestion is freeze friendly.

Things that logically should not explode + community input:

- [x] anything with status BROKEN

- [ ] atmos pipes and manual equipment

- [ ] disposals pipes

- [ ] transit tubing

for your consideration
 
1. Every kind of atmos machine (vents pumps, filters, etc.)
2. Disposals machinery (the kind that goes on the terminals)
3. Holopads
4. Suggestions

2017-06-10 18:35 UTC, Shadowlight213 commented
Never forget when the singularity was a machine and you could override it.

2017-06-10 18:41 UTC, Tacolizard commented
Holopads should totally be explodeable. They're machinery made specifically to be AI controllable

2017-06-10 18:49 UTC, Repukan commented
Holopads should remain explode-able.

Also I feel this would be better as a forum post as well.

2017-06-10 19:04 UTC, Supermichael777 commented
Why the fuck is this a proc? that's trash!

2017-06-10 19:56 UTC, Cyberboss requested changes

2017-06-10 19:56 UTC, Cyberboss commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +		if(stat & BROKEN)
Should probably use is_operational()

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +	var/can_be_overridden = 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +		return 1
TRUE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +		return 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
> +	can_be_overridden = 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/binary_devices/valve.dm
> +	can_be_overridden = 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/binary_devices/valve.dm
> +	can_be_overridden = 1
TRUE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/components_base.dm
> +	can_be_overridden = 1
TRUE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
> +	can_be_overridden = 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
> +	can_be_overridden = 0
FALSE

2017-06-10 19:56 UTC, Cyberboss commented on code/modules/atmospherics/machinery/components/unary_devices/tank.dm
> +	can_be_overridden = 0
FALSE

2017-06-10 20:15 UTC, lzimann commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	if(!M.can_be_overridden())
Why is this can_be_overriden a proc?

2017-06-11 04:38 UTC, Supermichael777 commented
i have lost all drive to make this better

2017-06-11 04:38 UTC, closed without merging