Gives the captain a somewhat robust golden fountain pen.
tgstation/tgstation pull request #28382
Opened 2017-06-12 09:29 UTC by Expletive

:cl:
add:  The Captain now starts with a gold fountain pen in their PDA. 
/:cl:
Sprite: 
![cap-pen](https://user-images.githubusercontent.com/9963278/27027566-ce1a52e4-4f16-11e7-9245-a605cb361047.png)

Ink Comparison:
![cappen](https://user-images.githubusercontent.com/9963278/27027527-a2a8c7da-4f16-11e7-9bda-26b316cf3ba0.PNG)

2017-06-12 11:26 UTC, GunHog commented
Neat, although the sprite could be improved a little.

2017-06-12 14:31 UTC, Xhuis commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
"Damn it, someone forgot a knife. How are we gonna cut this pizza now?"
Captain waltzes up and whips out his pen.
"Step aside, gents."

2017-06-12 16:34 UTC, Time-Green commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
This would also means you would be able to use a whetstone on the pen and make it an actual weapon

2017-06-12 16:55 UTC, Anonmare commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
@Time-Green Feature

2017-06-12 16:58 UTC, PKPenguin321 commented
Throwing star pen hell yeah

2017-06-12 18:47 UTC, ExcessiveUseOfCobblestone commented
The pen is mightier than the sword.

2017-06-12 21:58 UTC, Jalleo commented
Make it a darker yellow on paper its too sharp. More a dark gold if possible. Wrong screen right now and that will burn eyes.

2017-06-12 21:59 UTC, Jalleo commented
Ignire my last statement if you read it.

2017-06-13 13:17 UTC, improvedname commented
Make the crate costs 1000 because fountain pens are expensive and only for the rich

2017-06-13 13:52 UTC, lordpidey commented
Be sure to test this on multiple versions of windows.

2017-06-13 13:56 UTC, RemieRichards commented on code/modules/paperwork/pen.dm
> +	if(unique_reskin)
```
else
    ..()
```
So that it can still work as an Uplink.

2017-06-13 13:56 UTC, lordpidey requested changes

2017-06-13 13:56 UTC, lordpidey commented on code/game/objects/items/devices/PDA/PDA.dm
> +		inserted_item = new inserted_item(src)
Perhaps you should add a variable "pen_type".  The way you're using it, inserted_item is used as both a path AND an item.

2017-06-13 13:57 UTC, RemieRichards commented on code/game/objects/items/devices/PDA/PDA.dm
> +		inserted_item = new inserted_item(src)
@lordpidey This is a very common pattern we use.
The var will always be either null or the object (as expected) as if it is a path it replaces itself during New/Initialize/whatever

2017-06-13 14:00 UTC, RemieRichards commented
If the font is a stable one on windows, perhaps change ```SIGN_FONT``` to it too, since it's a better looking signature font than Times New Roman.

2017-06-13 15:09 UTC, DoctoreMad commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
>Sharpened Fountain Pen

**For fuck sakes**

2017-06-13 15:41 UTC, GunHog commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
EMERGENT GAMEPLAY

2017-06-13 16:00 UTC, Time-Green commented on code/modules/paperwork/pen.dm
> +	sharpness = IS_SHARP
Because being able to decapitate someone with a pen is a feature

2017-06-14 20:11 UTC, improvedname commented
Pen=fireproof
>grab oak skin
Fireproof wood fountain pen

2017-06-14 20:19 UTC, GunHog commented
Easy fix, remove fireproofing if wood skin selected.

2017-06-15 14:00 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +			..()
`. = ..()`

2017-06-15 14:01 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +		if(src && choice && !user.incapacitated() && in_range(user,src))
`!QDELETED(src)`

2017-06-15 14:01 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +			if(skins[choice] == null)
just `!skins[choice]` will do here.

2017-06-15 14:02 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +	var/unique_reskin = 1
`TRUE`

2017-06-15 14:03 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +		var/choice = input(user,"Choose the finish for your pen.","Reskin Pen") in skins
Instead of adding a "Cancel" option to the list, you can do `input() as null|anything in skins`. Hitting the cancel will return null.

2017-06-15 14:05 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +	if(unique_reskin)
The unique reskin should probably be in Alt Click, it will be in line with guns that allow reskins.

2017-06-16 01:51 UTC, lzimann commented on code/modules/paperwork/pen.dm
> +			if(skins[choice] == null)
This check is not necessary.

2017-06-17 01:12 UTC, merged