Adds onions
tgstation/tgstation pull request #28414
Opened 2017-06-13 02:48 UTC by QualityVan

:cl: QualityVan
add: The botany vending machine now has a stock of onion seeds
/:cl:

Adds onions and red onions, with sprites by WJohnson.
Onions are essentially unexceptional but can be put through the chef's processor to make onion rings. More recipes/mutations to come maybe???
Red onions contain a weak blinding agent which is mostly good for being annoying and which doesn't cause any lasting damage.

![hydroponics](https://user-images.githubusercontent.com/3839620/27063693-2c8f4d52-4fc1-11e7-86cc-cf8d9a2e06cf.png)
All the onion-y bits.

2017-06-13 02:53 UTC, Expletive commented
Make them slice-able with a knife, so you have have proper sandwiches.

2017-06-13 02:56 UTC, Jordie0608 commented
What if onions mutate into ¡¿Español?! onions which make you speak spanish when eaten?

2017-06-13 03:04 UTC, Niknakflak commented
Make players cry when they cut them. Force it. Literally hardcode that bitch

2017-06-13 03:06 UTC, WJohn commented
Aw, I wanted the pink onions to contain fluoro acid. Oh well.

2017-06-13 03:27 UTC, QualityVan commented
Gimme sprites for sliced onions and sure.

2017-06-13 04:26 UTC, optimumtact commented
do they have layers like ogres?

2017-06-13 05:06 UTC, Anonmare commented
Lizards are like onions.

They smell, make you cry, if you leave 'em out in the sun, they get all brown, an' start sproutin' little white hairs...

2017-06-13 05:16 UTC, Bawhoppen commented
We need more simple things like this, not everything has to be ultimate OP meme items

2017-06-13 06:49 UTC, FantasticFwoosh commented
When applied to the neck slot

> I held back adding more plants because not long ago i and maybe this thread would have been screamed at for botany-creep.

2017-06-13 06:52 UTC, TehZombehz commented
Thank you. I can now make french onion dip.

2017-06-13 06:57 UTC, Anonmare commented
@FantasticFwoosh Finally I can be an overly French Frenchie and Hon-Hon at all the rosbifs

2017-06-13 07:52 UTC, improvedname commented
Next up garlic

2017-06-13 07:53 UTC, improvedname commented
FUCK TEARJUICE GOT IN MY EYES CAPTAIN

2017-06-13 14:54 UTC, DoctoreMad commented
Garlic is already in /vg/ just go fetch it

2017-06-13 17:09 UTC, Tacolizard requested changes

2017-06-13 17:09 UTC, Tacolizard commented on code/modules/hydroponics/grown/onion.dm
> +	desc = "These seeds grow into onions."
ogres are like onions

2017-06-14 13:33 UTC, banthebantz commented
they need layers and they need to make people cry

2017-06-14 17:05 UTC, rsanchezbalo commented
![regular_onion](https://user-images.githubusercontent.com/1846317/27145000-3a4df2da-5134-11e7-8282-5c6eaf57890a.png)
![purple_onion](https://user-images.githubusercontent.com/1846317/27145001-3a5450a8-5134-11e7-874b-5f39616d2204.png)

Made some onions slices, im not the best at spriting tiny icons :D

2017-06-15 13:57 UTC, lzimann commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		return 1
`TRUE`

2017-06-16 03:14 UTC, nicbn commented
Onions + computer frame = syndicate deep web computer?

2017-06-16 07:02 UTC, Bawhoppen commented
Why do we have to keep adding new crazy meme weapons to science/antags when we can add things like this?

2017-06-16 17:05 UTC, octareenroon91 commented
>cry from cutting onion

Throw transparent smoke clouds of tear juice maybe?

2017-06-16 21:22 UTC, merged