[DNM] [WIP] Pocket protectors, which are so nerdy they completely break the game!
tgstation/tgstation pull request #28419
Opened 2017-06-13 05:55 UTC by Expletive

:cl:
add: Nerds on the station will be pleased to know they now have pocket protectors.
/:cl:

sprite: ![pocketprotector](https://user-images.githubusercontent.com/9963278/27067912-14dcd764-4fc2-11e7-9cc9-ef3aeec93a5b.png)

Pocket protectors are great. But this PR completely breaks the game for no discernable reason. If you can figure it out, you'll win the grand prize! I have no idea why this doesn't work when master does.  Oranges and MSO were similarly stumped.

2017-06-13 05:57 UTC, ExcessiveUseOfCobblestone commented
in what way does it break the game

2017-06-13 06:00 UTC, ExcessiveUseOfCobblestone requested changes
I probably found it.

2017-06-13 06:00 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/under/accessories.dm
> +	pockets = /obj/item/clothing/accessory/pocketprotector/full
/obj/item/weapon/storage/internal/pocket/pocketprotector/full/

2017-06-13 06:00 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/under/accessories.dm
> +	pockets = /obj/item/clothing/accessory/pocketprotector/cosmetology
/obj/item/weapon/storage/internal/pocket/pocketprotector/cosmetology/

2017-06-13 06:02 UTC, Expletive commented
Oh, damn. I am an idiot. Created an infinite loop.

2017-06-13 08:22 UTC, optimumtact commented
good spot cobby

2017-06-13 16:37 UTC, ShadowDeath6 commented
I think the protector's sprite could be a bit lower, it's kind of entering the neck area on a lot of the jumpsuit sprites

2017-06-13 23:07 UTC, tortellinitony commented
Eww, gradient sprite.

2017-06-14 05:10 UTC, octareenroon91 commented
I'm curious why roboticists are excluded here.

2017-06-17 20:12 UTC, Cyberboss approved these changes

2017-06-17 20:13 UTC, merged