Changes default scaling mode to Point Sampling
tgstation/tgstation pull request #28448
Opened 2017-06-13 22:54 UTC by Tacolizard

:cl: Tacolizard
tweak: Point Sampling is now the default scaling mode
/:cl:

Most people who play this game do so using the stretch-to-fit option, because most people don't happen to have a monitor at a resolution to make a perfect scaling option fit properly. When using stretch-to-fit, the game looks strange, to say the least. Setting the scaling mode to point sampling is perfect because people who play at perfect scaling modes won't notice a difference, and everyone else will enjoy better looking scaling.

2017-06-13 22:56 UTC, DoctoreMad commented
This isn't actually bad and I could support it but muh quality metaclub

2017-06-13 22:56 UTC, Tacolizard commented
what are you talking about?

2017-06-14 00:36 UTC, bgobandit commented
thank fucking god

2017-06-14 07:10 UTC, kevinz000 commented
on mine nearest neighbor is best. It's sharp. The other two are blurry as fuck and hurts my eyes. Yes, I'm using stretch to fit. Ffs tacolizard.

2017-06-14 07:51 UTC, RemieRichards commented
Disagree with this, just pick the one you like (I know there's been some issues with them not saving, but that's no reason to change everyone else's default too) and stick with it.

The default was picked as it was the previous behaviour, which is how we usually do things when it's not a flat upgrade for all (as has been mentioned, point-sampling looked so horrible to some that Lummox had to add the old setting back as an option)

2017-06-14 09:19 UTC, MrStonedOne commented
Point sampling is an attempt to bridge the gap between nearest neighbor and linear, its a nice attempt, but NN is pure, it doesn't change the pixels just dupes or excludes them, and linear and PS both change the pixels to try to make them blend in.

2017-06-14 13:20 UTC, bgobandit commented
Can it at least save prefs on the client because it is very annoying to constantly switch it to point sampling so the game doesn't look terrible

2017-06-14 14:41 UTC, RemieRichards commented
it does save, but as i said, thats bust.

2017-06-14 16:46 UTC, Cyberboss requested changes
This only changes the checkbox, you need to change the default in the .dmf

2017-06-14 17:33 UTC, dannno commented
I just wish that which ever option you picked would stay selected as a preference and you wouldn't have to re-select it every single time you launch the game, if it isn't the default. for fuck's sake.

2017-06-14 18:11 UTC, Tacolizard commented
I kinda knew that this only changed the textbox, so I'm just gonna close this because it won't really change anything.

2017-06-14 18:11 UTC, closed without merging

2017-06-14 20:14 UTC, MrStonedOne commented
I'll work on a hacky fix for preferences.