Paper frames, but with new sprites.
tgstation/tgstation pull request #28452
Opened 2017-06-14 00:11 UTC by Expletive

:cl:
add: Paper frames can be created using wood and paper, and can be used to create decorative structures.
add: Natural paper can now be crafted 
add: KorPhaeron can now start a maid cafe, if they so desire.
/:cl:

I gave spriting another shot, since I was asked to. These sprites smooth properly, but are probably still crap. I opened a new PR, since the old one had things I've already atomized out into PRs that have since been merged.

![scrnshot1](https://user-images.githubusercontent.com/9963278/27110031-45011484-505b-11e7-909a-318d0bfcf60a.png)

2017-06-14 00:19 UTC, QualityVan commented
horizontal door looks weeeeeeird

2017-06-14 00:26 UTC, bgobandit commented
I'm confused about what these are for

2017-06-14 00:26 UTC, KorPhaeron commented
It says in the changelog

2017-06-14 00:27 UTC, bgobandit commented
Yeah but the photo doesn't really explain what "decorative structures" are or why this would make a maid cafe

2017-06-14 00:28 UTC, KorPhaeron commented
https://upload.wikimedia.org/wikipedia/commons/e/e1/Takamatsu-Castle-Building-Interior-M3488.jpg

2017-06-14 00:39 UTC, Repukan commented
Slibbery slobe

2017-06-14 01:06 UTC, WJohn commented
These are much improved, good work.

Not a fan of the horizontal doors, but that's mostly since our doors don't do that, they're all the same direction.

2017-06-14 04:08 UTC, dannno commented
Kor is not in charge of the Maid Cafes, so if you could please fix your changelog to say kor is a stupid idiot

2017-06-14 08:59 UTC, Alek2ander commented
flammable - :white_check_mark: 
:ok_hand:

2017-06-14 21:17 UTC, nicbn commented
They look too thick, maybe make it 1-dir like the thin windows?

2017-06-15 15:31 UTC, Iatots commented
They shouldn't smooth, the whole point is that they are made of panels. It would be better for the doors too, since without smoothing you could have a wall flip 90° with a wrench and screwdriver.

2017-06-16 16:58 UTC, octareenroon91 commented
Paper windows seem to be transparent. Why are they transparent?

Also I think 'divider' or 'room divider' might have more common usage than 'separator'

2017-06-16 20:21 UTC, Bawhoppen commented
we need something that allows light to pass but is still dense you're right

2017-06-16 22:55 UTC, Expletive commented
@octareenroon91  They are not transparent. I just used xray eyes fr the screenshot.

2017-06-17 20:03 UTC, Cyberboss requested changes

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +new /datum/stack_recipe("paper frame door", /obj/structure/mineral_door/paperframe, 3, one_per_turf = 1, on_floor = 1, time = 10 )))
TRUE for one_per_turf and on_floor

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/mineral_doors.dm
> +	set_opacity(0)
FALSE

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/mineral_doors.dm
> +	set_opacity(1)
TRUE

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/mineral_doors.dm
> +	set_opacity(0)
FALSE

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/mineral_doors.dm
> +	queue_smooth_neighbors(src)
Shouldn't this be Destroy() instead?

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +					playsound(loc, 'sound/items/Welder2.ogg', 50, 1)
playsound(src, ...

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +	playsound(loc, 'sound/effects/Glassknock.ogg', 50, 1)
playsound(src, ...

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +	playsound(loc, 'sound/effects/Glassknock.ogg', 50, 1)
playsound(src, ...

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +	paper = mutable_appearance('icons/obj/smooth_structures/paperframes.dmi',icon_state = "paper", layer = ABOVE_OBJ_LAYER - 0.1)
Assign these at their definition

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		qdel(I)
if debris only contains items, just do QDEL_LIST(debris)

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		return
Remove this check, attack_hand already verifies that before it's called

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		playsound(loc, "pageturn", 50, 1)
playsound(src, ...

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		playsound(loc, hitsound, 50, 1)
playsound(src, ...

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		set_opacity(0)
FALSE

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		set_opacity(1)
TRUE

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +			fire_act(W.is_hot())
I think weldingtool/is_hot returns FALSE if it's off. Remove the weldingtool specific stuff

2017-06-17 20:03 UTC, Cyberboss commented on code/game/objects/structures/window.dm
> +		if(istype(W, /obj/item/weapon/paper) && obj_integrity < max_integrity)
Make these 2 lines 1

2017-06-18 11:32 UTC, LarissaMayrink commented
>maid cafe barsigh added
>maid suit added to the barman wardrobe
>weeb paperwalls

2017-06-18 11:33 UTC, LarissaMayrink commented
Its a lube covered slope, we are way beyond a slippery one

2017-06-18 14:42 UTC, Cyberboss approved these changes

2017-06-18 14:45 UTC, merged