Replaces a sleep with a timer in late joining
tgstation/tgstation pull request #28476
Opened 2017-06-14 22:14 UTC by lzimann

2017-06-14 22:14 UTC, Robustin commented
I was gonna say remove it because its redundant but whatever works.

2017-06-14 22:52 UTC, Robustin commented
Uh I went ahead and did your change and I'm getting:

Runtime in timer.dm,234: Cannot modify /mob/dead/new_player/proc/AddEmploymentContract.active_timers. proc name: New (/datum/timedevent/New)

2017-06-15 00:04 UTC, lzimann commented
I'll test it when I get home later

2017-06-15 02:22 UTC, Cyberboss requested changes

2017-06-15 02:22 UTC, Cyberboss commented on code/modules/mob/dead/new_player/new_player.dm
> +		addtimer(CALLBACK(.proc/AddEmploymentContract, humanc), 30)
addtimer(CALLBACK(src, .proc/AddEmploymentContract, humanc), 30)

2017-06-15 02:32 UTC, lzimann commented on code/modules/mob/dead/new_player/new_player.dm
> +		addtimer(CALLBACK(.proc/AddEmploymentContract, humanc), 30)
Oh right, forgot about the first arg lol

2017-06-15 12:44 UTC, Cyberboss requested changes
Line... Beginnings???

2017-06-15 13:14 UTC, closed without merging