Adds the Construction Nuke
tgstation/tgstation pull request #28494
Opened 2017-06-15 20:03 UTC by Robustin

Admin-only. It was sacrificed so that the dance machine could live - but its back!

90% for non-evil purposes. The other 10% will trigger an early shuttle call. 

The 2nd half of this video should prove informative:

https://www.youtube.com/watch?v=QupS19-Kxt8&feature=youtu.be

2017-06-15 20:10 UTC, Cyberboss requested changes

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	..()
. = ..()

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	if (!src || QDELETED(src))
jsut QDELETED

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	if (!src || QDELETED(src))
just QDELETED

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	addtimer(CALLBACK(src, .proc/boom), 100)
use TIMER_CLIENT_TIME

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	spawn_atom_to_turf(/obj/effect/temp_visual/explosion, startpoint, 1, FALSE)
just use new

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +			spawn_atom_to_turf(/obj/effect/temp_visual/fire, T, 1, FALSE)
new

2017-06-15 20:10 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +			spawn_atom_to_turf(/obj/effect/temp_visual/fire, T, 1, FALSE)
new

2017-06-15 20:17 UTC, lordpidey commented on code/game/machinery/engi_adv.dm
> +	var/static/list/possible_payloads = list("wood","sand","ice","mining","silver","gold","bananium","abductor","desolation", "plasma","uranium","bluespace","diamond","plasteel","safety","titanium","pla
Won't the comma at the end here cause problems?  Yet it still compiled.  *shrug*

2017-06-15 20:17 UTC, lordpidey commented
Did you remove the metal slug sprites?

2017-06-15 20:19 UTC, Robustin commented
Yes, it our super generic flash of circular light now.

😢

2017-06-15 20:20 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	var/static/list/possible_payloads = list("wood","sand","ice","mining","silver","gold","bananium","abductor","desolation", "plasma","uranium","bluespace","diamond","plasteel","safety","titanium","pla
its a null entry, remove it

2017-06-15 20:34 UTC, kevinz000 commented
construction nuke aka make the entire station ugly as fuck.
better let people who use it be valid.
also >adminspawn
that's what they (including me) all say until it becomes a part of the game
:-1:

2017-06-15 20:34 UTC, kevinz000 commented
if i wanted to mass replace turfs i'd improve sdql and just run a query.

2017-06-15 20:53 UTC, DoctoreMad commented
If the Hillary Clinton won. However I think that...

2017-06-15 21:39 UTC, Kromgar commented
The greatest grief of all. Turn everything to plasma and just light a wall. The entire station is immediately going up in flames

2017-06-15 21:54 UTC, Robustin commented
Let me tell @Kromgar its beautiful to watch. Something changed in my more recent tests compared to a few months ago though, neither of the "bad" walls are as lethal as they used to be - both can be survived until evac.

Also @kevinz000 that meme needs to die, it only applies to shit that gets trotted out consistently by admins (i.e. catgirls). Even the stuff that was added with the intention of making it admin-tradeable have been exceedingly rare.

2017-06-15 22:10 UTC, DoctoreMad commented
>Even the stuff that was added with the intention of making it admin-tradeable have been exceedingly rare.

Well what is the stuff that has been added solely to be admin-tradeable?
Maybe if someone just made a repository of items that never spawned without adminhelp somewhere maybe you'd see traitor TCtrades/chaplain prayers trying to invoke them.

2017-06-16 02:06 UTC, Bawhoppen commented
Adding in admin only meme stuff like this will only encourages the portion of our admins who like to fuck over and ruin rounds because they're bored to use things like this (see why we removed ragin mages)

2017-06-16 03:08 UTC, nicbn commented
> The greatest grief of all. Turn everything to plasma and just light a wall. The entire station is immediately going up in flames
Ok now I want it

2017-06-16 04:17 UTC, Robustin commented
I mean ultimately the players decide how to use one, so it takes a beautiful collaboration of grief between crew and admin. 

Plus there's already a massive arsenal of "things admins can use to fuck everyone over". 

Plus at the end of the day this thing is 90% fun, you can make a sexy silver station, a hardened plastitanium station, an abductor station, wood station, etc.

2017-06-16 07:25 UTC, kevinz000 commented
once again if i want to have this 90% fun i'll just mass proccall changeturf =|

2017-06-16 08:28 UTC, kevinz000 commented
@Bawhoppen my issue is this is already possible with a simple tweak to sdql to detect if something is a typepath instead of a string and this is going to encourage possible addition into the game later on.

2017-06-16 17:55 UTC, Robustin commented
1) It has multiple effects that make it a much more interesting experience, including crew choice - whereas admin mass editing is just instant "ur shit changed".

2) Not every admin wants to risk breaking the round with a mass proccall to all turfs, or even knows how to do such a thing.

2017-06-17 19:35 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		priority_announce("Catastrophic event detected: crisis shuttle protocols activated - jamming recall signals across all frequencies")
"Jamming recall signals" doesn't sound lore friendly

2017-06-17 20:59 UTC, Cyberboss requested changes

2017-06-17 20:59 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	for(var/I in spiral_range_turfs(range, startpoint))
Use the tick_checked parameter

2017-06-17 21:03 UTC, Cyberboss requested changes

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		M << 'sound/machines/Alarm.ogg'
M.playsound_local(get_turf(M), ...

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		icon_state = "nuclearbomb1"
This line in update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		icon_state = "nuclearbombc"
This line in update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		icon_state = "nuclearbomb2"
This line in update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		icon_state = "nuclearbomb1"
This line in update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		icon_state = "nuclearbomb2"
This line in update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	if (QDELETED(src))
&& Adjacent(usr)

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	if (QDELETED(src))
&& Adjacent(usr)

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	dat += "<b><A href='?src=\ref[src];action=activate'>[bomb_set ? "DEACTIVATE" : "ACTIVATE"]</A><b><br>"
Didn't close the <b> properly

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +					icon_state = "nuclearbomb3"
use update_icon

2017-06-17 21:03 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +	var/detonation_timer = null
remove the `= null`

2017-06-18 12:22 UTC, kevinz000 commented
so you're saying this thing isn't going to break rounds :^)

2017-06-18 17:51 UTC, Robustin commented
I held lots of round-breaking events as admin and never got a complaint about any of them?

You know why? I only used it when things were relatively calm and I would let the heads of staff decide if they were up for it.

Emergent gameplay motherfucker.

2017-06-18 19:39 UTC, Robustin commented on code/game/machinery/engi_adv.dm
> +		M << 'sound/machines/Alarm.ogg'
Maaaan this is how every nuke sound is handled. Plus with any playsound unless you tweak all the arguments right any sound that lasts more than a second sounds really fucking weird due to the pitch variance and pressure/distance volume.

2017-06-19 05:38 UTC, Bawhoppen commented
Spawning 400 simple mobs on the derelict isn't intrusive, but isn't interesting either

2017-06-19 15:40 UTC, Robustin commented on code/game/machinery/engi_adv.dm
> +		priority_announce("Catastrophic event detected: crisis shuttle protocols activated - jamming recall signals across all frequencies")
Not sure why not. This uses a new var I added to the emergency shuttle to prevent any sneaky recall methods from working.

2017-06-19 15:44 UTC, Robustin commented on code/game/machinery/engi_adv.dm
> +	if (QDELETED(src))
why?

2017-06-20 01:29 UTC, Haevacht commented on code/game/machinery/engi_adv.dm
> +		M << 'sound/machines/Alarm.ogg'
so actually test it and get the args right, mate

2017-06-20 02:30 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		M << 'sound/machines/Alarm.ogg'
playsound_local has arguments to ignore atmos

2017-06-23 18:26 UTC, Cyberboss requested changes

2017-06-23 18:26 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +						playsound(src, 'sound/machines/engine_alert2.ogg', 100, 0)
The logic isn't sound here 
```
if(quiet)
    playsound ...
```
??

Either way, cut these 4 lines down to 2 by removing the return and inverting the logic

2017-06-23 18:26 UTC, Cyberboss commented on code/game/machinery/engi_adv.dm
> +		timer_set = 300
Use timer_set =  Clamp(timer_set, 90, 300)

2017-06-25 12:44 UTC, lzimann commented
@Robustin

2017-06-26 14:19 UTC, KorPhaeron commented
Let me know when you're back

2017-06-26 14:19 UTC, closed without merging

2017-09-02 20:06 UTC, PraiseRatvar commented
@Robustin since you're halfback, can you finish this 😉