Vending machines accept space cash.
tgstation/tgstation pull request #28505
Opened 2017-06-16 06:11 UTC by Expletive

:cl:
add: Thanks to the invention of "Bill slots", vending machines can now accept space cash.
/:cl:

I thought it was silly that vending machines couldn't accept space cash, so I've added this.

2017-06-16 06:50 UTC, Jalleo commented
One Dollar from a service borg let you get the zippos then?

2017-06-16 07:12 UTC, Expletive commented
I don't see why not?

2017-06-16 07:19 UTC, improvedname commented
>roundstart

BORG GO SERVICE MODULE AND VEND A DOLLAR FOR ME SO I CAN BUY INSULATED GLOVES

>repeats between rounss

Borg salty in ooc

2017-06-16 09:10 UTC, meeeeme commented
3. Obviously unreasonable or obnoxious orders (collect all X, do Y meaningless task) are a violation of Server Rule 1. The occurrence of such an attempt should be adminhelped and then disregarded.


1. Ordering a cyborg to pick a particular module. without an extreme need for a particular module.   or a prior agreement is both an unreasonable and an obnoxious order.

2017-06-16 10:59 UTC, InsaneHyena commented
They operate by coin slots for a reason.

2017-06-16 13:12 UTC, Cyberboss commented
Would help if cash values actually meant something

2017-06-16 16:43 UTC, octareenroon91 commented
Yes, we might be at the point to offer two tiers of premium item.

2017-06-16 16:56 UTC, FantasticFwoosh commented
Just remove/replace the money printer from service borgs with fake money, or make it a additional emag real money printer. @improvedname

2017-06-17 08:47 UTC, improvedname commented
Doesn't stop you from putting it in the ATM baw

2017-06-17 15:45 UTC, ma44 commented
They make 20 credits, it's not a problem

2017-06-17 19:45 UTC, lzimann commented
@korphaeron

2017-06-17 20:42 UTC, Cyberboss requested changes

2017-06-17 20:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +	bill = null
QDEL_NULL(bill)

2017-06-17 20:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +			coin.loc = loc
remove this line

2017-06-17 20:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +				coin = null
else
    coin.forceMove(get_turf(src))

unindent the to_chat and coin = null lines

2017-06-17 20:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +			bill.loc = loc
Remove this line

2017-06-17 20:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +				bill = null
else
    bill.forceMove(get_turf(src))

unindent the to_chat and bill= null lines

2017-06-17 21:23 UTC, KorPhaeron commented
Cool idea

2017-06-18 16:16 UTC, Really-Good-Soda-Flavor commented
Maybe make it so a 100 credit bill is not the same as a 1 credit bill?

2017-06-19 01:34 UTC, Cyberboss commented
If someone wants to implement proper cash values and prices, they can go right ahead

2017-06-19 01:34 UTC, merged

2017-06-19 01:35 UTC, Cyberboss reviewed
>Postmortem approval