Turns the maid costume's apron into a detachable accessory.
tgstation/tgstation pull request #28527
Opened 2017-06-17 02:11 UTC by Expletive

:cl:
add: Maid Costume aprons can now be detached and reattached to any uniform.
/:cl:

I thought this would be fun. With the apron attached, the Maid costume is identical in appearance, but if you take the apron off, then it's rather plain.

apronless maid costume:
![maidapronless](https://user-images.githubusercontent.com/9963278/27249328-8ceef64e-52c7-11e7-8e2b-4c5065307aca.png)

2017-06-17 02:29 UTC, Cheridan commented
slippery slope

2017-06-17 02:30 UTC, dannno commented
neat idea

2017-06-17 03:57 UTC, Iamgoofball commented
FUCKING

# SLIPPERY

# S L O P E

2017-06-17 05:41 UTC, dannno commented
^imagine being this retarded

2017-06-17 06:15 UTC, Chronitonity commented
Id rather not think about that

2017-06-17 10:00 UTC, Kraseo commented
someone touched an article of clothing and separated it in 2 pieces, slippery slope!!!!!


goofball when's your next pr to remove X thing you don't like for the nth time this year

2017-06-17 19:29 UTC, Cyberboss requested changes

2017-06-17 19:29 UTC, Cyberboss commented on code/modules/clothing/under/miscellaneous.dm
> +	var/obj/item/clothing/accessory/maidapron/A = new /obj/item/clothing/accessory/maidapron(src)
`var/obj/item/clothing/accessory/maidapron/A = new(src)`

2017-06-18 08:26 UTC, Tokiko1 commented
You should fix the inconsistant sleeve lenght of the original sprite while at it.

2017-06-20 13:54 UTC, Cyberboss approved these changes

2017-06-24 20:39 UTC, merged