Refactors PDA cartridge permissions
tgstation/tgstation pull request #28567
Opened 2017-06-18 21:11 UTC by ohnopigeons

Instead of an ungodly amount of vars they are now bit flags with an ungodly amount of #define's.

Also I renamed the detonate var and fixed a thing where the virus sending PDA will no longer return success when the target PDAs aren't detonatable in the first place.

2017-06-18 21:19 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
new line for the if

2017-06-18 21:26 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
Before the if?

2017-06-18 21:35 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
the `difficulty++` should be in a new line

2017-06-18 21:38 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
https://medium.com/@jonathanabrams/single-line-if-statements-2565c62ff492

2017-06-18 21:56 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#control-statements

2017-06-18 22:08 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
That is dumb but okay

2017-06-19 01:44 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
What is dumb is linking an article about languages that use brackets as an excuse for byond.

2017-06-19 01:50 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
For something as simple as an iteration the all-in-one-line being more readable point still stands.

2017-06-19 01:56 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
I don't agree, all in one line is pretty bad for readability, also looks really bad.

2017-06-19 02:00 UTC, Cyberboss submitted a review, later dismissed

2017-06-19 02:00 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/detonatable = 1 // Can the PDA be blown up?
TRUE

2017-06-19 02:00 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +					if (cartridge.access&CART_CLOWN)
Add spaces between `access` `&` and the flag for each of these

2017-06-19 02:00 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA_types.dm
> +	detonatable = 0
FALSE

2017-06-19 02:00 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA_types.dm
> +	detonatable = 0
FALSE

2017-06-19 02:00 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) //if cartridge has manifest access it has extra snowflake difficulty
Spaces again

2017-06-19 02:04 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/PDA.dm
> +					if (cartridge.access&CART_CLOWN)
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#operators-and-spaces

2017-06-19 02:04 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) //if cartridge has manifest access it has extra snowflake difficulty
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#operators-and-spaces

2017-06-19 02:07 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
`if(target.cartridge.access&CART_MANIFEST) difficulty++`
reads like a sentence in natural language, splitting them up is as awkward as a paragraph indent midsentence

2017-06-19 02:11 UTC, optimumtact commented on code/game/objects/items/devices/PDA/PDA.dm
> +					if (cartridge.access&CART_CLOWN)
spaces > nonspaces

2017-06-19 02:20 UTC, optimumtact commented on code/__HELPERS/unsorted.dm
> +/proc/BitCount(bitfield)
you could make this a macro if you were cool and awesome

2017-06-19 02:20 UTC, lzimann requested changes

2017-06-19 02:20 UTC, lzimann commented on code/game/objects/items/devices/PDA/virus_cart.dm
> +			if(target.cartridge.access&CART_MANIFEST) difficulty++ //if cartridge has manifest access it has extra snowflake difficulty
Maybe a mistake, but it returned back to same line.

2017-06-19 05:08 UTC, ohnopigeons commented on code/__HELPERS/unsorted.dm
> +/proc/BitCount(bitfield)
`#define meme(B)	((B) - (((B)>>1) & 46811) - (((B)>>2) & 37449))`
`#define BITCOUNT(B)	((((meme(B)) + ((meme(B))>>3)) & 29127) % 63)`

2017-06-19 06:01 UTC, optimumtact commented on code/__HELPERS/unsorted.dm
> +/proc/BitCount(bitfield)
(B)ig guy

2017-06-19 16:38 UTC, lzimann approved these changes

2017-06-19 18:56 UTC, merged