Ancient Space Station [Space Spawn Ruin]
tgstation/tgstation pull request #28584
Opened 2017-06-19 05:29 UTC by Steelpoint

_An ancient Nanotrasen space station, once thought lost, has quietly reawoken its surviving crew one hundred years after they fell to slumber. Can the surviving crew overcome all odds and survive, or will the cold embrace of the stars become their new home?_

This PR adds a new space spawn ruin, a ancient space station, to the space ruin spawn list. Original idea thread is here for reference: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=11723

Up to three players can spawn in as a engineer, security officer or a scientist (roles are fluff, all have equal access and no unique items) as they attempt to repair, maintain and retake their station back, both from the elements of space, and the hostile invading force of Hivebots. 

-----

The station is divided into three, well technically four, separate stations. Alpha through to Delta.

Map overview, pre-round start: http://i.imgur.com/h1iguUj.jpg

I should note that at the start, the station has no power whatsoever, no lights or anything. 

Alpha station is long gone, Bravo station holds the remains of medbay and atmospherics, Charlie station is where the crew starts in, containing hydro, the kitchen, backup engineering, security and command. Delta station is the research station, but is overrun with Hivebots.

The crew's objective is to get everything going again, get backup power on, get the solar array's online, fix atmo, repair hull breaches, grow food, reclaims RnD and ultimatly fix the station and get it back to its former glory.

-----

Keeping with the theme of 'ancient'. The station's contents are all old and sub-standard to what you would expect off of SS13. 

Some examples.
* The precious few backpacks can only hold four items.
* The laser guns only hold five laser rounds per charge.
* The engineering space suit has a massive slowdown of 4
* The medkit has no health analyser. 
* The armour vest has a slowdown of 1, and the helmet has the same tint a welding mask has (due to degradation).

The station contains two "unique" items not seen anywhere else, the prototype Energy Gun and the prototype Hardsuit.
* The Proto Energy Gun can fire ten laser rounds, or a single stun round.
* The Proto Hardsuit has slightly better melee defence than the armour vest, but it has a slowdown of 3, produces a walking noise when you move in it, and the helmet has a tint value akin to the welding mask.

The theme should that the station should not be a loot pinata. anything on board is a worse version of what you can easily get on SS13 or elsewhere.

:cl: Steelpoint
add: An old Nanotrasen Space Station has quietly reawoken its surviving crew one hundred years after they fell to slumber. Can the surviving crew, using old, broken and out of date equipment, overcome all odds and survive, or will the cold embrace of the stars become their new home?
/:cl:

2017-06-19 05:29 UTC, Armhulen commented
Yay!

2017-06-19 05:30 UTC, Bawhoppen commented
Is this going to be another one of those things where there's only like a couple new gimmick items yet all the walls/tools/other generic junk is the exact same as the station? If so, please no.

2017-06-19 05:31 UTC, Steelpoint commented
I would appreciate any feedback or suggestions, I want the station to be difficult to survive  in, and no one can balance out entire station on their own.

2017-06-19 05:32 UTC, Steelpoint commented
@Bawhoppen I don't see how I could reach your suggestions, how do you change the function of a wall or toolbox to be different that what is on SS13? 

The general idea is that the crew have to make do with a limited and inferior set of tools and equipment. In the long term they can eventually research better items but that would be well after they secure the station .

2017-06-19 05:35 UTC, Bawhoppen commented
Every building I go into IRL is completely different (walls, paint, contents, floors, etc.) than any other building. They need to ATLEAST be aesthetically diverse from just more of the same of reused station content.

2017-06-19 05:35 UTC, Steelpoint commented
Despite everything it is still a Nanotrasen space station. The walls are rusted, the doors are grimy and decayed, but its still the same owner.

2017-06-19 05:36 UTC, DoctoreMad commented
Its a old station, so maybe it can have outdated standards.
I don't care myself, though.

2017-06-19 05:37 UTC, Bawhoppen commented
Is every Mcdonalds you go into the exact same building materials and design? What about Walmart? Pizza hut? Taco bell?

2017-06-19 05:39 UTC, Steelpoint commented
Alternative wall and floor sprites is way, way, on the bottom of my priority list.  If someone sprites and proposes good alt sprites I'll be more than happy to use them.

I'm more tempted to rework the stations RnD to give different, less powerful, items.

I do agree it should have slightly different sprites but that is sadly beyond my abilities.

2017-06-19 05:45 UTC, GunHog commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
"prototype hardsuit" is taken! Please find another name for it. Why not go with "ancient", since that is the type, anyway?

2017-06-19 06:06 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
It's a prototype in a different sense, besides to the crew it's a prototype, not ancient

2017-06-19 06:26 UTC, Chronitonity commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
having two things named the same is still awful though

2017-06-19 07:20 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
They are very visually and mechanically distinct from one another. I can understand the desire but I think in the context I'm presenting the suit, that its name is fine.  

Ancient Hardsuit makes little sense to someone who knows its a prototype, and from their perspective were likely working on the suit a few hours ago, at least before they went into cryo.

2017-06-19 08:56 UTC, Jordie0608 commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
Different items with the same name is bad, come up with a new one; it doesn't have to be `ancient hardsuit`, just something unique.

2017-06-19 09:24 UTC, SgtxRootbeer commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
Alternatively, change the science hardsuit to be more descriptive of it's purpose...
Call it an EOD hardsuit, or a explosives testing hardsuit...

2017-06-19 09:29 UTC, Armhulen commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
Keep the prototype name.

2017-06-19 09:29 UTC, Armhulen commented
The things need to have more fun gimmicks to them because they're old, not just "x but worse!"

2017-06-19 09:35 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
I'll change the RD's Hardsuit to a different name.

2017-06-19 09:38 UTC, Steelpoint commented
I'm happy for someone else to make those changes.

Maybe the Health Analyzer can only check one limb at a time? The egun has a overheat mechanic?  Etc, etc.

But that is all beyond my abilities. So I am doing what I can.

2017-06-19 10:18 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "prototype hardsuit"
Or I could change the name to 'Prototype RIG Hardsuit' as I do reference RIG in the paper desc.

2017-06-19 11:45 UTC, DoctoreMad commented
Okay mate what he is saying is, you don't need "THIS EGUN IS BETTER THAN THE STATION'S EGUN" or "WE HAVE A GOOD X VERSION OF STATION'S", but it would be nice if this station had a unique mechanic on it besides being a ghost role spawn.

2017-06-19 12:26 UTC, Steelpoint commented
I understand what he is saying.

Now what I'm saying is that I lack the coding expertise or knowledge to effect these kind of changes, which would support.

PS: I've also never used a health analyser on lifeweb so that's news to me.

2017-06-19 13:30 UTC, Cyberboss requested changes

2017-06-19 13:30 UTC, Cyberboss commented on _maps/RandomRuins/SpaceRuins/oldstation.dmm
> +"aa" = (/turf/template_noop,/area/template_noop)
Convert to TGM

2017-06-19 13:30 UTC, Cyberboss commented on code/game/area/areas/ruins.dm
> +	requires_power = 0
FALSE

2017-06-19 13:30 UTC, Cyberboss commented on code/game/area/areas/ruins.dm
> +	has_gravity = 0
FALSE

2017-06-19 13:30 UTC, Cyberboss commented on code/game/area/areas/ruins.dm
> +	has_gravity = 0
FALSE

2017-06-19 13:30 UTC, Cyberboss commented on code/game/machinery/doors/firedoor.dm
> +	density = 1
TRUE

2017-06-19 13:30 UTC, Cyberboss commented on code/game/machinery/doors/firedoor.dm
> +	opacity = 1
TRUE

2017-06-19 13:30 UTC, Cyberboss commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(melee = 40, bullet = 5, laser = 5, energy = 0, bomb = 50, bio = 100, rad = 100, fire = 100, acid = 75)
Quote these associations, I know it's everywhere else for armor lists but we're trying to get rid of that

2017-06-19 13:30 UTC, Cyberboss commented on code/modules/clothing/spacesuits/hardsuit.dm
> +		playsound(src.loc, "suitstep", 50, 1)
playsound(src, ...

2017-06-19 13:30 UTC, Cyberboss commented on code/modules/clothing/spacesuits/syndi.dm
> +	desc = "Engineering issue space suit. Age has degraded the suit making is difficult to move around in a gravity based enviroment."
>enviroment

2017-06-19 13:30 UTC, Cyberboss commented on code/modules/paperwork/paper.dm
> +	THE CAPTAIN AND RESEARCH DIRECTORS AUTHORISATION<b/>"
`DIRECTORS` needs an '

2017-06-19 13:44 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +		playsound(src.loc, "suitstep", 50, 1)
You mean place a quote around the defence type or what?

2017-06-19 13:46 UTC, Steelpoint commented on _maps/RandomRuins/SpaceRuins/oldstation.dmm
> +"aa" = (/turf/template_noop,/area/template_noop)
How do I do that?

2017-06-19 13:47 UTC, RemieRichards commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(melee = 40, bullet = 5, laser = 5, energy = 0, bomb = 50, bio = 100, rad = 100, fire = 100, acid = 75)
"melee" = 40, "bullet" = 5, "laser" = 5, etc.

2017-06-19 13:47 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	armor = list(melee = 40, bullet = 5, laser = 5, energy = 0, bomb = 50, bio = 100, rad = 100, fire = 100, acid = 75)
You mean place a quote around the defence type or what?

2017-06-19 14:04 UTC, Wyzack commented
I was under the impression that this station was not going to have anything better that the station does not have, both because  the station is terribly old and because the goal is to provide interesting gameplay and not be a place people jump from the station to try and find so they can steal the shit

2017-06-19 14:06 UTC, Steelpoint commented
Nothing on the station is better than what you can get from SS13.

The unique items on offer are substandard. The Hardsuit is inferior to even a space suit, and it's loud to move in so goodbye ant attempt at stealth, the egun is just a worse laser with a single stun round, etc, etc.

I'll take feedback on if any particular item needs to be toned down.

2017-06-19 16:51 UTC, Steelpoint commented
Also I've met all requested changes thus far.

2017-06-19 17:55 UTC, juanototo2 commented
Steelpoint. Make sure it has some ridiculously old openss13 era or r4407 level of old shit in, to help with the hilariously dilapidated old feel.. Just don't add esword x2 revolvers.

2017-06-19 18:00 UTC, Cyberboss submitted a review, later dismissed

2017-06-19 18:49 UTC, Armhulen commented
derilect station from the united earth government!

2017-06-19 20:48 UTC, octareenroon91 commented
Maybe make the spacemen spawn with the NASA jumpsuit instead, for part of your EVA needs.

2017-06-20 03:50 UTC, Steelpoint commented
As I said, there is no powerful gear on board, no eswords, no high tech guns, no uber powerful hardsuits. Also its a Nanotrasen Spacestation, not a UEG one. Though there is a UEG reference somewhere, hehe.

I'm happy to make alterations to add a more dilapidated feel, but I'll need actual direct suggestions.

2017-06-20 15:40 UTC, PraiseRatvar commented
I assume there won't be 101 hivebots in delta? Cause that's obviously overkill and will fuck time dilation sideways _(yes there is 101 hivebots in the station, i counted)_

If there weren't 101 hivebot then how much hivebots will be on the station?

2017-06-20 15:53 UTC, Armhulen commented
DEFINITELY DO THE NASA SPACE SUIT, YES!

2017-06-20 16:52 UTC, Kraseo commented
artificial difficulty: the ruin

2017-06-20 16:59 UTC, Armhulen commented on code/game/objects/structures/ghost_role_spawners.dm
> +	cryogenics pod due to a oncoming radioation storm. The last thing you remember is the station's Artifical Program telling you that you would only be asleep for eight hours. As you open \
Radioation Storm: Where everyone who doesn't go into maint turns into a radio. Very deadly!

2017-06-20 23:55 UTC, Kraseo commented on code/game/objects/structures/ghost_role_spawners.dm
> +	cryogenics pod due to a oncoming radioation storm. The last thing you remember is the station's Artifical Program telling you that you would only be asleep for eight hours. As you open \
don't forget that you work for Nanotrasen, not NanoTrasen, two whole different companies!

2017-06-21 01:52 UTC, SgtxRootbeer commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "Early prototype RIG hardsuit helmet, designed to quickly shift over a user's head. Design constraints of the helmet mean it has no inbuitl cameras, thus it restricts the users visability."
so thats how we see so far. thansk "inbuitl" camersa!

2017-06-21 01:52 UTC, SgtxRootbeer commented on code/modules/paperwork/paper.dm
> +	ratio, and is typically seen on military or high security ships and stations, however Fission reactors consume massive amounts of resources to keep operational, and are highly prone to \
fisusion generator vs fission.
"however fission reactors consume massive amounts of resources"

2017-06-21 01:52 UTC, SgtxRootbeer commented on code/modules/paperwork/paper.dm
> +	<b>SIGNIFICANT EVENTS OF NOTE</b><br>1: The primariy radioation detectors were taken offline after 112 years due to power failure, secondary radioation detectors showed no residual \
"primariy" "radioation"
should be
"primary" "radiation"
radiation misspelling continues on the line below, mind you.

2017-06-21 04:03 UTC, Steelpoint commented on code/modules/paperwork/paper.dm
> +	ratio, and is typically seen on military or high security ships and stations, however Fission reactors consume massive amounts of resources to keep operational, and are highly prone to \
Space Corps are so cheap they create knock off Fission Reactors. I dunno its just a fluff piece.

I'll reword it that Fission Reactors require very rare and expensive construction materials to make, hence why they are rare.

There's a reason the Centcom Ferry can reach SS13 within ten seconds, yet the evac ship needs three minutes.

2017-06-21 11:19 UTC, Steelpoint commented
Replaced the space suit with a renamed NASA Voidsuit. Also effected some minor spelling changes.

2017-06-21 11:34 UTC, Jalleo commented
Can I suggest that there are much fewer hivelords because most people wont be able to defeat them. Also when it comes to engineering tools you could make it a child with rusty sprites and take longer to use. So it gives them a motive to try and clean them or make new ones.

2017-06-21 11:35 UTC, Steelpoint commented
Hecks a Hivelord?

The majority of the Hivebots are the weak, 15 health, hivebots. For the most part only a few of the Hivebots are the stronger varient. 

I'll look into adding a subset of 'rusty' tools that have a slightly longer use period.

2017-06-21 16:28 UTC, Jalleo commented
Sorry I meant hivebot I was overheated a bit at the time. Its too hot at the moment.

2017-06-21 16:59 UTC, Steelpoint commented
Somehow on my map every single item in it has duplicated so that there's two if every single item on every tile on the map...

Don't know how that happened, but I'll fix be slowly fixing it.

2017-06-21 17:12 UTC, ghost reviewed
FIX YOUR SHIT SON.

2017-06-21 17:12 UTC, Armhulen commented on code/modules/paperwork/paper.dm
> +	radioation on station. Deduction, primariy detector was malfunctioning and was producing a radioation signal when there was none.<br><br>2: A data burst from a nearby Nanotrasen Space \
Radioation 2: Reawakening Report Boogaloo

(here and line above)

2017-06-21 17:43 UTC, Bawhoppen commented
Aside from all other problems, this is really bothering me: Why is it referred to as ancient, when it's only 100 years old?

2017-06-21 18:07 UTC, Armhulen commented
imagine what they'll do to tech today in 100 years, but instead of today's tech we have space technology

yeah it's ancient

2017-06-21 19:33 UTC, kilkun commented
my suggestions:

make the outdated laser guns use the old laser sprite, not the ugly nerf-looking one.

put a red syndicate space suit somewhere out in space, the classic one not the stupid black and red one

take some of the redone exadv1 sprites from the 2016 goon release. They include the ancient canisters as well as some other neat stuff. Adds the retro look without causing 200 burn damage to the player's eyes.

i don't see a neon green heat suit.

replace the engineering suit that uses the syndicate sprites with the old ss13 white suit sprites.

finally take some design cues from the original ss13. namely replace all the airlocks with windoors. that's how the space stations prior to goon were constructed. putting airlocks everywhere still looks retarded to me and it's a easy way to implement a callback to old ss13.

![](https://farm8.staticflickr.com/7320/14089610823_d198b5db86_o.png)

2017-06-21 19:36 UTC, Cyberboss commented
@Steelpoint ping me when the plan for this solidifies

2017-06-21 20:25 UTC, Jalleo commented
@kilkun we already have another derelict based on that. Also we have a retro laser which uses the old style.

2017-06-21 20:26 UTC, Iamgoofball commented
also use oldstation sprites pls

2017-06-21 20:59 UTC, kilkun commented
@jalleo i fail to see why that means effort can't be put into making this station look old instead of exactly like a modern station but a bit rusty

2017-06-21 21:35 UTC, WJohn commented
Your pic is broken, pls fix.

2017-06-21 21:43 UTC, kilkun commented
https://farm8.staticflickr.com/7320/14089610823_d198b5db86_o.png

2017-06-21 21:44 UTC, octareenroon91 commented
From code/modules/clothing/under/miscellaneous.dm :

````
/obj/item/clothing/under/space
        name = "\improper NASA jumpsuit"
        desc = "It has a NASA logo on it and is made of space-proofed materials."
        icon_state = "black"
        item_state = "bl_suit"
        item_color = "black"
        w_class = WEIGHT_CLASS_BULKY
        gas_transfer_coefficient = 0.01
        permeability_coefficient = 0.02
        body_parts_covered = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
        cold_protection = CHEST | GROIN | LEGS | ARMS //Needs gloves and shoes with cold protection to be fully protected.
        min_cold_protection_temperature = SPACE_SUIT_MIN_TEMP_PROTECT
        heat_protection = CHEST|GROIN|LEGS|FEET|ARMS|HANDS
        max_heat_protection_temperature = SPACE_SUIT_MAX_TEMP_PROTECT
        can_adjust = 0
        resistance_flags = 0
````

2017-06-22 09:31 UTC, Jalleo commented
One the original sprites for SS13 are partially ass
Two yes it could use some design ideas from that station but it isnt.
Three We dont have many spriters making a lot of old looking equipment. Its hard enough already.
Four I kinda agree on the whole rust thing but there arent many options available.

2017-06-22 09:39 UTC, Steelpoint commented
I'll make a post when I eventually get around to un-fucking the station.

Really want to know what caused the map to duplicated every single item on the map on the same tile.

2017-06-22 13:15 UTC, Jalleo commented
I have no idea on that issue.

2017-06-22 14:29 UTC, Steelpoint commented
It occured after I converted to TGM.

Are you meant to take a backup copy of the map prior or something?

2017-06-22 14:29 UTC, Steelpoint commented
It occured after I converted to TGM the second time.

Are you meant to take a backup copy of the map prior or something?

2017-06-22 18:59 UTC, Jalleo commented
I believe you are just incase. You may have a backup. @Jordie0608 might be able to help you.

2017-06-22 19:55 UTC, anconfuzedrock commented
I don't care how fucking ancient this station is there have been no recent innovations in BACKPACK TECHNOLOGY

2017-06-22 22:45 UTC, Jalleo commented
Consider it another way do you want to fill a 100 year old backpack completly full of stuff?

2017-06-22 23:08 UTC, Steelpoint commented
How do I revert to a older commit?

I figured out that the error occured under the 'TGMConv' commit.

2017-06-22 23:11 UTC, Steelpoint commented
Nevermind, I'll have to redo this PR due to this error. It's going to take me days to fix the error that I'm better off starting from scratch.

What a waste of my time.

2017-06-22 23:24 UTC, Steelpoint commented
I think I may have resolved the issue by partially reverting to a older map version, maybe.

2017-06-23 02:03 UTC, Armhulen commented
reeeeeeeeeeeeeeeeeeeeee

2017-06-23 14:27 UTC, Steelpoint commented
I should mention I did resolve the issue with that revert above.

The PR is merge ready.

2017-06-23 16:31 UTC, Jalleo commented
@anturk

2017-06-25 14:41 UTC, Armhulen commented
It's another code is 100% ready but nobody wants to review it so it just sits there and rots episode, change the channel!

2017-06-25 14:49 UTC, Steelpoint commented
I'll expand on certain ideas like 'rusted' tools and other minor ideas after the fact, I just want the main addition to be merged before I work on those minor features.

2017-06-25 16:01 UTC, Cyberboss approved these changes

2017-06-25 16:02 UTC, merged

2017-06-25 19:15 UTC, DoctoreMad commented on code/modules/paperwork/paper.dm
> +	radioation on station. Deduction, primariy detector was malfunctioning and was producing a radioation signal when there was none.<br><br>2: A data burst from a nearby Nanotrasen Space \
Second radioation still not removed.