Bluespace Artillery now requires keycard authentication to unlock controls
tgstation/tgstation pull request #28592
Opened 2017-06-19 12:52 UTC by kevinz000

This is on @KorPhaeron's planetstation list.

2017-06-19 13:16 UTC, Cyberboss requested changes

2017-06-19 13:16 UTC, Cyberboss commented on tgui/src/interfaces/bsa.ract
> +			<span>Bluespace Artillery firing protocals must be globally unlocked from two keycard authentication devices first!</span>
>protocals

2017-06-19 13:16 UTC, Cyberboss commented on code/modules/security_levels/keycard_authentication.dm
> +	minor_announce("Bluespace Artillery firing protocals have been [GLOB.bsa_unlock? "unlocked" : "locked"]", "ATTENTION: Weapons Systems Update:")
>protocals

2017-06-19 13:16 UTC, Cyberboss commented on code/modules/security_levels/keycard_authentication.dm
> +	minor_announce("Bluespace Artillery firing protocals have been [GLOB.bsa_unlock? "unlocked" : "locked"]", "ATTENTION: Weapons Systems Update:")
Remove `ATTENTION:` and the colon after Weapons Systems Update

2017-06-19 13:16 UTC, Cyberboss commented on code/modules/security_levels/keycard_authentication.dm
> +			SSblackbox.inc("alert_keycard_auth_bsa",1)
Remove the second param, it's 1 by default

2017-06-19 14:23 UTC, octareenroon91 commented on tgui/src/interfaces/bsa.ract
> +			<span>Bluespace Artillery firing protocals must be globally unlocked from two keycard authentication devices first!</span>
courtesy: "protocols"

2017-06-19 14:26 UTC, octareenroon91 commented
I suggest the BSA deployment spawn one, possibly two, keycard auth devices.

2017-06-19 15:17 UTC, lzimann commented on tgui/src/interfaces/bsa.ract
> +			<span>Bluespace Artillery firing protocals must be globally unlocked from two keycard authentication devices first!</span>
I don't like the `must be globallly unlocked` part, doesn't mean much in the game context.

2017-06-19 15:29 UTC, Cyberboss requested changes
Recompile tgui, you spoon!

2017-06-20 13:55 UTC, Cyberboss approved these changes

2017-06-20 13:55 UTC, merged

2017-06-20 13:57 UTC, PraiseRatvar commented
hey look its technically actual planetstation progress