Fixes shining lights into peoples eyes
tgstation/tgstation pull request #28618
Opened 2017-06-19 23:40 UTC by ExcessiveUseOfCobblestone

ITS NOT OPTIONAL IF IT REMOVES FUNCTIONALITY FROM ALL LIGHTS REEEEEEEEEEEE

2017-06-19 23:41 UTC, MimicFaux commented
Best codermin

2017-06-20 02:59 UTC, Cyberboss requested changes

2017-06-20 02:59 UTC, Cyberboss commented on code/game/objects/items/devices/flashlight.dm
> +	var/flashlight_power = 1 //strength of the light when on. optional
Fix the comment

2017-06-20 19:12 UTC, Expletive commented
I originally had `if(flashlight_power && flashlight_power < 1)` but @lzimann told me to change it to `if(flashlight_power < 1)` and that's why this broke, because null is less than 1.

2017-06-21 01:06 UTC, merged