[WIP] Ports bay's supermatter monitor modular program
tgstation/tgstation pull request #28635
Opened 2017-06-20 07:49 UTC by Shadowlight213

Holy shit, actually new content for modular computers instead of refactors!!! :tada: 

:cl:
add: There is now a new monitor program that engineers can use to monitor the supermatter status
/:cl:
Screenshot of the UI (the double colon thing was fixed. this one is a bit old)
![](http://puu.sh/wpb94/edffcaf547.png)

Since the sprites for laptops and tablets were redone, I can't use the bay ones for the monitor screens.
@Razharas need new tablet sprites for the screens.

Also, I'm getting a runtime, while testing which I'm stuck on.
Runtime in sm_monitor.dm,93: cannot read from list

2017-06-20 07:54 UTC, Bawhoppen commented
is this able to dynamically monitor any supermatter or just the roundstart engineering ones?

2017-06-20 07:55 UTC, RemieRichards commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
you don't need a second set of ```component.exports``` and ```data```, just put ```BigState(val, aver, max)``` below ```integState```

Like I did here: https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/tgui/src/interfaces/mech_bay_power_console.ract#L2

2017-06-20 07:56 UTC, Shadowlight213 commented
Any supermatter. The program starts you on a list of all supermatters detected. It will show any that are on the station or mining level, or on the same level as the user. You can then select one to view in more detail.

2017-06-20 07:56 UTC, Shadowlight213 commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
I did that at first, but it gave me compile errors.

2017-06-20 07:59 UTC, Bawhoppen commented
It'd be better if you had to stick a monitoring chip on or something probably instead of just showing all

2017-06-20 08:01 UTC, Shadowlight213 commented
All supermatters have a monitoring chip on them though. The radio. IC wise, this just interfaces with those existing sensors.

2017-06-20 08:08 UTC, Bawhoppen commented
I guess

2017-06-20 08:31 UTC, Shadowlight213 commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
@RemieRichards for future reference, is there a way to do an else if, or switch statement in tgui?

2017-06-20 08:32 UTC, RemieRichards commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
in the template or in the JS at the top of templates?

2017-06-20 08:33 UTC, Shadowlight213 commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
In the template

2017-06-20 08:34 UTC, RemieRichards commented on tgui/src/interfaces/ntos_supermatter_monitor.ract
> +  component.exports = {
```
{{#if data.example}}
{{else}}
    {{#if data.example_two}}
    {{/if}}
{{/if}}
```
You have to remember that ```else if``` is really just sugar for ```if {} else { if { } }```

2017-06-20 09:11 UTC, kevinz000 commented
>doing network refactor
>see this
>SCREAM

2017-06-20 12:05 UTC, meeeeme commented
neat

2017-06-20 18:51 UTC, Anonmare commented
Is MeV/cm^3 charge level?

2017-06-20 21:23 UTC, Shadowlight213 commented
yes

2017-06-21 00:13 UTC, Shadowlight213 commented
Ok, so I was able to codersprite the overlays for the program onto the tablet, but there is no way I'm managing to get them to fit onto the Eris laptop sprites. The laptop screens are just too small.

2017-06-21 03:55 UTC, Shadowlight213 commented
Kor won't let me use the bay laptops because I said mean words to oranges, and I cant fit the overlays on the eris ones.

2017-06-21 03:55 UTC, KorPhaeron commented
????

2017-06-21 03:56 UTC, KorPhaeron commented
Just use the new sprites you meme

2017-06-21 03:57 UTC, Shadowlight213 commented
They don't fit. The overlay is too big senpai. It's not going to fit.

2017-06-21 03:58 UTC, KorPhaeron commented
Then use the bay laptops nobody cares what the laptop sprites are I promise I thought asking permission about that was a joke

2017-06-21 04:05 UTC, optimumtact commented
maybe try the tip of the overlay?

2017-06-21 04:05 UTC, optimumtact commented
just the tip

2017-06-26 20:56 UTC, lzimann commented
@Shadowlight213

2017-06-26 23:21 UTC, Shadowlight213 commented
Ok, I have the overlay be overridden if a laptop is running the program, as I'd need more time to figure out how to port the bay overlays there.

2017-06-26 23:21 UTC, Shadowlight213 commented
Whoops.

2017-06-27 05:11 UTC, Shadowlight213 commented
This is basically done.

2017-06-27 13:49 UTC, Cyberboss commented on code/modules/modular_computers/computers/item/tablet_presets.dm
> +	hard_drive.store_file(new/datum/computer_file/program/supermatter_monitor())
Can't say I'm a fan of pre-installing programs, tbh

2017-06-27 13:56 UTC, Cyberboss requested changes

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +	requires_ntnet = 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +	var/obj/machinery/power/supermatter_shard/active = null		// Currently selected supermatter crystal.
Remove ` = null`

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +		if(!istype(air))
just !air

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +		data["active"] = 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +		var/list/relevantgas = list("o2","co2","n2","plasma","n2o","freon")
why exclude anything? this is basically all gases

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +		data["active"] = 0
FALSE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +		return 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +			return 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +			return 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/modular_computers/file_system/programs/sm_monitor.dm
> +			return 1
TRUE

2017-06-27 13:56 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +	if(get_integrity() < 5)
There should be defines for these levels

2017-06-27 17:24 UTC, Shadowlight213 commented on code/modules/power/supermatter/supermatter.dm
> +	if(get_integrity() < 5)
You sure? Its a percentage of the sm integrity remaining.

2017-06-27 19:27 UTC, Shadowlight213 commented on code/modules/modular_computers/computers/item/tablet_presets.dm
> +	hard_drive.store_file(new/datum/computer_file/program/supermatter_monitor())
I can remove it if you want.

2017-06-27 20:54 UTC, Cyberboss commented on code/modules/modular_computers/computers/item/tablet_presets.dm
> +	hard_drive.store_file(new/datum/computer_file/program/supermatter_monitor())
Please do, I believe tablets are eventually supposed to be a: build your own pda sort of deal

2017-06-27 20:59 UTC, Cyberboss commented on code/modules/power/supermatter/supermatter.dm
> +	if(get_integrity() < 5)
You're right, Can you make them defines please

2017-06-28 14:55 UTC, Cyberboss approved these changes

2017-06-28 15:05 UTC, merged