Implanting revheads and gang bosses actually uses up the implant.
tgstation/tgstation pull request #28634
Opened 2017-06-20 07:42 UTC by bgobandit

Fixes https://github.com/tgstation/tgstation/issues/28629.

2017-06-20 09:31 UTC, QualityVan commented
Should probably change the failure message to indicate the implant is used up.

2017-06-20 14:12 UTC, Cyberboss requested changes
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/implants/implant.dm#L44

This will destroy the implant in EVERY failure case. e.g. Target already has an implant, is not suitable for implants, etc.

2017-06-20 19:36 UTC, bgobandit commented
oops

2017-06-23 01:10 UTC, bgobandit commented
@Cyberboss as far as I can tell this needs to be refactored to be fixed, my options are afaict

1) Move the checks for can_be_implanted and already has implant out of implant() and into implanter's attack, so they just return before the whole nonsense starts
2) Add special code in the loyalty implant proc to handle this
3) Add some kind of var to be returned as well to govern whether the implant is trashed
4) Call this intended behavior -- you're sticking it in, why wouldn't the implant be trashed

2017-06-23 14:01 UTC, Cyberboss commented
Have the implant delete itself if the conditions are correct, then check QDELETED(imp) in implanter/attack

2017-06-25 05:35 UTC, bgobandit commented
>stale

2017-06-26 13:31 UTC, Cyberboss requested changes
You still need to make the implant delete itself in implant/implant()

2017-06-26 16:33 UTC, bgobandit commented
the qdel happens in loyalty implant code, it was already there

2017-06-27 20:41 UTC, Cyberboss requested changes

2017-06-27 20:41 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implanter.dm
> -					imp = null
Restore this line

2017-06-27 20:41 UTC, Cyberboss commented on code/game/objects/items/weapons/implants/implanter.dm
> +					update_icon()
untab this line

2017-07-03 22:16 UTC, KorPhaeron commented
Stale

2017-07-03 22:16 UTC, closed without merging