Replaces "istype"s with is_helpers procs
tgstation/tgstation pull request #28676
Opened 2017-06-21 16:20 UTC by nicbn

Replaces a lot of _istype_s with is_helpers procs, also adds some new is_helpers.

2017-06-21 17:18 UTC, ChangelingRain commented on code/__DEFINES/is_helpers.dm
> +#define ismob(L) (istype(L, /mob))
this already exists; it's a byond proc

2017-06-21 19:54 UTC, lordpidey requested changes
Looks like you changed a few files you didn't mean to.

There's also one return statement that could be simplified.

2017-06-21 19:54 UTC, lordpidey commented on code/game/objects/effects/effect_system/effects_foam.dm
>  // Foam
Did you mean to change this file?

2017-06-21 19:54 UTC, lordpidey commented on code/game/objects/items/weapons/tanks/watertank.dm
> -#define RESIN_LAUNCHER 1
Was this filechange intentional?

2017-06-21 19:54 UTC, lordpidey commented on code/game/objects/items/weapons/holosign_creator.dm
> -/obj/item/weapon/holosign_creator/atmos
This looks unintentional.

2017-06-21 19:54 UTC, lordpidey commented on code/game/objects/structures/holosign.dm
>  /obj/structure/holosign/barrier/engineering
Also appears unintentionally changed

2017-06-21 19:54 UTC, lordpidey commented on code/modules/mining/equipment/survival_pod.dm
> +	if(isitem(O))
return(isitem(O))

2017-06-21 21:34 UTC, nicbn commented on code/__DEFINES/is_helpers.dm
> +#define ismob(L) (istype(L, /mob))
Is its behaviour identical to istype(L, /mob)?

2017-06-21 21:37 UTC, nicbn commented on code/game/objects/effects/effect_system/effects_foam.dm
>  // Foam
Didn't noticed it. I'm fixing it.

2017-06-21 22:43 UTC, Jordie0608 commented on code/__DEFINES/is_helpers.dm
> +#define ismob(L) (istype(L, /mob))
Essentially yes http://www.byond.com/docs/ref/info.html#/proc/ismob

2017-06-22 16:10 UTC, lzimann commented on code/__DEFINES/is_helpers.dm
> +//#define isaliendrone(A) (istype(A, /mob/living/carbon/alien/humanoid/drone))
Either use this or remove commented code.

2017-06-22 16:13 UTC, lzimann commented on code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
> -	new /obj/item/weapon/inducer(src)
Accidental remove here.

2017-06-22 16:16 UTC, lzimann commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(!istype(I, /obj/item/weapon/card/id) && istype(I))
Forgot to replace the 2nd `istype` with `isitem`

2017-06-22 16:42 UTC, Expletive commented on code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
> -	new /obj/item/weapon/inducer(src)
>implying it was an accident

@nicbn has it out for me!

2017-06-22 18:03 UTC, merged