Makes RND servers perform worse if they're running on superheated air, not better. Servers are supposed to be cooled, not burned.
tgstation/tgstation pull request #28679
Opened 2017-06-21 17:52 UTC by kevinz000

Also makes them not initialize twice.

2017-06-21 18:04 UTC, Armhulen commented
It's another fix shoehorned in with balance change episode

2017-06-21 18:37 UTC, lordpidey requested changes

2017-06-21 18:37 UTC, lordpidey commented on code/modules/research/server.dm
>  		/*griefProtection() This seems to get called twice before running any code that deletes/damages the server or it's files anwyay.
This should go back in, as this if loop has a chance to remove tech levels.

You might be able to put it in the `if(prob(1))` section, to reduce the number of times it's called.

something along the lines of
```
if(!updateRD)
     griefProtection()
updateRD++
T.level--
```

2017-06-21 18:37 UTC, lordpidey commented on code/modules/research/server.dm
> +			heat_health = max(0, -(excess/40))
This max will always return 0, thus is pointless.


But even beyond that, the whole switch statement here is confusing and irrelevant.
The amount of overheating doesn't change how much the server loses, it's either overheating or it isn't.

Consider the following:

```
 	switch(environment.temperature)
 		if(0 to T0C)
  			overheating = FALSE
 		if((T20C + 20) to INFINITY)
 			overheating = TRUE
	if(overheating)
		//bad_stuff
```

With the way it currently is written, that is identical, and is MUCH easier to read.

Or an alternative method:
```
 	switch(environment.temperature)
 		if(0 to T0C)
  			heat_health++
 		if((T20C + 20) to INFINITY)
			var/excess = environment.temperature - (T20C + 20)
 			heat_health -= excess/40
	heat_health = Clamp(heat_health, 0, 100)
	if(heat_health <= 0)
		//bad_stuff
```

With this second method, the server will have a short grace period when overheating before it starts losing R&D levels.

2017-06-21 19:15 UTC, kilkun commented
this isn't really a balance change, this was always the intention.

2017-06-22 16:24 UTC, kevinz000 commented
rnd techweb pr covers this

2017-06-22 16:24 UTC, closed without merging