Centcom starts importing cat ears/tails
tgstation/tgstation pull request #28732
Opened 2017-06-23 09:33 UTC by improvedname

we all know centcom is half catmen and catgirls this makes sense lore wise

:cl: Improvedname
add: You can now export cat ears/tails for 1000 credits
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) LORE

2017-06-23 09:35 UTC, kevinz000 commented
WHY ARE YOU BUFFING CATS?!!

2017-06-23 09:35 UTC, RemieRichards commented
They need to import lizard parts too then.

@kevinz000 it's a nerf, because people will remove their tails for the credits.

2017-06-23 09:59 UTC, WJohn commented
remove catmemes when

2017-06-23 10:56 UTC, improvedname commented
someday

2017-06-23 11:33 UTC, Grazyn commented
All-cat cargo crew new meta

2017-06-23 12:16 UTC, meeeeme commented
Crate of cat parts in surgery when?

2017-06-23 13:21 UTC, Cyberboss approved these changes

2017-06-23 13:24 UTC, Cyberboss requested changes

2017-06-23 13:24 UTC, Cyberboss commented on code/modules/cargo/exports/organs.dm
> +	include_subtypes = FALSE
This datum isn't necessary

2017-06-23 15:59 UTC, lzimann commented
kill cat get cash

2017-06-24 00:14 UTC, Niknakflak commented
we can remove cat memes when we remove xeno memes first

2017-06-24 05:09 UTC, ExcessiveUseOfCobblestone commented
> we can remove cat memes when we remove xeno memes first

I'm down.

2017-06-24 05:16 UTC, Iamgoofball commented
@Niknakflak Unfortunately both fetishes have maintainers who close PRs removing them.

2017-06-24 05:39 UTC, Tacolizard commented
@RemieRichards i'm pretty sure you can export lizard parts. The skin at least.

2017-06-24 08:58 UTC, RemieRichards commented
@Tacolizard You have to kill for skin, you don't for bodyparts, if people want to make species more consistent, then it's only fair to be able to sell lizard tails and such also.

2017-06-24 09:34 UTC, Iamgoofball commented
censorship

@Niknakflak Both """features""" have maintainers actively protecting them, stating this as a fact is apparently discouraged but whatever.

2017-06-24 09:35 UTC, Iamgoofball commented
also

:+1:

this means catgrills have actual gameplay impact and I can use that as an excuse to remove them

ps. screenshotting all comments from here on for when the FAKE NEWS MSM censors me

2017-06-24 20:21 UTC, Tacolizard commented
add a crate of cat ears and tails to the brig execution chamber/torture chamber when

2017-06-24 22:47 UTC, Cyberboss approved these changes

2017-06-24 22:47 UTC, merged