Small jungle trees
tgstation/tgstation pull request #28765
Opened 2017-06-24 19:24 UTC by KorPhaeron

Ausops sprited them they're good I promise

2017-06-24 19:25 UTC, Armhulen commented
SPRIIIIIIIIIIIIIIIIIIIIIIITES!

2017-06-24 19:25 UTC, Thunder12345 commented
Pictures please

2017-06-24 19:25 UTC, KorPhaeron commented
Scared?

2017-06-24 19:47 UTC, WJohn commented
pretty!

2017-06-24 22:38 UTC, Armhulen commented
ok good!

2017-06-24 22:42 UTC, Cyberboss commented
Not sure if @MrStonedOne meming or the tagger bot going rogue...

2017-06-24 22:43 UTC, Cyberboss commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
This doesn't change the icon or anything?

2017-06-24 23:22 UTC, FantasticFwoosh commented
This is planetstations own aesthetic, but to our current code & sprites it sticks out like a thumb.

2017-06-24 23:27 UTC, Militaires commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
p sure it just offsets the sprite cause it's so giant

2017-06-24 23:51 UTC, PraiseRatvar commented
tree**s** THERE ARE MULTIPLE, I WANT TO SEE ALL THE TREES

2017-06-25 01:31 UTC, MrStonedOne commented
@Cyberboss I'm not even near a computer that has the password store for tg accounts like the github bot

2017-06-25 05:45 UTC, DoctoreMad commented
They are pretty good form the initial image, yes.

2017-06-25 21:23 UTC, Lumipharon commented
Neat.

2017-06-26 10:30 UTC, RemieRichards commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
no, he's commenting that there' no ```icon_state = ...``` line, meaning the small tree will look like a big tree

2017-06-26 11:09 UTC, AnturK commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
@KorPhaeron cmon.

2017-06-26 13:29 UTC, Cyberboss requested changes

2017-06-26 13:29 UTC, Cyberboss commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
FIX IT

2017-06-26 13:30 UTC, KorPhaeron commented on code/game/objects/structures/flora.dm
> +	pixel_x = -32
I fixed it

2017-06-26 13:53 UTC, Cyberboss approved these changes

2017-06-26 13:54 UTC, Cyberboss requested changes

2017-06-26 13:54 UTC, Cyberboss commented on code/game/objects/structures/flora.dm
>  	..()
. = ..() while you're here actually

2017-06-26 14:41 UTC, Cyberboss approved these changes

2017-06-26 14:41 UTC, merged