[Ancient Station] First Round Of Changes/Additions
tgstation/tgstation pull request #28843
Opened 2017-06-26 08:33 UTC by Steelpoint

First main changed based on feedback and similar.

* Fixed minor mapping issues, such as broken glass and similar.
* Added some bluespace crystals to the Hivebot ship for RnD.
* All station helmets and the hardsuit helmet no longer block vision.
* NASA Engineering Void Suit now has a proper slowdown of 4.
* Two pairs of 'worn down insulated gloves' have been added to engineering. Think of them as Budget Gloves, but they have a much better chance of working.
* New movement sounds for the prototype RIG Hardsuit, much more fitting.
* Minor map changes, such as a extra oxygen cannister and similar.

:cl: Steelpoint (Ancient Station)
add: Major changes to Ancient Station include new sounds for the prototype RIG hardsuit, the NASA Engineering Voidsuit slowing the user down properly, new insulated gloves in engineering and helmets don't block vision.
add: Several minor changes, such as extra oxygen tank and minor tile changes.
/:cl:

2017-06-26 08:36 UTC, DoctoreMad commented
>Slowdown of 4

Isn't that unnecessarily painful.

2017-06-26 08:37 UTC, Kraseo commented
there's no slowdown in space

2017-06-26 08:37 UTC, Steelpoint commented
Its to discourage them to wear it indoors, in space there's no movement penalty.

2017-06-26 08:43 UTC, Ergovisavi commented
Consider that any slowdown on non armored gear is entirely irrelevant because they will just hold it in their hands, and that having the slowdown is just annoying for everyone involved.

I get the intent, but in practice all you're doing is being annoying.

2017-06-26 08:52 UTC, DoctoreMad commented
Can you give botany some roundstart saltpetre(maybe) and pest spray(DEFINITELY)? Grapes contain sugar which increase pest levels, but sometimes its the only plant that is gaining potency.

2017-06-26 09:02 UTC, DoctoreMad commented
Oh
I see

2017-06-26 09:51 UTC, PraiseRatvar commented
> All station helmets and the hardsuit helmet no longer block vision.

not a fan of this nerf, like people said on your feedback thread, git gud

2017-06-26 10:06 UTC, Steelpoint commented
I'll see how the general mood before I commit that change, I've still got other things to work on for this PR.

2017-06-26 11:49 UTC, Steelpoint commented
I've removed the NT Banners as I did not realise they can be used to heal people, I've also made some minor spelling changes.

2017-06-26 11:51 UTC, DoctoreMad commented
Very rude

2017-06-26 13:05 UTC, Repukan commented
Don't nerf the helmets, they're cool like that.

Also the banners are hilarious.

2017-06-26 13:08 UTC, Steelpoint commented
I'll likely keep the helmet visor limitation.

2017-06-26 13:55 UTC, Cyberboss requested changes

2017-06-26 13:55 UTC, Cyberboss commented on code/modules/clothing/gloves/color.dm
> +	..()
Initialize and . = ..()

2017-06-26 14:45 UTC, juanototo2 commented
The banners are ridiculous but they are hilariously fun. Keep the "whacking people with toolboxes while waving around a flag that instantly closes wounds" meme. PLEASE.

2017-06-26 15:12 UTC, Jalleo commented
Perhaps make it so the old helmets visors are toggleable? When up the helmet has half protection or something like that.

2017-06-26 15:57 UTC, PraiseRatvar commented
also please add an airlock somewhere on delta or charlie so people don't have to make a giant gaping hole for mechs or borgs

2017-06-26 16:14 UTC, Armhulen commented
WHY DO PEOPLE ENJOY WELDER VISION JESUS

2017-06-26 16:16 UTC, Repukan commented
We don't, but if we add QoL changes then it follows more QoL will be added, thus killing the spirit of the ruin.

Slibbery slobe

2017-06-26 17:15 UTC, MimicFaux commented
The entire point of the ruin is to enjoy a hard-mode reclamation project, and so far 9/10 runs on it have been made fun by the difficulty level and roleplay (probably a bug) with other survivors. Everything from growing plants for healing, multiple trips to recharge shitty guns, to electrocuting myself on the solar arrays because someone else turned the grid on, have made the experience for me.

I like the vision reduction, I enjoyed the lack of gloves (but won't complain for budget gloves+), there was even something thematic about picking through the chemical storage beakers. What I would like to see is some more piece to the remains of atmos added for additional projects the spessmen can work on.

2017-06-26 17:33 UTC, Steelpoint commented
PR is still a work in progress, I'll post again when my next set of changes and alterations is up.

2017-06-26 23:40 UTC, Really-Good-Soda-Flavor commented
These look like stupid, unnecessary changes that nobody asked for to me.

2017-06-26 23:59 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/oldstation.dmm
> +	icon_state = "whitehall";
dirty vars
(you can just remove these two lines with notepad or w/e tbh)

2017-06-27 14:51 UTC, Steelpoint commented on code/modules/clothing/gloves/color.dm
> +	..()
Don't know what your asking me to change as its identical to the other similar code entry for budget gloves.

2017-06-27 14:55 UTC, Steelpoint commented
New push has some changes. Helmets and visors have the tinting again, I've removed the airless tiles on Charlie Station since I think that just raises unnecessary issues with broken atmo, and the fact its a non-issue to resolve. I've also scattered the parts to construct a sleeper, if you can find the parts.

Also some other minor mapping changes.

2017-06-27 15:02 UTC, Repukan commented
Don't add parts to build a sleeper, they're already available if you deconstruct other machines.

2017-06-27 15:42 UTC, Armhulen commented
at least not the hardsuit having tint aw god compromise

2017-06-27 16:27 UTC, Tacolizard commented
the voltage in the solars made it so that cutting or laying down any wire connected to them would shock you. It is better that now we get some insulation, but it's dumb to basically force the player to shock themselves in order to wire the solars.

2017-06-27 16:30 UTC, Tacolizard commented
also this map shouldn't be called oldstation (like it is in the filename) because that's the name of the original pre-boxstation map.

2017-06-27 22:22 UTC, PraiseRatvar commented
just it call it steelstation

2017-06-28 06:12 UTC, Steelpoint commented
I should mention I have removed the floor tiles on the solar array.

2017-06-28 22:10 UTC, Ergovisavi commented
> I've removed the NT Banners as I did not realise they can be used to heal people, I've also made some minor spelling changes.

Keep them in but change the effect to only work if you're below 20 HP and not in crit or something. It boosts morale, but that'll only keep you trucking along, it won't completely heal you.

You keep some of the absurdity for fun, but keep it from turning you into fucking wolverine.

2017-06-29 11:01 UTC, DoctoreMad commented
Why do the transit tubes have huge kPa anyways?

2017-06-29 12:40 UTC, Steelpoint commented
I got some further changes I'm making.

I might add blueprints to help in construction.

2017-06-29 14:36 UTC, Steelpoint commented
Pushed some changes, so my PR is now merge ready.

* The three spawn roles now have some extra equipment on them to differentiate them a bit. Security Officer spawns with a flash and handcuffs (plus his uniform having 10 melee makes him more combat focused). Engineer spawns with a emergency oxygen tank and a worn our insulated glove. Scientist spawns with a bandage in their pocket.
* Removed the tinting on the hardsuit helmet, I think that's fair considering its slow down.
* Reworked minor tiles, such as the solar arrays. Also got rid of the excess items to reconstruct a sleeper without raiding other machines.

2017-06-29 15:21 UTC, Steelpoint commented
Also @DoctoreMad the transit tubes had high pressure due to the lack of air on Charlie Station seeping into the tubes.

My removal of the airless tiles on Charlie should stop this issue.

2017-06-30 07:07 UTC, AnturK commented on code/modules/clothing/gloves/color.dm
> +/obj/item/clothing/gloves/color/old/New()
Initialize, also this should just be subtype of fake yellows.

2017-06-30 09:03 UTC, Steelpoint commented on code/modules/clothing/gloves/color.dm
> +/obj/item/clothing/gloves/color/old/New()
What does initialize mean?

2017-06-30 09:15 UTC, AnturK commented on code/modules/clothing/gloves/color.dm
> +/obj/item/clothing/gloves/color/old/New()
It's a function we call on objects immediately once map is fully loaded and ready. Replace New with Initialize, we have more control over initialization times and process with it. See https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/atoms.dm if you want more details.

2017-06-30 16:13 UTC, Steelpoint commented
Asked for changes have been made, PR is merge ready assuming nothing breaks.

2017-07-02 00:24 UTC, lordpidey commented
So... how does an area with LOW pressure seeping into the tube cause HIGH pressure?  That seems like it's a bug in it's own right.

2017-07-02 01:41 UTC, Steelpoint commented
This is still good to merge. I addressed the requested changes as @Cyberboss requested.

2017-07-03 00:21 UTC, octareenroon91 commented
How many oxygen tanks are there overall?

2017-07-03 04:27 UTC, Steelpoint commented
Two I believe.

2017-07-03 16:47 UTC, Steelpoint commented
So, err, is this going to get merged or anything anytime soon?

@Cyberboss for approving the changes I made.

2017-07-04 18:04 UTC, Cyberboss requested changes

2017-07-04 18:04 UTC, Cyberboss commented on code/modules/clothing/gloves/color.dm
> +	..()
. = ..()

2017-07-04 18:04 UTC, Cyberboss commented on code/modules/clothing/gloves/color.dm
> +/obj/item/clothing/gloves/color/fyellow.old/Initialize()
/

2017-07-05 03:56 UTC, Steelpoint commented
Fixes have been deployed.

2017-07-05 04:21 UTC, Cyberboss approved these changes

2017-07-05 04:22 UTC, merged