Adds heartbeats
tgstation/tgstation pull request #28858
Opened 2017-06-26 20:23 UTC by Tacolizard

:cl: Tacolizard
add: NanoTrasen has now outfitted their employees with Extra-Loud(TM) Genetically Modified Hearts! Now you can hear your heart about to explode when you take meth, or hear it slowly coming to a stop as you bleed out in critical condition!
/:cl:

2017-06-26 20:35 UTC, WJohn commented
Neato.

2017-06-26 20:46 UTC, Ratvar commented
Only you can hear your own heartbeat, or people standing near also can?
Give mime silent heart

2017-06-26 20:48 UTC, Tacolizard commented
@Ratvar only you can hear your heartbeat.

2017-06-26 20:51 UTC, nicbn commented
Seems ok

2017-06-26 21:15 UTC, XDTM commented
playsound_local to play sounds directly to players

2017-06-26 21:15 UTC, Tacolizard commented
@lzimann whyyyy

2017-06-26 21:16 UTC, XDTM commented on code/modules/mob/living/carbon/life.dm
> +		beat = 2
use defines

2017-06-26 21:17 UTC, Tacolizard commented
@XDTM I don't think so. plus there's no reason to use playsound_local here anyways as I'm not using any of it's features.

2017-06-26 21:23 UTC, XDTM commented
you could use sound channels to stop the sound instead of `<< sound(null)`. I'm not sure if it also stops ambience or other sounds, but it might do that.

2017-06-26 21:24 UTC, XDTM commented on code/__DEFINES/misc.dm
> +
up to you, but inserting a comment to describe what they're for is probably a good idea

2017-06-26 21:25 UTC, XDTM commented on code/__DEFINES/misc.dm
> +#define BEAT_NONE 0
up to you, but inserting a comment to describe what they're for is probably a good idea

2017-06-26 21:53 UTC, FantasticFwoosh commented
We already have working stethoscopes you haven't factored into this at all. For Call of duty sound effects so that the moron's know they fucked up, and overlay onto SUPER LOUD midi's admins spam at 2am in the morning to positively break my ears.

![](https://pbs.twimg.com/media/C4wuWLiXUAAE4ea.jpg)

So i'll never hear it because i play at like utmost minimum volume.

2017-06-26 22:01 UTC, Tacolizard commented
@FantasticFwoosh 
sounds like a personal problem.


also
>For Call of duty sound effects so that the moron's know they fucked up, and overlay onto SUPER LOUD midi's admins spam at 2am in the morning to positively break my ears.
is this english?

2017-06-26 22:15 UTC, Tacolizard commented
>So i'll never hear it because i play at like utmost minimum volume. 👎

'I play the game at a low volume so i don't like this sound change'

why don't you just remove every sound then?

2017-06-26 22:21 UTC, FantasticFwoosh commented
How is you overlooking existing vacular activity (because stethoscopes track vascular beats because the heart beats in accord with oxygen damage ALREADY) to make the system have interesting flavour by holding a stethoscope against the chest and **listen**

And instead just spam the shit out of it when literally anything happens for white noise ontop of a already what can be noisy game.

> @Tacolizard : "Why don't you remove every sound then?"

You're the one who wants to add pointless effect noisespam nobody will hear or appreciate.

2017-06-26 22:24 UTC, Tacolizard commented
@FantasticFwoosh YOU won't hear it, because YOU said YOU play at a low volume. not everybody plays at a low volume like you. 

>And instead just spam the shit out of it when literally anything happens

do you even read code

this isn't supposed to be a realistic feature fwoosh, it's just fluff. If you want to open a PR that makes stethoscopes by heartbeat sounds, then you do it. Don't get angry at this PR because it doesn't add a feature you thought of out of nowhere.

2017-06-26 22:31 UTC, FantasticFwoosh commented
I did read it, you took my words entirely out of context because going into critical is semi-common occurance, as is recreational drugs or even just drinking a extra sugary latte, its fluff and im not certain with the wasted opportunity why you didn't grab the bull by the horns more.

Is this literally all you're happy with doing? It's going to be literally just annoying to people who do actually play with volume on as it is completely irrelevant to people who play with it off.

2017-06-26 22:32 UTC, XDTM commented
don't argue with fwoosh, it's time lost

2017-06-26 22:32 UTC, Tacolizard commented
@XDTM i tell myself that every time he comments on my PRs, but each time he just says the perfect things to rope me into arguing with him kek.

2017-06-26 22:42 UTC, Really-Good-Soda-Flavor commented
I think this is kinda dumb and annoying but, @Tacolizard I suggest you tie this in with the heart's on_life() proc so that people without hearts will not hear it!

2017-06-26 22:45 UTC, Tacolizard commented
@Really-Good-Soda-Flavor to address the 'annoying' part, these sounds are both kinda quiet and pretty low-pitch, so I really don't think they will be annoying ingame. 

I can't really tie this into that because this feature is placed on mob/carbon/living, so even mobs without hearts can hear it.

2017-06-26 22:47 UTC, ghost requested changes

2017-06-26 22:47 UTC, Really-Good-Soda-Flavor commented on code/modules/mob/living/carbon/life.dm
> +		if(!beat || beat == BEAT_SLOW)
So here you could do:

```
var/obj/item/organ/heart/heart = getorgan(/obj/item/organ/heart)
if(heart)
     if(!heart.beat || heart.beat == BEAT_SLOW)
```
et cetera

2017-06-26 22:47 UTC, Really-Good-Soda-Flavor commented on code/modules/mob/living/carbon/life.dm
> +	if(health <= HEALTH_THRESHOLD_CRIT)
This could all be on the heart's on_life()

2017-06-26 22:47 UTC, Really-Good-Soda-Flavor commented on code/modules/mob/living/carbon/carbon_defines.dm
> +	var/beat //is this mob having a heatbeat sound played? if so, which?
This could be on the heart itself

2017-06-26 22:47 UTC, Really-Good-Soda-Flavor commented on code/__DEFINES/misc.dm
> +#define BEAT_NONE 0
Don't have a beat none, just set it to null

2017-06-26 22:47 UTC, Really-Good-Soda-Flavor commented on code/modules/mob/living/carbon/life.dm
> +		src << sound(null)
You should definitely use playsound_local

2017-06-26 22:49 UTC, Really-Good-Soda-Flavor commented
@Tacolizard If something doesn't have a heart, why would it hear a heartbeat? lmao

2017-06-26 22:49 UTC, Tacolizard commented
@Really-Good-Soda-Flavor I explained, because xenos would have hearts, but they have no heart organ.

2017-06-26 22:51 UTC, Really-Good-Soda-Flavor commented
Then give them a heart

2017-06-26 22:52 UTC, Tacolizard commented
@Really-Good-Soda-Flavor but this is a lazy PR

2017-06-26 22:55 UTC, Cyberboss requested changes
Listen to Soda

2017-06-26 23:21 UTC, MoreRobustThanYou commented
How about you make this TOGGLEABLE?

2017-06-26 23:45 UTC, lordpidey requested changes
How about you make sure they have a heart before it starts beating?

2017-06-27 00:54 UTC, ma44 commented
It's all in the mind

2017-06-27 07:48 UTC, RemieRichards submitted a review, later dismissed
Needs refactoring onto heart organ.

2017-06-27 15:05 UTC, Tacolizard commented on code/modules/mob/living/carbon/life.dm
> +		src << sound(null)
delivering a null sound stops sounds.

2017-06-27 15:19 UTC, Cyberboss commented on code/modules/mob/living/carbon/life.dm
> +		src << sound(null)
We have a proc for that

2017-06-27 16:22 UTC, Tacolizard commented
Ok, I finished refactoring.

@Cyberboss @RemieRichards

2017-06-27 16:39 UTC, Tacolizard commented on code/__DEFINES/misc.dm
> +#define BEAT_NONE 0
eehhhhhh i really don't want to do that. having a define is more descriptive.

2017-06-28 00:03 UTC, ghost requested changes

2017-06-28 00:03 UTC, Really-Good-Soda-Flavor commented on code/modules/surgery/organs/heart.dm
> +			H.stop_sound_channel(150)
Make the channel a define in the sounds defines file

2017-06-28 00:03 UTC, Really-Good-Soda-Flavor commented on code/modules/surgery/organs/heart.dm
> +	var/beat //is this mob having a heatbeat sound played? if so, which?
Set this to BEAT_NONE if you're gonna use that define

2017-06-28 00:03 UTC, Really-Good-Soda-Flavor commented on code/modules/mob/living/carbon/life.dm
> +				stop_sound_channel(150)
Channel a define

2017-06-28 01:27 UTC, Cyberboss commented on code/__DEFINES/misc.dm
> +#define BEAT_NONE 0
This is fine

2017-06-28 01:27 UTC, Cyberboss requested changes
Do what soda said

2017-06-28 01:51 UTC, optimumtact commented
if it's a sound it should have a pref, just like lobby music and admin midi's and environmental ambience

2017-06-28 01:52 UTC, Cyberboss commented
Just group it under ambience then, we don't need more pref creep

2017-06-28 01:53 UTC, optimumtact commented
I like ambience but I don't like this so I oppose that

2017-06-28 02:12 UTC, PKPenguin321 commented
so every human has a constant thump thump playing at them all the time

sounds awful

2017-06-28 02:45 UTC, Tacolizard commented
@PKPenguin321 read the pr desc dood.

it only plays when in crit or when jittery

2017-06-28 02:48 UTC, Tacolizard commented
@Cyberboss 

ping

2017-06-28 07:52 UTC, RemieRichards commented on code/__DEFINES/misc.dm
> +#define BEAT_NONE 0
whenever we have defines we always have a ```_NONE```, if they're flags, we also tend to have an ```_ALL``` (```~0```)

2017-06-28 07:53 UTC, RemieRichards commented on code/modules/surgery/organs/heart.dm
> +	if(ishuman(owner) && owner.client)
do monkeys have hearts?

2017-06-28 08:20 UTC, Tacolizard commented on code/modules/surgery/organs/heart.dm
> +	if(ishuman(owner) && owner.client)
yeah, i'm pretty sure.

2017-06-28 08:21 UTC, RemieRichards commented on code/modules/surgery/organs/heart.dm
> +	if(ishuman(owner) && owner.client)
sooo, no ```ishuman()``` then? you don't actually need anything lower than ```/mob/living```

2017-06-28 14:43 UTC, Cyberboss requested changes

2017-06-28 14:43 UTC, Cyberboss commented on code/__DEFINES/misc.dm
> +#define BEAT_CHANNEL 150 //sound channel for heartbeats
Put this in __DEFINES/sounds.dm and name it HEARTBEAT_CHANNEL

2017-06-28 14:43 UTC, Cyberboss commented on code/modules/mob/living/carbon/life.dm
> +		if(heart)
Do this in heart/on_life

2017-06-28 14:59 UTC, Cyberboss requested changes

2017-06-28 14:59 UTC, Cyberboss commented on code/__DEFINES/sound.dm
> +#define HEARTBEAT_CHANNEL 150 //sound channel for heartbeats
Sorry, `CHANNEL_HEARTBEAT` and make it 1019

2017-06-28 14:59 UTC, Cyberboss commented on code/__DEFINES/sound.dm
>  //KEEP IT UPDATED
![](http://www.safetysign.com/images/source/large-images/J6402.png)

2017-06-28 15:07 UTC, Cyberboss requested changes
You didn't change it https://github.com/tgstation/tgstation/pull/28858/commits/ac2085e0428041d7fddb316364fc80f142b5137f#diff-00843b2705408d5f51ac59356eceec1aR12

2017-06-28 15:46 UTC, Tacolizard commented
@Cyberboss the `HIGHEST_CHANNEL_AVAILABLE`? I didn't change it because some of the ratvar sounds are on higher channels, so I assumed that you don't need to update it.

2017-06-28 16:52 UTC, Cyberboss commented
All general sounds use channels <= HIGHEST_CHANNEL_AVAILABLE so whenever you add a new specific channel, like you are doing, you need to lower it as well

2017-06-28 18:36 UTC, Tacolizard commented
@Cyberboss 
pong

2017-06-28 18:40 UTC, Cyberboss requested changes

2017-06-28 18:40 UTC, Cyberboss commented on code/modules/surgery/organs/heart.dm
> +				H.playsound_local(src,'sound/health/fastbeat.ogg',40,0, channel = CHANNEL_HEARTBEAT)
The `stop_sound_channel`s aren't necessary, because playing the sound will overwrite whats currently playing on the channel

2017-06-28 18:48 UTC, Cyberboss requested changes

2017-06-28 18:48 UTC, Cyberboss commented on code/modules/surgery/organs/heart.dm
> +				H.playsound_local(src,'sound/health/fastbeat.ogg',40,0, channel = CHANNEL_HEARTBEAT)
Needs to be `H.playsound_local(get_turf(src),'sound/health/fastbeat.ogg',40,0, channel = CHANNEL_HEARTBEAT)`

2017-06-28 18:51 UTC, Tacolizard commented on code/modules/surgery/organs/heart.dm
> +				H.playsound_local(src,'sound/health/fastbeat.ogg',40,0, channel = CHANNEL_HEARTBEAT)
ok, well that's weird that it even worked.

2017-06-28 18:56 UTC, Cyberboss approved these changes

2017-06-28 19:01 UTC, merged