[WIP] The Photography Update - refactored photos, album persistence, large photos support and round based saving in logs
tgstation/tgstation pull request #28908
Opened 2017-06-28 20:10 UTC by kevinz000

2017-06-28 20:11 UTC, RemieRichards commented on code/game/gamemodes/miniantags/abduction/machinery/experiment.dm
> +		var/icon/I = icon(dissection_icon(occupant), dir = SOUTH)
lol @AnturK you hack.

2017-06-28 20:11 UTC, Tacolizard commented
dat changelog

2017-06-28 20:12 UTC, RemieRichards commented on code/modules/mob/living/silicon/robot/robot.dm
> +		connected_ai.aicamera.stored |= aicamera.stored
never use ```list |= val``` where you can use ```list[val] = TRUE```

2017-06-28 20:13 UTC, Shadowlight213 commented
\>picture persistence.
No more persistence features. Just stop

2017-06-28 20:13 UTC, kevinz000 commented
@Shadowlight213 what's the worst that can happen with making photo albums have a use?

2017-06-28 20:13 UTC, RemieRichards commented on code/modules/photography/_photos.dm
> +	var/icon/picture_image
fat lie, this is an ```/icon```

2017-06-28 20:15 UTC, RemieRichards commented on code/modules/photography/_photos.dm
> +		P.picture_image.Crop(cropx, cropy, psize_x - cropx, psize_y - cropy)
so in the above, you apply the operation to both icons.
but here only to one icon?

Why do you even need the second icon?
And why aren't you modifying it here? (is it some kind of immutable icon that represents the picture as it was taken?)

2017-06-28 20:16 UTC, nfreader commented
>Photos are now stored every round for Atlanta Ned to put on his site so we can laugh at embarresing moments 

See if you can include captions as well :)

2017-06-28 20:16 UTC, RemieRichards commented on code/modules/photography/camera.dm
> +	see_ghosts = 1
```TRUE```

2017-06-28 20:18 UTC, Shadowlight213 commented
My complaint is filesize mainly

2017-06-28 21:27 UTC, GunHog commented on code/modules/photography/ai_camera.dm
> +	C.toner -= 20	 //Cyborgs are very ineffeicient at printing an image
Could you make this cheaper? I doubt more than a handful of people would object if a borg could print out lots of photos.

2017-06-28 23:31 UTC, kevinz000 commented on code/modules/photography/ai_camera.dm
> +	C.toner -= 20	 //Cyborgs are very ineffeicient at printing an image
Sure

2017-06-30 02:16 UTC, Cyberboss requested changes

2017-06-30 02:16 UTC, Cyberboss commented on code/controllers/subsystem/persistence.dm
> +	file << json_encode(GLOB.picture_logging_information)
Use text2file

2017-06-30 02:16 UTC, Cyberboss commented on code/modules/photography/_photos.dm
> +//GLOBAL_PROTECT(picture_logging_information)			//pls no.
You're turning these on eventually right?

2017-06-30 02:16 UTC, Cyberboss commented on code/modules/photography/_photos.dm
> +GLOBAL_LIST_INIT(picture_logging_information, list())
GLOBAL_LIST_EMPTY(picture_logging_information)

2017-06-30 02:16 UTC, Cyberboss commented on code/modules/photography/camera.dm
> +			CHECK_TICK
This is just going to fuck up the photos

2017-06-30 02:16 UTC, Cyberboss commented on code/modules/photography/camera.dm
> +		CHECK_TICK
Ditto

2017-06-30 02:16 UTC, Cyberboss commented on code/modules/photography/camera.dm
> +		CHECK_TICK
Ditto

2017-06-30 09:58 UTC, Iatots commented
What do you mean by ID? Your C-key or whatever name you select at roundstart? Can I see and potentially mess with other people's albums by using their names?

2017-06-30 13:39 UTC, kevinz000 commented
@Iatots every picture generated has an ID used internally.

2017-06-30 13:39 UTC, kevinz000 commented on code/modules/photography/_photos.dm
> +//GLOBAL_PROTECT(picture_logging_information)			//pls no.
yep, it's disabled for testing, but leave the comment so i don't forget.

2017-06-30 14:27 UTC, kevinz000 commented on code/modules/photography/_photos.dm
> +		P.picture_image.Crop(cropx, cropy, psize_x - cropx, psize_y - cropy)
fixed, second icon is for photos having a small inhand icon that approximates its contents.

2017-06-30 14:28 UTC, kevinz000 commented on code/modules/photography/camera.dm
> +			CHECK_TICK
fixed, cameras now grab all atoms once.

2017-06-30 14:28 UTC, kevinz000 commented on code/modules/photography/camera.dm
> +		CHECK_TICK
fixed, cameras now grab all atoms once.

2017-06-30 14:28 UTC, kevinz000 commented on code/modules/photography/camera.dm
> +		CHECK_TICK
fixed, cameras now grab all atoms once.

2017-07-01 00:07 UTC, Tacolizard commented
>🆑 Skylar

2017-07-01 00:07 UTC, Tacolizard commented
you also didn't put a closing cl tag at the end of the changelog you weenie

2017-07-06 14:45 UTC, Cyberboss commented
@kevinz000

2017-07-06 14:57 UTC, RemieRichards commented on code/modules/admin/verbs/mapping.dm
> +			if(c2.layer <= c.layer)
>doesn't even handle planes

:/

2017-07-06 14:59 UTC, RemieRichards commented on code/modules/admin/verbs/mapping.dm
> +/proc/full_zlevel_picture(z)
HAHA wowee.
>getFlatIcon
>one of the slowest procs
>on all atoms on the Z level that are visible

No wonder it's locked behind debug stuff.

2017-07-06 16:38 UTC, kevinz000 commented
@Cyberboss I need your transit stuff since you insist on instant copying.

2017-07-07 08:39 UTC, kevinz000 commented on code/modules/admin/verbs/mapping.dm
> +			if(c2.layer <= c.layer)
......??????????!!!

2017-07-07 08:40 UTC, RemieRichards commented on code/modules/admin/verbs/mapping.dm
> +			if(c2.layer <= c.layer)
planes are like layers, they control the visual order of things.

2017-07-14 03:54 UTC, kevinz000 commented
im doing this when transit refactor is done

2017-07-14 03:54 UTC, closed without merging

2017-09-25 20:47 UTC, nicbn commented
Kevin do your shit

2017-10-06 11:40 UTC, nicbn commented
Kevinz finish your shit

2017-10-27 08:54 UTC, Bawhoppen commented
Finish this seriously, we need it