Replaces all instances of spawn() with addtimer/INVOKE_ASYNC
tgstation/tgstation pull request #28958
Opened 2017-06-30 18:14 UTC by kevinz000

some things to note:
rnd stuff will be done in the rnd pr because i don't want to give myself too many conflicts.
i don't know if doing it to the tooltips is a great idea
the disposals spawns semm needless since everything is already made at initialize unlike before when it used new() so i guess there shouldn't be problems?
Fixes #27136 as after this only R&D consoles will be the problem and I left a comment there.

2017-06-30 19:01 UTC, Cyberboss requested changes

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/reagents/reagent_containers/spray.dm
> +/obj/item/weapon/reagent_containers/spray/proc/do_spray(atom/A, wait_step, obj/effect/decal/chempuff/D, range, puff_reagent_left)
Use set waitfor = FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/recycling/disposal-unit.dm
> +	SSblackbox.inc("disposal_auto_flush",1)
no need for ,1

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/recycling/disposal-unit.dm
> +/obj/machinery/disposal/bin/proc/do_flush()
Use set waitfor = FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/recycling/disposal-unit.dm
> +				INVOKE_ASYNC(src, .proc/do_flush)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/reagents/reagent_containers/spray.dm
> +	INVOKE_ASYNC(src, .proc/do_spray, A, wait_step, D, range, puff_reagent_left)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/destructive_analyzer.dm
> +	icon_state = "d_analyzer_l"
use update_icon

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/destructive_analyzer.dm
> +	busy = 0
FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	icon_state = "h_lathe"
update_icon

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	addtimer(CALLBACK(src, .proc/del_dupes, dupes, counter), rand(10, 100))
You can use that qdel_list_proc you made instead

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +		explosion(user.loc, -1, rand(1,5), rand(1,5), rand(1,5), rand(1,5), flame_range = 2)
explosion(user, 0, ...

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +		visible_message("<span class='notice'>The [src]'s top opens, releasing a powerful blast!</span>")
\The

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	if(src.loc == user && userturf.z != ZLEVEL_CENTCOM) //Because Nuke Ops bringing this back on their shuttle, then looting the ERT area is 2fun4you!
remove src

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/research/rdconsole.dm
> +
Comment unecessary

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +/obj/effect/proc_holder/spell/dumbfire/proc/launch_at(turf/target, mob/user)
Use set waitfor = FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +		INVOKE_ASYNC(src, .proc/launch_at, target, user)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +		projectile:linked_spells += proj_type
please remove this colon if you can

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +			INVOKE_ASYNC(src, .proc/proj_trail, projectile)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +/obj/effect/proc_holder/spell/dumbfire/proc/proj_trail(obj/effect/proc_holder/spell/targeted/projectile)
Use set waitfor = FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +		trail.density = 0
FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/genetic.dm
> +	if(target && !QDELETED(target))
just !QDELETED(target)

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/projectile.dm
> +		INVOKE_ASYNC(src, .proc/launch, target, user)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/projectile.dm
> +		projectile:linked_spells += proj_type
colon

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/projectile.dm
> +			INVOKE_ASYNC(src, .proc/spawntrail)
standard call

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/projectile.dm
> +		trail.density = 0
FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/spells/spell_types/projectile.dm
> +/obj/effect/proc_holder/spell/targeted/projectile/proc/launch(mob/living/target, mob/user)
Use set waitfor = FALSE

2017-06-30 19:01 UTC, Cyberboss commented on code/modules/tooltip/tooltip.dm
> +	queueHide = showing ? 1 : 0
TRUE : FALSE

2017-06-30 19:13 UTC, kevinz000 commented on code/modules/spells/spell_types/dumbfire.dm
> +		projectile:linked_spells += proj_type
can i go "i'll do this in a later pr"? this actually looks like a pain in the ass and would probably require a full refactor if i was to do it.

2017-06-30 19:14 UTC, kevinz000 commented on code/modules/spells/spell_types/projectile.dm
> +		projectile:linked_spells += proj_type
refactor :^)

2017-06-30 19:19 UTC, Cyberboss commented on code/modules/spells/spell_types/dumbfire.dm
> +		projectile:linked_spells += proj_type
no

2017-07-01 00:02 UTC, Tacolizard commented
There shouldn't be any reason to do this with tooltips.

2017-07-01 00:03 UTC, Cyberboss requested changes

2017-07-01 00:03 UTC, Cyberboss commented
@Tacolizard if it uses spawn it has to go

2017-07-01 03:52 UTC, kevinz000 commented on code/modules/spells/spell_types/dumbfire.dm
> +/obj/effect/proc_holder/spell/dumbfire/proc/proj_trail(obj/effect/proc_holder/spell/targeted/projectile)
done

2017-07-01 03:52 UTC, kevinz000 commented on code/modules/recycling/disposal-unit.dm
> +/obj/machinery/disposal/bin/proc/do_flush()
done

2017-07-01 03:52 UTC, kevinz000 commented on code/modules/spells/spell_types/dumbfire.dm
> +/obj/effect/proc_holder/spell/dumbfire/proc/proj_trail(obj/effect/proc_holder/spell/targeted/projectile)
unless you mean remove the proc and just reinsert the code into the calling proc

2017-07-01 03:52 UTC, kevinz000 commented on code/modules/recycling/disposal-unit.dm
> +/obj/machinery/disposal/bin/proc/do_flush()
unless you mean remove the proc and just reinsert the code into the calling proc

2017-07-02 16:16 UTC, Cyberboss commented on code/modules/recycling/disposal-unit.dm
> +		flush()
Why this?

2017-07-02 16:23 UTC, Cyberboss requested changes

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/effects/smoke.ogg', 50, 1, -3)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/effects/smoke.ogg', 50, 1, -3)
playsound(src,...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/machines/ding.ogg', 50, 1) //Ding! Your death coffee is ready!
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/effects/smoke.ogg', 50, 1, -3)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/effects/supermatter.ogg', 50, 1, -3)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +			playsound(loc, 'sound/effects/supermatter.ogg', 50, 1, -3)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +		playsound(loc, 'sound/effects/supermatter.ogg', 50, 3, -1)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +				trackedIan.loc = loc
forceMove

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	playsound(loc, "sparks", rand(25,50), 1)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	playsound(loc, "sparks", rand(25,50), 1)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +	playsound(loc, "sparks", rand(25,50), 1)
playsound(src, ...

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/research/experimentor.dm
> +/obj/item/weapon/relic/proc/del_dupes(list/dupes, counter)
Unused proc

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
TRUE

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
Why does this have a param

2017-07-02 16:23 UTC, Cyberboss commented on code/modules/tooltip/tooltip.dm
> +	winshow(owner, control, 0)
FALSE

2017-07-02 16:27 UTC, kevinz000 commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
it's not a param it's a delay of 1 for whatever reason 
it's gooncode or somethign ask @Tacolizard but I didn't want to touch it.

2017-07-02 17:06 UTC, kevinz000 commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
not bool

2017-07-03 06:50 UTC, Tacolizard commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
i can't remember if this was gooncode or just copied from other tooltip shit. if you don't want to test it, I'd advise not touching it.

2017-07-03 06:51 UTC, Tacolizard commented on code/modules/tooltip/tooltip.dm
> +		addtimer(CALLBACK(src, .proc/do_hide), 1)
or wait what I didn't write this I didn't realize what you mean by tooltips this is wirewraith(?)'s tooltip code.

2017-07-04 14:49 UTC, Cyberboss commented
@kevinz000 fix the loc change

2017-07-05 16:51 UTC, kevinz000 commented
Ok give me a bit

2017-07-05 23:25 UTC, Cyberboss commented
@kevinz000 !!!!!!!!

On Jul 5, 2017 12:51 PM, "kevinz000" <notifications@github.com> wrote:

> Ok give me a bit
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/28958#issuecomment-313161756>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywepHObbWX58CWQYHCM4sH1Dr9IaP9ks5sK78kgaJpZM4OK5Zx>
> .
>

2017-07-06 02:12 UTC, kevinz000 commented
I JUST GOT TO A COMPUTER OK 6 HOURS I PROMISE

2017-07-06 02:13 UTC, kevinz000 commented
@Cyberboss FIXED

2017-07-06 02:15 UTC, Cyberboss approved these changes

2017-07-06 14:13 UTC, merged