Fixes cartridges not linking with their host PDAs on creation
tgstation/tgstation pull request #28989
Opened 2017-07-02 16:00 UTC by ohnopigeons

:cl:
fix: Nanotrasen Electronics have fixed a bug where issued factory-fresh PDAs did not link to their cartridges, requiring manual reinsertion.
/:cl:

I don't know why Initialize doesn't work in this case where New does. And I'm not going to figure out why. In fact I think I'll stop bothering with Initialize memes.

Fixes https://github.com/tgstation/tgstation/issues/28985

2017-07-02 17:47 UTC, Cruix commented
It is because the first variable of Initialize() is mapload

2017-07-02 23:33 UTC, Cyberboss requested changes
Do not revert this to New(). The problem is the `pda` parameter. Please read the documentation for Initialize

2017-07-05 04:15 UTC, Cyberboss commented
If you're absolutely sure that the loc is always a pda you can remove the parameter entirely and just do `var/obj/item/device/pda/pda = loc`

2017-07-06 01:02 UTC, Cyberboss approved these changes

2017-07-06 14:01 UTC, ohnopigeons commented on code/game/objects/items/devices/PDA/cart.dm
> +	if(istype(pda))
why not istype(pda, /obj/item/device/pda)?

2017-07-06 14:04 UTC, RemieRichards commented on code/game/objects/items/devices/PDA/cart.dm
> +	if(istype(pda))
the type of the variable ```pda``` is ```/obj/item/device/pda``` (see: ```var/obj/item/device/pda/pda = loc```), if ```istype()``` is not provided a 2nd argument, it instead uses the type of the variable.

This kind of ```istype()``` is basically ```is this variable what I think it is?``` as opposed to ```is this variable an instance of X?```

2017-07-06 14:06 UTC, merged

2017-07-06 14:07 UTC, RemieRichards commented on code/game/objects/items/devices/PDA/cart.dm
> +	if(istype(pda))
I don't actually like this kind of ```istype()``` being used on local variables (I like it for arguments only), I will have to hit @Cyberboss with a stick.

2017-07-06 14:08 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/cart.dm
> +	if(istype(pda))
n-nani?

2017-07-06 14:09 UTC, RemieRichards commented on code/game/objects/items/devices/PDA/cart.dm
> +	if(istype(pda))
*raises stick*