Refactors speech/communication logging and adds coordinates to speech logs
tgstation/tgstation pull request #28997
Opened 2017-07-03 02:35 UTC by Shadowlight213

Not tested at all yet.

I couldn't figure out the best way to avoid copypasta, so I went with an intermediate sorta proc that filters stuff back.
Some logging messages have had info added to them for clarity. For example, cult chat now clearly states its cult chat. Holopads show both the AI and holopad coordinates.

Getting a holoparasite is now logged.

2017-07-03 02:54 UTC, Cyberboss requested changes

2017-07-03 02:54 UTC, Cyberboss commented on code/__HELPERS/mobs.dm
> +/proc/log_talk(atom/user,message,type)
Varname other than type please

2017-07-03 02:54 UTC, Cyberboss commented on code/__HELPERS/mobs.dm
> +/proc/log_talk(atom/user,message,type)
mob/user

2017-07-03 02:54 UTC, Cyberboss commented on code/__HELPERS/mobs.dm
> +			warning("ERROR: invalid speech logging type detected. [type]. Defaulting to say")
This'll show up as WARNING: ERROR: in the logs

2017-07-03 02:54 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +	log_talk(src,"GUARDIAN:[src.real_name]/[src.key]: [input]",LOGSAY)
remove src

2017-07-03 02:54 UTC, Cyberboss commented on code/modules/mob/living/say.dm
> +				log_talk(src,"[mind.changeling.changelingID]/[src.key] : [message]",LOGSAY)
remove src

2017-07-03 02:54 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +				log_admin_private("[key_name(src.owner)] has a cookie from a banned account! (Matched: [found["ckey"]], [found["ip"]], [found["compid"]])")
remove src

2017-07-03 02:54 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +		log_talk(user,"[user] (PDA: [src.name]) sent \"[message]\" to Everyone",LOGPDA)
Remove src

2017-07-03 02:54 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +				log_talk(user,"[user] (PDA: [src.name]) sent \"[message]\" to [P.name]",LOGPDA)
Remove src

2017-07-03 14:36 UTC, nfreader commented
Most excellent. Thank you!

2017-07-04 19:08 UTC, Shadowlight213 commented
@Cyberboss changes made

2017-07-04 19:55 UTC, Cyberboss requested changes

2017-07-04 19:55 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +				log_admin("[key_name(src.owner)] has a cookie from a banned account! (Matched: [found["ckey"]], [found["ip"]], [found["compid"]])")
fix dis

2017-07-04 20:41 UTC, Shadowlight213 commented on code/modules/goonchat/browserOutput.dm
> +				log_admin("[key_name(src.owner)] has a cookie from a banned account! (Matched: [found["ckey"]], [found["ip"]], [found["compid"]])")
That should get undone by the other pr. I undid that and moved it to a separate pr.

2017-07-04 20:47 UTC, Cyberboss commented on code/modules/goonchat/browserOutput.dm
> +				log_admin("[key_name(src.owner)] has a cookie from a banned account! (Matched: [found["ckey"]], [found["ip"]], [found["compid"]])")
I don't see it anywhere?

2017-07-04 21:42 UTC, Shadowlight213 commented on code/modules/goonchat/browserOutput.dm
> +				log_admin("[key_name(src.owner)] has a cookie from a banned account! (Matched: [found["ckey"]], [found["ip"]], [found["compid"]])")
#29012
I changed the line back to avoid merge conflicts.
If you look at the overall diff, it didn't revert that pr.

2017-07-06 19:52 UTC, Cyberboss approved these changes

2017-07-06 20:06 UTC, merged