Adds Necropolis curses for cursed items in Necropolis ruins
tgstation/tgstation pull request #28992
Opened 2017-07-02 20:59 UTC by ChangelingRain

This is just the status effect for curses, no cursed items yet.
Curses include:
Blinding, obscures edges of screen.
Spawning, spawns aggressive curse smoke that only you can fight.
Wasting, slow health loss.
Grasping, arms of curse smoke will try to grab you.

Sprites credit @FuryMcFlurry
![](http://puu.sh/wzYjb/fc30a99d14.png)

2017-07-02 21:08 UTC, PraiseRatvar commented
wot, no hallucinations!?!?

seriously tho, add at least one of these effects to the hallucination fodder

2017-07-02 21:15 UTC, DoctoreMad commented
Does it go away with anything, like holy water?

2017-07-02 21:23 UTC, WJohn commented
these are crazy high quality sprites. mad props to flurry.

2017-07-02 21:30 UTC, FuryMcFlurry commented
I abused the special effects in paint.net so mad props to the software engineers of paint.net. if needed I can add more 'curse' sprites as those 4 legged blobs seem not that interesting.

2017-07-02 21:40 UTC, Jazaen commented
I heard you liek Don't Starve, so I put some Don't Starve in your spessmens.

2017-07-02 22:32 UTC, Supermichael777 commented
MY EYES SO PURE

2017-07-04 11:41 UTC, RemieRichards commented on code/datums/status_effects/debuffs.dm
> +		var/obj/effect/temp_visual/dir_setting/curse/C = new (owner.loc, owner.dir)
please stop creating this again every tick, reuse it.

2017-07-04 11:47 UTC, RemieRichards commented on code/datums/status_effects/debuffs.dm
> +			switch(owner.dir)
convert all of this into:

```
if(curse_flags & CURSE_GRASPING)
    var/grab_dir = turn(owner.dir, pick(-90,90,180))
    var/turf/spawn_turf = get_ranged_target_turf(owner, grab_dir, 5)
    if(spawn_turf)
        INVOKE_ASYNC(src, .proc/grasp, spawn_turf)
```

2017-07-04 11:48 UTC, RemieRichards commented on code/datums/status_effects/debuffs.dm
> +	if(CURSE_BLINDING & curse_flags)
eww wtf.
don't do this.
```bitfield & flag``` definitely NOT ```flag & bitfield```

2017-07-06 14:28 UTC, Cyberboss requested changes

2017-07-06 14:28 UTC, Cyberboss commented on code/datums/status_effects/debuffs.dm
> +	return ..()
wasting_effect = null before this line

2017-07-06 14:28 UTC, Cyberboss commented on code/datums/status_effects/debuffs.dm
> +	new/obj/effect/temp_visual/dir_setting/curse/grasp_portal(spawn_turf, owner.dir)
Just make this a regular proc call with set waitfor = FALSE

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
> +	deltimer(timerid)
datum/Destroy will do this

2017-07-06 14:28 UTC, Cyberboss commented on code/game/objects/effects/temporary_visuals/miscellaneous.dm
> +	icon_state = "[icon_state][handedness]"
update_icon()

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
> +	if(doing_move_loop)
set waitfor = FALSE > INVOKE_ASYNC

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
> +	return ..()
Could make all these a define: 
`#define IGNORE_PROC_IF_NOT_TARGET(X) /mob/living/simple_animal/hostile/asteroid/curseblob/##X(AM) { if (AM == set_target) return ..(); }`

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile.dm
> +			loc = target_turf
forceMove

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile/special.dm
> +	icon_state = "[icon_state][handedness]"
update_icon

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile/special.dm
> +	var/turf/T = get_step(loc, dir)
get_step(src, dir)

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile/special.dm
> +		qdel(G)
QDEL_LIST(starting)?

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile/special.dm
> +		animate(B, alpha = 0, time = 32)
Typeless?

2017-07-06 14:28 UTC, Cyberboss commented on code/modules/projectiles/projectile/special.dm
> +	if(forcedodge)
arm = null before this line

2017-07-06 14:33 UTC, ChangelingRain commented on code/modules/projectiles/projectile.dm
> +			loc = target_turf
I don't know if that does anything bad in relation to projectile code and I don't want to break anything finding out

2017-07-06 14:33 UTC, ChangelingRain commented on code/modules/projectiles/projectile/special.dm
> +		qdel(G)
starting is a turf, ie, fuck no

2017-07-06 14:47 UTC, ChangelingRain commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm
> +	deltimer(timerid)
It actually won't and I remember there being a bug or something due to it... though that might have been pooling so I'll remove it and hope nothing breaks

2017-07-06 15:14 UTC, Cyberboss approved these changes

2017-07-06 15:14 UTC, merged