[WIP]Cross-station newscaster feeds!
tgstation/tgstation pull request #29022
Opened 2017-07-04 02:01 UTC by kevinz000

- When someone writes a newscaster channel, message, or comment the following will happen (once I get it fully working and tested)
- Newscaster channel : It will be created on the server, as well as the linked server (so someone making a channel on bagil will create it on bagil AND sybil)
- Newscaster message: A newscaster message will create its host channel on the linked server and send itself over to that channel if one doesn't exist, or it will append itself to the channel on the linked server if one does
- Newscaster comment: A newscaster comment will send itself to the other server if both the host message and its host channel are existing on the other server.
- Backend information: Code will encode things into JSON and send them over with params for the recieving server to decode and inject into the global newscaster network
- As for pictures, since I'm lazy I'm planning for them to be bicon'd so I don't have to use world.Import() but uh, that's an option if bicon is shit or something.

TL;DR news reporting becomes fun.

2017-07-04 02:02 UTC, JamieH commented
Can Hippie and /tg/ work together to link the news casters between us? It'd be funny as fuck.

2017-07-04 02:05 UTC, MrStonedOne commented
Our rules are different, that would be bound to generate issues

2017-07-04 02:07 UTC, JamieH commented
You could have optional admin approval for outgoing/incoming stuff

2017-07-04 05:19 UTC, Iamgoofball commented
@MrStonedOne We could always just add a "jobban" that stops your shit from being sent across the dimension.

2017-07-04 06:35 UTC, ike709 commented
Or I could shill FTL13 and propose cross-server news between /tg/ and FTL13.

I like the idea of news being shared between a random Nanotrasen ship and a random Nanotrasen station.

2017-07-04 07:18 UTC, FantasticFwoosh commented
Downvoting because people abuse the cross station announcements all the while, people can't be trusted to actually make detailed journalistic pieces for issues of meta, spam and general garbage.

Issues surrounding people leaving meta-comments on the newscasters for what is technically IC meta-communication, and ghosts viewing newscasters prior to death and then server hopping and other shitty behavior. With access to every newscaster its hard to bottleneck and enforce too during busy rounds.
___________________________________________________________
As to positive feedback mekhi, without reading the code because i need my caffiene first, make sure that newspapers correctly reference the source of their news reports.

2017-07-04 07:43 UTC, RemieRichards commented
I agree we need to be able to sent photocopies of our bums to hippie and FTL.

2017-07-04 10:54 UTC, GunHog commented
What happens when the round ends? If I post a channel on the newscaster while on Basil, will Sybil players see it after the round on Basil ends? Would I see it again on the next round if Sybil players post on my feed?

2017-07-04 11:01 UTC, RemieRichards commented
That's an interesting idea @GunHog 
Imagine keeping a newscaster channel going.
forever.

2017-07-04 11:26 UTC, Iamgoofball commented
i think it'll be fine and you're all really worried about nothing

2017-07-04 11:29 UTC, RemieRichards commented
I'm saying it's a good thing.
Imagine juggling a channel back and forth between basil and sybil, forever* (* a long time).

2017-07-04 11:30 UTC, Iamgoofball commented
and hippie and ftl and yog

2017-07-04 14:15 UTC, FantasticFwoosh commented
Ill just block all the channels from the security office/HOS office then and mark them dangerous, hah.

2017-07-04 14:23 UTC, octareenroon91 commented
>What happens when the round ends? If I post a channel on the newscaster while on Basil, will Sybil players see it after the round on Basil ends? Would I see it again on the next round if Sybil players post on my feed?

The channel would effectively be pruned on each station with every round-end.


>IC
>metacomm

Can't both be true.

2017-07-04 17:16 UTC, kevinz000 commented
@GunHog when round end the news netwrok is wiped as normal, but if someone on the other server makes a new message on a feed channel that feed channel is automatically made again on the original server, but it'll be marked as external

@FantasticFwoosh i'm planning on making something that automatically marks them as external channels.

2017-07-04 17:50 UTC, nfreader commented
>Backend information: Code will encode things into JSON and send them over with params for the recieving server to decode and inject into the global newscaster network

_cough_ bet you won't add feedback logging for newscasters _cough_

2017-07-04 19:51 UTC, Cyberboss requested changes
@RemieRichards may want to use JATUM for this

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/locked = 0
FALSE

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/is_admin_message = 0
FALSE

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/icon/img = null
Remove ` = null`

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/txt = "[GLOB.news_network.redactedText]"
var/txt = GLOB.news_network.redactedText

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/txt = "[GLOB.news_network.redactedText]"
var/txt = GLOB.news_network.redactedText

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/locked = 0
FALSE

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/censored = 0
FALSE

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/network_datum.dm
> +	var/is_admin_channel = 0
FALSE

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	var/scribble_page = null
Remove = null

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	var/obj/W = new /obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey(H.loc)
var/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey/W = new (get_turf(H))

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	playsound(H.loc, 'sound/items/drink.ogg', rand(10,50), 1)
playsound(H, ...

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	user.say(";JOURNALISM IS MY CALLING! EVERYBODY APPRECIATES UNBIASED REPORTI-GLORF")
No radio suicides

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	user.visible_message("<span class='suicide'>[user] downs the contents of [W.name] in one gulp! Shoulda stuck to sudoku!</span>")
Add a second param

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	user.visible_message("<span class='suicide'>[user] downs the contents of [W.name] in one gulp! Shoulda stuck to sudoku!</span>")
of [W]

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	user.visible_message("<span class='suicide'>[user] is focusing intently on [src]! It looks like [user.p_theyre()] trying to commit sudoku... until [user.p_their()] eyes light up with realization!</s
Add a second param

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +	return(TOXLOSS)
remove brackets

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(0) //Cover
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +		var/dat
list

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(2) //Last page
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(1) // X channel pages inbetween.
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +		human_user << browse(dat, "window=newspaper_main;size=300x400")
dat.Join("\<br>")

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			playsound(loc, "pageturn", 50, 1)
src not loc

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +				screen = 2
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +					screen=1
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(curr_page == 0)
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(curr_page == 1)
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +				screen = 0
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +					screen = 1
define

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			playsound(loc, "pageturn", 50, 1)
src not loc

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			attack_self(loc)
never call attack_self directly, make a different proc

2017-07-04 19:51 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			attack_self(user)
never call attack_self directly, make a different proc

2017-07-04 20:44 UTC, RemieRichards commented
Yes, a good potential candidate for JATUM.
perhaps an excuse to get off my ass and do the last 10% of the Deserialiser.

2017-07-05 11:42 UTC, Durkel commented
I like this idea but I can't help but shake the feeling that this is just going to be used to call each other faggots.

2017-07-05 12:48 UTC, Iamgoofball commented
@MrStonedOne 
another option is we let servers add a word blacklist

we can just add shit to that

2017-07-09 01:22 UTC, MimicFaux commented
This is a very cool idea, and I'd like to see it at least given a test-drive.

2017-07-11 09:13 UTC, optimumtact commented
Given that it's just newspapers, I don't see what the harm would be, differing rulesets aside.

At worst you can only print something you find offensive to yourself and then get upset at it.

2017-07-11 09:25 UTC, optimumtact commented on code/game/machinery/newscaster/newspaper.dm
> +		U.set_machine(src)
in the year 1950

2017-07-12 07:22 UTC, MrStonedOne commented
allright, i'll greenlight the global station news caster network.

@kevinz000 make a seperate config for a list of servers to send these notices to, as well as their coms key, (since it would be different), add a delay and reject time for incoming and outgoing messages, 60 seconds would likely be enough, add a button to temporarily disable incoming news caster entries from a given server for admins with +ban or +server.

This could be a seperate pr if needed.

2017-07-12 09:39 UTC, kevinz000 commented
ok

2017-07-18 15:49 UTC, Cyberboss requested changes

2017-07-18 15:49 UTC, Cyberboss commented on code/_globalvars/sensitive.dm
> +GLOBAL_REAL_VAR(comms_allowed) = TRUE //By default, the server does not allow messages to be sent to it, unless the key is strong enough (this is to prevent misconfigured servers from becoming vulner
No, keep this false

2017-07-18 15:49 UTC, Cyberboss commented on code/_globalvars/sensitive.dm
> +GLOBAL_REAL_VAR(newscaster_relay_list) = list()			//List of server address = newscaster keys, for news relaying.
This doesn't need to be a real global

2017-07-18 15:49 UTC, Cyberboss commented on code/controllers/configuration.dm
> +	load_cross_news_list("config/newscaster_relay.txt")
This proc should be in this file

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	..()
Initialize, . = ..()

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	armor = list(melee = 50, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0, fire = 50, acid = 30)
unquoted lis associations

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	obj_integrity = 200
remove this line

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	var/obj/item/weapon/photo/photo = null
remove ` = null`

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	var/datum/newscaster/feed_channel/viewing_channel = null
remove ` = null`

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	anchored = 1
new vars after parent vars and TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	var/allow_comments = 1
TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	securityCaster = 1
TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	var/securityCaster = 0
FALSE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +		pixel_y = (dir & 3)? (dir ==1 ? -32 : 32) : 0
Use dir defines

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +		unit_no++
use .len

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +			update_icon()
Timer

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +	return attack_hand(user)
Don't call interaction procs directly

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +					var/wanted_already = 0
FALSE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +						wanted_already = 1
TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +				var/check = 0
FALSE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +						check = 1
TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +				if(FC.channel_name ==
forceMove

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +				if(FC.channel_name ==
TRUE

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newscaster_machine.dm
> +				if(FC.channel_name ==
Assigning it then qdeling it? wtf?

2017-07-18 15:49 UTC, Cyberboss commented on code/game/machinery/newscaster/newspaper.dm
> +			if(curr_page == 1)
Defines

2017-07-18 15:49 UTC, Cyberboss commented on config/newscaster_relay.txt
> +#Note that newscaster comms key is not the same thing as regular comms key!
Double ## and space after for all these lines

2017-07-18 17:01 UTC, dannno commented
I really hope this encourages a bit more commonplace use of the newscasters, they're such a neat little feature

2017-07-22 03:02 UTC, kevinz000 commented on code/_globalvars/sensitive.dm
> +GLOBAL_REAL_VAR(comms_allowed) = TRUE //By default, the server does not allow messages to be sent to it, unless the key is strong enough (this is to prevent misconfigured servers from becoming vulner
debug thing but yeah leave this here so i don't forget

2017-07-22 03:02 UTC, kevinz000 commented on code/_globalvars/sensitive.dm
> +GLOBAL_REAL_VAR(newscaster_relay_list) = list()			//List of server address = newscaster keys, for news relaying.
this has their newscaster comms keys though.

2017-07-25 09:05 UTC, kevinz000 commented
it occured to me that i should stop fragmenting my time across 20000 prs.

2017-07-25 09:05 UTC, closed without merging

2017-07-26 01:36 UTC, octareenroon91 commented
Please advise: how close to mergeready is this?