Goon chat is now a preference
tgstation/tgstation pull request #29035
Opened 2017-07-04 17:47 UTC by MrStonedOne

I've noticed that my pc actually lags a bit with goon chat, so, since @MrStonedOne gave us the option of doing this, might aswell do it.

2017-07-04 17:50 UTC, ChangelingRain requested changes
https://github.com/tgstation/tgstation/pull/29005#issuecomment-312762536

2017-07-05 02:48 UTC, Cyberboss requested changes

2017-07-05 02:48 UTC, Cyberboss commented on code/modules/client/preferences.dm
> +	var/fancy_chat = TRUE
This will actually default to FALSE because default preference values don't work for some reason. Maybe invert the logic?

2017-07-05 03:09 UTC, optimumtact commented
what a shit idea

2017-07-05 04:26 UTC, lzimann commented on code/modules/client/preferences.dm
> +	var/fancy_chat = TRUE
It did seem to default to TRUE on testing though.

2017-07-05 04:27 UTC, Cyberboss commented on code/modules/client/preferences.dm
> +	var/fancy_chat = TRUE
>known clients

2017-07-05 19:21 UTC, MrStonedOne commented
I'LL MAKE MY OWN BRANCH OF THIS CHANGE.

WITH BLACK JACK, AND UNSUPPORTED WARNINGS.

2017-07-05 19:21 UTC, closed without merging