Fixes holodeck not having the correct area
tgstation/tgstation pull request #29043
Opened 2017-07-04 21:33 UTC by lzimann

Fixes #29010

Completly forgot about `locate()` returning subtypes. This also changes so items only display the `fades away` message when the holodeck was forced off(power goes off, it gets damaged, etc) so there's less chat spam.

2017-07-05 01:48 UTC, Cyberboss commented on code/modules/holodeck/computer.dm
> -/obj/machinery/computer/holodeck/proc/finish_spawn()
This was removed why?

2017-07-05 02:15 UTC, lzimann commented on code/modules/holodeck/computer.dm
> -/obj/machinery/computer/holodeck/proc/finish_spawn()
Oh, I was just checking something and forgot to re-add.

2017-07-05 04:58 UTC, Cyberboss requested changes
^

2017-07-06 14:09 UTC, Cyberboss approved these changes

2017-07-06 14:09 UTC, merged