Adding the mook/wanderer mob for planetstation
tgstation/tgstation pull request #29046
Opened 2017-07-04 22:02 UTC by Ergovisavi

Adds another mob for planetstation, the mook/wanderer. They're low health mobs (45, which is three knife stabs) and intended to be fairly unthreatening while solo. In groups they become significantly harder to deal with as your opportunities to attack are diminished.

Designed to be an easier to read combatant where you can tell its states a bit better and shouldn't get meleed "at random".

They look like this:
![mook](https://user-images.githubusercontent.com/4465459/27843511-51fdd1d0-60c9-11e7-8dd1-fa055eb4da20.png)

* Also fixes a small bug with player controlled leapers where they couldn't fire sometimes.

:cl:
add: Adds another planetstation mob, the "wanderer/mook" to the backend
fix: Fixes a problem with player controlled leapers where they occasionally can't fire
/:cl:

2017-07-04 22:13 UTC, ChangelingRain commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	pixel_y = -16
I feel like this is weird since it means their feet are lower than the turf they're on; same for the leaper, actually

2017-07-04 22:41 UTC, dannno commented
cool ass sprite

2017-07-04 23:00 UTC, Ergovisavi commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	pixel_y = -16
Visually makes sense to me but maybe I have a fucked up sense of aesthetics. If people think that their pixel_y shouldn't be modified I don't have any qualms changing it to 0, I guess.

2017-07-05 00:11 UTC, RandomMarine commented
If it wields a hatchet it should drop a hatchet.

2017-07-05 00:37 UTC, Ergovisavi commented
@RandomMarine This is just establishing the mob, like with the Leaper. All loot and stuff like that will come after the fact... if I ever finish up on these mobs.

2017-07-05 01:02 UTC, PKPenguin321 commented
these sprites are so good

it would be neat if these guys were their own race native to planetstation but that would probably definitely be too different from what's already going on here

2017-07-05 01:06 UTC, Armhulen commented
we should really replace ashwalkers with these cool looking guys

2017-07-05 01:25 UTC, Armhulen commented
also it's another i get really excited about new mobs episode

2017-07-05 02:06 UTC, Repukan commented
Why not add a variant of them to Steelpoint'caust ruin?

2017-07-05 02:06 UTC, Repukan commented
Due to crashed ship and shit, they're weak anyways, right?

2017-07-05 03:38 UTC, WJohn commented
Interesting that it has actual attack animations.

I'm not a huge fan of how it doesn't follow the 100% side view that mobs are supposed to have. Heck, even the front sprite isn't really facing the front, it's slightly at an angle (or maybe I'm looking at it wrong).

Cool sprite otherwise.

2017-07-05 04:54 UTC, DoctoreMad commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
No I can't. I can't figure it out at all.

2017-07-05 06:13 UTC, DoctoreMad commented
Also I know ash liggers are shit but why would those replace them? They're kinda huge for a ghost spawn player character.

2017-07-05 06:56 UTC, Ratvar commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
autocloned descendants of past ships

2017-07-05 08:45 UTC, Armhulen commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
OH MY GOD IT'S THE SHELLS

2017-07-05 08:45 UTC, Armhulen commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
GASP

2017-07-05 08:49 UTC, Iamgoofball commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
why is this on the base simple animal

2017-07-05 09:22 UTC, Ergovisavi commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
Oops. Bad copy paste lol. Will fix.

2017-07-05 09:58 UTC, RemieRichards commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	pixel_y = -16
almost (actually no?) no mobs/objects extend below their turf.
Plenty extend NORTH, SOUTH and EAST out of their turf, but none below (SOUTH).

2017-07-05 14:13 UTC, dannno commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
do you mean diseased instead of deceased?

2017-07-05 16:18 UTC, DoctoreMad commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
This is a desc only for when the mob dies.

2017-07-05 19:11 UTC, FantasticFwoosh commented
Mooks are simple creatures, its a shit excuse to edge them out of the game when ashwalkers are superior because mooks are weaker.

> _Replace ashwalkers with mooks, suddenly lavaland ashwalker ruin is just a mook camp miners can clear out in 10 seconds_. Yeah unless you have a arguement that's a shitty and selfish reason to support them without actually giving a damn about planetstation.

If the consistent plan is to make a above & belowground, i can't see why not just keep ashwalkers as the below ground natives, and Mook's just as a annoying pest aboveground as the OP has provided with the commit detail.

2017-07-05 20:08 UTC, XDTM commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	desc = "A deceased and unhealthy looking primitive. Upon closer inspection, it was suffering from severe cellular degeneration and its garments are machine made..."//Can you guess the twist
time to reopen my shell pr, the lore is in

2017-07-05 21:47 UTC, Niknakflak commented
That sprite looks so out of place and made for another game it's not even funny.  
Heck, was it even made for ss13 or is it torn out of someplace ergo?

2017-07-05 22:27 UTC, Ergovisavi commented
Like the leaper mob's sprites, I created it myself.

2017-07-06 00:47 UTC, Ergovisavi commented
Removed the pixel_y offset on the leaper, changed the pixel_y offset on the mook to make it so it doesn't extend past the southern part of the tile it's on, fixed the description change on death pointing at all simple mobs

2017-07-06 01:32 UTC, Cyberboss requested changes

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	stat_attack = 1
I think this is a bool

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	robust_searching = 1
I think this is a bool

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	ranged = 1
I think this is a bool

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +			return 1
TRUE

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +					if(L.incapacitated() && L.stat < 2)
stat != DEAD

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +		if(prob(40) && !ckey)
use !client instead

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +			icon_state = "mook"
put this in update_icon

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +		notransform = FALSE
You shouldn't be touching notransform

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +		notransform = TRUE
You shouldn't be touching notransform

2017-07-06 01:32 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +			icon_state = "mook_strike"
put this in update_icon

2017-07-06 01:40 UTC, ChangelingRain commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +		notransform = FALSE
that would be ideal; a better fix would be to make simple animals respect being stunned, and thus apply a stun that ignores their lack of CANSTUN flag

2017-07-06 02:09 UTC, Ergovisavi commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +		notransform = FALSE
What else do we have for "FUCK YOU, YOUR INPUTS DO NOT MATTER", that isn't also available to players somehow?

2017-07-06 13:33 UTC, Ergovisavi commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	stat_attack = 1
Nope. stat_attack = 0 means you only attack the awake, 1 includes unconscious, 2 includes dead.

2017-07-06 13:35 UTC, RemieRichards commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +	stat_attack = 1
Then you should use defines.
(Amusingly, these line up perfectly with CONSCIOUS, UNCONSCIOUS, DEAD)

2017-07-06 15:16 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> -			icon_state = "mook_strike"
did you actually put an entry in update icons for this?

2017-07-07 04:39 UTC, Ergovisavi commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> -			icon_state = "mook_strike"
I did. All the icons are working properly.

2017-07-07 04:41 UTC, Ergovisavi commented
This is ready whenever.

2017-07-07 15:23 UTC, Cyberboss requested changes

2017-07-07 15:23 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
> +				if(density == FALSE)
if(!density)

2017-07-07 17:42 UTC, Cyberboss approved these changes

2017-07-07 19:15 UTC, merged