New portable generator icons
tgstation/tgstation pull request #29097
Opened 2017-07-07 00:12 UTC by KorPhaeron

:cl: Lexorion
add: The portable PACMAN generators now have new icons, including on and off states.
/:cl:

@Lexorion can add pictures I'm too lazy

2017-07-07 00:12 UTC, Niknakflak commented
It takes 5 seconds with file.house come on

2017-07-07 00:13 UTC, Lexorion commented
I said I would do it,sorry NikNak editing this post in a second

2017-07-07 04:36 UTC, DoctoreMad commented
TODO List: Make not 3/4

2017-07-07 06:51 UTC, fludd12 commented
These are insanely pretty holy frick

2017-07-07 10:42 UTC, WJohn commented
Good shit lexorion.

2017-07-07 12:58 UTC, ChangelingRain commented
The diamond pacman looks like its animation cycle is slightly off compared to the other two, though.

2017-07-07 13:00 UTC, RemieRichards commented
Off in what way. slow? fast? It doesn't appear wrong.

2017-07-07 13:01 UTC, RemieRichards commented
Oh hmm, the blue pixels in the center of each column last for 1 frame more than they should, you're right.

2017-07-07 14:01 UTC, Cyberboss requested changes

2017-07-07 14:01 UTC, Cyberboss commented on code/modules/power/port_gen.dm
> +	var/base_icon = "portgen0"
new vars after parent vars

2017-07-07 17:03 UTC, Lexorion commented
It's not easy to notice but looks like you are right. Mind if I do this in a different PR?

2017-07-07 18:09 UTC, Armhulen commented
keep the old genny sprites for ancientstation

2017-07-08 00:44 UTC, Cyberboss approved these changes

2017-07-08 03:28 UTC, merged