Dreams while sleeping are now slightly longer on average and will contain more possibilities
tgstation/tgstation pull request #29104
Opened 2017-07-07 02:19 UTC by ChangelingRain

:cl: Joan
tweak: Dreams while sleeping are now slightly longer on average and will contain more possibilities.
rscadd: Bedsheets may affect what you can dream.
/:cl:

2017-07-07 02:30 UTC, lordpidey commented on code/game/objects/structures/bedsheet_bin.dm
> +	dream_messages = list("mining", "stone", "a golem", "freedom")
I feel you should add the liberator's magic words of "Yeah, sure go do whatever."

2017-07-07 02:48 UTC, lordpidey commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
Any chance this could be replaced with a timer?

2017-07-07 02:55 UTC, Shadowlight213 commented on code/game/objects/structures/bedsheet_bin.dm
> +	dream_messages = list("authority", "a golden ID", "sunglasses", "a green disc", "an antique gun", "the captain")
add "a condom" to the list

2017-07-07 13:42 UTC, Cyberboss requested changes

2017-07-07 13:42 UTC, Cyberboss commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
Make this a timer

2017-07-07 13:48 UTC, octareenroon91 commented on code/game/objects/structures/bedsheet_bin.dm
> +	dream_messages = list("mining", "stone", "a golem", "freedom")
`"doing whatever"`

2017-07-07 13:50 UTC, ChangelingRain commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
There is no reasonable way to make this a timer without allowing dreams to stack up, since it depends on the `dreaming` var being set to FALSE.

2017-07-07 13:54 UTC, Cyberboss commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
Make it a counter then and decrement it each time one of them fires?

2017-07-07 13:55 UTC, lordpidey commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
The dreaming var is literally not used anywhere outside of this file.

2017-07-07 13:56 UTC, octareenroon91 commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
````
var/dream_sequence = list("...")
for(var/i in 1 to rand(3, rand(5, 10)))
    dream_sequence += pick_n_take(dreams)

/* timing and to_chat here*/
````

2017-07-07 14:04 UTC, ChangelingRain commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
@lordpidey that's not relevant? at all?

2017-07-07 14:08 UTC, lordpidey commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
@ChangelingRain The dreaming var is literally never read from.  Thus: depending on the dreaming var being set to FALSE isn't true.

2017-07-07 14:13 UTC, Cyberboss requested changes

2017-07-07 14:13 UTC, Cyberboss commented on code/modules/flufftext/Dreaming.dm
> +/mob/living/carbon/var/dreaming = 0
carbon_defines.dm

2017-07-07 15:03 UTC, Cyberboss approved these changes

2017-07-07 19:38 UTC, ChangelingRain commented on code/modules/flufftext/Dreaming.dm
> +		sleep(rand(30,60))
Uh, dude, it IS literally read from. Read the fucking code.

2017-07-08 00:16 UTC, bgobandit commented on code/game/objects/structures/bedsheet_bin.dm
> +	dream_messages = list("authority", "a silvery ID", "healing", "life", "surgery", "a cat", "the chief medical officer")
"stuttering"
"floor length braids"

2017-07-08 00:17 UTC, bgobandit commented on code/game/objects/structures/bedsheet_bin.dm
>  	desc = "You might dream of Nar'Sie if you sleep with this. It seems rather tattered and glows of an eldritch presence."
"Nar'Sie" isn't even on the list this is false advertising

2017-07-08 02:17 UTC, merged

2017-07-08 10:19 UTC, FantasticFwoosh commented
Good job, nobody will see this feature outside of the instances they are 10 seconds before they ragequit and log out of client in a non-stop N20 gas leak or are going to be killed after intaking 30+ ounces of morphine  because the other PR with healing will never be merged, its pointless.

Nobody in the game sleeps because the gameplay is "Too slow" for some.

2017-07-08 15:11 UTC, lordpidey commented
No, I'd hazzard to guess that nobody sleeps because there's no reason to.