true & false (cyberboss wet dream PR)
tgstation/tgstation pull request #29144
Opened 2017-07-08 20:57 UTC by ShizCalev

2017-07-08 20:58 UTC, kevinz000 commented
oh boy time to have all of my major prs killed by merge conflicts!!!!

2017-07-08 21:04 UTC, Armhulen commented
get good!

2017-07-08 22:44 UTC, Cyberboss requested changes
Good PR

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	return ((secondsMainPowerLost == FALSE || secondsBackupPowerLost == FALSE) && !(stat & NOPOWER))
Wrong here just use !seconds...

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +						src.justzap = FALSE
Remove src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +		src.spawnPowerRestoreRunning = TRUE
remove src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	if(src.secondsBackupPowerLost == FALSE)
remove src, also wrong just use !seconds...

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +		src.aiHacking = TRUE
remove src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	if(src.aiHacking == FALSE)
!aiHacking

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +			src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +		src.aiHacking = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +						src.aiDisabledIdScanner = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					if(src.secondsMainPowerLost == FALSE)
src also just !

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					if(src.secondsBackupPowerLost == FALSE)
src also just !

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +						src.aiDisabledIdScanner = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +		if(beingcrowbarred == FALSE) //being fireaxe'd
just !

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	src.density = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	src.locked = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +	src.locked = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +		src.operating = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +	src.density = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +		src.operating = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +	src.operating = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +	src.density = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/doors/windowdoor.dm
> +	src.operating = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/robot_fabricator.dm
> +					src.operating = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/machinery/robot_fabricator.dm
> +						src.operating = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/game/objects/items/toys.dm
> +		if(hacked == FALSE)
!hacked

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/admin/verbs/mapping.dm
> +		intercom_range_display_status = TRUE
interblahblah = !interblahblah

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/atmospherics/gasmixtures/gas_types.dm
> +	moles_visible = TRUE
Wrong

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/gibber.dm
> +	src.operating = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/gibber.dm
> +		src.operating = FALSE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/processor.dm
> +	src.processing = TRUE
src

2017-07-08 22:44 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/processor.dm
> +	src.processing = FALSE
src

2017-07-08 22:48 UTC, Fox-McCloud commented
Be very careful with this, it's easy to think something is boolean, when it's really not.

2017-07-09 00:21 UTC, MoreRobustThanYou commented
cyberboss, just enjoy your wettest dream ever

2017-07-09 00:21 UTC, MoreRobustThanYou commented
@Fox-McCloud doesn't matter, TRUE is just 1. FALSE is just 0.

2017-07-09 00:47 UTC, ExcessiveUseOfCobblestone commented
@MoreRobustThanYou so then what's the problem with leaving them all 0/1s.

The whole point of the defines is to make it clear to the person reading the code because it's a lot easier to click the 0 key than it is to type FALSE or TRUE. With that said, it's important to not make something that isn't True/False appear as such.

2017-07-09 01:03 UTC, MoreRobustThanYou commented
@ExcessiveUseOfCobblestone cleanness

2017-07-09 01:45 UTC, ExcessiveUseOfCobblestone commented
WRONG

2017-07-09 01:52 UTC, MoreRobustThanYou commented
@ExcessiveUseOfCobblestone consistency and butts

2017-07-09 21:49 UTC, DoctoreMad commented
Wait, does any of this actually matter?

2017-07-09 21:50 UTC, ShizCalev commented
technicalllllllllllllly

no, not at all.

2017-07-09 22:12 UTC, optimumtact commented
This is an absolutely terrible idea

2017-07-09 22:13 UTC, optimumtact commented
Are you just converting every single 0 and 1 to true and false? or are you actually checking?

2017-07-09 23:11 UTC, ShizCalev commented
Actually checking.

2017-07-10 00:47 UTC, Cyberboss requested changes

2017-07-10 00:47 UTC, Cyberboss commented on code/modules/admin/verbs/mapping.dm
>  		intercom_range_display_status = TRUE
No i meant these entire 4 lines -> `intercom_range_display_status = !intercom_range_display_status`

2017-07-10 02:16 UTC, optimumtact commented
okay well in that case it's a good idea +1

2017-07-10 14:30 UTC, Cyberboss commented
In the future, please don't rebase as it means I have to review the whole thing again ;-;

2017-07-10 14:31 UTC, merged