Adds in SS13 styled playing cards for dueling each other with
tgstation/tgstation pull request #29186
Opened 2017-07-11 03:55 UTC by ma44

Ported mostly from goonstation, called "griffening"

:cl: ma44
add: New ss13 styled playing cards for dueling each other!
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
1. Something that doesn't require being an antag to get

2. Adds in a feature of collecting cards, making decks and fighting each other

3. Feature rich; contains over a 100 unique cards, cards can be added with ease, will plan to do expansions by adding in other antags or departments later

4. May get holograms (we yugioh now)

TODO checklist

- [ ] Add in a rulebook for ingame usage (already got rules written out somewhere) 

- [ ] Make a card vendor 

- [ ] Differentiate cardhand and single card subtypes into their own things like regular decks do

- [ ] Fix the current bugs (missing sprite, missing interactions) 

- [ ] Add in the generic card sprite from goon and it's foil variant

FUTURE PRs

- Additional cards and mechanics 

- Interactive field with holograms

2017-07-11 03:58 UTC, optimumtact commented on code/game/objects/items/GriffeningPorted.dm
> +                CardCreatures = GLOB.CardCreatures  //Because if it fills up the GLOB, then I need to make sure the first object that calls this is filled, or else it's empty as GLOB didn't have data
why do you have a list on the class and a global list?

2017-07-11 04:04 UTC, Iamgoofball commented
![at least its better than paradox billiards vostroyan roulette fourth dimensional hypercube chess strip poker _6037cd21544a83e4f86d805ecef0b0bf](https://user-images.githubusercontent.com/4081722/28050586-67aeccd4-65b3-11e7-9f05-d72ebc8596ee.jpg)

2017-07-11 04:05 UTC, ma44 commented on code/game/objects/items/GriffeningPorted.dm
> +                CardCreatures = GLOB.CardCreatures  //Because if it fills up the GLOB, then I need to make sure the first object that calls this is filled, or else it's empty as GLOB didn't have data
Commit after this should have fixed this

2017-07-11 04:10 UTC, optimumtact commented on code/game/objects/items/GriffeningPorted.dm
> +        name = "Head Of Personal"
what is up with the indentation for this one?

2017-07-11 04:10 UTC, optimumtact commented on code/game/objects/items/GriffeningPorted.dm
> +        name = "Hull Breach"
odd whitespace

2017-07-11 04:12 UTC, ma44 commented
>spaces instead of tabs

2017-07-11 04:12 UTC, octareenroon91 commented on code/game/objects/items/GriffeningPorted.dm
> +        name = "Head Of Personal"
Also why is this "Personal" instead of "Personnel"?

2017-07-11 05:22 UTC, Grazyn commented
Decks should be persistent and linked with the character, you should always spawn with your deck in your pocket when you join

2017-07-11 05:23 UTC, ma44 commented
For test merging purposes I may leave in a sandbox deck or a way to get certain cards easier. I will also have prebuilt decks available

2017-07-11 05:31 UTC, Grazyn commented
Yeah I just think there's not enough time in a single round to build and play your deck, only to lose all your rares when it restarts. A framework for persistent character items may be useful for other things as well. Something like Gwent in the witcher so you can see and organise your deck and collection from character preferences.

2017-07-11 05:33 UTC, ma44 commented
Another solution is to have a option to copy paste all the typepaths for a deck (import and export builds)
 with a obvious time limit to prevent lagging the server (several minutes at least)

2017-07-11 05:45 UTC, ChangelingRain commented on code/game/objects/items/GriffeningPorted.dm
> +	desc = "Has the ability exchange; if the 'head of personal' is in play and on the owner's side of the field, sacrifice the assistant and immediately summon a non antagonist human that is either leve
you really need someone to standardize these to something like the current yugioh card format because these are mildly unclear at best

2017-07-11 05:46 UTC, ma44 commented on code/game/objects/items/GriffeningPorted.dm
> +	desc = "Has the ability exchange; if the 'head of personal' is in play and on the owner's side of the field, sacrifice the assistant and immediately summon a non antagonist human that is either leve
Definitely working on the descriptions, as some of these are unclear and not consistant

2017-07-11 06:10 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/GriffeningPorted.dm
> +	desc = "Has the ability exchange; if the 'head of personal' is in play and on the owner's side of the field, sacrifice the assistant and immediately summon a non antagonist human that is either leve
take the Magic The Gathering approach

2017-07-11 08:25 UTC, ninjanomnom commented
It doesn't even fucking compile. he cheated travis but just not loading it in the dme.

My pr fixes that but jesus.

2017-07-11 08:34 UTC, optimumtact commented
were we're going we don't need compilers

2017-07-11 10:10 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	desc = "Has the ability exchange; if the 'head of personal' is in play and on the owner's side of the field, sacrifice the assistant and immediately summon a non antagonist human that is either leve
It's called Space: The Collective. Google it.

2017-07-11 10:12 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	var/amountofcards = cards.len
Having a local var named the same as an object var is unacceptable

2017-07-11 10:13 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	cards += A
This could have just been cards += new CardThatGenerated, there was no need to reference the generated card at all

2017-07-11 10:15 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	var/IsBooster = FALSE //Muh booster packs
wtf make boosters a child type. Don't put the logic on the base type, that's stupid as fuck

2017-07-11 10:19 UTC, MrPerson commented
Make the cards datums, not fucking subtypes of the DECK OBJECT. That's incredibly idiotic, try again.

2017-07-11 10:20 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	var/CardThatGenerated //Used for the procs down below
This var is unused, you can remove it

2017-07-11 10:21 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	var/amountofcards //I hate this
This var isn't used at all.

2017-07-11 10:22 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +	cards += A
Actually just make it cards += new pick(GLOB.CardCreatures) and be done with it

2017-07-11 10:23 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +		var/randomnumber = rand(1, 10)
Fix the spacing here

2017-07-11 10:23 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +		if(1 to 3)
And then fix it here

2017-07-11 10:30 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +				to_chat(cardUser, "<span class='notice'>You also take [cards[1]] and hold it.</span>")
cards[1] should be A

2017-07-11 10:30 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +			var/N = new choice(src.loc)
Typecast N please

2017-07-11 10:32 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +			return
Remove this trailing return

2017-07-11 10:33 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +		qdel(I)
This has the effective result of cards += null because you deleted the card! Did you test this at all, holy shit

2017-07-11 10:35 UTC, MrPerson commented on code/game/objects/items/GriffeningPorted.dm
> +/obj/item/griffeningdeck/cardhand
Why are hands a child of decks when they literally don't inherit ANY behavior from the deck?

2017-07-11 10:36 UTC, MrPerson commented
I gave up critiquing your code. It's horrendous.

2017-07-11 10:51 UTC, optimumtact commented
he did copy it from goon

2017-07-11 15:52 UTC, ma44 commented
New subsystem where things are in actually different places. Going to work some more on the bug fixing and also for the missing features.

2017-07-11 17:54 UTC, ModDownloading commented
Though I am not a coder by any means, I can spot a couple of grammatical errors in the "GriffeningPorted" file under the cards section:

- "Head of Personal" should be "Head of Personnel"
- Chief Engineer card description has the word "opponents" which should be "opponent's"
- I don't know why Hull Breach has an attack, defense and level rating if it is not a creature
- In the Stimpack description, it should be "unequipping" not "denquipping"
- The words "raise" and "increase" used for stats are not consistent from card to card (or even on the same card). Similarly, "cyborg" and "robot" are not consistent.
- For consistency with our server, "Medical Director" should be renamed "Chief Medical Officer"
- The word "surplus" in the Surplus Crate card should be capitalized
- Also for consistency with our server, "Vuvuzela" should be renamed "Greytide"
- "Emergency Shuttle" and "Emergency Shuttle Area" seem to have the same effects for some reason

I might have missed something, but there you are.

2017-07-11 18:11 UTC, ma44 commented
Everything has been separated into different files (except for the cards) cards will have datums soon enough. Otherwise ill go get to work on the checklist in the meantime

2017-07-11 18:18 UTC, Grazyn commented
Make a WIP wiki page with a description of the game and basic cards please so we can start theorycrafting

2017-07-11 18:20 UTC, ma44 commented
That will be after the cards get some tags on what they do (for future all rules automated)

2017-07-11 18:34 UTC, ma44 commented
What's squashing

2017-07-11 18:57 UTC, ninjanomnom commented
ban of the day: using github web editor

2017-07-11 19:17 UTC, ma44 commented
It's invincible

2017-07-11 20:59 UTC, Balcore commented
Logged in specifically for this PR. This idea is freaking amazing and I'd play the hell out of it. Definitely would want persistence of decks between rounds so you don't lose the hard work of building a deck every hour.

Lastly the rarity of cards being tied to ruins or objectives sounds like an awesome idea and I'd be happy to use muh basic level spriting skills to sprite some cards if needed.

2017-07-11 22:54 UTC, ExcessiveUseOfCobblestone commented
I PLAY COLOSSUS, FALLEN ANGEL OF LAVALAND

BOW BEFORE ME

2017-07-12 01:29 UTC, Anonmare commented
My grandfather's deck has no pathetic cards Kaiba. Behold! George Malons, The Forbidden One!

2017-07-12 01:40 UTC, ExcessiveUseOfCobblestone commented
Rshoe, Nymph of Evasion

2017-07-12 03:26 UTC, Xhuis commented
point of note: @ma44 isn't an experienced coder and is self-taught, so don't pin terrible code directly on him, but onto his inexperience.

2017-07-12 11:08 UTC, alexkar598 commented
Warden card has the flag : SECURITy which should be SECURITY

2017-07-12 18:55 UTC, Tacolizard commented
@Xhuis well he's also porting gooncode.


hey I'm self taught!

(mabye that's why my PRs always get so many reviews, huh)

2017-07-12 19:06 UTC, Xhuis commented
I'm self-taught too! It just takes practice.

2017-07-12 21:01 UTC, ma44 commented
Again, rhe only thing that was ported were the cards. Literally everything else is either made by me or ninja.

2017-07-13 00:38 UTC, Shadowlight213 commented
Unless you have plans to add more cards or rebalances or something consistently, having persistent decks is going to kill the game extremely quickly.
I'd give it 2 weeks, maybe a month tops before people collect all the cards, and maybe a little longer before an optimum deck composition is discovered and card battles stop being interesting.
I say this, because this happens in real life card games. Companies counter it by releasing new cards and doing stuff like removing older cards from distribution/banning them in competitive play.
A randomized starter deck would help alleviate the issue by forcing people to come up with new strategies and compositions. Also, the card vending machine idea sounds like it would be perfect for a stationwide economy system.

2017-07-13 00:49 UTC, ma44 commented
I was thinking for prepersistance, every assistant starts off with a bunch of random cards, but the curator can copy cards, which could lead to some neat *muh roleplay* for shops and all of that

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone requested changes
Apart from the balance problems I can imagine with this game, please please PLEASE streamline attributes to automatically produce an extra piece to the description.

Also this is not a full review and I don't think I specifically looked at code related issues because there are much better people out there.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "This card may be played in response to Flamethrower, Plasma Fire and Incendiary Grenade. Instantly destroy both cards. When this card is activated, the opponent's turn immediately ends."
Counter fire-type equipment cards and end opponent's turn. Destroy this card.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "This card can only be played if there's a atmospheric tech in play. When this card is played, instantly reduce the DEF of all opponent humans by 10. While this card is active, all opponent h
Continuous Effect. Requires Atmos Tech to play. -10 DEF to all opponent humans.  At the start of opponent's turn, -10 DEF on all opponent human cards (stacks). If they would have no defense, kill creature instead.

Card is discarded if an area card is played.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "This card can only be played if there's a captain in play. If the captain is on your side of the field, summon two security officer immediately on your side of the field either from your han
Requires Captain to play. Play two security officers immediately from your hand,deck, or discard pile. If Captain is controlled by opponent, Play two nuclear operatives from your hand, deck, or discard pile.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "When this card is played, put a 'authentication disk' card into your hand either from both yours and opponent's discard pile or deck."
place an authentication disk card into your hand from either player's deck or discard pile.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "When this card is played, choose a face up equipment card and immediately send it to the gibbed pile and if you do, send this card to the discard pile."
choose target face up equipment card. Target is gibbed. Discard this card.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "Can only be equipped to humans, any human equipped with this is immune to 'hull breach', 'flamethrower', 'plasma fire' or 'incendiary grenade' as well as increase DEF by 10."
+10 DEF. immune to 'hull breach' and fire-type equipment cards.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "Can only be played if you control a 'changeling', if you do, target a enemy creature and send it to the gibbed pile. If you do, send 'changeling' to the discard pile and immediately summon '
Requires changeling in your control to play. Target enemy creature card. Target is gibbed. Discard a changeling card and summon an abomination from your hand,deck, or discard pile.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "When this card is played, place 5 cards from the discard pile of either player to their gibbed pile."
Place 5 cards from any discard pile into the respective gibbed pile.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "When attacking a human using 'Flamethrower', reduce their DEF by 30 before attacking. If target humanoid is 'changeling', immediately destroy the 'changeling;. If the target is 'Abomination'
Attacked creatures receives -30 DEF before attacking. If changeling, destroy it. If abomination, reduce DEF by half instead.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "Can only be equipped if you sacrifice a creature and if you do, you may equip this card to a creature. Raises the ATK by 40 and DEF by 20 of the equipped creature."
Requires creature sacrifice. +40ATK/+20DEF

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "If the equipped creature attacks an enemy that has an equipment card, remove the equipment card or choose one if there's more than one equipped."
While attacking an creature with this equipped, remove an equipment card from target creature.

2017-07-13 03:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "Requires a 'geneticist' to be in play on your field, take any equipment card currently equipped to a enemy creature and put it in your hand."
Requires a geneticist in your control. Remove equipped equipment card from an enemy creature and place in your hand.

2017-07-13 09:39 UTC, MrPerson commented
Need to get a feel for how card text should be written. It's more of an art than a science because you want to be concise but you also have to be perfectly clear. And of course everything needs to be standardized. But that's something that just takes iteration and an eye for detail. I mean jeez look at how all the mtg cards in alpha were written compared to how they read now.

If you want to be super lazy (and efficient), you can just straight copy "Magicese". Or any other ccg, if you prefer. Except Yu-Gi-Oh, which somehow manages to get worse with each expansion about card text.

2017-07-13 13:40 UTC, ma44 commented on code/__DEFINES/cards.dm
> +#define AREA_CARD "AREA_CARD"
Ninja did everything in this subsystem, I touched nothing

2017-07-13 14:35 UTC, ChangelingRain commented on code/modules/griffening_cardgame/carddatums.dm
> +	desc = "This card can only be played if you sacrifice a medical doctor. If this card is in play, increase all DEF of all humans you control by 20. This effect gives 20 more DEF per medical doctor yo
"While alive and not incapacitated, +20 DEF to all humans for each medical doctor under your control."
and make one of its types medical doctor so it counts itself, much clearer

2017-07-13 18:44 UTC, Tacolizard commented
honestly it would probably be better not to port the cards from goon, and just make it standardized from the ground up.

2017-07-14 03:38 UTC, Tacolizard commented
if this PR ends up crashing and burning (which i hope it does tbh) I might try my hand at doing it. except like doing it original and not griffening-based.

2017-07-14 23:49 UTC, ninjanomnom commented
If that does happen I'd be interested still in helping with that like I've helped somewhat with this. I would help more but I'm prety busy recently with things both inside and outside the ss13 community.

2017-07-15 19:19 UTC, ChayseRamsay commented on code/__DEFINES/cards.dm
> +#define ADMEME		0
Mono red player: "I cast smite the monstrous!"
Mono blue player: "I cast negate, then cast negate to counter my negate to trigger this effect which counters your ability and untaps all of my creatures"

2017-07-17 11:54 UTC, RemieRichards commented on code/modules/griffening_cardgame/carddatums.dm
> +	Attributes = list("Human", "Non antag", "Cyborg revival")
attribs should be defines.

2017-07-17 11:56 UTC, RemieRichards commented on code/modules/griffening_cardgame/deck.dm
> +	var/dat = "You have:<BR>"
this should be a list, ```var/list/dat = list("You have:<BR>")```
and then at the end, ```popup.set_content(dat.Join())```

2017-07-17 12:02 UTC, RemieRichards commented
I feel cards should be defined in JSON, or some other data lang.
Card effects would then be part of a standard system, which would make the game easier to play (as it'd be far less likely that two cards would have similar but not-quite-the-same mechanics).

Any special cards can still be defined in DM, where they have effects outside of standard rules/mechanics.

2017-07-19 02:30 UTC, ma44 commented
Nearly done finalizing, ready for review.

Note that the card hand and deck have been reworked into backpacks, as the last way I made it wouldn't work out. It's snowflaky but somehow works.

2017-07-19 04:28 UTC, Armhulen commented
giving every single assistant a deck when they spawn is just dumb

2017-07-19 04:33 UTC, ma44 commented
Obviously a temporally solution for having non persistent decks, an assistant can always throw it away if needed.

2017-07-20 05:45 UTC, Tacolizard commented
>ready for review
>temporary solution

pick one!

2017-07-20 15:38 UTC, octareenroon91 commented
Design starter decks, put one in each personal locker.

Shift to something more basic when persistence comes in.

2017-07-23 15:06 UTC, ma44 commented
This should be ready if i knew how to wiki

2017-07-25 23:45 UTC, optimumtact commented
it would help if it compiled, are you even testing this locally?

That doesn't inspire confidence at all

2017-07-26 14:42 UTC, ma44 commented
Was testing locally, turns out I forgot some stuff, go figure

2017-07-27 02:49 UTC, ma44 commented
Goodtogo.mp4

2017-07-27 07:12 UTC, AnturK commented
Thought this was meant to be automated ? This seems absolutely pointless in the current state. Zero proper interface, alerts() and half the cards referencing goon stuff that doesn't even exists here don't help.

2017-07-27 20:09 UTC, closed without merging

2017-07-27 21:07 UTC, optimumtact commented
I thought this was okay

2017-07-27 21:07 UTC, optimumtact commented
It's like the actual card pack, there are no actual rules enforced, so you can play as many card games as you like with some RP

2017-07-27 22:11 UTC, Iamgoofball commented
reopen this

2017-08-08 05:22 UTC, Tacolizard commented
>Zero proper interface, alerts() and half the cards referencing goon stuff that doesn't even exists here do not help.

not to mention the fact that the code is absolutely horrid.

keep this closed, i might come around to a rewrite

2017-08-08 06:02 UTC, optimumtact commented
you're not any better