Cleaned up some emag_acts
tgstation/tgstation pull request #29238
Opened 2017-07-13 09:44 UTC by ShizCalev

2017-07-13 13:26 UTC, lzimann commented on code/game/machinery/computer/communications.dm
> +					if(!src.emagged)
remove `src`

2017-07-13 13:28 UTC, lzimann commented on code/game/mecha/mech_fabricator.dm
> -	if(emagged)
I honestly prefer this  the old way. Just make the `emagged = FALSE` be a `TRUE` and remove the last line.

2017-07-13 13:36 UTC, Cyberboss requested changes

2017-07-13 13:36 UTC, Cyberboss commented on code/game/machinery/buttons.dm
> +		playsound(src.loc, "sparks", 100, 1)
playsound(src,...

2017-07-13 13:36 UTC, Cyberboss commented on code/game/machinery/computer/apc_control.dm
> +		playsound(src.loc, "sparks", 50, 1)
playsound(src,...

2017-07-13 13:36 UTC, Cyberboss commented on code/game/machinery/limbgrower.dm
> +		to_chat(user, "A warning flashes onto the screen, stating that safety overrides have been deactivated")
Give this a warning span

2017-07-13 13:36 UTC, Cyberboss commented on code/game/machinery/recycler.dm
> +	else if(emagged == TRUE)
this one needs to be reverted

2017-07-13 13:36 UTC, Cyberboss commented on code/game/mecha/mech_fabricator.dm
> +		emagged = TRUE
put these two lines at the top and use timers for the sleeps

2017-07-13 13:36 UTC, Cyberboss commented on code/modules/atmospherics/machinery/airalarm.dm
> +		visible_message("<span class='warning'>Sparks fly out of the [src]!</span>", "<span class='notice'>You emag the [src], disabling its safeties.</span>")
Remove the `the`s in front of the `src`s

2017-07-13 21:32 UTC, ShizCalev commented on code/game/mecha/mech_fabricator.dm
> -	if(emagged)
Done

2017-07-14 15:42 UTC, Cyberboss requested changes

2017-07-14 15:42 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +		emagged = 1
TRUE

2017-07-14 15:42 UTC, Cyberboss commented on code/game/mecha/mech_fabricator.dm
> -	if(emagged)
he wants it like
```
if(emagged)
    return
etc...
```
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-early-return

2017-07-15 15:27 UTC, merged