ClickCross now uses CanPass instead of density directly.
tgstation/tgstation pull request #29241
Opened 2017-07-13 18:40 UTC by AnturK

Fixes #28722
Closes #28837 - This is just more generic alternative.

This might cause non-obvious issues. Extended testmerge recommended.

2017-07-14 16:57 UTC, Cyberboss commented
Testmerged on sybil, should be fine in 24h

2017-07-14 17:10 UTC, Cyberboss requested changes

2017-07-14 17:10 UTC, Cyberboss commented on code/_onclick/adjacent.dm
> +		if(mover && O.CanPass(mover,get_step(src,target_dir)) || !mover && !O.density)
Can you add more brackets here to make precedence clear?

2017-07-14 17:26 UTC, AnturK commented on code/_onclick/adjacent.dm
> +		if(mover && O.CanPass(mover,get_step(src,target_dir)) || !mover && !O.density)
Sure

2017-07-15 15:23 UTC, Cyberboss approved these changes

2017-07-15 15:30 UTC, merged