[Cere] Removes all access from cell doors in brig
tgstation/tgstation pull request #29273
Opened 2017-07-15 00:49 UTC by Penguaro

:cl: Penguaro
fix: Adjusts access on right side cell doors to restrict access.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Nanotrasen Technical Support has resolved the security issue with that affected some of the cell doors on Cere Station. They are now all locked as per security standard. Fixes #29272

2017-07-15 00:51 UTC, Cyberboss approved these changes

2017-07-15 15:35 UTC, ShizCalev commented
Cell doors use req_access 2

2017-07-15 15:37 UTC, Cyberboss requested changes
2 not 1

2017-07-15 22:00 UTC, Penguaro commented
Sure I can make that change. That's not consistent across all stations. My best guess is that regular cells are 1 so heads can brig people.

2017-07-15 22:06 UTC, ShizCalev commented
I'll fix it on box after. It's 2 on the rest.

2017-07-15 22:23 UTC, Penguaro commented
@Cyberboss I made the changes you requested.

2017-07-16 02:54 UTC, Penguaro commented
Shiz went in a different direction that is cleaner.

2017-07-16 02:54 UTC, closed without merging

2017-07-17 11:43 UTC, Anajamois commented
It's still a shitty, bad map, but at least that's one thing fixed. Thanks.