Ports instruments from /VG/station, including harmonicas, xylophones, saxophones, trombones, and a BIKE HORN. Repaths instruments to sound/instruments. Also, allows piano synth to play all instruments but eguitar and gives cargo a crate with everything. Clown gets the bike horn trumpet at roundstart.
tgstation/tgstation pull request #29277
Opened 2017-07-15 04:17 UTC by kevinz000

Title.

2017-07-15 04:23 UTC, Armhulen commented
751 file changes for 5 new instruments :thinking:

2017-07-15 04:23 UTC, Armhulen commented
oh i just checked code uuuuuuuh

2017-07-15 05:17 UTC, GunHog commented
Kev, I am really worried right now...Kev...you made quite the mess here...Kev, stop using the online editor!

2017-07-15 06:17 UTC, meeeeme commented
Synthesizer for pAI 2017!

2017-07-15 06:44 UTC, DoctoreMad commented
>/VG/

Do you want to know why I'm laughing right now?

2017-07-15 15:13 UTC, Cyberboss requested changes

2017-07-15 15:13 UTC, Cyberboss commented on code/game/objects/items/devices/instruments.dm
>  	..()
Initialize and . = ..()

2017-07-15 15:13 UTC, Cyberboss commented on code/datums/action.dm
> +		synth.changeInstrument(input("Choose the type of instrument you want to use", "Instrument Selection", "piano") as null|anything in synth.insTypes)
do sanity checks after the input

2017-07-15 15:29 UTC, nicbn commented
The increase in the game size doesn't compensate for the minimal advantages of having one septillion instruments.

2017-07-15 15:31 UTC, Cyberboss commented
> 1MB

It's 2017, grow up

2017-07-15 18:01 UTC, Cyberboss requested changes

2017-07-15 18:01 UTC, Cyberboss commented on code/game/objects/items/devices/instruments.dm
> +	. = ..()
. = ..() first

2017-07-15 22:08 UTC, octareenroon91 commented
>a file for every MIDI note-instrument combination

holy fuck

2017-07-15 22:15 UTC, Tacolizard commented
WTF 1 MEGABYTE ON TOP OF MUH 1.1GB GAME?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!?!?!?!?!?!!?!?!?!?!?!?!!?!?!?!?!?!?!?!?!?!?!?!?!?!??!?!?!?!?!?!?!?!??!?!?!!?!?!?!?!?!?!?!?!?!??!?!?!?!!?!?!!!?!?!?!?!?!?!?!??!!?!?!?!?!?!

2017-07-15 23:53 UTC, kevinz000 commented
@Tacolizard 58 mb or something is how much players download iirc

2017-07-16 03:14 UTC, PKPenguin321 commented
Why can't synth play eguitar

2017-07-16 04:33 UTC, octareenroon91 commented
>Why can't synth play eguitar

That's an intentional choice. Maybe something about ear-rape.

2017-07-16 13:06 UTC, optimumtact commented
It's easy for you americans to not complain about the filesize, but it can take almost 5-6 minutes to download the tgstation resources if the CDN fails and or byond decides to invalidate the game cache.

2017-07-16 14:07 UTC, CPTANT commented
750 extra files and 1MB of extra gamesize for 5 instruments?

No thank you.

2017-07-16 15:29 UTC, kevinz000 commented
@PKPenguin321 i don't want to add more eguitar instruments, they're earrapey as fuck, loud, and obnoxious. if they want them there's one on the station roundstart on most maps I believe.

2017-07-16 15:31 UTC, kevinz000 commented
@CPTANT 
1. The only thing you should be worried about is gamesize. Number of files isn't really a concern as I don't believe byond actually makes 750 files on your computer, but if I'm wrong it still isn't that bad.
2. Many of the 750 files is from me moving all current instruments to another folder.

2017-07-16 15:35 UTC, kevinz000 commented
Did I say 1 MB bigger? My mistake.
Old
![old](https://puu.sh/wL2BW/89a638426c.png)
New
![new](https://puu.sh/wL2yO/132aef2061.png)

2017-07-16 15:42 UTC, kevinz000 commented
@PKPenguin321 il add eguitar to it in a later pr that also lowers the eguitar sounds, as well as eguitars to the crate because jesus christ they're too loud..

2017-07-16 16:05 UTC, PraiseRatvar commented
why are people so pissy over like 3 megabytes

2017-07-16 16:48 UTC, Cyberboss approved these changes

2017-07-16 16:48 UTC, Cyberboss commented
>actually decreases file size

Shows all it takes to start a shitstorm around here

2017-07-16 16:48 UTC, merged

2017-07-16 17:13 UTC, nicbn commented
> WTF 1 MEGABYTE ON TOP OF MUH 1.1GB GAME?!?!?
Not about me, it's about the players who already download around 50 MB to play.
> It's 2017, grow up
I live in Brazil. A third world country. My internet is one of the few good there are, but until december of the last year I had a 2 Mbps internet. Actually internet providers lie, so it was 1 Mbps, sometimes 0.5 Mbps.
Arount 7 minutes to play tg. That was one of the reasons I played tg instead of para. Para was 15 minutes to download. 15 fucking minutes. That's why I ask you: Don't take a step in this direction. Now it already has been taken, but please, when adding more assets, think about people who need to wait to play because they live in third world countries, and, in case of Brazil, countries where things normally don't work for them.

2017-07-16 17:14 UTC, Cyberboss commented
It's a half a megabyte DECREASE you memes

2017-07-16 17:21 UTC, nicbn commented
It's not anymore because of the file size, it's because you was rude about me complaining it. Come on, not everybody likes to have little more features - that they will probably never use - in tradeoff of more content to download.
If you showed the file decrease instead of saying me to "grow up" I'd be totally fine, but come on, not everybody lives in USA/Europe.

2017-07-16 17:33 UTC, Cyberboss commented
Funny how we get these complaints now after rsc size has dropped ~7MB in the past month, but w/e

2017-07-16 22:10 UTC, optimumtact commented
@kevinz000 wrong again, considering that often another file requires a new tcp request from the client, which entails the full tcp overhead of setting up a connection.

Especially a big issue on the webclient

2017-07-16 22:10 UTC, optimumtact commented
Err that was about file count

2017-08-02 07:20 UTC, Fox-McCloud commented
@kevinz000 

We actually made a PR on Para to lower their volume: https://github.com/ParadiseSS13/Paradise/pull/7768

they're very reasonable and in-line with the guitar, piano, and violin.

Also, you didn't delete the old instrument folders....andddd you used the shitty midi violin as opposed to the .ogg version.

Also, you added xylophone midis and sprites, but didn't include it as an instrument??