Adds more CAS cards. Removes a couple shit ones.
tgstation/tgstation pull request #29302
Opened 2017-07-16 10:37 UTC by bgobandit

:cl: bandit
add: New Cards against Spess cards are available!
/:cl:

hopefully this will not be proven wrong
also a bug or two with this I want to track down, haven't done it yet

2017-07-16 15:09 UTC, DoctoreMad commented
.>He doesn't like lewd alien abduction

2017-07-16 16:55 UTC, Cyberboss commented on strings/cas_white.txt
> +Cortical borers.
Not sure if good or bad meme

2017-07-16 16:56 UTC, Cyberboss requested changes

2017-07-16 16:56 UTC, Cyberboss commented on strings/cas_black.txt
> +What made me I sell my soul to the devil?
> me I

2017-07-16 19:00 UTC, nicbn commented
Why don't use the original meme and write "recent _____ on Hippie Station" instead of "recent _____ on this station"? I don't think Hippie will mind if we use it.

2017-07-16 21:00 UTC, bgobandit commented
because a) this isn't hippie station b) the round end sound doesn't say hippie station

2017-07-17 00:16 UTC, nicbn commented
Ok, so let there be the hippie world on the round end sound. I'm not sure if you know but the meme is this: [https://vimeo.com/201564125](https://vimeo.com/201564125).

2017-07-17 01:11 UTC, bgobandit commented
this isn't hippie though

2017-07-17 02:22 UTC, BeeSting12 commented on strings/cas_white.txt
> +Cortical borers.
No nazi references right?

2017-07-17 02:46 UTC, Cyberboss commented
The hippie station bit of the sound is specifically edited out

On Jul 16, 2017 10:22 PM, "BeeSting12" <notifications@github.com> wrote:

> *@BeeSting12* commented on this pull request.
> ------------------------------
>
> In strings/cas_white.txt
> <https://github.com/tgstation/tgstation/pull/29302#discussion_r127625462>:
>
> > \ No newline at end of file
> +Homicidal chefs.
> +Extended.
> +Grammar Nazi gods.
> +Cortical borers.
>
> No nazi references right?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/29302#discussion_r127625462>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHyweliSQ6Kx6qJoVdxazRSWo1wGAD_Eks5sOsVpgaJpZM4OZQod>
> .
>

2017-07-17 04:14 UTC, lordpidey commented
On the black cards, line 5, switch singularity to supermatter, since we don't use sings anymore.
I have an idea for a card.
Black:
Don't worry, we've replaced the supermatter with _______________.

2017-07-17 04:22 UTC, outbools commented
@DoctoreMad 
\>don't know how to use markdown

2017-07-17 08:41 UTC, Iamgoofball commented on strings/cas_white.txt
> +Cortical borers.
the word should not appear in the codebase

@Cheridan

2017-07-17 08:43 UTC, RemieRichards commented on strings/cas_white.txt
> +Cortical borers.
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#banned-content

2017-07-17 08:43 UTC, RemieRichards requested changes
Contains banned content.

2017-07-17 11:24 UTC, KorPhaeron commented on strings/cas_white.txt
> +Adding poo.
Can we not encourage the least funny forun poster

2017-07-18 06:57 UTC, optimumtact commented on strings/cas_white.txt
> +Cortical borers.
I think we can safely ignore the rule in this case

2017-07-19 05:00 UTC, Iamgoofball commented on strings/cas_white.txt
> +Cortical borers.
unacceptable

2017-07-19 18:45 UTC, ExcessiveUseOfCobblestone commented on strings/cas_white.txt
> +Adding poo.
It's ok he doesn't play

2017-07-20 05:54 UTC, Cyberboss requested changes

2017-07-20 05:54 UTC, Cyberboss commented on strings/cas_white.txt
> +Cortical borers.
Remove the nazi line

2017-07-20 21:23 UTC, optimumtact commented on strings/cas_white.txt
> +Cortical borers.
guys the rule was added because some guy kept making a ruin full of space nazi's, this is totally acceptable @Cheridan will not mind either way

2017-07-25 02:14 UTC, merged