Fixes shower runtimes
tgstation/tgstation pull request #29389
Opened 2017-07-20 01:35 UTC by kevinz000

2017-07-20 05:40 UTC, Cyberboss requested changes
wash_obj should only be being called on atom/movable, find out where the bad calls are coming from and fix them

2017-07-20 06:34 UTC, kevinz000 commented
fixed, it's coming from it trying to wash the null entries in mob's heldi ndexes.

2017-07-20 14:01 UTC, lzimann commented on code/game/objects/structures/watercloset.dm
>  		for(var/obj/item/I in M.held_items)
won't a typed loop call `istype` and prevent nulls?

2017-07-20 15:44 UTC, Cyberboss commented on code/game/objects/structures/watercloset.dm
>  		for(var/obj/item/I in M.held_items)
Yes, this is an ineffectual change

2017-07-20 18:56 UTC, kevinz000 commented
Hmm

2017-07-21 21:53 UTC, kevinz000 commented
fixed.

2017-07-22 18:48 UTC, merged