Multiple inhand sprites fix
tgstation/tgstation pull request #29456
Opened 2017-07-23 12:21 UTC by kingofkosmos

Fixes One-point bluespace-gravitational manipulator's inhand. Also adds placeholder-inhands for all the severed limbs - a gray block, same as a pipe, but it's better than nothing. If someone wants to make better inhands for the limbs, I'll add them here.

Still waiting for the inhand sprites for:
* Chem Sprayer
* DRAGnet

Will add once someone makes them (already requested on the forums).

:cl:
add: Inhands for One-point bluespace-gravitational manipulator and severed limbs.
/:cl:

Fixes #29096

2017-07-23 12:22 UTC, RemieRichards commented on code/modules/surgery/bodyparts/bodyparts.dm
> +	item_state = "buildpipe"
No.
Flesh limbs should not show up as pipes, that's dumb.

2017-07-23 12:55 UTC, DoctoreMad commented
>Also adds placeholder-inhands for all the severed limbs - a gray block, same as a pipe

Well that's not really necessary. If we get proper limb sprites we can use them, if we don't have them, its not like its some sort of lethal item or anything so why do you need to change it?

2017-07-23 15:25 UTC, kingofkosmos commented
>Well that's not really necessary. If we get proper limb sprites we can use them, if we don't have them, its not like its some sort of lethal item or anything so why do you need to change it?

I thought that anything in hand would add to the "feel" of the game. If people disagree I can remove it from the PR and wait for proper inhands if there will be any.

2017-07-26 00:00 UTC, optimumtact commented
it's really quite remarkable that dismembered limbs got in without an inhand

2017-07-26 07:47 UTC, RemieRichards commented
Not really, at the time we had poor support for colour inhands (read: none), no support for overlays on inhands, etc.

Not to mention they don't DO anything, they're not weapons and don't specifically -need- an inhand, certainly not enough to justify a grey pipe.

2017-07-27 11:06 UTC, AnturK commented
Yeah, just skip the inhands for now , we'll just wait bit longer.

2017-07-27 13:30 UTC, Cyberboss requested changes
Do the thing remie wants

2017-07-28 08:21 UTC, FuryMcFlurry commented
I've contributed dragnet and chemsprayer inhands. Awaiting change.

2017-07-28 12:45 UTC, Tacolizard commented
pics or GTFO

2017-07-28 13:36 UTC, Cyberboss commented
@kingofkosmos

2017-07-28 16:14 UTC, FuryMcFlurry commented
@Tacolizard 
![image](https://user-images.githubusercontent.com/8770071/28726194-90e01480-73c0-11e7-847f-934590091b2a.png)

guess which one is which

2017-07-30 16:33 UTC, kingofkosmos commented
Original post edited. Added Fury's DRAGnet and Chem Sprayer inhands.

Removed severed limbs stuff. Unless someone wants to make them, I'll add them to this PR. Btw should there be an inhand for every limb? Or just for heads and a some sort of blob-lookalike for all the other limbs + chest?

2017-07-31 00:29 UTC, Cyberboss approved these changes

2017-07-31 00:57 UTC, merged