[dnm]Update banned content to include open source bad actors
tgstation/tgstation pull request #29483
Opened 2017-07-24 19:24 UTC by MrStonedOne

# This is a meme pr, do not merge.

**Kite** goes and hires creators of popular open source software and then convinces those employees to inject promotional shit into that open source software.

https://theoutline.com/post/1953/how-a-vc-funded-company-is-undermining-the-open-source-community

2017-07-24 20:26 UTC, Supermichael777 commented on .github/CONTRIBUTING.md
> +* Code, Pull Requests, or Issue Reports submitted by Kite, Kite.com, or their employees or affiliates
whom are acting as agents of Kite or Kite.com or otherwise advancing the interests of Kite or Kite.com.

2017-07-24 20:28 UTC, Supermichael777 commented
Re-host as truly open license software MSO.

bring your biased heroism to the whole intewebz

2017-07-24 21:00 UTC, pubby commented
MSO is higher than Kite

2017-07-24 21:02 UTC, MrStonedOne commented on .github/CONTRIBUTING.md
> +* Code, Pull Requests, or Issue Reports submitted by Kite, Kite.com, or their employees or affiliates
No, the point is to make it clear that kite employees are not welcomed here, regardless of intent.

It also greenlights mass removing any code by anybody who later becomes an employee of kite, to reduce their stake in this repo.

2017-07-24 21:17 UTC, DoctoreMad commented on .github/CONTRIBUTING.md
> +* Code, Pull Requests, or Issue Reports submitted by Kite, Kite.com, or their employees or affiliates
>It also greenlights mass removing any code by anybody who later becomes an employee of kite, to reduce their stake in this repo.

Okay so if a coder gets a silly spite towards your codebase he can announce he joined kite and watch as you start eating parts of the codebase in a f~~it of rage~~ crusade of righteousness?

2017-07-24 21:28 UTC, DoctoreMad commented
So what is the point of this again? Are you placing bait for "Kite employees" or something?

2017-07-24 21:44 UTC, MrStonedOne commented
It's a meme pr.

Its here to meme.

Whats not to understand?

2017-07-24 22:27 UTC, MrStonedOne commented on .github/CONTRIBUTING.md
> +* Code, Pull Requests, or Issue Reports submitted by Kite, Kite.com, or their employees or affiliates
I think you missed the part where this is a meme pr that will never get merged.

2017-07-24 22:36 UTC, JJRcop commented
[Congrats on the last word.](https://github.com/atom-minimap/minimap/issues/588#issuecomment-317547010)

2017-07-25 02:43 UTC, octareenroon91 commented
Is this PR going to close at some point?

What kind of meme is this

2017-07-25 03:36 UTC, Buggy123 commented
As a employee of Kite™, I see no reason to add this PR. Instead, might I suggest signing up for our Kiteport™ package, one of the many Kitervices™ we offer here at Kite™? With Kiteport™, our Kitevelopers™ will encrypt your codebase, ensuring only KiteQuality™ PRs are created, improving your software quality by Kitefold™! V™i™s™i™t™ K™i™t™e™.™c™o™m™ f™o™r™ d™e™t™a™i™l™s™.™™

2017-07-25 04:25 UTC, lordpidey requested changes

2017-07-25 04:25 UTC, lordpidey commented on .github/CONTRIBUTING.md
> +
Undocumented change in PR body, you made no mention of changing the spacing between points in documentation

2017-07-27 11:02 UTC, closed without merging