Lava dwarfs 3: The testmerge era
tgstation/tgstation pull request #29481
Opened 2017-07-24 17:06 UTC by ma44

cool wiki for people that don't know what dorfs are
https://tgstation13.org/wiki/Lava_Dwarf
Hopefully feature freeze doesn't rekt this pr

## **Test merges only**

:cl: dwarfs or something
add: dorfs lavaland ruin, play as a dorf migrant
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
Because dorfs was always fun, but it can still run even without GOAP additions, so I'm leaving it here so the playerbase can enjoy being dorfs if this gets testmerged for some reason

2017-07-24 17:06 UTC, ma44 commented
Oh neat conflicts

2017-07-24 17:20 UTC, RandomMarine commented
Please.
Oh god please.
Disregard feature creep and just get this in a working, merge-able state.

2017-07-24 17:34 UTC, DoctoreMad commented
Goof's PR has less conflicts than this one.

2017-07-24 17:35 UTC, ma44 commented
I'm not even going to understand how that works

2017-07-24 17:36 UTC, DoctoreMad commented on code/game/turfs/simulated/minerals.dm
> +			GLOB.secret_triggered = FALSE //How to be unlucky
Are you telling me there's a chance that two HFSs appear in the same round?

2017-07-24 17:37 UTC, ma44 commented on code/game/turfs/simulated/minerals.dm
> +			GLOB.secret_triggered = FALSE //How to be unlucky
a *chance*

2017-07-24 17:38 UTC, DoctoreMad commented
RIP Lava Dwarves

2017-07-24 17:41 UTC, FantasticFwoosh commented
Wait. Fuck. Already? Nice to see it back.

- GOAP if i remember correctly could mean we can have a dwarf fortress on lavaland that is 100% autonomous run by bots.

2017-07-24 17:52 UTC, ma44 commented
huh, turns out that i did the wrong version, hold on kids

2017-07-24 17:54 UTC, ma44 commented on code/game/turfs/simulated/minerals.dm
> +			GLOB.secret_triggered = FALSE //How to be unlucky
this is also outdated and not included, go figure

2017-07-24 17:58 UTC, Armhulen commented
IT'S DEAD

2017-07-24 17:58 UTC, ma44 commented
Can't be ded if there's a ma44 on it or something

2017-07-24 17:59 UTC, ma44 commented
>realizing you can't edit the files because you made the pr of goofs branch which you don't have control over but since you use web editor you can't make a fork of that branch or something and stuff

2017-07-24 18:07 UTC, ma44 commented on code/modules/reagents/reagent_containers/glass.dm
> +	volume = 75 //Code adds 75u of reagents while the original bucket had 70u max, making it loose	flags = OPENCONTAINER
cool reminder for me to FIX THISSSSSSSSSSSSS

2017-07-24 18:54 UTC, DoctoreMad commented
>GOAP if i remember correctly could mean we can have a dwarf fortress on lavaland that is 100% autonomous run by bots.

Yeah but why? For what purpose? I thought this was supposed to be for players.

2017-07-24 18:55 UTC, ma44 commented
For autistic forts and to make you be frustrated so you can go and scream at the computer about why your 2d spessmen lure a colossus into the base

2017-07-24 22:41 UTC, ma44 commented
# cant wake up

2017-07-24 23:34 UTC, AnonymousNow commented
This sounds fun.

2017-07-24 23:48 UTC, tortellinitony requested changes

2017-07-24 23:48 UTC, tortellinitony commented on code/_onclick/hud/hud.dm
> +	var/obj/screen/alcohol_amount
Unused var

2017-07-24 23:48 UTC, tortellinitony commented on code/_onclick/hud/hud.dm
> +	alcohol_amount = null
Unused var

2017-07-24 23:48 UTC, tortellinitony commented on code/modules/mining/smelter.dm
> +				M.loc = src
`M.forceMove(src)`

2017-07-24 23:48 UTC, tortellinitony commented on code/modules/mob/living/carbon/human/interactive.dm
> +	var/allow_random = 1
Use TRUE

2017-07-24 23:48 UTC, tortellinitony commented on code/modules/reagents/chemistry/recipes/others.dm
> +	mob_react = 1
Use TRUE

2017-07-24 23:48 UTC, tortellinitony commented on code/modules/mob/living/carbon/human/species_types/dwarf.dm
> +		dwarf = new()
Remove `()`

2017-07-24 23:48 UTC, tortellinitony commented on code/modules/surgery/organs/dwarf_organ.dm
> +	slot = "dwarf_organ"
Make an organ define DWARF_ORGAN

2017-07-25 00:33 UTC, ma44 commented
waitin years for pr to be merged at goofs branch

2017-07-25 07:28 UTC, Grazyn commented
>GOAP if i remember correctly could mean we can have a dwarf fortress on lavaland that is 100% autonomous run by bots.

Would it be possible to give a ghost the ability to place structures and give simple orders to the dwarf bots? You know, so we could play ACTUAL dwarf fortress.

2017-07-25 08:31 UTC, LarissaMayrink commented
>Would it be possible to give a ghost the ability to place structures and give simple orders to the dwarf bots? You know, so we could play ACTUAL dwarf fortress.
lava carps when

2017-07-25 08:56 UTC, FantasticFwoosh commented
Whoever controls the sceptre controls the dwarves @Grazyn i guess, also @DoctoreMad its a fun simulation thing like swarmers on lavaland (granted that's not as much fun) and you could roll back the ghost roles to being dwarven nobles in charge of dwarf-bots as peasantry.

2017-07-25 14:13 UTC, Jalleo commented
Well there are a few merge conflicts.

2017-07-25 16:05 UTC, ma44 commented
# Rip
https://github.com/Iamgoofball/-tg-station/pull/13#issuecomment-317619212

2017-07-26 19:25 UTC, kevinz000 commented
it's another ma44 episode
Change the channel.

2017-07-26 19:27 UTC, Tacolizard commented
>web editor

2017-07-27 20:09 UTC, closed without merging