Transformation procs now properly grant/remove languages.
tgstation/tgstation pull request #29737
Opened 2017-08-05 23:07 UTC by bgobandit

Fixes https://github.com/tgstation/tgstation/issues/29576.

To be clear these are the monkeyize, humanize, etc procs (the same ones in the admin panel). There are two things I do not know what to do about:

- SMALLER THING: I don't know what to do about AI-ize
- LARGER THING: From a design standpoint do we want people to lose/gain galcom and gain the new language every time this happens? If not, what refactor would be better?

2017-08-05 23:40 UTC, optimumtact commented
Is there a binary language or is it still a snowflake comms channel? It's probably fine to just give them galcomm

2017-08-06 00:12 UTC, bgobandit commented
I mean in code terms, AI mob and mind structure is... special and as you can see the code for it is different (grant_language doesn't run off mind but mob)

2017-08-06 00:39 UTC, YakumoChen commented
its both optimum

2017-08-06 22:41 UTC, Cyberboss requested changes
Add galcomm and machinespeak to AIs

2017-08-07 00:12 UTC, optimumtact commented
sorry I'm not sure I understand the issue? are there missing helper procs for the AI mob path or something?

2017-08-07 01:49 UTC, bgobandit commented
The AI-ize puts the mob into an AI core, because that's what AIs do. This fucks up references to mob. The procs for giving languages are designed to be used on mobs, not minds.

2017-08-08 13:24 UTC, Cyberboss commented
@bgobandit

2017-08-08 13:25 UTC, Cyberboss commented
Just call `grant_language()` on the . parameter of AIize

2017-08-09 08:20 UTC, AnturK requested changes

2017-08-09 08:20 UTC, AnturK commented on code/modules/mob/transform_procs.dm
> +	O.remove_all_languages()
Won't this drop faction languages like cultspeak ?

2017-08-10 01:48 UTC, bgobandit commented on code/modules/mob/transform_procs.dm
> +	O.remove_all_languages()
possibly I need to figure out how to handle it

2017-08-11 19:53 UTC, KorPhaeron commented
Stale

2017-08-11 19:53 UTC, closed without merging