Removes a great amount of machinery copypasta with circuitboards.
tgstation/tgstation pull request #29747
Opened 2017-08-06 17:23 UTC by lzimann

Now, instead of creating a new circuitboard and applying default parts in every machinery `Initialize()`, you put the path in the `circuit` variable, removing a good amount of unecessary proc overhead.

Also changes New -> Initialize in most of them.
renamed: `code/game/machinery/computer/computer.dm` -> `code/game/machinery/computer/_computer.dm`
renamed: `code/game/machinery/machinery.dm` -> `code/game/machinery/_machinery.dm`
Moved all circuitboards(except mech circuits for now) to a new folder at `code/game/objects/items/weapons/circuitboards`

It shouldn't have any problems, but might be a good idea to throw a testmerge for a more extensive testing.

2017-08-06 18:10 UTC, FantasticFwoosh commented
![](https://pics.onsizzle.com/all-spaghetti-no-regretti-pasta-la-vista-26477273.png)
____________________________________________________
Looks good.

2017-08-06 22:40 UTC, Cyberboss commented
Code Improvement and Refactor are mutually exclusive IMO

2017-08-06 22:42 UTC, lzimann commented
not always, but w/e

2017-08-06 23:09 UTC, Jordie0608 commented
Is a refactor not an improvement of the code?

2017-08-06 23:28 UTC, Cyberboss commented
Code Improvement was added because things that weren't refactors were getting the Refactor tag IIRC

2017-08-06 23:37 UTC, optimumtact commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
doesn't this return null? you changed the semantics of how it behaves

2017-08-06 23:54 UTC, lzimann commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
I believe `CRASH` returns `.`, but I might be wrong.

2017-08-06 23:55 UTC, Cyberboss commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
You are correct

2017-08-07 00:15 UTC, optimumtact commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
yeah but it was explicitly returning 0 before, not .
It's almost certainly fine, but you should probably check if it matters.

2017-08-07 00:55 UTC, lzimann commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
Actually this can just become a stack_trace and return a init_qdel_hint instead.

2017-08-07 07:52 UTC, RemieRichards commented
@Cyberboss not really but sort of.
I added it because there were cases where things were improvements, but the refactor tag just didn't make sense, meaning the pr would often go tagless which is sad and bad for quickly glancing at what something does.

2017-08-07 14:03 UTC, Cyberboss commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
can and should

2017-08-07 16:54 UTC, Cyberboss requested changes

2017-08-07 16:54 UTC, Cyberboss commented on code/game/gamemodes/nuclear/nuclearbomb.dm
>  		qdel(src)
Have it return INITIALIZE_HINT_QDEL instead

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/announcement_system.dm
> -	radio = new /obj/item/device/radio/headset/ai(src)
Where'd this go?

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/autolathe.dm
> +	return ..()
Why is this at the bottom now?

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/_computer.dm
> +/obj/machinery/computer
Line endings

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/apc_control.dm
> +	return ..()
. = ..() first if possible please, it's meant to run like a constructor

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/dna_console.dm
> +	return INITIALIZE_HINT_LATELOAD
This doesn't need late initialization, it's just looking for the presence of the machine so regular Initialize is fine

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	..()
Move this into Initialize

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	light_color = LIGHT_COLOR_BLUE
parent vars first

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	var/id = null
`= null`s

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	for(dir in list(NORTH,EAST,SOUTH,WEST))
GLOB.cardinals

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	src.attack_hand(user)
src

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	return
trailing return

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +		locked.loc = loc
forceMove

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/computer/teleporter.dm
> +	return 1
TRUE and FALSE returns

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/gulag_teleporter.dm
> +	locate_reclaimer()
Doesn't need late Initialize

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/magnet.dm
> +	SSradio.add_object(src, freq, GLOB.RADIO_MAGNETS)
This line doesn't need late Initializing

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/magnet.dm
> +	radio_connection = SSradio.add_object(src, frequency, GLOB.RADIO_MAGNETS)
Doesn't need late Initializing

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +/obj/machinery/turretid/Initialize(loc, ndir = 0, built = 0)
mapload

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/recycler.dm
> +	return ..()
. = ..() first

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/shieldgen.dm
> +	. = ..()
I believe this should be:

```
. = ..()
setDir(pick(GLOB.cardinals))
```

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/teleporter.dm
> +	var/engaged = 0
FALSE?

2017-08-07 16:54 UTC, Cyberboss commented on code/game/machinery/vending.dm
> +	if(!refill_canister) //constructable vending machine
You need to null out circuit before ..() if refill_canister is TRUE

2017-08-07 16:54 UTC, Cyberboss commented on code/game/mecha/mech_fabricator.dm
> +	return ..()
. = ..() first

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/gibber.dm
> +			M.loc = src
forceMove

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
> +		"singulo" = 5)
Ehh, I preferred this in the proc but w/e

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/processor.dm
> +	var/broken = 0
FALSE?

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/mining/laborcamp/laborstacker.dm
> +	locate_stacking_machine()
No need for lateload

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/mining/machine_input_output_plates.dm
>  /obj/machinery/mineral/input/New()
Init

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/mining/machine_input_output_plates.dm
>  /obj/machinery/mineral/output/New()
Init

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/power/singularity/emitter.dm
> +	var/atom/target = null
`= null`

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/power/singularity/emitter.dm
> +	if(state == 2 && anchored)
This magic number hurts me

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/power/singularity/emitter.dm
> +	sparks.set_up(5, TRUE, src)
do_sparks?

2017-08-07 16:54 UTC, Cyberboss commented on code/modules/power/smes.dm
> +	return INITIALIZE_HINT_LATELOAD
No need for late init

2017-08-07 17:33 UTC, lzimann commented on code/game/machinery/announcement_system.dm
> -	radio = new /obj/item/device/radio/headset/ai(src)
Accidental removal

2017-08-07 17:34 UTC, lzimann commented on code/game/machinery/autolathe.dm
> +	return ..()
`..()` calls refreshparts, which runtimes since `materials` will be null.

2017-08-07 17:37 UTC, lzimann commented on code/game/machinery/computer/arcade.dm
>  		qdel(src)
Gotta return qdel hint here

2017-08-09 03:44 UTC, Cyberboss commented on code/game/gamemodes/nuclear/nuclearbomb.dm
> +		CRASH("Attempted to spawn a syndicate nuke while one already exists at [existing.loc.x],[existing.loc.y],[existing.loc.z]")
So the technically correct code would be . = INITIALIZE_HINT_QDEL then the CRASH

2017-08-09 10:27 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	sparks.set_up(5, TRUE, src)
The spark system is reused later on

2017-08-09 13:42 UTC, lzimann commented on code/modules/power/singularity/emitter.dm
> +	if(state == 2 && anchored)
I agree, but I won't change in this pr.

2017-08-09 19:10 UTC, Cyberboss commented on code/game/machinery/shieldgen.dm
> +	setDir(pick(1,2,3,4))
GLOB.cardinals!

2017-08-09 19:11 UTC, Cyberboss requested changes

2017-08-09 19:11 UTC, Cyberboss commented on code/game/machinery/shieldgen.dm
> +	setDir(pick(1,2,3,4))
GLOB.cardinals!

2017-08-09 19:14 UTC, merged

2017-08-09 19:14 UTC, RemieRichards commented on code/game/machinery/shieldgen.dm
> +	setDir(pick(1,2,3,4))
3 also isn't a dir, it's NORTH|SOUTH which isn't a dir.