Makes the colon catcher deterministic
tgstation/tgstation pull request #29808
Opened 2017-08-09 14:46 UTC by Cyberboss

- line_num now increments during multiline strings
- line increments now reset a number of things
- ternary_on_line var repurposed to an int to count the number of ternarys
- in_string is now false while in_embedded_statement

Result: no more questionable colons due to ternarys. Updated the operator log

2017-08-09 14:48 UTC, RemieRichards commented on tools/ColonCatcher/2017-08-09-colon_operator_log.txt
> +52/2191 files have colons in them
almost 500 new files and yet 350 less colons.
we're truly doing gods work.

2017-08-09 14:49 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
> +                    in_string = False
but mutliline strings though...

```
var/mstring = {" I
am
not
happy
with
you"}
```

2017-08-09 14:49 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
> +                    if char == "?":
will need updating with 512's ```?.``` operator

2017-08-09 14:51 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
>                          if not data in lines_with_colons: #only add the line twice if it's like: 76, 76? (eg: a "bad" colon and a ternary colon)
? lines can't exist anymore, so update this logic/the comment

2017-08-09 14:52 UTC, RemieRichards requested changes
Looks good, just a few points

2017-08-09 14:52 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
> +                    in_string = False
but mutliline strings though...

```
var/mstring = {"I
am
not
happy
with
you"}
```

2017-08-09 14:52 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
> +                    if char == "?":
will need updating with 512's ```?.``` operator

2017-08-09 14:52 UTC, RemieRichards commented on tools/ColonCatcher/ColonCatcher.py
>                          if not data in lines_with_colons: #only add the line twice if it's like: 76, 76? (eg: a "bad" colon and a ternary colon)
? lines can't exist anymore, so update this logic/the comment

2017-08-09 14:53 UTC, RemieRichards commented
also where was it not deterministic before?
If you mean in the logic of correctly detecting colons that's not determinism that's just fixing it being wonky.

2017-08-09 14:55 UTC, RemieRichards commented on tools/ColonCatcher/2017-08-09-colon_operator_log.txt
> +..code\modules\admin\verbs\SDQL2\SDQL_2.dm Lines: 392, 434 Total Colons: 2
both of these are in strings
https://github.com/tgstation/tgstation/blob/master/code/modules/admin/verbs/SDQL2/SDQL_2.dm#L392
https://github.com/tgstation/tgstation/blob/master/code/modules/admin/verbs/SDQL2/SDQL_2.dm#L434

Not bothered to check other files, this is enough to prove it's still a bit wonk.

2017-08-09 15:00 UTC, RemieRichards commented on tools/ColonCatcher/2017-08-09-colon_operator_log.txt
> +..code\game\mecha\mecha.dm Lines: 717 Total Colons: 1
https://github.com/tgstation/tgstation/blob/master/code/game/mecha/mecha.dm#L717

Also highlighting this one actually, as it's a multi line ternary (DUN DUN DUN!!!1!!)

2017-08-09 15:01 UTC, Cyberboss commented on tools/ColonCatcher/2017-08-09-colon_operator_log.txt
> +..code\game\mecha\mecha.dm Lines: 717 Total Colons: 1
WHY!

2017-08-09 15:09 UTC, Cyberboss commented
By not deterministic I meant not being able o detect embedded ternarys

2017-08-09 15:10 UTC, RemieRichards commented
Then you don't know what determinism means :P

2017-08-13 05:55 UTC, Cyberboss commented
lazy

2017-08-13 05:55 UTC, closed without merging