Adds callback select system
tgstation/tgstation pull request #29843
Opened 2017-08-10 20:47 UTC by MrStonedOne

This system lets you run a group of callbacks asynchronously, returning once all of them finish, without having to wait for each callback to finish before running the next one.

I made it in my bicon pr, but i don't need it anymore, so i removed it from there and put it here.

2017-08-10 20:47 UTC, RemieRichards commented
still hate the name

2017-08-10 22:55 UTC, JJRcop requested changes
Code looks good to me, there are some lingering debug calls to a proc that doesn't exist.

2017-08-10 22:55 UTC, JJRcop commented on code/datums/callback.dm
> +	debug_usr("calling callback")
Debug call

2017-08-10 22:55 UTC, JJRcop commented on code/datums/callback.dm
> +	debug_usr("callback returned")
Debug call

2017-08-10 22:55 UTC, JJRcop commented on code/datums/callback.dm
> +	debug_usr("starting callbacks: [CS.pendingcount]")
Debug call

2017-08-10 22:55 UTC, JJRcop commented on code/datums/callback.dm
> +		debug_usr("callbacks: [CS.pendingcount]")
Debug call

2017-08-11 21:41 UTC, JJRcop approved these changes

2017-08-13 06:01 UTC, Cyberboss approved these changes

2017-08-13 06:26 UTC, merged