Adds icon_states to the unused and used Eldritch whetstones
tgstation/tgstation pull request #29840
Opened 2017-08-10 19:51 UTC by kingofkosmos

Adds icon_states to the unused (pulsing red glow) and used Eldritch whetstones.
Unused: ![image](https://user-images.githubusercontent.com/5420151/29189188-67bc2608-7e1e-11e7-849e-1a3ddcd53b6e.png)
Used: ![image](https://user-images.githubusercontent.com/5420151/29189232-71b32706-7e1e-11e7-8866-b8b705d9f2e0.png)

:cl:
add: Adds icon_states to the unused and used Eldritch whetstones. Sprites by FuryMcFlurry.
/:cl:

2017-08-10 19:53 UTC, Cyberboss requested changes

2017-08-10 19:53 UTC, Cyberboss commented on code/game/gamemodes/cult/cult_items.dm
> +		icon_state = "cult_sharpener_used"
icon_state = "cult_sharpener[used ? "_used" : ""]"

2017-08-10 20:09 UTC, Cyberboss approved these changes

2017-08-11 05:35 UTC, FuryMcFlurry commented
![eldritch stone](https://user-images.githubusercontent.com/8770071/29202321-4b117456-7e67-11e7-8569-bdf44d8730c1.gif)

Heres the animated not used up whetstone.
Also my Ckey is Fury McFlurry, not FuryMcFlurry

2017-08-11 09:26 UTC, kingofkosmos commented
Christ man, first you complain about not getting properly credited in the changelog, only in the PR. And now in the changelog you're still saying it's not properly credited. I dunno what you're achieving with the credits. I mean what are you planning to show these to your future employer or something?

2017-08-11 10:33 UTC, FuryMcFlurry commented
Just stating what I want.

2017-08-11 20:36 UTC, WJohn commented
Better to have it show whether it's used than not 👍

2017-08-12 09:26 UTC, kingofkosmos commented
Checks failed, should I do something about it?

2017-08-13 05:58 UTC, Cyberboss approved these changes

2017-08-13 06:26 UTC, merged