LORD SINGULOTH HUNGERS FOR MORE
tgstation/tgstation pull request #29859
Opened 2017-08-11 18:17 UTC by ShizCalev

Fixes #29857

It'll now dig up the asteroid (sucking the sand off) if in proximity, and "eat" the asteroid if it goes over it like everything else.

2017-08-11 19:44 UTC, KorPhaeron commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	src.ChangeTurf(/turf/open/space)
lmao the fuck are you doing

2017-08-11 19:46 UTC, imtakingabreakdontatme requested changes

2017-08-11 19:46 UTC, KorPhaeron commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	src.ChangeTurf(/turf/open/space)
This will fuck up lavaland pretty badly

You don't need to use src like that

This is snowflake in general

2017-08-11 19:59 UTC, JJRcop commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	src.ChangeTurf(/turf/open/space)
change to baseturf instead of /turf/open/space
still snowflake tho

2017-08-11 20:00 UTC, KorPhaeron commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	src.ChangeTurf(/turf/open/space)
@JJRcop 

Singulo already eats to baseturf, the asteroids baseturf is itself though

2017-08-11 20:59 UTC, ShizCalev commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	src.ChangeTurf(/turf/open/space)
@KorPhaeron Forgot about that, fixed it now. 

Also there's other issues with singularities on lavaland, such as /mob/living/simple_animal/hostile/megafauna not being gibbed by them.

2017-08-12 02:08 UTC, imtakingabreakdontatme requested changes

2017-08-12 02:27 UTC, Iamgoofball commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	if(!(z == ZLEVEL_MINING)) //Turf on lavaland switches to baseturf, preventing immersion breaks.
seems like emergent gameplay

2017-08-12 02:30 UTC, KorPhaeron commented
Activating a zillion turfs and choking the server to death because you set up the PA is not good gameplay

2017-08-12 02:36 UTC, Iamgoofball commented
fuck

2017-08-12 02:44 UTC, ShizCalev commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	if(!(z == ZLEVEL_MINING)) //Turf on lavaland switches to baseturf, preventing immersion breaks.
what's the path? can't fix it if it doesn't exist yet

2017-08-12 02:52 UTC, ShizCalev commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	if(!(z == ZLEVEL_MINING)) //Turf on lavaland switches to baseturf, preventing immersion breaks.
can't fix something that doesn't exist :)

2017-08-12 02:56 UTC, ShizCalev commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	if(!(z == ZLEVEL_MINING)) //Turf on lavaland switches to baseturf, preventing immersion breaks.
Want me to just remove this then, or what?

2017-08-13 06:11 UTC, Cyberboss requested changes

2017-08-13 06:11 UTC, Cyberboss commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +		return
trailing return

2017-08-13 06:11 UTC, Cyberboss commented on code/game/turfs/simulated/floor/plating/asteroid.dm
> +	if(current_size == STAGE_THREE)
Use a switch

2017-08-13 06:11 UTC, Cyberboss commented on code/game/turfs/turf.dm
> +		return TRUE
just do return (T.z in GLOB.z_is_planet)

2017-08-13 12:20 UTC, KorPhaeron commented
This still feels like a lot of snowflake when you could just change the baseturf of asteroid plating to space

2017-08-13 13:07 UTC, ShizCalev commented
@KorPhaeron Wouldn't that cause issues with RCDs, mech RCDs, spacevines, acid, clf3, narsie, and supermatter swords?

2017-08-13 13:28 UTC, Cyberboss commented
No? How so?

2017-08-13 14:08 UTC, ShizCalev commented
Most of the areas on stations that use asteroids with the intent of having them as baseturf aren't properly set (which is part of why I opened #29849 so I could fix it)

Most of those things I mentioned have procs that changes turf to it's baseturf, so setting asteroid baseturf to space would cause unintended behavior (for now atleast), no?

2017-08-13 14:14 UTC, fludd12 commented
https://www.youtube.com/watch?v=sdAwGKk8a4M

2017-08-13 22:57 UTC, optimumtact commented
The base turf hack was to stop the fridge logic of you cutting a square through an entire asteroid with your RCD.

This is probably fine since a singularity can be expected to chop a big hole in most things.

2017-08-14 14:45 UTC, fludd12 commented
Didn't singulo used to make chasms in lavaland?

2017-08-14 15:09 UTC, KorPhaeron commented
What if we load an away mission? How do we tell whether its a planet z or not? What about maps that have different numbers of planet zs?

This is adding a lot of extra checks in different places for a single weird exception to a simple and workable system. The entire point of baseturfs was to avoid z lists and the like

2017-08-14 20:32 UTC, ShizCalev commented
@KorPhaeron Could add a new helper object (similar to the baseturf editor) that adds the z level to the z_is_planet list, which could also be utilized in the future with multi-z planets for any other system that would need it. Just drop it in 1,1 (for consistency) on a map and it'd be added; that way nothing would have to be hardcoded.

2017-08-16 01:44 UTC, ShizCalev commented
@KorPhaeron Input?

2017-08-17 22:17 UTC, ShizCalev commented
Removed the digging component of this PR and moved it to #29994, that way this is more focused on just the eating asteroid turf part.

2017-08-18 15:29 UTC, kevinz000 commented on code/__HELPERS/unsorted.dm
> +	return (T.z in GLOB.z_is_planet)
Do believe an associative list is faster.
Ask maintainers though.

2017-08-22 18:07 UTC, Cyberboss commented on code/__HELPERS/unsorted.dm
> +	return (T.z in GLOB.z_is_planet)
It is, the list should function so that the line should be `return GLOB.z_is_planet[T.z]`

2017-08-24 12:47 UTC, RemieRichards commented
This when:
```dm
//somewhere in world init, after map load
for(var i in 1 to world.maxz)
    var/atom/z_level_meta/zmeta = GLOB.z_level_meta["[i]"]
    if(!zmeta)
        debug("Warning! Z level [i] has no metadata object, treating as generic level (space)")
        zmeta = GLOB.z_level_meta["[i]"] = new /atom/z_level_meta()
 

//on a map:
/atom/z_level_meta
    var/planetary = FALSE
    ... //other stuff we need/want

/atom/z_level_meta/Initialize()
    LAZYSET(GLOB.z_level_meta, "[z]", src)
    return ..()

```

2017-08-24 20:52 UTC, optimumtact commented
WYCI!

2017-08-24 20:52 UTC, RemieRichards commented
I... just did didn't I? ;)

2017-08-24 20:55 UTC, optimumtact commented
:thinking:

2017-08-29 22:10 UTC, merged