The agent card now has 15 throw force
tgstation/tgstation pull request #29887
Opened 2017-08-14 08:48 UTC by optimumtact

The syndicate has added a razor tipped edge to the agent card, as a
weapon of last resort

:cl: orangess
tweak: The syndicate has added a razor edge to the agent card for last resort situations/:cl:
/:cl:

2017-08-14 09:16 UTC, RandomMarine commented
A non-traitor could use this to metaconfirm.

But I'll admit that would be an extreme edge case to have someone suspect somebody else of being a traitor so much that they steal and throw their id in the absence of any stronger evidence.

2017-08-14 11:52 UTC, jughu commented
>A traitor could use this to metaconfirm

If it already didnt give you a giantic action button to change idd type

2017-08-14 14:00 UTC, pubby commented
needs `IS_SHARP`

2017-08-14 14:01 UTC, Cyberboss requested changes
Add the IS_SHARP flag

2017-08-14 14:11 UTC, ma44 commented
>beheading a human

@jughu Only visible if your a antagonist, otherwise you can slightly metaconfirm and just attempt to set them to arrest

2017-08-14 14:37 UTC, MoreRobustThanYou commented
We kinda do need metashield rules tbh

2017-08-14 16:20 UTC, kilkun commented
why not just make both this and the chameleon verb contingent on the mind having the traitor flag turned on

2017-08-14 18:40 UTC, ma44 commented
>spend 14 tc on agent cards
>Load into cannon and fire for instant crit

2017-08-14 19:33 UTC, Repukan commented
Echoes 3 Freeze

2017-08-14 21:57 UTC, Kromgar commented
Make it embed too

2017-08-14 22:37 UTC, PKPenguin321 commented on code/game/objects/items/weapons/cards_ids.dm
>  	var/anyone = FALSE //Can anyone forge the ID or just syndicate?
\>has special vars deliberately designed to keep it from having hard tells, one of the only truly subtle traitor items
\>now it has a hard tell one line below it

2017-08-14 22:46 UTC, InsaneHyena commented
Schrodinger's ID card - only slices people when a traitor uses it.

2017-08-15 10:46 UTC, KorPhaeron commented
Can't wait to have security chuck my ID card at my head every time I get arrested

2017-08-15 10:51 UTC, closed without merging