GRAB FUCKING PIRSONERS
tgstation/tgstation pull request #29918
Opened 2017-08-15 10:38 UTC by Iamgoofball

!(fuck)[https://file.house/Ev5t.png]

2017-08-15 10:39 UTC, RemieRichards commented on strings/brain_damage_lines.json
> +		"@pick(semicolon)okay i'm reporting shitcurity don't grab prisoners with you is 1 shitcurity is 2 and asscurity is 3 = permaban i'm reporting"
what was our stance on OOC in IC in code again?
I believe it was NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.
(the 'permaban' bit)

2017-08-15 10:58 UTC, Iamgoofball commented on strings/brain_damage_lines.json
> +		"@pick(semicolon)okay i'm reporting shitcurity don't grab prisoners with you is 1 shitcurity is 2 and asscurity is 3 = permaban i'm reporting"
there's a whole setup for randomly picking what type of "is it a bug" to pick and brain damage stuff is the ramblings of the insane and damaged

2017-08-15 10:59 UTC, RemieRichards commented on strings/brain_damage_lines.json
> +		"@pick(semicolon)okay i'm reporting shitcurity don't grab prisoners with you is 1 shitcurity is 2 and asscurity is 3 = permaban i'm reporting"
that's a "this is a game" thing, not a "admins be spying on yo ass" thing.
plus we had that whole thing with the "bans" in descriptions of items.

2017-08-15 12:30 UTC, Bawhoppen commented
Say it with me: "Goof's jokes AREN'T FUNNY."

2017-08-15 15:44 UTC, nicbn commented
NO

2017-08-15 15:44 UTC, nicbn commented
STOP ADDING FUCKING LINES

2017-08-15 17:47 UTC, Cyberboss commented
fluff text hurts literally no one @nicbn

2017-08-15 17:47 UTC, Cyberboss requested changes

2017-08-15 17:47 UTC, Cyberboss commented on strings/brain_damage_lines.json
> +		"@pick(semicolon)okay i'm reporting shitcurity don't grab prisoners with you is 1 shitcurity is 2 and asscurity is 3 = permaban i'm reporting"
Fix indentation and remove ooc reference

2017-08-18 18:32 UTC, KorPhaeron commented
stale

2017-08-18 18:32 UTC, closed without merging