[WIP] new old APC sprites
tgstation/tgstation pull request #29922
Opened 2017-08-15 12:17 UTC by pubby

A repainting of the old APC sprites to look like the Eris sprites except not shitty.

Still a work in progress.

![image](https://user-images.githubusercontent.com/1446540/29315450-f0e37b4e-8188-11e7-8554-21fe2183e88f.png)

![image](https://user-images.githubusercontent.com/1446540/29315470-072f93ba-8189-11e7-9888-277dd5241b17.png)

![image](https://user-images.githubusercontent.com/1446540/29315476-0d19b422-8189-11e7-8bed-df4d18ff2a08.png)

![image](https://user-images.githubusercontent.com/1446540/29315485-158d7774-8189-11e7-889d-7335e1e4aa7e.png)

:cl: Pubby
imageadd: new APC sprites (again)
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

2017-08-15 12:59 UTC, GunHog commented
They just look smaller now. APCs should not be smaller given all the information provided from the animation alone! (Charging state, emag state, breaker on/off, equip/power/atmo on/off/auto, locked/unlocked)

2017-08-15 13:12 UTC, pubby commented
These are 1 pixel thinner than the old sprites and have the same indicator lights.

I do not understand what you are talking about.

2017-08-15 13:38 UTC, GunHog commented
Old APCs were shaped like rectangles, yours look like squares. It looks scrunched in comparison.

2017-08-15 13:46 UTC, pubby commented
![image](https://user-images.githubusercontent.com/1446540/29318563-2aef102a-8196-11e7-8077-96d944ee4dc7.png)

This one is now exactly the same dimensions as the old one.

2017-08-15 13:54 UTC, GunHog commented
Works for me :+1:

2017-08-15 16:11 UTC, WJohn commented
These don't even get the benefits of the new ones, and actually are less readable than the old ones. 👎 from me.

2017-08-15 16:52 UTC, pubby commented
Higher contrast diode indicators: yay or nay?

![image](https://user-images.githubusercontent.com/1446540/29326151-0daee6e2-81b0-11e7-9ae6-c3dce074c9dd.png)

2017-08-15 17:04 UTC, Hatfish commented
Better than what we have now 👍

2017-08-15 17:11 UTC, WJohn commented
I mean to say that they don't have the vertically laid out lights, which is the benefit I'm talking about. Besides that, I rather like 3/4th and am biased towards it. I think we could move more towards it. We'll see if there are still complaints after the other contrast update PR is merged.

2017-08-15 17:51 UTC, Cyberboss requested changes

2017-08-15 17:51 UTC, Cyberboss commented on code/modules/power/apc.dm
> +	pixel_y = (src.tdir & 3)? (src.tdir ==1 ? 24 : -24) : 0
remove `src`

2017-08-15 19:36 UTC, Dorsisdwarf commented
I like how these look far more than either the current ones or the other option

2017-08-16 02:12 UTC, Qbopper commented
looks really nice, much better than the current new one

2017-08-16 07:12 UTC, pubby commented
I've added an upper edge to make it a subtle 3/4 perspective and redid the indicator lights to make them readable. I did not explain this before, but the lock/unlock indicator is animated into the card reader.

![image](https://user-images.githubusercontent.com/1446540/29351271-b698efe2-8227-11e7-803e-5d1ecedee399.png)

![image](https://user-images.githubusercontent.com/1446540/29351268-b41d553c-8227-11e7-874b-4039663e6942.png)

I'll consider this my final version. If @WJohn doesn't approve, I'll close this.

2017-08-16 17:48 UTC, nicbn commented
This no longer closes #29716.

2017-08-16 22:55 UTC, optimumtact commented
#29931 is the blessed version

2017-08-16 22:55 UTC, closed without merging