Nerfs Perfluorodecalin.
tgstation/tgstation pull request #29999
Opened 2017-08-17 22:45 UTC by LanCartwright

:cl: 
balance: Perfluorodecalin now only mutes at high level of Oxygen loss damage.
/:cl:

[why]: # Requesting a bypass to the freeze for Chemical nerfs.

Chemical nerfs are not fun and their abuse allows a mere single syringe to kill one person with no chance of retaliation.

With a shift in playerbase, people have rushed to use this to the maximum extent and the rounds aren't fun to deal with this anymore.

2017-08-17 23:52 UTC, Fox-McCloud commented
Perflu doesn't allow you to "kill someone with no retaliation".

Neurotoxin (the drink) is definitely in this category, but definitely not perflu.

2017-08-18 00:35 UTC, PopNotes commented
this is shit, close

2017-08-18 00:45 UTC, Iamgoofball commented
Please think of another downside to replace the mute with, if you're axing one of the balancing modifiers

2017-08-18 09:03 UTC, PraiseRatvar commented
![2017-08-18_10-00-26](https://user-images.githubusercontent.com/28678854/29451862-1dd5982e-83fc-11e7-9a9f-a5e7180a702a.png)
👍 🥇 💯

2017-08-18 09:36 UTC, banthebantz commented
This is what makes the chem balanced for healing purposes you idiot

2017-08-18 14:25 UTC, Hatfish commented
If it's such a problem why not make the chem force you to whisper everything you say?

2017-08-18 18:14 UTC, Ergovisavi commented
>PEOPLE HEALING WITH PERFLUO

Let's not kid around here, it's exclusively used as mute toxin

2017-08-18 22:56 UTC, Iamgoofball commented
it's a VERY good spacewalk chem

2017-08-19 00:05 UTC, AdamElTablawy commented
It's a fantastic spacewalk chem. 

Or good for use in a cryo mix, or just stabilizing critted people, etc. 

It's just also a ghetto mute toxin-the problem with using it to kill someone is that they heal suffocation damage, so critting and leaving isn't quite an option.

But yes, it's a particularly effective chem if you just use it in a spraybottle with neurotoxin. Instant stun + mute, no fort save. 

Could probably do with another downside other than muting, since it makes mute toxin basically useless for all the difficulty mute toxin requires.

2017-08-19 01:32 UTC, ExcessiveUseOfCobblestone commented
Why not use salbu over perf?

2017-08-19 23:04 UTC, Cyberboss requested changes

2017-08-19 23:04 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  		M.adjustBruteLoss(-0.5*REM, 0)
You removed the prob(). Either re add it or update the desc

2017-08-19 23:10 UTC, kevinz000 commented
wtf i like jmad now?

2017-08-20 00:01 UTC, ExcessiveUseOfCobblestone commented
also those quads

2017-08-20 01:04 UTC, XDTM commented
salbu is enough to breathe without oxygen, there's no real healing use for perfluoro except extreme blood loss i suppose

2017-08-20 01:47 UTC, ExcessiveUseOfCobblestone commented
it also heals brute/burn like sal-poo I think

2017-08-20 02:39 UTC, PopNotes commented
overall bad change

2017-08-20 14:29 UTC, LanCartwright commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  		M.adjustBruteLoss(-0.5*REM, 0)
I mean it's a may as in you may not have huge amounts of oxyloss damage to garuantee the mute.

2017-08-20 15:30 UTC, LanCartwright commented
@PopNotes fucking crybaby 

https://github.com/HippieStation/HippieStation/pull/2751
https://github.com/HippieStation/HippieStation/pull/2692
https://github.com/HippieStation/HippieStation/pull/2680

waaah waah i don't get my way when i add shitty fucking features and buff antag/antagbait content.

here go mergebeg your shitty firesuit somewhere else

2017-08-21 00:56 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  		M.adjustBruteLoss(-0.5*REM, 0)
It's not a "may" in that case, there's a specific trigger for it. Update the dec

2017-08-22 07:48 UTC, closed without merging

2017-08-22 08:30 UTC, Iamgoofball commented
why?