Reopens #28650
tgstation/tgstation pull request #29990
Opened 2017-08-17 20:27 UTC by ExcessiveUseOfCobblestone

#28650 

🆑 Cobby
add: A stealth option for the traitor microlaser has been added. When used, it adds 30 seconds to the cooldown of the device.
/🆑

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=11789

People disliked having an easy tell on them when using it, but I didn't want to make it come without costs.

2017-08-17 20:37 UTC, RemieRichards commented on code/game/objects/items/devices/traitordevices.dm
> +	dat += "Stealth Mode (NOTE: Deactivates automatically while Irradiation is off): <A href='?src=\ref[src];stealthy=1'>[stealth ? "On" : "Off"]</A><br>"
if you wanted square brackets, just make the first one ```\[``` to escape the parsing.

2017-08-17 20:38 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/devices/traitordevices.dm
> +	dat += "Stealth Mode (NOTE: Deactivates automatically while Irradiation is off): <A href='?src=\ref[src];stealthy=1'>[stealth ? "On" : "Off"]</A><br>"
it's no biggy, just didn't know what the problem was

2017-08-19 23:11 UTC, kevinz000 commented
This might be a bit op if you can just graze and hit someone with it and they pass out later with no indication of being hit with it unless they had a hardsuit.

2017-08-19 23:14 UTC, Cyberboss requested changes

2017-08-19 23:14 UTC, Cyberboss commented on code/game/objects/items/devices/traitordevices.dm
> +	if(!stealth || (stealth && !irradiate))
just `if(!stealth || !irradiate)`

2017-08-19 23:14 UTC, Cyberboss commented on code/game/objects/items/devices/traitordevices.dm
>  	if(!used)
You didn't actually change the cooldown 3 lines below here

2017-08-19 23:14 UTC, Cyberboss commented on code/game/objects/items/devices/traitordevices.dm
> +	dat += "Stealth Mode (NOTE: Deactivates automatically while Irradiation is off): <A href='?src=\ref[src];stealthy=1'>[stealth ? "On" : "Off"]</A><br>"
stealthy=[TRUE]

2017-08-19 23:15 UTC, Cyberboss commented
I don't understand the point of this when people who use it will get the radiation printout anyway.

2017-08-19 23:26 UTC, kevinz000 commented
i believe this prevents the message from being shown to everyone?

2017-08-20 00:05 UTC, ExcessiveUseOfCobblestone commented
It prevents the visible "someone scanned X" message.

@kevinz000 Kevinz there's a pen that you can combine with traitor chems to mute and kill you instantly since it's a hypo, not to mention you'll just look for the person running around with an analyzer after the first time like you would a gang pen. I think this is pretty tame.

2017-08-20 18:06 UTC, Kraseo commented
yeah but said pen has an indication of being used

2017-08-20 19:00 UTC, ExcessiveUseOfCobblestone commented
but it doesn't matter because you're lol stunned or lol ded. 

There's also the ebow which is entirely silent. You can hit someone from the dark and they can't do anything except ; help

2017-08-22 12:45 UTC, kevinz000 commented
eh, fair.

2017-08-22 14:33 UTC, Cyberboss commented
@ExcessiveUseOfCobblestone

2017-08-22 18:56 UTC, ExcessiveUseOfCobblestone commented
WHY DID IT JUST GIVE ME NOTIFICATIONS FOR THIS PR DUMB DUMB DUMB!

2017-08-22 19:00 UTC, ExcessiveUseOfCobblestone commented
I did some github memery and now this branch is GONE 5ever so I guess ill just do this pr later in life.

2017-08-22 19:00 UTC, closed without merging