Adds magillitis, a traitor syrum for geneticists & CMOs
tgstation/tgstation pull request #30113
Opened 2017-08-23 02:42 UTC by ShizCalev

Upon injection of the syrum into a monkey, it will transform the monkey into a gorilla.

@The-clown-known-as-Pepe Ask and ye shall receive.

2017-08-23 02:47 UTC, RandomMarine commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/toxin/magillitis
What's the point of this being under the toxin path?

2017-08-23 02:52 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/toxin/magillitis
Just to make it clear that it's a bad chemical. Can move it anywhere if requested.

2017-08-23 02:59 UTC, RandomMarine commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/toxin/magillitis
It doesn't really matter much. But being under the toxin path just makes it count for liver shenanigans and trekchem anti-toxin. Which seems pointless when it just makes monkeys into gorillas.

2017-08-23 03:06 UTC, RandomMarine commented
As another note, it's a simple matter to split the 5u you get in each bottle to 0.1u doses.

Enough to mutate 50 gorillas.

2017-08-23 04:48 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/toxin/magillitis
could probably just do tox damage to non-monkeys

2017-08-23 06:49 UTC, Armhulen commented
but gorillas are incredibly easy to get. Make it turn humans into gorillas, and you'd have something to write home about.

2017-08-23 07:08 UTC, DoctoreMad commented
I'll be surprised if Gorillas aren't unmerged by a weeks time.
Pre-emptive PR, its totally okay.

2017-08-23 07:23 UTC, ShizCalev commented
@Armhulen Easy change, but I don't want to go balls to the wall too early since they're still being tweaked.

2017-08-23 08:24 UTC, DoctoreMad commented
I liked experimental syrup more.

2017-08-23 10:18 UTC, pubby commented
If the radiation transformation doesn't get removed, traitors can use a microlaser to make gorillas.

2017-08-23 11:58 UTC, FantasticFwoosh commented
you want to know the best part about this?

- Its a reagent so you can get it from strange plants in hydroponics

2017-08-23 15:46 UTC, The-clown-known-as-Pepe commented
@FantasticFwoosh its like hitting a big rng loterry, you have 30% chance to get a chem in strange plant and then you have to roll this exact chem.

2017-08-23 16:25 UTC, FantasticFwoosh commented
As my previous PR proves at #29956, there are ways to play the lottery more than once if the right tools are put in place, and the lottery is always fun game to play.

2017-08-23 19:47 UTC, Cyberboss requested changes

2017-08-23 19:47 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		M.gorillize()
Make it use all 5u first (cycle var i think?)

2017-08-23 19:47 UTC, Cyberboss commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	container_type = 0
NONE

2017-08-23 19:47 UTC, Cyberboss commented on code/modules/reagents/reagent_containers/hypospray.dm
> +			to_chat(user, "<span class='notice'>I probably shouldn't use that on [M.p_them()]...</span>")
Non traitors know this how?

2017-08-23 19:47 UTC, Cyberboss commented on code/modules/uplink/uplink_item.dm
> +	item = new /obj/item/reagent_containers/hypospray/magillitis
This is supposed to be a path, not an instance

2017-08-23 20:48 UTC, ShizCalev commented on code/modules/uplink/uplink_item.dm
> +	item = new /obj/item/reagent_containers/hypospray/magillitis
Whoop.

2017-08-24 13:44 UTC, RicardoFort commented
Rename it Injector de Maccaco and call it a day

2017-08-24 14:22 UTC, Cyberboss requested changes

2017-08-24 14:22 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	..()
Call ..() first

2017-08-24 14:22 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	if(ismonkey(M) && volume >= 5)
Change `volume >= 5` to `current_cycle >= 10`

2017-08-24 14:22 UTC, Cyberboss requested changes

2017-08-24 14:22 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		M.reagents.del_reagent("magillitis")
Remove this line

2017-08-26 15:26 UTC, Cyberboss approved these changes
For 15TC, sure why not

2017-08-26 15:37 UTC, merged