Fixes clowns blowing shit up not being logged 50% of the time
tgstation/tgstation pull request #30175
Opened 2017-08-25 11:32 UTC by kevinz000

clowny clown clown :clown_face:

2017-08-25 11:35 UTC, AnturK commented
Don't copypaste, add argument/s to the standard function

2017-08-25 12:20 UTC, KingPhilipIII commented
Why the clown in specific?

2017-08-25 14:03 UTC, Cyberboss requested changes

2017-08-25 14:03 UTC, Cyberboss commented on code/game/objects/items/grenades/grenade.dm
> +	log_game("[key_name(user)] has primed a [name] for detonation at [A.name] [COORD(T)].")
\a [src]

2017-08-25 14:03 UTC, Cyberboss commented on code/game/objects/items/grenades/grenade.dm
> +	var/message = "[ADMIN_LOOKUPFLW(user)]) has primed a [name] for detonation at [ADMIN_COORDJMP(T)]"
\a [src]

2017-08-27 00:19 UTC, kevinz000 commented
fixing this soon dont yell at me <3

2017-08-27 23:18 UTC, Cyberboss commented
REEEE

2017-08-28 10:42 UTC, PraiseRatvar commented
WHY THE CLOWN IN SPECIFIC?

2017-08-28 14:15 UTC, kevinz000 commented
fixed

2017-08-28 18:13 UTC, Cyberboss requested changes

2017-08-28 18:13 UTC, Cyberboss commented on code/game/objects/items/grenades/grenade.dm
> +	var/message = "[ADMIN_LOOKUPFLW(user)]) has primed \a [name] for detonation at [ADMIN_COORDJMP(T)]"
[src]

2017-08-28 18:13 UTC, Cyberboss commented on code/game/objects/items/grenades/grenade.dm
> +	log_game("[key_name(user)] has primed \a [name] for detonation at [A.name] [COORD(T)].")
[src]

2017-08-28 18:13 UTC, Cyberboss commented on code/game/objects/items/grenades/grenade.dm
> +/obj/item/grenade/proc/glog(mob/user, turf/T)
name this something more descriptive

2017-08-29 14:31 UTC, Cyberboss approved these changes

2017-08-29 14:31 UTC, merged