Makes APC cell_type actually pick a cell
tgstation/tgstation pull request #30327
Opened 2017-08-31 23:46 UTC by ShizCalev

Closes #30326

Setting a APC's cell_type path used to set the max charge for the standard cell inside, resulting in a ton of var-editted increased capacity cells being spread out around the station.

This makes it so those cells are actually the proper types instead of just being a mass of varedited ones.

2017-08-31 23:49 UTC, ShizCalev commented
Should probably make new subtypes for the APCs with custom cells in them to prevent someone accidentally putting down a super-high cap one where it's not needed, but I think people would kill me for doing that.

2017-09-01 02:31 UTC, Jordie0608 requested changes

2017-09-01 02:31 UTC, Jordie0608 commented on code/modules/power/cell.dm
> +	desc = "A power cell with an every higher capacity than the base model!"
`an even higher`

2017-09-01 02:31 UTC, Jordie0608 commented on code/modules/power/apc.dm
> +		src.cell = new cell_type
Kill off the `src.` while you're here.

2017-09-01 02:32 UTC, Jordie0608 commented
Subtypes does't sound too bad.

2017-09-01 03:04 UTC, Jordie0608 approved these changes

2017-09-01 03:11 UTC, ShizCalev commented
Just as a note, I'll be offering assistance for anyone currently making a map / downstream folks if they can't figure out how to update their APCs for this.

2017-09-03 03:16 UTC, merged