adds a brain damage line
tgstation/tgstation pull request #30363
Opened 2017-09-02 22:02 UTC by Iamgoofball

# IM GONNA CUM

2017-09-02 22:02 UTC, Errorin commented
# **BIG CUMS**

2017-09-02 22:04 UTC, The-clown-known-as-Pepe commented
💦

2017-09-02 22:29 UTC, Bluespace commented
Add another that says 
"robotacist has FLASH!!! REVV?"

2017-09-02 22:43 UTC, Repukan commented
Add another one that says 

"Year of the goof"

2017-09-02 23:24 UTC, AnonymousNow commented
Can't like on principle, since "revert Goonchem" is a line, for some reason.

2017-09-03 01:41 UTC, GunHog commented
"I test this"?

2017-09-03 16:06 UTC, Cyberboss requested changes

2017-09-03 16:06 UTC, Cyberboss commented on strings/brain_damage_lines.json
> +		"@pick(semicolon)ay-tee ess-tees AY-TEE ESS-TEES!!!"
indentation

2017-09-03 23:45 UTC, Bawhoppen commented
NO MORE BRAIN DAMAGE LINES

2017-09-04 22:44 UTC, KorPhaeron commented
2 days to fix an indentation is stale

2017-09-04 22:44 UTC, closed without merging

2017-09-04 23:30 UTC, Iamgoofball commented
Lmao my comment didn't go through