More timer debugging for the debug gods.
tgstation/tgstation pull request #30436
Opened 2017-09-05 09:32 UTC by MrStonedOne

Records what time a timer is spent for debug outputting

A runtime was made to use `get_timer_debug_string`.

`get_timer_debug_string` reports rather or not something has a callback at that moment.

And I made an undocumented change to timer's New

2017-09-05 09:35 UTC, RemieRichards commented
@MrStonedOne do you mean being able to add it to the last commit, or add more commits? (re: last commit message)

2017-09-05 09:39 UTC, MoreRobustThanYou commented
> patch-420

insert shitty 420 meme here

2017-09-05 13:40 UTC, Cyberboss requested changes

2017-09-05 13:40 UTC, Cyberboss commented on code/controllers/subsystem/timer.dm
> +	if(!timer.callBack)
TE

2017-09-05 16:29 UTC, MrStonedOne commented
@RemieRichards add it to the last commit

2017-09-07 14:58 UTC, Cyberboss approved these changes

2017-09-07 14:58 UTC, merged