Gives the webhook processor the ability to self update
tgstation/tgstation pull request #30448
Opened 2017-09-05 18:05 UTC by Cyberboss

What it says on the tin

2017-09-09 09:39 UTC, MrStonedOne commented on tools/WebhookProcessor/github_webhook_processor.php
> +	$content = file_get_contents('https://raw.githubusercontent.com/' . $payload['pull_request']['base']['repo']['full_name'] . '/master/'. $path_to_script);
While we normally use these github variables, it might be worth it to config this so that we can harden against a minor api flaw or secret leak from becoming a full blown RCE exploit.

Might.

2017-09-09 22:40 UTC, Cyberboss commented
Done

2017-09-11 08:19 UTC, MrStonedOne commented on tools/WebhookProcessor/github_webhook_processor.php
> +	$code_file = fopen(basename($path_to_script), 'w');
So, one minor issue.

on/tg/, `github_webhook_processor.php` is not the name of script locally.

2017-09-11 08:19 UTC, MrStonedOne commented on tools/WebhookProcessor/github_webhook_processor.php
>  $maintainer_team_id = 133041;	//org team id that is exempt from PR balance system, setting this to null will use anyone with write access to the repo. Get from https://api.github.com/orgs/:org/teams
all configs need to be in the secrets file, as other wise they get replaced

2017-09-11 08:29 UTC, MrStonedOne commented on tools/WebhookProcessor/secret.php
> +$hookSecret = '08ajh0qj93209qj90jfq932j32r';
It worked perfectly fine without the globals in this file on my test.

I was not able to see anything that would explain this being required skimming thru the 5->7 compilability changes list

2017-09-11 08:57 UTC, MrsTonedOne requested changes
Branches man.

2017-09-11 08:57 UTC, MrStonedOne commented on tools/WebhookProcessor/github_webhook_processor.php
> +	$content = file_get_contents('https://raw.githubusercontent.com/' . $repoOwnerAndName . '/master/'. $path_to_script);
Branch name should be configurable.

2017-09-11 08:57 UTC, MrStonedOne commented on tools/WebhookProcessor/github_webhook_processor.php
> +	if(!$enable_live_tracking || !has_tree_been_edited($payload, $path_to_script))
This should also check that the pr is against the configured branch name

2017-09-11 09:24 UTC, MrStonedOne commented
This is currently live. make the changes and then get this merged.

The live version already has all configs moved too.

2017-09-11 21:24 UTC, optimumtact commented
@MrStonedOne ready?

2017-09-11 22:40 UTC, MrStonedOne commented
no, CB is going to make it default the config settings for when new settings get added

2017-09-12 01:59 UTC, merged