Flying mobs now clip past non flying mobs, various flightsuit/iontrail/movement tweaks/code improvements/bugfixes
tgstation/tgstation pull request #30570
Opened 2017-09-10 10:48 UTC by kevinz000

:cl:
experimental: Flying mobs now fly over those that aren't flying.
experimental: Flightsuits will now be unstable if EMPed! Don't get ion'd! 
bugfix: Flightsuits now allow proper pulling
experimental: Moved now has an argument for if it was a regular Move or a forceMove.
rscadd: Instead of dumb sleep()s, follow trails now use SSfastprocess for processing!
rscadd: Mobs now float while flying automatically!
rscdel: Flightsuits can no longer be safely shut off if you're still barreling down the hallway.
experimental: Flightsuits should be less shitcode. Hope this PR doesn't blow anything important up!
/:cl:

2017-09-10 11:29 UTC, PraiseRatvar commented
> experimental: Flightsuits will now be unstable if EMPed! Don't get ion'd!

explain

2017-09-10 11:43 UTC, kevinz000 commented
emp = each move has a chance to throw you off by one tile instead of being perfectly accurate.
pulling = fixes pulling being interrupted when you fly past things.

2017-09-10 17:26 UTC, DoctoreMad commented
Does crashing into a wall due to EMP damage you?

2017-09-10 21:55 UTC, kevinz000 commented
hmmm i really should make emps more lethal

2017-09-20 09:04 UTC, optimumtact commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/icon_state_active = "flightpack_on"
why are these vars and not defines?

2017-09-20 09:04 UTC, optimumtact commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/icon_state_active = "flightpack_on"
vars have a performance impact

2017-09-20 09:07 UTC, optimumtact commented on code/modules/mob/living/living.dm
> +//TODO: Better floating
can you not add these? they very rarely get followed up on, keep a todo list in your own management tool of choice

2017-09-23 00:53 UTC, kevinz000 commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/icon_state_active = "flightpack_on"
is varediting an acceptable response?

2017-10-13 21:45 UTC, duncathan requested changes

2017-10-13 21:45 UTC, duncathan commented on code/modules/mob/living/living.dm
> +	if(((movement_type & FLYING) && !(M.movement_type & FLYING)) || (!(movement_type & FLYING) && (M.movement_type & FLYING)))	//Fly past each other.
`if((movement_type & FLYING) ^ (M.movement_type & FLYING))`

2017-10-14 00:07 UTC, duncathan approved these changes

2017-10-14 00:09 UTC, merged