Lessens preferences lag
tgstation/tgstation pull request #30596
Opened 2017-09-11 01:28 UTC by kevinz000

Makes it reuse one mob instead of making and deleting one each time it generates a preview.
Tested to work with one person, no idea how it'll behave on live, hope this can get a testmerge.

2017-09-11 01:30 UTC, Cyberboss requested changes

2017-09-11 01:30 UTC, Cyberboss commented on code/__HELPERS/icons.dm
> +		return D
Move these two lines out of each if

2017-09-11 14:16 UTC, Cyberboss requested changes

2017-09-11 14:16 UTC, Cyberboss commented on code/__HELPERS/icons.dm
> +GLOBAL_LIST_INIT(human_dummy_list, list())	//Dummy mob = In use (TRUE/FALSE)
GLOBAL_LIST_EMPTY

2017-09-11 14:16 UTC, Cyberboss commented on code/__HELPERS/icons.dm
> +/proc/generate_or_wait_for_human_dummy(slotkey)
Why not put all this crap in dummy.dm, then you wouldn't have to move the UNTIL macro

2017-09-13 17:47 UTC, Cyberboss requested changes

2017-09-13 17:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/dummy.dm
> +
probably should cut_overlays(TRUE) here as well

2017-09-13 17:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/dummy.dm
> +	UNTIL(!D.in_use)
what if D is QDELETED during the UNTIL?

2017-09-14 14:24 UTC, Cyberboss requested changes

2017-09-14 14:24 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/dummy.dm
> +/mob/living/carbon/human/dummy/Life()
Add a Destroy() above here and set in_use to FALSE in it

2017-09-15 19:14 UTC, Cyberboss approved these changes

2017-09-15 19:14 UTC, merged

2018-10-19 02:04 UTC, MrStonedOne commented on code/modules/mob/living/carbon/human/dummy.dm
> +		pass()
WHAT IS THAT

WHAT. THE. FUCK. IS. THAT?