Fixes evidence bags showing ghost contents after their contents get deleted
tgstation/tgstation pull request #30702
Opened 2017-09-13 18:55 UTC by vuonojenmustaturska

Fixes #9544

On a related note, I cannot reproduce #20795 but it might've been caused by this bug leaving a ghost in the evidence bag that was used to bag the item.

[Changelogs]: 
[]: 

:cl: Naksu
fix: Evidence bags will no longer show ghosts of items such as primed flashbangs after the flashbang inside explodes
/:cl:

[why]: 
bugfix

2017-09-14 16:11 UTC, Cyberboss requested changes

2017-09-14 16:11 UTC, Cyberboss commented on code/modules/detectivework/evidence.dm
> +	desc = "An empty evidence bag."
initial for icon_state and desc

2017-09-14 16:12 UTC, Cyberboss commented on code/modules/detectivework/evidence.dm
> +	desc = "An empty evidence bag."
and w_class

2017-09-14 19:42 UTC, vuonojenmustaturska commented on code/modules/detectivework/evidence.dm
> +	desc = "An empty evidence bag."
eh, might as well

2017-09-14 19:54 UTC, vuonojenmustaturska commented
tested and still works

2017-09-15 05:17 UTC, Cyberboss approved these changes

2017-09-15 05:17 UTC, merged