Species blacklist refactor/defines in species vars
tgstation/tgstation pull request #30784
Opened 2017-09-16 01:47 UTC by KorPhaeron

The magic mirror now uses the species blacklisted var instead of a list of strings

Used defines for various species vars

This also fixes nightmare being selectable by the wizard

2017-09-17 11:47 UTC, Cyberboss requested changes
You also need to change the checks for the blacklisted var

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/angel.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/corporate.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/plasmamen.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species.dm
> +	var/blacklisted = FALSE //Flag to exclude from green slime core species or the magic mirror
Make it a flags var instead

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
>  	blacklisted = TRUE
You didn't remove the old line

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/synths.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/skeletons.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-17 11:47 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +	blacklisted = SPECIES_BLACKLIST_MAGIC_MIRROR
| SPECIES_BLACKLIST_SLIME_MUT

2017-09-18 02:41 UTC, KorPhaeron commented
@Cyberboss 

Should I just put these in with the rest of the species flags then, or move the other blacklist related vars (changeling stings) out of the species flags and into this new list?

2017-09-18 12:48 UTC, Cyberboss commented
go with the second

2017-09-20 08:55 UTC, optimumtact commented on code/modules/mob/living/carbon/human/species.dm
> +	var/list/species_blacklist = list()
why this be a list and not a flag, u only got 4 things yo

2017-09-20 08:55 UTC, optimumtact commented on code/modules/mob/living/carbon/human/species.dm
> +	var/list/species_blacklist = list()
we paying init overhead for all these lists, every single one on every single species datum

2017-09-20 08:55 UTC, optimumtact commented on code/modules/mob/living/carbon/human/species.dm
> +	var/list/species_blacklist = list()
you didn't even make a lazy init list shame on you

2017-09-20 15:37 UTC, XDTM commented
Add no trans sting and no dna copy to android, no way a ling can get its dna!

2017-09-21 02:31 UTC, KorPhaeron commented
Between getting ready for classes and divinity 2 I realistically will not work further on this

2017-09-21 02:31 UTC, closed without merging