Makes building with plasma glass a thing.
tgstation/tgstation pull request #30800
Opened 2017-09-16 09:14 UTC by ShizCalev

Closes #30760

Adds a helper, isglasssheet, which returns if the sheet you're using is... glass.

Makes it so that you can actually build plasma windows on grills, as well as being able to make fireproofed airlocks with plasma glass sheets.

2017-09-16 09:34 UTC, MrROBUST commented
Will something like `is_glass_sheet` look better?

Can DM fill glass_sheet_types list via constructors of /obj/item/stack/sheet/glass and subtypes?

2017-09-16 09:59 UTC, ShizCalev commented
Was on the fence about doing is_glass_sheet since only one other helper uses underscores, but I agree that it does look better.

2017-09-17 12:11 UTC, Cyberboss requested changes

2017-09-17 12:11 UTC, Cyberboss commented on code/game/objects/structures/grille.dm
> +					WD = new/obj/structure/window/plasma/fulltile(loc) //plasma window
These locs should be drop_location()

2017-09-17 16:35 UTC, Cyberboss requested changes

2017-09-17 16:35 UTC, Cyberboss commented on code/game/objects/structures/grille.dm
> +		new /obj/effect/temp_visual/ratvar/beam/grille(drop_location())
effects like these should probably stay on the turf

2017-09-17 19:32 UTC, Cyberboss requested changes

2017-09-17 19:32 UTC, Cyberboss commented on code/game/objects/structures/grille.dm
> +			new grille_type(drop_location())
Given that this is a transformation, it should use loc

2017-09-17 20:06 UTC, merged