Fixes singularity not instantly consuming things the center passes over
tgstation/tgstation pull request #30845
Opened 2017-09-17 22:47 UTC by kevinz000

fixes #9946

2017-09-17 23:11 UTC, Cyberboss requested changes

2017-09-17 23:11 UTC, Cyberboss commented on code/modules/power/singularity/singularity.dm
> +	return
No trailing return

2017-09-17 23:11 UTC, Cyberboss commented on code/modules/power/singularity/singularity.dm
> +	consume(A)
..() first

2017-09-17 23:20 UTC, ChangelingRain commented
the fact that the singularity doesn't keep drifting after it bumps into something is the major part of the issue there so like, can you make it keep drifting in the direction it was drifting after it bumps something

2017-09-18 09:38 UTC, kevinz000 commented
@ChangelingRain done it now always returns false on process_spacemove

2017-09-19 18:29 UTC, ChangelingRain commented
It already did that, so no, you haven't fixed it.

2017-09-29 02:50 UTC, closed without merging