Adds new helper, DisplayTimeText
tgstation/tgstation pull request #30940
Opened 2017-09-21 19:46 UTC by ShizCalev

Noticed that there was tons of duplicate math to calculate how much time was remaining on some items for chat messages.

This cleans up that math by adding a new helper, DisplayTimeText(). 

It takes a value in deciseconds and returns the amount as a text value with the correct measurement proceeding it (days, hours, minutes, seconds.)

This makes it so you will no longer see messages such as "This will take around 1 minutes", instead saying "This will take 60 seconds." Something that says "This will take 1 seconds" now only states "This will take 1 second."

It will roll over to the larger figure once you pass the exact point for the corresponding measurement, IE; 1.1 minutes = 1.1 minutes. 1 hour exact = 60 minutes. 1.1 hours = 1.1 hours, so on so forth.

2017-09-21 23:23 UTC, Jordie0608 requested changes

2017-09-21 23:23 UTC, Jordie0608 commented on code/__DEFINES/misc.dm
> +#define DECISECONDS_WEEK		6048000
This one is unused and could be done without.

2017-09-22 00:34 UTC, Jordie0608 submitted a review, later dismissed

2017-09-22 17:36 UTC, Cyberboss submitted a review, later dismissed

2017-09-22 17:36 UTC, Cyberboss commented on code/__HELPERS/time.dm
> +/proc/DisplayTimeText(var/time_value)
remove var/

2017-09-22 17:37 UTC, Cyberboss requested changes
What I said

2017-09-22 20:47 UTC, ChangelingRain commented
I'd kind of prefer `1 hour and 6 minutes` instead of `1.1 hours`

2017-09-23 00:23 UTC, ShizCalev commented
@ChangelingRain Got it working; I'll make another PR for it in a bit so folks can decide.

2017-09-23 10:26 UTC, Jordie0608 commented
I think it's fair to say the alternate PR is all around better as it reads akin to normal formatting and avoids uglies like `3.9 minutes`

2017-09-23 10:26 UTC, closed without merging