Blackbox stat for internet midis
tgstation/tgstation pull request #31033
Opened 2017-09-26 18:38 UTC by JJRcop

New blackbox stat when playing internet midis, which stores the url played. This only happens when the url is valid and successfully plays.

nfreader/newSS13tools#63

2017-09-26 18:45 UTC, Cyberboss requested changes

2017-09-26 18:45 UTC, Cyberboss commented on code/modules/admin/verbs/playsound.dm
> +					SSblackbox.add_details("played_url","[web_sound_input]")
Don't stringify web_sound_input

2017-09-26 20:43 UTC, nfreader commented
Hooray

2017-09-26 20:54 UTC, Cyberboss approved these changes

2017-09-27 18:15 UTC, kevinz000 commented
fuck

2017-09-27 20:44 UTC, merged