Refactor quick create antag, fixed AFK rev roundend
tgstation/tgstation pull request #31103
Opened 2017-09-28 22:12 UTC by ShizCalev

Fixes #29322

Also cleans up quick antag creation code a bit. 
Players who are AFK will no longer be made new antags through the panel.

2017-09-29 04:06 UTC, Cyberboss requested changes

2017-09-29 04:06 UTC, Cyberboss commented on code/__HELPERS/game.dm
> +/datum/proc/considered_alive(datum/mind/M)
certainly you meant something other than /datum?

2017-09-29 04:06 UTC, Cyberboss commented on code/__HELPERS/game.dm
> +/datum/proc/considered_afk(datum/mind/M)
ditto

2017-10-02 07:33 UTC, AnturK commented on code/__HELPERS/game.dm
> +		switch(enforce_human)
All good but switch on boolean is just ugly.

2017-10-02 07:48 UTC, merged