Makes gutlunches hungry for gibs again
tgstation/tgstation pull request #31241
Opened 2017-10-02 18:10 UTC by vuonojenmustaturska

In my zealousness in #31141 I mistakenly removed the ability of gutlunches to find and eat gibs. As gib-eating directly affects their milk production, this is a bit worse than just some missing fluff.

[Changelogs]: 

:cl: optional name here
fix: Gutlunches will now once again look for gibs to eat.
/:cl:

[why]:
Bugfix

2017-10-02 18:10 UTC, Cyberboss requested changes

2017-10-02 18:10 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
> +		if(attack_all_objects || is_type_in_typecache(the_target, wanted_objects))
Combine these ifs

2017-10-02 18:10 UTC, vuonojenmustaturska commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
> +		if(attack_all_objects || is_type_in_typecache(the_target, wanted_objects))
I'll do one better

2017-10-02 23:22 UTC, FantasticFwoosh commented
Was there any other collateral damage in the behaviour of gold-grubs etc? Its one of the only other object orientated creatures that comes to mind.

2017-10-02 23:25 UTC, JJRcop commented
optional name here does it again!

2017-10-03 00:04 UTC, vuonojenmustaturska commented
@FantasticFwoosh no, goldgrubs are straight simple animals AI-wise. The mistake with gutlunches was when I ported their snowflake exceptions to a copy-pasted override proc and trimmed down on all the stuff gutlunches don't actually do.

2017-10-04 09:11 UTC, merged