Hosts can lock config options from admins
tgstation/tgstation pull request #31254
Opened 2017-10-03 03:59 UTC by JJRcop

:cl:
config: Hosts can now lock config options with the @ prefix. This prevents admins from editing the option in-game.
/:cl:

Figured if we had some hard coded ones why not let downstreams easily lock whichever ones themselves without editing the code.

2017-10-03 20:23 UTC, Cyberboss requested changes

2017-10-03 20:23 UTC, Cyberboss commented on code/controllers/configuration/configuration.dm
> +		if(copytext(L, 1, 2) == "@")
var/lockthis = copytext(L, 1, 2) == "@"
if(lockthis)

2017-10-03 20:23 UTC, Cyberboss commented on code/controllers/configuration/configuration.dm
> +			lockthis = TRUE
and then remove this line

2017-10-03 22:30 UTC, Cyberboss approved these changes

2017-10-04 19:58 UTC, optimumtact commented
This is a really good change, thanks

2017-10-04 19:58 UTC, merged