Adds ERP intent, makes tail-wagging a signal of ERP intent, adds wagging tails for lizards
tgstation/tgstation pull request #31321
Opened 2017-10-04 22:20 UTC by vuonojenmustaturska

This is fairly small beans, but every little bit helps I guess.

Measured by total time (the one that actually matters in this case):

/datum/gas_mixture/thermal_energy() is infinitely faster, due to no longer existing.
/datum/gas_mixture/react() is 5.6% faster, due to no longer calling thermal_energy()
/datum/pipeline/proc/reconcile_air() is 6.24% faster, for the same reason

Measured by self time (the one that actually doesn't matter in this case)
/datum/gas_mixture/thermal_energy() still does not exist
/datum/gas_mixture/react() is 0.48% slower, due to taking on extra work that used to happen in thermal_energy()
/datum/pipeline/proc/reconcile_air() is 1.5% slower, for the same reason

[Changelogs]: 

:cl: Naksu
tweak: Made atmos tiny bit faster
/:cl:

[why]: 
![image](https://user-images.githubusercontent.com/20017308/31202167-3f62a69c-a96a-11e7-9ff6-da06d791de78.png)

2017-10-04 22:48 UTC, Thunder12345 commented
![img_0188](https://user-images.githubusercontent.com/5479091/31203318-77462932-a95e-11e7-9ab9-e7e42a4a7d59.JPG)

2017-10-05 13:55 UTC, Cyberboss requested changes

2017-10-05 13:55 UTC, Cyberboss commented on code/modules/atmospherics/gasmixtures/gas_mixture.dm
> +#define THERMAL_ENERGY(gas) (gas.temperature * gas.heat_capacity())
Since it's used across files, put it in __DEFINES/atmospherics.dm please

2017-10-05 18:51 UTC, Cyberboss approved these changes

2017-10-05 22:58 UTC, merged