Code Consistency: luminosity --> light_range
tgstation/tgstation pull request #31355
Opened 2017-10-05 20:28 UTC by Firecage

Well, the title basically says what this PR does. Change the remaining luminosity vars in applicable code to light_range.

2017-10-06 13:50 UTC, ma44 commented
>branch name

2017-10-06 14:19 UTC, Cyberboss requested changes

2017-10-06 14:19 UTC, Cyberboss commented on code/game/machinery/lightswitch.dm
> +	//	light_range = 1
just remove the line

2017-10-06 14:19 UTC, Cyberboss commented on code/modules/power/apc.dm
> +//	light_range = 1
^

2017-10-06 14:19 UTC, Cyberboss commented on code/modules/power/singularity/singularity.dm
> +		light_range = 10
You need to use set_light here instead

2017-10-07 20:11 UTC, Firecage commented
Sure, will make the changes

2017-10-10 08:26 UTC, optimumtact commented
no RUSH

2017-10-12 20:23 UTC, Firecage commented
Oranges. Can you perhaps unclose this? Will finish it up tomorrow. I actually forgot about this PR.

2017-10-15 11:04 UTC, Firecage commented
Ahwell then.

2017-10-17 14:01 UTC, AnturK commented
@Firecage please

2017-10-18 07:15 UTC, Firecage commented
I...didn't even see anyone reopen this to be honest. Since after oranges ignored me....I gave up and didn't get any notifications...

2017-10-18 07:16 UTC, optimumtact commented
I didn't get your notification or ignored it, did you try to reach me in IRC I can be much more easily reached with a pm there.

2017-10-18 07:21 UTC, Firecage commented
Alright @optimumtact , PR is finally doneso.

2017-10-19 03:06 UTC, ShizCalev submitted a review, later dismissed

2017-10-19 03:06 UTC, ShizCalev commented on code/modules/power/singularity/singularity.dm
> +		set_light = 10
set_light(10)

2017-10-20 16:16 UTC, Cyberboss commented
@Firecage !!!

2017-10-21 06:37 UTC, optimumtact commented
fool me once, shame on me

fool me twice, shame on me

2017-10-21 18:47 UTC, Firecage commented
Well sorry guys. The past two weeks I have been dead tired by the time it gets night, which is what the time is here now. And otherwise in general been busy the entire day.

2017-10-22 00:17 UTC, Cyberboss approved these changes

2017-10-22 05:06 UTC, merged