Prioritizes the PDA pen as a traitor uplink location when the pen is selected
tgstation/tgstation pull request #31434
Opened 2017-10-07 23:38 UTC by vuonojenmustaturska

Fixes #31402 i think

> < Naksu> Daturix: could you confirm that the traitor panel says Uplink: . when the pocket protector thing happens
< Naksu> or is that a separate bug
< Daturix> Naksu yup <

[Changelogs]:

:cl: Naksu
change: Traitor pen uplinks now preferentially spawn in the PDA pen, and not in a pocket protector full of pens that no-one checks.
/:cl:

[why]:
Requested by Daturix on coderbus, also seems legit

2017-10-07 23:40 UTC, Cyberboss requested changes

2017-10-07 23:40 UTC, Cyberboss commented on code/datums/mind.dm
> +		P = locate() in PDA.contents
locate() in PDA

2017-10-07 23:56 UTC, Cyberboss approved these changes

2017-10-08 20:24 UTC, AlchemicalGitHub commented
This seems dumb, I mean, I don't understand the point of having this for the pure fact of players negligence.

2017-10-09 00:09 UTC, merged