Fix a bug in the new lobby music system
tgstation/tgstation pull request #31477
Opened 2017-10-08 23:02 UTC by JamieH

Oopsie. @Cyberboss

2017-10-08 23:12 UTC, Cyberboss requested changes

2017-10-08 23:12 UTC, Cyberboss commented on code/controllers/subsystem/ticker.dm
> +		login_music = "config/title_music/music/" + pick(music)
login_music = "config/title_music/music/[pick(music)]"

2017-10-08 23:13 UTC, Cyberboss submitted a review, later dismissed

2017-10-09 00:03 UTC, optimumtact commented
bruuh

2017-10-09 00:03 UTC, optimumtact commented
look at this dude

2017-10-10 18:13 UTC, Cyberboss approved these changes

2017-10-10 18:13 UTC, merged