fixes aliens being unable to stun
tgstation/tgstation pull request #31491
Opened 2017-10-09 05:19 UTC by kevinz000

lmao that round was fun

2017-10-09 05:55 UTC, Cyberboss requested changes

2017-10-09 05:55 UTC, Cyberboss commented on code/modules/mob/living/carbon/human/human_defense.dm
> +			if(istype(I) && dropItemToGround(I))
if(I && dropItemToGround(I))

2017-10-09 06:26 UTC, ShizCalev commented
Fixes #31488

2017-10-09 06:27 UTC, ShizCalev commented
Replicate it here too please;
https://github.com/kevinz000/-tg-station/blob/9f12b782f7464a37ae1401a79f45739f798983fc/code/modules/mob/living/carbon/human/human_defense.dm#L207

2017-10-10 17:39 UTC, Cyberboss requested changes
Do what Shiz said

2017-10-11 15:23 UTC, Cyberboss approved these changes

2017-10-11 15:24 UTC, merged