Tweaks syndicate infiltrator and box/meta whiteships.
tgstation/tgstation pull request #31514
Opened 2017-10-09 21:45 UTC by WJohn

Box and metastation whiteships now no longer have any knockdown when you travel, but also spend 250 ticks in hyperspace instead of 10. This, coupled with not needing to be in a chair to avoid the annoying milisecond long knockdown, incentivizes people to walk around their ship and maybe fix it up or do something in it or bring some friends to go talk to when you're out adventuring all over the place.

The syndie infiltrator had its windows slightly changed to look prettier, and the northwest docking port of boxstation now works again. (The port had no width value put in).
![](https://i.imgur.com/QXyF9H0.png)

:cl: WJohnston
tweak: Due to age, the abandoned ship's engines are now considerably slower when bringing it place to place. This does however mean that the ship now has a more gradual takeoff, with no sudden jolt to knock you off your feet.
/:cl:

2017-10-09 21:56 UTC, AnonymousNow commented
That's a considerable length of time, isn't it? Does this happen for jumps within the same station Z-level?

2017-10-09 22:00 UTC, WJohn commented
It's an increase from 10 seconds to 25 seconds, so not that bad. Metastation's whiteship has quite a lot to look around in it. I wanted it to feel more like you're on a journey from place to place, which is why I removed the knockdown so you can walk around while it's travelling without buckling yourself down the entire time in the cockpit. Less like a magic box that way.

2017-10-09 22:01 UTC, ShizCalev commented on _maps/map_files/generic/CentCom.dmm
> +"OVERFLOW" = (
welp

2017-10-09 22:08 UTC, AnonymousNow commented
If ticks are equal to seconds, more or less, then your original post says that you're upping the time to 4 1/6 minutes, not 25 seconds.

2017-10-09 22:12 UTC, ShizCalev commented
@AnonymousNow callTime is in deciseconds.

2017-10-09 22:23 UTC, AnonymousNow commented
So it's the ten that represents one second that's throwing me off.

2017-10-09 22:32 UTC, WJohn commented
Apparently there's still an overflow despite me reverting and then changing more tiles when I try again.

2017-10-09 23:01 UTC, ShizCalev requested changes

2017-10-09 23:01 UTC, ShizCalev commented on _maps/shuttles/whiteship_box.dmm
> +	timid = null;
This will break the template version. 
timid = 1 please.

2017-10-09 23:01 UTC, ShizCalev commented on _maps/shuttles/whiteship_meta.dmm
>  	preferred_direction = 4;
add timid = 1; here if you wouldn't mind.

2017-10-09 23:01 UTC, ShizCalev commented on _maps/shuttles/whiteship_box.dmm
> +/obj/docking_port/stationary{
iirc doesn't having two docking_port modules on a template shuttle prevent it from loading?

2017-10-09 23:01 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	 dheight = 9;
Extra space?

2017-10-10 00:22 UTC, WJohn commented
Gonna remake this PR one sec.

2017-10-10 00:22 UTC, closed without merging