Makes varediting pneumatic cannon easier and makes the code less snowflake-y
tgstation/tgstation pull request #31752
Opened 2017-10-15 08:57 UTC by kevinz000

2017-10-15 09:36 UTC, optimumtact commented
stop adding vars to shit, it increases compile and access time you dunderheaded buffoon

2017-10-15 10:47 UTC, praisenarsie commented
yeah because i want kevinz to spawn super pneumatic cannons on a rev round

2017-10-23 13:15 UTC, AnturK requested changes

2017-10-23 13:15 UTC, AnturK commented on code/game/objects/items/pneumaticCannon.dm
> +	allowed_typecache = typecacheof(/obj/item/reagent_containers/food/snacks/pie)
Make this static for the subtype and assign it.

2017-10-25 15:00 UTC, AnturK requested changes

2017-10-25 15:00 UTC, AnturK commented on code/game/objects/items/pneumaticCannon.dm
> +		fill_with_type(/obj/item/reagent_containers/food/snacks/pie/cream, charge_amount)
Shouldn't this be charge type

2017-10-29 12:03 UTC, AnturK commented
@kevinz000

2017-10-29 16:40 UTC, kevinz000 commented
One second

2017-10-30 19:56 UTC, Cyberboss requested changes

2017-10-30 19:56 UTC, Cyberboss commented on code/game/objects/items/pneumaticCannon.dm
> +			to_chat(user, "<span class='warning'>\The [src] won't fit [I]!</span>")
Remove \The

2017-10-30 19:56 UTC, Cyberboss commented on code/game/objects/items/pneumaticCannon.dm
> +			to_chat(user, "<span class='warning'>\The [src] won't fit [I]!</span>")
check your grammar

2017-10-30 19:56 UTC, Cyberboss commented on code/game/objects/items/pneumaticCannon.dm
> +	if(!isnull(allowed_typecache) && !allowed_typecache[I.type])
replace if with is_type_in_typecache(I, allowed_typecache)

2017-10-31 14:13 UTC, merged