Tweaks to GC_FAILURE_HARD_LOOKUP
tgstation/tgstation pull request #31921
Opened 2017-10-19 20:49 UTC by vuonojenmustaturska

Fixes #31910

Doesn't make it useful yet, since it takes days to run even with the simplest of settings. But at least it doesn't crash anymore.

[Changelogs]: 

:cl: Naksu
code: find_references() now technically works, however takes days to run. Doesn't crash though.
/:cl:

2017-10-19 21:00 UTC, Cyberboss requested changes

2017-10-19 21:00 UTC, Cyberboss commented on code/controllers/subsystem/garbage.dm
> +			if(!A.loc || A.loc.z != 2)
use the z defines

2017-10-19 21:00 UTC, Cyberboss commented on code/controllers/subsystem/garbage.dm
> +			testing("World search progress: [counter] / [maxlen]")
don't do this if GC_FAILURE_HARDER_LOOKUP is defined, it'll just slow it down

2017-10-19 22:19 UTC, vuonojenmustaturska commented
With the latest changes, the simplest lookup will now finish in the same day! Still completely useless.

2017-10-20 13:50 UTC, kevinz000 commented
at this point just call it GC_FAILED_LETS_LOCKUP :^)

2017-10-22 00:00 UTC, Cyberboss commented
Is this ready?

2017-10-22 01:18 UTC, vuonojenmustaturska commented
not really, MSO has better things cooking, and i have a private fucking around branch for some more stuff

2017-10-27 22:34 UTC, Cyberboss commented
MSO fixed it

2017-10-27 22:34 UTC, closed without merging