Removes mob.lastattacked and replaces lastattacker with a string
tgstation/tgstation pull request #31981
Opened 2017-10-21 16:55 UTC by vuonojenmustaturska

We shouldn't leave mob references dangling just so we can gamble on one of them still existing at roundend for stats generation.

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Naksu
code: Removed dangling mob references to last attacker/attacked
/:cl:

[why]: 
These cause mob harddels and all the death reporting subsystem needs is a name and a ckey.

2017-10-21 18:19 UTC, AnturK commented
You could just store text ref ?

2017-10-22 11:15 UTC, vuonojenmustaturska commented
@AnturK the last attacked mob might not exist by the time the death is reported, particularly in the case of mobs that qdel on death or are butcherable.

2017-10-22 15:50 UTC, Cyberboss requested changes

2017-10-22 15:50 UTC, Cyberboss commented on code/_onclick/item_attack.dm
> +	M.lastattackerckey = user.ckey
This should be changed back to key unless @nfreader is ok with this

2017-10-22 15:50 UTC, Cyberboss commented on code/game/gamemodes/miniantags/abduction/abduction_gear.dm
> +	L.lastattackerckey = user.ckey
ditto

2017-10-22 15:50 UTC, Cyberboss commented on code/game/objects/items/stunbaton.dm
> +		L.lastattackerckey = user.ckey
ditto

2017-10-22 15:50 UTC, Cyberboss commented on code/game/objects/structures/manned_turret.dm
> +	M.lastattackerckey = user.ckey
ditto

2017-10-22 16:21 UTC, nfreader commented
Ckey is always better.

2017-10-22 16:28 UTC, Cyberboss approved these changes

2017-10-22 16:28 UTC, merged