fixes AIs being able to teleport the id card console inserted cards to their core
tgstation/tgstation pull request #32003
Opened 2017-10-22 13:53 UTC by kevinz000

2017-10-22 13:55 UTC, praisenarsie commented
[s] ?

2017-10-22 14:10 UTC, MoreRobustThanYou commented
vroom

2017-10-22 15:38 UTC, Cyberboss approved these changes

2017-10-22 16:00 UTC, ShizCalev requested changes
Fix TK teleporting IDs too please.

2017-10-22 16:00 UTC, ShizCalev commented on code/game/machinery/computer/card.dm
> +		if(!isAI(user))
`if(!issilicon(user) && Adjacent(user))`

2017-10-22 16:00 UTC, ShizCalev commented on code/game/machinery/computer/card.dm
>  	else //switching the ID with the one you're holding
Add this below the else & do the same w/ the else for eject_id_modify
```
if(issilicon(user) || !Adjacent(user))
	return
```

2017-10-22 16:00 UTC, ShizCalev commented on code/game/machinery/computer/card.dm
> +		if(!isAI(user))
`if(!issilicon(user) && Adjacent(user))`

2017-10-23 11:40 UTC, jughu commented
Feature

2017-10-23 12:10 UTC, ShizCalev approved these changes

2017-10-23 13:58 UTC, merged