Adds some new grindables to the grinder
tgstation/tgstation pull request #32107
Opened 2017-10-25 20:24 UTC by Anonmare

[Changelogs]: Adds several new items that the grinder can grind, for the aspiring ghetto chemist

:cl: 
add: Adds new grindables
/:cl:

[why]: I'm currently looking into adding ghetto chemistry for aspiring assistants (both loyal and disloyal) to make use of in their endeavours, this PR adds new things that can be scavenged and ground up for those without chemistry machines. If anyone wants to make any suggestions or give pointers, I'd be more than happy to hear them

2017-10-25 20:25 UTC, PKPenguin321 commented
Super cool

2017-10-25 20:25 UTC, RemieRichards commented
At this point all these lists should be on the individual types, not like this anymore.

2017-10-25 20:30 UTC, nicbn commented
Cable is not made of copper is it?

2017-10-25 20:31 UTC, Anonmare commented
@nicbn Technically no as far as the lathe is concerned but I'm willing to take some liberties with a few things that would be "reasonable"

2017-10-25 20:48 UTC, DoctoreMad commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +
Nice space

2017-10-25 20:49 UTC, DoctoreMad commented
Specify changelog a bit, maybe?

add: More items can now be used in a all-in-one grinder to get ghetto chemistry components.

2017-10-25 20:52 UTC, Anonmare commented
@docotremad I'm working on adding a mortar and pestle craftable so that you don't have to rely on the all-in-one grinder only. Also working on making a craftable electrolyzer and a primitive chemmaster that can only separate chemicals

2017-10-25 20:53 UTC, Anonmare commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +
Oh darn I thought I got that already

2017-10-25 23:05 UTC, DoctoreMad commented
Basically /vg/station ghetto chem then?

2017-10-25 23:16 UTC, Anonmare commented
I guess so, perhaps it might be worth looking into how they've managed it  and seeing if I can learn something

2017-10-25 23:32 UTC, Anonmare commented
Also if anyone has any ideas for anything that would, reasonably, contain mercury and/or radium I'd like to hear it. Preferably something common and easy to get

2017-10-26 01:49 UTC, Bawhoppen commented
Another ghetto chem tip: You can get fluorine from bottled water

2017-10-26 02:56 UTC, YakumoChen commented
@anonmare put mercury in analyzers, since they measure temperature. Maybe radium in medical analyzers or Geiger counters since they measure radiation? I feel like this somehow makes sense.

2017-10-26 05:49 UTC, bgobandit commented
soap => lye

2017-10-26 06:35 UTC, Bawhoppen commented
Issue is, some of these only take metal to make them, thus creating infinite chems from nothing.

Solution: Add chem requirements to autolathe

2017-10-26 07:34 UTC, ACCount12 commented
Not an issue, chemistry has a much easier way to create infinite chems from nothing. Sure, the dispenser may run out of power, but your average Assistant McChemist will run out of patience even faster.

2017-10-26 07:35 UTC, ACCount12 commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +			/obj/structure/cable = list ("copper" = 5),
Not going to work. This is object cable, not item cable.

2017-10-26 07:44 UTC, Bawhoppen commented
Just because of balance not being involved, doesn't mean it's not a huge consistency issue

2017-10-26 07:47 UTC, ACCount12 commented
what is consistency

2017-10-26 07:54 UTC, Bawhoppen commented
It being consistent in having the same materials that go in, come out

2017-10-26 08:49 UTC, YakumoChen commented
adding chem requirements to autolathe would both ruin the point of trying to avoid using chemistry and would make most things unprintable because chemistry sure as hell isn't going to provide chems all day for it

2017-10-26 09:10 UTC, Bawhoppen commented
We need less watered down crap anyways actually

2017-10-26 13:29 UTC, Anonmare commented
@YakumoChen Don't know how I feel about geiger counters, will have to come back to that suggestion. Gas analyzers will now have a small amount of mercury in them, since Nanotrasen is cheap enough to put dangerous chemicals in their commonly used equipment.

2017-10-26 13:52 UTC, pantherpusher commented
What if you got radium from glowsticks

2017-10-26 14:25 UTC, davethwave commented
Radium in dna injectors then?

2017-10-26 14:27 UTC, davethwave commented
Considering they change the dna of a human momentarily they use controlled radiation and thus radium

2017-10-26 15:45 UTC, davethwave commented
lighters and stuff for welder fuel, the more fancy it is the more welding fuel it has in it. Flare for phosphorus. Power cell/capacitor for iodine and sulfuric acid. Welding tool for iron/welding fuel(depends on how full the welding tool is). Night vision goggles as stuff like it can give uranium or some other precious metals like gold or silver as they are created with them. Monkey cubes for blood/nutriment perhaps?

2017-10-26 17:20 UTC, Supermichael777 commented
welder-fuel is common if cargo aren't being thieving assholes.

so yeah an alt source would be nice

2017-10-26 21:18 UTC, Anonmare commented
Hmm, I don't entirely know how to have the grinder account for the welding tool's fuel capacity but lighters are easily doable. I'd prefer to keep this list to commonly found/unrestricted station items but I'll try adding some rarer items as well

2017-10-26 21:30 UTC, davethwave commented
Also how about grinding up cigarettes for nicotine and some minor drugs, antag tokens may contain a few units of dangerous chems in them like cyanide and the like, bruisepacks will give styptic powder when ground up, and ointment will give silver sulfadiazine when ground up.

2017-10-26 21:37 UTC, Anonmare commented
Hmm, I already did cigarettes but I can go for bruise packs and ointment at the very least. Ideally, I want the most common elements of chemistry to be acquirable by assistants in some capacity.

2017-10-26 21:51 UTC, davethwave commented
So what are you missing on the common ingredients list then?

2017-10-26 21:55 UTC, Anonmare commented
I've covered most of my bases, carbon I'm not overly happy with but I can't think of something that would be a pure source of it

2017-10-26 22:11 UTC, davethwave commented
How about the standard power cells? For instance you can get carbon rods out of old car batteries I believe.

2017-10-26 22:21 UTC, Jordie0608 requested changes

2017-10-26 22:21 UTC, Jordie0608 commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +			/obj/item/clothing/mask/cigarette = list()
You need the extra `)` from the line above to be here.

`/obj/item/toy/crayon = list(),`
`/obj/item/clothing/mask/cigarette = list())`

2017-10-27 00:02 UTC, Jordie0608 approved these changes

2017-10-27 15:08 UTC, davethwave commented
how about grinding electronics and boards for silicon? Also another way to get carbon via real life chems is sulfuric acid and sucrose. https://www.youtube.com/watch?v=XGLuZhBWLrQ

2017-10-27 15:10 UTC, davethwave commented
Also supposedly when sugar gets hot enough the sugar turns into carbon as well. https://www.youtube.com/watch?v=9d8oaBHaTwY

2017-10-27 16:26 UTC, Anonmare commented
Already get electronics and computer boards, grinding a circuitboard will give you 0.5u of sulphuric acid as well (This is for balance so you can't produce more acid than you use, even with bluespace parts). I'll be working on adding some new things for ghetto chemistry, like electrolysis to breakdown reagents into their constituents but that's outside of this PR for now

2017-10-27 21:36 UTC, naltronix commented
FUCK YOU BEAT ME TO IT
FUCKING HELL DAMNIT REEE

2017-10-27 22:29 UTC, merged