Fix improper diagonal corners on the Raven shuttle
tgstation/tgstation pull request #32182
Opened 2017-10-28 10:32 UTC by SpaceManiac

🆑
fix: The walls and windows of the CentCom Raven Battlecruiser now smooth properly.
/🆑

It hadn't been updated for the plastitanium changes and the corners are a bit wonky. This patch adds nodiagonal walls where needed and replaces the ordinary windows with the new plastitanium ones to complete the theme.

All the deleted lines are just duplicates clogging up the file.

New appearance:
![image](https://user-images.githubusercontent.com/222630/32133482-7e3f6afa-bb8d-11e7-818f-3344bb5b8163.png)

2017-10-28 13:14 UTC, Bawhoppen commented
Be the change you want to see in the world

2017-10-28 19:06 UTC, Shadowflame909 commented
Centcomm Raven Battle Cruiser with code red ert on it, vs Nuclear operative ship with nukies on it when???

2017-10-29 16:01 UTC, ShizCalev requested changes
Did you run map merge on this? Why are a ton of keys being deleted leaving the dictionary fragmented?

2017-10-29 20:40 UTC, SpaceManiac commented
I've been working on an updated mapmerge that's less cumbersome to use and supports multi-Z, it has this slightly spammy side-effect of deleting keys that are the same as each other, like the 40 or so keys in this template that are the exact same floor turf + shuttle area. I want to PR that soon to get some proper feedback, in the meantime I can either undo all those deletions or defrag the dictionary, whichever you want.

2017-10-31 20:13 UTC, optimumtact commented
Given that this map is rarely touched, I'm not worried about conflicts on it

2017-10-31 20:13 UTC, merged