Deterministic output slots for smartfridges
tgstation/tgstation pull request #32225
Opened 2017-10-29 17:59 UTC by vuonojenmustaturska

Simply put, when you take items out of a smartfridge, they are output in one of the output slots in a 3x3 grid inside the fridge tile in a deterministic fashion, so that a 9u pill of cyanide you might use to escape an assignment in security will always pop out at the same slot. This hopefully reduces the right-click menu usage a fair bit.

Looks kinda like this:

![image](https://user-images.githubusercontent.com/20017308/32146648-32d3ce06-bce3-11e7-8e60-557b43d7eb13.png)

[Changelogs]: 

:cl: Naksu
tweak: Smartfridges now output items in a deterministic 3x3 grid rather than in a huge pile in the middle of the tile.
/:cl:

2017-10-29 18:41 UTC, MoreRobustThanYou commented
YOU ARE A GOD, THANK YOU

2017-10-29 19:49 UTC, psykzz commented
Can we make this a proc on all vending type machines?

2017-10-29 20:06 UTC, vuonojenmustaturska commented
Yeah, I'm already working on an improved commit

2017-10-29 22:10 UTC, vuonojenmustaturska commented
Red for beaker, green for pill bottles, condensed 3x3 for others. Now the beaker won't be buried under a pile of crap.

![image](https://user-images.githubusercontent.com/20017308/32148963-8fae8db4-bd06-11e7-9f47-c09df5d466d3.png)

2017-10-29 22:27 UTC, vuonojenmustaturska commented
![image](https://user-images.githubusercontent.com/20017308/32149151-016ec39a-bd09-11e7-8040-6291aa8891c1.png)

made pill bottles with contents pop out to the left and empty ones to the right, also made the bottles have a bit more space between them

2017-10-30 00:16 UTC, Cyberboss requested changes

2017-10-30 00:16 UTC, Cyberboss commented on code/game/machinery/_machinery.dm
> +		. += hex2num(copytext(md5,i,i+1))
Add a compile error if DM_VERSION >= 512 so we can use string iteration eventually

2017-10-30 19:34 UTC, Cyberboss approved these changes

2017-10-30 19:34 UTC, merged

2017-10-30 21:51 UTC, 81Naoki commented
That's beautiful! I have ideas for three more machines:
- Smart slime fridge and slime processor (/obj/machinery/smartfridge/extract/preloaded // machinery/processor): These output one homogenous pile of slime extracts that are all exactly the same size.
- Plant DNA manip (/obj/machinery/plantgenes): This machine outputs seed packages and plant disks on top of each other.

2017-11-04 00:03 UTC, Supermichael777 commented
Now nerf chemists

2017-11-08 17:01 UTC, 81Denton commented
Forgot to mention the med vending machines you find in medbay. They have 10+ different items that get output as a pile.