Allows cyborgs to perform limb augmentation
tgstation/tgstation pull request #32233
Opened 2017-10-29 20:23 UTC by swindly

:cl: Swindly
add: Organ storage bags can be used to perform limb augmentation.
/:cl:

Fixes https://github.com/tgstation/tgstation/issues/29318

2017-11-01 00:52 UTC, ExcessiveUseOfCobblestone commented
thanks for this

2017-11-03 02:43 UTC, ninjanomnom requested changes

2017-11-03 02:43 UTC, ninjanomnom commented on code/modules/surgery/limb_augmentation.dm
> +			tool.desc = "A container for holding body parts."
use `initial()` here to get the original values

2017-11-03 03:21 UTC, ninjanomnom approved these changes

2017-11-03 03:21 UTC, merged