Improves BoxStation supermatter
tgstation/tgstation pull request #32254
Opened 2017-10-30 11:59 UTC by ACCount12

* Emitter room is expanded. New reflectors allow some crazy emitter setups, and the old room was not large enough to be a playground.
* New pipe is added: Output to Waste. It allows you to redirect supermatter loop output into the scrubbers system by opening one valve and closing another. Useful if you don't want your gas to be wasted.

Before:
![default](https://user-images.githubusercontent.com/3888532/32169719-bb8f4096-bd82-11e7-8eb6-597538bdcbf8.png)

After:
![default](https://user-images.githubusercontent.com/3888532/32169740-cb3fce70-bd82-11e7-981f-9cb60ecd2c23.png)

2017-10-30 14:47 UTC, ShizCalev requested changes

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	open = 0
Why are you editing a var to do this when you used valve/open

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +/obj/item/stack/sheet/metal{
There should be a metal/fifty path too iirc

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	layer = 2.9
Layer edit?

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	layer = 2.9
Layer?

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	dir = 8;
Changing dir doesn't do anything for racks iirc

2017-10-30 14:47 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	dir = 8;
Dir

2017-10-30 20:51 UTC, ACCount12 commented
All fixed. I just copied objects from the map most of the time, looks like it was a bad idea.

2017-10-30 21:00 UTC, ACCount12 commented
I also removed dirs and layers from all the racks on the map, so this would not repeat.

2017-10-30 21:03 UTC, ShizCalev requested changes

2017-10-30 21:03 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	tag = "icon-dvalve_map (EAST)"
Dirty var

2017-10-30 21:03 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	icon_state = "dvalve_map";
Dirty var

2017-10-30 21:03 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	icon_state = "dvalve_map";
Also is there a /open path for this?

2017-10-30 21:04 UTC, ACCount12 commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	icon_state = "dvalve_map";
nope

2017-10-30 21:35 UTC, ACCount12 commented
"Dirty vars" removed, hope this is the last time.

2017-10-31 00:38 UTC, ShizCalev approved these changes

2017-10-31 13:06 UTC, merged