Fixes hand tele losing ranged portal-dispel function
tgstation/tgstation pull request #32408
Opened 2017-11-04 05:45 UTC by kevinz000

IM SORRY LAST TIME I HAVE TO FIX THIS I MOSTLY PROMISE

2017-11-04 05:45 UTC, Hatterhat commented
@kevinz000 fix ur shit reatard

2017-11-04 15:07 UTC, ShizCalev commented
web edit?

2017-11-05 10:34 UTC, ninjanomnom requested changes

2017-11-05 10:34 UTC, ninjanomnom commented on code/game/objects/items/teleportation.dm
> +	return try_dispel_portal(target, user)? FALSE : ..()
for the sake of clarity just do an if statement here

2017-11-06 20:42 UTC, merged