Cleans up turf decal and lets it be applied to atoms
tgstation/tgstation pull request #32462
Opened 2017-11-06 07:12 UTC by ninjanomnom

I forgot to allow dupes and made it use a mutable appearance to store the image instead of recreating it every time.

2017-11-06 07:20 UTC, ShizCalev commented
Oh lovely, does this fix the rumtime happening with remove_decal?

2017-11-06 07:23 UTC, ninjanomnom commented
Not directly, that's a problem with how components were changed in general. They're supposed to never be null in destroy but we're at a loss with how to do that and allow components to destroy themselves when applied incorrectly.

2017-11-06 07:25 UTC, ninjanomnom commented
#32351 is the actual fix for that

2017-11-07 16:02 UTC, Cyberboss requested changes

2017-11-07 16:02 UTC, Cyberboss commented on code/datums/components/decal.dm
> +	if(!istype(parent, /atom) || !_icon || !_icon_state)
i think we have isatom

2017-11-07 16:02 UTC, Cyberboss commented on code/datums/components/decal.dm
> +		CRASH("A turf decal was applied incorrectly to [parent]: icon:[_icon ? _icon : "none"] icon_state:[_icon_state ? _icon_state : "none"]")
parent.type

2017-11-07 16:02 UTC, Cyberboss commented on code/datums/components/decal.dm
> +	master.add_overlay(pic)
use TRUE because it's a priority overlay

2017-11-07 16:02 UTC, Cyberboss commented on code/datums/components/decal.dm
> +	master.cut_overlay(pic)
ditto

2017-11-07 18:57 UTC, Cyberboss approved these changes

2017-11-07 18:57 UTC, merged