Generalizes some reagent heating
tgstation/tgstation pull request #32461
Opened 2017-11-06 05:25 UTC by swindly

:cl: Swindly
fix: Fixed hot items and fire heating reagent containers and floor spills to temperatures higher than their heat source.
fix: Sprays can now be heated with hot items.
tweak: The heating of reagent containers and floor spills by hot items, fire, and microwaves now scales linearly with the difference between the reagent holder's temperature and the heat source's temperature instead of constantly.
tweak: The body temperature of a mob with reagents is affected by the temperature of the mob's reagents.
tweak: Reagent containers can now be heated by hot air.
/:cl:

Fixes https://github.com/tgstation/tgstation/issues/29557 and https://github.com/tgstation/tgstation/issues/32372
 
Added expose_temperature proc to be used for heating reagents in a consistent manner instead of different reagent holders being heated differently. It heats linearly similar to the way the chem heater works.
Added temperature_expose for reagent containers so that they can be heated by the environment for realism or something.
Metabolizing reagents causes the temperatures of the reagents and the mob to average with each other instead of always being the temperature of the mob. This is consistent with the expected behavior of reagents and reactions that change the reagent holder's temperature (i.e. cryostylane synthesis and pyrosium synthesis) that currently do nothing.

2017-11-06 06:00 UTC, ACCount12 commented
Will heating the mob still heat up the reagents?

2017-11-06 15:25 UTC, swindly commented
Heating the mob still heats up the reagents.

2017-11-06 16:47 UTC, swindly commented
Changed metabolizing temperature change so that it quickly changes to meet the body temperature. Changing the body temperature towards the reagent temperature allowed high reagent volumes to prevent the body temperature from reaching extremes.

2017-11-08 11:23 UTC, AnturK requested changes

2017-11-08 11:23 UTC, AnturK commented on code/modules/reagents/chemistry/holder.dm
>  		handle_reactions()
Not needed anymore ?

2017-11-08 11:23 UTC, AnturK commented on code/modules/reagents/reagent_containers.dm
>  		reagents.handle_reactions()
Same here ?

2017-11-08 17:04 UTC, ninjanomnom approved these changes

2017-11-08 17:04 UTC, merged