Ensures sentienced animals know how to speak Common
tgstation/tgstation pull request #32518
Opened 2017-11-08 01:11 UTC by PKPenguin321

Fixes https://github.com/tgstation/tgstation/issues/32499

2017-11-08 01:20 UTC, imtakingabreakdontatme submitted a review, later dismissed
It should grant the languages of the person using the sentience potion

2017-11-08 01:41 UTC, KorPhaeron commented
Probably. I don't know how you'd choose the correct one to grant otherwise.

2017-11-08 01:47 UTC, PKPenguin321 commented
Seems exploitable with the librarian to me, are you sure?

2017-11-08 05:16 UTC, KorPhaeron commented
I guess that is a fair concern but it'd also be weird if we ever had something that couldn't speak common sentience potion a mob

2017-11-08 05:42 UTC, PKPenguin321 commented
I guess if you insist
I'll touch it up either tomorrow or the day after

2017-11-08 20:07 UTC, PKPenguin321 commented
Still seems weird for edge cases to me, but I'm just going to do what Kor said.

2017-11-08 20:14 UTC, PKPenguin321 commented
That oughtta do it

2017-11-09 09:30 UTC, RemieRichards commented on code/modules/research/xenobiology/xenobiology.dm
> +		for(var/ld in GLOB.all_languages)
```SM.copy_known_languages_from(user, TRUE)```

no, I'm not kidding, this proc exists.

2017-11-09 15:03 UTC, Cyberboss requested changes
Yeah use the proc @RemieRichards said

2017-11-09 17:08 UTC, merged