Adds icons for items with randomization
tgstation/tgstation pull request #32523
Opened 2017-11-08 07:14 UTC by ShizCalev

Adds icons for items that have randomized features (ie change colors, subtypes, ect) when they spawn so they are more easily distinguished from normal versions in DM.

These are not visible ingame.

Also fixes invisible engineer scanners and headphones in DM.

2017-11-08 16:23 UTC, Bawhoppen commented
The jumpsuit one looks kind of like the rainbow jumpsuit

2017-11-09 00:35 UTC, Partheo commented
Why only add rainbow to some things and question marks to others? Just stick with a standard- I suggest a question mark for every random item. Rainbows are pretty, but they don't matter because they won't show up in game.

2017-11-09 01:45 UTC, ShizCalev commented
Rainbows were for things that only change color, question marks were for things that change attributes beyond color.

2017-11-09 02:27 UTC, Partheo commented
Alright, well at least you did have some standard, which is good. But yeah, questions marks on everything would be good.

2017-11-09 15:01 UTC, Cyberboss requested changes

2017-11-09 15:01 UTC, Cyberboss commented on code/game/objects/items/devices/flashlight.dm
> +	new T(get_turf(src))
use loc for transformations

2017-11-10 05:22 UTC, Cyberboss approved these changes

2017-11-10 05:23 UTC, merged