adjusted default internet song volume to 25
tgstation/tgstation pull request #32585
Opened 2017-11-10 04:57 UTC by Qbopper

:cl: Qbopper
tweak: The default internet sound volume was changed from 100 to 25. Stop complaining in OOC about your ears!
/:cl:

literally any time any admin plays anything there's 2-3 people who say "MY EARS" because the default volume is TOO LOUD and they don't change it

i tested this and it actually worked so if it doesn't work i'm gonna be mad

2017-11-10 05:00 UTC, ike709 commented
![image](https://user-images.githubusercontent.com/5714543/32643557-d168e9f4-c5a1-11e7-8f49-d3fdcfd75cab.png)

2017-11-10 05:09 UTC, WJohn commented
It'd be nice if these had a volume control panel and an optional OOC notification message when playing these. Would fix #32321

2017-11-10 07:16 UTC, Qbopper commented
yeah, but this was a low effort PR I could get made to stop people complaining quite as much

most admins (on sybil at least) tend to use internet sounds so we hear a lot more complaints about the volume there

2017-11-10 08:55 UTC, ShizCalev commented
#31575

2017-11-10 09:01 UTC, AnonymousNow commented
>Turn down system/SS13 client sound
>Surely you'll still be able to hear the rest of the game properly.

Where are these memes coming from?

2017-11-10 10:35 UTC, Dorsisdwarf commented
Ike missing the point
this pr isnt "admin memes are too loud reee" its
"some players are idiots who dont bother to use the ingame volume control then bitch every time one is played so lets just nip that in the bud"

2017-11-10 17:20 UTC, Qbopper commented
@ShizCalev i don't know if i'd close that issue because it doesn't fix the problem of oggs vs internet sounds being wildly different

it's just what doris said, the idea is to get people to not complain about internet sounds as much, and if it's too quiet then it's not hard for them to turn it up

also sometimes my setting resets to the default so when an admin plays a song my settings is back to 100 so i know how it feels

2017-11-10 18:23 UTC, JJRcop commented
This is needed in order to function properly: Qbopper#1

2017-11-10 18:25 UTC, JJRcop commented
Also for anyone curious I just posted my reasoning for not giving admins volume control over internet midis here: https://github.com/tgstation/tgstation/issues/31575#issuecomment-343548065

>The reason I don't want admins to be able to control the volume for internet midis, is that if they get it wrong, players will have to fiddle with their volume to hear it properly, which will affect the next music. Say an admin plays an internet midi quiet on purpose, so players turn the music slider up, then play a really loud one at full volume, which doesn't feel great.
I encourage you to pick music/audio that isn't too loud, so that the player's appropriate audio settings will work for them. If a track isn't mixed properly, then that's a bad track to play.

2017-11-10 20:39 UTC, Qbopper commented
merged pr + gave @JJRcop credit in the changelog, thanks man

I wasn't sure if there would be anything else I needed to change, it worked in my testing for some reason but whatever lol

2017-11-10 21:10 UTC, BeeSting12 commented
I'd rather see it a bit higher, such as 50.

2017-11-10 21:16 UTC, Bawhoppen commented
no it's too loud even at this

2017-11-10 22:54 UTC, Qbopper commented
my system volume is at about 60-70 and I don't fuck with SS13 in volume mixer and 25 is the level at which it's reasonably loud for me so I put that

2017-11-12 00:37 UTC, ExcessiveUseOfCobblestone commented
> my system volume is at about 60-70 and I don't fuck with SS13 in volume mixer and 25 is the level at which it's reasonably loud for me so I put that
tfw volume on 26, admin sounds are on 8

2017-11-12 00:59 UTC, Cyberboss requested changes
Make it 50 instead

2017-11-12 03:25 UTC, Qbopper commented
@Cyberboss 

why

2017-11-12 03:28 UTC, Bawhoppen commented
50 is way too loud seriously

2017-11-12 03:29 UTC, Qbopper commented
it's also much less irritating for a user to have to turn music up than it is to have their eardrums melted

2017-11-12 04:31 UTC, PKPenguin321 commented
I roll at 💯 and its a-ok

2017-11-12 17:42 UTC, Qbopper commented
ok good for you except the point of the pr is that for the majority of users 100 is too loud and so is 50 you can still turn it up from the new default

i had no idea this pr would get so much opposition

i know pkp is memeing but cmon

2017-11-12 18:52 UTC, Cyberboss approved these changes

2017-11-12 18:52 UTC, merged

2017-11-12 19:11 UTC, Qbopper commented
oh

thanks

2017-11-13 18:28 UTC, PKPenguin321 commented
Not a meme I do keep it at full volume
Earlets when will they learn