Refactors uplinks to a component!
tgstation/tgstation pull request #32624
Opened 2017-11-11 02:38 UTC by kevinz000

2017-11-11 02:41 UTC, Qustinnus commented
shut up and take my GBP

2017-11-11 02:47 UTC, MoreRobustThanYou commented
do storage next

2017-11-11 14:29 UTC, GuyonBroadway commented
I bet uplinks are part of kevinz fetish.

2017-11-11 16:27 UTC, Cyberboss requested changes
This is too much of a "path change" port. Take a look at my old attempt and base it off that.#29785

2017-11-20 01:17 UTC, Cyberboss requested changes

2017-11-20 01:17 UTC, Cyberboss commented on code/datums/components/uplink.dm
> +	var/datum/game_mode/gamemode = null
remove = nulls

2017-11-20 01:17 UTC, Cyberboss commented on code/datums/uplink_items.dm
> +GLOBAL_LIST_EMPTY(uplink_items) // Global list so we only initialize this once.
Fix line endings

2017-11-22 21:16 UTC, merged