Corrects an initialize()
tgstation/tgstation pull request #32641
Opened 2017-11-11 20:35 UTC by praisenarsie

2017-11-11 22:12 UTC, Cyberboss requested changes

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/kitchen_machinery/juicer.dm
> +	. = ..()
This should be PopulateContents and just ..()

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/food_and_drinks/pizzabox.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/holodeck/items.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/mob/living/carbon/alien/organs.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
>  	reagents = new(50)
Add . = ..()

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/modular_computers/hardware/hard_drive.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/paperwork/filingcabinet.dm
>  	return ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/paperwork/pen.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/power/lighting.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/power/lighting.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/hydroponics/grown/random.dm
> +	. = ..()
. = ..() first

2017-11-11 22:12 UTC, Cyberboss commented on code/modules/hydroponics/grown/random.dm
> +	. = ..()
Also you need to port seeds to Initialize or this will break things

2017-11-12 10:34 UTC, praisenarsie commented on code/modules/games/cas.dm
> +/obj/item/toy/cards/deck/cas/Initialize()
does this need . = ..() first?

2017-11-12 18:09 UTC, ShizCalev commented on code/modules/games/cas.dm
> +/obj/item/toy/cards/deck/cas/Initialize()
Current location should be fine.

2017-11-13 17:36 UTC, Cyberboss approved these changes

2017-11-13 17:37 UTC, Cyberboss commented
Travis did finish, but it's being a shitter

2017-11-13 17:37 UTC, merged