Nuke Op Datumization
tgstation/tgstation pull request #32680
Opened 2017-11-12 17:57 UTC by AnturK

This one is half-done since the halfwin stuff needs be translated into objectives 

- [ ] Fully port nukeop win conditions/partial wins into objectives.
- [ ] Testing
- [ ] More testing

2017-11-21 16:15 UTC, JJRcop commented
Getting stale

2017-11-21 16:55 UTC, AnturK commented
I keep getting distracted with other stuff

2017-11-29 17:21 UTC, Cyberboss requested changes

2017-11-29 17:21 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +	to_chat(owner.current, "<B>In your hand you will find a special item capable of triggering a greater challenge for your team. Examine it carefully and consult with your fellow operatives before acti
just to_chat(owner, ... all of these

2017-11-29 17:21 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +	for(var/datum/mind/operative_mind in members)
typeless

2017-11-29 17:21 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +	return (S && (S.z == ZLEVEL_CENTCOM || S.z == ZLEVEL_TRANSIT)) ? 1 : 0
TRUE FALSE

2017-11-29 17:21 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +	for(var/datum/mind/syndicate in members)
ditto?

2017-11-29 17:21 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +		for(var/datum/component/uplink/H in GLOB.uplinks)
ditto

2017-11-29 17:21 UTC, Cyberboss commented
Testing seems fine

2017-11-29 17:23 UTC, Cyberboss commented on code/datums/antagonists/nukeop.dm
> +	return (S && (S.z == ZLEVEL_CENTCOM || S.z == ZLEVEL_TRANSIT)) ? 1 : 0
actually this, doesn't need a ternery at all

2017-11-29 18:52 UTC, Cyberboss approved these changes

2017-11-29 18:52 UTC, merged