Nerfs power regen on both variants of tesla relay circuits
tgstation/tgstation pull request #32782
Opened 2017-11-15 19:38 UTC by MMMiracles

:cl: MMMiracles
balance: Power regen on both the regular and large tesla relay circuits have to be nerfed to 50 and 300, from 150 and 1000.
/:cl:

[why]: It's more or less impossible to balance a circuit with heavy power usage when the tesla relay circuits exist as they currently do. They should exist as a way to passively regen power when not in use, not outright remove the need to worry about it.

2017-11-15 19:42 UTC, arsserpentarium commented
unnerf large relay.It's suitable only for machine.Machine have more stationary usage,so fast power regen isn't bad.

2017-11-15 19:58 UTC, ma44 commented
Description probably needs updating.

2017-11-15 19:59 UTC, Iamgoofball commented on code/modules/integrated_electronics/passive/power.dm
> +	power_amount = 300
this basically only really fits in large machinery anyways

2017-11-15 22:05 UTC, arsserpentarium commented
also solar cell for calculator generating 30 energy.maybe 50 is too small?

2017-11-15 23:37 UTC, ShizCalev requested changes

2017-11-15 23:37 UTC, ShizCalev commented on code/modules/integrated_electronics/passive/power.dm
> +	extended_desc = "The siphon generates 50W of energy, so long as an APC is in the same room, with a cell that has energy.  It will always drain \
50 W

Consistency.

2017-11-15 23:57 UTC, ShizCalev approved these changes

2017-11-16 04:53 UTC, PKPenguin321 commented
Unclosed :cl: in OP

2017-11-17 00:37 UTC, merged