Allows turrets to shoot cyborgs.
tgstation/tgstation pull request #32939
Opened 2017-11-20 17:56 UTC by Y0SH1M4S73R

:cl: Y0SH1 M4S73R (with credit to Anonmare)
add: Turrets can target silicons. Whether or not they will can be configured in the turret's interface.
fix: Syndicate turrets will shoot at non-Syndicate silicons by default.
/:cl:

Basically #32938 but with working code.

2017-11-20 18:12 UTC, Cyberboss requested changes

2017-11-20 18:12 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +	var/target_silicons = 0 //checks if it can shoot silicons
FALSE

2017-11-20 18:12 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +	target_silicons = 1
TRUE

2017-11-20 18:12 UTC, Cyberboss commented on code/game/machinery/porta_turret/portable_turret.dm
> +			if(!in_faction(C) && target_silicons) //if the target is a silicon and not in our faction, target it if we are allowed to target silicons
check target_silicons first

2017-11-20 18:17 UTC, vuonojenmustaturska commented
While you're rooting around this bit of code, please change the 0/1s to TRUE/FALSE, and refactor the check to be `if (target_silicons && issilicon(A))`, that way the branch is skipped early when the setting is false, which seems to be the default.

2017-11-21 00:36 UTC, WJohn commented
These syndie turrets don't shoot at syndicate borgs, right? Faction overrules that, yes?

2017-11-21 17:48 UTC, Anonmare commented
@WJohn I think it might, non-AI turrets actually consider people wearing Agent IDs a non-threat even if they normally would be. If not, it shouldn't be too difficult to add a check that looks for an Agent ID

2017-11-24 10:35 UTC, AnturK requested changes

2017-11-24 10:35 UTC, AnturK commented on code/game/machinery/porta_turret/portable_turret.dm
> +			if(target_silicons && !in_faction(S)) //if the target is a silicon and not in our faction, target it if we are allowed to target silicons
Still can be moved before the first type check.

2017-11-29 21:39 UTC, closed without merging