Measure energy values in joules
tgstation/tgstation pull request #32964
Opened 2017-11-21 11:25 UTC by SpaceManiac

:cl:
spellcheck: Energy values are now measured in joules. What was previously 1 unit is now 1 kJ.
/:cl:

Continues #32788. Power is measured in watts and energy is measured in joules. 1 W = 1 J/s. The actual mechanics have not changed, only descriptions. The ratio between cell units and joules is based on the fact that APCs tick every 2 seconds and increase cells by 0.002 units per watt. For reference:

* Crap power cell is 500 units = 500 kJ and will last 100 seconds at 5 kW.
* High-capacity power cell+ is 15000 units = 15 MJ.
* Crazy-good potato batteries are in the 400 MJ range.

I didn't touch clockcult because I'm not familiar with its mechanics, but it's probably also inconsistent.

2017-11-21 11:32 UTC, WJohn commented
This is also the case with clock cult stuff being stored in watts rather than joules, even though STORED energy is supposed to be joules if it's not being used.

2017-11-21 16:05 UTC, davethwave commented
Bringing a bit of reality like this is nice

2017-11-22 00:40 UTC, MoreRobustThanYou commented
Ensure you keep stuff that's supposed to be Watts, watts, and stuff that's supposed to be Joules, Joules.

2017-12-02 23:48 UTC, Cyberboss requested changes

2017-12-02 23:48 UTC, Cyberboss commented on code/__HELPERS/unsorted.dm
> +/proc/DisplayEnergy(var/units)
remove var/

2017-12-05 07:42 UTC, merged