Reverts pull facing change
tgstation/tgstation pull request #33007
Opened 2017-11-22 18:58 UTC by CPTANT

Reverts the pull facing part of #32778

I talked to some people on the server and a lot of people agreed that it looks kinda odd.

 Physically it might be "right", but it translates rather badly to our tile based game. For example when it comes to small objects such as cigarettes and books and whatnot, turning around because you are dragging a cigarette bud is just weird. People walking backwards at 20km/h also feels a lot more unnatural than someone not facing an object they are dragging.

2017-11-22 19:00 UTC, Qustinnus commented
"turning around because you are dragging a cigarette bud is just weird"

lol dragging a cigarette bud is weird in general. I don't really see your point.

2017-11-22 19:03 UTC, CPTANT commented
It just moving behind you is a lot less jarring then you turning around because you have to actively "pull" it.

2017-11-22 19:05 UTC, Qustinnus commented
i don't see how that is a negative difference

2017-11-22 19:10 UTC, Cyberboss commented
This was only supposed to trigger with structures IIRC

2017-11-22 19:14 UTC, psykzz commented
If you want to make it contextual for larger items that would be fine but honestly this is better overall.

2017-11-22 19:32 UTC, nicbn commented
So we're back in the addfeature-removefeature game?

2017-11-22 20:13 UTC, banthebantz commented
make it only apply to dense objects, done

2017-11-22 20:53 UTC, CPTANT commented
I just keep imagining someone backstepping at Usain Bolt speeds.

2017-11-22 21:30 UTC, nicbn commented
Just slowdown people when pulling then.
I was going to do it too but forgot.

2017-11-22 21:31 UTC, Qustinnus commented
slowdown when pulling is stupid and is a big ass balance change

2017-11-22 21:36 UTC, nicbn commented
I agree it is a balance change but I don't think it's stupid
I mean when you pull closets you normally walk a lot slower

2017-11-22 21:38 UTC, Qustinnus commented
and you are normally not always running through hallways. This is a video game not a simulation of real life. This kills tactical closets.

2017-11-22 21:38 UTC, nicbn commented
>This is a video game not a simulation of real life.

So the "people walking backwards at 20km/h feels unnatural" argument is invalid too.

2017-11-22 21:39 UTC, Qustinnus commented
ya

2017-11-22 23:27 UTC, CPTANT commented
All cosmetic changes are subjective. 

Still I feel the effect of pulling objects the "wrong way" around is pretty negligible, while high speed backwards motion is very noticeable.  

And there are plenty of real world objects I wouldn't turn around for to drag with me anyway. I can hold a chair just fine with one hand and drag it behind me

2017-11-23 01:35 UTC, kevinz000 commented
improve not remove

2017-11-23 03:14 UTC, Qbopper commented
this is a cool feature, if it's that big of a deal make it so it only works when dragging people/structures or something and small objects don't do it

2017-11-23 03:14 UTC, optimumtact requested changes
Make it apply for large/dense objects, this PR is not acceptable in current form

2017-11-23 03:43 UTC, ShizCalev commented
#33024 is better.

2017-11-23 03:49 UTC, closed without merging