Adds spawn override system
tgstation/tgstation pull request #33075
Opened 2017-11-24 21:19 UTC by AnturK

2017-11-24 21:20 UTC, praisenarsie commented on code/game/objects/effects/landmarks.dm
> +	jobspawn_override = TRUE
nothing to see here

2017-11-24 21:21 UTC, Cyberboss requested changes

2017-11-24 21:21 UTC, Cyberboss commented on code/controllers/subsystem/job.dm
> +		if(GLOB.jobspawn_overrides.len && GLOB.jobspawn_overrides[rank])
no need for .len

2017-11-25 12:20 UTC, Dorsisdwarf commented
casual reminder that this is specifically to let us make all assistants spawn in the gulag

2017-11-25 22:37 UTC, Cyberboss approved these changes

2017-11-25 22:37 UTC, merged