Adds combat knifes to nukeop gear and ability to mount bayonets on few weapons.
tgstation/tgstation pull request #33071
Opened 2017-11-24 13:19 UTC by The-clown-known-as-Pepe

Shouldn't upset the balance too much.

Changed guns are WT-550, c20-r and moist nugget.

![image](https://user-images.githubusercontent.com/25509881/33212221-5777e334-d122-11e7-88af-c5401332c610.png)

2017-11-24 13:22 UTC, Tlaltecuhtli commented
can you mount eswords and edaggers?

2017-11-24 13:24 UTC, The-clown-known-as-Pepe commented
@Tlaltecuhtli pretty sure edagger does less damage than combat knife (which has 20 force)

2017-11-24 13:26 UTC, Tlaltecuhtli commented
for stealth

2017-11-24 13:26 UTC, The-clown-known-as-Pepe commented
you want to hide a edagger on a gun?







fuck it why not

2017-11-24 13:42 UTC, nicbn commented
Add to egun, laser, HoS gun, captain antique, combat and riot shotguns and cycler shotgun too.

2017-11-24 14:27 UTC, DoctoreMad commented
>HoS gun, captain antigue

They, huh, have a rather odd shape. Are you sure bayonet would would there?

2017-11-24 14:27 UTC, Hatfish commented
Will we ever get bayonet sprites that aren't complete shit?

2017-11-24 14:31 UTC, WJohn commented
Yes, and you should see the updated ones shortly that I just made.

2017-11-24 14:42 UTC, The-clown-known-as-Pepe commented
>HoS gun, captain antique

Makes no sense for pistols

>combat and riot shotguns and cycler shotgun

Chances are that you'd rather want to shoot them instead

new bayonet sprite

![image](https://user-images.githubusercontent.com/25509881/33214913-02e13d82-d12e-11e7-9bce-706766f670dc.png)

2017-11-24 20:03 UTC, Mark9013100 commented
target head stand behind ally burst fire ap mag

2017-11-24 21:48 UTC, optimumtact commented
![PC LOAD LETTER, WHAT THE FUCK DOES THAT MEAN](https://file.house/wBgT.png)

Horrifying

2017-11-24 22:19 UTC, ike709 commented
We need a gun that shoots bayonets.

2017-11-24 22:20 UTC, The-clown-known-as-Pepe commented
pneumatic cannon

2017-11-25 03:09 UTC, WJohn commented
Could you also try to make the bayonet an underlay? See if it looks any better when it's behind the gun?

2017-11-25 12:19 UTC, The-clown-known-as-Pepe commented
sadly real coding is not my forte

2017-11-25 12:43 UTC, Qustinnus commented
go learn then :^)

2017-11-25 19:44 UTC, Anonmare commented
Can we attach a flashlight to a bayonet? Can we also attach a laser pointer for higher accuracy bayoneeting?

2017-11-26 01:22 UTC, ShizCalev requested changes

2017-11-26 01:22 UTC, ShizCalev commented on code/game/gamemodes/nuclear/nuclear.dm
> +	r_pocket = /obj/item/kitchen/knife/combat
put it in their bag instead, that way they still get it with the full kit outfit.

2017-11-26 01:26 UTC, ShizCalev commented
Might also want to add the knife to the allowed list for /obj/item/clothing/suit/space/hardsuit/syndi.

Also does it fit in /obj/item/storage/belt/military?

2017-11-26 11:06 UTC, Bawhoppen commented
That's not the right sprite... That's the survival knife miners get, not the combat knife you're giving them

Also literally definition of powercreep, but I still like it so it's okay

2017-11-26 12:25 UTC, The-clown-known-as-Pepe commented
@ShizCalev pretty sure they can store them in their shoes

2017-11-26 12:29 UTC, The-clown-known-as-Pepe commented
Currently there is only one sprite for all bayonets

2017-11-26 13:01 UTC, WJohn commented
I would rather they be given survival knives. They're not as powerful (15 instead of 20) and look better. Would also mean there's an actual reason to take a more expensive weapon like an esword or such.

2017-11-26 13:23 UTC, ShizCalev commented
The knife on the mosin sprite would be roughly 33 inches at the scale the weapon is at, the c20r knife would be roughly 12~13 inches, and the sec rifle knife would be about 5.6 inches. Reeeeeeeeeeeee

2017-11-26 15:29 UTC, The-clown-known-as-Pepe commented
blame kevinz

2017-11-29 16:45 UTC, ShizCalev approved these changes

2017-11-29 16:47 UTC, merged