Good Clean Fun: A vending machine for games!
tgstation/tgstation pull request #33265
Opened 2017-12-04 12:57 UTC by coiax

:cl: coiax
add: Quiet areas of libraries on station have now been equipped with a
vending machine containing suitable recreational activities.
/:cl:

- Sprite by WJohn
- Removes dice bags and cards from the tables of libraries, you can now
get them from the vendor.
- If we ever implement checkers or go or chess, we should add the
playing kits to the vendor.

![image](https://user-images.githubusercontent.com/609465/33553145-805d7ea6-d8ef-11e7-93da-bc710fbbff12.png)

Box:
![image](https://user-images.githubusercontent.com/609465/33553220-c16e46dc-d8ef-11e7-93a6-a3c0a052c8ff.png)

Delta:
![image](https://user-images.githubusercontent.com/609465/33553316-2469d04e-d8f0-11e7-8892-12f35dfa5d90.png)

Meta:
![image](https://user-images.githubusercontent.com/609465/33553368-549de7e6-d8f0-11e7-9b66-492780d756cb.png)

Omega:
![image](https://user-images.githubusercontent.com/609465/33553406-8b0bb240-d8f0-11e7-843e-baa52d36296a.png)

Pubby:
![image](https://user-images.githubusercontent.com/609465/33553469-d2ff2b36-d8f0-11e7-9265-2ba4d6374e19.png)

2017-12-04 19:53 UTC, praisenarsie commented on code/game/machinery/vending.dm
>  #undef COIN_CHARGE
move the undefs to the end of the file

2017-12-04 22:52 UTC, SpaceManiac commented
I don't think you can over easels or photocopiers, so the Meta one looks inaccessible?

2017-12-05 00:03 UTC, coiax commented
@SpaceManiac yeah, I have another PR to move that easel to art storage.

2017-12-05 07:59 UTC, ShizCalev requested changes
move undefs please.

2017-12-05 23:19 UTC, merged