People pulling/grabbing a defib target now gets shocked harmfully when the defib goes off
tgstation/tgstation pull request #33263
Opened 2017-12-04 11:50 UTC by kevinz000

:cl:
rscadd: Nanotrasen would like to remind crewmembers and especially medical personnel to stand clear of cadeavers before applying a defibrillator shock. (You get shocked if you're pulling/grabbing someone being defibbed.)
/:cl:

2017-12-04 11:52 UTC, kevinz000 commented
some part of me thinks 30 burn is too high hmmm...

2017-12-04 12:01 UTC, coiax commented
CLEAR!

2017-12-04 13:21 UTC, ExcessiveUseOfCobblestone commented
Shocking!

2017-12-04 15:28 UTC, RemieRichards commented on code/game/objects/items/defib.dm
> +				M.emote("scream")
screaming robots.
how exotic.

2017-12-04 16:08 UTC, davethwave commented
Well considering that your using your hands to really pull someone or grab someone 30 does seem a bit high... how about 20 instead?

2017-12-04 16:27 UTC, imsxz commented
Add a check to make sure that the one getting shocked doesn't have shock proof hands. Wouldn't make too much sense to be wearing insulated gloves and *still* be shocked.

2017-12-04 16:38 UTC, coiax commented
@imsxz except you can pull someone even if you're missing hands...

2017-12-04 16:47 UTC, davethwave commented
but you can't pull anything if your handcuffed...

2017-12-04 16:48 UTC, davethwave commented
hmm... I see a fix or tweak PR coming due to this.

2017-12-04 16:53 UTC, Spaceinaba commented
NOW I CAN YELL CLEAR AND IT WILL MEAN SOMETHING

2017-12-04 23:42 UTC, ExcessiveUseOfCobblestone commented
> Well considering that your using your hands to really pull someone or grab someone 30 does seem a bit high... how about 20 instead?

Punishing mistakes are 11fun11

2017-12-04 23:57 UTC, PKPenguin321 commented
dont even deal shock damage just straight up give them a heart attack

2017-12-05 05:42 UTC, Repukan commented
Cadavers or corpses.

2017-12-05 07:40 UTC, kevinz000 commented
who cares

2017-12-06 17:28 UTC, Cyberboss requested changes

2017-12-06 17:28 UTC, Cyberboss commented on code/game/objects/items/defib.dm
> +						M.emote("scream")
duplicate code, make it a proc

2017-12-06 17:28 UTC, Cyberboss commented on code/game/objects/items/defib.dm
> +					M.emote("scream")
.

2017-12-06 17:28 UTC, Cyberboss requested changes

2017-12-06 17:28 UTC, Cyberboss commented on code/game/objects/items/defib.dm
> +		playsound(get_turf(src), 'sound/machines/defib_charge.ogg', 75, 0)
playsound(src, ...

2017-12-06 17:28 UTC, Cyberboss commented on code/game/objects/items/defib.dm
> +				playsound(get_turf(src), 'sound/machines/defib_zap.ogg', 75, 1, -1)
playsound(src, ...

2017-12-06 17:29 UTC, Cyberboss requested changes

2017-12-06 17:29 UTC, Cyberboss commented on code/game/objects/items/defib.dm
> +				var/failed
Unused var

2017-12-08 01:49 UTC, kevinz000 commented on code/game/objects/items/defib.dm
> +				var/failed
wait what

2017-12-08 01:51 UTC, kevinz000 commented on code/game/objects/items/defib.dm
> +				var/failed
this is used..?

2017-12-09 21:25 UTC, Cyberboss approved these changes

2017-12-09 21:25 UTC, merged