[WIP] Makes the default view range a config option (Allows hosts to enable widescreen)
tgstation/tgstation pull request #33324
Opened 2017-12-06 02:47 UTC by deathride58

Followup to #32950 
This is happening.

:cl: deathride58
config: The default view range can now be defined in the config. The default is 15x15, which is simplified to 7 by BYOND. For reference, Goonstation's widescreen range is 21x15.
/:cl:

2017-12-06 02:51 UTC, MrStonedOne commented
Almost nothing can support a non-number in view. while view supports strings, everything that works with view expects it to be a number.

You'll have to make sure thats all handled

2017-12-06 02:52 UTC, deathride58 commented
Already handled by #32950

2017-12-06 04:12 UTC, MrStonedOne commented
Leave the other things set to world.view

Have your config change world.view, and leave it at that.

You are making this a million times harder on yourself.

2017-12-06 04:42 UTC, deathride58 commented
~~I love it *hard,* daddy~< 3~~

Right now, the PR is actually mostly finished already. Changing the default view variable in the config works exactly as you'd expect it to. Aside from the title screen and the awfully buggy AI anticheat, there's really no noticeable errors or weird sudden view changes, if my 20 minutes of testing is anything to go off of.

The method I've gone about things is actually pretty sane and simple. I used atom to replace all instances of change_view(world.view) with change_view(GLOB.DEFAULT_VIEW). That was pretty much the heaviest lifting in this PR so far. world.view can be left as-is, since too many things rely on it for numeric calculations, as you've said.

All that's left is to figure out how to handle the title screen, and either remove or update the AI anticheat.

2017-12-06 15:25 UTC, Cyberboss requested changes

2017-12-06 15:25 UTC, Cyberboss commented on code/_globalvars/configuration.dm
> +GLOBAL_VAR_INIT(DEFAULT_VIEW, "15x15")
You are just mirroring the config though, just use CONFIG_GET(string/default_view) instead of GLOB.DEFAULT_VIEW

2017-12-06 15:25 UTC, Cyberboss commented on code/controllers/configuration/entries/game_options.dm
> +		GLOB.DEFAULT_VIEW = value
And then you don't need this ValidateAndSet

2017-12-06 15:25 UTC, Cyberboss commented on code/controllers/configuration/entries/game_options.dm
> +		GLOB.DEFAULT_VIEW = value
Also, the option should be in config.dm

2017-12-06 20:03 UTC, KorPhaeron commented
This is gonna be a pretty big performance issue if we have to increase the vision range of hostile mobs to compensate for this

2017-12-06 23:49 UTC, Deitus commented
im still entirely against this, i still see it as a silly fix for something that doesnt even really need balanced, not to mention causing way more problems than it "solves"

2017-12-07 00:35 UTC, deathride58 commented
@Deitus what exactly are you against here? This doesn't fix anything, nor does this balance anything. All this does is allow hosts the ability to change the default screen resolution that players get when they first connect. The amount of problems it actually causes are minimal, and happen to be insanely easy to fix.

@KorPhaeron Vision ranges of hostile mobs shouldn't have to be touched. Vision in areas with hostile mobs is usually obscured by walls and other objects anyhow, so the cases in which a larger view range is actually exploitable around hostile mobs are edge cases.

2017-12-07 00:40 UTC, Fox-McCloud commented
>This is gonna be a pretty big performance issue if we have to increase the vision range of hostile mobs to compensate for this

Not just that; overall client performance will be worse too.

Paradise insisted on using 17x17 for a while; when we switched to a better lighting system it increased the number of crashes.

It's an interesting concept, but I don't recommend it.

2017-12-07 02:27 UTC, MrStonedOne commented
I do want to at some point add a 1:1 mode for ghosts where their vision scales to what ever size is needed to allow them have the entire viewport filled without any scaling or letterboxing.

However, this other wise is unlikely to be enabled on /tg/. not that i'm against it being added for downstreams, but atm the internal sendmaps() function in byond is a large portion of cpu usage on the server. its why sybil and terry will have a 1% time dilation but bagil will be at 40% time dilation.

2017-12-07 03:40 UTC, deathride58 commented
In that case, all the work left for this PR is to resolve the issue with the AI anticheat. Updating the Centcom z-level's title screen to a non-1:1 resolution can be handled by downstreams if they choose to change the default resolution.

The title screen can probably be reworked to make changing the resolution even smoother for server hosts, but that's out of this PR's scope.

2017-12-07 09:54 UTC, MrStonedOne commented
>In that case, all the work left for this PR is to resolve the issue with the AI anticheat. 

Explain... as far as I know the anti-cheat doesn't bother with checking the client's view

2017-12-07 16:29 UTC, deathride58 commented
The anticheat compares client.view with getdistance if the AI is carded or shunted. This results in runtimes with non-1:1 resolutions. This has already been resolved.

2017-12-07 18:00 UTC, MrStonedOne commented
who added that? hmm no matter, i'll just remove it once your pr is merged.

2017-12-07 18:49 UTC, Cyberboss approved these changes

2017-12-07 18:50 UTC, merged