Fixes random in random seeds
tgstation/tgstation pull request #33362
Opened 2017-12-07 14:07 UTC by ACCount12

The lower threshold on `add_random_reagents` and `add_random_traits` wasn't set, which resulted in strange seeds being less likely to have traits and reagents than it was intended.

2017-12-07 14:52 UTC, Cyberboss requested changes

2017-12-07 14:52 UTC, Cyberboss commented on code/modules/hydroponics/grown/random.dm
> +		add_random_traits(lower=1, upper=2)
Don't use named args here

2017-12-07 21:39 UTC, ACCount12 commented on code/modules/hydroponics/grown/random.dm
> +		add_random_traits(lower=1, upper=2)
Why not?

2017-12-08 18:10 UTC, merged

2017-12-08 18:43 UTC, Cyberboss commented
@ACCount it creates maintainability issues in that named args aren't
verified until runtime. If a proc definition changes, it can create hard to
finds bugs. Not to mention certain callstacks of ours straight don't
support it (i.e. Initialize). The only case where named args are
appropriate is when you want to use the default parameter values of some
preceding arguments.

On Dec 8, 2017 1:10 PM, "AnturK" <notifications@github.com> wrote:

> Merged #33362 <https://github.com/tgstation/tgstation/pull/33362>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/33362#event-1379292849>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHywerYzaHvSfhu01wEbjMqr9PSM4A-3ks5s-XuSgaJpZM4Q5mZY>
> .
>

2017-12-10 01:06 UTC, ACCount12 commented
Oh, I thought BYOND handles this compile time. Thanks for the response.