Limit bullet overlays on walls
tgstation/tgstation pull request #33364
Opened 2017-12-07 14:42 UTC by AnturK

Badcode

2017-12-07 14:43 UTC, Cyberboss requested changes

2017-12-07 14:43 UTC, Cyberboss commented on code/game/turfs/simulated/walls.dm
> +		var/mutable_appearance/decal = pick(dent_decal_list[denttype])
Early return

2017-12-07 14:52 UTC, nicbn commented
Call undef at the end of the file, and raise this limit.

2017-12-07 15:01 UTC, vuonojenmustaturska commented
5 is plenty

2017-12-07 15:30 UTC, Cyberboss submitted a review, later dismissed

2017-12-07 15:48 UTC, Iatots commented
Badcoder.
An intense firefight ending with all walls bearing the exact same number of holes kill immersion real quick.
A wall starts to become more holes than panels at around 42 shots (assuming no overlap) so maybe start around there for the limit.

2017-12-07 15:52 UTC, Buggy123 commented
Agreed, increase the bullet hole limit significantly at the very least. I think this would only be useful to prevent abuse - such as somehow printing thousands of bullets and spamming enough holes to potentially cause lag.

2017-12-07 16:07 UTC, vuonojenmustaturska commented
potentially cause lag? this is literally the cause of most server crashes right now

2017-12-07 16:10 UTC, Iatots commented
Is the problem a high amount of holes on 1 wall or the global amount of decals?

2017-12-07 16:14 UTC, vuonojenmustaturska commented
The former is the more immediate concern, but the latter is also important because the holes are only cleared at roundstart or when a singulo eats the station, and their cost is largely the same regardless of whether there are 40000 extra overlays on one object or across the station

2017-12-07 16:18 UTC, Cyberboss commented
I think we can handle 10 per wall at least

2017-12-07 16:23 UTC, Arianya commented
The actual solution is to make bulletholes act as tiny atmos leaks/passthroughs that can be repaired with a welding tool or a sheet of metal.

2017-12-07 16:58 UTC, vuonojenmustaturska commented
Yes, the solution to a subsystem killing the server is to make it also stress another subsystem by making all tiles near a bullet hole permanently active atmos regions and remove the whole ATMOS_PASS_DENSITY optimization.

@duncathan

2017-12-07 16:59 UTC, Arianya commented
Of course it would, because people would have a reason to fix dents, rather then leaving walls with 89 holes.

Regardless, the limit should be higher then 5 lmao

2017-12-07 19:13 UTC, AnturK commented
I'll bump it to 15, we can amortize many overlays over many objects with CHECK_TICK, not so much single object having million overlays

2017-12-07 19:41 UTC, Cyberboss approved these changes

2017-12-07 19:44 UTC, duncathan commented
lmao, bullet holes acting as atmos leaks, fuckin imagine
that's such a retarded idea I can't do anything but laugh

2017-12-08 13:23 UTC, nicbn commented
>the holes are only cleared at roundstart or when a singulo eats the station

Just use a welding tool

A better solution is make the wall fall apart after some amount of shots

2017-12-08 13:26 UTC, RemieRichards commented
@nicbn is 100% correct, there's no other acceptable answer, the wall should break at 'X' holes, and that is your arbitrary limit.

2017-12-08 15:06 UTC, Iatots commented
It could break into sharp pieces too for when the bullets run out.

2017-12-08 15:10 UTC, Arianya commented
@RemieRichards Lets please not have structural damage 2.0 where people find yet more ways to avoid the construction or ID systems in favour of brute dumb force.

2017-12-08 15:32 UTC, merged

2017-12-08 16:11 UTC, vuonojenmustaturska commented
@RemieRichards the problem here is that a bullet hole does not mean that the wall is damaged in any way, only that at some point in time it collided with a projectile type. Reinforced walls for example should probably not be destroyed by laser tag guns, but making bullet holes destroy a wall will do that. 

@nicbn I can guarantee you with one hundred percent certainty that in no point in time will I ever take a 24 hour job hopping between the servers using a welding tool on walls that have been shot at when a better solution (this PR) exists.