[DNM] Blessed turfs are visible to people who care about blessed turfs
tgstation/tgstation pull request #33374
Opened 2017-12-07 21:44 UTC by coiax

- Chaplains, revenants, anyone with an ethereal jaunt spell will be able to see a glowing yellow shimmer on turfs that are "blessed".
- NOJAUNT_1 still exists as a flag, but that can no longer be set by any players, it's a pure admin only flag, for technical turfs.

- [ ] Sprites for the blessing, tuned so they're visible but not overwhelming
- [ ] Actually making it so only those groups of people (+observers) can see the blessings

2017-12-07 21:59 UTC, coiax commented
Drones are cool.

2017-12-07 22:11 UTC, ACCount12 commented
I like the idea of blessed tiles being a silent trap more.

2017-12-07 23:26 UTC, Buggy123 commented
I mean I'd agree with you if it wasn't for the fact you can bless massive areas really quickly via a fire extinguisher.

2017-12-09 05:46 UTC, ExcessiveUseOfCobblestone commented
> I mean I'd agree with you if it wasn't for the fact you can bless massive areas really quickly via a fire extinguisher.

I'd agree with you if those spells weren't temporary noclip. Ofc the area is going to be massive when you have to cover every nook and cranny or else it will be evaded.

2017-12-09 22:28 UTC, ghost requested changes

2017-12-09 22:28 UTC, MoreRobustThanYou commented on code/modules/mob/mob_movement.dm
> +				for(var/obj/effect/blessing/B in stepTurf)
you can change this to ```if (/obj/effect/blessing in stepTurf)```

2017-12-09 22:28 UTC, MoreRobustThanYou commented on code/modules/spells/spell_types/ethereal_jaunt.dm
> +	for(var/obj/effect/blessing/B in newLoc)
you can change this to ```if (/obj/effect/blessing in stepTurf)```

2017-12-27 21:44 UTC, closed without merging