Makes Video Camera Circuits Able to Broadcast to More Camera Networks
tgstation/tgstation pull request #33646
Opened 2017-12-18 06:04 UTC by JStheguy

[Changelogs]:
:cl: JStheguy
tweak: The camera network the integrated circuit video cameras' broadcast to is no longer hard coded, it is now set by a list on data input pin 2.
/:cl:

[why]: The video camera circuit only transmitting to a camera system only one dude can see is kinda lame, also it means that entertainment monitors can potentially get some use even when there isn't a thunderdome match on.

2017-12-18 15:57 UTC, KomradeSpectre commented
Yes yes yes yes yes yes yes yes yes yes

2017-12-18 16:16 UTC, JStheguy commented
Oh shit I accidentally included uncommenting IC_PRINTING from my testing.
But that shouldn't be a problem though, the servers use their own custom config files, right?

2017-12-18 16:38 UTC, praisenarsie commented
yeah

2017-12-18 22:06 UTC, arsserpentarium commented
Thank youfor doing it.

2017-12-23 00:05 UTC, ninjanomnom requested changes

2017-12-23 00:05 UTC, ninjanomnom commented on config/game_options.txt
> +IC_PRINTING
yes it doesn't matter but revert it anyways

2017-12-28 15:06 UTC, ShizCalev commented
@JStheguy

2017-12-31 23:46 UTC, ninjanomnom commented
@JStheguy ping for re-open if you start working on this again

2017-12-31 23:46 UTC, closed without merging