Immovable rod abuse, smite and event trigger.
tgstation/tgstation pull request #33681
Opened 2017-12-19 20:10 UTC by AnturK

Was it just an accident ? Who can tell ?

2017-12-19 20:12 UTC, Cyberboss commented
![](https://media.giphy.com/media/pcfdfm6hjTvji/giphy.gif)

2017-12-20 05:23 UTC, Buggy123 commented
Why are there 10,000 commits?

2017-12-20 23:38 UTC, ghost requested changes

2017-12-20 23:38 UTC, MoreRobustThanYou commented on code/modules/admin/verbs/randomverbs.dm
> +			var/turf/endT = spaceDebrisFinishLoc(startside, T.z)
Should Stun() the target, too

2017-12-21 06:11 UTC, ninjanomnom approved these changes

2017-12-21 06:11 UTC, merged