Turns the baseturf var into a part time list
tgstation/tgstation pull request #33705
Opened 2017-12-20 07:29 UTC by ninjanomnom

:cl: ninjanomnom
fix: Things like thermite which burned through walls straight to space now stop on plating. You'll have to thermite it again to get to space.
/:cl:

Changes the baseturf var into a list where it's needed. Most of the time it'll just be a single type like before but the ScrapeAway(), PlaceOnTop(), and CopyOnTop() procs handle turning it to and from a list.

This allows us to have multiple layers of turfs before digging down further doesn't change the turf type and allows shuttles (eventualy) to be able to keep track of more turfs under it, thus allowing shuttles to land on more complex landing zones than single types.

Shuttles and thermite works as intended, something is going to be broken though so testmerging is required.

fixes #32776

2017-12-20 08:26 UTC, Buggy123 commented
_Theoretically speaking_, this means that you could, say, allow players to emag navigation consoles, and then land *in* the station, right?

2017-12-20 10:48 UTC, ninjanomnom commented
Yes though in the case of a shuttle landing inside the station it'd make more sense if it broke a hole.

If you want it to keep all the turfs that were there before though sure it works

2017-12-20 16:48 UTC, Xhuis commented
With luck, after he shows he's a good worker, we can take Baseturf on as a full-time list, too.

2017-12-20 17:47 UTC, arsserpentarium commented
So that's way to implement archeology?

2017-12-20 17:52 UTC, ShizCalev requested changes

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
> +	baseturfs = /turf/open/floor/plating/asteroid/basalt/lava_land_surface
Remove these, there's a baseturf helper down.

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/deepstorage.dmm
> +	baseturfs = /turf/open/floor/plating/asteroid/airless
Replace with baseturf helpers.

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/spacehotel.dmm
> +	baseturfs = /turf/open/space
Replace with a space baseturf helper.

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomZLevels/beach2.dmm
> +	baseturfs = /turf/open/floor/plating/beach/sand
Delete and replace with a beach sand baseturf helper.

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomZLevels/caves.dmm
> +	baseturfs = /turf/open/lava/smooth;
Replace with a lava baseturf helper

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomZLevels/snowdin.dmm
> +	baseturfs = /turf/open/floor/plating/asteroid/snow
snow baseturf helper

2017-12-20 17:52 UTC, ShizCalev commented on _maps/shuttles/emergency_delta.dmm
> +	baseturfs = /turf/open/lava/smooth/lava_land_surface;
This seems to be a mistake.

2017-12-20 17:52 UTC, ShizCalev commented on _maps/RandomZLevels/caves.dmm
> +	baseturfs = /turf/open/floor/plating/asteroid/basalt
basalt baseturf helper

2017-12-20 19:56 UTC, Buggy123 commented
This does mean you could do things like pressurized shuttle bays with a floor, which is neat.

2017-12-20 22:01 UTC, ninjanomnom commented
That's already easily possible

2017-12-21 03:33 UTC, ninjanomnom commented
@ShizCalev Map baseturf helpers added and old baseturf var edits removed with these two regexes:
`\sbaseturfs *= *.+?;\n`
`{\n\sbaseturfs *= *.+?\n\s}`

2017-12-21 03:33 UTC, ShizCalev submitted a review, later dismissed
Mapping.

2017-12-21 06:57 UTC, Cyberboss commented on code/game/turfs/turf.dm
> +			current_target = initial(baseturfs) || type // This should never happen but just in case...
maybe add a stack_trace() then?

2017-12-21 06:58 UTC, Cyberboss submitted a review, later dismissed
Mapping module

2017-12-23 22:15 UTC, ninjanomnom commented
This has been tested enough, we're good to go whenever I think

2017-12-26 01:10 UTC, merged