Made atoms not smooth with shuttles
tgstation/tgstation pull request #33807
Opened 2017-12-24 01:45 UTC by Cruix

Fixes #25090

2017-12-25 16:47 UTC, Bawhoppen commented
Wow I never thought we'd fix this because of how smoothing works

2017-12-25 22:36 UTC, ninjanomnom requested changes

2017-12-25 22:36 UTC, ninjanomnom commented on code/game/area/areas/shuttles.dm
> +	canSmoothWithAreas = /area/shuttle
in initialize just have it set canSmoothWithAreas to the same type as itself for shuttle areas if the var is empty

2017-12-27 05:41 UTC, ninjanomnom commented on code/game/area/areas/shuttles.dm
> +	canSmoothWithAreas = /area/shuttle/pirate
could you move these pirate shuttle areas into the multi area shuttles section

2017-12-28 20:27 UTC, merged