Fixes deleting handcuffs
tgstation/tgstation pull request #33821
Opened 2017-12-24 19:42 UTC by ShizCalev

Didn't feel #33728 was a proper fix to the issue.

Fixes #33707

2017-12-24 19:47 UTC, Cyberboss submitted a review, later dismissed

2017-12-24 23:58 UTC, Cyberboss requested changes

2017-12-24 23:58 UTC, Cyberboss commented on code/modules/mob/living/carbon/carbon.dm
> +		qdel(I)
qdel(I)
return !(I == (handcuffed || legcuffed))

2017-12-25 16:56 UTC, Cyberboss submitted a review, later dismissed

2017-12-25 17:00 UTC, ShizCalev commented
Wait @cyberboss, how would that even work if those vars are cleared before it gets to that return?

2017-12-25 17:01 UTC, Cyberboss commented
arrgh right, set . before the qdel then just return

2017-12-25 22:25 UTC, ninjanomnom requested changes

2017-12-25 22:25 UTC, ninjanomnom commented on code/modules/mob/living/carbon/carbon.dm
> +		. = !(I == (handcuffed || legcuffed))
if `handcuffed` is not null and not `I` this will return false even if `legcuffed` is `I`

well true after it's been notted

2017-12-26 06:12 UTC, ninjanomnom approved these changes

2017-12-26 06:12 UTC, merged