Fixes airlocks in maintenance having walls in them
tgstation/tgstation pull request #33836
Opened 2017-12-25 09:08 UTC by kevinz000

*sighs at you*

2017-12-25 09:08 UTC, kevinz000 commented on code/game/machinery/doors/airlock.dm
> -					return INITIALIZE_HINT_QDEL
lateinit doesnt care about your qdel hints.

2017-12-25 16:59 UTC, Cyberboss requested changes

2017-12-25 16:59 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					break
use locate()

2017-12-25 17:02 UTC, Bawhoppen commented
This was an intentional feature. Talk to @Robustin

2017-12-25 17:03 UTC, Cyberboss commented
@Bawhoppen the use of the initialize hint says it's not

2017-12-25 20:49 UTC, ShizCalev commented
This was intentional #31312

2017-12-25 20:50 UTC, ShizCalev commented
![image](https://user-images.githubusercontent.com/6209658/34342848-6270fe70-e98b-11e7-92c1-6ea7dafaa523.png)
kek

2017-12-26 00:54 UTC, Bawhoppen commented
I swear to god

2017-12-26 01:10 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					break
and to keep on par with robustin's airlock tweak only qdel it if the locate succeeds

2017-12-26 01:22 UTC, ShizCalev commented
conflict.

2017-12-26 15:39 UTC, Robustin commented
It was intentional. 

The entire purpose was to have airlocks in maint and other "abandoned" areas obscure whether the door was broken or tampered from actual crew sabotage.

The original behavior included an option that flat out deleted the door and put a wall in its place... except I realized after seeing it live that nobody would actually be convinced because only an engineer would even have the tools to bother with deconstructing a door and replacing it with a wall... and that engineers would never do that when they can just replace the door with one using heightened access requirements. 

What I had seen is people building walls inside an open door to keep prying eyes out. I even paid $500 to commission this state of the art visual aid to help you smoothbrains understand: 

https://thumbs.dreamstime.com/z/brick-wall-behind-open-door-17766141.jpg

2017-12-26 16:36 UTC, Cyberboss requested changes

2017-12-26 16:36 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +				if(newtype)
What do you think will happen if T is null @kevinz000 >:[

2017-12-26 19:03 UTC, ChangelingRain commented
This was literally intended. That's about it.

2017-12-26 19:55 UTC, Bawhoppen commented
I was right!

2017-12-27 14:28 UTC, Cyberboss commented
The INITIALIZE_HINT_QDEL is still factually wrong

2017-12-27 14:30 UTC, Cyberboss requested changes

2017-12-27 14:30 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
>  			if(9 to 11)
else here.PlaceOnTop(/turf/closed/wall)

2017-12-27 14:30 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					return
Remove this return

2017-12-27 14:32 UTC, Cyberboss requested changes

2017-12-27 14:32 UTC, Cyberboss commented on code/game/machinery/doors/airlock.dm
> +					qdel(src)
Remove the qdel

2017-12-29 11:25 UTC, kevinz000 commented
On vacation and my laptop is depowrred.

2017-12-29 11:25 UTC, closed without merging

2017-12-29 11:39 UTC, PKPenguin321 commented
walls under airlocks is the stupidest intentional feature i've ever seen

2017-12-30 11:12 UTC, Bawhoppen commented
>just now people are realising how dumb it is