Prevent infinite loops in orbit checks
tgstation/tgstation pull request #33914
Opened 2017-12-28 22:33 UTC by optimumtact

We bookkeep the list of orbiters we've already checked, so if there is a
chain of orbiters orbiting each other we don't keep checking infinitely.

There is an argument that we should prevent this situation arising at
all, but the list should never grow that large so this should be fine

@MrStonedOne

2017-12-28 22:33 UTC, optimumtact commented on code/modules/orbit/orbit.dm
> +		if(OO in checked_already)
we can cut these checks down because the initial case of an orbiter orbiting itself or another orbiter is checked by this mechanism as well

2017-12-28 22:34 UTC, Cyberboss requested changes

2017-12-28 22:34 UTC, Cyberboss commented on code/modules/orbit/orbit.dm
> +	checked_already.add(src)
[src] = TRUE

2017-12-28 22:34 UTC, Cyberboss commented on code/modules/orbit/orbit.dm
> +		if(OO in checked_already)
checked_already[OO]

2017-12-28 22:34 UTC, Cyberboss submitted a review, later dismissed

2017-12-28 22:34 UTC, Cyberboss commented on code/modules/orbit/orbit.dm
> +/datum/orbit/proc/Check(turf/targetloc, /var/list/checked_already = list())
remove /var/

2017-12-29 15:59 UTC, Cyberboss approved these changes

2017-12-29 16:00 UTC, merged