Pwr Game can now produce research points when consumed by scientists
tgstation/tgstation pull request #33938
Opened 2017-12-29 23:09 UTC by deathride58

Title.

:cl: deathride58
add: Drinking Pwr Game as a scientist will now increase the station's research point generation rate!
/:cl:

The players want pwrgame&d back. This restores pwrgame&d.

2017-12-29 23:10 UTC, ishitbyabullet commented
damn, you fixed techwebs once and for all.

You did it!

2017-12-29 23:11 UTC, ShiggyDiggyDo commented
>CARGO ORDER MORE SOFTDRINKS SUPPLY CRATES!!

2017-12-29 23:13 UTC, ninjanomnom requested changes

2017-12-29 23:13 UTC, ninjanomnom commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	var/datum/techweb/linked_techweb
Don't store it, just grab the techweb in the proc and add points all at once

2017-12-29 23:14 UTC, Tlaltecuhtli approved these changes

2017-12-30 02:07 UTC, PKPenguin321 commented
i think vapes would make this OP

2017-12-30 03:33 UTC, Iamgoofball commented
you should make this get you really really hammered if you're a scientist

2017-12-30 03:41 UTC, deathride58 commented
@Iamgoofball that is out of this PR's scope.

2017-12-30 04:30 UTC, Iamgoofball commented
No it's balance that's funny

Just call it the ballmer peak

2017-12-30 06:28 UTC, kevinz000 commented
@Iamgoofball is right

2017-12-30 08:44 UTC, Iamgoofball commented
just make it work like this:
![ballmer_peak](https://user-images.githubusercontent.com/4081722/34452700-a2faf230-ecfa-11e7-8a8c-db87904a62b4.png)

2017-12-30 09:06 UTC, PKPenguin321 commented
Goof's idea is excellent actually

2017-12-30 11:09 UTC, Iamgoofball commented
Will code after my shift tomorrow

2017-12-30 16:08 UTC, Cyberboss commented
Ha. Ha.

No

2017-12-30 16:08 UTC, closed without merging

2017-12-31 05:39 UTC, Iamgoofball commented
@Cyberboss buzzkill

time 2 redo