Makes report issue handle null round IDs and server names
tgstation/tgstation pull request #34124
Opened 2018-01-05 16:59 UTC by Cyberboss

For them git version people

2018-01-06 17:18 UTC, lzimann commented on interface/interface.dm
> +		if(GLOB.round_id || servername)
could do this whole thing:
```
var/href = issue_template
if(GLOB.round_id || servername)
  href = "Issue reported from [GLOB.round_id ? " Round ID: [GLOB.round_id][servername ? " ([servername])" : ""]" : servername]\n\n[issue_template]"
DIRECT_OUTPUT(src, link("[githuburl]/issues/new?body=[url_encode(href)]"
```

2018-01-08 02:56 UTC, ShizCalev requested changes
what lzi said

2018-01-11 09:56 UTC, ShizCalev requested changes

2018-01-11 09:56 UTC, ShizCalev commented on interface/interface.dm
> +		DIRECT_OUTPUT(src, link("[githuburl]/issues/new?body=[url_encode(href)]"
missing brackets

2018-01-13 14:51 UTC, KorPhaeron commented
@Cyberboss reopen when you're ready, stale

2018-01-14 19:39 UTC, AnturK commented
Still broken ?

2018-01-15 19:36 UTC, ShizCalev requested changes

2018-01-15 19:36 UTC, ShizCalev commented on interface/interface.dm
> +		DIRECT_OUTPUT(src, link("[githuburl]/issues/new?body=[url_encode(href)]")
one more closing bracket

2018-01-16 20:28 UTC, merged