Replaces the RnD labs on Box, Delta, and Meta with circuitry labs
tgstation/tgstation pull request #34163
Opened 2018-01-07 06:30 UTC by deathride58

Title. Since RnD is now decentralized with techwebs, and circuitry is supposed to be the thing to replace RnD in the science department, this change should have been made a long time ago.

This also re-adds the RnD console to the bridge, as that was supposed to be done with the initial techwebs PR, according to #32606

This also moves the RnD console that used to be in the RnD area to the RD's office.

:cl: deathride58
add: The research department on Boxstation, Deltastation, and Metastation now contain circuitry labs instead of RnD labs. Have fun creating all sorts of unique devices!
/:cl:

## Screenshots
Boxstation
![image](https://user-images.githubusercontent.com/6356337/34647159-d8188dc0-f348-11e7-96f6-f698bbf893b2.png)

Metastation
![image](https://user-images.githubusercontent.com/6356337/34647160-e3cd8f44-f348-11e7-9425-c47510d7483c.png)

Deltastation
![image](https://user-images.githubusercontent.com/6356337/34647163-ec599a68-f348-11e7-850e-c94c4eec35d7.png)

The empty space is mostly to provide room to test drones and other devices that require an open space to function.

2018-01-07 06:31 UTC, SpaceManiac commented
The destructive analyzer currently can't be used independently of an R&D console.

2018-01-07 06:42 UTC, deathride58 commented
That can be fixed in a separate PR to make it plausible to activate the DA without touching the RD console.

2018-01-07 07:46 UTC, WJohn commented
Boxstation's empty space in R&D is a real eyesore. At least put warning lines down or *something* to indicate a testing area.

2018-01-07 08:10 UTC, Iamgoofball commented
@deathride58 add an extra work table and starter circuit printer

ps. make circuit tech roundstart

2018-01-07 08:25 UTC, deathride58 commented
Hmm...

Perhaps I can give the DA's functionality to the experimentor, and remove the DA from the maps to solve the problem of the DA requiring an RD console, making room for a circuit printer, and giving the experimentor an actual use all in one PR?

As for the empty space being an eyesore, would something like this work?
![image](https://user-images.githubusercontent.com/6356337/34647786-5a901bcc-f35a-11e7-9b16-f736e16782db.png)

2018-01-07 09:35 UTC, 81Denton commented
For clarification, would that mean you'd need to have an RD or someone with head access to research notes? Or at least have someone break into the RD office and move the console.

2018-01-07 09:59 UTC, kevinz000 commented
DA/lathe/imprinter MUST BE IN THE ROOM with a RND console.

2018-01-07 10:00 UTC, silicons requested changes
DA/lathe/imprinter MUST BE IN THE ROOM with a RND console. DA requires it to work, the other two get better interfaces with one. Unless we decide to fully remove rnd consoles that can research from anyone but heads of staff which is bad as of right now unless @KorPhaeron says otherwise.

2018-01-07 10:01 UTC, kevinz000 commented
just tuck em in a corner or something.

2018-01-07 11:19 UTC, arsserpentarium commented
1. Don't you think,that there should be more metal?
2. It's more usable,if there are more tables around working place. And you can do it,if you'll flip tables.
3.you should look at goof's map. It was better.
4.Yeah,don't remove console.

2018-01-07 12:58 UTC, Tlaltecuhtli commented
>expecting the condom to do rnd 
add this to the fuck up 2018 list

2018-01-07 14:30 UTC, GuyonBroadway commented
Why not put the circuit lab in the useless fucking E.X.P.E.R.I.M.E.N.T.O.R room?

2018-01-07 14:54 UTC, Kromgar commented
Okay what the fuck? Why the hell is the the research console being put in the RDs office? What if there is no RD then are we supposed to break into his office to do the research?

2018-01-07 14:54 UTC, arsserpentarium commented
Well basically yes. No good idea to put console only in RD hands: Heads of staff often have their head in the butt. And often is absent.

Maybe,guys, you shouldn't cripple RnD SO hard.

2018-01-07 15:07 UTC, Arzion5 commented
First, R&D was nerfed under the guise of a rework so now it takes about 60 minutes to max R&D instead of interacting with people around the station in order to acquire research-maxing items.
Afterwards, Virology was about to be killed off because it reduced interactions, mainly with medbay, because you could sit for a while and be healed.
Circuits also appeared in the mean time, which proved to be a balancing trainwreck as people discovered powerful combinations
Now this god-forsaken PR appears which makes any sort of actual R&D only available to be made by the RD.

You only have yourselves to blame. Why didn't you stop it?

2018-01-07 15:08 UTC, arsserpentarium commented
Also,please, don't even try to REPLACE all RnD with circuitry in it's current condition.
It's totally OK situation, when somebody uses printer as fancier protolathe with custom devices. Because you don't inventing your computer from scratch.
But now even this option is fairly complex,because there is no ingame blueprints base yet. So if i am botanist, I can't ask scientists for farmbot 4.2. I gonna ask for printer itself.
I don't want to make people hate circuitry ,forcing them to do fairly complex things,which is required creativity. Because forced creativity isn't fun.

2018-01-07 15:10 UTC, arsserpentarium commented
It's good idea to make lab for circuitry. 
But in this version it's like good thing,which is forcefully was screwed in your butt. Completely unwanted in this condition.

2018-01-07 15:12 UTC, GuyonBroadway commented
Can we stop pretending that going up to another player in another department and asking for one specific thing so you can get back to doing your job is in ANY WAY meaningful player interaction?

Does sec/heads ever roleplay with cargo during a rev round? Of course not and they never did, they just bust into cargo, stun and implant everyone, kill anyone who resists and they MIGHT give a taser to the QM before buying as many implants as they can and fucking off to ghestapo the station.

Forced player interaction does not create memorable moments, just a fucking checklist of shit to do that relies on another human to finish.

2018-01-07 15:34 UTC, Kromgar commented
What the fuck is the point of even having the destructive analyzer now that research is only done via waiting game?

2018-01-07 16:03 UTC, The-clown-known-as-Pepe commented
🤢

2018-01-07 16:46 UTC, Repukan commented
Lmao @ implying old RnD interacted with departments and didn't just min max research in 6 minutes.

2018-01-07 17:09 UTC, McBawbaggings commented
Isn't the purpose of command jobs to keep order, delegate jobs and actually act as heads of a department? Why is the core of science being taken out of it and given to the heads when their duty isn't a part of it. The workload of cargo should not be decided by the HoP and command staff solely. If the issue is that science goes for a greedy, selfish item progression then that's an issue with the order of techwebs or what RnD offers to other crew.

Also, why are the circuit printers being put away from the windows on boxstation? Having departments near windows so you can see and talk to people is a more organic way to encourage player interaction rather than to divvy it up among other jobs.

2018-01-07 21:06 UTC, deathride58 commented
Eh, if anyone else wants to pick this back up, do so after circuitry is a little more fleshed out, maybe after circuitry blueprints become a thing?

Also, ITT: salty science mains complain about about techwebs itself, rather than the actual PR.
Techwebs is supposed to have decentralized RnD, if you don't know what that's supposed to entail, then I dunno what to tell you. If the change that added research consoles to the RD's office and the bridge didn't get stealth reverted, then this PR would only be removing a single RnD console without adding any more.

Most of the players I've talked to had no idea that integrated circuitry is even a thing on TGcode. A circuitry lab would help alleviate that, and help encourage players to tinker around with circuitry.
Most of the players I've talked to are confused as to what science is supposed to do now that science can't speedrun RnD in 5 minutes and collect all of the overpowered toys the moment miners deliver materials. Axing the now nearly useless RnD lab would just be the final nail the coffin for old RnD, and replacing it with a circuitry lab would give science mains something to do the moment the round starts.

2018-01-07 21:06 UTC, closed without merging

2018-01-07 21:33 UTC, KorPhaeron commented
>Also, ITT: salty science mains complain about about techwebs itself, rather than the actual PR

Basically yeah. I appreciate the attempt though.

2018-01-07 22:55 UTC, davethwave commented
The only complaint about the circuits is that the cloning upgrade no matter what I do I can't find out how it works.

2018-01-07 23:23 UTC, arsserpentarium commented
I am totally like idea of circuitry lab. But I'd like to see it not INSTEAD of RnD lab, but along.
Why I think, that this attempt not the best idea? Have you ever seen RD in his office? I didn't. How fast he will die and loose access to this console? try to guess.

Also this project have design flaws:
1.need more metal. Now you can't feed even one printer.
2.try to look at goof's map, how there implemented workplaces. It's much better.
3.Pizza ,chairs and coffe vendors provided cosy athsmosphere.
4.It would be better to put there autolathe.

2018-01-08 10:19 UTC, FantasticFwoosh commented
You know nobody at the current moment can even operate the experimentor safely and coders have 0 public ideas for it, use the floorspace for that. Id even go as far as to say removing Toxins  mixing lab (move them to test lab) instead if the experimentor area is too out of the way.

Because everyone will love the parallel telescience meme when every awkward or powergamey piece of science equipment is constrained to that one room in the top right of science on box as a afterthought.

2018-01-08 18:03 UTC, Iamgoofball commented
Fwoosh is an idiot, disregard all fwooshposts.

2018-01-08 18:04 UTC, The-clown-known-as-Pepe commented
how about we just wreck firing range instead


SINCE RND HAS NO GUNS ANYMORE?

2018-01-08 18:06 UTC, arsserpentarium commented
If I'll figure out,how to fuck with mapmerger,probably I'll make circuitry lab on place of firing range.

2018-01-08 18:07 UTC, The-clown-known-as-Pepe commented
that would be great, thank you 🤗