Refactors how flashes get targets and whatnot, so they no longer work from inside containers to outside.
tgstation/tgstation pull request #34171
Opened 2018-01-07 22:09 UTC by kevinz000

Fixes #12591
:cl:
bugfix: Flashes can no longer work from inside containers to flash people outside.
/:cl:

2018-01-08 16:52 UTC, XDTM commented on code/modules/assembly/flash.dm
> +	var/last_use = 0
What's the difference from last_used? If there have to be both you might want to rename one of these to avoid confusion

2018-01-09 15:43 UTC, Cyberboss requested changes

2018-01-09 15:43 UTC, Cyberboss commented on code/modules/assembly/flash.dm
> +	return considering & can_see*/
remove

2018-01-09 15:43 UTC, Cyberboss commented on code/modules/assembly/flash.dm
> +	update_icon(flash = TRUE)
don't use named args

2018-01-09 15:43 UTC, Cyberboss commented on code/modules/assembly/flash.dm
> +/obj/item/device/assembly/flash/proc/flash_carbon(mob/living/carbon/M, mob/user = null, power = 15, targeted = TRUE, generic_message = FALSE)
remove = null

2018-01-09 15:43 UTC, Cyberboss commented on code/modules/assembly/flash.dm
> +	to_chat(user, "<span class='danger'>Your flash emits a blinding light!</span>")
[src]

2018-01-15 17:18 UTC, kevinz000 commented
@AnturK tested.

2018-01-16 14:30 UTC, merged