Adds human death sound
tgstation/tgstation pull request #34241
Opened 2018-01-09 22:05 UTC by Cyberboss

:cl:
soundadd: Humanlike mobs now have an audio cue when they die
/:cl:

2018-01-09 22:07 UTC, GuyonBroadway commented on code/modules/mob/living/carbon/human/death.dm
> +	playsound(src, 'sound/voice/human/death.ogg', 50, TRUE)
make this a variable intrinsic to the mob.

2018-01-09 22:49 UTC, TribeOfBeavers commented
Does this play if you deathgasp?

2018-01-09 22:58 UTC, Cyberboss commented
Yes

2018-01-09 23:00 UTC, Durkel commented
I get it, I aint laughin, but I get it.

2018-01-09 23:06 UTC, MMMiracles commented
oof

2018-01-09 23:44 UTC, epochayur commented
it's a slippery slope to *scream and *fart

2018-01-10 00:15 UTC, deathride58 commented
,,, Is this another oof meme?

2018-01-10 00:23 UTC, ShizCalev requested changes
https://dl.dropbox.com/s/3womui08pwy4rmc/death.ogg

cleaned up ending fade

2018-01-10 01:28 UTC, nicbn commented
Not the bad meme wave again

2018-01-10 03:26 UTC, Jordie0608 commented
This better not be the roblox sound.

2018-01-10 03:27 UTC, Jordie0608 commented
It was.

2018-01-10 03:27 UTC, closed without merging

2018-01-10 13:32 UTC, cebutris commented
We had this on Citadel for a while and it made the game 1000% more immersive I don't know why anyone would close this