Fixed stack automerging
tgstation/tgstation pull request #34396
Opened 2018-01-13 12:34 UTC by JohnGinnane

[Changelogs]: I've added a new argument to `mob/put_in_hands()` that let's you stop the stacks from merging automatically. This is set to `TRUE` by default. Fixes #34302

:cl: JohnGinnane
fix: Fixed not being able to alt click on a stack
/:cl:

2018-01-13 14:17 UTC, JohnGinnane commented
Need to look at #34397 before merging

2018-01-13 15:04 UTC, JohnGinnane commented
Ready for review and merge

2018-01-13 15:25 UTC, Cyberboss requested changes
There's another override of put_in_hands for simple_animals you need to adjust

2018-01-13 16:24 UTC, JohnGinnane commented
@Cyberboss that's done

2018-01-15 04:03 UTC, Cyberboss approved these changes

2018-01-15 04:04 UTC, merged