Adds holy vision (Some mobs can now see blessed tiles)
tgstation/tgstation pull request #34497
Opened 2018-01-15 23:49 UTC by DaxDupont

[Changelogs]: 
:cl: Dax Dupont & Coiax
add: Praise the lord for he has granted thy chaplains, wizards, revenants and eminences with holy vision. They can now see blessed tiles.
/:cl:

[why]: Finally we can see blessed tiles again. I think it was a feature at one point that got removed, not sure what happened to it but the wiki still mentions it.
I opted out observers aside from the ones that inherit the view from their former being to not have holiness shown all over the place.
![dreamseeker_2018-01-16_00-37-48](https://i.imgur.com/P931kPJ.gif)

2018-01-16 00:00 UTC, MoreRobustThanYou commented
Idea: have the holy turfs use connected textures so they'd look something like
![untitled](https://user-images.githubusercontent.com/25724666/34965995-69f71c6e-fa26-11e7-9398-59d4d5668673.png)

2018-01-16 00:01 UTC, DaxDupont commented
I don't think you can even do that in this case

2018-01-16 00:06 UTC, MoreRobustThanYou commented
anything's possible

2018-01-16 00:19 UTC, coiax commented
Can you have it as a toggle? And let observers have that toggle?

2018-01-16 00:22 UTC, DaxDupont commented
The way alternate appearances works makes it hard to make it a toggle, since you can't just toggle it back on without looping through all blessing effects and refreshing them.
I really don't think that's a good idea.

2018-01-16 00:25 UTC, deathride58 commented
Could probably use a planemaster to make turning it into a toggle a lot easier, along with making it a lot lighter on server performance.

2018-01-16 00:26 UTC, DaxDupont commented
I don't know how to use a planemaster

2018-01-16 02:18 UTC, Armhulen commented
that's pretty gross i'll be honest

2018-01-16 02:18 UTC, Armhulen commented
just do some shimmering yellowness it has to be better than that

2018-01-16 05:22 UTC, Bawhoppen commented
Wizards and chaplains should not get this...
That's a huge balance change. 
The sprite is also very bad and needs to be way better before this ever got approved. Also what MRTY is suggesting would be far preferable and is simply just using the smoothing flags.

2018-01-16 13:44 UTC, DaxDupont commented
I would like someone to give me a good sprite
Also I don't think you can smooth effects, and I dont think it'll work with alternate appearances

2018-01-16 13:45 UTC, DaxDupont commented
I can just reuse the clockwork floor glow

2018-01-16 13:49 UTC, DaxDupont commented
Here I made it so it's a modified ratvar floor glow that just glimmers occasionally.

2018-01-16 14:06 UTC, DaxDupont commented
End result:
Every 10 seconds:
https://i.imgur.com/2anvSPT.gif

2018-01-16 16:07 UTC, coiax commented
@DaxDupont actually, I think all observers use the alternate appearance system for toggling on and off people's individual ghost cosmetics (which is up to the viewer whether they see it), so I don't think it would be that bad to have a toggle.

2018-01-16 16:07 UTC, coiax commented
Also, I like the new sprite. Hurray for reusing animations, it's what I did for shuttle ripples.

2018-01-16 16:08 UTC, coiax commented on code/game/alternate_appearance.dm
> +		return TRUE
also include cult wraiths

2018-01-16 16:14 UTC, Potato-Masher commented
I believe the wiki says it was a faint gold shimmer every once in a while. I agree that we might need a little less obnoxious effect/sprite. 

The only thing I'm a little unsure about is the wizard getting this vision. Maybe add the holy vision when the wizard gets the Scrying orb as an add on to his xray vision?

2018-01-16 16:15 UTC, DaxDupont commented
This is the new sprite @Potato-Masher, people were complaining about the old one

2018-01-16 17:21 UTC, ChangelingRain commented
I'd recommend against using this visual for these. It's especially odd for the clockcult camera mob thing, since that visual means *good things* to it.

2018-01-16 17:23 UTC, DaxDupont commented
Honestly unless someone comes up with something else I can use I'd keep it like this tbh. 
I can't sprite well enough.

2018-01-16 19:07 UTC, Bawhoppen commented
Why are you trying to make a change if you can't actually get the sprite for it then?

2018-01-16 19:39 UTC, DaxDupont commented
@Bawhoppen Because @coiax his one went stale. We were supposed to have this feature years ago, it's been on the wiki for ages. Besides I tried using my own sprite but people didn't like it, which was about the best I could do.
It would just be nice if the people whining about the sprite being bad do more than just whine about it. 
I want the gameplay mechanic and the way it looked originally was good for me, this is also fine for me. It's a matter of taste.

2018-01-17 13:32 UTC, DaxDupont commented
There now it's barely visible sparkling on tiles.

2018-01-17 14:26 UTC, Potato-Masher commented
Ooo, sparkly. I like that one, it isn't too hard on the eyes and shouldn't be too annoying when you bless the entire main hallway or something.

I ain't no spriter, so you should take my opinions with a grain of salt though. I'm surprised that none of the usual spriters are giving feedback though, they are way better at telling whats good or bad.

2018-01-17 17:31 UTC, Bawhoppen commented
Having sprite standards is not autism

2018-01-19 12:37 UTC, DaxDupont commented
Can you review @ShizCalev it's been open for 4 days

2018-01-19 15:51 UTC, Cyberboss requested changes

2018-01-19 15:51 UTC, Cyberboss commented on code/game/objects/effects/blessing.dm
> +		else
else is dangling

2018-01-19 15:51 UTC, Cyberboss commented on code/modules/mob/mob_movement.dm
> +				for(var/obj/effect/blessing/B in stepTurf)
if locate()...

2018-01-19 15:51 UTC, Cyberboss commented on code/modules/spells/spell_types/ethereal_jaunt.dm
> +	for(var/obj/effect/blessing/B in newLoc)
if locate() ...

2018-01-19 16:07 UTC, DaxDupont commented
Done @Cyberboss

2018-01-21 08:04 UTC, merged