Ports Aurora's floor tile color turf decals (For mappers)
tgstation/tgstation pull request #34492
Opened 2018-01-15 22:39 UTC by deathride58

Title. This also puts turf decals in files separate from decals.dm, adds a shitton of colors to colors.dm in _DEFINES for future use, all copy-pasted from Aurora, and allows turf decals to pass their color to the decal component.

In layman's terms, this PR allows mappers to do shit like this without touching a single line of code
![image](https://user-images.githubusercontent.com/6356337/34963671-c0701ea6-fa17-11e7-9d8b-88233164ee85.png)
![image](https://user-images.githubusercontent.com/6356337/34964065-9dfbb842-fa19-11e7-84ea-f2ce766a975b.png)
![image](https://user-images.githubusercontent.com/6356337/34964220-7318909a-fa1a-11e7-8080-e5b99c63454f.png)

:cl: deathride58
add: Mappers can now color individual tiles of floors via turf decals.
/:cl:

These decals are a *lot* more flexible compared to the current method of coding in new tile color combinations as new turf subtypes. This also makes it much easier for mappers to

2018-01-15 22:41 UTC, optimumtact commented
hey, that's pretty good

2018-01-15 22:41 UTC, praisenarsie commented
@deathride58 and you didn't even bother adding the floor painter. shame on you.

2018-01-15 22:44 UTC, ChangelingRain commented
These seem much less textured than the current floor tiles, but that's at least easy to fix if desired since it's so little sprites to edit in comparison.

2018-01-15 22:52 UTC, epochayur commented
this is seriously cool

2018-01-15 22:52 UTC, praisenarsie commented
joan is right actually, they do look different. i'll show how tomorrow unless someone spots the Cool Mistake!

2018-01-15 22:58 UTC, deathride58 commented
Aye, these sprites are lifted directly from Aurora.

The only real noticeable issue is that only the bottom right tile has the subtle smudges present in all floor tiles, while the rest of the tiles lack those smudges. It should be a relatively easy, though tedious fix. That issue is pretty hard to notice ingame most of the time, though.

2018-01-15 23:16 UTC, coiax commented
If the floor is broken and then replaced with a fresh tile, will the decals still be there

2018-01-15 23:30 UTC, deathride58 commented
@coiax No, unfortunately, but that's an issue with all turf decals.

2018-01-15 23:53 UTC, Mark9013100 commented
Could this pave the way for a floor painter object?

2018-01-16 00:23 UTC, deathride58 commented
@Mark9013100 yep! This PR makes it a lot easier to add that.

2018-01-16 20:11 UTC, ShizCalev commented
https://imgur.com/a/ljaq4

2018-01-16 20:22 UTC, ShizCalev requested changes
Move the current intermediate directions of the corner_white sprite into a corner_white_side one, move corner_white_full's sprites into the intermediates of corner_white, and make the corner_white_full sprite contain 4 squares to color the entire tile instead.

2018-01-16 20:22 UTC, ShizCalev commented on code/game/objects/effects/decals/turfdecal/tilecoloring.dm
> +/obj/effect/turf_decal/corner
Change the path to `/obj/effect/turf_decal/tile` instead

2018-01-16 20:22 UTC, ShizCalev commented on code/game/objects/effects/decals/turfdecal/tilecoloring.dm
> +	icon_state = "corner_white_full"
These aren't actually full and should be part of the corner sprite instead as the intermediate directions.

2018-01-16 22:06 UTC, nicbn commented
Ok so who's going to replace all the old tiles with this

2018-01-17 17:20 UTC, praisenarsie commented
![image](https://user-images.githubusercontent.com/31222036/35056665-726db7ba-fbaa-11e7-88fc-ec61e5f1cf20.png)
wow im a day late on showing the mistake, as you see here there's lack of shading/detail on some of the tiles.
compare the default floors to the colored one, there's (for some reason) only shading/detail on the bottom right tile of the colored floors

so fix it somehow 🥘

2018-01-17 18:35 UTC, deathride58 commented
@praisenarsie Fixed.

@nicbn Probably not me, replacing every single colored tile with these would be a pain in the ass.

2018-01-17 21:11 UTC, ShizCalev requested changes

2018-01-17 21:11 UTC, ShizCalev commented on code/game/objects/effects/decals/turfdecal/tilecoloring.dm
> +	icon_state = "corner_white_full"
name = "tile decal"

2018-01-17 21:11 UTC, ShizCalev commented on code/game/objects/effects/decals/turfdecal/tilecoloring.dm
> +	name = "black corner"
name = "black tile decal"

and the rest leading down.

2018-01-18 21:42 UTC, praisenarsie commented
now add the fookin' floor painter

2018-01-19 03:28 UTC, merged

2018-01-19 03:32 UTC, ninjanomnom commented
I'm so proud of my decal component. It's grown up, left the nest, then come back to visit me already T.T