Makes fire priority values defines
tgstation/tgstation pull request #34534
Opened 2018-01-17 08:00 UTC by ninjanomnom

...again, except keeping the original values

2018-01-17 08:03 UTC, Jordie0608 commented
So many defines why even have them.

2018-01-17 08:04 UTC, Jordie0608 submitted a review, later dismissed

2018-01-17 08:04 UTC, Jordie0608 commented on code/controllers/subsystem/processing/projectiles.dm
> -	priority = 25
This one hasn't been replaced.

2018-01-17 08:04 UTC, Jordie0608 commented on code/controllers/subsystem/radiation.dm
> -	priority = 25
Nor this.

2018-01-17 08:48 UTC, ninjanomnom commented
So it's easier to tell what subsystems have higher priority than others by looking at a single place in code rather than having to go look at each subsystem individualy

2018-01-17 08:48 UTC, ninjanomnom commented on code/controllers/subsystem/processing/projectiles.dm
> -	priority = 25
These are both the same as the parent

2018-01-17 13:06 UTC, Cyberboss requested changes
Seperate SS_BACKGROUND subsystems into a different list
```
[03:55:17] <%MrStonedOne> background subsystems have their own priority bucket
```

2018-01-18 21:22 UTC, ninjanomnom commented
@Cyberboss feels like a pointless change imo and a lot of background subsystems just use the default anyway. Easier to just lookup based on subsystem name than also have know whether it's a background subsystem or not to know which section to look in.

2018-01-19 15:18 UTC, Cyberboss approved these changes

2018-01-19 15:18 UTC, merged