Tweaks space syndie listening post and lava syndie base.
tgstation/tgstation pull request #34718
Opened 2018-01-20 23:43 UTC by WJohn

Both bases now have their broadcast/listening channels turned into 1 intercom, which starts with listening on, broadcasting off (so you don't accidentally alert the station while talking on your radio near them). Space listening post now has a real microwave instead of a model, a library book management console, and the rocks surrounding it can now contain minerals.

:cl: WJohnston
fix: Space syndie listening post now has a real microwave, and a book management console. Lava listening post comms room intercom now no longer starts with broadcast on.
/:cl:

2018-01-20 23:45 UTC, Kromgar commented
Who was the dick who put them to be on right when you started?

Oh god I screamed internally when I saw my message about framing the captain got broadcasted to the whole crew

2018-01-20 23:54 UTC, Ratvar commented
Two intercoms let you say false messages to many radiochanels at once, leave second intercom in

2018-01-21 00:03 UTC, WJohn commented
That's how they always were in the original design, I think it's because they were ripped from ye olde DJ station out in space. So whoever made that, got copied by okand, got copied by me. I'm only fixing it all these years later.

2018-01-22 03:12 UTC, ShizCalev requested changes

2018-01-22 03:12 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
> +	listening = 1;
DV

2018-01-22 03:12 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/listeningstation.dmm
> +	listening = 1;
DV

2018-01-22 19:05 UTC, merged