Makes Oldman Robustin happy in the pants
tgstation/tgstation pull request #34868
Opened 2018-01-24 15:53 UTC by Dorsisdwarf

Apparently people think water is OP so instead of having a big circular argument in discord you can have it here. 

Takes water from a 6 second stun to a 3 second stun, which is just about enough to apply cablecuffs if you're quick I think.

:cl: Dorsidwarf
tweak: Through reverse-engineering syndicate technology, we've found that grips on the bottom of shoes make trips and falls less unpleasant.
/:cl:

2018-01-24 15:54 UTC, ShiggyDiggyDo commented
git gud

2018-01-24 15:54 UTC, coiax commented
bUt WhAt If YoU'rE nOt WeArInG sHoEs

2018-01-24 15:54 UTC, Maciekkub commented
<3
Lovely

2018-01-24 15:54 UTC, Cyberboss approved these changes

2018-01-24 15:55 UTC, Tlaltecuhtli commented
i ded

2018-01-24 16:03 UTC, Robustin commented
This only gave me a chub. To get the full mast experience you're gonna have to head on over to line 408 of  tgstation/code/modules/mob/living/carbon/carbon.dm and reweight the probabilities there so that its much more likely that you'll "throw" the items you drop when slipping. People seem to like that.

2018-01-24 16:12 UTC, Spaceinaba commented
water should just like fucking kill you with 200 brute when you fall on it tbh

2018-01-24 16:23 UTC, Anonmare commented
The top three workplace hazards are slips, trips and falls. Possession of water should be a capital offense

2018-01-24 16:24 UTC, 81Denton commented
>The top three workplace hazards are slips, trips and falls. Possession of water should be a capital offense

Move box of paper cups to nullcrates

2018-01-24 16:26 UTC, davethwave commented
The water dispenser also dispenses infinite paper cups with the water.

2018-01-24 16:31 UTC, ShadowDimentio commented
WHY

JUST WALK YOU IDIOTS, STOP NERFING STUNS GOD DAMN IT

2018-01-24 16:35 UTC, WJohn commented
because stuns are fucking dumb?? that's why.

remember when these things were largely invisible except for when they briefly flashed?

2018-01-24 17:23 UTC, ExcessiveUseOfCobblestone commented
water isn't that bad but epic intant half-screen aoe sliptrap that a simple mob can make from a common static item across every map is dumb (it was funny when PR'd though!).

2018-01-24 17:27 UTC, praisenarsie requested changes
make it 4.5 seconds

2018-01-24 17:27 UTC, ExcessiveUseOfCobblestone commented
🚲 🏠

2018-01-24 17:32 UTC, Spaceinaba commented
ah yes the fabled bike house

2018-01-24 17:38 UTC, DaedalusGame commented
press one button/click on one button on the screen

2018-01-24 17:47 UTC, calzilla1 commented
Why dont we nerf peels and the clowns PDA as well? Might as well.

2018-01-24 17:49 UTC, Iamgoofball commented
@KorPhaeron yet more proof we cant add small flavor features anymore

2018-01-24 18:15 UTC, epochayur commented
RIP stun meta, good riddance

2018-01-24 18:35 UTC, JStheguy commented
@calzilla1 
Because peels and clown PDAs are brightly colored, easily seen, and limited in supply, not a barely visible effect that can be acquired from literally anywhere in abundance.

2018-01-24 18:44 UTC, Robustin commented
@calzilla1 

I did nerf both of those things in 2016. People hemmed and hawed about the major reductions on lube, botany slips, and clown PDA.

Yet nearly 2 years later they're all still extremely effective combat items.

2018-01-24 19:00 UTC, BeeSting12 commented
originally thumbs up but changed to a 👎 when i saw he upvoted his own pr

2018-01-24 19:05 UTC, Robustin commented
@BeeSting12 

Its not my PR ya dingus and even if it was its still a shitty reason to change a vote. Most voting systems incorporating an automatic +1 for the author anyway.

2018-01-24 19:23 UTC, calzilla1 commented
@Robustin if you think of it, this PR is a knee jerk reaction. Also git gud

2018-01-24 19:23 UTC, ExcessiveUseOfCobblestone commented
Arguments against slip times that have been here for months/years being nerfed are kneejerk reactions, but arguments for water slipping getting the nerf bat after the relatively recent water tank change are well grounded?

2018-01-24 19:44 UTC, optimumtact commented
I don't want to have it here, take it to the forums

2018-01-24 19:44 UTC, optimumtact commented
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

2018-01-24 19:49 UTC, optimumtact commented
It's come to my attention you can't, so I will

2018-01-30 13:18 UTC, vuonojenmustaturska commented
@KorPhaeron you're assigned, can you take a look

2018-01-30 14:10 UTC, KorPhaeron commented
Forgot about this sorry

2018-02-01 04:41 UTC, ShizCalev commented
👎

2018-02-01 05:09 UTC, KorPhaeron commented
Cyberboss said he had an idea and would like me to wait a few days to decide

2018-02-01 05:10 UTC, Cyberboss commented
Right, remind me to code it in the morning

On Feb 1, 2018 12:09 AM, "KorPhaeron" <notifications@github.com> wrote:

> Cyberboss said he had an idea and would like me to wait a few days to
> decide
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/34868#issuecomment-362160236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHyweoAx0FkF3_cNjNYQpWg7dJsTV6E1ks5tQUcdgaJpZM4RreZt>
> .
>

2018-02-03 19:17 UTC, ShizCalev commented
@Cyberboss

2018-02-04 09:06 UTC, duncathan commented
evidently cyber has an alternative coming, RIGHT?

2018-02-04 09:06 UTC, closed without merging