Holorecord fixes and additions
tgstation/tgstation pull request #34882
Opened 2018-01-24 18:51 UTC by DaxDupont

[Changelogs]: 

:cl: Dax Dupont
add: You can now rename and copy holodisks!
tweak: Holodisks now have materials and the autolathe cost has been adjusted.
fix: Fixed holodisk speaker name not getting set when on non-prerecorded messages.
/:cl:

[why]: Fixes holorecords not setting speaker name. Checked for Unknown, since that's the default and it's required for the preprocessed disks.

2018-01-24 18:57 UTC, ExcessiveUseOfCobblestone commented
nani tf are holodisks

2018-01-24 18:59 UTC, AnturK submitted a review, later dismissed
Looks good.

2018-01-24 19:50 UTC, Anonmare commented
I use them to anonymously insult people

2018-01-25 00:31 UTC, DaxDupont commented
I made it so you can set them to loop, so people can have advertisement holopads and what not. Figured that was cool to do.

2018-01-26 07:34 UTC, AnturK requested changes
The rest looks good.

2018-01-26 07:34 UTC, AnturK commented on code/datums/holocall.dm
> +		record = holodiskOriginal.record
This should probably copy it not reference, cleaning the disk deletes the record.

2018-01-26 13:17 UTC, merged