Morgue and Crematorium Repositions
tgstation/tgstation pull request #35113
Opened 2018-01-29 19:41 UTC by ChuckTheSheep

[Changelogs]: 
:cl: Jittai
tweak: Some of the Morgue Trays and Crematoriums on Box, Delta, and Meta have been re-positioned.
/:cl:

Very minor re-positions, some are just turned, adds no extra trays.
Note: on Delta (image 2) I had to move a random-event-spawner up by 1 tile.

![1](https://user-images.githubusercontent.com/6071161/35525277-0a7a28d6-04f2-11e8-8e55-b9b67b693f36.png)
![x](https://user-images.githubusercontent.com/6071161/35528946-76caf122-04fd-11e8-890f-1ca8ed119bc1.png)
![3](https://user-images.githubusercontent.com/6071161/35525279-0a95304a-04f2-11e8-989e-9f35badafdd0.png)
![4](https://user-images.githubusercontent.com/6071161/35525280-0a9f9422-04f2-11e8-99a3-12a786c86678.png) ![5](https://user-images.githubusercontent.com/6071161/35525281-0aa96f2e-04f2-11e8-9bcb-684c4b9e1651.png)

[why]: To make use of the new directional states, gives a bit more space in the rooms, and arguably looks better.

redo of: #35110

2018-01-29 20:08 UTC, Armhulen commented
I don't like th cremator change but the rest is great

2018-01-29 21:34 UTC, ChuckTheSheep commented
I tweaked them a bit for variety's sake.

2018-01-30 14:31 UTC, DaxDupont commented
Delta morgue feels too big now

2018-01-30 14:55 UTC, ChuckTheSheep commented
It is the power of feng shui.

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	icon_state = "morgue1";
bad

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/BoxStation/BoxStation.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:27 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "crema1";
remove
put the ID back in.

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:28 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:29 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:29 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "crema1";
isn't the ID cremawheat?

2018-01-30 23:29 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "morgue1";
cremawheat

2018-01-30 23:29 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	icon_state = "morgue1";
remove

2018-01-30 23:29 UTC, ShizCalev requested changes
do the things please.

2018-01-31 00:01 UTC, ChuckTheSheep commented
@ShizCalev How do I remove the icon_state lines? And I don't think crematoriums need IDs unless there are multiple across the station- I wasn't aware of any of them using unique IDs.

2018-01-31 00:31 UTC, ShizCalev commented
open the map in notepad++ and remove the line.

2018-01-31 00:33 UTC, ChuckTheSheep commented
I was able to figure it out in editor, had to make the instances myself rather than auto-generate.

2018-01-31 01:04 UTC, ChuckTheSheep commented
Should be good to go.

2018-01-31 08:20 UTC, merged

2022-06-01 06:06 UTC, Son-of-Space commented on _maps/map_files/MetaStation/MetaStation.dmm
> +	req_access_txt = "27"
caught almost 4 years later because the change didn't work.