adds that farm your dad talked about sending your old pet catperson to so they could live out the rest of their lives free
tgstation/tgstation pull request #35168
Opened 2018-01-31 06:47 UTC by MMMiracles

:cl: MMMiracles
add: A brand new space-farm, where your family sends all your old/sick catpeople to live out the rest of their days being free to roam the acres and chase the field grayshirts.
/:cl:

[why]: It exists for lizards, so why not catpeople?

2018-01-31 06:49 UTC, Bawhoppen commented
You're a pretty funny guy MMMiracles, ya know that?

2018-01-31 06:49 UTC, MMMiracles commented
thank you ill be here all week

2018-01-31 07:21 UTC, ZeWaka commented
I like this PR. I think it adds to the backstory and the overall lore of the catpeople. By introducing the concept of a hospice/elderly home into their lore, the potential for further development is expanded greatly. The lore behind the Animal Rights Consortium is lacking, and definitely could be expanded within this PR.
This PR and process can also drive both profit and comfort to the station through the use of PRs #28732 and #28395, and contribute positively on both ends of the equation.

2018-01-31 07:26 UTC, Iamgoofball commented
Good PR

2018-01-31 07:28 UTC, Iamgoofball commented
This PR has my full support.

2018-01-31 08:04 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "cobweb2"
/obj/effect/decal/cleanable/cobweb/cobweb2

2018-01-31 08:05 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHEAST)";
dirty var

2018-01-31 08:05 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:06 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dirty var

2018-01-31 08:06 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:06 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dirty var

2018-01-31 08:07 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:07 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-manifold (NORTH)";
dirty var

2018-01-31 08:08 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "manifold";
dirty var

2018-01-31 08:09 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:09 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:09 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:10 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:10 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:11 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-bulb1 (NORTH)";
dirty var

2018-01-31 08:11 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "bulb1";
dirty var

2018-01-31 08:11 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-bulb1 (NORTH)";
dirty var

2018-01-31 08:12 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "bulb1";
dirty var

2018-01-31 08:12 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (NORTHEAST)";
dirty var

2018-01-31 08:13 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:13 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-door_open (NORTH)";
dirty var

2018-01-31 08:13 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "door_open";
dirty var

2018-01-31 08:14 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:14 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:15 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:15 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:15 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTHEAST)";
dirty var

2018-01-31 08:16 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:16 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-bulb1 (NORTH)";
dirty var

2018-01-31 08:17 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "bulb1";
dirty var

2018-01-31 08:17 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitecorner (WEST)";
dirty var

2018-01-31 08:17 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitecorner";
dirty var

2018-01-31 08:18 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (EAST)";
dirty var

2018-01-31 08:18 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:20 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:20 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dirty var

2018-01-31 08:20 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:21 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-manifold (EAST)";
dirty var

2018-01-31 08:21 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "manifold";
dirty var

2018-01-31 08:22 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-wooden_chair_wings (WEST)";
dirty var

2018-01-31 08:22 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "wooden_chair_wings";
dirty var

2018-01-31 08:22 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitehall (EAST)";
dirty var

2018-01-31 08:23 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitehall";
dirty var

2018-01-31 08:23 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitehall (WEST)";
dirty var

2018-01-31 08:24 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitehall";
dirty var

2018-01-31 08:24 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (EAST)";
dirty var

2018-01-31 08:25 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:25 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitecorner (EAST)";
dirty var

2018-01-31 08:25 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitecorner";
dirty var

2018-01-31 08:26 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitehall (NORTH)";
dirty var

2018-01-31 08:26 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitehall";
dirty var

2018-01-31 08:27 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-whitecorner (NORTH)";
dirty var

2018-01-31 08:27 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "whitecorner";
dirty var

2018-01-31 08:27 UTC, MMMiracles commented
ALRIGHT MAN I GET IT THERE'S A LOT OF TAGS

2018-01-31 08:27 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (SOUTHEAST)";
dirty var

2018-01-31 08:28 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:28 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dirty var

2018-01-31 08:29 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:29 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:29 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:30 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:30 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:31 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:31 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:31 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-neutral (NORTH)";
dirty var

2018-01-31 08:32 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "neutral";
dirty var

2018-01-31 08:32 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHEAST)";
dirty var

2018-01-31 08:32 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:33 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (NORTHWEST)";
dirty var

2018-01-31 08:33 UTC, ShizCalev commented
note to self; never use smartgit commenting for reviews again

2018-01-31 08:33 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:34 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHEAST)";
dirty var

2018-01-31 08:34 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:34 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHEAST)";
dirty var

2018-01-31 08:35 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:35 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (NORTHEAST)";
dirty var

2018-01-31 08:36 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:36 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-manifold (NORTH)";
dirty var

2018-01-31 08:36 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "manifold";
dirty var

2018-01-31 08:37 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (NORTHWEST)";
dirty var

2018-01-31 08:37 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:38 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHWEST)";
dirty var

2018-01-31 08:38 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:38 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "freezer";
dirty var

2018-01-31 08:39 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-freezer (EAST)";
dirty var

2018-01-31 08:39 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-manifold (EAST)";
dirty var

2018-01-31 08:40 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "manifold";
dirty var

2018-01-31 08:40 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (NORTHEAST)";
dirty var

2018-01-31 08:41 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:41 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dirty var

2018-01-31 08:42 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "intact";
dirty var

2018-01-31 08:42 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +/obj/machinery/door/window{
replace with door/window/westleft

2018-01-31 08:43 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (EAST)";
dv

2018-01-31 12:02 UTC, 81Denton commented on code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
> +			visible_message("[src] severs [L]'s tail in one swift swipe!", "<span class='notice'>You sever [L]'s tail in one swift swipe.</span>")
That's amazing, good PR.

2018-01-31 12:07 UTC, arsserpentarium commented
Lovely to see.
Lizard death camp is equipped with gas delivery system. And torture room is hidden in backroom.
Catperson death camp without gas chambers,but allow to slowly dissect one victim before eyes of all other prisoners. Lovely.
We need ghost antag role,which start in such facility. And must kidnap and dissect given race to put their guts into mining-like vendor to get more cool toys.
Like abductor,but just maniac.

2018-01-31 13:01 UTC, Bawhoppen commented
The real reason this PR is so great, is that it will solidify catbeasts as having a permanent place in tg-station code. Nobody can try to remove them after this...

2018-01-31 14:54 UTC, arsserpentarium commented
That's why you should be very careful with genocide:
You can try very hard. But if you will fail, or use wrong media policy, you'll only enforce their positions.

2018-01-31 15:00 UTC, ma44 commented
A ghost role spawner that it's only purpose is to hunt down people with tails, harvest and probably also have some form of restraints and actively hunt out the station can't possibly go wrong at all.

2018-01-31 17:11 UTC, Xhuis commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	tag = "icon-intact (SOUTHEAST)";
😩

2018-01-31 17:41 UTC, Buggy123 commented
I wondered why there were so many comments on this, I opened it expecting a raging discussion. Instead I saw only a dozen or so... and nearly a hundred "dirty var" reviews from Shiz.

2018-02-02 01:12 UTC, MMMiracles commented
c'mon guys the cats need their home

2018-02-02 05:56 UTC, ShizCalev requested changes
last ones.

2018-02-02 05:56 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +/area/space)
/area/ruin/unpowered

2018-02-02 05:56 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +/area/space)
/area/ruin/unpowered

2018-02-03 18:58 UTC, ShizCalev requested changes
you added another :(

2018-02-03 18:58 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +/area/space)
/area/ruin/unpowered/no_grav

2018-02-03 19:11 UTC, ShizCalev requested changes

2018-02-03 19:11 UTC, ShizCalev commented on _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
> +	icon_state = "freezer";
dv

2018-02-06 08:56 UTC, ShizCalev commented
@MMMiracles conflict.

2018-02-07 17:02 UTC, MMMiracles commented
ok lessa go

2018-02-08 02:23 UTC, merged

2018-02-08 02:48 UTC, WJohn reviewed
Sprites are fine.