Adds All-In-One Grinder as an actual buildable machinery
tgstation/tgstation pull request #35207
Opened 2018-02-01 19:49 UTC by Mokiros

:cl: Mokiros
add: All-In-One Grinder can now be built as an actual machinery using circuit board and micro-manipulator.
tweak: All-In-One Grinder doesn't have a roundstart beaker anymore.
/:cl:

Mostly cloned code from other machinery, tested a few times, no errors.
Had to remove roundstart beaker because it also spawns when you build a new grinder.

2018-02-01 19:50 UTC, DaedalusGame commented
make this upradeable baybee just do like processing speed or something so it's not silly

2018-02-01 19:52 UTC, PKPenguin321 commented
Make a `/roundstart` or `/hasbeaker` subtype that starts with a beaker that can be used for maps. 👎 until this part is corrected. You don't even need to do proper map editing, just manually open map files as text and find/replace any grinder paths with the /roundstart path.

2018-02-01 20:27 UTC, arsserpentarium commented
Or put beaker in part list.

2018-02-01 21:04 UTC, DaxDupont commented
Please don't remove large beakers from roundstart ones, they are needed in botany and chemistry, especially on maps without public autolathe.

2018-02-01 23:41 UTC, MoreRobustThanYou commented
Make a subtype that spawns with a beaker

2018-02-02 11:24 UTC, Bawhoppen commented
Just give those departments their own beakers, or they can get one from cargo.

2018-02-02 11:52 UTC, arsserpentarium commented
No,Bawhoppen. FYI,beaker usually provided in complectation of such machines

2018-02-02 16:17 UTC, DaedalusGame commented
some ruins also have grinders like syndi lavabase

2018-02-04 13:24 UTC, arsserpentarium commented
just put beaker in partlist.don't fuck with maps.
Also instead of /roundstart or /hasbeaker, you could make /constructable subtype. Which one without beaker.To avoid map/ruin fuckery.

2018-02-07 13:24 UTC, vuonojenmustaturska requested changes
Either fix all the maps or, as suggested, make the beakerless version a subtype for constructing instead. You could also maybe use a large beaker as a construction material, but then you'd have to remove it from the parts on completion so that it doesn't get teleported when the machine is deconstructed.

2018-02-08 08:55 UTC, optimumtact commented
ping for reopen or make a new pr when you've completed the tasks

2018-02-08 08:55 UTC, closed without merging