"This doesn't belong here?" Brings bay's spare id to our maps.
tgstation/tgstation pull request #35214
Opened 2018-02-01 22:23 UTC by praisenarsie

Since Bay is removing their spare id https://github.com/Baystation12/Baystation12/pull/20425
I might as well add it to our maps...

million dollar joke

2018-02-01 22:24 UTC, Bawhoppen commented
Just use our gold ID instead of mixing and match old-style sprites with new ones. Then clown can play pranks too.

2018-02-01 22:34 UTC, praisenarsie commented
also pubby's mapdiff is long because there was an area placed in the wrong spot

2018-02-01 22:40 UTC, DaxDupont commented
Add it to loot table instead

2018-02-01 22:40 UTC, PKPenguin321 commented
anybody else low key get hit with nostalgia by that sprite

2018-02-01 22:44 UTC, praisenarsie commented
@PKPenguin321 one of the reasons why i got the sprite from bay instead of using our shinier one

2018-02-02 03:45 UTC, MMMiracles commented
for something that'll be on every map should be its own thing instead of just a variety edited id, tbh

2018-02-02 11:07 UTC, lzimann commented
what mmmiracles said

2018-02-02 11:08 UTC, lzimann requested changes
make it an actual path instead of varedit across 5 maps

2018-02-02 14:35 UTC, ExcessiveUseOfCobblestone commented
I've literally never noticed the spare is not this sprite anymore.

2018-02-02 16:34 UTC, lzimann approved these changes

2018-02-03 19:12 UTC, ShizCalev commented
conflict.

2018-02-04 23:19 UTC, ACCount12 commented on code/game/objects/items/cards_ids.dm
> +		righthand_file = 'icons/mob/inhands/equipment/idcards_righthand.dmi'
Does it even need those? Aren't they set in parent type already?

2018-02-05 12:02 UTC, praisenarsie commented
@DaxDupont told me i have to rebase due to coiax doing funky shit with mapping

tldr have to do a lot of git fuckery, will just remake it in a new pr because i'm not bothered to rebase and fix conflicts and all

2018-02-05 12:02 UTC, closed without merging