Makes drake breath deadly again
tgstation/tgstation pull request #35236
Opened 2018-02-02 20:23 UTC by KorPhaeron

:cl: Kor
balance: The drakes breathe can once again hit multiple times if you stay in the stream of fire.
/:cl:

The fire breath was doing pitiful damage considering miners have firepoof gear, and the drake is currently too easy for the rewards it gives

2018-02-02 20:26 UTC, Repukan commented
Maybe we could limit the amount of materials it drops to only allow one Ash Drake suit as well.

2018-02-02 21:30 UTC, Buggy123 commented
As a miner i'm okay with this TBH.

2018-02-03 02:33 UTC, Kromgar commented
As a miner i'm okay with this because im not a dumbass and make an arena to fight it

2018-02-03 04:03 UTC, Darkgenerallord commented
Good pr, but drake should honestly either be significantly harder still or should have the drops toned down.

2018-02-03 15:13 UTC, ChangelingRain commented
This only does more damage if you're running in the direction of the fire:
It'd be better to just increase the actual damage it does, since this change won't do more damage if the target runs to the side or at the drake, even if they get hit.

2018-02-03 20:07 UTC, Cyberboss requested changes

2018-02-03 20:07 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/megafauna/dragon.dm
> +		for(var/mob/living/L in J.contents)
just in J

2018-02-04 23:04 UTC, imsxz commented
make megafauna abilities work on mechs current year. drake firebreath, swoop, and fire rain don't damage mechs. Bubblegums rend doesn't target mechs.

2018-02-06 16:46 UTC, Cyberboss commented
@korphaeron

2018-02-08 08:58 UTC, closed without merging