Mining sentience upgrade grants minebots a radio and ID
tgstation/tgstation pull request #35235
Opened 2018-02-02 20:21 UTC by KorPhaeron

:cl: Kor
add: Mining sentience upgrades now grant minebots an ID and radio.
/:cl:

I think it will make minebot much less frustrating to play if they can actually communicate with their team mates and move in/out of the base with them.

Thanks @coiax for the original idea with cayenne and leaving the code easy to expand on

2018-02-02 21:15 UTC, GunHog commented
Thank goodness! A minebot not having being able to yell at its owner over radio is frustrating when he walks out of the bot's light range. It is quite easy to get lost out there, you know!

2018-02-02 22:06 UTC, coiax commented on code/game/objects/items/implants/implant_misc.dm
> -	desc = "Are you there God? It's me, Syndicate Comms Agent."
undisclosed change, reee

2018-02-02 22:07 UTC, coiax commented on code/modules/research/xenobiology/xenobiology.dm
> +	var/obj/item/implant/radio/syndicate/imp = new(src)
Did you change the implant that you can buy as a regular traitor to be this?

2018-02-02 23:15 UTC, QualityVan commented
It might also be nice to give minebots an indication of their integrity if they don't have one but that's probably effort and outside scope.

2018-02-07 15:01 UTC, vuonojenmustaturska requested changes
Please replace the syndi uplink purchasable radio with the new subtype you made

2018-02-10 23:39 UTC, merged