Forces gases to obey certain laws of nature
tgstation/tgstation pull request #35277
Opened 2018-02-03 22:47 UTC by DaedalusGame

:cl:
fix: Fixes Noblium Formation being multiplicative, so having 500 moles of tritium and 500 moles of nitrogen no longer produces 2500 moles of noblium (it should correctly produce 10 moles)
fix: Fixes most reactions deleting more gas than exists and making gas out of nowhere
fix: Fixes Stim Formation invoking a byond bug and not using its intended polynomial formula
fix: Fixes Cryo Cells not having garbage_collect and clamping
fix: Fixes Rad Collectors not having clamping
fix: Fixes Division by Zero when Fusion has no impurities.
fix: Removes a redundant line in lungs
fix: Fixes rad_act signal not firing from turfs, living mobs, rad collectors and geiger counters
/:cl:

I need someone to look over my math again because I'm not 100% sure this is right.
Things that should probably be done before merging this:
- ~~Fire, but it's complicated~~
- ~~Fusion, but it's disabled (Can we get a rework already damnit)~~
- Add clamping to everything that removes gases because obviously we can't trust garbage_collect()

Did you know that TRITIUM_BURN_TRIT_FACTOR is a constant factor for how insane tritium is?
Closes #33532

2018-02-05 15:23 UTC, vuonojenmustaturska commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	tritium_catalyzed = min(tritium_catalyzed,cached_gases[/datum/gas/tritium][MOLES])
please combine these two assignments with the var initialization above

2018-02-06 06:58 UTC, duncathan requested changes
doing these in one line is ugly but unfortunately necessary for the minor performance enhancements that come with it

2018-02-06 06:58 UTC, duncathan commented on code/game/turfs/open.dm
> +		pulse_strength = min(pulse_strength,air.gases[/datum/gas/carbon_dioxide][MOLES]*1000,air.gases[/datum/gas/oxygen][MOLES]*2000)
could you leave a comment on these and similar limits elsewhere in the PR indicating that this is ensuring that matter is conserved appropriately?

2018-02-06 06:58 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	heat_efficency = min(heat_efficency,cached_gases[/datum/gas/oxygen][MOLES],cached_gases[/datum/gas/nitrogen][MOLES])
as naksu said above

2018-02-06 06:58 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	reaction_efficency = min(reaction_efficency,cached_gases[/datum/gas/tritium][MOLES],cached_gases[/datum/gas/plasma][MOLES]/2)
^

2018-02-06 06:58 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	heat_scale = min(heat_scale,cached_gases[/datum/gas/tritium][MOLES],cached_gases[/datum/gas/plasma][MOLES],cached_gases[/datum/gas/nitryl][MOLES])
^

2018-02-06 06:58 UTC, duncathan commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +	nob_formed = min(nob_formed,cached_gases[/datum/gas/tritium][MOLES]/10,cached_gases[/datum/gas/nitrogen][MOLES]/20)
^

2018-02-06 21:16 UTC, merged