Fixes the AI from being able to magically turn on broken APCs
tgstation/tgstation pull request #35284
Opened 2018-02-04 00:56 UTC by DaxDupont

[Changelogs]: 

:cl: Dax Dupont
fix: AIs can no longer turn on broken APCs,
/:cl:

[why]: Fixes #35257

2018-02-04 06:08 UTC, Cyberboss requested changes

2018-02-04 06:08 UTC, Cyberboss commented on code/modules/power/apc.dm
> +	if((stat & (BROKEN|MAINT)) || failure_timer)
use is_operational() instead of BROKEN, check and see if it check MAINT and failure_timer too

2018-02-04 14:29 UTC, DaxDupont commented
@Cyberboss done

2018-02-04 14:39 UTC, Cyberboss requested changes

2018-02-04 14:39 UTC, Cyberboss commented on code/modules/power/apc.dm
> +	if(!is_operational() || (stat & MAINT) || failure_timer)
https://github.com/tgstation/tgstation/blob/36b6b72b0268bab04198f3bd7ec6543e3772260a/code/game/machinery/_machinery.dm#L207-L208

MAINT isn't necessary

2018-02-04 16:04 UTC, DaxDupont commented
i fix

2018-02-06 05:39 UTC, ninjanomnom approved these changes

2018-02-06 05:40 UTC, merged