Fixes sleeps in movement procs creating lag in ssinput.
tgstation/tgstation pull request #35350
Opened 2018-02-05 16:44 UTC by MrStonedOne

2018-02-05 17:07 UTC, Cyberboss requested changes

2018-02-05 17:07 UTC, Cyberboss commented on code/modules/keybindings/setup.dm
> +	set waitfor = 0
FALSErino

2018-02-06 05:29 UTC, ninjanomnom approved these changes

2018-02-06 13:32 UTC, Cyberboss approved these changes

2018-02-06 13:32 UTC, merged