Removes null crates
tgstation/tgstation pull request #35355
Opened 2018-02-05 18:47 UTC by Iamgoofball

They're shit, op, and a crutch. Traitor qms can rain rockets of crates on people. More useful.

2018-02-05 18:48 UTC, Iamgoofball commented
Also every time we try to change cargo all I hear is "BUT NULL CRATES" and they're holding us back

2018-02-05 18:50 UTC, Togopalis commented
Eat your heart out kevinz000, you have a competition in who can nerf everything the fastest

2018-02-05 18:50 UTC, praisenarsie commented
@iamgoofball tbh the only way you're getting them removed is finishing what you started, SHIPPING DATUMS!

2018-02-05 18:51 UTC, evsey9 commented
yeah i have to agree with  this
null crates are op

2018-02-05 18:58 UTC, Buggy123 commented
I never roll traitor, but I like the _idea_ of this at least :-1:

2018-02-05 19:12 UTC, ExcessiveUseOfCobblestone commented
No, the problem is having so much money you can buy **a bunch** of them hence why it's so important to minimize money production.

If you take nulls then people will just spam guns/swat gear.

2018-02-05 19:17 UTC, Cyberboss approved these changes

2018-02-05 19:17 UTC, Cyberboss requested changes
Changelog

2018-02-05 19:53 UTC, Slignerd commented
I do agree that non-antags running around in traitor gear, while fun for said non-antags at the time, is a bit odd when you think about it. And by now, it's basically a common occurence.

2018-02-05 19:54 UTC, ExcessiveUseOfCobblestone commented
Is it now though after techdisks were removed?

2018-02-05 19:55 UTC, Iamgoofball commented
@ExcessiveUseOfCobblestone take your shit elsewhere

I don't care if people spam swat gear or guns, those aren't on the same level as literal uplink items and you fucking know it. Stop arguing in bad faith.

2018-02-05 20:03 UTC, PKPenguin321 commented
>goof buffs null crates to have 50 TCs of items instead of just being bundles
>wait a few months
>uses the buff to justify a full removal

🤔

2018-02-05 20:19 UTC, ExcessiveUseOfCobblestone commented
What exactly is worse than the WT rifle and SWAT armor? A bomb?

Why not just blacklist items instead of removing null crates entirely?

You could also raise the cost and not encourage people to add EZ money machines. Wouldn't that be something?

2018-02-05 20:30 UTC, MrDoomBringer commented
literally what is the point of this? you realize currently it takes **40** fucking crates to buy a single NULL, right?

2018-02-05 20:31 UTC, praisenarsie commented
@MrDoomBringer have you ever heard of selling minerals or stocks

2018-02-05 20:33 UTC, MrDoomBringer commented
@praisenarsie even selling stacks and stacks of plasma (which is a gay use of them, imo) is only gonna net you...3, maybe 4 crates? Ive seen fucktons of nulls ordered and not a single useful item, outside an extra emag or two.

also
>implying cargo's main way of point generation should be funless RNG that takes constant, soul-sucking monitoring and the entire round to get anything substantial

2018-02-05 20:35 UTC, Iamgoofball commented
We want to add the PTL to sell excess power for money but people bitch "muh null crate" any time we touch economy so I'm killing null crates @MrDoomBringer

2018-02-05 20:36 UTC, Iamgoofball commented
also I'd be killing them for my cargo rework down the line

2018-02-05 20:37 UTC, Iamgoofball commented
Raising the cost is a bandaid and telling people to add less features is retarded Cobby

2018-02-05 20:38 UTC, MrDoomBringer commented
@Iamgoofball I can respect that, but why not make more OP shit have a smaller chance of coming along, or just making it harder to get?

2018-02-05 20:43 UTC, Iamgoofball commented
Adjusting the contents of the null crate is ignoring the problem of letting players order traitor items and doesn't fix the problem of "we have to balance every credit gaining method against null crates"

2018-02-05 20:51 UTC, MrDoomBringer commented
Having traitor gear accessible from the crew in /some/ regard other than looting traitors adds a strong amount of gameplay, (ex.  paranoia: how did he get that agent ID? from his uplink or from a nullcrate?) as well as giving players more chances to see how useful some of the less used tator gear can be (promoting less ebow+esword bullshit and more interesting tator builds).

2018-02-05 20:55 UTC, MrDoomBringer commented
also @praisenarsie a stack of plasma nets you about 1 nullcrate. have you ever seen a single nullcrate ordered and something good been inside?

2018-02-05 20:56 UTC, praisenarsie commented
@MrDoomBringer define 'good'

2018-02-05 20:56 UTC, darkpaladin109 commented
Oh no, a stack of one of the most common types of ore around gets you "only" 1 crate!

2018-02-05 20:56 UTC, arsserpentarium commented
letting players order traitor items isn't a problem.It should be just well gated.
Also if you make more methods of gaining cargo points, there should be some things in cargo, which are OP but expensive.To provide goals for CP gain.
Otherwise, what will you buy,after you set up energy transfer laser and some kind of production line?Infinite pizza crates?

2018-02-05 20:57 UTC, MrDoomBringer commented
@darkpaladin109 in my ~1300 connections ive never seen someone sell more than 3 stacks of plasma

2018-02-05 20:58 UTC, MrDoomBringer commented
@praisenarsie something that makes buying the nullcrate worth it

2018-02-05 21:00 UTC, MrDoomBringer commented
potential solution i mentioned to @Iamgoofball: make NULLS only orderable from an emagged express console. That way the tator QM has to run about the station looking for them/send out their techs to watch out for an asston of nullcrate slanding. 
Secondarily, maybe give the crate a lock (openable by sec/warden) so you're not just dispensing tator gear among the crew, and so that if sec sees it, they have a chance to drag it back to brig for distribution among trusted officers.

2018-02-05 21:06 UTC, Cyberboss approved these changes

2018-02-05 21:12 UTC, ma44 commented
>This pr again

2018-02-05 21:18 UTC, ExcessiveUseOfCobblestone commented
"you're arguing in bad faith!!!"

*PR exists as a strawman to another PR*

Truly amazing the lack of self-awareness.

2018-02-05 21:20 UTC, MrDoomBringer commented
@ExcessiveUseOfCobblestone strawman to which pr?
also check your discord jeez

2018-02-05 21:21 UTC, ExcessiveUseOfCobblestone commented
@MrDoomBringer at work ^_^

also the laser beam pr #35345

2018-02-05 21:23 UTC, MrDoomBringer commented
![image](https://user-images.githubusercontent.com/29008542/35829327-8a96db9c-0a90-11e8-8f91-0c16f33c6b4c.png)
anyways as a fun experiment, i sold a fuckload of plasma (as in, many times more than ive ever seen sold), and saw how many OP and GAMEBREAKING things i could get. anyways, the results were essentially:

- aaa 5 godawful pistols, infinite powerfists and radiojammers, and a **single ebow jesus christ!!!**

2018-02-05 21:26 UTC, ExcessiveUseOfCobblestone commented
> doesn't do stocks

> has QM profile pic

:thinking:

2018-02-05 21:28 UTC, MrDoomBringer commented
i never said I do stocks, i just believe that they're a pretty damn boring solution for getting money; a problem that has such goddamn potential to have an amazing and fun solution, that hundreds of other games have accomplished.

2018-02-05 22:22 UTC, KorPhaeron commented
Having desirable items but limited money seems more fun for players than having infinity money but nothing to buy with it

If it isnt null crates it will be guns or implant spam or something

tl;dr cobby is right

2018-02-05 22:22 UTC, closed without merging

2018-02-05 22:23 UTC, Iamgoofball commented
@KorPhaeron Guns and implants are not the same as traitor items my dude

2018-02-05 22:24 UTC, Anonymous583 commented
Fuck off Goof, go do something good like finishing dwarves

2018-02-05 22:26 UTC, Iamgoofball commented
@Anonymous583 itt: angry null crate abuser

2018-02-05 23:26 UTC, kevinz000 commented
I abuse null crates and I think this is hilarious

2018-02-07 03:14 UTC, YakumoChen commented
null crates are a good reason to actually spend TC on the money briefcase