I question if this ever got tested
tgstation/tgstation pull request #35643
Opened 2018-02-13 23:03 UTC by Supermichael777

:cl:
fix: After a minor firmware update crew monitoring consoles now work for cyborgs.
/:cl:

Fixes: #35641

2018-02-13 23:14 UTC, francinum commented
the CMC needs to have a UI redo, it's operating on some really weird not-tgui system.

2018-02-13 23:22 UTC, Supermichael777 commented
way beyond my skill

2018-02-15 07:03 UTC, YPOQ commented
BYOND doc says range accepts strings
>You can also use a rectangular box size using a text string such as "13x11". Both arguments are optional and may be passed in any order.

2018-02-15 10:56 UTC, vuonojenmustaturska requested changes

2018-02-15 10:56 UTC, vuonojenmustaturska commented on code/game/machinery/computer/crew.dm
> +			return (locate(/obj/machinery/computer/crew, range(7, hclient.client.mob))) || (locate(/obj/item/device/sensor_device, hclient.client.mob.contents))
use `getviewsize()`, which returns a list with X and Y view sizes. Take the max() of those sizes, and round half of it. That's your view radius.

2018-02-25 20:45 UTC, optimumtact commented
ping for reopen or make new pr when you're ready to conintue

2018-02-25 20:45 UTC, closed without merging