The asteroid-with-engines shuttle now announces people it runs over
tgstation/tgstation pull request #35672
Opened 2018-02-14 19:03 UTC by coiax

:cl: coiax
add: When the asteroid-with-engines shuttle runs people over, there is
an anouncement with their names, allowing you to learn from their
mistakes.
/:cl:

Gotta get your name on the board.

2018-02-14 19:05 UTC, chesse20 commented
add this please and give me one

2018-02-15 01:42 UTC, RandomMarine commented
\>be geneticist
\>create army of monkeybrain men
\>stuff them all in lockers and bodybags
\>drag them into range of the shuttle
\>shuttle docks
\>instant cascade of announcements floods across the chat

2018-02-15 02:07 UTC, darkpaladin109 commented
Yeah, you should make it so that NPC's don't count for that, if possible.

2018-02-16 17:11 UTC, Cyberboss requested changes

2018-02-16 17:11 UTC, Cyberboss commented on code/datums/components/roadkill_counter.dm
> +	names = list()
make this a lazy list

2018-02-20 07:42 UTC, chaoko99 commented
Reminds me of when slimepeople could gain stacks from the toxins they'd take from their own blood. They had to use a shuttle to stop me.

2018-02-21 20:19 UTC, optimumtact commented
stale ping for reopen etc, just needs that lazy list

2018-02-21 20:19 UTC, closed without merging