Map spawned corpses start with their suitsensors turned off
tgstation/tgstation pull request #35731
Opened 2018-02-16 19:23 UTC by TankNut

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: TankNut
tweak: Corpses spawned in ruins have their suit sensors disabled
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Some ruins are meant to be easier to find than others, using a crew pinpointer to home in on corpses wearing security jumpsuits (Which always start with their suit sensors enabled) defeats the point of not including a GPS in the first place.

2018-02-16 19:37 UTC, Cyberboss requested changes

2018-02-16 19:37 UTC, Cyberboss commented on code/modules/awaymissions/corpse.dm
> +			var/obj/item/clothing/under/C = locate(/obj/item/clothing/under) in H
= H.wear_suit

2018-02-16 20:33 UTC, 81Denton commented
While the SCP-239 ruin is pretty valuable, this PR would leave players pretty much unable to find it - might as well remove it from the game.

Making the coffee machine a lot harder to get to would be a less ham-fisted solution.

2018-02-16 21:01 UTC, Repukan commented
If they really want to find it, they'll look for it.

Ruins aren't supposed to be something you can easily rush to every round. They're supposed to be there to spice space for those that are willing to look.

2018-02-16 21:46 UTC, 81Denton commented
That would be valid if it wasn‘t A) smaller than a single screen and B) the vast majority of ruins didn‘t have GPS signals.

2018-02-16 21:50 UTC, Cyberboss approved these changes

2018-02-16 22:56 UTC, Iatots commented
If the ruin was deliberately given no GPS signal, what makes you think the _other_ GPS system is ok?

@MoreRobustThanYou

2018-02-16 23:36 UTC, MoreRobustThanYou commented
it CAN be detected slightly further than a screen, the lasers range are slightly further than one screen

2018-02-17 14:53 UTC, merged

2018-02-19 01:51 UTC, AlexTheSysop42 commented
>SCP-239