Fixes mushroom bowls
tgstation/tgstation pull request #35740
Opened 2018-02-16 22:58 UTC by fludd12

Made the mushroom bowl a subtype of the normal bowl, and deleted a
duplicate definition.

Also, adds custom soup and salad support for the mushroom bowls.

Fixes #32471

2018-02-16 22:59 UTC, praisenarsie commented
### ITS THE REAL FLUDD12

2018-02-16 23:01 UTC, fludd12 commented
...Was there a fake fludd12...?

2018-02-18 19:42 UTC, fludd12 commented
@optimumtact Does it look good?

2018-02-19 01:06 UTC, ShizCalev requested changes

2018-02-19 01:06 UTC, ShizCalev commented on code/modules/mining/lavaland/ash_flora.dm
> +	return
don't need this return

2018-02-19 20:58 UTC, merged

2018-02-19 22:04 UTC, fludd12 commented
Ah, thanks for the fix, I didn't have power yesterday.