Removes the Extend-o-Hand
tgstation/tgstation pull request #35771
Opened 2018-02-17 21:59 UTC by Iamgoofball

1. attack_hand on 90% of objects was designed with "you're next to the machine" in mind
2. this is shit code, doesnt call ..(), and has long range(ha) balance implications and fucks shit up bigtime
3. doesnt even work properly and bypasses all normal shit for calling punches/disarms/etc.
4. we had huge arguments over changeling tentacles and curator whips disarming people and we allowed this?

2018-02-17 22:45 UTC, deathride58 commented
Needs `i ded` label

2018-02-17 22:46 UTC, kevinz000 commented
honestly this is one of those things that are neat but should have better code

2018-02-17 22:47 UTC, Spaceinaba commented
fix the code then dork

2018-02-17 23:14 UTC, Iamgoofball commented
@Spaceinaba the proper fix for this would require a recode of how attacking and clicking works and I'm not about that life

2018-02-17 23:47 UTC, Armhulen commented
this is sadly correct

2018-02-18 03:44 UTC, PKPenguin321 commented
I whipped this up in like 30 seconds so I don't really mind if this goes through
Just curious what exactly prompted this? Did they turn out to be OP or something

2018-02-18 03:56 UTC, BeeSting12 commented
@PKPenguin321 
1. attack_hand on 90% of objects was designed with "you're next to the machine" in mind
2. this is shit code, doesnt call ..(), and has long range(ha) balance implications and fucks shit up bigtime
3. doesnt even work properly and bypasses all normal shit for calling punches/disarms/etc.
4. we had huge arguments over changeling tentacles and curator whips disarming people and we allowed this?

2018-02-18 05:27 UTC, PKPenguin321 commented
no yeah i read that but i mean those are just kind of existing conditions, usually PRs like these are prompted by something out of the ordinary happening in game

2018-02-18 08:00 UTC, 81Denton commented
@PKPenguin321 Some monk killed someone with punches that didn't show messages or something

2018-02-18 12:54 UTC, Iamgoofball commented
Which prompted me to check the code out looking for a bugfix and then oh god

2018-02-18 15:52 UTC, KorPhaeron commented
If extendo hands dont function it probably means reach weapons in general don't function, and if you're going to remove the only reach weapon for being non functional you may as well remove the rest of reach code as well

2018-02-18 19:09 UTC, Iamgoofball commented
@KorPhaeron nono, it's not an issue with reach code

lemme just code comment to explain the issue

2018-02-18 19:09 UTC, Iamgoofball commented on code/game/objects/items/weaponry.dm
> -	M.attack_hand(user)
see this fucker right here? it's the issue

2018-02-18 22:52 UTC, Cyberboss approved these changes

2018-02-18 23:04 UTC, KorPhaeron commented
@Iamgoofball in that case just the icons then please

2018-02-18 23:25 UTC, Cyberboss requested changes
Icons

2018-02-22 03:40 UTC, Qbopper commented
just make it admin spawn only because it's a funny meme

2018-02-22 06:07 UTC, Iamgoofball commented
ehhhhhhhhhhhhhhhhh

2018-02-24 05:50 UTC, Cyberboss commented
They think it don't be like it be

2018-02-24 05:50 UTC, closed without merging