Adds 20% Iron production to Steel Caps
tgstation/tgstation pull request #35819
Opened 2018-02-19 13:33 UTC by ThePainkiller

Because it's ridiculous that an Iron Rod-producing plant does not produce Iron by itself as a chemical, so....okay, let's be honest. Botany really needed a way to make EMP pulses against things like a Malf AI, rogue Borgs or a Nuke ops Marauder. There's already a lot of things you can make in botany, and it was really lacking on EMP making capabilities. It's infuriating that something as basic as Iron is not produced by any plants, and a "steel cap" mutation is the perfect excuse for a plant to have it.
If a 100 potency Electrical Activity potato battery can have as much charge as a bluespace power cell (40MJ) and you can make atropine rollies or ephedrine gaia then why the fuck not be able to do EMP's like a chemist with a grenade?

**Botanical notes:**
Tested on a private server with Lemons, producing 27 Uranium and 21 Iron on 100 Potency with Densified Chemicals, resulting on an EMP pulse with size (1,3). Potency below 90 to 78 create EMP's of size (1,2).

2018-02-19 13:38 UTC, QualityVan commented
You used to be able to grind metal rods/sheets to get iron, was that removed?

2018-02-19 13:46 UTC, DaedalusGame commented
no, but he wants to produce automatic emp pulses with seperated chems

2018-02-19 13:47 UTC, arsserpentarium commented
emp tomatoes is rising.Gold now grows on trees.
I like it.
But there is really lack of oxygen production 15%

2018-02-19 13:49 UTC, ThePainkiller commented
^ I second your motion. Grass Seeds should produce Oxygen too. Botany can grow its own Unstable Mutagen, but not its own Saltpetre...yet. Maybe they don't want Botania to be so independant from Chemistry...

2018-02-19 13:50 UTC, arsserpentarium commented
Anyway,there is no nitrogen.

2018-02-19 13:51 UTC, ThePainkiller commented
Gatfruits produce 7% nitrogen IIRC, but you need xenobio.

2018-02-19 13:52 UTC, arsserpentarium commented
Have you ever recieved this gene from xeno?

2018-02-19 13:53 UTC, 81Denton commented
@DaedalusGame I mean botanists can grind metal and inject the iron into a fruit with uranium production, but I've only ever seen one person do that.

2018-02-19 13:57 UTC, DaedalusGame commented
selea, he's talking about using slimes to make gatfruit, then turning them into seeds

2018-02-19 13:58 UTC, arsserpentarium commented
I know, and I've tryed a lot. But RNGesus wasn't merciful for me.

2018-02-19 14:02 UTC, ThePainkiller commented
Using the _"inject iron into your plant to have it mixed with its chemicals"_ method makes it a chore, or makes you very similar to a xenobiologist making localized reactions when what you need is to throw the fruits at them. My PR is to help make the process of making EMP fruits more automated.
There's already tesla shock fruits and nitroglycerin lemons anyways, so why the hell not?

2018-02-19 14:28 UTC, Ordonis commented
I think the why the hell not is explicitly outlined in the fact that they already have teslafruit and nitro lemons; Botany is almost completely self-sufficient, and can grow obscenely powerful in a way most other departments can't; having them be a one-stop shop for all problems isn't going to make that better.

2018-02-19 16:25 UTC, DaedalusGame commented
Botany is the best designed department on the station because it's non-obvious even to code readers in some cases and putting thought into doing it can get you powerful toys. It's also not a one-stop shop because any kind of powergaming requires two or more competent botanists and a competent chemist which happens once every bluemoon. The argument that botany can do everything is tiring everybody out can't you see

2018-02-19 18:53 UTC, Teepeepee commented
Weld it into metal, grind down, easily print large beakers from public lathe, make 'nades with the fucktons of metal you should have (grab some cable too I guess). Not that hard tbh, and way more potent if you fill the beakers.

2018-02-19 18:55 UTC, Teepeepee commented
Also if you get to grow steel caps and glow berries during ops then they're not really that much of a threat, if they're taking so long.

2018-02-19 19:04 UTC, 81Denton commented
🆑

2018-02-19 22:43 UTC, ThePainkiller commented
@Teepeepee Read my comment again. EMP's being useful against a [Marauder](https://github.com/tgstation/tgstation/blob/d282c60c7d1056a2a98968f6fc00b70fcfb71c21/code/game/mecha/combat/marauder.dm), wich is bought during War Ops since it costs a fuckton of TC, and you have a 20 minutes time window to be able to make them.

2018-02-20 02:12 UTC, Repukan commented
@KorPhaeron please give some input on this ridiculous arms race powercreep that is presented by both this and the other Apple PR

2018-02-20 05:11 UTC, ThePainkiller commented
I'm neither competing nor comparing with any other PR, this is an idea I had in my mind to make EMP's without the need to grind iron and inject it on an uranium plant, and my first contribution other than typos. But I agree, I'd like to see a second opinion, if it is balanced, if it should be less iron produced, etc

2018-02-20 05:26 UTC, Repukan commented
No no, I don't mean any abrassivenes, but this is probably making botany too self reliant.

2018-02-20 15:05 UTC, ExcessiveUseOfCobblestone commented
Is it possible that the botanist isn't suppose to easily take on a marauder though, or at the very least put minimal work in (inject iron into cryostasis uranium plants) to combat it?

2018-02-20 18:38 UTC, Rinoka commented
As people have pointed out, you can already do this with an injection of grinded iron (a thing a botanist can reasonably get). There's no real excuse for not having iron here; lacking iron does not prevent botany powergaming, it just makes it tedious.

I see no reason to complain about Steelcaps having iron, for that reason. Tediousness shouldn't be our last line of defense against powergaming behavior...

2018-02-20 18:47 UTC, ExcessiveUseOfCobblestone commented
Nor should you simply remove without adding difficulty elsewhere it when it does act as a balancing mechanic in practice.

2018-02-20 19:34 UTC, arsserpentarium commented
maybe lower iron production?

2018-02-20 19:49 UTC, DaedalusGame commented
METAL FOAM LEMONS

2018-02-20 19:58 UTC, arsserpentarium commented
gold solidification.

2018-02-20 21:01 UTC, ExcessiveUseOfCobblestone commented
Not doing something because it's tedious IS a practical balancing mechanic, just like taking ballistic over energy because you want on-the-fly recharge is a balance mechanic.

I'm not arguing it's a good one, i'm just arguing it is one.

2018-02-21 01:36 UTC, ThePainkiller commented
I just wanted to simplify the EMP fruit method for quick production, instead of having to inject 20u of Iron on every single uranium fruit for them to create an EMP pulse when thrown. EMP fruits **can** be produced still! My pr aims to eliminate the need to inject **all** your harvested fruits with a chemical that is not available on any fruit, yet easily obtainable by any other means, even moreso the one described in here: **_Steel Caps._**
You could cut Steel Caps into Metal Rods and grind them on botany's grinder to have Iron, wich then you inject into your plants. You can also scavenge the maint tunnels nearby for metal and rods, wrench down chairs around the station...Metal (and by proxy, Iron) is a readily available and easily obtainable resource, so I don't see what's the problem of simplifying a gimmick down to just having a fruit produce both components needed for an EMP pulse. Is it for "balance", because it takes two more steps to produce an EMP fruit that you can still recreate regardless of iron production or not?
The obtainability of iron directly tied to the steel caps (rods) is me trying to make sense of _"hey if you can get rods out of this and grind them to get the iron needed why not just simplify the steps and give the plant iron production?"_

2018-02-21 01:40 UTC, ThePainkiller commented
Cobby, so you're saying "if this mechanic is tedious enough to get people will be discouraged to use it so it will be used less"?
Have you seen how mass spammed chaplain monks were despite the fact you need to train for a fuckton of punches to get to the _three-hit-and-put-you-in-crit_ state? Or how people playing xenobio still try to reach for those rainbow slimes to ling themselves despite mutations being completely chance based?
Tedious never stopped anyone willing enough to get what they really wanted in the end, antag or not, and if it did then they didn't want it hard enough!

2018-02-21 06:56 UTC, Bawhoppen commented
It's about the principle

2018-02-21 13:57 UTC, ExcessiveUseOfCobblestone commented
Ah yes I can't count the amount of people that get ling nowadays, do epic golem/mob spam, or inject iron into all their fruit for emplemons or whatever.

And there's nothing wrong with getting the reward in the end, the "balance" is that you're more apt to just do something else.

Again, i'm not arguing it's GOOD balance, but it does act as a deterrent and should be accounted for rather than playing the "QoL" game.

2018-02-21 17:45 UTC, Cyberboss requested changes
:cl:

2018-02-21 20:21 UTC, optimumtact commented
power creep disguised as quality of life.

there's the door -> [ ]

2018-02-21 20:21 UTC, closed without merging

2018-02-21 21:51 UTC, ThePainkiller commented
"Power creep" even though you can still make emp fruits just that you have to manually inject the iron on them? I was not _enabling_ something that was previously impossible to reproduce, I was literally making the process _easier_, but alright oranges.

2018-02-21 22:19 UTC, Rinoka commented
Gotta agree with Painkiller on this one.

Difficult to access materials like Plasma, I would agree - they're power creep - but iron isn't hard to get.

Also, since apparently people don't understand this has downsides: I can grind up stuff I deconstruct to get some basic metal sheets to make iron. This isn't really hard.

If I want more iron than that, I have to make Steelcaps. This requires a source of mutagen, and if you don't have Mutagen Glowshrooms or a chem dispenser, then mutagen is a rarer resource you gotta beg chemistry for.

Most of the time, people don't make Steelcaps for that reason: mutagen is semi-rare if you don't produce mutagen plants first, and once you have mutagen plants it's still a pain to grow them if you don't NEED them.

In other words, this would add an additional step to creating your bomb-plants if you wanted to make EMP or foam objects, not even mentioning how an adept Botanist can make far more dangerous things.

This isn't a flat out Free Power Creep thing - Botany has enforced tedium in tending plants and letting them grow. I don't even think a round will last long enough for a ton of EMP plants to be used without a hypercompetent botanist, since that'd take:

Getting Separated Chems & Uranium (Glowberries - these require major luck to get early, and they're a huge mutagen sink.)

Getting Steelcaps' Iron

Getting the Mutagen needed for the above two things somehow (If you suck the chemist's dick, this can be very fast, or if you insist on going self-sufficient, you have to wait on a Blumpkin harvest, and then a Glowshroom harvest.)

Then, you have to wait on whatever you put it all in. They're also pretty weak without major potency buffs or going out of your way to get Concentrated Chems (mutating Beets).

If you wanna call it power creep, I have a question: are EMPs powerful enough that having more than 10 or so is just flat out power creep? Because I will admit I'm not familiar with EMP code, but I also feel like they wouldn't be so simple to make into grenades if they were objectively ridiculous.

2018-02-21 22:26 UTC, PKPenguin321 commented
Clicking a tray and getting 30 tomatos and throwing them to instantly make an EMP appear is much stronger than having to carry a syringe that can only carry 15u at a time and having to inject one tomato at a time to make an EMP. You are enabling mass EMPs with this. It *is* enabling, not just making easier.

2018-02-21 22:30 UTC, Rinoka commented
Uh...

Separated Chems works on injected chems, too, last I heard.

So you just take 1 pre-prepared tomato with Sep. Chems + Uranium, inject Iron, shove it in your bag. Rinse and repeat; you now have EMP grenade tomatoes.

My point is that this is already a feature and can be replicated without the Iron gene because you're not actually limited to doing the equivalent of carrying around a beaker of Uranium and dripping in 1u drops of iron or something, you can pre-prepare as many tomatoes as you want if you grind up enough iron.

2018-02-21 22:38 UTC, Rinoka commented
I honestly don't think you understand the common yields on these plants; I rarely see yields over 11, given that I'm not someone who tries to minmax yield or use stuff like the somatoray, so I'd be interested to learn how you propose I can get 30 per harvest.

Allowing plants like these would allow exponential harvests, but I also don't think most rounds last nearly long enough for these to kick into major gear. Not even mentioning that I'm not sure EMP plants compare to how utterly ridiculously broken Botany gets the further the round lasts. (Deathmix inject-on-hit onions spring to mind - I've been crit in seconds by those damn things.)

2018-02-21 22:44 UTC, ThePainkiller commented
1. The maximum yield possible is 10, going up to 13.2 with Robust Harvest (30% yield increase), if you know a way how to harvest 30 plants from a single harvest **PLEASE LET ME KNOW**
2. Getting production speed 1 to mass harvest 30 in less than a minute requires more mutagen in 2u doses and **luck**, wich like Rinoka said, more mutagen to spend
3. If your fruit has Separated Chemicals (wich it should), injecting Iron on it just gets it on the plant, but does not make it react. Granted, in this way it's superior to a yellow slime core injected with blood, but still requires a very rare trait wich is fucking Separated Chemicals. I've done this last night on a shift and got myself around 15 emp tomatoes along with tesla shock lemons, poisonous limes and nitroglycerin onions.
4. To make a full size EMP (size 1,3) on a 100 potency fruit (~25u Uranium) you need to inject at least 20u of Iron, and a syringe does 15u at a time, wich requires an extra manual draw+inject
5. Like Rinoka said, are 1,3 EMP's really **_that_** much of a threat? Do you fear that your rogue AI with borgificator and 8 connected borgs will no longer be a terrifying powertrip? Are EMP fruits more dangerous than what botany _can_ and **will** already mass-produce?

2018-02-21 22:48 UTC, ThePainkiller commented
@Rinoka I see you've been struck by the coniine/cyanide/carpotoxin/toxin/amanitin/amatoxin deathfruits, huh?~
I've gotten so much of those I had to get a second plant bag to carry them (30 mannitol laughing gaia, 30 poison limes, 30 explosive onions, 10 tesla shock lemons is my typical plant bag), yet people believe mass producing EMP's is a threat. Wew.

2018-02-21 22:54 UTC, Rinoka commented
Yeah, I've made some myself. There's a few, ah... things I don't think botany coders _expected_ (specifically, put Wheat's Perennial Growth on mushrooms for long grow time but 1 harvest per tick mushrooms - they're really the only thing I think could remotely achieve PK's estimated 30, but that has their own downsides: they take like a goddamn minute or two to grow, which makes them difficult to utilize if you can't start early)...

I don't think people realize the sheer breadth of what Botany can achieve; it's more a matter of "which tools did you make before you knew the round?" (since by the time you know what the round is, you probably don't have the time to make more of your given fruit.)

EMP grenades? Not bad for malf, but if the AI's on your side, they're just a liability.

Acid gas grenades? Great on blobs, but they tend to kill people; using them in crowded areas is asking for a B W O I N K.

So on, so forth. The big thing about this is that the perfect scenario would result in massive usability, but the perfect scenario basically never happens, so...

2018-02-21 23:24 UTC, ThePainkiller commented
Gas grenades are even more of a pain in the ass to get than 10% Teslium/Electrical Activity (because glowcaps have FUCKING FIXED 15 MATURATION SPEED) because it's either a random mutation you have to hunt for (or pray to the strange seeds gods) rather than _"mutate this plant with 2u of mutagen and get it if you're extremely lucky"_

2018-02-21 23:43 UTC, Rinoka commented
Gas can be made with Phosphorous, Potassium, and Sugar - you only need glowshrooms, bananas, and beets. Get separated chems + liquid chems? Bam, gas grenades.

It's actually very simple, and I don't recommend focusing too much on the potential for a strange seeds trait when you can make it with only Glowberries being your limiter.

2018-03-20 22:43 UTC, yorii commented
onions are already smoke grenades by their own unique code, you don't need to add any of the reagents to produce smoke.

2018-03-20 23:40 UTC, optimumtact commented
don't necropost yorii

2018-03-21 22:43 UTC, Rinoka commented
esp. not with info that's unhelpful

last i knew it only activates smokecode on slice, which makes most toxin or acid mixes completely nonviable for your average plant-chemist - they'd be at the center of the hellstorm.

since glowshrooms/bananas/beets are all accessible at roundstart anyway it's not like it's hard to do either lol

2019-02-23 16:43 UTC, habader commented
maybe this should be merged now that sep chems are gone

2019-03-17 01:59 UTC, ThePainkiller commented
I'm not saying this because it's my PR but Habader has a point
Now that separated chemicals are gone it beats the emp production (will still produce EMP's when harvesting though! But I can't imagine a Botanist dragging around an entire tray in space to harvest his EMP plant just to emp a rogue AI)
Also this 20% Iron trait could go perfect with an even better healing Gaia since Iron stimulates blood production and could help with heavy bloodloss as well
How do I re-open my PR?