Golden apples can now mutate into poison apples
tgstation/tgstation pull request #35821
Opened 2018-02-19 14:12 UTC by Buggy123

alternative to #35820
closes #35820

Having a unused item in the game is bad, but I thought I'd make a alternative PR that addresses the other possible solution (remove vs improve).

🆑 
tweak: Nanotrasen has... uh... I don't know, whatever. Golden apples can now mutate into poison apples.
IC changelogs are nice but I got 2 hours of sleep so fuck that.
/🆑

2018-02-19 14:13 UTC, vuonojenmustaturska commented
We don't actually want to put zombie powder in the hands of botany

2018-02-19 14:19 UTC, Buggy123 commented
I have basically never played botany in its current state and have no idea what is or isn't balanced.

2018-02-19 14:21 UTC, vuonojenmustaturska commented
zombie powder is what's in the sleepy pen

2018-02-19 14:23 UTC, ChangelingRain commented
what part of "really, really not something we'd want botany able to easily access" did you not understand?

2018-02-19 14:25 UTC, Buggy123 commented
No I know what it is, and what it does. It's a super-stun chem which puts you to sleep the instant it enters your system, metabolizes slowly, makes you appear to be dead(and thus draws less suspicion), and is mildly toxic. Shit's hilarious if you emag the chem dispenser and then load the smoke machine with it.

But in botany, I have no idea if getting this mutation takes 3 minutes or 30 minutes or 3000 minutes.

2018-02-19 14:29 UTC, Repukan commented
No, trying to punish a feature after mantainers say they don't want it in, is the real bad idea.

2018-02-19 14:30 UTC, vuonojenmustaturska commented
@Buggy123 all mutations are effectively roundstart, the only limiters are things like cannabis that don't always mutate into the thing you want and have a limited amount of seeds, two problems apples don't and won't have

2018-02-19 14:32 UTC, Buggy123 commented
Wait, Changelingrain is a maintainer?

Either way maintainer opinions differ massively so just because 1 maintainer hates this idea doesn't mean that others don't. I mean, have you _seen_ Goofball?

2018-02-19 14:35 UTC, Buggy123 commented
>@Buggy123 all mutations are effectively roundstart, the only limiters are things like cannabis that don't always mutate into the thing you want and have a limited amount of seeds, two problems apples don't and won't have

Oooooooohhhh...

Uh.

**_Well_**, might be wise to close this then.

I don't suppose decreasing the mutation chance would help at all? That seems to be a thing you can do.

2018-02-19 14:39 UTC, RandomMarine commented
Why not just give it a different toxin?

2018-02-19 14:40 UTC, 81Denton commented
I'm all for bringing back unused assets, but zombie powder is absolute nuts and makes all other KO chems look like a joke.

@vuonojenmustaturska Sleepypens have a snowflake version of chloral that kicks in later, but sleeps people for longer. Zombie powder is an instant KO + fake death

2018-02-19 14:41 UTC, Buggy123 commented
That's not a bad idea. The original toxin appears to have been cyanide so...

2018-02-19 14:43 UTC, Buggy123 commented
see title

2018-02-19 14:46 UTC, 81Denton commented
Looks solid to me. I don't see an issue balance wise since cyanide is mediocre compared to coniine/other toxins and can already be obtained through deathweed.

2018-02-19 14:50 UTC, Buggy123 commented
Would there be another poison which is better? I thought about initropidril because suddenly having a heart attack and keeling over sorta fits with the sleeping beauty theme but that might be too strong.

2018-02-19 14:57 UTC, vuonojenmustaturska commented
@Buggy123 the way mutations in botany work is that you get unstable mutagen from the chemist and apply it in 5u drops on the plant until it mutates. Each 5u drop has a 10% chance of mutating the plant to a species in the mutate list. Mutagen is a thing you should never be in short supply of, if you know what you're doing.

2018-02-19 14:57 UTC, 81Denton commented
Initropidril can kill extremely quickly if you're unlucky and get hit with a heart attack.
Chloralhydrate2/Delayed Chloral Hydrate could work, it's essentially a gimped version of chloral that takes twice as long to kick and and doesn't deal any tox damage.

2018-02-19 14:59 UTC, Buggy123 commented
Oh, really? That hasn't changed? Don't they get a gene machine thing and strange plants with random reagents and trait things and other shit?

2018-02-19 15:02 UTC, vuonojenmustaturska commented
yeah but the gene machine can't mutate into a different plant, it can only splice in traits and reagents from seeds you already have to seeds you already have

2018-02-19 15:03 UTC, 81Denton commented
@Buggy123 That sounds good, it would make it something unique instead of just adding a chemical that's weaker chloral.

2018-02-19 15:37 UTC, arsserpentarium commented
cyanide can be very easy accessable. Put there something more exotic, or add oxygen. To worth handle these apples.

2018-02-19 15:45 UTC, davethwave commented
"During our experimentation on gene manipulation on apple mutation to gold apples a new undiscovered variety of golden apple seems to be unlocked. In addition any nanotrasen employees in possession of or growing of said apple is now a major crime."

2018-02-19 15:57 UTC, DaedalusGame commented
selea, what are you talking about, there's no botany crop that makes cyanide and you need oxygen to make cyanide, which you by your own admission, can't get through botany

2018-02-19 15:59 UTC, Buggy123 commented
Well now it makes Kindleium instead.

2018-02-19 15:59 UTC, 81Denton commented
@DaedalusGame Poison berries have cyanide

2018-02-19 16:00 UTC, DaedalusGame commented
i thought they had coniine or someshit

2018-02-19 16:39 UTC, Buggy123 commented
>Given that this is gated behind 2 transformations it'd be nice if it were slightly more potent than just cyanide again, but I don't have any helpful suggestions.

I mean, it has kindleium instead of cyanide now, what do you think of that.

2018-02-19 16:42 UTC, 81Denton commented
You should probably update the title and shorten it a little

2018-02-19 16:44 UTC, arsserpentarium commented
I don't even know, what is kindlenium.What it supposed to do?

2018-02-19 16:49 UTC, Buggy123 commented
Its exactly like getting hit by kindle. It kindles you when it first enters your system, has a 5% chance to kindle you again at any point while its in your system and you aren't already kindled, and it removes the kindle when it exits your system.

2018-02-19 16:51 UTC, DaedalusGame commented
aka you just gave a clockcult special to botany why

2018-02-19 17:00 UTC, Buggy123 commented
Well, for one, same reason as Narsour: plausible deniability. Kindle has a distinctive sound and distinctive slurring effect. If you hear or see anything along those lines you immediately get ";CLOCK CULT", so clock cult rounds are basically 50% steamroll, 50% discovered immediately and then sodomized for 40 minutes by a long brass rod.

Admittedly its not quite as effective as Narsour, but its a positive, however small.

2018-02-19 17:06 UTC, DaedalusGame commented
weakness
no +1 from me

2018-02-19 17:07 UTC, Buggy123 commented
Weakness?

2018-02-19 17:10 UTC, JJRcop commented
Can you please shorten the PR title to "Golden apples mutate into poison apples, which have a new chem"?

2018-02-19 17:16 UTC, Buggy123 commented
Okay enough title memes

2018-02-19 17:27 UTC, arsserpentarium commented
How about neurotoxin,imprednezene,formaldehyde?

2018-02-19 17:37 UTC, Buggy123 commented
I dunno, @81Denton like kindleium, and @DaedalusGame doesn't support it apparently but won't say why. I'll wait and see what other people think.

2018-02-19 18:08 UTC, Buggy123 commented
Okay @FantasticFwoosh has given me some ideas. Plans for when I get to something that can run git/byond:

1: rename and possibly resprite to brass apples
2: replace nutriment, etc with metal
3: possibly put steam in them?

2018-02-19 18:20 UTC, arsserpentarium commented
1.Or put assort of neurotoxins to get brainkilling apples.
For most fun,gene engineer them to add earthsblood.to negate tox and max brain dmg.
2.brass apples needs enought work to be another possible mutation of gold apples.
copper
kindlenium
iron

2018-02-19 18:32 UTC, improvedname commented
except when botanists already can get carptoxin so zombie powder shouldnt be a issue besides its a reference lol

2018-02-19 18:39 UTC, arsserpentarium commented
That's for refference,yeah!why do you think,that people so mean?

2018-02-19 18:51 UTC, ExcessiveUseOfCobblestone commented
You know there's a machine literally dedicated to messing with the chemicals within a plant, right?

2018-02-19 18:52 UTC, arsserpentarium commented
But copper needs for refference.

2018-02-19 18:53 UTC, Kromgar commented
Botany being able to mass produce zombie powder could have 0 terrible consequences

2018-02-19 18:55 UTC, epochayur commented
what a pointless PR

2018-02-19 18:57 UTC, ExcessiveUseOfCobblestone commented
> Botany being able to mass produce zombie powder could have 0 terrible consequences

they already can @Kromgar ever since morphine became a producible recipe.

No one ever does it though.

2018-02-19 19:07 UTC, Iamgoofball commented on code/modules/hydroponics/grown/apple.dm
> -	reagents_add = list("zombiepowder" = 0.5, "vitamin" = 0.04, "nutriment" = 0.1)
ok so this kills the snow white joke

2018-02-19 19:09 UTC, Iamgoofball commented
yeah zombie powder isn't a concern anymore

plus removing zombie powder kills the joke about poison apples, did you ever see snow white

2018-02-19 19:13 UTC, Repukan commented
I don't watch Western anime

2018-02-19 19:39 UTC, Buggy123 commented
Okay, so, i'm thinking brass apples should be a new thing. Fuck it, back to normal

2018-02-19 19:40 UTC, Buggy123 commented
Gotta wait till I get home cause I dunno how to revert commits via web interface.

2018-02-19 20:02 UTC, arsserpentarium commented
please, add into poison apples neurotoxin and imprednezene.

2018-02-19 23:12 UTC, Kromgar commented
@ExcessiveUseOfCobblestone How? Don't you need carpotoxin?

2018-02-19 23:32 UTC, arsserpentarium commented
you have

2018-02-19 23:52 UTC, ExcessiveUseOfCobblestone commented
@Kromgar Botany can make carpotoxin

2018-02-20 01:07 UTC, newfren commented
The actual bottleneck for zombie powder for botany is actually copper. They could always get morphine from reishi.

2018-02-20 05:55 UTC, Kromgar commented
@ExcessiveUseOfCobblestone 

How the fuck does it even work?


WIRE IS MADE OF IRON AND GLASS HOW DO YOU GET COPPER FROM WIRES MADE OF IRON AND GLASS

2018-02-20 06:47 UTC, arsserpentarium commented
It uses alchemical transmutation.grinder changes configuration o spirits of fire to adjust influence of planets. so iron becomes copper.

2018-02-20 08:35 UTC, ShizCalev requested changes

2018-02-20 08:35 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/toxin/kindleium/kindle(M)
/proc, typecast

2018-02-20 08:35 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +/datum/reagent/kindleium //works like if you get hit by kindle
missing /toxin here

2018-02-20 14:33 UTC, ExcessiveUseOfCobblestone commented
@Kromgar idk im not a maintainer :^)

I have to break a few more things before I get that title!

2018-02-20 14:35 UTC, 81Denton commented
@Kromgar You can print wrapping paper from metal and glass. Spessmen have clearly developed universal constructors.

2018-02-20 20:30 UTC, Buggy123 commented
Making a new PR because this one is all over the place

2018-02-20 20:30 UTC, closed without merging