Makes new surgeries check for tool qualities
tgstation/tgstation pull request #35847
Opened 2018-02-20 16:04 UTC by ACCount12

Surgeries from #35520 now check tool types instead of tool paths. 

This PR also converts some surgery-related `attack_by` procs to `tool_act`.

Tag: code improvement.

2018-02-21 17:44 UTC, Cyberboss requested changes

2018-02-21 17:44 UTC, Cyberboss commented on code/modules/surgery/organs/autosurgeon.dm
> +		floorloc.contents += contents
```dm
var/atom/drop_loc = user.drop_location()
for(var/I in src)
    var/atom/movable/AM = I
    AM.forceMove(drop_loc)
```

2018-02-23 01:36 UTC, ACCount12 commented
@Cyberboss done

2018-02-24 05:08 UTC, ShizCalev commented
doesn't compile.

2018-02-24 06:01 UTC, Cyberboss approved these changes

2018-02-24 06:13 UTC, merged

2018-02-24 07:18 UTC, ACCount12 commented
@Cyberboss thanks for fixing it for me