Makes light fixtures actually glow in the dark while on (And adds the necessary groundwork for other above lighting plane stuff)
tgstation/tgstation pull request #35879
Opened 2018-02-21 21:50 UTC by deathride58

Title.

Before:
![dreamseeker_2018-02-21_16-44-11](https://user-images.githubusercontent.com/6356337/36507290-390ce8ae-1727-11e8-8077-1da1a57ce659.png)

After:
![dreamseeker_2018-02-21_16-33-29](https://user-images.githubusercontent.com/6356337/36507296-3e07bdde-1727-11e8-80aa-b3e1f569ed0f.png)

:cl: deathride58
add: Lights will now actually glow in the dark!
/:cl:

2018-02-21 21:51 UTC, DaedalusGame commented
this is unironically a good change

2018-02-21 22:01 UTC, Xhuis commented
*That* is cool. I can think of so many things that can use this!

2018-02-21 22:26 UTC, ChangelingRain commented
downside: anything using this will render above things that aren't using it, even if it shouldn't render above, such as megafauna/alien queens/other shit

2018-02-21 22:28 UTC, DaedalusGame commented
are you sure

2018-02-21 22:28 UTC, ChangelingRain commented
yes I've tried stuff like this before

2018-02-21 22:28 UTC, XDTM commented
Doesn't this mean they'll ignore colored lighting? Might look jarring in some cases.
Also, it seems that this is only really useful because of night dimming, since light emitters are already in lighted turfs anyway

2018-02-21 22:30 UTC, DaedalusGame commented
also technically it's possible to prevent this by adding a fullblack overlay at abovelightinglayer to... everything

2018-02-21 22:40 UTC, deathride58 commented
APCs, air alarms, fire alarms, airlocks, and various other machinery around the station could probably make use of the above lighting layer, as they're often in dimmed areas where their glowy bits end up getting darkened by the ambient lighting.

Light fixtures, and pretty much every other piece of machinery that could make use of the above lighting layer, are all almost always above most other objects. This means the oddities that occur when one object is above another object that has an above lighting overlay will hopefully be way too rare in actual gameplay to justify the memory impact of adding full-black overlays to every single object in the game.

2018-02-21 22:41 UTC, epochayur commented
at some point, I'd love to see this on anything with a backlit display, like APCs, request consoles, morgue lights, etc.

2018-02-21 22:41 UTC, XDTM commented
don't forget light colors; this means that even if there's a red floodlight in the room you'll see even the weakest lightbulbs in their normal color

2018-02-21 23:15 UTC, deathride58 commented
The issue with light overlays not being influenced by the room's lighting has been somewhat resolved via light overlays using the light's power for their alpha. Unfortunately, this will only apply during night shifts and on Citadel, due to the sparse usage of light sources with a light power below 1 in this codebase. I could probably decrease the min/max alpha values for light fixture overlays, though.

For the issue with light fixtures with non-standard colors suddenly having overlays that aren't influenced nearly as much by the light fixture's actual color, I could resolve this by making light overlays inherit their source's light color, but that'll have odd results for subtle, non-incandescent-like colors. Only way to resolve the issue with subtle colors looking odd with the light overlays would be to make light overlays greyscale, but that'll introduce the problem of lights losing their stylization, and will make light fixture overlay colors physically inaccurate in some cases, both of which are pretty big bags of worms that I'd rather not drown in.

2018-02-21 23:34 UTC, WJohn commented
Could you do this with computers, while you're at it?

2018-02-21 23:34 UTC, WJohn submitted a review, later dismissed

2018-02-22 00:15 UTC, Cyberboss requested changes

2018-02-22 00:23 UTC, Cyberboss commented on code/datums/mutable_appearance.dm
> +	var/mutable_appearance/MA = new(plane)
Didn't know that, forget me

2018-02-22 00:23 UTC, Cyberboss submitted a review, later dismissed

2018-02-22 01:06 UTC, deathride58 commented on code/datums/mutable_appearance.dm
> +	var/mutable_appearance/MA = new(plane)
Just tested, seems like the issue where mutable appearances can't have their plane set outside of a proc within the mutable appearance itself has been fixed!

2018-02-22 01:23 UTC, Cyberboss requested changes
[It's not gonna work out](https://github.com/tgstation/tgstation/search?utf8=%E2%9C%93&q=mutable_appearance+ma+%3D+new&type=). I'm certain those aren't all the cases either

2018-02-24 05:46 UTC, Cyberboss approved these changes

2018-02-24 05:46 UTC, merged