tabling people on brass tables makes a clanging sound
tgstation/tgstation pull request #35876
Opened 2018-02-21 20:46 UTC by Buggy123

@kevinz000

2018-02-21 21:44 UTC, Cyberboss requested changes

2018-02-21 21:44 UTC, Cyberboss commented on code/game/objects/structures/tables_racks.dm
> +	..()
. = ..()

2018-02-22 04:52 UTC, ShizCalev requested changes
still missing

2018-02-22 04:52 UTC, ShizCalev commented on code/game/objects/structures/tables_racks.dm
> +	.
= ..()

2018-02-22 20:31 UTC, merged

2018-02-22 22:50 UTC, Buggy123 commented
w e w