[s] Gee, it sure is boring around here. I wonder what the Syndicate is up to?
tgstation/tgstation pull request #35964
Opened 2018-02-25 05:08 UTC by Iamgoofball

My boy, this peace is what all true maintainers strive for.

:cl: Iamgoofball
add: adds a flying carpet to ride
/:cl:

2018-02-25 05:12 UTC, MrDoomBringer commented
>My boy, this peace is what all true maintainers strive for

u fokin wot you got the quote wrong goddamn its "this place" fuck

2018-02-25 05:29 UTC, Iamgoofball commented
no m8 he's talking about things being boring, the king replies that this PEACE is what all true heroes strive for, because peace is good

fucking let's hit the subtitles

2018-02-25 05:55 UTC, PKPenguin321 commented
this is really really funny, not just for the reference

2018-02-25 06:42 UTC, Buggy123 commented
> someone says goof would code a magic carpet if someone sprited it
 > hours later goof codes magic carpet

2018-02-25 08:04 UTC, Iamgoofball commented
someone asked me to make a magic carpet and I told adminss to tell OOC I'd do it if they made me sprites, then kor came up with the idea of "what if its a shuttle that blocks air movement"

2018-02-25 10:07 UTC, praisenarsie requested changes
mapmerge

2018-02-25 11:13 UTC, 81Denton commented
mah boi

2018-02-25 11:13 UTC, 81Denton commented
Can't wait for this thing to launch and fling 90% of the crew into space

2018-02-25 14:36 UTC, Ordonis commented
>Tfw a goofcode storm comes and and the PRs are actually entertaining and the titles vaguely relate to the code involved

2018-02-25 14:37 UTC, 81Denton commented
@Ordonis HMMMMM I wonder if there are some sort of elections going on right now

2018-02-25 16:57 UTC, ShizCalev requested changes

2018-02-25 16:57 UTC, ShizCalev commented on _maps/shuttles/emergency_carpet.dmm
> +"a" = (/turf/template_noop,/area/template_noop)
TGM.

https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#mapping-standards

2018-02-25 16:58 UTC, ShizCalev requested changes

2018-02-25 16:58 UTC, ShizCalev commented on _maps/shuttles/emergency_carpet.dmm
> +"e" = (/obj/docking_port/mobile/emergency{dheight = 0; dir = 2; dwidth = 9; name = "Magic Carpet"; width = 19},/turf/open/floor/carpet/magic,/area/shuttle/escape)
dheight = 0 is a dirty var.

2018-02-25 19:22 UTC, McBawbaggings commented on code/datums/shuttles.dm
> +	description = "Shadala, we're off!"
Isn't it "Squadala" though?

2018-02-25 19:28 UTC, Iamgoofball commented on _maps/shuttles/emergency_carpet.dmm
> +"a" = (/turf/template_noop,/area/template_noop)
Having python issues but will do

2018-02-27 17:19 UTC, Potato-Masher commented
Squadala, we're off!

2018-02-27 18:31 UTC, Armhulen commented on code/datums/shuttles.dm
> +	description = "Shadala, we're off!"
it is, he won't fix it >:(

2018-02-27 18:33 UTC, 81Denton commented on code/datums/shuttles.dm
> +	description = "Shadala, we're off!"
booo

2018-02-27 19:48 UTC, KorPhaeron commented
@iamgoofball

This needs to not throw people on liftoff

2018-02-27 20:17 UTC, Iamgoofball commented
i feel like that's part of the experience

wait didnt we already disable that

2018-02-27 20:20 UTC, JJRcop commented
I won't let #35963 be forgotten!

2018-02-27 21:01 UTC, KorPhaeron commented
@iamgoofball

The experience is gonna be people jostling during the flight if it just straight up kills everyone on launch admins will disable it

2018-02-27 21:29 UTC, ExcessiveUseOfCobblestone commented
only one can survive, kor...

2018-02-28 07:46 UTC, Iamgoofball commented
If only one can survive, I'm putting my money on Mr. Rodgers.

2018-02-28 23:32 UTC, MrDoomBringer commented
@Iamgoofball his sweater would probably be bloodstained tho

2018-03-02 00:34 UTC, optimumtact commented
dumb idea like the maker of the pr

2018-03-02 00:34 UTC, closed without merging

2018-03-03 06:08 UTC, Iamgoofball commented
my python is fucked and I cant mapmerge anyways