Standardises atmospherics' holding tanks' contents
tgstation/tgstation pull request #36002
Opened 2018-02-26 19:03 UTC by Anonmare

[Changelogs]: The gas tanks in atmospherics will now all hold a more uniform level of contents, and actually let you do something with the gases before they all get used up 5 minutes after roundstart, looking at you especially N2O.

:cl: 
tweak: Atmospherics' holding tanks now possess a more uniform amounts of contents.
/:cl:

[why]: This has annoyed me for a long time and I'm tired of waiting for someone else to do it.

2018-02-26 19:10 UTC, RandomMarine commented on code/game/turfs/simulated/floor/reinf_floor.dm
> +	initial_gas_mix = "o2=79000;n2=21000;TEMP=293.15"
These are backwards.

2018-02-26 19:53 UTC, Anonmare commented on code/game/turfs/simulated/floor/reinf_floor.dm
> +	initial_gas_mix = "o2=79000;n2=21000;TEMP=293.15"
Oh you're right, one moment

2018-02-26 22:02 UTC, Cyberboss requested changes

2018-02-26 22:02 UTC, Cyberboss commented on code/game/turfs/simulated/floor/reinf_floor.dm
> +	initial_gas_mix = "o2=21000;n2=79000;TEMP=293.15"
The proper ratio is 25 - 75

2018-02-26 22:07 UTC, 81Denton commented on code/game/turfs/simulated/floor/reinf_floor.dm
> +	initial_gas_mix = "o2=21000;n2=79000;TEMP=293.15"
Isn't it this instead?
>#define O2STANDARD				0.21	//percentage of oxygen in a normal mixture of air
>#define N2STANDARD				0.79	//same but for nitrogen

2018-02-26 22:45 UTC, Cyberboss approved these changes

2018-02-27 03:11 UTC, Anonmare commented on code/game/turfs/simulated/floor/reinf_floor.dm
> +	initial_gas_mix = "o2=21000;n2=79000;TEMP=293.15"
Proper air mix should be 21% O2/79% N2

2018-02-27 04:43 UTC, Poojawa commented
tbh, the air mix tank shouldn't have more in it. as it's something that should come as a penalty if atmosia's nonexistent or just fucking off.

the N2O being fixed is good though.

2018-02-27 12:03 UTC, DaedalusGame commented
this but unironically 
make the air tank contain as much air as N2O contained before the change henk

2018-03-04 21:30 UTC, ShizCalev requested changes
Gotta agree with the two above. Setting the air tank to max pressure will nullify the point of having all the other tanks to mix into it, since it will have -more- than enough contents to last forever.

Bringing the total pressure of /air tiles to 6000 (1260/4740) sounds like a good idea imo.

2018-03-04 22:47 UTC, duncathan commented
for starters this is WAY too much gas, why are you increasing it so much
also, we are not supposed to have the same amount of each gas. the obvious one is airmix which i hope i don't have to explain very much, but the gases other than o2/n2 are absolutely supposed to have less than those two gases. they're dangerous and not nearly as important as o2/n2. if players are actually running out of important gases within 5 minutes of roundstart then we can try to work out a better solution than this but this is a very shitty "fix"

2018-03-04 22:47 UTC, closed without merging

2018-03-04 23:59 UTC, Anonmare commented
@duncathan Then can I *at least* standardise the dangerous gases? N2O for one is significantly less than plasma and I don't see a good reason for it, the station is designed to be dangerous - hence why the plasma tank is ~2 pumps away from flooding distro

2018-03-05 20:26 UTC, duncathan commented
I'd be ok with bringing n2o up to like 30-50k, 6k is really low I'll agree, but I want there to be more plasma than the others