Medals now show the commendation text in the description.
tgstation/tgstation pull request #36020
Opened 2018-02-27 16:05 UTC by DaxDupont

[Changelogs]: 

:cl: Dax Dupont
add: Medals now show the commendation text in the description.
/:cl:

[why]: I mean it kinda makes sense and now you can see what people write on your medal as a commendation.

2018-02-27 19:00 UTC, Cyberboss requested changes

2018-02-27 19:00 UTC, Cyberboss commented on code/modules/clothing/under/accessories.dm
> +							desc += "<br>The inscription reads: [input] - [user]"
user.real_name

2018-02-27 20:07 UTC, DaxDupont commented on code/modules/clothing/under/accessories.dm
> +							desc += "<br>The inscription reads: [input] - [user]"
Done

2018-02-28 19:11 UTC, merged

2018-03-06 16:26 UTC, Tacolizard commented
but then you can't write ooc memes on them