why doesn't nukeops actually check required_enemies
tgstation/tgstation pull request #36056
Opened 2018-03-01 06:37 UTC by checkraisefold

this is causing problems on downstream like hippie (wow loneop every round) because in every other gamemode required_enemies is check in pre_setup, but I guess because nukeops is www.youtube.com/watch?v=yqdDB_tMtgA
it doesn't care

:cl: checkraisefold
fix: Nukeops properly checks the required amount of enemies for the gamemode! This should fix downstream problems.
/:cl:

2018-03-01 06:43 UTC, SpaceManiac commented
seems like this does the exact opposite of what you intend

2018-03-01 06:44 UTC, checkraisefold commented
ficksed @SpaceManiac

2018-03-01 06:53 UTC, kevinz000 commented
![image](https://user-images.githubusercontent.com/2003111/36830846-320ba0a0-1cda-11e8-96aa-c641a96f32e5.png)
I'm triggered.

2018-03-02 18:28 UTC, checkraisefold commented
i'm a rebel I can use the master branch nerd

2018-03-04 14:05 UTC, AnturK requested changes

2018-03-04 14:05 UTC, AnturK commented on code/game/gamemodes/nuclear/nuclear.dm
> +		message_admins("<span class='notice'> [n_agents] nuclear operative(s) were created!</span>")
This seems unnecessary it's nothing admins need to know immediately.

2018-03-12 04:03 UTC, checkraisefold commented
hey can this be reopened I wasn't checking it, will make changes

2018-03-12 06:49 UTC, duncathan commented
Sure thing

2018-03-12 09:35 UTC, merged