Syndie lavaland base: adds turret control panel, soap
tgstation/tgstation pull request #36486
Opened 2018-03-17 20:39 UTC by 81Denton

:cl: Denton
tweak: The lavaland Syndicate base has been outfitted with a turret control panel as well as one (1) bar of soap.
/:cl:

[why]: The control panel lets you disable turrets in case they fire at monkeys/bubblegum or you want to kill fauna yourself. Soap lets you clean the microwave so it doesn't explode.

2018-03-18 01:08 UTC, ShizCalev commented
@mapdiffbot

2018-03-18 01:31 UTC, Cyberboss commented
@MapDiffBot

2018-03-18 07:02 UTC, 81Denton commented
@mapdiffbot

2018-03-18 11:59 UTC, Cyberboss commented
@MapDiffBot

2018-03-18 18:34 UTC, Cyberboss commented
@MapDiffBot

2018-03-18 22:27 UTC, factoryman942 commented
poor slow mapdiffbot :(

2018-03-19 16:11 UTC, vuonojenmustaturska commented
@mapdiffbot

2018-03-19 22:13 UTC, ShizCalev requested changes

2018-03-19 22:13 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
> +	control_area = /area/ruin/unpowered/syndicate_lava_base;
this should be in quotes

2018-03-20 19:34 UTC, 81Denton commented
@ShizCalev Ok, I fixed the control_area and updated the PR desc.

2018-03-22 04:35 UTC, ShizCalev approved these changes

2018-03-22 04:35 UTC, merged