Lavaland cafe
tgstation/tgstation pull request #36519
Opened 2018-03-19 01:53 UTC by kevinz000

![image](https://user-images.githubusercontent.com/2003111/37574377-9d021f7c-2add-11e8-8031-1ec6b3c78980.png)

2018-03-19 01:54 UTC, ExcessiveUseOfCobblestone commented
Days without fetishist tricks: ~~1~~ 0

2018-03-19 01:54 UTC, kevinz000 commented
!(https://cdn.discordapp.com/attachments/317234835934674948/424169795911417856/unknown.png)

2018-03-19 01:59 UTC, 81Denton commented
And here I was gonna add a kitchen to the seed vault and call it the lavaland seed vault & snack bar

2018-03-19 02:29 UTC, MMMiracles commented
Don't you hate when you're at work setting questionably priced simple meals to hipsters when suddenly your workplace is transported to hell?

The clothing vendor in the back shows that the bistro is actually a front for the maid cafe so the space police wouldn't catch on.

2018-03-19 04:00 UTC, YakumoChen commented
I don't feel like this is going to see use outside of memes. Space bar wasn't a rousing success either.

2018-03-19 04:45 UTC, Repukan commented
Fetish content.

2018-03-19 04:45 UTC, Repukan commented
You stop this shit or I'm going to mix cyanide into your catnip

2018-03-19 05:56 UTC, Bawhoppen commented
Has far too much stuff in it. Not the most interesting mapping. No new original assets or features with it. 
Don't expect it to see much use in real rounds, either. 
Personally don't think we should add it.

2018-03-19 06:02 UTC, Wilchenx commented
In the dark year of 2018 even cafes are considered a fetish content.

2018-03-19 06:06 UTC, JStheguy commented
The only acceptable restaurants in the 26th century are dive bars and burger joints, anything else is heresy.

2018-03-19 06:07 UTC, Wilchenx commented
Thing is, you can make it a FANCY burger joint if you want to. Nothing in this is predefined

Like a great coder once said

YOU CAN DO ANYTHING

2018-03-19 06:22 UTC, Shadowflame909 commented
I want a clown themed cafe or McDonald's! McDonald's! McDonald's!!!!

2018-03-19 06:22 UTC, Wilchenx commented
We have food at home

2018-03-19 06:23 UTC, Tlaltecuhtli commented
slippery slope

2018-03-19 06:23 UTC, Repukan commented
*Drives into drive thru*
*Orders a black coffee, no sugar*
*Drive out*

2018-03-19 06:23 UTC, Shadowflame909 commented
You respond very fast

On Sun, Mar 18, 2018, 11:22 PM Wilchenx <notifications@github.com> wrote:

> We have food at home
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/36519#issuecomment-374112425>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3meRyorEyutSihDvsbhWz9UYKMig43ks5tf06qgaJpZM4SvfRY>
> .
>

2018-03-19 06:25 UTC, Wilchenx commented
@Tlaltecuhtli point where did you see slippery slope, we've been trying to catch him for years.

2018-03-19 06:33 UTC, myonn commented
everything can and will be a fetish.

someone out there definitely has a thing for cafes transported to hellscapes, and I'm starting to connect the dots between that and a possible insecurity in repukan

2018-03-19 06:35 UTC, Repukan commented
Let's close a PR for being fetish material and then reopen it but still add a way for whatever made it a fetish thing in the first place to still be accessible so I can put my dumb fetish into the game but uh oh bucko I didn't really make them spawn as maids so if they get the uniforms from the conveniently placed custome vendor it ain't me on yeah :^)

2018-03-19 06:36 UTC, Wilchenx commented
You can PR removal of costume vendors to eradicate all fetishes alltogether if that really bothers you.

2018-03-19 06:45 UTC, Shadowflame909 commented
Cat girl ears with a maid costume. I uh..... Well there's more then one
costume choice. I hope for the best.

On Sun, Mar 18, 2018, 11:36 PM Wilchenx <notifications@github.com> wrote:

> You can PR removal of costume vendors to eradicate all fetishes
> alltogether if that really bothers you.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/36519#issuecomment-374114490>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3meY6ZFebKnsutL2F2gt2LgoCaM53cks5tf1H1gaJpZM4SvfRY>
> .
>

2018-03-19 07:05 UTC, kevinz000 commented
yell at wilchen/shezza about design issues i'm just coding and pring this for them because they're a lazy cat

2018-03-19 09:42 UTC, arsserpentarium commented
Where did you find fetish content?
I didn't.

2018-03-19 09:45 UTC, arsserpentarium commented
If you are talking about maids and catgirls, maids is needed profession in cafe.
Ca/tg/irls is part of TG culture. I don't like them very much myself, but it's part of local colorite and tradition.

2018-03-19 10:12 UTC, GuyonBroadway commented
Why does a cafe have a botanical garden, protolathe and engineering vendors?

No other lavaland ruin gives you that much stuff besides free golems and they have to harvest thier own stuff to do anything.

Also ca/tg/ays are only a nu-tg thing.

2018-03-19 10:14 UTC, Wilchenx commented
@GuyonBroadway because if something gets fucked you can then replace it using materials from botany, you are not supposed to leave the ruin anyway so it doesn't really matter.

2018-03-19 10:21 UTC, GuyonBroadway commented
Yeah but all they need is a toolbox and a few sheets of metal, glass and wood. The beach bums don't get this much stuff, the animal hospital doesnt get this much stuff, the space hotel doesn't get this much stuff.  Heck the space hotel doesn't even get thier own hydroponics bay and considering they are more likely to get visitors that just goes to show how much stuff is crammed into one single lavaland outpost.

2018-03-19 10:29 UTC, Tlaltecuhtli commented
whole point of those spawns was to learn specific jobs so they required adv tech shit

2018-03-19 10:30 UTC, Wilchenx commented
Yeah the whole point of this is to mess around with food and have fun.

2018-03-19 14:15 UTC, AlexTheSysop42 commented
“Curiously enough, the only thing that went through the mind of the bowl of petunias as it fell was Oh no, not again. Many people have speculated that if we knew exactly why the bowl of petunias had thought that we would know a lot more about the nature of the Universe than we do now.”

2018-03-19 15:20 UTC, praisenarsie commented
this is just powercreep ad infinitium to a shitty ruin that people will only play for like 2 days and no one is going to be down there anyway unless miners place a teleporter.

in fact it's a shitty reskin of the abandoned station & derelict

2018-03-19 15:25 UTC, praisenarsie commented
> Thing is, you can make it a FANCY burger joint if you want to. Nothing in this is predefined
>
>Like a great coder once said
>
>YOU CAN DO ANYTHING

then what's wrong with spending like 15 minutes renovating the bar on the station into a cafe.

2018-03-19 16:19 UTC, Wilchenx commented
>in fact it's a shitty reskin of the abandoned station & derelict

[citation needed]

2018-03-19 19:40 UTC, KorPhaeron commented
I had vague plans to make a Restaurant At The End Of The World that was a space ship that landed in apocalyptic areas and had some ghost role patrons of various backgrounds/bartender/a way to let the mining shuttle land there and you should do that instead because Hitchhikers Guide is better than maid cafes

2018-03-19 19:40 UTC, KorPhaeron commented
Also it provides a reason why there is a fucking resturaunt in the hellscape

2018-03-19 19:41 UTC, Wilchenx commented
@KorPhaeron we never questioned beach biodome

2018-03-19 20:01 UTC, Shadowflame909 commented
These guys should be trained in the art of plasma fist. So they can defend
against the eventual ash lizard vs catgirl struggle. Or when the ash
lizards bring bubblegum to the cafe.

On Mon, Mar 19, 2018, 12:41 PM Wilchenx <notifications@github.com> wrote:

> @KorPhaeron <https://github.com/korphaeron> we never questioned beach
> biodome
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/36519#issuecomment-374343662>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3meQhOHPPATcwd0voNV6boafNZ7h37ks5tgAndgaJpZM4SvfRY>
> .
>

2018-03-19 20:02 UTC, Wilchenx commented
@Shadowflame909 or they can powergame botany or die trying.

2018-03-19 20:57 UTC, Qustinnus commented
@kevinz000 lol isn't this the type of shit you condemn goof for? "shit PR A was denied so I'll just make shit PR B which is really shit PR A in disguise"

2018-03-19 21:00 UTC, Wilchenx commented
@Qustinnus i've talked to the maintainer that closed the PR
![image](https://user-images.githubusercontent.com/25509881/37621946-b9986a4a-2bc0-11e8-999b-ed428555ea25.png)
In case you've only read the title and saw the opportunity to shitpost i'm reposting the crucial information why this pr is open.

2018-03-19 21:02 UTC, Shadowflame909 commented
This is still catgirl maids though. Just with more disguises. If erp gets
enabled this rune will be a leaf hotspot for it. Honk

On Mon, Mar 19, 2018, 2:00 PM Wilchenx <notifications@github.com> wrote:

> @Qustinnus <https://github.com/qustinnus> i've talked to the maintainer
> that closed the PR
> [image: image]
> <https://user-images.githubusercontent.com/25509881/37621946-b9986a4a-2bc0-11e8-999b-ed428555ea25.png>
> In case you've only read the title and saw the opportunity to shitpost i'm
> reposting the crucial information why this pr is open.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/36519#issuecomment-374374781>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3mefHTFJiNg0YFgc8pPRTlToVf4Tnfks5tgBxggaJpZM4SvfRY>
> .
>

2018-03-19 21:02 UTC, Wilchenx commented
They were never catgirls in the first place.

2018-03-19 21:06 UTC, Shadowflame909 commented
Aren't there cat ears in the vendor?

2018-03-19 21:06 UTC, Wilchenx commented
There's also a cow in the pen.

2018-03-19 21:15 UTC, Shadowflame909 commented
If this does get merged first thing I'm doing is stealing the bananium tiles from the clown planet rune and turning this cafe into a clown themed one. Another idea is having an arcade machine in the cafe and taking the toy space suits and the space tiles and having a space themed version. add an arcade kevinz. Do it.

2018-03-19 22:09 UTC, Qustinnus commented
@Wilchenx I read the PR and it only added the extra step of making you walk to a vendor

2018-03-19 23:22 UTC, kevinz000 commented
honestly kor's idea sounds better but i promised wilchen so whatever i'll code that after regardless

2018-03-20 00:35 UTC, sawrge commented
if if's and but's were big fat nuts i'd have popped about a hundred

2018-03-20 02:03 UTC, ShizCalev requested changes

2018-03-20 02:03 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_lavaland_cafe.dmm
> +	req_access_txt = "0";
dv

2018-03-20 02:03 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_lavaland_cafe.dmm
> +	pixel_y = 0
dv

2018-03-20 02:03 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_lavaland_cafe.dmm
> +	req_access_txt = "0"
dv

2018-03-20 02:03 UTC, ShizCalev commented on _maps/RandomRuins/LavaRuins/lavaland_surface_lavaland_cafe.dmm
> +	pixel_y = 0
dv

2018-03-20 09:08 UTC, improvedname commented
What worries me the whole structure is made out of wood and paper on a lava filled plaaanet

2018-03-20 11:00 UTC, GuyonBroadway commented
Careful now, if you use logic you might upset the weeaboos and thier glorious folded a thousand times nippon paper houses.

2018-03-20 11:31 UTC, kevinz000 commented
@Wilchenx fix your map

2018-03-20 13:21 UTC, sawrge commented
>tfw you walk into burger king and pop a half chub because your fetish is restaurants

2018-03-20 14:30 UTC, Qustinnus commented
Knowing you you probably spotted the ballpit full of kids tbf @sawrge

2018-03-20 14:55 UTC, Bawhoppen commented
Keep drama out. Github is only for serious business.

2018-03-20 15:15 UTC, ExcessiveUseOfCobblestone commented
@Qustinnus not illegal when he's 15 tbf

2018-03-20 17:09 UTC, 81Denton commented
- 4 (four) autodrobe resupply canisters so you can get kitty ears for the whole metagang BUT
- no shaker or bartending book
- no universal enzyme or a cookbook, no oil for the deep frier, no soap so the microwave doesn't explode
- no spare candles
- an autolathe but no materials to feed it with
- engivend has req_access_txt "11", meaning staff can't use it (or even hack it due to lack of multitool)
- a single beaker for all of botany, with no available mutagen to give chefs exotic ingredients
- wooden walls and paper windows, yet no wood for repairs or anything atmos related to repressurize, so staff and patrons don't suffocate when something punches a hole in the wall

cum on wilch you can do better

2018-03-20 17:36 UTC, AlexTheSysop42 commented
>4 (four) autodrobe resupply canisters so you can get kitty ears for the whole metagang

Maid outfits too, don't forget that

>no shaker

Might be in the bar vendor, not sure though.

>an autolathe but no materials to feed it with
engivend has req_access_txt "11", meaning staff can't use it (or even hack it due to lack of multitool)

You can probably use some spare tools from the vendor for a multitool and a bit of mats from the autolathe, but you still shouldn't have to scrounge up mats in what's supposed to be a well-stocked cafe.

>a single beaker for all of botany, with no available mutagen to give chefs exotic ingredients

Bottles can be made from the biogen and a competent botanist can use the chlorine gene from the blumpkin seeds with glowshrooms to get mutagen. It's pretty low-effort to just add some blumpkin seeds though, and shows that the botany area was added as an afterthought.

>no universal enzyme or a cookbook, no oil for the deep frier, no soap so the microwave doesn't explode

That makes the cafe part fairly useless, and clearly shows that it wasn't the main thing the author was thinking of. 

In general, nothing seems to be planned out very well except for the autodrobe restockers. This is definitely thinly-veiled fetish bait, and removing the starting maid costumes doesn't matter when someone can just get one from a vending machine.

2018-03-20 17:37 UTC, Wilchenx commented
@81Denton this was made before cooking oil, added some
botany has blumpkins seeds from get go so mutagen is given for very little work
autolathe has materials now
engivend and other vendors removed because there's autolathe with materials
added one more beaker to botany, more can be made in autolathe
wood can be grown, steel can be grown too
made some atmos system that steals air from lavaland
spare candles added

2018-03-20 17:40 UTC, AlexTheSysop42 commented
You still haven't addressed the restocking units or the universal enzyme

2018-03-20 17:40 UTC, Wilchenx commented
@AlexTheSysop42 restock canisters were added so players can decide on a gimmick if they want to and so everyone can follow it.

2018-03-20 17:40 UTC, Qustinnus commented
mate i'm 100% sure if I open this map I'll find catears everywhere.

2018-03-20 17:41 UTC, Wilchenx commented
@Qustinnus wanna bet 5$?

2018-03-20 17:43 UTC, AlexTheSysop42 commented
>so players can decide on a gimmick if they want to and so everyone can follow it

like catmaids

Also, that seems fairly thoroughly thought out compared to the lack of enzyme, only proving my point.

2018-03-20 17:43 UTC, arsserpentarium commented
For guys, who are angry about maid outfit:did you know, that maid outfit isn't fetish content at first place,but formal uniform, used by workers of certain profession.
Guess, what is this profession and where do they work.

2018-03-20 17:45 UTC, Wilchenx commented
@AlexTheSysop42 
![image](https://user-images.githubusercontent.com/25509881/37672642-b2c248cc-2c6e-11e8-9dd1-ee9c20778dca.png)
here's your enzyme, i gathered some while you were salivating

2018-03-20 17:45 UTC, AlexTheSysop42 commented
Yes, people do use it to work, but it's also fetish content; that was established in the original PR and the "lack" of it is why this one is under consideration

2018-03-20 17:46 UTC, Wilchenx commented
Now please stop trying to cause shitstorm and let me finish pipes so we can update the map

2018-03-20 17:48 UTC, AlexTheSysop42 commented
I'm making such a big deal over the enzyme because it's one of the key ingredients in almost anything a kitchen would make, and you _somehow_ forgot about that.

2018-03-20 17:48 UTC, Wilchenx commented
I forgot to add it to the comment my friend, i never forgot about it.

2018-03-20 17:48 UTC, Wilchenx commented
Well i did sort of.

2018-03-20 17:49 UTC, arsserpentarium commented
If you aren't afraid for your sanity, give me any map and I'll find there fetish content.

2018-03-20 17:51 UTC, ExcessiveUseOfCobblestone commented
2 showers for a 1-person bathroom certainly raises the question....

2018-03-20 17:52 UTC, Wilchenx commented
@ExcessiveUseOfCobblestone people shower in clothes anyway

2018-03-20 17:56 UTC, AlexTheSysop42 commented
Even ignoring the fetish content, no one's even going to use the cafe. Just look at the beach bum ruin, how often does someone become a beach bum, stay in the biodome, and not commit suicide less than 5 minutes afterwards? In addition, it doesn't fit the theme of lavaland at all and (when you count the hydroponics area and tool vendors/lathe) doesn't have as much specialization as it should.

2018-03-20 17:59 UTC, Wilchenx commented
Ruins that leave players to their own creativity like free golems and seed vault are often used to make fun things, I hope this one will provide similiar source of fun for players.

2018-03-20 18:03 UTC, Wilchenx commented
The types of players that I expect to have fun from this ruin are mainly service departament players, so I added every service departament to the ruin.

2018-03-20 18:04 UTC, Wilchenx commented
Well except janitors, because janitors are fetish content.

2018-03-20 18:08 UTC, AlexTheSysop42 commented
I'd be a lot more fine with this if the autodrobe had cat ears/maid outfits VV'd out and the chef had some kind of ingredient orderer (this _is_ a cafe, cafes don't normally grow ingredients)

2018-03-20 18:09 UTC, Wilchenx commented
I don't think I need to cater to you if you're not the kind of player that would use this ruin.

2018-03-20 18:11 UTC, AlexTheSysop42 commented
>janitors are fetish content

![what](https://user-images.githubusercontent.com/25281214/37674137-7ec8f780-2c48-11e8-9db9-28e2d1bcac0c.png)

2018-03-20 18:11 UTC, Wilchenx commented
![image](https://user-images.githubusercontent.com/25509881/37674180-883fd4b2-2c72-11e8-9f65-4d1912ce8bf6.png)

2018-03-20 18:12 UTC, ExcessiveUseOfCobblestone commented
The kind of players that use this ruin..

Like space bar ruin...
Space hotel ruin...
Beach bar ruin?

2018-03-20 18:12 UTC, AlexTheSysop42 commented
>you're not the kind of player that would use this ruin

I'm trying to keep a half-baked, potentially unbalanced/incomplete ruin from being added to the game and crowding out other ruins.

2018-03-20 18:13 UTC, Wilchenx commented
>I'm trying to keep a half-baked

Don't worry there will be plenty of baking!

2018-03-20 18:16 UTC, Shadowflame909 commented
Kek this rune already exists/existed 3 other times. I'm not sure cat ears
are enough to keep it from disappearing again. But a mime sleeper outta
work. Fake wall memes.

On Mar 20, 2018 11:13 AM, "Wilchenx" <notifications@github.com> wrote:

I'm trying to keep a half-baked

Don't worry there will be plenty of baking!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/36519#issuecomment-374702416>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/Ab3meSmzV84yuFjUel4z3r7UK0Zen9ttks5tgUbagaJpZM4SvfRY>
.

2018-03-20 18:31 UTC, 81Denton commented
@Wilchenx I'd probably divide the ruin into multiple areas with their own air alarms so the place can repressurize properly.

2018-03-20 23:22 UTC, ShizCalev approved these changes

2018-03-22 04:33 UTC, ninjanomnom commented
This just isn't interesting enough or worth adding to lavaland, cluttered as it is. No one on the team seems interested in it either.

2018-03-22 04:34 UTC, closed without merging

2018-03-22 05:08 UTC, Iamgoofball commented
@ExcessiveUseOfCobblestone it is at a federal and most state level