Pubbystation: makes evac location more obvious
tgstation/tgstation pull request #36528
Opened 2018-03-19 12:51 UTC by 81Denton

:cl: Denton
tweak: Pubbystation's sign to evac have been made more obvious.
/:cl:

![evac signs yeah](https://user-images.githubusercontent.com/32391752/37596303-04137a96-2b7c-11e8-8330-5e36edf20cb6.JPG)

This PR makes Pubby's signs to evac more obvious for people who can't escape good yeah
Adds a few of the small ones (botany, bridge, near brig) and a big one right at the escape airlock, 50 hours in notepad

2018-03-19 12:51 UTC, 81Denton commented
@mapdiffbot You can do it, we all believe in you!

2018-03-19 14:22 UTC, 81Denton commented
@mapdiffbot

2018-03-19 15:33 UTC, Cyberboss commented
@MapDiffBot

2018-03-19 15:43 UTC, Cyberboss commented
@MapDiffBot

2018-03-19 18:15 UTC, Cyberboss commented
@MapDiffBot

2018-03-19 18:18 UTC, 81Denton commented
Poor thing

2018-03-19 19:25 UTC, Cyberboss commented
@MapDiffBot

2018-03-19 19:28 UTC, Cyberboss commented
@MapDiffBot

2018-03-19 19:40 UTC, ExcessiveUseOfCobblestone commented
I thought it said closing and I was like "finally..."

2018-03-19 19:42 UTC, 81Denton commented
![wgrefdwfe](https://user-images.githubusercontent.com/32391752/37618267-0873b97c-2bb6-11e8-832e-a281df89c565.JPG)

2018-03-19 20:30 UTC, Jalleo commented
@MapDiffBot

2018-03-20 22:00 UTC, ShizCalev requested changes

2018-03-20 22:00 UTC, ShizCalev commented on _maps/map_files/PubbyStation/PubbyStation.dmm
> +	icon_state = "direction_evac";
dv

2018-03-20 22:00 UTC, ShizCalev commented on _maps/map_files/PubbyStation/PubbyStation.dmm
> +	icon_state = "direction_evac";
dv

2018-03-22 12:29 UTC, 81Denton commented
@mapdiffbot

2018-03-22 12:30 UTC, 81Denton commented
@ShizCalev I thought I fixed this ages ago. Should be good now.

2018-03-22 23:39 UTC, Cyberboss commented
@MapDiffBot

2018-03-24 11:26 UTC, 81Denton commented
Sorry about that, let me fix the issue.

2018-03-24 11:27 UTC, ShizCalev commented
oh gawd

2018-03-24 11:42 UTC, 81Denton commented
OK shoot me if I ever force push again

2018-03-24 12:14 UTC, Jordie0608 commented
You have summoned the dark council.

2018-03-24 19:47 UTC, 81Denton commented
@mapdiffbot

2018-03-26 15:54 UTC, 81Denton commented
@mapdiffbot

2018-03-26 19:24 UTC, Cyberboss commented
@MapDiffBot

2018-03-27 02:38 UTC, merged