Fixes cells being deleted from chem dispensers on deconstruction
tgstation/tgstation pull request #36589
Opened 2018-03-20 23:23 UTC by GLACoding

2018-03-20 23:26 UTC, Cyberboss requested changes
This just moves the cell to nullspace where it'll at best be garbage collected and at worst hang around forever. Do what the beaker does and forceMove it to the drop_location() before nulling it

2018-03-20 23:38 UTC, GLACoding commented
Cell is dropped as part of component_parts though

2018-03-21 01:10 UTC, Cyberboss approved these changes

2018-03-22 03:03 UTC, ShizCalev commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	cell = null
if(!QDELETED(cell))

2018-03-22 04:29 UTC, merged