Plastic flaps are now airtight
tgstation/tgstation pull request #36659
Opened 2018-03-23 16:41 UTC by 81Denton

:cl: Denton
tweak: Plastic flaps are now airtight.
/:cl:

Right now, some maps (for example Delta) atmos connect huge areas through plastic flaps. 
You break a window in room A and can basically hear the CPU screech as it updates room A, corridors B, C, and D as well as the connected rooms.

An alternative solution would be adding windoors in front of plastic flaps, like how it's done on Boxstation.

What do you think?

2018-03-23 17:28 UTC, Supermichael777 commented
plastic flaps were a hand-wave for mule-bots.  I see mulebots used a lot less these days.  Their outdated with disposal shipping.  their vulnerable to interception, slow, and limited in scale.

2018-03-23 17:34 UTC, Iatots commented
Nobody uses disposal for delivery either.

2018-03-23 17:55 UTC, Rinoka commented
People use disposals more than mulebots; disposals are faster, simpler, and don't require pulling up a clunky interface with low control when you can generally trust disposals to function for your needs, especially since a failed delivery for whatever reason will just end up at your door again.

As it is, flaps are nice, but they really don't need to allow airflow.

2018-03-23 18:12 UTC, chesse20 commented
ad this please :)

2018-03-23 18:35 UTC, Cyberboss requested changes

2018-03-23 18:35 UTC, Cyberboss commented on code/game/objects/structures/plasticflaps.dm
> +	CanAtmosPass = ATMOS_PASS_NO
above `state` please

2018-03-23 18:35 UTC, Cyberboss commented on code/game/objects/structures/plasticflaps.dm
>  	. = ..()
```dm
/obj/structure/plasticflaps/Initialize()
 	. = ..()
 	air_update_turf(TRUE)
```

2018-03-23 19:24 UTC, nicbn commented
Windoors please

2018-03-23 19:50 UTC, Cyberboss commented
Pretty sure windoors are already air tight

2018-03-23 19:50 UTC, Cyberboss approved these changes
To whomever merges this, add flaps to the "Resprite Needed" project

2018-03-23 21:16 UTC, nicbn commented
I'm asking him to put windoors in the maps instead of making the flaps airtight.

2018-03-23 23:25 UTC, Cyberboss commented
@MapDiffBot

2018-03-24 16:57 UTC, ExcessiveUseOfCobblestone commented
There's balance implications here but idt they should be an issue.

2018-03-24 20:11 UTC, Rinoka commented
really the only balance change i can think of is that this might make a personal glitch I kind of enjoy (using air canisters to slide under flaps) just trap you instead

but that requires several things to make happen so

2018-03-25 03:01 UTC, merged