Replaces sniper bullets ex_act with bonus obj damage
tgstation/tgstation pull request #36715
Opened 2018-03-25 16:12 UTC by XDTM

:cl: XDTM
fix: Sniper rifles will no longer oneshot mechs (although they still deal high damage).
fix: Sniper rifles no longer knock down walls they hit.
/:cl:

Fixes #34761

2018-03-25 16:13 UTC, XDTM commented
Tbh the bonus damage could probably be removed altogether, i'm pretty sure it was there because obj damage wasn't in the game yet.

2018-03-25 16:33 UTC, YPOQ commented
I think it was ex_act so that the bullets could destroy walls. Similar to pulse beams/swarmer attacks.

2018-03-25 16:36 UTC, XDTM commented
Why would a sniper rifle knock down walls, though? I can understand piercing through them, and we have specialized bullets for that, but currently they just blow the wall up and stop there.

2018-03-25 20:27 UTC, Rinoka commented
I think it was because the ones with that function are like, on the level/design of anti material rifles lol

2018-03-25 22:51 UTC, Poojawa commented
It'd make more sense to give them X-ray like wall penetration that chops down their viable force

2018-03-26 19:19 UTC, Cyberboss requested changes

2018-03-26 19:19 UTC, Cyberboss commented on code/modules/projectiles/projectile/bullets/sniper.dm
> +		if(isobj(target))
condense ifs

2018-03-26 22:17 UTC, merged