Get_Flat_Human_Icon no longer draws asses that nobody wants
tgstation/tgstation pull request #36781
Opened 2018-03-28 18:55 UTC by Robustin

Get_Flat_Human_Icon (and manifest inject, which calls it) is probably the most expensive procs per call we have. 

In part because it creates an icon for a real human bean from scratch for all 4 directions.

Only imaginary friends used all 4, manifest inject only needs 2 directions and cult (sac image) only needs one.

2018-03-28 19:40 UTC, demonfiren commented
doesn't have anything to do with actual asses/10

2018-03-28 20:55 UTC, Cyberboss submitted a review, later dismissed

2018-03-30 16:16 UTC, Cyberboss requested changes

2018-03-30 16:16 UTC, Cyberboss commented on code/__HELPERS/icons.dm
> +/proc/get_flat_human_icon(icon_id, datum/job/J, datum/preferences/prefs, dummy_key, showDirs = list(NORTH, SOUTH, EAST, WEST))
`showDirs = GLOB.cardinal_dirs` or whatever the list is called

2018-03-31 04:01 UTC, Cyberboss approved these changes

2018-03-31 04:02 UTC, merged