Sender of PDA messages is told when their message is sent
tgstation/tgstation pull request #37055
Opened 2018-04-08 12:32 UTC by JohnGinnane

Mostly a quality of life thing. I wasn't sure of sending messages from the backpack worked

Screenshot:
![image](https://user-images.githubusercontent.com/3355198/38467499-4dbb5ab4-3b31-11e8-8555-b8cb70b4aeb3.png)

:cl: JohnGinnane
add: PDA messages you send are now displayed in the chat for your confirmation

2018-04-08 12:34 UTC, DaxDupont commented
This is a bad idea for the lawyer/captain send to all PDA message function.

2018-04-08 12:40 UTC, JohnGinnane commented
I didn't even know he could do that, that's neat. I'll look into making it a single line in both cases

2018-04-08 12:44 UTC, JohnGinnane commented
Turns out to be okay (I know there's only one recipient, but this would mean ghosts also get spammed which I don't think happens?)

![image](https://user-images.githubusercontent.com/3355198/38467598-f4f19ebe-3b32-11e8-9eac-49f00b6ad3ef.png)

2018-04-08 14:09 UTC, DaxDupont commented
Oh if it already filters to everyone its fine

2018-04-09 16:54 UTC, cyclowns commented
vv good

2018-04-10 22:16 UTC, ShizCalev requested changes

2018-04-10 22:16 UTC, ShizCalev commented on code/game/objects/items/devices/PDA/PDA.dm
> +	to_chat(user, "Message sent to [target_text]: \"[message]\"")
to_chat(user, "<span class='info'>Message sent to [target_text]: \"[message]\"</span>")

2018-04-14 21:13 UTC, JohnGinnane commented
@ShizCalev that'd one

2018-04-14 21:13 UTC, merged