sucessfully fixes some grammar
tgstation/tgstation pull request #37095
Opened 2018-04-10 07:37 UTC by Tlaltecuhtli

🆑
grammar:fix
/:cl:

2018-04-10 07:39 UTC, RandomMarine commented
Achktuhally this is a spelling fix and not a grammar fix.

2018-04-10 14:31 UTC, KorPhaeron commented
why in gods name would you make a changeling that just says "fix" for a typo

2018-04-10 14:38 UTC, ExcessiveUseOfCobblestone commented
I height this pr.

2018-04-10 14:43 UTC, Tlaltecuhtli commented
muh gbp

2018-04-10 14:47 UTC, ExcessiveUseOfCobblestone commented
g/f are 0 anyways sweetie

2018-04-10 17:51 UTC, XDTM commented
>why in gods name would you make a changeling that just says "fix" for a typo

New changeling rework?

2018-04-10 17:58 UTC, ExcessiveUseOfCobblestone commented
Changelings were a mistake, why do we need to tell them every little thing that changes within the cod?

2018-04-10 20:38 UTC, ShizCalev requested changes

2018-04-10 20:38 UTC, ShizCalev commented on code/modules/clothing/spacesuits/flightsuit.dm
> +			usermessage("[I] has been successfully installed into systems.", mob_override = user)
missed it on 661, 668, and 675.

should probably just set the message in a var

2018-04-10 21:34 UTC, KorPhaeron commented
@ExcessiveUseOfCobblestone they can absorb and process foreign DNA, why wouldn't they be able to detect changes in a fish?

2018-04-11 14:12 UTC, ShizCalev requested changes

2018-04-11 14:12 UTC, ShizCalev commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/SuccessMessage = " has been successfully installed into systems."
just have that in the attackby instead of a new var on the object itself...

2018-04-11 19:44 UTC, ExcessiveUseOfCobblestone commented
@KorPhaeron Each time I look at this fred I confuse myself more and more.

2018-04-12 09:29 UTC, vuonojenmustaturska requested changes

2018-04-12 09:29 UTC, vuonojenmustaturska commented on code/modules/clothing/spacesuits/flightsuit.dm
> +	var/SuccessMessage = " has been successfully installed into systems."
make this a `var/const/SuccessMessage` too

2018-04-14 13:12 UTC, merged