Plant icon unit tests
tgstation/tgstation pull request #37262
Opened 2018-04-17 08:08 UTC by kevinz000

2018-04-17 13:49 UTC, Cyberboss submitted a review, later dismissed

2018-04-17 13:50 UTC, Cyberboss commented
So it turns out it was broken after all

2018-04-17 15:10 UTC, ShizCalev commented
lmao

2018-04-17 15:12 UTC, ShizCalev commented on code/modules/unit_tests/plant_growth_icons.dm
> +	states |= icon_states('icons/obj/hydroponics/growing_vegetables.dmi')
add goon\icons\obj\hydroponics.dmi

2018-04-17 15:15 UTC, ShizCalev commented
/obj/item/seeds/lavaland is a dummy parent, just assign it a random grow_icon and you should be fine

2018-04-18 15:37 UTC, kevinz000 commented
changed it to respect the seed growing icon files, as opposed to searching all of the states.

2018-04-18 19:58 UTC, Cyberboss commented
```
REASON #600 ...
```

You made it worse

2018-04-19 00:24 UTC, ShizCalev commented on code/modules/hydroponics/grown/mushrooms.dm
> +	growing_icon = 'icons/obj/hydroponics/growing_mushrooms.dmi'
species

2018-04-19 00:44 UTC, kevinz000 commented on code/modules/hydroponics/grown/mushrooms.dm
> +	growing_icon = 'icons/obj/hydroponics/growing_mushrooms.dmi'
oof

2018-04-19 00:45 UTC, kevinz000 commented on code/modules/hydroponics/grown/mushrooms.dm
> +	growing_icon = 'icons/obj/hydroponics/growing_mushrooms.dmi'
fixed

2018-04-23 00:07 UTC, ShizCalev requested changes

2018-04-23 00:07 UTC, ShizCalev commented on code/modules/hydroponics/grown/mushrooms.dm
> -	genes = list(/datum/plant_gene/trait/plant_type/fungal_metabolism, /datum/plant_gene/trait/glow)
missing the glow trait

2018-04-25 11:14 UTC, ninjanomnom requested changes

2018-04-25 11:14 UTC, ninjanomnom commented on code/modules/unit_tests/plant_growth_icons.dm
> +	var/list/paths = typesof(/obj/item/seeds) - /obj/item/seeds - typesof(/obj/item/seeds/sample)
`subtypesof(/obj/item/seeds) - typesof(/obj/item/seeds/sample)`

2018-04-28 01:25 UTC, closed without merging