Cleans up conveyor belts
tgstation/tgstation pull request #37288
Opened 2018-04-18 23:31 UTC by ShizCalev

Fixes #37248

Cleans up a ton of dirty conveyor belt vars
Adds directional icons to conveyor belts and conveyor belt switches (only visible in DM) so mappers can easily identify what's going on with them.
Added an inverted subtype for conveyor belts (cuts down on varedits)
Removed the convdir switch var, making the switches alot easier to work with. Icons will now be handled based off the switch's dir instead.
Fixed a good number of conveyor belts moving things in the incorrect direction.

2018-04-19 00:34 UTC, MrDoomBringer commented
yet another cargo buff
good

2018-04-19 02:31 UTC, Supermichael777 commented
This is actually a mapping buff.  Sec auto-processer when?

2018-04-19 02:40 UTC, cacogen commented
>buff

2018-04-19 14:04 UTC, WJohn commented
Much appreciated. This has always been annoying to work with wihout doing pixel hunting and comparisons to make sure you have the right ones.

2018-04-19 14:04 UTC, WJohn submitted a review, later dismissed

2018-04-20 00:58 UTC, ninjanomnom requested changes

2018-04-20 00:58 UTC, ninjanomnom commented on code/modules/shuttle/on_move.dm
> +	for(var/obj/machinery/conveyor/C in orange(1, src)) //Automatically assigned direction based on the dir of an adjacent conveyor belt to prevent desync
This will also pick up diagonals and potentially fuck up with 2 different direction but parallel conveyor lines.

2018-04-20 06:52 UTC, ninjanomnom approved these changes

2018-04-20 06:52 UTC, merged