Fixes emitters firing projectile with null arguments
tgstation/tgstation pull request #37307
Opened 2018-04-20 11:35 UTC by kevinz000

why....

2018-04-23 14:03 UTC, Cyberboss commented
That's a good question, you should find out instead of bandaiding the issue

2018-04-24 18:26 UTC, kevinz000 commented
@Cyberboss I've used sdql to try to select nullspace emitters but it didn't show any

2018-04-24 18:28 UTC, Cyberboss commented
Then this wouldn't fix it either, would it?

2018-04-28 01:30 UTC, optimumtact requested changes

2018-04-28 01:30 UTC, optimumtact commented on code/modules/power/singularity/emitter.dm
> +	if(!isloc(loc))			//One was somehow processing in nullspace or something.
this is not a fix, it's covering up a bug

you know better, remove this

2018-04-28 01:31 UTC, optimumtact commented
in fact just no, this is terrible

2018-04-28 01:31 UTC, closed without merging