Makes it possible to see tiles past z transitions
tgstation/tgstation pull request #37342
Opened 2018-04-21 20:56 UTC by ninjanomnom

:cl: ninjanomnom
add: You can now see objects and turfs past the map edge borders.
/:cl:

https://puu.sh/A6EQa/057293c3f3.mp4

It's a little bit rough with the animation there since we need to snowflake the movement glide for the map edge but we can use this to allow for some interesting things. This pr is just to get the visual in.

2018-04-21 21:25 UTC, MrDoomBringer commented
holy shit the madman did it

2018-04-21 22:27 UTC, ninjanomnom commented on code/datums/components/mirage_border.dm
> +/datum/component/mirage_border
This doesn't have too much reason to be a component other than organizational purposes atm but I can think of expansions on this functionality that would benefit from it being a component with access to signals.

I'm considering in the future making the component handle the border teleportation as well for example.

2018-04-22 00:16 UTC, arsserpentarium commented
I knew, that Ninjanomnom is a wizard.Powerful one.

2018-04-22 01:57 UTC, fludd12 commented
Yesssssss
Also I may or may not have an idea for similar effects with portals

2018-04-23 13:40 UTC, Cyberboss commented on code/datums/components/mirage_border.dm
> +		qdel(src)
I THINK COMPONENT_INCOMPATIBLE works here, but I'll have to double check

2018-04-23 13:51 UTC, Cyberboss requested changes
Yeah change that qdel to a COMPONENT_INCOMPATIBLE return

2018-04-23 19:32 UTC, Cyberboss commented on code/datums/components/mirage_border.dm
> +		qdel(src)
also remove the stack_trace, it's logged at the /component level

2018-04-26 20:24 UTC, Cyberboss approved these changes

2018-04-26 20:24 UTC, merged