Tesla Update
tgstation/tgstation pull request #37369
Opened 2018-04-22 21:15 UTC by kevinz000

:cl:
experimental: Tesla damage has been reworked to structures and objects have been worked with a linear scaling.
experimenta: All tesla weapons now no longer need to hit a mob to arc lightning; however, they will no longer stun, and only hit each target once.
/:cl:

tesla_zap vars are now a single bitfield.

2018-04-23 07:43 UTC, Vidiveni commented
Will the tesla shock from teslium/water grenades still stun?

2018-04-23 08:30 UTC, kevinz000 commented
yes

2018-04-30 19:01 UTC, Cyberboss requested changes

2018-04-30 19:01 UTC, Cyberboss commented on code/game/machinery/_machinery.dm
> +		explosion(loc, 1, 2, 4, flame_range = 2, adminlog = FALSE, smoke = FALSE)
loc => src

2018-05-09 21:10 UTC, optimumtact commented
stale kevin pr spam

2018-05-19 11:54 UTC, kevinz000 commented on code/modules/clothing/suits/reactive_armour.dm
> +/obj/item/clothing/suit/armor/reactive/tesla/equipped(mob/user, slot)
going to point this out so no one screeches. it prevents tesla armor nerds from getting targeted by tesla bolts. was in the original pr but people might have different opinions now that tesla armor is a thing.

2018-05-23 01:40 UTC, merged