Adds a cooldown to PDA send to all messages.
tgstation/tgstation pull request #37422
Opened 2018-04-24 22:37 UTC by DaxDupont

[Changelogs]:

:cl: Dax Dupont
balance: Adds a cooldown to PDA send to all messages.
fix: Last sent message cooldown actually works now.
/:cl:

[why]: People using it to spam is getting annoying, a cooldown seems appropriate considering it sends messages to everyone.

2018-04-24 22:38 UTC, QualityVan commented
despondent honking noises

2018-04-24 22:41 UTC, F-OS commented
How long is the cooldown i can't be arsed to math

2018-04-24 22:48 UTC, DaxDupont commented
@F-OS 3 minutes

2018-04-24 23:09 UTC, Therapist1 commented
gee, i can only imagine why this one got opened

2018-04-24 23:35 UTC, Bombpants commented
What was it before?

2018-04-24 23:55 UTC, DaxDupont commented
@Bombpants none

2018-04-25 03:09 UTC, ShizCalev requested changes

2018-04-25 03:09 UTC, ShizCalev commented on code/game/objects/items/devices/PDA/PDA.dm
> +	if (last_everyone && world.time < last_everyone + 1800)
`last_everyone + (3 MINUTES)` please

2018-04-25 04:35 UTC, PKPenguin321 commented on code/game/objects/items/devices/PDA/PDA.dm
> +	if (last_everyone && world.time < last_everyone + 1800)
also maybe like a minute and a half pls

2018-04-25 12:46 UTC, DaxDupont commented on code/game/objects/items/devices/PDA/PDA.dm
> +	if (last_everyone && world.time < last_everyone + 1800)
@PKPenguin321 I'll do two minutes

2018-04-25 18:16 UTC, ShizCalev requested changes

2018-04-25 18:16 UTC, ShizCalev commented on code/game/objects/items/devices/PDA/PDA.dm
> +	if((last_text && world.time < last_text + 10) || (everyone && last_everyone && world.time < last_everyone + (2 MINUTES)))
actually, since the time is now present in two places, make it a define please.

2018-04-25 19:52 UTC, Anonmare commented
Make sure that you can't bypass the cooldown by taking the cart out and slotting it back in or using other PDAs. Or do if that's your kink

2018-04-25 23:05 UTC, kevinz000 commented
1 minute is more sane but i'm probably just too nice

2018-04-26 09:27 UTC, arsserpentarium commented
Make cooldown 5 mins for lawyers pda.
Add send all option to clown pda. Make cooldown 0.5 s. Honk.

2018-04-26 18:34 UTC, iskyp commented
mute your pda it's not hard

2018-04-26 22:25 UTC, imsxz commented
u mad whiteboi? :)

2018-04-29 15:31 UTC, ShizCalev approved these changes

2018-04-30 06:09 UTC, merged