ORM reinforced plasmaglass + plasmaglass materials fix
tgstation/tgstation pull request #37466
Opened 2018-04-26 21:20 UTC by Barhandar

Fixes #37462
Fixes #37458

:cl: Barhandar
add: Reinforced plasmaglass is now directly smeltable in the ORM. Rejoice!
tweak: Plasmaglass and reinforced plasmaglass now have full plasma sheet per sheet instead of half.
fix: Reinforced plasmaglass didn't have metal material, added.
/:cl:

[why]: I don't want to click 50 times to make plasmarglass sheets and their materials were inconsistent with the other sheets. This is a mutually exclusive alternative to commit #37464 that does not reduce costs.
Note that refactoring is not the scope of this PR and I suspect the materials amount gets calculated at compile time anyway with negligible difference between /2 and *0.5.

2018-04-26 21:30 UTC, praisenarsie commented
@KorPhaeron thoughts?

2018-04-26 23:46 UTC, Fox-McCloud commented on code/game/objects/items/stacks/sheets/glass.dm
> +	materials = list(MAT_METAL=MINERAL_MATERIAL_AMOUNT/2, MAT_PLASMA=MINERAL_MATERIAL_AMOUNT, MAT_GLASS=MINERAL_MATERIAL_AMOUNT)
Use multiplication instead of division.

2018-04-26 23:46 UTC, Fox-McCloud commented on code/modules/research/designs/smelting_designs.dm
> +	materials = list(MAT_METAL = MINERAL_MATERIAL_AMOUNT/2, MAT_PLASMA = MINERAL_MATERIAL_AMOUNT, MAT_GLASS = MINERAL_MATERIAL_AMOUNT)
Use multiplication instead of division.

2018-04-27 12:49 UTC, Barhandar commented
There is no meaningful difference between dividing by 2 and multiplying by 0.5 (and for that matter, bitshifting right once). Halving values from 10,000,000 to 1 in a for loop takes ~28 world.timeofday deciseconds for all three methods. Halving 2000 10,000,000 times similarly takes ~23 deciseconds _for all three methods_.

2018-04-27 13:11 UTC, ExcessiveUseOfCobblestone commented
It literally does not matter either compile-wise or stylistically.

2018-04-27 18:18 UTC, ExcessiveUseOfCobblestone commented
wonder if that was prior to the optimization, as of now it should give the equivalent effect.

2018-05-10 02:58 UTC, SpaceManiac requested changes
Other than a nitpick, looks good to me. Favoring it over the other PR just for not being a balance change at the same time. It's not like plasma is in short supply.

2018-05-10 02:58 UTC, SpaceManiac commented on code/modules/research/designs/smelting_designs.dm
> +	name = "Reinforced Plasma + Glass alloy"
I think I'd go with either "Plasma + Reinforced Glass alloy" or "Plasma + Iron + Glass alloy". It's not the plasma that's reinforced.

2018-05-13 06:04 UTC, closed without merging