Changes the trauma formula so constant small ticks don't keep triggering traumas
tgstation/tgstation pull request #37516
Opened 2018-04-28 09:52 UTC by XDTM

:cl: XDTM
balance: Small, constant ticks of brain damage are now less likely to cause traumas.
/:cl:

New formula is `brain damage hit` + 2% for each point of existing brain damage past the threshold (or -2% for each point before the threshold).

Current thresholds are 20 for mild traumas and 100 for heavy ones, which means that you have no chance of heavy before 50.

2018-04-30 18:09 UTC, Cyberboss requested changes

2018-04-30 18:09 UTC, Cyberboss commented on code/modules/mob/living/carbon/damage_procs.dm
> +	else if(prev_brainloss < (BRAIN_DAMAGE_DEATH - 20) && (BRAIN_DAMAGE_DEATH - 20))
second check makes no sense

2018-04-30 19:27 UTC, XDTM commented on code/modules/mob/living/carbon/damage_procs.dm
> +	else if(prev_brainloss < (BRAIN_DAMAGE_DEATH - 20) && (BRAIN_DAMAGE_DEATH - 20))
whoops

2018-05-01 14:56 UTC, Cyberboss approved these changes

2018-05-01 14:56 UTC, merged