Makes the jukebox less terrible
tgstation/tgstation pull request #37587
Opened 2018-04-30 17:49 UTC by KorPhaeron

:cl: Kor
add: The jukebox song will no longer restart when you leave and re-enter the room.
add: You will only hear the jukebox when it is visible to you.
fix: The jukebox will no longer freeze the game.
/:cl:

2018-04-30 18:11 UTC, KorPhaeron commented
This seems inconsistent at eliminating the lag, but it felt shorter and less frequent I think

Sound files probably just need to be smaller now

2018-04-30 19:07 UTC, Aloraydrel commented
Based

2018-04-30 21:11 UTC, Dorsisdwarf commented
Is there any way you can fix it being a binary on/off between it going from full loudness to off the instant its more than 7 tiles away? 

Also it takes a second or so to restart when you come back into range, which is weird and disjointed

2018-04-30 22:06 UTC, optimumtact commented
the lag comes from the file being streamed to you, it locks up your client.

For people like me who are further away this lag is anywhere upwards of 20 seconds

2018-05-01 00:43 UTC, KorPhaeron commented
@optimumtact I'm not at all familiar with goonchat, would sending music from the jukebox through it/stopping music sent by it conflict with admin played youtube links?

2018-05-01 06:45 UTC, optimumtact commented
you can add more html5 audio elements.

I'm sure it will be incredible

2018-05-01 15:58 UTC, ExcessiveUseOfCobblestone commented
mfw when you leave the area and come back it just reuploads the song to you.

2018-05-01 20:36 UTC, Cyberboss requested changes

2018-05-01 20:36 UTC, Cyberboss commented on code/game/machinery/dance_machine.dm
>  /obj/machinery/jukebox/disco/activate_music()
Spacing

2018-05-02 04:52 UTC, closed without merging