Adds grenadine.
tgstation/tgstation pull request #37598
Opened 2018-05-01 03:02 UTC by Hyacinth-OR

:cl: Hyacinth
add: Grenadine is now available in the bar!
tweak: Tequila sunrises now require grenadine to make!
/:cl:

Grenadine is an essential part of a barkeeper's toolkit. In addition, being a huge fan of tequila sunrises in real life, I've always been disappointed that the code passes off a tequila screwdriver as a tequila sunrise, so I've remedied that, and edited the tequila sunrise sprite to reflect this.

I'm looking forward to hearing any of your questions comments or concerns :D!

2018-05-01 03:05 UTC, Cyberboss submitted a review, later dismissed

2018-05-01 12:50 UTC, europax commented
From #37589 here - possible merge conflict incoming

2018-05-01 16:07 UTC, ShizCalev submitted a review, later dismissed

2018-05-01 16:07 UTC, ShizCalev commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +	righthand_file = 'icons/mob/inhands/equipment/kitchen_righthand.dmi'
There's no item_state defined for this, so changing these inhand files won't do anything

2018-05-01 20:29 UTC, Cyberboss requested changes

2018-05-01 20:29 UTC, Cyberboss commented on code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +<<<<<<< .mine
You messed up the merge

2018-05-01 20:56 UTC, improvedname commented
Drink bloat that one thing that might ever get used in a super rare rp moment on tg

2018-05-01 21:05 UTC, epochayur commented
do you get paid to make pointless, obnoxious comments, or do you just really enjoy it that much

2018-05-01 21:07 UTC, ExcessiveUseOfCobblestone commented
I plan on giving these functionality after merge so shush zootopia

2018-05-02 15:37 UTC, WJohn submitted a review, later dismissed
Not a super unique sprite, but I do like the little rainbow going on in the center and the bright red is cheerful. Fine by me.

2018-05-02 17:00 UTC, ExcessiveUseOfCobblestone requested changes

2018-05-02 17:00 UTC, ExcessiveUseOfCobblestone commented on code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/alexander
Dupe 

https://github.com/tgstation/tgstation/pull/37598/files#diff-96dc0c287671d3dd23c39f617ecf5ad6R667

2018-05-02 18:12 UTC, Cyberboss approved these changes

2018-05-02 18:12 UTC, merged