Shows assemblies some love.
tgstation/tgstation pull request #37632
Opened 2018-05-02 22:57 UTC by ShizCalev

🆑 ShizCalev
fix: Fixed proximity sensors not working
fix: Fixed mousetraps not working properly when attached to TTVs and one tank bombs.
fix: Fixed infrared sensors not updating the direction of their beam when connected to another device.
fix: Fixed infrared sensor beams not aligning correctly with the device correctly when attached to another device, or a TTV
fix: Fixed infrared sensors not turning on when connected to another device....
fix: Fixed infrared sensors facing the wrong direction when connected to another assembly device.
fix: Fixed the beam for infrared sensors not starting at the actually emitter portion of the infrared sensor.
fix: Fixed proximity sensors showing the arming timer when it's already armed
fix: Fixed assembly items being detached from one another dropping both items in the incorrect location.
/🆑

Fixes #35829
Fixes #27235
Fixes #37545

2018-05-02 22:58 UTC, optimumtact commented
Great PR :heart:

2018-05-03 00:34 UTC, MrDoomBringer commented
holy shit
i can finally code a real proximity suicide now

2018-05-03 01:25 UTC, PKPenguin321 commented
Might be out of scope but this just reminded me to report https://github.com/tgstation/tgstation/issues/37635 and a fix for that would be appropriate here

2018-05-03 01:30 UTC, ShizCalev commented
@PKPenguin321 think the fix for that would be the componentization of flashes.

2018-05-03 03:50 UTC, Iamgoofball commented
Assemblies need to be axed entirely.

2018-05-03 03:52 UTC, SpaceManiac commented
>fix: Fixed proximity sensors not working

THANK you

2018-05-03 23:08 UTC, AlexTheSysop42 commented
Bug: signallers have issues when put in buttons

2018-05-04 13:52 UTC, Cyberboss requested changes

2018-05-04 13:52 UTC, Cyberboss commented on code/game/objects/items/devices/transfer_valve.dm
> +	if(attached_device)
. = ..()

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
use a timer with VARSET_CALLBACK please

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
^

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
^

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
^

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
^

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/doorcontrol.dm
> +	cooldown = FALSE
^

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/infrared.dm
> +	for(var/mob/CHM in get_hearers_in_view(hearing_range, src))
typeless

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/proximity.dm
> +	for(var/mob/CHM in get_hearers_in_view(hearing_range, src))
typeless

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/assembly/timer.dm
> +	for(var/mob/CHM in get_hearers_in_view(hearing_range, src))
typelass

2018-05-04 13:52 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/input.dm
> +	for(var/mob/CHM in get_hearers_in_view(hearing_range, src))
.

2018-05-06 12:05 UTC, merged