Moves removing the cell to screwdriver_act for APCs
tgstation/tgstation pull request #37648
Opened 2018-05-03 17:24 UTC by vuonojenmustaturska

Fixes #37628

:cl: Naksu
fix: APCs are closed with crowbars properly again. Screwdrivers can now be used by borgs to pop out the cell instead of crowbars
/:cl:

2018-05-03 17:33 UTC, Jalleo commented on code/modules/power/apc.dm
> +		if(cell)
Why cant it just be set in the interact proc with removing the cell?

2018-05-03 17:48 UTC, Cyberboss requested changes

2018-05-03 21:32 UTC, ShizCalev commented on code/modules/power/apc.dm
> +			charging = 0
not boolean

2018-05-04 09:29 UTC, vuonojenmustaturska commented on code/modules/power/apc.dm
> +			charging = 0
this whole code could use someone to take an axe to it

2018-05-06 13:51 UTC, Winterous commented
Can this get fixed already? This is a stupid issue.

2018-05-06 15:12 UTC, Anonmare commented
Can we please have this fixed already

2018-05-06 15:13 UTC, Anonmare commented
@Cyberboss

2018-05-06 16:44 UTC, Cyberboss approved these changes

2018-05-06 16:44 UTC, merged