Podpeople inherit plant traits
tgstation/tgstation pull request #37722
Opened 2018-05-07 07:16 UTC by Time-Green

Pod people will now inherit a random plant trait from the seeds they were grown from. 

Plant people now start with plant blood. On creation it will try to find a random reagent gene in the seeds, and use that as blood.

They also inherit yield and potency

I also added a proc that gets called when a species is admin forced. I used it for debug purposes so I wouldn't have to fucking regrow pod people to test it, but I kept it in.

:cl: Time-Green
add: Podpeople now inherit traits from the seeds they grew from. Mr Slippery Space Drug. 
add: Calls on_admin_forced on species when it's admin forced
/:cl:

im gonna write down what all the traits do, wait a sec

2018-05-07 07:27 UTC, Time-Green commented
one chem production trait is picked and used as blood, if there are any

2018-05-07 07:30 UTC, PKPenguin321 commented
Buffing the best race in the game reee

Innate reactive teleport is way to fucking good
Innate damage resist seems really really strong but idk the threshhold for gibbing
Literal stun gloves
Innate soap

Incredibly strong, it's cool but I hate it

2018-05-07 07:34 UTC, Time-Green commented
tele fuck doesnt react on thrown or projectiles. still OP i guess
the gib one, min is 10 and max is 18. so stuff like an axe or spears will always gib you
what if it has an innate chance to backfire?
soap one is good

2018-05-07 07:36 UTC, BebeYoshi commented
As a botanist main, I totally approve it, but I have suggestions to make it less OP:
Cell and Eletrical Activity shouldn't shock people, instead make your punch does some burn damage scaling with potency (not more than 15 tho) and shocking sound, also the battery one make your hand an inducer in cost of hunger/blood
Smoke: Makes smoke reaction in a little range when you're hit or takes a certain amount of damage in a cooldown
Fire Resistence: Removes the burn damage penality for podpeople and make them resistent at higher potency
And black list some chems, you don't want to be turned into a plasmaman because a podpeople punched you with toxin, with these I'm sure it won't be OP and will actually be fun, cheers!

2018-05-07 07:37 UTC, PKPenguin321 commented
If this goes through they should no longer heal in sunlight imo, these perks are already enough

2018-05-07 07:37 UTC, BebeYoshi commented
Also give the teleport one a long cooldown when it procs

2018-05-07 07:37 UTC, BebeYoshi commented
Yeah, remove the ligh perk since it doesn't make sense at all as plants don't need light in spess

2018-05-07 07:42 UTC, Time-Green commented
you can only inherit the plants chems. unless there's a way to turn any chem into a plant gene, there's no danger of plasmatoxin plant people. excluding strange seeds

I like your suggestions, I'll get on it. Not sure about the fire one, burndamage should be painful to them

2018-05-07 07:43 UTC, BebeYoshi commented
Also, if slip time isn't the same as banana (aka, if any other plant has slippery and isn't a banana, the stun is reduced as heck) it should be ok

2018-05-07 07:44 UTC, BebeYoshi commented
Fire resistence trait doesn't make sense at all, so that should be a good perk, not that anyone will use them comparing to the other perks

2018-05-07 07:44 UTC, Time-Green commented
I can disable the light perk
you guys have better judgement: always have it disabled or only when there's a major perk?

2018-05-07 07:45 UTC, BebeYoshi commented
Always disabled

2018-05-07 07:49 UTC, BebeYoshi commented
also, please consider the blacklist thing or this will never be approved, nettles with toxin would happen almost everytime, strange seeds do amazing and terrible things

2018-05-07 07:55 UTC, BebeYoshi commented
Also, think more of funny and unrobust disadvantage for the OP traits like slippery skin, make that every second you have a random chance to drop the item on your hand, the nettle one has a chance to deal damage to your self everytime you pick an item with your hand and always when you punch someone

2018-05-07 08:42 UTC, Tlaltecuhtli commented
make the chem u produce also affect you so having cyanide blood also give you cyanide

2018-05-07 12:14 UTC, Time-Green commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/harm(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style) //the datum belongs to target, fuck you
This species datum is actually owned by the target for some reason. 
on_harm is owned by the actual attacker

2018-05-07 12:14 UTC, Time-Green commented
potassium + water podperson stinger
https://gyazo.com/543849b60c5d0c1c08a65f1c2d653171

2018-05-07 12:43 UTC, Time-Green commented
Should be all good now

2018-05-07 14:01 UTC, MMMiracles commented
I'd imagine mutating a pod plant to 100 potency would be a major pain in the ass since you can't just make copies of a high-potency seed and use that as a base if RNG fucks up the potency on your current plants.

2018-05-07 14:46 UTC, Spaceinaba commented
good change

2018-05-07 15:25 UTC, ExcessiveUseOfCobblestone commented
Fire resistance needs to go, podpeople have intrinsic weaknesses against it and forgoing that seems wrong.

Ofc the people who play podpeople are going to want to bypass one of the very few weaknesses they have lol.

2018-05-07 15:26 UTC, ExcessiveUseOfCobblestone commented
> Yeah, remove the ligh perk since it doesn't make sense at all as plants don't need light in spess

If plants are working fine w/o light and w/o fungal vit that's a bug i'm pretty sure.

2018-05-07 18:42 UTC, BebeYoshi commented
First of all, thanks for hearing my suggestions, I come with some more suggestion:
When I said remove the light perk, I meant only the good part of it, you should STILL take damage of darkness, just not healing or gaining nutrition, that would be a huge nerf, also another huge nerf I had in mind would be:
-Make them not immune to kudzus anymore (Still immune to tomatoes and bees)
-Weed Adptation makes you immune to kudzus and makes you get hungry slower
-Fungal Vitality would make you take less damage from darkness
Also, I think the fire resistence thing should be ok, since if you take it, you can't take the other traits, keep in mind you can only take one trait AND one chem trait, so it should be ok, hope my idea helps you once again and cheers!

2018-05-07 18:46 UTC, BebeYoshi commented
And just like Kudzu Fire-Immune trait, make Fire Resistence pod people take more damage from other sources, so it won't be abused and it should be good

2018-05-07 20:00 UTC, Time-Green commented
I like the idea of having the stronger ones be a double edged blade, I guess making them really vulnerable to cold with fire resist would make sense

2018-05-07 22:08 UTC, Doppeltongue commented
What about lifebringers from the lavaland vault? Should we leave those as the current podpeople? How does having certain chems as blood affect overdosing? If you have black powder blood with densified chemical trait, how funny is the result of someone setting you on fire? 

Fire resistance is definitely powerful, but you need to remember that there is no plant that naturally spawns with fire resistance, so it takes extreme RNG to actually obtain it, and podpeople don't show up very frequently ( in my experience). Competent botanists are also relatively rare.

Gaseous decomposition should put some of your blood into the smoke emitted for added hilarity, since that's what its primary use is for. If this gets merged, can you add a new plant that contains table salt as a reagent so that people can literally have salt running through their veins?

Also, some of these traits seem so terrible that they'd only be used for punishment/jokes, which is fine since you can pick and choose, but just be careful on where it falls on the broken to outright terrible scale.

2018-05-07 22:44 UTC, BebeYoshi commented
You wouldn't be able to have blackpowder in plants unless you have cherry bombs, also, they should overdose, why would you even do that to yourself, and I'm pretty sure Gaseous decomp already does that.
Also, no idea why no one mentioned it yet, but having no blood means you won't be able to be plant yourself again, which means if you want to change traits or something, you will have to do a surgery and become human again or monkey just to get blood and do it again, also would be really hard to get your "blood" back to your body, depending on what chem you take

2018-05-08 00:51 UTC, Kromgar commented
It would be neat if firing a floral somatoray at a pod person had a chance to give them traits and or change their blood chemical composition. I mean it already has a high chance to make them deaf, mute and retarded anyway

2018-05-08 01:00 UTC, ExcessiveUseOfCobblestone commented
how does this whole "the mob blood is now water" and using that to podrevive someone work?

2018-05-08 03:26 UTC, BebeYoshi commented
Simple, you can't regrow someone if they don't have blood on them, and with blood I mean really blood, not some random chem you use as blood, should be like that to balance too, also, don't know if it's already done, but make hugs while having prickles also hurt/pass some of your blood to the target while also hurting yourself

2018-05-08 06:10 UTC, Grazyn commented
Maybe you could make podpeople drop seeds when they reach a certain amount of nutrition, those seeds would work like DNA-injected regular pod seeds. And make the seeds decay after some time (like legion cores) to avoid hoarding infinite clone vouchers.

Also yes, podpeople with the prickle trait should definitely prick others when hugging/being hugged, case in point: https://i.imgur.com/Ut8eLM1.png

2018-05-08 06:17 UTC, Doppeltongue commented
Yeah, maybe there should be a way for podpeople to just make replica seeds of themselves then. Having overdose/chem in your blood affect you will severely limit the variety of chems you can put in yourself, and could potentially make some chems broken.

2018-05-08 07:43 UTC, Time-Green commented
@Doppeltongue gas already does that, and fire resistence can be gotten from lavaland flora

Also hugs are sacred, but sure?

2018-05-08 09:09 UTC, BebeYoshi commented
You can only put one chem in your body, and you will metabolize it (At least I hope) but also generate it, so blackpowder selfbomb wouldn't be as good since you could only do that one time unless you have autocloning (since you wouldn't be able to plant yourself, cuz no blood) and putting powerful venoms would kill you, so yeah, unless you want to plant something for 2 minutes, to revive with a stong poison and kill someone before you die from it, wouldn't be so broken

2018-05-08 10:39 UTC, Doppeltongue commented
Metabolizing from blood would result in almost all chems being unusable due to instant overdose/poisoning. Actually, now that I read the code, it seems like once the podman spawns, they get 200u of whatever reagent is picked injected into them aside from their blood getting replaced, which is enough to exceed all overdose thresholds. I can think of only two naturally occuring chems aside from the default chlorophyll that I'd ever consider using on myself under these circumstances, and even then just barely and very situationally. 

Maybe podpeople shouldn't overdose on their own blood? The thought of them being addicted to their own blood is funny though, so I wouldn't mind if that stays in.

2018-05-08 13:14 UTC, Kromgar commented
So if your blood is bicardine do you just instantly overdose?

2018-05-08 13:16 UTC, ExcessiveUseOfCobblestone commented
Maybe i'm just buzzwordbox but I wouldn't be a big fan if I got """revived""" but lol I now have to constantly watch my damage because i'm forever ODing on the botanists' chem of choice.

2018-05-08 13:27 UTC, BebeYoshi commented
I don't see why you shouldn't overdose/be addicted/metabolize your body, this would easily make podpeople really borken so fast, just imagine someone with infinite meth on body without suffering any trouble, if you want a good chem in your body you will have to get creative, as all botany things.

2018-05-08 13:32 UTC, Kromgar commented
Don't most chems have an overdose affect?

2018-05-08 13:33 UTC, Kromgar commented
Wait... what happens if a plant persons blood is nutriment?

2018-05-08 13:39 UTC, BebeYoshi commented
They just become fat I guess, and can make people eat if they bash/hug them if they have nettle or make other fats (would take a lot of hugs tho)

2018-05-08 13:41 UTC, ExcessiveUseOfCobblestone commented
@BebeYoshi what if you're not the one deciding the chem, or you don't even have a say in the matter? Even if you're antag it would be absurd to get """cloned""" just to be forever debilitated, that's not engaging for anyone since the only practical solution is to kill and clone.

The trait thing is cool, but spawning with a chem that forever puts you in OD hell is not. I'd rather the feature not exist than ever having to deal with someone grieffing with it, antag or not.

2018-05-08 13:47 UTC, BebeYoshi commented
Podcloning is totally optional and it will always be, just stay in your body if you don't want to be podcloned, I don't see how that should be a problem

2018-05-08 13:49 UTC, BebeYoshi commented
If you don't trust the botanists, just don't leave your body when the plant is ready to be harvested, if you still think this is a shitty way to avoid it, I suggest that a popup could also be added and make harvesting podpeople take some time so they can choose to revive or not.

2018-05-08 13:59 UTC, ExcessiveUseOfCobblestone commented
You don't know what chem you're going to receive until you're in the body.

I mean this is probably bikeshed considering if you don't have healing meds your round is effectively over as soon as you spawn in with >3/4th of the chems available, including antag chems obv. Friendly reminder purge chems would kill you depending on how this whole "reagent replaces blood" thing works.

So my thought is the only time this would ever see any use is if you happen to find a chem with 
0 downsides (this will be a ticket to nerf so enjoy it while you can) OR you use it to grief/antag.

2018-05-08 14:27 UTC, BebeYoshi commented
There are many uses for it, if you get charcoal, for instance, you could heal people with it and always be healing yourself, if you put some easy chem as blood, like water, you can never die of bleeding, a holy water machine, laugher dispenser, occuline, or you could use teamwork to make funny things as well. And as I said, if you don't trust the botanist, just don't leave your body, and I think purge chem should work good since they don't purge themselves. Also, beign hard to find chems without downside is something we want, since what most people don't know about botany is that the hard part is not cultivating plant, but cultivating our creative ideas!

2018-05-08 15:08 UTC, Grazyn commented
what if your blood is booze, would it make you perma-drunk?

2018-05-08 15:13 UTC, ExcessiveUseOfCobblestone commented
"Just don't watch the round" is pretty bad (although this is fixed by a prompt and not necessarily tied to this PR), and I didn't even think about the abusive nature of holy water blood reagent. Once the blacklist inevitably gets added this feature is hecked.

It just seems like the only use for this parallels with circuitry in that it has little regard for the current balancing mechanisms in place. It's either passive-regen mobile medicines, literally free cult immunity (once you are the podperson), passive-regen mobile nutrients/water/etc. for plants, or a bad time. There's no room for "it's just a change in blood" because the player determines the reagent, and it will never not be something either mechanically useful to them or malicious to others byond maybe the first time before it clicks.

I guess we've just hit a point in botany where adding any more non-linear arrangements that are driven by player decision basically forgoes our current balance, but adding linear arrangements sucks because linearity has much less replay value. We should divert the attention to other jobs that could use this aspect rather than adding yet another power level to a department well ahead of everyone else. Most people won't like this statement, but players should find enjoyment in playing a variety of jobs rather than "maining" the same job until the only recourse they have is to add powerful content because they've exhausted the current best items available to the role.

@Grazyn Yes until you died from liver failure.

2018-05-08 15:46 UTC, BebeYoshi commented
Well, holy water may be op, but that's why I suggested blacklist, and you just need to renter your body BEFORE the botanists can harvest, still think this is a very nice PR, mostly the liquid contents and slippery one sounds really fun

2018-05-08 17:51 UTC, ExcessiveUseOfCobblestone commented
Yeah the traits are neat, I'm just not a fan of having to play balance hopscotch with every chem (strange seeds) or with yet another blacklist.

2018-05-09 00:06 UTC, Kromgar commented
If your blood is charcoal wouldn't your charcoal blood just delete itself as it would purge all chems?

2018-05-09 06:48 UTC, TheDreamweaver commented
If light hekng gets removed, i'd instead tie light levels to blood generation, as that makes more sense biological anyways.

2018-05-09 07:19 UTC, Time-Green commented
Chems that are used as blood are completely seperated from the rest of your body. So you wouldn’t have any side effects apart from just getting bornc

2018-05-09 13:05 UTC, BebeYoshi commented
So you will metabolize them, but not overdose/get addicted?

2018-05-09 15:13 UTC, ExcessiveUseOfCobblestone commented
you wouldn't metabolize them either.

2018-05-09 16:10 UTC, BebeYoshi commented
Now that would be easily OP, botany has acess to deadly toxins, this + nettle could easily kill +20 people in less than one minute just by hugging

2018-05-09 16:16 UTC, AlexTheSysop42 commented
You make the nettles deal damage to the person then, and also use up some blood

2018-05-09 20:58 UTC, Time-Green commented
You don’t transfer by hugging, and if you use a really bad chem, you’ll probably die yourself from the chems you start with. And yes you do OD

2018-05-09 23:04 UTC, AlexTheSysop42 commented
>yes you do OD

That makes any remotely interesting chem completely worthless

2018-05-10 07:13 UTC, Time-Green commented
Meh, you can still life quite easily if you do some preparing

2018-05-10 12:09 UTC, AlexTheSysop42 commented
Like?

2018-05-10 13:00 UTC, BebeYoshi commented
> That makes any remotely interesting chem completely worthless
You mean that makes most of the strong chems useful, remember chem swords that healed? That's the same reason we don't want these too common.

2018-05-10 17:37 UTC, Time-Green commented
@AlexTheSysop42 making a chem reaction or just alot of medical treatment

2018-05-10 18:15 UTC, AlexTheSysop42 commented
Does the smoke reaction keep more from being added? Does it remove your blood?

2018-05-10 19:13 UTC, Time-Green commented
Your blood and normal chems are completely seperated. Your blood doesnt even exist as a datum, it’s literally the reagent and how much there is of it.
BLOOD DOESNT DO SHIT

2018-05-11 00:01 UTC, Doppeltongue commented
I know that. The thing is that the code also seems to directly inject you with 200u of chem, which is lethal overdose levels of just about everything that you can overdose on. And if you do survive the overdose, you've also hit every addiction threshhold, so you're also addicted to the chem if you can be addicted to it.

Now that I think of it, how does this interact with cloning? Do podpeople get another 200u of chem once they clone?

2018-05-11 00:37 UTC, ExcessiveUseOfCobblestone commented
@Doppeltongue it's on the harvest of the plant so if you mean cloning as the actual cloning in medical then no it won't give you 200u again.

If you're talking about cloning as any form that revives a player, no it does not.

2018-05-11 01:59 UTC, optimumtact commented on code/modules/hydroponics/grown/replicapod.dm
> +			for(var/datum/plant_gene/trait/T in genes)
why not just pick from the genes list, what is the significance of the gene trait list.

2018-05-11 02:02 UTC, optimumtact commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		dna.species.on_move(src)
there is a moved signal for all atoms, register for that, don’t' add your own hook

2018-05-11 02:03 UTC, optimumtact commented on code/modules/mob/living/carbon/human/species.dm
> +			user.dna.species.on_harm(user,target, attacker_style)
add a signal

2018-05-11 02:03 UTC, optimumtact commented on code/modules/mob/living/carbon/human/species.dm
> +			user.dna.species.on_harm(user,target, attacker_style)
rather change to a signal

2018-05-11 02:06 UTC, BebeYoshi commented
Also, most of botanies fun dead plants died recently, not sure what PR did it, so that may motivate this nice PR? Didn't test enough but either plants are getting less chemicals or transfering less chems, so it has being a pain to make some nice prickles plants

2018-05-11 02:08 UTC, optimumtact commented on code/modules/hydroponics/plant_genes.dm
> +/datum/plant_gene/trait/slip/pod_Crossed(datum/species/pod/P,mob/living/carbon/human/H,atom/movable/AM)
don't do this, there is a slippery component. add one to your appropriate mob when you get the slip trait

https://github.com/tgstation/tgstation/blob/master/code/datums/components/slippery.dm#L6

2018-05-11 02:08 UTC, optimumtact requested changes
Code needs serious work

2018-05-11 02:09 UTC, optimumtact commented on code/modules/hydroponics/plant_genes.dm
> +/datum/plant_gene/trait/slip/pod_on_move(datum/species/pod/P, mob/living/carbon/human/H)
register for the movable signal on your source mob instead

2018-05-11 02:10 UTC, optimumtact commented on code/modules/hydroponics/plant_genes.dm
> +/datum/plant_gene/trait/slip/pod_on_move(datum/species/pod/P, mob/living/carbon/human/H)
honestly this could probably be a movement type, like FLYING, but SLIPPERY or something, that can be checked in the core slip code, instead of here.

2018-05-16 05:52 UTC, yorii commented
> densified chemicals: you become thicc af and can hold double the reagents
So you can hold 2000u of nitroglycerin? You do realize this amounts to basically being able to use a plantperson as a bomb with the potency of about a decently sized SM explosion?

2018-05-16 06:04 UTC, BebeYoshi commented
I don't think podpeople will have the same amount of max reagent than others carbon, also nitroglycerin reacts automatically so it would be impossible to do that I suppose

2018-05-16 09:52 UTC, Time-Green commented
if you actually manage to get your hands on that much nitroglycerin, well you deserve that

2018-05-16 15:37 UTC, ExcessiveUseOfCobblestone commented
@BebeYoshi where r u getting this info from?

2018-05-16 16:16 UTC, BebeYoshi commented
I may have misread some commentaries above about having 200 units maximum, my bad once again

2018-05-17 09:48 UTC, yorii commented
>if you actually manage to get your hands on that much nitroglycerin, well you deserve that

Same department that grows podpeople can also grow nitroglycerin with ease and getting 2000u of nitroglycerin does not take as long as you might think.

2018-05-18 08:05 UTC, Doppeltongue commented
Injecting 2000u nitroglycerin would probably take 10 minutes of straight clicking, as well as a tiny bit of help from chemistry to get the oxygen needed for stabilizing. You'd also need to grow the ingredients somewhat separately, while dealing with the fat/burns from injecting corn oil/acid into yourself. 

6 clicks per 15u (3 to fill the syringe and 3 to inject). To make 5u of nitroglycerin, you'd need 15u corn oil, 10u sacid, 5u facid. Since all of these things metabolize, you're guarenteed to deal with burns/weight gain the whole way through. 2000u nitroglycerin is minimum of 400 reactions of this, which is about 4800 clicks minimum just to deal with syringes. This doesn't include having to pick up new plants whenever you empty your current one, and you'd need at least 2 different strains (one plant technique would result in explosions in the syringe and shitty ratios), nor does it include the chem loss from metabolizing your poisons. You can skip 200 u of corn oil by using it as your blood. Due to the ratios of the available corn oil to acid (20% corn oil production vs 50% sacid and facid), there is no way to avoid serious burns.

Scratch that 10 min guess. This is easily a 1 hour round, 2 person ordeal (you need someone to harvest the pod) just for one explosion. Personally, I wouldn't think the resulting carpal tunnel would be worth it.

2018-05-18 08:17 UTC, yorii commented
@Doppeltongue you possibly just found the most convoluted method I have ever heard of doing this.

2018-05-18 21:54 UTC, Doppeltongue commented
@yorii Oh right, you can just eat them, fuck me. Still a pain in the ass to eat all that and will still result in a lot of burns, since you need to eat the acids first or else the corn will fill you up and stop you from eating more.

2018-05-18 22:31 UTC, Teepeepee commented
Have you thought of just grinding the plant in a beaker with 1u of stabilizing reagent and using the chemmaster to separate all nitroglycerin into 50u pills, and injecting pyrosium+oxygen to detonate after eating all the pills?

2018-05-19 01:39 UTC, yorii commented
@Doppeltongue Jesus Christ you're dumb.

Just eat 40 pills of 50u Nitroglycerin, sure it takes a while, but only a minute or two.
I timed myself doing this today and it took less than 20 minutes to solo it after I had acquired a full chemistry setup in botany. (Which doesn't really take long either).
And this time includes accidentally deleting 300u of Glycerin from the chemmaster.

2018-05-19 02:38 UTC, Doppeltongue commented
That's an idea, but nitro plants result in about 6.7u nitro, 37.6u sulf acid, and 23.3u facid at 100 potency with densified chems. Botanists don't get chemmasters, only condimasters, and even if you grabbed a chemmaster, making one 50u pill would be about 8 growns that need to be ground one by one due to the sheer volume of excess acid, which also need to be dumped into the buffer afterwards for deletion. Much slower than just eating the plants while monitoring your chem balance and chugging healing chems.

This is also ignoring that the bomb-to-be would need to die twice, once for podding, the other when they explode. You could invest the immense amount of time and effort to do this, or you could just break into R&D and print off two BoH and do more damage to the station in 5 minutes and no effort. Hell, you could do as much with just one good kudzu seed right now, which are way easier to mass produce, and nobody abuses that.

Seriously, it's possible now to make exploding bodies with 1000u nitro, and I've never seen anybody even try.

2018-05-19 16:01 UTC, yorii commented
Dude just remove all traits from corn and grind pure corn oil, the rest can be make in the chemmaster.

2018-05-19 16:39 UTC, Time-Green commented
guys what the fuck

2018-05-19 17:12 UTC, Time-Green commented
wait i got an even worse feature idea then this one hold on

2018-05-19 17:12 UTC, closed without merging