Update PubbyStation
tgstation/tgstation pull request #37736
Opened 2018-05-07 19:19 UTC by pubby

A bunch of changes and several fixes.

Some pictures are in this thread:
https://tgstation13.org/phpBB/viewtopic.php?p=395721#p395721

:cl: Pubby
tweak: PubbyStation has been updated. You can now be the lawyer.
/:cl:

2018-05-08 04:47 UTC, 81Denton commented
That is one sexy shuttle

2018-05-08 22:48 UTC, ShizCalev requested changes

2018-05-08 22:48 UTC, ShizCalev commented on _maps/shuttles/emergency_pubby.dmm
> +	tag = "icon-darkgreen (NORTHEAST)";
Dv

2018-05-08 22:48 UTC, ShizCalev commented on _maps/shuttles/emergency_pubby.dmm
> +	icon_state = "darkgreen";
Nope

2018-05-08 22:48 UTC, ShizCalev commented on _maps/shuttles/emergency_pubby.dmm
> +	icon_state = "darkgreen";
Dv

2018-05-08 22:48 UTC, ShizCalev commented on _maps/shuttles/emergency_pubby.dmm
> +	tag = "icon-darkgreen (SOUTHWEST)";
Anything that's tag = "icon is a dv

I'd mark them all but I'm on my phone till next week.

2018-05-12 14:16 UTC, pubby commented
I think it's good now?

2018-05-17 00:47 UTC, pubby commented
Cyberboss your render robot is having difficulties.

I would like this merged soon so that I can do map changes in #37833

2018-05-17 15:01 UTC, merged