Individual Logs now follow the client around automatically
tgstation/tgstation pull request #37790
Opened 2018-05-11 03:59 UTC by optimumtact

The logging is now stored in the persistent client/player_details datum,
that will survive an entire round

The existing mob log is retained and a new admin verb is added to access
it. It will only show logs for the mob in question, across all players
who possibly spent time in that mob

A new log type is added that tracks the mobs the player changes across
into and the times they occured, to better help admins manage complex
situations, this also appears in the mob log as a record of the players
who entered/exited control of the mob

TODO 
* add the mob log verb, probably linked off the Player Panel but that is TBD
* add the log type for client exit/enter mobs and log those occurrences

2018-05-15 06:06 UTC, optimumtact commented
Did you know this was already a thing? there was a global list.

anyway I tore that out because this way is better

2018-05-16 21:34 UTC, optimumtact commented
no, but I suppose it could

2018-05-19 22:12 UTC, AnturK commented
Yeah, ckey transfer is one of current logs weak points.

2018-05-24 05:14 UTC, MrsTonedOne approved these changes

2018-06-01 09:39 UTC, AnturK reviewed
Anyway will throw a testmerge of this up

2018-06-01 20:57 UTC, optimumtact commented on code/modules/admin/verbs/individual_logging.dm
> +		dat += "<p> No client attached to mob </p>"
There's a mob specific log set below it that will show you all the logs for the mob itself.

Previously that was all that was gettable when a client  was connected as well.

I've been meaning to add some way to access data of clients who are disconnected, but thats a more general problem (i.e we need to get notes/bans/logs (if they connected this round) for disconnected clients)

coming soon the omni panel that loads the last 300 ckeys connected via the db

2018-06-02 12:27 UTC, AnturK requested changes
One minor tweak and i'll merge this.

2018-06-02 12:27 UTC, AnturK commented on code/modules/admin/verbs/individual_logging.dm
> +/proc/show_individual_logging_panel(mob/M, source = "Client", type = INDIVIDUAL_ATTACK_LOG)
Could you define that "Client" please.

2018-06-03 19:18 UTC, KorPhaeron commented
@optimumtact

2018-06-06 08:45 UTC, optimumtact commented
@AnturK

2018-06-06 09:10 UTC, merged