Provides a link to round specific logs/stats on statbus when the round reboots.
tgstation/tgstation pull request #37896
Opened 2018-05-17 16:02 UTC by ShizCalev

or if a downstream doesn't have a fancy statbus system, they can insert a URL link to their own log location so folks can find them. 

Closes #37873

@MrStonedOne

2018-05-17 17:58 UTC, nfreader commented
We discussed linking statbus to the game previously, but making this a config option is probably ok.

2018-05-17 18:06 UTC, Cyberboss requested changes

2018-05-18 02:35 UTC, SpaceManiac commented on code/controllers/subsystem/ticker.dm
> +		to_chat(world, "<span class='info'>Round statistics and logs can be viewed at [statspage][GLOB.round_id]</span>")
Should probably explicitly link this because there is desire to kill goonchat linkify except in OOC

2018-05-18 15:12 UTC, Cyberboss approved these changes

2018-05-18 15:13 UTC, merged