[s] [paid code] Communal Resource Storage [DNM]
tgstation/tgstation pull request #37901
Opened 2018-05-17 19:11 UTC by Iamgoofball

:cl: Iamgoofball
fix: The R&D console no longer has a separate duplicated UI for protolathes and circuit imprinters.
tweak: You now can use circuit imprinters and protolathes directly to print stuff.
add: All materials on the station are now stored inside the communal Ore Silo. This is housed in the Vault which has been relocated to Cargo.
add: All protolathes, techfabs, and circuit imprinters now pull resources from the Ore Silo. They no longer have their own material storage. Stuffing sheets into them will put the resources into the Ore Silo.
tweak: To get sheets/alloys, print the added sheet/alloy designs that are available at the cargo protolathe.
tweak: The ORM will still give miners their points for the ores they process, but the ores will automatically be put into the Ore Silo.
add: The Quartermaster and HoP can blacklist lathes from the pool. Newly constructed non-roundstart lathes will NOT be allowed access by default. They will also be able to access logs of what was constructed and for what resources from a computer next to the Ore Silo.
/:cl:

No more material hogging, if mining has it, everyone has it.

TODO:

- [ ] GUI for blacklisting 
- [ ] Logging system/GUI for that
- [ ] More checks to ensure an Ore Silo exists before acting on it
- [ ] Add stuffing into lathes -> ore silo
- [ ] Make new lathes link with multitools

2018-05-17 19:14 UTC, Cyberboss requested changes

2018-05-17 19:14 UTC, Cyberboss commented on code/modules/mining/ore_storage_bin.dm
> +GLOBAL_LIST_INIT(silo_access_lathes, list())
GLOBAL_LIST_EMTPY

2018-05-17 19:14 UTC, Cyberboss commented on code/modules/mining/ore_storage_bin.dm
> +	GLOB.ore_silo = src
Needs sanity checks + clear on Destroy()

2018-05-17 19:14 UTC, Cyberboss commented on code/modules/research/machinery/_production.dm
> +		GLOB.silo_access_lathes[src] = FALSE
GLOB.silo_access_lathes[src] = mapload

2018-05-17 19:28 UTC, Iamgoofball commented
Yeah I'm gonna set up multi-tool linking for new stuff soon, need to slap that on the todo list.

2018-05-17 20:04 UTC, iskyp commented
@Iamgoofball does this machine have a circuit so you can recon it

2018-05-17 20:36 UTC, YakumoChen commented
>Vault is in cargo

No. That's bad for map balance.

2018-05-17 20:43 UTC, Iamgoofball commented
@YakumoChen Your feedback doesn't matter, this is a paid PR and the request was made by our head designer.

Get used to it.

2018-05-17 21:19 UTC, PKPenguin321 commented
@Iamgoofball it should still have circuits, just not be linkable, similar to how departmental lathes already work

2018-05-17 22:05 UTC, Iamgoofball commented
dnm until https://github.com/tgstation/tgstation/pull/37904

2018-05-17 23:04 UTC, imsxz commented
Make sure that it blacklists the specific circuit board from using ore silo mats, not just the techfab itself. Otherwise people will just rebuild if they get blacklisted.

OOS but does techwebs have logging/blacklisting for point spending? Nothing irritates me more than some random engi using all the points on clown tech.

2018-05-18 00:04 UTC, kevinz000 commented
why are you killing off ORMs? just make a separate version that goes to ore silo and make that the default.

2018-05-18 00:29 UTC, Repukan commented
How does this interact with Lathes made on other z levels

2018-05-18 01:11 UTC, Wilchenx commented
@KorPhaeron Ability to toggle ORM between normal and silo mode would basically fix all of this with minimal impact on gameplay, either by a interaction in ORM screen or by screwdriving the board.

2018-05-18 01:18 UTC, Iamgoofball commented
Sorry I meant to say blocked access, to specifically prevent that from occuring

2018-05-18 05:13 UTC, Shadowflame909 commented
I'm ready to kill some greedy QMs if they cut off my supply of plasma. #scienceneedsplasma2

2018-05-18 11:03 UTC, kevinz000 commented
@Iamgoofball move the new ones to a subpath and adding it to techwebs as a silo ORM would be the high effort and better path imo, you can find/replace the paths in the main maps and keep everything else intact. old ones should still be constructable.

2018-05-18 18:37 UTC, Iamgoofball commented
lmao @ science mains trying to keep their old system of ore hogging

2018-05-18 20:01 UTC, iskyp commented
@Iamgoofball as a non science main i can say that keeping a version of the old ORM is a better idea and allows for more variety with mappers (and lets free golems do their thing)
but replacing the ORM used on station with nu-orm is a good idea

2018-05-18 20:02 UTC, Wilchenx commented
@Iamgoofball calling everyone a science main doesn't help you win this argument

xoxo

2018-05-19 06:32 UTC, Tlaltecuhtli commented
can you give cargo tech round start rifles an armor so they can protect the vault from hostile assistants?

2018-05-19 06:38 UTC, Tlaltecuhtli commented
also ;
- is there a way to eject minerals from the lathe? or from the silo?
- call it  bluespace silo ok
- instead of white list /black list there should be a "limit" that qm can set

2018-05-20 15:04 UTC, Kromgar commented
Is there anything to prevent assholes from stealing all the ore?

2018-05-20 20:55 UTC, kevinz000 commented
the real punishment of being lazy is having a wrecking goofball run through your second favorite department :+1:

2018-05-21 20:46 UTC, Shadowflame909 commented
You coders sure love departmental co-operation(escalation) also that black
list is so dumb. We all know it's gonna have cargo vs all departments (at
the very least science.) Is this what you wanted coders. Nations, but
everyone hunting for the qms id card.

On Mon, May 21, 2018, 1:24 PM Grandmother of 50 <notifications@github.com>
wrote:

> If people steal their ore, find them and kick their butt.
>
> If people take all the mats, find them and kick their butt.
>
> Or call sec I guess.
>
> Or do nothing.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/37901#issuecomment-390771324>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3meQFXOM_NCixJPkLYvHJpP5owkCwEks5t0yKKgaJpZM4UDnt2>
> .
>

2018-05-21 21:01 UTC, ExcessiveUseOfCobblestone commented
I can't help if you don't understand opportunities for non-antags to ruin something = opportunities for antags to ruin something and not make it blatantly obvious it was an antag's doing.

But yes I do like conflict (escalation) in a game where some people play almost-exclusively to get the conflict-creating roles. If you have nothing to offer I don't see why a department has to spend their round only to appease you with no ability to change that because science just _has_ to get the same amount of mats as the chef.

The solution is to make each job mechanically important in some way to everyone else so that each job has bargaining power rather than having to be spoonfed goodies.

2018-05-21 21:08 UTC, Shadowflame909 commented
I didn't really see it like that. I more or less saw it as a way to
basically be chemistry and botany's version of "no mutagen, fuck off." Type
of deal. Except more massive. If an antagonist is doing it to make
departments go to war. I can't really complain.

On May 21, 2018 2:01 PM, "Grandmother of 50" <notifications@github.com>
wrote:

I can't help if you don't understand opportunities for non-antags to ruin
something = opportunities for antags to ruin something and not make it
blatantly obvious it was an antag's doing.

But yes I do like conflict (escalation) in a game where some people play
almost-exclusively to get the conflict-creating roles. If you have nothing
to offer I don't see why a department has to spend their round only to
appease you with no ability to change that because science just *has* to
get the same amount of mats as the chef.

The solution is to make each job mechanically important in some way to
everyone else so that each job has bargaining power rather than having to
be spoonfed goodies.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/37901#issuecomment-390781597>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/Ab3meYZeJcIJ3AXHxflTzbBOO3mOTALFks5t0ytCgaJpZM4UDnt2>
.

2018-05-22 16:13 UTC, Shadowflame909 commented
You can't stop someones dreams. Only slow them down!

On Tue, May 22, 2018, 9:08 AM Grandmother of 50 <notifications@github.com>
wrote:

> Can we disallow replies via email jesus
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/37901#issuecomment-391048758>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ab3mefiE_TI5nC1q-oTglXEnM9ZPFfAaks5t1DgRgaJpZM4UDnt2>
> .
>

2018-05-22 17:29 UTC, ExcessiveUseOfCobblestone commented
Botany/Chemistry relationship sucks because Botany has no bargaining power initially but gains a ton as well as takes Chem's away once they get mutagen because if you play botany you know how to make your own and heal basically everything, even death (tfw they even have the crucial reagent for parapen juice/ rezadone).

It used to be a good trade between mutagen/omnizine.

2018-05-22 18:07 UTC, Iamgoofball commented
stop shit posting in my pr holy fuck

2018-05-22 19:15 UTC, Shadowflame909 commented
Literally no shitposts goof. Also have you ever heard of reverse psychology

On May 22, 2018 11:07 AM, "Iamgoofball" <notifications@github.com> wrote:

stop shit posting in my pr holy fuck

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/37901#issuecomment-391086990>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/Ab3meRym0UPZQRBUnLgiixlOIwDAsDevks5t1FPPgaJpZM4UDnt2>
.

2018-05-22 19:29 UTC, KorPhaeron commented
@Iamgoofball just ignore them the PR is getting merged as soon as you finish it

2018-05-22 21:15 UTC, optimumtact commented
@Shadowflame909 if you're going to reply by email, delete the existing email body first

2018-06-02 06:35 UTC, zxaber commented
So what stops the QM from unlinking all lathes at round start, if there's no HoP/Cap? What is done about an assistant sneaking into engineering and blowing all the mats on a pile of lasers or something if there's no Sec? Are we just accepting that low-pop will be (even more) terrible?

Truth be told, I'm not really even sure what this is trying to fix.

2018-06-02 15:29 UTC, KorPhaeron commented
If there are no security and no admins and no vigilantes and people grief or don't do their jobs then yes things won't function very well.

We can't have the game function flawlessly at 5-90 players with 50 some odd job slots that may or may not be filled. We can't design around the majority of critical roles being unfilled and whoever is left acting in bad faith.

2018-06-03 06:02 UTC, msgerbs commented
So... Why can't people just walk to the ORM? I'm with zxaber I don't understand what this is fixing or improving.

2018-06-11 23:16 UTC, optimumtact commented
@Iamgoofball proceed without cyberbosses changes, just manually link them

2018-06-12 00:31 UTC, Iamgoofball commented
Aight, in LA this week so I'll do it next week

2018-06-12 19:07 UTC, ExcessiveUseOfCobblestone commented
@msgerbs it's a decision between "Science/Mining has a monopoly on resources so no one else can print anything of worth" vs "dude why did you just build 50 advanced mops". We're trying the latter since we've played with the first for years.

2018-06-12 19:37 UTC, msgerbs commented
But the ORM is in a public location. I've never had any problem, assuming miners are actually mining, getting stuff out of the ORM.

2018-06-12 19:58 UTC, ExcessiveUseOfCobblestone commented
Some jobs don't have access and some don't go to the ORM because they have a perceived notion science/mining has a monopoly.

2018-06-19 05:41 UTC, MrStonedOne commented
Please self-close pr or fix merge contents within 72 hours to avoid maintainer close.

2018-06-19 07:57 UTC, optimumtact commented
you're not a maintainer nerd get out

2018-06-19 09:08 UTC, Iamgoofball commented
Why does he have tagging access to begin with
This also isn't "stale", I'm just still whiteboarding out how I want the backend for connected machines to work

2018-06-20 04:03 UTC, MrStonedOne commented
I never said I'd close it, I just said doing those things within 72 would avoid it getting closed by a maintainer.

2018-06-24 22:43 UTC, MrDoomBringer commented
![image](https://user-images.githubusercontent.com/29008542/41824470-6fb7bcea-77de-11e8-9afa-db0859e6cd8f.png)

2018-06-24 22:43 UTC, Iamgoofball commented
most of its done locally just havent committed it yet

2018-06-26 20:56 UTC, Iamgoofball commented
i cant oversee the testmerge for this so I can't verify everything is working for the live build, if someone else wants to take over pm me on discord so I can give you what I have codewise

2018-06-26 20:56 UTC, closed without merging