Adds atom linker component/mapping helper/admin browser
tgstation/tgstation pull request #37904
Opened 2018-05-17 20:49 UTC by Cyberboss

This is a component to help objects establish links at mapping time without the use of global vars. Plenty of things already do this using globals, goal is to eventually port them all. Uses a simple string id system set using `map_text`. Links can be checked in LateInitialize using GET_COMPONENT(/datum/component/atom_linker)

Things to port:

- [ ] Cycle links
- [ ] There's more, help me out here

2018-05-17 20:58 UTC, optimumtact commented
radio machinery uses heavy linking at runtime

2018-05-18 00:28 UTC, Cyberboss commented
1. Not porting cycle links since there's so many of them and they work _o k_ as is.
2. Lets' just get this merged for now. Force new things to use it (goof's PR) and slowly port the stuff as it comes along

2018-05-18 00:29 UTC, Cyberboss commented
What I'll actually probably do is change cyclelink helpers to use atom linkers

2018-05-18 00:31 UTC, Cyberboss commented
@optimumtact, care to point me to an example? My grepping is weak

2018-05-18 06:28 UTC, optimumtact commented
https://github.com/tgstation/tgstation/blob/master/code/game/machinery/telecomms/telecomunications.dm#L91

2018-05-20 21:16 UTC, Iamgoofball commented
@Cyberboss hey hey hey this needs done still

2018-05-28 14:28 UTC, Cyberboss commented
I'm done with this for now, the component and mapping helper works and I'm too busy to handle porting anything atm.

2018-05-28 21:07 UTC, optimumtact commented
it would help if it compiled

2018-05-30 09:28 UTC, SpaceManiac requested changes

2018-05-30 09:28 UTC, SpaceManiac commented on code/datums/components/atom_linker.dm
> +	return linker_lists[id]
Just put it on GLOB if it's supposed to be exposed.

2018-05-30 09:28 UTC, SpaceManiac commented on code/modules/mapping/mapping_helpers.dm
>  		return
src is not qdel'd if it doesn't find anything

2018-05-30 09:28 UTC, SpaceManiac commented on code/datums/components/atom_linker.dm
> +/atom/proc/GetLinkedAtoms(id)
When would you call this already knowing what id to pass in, if the id is intended to be defined entirely by the component?

2018-06-11 23:15 UTC, optimumtact commented
@Cyberboss you shit cunt

2018-06-11 23:15 UTC, closed without merging