Small QoL improvement on smartfridge item release
tgstation/tgstation pull request #37946
Opened 2018-05-20 07:53 UTC by yorii

[Changelogs]: 
:cl: yorii
fix: Fixed the smartfridges to be in line with all other machines and puts the released item in your hand.
/:cl:

2018-05-20 07:55 UTC, SpaceManiac submitted a review, later dismissed

2018-05-20 12:28 UTC, DaxDupont commented
oh yeah i forgot to do this

2018-05-21 19:25 UTC, SpaceManiac requested changes
If you pick Many and enter a number bigger than how many there actually are, none of them get put in your hands. It might be reasonable to simply attempt putting the item in hand every time - so vending 2 with two empty hands picks up both of them.

2018-05-21 20:30 UTC, ExcessiveUseOfCobblestone commented
In what instance would you drop say 5 of the same item but want 1/2 of those in your hands? You'd want all of them in a plant bag or something similar. If you choose more than 2 it should all go to the ground (you can get by with this by clicking 1,optional 1,many which are right beside each other)

It wouldn't exactly be a QoL if you had to take more clicks than what you did previously for a common event (you want items to go to a plant bag).

2018-05-22 05:04 UTC, yorii commented
Hmm, differing opinions here, how about I only make the withdraw of a single item put it in your hand and anything else is ejected on the tile?

2018-05-22 13:17 UTC, yorii commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +					if(desired == 1 && Adjacent(usr) && !issilicon(usr))
If I just edit this line to `if(Adjacent(usr) && !issilicon(usr))` will the `usr.put_in_hands(O)` drop the items on the ground if no hands are free?

2018-05-22 16:01 UTC, ExcessiveUseOfCobblestone commented
Perhaps you can make it put in hands if Max or Equal to your amount of arms rather than a specific 2 then. I see what he is saying and I agree it should go into your hands UNLESS you want way more items than you could realistically carry, which you'd want on the ground for single click bags which is applicable to several variants of the fridge.

2018-05-22 19:37 UTC, SpaceManiac commented
`put_in_hands` with an S will place the item on the floor beneath the mob if it fails. You can check if it returns `FALSE` and put it back on the same tile as the fridge with the usual pixel placement logic.

I think making "One" try to put in hands and "Many" always drop on tile would be best. If you want two in your hands you can click "One" twice.

2018-05-23 03:42 UTC, yorii commented
>I think making "One" try to put in hands and "Many" always drop on tile would be best. If you want two in your hands you can click "One" twice.

Yeah okay, I'll do this.

2018-05-25 09:50 UTC, merged