collector-examine
tgstation/tgstation pull request #38035
Opened 2018-05-24 14:28 UTC by Dennok

Now collector on examine shows real produced power and stored power.
Rename last_power to stored_power.

:cl: optional name here
add: Now collector on examine shows real produced power and stored power.
code: Rename last_power to stored_power.
/:cl:

[why]: Now it show only stored power.

2018-05-24 15:06 UTC, MrDoomBringer commented
>bubblegum slams into you
i see you follow standard NT collector testing procedures as well

no but really good change

2018-05-24 16:42 UTC, Tlaltecuhtli commented
its probably an hallucination

2018-05-24 16:42 UTC, Tlaltecuhtli commented
you should test if it works while soloing a bubblegun tho

2018-05-24 19:08 UTC, PKPenguin321 commented
Delete "optional name here" from :cl:

2018-05-25 01:24 UTC, SpaceManiac requested changes
One grammar item, otherwise looks good.

2018-05-25 15:12 UTC, Dennok commented on code/modules/power/singularity/collector.dm
> +			to_chat(user, "<span class='notice'>[src]'s display states that it is stored <b>[DisplayPower(stored_power)]</b>, and processing <b>[DisplayPower(min(stored_power, (stored_power*RAD_COLLECTOR_STOR
Ready

2018-05-25 15:43 UTC, Cyberboss commented on code/modules/power/singularity/collector.dm
> +			to_chat(user, "<span class='notice'>[src]'s display states that it has stored a total of <b>[stored_power*RAD_COLLECTOR_MINING_CONVERSION_RATE]</b>, and producing [(min(stored_power, (stored_power
Maybe create a function for this equation since it seems to be used in a few places

2018-05-28 08:58 UTC, Dennok commented on code/modules/power/singularity/collector.dm
> +			to_chat(user, "<span class='notice'>[src]'s display states that it is stored <b>[DisplayPower(stored_power)]</b>, and processing <b>[DisplayPower(min(stored_power, (stored_power*RAD_COLLECTOR_STOR
@SpaceManiac

2018-05-29 07:38 UTC, Dennok commented on code/modules/power/singularity/collector.dm
> +			stored_power-=bitcoins_mined
Oh, yes.You right.

2018-05-29 07:52 UTC, Dennok commented on code/modules/power/singularity/collector.dm
> +			stored_power-=bitcoins_mined
Fixed

2018-05-29 13:00 UTC, merged