[s] Stops infinite food generation by frying the same item repeatedly
tgstation/tgstation pull request #38050
Opened 2018-05-24 21:36 UTC by ShizCalev

Closes #38025

🆑 ShizCalev
fix: You can now only deepfry a single item once.
/🆑

2018-05-24 21:39 UTC, Iamgoofball commented
This shouldn't need to happen, the doublefry blocker should stop it

2018-05-24 21:45 UTC, ShizCalev commented
@Iamgoofball When you fry a non-food item and eat it, it drops the original item. You can then fry it again afterward, allowing you to boost your mood infinitely.

2018-05-24 21:49 UTC, Iamgoofball commented
just make it delete the item on frying, keeping it is stupid and was only added to appease immersion nerds

2018-05-24 22:19 UTC, XDTM commented
Sugar comes from chem dispensers, gives nutrition and is near infinite (no satiety limit either). This is less problematic in comparison.

2018-05-24 22:44 UTC, Fox-McCloud commented
>just make it delete the item on frying, keeping it is stupid and was only added to appease immersion nerds

Yeah, I dunno why the original item isn't just deleted; this would completely solve the problem.

2018-05-24 23:33 UTC, SgtxRootbeer commented
Traitor items/nuke disks, etc.

2018-05-25 00:14 UTC, PKPenguin321 commented
This is intended and this fix is stupid. You can fry literally anything and eat it, including your clothes. Preventing somebody from frying the same pair of shoes a second time won't stop them from just frying and eating some random shit they found on the floor instead.

2018-05-25 00:18 UTC, Therapist1 commented
i don’t see the point. do this and they’ll just walk over with a paper bin or card deck, take one out, fry it, discard it, and fry another

2018-05-25 02:18 UTC, SgtxRootbeer commented
tbh, as many have pointed out, this doesnt make sense and isnt an issue. why cant we stick something that we ate the breading off of back into the fryer? by then its surely not double-frying. 
that and if people want to eat, they're going to eat.

2018-05-25 15:08 UTC, davethwave commented
What makes frying a item thats been fried before after eating it horrible enough to require a fix PR? Is it even a problem in the first place? Your logic for this seems to be that it closes one of the issue's however it seems to me that this wouldn't even solve the problem, making the reasoning for this faulty.

2018-05-26 18:46 UTC, vuonojenmustaturska requested changes

2018-05-26 18:46 UTC, vuonojenmustaturska commented on code/game/objects/items.dm
> +	var/was_previously_fried //Prevents the same item from being refried multiple times
booleans like these belong in item_flags imo

2018-05-26 22:13 UTC, closed without merging