Those footprints are... moving? [Chameleon Proj will let you scan decals]
tgstation/tgstation pull request #38071
Opened 2018-05-25 15:46 UTC by ExcessiveUseOfCobblestone

:cl: Cobby
tweak: Decals are the exception to the recent removal of effects in Chameleon Projectors.
/:cl:

I was never told decals would be problematic when asked in the previous PR and didn't like that it just gutted a large possibility of items to scan. When I asked if these would ever be a problem, I was ignored. I could probably just change it to only exclude temp effects like Naksu said previously but I don't want to play gotcha with a rogue one and have my PR closed over it.

I'm not looking for major balance discussion, I'm ensuring that the "fix" pr remains just that or at least the decal question gets properly addressed. If there were/are actual balance issues, it should have been PR'd separately from a legitimate bug or at least called out in the PR rather than throwing it under the bugfix umbrella.

Again, for those seeking balance discussion (preferably not on my PR),

# The default option is a common, two pixel item.

Oh and I expanded the centipede-if into readable items.

2018-05-26 14:00 UTC, kevinz000 commented
The default option also likely won't be literally everywhere in the halls in the average shift unless a janitor is very thorough. 
Chameleon projector does NOT need buffs when it's already something you use to guarantee the first hit in a fight and to dodge projectiles/instantly disappear.

2018-05-27 09:20 UTC, SpaceManiac requested changes
Otherwise looks good

2018-05-27 09:20 UTC, SpaceManiac commented on code/game/objects/items/devices/chameleonproj.dm
> +	if(!active_dummy) //I now present you the blackli(f)st
This could just be an `if(active_dummy) return` like everything else

2018-05-27 20:39 UTC, SpaceManiac approved these changes

2018-05-27 20:44 UTC, merged