Fixes banhammer grammar
tgstation/tgstation pull request #38078
Opened 2018-05-25 19:53 UTC by Michael-Ashfield

[Changelogs]: # Fixed grammar on the banhammer item when used on players heads.
Converts:
"[user] are stroking the head of [M] with a bangammer"
To:
"[user] is stroking the head of [M] with a banhammer"
Fixes and additional "Bangammer" to its correct spelling.

:cl: Mickyy5
spellcheck: Fixed grammar on the banhammer
/:cl:

[why]: # The banhammer item had incorrect grammar and spelling when being targeted on the head.

2018-05-25 20:41 UTC, SpaceManiac requested changes

2018-05-25 20:41 UTC, SpaceManiac commented on code/game/objects/items/weaponry.dm
> +		M.visible_message("<span class='danger'>[user] is stroking the head of [M] with a banhammer</span>", "<span class='userdanger'>[user] is stroking the head with a banhammer</span>", "you hear a banh
Use `[user] [user.p_are()] stroking`. It'll come out to "is" most of the time but remain "are" in the narrow cases where doing so is appropriate.

2018-05-25 20:47 UTC, SpaceManiac commented on code/game/objects/items/weaponry.dm
> +		M.visible_message("<span class='danger'>[user] is stroking the head of [M] with a banhammer</span>", "<span class='userdanger'>[user] is stroking the head with a banhammer</span>", "you hear a banh
Actually I'm not entirely sure about this, I'll take a deeper look at some point.

2018-05-25 21:51 UTC, optimumtact commented
This is a meme relating to the english translation of the ss13 russian wiki page on lurkmore.

This is now the second pr fixing this so at this point I don't even care to keep it

2018-05-26 10:46 UTC, SpaceManiac commented
If it's intended add a comment so people know that and move on

2018-05-26 20:18 UTC, MrDoomBringer commented
Means that one of the crew members works for a criminal Syndicate and
must something to seize / kill someone / someone to protect and dump
from that Durkee on the shuttle. At English stations the word everyday,
for Russians for the mention of the word "traitor" is not in the chat
(IC) admins are stroking the head with a bangammer. So this word and
memetic.

2018-05-26 20:19 UTC, MrDoomBringer commented
[mfw newfags dont bangammer](https://github.com/tgstation/tgstation/pull/30173)

2018-05-28 05:40 UTC, ninjanomnom commented
Well I'm certainly fine doing that especially seeing as they haven't responded to anything in here. If someone wants to add a comment in another pr, go for it.

2018-05-28 05:40 UTC, closed without merging