Delta toxins lab DLC
tgstation/tgstation pull request #38110
Opened 2018-05-27 14:42 UTC by 81Denton

:cl: Denton
tweak: Deltastation's firing range has been decommisioned and replaced with a brand new toxins burn chamber. 
fix: Delta toxins disposals are now actually connected to the disposals loop. Toxins storage has a fire alarm too.
/:cl:

RIP RnD printing guns, I replaced the now unused shooting range with a toxins burn chamber and integrated it with the toxins mixing lab.
Also, connected toxins disposals to the disposal loop, replaced the heater with a filter and added a missing fire alarm to toxins storage.

If anyone has an idea what to do with the Meta firing range, let me know.

2018-05-27 15:10 UTC, 81Denton commented
Since mapdiffbot isn't showing me the changes:

![hhhhh](https://user-images.githubusercontent.com/32391752/40587551-c9f2de48-61d0-11e8-9b21-a163188eaa5c.PNG)

2018-05-27 16:54 UTC, KomradeSpectre commented
Looks good to me! 👍

2018-05-27 16:56 UTC, ShizCalev commented
![diff](https://user-images.githubusercontent.com/6209658/40588563-4ec277e2-61ad-11e8-95d3-264b8495fd18.png)
think you hit a few valves there by accident.

2018-05-27 17:12 UTC, 81Denton commented
That explains a lot, I‘ll fix it in a little

2018-05-27 18:46 UTC, Tlaltecuhtli commented
why is there blob

2018-05-27 19:09 UTC, Mark9013100 commented
it's a dynamic spawn for blobs, every map has them

2018-05-27 19:38 UTC, 81Denton commented
@ShizCalev I readded the three valves, Mapdiffbot just shows the two western ones as modified still.

2018-05-27 20:06 UTC, ShizCalev requested changes

2018-05-27 20:06 UTC, ShizCalev commented on _maps/map_files/Deltastation/DeltaStation2.dmm
> +	icon_state = "mvalve_map";
DV

2018-05-28 05:14 UTC, ShizCalev commented
I'm not too wild on having a blob start inside the exterior chamber since the mere act of the blob spawning there could/would release burning gases and stunt it's growth for a good period.

2018-05-28 11:59 UTC, Thunder12345 commented
Blob spawn points don't matter now anyway, the overmind just spawns there, but they pick where to drop the core

2018-05-28 15:33 UTC, merged

2018-05-30 06:43 UTC, zaracka commented
Good PR, this was the only thing DeltaStation was lacking. I kind of enjoyed the variation between maps, but more options is better, I suppose.

Probably should have stated this earlier, but 2 things.

One, the directional windows aren't really necessary. They can get annoying when the other sides both have wrenched canisters blocking the freezer, meaning you can't interact with it. However, it's like this on other maps, so whatever... consistency. Although on other maps, they're reinforced windows.

Two, please leave at least one portable scrubber and air pump. These are useful and other maps have them.