Adds module upgrades for the Janiborg.
tgstation/tgstation pull request #38114
Opened 2018-05-27 19:24 UTC by Firecage

This PR adds two new upgrades for the Janiborg. Well, technically adds their first upgrades since they didn't have any module specific ones. These are the Advanced Mop and the Trash Bag of Holding.

:cl: Firecage
add: The mech fabricator can now print two new janiborg upgrades. Advanced Mop and Trash Bag of holding. These two upgrades uses the advanced robotics node.
/:cl:

2018-05-29 03:07 UTC, YakumoChen commented
Instead of making it a new node why not just add it to the Advanced Robotics Programming or whatever it's called that only had the Diamond Drill upgrade and is otherwise a dead end?

2018-05-29 23:23 UTC, SpaceManiac requested changes
I agree with YakumoChen here. I don't think it's a big problem if cyborg janitorial doesn't actually require human janitorial; things can always be rearranged later if it's needed. The cyborg diamond drill doesn't require the regular diamond drill.

2018-05-30 04:57 UTC, YPOQ commented on code/game/objects/items/robot/robot_upgrades.dm
> +		for(var/obj/item/storage/bag/trash/cyborg/TB in R.module)
R.module only contains the not-currently-equipped modules. R.module.modules has all equipped and unequipped modules.

2018-05-30 09:45 UTC, Firecage commented
Alright, will do so.

2018-05-31 01:08 UTC, SpaceManiac approved these changes

2018-05-31 01:09 UTC, merged