Logs minor and major crimes
tgstation/tgstation pull request #38358
Opened 2018-06-08 15:40 UTC by nfreader

:cl: atlanta_ned
:add: Simply adds minor and major crimes to the records.html investigate log
/:cl:

[why]: More logs for the log gods and I'm curious to see what people are being arrested for.

2018-06-08 16:14 UTC, ShizCalev requested changes

2018-06-08 16:14 UTC, ShizCalev commented on code/game/machinery/computer/security.dm
> +							investigate_log("New Major Crime: <strong>[t1]</strong>: [t2] | Added to [active1.fields["name"]] by [usr.name] ([usr.key])", INVESTIGATE_RECORDS)
[key_name(usr)]

2018-06-08 16:14 UTC, ShizCalev commented on code/game/machinery/computer/security.dm
> +							investigate_log("New Minor Crime: <strong>[t1]</strong>: [t2] | Added to [active1.fields["name"]] by [usr.name] ([usr.key])", INVESTIGATE_RECORDS)
[key_name(usr)]

2018-06-08 16:14 UTC, ShizCalev commented on code/modules/mob/living/carbon/human/human.dm
> +													investigate_log("New Minor Crime: <strong>[t1]</strong>: [t2] | Added to [R.fields["name"]] by [usr.name] ([usr.key])", INVESTIGATE_RECORDS)
[key_name(usr)]

2018-06-08 16:14 UTC, ShizCalev commented on code/modules/mob/living/carbon/human/human.dm
> +													investigate_log("New Major Crime: <strong>[t1]</strong>: [t2] | Added to [R.fields["name"]] by [usr.name] ([usr.key])", INVESTIGATE_RECORDS)
[key_name(usr)]

2018-06-08 16:54 UTC, ShizCalev submitted a review, later dismissed

2018-06-08 16:56 UTC, ShizCalev requested changes

2018-06-08 16:56 UTC, ShizCalev commented on code/modules/mob/living/carbon/human/human.dm
> +													investigate_log("[src.key] has been set from [R.fields["criminal"]] to [setcriminal] by [key_name(usr)].", INVESTIGATE_RECORDS)
[key_name(src)] at the start too, please.

2018-06-08 16:57 UTC, nfreader commented
Also cleaned up a few other places where `key_name` should be used ^_^ I got that consistency HYPE 🎉

2018-06-08 17:11 UTC, ExcessiveUseOfCobblestone commented
hey cutie ;)

2018-06-08 18:22 UTC, ShizCalev approved these changes

2018-06-09 00:18 UTC, Iamgoofball commented
Did you fix the thing where the stats site would be missing stats on some stuff that we found when going over syndie items? You said it was on your end and I made sure the code wasn't dropping stats for any reason, we removed the stupid black box destruction deleting stats ages ago.

Because I've been asking for months if you fixed that, and stat gathering is useless if the stats can get shot down in any balance debate with "well it missed a ton of rounds so its worthless data"

2018-06-09 01:05 UTC, ShizCalev commented
@cacogen why downvote?

2018-06-09 17:21 UTC, merged