You can see what other people eat or drink
tgstation/tgstation pull request #38395
Opened 2018-06-10 03:59 UTC by cacogen

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: cacogen
add: You can now see what other people are eating or drinking.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I like renaming food and drinks but it's not very satisfying when you can't see them eat it.

2018-06-10 10:12 UTC, SpaceManiac requested changes
Grammar might not turn out perfect in all cases (`eatverb="gnosh"`) but w/e, it's not trivial to fix

2018-06-10 10:12 UTC, SpaceManiac commented on code/modules/food_and_drinks/food/snacks.dm
> +				user.visible_message("[user] cannot force any more of \the [src] to go down [user.p_they()] throat!</span>", "<span class='warning'>You cannot force any more of \the [src] to go down your throat!
Should be `p_their()`

2018-06-10 12:29 UTC, AlexTheSysop42 commented
Make it only when a person eats it themself so others can't see you poisoning someone by force feeding them

2018-06-10 16:44 UTC, Mickyan commented
I have a feeling this might lead to more chat spam than it's worth for something that's irrelevant to other players 99% of the time, would it be possible to add a cooldown to it?

2018-06-10 17:34 UTC, improvedname commented
just make it when they finish the meal

2018-06-10 17:51 UTC, Dorsisdwarf commented
but then if someone labels the food "dicks" with a pen nobody can eat it, rule 8

2018-06-10 23:32 UTC, cacogen commented
>chat spam

Goonchat makes this irrelevant now

2018-06-11 09:00 UTC, Ratvar commented
What's the blood made is? Can it be used for blood transfusions to everyone?

2018-06-11 17:05 UTC, Cyberboss commented
Blood seems odd to synthesize, yeah

2018-06-13 09:34 UTC, merged