Adds shuttle docks to runtimestation
tgstation/tgstation pull request #38507
Opened 2018-06-15 16:59 UTC by 81Denton

:cl: Denton
tweak: Runtimestation: Added shuttle docking ports, a comms console, cargo bay and syndicate/centcom IDs.
/:cl:

Right now there is no test map for shuttles; using the regular maps gets pretty annoying.
I added all docks while trying to keep the layout compact - arrivals, departures, pods, cargo, gulag, mining, ferry, aux/whiteship. 

Also, added syndie/centcom IDs for ID/access testing and some light fixtures to the western construction area.

[Screenshot](https://i.imgur.com/iWVscOH.png)

2018-06-15 19:13 UTC, ShizCalev requested changes

2018-06-15 19:13 UTC, ShizCalev commented on _maps/map_files/debug/runtimestation.dmm
> +	icon_state = "direction_supply";
dv

2018-06-15 19:13 UTC, ShizCalev commented on _maps/map_files/debug/runtimestation.dmm
> +	icon_state = "direction_eng";
dv

2018-06-15 19:13 UTC, ShizCalev commented on _maps/map_files/debug/runtimestation.dmm
> +	icon_state = "direction_eng";
dv

2018-06-15 19:13 UTC, ShizCalev commented on _maps/map_files/debug/runtimestation.dmm
> +	icon_state = "direction_supply";
dv

2018-06-15 19:13 UTC, ShizCalev commented on _maps/map_files/debug/runtimestation.dmm
> +	name = "MetaStation emergency evac bay";
if you'd be so kind, please rename this

2018-06-15 20:21 UTC, 81Denton commented on _maps/map_files/debug/runtimestation.dmm
> +	name = "MetaStation emergency evac bay";
Ok, done!

2018-06-16 06:34 UTC, ShizCalev submitted a review, later dismissed

2018-06-16 09:11 UTC, SpaceManiac commented
Can you add fans to the escape pod bay as in #38523, so we're not knowingly causing roundstart ATs? Otherwise looks good.

2018-06-16 09:29 UTC, 81Denton commented
Yeah, I'll ping you once it's done.

2018-06-16 15:51 UTC, 81Denton commented
@SpaceManiac Done!

2018-06-16 20:36 UTC, merged