PDA can be ctrl-clicked to remove the item in its pen slot
tgstation/tgstation pull request #38577
Opened 2018-06-18 15:03 UTC by Irafas

:cl: 
add: Players can now ctrl-click the PDA to remove the item in its pen slot
/:cl:

This just makes taking the pen, or other items, out of the PDA easier. Now you can do it with just one click and one hand.

2018-06-18 15:18 UTC, TBartl commented
What happens if you try to pull a PDA by CTRL+Clicking it?

2018-06-18 15:24 UTC, ExcessiveUseOfCobblestone commented
Just switch the order in alt click.

2018-06-18 15:28 UTC, Irafas commented
@TBartl 
SHIT
I'm an idiot as I somehow forgot about that. Might as well close this PR in shame

@ExcessiveUseOfCobblestone 
Most people care more about removing the ID first so I think that's not going to be very useful. Also I found that there's a verb for removing the pen from a PDA already, so this PR isn't really necessary.

2018-06-18 15:31 UTC, ExcessiveUseOfCobblestone commented
At the end of the day you're just alt clicking twice either way lol

2018-06-18 17:08 UTC, fludd12 commented
Wait nooooo reopen this and make it work only when loc is not a turf

It's not like someone will pull it in their ID slot

2018-06-18 17:38 UTC, Irafas commented
Alright should work now, Thanks @fludd12 for the solution.

2018-06-18 17:45 UTC, ExcessiveUseOfCobblestone requested changes

2018-06-18 17:45 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/devices/PDA/PDA.dm
> +		to_chat(user, "<span class='notice'>Alt-click to remove contents.<br>Ctrl-click to remove item from pen slot</span>")
Only if it's on you.

2018-06-18 17:45 UTC, Cyberboss requested changes

2018-06-18 17:45 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +		to_chat(user, "<span class='notice'>Alt-click to remove contents.<br>Ctrl-click to remove item from pen slot</span>")
This line needs better wording

2018-06-18 17:56 UTC, Cyberboss requested changes

2018-06-18 17:56 UTC, Cyberboss commented on code/game/objects/items/devices/PDA/PDA.dm
> +		to_chat(user, "<span class='notice'>Alt-click to remove contents.<br>Ctrl-click, while its in an inventory, to remove the pen</span>")
Remove the comma after Ctrl-click

2018-06-18 17:58 UTC, Cyberboss submitted a review, later dismissed

2018-06-18 18:03 UTC, ExcessiveUseOfCobblestone commented
Feel free to use

```javascript
if(id)
    to_chat(user, "<span class='notice'>Alt-click to remove [id].</span>")
if(inserted_item && (!isturf(loc)))
    to_chat(user, "<span class='notice'>Ctrl-click to remove [inserted_item].</span>"
```

The secret "Alt-click to remove the pen if the pen isn't there" can be just that.

2018-06-18 18:31 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/devices/PDA/PDA.dm
> +		to_chat(user, "<span class='notice'>Alt-click to remove the id.</span>")
Probably a wise decision.

2018-06-19 14:48 UTC, Cyberboss approved these changes

2018-06-19 14:49 UTC, merged