Cyborgs now drop radio keys on detonation/destruction
tgstation/tgstation pull request #38617
Opened 2018-06-19 21:49 UTC by kevinz000

Why: Radio keys as of now are not replaceable, and being able to retrieve them from destroyed cyborgs would be a useful thing.

2018-06-19 22:53 UTC, GunHog commented
Please test that destroyed AI shells do not drop their radio keys.

2018-06-20 07:44 UTC, SpaceManiac requested changes

2018-06-20 07:44 UTC, SpaceManiac commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/turf/T = get_turf(loc)//To hopefully prevent run time errors.
should be drop_location

2018-06-20 20:55 UTC, SpaceManiac commented
also needs CL

2018-06-21 23:14 UTC, Cyberboss requested changes

2018-06-21 23:14 UTC, Cyberboss commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/turf/T = drop_location()//To hopefully prevent run time errors.
atom not turf

2018-06-21 23:23 UTC, optimumtact commented
this is a poor quality fix that papers over the real issue which is that you can't construct radio keys when they should be available (probably best to put them in engineering's proto lathe (at roundstart))

:-1:

2018-06-22 00:52 UTC, Cyprex commented
How do you mediate access though? Letting engineering lathes manifacture captain's keys unrestricted doesn't seem like a great idea.

2018-06-22 03:00 UTC, davethwave commented
each compartment can build there own radio key then?

2018-06-22 03:14 UTC, optimumtact commented
ah fuck I completeyl forgot about that

2018-06-22 11:51 UTC, Dorsisdwarf commented
does this mean that now as soon as the syndieborg dies op radio is compromised and theres nothing the ops can do to prevent it?

2018-06-22 14:10 UTC, ExcessiveUseOfCobblestone commented
@Dorsisdwarf They could secure the corpse, unlike ops themselves who just drop everything on the floor (a headset is usually a given).

2018-06-23 00:05 UTC, Dorsisdwarf commented
Ops dont drop things on the floor do they? their bomb implant exists specifically for the purpose of vaporising their gear, so its only through op incompetence (not deathgasping in crit) that crew can get headsets

2018-06-23 03:18 UTC, improvedname commented
All ops gear is just destroyed excepy the headset usually

2018-06-23 19:03 UTC, merged

2018-06-25 14:07 UTC, ExcessiveUseOfCobblestone commented
@Dorsisdwarf I always get their gear, typically mask headset and heavily damaged gloves/boots.