Dream fixes
tgstation/tgstation pull request #38884
Opened 2018-07-03 01:42 UTC by MacHac

Closes #38860.

:cl: MacHac
fix: Silicons, pAIs, and simple animals can no longer modify circuits.
/:cl:

Also fixes a misspelling of the word 'dexterity' that was bugging me.

2018-07-03 10:17 UTC, Time-Green commented
your title fucked up

2018-07-03 13:41 UTC, MacHac commented
whups

2018-07-04 14:11 UTC, Cyberboss requested changes

2018-07-04 14:11 UTC, Cyberboss commented on code/modules/integrated_electronics/core/assemblies.dm
> +	return istype(user, /mob/living/carbon) && user.canUseTopic(src, BE_CLOSE)
iscarbon

2018-07-09 18:51 UTC, ExcessiveUseOfCobblestone commented
I'm confused, how does this fix the bug?

2018-07-12 16:16 UTC, Cyberboss commented
You're PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

2018-07-13 22:09 UTC, closed without merging