Gibs squelch when walked over
tgstation/tgstation pull request #38922
Opened 2018-07-05 00:37 UTC by cacogen

:cl: cacogen
add: Gibs squelch when walked over
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

This makes them more visceral. Plus more sound effects are always good.

2018-07-05 02:13 UTC, JJRcop commented
Can you source the sound effect?

2018-07-05 03:55 UTC, MrDoomBringer commented
good PR

2018-07-05 20:31 UTC, Fox-McCloud commented on code/game/objects/effects/decals/cleanable/humans.dm
> +			playsound(loc, 'sound/effects/gib_step.ogg', 20, 1)
`playsound(loc, 'sound/effects/gib_step.ogg', L.has_trait(TRAIT_LIGHT_STEP) ? 20 : 50, 1)`

2018-07-06 16:40 UTC, ninjanomnom requested changes

2018-07-06 16:40 UTC, ninjanomnom commented on code/game/objects/effects/decals/cleanable/humans.dm
> +	. = ..()
`return ..()`

2018-07-06 16:42 UTC, Jalleo requested changes
Under the licence that you have linked through that website it says we need to link to the person in the way they wanted and as such how do they want their attribution to be known.

2018-07-07 04:17 UTC, Shadowflame909 commented
Cacogen would like there attribution to be known by re-enabling coder credits and making the entire serverbase angry

2018-07-08 01:59 UTC, cacogen commented
@Jalleo 

There's a link to that sound file in the .ogg, is that good enough? Otherwise I'll have to find another file.

2018-07-08 02:10 UTC, merged