Emitters no longer sometimes produce sparks upon firing
tgstation/tgstation pull request #38965
Opened 2018-07-07 08:40 UTC by Anonmare

[Changelogs]: Emitters no longer sometimes produce sparks on firing.

:cl: 
del: Emitters no longer sometimes produce sparks on firing 
/:cl:

[why]: I've noticed a lot that with the fact that sparks heat up the air, it can render the laser room of engineering uninhabitable from the high heat - especially with many/sufficiently upgraded emitters.  I've also noticed this sometimes causing plasma to spontaneously ignite in a few circumstances.

2018-07-07 10:09 UTC, Time-Green commented
Took me a second to realize you were removing it altogheter instead of making it spark on evey shot

2018-07-07 11:33 UTC, 81Denton commented
Letting sparks heat up air without going through every single spark source to make sure shit like this doesn't happen was a mistake

2018-07-07 12:46 UTC, Dorsisdwarf commented
Removing sparks from high-powered machinery because a bug makes those sparks superheat an area is dumb, fix the problem not the symptoms

2018-07-07 13:41 UTC, Kromgar commented
Its not a bug sparks are supposed to heat the aur for some dumb reason

2018-07-07 13:57 UTC, Qustinnus commented
then make the emitter's sparks not do that?

2018-07-07 18:00 UTC, subject217 commented
@dorsisdwarf It was already "nerfed" in https://github.com/tgstation/tgstation/pull/38232
The intrisnic issue (sparks are used as fluff to make stuff look cooler and arguing about conservation of energy is extremely silly) is still present, which is why you run into niche cases like the emitter room being an inferno 40 minutes in or RPDs being used to spam sparks and make rooms unlivable.

That entire heating air PR is a feature nobody asked for that just makes the game worse and more annoying to play.

2018-07-07 18:09 UTC, 81Denton commented
Honestly, I don't see an issue with reverting all of it except for bonfires. The rest adds absolutely zero interesting interactions to the game while creating annoying issues.

2018-07-07 18:10 UTC, Jalleo commented
The proper solution is to get sparks to give off a scaling heat depending on X reason given to it by each item. A lot of upgraded emmiters should be giving off a fuck ton of heat. This is something that engineers can work on as a addition to their mad engine setup. Keeping the room itself cool.

2018-07-08 23:01 UTC, ninjanomnom requested changes
@Dorsisdwarf is right, fix the base cause with sparks if you want to deal with this issue

2018-07-09 12:29 UTC, closed without merging