Allow players to un-ignore previously ignored popups for ghostroles, and ignore notifications with no ignore button
tgstation/tgstation pull request #38990
Opened 2018-07-08 17:32 UTC by vuonojenmustaturska

:cl: Naksu
add: Added a new ghost verb that lets you change your ignore settings, allowing previously ignored popups to be un-ignored and notifications without an ignore button to be ignored
/:cl:

![image](https://user-images.githubusercontent.com/20017308/42422390-c10f61be-82ed-11e8-8ece-fae4498439e7.png)

2018-07-08 17:51 UTC, Ratvar commented
where's "Do you want to play as Rob Ust? Job: Tator toe" preference, tho

2018-07-08 22:39 UTC, BeeSting12 commented
I love you

2018-07-09 03:19 UTC, Shadowflame909 commented
WHERES THE MINEBOT OPTION. Accidentally clicking yes to it is the worst thing ever reeeeeeeeeee

2018-07-09 09:45 UTC, vuonojenmustaturska commented
minebot is sentience potion

2018-07-09 19:06 UTC, ninjanomnom requested changes

2018-07-09 19:06 UTC, ninjanomnom commented on code/modules/mob/dead/observer/notificationprefs.dm
> +datum/notificationpanel
/

2018-07-09 19:06 UTC, ninjanomnom commented on code/modules/mob/dead/observer/notificationprefs.dm
> +datum/notificationpanel/New(user)
/

2018-07-09 19:06 UTC, ninjanomnom commented on code/modules/mob/dead/observer/notificationprefs.dm
> +datum/notificationpanel/ui_interact(mob/user, ui_key = "main", datum/tgui/ui = null, force_open = FALSE, datum/tgui/master_ui = null, datum/ui_state/state = GLOB.observer_state)
/

2018-07-09 19:06 UTC, ninjanomnom commented on code/modules/mob/dead/observer/notificationprefs.dm
> +datum/notificationpanel/ui_data(mob/user)
/

2018-07-09 19:06 UTC, ninjanomnom commented on code/modules/mob/dead/observer/notificationprefs.dm
> +	if (istype(user, /mob))
ismob

2018-07-09 19:10 UTC, ninjanomnom approved these changes

2018-07-09 19:24 UTC, merged