SDQL queries are now on statbus
tgstation/tgstation pull request #39141
Opened 2018-07-14 18:03 UTC by kevinz000

Makes them logged similar to internet sounds
Already in public logs, why not?
I also want to see how many people actually use this.

2018-07-15 05:01 UTC, Cyberboss commented
it only you

2018-07-16 02:08 UTC, nfreader commented
>SQL-like queries in SQL
Are we sure this is safe? (I'm assuming it is but I wanna double check)

2018-07-16 03:54 UTC, Cyberboss requested changes

2018-07-16 03:54 UTC, Cyberboss commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +	SSblackbox.record_feedback("nested tally", "SDQL query", 1, list("[ckey]", "[query_text]"))
no need to quote the list items

2018-07-16 03:55 UTC, Cyberboss commented
It's escaped json data, so its fine

2018-07-20 01:17 UTC, merged