Rebalances the deep space storage bunker space ruin.
tgstation/tgstation pull request #39186
Opened 2018-07-17 09:03 UTC by WJohn

Because 6 boxes of 9mm ammo (180 rounds!) and two wt-550s is just dumb, especially if you got the 9mm APS pistol from the caravan ruin.

Reduced that to 3 magazines (45 rounds) and one wt-550 with one spare compatible mag for it (so you cannot dual wield that, and also have to spend time reloading instead of just pulling out another gun).

Also reduced the amount of food in the food storage by half and made it look a bit neater (I do love me some stacked looking items in crates and racks).

Lastly, turned the syndicate hardsuit into a regular grey space suit. We don't need non-antags freaking people out over it and it's very, very strong space armor to boot. It was also weirdly out of place with the aesthetic of the ruin, being the *only* thing that pointed to it being syndicate base at all.

:cl: WJohnston
balance: Reduced the 180 rounds (6 boxes) of 9mm ammo in the deep storage bunker to 45 (3 mags). Removed one of the wt-550s but put a compatible magazine in its place for the other to use. Turned the syndicate hardsuit into a regular grey space suit.
/:cl:

2018-07-17 09:04 UTC, Hatterhat commented
wack

2018-07-17 09:08 UTC, subject217 commented
>We don't need non-antags freaking people out over it and it's very, very strong space armor to boot.
Miner legion loot does it anyway. At any rate I always felt the hardsuit was pretty harmless, doesn't really need to go IMO.

2018-07-17 09:12 UTC, duckay commented
it could do with turrets, but removal of the only guaranteed method to get a bloodred is hurty and painy
wack

2018-07-17 09:48 UTC, WJohn commented
Miner's equipment and loot is not a good baseline to compare anything in the game to. It is in its own league.

2018-07-17 10:07 UTC, Tlaltecuhtli commented
9mm ammo is autolathe printable, the sec auto rifles (they use 4.57 ammo not 9mm ammo) are garbage as they are pretty much ballistic generic lasers, nuke op suit which is somewhat worth wasting half the round navigating space and hacking 3 strong doors is a free ticket to being stripped by sec and looted also anti meta

2018-07-17 10:24 UTC, Grazyn commented
Deep storage has a GPS (DEEP tag IIRC) so it's not really that hard to find

2018-07-17 10:31 UTC, Tlaltecuhtli commented
you still have to go trough randomized maps to get in the right place, get jetpack gloves and other stuff to start exploring

2018-07-17 14:13 UTC, AlexTheSysop42 commented
> only thing that pointed to it being syndie

Pretty sure the notes on the bulletin board do too

2018-07-17 17:06 UTC, Anonmare commented
Remove the GPS and add turrets

2018-07-17 19:37 UTC, WJohn commented
@Grazyn Nope, none of the notices point to that at all.

2018-07-18 02:30 UTC, Supermichael777 commented
>everyone admits mining is unbalanced.

>vocal minority insists ![image](https://user-images.githubusercontent.com/11540177/42855928-cec40d44-8a10-11e8-9a59-05be7759f1b5.png)

>power-creep impossible to tamp despite being swiftly whacked elsewhere because "muh monster-hunter" tangential to the job

2018-07-18 07:53 UTC, Bawhoppen commented
Remove GPS pls. Also remove the fact it's a miniature station rather than just a shitty bunker.

2018-07-18 13:09 UTC, AlexTheSysop42 commented
Elite hardsuit has better armor and shield suit has a shield.

Also the ammo (and beans) stockpile makes sense because it's a bunker, the idea is to bring enough supplies that you don't have to leave for years.

2018-07-18 13:19 UTC, WJohn commented
I can re-add the extra food supplies, I suppose. But the armor really is incredibly strong, boasting 40/50/30/15 (melee, laser, bullet, energy) protection. This is roughly tied in durability with the HoS's personal hardsuit! And it's just sitting out in the open easy to steal with nothing protecting it. I think above all else that is the thing that must go.

2018-07-18 14:42 UTC, ExcessiveUseOfCobblestone commented
d-d-d-d-dont you have to go into space to get this space suit though?

2018-07-18 16:23 UTC, Grazyn commented
The amount of beans is excessive, it makes sense to tone it down. There are enough beans in there to make the kitchen irrelevant for an entire marathon round.

2018-07-19 01:10 UTC, Suicidalpickles commented
although the syndie hardsuit does have some decent armor, can be bagged, and has a built-in jetpack, it has the risk of being lynched for even using it among the crew tbh. Don't see how its too problematic, considering its just a single suit. If the concern is over people panicking and assuming there's ops over seeing it about, maybe just give the suit a new color scheme? Bluesuit sounds pretty rad.

2018-07-19 21:47 UTC, blobbernaut commented
Johnston, who the fuck cares if it's on par with the HOS hardsuit? Yeah, wow, some spaceloot's on par with a head's starting gear! SHUT DOWN EVERYTHING!

It's not even that good, anyway. You're a bit more durable to lasers and spears, you still go down to a taser or a few disablers. It's not good because of the armor, it's good because of the utility. Fits in a backpack and has a jetpack. 

It's kind of crazy you're allowed to change things when you do not even understand what is good about an item, holy shit.

2018-07-19 21:59 UTC, ExcessiveUseOfCobblestone commented
You can disagree and not formulate it in such a rude manner.

2018-07-20 00:00 UTC, Repukan commented
Yo this nigga eating beans in the abandoned bunker

2018-07-20 01:54 UTC, Anonmare commented
If it's purely utility, then why not replace it with the soft syndicate spacesuit?

2018-07-20 02:29 UTC, ShizCalev submitted a review, later dismissed

2018-07-20 20:20 UTC, ninjanomnom requested changes

2018-07-20 20:20 UTC, ninjanomnom commented on _maps/RandomRuins/SpaceRuins/deepstorage.dmm
> +/obj/structure/closet/crate{
There seems to be 2 of these on the tile

2018-07-20 20:20 UTC, ninjanomnom commented on _maps/RandomRuins/SpaceRuins/deepstorage.dmm
> +/obj/structure/closet/crate{
Same as above

2018-07-21 04:29 UTC, ninjanomnom approved these changes

2018-07-21 04:29 UTC, merged

2018-07-23 15:43 UTC, blobbernaut commented
Remember, you should have no incentive to visit space in a space station
game! Remove all z-levels!

2018-07-24 00:08 UTC, OmegaShoots commented
>Let's remove any reason for anyone to want to explore off station, and instead just force them to stay on station looking for valids because everything ELSE on station that's fun also gets removed

:clap:

2018-08-09 16:56 UTC, blobbernaut commented
basically

On Mon, Jul 23, 2018 at 8:08 PM, OmegaShoots <notifications@github.com>
wrote:

> Let's remove any reason for anyone to want to explore off station, and
> instead just force them to stay on station looking for valids because
> everything ELSE on station that's fun also gets removed
>
> 👏
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/39186#issuecomment-407238354>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMvFBbVEMxel1XYg0PtQvqRZ6tJNGEhHks5uJmWFgaJpZM4VSdIw>
> .
>

2018-08-09 21:59 UTC, epochayur commented
\> +1, -18
\>merged anyway
🤔

2018-09-06 07:50 UTC, Barhandar commented
Don't call straight nerf "rebalancing".