Updates the caravan space ruin.
tgstation/tgstation pull request #39182
Opened 2018-07-17 05:33 UTC by WJohn

This re-adds the 2nd fighter ship as was originally seen in #34621 but was unintentionally removed in #37474

This also nerfs a lot of this ruin's loot. The middle cargo ship containing all the guns has lost much of its firepower; the 40mm shells were moved into the pirate ship and dropped to only one box, the frag12 shells are gone, the shotgun shells crate has been dropped to a single rubber shells crate, and the 10mm boxes to two magazines. The APS pistol has been moved into the cargo ship, while one of the energy pistols moved outside. The ship also now contains a bandolier and a shoulder holster.

The pirate ship has lost its combat shotgun and one of its laser guns, as stated before it now contains the 40mm shells box.

The dropship now has a pistol, among a bunch of clothing, but no spare 10mm magazines in its lockers.

Overall should make the ruin much less easy to cheese, and change up the meta a bit now that you're not drowning in lethal buckshot rounds, and there's an extra ship hanging around waiting to shoot you.

:cl: WJohn
fix: Caravan ruin has regained its 2nd fighter ship that went unintentionally missing a while back.
balance: Caravan ruin overall contains much less firepower, and should be harder to cheese due to placement changes and less ammunition to work with.
/:cl:

2018-07-17 06:22 UTC, subject217 commented
Remove 👏 the 👏 syndie 👏 headsets 👏 

To clarify, they spawn in the lockers of the Syndicate Dropship. Two headsets, both with Syndicate encryption keys. I wasn't able to find any other headset that spawned with a Syndie key in the ruin, including on all the mobs.

2018-07-17 07:41 UTC, WJohn commented
Oh! So they are.

2018-07-18 10:12 UTC, ninjanomnom commented
As I said in irc if you want to include the second fighter it needs to be different from the first or I need to get around to moving some code from pods to regular shuttles to allow duplicate templates. I can't tell if there are any differences in this fighter compared to the other.

2018-07-18 10:31 UTC, WJohn commented
It is different. Different area, mobile port, consoles, everything. It just looks identical to the first because it's the same "ship model". You'd expect these to be mass produced.

2018-07-18 15:40 UTC, ninjanomnom requested changes

2018-07-18 15:40 UTC, ninjanomnom commented on code/datums/shuttles.dm
> +	suffix = "syndicate_fighter_1"
you left this change in

2018-07-18 22:46 UTC, ninjanomnom approved these changes

2018-07-18 22:46 UTC, merged