Fixes few things not restoring air flow on destroy
tgstation/tgstation pull request #39210
Opened 2018-07-18 10:25 UTC by AnturK

Statues (including blown up plasma ones), alien resin and forcefields.

2018-07-20 02:37 UTC, ShizCalev submitted a review, later dismissed

2018-07-20 06:54 UTC, AnturK commented
Probably, i'll take a look at making this generic.

2018-07-21 09:09 UTC, AnturK commented
Should be good now, there's some unrelated runtime  with atmos_spawn_air that i'll address in another PR

2018-07-21 09:34 UTC, ninjanomnom requested changes

2018-07-21 09:34 UTC, ninjanomnom commented on code/game/atoms_movable.dm
> +		if((CanAtmosPass == ATMOS_PASS_DENSITY && density || CanAtmosPass == ATMOS_PASS_NO) && isturf(loc))
Mind grouping this so it's a bit more clear

2018-07-21 10:25 UTC, ninjanomnom approved these changes

2018-07-21 10:28 UTC, merged