Removes icon-on / icon-off from Smartfridge Types
tgstation/tgstation pull request #39251
Opened 2018-07-20 23:44 UTC by ExcessiveUseOfCobblestone

Please review the replacetext, only reason I have that is for admin shitlery but I can remove it if we want to BTFO admins from changing icons of fridges.

2018-07-20 23:46 UTC, ExcessiveUseOfCobblestone commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +		startstate = replacetext(icon_state, "-off", "") //admins ruin everything!
^^

2018-07-22 06:20 UTC, ninjanomnom commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +		startstate = replacetext(icon_state, "-off", "") //admins ruin everything!
Don't bother with this

2018-07-23 10:33 UTC, ninjanomnom requested changes

2018-07-23 10:33 UTC, ninjanomnom commented on code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> +		startstate = replacetext(icon_state, "-off", "") //admins ruin everything!
Just handle it normally, dont't bother with badmin checks

2018-07-23 14:31 UTC, ExcessiveUseOfCobblestone commented
c-c-c-can you fix the labels

2018-07-24 00:24 UTC, ninjanomnom approved these changes

2018-07-24 00:25 UTC, merged