Redesigns Deltastation's white ship into a luxury NT frigate.
tgstation/tgstation pull request #39278
Opened 2018-07-22 07:25 UTC by WJohn

![](https://i.imgur.com/JqDdIGV.png)

Delta's white ship has always come off as too large, empty, and boxy to me, personally, so I set out to redesign it into something with an actual shape and more details!

Also, it's infested with starving giant spiders. They have half as much health and damage as their regular versions so they're not a complete nightmare to take out, but they're still dangerous to an unarmed explorer.

:cl: WJohnston
add: Redesigned deltastation's abandoned white ship into a luxury NT frigate. Oh, and there are giant spiders too.
/:cl:

2018-07-22 07:32 UTC, Mark9013100 commented
Ten times more interesting than the current whiteship, nice.

2018-07-22 08:09 UTC, WJohn commented
Yes, it has outfits in the locker above the bridge.

2018-07-22 09:47 UTC, 81Denton commented
That design is really nice, I like that it comes with power and atmos.
Circuit board/defib/sunglasses/somatoray removal should probably be mentioned in the CL.

2018-07-22 11:30 UTC, Tlaltecuhtli commented
spiders arent space proof also it needs more wood/carpet

2018-07-22 13:40 UTC, Bombpants commented
A small botany area would be nice

2018-07-22 15:07 UTC, ShizCalev submitted a review, later dismissed

2018-07-22 15:48 UTC, coiax commented
Don't passive spiders lay webs when active anyway? Do they need to be mapped in?

2018-07-22 20:15 UTC, subject217 commented
Any chance you leave a mini egun mapped in there, somewhere? It was nice to see it used. Could go in the bridge.

2018-07-22 20:37 UTC, MrDoomBringer commented
yay you added it! such a better design <3

2018-07-22 21:42 UTC, WJohn commented
@coiax to my knowledge only nurses do, of which there's only one, and they only do it when they're active and wandering around when a living player is on the level.

2018-07-23 01:02 UTC, Bawhoppen commented
This change is only good.

2018-07-23 10:27 UTC, ninjanomnom requested changes

2018-07-23 15:42 UTC, WJohn commented
oh! my bad, i completely forgot to do that.

2018-07-24 00:18 UTC, ninjanomnom commented
No look at the comments in that file. Your area definitions are in the single area shuttle section and this isn't a single area shuttle.

2018-07-24 01:12 UTC, ninjanomnom requested changes

2018-07-24 01:12 UTC, ninjanomnom commented on code/game/area/areas/shuttles.dm
> +	blob_allowed = FALSE
blob_allowed is set to false already in `/area/shuttle/abandoned`

2018-07-24 02:56 UTC, ninjanomnom approved these changes

2018-07-24 02:56 UTC, merged