Emitter gun mounts
tgstation/tgstation pull request #39367
Opened 2018-07-25 20:40 UTC by Time-Green

Simple PR, allows you to mount energy guns into emitters. You can now insert anything from a taser to an x-ray gun, and have the emitter shoot that round.

:cl: Time-Green
add: You can now mount energy guns into emitters
/:cl:

Turrets already do exactly this, and why not let people do it with emitters

2018-07-25 21:02 UTC, Qustinnus commented
would work better as its own object imo

2018-07-25 21:17 UTC, Kagus commented
Worth noting that energy/gun also includes fun things like the particle acceleration beam rifle, the portal gun, and the gravity gun.

I'm not sure how any of those things work when fired by a non-human.

2018-07-25 21:48 UTC, 81Denton commented
Can you still add assemblies (timer, remote signaler etc) to the emitter wire when something is mounted?

2018-07-25 21:49 UTC, Time-Green commented
All this does is change the projectile type and sound, so yes

2018-07-25 22:00 UTC, Grazyn commented
RIP blob

2018-07-25 22:16 UTC, GravitronBlue commented
Unless there's already a specific check for the portal gun, this PR sounds like it has potential to get a set(s) of portals connecting the station to the Centcom z-level. I'd ask that you test whether this is feasible.

2018-07-26 04:36 UTC, Tlaltecuhtli commented
its the micro laser you use to make the emitter

2018-07-26 08:22 UTC, Time-Green commented
@GravitronBlue teleporting has been disabled on centcom for ages now

2018-07-26 08:32 UTC, Time-Green commented
Right, portal guns dont work, wich I kinda expected, but it also caused a fucking runtime because qdelling is async. 
Anyway that's fixed now.

2018-07-26 17:52 UTC, AnturK commented
A lot of projectiles require special setup. Use the turret properties instead. These are required to work out of the box.

2018-07-26 19:30 UTC, Time-Green commented
https://github.com/tgstation/tgstation/blob/d80ae38e1e96f7f95d8fc94868744c5bd06718f1/code/game/machinery/porta_turret/portable_turret.dm#L550
Uses the same stuff. Wormhole projector was runtiming like crazy on the turret, wich is what I fixed.
I tested some other exotic lasers, and apart from particle rifle not doing damage, it all works fine now.

2018-07-27 06:38 UTC, AnturK commented
That's done after it already received proper projectile through get_turret_properties. As opposed to directly grabbing the projectile type.

2018-07-28 11:04 UTC, Time-Green commented
Right, it now uses get_turret_properties. There's a new wire that switches the projectile type it fires, if there's more then one

2018-07-28 12:37 UTC, AnturK requested changes
Looks good now, just a nitpick.

2018-07-28 12:37 UTC, AnturK commented on code/modules/projectiles/projectile/special/wormhole.dm
> +		return qdel(src)
qdel does not have any meaningful return value, so this should be on next line to not confuse people reading this later.

2018-07-28 12:46 UTC, AnturK submitted a review, later dismissed

2018-07-28 13:29 UTC, Time-Green commented
I found a bug while reading code, that’d break shit when you would click it with a nodrop gun.

2018-08-01 07:12 UTC, merged