Adds in a new type of securitron
tgstation/tgstation pull request #39382
Opened 2018-07-26 16:49 UTC by Kmc2000

:cl: Kmc2000
add: You can now attach 4 energy swords to a securiton assembly instead of a baton to create a 4 esword wielding nightmare-bot
/:cl:

Meet General Beepsky!
He's Officer Beepsky's more robust cousin, instead of stunning and arresting people, he'll only stop when they're dead!

https://i.gyazo.com/6e5be23a4a9356551bc338ec22d88653.mp4

![](https://i.gyazo.com/84a4f1a742c717c6358266ba7bde0490.png)

Try emagging him for even more fun!

He's pretty robust because of the exhorbitant materials cost for making him, and will likely only be used on meme filled nukeop rounds or on traitorbros.

To create one, follow the securitron assembly instructions all the way up to attaching his baton, instead attach 4 eswords and security's murderous new mascot will be complete!

2018-07-26 17:14 UTC, ShizCalev requested changes

2018-07-26 17:14 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		new /obj/item/melee/transforming/energy/sword/saber(src.loc)
Tsec, not src.loc

2018-07-26 17:15 UTC, ShizCalev requested changes

2018-07-26 17:15 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +						new /obj/item/melee/transforming/energy/sword/saber(src.loc)
Tsec

2018-07-26 17:16 UTC, Kagus commented
This is a terrible idea.

I like it.

2018-07-26 17:20 UTC, ShizCalev requested changes

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		playsound(loc, 'sound/weapons/blade1.ogg', 50, 1, -1)
playsound(src, 'sound/weapons/blade1.ogg', 50, TRUE, -1)

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		return 0
FALSE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		playsound(loc,'sound/effects/beepskyspinsabre.ogg',100,1,-1)
src, TRUE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +				playsound(loc, 'sound/weapons/blade1.ogg', 50, 1, -1)
src, TRUE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +				return 0
FALSE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +			playsound(loc, 'sound/weapons/blade1.ogg', 50, 1, -1)
src, TRUE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	playsound(loc, 'sound/weapons/blade1.ogg', 50, 1, -1)
src, TRUE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +			playsound(loc,'sound/effects/beepskyspinsabre.ogg',100,1,-1)
src, TRUE

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +			playsound(loc, pick('sound/voice/bcriminal.ogg', 'sound/voice/bjustice.ogg', 'sound/voice/bfreeze.ogg'), 50, 0)
src, false

2018-07-26 17:20 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +			playsound(loc,'sound/weapons/saberon.ogg',50,1,-1)
src, TRUE

2018-07-26 17:30 UTC, ShizCalev requested changes

2018-07-26 17:30 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		playsound(loc, 'sound/weapons/blade1.ogg', 50, TRUE)
src

2018-07-26 17:30 UTC, Time-Green commented
Hello there!

2018-07-26 17:53 UTC, Kmc2000 commented
gonna add a toysword version right quick

2018-07-26 18:03 UTC, ShizCalev requested changes

2018-07-26 18:03 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	var/obj/item/melee/transforming/energy/sword/weapon = new
move this new into Initialize()

2018-07-26 18:03 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	var/block_chance = 50
Move this below base speed please. New vars should be kept at the bottom just for readability sake.

2018-07-26 18:03 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	if(has_gravity() && ismob(AM) && target)
this is already done by ..()

2018-07-26 18:03 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	..()
wouldn't it retaliate twice?

2018-07-26 18:10 UTC, praisenarsie commented
why not energy daggers?

2018-07-26 21:32 UTC, Tlaltecuhtli commented
the sprite is ugly

2018-07-26 23:22 UTC, PKPenguin321 commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	if(prob(block_chance))
honestly remove this and just make it guaranteed

2018-07-27 14:55 UTC, ExcessiveUseOfCobblestone commented
> not naming him general grieffous

2018-07-27 17:01 UTC, Kmc2000 commented
Cheers Shiz

2018-07-27 19:08 UTC, ShizCalev submitted a review, later dismissed

2018-07-28 08:12 UTC, Bawhoppen commented
The eswords are so tiny on the sprite.

2018-07-28 23:48 UTC, Cyberboss requested changes

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +		return
remove trailing return

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	qdel(weapon)
QDEL_NULL

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	new /obj/effect/decal/cleanable/oil(loc)
use Tsec instead of loc

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
> +	qdel(weapon)
Or just remove the line entirely since you qdel(src) below and /Destroy() already does it

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +					for(var/IS = 0 to toyswordamt)
var/IS in 1 to toyswordamt

2018-07-28 23:48 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/bot/construction.dm
> +				for(var/IS = 0 to swordamt)
same

2018-07-29 09:30 UTC, Memager commented
e-daggers to reduce cost

2018-08-03 16:07 UTC, merged

2018-08-03 16:09 UTC, JohnGinnane commented
this is great

2018-08-03 20:50 UTC, ishitbyabullet commented
I've said it recently and I'll say it again - this is just General fucking Grievious as a kid.