Removes canvases on runtime
tgstation/tgstation pull request #39401
Opened 2018-07-27 10:14 UTC by Jared-Fogle

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl:
del: Temporarily removes canvases until someone figures out how to fix them.
/:cl:

[why]: # #38942 I didn't make it a config option because if you're going to be fixing the canvases you'd be removing the code for the config option anyway.

2018-07-27 10:30 UTC, Jared-Fogle commented on code/game/objects/structures/artstuff.dm
> +/obj/item/canvas/New()
Only because I don't think it makes much of a difference. I'll comment it out, though.

2018-07-27 13:43 UTC, Cyberboss requested changes
Remove the comment block and add ..() before returning the initialize hint

2018-07-27 13:44 UTC, Cyberboss commented on code/game/objects/structures/artstuff.dm
> +/obj/item/canvas/New()
we don't comment shit out kevinz, you know this by now

2018-07-27 13:50 UTC, Jared-Fogle commented
@Cyberboss Which comment block? The one with the rest of the canvas code?

2018-07-27 13:57 UTC, Cyberboss commented
Yes

On Fri, Jul 27, 2018, 9:51 AM Jared-Fogle <notifications@github.com> wrote:

> @Cyberboss <https://github.com/Cyberboss> Which comment block? The one
> with the rest of the canvas code?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/39401#issuecomment-408424607>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHywegp5MkDnQNek6nNj0YaUoGMCMCueks5uKxrFgaJpZM4VjQcN>
> .
>

2018-07-27 13:57 UTC, Jared-Fogle commented
Done

2018-07-28 23:49 UTC, Cyberboss approved these changes

2018-07-28 23:49 UTC, merged

2018-12-28 10:14 UTC, SgtxRootbeer commented
so, has this been worked on at all yet?