Giving circuits possibility to load item while in assembly
tgstation/tgstation pull request #39454
Opened 2018-07-29 19:56 UTC by Shdorsh

[Changelogs]: # Makes it possible to create circuits that can get an item loaded into them while they are in an assembly and the assembly is open.

:cl: Shdorsh
tweak:
code: Changed the attack_self proc so it doesn't require 2 lists and a list.Find() proc. It only uses 1 list now and that should do the trick.
/:cl:

[why]: # Initiating 2 lists is unneeded, so I optimized it all a little bit. Also, makes it easier to craft circuits.

2018-07-29 21:12 UTC, Cyprex commented
The part between CL is player-facing, the part above is only for github users, it seems you need to swap them.

2018-07-31 07:50 UTC, Garen7 commented
great change, there are a lot of circuits that need something like this

2018-07-31 23:44 UTC, Shdorsh commented
thanks man

2018-08-12 04:13 UTC, BlueNothing commented
We've kind of needed this for a while.

2018-08-12 04:41 UTC, PKPenguin321 commented
Very nice PR, makes loading circuits that require specific items (gun firers, grenade primers) less hacky. Doesn't actually buff or nerf circuits, just straight up QoL.

2018-08-13 19:47 UTC, Shdorsh commented
What I experienced is that whenever your assembly is in your backpack, adding a battery to it will add the battery in the backpack and the assembly, so you can take the battery from the backpack and put it in other assemblies to link it all to the same battery. This might be exploited to create energizing assemblies made of pure photovoltaic cells or tesla relays that keep energizing the battery while the real assembly can just walk off and do its job far away from any apcs it could drain and lightsources.

2018-08-13 19:50 UTC, BlueNothing commented
Or just to run a bunch of assemblies off of one battery, saving time
charging more.

On Mon, Aug 13, 2018, 3:47 PM Shdorsh <notifications@github.com> wrote:

> What I experienced is that whenever your assembly is in your backpack,
> adding a battery to it will add the battery in the backpack and the
> assembly, so you can take the battery from the backpack and put it in other
> assemblies to link it all to the same battery. This might be exploited to
> create energizing assemblies made of pure photovoltaic cells or tesla
> relays that keep energizing the battery while the real assembly can just
> walk off and do its job far away from any apcs it could drain and
> lightsources.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/39454#issuecomment-412640709>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATzMBG3mzBX4-EFicQCLaefnOEuZGzC1ks5uQdfTgaJpZM4Vli98>
> .
>

2018-08-13 19:51 UTC, BlueNothing commented
Or, just put one of the networked batteries on a charger.

On Mon, Aug 13, 2018, 3:50 PM Wyatt walavigne@earthlink.net <
wylthhalm@gmail.com> wrote:

> Or just to run a bunch of assemblies off of one battery, saving time
> charging more.
>
> On Mon, Aug 13, 2018, 3:47 PM Shdorsh <notifications@github.com> wrote:
>
>> What I experienced is that whenever your assembly is in your backpack,
>> adding a battery to it will add the battery in the backpack and the
>> assembly, so you can take the battery from the backpack and put it in other
>> assemblies to link it all to the same battery. This might be exploited to
>> create energizing assemblies made of pure photovoltaic cells or tesla
>> relays that keep energizing the battery while the real assembly can just
>> walk off and do its job far away from any apcs it could drain and
>> lightsources.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/tgstation/tgstation/pull/39454#issuecomment-412640709>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/ATzMBG3mzBX4-EFicQCLaefnOEuZGzC1ks5uQdfTgaJpZM4Vli98>
>> .
>>
>

2018-08-22 14:30 UTC, Shdorsh commented
Build success, yet errored, no idea what's going on. My own modded version on my desktop works without any porblems though...

2018-08-30 08:25 UTC, optimumtact commented
another pr lost to maintainer disinterest

2018-08-30 23:40 UTC, Shdorsh commented
Whelp nevermind, I'll port it to hippie, we got the same taste in circuits shenanigans.

2018-08-31 02:15 UTC, PKPenguin321 commented
oranges reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeopen this NOW

2018-08-31 02:37 UTC, optimumtact commented
it's not magically going to make someone care enough to merge it so no, go find a maintainer who wants to merge it and ask them.

2018-08-31 03:10 UTC, PKPenguin321 commented
😡

2018-09-01 13:20 UTC, vuonojenmustaturska requested changes

2018-09-02 00:46 UTC, Shdorsh commented on code/modules/integrated_electronics/core/assemblies.dm
> +				choice = input_selection.[selection]
wow, I must have been drunk while I did this. amazing what you can find out with a bit of strawberry juice, amaretto and concentrated lemon juice.

2018-09-03 21:31 UTC, merged