You can now show off your Attorney's Badge to people
tgstation/tgstation pull request #39533
Opened 2018-08-03 07:30 UTC by epochayur

Can you take a look at this?

:cl: Epoc
add: You can now show off your Attorney's Badge
/:cl:

what's the point of having this in the game in the first place if you can't show it off to people?

2018-08-03 07:30 UTC, fen0s commented
SUPPORT SUPPORT SUPPORT SUPPORT SUPPORT.
We need this. Every lawyer should show their badge.

2018-08-03 07:31 UTC, QualityVan commented
this is a useless thing to do
:+1:

2018-08-03 21:00 UTC, Anonmare commented
Present-->Attorney's Badge

Detective: "Ha ha. Good one, pal. You're always good for a laugh with your little badge."

2018-08-03 23:13 UTC, Iamgoofball commented
https://github.com/epochayur/tgstation/pull/1 you should merge this @epochayur

2018-08-04 22:02 UTC, SpaceManiac requested changes

2018-08-04 22:02 UTC, SpaceManiac commented on code/modules/clothing/under/accessories.dm
> +	user.visible_message("[user] shows their attorney's badge.", "<span class='notice'>You show your attorney's badge.</span>")
`their` -> `[user.p_their()]`

2018-08-04 23:53 UTC, SpaceManiac approved these changes

2018-08-05 00:03 UTC, merged