Ports Binoculars from /vg/: 2 Electric boogaloo
tgstation/tgstation pull request #39544
Opened 2018-08-03 21:54 UTC by CitrusGender

:cl:  CitrusGender
add: Adds binoculars
:cl: 

[why]: # Thought I'd take a shot at it since I thought they were pretty cool and I was gonna add them to the charity event. I guess they would also be useful ingame too if anyone wanted to use them for an event.

I probably did something wrong since /vg/ is baycode and does things a bit differently but it works ingame just fine for me. /vg/ doesn't do components the same way as us so I did a work around for the "mob_moved" part with a component.

2018-08-03 22:11 UTC, Militaires commented
![snake](https://user-images.githubusercontent.com/16103879/43668003-ecb5933c-977a-11e8-93b1-6c63b8820c58.PNG)

2018-08-03 22:13 UTC, Militaires commented
![image](https://user-images.githubusercontent.com/16103879/43668041-25d75a7e-977b-11e8-9bca-8e973ea0a1bd.png)

2018-08-04 01:42 UTC, CosmicScientist commented
Does this let you see further in all or one direction?

2018-08-04 03:09 UTC, kingoftheautism commented
I think it will work like sniper rifle zoom, one direction only

2018-08-04 22:06 UTC, WJohn commented
We really gotta make zoom function consistent in all usage. From sniper, to mech, to beam rifle and now to these. It's a really inconsistent mess.

These sprites look fantastic though.

2018-08-04 23:29 UTC, ShizCalev requested changes

2018-08-04 23:29 UTC, ShizCalev commented on code/game/objects/items/twohanded.dm
> +		user.visible_message("\The [user] holds \the [src] up to \his eyes.","You hold \the [src] up to your eyes.")
`"The Citrus Gender holds the"`

wat

lose all the `\the`'s

also pronoun helpers. `user.p_their()`

2018-08-04 23:29 UTC, ShizCalev commented on code/game/objects/items/twohanded.dm
> +	user.visible_message("\The [user] lowers \the [src].","You lower \the [src].")
same

2018-08-07 09:34 UTC, CitrusGender commented
@ShizCalev @WJohn  Changed the wording. Also, I made it more like the sniper rifle. Don't ask me how I got those values, but the zoom is completely the same as the sniper rifle now.

2018-08-08 16:53 UTC, ninjanomnom requested changes

2018-08-08 16:53 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +		if(user && user.client)
You can avoid this entire proc being indented like this by doing
```
if(!wielded)
  return
...
if(!user?.client)
  return
...
```

2018-08-08 16:53 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +	QDEL_NULL(mobhook)
Rather than deleting and recreating it every time just detach and reattach it

2018-08-08 16:53 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +/obj/item/twohanded/binoculars/wield(mob/user)
Minor nitpick extreme: Could you put a blank line between these

2018-08-09 01:07 UTC, ninjanomnom requested changes

2018-08-09 01:07 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +	if(!user?.client)
??

This should be down below where the check is

2018-08-09 01:07 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +	mobhook.RemoveComponent()
Under the parent call

2018-08-09 01:07 UTC, ninjanomnom commented on code/game/objects/items/twohanded.dm
> +	mobhook = user.AddComponent(/datum/component/redirect, list(COMSIG_MOVABLE_MOVED = CALLBACK(src, .proc/unwield, user)))
```
if(QDELETED(mobhook))
  mobhook = user.AddComponent(etc...
else
  user.TakeComponent(mobhook)
```

2018-08-09 02:11 UTC, ninjanomnom approved these changes

2018-08-09 02:12 UTC, merged