Clean ashligger food
tgstation/tgstation pull request #39574
Opened 2018-08-05 20:12 UTC by Tlaltecuhtli

:cl: 
add: 3 new dishes for liggers
add: gutlunch now has his own milk
code: removed a rogue line 
/:cl:

[why]: why not

2018-08-05 20:15 UTC, Tlaltecuhtli commented
fuck you bot dont remove my labels

2018-08-06 00:00 UTC, octareenroon91 commented
Addition of "entpolyneutr" appears to be an undocumented change.

2018-08-06 00:32 UTC, octareenroon91 commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/datum/chemical_reaction/entpolyneutr
changes a lavaland mushroom poison into rotatium
antitoxin isn't that available though.

2018-08-06 02:17 UTC, cyclowns commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/datum/chemical_reaction/entpolyneutr
ok but why is it here and undocumented is what im asking

2018-08-06 04:46 UTC, Tlaltecuhtli commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/datum/chemical_reaction/entpolyneutr
because the soup uses the poisonus mushrooms so you dont die when eating it

2018-08-06 06:56 UTC, Ratvar commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/datum/chemical_reaction/entpolyneutr
but there's poisonous food tho

2018-08-06 07:34 UTC, Tlaltecuhtli commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +/datum/chemical_reaction/entpolyneutr
no

2018-08-06 09:07 UTC, Kagus commented
What the actual fuck even is this PR.

And, I mean, it's not like ashy bois are already overweight the entirety of the time because their only renewable healing chems come with a massive nutriment load... We should give them more random high-nutriment food, and put it in the tribal menu because, well, fuck.

---
At least gutlunch milk isn't just this hilarious combo of cream and saline-glucose, serving... No purpose. Which was honestly fine, since sacrificing corpses doesn't spawn gibs for them to eat anymore. Speaking of, will this run into the same on_mob_add/delete issues that Brave Bull does?

2018-08-06 10:09 UTC, Tlaltecuhtli commented
- overweight change (#38383) is not my problem make a revert for that if you think you eat too much
- gibbing not spawing gibs on the floor is not my problem because it is a bug
- there are no issues reported for brave bull doing stuff so please report them instead of shitposting

2018-08-06 12:25 UTC, Kagus commented
As mentioned in the comments of #39234, there's an interaction with microdoses of status-providing chems, and because of how that was handled and how Brave Bull's buff was handled (I.E., directly fiddling with stats, like here, rather than having a defined trait that it checks for and then adds/removes), multiple small doses could either do nothing or end up killing you. But that's *probably* not going to be a problem due to tribals not having easy access to smoking implements with which to repeatedly microdose themselves, and nobody uses the IV drip anyways.

Sacrifices not spawning gibs indeed isn't your responsibility to fix, but this PR has gameplay effects that are indirectly affected by it, so it needs to be taken into consideration when asking the question "does this contribute meaningfully (or at all) to the game as a whole?"

Likewise, the changes to overeating and nutrition are neither your responsibility nor mine to change, but it *is* your responsibility to take it into consideration seeing as that's the current state of the game, and you're making a PR for the current state of the game, and that PR is directly affected by those values (*especially* considering one of the recipes calls for the mushroom type that contains mint toxin. You know, the one that instantly gibs people who are overweight). Not that it's your problem if people actually eat the food added by this PR.

Actually, are food crafting recipes child-exclusive? If requirements don't automatically exclude their children, then it seems like the recipe will happily accept pretty much any lavaland flora, since it's calling for `grown/ash_flora` and the other mushroom types are `grown/ash_flora/whatever`. Which is kind of awful in and of itself, but again, not your problem.

---
Shitposting aside, I'm just impressed by how many commits this has.

2018-08-06 18:55 UTC, 81Denton commented
I didn't know Fwoosh had a brother

2018-08-08 21:42 UTC, Militaires commented
As mentioned in the comments of #39234, there's an interaction with microdoses of status-providing chems, and because of how that was handled and how Brave Bull's buff was handled (I.E., directly fiddling with stats, like here, rather than having a defined trait that it checks for and then adds/removes), multiple small doses could either do nothing or end up killing you. But that's probably not going to be a problem due to tribals not having easy access to smoking implements with which to repeatedly microdose themselves, and nobody uses the IV drip anyways.

Sacrifices not spawning gibs indeed isn't your responsibility to fix, but this PR has gameplay effects that are indirectly affected by it, so it needs to be taken into consideration when asking the question "does this contribute meaningfully (or at all) to the game as a whole?"

Likewise, the changes to overeating and nutrition are neither your responsibility nor mine to change, but it is your responsibility to take it into consideration seeing as that's the current state of the game, and you're making a PR for the current state of the game, and that PR is directly affected by those values (especially considering one of the recipes calls for the mushroom type that contains mint toxin. You know, the one that instantly gibs people who are overweight). Not that it's your problem if people actually eat the food added by this PR.

Actually, are food crafting recipes child-exclusive? If requirements don't automatically exclude their children, then it seems like the recipe will happily accept pretty much any lavaland flora, since it's calling for grown/ash_flora and the other mushroom types are grown/ash_flora/whatever. Which is kind of awful in and of itself, but again, not your problem.

2018-08-10 13:50 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	. = 1
these should probably be changed to `return TRUE`

2018-08-13 07:39 UTC, Tlaltecuhtli commented
like this? @ShizCalev

2018-08-24 00:06 UTC, ShizCalev requested changes

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/crafting/recipes.dm
> +	name = "Paleo salad"
Capitalize

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/crafting/recipes.dm
> +	name = "Toad lick soup"
Capitalize

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/crafting/recipes.dm
> +	name = "Bone broth"
Capitalize

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/food_and_drinks/food/snacks_salad.dm
> +	name = "Paleolithic salad"
\proper

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/food_and_drinks/food/snacks_soup.dm
> +	name = "Bone broth"
lowercase

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/food_and_drinks/food/snacks_soup.dm
> +	name = "Toad lick soup"
lowercase

2018-08-24 00:06 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/drink_reagents.dm
> +	name = "Gutlunch milk"
Capitalize

2018-08-26 00:39 UTC, optimumtact commented on code/modules/crafting/recipes.dm
> +/datum/crafting_recipe/gold_horn
what is this?

2018-08-26 05:25 UTC, octareenroon91 commented on code/modules/food_and_drinks/food/snacks_salad.dm
> +	name = "/proper paleolithic salad"
DM ref:
`\proper    // used in an object name to force proper-noun behavior`

2018-08-30 08:08 UTC, optimumtact commented
I just can't bring myself to care about this, so I imagine nobody else will either

2018-08-30 08:08 UTC, closed without merging