Circuit logging and etc
tgstation/tgstation pull request #39582
Opened 2018-08-06 08:06 UTC by Garen7

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Garen
fix: fixed using items on a circuit removing all its access(now access gained from each new item stacks)
admin: adds logging for gun circuits, grabber circuits, and dragging claw circuits
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Currently circuits change their id access to be whatever you used last on it so if you say use a toolbox on a circuit it would delete whatever access was stored on it, now it retains whatever access it had previously when you use an item on it. I also added some logging because #38588. I also broke grabber functionality into different procs and merged the two examine procs into one.

2018-08-12 04:13 UTC, BlueNothing commented
This sounds cool, but I wonder how the new grabber mode works.

2018-08-12 06:08 UTC, Garen7 commented
oh you set the target to an item in the grabber and it drops it @BlueNothing

2018-08-12 06:51 UTC, BlueNothing commented
Set by index?

On Sun, Aug 12, 2018, 2:08 AM Garen Crownguard <notifications@github.com>
wrote:

> oh you set the target to an item in the grabber and it drops it
> @BlueNothing <https://github.com/BlueNothing>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/39582#issuecomment-412321080>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATzMBFuzJz-bBF_D731tp9_SEami3SWfks5uP8ZbgaJpZM4Vv7tU>
> .
>

2018-08-12 07:09 UTC, Garen7 commented
nah, a ref

2018-08-12 07:41 UTC, BlueNothing commented
Ah... could be a significant efficiency improvement for my storage implant.

2018-08-13 02:36 UTC, Garen7 commented
do you think its an issue? i can raise the complexity

2018-08-13 03:13 UTC, BlueNothing commented
Hm, maybe. If you want to, anyway.

On Sun, Aug 12, 2018, 10:36 PM Garen Crownguard <notifications@github.com>
wrote:

> do you think its an issue? i can raise the complexity
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/39582#issuecomment-412394268>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATzMBFAdAmhNaj527lAfj9eHAQ-49FOJks5uQOZGgaJpZM4Vv7tU>
> .
>

2018-08-18 05:37 UTC, Cyberboss requested changes

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/manipulation.dm
>  		if(mode == 1)
change this to a switch statement please

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +			get_object().investigate_log("picked up ([AM]) with [src].", INVESTIGATE_CIRCUIT)
this is equivalent to get_object():investigate_log which isn't allowed

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +	get_object().investigate_log("dropped ([AM]) from [src].", INVESTIGATE_CIRCUIT)
same

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +		for(U in contents)
in src

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/manipulation.dm
> +		var/turf/T = get_turf(get_object())
should be drop_location instead of get_turf

2018-08-18 05:37 UTC, Cyberboss commented on code/modules/integrated_electronics/subtypes/output.dm
> +		get_object().investigate_log("played a sound ([selected_sound]) as [type].", INVESTIGATE_CIRCUIT)
again

2018-08-19 13:50 UTC, Cyberboss approved these changes

2018-08-19 13:51 UTC, merged