Removes now obsolete floorgrime path and icon
tgstation/tgstation pull request #39816
Opened 2018-08-20 14:09 UTC by WJohn

As of #39699 we now have effectively identical looking floorgrime icons coming in the form of decals, which means the original dirty looking plasteel floor icon "floorgrime" is obsolete since its effect can be applied to anything. As such, I have removed it from every map and the code.

HUGE thanks to antur for their map tool, babying me through it, and making hotfixes for me to work with our new map merger!

This touches quite a lot of maps, so I'm likely to get conflicts if this doesn't get merged after about a day.

2018-08-20 16:11 UTC, nicbn commented
You replaced it with `obj/effect/decal/cleanable/dirt` instead of `/obj/effect/decal/cleanable/dirt` in some maps (not sure if this is an issue anyway).

2018-08-20 16:30 UTC, WJohn commented
fuck

2018-08-20 16:51 UTC, WJohn commented
That should fix it.

2018-08-20 21:59 UTC, nicbn commented
Conflicts

2018-08-21 12:01 UTC, ShizCalev requested changes

2018-08-21 12:01 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +<<<<<<< HEAD/turf/open/floor/plasteel,
no.

2018-08-21 12:01 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +>>>>>>> 7a52e44b0d19f4ee7e87fa92b699ed9a3e93e062/area/crew_quarters/locker)
.

2018-08-21 12:12 UTC, WJohn commented on _maps/map_files/MetaStation/MetaStation.dmm
> +>>>>>>> 7a52e44b0d19f4ee7e87fa92b699ed9a3e93e062/area/crew_quarters/locker)
heck

2018-08-22 11:57 UTC, merged