[s] Fixes exploit with box suicide
tgstation/tgstation pull request #39835
Opened 2018-08-21 12:58 UTC by Mickyan

:cl: Mickyan
fix: Suiciding with a box no longer removes your head for easy debraining
/:cl:

Fixes #39796

2018-08-21 13:06 UTC, vuonojenmustaturska commented
This is not what [s] is for

2018-08-21 13:07 UTC, 81Denton commented
That's not an exploit and other suicides decapitate as well

2018-08-21 13:13 UTC, Mickyan commented
@81Denton using something to gain an unintended advantage is the very definition of an exploit

2018-08-21 13:17 UTC, Jared-Fogle commented
What good gameplay does the time spent to cut the head off manually add? If anything this seems more like quality of life.

2018-08-21 13:18 UTC, FloranOtten commented
Why? What advantage does it give over another player? This is QOL and it really ought not to be removed.

2018-08-21 13:34 UTC, FloranOtten commented
"It's not the intended use" riiiiiight, the intended use for the supermatter crystal is not blob removal but I still do it don't I?

2018-08-21 14:10 UTC, Iatots commented
Brains from suicides should have been made uncloneable and unborgable as soon as dismemberment was put in, I'd rather you correct that.

2018-08-21 14:42 UTC, ExcessiveUseOfCobblestone requested changes
suicide needs to transfer the var to the brain too as opposed to removing any form of decapitating suicide

2018-08-21 14:53 UTC, closed without merging

2018-08-21 14:55 UTC, Mickyan commented
@ExcessiveUseOfCobblestone do suicided brains even become inactive in MMIs or does it just prevent cloning

2018-08-21 15:07 UTC, ExcessiveUseOfCobblestone commented
I'm not sure the var transfers to brains on decap

2018-08-21 17:26 UTC, 81Denton commented
@Mickyan Cobby was right, the `suiciding` var doesn't transfer to brains on suicide. Hence, MMIs don't for it either.
It would be a good idea to add that since suiciding prevents about anything that's not revival magic.

2018-09-17 01:05 UTC, deranging commented
just did this earlier today *spin *flip