bike horns and most things that have the squeak component no longer triggers from projectiles flying past them
tgstation/tgstation pull request #40077
Opened 2018-09-03 19:56 UTC by kevinz000

why: doesn't make sense for these things to trigger from a projectile flying above them.
still happens if you directly target (and hit) them.

2018-09-03 20:43 UTC, nichlas0010 commented
boo

2018-09-03 21:33 UTC, SpaceManiac commented
just how old code are you on
```
code/datums/components/squeak.dm:56:error: ABSTRACT_1: undefined var
```

2018-09-04 19:30 UTC, ninjanomnom requested changes

2018-09-04 19:30 UTC, ninjanomnom commented on code/datums/components/squeak.dm
> +	if(istype(AM, /obj/item/projectile))
`else if`

2018-09-04 19:30 UTC, ninjanomnom commented on code/datums/components/squeak.dm
> +	return play_squeak_turf()
just modify this proc, it's only used in one place

2018-09-04 22:29 UTC, octareenroon91 commented
>Now how will i build my emitter+mirror god awful cacophony generators?
Disposals x conveyor belts?

2018-09-04 22:34 UTC, GuyonBroadway commented
Its just not as fun if it doesn't involve deadly deadly laser beams.

2018-09-04 22:37 UTC, octareenroon91 commented
>Its just not as fun if it doesn't involve deadly deadly laser beams.

We're going way off topic, but aren't spears or shards traditional for disposals horrors?

2018-09-04 22:39 UTC, GuyonBroadway commented
Mirrors and lasers are the choice of real deathtrap builders.

2018-09-05 01:50 UTC, kevinz000 commented
@ninjanomnom done

2018-09-07 10:57 UTC, merged

2018-09-07 12:11 UTC, nichlas0010 commented
boo