Makes law upload consoles require RD access
tgstation/tgstation pull request #40112
Opened 2018-09-05 08:56 UTC by daklaj

[Changelogs]: 
:cl:
tweak: Law upload consoles now require RD access. Hacked law boards can bypass it.
/:cl:

[why]: 
being able to subvert every single silicon on the station with the total effort of a few clicks on rnd console and no cost at all is dumb
investing 9 TC in hacked law board when you can achieve almost the same result with whatever variation of purge/freeform/onehuman you like also is dumb

2018-09-05 09:05 UTC, AnturK requested changes

2018-09-05 09:05 UTC, AnturK commented on code/game/machinery/computer/law.dm
> +		if(!src.allowed(usr) && !M.bypass_access_check)
Drop `src`, it's redundant and use user instead of usr here. Same below.

2018-09-05 09:27 UTC, Tlaltecuhtli commented
maybe leave core lawsets and reset to be uploaded without id

2018-09-05 09:43 UTC, GuyonBroadway commented
This violates the long standing ss13 tradition AND culture of the clown sneaking/being let into the upload and uploading funny laws like "Always address the captain as lord comdom" and "opening doors causes human harm." etc...

2018-09-05 11:13 UTC, optimumtact commented
The ID lock on the entrance to the AI upload is more than sufficient, especially when on most stations it's located on the bridge.

I will close this after the 24 hour review period.

2018-09-05 11:58 UTC, Tlaltecuhtli commented
once again oranges doesnt even read half the OP, you can print the ai upload and the lawsets from the circuit printer as engineer or scientist or roboticist or anyone who broke in tech storage and built a circuit printer in a remote maint room

2018-09-05 12:15 UTC, optimumtact commented
so what you're saying is that the real bug is that there isn't a secure protolathe on the bridge that prints some high value items?

2018-09-05 16:37 UTC, kevinz000 commented
>this has been a thing way before techwebs was ever made, science being able to print law uploads

>the only difference is engineering can do it

hahaa.
but yeah I'll get on that soonish, a command lathe would be nice.

2018-09-06 02:57 UTC, octareenroon91 commented
>suddenly unacceptable when engineering gets to do it

2018-09-06 04:02 UTC, TerraGS commented
Sounds like a great way to make the game less fun. There are enough hurdles in place that anyone uploading custom laws earned the right. If an AI player has a problem with the nature or quantity of uploads they can always speak with an admin.

2018-09-06 08:41 UTC, Barhandar commented
Prevents golems from purge-customlawing "Yeah go do whatever" the AI, 0/10

2018-09-08 05:17 UTC, kevinz000 commented
@ExcessiveUseOfCobblestone just give the golem ruin a hardcode-anchored protolathe ez

2018-09-08 22:15 UTC, ExcessiveUseOfCobblestone commented
Taking longer to second life doesn't make the role less poopy

2018-09-10 21:30 UTC, optimumtact commented
I don't agree with this change, move the circuits to a command protolathe that lives in the bridge somewhere, or in tech storage.

2018-09-10 21:30 UTC, closed without merging