Adds meat donuts
tgstation/tgstation pull request #40145
Opened 2018-09-06 18:51 UTC by Supermichael777

:cl:
add: NTs crack archeo-gastronomers have discovered a long lost recipe for a meat based donut.
/:cl:

You thought it was delicious puff pastry. BUT IT WAS I, MEATO, who entered your lips.
![](https://cdn.discordapp.com/attachments/326843254639165441/487300087761076244/image1.jpg)

2018-09-06 18:52 UTC, Kagus commented
Pfeh. Keep this kind of nonsense up, and next thing the lizards will start to actually feel _welcome_ on the station security force.

2018-09-06 18:53 UTC, Supermichael777 commented
fun fact sec officers can eat any doughnut without penalty.

2018-09-06 18:55 UTC, ExcessiveUseOfCobblestone commented
food gore shouldn't be tolerated on my pious codebase

2018-09-06 19:13 UTC, epochayur commented
🤢

2018-09-06 19:17 UTC, fen0s commented
please no

2018-09-06 19:32 UTC, 81Denton commented
![1503638785427](https://user-images.githubusercontent.com/32391752/45180668-559d4a00-b21c-11e8-9ade-676701731027.png)

2018-09-06 19:58 UTC, MrDoomBringer commented
what @81Denton said

2018-09-06 22:31 UTC, Doppeltongue commented
But why?

2018-09-06 22:57 UTC, octareenroon91 requested changes

2018-09-06 22:57 UTC, octareenroon91 commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
> +datum/crafting_recipe/food/donut
duplicate typepath

2018-09-06 23:27 UTC, WJohn commented
that's fucking disgusting

2018-09-07 06:04 UTC, Arkvold commented
... I'm simultaneously sickened and intrigued.  It would be _slightly_ less disgusting if it used actually-cooked meat.

I do appreciate that this establishes that Security will eat damn near anything so long as it's vaguely donut-esque.

Can you arrange for these to spawn in donut boxes?  Or will that happen in the existing configuration, since they're a child of food/snacks/donut?

2018-09-07 09:51 UTC, zamolxius commented
hot

2018-09-07 14:37 UTC, Potato-Masher commented
5% chance that donuts in normal boxes that spawn are replaced by a meat donut.

2018-09-08 05:15 UTC, ninjanomnom approved these changes
The food gore shadow council has my family. I'm sorry but I must merge this.

2018-09-08 05:15 UTC, merged