Fix telecomms logs to check actual language rather than mob type
tgstation/tgstation pull request #40256
Opened 2018-09-13 04:52 UTC by SpaceManiac

:cl:
fix: The telecomms log computers now use the actual language of messages, rather than mob type.
/:cl:

Stealth universal translator for "anything a humanoid says" seems unintended, probably a relic from before the language system

2018-09-14 04:10 UTC, Lxtoofonea commented
+1

2018-09-14 08:53 UTC, Barhandar commented
It takes longer to print universal translator components than to build one, and barely anyone ever touches telecomms, I say, this is a feature.

2018-09-15 00:14 UTC, Cyberboss requested changes

2018-09-15 00:14 UTC, Cyberboss commented on code/game/machinery/telecomms/computers/logbrowser.dm
> +					else if(ispath(mobtype, ))
nani?

2018-09-15 00:28 UTC, SpaceManiac commented on code/game/machinery/telecomms/computers/logbrowser.dm
> +					else if(ispath(mobtype, ))
uh whoops

2018-09-16 03:19 UTC, merged