Adds an admin button to turn everyone into plasmamen with suits and internals
tgstation/tgstation pull request #40565
Opened 2018-09-28 02:32 UTC by GuppyLaxx

Boris told me if I made this I could finally use my 3 antag tokens

2018-09-28 02:34 UTC, DaedWren commented
Skeleboners all round

2018-09-28 03:29 UTC, GuppyLaxx commented
Tried so, doesn't replace the clothing, so you have plasmamen with no suit or helmet

2018-09-28 08:32 UTC, Barhandar commented
Even after you've qdel'd said clothing already?

Also, Jordie probably means something like "new /datum/outfit/plasmaman/P;  H.equip_to_slot_or_del(new P.uniform(H), SLOT_W_UNIFORM)` except functional, i.e. using datum as the source of the type.

2018-09-28 13:51 UTC, Borisvanmemes commented
oh my fuck he really made it.

2018-09-28 14:35 UTC, Jordie0608 commented
Yeah sorry I wasn't clear, @Barhandar is correct; you can condense all this into
````
H.set_species(/datum/species/plasmaman)
qdel(H.w_uniform)
qdel(H.wear_mask)
qdel(H.head)
H.drop_all_held_items()
var/datum/outfit/plasmaman/O = new /datum/outfit/plasmaman
H.equipOutfit(O, visualsOnly)
H.internal = H.get_item_for_held_index(2)
H.update_internals_hud_icon(1)
````
Although do test it first, should work but I can't be sure of that.

2018-09-28 22:30 UTC, zxaber commented
Rather than delete all the worn gear, can it just be moved to the tile the player is standing on?

2018-09-29 05:28 UTC, Doppeltongue commented
This is horrible. Speedmerge it.

2018-10-04 07:06 UTC, ShizCalev requested changes
what Jordie said.

2018-10-04 07:06 UTC, ShizCalev commented on code/modules/admin/secrets.dm
> +				H.update_internals_hud_icon(1)
TRUE

2018-10-15 19:50 UTC, AnturK commented
:hourglass_flowing_sand:

2018-10-17 10:17 UTC, closed without merging