Makes fire alarm simpler
tgstation/tgstation pull request #40586
Opened 2018-09-29 17:04 UTC by nicbn

[Changelogs]: #
:cl: nicbn
tweak: Fire alarm is now simpler. Touch it to activate, touch it to deactivate. No security level lights.
/:cl:

Now toggling it is faster, because there is no tgui, and the security level lights are gone, as it makes the lights easier to understand.

A lot of air alarms were inverted in the maps, so the fire icon that replaces the old lights was inverted as well.

If the air alarm is emagged it will blink red every 10 seconds.

2018-09-29 17:09 UTC, GunHog commented
Against this because:
1) There is no other public indicator of station alert status for those that missed the announcements
2) The emag change makes emagging / malf hacking them less viable. The current system requires someone to check it, rather than anyone in eyeshot of it being alerted.
3) You could add a mouse shortcut (such as ctrl-click) for toggling the alarm faster, if your goal is simply making the alarm usable without loading the UI (which might take 10+ seconds or never load)

2018-09-29 17:13 UTC, nicbn commented
Ok I will readd the alert status and make it so that the only way to tell if an alarm is emagged is by activating it.

2018-09-29 23:07 UTC, nicbn commented
No it only toggle with empty hands
The proc is literally called `attack_hand`

2018-09-29 23:46 UTC, deathride58 commented
Fire alarms have a 33% chance of toggling on/off when damaged by *anything.* Projectiles, toolboxes, etc, are all capable of toggling fire alarms.

Over at Citadel, we made it so that right-clicking fire alarms quickly toggles them if possible. It might be worth taking inspiration from that

2018-09-30 00:05 UTC, nicbn commented
Hmm maybe in another PR

2018-09-30 01:31 UTC, GunHog commented
Please make sure that the AI can sill use it as well. I did not find an attack_ai() in your code. This was previously handled by the TGUI.

2018-09-30 02:12 UTC, nicbn commented
Gimme some time

2018-10-01 03:53 UTC, imsxz commented
freddy alarms buff

2018-10-02 07:51 UTC, Tlaltecuhtli commented
remove tgui

2018-10-05 18:57 UTC, optimumtact commented
please update your OP to reflect the current state of this PR

2018-10-05 19:51 UTC, nicbn commented
It already is up to date

2018-10-08 08:10 UTC, AnturK requested changes
Just this and this is good to go.

2018-10-08 08:10 UTC, AnturK commented on code/game/machinery/firealarm.dm
> +	add_overlay("fire_[detecting && A.fire ? (obj_flags & EMAGGED) ? "emagged" : "on" : "off"]")
This icon state name is complicated enough to put into variable.

2018-10-09 08:52 UTC, AnturK approved these changes

2018-10-09 08:53 UTC, merged