Ejecting canisters from canisters dose not behave as expected #40865 Fix
tgstation/tgstation pull request #40866
Opened 2018-10-11 11:30 UTC by chris-hill1990

[Changelogs]: 

:cl: optional name here
fix: Fixed the canisters eject button to use the replace tank logic
/:cl:

[why]: # see Issue #40865 when ever you eject the tanks from the canisters it whould be placed on the ground not in the users hand

2018-10-11 11:34 UTC, AnturK submitted a review, later dismissed

2018-10-11 11:34 UTC, AnturK commented
You might want to remove "optional name here" from changelog.

2018-10-11 11:36 UTC, chris-hill1990 commented
Thanks for the heads up and cool my first pr. I sorry I had to fix it it bugged the hell out of me that it didn't behave as expected. Please let me know if I did everything right for the pr's and that

2018-10-11 11:44 UTC, chris-hill1990 commented
Just noticed this also happens in the portable air pumps

2018-10-11 11:53 UTC, AnturK commented
Don't worry about travis failure it's issue with byond version.

2018-10-13 17:06 UTC, duncathan requested changes
thank you very much for the fix! just get rid of that semicolon and you're good to go

2018-10-13 17:06 UTC, duncathan commented on code/modules/atmospherics/machinery/portable/canister.dm
> +				replace_tank(usr, FALSE);
please remove the semicolon

2018-10-14 03:56 UTC, merged