Phobia trigger words are highlighted in pulsing red/black
tgstation/tgstation pull request #40885
Opened 2018-10-12 10:32 UTC by XDTM

:cl: XDTM
tweak: Phobia trigger words are now more noticeable.
/:cl:

Spooky

2018-10-12 11:01 UTC, Arianya commented
How does it pulse? Screenshot/gif needeeeed

2018-10-12 11:47 UTC, XDTM commented
It's text that shifts from black to red and back in 0.75 seconds

Can't compile code to get gifs at the moment

2018-10-12 11:50 UTC, AnturK commented
It's just css, https://jsfiddle.net/kveyfurh/

2018-10-12 20:09 UTC, SpaceManiac requested changes

2018-10-12 20:09 UTC, SpaceManiac commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +		100% { color: #0d0d0d; }
The indentation here is wacky and there's some spurious line changes. Ditto below.

2018-10-12 20:09 UTC, SpaceManiac commented on code/datums/brain_damage/phobia.dm
>  			break
Doesn't this `break` mean the replacement below never runs?

2018-10-13 12:57 UTC, Arianya commented
Looks pretty fancy.

2018-10-17 15:15 UTC, Militaires commented
make it the orange TRIGGERED meme

2018-10-20 21:34 UTC, SpaceManiac commented
Awaiting author reply for 7+ days, closed as stale, contact a maintainer for reopen

2018-10-22 10:16 UTC, XDTM commented
@SpaceManiac reviews addressed in new commits

2018-10-22 10:18 UTC, XDTM commented
Reviews addressed in new commits

2018-10-23 12:49 UTC, merged