Gives pais the ability to toot
tgstation/tgstation pull request #40910
Opened 2018-10-13 16:54 UTC by anconfuzedrock

:cl: Confused Rock
rscadd: Pais can now install the loudness booster to play horrible music so they can sound and look awful at the same time!
/:cl:
This allows PAIs to play a recorder (if it were a violin or something it'd probably sound really annoying) if they download the proper software. I think this is the kind of mostly useless feature that pais are built for, and that's about it.

2018-10-13 16:55 UTC, MrDoomBringer commented
well done lad

2018-10-13 16:58 UTC, AnturK requested changes
You need to add deletion of the instrument on pAI destroy.

2018-10-13 16:58 UTC, AnturK commented on code/modules/mob/living/silicon/pai/software.dm
> +			if("loudness")
I know you're just following the convention here but man these are ugly.

2018-10-13 16:58 UTC, AnturK commented on code/modules/mob/living/silicon/pai/pai.dm
> +	var/obj/item/instrument/recorder/P
Name this something more relevant please. Like internal_instrument or whatever.

2018-10-13 17:01 UTC, MrDoomBringer commented
can we get a "good first PR" tag

2018-10-13 17:16 UTC, anconfuzedrock commented
Right I'll add the deletion not that it changes anything

2018-10-13 17:55 UTC, anconfuzedrock commented
Think this fixes it.

2018-10-14 21:47 UTC, anconfuzedrock commented
Am I forgetting something or do I need to somehow resolve the requested changes or what?

2018-10-15 03:00 UTC, MrDoomBringer commented
@anconfuzedrock nah fam ur good, just w8 4 merge

2018-10-15 13:04 UTC, ShizCalev approved these changes

2018-10-15 13:06 UTC, merged