Footsteps sounds for bare feet and other mobs
tgstation/tgstation pull request #40981
Opened 2018-10-17 02:57 UTC by nero1024

Bare feet and other mobs will now make the correct footstep sounds and added new samples to go with them. Added a lot of helpers to is_helpers.dm, mostly for (future) footstep support but maybe someone else can make use of them.

:cl: Nero1024
soundadd: Bare feet will now make the correct footstep sounds.
soundadd: Other mobs will make the correct footstep sounds.
/:cl:

As others indicated in the very first footsteps PR other users wanted footstep sounds for barefeet. I also noticed that do_footstep is in a bunch of other mobs, but Ian and Xenomorphs don't wear shoes so I fixed that too.

Demos:
Barefeet in action: https://my.mixtape.moe/lrtohp.webm
Xenomrphs clacking around: https://my.mixtape.moe/edzqpc.webm

2018-10-17 03:07 UTC, Qustinnus commented
code seems snowflakey

2018-10-17 03:15 UTC, nero1024 commented
I'll admit that `ishumansimple()` is an absolute mess. Any tips on how It can be tidied up and made presentable?

2018-10-17 04:29 UTC, ShizCalev commented on code/__DEFINES/is_helpers.dm
> +#define ishumansimple(A) (istype(A, /mob/living/simple_animal/hostile/cat_butcherer) || istype(A, /mob/living/simple_animal/hostile/faithless) || istype(A, /mob/living/simple_animal/hostile/nanotrase
atleast make it a typecache or something
https://github.com/tgstation/tgstation/blob/151c4e9b183bf233fa9755ecd0d0bb4d7896e208/code/__DEFINES/is_helpers.dm#L16-L23

2018-10-17 04:31 UTC, ShizCalev commented on code/datums/components/footstep.dm
> +	if(isalienadult(LM) || isdog(LM) || isfox(LM) || isbear(LM) || ismegaarachnid(LM))
typecache

2018-10-17 07:34 UTC, Bawhoppen commented
I like adding new footstep sounds, but I'm not so sure about the ones for xenos. While I'm not sure how they *should* sound, doesn't seem right to me.

2018-10-17 10:05 UTC, nicbn commented
Have an associative list including sounds for barefoot, shoes, claws etc. as a var for turfs. Use defines as keys.
Have a var for mobs and shoes that equals to the define of the sound of such mob or shoe.

When the mob steps, check for shoes. If none or if the var equals zero, use the mob define. Else, use the shoes define.
Then, access the turf list using such define as key.

No istypes, just oop.

2018-10-17 15:47 UTC, Qustinnus commented
why not just make the sound lists defines as we do with things such as ambience

2018-10-17 17:05 UTC, epochayur commented
ignoring the fact that xeno footsteps are a thinly-veiled excuse to include step sounds for lizards, isn't the entire point of xenos that they're genetically perfect silent killers? it doesn't make sense to me that you could hear them coming

2018-10-17 20:20 UTC, Poojawa commented
Xenos have very noisy breathing problems, also not spamming *deathgasp is a terrible Xeno

2018-10-18 00:53 UTC, nicbn commented on code/__DEFINES/is_helpers.dm
> +#define isdog(A) (istype(A, /mob/living/simple_animal/pet/dog))
Remove the unused defines you added

2018-10-18 00:59 UTC, nicbn requested changes

2018-10-18 00:59 UTC, nicbn commented on code/__DEFINES/is_helpers.dm
> +GLOBAL_LIST_INIT(simplehuman, typecacheof(list(
You should use a var in these types instead of making a list.

2018-10-18 06:47 UTC, Militaires commented
footsteps for xenos blows their cover early on and ruins the earlygame stealth you need to establish a colony, do u even xenos bro

2018-10-18 08:09 UTC, nero1024 commented
I've tried quieting xeno footsteps down, It seems like you have to be right next to them to hear them now. 
Here's a webm:
https://my.mixtape.moe/vwgqlw.webm

2018-10-18 17:19 UTC, GuyonBroadway commented
Personally I think the xenos sounds are a little too "slappy" for lack of a better term.

Needs a harder "clack" if you can do such a thing.

2018-10-19 00:05 UTC, nero1024 commented
Those are the clack-iest claw sounds that I can source.

2018-10-20 00:19 UTC, nero1024 commented
`if(!T.footstep || LM.buckled || !CHECK_MULTIPLE_BITFIELDS(LM.mobility_flags, MOBILITY_STAND | MOBILITY_MOVE) || LM.throwing || LM.movement_type & (VENTCRAWLING | FLYING))`, specifically mobility_flags, is supposed to check if the mob cannot stand or move correct? How come I'm still hearing footstep sounds from mobs when they're crawling, dead, or lying and being dragged?

2018-10-20 01:32 UTC, nero1024 commented
I've decided to keep the footstep sounds while crawling, and have the barefeet sounds play as well when crawling (cuz you're using your hands to crawl).

2018-10-22 19:07 UTC, Militaires commented
ok what if you're wearing gloves

2018-10-22 19:12 UTC, nero1024 commented
It would sound about the same.

2018-10-27 00:12 UTC, merged