Allows Grilles to be built on space turf.
tgstation/tgstation pull request #41081
Opened 2018-10-22 20:50 UTC by Coconutwarrior97

:cl: 
tweak: Allows Grilles to be built on space turf.
/:cl:

The grilles surrounding the station aren't built on floors. However; if you ever feel like rebuilding them due to the damage they take from space dust/meteors you'll have to create a floor first. Seems like a  waste of resources to have to build a floor for every Grille you repair in space.

2018-10-23 09:10 UTC, Barhandar commented
You can move constructed grilles so you technically only need 1 floor, but it's still annoying as fuck and pointless.

2018-10-23 17:04 UTC, MACIEKBAKI commented
the hero we needed.

2018-10-24 14:34 UTC, Cyberboss requested changes

2018-10-24 14:34 UTC, Cyberboss commented on code/game/objects/items/stacks/rods.dm
> +	new/datum/stack_recipe("grille", /obj/structure/grille, 2, time = 10, one_per_turf = 1, on_floor = 0), \
```suggestion
	new/datum/stack_recipe("grille", /obj/structure/grille, 2, time = 10, one_per_turf = TRUE, on_floor = FALSE), \
```

2018-10-24 15:57 UTC, Barhandar commented on code/game/objects/items/stacks/rods.dm
> +	new/datum/stack_recipe("grille", /obj/structure/grille, 2, time = 10, one_per_turf = 1, on_floor = 0), \
You can now webedit the webedits? Nice!

2018-10-28 18:02 UTC, Cyberboss approved these changes

2018-10-28 18:11 UTC, merged