Adds empty oxygen and plasma tanks to techwebs
tgstation/tgstation pull request #41090
Opened 2018-10-23 06:05 UTC by 81Denton

:cl: Denton
add: The 'Industrial Engineering' research node now includes empty oxygen and plasma tanks.
/:cl:

This PR lets players print empty oxygen and plasma tanks from the RnD and engineering protolathes once they have Industrial Engineering researched.

Turns out that such a basic thing as tank dispensers can't be built or ordered once they're gone. It might be worth adding that in a separate PR.

2018-10-24 04:41 UTC, SpaceManiac requested changes
Looking forward to buildable tank dispensers

2018-10-24 04:41 UTC, SpaceManiac commented on code/game/objects/items/tanks/tank_types.dm
> +	air_contents.assert_gas(/datum/gas/oxygen)
the parent already asserts this gas, so this check is unnecessary

2018-10-24 18:56 UTC, SpaceManiac approved these changes

2018-10-25 21:18 UTC, merged

2018-10-27 15:13 UTC, MegaEmpirical commented
Does this include plasma internal tanks or just the normal tanks that don't fit into any slots?