"Floor is lava" no longer affects flying mobs, like say... artificers from a summon event wizard
tgstation/tgstation pull request #41101
Opened 2018-10-23 19:58 UTC by Robustin

:cl: Robustin
fix: "Floor is lava" event no longer affects flying mobs
/:cl:

2018-10-23 19:58 UTC, adamkad1 commented
yay, i made someone patch something

2018-10-23 22:16 UTC, ShizCalev requested changes

2018-10-23 22:16 UTC, ShizCalev commented on code/datums/weather/weather_types/floor_is_lava.dm
> +	if(L.movement_type == FLYING)
movement_type & FLYING

2018-10-23 22:43 UTC, ShizCalev approved these changes

2018-10-25 08:13 UTC, subject217 commented
Summon events and shard wizard weren't cancerous enough without levitating constructs running hog wild during floor is lava.

2018-10-25 21:14 UTC, merged