Shard layer fix
tgstation/tgstation pull request #41107
Opened 2018-10-24 00:47 UTC by Seagleb

:cl: Zaex
tweak: Supermatter Shard is now placed in front of other objects.
/:cl:

Issue ID# 41043
Suppermatter Shard was being exploited and put under objects to hide it.

2018-10-24 03:05 UTC, optimumtact commented
use a define

2018-10-24 14:10 UTC, ShizCalev requested changes
layer defines go in here
https://github.com/tgstation/tgstation/blob/8a35a5ece0b1aa450724563de9621fef8f6fc87c/code/__DEFINES/layers.dm#L58

also you put the shard not just above objects, but also mobs.

2018-10-24 14:18 UTC, XDTM commented
to be fair it's hard to imagine a situation where a mob is sharing a tile with an SM shard

2018-10-24 14:58 UTC, Seagleb commented
Right, I put it up there because in testing I was able to hide it under corpses as well. Thanks for the info I was looking all over for where the default layer define was

2018-10-25 21:14 UTC, ShizCalev approved these changes

2018-10-25 21:14 UTC, merged