Makes basic tools a starting node instead of having to research them
tgstation/tgstation pull request #41121
Opened 2018-10-24 14:50 UTC by Barhandar

Closes #41091
Makes #41092 irrelevant

:cl: Barhandar
balance: Basic tools are now a starting node and do not need researching.
/:cl:

Because it's bloody stupid that you have to research something you can just otherwise plop down from autolathe.

2018-10-24 16:32 UTC, ExcessiveUseOfCobblestone commented
If something req's this node it should cost more to compensate.

If you're removing the node you'll need to `closes #41092` as well

2018-10-24 17:44 UTC, Barhandar commented
Nothing requires this node at the moment.
The node _technically_ isn't being removed (that would be adding the stuff it makes to base), it's being made starting node which is unlocked by default. Though I guess it does make sense to close the other PR because it's meaningless.

2018-10-29 12:56 UTC, ShizCalev requested changes
Undo the changes from #41092

2018-10-30 10:53 UTC, ShizCalev requested changes

2018-10-30 10:53 UTC, ShizCalev commented on code/modules/research/techweb/all_nodes.dm
>  	id = "basic_tools"
just noticed, move this to the top of the file with the rest of the starting nodes, then all good to merge.

2018-10-30 15:10 UTC, merged