Vareditting the dir var now calls setDir()
tgstation/tgstation pull request #41390
Opened 2018-11-10 01:19 UTC by ShizCalev

Fixes stuff getting out of sync in the case of things like chairs, infrared sensors, conveyor belts, ect.

Shouldn't have any issues, though for some reason I think there's probably a different proc up the atom movement chain that this should be calling instead.

2018-11-10 04:44 UTC, SpaceManiac submitted a review, later dismissed
setDir seems right for this

2018-11-10 07:02 UTC, ninjanomnom commented
I pretty commonly need to change the dir value directly and avoid the setDir call when debugging.

2018-11-11 06:38 UTC, ninjanomnom requested changes

2018-11-11 06:38 UTC, ninjanomnom commented on code/game/atoms.dm
> +				setDir(var_value)
Calling setDir after the value has already changed wont play nicely with functionality which expect the existing dir value to be the old one.

2018-11-11 06:57 UTC, closed without merging

2018-11-11 06:57 UTC, ShizCalev commented
rip