Medbay Item Respriting
tgstation/tgstation pull request #41409
Opened 2018-11-11 01:09 UTC by Coconutwarrior97

🆑
tweak: If you rename medical sprays to styptic powder, silver sulfadiazine, or synthflesh it updates the icon to the appropriate spray type. Also when making patches in the chem master if they are named "brute" or "burn" they have their icon changed to the brute/burn patches.
/🆑
Naming sprays/patches these specific names should change their sprite.

2018-11-11 01:11 UTC, Coconutwarrior97 commented
Previous PR here: https://github.com/tgstation/tgstation/pull/41389
That branch of mine wasn't fully updated to the master so it was causing some major issues.

Unnecessary callings of lowertext() and update_icon() were removed as well.

2018-11-11 01:13 UTC, zxaber commented
How devilish.

2018-11-11 01:21 UTC, ExcessiveUseOfCobblestone submitted a review, later dismissed
use `update_icon()` and check for the name instead.

2018-11-11 02:05 UTC, ShizCalev requested changes

2018-11-11 02:05 UTC, ShizCalev commented on code/modules/paperwork/pen.dm
> +				O.changed_name(input)
I'd have this send a signal instead.

`SEND_SIGNAL(O, COMSIG_RENAMED, user)`

2018-11-11 02:05 UTC, ShizCalev commented on code/modules/reagents/reagent_containers/medspray.dm
> +/obj/item/reagent_containers/medspray/changed_name(newname)
then add a listener and have this just be handled in update_icon()
`AddComponent(/datum/component/redirect, list(COMSIG_RENAMED = CALLBACK(src, .proc/update_icon)))`

2018-11-12 02:09 UTC, kingoftheautism commented
- Is this a brute patch?
- Yeeeessss
- *actually a 40u deadly chem mix*

good pr

2018-11-30 19:15 UTC, ExcessiveUseOfCobblestone commented
Let me know when you want to recontinue this.

2018-11-30 19:15 UTC, closed without merging