teleporter computer now shows renamed beacons
tgstation/tgstation pull request #41407
Opened 2018-11-11 01:07 UTC by zxaber

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Zxaber
add: Teleporter computers now show the name of renamed beacons.
/:cl:

I suspect this was intended, since the beacon already has code for renaming it via pen and a "renamed" variable that gets updated when the beacon is renamed. In any case, it's now consistent with tracking implants, which already show the name of the person implanted.

![image](https://user-images.githubusercontent.com/37497534/48307834-7d55aa80-e50a-11e8-8478-755139223c28.png)

This change only affects the list popup. Once the beacon is selected, the TGUI window shows the actual destination  (also just like tracking implants)

2018-11-13 17:53 UTC, delaron commented
Would it be useful to instead have it display the location and in parenthesis the new name? Currently this include a soft loss of functionality.  If you dont want to the beacon to report location data maybe a separate pr  providing a disable location data option in a on click menu.

2018-11-13 18:22 UTC, zxaber commented
The window is already fairly small, adding both the name and the location would probably cause the text to run offscreen constantly.

Like I said, the location is shown in the tgui window after a selection is made, just like a tracking implant works.

2018-11-13 21:44 UTC, zxaber commented
For clarity's sake, this shows what I mean. Though the pop-up window on the left only shows the new name of the beacon, the tgui window on the right shows the actual destination.

![image](https://user-images.githubusercontent.com/37497534/48444888-158da280-e74a-11e8-9339-a268e3a56444.png)

2018-11-17 08:26 UTC, SpaceManiac requested changes

2018-11-20 00:36 UTC, zxaber commented
Actually, I like the idea that it shows the location as well in the selection box, so that's in. For constancy's sake, tracking implants now show location as well.

![image](https://user-images.githubusercontent.com/37497534/48743717-22623880-ec19-11e8-9cc2-60cbda85177e.png)
(Tracking implant is the bottom selection here)

2018-11-20 00:42 UTC, SpaceManiac approved these changes

2018-11-20 00:48 UTC, merged