MK II. SWAT Suit
tgstation/tgstation pull request #41474
Opened 2018-11-13 12:58 UTC by Steelpoint

This PR sees the old mk2 SWAT suit sprites get some use. This PR creates official baseline MKII Swat Suit.

In 'lore' the MKII SWAT Suit is the baseline of which the Captains SWAT suit is split off from, and is intended as a 'frontline combat armour' for future soldiers. The older MKI SWAT suit is represented as an aged surplus item that cargo can order (and is the signature cargonian uniform) whereas the MKIII SWAT Suit is the hyperadvanced/prototype/expensive newer variant used by the secretive NT Deathsquad. 

![screenshot 2018-11-13 20 51 55](https://user-images.githubusercontent.com/6595389/48414763-8c489100-e786-11e8-8ff9-1b394556728f.png)

Compared with the other SWAT Suits
![screenshot 2018-11-13 20 51 52](https://user-images.githubusercontent.com/6595389/48414777-92d70880-e786-11e8-96a2-7c18f7b85d07.png)

Functionally the armour is identical to the Captains variant sans its greyscale. 

Current its not found anywhere in game and is admin only. I could imagine it being some kind of base for a hirable Mercenary that admins could send in for events or otherwise just a misc item that might show up or be used later. I don't think it'd be appropriate for the station to be able to buy one.

:cl: Steelpoint
add: MK II SWAT Suit has been officially added to the game, the base model that Captains SWAT Suit is based off of. Currently it does not spawn in the game anywhere and is admin only. 
/:cl:

2018-11-13 14:43 UTC, Arianya commented
Wouldn't it make more sense to make this suit the parent and then make the captain's one a child of it?

2018-11-13 14:56 UTC, Steelpoint commented
Actually a good point. I'll rework it to do that when I get a chance.

2018-11-13 16:30 UTC, ExcessiveUseOfCobblestone commented
I'm on the fence about that sprite, there's so much going on i'm not sure what's going on!

2018-11-13 17:10 UTC, SgtxRootbeer commented
The legs and sides of the chest look poorly defined, and the helmet's eyepiece looks different from the Captain's.

Also, you might wanna add the ability to throw the mkII into a washing machine with a blue crayon to get a Captain's varient.

2018-11-13 19:12 UTC, GravitronBlue commented
If this is of any relevance I made a somewhat polished Mk2 suit a while back after being unsatisfied with the greyscale icon.
![](https://i.imgur.com/iizUd1V.png)
(It's really just a less stylish Deathsquad suit that fits better with original UEG helmet icon)

2018-11-13 19:34 UTC, ExcessiveUseOfCobblestone commented
having some color to help define the suit really helps, nice edits.

Reminder you can put sprites in our sprite repo for people to use, i'm sure coders would love to have them :3

2018-11-14 09:22 UTC, optimumtact commented
I have an inbuilt rage defence mechanism against swat suits thanks to @Bawhoppen

2018-11-14 10:33 UTC, Bawhoppen commented
SWAT is the future, don't let anyone tell you otherwise @Steelpoint

2018-11-14 10:42 UTC, Steelpoint commented
@GravitronBlue if you want me to use your sprites I'd need em in a dmi format for ease of use.

2018-11-14 10:54 UTC, Steelpoint commented
I've repathed it so the Captains SWAT suit is now a subtype of the regular SWAT suit.

2018-11-14 19:37 UTC, ExcessiveUseOfCobblestone commented
why did you ping baw you've made a grave mistake...

2018-11-15 00:08 UTC, FantasticFwoosh commented
> 
> 
> SWAT is the future, don't let anyone tell you otherwise @Steelpoint

![You're either SWAT or you're not](https://puu.sh/C1UDs/3fed56ef20.jpg)

2018-11-15 06:49 UTC, lolman360 commented
craftable/orderable secways when

2018-11-20 00:11 UTC, SpaceManiac submitted a review, later dismissed

2018-11-20 00:11 UTC, SpaceManiac commented on code/modules/clothing/spacesuits/hardsuit.dm
> -	allowed = GLOB.security_hardsuit_allowed
Seems like this got dropped

2018-11-22 15:21 UTC, Steelpoint commented on code/modules/clothing/spacesuits/hardsuit.dm
> -	allowed = GLOB.security_hardsuit_allowed
I think I resolved it

2018-11-22 15:21 UTC, Steelpoint commented
I think I should've fixed the issue.

2018-11-30 03:54 UTC, ExcessiveUseOfCobblestone submitted a review, later dismissed

2018-11-30 22:02 UTC, SpaceManiac submitted a review, later dismissed
Is it "MK II." or "MK.II"? It's meant to be in the same series as the "MK.I" and "MK.III", right?

2018-11-30 22:02 UTC, SpaceManiac commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "A MK.II SWAT suit with streamlined joints and armor made out of superior materials, insulated against intense heat. The most advanced tactical armor available Usually reserved for heavy hitt
Missing `.` before `Usually`

2018-11-30 22:02 UTC, SpaceManiac commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "MK II. SWAT Suit"
Name should have `\improper`, so we get "a/the MK.II SWAT suit"

2018-12-03 18:06 UTC, Steelpoint commented
done

2018-12-03 19:14 UTC, ExcessiveUseOfCobblestone requested changes
finishing touches :)

2018-12-03 19:14 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "MK.II. SWAT Helmet"
```suggestion
	name = "\improper MK.II. SWAT Helmet"
```

2018-12-03 19:14 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	name = "MK.II. SWAT Suit"
```suggestion
	name = "\improper MK.II. SWAT Suit"
```

2018-12-03 19:14 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "A tactical SWAT helmet MK.II boasting better protection and a horrible fashion sense."
```suggestion
	desc = "A tactical MK.II SWAT helmet boasting better protection and a horrible fashion sense."
```

2018-12-03 19:14 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/spacesuits/hardsuit.dm
> +	desc = "A MK.II SWAT suit with streamlined joints and armor made out of superior materials, insulated against intense heat. The most advanced tactical armor available Usually reserved for heavy hitt
```suggestion
	desc = "A MK.II SWAT suit with streamlined joints and armor made out of superior materials, insulated against intense heat. The most advanced tactical armor available. Usually reserved for heavy hitter corporate security, this one has a regal finish in Nanotrasen company colors. Better not let the assistants get a hold of it."
```

2018-12-04 05:32 UTC, Steelpoint commented
Yay

2018-12-04 17:39 UTC, ExcessiveUseOfCobblestone approved these changes

2018-12-04 17:40 UTC, merged

2018-12-04 17:49 UTC, Steelpoint commented
The offer to use @GravitronBlue sprites in lieu of this PR's one is still on the table.