Paystands now take a custom input for payment
tgstation/tgstation pull request #41588
Opened 2018-11-18 20:55 UTC by MMMiracles

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: MMMiracles
tweak: Paystands now ask for how much you want to deposit when interacting instead of a static price.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I thought it was pretty dumb the paystands designed to encourage shops was also forced to a single static price instead of allowing the person to put in how much they actually wanted to pay.

2018-11-18 21:37 UTC, PKPenguin321 commented
Allow the stand owner to set a min and max, maybe?

2018-11-18 22:10 UTC, MMMiracles commented
I dunno exactly what you could use with a minimum/maximum amount, but I am going to add an option to slap a signaler on it that activates when a threshold is hit on depositing.

2018-11-19 03:08 UTC, swindly commented on code/modules/economy/pay_stand.dm
> +			var/cash_limit = input(user, "Enter the minium amount of cash needed to deposit before the signaler is activated.", "Signaler Activation Threshold") as null|num
```suggestion
			var/cash_limit = input(user, "Enter the minimum amount of cash needed to deposit before the signaler is activated.", "Signaler Activation Threshold") as null|num
```

2018-11-19 05:01 UTC, davethwave commented
Set up a hellnade hidden outside or inside sec with a signaler attached to it. Then make a paystand saying *I will destroy sec for 500 moneys* or something. Watch as sec gets hellnade by the power of capitalism.

2018-11-19 12:44 UTC, 81Denton commented
Now I can finally swallow a signaller and have people pay me to die

2018-11-19 17:48 UTC, coiax commented
@MMMiracles coding tills with payment terminals when

2018-11-19 19:41 UTC, Cyberboss requested changes
Other spelling reviews +

2018-11-19 19:41 UTC, Cyberboss commented on code/modules/economy/pay_stand.dm
> +	var/obj/item/assembly/signaler/signaler = null //attached signaler, let people attach signalers that get activated if the user's transaction limit is achieved.
```suggestion
	var/obj/item/assembly/signaler/signaler //attached signaler, let people attach signalers that get activated if the user's transaction limit is achieved.
```

2018-11-19 19:41 UTC, Cyberboss commented on code/modules/economy/pay_stand.dm
> +				name = "[msg]"
```suggestion
				name = msg
```

2018-11-19 20:47 UTC, MMMiracles commented
I wanna do ATMs next to allow pulling credits out and depositing physical cash. Maybe even let people hack them for their internal hold of physical cash and give grey shirts more !FUN! ways of getting dirty money.

2018-11-20 17:13 UTC, ExcessiveUseOfCobblestone commented on code/modules/economy/pay_stand.dm
> +				desc = "Owned by [assistant_mains_need_to_die.registered_account.account_holder], pays directly into [user.p_their()] account."
todo: make desc customizable

2018-11-21 00:30 UTC, Iamgoofball commented
Fuck off with that atm idea holy shit we literally do not need ATMs
The pr is good though

2018-11-21 03:19 UTC, Iamgoofball commented
faur but I'll call you fucking retarded for it

2018-11-21 08:14 UTC, PKPenguin321 commented
WOW goof, reported you to github for being rude/ableist which violates their ToS.

2018-11-22 23:05 UTC, Militaires commented
Goof has been attacked, this will not stand.

2018-11-23 22:44 UTC, k-k-karma commented
@PKPenguin321 You fucking killed Goofball

2018-12-02 07:10 UTC, merged

2018-12-02 21:11 UTC, optimumtact commented
```
[2018-12-02 21:00:58.676] runtime error: Cannot read null.secured
[2018-12-02 21:00:58.676] proc name: attackby (/obj/machinery/paystand/attackby)
[2018-12-02 21:00:58.676]   source file: pay_stand.dm,64
[2018-12-02 21:00:58.676]   usr: Grant Tin (/mob/living/carbon/human)
[2018-12-02 21:00:58.676]   src: Pay to kill me (/obj/machinery/paystand)
[2018-12-02 21:00:58.676]   usr.loc: the floor (108,116,2) (/turf/open/floor/plasteel)
[2018-12-02 21:00:58.676]   src.loc: the floor (108,115,2) (/turf/open/floor/plasteel)
[2018-12-02 21:00:58.676]   call stack:
[2018-12-02 21:00:58.676] Pay to kill me (/obj/machinery/paystand): attackby(the remote signaling device (/obj/item/assembly/signaler), Grant Tin (/mob/living/carbon/human), "icon-x=19;icon-y=17;left=1;scr...")
[2018-12-02 21:00:58.676] the remote signaling device (/obj/item/assembly/signaler): melee attack chain(Grant Tin (/mob/living/carbon/human), Pay to kill me (/obj/machinery/paystand), "icon-x=19;icon-y=17;left=1;scr...")
[2018-12-02 21:00:58.676] Grant Tin (/mob/living/carbon/human): ClickOn(Pay to kill me (/obj/machinery/paystand), "icon-x=19;icon-y=17;left=1;scr...")
[2018-12-02 21:00:58.676] Pay to kill me (/obj/machinery/paystand): Click(the floor (108,115,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=19;icon-y=17;left=1;scr...")
[2018-12-02 21:00:58.676] Blargety (/client): Click(Pay to kill me (/obj/machinery/paystand), the floor (108,115,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=19;icon-y=17;left=1;scr...")
```

2018-12-03 07:19 UTC, MMMiracles commented
d'oh