Security Departmental Helmets
tgstation/tgstation pull request #41642
Opened 2018-11-23 12:55 UTC by Steelpoint

This PR adds unique helmets that departmental officers can chose to find and wear, the helmets spawn inside the departmental closets 

I've been thinking of ways to give departmental officers something else unique as a fun toy or item for being part of that department. Since giving the Cargo officer a free combat shotgun would be excessive, I've started with this minor idea.

![screenshot 2018-11-23 20 45 24](https://user-images.githubusercontent.com/6595389/48944484-d2a9a700-ef61-11e8-9105-69252533d48d.png)
Left to right: Science, Medical, Engineering, Cargo

The helmets themselves are cosmetic only, while I'd like to explore them having minor differences (Med helm with a bit more bio prot, sci with a bit more explosive prot, etc) but I want to avoid wars over sec buffs.

Feedback appreciated, and if there is anything cool I could look to further giving departmental officers as a neat toy or minor item. 

:cl: Steelpoint
add: Departmental Security Officers have been issued new helmets for their assigned department, each helmet is only cosmetically different. They can be found inside the departmental lockers.
/:cl:

2018-11-23 12:59 UTC, Steelpoint commented
I might do a slight rework on the Sci and Eng helmets to be more akin to the Cargo helm.

2018-11-23 13:48 UTC, Grazyn commented
You may want to make the helmet strip a bit wider so it doesn't look like the tip of a penis

2018-11-23 13:53 UTC, Steelpoint commented
![screenshot 2018-11-23 21 52 19](https://user-images.githubusercontent.com/6595389/48946907-389a2c80-ef6a-11e8-95ec-59e74852b5df.png)

I've updated the side sprites a bit.

2018-11-23 20:54 UTC, subject217 commented
Kor had a good PR for unique departmental sec guard stuff from like April or thereabouts. Might be a good place to look for some inspiration.

2018-11-24 01:58 UTC, Steelpoint commented
Yeah but some of his proposals were way too good, cargo officer gets a Combat Shotgun or a traitor item  Sci officer gets reactive armour or a advance gun.

I might look at something more mild like the med officer getting a first aid kit and akin

2018-11-24 11:34 UTC, Steelpoint commented
The mask implication is its blast plating to help protect against fragmentation and debris from explosions.

2018-11-24 11:35 UTC, Steelpoint commented
I think I'll do one more sprite edit to standardise the sprite dimensions of the departmental colours so the positioning is consistent.

2018-11-24 12:02 UTC, Steelpoint commented
I've done a final update on the sprites, and have updated the OP with the latest varient.

![screenshot 2018-11-24 19 52 41](https://user-images.githubusercontent.com/6595389/48967994-cede5900-f023-11e8-9d41-e609a69f2d06.png)
Cargo-Engineering-Medical-Science

I'll leave this PR as is. I'll consider adding a minor item of note to each of the dept sec closets in a future PR.

2018-11-24 15:51 UTC, improvedname commented
Remember that mini hypospray steel give that to the medbay officer with safeties

2018-11-24 18:11 UTC, Cyberboss requested changes
Any reason you aren't overriding the basic sec helmet?

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +	can_flashlight = TRUE
```suggestion
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +	can_flashlight = TRUE
```suggestion
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +	can_flashlight = TRUE
```suggestion
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +	can_flashlight = TRUE
```suggestion
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/med
```suggestion
/obj/item/clothing/head/helmet/sec/med
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/eng
```suggestion
/obj/item/clothing/head/helmet/sec/eng
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/crg
```suggestion
/obj/item/clothing/head/helmet/sec/crg
```

2018-11-24 18:11 UTC, Cyberboss commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/sci
```suggestion
/obj/item/clothing/head/helmet/sec/sci
```

2018-11-24 18:11 UTC, Cyberboss commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/head/helmet/med(src)
```suggestion
	new /obj/item/clothing/head/helmet/sec/med(src)
```

2018-11-24 18:11 UTC, Cyberboss commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/head/helmet/sci(src)
```suggestion
	new /obj/item/clothing/head/helmet/sec/sci(src)
```

2018-11-24 18:11 UTC, Cyberboss commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/head/helmet/eng(src)
```suggestion
	new /obj/item/clothing/head/helmet/sec/eng(src)
```

2018-11-24 18:11 UTC, Cyberboss commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/clothing/head/helmet/crg(src)
```suggestion
	new /obj/item/clothing/head/helmet/sec/crg(src)
```

2018-11-25 17:58 UTC, Steelpoint commented
I missed that, thanks @Cyberboss 

Changed effected.

2018-11-26 12:08 UTC, Memager commented
The cargo helmet is almost the same color as the engineering one, maybe use the orange from the engi armband?

2018-11-27 05:48 UTC, Steelpoint commented
Done

2018-11-29 04:09 UTC, ninjanomnom requested changes

2018-11-29 04:09 UTC, ninjanomnom commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/sec/crg
crg? We don't live in a world of limited name sizes, make it more clear

2018-12-02 14:35 UTC, Cyberboss commented
Your PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

2018-12-02 15:30 UTC, Steelpoint commented
Not enough interest.

2018-12-02 15:30 UTC, closed without merging