Added TRAIT_DISK_VERIFIER, refactors how fake disk checks work slightly
tgstation/tgstation pull request #41711
Opened 2018-11-28 02:24 UTC by coiax

Old system: Fake disk checks on examine() can be done by ghosts, nuke ops and Captains. However, this is
done through isobserver(), assigned_role, and has_antagonist datum.

New system: Check the mob or the mind for the TRAIT_DISK_VERIFIER trait, and allow them
to check the fake that way. Gets rid of stuff being hard coded to "assigned_role".

I think this is a good idea, and was good practice for me doing trait related stuff.

2018-11-28 17:49 UTC, ExcessiveUseOfCobblestone commented
what's the benefit of instead of putting the checks on the singular item you now have to sift through various files to ensure a mob does/doesn't have X trait?

2018-11-28 20:19 UTC, coiax commented
What do you mean, sift through various files?

I mean, for one thing, means the captain could order a "Nuke Disk Identification pamphlet" for the head of security or something, who could then be taught in the arcane ways of checking serial numbers.

2018-11-28 21:04 UTC, ExcessiveUseOfCobblestone commented
for instance if I want to see who can/cannot see le epic examine I have to go to job.dm, dead.dm, and nukeops.dm (and that's assuming I know where to look) vs it all being in the singular file in the singular proc where I can say "Oh just captains, ops, and observers can see the message".

But if you plan on making it malleable then this is fine, just u kno follow thru lol

2018-11-28 22:39 UTC, coiax commented
So, you're saying I should put a comment in, explaining who normally has the trait?

2018-11-28 22:43 UTC, ExcessiveUseOfCobblestone commented
nah you can easily lookup the trait define it's just a minute pain if I wanted to webbit something :P

2018-11-30 05:57 UTC, SpaceManiac requested changes

2018-11-30 05:57 UTC, SpaceManiac commented on code/modules/antagonists/nukeop/nukeop.dm
> +	owner.add_trait(TRAIT_DISK_VERIFIER, "nuke-op")
Should probably be matched with losing the trait when not a nuke op anymore

2018-11-30 05:57 UTC, SpaceManiac commented on code/modules/jobs/job_types/captain.dm
> +	mind_traits = list(TRAIT_DISK_VERIFIER)
Feels iffy to me that this is on the outfit, maybe it should go on the job instead?

2018-12-11 17:30 UTC, merged

2018-12-11 17:31 UTC, tgstation-server commented
Your Fix/Feature pull request delta is now above zero (1). Feel free to make Feature/Tweak/Balance PRs.