Gibs now rot and generate miasma
tgstation/tgstation pull request #41782
Opened 2018-12-03 16:13 UTC by coiax

:cl: coiax
add: Gibs will now rot if not cleaned, and produce small amounts of miasma, approximately
equal to a quarter of a corpse.
/:cl:

Miasma is fun. Gives the janitor more of a reason to do work. It will only become
dangerous if you have a lot of gibs in a small space. So better keep those Hopline shutters
open.

2018-12-03 16:39 UTC, Steelpoint commented
This is a nice change, although I do think miasma needs to be more prominent since I've never seen miasma become a issue at any point.

2018-12-03 17:22 UTC, MACIEKBAKI commented
Well you know miasma factories.. you could always set up a miasma factory and put it in the distro loop... crazy antag idea right there!!

2018-12-03 22:19 UTC, Potato-Masher commented
Literally, the only time I have ever seen Miasma come into play was yesterday when someone made a gas chamber with Miasma that would keep you throwing up for a solid 10 minutes after you got out.

2018-12-03 23:10 UTC, Arianya commented
We Dwarf Fortress Now

2018-12-05 00:38 UTC, Cyberboss requested changes

2018-12-05 00:38 UTC, Cyberboss commented on code/game/objects/effects/decals/cleanable/humans.dm
> +	var/list/cached_gases = T.air.gases
Use T.return_air() instead of T.air

2018-12-08 02:09 UTC, Cyberboss requested changes

2018-12-08 02:09 UTC, Cyberboss commented on code/game/objects/effects/decals/cleanable/humans.dm
> +	STOP_PROCESSING(SSobj, src)
Unnecessary?

2018-12-08 08:18 UTC, coiax commented on code/game/objects/effects/decals/cleanable/humans.dm
> +	STOP_PROCESSING(SSobj, src)
Yep, nice catch.

2018-12-09 13:29 UTC, merged

2018-12-09 14:01 UTC, Jordie0608 commented
You are the weakest link coiax.