Boxstation EVA Mapping Changes
tgstation/tgstation pull request #41798
Opened 2018-12-04 06:59 UTC by Steelpoint

This is a split up of my prior PR (https://github.com/tgstation/tgstation/pull/41608), this PR focuses on the EVA change. 

![screenshot 2018-11-21 00 03 51](https://user-images.githubusercontent.com/6595389/48787185-4447e200-ed23-11e8-86b4-bbb399251cd1.png)
EVA

:cl: Steelpoint
add: NTSS Boxstations EVA area has undergone a large scale retrofit by the Nanotrasen Corps of Engineers.
/:cl:

2018-12-04 08:29 UTC, Steelpoint commented
Other half of what.

2018-12-04 08:32 UTC, JMoldy commented
Having only shutters and no door into this section of EVA is a little awkward. Combining multiple rooms into one strikes me as unnecessary, the division allowed for people to control a little bit better who was getting what.

2018-12-04 08:35 UTC, Steelpoint commented
The ultimate effort here is to make it far easier for someone to open EVA to the crew if needed for a emergency. If I were to section off half of the EVA storage akin to the original design, I'd have to make the initial area open access, or do a entirely different redesign.

Furthermore the tools in EVA storage allow people to assist in station repairs, and keeping all the supplies in one area does try to suggest this.

2018-12-04 08:47 UTC, nicbn commented
More EVA suits = less conflict in case of emergency (which is bad, don't forget we're playing paranoid spessmen simulator)
Also looks big and empty.

2018-12-04 08:50 UTC, Steelpoint commented
I have alternative designs if we want to reduce the number to six suits.

I've never seen conflict over a lack of space suits, the only time this is a issue is during Blob, but infinite SWAT suits helps combat that.

2018-12-04 13:00 UTC, Tlaltecuhtli commented
the room on the right

2018-12-04 13:04 UTC, Steelpoint commented
Command tool storage is untouched.

2018-12-04 14:42 UTC, MrDoomBringer commented
@nicbn is right here, more spacesuits means less reason for cargo to order them, for example

2018-12-04 15:38 UTC, anconfuzedrock commented
This makes eva easier to bust into because nobody can see you if you hack in from maint. Box eva was always openable by the ai or a remote or a toolbelt or by smashing windows anyway.

2018-12-04 16:07 UTC, Steelpoint commented
An alternative idea I had was to resize the room slightly by pushing it down northward a few tiles, remake the upper area into a maintenance area and bringing the suits down to six or less. That'd make the room less big, and you won't be able to freely break in as easily.

2018-12-04 21:59 UTC, improvedname commented
Remove tool storage right of eva make that into teleporter then put tool storage next into caps office with some greytide spawns.

2018-12-04 21:59 UTC, improvedname commented
Also if you secure the jetpack/magboots because meta design you also have to secure the rcd

2018-12-04 22:00 UTC, improvedname commented
If your keeping the tool storage right of it remove the toolboz in the space suit room or merge it into one.

2018-12-04 22:23 UTC, epochayur commented
i like the changes overall but I still think 8 is too many

2018-12-07 13:59 UTC, ShizCalev approved these changes

2018-12-08 02:06 UTC, Cyberboss requested changes
Check mapdiffbot, something seems wrong...

2018-12-08 22:48 UTC, ShizCalev commented
oof

2018-12-09 10:17 UTC, optimumtact commented
just set a pop max on box or something smh

2018-12-09 10:17 UTC, closed without merging