Succumb is only possible below -70% health
tgstation/tgstation pull request #41961
Opened 2018-12-14 17:41 UTC by kriskog

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Skoglol
tweak: You cannot succumb above -70% health. Down from -1% via verb, -30% via whisper.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
I see a lot of abuse of the succumb verb lately, ranging from people denying slimes feeding on them to people just succumbing out of being converted/deconverted during those modes. It's an easy out of #fun and great for cucking antags. I dont think full removal is in order, but being able to succumb at -1% health is getting silly. 

This changes both the verb and succumbing by whispering to only work under -70% health (down from -1% and -30% respectively) , which I think is a much more reasonable treshold for giving up on life. It does let you whisper for longer, but you still lose hearing at the old treshold so you can only really keep the monologue going.

If you refuse to wait the few minutes dying usually takes if left alone, then you can ghost instead but take the permanent round removal choice.

2018-12-14 18:44 UTC, DaxDupont commented
Good now I can torture people longer

2018-12-14 18:50 UTC, epochayur commented
haha holy fuck this is terrible

2018-12-14 19:10 UTC, ExcessiveUseOfCobblestone commented
why not just set it to fullcrit? If you're getting them down to -30 to (de)convert you're dumb but I do think there's a sweet spot we can get to enforce good faith (particularly with conversion) at the cost of missing a small amount of time doing ghosty stuff.

2018-12-14 19:32 UTC, kriskog commented
I dont think fullcrit is low enough, at only 30 damage below crit while you are also taking oxyloss damage. If you are trying to keep someone alive for something, I don't think they should be able to get out of it just because you hit them one extra time after entering crit. If they are adamant about not participating in the roleplaying/fun, they can still ghost.

That's not to say I'm not up for discussing the limit at 70, but I don't think it should be very much higher.

2018-12-14 19:48 UTC, RogueSteampunker commented
>I see a lot of abuse of the succumb verb lately, ranging from people denying slimes feeding on them to people just succumbing out of being converted/deconverted during those modes. 

So xenobio, cult, and revs are having issues with literally beating people to near death, and having them die? Who could have expected this one?

>This changes both the verb and succumbing by whispering to only work under -70% health (down from -1% and -30% respectively) , which I think is a much more reasonable treshold for giving up on life. It does let you whisper for longer, but you still lose hearing at the old treshold so you can only really keep the monologue going.

So it literally does nothing for anyone but antags who literally want to skip the step of ensnaring someone, and go straight into mirror shied mirror shield drag crit body onto rune, or sec who need more of a reason to put revs down cause "they can't just succumb before I can implant."

>If you refuse to wait the few minutes dying usually takes if left alone, then you can ghost instead but take the permanent round removal choice.

So either hope your antag is being a ganky asshole, or wait three minutes on a white screen while you gasp in a locker in maint. This doesn't seem like good game design in any form or the sort, especially when the only other option you leave is to permanently leave the fucking round.

2018-12-14 20:34 UTC, Tlaltecuhtli commented
the whole issue is because of those pyro anomaly event slimes, why not remove the slimes instead for being a shitty memebone ghost role which if the OP was slighty more smart he would notice that you can just feed on monkeys or braindead which are common when the events happen

>there is a problem for cult ppl succumbing
then dont fucking kill people cause its faster to shoot em death and drag, if they succumb because they dont want to play then the cultist can use those nice soul shards feature that pull from salt chat if the dude ghosts from the shard, if the victim wanted to play as  human cultist and got crit dragged by the cultist he could just not ghost lol

only thing it ll add is more people ahelping to offer their body because they didnt want to play cult and more people complaining as they  get put into a crit loop with either regen coma, medibots, other shenanigans or by malicious players as you can just crit someone and filling  him with epinephrine as they cant succumb without being perma removed and ll have to wait 2-3 min to heal out of crit or die out

2018-12-14 20:43 UTC, ExcessiveUseOfCobblestone commented
You're trying to patch admin issues with code so there's obviously going to be an argument against the worst playertype still abusing mechanics unless you outright remove succumbing. That obviously isn't acceptable so those people really shouldn't be considered in the argument code-wise. I'm also not balancing around slimetags lol there are plenty of bodies they can use and abuse and they are certainly not central baddies.

It should be low enough that you still have time to quickly take them to get converted after being critted without basically making it so they have to constantly keep getting pounded/wait 5ever before they can just give up.

On Tlat's point, there should also be a time mechanic where you can succumb if you've been stuck in crit for an extended period of time regardless of what health you're at.

2018-12-14 21:36 UTC, anconfuzedrock commented
Maybe people succumbing to avoid facing the music would be an issue, if sec officers started with a single lethal weapon (spoilers: hydro starts with a more lethal weapon than a sec officer)

2018-12-15 00:16 UTC, Cyprex commented
Does this mess with succumbing while being cloned?

2018-12-15 11:09 UTC, PKPenguin321 commented
*ghosts and disconnects*

2018-12-16 22:33 UTC, ExcessiveUseOfCobblestone commented
@PKPenguin321 the issue is people succumbing to deny baddies, if they take the ghost route they can't come back in as that character.

A less aggressive option would be to notify admins if someone succumbs while being pulled by an antagonist, but you'd have to assume admins would be willing to consider such actions a rule 1 violation else it's just spammy.

2018-12-16 23:45 UTC, PKPenguin321 commented
That's stupid as fuck, if you don't want people succumbing on you when you're an antag just don't crit them??

2018-12-17 00:33 UTC, ExcessiveUseOfCobblestone commented
We can't move away from stun based combat then tell antags they must use stuns as the only method to safely control someone unfortunately.

"Just don't crit them" doesn't answer the bad-sportsmanship aspect of succumbing to avoid gameplay, I'm thinking mostly conversion. Cult has some countermeasure to this by shards but those come with a disadvantage compared to a human cultist. If you don't want to play as that character at all anymore this PR will not affect that, it will only affect people who DO want to play as that character but don't like the team they're on.

2018-12-17 00:39 UTC, ExcessiveUseOfCobblestone requested changes
For ease of access, 

This will need a time component so that people can't indefinitely be critted AND unable to be succumbed if the antag keeps them at a certain HP level.

I'm thinking succumb can be made available after the %HP threshold OR after a minute of being in crit regardless of %.

2018-12-17 02:04 UTC, ExcessiveUseOfCobblestone commented
Talked this over with my gfs and it’s basically fruitless to try to force people to play the game. If this is an issue it should be taken up with your local administration.

2018-12-17 02:04 UTC, closed without merging