Beepsky Retaliate Fix
tgstation/tgstation pull request #42007
Opened 2018-12-19 07:21 UTC by Garen7

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Garen
fix: Beepsky once again will defend himself when attacked.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Tested and Fixes #42006

2018-12-19 08:11 UTC, carshalash commented
Much appreciated, have a nice day.

2018-12-19 08:21 UTC, Garen7 commented
np dog

2018-12-20 00:44 UTC, nicbn requested changes

2018-12-20 00:44 UTC, nicbn commented on code/game/objects/items/robot/robot_parts.dm
> +	if(!item_in_hand || !(item_in_hand.tool_behaviour == TOOL_MULTITOOL))
use `!=`

2018-12-20 00:44 UTC, nicbn commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +	if(!(W.tool_behaviour == TOOL_SCREWDRIVER) && (!target)) // Added check for welding tool to fix #2432. Welding tool behavior is handled in superclass.
same

2018-12-20 00:44 UTC, nicbn commented on code/modules/mob/living/simple_animal/bot/honkbot.dm
> +	if(!(W.tool_behaviour == TOOL_SCREWDRIVER) && (W.force) && (!target) && (W.damtype != STAMINA) )
same

2018-12-20 00:44 UTC, nicbn commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +	if(!(W.tool_behaviour == TOOL_SCREWDRIVER) && (W.force) && (!target) && (W.damtype != STAMINA) ) // Added check for welding tool to fix #2432. Welding tool behavior is handled in superclass.
same

2018-12-20 21:05 UTC, merged

2018-12-27 18:55 UTC, GhostEcho commented
Cue accidentally hitting beepsky with an object and pissing it off

2018-12-27 18:56 UTC, GhostEcho commented
Does this apply to thrown objects though is the real question