Blacklists supermatter, shield walls, and containment fields from swarmer consumption.
tgstation/tgstation pull request #42052
Opened 2018-12-23 08:30 UTC by FrostyFridge

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Frosty Fridge
tweak: Swarmers can no longer unleash Lord Singuloth or eat the Supermatter.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Containment Field generators were already blacklisted for swarmer disassembly, but the containment fields themselves could be disassembled. This has been rectified.  Shield generators and their shields have been blacklisted as well. The supermatter has been blacklisted as well, for obvious reasons.

Disclaimer: i ded

2018-12-23 08:31 UTC, obscolene commented
These were already blacklisted, I already tested it literally last round.

2018-12-23 09:01 UTC, FrostyFridge commented
My bad, you're correct about the SM already being blacklisted. The containment fields were not.
https://giant.gfycat.com/HardCarefreeCoral.webm

2018-12-23 12:02 UTC, tuypo1 commented
I think it would be better to make them able to but make it take a while, gives the crew something to mobilise against when there are swarmers

2018-12-24 20:28 UTC, Cyberboss submitted a review, later dismissed

2018-12-24 20:29 UTC, Cyberboss requested changes

2018-12-28 10:24 UTC, merged