Notifies ghosts when bombs and C4/X4 get activated
tgstation/tgstation pull request #42081
Opened 2018-12-26 10:27 UTC by 81Denton

:cl: Denton
tweak: Ghosts now get notified whenever a bomb or C4/X4 get activated.
/:cl:

This notifies ghosts whenever a bomb gets activated and lets them jump to it. It's always hilarious watching people try to defuse bombs, or Ricky playing out hostage situations.

Edit: I added a notification for C4/X4 as well.

2018-12-26 12:12 UTC, tuypo1 commented
Best thing is when somebody accidentally attaches a bomb to themselves.

2018-12-26 12:59 UTC, 81Denton commented
Actually, adding that for C4 and X4 might be nice too. It's not like every round has a ton of them that would spam ghost chat.

2018-12-26 13:45 UTC, tuypo1 commented
The question is would grenades be too much.
Maybe have syndicate grenades notify but not flashbangs and things.

2018-12-26 14:01 UTC, 81Denton commented
I think that grenades might be too much since they can be spammed hard (like the nuke ops grenade belt) and usually just have a 5 second fuse.

2018-12-26 16:33 UTC, Vidiveni commented
Could do the same for bomb cores. They can be built empty though.

2018-12-27 00:02 UTC, SpaceManiac requested changes
Avoid using "[name]" in user-facing strings

2018-12-27 00:02 UTC, SpaceManiac commented on code/game/machinery/syndicatebomb.dm
> +	notify_ghosts("A [name] has been activated at [get_area(src)]!", source = src, action = NOTIFY_ORBIT, ghost_sound = 'sound/machines/beep.ogg')
```suggestion
	notify_ghosts("\A [src] has been activated at [get_area(src)]!", source = src, action = NOTIFY_ORBIT, ghost_sound = 'sound/machines/beep.ogg')
```

2018-12-27 00:02 UTC, SpaceManiac commented on code/game/objects/items/grenades/plastic.dm
> +		notify_ghosts("[user] has planted [name] on [target.name] with a [det_time] second fuse!", source = src, action = NOTIFY_ORBIT, ghost_sound = 'sound/machines/beep.ogg')
```suggestion
		notify_ghosts("[user] has planted \a [src] on [target] with a [det_time] second fuse!", source = src, action = NOTIFY_ORBIT, ghost_sound = 'sound/machines/beep.ogg')
```

2018-12-27 20:19 UTC, SpaceManiac requested changes
The orbit links don't work because they're set to `source = src`, which is summarily deleted

2018-12-27 21:16 UTC, 81Denton commented
I changed the source to `target` now.

2018-12-27 21:37 UTC, SpaceManiac approved these changes

2018-12-27 21:38 UTC, merged

2018-12-30 00:04 UTC, Hathkar commented
Any chance you could lower the volume on this? It's extremely loud, and gets grating very quickly.

2018-12-30 11:06 UTC, 81Denton commented
Sure thing! I'll get to it when I'm back home.