Wearing freshly washed clothes makes you feel better
tgstation/tgstation pull request #42129
Opened 2018-12-29 20:10 UTC by coiax

:cl: coiax
add: Wearing a jumpsuit that's been washed in a washing machine
will give you a positive moodlet.
/:cl:

In addition, cleaned up the washing machine code so there no longer
needs to be a "has_corgi" var.

Something with dodgy colours no longer clobbers the examine text on a jumpsuit

2018-12-29 23:55 UTC, JJRcop commented
What do you think about changing `freshly_laundered` into a timestamp that it was laundered, and you only get the moodlet if it was within some time (long? short?)

2018-12-30 04:57 UTC, optimumtact commented
@JJRcop that does imply either the moodlet or the item has to check periodically though

2018-12-30 11:01 UTC, coiax commented
@Tlaltecuhtli Good idea, but out of scope.

2019-01-02 15:52 UTC, Cyberboss requested changes

2019-01-02 15:52 UTC, Cyberboss commented on code/modules/clothing/under/_under.dm
> +	to_chat(world, "<span class='reallybig'>[user], [slot]</span>")
.

2019-01-11 05:05 UTC, merged