Item fortification scroll changes
tgstation/tgstation pull request #42173
Opened 2019-01-01 14:32 UTC by coiax

:cl: coiax
fix: Applying an item fortification scroll to a non-enchanted item no longer has a chance of immediately deleting that item.
tweak: Also, item fortification scrolls have more colourful messages.
/:cl:

Essentially, old behaviour: item fortification scroll adds the RPG loot datum, then upgrades it. But sometimes the random loot datum has a level greater than 10, which means when the item is upgraded, there's a serious risk of it immediately turning to dust.

New behaviour: applying an item fortification scroll to a mundane item makes a special message (more nethack references) and just applies a loot datum without modifying it.

- Also, item fortification scrolls are no longer created in nullspace during the RPG Loot event.
- Item fortification scroll now just have a "uses" var, instead of one_use.

2019-01-01 15:08 UTC, 4dplanner commented
While you're at it, 

`I.armor = I.armor.modifyAllRatings(quality)` should use quality_mod, shouldn't it?

2019-01-02 15:50 UTC, Cyberboss requested changes

2019-01-02 15:50 UTC, Cyberboss commented on code/modules/events/wizard/rpgloot.dm
> +	if(uses <= 0)
```suggestion
 	if(--uses <= 0)
```

2019-01-02 15:50 UTC, Cyberboss commented on code/modules/events/wizard/rpgloot.dm
> +	uses--
```suggestion
```

2019-01-03 02:10 UTC, lordpidey requested changes

2019-01-03 02:10 UTC, lordpidey commented on code/modules/events/wizard/rpgloot.dm
> +		if(can_backfire && (quality > 9 && prob((quality - 9)*10)))
`if(can_backfire && quality > 9 && prob((quality - 9)*10))`

2019-01-10 20:18 UTC, ExcessiveUseOfCobblestone commented
granny pr

2019-01-14 17:29 UTC, merged