Kaledioscope component, for colour-changing pattern
tgstation/tgstation pull request #42381
Opened 2019-01-16 07:35 UTC by coiax

:cl: coiax
refactor: The way that colorful reagent, crayon powder,
and the nuke disk suicide function at a code level has been changed.
/:cl:

The kaleidoscope component standardises the "changes colour every X
tickets" component that the nuke disk and (sort of) colorful reagent
exhibit.

I have something in mind for this sort of pattern, where you
can just put the component on something, then remove it later when
you're done with the color changing, but this is a complex enough change
that I wanted to make it seperate.

- Crayonpowder is no longer a subtype of colorful reagent, given it
has only a single colour to apply (but I'm not wedded to the idea, it
just seemed simpler).

- Coding/admin item, the "colorful spray bottle", which has colorful
reagent, and also has the kaleidoscope component which means it changes
colour constantly on its own anyway.

- For badminry, adding the kaledioscope component (or one of its
subtypes) to an atom will have it strobe through colours. No clue what
you'd use it for.

2019-01-16 15:10 UTC, nicbn commented
I think you should name it something more clear like color_flick

2019-01-16 15:40 UTC, Qustinnus commented
@coiax ethereal discoball might need this component too, but that also has lights and not just the color

2019-01-18 12:18 UTC, Jordie0608 commented on code/datums/components/kaleidoscope.dm
> +				_index = _index + 1
```suggestion
				_index++
```

2019-01-18 12:18 UTC, Jordie0608 commented on code/datums/components/kaleidoscope.dm
> +				_index = 1
Is this not just `next_list_item()`?
https://github.com/tgstation/tgstation/blob/a89c5aee03f3660d31715f268b192270e90abeae/code/__HELPERS/_lists.dm#L283-L290

2019-01-18 12:18 UTC, Jordie0608 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		A.add_atom_colour(chosen, WASHABLE_COLOUR_PRIORITY)
No component?

2019-01-18 12:18 UTC, Jordie0608 commented on code/datums/components/kaleidoscope.dm
> +	qdel(src)
Idk if it's great to create a timer only to delete the component after, maybe you should have a switch for if the color is one-time or not. Or maybe make `/once` the default behavior and have a child that handles repeating? 
Can't be sure that's worth the bother however ¯\\\_(ツ)_/¯

2019-01-23 20:26 UTC, Cyberboss requested changes

2019-01-30 16:43 UTC, closed without merging