Sepia slime extract works like a grenade [WIP]
tgstation/tgstation pull request #42494
Opened 2019-01-23 16:42 UTC by 4dplanner

:cl: optional name here
balance: sepia slime extract has a delay before activating
balance: sepia slime extract freezes the user
/:cl:

2019-01-23 16:57 UTC, Shadowflame909 commented
So now it freezes you. Does it Still do that if you go near the time clock? Or just the initial reaction

2019-01-23 16:59 UTC, imsxz commented
redpilled

2019-01-23 17:01 UTC, 4dplanner commented
So the way this works will be:
t=0: sepia slime is injected
You then throw it
t=5: it spawns the big clock
Anyone walking into the big clock is frozen as usual, including you.

2019-01-23 17:02 UTC, Shadowflame909 commented
Oh. So this won't be very useful outside of a ranged laser attack.

2019-01-23 17:05 UTC, iskyp commented
yeah but we already have large grenade casings 
why not just make it freeze the user

2019-01-23 17:07 UTC, 4dplanner commented
The changelog already says that
balance: sepia slime extract freezes the user if they're in the AOE

2019-01-23 17:08 UTC, 4dplanner commented
It'll still be useful for several reasons - 
1:if you hit someone with it they are basically dead, because you can just throwing weapon them to death/stand just outside
2: powerful area denial/escape ability
3: defensive purposes

2019-01-23 17:08 UTC, Shadowflame909 commented
Kind of misleading as that's not the important feature

2019-01-23 17:09 UTC, 4dplanner commented
There are two, are you serious?

2019-01-23 17:09 UTC, iskyp commented
hence why not just make it freeze the user instead of making it also have a delay
this is a stealth nerf to the large grenade casing if you want to get big brained about it

2019-01-23 17:09 UTC, 4dplanner commented
If you just make it freeze the user it'd be useless, why would you freeze yourself?

2019-01-23 17:10 UTC, 4dplanner commented
You shouldn't HAVE to use the large casing to make it worthwhile

2019-01-23 17:10 UTC, AdamElTablawy commented
making it freeze the user would make it useless, tbh. the delay before activation should be strong enough-it's very powerful, but still.

also, this would make recurring slime extracts worse than useless-you'd activate it and then someone could pick it up, activate it and throw it back *to you.*

crossbreeds shouldn't be affected by this, basically, and a delay in activation SHOULD be enough to make this not disgustingly powerful anymore. even if you're not going to bother with the removing the freeze the user effect, don't change crossbreeds for this-they're time consuming enough to deserve a reward and the only crossbreed that really needs a nerf is the permanent methspeed slime

(also i'm fairly sure holy melons and null rods block slime timestop magic regardless).

2019-01-23 17:11 UTC, 4dplanner commented
I don't believe that "it takes a long time" is justification to have that level of power.

2019-01-23 17:12 UTC, 4dplanner commented
As to just having the delay, that would make spam throwing and also just running at people far too good

2019-01-23 17:15 UTC, iskyp commented
the delay is stupid because, if you don't want to freeze yourself, you should make it into a grenade
>you shouldn't have to use a grenade to make it worthwhile

then why have large grenade casings when their entire point is to be grenades for slime extracts

2019-01-23 17:15 UTC, 4dplanner commented
Just because one specific slime extract doesn't need them, doesn't mean they're not useful for any of the others

2019-01-23 17:16 UTC, 4dplanner commented
Grenades should be an optional upgrade for a slime extract, not a necessary function for them.

2019-01-23 17:17 UTC, 4dplanner commented
rephrased to the shadow flame way

2019-01-23 17:18 UTC, iskyp commented
i think it should need them though which is my entire argument, because having no delay while still freezing the user would balance them in exactly the same way you're trying to achieve here just with a little more hassle to achieve breaking the flow of time itself

2019-01-23 17:19 UTC, AdamElTablawy commented
While I don't like to use other things as an example of being overpowered as a justification for another thing, I could point out that *most* things scale with power like that. Mechs, for one, or genetics.

Still, that's not necessarily a good example, so here's a better justification-Each crossbred chilling slime can only be used once ever since I fixed it, and recurring slimes can be used against you, accordingly, and neither can be mass produced. You can either create a large amount of sepia slimes-which you already do-and attempt to stunlock someone down with timestops, and while that's viable it's not an incredibly effective tactic. It's certainly one of the strongest tools xenobiology has by default, alongside mobs and instant heals and all of that, and with the old infinite timestop being gone you now need to actually stock up on plasma and slime cores for these things to function-which takes a fair amount of effort, considering that slimes are obnoxious to breed and take a while and so on and so forth. Reproductive extracts neutralize some of that, but still.

You're basically turning one extract from a very good extract which can be used as a weapon of mass destruction via timestop chaining someone to a weapon that can't really be used very well at all since it freezes you too and has a smaller radius than a chemical grenade which you could make in science regardless. There's a reason nobody uses oil slimes.

The delay alone should be a nerf to their function, and punishing someone for going to the effort to get a crossbred slime, intentionally meant to be fairly powerful for all the time it takes to breed ten cerulean slime cores and slot them into an adult sepia slime is kinda shitty.

2019-01-23 17:19 UTC, 4dplanner commented
You're right, it would work. I guess I just think that'd be a bit of an over-nerf before we've seen how this plays out.

2019-01-23 17:23 UTC, 4dplanner commented
So there are two parts here - firstly, I don't think it's THAT much effort. Make a reproductive cerulean, reap the rewards. 

Secondly, even having only say 5 chilling extracts would be far too good.

As to the use of the new sepias, I still think they'd be very useful. As I've said, they confirm a kill, and what makes them better than mere explosions is the fact the field stays behind. Recurring slimes would admittedly have a pretty strong nerf - but how many people you'd be fighting just happen to carry plasma syringes around?

2019-01-23 17:25 UTC, AdamElTablawy commented
I like the idea of being able to lob a slime core at someone for a timestop, and I like the idea of cerulean slimes having some backlash, since someone could activate the slime and throw it back at you if you use a recurring to get around inventory management problems, but the freezing the user makes it a shitty idea to use in general because it's really easy to kill yourself with in the process as a result. 

Chilling extracts do not freeze the user anyway, because you can mark yourself as not to be frozen regardless and thus would still be superior to ordinary slime extracts for the exact same reason you are concerned they would be 'too good.' What you just said doesn't make much sense on that mark.

2019-01-23 17:27 UTC, 4dplanner commented
It's WIP, I haven't decided on what to do with chilling slimes yet.

2019-01-23 17:27 UTC, 4dplanner commented
I agree that if just this was merged it'd be pretty inconsistent.

2019-01-23 17:27 UTC, Shadowflame909 commented
Wait you can put slime extracts in grenades? Oh shit. Why don't I see orange mini fireball and sepia slime grenades

2019-01-23 17:28 UTC, AdamElTablawy commented
Crossbreeding can usually take more time than the round actually HAS, because of RNG and murderbone interrupting you as well as how annoying it can be to get the necessary things for reproductive extracts, etc.

@Shadowflame909 Because phlog grenades are easier to make, which is why orange slimes suck, and sepias can just be popped normally.

2019-01-23 17:39 UTC, Shardj commented
Feels like chilling sepia is now in the right place, since to replicate the functionality of what was recurring sepia with chilling sepia you need 10u plasma each time. What I don't like is how recurring sepia is now just useless. I think sepia could be nerfed in better ways, simply shortening the freeze time would be a more appropriate nerf. I'm sure there are other more appropriate nerfs too

2019-01-23 17:45 UTC, Tlaltecuhtli commented
you just need to apply brain think to make the recurring ones work

2019-01-23 17:47 UTC, 4dplanner commented
I'd honestly rather snowflake recurring sepia than sabotage what I believe to be otherwise a good nerf. Would you say other than recurring it was fine?

As to the plasma part, plasma dust is too easily acquired to be a good balancing lever

2019-01-23 17:47 UTC, ExcessiveUseOfCobblestone commented
Train came early today.

2019-01-23 17:55 UTC, Amelia0010 requested changes

2019-01-23 17:55 UTC, nichlas0010 commented on code/modules/reagents/chemistry/recipes/slime_extracts.dm
> +	new /obj/effect/timestop(T, null, null, null)
```suggestion
	new /obj/effect/timestop(T)
```

2019-01-23 17:55 UTC, 4dplanner commented on code/modules/reagents/chemistry/recipes/slime_extracts.dm
> +	new /obj/effect/timestop(T, null, null, null)
...good point

2019-01-23 20:24 UTC, optimumtact commented
4dplanner making an an enemy of sci mains next

2019-01-23 21:56 UTC, nichlas0010 commented
why...

2019-01-23 22:16 UTC, 4dplanner commented
I'm burned out for the moment honestly

2019-01-23 22:17 UTC, FrostyFridge commented
thank god

2019-01-23 22:35 UTC, Shadowflame909 commented
Thus the tale of a man fighting against the salt of the playerbase comes to a halt. He needed a break from being viewed as the bad guy. But surely, another one to burden these negative feelings shall arise...

2019-01-23 23:03 UTC, imsxz commented
i cant believe xenobabies killed our hero

2019-01-23 23:30 UTC, Whoneedspacee commented
@4dplanner take a good break and honestly just work on whatever you're passionate about. I'm honestly feeling the same way as you.

2019-01-24 05:55 UTC, optimumtact commented
I didn't say you could sleep

2019-01-24 07:35 UTC, KomradeSpectre commented
Downvoted because I think the better way of balancing the sepia extract/time stopping is to make the field slow users and projectiles down instead of completely stopping them. Making the spell be "Slow Time" instead of "Time Stop". This would allow counterplay, but still have good strength to it.

2019-01-24 09:35 UTC, Shardj commented
> Downvoted because I think the better way of balancing the sepia extract/time stopping is to make the field slow users and projectiles down instead of completely stopping them. Making the spell be "Slow Time" instead of "Time Stop". This would allow counterplay, but still have good strength to it.

That would make it useless

2019-01-24 10:11 UTC, zeroisthebiggay commented
You know this is like the only 4dplanner nerf I partially agree with.
I remember a time I was a Nightmare, a scientist ran up to me _in maintenance_, stopped me with a sepia extract and proceeded to beat me to death with a crowbar while they shined a flashlight on me.
It should not be possible to fight a side antagonist with one of their hard counters being "bring a friend" in a one on one fight with **a fucking crowbar**.

Though I think it'd probably better to rework it into a slow time rather than a full _"congratulations you're stunlocked as a nukie and this scientist is going to slowly kill you with a toolbox"_.

2019-01-24 10:19 UTC, 4dplanner commented
So you agree when u are the one who is ded :^)


I still might well finish this later, though.

2019-01-24 10:56 UTC, Shardj commented
> You know this is like the only 4dplanner nerf I partially agree with.
> I remember a time I was a Nightmare, a scientist ran up to me _in maintenance_, stopped me with a sepia extract and proceeded to beat me to death with a crowbar while they shined a flashlight on me.
> It should not be possible to fight a side antagonist that excells in one on one combat (with one of their hard counters being "bring a friend") in a head on fight with **a fucking crowbar**. I ded.
> 
> Though I think it'd probably better to rework it into a slow time rather than a full _"congratulations you're stunlocked as a nukie and this scientist is going to slowly kill you with a toolbox"_.

Just stun them before they do that... you had all of the advantages still, that's like complaining that you were hit with a tazer even though you have a hitscan rocket launcher

2019-01-24 10:58 UTC, 4dplanner commented
You can't really use melee stuns against a scientist with a 5x5 melee instakill

2019-01-24 14:53 UTC, Shardj commented
Been talking about balancing this a lot in discord, main problem is that you can effectively carry tons of these making them disproportionately strong for how easy they are to get. A single use sepia would be less deadly than a grenade, and you have to work far harder to get it than you would to even get a maxcap. It's the botany problem again, the sheer volume of a certain strong weapon you can carry thanks to department plant/bio bags. Spamming timestops, making you effectively unstoppable is the issue here.

So the **proposed solution** which we like as a basepoint nerf to try is currently:

Sepia slimes now spawn "Bluespace Stopclocks" when the extract is given plasma, "Strangely fluctuating weight, its constant shifting in space causes it to take up more room than you'd think. Halts time on activation in a small area". After creation they take a minute to wind up before they're able to be used, and placing them in a bluespace bag will cause a tear in reality the same as placing a bluespace bag in another bluespace bag. These take up a "laser gun size" space in a bag severely limiting how many can be carried and stops rapid spam creating and using of them due to their prep time after creation.

This will mean a player is very limited on how many they can carry, they sacrifice being able to have a bluspace bag, and if they do carry them then they're sacrificing a lot space in their bag that could otherwise be used by crossbreeds, weapons and other. Feedback would be appreciated.

2019-01-24 16:03 UTC, dylanstrategie commented
Yes brother, bring on the nerfs. Teach them

2019-01-24 18:23 UTC, wesoda25 commented
> Been talking about balancing this a lot in discord, main problem is that you can effectively carry tons of these making them disproportionately strong for how easy they are to get. A single use sepia would be less deadly than a grenade, and you have to work far harder to get it than you would to even get a maxcap. It's the botany problem again, the sheer volume of a certain strong weapon you can carry thanks to department plant/bio bags. Spamming timestops, making you effectively unstoppable is the issue here.
> 
> So the **proposed solution** which we like as a basepoint nerf to try is currently:
> 
> Sepia slimes now spawn "Bluespace Stopclocks" when the extract is given plasma, "Strangely fluctuating weight, its constant shifting in space causes it to take up more room than you'd think. Halts time on activation in a small area". After creation they take a minute to wind up before they're able to be used, and placing them in a bluespace bag will cause a tear in reality the same as placing a bluespace bag in another bluespace bag. These take up a "laser gun size" space in a bag severely limiting how many can be carried and stops rapid spam creating and using of them due to their prep time after creation.
> 
> This will mean a player is very limited on how many they can carry, they sacrifice being able to have a bluspace bag, and if they do carry them then they're sacrificing a lot space in their bag that could otherwise be used by crossbreeds, weapons and other. Feedback would be appreciated.

Make a PR and force the feedback.

2019-01-24 19:36 UTC, ExcessiveUseOfCobblestone commented
The core issue for me is that it gives the scientist immunity to the field. For wizard it makes sense I guess because lol muh 1v50 but certainly not for a science item.

2019-01-24 21:43 UTC, Shardj commented
> The core issue for me is that it gives the scientist immunity to the field. For wizard it makes sense I guess because lol muh 1v50 but certainly not for a science item.

Do you not think it'd be useless without that affect? Also I really don't think it's any more powerful than a regular grenade, bomb,  any botany bullshit or any of the rest when compared as a single use item. And it requires far more work to acquire. than the above mentioned items. However, if the bluespace stopclock still isn't enough of a nerf things can be tweaked, honestly though after that I can't see people calling sepia overpowered when compared to gold mobs or adamantium.

2019-01-24 21:55 UTC, ExcessiveUseOfCobblestone commented
No that's why I think it's the core issue lol. It's why it needs to be delayed so you can drop it, it WOULD be useless if it was instant and 100% trapped you inside.

2019-01-24 21:58 UTC, ExcessiveUseOfCobblestone commented
Also any other BS xenobio can obtain does not justify an arms race with itself.

2019-01-24 22:03 UTC, Shardj commented
You can only throw stuff then to affect the person trapped, xenobio doesn't synergise with that. It also makes all of the sepia crossbreeds useless.

2019-01-24 22:09 UTC, 4dplanner commented
It doesn't make ALL of the crossbreeds useless

2019-01-24 22:10 UTC, Shardj commented
> It doesn't make ALL of the crossbreeds useless

It makes all of the ones that aren't already terrible terrible too

2019-01-24 22:57 UTC, Shardj commented
> Yes it's almost like timestop should be used to get out of an area instead of allowing for free hits on everyone inside with no counterplay.

There is no should, it's whatever it's chosen to be. And that hasn't been its purpose in the past so you can't really pull that. However if you feel so strongly about this, then I recommend you take this nerf as it is on this branch and merge it. But I know I and others aren't happy with the state of this and other nerfs recently.

2019-01-24 22:59 UTC, optimumtact commented
oh no, whatever will we do to restore shardj's happiness.

2019-01-24 23:00 UTC, Shardj commented
> oh no, whatever will we do to restore shardj's happiness.

You act like I didn't just say you can merge this, I'm just a peon, feel free. I'm not dramatic enough to claim tg is dead like some people because of minor nerfs.

2019-01-24 23:01 UTC, KomradeSpectre commented
> Yes it's almost like timestop should be used to get out of an area instead of allowing for free hits on everyone inside with no counterplay.

Making it a huge slowdown instead of a complete stop would be good for adding counterplay, but retaining it's strength. Everyone inside of the field would be moving slower(we're talking like Citrus tier slow), and the projectiles would be moving slow. Some other changes I can't really think of would have to be made to make this viable.

2019-01-24 23:04 UTC, 4dplanner commented
If shardj's solution isn't acceptable, I have thought up a solution to the recurring thing: have it recall to hand after activating (or possibly after the effect ends)

2019-01-25 02:39 UTC, OverlyGeneric commented
> So the **proposed solution** which we like as a basepoint nerf to try is currently:
> 
> Sepia slimes now spawn "Bluespace Stopclocks" when the extract is given plasma, "Strangely fluctuating weight, it's constant shifting in space causes it to take up more room than you'd think. Halts time on activation in a small area". After creation they take a minute to wind up before they're able to be used, and placing them in a bluespace bag will cause a tear in reality the same as placing a bluespace bag in another bluespace bag. These take up a "laser gun size" space in a bag severely limiting how many can be carried and stops rapid spam creating and using of them due to their prep time after creation.
> 
> This will mean a player is very limited on how many they can carry, they sacrifice being able to have a bluspace bag, and if they do carry them then they're sacrificing a lot space in their bag that could otherwise be used by crossbreeds, weapons and other. Feedback would be appreciated.

Holy moly, this sounds fantastic. 4dplanner why don't you put some extra effort into your PR and make a feature instead of a removal?

This is an interesting and clever concept that would work. **Steal the idea** and make it your own. It's free real estate.


> Next thing you know xenobio will be giving themselves fireball and bolt of death because of the “fun” argument.

**No, do not. Bad soda. Do NOT GIVE HIM IDEAS.**

2019-01-25 10:47 UTC, Tlaltecuhtli commented
what if instead it stopped only items(projectiles, trowns,etc) and made the people in the field slown down? so they could have an anime fight

2019-01-25 17:32 UTC, ExcessiveUseOfCobblestone commented
@KomradeSpectre idc what happens in the field as long as the spawner is affected by it as well. Getting free hits whether it's because they literally can't do anything or because they're too slow to strike back isn't fun.

2019-01-25 18:01 UTC, Shardj commented
@ExcessiveUseOfCobblestone you're gonna hate these obscure things called tazers.

2019-01-25 18:09 UTC, ExcessiveUseOfCobblestone commented
There are several ways to avoid and/or mitigate stuns and it's quite obvious when they have tasers out.

2019-01-25 18:21 UTC, Shardj commented
@ExcessiveUseOfCobblestone they're also a round start item. If you want to be serious about it though. How do you plan to deal with a guy who has a bluespace bag full of IED spears. I ask because in my mind they're equally powerful and neither have good counterplay apart from the fact that you can carry a fuck ton of sepias but only a few spears. I'll quite often go for grenade spears in a bluespace bag along with some helpful stabilized crossbreeds.

I can honestly see what you're getting at, I just don't view it as a problem.

2019-01-25 18:58 UTC, ExcessiveUseOfCobblestone commented
I've already said in another PR I would love to see those removed as well.

2019-01-25 19:10 UTC, Shardj commented
I'm looking forward to the drama of that one, pretty much the only positive thing about it though

2019-01-25 20:34 UTC, OverlyGeneric commented
> Sepia slimes now spawn "Bluespace Stopclocks" when the extract is given plasma, "Strangely fluctuating weight, it's constant shifting in space causes it to take up more room than you'd think. Halts time on activation in a small area". After creation they take a minute to wind up before they're able to be used, and placing them in a bluespace bag will cause a tear, in reality, the same as placing a bluespace bag in another bluespace bag. These take up a "laser gun size" space in a bag severely limiting how many can be carried and stops rapid spam creating and using of them due to their prep time after creation.


Sounds cool, 4dplanner put some extra effort into your PR and implement this. It's an interesting and clever concept.

2019-01-25 20:37 UTC, 4dplanner commented
Was unironically in talks with shardj about this, and he said he'd code it himself.

2019-01-25 20:52 UTC, ExcessiveUseOfCobblestone commented
When are we replacing timestop with wizard-time so I can summon Gomorrah to kill the colossus?

2019-01-25 21:40 UTC, wesoda25 commented
Tasers are stupid (kinda eh) but theres a ton of counterplay to them. Anti magic doesn’t even work now so you’re a God with sepia extract.

2019-01-25 22:15 UTC, Shardj commented
> Was unironically in talks with shardj about this, and he said he'd code it himself.

I'm only going to do it if maintainers don't shoot it down, I would've already started if I hadn't received such negative reactions from oranges and cobble. I've heard positive responses from most others so far though.

2019-01-25 22:16 UTC, Shardj commented
> Tasers are stupid (kinda eh) but theres a ton of counterplay to them. Anti magic doesn’t even work now so you’re a God with sepia extract.

Getting in a regular stun or grenade is still just as effective. You become a station wide threat yes, are you unstoppable, not at all. But yeah it's too strong for how easy it is to get tons of.

2019-01-25 23:12 UTC, Shardj commented
https://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgKC4p-D2Cgw/view

I only shaded the first frame properly for now as it probably won't be animated except maybe at activation? But that's a rough idea of how I imagine it

2019-01-26 00:57 UTC, wesoda25 commented
Wait do you intend for the animation to begin once activated (plasma injected), and once it finishes the animation the clock stops and time actually freezes? That'd be really cool.

2019-01-26 02:37 UTC, Shardj commented
> Wait do you intend for the animation to begin once activated (plasma injected), and once it finishes the animation the clock stops and time actually freezes? That'd be really cool.

I have no plans for how to use the animations, I haven't thought about it

2019-01-30 16:52 UTC, ExcessiveUseOfCobblestone commented
IDC how it's approached as long as the end product makes the user, by default at least, susceptible to the field.

2019-01-30 16:52 UTC, ExcessiveUseOfCobblestone commented
Update on this btw?

2019-01-31 09:43 UTC, Shardj commented
If that's your unmoving position then you'll never be happy with my nerf, so may as well merge this in as it currently is @ExcessiveUseOfCobblestone as I can't see a better solution.

2019-01-31 09:44 UTC, Shardj commented
@4dplanner any thoughts?

2019-01-31 09:46 UTC, Shardj commented
Hm, another idea, merge this in as it currently is. But maybe stablized sepia gives you partial immunity to the time field? The current stablized sepia is terrible

2019-02-03 12:52 UTC, 4dplanner commented
I'm still not looking at this until things cool down a bit IRL, but I'll re-open later if shardj's solution doesn't go through.

2019-02-26 15:21 UTC, 4dplanner commented
here we go again

2019-02-26 15:24 UTC, closed without merging

2019-02-26 15:33 UTC, Whoneedspacee commented
ok

2019-02-26 15:52 UTC, 4dplanner commented
Please can I direct you to my new website at https://github.com/tgstation/tgstation/pull/42933

2019-07-29 20:25 UTC, wesoda25 commented
interesting