Reduces toxin damage and increases metabolisation rate of perfluorodecalin
tgstation/tgstation pull request #42528
Opened 2019-01-26 16:37 UTC by 4dplanner

## Changelog
:cl:
balance: buffs perfluorodecalin by decreasing strength of side effects
balance: lowers metabolisation rate
/:cl:

## About The Pull Request
What it says on the tin

## Why It's Good For The Game
closes #42527

2019-01-26 17:03 UTC, 4dplanner commented
@angustmeta what do you think of this is a toxin power?

2019-01-26 17:05 UTC, Rayisken commented
Might as well just relabel it as salbutamol

2019-01-26 17:53 UTC, GuyonBroadway commented
Honestly Perf started life as a better salbutomol and then got given the mute as it was a better salbutomol.

Turns out the mute just made it an easier to get mute toxin and if you just made the salbutomol recipie easier and got rid of perf we really wouldn't be losing anything of value.

2019-01-26 17:55 UTC, doublepointstation commented
4d died again? oof

2019-01-26 18:04 UTC, 4dplanner commented
4d manages to die to something not yet in the game: the latest from vital feedback

2019-01-26 18:06 UTC, 4dplanner commented
Actually Terry might have it whoops

2019-01-26 20:20 UTC, 4dplanner commented
I'd rather not nerf salbu, given oxyloss is so niche + epi is so good anyway. If someone else wants to PR that they can feel free, it's a simple numbers change. 

However the rest of that sounds pretty reasonable. I'll adjust this PR to make it happen.

2019-01-26 20:31 UTC, 4dplanner commented
Gone for 0.3 toxin, could be tuned down later if that proves too much.

2019-01-27 03:29 UTC, chesse20 requested changes

2019-01-27 07:55 UTC, Angustmeta commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	M.adjustToxLoss(0.3*REM, 0)
@chesse20 
He reverted to 0.1 metabolism. Dexalin is 0.4. It heals less than salbutamol, can be overdosed and can not be made. 

Eventually the other oxyloss meds should be nerfed imo, or choking be buffed. And/or more sources of oxyloss be added.

2019-01-27 14:07 UTC, wesoda25 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	M.adjustToxLoss(0.3*REM, 0)
We have more than enough sources of oxyloss, the problem is epinephrine is the greatest cuck all so it almost makes other meds pointless, given you recover from oxygen damage on your own.

2019-01-27 19:06 UTC, Rayisken commented
Maybe change PFDs use to some inline with realworld use, it has been studied for liquid breathing (which we kinda have already in its space walk application) it's an ingredient in a number of blood substitutes as well. Maybe we can have it become a middle point between sab+saline glucose. Remove the mute for on touch applications and injections and give a delayed+short mute on ingestion like a hard max of 5-10 seconds of silence. The justification for muting on ingestion would be it's relaxing the throat/vocal chords or something.

2019-01-27 20:16 UTC, FantasticFwoosh commented
In general, outlasting damage as a chemist by t-posing outside the station in creative mode doped up to your eyeballs in every kind of damage healing chem & perflu is bad design; you could never survive space in such a way through a chemical compound in real life without dramatic hibernation-like physiologically induced changes.

2019-01-28 00:18 UTC, wesoda25 commented
> In general, outlasting damage as a chemist by t-posing outside the station in creative mode doped up to your eyeballs in every kind of damage healing chem & perflu is bad design; you could never survive space in such a way through a chemical compound in real life without dramatic hibernation-like physiologically induced changes.

Yeah bubblegum doesn't exist either. Realism argument, surprisingly enough, is still shit.

2019-01-30 17:23 UTC, ExcessiveUseOfCobblestone commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	M.adjustToxLoss(0.3*REM, 0)
we also don't use dex

2019-01-30 19:33 UTC, ExcessiveUseOfCobblestone commented
I'm imagining higher Oxyloss heal and no toxloss.

Perf should be used to delay oxyloss at the cost of an increasing toxloss (emergencies).

2019-01-31 06:17 UTC, GuyonBroadway commented
Or swap the recipies over so the weaker chem has the easier recipie.

2019-01-31 16:18 UTC, ExcessiveUseOfCobblestone commented
People are comfortable with salbu being THE oxyloss medicine so may as well retain that design.

2019-02-03 15:46 UTC, 4dplanner commented
@ExcessiveUseOfCobblestone are you saying I should make those changes (i.e. medkits having perflu) in this PR?

2019-02-04 16:31 UTC, ExcessiveUseOfCobblestone commented
not necessarily i've just been lazy

2019-02-04 16:42 UTC, merged