Prevents admins from doing stupid things
tgstation/tgstation pull request #42534
Opened 2019-01-26 23:44 UTC by monster860

So we had a round on yogs today where one of the admins made the unfortunate decision of changing the `bounds` var on a briefcase, which has no protections at all, to `2, 2`resulting in jerky movement.

2019-01-27 00:14 UTC, Cyberboss approved these changes

2019-01-27 03:36 UTC, chesse20 requested changes
I think admins are supposed to do stupid things, we shouldnt limit their power :yum:

2019-01-27 04:34 UTC, Jordie0608 commented
Like `bound_width`, `bound_x`, etc. `bounds` can have legitimate cases for being changed, it's not locked because of that. Add it to this list instead:
https://github.com/tgstation/tgstation/blob/6df78fc92aebb55802858b59e63930334145b281/code/modules/admin/verbs/modifyvariables.dm#L7

2019-01-27 05:15 UTC, nicbn commented
>Prevents admins from doing stupid things

Misleading title, does not remove mass purrbation

2019-01-30 07:39 UTC, SpaceManiac approved these changes
haven't done the research on how badly setting this actually breaks things but this isn't really a meaningful var in our current movement system, so this is good to go in

2019-01-30 07:39 UTC, merged

2019-01-30 15:03 UTC, Cyberboss commented
lmao