fixes barnyard only being able to curse humans
tgstation/tgstation pull request #42603
Opened 2019-01-30 15:38 UTC by tralezab

fixes #41721

i might need to test this first

2019-01-30 15:39 UTC, tralezab commented on code/modules/spells/spell_types/barnyard.dm
> -	if(!(target.type in compatible_mobs))
it checked the specific type but not sub types which messed it up, or something like that

2019-01-30 15:44 UTC, adamkad1 commented
will it kill plasmamems?

2019-01-30 18:11 UTC, davethwave commented
It would if the mask doesn't allow internals

2019-01-30 18:36 UTC, Cyberboss requested changes
Use the typecache function family, change `compatible_mobs` to a typecache

2019-01-31 20:23 UTC, tralezab commented
@Cyberboss this should work but you should double check just in case

2019-02-01 20:06 UTC, SpaceManiac requested changes

2019-02-01 20:06 UTC, SpaceManiac commented on code/modules/spells/spell_types/barnyard.dm
> +	var/list/compatible_mobs_typecache = list(/mob/living/carbon/human, /mob/living/carbon/monkey)
I believe you will need to do this, in order for the `is_type_in_typecache` check to work correctly:
```suggestion
	var/list/compatible_mobs_typecache = typecacheof(/mob/living/carbon/human, /mob/living/carbon/monkey)
```
I suggest testing though.

2019-02-02 20:40 UTC, tralezab commented
i think you were right, let me try this

2019-02-02 21:14 UTC, tralezab commented
![image](https://user-images.githubusercontent.com/40974010/52169397-76df6500-26ec-11e9-8ee1-3ca3cc28c4d9.png)
confirmed working now

2019-02-04 17:11 UTC, ExcessiveUseOfCobblestone commented
This will kill plasmamen, as none of the barn masks allow for internal usage.

2019-02-05 00:37 UTC, SpaceManiac commented
It did before, it was just inconsistent (ex-humans transformed into plasmamen were vulnerable, for instance).

2019-02-05 15:58 UTC, ExcessiveUseOfCobblestone commented
rip

2019-02-05 17:33 UTC, tralezab commented
sucks to be a plasmaman, people don't pick barnyard often anyways.

2019-02-06 01:34 UTC, pizzatiger commented
I see no problem with it killing plasma-men seeing how plasma men are immune to hive-minds heart-attack power

2019-02-06 18:18 UTC, merged