Tweaks lights to spark less
tgstation/tgstation pull request #42696
Opened 2019-02-07 19:04 UTC by VileBeggar

## About The Pull Request
Makes lights spark less.

## Why It's Good For The Game
These things spark way too often, and it's frankly quite annoying.

## Changelog
:cl: Vile Beggar
tweak: Lights now spark less.
/:cl:

2019-02-07 19:38 UTC, 81Denton submitted a review, later dismissed

2019-02-07 20:32 UTC, ExcessiveUseOfCobblestone requested changes

2019-02-07 20:32 UTC, ExcessiveUseOfCobblestone commented on code/modules/power/lighting.dm
> +#define BROKEN_SPARKS_MIN 30 SECONDS
```suggestion
#define BROKEN_SPARKS_MIN (30 SECONDS)
```

2019-02-07 20:32 UTC, ExcessiveUseOfCobblestone commented on code/modules/power/lighting.dm
> +#define BROKEN_SPARKS_MAX 90 SECONDS
```suggestion
#define BROKEN_SPARKS_MAX (90 SECONDS)
```

2019-02-07 20:33 UTC, ExcessiveUseOfCobblestone commented
good pr

2019-02-07 20:37 UTC, ExcessiveUseOfCobblestone approved these changes

2019-02-07 23:19 UTC, Cyberboss approved these changes

2019-02-08 16:56 UTC, ExcessiveUseOfCobblestone commented
should have claimed it was causing lag so I could early merge tbh lol

2019-02-08 17:42 UTC, VileBeggar commented
i'm a good man i never lie

2019-02-08 21:32 UTC, merged