Pr to test draft prs again.
tgstation/tgstation pull request #42794
Opened 2019-02-15 19:09 UTC by MrStonedOne

Somebody without write/commit/labels access please attempt to set this as ready for review

@Sabiram

2019-02-15 19:24 UTC, Tlaltecuhtli approved these changes

2019-02-15 20:16 UTC, MrDoomBringer requested changes

2019-02-15 20:16 UTC, MrDoomBringer commented on config/admins.txt
> -MrStonedOne = Lazy Master
bad change

2019-02-15 20:17 UTC, Ziiro commented
Neat, the icon is different now
![chrome_2019-02-15_13-16-55](https://user-images.githubusercontent.com/26494679/52882156-0a208d80-3124-11e9-849b-03f3f329d14c.png)

2019-02-15 20:43 UTC, sabiram commented
@MrStonedOne Can't do it

2019-02-16 00:33 UTC, ExcessiveUseOfCobblestone commented
I can't undraft the PR how boring

2019-02-16 02:05 UTC, closed without merging