Correctly patches out the debrain test for changelings
tgstation/tgstation pull request #42811
Opened 2019-02-17 01:18 UTC by kevinz000

Was supposed to be removed a long time ago, determined to be a bug exploit.
this makes all of the usual brain transfer stuff happen but not actually transfer the player into the brain afterwards.

2019-02-17 03:01 UTC, ATH1909 commented
Wait, what was the bug that this fixes?

2019-02-17 04:49 UTC, wesoda25 commented
> Wait, what was the bug that this fixes?

You could meta if someone was a ling by using their brain on an MMI shell, you'd get some sort of message indicating its not possible, which was because lings brains don't actually matter.

2019-02-17 10:02 UTC, HomocidlePancakes commented
It's very simple to work around this. Debraining doesn't actually kill the ling, so you can dose him on BZ and he won't be able to use fake death. All though this is alot more IC then the MMI test.

2019-02-19 04:47 UTC, Cyberboss requested changes

2019-02-19 04:47 UTC, Cyberboss commented on code/modules/mob/living/brain/brain_item.dm
> +	if(!decoy_override && L.mind && L.mind.current)
```suggestion
	if(!decoy_override && L.mind?.current)
```

2019-02-21 19:45 UTC, ExcessiveUseOfCobblestone commented
> exploit
>> not using S tag

🤔

2019-02-25 02:02 UTC, closed without merging