uplink items rebalance
tgstation/tgstation pull request #42883
Opened 2019-02-23 21:32 UTC by Tlaltecuhtli

:cl:
balance: rebalanced the price of some almost never used traitor items 
balance: the power sink costs 10 tc
/:cl:
**syndicate dart pistol 3 -> 2:** its pretty crappy and at the same price you can buy a trowing weapon kit which is way stronger
**power beacon 14 -> 10:** it requires already that you need either to get in cargo and spend 10k on singulo or tesla parts steathly or you to actually tesla/singulo the supermatter which is already hard on its own
**power sink 6 -> 10:** putting a sink + buying a syndi bomb and blow up brig/medical is a garanteed shuttle call 90% of the times with no effort, at least now you cant buy both
**c4 bag 9 -> 8:** you get 1 free c4 and a "i m valid " bag, doesnt seem that much of a bundle
**syndicate thome 9 -> 5:** literally trash item that just give you the power of heal others???? why would someone spend 9 tc for something white medkits do for free?
**slipapocalypse 6 -> 3:** with the soap not stunning anymore i dont see why keep this at this really high price 
**power fist 8 -> 6:** its a downgraded esword at least now it costs less than it
**pizza bomb 6 -> 5:** its a meme item and now you can buy 4 instead of 3

2019-02-23 22:30 UTC, py01 commented
Some of the syndicate bundles contain these items. If these items were misvalued, the bundles may also need to be readjusted.

2019-02-23 22:43 UTC, deathride58 commented
The duffelbag that comes with C4 and various other syndie bundles is primarily useful because it gives you all of the storage space of a duffelbag with literally none of the slowdown and none of the waiting required for a BoH. And let's face it, if you're buying a C4 bag in the first place, then chances are you probably aren't planning on being stealthy in any way, shape, or form. If statbus were a little more robust, then it'd be easy to see that most folks who buy a C4 bag also buy a syndie space suit and various other items that scream "valid me". The rest of this PR is pretty good, though

2019-02-23 23:49 UTC, WJohn commented
you could remove the dart pistol, syndicate tome, slipocalypse, power fist, and pizza bomb and no one would notice or really care. they're kind of just downgrade bloat.

2019-02-23 23:59 UTC, wesoda25 commented
Everything here is good but power fist is like a 3 hit kill on the right setting, with a high chance of stun. Its price should stay as is IMO

2019-02-24 03:31 UTC, OverlyGeneric commented
> Everything here is good but power fist is like a 3 hit kill on the right setting, with a high chance of stun. Its price should stay as is IMO

Perhaps, powerfist should come with some syndicate-grade oxygen tanks that carry more gas than other ones. I don't know if powerfists also release gas because it would be hilarious if you put plasma and it ignites.

2019-02-24 03:39 UTC, Eaglendia commented
C4 bag is fine. You could make powerfist come in a box with an extended capacity air tank and it'd probably be fine. Other changes are :+1: imo, though I'd probably hold off on changing the power beacon since there are stations in rotation with different engines and #42884 is a thing.

2019-02-24 04:00 UTC, OverlyGeneric commented
> C4 bag is fine. You could make powerfist come in a box with an extended capacity air tank and it'd probably be fine. Other changes are 👍 imo, though I'd probably hold off on changing the power beacon since there are stations in rotation with different engines and #42884 is a thing.

That's probably going end up being emaggable-only because of what #42730 was trying to prevent "_consequence-free griefing_."

2019-02-24 04:01 UTC, necromanceranne commented
Power fist is fucking disgusting, but underutilized because esword brings more versatile power in block, armor piercing and consistent damage in an easily concealed form. But as wesoda already said the max setting, while it will drain a tank fairly fast, will deck you into crit in about two hits without armor and will still fuck you up with it. For straight up killing someone quickly it is very decent. At 6 TC you can by it and an ebow some other useful utility item. A lot of powerful gear is in the 2 tc range. Like the EMP flashlight, which you can't get with esword+ebow.

Not saying this is good or bad, just something to be mindful about.

2019-02-24 04:03 UTC, OverlyGeneric commented
>At 6 TC you can by it and an ebow some other useful utility item. A lot of powerful gear is in the 2 tc range. Like the EMP flashlight, which you can't get with esword+ebow.
> 
> Not saying this is good or bad, just something to be mindful about.

Again, keep the original price but give it some form of air tank along with it be a syndicate-variant or just the rare extended oxygen tanks from **Monsters Inc.**

2019-02-24 05:51 UTC, anconfuzedrock commented
lmao powerfist is basically a melee revolver 8tc is perfect it's a more blunt offense than the esword at the cost of less utility and requiring complex refill if you wanna punch more than a few people

2019-02-24 06:23 UTC, necromanceranne commented
Now that I'm thinking on this more I'm even less of a fan on power fist being 6 TC. There has been an upswing in the use of emp flashlight and ebow and for the most part people used edaggers in place of the esword since it didn't matter how long you took at that point, you'd kill them all the same since they can't scream for help. Unless they're hopping antistun strong enough to break the ebow stun, they'll die all the same. With the power fist they haven't even that benefit before they're in crit.

2019-02-25 08:20 UTC, Tlaltecuhtli commented
i dont think the power fist is a problem as i consider the trowing away your opponents a drawback as you want to keep them still to 2 tap em instead of chasing corpses while other ppl are around

2019-02-25 15:53 UTC, necromanceranne commented
That's why you buy a ebow.

2019-02-25 16:15 UTC, anconfuzedrock commented
Also this makes pizza bombs cheaper than minibombs which is fucktarded

2019-02-25 17:25 UTC, ExcessiveUseOfCobblestone commented
why? One requires you to self-detonate and the other can be primed and thrown at will.

2019-02-25 20:01 UTC, anconfuzedrock commented
Silly cobby, you can set the pizza bomb timer to various numbers, including setting it to 5 seconds to open it and toss just like a quieter minibomb

2019-02-25 20:35 UTC, ExcessiveUseOfCobblestone commented
cringe

2019-02-25 20:36 UTC, ExcessiveUseOfCobblestone requested changes

2019-02-25 20:36 UTC, ExcessiveUseOfCobblestone commented on code/modules/uplink/uplink_items.dm
> +	cost = 5
revert due to above

2019-02-25 20:38 UTC, necromanceranne commented
You can also stack the boxes so they're very economic on bag space.

2019-02-26 06:38 UTC, ShizCalev commented
@anconfuzedrock so you're saying to add a special explosion sound just for pizza bombs, right

2019-02-26 14:16 UTC, anconfuzedrock commented
No, I’m saying to make minibombs 1tc

2019-02-27 20:53 UTC, merged