Changes electropacks to be a child of /signaler/
tgstation/tgstation pull request #42973
Opened 2019-03-01 22:00 UTC by UndeadNappist

This is mostly to make a point about the hierarchy system and copy-pasted code, along with some mild optimization I was playing with.

This is derived from how the codebase is disorganized.

2019-03-01 22:07 UTC, PKPenguin321 commented
I think this will make it attachable to shit like flashes if you screwdriver it which will probably be really weird

2019-03-01 22:13 UTC, UndeadNappist commented
It does. It doesn't do anything, and makes a defunct assembly that does nothing, although in the future if someone wanted to they could merge the helmet construction to use the same procs.

It could also open up the door for having timer or proximity based electropacks instead of having it be a separate device. Or you could make the electropack an empty box that contains a signaler and an igniter and some wires, etc.

It doesn't really matter.

2019-03-02 02:04 UTC, JJRcop commented
![screenshot_20190301_210408](https://user-images.githubusercontent.com/5211576/53675563-8e672a80-3c65-11e9-93a8-ea05e5489dba.png)

2019-03-02 02:05 UTC, JJRcop commented
![screenshot_20190301_210504](https://user-images.githubusercontent.com/5211576/53675572-b35b9d80-3c65-11e9-80ca-ddd935b98ddd.png)

2019-03-02 18:28 UTC, Tlaltecuhtli commented
was this tested

2019-03-02 20:14 UTC, optimumtact commented
your point is lost in the fact you can't even use git properly

2019-03-02 20:30 UTC, UndeadNappist commented
> was this tested

Works on another server where this change has already been implemented.

>your point is lost in the fact you can't even use git properly

and you add pointless nagware logs when there's already too many of them, what's your point?

2019-03-03 01:11 UTC, JJRcop commented
BadDeathclaw/TG-Claw#614 for reference

2019-03-12 17:44 UTC, ExcessiveUseOfCobblestone requested changes

2019-03-12 17:44 UTC, ExcessiveUseOfCobblestone commented on code/modules/assembly/electropack.dm
>  	var/shock_cooldown = 0
new variables go at the bottom

2019-03-12 17:44 UTC, ExcessiveUseOfCobblestone commented on code/modules/assembly/shock_kit.dm
> +	var/obj/item/assembly/signaler/electropack/part2 = null
remove both `= null`s here

2019-03-12 17:44 UTC, ExcessiveUseOfCobblestone commented on code/modules/assembly/shock_kit.dm
> +	var/obj/item/assembly/signaler/electropack/part2 = null
also new vars go at the bottom

2019-03-12 20:09 UTC, PKPenguin321 commented
Also im pretty sure you wouldn't be able to equip assembly-fied electropacks which kind of defeats the point

2019-03-17 10:21 UTC, closed without merging