Adds two shuttle states more functionality
tgstation/tgstation pull request #43005
Opened 2019-03-04 13:13 UTC by spookydonut

## About The Pull Request

Adds two states, post-landing recharging and pre-arrival landing.

## Why It's Good For The Game

Allows shuttles to be restricted from leaving immediately after landing.  Allows the ability to play a landing sound effect before the shuttle lands within the shuttle timer system without having to use an external callback timer.
With minimal work shuttles could also be prevented from a change of destination while in the process of landing.

## Changelog
:cl:
add: Adds the ability to give shuttles a cooldown timer
/:cl:

2019-03-07 09:56 UTC, AnturK commented
Pirate shuttle already implements something similar but isn't generic, please remove it and replace with checking the state.

2019-03-08 08:22 UTC, ShizCalev requested changes
what AnturK said, please

2019-03-08 10:56 UTC, spookydonut commented
@AnturK @ShizCalev i dont play tg or know the codebase, can you give me a file/line reference to what you're talking about?

2019-03-08 10:59 UTC, AnturK commented
https://github.com/tgstation/tgstation/blob/b561f5eeba0411735d23bb8d1ac59d272059134a/code/modules/events/pirates.dm#L198-L221

2019-03-08 15:55 UTC, ninjanomnom approved these changes

2019-03-08 15:56 UTC, merged