Fixes gondolapods and adds more examine text
tgstation/tgstation pull request #43044
Opened 2019-03-07 01:55 UTC by MrDoomBringer

## About The Pull Request
Fixes Gondolapods, also lets people see if the gondolapod has made a delivery yet

## Why It's Good For The Game
Gondolapods are great

## Changelog
:cl: MrDoomBringer
fix: Gondolapods work again
/:cl:

2019-03-07 05:00 UTC, SpaceManiac commented
does this fix #43033?

2019-03-07 19:54 UTC, DaxDupont commented
Speed merge game breaking bug for Adminbus

2019-03-08 09:30 UTC, ShizCalev requested changes

2019-03-08 09:30 UTC, ShizCalev commented on code/modules/cargo/gondolapod.dm
> +		to_chat(user, "<span class='notice'>It looks like it hasn't made its delivery yet.</b>.<span>")
extra period

2019-03-08 09:30 UTC, ShizCalev commented on code/modules/cargo/gondolapod.dm
> +		to_chat(user, "<span class='notice'>It looks like it has already made its delivery.</b>.<span>")
extra period

2019-03-08 09:30 UTC, ShizCalev commented on code/modules/cargo/supplypod.dm
> +		//pixel_y = 0
remove, don't comment out.

2019-03-08 17:40 UTC, MrDoomBringer commented on code/modules/cargo/supplypod.dm
> +		//pixel_y = 0
oops did this during testing

2019-03-17 10:43 UTC, AnturK commented
Fix the typos please.

2019-03-17 18:12 UTC, MrDoomBringer commented
fuk

2019-03-17 18:15 UTC, MrDoomBringer commented
@AnturK should be good

2019-03-19 16:14 UTC, merged