ai uploads now have a gps signal
tgstation/tgstation pull request #43066
Opened 2019-03-08 18:03 UTC by Tlaltecuhtli

:cl:
balance: ai uploads now have a gps signal which will be active until its monitor gets decostructed
/:cl:

maintuploads are a pain in the ass to deal for all the parties involved as you ll have x and y uploading laws every second to counter the other while the ai switches from asimov and rogue back and forward and suicides

2019-03-08 18:04 UTC, HomocidlePancakes commented
Holy shit. PR of the year right here.

2019-03-08 18:10 UTC, anconfuzedrock commented
MWAHAHA MORE GPS SIGNALS FIRST THE UPLOAD NEXT YO MOMMA’S HOUSEZ

2019-03-08 18:14 UTC, HomocidlePancakes commented
Do AI boards have a GPS signal or consoles?

2019-03-08 18:21 UTC, Tlaltecuhtli commented
read the OP

2019-03-08 18:26 UTC, ondrej008 commented
@Tlaltecuhtli can the AI get the GPS signal? I know only that Mining module cyborgs can use a GPS, so this would probably only help the crew.

2019-03-08 19:12 UTC, ExcessiveUseOfCobblestone commented
It'll always be on the same Z level so you could just display a message to the AI stating the coords.

That feels a lot safer than a miner/literally anyone looking at the GPS and noticing this signal popping up and instantly calling it out.

2019-03-08 19:16 UTC, zxaber commented
I still say that carded AIs shouldn't be eligible for law changes. But this is a good alternative fix.

2019-03-08 19:28 UTC, Ratvar commented
Can you add this behavior to comms console as well?

2019-03-08 19:59 UTC, JMoldy commented
Merge this yesterday.

2019-03-08 20:13 UTC, ExcessiveUseOfCobblestone requested changes
default the GPS to `tracking = FALSE`, only activating once it's actually been used (see hit by law board).

I would also prefer the default computer to not have this.

2019-03-08 22:17 UTC, Dorsisdwarf commented
Wait, its only active when the monitor is connected? cant you just screwdriver -> upload law -> screwdriver

2019-03-08 22:21 UTC, zxaber commented
That's why the decon takes longer now, presumably.

Far as I can tell, this isn't a nerf to tators subverting the AI, it's meant to be a way to stop law spammers who are doing nothing but making the AI's life miserable.

2019-03-09 06:03 UTC, Tlaltecuhtli commented
@ExcessiveUseOfCobblestone what do you mean
@Ratvar comms console already have the message thing printed on all consoles
@ExcessiveUseOfCobblestone ai being aware of uploads may cause them to premtively suicide because law 1

2019-03-09 12:14 UTC, carshalash commented
Oh thank god.

2019-03-10 21:50 UTC, AnonymousTGplayer commented
I fail to see the initial issue as I feel this PR oozes plenty of salt. Sure, maintenance uploads are a pain to deal with, but that's kind of the point of them. I feel this PR punishes traitors (specifically non-science/engineering traitors)/ops with hacked AI boards rather than players who law spam for fun.

> Far as I can tell, this isn't a nerf to tators subverting the AI, it's meant to be a way to stop law spammers who are doing nothing but making the AI's life miserable.
Spamming (law/chat or otherwise) is precedent enough to violate rule 1 (and getting bwoinked if the admins have had enough regardless if you're traitor or not) and law spam usually result in admins (especially if you ahelp regarding just this) deciding that the AI gets a free malf due to "software bugs".
I feel a cooldown on the boards or upload would be better fix to deal with spammers than adding a magic GPS signal to every upload.

2019-03-11 08:17 UTC, zxaber commented
Admins aren't always available to grant malf or handle the upload spam. A cooldown would prevent legitimate back-to-back uploads (such as a set of custom laws), though a built-up cooldown or temporary "burnout" of the board similar to flashes might not be a bad idea.

Really, though, this isn't going to hurt tators unless people already know they’re gonna upload a law. No one will be watching for upload locations normally, and there's no alert the AI gets an upload. Under normal circumstances, by the time anyone realizes the upload happened, the traitor will likely not be near the location where they uploaded anymore.

2019-03-11 12:06 UTC, Cyprex commented
>comms console already have the message thing printed on all consoles
Yes, but that only prints the area name, and unreliably, and there are some ways around that. Comms consoles should also have this behaviour, the only issue I can see is GPS spam, which could be mitigated by adding them into a seperate tab on the GPS.

2019-03-11 13:55 UTC, SouDescolado commented
Btw, you used it all correctly, but you named it time to scewdrive, when I think you meant screwdrive.

2019-03-11 14:25 UTC, ExcessiveUseOfCobblestone commented
I don't want there to be any indication a non-default (mapload) upload exists UNLESS it has already been used to upload a law.

I don't really want there to be a signal for the default upload either, it's useless.

2019-03-11 17:19 UTC, MacHac commented
If miners have their GPSes up, and they usually do while hunting goodies, they'll see the signal pop up on the station for a moment.  Even if they don't know where the console is, they can yell about it over comms, and the AI core is now being raided by all of security + every bored validhunter on the station.

Alternate suggestion: When the AI's laws are changed, it gets a message saying where the change came from.  The location of the most recent change also appears in the carded AI's interface.  

If the AI's being one-off subverted, its laws almost certainly forbid it from revealing the location; If the AI's being lawspammed, anyone that cards it will be able to find the console without the console user realizing.

2019-03-11 17:23 UTC, Cyprex commented
Having a signal on the default upload would help players realize this change.

2019-03-11 18:50 UTC, ExcessiveUseOfCobblestone commented
We have a changelog if players want to stay in the know, we don't need a useless entry autoupdating.

> If miners have their GPSes up, and they usually do while hunting goodies, they'll see the signal pop up on the station for a moment. Even if they don't know where the console is, they can yell about it over comms, and the AI core is now being raided by all of security + every bored validhunter on the station.
> 
> Alternate suggestion: When the AI's laws are changed, it gets a message saying where the change came from. The location of the most recent change also appears in the carded AI's interface.
> 
> If the AI's being one-off subverted, its laws almost certainly forbid it from revealing the location; If the AI's being lawspammed, anyone that cards it will be able to find the console without the console user realizing.

Yes I'm afraid of that as well, but i'm not sure how to fix "I want to be able to know exactly where a console is so I can sucker punch it... but not too much"

2019-03-14 06:15 UTC, Tlaltecuhtli commented
@ExcessiveUseOfCobblestone having the tracking turn on only when laws is uploaded and then turn off is worse tho i think its better as currently is

2019-03-14 15:32 UTC, 4dplanner commented
You can just leave the console almost constructed anyway

2019-03-14 15:36 UTC, ExcessiveUseOfCobblestone commented
> @ExcessiveUseOfCobblestone having the tracking turn on only when laws is uploaded and then turn off is worse tho i think its better as currently is

It's not meant to turn off after use, it's meant to START off and turn on indefinitely after use. Like I said if you're worried about deconstruction/reconstruction put it on the circuitboard instead.

2019-03-15 01:30 UTC, zxaber commented
Would it be better if, instead of emitting a GPS signal, all AI uploads simply listed the coordinates where the most recent law change happened, regardless if the console it actually still there? It would solve the worry that random miners or whoever could call out traitors, but would mean that someone deconning the maint upload console could still be found.

2019-03-15 14:43 UTC, ExcessiveUseOfCobblestone commented
It doesn't use a UI unless you want it to "say" it in which case it would be useless unless you stood by one.

Putting the GPS on the circuitboard would fix the issue of deconning to bypass the mechanic.

2019-03-15 16:30 UTC, zxaber commented
Maybe, but is the point of this to dissuade against maintenance law spam, or give a counter to proper traitors subverting the AI? I was under the impression that we were trying to not touch normal traitors, but having a GPS link to their pocket once the subverting is done is a pretty big nerf to the subversion mechanic. At the very least, even if they drop off the board somewhere, it's an unintuitive way for their work to be found out if someone just happens to glance at a GPS.

I thought we were limiting this to be seen only from other AI uploads. Having GPS pinpointer that anyone might notice is pretty terrible, and having it be permanently on the board would be even worse.

2019-03-15 16:54 UTC, ExcessiveUseOfCobblestone commented
> Above Post

You can't exactly differentiate the two is the main issue. As I said:

>i'm not sure how to fix "I want to be able to know exactly where a console is so I can sucker punch it... but not too much"

If the only metric for this PR is that it stops spam at the cost of previous gameplay interactions then it may as well be closed, we have admins for those abusing mechanics.

2019-03-15 22:37 UTC, zxaber commented
Punishing it by making it so easy to powergame against seems not great.

2019-03-18 14:46 UTC, ExcessiveUseOfCobblestone commented
> Punishing it by making it so easy to powergame against seems not great.

Right hm....

I think I should go back to my original suggestion of printing the coords to the AI.

2019-03-19 16:19 UTC, ShizCalev commented on code/game/machinery/computer/law.dm
> +	var/obj/item/gps/internal
mind renaming this to internal_gps?

2019-03-22 04:00 UTC, merged