Fixes wormhole projectors and gravity manipulators for pacifists
tgstation/tgstation pull request #43096
Opened 2019-03-11 14:05 UTC by ShizCalev

Fixes #43054

:cl: ShizCalev
fix: Pacifists can now use wormhole projectors and gravity manipulators.
/:cl:

2019-03-11 14:07 UTC, SouDescolado commented
I'm not sure about areas and turfs, but could it blacklist turfs because it could be dangerous? Like space or something? Otherwise I think this will be the go to weapon for Pacifist Traitors (I think @imsxz made a PR that got merged which allows this)

2019-03-11 14:13 UTC, HomocidlePancakes commented
It's super easy to harm someone with a gravity manipulator. You shouldn't allow pacifists to use  it

2019-03-11 17:24 UTC, Ratvar commented
Same way it's easy to harm someone using wormhole projectors. They can't shoot syringe guns, why let them shoot those?

2019-03-11 17:32 UTC, Cyprex commented
A lot of things can be abused as a pacifist, with the variety of things you can do in this game there will always be loopholes. Restricting half the game from pacifists doesn't seem like the right way.

2019-03-11 17:34 UTC, Ratvar commented
If you don't want to be a pacifist, don't be. Or use some more (then a gun) creative damage dealer. Wormhole projectors and gravity manipulators (and guns) are in no way "half of the game".

2019-03-11 17:37 UTC, SouDescolado commented
> Or use some more (then a gun) creative damage dealer.

Or do no damage. You are a pacifist after all.

2019-03-11 17:41 UTC, Ratvar commented
Sadly, that wouldn't be feasable because you can't code all that forbidding shit. Can forbid guns tho.

2019-03-11 17:44 UTC, dr-bee commented
Wormhole projectors makes sense, but the gravity gun is a literal weapon. it does damage by throwing shit at the target.

2019-03-11 19:06 UTC, ExcessiveUseOfCobblestone commented
wormhole has nonantag uses, gravity is just a mislabeled griefgun

2019-03-11 21:31 UTC, Ratvar commented
Syringe gun can be used for healing people, so? They are still killing weapons and will be used for killing by pacifists without a second thought

2019-03-11 22:17 UTC, GuyonBroadway commented
Literally what is the point of the gravity gun?

Maybe if you could move normally unmoveable shit around with it, it's be neato, I know atmos techs would sick a dick or two to have a gun that lets you move heaters/freezers without needing to deconstruct the dang things.

2019-03-13 06:39 UTC, imsxz commented
grav gun is for killing humanoid antags that dare show up that long into a round (generally a free short stun on everyone in the massive AOE) and or running around shooting it for epic grief

I used a grav gun to dislodge an item that I couldn’t reach but otherwise I’d be impressed if someone managed to make use of one without hurting someone in the process. Probably a really bad idea for pacifists.

While wormhole guns do have some creative uses to kill people as pacifist, its primary purpose is harmless and very nice to have for whatever a science powergamer may have in mind I don’t really need to go into detail

2019-03-13 12:09 UTC, ExcessiveUseOfCobblestone commented on code/modules/mob/living/simple_animal/hostile/jungle/mega_arachnid.dm
>  	name = "flesh snare"
lewd

2019-03-14 14:01 UTC, ninjanomnom requested changes

2019-03-14 14:01 UTC, ninjanomnom commented on code/modules/projectiles/ammunition/energy/portal.dm
> +	var/obj/item/gun/energy/wormhole_projector/gun = null
```suggestion
	var/obj/item/gun/energy/wormhole_projector/gun
```

2019-03-14 19:28 UTC, merged