Research Printing Cost Balances
tgstation/tgstation pull request #43189
Opened 2019-03-19 09:48 UTC by Pandolphina

## About The Pull Request

Makes the KA upgrades and the sonic jackhammer more expensive, except for the AOE one to encourage miners to actually mine. The holographic projector now takes gold to make. The forensic scanner now only takes 1 sheet of gold to make. The inducer takes silver to prevent "barricade science and keep making inducers". And the "free entry into the bridge, armory and everywhere that isn't completely window-less" costs 2 full sheets now.

## Why It's Good For The Game

Mining now has to work _slightly_ more before they can take their damage upgrades and run off to die to megafauna. Also, the **wall destroyer supreme** is slightly more expensive, meaning science can't rush the armory quite as fast. Holographic projectors can kek any people if you're in maint and inducers should generally be slightly more expensive. The forensic scanner is barely used anyway so now the HoS can detective slightly better on the rare occasion that they do. Also portal gun rush armory bad.

## Changelog
:cl: Pandolphina
balance: KA Range, Damage and Cooldown upgrades and the sonic jackhammer cost more. AOE upgrade costs slightly less.
balance: The holographic projector costs more, along with the inducer and the portal gun.
balance: The forensic scanner is slightly cheaper.
/:cl:

2019-03-19 09:57 UTC, Tlaltecuhtli commented
like minerals mean anything afther 2nd deliver

2019-03-19 10:15 UTC, drderp3635 commented
Nobody is going to use aoe, because aoe sucks ass regardless of material cost

2019-03-19 10:16 UTC, HomocidlePancakes commented
>Makes the KA upgrades more expensive, except for the AOE one to encourage miners to actually mine

Miners use cutters to mine. AOE upgrades are only ever used by free golems (if the didn't get a mech by that point).

2019-03-19 11:16 UTC, Tlaltecuhtli commented
also who the fuck nerfs the janitor projector??????

2019-03-19 11:39 UTC, Pandolphina commented
> also who the fuck nerfs the janitor projector??????

I didn't, the jani one is a sub-type with its own cost.

2019-03-19 12:32 UTC, AzureWildfire commented
I don't know if i like this change, but anyways did you change robotics recipe of KA upgrades also? because robotics recipes are more expensive than the cargo-lathe ones (currently).

2019-03-19 12:43 UTC, Nickkoranda commented
Forcefield projectors could use a gold requirement as well. They're very powerful for only costing metal and glass.

2019-03-19 13:19 UTC, knacker48 commented
Whats the point of making the holo projector more expensive when people almost never use it anyway?

2019-03-19 13:54 UTC, Pandolphina commented
> Whats the point of making the holo projector more expensive when people almost never use it anyway?

I dunno, I've seen it used quite a lot as a makeshift "Forcewall" spell by scientists.

2019-03-19 15:19 UTC, ExcessiveUseOfCobblestone commented
Every mineral cost in this game feels arbitrary, I can't wait until I stop playing the sloth and base those costs around defines.

2019-03-19 16:10 UTC, Barhandar commented
The only valid mining change in here is jackhammer; all of them say that you've never actually played the miner because _plasmacutter is for mining_, KA upgrades are entirely for fighting, and it costing more won't actually affect them fucking off to die.

2019-03-19 17:16 UTC, Pandolphina commented
> The only valid mining change in here is jackhammer; all of them say that you've never actually played the miner because plasmacutter is for mining, KA upgrades are entirely for fighting, and it costing more won't actually affect miners fucking off to die.

I have. The reason it’s _being_ nerfed is that it may slightly encourage its use. The AOE is never actually used so it may as well be removed, but I’d prefer to keep it, simply cheaper.

2019-03-19 18:00 UTC, knacker48 commented
The only things I agree with here are uping the sonic jackhammer and reducing the AOE upgrade for KA's. The other changes feel arbitrary to me and I don't fully agree with the reasoning. Also I'm indifferent about the forensic scanner cause forget making them, I can't even remember the last time I saw someone even use one.

2019-03-19 21:17 UTC, zxaber commented
The AoE is used for mining borgs quite often, as they do not have access to cutters.

2019-03-19 21:52 UTC, AzureWildfire commented
Yeah the AoE is used by golems and mineborgs, but I still don't see the point of making Ka upgrades more expensive, I don't feel there is a good reason behind it, because it won't change how much a miner will mine, if miner isn't going to mine for the crew and just go for megafauna it will just go for enough minerals for the upgrades.

2019-03-19 22:18 UTC, zxaber commented
It's also worth noting that the miner upgrades are available from the vendors too. Way back when I used to play miner, that's how I upgraded my Pka.

Granted, that was before the silo was a thing. I guess now it's easier to just print from the protolathe.

I dunno how I feel about the higher inducer cost. If someone is on top of things, they can trivialize power sinks, but power sinks can legit lead to shuttle calls if no one finds the sink and using inducers to fix the power issue becomes a full-time job for whoever is doing it.

2019-03-20 14:59 UTC, ExcessiveUseOfCobblestone commented
The miner changes don't make sense since the Plassy cutters haven't been converted into a KA upgrade (yet).

2019-03-21 15:52 UTC, ExcessiveUseOfCobblestone requested changes
I'm down for the sonic and holographic changes but I'm not really sold on the others.

2019-03-25 15:25 UTC, closed without merging