[S] Adds incap check to canusetopic
tgstation/tgstation pull request #43302
Opened 2019-03-23 21:25 UTC by 4dplanner

## About The Pull Request

For some reason this was checked for living/canusetopic, but not for human/canusetopic. Tell me if this is deliberate, just looks like an oversight

## Why It's Good For The Game
fixes #43295

## Changelog
:cl:
fix: Humans can no longer use UIs while incapacitated
/:cl:

2019-03-23 23:13 UTC, SpaceManiac submitted a review, later dismissed

2019-03-24 00:28 UTC, ShizCalev commented
we've come full circle, lmao
https://github.com/tgstation/tgstation/commit/3e7184c9756aa0ccc4fa224ffc05171d4ea2dfc3#diff-1ff8328c73a4a8a73ad2c1fe6d517588R724

2019-03-24 00:31 UTC, ShizCalev commented
tbh, should probably just move the MOBILITY_UI flag under here; https://github.com/tgstation/tgstation/blob/65a67058694149c4b3dd604f5054275cd6f08c9e/code/modules/mob/living/living.dm#L1108-L1111

2019-03-24 00:34 UTC, ShizCalev requested changes
This is just a band-aid that doesn't really fix #43295, since dead/unconscious/ect mobs will still get the `MOBILITY_PULL` flag added to them. `update_mobility()` has to be corrected instead.

Likewise, `canUseTopic()` isn't the only thing that checks if `MOBILITY_UI` exists.

2019-03-24 01:14 UTC, 4dplanner commented
You're right, I've fixed it properly.

2019-03-24 03:50 UTC, ShizCalev commented on code/modules/mob/living/living.dm
> +	if(should_be_lying || restrained || incapacitated())
```
	if(buckled)
		if(buckled.buckle_lying != -1)
			should_be_lying = buckled.buckle_lying
			(beds = 90)
```
```
	if(should_be_lying || restrained || incapacitated())
 		mobility_flags &= ~(MOBILITY_UI|MOBILITY_PULL)
```

aka
if buckled to bed, canUseTopic = TRUE

2019-03-24 03:52 UTC, ShizCalev approved these changes

2019-03-24 03:54 UTC, ShizCalev commented
testmerged on bagil and sybil

2019-03-24 07:04 UTC, checkraisefold commented
speedmerge now

2019-03-25 21:38 UTC, merged