Adds a new minor gas reaction.
tgstation/tgstation pull request #43362
Opened 2019-03-27 18:24 UTC by as334

## About The Pull Request

Adds a new small reaction for some of the endgame gases. You can combine hot Stimulum and Pluoxium(with some nitryl to catalyze and plasma as fuel), and it will release a high power radioactive energy ball like the ones released by fusion. The angle of the shot is also dependent on the concentrations of water vapor and nitryl within the reaction, so you can modify those amounts to aim which way the ball is shot for those elaborate atmos snipes. Also significantly lowers the heat requirements of Nitryl, as it was way too high and now there's more motivation to obtain it.

Deletes the fusion test canisters that I forgot to take out of the code earlier.

## Why It's Good For The Game

Atmos is still lacking in reactions that produce meaningful effects in the world, this is an example of a fun, small one that's pretty versatile and adds slightly more incentive to acquiring late game gases. The reaction itself is very flexible, and allows a couple cool possibilities. 
Possible things you can try with this:
- Atmosia Gatling Gun
- Using it with a TTV for a portable weapon
- Have it going in distro to have random energy blasts shoot around the station

## Changelog
:cl:
add: New Gas Reaction, Stimulum Energy Balls. Combine 100 degree Pluoxium, Stimulum and small amounts of Plasma and Nitryl to shoot off a deadly radioactive energy ball.
add: The reaction will consume the plasma, pluoxium and stimulum and release small amounts of heat. The presence of water vapor will change the direction in which it shoots. See if you can figure out how to aim it.
tweak: Nitryl now forms at 22,000 degrees, a significantly lower temperature.
fix: fixed a few things
del: Removed some old left-behind fusion test canisters.
/:cl:

2019-03-27 20:24 UTC, blueybloke commented
+rep, would be nice to be able to have more things to do with late game gases.

2019-03-28 04:24 UTC, plapatin commented
atmos techs are getting an awful amount of love lately aren't they

2019-03-28 04:44 UTC, as334 commented
Every job deserves more love, I'm just trying to do my part.

2019-03-28 13:36 UTC, SouDescolado commented
> Every job deserves more love, I'm just trying to do my part.

Even Assistants?

2019-03-28 13:40 UTC, duncathan commented
this is fun :+1:

2019-04-02 19:09 UTC, AnturK requested changes
Looks fine outside of this, if bit abusable.

2019-04-02 19:09 UTC, AnturK commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +			air.temperature = (air.temperature*old_heat_capacity + energy_released)/new_heat_capacity
Needs a clamp

2019-04-18 20:36 UTC, as334 commented
Sorry this took so long to update, I switched to a new computer recently and it took me a while to get around to getting my code stuff set up.

2019-05-02 00:00 UTC, merged