Adds an admin spawnable Stunbaton variant, the SCAM boomerang.
tgstation/tgstation pull request #43477
Opened 2019-04-03 06:48 UTC by ArcaneMusic

## About The Pull Request

This started out as a meme April Fools PR to fuck with stunbatons, and then ATH convinced me to make it a real thing, and then I spent the last 2 days fucking with Git and downloading the source code over about 9 fucking times, now it's here.

Functionally acts as love child between bananium shields and the default stunbaton, complete with a default shitty battery to serve as a one-off ranged stun before needing a charge unless it's upgraded with a less shit battery.  Inherits all the flaws of the default stun baton, and requires manually catching them upon throw to make them more challenging and reflex based to balance the potential of having a spammable ranged stun.

(SCAM stands for Security Critical Aeromation Matrices, or, what you'll say when you hit yourself the first time with one.)

## Why It's Good For The Game

They're admin spawnable, so no harm no fowl. They're also a fun variant of the stun baton with the potential drawback of hitting yourself if thrown.

## Changelog
:cl: Arcane
add: Australian Justice can now be dished out.
/:cl:

2019-04-03 08:45 UTC, Tlaltecuhtli commented
make it a premium item from sec vendor, maybe with less cell power to max 1 hit

2019-04-03 09:49 UTC, Borisvanmemes commented
Add it to the sec vendor, it looks REALLY fun, if a tad powerful.

2019-04-03 12:00 UTC, knacker48 commented
How much should it cost?

2019-04-03 13:08 UTC, ATH1909 commented
> Add it to the sec vendor, it looks REALLY fun, if a tad powerful.

This, but make the ones in the sec vendors not come back after you throw them.

Alternatively, maybe make throwing a normal stunbaton while you know krav maga boost the stunbaton's thrown hit chance up to 100% (for that throw), since krav maga is kind of mostly redundant with stunbatons (or the other way around, depending on your point of view) anyway.

I really don't like the 99% chance to hit (instead of a 100% chance to hit). People already get mad about someone's riot shield blocking their attacks three times in a row (a 12.5% chance); I can only see a 1% chance to avoid being stunned by an item that should have hit you infuriating many people and causing a lot of salt.

But yeah, I do support this PR and will likely TC trade for this item+instant summons at some point if it gets merged.

2019-04-03 14:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/stunbaton.dm
> +	. = ..()
purpose?

2019-04-03 14:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/stunbaton.dm
> +	..()
purpose?

2019-04-03 14:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/stunbaton.dm
> +	. = ..()
purpose?

2019-04-03 14:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/stunbaton.dm
> +	. = ..()
duplicate anyways

2019-04-03 14:47 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/stunbaton.dm
> +/obj/item/melee/baton/scam/update_icon()
put further subtypes below the procs that you're editing

2019-04-03 19:25 UTC, Barhandar commented
Stunahawks _completely_ miss the point of boomerang stunbatons (that is, punishment for missing).

2019-04-03 20:59 UTC, ATH1909 commented
> Stunahawks _completely_ miss the point of boomerang stunbatons (that is, punishment for missing).

The punishment for missing is that you've just tossed your intended target a potent stun weapon that they will likely run off with and keep forever and/or use against you.

2019-04-04 18:22 UTC, ATH1909 commented
Somewhat relevant: https://www.youtube.com/watch?v=rZdEZSsIZIs

2019-04-06 20:27 UTC, SpaceManiac requested changes
what Cobby said

2019-04-11 05:41 UTC, ArcaneMusic commented
Hopefully fixed all the style changes and removed the Duplicate Procs.

Gitbash scares me.

2019-04-13 23:01 UTC, Jalleo commented
What happens when it had a bluespace power cell filled with plasma when its used? Does it explode? Please tell me it does.

2019-04-13 23:14 UTC, ArcaneMusic commented
Explodes on contact with the first target hit. This includes upon self-stun.

2019-04-15 03:51 UTC, ArcaneMusic reviewed
Cleaned everything up, removed duplicate and blank methods as well as moved the subtype.

2019-04-16 09:53 UTC, optimumtact commented on code/game/objects/items/stunbaton.dm
> +			sleep(1)
after you sleep you have to check !qdeleted(src)

2019-04-26 16:11 UTC, closed without merging