Adds dueling pistols.
tgstation/tgstation pull request #43489
Opened 2019-04-04 20:05 UTC by AnturK

Why is our gun code so backwards. Anyway, adds dueling pistols for the times when you need something more classy than toolbox to the head for solving disputes. Could use some unique sprites.

2019-04-04 20:07 UTC, WJohn commented
Maybe also add this in the holodeck as well? Could be cool to resolve fights that way without anyone dying, but that's up to you.

2019-04-04 20:10 UTC, AnturK commented
I'd have to map holodeck area and that's above my effort quota for this week.

2019-04-05 00:10 UTC, OverlyGeneric commented
I wouldn't say a bullet would decapitate someone but I would say the brain trauma caused by it would render the person unclonable.

Here are the old-fashioned rules to dueling despite this being _glorified RPS_.

- The person who felt offended or dishonored had to "challenge" his opponent to a duel and this was usually done by throwing his glove down in front of the opponent or by hitting him in the face with a glove. 

- Each person had to then find a person to be his "second" and the job of the seconds was to choose a place to duel and to decide whether or not the weapons were equal.

- The person who declared the duel got to choose when the duel would be finished. Common endings were if one person was injured, grievously injured or hurt, and killed. 

- Duels with pistols could be ended after the first shot, even if no one was hit. Most pistol duels didn't go longer than three shots.

Techno-flintlocks for sprites? 🗿

2019-04-05 00:27 UTC, ATH1909 commented
https://www.youtube.com/watch?v=m7iHmuco_zo

2019-04-05 12:28 UTC, Repukan commented
If a person doesn't want to die they can just not duel.

Kinda stupid to make something thematically lethal non lethal

2019-04-05 20:22 UTC, SgtxRootbeer commented
@Repukan
Because sometimes roleplayers might want something else at stake for the duel.
Eg:
Racist human vs lizard. If the Liz wins, the human has to say on comms that lizards are the Master race, if the human wins, then the lizard has to build a gas chamber for himself.
Assistant vs rd: if the assistant wins, then the Rd will remove the DNA lock on his phazon and give it to the assistant, if the Rd wins, the assistant feeds the slimes in xenobio.

2019-04-05 20:24 UTC, Repukan commented
Sounds stupid

2019-04-05 20:58 UTC, PKPenguin321 commented
Duels are typically the final lethal level of escalation, sgtx. You use them when you want to kill somebody

2019-04-06 15:16 UTC, FantasticFwoosh commented
Even if its non-lethal, nothing says that the captain can't decree you to be executed or punished anyway if either participant loses this duel for their innocence. Least its more resolute than trial by combat which is messy.

2019-04-07 10:41 UTC, ATH1909 commented
Add a function where if you're on help intent and fire your dueling pistol, your character intentionally make your shot miss (or just not count as a hit if it connects with your target? I dunno).

2019-04-09 00:59 UTC, MrDoomBringer requested changes

2019-04-09 00:59 UTC, MrDoomBringer commented on code/modules/projectiles/guns/energy/dueling.dm
> +	desc = "Let's solve this like gentlemen."
```suggestion
	desc = "Let's solve this like gentlespacemen."
```

2019-04-10 14:21 UTC, MrDoomBringer commented
![image](https://user-images.githubusercontent.com/29008542/55886819-6dee9200-5b7a-11e9-8685-c03a09f30106.png)
new sprites by some loser

2019-04-16 02:25 UTC, OverlyGeneric commented
> new sprites by some loser
> color changes based on firing mode

very good. feels like it belongs in a Steampunk setting but fits just as well in a futuristic setting.

2019-04-25 18:44 UTC, ATH1909 commented
> > new sprites by some loser
> > color changes based on firing mode
> 
> very good. feels like it belongs in a Steampunk setting but fits just as well in a futuristic setting.

It reminds me of the laser muskets from the Fallout series.

2019-04-30 15:04 UTC, ExcessiveUseOfCobblestone commented
I want this but don't want to review this :^)

2019-04-30 15:06 UTC, ExcessiveUseOfCobblestone commented
nvm it looks fine, are you going to change the sprite

2019-04-30 15:06 UTC, merged