Ghosts can analyze gas mixes and some new objects can be analyzed
tgstation/tgstation pull request #43502
Opened 2019-04-05 21:27 UTC by willox

## About The Pull Request
This lets ghosts toggle a gas scanner when observing (like the current health scanner toggle.) Just click whatever you want to scan when it is enabled. It will scan turfs, too.

I also ended up enabling analysis of some objects that can't be scanned at the moment:
- Mechs
- Critter closets
- Transmit tube pods
- Open Turfs (but only ghosts can reach that call path)

I was arguing with myself for a while when figuring out how to disconnect analysis from the `analyzer_act` proc and ended up adding a `return_analyzable_air` proc to every atom. If you have a better idea, please tell me. I think it ended up okay, though.

Please critique.

## Why It's Good For The Game
It'll let people observe atmos/engine shenanigans better. Maybe it could also help admins if it's any easier to use than current methods of monitoring pipes.

## Changelog
:cl:
add: Added 'Toggle Gas Scan' verb to allow observers to analyze gas mixtures 
tweak: Mechs, critter closets, and transmit-tube-pods can be analyzed with analyzers
/:cl:

2019-04-05 21:47 UTC, Barhandar commented
Would be nice if ghosts could see what gas(es) the filters and scrubbers are set to too, right now all buttons are identically greyed out or outright inaccessible.

But that's tgui.

2019-04-05 21:52 UTC, Whoneedspacee commented
damn now people are just gonna stalk for bomb mixes gay

2019-04-06 00:28 UTC, Jimmius commented
I've said "i'll kill for ghost gas analyzer vision" so many times. so glad its finally here and everything was worth it

2019-04-06 07:07 UTC, Fox-McCloud commented
>damn now people are just gonna stalk for bomb mixes gay

Yeah. Ghosts viewing everything is kinda meh.

Admin ghosts being able to view everything though? Huge help to administration.

2019-04-08 14:54 UTC, ExcessiveUseOfCobblestone commented
> damn now people are just gonna stalk for bomb mixes gay

start making dummy setups while working from a secret location to own the deadchat lol

2019-04-08 15:14 UTC, Whoneedspacee commented
yes just mix this plasma and oxygen at 373.16 then directly insert it into the tank and woila you have 3 tile devestated yourself

2019-04-08 19:22 UTC, ExcessiveUseOfCobblestone commented
The age of knowledge-gating is coming to an end

2019-04-09 15:49 UTC, ondrej008 commented
@Whoneedspacee Do you mean singlecaps as in those gay ass bombs with only one tank? Those can never be maxcap, because it's literally impossible.

2019-04-09 16:15 UTC, Whoneedspacee commented
no i dont mean that

2019-04-10 12:58 UTC, duncathan requested changes
https://github.com/tgstation/tgstation/blob/f221870b3eee4595dc02f221f53861be1116cfa7/code/modules/admin/verbs/diagnostics.dm
could you update this verb to the new system as well? otherwise I support the deobfuscation of atmos and toxins

2019-04-10 21:07 UTC, duncathan approved these changes

2019-04-16 09:46 UTC, merged

2019-04-22 13:23 UTC, capn-monkeypaw commented
I made an account simply so I could thank you for this. I've been screaming for it in deadchat for ages and I couldn't be more thankful!