Makes rcd not work on reinforced doors.
tgstation/tgstation pull request #43598
Opened 2019-04-12 11:52 UTC by AnturK

:cl:
balance: Reinforced doors reinforcement need to be removed before RCD can deconstruct them.
/:cl:

This is not really a big change since there's almost certainly walls around the door.

2019-04-12 13:20 UTC, Fikou commented
based malf ai buff

2019-04-12 13:58 UTC, yoyobatty commented
At least it's not so bad, all you gotta do is remove the shielding, perfect rebalance.

2019-04-12 14:41 UTC, SouDescolado commented
Will this also block admin RCD?

https://github.com/tgstation/tgstation/blob/a39d4ea60210af1f17f5bb9ec1ef6372b2a89cb6/code/game/objects/items/RCD.dm#L610

2019-04-12 15:50 UTC, MrDoomBringer commented
This shouldn't block combat rcd

2019-04-13 07:38 UTC, zxaber commented
> based malf ai buff

Presumably, the AI's shutters effectively accomplished this already, right?

2019-04-13 14:32 UTC, Daxxed commented
Guess who died to an RCD
Jokes aside, this is good balance

2019-04-13 16:36 UTC, Barhandar commented
This will prevent me from laughing at idiots who go through hacking upload airlocks normally en-masse like in recent rev round instead of getting a RCD, DOWNVOTED

2019-04-15 04:46 UTC, SpaceManiac requested changes

2019-04-15 04:46 UTC, SpaceManiac commented on code/game/machinery/doors/airlock.dm
> +				to_chat(user,"<span class='notice'>[src] reinforcement needs to be removed first.</span>")
```suggestion
				to_chat(user, "<span class='notice'>[src]'s reinforcement needs to be removed first.</span>")
```

2019-04-15 19:13 UTC, Fikou commented
> > based malf ai buff
> 
> Presumably, the AI's shutters effectively accomplished this already, right?

yes but the shutters are destroyable with weaponry, the doors im pretty sure are invincible without explosives, so this will make the crew need to hack them or break the walls

2019-04-15 23:19 UTC, SpaceManiac approved these changes

2019-04-15 23:20 UTC, merged