*dab
tgstation/tgstation pull request #43682
Opened 2019-04-23 05:31 UTC by actioninja

## About The Pull Request

Adds dabbing

## Why It's Good For The Game

immersive dabbing roleplay SOUL balance community vote oranges bad coder dont play jkdsfjkaejrklsdjfksnweltknatkldtrjawettkl

## Changelog
:cl:
add: *dab
/:cl:

2019-04-23 05:32 UTC, Ordonis commented
c u r s e d

2019-04-23 05:34 UTC, Ordonis requested changes
Yes hello I would like to suggest the removal of the additions to the emote file. All the other changes are good. Reason: Dab.

2019-04-23 05:40 UTC, ATH1909 commented
YES.

I'd suggest removing the chance to get a special brain trauma, though- people already have other people intentionally fail lobotomies so they can get a shot at getting an imaginary friend, bluespace prophet, godwoken...

Actually, keep it in- dabbing so hard/well that you receive a guardian dabgel that only you can see/become woke and see the holes that you tore in spacetime with your dab/become possessed by the god of dabbing sounds rad as hell.

2019-04-23 06:00 UTC, closed without merging

2019-04-23 06:06 UTC, actioninja commented
bruh sound effect #2

2019-04-23 07:01 UTC, PKPenguin321 commented
monky

2019-04-24 18:14 UTC, Ziiro commented on code/modules/mob/living/carbon/emote.dm
> +			if(prob(80))
`(prob(80))`

n i c e

2019-04-25 08:20 UTC, ATH1909 commented
IT WORKS

AHAHAHAHAHAHAHAAAAAAA

https://cdn.discordapp.com/attachments/326826573951008769/570886097375068170/200_dabs.PNG

I HAVE DABBED OVER 200 TIMES IN A SINGLE ROUND

AND LIVED

AHAHAHAHAHAHAHAAAAAAAAAAAAAAA

2019-04-25 10:41 UTC, ATH1909 commented
https://www.reddit.com/r/SS13/comments/bh654h/local_lizardperson_dabs_over_200_times_and/

2019-04-25 18:50 UTC, gy1ta23 commented
Plagiarism is not okay

2019-04-25 21:14 UTC, ATH1909 commented
> Plagiarism is not okay

Plagiarism?! Those screenshots are mine, not someone else's. You can ask Plapatin himself about it, and he'll tell you that I play Hits-The-Ball (in addition to Jack Jackson and a few other characters).

2019-04-26 00:09 UTC, ATH1909 commented
... Wait, do you need arms to dab?

2019-04-26 00:24 UTC, Ziiro commented
>... Wait, do you need arms to dab?

Apparently not. I got myself nuggeted by too much dabbing and I could still do it.

2019-04-26 16:50 UTC, adamkad1 commented
anyone who dabs should be valid

2019-05-02 23:56 UTC, Ziiro commented
Some actual issues:

1) If you dab while stunned/unconscious, the emote doesn't play but it still runs through all the bad shit
2) If you dab your legs off, they aren't actually removed? It's really weird. Examine says  they're missing, but there the sprite is still there and you can keep wearing shoes
3) I have seen at least 25% of a shift dab itself to death every shift

Dabbing your way to superpowers is legit. Gamble big, win big prizes.

2021-02-27 00:38 UTC, ZeWaka commented
necro bruh