Pressurized Slime: Buff to oxygen and SILICON components
tgstation/tgstation pull request #43689
Opened 2019-04-24 00:34 UTC by carshalash

Water is fucking dumb to slip on now, even if some retard manages to slip on the wet floors, it's only a one tile difference and within range to pick up their guns easily. Lets fucking change that, pressurized blob is now the clowns best friend and will lube tiles.

2019-04-24 05:40 UTC, subject217 commented
Wow, another silicon buff from Carshalash :wink:

2019-04-24 08:08 UTC, Barhandar commented
Pressurized Slime will be the best blob chem, even better than cryo poison.

2019-04-24 09:36 UTC, 81Denton requested changes
Change all the description lines too por favor

2019-04-24 09:47 UTC, carshalash commented
> Change all the description lines too por favor

Fix the tubes to the ai sat on meta REEEEEEEEEEEEEEEEEEEEEEE

2019-04-24 10:31 UTC, carshalash commented
"	description = "will do low brute, oxygen, and stamina damage, and wet tiles under targets."

You mean that right?

2019-04-24 12:33 UTC, 81Denton commented
>Fix the tubes to the ai sat on meta REEEEEEEEEEEEEEEEEEEEEEE

Odd, I'll have another look at them.

>You mean that right? I thought it still applied pretty well so I left it.

Can you replace the "wets" part in those four desc lines with "lubes"? Lube doesn't freeze into ice and slips harder, I'd rather the exact name to be sure.

2019-04-24 13:19 UTC, carshalash commented
Now give me back the transit tubes you can walk over, you removed them all reeeeee.

2019-04-24 15:26 UTC, ExcessiveUseOfCobblestone commented
`Buff to oxygen and SILICON components` what does this mean?

2019-04-24 15:59 UTC, Barhandar commented
Spacelube is made with oxygen, silicon and water reagents, also silicons are slip-proof.

2019-04-24 16:13 UTC, ExcessiveUseOfCobblestone commented
cringe

2019-04-24 19:54 UTC, zxaber commented
People will just disable gravity, like they did before the slip rework.

2019-04-25 02:18 UTC, carshalash commented
> People will just disable gravity, like they did before the slip rework.

Better than people just not needing to worry at all about it.

2019-04-25 05:40 UTC, zxaber commented
The result is the only positive effect of this chem gets bypassed by engineer borgs, moths, anyone with mag boots, and anyone with a ranged weapon. That would be fine if blob wasn't a random roll of the dice for a decent chem. As long as changing chems is completly random, it's not great to have one so drastically useless (or at least, so situational).

2019-04-25 09:28 UTC, Barhandar commented
Magboots slip on lube, no? Also, still better than water (which IS bypassed by everything you've listed, but doesn't even slip satisfactorily).

2019-04-25 10:54 UTC, zxaber commented
While gravity is out? I have no idea. My understanding was that gravity disables slips entirely, but I suppose mag boots might change that.

Anyway, you're right, the current version is even worse, but I don't see this as a solid fix. Honestly, I think oranges was right, we ought to remove this chem entirely. If we could balance around the blob getting to choose the chem, it would be a nice situational choice, but unless you're specifically running from a chem that got hardcountered, chances are what you had before gave a better bonus than forcing the crew to fight without gravity.

2019-04-25 11:20 UTC, carshalash commented
Lube will leave the blob pretty powerful when it comes to  closed maint areas , it won't be good in spaced places but I see this being really decent. It's not gonna be emp levels of good but it'll still be pretty fun.

2019-04-25 12:48 UTC, YakumoChen commented
Raise the damage too to make up for the fact it doesn't stun now

2019-04-26 01:14 UTC, carshalash commented
Raise its stamina/oxygen damage or brute damage?

2019-04-26 06:10 UTC, YakumoChen commented on code/modules/reagents/chemistry/reagents/blob_reagents.dm
>  	M.apply_damage(0.4*reac_volume, BRUTE)
I'd change it to 0.5 maybe? Most of the blob's damage is temporary so if someone pulls out the victim before they crit they're usually fine (which almost always happens unless they're attacking from a lone angle)

2019-04-26 07:34 UTC, carshalash commented
hm... how do the number values here even work in comparison to their wiki numbers?

2019-04-26 15:58 UTC, ExcessiveUseOfCobblestone commented
Changelog needed

2019-04-26 22:58 UTC, carshalash commented
> Changelog needed
> 
> Also if you are editing anything beyond making the slip go from water-like to lube-like please update OP (preferably in the templated format).

Still contemplating whether I should touch damage or leave it be to see how it works with the lube changes.

2019-04-27 02:02 UTC, carshalash commented
Yeah I think i'll leave damage as is at the moment. Maybe tweak it in a future PR involving other blob changes.

2019-04-29 14:19 UTC, merged