Fixes shapeshift health adjustment
tgstation/tgstation pull request #43784
Opened 2019-05-01 19:53 UTC by 4dplanner

## About The Pull Request
Previous coder did extreme bad maths when making transform transfer health percentage. 

## Why It's Good For The Game
warning: not yet tested
This will make 0% simplemob health map to 0 carbon health, because having 20% send you into crit when you turn back would be dumb.

## Changelog
:cl:
fix: transform spell actually transfers damage correctly instead of healing most of the time
fix: 0% simplemob health maps to 0 carbon health, 100% simplemob to 100% carbon
/:cl:

2019-05-01 19:54 UTC, habader commented
love you fam

2019-05-01 20:02 UTC, Fikou commented
make it a full heal always that would be epic

2019-05-01 22:52 UTC, ATH1909 commented
Thank you for doing what I could not manage to do.

I fully support this PR.

2019-05-02 15:02 UTC, 4dplanner commented
wip because there's a damage coeff bug I have to fix when I get back

2019-05-03 12:25 UTC, 4dplanner commented
Did a quick test, but probably needs a testmerge to make sure usage of named arguments doesn't cause runtimes

2019-05-05 21:05 UTC, ExcessiveUseOfCobblestone commented
this is an issue 1 sec

2019-05-06 07:19 UTC, AnturK requested changes

2019-05-06 07:19 UTC, AnturK commented on code/modules/mob/living/damage_procs.dm
> +/mob/living/proc/apply_damage(damage = 0,damagetype = BRUTE, def_zone = null, blocked = FALSE, forced = FALSE)
Add it to overrides please.

2019-05-06 11:42 UTC, 4dplanner commented
Eh?

2019-05-07 23:19 UTC, merged