more buttons
tgstation/tgstation pull request #43799
Opened 2019-05-02 18:23 UTC by TetraK1

## About The Pull Request
Adds another increase and decrease button to frequency and code in remote signallers, increasing by 5 (Hz?) for frequency and by 10 for code.  Fixes going outside of freq range clamping to comms channel frequency range instead of free freq range.

## Why It's Good For The Game
It's a god damn effort clicking through the frequencies for anomalies, taking 20-30 clicks fairly frequently.  Previously the biggest freq button changes by 1Hz and the code by 5.  With the range clamping, if you went over 159.9 or below 120.1 it would clamp to whatever the comms freq range is (140s?).

## Changelog
:cl: Tetr4
tweak: Added another set of increase/decrease buttons to the remote signaller.
fix: Remote signaller range no longer clamps to the wrong range.
/:cl:

2019-05-05 17:57 UTC, 81Denton submitted a review, later dismissed

2019-05-06 07:28 UTC, AnturK commented
Could just make this typed in ?

2019-05-06 12:23 UTC, TetraK1 commented
> Could just make this typed in ?

ya

2019-05-07 12:41 UTC, vuonojenmustaturska requested changes

2019-05-07 12:41 UTC, vuonojenmustaturska commented on code/modules/assembly/signaler.dm
> +			var/new_freq = input(usr, "Input a new signalling frequency", "Remote Signaller Frequency", format_frequency(frequency)) as num|null
this is a sleep, you have to check that the signaler still exists after input

2019-05-07 12:41 UTC, vuonojenmustaturska commented on code/modules/assembly/signaler.dm
> +			var/new_code = input(usr, "Input a new signalling code", "Remote Signaller Code", code) as num|null
ditto

2019-05-10 19:43 UTC, AnturK submitted a review, later dismissed

2019-05-10 19:43 UTC, AnturK commented on code/modules/assembly/signaler.dm
> +			src.code = new_code
Drop the src. here and it's good to go.

2019-05-11 16:10 UTC, merged

2019-05-11 16:10 UTC, AnturK commented
Someone should update this one to browser datum.