DNA sequencer now uses a popup
tgstation/tgstation pull request #43853
Opened 2019-05-07 18:22 UTC by Time-Green

The genetic sequencer, now instead of dumping it's contents in the chat, saves it to a buffer. The sequencer can be clicked in-hand at anytime to view the last scanned sequence.

Someone made webscript that let you just kinda scan a few people and then get all the mutations lined up. Didn't think anyone would use it, but I actually caught quite a few people doing this. This breaks it for now, at least till I find a more waterproof solution

:cl:
tweak: The genetic sequencer now displays the sequence as a pop-up
/:cl:

2019-05-07 19:37 UTC, knacker48 commented
My main method of doing genetics was scanning a bunch of people in the halls at round start then going back to genetics and comparing the numbers to the mutations in order to solve the more difficult mutations. Will this PR invalidate this strategy?

2019-05-07 19:46 UTC, getbrecked commented
> My main method of doing genetics was scanning a bunch of people in the halls at round start then going back to genetics and comparing the numbers to the mutations in order to solve the more difficult mutations. Will this PR invalidate this strategy?

You could copy/paste the data into your PDA notes or a text editor.

2019-05-08 09:41 UTC, Grazyn commented
I wish there was another way to break the webscript, this really makes genetics much more painful to do.

2019-05-08 15:16 UTC, WarRage333 commented
Oh well it's still faster to use the old exploit to get powers

2019-05-08 15:53 UTC, py01 commented
Using the script is still going to be the quickest way to do genetics, you just need to do more copy-pastes.

2019-05-08 17:17 UTC, ATH1909 commented
But that script was what made genetics actually fun/playable for me...

Aw.

2019-05-08 19:17 UTC, ATH1909 commented
> this breaks that dude’s genetic solver script lol

That is literally the stated point of this PR.

2019-05-08 19:54 UTC, Time-Green commented
> Using the script is still going to be the quickest way to do genetics, you just need to do more copy-pastes.

@py01 I considered it, but I’m counting on people using the script to lack the mental capacity to figure that out

2019-05-08 22:26 UTC, knacker48 commented
If they're using a script they're at least smart enough to setup and use a script. I've never used one but how hard do you think it would be for them to alter the script to work around this change?

2019-05-09 09:15 UTC, Tlaltecuhtli commented
>If they're using a script they're at least smart enough to setup and use a script. 

you have to press save logs ingame put in a folder and click the dolphin.exe
you dont really need to be smart

2019-05-12 19:20 UTC, ShizCalev requested changes

2019-05-12 19:20 UTC, ShizCalev commented on code/game/objects/items/devices/scanners.dm
> +/obj/item/sequence_scanner/attack_self(mob/user)
Need to check for tk memes

2019-05-13 15:32 UTC, WaterStBlues commented
Brutal. Let's see how long it takes me to make another

2019-05-13 18:18 UTC, Time-Green commented
> Brutal. Let's see how long it takes me to make another

I was gonna hold back my trump card, but you give me no choice.
You’re going to regret saying that boy

2019-05-14 10:50 UTC, WaterStBlues commented
>I was gonna hold back my trump card, but you give me no choice. You’re going to regret saying that boy

I won't go as far as making an autoPy script, but it'll be fun!
Instead of comparing eDick size, what if we just made the genetics scanner do what my script does, but with a cooldown between scans? Genetics has been woefully nerfed anyway.

2019-05-14 14:00 UTC, Time-Green commented
> > I was gonna hold back my trump card, but you give me no choice. You’re going to regret saying that boy
> 
> I won't go as far as making an autoPy script, but it'll be fun!
> Instead of comparing eDick size, what if we just made the genetics scanner do what my script does, but with a cooldown between scans? Genetics has been woefully nerfed anyway.

What would prevent someone from just walking around for 10-15 minutes scanning people with the cooldown and then instantly completing all of genetics? Because it would be that easy. I’m open to suggestions, but I’m not going to make any massive changes anymore. (Feel free to do so yourself though)

2019-05-14 14:57 UTC, WaterStBlues commented
Alright think bout this: a slowly recharging "ammo" system. A geneticist can scan four dudes right away, but then each charge after that will take 30-40 seconds a piece to recharge. This will encourage him to go back to the lab and solve more sequences before going back out and getting more of those sweet, sweet sequences.

That being said, is running around for 20 minutes, then needing to crawl back and punch in hundreds of bases any better for gameplay than just sitting at a console matching base pairs?

2019-05-14 19:39 UTC, Time-Green commented
> Alright think bout this: a slowly recharging "ammo" system. A geneticist can scan four dudes right away, but then each charge after that will take 30-40 seconds a piece to recharge. This will encourage him to go back to the lab and solve more sequences before going back out and getting more of those sweet, sweet sequence scans.
> 
> That being said, is running around for 20 minutes, then needing to crawl back and punch in hundreds of bases any better for gameplay than just sitting at a console matching base pairs?

People are just gonna abuse it by getting more, and 4 is alot.

Yeah it’s alot better than constantly chasing people, then waiting, then chasing people. If your argument is that the solving is boring, then actually make a meaningful change to make it more engaging instead of encouraging people to exploit it.

2019-05-15 13:56 UTC, Time-Green commented
I pretty much made a new PR. It can only show one mutations' sequence at 20 second intervals.

2019-05-15 13:59 UTC, WaterStBlues commented
Cool - I had a few alternate ideas to run past you, will post there after
I'm done work

On Wed, May 15, 2019, 11:26 AM Time-Green, <notifications@github.com> wrote:

> I pretty much made a new PR. It can only show one mutations' sequence at
> 20 second intervals.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/43853?email_source=notifications&email_token=AKYLY5CTBW56QXWXK4PDOXLPVQJCTA5CNFSM4HLLKZO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVOXWNY#issuecomment-492665655>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKYLY5AWB3PCC256QX647YTPVQJCTANCNFSM4HLLKZOQ>
> .
>

2019-05-29 10:25 UTC, 0d0be32b607ee4ecbc2358f3dd4a27de commented
WAAA WAAA PEOPLE DON'T PLAY THE GAME MY WAY WAAAAAAAAA

2019-05-30 08:35 UTC, merged

2019-05-30 19:55 UTC, kopoba commented
unplayble

2019-05-31 06:46 UTC, Time-Green commented
Try using your three braincells instead of third party programs. People playing genetics legitimitely are pretty much completely unaffected.

2019-05-31 13:43 UTC, kopoba commented
> 
> 
> Try using your three braincells instead of third party programs. People playing genetics legitimitely are pretty much completely unaffected.

like how the they unaffected?
You run like crazy around station for each sequence to find one that you are workin on and then you do this again for another one because you don't store results and cant see them.

If you try to store each of 8 mutations from scanned man you got stupid 20 seconds cooldown to just view sequence. ~160-180 seconds on one man.
then copypaste it somewhere that also takes sometime.
>People playing genetics completely unaffected.
this is a joke?

2019-05-31 14:05 UTC, Time-Green commented
@kopoba Results are stored in the chat if that's what you mean. Just work on one mutation at a time, and if you can't solve it scan one of your monkeys and then move on.

2019-05-31 16:40 UTC, kopoba commented
> 
> 
> @kopoba Results are stored in the chat if that's what you mean. Just work on one mutation at a time, and if you can't solve it scan one of your monkeys and then move on.

you need 20 seconds to view one result theres like 45 mutations
45*20=15 minutes to get all mutations if you lucky and have all 45 in one man in one scan
and don't even solve them
are you sure this is right?
because it seems to take ridiculous amount of time to work in genetics

2019-05-31 17:14 UTC, Time-Green commented
In those 20 seconda you could be entering the sequence thingy. You don’t literally stand still 20 seconds

2019-05-31 19:38 UTC, kopoba commented
> 
> 
> In those 20 seconda you could be entering the sequence thingy. You don’t literally stand still 20 seconds

So in addition you need to scan peoples again and again and again to find mutation you trying to solve.

2019-05-31 20:18 UTC, Time-Green commented
That doesnt happen at all though. You can scan mutations to your hearts content without cooldown. Only the option to view the sequence of the specific mutation has a cooldown.

2019-05-31 21:19 UTC, kopoba commented
> 
> 
> That doesnt happen at all though. You can scan mutations to your hearts content without cooldown. Only the option to view the sequence of the specific mutation has a cooldown.

This update make genetics worse and take alot more time and manipulation. Also  scanner don't show instability on scan.

2019-06-23 21:56 UTC, adamkad1 commented
lemme make this shiz so that it stores genes from all people scanned and you can see complete sequences with enough people scanned.

2019-06-24 06:23 UTC, Time-Green commented
Go ahead, I don’t own the code. But that has serious balance implications and makes genetics extremely easy