Comms console window no longer steals focus
tgstation/tgstation pull request #43909
Opened 2019-05-10 04:52 UTC by kriskog

## About The Pull Request
Fixes #15526
Fixes #36837

Prevents the comms console window taking focus on every process() when used by AI. Only happens in default view.

Don't ask me why this works, it sets content and opens popup twice for non-ai as well. 

## Why It's Good For The Game
Bug fix

## Changelog
:cl:
fix: Communications console window no longer steals focus every couple seconds when used by AI.
/:cl:

2019-05-10 04:53 UTC, Eaglendia commented
Best change in years.

2019-05-10 07:12 UTC, actioninja commented
Oh my god, finally

2019-05-10 07:51 UTC, MimicFaux commented
ALL THIS TIME I THOUGHT I WAS THE ONLY ONE. PRAISE IT.

2019-05-10 12:25 UTC, 4dplanner commented
>don't ask me why this works 

👺

2019-05-10 12:47 UTC, actioninja commented on code/game/machinery/computer/communications.dm
> +			popup.set_content(dat)
add a comment explaining why this is here so that someone doesn't come along later and remove it thinking it's an accidental duplication

2019-05-10 16:01 UTC, AnturK requested changes
This is complete nonsense, remove the process or add explicit focus checking.

2019-05-10 23:40 UTC, kriskog commented
@AnturK Yes it's stupid. It somehow works though. Its been done that way for years for non-silicons.
I can't see a way of preserving the automatic updates (shuttle timer, others doing stuff) and preventing it from taking focus. The brower instance used doesn't seem to have an option for focus, and removing process() is a step backwards.

2019-05-11 10:29 UTC, alexkar598 commented
With a bit of work you can change the timer to be updated by a javascript script which you can call with arguments using browse()

2019-05-15 13:50 UTC, Timonkeyn commented
I love you

2019-05-24 19:52 UTC, kriskog commented
I guess I am removing the process() here. I'll get to it.

2019-05-27 10:22 UTC, closed without merging