Reduces crabphone volume to being merely loud and reduces the market's hp by 2700
tgstation/tgstation pull request #43918
Opened 2019-05-11 02:29 UTC by vuonojenmustaturska

## About The Pull Request

Title + also makes it not spawn inside closed walls and makes it not process until it can actually do something inside process()

## Why It's Good For The Game

Fucking christ try playing with sounds on. Also it takes several people several minutes to destroy the fucking thing even if it's immediately found due to high armor, having more HP than bubblegum and being immune or highly resistant to most damage types

## Changelog
:cl: Naksu
balance: The crabphone will no longer deafen everyone who didn't have the foreknowledge that it was coming.
balance: The crabphone has 90% less HP, as befits something that costs 7 TC and is not two bubblegums stacked on top of eachother.
/:cl:

2019-05-11 02:37 UTC, actioninja commented
Fuck, 20 is still loud? Why is this one sound so much louder than so much other stuff?

2019-05-11 02:52 UTC, Shadowflame909 commented
please buff the amount of money it drains considering the entire station will be after it.

The health goes down pretty fast when 30 people are bashing it with their strongest weapon.

2019-05-11 05:17 UTC, tralezab commented
7 tc takes 30 people to intervene

2019-05-11 05:57 UTC, Shadowflame909 commented
No silly. 7 TC but it tells the entire server of 90 people that they're being robbed and where they're being robbed.

Compare it to the power sink.

2019-05-11 10:24 UTC, subject217 commented
qustinnus with a poorly balanced meme traitor item? who could have predicted this?!

2019-05-11 13:05 UTC, Arianya commented
>The health goes down pretty fast when 30 people are bashing it with their strongest weapon.

This thing exists as a single tile. So at most 8 people could hit it, in a ideal situation. In a more realistic situation, some or most of these tiles will be taken up by walls, tables, or other things which prevent someone hitting it.

So realistically most of the time you have 4 or 5 people hitting it and their best weapon is a toolbox or a lit welder, not a double esword.

2019-05-11 15:37 UTC, duckay commented
not accounting for the smart folk who decided to crawl?

2019-05-12 16:10 UTC, Arianya commented
Accounting for the minority of the playerbase who would crawl and giving something 3000 hp on top of some pretty nice armour buffs is called "balancing for the far end of the bell curve" and is dumb

2019-05-12 17:24 UTC, Shadowflame909 commented
By the time the syndicate bomb gets set off every time this is used. It ends up at 2300 from 3000.

This'll make this item being destroyed a breeze.

2019-05-12 22:03 UTC, subject217 commented
What's the problem, Shadowflame? That's a good thing.

2019-05-12 23:56 UTC, JusticeGoat commented
Thank you, i was about to open a issue with how ear shattering loud it is.

2019-05-13 04:26 UTC, wesoda25 commented
Can we please just remove this already. It’s really annoying to deal with, especially considered only two people ever show up to stop it, meaning they have to beat it with fire extinguishers the whole round, at which point they get blown up or some shit.

2019-05-13 16:45 UTC, Shadowflame909 commented
@subject217 

It wont be worth 7 tc. Since it'd be reduced to a Loud powersink

2019-05-13 19:54 UTC, subject217 commented
Yes, and? It shouldn't be in the game to begin with.

2019-05-13 20:26 UTC, vuonojenmustaturska commented
i have generously doubled the market's HP in the latest commit, from 300 to 600

2019-05-13 20:55 UTC, ninjanomnom requested changes

2019-05-13 20:55 UTC, ninjanomnom commented on code/game/objects/items/crab17.dm
> +		var/turf/targetturf = get_safe_random_station_turf()
You should handle the rare case of get_safe_random_station_turf() being null

2019-05-14 13:35 UTC, ninjanomnom approved these changes

2019-05-14 15:55 UTC, merged