Agent card
tgstation/tgstation pull request #44075
Opened 2019-05-21 18:04 UTC by Yenwodyah

## About The Pull Request

Allows agent cards to be forged by anyone if they're used in an unforged state by a non-traitor. Previously, to prevent metagaming, only antags could forge agent IDs.

## Why It's Good For The Game

There's no reason to hide the fact that a card is an agent ID if it hasn't been forged into anything yet. Now if a non-antag gets an unforged agent ID from null crates, stolen uplinks, captured traitors, etc. they can use it to call themself bogdanoff and yell "dump eet" over comms. And other hilarious memes.

## Changelog
:cl: Yenwodyah
tweak: Non-antags can now forge all agent IDs if they find them before they've been forged.
/:cl:

2019-05-21 18:20 UTC, imsxz commented
the point of it was to prevent sec from using agent ID cards in hand to check if it was an agent ID card, the issue was that nonantags still got the chameleon change buttons after they were added.

2019-05-21 18:32 UTC, Yenwodyah commented
Even less of a reason to stop nonantags from forging them, then.

2019-05-21 21:55 UTC, necromanceranne commented
Finally.

2019-05-22 00:34 UTC, nero1024 commented
Why can't just anyone forge an ID with the agent card in the first place?

2019-05-22 06:31 UTC, HomocidlePancakes commented
Because it’s supposed to be a camouflage item/a way for you to stealthy gain more access and the fact that sec can just use it hand to check kinda nullifies it’s whole purpose.

2019-05-22 13:16 UTC, anconfuzedrock commented
Yen be like
"oh, the thing is broken because of a very minor, fixable issue? I better use that issue as an excuse to change the thing, instead of fixing the minor, fixable issue."
heck no, that's not an excuse or we wouldn't have metastation in the game because it has access issues with the virology front door

2019-05-22 15:10 UTC, Yenwodyah commented
Not sure what you mean confuzed. If you're talking about the chameleon action buttons, that's unrelated to this PR.

2019-05-22 20:39 UTC, ATH1909 commented
While you're at it, could you fix this bug?

https://github.com/tgstation/tgstation/issues/44087

2019-05-22 23:41 UTC, Yenwodyah commented
@ATH1909 This should fix it, but it won't fix the underlying problem, which is probably some antag spawner forgetting to set special_role.

2019-05-23 07:12 UTC, HomocidlePancakes commented
Non-traitors being able to cham buttons on the IDs was an oversight when they were added

2019-05-23 14:54 UTC, Shadowflame909 commented
Do you think now that anyone can use it, it's no longer worth its current price?

2019-05-23 15:20 UTC, Yenwodyah commented
@Shadowflame909 As long as you disguise it as something after you buy it, non-traitors still can't use it.

2019-05-28 06:10 UTC, ShizCalev requested changes

2019-05-28 06:10 UTC, ShizCalev commented on code/game/objects/items/cards_ids.dm
> +				..()
return ..()

2019-05-28 06:10 UTC, ShizCalev commented on code/game/objects/items/cards_ids.dm
>  	..()
return ..()

2019-05-28 14:10 UTC, merged