Massive buff for Xenobiology in the form of adding additional lights on Meta and Box Station
tgstation/tgstation pull request #44259
Opened 2019-06-01 11:27 UTC by 123chess456

## About The Pull Request

This adds 2 more lights to the xenobiology test chamber on MetaStation and Box, and adds a light in every slime breeding chamber on Box Station where there was none from before. It also removes the nearly useless table in the MetaStation xenobiology test chamber that doesn't have any purpose except to add more clutter to a slime storage area.

Below is the map on box before:

![boxtestchamberbefore](https://user-images.githubusercontent.com/8888654/58747731-4b238000-843d-11e9-91e1-c7eeadf76dcf.PNG)

![boxxenobiobefore](https://user-images.githubusercontent.com/8888654/58747732-4fe83400-843d-11e9-9267-74ad95d74fa4.PNG)

Here is the map on box after:

![boxstationxenobiology](https://user-images.githubusercontent.com/8888654/58747744-5e365000-843d-11e9-9516-2a2a6096dc15.PNG)

![boxtestchamber](https://user-images.githubusercontent.com/8888654/58747745-61314080-843d-11e9-9748-220acd6bb260.PNG)

Here is the test chamber on Meta before:

![xenobiotestchamberwithoutlights](https://user-images.githubusercontent.com/8888654/58747756-8faf1b80-843d-11e9-9595-c8092bf22d9b.PNG)

Here it is after:

![xenobiotestchamberwithmorelights](https://user-images.githubusercontent.com/8888654/58747760-93db3900-843d-11e9-8b4e-d26a7ac98730.PNG)

## Why It's Good For The Game

Before this PR, xenobiology was very dark and hard to see in. This is annoying if your eyesight or colour differentiation wasn't good, and made differentiating silver and metal slimes in the xenobiology test chamber incredibly difficult. On Box, this was even worse. It was dark and very difficult to see, which unfortunately was not an aspect I was able to show in my screenshots because I used an online map viewer.

This represents an increase in quality of life for xenobiology as it actually allows them to differentiate certain slime species that look similar, such as oil/black and silver/metal at a glance.

## Changelog
:cl:
add: Every slime chamber in Xenobiology on BoxStation now has its own light. 2 more lights have been added to the Xenobiology Test Chamber on BoxStation and MetaStation making it much more well lit.
del: Removed the table with an electropack, power cell stuff, and igniters in the xenobiology test chamber.
/:cl:

2019-06-01 11:30 UTC, Barhandar commented
Why did you touch the memetable in the PR intended for just adding lights?

2019-06-01 11:34 UTC, 123chess456 commented
i realized oranges wouldn't want to merge a PR unless it removed something that people liked

2019-06-01 11:43 UTC, Rowelll commented
> i realized oranges wouldn't want to merge a PR unless it removed something that people liked

we love you.

2019-06-01 11:54 UTC, Barhandar commented
Also, your PR's title is severely misleading: you claim to only be adding lights, but what you actually do is also remove table and igniter for separate reasons. Describe your changes fully or atomize.

2019-06-01 14:38 UTC, Akrilla commented
Removing the tables is a bit of a nerf for alien larvae no?

2019-06-01 14:53 UTC, kriskog commented
The igniter is used to burn xenos, leave it in.

2019-06-03 15:01 UTC, RaveRadbury commented
Part of map clutter is about giving people stuff to do while setting up their work spaces. I'd hate to see that table and loot go.

2019-06-03 17:27 UTC, ExcessiveUseOfCobblestone requested changes
> The igniter is used to burn xenos, leave it in. You'll notice there is a gas injector there too, partially for the same reason.

The table removal is fine, i'm not sure why those items are in there since it's a holding pen (probably legacy when we didn't have a gun lab)

2019-06-04 05:04 UTC, optimumtact commented
funny

2019-06-09 21:43 UTC, ExcessiveUseOfCobblestone commented
my last review was 6 days ago so just PM if you plan on updating this.

2019-06-09 21:43 UTC, closed without merging