experimental_dissection available at roundstart
tgstation/tgstation pull request #44338
Opened 2019-06-05 17:28 UTC by japisd

## About The Pull Request
Experimental dissection surgical procedure will now be available at the beginning of the round, giving medical doctors something else to do at round start that:

1. positively affects the whole station.
2. is some warm up practice for surgery
3. allows for earlier in round medical rp and fun.
4. increases medical interaction with genetics department and xenobiology

The success chance is now 70% with a scalpel, 20% with knife, and 10% with a shard.
The research points returned by the procedure are higher, 1.5k for monkeys, 2.5k for humans, 4k for jellyperson, 4k for golem, 10k for alien royal, 5k for alien adult and as 8k for an abductor.
The time was also increased to twenty seconds.

## Why It's Good For The Game

Additional things for medical personnel to have fun with and contribute to the station. It will make research go faster if people spend the time and effort which I think is worth it. 

## Changelog
:cl:
tweak: moved experimental dissection surgery to be available at round start and deliver slightly higher rewards.
/:cl:

2019-06-05 18:15 UTC, knacker48 commented
Great change!
Gives something for doctors to do round start and gives science a little more points

2019-06-05 18:57 UTC, Swiftkor commented
could you add some sort of automated announcement on sci radio when a surgery is successful that states how many points sci gained from the surgery? Would be nice to have science appreciate the hard work of medical doctors

2019-06-05 19:08 UTC, shellspeed1 commented
Good pr, also imagine science also appreciating medbay's work.

2019-06-05 20:34 UTC, FantasticFwoosh commented
It should/would be priority for mining to bring back bodies to dissect since they are easily accessible on lavaland with this change by fighting a legion (mob) or two.

2019-06-05 21:34 UTC, ExcessiveUseOfCobblestone commented
placeholder for rationale

2019-06-05 21:39 UTC, ExcessiveUseOfCobblestone requested changes
See below

2019-06-06 10:06 UTC, japisd commented
I love the idea of upgradable techweb, but why wait for that to happen before testing out how medbay and people find ways of using this / exploiting it? The earlier we can see how it plays the earlier we can fine tune it. 
Thoughts?

2019-06-06 15:08 UTC, ExcessiveUseOfCobblestone commented
I'm down, just see review

2019-06-06 15:09 UTC, ExcessiveUseOfCobblestone commented on code/modules/surgery/experimental_dissection.dm
> +				return 4000
43-46 should be

```DM
if(isgolem(H) || iszombie(H) || isjellyperson(H) || ispodperson(H))
    return 4000
```
since it's the same price now

2019-06-06 16:11 UTC, AdamElTablawy commented
It'd be nice if it existed in its original form but researching it yielded higher research points per dissection up to the values proposed here, so that sci still has to invest in it for research point return, but can still get research points from it

Because otherwise robotics will have a field day mass  producing research points

2019-06-06 16:13 UTC, ExcessiveUseOfCobblestone commented
They can mitigate speed but they won't be able to mitigate the prob

2019-06-06 16:17 UTC, Tlaltecuhtli commented
does dissecting different human species ( moth, etheral, plasmaman) give 1k each or do they count as the same?

2019-06-06 16:22 UTC, ExcessiveUseOfCobblestone commented
You DON'T get a bonus for doing a unique species compared to your experimental surgery history, it's on a per mob basis.

You DO get a bonus if the human is a special species **each time you do the surgery**. 2 abductors = 20K, not 10K then 2K.

2019-06-06 16:32 UTC, Yttriums commented
Maybe the human/monkey numbers could be tuned downward and/or the bonuses for them could be available only once for each station? That would prevent most abuse while still allowing the crew to get a nice bonus when a rarer corpse is found (without regard to the station's level of research).

2019-06-06 17:28 UTC, japisd commented
Good idea, maybe actually keep a counter and do decreasing rewards per member of the same species that is dissected. I am unfamiliar with the codebase at the moment so I can't do that right now but I will look into it.

2019-06-06 17:48 UTC, ExcessiveUseOfCobblestone commented
The surgery prob is low (and why borgs can't do it) to account for the repeatability. It's by design to be repeatable to the same types of mobs.

2019-06-06 18:16 UTC, japisd commented
I think the test merge candidate tag was removed because I made a mistake on the commit. It should be fine now.

2019-06-06 19:38 UTC, ExcessiveUseOfCobblestone commented
stop resisting!

2019-06-06 22:37 UTC, ExcessiveUseOfCobblestone commented
FYI if you fail the prob you can never do the surgery again on that body.

2019-06-09 19:32 UTC, AdamElTablawy commented
@ExcessiveUseOfCobblestone The prob isn't that severe, is the thing.

Monkeys are easy to mass produce and surgery goes very fast, especially once you get the advanced tools. If someone's really dedicated they can shave like 30 minutes off the research table time.

2019-06-10 12:38 UTC, japisd commented
There should be a max cap on the research you can get from this, I will read up on how they max the amount of rp from toxins and try to update this with something similar.

2019-06-10 19:55 UTC, ExcessiveUseOfCobblestone commented
> @ExcessiveUseOfCobblestone The prob isn't that severe, is the thing.
> 
> Monkeys are easy to mass produce and surgery goes very fast, especially once you get the advanced tools. If someone's really dedicated they can shave like 30 minutes off the research table time.

Then just lower the research gained per monkey and normal human but keep it so that it's still "spammable". If you are going to spam monkeys > optionally turn them into human > kill them > do surgery on EVERY SINGLE ONE then I don't see the issue with getting a reward out of that. That surgery alone takes a bit to do and you have to find a new body each time.

2019-06-12 00:12 UTC, adamkad1 commented
its not like you cant make 50k points in 20 mins

2019-06-12 14:58 UTC, adamkad1 commented
> > @ExcessiveUseOfCobblestone The prob isn't that severe, is the thing.
> > Monkeys are easy to mass produce and surgery goes very fast, especially once you get the advanced tools. If someone's really dedicated they can shave like 30 minutes off the research table time.
> 
> Then just lower the research gained per monkey and normal human but keep it so that it's still "spammable". If you are going to spam monkeys > optionally turn them into human > kill them > do surgery on EVERY SINGLE ONE then I don't see the issue with getting a reward out of that. That surgery alone takes a bit to do and you have to find a new body each time.

its not like you cant make 50k points in 20 mins so whats the bother

2019-06-12 16:09 UTC, ExcessiveUseOfCobblestone commented
something not being balanced is not an excuse to make other things imbalanced.

2019-06-13 20:44 UTC, adamkad1 commented
> something not being balanced is not an excuse to make other things imbalanced.

if everything is unbalanced nothing is unbalanced

2019-06-14 14:39 UTC, ExcessiveUseOfCobblestone commented
lol

2019-06-17 01:39 UTC, optimumtact commented
@ExcessiveUseOfCobblestone where are you taking this?

2019-06-17 16:56 UTC, ExcessiveUseOfCobblestone requested changes
Goal: Make experimental dissection a small player in research gain but can have a higher impact if someone chooses surgery "route"

Todo for me to ok this PR:

1. Please remove the inability to try the surgery again upon failing the last step. The balance should be on the pointgain/time/probability and not an all/nothing mechanic.
2. If you're not creating upgrades, the points need to assume players will do this constantly and as much as possible from beginning to end. Ergo humans/monkeys definitely need a drop.

2019-06-23 00:15 UTC, adamkad1 commented
so is this viable?

2019-06-23 01:22 UTC, optimumtact commented
IF op ever came back yes

2019-06-23 01:22 UTC, closed without merging