Fixes monkey cube exploit.
tgstation/tgstation pull request #44366
Opened 2019-06-06 23:25 UTC by nemvar

## About The Pull Request

Fixes an exploit that allows you to spawn an infinite amount of monkeys with a single cube. The bug exists because of a fault in the delete logic and quite frankly, I have no idea how to fix it properly.

Fixes #44364

## Why It's Good For The Game

This bad fix is better than the alternative of having an infinite amount of gorillas every round.

## Changelog
:cl:
fix: Fixes an exploit that allowed to you to spawn multiple monkeys with a single cube.
/:cl:

2019-06-06 23:26 UTC, spessbro commented
gimme muh infinity monkeys

2019-06-07 12:59 UTC, Ty-the-Smonk commented
I didnt even know this existed

2019-06-07 18:26 UTC, ma44 commented
The players have spoken

2019-06-08 11:13 UTC, AnturK requested changes

2019-06-08 11:13 UTC, AnturK commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +	QDEL_NULL(src)
I don't know what the issue here is but this won't be fixing it.

2019-06-08 13:31 UTC, closed without merging