EMPs now randomize suit sensors if they're on
tgstation/tgstation pull request #44398
Opened 2019-06-08 18:54 UTC by Couls

## About The Pull Request
Makes suit sensors react to EMPs

## Why It's Good For The Game
It's just a cool feature and since jumpsuits can have their sensors broken by damage I don't see why they wouldn't be impacted by EMPs if they were on

## Changelog
:cl:
add: suit sensors are now randomized when caught in an EMP
/:cl:

2019-06-08 19:07 UTC, Shadowflame909 commented
should turn them on if they're off.

2019-06-08 19:18 UTC, Couls commented
That would be easy to change but I didn’t really wanna mess with balance all that much because that’ll buff EMPs

2019-06-08 19:55 UTC, wesoda25 commented
Randomizing is perfect, theres a chance for your victim to go off but you go on

2019-06-08 20:13 UTC, Time-Green commented
New medical doctor meta

2019-06-08 20:45 UTC, Akrilla commented
Rough CMO turning up those suit sensors

2019-06-08 21:39 UTC, Shadowflame909 commented
I think emps turning suit sensors on would be a nerf. Make people think twice before revealing their locations.

Also, this won't help CMOS other gamers. It only affects suit sensors when ON. So it'll just make more people with suit sensors off.

Add that nerf Couls. The balance must be restored. Since this is also a buff.

2019-06-08 23:09 UTC, Couls commented
It would make no sense for an EMP to turn your sensors on.. thats like an EMP turning your cellphone on when it was off

2019-06-10 15:40 UTC, ninjanomnom requested changes

2019-06-10 15:40 UTC, ninjanomnom commented on code/modules/clothing/under/_under.dm
> +	..()
Use `. = ..()` at the top

2019-06-10 22:40 UTC, ninjanomnom approved these changes

2019-06-10 22:40 UTC, merged