Adds drone shell activation logging + admin notify
tgstation/tgstation pull request #44461
Opened 2019-06-11 19:26 UTC by 81Denton

This PR adds drone shell activation logging + admin notify with the activation location, so that drones can't hop over to the station and claim that someone brought their inactive shell over to the station first.

2019-06-11 19:50 UTC, DaxDupont commented
Free drone

2019-06-14 19:38 UTC, SpaceManiac requested changes

2019-06-14 19:38 UTC, SpaceManiac commented on code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
> +	message_admins("[ADMIN_LOOKUPFLW(user)] has taken possession of a [src] in [AREACOORD(src)].")
`a [src]` will produce "a the drone shell", either just `[src]` for "the drone shell" or `\a [src]` for "a drone shell"

2019-06-19 07:35 UTC, 81Denton commented
Ok, grammar should be fixed

2019-06-19 10:16 UTC, SpaceManiac requested changes

2019-06-19 10:16 UTC, SpaceManiac commented on code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
> +	log_game("[key_name(user)] has taken possession of a [src] in [AREACOORD(src)].")
```suggestion
	log_game("[key_name(user)] has taken possession of \a [src] in [AREACOORD(src)].")
```

2019-06-19 19:42 UTC, SpaceManiac approved these changes

2019-06-19 19:43 UTC, merged