[WIP]Space is no longer cold
tgstation/tgstation pull request #44503
Opened 2019-06-13 18:20 UTC by XDTM

## About The Pull Request

It's about time that an atmos simulator actually represented space as not cold!

To be exact, space is still cold, but now it has no heat capacity or thermal conductivity, making it unable to sap or give off heat.
For mobs instead i made the formula add in air pressure as a factor; therefore standing in space won't change your temperature die to the lack of heat. As a plus, areas with very thin air but extreme temperatures no longer affect people as much as they used to.

## Why It's Good For The Game

⭐️ Realism! ⭐️ 

There is such a thing as suspension of disbelief, but a game so centered on space and so mechanically intricate should have space mechanics a bit closer to reality.
Plus it would shake up a lot of deep-rooted mechanics of the game and i think it's a good opportunity to consider potential changes to space balance as a whole.

**I do realize that such a change does disrupt gameplay a LOT, which is why this is staying WIP until stuff is rebalanced appropriately.**

## To-Do List (Will add new stuff as it comes)

- Rebalancing loss of cold space damage with pressure
  - Considering the removal of the cold slowdown in space
  - Considering that suits now only need to be pressure-proof and not cold-proof
  - Considering, vice versa, that suits that protect only from heat no longer give any space protection
  - Figure out a good formula for damage that considers both low and high pressure

- Checking for mechanics which rely on space to be cold
  - Supermatter heat transfer pipes using space to cool down the gas

## Changelog
:cl: XDTM
balance: Space is no longer cold. (To be exact, it no longer transfers heat).
/:cl:

2019-06-13 18:21 UTC, plapatin commented
what is the cosmic radiation background

2019-06-13 18:21 UTC, adamkad1 commented
heresy

2019-06-13 18:21 UTC, loserXD commented
sorry I don't understand

2019-06-13 18:24 UTC, duncathan requested changes
so long as i still draw breath, i will fight against the proclamation of "realism" for the sake of space being cold :-1:

2019-06-13 18:26 UTC, duncathan commented
for the record space being cold is both better gameplay imo and also very importantly matches the average person's understanding, despite that understanding being flawed. realism has its place but i firmly believe that this is not it

2019-06-13 18:28 UTC, Ty-the-Smonk commented
This game has plasma, a item that can be 3 states of matter at room temperature, realism man bad.

2019-06-13 18:29 UTC, Tlaltecuhtli commented
its always at the gas status but its finely packaged into bars

2019-06-13 18:30 UTC, Ty-the-Smonk commented
> its always at the gas status but its finely packaged into bars

based

2019-06-13 18:31 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
20C at 101.3 kPa is plasma's triple point

2019-06-13 18:33 UTC, XDTM commented
@duncathan i suppose changing it now is probably undoable (i know this PR won't survive, but i wanted to try), but if the game started out with realistic space i bet it would not be changed to cold space for gameplay reasons; i think it's a balancing history issue more than a realism vs gameplay issue.

2019-06-13 18:39 UTC, duncathan commented
it's true, much of it has to do with the history of features we've had - you may be right that if we started with thermal vacuum we wouldn't switch to cold. however, when your to do list doesn't even mention the important gameplay things like drinking hot coffee to prepare for a ghetto spacewalk, desperately hoping that it'll last long enough that you can make it to the shuttle before the pressure kills you anyway, it becomes clear to me that you haven't considered this decision quite as much as I have. that's just one example of the gameplay I'm concerned with - none of it is mentioned in your pr

2019-06-13 18:41 UTC, XDTM commented
Fair enough, i did rush through opening it, but mostly because i wanted to hear the counter-arguments before starting the balancing work (again, not much hope of this actually happening).

2019-06-13 18:51 UTC, FloranOtten commented
Big problem; Firesuits are now spacesuits. You can literally just wear a firesuit and helmet, and use backpack internals to spacewalk. Why even use a spacesuit, then?

2019-06-13 18:53 UTC, XDTM commented
Antur made me notice that plasmafires will never cool down without the space heatsink, and the ramifications of fixing that are probably too wide to even consider.

2019-06-13 18:53 UTC, closed without merging

2019-06-13 23:20 UTC, yoyobatty commented
You also lower pressure which increases the boil point of all bodily fluids which contain heat. Those vaporize and move away. Also, in space, you lose heat to radiation and it's quite a quick process.

2019-06-14 13:19 UTC, Dennok commented
> Antur made me notice that plasmafires will never cool down without the space heatsink, and the ramifications of fixing that are probably too wide to even consider.

You dont need heatsink for stop plasmafire, you just need to remove fuel of the fire.
Space heatsink need to supermatter engine but can be replaced by freezer units, and as i know now heat exchange pipes dont use space as heat capacitor, it just remove heat by radiation (magick).
About space and cool, matter coold in the space becose it lost heat in expansion and low pressure lower it boil point.
Now i see problem in supermatter low pressure interaction. As i know it take actual temperature of border gases regardless of it density ()

2019-06-15 16:04 UTC, WJohn commented
Dealing with heat in space is, in fact, kind of a huge pain in the ass. You'd need a proper cooling/heating system to go anywhere with this, sadly.