fixes russian helmets not holding vodka
tgstation/tgstation pull request #44692
Opened 2019-06-20 11:41 UTC by Tlaltecuhtli

:cl:
fix: fixes russian helmets not holding vodka
/:cl:

2019-06-20 12:54 UTC, europaisch commented
quality pr, товарищ

2019-06-20 14:19 UTC, europaisch commented
Also this fixes #44686

2019-06-20 14:19 UTC, europaisch commented
Also this fixes #44686

2019-06-20 15:24 UTC, nemvar commented on code/datums/components/storage/concrete/pockets.dm
> +	max_items = 2
I'm sensing some russian bias here.

2019-06-20 16:41 UTC, 81Denton requested changes
Document your changes properly por favor

2019-06-22 05:51 UTC, ninjanomnom requested changes

2019-06-22 05:51 UTC, ninjanomnom commented on code/datums/components/storage/concrete/pockets.dm
> +	max_combined_w_class = 100
You don't need this much

2019-06-22 06:16 UTC, ninjanomnom approved these changes

2019-06-22 06:17 UTC, merged