Changes improvised jetpack recipe
tgstation/tgstation pull request #44794
Opened 2019-06-24 16:27 UTC by Shapsy

## About The Pull Request
Fixes: #44775

Makes the improvised jetpack require 15 cable coils instead of 30, since you can only stack up to 15 now
Also removes the hidden requirement for both oxygen tanks to be red to match the sprite. Sure it's weird for your blue oxygen tank to suddenly turn red, but it's better than having to code-dive to figure out why your oxygen tanks don't work

Tested, was able to craft successfully

## Why It's Good For The Game
Lets you craft the jetpack again

## Changelog
:cl: Shaps/Ryll
fix: Improvised jetpacks can be crafted with 15 cable coils instead of 30
/:cl:

2019-06-24 16:29 UTC, Detective-Google commented
Nice

2019-06-26 11:55 UTC, nemvar commented on code/datums/components/crafting/recipes.dm
> +	reqs = list(/obj/item/tank/internals/oxygen = 2, /obj/item/extinguisher = 1, /obj/item/pipe = 3, /obj/item/stack/cable_coil = 15)
#44784 is changing the max stack size back to 30.
```suggestion
	reqs = list(/obj/item/tank/internals/oxygen = 2, /obj/item/extinguisher = 1, /obj/item/pipe = 3, /obj/item/stack/cable_coil = MAXCOIL)

2019-06-29 09:10 UTC, optimumtact commented
The max stack size was chagned back

2019-06-29 09:13 UTC, 81Denton requested changes
You can just apply nemvar's suggestion and we're good to merge this

2019-06-29 14:39 UTC, Shapsy commented
blorf hold on

2019-06-29 16:09 UTC, Shapsy commented
i did it @81Denton :DD

2019-07-01 18:52 UTC, 81Denton approved these changes

2019-07-01 18:52 UTC, merged