Tweaks the damage that podpeople take from being low on food
tgstation/tgstation pull request #44839
Opened 2019-06-26 22:42 UTC by ATH1909

## About The Pull Request

Makes the damage that podpeople take from being low on food to be more consistent with the damage that shadowpeople take from being in light by making it not affect non-organic limbs (why would a podperson starving cause their prosthetic limbs to begin to shrivel up?) and making it be a mixture of brute and burn damage (instead of just brute damage).

## Why It's Good For The Game

I was doing some codediving for Crosoak over on the /tg/station Discord when I discovered that the damage that podpeople take from being low on food didn't only affect organic limbs like their healing from being in light (and the healing from being in a coffin that vampires get, the healing from being in darkness that shadowpeople get, and the damage from being in light that shadowpeople get) did. This PR changes that to be more consistent with other racial damage and healing over time. It also changes the damage done by it from two brute damage per tick to one brute damage and one burn damage per tick(,) to match the damage that shadowpeople (the "opposites" of podpeople, IMO) take from being in light.

## Changelog
:cl: ATHATH
tweak: podpeople now take 1 brute damage per tick and 1 burn damage per tick while low on food instead of 2 brute damage per tick
fix: the damage that podpeople take while low on food now only affects their organic limbs
/:cl:

2019-06-26 22:47 UTC, ATH1909 commented
Aw shoot, I forgot about wood golems. Hold on a moment.

2019-06-26 22:48 UTC, nemvar commented
I've never taken damage from hunger as a podperson. It seems almost impossible because it takes a good few minutes in the dark before you even start starving and you are almost instantly at full nutrition from being in the light.

2019-06-26 22:49 UTC, tralezab commented
just do the fix, it's much harder to stay away from light than it is to stay away from darkness and the damage reflects that.

I don't even get what you mean by making the damage this species takes "consistent", that makes no sense

2019-06-26 22:50 UTC, ATH1909 commented
There, I also applied the change to wood golems and edited the changelog.

2019-06-26 22:53 UTC, ATH1909 commented
> just do the fix, it's much harder to stay away from light than it is to stay away from darkness and the damage reflects that.
> 
> I don't even get what you mean by making the damage this species takes "consistent", that makes no sense

Compare the current spec_life() of a podperson to the spec_life() of a shadowperson:
```
/datum/species/pod/spec_life(mob/living/carbon/human/H)
	if(H.stat == DEAD)
		return
	var/light_amount = 0 //how much light there is in the place, affects receiving nutrition and healing
	if(isturf(H.loc)) //else, there's considered to be no light
		var/turf/T = H.loc
		light_amount = min(1,T.get_lumcount()) - 0.5
		H.adjust_nutrition(light_amount * 10)
		if(H.nutrition > NUTRITION_LEVEL_ALMOST_FULL)
			H.set_nutrition(NUTRITION_LEVEL_ALMOST_FULL)
		if(light_amount > 0.2) //if there's enough light, heal
			H.heal_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjustToxLoss(-1)
			H.adjustOxyLoss(-1)

	if(H.nutrition < NUTRITION_LEVEL_STARVING + 50)
		H.take_overall_damage(2,0)
```
```
/datum/species/shadow/spec_life(mob/living/carbon/human/H)
	var/turf/T = H.loc
	if(istype(T))
		var/light_amount = T.get_lumcount()

		if(light_amount > SHADOW_SPECIES_LIGHT_THRESHOLD) //if there's enough light, start dying
			H.take_overall_damage(1,1, 0, BODYPART_ORGANIC)
		else if (light_amount < SHADOW_SPECIES_LIGHT_THRESHOLD) //heal in the dark
			H.heal_overall_damage(1,1, 0, BODYPART_ORGANIC)
```
Shadowpeople take_overall_damage(1,1, 0, BODYPART_ORGANIC) under their "bane" condition (being in light), while podpeople take_overall_damage(2,0) under their "bane" condition (being low on food).

2019-06-26 22:56 UTC, ATH1909 commented
Perhaps in a future PR I could make podpeople take damage in darkness instead of just while they're low on food, but that's a pretty big balance change for them and this is a fix/tweak PR.

2019-06-26 23:29 UTC, ATH1909 commented
> Perhaps in a future PR I could make podpeople take damage in darkness instead of just while they're low on food (to further mirror shadowpeople), but that's a pretty big balance change for them and this is a fix/tweak PR.

Actually, should I just close this PR and go with this PR idea? I think the code that I've written up for it should work:

```
/datum/species/shadow/spec_life(mob/living/carbon/human/H)
	var/turf/T = H.loc
	if(istype(T))
		var/light_amount = T.get_lumcount()
		if(light_amount > SHADOW_SPECIES_LIGHT_THRESHOLD) //if there's enough light, start dying
			H.take_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjust_nutrition(-2)
		else if (light_amount < SHADOW_SPECIES_LIGHT_THRESHOLD) //heal in the dark
			H.heal_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjustToxLoss(-1)
			H.adjustOxyLoss(-1)
			H.adjust_nutrition(2)
	if(H.nutrition > NUTRITION_LEVEL_ALMOST_FULL)
		H.set_nutrition(NUTRITION_LEVEL_ALMOST_FULL)
```

```
/datum/species/pod/spec_life(mob/living/carbon/human/H)
	var/turf/T = H.loc
	if(istype(T))
		var/light_amount = T.get_lumcount()
		if(light_amount < SHADOW_SPECIES_LIGHT_THRESHOLD) //if there's not enough light, start dying
			H.take_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjust_nutrition(-2)
		else if (light_amount > SHADOW_SPECIES_LIGHT_THRESHOLD) //heal in the light
			H.heal_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjustToxLoss(-1)
			H.adjustOxyLoss(-1)
			H.adjust_nutrition(2)
	if(H.nutrition > NUTRITION_LEVEL_ALMOST_FULL)
		H.set_nutrition(NUTRITION_LEVEL_ALMOST_FULL)
```

```
/datum/species/golem/wood/spec_life(mob/living/carbon/human/H)
	var/turf/T = H.loc
	if(istype(T))
		var/light_amount = T.get_lumcount()
		if(light_amount < SHADOW_SPECIES_LIGHT_THRESHOLD) //if there's not enough light, start dying
			H.take_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjust_nutrition(-2)
		else if (light_amount > SHADOW_SPECIES_LIGHT_THRESHOLD) //heal in the light
			H.heal_overall_damage(1,1, 0, BODYPART_ORGANIC)
			H.adjustToxLoss(-1)
			H.adjustOxyLoss(-1)
			H.adjust_nutrition(2)
	if(H.nutrition > NUTRITION_LEVEL_ALMOST_FULL)
		H.set_nutrition(NUTRITION_LEVEL_ALMOST_FULL)
```

Said code would make podpeople and wooden golems gain nutrition and heal in light and lose nutrition and take damage(!) in darkness (with the inverse applying for shadowpeople and nightmares). Also, shadowpeople and nightmares would become unable to get fat (to match podpeople and wooden golems). As another side effect, the regen of podpeople and wooden golems would apply while they're dead (to match the regen of shadowpeople and nightmares (and vamps who are in coffins)), but I could change this under the argument that most plants don't grow/heal while dead (if we wanted to go the other way, I could make alien golems regen while dead too).

Any thoughts on this?

2019-06-27 12:30 UTC, nicbn commented
It doesn't work like that, leaving a plant in the darkness for like less than a week won't kill it
If you want to make life for podpeople more of a pain without resorting to nonsense, you could require them to be watered from time to time (by either drinking water or showering, with the penalty of drying out )

2019-06-27 19:24 UTC, ATH1909 commented
> It doesn't work like that, leaving a plant in the darkness for like less than a week won't kill it
> If you want to make life for podpeople more of a pain without resorting to nonsense, you could require them to be watered from time to time (by either drinking water or showering, with the penalty of drying out )

Don't humans also need to be "watered", though? We don't have a thirst system for humans, so why should we have one for podpeople?

2019-07-05 00:01 UTC, SpaceManiac requested changes
Pretty sure the arguments to `take_overall_damage` are incorrect here. 4th argument is `updating_health`, not `required_status`.

2019-07-08 17:48 UTC, ExcessiveUseOfCobblestone commented
> Perhaps in a future PR I could make podpeople take damage in darkness instead of just while they're low on food (to further mirror shadowpeople), but that's a pretty big balance change for them and this is a fix/tweak PR.

The tweak IS balance.

this should just be a fix PR unless you're telling me to merge/close only on the merits of the balance change, and I see no reason to do that right now.

2019-07-08 17:49 UTC, closed without merging