Fixes radiation wave runtime.
tgstation/tgstation pull request #45075
Opened 2019-07-08 22:20 UTC by nemvar

¯\_(ツ)_/¯ get_step sometimes returns null and I'm not sure why. This should fix the runtime though.

2019-07-08 23:11 UTC, optimumtact commented
this doesn't fix anything, it suppresses the runtime which is silly

2019-07-09 11:09 UTC, mrhugo13 commented
> 
> 
> this doesn't fix anything, it suppresses the runtime which is silly

Don't you get it Oranges? We must supress the anti-gamer-karen-runtimes.

2019-07-09 12:01 UTC, Dennok commented
It runtime if try to out of bounds of map?
So what fix for this can be?

2019-07-09 13:41 UTC, nemvar commented
Does it really just surpress the runtime if it's consistent with how rad waves work otherwise?

2019-07-09 20:25 UTC, ninjanomnom commented
This isn't suppressing anything bad, radiation waves check that they arent exiting the map in the primary direction of movement but I forgot to add a check for when the width goes outside map bounds

2019-07-09 20:26 UTC, optimumtact commented
yeah but shouldn't you check instead, rather than supressing it all the way here

2019-07-09 20:26 UTC, ninjanomnom requested changes

2019-07-09 20:26 UTC, ninjanomnom commented on code/datums/radiation_wave.dm
> +				atoms += get_rad_contents(place)
If you hit a null location you don't need to continue trying this direction, you can skip to the next one. Break out of this loop instead
```
if(!place)
  break
```

2019-07-09 20:27 UTC, ninjanomnom commented
This is where the check should happen, it's just doing a slightly wrong thing because of the check at the moment. A break there makes it stop trying to get locations off the map edge

2019-07-10 03:04 UTC, kriskog commented
\\\¯\\\_(ツ) you dropped this

2019-07-10 11:56 UTC, nemvar commented
¯ \_(ツ)_/¯

2019-07-10 13:25 UTC, ninjanomnom approved these changes

2019-07-10 13:25 UTC, merged