Job specific ID cards
tgstation/tgstation pull request #45112
Opened 2019-07-10 16:23 UTC by Alek2ander

## About The Pull Request
Inspired by #45051

- Changes ID card sprites and adds overlays for every station job with secHUD icons and department-colored barcodes, as well as department budget card sprites with colored stickers for each department.
- The emag is also changed to fit the same shape. (unsure about this)
- Changes the wallet to fit the new ID sprite and makes the ID icon visible through it
- Improves ID card naming consistency
![ids](https://user-images.githubusercontent.com/5909770/60985862-f41b9f80-a346-11e9-8f24-a39e5f4ab680.png)

## Why It's Good For The Game
>A lot of other servers have job specific ID cards. Helps in quick identification of access tied to cards or job identification of unknown individuals.

>A nice bit of QOL I'd think.

## Changelog
:cl: Alek2ander and Triiodine
imageadd: "Nanotrasen released brand-new adaptive ID cards with colorful displays. Now you can see a crew member's assignment without the need to examine any small print."
imageadd: "The Syndicate immediately responded by printing their notorious cryptographic sequencer in a new form-factor."
imageadd: "Wallet ID windows are now twice as big to show the new ID cards in all thri glory."
/:cl:

2019-07-10 17:20 UTC, nicbn commented
How can you change the ID skin ingame?

2019-07-10 17:27 UTC, Alek2ander commented
@nicbn It's tied to the job on the ID, so any access modification console can do it. 
Making it fully customizable would be a balance change I'd rather PR separately after this is merged.

2019-07-10 17:27 UTC, Swiftkor commented
I really like these sprites, they’re a lot more vibrant than the last pr

2019-07-10 18:27 UTC, Kmc2000 commented
Sweet

2019-07-10 18:35 UTC, Akrilla commented
Fuck yeah

2019-07-10 20:16 UTC, ExcessiveUseOfCobblestone commented
> Lawyer 
>> Security

2019-07-10 21:13 UTC, zxaber commented
I wonder if you could overlay the job hud icon onto the card sprite?

The only real advantage, I suppose, would be that if new jobs are created, no one has to add custom IDs alongside everything else.

2019-07-10 22:09 UTC, ExcessiveUseOfCobblestone commented
don't tell her anons

2019-07-11 05:22 UTC, Alek2ander commented
@ExcessiveUseOfCobblestone Lawyers crave donuts, that's proof right there
@zxaber I'll switch to actual secHUD overlays and color-blended accents when I get around to making IDs customizable

2019-07-11 15:26 UTC, ExcessiveUseOfCobblestone commented
They're TECHNICALLY under the jurisdiction of the HoP (Service dept?) but *shrug*

2019-07-12 23:19 UTC, wesoda25 commented
Why aren’t there silver variants for everything? Just because its silver doesn’t mean it’s always a head role. Or did you just not bother including that stuff?

2019-07-13 05:22 UTC, Alek2ander commented
Normal, silver and gold IDs can have any job overlay.

2019-07-13 09:48 UTC, actioninja requested changes

2019-07-13 09:48 UTC, actioninja commented on code/game/objects/items/cards_ids.dm
> +		return "[costly_icon2html(src, user)] [thats? "That's ":""][get_examine_name(user)]" //displays all overlays in chat
cache the result of costly_icon2html, it calls getflaticon which is very expensive

2019-07-13 09:48 UTC, actioninja commented on code/game/objects/items/storage/wallets.dm
> +	return "[costly_icon2html(src, user)] [thats? "That's ":""][get_examine_name(user)]" //displays all overlays in chat
same for this

2019-07-13 09:48 UTC, actioninja commented on code/modules/economy/account.dm
> +				to_chat(card_holder, "[costly_icon2html(A, card_holder)] *[message]*")
_especially_ for these

2019-07-13 09:48 UTC, actioninja commented on code/modules/economy/account.dm
> +				A.audible_message("[costly_icon2html(A, hearers(A))] *[message]*", null, 1)
same

2019-07-13 09:48 UTC, actioninja commented on code/modules/economy/account.dm
> +					to_chat(M, "[costly_icon2html(A, M)] *[message]*")
same

2019-07-13 20:35 UTC, actioninja approved these changes

2019-07-14 04:24 UTC, merged