Adds a New Drink, the Flaming Homer
tgstation/tgstation pull request #45228
Opened 2019-07-16 20:04 UTC by wesoda25

## About The Pull Request

Adds a new drink, the flaming homer. 

source: 
![image](https://user-images.githubusercontent.com/37246588/61325689-42b3b880-a7e3-11e9-952a-082c8d611781.png)

## Why It's Good For The Game

More drinks are fun. 

## Changelog
:cl:
add: A new drink, the Flaming Homer
/:cl:

unabashed reference code, which I normally dislike, almost didn't make the PR bc of it. but I think its fun and doesn't really ruin immersion at all, if you want I could change the Homer name to the name of whoever made it or something.

2019-07-16 20:06 UTC, Detective-Google commented
more drink more better 👍

2019-07-16 20:06 UTC, Krysonism commented
They have this on paradise but called "flaming moe".

I like this PR though.

2019-07-16 20:07 UTC, wesoda25 commented
oh i probably wont be able to fix that

2019-07-16 20:08 UTC, wesoda25 commented
> They have this on paradise but called "flaming moe".
> 
> I like this PR though.

he stoel the dirnK!!

2019-07-16 20:13 UTC, wesoda25 commented
Dammit i was using an older version of the drink sprites ill fix that later

2019-07-16 20:27 UTC, fludd12 commented
You could make it a combination VA-11HALL-A and Simpsons reference with the Flaming Moai drink, if you wanted.

2019-07-16 21:18 UTC, optimumtact commented
We're reaching the point where more drinks == better is not actually true

2019-07-16 21:41 UTC, wesoda25 commented
> We're reaching the point where more drinks == better is not actually true

I disagree. I've been playing chef and bartender pretty often later and new content is always welcome. I believe its a different issue than chemical bloat.

2019-07-16 21:45 UTC, OverlyGeneric commented
> You could make it a combination VA-11HALL-A and Simpsons reference with the Flaming Moai drink, if you wanted.

I am moyai and I approve of this message.

2019-07-16 23:50 UTC, Krysonism commented
> 
> 
> We're reaching the point where more drinks == better is not actually true

Disagree, even if a drink is identical to another it will still improve bar gameplay by offering a new sprite and taste description. 

Variety is very important for the bar or kitchen gameplay.

2019-07-17 00:21 UTC, optimumtact commented
\>I disagree

good for you

2019-07-17 00:58 UTC, wesoda25 commented
Sorry oranges I figured you might value the opinion of people who play the roles these pieces of code interact with.

2019-07-17 02:23 UTC, dr-bee commented
Does this actually do anything? because there already is a flaming drink and its the toxins special. Which isnt a reference to something that has no relationship to space or sci-fi.

2019-07-17 05:14 UTC, Dennok commented
Make it name from name of creator like "flaming [creator.name]"

2019-07-17 06:06 UTC, wesoda25 commented
> Make it name from name of creator like "flaming [creator.name]"

Ya I was considering that if people had a big issue with the reference

> Does this actually do anything? because there already is a flaming drink and its the toxins special. Which isnt a reference to something that has no relationship to space or sci-fi.

ya it makes you drunk bc its an alcoholic beverage

2019-07-17 15:42 UTC, ExcessiveUseOfCobblestone requested changes
you reverted a few drink sprites

2019-07-17 15:45 UTC, ExcessiveUseOfCobblestone commented
If drinks should be added they should have a unique aspect to them besides the name and sprite imo.

2019-07-17 19:42 UTC, wesoda25 commented
I mean if maintainers don’t like it I’ll just close the PR. As I said, I was conflicted on PRing it in the first place so it won’t really tear me up.

2019-07-17 23:11 UTC, 81Denton commented on code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +	required_reagents = list(/datum/reagent/consumable/ethanol/tequila = 5, /datum/reagent/consumable/ethanol/creme_de_menthe = 5, /datum/reagent/medicine/spaceacillin = 1) //spaceacillan standing in fo
Imo replace spaceacilin with morphine since both codeine and morphine are opiates

2019-07-18 04:31 UTC, plapatin commented
why cant we have more chef recipes instead of more drink recipes, chef's barely gotten any love lately

2019-07-18 04:37 UTC, wesoda25 commented
> why cant we have more chef recipes instead of more drink recipes, chef's barely gotten any love lately

i might add some new donut types [tm]

2019-07-18 21:23 UTC, closed without merging