Replaces cables with redstone
tgstation/tgstation pull request #45235
Opened 2019-07-17 13:11 UTC by Kmc2000

## About The Pull Request

Hi /tg/! It's me again

I've seen a lot of buzz about "smart cables" recently and well, when I looked at them I knew exactly what needed to be done.

Several players have complained that they're too simple to use, and I think they're on to something. So in return, I've made them thematically much more in-line with how they feel to use in game. Working with redstone in ss13 makes a lot more sense because of how easy it is to place these cables, and how they end up linking.

Demo video:
https://streamable.com/lbtz2

I do hope that you'll consider this pull request and give constructive feedback so that we can make truly epic redstone piston houses on /tg/.

## Why It's Good For The Game

The way cables link feels inconsistent and out of place. This replaces them with something I'm more used to so that the mechanic of autocompleting cables makes more sense.

## Changelog
:cl: Kmc2000
fix: Cables have been replaced by redstone
/:cl:

2019-07-17 13:15 UTC, 1fbff5f83b23d39d38b1dfcb4cac8d9b commented
Make them bright red and glowing when charged

2019-07-17 15:05 UTC, nemvar commented
:-1: Didn't change ``MAXCOIL`` to 64

2019-07-17 15:10 UTC, dr-bee commented
Keep this for april fools. this is gold!

2019-07-17 15:19 UTC, wesoda25 commented
God bless

2019-07-17 15:29 UTC, nemvar commented on code/modules/power/cable.dm
>  	singular_name = "cable piece"
:eyes:

2019-07-17 16:24 UTC, GalacticSwan commented
finally, some good fucking updates

2019-07-17 16:50 UTC, ishitbyabullet commented
unironically make it a subtype of cable.

2019-07-17 16:51 UTC, mrhugo13 commented
if oranges doesn't merge this then orange man bad eternal

2019-07-17 16:54 UTC, ishitbyabullet commented
he doesn't have to merge the meme of renames and complete cable replacement.

but redstone being a type of cable that we could spawn would be funny as fuck.

2019-07-17 16:55 UTC, mrhugo13 commented
also
>April  Fools
Is there not a Late April Fools tag?
Smh what are you /TG/ people doing over there?

2019-07-17 18:34 UTC, 81Denton commented on code/modules/power/cable.dm
>  	singular_name = "cable piece"
lol

2019-07-17 18:57 UTC, Dorsisdwarf commented
This is the best PR

2019-07-17 20:44 UTC, zxaber commented
At least the four-way crosses will look decent.

2019-07-17 21:13 UTC, CRITAWAKETS commented
This should be able to be made post-april 1st via a recipe involving bronze dust, gold dust and plasma.

2019-07-17 22:35 UTC, PolithunIvan commented
Okay this is epic

2019-07-18 10:06 UTC, ShizCalev requested changes

2019-07-18 10:06 UTC, ShizCalev commented on code/modules/power/cable.dm
>  	singular_name = "cable piece"
fix this and i'll merge it.

2019-07-18 10:55 UTC, closed without merging

2019-07-18 11:08 UTC, Kmc2000 commented on code/modules/power/cable.dm
>  	singular_name = "cable piece"
fix how?

2019-07-18 11:34 UTC, 81Denton commented
We're not worthy