Removes warops challenge item from the syndicate commander
tgstation/tgstation pull request #45307
Opened 2019-07-21 01:17 UTC by optimumtact

This mode is literally a team deathmatch, and encourages players to ignore normal station roles and act like idiots instead.

This server isn't a full on deathmatch, people are expected to follow command authority and not murder the captain because he has the disk and isn't playing how they think warops should be played.

I believe this mode is deeply damaging to the character of this server and therefore I am removing it before it can do any more damage.

2019-07-21 01:18 UTC, BOBAMAx commented
bruh

2019-07-21 01:18 UTC, trexter555 commented
how about admins do their job when people are being shitters instead of removing a core part of nukeops

2019-07-21 01:20 UTC, ishitbyabullet commented
Oranges has no faith in that happening. That's why he went straight to this option.

2019-07-21 01:20 UTC, ayebee123 commented
holy shit he wasn't fucking kidding i thought it was a joke

2019-07-21 01:21 UTC, nonfictiongames commented
good change here
war ops = cancerous TDM shit

2019-07-21 01:22 UTC, optimumtact commented
The appveyor build failure is a spurious unrelated issue.

2019-07-21 01:24 UTC, cacogen commented
I don't even really like war ops but this is kneejerk, self-serving coding if I ever saw it. You didn't even play the round that prompted this. I hardly ever see you on the actual servers to begin with.

2019-07-21 01:25 UTC, SynnGraffkin commented
On that note, can we just remove Revolutionaries? It just turns the station into Team Deathmatch and people ignore station roles to just be idiots instead. 

But on a serious note, a code change like this shouldn't be required and if people are being shitters during War Ops, that should require admin intervention instead of a full code change like this. This is kind of proof about the separation between admins and coders. 

Coders: "Can't expect admins to do their job, so let's just remove stuff." 

What the hell are ops supposed to do in order to purchase extremely expensive syndicate equipment, such as mechs? Trade their crystals on an already small budget without war for such an item?

2019-07-21 01:25 UTC, optimumtact commented
What about it is self serving, im acting in what I believe to be the servers best interest here.

2019-07-21 01:26 UTC, Gamer025 commented
How about adding a ingame poll before merging this pull request?

2019-07-21 01:26 UTC, optimumtact commented
It's quite obvious the change will be wildly unpopular but I don't believe that changes the fact of it being necessary or not.

2019-07-21 01:27 UTC, cacogen commented
>How about adding a ingame poll before merging this pull request?

Exactly, you'd get a consensus or at least make a feedback thread first if you were acting in the server's best interest and not just in the interest of how you think the server should be.

2019-07-21 01:27 UTC, ayebee123 commented
wouldn't some mechs need to be removed, as they need warops activated to be bought?

2019-07-21 01:30 UTC, ishitbyabullet commented
war op removal doesn't mean they're 100% useless and must be gone.

We wouldn't have the reticence if that was true.

2019-07-21 01:36 UTC, dee-dubya commented
Sure, let's also remove conversion modes, wizard, and regular ops while we're at it too. After all, they're all just glorified TDMs as well, except unlike war ops, players actually have legitimate excuses to be utter shitbaskets to one another.

War ops is unique in the fact that it's the only "TDM mode" where the entire crew is given fair warning and are expected to be fully cooperative in their goal of keeping the disk secure and getting off the station ASAP. If certain players can't handle that responsibility, that's not the job of coders to deal with, it's the job of administration to deal with the select individuals ruining the experience, rather than punishing the entire server by removing a mode that is fairly well liked, unique, and somewhat balanced.

obligatory "orang men badd"

2019-07-21 01:38 UTC, optimumtact commented
The difference in those modes is that people dont' immediately abandon all pretence of it being a spacestation simulator and start murdering anyone who isn't helping them kill warops in the most optimally efficient manner.

If I believed a change in admin policy would help, I would have gone there, but I doubt it very much.

2019-07-21 01:40 UTC, NoxVS commented
Nuke ops in general is a team death match mode. There are two teams. Both teams have the goal of killing the other team. Without war ops its still a team death match mode except it tends to be over before the crew can do anything. Yeah people abandon their jobs but they do that because there is no point in doing a job when the round can just end instantly which is just the nature of not only nuke ops but also wizard, revs, cult, and hivemind. 

Removing war ops wont fix the problem you have here, it will just mean most nuke op rounds end abruptly for most of the server.

2019-07-21 01:41 UTC, optimumtact commented
Warops has lead to an incredibly entitled culture from the players who are playing during it.

No other mode has that level of entitlement at all, the only one that even gets close is wizard.

Why should I do nothing about this?

2019-07-21 01:42 UTC, dee-dubya commented
If crew are murdering other crew during a confirmed war ops round, that's an administration issue. At least ATTEMPT to have the problem solved through admin intervention or changes to admin policy before removing options for players. If administration proves to be incapable more often than not on that specific issue, only then should you remove the option entirely. Knee jerk reactions to fringe issues like this make nobody happy in the long run.

2019-07-21 01:44 UTC, optimumtact commented
it's not a fringe issue, it's incredibly serious, that kind of entitlement and player behaviour will (and likely already is) bleeding into the rest of the community and the other gamemodes.

What convincing argument do you have that admins are capable of preventin this? They have already failed to do so apparently.

2019-07-21 01:45 UTC, NoxVS commented
What problem do you think exists here? I don't see it really.

2019-07-21 01:45 UTC, optimumtact commented
^ exhibit A

2019-07-21 01:45 UTC, wesoda25 commented
I fucking hate war ops like nothing else but its a core part of SS13 not to mention TG and should not be removed. Its one of the few gamemodes where total teamwork is required to win, which is why you seem to think it eliminates crew roles. Its not damaging whatsoever to “the image of TG” or whatever other reason you seem its appropriate to remove it for. How the fuck does people working together degrade from the server?

2019-07-21 01:46 UTC, YakumoChen commented
>wouldn't some mechs need to be removed, as they need warops activated to be bought?

They existed long before warops, you still see them bought on non-war rounds as well (usually at a discount)

2019-07-21 01:46 UTC, NoxVS commented
Im just asking what problem you see with the game that has to be fixed by this.

2019-07-21 01:46 UTC, optimumtact commented
It is not a core part of ss13, dispense with that nonsense right now.

It's existed since 2015 only

2019-07-21 01:47 UTC, dee-dubya commented
The fact that the vast majority of nuke ops rounds seem to pass without a hitch is reason enough in my eyes. "No news is good news" applies here. If 1/10 nuke ops rounds wind up being an issue, does that truly warrant removing the other 9/10 issue free nuke ops rounds with it?

2019-07-21 01:47 UTC, Yttriums commented
War ops is fun. Change balance and add content to encourage station-side cooperation and give people ways to contribute meaningfully to the fight from all roles. There's something unique about how the mode feels like a time trial for the station to get as robust as possible, so I hope it isn't scrapped.

2019-07-21 01:48 UTC, Swagile commented
I think others have a point here that the crew acts the same in other similar conversion modes.

In hivemind, everyone rushes to get implanted so they can find the hiveminder and all rush out with guns to end them immediately lest hivemind One Minds and rolls the crew.

In Rev, rev rushes normal crew to get converts, and sec rushes cargo to mass arm up and implant loyalists then rush anyone who refuses to comply with maximum harm baton lest they get overwhelmed by rev.

In Cult, the same thing happens; loyal crew try to get implanted and armed (because deconversion is a joke and waiting for Halo'd cult is the best meta strategy right now) then rush out and murderbone anyone with a halo then cremate / gib them to prevent revive because cult is bullshit and can insta revive people and teleport them across the map.

2019-07-21 01:49 UTC, optimumtact commented
Yes but none of them are quite as obvious or as bad as warops, it's the flagship for the powergaming, valid hunting  meta bullshit we see from some people

2019-07-21 01:50 UTC, bigfatbananacyclops commented
Hello, i was a witness of how probably the cap got fucked over, i think oranges really lacks context and didnt see everything else that happened.

When the ops declared war i went to the captain office and the clown for some reason was tabling the captain, trying to take his ID, i tried to tell him to stop and just let him give us access, i shaked up the captain and the clown went into the room, gave himself access, then the captain charged towards the clown with his rapier, meanwhile he was doing that, i was just giving my self AA with the card the clown left in the console, the captain then began to start sabering me even after i helped him, after i left, i have no idea what else happened.

War has always been a death match and obviously it will encourage people to arm up and defend themselves, thats part of the fun of this gamemode and alot of people likes it. rare for me to see someone disliking it, mostly those are just people who wants everyone to have limited access and just fight ops with a cargo gun, nothing else.

``encourages players to ignore normal station roles and act like idiots instead.``
is this a reference to the previous round where security executed 15 assistants including some of them being cuffed and incapable of fighting back?

2019-07-21 01:50 UTC, Wilchenx commented
Make this a config

2019-07-21 01:51 UTC, optimumtact commented
I could make it it's own gamemode to make it a config

2019-07-21 01:51 UTC, Swagile commented
> 
> 
> Yes but none of them are quite as obvious or as bad as warops, it's the flagship for the powergaming, valid hunting meta bullshit we see from some people

Hivemind is obvious; pink halos and a One Mind that can insta convert people.

Rev is obvious; flashes start going off and immediately sec goes on lockdown and arm up mode.

Cult is obvious; you see a rune, and instantly sec and crew go into a blitz.

The only difference is its a conversion gamemodes, meaning some people either willingly or unwillingly get converted so not the ENTIRE crew works together, whereas in War Ops there is no possible conversion; its do or die, you or them, so everyone works together.

But make no mistake they are just as bad as nuke ops, if not worse in some cases (cult, hivemind).

2019-07-21 01:52 UTC, NoxVS commented
Roles and authority shouldnt even matter in situations like war ops because there is no qualification for being that role or whatever. You click a button and you are it. Of course the crew doesnt respect authority when its usually an incompetent power tripping loser who ends up in command or security.

Whats wrong with an assistant running around with the disk? Is fun only allowed for the nukies and command/sec during nuke rounds? Because those are the only people who have fun in normal nuke rounds where the rest of the crew is entirely unequipped and the round usually ends before any of them even get a gun.

2019-07-21 01:52 UTC, optimumtact commented
@bigfatbananacyclops this isn't a ban appeal and nothing you said actually makes what happened any more or less valid, also I have no issue with that previous brig round.

2019-07-21 01:53 UTC, Wilchenx commented
@NoxVS not sure about your downstream but we have playtime requirements as well as minimal effort requirement for headroles.

2019-07-21 01:53 UTC, optimumtact commented
Nox's comment is pretty much the entire reason to remove this mode.

2019-07-21 01:54 UTC, dee-dubya commented
> The thing damaging is the kind of player behaviour where they will murder the captain, take the disk of them and run around with all access as an assistant because that's apparently the acceptable meta of the mode, where by the roles and authority on station don't matter, only who is most robust.

What in the god damn? Where exactly do you get this from? I am going to ask the following question as non-offensively as possible: Do you actually play the game? I have sat through so many goddamn war ops rounds, and this basically never happens. Last time I personally witnessed this happening was half a year ago, and the round end got delayed due to a lengthy bwoinking(probably because of this issue).

Every war ops round I've been part of, the Captain and HOS's orders have been followed as gospel by nearly the entire crew. Nobody commits any grief on purpose. It's a surprising rarity, honestly. That's why I'm so baffled by this sudden PR and your view of "entitled grayshits robusting the captain" being the accepted meta for war ops. I don't see this anywhere, and as such I don't see the point in this PR at all.

2019-07-21 01:55 UTC, optimumtact commented
I don't believe you at all, if people felt able to do that on a prime time basil round with admins online then it's definitely the standard meta.

2019-07-21 01:55 UTC, Ty-the-Smonk commented
> > The thing damaging is the kind of player behaviour where they will murder the captain, take the disk of them and run around with all access as an assistant because that's apparently the acceptable meta of the mode, where by the roles and authority on station don't matter, only who is most robust.
> 
> What in the god damn? Where exactly do you get this from? I am going to ask the following question as non-offensively as possible: Do you actually play the game? I have sat through so many goddamn war ops rounds, and this basically never happens. Last time I personally witnessed this happening was half a year ago, and the round end got delayed due to a lengthy bwoinking(probably because of this issue).
> 
> Every war ops round I've been part of, the Captain and HOS's orders have been followed as gospel by nearly the entire crew. Nobody commits any grief on purpose. It's a surprising rarity, honestly. That's why I'm so baffled by this sudden PR and your view of "entitled grayshits robusting the captain" being the accepted meta for war ops. I don't see this anywhere, and as such I don't see the point in this PR at all.

from what I heard he witnessed one round of this and decided to throw the whole mode out

2019-07-21 01:55 UTC, carshalash commented
> I don't believe you at all, if people felt able to do that on a prime time basil round with admins online then it's definitely the standard meta.

Dude what

2019-07-21 01:56 UTC, optimumtact commented
that's not very convincing

2019-07-21 01:57 UTC, Arathianen commented
War Ops is not a "challenge". It's an option. Nukies get more TC for declaring war in exchange for facing a more prepared station.

I DEEPLY dislike this change. 

Since it's you Oranges, I will present some reasons why I believe this is a bad change:

1) it removes a real choice between less TC but element of surprise or loud and better equipped.

2) you claim that the prep and dissolution of command is "bad for the game" but...why? It's a unique war mode where everyone prepares to the full extend of their ability. Miners rush cash, sci researches guns, engineers build walls and barricades, HoP pumps out AAs etc Obviously it's not a normal round but is having a different round every now and then objectively bad? I strongly disagree and I believe it's a great thing.

3) this is already semi-solved with dynamic where other antags beside nukies might exist. People might have to think twice before handing out mass AA. This is an unnecessary change when we got dynamic.

All in all, you seem to have made your mind up, but strong -1

2019-07-21 01:58 UTC, dee-dubya commented
So a handful of shitters on the server known for having the least amount of fucks given to decent RP and gameplay standards(bagil) during one round is reason enough for you to toss the entire mode out? I'd ask if you were joking, but the fact that this PR even exists is evidence that you're actually serious.

Like I said before, sit on it for a while. Weeks, a month, two months. If the issue continues to repeat itself to an alarming degree, take action then and only then.

2019-07-21 01:58 UTC, NoxVS commented
The whole round is a team death match. Normal nuke ops is a team death match. The only problem is only a handful of people get to have fun while the rest just twiddle their thumbs until the round ends. But apparently you are entitled if you want to have fun and be involved in the team death match mode rather than do your job for 20 minutes and then the round ends.

2019-07-21 01:59 UTC, nervere commented
Warops is a boring deathmatch gamemode that is the same every shift:
- 0-5 minutes: Warops declare
- 5-20 minutes: Crew gets all access and lynches anyone who tries to stop them, loots armory and anything else valuable.
- 20-25 minutes: Crew finishes barricades as warops arrive, ~10-15% of the crew is already dead of suicide to escape the awful gamemode or because of deaths related to tiding.
- 25-30 minutes: Shuttle is called, red-alerted, shuttle arrives at 30 minute mark.
- 35-40 minutes: Shift ends prematurely from warop death or another 5 minutes are wasted on time to depart/arrival at central command.

There is never any roleplay. There is never any chance to do your job because everyone is tiding.
It's not an administrative issue, it's inherent to the gamemode. No amount of rules will make players stop being feral apes when nukeops with 500TC are about to arrive on the station.

It is 100% focused on combat, nothing else, and has no place in a roleplaying game.
I fully support the removal of the war challenge mode.

2019-07-21 01:59 UTC, optimumtact commented
there's no reason to sit on it, waiting six months wont' change what this gamemode is about.

2019-07-21 01:59 UTC, Swagile commented
> 
> 
> > The thing damaging is the kind of player behaviour where they will murder the captain, take the disk of them and run around with all access as an assistant because that's apparently the acceptable meta of the mode, where by the roles and authority on station don't matter, only who is most robust.
> 
> What in the god damn? Where exactly do you get this from? I am going to ask the following question as non-offensively as possible: Do you actually play the game? I have sat through so many goddamn war ops rounds, and this basically never happens. Last time I personally witnessed this happening was half a year ago, and the round end got delayed due to a lengthy bwoinking(probably because of this issue).
> 
> Every war ops round I've been part of, the Captain and HOS's orders have been followed as gospel by nearly the entire crew. Nobody commits any grief on purpose. It's a surprising rarity, honestly. That's why I'm so baffled by this sudden PR and your view of "entitled grayshits robusting the captain" being the accepted meta for war ops. I don't see this anywhere, and as such I don't see the point in this PR at all.

Gunna have to agree with the gospel thing, I was Luca Paytner on Basil as a HoS during a War Ops round and got the disk, and by the time war ops came, I had 5 assistants around me at all times with combat shotguns or autorifles protecting me, and 5-10 other crew members wandering the hallways around Cargo where we were holding up alongside security forces. Everyone followed orders and we ended up managing to make it to escape and force call to 10 seconds after killing off every nukie except one that was probably trying to suicide escape but didn't get a chance.

Grief is rare in the times ive seen war ops, so dunno why this is really needed.

2019-07-21 02:01 UTC, wesoda25 commented
OK oranges, I can accept that the meta is problematic and should be done away with. I would tell you to address the meta itself and find a way to discourage it but since I can’t come up with any ideas myself I won’t. 

However, War Ops by far one of our most balanced game modes. Its WAY more balanced than blitz ops, which win nearly all the time. While you might be improving the server by removing it, you certainly won’t be improving the game mode.

2019-07-21 02:01 UTC, Wilchenx commented
nukeops should have alternative challenges

like kidnapping a target

2019-07-21 02:01 UTC, nervere commented
>Every war ops round I've been part of, the Captain and HOS's orders have been followed as gospel by nearly the entire crew. Nobody commits any grief on purpose. It's a surprising rarity, honestly. That's why I'm so baffled by this sudden PR and your view of "entitled grayshits robusting the captain" being the accepted meta for war ops. I don't see this anywhere, and as such I don't see the point in this PR at all.

I suicide every time warops happens because it's an awful gamemode, and as a result I see the administrative side of things.
From an administrative perspective, warops is about as bad as secret extended. There's always a ton of non-antag on non-antag murder because every validhunter is looking to secure their gamer loot to be the hero of the station and kill the warops. It is **always** a headache.

2019-07-21 02:03 UTC, NoxVS commented
People abandon their jobs and ignore the chain of authority and all that stuff because the round is going to end in less than 30 minutes. Why bother doing your job if your normal shift is tied to a team death match mode and your normal round ends the instant either team loses.

If you are going to remove war ops just remove nuke ops in general because the problem with war ops is just that the crew knows what round type they have and doing their normal job is utterly pointless

2019-07-21 02:05 UTC, optimumtact commented
We agree, but our methods of fixing the situation differ

2019-07-21 02:05 UTC, nervere commented
The beauty of SS13 shifts is that there is an opportunity and a means to create an interesting story:
This is not possible in warops. The only "story" that will come of it is someone trying to robust the warops. Cool, maybe someone will do something smart and kill a warop or two, but that's not engaging at all, and combat is not the focus of this game or server.

2019-07-21 02:06 UTC, dee-dubya commented
Furthermore, I don't see the validity behind "removing war ops will lead to a reduce in validhunting culture". The exact opposite will occur, if you ask me. In my eyes, war ops mere existence is a way for pvp hungry players to let off steam in a way that no other game mode directly encourages. I mean sure, the argument of "go play CM instead" exists, but you know the vast majority of players aren't gonna touch that. If you remove the only mode where valids are clear cut (crew vs red suit) and participating in the TDM is encouraged by everyone, then you're going to wind up with more pent up validhunting in all the other modes.

2019-07-21 02:06 UTC, granpawalton commented
not the PR the server wants but the one it needs

2019-07-21 02:06 UTC, nervere commented
>In my eyes, war ops mere existence is a way for pvp hungry players to let off steam in a way that no other game mode directly encourages

I would prefer if pvp-hungry players left our server entirely. SS13 is not the game for this kind of person.

2019-07-21 02:07 UTC, Arathianen commented
Nervere, you might dislike the mode. Ok. It's not my personal favourite either (although stealth ops is far worse. But that is another topic).

That doesn't mean it should be nuked from the skies.

Yes, there is an efficient way to do war ops. And almost all servers do it. And yeah, if a random idiot tries to stop people entering the armoury "cuz reasons" he will be lynched....because he is currently actively preventing the station's defence.

I have personally never seen people lynch the captain. 99% of the time I see the captain with a personal escort of armed to the teeth death squad ready to shoot anything red. Maybe it happened one round, but it's certainly not "nuke the mode" -worthy.

2019-07-21 02:08 UTC, Ty-the-Smonk commented
I dont like warops not gonna lie but I also dont want to see it go, I do xenobio and I cant get SHIT off of it since war ops is a 20 min prep time but the mode whenever it came up actually gave me a nice challenge to speedrun xenobio for some bullshit extracts to fuck over ops if I could. now i can only use it against cult i guess

2019-07-21 02:09 UTC, dee-dubya commented
> > In my eyes, war ops mere existence is a way for pvp hungry players to let off steam in a way that no other game mode directly encourages
> 
> I would prefer if pvp-hungry players left our server entirely. SS13 is not the game for this kind of person.

Unless you change tgstation from RP-superlite in the near future and enforce the change heavily, this isn't going to happen. Validhunting and "sacred antags" have been part of this server's culture as long as I can remember. I'm not saying I'd be opposed to breeding that culture out, but as it currently stands this change is only going to make shit worse unless player and admin policy change along with the removal of options and modes like this.

2019-07-21 02:09 UTC, imsxz commented
speedmerge please the pvp gamers are corrupting my roleplay experience

2019-07-21 02:09 UTC, zxaber commented
Truth be told, it's more fun to have twenty minutes of getting prepared for the big war than spend twenty minutes doing some autism building only to get ganked by some dude in a red suit that's way more equipped than I am. Warops is a challenge, but it's also fun for more players than just the antags and the few people that happen to have a viable weapon.

Really, I'd rather see the change be _forcing_ warops mode rather than removal of it.

2019-07-21 02:10 UTC, optimumtact commented
I don't think you understood the problem at all

2019-07-21 02:10 UTC, Swagile commented
Hivemind is a PVP gamemode; its secret extended (with all the problems of secret extended) due to how obscure it is to figure out if its hivemind or not unless you run into gibs in maintenance and then mass implant, and if you don't figure this out, suddenly BOOM ONEMIND LICENSE TO GRIEF.

Rev is a PVP gamemode; random guy runs up to you and flashes you suddenly LICENSE TO GRIEF EVERYONE (yes, everyone, you don't even need to convert). You do this till you get implanted or die; there is no RP and most crew give up on their jobs because if rev isn't beaten the game is over.

Cult is a PVP gamemode; you get converted and BOOM you have EMP, instant mute stun, instant cuffs, AOE critical rune, barrier runes, constructs, teleport both stationary and moving, good armor, and LICENSE TO GRIEF. If you do not kill cult at red eyes or above (halos) you lose due to nar sie (or if sac target cremates themselfs) apocalypse rune. Hence your job is pointless and there is no RP to be had; you kill and kill till the round is over.

If you remove War Ops on the basis of a lack of RP, issues with administration, and the fact that its a PVP gamemode then you have to remove basically 60% of all the biggest gamemodes on the server.

2019-07-21 02:10 UTC, nervere commented
>That doesn't mean it should be nuked from the skies.

What is the solution, then?
The entire premise of warops is that people are informed at shift-start of an enormous threat. The result will *always* be that the crew goes into a frenzy, and abandons everything but the pursuit of self-defense and combat. I do not think there is a way to fix it.

>Truth be told, it's more fun to have twenty minutes of getting prepared for the big war than spend twenty minutes doing some autism building only to get ganked by some dude in a red suit that's way more equipped than I am.

At least you have a *chance* to have a fun shift before nuke ops come and murder people. There is no such opportunity in warops: the entire shift becomes dedicated to combat.

2019-07-21 02:11 UTC, Gamer025 commented
> > > In my eyes, war ops mere existence is a way for pvp hungry players to let off steam in a way that no other game mode directly encourages
> > 
> > 
> > I would prefer if pvp-hungry players left our server entirely. SS13 is not the game for this kind of person.
> 
> Unless you change tgstation from RP-superlite in the near future and enforce the change heavily, this isn't going to happen. Validhunting and "sacred antags" have been part of this server's culture as long as I can remember. I'm not saying I'd be opposed to breeding that culture out, but as it currently stands this change is only going to make shit worse unless player and admin policy change along with the removal of options and modes like this.

Well I guess events halls is like super-low roleplay while the other servers are light roleplay. Maybe the servers could be restructured to feature different servers with higher or lowers level of RP and of course this.

2019-07-21 02:12 UTC, zxaber commented
I get the problem you're trying to solve. My point is that even with the undesirables doing things they shouldn't (and should be getting ahelped about), Warops is more fun than Stealthops for crew members.

2019-07-21 02:12 UTC, Ty-the-Smonk commented
reminder that sybil is the only one to have someone banned for powergame, so its the dedicated PVP server

2019-07-21 02:14 UTC, nervere commented
I reject the idea that most of our gamemodes are PvP-focused:
Most of them are not entirely disruptive to the shift. I can play hivemind, traitor, cult, etc. without it completely interfering with my goals and denying me the opportunity to play the job I'd like. I cannot say the same of war mode.

2019-07-21 02:15 UTC, granpawalton commented
If war ops were to be left in it should be declared right as the syndicate depart for the station and give lesser rewards so it could stop holding rounds hostage till the fragfest

2019-07-21 02:16 UTC, zxaber commented
@nervere 
>At least you have a chance to have a fun shift before nuke ops come and murder people. There is no such opportunity in warops: the entire shift becomes dedicated to combat.

The first twenty minutes of a round is basically prep work for the fun stuff that comes soon after. It's really more frustrating to go through the motions as if it's going to be a normal traitor round with generally less destruction and then right as things are getting good, you get steamrolled by people you can barely even fight. Even if you win, the round just ends, and you lose any hope of continuing what you were doing. You put up with it because "dying is part of the game" but it doesn't make it any less frustrating.

2019-07-21 02:17 UTC, dee-dubya commented
> I reject the idea that most of our gamemodes are PvP-focused:
> Most of them are not entirely disruptive to the shift. I can play hivemind, traitor, cult, etc. without it completely interfering with my goals and denying me the opportunity to play the job I'd like. I cannot say the same of war mode.

What's stopping you from playing the job you want on war ops? Short of xenobio(not enough time), every job is still necessary and beneficial during war ops, on top of the drafted militia of bored greyshirts looking to robust the red suits. You can choose to ignore the call to war and just do your job. The only thing that changes compared to other "short shift" rounds is that you know beforehand it's going to be short.

2019-07-21 02:18 UTC, Arathianen commented
>At least you have a chance to have a fun shift before nuke ops come and murder people

No. You don't. 20 minutes are enough for you to maybe set up your shit, get the first stuff rolling etc

The real game lasts for about an hour and a half. You are not even halfway through. Setting up your shit only to get a random explosion that kills you/destroys your shit is the exact opposite of fun. It's frustrating.

In fact, if this PR was about making war ops obligatory and nerfing stealth ops in a separate game mode, I might have supported it (even though i still like the option to declare or not).

This is basically keeping the worst part of the mode because Muh RP

2019-07-21 02:19 UTC, Swagile commented
> 
> 
> I reject the idea that most of our gamemodes are PvP-focused:
> Most of them are not entirely disruptive to the shift. I can play hivemind, traitor, cult, etc. without it completely interfering with my goals and denying me the opportunity to play the job I'd like. I cannot say the same of war mode.

Hivemind: One mind murders you after 20 minutes of one hivemind rushing everyone, good luck doing what you like.

Rev: If you don't stop the rev the game ends very quickly with sec being steamrolled then heads being destroyed as they now have no cover and are swarmed.

Cult: Nar nar is summoned in 20-30 minutes because cult currently snow balls fast.

Its the same thing as War Ops, but War Ops give you 20 minutes of prep time to actually fight back, whereas all the roles above barely give you time to fight back unless the people playing the antagonist roles completely suck and have no idea what they are doing.

2019-07-21 02:20 UTC, Ty-the-Smonk commented
wizard is literally a disruption

2019-07-21 02:21 UTC, Whoneedspacee commented
This gamemode is a good change of pace from being on a space station and not knowing who your enemy is.

Your point about people killing captains because they're playing wrong is something I rarely to never see at all, and is also against the rules, so I don't really see that as a valid strike against the gamemode.

The gamemode doesn't encourage people to ignore station roles, roles like janitor are yes abandoned for good reason, all personnel on hands we're in a war, time to fight. Nobody plays janitor during blob or wizard with crazy events, it just doesn't happen.

Roles like geneticist, xenobiologist, atmos, engineering, medical, cargo, mining, are still used but for their points that help you fight against the war ops.

Geneticts can provide massive buffs to the entire station, same with robotics and xenobio. Atmos can produce pretty effective bombs, and forms of gas that can help the station. Engineering still has to keep the engine running and it's a pretty clear target for sabotage so much of the time there's at least someone watching that.

It's a nice change of pace for a job to know that they can do a specific thing to help the station and have time to prepare. Removing this just removes depth from the game in my opinion and doesn't really replace it in any way. And yes "depth" isn't always a good reason to not remove something, but this gamemode has clear benefits and a lot of people do enjoy playing it.

That being said I do agree that the war button is pushed too many times and needs some sort of restrictions or limitations. If you made it a probability that it didn't happen or a seperate mode entirely that would be fine I think.

2019-07-21 02:25 UTC, optimumtact commented
What are the benefits other than "attracting people who prefer to valid hunt than actually play"?

WE already have two blowoff modes in the form of rev and wizard, why did nukeops need to become a third.

2019-07-21 02:25 UTC, datorangebottle commented
Honestly, if there's one thing TG needs, it's less deathmatch gamemodes. It's a mode where nobody gets to do their jobs or put in anything resembling decent RP because everybody is running around trying to murder ops. 

>Swagile

Except all of those modes provide the opportunity to engage with other players that isn't stabbing them in the fucking face.

One of my most memorable moments in SS13 is when Bill Cromswell grabbed my brain from my dead body during a cult round and crammed me into a mech, and we fled to lavaland and sat there roleplaying about how we were waiting for the station to become a nuclear fucking fireball in the sky.

Whenever someone mentions hivemind, I remember when owen kimple ascended and I got to speak using the communal 'we' to any normal people who asked me what the fuck was going on. I fucking HATE that gamemode, and I still think one mind is the one of the best things in the game.

Players these days are just too busy performing its mechanics to look at the window dressing and go, "Hey. That's hella cool." They'd rather beat eachother to death with toolboxes than consider that maybe summoning an elder god isn't a good idea, or that they can exile the heads instead of slicing their heads off with a cakehat. It's fucking depressing, and it's one of a few reasons I think removing war ops is a good idea.

2019-07-21 02:28 UTC, NoxVS commented
Personally I think the opposite should be done and instead remove normal nuke ops and only have war ops

War Ops - The operatives get more TC to buy more stuff, the crew gets to arm up and fight back, fun for both sides

Normal Ops - The whole crew is almost entirely unequipped to fight, they get steamrolled or the nukies fuck up and get steamrolled, round ends unsatisfyingly for everyone including the ops who probably just showed up and won and then left.

And if there is a problem with too many TDM modes just remove rev and wizard and keep nuke ops

2019-07-21 02:29 UTC, Swagile commented
> 
> 
> Honestly, if there's one thing TG needs, it's less deathmatch gamemodes. It's a mode where nobody gets to do their jobs or put in anything resembling decent RP because everybody is running around trying to murder ops.
> 
> > Swagile
> 
> Except all of those modes provide the opportunity to engage with other players that isn't stabbing them in the fucking face.
> 
> One of my most memorable moments in SS13 is when Bill Cromswell grabbed my brain from my dead body during a cult round and crammed me into a mech, and we fled to lavaland and sat there roleplaying about how we were waiting for the station to become a nuclear fucking fireball in the sky.
> 
> Whenever someone mentions hivemind, I remember when owen kimple ascended and I got to speak using the communal 'we' to any normal people who asked me what the fuck was going on. I fucking HATE that gamemode, and I still think one mind is the one of the best things in the game.
> 
> Players these days are just too busy performing its mechanics to look at the window dressing and go, "Hey. That's hella cool." They'd rather beat eachother to death with toolboxes than consider that maybe summoning an elder god isn't a good idea, or that they can exile the heads instead of slicing their heads off with a cakehat. It's fucking depressing, and it's one of a few reasons I think removing war ops is a good idea.

But these roleplay opportunities you are talking about happen in War Ops as well. Some people go to lavaland and stake it out after they lose the disk for good, others bond in comradery in surviving a war ops round (especially if the war ops are using meme weapons like the L46 machine gun that crits / kills in one burst depending if your wearing armor or not).

:shrug: At this point ive said what I wanted to say, the maintainers have final say anyway, but I personally don't think this will help anything at all and is merely a stop gap to other serious issues with the culture of the server itself that can't be hand waved away with just removing entire portions of gamemodes.

2019-07-21 02:29 UTC, Arathianen commented
>WE already have two blowoff modes in the form of rev and wizard

War ops are very different from both:

1) you have forewarning and a prep time. That is unique from any other game mode.

2) Both during rev and wizard, you might not know who the real enemy is for various reasons (rev conversions/wizard antags and mind swaps). Nuke ops is unique in that it encourages complete cooperation.

The modes are not the same and don't play the same. War ops plays unique amongst any other mode and the big majority of players, I believe, enjoy it. It can't really be compared to other "team deathmatches" because other teams aren't fixed.

2019-07-21 02:30 UTC, necromanceranne commented
Blitz ops being the only op strategy worth a damn. The way to play ops that is fun for literally nobody. Joy.

2019-07-21 02:30 UTC, PKPenguin321 commented
i for one would have disliked this months ago, but now i'm tired of the "war ops declared, drop everything and line up at the hop office for all access, then every man for themselves" shit that happens every single time

2019-07-21 02:31 UTC, dee-dubya commented
> What are the benefits other than "attracting people who prefer to valid hunt than actually play"?
> 
> WE already have two blowoff modes in the form of rev and wizard, why did nukeops need to become a third.

Wizard is only a blowoff round for the wizard player, or any validhunter that wants to robust the "peaceful wizard" meme. Plus, wizard is far, FAR worse than war ops as far as the "abandon your job, tide your way to guns, fuck everyone else, kill the antag at all costs" sort of mindset. At least mild job progression and thoughtful cooperation consistently happen during a war ops round. I'd support canning wizard for those reasons long before I'd consider canning war ops.

No comments about rev, as that's actually a fairly good game mode as well. Sure, being converted and being given a "license to griff" is problematic, but you're not going to solve that aspect of server culture with a simple PR.



So far I'm not hearing many rebuttals as to the reasons why war ops should stay, just repeatedly asking "why do we need this when it could cause problems" despite being given several compelling reasons.

2019-07-21 02:32 UTC, datorangebottle commented
>But these roleplay opportunities you are talking about happen in War Ops as well. Some people go to lavaland and stake it out after they lose the disk for good, 
Alright. That does exist, I'll give you that.

>others bond in comradery in surviving a war ops round (especially if the war ops are using meme weapons like the L46 machine gun that crits / kills in one burst depending if your wearing armor or not).
You mean others try to type something in 'say' and then get fucking robusted by the nearest guy who's running around murdering people because the round ended?

2019-07-21 02:32 UTC, Whoneedspacee commented
The blowoff modes are rare as hell probability wise to my mind anyways, so I don't really see a purpose in removing this from a mode where as soon as someone finds out that it's ops they're going to act in the same way they do in war ops and panic rush to secure the disk, or kill themselves.

At least with war ops you know what you're getting into and can suicide if you wish, with normal ops there's mostly two outcomes. It's like normal war ops and they buy some op guns and just stomp everyone immediately. Or it's stealth ops and the captain gets one shot and dies.

Then of course there's the rare round that's actually funny where they don't just buy my omega adrenals and best gun that kill super fast.

This isn't a gamemode you're going to fix by removing war ops it's literally a gamemode based around a blow up the entire station scenario.

2019-07-21 02:33 UTC, Whoneedspacee commented
And of course if the blowoff gamemodes aren't more rare then maybe they should be. If someone can't play the normal game 80% of the time then they probably shouldn't be playing in the first place.

2019-07-21 02:39 UTC, NoxVS commented
> i for one would have disliked this months ago, but now i'm tired of the "war ops declared, drop everything and line up at the hop office for all access, then every man for themselves" shit that happens every single time

This is a problem with nuke ops in general, not war ops. People abandon their normal roles when they learn nuke ops are coming because the round will end and theres no point doing your normal job if a round end screen will suddenly pop up so why not just say fuck it and join in the TDM. This problem is because of the nature of nuke ops, its just in war ops the crew know its going to happen and just join the TDM right away because there is nothing else you can do in a nuke op round

2019-07-21 02:44 UTC, Detective-Google commented
I mean war ops is so rare it's never really been an issue in my eyes, people act like apes trying to get the best gear for a round but it's also interesting to roll your job into full combat mode, instead of sitting around waiting for people to die as a medic, you have to have a good loadout to be able to save people on the spot, because you're not gonna have time to clone them, etc.

if you can't stand warops I really don't understand why we even have revs and wizard, revs especially are literally a team death match between flashy blue people and not flashy blue people, and instead of a nonantag doing something shitty and just getting banned, revs get a full license to do whatever the fuck they want, I (on sybil) have never seen anything close to 'killing the captain for the disk' playing, worst I've ever seen was someone mugging the hop for his ID, which is super shitty, but you could just get rid of players who do that, not remove an entire game mode

The best part of warops, in my opinion is that *everyone* gets to participate in the fight, whether directly or logistically, the entire station has to work as a team to get ready for a huge fight and it's a lot of fun.

2019-07-21 02:48 UTC, Gamer025 commented
Another way to approach this problem as I proposed on Discord:
Announce the fact that war ops are coming only to the captain or maybe the command staff
That way the can react either by keeping it a secret if they think security is good enough alone
Or they can announce it at a later time
Or announce it to single players only
etc
This way people who are affected the most about it (captain getting raided, HoS giving everyone weapons) can decided how to handle it.
They can either announce it which will lead to chaos but maybe a better defense if the station is cooperative. Or they don't and maybe announce it shortly before happening.

2019-07-21 02:51 UTC, dee-dubya commented
Honestly, from the subtext I'm reading, this PR is meant to help breed out validhunting culture on tgstation. This isn't the way to do it though, at least not alone. I'd say admin and/or policy discussion/changes needs to happen regarding that before we start changing the code to accommodate a sweeping server culture change like that.

Also, I like the change suggested above. Make it so that the war ops announcement only goes through the command and/or security channels. That'd add another layer to the impending "tide for AA and guns" shitfest that you apparently think is a regular occurrence during war ops.

2019-07-21 02:51 UTC, zxaber commented
>The best part of warops, in my opinion is that everyone gets to participate in the fight, whether directly or logistically, the entire station has to work as a team to get ready for a huge fight and it's a lot of fun.

Pretty much this. War ops may be a bit more deathmatchy than other modes, but at least you're part of a team and get to do things towards that goal. Stealthops just has you as cannonfodder unless you happened to have powergamed for a lethal weapon.

If we have to lose warops, I think we'd be better off just disabling ops.

2019-07-21 03:01 UTC, PKPenguin321 commented
>This is a problem with nuke ops in general, not war ops.

"no"

2019-07-21 03:04 UTC, necromanceranne commented
So to stress my point further than a shitpost, war ops at the very least is the one instance of this game being unbashedly honest about the way it is played.

Like a competitive deathmatch. Whether thats as one person verses everyone or team against team. People play this game to win and win as hard as possible and will use anything to ensure that victory on a per round basis. Shameless powergaming is the belly of the beast of /tg/. Even I am not above it.

Blitz ops is this cranked to 100. It is literally the most optimal method of winning ops. And it wins the hardest of any other strategy because it cuts out as many variables as possible to victory. Go in, kill and capture faster than resistance could be mounted. Arm. Leave. You can do it in five minutes. You can do it as one op who launches the shuttle, buys cqc en route, buys stims, buys his emag, and just guns for the captains office. Alone. He needs nobody else. This isn't even hard. It can happen so fast to be basically trivial.

Because this is not conjecture. This is the reason various historical changed occured for ops. Old sleepy pen got removed from the ops arsenal because of this as an example.

There are some far more sigificant changes that need to happen to the game and the administration of the game before this is ever a sensible choice to make. /tg/ might be too far gone to turn back now.

2019-07-21 03:05 UTC, optimumtact commented
only because admins like you give up

2019-07-21 03:11 UTC, necromanceranne commented
Do you want me to start banning people for playing this game too well? We allow our antags to do whatever they want. That includes using optimized strategies if that is what they want to do. If we start restricting antags that's an administrative decision that likely isn't going to go down well and believe me I've bitched about this plenty myself.

2019-07-21 03:14 UTC, imsxz commented
blitz ops is cancer if youre gonna remove warops you might as well remove the whole mode because blitz ops is a cruel joke. blitz ops, in theory, leaves little to no opportunity for the crew to do anything. if you were in the middle of something, your round is abruptly ended by a code delta. there is no disadvantage to going blitz ops, it's 100% play to win. either way, you arent gonna get to do your fucking roleplay or whatever the warop haters are crying about. war saves you the trouble of starting an autism project on a seemingly peaceful shift and gives you the opportunity to just suicide if you dont wanna play.

after all, we have like 6 other servers at this point and ghost roles to keep you busy

2019-07-21 03:36 UTC, necromanceranne commented
Hell, war ops gets you creative if you want to be. While the most ingenious defenses can be circumvented by ops, it still makes the odd weird, novel but clever strategies employed by the devious stand out as fun things to do and witness

2019-07-21 03:38 UTC, NoxVS commented
War ops gives you more TC to try out more gimmicky strategies rather than doing whats guaranteed to work and net you a win

2019-07-21 04:06 UTC, Shadowflame909 commented
This very divided comment section and the very negative player opinion has said more then I could ever rant or ramble about.

I hope Oranges sees the value and the enjoyment the players get out of this style of play. It's balanced and I think it at least warrants some changes instead of full-on removal.

2019-07-21 04:09 UTC, SynnGraffkin commented
I feel like at this point, arguing against Citrus man will only get people silenced on Git now, because Coders will do whatever they want and with how divided things are between Coders and Admins, nothing can be done to stop them. 

Even if a public poll was held, nothing will stop Orange from merging their own PRs to remove things like Felinids.

2019-07-21 04:10 UTC, Shadowflame909 commented
> 
> 
> I feel like at this point, arguing against Citrus man will only get people silenced on Git now, because Coders will do whatever they want and with how divided things are between Coders and Admins, nothing can be done to stop them.
> 
> Even if a public poll was held, nothing will stop Orange from merging their own PRs to remove things like Felinids.

You could try to bribe them

2019-07-21 04:10 UTC, wesoda25 commented
He (probably) can’t merge his own PR, and I’m sure he knows that if he does, it’ll just create senseless drama.

2019-07-21 04:12 UTC, Shadowflame909 commented
They've actually merged their own PRs before. Remember the felinds drama?

2019-07-21 04:13 UTC, Whoneedspacee commented
> He (probably) can’t merge his own PR, and I’m sure he knows that if he does, it’ll just create senseless drama.

thats funny that you think that.

> I feel like at this point, arguing against Citrus man will only get people silenced on Git now, because Coders will do whatever they want and with how divided things are between Coders and Admins, nothing can be done to stop them.
> 
> Even if a public poll was held, nothing will stop Orange from merging their own PRs to remove things like Felinids.

uh yeah he's basically the lead designer for this branch of the game, it's fully up to him to do whatever he wants.

> This very divided comment section and the very negative player opinion has said more then I could ever rant or ramble about.
> 
> I hope Oranges sees the value and the enjoyment the players get out of this style of play. It's balanced and I think it at least warrants some changes instead of full-on removal.

this pretty much sums up the entire thread. yes war ops is shitty in some ways but i'd like to see it as another gametype even if it's not one that's even in the default config. at the very least as an admin event it would be good to have as another tool to create fun memories.

2019-07-21 04:22 UTC, Shadowflame909 commented
Is stealth ops that much better though? Here's an actual situation I've been in:
>Be me captain
Review the chefs delicious food
Suddenly the clown walks up right next to me and pulls out a bulldog shotgun
Get three-tapped before I can even react
The clown scares off the chef and speeds away with my body into arrivals. (It was delta if thats the station with the bar down arrivals hallway)
We lose before we can even react

2019-07-21 04:23 UTC, SynnGraffkin commented
Stealth ops work if they don't give things away by wearing their hardsuits in the station.

2019-07-21 04:37 UTC, Shadowflame909 commented
Honestly on the "valid hunting culture." Might actually be the code itself.
/Tg/ has multiple high-pop downstream that have very differing rules. 
Yet from what I can see the play-style on all of them and the mentality is the same.
Rules can only go so far if the code doesn't align with it.

2019-07-21 09:07 UTC, AffectedArc07 commented
*This comment has been marked as off-topic*

2019-07-21 09:24 UTC, AtlasRules commented
I knew you were stupid, but this just reinforces that.

2019-07-21 09:24 UTC, optimumtact commented
lol who tf is this guy?

2019-07-21 09:26 UTC, AtlasRules commented
> lol who tf is this guy?

Someone who's sick of your shit.

2019-07-21 09:30 UTC, optimumtact commented
oh man bad news for me

2019-07-21 09:40 UTC, Akrilla commented
>It's quite obvious the change will be wildly unpopular but I don't believe that changes the fact of it being necessary or not.

What's your criteria for being necessary for the server? Doesn't the server serve the wants of the players that go on it?

2019-07-21 09:50 UTC, optimumtact commented
It's a combination of that and what the senior leadership team want, which is actually who I'm currently talking to in respect to feedback on the change.

2019-07-21 09:51 UTC, Whoneedspacee commented
> > It's quite obvious the change will be wildly unpopular but I don't believe that changes the fact of it being necessary or not.
> 
> What's your criteria for being necessary for the server? Doesn't the server serve the wants of the players that go on it?

boy do you have a lot to learn about administration and servers.

yes that's what they'll make it seem like hell if they have to run for a position that's voted on by the players it's all about what the players want.

truth is being in these positions is a pain in the ass and if people are going for them that means they want to make the changes they want. very rarely is someone going to spend that much of their time just to serve you for free, that's just unreasonable.

that's just the way it is, and honestly it's not a bad thing, they do a lot of work and therefore get to have a larger voice.

2019-07-21 09:57 UTC, Akrilla commented
> It's a combination of that and what the senior leadership team want, which is actually who I'm currently talking to in respect to feedback on the change.

Admins want this change? 👀

2019-07-21 09:57 UTC, Mithrandalf commented
wow this fucking sucks dude

2019-07-21 09:59 UTC, actioninja commented
> Admins want this change? 👀

https://github.com/tgstation/tgstation/pull/45307#issuecomment-513512679

2019-07-21 10:02 UTC, FancyCyclops commented
Gee, if only the rest agreed.

2019-07-21 10:08 UTC, Akrilla commented
>It is 100% focused on combat, nothing else, and has no place in a roleplaying game.
I fully support the removal of the war challenge mode.

Isn't that *exactly* what nukeops is meant to be...? A deathmatch in a roleplaying game? If it happens too often make it rarer, surely you know that it's popular with players, and that people really do like the chaoticness of it.

2019-07-21 10:25 UTC, Ratvar commented
TGstation is literally a team deathmatch, and encourages players to ignore normal station roles and act like idiots instead.

People never follow command authority and murder the captain because he has the disk and isn't playing how they think warops should be played.

I believe this station is deeply damaging to the character of ss13 and therefore I am removing it before it can do any more damage.

2019-07-21 11:12 UTC, Yttriums commented
This shit is sad. I've had so much fun contributing to these rounds in other ways, either by rushing healing items and ephedrine in botany so that I can be a speedy rescue healer, rushing various genetic mutations so I can spot the ops out and provide intel, peering out windows with Det binoculars trying to catch the ops early, rushing Regen coma viruses as viro, etc. These rounds don't encourage me to totally abandon my job - it makes me focus really hard on practicing the job for a particular purpose.

2019-07-21 11:31 UTC, Magikarpet commented
I enjoyed the cooperative aspects of war ops, being that the station had to work together and cooperate to defeat the ops. It's a shame that it's taken super gamey but the concern would be "How will this impact the appeal of nuclear operatives?" 

War ops sorta solved the whole issue with blitz ops being the only thing operatives can do which is about as unpopular if not potentially more unpopular than constant war. Imsxz kinda made the point but this might make operatives in general even more unpopular, but time will tell if that's the case.

2019-07-21 12:12 UTC, BeloneX commented
How about you tell the admins to get their shit together then instead?

2019-07-21 12:17 UTC, necromanceranne commented
As I asked oranges, what on an administrative end would you want us to do? Ban blitz strats? When we start restricting antags that heavily, we then need to scrutinize every antags actions and then we spiral into the mess that is Paradise.

2019-07-21 12:40 UTC, Evilsack commented
Heck, instead of changing certain features; gathering relevant feedback from the playerbase and taking that into consideration; holding polls and pretending to care about what players think, you somehow think that it's okay to remove a feature that people enjoy because _you_ feel that it's necessary. From what I can see, you didn't even try and make compromise with this decision, nor did you try and find alternative options. You went straight for the nuclear option because it's the easiest thing to do and you have little to no faith in the administration team or the actual playerbase itself. It's easy to press the big red button and delete shit. Because you feel that it's necessary doesn't mean it's the best course of action. Deleting a game mode because people aren't playing in a manner you can accept instead of re-educating defeats the purpose of deleting it in the first place. If people enjoy playing like this they will find a way to do it sooner or later. Re-evaluate your decision.

2019-07-21 13:21 UTC, SkeletalElite commented
The entire nuke op game mode is TDM. Removing war ops isn't going to change that.

2019-07-21 14:06 UTC, MimicFaux commented
If the primary reason for wanting to remove the option to declare war is people breaking server rules, then the solution lies in enforcing those rules.

2019-07-21 14:52 UTC, MMMiracles commented
I think the problem is oranges doesn't believe those rules are really getting enforced in the first place.

2019-07-21 14:54 UTC, Ratvar commented
If neither players nor admins follow and enforce rules, maybe rules should be changed and TG should embrace being what it is?

2019-07-21 15:19 UTC, Evilsack commented
The argument here is that, "Everyone griefs during this mode, everyone is validhunting, it's hell." Surely if rules are properly enforced, and people are aware of the punishments they risk being subjected to, this wouldn't be a problem? I'm failing to understand how removing the ability to declare war changes this "meta". If the problem is the mentality of the players then clearly the problem is deeper than lines of code. There's no deterrent in place. Players think it's okay. Clearly because of the lack of administrative force being applied.

2019-07-21 15:24 UTC, Nickkoranda commented
/tg/ has a long history of being more than a "TDM" server. I love war ops myself but it's pretty easy to see how a giant prompt and usually a copypasta turns the round into a gamerfest of loot and literal TDM instead of the subterfuge/rushing nuke ops have had in the past. Regardless of how fun these rounds can be, this is a stance somebody has to take in order to stop devolving /tg/ culture into becoming more than "robust or be robusted" like it has been lately.

2019-07-21 15:31 UTC, ATH1909 commented
https://www.youtube.com/watch?v=31g0YE61PLQ

In addition to the reasons cited above (including the fact that many players ENJOY war ops, as evidenced by the controversial nature of this PR (this is why I think that ops as a whole should stay in the game: both stealth ops AND war ops)), I also think that this PR is an incredibly bad idea because it encourages blitz ops.

Right now, ops have three ways to play:
1. War ops: A team deathmatch that warns people ahead of time that the round will end at around the 20-25 minute mark, so they won't waste their time on doing a long gimmick and have their round ruined by a surprise nuking. The ops get fancy, expensive (and fun to use) toys, and the powergamers on the station get to show off their skills. 
2. Stealth ops: The ops get to have fun planning and executing an Oceans 11-esque heist. It's great fun for the ops and about as fun as secret extended for most of the crew (until the nuke goes off), and unlike some other people, I think it's a fine way to play nuke ops.
3. Blitz ops: Literally cancer. The ops run in, grab the disk, and ruin everyone's round with (almost) no challenge involved whatsoever, making it not even that much fun for the ops (unless they take their time to "toy with their prey" and murderbone unarmed people for kicks). Blitz ops is so pathetically easy that it's ironically not done very often, as it's considered "dishonorable" to do so.

Unfortunately, removing war ops will make blitz ops the mode of choice for many op players who just want to kill people with cool guns (there's usually at least one on every team of ops), and the result will be AWFUL. Hell, this already happens on some rounds when war ops isn't declarable due to the low player count. I suppose that some more honorable nuke op leaders could risk getting lynched by their team to announce their presence over general comms (or commanding a syndiborg to do so over borg comms to prove that they're legit and not a comms agent), but I doubt that that'd happen (and if it does happen and blitz ops remains dishonorable, what was the point of removing war ops?).

Listen, if you don't like the frequency of nuke ops (and have the view that it pops up too often to be considered a "change of pace"), why not just... reduce the frequency of nuke ops instead of making the game mode itself much, much worse so that you'll have an excuse for entirely removing it later?

2019-07-21 15:39 UTC, knacker48 commented
War ops is a genuinely unique experience on /tg/. Unlike other antagonists that spend most of the round hiding in maint, steathly killing people, war ops is one of the few enemies that brings the crew together, throwing the usual jobs and priorities into the air and makes people scramble for whatever they can get their hands on in order to save the station. Even blob, which tries to do this usually fails as stationary opponents are nowhere near as scary as a highly mobile, heavily armed team of ops that can have a wide range of equipment to do their job. 

To throw that away for what, cause its too chaotic for you to handle? Cause you can't be bothered to ban the odd asshole who kill the captain? That's a terrible excuse and you know it

2019-07-21 19:29 UTC, ayebee123 commented
"I believe this mode is deeply damaging to the character of this server," but how does it damage the character of the server? hasn't "the character of the server" already been tarnished by changes like these? it's clear, the players WANT war ops. it hasn't tarnished "the character of the server," it seems to help it. "the character of the server" seems to be removing features of the game even though the players advocate against that. isn't the whole point of making changes like these to please the playerbase? this seems to just make the players more and more displeased.

2019-07-21 20:41 UTC, SweptWasTaken commented
Can you please listen to the community for once in your godamn life.

2019-07-21 20:55 UTC, PKPenguin321 commented
The notion that admins need to "admin better" on war ops rounds is a bit silly. The problem isn't rule breaking because dropping what you're doing to grab free all access/weapons to fight ops with isn't against the rules at all. The problem with that behavior is (according to oranges) that it's not how the game should be played, and he wants to stop that behavior by removing the mode.

2019-07-21 21:48 UTC, Evilsack commented
> The notion that admins need to "admin better" on war ops rounds is a bit silly. The problem isn't rule breaking because dropping what you're doing to grab free all access/weapons to fight ops with isn't against the rules at all. The problem with that behavior is (according to oranges) that it's not how the game should be played, and he wants to stop that behavior by removing the mode.

If what he witnessed was toxic, which includes assistants killing command because they fell like they can do a better a job, and he mentioned that it must be the default meta because it was done during a time in which admins were online, (implying that the problem lies in either disregard of policy or lack of suitable policy), then it's an administrative issue. If you think about this logic, then One Mind Ascension, Cult Ascension, and any other antag that paints a target on you should be removed. Which would be ridiculous. But I wouldn't be surprised if that was the case.

2019-07-21 21:52 UTC, msgerbs commented
>This mode is literally a team deathmatch, and encourages players to ignore normal station roles and act like idiots instead.

Yes, let's just remove everything that makes any round anything other than the same thing over and over. Excellent justification, 10/10, speedmerge please.

2019-07-21 21:58 UTC, Akrilla commented
> The problem with that behavior is (according to oranges) that it's not how the game should be played, and he wants to stop that behavior by removing the mode.

Fundamentally people choose how the game should be played, it’s insane to me that this is still an open PR and actually has a chance to be merged. If this really wants to be removed, a poll should be done, with at least having the decenancy to care about the opinion of people that play on the server. If the poll wants it removed cool, if not, don’t remove it, surely?

2019-07-21 22:05 UTC, optimumtact commented
People choose what server they play on, not how its played.

2019-07-21 22:16 UTC, Spyroshark commented
oranges made a good pr? what??

2019-07-21 22:26 UTC, Akrilla commented
I say fundamentally because if the game doesn’t cater to how players want to play then they leave, or at least have less enjoyment if there’s not a decent enough alternative. If I asked you the question, if you knew something you changed led to people enjoying playing on tg less overall, but you believed it to be the right thing to do, would still make the change?

2019-07-21 22:27 UTC, optimumtact commented
yes

2019-07-21 22:27 UTC, Akrilla commented
Alright fair enough

2019-07-21 22:44 UTC, optimumtact commented
We've decided to make warops into it's own gamemode instead

2019-07-21 22:51 UTC, BeloneX commented
that's the stupidest thing I've heard today

2019-07-21 22:52 UTC, datorangebottle commented
How does that solve literally any of the problems you and Nervere brought up, Oranges?

2019-07-21 22:52 UTC, nemvar commented
Why even bother at that point? What does this solve? So that people are forced to play stealth ops once in a while?

2019-07-21 22:54 UTC, optimumtact commented
That is what has been requested so the headadmins can choose how often warops runs instead.

I don't think it's perfect but it's better than doing nothing and also better than removing it because it's been made quite clear that people dont' want that.

2019-07-21 23:13 UTC, Shadowflame909 commented
That's an alright compromise.

I think the real issue with OPs. Being Im Ded here. Is how the mode can be over before anyone can realize what mode it is. IE. The ops buying the clown chameleon suit and 3 tapping you while you're doing captainly duties.

2019-07-21 23:15 UTC, SynnGraffkin commented
> 
> 
> We've decided to make warops into it's own gamemode instead



> 
> 
> That is what has been requested so the headadmins can choose how often warops runs instead.
> 
> I don't think it's perfect but it's better than doing nothing and also better than removing it because it's been made quite clear that people dont' want that.

So, How I understand this, is it's going to be it's own game mode, there will still be people who have either op mode on and not wanting to do that mode or be disappointed it didn't roll the one they prefer (Say you wanna do Stealth ops more and instead you rolled War because you have both selected), and probably because Citrus Man and the Heads dislike War mode so much, they will probably just set the Config chance on War to be 0~0.1% chance to happen because it satisfies their desire for War to be removed, which gives the illusion to the playerbase of the game mode still being in.

2019-07-21 23:19 UTC, HeartwawyHorror commented
Are there going to be any changes to the new separate war ops?

2019-07-22 00:42 UTC, dr-bee commented
Making it it own game mode also allows it to be balanced separately from normal ops. That is overall the best way to do it.

You can, for example, limit certain weapons on the operative side to make the fight vs the crew less one sided and to make grouping up and defending an area actually possible for the crew instead of suicidal.

2019-07-22 00:44 UTC, necromanceranne commented
Alternative, give regular ops objectives other than nuke the station.

2019-07-22 03:57 UTC, qbmax32 commented
lmao if you want to stop "team deathmatch" can we remove revs too?

2019-07-22 04:06 UTC, nervere commented
The comments I've left on this PR remain my personal opinion, but the opinion of the community at large is much more important than my personal will on the matter.

Oranges has proposed to make this a gamemode, and I think this is a great compromise. This way each downstream can adjust the odds as they see fit, and we as a community can come to our own decisions on it. I don't particularly like the gamemode, but this will give us the opportunity to come to a conclusion on it as a group. Expect a community meeting soon on this topic and other related matters, I hope the compromise gets merged so we can all work together on resolving this issue and hear from other.

2019-07-22 04:19 UTC, Arathianen commented
I like the compromise personally.

I still have a hateboner for stealth ops but we'll see.

2019-07-22 06:12 UTC, ErwinSnowden commented
Imagine this, okay, do you not understand the issue with your logic, you anti-war-ops liberals? You think that /tg/ culture should be changed and if they don't like it, they can just get the fuck out. Great logic, which is why a system that isn't controlled by the people is stupid, and anything to this magnitude of ignoring the general populous just because you feel that the game function is making the people toxic, not the people being toxic already is stupid, but then you go on top of that and make up bullshit excuses for removing it.... Just admit you don't fucking like the gamemode and rework it, don't remove it.

2019-07-22 08:55 UTC, Michael-Ashfield commented
> I reject the idea that most of our gamemodes are PvP-focused:
Most of them are not entirely disruptive to the shift. I can play hivemind, traitor, cult, etc. without it completely interfering with my goals and denying me the opportunity to play the job I'd like. I cannot say the same of war mode.

This is flat out incorrect, sorry. Yes, some players abandon their jobs, normally assistants (who would otherwise tide), curators (who would otherwise tide) and a scannteirng of other crew. What normally happens is that jobs go hyper rushing to produce defences and supplies that will be needed. Ive seen botany rush gaia or harmful plants to stop ops, science rush research, robotics rush multiple engineer/med borgs and even mechs, cargo does their job ordering guns, chemistry rush out loads of meds while docs prep up as EMT, engineering have to rush engine to get power going before wires are blown while also having to make barricades and defences, atmos fills distro with good air, miners gather some quick resources to get guns printed in time, science can be seen making bombs and the chef can often been seen mass producing pizza to feed the army. Hell once I have seen viro rush out some decent healing viruses in time.

War ops can bring out the best in some crew doing their jobs, it is a rush and allows them to make some stuff they wouldnt normally be allowed to make. If you cant get fun out of war ops, it is your problem, not the modes.

2019-07-22 09:03 UTC, optimumtact commented
![](https://file.house/WAG_.png)

2019-07-22 09:15 UTC, Whoneedspacee commented
mark the above oranges comment as off topic immediately

the compromise is happening you cant stop it.

but really downstreams its a fucking one line change for an item to be spawned with, it’s literally not even being removed the item just doesnt spawn with him.

even if you suck at code just spawn in the damn item if you want war ops to happen.

and then theres another gamemode on the way so we can add more easily possibly unique shit to the different modes considering they play so differently anyways.

pretty much nothing to complain about at this point

2019-07-22 09:16 UTC, optimumtact commented
scared?

2019-07-22 09:42 UTC, CPTANT commented
I am fine with warops being a seperate mode.

2019-07-22 10:31 UTC, Michael-Ashfield commented
I don't see why that attack was necessary, Orange. That "tg remake" repo is an entirely different project which I simply contributed a tiny fix to, a project that is remaking tg in node, not even BYOND. Next time please address my actual point.

2019-07-22 10:43 UTC, optimumtact commented
attack?

2019-07-22 10:48 UTC, Wilchenx commented
dick clanker

2019-07-22 10:59 UTC, Michael-Ashfield commented
> attack?

I'm not going to argue on github (as its clearly unrelated to this pr and off-topic) but it was pretty obvious what you was implying with that post, unless you would like to clarify what you meant by that.

2019-07-22 11:00 UTC, optimumtact commented
I just wanted to know if you found the javascript GC hard to work around or if it wasn't a problem at the amount of objects you were burning and turning

2019-07-22 11:03 UTC, Michael-Ashfield commented
> I just wanted to know if you found the javascript GC hard to work around or if it wasn't a problem at the amount of objects you were burning and turning

Off-topic but I wouldn't know, I only fixed an error with buckets saying whatever inside them was water, even if it turned out to be acid. You will have to ask the developers which I forked from to make my change.

2019-07-22 11:34 UTC, optimumtact commented
awww

2019-07-22 15:23 UTC, SkeletalElite commented
I honestly don't see the problem here.



> Warops is a boring deathmatch gamemode that is the same every shift:
> 
> * 0-5 minutes: Warops declare
> * 5-20 minutes: Crew gets all access and lynches anyone who tries to stop them, loots armory and anything else valuable.
> * 20-25 minutes: Crew finishes barricades as warops arrive, ~10-15% of the crew is already dead of suicide to escape the awful gamemode or because of deaths related to tiding.
> * 25-30 minutes: Shuttle is called, red-alerted, shuttle arrives at 30 minute mark.
> * 35-40 minutes: Shift ends prematurely from warop death or another 5 minutes are wasted on time to depart/arrival at central command.
> 
> There is never any roleplay. There is never any chance to do your job because everyone is tiding.
> It's not an administrative issue, it's inherent to the gamemode. No amount of rules will make players stop being feral apes when nukeops with 500TC are about to arrive on the station.
> 
> It is 100% focused on combat, nothing else, and has no place in a roleplaying game.
> I fully support the removal of the war challenge mode.

Lets look at the same situation except without war

0-5 minutes nukies prepare
5-10 minutes nukies arrive on station and rush the disk
10-15 minutes the round has ended because the station already blew up and the vast majority of the crew just wasted their time by even starting to get invested in their jobs because it just got wasted and they didn't even get to have fun fighting the nukies because the fighting with the nukies was already over before they were even prepared to do anything.

2019-07-22 15:35 UTC, SkeletalElite commented
In fact the more I read the opposition of this thread the more I get the impression its just people going antag bad, conflict bad, chat box good.

2019-07-22 17:35 UTC, AffectedArc07 commented
Oranges where the fuck is your changelog, this is a pretty big change and you havnt put a CL

2019-07-22 17:43 UTC, GalacticSwan commented
what the fuck

2019-07-22 20:00 UTC, ExcessiveUseOfCobblestone requested changes
CL please and is this ready ? I thought this was going to be config bound (as it should have been from the getgo imo)

2019-07-22 21:25 UTC, optimumtact commented
It's obviously not ready you fucking spoon

2019-07-22 22:16 UTC, OverlyGeneric commented
i don't understand why some people are complaining about the compromise.

it maybe could be better but i'm not looking a gift horse in the mouth.

2019-07-23 04:57 UTC, dee-dubya commented
The only complaint I have about the compromise is it's not going to be a compromise. The seperate warops game mode will wind up disabled in the config or set to a 0.0001% chance of occurring to give the illusion of chance, and the codemins still fuck everyone over.

Lack of faith goes both ways. Coders say they have no faith in the admins to do their jobs or the community to act appropriately, meanwhile the community has no faith in the codemins to act in their best interests.

2019-07-23 05:05 UTC, optimumtact commented
except, coders have no control over the config, so your comment makes zero sense

2019-07-23 06:23 UTC, optimumtact commented
closing in favour of a new pr

2019-07-23 06:23 UTC, closed without merging

2019-07-23 17:19 UTC, ExcessiveUseOfCobblestone commented
> It's obviously not ready you fucking spoon

I don't think I warranted that kind of tone.

2019-07-24 02:47 UTC, wesoda25 commented
> i don't understand why some people are complaining about the compromise.
> 
> it maybe could be better but i'm not looking a gift horse in the mouth.

Shitty PR 
No one likes it
HoW AbOUt cOMpROmISe?
People would rather nothing changw
?????????