Removes survival medipen from vendor.
tgstation/tgstation pull request #45499
Opened 2019-07-26 09:26 UTC by SgtxRootbeer

:cl: Hits
del: Removes mining survival pen from the vendor
/:cl:

In line with my views presented in my previous pr, I've foreseen that the mining pen will need removal.

why?
1, this prevents medbay from using their dept budget card on the vendor to buy tons of medipens and avoid having to use chemistry.
2, this encourages inter-dept cooperation, in that miners will now have to venture to chem and ask for a pillbottle of sali/oxand or whatever other chems they want for mining. This is a more natural form of dependency and may even lead to miners asking for mixes of adrenals too!

2019-07-26 09:28 UTC, shellspeed1 commented
I can say, I have bought survival pens before as a medical doctor to treat people. It is kind of bullshit and should be removed. Might not be a bad idea to make it so people can make epipens.

2019-07-26 09:32 UTC, Akrilla commented
ided

2019-07-26 09:38 UTC, SgtxRootbeer commented
if it makes you feel any better akrilla, i've only played on /tg/ for one round in the past 2 weeks or so.

2019-07-26 09:42 UTC, Whoneedspacee commented
imagine removing mining points and then complaining when people use money to buy the healing item that was meant for mining points.

seriously what the hell was the point of "integrating mining points into station funds", you can already use the fucking coin press to turn ore into buttloads of cash with diamonds.

>miners asking for chems is the meta

that'll be the fuckin day, all this does is make it more of a pain in the ass for new players, i'll just be sitting here spamming my legion cores all day.

honestly at this point i see no reason to mine at all unless you really want those damage mods.

2019-07-26 09:44 UTC, Dawson1917 commented
>1, this prevents medbay from using their dept budget card on the vendor to buy tons of medipens

Revert [44507](https://github.com/tgstation/tgstation/pull/44507) then. That's the simplest solution. You either overhaul lavaland in its entirety (I dare you) or you undo the PR that thought it was a good idea to let heads of staff use their magic money generator cards to buy unlimited quantities of mining gear. Miners having to slug up to chemistry or medbay every time they get shot by a watcher and lose half their health? Hah! Some of us would like to play the game.

Imagine fighting megafauna with this.

2019-07-26 09:46 UTC, shellspeed1 commented
Imagine going and asking chem to do their job for once.

2019-07-26 09:47 UTC, Whoneedspacee commented
yeah except it's an incredible time waste for miners to spend 3 damn minutes flying back to the station and asking chem to do shit and then wait for them to do the shit etc

i'd rather just tough it out to be honest, this isn't going to do anything but discourage miners from mining even more.

2019-07-26 09:52 UTC, SgtxRootbeer commented
Imagine popping a pill instead of using a syringe for your heals. Gosh!

2019-07-26 09:53 UTC, SynnGraffkin commented
> 
> 
> Imagine going and asking chem to do their job for once.

Medbay? More like Chembay. Just make a PR to turn all of Medbay into Chemistry.

2019-07-26 09:55 UTC, Dawson1917 commented
> 
> 
> Imagine popping a pill instead of using a syringe for your heals. Gosh!

Have you ever played mining? Once?

2019-07-26 09:56 UTC, FancyCyclops commented
[And they don't stop coming and they don't stop coming and they don't stop coming...](https://youtu.be/eT3BFzSD6YY)

2019-07-26 10:02 UTC, MCterra10 commented
Coders:
> Make PR allowing anyone to buy powerful items from the mining vendors
Also coders:
> REEEE I CAN'T BELIEVE THIS EXPLOIT WE KNOWINGLY INTRODUCED! Time to nerf mining!

2019-07-26 10:08 UTC, Dawson1917 commented
> 
> 
> Coders:
> 
> > Make PR allowing anyone to buy powerful items from the mining vendors
> 
> Also coders:
> 
> > REEEE I CAN'T BELIEVE THIS EXPLOIT WE KNOWINGLY INTRODUCED! Time to nerf mining!

Someone will make a comment saying this'll force coders to overhaul lavaland to not be a magical private land unbalanced for being on station and we can all laugh at them for thinking that'll ever happen

2019-07-26 10:14 UTC, Chessus commented
No need to remove it when it's already locked behind a paywall. I'd increase the cost first before thinking about removing it. Doubled at least. That way both of your points are covered.

2019-07-26 10:14 UTC, Akrilla commented
> if it makes you feel any better akrilla, i've only played on /tg/ for one round in the past 2 weeks or so.

😅 

Nah but this is a massive nerf to mining, I agree CMO being able to make medbay just survival pen land is dumb, but you haven't considered what they were actually there for in the beginning.

2019-07-26 10:28 UTC, ike709 commented
>if it makes you feel any better akrilla, i've only played on /tg/ for one round in the past 2 weeks or so.

coders don't play the game but we still let them balance things

2019-07-26 10:28 UTC, shellspeed1 commented
Chemistry too slow? I can have patches done in 5 mins for the majority of the shift. If the miners needs some they are welcome to nab them from the fridge.

2019-07-26 10:31 UTC, nemvar commented
Don't you know? Miners having any kind of interaction with the station BAAAD.

2019-07-26 10:32 UTC, Chessus commented
How often does the CMO power game like this to be an issue?

2019-07-26 10:34 UTC, MCterra10 commented
@shellspeed1 unfortunately, you are in a small minority of chemists who actually do their job and stock the fridge with chems instead of spending the shift making potas/water grenades and toxin syringes. I wish I could say that mining could cooperate with chem, but that's just not the case, and I won't stand around waiting for chem to scour the wiki and painfully slowly mix a few healing pills if they do so at all.

2019-07-26 10:36 UTC, knacker48 commented
Just revert #44507 as that was a terrible idea in the first place. They were meant to be something only miners had access too. Now if you think they should cost more miner points that's fine but if you just remove them entirely your just gonna make fighting megafauna that much more difficult. Nobody has time to stand still and use a patch while an ash drake is setting you on fire

2019-07-26 10:39 UTC, Dawson1917 commented
Miners require long-lasting "passive" healing they can apply instantly, ie survival pens and NOT patches or pills (miasma or n2o or bz in the lavaland air no thank you) because lavaland is designed all around having to fight hostile mobs while mining, or fighting even more hostile mobs while looting tendrils, or fighting hostile megafauna. None of these give you the opportunity to sit still and apply patches (god for-fucking-bid category chems that give miners toxin damage or cold slowdown while healing) or to take off your mask and internals to chug pills.

You should be considering these things when making balance changes, not nerfing because some CMO powergamed a very obvious exploit for a job that operates separate from the station.

2019-07-26 11:13 UTC, 81Denton requested changes
Either rebalance all lavaland encounters to account for the lack of survival medipens or close this PR. 
Right now, mining is balanced around the availability of survival pens - you can't remove an essential part of a job and then expect other coders to clean up after you.
Some of the medipen reagents, like lavaland extract and tricordrazine, aren't available to players either.

2019-07-26 11:15 UTC, Krysonism commented
Syringes can be applied instantly even while wearing a mask.

2019-07-26 13:25 UTC, lolman360 commented
Why not replace legion core and medipen effects? Medipen now removes damage slowdown (maybe heals a little idk.) Legion core now works as a medipen, doing a fast heal for 3s (lavaland extract in pen) and a longer, gradual heal over time (like other chems in pen)? Now there is no problem with Med/survipens as they are useless for healing (more or less.)

2019-07-26 14:03 UTC, nicbn commented
Just overprice it
That nice murica feelin

2019-07-26 14:11 UTC, daklj commented
instead of introducing goofconomy everywhere and then complaining that everything affected by goofconomy suddenly is broken af, we should remove goofconomy or at least remove department budget cards

this would:
- solve the problem of heads being able to get tons of unbalanced premium mining gear
- solve the problem of sec having infinite mindshields turning every rev/cult round into emergent 'stun everyone you see and then implant them' gameplay
- solve the problem of the crew being better armed than war ops
- make other ways of gaining credits by cargo that are actually fun viable once again - i mean bounties here, it's funny how economy was supposed to encourage cross department cooperation and instead it kind of killed cargo bounties that were probably the best feature when it comes to interactions between different jobs, why bother with bounties now when you can just ask 3 random heads for their ids and never care about cargo budget anymore

it's stupid how many cargo budget balance changes were made in the past and then goofconomy arrived, breaking cargo balance harder than anything else (even stocks required some effort unlike absurd budget cards)

with budget cards gone mining vendors wouldnt be much of an issue honestly, if they still would be abused you can just remove the one on the station leaving only the one in lavaland and i dont think anyone would bother going there without absurd amount of credits

2019-07-26 14:36 UTC, Tlaltecuhtli commented
[[[id locked medipens]]]

2019-07-26 14:52 UTC, HeartwawyHorror commented
Survival pens are balanced only for mining. They provide near-instant, mobile heals useful for fights where one wrong move or moment of hesitation can cause certain death through damage slowdown. On the other hand, overusing them results in a very painful overdose, forcing miners to git gud and not use them as a crutch. With the change to credits, everyone (especially the CMO) has the ability to buy these medipens, completely negating the entirety of chemistry and turning people who have these pens into very unstoppable people. Removing these pens would make Legion skulls the only source of instant healing, which lacks the slowdown negation chem (a major must in mining) and the temperature restoring chem.

2019-07-26 14:55 UTC, MCterra10 commented
@HeartwawyHorror while I make myself clear that I dislike this PR immensely, I will point out that legion cores do actually provide a short status effect that negates showdown, although they do not stabilize temperature

2019-07-26 14:58 UTC, HeartwawyHorror commented
@MCterra10 Oh alright, I didn’t know about that. Guess the new strategy for mining is legion farming then. That honestly is going to be really annoying, but manageable.

2019-07-26 15:00 UTC, MCterra10 commented
That's assuming this gets merged, which I'm fairly sure it won't, but if it is you are right about farming legion cores.

2019-07-26 15:08 UTC, HeartwawyHorror commented
Now that I realize that legion farming is going to be the new meta, there STILL isn’t going to be any of that sweet sweet interdepartamental interaction OP is going for. Sure this PR fixes a major exploit, but in the long run, mining is just going to become more bloody annoying with legion farming for the free heals. inb4 he also tries to remove legion cores.

2019-07-26 15:10 UTC, SgtxRootbeer commented
![2ev1ws](https://user-images.githubusercontent.com/22112255/61961704-d07a6b00-af7c-11e9-99a7-d02fa250d7d8.jpg)
Mfw I see legion cores are in my way.

2019-07-26 15:23 UTC, HeartwawyHorror commented
No words can express my utter disappointment in your ability to rebalance the meta. If what I think you’re going to do is going to happen, removing both pens and cores can and will make healing on lavaland reliant on literally two people on the station who probably aren’t going to do their jobs or are probably too busy helping out with chems for healing regular people instead of busting their asses making combat grade stimulants and instant healing chems that won’t give you brain damage. Healing on lavaland alone will be limited to eating Donk pockets and cacti, which could make you fat and ridiculously slow. Compounded by the fact that they take more time to kick in than a pen or a core, you are basically screwed when you take enough damage to have slowdown. At least give the miners something to combat slowdown if this PR and the one you are considering are going to be merged.

2019-07-26 15:29 UTC, SgtxRootbeer commented
If I decide to remove legion cores, I'll add a stun-reduction/negation thingy in their place. I just had a strong urge to meme.

2019-07-26 15:32 UTC, shellspeed1 commented
Look, lavaland is public  access now. If the miners are all dead go mining yourself or have the robo build a mining borg.

2019-07-26 15:36 UTC, HeartwawyHorror commented
As much as I detest your goals in balancing mining, at least there’s going to be something for the slowdown and stuns. Thanks for that.

2019-07-26 15:42 UTC, 81Denton commented
The pens themselves aren't the core of the issue, it's more that department budgets are so grossly bloated that you can buy dozens of them. This doesn't only apply to pens, but also to cargo packs. As @daklj already said, it's so bad that bounties are more or less irrelevant.

2019-07-26 17:31 UTC, SgtxRootbeer commented
The real issue is that aside from a few cargo crates, and mining pens, there's nothing to buy for the station. Dakij alluded to this when he said you can ask "3 random heads" for their budget card, and likely get it because they're not gonna use it for anything else.

2019-07-26 17:38 UTC, ExcessiveUseOfCobblestone commented
nerf department budgets and then someone will be prompted to make active methods of boosting said budget :^)

2019-07-26 18:17 UTC, Shadowflame909 commented
@SgtxRootbeer 

Isn't the budget what pays the crew in the first place. I know damn well that if the service budget gets wasted. That I just quit doing my job/if im a miner I quit going back to the station.

Because you're essentially not paying people for working.

2019-07-26 18:20 UTC, OverlyGeneric commented
when did we lose sight of the original aspect of goofconomy?

it was literally about incentivizing people to do their job and keep the greytide from powergaming.

now it's just been made heads the new powergamers. I'm saddened by this.

2019-07-26 18:21 UTC, Shadowflame909 commented
Goofconomy was actually just a useless goof dumb bounty. That maintainers HAD to give a use.

Is it surprising that it fucked up balance this bad?

2019-07-26 18:29 UTC, OverlyGeneric commented
> Is it surprising that it fucked up balance this bad?

I think mostly the problem was that people kept adding onto it instead of fixing key issues with it.

It was bad in design but not code-wise. You can't blame the code for doing its job.

2019-07-26 18:44 UTC, ExcessiveUseOfCobblestone commented
uh we don't merge based off it being a bounty or not, especially when it's strictly between person willing to buy and person willing to code.

If someone's getting commission for code bounties I want in smh.

2019-07-26 18:56 UTC, Shadowflame909 commented
I was just paraphrasing what the orange man said

2019-07-26 19:03 UTC, ExcessiveUseOfCobblestone commented
orange man wanted economy foundation regardless of the bounty. It just so happens that goof was the one to code it :^)

2019-07-26 19:56 UTC, ayebee123 commented
as someone who mainly uses the proto-kinetic crusher for mining, i'd like to say this feels like a complete fucking indirect nerf to it.

now, i'm not saying im a good miner, but a even a skilled player using the crusher is bound to get hit, and being able to pop a medipen when you're getting low is amazing. having to pop a pill adds the extra step of taking off your mask which can make a big fucking difference in a fight against megafauna.

2019-07-26 19:56 UTC, Naloacisamazing commented
if this is merged, it will just cause miners to rely on farming legions for their heals. and continue to completely ignore chemistry as the majority of the heals that are based for on station stuff are far too slow for the majority of lavaland content. Trying to stand stock still to spray yourself or apply a brute patch as bubblegum instantly kills you is no fun. It will also cause the station to begin to receive alot less mats because miners are now trying to collect legion cores to make up for the lack of proper fast healing. Now imagine if a new miner runs down sees the legion tendril and kills it? everything then slows to a crawl as miners dont wanna be overactive and mine incase they die. imagine ash lizards are in that round? nearly endless spawning.  Now the fact the station relies on miners extremely heavily becomes a large problem. 

Is Heads of staff buying 50 medipens stupid? 100%, but thats a problem with the shit tier economy system. fucking up the balance of the entire lavaland and material system because of people spamming one part of the system where its not meant to be used is stupid and there is other ways to fix this. 

Unless of course your planning a 100% lavaland overhall but I wish that pain on no one

2019-07-26 20:09 UTC, YakumoChen commented
![image](https://user-images.githubusercontent.com/10399117/61978612-3ef11480-afe1-11e9-8bb0-b934100e7b45.png)
lol

2019-07-26 20:21 UTC, ExcessiveUseOfCobblestone commented
The crux of the issue is lavaland features, not economy. This is what happens when you just scale items instead of properly balancing them to play nicely with the main aspect of the game.

>  imagine ash lizards are in that round? nearly endless spawning.

what does this have to do with medpens? This is true regardless of the PR's outcome.

2019-07-26 20:42 UTC, zombiegums commented
Leave miner medipens alone. The job they do is dangerous, gated by things like research, but is still vital for station progression. Slowing them down even further with this arbitrary change isn't engaging or fun.

2019-07-26 22:11 UTC, carlarctg commented
>get inevitably hit by goliath while using crusher
>take mask off, pop a pill
>instantly get the fake death hallucination because there's BZ in the air
>goliath comes over and kills you
dude....genius

2019-07-26 22:48 UTC, wesoda25 commented
You’re like 4dplanner except you have a terrible idea of balance

2019-07-27 00:00 UTC, Naloacisamazing commented
> what does this have to do with medpens? This is true regardless of the PR's outcome.

due to the fact that ashies advantage is numbers and miners is sustainability, if an ashie is beating a miner they can pop a medipen and shoot them with their high damage weapons. meaning that a single miner playing well can take out the endlessly spawning lizards due to the fact they can heal and take on large numbers. Ashies nearly always from what Ive seen rush miners extremely quickly because thats the best time to, removing medipens leads directly to mining being taken over by ash lizards. Causing the entire game to stop because everyone relies on mining. If this gets merged lavaland needs to be changed to suit the slower heals of on station. or rounds are going to start slowly down alot.

2019-07-27 00:33 UTC, kriskog commented
Don't actually merge this though, straight removal is NOT the solution to this problem. These medipens are designed around megafauna, and you simply do not get the same potency of limb recovery off station meds. Without it, any stray megafauna hit suddenly gets extremely debilitating and will probably lose you the fight. That's shitty, and it will make fighting on lavaland shitty.

Using the same meds as security/medbay on station is retarded, but we can put our heads together and come up with a solution to that too just like we do other shit.

tl;dr: Kneejerk removal bad, thinking good.

2019-07-27 01:19 UTC, elyina commented
Miners need a consistent form of healing to do their job.  Just make the medipens usable only on the lava planet. Who gives a fuck about ash liggers, begone scalie.

2019-07-27 02:22 UTC, SgtxRootbeer commented
Miners proved that inter dept cooperation works with old rnd.

This is along similar lines, and a good chemist will stack Chems like adrenals, meth, Sali, oxand, and whatever else so their pills heal fast. You can have them customize it to your preference!

If you need to inject faster, ask chem for your meds in a beaker and with a bluespace syringe.

2019-07-27 02:32 UTC, kriskog commented
1: No, thats not how anything chemistry related works. Chemists wont "customize it for you" because they can barely be relied on for normal non customized medbay medicine. Also, should miners be shit out of luck if the chemists are tots and ran off on a murderboner or are just plain new to the role? You will also not get nowhere near the same limb recovery, as I already said. 
And you can shove your meth, its shit for mining.

2: If I get deathly sick from miasma or get a slowdown/knockdown/stun halluzination from the bz while trying to eat a pill WHILE DODGING FUCKING BUBBLEGUM, that's not very fun/cool/engaging. No, syringes arent a very good solution to this, see point 1.


You can try to argue the same repeated point as many times as you'd like, but it still will not make this a good change.

2019-07-27 02:46 UTC, Whoneedspacee commented
>Miners proved that inter dept cooperation works with old rnd.

Yes OLD RND, where it was insanely easy to get whatever you wanted.

With new RND I struggle some rounds to get rnd to research what we need, even with the promise of materials sometimes they just skimp off and I have to break in.

If there's basically no incentive for rnd to help, they wont. Unless they're making like mechs and shit they pretty much don't need more materials than the first batch.

Nothing is 100% and you shouldn't force miners to not have healing chems or break into chemistry to get healing some rounds, that's just lame.

Survival medipen should just be like a brute + burn normal heal injection and increase the price. That way when they do cooperate it's better (as it should be), but they also have an option that doesn't include asking someone else for help.

Survival medipen should never have been as good as it is now that legion cores and medipens are meant to work in conjunction with one another, there's basically no reason that miners should have healing that heals that fast and also smaller heal over a long time.

Tl;dr just remove the op admin chem from survival medipens and they'll be fine.

2019-07-27 03:58 UTC, PKPenguin321 commented
at the absolute least these should instead make your movespeed do a `max(currentspeed, default_undamaged_speed)` so you can sprint out of a deadly situation

2019-07-27 04:10 UTC, optimumtact commented
![threadgoingbad](https://user-images.githubusercontent.com/2544323/61989831-17ee1d80-b089-11e9-879a-82bc1ff8545c.jpg)

2019-07-27 04:11 UTC, Shadowflame909 commented
That would help. But not by a whole lot. In exchange for the megafauna buff. They've gained some Stop-Gaps to prevent running away. Or they always had them. The Ash-Drakes Lava-Trap. The Hierophants Arena Wall. Bubblegums jaunt. (Used to have those shitty bloodlings that'd block movement as well. But it got removed for being undocumented.) Bloodlusted Miners Jaunt as well.

I mean, this change might have worked out when megafauna were still weak one-trick ponys. But their AI has REALLY smartened up thanks to @Whoneedspacee It's just a death-sentence.

Lastly, please do not **EVER** (x100) cite departmental cooperation as a potential fix to a mess of a PR.

Humans are Jerks and they don't do shit that isn;'t incentivized. Especially boring tedious stuff like making chems for others.

We can see this again and again with Chemistry V Botany.

We can see this much more recently with Stasis and how Cobblestone had to add in alternative methods of healing because chemistry isn't reliable at all. (And also rely on the vendors)

Also, another reason why this change would suck. Is because of a recent change you yourself made.

NO ONE. Is using medicine made by chemistry right now. They're relying on synth-flesh in the vendors. The Brute/Burn regular plain medikits, Cryo, and Cloning.

This new tier 2 medicine is too gimmicky and deadly that everyone instantly tosses it out and deems it worthless. 

Hell, Medical Borgs have decreased activity 10 fold. No one wants to use that death-trap.

This is a bust bro. No matter how you spin it.

2019-07-27 04:26 UTC, Akrilla commented
Can we talk about the actual problem yet? The mining point to cash PR? Overall good intentions/change, money more useful etc etc. Except... The point system was balanced around exactly that. The *point* system - not money, and certainly not the budgets each head gets. Either revert back to points, add player limited stocks of items, nerf budgets, or think of another wacky way of stopping medipen buying because it ain't this.

2019-07-27 07:07 UTC, MCterra10 commented
SgtxRootbeer: Chief, is this it?
Chief: This ain't it.

2019-07-27 07:53 UTC, Dawson1917 commented
Survival pens really need to be kept to miners via mining points. You know how I used them for that sweet, sweet **interdepartmental cooperation?** I traded them for favours. If I've been mining all round and people upgraded the ORM I'll have enough points to carry spare survival pens, and they're great for currying favour or getting people on your side. QM will give you a gun, robotics will give you augments, security might even look the other way, heads will usher you into the escape shuttle bridge, all for a taste of the healing pen. They don't imbalance the station when the only people with access to them are miners and a handful of people who traded with the miners. That's actual inter-departmental cooperation and player interaction which was dampened by mining points being turned into regular money, as the items are no longer so 'exclusive', but you can still win people's hearts with survival pens so long as they aren't a head of staff. Bring back good boy miner points.

2019-07-27 08:31 UTC, 81Denton commented
I don't see the value in keeping a one line web edit PR open, but I want to thank all of you for (mostly) remaining civil and giving really good input on alternative ways to solve this issue.

I personally think that departmental cooperation would not be a replacement for medipens, since chemists have no incentives to provide shaft miners with an elaborate healing cocktail at the start of each round. 
The interaction is completely one-sided, and I don't think that interactions where one side feels like a fast food cashier are fun or healthy for the game.

There are other approaches that I think would be a good solution:
1) Rebalancing the price and contents of medipens. They should give miners the opportunity to survive mistakes like stepping into lava - I'm sure that players with a ton of mining experience like @Whoneedspacee have a pretty good idea of what would be balanced.
2) Nerfing department budgets. Any price balancing done in 1) will be irrelevant if the CMO can just roll up with tens of thousands of credits for no effort.
3) As a long-term goal, lavaland content should be normalized. I know that Qustinnus is currently working on a lavaland project, but I'm not sure if it touches the monster hunting part.
4) Making interactions with chemistry less one-sided. I'd welcome anyone to take part in the discussion on the forums:
https://tgstation13.org/phpBB/viewforum.php?f=9

2019-07-27 08:31 UTC, closed without merging

2019-07-27 14:21 UTC, MCterra10 commented
So guys, we did it

2019-07-27 14:38 UTC, Akrilla commented
victory royale

2019-07-29 01:42 UTC, lolman360 commented
YES