Smokebomb changes.
tgstation/tgstation pull request #45504
Opened 2019-07-26 13:02 UTC by nemvar

## About The Pull Request

This is the most critical PR of 2k19.
Changes smoke grenade description.
Adds extremely useful documentation.
Does some general sanity changes, but who gives a fuck about that?

## Why It's Good For The Game

It's Hip.

## Changelog
:cl:
tweak: Smoke grenades are now double dank.
imageadd: Inhands for smokebombs.
/:cl:

2019-07-26 20:25 UTC, ExcessiveUseOfCobblestone commented
needs a sound effect that says "smoke bomb ev'ry day"

2019-07-27 09:37 UTC, actioninja requested changes

2019-07-27 09:37 UTC, actioninja commented on code/game/objects/items/grenades/smokebomb.dm
> +	desc = "Real bruh moment if you ever see this. Probably tell a c*der or something."
Smoke grenades are obtainable in game, real bruh moment right here.

2019-07-27 09:38 UTC, actioninja commented on code/game/objects/items/grenades/smokebomb.dm
> +	desc = "Real bruh moment if you ever see this. Probably tell a c*der or something."
the real bruh moment was within me all along, I just realized what you did.

2019-07-27 09:38 UTC, actioninja approved these changes
I'm just an idiot

2019-07-27 09:39 UTC, merged

2021-11-26 22:28 UTC, Bawhoppen commented
I'm still not sure why you made this change but 👍