Adds "you" to local visible_messages
tgstation/tgstation pull request #45631
Opened 2019-07-31 12:35 UTC by kingofkosmos

## About The Pull Request
Replaces [target], [user], etc. to "you" wherever it is the player who is receiving the message locally.

Before:
**`John Johnson hits Smith Smithson!`**

After:
**`John Johnson hits you!`**

Also makes some of the attack verbs to present tense ("hits" instead of "has hit").

## Why It's Good For The Game
Makes quickly glancing the chat more clear about who's doing what to whom in various situations, mostly in combat.

2019-07-31 17:55 UTC, Cyprex commented
Does this make "You hits thing" or "You hit thing"

2019-07-31 19:16 UTC, kingofkosmos commented
> Does this make "You hits thing" or "You hit thing"

I'm not totally sure what you mean, but I'm aiming for mostly "Someone hit you", because it also keeps open for more different phrasing for attack verbs like "Someone hits you" as well.

2019-08-01 05:28 UTC, ShadowDeath6 commented
I think they mean object damage like hitting a door or a light with a toolbox

2019-08-01 14:15 UTC, kingofkosmos commented
Oh yeah, it does change that! So before:
**`John Johnson hits the reinforced window with the fire axe!`**

Would now be:
**`You hit the reinforced window with the fire axe!`**

I was surprised myself, didn't realize to test that. I'm guessing it's this here what affects the change:
https://github.com/tgstation/tgstation/pull/45631/files#diff-638d9f4bf631ba885e06844ac34d7196R87

2019-08-01 14:30 UTC, kingofkosmos commented
Ready for reviewing.

2019-08-01 18:44 UTC, PKPenguin321 commented
Might make it harder to parse logs on the users end if they change names during the round

2019-08-05 08:42 UTC, actioninja commented
I'm really not sure what you mean by that @PKPenguin321

2019-08-05 08:57 UTC, actioninja requested changes
mostly just grammar fixes

2019-08-05 08:57 UTC, actioninja commented on code/datums/martial.dm
> +		D.visible_message("<span class='danger'>[A] knocked [D] down!!</span>", \
knocked > knocks

2019-08-05 08:57 UTC, actioninja commented on code/modules/food_and_drinks/drinks/drinks.dm
> +		M.visible_message("<span class='danger'>[user] is feeding [M] the contents of [src].</span>", \
I don't like the phrasing on this. back to attempts to feed would make more sense for what's happening.

2019-08-05 08:57 UTC, actioninja commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +				"<span class='userdanger'>[user] hits you[head_attack_message] with a bottle of [src.name]!</span>")
missing a space

2019-08-05 08:57 UTC, actioninja commented on code/modules/food_and_drinks/food/condiment.dm
> +		M.visible_message("<span class='warning'>[user] is feeding [M] from [src].</span>", \
same as the other message

2019-08-05 08:57 UTC, actioninja commented on code/modules/food_and_drinks/food/snacks.dm
> +										"<span class='userdanger'>[user] is feeding you [src].</span>")
ditto

2019-08-05 11:14 UTC, PKPenguin321 commented
Last I checked you can save your own client side text logs from the BYOND client, and if a user has multiple different names in a round it may be harder for them to locate specific lines
On second thought that is such an esoteric problem that it probably won't ever happen

2019-08-06 09:14 UTC, actioninja approved these changes

2019-08-06 09:15 UTC, merged