Cleans up card generation a little
tgstation/tgstation pull request #45784
Opened 2019-08-07 22:45 UTC by ShizCalev

Just condensing some code down, nothing really to note.

2019-08-09 20:29 UTC, Cyprex commented
Ace can be added to the persons for loop

2019-08-10 18:05 UTC, francinum commented
Not without breaking the order.

2019-08-10 22:56 UTC, Cyprex commented
This seems to change the order anyway?

2019-08-11 09:12 UTC, actioninja requested changes

2019-08-11 09:12 UTC, actioninja commented on code/game/objects/items/toys.dm
> +		for(var/i in (2 to 10))
this is setting off the linter, it's a known issue
```suggestion
		for(var/i in 2 to 10)
```

2019-08-18 17:59 UTC, SpaceManiac commented
7 day stale

2019-08-20 23:24 UTC, merged