[s]Wizards no longer get a free use of a touch spell by refunding the spell.
tgstation/tgstation pull request #46249
Opened 2019-08-30 02:03 UTC by bgobandit

## About The Pull Request

If a wiz refunds a touch spell (ei nath, etc.), if there is an active touch attack, that attack is deleted. This is probably not the greatest way codewise to do this, but it does it.

Fixes https://github.com/tgstation/tgstation/issues/46202.

## Why It's Good For The Game

Fixes an exploit.

2019-08-30 02:10 UTC, bgobandit commented
travis what the fuck

2019-08-30 02:14 UTC, ATH1909 commented
Thanks, man.

2019-08-30 16:38 UTC, ExcessiveUseOfCobblestone commented
https://github.com/tgstation/tgstation/blob/2029163d335356dc5f78ddf04f0750c4fa06c429/code/modules/spells/spell_types/godhand.dm#L53

```DM
if(!attached_spell && !(flags_1 & ADMIN_SPAWNED_1)) //No Spell, No Use (Unless Admin Bafoonery)
```

2019-08-30 16:48 UTC, bgobandit commented
ok yeah that's a way better fix

2019-08-31 09:19 UTC, PKPenguin321 commented
Actually I think the best method would be to tie removing the touch spell object into the removal proc of the spell action button

2019-08-31 09:27 UTC, PKPenguin321 requested changes
See above

2019-08-31 18:08 UTC, bgobandit commented
good call

2019-08-31 19:37 UTC, PKPenguin321 commented on code/modules/spells/spell_types/touch_attacks.dm
> +
..()

2019-08-31 19:38 UTC, PKPenguin321 commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +
run `git checkout upstream/master -- code/modules/antagonists/wizard/equipment/spellbook.dm` to totally undo all changes to this file

2019-08-31 19:42 UTC, PKPenguin321 commented on code/modules/spells/spell_types/touch_attacks.dm
> +			qdel(T)
no need for any this, there's already a proc to handle it; run `remove_hand()`

2019-09-03 04:27 UTC, merged