equip sounds
tgstation/tgstation pull request #46387
Opened 2019-09-07 10:19 UTC by actioninja

## About The Pull Request

Adds support for equip sounds for items, currently only for jumpsuits and belts as a proof of concept.

## Why It's Good For The Game

muh immulsions

## Changelog
:cl:
soundadd: support for equip sounds, with jumpsuits and toolbelts serving as a proof of concept
/:cl:

2019-09-08 19:58 UTC, cacogen commented
when i go "view raw" the fucking thing doesn't play for me so i have to download it
as a fan of your sounds i put them on the internet to prevent others having to share the same fate:

[toolbelt_equip](https://sndup.net/4qq6/toolbelt_equip.ogg)
[jumpsuit_equip](https://sndup.net/7kwh/jumpsuit_equip.ogg)

2019-09-09 17:00 UTC, ninjanomnom requested changes

2019-09-09 17:00 UTC, ninjanomnom commented on code/game/objects/items/storage/belt.dm
> +	equip_sound = "sound/items/equip/toolbelt_equip.ogg"
single quote

2019-09-09 17:00 UTC, ninjanomnom commented on code/modules/clothing/under/_under.dm
> +	equip_sound = "sound/items/equip/jumpsuit_equip.ogg"
single quote

2019-09-11 19:37 UTC, ninjanomnom approved these changes

2019-09-11 19:37 UTC, merged