creamed component
tgstation/tgstation pull request #46496
Opened 2019-09-14 10:24 UTC by spookydonut

## About The Pull Request
I have no mouth but I must scream

## Why It's Good For The Game
creampie.dmi

2019-09-14 10:29 UTC, optimumtact commented
absolutely based and component pilled beyond belief

2019-09-14 13:43 UTC, Fikou commented
can you make the unused creampie images for xenos borgs and monkeys not be unused thanks

2019-09-14 16:20 UTC, spookydonut commented
> 
> 
> can you make the unused creampie images for xenos borgs and monkeys not be unused thanks

the what

2019-09-14 18:23 UTC, ExcessiveUseOfCobblestone commented
stop

2019-09-16 02:36 UTC, ghost approved these changes
very good use of components. Good job.

2019-09-16 02:36 UTC, Qustinnus commented on code/__DEFINES/components.dm
> +#define COMSIG_COMPONENT_CLEAN_FACE_ACT "clean_face_act"		//called when you wash your face
Add params

2019-09-16 02:36 UTC, Qustinnus commented on code/__DEFINES/components.dm
> +#define COMSIG_COMPONENT_CLEAN_FACE_ACT "clean_face_act"		//called when you wash your face
And source

2019-09-17 15:03 UTC, ninjanomnom requested changes

2019-09-17 15:03 UTC, ninjanomnom commented on code/datums/components/creamed.dm
> +	pie_hit(source, stunning)
This component has too many functions. The effects of the pie hitting shouldnt be tied to the graphics for it in component code.

2019-09-17 15:03 UTC, ninjanomnom commented on code/datums/components/creamed.dm
> +	pie_hit(source, stunning)
No, the args are passed as a list, not individual arguments

2019-09-24 15:17 UTC, merged