Call me daddy
tgstation/tgstation pull request #46628
Opened 2019-09-19 10:39 UTC by spookydonut

## About The Pull Request
Adds linting for top level procs that send signals

2019-09-19 12:47 UTC, JJRcop commented
Your PR title is disgusting

2019-09-23 19:27 UTC, ExcessiveUseOfCobblestone commented
daddy

2019-09-25 18:52 UTC, ninjanomnom requested changes
You should know that no one wants to review this kind of mass change, break it up

2019-09-25 18:52 UTC, ninjanomnom commented on code/game/machinery/porta_turret/portable_turret_cover.dm
> +	SHOULD_CALL_PARENT(0)
If you're not willing to go through the whole proc chain to make them all call parent don't bother adding the linting yet.

2019-09-25 18:52 UTC, closed without merging