Replace some sleep()s with timers
tgstation/tgstation pull request #46631
Opened 2019-09-19 12:36 UTC by spookydonut

## About The Pull Request
Not as many easily replaced as with spawn()s

2019-09-19 12:39 UTC, Cyprex commented
I find it easier to read with sleeps

2019-09-19 13:46 UTC, Qustinnus commented
yeah well I find it easier to play without them

2019-09-20 06:04 UTC, ShizCalev requested changes

2019-09-20 06:04 UTC, ShizCalev commented on code/game/objects/items/devices/taperecorder.dm
> +	addtimer(VARSET_CALLBACK(src, canprint, 1), 30 SECONDS)
TRUE

2019-09-22 10:01 UTC, merged