people doing dissections get paid with rnd funds
tgstation/tgstation pull request #46780
Opened 2019-09-28 09:49 UTC by Tlaltecuhtli

:cl:
tweak: people doing dissections get paid with sci funds with a 0.3 multiplier
/:cl:

it doesnt generate money, gives incentives to people helping rnd and works in cryptocurrency based societies

2019-09-28 14:58 UTC, MacBlaze1 commented
* comments valid criticism* gets blocked 

s-sad!! No but seriously this is a good idea, medical doctors need love

2019-09-30 00:09 UTC, ExcessiveUseOfCobblestone commented
Research shouldn't be a science exclusive activity though 😏

2019-10-07 16:19 UTC, ExcessiveUseOfCobblestone commented
FYI I haven't merged this because RND shouldn't be considered a science activity. The plan is still (to my knowledge) to move it out of science, it just hasn't been done yet.

2019-10-07 18:01 UTC, PKPenguin321 requested changes

2019-10-07 18:01 UTC, PKPenguin321 commented on code/modules/surgery/experimental_dissection.dm
>  	target.apply_damage(80, BRUTE, L)
I kind of hate that all of this code is ran in the surgery itself, seems too magical to have your ID automagically paid. There should be a Claim Credits button on the surgery console that's created when the surgery is finished, and can be swiped by anybody.

2019-10-07 18:02 UTC, PKPenguin321 commented
>FYI I haven't merged this because RND shouldn't be considered a science activity.

I had assumed this would be a medbay activity, not an RND one, so it should totally fit within this idea

2019-10-07 20:29 UTC, ExcessiveUseOfCobblestone commented
Medbay will typically do the surgery (maybe robros do it too, idk) but the act of progressing via RND is a stationwide activity, not a science activity. It doesn't make sense for it to automatically pull out of science funds when they aren't (SUPPOSE TO BE, at least) managing the flow of research.

It's just no one has changed it yet 😏

2019-10-08 23:42 UTC, ExcessiveUseOfCobblestone commented
Staling this until someone says "no we no longer want to pull RND out of science"

2019-10-09 17:30 UTC, Tlaltecuhtli commented
the funds are called "research funds" and the research director holds the research funds, he has all interest into pay people to do research, it makes sense they are paid by research funds

2019-10-09 18:04 UTC, ExcessiveUseOfCobblestone commented
> the funds are called "research funds" /// research director holds the research funds

I don't care what it's called, it's the science department budget.

> he has all interest into pay people to do research

That's because currently he controls the flow of what gets unlocked for the purpose of techwebs. The proper fix is to move it out of research.

> it makes sense they are paid by research funds

because rnd is currently restricted to science. It will no longer make sense to pull from the science budget when unlocking content via the rnd computer is not bound to what scientists like/don't like as was the intention of techwebs.

Personally I think it would be cool to not have all of the RP go to the cloud, but instead a portion of it goes on the person('s card?), then they can trade it as a secondary currency (with the intention these points can only be accessed by the person holding them). 

That would also encourage use since it feels like you personally get rewarded instead of doing it for the benefit of others (even though for the most part you still are).

2019-10-10 07:54 UTC, Tlaltecuhtli commented
you want an item that gets turned into rnd poins?

2019-10-10 17:45 UTC, ExcessiveUseOfCobblestone commented
not necessarily a physical representation like holochips, but I'd like a localized version of RP points that the user has control over and therefore can trade with/for to reserve points.

Basically you'd have the public pool (what we have now) that most of the points go to, but you'd also have your local pool that can only be used by you until you donate/trade it.

This is on top of throwing RND out of science so other heads can use the machine.

2019-10-10 22:24 UTC, closed without merging