Donuts! New foods! Nuggbox! Bowl resprite.
tgstation/tgstation pull request #46933
Opened 2019-10-07 03:02 UTC by Krysonism

## About The Pull Request

TBA

## Why It's Good For The Game

TBA

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2019-10-07 03:17 UTC, carshalash commented
Nice sprites!

2019-10-07 03:28 UTC, Krysonism commented
I will update the PR with more information once i get to work.

2019-10-07 03:45 UTC, Potato-Masher commented
Blessed bowl sprite, actually looks like a bowl.

2019-10-07 05:21 UTC, GuyonBroadway commented
Rename the nugbox to be a box of nugs so its a play on the box of hugs the clown spawns with.

2019-10-07 06:30 UTC, ArcaneMusic commented
Not only does the food look better, but the bowl looks like it was WASHED

2019-10-08 04:40 UTC, Farquaar commented
>He removed cherry jelly donuts
Why even live anymore?

2019-10-08 07:15 UTC, PKPenguin321 commented
>Rename the nugbox to be a box of nugs so its a play on the box of hugs the clown spawns with.

Do you realize the box of hugs is a reference to the phrase "hugbox," which "nugbox" is already seemingly a parody of

2019-10-08 07:17 UTC, GuyonBroadway commented
>Do you realize the box of hugs is a reference to the phrase "hugbox," which "nugbox" is already seemingly a parody of


Very much so but this game of chinese whispers could end up somewhere funny.

Box of bugs up next.

2019-10-08 08:01 UTC, Krysonism commented
I have done some more testing and have noticed two bugs. 

Electron soup does not delete it's ingredients upon crafting

The plain donut recipe shows up twice in the crafting menu

2019-10-15 14:27 UTC, 81Denton commented
Merge conflicts ahead

2019-10-19 04:32 UTC, Krysonism commented
I will resolve conflict and take another look at this tomorrow

2019-10-20 12:18 UTC, Krysonism commented
This compiles and crafting the electron soup seems to work. It should be ready for merge.

2019-10-20 12:33 UTC, 81Denton requested changes
You just need to remove a few duplicate definitions/fix typos and this is good to go.

2019-10-20 12:33 UTC, 81Denton commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +		new /datum/stack_recipe("nuggetbox box", /obj/item/storage/fancy/nugget_box),			\
```suggestion
		new /datum/stack_recipe("nugget box", /obj/item/storage/fancy/nugget_box),			\
```

2019-10-20 12:33 UTC, 81Denton commented on code/game/objects/items/storage/fancy.dm
> +/obj/item/storage/fancy/heart_box/ComponentInitialize()
```suggestion
/obj/item/storage/fancy/nugget_box/ComponentInitialize()
```

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
/obj/item/reagent_containers/food/snacks/donut already has `is_decorated` set to FALSE, no need to define it twice.

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
same here

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
same here

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
same here

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
same here

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
same here

2019-10-20 12:33 UTC, 81Denton commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
>  	subcategory = CAT_PASTRY
/datum/crafting_recipe/food/donut already has `subcategory` set to CAT_PASTRY, no need to define it twice

Same goes for all the other child datums like /datum/crafting_recipe/food/donut/slimejelly

2019-10-20 12:46 UTC, Krysonism commented on code/modules/food_and_drinks/food/snacks_pastry.dm
> +	is_decorated = FALSE
fixed

2019-10-20 12:55 UTC, merged

2019-10-23 23:38 UTC, wesoda25 commented
@Krysonism this PR was fucking excellent and by far is my favorite feature ive seen in game since i took a break. bravo keep up the good work.