Cleans up revive related procs
tgstation/tgstation pull request #47025
Opened 2019-10-11 20:03 UTC by 81Denton

This PR cleans up revive proc related code. Now it's possible to easily check which procs use full_heal and/or admin_revive too.

2019-10-15 19:09 UTC, ninjanomnom requested changes

2019-10-15 19:09 UTC, ninjanomnom commented on code/modules/mob/living/silicon/ai/ai.dm
> +/mob/living/silicon/ai/revive()
This seems backwards, all the procs should have the arguments so that keyword arguments can still be used.

Why are you doing this?

2019-10-16 14:40 UTC, ninjanomnom requested changes

2019-10-16 14:40 UTC, ninjanomnom commented on code/modules/mob/living/silicon/robot/robot.dm
> +/mob/living/silicon/robot/revive(admin_revive = FALSE)
you need all the vars for every subtype

2019-10-16 14:40 UTC, ninjanomnom commented on code/modules/mob/living/living.dm
> +/mob/living/proc/fully_heal(admin_revive = FALSE)
Ditto

2019-10-22 11:31 UTC, actioninja commented
conflict

2019-10-22 11:31 UTC, actioninja submitted a review, later dismissed

2019-10-22 13:19 UTC, 81Denton commented
Alright, merge conflicts are gone.

2019-10-22 22:16 UTC, merged