tgui-next: Low level stuff
tgstation/tgstation pull request #47122
Opened 2019-10-16 11:07 UTC by stylemistake

## About The Pull Request

- [x] Warn about lowercase onclick handlers.
    - This was a common source of bugs on some russian tgstation fork, educational warnings are always good.
- [x] Use camelcase `tabIndex` on buttons.
    - Performance improvement mostly
- [x] Improve byond cache path searching,
    - Faster and more optimal cache reloading.
- [x] Add WSL-specific paths to cache reloader.
    - Official out of the box support for WSL, no more symlinkage.
- [x] Use `url-loader` for inlining images as base64.
    - No more manual inlining of SVGs in CSS.
- [x] Reload once by calling `bin/tgui --reload`
    - In that special case when you want to simply reload the build you currenty have in `public` folder.
- [x] Do not truncate objects in logger
    - Now we use `util.inspect` to show objects in its full glory. Free color support too.
- [x] Logging will now send objects with circular references without crashing.

## Why It's Good For The Game

Improved developer experience.

## Changelog
:cl:
tweak: Few development related improvements for tgui-next
/:cl:

2019-10-18 01:21 UTC, stylemistake commented
Added some more things, found no bugs on a local server.

2019-10-18 22:15 UTC, stylemistake commented
Rebased on top of Coin Press UI. Added eslint react plugin, since linter wasn't checking for react bugs and code style. Still ready to merge.

2019-10-20 06:00 UTC, actioninja requested changes
tiny complaint

2019-10-20 07:18 UTC, stylemistake commented on tgui-next/packages/tgui-dev-server/link/client.js
> +  cache = null;
This is to improve garbage collection, especially on IE8.

2019-10-20 14:49 UTC, merged