[s] Fixes an href exploit related to shuttle docking
tgstation/tgstation pull request #47149
Opened 2019-10-17 08:45 UTC by actioninja

## About The Pull Request

As title
closes #47142 

## Changelog
:cl:
fix: Fixed an href exploit related to shuttle docking
/:cl:

2019-10-17 08:51 UTC, AnturK requested changes

2019-10-17 08:51 UTC, AnturK commented on code/modules/shuttle/computer.dm
> +			to_chat(usr, "<span class='userdanger'>I'm sure your \"Special\" sock would be proud of you for this action.</span>") // thanks citruses
No.

2019-10-17 10:18 UTC, actioninja commented on code/modules/shuttle/computer.dm
> +			to_chat(usr, "<span class='userdanger'>I'm sure your \"Special\" sock would be proud of you for this action.</span>") // thanks citruses
fun police

2019-10-17 15:37 UTC, GravitronBlue commented on code/modules/shuttle/computer.dm
> -			to_chat(usr, "<span class='userdanger'>I'm sure your \"Special\" sock would be proud of you for this action.</span>") // thanks citruses
👀

2019-10-17 17:09 UTC, GravitronBlue commented on code/modules/shuttle/computer.dm
> +			to_chat(usr, "<span class='userdanger'>I'm sure your \"Special\" sock would be proud of you for this action.</span>") // thanks citruses
Wsock reference?
Personally don't need client-side hacks to find href exploits like this, nor do I support griefing when it isn't at least funny, which is mostly why I'm trying to find and get abusable hrefs fixed.

2019-10-18 00:33 UTC, ninjanomnom approved these changes

2019-10-18 05:46 UTC, merged