Xeno impreg now gets stopped by stasis
tgstation/tgstation pull request #47307
Opened 2019-10-22 16:04 UTC by nemvar

## About The Pull Request

title. Xeno eggs where getting processed both by their owner and SSobj.

## Why It's Good For The Game

Bugs bad.

## Changelog
:cl:
fix: Xeno and changeling impregnation times now get stopped by stasis. Also fixes a bug where they were growing up almost twice as fast as intended.
/:cl:

2019-10-22 17:36 UTC, ATH1909 commented
> Also fixes a bug where they were growing up almost twice as fast as intended.

Could you halve the "intended" gestation time, then? I do appreciate this bug being fixed, but I feel like doubling the already long alien larva gestation times is going to negatively impact xeno balance/fun (especially for alien queens, who'll now have to wait around twice as long for a larva to emerge from the body of their first victim).

2019-10-22 18:06 UTC, PKPenguin321 commented
I kinda hate this since it makes xeno egg removal not very urgent

2019-10-22 19:31 UTC, nemvar commented
It's now the time it took a few months ago. It's just that nobody noticed that it's actually half the time it used to be.

2019-10-23 17:04 UTC, shellspeed1 commented
Gonna throw my 2 cents in here, maybe instead of xeno's being frozen, we should make it so they don't gib when they hatch so doctors have a chance to save the patient.

2019-10-23 18:57 UTC, AnturK requested changes

2019-10-23 18:57 UTC, AnturK commented on code/game/objects/items/body_egg.dm
> +/obj/item/organ/body_egg/Initialize(loc)
Param is incorrect now.

2019-10-27 19:21 UTC, merged