Makes toilets and sinks constructable
tgstation/tgstation pull request #47320
Opened 2019-10-22 21:54 UTC by defiantGrace

## About The Pull Request
Makes toilets and sinks constructable

## Why It's Good For The Game
I took a poo in a plasma toilet and that's just peachy

## Changelog
:cl:
add: makes toilets constructable
add: makes sinks constructable
/:cl:

2019-10-22 22:13 UTC, ninjanomnom requested changes

2019-10-22 22:13 UTC, ninjanomnom commented on code/game/objects/structures/watercloset.dm
>  /obj/structure/toilet/update_icon()
Switch this to update_icon_state while you're here
```suggestion
/obj/structure/toilet/update_icon_state()
```

2019-10-22 23:05 UTC, MCterra10 commented
Good first pr 👍

2019-10-23 00:45 UTC, ArcaneMusic commented
Not even just constructable, but constructable with datum mats too? Nice!

2019-10-23 01:10 UTC, MCterra10 commented
Please make it so that we can buckle people to toilets. I want to buckle people to uranium toilets and irradiate them

2019-10-23 04:01 UTC, fludd12 commented
Next is to make them and showers valid plumbing connections

2019-10-23 05:03 UTC, TheChosenEvilOne commented
Should shift the sinks a bit i'd say, they don't look that great when separated from the wall.

2019-10-23 06:53 UTC, carlarctg commented
plasma shower please

2019-10-23 07:00 UTC, dr-bee commented
Time to make that solid gold toilet ive always wanted.

2019-10-25 23:33 UTC, merged