Added a period
tgstation/tgstation pull request #47391
Opened 2019-10-25 15:10 UTC by Derpyhsi

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2019-10-25 15:23 UTC, Ty-the-Smonk commented
This needs actual documentation

2019-10-25 16:40 UTC, FloranOtten commented
Overdocumented features

2019-10-25 22:27 UTC, Epsilos commented
very informative

2019-10-25 23:34 UTC, actioninja requested changes
put a proper description

2019-10-27 00:54 UTC, optimumtact commented
this is a spam bot building up reputation

2019-10-27 00:54 UTC, closed without merging