Fixes guardian summoners not dusting properly
tgstation/tgstation pull request #47403
Opened 2019-10-26 02:59 UTC by Neo-0

## About The Pull Request
Fixes #47238 

## Changelog
:cl:
fix: Holoparasite summoners now properly dust when their guardians are cremated
/:cl:

2019-10-26 06:48 UTC, nemvar commented
Remove the dusting code from Life() and move that here.

2019-10-26 16:39 UTC, YPOQ requested changes

2019-10-26 16:39 UTC, YPOQ commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +			death(TRUE)
This looks like infinite recursion

2019-10-26 16:39 UTC, YPOQ commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +		death(TRUE)
.

2019-10-26 16:55 UTC, Neo-0 commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +			death(TRUE)
no, it works

2019-10-30 19:15 UTC, AnturK requested changes
Please explain how is this supposed to work because it doesn't make any sense right now.

2019-10-30 19:15 UTC, AnturK commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +		death(TRUE)
This is just recursively calling itself without any escape ? Same above.

2019-10-30 19:15 UTC, AnturK commented on code/modules/mob/living/simple_animal/guardian/guardian.dm
> +			visible_message("<span class='danger'><B>\The [src] dies along with its user!</B></span>")
These don't really make sense if the death was initiated by the guardian.

2019-10-30 19:28 UTC, Neo-0 commented
Initially this PR was made to fix this issue #47238 
I'll leave it the way it was, fixing the issue
I'm not a coder

2019-11-03 09:53 UTC, merged