Fixes disease outbreak secret
tgstation/tgstation pull request #47541
Opened 2019-11-02 06:26 UTC by kriskog

## About The Pull Request
The "Trigger a Virus Outbreak" button in secrets had some big issues. The custom one didn't update biotypes properly, and the random and non-advanced disease buttons flat out didnt work. Custom disease now lets you target a specific human.

## Why It's Good For The Game
Fixes

## Changelog
:cl: Skoglol
admin: "Trigger a Virus Outbreak" button fixed, targeting added to custom disease.
/:cl:

2019-11-05 00:52 UTC, ATH1909 commented
This doesn't happen to fix this issue (https://github.com/tgstation/tgstation/issues/47359), does it?

2019-11-05 06:48 UTC, kriskog commented
Nope

2019-11-06 18:32 UTC, AnturK requested changes

2019-11-06 18:32 UTC, AnturK commented on code/datums/diseases/advance/advance.dm
> +		var/target = input("Pick a viable human target for the disease.", "Disease Target") as null|anything in targets
You have explicit user here, use it instead of usr.

2019-11-06 18:32 UTC, AnturK commented on code/datums/diseases/advance/advance.dm
> +					break
Should probably let the user know if it can't find infectable human.

2019-11-06 19:32 UTC, kriskog commented
Done

2019-11-06 19:42 UTC, merged