Moves achievements from Hub to DB.
tgstation/tgstation pull request #47617
Opened 2019-11-06 14:02 UTC by AnturK

Drops byond hub support and adds score and top 50 browsers.

Requires DB changes and manual creation of migration script if we want to keep old achievements so no random merges please.

2019-11-07 02:59 UTC, PKPenguin321 commented
>so no random merges please.

If you put [DNM] into your title it will append a Do Not Merge tag automatically

2019-11-07 05:02 UTC, stylemistake commented on tgui-next/packages/tgui/interfaces/Achievements.js
> +                {
Please do not use this style of braces. Format it as all other code.

2019-11-07 05:05 UTC, stylemistake commented on tgui-next/packages/tgui/interfaces/Achievements.js
> +                }
You know, it could've been 3 lines of code, you made it 7.

Not only that, you also run off the 80 character mark. Structure it vertically.

2019-11-07 05:07 UTC, stylemistake commented on tgui-next/packages/tgui/interfaces/Achievements.js
> +import { LabeledListItem } from '../components/LabeledList';
Remove this import, and use a `LabeledList.Item` instead.

2019-11-18 11:18 UTC, Jordie0608 requested changes

2019-11-18 11:18 UTC, Jordie0608 commented on tools/HubMigrator/HubMigrator.dm
> +/mob/verb/generate_migration_script()
I think this'd be better as an external script. I've used python for parsing byond.com before and it handled the volume and inserting to DB oodles better than byond did https://github.com/tgstation/tgstation/blob/master/SQL/populate_key_2018-07-09.py

On other hand I won't blame you if you don't want to rewrite this, it looks like a hassle.

2019-11-18 11:18 UTC, Jordie0608 commented on code/datums/achievements/_achievement_data.dm
> +		var/key = Query.item[1]
I can't comment on the line but line 4 `var/key` is used to store a ckey and this is confusing when that's an actual client var as well, rename it to something like `var/owner_ckey`

2019-11-18 11:33 UTC, AnturK commented on code/datums/achievements/_awards.dm
> +	var/datum/DBQuery/Q = SSdbcore.NewQuery("INSERT INTO [format_table_name("achievements")] (ckey, achievement_key, value, last_updated) VALUES ('[sanitizeSQL(key)]', '[sanitizeSQL(hub_id)]', '[sanev]'
Yeah, this is just remnant of the hub code, should probably be moved out.

2019-11-18 11:41 UTC, Jordie0608 commented on code/datums/achievements/_awards.dm
> +	var/datum/DBQuery/Q = SSdbcore.NewQuery("INSERT INTO [format_table_name("achievements")] (ckey, achievement_key, value, last_updated) VALUES ('[sanitizeSQL(key)]', '[sanitizeSQL(hub_id)]', '[sanev]'
Side note for a tiny bit of efficiency, remove `last_updated` from the insert and update part of this query and change the schema for that column to 
`DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,` so the update automatically changes the timestamp for 32 bytes less per row.
I doubt that'll mean any noticeable difference but it's cool and stylish.

2019-11-18 11:42 UTC, Jordie0608 commented on tools/HubMigrator/HubMigrator.dm
> +/mob/verb/generate_migration_script()
nevermind thanks byond api

2019-11-26 06:45 UTC, optimumtact commented on SQL/tgstation_schema_prefixed.sql
> +DROP TABLE IF EXISTS `SS13_achievements`;
SS13achievements

2019-11-26 06:51 UTC, optimumtact commented
DB is now at 5.4 and acheves table exists

2019-11-26 06:53 UTC, optimumtact commented on SQL/database_changelog.txt
> +INSERT INTO `SS13_schema_revision` (`major`, `minor`) VALUES (5, 4);
SS13schema_revision

2019-11-26 06:54 UTC, optimumtact commented
wow ignore those comments about the table names, seems like neither the prefixed or prefixed versions exactly match the actual table naming scheme lol

2019-11-26 07:35 UTC, merged