Some ghost improvements
tgstation/tgstation pull request #47700
Opened 2019-11-10 20:37 UTC by kriskog

## About The Pull Request
Ghosts can now change the direction they are facing by using ctrl+dir.
Ghosts that use the "Restore Ghost Character" verb now has their ghost mobs name changed, and gets it reapplied whenever the ghost is made again for the mind.

## Why It's Good For The Game
Ghosts are people too

## Changelog
:cl: Skoglol
add: Ghosts can now turn using the ctrl + direction hotkeys.
fix: The "Restore Ghost Character" verb now changes the name of your ghost mob as well.
/:cl:

2019-11-13 18:35 UTC, ninjanomnom requested changes

2019-11-13 18:35 UTC, ninjanomnom commented on code/modules/mob/mob.dm
> +	if((stat == DEAD || stat == UNCONSCIOUS) && isliving(src))
override the observer canface

2019-11-13 18:44 UTC, kriskog commented on code/modules/mob/mob.dm
> +	if((stat == DEAD || stat == UNCONSCIOUS) && isliving(src))
Hm, yeah I guess thats smarter

2019-11-14 00:33 UTC, kriskog commented on code/modules/mob/mob.dm
> +	if((stat == DEAD || stat == UNCONSCIOUS) && isliving(src))
Done

2019-11-14 01:52 UTC, merged