Adds immersion and realism to internals tank suicides
tgstation/tgstation pull request #47714
Opened 2019-11-11 17:32 UTC by SteelSlayer

## About The Pull Request
When you suicide with an internals tank, normally you just fall over and gib immediately. Now you get to see people inflate from inhaling the gas in the tank before they explode. I can still tweak how it looks but this is what I have so far:

![GIF](https://user-images.githubusercontent.com/42044220/68607138-907cbc80-0475-11ea-9305-c66d6660bf4e.gif)

## Changelog
:cl:
tweak: When you suicide using an internals tank, you're character will now inflate, and grow in size before you gib.
code: Adds a safe_gib argument to the carbon gib proc. Allows you to specifiy if you want to preserve the items on the mob you're gibbing.
/:cl:

2019-11-11 17:34 UTC, Tumesuo commented
Fetish content, speedmerge.

2019-11-11 17:43 UTC, nemvar commented
This doesn't make people uncloneable after they commit die.

2019-11-11 17:51 UTC, SteelSlayer commented
@nemvar Is it the MANUAL_SUICIDE_NONLETHAL that breaks it?

2019-11-11 17:55 UTC, nemvar commented
Yep, that return value requires you to manually set the suicide flag.

2019-11-11 19:30 UTC, TheVekter commented
Definitely fetish material. I'm ~~aroused~~ disgusted.

2019-11-11 22:59 UTC, PepperPrepper commented
I'd add this to mint toxins as well

2019-11-12 00:29 UTC, wesoda25 commented
Does mint toxin even work

2019-11-12 03:18 UTC, Shadowflame909 commented
>Does mint toxin even work 

Yes.

Surprising to say, I don't hate this. Even though its fetish content, all the good times of watching tom and jerry cartoons overwrite the negative connotation. 

Nostalgia > Furrys

2019-11-12 03:32 UTC, SteelSlayer commented
Everyone saying this is fetish content is probably fucked in the head, and I suggest you take a break from the internet. Also what do furries have to do with this? :thinking:

2019-11-12 03:57 UTC, Shadowflame909 commented
I don't want to assume by your sprite..

And how you code on the paradise code-base.

2019-11-12 04:00 UTC, PepperPrepper commented
I agree with @SteelSlayer How the fuck is this fetish content?

I mean I get the whole everything that is weird is fetish content joke we have running, But if anyone think this is some form of fetish is just being stupid.

Who takes sexual pleasure in watching someone/being inflated till they pop?

2019-11-12 04:01 UTC, Couls commented
> I don't want to assume by your sprite..
> 
> And how you code on the paradise code-base.

How is this related to the PR though? someone's profile pic or past works shouldn't affect the content of the PR it doesn't become fetish content because someone has a lewd profile pic but posts a PR

2019-11-12 04:09 UTC, Shadowflame909 commented
> 
> 
> I agree with @SteelSlayer How the fuck is this fetish content?
> 
> I mean I get the whole everything that is weird is fetish content joke we have running, But if anyone think this is some form of fetish is just being stupid.
> 
> Who takes sexual pleasure in watching someone/being inflated till they pop?

There's literally an ss13 server called Vorestation.

/TG/ has merged PRs getting rid of anything related to that. Like fat, humans being able to eat monkeys, and Xenos doing the same.

Is it innocence?!? Or is it argumentative ignorance to ignore the horrifying truth of the matter!

2019-11-12 04:14 UTC, wesoda25 commented
Sorry shadowflame i dont quite follow could you please elaborate?

2019-11-12 04:15 UTC, TheVekter commented
Holy shit I was joking guys, are you serious?

2019-11-12 04:25 UTC, Shadowflame909 commented
I'm not going to tell the tale of one of 4chans greatest enemies on github because that's dumb and would stray away from the PR.

I'd be happy to do it on the forums though.

All in All, to save you all the time and strain of losing your innocence.

An Inflation fetish is a very very very real thing.

2019-11-12 04:26 UTC, SteelSlayer commented
You'll have to forgive me as I'm new to the codebase and I don't know all the memes yet. 

But anyway, this is not intended as fetish content. I have no desire to put any ERP, or vore content into the game. This is just a 3 second animation I made for fun testing out some new stuff I've never worked with before, that's it.

2019-11-12 04:46 UTC, TheVekter commented
I legit do _not_ care if someone comes on our server, kills themselves with an airtank, and gets a semi from it. You can only do it once a round, it's nowhere near as concerning as ERP or those goddamn locking outfits, it's a cool animation that has more than one use. If people haven't been using the mint to jerk off, they're not gonna use this.

Merge it, it looks great, it's a funny suicide that could use more work making it look better. Hard +1.

2019-11-12 05:45 UTC, SteelSlayer commented
Yeah I'll see about doing that, and maybe adding this to the mint toxin too.

2019-11-12 05:59 UTC, anconfuzedrock commented
I accidentally made it easy to do airtank suicides again, I need to make the pressure requirement higher now.

2019-11-12 12:08 UTC, Tumesuo commented
God how will i able to play as hop without popping a boner? Can you make it so that wizards can timestop to make the animation freeze? :flushed:

2019-11-12 18:33 UTC, SteelSlayer commented
Alright I made some final adjustments, and added the animation to the mint gib for fat people too. I'm not gonna add the floor tile damage as none of the other gibs do that.. plus I don't know how to without causing an explosion :smile:. 

I'm going to call this completed and ready for review/merge.

2019-11-12 20:01 UTC, PKPenguin321 commented
the PR that made dobson join /tg/station

2019-11-12 21:08 UTC, Shadowflame909 commented
> the PR that made dobson join /tg/station

Told you zoomers it's 4chan history

2019-11-12 21:19 UTC, Timonkeyn commented
I still don't understand how you consider xeno eating humans fetish content, as it was a useful tool and xeno queen dragging someone is basically walk crawl speed right now

2019-11-12 21:46 UTC, Couls commented
speedmerge so people shut up about fetish content

2019-11-13 11:12 UTC, actioninja requested changes

2019-11-13 11:12 UTC, actioninja commented on code/modules/mob/living/carbon/death.dm
> +	if(safe_gib) // If you wan't to keep all the mob's items and not have them deleted
tiny, but `wan't`

2019-11-14 00:47 UTC, merged