Some small random tgui-next uis
tgstation/tgstation pull request #47712
Opened 2019-11-11 11:31 UTC by actioninja

## About The Pull Request

Holodeck:
![image](https://user-images.githubusercontent.com/5194834/68582918-be8bdd80-0430-11ea-8ab9-68c56c17f820.png)

Engraved messages:
![image](https://user-images.githubusercontent.com/5194834/68582931-c64b8200-0430-11ea-8654-6a1ae2f0baa9.png)

DNA Vault:
![image](https://user-images.githubusercontent.com/5194834/68583145-54276d00-0431-11ea-9c9b-e6d355bd0de2.png)

## Why It's Good For The Game

good ui yes

## Changelog
:cl:
add: DNA vault, holodeck, and engraved message tgui-next
/:cl:

2019-11-11 12:29 UTC, actioninja commented
Something is broken with build checking, I confirmed 3 times that this in fact the proper build for this pr.

2019-11-11 14:06 UTC, Tharcoonvagh commented
Safe ui too please

2019-11-11 21:11 UTC, stylemistake commented
@actioninja my local build differs too, so the best guess is that somehow your local `node_modules` folder got fucked up, and you need to clean build.

```
bin/tgui --clean
bin/tgui
```

2019-11-16 13:34 UTC, stylemistake approved these changes

2019-11-17 18:37 UTC, AnturK requested changes

2019-11-17 18:37 UTC, AnturK commented on code/game/objects/structures/ghost_role_spawners.dm
> +	important_info = "Do NOT leave the hotel, as that is grounds for contract termination.</b>"
`</b>`

2019-11-18 01:10 UTC, actioninja commented on code/game/objects/structures/ghost_role_spawners.dm
> +	important_info = "Do NOT leave the hotel, as that is grounds for contract termination.</b>"
</b>

2019-11-21 04:22 UTC, merged