New MOB_SIZE define & Megafauna Fix
tgstation/tgstation pull request #47837
Opened 2019-11-17 13:00 UTC by mrhugo13

## About The Pull Request
Adds a `MOB_SIZE_IMPOSSIBLE` and changes `MOB_SIZE_LARGE` to `MOB_SIZE_IMPOSSIBLE` in megafauna.dm

## Why It's Good For The Game
Adds a define that would mainly be used to avoid having mobs/simplemobs put in thing such as bluespace body bags and/or other such things that allow `MOB_SIZE_LARGE` into it.

Also fixes #47832 

## Changelog
:cl:Vondiech
fix: You can no longer put megafauna into bluespace body bags.
/:cl:

2019-11-17 16:18 UTC, Cenrus commented
It was fun while it lasted.

2019-11-18 17:51 UTC, ninjanomnom commented
Bad name, it's very important that we go with the size naming convention of D&D. The next step up should be huge

2019-11-19 05:02 UTC, ShizCalev requested changes

2019-11-19 05:02 UTC, ShizCalev commented on code/__DEFINES/mobs.dm
> +#define MOB_SIZE_IMPOSSIBLE 4
Rename this to massive or huge.

2019-11-19 06:42 UTC, Shadowflame909 commented
Okay gamers now what's beyond Bluespace so we can figure out some legit way to pocket Mob_Size_Huge mobs

Maintainers hit me with the DnD lore

2019-11-19 12:13 UTC, mrhugo13 commented on code/__DEFINES/mobs.dm
> +#define MOB_SIZE_IMPOSSIBLE 4
Renamed it to huge.

2019-11-19 18:25 UTC, merged