Tgui random fixes, client-side theming
tgstation/tgstation pull request #47836
Opened 2019-11-17 12:50 UTC by stylemistake

## About The Pull Request

- Random fixes
- Theme is now handled on the client-side, via `routes.js` file.

## Why It's Good For The Game

Setting themes on client side is good, because: a. you save bandwidth on ui_data; b. you can experiment with new themes without the need to set ui_style and recompile the whole server.

As for the fixes... `¯\_(ツ)_/¯`

2019-11-20 13:10 UTC, actioninja requested changes

2019-11-20 13:10 UTC, actioninja commented on code/modules/modular_computers/file_system/programs/ntdownloader.dm
> +	data["hackedavailable"] = 0
= FALSE

2019-11-20 13:10 UTC, actioninja commented on code/modules/modular_computers/file_system/programs/ntdownloader.dm
> +			data["hackedavailable"] = 1
= TRUE

2019-11-21 00:13 UTC, stylemistake commented on code/modules/modular_computers/file_system/programs/ntdownloader.dm
> +	data["downloading"] = !!downloaded_file
downloaded_file is a string, and it does convert it into a "boolean", as in 0/1.

2019-11-21 03:41 UTC, actioninja commented on code/modules/modular_computers/file_system/programs/ntdownloader.dm
> +	data["downloading"] = !!downloaded_file
eh, ok.

2019-11-21 03:54 UTC, merged