Bureaucratic error event has new effects
tgstation/tgstation pull request #47873
Opened 2019-11-18 22:42 UTC by kriskog

## About The Pull Request
Bureacratic error event now has two possible outcomes. In the first, a single job is set to the new overflow role and the rest are set to 0. In the other, all jobs (except AI) have their available slots adjusted by a value between -2 and 4. 
Should cause some more chaos than currently, and fits better with the announcement flavor text. Diligent HoP's can correct the issue over time, though the 30 second cooldown between job management actions will try their patience.

When/if this is in, someone can go ahead and add latejoin AI drop-podding and adminbuse options.

## Why It's Good For The Game
Boring event made fun

## Changelog
:cl: Skoglol
tweak: Bureaucratic error event has new effects!
/:cl:

2019-11-18 23:04 UTC, PKPenguin321 commented
Not a fan of the first. I can't be the only one who actually likes latejoining with a real job instead of being the 50th chaplain, right?

2019-11-18 23:37 UTC, actioninja commented
event isn't very common and getting way too many latejoiners of one type is funny. Gives the hop more to do as well.

2019-11-18 23:51 UTC, ATH1909 commented
> event isn't very common and getting way too many latejoiners of one type is funny. Gives the hop more to do as well.

And it makes the event much more noticeable/interesting.

2019-11-19 00:06 UTC, tralezab commented
maybe a good inbetween is forcing one job but only temporarily?

2019-11-19 00:12 UTC, kriskog commented
If people are worried about the first one, we can make it the rarer kind. I like it in though, captain overflow time.

2019-11-19 05:31 UTC, SkeletalElite commented
Cant wait to see 15 chaplains on a cult round

2019-11-19 14:55 UTC, Dorsisdwarf commented
I think tral is right, and that time-limiting the first one so everyone isnt joining as the warden for the rest of the round or whatever might be a sensible adaption

2019-11-19 16:11 UTC, Grazyn commented
If a head job is selected in the first outcome, does it mean new players who have not unlocked it yet can't join at all? And yes, please make it temporary, the HoP can "fix" it but it means 15 minutes to open 1 slot for each job doing nothing but waiting for the cooldown. It sounds kinda permanent to me. Otherwise just make it a wizard event only.

2019-11-19 16:49 UTC, Michael-Ashfield commented
Does this mean assistant could be locked? This could result in new players being forced to play as a warden in their first round.

2019-11-20 00:39 UTC, kriskog commented
Okay, I need to remove job restriction from whatever is set as overflow so no mergies until then.

2019-11-20 00:55 UTC, cacogen commented
this is cool

2019-11-20 12:19 UTC, Grazyn commented
I don't really like the idea of an IC event touching OOC stuff like job restrictions

2019-11-20 13:20 UTC, kriskog commented
Okay, probability of single role reduced. Job requirements removed, and confirmed that assistant will remain open.

2019-11-20 21:55 UTC, kriskog commented
Okay, since we keep assistant open I'm no longer removing the role restrictions.

2019-11-21 22:52 UTC, cacogen commented
So in the first version, it's possible that the only remaining latejoin roles are AI, curator and assistant? Should this affect head of staff roles? What if there's no head of personnel or captain when it happens? The job slot computer can't change head of staff slots.

Captain being overflow is cool and good though

2019-11-22 04:10 UTC, kriskog commented
Its possible, super rare, and I guess find out who nabbed the spare and start fixing it.

2019-11-30 11:52 UTC, actioninja requested changes
Not convinced that either of these actually work.
Jobs in `jobs` are operated on and `jobs` is just a copy of the actual job instances

2019-11-30 14:11 UTC, kriskog commented
I've tested, it works. The jobs list contains the references to the correct instances of jobs.

Re-reading it I noticed removing the AI like that would never work, so I'm just skipping it instead.

2019-12-01 03:25 UTC, merged