Adds a new element, Self-Knockback.
tgstation/tgstation pull request #47938
Opened 2019-11-22 10:50 UTC by KomradeSpectre

## About The Pull Request
Adds a new element, Self Knockback, currently available for items and projectiles. This element will throw a user back a set amount of tiles proportional to the force of an item or damage of a projectile, min 1, max 5 tile(s) on things that contain this behavior. I can add a way to override the max tiles thrown if necessary but I was advised to keep it around 3-5. The element can easily be implemented in other things as necessary by others.

## Why It's Good For The Game
It's the inverse of our current knockback, and could be useful for things like recoil throwing users back on guns (though it's also available for items too). I'll be using it in my upcoming Gunmods system, so this is part of atomizing my stuff to prepare for that PR soon.

## Changelog
:cl: TheMythicGhost
add: Adds a self knockback (recoil) element that can be applied currently to items and projectiles.
/:cl:

2019-11-22 11:08 UTC, nemvar commented
This feels like something that could benefit from https://github.com/tgstation/tgstation/pull/47807.

2019-11-22 11:09 UTC, KomradeSpectre commented
> This feels like something that could benefit from #47807.

I actually structured this according to advice from @ninjanomnom himself.

2019-11-22 11:13 UTC, nemvar commented on code/datums/elements/selfknockback.dm
> +	var/atom/movable/knockback_target = P.firer
Not every projectile has a firer. Also feels kinda odd to attach this to projectiles in the first place.

2019-11-22 11:15 UTC, nemvar commented
What I meant is that knockback is based on force. This means that you can't, for example, have a lasertag gun that has knockback. That's why it could benefit from bespoke elements

2019-11-22 11:16 UTC, KomradeSpectre commented
> 
> 
> What I meant is that knockback is based on force. This means that you can't, for example, have a lasertag gun that has knockback. That's why it could benefit from bespoke elements

Did you read the changed files? Projectiles are based on damage, items are based on force.

2019-11-22 11:18 UTC, nemvar commented
The point still stands that lasertag shots can't cause knockback.

2019-11-22 11:19 UTC, KomradeSpectre commented
> 
> 
> The point still stands that lasertag shots can't cause knockback.

Projectile
`var/knockback_force = CLAMP(CEILING((P.damage / 10), 1), 1, 5)`
Item
`var/knockback_force = CLAMP(CEILING(I.force / 10, 1), 1, 5)`

2019-11-22 12:12 UTC, KomradeSpectre commented
Fixed a potential runtime error before it can happen thanks to @nemvar , after discussion I will look into making this bespoke after/if ninjanomnom's bespoke PR is merged.

2019-11-22 13:07 UTC, GuyonBroadway commented
As a suggestion perhaps consider not directly tying knockback to damage so you can have a 0 damage object with massive recoil for shits and/or giggles.

2019-11-22 14:00 UTC, KomradeSpectre commented
> 
> 
> As a suggestion perhaps consider not directly tying knockback to damage so you can have a 0 damage object with massive recoil for shits and/or giggles.

The issue with that is force isn't the universal damage, neither is damage. It's typed because the implementations are different.

2019-11-22 14:03 UTC, GuyonBroadway commented
Sorry I meant force.

Indeed it'd be funny to say, get some item out the arcade that sends you flying back 10 tiles if you throw it even if said item was otherwise harmless.

2019-11-22 14:42 UTC, KomradeSpectre commented
That should be possible if I pursue using the Element Bespoke if it gets merged.

2019-11-22 15:31 UTC, ninjanomnom requested changes

2019-11-22 15:31 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +	element_flags = ELEMENT_DETACH
You don't need this flag, signals get cleaned up automaticaly in qdel. Keep the code in Detach though

2019-11-22 15:31 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +	if(ismovableatom(attacktarget)) //This check prevents us from launching ourselves off floors or walls.
Why?

2019-11-22 18:16 UTC, ATH1909 commented
Could you use this component for the effect of firing an improvised pneumatic cannon at the maximum pressure setting?

2019-11-23 09:12 UTC, KomradeSpectre commented
> 
> 
> Could you use this component for the effect of firing an improvised pneumatic cannon at the maximum pressure setting?

The two implementations I included here are for item listening for COMSIG_ITEM_AFTERATTACK, and projectile listening for COMSIG_PROJECTILE_FIRE. So, the element is currently compatible with attacking someone/something with an item, or firing a bullet on compatible things with this attached.

Additional note/update, I've locally made this Bespoke ready, and people can input a custom value during the AddElement process to skip my damage calc and input their own tile distance to throw should they want to.

2019-11-23 20:46 UTC, AnonymousNow commented
Consider eliminating when using magboots, except in instances where the knockback exceeds a large threshold, at which point it just rips your body out of the boots without your feet.

2019-11-24 08:21 UTC, ATH1909 commented
> > Could you use this component for the effect of firing an improvised pneumatic cannon at the maximum pressure setting?
> 
> The two implementations I included here are for item listening for COMSIG_ITEM_AFTERATTACK, and projectile listening for COMSIG_PROJECTILE_FIRE. So, the element is currently compatible with attacking someone/something with an item, or firing a bullet on compatible things with this attached.
> 
> Additional note/update, I've locally made this Bespoke ready, and people can input a custom value during the AddElement process to skip my damage calc and input their own tile distance to throw should they want to.

No, I meant that maximum pressure improvised pneumatic cannons already do something similar to this when fired, and that you should make them use this system instead.

2019-11-24 13:25 UTC, KomradeSpectre commented
> No, I meant that maximum pressure improvised pneumatic cannons already do something similar to this when fired, and that you should make them use this system instead.

>Consider eliminating when using magboots, except in instances where the knockback exceeds a large threshold, at which point it just rips your body out of the boots without your feet.

When and if this gets merged after I commit the bespoke thing (when and if the parent PR for THAT gets merged) then by all means feel free to PR something that adds this behavior where you want it.

2019-11-24 14:07 UTC, GuyonBroadway commented
>Consider eliminating when using magboots, except in instances where the knockback exceeds a large threshold, at which point it just rips your body out of the boots without your feet.

Honestly imagine if you hit some hard enough you punted them out from under thier own hat/out thier own boots/both

2019-11-25 17:15 UTC, ninjanomnom commented
Bespoke elements are merged if you want to add the knockback force argument now

2019-11-25 19:13 UTC, KomradeSpectre commented
Will fix the newline issue after I test this, really quickly.

2019-11-25 20:10 UTC, ninjanomnom requested changes

2019-11-25 20:10 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +		return round(override_throw_val, 1)
You don't need to round, if someone gives a decimal then it's their own fault

2019-11-25 20:10 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +		return round(override_speed_val, 1)
Ditto

2019-11-25 20:10 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +	if(override_throw_val > 0)
```suggestion
	if(override_throw_val)
```

2019-11-25 20:10 UTC, ninjanomnom commented on code/datums/elements/selfknockback.dm
> +	if(override_speed_val > 0)
```suggestion
	if(override_speed_val)
```

2019-11-25 21:33 UTC, ninjanomnom approved these changes

2019-11-25 21:34 UTC, merged