COMPONENT_DUPE_SELECTIVE
tgstation/tgstation pull request #48021
Opened 2019-11-27 13:34 UTC by spookydonut

## About The Pull Request
Adds new component dupe mode that allows selective duplicates, the existing duplicates each decide if they will absorb the new component or allow it to exist separately.

## Changelog
:cl:
code: adds selective duplicate component mode
/:cl:

2019-11-28 01:53 UTC, optimumtact commented
what justification is there for adding this

2019-12-01 06:43 UTC, spookydonut commented
> 
> 
> what justification is there for adding this

@ninjanomnom has expressed a desire for this previously

2019-12-02 01:16 UTC, Moja10 commented
Does this allow you duplicate mobs without fucking everything if you put a soul into the cloned body or am I clinically retarded?

2019-12-02 15:10 UTC, ninjanomnom requested changes
`GetComponent` should runtime with components of this type like `COMPONENT_DUPE_ALLOWED`

2019-12-02 15:10 UTC, ninjanomnom commented on code/datums/components/_component.dm
> +						var/list/arguments = args.Copy(2)
You can do something like
```
arguments = args.Copy()
arguments[1] = new_comp
```
And you don't need to duplicate the loop

2019-12-09 15:01 UTC, ninjanomnom requested changes

2019-12-09 15:01 UTC, ninjanomnom commented on code/datums/components/_component.dm
>  		else if(!new_comp)
You need to actually make a new component

2019-12-14 19:05 UTC, ninjanomnom requested changes

2019-12-14 19:05 UTC, ninjanomnom commented on code/datums/components/_component.dm
> +						new_comp = new nt(arglist(args))
You should only make the new component if it fails the checks on the existing components

2019-12-26 06:02 UTC, ninjanomnom approved these changes

2019-12-26 06:02 UTC, merged