Kicking people to the side now stuns for a third of the remaining knockdown time.
tgstation/tgstation pull request #48061
Opened 2019-11-30 15:51 UTC by carlarctg

## About The Pull Request
Title

## Why It's Good For The Game
Shove stuns are kind of OP as hell. I've heard headmins asked for it to be long enough to cuff people as a means to stop tiders going into departments, but this _kind of_ impacts other areas of the game? It's just way too long for a no-effort stun that allows you to hit someone with a toolbox 5 times for free before they can stand up (only to be shoved into the wall again).

## Changelog
:cl:
balance: Kicking people to the side now stuns for a third of the remaining knockdown time.
/:cl:

2019-11-30 16:39 UTC, Pugie commented
Flashbang buff

2019-11-30 18:42 UTC, HomocidlePancakes commented
Barely changes anything

2019-11-30 21:16 UTC, necromanceranne commented
This is a baton buff anything isn't it?

2019-11-30 22:03 UTC, Angustmeta commented
Knockdown times from stun batons and most other sources are pretty short, so this heavily nerfs most of them by making floor shove+cuff impossible in most cases. Flashbang is an exception.

2019-11-30 22:57 UTC, anconfuzedrock commented
laugh if you want, but I got shoved and kicked to death by an assistant as warden because I gave them a second of benefit of the doubt. probably shouldn't be possible

2019-11-30 23:01 UTC, necromanceranne commented
Floor shoves are terrifyingly powerful I am absolutely not arguing anything different. You can currently get people into death spirals as a result of them using tables or wall throws.

2019-11-30 23:10 UTC, ATH1909 commented
Imagine getting so mad that you got dunked on by an unarmed attacker that you decide to gut shove+kickstunning.

... Except for flashbangs, of course, which now become much stronger with this PR.

2019-11-30 23:14 UTC, necromanceranne commented
I mean I've been abusing the shit out of them and have killed people completely unarmed fairly handedly so make of that what you will.

2019-11-30 23:23 UTC, carlarctg commented
if flashbangs turn great then honestly good, they're not that useful right now

2019-12-01 03:27 UTC, actioninja commented
just remove the stun entirely

2019-12-02 15:29 UTC, daklj commented
**keep unrobust people away from balance changes**

2019-12-02 22:39 UTC, ExcessiveUseOfCobblestone commented
why does this need a stun?

2019-12-02 23:56 UTC, PKPenguin321 commented
So you can't disarm them right back while you're prone on the floor maybe? Really hard to drag someone out of your department if you have literally no way of stopping them from shoving you away every time they click short of literally beating them to death

2019-12-04 01:08 UTC, ExcessiveUseOfCobblestone commented
you can't have the cake and eat it too though.

You either stop someone nonlethally through the use of hard CCs (which comes with pros/cons of such items existing), or you stop them lethally to the point they're hard CCs (also pros/cons of no such items existing). This of course is assuming they deserved to be stopped, though that gets into admin territory.

I'm a fan of an immediate short hardstun followed by the knockdown, i've even considered entertaining the idea it gets prebuilt into knockdown.

In regards to this though, i'm afraid it might be used to rack up a hardstun which goes against why we changed disarm from a KO to a knockdown in the first place. It should scale with the push knockdowns, be based around a single push, or just be a static number.

basically i'm afraid this PR hits it's goal so well it goes through and hits something else we/author didn't want it to (according to documentation).

2019-12-04 08:11 UTC, PKPenguin321 commented
>you can't have the cake and eat it too though.

>You either stop someone nonlethally through the use of hard CCs (which comes with pros/cons of such items existing), or you stop them lethally to the point they're hard CCs (also pros/cons of no such items existing), or we need to build some sort of middle ground resolve either via code/admin realm.

Literally, I am not joking, what did you mean by any of this? Doesn't seem to address anything I said and I'm not sure you used that phrase about cake correctly.

2019-12-09 20:01 UTC, kriskog requested changes

2019-12-09 20:01 UTC, kriskog commented on code/modules/mob/living/carbon/human/species.dm
> +			var/stun_cut = target.AmountKnockdown()/3
Old behaviour also had the knockback end at the end of the stun. This happens on line 1356, which I can't add a comment on. I would like you to replace the SHOVE_CHAIN_PARALYZE there with stun_cut.

2019-12-09 22:51 UTC, ExcessiveUseOfCobblestone commented
> Literally, I am not joking, what did you mean by any of this? Doesn't seem to address anything I said and I'm not sure you used that phrase about cake correctly.

i have no idea tbh, i think i was having a conversation elsewhere that was a more broad conversation between stuns/lethals and brought it here...

2019-12-09 23:10 UTC, necromanceranne commented
@PKPenguin321 the only thing you can do prone is help intent and harm intent. Disarm and Grab don't work.

2019-12-09 23:23 UTC, PKPenguin321 commented
How is that any better?

2019-12-10 07:57 UTC, closed without merging

2019-12-10 08:04 UTC, necromanceranne commented
Okay so why exactly is this closed, because shove stub entirely defeats the purpose of stun removal. This is the strongest stun in the game, and unbelievably powerful by pre-baton stun removal standards even because there have been put in so many knockdowns you can chain knockdowns into shoves to kill someone with ease and you can do this completely unarmed. I've taken down armed opponents with this and abusing microstuns and knockdowns like shove itself.

If the concern is that you can't remove people easily, nonlethally, without a hard stun then the problem is not in this but in other factors. The problem remains that this is a terrible mechanic and will continue to put a hole through any effort for stun removal as it has become the literal crux of all combat.

2019-12-10 11:57 UTC, actioninja commented
@optimumtact Wondering about this one as well. Not sure why you closed without any elaboration on to why.

2019-12-10 19:58 UTC, optimumtact commented
the headadmins at the time explicitly asked me at the time for a non equipment required stun to help remove people from depts.

I am not going to change it at this time.

2019-12-11 03:36 UTC, actioninja commented
Fair enough.