Tgui-next pandemic
tgstation/tgstation pull request #48074
Opened 2019-12-01 10:29 UTC by actioninja

## About The Pull Request

![image](https://user-images.githubusercontent.com/5194834/69912742-62d6c380-13e2-11ea-9a7c-42b87fb625f6.png)

## Changelog
:cl:
add: pandemic now uses tgui-next
/:cl:

2019-12-01 20:39 UTC, stylemistake requested changes

2019-12-01 20:39 UTC, stylemistake commented on tgui-next/packages/tgui/interfaces/Pandemic.js
> +      {thresholds !== {} && (
You can't compare objects like this. Equality compares object identities (pointers), not contents. One way you could do it cleanly, is to convert it to a list first (using the same `map()`, but near your data destructurings), then check `length` property on it.

Something like:
```js
const thresholds = map((desc, label) => ({ desc, label }))(data.thresholds || {});
```

As a bonus, you get a clean array to work with. But ideally, of course, you want backend to send clean arrays:

```dm
threshold_descs = list(
  list(
    "label" = "Resistance 8"
    "desc" = "Additionally regenerates lost blood."
  ),
  ...
)
```

2019-12-10 09:57 UTC, AnturK commented
Needs update

2019-12-11 02:00 UTC, merged

2019-12-11 08:46 UTC, Shirbu commented
You can no longer name diseases.

2019-12-11 09:23 UTC, stylemistake commented
@actioninja What happened to the input. I merged it before realising it wasn't there.

2019-12-12 08:47 UTC, actioninja commented
It should be being dynamically replaced with the input if it's renamable, then replaced with normal text if you can't rename it. iirc you weren't able to rename the stock flu before as well.