Some minor Ecobbomy items (Paystand Functions, Merchant Necklace for Admins)
tgstation/tgstation pull request #48205
Opened 2019-12-11 01:42 UTC by ExcessiveUseOfCobblestone

## About The Pull Request

### Paystands
Paystands have some more functionality based on how you hit them with your registered card

- Help/Harm: Default (Lock it down)
- Disarm: Rename
- Grab: Replace "Pay as much as you want" with an amount you decide. 0 returns it to the old mode.

These options are shown on examine while having the card in your hand.

Paystands also had their lock message edited to clarify it's not the same as anchoring.

### Blingy Bling
Adds a merchant bling necklace that converts items to their export value in holochips (Admin-Only). Can also look at prices (post-fees only). Has a variable admins can edit `profit_scaling` to apply "processing fees".

## Why It's Good For The Game
Paystand Change: Allows for more customization of the paystand to make it more practical to users.

Merchant Necklace: Admin Event-Support

## Changelog
:cl: Ecobbomy
tweak: Paystands have a few new functions. Examine your paystand with the registered card in hand to view these options!
admin: there is a bling necklace subtype that allows you to sell items for credits, hassle-free (search "merchant" in the spawn menu)! Useful for merchant-based events.
/:cl:

2019-12-11 03:00 UTC, RaveRadbury commented
Speedmerge

2019-12-11 03:16 UTC, bobbahbrown commented
good pr

NOTICE: this is a sponsored message

2019-12-11 03:47 UTC, bobbahbrown commented on code/modules/economy/pay_stand.dm
> +		. += "<span class='notice'>Paystands can be edited through swiping your card with different intents. <b>Disarm</b> allows editing the name while <b>Grab</b> changes payment functionality."
```suggestion
		. += "<span class='notice'>Paystands can be edited through swiping your card with different intents. <b>Disarm</b> allows editing the name while <b>Grab</b> changes payment functionality.</span>"
```

more span

2019-12-11 08:05 UTC, HomocidlePancakes commented
Ecobbomy. Really? Is this how we call it now?

2019-12-11 14:58 UTC, Time-Green commented
You should add a hint to the description or this will end up completely overlooked by most people

2019-12-11 23:02 UTC, ExcessiveUseOfCobblestone commented
it does already but requires you to be holding the registered card (and also if the card is null you can see it when you're not holding anything).

2019-12-11 23:03 UTC, ExcessiveUseOfCobblestone commented
> 
> 
> Ecobbomy. Really? Is this how we call it now?

I was just making a funny, idc what you choose to call it.

2019-12-12 14:15 UTC, ninjanomnom requested changes

2019-12-12 14:15 UTC, ninjanomnom commented on code/modules/clothing/neck/_neck.dm
> +	var/profit_scaling = 1 //in case you want to RP taxes or something
Use doc comments

2019-12-12 22:21 UTC, ExcessiveUseOfCobblestone commented
do you want autodoc for the datum's values as well?

2019-12-13 15:29 UTC, ninjanomnom commented
Nah they just seemed like comments that were perfect for autodocs except they weren't in the right format

2019-12-13 15:30 UTC, ninjanomnom approved these changes

2019-12-13 15:30 UTC, merged