Engineering lobby update with service desk
tgstation/tgstation pull request #48357
Opened 2019-12-22 17:46 UTC by nightred

## About The Pull Request

Engineering was one of the only departments that did not have a service desk. The lobby is connected to a large hallway, Atmos has a service desk right beside them. The lobby is not public so the average person had little way to actually interact with engineering without pushing in to a restricted zone.

![engineering lobby revamp](https://user-images.githubusercontent.com/6491940/71325263-d767c400-24af-11ea-8cd7-cd4c1c1bf365.PNG)

The Storage room is also bigger to improve flow when more then one person is getting parts, new tools, or just puttering around.
Security has better visibility in to security, they can see the decontamination room and have a small view in to the SM.
Service Desk for Engineering lobby.

## Why It's Good For The Game
Enhanced presence to the station by engineering.
This lets people interact with engineers in the same way you can with all other departments,  by filling out paperwork.
Engineering security checkpoint now has the ability to monitor who is going in and out of the engine from the lobby.

## Changelog
:cl:
add: Engineering security checkpoint has better view of who is running around.
add: Engineering service desk
tweak: Engineering shared storage has been revamped
/:cl:

2019-12-23 10:07 UTC, trollbreeder commented
Nice. Engineering shared storage looks quite cramped, though, but there's nothing anyone can do about that due to limited space.

2019-12-24 16:06 UTC, zxaber commented
Is it possible to actually see the crystal from the sec checkpoint? Are we going to have hallucinating officers be a standard event?

2019-12-24 16:58 UTC, nightred commented
The crystal can not be seen from security, they can just see the door to the inner chamber. And the plasma windows block hallucinations I thought. Or at least radiation.

2019-12-26 17:33 UTC, kriskog commented
Merge conflict
Im not a fan of splitting up the manufacturing equipment, as you can control the protolathe from the console. If the goal is to make people bump and swap less, it also seems counterproductive.

2019-12-26 23:02 UTC, nightred commented
Fixed the conflict, and cleaned up the storage room again.
I feel this flow is better still, all devices on one side, and the doors offset.

2019-12-27 02:03 UTC, kriskog requested changes
Stray pipe
![image](https://user-images.githubusercontent.com/33292112/71496650-a4795380-2854-11ea-9214-6e16c99d67dd.png)

Dont power the plasmaglass off the engine output, and add cables to the outpost windows.
![image](https://user-images.githubusercontent.com/33292112/71496773-4a2cc280-2855-11ea-977b-72f3207fb900.png)

2019-12-27 02:52 UTC, nightred commented on html/changelogs/AutoChangeLog-pr-48358.yml
> +  - bugfix: "first aid kits found in medbay clinic actually contain stuff now"
I.... What... Well ok, I have no idea what happened here.
I deleted it.

2019-12-27 02:54 UTC, nightred commented
Removed the Pipe, and rewired the sec checkpoint.
That would have been bad right of the SM.

2019-12-27 03:11 UTC, kriskog commented
Lets give this a go then

2019-12-27 03:11 UTC, merged