Uncurses Polycircuit Stack Marginally.
tgstation/tgstation pull request #48474
Opened 2019-12-30 10:23 UTC by ArcaneMusic

## About The Pull Request

Fixes #48420 hopefully. Circuit stack now has a cancel button in the switch menu, as well as a distance check, so that if you just leave it alone it won't start sticking to your arms and teleporting all around the house like a chucky rip off.

## Why It's Good For The Game

Fixes a bug

## Changelog
:cl:
fix: The Polycircuit Stack item no longer leaps through space and time until a circuit is removed.
/:cl:

2020-01-01 08:39 UTC, kriskog requested changes
There is another issue where if used correctly in offhand, it will split a single sheet from the stack and put it under your feet as you finish removing your circuit. Likely related to line 39, where you create the new circuit inside the stack item. Try to create it on get_turf(user) instead, it shouldn't show on the floor before put in hand.

2020-01-01 08:39 UTC, kriskog commented on code/game/objects/items/devices/polycircuit.dm
>  	else
Github wont let me comment there, but line 16 change the check to:
if(user.get_inactive_held_item() != src)

2020-01-01 08:39 UTC, kriskog commented on code/game/objects/items/devices/polycircuit.dm
> +		if(get_dist(user, src) > 1)
if(loc != user) or even safer a repeat of the offhand check from earlier.

2020-01-01 08:39 UTC, kriskog commented on code/game/objects/items/devices/polycircuit.dm
>  	else
Fixes the picking up issue.

2020-01-02 04:31 UTC, ArcaneMusic commented
Whoops.

2020-01-02 12:26 UTC, kriskog commented on code/game/objects/items/devices/polycircuit.dm
> +			return
You need to check this after the input, since thats when you do stuff.

2020-01-02 12:27 UTC, kriskog commented
Did you read the review comment too?

2020-01-03 06:00 UTC, merged