FIXED: Better species environment handlers, and custom race body temperature
tgstation/tgstation pull request #48569
Opened 2020-01-03 20:50 UTC by nightred

## About The Pull Request

This now fixes hard suit fire suits and overheating issues.

This refactors the handle_environment for most mobs and species. 
Better documentation in the code
Better consistency across mobs.
Basic mobs can now have cold and heat protection form the environmental. (not simple mobs)
Slime's temperature change code has been cleaned up.
Base human default temperature range is a bit more reasonable, (+30, -40 vs +/- 50) you would cook or freeze without taking damage before. (Thoughts)
Split up species handle_environment, it was a single massive proc, now each species has handle_environment, handle_body_temperature, handle_environment_pressure.
Each species can now have their own body temp, and hot/cold damage ranges.
Removed checks that we have an environment in many of the classes, this is handled at the base mob class.

**SPECIES:**
All the species modified will survive the normal range of temperature range on station.
- Ethereals core body temp is hotter and can stand higher body heat, but they take damage in cold areas faster.
- Lizard people are cold blooded and do not stabilize body temperature normally, because of they do not take damage as fast as a human. They still stabilize to the room temp.
- Plasmamen like it cold and can survive colder temps better, but take damage when it is hot faster and they can stabilize body temp slower at times.
- Zombies do not stabilize body heat naturally, they are dead. Heat damage is equal to fire spread temp, and cold temp is equal to min temp to move. They still stabilize to the room temp, like lizards

## Why It's Good For The Game

Code cleanup
Each race now can be special and handle the environment differently.
Human body temp is not normal for everyone now.
You could find a zombie by scanning its body temp.

## Changelog
:cl:
add: Species body temperature handling 
balance: Plasmamen, Lizardpeople, Ethereal have custom body temperatures to deal with
fix: natural body temp stabilization now returns proper values
refactor: clean up of the environment handles for mobs and species
/:cl:

2020-01-03 20:53 UTC, nightred commented
The natural stabilization was off and causing overheating.
You can now survive hard suits, fire suits, bio suits.
Lizards recover from being on fire.

2020-01-03 22:07 UTC, itseasytosee commented
So just checking being in a fire suit now no longer makes it worse when you are on fire

2020-01-04 22:47 UTC, ATH1909 commented on code/modules/mob/living/carbon/human/species_types/plasmamen.dm
> +	// In the event they loss the cold resit trait
*resist

2020-01-04 22:53 UTC, ATH1909 commented
So, are lizards just gonna die if they don't eat iced tea or something after getting set on fire (and later extinguishing themselves) because their body temperature can't correct itself?

Are cryo stings just gonna become a one click win button against lizardpeople, even if they have coffee or something on their person?

Do zombies reset their internal temperature when they rez, or can you cause a zombie to repeatedly die over and over again if you set it on fire once?

2020-01-05 02:19 UTC, nightred commented
Body temp stabilization is only 50% natural, what that means is the turf they are on is what they will stabilize body temp to.

Lizards that are on fire and over 1500 k will drop down to 290 k in about 20 seconds where a human will do the same in half the time. Where this is an issue for the lizards is that if the room is 500 k because of a fire they have no wait to fight that. Now in a human they will still over heat in that room but it will take them twice as long to reach overheat temp, this is because natural stabilization will be trying to bring that down. 

Lizards do not heat up or cool down in hard suits but they maintain where they currently are based on the same magic that makes humans stable in a hard suit.

For a zombie this means that the body will be the same temp as the room and will be fine on revival.
I have no idea how cryo sting will hit a zombie.

2020-01-09 22:56 UTC, nightred commented
This has been test merged for several days on Sybil without complain.

2020-01-15 14:03 UTC, nightred commented
Ash Lizards were only 0.15 kelvin above lavaland atmos max temp, this gives lizards better lavaland survival.

2020-01-16 17:00 UTC, ninjanomnom requested changes

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/carbon/carbon_defines.dm
> +	var/cold_protection = 0 // No cold protection
Use doc comments
```
/// This is a doc comment
var/something
```

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/carbon/human/life.dm
> +// This returns a 0 - 1 value which corresponds to the percentage of protection
Put this as a doc comment on the base proc

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/carbon/human/species.dm
> +	var/bodytemp_cold_damage_limit = BODYTEMP_COLD_DAMAGE_LIMIT
More things needing doc comments

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/carbon/life.dm
> +// Used to stabilize the normal body temperature on living mobs
```suggestion
/// Used to stabilize the normal body temperature on living mobs
```

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/simple_animal/slime/life.dm
> +	// Get the current air temperature
```suggestion
	/// Get the current air temperature
```

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/simple_animal/slime/life.dm
> +	// This divisor controls how fast body temperature changes
```suggestion
	/// This divisor controls how fast body temperature changes
```

2020-01-16 17:00 UTC, ninjanomnom commented on code/modules/mob/living/simple_animal/slime/life.dm
> +	// lowering this number changes body temp faster
```suggestion
	/// lowering this number changes body temp faster
```

2020-01-16 18:31 UTC, nightred commented
Updated the comments and used mode doc comments. does this clean up work for you ninja?

2020-01-16 19:30 UTC, ninjanomnom approved these changes

2020-01-16 19:30 UTC, merged