shuttle docking autodoc
tgstation/tgstation pull request #48677
Opened 2020-01-08 14:30 UTC by actioninja

hey kids, remember autodoc?
No?
Oh.

2020-01-08 15:01 UTC, Fikou commented
wow i can use that surgery thingy to implant a shuttle dock in myself?

2020-01-08 15:12 UTC, actioninja commented
yes

2020-01-08 19:33 UTC, optimumtact commented
they will remember it soon

2020-01-09 03:25 UTC, Ohagi-Chan commented
What does this change do?

2020-01-09 06:40 UTC, optimumtact commented
http://codedocs.tgstation13.org/ @Ohagi-Chan

2020-01-09 16:55 UTC, ninjanomnom commented on code/modules/shuttle/shuttle.dm
> +	///this should point -away- from the dockingport door, ie towards the ship
Not necessarily true but is a common standard

2020-01-09 16:57 UTC, ninjanomnom requested changes

2020-01-09 16:57 UTC, ninjanomnom commented on code/modules/shuttle/shuttle.dm
> +	var/dheight = 0
You don't need these modified in template mobile docks

2020-01-12 05:22 UTC, ninjanomnom requested changes

2020-01-12 05:22 UTC, ninjanomnom commented on code/modules/shuttle/shuttle.dm
> +	///size of covered area, perpendicular to dir
This is also automatic for mobile

2020-01-12 05:22 UTC, ninjanomnom commented on code/modules/shuttle/shuttle.dm
> +	///size of covered area, parallel to dir
Ditto

2020-01-12 05:53 UTC, ninjanomnom approved these changes

2020-01-12 05:53 UTC, merged