Allows calling procs in SDQL update queries without storing the return anywhere.
tgstation/tgstation pull request #48690
Opened 2020-01-09 00:58 UTC by nemvar

## About The Pull Request

Using "#null" as you variable name now only resolves the expression without storing the returning value anywhere. This allows you to more easily chain operations on the same set of objects.

This create support for the same thing as in https://github.com/tgstation/tgstation/pull/48684, only it's cleaner.

```
UPDATE /mob/living/carbon/monkey SET #null = forceMove(usr.loc), pixel_x = 5
```
^This. for example, would forceMove all monkeys to the users location and also sets their pixel_x to 5.

There is also an additional benefit to this:
```
UPDATE /mob/living/carbon/superior_animal SET #null = forceMove(marked), #null = gib()
```
 is also more efficient than
```
CALL forceMove(marked) ON /mob/living/carbon/superior_animal;
CALL gib() ON /mob/living/carbon/superior_animal
```
which is currently the suggested way of doing it.

If someone knows a better way of representing this, please tell me.

## Changelog
:cl:
admin: Added another SDQL option. Using "UPDATE <selectors> SET #null=<value>" will now resolve <value> and discard the return. This is useful if you only care about the side effect of a proc.
/:cl:

2020-01-12 06:05 UTC, ninjanomnom requested changes

2020-01-12 06:05 UTC, ninjanomnom commented on code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
> +	return file(name)
This seems like a massive security hole to allow admins to call, what is this doing here

2020-01-12 21:09 UTC, Cyprex commented
I think you can already do this by calling the proc or prefixing it with "global."?

2020-01-14 00:32 UTC, nemvar commented
It is currently not possible to call a proc on the datum without side effect in an SDQL UPDATE SET query. Security concern over file helper is valid, did not consider. Will remove it.

2020-01-14 00:52 UTC, ninjanomnom approved these changes

2020-01-14 00:52 UTC, merged