Having your hair turned purple by Poly Omers now shows a message
tgstation/tgstation pull request #48777
Opened 2020-01-13 16:26 UTC by carlarctg

## About The Pull Request

## Why It's Good For The Game
you may not notice it

## Changelog
:cl:
add: Having your hair turned purple by Poly Omers now shows a message
/:cl:

2020-01-13 17:53 UTC, trollbreeder commented
the quality of life master delivers a quality PR once again, thumbs up

2020-01-15 00:15 UTC, Cyberboss requested changes

2020-01-15 00:15 UTC, Cyberboss commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  			H.facial_hair_color = "92f"
Can you cleanup the three instances of `"92f"` into one var please

2020-01-15 07:37 UTC, cacogen commented
i dont understand

2020-01-18 20:58 UTC, ExcessiveUseOfCobblestone commented
define it

2020-01-27 04:09 UTC, ExcessiveUseOfCobblestone commented
this should apply to the beard too? also stale.

2020-01-31 17:14 UTC, closed without merging