Updates Upload console material costs
tgstation/tgstation pull request #48801
Opened 2020-01-15 02:59 UTC by Anonmare

## About The Pull Request
The AI/Cyborg uploads now require bluespace crystals to construct

## Why It's Good For The Game

Before you say anything I want you to consider the following:

You are an antagonist and you want to subvert the AI. Do you, 
A) Break-in to the AI Upload, an extremely risky, obvious method but you have everything you need to subvert the AI without any extra steps?
B) Break-in to secure tech storage, a place with signficiantly less security and not as often checked on, but have to find another way to acquire the modules you need?
C) Wait a good 15-25 minutes for mining and science to do the bare minimum of their job, enter in the back way and print off everything you need with very little risk or leaving behind very little evidence?

If you answered anything but C, I like you and you can fuck my sister but let's be realistic here. 
It's not going to """fix""" the issue and I won't pretend it will, but with the rarity of bluespace crystals it does mean that they're not going to be as prevalent or as available as early and may force you to take the riskier strategies if the resources you need don't appear quickly enough and encourage conflict.
## Changelog
:cl:
balance: AI and Cyborg Upload consoles require bluespace crystals to print now
/:cl:

2020-01-15 03:05 UTC, zxaber commented
Sad change that means unsubverting an AI will be harder too.

I can't say it's not deserved, but I'll miss raiding the vault for gold under the guise of making positronics just to get upload mats.

2020-01-15 04:03 UTC, Ziiro commented
Even as someone who has a go to strategy of subverting silicons I find this to be a pretty good change.

You might even want to boost the costs across the board because by the time you can print an upload console and all the modules, you're usually in T4 territory anyway.

2020-01-15 05:56 UTC, improvedname commented
Just remove the board only two should exist.
1. Ai upload
2. Tech storage

2020-01-15 06:10 UTC, zxaber commented
Disagree with full removal. Fixing a subverted AI should be possible even if the shift-start upload boards have seen the inside of the crematorium.

2020-01-15 09:06 UTC, XDTM commented
Won't mining also deliver a few crystals anyway in about that timeframe?

2020-01-15 09:20 UTC, TheVekter commented
Realistically, you shouldn't be able to print the fuckin' things at all.

2020-01-15 09:52 UTC, XDTM commented
Making them irreplaceable is not great either, but if we need to make construction of upload consoles less of a subversion option, we could make it so it requires manual linking to the AI before it works

2020-01-15 15:53 UTC, improvedname commented
Let cargo order it :^)

2020-01-15 15:55 UTC, improvedname commented
But honestly ai upload shouldnt be able to be mass produced i mean it lets turn an ai into a murder machine or all it borgs but with breaking into tech storage/ai upload your atleast risking of being seen unlike LOL PRINT BOARD AT SCIENCE OR ENGIBXD XD XD

2020-01-15 15:58 UTC, XDTM commented
Having the manual link requirement would effectively always enforce that (you could build your own, but you still have to take a trip to the AI core), while still allowing scientists/roboticists/free golems to manage the AIs they build on their own with a built console.

2020-01-15 16:46 UTC, Ziiro commented
Having a manual link requirement would be nightmarish. For both subverting and fixing subverted AIs. The AI itself would have to be much more accessible, which, current map design _doesn't_ work that way.

2020-01-15 17:43 UTC, ATH1909 commented
I like the idea of making AI upload boards unprintable, but allowing cargo to order them in a special kind of crate.

This is good too, though, but remember that teleporters can be deconstructed for some near-roundstart bluespace crystals.

2020-01-15 19:41 UTC, improvedname commented
@ATH1909 Theoritically You can get diamonds from the roulette wheel and deconstruct them.
Silver can be gotten from surgery tables.
Gold can be found in vault.
Bluespace crystals from teleporter.
But then again nothing stops you going to public lavaland 🤷‍♂

2020-01-15 19:47 UTC, zxaber commented
Heavily restricting creation of AI uploads is going overboard. They're just as important in fixing an AI as the initial subversion (and remember that traitor RDs have free uncontested access to the upload).

Bluespace requirement is one thing, but flat out removal of the ability to create uploads would make things worse.

2020-01-15 21:03 UTC, Anonmare commented
@improvedname  I'm okay with the teleporter being usable as a means of acquiring BS crystals as it does leave behind evidence and does sacrifice the teleporter for, at least, a fair amount of time. 

As well as going down to public mining because you're putting effort in, this is more of a patch at increasing scarcity since BS crystals are decently rare and fairly contested as a resource goes. Diamonds I may consider, the ideal should be that printing an Upload should be a hefty cost investment and not something you do on a whim

2020-01-15 21:06 UTC, Anonmare commented
I'll be taking @Ziiro's suggestion and @ATH1909 's suggestions onboard

2020-01-15 21:56 UTC, Bawhoppen commented
my suggestion: bluespace crystal for the upload and core boards, diamond + titanium + plasma for normal module boards (asimov, reset, purge, freeform), bepis research required for all the gimmick module boards (corporate, tyrant, etc)

2020-01-15 23:59 UTC, ATH1909 commented
IMO, the law boards should require gold or something, not bluespace crystals. The console is what's using bluespace tech to beam laws into the AI/borgs; the law boards just need to be plugged into the console so it can use their data.

2020-01-16 00:45 UTC, zxaber commented
Yeah, the increase in cost for each board is overkill. The upload is already on GPS when it's used, and you can watch for it once you know someone is fucking with the laws. It takes longer to deconstruct than other computers, so there is time to locate the area it's being used in.

Trying to make it so people can't fix an AI is just asking for more situations where subversions are one-way streets and the round quickly ends to a plasma fire.

2020-01-16 01:11 UTC, Anonmare commented
@ATH1909 The law boards already use gold, the issue is that gold is not remotely a rare resource which means there's no point in breaking into the Upload or secure storage to get the Upload becuase you can just wait 25 minutes and have everything you need printable at science/engineering where very little people pay attention or even report people being.

@zxaber This change is a two-way street - it's harder to fix an AI but it's also harder to subvert one. The idea behind this PR is to pressure antagonists to either make the more risky choice of breaking into someplace secure and leave behind evidence or wait for the rare resources they need but risk the station being better prepared to counter them.

if anything, the material costs may still be too low, it's not unusual for the ORM to have 20,000 diamond/BS and 100,000+ Gold by the 45 minute mark if mining isn't incompetent.

2020-01-16 02:17 UTC, MCterra10 commented
Tbh, make upload boards unconstructable, station loving and indestructible, with a new pinpointer for them. That way it'll keep it relatively easy to fix the AI it you can track the boards and will make it far more of a challenge to subvert the AI but still not unnecessarily difficult

2020-01-16 03:24 UTC, zxaber commented
It's really not terribly difficult to get to the spare board, and that's assuming that you don't have round-start access to tech storage in the first place. And once a subversion happens, you just go grab the other board and empty the silo of bluespace crystals and your subversion cannot be undone.  These are both things that can be accomplished with minimal suspicion, especially if you just assign a borg to do it.

And no, making the boards invincible and tacking on extra pinpointers is not a great solution to any of this. It limits gameplay possibilities to a meta of putting the board somewhere safe (like the AI sat which requires a break-in against turrets), and you could just have the AI moved to lavaland to prevent the laws from being fixed anyway.

Currently, subversion runs the risk of someone un-subverting the AI and having it oust you, so you have to do a little cloak and dagger and fly under the radar enough that no one tries to stop you until everything is in place. What this change really accomplishes is removal of that risk.

2020-01-16 04:18 UTC, gitbirb commented
You could do something like put an ID lock on printing AI upload/law boards which means you need to be the RD and/or captain to print them (could also work to make new systems with the circ imprinter because right now all you need to do is get a circ imprinter and you have everything you ever need), but I don't code and don't know how hard or good that would be in the end.

2020-01-16 13:41 UTC, improvedname commented
Its no use because the materials arent rare and half is already found om station like for bluespace crystals gulag/teleporter. Silver. Surgery tables. Diamond deconstructing the diamond coins after winning roulette wheel(same with silver) gold is in the vault plasms is random loot spawn or science/chemistry/engineering the only thing you cant roundstart is uranium unless i forgot something

2020-01-16 15:20 UTC, improvedname commented
I remember old rnd letting you delete certain tech so you can keep 1 thing off the list maybe it be nice if you could delete nodes and keep it safe on a disk

2020-01-16 15:43 UTC, BadSS13Player commented
I don't get why is the feasibility of printing the boards even an issue. Subverting the AI isn't that common.

2020-01-16 19:48 UTC, Anonmare commented
I think there's a misunderstanding, I'm not trying to stop the boards from being printed, just making the no-risk method not the best choice - it takes no time at all for mining to have enough gold for an Upload+freeform (incidentally I have no idea who the genius was who made a freeform only need gold).  I certainly don't want to make boards ID locked for printing, that would be too snowflake for my taste due to no other item requiring it, and implementing that is outside of the scope of this PR. Not too mention that it would be reducing conflict

@improvedname I have zero problem with effort, all the ways you're describing of getting materials are exactly what I want to hear because it means you're thinking, causing conflict and potentially getting into trouble. That's interesting and engaging to me because you *might* get caught.

Besides, if you decon the teleporter, you'll only get 2000 bluespace crysta froml deconning the artificial crystals in one teleporter so you'll only get enough for one board which means you will still need to make-up the difference another way. Roulette? A perfect use for all that syndie cash if you ask me. 

@BadSS13Player It may not be common but it's certainly not hard, really think about it - whenever the AI does get subverted, is it ever subverted using the main upload? I personally can count on one hand the amount of times the secure tech board's been used this and last month on Sybil alone and 2/3 of the time it's to reset an early bad ion law rather than subversion. 

@zxaber I disagree, nothing's ever stopped the same being done when it was just gold being required so I don't see how adding another material will somehow remove the risk you describe except by making it less obvious something's going on due to the comparable scarcity of BS crystals to gold. In addition, moving an AI to Lavaland means it can't interact with the station anymore so that's also a fine thing to do, in my humble opinion.

2020-01-16 22:08 UTC, zxaber commented
>incidentally I have no idea who the genius was who made a freeform only need gold

Side point, but this was probably done because regular freeform laws can be removed with the reset board and don't require a purge like the core freeform does.

>so I don't see how adding another material will somehow remove the risk you describe except by making it less obvious something's going on due to the comparable scarcity of BS crystals to gold.

I'll admit now that I just remembered the teleporter requires three BS crystals (rather than the one I was thinking of), so it's not terribly bad as a source for both the upload and also the purge board. That being said, I think that at least the non-core freeform and reset boards should remain at their old costs, if only to promote using them over the superior core freeform.

2020-01-16 23:20 UTC, Anonmare commented
I will concede to allowing the Reset module to not need crystals and the non-core freeform to be gold rather than diamond since you raise a fair point.

Are you sure? I couldn't access the station from Lavaland about two weeks ago as an AI unless it got re-broken recently

2020-01-16 23:31 UTC, zxaber commented
Oh, nevermind, I just tested with an AI on Lavaland and it seems that you're right. I was unaware that it was fixed.

2020-01-17 13:59 UTC, Arathianen commented
I think the real solution to the upload thing should be that uploads would need something more than "just a pc".

Basically, it would need some real set up. I was memeing with bluespace launchpad yesterday (which is far less destructive even though I stole all the armoury) and even that needed at least a machine to go with the PC.

2020-01-17 15:42 UTC, yeeyeh commented
What if we just made the boards printed at sci just inferior to the roundstart ones in function? Say something about calibration if you need an in game explanation. Obviously keep Purge/Reset as strong as the normal ones to handle subversion, but make them have a delay before they go into effect or something along those lines. As for other modules make them have higher priority sectors so a board taken from upload will precede one printed, especially for freeform.

And maybe make uploads ping their location to the AI or over radio when they're constructed to stop people from hiding in maint with an upload.

2020-01-17 15:59 UTC, zxaber commented
Delays won't be meaningful unless they're super long (excess of like ten minutes). It's easy enough to do your subversion and then go back and wait for the AI to contact you when the process is complete.

Making boards obtained from the incorrect source behave in unexpected ways seems like bad game design. Priority levels are fairly easy to understand at the moment, and there's really no reason to have "bad" boards that don't follow these rules.

AIs are given the name of anyone that uses a Purge board on them, and uploads are already on GPS for the crew to find. If someone's being a shitter in maint with their private upload, they're easy enough to track down(especially since deconing the upload takes longer than normal).

2020-01-18 13:26 UTC, TheMidnightRose commented
> Oh, nevermind, I just tested with an AI on Lavaland and it seems that you're right. I was unaware that it was fixed.

At most, AI can access Lavaland but cannot do the reverse. As Malf AI I usually use the Mining base APCs as my starter grabs. I have full control of the mining base from the station.

2020-01-20 21:47 UTC, ExcessiveUseOfCobblestone requested changes

2020-01-20 21:47 UTC, ExcessiveUseOfCobblestone commented on code/modules/research/designs/AI_module_designs.dm
> +	materials = list(/datum/material/glass = 1000, /datum/material/gold = 10000, /datum/material/bluespace = 2000)//Custom inputs should be more expensive to get
this should apply for onehuman too so since freeform is mainly used to subvert the AI to yourself.

2020-01-20 21:57 UTC, BadSS13Player commented
> It may not be common but it's certainly not hard, really think about it - whenever the AI does get subverted, is it ever subverted using the main upload? I personally can count on one hand the amount of times the secure tech board's been used this and last month on Sybil alone and 2/3 of the time it's to reset an early bad ion law rather than subversion.

I usually see it when Captain subverts the AI as non-antag.
I don't think this will make antag subversion using the AI Upload room any more common, just make all antag subersion less common.

2020-01-23 00:05 UTC, merged

2020-01-23 00:05 UTC, optimumtact commented
I'm always down for making peoples lives harder

2020-01-31 06:56 UTC, zxaber commented
I know this is post-merge, but did you mean to make the board used in actually creating AIs to also require bluespace? I didn't notice it myself until a game where we had a player wanting to become a secondary AI.