metastation genetics chances /experimentor lab
tgstation/tgstation pull request #48852
Opened 2020-01-17 19:01 UTC by Tlaltecuhtli

🆑
tweak: sci firing range is now experimentor/bepis room
tweak: genetic room has been remodeled
fix: disposals mailing now sends to genetics
/🆑

new experimentor lab:
has blast doors on the doors
has the experimentor with rnd console

genetics:
added a cool monkey pen instead of weird roller bed corridor
added shower for monkey cubes
added functional delivery system to there (it didnt have sorting pipe)
added mutadone pill bottle
removed 8 tile long glass table
removed random rad locker
removed random dupe stuff ( gloves, spare radios)
removed "decorative" hazard lines around the whole room

sci:
changed disposals pipes around to actually work

@81Denton old pr got hit by iranian missle can i have a merge before conflict hell happens again

2020-01-17 23:20 UTC, MCterra10 commented
Surely there was a PR for this already one sec

2020-01-17 23:21 UTC, MCterra10 commented
Oh you were the one who made it carry on

2020-01-18 08:10 UTC, 81Denton requested changes
Nice job, all of this looks really good both from a design and quality standpoint.

Few minor requests:

1) This increased the amount of monkeys from 3 to 6, either reduce them to 3 or remove a monkey cube box so there is less free stuff roundstart.

2) That airlock needs to have the Stbd. Maint. 2 area and the tile north of it the testing range area:
![bepis](https://user-images.githubusercontent.com/32391752/72660674-1a468a00-39d1-11ea-970b-46b98f86915b.png)

3) Can you rename the airlock on the east end of Toxins from "Toxins Launch Room Access" to something like "Toxins Launch Room and Experimentor Access"?

2020-01-19 21:57 UTC, 81Denton approved these changes

2020-01-19 21:57 UTC, merged