Fixes not being able to unwrench drawers
tgstation/tgstation pull request #48971
Opened 2020-01-24 01:25 UTC by Bawhoppen

:cl:
fix: Drawers & filing cabinets may now unwrench once again.
/:cl:

Fixes: https://github.com/tgstation/tgstation/issues/48970

Sorry, I broke this in https://github.com/tgstation/tgstation/pull/48353.
**150 hours of testing.**

2020-01-24 15:45 UTC, kriskog commented on code/modules/paperwork/filingcabinet.dm
> +	if(P.tool_behaviour == TOOL_WRENCH)
Add an intent check here, like on tables that can only be unwrenched if on harm intent. That way you can still insert wrenches.

2020-01-28 09:30 UTC, ShizCalev requested changes
what kriskog said.

2020-01-28 15:23 UTC, Bawhoppen commented
Sorry I forget about this PR, will do when I get a chance

2020-02-01 06:27 UTC, Bawhoppen commented
Should be ready with the suggested changes, although tables can be deconstructed on any intent besides help so I did the same here as well.

2020-02-01 07:25 UTC, 81Denton approved these changes

2020-02-01 07:26 UTC, merged