fixes #49026
tgstation/tgstation pull request #49037
Opened 2020-01-27 09:22 UTC by Tlaltecuhtli

:cl:
fix: grinder chem not grinding
fix: dir of grinder chem
/:cl:

2020-01-30 04:38 UTC, ShizCalev requested changes

2020-01-30 04:38 UTC, ShizCalev commented on code/modules/plumbing/plumbers/grinder_chemical.dm
> -	if(anchored)
still need the anchored check.

2020-01-30 10:28 UTC, spookydonut commented
Spurious travis failure

2020-02-04 08:58 UTC, ShizCalev submitted a review, later dismissed

2020-02-04 08:58 UTC, ShizCalev commented on code/modules/plumbing/plumbers/grinder_chemical.dm
> +	eat_dir = dir
this should occur in setDir() instead

2020-02-05 07:23 UTC, ShizCalev commented on code/modules/plumbing/plumbers/grinder_chemical.dm
> +	eat_dir = dir
eat_dir = newdir

2020-02-08 20:25 UTC, Cyberboss approved these changes

2020-02-08 20:25 UTC, merged