Swap Meta plumbing with morgue
tgstation/tgstation pull request #49054
Opened 2020-01-28 04:01 UTC by cacogen

## About The Pull Request

It swaps Meta's plumbing with the morgue, which removes cloning. 

## Why It's Good For The Game

wesoda23 wanted someone to swap Meta's plumbing with the morgue. I didn't know it'd lead to me replacing cloning. It seems like we're headed for its removal anyway though. I can probably put either the chemistry lab or cloning in a different place (e.g. before the morgue, the maint medical room) if it ends up staying.

## Changelog
:cl: cacogen
tweak: Plumbing on meta is now where the morgue was, while the morgue is where plumbing was. Also cloning is gone
/:cl:

2020-01-28 06:42 UTC, ArcaneMusic commented
I'd say the new morgue could probably use a bit more trays than that personally, just take that extra little mait sliver and throw it into the morgue as well.
Also, there's good enough reason to wall chemistry with Rwalls, due to the nature of the more dangerous chemicals, and the chance of tiding players being able to break in easily.
(Also there's a hole from the main hall to the chem lab still)
But that's not important, actually.

What IS important is if we can get the old mait bar back with all the extra space that affords.

2020-01-28 07:00 UTC, Buggy123 commented
I like the idea (cloning removal aside), but I see a big issue: The new plumbing room is smaller. That's less than ideal considering how much space plumbing takes, I've seen lots of involved chem setups that take up the entirety of the current chemistry room.

Also, it feels a little silly to have a mini-chemistry room a few paces away from the real chemistry ('apothecary') room. It only made sense when plumbing was a entire department away from it, but if they're being moved so close together then chemistry and the mini-chemistry should be merged together.

2020-01-28 07:19 UTC, Tlaltecuhtli commented
yeah just expand plumbing area into the crappy locker room + chem room (they can use the maint door to go to chem
and you could also expand into the shitty south maint room that no one uses other than cultists 

also missing wall on the right?

2020-01-28 07:25 UTC, necromanceranne commented
Make sure roboticists, the chef and the chaplain can reach the new morgue.

2020-01-28 11:56 UTC, wesoda25 commented
Waiting for someone else to do what I’m too lazy to always works. Thanks cacogen 🙏

2020-01-28 12:29 UTC, Dorsisdwarf commented
While I hate to be awkward can I recommend changing medbay maint somewhat to avoid leaving a gigantic chemfactory-shaped hole?

2020-01-28 12:53 UTC, cacogen commented
I'll find the commit before the change and copy over the difference.

Sent via smoke signal

On Wed, 29 Jan 2020 at 1:29 AM, Dorsisdwarf <notifications@github.com>
wrote:

> While I hate to be awkward can I recommend changing medbay maint somewhat
> to avoid leaving a gigantic chemfactory-shaped hole?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/49054?email_source=notifications&email_token=AF7NO6T2U5ACPZ3HFUVEFTDRAAQKLA5CNFSM4KMMAIEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKDDY7A#issuecomment-579222652>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF7NO6SRVHIXLL2ZZINZHDDRAAQKLANCNFSM4KMMAIEA>
> .
>

2020-01-28 17:36 UTC, AWalton commented
(This thread needs pictures).

2020-01-29 04:26 UTC, wesoda25 commented
You might wanna add a desk for the plumbing room, so that chemists know if anyone wants anything while setting stuff up.

2020-01-29 11:09 UTC, Tlaltecuhtli commented
can you add  a rwindow to the outside hall?

2020-01-30 01:13 UTC, ShizCalev submitted a review, later dismissed
move the xeno and blob spawners into the new morgue please.

2020-02-04 05:38 UTC, kriskog commented
This cant be merged before #48668 since it removes the cloners.

2020-02-08 08:05 UTC, cacogen commented
>There are no checks for this commit

2020-02-09 11:46 UTC, kriskog requested changes
No chem dispenser in the new room, did you forget to add it?

2020-02-10 01:56 UTC, cacogen commented
@kriskog 
>Also, it feels a little silly to have a mini-chemistry room a few paces away from the real chemistry ('apothecary') room. It only made sense when plumbing was a entire department away from it, but if they're being moved so close together then chemistry and the mini-chemistry should be merged together.

I was following this part of @Buggy123's comment above and got rid of the Chemistry Lab they used to have given the proximity of the Pharmacy. Do you think they need one?

2020-02-10 01:59 UTC, kriskog commented
The pharmacy/chemistry shuffle feels really weird lately, where chemists are practically thrown out by busy doctors trying to make meds. I think giving them a degree of separation is good, assuming only the chemists have access to the plumbing room.

2020-02-10 03:45 UTC, cacogen commented
I added the chem dispenser back in. Looks a little unnatural. Also expanded the chem factory area downwards out of fear it would be too small. This meant gaps to fill. I could move medical surplus storage closer to medbay, and return the NanoMed alcove. But I need to work on the connection between virology and Medical Surplus Storage, as well as the new space beneath robotics. There's other things I need to tweak too. Plus I need to test it in-game and use the debug Mapping verbs.

2020-02-10 06:41 UTC, Tlaltecuhtli commented
>The pharmacy/chemistry shuffle feels really weird lately, where chemists are practically thrown out by busy doctors trying to make meds. I think giving them a degree of separation is good, assuming only the chemists have access to the plumbing room.

if you are full plumber you only need like 1-2 things from chemistry, if you dont want to do plumbing why did you not choose  to be a doc 🤔

2020-02-10 08:24 UTC, cacogen commented
i've been working on this for six hours... anyway i gave the chem factory its own chem dispenser and put it in front of the interior windoor they have. i think i'm gonna change the xenobio bridge back because it's ugly and i don't want that to undermine the rest of the PR. i tried a 3 wide bridge but it took up a lot of space for what it was and i figured people wouldn't like that. what else? oh, all the map errors for the parts i've changed are fixed. all that remains is what people think about the design and the functionality (e.g. anything else missing? anything unnecessary?)

2020-02-10 21:18 UTC, kriskog commented
cmon mapdiff

2020-02-10 21:18 UTC, kriskog commented
Ugh fuck you too then mapdiffbot.

2020-02-10 21:26 UTC, kriskog submitted a review, later dismissed
Atomize your PR please. The medbay thing is fine, but Im not a fan of the unrelated xenobio change.

2020-02-10 21:41 UTC, cacogen commented
I remember now I changed it because there was no longer a gap between the external wall of robotics maint and the glass of the bridge and two solid turfs beside each other can look bad so I opted to make the bridge wider because of multiple experiences with the awkwardness of passing mechs and simple mobs on it. Anyway, I changed it back. Not gonna update the picture in OP because it took too long to make.

2020-02-10 21:50 UTC, kriskog commented
Right, I didnt notice those changes since mapdiff isnt working and I thought it said maint robo in the changelog. Why are you changing stuff on that side anyway? Really should have been done in a separate PR.

Also making new commits isnt a crime, and we squash anyway. Mapdiffbot doesnt seem to like it when you force push the "same" commit.

2020-02-10 21:58 UTC, cacogen commented
Expanding the chem factory downwards meant extra space I had to fill. On that side as well.

2020-02-10 22:13 UTC, kriskog commented
Oh shit you made the whole station longer, yeah I see it now. This is why mapdiff is super useful. I need a while to consider this one then.

2020-02-11 14:13 UTC, kriskog requested changes
![image](https://user-images.githubusercontent.com/33292112/74241134-ad769500-4cdb-11ea-9dd7-aa11f5fb10a2.png)
Wrong area in the middle here

![image](https://user-images.githubusercontent.com/33292112/74243787-a43bf700-4ce0-11ea-8177-4f1292e0badd.png)
Cables here

![image](https://user-images.githubusercontent.com/33292112/74243930-e7966580-4ce0-11ea-9984-7429bf07a573.png)
This junction is reversed

2020-02-12 05:56 UTC, cacogen commented
Forgot to test disposals... The cables are to electrify those windows. I'll fix that area.

2020-02-12 07:00 UTC, cacogen commented
i also tested disposals and it goes the right way now

2020-02-13 07:19 UTC, kriskog approved these changes
Ah, didnt see the windows there.

Looks okay now

2020-02-13 07:19 UTC, merged