ATMOS: Lavaland atmospheric vents, caps, and even more regrettable balance decisions! [WIP]
tgstation/tgstation pull request #49069
Opened 2020-01-28 23:49 UTC by Buggy123

Adds a more balanced and server-friendly and involved counterpart to Gas Miners as suggested by @ninjanomnom, as a method for getting non-finite supplies of gas for atmospheric projects.

![The stuff](https://user-images.githubusercontent.com/16315400/73314811-7c3a9700-41fc-11ea-8627-8e285d6d43f4.gif)

**Atmospheric Vents**
Atmospheric vents spawn on lavaland, one for each type of gas found in the randomized atmosphere.

**Vent Caps** (non-lame name pending)
You stick these on a Atmospheric Vent to gather gas and direct it into pipes.

By default, it requires no power and produces a decent amount of gas. If you need more, you can supply (quite a bit) of power to widen the vent, increasing production. Note that the gas output is scaled to the quantity of the gas in the atmosphere, so gathering anything with a low concentration is substantially slower.

Maintaining the new rate of outflow doesn't require power, but only if you can keep up with it! Too much pressure in the vent will clog it and slow it back down. And beware, you **really** don't want to damage the machinery which is actively containing a immense outflow of very high pressure gas; keep those fauna _away_ from the vent!<br/>
<br/>
 
As far as balance, these don't actually add much of anything that you can't do already; you can already use Lavaland's atmospheric turfs to gather infinite quantities of any gas in the atmosphere via scrubbers.

The problem with this method, however, is that it breaks the game; several dozen+ scrubbers will lag and break the air alarm GUI, in extreme cases outright freezing your client and forcing you to restart. It also lags the server rather noticably. This method does the same thing and requires similar amounts of setup time, but in a less broken way with less server impact.<br/>
<br/>

Note: EXTREMELY WIP. Literally only putting it out this early because it's such a perfect counterpart to #49067. Todo:

- [ ] Finish and refine the code.
- [ ] Add the finishing touches.
- [ ] Finish the UI.
- [ ] Balance it a bit.
- [ ] Add animated codersprites to gas vent.
- [ ] Maybe get non-codersprites too?
- [ ] Figure out less-lame alternative names for 'gas vent' and 'growing'.
<br/>
<br/>
:cl:
Add: The Nanotrasen Office of Lavaland Exploration and Gathering has discovered the source of Lavaland's strange atmosphere; a series of vents which have incorporated the naturally-occuring bluespace minerals into their structure, producing a infinite supply of gas! The NOLAG office has begun distributing plans for vent capping machinery to aid in harvesting useful gases directly from these vents, in hopes of reducing the local space-time pollution produced by the current practice of using ill-designed contaminant scrubbing equipment to harvest gas from the atmosphere.
/:cl:

2020-01-29 07:06 UTC, TheVekter commented
This is a neat idea and a decent alternative to gas miners. I like it.

2020-01-29 08:49 UTC, HomocidlePancakes commented
Ok. So how are you going to get the gas back to station? In canisters? If so, then this is a bruh moment.

2020-01-29 09:03 UTC, Buggy123 commented
>Ok. So how are you going to get the gas back to station? In canisters? If so, then this is a bruh moment.

Shuttles can be used as impromptu gas tanks or have storage pipe networks placed in them, which _should_ automatically connect whenever it moves but that's kinda fucky still.

Failing that, canisters with supercooled gas can hold up to about 360,000 moles of gas. Each.

2020-01-29 14:26 UTC, Tlaltecuhtli commented
why does the gayser look like a hologram

2020-01-29 17:37 UTC, ninjanomnom commented
You don't need bluespace to explain a gas vent

2020-01-29 18:02 UTC, ninjanomnom requested changes

2020-01-29 20:45 UTC, Buggy123 commented on code/modules/atmospherics/machinery/components/unary_devices/ventcap.dm
> +		pinfo["[pinfo[1]]"] += M.rating
Yeah, I thought having it be part-count independent would be good but it turned into nuclear-grade shitcode.

2020-01-29 20:47 UTC, Buggy123 commented on code/datums/looping_sounds/machinery_sounds.dm
> +	end_sound = 'sound/weather/ashstorm/inside/active_end.ogg'
I checked thoroughly, there is no "gas loudly flowing through pipes and machinery" noise in the sound files. Ash storms sounds are the closest.

2020-01-29 20:48 UTC, Buggy123 commented
>why does the gayser look like a hologram

Codersprites

2020-01-30 01:34 UTC, ninjanomnom commented on code/datums/looping_sounds/machinery_sounds.dm
> +	end_sound = 'sound/weather/ashstorm/inside/active_end.ogg'
Then add a new one

2020-02-01 02:49 UTC, PKPenguin321 commented
>Atmospheric vents spawn on lavaland, one for each type of gas found in the randomized atmosphere.

More than one would probably be okay. Maybe in the far future a way to bore a hole to make your own one.

2020-02-03 07:09 UTC, stylemistake submitted a review, later dismissed
TGUI part is ok

2020-02-03 15:06 UTC, Buggy123 commented
>TGUI part is ok


TGUI part isn't done. Nor is the atmos code, or the non-atmos code. I DID recently finish the animated icon_states and now I'm just slowly chipping away at making sure it animates properly without any way to skip between states.

When I said "EXTREMELY WIP", I really mean it. Assume at least half of the code will be completely refactored and/or added to.

2020-02-03 16:04 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +		qdel(src)
I guess, I just don't want to spam lavaland with random 3x3 excavated squares. Which also might require, additionally, a moderately sized area around them which blocks ruin formation. Too much stuff on lavaland and it starts interfering with ruin and boss spawn, and I _don't_ want to do that.

2020-02-03 18:16 UTC, ninjanomnom commented on code/game/objects/structures/lavaland/vent.dm
> +		qdel(src)
You already restrict to a max of 7 or something though, that's prety reasonable and if the atmosphere has a low amount of gases more of each type seems fine

2020-02-04 16:52 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +		if(vent.z == src.z)
should be done

2020-02-04 16:52 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +			possible_gases += gas
done

2020-02-04 16:52 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +	for(var/obj/machinery/atmospherics/components/unary/portables_connector/atmosphere_vent/vent in GLOB.atmospheric_vents)
done, though I don't think it saves much effort

2020-02-04 16:53 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +	addtimer(CALLBACK(src, .proc/set_gas), 10) // This breaks if done immediately for whatever reason.
done

2020-02-04 16:53 UTC, Buggy123 commented on code/game/objects/structures/lavaland/vent.dm
> +	. = ..()
done

2020-02-17 08:37 UTC, optimumtact commented
how about you come back when this is actually done

2020-02-17 08:37 UTC, closed without merging

2020-02-18 23:25 UTC, Buggy123 commented
:(