TG's Got the Pop Factor: The Singing Update
tgstation/tgstation pull request #49063
Opened 2020-01-28 20:53 UTC by EOBGames

## About The Pull Request
Adds singing as a new speech verb. Simply use ~ (the same as you would use # for whispering) to start belting out a tune! This applies a special span class, speech verb, and adds music notes to your message for optimum lyrical loveliness. The speech verb is logged, and this logging is toggled via a new server setting.

## Why It's Good For The Game
A good sing along is good for crew morale.

## Changelog
:cl:
add: The crew has finally remembered how to sing. Simply use ~ to start singing your favourite tune!
config: Server config setting for logging singing
/:cl:

2020-01-28 21:12 UTC, Anonmare commented
Now I can finally host that talent competition 

Welcome ladies and Gentlemen to the first annual Nanotrasen Top of the Pops. First up, we have the Cargo Shop Quartet followed by our resident Mime "Deafening Silence". Later please enjoy the musical stylings of Bubbles the Talking Monkey Clown.

2020-01-28 21:22 UTC, MrDoomBringer commented
![image](https://user-images.githubusercontent.com/29008542/73306522-68863500-41ea-11ea-8d2c-1a455f31e6a1.png)
feature incorporation when?

2020-01-28 21:23 UTC, AnturK requested changes

2020-01-28 21:23 UTC, AnturK commented on code/__DEFINES/logging.dm
> +#define LOG_SING            (1 << 19)
Absolutely no need to separate this log from say

2020-01-28 21:23 UTC, AnturK commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +.singing				{font-family: "Apple Chancery", cursive, sans-serif; font-style: italic;}
Chances of users having that specific font are kinda slim.

2020-01-28 21:23 UTC, AnturK commented on code/modules/mob/living/say.dm
> +		var/randomnote = pick("♩", "♪", "♫")
Use \uXXXX macro, we're still supporting 512 compilation.

2020-01-28 21:23 UTC, AnturK commented on code/modules/mob/say.dm
> +	say(message, language) //only living mobs can sing, dead things are pretty tonedeaf
This does nothing but say. Completely unnecessary.

2020-01-28 22:13 UTC, Shadowflame909 commented
> ![image](https://user-images.githubusercontent.com/29008542/73306522-68863500-41ea-11ea-8d2c-1a455f31e6a1.png)
> feature incorporation when?
> 
> Also vending machines should sing their slogans
> Also elvis mutation should make you perma-sing

Wearing vocaloid outfits changes your singing color to the costume color.

To simulate the simulation of song

2020-01-28 23:29 UTC, ExcessiveUseOfCobblestone commented
Nya~ I mean 🎵 Nya

2020-01-29 07:41 UTC, XDTM commented
Some keyboards don't have the ~ symbol; is there a more international alternative?

2020-01-29 09:34 UTC, HomocidlePancakes commented
Even my Russian keyboard has a tilde, even though it’s not used in writing. Fairly certain a good chunk of keyboards has a tilde too.

2020-01-29 09:35 UTC, HomocidlePancakes commented
It’s supposed to be above tab.

2020-01-29 09:41 UTC, XDTM commented
Must be an Italian thing, then. Doesn't affect me personally since i have an english layout, but it might happen to others.

2020-01-29 11:53 UTC, Tlaltecuhtli commented
i dont have stinky line symbol, how about §

2020-01-29 12:38 UTC, Grazyn commented
I'll just press alt+126

2020-01-29 13:07 UTC, XDTM commented
Could also be % or &, i think they're unused

2020-01-29 13:49 UTC, trollbreeder commented
Why not microphones that boost your voice to loud when you sing?

2020-01-30 06:09 UTC, gitbirb commented
Good update, cuban petes can finally sing to the drum beat. Also i suggest making science labcoats as a result give you a unique singing color to symbolize it.

2020-01-31 18:43 UTC, SweptWasTaken commented
When can we have Starbound style synced up singalongs?

2020-01-31 19:10 UTC, merged

2020-02-01 16:57 UTC, ATH1909 commented
> Good update, cuban petes can finally sing to the rumba beat. Also i suggest making science labcoats as a result give you a unique singing color to symbolize it.

Eh, I think it'd be better to tie that to sombreros and/or the Cuban Pete hat from the gene vault away mission.