Fixes multi-z photography
tgstation/tgstation pull request #49287
Opened 2020-02-10 22:58 UTC by ike709

## About The Pull Request

Fixes #48992 

**BEFORE:**
![image](https://user-images.githubusercontent.com/5714543/74198017-25828380-4c26-11ea-92c4-3389bc31272d.png)

**AFTER:**
![image](https://user-images.githubusercontent.com/5714543/74198039-2ca99180-4c26-11ea-9f26-f897960ecbfa.png)

Note to self: Stop coding while running on no sleep and a lot of caffeine.

## Why It's Good For The Game

Now you can stalk people from above, and also I can claim one of the game keys @MMMiracles is offering for fixing multi-z bugs.

## Changelog
:cl: ike709
fix: Taking pictures of openspace turfs works now.
/:cl:

2020-02-10 23:00 UTC, ike709 commented on code/modules/photography/camera/camera.dm
> +			if(!T)
This is probably unnecessary, but better safe than sorry I guess?

2020-02-11 08:58 UTC, Dennok commented
This nice but camera see past darkness.

2020-02-11 17:16 UTC, ike709 commented
@Dennok Cameras intentionally don't capture darkness, they have a flash when you use them.

2020-02-11 18:28 UTC, Cyberboss requested changes

2020-02-11 18:28 UTC, Cyberboss commented on code/modules/photography/camera/camera.dm
> +		if(T && ((ai_user && GLOB.cameranet.checkTurfVis(T)) || (T in seen) || turf_is_below))
```suggestion
		if(T && ((ai_user && GLOB.cameranet.checkTurfVis(placeholder)) || (placeholder in seen))
```

2020-02-12 14:30 UTC, Cyberboss approved these changes

2020-02-12 14:31 UTC, merged