Goliath Riding: 2.0 You Can (Not) Move Nukes
tgstation/tgstation pull request #49459
Opened 2020-02-20 14:12 UTC by Fikou

## About The Pull Request

goliath when you tame it only becomes YOUR friend, not everyone that you share the faction with (scary i know)

the vault nuke now has infinite pulling resist, you CANNOT move it

## Why It's Good For The Game

i dont know if the first part is good, since its take your poison
either make the goliath become friends with all neutral mobs which is kinda lame or make it attack everyone except the owner which is cool but also sad
also the nuke thats anchored into the station shouldnt be movable

## Changelog
:cl:
tweak: goliaths become only friends to you, not your allies too
fix: the vault self destruct nuke is no longer movable
/:cl:

2020-02-20 14:27 UTC, Qustinnus commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
> +	move_resist = INFINITY //I SAID STOP
?? but why

2020-02-20 14:28 UTC, Fikou commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
> +	move_resist = INFINITY //I SAID STOP
so you cant move the nuke

2020-02-20 15:16 UTC, Ty-the-Smonk commented
You could make it follow commands like slimes

2020-02-20 15:24 UTC, Qustinnus commented
If you do that should be a component

2020-02-20 15:25 UTC, Qustinnus commented
It could be an assoc list of command - callback aww yeah its gonna be epic

2020-02-20 17:07 UTC, Fikou commented
> It could be an assoc list of command - callback aww yeah its gonna be epic

wyci

2020-02-20 19:02 UTC, ATH1909 commented
> > It could be an assoc list of command - callback aww yeah its gonna be epic
> 
> wyci

Maybe just add an action button that the goliath's master can use that'll toggle their pet goliath between "attack everyone but me" mode and "just chill, bro, don't maul the doctors who are trying to heal me" mode?

2020-02-20 19:03 UTC, ATH1909 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
> +		faction = list("[REF(fren)]")
are you sure that fren have "fren" in their faction list?

2020-02-20 19:08 UTC, ATH1909 commented
Can you move anchored nuke op nukes with goliaths?

2020-02-21 03:41 UTC, spookydonut requested changes
Get in the Goliath, @Fikou

2020-02-21 12:46 UTC, Fikou commented
> Get in the Goliath, @Fikou

fetish content

2020-02-21 22:47 UTC, ShizCalev commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
>  		to_chat(usr, "<span class='warning'>There is nothing to anchor to!</span>")
fix this while you're at it too please.

2020-02-22 14:38 UTC, Fikou commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
>  		to_chat(usr, "<span class='warning'>There is nothing to anchor to!</span>")
whats broken about it

2020-03-03 03:33 UTC, TemporalOroboros commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
>  		to_chat(usr, "<span class='warning'>There is nothing to anchor to!</span>")
It uses usr.

2020-03-03 13:17 UTC, Mickyan commented
This isn't a good idea if you're not going to bother with an elegant solution, taming may not be worthwhile for combat but it's even less so if friendlies are forced to kill them in self defence

2020-03-03 19:44 UTC, AnturK requested changes
From quick glance you should just override force_pushed on the nuke.

2020-03-04 18:59 UTC, closed without merging