transit tube violence
tgstation/tgstation pull request #49523
Opened 2020-02-23 09:30 UTC by tralezab

## About The Pull Request

transit tube pods eject you if they leave the transit tube

## Why It's Good For The Game

more traitor tactics

## Changelog
:cl:
tweak: transit tube pods will now throw you when they
/:cl:

2020-02-23 19:15 UTC, spookydonut requested changes

2020-02-23 19:15 UTC, spookydonut commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +	var/list/savedcontents = contents
not actually saved, just a reference

2020-02-23 19:15 UTC, spookydonut commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +		i.throw_at(destination,rand(1,3),5)
you need to cast i to /atom/movable

2020-02-23 19:15 UTC, spookydonut commented on code/game/objects/structures/transit_tubes/transit_tube_pod.dm
> +	var/list/savedcontents = contents
use contents.Copy()

2020-02-29 21:05 UTC, kriskog approved these changes

2020-02-29 21:05 UTC, merged