Cleans up some of the code for unhusking people with chems, also reduces the amount of synthflesh required to unhusk someone
tgstation/tgstation pull request #49545
Opened 2020-02-24 09:55 UTC by ATH1909

## About The Pull Request

Replaces all mentions of "TRESHOLD_UNHUSK" with "T**H**RESHOLD_UNHUSK" (seriously, guys?).

Updates the description of synthflesh to reflect what it actually does more accurately (a percentage in the description was wrong because of a stealth revert that oranges made).

Changes the name of the variable "Carbies" to "carbies", because the capitalization of that variable's name was annoying me.

You now no longer need to apply an absurd amount of synthflesh (100u) to a corpse to unhusk it (if it was husked because of burn damage). Now you only need to apply 25u of synthflesh to a corpse to unhusk it, but that synthflesh must be applied all at once. I'm not even sure if that bit of code even worked properly before if you applied all 100u in a single splash, and this way is much more intuitive, IMO (since it's more similar now to the system that rezadone uses to unhusk corpses).

I also tweaked the description of the text that's displayed when a corpse is unhusked by synthflesh a little bit.

## Why It's Good For The Game

See above.

## Changelog
:cl: ATHATH
balance: You now only need 25u of synthflesh to unhusk a corpse that has been husked by burn damage, but that synthflesh must be applied (via touch or patch) all at once in order for the corpse to be unhusked. Remember that a corpse must have less than 50 burn damage and have been husked by burn damage (and not, say, by a changeling's absorption ability) to be unhusked by an application of synthflesh or rezadone!
fix: Fixed the description of synthflesh to reflect the changes caused by a stealth reversion that oranges made to the chem. The amount of tox damage dealt is 66% of the amount of brute and burn damage healed, not 75%.
/:cl:

2020-02-24 10:43 UTC, Angustmeta commented
I don't think Oranges' revert of the Synthflesh buff was actually stealthy. A proper revert PR was made. I just failed to notice it.

2020-02-24 17:35 UTC, ATH1909 commented
> I don't think Oranges' revert of the Synthflesh buff was actually stealthy. A proper revert PR was made. I just failed to notice it.

Ah, okay. I've edited the changelog to account for this.

2020-02-24 17:37 UTC, ATH1909 commented
Should I add "Can also be used to unhusk corpses under certain conditions." to the descriptions of synthflesh and rezadone?

2020-02-24 18:35 UTC, Krysonism commented
Power creep

We shouldn't trivialize husking further, it is meant to be a serious hindrance to revival.

2020-02-24 20:35 UTC, kriskog requested changes

2020-02-24 20:35 UTC, kriskog commented on code/modules/reagents/chemistry/reagents/cat2_medicine_reagents.dm
> +			if(HAS_TRAIT_FROM(M, TRAIT_HUSK, "burn") && carbies.getFireLoss() < THRESHOLD_UNHUSK && reac_volume >= 40)
```suggestion
			if(HAS_TRAIT_FROM(M, TRAIT_HUSK, "burn") && Carbies.getFireLoss() < TRESHOLD_UNHUSK && (Carbies.reagents.get_reagent_amount(/datum/reagent/medicine/C2/instabitaluri) + reac_volume >= 100))
```

Getting 100u synthflesh is trivial, this fixes the issue where you cant splash husks to fix them.

2020-02-24 23:44 UTC, AdamElTablawy commented
husking is very easy though, one full laser clip does it

100u synthflesh every time is expensive to make and produce

2020-02-25 01:25 UTC, kriskog commented
Its supposed to be an annoying thing to fix. The threshold for getting husked was increased before cloning removal, and plumbing can supply an infinite amount of synthflesh easily enough

2020-02-29 22:23 UTC, merged