Defib mounts are now roundstart but do not recharge. Rechargable variants still exist /w same reqs.
tgstation/tgstation pull request #49599
Opened 2020-02-27 04:26 UTC by ExcessiveUseOfCobblestone

## About The Pull Request

The defib mount now JUST holds defibs. It is available roundstart.

The new mount, PENLITE defib mount, now provides passive recharging of your defibs (lower rate than pre-PR). Costs 1/4 silver.

The CMO spawns with the default (no recharge) variant.

## Why It's Good For The Game

The defib mount trivializes the need to ever upgrade the defib batteries while also providing easy security. Since this is now meant to be a staple in maps (#49520) for the purpose of keeping defibs secure, I decided to add another one that does the passive recharging at a slower rate to encourage players to maintain/upgrade all aspects of their equipment.

The CMO does not start with a new variant because they start with something even better, a defib that doesn't take up the back slot. They give their mount to the doc's anyways.

## Changelog
:cl: Cobby
balance: Removes passive charging from defib mounts, allows them to be built roundstart.
add: Adds PENLITE defib mount, which charges. No techweb changes.
/:cl:

2020-02-27 04:27 UTC, ExcessiveUseOfCobblestone commented
whoops forgot about the small silver I added in title 🙄

2020-02-27 04:38 UTC, zxaber commented
Do wall-mounted defibs run off station power? As in, will a wall-mounted defib ever run out the battery if it's never removed from the wall?

2020-02-27 05:22 UTC, TheVekter commented
This is good shit. I've been wanting to have these at round start for a while. Part of me still wants one-off AED-style defibs around the station, but I get that'd kinda screw with balance.

> 
> 
> Do wall-mounted defibs run off station power? As in, will a wall-mounted defib ever run out the battery if it's never removed from the wall?

The roundstart ones do not. The upgraded ones do.

2020-02-27 09:35 UTC, kriskog commented
Thanks :+1:

2020-02-27 13:04 UTC, Donpedrito commented
Is there a way to remove the roundstart mounts if you want to replace them with the recharging ones?

2020-02-27 13:24 UTC, kriskog commented
Wrench should work iirc

2020-02-27 16:50 UTC, ExcessiveUseOfCobblestone commented
> Do wall-mounted defibs run off station power? As in, will a wall-mounted defib ever run out the battery if it's never removed from the wall?

It runs on station power but charges the defib at a set rate (PENLITE).

https://github.com/tgstation/tgstation/pull/49599/files#diff-729b46e996ed12ab77e71b5f56faccb3R141-R145

The straight answer is Yes then No, unless the power dies. Even better, the rate was pretty wild. Every 10 process iterations it would have charged 1800, which is nearly 2 defib uses (1000 req to use the defib).

As of this commit it takes 13 iterations to recharge the unit.

2020-02-27 18:01 UTC, BadSS13Player commented
> Wrench should work iirc

Would it? I can't see anything handling deconstruction in code and the description says you can't remove them after placing.

2020-02-28 12:33 UTC, kriskog commented
You're right, it cant. Should just be wrenchable, you can already pop the defib off easily enough. You on it cobbman?

2020-02-28 18:34 UTC, ExcessiveUseOfCobblestone commented
s-s-sure

2020-02-29 22:03 UTC, kriskog commented
Alternatively, could make it upgrade an old one if you slap the upgraded one on.

2020-03-02 23:41 UTC, kriskog requested changes

2020-03-02 23:41 UTC, kriskog commented on code/game/machinery/defibrillator_mount.dm
> +	desc = "A frame for a PENLITE defibrillator mount. It can't be removed once it's placed."
It can now

2020-03-02 23:53 UTC, ExcessiveUseOfCobblestone commented on code/game/machinery/defibrillator_mount.dm
> +	desc = "A frame for a PENLITE defibrillator mount. It can't be removed once it's placed."
```suggestion
	desc = "A frame for a PENLITE defibrillator mount. Unlike the normal mount, it can passively recharge the unit inside."
```

2020-03-03 00:01 UTC, merged