Vendor fix when they are hacked and have no contraband items
tgstation/tgstation pull request #49626
Opened 2020-02-28 19:30 UTC by nightred

## About The Pull Request

The TGUI would break on vendors that did not have any contraband items when they were hacked.

## Why It's Good For The Game

Vendors now work properly when hacked.

## Changelog
:cl:
fix: fixed vendor hacking related tgui issue
/:cl:

2020-02-28 21:00 UTC, Tharcoonvagh commented
Fixes #49467

2020-02-28 21:43 UTC, stylemistake submitted a review, later dismissed

2020-03-01 03:16 UTC, Cyberboss requested changes

2020-03-01 03:16 UTC, Cyberboss commented on code/modules/vending/_vending.dm
> +	.["hidden_records"] += list()
```suggestion
	.["hidden_records"] = list()
```

2020-03-01 14:32 UTC, nightred commented on code/modules/vending/_vending.dm
> +	.["hidden_records"] += list()
I updated and fixed this up. thanks

2020-03-03 08:06 UTC, merged