Gateway refactor
tgstation/tgstation pull request #49868
Opened 2020-03-10 18:13 UTC by AnturK

Gateways now have control computers, can handle multiple destinations, are single object.

![image](https://user-images.githubusercontent.com/4047233/76345164-241aa880-6303-11ea-9f54-03b9cd8dd93c.png)

TODO:
- Tgui build.
- Kilo broken on master, still needs update.
- Codedoc pass.
- Power drain balance.
- Probably something else i forgot.

2020-03-10 18:21 UTC, trollbreeder commented
Away missions coming back? Boy, i'm excited!

2020-03-10 19:14 UTC, MMMiracles commented
that's hot ngl

2020-03-10 19:27 UTC, OverlyGeneric commented
oh boy, I can't wait to see away missions get nerfed to shit or some arbitrary blockade like R&D research, time locks, and recycling telescience maths.

2020-03-12 19:44 UTC, Ziiro commented
>Away missions coming back? Boy, i'm excited!

Off station content is being axed, so no

2020-03-13 22:14 UTC, AnturK commented
Okay, should be good to review now.

2020-03-14 09:02 UTC, spookydonut requested changes

2020-03-14 09:02 UTC, spookydonut commented on code/modules/awaymissions/gateway.dm
> +	var/obj/machinery/gateway/G
G is a dumb var name, call it like parent or parent_atom or some shit

2020-03-14 09:02 UTC, spookydonut commented on code/modules/awaymissions/gateway.dm
> +	return get_step(G.portal,SOUTH)
why not have it use the gateway's direction?

2020-03-14 09:02 UTC, spookydonut commented on code/modules/awaymissions/gateway.dm
> +/obj/effect/gateway_portal_bumper/Bumped(atom/movable/AM)
make it optionally directional where it can only be entered from a specific direction?

2020-03-14 09:10 UTC, spookydonut commented on code/modules/awaymissions/gateway.dm
> +	var/obj/machinery/gateway/G
also autodoc

2020-03-18 21:27 UTC, stylemistake commented
I'd merge if all other reviews were addressed.

2020-03-19 20:31 UTC, merged