Adds range check to beaker eject for grinder and biogen
tgstation/tgstation pull request #49998
Opened 2020-03-16 07:04 UTC by kriskog

## About The Pull Request
Since these put in hand, adds range check to the eject proc as well. Stops TK users and borgs from teleporting beakers around.

## Why It's Good For The Game
Fixes #49856

## Changelog
:cl: Skoglol
fix: Grinder and biogen now rangecheck before ejecting beaker into hand.
/:cl:

2020-03-16 07:07 UTC, Dennok commented
Please, make it drop on ground instead of block ejecting, like with light bulbs.

2020-03-18 02:34 UTC, ShizCalev commented on code/modules/hydroponics/biogenerator.dm
> +	if(!can_interact(user) || !user.canUseTopic(src, BE_CLOSE, FALSE, NO_TK))
user.canUseTopic(src, BE_CLOSE, ismonkey(user), NO_TK) imo

2020-03-18 02:34 UTC, ShizCalev commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	if(!can_interact(user) || !user.canUseTopic(src, BE_CLOSE, FALSE, NO_TK))
.

2020-03-20 07:17 UTC, actioninja requested changes
I agree with dennok here, just make it drop on the ground

2020-03-20 08:15 UTC, Dennok commented
Please check another chem machinery too, dispenser, etc.

2020-03-27 09:43 UTC, kriskog commented
Dispenser cant do this, the reason this screws up is because the proc is run directly from html UI/radial instead of the alt click which has this check.

2020-03-27 22:18 UTC, merged