Enhances multi-z falling, adds anvil-ing people with vendors and divebomb tackles
tgstation/tgstation pull request #50033
Opened 2020-03-17 07:12 UTC by Ryll-Ryll

## About The Pull Request
[![dreamseeker_2020-03-17_03-12-01.png](https://i.imgur.com/HeOr5Ws.png)](https://i.imgur.com/HeOr5Ws.png)

Multi-Z falls needed some dire love and SOUL, and this is a start. Falling atoms will take a bit of time  (2-3 seconds at max, most less than a half second) to fall, giving warning to those below that they should move out of the way, allowing falling objects to be much more hazardous without being instant death. Heavier and more dangerous objects take slightly longer to fall, with vendors doing automatic tilts on anyone they land on, items dealing damage based on their size (still needs work and ignoring soft items like boxes), and other heavy things planned.

You can also launch tackles over ledges now! It's really probably not a good idea since the penalty for missing and hitting the ground is around a 5% chance of instant death and dismemberment, and a 45% chance of heavy full-body damage, but if you manage to land a tackle on someone from above, you'll get a nice bonus to your tackle roll!

Still need to do a bit of fleshing out balance wise, as well as making a nicer effect for the falling (shadows/scaling/something to indicate falling speed), but I think this is a really good start for making the most of muti-z!

Video:
https://cdn.discordapp.com/attachments/564124572392226838/689367729735598117/fall.mp4
*[Note that the outright gibbing at the end was ridiculously unlucky, that's a 2% chance without protection, most of the tackle splats are less dangerous than that, but still incredibly dangerous]*

Also fixes #49685 which was what started me on all this in the first place, and as a side effect, made cutting lattices and catwalks require a short 1 second action rather than being instant

## Why It's Good For The Game
Adds more depth to multi-z interactions, the current behavior of just bonking the highest atom on the target turf is a bit lame.

## Changelog
:cl: Ryll/Shaps
add: You can now launch tackles off ledges on multi-z maps on unsuspecting targets on lower levels! It's really, really, really dangerous, but you can still do it! Just don't miss!
tweak: Objects falling down z-levels have a short falling delay before impact, giving you some warning before that vending machine someone pushed off crushes you to death.
balance: rebalanced something

/:cl:

2020-03-17 07:29 UTC, trollbreeder commented
ree your changelog has a default in it

2020-03-17 07:38 UTC, HomocidlePancakes commented
**PIANOGIBBING PIANOGIBBING!**

2020-03-17 08:03 UTC, Tlaltecuhtli commented
assassin creed

2020-03-17 09:39 UTC, Qustinnus commented
the layering is weird.

2020-03-17 10:23 UTC, cacogen commented
Why wouldn't a box just do its thrown damage? i.e. Why wouldn't falling items just use their throwforce, perhaps with a multiplier that increases with each floor?

And you know tackling from the second floor works already? It's very fun. Please don't ruin it with a snowflakey 5% chance to die.

2020-03-17 11:22 UTC, Qustinnus commented
yeah the gib is way over the top. I think gimmicky things like the vending machine squishing are fun but this is touching on pretty core stuff of multi-Z and seems like a bit too much

2020-03-17 11:47 UTC, HomocidlePancakes commented
@Qustinnus 

>[Note that the outright gibbing at the end was ridiculously unlucky, that's a 2% chance without protection, most of the tackle splats are less dangerous than that, but still incredibly dangerous]

It’s a lowchance lowroll for something extremely stupid that you should never even try to do. You are being such a buzzkill.

2020-03-17 11:59 UTC, Ryll-Ryll commented
It's a fringe part of tackling not core multi-z, if you don't want to die when you leap off a second story floor, wear a helmet. Normal falling is still the same/will be around the same level of damage.

As for object and item falling behavior, that's still something I'm hashing out the best way of handling to make dangerous without being sudden instant death with no warning

2020-03-17 12:12 UTC, Qustinnus commented
I was talking more about the vending machine etc dropping. If you make falling slow it should work like that for everything or for nothing.

2020-03-17 13:10 UTC, HomocidlePancakes commented
@Qustinnus Can be fluffed as large objects dangling back and forth on the edge for a bit before falling.

2020-03-17 15:54 UTC, Qustinnus commented
I still think that makes very little sense; you can push these objects just fine normally but when pushed over a ledge they'd wobble?

2020-03-17 16:35 UTC, HomocidlePancakes commented
Yeah, you are right. Should just fall instantly or with a 0.5 second delay tops.

2020-03-17 18:55 UTC, Ryll-Ryll commented
Alright, I'll try it with a flat .5 second falltime

2020-03-20 07:39 UTC, actioninja requested changes
I agree the delay is stupid

2020-04-05 00:08 UTC, closed without merging