Autodocs some stuff
tgstation/tgstation pull request #50085
Opened 2020-03-19 07:58 UTC by TiviPlus

## About The Pull Request

Item.dm now has some docs

## Why It's Good For The Game
Gamerdocs

2020-03-19 08:12 UTC, optimumtact commented on code/game/objects/items.dm
> +	///see setup.dm for appropriate bit flags
this is not documentation

2020-03-19 08:12 UTC, optimumtact commented on code/game/objects/items.dm
> +	/// for chemicals/diseases
ditto

2020-03-19 08:12 UTC, optimumtact commented on code/game/objects/items.dm
> +	///suit storage stuff.
ditto

2020-03-19 08:12 UTC, optimumtact commented on code/game/objects/items.dm
> +	///The type of tool, engineering or mining for example
wrong

2020-03-19 08:13 UTC, optimumtact commented on code/game/objects/items.dm
> +	/// Wheher dogs can wear the item: Needs to be in /obj/item because corgis can wear a lot of non-clothing items
not if they can wear the item, but instead a reference to the datum that determines behaviour if they do.

2020-03-19 08:13 UTC, optimumtact commented
2 out of ten apply yourself

2020-03-19 12:24 UTC, TiviPlus commented
var/gas_transfer_coefficient  is defined for several masks but does literally nothing

2020-03-23 01:19 UTC, Rohesie commented on code/game/objects/items.dm
> +	///suit storage stuff.
Still pending.

2020-03-23 01:20 UTC, Rohesie commented on code/game/objects/items.dm
> +/// this proc says it's for initializing components, but we're initializing elements too because it's you and me against the world >:)
This proc is also deprecated.

2020-03-23 01:39 UTC, Rohesie commented on code/game/objects/items.dm
> +///Handles attacking by blobs
Children proc, leave the documenting at the base of it.

2020-03-23 14:19 UTC, spookydonut requested changes

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +  *damagetype: The type of damage the item will inflict on the user
these arent parameters

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	///Same as for worn_x_dimension but for inhands, uses the lefthand_ and righthand_ file vars
```suggestion
	///Same as for [worn_x_dimension][/obj/item/var/worn_x_dimension] but for inhands, uses the lefthand_ and righthand_ file vars

```

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	///Same as for worn_y_dimension but for inhands, uses the lefthand_ and righthand_ file vars
```suggestion
	///Same as for [worn_y_dimension][/obj/item/var/worn_y_dimension] but for inhands, uses the lefthand_ and righthand_ file vars

```

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	//flags which determine which body parts are protected from heat. Use the HEAD, CHEST, GROIN, etc. flags. See setup.dm
link to the defines using []

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	///Used in attackby() to say how something was attacked "[x] has been [z.attack_verb] by [y] with [z]"
link to the attackby

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	///for flags such as GLASSESCOVERSEYES
```suggestion
	///for flags such as [GLASSESCOVERSEYES]

```

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +	///The list of slots by priority. equip_to_appropriate_slot() uses this list. Doesn't matter if a mob type doesn't have a slot. For default list, see [/mob/proc/equip_to_appropriate_slot()]
```suggestion
	///The list of slots by priority. equip_to_appropriate_slot() uses this list. Doesn't matter if a mob type doesn't have a slot. For default list, see [/mob/proc/equip_to_appropriate_slot]

```

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +  *user is mob that equipped it
use the proper arguments formatting

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +  *the mob M is attempting to equip this item into the slot passed through as 'slot'. Return 1 if it can do this and 0 if it can't.
ditto

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +/// Called before use_tool if there is a delay, or by use_tool if there isn't. Only ever used by welding tools and stacks, so it's not added on any other use_tool checks.
link to use_tool

2020-03-23 14:19 UTC, spookydonut commented on code/game/objects/items.dm
> +/// A check called by tool_start_check once, and by use_tool on every tick of delay.
link tool_start_check

2020-03-25 16:52 UTC, Rohesie commented on code/game/objects/items.dm
> +	//flags which determine which body parts are protected from heat. Use the HEAD, CHEST, GROIN, etc. flags. See setup.dm
Still pending.

2020-03-26 06:20 UTC, spookydonut commented on code/game/objects/items.dm
> +	//flags which determine which body parts are protected from heat. Use the HEAD, CHEST, GROIN, etc. flags. See setup.dm
```suggestion
	//flags which determine which body parts are protected from heat. [See here][HEAD]

```

2020-03-27 23:49 UTC, Rohesie approved these changes

2020-03-28 06:22 UTC, SpaceManiac approved these changes
Not perfect but it's progress.

2020-03-28 06:23 UTC, merged