Refactors eyestabbing, allows scalpels and surgical drills to eyestab
tgstation/tgstation pull request #50511
Opened 2020-04-17 13:26 UTC by Thunder12345

## About The Pull Request
See title

## Why It's Good For The Game
Scalpels and drills both seem like reasonable items to stab people in the eyes with, and moving eyestabbing to a var makes it more versatile and avoids copypasted code.

## Changelog
:cl: Thunder12345 and Fikou
balance: Scalpels and surgical drills can be used to eye stab.
refactor: Eye stabbing is now set by a variable instead of being hardcoded.
/:cl:

closes #50476

2020-04-17 13:33 UTC, Fikou requested changes
use defines you STINKY

2020-04-17 13:33 UTC, Fikou commented on code/_onclick/item_attack.dm
> +	if(user.zone_selected == BODY_ZONE_PRECISE_EYES && eyestab == 1)
```suggestion
	if(user.zone_selected == BODY_ZONE_PRECISE_EYES && eyestab == TRUE)

```

2020-04-17 13:33 UTC, Fikou commented on code/game/objects/items.dm
> +	var/eyestab = 0
```suggestion
	var/eyestab = FALSE

```

2020-04-17 13:33 UTC, Fikou commented on code/game/objects/items/kitchen.dm
> +	eyestab = 1
```suggestion
	eyestab = TRUE

```

2020-04-17 13:33 UTC, Fikou commented on code/game/objects/items/kitchen.dm
> +	eyestab = 1
```suggestion
	eyestab = TRUE

```

2020-04-17 13:33 UTC, Fikou commented on code/game/objects/items/tools/screwdriver.dm
> +	eyestab = 1
```suggestion
	eyestab = TRUE

```

2020-04-17 13:33 UTC, Fikou commented on code/modules/surgery/tools.dm
> +	eyestab = 1
```suggestion
	eyestab = TRUE

```

2020-04-17 13:33 UTC, Fikou commented on code/modules/surgery/tools.dm
> +	eyestab = 1
```suggestion
	eyestab = TRUE

```

2020-04-17 13:40 UTC, Tlaltecuhtli commented
change eyestrap code too, its dumb that if the enemy is wearing a gasmask it just returns you a dumb message instead of just progressing into a normal melee attack

2020-04-17 15:57 UTC, Qustinnus commented on code/game/objects/items.dm
> +	var/can_eyestab = FALSE
Making vars for specific behaviors like this is usually not something we'd want to do, making this into an element would be preferable.

2020-04-17 18:59 UTC, Qustinnus commented on code/datums/elements/eyestab.dm
> +// It an item has the eyestab element, when you hit someone while targetting their eyes it stabs them in the eyes
make sure to autodoc this element!:)

2020-04-18 01:32 UTC, Akrilla commented on code/datums/elements/eyestab.dm
> +			M.Paralyze(40)
lol

2020-04-18 12:36 UTC, ghost approved these changes
PR looks good. Good job.

2020-04-18 12:36 UTC, Qustinnus commented on code/datums/elements/eyestab.dm
> +	if(eyes.damage >= 10)
This could also be an early return :)

2020-04-19 09:47 UTC, spookydonut commented
see #50556

2020-04-23 10:28 UTC, closed without merging