An attempt to clean up tesla code
tgstation/tgstation pull request #50530
Opened 2020-04-18 08:22 UTC by LemonInTheDark

## About The Pull Request

Adds an override to tesla's consume() to prevent the tesla from calling consume() on what seems to be it's own energy balls, blowing up the containment.
Refactors the way tesla_zap deals with type, instead of dealing with type with a var for each type, we store the type integer, so we can clean up the zap_act part and something something lower the amount of vats we have to create on each zap.
Moves the base of zap_act to /atom so we don't need to type the default target var on most zaps.
Uses this in the same manner in supermatter_zap
*Should* make power output of tesla zaps more sane, mostly from tesla coils. I'll go into this more in future.

Now onto the more interesting changes.
We no longer track the closest object. We can do this because of how byond outputs objects with range()/view().
It outputs things in a spiral, starting from the center. [See](https://tgstation13.org/phpBB/viewtopic.php?f=5&t=25922)
Let me know if you want me to change this. It should speed up things slightly, it's mostly a cleanliness thing at this point.

And finally onto what I didn't change.
oview() for some insane reason cares about darkness. I've tried dview() and a modified version of that doview(), and neither worked. It didn't seem to return any objects from the for loop.  I plan on doing more testing on this in future.

## Why It's Good For The Game

Fixes #50506 
Cleans some stuff up, fixes some fucking weird shit. Documents some strange behavior.
Maybe now b**mer st##ion feature coders will stop being toxic towards my code.

## Changelog
:cl:
fix: Fixes teslas not containing properly sometimes
fix: Maybe makes tesla coil power output more sane, not totally sure myself
refactor: Refactored tesla code a bit
/:cl:

2020-04-19 14:38 UTC, spookydonut requested changes

2020-04-19 14:38 UTC, spookydonut commented on code/modules/power/tesla/energy_ball.dm
> +	for(var/atom/A in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
make this typeless

2020-04-19 14:38 UTC, spookydonut commented on code/modules/power/tesla/energy_ball.dm
> +	for(var/atom/A in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
```suggestion
	for(var/i in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
		var/atom/A = i
```

2020-04-19 22:39 UTC, LemonInTheDark commented on code/modules/power/tesla/energy_ball.dm
> +	for(var/atom/A in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
Finally a micro-op I can get behind.

2020-04-20 04:11 UTC, spookydonut commented on code/modules/power/tesla/energy_ball.dm
> +	for(var/atom/A in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
its not a micro opt its a normal opt

2020-04-23 21:38 UTC, Rohesie commented
Are you planning to include turfs in `zap_act()`? Else just use `atom/movable`

2020-04-24 00:10 UTC, LemonInTheDark commented
I'm gonna go with what spooky suggested. Using atom/movable would actually be a little bit slower because of how the list gets culled, and how typecache_filter_multi_list_exclusion works. At least I'm reasonably sure so.

2020-04-24 03:29 UTC, Rohesie commented on code/modules/power/supermatter/supermatter.dm
> +	var/target_type = 0
Keep a define here instead of a number.

2020-04-24 05:02 UTC, LemonInTheDark commented on code/modules/power/supermatter/supermatter.dm
> +	var/target_type = 0
sure

2020-04-24 05:03 UTC, LemonInTheDark commented on code/modules/power/tesla/energy_ball.dm
> +	for(var/atom/A in typecache_filter_multi_list_exclusion(oview(zap_range+2, source), things_to_shock, blacklisted_tesla_types))
done

2020-04-24 13:55 UTC, Rohesie commented
Alright, have you tested this locally to perform as you expect it to?

2020-04-24 22:24 UTC, LemonInTheDark commented
I have. My main concern is the reliance on the order view() outputs objects.

Is that an issue? It's a thing in this version, but from what I've heard people say it hasn't always been.

2020-04-25 00:27 UTC, Rohesie commented
Looks like `view()` lists things ordered by proximity. It scans one range-circle at a time. Which is an assumption this code does, correctly.
Not the best behavior to depend on, mind you, but it is what it is.

2020-04-25 00:34 UTC, merged