Adds the unwieldy element and an admin only sledgehammer
tgstation/tgstation pull request #50839
Opened 2020-05-03 07:18 UTC by Ryll-Ryll

## About The Pull Request
I originally did this with my wounds PR because I wanted to add a sledgehammer as a non-sharp counterpart to the fireaxe for breaking bones, but I figure I may as well atomize. This adds an unwieldy element, mainly for 2h weapons, that crudely emulates swinging a heavy weapon when attacking mobs. How crudely, you ask? This crudely!

[![unwield.png](https://i.imgur.com/alF2qxrl.jpg)](https://i.imgur.com/alF2qxr.png)

Depending if the weapon is in your left or right hand, the element will check the tile counter-clockwise or clockwise from you to your target for any solid obstructions. If there's something solid there, your attack hits the obstruction instead, and you're briefly stunned standing for half a second. Otherwise, the hit goes through and you switch hands on the weapon, so as to swing from the other side next. Fun!

## Why It's Good For The Game
Seems like it might be a fun mechanic to throw on big dangerous weapons like sledgehammers or giant swords/whatever to compensate for their raw killing/crippling power by making them more dangerous to use in cramped areas. I'm interested in hearing feedback on whether this might be a fun thing to throw on large, dangerous weapons maybe in exchange for some other buffs, or if people think it might be useful for other new weapons/concepts.

2020-05-03 07:20 UTC, necromanceranne commented
Is there no way for an overhead smash? this seems like it'll get pretty weird with how maint is laid out. Maybe if you aim for the head?

2020-05-03 07:35 UTC, PKPenguin321 commented
I dont like that it stuns you on a whiff, if it instead greatly raised your cooldown before you could attack again that would be better

2020-05-03 07:41 UTC, actioninja commented
maybe make you drop it or something like what pkp suggested, this just makes it ridiculously risky to actually use anything like this.

2020-05-03 07:45 UTC, Ryll-Ryll commented
It's not a paralyze "you fall over and are helpless" stun, it's the "you can't move + drop what you're holding" stun for half a second, just to clarify. You can also define your own behavior for each weapon, this is just what I came up with on the spot for the sledgehammer. I can easily change it to change cooldown or just make you drop it OR immobilize you for half a second, or whatever else would  be fitting.

2020-05-03 07:49 UTC, TemporalOroboros commented
So goliath tendril stun?

2020-05-03 07:49 UTC, necromanceranne commented
The concept of it stopping an attack based on what is around you is cool but making it a stun is probably not the best. Cooldown seems more fitting. And a loud _bonk_ sound to go with it.

2020-05-03 08:35 UTC, Fikou commented
maybe make it so that if you aim for the head after a 1-2 second do after you swing from above?

2020-05-03 12:30 UTC, Qustinnus commented
Ironically this would make it extremely hard to smash windows with this hammer even though it's purpose is to demolish things. I'd still like to see a solution for that tbf

2020-05-03 14:28 UTC, Ryll-Ryll commented
@Qustinnus nah i made it only check when you're swinging at a mob because i realized that issue t he first time I hit a window with it.

2020-05-03 14:29 UTC, Qustinnus commented
based

2020-05-04 00:21 UTC, PKPenguin321 commented
Really though, this shouldn't apply to attacking downed mobs or structures because think about it, you can just overhead swing

2020-05-22 23:19 UTC, ghost requested changes
Getting there but you need to use callbacks, hmu if you need help with that.

2020-05-22 23:19 UTC, Qustinnus commented on code/datums/elements/unwieldy.dm
> +	UnregisterSignal(target, list(COMSIG_ITEM_PRE_ATTACK))
list isn't needed

2020-05-22 23:19 UTC, Qustinnus commented on code/datums/elements/unwieldy.dm
> +		SEND_SIGNAL(I, COMSIG_UNWIELDY_BONK, user, intended_target, obstacle)
In cases like this you want a callback, as all you're doing is running behavior on the object the component is on.

2020-05-22 23:19 UTC, Qustinnus commented on code/game/objects/items/sledgehammer.dm
> +	icon_state = "hammeroff"
whats the point in this?

2020-05-22 23:19 UTC, Qustinnus commented on code/game/objects/items/sledgehammer.dm
> +	var/wielded = FALSE // track wielded status on item
don't do this, it's poor use of components as you shouldn't need to save the state of the component.

2020-05-22 23:19 UTC, Qustinnus commented on code/game/objects/items/sledgehammer.dm
> +/obj/item/sledge/afterattack(atom/A, mob/living/carbon/user, proximity)
this proc seems like it should be part of the unwieldy behavior, or be a callback thats run on the unwieldy component after a succesful hit.

2020-05-22 23:19 UTC, Qustinnus commented on code/modules/mob/inventory.dm
> +/mob/proc/force_hand_swap()
This skips over the proper procs for equipin and unequiping things from slots, and I don't think this is the right way of handling this.

2020-05-22 23:19 UTC, Qustinnus commented on code/modules/mob/inventory.dm
> +/mob/proc/force_hand_swap()
haha get it, handling? ok ill stop.

2020-05-22 23:20 UTC, Qustinnus commented on code/game/objects/items/sledgehammer.dm
> +/obj/item/sledge/afterattack(atom/A, mob/living/carbon/user, proximity)
On that note, that means you can also include things like the direction etc in the callback which means you dont have to do the calculations again.

2020-05-23 00:43 UTC, Ryll-Ryll commented
@Qustinnus thank you for the thorough reviews! I'm gonna mothball this PR for now since I don't have any immediate plans for stuff using this and there's lots of other PR's I have open already, but rest assured when I come back to this I'll thank you again for the review!

2020-05-23 00:43 UTC, closed without merging