Fixes juggernaut punch spell and new effects
tgstation/tgstation pull request #50954
Opened 2020-05-06 21:17 UTC by Garen7

## About The Pull Request

Fixes the juggernaut punch spell so it actually does the 30 damage and the 5 second knockdown it was supposed to do. Angelic constructs punch spell will no longer pass through cultists. New effects for the angelic juggernaut punch spell and force wall(they're basically the same as the normal ones but blue).

## Why It's Good For The Game

The angelic constructs should be able to hit cultists as that's what they were made to do. I made new effects since the old ones looked very cult like especially the part where a mini nar'sie face pops up.

## Changelog
:cl:
tweak: Angelic juggernaut constructs can now use their punch spell on cultists.
fix: Angelic juggernaut constructs' punch spell will now do the intended effect of 30 damage and a 5 second knockdown.
imageadd: Added new effects for the angelic juggernaut construct's spells
/:cl:

2020-05-06 21:17 UTC, Garen7 commented
Oops sorry for the commit spam

2020-05-07 11:07 UTC, Fikou commented on code/modules/spells/spell_types/construct_spells.dm
> +	splash_effect = /obj/effect/temp_visual/dir_setting/firing_effect/magic
newline

2020-05-07 18:31 UTC, Garen7 commented on code/modules/spells/spell_types/construct_spells.dm
> +	splash_effect = /obj/effect/temp_visual/dir_setting/firing_effect/magic
What do you mean?

2020-05-08 08:52 UTC, Twaticus approved these changes

2020-05-10 08:20 UTC, AnturK requested changes
Looks good, just some minor stuff

2020-05-10 08:20 UTC, AnturK commented on code/modules/spells/spell_types/construct_spells.dm
> +	splash_effect = /obj/effect/temp_visual/dir_setting/firing_effect/magic
Add a newline at the end of file.

2020-05-10 08:20 UTC, AnturK commented on code/modules/spells/spell_types/construct_spells.dm
> +	var/obj/effect/temp_visual/impact_effect = /obj/effect/temp_visual/cult/sac
You don't actually keep instances here so var type is bit misleading.

2020-05-11 19:50 UTC, merged