Various grammar and spelling fixes.
tgstation/tgstation pull request #51061
Opened 2020-05-11 10:14 UTC by Coconutwarrior97

## About The Pull Request

Fixes grammar/spelling related to the Space Dragon as outlined by #50602.

## Why It's Good For The Game

Grammar fixes are good.

## Changelog
:cl:

fix: Fixes grammar/spelling relating to Space Dragon.
/:cl:

2020-05-11 17:27 UTC, spessman-007 requested changes

2020-05-11 17:27 UTC, spessman-007 commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +	deathmessage = "screeches as its wings turn to dust and it collapses on the floor, its life exstinguished."
Should be extinguished

2020-05-11 23:39 UTC, Coconutwarrior97 commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +	deathmessage = "screeches as its wings turn to dust and it collapses on the floor, its life exstinguished."
Thanks for the catch!

2020-05-18 18:19 UTC, IndieanaJones commented
I was going to get to around to this, but I certainly don't mind someone else doing it, either.  👍

2020-05-25 04:31 UTC, kriskog commented
merge conflict

2020-05-28 17:39 UTC, AnturK commented
Still conflicts @Coconutwarrior97

2020-06-05 18:22 UTC, nemvar commented
Doesn't compile

2020-06-05 22:47 UTC, kriskog commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +>>>>>>> remotes/origin/master
You need to resolve this conflict. Remove everything but the correct line.

2020-06-12 10:58 UTC, kriskog commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +>>>>>>> remotes/origin/master
```suggestion
	priority_announce("A large amount of lifeforms have been detected approaching [station_name()] at extreme speeds.  
```

2020-06-12 11:02 UTC, kriskog commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +	priority_announce("A large amount of lifeforms have been detected approaching [station_name()] at extreme speeds.
```suggestion
	priority_announce("A large amount of lifeforms have been detected approaching [station_name()] at extreme speeds. Evacuation of the remamining crew will begin immediately.", "Central Command Spatial Corps")
```

2020-06-12 11:03 UTC, kriskog commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +	priority_announce("A large amount of lifeforms have been detected approaching [station_name()] at extreme speeds. Evacuation of the remamining crew will begin immediately.", "Central Command Spatial
```suggestion
	priority_announce("A large amount of lifeforms have been detected approaching [station_name()] at extreme speeds. Evacuation of the remaining crew will begin immediately.", "Central Command Spatial Corps")
```

2020-06-12 11:13 UTC, merged