light floors emit colored lights
tgstation/tgstation pull request #51097
Opened 2020-05-13 16:23 UTC by Tlaltecuhtli

:cl:
fix: lightfloor makes colored lights and are more visible
fix: you can turn them off by using your hand on it (ai can too)
fix: you can emp em
fix: breaking them actually works
fix: using a broken bulb wont fix em
sprites: flicker states for each colour
/:cl:

the "black" light doesnt make sense so i made it able to turn off and on
the "s" state was literally the same as color cycling just with some colors moved so i removed it

inb4 .dmi conflicts

2020-05-13 19:13 UTC, Qustinnus commented on code/game/turfs/open/floor/light_floor.dm
> +	var/state = 0
this should use defines

2020-05-13 19:41 UTC, trollbreeder commented on code/game/turfs/open/floor/light_floor.dm
> +	var/state = 0
```
	#define LIGHTFLOOR_FINE 0
	#define LIGHTFLOOR_FLICKER 1
	#define LIGHTFLOOR_BREAKING 2
	#define LIGHTFLOOR_BROKEN 3

	var/state = LIGHTFLOOR_FINE
```

2020-05-13 19:42 UTC, Qustinnus commented on code/game/turfs/open/floor/light_floor.dm
> +	var/state = 0
tlalt knows how to use defines

2020-05-15 04:36 UTC, RaveRadbury commented
Tlal, I just did the PR that added that stuff. The offset is so you can have alternating floors. The black sprite is so you can easily set up color systems. It's a QoL update.

I made #50966 recently

![image](https://user-images.githubusercontent.com/3204033/82011794-e26fec00-962a-11ea-8b74-d336bd1f9052.png)

I request that you do not include these changes in your PR.

2020-05-15 06:10 UTC, Tlaltecuhtli commented
u can have your alt color but having a fake turned off black tile is dumb i dont see how its a qol for someone to expect the black tile to not emit light but it does
 having togglable by hand click is more qol especially if some traitor wants some darkness quickly without having to fiddle with a vibrator wand

2020-05-15 06:24 UTC, Fikou commented
black light moment

2020-05-15 07:38 UTC, RaveRadbury commented
> having togglable by hand click 

The whole problem is that people walk onto these floors and accidentally click them. That's why I made it multitool only. Also, what traitor is in need of turning of dance floor light tiles??????

I made the previous PR with the intention of making light tiles only alterable with a multitool. The reasoning for that is obvious.

2020-05-15 09:51 UTC, Tlaltecuhtli commented
if someone accidentally click he can just click back, nightmares dont have multitools

2020-05-15 10:55 UTC, nemvar commented
put it on alt-click or something. just plain attack_hand sounds silly.

2020-05-15 18:23 UTC, RaveRadbury commented
> if someone accidentally click he can just click back, nightmares dont have multitools

Nightmares also have a blade that kills any light device, they don't need to flick a switch on a dance floor.

> put it on alt-click or something. just plain attack_hand sounds silly.

This almost works, but alt-clicking still has a bunch of other usages.

2020-05-25 05:39 UTC, kriskog submitted a review, later dismissed
.

2020-05-29 08:51 UTC, Rohesie requested changes
Do the changes requested by RaveRadbury please.

2020-05-31 11:03 UTC, Rohesie commented
@RaveRadbury ?

2020-06-02 04:48 UTC, RaveRadbury commented
Putting the on/off switch onto a screwdriver is fine. Tlal seems to be committed to the idea of having the black color setting be a separate and literal switch. Given the improvements that he has made to the light tiles here I am alright with this change, as ultimately it's a realism vs ease argument.

I don't quite understand why all the colors have unique names when they are quite literally ROYGBIV but it's not really an issue.

Reviewing the icon changes, light_on_flicker-9 and light_on_flicker-10 have a stray yellow pixel in the upper right of several frames. This should be addressed.

Other than the stray pixels this all looks good. Sorry I just got to this now.

2020-06-02 07:27 UTC, Rohesie commented
Could you fix the stray pixels then? We can merge after that.

2020-06-02 15:09 UTC, Tlaltecuhtli commented
i checked the icons and i see no yellow pixel in light_on_flicker-9 and light_on_flicker-10

2020-06-02 17:39 UTC, RaveRadbury commented
![image](https://user-images.githubusercontent.com/3204033/83551569-57617380-a4bd-11ea-8759-20e3e40ba27d.png)

It's there, on multiple frames.

2020-06-02 17:56 UTC, Tlaltecuhtli commented
there are no white tile sprites on -9 and -10 (multicolors), even -8 (the white tile) doesnt have it are you sure you havent missclicked a pixel on your local?

2020-06-02 18:18 UTC, RaveRadbury commented
I downloaded this from the check tab, is there a reason why the check tab would throw this kind of error?

2020-06-02 18:24 UTC, RaveRadbury commented
@Tlaltecuhtli I checked out your PR on local and I didn't see the pixels. It seems that it is an issue with the icon-diff bot. Apologies for hanging up your PR on this.

@Rohesie It's good to go

2020-06-03 01:51 UTC, merged