Rebalanced timestop
tgstation/tgstation pull request #51168
Opened 2020-05-19 09:53 UTC by Terra1

## About The Pull Request

Increases timestop freeze range to 11x11, but decreases freeze time to 8s.
Note: I haven't actually tested or compiled the code yet, but it _should_ work, since it's just a minor value change.

## Why It's Good For The Game

Timestop breaks the current direction for combat. We're supposed to be moving away from instant stuns, not towards, right?
So, basically, this changes timestop into more of an area denial and getaway spell, with the long freeze range allowing use during a chase, and the short freeze length making offensive use less viable.

## Changelog
:cl:
tweak: Increased timestop freeze range, decreased timestop freeze length..
/:cl:

2020-05-19 11:33 UTC, SkeletalElite commented
If people want a defensive spell to use during chase they're going to take force wall, which is on a much shorter cool down, and has a longer effect. The entire purpose of time stop is being a high cool down but multipurpose area control and that includes offensive use. Not to mention this isn't the only stun wizard has. Wizard also has repulse and a variety of spells that electrocute (which is a stun without insuls.) It's also worth mentioning that smite exists, which while it isn't a stun, is literally instant kill.  Also not an instant stun, lesser summon guns does like 60 stamina damage, which is a 2 shot stun and is spammable in bursts. Wizard still has stuns because wizard is meant to be a one man army.

2020-05-19 13:33 UTC, wesoda25 commented
Bruh 11x11 is BIG

2020-05-19 16:26 UTC, SkeletalElite commented
Also am I stupid or would range 5 be a 10x10 not an 11x11 (still really big though)

2020-05-19 16:45 UTC, bobbahbrown commented
Why have you decided on these changes without testing them? Do you feel that the 11x11 radius and 8 second effect is reasonable without having tested it?

I don't fully understand your justification for these changes.

2020-05-19 17:29 UTC, ATH1909 commented
You do realize that this is actually a BUFF to time stop, right?

2020-05-19 18:05 UTC, wesoda25 commented
Honestly whose alt is this

2020-05-20 04:44 UTC, 2whatever2 commented
> Edit: also forgot to mention getting smashed into a wall with mjolnir is a stun too

Mjolnir is a stun even if you don't hit them into a wall it's always a 100% stun, Singularity hammer also does a stun if you hit a tile with the hammer wielded.

2020-05-20 07:14 UTC, Terra1 commented
> 
> 
> You do realize that this is actually a BUFF to time stop, right?

It isn't a buff - it lasts 6 fewer seconds than before, making it almost useless as an offensive spell.

2020-05-20 08:07 UTC, Fikou commented
does this even resize the timestop effect size? it will look really janky if it doesnt

2020-05-20 08:10 UTC, ATH1909 commented
> > You do realize that this is actually a BUFF to time stop, right?
> 
> It isn't a buff - it lasts 6 fewer seconds than before, making it almost useless as an offensive spell.

> 8 second hardstun that also makes you nigh-immune to projectiles
> useless

2020-05-20 18:09 UTC, Shadowflame909 commented
![addtext_com_MTQwOTIyMTA1NjU](https://user-images.githubusercontent.com/29222521/82481604-6c381300-9a8a-11ea-9af7-4addd8f19a1c.jpg)

2020-05-21 13:04 UTC, HomocidlePancakes commented
>Post above

He’s trolling if you haven’t figured it out.
2/10 shitpost, no funny pictures, no funny rant.

2020-05-21 13:34 UTC, HomocidlePancakes commented
Like, the fact that so many people seem to be taking this seriously only shows how cringe this is.

2020-05-22 05:53 UTC, ATH1909 commented
> Like, the fact that so many people seem to be taking this seriously only shows how cringe this is.

https://github.com/tgstation/tgstation/pull/51094

Judging by this other PR, I think he might be serious.

2020-05-22 06:27 UTC, HomocidlePancakes commented
Nah that PR was serious. This PR is him trying to flex because his nerf was dismissed.

2020-05-25 06:04 UTC, kriskog requested changes
A modearate duration reduction (1-2 seconds so it cant be chained as easily) is fine, but keep the size where its at.

2020-05-25 12:37 UTC, Qustinnus commented on code/modules/fields/timestop.dm
> +	var/duration = 80
use time defines

2020-05-30 08:00 UTC, Rohesie commented on code/modules/fields/timestop.dm
> +	var/duration = 80
```suggestion
	var/duration = 8 SECONDS
```
This is what Floyd means.

2020-06-07 12:56 UTC, closed without merging