Moves client vars to their definition
tgstation/tgstation pull request #51325
Opened 2020-05-27 05:15 UTC by Rohesie

Defining variables elsewhere breaks the langserv Go to Definition feature and promotes messy code.

2020-05-27 22:30 UTC, Cyberboss approved these changes

2020-05-29 05:13 UTC, spookydonut commented
Thats more a problem with dm langserver than it is with our code. 👎

2020-05-29 07:12 UTC, Rohesie commented
It is also better to have the client defines in `client_defines.dm` same for every other variable.
Clearer to be able to look at a single place to see the object's defined variables.

2020-05-29 13:44 UTC, Cyberboss requested changes
Be a bae and do that please c:

2020-05-29 17:23 UTC, Rohesie commented
Sorry, could you clarify the request?
This is what the PR is doing.
I've done other similar ones in the past, moving variables to their object's definition.
I seem to have missed these, though.

2020-05-29 17:29 UTC, Cyberboss approved these changes
Yeah I'm dumb

2020-06-01 00:42 UTC, nemvar commented
Haha merge button go brrrrrr

2020-06-01 00:42 UTC, merged