Adds a Pride Week themed bar sign.
tgstation/tgstation pull request #51423
Opened 2020-06-02 04:39 UTC by genessee596

## About The Pull Request

![image](https://user-images.githubusercontent.com/46986487/83480377-29eada80-a469-11ea-8698-30a42a5d119b.png)
Does what it says on the tin. Adds a new barsign to celebrate pride week, that's it. Doesn't do anything with other barsigns, and is totally optional for the bartender to set it to or whatever. Called 'The Pride Bar'.

## Why It's Good For The Game

A little nod to Pride Week for those who desire it, but nothing too flashy to avoid taking away from the main SS13 holiday events.

## Changelog
:cl:
add: Added a new bar sign to celebrate Pride Week.
/:cl:

2020-06-02 04:55 UTC, bobbah requested changes

2020-06-02 04:55 UTC, bobbahbrown commented on code/game/objects/structures/barsigns.dm
> +
why new lines
```suggestion
```

2020-06-02 04:56 UTC, bobbahbrown commented
is this intended to be something that is testmerged for the duration of pride week? otherwise it seems like an odd addition to the codebase for the majority of the year

2020-06-02 05:02 UTC, genessee596 commented
> is this intended to be something that is testmerged for the duration of pride week? otherwise it seems like an odd addition to the codebase for the majority of the year

Testmerged for prideweek, yeah.

2020-06-02 05:03 UTC, MrPerson commented
Gay bars are a thing all year round and it's nice to have a little nod to them that's not cringey.

2020-06-02 05:07 UTC, genessee596 commented
Fixing colors really quickly, right now it's kind of hard to read the text - please hold



> Gay bars are a thing all year round and it's nice to have a little nod to them that's not cringey.
> 
> EDIT: You could also hide it behind a holiday datum if you absolutely insist on it.

Meh, I'm lazy and stupid, so I'll avoid putting the holiday datum for now

2020-06-02 05:14 UTC, genessee596 commented on code/game/objects/structures/barsigns.dm
> +
Whoopsie. My bad!

2020-06-02 05:17 UTC, genessee596 commented
Edited sign text coloring to make it easier to read.

2020-06-02 06:24 UTC, ishitbyabullet commented
Can you give the text outlines or something? It's hard to read.

2020-06-02 06:27 UTC, genessee596 commented
> Can you give the text outlines or something? It's hard to read.

I don't think there's enough room to do an outline? I'll double-check in a few hours, but I think it'll make it look crappy.

2020-06-02 06:40 UTC, wesoda25 commented
I think more frames would definitely help this one, seems very bare bones currently. Thinking stuff like flashing colors or the rainbow having some sort of movement.

2020-06-02 06:55 UTC, genessee596 commented
> I think more frames would definitely help this one, seems very bare bones currently. Thinking stuff like flashing colors or the rainbow having some sort of movement.

Remember, this is only getting testmerged for a week.

2020-06-02 08:56 UTC, carshalash commented
Colons are a little hard to see and some of the choice of colors for the letters make it a lil hard to see.

2020-06-02 09:45 UTC, necromanceranne commented
I'd make the colours bold dark colours to stand out from the already colourful background. Like, straight up a black would be fine.

Also

LET'S START A WAR
LET'S START A NUCLEAR WAR
AT THE GAY BAR, GAY BAR, GAY BAR

(if the nukie bar doesn't come set default to the pride flag I'll be deeply upset is what I'm saying)

2020-06-02 10:24 UTC, PKPenguin321 commented
Maybe it's because it's a pixel based sprite but I'm getting mad nyan cat vibes off of this

2020-06-02 12:12 UTC, Twaticus requested changes
Way too many clashing colors making it barely legible.

If youre going for a neon lights display, the backround needs to be muted with the text bright. Could be a black backround with rainbow text, or dark rainbow backround with light rainbow text. See thegreytide, maltesefalcon, theouterspess.

An LCD type display could really be anything as long as its readable. It could be as complicated as thenet or as simple as thewretchedhive. Maybe something like thesingulo where its a simple text but animated rainbow on the side?

The other option is something like alohasnackbar where it can straight up be a pride flag on the wall.

Sorry for wall of text but this sprite aint it chief hope this helps.

2020-06-02 12:43 UTC, TheVekter commented
We're doing a bit of a bigger pride week thing and Genessee gave me permission to use this in that.

2020-06-02 16:33 UTC, genessee596 commented
> We're doing a bit of a bigger pride week thing and Genessee gave me permission to use this in that.

This is true, this has been rolled in with that.

2020-06-02 16:33 UTC, closed without merging

2020-06-03 21:49 UTC, interestingusernam3 commented
>Colons are a little hard to see

Clearly the owners of those colons are not gay enough