Simplifies ear damage, allows empaths to properly spot deafness
tgstation/tgstation pull request #51436
Opened 2020-06-03 08:41 UTC by Ryll-Ryll

## About The Pull Request
Ears currently behave strangely compared to other organs, especially their most closely related sensory organ, eyes. They only assign a deafness trait for quirks, mutations, and clothing (which prevents empaths from noticing hearing damage deafness), have lots of unnecessary procs for dealing/assessing damage, and several audible events check istype() for earmuffs specifically for whether a mob can hear something.

This cuts down on all of that. I removed most ear related procs from mobs, tied deafness explicitly to TRAIT_DEAF (and added a new source for hearing damage), and generally neatened up related code. As a direct result, empaths can now detect deafness from hearing damage, as I assume was intended. I also fixed a bug with examining with med HUD's or as an observer not showing a person's quirks, though I'm not sure people will really care about the info with med HUDs. Also, full revives/regenerating organs now remove all damage from existing organs rather than only trying to replace missing ones

In addition, Inacusiate and Sensory Restoration no longer instantly cure all hearing damage when applied, they now rapidly decrease both ear damage and deafness each tick. This isn't really a fix, but I figured I'd throw it in since I think cobby wanted to move away from instant fix microdose chems, and I punted the restoreEars() procs anyway

Fixes: #51435 
Fixes: #48974

## Why It's Good For The Game
Brings ears in line with how other organs operate, makes them easier to understand, and restores (what I assume to be) intended functionality for the empath quirk and medhud/observer examines

## Changelog
:cl: Ryll/Shaps
fix: Empaths are able to detect deafness derived from hearing damage
tweak: Inacusiate and Sensory Restoration no longer instantly heal all hearing damage when applied, instead rapidly removing both ear damage and deafness.
fix: MedHUDs and observers now display quirks as intended on examine
/:cl:

2020-06-11 02:33 UTC, Ryll-Ryll commented
This should be good for review/merge

2020-06-14 11:46 UTC, AnturK requested changes
Was this tested, organ changes cause domino effects often.

2020-06-14 11:46 UTC, AnturK commented on code/modules/surgery/organs/ears.dm
> +	if(HAS_TRAIT_NOT_FROM(owner, TRAIT_DEAF, EAR_DAMAGE))
This should still call parent though ?

2020-06-14 13:12 UTC, Ryll-Ryll commented on code/modules/surgery/organs/ears.dm
> +	if(HAS_TRAIT_NOT_FROM(owner, TRAIT_DEAF, EAR_DAMAGE))
ah right you are fixed

2020-06-14 13:14 UTC, Ryll-Ryll commented
@AnturK I tested by throwing flashbangs at myself and standing on them both close and far away, and the ear damage dropped as it was supposed to, but I can do a more rigorous battery with enough flashbangs to fully kill ears if you'd like

2020-06-18 22:51 UTC, merged