restores racial equality to the revolution
tgstation/tgstation pull request #51443
Opened 2020-06-03 14:05 UTC by tmtmtl30

## About The Pull Request

sometimes, during a revolution, converted revolutionaries will be "promoted" to headrevs if the number of heads of staff / security officers increases significantly enough that another head revolutionary is warranted for balance concerns. for some dumbass reason, nonhuman revolutionaries are only promoted if there aren't any eligible human revolutionaries. this is stupid; this PR removes the check.

## Why It's Good For The Game

"This is why those humans who want to escape their own slavery must first of all rally to the lizard revolt — not, obviously, in species solidarity, but in a joint galactic rejection of the commodity and of the state."

-Guy Debord, _The Decline and Fall of the Spectacle-Commodity Economy_, 2505

## Changelog
:cl:
tweak: Nonhuman revolutionaries are now just as likely as human revolutionaries to be promoted to headrevs.
/:cl:

2020-06-03 14:07 UTC, ExcessiveUseOfCobblestone commented
wonder why this was added lol

2020-06-03 15:00 UTC, ArcaneDefence commented
viva

2020-06-03 15:00 UTC, necromanceranne commented
Maybe it has to do with heads being human? Very peculiar given roundstarf revs don't have this restriction.

2020-06-03 15:19 UTC, Tlaltecuhtli commented
didnt even know this exsited,  why does it need to be removed?

2020-06-03 15:19 UTC, Kaffe-work commented
based racism against inferior races, not even in code are subhumans safe

2020-06-03 15:21 UTC, tmtmtl30 commented
@Tlaltecuhtli i'm not aware of any other scenarios where nonhumans are put at a lower chance of becoming antagonists. it's inconsistent and doesn't make sense to have. the less bloat in the horrific mess of gamemode and antagonist code, the better

2020-06-03 15:52 UTC, Qustinnus commented
make it generic so all non humans will have a lower chance of being an antag.

2020-06-03 16:03 UTC, tmtmtl30 commented
despite making up only 70% of the nanotransen workforce, humans commit 95% of the insurrections

2020-06-03 18:16 UTC, ATH1909 commented
er, doesn't "ishuman()" just check to see if you're a humanoid, not if you're specifically a human (and not, say, a lizard)? this check could be here to keep stuff like simplemob headrevs from becoming a thing

2020-06-03 19:25 UTC, ExcessiveUseOfCobblestone commented
you're right, i got baited 😭

2020-06-03 19:27 UTC, Qustinnus commented
lmao i shouldve checked the code. you know its bad when athath points it out

2020-06-03 20:16 UTC, trollbreeder commented
ishuman(M) checks for mob/living/carbon/human, which all spacemen are regardless of race or species (hope that confirms your everyone is mutant lore), and ishumanbasic(M) checks for the human species only.

2020-06-03 20:28 UTC, PKPenguin321 requested changes

2020-06-03 20:28 UTC, PKPenguin321 commented on code/modules/antagonists/revolution/revolution.dm
> -			if(!promotable.len && nonhuman_promotable.len) //if only nonhuman revolutionaries remain, promote one of them to the leadership.
ishuman isn't a race check, it checks if their path is mob/carbon/human
"Nonhuman" in this context means shit like borgs or sentient slimes

2020-06-03 22:28 UTC, tmtmtl30 commented
FUCK

2020-06-03 22:28 UTC, closed without merging

2020-06-03 22:31 UTC, tmtmtl30 commented
(i mean admittedly a slime revhead would be cool but i can see the argument that it would be unbalanced)

2020-06-05 04:35 UTC, Shadowflame909 commented
borg head rev could still flash tho

reopen now!!!