Removes some var/const that should be defines
tgstation/tgstation pull request #51461
Opened 2020-06-05 03:08 UTC by spookydonut

## About The Pull Request
Don't use const for this shit it causes runtimes with shit like holodeck
```
[21:54:41] Runtime in area_copy.dm,26: Cannot write to /obj/item/pizzabox/pineapple/var/const/BOMB_TIMER_MIN

  proc name: DuplicateObject (/proc/DuplicateObject)
  usr: The John Smith/(Malcolm Blackmore)
  usr.loc: (Abandoned Gambling Den (189, 150, 3))
  src: null
  call stack:
  DuplicateObject(the pizza box (/obj/item/pizzabox/pineapple), 1, null, the floor (191,146,3) (/turf/open/floor/plasteel/white), 1, 1)
  PropHunt - Maintanence (/area/prophunt/mg2/doubleoh): copy contents to(the Recreational prophunt (/area/prophunt/mg2), 1, 1)
  the prophunt control console (/obj/machinery/computer/prophunt): load program(PropHunt - Maintanence (/area/prophunt/mg2/doubleoh), 0, 1)
  the prophunt control console (/obj/machinery/computer/prophunt): ui act("load_program", /list (/list), /datum/tgui (/datum/tgui), /datum/ui_state/default (/datum/ui_state/default))
  /datum/tgui (/datum/tgui): Topic("src=%5B0x21001ac8%5D&action=lo...", /list (/list))
  The John Smith (/client): Topic("src=%5B0x21001ac8%5D&action=lo...", /list (/list), /datum/tgui (/datum/tgui))
  The John Smith (/client): Topic("src=%5B0x21001ac8%5D&action=lo...", /list (/list), /datum/tgui (/datum/tgui))
```

## Why It's Good For The Game
If you want to stop something being vareditted then use a define

2020-06-05 03:42 UTC, WarlockD commented
Wait so var/const shows up in vars?   is it posable to detect them with istype(T,/var/const)?

2020-06-05 07:59 UTC, Jordie0608 commented
I hope nobody has been trying to put a database subsystem onto the holodeck.

2020-06-05 08:33 UTC, AnturK commented
Throw some prefixes or undefines there, some of these have horribly generic names.

2020-06-05 09:54 UTC, spookydonut commented
> 
> 
> Throw some prefixes or undefines there, some of these have horribly generic names.

dreamchecker detects and throws errors on duplicate defines

2020-06-06 17:58 UTC, ShizCalev commented on code/modules/food_and_drinks/pizzabox.dm
> +#define BOMB_TIMER_MAX 10
this seems better off as a normal var for admin editing tbh.

2020-06-06 17:59 UTC, ShizCalev commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +#define BOTTLE_KNOCKDOWN_DURATION 13
some here tbh

2020-06-06 18:03 UTC, ShizCalev commented on code/game/objects/items/devices/powersink.dm
> +#define OPERATING 2
should undef these after since they're so generic.

2020-06-06 18:04 UTC, ShizCalev commented on code/game/objects/structures/transit_tubes/station.dm
> +#define CLOSE_DURATION 6
undef at end

2020-06-06 18:04 UTC, ShizCalev commented on code/modules/power/singularity/field_generator.dm
> +#define NUM_POWER_LEVELS 6
undef when done

2020-06-06 18:05 UTC, ShizCalev commented on code/_onclick/hud/picture_in_picture.dm
> +#define MAX_DIMENSIONS 10
this is used in only a single place, just set the value and comment in the proc instead.

2020-06-06 18:06 UTC, ShizCalev commented on code/controllers/subsystem/dbcore.dm
> +#define FAILED_DB_CONNECTION_CUTOFF 5
only used in a single place and the proc comments on the exact time, might as well just put the number in the proc instead.

2020-06-06 18:07 UTC, ShizCalev commented on code/game/machinery/computer/communications.dm
> +#define STATE_PURCHASE 11
undef when done

2020-06-10 00:57 UTC, Cyberboss requested changes
What Shiz said

2020-06-16 10:12 UTC, ShizCalev requested changes

2020-06-16 10:12 UTC, ShizCalev commented on code/game/machinery/computer/camera.dm
> +#define DEFAULT_MAP_SIZE 15
undef

2020-06-16 10:12 UTC, ShizCalev commented on code/modules/antagonists/disease/disease_mob.dm
> +#define FREEMOVE_TIME 1200
undef

2020-06-25 07:00 UTC, merged