Converts the Cargo Bounties UI to TGUI and adds a modular app for it.
tgstation/tgstation pull request #51509
Opened 2020-06-08 07:13 UTC by ArcaneMusic

How did bounty boards take me like 2 months but I finished this in 4 hours on a weekend, I'd be proud if I wasn't so baffled

## About The Pull Request

![image](https://user-images.githubusercontent.com/41715314/84001394-800dc100-a934-11ea-86a1-d621dd766da8.png)
_Standard, standalone computer UI on the left, modular app UI on the right._
First and foremost, this reworks the cargo bounty UI to work within TGUI. Functionality is fully the same, but it means that there's no longer a need for a refresh button at the top right alongside the bounty sheet printer.
Second, while I was staring at this, I also ported it over to a modular computer app because it turned out to be a lot simpler than I imagined, considering it runs off of global lists.
Lastly, I went and pre-installed both this app as well as the other cargo-inspired app into the cargo tablets. For those installing the app instead, it requires cargo access to be downloaded, but it enables cargo crew to claim and read the list of bounties anywhere on the station.

## Why It's Good For The Game

I tried doing a project with the cargo bounty system a while back, but because of the un-responsiveness from the HTML UI, it was enabling all sorts of weird bugs and issues, and being a TGUI will help solve some problems down the road.
Also, this is a major part of what cargo can and should be doing during the shift, so having bounties available on a tablet increases the value of the modular app system as well. As an added bonus, now the cargo tablet has a reason to be used outside of "sell it for parts".

## Changelog
:cl:
add: Adds the Cargo Bounty UI as a modular app, with cargo access.
tweak: The Cargo Bounty UI has been revamped.
tweak: Cargo tablets now come preinstalled with the price tagger and cargo bounty apps.
/:cl:

2020-06-08 09:41 UTC, TheVekter commented
I am so fucking rigid right now

How hard would it be to make a modular app for ordering shit from cargo?

2020-06-08 12:55 UTC, zxaber commented
The requests console is already tgui, so probably not difficult at all.

2020-06-12 00:58 UTC, Twaticus approved these changes

2020-06-12 12:13 UTC, stylemistake submitted a review, later dismissed

2020-06-12 23:19 UTC, ArcaneMusic commented
Quick screenshot of the post updated visuals, High priority bounties are still highlighted.
![image](https://user-images.githubusercontent.com/41715314/84553260-ae4b2200-ace1-11ea-86dd-a5b71e54fb98.png)

2020-06-13 13:42 UTC, stylemistake commented on tgui/packages/tgui/interfaces/CargoBountyConsole.js
> +          title=<BountyHeader />
```suggestion
          title={<BountyHeader />}
```

2020-06-13 13:42 UTC, stylemistake commented on tgui/packages/tgui/interfaces/NtosBountyConsole.js
> +          title=<BountyHeader />
```suggestion
          title={<BountyHeader />}
```

2020-06-27 08:52 UTC, AnturK requested changes

2020-06-27 08:52 UTC, AnturK commented on code/modules/cargo/bounty_console.dm
> +	var/datum/bounty/cashmoney = locate(params["bounty"]) in GLOB.bounties_list
Move this inside the case its for.

2020-06-27 08:52 UTC, AnturK commented on code/modules/cargo/bounty_console.dm
> +	. = TRUE
Why are you updating if there was no changes. This should only return true for claim here from what i can see.

2020-06-28 09:18 UTC, AnturK commented on tgui/packages/tgui/interfaces/CargoBountyConsole.js
> +            <Flex>
Why Flex if there's only a single element

2020-06-28 09:56 UTC, merged