Support fireman carrying people onto trays
tgstation/tgstation pull request #51539
Opened 2020-06-09 09:15 UTC by Jared-Fogle

## About The Pull Request

This PR lets you click on open trays while fireman carrying on them to place them on it.

## Why It's Good For The Game

Currently, if you are fireman carrying someone, the best course of action is to close the tray if it is open, stand on top of the tile, drop the person, stand out of the way, then close the tray. You might be able to drag and drop their sprite as well, though this is still not as intuitive as simply clicking on the tray.

## Changelog
:cl:
add: You can now place people you are fireman carrying onto trays.
/:cl:

2020-06-09 10:50 UTC, Twaticus commented
wow i thought you meant food trays until i read the branch name wtf

2020-06-09 10:59 UTC, Jared-Fogle commented
Changed it to be more obvious then.

2020-06-09 12:10 UTC, WarlockD commented
*obligatory vore refrence*  Just curious, why do you call them trays?  Not that I have a better name mind you.

2020-06-09 12:17 UTC, XDTM commented
If i'm not wrong, it's because actual morgues keep bodies on large trays, i suppose to make it easier to move them around. In SS13 they behave more like drawers, but i suppose the original term stuck for realism.

2020-06-09 12:31 UTC, Jared-Fogle commented
*I* called them trays just because that's what it's code named.

2020-06-09 15:25 UTC, Iatots commented
Perhaps you should be able to set people down on roller beds too?

2020-06-10 01:00 UTC, Jared-Fogle commented
@Iatots I can do that.

2020-06-10 01:41 UTC, Jared-Fogle commented
Before I commit that, can anyone think of a scenario of an oversight with that? Fireman carrying someone, clicking on something that can buckle, and it putting them in like normal?

2020-06-10 05:19 UTC, Twaticus commented
im still laughing about carrying people on food trays

2020-06-17 13:58 UTC, ExcessiveUseOfCobblestone requested changes
please format both to be

```DM
if(!check)
    return ..()
rest of code
```

Also if it meets the req it will not send the attackbysignal

2020-06-18 04:46 UTC, Jared-Fogle commented
@ExcessiveUseOfCobblestone Will do that tonight.

2020-06-23 23:58 UTC, Jared-Fogle commented
I have since my message made those changes.

2020-07-01 00:36 UTC, Jared-Fogle commented
It's been ready for a long time.

2020-07-01 00:42 UTC, Jared-Fogle commented on code/game/objects/buckling.dm
> +		return ..()
Looking at this condition again now--what happens if you attack a chair? Will check to make sure it's normal.

2020-07-01 00:49 UTC, Jared-Fogle commented on code/game/objects/buckling.dm
> +		return ..()
It works fine, but I don't know if that's just a lucky coincidence based on the ordering.

2020-07-02 23:25 UTC, merged