replaces the normal medbot on the library ship with a mysterious one
tgstation/tgstation pull request #51629
Opened 2020-06-13 22:29 UTC by ATH1909

## About The Pull Request

Replaces the normal medbot on the library ship space ruin with the currently unused "International Medibot of Mystery" one.

## Why It's Good For The Game

The library ship currently has basically no loot in it, which makes it kind of pointless for most space explorers. It's basically the space equivalent of the sloth ruin (except less obstructive/annoying to encounter). Now there is a special medbot there that you can bring back to Medbay or put on your white ship or whatever, provided that you're willing to drag it behind you all the way to wherever you want to move it to.

## Changelog
:cl: ATHATH
balance: The medbot on the library ship is now more mysterious.
/:cl:

2020-06-15 18:34 UTC, TotallyNotChief commented
why not actually make the ship somewhat interesting instead, like i dunno maybe make it into an actual shuttle

2020-06-15 23:47 UTC, Pumpkinoe commented
if nobody wants to make it into an actual shuttle or make it interesting in other ways this is a fine placeholder tbh

2020-06-16 13:12 UTC, ExcessiveUseOfCobblestone commented
um you might want to lower the heal amount lol.

2020-06-16 21:59 UTC, ShizCalev requested changes
this is a CENTCOM heal-everything ridiculously fast variant. use/make a subtype of `/mob/living/simple_animal/bot/medbot/derelict` instead.

2020-06-16 23:50 UTC, ATH1909 commented
> this is a CENTCOM heal-everything ridiculously fast variant. use/make a subtype of `/mob/living/simple_animal/bot/medbot/derelict` instead.

sure

2020-06-22 11:02 UTC, Doosteroni commented
LAME! You removed the supa-medibot

2020-06-30 22:21 UTC, merged