manly dorf now still gets you drunk with dorf mutation
tgstation/tgstation pull request #51940
Opened 2020-06-30 17:32 UTC by Fikou

## About The Pull Request

manly dorf with dwarf mutation/alcohol tolerance quirk sets the boozepwr to 5, and then heals 2 brute and 2 burn every tick
now it doesnt set boozepwr to 5 so at least you get drunk with your free healing

## Why It's Good For The Game

with a single quirk a really easy recipe becomes a c3 healing chem, now it will at least damage your liver or something

## Changelog
:cl:
balance: manly dorf now still gets you drunk with dorf mutation
/:cl:

2020-06-30 21:48 UTC, ATH1909 commented
this (and maybe quadruple/quintuple sec) is pretty much the only reason to take the alcohol tolerance quirk (which is effectively a 2 point quirk because it's mutually exclusive with light drinker)

2020-06-30 22:57 UTC, Fikou commented
>(which is effectively a 2 point quirk because it's mutually exclusive with light drinker)

are you dense

2020-06-30 23:37 UTC, ATH1909 commented
> > (which is effectively a 2 point quirk because it's mutually exclusive with light drinker)
> 
> are you dense

light drinker is a free +1 quirk point because it has absolutely 0 impact in 99.9999999999% of situations (if you're not a bartender), mostly because most bartender drinks are either shit or way too expensive/hard to make compared to their "real medicine" counterparts. taking alcohol tolerance means that you can't take light drinker, which means that you have to find another source for that +1 quirk point (opportunity cost, y'see). 1+1=2.

2020-07-01 04:14 UTC, carshalash commented
Dorf is a cringe drink to be honest.

2020-07-01 05:56 UTC, necromanceranne commented
@Fikou he's asking you to close the pr so he can keep powergaming the low booze power c2 level healing while retaining perfect perk balance for other due to low alcohol tolerence acting as a zero'd out perk with dwarfism. Just ignore him.

2020-07-01 06:42 UTC, ATH1909 commented
> @Fikou he's asking you to close the pr so he can keep powergaming the low booze power c2 level healing while retaining his perk loadout, due to low alcohol tolerence acting as a zero'd out perk with dwarfism.
> 
> Just ignore him basically.

I still use light drinker over alcohol tolerance, though (so that I can afford the Spiritual Quirk).

Also, did you not hear me mention multiple times that alcohol tolerance is mutually exclusive with light drinker? You can't take both.

2020-07-01 07:01 UTC, ATH1909 commented
ohhhhhhhh wait you meant dwarfism the mutation not alcohol tolerance the quirk

nah, I don't do that (yet). I prefer white kits over chems for healing, since I'm an impatient bastard (and, unlike manly dorf, they work on most other people, although I could carry around a dwarfism mutator, I suppose...). an aiuri/libital/manly dorf mix sounds pretty good, though; I might try that out next time I have nothing better to do (and dwarfism is available).

2020-07-01 19:09 UTC, Kaffe-work commented
healing others is cringe, why would you help someone else?

2020-07-02 00:21 UTC, ATH1909 commented
> healing others is cringe, why would you help someone else?

it makes me feel warm and fuzzy inside

2020-07-02 08:30 UTC, ArcaneDefence commented
I carry a bottle of manly dorf because it's near zero effort mass produced very generalist healing that also gives a moodlet. 
Sometimes I even use it in glasses to throw at people and set them on fire.

The least it could do is make me drunk.

2020-07-02 09:58 UTC, Fikou commented
> I carry a bottle of manly dorf because it's near zero effort mass produced very generalist healing that also gives a moodlet.

same 😳

2020-07-03 01:30 UTC, ExcessiveUseOfCobblestone commented
just take off the alcohol quirk check tbh, im not sure how that passed through since that is a strong combat-oriented buff for a quirk.

not even considering the fact the bonus loses its joke when you dont have to be a dwarf to get the bonuses of dwarfdrink

2020-07-03 02:29 UTC, carshalash commented
As someone who thinks that healing/beneficial drinks have a strong place in the codebase, this NEEDS to at the very least have an alcoholic value. This drink has no complexity to its creation and can be mass produced at round start with literally no effort, every other drink requires things from other departments to be made or a metric fuck tonne of power to be made. 

Having the "Yeah b-b-b-but it needs a mutation to be used!" is an incredibly flimsy defense to this, this heals both brute and burn at bicaridine level and doesn't even have the downside of getting you drunk.  If you want to larp as "heehoo funny drunk dorf" then deal with being drunk.

2020-07-03 04:23 UTC, Shadowflame909 commented
this pr is a 30 minute mans cobby chem

2020-07-04 16:33 UTC, kriskog requested changes
What cobby said

2020-07-07 19:10 UTC, ExcessiveUseOfCobblestone commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +			boozepwr = 5
```suggestion
			boozepwr = 50 // will still smash but not as much.
```

2020-07-07 20:00 UTC, merged