Monkey mind mag helmets's sprites don't break on updating their icon_state
tgstation/tgstation pull request #52155
Opened 2020-07-10 22:08 UTC by tralezab

## About The Pull Request

adds a special override for update icon that keeps the light color.

## Why It's Good For The Game

ERROR ERROR

## Changelog
:cl:
fix: mind mag helms losing their icon sometimes
/:cl:

2020-07-10 22:11 UTC, tralezab commented
![image](https://user-images.githubusercontent.com/40974010/87206974-a1f5bd00-c2bf-11ea-8bc0-942acbf2be87.png)

2020-07-10 22:14 UTC, yeeyeh commented
munkee

2020-07-11 01:00 UTC, ShizCalev commented on code/modules/clothing/head/helmet.dm
> +	icon_state = "[icon_state][light_colors]"
call update_icon instead

2020-07-11 01:09 UTC, tralezab commented on code/modules/clothing/head/helmet.dm
> +	icon_state = "[icon_state][light_colors]"
smart!

2020-07-11 01:33 UTC, ShizCalev commented
misclick, what did you say

2020-07-11 01:36 UTC, ShizCalev requested changes

2020-07-11 01:36 UTC, ShizCalev commented on code/modules/clothing/head/helmet.dm
> +	icon_state = "[icon_state][light_colors]"
call update_icon instead

2020-07-11 01:36 UTC, ShizCalev commented on code/modules/clothing/head/helmet.dm
> +	var/lightson = magnification ? "up" : ""
just do this in the line below

2020-07-11 07:29 UTC, tralezab commented
👍

2020-07-12 09:42 UTC, merged