Adds shock immunity to rubberneck
tgstation/tgstation pull request #52162
Opened 2020-07-11 09:09 UTC by carshalash

## About The Pull Request
Essentially, I noticed from the rare time of making this drink that it doesnt actually inherit the shock immunity aspect that grey bull has, this drink is kind of a pain in the ass to make, so why not carry it over

## Why It's Good For The Game
Provides a reason to make a cocktail that nobody ordered/drank before in the past.

## Changelog
:cl:
balance: Rubberneck now includes shock immunity due to containing grey bull.
/:cl:

2020-07-16 13:50 UTC, ExcessiveUseOfCobblestone reviewed
. = ..() for both please

2020-07-20 09:25 UTC, ShizCalev requested changes

2020-07-20 09:25 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	..()
return ..()

2020-07-20 09:25 UTC, ShizCalev commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	..()
. = ..()

2020-08-03 17:58 UTC, merged