Refactors some borg inventory code and removes a bunch of unused references to borgs taking oxy/tox damage
tgstation/tgstation pull request #52265
Opened 2020-07-15 22:20 UTC by MrMelbert

## About The Pull Request

This PR refactors borg inventory code - equipping and un-equipping items to slots, the process of how slots are broken and repaired, how modules are selected, etc. In the process, this fixes the use-items-in-broken-slots tech. Sorry, borg mains.

This PR also removes a few old, now deprecated references to cyborgs taking oxygen and toxin damage. There was a few locations that called adjustToxLoss and adjustOxyLoss of cyborgs, despite the fact that the procs were overridden and did nothing. The big performance change lies in the cyborg life proc - I removed the adjustOxyLoss in the life proc, because it was calling updateHealth every life tick, wasting processing.

Let me know if I overstepped myself in any areas, and accidentally cleaned something I shouldn't have.

**If there are any situations I missed in which a cyborg can take oxygen/tox damage, please let me know, so I can remove them too or adjust the PR accordingly.**

## Why It's Good For The Game

Makes some of the code for cyborgs nicer, and improves the speed of the code.

before the refactor (~20 minutes in game with 10 cyborgs spawned):
![image](https://user-images.githubusercontent.com/51863163/87603887-cd144e00-c6bd-11ea-924c-037a923a0030.png)
after the refactor (~22 minutes in game with 10 cyborgs spawned):
![image](https://user-images.githubusercontent.com/51863163/87604062-dbfb0080-c6bd-11ea-9ec2-e5144b5e3bd2.png)

## Changelog
:cl: Melbert
fix: You can no longer use broken cyborg slots by being fast at clicking
code: Removed a bunch of deprecated cyborg code involving taking toxin and oxygen damage
refactor: Refactored part of cyborg inventory code
/:cl:

2020-07-15 22:21 UTC, optimumtact commented
Good PR

2020-07-15 23:39 UTC, ATH1909 commented
> In the process, this fixes the use-items-in-broken-slots tech. Sorry, borg mains.
Damn.

Still, I support this PR; you dun did good here, MrMelbert.

2020-07-16 02:29 UTC, bobbahbrown commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	return TRUE
would it be feasible to kill off the hardcoded inv1/2/3 or are they too baked into borg existence

so much code duplication

2020-07-16 02:51 UTC, ShizCalev commented on code/modules/mob/living/silicon/damage_procs.dm
> +	return FALSE
this isn't returning the proper value for AI mobs.

2020-07-16 02:51 UTC, ShizCalev commented on code/modules/mob/living/silicon/damage_procs.dm
> +	return FALSE
same

2020-07-16 02:52 UTC, ShizCalev requested changes

2020-07-16 02:52 UTC, ShizCalev commented on code/modules/mob/living/silicon/damage_procs.dm
> +		. = ..()
return ..()

2020-07-16 02:52 UTC, ShizCalev commented on code/modules/mob/living/silicon/damage_procs.dm
> +		. = ..()
return ..()

2020-07-16 03:07 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	var/first_free_slot = 0
var/first_free_slot = !held_items[1] ? 1 : (!held_items[2] ? 2 : (!held_items[3] ? 3 : null)

2020-07-16 03:08 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	/// The number of module slots we're checking
```
if(!module_num)
	return false
```

2020-07-16 03:09 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	playsound(loc, 'sound/machines/warning-buzzer.ogg', 50, TRUE, TRUE)
src

2020-07-16 03:11 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	to_chat(src, "<span class='userdanger'>SYSTEM ERROR: Module [module_num] OFFLINE.</span>")
```
 					audible_message("<span class='warning'>[src] sounds an alarm! \"CRITICAL ERROR: All modules OFFLINE.\"</span>")
					to_chat(src, "<span class='userdanger'>CRITICAL ERROR: All modules OFFLINE.</span>")
					playsound(loc, 'sound/machines/warning-buzzer.ogg', 75, TRUE, TRUE)
```

preserve the old functionality of these getting louder with each one that gets disabled / a message saying everything is disabled when everything is... well, disabled.

2020-07-16 03:18 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +				inv1.icon_state = "inv1"
initial(icon_state)

2020-07-16 03:18 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +				inv2.icon_state = "inv2"
initial(icon_state)

2020-07-16 03:18 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +				inv3.icon_state = "inv3"
initial(icon_state)

2020-07-16 03:19 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv1.icon_state = "inv1 +b"
"[initial(inv1.icon_state)] +b"

2020-07-16 03:19 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv2.icon_state = "inv2 +b"
"[initial(inv2.icon_state)] +b"

2020-07-16 03:19 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv3.icon_state = "inv3 +b"
"[initial(inv3.icon_state)] +b"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv1.icon_state = "inv1"
"[initial(inv1.icon_state)]"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv2.icon_state = "inv2"
"[initial(inv2.icon_state)]"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			inv3.icon_state = "inv3"
"[initial(inv3.icon_state)]"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv1.icon_state = "inv1 +a"
"[initial(inv1.icon_state)] +a"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv2.icon_state = "inv2 +a"
"[initial(inv2.icon_state)] +a"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv3.icon_state = "inv3 +a"
"[initial(inv3.icon_state)] +a"

2020-07-16 03:20 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv1.icon_state = "inv1"
"[initial(inv1.icon_state)]"

2020-07-16 03:21 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv2.icon_state = "inv2"
"[initial(inv2.icon_state)]"

2020-07-16 03:21 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
>  				inv3.icon_state = "inv3"
"[initial(inv3.icon_state)]"

2020-07-16 03:28 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	if(is_invalid_module_number(first_free_slot))
if(!first_free_slot || is_invalid_module_number(first_free_slot))

2020-07-16 05:57 UTC, ShizCalev requested changes

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			audible_message("<span class='warning'>[src] sounds an alarm! \"CRITICAL ERROR: ALL modules OFFLINE.\"</span>")
1 & 3 are reversed.

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			to_chat(src, "<span class='userdanger'>CRITICAL ERROR: ALL modules OFFLINE.</span>")
.

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			playsound(src, 'sound/machines/warning-buzzer.ogg', 75, TRUE, TRUE)
.

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			playsound(src, 'sound/machines/warning-buzzer.ogg', 50, TRUE, TRUE)
.

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			audible_message("<span class='warning'>[src] sounds an alarm! \"SYSTEM ERROR: Module [module_num] OFFLINE.\"</span>")
.

2020-07-16 05:57 UTC, ShizCalev commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			to_chat(src, "<span class='userdanger'>SYSTEM ERROR: Module [module_num] OFFLINE.</span>")
.

2020-07-16 15:35 UTC, Twaticus approved these changes

2020-07-17 05:06 UTC, zombiegums commented
> In the process, this fixes the use-items-in-broken-slots tech. Sorry, borg mains.

:'(

On a serious note, thank you for tidying things up!

2020-07-20 21:41 UTC, Rohesie commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	return equip_module_to_slot(I, first_free_slot)
```suggestion
/mob/living/silicon/robot/proc/activate_module(obj/item/item_module)
	if(QDELETED(item_module))
		CRASH("activate_module called with improper item_module")

	if(!(item_module in module.modules))
		CRASH("activate_module called with item_module not in module.modules")

	if(activated(item_module))
		to_chat(src, "<span class='warning'>That module is already activated.</span>")
		return FALSE

	if(disabled_modules & BORG_MODULE_ALL_DISABLED)
		to_chat(src, "<span class='warning'>All modules are disabled!</span>")
		return FALSE

	/// What's the first free slot for the borg?
	var/first_free_slot = !held_items[1] ? 1 : (!held_items[2] ? 2 : (!held_items[3] ? 3 : null))

	if(!first_free_slot || is_invalid_module_number(first_free_slot))
		to_chat(src, "<span class='warning'>Deactivate a module first!</span>")
		return FALSE

	return equip_module_to_slot(item_module, first_free_slot)
```

2020-07-20 21:42 UTC, Rohesie commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	return TRUE
```suggestion
/mob/living/silicon/robot/proc/equip_module_to_slot(obj/item/item_module, module_num)
	switch(module_num)
		if(1)
			item_module.screen_loc = inv1.screen_loc
		if(2)
			item_module.screen_loc = inv2.screen_loc
		if(3)
			item_module.screen_loc = inv3.screen_loc

	held_items[module_num] = item_module
	item_module.equipped(src, ITEM_SLOT_HANDS)
	item_module.mouse_opacity = initial(I.mouse_opacity)
	item_module.layer = ABOVE_HUD_LAYER
	item_module.plane = ABOVE_HUD_PLANE
	item_module.forceMove(src)

	if(istype(item_module, /obj/item/borg/sight))
		var/obj/item/borg/sight/borg_sight = item_module
		sight_mode |= borg_sight.sight_mode
		update_sight()

	observer_screen_update(item_module, TRUE)
	return TRUE
```

2020-07-20 21:45 UTC, Rohesie commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			unequip_module_from_slot(held_items[I], I)
```suggestion
	for(var/item_module in 1 to 3)
		if(!held_items[item_module])
			continue
		unequip_module_from_slot(held_items[item_module], item_module)
```

2020-07-20 21:45 UTC, Rohesie commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	if(I in held_items)
```suggestion
/mob/living/silicon/robot/proc/activated(obj/item/item_module)
	if(item_module in held_items)
```

2020-07-21 01:39 UTC, merged

2020-07-22 03:47 UTC, carshalash commented
This is INCREDIBLY buggy and makes hotkey switching as a cyborg a nightmare as well as just 100% inaccuracy on which item you're using if you're using all three slots.

2020-07-22 03:52 UTC, MrMelbert commented
@carshalash i never had any problem testing, can you share the process in which you broke it / record you breaking it?

2020-07-22 04:07 UTC, carshalash commented
Cycling is 100% busted.

![image](https://user-images.githubusercontent.com/16896032/88132861-ee2bf000-cc23-11ea-9653-146ccbdcfc1a.png)
First point, all items, nothing selected yet
![image](https://user-images.githubusercontent.com/16896032/88132936-1fa4bb80-cc24-11ea-8922-e2eefb6744a3.png)
Smack cycle button once, EVERYTHING lights up, wrench is the item that is equipped instead of the welding tool
![image](https://user-images.githubusercontent.com/16896032/88132957-321ef500-cc24-11ea-8cd2-a0382356f883.png)
Switches to the screwdriver because? Other 2 items are lit up
![image](https://user-images.githubusercontent.com/16896032/88133052-86c27000-cc24-11ea-918b-ac9d9dde1942.png)
Welder is in use now, others stay lit up.

Cycling is in reverse for, some reason and other items constantly stay lit up while cycling.

2020-07-22 04:07 UTC, bobbahbrown commented
tested code

2020-07-22 04:18 UTC, MrMelbert commented
just a bug with cycling, or anything else? the cycling should be an easy fix cause I think I know where that went wrong

2020-07-22 04:21 UTC, carshalash commented
Seems to be that from what i've found so far, it is VERY bad for cycling.

2020-07-22 04:23 UTC, MrMelbert commented
okay, i'll fix the cycling in a bit, at least it's not completely awful like preventing borgs from using modules (which is what I was worried would be a bug by the way you phrased it)