Fixes handi-capable tackling from beyond the grave
tgstation/tgstation pull request #52304
Opened 2020-07-18 02:43 UTC by Ryll-Ryll

## About The Pull Request
Fixes #52300 

I mixed up buckling and buckled due to some weird comments (which i fixed a while ago in #49749), which meant that you were only prevented from tackling if something was buckled to you, not if you were buckled to something. Since these vehicles give back your stand flag, being buckled them allowed you to tackle from the grave. This fixes that (and also tackling from chairs and such in general)

## Why It's Good For The Game
remove exploit

## Changelog
:cl: Ryll/Shaps
fix: Corpses buckled to chairs can no longer tackle
/:cl:

2020-07-18 04:42 UTC, ShizCalev requested changes

2020-07-18 04:42 UTC, ShizCalev commented on code/datums/components/tackle.dm
need an incapacitated check too.

2020-07-18 09:35 UTC, Ryll-Ryll commented on code/datums/components/tackle.dm
done

2020-07-20 08:17 UTC, ShizCalev requested changes

2020-07-20 08:17 UTC, ShizCalev commented on code/datums/components/tackle.dm
> +	if(!user.in_throw_mode || user.get_active_held_item() || user.pulling || user.buckled || HAS_TRAIT(user, TRAIT_INCAPACITATED))
user.incapacitated()

2020-07-21 03:26 UTC, Ryll-Ryll commented on code/datums/components/tackle.dm
> +	if(!user.in_throw_mode || user.get_active_held_item() || user.pulling || user.buckled || HAS_TRAIT(user, TRAIT_INCAPACITATED))
done for real

2020-07-21 06:53 UTC, ATH1909 commented
one of the better bugs we've had

2020-07-21 17:25 UTC, kriskog approved these changes

2020-07-21 17:25 UTC, merged