9x10 Holodeck and New Holodeck Simulations
tgstation/tgstation pull request #52793
Opened 2020-08-08 05:01 UTC by Kylerace

## About The Pull Request
Enlarges the holodeck areas on all stations to be 9x10 and adds two new simulations: space checkers and skate park. All previous holodeck simulations were changed to be 9x10 without adding things that would completely changing what they could do. Skate park is just a bunch of tables and skateboards, and space checkers is a chess board set up with white/black pawns in checkers starting positions. 
![skatepark](https://user-images.githubusercontent.com/15794172/89702051-aa0e4000-d8f1-11ea-8b3f-a7b24ae0edea.png)
New Skate Park Sim
![spacecheckers](https://user-images.githubusercontent.com/15794172/89702028-a4185f00-d8f1-11ea-921c-41836433c03e.png)
New Space Checkers Sim
![actualchess](https://user-images.githubusercontent.com/15794172/89702029-a5498c00-d8f1-11ea-8a3e-e465ca523c6b.png)
Not Shitty Space Chess

## Why It's Good For The Game
Was originally started because space chess is horrible and boring, so it needed to have space for a full chess board. This PR allows all sims to have about 30 extra tiles of space, and the new sims added are very reliant on said extra space. Space checkers is just as space dependent as space chess and the skate park is still somewhat cramped even with the space. The main thing this PR does is scale everything up, which allows more people to use it at once, more people can fit in the lounge, the courtroom, both thunderdomes, etc. More of the station can rely on the holodeck for competitions, chess matches against the clown (without barfing), skating matches against the captain for aa, etc. 

## Changelog
:cl:
tweak: All holodeck sims now 9x10,
tweak: All stations can accommodate the enlarged holodecks
add: added skatepark sim
add: added space checkers sim
add: emergency medical sim now has a morgue and blood bag chest
add: all chess pieces have been added to space chess
add: lounge sim now has a small bar area
tweak: thunderdome 1218 now has two more tables of plate armor + claymores
tweak: anthophillia now has almost double the bees, and twice the distance to get to the bee keeper suit, be warned
balance: removed space carp that was right next to deltastation holodeck
add: five extra queens per player on space chess, in reserve. 
/:cl:

All the rest of the new sims:

![newbasketballcourt](https://user-images.githubusercontent.com/15794172/89702030-a5498c00-d8f1-11ea-9292-c6e9da4b1747.png)
basketball
![newbeach](https://user-images.githubusercontent.com/15794172/89702031-a5498c00-d8f1-11ea-9d41-9569e468f330.png)
beach
![newBEEES](https://user-images.githubusercontent.com/15794172/89702033-a5e22280-d8f1-11ea-935c-9e2a11a8ff5a.png)
anthophillia 
![newburntest](https://user-images.githubusercontent.com/15794172/89702034-a5e22280-d8f1-11ea-852b-db4f5198bf78.png)
the burney plasma one
![newchapelcourtroom](https://user-images.githubusercontent.com/15794172/89702035-a67ab900-d8f1-11ea-9d2a-234294d7ed34.png)
chapel courtroom
![newdodgeball](https://user-images.githubusercontent.com/15794172/89702036-a67ab900-d8f1-11ea-9ece-9bc7707308e4.png)
dodgeball
![newemptycourt](https://user-images.githubusercontent.com/15794172/89702037-a67ab900-d8f1-11ea-91c0-c1a31e3dcaaf.png)
empty court
![newfetishschool](https://user-images.githubusercontent.com/15794172/89702038-a7134f80-d8f1-11ea-80fe-d84c154b8feb.png)
erp school sim
![newfuel](https://user-images.githubusercontent.com/15794172/89702039-a7134f80-d8f1-11ea-8cfa-78c5ac17e6d5.png)
fuel tanks
![newholdoutbunker](https://user-images.githubusercontent.com/15794172/89702040-a7134f80-d8f1-11ea-920b-00211a1484f2.png)
holdout bunker
![newkobayashimaru](https://user-images.githubusercontent.com/15794172/89702041-a7abe600-d8f1-11ea-9592-e00bbc9c29e9.png)
kirk rp sim
![newlounge](https://user-images.githubusercontent.com/15794172/89702042-a7abe600-d8f1-11ea-8e4c-466795f3cd5f.png)
lounge
![newmedical](https://user-images.githubusercontent.com/15794172/89702043-a8447c80-d8f1-11ea-88fd-7d5ae9414955.png)
medical sim 
![newmedievaltourney](https://user-images.githubusercontent.com/15794172/89702044-a8447c80-d8f1-11ea-8489-c95e50e48b06.png)
medieval tournament
![newpicnic](https://user-images.githubusercontent.com/15794172/89702045-a8447c80-d8f1-11ea-9475-bbb4211422c9.png)
picnic
![newsnowwhateveritis](https://user-images.githubusercontent.com/15794172/89702046-a8dd1300-d8f1-11ea-84e7-e4448b129e85.png)
snowball fight
![newtargetpractice](https://user-images.githubusercontent.com/15794172/89702047-a8dd1300-d8f1-11ea-84da-30488be4f8fc.png)
target practice
![newthunderdomesim](https://user-images.githubusercontent.com/15794172/89702048-a975a980-d8f1-11ea-9456-f4434853e356.png)
thunder dome
![newwildlifesim](https://user-images.githubusercontent.com/15794172/89702049-a975a980-d8f1-11ea-9e30-59d6882df52c.png)
wildlife sim
![newwinterwonderland](https://user-images.githubusercontent.com/15794172/89702050-aa0e4000-d8f1-11ea-8ad6-34a734c11d1e.png)
winter wonderland

New Station Holodecks:
![new meta holo](https://user-images.githubusercontent.com/15794172/89702374-9664d880-d8f5-11ea-86ec-d22ac64734eb.png)
Meta (moved maint to the right, and changed the shape of the airlock, the room below the holodeck is now bigger since it was merged with a hallway)
![new delta holo](https://user-images.githubusercontent.com/15794172/89702392-c318f000-d8f5-11ea-87e5-83f8505419e2.png)
Delta (not many changes, just bigger, and no adjacent carp)
![new icebox holo](https://user-images.githubusercontent.com/15794172/89702436-273bb400-d8f6-11ea-9f29-c22afc73db15.png)
Icebox (moved maint around a bit)
![new pubby holo](https://user-images.githubusercontent.com/15794172/89702476-7eda1f80-d8f6-11ea-858b-3489254a3170.png)
Pubby (lengthened top maint hallway to meet it, and moved bottom maint to the right)

2020-08-08 05:47 UTC, Tlaltecuhtli commented
idk man, making every other holodeck sim feel like an almost empty room in exchange of the chess sim no one uses to feel realistic?
20 holoeswords and 4 claymores might be a slipshod inkling

2020-08-08 06:03 UTC, Kylerace commented
> idk man, making every other holodeck sim feel like an almost empty room in exchange of the chess sim no one uses to feel realistic?
> 20 holoeswords and 4 claymores might be a slipshod inkling
its important to note that ALL of those disappear if anyone changes the holodeck sim, and thats assuming the safety's are off. It takes four hits with a holo esword to down someone with stamina damage, and each hit doesnt slow people down that much. holo eswords in my experience are pretty hard to use for stunning. I dont see a problem with having more holoeswords, since only one round type even has a potential use for the extra swords (assuming all antags used a holosword together, and that no one changes the sim).
However the extra claymores are pretty strong, and i should get rid of two. I assumed that all holo melee weapons only dealt stamina damage.

2020-08-08 07:13 UTC, Fikou commented
they all look more ugly empty and dumb

2020-08-08 09:06 UTC, Tharcoonvagh commented
Swap the dark clown and mime on the chess sim
Isnt the bee sim supposed to have a beekeper suit and hat?

2020-08-08 09:07 UTC, Tharcoonvagh commented
Also yeah they do look kinda empty

2020-08-08 09:12 UTC, Kylerace commented
The clown is the king and the mime is the queen, so i cant swap their positions without violating the chess starting position, also the bee sim does have a beekeeping suit, but for some reason it doesn't look like one
![beeeeee](https://user-images.githubusercontent.com/15794172/89706647-89a7ab00-d91c-11ea-9343-b0623f796cf1.png)

2020-08-08 09:36 UTC, Kylerace commented
![newerlounge](https://user-images.githubusercontent.com/15794172/89707040-b4473300-d91f-11ea-9be6-0c7a5166a768.png)
![newfiringrange](https://user-images.githubusercontent.com/15794172/89707041-b5786000-d91f-11ea-9e3f-1aedc86c3a8f.png)
![newwinterthing](https://user-images.githubusercontent.com/15794172/89707043-b7422380-d91f-11ea-8e08-c49a25849d09.png)
Here are some of the improvements im working on to make things less empty, dont really know what to do with the winter one, since its original doesnt have a whole lot of stuff to expand on, also not quite sure what to do with the chapel courtroom

2020-08-08 09:37 UTC, ATH1909 commented
Nice.

Could you add a second hoop to the bottom of the basketball court simulation, or can hoops only ever face south?

2020-08-08 10:10 UTC, Kylerace commented
Unfortunately no, there is no northwards facing hoop that I can find, there are east/west ones but since the sims are 10 tiles tall that would make the hoops off center

2020-08-08 15:27 UTC, vkalls commented
Someone really wanted to play real chess huh? 👀

2020-08-08 16:24 UTC, ArcaneMusic commented
Did you remove the maint door off of icebox holodeck?
I also can't tell, but are the rechargers still there on the kobiyashi maru? That's one of the few reasons people use that holodeck loadout.
Also, blocking a maint door by default with movables is kinda cringe tbh

2020-08-08 18:07 UTC, Kylerace commented
Whoops didnt see those canvasses, thank you. Also a recharger has been re added to kobayashi maru and icebox has a maint door again.
![newermetamaint](https://user-images.githubusercontent.com/15794172/89717027-43c40480-d967-11ea-807c-02faa1db02f9.png)
![newerkobayashi](https://user-images.githubusercontent.com/15794172/89717031-4e7e9980-d967-11ea-9040-acd747ebb6ea.png)
![newericebox](https://user-images.githubusercontent.com/15794172/89717038-67874a80-d967-11ea-9c96-cfcc942f613a.png)

2020-08-09 04:48 UTC, Tharcoonvagh commented
Wait im dumb aaa

2020-08-09 17:22 UTC, trollbreeder commented
if you make it 10x10, you can make space chess and space checkers have a whole ring around, it looks nicer and allows space for 8 more captured pieces

2020-08-09 20:49 UTC, Kylerace commented
Originally I did that, and it does look nicer when it comes to the checkers and chess sims, but many of the other sims were designed for there to be an odd number of horizontal tiles. For example, the chapel courtroom has the judge sit in the exact middle, the thunderdome 1218 sim has the crown in the exact middle, kobayashi maru has the front chair in the center, etc. If it was 10 tiles horizontally everything would have to be either to the left or right of the center, so I decided to make it 9x10.

2020-08-10 19:09 UTC, GravitronBlue commented
Mind verifying that the skateboards don't become permanant once they're 'deployed'?
Pretty concerned that their holo-quality doesn't carry over when placed.

2020-08-10 23:55 UTC, Kylerace commented
Unfortunately I think they do disappear, with both this and the invisible table bug the skate park is unusable. They'll have to be fixed before I can re add it

2020-08-14 01:55 UTC, Kylerace commented
Update: Massive thanks to uomu for https://github.com/tgstation/tgstation/pull/52924#issue-467665975 and for fixing the skateboard problem, so now the skating park sim can be re added.

2020-08-19 22:52 UTC, Kylerace commented
gameplay of the skate park sim

2020-08-21 19:47 UTC, AnturK requested changes

2020-08-23 10:18 UTC, AnturK requested changes

2020-08-23 19:58 UTC, Kylerace commented on code/modules/vehicles/scooter.dm
> +	if(!istype(Skater) || Skater.incapacitated() || !Adjacent(Skater))
```
/obj/vehicle/ridden/scooter/skateboard/MouseDrop(atom/over_object)
	. = ..()
	var/mob/living/carbon/Skater = usr
	if(!istype(Skater))
		return
	if (over_object == Skater)
		pick_up_board(Skater)

/obj/vehicle/ridden/scooter/skateboard/proc/pick_up_board(mob/living/carbon/Skater)
	if (Skater.incapacitated() || !Adjacent(Skater))
		return
	if(has_buckled_mobs())
		to_chat(Skater, "<span class='warning'>You can't lift this up when somebody's on it.</span>")
		return
	var/board = new board_item_type(get_turf(Skater))
	Skater.put_in_hands(board)
	qdel(src)
```

2020-08-27 05:58 UTC, merged