Adds Plasmamen Command and Centcom suits.
tgstation/tgstation pull request #53042
Opened 2020-08-18 19:33 UTC by GuillaumePrata

## About The Pull Request
If a server had Human Authority disabled, Plasmamen heads of staff would join with the Assistant suit, this fixes that by adding new Command Suits for each head of staff.
If Human Authority wasn't enforced on ERTs, they would spawn without internals and suits, this both give them suits and changes some code to check if the ERT is a Plasmamen and give them proper gear.
All sprites made by Horatio22, all code and possibly bugs by me...

## Why It's Good For The Game
CE Plasmamen won't get lynched by engineers because they thought it was a Assistant breaking in to steal Insuls, Plasmamen Centcom Interns won't have their rare ERT rounds ruined by burning to death...
Also moves some outfit items away from r_hand since that is were the Plasma internals spawn, which could result in lost items when the outfit was given.

## Changelog
:cl: Guillaume Prata and M. Joyce
add: Added Command outfits for Plasmamen
add: Added Centcom outfits for Plasmamen
tweak: Moved some items away from the right hand in outfits to make it more Plasmamen Friendly for future projects.
balance: rebalanced something
imageadd: Icons for Centcom and Command Plasmamen gear.
/:cl:

2020-08-18 20:21 UTC, Ryll-Ryll commented
You are the MVP, whenever I spawned a wave of interns with human only toggled off, I'd have to race to turn the plasmamen into humans ASAP upon spawning.

2020-08-18 20:57 UTC, tralezab requested changes
Okay that was pretty choco cooky, I'm actually going to open a pull request fixing spelling and grammatical errors in other plasmamen related stuff.

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/gloves/miscellaneous.dm
> +	desc = "Covers up those scandalous boney hands. Appears to be a attempt at making a Captain's glove replica"
```suggestion
	desc = "Covers up those scandalous, bony hands. Appears to be an attempt at making a replica of the captain's gloves."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A plasmaman containment helmet designed for the Head of Security, a pair of gold stripes being added to differeciate them from other members of security."
here's the part where the english got so bad I just decided to suggest redoing them entirely. THEN, I realized this is already misspelled in the other plasmamen stuff that have it, dear god, save us all

```suggestion
	desc = "A special containment helmet designed for the Head of Security. A pair of gold stripes are added to differentiate them from other members of security."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "An envirohelmet designed for chief medical officers, light grey to differeciate them from other doctors."
```suggestion
	desc = "A special containment helmet designed for the Chief Medical Officer. A light grey design is applied to differentiate them from other medical staff."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A plasmaman envirohelmet designed for the Research Director, light brown to differeciate them from other members of science."
```suggestion
	desc = "A special containment helmet designed for the Research Director. A light brown design is applied to differentiate them from other scientists."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A space-worthy helmet specially designed for chief engineer plasmamen, the top is painted white to resemble a hardhat and has the Chief's green stripes."
```suggestion
	desc = "A special containment helmet designed for the Chief Engineer. An expensive, element resistant white and green carapace design is applied to protect the plasmaman inside."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A blue plasmaman envirohelm designed for the Head of Personnel. You could mistake it for the Captain's if it wasn't for the red stripes"
```suggestion
	desc = "A special containment helmet designed for the Head of Personnel. Embarrassingly enough, it looks way too much like the captain's design save for the red stripes."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A blue plasmaman containment helmet designed for the Captain, a pair of gold stripes to show who is the king."
```suggestion
	desc = "A special containment helmet designed for the Captain. Embarrassingly enough, it looks way too much like the hop's design save for the gold stripes. I mean, come on. Gold stripes can fix anything."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A plasmaman envirohelm designed for Centcom Commanders."
```suggestion
	desc = "A special containment helmet designed for the Higher Centcom Command Staff. Not many of these exist, as Centcom does not usually employ plasmamen to higher staff positions due to their complications."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A plasmaman envirohelm designed for Centcom Officials."
```suggestion
	desc = "A special containment helmet designed for the Centcom Staff. They sure do love their green."
```

2020-08-18 20:57 UTC, tralezab commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A plasmaman envirohelm designed for Centcom Interns."
```suggestion
	desc = "A special containment helmet designed for the Centcom Staff. You know, so any coffee spills don't kill the poor sod."
```

2020-08-18 21:10 UTC, GuillaumePrata commented
It was a lot of copy pasta descriptions in my end so thanks for the suggestions @tralezab

2020-08-18 21:23 UTC, tralezab commented
👉 👉

2020-08-18 23:13 UTC, ShibaInuLord commented
exavere buff

2020-08-18 23:30 UTC, Fikou requested changes
how did you manage to do this much stuff wrong

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	name = "head of personnel envirosuit"
```suggestion
	name = "head of personnel's plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	name = "chief engineer envirosuit"
```suggestion
	name = "chief engineer's plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	name = "chief medical officer envirosuit"
```suggestion
	name = "chief medical officer's plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	name = "captain envirosuit"
```suggestion
	name = "captain's plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	desc = "It's a envirosuit worn by CentCom Officers."
```suggestion
	desc = "It's an envirosuit worn by CentCom Officers."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	name = "centcom official plasma envirosuit"
```suggestion
	name = "CentCom official plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	name = "centcom command plasma envirosuit"
```suggestion
	name = "CentCom commander plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	desc = "It's a envirosuit worn by CentCom's highest-tier Commanders."
```suggestion
	desc = "It's an envirosuit worn by CentCom's highest-tier Commanders."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	name = "centcom intern plasma envirosuit"
```suggestion
	name = "CentCom intern plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/centcom.dm
> +	desc = "It's a envirosuit worn by those interning for CentCom. The top is styled after a polo shirt for easy identification."
```suggestion
	desc = "It's an envirosuit worn by those interning for CentCom. The top is styled after a polo shirt for easy identification."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	desc = "It's a envirosuit worn by someone who works in the position of \"Head of Personnel\"."
```suggestion
	desc = "It's an envirosuit worn by someone who works in the position of \"Head of Personnel\"."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	desc = "It's a envirosuit worn by those with the experience to be \"Chief Medical Officer\"."
```suggestion
	desc = "It's an envirosuit worn by those with the experience to be \"Chief Medical Officer\"."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	desc = "It's a envirosuit worn by those with the know-how to achieve the position of \"Research Director\"."
```suggestion
	desc = "It's an envirosuit worn by those with the know-how to achieve the position of \"Research Director\"."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/under/jobs/Plasmaman/command.dm
> +	name = "chief engineer envirosuit"
```suggestion
	name = "chief engineer's plasma envirosuit"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "research director plasma envirosuit helmet"
```suggestion
	name = "research director's plasma envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "chief engineer plasma envirosuit helmet"
```suggestion
	name = "chief engineer's plasma envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "head of personnel envirosuit helmet"
```suggestion
	name = "head of personnel's envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A special containment helmet designed for the Captain. Embarrassingly enough, it looks way too much like the hop's design save for the gold stripes. I mean, come on. Gold stripes can fix any
```suggestion
	desc = "A special containment helmet designed for the Captain. Embarrassingly enough, it looks way too much like the Head of Personnel's design save for the gold stripes. I mean, come on. Gold stripes can fix anything."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "centom plasma envirosuit helmet"
```suggestion
	name = "CentCom commander plasma envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A special containment helmet designed for the Higher Centcom Command Staff. Not many of these exist, as Centcom does not usually employ plasmamen to higher staff positions due to their compl
```suggestion
	desc = "A special containment helmet designed for the Higher Central Command Staff. Not many of these exist, as CentCom does not usually employ plasmamen to higher staff positions due to their complications."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "centom official plasma envirosuit helmet"
```suggestion
	name = "CentCom official plasma envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A special containment helmet designed for the Centcom Staff. They sure do love their green."
```suggestion
	desc = "A special containment helmet designed for CentCom Staff. They sure do love their green."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	name = "centom interns plasma envirosuit helmet"
```suggestion
	name = "CentCom intern plasma envirosuit helmet"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/spacesuits/plasmamen.dm
> +	desc = "A special containment helmet designed for the Centcom Staff. You know, so any coffee spills don't kill the poor sod."
```suggestion
	desc = "A special containment helmet designed for CentCom Staff. You know, so any coffee spills don't kill the poor sod."
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Centcom Intern Plasmaman"
```suggestion
	name = "CentCom Intern Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Centcom Official Plasmaman"
```suggestion
	name = "CentCom Official Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Centcom Command Plasmaman"
```suggestion
	name = "CentCom Command Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Chief Medical Plasmaman"
```suggestion
	name = "Chief Medical Officer Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Chief Engineering Plasmaman"
```suggestion
	name = "Chief Engineer Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Head Security Plasmaman"
```suggestion
	name = "Head of Security Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/outfits/plasmaman.dm
> +	name = "Head Personnel Plasmaman"
```suggestion
	name = "Head of Personnel Plasmaman"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "research director envirogloves"
```suggestion
	name = "chief medical officer's envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "research director envirogloves"
```suggestion
	name = "research director's envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "chief engineer envirogloves"
```suggestion
	name = "chief engineer's envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "head of personnel envirogloves"
```suggestion
	name = "head of personnel's envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "black envirogloves"
```suggestion
	name = "CentCom commander envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "black envirogloves"
```suggestion
	name = "CentCom official envirogloves"
```

2020-08-18 23:30 UTC, Fikou commented on code/modules/clothing/gloves/miscellaneous.dm
> +	name = "black envirogloves"
```suggestion
	name = "CentCom intern envirogloves"
```

2020-08-19 00:05 UTC, GuillaumePrata commented
Boooye... that was a lot of missing 's, a instead of an and others, thanks a lot for your time pointing out my mistakes @Fikou

2020-08-19 08:23 UTC, pireamaineach commented on code/modules/clothing/gloves/miscellaneous.dm
> +	desc = "Covers up those scandalous boney hands. Appears to be a attempt at making a Captain's glove replica"
Actually boney isn't incorrect grammatically speaking.

2020-08-19 13:40 UTC, RaveRadbury commented
Now we just need Centcom jumpskirts

2020-08-20 13:46 UTC, lordpidey commented
66 commits?  Good god.

2020-08-20 21:50 UTC, wesoda25 commented
Why don't we just force them to be human?

2020-08-20 21:51 UTC, pireamaineach commented
We do, this is for downstream and if a moffmin disables that.

2020-08-20 22:58 UTC, Rohesie commented
@Twaticus

2020-08-21 17:43 UTC, Twaticus approved these changes

2020-08-21 19:47 UTC, merged