DMAPI 3 patch. Fix Discord mention parsing
tgstation/tgstation pull request #53312
Opened 2020-08-29 19:12 UTC by Cyberboss

On the tin

2020-08-30 03:03 UTC, bobbahbrown commented on code/modules/tgs/v3210/commands.dm
> +	var/regex/discord_id_regex = regex(@"[0-9]+")
```suggestion
	var/regex/discord_id_regex = regex(@"^[0-9]+$")
```

2020-09-03 23:54 UTC, SpaceManiac requested changes
please confirm/deny what bobbah pointed out

2020-09-04 20:00 UTC, Cyberboss commented
His is better, but I need to patchit upstream

2020-09-12 00:57 UTC, SpaceManiac commented
You can reopen this when you fix it

2020-09-12 00:57 UTC, closed without merging