I killed Metalgen for a reason, dang it. Kills infinite material duplication.
tgstation/tgstation pull request #53379
Opened 2020-09-01 09:42 UTC by Iamgoofball

…

## About The Pull Request

Removes the metalgen recipe AGAIN.

## Why It's Good For The Game

Infinite mats is not a good game design. See https://github.com/tgstation/tgstation/pull/50552 for the previous reasoning. The current reasoning is that hey, material scarcity is actually important and literal alchemy just destroys any attempts at balancing resource availability.

## Changelog
:cl:
del: Removed metalgen AGAIN.
/:cl:

2020-09-01 09:55 UTC, TemporalOroboros commented
Has anyone actually used this since it was re-merged? I haven't seen it at all.

2020-09-01 10:09 UTC, Time-Green commented
It's extremely rare for someone to actually be able to make metalgen now. If someone goes through the effort of finding the recipy and finding wittel (and the other random reagents), they should be allowed to have a round where some materials can be duplicated. It's such an endgame goal that the process of making it can span over multiple rounds. 

To my knowledge it hasn't even happened yet (correct me if I'm wrong, I can only view chemical reactions on a per-round basis on scrubby). Materials also can't actually be sold for money anymore, so it doesn't inflate the economy. It just means that someone can turn the entire station into gold. They would also not have to worry about the vault anymore, given that they bother to actually make infinite metals. In a good round the vault is filled to the brim either way.

We're talking about something super rare and difficult to get. If some madman actually does it, let them have their victory.

2020-09-01 11:34 UTC, Doosteroni commented
It’s easier to grab a mech and flatten the entire map then making metelgen

2020-09-01 13:44 UTC, moocowswag commented
And there are other (superior) ways of making infinite of any mat.

2020-09-01 15:44 UTC, ArcaneMusic commented
Metalgen was a problem several months ago when that removal was in place, between datum exports as well as being easier to produce at the time. Now however I feel like it's a sufficiently rare resource as of now, and the focus should be aimed at removing the extreme ease of collecting some materials instead (Meat, plastic, etc).

2020-09-01 15:47 UTC, ATH1909 commented on code/modules/reagents/chemistry/recipes/special.dm
> -/datum/chemical_reaction/randomized/metalgen
did you remember to remove this recipe from the paper wizard space ruin as well?

2020-09-01 17:02 UTC, TheVekter commented
Anything that will let us actively balance material costs is a good change at this point.

2020-09-01 20:15 UTC, Spepbuthewranglesgithub commented
oh boy, another PR that removes something fun and generally balanced for the sake of scarcity.


_even though in this case ore is already so common its irrelevant, and if it was made rarer absolutely nobody would be happy._

2020-09-01 23:30 UTC, optimumtact commented
>oh boy, another PR that removes something fun and generally balanced for the sake of scarcity.

He lied confidently

2020-09-02 00:55 UTC, NaturesMayhem commented
I disagree with this. Metalgen should be a last ditch effort by crew to produce more materials in the event miners have all fucked off and died and/or a megafauna has decided to make lavaland base their home this servers as a way for the crew to produce more. If we have miners and enough resources, so nobody feels the need to use the recipe then that's fine. If we have miners and enough resources, but someone feels the need to abuse this then what does it hurt? Miners that are actually doing their job produce more mats than the station ever reasonably manages to use. And if the miners all died and someone felt the need to use this, then good it means you don't have to shuttle call just cause you don't have the mats to do anything.

2020-09-02 01:02 UTC, ATH1909 commented
> I disagree with this. Metalgen should be a last ditch effort by crew to produce more materials in the event miners have all fucked off and died and/or a megafauna has decided to make lavaland base their home this servers as a way for the crew to produce more. If we have miners and enough resources, so nobody feels the need to use the recipe then that's fine. If we have miners and enough resources, but someone feels the need to abuse this then what does it hurt? Miners that are actually doing their job produce more mats than the station ever reasonably manages to use. And if the miners all died and someone felt the need to use this, then good it means you don't have to shuttle call just cause you don't have the mats to do anything.

Uh, don't you need wittel to make metalgen? And doesn't wittel come from lavaland? So unless you've got a stockpile of it beforehand and/or have a service borg or bees to dupe it with, it doesn't look like you can really do this if it's unsafe to enter lavaland.

2020-09-02 09:23 UTC, Winterous commented
> Uh, don't you need wittel to make metalgen? And doesn't wittel come from lavaland? So unless you've got a stockpile of it beforehand and/or have a service borg or bees to dupe it with, it doesn't look like you can really do this if it's unsafe to enter lavaland.

Wait, service borg can duplicate reagents?

Also it's far easier to just use xenobio to duplicate material sheets than it is to make this shit; just get the stabilised metal extract or whatever it is, put it in a backpack with a diamond, and stick it on a humanised monkey. Done, now you get a diamond ever ~30 seconds.

2020-09-02 10:47 UTC, Qustinnus commented
@ArcaneMusic who cares if people make a lot of meat it has little value (and if thats still a problem just remove its value)

if someone actually wants to make a lot of meat mat its still enough effort to take up a large portion of their time.

2020-09-02 15:01 UTC, fludd12 commented
Speaking of Xenobiology. Given desired resource scarcity, you should probably change stabilized metal(?) and industrial gold.

~~`Or just remove crossbreeding as a whole I regret making it and the way people compare it to other things to make arguments for balance which I never intended when I designed it. It didn't solve the problem of Xenobio being boring, it just rewarded you more for doing a boring thing.`~~

2020-09-02 15:39 UTC, ArcaneMusic commented
> @ArcaneMusic who cares if people make a lot of meat it has little value (and if thats still a problem just remove its value)
> 
> if someone actually wants to make a lot of meat mat its still enough effort to take up a large portion of their time.

That's diametrically opposed to the design decision of any kind of economy as far as I see it.
Economy in any sense (And this isn't my cash economy discussion mind you, this is the material ecconomy!) requires scarcity. If the overarching design decision is to keep infinitely producable materials, then goof is correct to make this PR, as lead to gold is just the same as being able to mine miasma and produce millions of credits of gas for practically no effort, forever.

But, if the design direction is that the ability to duplicate materials is bad, then the existence of something rare powerful like metalgen is balanced by the fact that there's less materials of one type in the system by the time you're done. If this does/doesn't go through at least we have a precident to work off of.

2020-09-03 01:10 UTC, SpaceManiac requested changes
Doesn't compile. This is why we disapprove of webedits

2020-09-03 07:45 UTC, Fikou commented
>remove metalgen
>gets brought back as secret recipe
>hasnt even appeared in a single round yet i think
>NO I SAID REMOVE!!!

2020-09-03 13:44 UTC, Qustinnus commented
@ArcaneMusic 

scarcity implies there is enough demand for the material that there is a lack of supply. something like meat material is not scarce as there's no real demand besides for autism projects. making things have non-existent supply for the sake of them being uncommon makes noone bother with creating them, especially when its already a PITA to create (like honestly, making meat sheets is not an instant process, and the only reward is style points)

2020-09-03 16:44 UTC, ArcaneMusic commented
The demand in the case of meat is that it can be converted. If you go to the effort to learn the metalgen recipe, you're going to want something to convert into something else. Given the option, and having the knowledge, you will go out of your way to use the cheapest material to convert into the material you want. Why would you ever choose metal/glass/sand when you can pump out slabs of synthmeat from the comfort of the chem factory? It's a very fast setup to mass-produce setup that requires very little extra work to maintain pumping out synthmeat, far far less than producing the other available infinite materials.

Where there is no _practical_ demand for meat in any other situation, metalgen is the wholesale demand for meat.

2020-09-03 17:15 UTC, TemporalOroboros commented
Didn't we specifically have a flag for preventing materials from being extracted from an object? I think it was being used in coins for some reason. Can't we just apply that to whatever metalgen acts on?

2020-09-03 21:46 UTC, TemporalOroboros commented
I might have figured out how to keep metalgen from crashing the economy.

2020-09-04 05:09 UTC, Qustinnus commented
But arcane that just sounds like an argument against metal Gen. If the problem is people mass replacing meat and plastic with metalgen.. Then why don't we not make it work on meat and plastic? They're not metal.

I also like the idea of metalgen just not creating usable materials, as that's part of the main problem too. Metalgen would work best as a visual/audio change rsther than being a way to generate usable materials

2020-09-04 05:10 UTC, Qustinnus commented
Optionally just kill off metalgen with this pr, I'm not necessarily for if but if it were that vs killing off any meat and plastic supply because someone might use metalgen on them I'd pick this pr

2020-09-04 07:20 UTC, Winterous commented
It's not like iron isn't an infinite resource, borgs can generate it, autolathes can generate it.

2020-09-05 17:36 UTC, ExcessiveUseOfCobblestone commented
It's rare enough I'm fine with it as is hence why I merged it's reintroduction.

2020-09-05 22:58 UTC, Iamgoofball commented
Manuel and Bagil players would beg to differ. Getting it is not hard once the "secret" is found for the week.

2020-09-06 07:02 UTC, Time-Green commented
> Manuel and Bagil players would beg to differ. Getting it is not hard once the "secret" is found for the week.

Reset period is about three days. If they’re consistent in getting it you can decrease the reset timer. You’re also a little late with saying it actually IS common (on manuel and bagil)

2020-09-06 21:48 UTC, optimumtact commented
@ExcessiveUseOfCobblestone then close the pr dummy

2020-09-06 21:48 UTC, closed without merging

2020-09-07 02:53 UTC, Iamgoofball commented
we talked in coding general and agreed on a removal, i forgot to repost it to the pr

2020-09-07 11:09 UTC, kassori commented
Is the chemical being removed entirely or is it just getting the ability to break things down nerfed? Being able to make golden shrubberies from the plants on the station is great, crashing the economy isnt.