[WIP] Try to fix runtime map loading runtime errors.
tgstation/tgstation pull request #53575
Opened 2020-09-09 10:47 UTC by Dennok

## About The Pull Request

Try to fix runtime map (mostly shuttle) loading runtime errors.

## Why It's Good For The Game

Runtime error is bad.

## Changelog

2020-09-09 15:05 UTC, Cyberboss commented
This feels like the wrong angle to be taking, I think the machines that are runtiming should be using LateInitialize

2020-09-09 16:46 UTC, Dennok commented
> This feels like the wrong angle to be taking, I think the machines that are runtiming should be using LateInitialize

Yes, this way don't work, or don't completely work.
But i think there is no LateInit issue since InitializeAtoms hold LateInit, and runtime errors mostly from `process_atmos()` of un inited machinery.

2020-09-09 19:58 UTC, willox commented
Is this why the air canister on the donut escape shuttle runtimes when it loads in?

2020-09-10 05:32 UTC, Dennok commented
> Is this why the air canister on the donut escape shuttle runtimes when it loads in?

Yes.

And i really think on this from wrong angle.

2020-09-10 07:33 UTC, Dennok commented
OMG, 
https://github.com/tgstation/tgstation/blob/134964a0a5173225a81f56100c4bdd4060fd395c/code/modules/atmospherics/machinery/portable/portable_atmospherics.dm#L17-L20

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/air.dm
> +/datum/controller/subsystem/air/proc/setup_template_machinery(list/atmos_machines, no_check_tick = FALSE)//Call it with CHECK_TICK on runtime cause runtime errors.
```suggestion
/datum/controller/subsystem/air/proc/setup_template_machinery(list/atmos_machines)
```

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/air.dm
> +			continue
```suggestion
```

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/air.dm
> +			continue
```suggestion
```

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/atoms.dm
> +/datum/controller/subsystem/atoms/proc/InitializeAtoms(list/atoms, no_check_tick = FALSE)//Call it with CHECK_TICK on runtime cause runtime errors.
```suggestion
/datum/controller/subsystem/atoms/proc/InitializeAtoms(list/atoms)
```

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/atoms.dm
> +					continue
```suggestion
```

2020-09-10 07:40 UTC, Dennok commented on code/controllers/subsystem/atoms.dm
> +				CHECK_TICK //don't add no_check_tick here, since removing CHECK_TICK from initializing all world, freeze world.
```suggestion
				CHECK_TICK
```

2020-09-10 07:40 UTC, Dennok commented on code/modules/atmospherics/machinery/portable/canister.dm
> +		log_world("<span class='boldannounce'>[src] un inited process_atmos()2</span>")
```suggestion
```

2020-09-10 07:40 UTC, Dennok commented on code/modules/mapping/map_template.dm
> +	SSatoms.InitializeAtoms(atoms, TRUE)// TRUE forbids CHECK_TICK, CHECK_TICK create runtime errors on runtime map loading
```suggestion
	SSatoms.InitializeAtoms(atoms)
```

2020-09-10 07:40 UTC, Dennok commented on code/modules/mapping/map_template.dm
> +	SSair.setup_template_machinery(atmos_machines, TRUE)// TRUE forbids CHECK_TICK, CHECK_TICK create runtime errors on runtime map loading
```suggestion
	SSair.setup_template_machinery(atmos_machines)
```

2020-09-10 16:39 UTC, Cyberboss submitted a review, later dismissed
Lol, wtf

2020-09-10 16:40 UTC, Cyberboss requested changes

2020-09-10 16:40 UTC, Cyberboss commented on code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
>  	..()
Remove this entirely please

2020-09-10 17:02 UTC, Dennok commented on code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
>  	..()
Done

2020-09-10 17:06 UTC, Cyberboss approved these changes

2020-09-10 17:07 UTC, merged