Shuttle hulk fix.
tgstation/tgstation pull request #53631
Opened 2020-09-11 13:18 UTC by Dennok

## About The Pull Request

Shuttle hulk fix.
Shuttles no more able move docking ports.

## Why It's Good For The Game

Bugs is bad.

## Changelog
:cl:
fix: Shuttle hulks
/:cl:

2020-09-11 16:21 UTC, Timberpoes commented
These are very small changes including uncommenting some code.

Both the issues you've got listed are already closed (supposedly some other PR fixed them).

Can you give me some finer details on what the existing issue is and what your changes have done to fix them?

Also, while few word good and many word bad, I'd like to see a bit more descriptive change log entry if that's possible? Players and coders alike use them and "Hulk" is also a genetics mutation, so there's some ambiguity in it.

2020-09-11 17:07 UTC, Dennok commented
@Timberpoes Better?

2020-09-11 18:29 UTC, Timberpoes commented
> 
> 
> @Timberpoes Better?

My hero! Thank you for your time!

2020-09-12 00:49 UTC, SpaceManiac requested changes
Thanks for attention to this issue. I wanted to see it fixed properly but wasn't inspired to do so myself.

I checked and this function already exists here:

https://github.com/tgstation/tgstation/blob/ffa7050651ff7feb4a7d355276da8c7be9c5d375/code/modules/shuttle/on_move.dm#L374-L377

I think the simplest solution for now is removing `can_move_docking_ports = 1` from the two whiteships which have it.

When a whiteship is introduced which has a stationary port inside it (for nesting shuttles), this code can be changed to also skip the new dock in addition to the old dock.

2020-09-12 05:00 UTC, Dennok commented
> Thanks for attention to this issue. I wanted to see it fixed properly but wasn't inspired to do so myself.
> 
> I checked and this function already exists here:
> 
> https://github.com/tgstation/tgstation/blob/ffa7050651ff7feb4a7d355276da8c7be9c5d375/code/modules/shuttle/on_move.dm#L374-L377
> 
> I think the simplest solution for now is removing `can_move_docking_ports = 1` from the two whiteships which have it.
> 
> When a whiteship is introduced which has a stationary port inside it (for nesting shuttles), this code can be changed to also skip the new dock in addition to the old dock.

I think, for this, better create subtype of stationary port, instead of creating bunch of checks.

2020-09-18 02:20 UTC, SpaceManiac approved these changes

2020-09-18 02:21 UTC, merged