Emergency Shuttle Toggle
tgstation/tgstation pull request #53912
Opened 2020-09-22 23:14 UTC by Gandalf2k15

## About The Pull Request

I made this way back in 2015 for hippiestation, I've decided it needs to be here because it is very useful. So I've ported and refactored it. This is also a downstream-upstream PR.

Admins now have the option to enable or disable the shuttle(located in the admin tab).
Disabling the shuttle will basically pause it where it is, regardless(unless game is over). Until the admins enable it again. It will resume exactly back to where it was and continue from there. This is great for events. You can't recall or call the shuttle while it's disabled.

Admins also now get the option when calling the shuttle to disable the recall of said shuttle unless they cancel it or select enable shuttle.

## Why It's Good For The Game

This enables admins to prevent shuttle disruption in terms of events. It's generally just a useful tool.

## Changelog
:cl:
add: Adds a new admin shuttle call option: No recall.
admin: Gives admins the option to enable or disable the shuttle.
/:cl:

2020-09-23 08:44 UTC, lordpidey requested changes

2020-09-23 08:44 UTC, lordpidey commented on code/modules/shuttle/shuttle.dm
> +		return "--:--"
Roll this into the above if statement, joining the equalities with an or.

2020-09-23 12:53 UTC, Gandalf2k15 commented
good to go

2020-09-24 09:52 UTC, Rohesie commented on code/controllers/subsystem/shuttle.dm
> +			return FALSE
```suggestion
		if(SHUTTLE_STRANDED, SHUTTLE_DISABLED)
			to_chat(user, "<span class='alert'>The emergency shuttle has been disabled by CentCom.</span>")
			return FALSE
```

2020-09-24 09:57 UTC, Rohesie commented on code/modules/admin/verbs/randomverbs.dm
> +		SSshuttle.emergency.mode = SHUTTLE_IDLE
```suggestion
	switch(confirm)
		if(null, "No")
			return
		if("Yes (No Recall)")
			SSshuttle.adminEmergencyNoRecall = TRUE
			SSshuttle.emergency.mode = SHUTTLE_IDLE
```

2020-09-24 09:59 UTC, Rohesie commented on code/modules/admin/verbs/randomverbs.dm
> +		message_admins("<span class='adminnotice'>[key_name_admin(usr)] admin-called the emergency shuttle.</span>")
```suggestion
	message_admins("<span class='adminnotice'>[key_name_admin(usr)] admin-called the emergency shuttle[confirm == "Yes (No Recall)" ? " (non-recallable)" : ""].</span>")
```

2020-09-24 10:01 UTC, Rohesie commented on code/modules/admin/verbs/randomverbs.dm
> +	if(alert(src, "You sure?", "Confirm", "Yes", "No") != "Yes") return
```suggestion
	if(alert(src, "You sure?", "Confirm", "Yes", "No") != "Yes")
		return
```
Avoid same-line control statements as per the contribution guidelines.

2020-09-24 10:03 UTC, Rohesie commented on code/modules/admin/verbs/randomverbs.dm
> +	SSshuttle.emergency.setTimer(null)
```suggestion
	SSshuttle.emergency.setTimer(0)
```
This uses num vars.

2020-09-24 10:03 UTC, Rohesie commented on code/modules/admin/verbs/randomverbs.dm
> +	if(alert(src, "You sure?", "Confirm", "Yes", "No") != "Yes") return
```suggestion
	if(alert(src, "You sure?", "Confirm", "Yes", "No") != "Yes")
		return
```

2020-09-24 10:05 UTC, Rohesie commented on code/modules/shuttle/emergency.dm
> +			SSshuttle.checkHostileEnvironment()
```suggestion
		if(SHUTTLE_STRANDED, SHUTTLE_DISABLED)
			SSshuttle.checkHostileEnvironment()

```

2020-09-24 10:07 UTC, Rohesie requested changes
Check the defines in `shuttles.dm`, such as `EMERGENCY_ESCAPED_OR_ENDGAMED` and similar. Make sure they are compatible with this change and don't break.

2020-09-25 00:56 UTC, Gandalf2k15 commented
This has been on hippeistation and a few other servers for years, there have never been any issues regarding the defines, it's designed in such a way that it stores the previous state. I can confirm this works as intended.

> Check the defines in `shuttles.dm`, such as `EMERGENCY_ESCAPED_OR_ENDGAMED` and similar. Make sure they are compatible with this change and don't break.

2020-09-25 10:40 UTC, merged