Changes organs to be inside the body
tgstation/tgstation pull request #53934
Opened 2020-09-24 16:28 UTC by nightred

## About The Pull Request

Organs were nullspaced when inserted.
This makes organs be in the mob that they are well in.

Organ manipulation surgery still works properly, organs still work properly.

## Why It's Good For The Game

This fixes several interactions with chems in the stomach that had no effect because they happened in null space.
This fixes that.

After eating gunpowder and set my self on fire.
![image](https://user-images.githubusercontent.com/6491940/94172924-c3932900-fe58-11ea-8aff-198804aa330a.png)

## Changelog
:cl:
fix: Organs are now in the mob and not some cosmic void
/:cl:

2020-09-24 17:18 UTC, TemporalOroboros commented
I'm reasonably sure some equipment/hand code uses "for item in mob" so as to not need to deal with the horror that is inventory slots. Can you make sure this doesn't break that?

2020-09-24 18:11 UTC, nightred commented
I will do a sweep of hand codes and object in mobs to see what I can find.

2020-09-26 20:55 UTC, coiax commented
I remember trying to do this in the past, (although I don't recall the specific difficulties that I ran into other than that we tried a test round, and everyone straight up died really quickly because of bugs), so good luck to you!

2020-09-30 14:59 UTC, ShizCalev requested changes
https://github.com/tgstation/tgstation/blob/cbbb6ea4484e9605647478f28c556271057dfb58/code/modules/projectiles/projectile/magic.dm#L167-L180

wabbajack/staff of change kills everybody.

2020-09-30 15:06 UTC, nightred commented
Fixing wabbajack and doing a new round of checks.
This should be test merged, this is a large change to organs.

2020-09-30 15:12 UTC, TemporalOroboros commented
This _might_ cause issues? I'm not sure whether there are any cases where an organ can wind up with the `IN_INVENTORY` item flag.

https://github.com/tgstation/tgstation/blob/d6988bdfbb2ed696de8588d2042dfd76289ecca1/code/modules/mob/inventory.dm#L330-L343

2020-09-30 15:30 UTC, nightred commented
> This _might_ cause issues? I'm not sure whether there are any cases where an organ can wind up with the `IN_INVENTORY` item flag.

I do not know of any case where the organ being in you and have that flag set, I am searching for all locations i can find that have contents interactions that would cause issues.

2020-09-30 20:03 UTC, ShizCalev requested changes
https://github.com/tgstation/tgstation/blob/cbbb6ea4484e9605647478f28c556271057dfb58/code/datums/mind.dm#L612-L613

another

2020-09-30 20:03 UTC, ShizCalev commented on code/modules/projectiles/projectile/magic.dm
>  	var/list/contents = M.contents.Copy()
can probably just be get_equipped_items too since everything gets equip_to_appropriate_slot called as well.

2020-09-30 20:24 UTC, nightred commented on code/game/machinery/gulag_teleporter.dm
> +			continue
also fixed up and it works in my testing.

2020-09-30 20:46 UTC, ShizCalev requested changes

2020-09-30 20:46 UTC, ShizCalev commented on code/modules/projectiles/projectile/magic.dm
> +	var/list/contents = M.get_equipped_items()
TRUE.

2020-09-30 20:46 UTC, ShizCalev commented on code/game/machinery/gulag_teleporter.dm
> +	var/list/equipped = mob_occupant.get_equipped_items()
TRUE

2020-09-30 20:54 UTC, nightred commented on code/game/machinery/gulag_teleporter.dm
> +	var/list/equipped = mob_occupant.get_equipped_items()
what do you mean by true?

2020-09-30 21:31 UTC, nightred commented on code/game/machinery/gulag_teleporter.dm
> +	var/list/equipped = mob_occupant.get_equipped_items()
Ok i think i got what you mean

2020-09-30 21:31 UTC, nightred commented on code/modules/projectiles/projectile/magic.dm
> +	var/list/contents = M.get_equipped_items()
same here

2020-10-23 17:50 UTC, Fikou commented
noooooooooo

2020-11-04 18:04 UTC, nightred commented
This is ready but keeps staling out

2020-11-06 01:18 UTC, ExcessiveUseOfCobblestone commented
has this been tmd

2020-11-06 01:29 UTC, nightred commented
I am putting my attention on two other prs first, then I can circle back
here. Take it up if you wish.

On Thu, Nov 5, 2020, 7:19 PM girl <notifications@github.com> wrote:

> has this been tmd
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/53934#issuecomment-722744906>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRQ6JDRYINOQWFCDHJT2MLSONFJBANCNFSM4RYQOJYQ>
> .
>

2020-11-07 11:07 UTC, cacogen commented
This is kind of exciting

2020-11-20 19:41 UTC, Cyberboss commented
Is this in a testable state (After conflicts are resolved)?

2020-11-25 04:13 UTC, closed without merging

2020-11-25 04:13 UTC, ExcessiveUseOfCobblestone commented
repr when u get back to this

2020-12-01 09:36 UTC, TemporalOroboros commented
@nightred https://github.com/tgstation/tgstation/blob/fea8d14bc6c7851f5248dd317caa740ffb419c17/code/modules/awaymissions/mission_code/Academy.dm#L240-L246

Found another one for you.