Replaces sleeping carp pierce immunity with wound resistance, few other small fixes
tgstation/tgstation pull request #53986
Opened 2020-09-26 04:36 UTC by Ryll-Ryll

## About The Pull Request
Back in #50904, wesoda read me like a textbook

> So basically this is the trigger to a pr balance war. Its too radical but will get people scared enough to accept a PR which gives us a weaker form of original carp (lemme guess you can’t aggressive grab people?). Nice job

I wasn't really thinking about the specifics of how sleeping carp should function, I just made that PR to apply pressure to get something I thought was obnoxious changed. After it was merged, I realized that leaving in the pierce immunity was actually an unintentional mistake on my part since they still couldn't use lots of medical stuff despite losing the resists, but I figured someone else would realize I botched it and fix it. Turns out no one ever did!

So this is me redeeming for my sins and finally removing the pierce immunity from sleeping carp, so they can now use medical supplies as normal. In its place, I gave sleeping carp the wound resistance trait, which reduces the wounding power of all incoming attacks by a decent amount. I figure it makes sense cause it gives the user more staying power and reduces how easy it is to knock them out of commission with a lucky hit. Please don't start doing this everywhere for all of your pet antags.

I also fix a few other things, like-
* Fixes: #53733
Looking back I'm pretty sure I got memed by this issue because afaict the only clothing that is THICKMATERIAL and doesn't cover the entire body below the neck is the bee costume which leaves the legs uncovered, which means this was a waste, but can_inject() now checks the specific targeted bodypart to see if it's covered rather than just checking their suit.

* Fixes: #53191
You can no longer readapt while you're in stasis, preventing this bug

* Fixes: #51218
Medical, chemical, and wound scanners are now properly inaccessible to the blind. Progress!

## Why It's Good For The Game

## Changelog
:cl: Ryll/Shaps
balance: Sleeping carp users are no longer immune to piercing, which means they can once again use most medical supplies, but will trip on glass and such like normal people. In return, they are now somewhat more resistant to suffering wounds.
tweak: Medical, chemical, and wound scanners are now consistent in that they are all inaccessible to the blind. Progress!
tweak: Thick material checks (like syringes and such) are now applied on a bodypart by bodypart basis, rather than just depending on your suit.
fix: As a changeling, you can no longer readapt your mutations while in fakedeath stasis, which would cause you to stay in sleepies forever
/:cl:

2020-09-26 05:50 UTC, Cyprex commented
Wound immunity I would value at maybe 8 TC at best, and only under very specific circumstances.

2020-09-26 06:06 UTC, necromanceranne commented
Thank you for fixing this.

2020-09-26 06:30 UTC, Ryll-Ryll commented
> Wound immunity I would value at maybe 8 TC at best, and only under very specific circumstances.

You still get the whole martial art thing bro

Also mind that it's not wound immunity, it's a reduction in incoming wounding power, which means... well, I'm not really sure! Edge added the trait in as a reverse of the easier wounding trait I added for kicks, but I didn't really plan for modifiers like this when I wrote the system, so I actually have no clue how much this affects taking wounds, and whether it makes you practically immune, or just more resilient. I'll do a few tests to get a rough figure I guess.

2020-09-26 10:55 UTC, Rohesie commented on code/game/objects/items/devices/scanners.dm
> +		return
This is a good change, but is it related?
Could you atomize these fixes in their own PRs?

2020-09-26 10:55 UTC, Rohesie commented on code/modules/antagonists/changeling/changeling.dm
> +		return
Same for this, it looks like a standalone fix?

2020-09-29 22:11 UTC, Ryll-Ryll commented
Yeah I'll do it tonight

2020-09-30 15:10 UTC, ShizCalev requested changes

2020-09-30 15:10 UTC, ShizCalev commented on code/game/objects/items/devices/scanners.dm
> +	if(scanner && user.is_blind())
atomize as rohesie said. also use `user.can_read()` instead.

2020-10-01 12:00 UTC, closed without merging

2020-10-01 12:16 UTC, Iamgoofball commented
?