AIs can now select portraits as their display
tgstation/tgstation pull request #53994
Opened 2020-09-26 22:37 UTC by tralezab

## About The Pull Request

A new option has been added to the AI display radial menu alongside random, "Portrait"

It opens a small menu that lets you peruse all of the portraits and select one as your display.

## Why It's Good For The Game
This can let avid artists draw exactly what they want their AI to be like, and not-so-avid artists to bring tears to my eyes.

Pictures soon!

## Changelog
:cl:
add: AIs can now select art from the gallery as their display!
/:cl:

2020-09-26 22:39 UTC, tralezab commented
Pictures will be added, if you can forgive my painting skills.

2020-09-26 22:41 UTC, Jared-Fogle commented on code/modules/asset_cache/asset_list_items.dm
> +	)
```suggestion
	assets = list()
```

2020-09-26 22:42 UTC, Jared-Fogle commented on code/modules/asset_cache/asset_list_items.dm
> +			assets["[portrait["title"]]"] = png
```suggestion
			assets[portrait["title"]] = png
```

2020-09-26 22:50 UTC, necromanceranne commented
The best ai portrait.

Catgirl butt.

2020-09-26 22:57 UTC, ATH1909 commented
InB4 people make an AI portrait that looks like an empty/inactive AI core.

2020-09-26 23:04 UTC, tralezab commented
They don't have animations so don't worry

2020-09-26 23:05 UTC, tralezab commented
well i mean at least that stops SOME of the clownery

2020-09-27 00:14 UTC, CRITAWAKETS commented
i now have an excuse to draw mr. progs everywhere

infact i already had an excuse and i should work on that now

2020-09-27 01:19 UTC, cacogen commented
Can you post a screenshot of it on the mob?

2020-09-27 01:25 UTC, tralezab commented
![image](https://user-images.githubusercontent.com/40974010/94353399-92b41f00-0025-11eb-9d57-26550d07e28b.png)
ai that kind of wishes it wasn't there

2020-09-27 01:29 UTC, optimumtact commented
why did this PR ping me reee

2020-09-27 01:31 UTC, tralezab commented
wanna like my pr?

2020-09-27 01:39 UTC, tralezab commented
Okay so the solution to the 23x23 on a 32x32 issue never being able to be centered is to introduce a new canvas called 24x25 that perfectly fits the AI. during testing, 23x23 will be available but for final merge i'm gonna swap it to 24x25

2020-09-27 02:25 UTC, Timberpoes commented
![image](https://user-images.githubusercontent.com/24975989/94354235-1810f100-0071-11eb-891c-637d6d2fc8ac.png)

2020-09-27 10:03 UTC, ATH1909 commented
Can you choose your death display as well?

If so, is it possible to change your display while dead?

2020-09-27 21:31 UTC, tralezab commented
death display is now the default

2020-09-28 04:27 UTC, Winterous commented
I love this and I want some sort of art browser console to see all the stuff that can show up in galleries as well!

2020-09-28 06:59 UTC, stylemistake commented on tgui/packages/tgui/interfaces/PortraitPicker.js
>                  {multiline`
Doesn't need the multiline string, you can just shove the text directly into the tag.

2020-09-28 13:33 UTC, Cyprex commented
"lewd" is OOC, should be something more official-sounding imo

2020-09-28 18:49 UTC, Jared-Fogle commented
Seems like a nonissue, but I think "provocative" fits better anyway.

2020-09-28 23:29 UTC, wabash1 commented
This is cool but it needs the ability to change status display to the art as well. the only way people can see your picture is admeme or that traitor that has come to card you.

2020-09-29 20:22 UTC, AnturK commented on code/modules/mob/living/silicon/ai/ai_portrait_picker.dm
> +/datum/portrait_picker/New(user)//user can either be a client or a mob due to byondcode(tm)
You're doing something wrong if that's the case.

2020-09-29 20:22 UTC, AnturK commented on code/modules/mob/living/silicon/ai/ai_portrait_picker.dm
> +			ai.cut_overlays() //so people can't keep repeatedly select portraits to add stacking overlays
Use update overlays to pass back single one if it's set instead ? This applies to most cut_overlays() added in this pr.

2020-09-29 20:22 UTC, AnturK commented on code/modules/asset_cache/asset_list_items.dm
> +	for(var/p in SSpersistence.paintings[tab])
I'm not sure loading and sending all portraits at once is a good idea.

2020-09-29 22:42 UTC, Timberpoes requested changes
![image](https://user-images.githubusercontent.com/24975989/94623982-63174800-02ad-11eb-8013-f0d0412bd6dd.png)

Make sure you run the tgui linter before your final commit and fix everything that pops up. Ideally you should run it before you push any commits, too.

2020-09-30 14:37 UTC, Twaticus approved these changes

2020-09-30 15:19 UTC, wabash1 commented
Is the private tab working? It crashed tgui when I last used it.

On Wed, Sep 30, 2020, 10:37 AM Twaticus <notifications@github.com> wrote:

> *@Twaticus* approved this pull request.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/53994#pullrequestreview-499502353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3ZUQNP6P3EEA2B7NLPOLLSIM7DLANCNFSM4R3FHQKQ>
> .
>

2020-10-06 21:17 UTC, tralezab commented
@wabash1 yeah, just that now it doesn't show the tab if there's nothing in it.

2020-10-07 05:29 UTC, stylemistake commented on tgui/packages/tgui/interfaces/PortraitPicker.js
> +              <Tabs fluid={1}>
```suggestion
              <Tabs fluid textAlign="center">
```

2020-11-02 21:08 UTC, tralezab commented
i hate how basically ready this is

2020-11-03 00:23 UTC, stylemistake commented
sigh, do i really need to rebuild this myself?

2020-11-03 00:34 UTC, tralezab commented
no i'll do it for you, but we can pretty much merge this the moment i do. people need to make more 24x24 paintings in game

2020-11-03 03:24 UTC, Winterous commented
People would probably make more art if there was better reward for doing so; it's just a rare chance of seeing it in later rounds, no other way of seeing it ever again.

2020-11-03 13:42 UTC, wabash1 commented
@winterous I would think to encourage more art there needs to be a search
function in this for portraits, and then later someone could add the
ability for curators to print paintings for a price and that same search
function would be used again. Also a rule against spamming duplicates would
help and a general gallery people can view on web.

On Mon, Nov 2, 2020, 10:25 PM Winterous <notifications@github.com> wrote:

> People would probably make more art if there was better reward for doing
> so; it's just a rare chance of seeing it in later rounds, no other way of
> seeing it ever again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/53994#issuecomment-720884053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3ZUQNAPPPKADOINQPRMEDSN5ZY3ANCNFSM4R3FHQKQ>
> .
>

2020-11-11 08:26 UTC, stylemistake commented
rip, i should've rebuilt it myself

2020-11-20 03:37 UTC, merged