MultiZ camera console actions
tgstation/tgstation pull request #54043
Opened 2020-09-28 16:49 UTC by nightred

## About The Pull Request

This adds an action button to camera consoles to move up or down a floor.

## Why It's Good For The Game

Better camera console controls are great for multiz setups.

## Changelog
:cl:
add: Camera consoles now have move up down action buttons.
/:cl:

2020-09-30 11:53 UTC, Timberpoes requested changes

2020-09-30 13:04 UTC, nightred commented on code/game/machinery/computer/camera_advanced.dm
> +	var/datum/action/innate/camera_multiz_down/move_down_action = new
I blanked on that, it has been done.

2020-09-30 14:25 UTC, Twaticus approved these changes

2020-10-01 01:19 UTC, Timberpoes approved these changes

2020-10-01 01:22 UTC, merged