Constructed mining shuttle
tgstation/tgstation pull request #54105
Opened 2020-09-30 17:49 UTC by Dennok

## About The Pull Request

Add shuttlecapsule that can spawn empty mining shuttle shell.

## Why It's Good For The Game

More things to engineers to do.
Now, when your mining shuttle harassed by ashdrake or bubelgum, you can order new mining shuttle.

## Changelog
:cl:
add: Mining shuttlecapsule.  Now, when your mining shuttle harassed by ashdrake or bubelgum, you can order new mining shuttle.
/:cl:

2020-09-30 17:55 UTC, Fikou commented
but you cant order a new mining shuttle because you cant get that capsule anywhere
also wont it cause immediate atmos changes from lavaland turfs and airless plating?

2020-09-30 17:57 UTC, Ghilker commented on code/modules/mining/constructed_shuttles.dm
> +			return*/
why all this section is commented out?

2020-09-30 17:58 UTC, Ghilker commented on code/modules/mining/constructed_shuttles.dm
> +		//var/turf/T = deploy_location
another commented code

2020-09-30 18:00 UTC, Dennok commented
> but you cant order a new mining shuttle because you cant get that capsule anywhere
> also wont it cause immediate atmos changes from lavaland turfs and airless plating?

Uhh i lost cargo ordering.
Airless plating airless only on initial place.

2020-10-09 19:55 UTC, Dennok commented
Uhh, Sorry for some unintended merge problems.

2020-10-12 00:27 UTC, Timberpoes requested changes

2020-10-12 00:27 UTC, Timberpoes commented on _maps/shuttles/construction_mining.dmm
> +	shuttlePortId = "construction_mining_custom"
I'm not allowing player-built shuttles with custom docking locations. This `construction_mining_custom` looks suspiciously like a player-defined docking location.

You're advertising this as a buyable spare mining shuttle, so it should be limited to all the same docking ports as the existing mining shuttle.

If this means you need to add a secondary docking areas to allow this to function properly, then that's fine.

Also this should not be a var edit hidden in a mapping file.

2020-10-12 00:27 UTC, Timberpoes commented on _maps/shuttles/construction_mining.dmm
> +	},
I'm not allowing player-built shuttles with custom docking locations. This `construction_mining_custom` looks suspiciously like a player-defined docking location.

You're advertising this as a buyable spare mining shuttle, so it should be limited to all the same docking ports as the existing mining shuttle.

If this means you need to add a secondary docking areas to allow this to function properly, then that's fine.

Also this should not be a var edit hidden in a mapping file.

2020-10-26 00:53 UTC, closed without merging