Fixes being able to bypass locks by breaking the container with lava, guns, or brute force.
tgstation/tgstation pull request #54128
Opened 2020-10-01 11:25 UTC by Iamgoofball

This is an extremely old bug I'm surprised nobody fixed.
![tumblr_ot46p81g3s1urjvsco1_500](https://user-images.githubusercontent.com/4081722/94803452-29723a00-039e-11eb-9ac6-d4c1d976a64f.png)

## About The Pull Request

See title.

## Why It's Good For The Game
Fixes #23473 

## Changelog
:cl:
fix: Fixes being able to bypass crate locks with brute force, lava, or guns.
/:cl:

2020-10-01 11:37 UTC, necromanceranne commented
So uh you can qdel anything in a broken container?

This seems really easy to abuse.

2020-10-01 11:39 UTC, bobbahbrown commented
See #20867 and related PRs to understand that what you are 'fixing' is intended content. This is not a fix. At best this is content removal.

![image](https://user-images.githubusercontent.com/10467687/94804596-7287b580-03c1-11eb-91c7-ca2ee3bac95c.png)

2020-10-01 11:49 UTC, Iamgoofball commented
Issues resolved, crates/lockers now just pass damage through to their contained objects.

2020-10-01 12:49 UTC, brotherbeyondd commented
iamgoofball more like iamded

2020-10-01 13:06 UTC, Iatots commented
All the meta items are fireproof anyways.

2020-10-01 15:21 UTC, ATH1909 commented
IMO, if the aim is trying to stop the practice of using lava to break open crates, this PR should be making lava specifically deal damage to stuff inside of crates, not ANY source of damage.

2020-10-01 15:23 UTC, ATH1909 commented
Also....
![Uploading image.png…]()

2020-10-01 15:57 UTC, nightred commented
I would argue that brute damage to the locker should not damage the contents, but i agree with lava based damage passed in.

2020-10-01 15:59 UTC, Tlaltecuhtli commented
making this code add the contents of the crate fixes the issue
https://github.com/tgstation/tgstation/blob/de288cb657b163629b89bf58b011af85ef57fa0b/code/game/turfs/open/lava.dm#L128

2020-10-01 19:15 UTC, Jared-Fogle requested changes
Don't apply this to all damage.

2020-10-03 04:20 UTC, msgerbs commented
"Bug"

2020-10-03 18:17 UTC, Jared-Fogle commented
Superceded by #54143.

2020-10-03 18:17 UTC, closed without merging