Hotspots fix
tgstation/tgstation pull request #54213
Opened 2020-10-06 13:20 UTC by Ghilker

## About The Pull Request
affected.react() allows only fire to react inside the hotspot. Previously fires would make gases react twice, this is good for fires so that they have a normal behaviour, but for other reactions like fusion is a dreadful experience. This was leading to having weird behaviours in some reactions and open air fusion crashing the server if done in a big chamber (it became a radball party that killed the atmos system and crashed the servers).

Credit to @park66665 for the idea in [this PR](https://github.com/BeeStation/BeeStation-Hornet/pull/2649) and on discord

## Why It's Good For The Game
less bugs and less server ending glitches

## Changelog
:cl:
fix: fix open air fusion crashing the server if on fire
/:cl:

2020-10-06 14:33 UTC, park66665 commented
Noice

And... I am going to port this PR to Bee (or AU?) when this get merged instead of fixing the original PR because that seems to leave the most intuitive and straightforward git history and honestly this PR simply is better lmao

2020-10-07 06:21 UTC, LemonInTheDark commented
The behavior is a bit odd, but do you have evidence of it actually causing these things? I don't understand why this would nuke fusion like you describe, especially with how rare it is for it to happen

2020-10-07 09:14 UTC, park66665 commented
![fusiondemo](https://user-images.githubusercontent.com/8010007/95310221-1cd27200-08c7-11eb-83b1-ea3543c2a953.png)
_Fig 1. A demonstrative graph about the problems of fusion as of now; red graph follows left vertical axis; blue graph follows right vertical axis._

![Screenshot 2020-10-07 175721 - Copy](https://user-images.githubusercontent.com/8010007/95310499-7044c000-08c7-11eb-95a2-b7890813317e.png)
_Fig 2. How this bug looks like at log._

![Screenshot 2020-10-07 180727](https://user-images.githubusercontent.com/8010007/95310980-feb94180-08c7-11eb-8b86-6e23a937f4b7.png)
_Fig 3. Changes in moles of carbon dioxide that can't be explained solely by fusion happening on a single and undivided gas mixture._

2020-10-07 22:11 UTC, ShizCalev requested changes

2020-10-07 22:11 UTC, ShizCalev commented on code/modules/atmospherics/environmental/LINDA_fire.dm
> +			affected.react(src, TRUE, typecacheof(list(/datum/gas_reaction/tritfire, /datum/gas_reaction/plasmafire, /datum/gas_reaction/h2fire), only_root_path = TRUE))
make this a global list instead of rebuilding it for every `Initialize()` and tick of `process()`

2020-10-08 21:34 UTC, LemonInTheDark commented
Before we add more cost to react() I'd like evidence of this issue causing what's described, and an investigation of if the react() inside fire code helps anything terribly.

2020-10-09 05:58 UTC, park66665 commented
### The Write-up I've Been Putting Off

#### A Closer Look at The Graphs

Let's have a closer look at the graphs, for the graphs are the start of it.

![Screenshot 2020-10-09 121404](https://user-images.githubusercontent.com/8010007/95538338-f4fb1f80-0a28-11eb-90a9-592b124ce95f.png)
_Fig 1. Concatenated and cut version of the graphs I posted earlier._

Graphs like this kept coming out while I was debugging fusion, and I don't want any of the graphs to look like this. That is because these graphs shows that:

1. Thermal energy decreased tenfold _somehow_ as a result (upper graph, red);
2. It seems that, while doing fusion, there are alternating series of huge exogenous loss and gain in thermal energy -- and the size of the gains and the losses are *far* beyond the fusion should be making:fusion makes up to ±3e11 whilst the changes shown are making 1e13 changed (upper graph, blue);
3. It seems that, something is subtracting huge amounts of carbon dioxide after one fusion, and fusion happens with a mix that has much lower gas in it, and then the subtracted amount seems to be re-add and fusion runs on it again (lower graph)

And all of these shenanigans really shouldn't happen on a single tile open turf fusion. What is happening?

#### Fusion Runs Twice

It turns out, when said shenanigans happen, the fusion runs twice a tick, and that is also unacceptable since I was running a single tile open turf fusion -- only one fusion per tick is desired.

![Screenshot 2020-10-09 122636](https://user-images.githubusercontent.com/8010007/95540070-fcbbc380-0a2a-11eb-8f05-21dc7fd891f6.png)
_Fig 2. A part of the logging of every fusion reaction that took place. Because fusion is a laggy mess, it barely runs two times per millisecond._

And, more interestingly, *every gas* seems to be subtracted and then re-added -- once per tick but fusion isn't always happening once per tick.

![Screenshot 2020-10-09 124131](https://user-images.githubusercontent.com/8010007/95540943-0c3c0c00-0a2d-11eb-90a2-fa94bc362cb0.png)
_Fig 3. Exogenous changes in carbon dioxide(red), plasma(green), tritium(purple), total moles of gases(blue). Notice that changes in total moles of gases are larger than other three combined; it means that gases not tracked in this visualization are also affected by this phenomenon._

So the logical conclusion of all these evidences point to one thing: something lurking in the atmos code is subtracting a part of the turf air, calls react() on it, and re-adds the gas, all while causing severe disruptions to fusion -- especially single tile open turf fusion.

#### A Proc of Interest

And we know a proc that does a part of it: the subtraction part is very likely to be remove_part proc -- it removes a part(as a ratio) of a gas mixture and returns the removed gas, thereby making the re-adding convenient -- but something has to call react() after that. It turns out, the culprit is very likely to be 7-year-old code that has been a part of LINDA.

https://github.com/tgstation/tgstation/blob/9ba5751bb9221e80be74840fe8d4360734349a4a/code/modules/atmospherics/environmental/LINDA_fire.dm#L85-L95

Obviously this doesn't happen every time. LINDA is configured to bypass this double react() in case of fires large enough, but, oxygen isn't always in ample supply at fusion, therefore, this is bound to happen from time to time, and disrupt the fusion _greatly_ while doing reactions other than fires.

So let me build up a diagram of it. If the logic doesn't build up, well, we need another suspect after all.

![Screenshot 2020-10-09 131228](https://user-images.githubusercontent.com/8010007/95542572-1f50db00-0a31-11eb-965f-079fd3e6bfa9.png)
_Fig 4. Making sense of the dancing graphs. Please note that exogenous changes in total moles are polluted a little by reactions other than fusion._
![Fusion and LINDA Fixed Again](https://user-images.githubusercontent.com/8010007/95548218-94c3a800-0a3f-11eb-8441-756804c58219.png)
_Fig 5. How and why all these things happen, abbreviated. Please note that: 1) graph is based on logs produced by every fusion, no matter where it happened, 2) nearly every part of it has a chance of not happening at all, and 3) the case of preexisting hotspot is skipped, for it is mostly the same and I don't have enough time._

#### What's The Matter?

Well, to be honest, single tile open turf fusion suddenly gaining or losing illogical amounts of thermal energy was the _only_ reason why I investigated this, and I am not even sure that this illogical thermal energy madness is *that* drastic in /tg/station 13 code -- I debug fusion at Austation Code, which is around 99.9% same as Beestation code, but they are not tgstation code damnit! I mean, I still can't quite understand _precisely why_ this phenomenon causes serious disruptions in thermal energy calculation -- the only clue there is that fusion is _really_ sensitive to initial gas mixture, unlike other reactions that will run happily again even if the gas mixture is only 25% of what it was; the working hypothesis is that it _has tendency_ to consume energy since creation of plasma is costlier than the consumption of it, and the supply of plasma that can be used to counteract the declining energy can't be overclocked. (And all of these don't matter since fusion creates exponential increase in temperature ex nihilo: see BeeStation/BeeStation-Hornet#2614)

However the reason why Ghilker decided to make fix happen at tg seems to be a little different. Whilst the author indeed wants to reduce the brokenness of fusion, but another reasoning behind it is that hotspot react proc running only fire reactions actually reduced the lag -- gas_reactions *are* costly -- and made fusion less laggy in general: fusion *is* one of the most costly reaction in terms of time, taking whopping _0.3 ms or worse_, so making sure that fusion happens once per tick per gas mixture is a great way to reduce fusion lag.

And think of the rad balls created by two fusions per tick per tile. Oh boy, does rad ball clog too often.

![Radball Clogging](https://user-images.githubusercontent.com/8010007/95545815-e406da00-0a39-11eb-8f8b-e68996d8f38a.png)
_Fig 6. A severe case of rad ball clogging on Austation code. Rad balls clogging mid-air might not happen in case of tg, but Ghilker provided me with a picture of rad balls clogging in tg. Whilst we haven't run a rigorous statistical analysis on it, the PR seems to reduce the amount of clogged rad balls in general._

And beyond all these practical problems, I think that reactions other than fire _shouldn't_ be run by a 7-year-old code that originally intended to grow the size of fire. I should've tried to preemptively stop that before sinking hours after hours investigating hotspot and fusion interactions.

However, LINDA is not the problem of it, nor the fusion that is _very_ sensitive to the amount of plasma and carbon dioxide. I bet that SS13 atmos as a whole is the problem, for it is likely that there was some oversight in letting hotspot run every reaction.

2020-10-09 23:02 UTC, LemonInTheDark commented
Can we achieve this fix without bogging down react() any further?

2020-10-10 03:19 UTC, park66665 commented
I have thought about two directions at achieving this fix without touching react() 

1. Making hotspot react() _strictly_ an intermediate phase between ignited fire and full tile fire, by making full tile fire block hotspot react(); or making hotspot react() have a upper limit on temperature to prevent two fusions per tile per tick etc etc.
2. Having a separate proc for hotspot react() which only cares about fire reactions (and possibly replace other react() calls too?)

Both achieves the same results in regard to fusion but there are shortcomings nonetheless:

1. Reactions other than fire and fusion will still might be called at hotspot, and fire might become slower since the resulting full tile fire might still need help: full tile plasma fire that barely meets minimal fire temperature will burn meager amount of plasma, after all. It might be better to use a stronger bypass decision or hotspot volume calculation that incorporates temperature... or a minimal number that is not 0 for plasmafire's temperature_scale...?
2. This is a better solution for optimization and achieving exactly the same fix but it feels like a *horribly* bad code practice.

2020-10-10 07:41 UTC, LemonInTheDark commented
Are we sure that the call in react is needed? or is this down to hotspots encouraging fires. Could we change the logic/decay rate to better support it? and is the fix worth the cost it would require?

2020-10-10 08:25 UTC, park66665 commented
Necessity of hotspot react really boils down to temperature; it serves the track between ignited hotspot fires to full tile fire (tile air temp > fire threshold) because it lets fires grow without concerning about tile air temp by letting fire reactions run with hotspot temperature (probably around 700K~1000K). For example, igniter used at room temperature won't cause real fires without hotspot react:

![Screenshot 2020-10-09 175747](https://user-images.githubusercontent.com/8010007/95650147-9adb8680-0b1c-11eb-9f6f-60f23f62b9d7.png)
_~~Such is the power of having a personal server~~ The "fires" didn't spread, so our brave firetester could survive_

But because the necessity of hotspot react depends on temperature, we probably can check whether the tile is past fusion temperature (or some arbitrarily okay temperature, like 1000K) before the hotspot react code in order to stop hotspot react from messing with fusion without any ill effect on small fires.

2020-10-12 09:20 UTC, park66665 commented
So...... in a nutshell, we have a multitude of ways to fix it:

#### Fix and Forget

https://github.com/tgstation/tgstation/blob/f53d65ee3d0269331043ade93fe3e2fd50f4111b/code/modules/atmospherics/environmental/LINDA_fire.dm#L83

Add `|| FUSION_TEMPERATURE_THRESHOLD < location.air.temperature` to the above line.

This will prevent hotspots from calling react() at fusion temperature range. At this range, hotspot is absolutely unneeded in terms of temperature since not having enough consumed fuel -- the triggering cause of this fusion and hotspot problem -- is mostly just a problem of gas moles. And, again, hotspot react() exists because of temperature. This solution _will_ be the easiest and most neglect-able of them all. It'll do its job, and it isn't some sort of hard-to-comprehend dark magic.

#### Fix and Forget but Bolder

Do the same as above, except using a lower temperature instead of FUSION_TEMPERATURE_THRESHOLD -- i.e. 1000K.

It might have minimal to zero effect on growing fires since full tile fire raging with 1000K might not need the help of hotspot, or be bypassing the hotspot react for the most of the time in the first place. This risk *might* be acceptable if you think it'll reduce a tiny tiny more lag than the FUSION_TEMPERATURE_THRESHOLD solution.

#### The Right Way(tm)

This is mostly what this PR tries to do; adding whitelist (or blacklist) infrastructure, and/or implementing a way to further control the reactions list building.

In my opinion, it is elegant, straightforward, and technical-debt-less, and it can be utilized to further constrain the actions of (and thusly the negative effects on performance by) other react() calls that are, or will be scattered throughout the codebase, if the needs arise. The only problem here is that it will might increase the overhead and hence the lag in contrast to other solutions which doesn't add any overhead to the react proc.

#### Hotspot react()s Done Dirty and Dirty Quick

Add a proc designed for hotspot react() which only thinks about fires -- and hence faster than the original react() -- which is mostly a copy of original react() proc except the reactions list building. Or go further and _inline_ that thing. Combining this with 'Fix and Forget but Bolder' solution will probably result in the fastest DM code -- mostly because the amount of reactions this solution is going to cull will be the greatest. Again, this is *horrible* code-wise and technical-debt-wise, but, hey, the servers' CPUs will think otherwise.

#### Postscript

All of these matters will mostly be rendered moot if we port C++ atmos and reaction system or if you manage to rework this part of code further.

2020-10-20 23:04 UTC, LemonInTheDark commented
At this point I'm favoring fix and forget, I don't trust typecaches to be performant enough, if it was profiled as close to the same in say a fire I'd be less worried, I know ghil is working on moving fusion to a contained machine, that'd also resolve this issue.

2020-10-28 00:53 UTC, closed without merging