May i borrow some sugar? Nerfs free sugar(All aboard the nerf train).
tgstation/tgstation pull request #54304
Opened 2020-10-11 00:02 UTC by Krysonism

## About The Pull Request
This PR removes sugar from the synthesizer and dispenser. In addtion the ability of the soda dispenser to dispense pure sugar is locked behind the emag effect.

To compensate you will be able to buy sacks of sugar from the booze-o-mat for 100 credits each.

## Why It's Good For The Game
Infinite free sugar from these dispensers allows player to opt out of the hunger mechanic and makes sugar an extremely low value chemical. This negates any reason to grow sugar yielding plants such as sugarcane.

For small or average batch chemistry you can buy sugar, or find and grind various sugary snacks, but for big plumbing setups you might need to grow some sugarcane or emag a soda dispenser.

Sugarcane has a very high yield of sugar(25%) and decent stats, so this should not be too much of an impediment to plumbing setups since the grinding module does the annoying part for you.

## Changelog
:cl:
add: The booze-o-mat now sells sacks of sugar.
del: The chemical dispenser no longer dispenses sugar.
del: The chemical synthesizer no longer synthesizes sugar.
del: The soda dispenser no longer dispenses sugar unless emagged.
/:cl:

2020-10-11 00:03 UTC, gryffinp commented
I mean, you're right, but I'm upset that this is happening anyway.

2020-10-11 00:12 UTC, Jared-Fogle commented
A shortlist of chemicals that are now impossible to make alone:
- Helbital
- Cryptobiolin
- Mannitol
- Neurine
- Saline glucose<sup>1</sup>
- Ephedrine<sup>1</sup>
- Synaptizine<sup>1 2</sup>
- Spaceacilin<sup>1</sup>
- Miner's salve
- Psicodine
- Meth
- Space drugs<sup>1</sup>
- Smoke
- Carpet
- Impedrezene
- Pax<sup>1</sup>
- Anacea<sup>1</sup>

<sup>1</sup> - Cure for viruses
<sup>2</sup> - Important for virology

2020-10-11 00:15 UTC, challade commented
Downvoted. This is completely ignorant of the nutrition problem and an insult to my chef role. How dare you make this blatant bastard child of a pull. How will I sustain my social credit when there are dirtbags walking around my nutritionary objectives. How fucking dare you. 

I demand you remove sugar from booze-o-mat as well. It's simply not enough that people can buy sugar now. What's next, omnizine in cigarettes? We need more balance, you've only made getting sugar like... 2% harder. It's not enough. Remove sugar from anything non sugarcane and anything not made from me this instant. As we speak, there are five people (two moths, a a bartender and the chemists) who are barred from going to the kitchen thanks to their broken mechanics that enforce the current meta.

2020-10-11 00:15 UTC, nianjiilical commented
just ctrl+fing sugar on the wiki, this nerfs the availability of helbital, mannitol, saline-glucose, ephedrine, synaptizine, space drugs, smoke, life, cryptobolin, impedrezine, laughter and sucrose agar (viro), and by extension neurine, psicodine, meth, lipolicide, virus rations, barber's aid, carpet, colorful reagent, quantum hair dye, fentanyl, rezadone, spaceacillin, anacea and more

if hunger exploits is a problem please for the love of god just replace the sugar in the chem dispensers with "synthsugar" or something with no nutritional value

2020-10-11 00:20 UTC, Krysonism commented
> 
> 
> A shortlist of chemicals that are now impossible to make alone (or the booze o mat, whatever):
> 
>     * Helbital
> 
>     * Cryptobiolin
> 
>     * Mannitol
> 
>     * Neurine
> 
>     * Saline glucose1
> 
>     * Ephedrine1
> 
>     * Synaptizine1 2
> 
>     * Spaceacilin1
> 
>     * Miner's salve
> 
>     * Psicodine
> 
>     * Meth
> 
>     * Space drugs1
> 
>     * Smoke
> 
>     * Carpet
> 
>     * Impedrezene
> 
>     * Pax1
> 
>     * Anacea1
> 
> 
> 1 - Cure for viruses
> 2 - Important for virology

How many those you need in large amount and contain significant  amounts of sugar?

Many of those you can make in a sufficient quantity with by just grinding roundstart donuts and a couple of twinkies. Or a single 100 credit sack from bar.

2020-10-11 00:25 UTC, Jared-Fogle commented
Saline glucose is regularly pretty damn important. If you're going to fuck with those chemicals, then you should also re-arrange their resistance tiers, consider modafinil is now easier to make than ephedrine or pax.

2020-10-11 00:30 UTC, Mickyan commented
I've meant to do this for a while but only for the soda dispenser, the change to the chem dispenser is going to be contentious and I can't say I've ever seen people lining up at chemistry to order sugar, but the bar is typically a short distance from the kitchen and easily accessible by anyone

2020-10-11 00:32 UTC, Krysonism commented
> 
> 
> Saline glucose is regularly pretty damn important. If you're going to fuck with those chemicals, then you should also re-arrange their resistance tiers, consider modafinil is now easier to make than ephedrine or pax.

Saline-glucose is available in the medical vendor in excess of what you regularly need. There is also the 3000u saline tank from cargo, it would be nice if it saw more use actually.

2020-10-11 00:44 UTC, challade commented
> 
> 
>A shortlist of chemicals that are now impossible to make alone (or the booze o mat, whatever):

> I know it is going to be very contentious, but i believe adding a price, either in time or credits, to these reagents is a good thing. Maybe that meth would feel a little cooler and that mannitol a bit more precious if you couldn't crap out 1000s of units with no real cost.

Plasma is in the same state. Vanilla plasma (not the stable version) is useful for chems too. Sugar is too widespread. This is only a time nerf anyways since eventually botany is gonna be flooded with requests for sugar and eventually throw out gaia trays with sugar, leading to infinite sugar anyways. 

This was an inevitable nerf.

2020-10-11 00:46 UTC, MrMelbert commented
does this literally just kill brain tumor players? no way to get make mannitol easy?

2020-10-11 00:49 UTC, challade commented
> 
> 
> does this literally just kill brain tumor players? no way to get make mannitol easy?

No, this just moves the responsibility to the chef. A certified brain surgeon. Like all members of the station are.

2020-10-11 00:55 UTC, wesoda25 commented
Gonna keep it real with you chief, no one cares about kitchen balance or whatever

2020-10-11 01:10 UTC, ATH1909 commented
Kitchen balance should be achieved by adding benefits to consuming food items of certain categories, instead of just boosting mood and your nutrition level to avoid penalties.

2020-10-11 01:22 UTC, CRITAWAKETS commented
wait so you put more effort into just removing sugar rather than just fixing the problem easily by getting rid of sugar's nutrition gain or making it so that you puke if you injest too much sugar

this feels like a troll PR

2020-10-11 01:27 UTC, challade commented
> 
> 
> Gonna keep it real with you chief, no one cares about kitchen balance or whatever

If nobody cared, why are there more kitchen buffs on their way by nerfing alternatives? Checkmate Improve-not-Remove drone.

2020-10-11 01:57 UTC, optimumtact commented
![githubmods](https://user-images.githubusercontent.com/2544323/95668551-0fbcc800-0bd2-11eb-985d-1db9c136975e.png)

2020-10-11 01:58 UTC, IndieanaJones commented
Massive nerf to Lifebringers, I'm not buying it.

2020-10-11 02:06 UTC, cacogen commented
And we'll never know what he did wrong

2020-10-11 03:32 UTC, carshalash commented
You could just, nerf the nutriment values of sugar and caramel instead of doing whatever the fuck this is.

2020-10-11 03:56 UTC, antropod commented
This PR makes more problems than it solves.

Instead of removing things from the game, invent new interesting mechanic that make sugar more dangerous to eat. Diabetes. Heart attack. Anything else. Just removing sugar breaks too many things.
Changing nutritional values does not solve the problem, I can always make synthmeat as chemist. Or caramel.

2020-10-11 05:33 UTC, Yenwodyah commented
If this is merged, all those terrible, hunger-ignoring chemists will cry for half a second and then go back to making 5000 slabs of synthmeat

2020-10-11 05:38 UTC, antropod commented
Why do you need a monkey, when you can use unstable mutagen

2020-10-11 07:33 UTC, Qustinnus commented
just nerf the nutrition sugar gives by a factor of 10 - 15, its way too good anyways for what is essentially an unhealthy food.

2020-10-11 07:42 UTC, Timberpoes requested changes
Sugar pills are food. By the same logic, literal food lets you opt out of the hunger mechanic when eaten, too. Botany with 100 potency watermelons let you opt out of the hunger mechanic in one bite.

I see this as a non solution to a non problem.

> I think making these chems slightly harder/more expensive to make would be interesting.

Can you explain in more detail why you think it would be more interesting, add to the game and benefit the game in some way?

If I don't see a very good justificaton for all of the cascading nerfs that stem from this removal, I'm blocking this.

2020-10-11 07:48 UTC, Qustinnus commented
Great point except one of those is a chemist pressing 2 buttons and being done, and the other is a botanist growing 100 potency food.

2020-10-11 08:07 UTC, KathyRyals commented
Growing 100 potency food takes literally two clicks. One to plant the watermelon, one to pour Saltpetre and Dieth in the tray and max the stats in 20 seconds.

2020-10-11 08:07 UTC, msgerbs commented
Man if you don't want people making sugar pills as food at least do it right and not in a way that massively nerfs chemistry's access to a whole shitload of reagents.

2020-10-11 08:09 UTC, KathyRyals commented
The point of this PR is to prevent cheesing the nutrition system with sugar pills. Great, I'm all for helping more interactions with the kitchen and such. But don't remove sugar! Instead just remove the nutrients or make it so 20+u makes you vomit or something.

2020-10-11 08:39 UTC, Pugie commented
This PR suggests a bright future for service-chemistry relations but will inflation cause sugar prices to skyrocket to 10000c shift start?

2020-10-11 09:35 UTC, Fikou commented
how do i eat as golem now

2020-10-11 10:06 UTC, brotherbeyondd commented
bad

2020-10-11 13:02 UTC, interestingusernam3 commented
This destroys infinite plumbing smoke cloud makers and therefore makes me sad, please don't merge.

2020-10-11 13:11 UTC, Krysonism commented
> 
> 
> how do i eat as golem now

eat cactus

2020-10-11 13:44 UTC, Krysonism commented
> 
> 
> Sugar pills are food. By the same logic, literal food lets you opt out of the hunger mechanic when eaten, too. Botany with 100 potency watermelons let you opt out of the hunger mechanic in one bite.

Botany is one of the two food producing jobs so if they grow melons, great. Going to botany and enjoying a slice of melon is not the same as drinking pure sugar in your chemistry cave because you are busy making grenades.

>This destroys infinite plumbing smoke cloud makers and therefore makes me sad, please don't merge.

There is still the smoke machine. 

>Can you explain in more detail why you think it would be more interesting, add to the game and benefit the game in some way?
I believe scarcity is good, and things that are effortless and infinite are bad.

The main two reagents this affects, smoke and mannitol(33% sugar content) are pretty powerful chems with easy recipes, putting a moderate cost on these reagents will force the chemist to make choices which leads to better gameplay, and people appreciating these reagents more. 

The chemist produces a wide variety of reagents the crew would be interested in buying. Yet he needs pretty much nothing himself(unless you want to mine some geysers).

I think this PR helps move the game in the right direction in nutrition, scarcity and economy integration.

I also think many people who are freaking out are vastly overestimating how much sugar they need in an average round.

2020-10-11 13:57 UTC, Krysonism commented
> 
> 
> just ctrl+fing sugar on the wiki, this nerfs the availability of helbital, mannitol, saline-glucose, ephedrine, synaptizine, space drugs, smoke, life, cryptobolin, impedrezine, laughter and sucrose agar (viro), and by extension neurine, psicodine, meth, lipolicide, virus rations, barber's aid, carpet, colorful reagent, quantum hair dye, fentanyl, rezadone, spaceacillin, anacea and more

Have you checked how much sugar those contain? It is negligible for most of them.

2020-10-11 14:47 UTC, Timberpoes commented
I'm going to say it, unpopular opinion time - Hunger sucks in its current incrarnation. It exists to punish players who don't eat rather than reward players who do. You don't feel any satisfaction from eating, just a sense of relief that the hunger-related debuffs are gone. It's not a fun gameplay loop. I don't personally want food to be scarce.

In my opinion, prepared meals from the kitchen should confer some tangible benefits that go above and beyond merely satisfying hunger. The chef should be valuable as a crew member because a good meal should provide some good buffs to the crew in general.

The issue isn't that sugar pills are too powerful. It's that properly prepared and cooked food sucks ass in almost every scenario and needs buffing with some tangile benefit or reason to eat it over taking a sugar pill.

2020-10-11 15:00 UTC, Krysonism commented
>I don't personally want food to be scarce.
This leads to what we can see on paradise, where most players just opt out of visiting the chef and instead just drink chocolate or chicken soup.
> In my opinion, prepared meals from the kitchen should confer some tangible benefits
This it's own set of downsides in my opinion because it could easily lead to chef becoming more of a powergaming job that are expected to create a small set of meta foods with the best buffs, rather than a creative job.

I like visiting chef and having a snack, and the chef needs customers for the job to be fulfilling.

2020-10-11 16:37 UTC, msgerbs commented
> I like visiting chef and having a snack, and the chef needs customers for the job to be fulfilling.

Hot take: This isn't going to result in any more engaging interaction for the chef. The same people who pop sugar pills now will just run by, grab everything on the counter and bring it back to their workplace so they don't have to leave again.

2020-10-11 16:44 UTC, Moja10 commented
Says sugar is too easy to avoid hunger, person hasn't obviously experienced the 4 minute long stun and sleep when you get DIABETES, as a former sugar powergamer I can safely say there is no chance in hell I would risk the literal coma that can result from eating too much sugar.

2020-10-11 21:20 UTC, Anonmare commented
You know you could just make sugar not satisfy hunger. This is cutting off your arm cause you broke a fingernail.

2020-10-11 22:03 UTC, Learner10 commented
I have never hit the outrageous 200 units of sugar needed to achieve the literal sugar coma state. I have never even seen a reason to not eat sugar. This doesn't address the issue behind sugar, this instead makes new issues. Nothing about this is a good idea.

(Also, begone with your sugarcane love, I'm growing white beets.)

2020-10-11 22:04 UTC, ExcessiveUseOfCobblestone commented
white beater

https://github.com/tgstation/tgstation/pull/54327#issuecomment-706774343

2020-10-13 06:07 UTC, cacogen commented
>61 thumbs down on the anti-sugar PR

it's not bikeshedding but it is inordinate attention on an unimportant issue because everyone easily understands it

2020-10-14 07:04 UTC, trerri commented
@interestingusernam3 you can still hook up a smoke machine to make infinite smoke with higher yield

2020-10-14 22:35 UTC, OmegaDarkPotato commented
so outside of the fact that this makes sugar more rare instead of "less of an alternative to talking to the chef", this also prevents me from sending out as many Sugar Rushes as bartender.

This is unacceptable.


In a more serious light, I think that everyone else in this PR has the better idea - if sugar is such a bad thing because of this hunger issue, just make it nowhere as nutritious or make a diabetic shock a real problem for **everyone**. Few people consume sugar for reasons outside of "I get to ignore chef", so even dropping an OD amount to 20u would probably go unnoticed by everyone else on-station, while still making it so that popping a sugar pill would be unviable, and that combined with a nerf to its effectiveness as a food supply should do it in for the issue you're trying to address here.

Forcing cooperation for sugar or making the bartender spend his 12 dollars and 13 cents on sugar both seem like poor solutions for a problem that I rarely ever hear about, anyway. We have enough snack machines on station that even if sugar became nonexistent people would just eat 4no raisins if they didn't want to have to go to the chef.

2020-10-14 23:35 UTC, Jared-Fogle commented
> so even dropping an OD amount to 20u would probably go unnoticed by everyone else on-station

Just remember syringe guns exist when doing anything like this.

2020-10-15 01:58 UTC, Pumpkinoe commented
forced sugar rush overdose

2020-10-15 06:33 UTC, XDTM commented
If the goal is to prevent sugar from being the best option to deal with hunger, it'd be better solved by making it not give nutrition, making it have to be paired with food to get nutrition, or giving it an organ-based limit until it stops being nutritious.

If the goal is to make chemistry more dependent on botany, it would be handled better by making a full organized rework, looking over existing recipies to see what would need rebalancing, and giving some QoL features to make it easier to share and store chemicals made by plants.

The intention of this (as well as the silver PR) seems to be the latter, but for some reason it's justified as if it's the former? In any case, picking and randomly removing single reagents based on unrelated issues will break balance until the step-by-step rework is complete, which would take a long time at this rate while also ending up worse than a planned full rework PR.

2020-10-15 07:40 UTC, necromanceranne commented
> I have never hit the outrageous 200 units of sugar needed to achieve the literal sugar coma state. I have never even seen a reason to not eat sugar. This doesn't address the issue behind sugar, this instead makes new issues. Nothing about this is a good idea.

Honey decays into an absurd quantity of sugar for some inexplicable reason. Therefore you can use very little honey to sugar coma people.

2020-10-17 08:29 UTC, Pugie commented
> I have never hit the outrageous 200 units of sugar needed to achieve the literal sugar coma state. I have never even seen a reason to not eat sugar. This doesn't address the issue behind sugar, this instead makes new issues. Nothing about this is a good idea.
> 
> (Also, begone with your sugarcane love, I'm growing white beets.)

Sugar coma is easy foam duplicates reagents.

2020-10-18 08:22 UTC, OmegaShoots commented
> 
> 
> wait so you put more effort into just removing sugar rather than just fixing the problem easily by getting rid of sugar's nutrition gain or making it so that you puke if you injest too much sugar
> 
> this feels like a troll PR

the same person also removed silver from chemistry dispenser for some astronomically stupid fluff reason of "silver is a precious metal and should be rare" despite silver not being used for any powerful reactions that needed the removal for any balance reason

2020-10-19 00:01 UTC, ExcessiveUseOfCobblestone commented
The silver item i was fine with because it could have been argued as standalone, but for sugar i think it needs to be a more comprehensive removal of the dispenser than slowly pulling out reagents from its options.

2020-10-19 00:01 UTC, closed without merging