fixes express consoles not working right
tgstation/tgstation pull request #54398
Opened 2020-10-14 18:03 UTC by Tlaltecuhtli

:cl:
fix: express console sends rockets
/:cl:

this code made it run the father console add interaction which made it not send a rocket but just add a request, it is now removed making it work again

2020-10-14 18:16 UTC, willox commented
this allows ghosts use an unlocked express supply console if they somehow spoof tgui acts (which they can)

2020-10-15 10:27 UTC, Pugie commented
Other stuff like mech orbital pads are broken and don't send either, could it be related?

2020-10-15 17:42 UTC, Rohesie requested changes
Don't remove the parent call, rework it at the base to support the behavior you want, instead.

2020-10-18 23:37 UTC, Rohesie commented on code/modules/cargo/console.dm
> +				return . = FALSE
`istype(src)` is almost never the right way to do things, what you want is a redefined proc
I assume you wanted to `return FALSE` so the rest of the proc doesn't happen.
The correct way h ere would be to move the things inside the `if("add)` check into a proc such as `/obj/machinery/computer/cargo/proc/add_id(id)`, which you redefine for `/obj/machinery/computer/cargo/express`

2020-10-19 14:27 UTC, Rohesie commented on code/modules/cargo/console.dm
> +	var/express = FALSE
Could you document this variable?
Maybe give it a better name as well?
What does `express` mean?

2020-10-19 14:28 UTC, Rohesie commented on code/modules/cargo/console.dm
> +				return . = FALSE
You want either `return FALSE` or `. = FALSE`, depending on if you want it to return here or not.

2020-10-19 16:44 UTC, closed without merging