Corrects the Chisel Description (The Pettiest PR Ever Made)
tgstation/tgstation pull request #54711
Opened 2020-10-31 02:39 UTC by EOBGames

## About The Pull Request
Corrects incorrect capitalisation in the chisel description.

## Why It's Good For The Game
This improves the gameplay experience by 0.001%, by my estimates.

## Changelog
:cl: Inept
fix: the pettiest errata ever in the chisel description
/:cl:

2020-10-31 02:40 UTC, Jared-Fogle approved these changes

2020-10-31 14:10 UTC, Fikou requested changes
it sounds better without the

2020-10-31 14:10 UTC, Fikou commented on code/game/objects/structures/statues.dm
> +	desc = "Breaking and making art since 4000 BC. This one uses advanced technology to allow the creation of lifelike moving statues."
```suggestion
	desc = "Breaking and making art since 4000 BC. This one uses advanced technology to allow creation of lifelike moving statues."
```

2020-11-01 00:50 UTC, msgerbs commented
Somebody's trying to get their T-shirt!

2020-11-01 04:35 UTC, merged