Unit tests for heretic knowledge
tgstation/tgstation pull request #55022
Opened 2020-11-17 23:57 UTC by EdgeLordExe

## About The Pull Request

Adds unit tests for heretic knowledge tree.

## Changelog
:cl:
code: No more shittery with inaccessible nodes getting merged. 
/:cl:

2020-11-18 05:28 UTC, Jared-Fogle commented
run the tests on ur own machine first

just uncomment `#define UNIT_TESTS` and run in dream daemon

2020-11-18 21:11 UTC, optimumtact commented
![](https://file.house/rT06.png
)

2020-11-18 21:12 UTC, optimumtact commented
You should collect the reachable ones in a list that you can intersect with
`subtypesof(base paths) - (unreachables)`

so you can show what wasn't hit

2020-11-18 21:12 UTC, EdgeLordExe commented
> You should collect the reachable ones in a list that you can intersect with
> `subtypesof(base paths) - (unreachables)`
> 
> so you can show what wasn't hit

good idea

2020-11-18 21:59 UTC, Jared-Fogle requested changes
Should have a comment explaining what the test actually *does* as well, it's a bit confusing for me just from reading the code.

2020-11-18 21:59 UTC, Jared-Fogle commented on code/modules/antagonists/eldritch_cult/eldritch_antag.dm
> +			gain_knowledge(EK)
```suggestion
		for(var/eldritch_knowledge in GLOB.heretic_start_knowledge)
			gain_knowledge(eldritch_knowledge)
```

2020-11-18 21:59 UTC, Jared-Fogle commented on code/modules/unit_tests/heretic_knowledge.dm
> +			list_to_check += Y
```suggestion
		var/datum/eldritch_knowledge/eldritch_knowledge = allocate(list_to_check[++i])
		for(var/next_knowledge in eldritch_knowledge.next_knowledge)
			if(next_knowledge in list_to_check)
				continue
			list_to_check += next_knowledge
```

2020-11-20 10:11 UTC, Jared-Fogle commented
Still requesting a comment on what the test actually does--it's not obvious to me just by reading code.

2020-11-20 11:23 UTC, EdgeLordExe commented
> Still requesting a comment on what the test actually does--it's not obvious to me just by reading code.

it checks all heretic knowledge nodes - excluding the ones which are unreachable on purpose - if players can reach them in game, if it finds a single node that is unreachable it throws an error

2020-11-20 21:31 UTC, Jared-Fogle commented
Cool, now put that in a comment 😛

2020-11-20 21:59 UTC, Jared-Fogle commented on code/modules/unit_tests/heretic_knowledge.dm
> +*/
```suggestion
/// This test checks all heretic knowledge nodes - excluding the ones which are unreachable on purpose - and ensures players can reach them in game.
/// If it finds a node that is unreachable, it throws an error.
```

2020-11-20 22:00 UTC, Jared-Fogle commented on code/modules/unit_tests/heretic_knowledge.dm
> +*/
Last nitpick, then it's fine.

2020-11-20 23:53 UTC, merged