Fixes lightbulb injections
tgstation/tgstation pull request #55132
Opened 2020-11-23 16:18 UTC by CoffeeDragon16

## About The Pull Request

Fixes #55071. Light bulb injections worked odd, and I simply made it work the same as it does for energy cells. This makes it so you can only inject the plasma once, as intended.

## Why It's Good For The Game

Fixes are good, and bugs are bad.

## Changelog
:cl:
fix: Light bulb injections work properly now
/:cl:

2020-11-23 16:24 UTC, bobbahbrown commented on code/modules/power/lighting.dm
> +	rigged = (reagents.has_reagent(/datum/reagent/toxin/plasma, 5)) //has_reagent returns the reagent datum
```suggestion
	rigged = reagents.has_reagent(/datum/reagent/toxin/plasma, 5) //has_reagent returns the reagent datum
```

you don't really need to wrap this in brackets i don't think

2020-11-23 18:25 UTC, itseasytosee commented
The unintended consequences of this PR are that you can now smuggle meth in lightbulbs.

2020-11-23 19:32 UTC, Jared-Fogle requested changes

2020-11-23 19:32 UTC, Jared-Fogle commented on code/modules/power/lighting.dm
> +	create_reagents(5, INJECTABLE | DRAINABLE)
Magic number--move 5 out to a define and then `#undef` it at the end.

2020-11-23 19:32 UTC, Jared-Fogle commented on code/modules/power/lighting.dm
> +	rigged = reagents.has_reagent(/datum/reagent/toxin/plasma, 5) //has_reagent returns the reagent datum
Then use that define here.

2020-11-23 21:25 UTC, TheBonded commented
> The unintended consequences of this PR are that you can now smuggle meth in lightbulbs.

does this mean you can fill lightbulbs with other chemicals that react when heated, and have them react when the lightbulb is turned on?

stabilized TaTP lightbulb meta

2020-11-23 21:43 UTC, itseasytosee commented on code/modules/power/lighting.dm
> +	return ..()
```suggestion
	return ..()
	#undef LIGHT_REAGENT_CAPACITY
```

2020-11-23 22:06 UTC, CoffeeDragon16 commented
sadly thebonded its snowflaked to plasma so that's someone else's job to get working

2020-11-23 22:16 UTC, CoffeeDragon16 commented on code/modules/power/lighting.dm
> +	return ..()
thanks i totally forgot to undef

2020-11-23 22:28 UTC, TheBonded commented
does injecting it with a bluespace syringe put in 60u instead of 15?

2020-11-23 22:47 UTC, TemporalOroboros commented
@TheBonded Injecting it used to just rig it and eat all of the reagents in the syringe. Now it can store up to 5u of reagents and if all of that's plasma it will explode when it's used.

2020-11-24 04:24 UTC, Jared-Fogle commented on code/modules/power/lighting.dm
> +	#undef LIGHT_REAGENT_CAPACITY
```suggestion
#undef LIGHT_REAGENT_CAPACITY
```

2020-11-24 21:27 UTC, merged