Improvements to Anon Names + Wizard Academy theme
tgstation/tgstation pull request #55935
Opened 2021-01-03 21:34 UTC by tralezab

## About The Pull Request

### Code Improvements:
Anon names now uses fully randomizing human proc instead of generating a random preference, this should preserve your character in instances where you join an anon mode game, then check your game panel and save the changes before next round

Anon names can now be activated at any time, it has a few more prompts for changing the crew or just making it for new joins + announcing or not

Anon names can be DISABLED at any time, loading everyone's preferences for who they originally were. This can probably go awry, but it really doesn't need to be perfect

There's one new theme for anonymous names, giving everyone a wizard name and the AI into crystallized intelligences. I'm considering refactoring this whole thing into a "ERT datum" like system so it uses less switch cases and generally lazy code

## Why It's Good For The Game

I Ran Anon Names And Didn't Get An Admin Complaint. No really though there wasn't much reason to make this pregame only and it can be used for events a bit better

## Changelog
:cl:
add: Added the Wizard Academy names setup
add: Anon names can be ran post roundstart with many more options
fix: Anon names won't fuck with your preferences anymore, only loading from it instead of saving to it.
/:cl:

2021-01-09 00:23 UTC, tralezab commented
eff it, i'm the only one working on anon names in any capacity i'm going to refactor it to use datums and document it

2021-01-17 03:22 UTC, Rohesie commented on strings/names/wizardfirst.txt
> +Wizardman
what

2021-01-17 03:24 UTC, Rohesie commented on strings/names/wizardsecond.txt
> +Evergreen
Could you order this alphabetically? There's phyton sort scripts and tools to automatically do that for you.

2021-01-17 03:30 UTC, Rohesie requested changes

2021-01-17 03:30 UTC, Rohesie commented on code/modules/admin/verbs/anonymousnames.dm
> +					player.fully_replace_character_name(old_name, player.real_name) //this changes IDs and PDAs and whatnot
```suggestion
			if(!player.mind || (!ishuman(player) && !issilicon(player)) || !SSjob.GetJob(player.mind.assigned_role))
				continue
			var/old_name = player.real_name //before restoration
			if(issilicon(player))
				var/is_AI = isAI(player)
				player.apply_pref_name("[is_AI ? "ai" : "cyborg"]", player.client)
			else
				player.client.prefs.copy_to(player, antagonist = (LAZYLEN(player.mind.antag_datums) > 0), is_latejoiner = FALSE)
				player.fully_replace_character_name(old_name, player.real_name) //this changes IDs and PDAs and whatnot
```
Early continue

2021-01-17 03:30 UTC, Rohesie commented on code/modules/admin/verbs/anonymousnames.dm
> +				player.fully_replace_character_name(player.real_name, theme.anonymous_name(player))
```suggestion
		if(!player.mind || (!ishuman(player) && !issilicon(player)) || !SSjob.GetJob(player.mind.assigned_role))
			continue
		if(issilicon(player))
			player.fully_replace_character_name(player.real_name, theme.anonymous_ai_name(isAI(player)))
		else
			randomize_human(player) //do this first so the special name can be given
			player.fully_replace_character_name(player.real_name, theme.anonymous_name(player))
```
Early continue

2021-01-23 20:11 UTC, merged