Revives old Mafia PR adding security, a mind bogglingly large amount of refactors, some documentation, and other niceities
tgstation/tgstation pull request #56199
Opened 2021-01-16 07:51 UTC by tralezab

revival of #53456 from last year, but with some changed design thoughts on moffia. for example, not removing thoughtfeeder, but instead removing assistant.

## About The Pull Request

### New Roles:
Warden: Can go on alert once per game, killing everyone who visits. Careful that you don't teamkill with this!
Security Officer: Protects other players like a medical doctor, but when attacked they will attack the attacker and die instead of the person they're protecting
Head of Security: Can choose to attack and kill someone during the night. If they are innocent, they will die the next day.

### Things to make game nicer to play:
The game will speed up once there are only half the players who joined, halfing all the times in phases. Should allow games that are "set" to resolve quicker

The game no longer adds assistants

Game 

### Refactor stuff for coders:

Renames can_preform_action signal to on_visit, makes things much more readable
Roleblocking is a flag
Lawyer uses it (duh)

all prerequisites for doing an action are now in a proc that checks for visiting and all that
ALL ACTION STUFF IS NO LONGER DONE COMPLETELY DIFFERENTLY FOR EACH ACTION WOOO NO MORE INSANOFLEX CODE

## Why It's Good For The Game

Mafia is a beautiful shitty mess and my love was sparked by some games that randomly started

## Changelog
:cl:
add: MAFIA STUFF: Three new security roles have been added for townies!
tweak: MAFIA: speeds up when half the people are dead, thank god
balance: Assistants are no longer in the game. Too boring of a role when 
fix: Lawyers didn't roleblock like half the roles in the game?!? now they do.
/:cl:

2021-01-17 13:10 UTC, BadSS13Player commented
>balance: Assistants are no longer in the game. Too boring of a role when

WHEN WHAT???

Also, you didn't add MAFIA: to the last two entries.

2021-01-17 18:13 UTC, davethwave commented
Getting rid of assistants should be in a separate PR. Even then assistants are for letting people do their own thing without having any responsibility from a job as well as a job for new people to get used to their controls. If assistant is boring then you aren't doing anything with the role. Open a shop, make a space base. I dunno. But I would be very surprised if this was merged with a job removal as part of the package.

2021-01-17 20:57 UTC, optimumtact commented
7 day blocks for both of you for not actually reading the PR before clutching your purse.

He's talking about in the mafia minigame not the job on the station

2021-01-17 20:59 UTC, optimumtact commented on code/datums/achievements/mafia_achievements.dm
> +/*
your PR is not ready while these are here

2021-01-19 10:46 UTC, Jared-Fogle requested changes

2021-01-19 10:46 UTC, Jared-Fogle commented on code/modules/mafia/controller.dm
> +	// 1-2 disruptors to equal up to 12, depending on if there was a killing role
Move this comment above the line it's talking about.

2021-01-19 10:46 UTC, Jared-Fogle commented on code/modules/mafia/roles.dm
> +	var/datum/outfit/revealed_outfit = /datum/outfit/mafia/assistant //what they get equipped with when they are revealed
Make this a doc comment.

2021-01-19 10:46 UTC, Jared-Fogle commented on code/modules/mafia/roles.dm
> +	var/role_flags = NONE
Document this.

2021-01-19 10:46 UTC, Jared-Fogle commented on code/modules/mafia/_defines.dm
> +#define ROLE_ROLEBLOCKED	(1<<5) //cannot perform any actions that night, preselected actions fail
Doc comments.

2021-01-19 17:54 UTC, adamkad1 commented
Are we copying town of salem yet? they dont have 'townies' so thats nice

2021-01-20 03:11 UTC, Twaticus approved these changes

2021-01-25 01:42 UTC, davethwave commented
Here to apologize. Though you were talking about the families gamemode rather than the maffia minigame.

2021-02-05 02:34 UTC, merged