Add better weakref support to qdel
tgstation/tgstation pull request #56206
Opened 2021-01-16 16:42 UTC by spookydonut

## About The Pull Request
This is better/less overhead

2021-01-16 17:53 UTC, Cyberboss requested changes

2021-01-16 17:53 UTC, Cyberboss commented on code/datums/weakrefs.dm
> +	qdel(resolve())
Avoid calling resolve twice in this proc please

2021-01-17 05:30 UTC, Cyberboss approved these changes

2021-01-17 14:20 UTC, MrStonedOne approved these changes

2021-01-17 20:19 UTC, merged