Donkpockets 4: Return of the Mousepockets
tgstation/tgstation pull request #56295
Opened 2021-01-20 10:14 UTC by Coconutwarrior97

## About The Pull Request
![image](https://user-images.githubusercontent.com/40315842/105160527-f59a5c00-5ad5-11eb-891e-61633aafa8cb.png)

Adds mouse pockets and a crab pocket to the game!

## Why It's Good For The Game

Mouse pockets are made from tasty easily available maint mice! Also theres a crab pocket which is cool.

## Changelog
:cl:
add: Adds mouse pockets + crab pocket for crafting.
/:cl:

2021-01-20 11:24 UTC, Jared-Fogle commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
> +	if(mouse_state == "mouse_brown_dead")
When is this not true? Admin intervention?

I think either way, I'd rather this check `initial(deadmouse.icon_state)` (after correctly checking `var/obj/item/food/deadmouse` to `var/obj/item/food/deadmouse/deadmouse`).

2021-01-20 11:30 UTC, Jared-Fogle commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
> +/datum/crafting_recipe/food/donkpocket/donkmousebrown
I don't really like having separate recipe per mice, our crafting menu is already not very great as is.

This should instead be a general recipe for any `/obj/item/food/deadmouse`, which creates a generic `/obj/item/food/donkpocket/deadmouse`. Then, *that* re-implements `/CheckParts`. That way, you can dynamically update the sprite depending on the mouse.

Search CheckParts across the codebase to find existing crafting recipes that do this.

2021-01-20 11:31 UTC, Jared-Fogle commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
> +/datum/crafting_recipe/food/donkpocket/donkmousebrown
If you want to keep the different tastes and descriptions and whatnot, you still can with this, you should be able to replace the item in CheckParts.

2021-01-20 11:31 UTC, Jared-Fogle requested changes
I'd like the recipes to be combined into one, creating an abstract dead mouse donk pocket that decides then and there.

2021-01-21 08:10 UTC, Farquaar commented
Wow those sprites look fantastic

2021-01-23 03:30 UTC, maxymax13 commented
delicious

2021-01-28 14:12 UTC, Twaticus approved these changes

2021-02-02 17:42 UTC, Escamado commented
they should make lizards happy, since all donkpockets make them disgust since its a pastry.

2021-02-06 21:33 UTC, optimumtact commented
@Coconutwarrior97 stop playing vrchat and finish this PR instead

2021-02-15 05:38 UTC, Mothblocks commented
this has been untouched for a month silly

2021-02-15 05:38 UTC, closed without merging