Resonator rework
tgstation/tgstation pull request #56293
Opened 2021-01-20 07:07 UTC by SmArtKar

## About The Pull Request

This PR slightly reworks resonators so they aren't completely useless as a mining tool. It now has 2 modes: Automatic detonation after 2 seconds, or manual which triggers after you hit a field with resonator. The main change is that now field can chain detonate. Upgraded detonator also posesses a third mode: Matrix traps, which detonate after someone walks over them. This will turn resonators into a handy tool for all the fauna hunters.

## Why It's Good For The Game

Currently resonators are utterly useless and nobody gonna use em(except golems who are forced to start with it)

## Changelog
:cl:
tweak: Resonators can now chain detonate fields and set matrix traps that activate upon someone walking over them.
/:cl:

2021-01-20 07:10 UTC, Fikou commented on code/modules/mining/equipment/resonator.dm
> +		mode = 1
magic numbers, replace with defines

2021-01-20 07:11 UTC, Fikou commented on code/modules/mining/equipment/resonator.dm
> +		mode = 1
here too

2021-01-20 07:15 UTC, SmArtKar commented on code/modules/mining/equipment/resonator.dm
> +		mode = 1
solved

2021-01-20 07:15 UTC, SmArtKar commented on code/modules/mining/equipment/resonator.dm
> +		mode = 1
solved

2021-01-20 08:03 UTC, Fikou commented on code/modules/mining/equipment/resonator.dm
> +#define RESONATOR_MODE_MATRIX 3
undef these at the end

2021-01-21 09:57 UTC, AndroidMK2 commented
I would really like this changes

2021-01-23 10:33 UTC, Jared-Fogle requested changes

2021-01-23 10:33 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +	duration = 600
Is this meant to be 60 seconds? What does this number mean?

2021-01-23 10:33 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +#define RESONATOR_MODE_MATRIX 3
what he said

2021-01-23 10:33 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +	var/quick_burst_mod = 0.8 //How efficient it is in manual mode. Yes, we lower the damage cuz it's gonna be used for mobhunt
```suggestion
	/// How efficient it is in manual mode. Yes, we lower the damage cuz it's gonna be used for mobhunt
	var/quick_burst_mod = 0.8
```

2021-01-23 10:33 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +		duration = 20
This too, do you mean `2 SECONDS`?

2021-01-23 10:33 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +	if(mode == 1)
Use your defines, not a magic number.

2021-01-23 19:30 UTC, Jared-Fogle commented on code/modules/mining/equipment/resonator.dm
> +	//How efficient it is in manual mode. Yes, we lower the damage cuz it's gonna be used for mobhunt
Doc comments use three slashes.

2021-01-31 01:09 UTC, merged