Adds Quirk-Related "Special Pool" to obsessed for Chaplain, Clown, and Mime targets.
tgstation/tgstation pull request #56357
Opened 2021-01-22 23:57 UTC by RaveRadbury

also adds some descriptions to vars, moves them around for readability

## About The Pull Request
Adds a special pool to the obsessed target picker, making it so if the obsessed has the Spiritual, Clown Fan, or Mime Fan quirks that they will pick from a smaller pool of Chaplains and Clowns/Mimes if they have the respective quirks.

## Why It's Good For The Game
It makes sense that if you're a fan of these jobs that you would likely have them as your obsession target, it also adds to the texture of these jobs. They are all RP-centric, so you're more likely to get some good interactions with them rather than trying to spend your whole shift clawing at the viro airlock so you can get a picture with the reclusive disease person. Adds more texture to the quirks involved.

## Changelog
:cl:
tweak: If you're a Clown/Mime fan and you become obsessed, you'll have them as your target. Also works for Spiritual with the Chaplain.
/:cl:

2021-01-22 23:57 UTC, RaveRadbury commented
I'd like to request a testmerge for this so I can make sure that it's working as intended. Tried it on local but you *need* the potential targets to be occupied by a player in order for them to be in the pool, aghosting did not work.

2021-01-23 02:13 UTC, Jared-Fogle commented
1. Start server with Dream Daemon
2. Connect
3. Log out. Sign into an alt account or stay as a guest
4. Connect on that account

2021-01-23 02:15 UTC, Jared-Fogle commented on code/datums/brain_damage/creepy_trauma.dm
> +				continue
Change this copy and paste in favor of an associative list of assigned_role -> trait.

2021-01-24 01:11 UTC, RaveRadbury commented
Alright, added the list as requested, also tested with the method provided in the earlier comment. All working as expected!

2021-01-24 02:16 UTC, Jared-Fogle requested changes

2021-01-24 02:16 UTC, Jared-Fogle commented on code/datums/brain_damage/creepy_trauma.dm
> +					break
This is why I said job -> trait, and not trait -> job.

If you do job -> trait, you can save the loop and just check:

```dm
if (trait_obsessions[job] != null && HAS_TRAIT(owner, trait_obsessions[job]))
```

2021-01-24 02:49 UTC, RaveRadbury commented
Changes made, local test run

2021-01-24 02:58 UTC, merged