disabled DLC only content on arena shuttle
tgstation/tgstation pull request #56376
Opened 2021-01-23 15:23 UTC by Tlaltecuhtli

🆑 
fix: arena shuttle has keys to open the crates
/:cl:
forgot about the only place that spawns tendril crates outside of tendrils, now it has keys to open the boxes
used strongdmm to edit map, not sure if it worked right

2021-01-26 15:14 UTC, Iatots commented
What if everyone received a key after passing through the portal? It would fix the first person getting on the shuttle looting all of them.

2021-01-31 20:23 UTC, coiax requested changes
> 
> 
> What if everyone received a key after passing through the portal? It would fix the first person getting on the shuttle looting all of them.

This is a good suggestion, do this.

2021-02-01 14:59 UTC, Rohesie commented
Set PRs to draft after you review them please, @coiax

2021-02-07 16:34 UTC, coiax commented
@Tlaltecuhtli This good to go, you tested it?

2021-02-11 20:31 UTC, Tlaltecuhtli commented
yes

2021-02-15 11:01 UTC, merged