Cargo bounty cube incentives
tgstation/tgstation pull request #56375
Opened 2021-01-23 14:50 UTC by cacogen

## About The Pull Request

1. Bounty cube announces its creation over Supply with its creator and area, starting the bonus countdown
2. 20% speedy delivery bonus for cargo if you send the cube within 5 minutes of its creation
3. Using an export scanner on it in the supply shuttle awards a 10% personal handling tip when it reaches Centcom
4. Cube nags at five minutes over Supply if it's not sent and cargo bonus is lost
5. If there's a handler attached when it nags their ID card tells them it hasn't been sent
6. Cube continues to nag less and less often
7. All nags tell you the cube's area

## Why It's Good For The Game

Incentivises cargo to send bounty cubes in a timely fashion.

## Changelog
:cl: cacogen
add: Bounty cube announces creation over Supply with its creator and area
add: Bounty cube speedy delivery bonus of 20% for cargo if it's sent within five minutes
add: Bounty cube personal handling tip of 10% if you scan it with an export scanner while on the shuttle, which is paid when it reaches Centcom
add: Unsent bounty cubes nag over Supply with their area, starting at 5 minutes and decreasing in regularity after each nag
/:cl:

2021-01-23 18:39 UTC, ArcaneMusic commented
You've given bounty cubes tracking labels.
I'll admit, it's clever, I like this 👍

2021-01-27 00:21 UTC, coiax requested changes
Some changes.

My main concern is that this is going to get too spammy far too quickly. I admit, having 3 bounty cubes pile up is a concern, but that means that in the space of 12 minutes, Cargo is going to get 6 seperate messages about it.

2021-01-27 00:21 UTC, coiax commented on code/game/machinery/civilian_bounties.dm
> +	QDEL_NULL(radio)
Do cleanup logic specific to the type before the `. = ..()` call.

2021-01-27 00:21 UTC, coiax commented on code/game/machinery/civilian_bounties.dm
> +	var/next_nag_time = 0
Use the COOLDOWN_DECLARE family of define helpers.

2021-01-27 00:21 UTC, coiax commented on code/datums/components/pricetag.dm
> +	var/list/payees = list()
Could you put an autodoc string `///` above this explaining what it's likely to contain

2021-01-27 00:21 UTC, coiax commented on code/modules/cargo/export_scanner.dm
> +/obj/item/export_scanner/afterattack(obj/O, mob/living/carbon/user, proximity)
Is this an assertion you can make with `afterattack`?

2021-01-27 00:21 UTC, coiax commented on code/game/machinery/civilian_bounties.dm
> +		. += "<span class='notice'>Scan this in the cargo shuttle with an export scanner to claim the <b>[bounty_value * (handler_cut/100)] cr</b> handling tip."
Need to close this `<span>`

2021-01-27 01:37 UTC, cacogen commented
I understand. The potential spamminess is one of the concerns I have. But I'd prefer to see it in action before making assumptions about it. If it gets pulled I'll tweak the problems I see with it.

I don't know if six messages for three cubes is going to be all that much in twelve minutes of chat logs. If you send it in five minutes (and that seems reasonable barring someone taking off with it, which I don't think will happen often) then it's only the creation messages which are desirable because they tell you how to get your bonus. 

If it proves to be too spammy I'll have to figure out another way of getting the message to people with shuttle access or an alternative to using a message (which I assume would be more easily missed).

I was thinking of a console or a tablet app that has a list of cubes and their locations, but by itself that doesn't solve the problems of them being easy to ignore, undesirable to send and there being no motivation to send them quickly. The tablet app could let you track cubes using an overlay too.

2021-01-31 17:14 UTC, cacogen commented
Ok so some issues

1. @coiax COOLDOWN_DECLARE seems to create a global variable and I'm not sure how to make it use a different variable for each cube
2. Value isn't split between cargo and the bounty holder, Centcom pays 130% of the value, should probably fix but this will devalue them for cargo (i.e. 70% vs. 100%, with 20% speed bonus optional in each case)
3. Cubes are trivially undervalued for reasons I don't understand (something to do with the k-elasticity I'm guessing), would like to fix for perfectionism but not sure how

Bonus

  i. Not sure if it can register multiple handlers but if so I need to fix that and it should probably not be overwriteable (though this creates drama so perhaps it should)
  ii. It sends the handler registered message after the handler has already been registered (makes it less clear if it worked so I will fix)

2021-02-06 05:22 UTC, cacogen commented
I want to use the creation time variable I added here to tell the bounty holder how long the cube took to send, in addition to the name of the handler and the amount the holder got from it. Currently it's not used. Price tags can probably have custom sale messages set by their parent.

2021-02-06 10:23 UTC, coiax requested changes

2021-02-06 10:23 UTC, coiax commented on code/game/machinery/civilian_bounties.dm
> +		COOLDOWN_START(src, next_nag_time, world.time + nag_cooldown)
COOLDOWN_START already uses `world.time`.
```suggestion
		COOLDOWN_START(src, next_nag_time, nag_cooldown)
```

2021-02-06 10:23 UTC, coiax commented on code/game/machinery/civilian_bounties.dm
> +	var/bonus_countdown = 5 MINUTES
I'm confused why this is a var, given that the speed bonus is lost when the cube first nags.

2021-02-06 15:44 UTC, cacogen commented on code/game/machinery/civilian_bounties.dm
> +			radio.talk_into(src, "Unsent in <b>[get_area(src)]</b>.[speed_bonus ? " Speedy delivery bonus of <b>[bounty_value * speed_bonus]</b> credit\s lost." : ""]", RADIO_CHANNEL_SUPPLY)
Well, it obviously indicates emphasis in speech. Players not having that level of control doesn't mean other things that talk shouldn't. I doubt it's unprecedented in the codebase.

But this minor type of thing isn't worth arguing over. And the boldness is difficult to see in the monospaced font machines use anyway.

2021-02-06 15:49 UTC, cacogen commented on code/game/machinery/civilian_bounties.dm
> +	desc = "It needs to be squeezed by someone with a bank account it can detect to set itself up. This will alert Supply."
I wasn't sure how IC to make it. I figured if it showed up in the round somehow then it's less immersion breaking this way. But sure.

2021-02-10 03:02 UTC, cacogen commented
@coiax okay well whoever you're ready

2021-02-10 10:17 UTC, merged

2021-02-10 10:17 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-13). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.