Makes borg organ bags into an apparatus
tgstation/tgstation pull request #56401
Opened 2021-01-24 20:01 UTC by dragomagol

## About The Pull Request
Despite behaving exactly like a borg apparatus, this was a tool. Now it is an apparatus, and appropriately dumps organs on decon. 

I'm not sure that setting the icon_state to null is the ideal way to handle the organ bag being drawn twice (once underneath and once above as an overlay), so if there's a better way please let me know. 

## Why It's Good For The Game
Fixes #53248

## Changelog
:cl:
fix: borg organ bags are now an apparatus and drop held organs on deconstruction
/:cl:

2021-01-24 20:16 UTC, AlinaStarkova commented
by drop on deconstruction, do you mean, drops the organs when you store the tool inside the borg? if so, i dont like this, not one bit

rather I would prefer a fix so that hitting a smart fridge with the organ bag throws the organ into the fridge, currently borgs cant put organs into fridges

2021-01-24 20:18 UTC, dragomagol commented
> by drop on deconstruction, do you mean, drops the organs when you store the tool inside the borg? if so, i dont like this, not one bit
Not at all, it makes it function like a circuitboard holder or beaker holder. The behaviour should be the same as before, just when your model is reset it drops anything in the bag.

2021-01-24 20:19 UTC, AlinaStarkova commented
> > by drop on deconstruction, do you mean, drops the organs when you store the tool inside the borg? if so, i dont like this, not one bit
> 
> Not at all, it makes it function like a circuitboard holder or beaker holder. The behaviour should be the same as before, just when your model is reset it drops anything in the bag. 
> 

is it tested? and while your fixing this, could you also *maybe* fix it so you can put organs into the fridge using the bag? 🥺

2021-01-24 20:26 UTC, dragomagol commented
It is tested, yes. I can take a look at the storage thing.

2021-01-25 08:09 UTC, zxaber commented
>and while your fixing this, could you also _maybe_ fix it so you can put organs into the fridge using the bag? pleading_face

Assuming everything is done correctly, apparatus base code should allow that by default. Humans holding an object make an attack with that object when they try to use it on something (IE, you "attack" a chem machine with a beaker to insert it), and the apparatus code emulates that attack with the held object.

2021-01-25 08:21 UTC, dragomagol commented
I just tested it and Zxaber is absolutely right, this code makes the organ bag work with organ storage.

2021-01-29 06:47 UTC, spookydonut requested changes

2021-01-29 06:47 UTC, spookydonut commented on code/game/objects/items/robot/robot_items.dm
>  	storable = list(/obj/item/reagent_containers/food/drinks/,
```suggestion
	storable = list(/obj/item/reagent_containers/food/drinks,
```

2021-02-05 09:34 UTC, merged