Dennok's old shuttle decal fix but I'm gonna try and do what anturk wanted in that pr (a few hedge funds are about to go bust)
tgstation/tgstation pull request #56471
Opened 2021-01-27 20:06 UTC by tralezab

## About The Pull Request

Shuttle decals will work and this won't break bespoke

## Why It's Good For The Game

Fix

## Changelog
:cl:
fix: shuttle decals will work.
/:cl:

2021-01-27 20:27 UTC, TemporalOroboros commented
Does this also apply to smoothing decals? If I remember correctly they copy some normal decal code because of needing to pass extra args when the decal changes.

2021-01-27 20:32 UTC, tralezab commented
maybe 🤡

2021-01-27 21:58 UTC, tralezab commented
Ok, implemented anturk's mostly completed fix, and it works. Looks like this is good to go

2021-01-27 22:14 UTC, tralezab commented
really was a draft for only a couple seconds huh

2021-01-29 09:51 UTC, cacogen commented
>doesn't say bugs is bad

one job

2021-01-30 02:06 UTC, tralezab commented
bro...

2021-01-31 07:56 UTC, Jared-Fogle commented on code/__DEFINES/dcs/signals.dm
> +///from base of turf/proc/onShuttleMove(): (turf/newT) //E
//E?

2021-01-31 07:56 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +			var/datum/element/decal/D = source.comp_lookup[COMSIG_ATOM_UPDATE_OVERLAYS]
Better variable names.

2021-01-31 07:59 UTC, Jared-Fogle requested changes

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +		else
Just use an if statement, not a switch.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +	switch(length(source.comp_lookup[COMSIG_ATOM_UPDATE_OVERLAYS]))
What is this for? Are you sure this is sane? It's scary to me to be using internal stuff like this.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +	for(var/datum/element/decal/D in old_decals)
Better variable names.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +		source._AddElement(result)
Don't use the internal `_AddElement`. Use `AddElement`.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +		source._AddElement(result)
I know *why* you're doing this, but you shouldn't. This is an implementation detail.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +	newT.AddElement(/datum/element/decal, pic.icon, pic.icon_state, directional , cleanable, pic.color, pic.layer, pic.plane, description, pic.alpha)
```suggestion
	newT.AddElement(/datum/element/decal, pic.icon, pic.icon_state, directional, cleanable, pic.color, pic.layer, pic.plane, description, pic.alpha)
```

2021-01-31 07:59 UTC, Jared-Fogle commented on code/modules/shuttle/on_move.dm
> +	//Decal stuff
```suggestion
```

Useless comment.

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +/datum/element/decal/proc/shuttle_move_react(datum/source, turf/newT)
`new_turf`

2021-01-31 07:59 UTC, Jared-Fogle commented on code/datums/elements/decals/_decal.dm
> +	if(!isatom(target) || ( !_pic && !generate_appearance(_icon, _icon_state, _dir, _layer, _plane, _color, _alpha, target)))
```suggestion
	if(!isatom(target) || (!_pic && !generate_appearance(_icon, _icon_state, _dir, _layer, _plane, _color, _alpha, target)))
```

2021-02-15 00:41 UTC, closed without merging