Fixes inconsistent weight classes in chameleon gear
tgstation/tgstation pull request #56525
Opened 2021-01-31 05:01 UTC by KathrinBailey

## About The Pull Request
• Makes chameleon masks w_class 2 (Small)
• Makes chameleon neck w_class 2 (Small)

## Why It's Good For The Game
This seems like an oversight. Almost every mask slot item is small, except for a few outliers like the explorer gas mask.
Same for neck slot items. They're almost always small.
Also, would you really want a breath mask to not fit in a box? This just seems like an accidental oversight.

## Changelog
:cl:
fix: Chameleon masks and neck slot items fit into boxes and pockets, like their counterparts they're camouflaging as almost always do.
/:cl:

2021-02-01 17:07 UTC, coiax requested changes

2021-02-01 17:07 UTC, coiax commented on code/modules/clothing/chameleon.dm
> +	w_class = 2
```suggestion
	w_class = WEIGHT_CLASS_SMALL
```

2021-02-01 17:07 UTC, coiax commented on code/modules/clothing/chameleon.dm
> +	w_class = 2
```suggestion
	w_class = WEIGHT_CLASS_SMALL
```

2021-02-05 09:15 UTC, KathrinBailey commented
aaaaa sorry I'm an idiot how could I forget about using defines sorry

2021-02-05 09:41 UTC, merged