ID Card Refactor Part 1: The Trim
tgstation/tgstation pull request #56532
Opened 2021-01-31 10:49 UTC by Timberpoes

## Test Merge Candidate

This PR is currently lacking in robust testing. There have been a number of sweeping changes including repathing. There are no gameplay functionality changes, but I would highly suggest testmerging this to make sure I haven't introduced any major runtimes or bugs in my repathing and refactoring efforts, especially on the visual side. I don't got the time to test every single change, but I've tested out as many of the systems as I can (as is evidenced by the gifs below).

## About The Pull Request

Advancing the implementation of https://hackmd.io/@tgstation/HkS-z64NP

Separates the concept of "retro" ID cards that use single icon states from "advanced" ID cards that are a composite of overlays.

Advanced ID cards are a base template - For example, we have the orange prisoner cards, black deathsquad/syndicate ones, gold, silver, grey - Without any hardcoded icons or any other details.

The assigned text, the little overlay that happens when the ID card has a name assigned to it, has similarly been pulled out to an overlay in all cases. This allow for future customisation if necessary - Any card can have any of the 3 assign text templates overlayed.

The card's assignment is now colloquially known as its trim. Currently there's no functionality change, but dynamic card "trimming" sets the stage for the trim portion of the design doc.

As a result of the additional flexibility afforded, this does mean players can now have Syndicate, Death Squad. ERT and NT assignments on their ID cards. I expect players to abuse this for fun and/or profit until it's no longer cool, unique or funny.

![X22mkYTNM6](https://user-images.githubusercontent.com/24975989/106381321-cb874a80-63af-11eb-89df-9afc19594dfc.gif)
![Fso72RziTF](https://user-images.githubusercontent.com/24975989/106381323-cd510e00-63af-11eb-9901-df16c9bfa42f.gif)

Massive re-pathing, although there should be no functionality changes in practice (beyond being able to customise formerly hardcoded cards like ERT cards, syndie/deathsquad black cards and prisoner cards)

Also to accomplish this I needed to atomise some icons.
![image](https://user-images.githubusercontent.com/24975989/106381311-c1fde280-63af-11eb-95d4-75f6b730c1de.png)

## Why It's Good For The Game

Advances towards the ID card design doc. More versatile and modular ID cards.

## Changelog
:cl:
refactor: Modified ID cards to be more flexible and accept a wider variety of job trims.
/:cl:

2021-02-01 09:07 UTC, Fikou commented
captain icon still is dirty grey  and not white 0/10

2021-02-02 00:34 UTC, Twaticus approved these changes

2021-02-07 22:53 UTC, Rohesie commented on code/controllers/subsystem/id_access.dm
> +		trims_by_title[title] = "trim_[ckey(title)]"
interesting usage of the `ckey()` proc 🎉

2021-02-07 23:11 UTC, Rohesie commented on code/modules/mining/machine_vending.dm
> +		new /datum/data/mining_equipment("Extra Id",       				/obj/item/card/id/advanced/mining,								250),
```suggestion
		new /datum/data/mining_equipment("Extra Id", /obj/item/card/id/advanced/mining, 250),
```
I swear, this pattern of adding a million spaces is diff hell.
Can you just replace these with a space each? Or just accept the suggestion if you don't want to go there.

2021-02-07 23:12 UTC, Rohesie requested changes
Great PR. Do the changes and this is ready for testing.

2021-02-14 01:00 UTC, Timberpoes commented
There's a bigger, badder, more insane PR incoming.

2021-02-14 01:00 UTC, closed without merging