Backport: Added the ability to freely change fonts + fixed dropdown overflow
tgstation/tgstation pull request #56575
Opened 2021-02-01 14:41 UTC by Watermelon914

## About The Pull Request

https://gitlab.com/cmdevs/colonial-warfare/-/merge_requests/593

Able to pick your own chat font from a list of fonts in chat settings
![image](https://user-images.githubusercontent.com/37270891/106472672-d1a62580-649a-11eb-959e-7dde803aeb41.png)
![image](https://user-images.githubusercontent.com/37270891/106472705-dc60ba80-649a-11eb-966d-0ee1634c5118.png)
![image](https://user-images.githubusercontent.com/37270891/106472832-fd291000-649a-11eb-909a-c6fd5d16f988.png)

Also fixed dropdown overflow so that it doesn't auto-break if the selected input is too long. Instead, it cuts it off with an ellipsis.
![image](https://user-images.githubusercontent.com/37270891/106473027-33ff2600-649b-11eb-9c23-c569581f9da2.png)

## Why It's Good For The Game

More user friendly

## Changelog
:cl:
add: Added chat fonts that can be chosen via settings. You can also input a custom font.
fix: Fixed dropdown overflow if the selected input is too long.
/:cl:

2021-02-01 15:55 UTC, stylemistake approved these changes
Very good.

2021-02-01 17:29 UTC, Watermelon914 commented
> Very good. I don't understand why dropdowns have this weird space at the bottom. Is it because of your dropdown changes in css?
> 
> Previous PR backported by spooky: #55928

No, it happened before and only happens when you open the dropdown for the first time.

2021-02-01 17:57 UTC, Watermelon914 commented
![image](https://user-images.githubusercontent.com/37270891/106498198-f3150a80-64b6-11eb-8189-be566d2c04df.png)
Fixed

2021-02-01 19:35 UTC, stylemistake commented
Hmmm, baselines are misaligned, try adding `inline align="baseline"` to Stack.

2021-02-01 19:59 UTC, Watermelon914 commented
![image](https://user-images.githubusercontent.com/37270891/106511336-ffee2a00-64c7-11eb-8fd3-440392df5c0e.png)
Nice

2021-02-01 20:53 UTC, stylemistake approved these changes
Not perfect, but I accept. 👍

2021-02-02 02:57 UTC, zxaber commented
Is this VV-changeable? Can I punish players by setting their font to wingdings?

2021-02-02 09:53 UTC, Watermelon914 commented
> Is this VV-changeable? Can I punish players by setting their font to wingdings?

Nah, it's all done clientside.

2021-02-02 10:32 UTC, stylemistake commented
You can forge and inject a tgui message as an admin that changes player's font.

2021-02-03 08:31 UTC, cacogen commented
now everything can be comic sans

2021-02-04 07:40 UTC, Jared-Fogle commented on tgui/packages/tgui-panel/settings/constants.js
> +export const FONTS_DISABLED = "Use CSS";
```suggestion
export const FONTS_DISABLED = "Default";
```

I don't like this exposing of implementation details to players.

2021-02-04 07:40 UTC, Jared-Fogle commented on tgui/packages/tgui-panel/settings/SettingsPanel.js
> +import { SETTINGS_TABS, FONTS } from './constants';
```suggestion
import { FONTS, SETTINGS_TABS } from './constants';
```

2021-02-04 07:41 UTC, Jared-Fogle commented on tgui/packages/tgui-panel/settings/reducer.js
> +import { SETTINGS_TABS, FONTS } from './constants';
```suggestion
import { FONTS, SETTINGS_TABS } from './constants';
```

2021-02-04 07:41 UTC, Jared-Fogle requested changes
Minor feedback.

2021-02-04 22:02 UTC, merged

2021-02-04 22:02 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.