Changes fireman carrying from a trait on gloves to a skillchip
tgstation/tgstation pull request #56593
Opened 2021-02-02 14:35 UTC by necromanceranne

## About The Pull Request

What it says on the tin. 

Latex gloves were readily available in significant numbers. So I put a box of them in the medical lockers. Latex gloves are cheap and plentiful, so the skillchips here should be as well. Every medical doctor starts with this chip implanted.

However, nitrile gloves are special. There aren't as many available in a round, with one in each medical locker, one in the CMO's, and spawned with paramedics. Therefore, the CMO gets a box of the skillchips in their locker. They and paramedics also start with one implanted.

## Why It's Good For The Game

This fits a skillchip way more than a glove trait, since it is literally a skill imparted by the gloves.

## Changelog
:cl:
balance: Changes the carrying traits on Latex/Nitrile gloves into a skillchip.
balance: Medical doctors start the round with a quick carry skillchip (was the latex glove trait).
balance: Paramedics and the CMO start the round with a quicker carry skillchip (was the nitrile glove trait).
/:cl:

2021-02-02 16:14 UTC, coiax commented
Literally was thinking about doing this the other day, a good candiate for skillchips.

2021-02-02 16:15 UTC, coiax commented on code/modules/library/skill_learning/skillchip.dm
> +	chip_category = "bodycarrying"
Should this category be a define?

2021-02-02 16:51 UTC, Fikou commented
tinkerer gloves dont have a reason to be latex subtypes anymore

2021-02-02 16:54 UTC, necromanceranne commented on code/modules/library/skill_learning/skillchip.dm
> +	chip_category = "bodycarrying"
Yeah probably.

2021-02-02 18:45 UTC, necromanceranne commented
> tinkerer gloves dont have a reason to be latex subtypes anymore

Why were they before?

2021-02-02 21:55 UTC, Jared-Fogle commented on code/modules/library/skill_learning/skillchip.dm
> +	chip_category = "bodycarrying"
yeah

2021-02-02 21:56 UTC, Mothblocks requested changes
make that thing a define

personally as a medical doctor i don't like that the slight nerf on me so much but it makes sense so i bite my tongue

2021-02-03 10:27 UTC, coiax commented
> 
> 
> make that thing a define
> 
> personally as a medical doctor i don't like that the slight nerf on me so much but it makes sense so i bite my tongue

Just drag a braindead paramedic to the library, and steal his chip.

2021-02-03 13:21 UTC, necromanceranne commented
Did some categories defines hope that's enough

2021-02-03 21:30 UTC, Jared-Fogle commented
> Just drag a braindead paramedic to the library, and steal his chip. 🔪 🧠

i just get promoted to cmo every round anyway i'll just steal it from the locker so much work though

2021-02-03 21:31 UTC, merged

2021-02-03 21:31 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-10). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.