You can now remove embedded objects directly with a hemostat
tgstation/tgstation pull request #56637
Opened 2021-02-04 09:07 UTC by Ryll-Ryll

## About The Pull Request
Getting someone with a bullet or a throwing star lodged in their skull to lay down and let you do the remove embedded object surgery on them (possibly several times if they have shrapnel in multiple limbs) is a lot to ask for in hectic situations, and I doubt people ever really bothered since the object would probably fall out on its own (throwing stars notwithstanding) by the time you could actually finish the surgery.

So, now you just target the affected limb and use a hemostat on the patient to pry shrapnel out, ez pz. It takes a few seconds that scales with the size of the object, and you can do it to yourself if you're fine with taking twice as long (and happen to be carrying around a hemostat, you weirdo). This process causes no harm to the patient.

This PR also makes a few other tiny tweaks to embedding I've been meaning to get around to. Here's the breakdown:

- Objects thrown extra fast (higher than their normal throw_speed, like thrown by a hulk or an amped up disposal outlet) gain +10 to their embedding chance for each extra speed.
- Most bullets are now slightly more likely to embed, especially at point blank
- .357 bullets are somewhat more likely to cause piercing wounds

## Why It's Good For The Game
Makes removing embedded objects from other people less obnoxious. The other changes just make embedding and bullets more consistent

## Changelog
:cl: Ryll/Shaps
add: You can now remove embedded objects in a patient by using a hemostat on the patient's affected limb, no surgery necessary!
del: Removed the now obsolete "remove embedded objects" surgery
balance: Objects thrown at high speed (like by a hulk or amped up disposal outlet) are now more likely to embed, scaling with the speed they're flung into you at
balance: Most bullets are now slightly more likely to embed
balance: .357 bullets are now somewhat more likely to cause piercing wounds
/:cl:

2021-02-04 09:11 UTC, Jared-Fogle requested changes
Minor quip, rest looks good.

2021-02-04 09:11 UTC, Jared-Fogle commented on code/__DEFINES/combat.dm
> +#define EMBED_CHANCE_SPEED_BONUS				10
Remove the tab indent on this, it's not aligned to anything anyway and are hideous.

2021-02-04 10:59 UTC, SkeletalElite commented
make it possible to do with ghetto hemostat alternatives but make it cause damage

2021-02-04 11:15 UTC, Tlaltecuhtli commented
> make it possible to do with ghetto hemostat alternatives but make it cause damage

crowbar has hemostat tool flag

2021-02-04 11:34 UTC, Ryll-Ryll commented
how the shit are you supposed to clamp blood vessels with a mf'ing crowbar

2021-02-04 22:03 UTC, Jared-Fogle approved these changes

2021-02-05 02:51 UTC, necromanceranne commented
Pulling bullets out with wirecutters sounds awesome.

2021-02-05 09:08 UTC, merged