Contribution guidelines: type checks in lists
tgstation/tgstation pull request #56761
Opened 2021-02-08 20:43 UTC by Rohesie

* Updates the contribution guidelines to include the `as anything` key to skip checks in lists.
* Reduces the explanation a bit, to make it more succinct.
* Makes the examples use default byond types and vars, and code that actually compiles, instead of pseudo-code. Plus early continues, because they're good.

2021-02-08 20:46 UTC, Rohesie commented
@tgstation/commit-access

2021-02-08 20:48 UTC, optimumtact commented
gross

2021-02-08 21:01 UTC, Rohesie commented
This is byond syntax, not really my choice.
I'm skeptical a define would make things much more clear, honestly.

2021-02-08 21:24 UTC, stylemistake commented
```
#define of as anything
```

Nice and evil.

2021-02-08 21:25 UTC, Jared-Fogle commented
+1 to `of` as a define, `as anything` looks weirdly relies-on-implementation-details to me.

2021-02-08 21:34 UTC, optimumtact commented
-1 to the define, it's ugly but just accept it

2021-02-08 21:53 UTC, Cyberboss commented
> 
> 
> -1 to the define, it's ugly but just accept it

I'd easily accept it if we could lint and auto-correct (i.e. prettier) to it.

2021-02-08 22:05 UTC, LemonInTheDark commented
Is this more performant then 
```
for(var/item in list)
        var/typepath/varname = item
```
If so, by how much? I really really hate this syntax

2021-02-08 22:18 UTC, Rohesie commented
I'll do whatever is decided, but I feel that an `of` define does not really offer any clarity as to what's going on, while `as anything`, ugly as it may be, at least has a parallel in filtering input (technically `as null|anything` would also work).

We don't have defines for filtering inputs, for good reasons.
It's ugly, sure, but it's DM syntax and I haven't seen a way to actually make it more clear yet.

> 
> 
> Is this more performant then
> 
> ```
> for(var/item in list)
>         var/typepath/varname = item
> ```
> 
> If so, by how much? I really really hate this syntax

By very little, performance shouldn't be a big concern here.
500000 iterations of a list containing 50 elements:
```
with the typecheck took 7265.44 ms
untyped with type casting took 6637.92 ms
as_anything took 5268.26 ms
```
But there's less boilerplate code involved.
It may be ugly, but I think we'll get used to it fast.

2021-02-08 22:44 UTC, stylemistake commented
I was not suggesting that define seriously. You might remember, that I've also coined refactoring of `1 SECONDS` to `SECONDS(1)`.

2021-02-08 22:48 UTC, Rohesie commented
> 
> 
> I was not suggesting that define seriously. You might remember, that I've also coined refactoring of `1 SECONDS` to `SECONDS(1)`.

That seconds define has the unironic support of every maintainer that has made their opinion public so far, though.
It just takes someone to do the refactor.

2021-02-08 23:06 UTC, Cyberboss commented
Can at least add a grep lint for this? Something like: `for\s*\(\s*var\/[a-zA-Z_][a-zA-Z0-9_]*\s+(?!as\s+anything).+`

2021-02-08 23:11 UTC, Cyberboss commented
Bit of an oof to setup
![image](https://user-images.githubusercontent.com/8171642/107293107-06852000-6a39-11eb-96e4-486d466bcc2f.png)

2021-02-08 23:11 UTC, Rohesie commented
> 
> 
> Can we at least add a grep lint for this? Something like: `for\s*\(\s*var\/[a-zA-Z_][a-zA-Z0-9_]*\s+(?!as\s+anything\s+)in\s+.+\)`

To what end?
This catches things like `for(var/i in min(x1, x2) to max(x1, x2))` which is fine, as numbers don't have types.
Plus things like this that are not in immediate need of being typed (though it would add clarity if they were):
```dm
for(var/R in D.make_reagents)
	beaker.reagents.add_reagent(R, D.make_reagents[R])
```

2021-02-08 23:21 UTC, MrDoomBringer requested changes

2021-02-08 23:21 UTC, MrDoomBringer commented on .github/CONTRIBUTING.md
> +Typecasting in `for` loops carries and implied `istype()` check that filters non-matching types, nulls included. The `as anything` key can be used to skip the check.
```suggestion
Typecasting in `for` loops carries an implied `istype()` check that filters non-matching types, nulls included. The `as anything` key can be used to skip the check.
```

2021-02-08 23:21 UTC, MrDoomBringer commented on .github/CONTRIBUTING.md
> +Nulls in lists tend to point to improperly-handled references, which cause hard deletes are are hard to debug. Generating a runtime on those cases is more often than not positive.
```suggestion
Nulls in lists tend to point to improperly-handled references, making hard deletes hard to debug. Generating a runtime in those cases is more often than not positive.
```

2021-02-08 23:38 UTC, LemonInTheDark commented
> By very little, performance shouldn't be a big concern here.

If this is purely a code cleanliness thing I'm not in favor of standardizing it. I think we just disagree here, but just because it's a byond feature that doesn't mean we should use it. This looks like a straight downgrade in terms of readability to me.

2021-02-09 05:33 UTC, spookydonut commented
> 
> 
> > By very little, performance shouldn't be a big concern here.
> 
> If this is purely a code cleanliness thing I'm not in favor of standardizing it. I think we just disagree here, but just because it's a byond feature that doesn't mean we should use it. This looks like a straight downgrade in terms of readability to me.

using this syntax over former typeless loop syntax removes two byte code operations per loop iteration, get+set.

according to zewaka it can have a huge performance impact.

2021-02-09 05:54 UTC, optimumtact commented
according to zewaka eh

2021-02-09 06:40 UTC, LemonInTheDark commented
Is it a cleanliness thing then? or is it a performance meme. If we're gonna standardize this we should know why

2021-02-09 15:08 UTC, Cyberboss commented
I don't doubt we might get some small gain by replacing all ~4k fors with this. It does make readability a PITA though, which is why I still honestly support the `OF` define.

2021-02-09 18:53 UTC, Rohesie commented
To me it's a cleanliness thing
```dm
for(var/obj/item/radio/radio as anything in radios)
	radio.stuff()
```
is much cleaner than
```dm
for(var/r in radios)
	var/obj/item/radio/radio = r
	radio.stuff()
```
Less boilerplate code overall, and `as flag` being something we already use elsewhere in the code.
We don't have issues with things like this, right?
`var/crystals = input("Amount of telecrystals for [key]","Syndicate uplink", U.telecrystals) as null | num`

2021-02-09 20:47 UTC, LemonInTheDark commented
I personally find that syntax very confusing, even for input(), and I think it hurts understanding at a glance or hell even after explanation. Lines of code != complexity. Even with minor performance benefits I don't support this

2021-02-09 21:46 UTC, stylemistake commented
You will get used to it.

2021-02-09 21:59 UTC, LemonInTheDark commented
My concern is the people learning our codebase, I want the process of reading our code to be as painless as humanly possible, and adding a byondism to for loops is just gonna confuse people, even if it's possible to get used to.

2021-02-09 22:02 UTC, optimumtact commented
suck it up buttercup

2021-02-09 23:01 UTC, LemonInTheDark commented
You're right, it's depressing, but you're right

2021-02-11 19:20 UTC, Cyberboss commented
It is what it is then.

2021-02-11 19:21 UTC, merged