Glowcap spread is limited to 3 generations.
tgstation/tgstation pull request #56885
Opened 2021-02-12 15:44 UTC by MLGTASTICa

## About The Pull Request
Adds a hardlimit to how much glowcap can spread.If maintainers demand it i can make it based off potency or a config option.
## Why It's Good For The Game
Stops glowcaps from overtaking the station , reduces subsequent lag that comes from all the lightning that has to be calculated.

## Changelog
:cl:
tweak: Glowcaps have received a limit on how many generations they can produce , which is only 3.
/:cl:

2021-02-12 15:45 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -38. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-12 15:49 UTC, coiax commented
> config option

Oh no

2021-02-12 15:49 UTC, interestingusernam3 commented
tweak

2021-02-12 15:50 UTC, Krysonism commented
There is already a cap on how many generations can spread, it is called endurance.

A better solution would have glowshrooms lose endurance faster.

2021-02-12 15:51 UTC, interestingusernam3 commented
How the hell do you have -38 GBP at the time of your first contribution to the codebase ever?

2021-02-12 15:52 UTC, MLGTASTICa commented
> How the hell do you have -38 GBP at the time of your first contribution to the codebase ever?

Contributed on TGMC.

2021-02-12 15:59 UTC, MLGTASTICa commented
> There is already a cap on how many generations can spread, it is called endurance.
> 
> A better solution would have glowshrooms lose endurance faster.

Yes , but on a downstream it has happened quite frequently that glowshrooms go over 10+ generations which is not fine for performance . Im also assuming that the botany interactions are still being called on the glowshrooms which makes them recover potency/yield .  They also have a chance to receive more yield which makes them roll more times for spreading.

2021-02-12 16:04 UTC, NotRanged commented
Make it scale with stats like endurance/production/potency and add some logging to INVESTIGATE_BOTANY about planting them perhaps

2021-02-13 20:34 UTC, Jared-Fogle commented
> If maintainers demand it i can make it based off potency or **a config option**.

you're a card 😊

2021-02-13 20:35 UTC, Jared-Fogle commented on code/game/objects/effects/glowshroom.dm
> +	if(generation>2)
Magic number, move it to a define.

2021-02-14 05:03 UTC, MLGTASTICa commented on code/game/objects/effects/glowshroom.dm
> +	if(generation>2)
Moved it to a define in botany defines.

2021-02-15 02:19 UTC, Mothblocks commented
what @Krysonism said though

2021-02-15 05:37 UTC, Mothblocks requested changes
There is already a cap on how many generations can spread, it is called endurance.

A better solution would have glowshrooms lose endurance faster.

2021-02-15 06:30 UTC, MLGTASTICa commented
> There is already a cap on how many generations can spread, it is called endurance.
> 
> A better solution would have glowshrooms lose endurance faster.

Done , they now lose 10 times more endurance.

2021-02-15 20:51 UTC, Mothblocks commented on code/game/objects/effects/glowshroom.dm
> +			Decay(TRUE, 20) // Decay before spawning new mushrooms to reduce their endurance
Move to define, then it's good.

2021-02-15 22:00 UTC, MLGTASTICa commented on code/game/objects/effects/glowshroom.dm
> +			Decay(TRUE, 20) // Decay before spawning new mushrooms to reduce their endurance
Done

2021-02-15 22:10 UTC, merged

2021-02-15 22:10 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-46). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.