Fixed customizable reagent holders for held holders
tgstation/tgstation pull request #56932
Opened 2021-02-15 05:42 UTC by swindly

## About The Pull Request

Changes customizable_reagent_holder to put the new parent item in the hands of the attacker when the old parent is being held by the attacker.

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/56544

## Changelog
:cl:
fix: Fixed tablecrafted foods being put inside their creators when they are held.
/:cl:

2021-02-15 05:43 UTC, Mothblocks requested changes

2021-02-15 05:43 UTC, Mothblocks commented on code/datums/components/customizable_reagent_holder.dm
> +			var/obj/item/I = atom_parent
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-02-15 05:43 UTC, Mothblocks commented on code/datums/components/customizable_reagent_holder.dm
> +				var/obj/item/R = replacement_parent
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-02-15 05:55 UTC, Mothblocks commented
Undraft your PR when it is ready (and passes linters).

2021-02-15 20:52 UTC, Mothblocks commented on code/datums/components/customizable_reagent_holder.dm
> +				attacker.put_in_hand(replacement_item, attacker.get_held_index_of_item(old_item), TRUE)
Use a named argument for `TRUE`.

2021-02-15 22:10 UTC, Mothblocks approved these changes

2021-02-15 22:12 UTC, Mothblocks reviewed
wait mmm actually i dont know if i like that force

is there any reason you're not doing something like deleting/nullspacing the existing item? can i get an understanding at the thought process here?

2021-02-15 22:18 UTC, swindly commented
The existing item needs to continue existing after the replacement item is created so that the component can be transferred. The existing item gets deleted a few lines later.

2021-02-15 23:40 UTC, Mothblocks commented
It gives me pause when it comes to things like NODROP. I think you should instead call `dropItemToGround` or whatever the proc is directly, and handle the fail state of that.

2021-02-16 00:14 UTC, swindly commented
Copying flags like NODROP to the replacement parent and adding conditions on which to fail to delete the old item will change the behavior of food tablecrafting.

2021-02-16 00:14 UTC, closed without merging