you can now cast rituals on 100 threat dynamic
tgstation/tgstation pull request #56961
Opened 2021-02-16 10:22 UTC by Fikou

## About The Pull Request

wizards on 100 threat dynamic can now cast summon guns, magic and events

## Why It's Good For The Game

the round is already chaos and is gonna end in 10 minutes, and the wizard events once in a year would be pretty fun i think

## Changelog
:cl:
add: you can now cast rituals on dynamic if the threat level is 100
/:cl:

2021-02-16 10:23 UTC, Mothblocks requested changes

2021-02-16 10:23 UTC, Mothblocks commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +#define MINIMUM_THREAT_FOR_RITUALS 100
undef at the end

2021-02-16 10:45 UTC, nianjiilical commented
make sure theres a notification since most wizards probably arent going to check the rituals page every round on the tiny chance theyre castable

2021-02-16 11:13 UTC, necromanceranne commented
Cowabunga it is.

2021-02-16 19:31 UTC, oklews commented
This is where we add a button to make the threat level 100 right?

2021-02-16 19:41 UTC, RaveRadbury commented
> This is where we add a button to make the threat level 100 right?

**Open** wizard spell to make threat 100

2021-02-16 21:55 UTC, Mothblocks approved these changes

2021-02-17 00:32 UTC, Timberpoes approved these changes

2021-02-17 10:39 UTC, merged