Cleans up bee code very slightly, doesn't allow unsynthisisable chems to be put in bees
tgstation/tgstation pull request #56995
Opened 2021-02-17 10:14 UTC by LemonInTheDark

## About The Pull Request

Updates some documentation, makes bee synth respect the can synth flag, and implements early returns in one proc properly.

## Why It's Good For The Game

Honestly I initially did this cause of the synth thing, but at this point I care more about the early returns. Or maybe that's the nightcode talking.

Oh also I updated some documentation, yadeyada, comments do not compile all that.
This kills the tactical romeral bee

## Changelog
:cl:
balance: Bees can no longer synthesize forbidden chemicals. Looking at you romeral (Did I spell that right?)
/:cl:

2021-02-17 10:20 UTC, coiax requested changes

2021-02-17 10:20 UTC, coiax commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +	var/obj/item/reagent_containers/syringe/S = I
Under new contributing guidelines, you should use more informative variable names.

2021-02-17 10:20 UTC, coiax commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +		S.reagents.remove_reagent(R.type,5)
```suggestion
		S.reagents.remove_reagent(R.type, 5)
```

2021-02-17 10:20 UTC, coiax commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +		S.reagents.remove_reagent(R.type,5)
also probably more with the variable renaming

2021-02-17 10:20 UTC, coiax commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +	to_chat(user, "<span class='warning'>You don't have enough units of that chemical to modify the bee's DNA!</span>")
Probably move this line to an early return, and have the "mutating bee DNA" be at the very bottom.

2021-02-17 10:20 UTC, coiax commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +	var/datum/reagent/R = GLOB.chemical_reagents_list[S.reagents.get_master_reagent_id()]
Same here on "informative variable names"

2021-02-17 12:10 UTC, Mothblocks commented on code/modules/mob/living/simple_animal/hostile/bees.dm
> +		var/obj/item/queen_bee/qb = new(user.drop_location())
Under new contributing guidelines, you should use more informative variable names.

2021-02-17 12:10 UTC, Mothblocks commented on code/modules/reagents/chemistry/fermi_readme.md
> +#define REAGENT_DEAD_PROCESS (1<<0)	//allows on_mob_dead() if present in a dead body
```suggestion
#define REAGENT_DEAD_PROCESS (1<<0) //allows on_mob_dead() if present in a dead body
```

2021-02-17 12:10 UTC, Mothblocks commented on code/modules/reagents/chemistry/fermi_readme.md
> +#define REAGENT_SPLITRETAINVOL (1<<4)  //Retains initial volume of chem when splitting for purity effects
```suggestion
#define REAGENT_SPLITRETAINVOL (1<<4) //Retains initial volume of chem when splitting for purity effects 
```

2021-02-17 14:58 UTC, TemporalOroboros commented
And so the hugboxing begins.

2021-02-17 16:34 UTC, Fikou commented
hugbox BOOOOOOOOOOOOOOOOOO

2021-02-17 19:28 UTC, ATH1909 commented
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

2021-02-17 19:28 UTC, ATH1909 commented
also it's romerol

2021-02-18 00:23 UTC, LemonInTheDark commented
> 
> 
> also, it's spelled "romerol"

Thank you

2021-02-18 08:39 UTC, LemonInTheDark commented
> 
> 
> NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> 
> I don't suppose it'd be possible to just make bees not produce can_synth = FALSE chems in honey combs, while still allowing them to sting people with them? I like nanomachine bees...

I mean feel free to pr that, I'm mostly doing this cause of the inconsistency, if something can't be synthesized it shouldn't be able to be mass produced or distributed. I wouldn't even block it, like I said most of the reason I made this pr is the code stinking so hard

2021-02-28 09:48 UTC, LemonInTheDark commented
Ew, the bee's gone stale

2021-03-08 00:44 UTC, closed without merging