brand_intelligence no longer makes explosions which make holes in station
tgstation/tgstation pull request #57038
Opened 2021-02-19 14:34 UTC by Tlaltecuhtli

:cl:
tweak: brand_intelligence event no longer has 70% prob of making a hole for every vending machine
/:cl:

the random holes in the whole station are just bad as it depressurizes whole departments at the same time and its more dangerous than the vending machine, no air event exists and its called meteors

2021-02-19 14:37 UTC, Qustinnus commented
1. It's a 30% chance
2. this now makes every vending machine hostile rather than 70%

2021-02-19 14:53 UTC, Pugie commented
sounds more fun... 30% chance is still resulting in a lot of explosions (need I explain why?), and with the current state of atmos that's awful for the station I'd absolutely take 100% evil satan vendors over evil hell has frozen over due to coldmos vendors.

2021-02-19 15:04 UTC, Tlaltecuhtli commented
i prefer 30% more funny vendors than gasping and firelocks closing in the halls every time this event happens

2021-02-19 15:09 UTC, Fikou commented
tweake tag no longer exist.....

2021-02-19 17:20 UTC, Qustinnus commented
It's not that I disagree with the change, moreso that the change log shouldn't lie about the changes

2021-02-19 17:58 UTC, Pugie commented
lie or mistake?

2021-02-19 18:22 UTC, Qustinnus commented
really dumb mistake if its the case, and it's not the first time tlalt has hidden things in his PRs or purposefully left out info.

2021-02-20 23:09 UTC, Mothblocks requested changes
make the changelog accurate in the way floyd said

2021-02-22 01:38 UTC, Mothblocks commented
> this now makes every vending machine hostile rather than 70%

this needs to be in the changelog

2021-02-26 03:41 UTC, LemonInTheDark commented
Sounds good to me, hull breaches shouldn't happen randomly like this

2021-02-26 03:54 UTC, merged