Adds cooldown feedback to emotes
tgstation/tgstation pull request #57114
Opened 2021-02-22 07:03 UTC by Ryll-Ryll

## About The Pull Request
When I added a 3 second cooldown to the *kiss emote, some people got confused about why the emote would sometimes fail to work, because it turns out there's no message telling you an emote is on cooldown. This adds a message telling you to hold your horses a bit longer, and for how long those horses need to be held.

This message will only be displayed if it's an emote that has a cooldown of at least 1 second, because if you're managing to trigger the standard 0.8 second cooldown, you're probably just mashing a hotkey and not paying attention to the chat anyway

## Why It's Good For The Game
Improved feedback

## Changelog
:cl: Ryll/Shaps
qol: Trying to use an emote while it's cooling down will now tell you how much longer you have to wait. This will only show for emotes with longer than normal wait times.
/:cl:

2021-02-22 07:09 UTC, tralezab reviewed
![image](https://user-images.githubusercontent.com/40974010/108674251-d35f7980-7499-11eb-9d3f-8316739b3f8b.png)

2021-02-22 07:09 UTC, tralezab commented on code/datums/emotes.dm
> +		to_chat(user, "<span class='danger'>You must wait another [(user.emotes_used[src] - world.time + cooldown) * 0.1] seconds before using that emote.</span>")
You should use [DisplayTimeText(user.emotes_used[src] - world.time + cooldown)] instead!

The helper proc is in time.dm:76

2021-02-22 09:58 UTC, Mothblocks commented on code/datums/emotes.dm
> +		if(cooldown >= 1 SECONDS)
Move this magic number out to a define.

2021-02-22 09:58 UTC, Mothblocks commented on code/datums/emotes.dm
> +		if(cooldown >= 1 SECONDS)
Or, honestly, just check `> initial(cooldown)`.

2021-02-22 10:06 UTC, Mothblocks commented on code/datums/emotes.dm
> +		if(cooldown >= 1 SECONDS)
(Note the `=` removal)

2021-02-23 12:00 UTC, Mothblocks requested changes
da review

2021-02-24 03:03 UTC, Mothblocks commented
undraft if ready

2021-02-26 09:25 UTC, merged