Spiders on web now ignore an absence of gravity.
tgstation/tgstation pull request #57129
Opened 2021-02-23 01:07 UTC by Gurkenglas

## About The Pull Request

Being on a web (not next to one, as is the case with rods in space) lets spiders ignore an absence of gravity.

## Why It's Good For The Game

It's in-flavor and it lets broodmothers that spawn into zero gravity lay a web to move around. Yes, I'm salty.

## Changelog
:cl:
add: Spiders on web now ignore an absence of gravityy.
/:cl:

2021-02-23 02:51 UTC, Cyberboss requested changes
Nice work

2021-02-23 02:51 UTC, Cyberboss commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	return (. || web)
Avoiding the locate if possible.

```suggestion
	. = ..()
	if (.)
		return
	var/obj/structure/spider/stickyweb/web = locate() in loc
	return web
```

2021-02-23 02:52 UTC, bluetshirtguy commented
Spiders are pretty dangerous as is.

2021-02-23 03:16 UTC, LemonInTheDark commented
Has god damn soul, finally some good ided prs

2021-02-23 05:10 UTC, Mothblocks commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	return (. || web)
```suggestion
	return ..() || (locate(/obj/structure/spider/stickyweb) in loc)
```

...works too 😄

2021-02-23 21:13 UTC, Mothblocks approved these changes

2021-02-24 02:00 UTC, merged

2021-02-24 02:00 UTC, tgstation-server commented
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

2021-02-24 02:13 UTC, ATH1909 commented
we could probably let this work for spiders who're standing next to webs as well, tbh