Miscellaneous appearance fixes.
tgstation/tgstation pull request #57133
Opened 2021-02-23 06:23 UTC by TemporalOroboros

## About The Pull Request
- Fixes massive modular computer runtimes caused by giving update_icon args it cares about.
- Fixes mind magnification helmets being errors
- Fixes the bloody hands overlay being applied to people without hands
- Fixes removing accessories also temporarily removing the bloodsplatter overlay from clothes.
- Assorted other code tweaks.

## Why It's Good For The Game
- Less bugs

## Changelog
:cl:
fix: A recent firmware update reenabled the screens on Nanotransen brand computers.
fix: Bloodsplatter no longer experiences phantom limb syndrome on people missing both of their arms.
fix: Recent budget cuts have resulted in accessories no longer having magnets strong enough to pull bloodstains directly out of clothing. Washing machine usage has jumped 50% over the last week.
fix: No one is entirely certain who injected the the design schema for neon error signs into the mind magnification helmet production line, but the affected units have been recalled and the perpetrator <i>will</i> be brought to justice.
/:cl:

2021-02-23 08:17 UTC, TemporalOroboros commented
Oh right. Fixes #57102, fixes #57087, fixes #57078.

2021-02-24 10:40 UTC, Mothblocks requested changes

2021-02-24 10:40 UTC, Mothblocks commented on code/modules/clothing/under/_under.dm
> +	var/obj/item/clothing/accessory/A = I
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-02-24 10:40 UTC, Mothblocks commented on code/modules/clothing/under/_under.dm
> +	var/obj/item/clothing/accessory/A = attached_accessory
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-02-24 10:40 UTC, Mothblocks commented on code/modules/clothing/under/_under.dm
> +	var/mob/living/carbon/human/H = loc
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-02-24 10:40 UTC, Mothblocks commented on code/modules/modular_computers/computers/machinery/modular_computer.dm
> +/obj/machinery/modular_computer/proc/relay_icon_update(obj/item/modular_computer/processor/source, updates, updated)
```suggestion
/obj/machinery/modular_computer/proc/relay_icon_update(datum/source, updates, updated)
```

I'm pretty sure it is not guaranteed that your source will be what you expect it to be in this case, anything else could update the icon.

2021-02-24 10:41 UTC, Mothblocks commented
> Oh right. Fixes #57102, fixes #57087, fixes #57078.

Then put it in the body, GitHub only checks the PR body.

2021-02-26 03:21 UTC, LemonInTheDark commented
> 
> 
> Oh right. Fixes #57102, fixes #57087, fixes #57078.

Put it in the pr desc so it'll auto close pls I'm begging you

2021-03-02 23:18 UTC, merged