Adds a new type of botany experiment that tests plants.
tgstation/tgstation pull request #57166
Opened 2021-02-24 15:37 UTC by ArcaneMusic

## About The Pull Request

Adds two new experiments, the plant trait experiment and the wild mutation plant experiment which boosts experimental surgery and the botany node respectively.

The wild mutation experiment is rather simple, and actually helps teach players on how to use wild experiments in order to get free mutations out of plants without having to fiddle with instability for as long. Just go and use the deconstructive scanner (which is a public machine on each map) with a plant that was mutated with this method, and the botany node is now cheaper.

The plant trait experiment looks for a few plants with a collection of random traits, all selected from some of the harder traits to aquire. You might need to acquire some plants with googly eyes, or shadowshrooms, or perhaps even prickly adhesion. Regardless, any plant with one of the requested traits will be all it takes, and it boosts the surgery node.

## Why It's Good For The Game

This gives botany another way to interact with the crew, makes their own stuff a little cheaper if science is being cheapstakes, and gives a neat framework to enable botany to hit unique milestones within the round to benefit the rest of the crew. More per-round engagement and inter-departmental cooperation creates a more lively round. Plus it gives the new and old botany powergamers something to do that isn't feeding toxic soybeans into the tapwater.

## Changelog
:cl:
add: There are now two experiments that botany can perform that boosts botany tech and experimental surgery.
/:cl:

2021-02-24 15:54 UTC, bobbahbrown commented
@Qustinnus worth taking a peek when you get a chance

2021-02-24 16:03 UTC, Qustinnus requested changes

2021-02-24 16:03 UTC, Qustinnus commented on code/modules/experisci/experiment/types/scanning_plants.dm
> +		return ..() && crop?.seed.get_gene(required_genes[typepath])
crop cant be nul lhere

2021-02-24 16:03 UTC, Qustinnus commented on code/modules/research/techweb/all_nodes.dm
> +	discount_experiments = list(/datum/experiment/scanning/random/plants/traits = 2500)
personal rpeference is that you increase the cost of the node as well so its more likely people will do the experiment

2021-02-24 16:03 UTC, Qustinnus commented on code/modules/research/techweb/all_nodes.dm
> +	discount_experiments = list(/datum/experiment/scanning/random/plants/traits = 2500)
(and then make it so that the experiment cuts out a bigger portion of that cost)

2021-02-24 19:07 UTC, Qustinnus approved these changes

2021-02-25 23:24 UTC, Mothblocks commented on code/__DEFINES/traits.dm
> +#define TRAIT_PLANT_WILDMUTATE "wildmutation" //Plants that were mutated as a result of passive instability, not a mutation threshold.
```suggestion
/// Plants that were mutated as a result of passive instability, not a mutation threshold.
#define TRAIT_PLANT_WILDMUTATE "wildmutation"
```

Doc comments.

2021-02-25 23:35 UTC, merged