RangedAttack now takes modifiers.
tgstation/tgstation pull request #57214
Opened 2021-02-26 17:08 UTC by Gurkenglas

## About The Pull Request

The RangedAttack proc 

## Why It's Good For The Game

RangedAttack was passing `params` in place of `modifiers` to `Touch`. This caused (harmless) runtimes whenever a ninja would click more than one tile from himself using his gloves. https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/bot/firebot.dm#L75 already expects `modifiers`, though it wasn't using it.

No changelog since the player doesn't see this.

2021-02-26 17:09 UTC, tgstation-server commented
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-02-27 08:32 UTC, Mothblocks requested changes
I told you why it's not passed, `params2list` can never return null, it'll always return a list. **This means we can call it directly without having to create a list of our own every time we call.** It is possible for attack_\* and friends to be called outside the attack chain. This was an intentional decision by Floyd, I remember talking to them about it.

Fix the ninja code to use params2list.

2021-02-27 10:45 UTC, Mothblocks commented
Nevermind, I concede, **as long as every access of this uses LAZYACCESS**.

2021-02-27 10:51 UTC, Mothblocks approved these changes

2021-02-28 03:55 UTC, merged