Announced Extended now sends a report for station traits + minor punctuation cleanup
tgstation/tgstation pull request #57224
Opened 2021-02-26 20:20 UTC by MrMelbert

## About The Pull Request

- Fixes two minor punctuation errors in station traits.
- Announced greenshifts now send a command report so players can figure out what station traits may be affecting the station.
- Changed some code in game_mode and dynamic `send_intercept()` to be their own procs to reduce copy+paste.

## Why It's Good For The Game

Announced greenshifts aren't run normally / are admin only but if they happen to be ran, and the station has traits, the crew should be able to know what they're affected with.

## Changelog
:cl: Melbert
qol: Announced Extended shifts now send a command report listing station traits.
spellcheck: Fixed some punctuation in station trait reports.
/:cl:

2021-02-26 20:28 UTC, MrMelbert commented on code/game/gamemodes/game_mode.dm
> -				return
Turns out for normal gamemodes, the fix for station traits blocking reports was never mirrored over 🥴

2021-02-28 03:48 UTC, Mothblocks requested changes

2021-02-28 03:48 UTC, Mothblocks commented on code/game/gamemodes/game_mode.dm
> +		. += G.get_report()
```suggestion
	for(var/datum/station_goal/station_goal in station_goals)
		station_goal.on_report()
		. += station_goal.get_report()
```

2021-02-28 03:48 UTC, Mothblocks commented on code/game/gamemodes/game_mode.dm
> +		. += "[station_trait_iterator.get_report()]<BR>"
```suggestion
	for(var/datum/station_trait/station_trait as anything in SSstation.station_traits)
		if(!station_trait.show_in_report)
			continue
		. += "[station_trait.get_report()]<BR>"
```

2021-02-28 03:48 UTC, Mothblocks commented on code/game/gamemodes/game_mode.dm
> +/datum/game_mode/proc/generate_station_goal_report()
Document.

2021-03-02 23:50 UTC, merged