Right-click to remove carbon-copies
tgstation/tgstation pull request #57402
Opened 2021-03-03 22:30 UTC by mozi-h

## About The Pull Request
- Enforce Right-click to tear off a carbon copy instead of any click.
- Add examine text to explain this

## Why It's Good For The Game
Prevents accidental premature ripping off of carbon copies. HoPs hate(d) this!
Also improves consistency.

## Changelog
:cl: mozi_h
qol: Carbon-copies can now only be removed with a right-click. HoPs, you are welcome (yet again)!
/:cl:

2021-03-03 22:31 UTC, RaveRadbury commented
Paperwork hero

2021-03-03 22:34 UTC, mozi-h commented
> Paperwork hero

My work is not done yet!
![grafik](https://user-images.githubusercontent.com/19172408/109881568-ce0fe500-7c78-11eb-8528-ed0124ef4764.png)

2021-03-04 02:46 UTC, maxymax13 commented
do "much needed paperwork improvement" prs count as hop buffs

2021-03-04 06:03 UTC, itseasytosee commented
Buffing paperwork is not a quality of life for bureaucrats.

2021-03-05 09:47 UTC, Mothblocks requested changes

2021-03-05 09:47 UTC, Mothblocks commented on code/modules/paperwork/carbonpaper.dm
>  /obj/item/paper/carbon/attack_hand(mob/living/user, list/modifiers)
Change this to `/attack_hand_secondary`, perform your behavior, then return CANCEL_ATTACK_CHAIN.

2021-03-05 09:47 UTC, Mothblocks commented on code/modules/paperwork/carbonpaper.dm
>  /obj/item/paper/carbon/attack_hand(mob/living/user, list/modifiers)
Or rather, add `/attack_hand_secondary` instead of using modifiers.

2021-03-06 00:25 UTC, Mothblocks commented
Undraft if ready.

2021-03-07 01:29 UTC, merged