Adds Mexican tourists to the restaurant system, plus some QOL tweaks.
tgstation/tgstation pull request #57447
Opened 2021-03-05 00:36 UTC by ArcaneMusic

## About The Pull Request

Alright, brass tacks, adds new Mexican tourists to the restaurant. Their orders are fairly traditional spanish and mexican food, their dialog sound is some pretty classy spanish guitar, and by god they care about football. REAL football.

This also created a few QOL tweaks that I noticed and changed along the way:

- Chef Holosign creator for restaurant seating didn't look very unique due to using the standard holosign sprite, so I gave it a nice recolor with a bright white and red restaurant pattern on an edge to help it stand out a bit.
- The two taco recipies have been given a minor name tweak, which actually already existed in the crafting menu, but didn't change the names of the two tacos, so now the actual food tacos are classic tacos ( Cheese, meat, cabbage, tortilla) and plain tacos (tortilla, cheese, meat).

## Why It's Good For The Game

Adds more variety to the restaurant system, keeps it tasteful in flavor and the foods themselves aren't cooked very often on station, so this helps bump up food variety on the whole.
Helps to distinguish the existing food on station a bit with the variable name, and helps to make the venue specific aspects of the restaurant system stand out a tiny bit more.

## Changelog
:cl:
add: There are now space tourists from south of the border. Andele!
qol: The two taco recipes are now distinguished by name in game to help tell the two apart.
imageadd: The Restaurant Holoseat Creator now uses a slightly different sprite to help it stand out.
/:cl:

Demo Video (Note: this was the exact moment I realized I needed to change the name):
https://discord.com/channels/326822144233439242/326831214667235328/817188033446412290

2021-03-05 01:10 UTC, tralezab commented
damn NICE

2021-03-05 11:54 UTC, Ghommie requested changes
Bettering this hollywood spanish a little.

2021-03-05 11:54 UTC, Ghommie commented on code/modules/food_and_drinks/restaurant/customers/_customer.dm
> +	found_seat_lines = list("Como te va, space station 13?", "Who's ready to party!", "Ah, muchos gracias.", "Ahhh, smells like mi abuela's cooking!")
```suggestion
	found_seat_lines = list("¿Como te va, space station 13?", "Who's ready to party!", "Ah, muchas gracias.", "Ahhh, smells like mi abuela's cooking!")
```

2021-03-05 11:54 UTC, Ghommie commented on code/modules/food_and_drinks/restaurant/customers/_customer.dm
> +	cant_find_seat_lines = list("En Serio? Seriously, no seats?", "Andele! I want a table to watch the football match!", "Ay Caramba...")
```suggestion
	cant_find_seat_lines = list("¿En Serio? Seriously, no seats?", "Andele! I want a table to watch the football match!", "Ay Caramba...")
```

2021-03-05 11:54 UTC, Ghommie commented on strings/names/mexican_prefix.txt
> +Conqustador
That's a typo.
```suggestion
Conquistador
```

2021-03-05 11:54 UTC, Ghommie commented on code/modules/food_and_drinks/restaurant/customers/_customer.dm
> +	leave_mad_lines = list("Aye dios mio, I'm out of here.", "Esto es ridiculo! I'm leaving!", "I've seen better cooking at taco campana!", "I though this was a restaurant, pero es porqueria!")
```suggestion
	leave_mad_lines = list("Aye dios mio, I'm out of here.", "Esto es ridículo! I'm leaving!", "I've seen better cooking at taco campana!", "I though this was a restaurant, pero es porquería!")
```

2021-03-05 11:54 UTC, Ghommie commented on strings/names/mexican_prefix.txt
> +Senor
```suggestion
Señor
```

2021-03-05 12:01 UTC, Pugie commented
Sure, boss, this sounds good.

2021-03-05 20:48 UTC, maxymax13 commented
all these restaurant costumer prs never give any love to the bartender part

2021-03-05 21:48 UTC, ArcaneMusic commented
> all these restaurant costumer prs never give that much love to the bartender part

Any suggestions to keep it more neutral? Admittedly I probably lean closer towards food than drinks here.

2021-03-06 03:06 UTC, tralezab commented
I think that's something qust is gonna have to address at some time in the future in general, every single customer is like that

2021-03-06 18:19 UTC, Twaticus approved these changes

2021-03-07 01:39 UTC, merged