Space Dragon Gust on Right Click
tgstation/tgstation pull request #57451
Opened 2021-03-05 06:50 UTC by IndieanaJones

## About The Pull Request

This PR removes the button on Space Dragon's UI to use Wing Gust and maps the ability to right-click instead.

## Why It's Good For The Game

Combat mode being merged has opened up the ability to map simplemob powers to right click instead of clunky UI buttons which can sometimes be cumbersome in the midst of heated combat.  Since Space Dragon is a relatively simple example of doing this, here it is.

## Changelog
:cl:
del: Space Dragon's gust ability button has been removed
qol: Space Dragon's gust ability is now triggered using right click
/:cl:

2021-03-05 19:52 UTC, tralezab commented
God I love right click shit

2021-03-06 22:51 UTC, Mothblocks requested changes

2021-03-06 22:51 UTC, Mothblocks commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +/mob/living/simple_animal/hostile/space_dragon/RangedAttack(atom/target, modifiers)
Same advice on the spider PR. I think this should be abstracted into a `ranged_attack_secondary`.

I would recommend making that its own PR, which I can merge before these two as soon as it's ready.

2021-03-06 22:51 UTC, Mothblocks commented on code/modules/mob/living/simple_animal/hostile/space_dragon.dm
> +	..()
Same advice here--I think it's weird when right-click also does the same thing as left-click, that's a side effect of BYOND processing clicks through the same chain.

2021-03-21 00:47 UTC, closed without merging