Fixed injection alert on sleepypen. Removed deprecated stealth parameter.
tgstation/tgstation pull request #57479
Opened 2021-03-06 08:52 UTC by KathyRyals

## About The Pull Request

Currently getting stabbed with a pen doesn't alert the stabbed person. This fixes it by removing an unsused parameter that didn't work since the combat refactor, allegedly.

## Why It's Good For The Game

I would like to know when I'm getting injected with 45 units of poison.

## Changelog
:cl:
fix: Pens now alert the stabbed person again.
/:cl:

2021-03-06 11:23 UTC, KathyRyals commented
Squashies.

2021-03-09 11:30 UTC, Mothblocks requested changes

2021-03-09 11:30 UTC, Mothblocks commented on code/modules/paperwork/pen.dm
> +	if(force)	// If the pen has a force value, call the normal attack procs. Used for e-daggers and captain's pen mostly.
```suggestion
	if(force) // If the pen has a force value, call the normal attack procs. Used for e-daggers and captain's pen mostly.
```

No inline tabs.

2021-03-09 11:30 UTC, Mothblocks commented on code/modules/paperwork/pen.dm
> +		return
These comments are useless--they just repeat what the code is already saying. Comments should say why, not what. Just remove them.

2021-03-11 10:30 UTC, merged