Makes pipenet rebuilds yield much more often
tgstation/tgstation pull request #57511
Opened 2021-03-07 06:35 UTC by LemonInTheDark

## About The Pull Request

Basically, pipenet rebuilds were blocking operations. My first commit made them sleep in between full rebuilds, but that didn't really solve the game lag that came from the operation. So I refactored how pipeline rebuilds work so I could split out each expansion step and check in to see if we're overrunning between each one.

The code is mildly pain, but I'm honestly not sure how to make it suck less. Behavior's solid tho.

Oh and a short note, some parts of the code rely on atmos components always having a parent. This wasn't always the case before, but it's more likely now. Shouldn't be that bad, but I need to do an audit regardless. I'm putting this up to run some tests, and get some feedback on the rebuild loop, since it gives me hives.

## Why It's Good For The Game

Yeets a blocking operation, things that cause pipenet rebuilds often, like explosions or the singularity will cause much less TD now.
People will bother me about atmos lagging less.

## Changelog
:cl:
refactor: Things that break pipes will cause much less game lag now. Looking at you singularity
/:cl:

2021-03-07 07:51 UTC, Ghilker commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +/obj/machinery/atmospherics/proc/get_rebuild_canidates()
canidates > candidates

2021-03-07 08:06 UTC, LemonInTheDark commented on code/modules/atmospherics/machinery/atmosmachinery.dm
> +/obj/machinery/atmospherics/proc/get_rebuild_canidates()
WHOOOP

2021-03-07 09:12 UTC, LemonInTheDark commented
I've added a var like `turf/open/var/excited` to prevent list blaot

2021-03-09 11:28 UTC, Mothblocks requested changes

2021-03-09 19:43 UTC, LemonInTheDark commented on code/modules/atmospherics/machinery/datum_pipeline.dm
> +	else
I think that'd make things hard to read too, but I'll do it if you insist

2021-03-09 19:43 UTC, LemonInTheDark commented on code/controllers/subsystem/air.dm
> +		for(var/datum/pipeline/boi as anything in targets)
honestly I wasn't sure what to call em. Maybe to_rebuild?

2021-03-10 09:32 UTC, merged