Kills all the remaining var-edited scrawny spiders
tgstation/tgstation pull request #57579
Opened 2021-03-09 18:03 UTC by SgtHunk

## About The Pull Request

Replaces the remaining var-edited spiders in Kilo (in the maintenance bank) and the ones in Delta Whiteship which used the same spiders.

## Why It's Good For The Game

I swear to God if I see any more things that should be a subtype and have 6+ variables changed

2021-03-09 18:55 UTC, Ghommie requested changes

2021-03-09 18:55 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	environment_smash = 0
```suggestion
	environment_smash = ENVIRONMENT_SMASH_NONE
```

2021-03-09 18:55 UTC, Ghommie commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	environment_smash = 0
```suggestion
	environment_smash = ENVIRONMENT_SMASH_NONE
```

2021-03-10 12:20 UTC, ATH1909 commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	environment_smash = ENVIRONMENT_SMASH_NONE
```suggestion
	environment_smash = ENVIRONMENT_SMASH_NONE
	gold_core_spawnable = NO_SPAWN
```

2021-03-10 12:22 UTC, ATH1909 commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	maxHealth = 30
```suggestion
	maxHealth = 30
	gold_core_spawnable = NO_SPAWN
```

2021-03-10 22:39 UTC, Cyberboss approved these changes

2021-03-10 22:39 UTC, merged