Refactors and Tguizes Orion Trail arcade machine
tgstation/tgstation pull request #57647
Opened 2021-03-12 02:49 UTC by tralezab

## About The Pull Request

WOW all this for gbp well yeah here.

a few more things: now has an intructions page
lings before had literally no reason to kill people because the worst outcome of lings is that it kills someone anyway, now it's a game over if lings attack
few things have a confirmation prompt when they didn't

pioneers now get funny little moodies to reflect their situation and it goes up and down depending on how fucked they are. purely fluff!

## Why It's Good For The Game

tee goo ey

![image](https://user-images.githubusercontent.com/40974010/110884730-653cf400-829a-11eb-9c0f-5eada63913aa.png)

## Changelog
:cl: tralezazelart
ui: tguized orion trail
code: Orion code maybe less shit?
refactor: Orion Events use datums whew
/:cl:

2021-03-12 02:53 UTC, tralezab commented on code/modules/tgui_panel/tgui_panel.dm
> -	// Other setup
This needs a different pr!

2021-03-12 03:30 UTC, tralezab commented on code/modules/tgui_panel/tgui_panel.dm
> -	// Other setup
#57649

2021-03-13 18:17 UTC, stylemistake commented on code/game/machinery/computer/arcade/arcade.dm
>  	updateUsrDialog()
I don't think this is needed

2021-03-13 22:56 UTC, tralezab commented on code/game/machinery/computer/arcade/arcade.dm
>  	updateUsrDialog()
Good catch, remnant of the old system

2021-03-13 23:09 UTC, tralezab commented
Last thing I need to fix before this is ready for testing/merge: I have some world messages hooked up to the targeted kill button because it's sending in the name of the target to kill but somehow isn't finding it in the execute crew proc

2021-03-13 23:18 UTC, tralezab commented
damn these lints cray cray

2021-03-14 04:33 UTC, Mothblocks requested changes
I have no idea what code you wrote and what you didn't, so it's time to do some editing-maybe-very-old-code. Too many magic numbers, etc.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +			for(var/datum/data/record/R in GLOB.data_core.general)
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +		/datum/orion_event/space_port_raid
```suggestion
		/datum/orion_event/space_port_raid,
```

trailing comma good

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +	var/obj/item/radio/Radio
```suggestion
	var/obj/item/radio/radio
```

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +		gamers[gamer] = -1
Move -1 to a define.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +					if(1) //Engine Parts
Magic number, make this a define.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +					if(1) //Engine Parts
Everything else like it.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +			if(!spaceport_raided && fuel > 5)
Move the 5 out to a define, and use that in the buying too.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +							food -= 5
Magic numbeeeers

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +/obj/machinery/computer/arcade/orion_trail/proc/encounter_event(path, gamer, gamerSkill, gamerSkillLevel, gamerSkillRands)
snake_case

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> + * * path: if we want a specific event, this is the path of the wanted one
There's a lot more arguments than this!

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +		return TRUE
what on earth is going on over here with this indentation

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +	var/list/safe2remove = settlers
`safe_to_remove` ya dork

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +		if(killed_crew >= 4)
This should use a define, or .len, or something to signify that its the number of crew you get.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +		settlermoods[settlers[i]] +=  max(settlers.len + food_mood + supply_mood + changing_mood, 1)
```suggestion
		settlermoods[settlers[i]] += max(settlers.len + food_mood + supply_mood + changing_mood, 1)
```

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +	game = _game
This allows for named arguments. I like it.

```suggestion
/datum/orion_event/New(game)
	. = ..()
	src.game = game
```

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +	var/gamerSkillLevel = 0
snake_case

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +	var/obj/machinery/computer/arcade/orion_trail/game
Weakref, or hook to its deletion to stop hard dels.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> + * * _gamerSkillLevel: gaming skill level of the player
More of the `src.var = var` pattern here, please. Documentation with underscore-prefixed names is weird, and shows off the implementation detail.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		game.food -= ((game.alive + game.lings_aboard)*2)*3
Magic numbers.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		game.food -= ((game.alive + game.lings_aboard)*2)*3
Magic numbers here too.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		event_responses += "Repair Electronics"
I don't like the new-then-comparing strings. Can we make these defines as well? Prevents any possibility of typos and such.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		game.electronics = max(0, --game.electronics)
Don't use the return of `++` or `--`, it's very confusing.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		sleep(10)
`addtimer`.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		F.ScrapeAway()
What the fuck?

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +			T.PlaceOnTop(/turf/open/floor/plating)
What the FUCK?

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +			game.lings_aboard = max(0,--game.lings_aboard)
Don't use the result of `--`.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +			game.lings_aboard = max(0, --game.lings_aboard)
Don't use the result of `--`.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		game.food -= ((game.alive + game.lings_aboard)*2)*3
More magic numbers.

2021-03-14 04:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +					O.target = usr
```suggestion
					var/mob/living/simple_animal/hostile/syndicate/ranged/smg/orion/orion_smg = new(get_turf(src))
					orion_smg.target = usr
```

2021-03-14 04:33 UTC, Mothblocks commented on code/modules/asset_cache/asset_list.dm
> +/datum/asset/spritesheet/proc/ModifyInserted(icon/I)
Better variable names.

2021-03-15 07:02 UTC, optimumtact commented on code/game/machinery/computer/arcade/orion.dm
> +	var/mob/living/carbon/gamer = usr
I know you did the iscarbon check earlier but I think you should do this and then `if(!istype(gamer)) return`
instead as it means it's harder for someone to accidentally remove the iscarbon check without realising the cast exists and blowing shit the fuck up

2021-03-15 07:02 UTC, optimumtact commented on code/game/machinery/computer/arcade/orion.dm
> +			usr?.mind?.adjust_experience(/datum/skill/gaming, xp_gained+1)
use gamer here

2021-03-15 07:02 UTC, optimumtact commented on code/game/machinery/computer/arcade/orion.dm
> +			usr?.mind?.adjust_experience(/datum/skill/gaming, xp_gained+1)
also stop abusing ?, you should only use that where it's actually sensible for the values to be potentially null.

2021-03-15 20:00 UTC, tralezab commented
I need to handle some comments anturk made over discord before merge, mainly making the arcade event datums static

2021-03-16 02:37 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion.dm
> +	/datum/orion_event/black_hole_death,
indeeeent

2021-03-16 22:33 UTC, Mothblocks requested changes
Last one.

2021-03-16 22:33 UTC, Mothblocks commented on code/game/machinery/computer/arcade/orion_event.dm
> +		var/S = new /obj/singularity/academy(gamer.loc)
Better variable name.

2021-03-17 07:10 UTC, merged