Gives clown cars headlights
tgstation/tgstation pull request #57643
Opened 2021-03-12 00:09 UTC by ArcaneDefence

## About The Pull Request
Uses directional lighting as a toggle via an action that only clown car drivers get

## Why It's Good For The Game
**Pros:** 

1. Clowns can see where they're driving
2. Clowns get another button to click and make funny noises to annoy everyone
3. It makes sense to give cars headlights

**Cons:**

1. Clowns can see where they're driving
2. Clowns get another button to click and make that goddamn fucking click never stop

![image](https://user-images.githubusercontent.com/51932756/110871846-5f401680-828c-11eb-9ff4-3684ff9dc3e2.png)
Big light for big energy

## Changelog
:cl:
add: Clown cars are now fitted with functioning headlights!
/:cl:

2021-03-12 02:05 UTC, maxymax13 commented
why is icondiffbot missing

2021-03-13 13:51 UTC, TheVekter commented
Can we make it so emagging the car makes the headlights cycle through the spectrum?

2021-03-13 19:11 UTC, ArcaneDefence commented
> 
> 
> Can we make it so emagging the car makes the headlights cycle through the spectrum?

![image](https://user-images.githubusercontent.com/51932756/111041403-3a1ae780-83f5-11eb-88bb-9450f968bf92.png)

2021-03-14 01:21 UTC, Mothblocks requested changes
Minor nitpick.

2021-03-14 01:21 UTC, Mothblocks commented on code/modules/vehicles/cars/clowncar.dm
> +	if(light_on && obj_flags & EMAGGED )
```suggestion
	if(light_on && (obj_flags & EMAGGED))
```

2021-03-14 01:21 UTC, Mothblocks commented on code/modules/vehicles/cars/clowncar.dm
> +	if(light_on && obj_flags & EMAGGED )
My concerns more with the trailing space, but I just like parentheses around bitops.

2021-03-14 01:21 UTC, Mothblocks commented on code/modules/vehicles/cars/clowncar.dm
> +		return
```suggestion
```

Return is implicit.

2021-03-14 03:07 UTC, merged