Fixes non cultists being able to use cult bolas
tgstation/tgstation pull request #57653
Opened 2021-03-12 04:03 UTC by SuperNovaa41

## About The Pull Request

Fixes non cultists being able to use cult bolas

Fixes #57652 

## Why It's Good For The Game

non cultists shouldnt be able to use blood magic items

## Changelog
:cl:
fix: Fixes crippled non cultists from using cult bola
/:cl:

2021-03-12 04:10 UTC, SuperNovaa41 commented
I'm open to lowering/raising the stun for grabbing it to whatever, I just grabbed a value that was already being used for cult gear

2021-03-12 06:12 UTC, ATH1909 commented on code/modules/antagonists/cult/cult_items.dm
> +		if(user.num_legs <= 1)
```suggestion
		if(C.legcuffed || C.num_legs < 2)
```

2021-03-12 15:46 UTC, SuperNovaa41 commented
changed the stun to the same time as it takes to breakout of bola for consistency

2021-03-13 08:38 UTC, Mothblocks requested changes

2021-03-13 08:38 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +	var/stun = 6 SECONDS
Make it a define.

2021-03-13 08:38 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +/obj/item/restraints/legcuffs/bola/cult/attack_hand(mob/living/carbon/user, list/modifiers)
This can't be guaranteed. Just check `iscarbon`.

2021-03-14 00:54 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +			var/mob/living/carbon/C = user
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

Rename this `carbon_user` or similar.

2021-03-14 01:28 UTC, Mothblocks commented
Undraft if ready.

2021-03-14 01:29 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +		if(iscarbon(user))
Last change--make these one if statement and early return.

i.e.

```dm
if (iscultist(user) || !iscarbon(user))
    return
```

2021-03-14 02:00 UTC, merged