Bane AI
tgstation/tgstation pull request #57771
Opened 2021-03-16 20:38 UTC by tralezab

## About The Pull Request
### "Bane?"
![image](https://user-images.githubusercontent.com/40974010/111376376-9cc1ec80-865c-11eb-9018-d32a130c97e5.png)

## Why It's Good For The Game

We take Gotham from the corrupt! The rich! The oppressors of generations who have kept you down with myths of opportunity, and we give it back to you...the people...Gotham is yours. None shall interfere, do as you please!

## Changelog
:cl:
add: Bane AI
/:cl:

2021-03-16 20:39 UTC, tralezab commented
@github-actions
Do you feel in Charge?

2021-03-16 20:40 UTC, wesoda25 commented
ooohh thats what that dude is from

2021-03-16 20:41 UTC, Qustinnus commented
wtf wesoda

2021-03-16 20:42 UTC, wesoda25 commented
what i knew i recognized him from somewhere but it's been a while since i watched the movie

2021-03-16 20:43 UTC, Qustinnus commented
smh how did u not know CIA

2021-03-16 20:43 UTC, tralezab commented
![image](https://user-images.githubusercontent.com/40974010/111377190-9718d680-865d-11eb-8dec-c09649881c3d.png)

2021-03-16 20:54 UTC, Pugie commented
can you add banepoetry?
[https://www.youtube.com/watch?v=nFzl0_Qeb84](url)
It's _beautiful._

2021-03-16 23:52 UTC, Pugie commented
> what i knew i recognized him from somewhere but it's been a while since i watched the movie

I forgot too over a year ago and had to search 'cia' through the discord to jog my memory it was extremely painful.

2021-03-17 06:04 UTC, optimumtact commented
> 
> 
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

2021-03-17 15:37 UTC, Qustinnus commented
@ oranges

![image](https://user-images.githubusercontent.com/20987591/111494712-9d2eb600-8736-11eb-8c47-9ff596e89fcb.png)

2021-03-17 18:41 UTC, tralezab commented
WE BROKE THE BAT
![image](https://user-images.githubusercontent.com/40974010/111520820-b410e080-8715-11eb-9792-b78fcfb50153.png)

2021-03-17 23:55 UTC, optimumtact commented on code/datums/ai/bane/bane_behaviors.dm
> +		"They expect one of us in the wreckage, brother.",
strings framework

2021-03-18 06:27 UTC, cacogen commented
CAI when

2021-03-19 00:44 UTC, Cyberboss requested changes
Load lines with the string framework

2021-03-19 00:54 UTC, tralezab commented
done

2021-03-19 02:38 UTC, lordpidey requested changes

2021-03-19 02:38 UTC, lordpidey commented on code/datums/ai/bane/bane_controller.dm
> +			batman = possibly_the_dark_knight
Add a break here, so that we early return.

2021-03-19 11:11 UTC, CPTANT commented
Batman and Bane are copyrighted material, they should not be mentioned by name in the code.

2021-03-19 15:52 UTC, Qustinnus commented
That is not how copyright works.

2021-03-25 15:09 UTC, Cyberboss approved these changes

2021-03-25 15:10 UTC, merged

2021-03-25 15:23 UTC, 81Denton commented
> Batman and Bane are copyrighted material, they should not be mentioned by name in the code.

![EYA2waOXsAAEUlu](https://user-images.githubusercontent.com/32391752/112498043-73a10a80-8d86-11eb-8eab-129bab3a0891.jpg)