Cleans up bullets to use subtypes for ammo variations
tgstation/tgstation pull request #57846
Opened 2021-03-20 01:06 UTC by KathrinBailey

#57517

## About The Pull Request
We have a bunch of bullets across the code that are **pewpew**mm_ap and **powpow**mm/ap
This switches it to the latter for consistency.
Be warned, this does mean that, for example, the nukie LMG will inherit new stats for their bullet subtypes:
```
/obj/projectile/bullet/mm712x82/ap
	name = "7.12x82mm armor-piercing bullet"
	damage = 40
	armour_penetration = 75
```
This will now inherit these stats from its parent:
```
	wound_bonus = -50
	wound_falloff_tile = 0
```
The stats previously for the AP version of the bullet, as defined by projectile/bullet, were:
```
	wound_bonus = -100
	wound_falloff_tile = -5
```

I'm unsure if bullets affected in this manner were supposed to be doing this or not. If I were to guess, the AP/HP/whatever variants of each bullet should've used the same base stats of the base bullets and modified the stats.

## Why It's Good For The Game
Potential fix..? It's up for interpretation, really. Some of those bullets are inheriting stats from projectile/bullet, and I'm not sure if they should be or if they should be inheriting stats from the version of the bullet they are.
Also, consistency across code. Bullet casings are subtypes, some bullets are subtypes, may as well make more bullets into subtypes.

## also this
![image](https://user-images.githubusercontent.com/53862927/111854686-631d0a00-8918-11eb-8e4b-a6f935870591.png)

2021-03-20 13:55 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/lmg.dm
>  	damage = 40
Same value as parent. You can remove this line.

2021-03-20 13:55 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/lmg.dm
>  	damage = 40
Ditto.

2021-03-20 13:55 UTC, Ghommie commented on code/modules/projectiles/projectile/bullets/smg.dm
>  	damage = 30
Ditto.

2021-03-22 20:30 UTC, Cyberboss requested changes
Above

2021-03-27 07:56 UTC, LemonInTheDark commented
How expansive is the effect on damage here?

2021-03-27 09:08 UTC, KathrinBailey commented
Should be zero affect on damage other than c9mm hollowpoint inheriting
`embedding = list(embed_chance=15, fall_chance=3, jostle_chance=4, ignore_throwspeed_threshold=TRUE, pain_stam_pct=0.4, pain_mult=5, jostle_pain_mult=6, rip_time=10)`
from it's parent.

2021-04-12 15:51 UTC, merged