Makes the explosive compressor and blastcannon actually use the TTVs they're given + the explosion changes to support that.
tgstation/tgstation pull request #58015
Opened 2021-03-28 11:34 UTC by TemporalOroboros

## About The Pull Request
- Adds a simple framework to let objects respond to explosions occurring inside of them. 
- Changes a whole bunch of explosions to use the object being exploded as the origin of the explosion rather than the turf the object is on.
- Makes the explosive compressor and blastcannon actually use the TTVs they are given.

- TODO: Less ugly argument passing

## Why It's Good For The Game
- Adds support for things responding to internal explosions.
- Less snowflake code for the explosive compressor and blastcannon calculating bomb range.*

*does not guarantee that the solution to letting them actually use the TTV is any less snowflake.

## Changelog
:cl:
refactor: The explosive compressor and blastcannon now actually use the bombs they are given. Both have experienced slight changes to their response times as a result.
/:cl:

2021-03-29 06:34 UTC, ATH1909 commented
does this happen to fix any other explosion bugs, like some of the fireball ones?

2021-03-29 08:37 UTC, TemporalOroboros commented
@ATH1909 
> 
> 
> does this happen to fix any other explosion bugs, like some of the fireball ones?

I don't know of the explosion bugs you're referring to so probably not.

2021-03-29 15:24 UTC, moocowswag commented
Id consider this a balance change to blast cannons since you cant reuse tank transfer valves after this change.

2021-03-29 16:46 UTC, TemporalOroboros commented
@moocowswag 
> Id consider this a balance change to blast cannons since you wont be able to reuse tank transfer valves and spam short range shots.

Actually no, since I didn't fix this. They will eat one of the tanks and empty the other one though.

> But then again they probably wernt intended to be reusable.

Yes. But I don't care that they weren't. It's funny.

> And i think one of the bugs athath is refering to is how fireballs wont actually explode when they hit a bot like beepsky and instead will somehow only damage the bot as if it was just a damaging projectile.

I'll check it once I fix my copy of DM refusing to debug anything for some reason.

2021-04-05 05:21 UTC, TemporalOroboros commented
@ATH1909 @moocowswag 
I think I figured out the fireball bug. The fireball does its damage before it tries to handle the explosion. Bots delete themselves when they die. As a result, if the fireball kills the bot before it gets around to the exploding bit it winds up trying to explode null and it breaks.

2021-04-13 08:01 UTC, LemonInTheDark commented
aw shit here we go again

2021-04-18 06:04 UTC, LemonInTheDark requested changes
Here's just the conversions, I'll do the 4 major file changes later

2021-04-18 06:04 UTC, LemonInTheDark commented on code/game/gamemodes/meteor/meteors.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 4, flame_range = 0, flash_range = 3, adminlog = FALSE)
ditto

2021-04-18 06:04 UTC, LemonInTheDark commented on code/game/gamemodes/meteor/meteors.dm
> +	explosion(src, devastation_range = 5, heavy_impact_range = 10, light_impact_range = 15, flame_range = 0, flash_range = 20, adminlog = FALSE)
and again

2021-04-18 06:04 UTC, LemonInTheDark commented on code/game/gamemodes/meteor/meteors.dm
> +		explosion(src, devastation_range = 2, heavy_impact_range = 4, light_impact_range = 6, flame_range = 0, flash_range = 8, adminlog = FALSE)
ONE MORE TIME

2021-04-18 06:04 UTC, LemonInTheDark commented on code/modules/events/spacevine.dm
> +	explosion(holder, devastation_range = 0, heavy_impact_range = 0, light_impact_range = severity, flash_range = 0, adminlog = FALSE)
why set flash range?

2021-04-18 06:36 UTC, TemporalOroboros commented on code/modules/vehicles/mecha/working/ripley.dm
> +		if(prob(10 * severity))
The defines were reversed. I un-reversed them and had to compensate.

2021-04-18 06:37 UTC, TemporalOroboros commented on code/modules/power/rtg.dm
> +	addtimer(CALLBACK(GLOBAL_PROC, .proc/explosion, src, 2, 3, 4, null, 8), 100) // Not a normal explosion.
The null was from before I started named args-ing everything. I'll fix it.

2021-04-18 06:38 UTC, TemporalOroboros commented on code/modules/power/gravitygenerator.dm
>  		set_broken()
There is nothing above `EXPLODE_DEVASTATE`. If someone adds something stronger at some point it should still break the generator.

2021-04-18 06:39 UTC, TemporalOroboros commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	adjustBruteLoss(-30 * severity)
Yep.

2021-04-18 06:39 UTC, TemporalOroboros commented on code/modules/mining/machine_vending.dm
>  		qdel(src)
Yep

2021-04-18 06:40 UTC, TemporalOroboros commented on code/modules/events/crystal_event.dm
> +		explosion(center_turf, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 5, flame_range = 7, flash_range = 7)
Nope. For some reason it was setting `adminlog = 7`. Since that's supposed to be a bool I assumed it was intended to be flame range.

2021-04-18 06:41 UTC, TemporalOroboros commented on code/datums/diseases/rhumba_beat.dm
> +				explosion(affected_mob, devastation_range = -1, heavy_impact_range = 0, light_impact_range = 2, flame_range = 2, flash_range = 3, adminlog = FALSE) // This is equivalent to a lvl 1 fireball
That's what I'm assuming. I moved it to flame range since that's the next thing in line that isn't a bool.

2021-04-18 06:41 UTC, TemporalOroboros commented on code/datums/mutations/body.dm
> +	explosion(owner, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flame_range = 0, flash_range = 0, adminlog = TRUE)
I'll fix it.

2021-04-18 06:41 UTC, TemporalOroboros commented on code/modules/antagonists/changeling/powers/headcrab.dm
> +	explosion(user, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flash_range = 0, adminlog = TRUE)
Ditto

2021-04-18 06:42 UTC, TemporalOroboros commented on code/modules/admin/smites/bsa.dm
> +	explosion(target.loc, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 0, flash_range = 0)
I'm pretty sure this means it hits just that specific turf.

2021-04-18 06:42 UTC, TemporalOroboros commented on code/game/objects/items/tanks/tanks.dm
> +	var/turf/location = loc
Right, I need to change that cast.

2021-04-18 06:43 UTC, TemporalOroboros commented on code/game/objects/items/tanks/tanks.dm
> +	var/turf/location = loc
Same

2021-04-18 06:43 UTC, TemporalOroboros commented on code/game/objects/items/granters.dm
> +	explosion(user, devastation_range = 1, heavy_impact_range = 0, light_impact_range = 2, flame_range = 2, flash_range = 3, adminlog = FALSE)
Yeah, it was the default for `ignorecap`

2021-04-18 06:43 UTC, TemporalOroboros commented on code/modules/events/spacevine.dm
> +	explosion(holder, devastation_range = 0, heavy_impact_range = 0, light_impact_range = severity, flash_range = 0, adminlog = FALSE)
Consistency I guess.

2021-04-20 08:26 UTC, LemonInTheDark commented on code/modules/events/crystal_event.dm
> +		explosion(center_turf, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 5, flame_range = 7, flash_range = 7)
![image](https://user-images.githubusercontent.com/58055496/115363608-76213500-a177-11eb-8480-8a532e9888bc.png)

2021-04-23 05:21 UTC, TemporalOroboros commented on code/controllers/subsystem/explosions.dm
> +	if(SEND_SIGNAL(origin, COMSIG_ATOM_EXPLODE, arguments[EXARG_KEY_DEV_RANGE], arguments[EXARG_KEY_HEAVY_RANGE], arguments[EXARG_KEY_LIGHT_RANGE], arguments[EXARG_KEY_FLAME_RANGE], arguments[EXARG_KEY_
I sure hope so, but so far I haven't found one.

2021-04-23 05:21 UTC, TemporalOroboros commented on code/modules/reagents/reagent_dispenser.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 3, light_impact_range = 5, flash_range = 7, flame_range = 10)
Yes.

2021-04-23 05:49 UTC, TemporalOroboros commented on code/modules/reagents/reagent_dispenser.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 3, light_impact_range = 5, flash_range = 7, flame_range = 10)
Fixed

2021-04-23 05:50 UTC, TemporalOroboros commented on code/modules/projectiles/projectile/special/rocket.dm
> +		explosion(target, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flash_range = 4, flame_range = 3)
Fixed

2021-04-23 05:50 UTC, TemporalOroboros commented on code/modules/projectiles/projectile/special/rocket.dm
> +		explosion(target, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flash_range = 4, flame_range = 3)
Fixed

2021-04-23 05:50 UTC, TemporalOroboros commented on code/modules/projectiles/projectile/special/rocket.dm
> +	explosion(target, devastation_range = -1, heavy_impact_range = 1, light_impact_range = 3, flash_range = 1, flame_range = 4, adminlog = FALSE)
Fixed

2021-04-23 05:51 UTC, TemporalOroboros commented on code/modules/projectiles/pins.dm
> +		explosion(src, devastation_range = -1, heavy_impact_range = 0, light_impact_range = 4, flash_range = 3)
I don't know. It's fixed.

2021-04-23 05:52 UTC, TemporalOroboros commented on code/modules/projectiles/guns/magic/wand.dm
> +	explosion(user, devastation_range = -1, heavy_impact_range = 0, light_impact_range = 2, flame_range = 2, flash_range = 3, adminlog = 0)
Fixed

2021-04-23 05:53 UTC, TemporalOroboros commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 0, flame_range = 3, adminlog = FALSE)
Not really, I'll get rid of them.

2021-04-23 05:53 UTC, TemporalOroboros commented on code/datums/mutations/body.dm
> +	explosion(owner, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flame_range = 0, flash_range = 0, adminlog = TRUE)
Fixed

2021-04-23 05:53 UTC, TemporalOroboros commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 0, flame_range = 3, adminlog = FALSE)
Done.

2021-04-23 05:53 UTC, TemporalOroboros commented on code/modules/antagonists/changeling/powers/headcrab.dm
> +	explosion(user, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 2, flash_range = 0, adminlog = TRUE)
Done

2021-04-23 05:54 UTC, TemporalOroboros commented on code/game/objects/items/tanks/tanks.dm
> +	var/turf/location = loc
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/game/objects/items/tanks/tanks.dm
> +	var/turf/location = loc
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/game/gamemodes/meteor/meteors.dm
> +	explosion(src, devastation_range = 1, heavy_impact_range = 2, light_impact_range = 3, flame_range = 0, flash_range = 4, adminlog = FALSE)
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/game/gamemodes/meteor/meteors.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 4, flame_range = 0, flash_range = 3, adminlog = FALSE)
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/game/gamemodes/meteor/meteors.dm
> +	explosion(src, devastation_range = 5, heavy_impact_range = 10, light_impact_range = 15, flame_range = 0, flash_range = 20, adminlog = FALSE)
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/game/gamemodes/meteor/meteors.dm
> +		explosion(src, devastation_range = 2, heavy_impact_range = 4, light_impact_range = 6, flame_range = 0, flash_range = 8, adminlog = FALSE)
Done

2021-04-23 05:55 UTC, TemporalOroboros commented on code/modules/events/spacevine.dm
> +	explosion(holder, devastation_range = 0, heavy_impact_range = 0, light_impact_range = severity, flash_range = 0, adminlog = FALSE)
Removed

2021-04-23 07:34 UTC, TemporalOroboros commented on code/controllers/subsystem/explosions.dm
> +	if(SEND_SIGNAL(origin, COMSIG_ATOM_EXPLODE, arguments[EXARG_KEY_DEV_RANGE], arguments[EXARG_KEY_HEAVY_RANGE], arguments[EXARG_KEY_LIGHT_RANGE], arguments[EXARG_KEY_FLAME_RANGE], arguments[EXARG_KEY_
Changed it to use the arguments list instead, since we're already passing that. It won't look nearly as good on the hook's end but whatever.

2021-04-23 07:35 UTC, TemporalOroboros commented on code/modules/power/rtg.dm
> +	addtimer(CALLBACK(GLOBAL_PROC, .proc/explosion, src, 2, 3, 4, null, 8), 100) // Not a normal explosion.
Apparently you can't use named arguments in callbacks. The null stays.

2021-04-23 07:35 UTC, TemporalOroboros commented on code/game/objects/structures/training_machine.dm
> +	explosion(src, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 1, flash_range = 2)
Fixed

2021-04-23 23:08 UTC, LemonInTheDark commented on code/modules/admin/smites/bsa.dm
> +	explosion(target.loc, devastation_range = 0, heavy_impact_range = 0, light_impact_range = 0, flash_range = 0)
hhhhhhhhhhhhhhhhh

2021-04-25 08:40 UTC, LemonInTheDark requested changes

2021-04-25 08:40 UTC, LemonInTheDark commented on code/modules/research/anomaly/explosive_compressor.dm
> +	say("Beginning compression test. Opening transfer valve.")
will this pop up as maptext?

2021-04-25 08:40 UTC, LemonInTheDark commented on code/modules/research/anomaly/explosive_compressor.dm
> +		say(message)
Ditto here

2021-04-25 09:51 UTC, TemporalOroboros commented on code/modules/research/anomaly/explosive_compressor.dm
> +	say("Beginning compression test. Opening transfer valve.")
Yes.

2021-04-25 09:51 UTC, TemporalOroboros commented on code/modules/research/anomaly/explosive_compressor.dm
> +		say(message)
Yep.

2021-04-26 08:41 UTC, LemonInTheDark commented
Fix the merge conflicts and we're golder

2021-04-26 09:18 UTC, LemonInTheDark commented
Oh also fix #58717

2021-04-27 00:31 UTC, merged