Fixes a few roulette wheel runtimes.
tgstation/tgstation pull request #58139
Opened 2021-04-03 22:22 UTC by Timberpoes

## About The Pull Request

Roulette wheel would runtime/bluescreen when an observer used it because of a naked cast of user to /mob/living/carbon/human
Roulette wheel would runtime/bluescreen when the ID card linked to it lost its registered account for any reason.
Roulette wheel would runtime/bluescreen when the user had an ID card that had no registered account.

Fixes all three of these runtimes.

## Why It's Good For The Game

Runtimes bad.

## Changelog
:cl:
fix: The Roulette Wheel interface should no longer bluescreen for bank account-less ID cards and observers.
/:cl:

2021-04-03 22:31 UTC, notfrying1pans commented
thanks :)

2021-04-05 12:11 UTC, Mothblocks requested changes
Two nit-picks to create more readable and maintainable code (since it'll ensure only one place needs to be touched, not two).

2021-04-05 12:11 UTC, Mothblocks commented on code/game/machinery/roulette_machine.dm
> +	data["HouseBalance"] = my_card?.registered_account ? my_card?.registered_account.account_balance : 0
```suggestion
	data["HouseBalance"] = my_card?.registered_account?.account_balance || 0
```

2021-04-05 12:11 UTC, Mothblocks commented on code/game/machinery/roulette_machine.dm
> +		data["AccountBalance"] = id_card?.registered_account ? id_card.registered_account.account_balance : 0
```suggestion
		data["AccountBalance"] = id_card?.registered_account?.account_balance || 0
```

2021-04-06 07:34 UTC, merged