fuck it. captain names the entire planet on icebox
tgstation/tgstation pull request #58168
Opened 2021-04-05 03:13 UTC by tralezab

## About The Pull Request

on icebox, captain gets a nanotrasen banner instead of a normal charter and he can choose the name of the entire planet

## Why It's Good For The Game

well that's why it's supposed to be in the game after all!

## Changelog
:cl:
qol: fuck it, captain names the entire planet on ice moon
/:cl:

2021-04-05 04:16 UTC, necromanceranne commented
Just wait till the golems hear about this and bust out the land claimer.

2021-04-05 04:49 UTC, Imaginos16 commented
Armhulen is on a roll!

2021-04-05 05:47 UTC, Farquaar commented
Prepare for your new life on Blue Station 13 on the cold planet of Balldonia

2021-04-05 12:56 UTC, wesoda25 commented
It’s a moon

2021-04-05 22:19 UTC, Zytolg commented
That's no moon...

2021-04-06 02:07 UTC, TheVekter commented
THAT'S MY ASS

2021-04-06 13:21 UTC, SuperNovaa41 commented
feature disguised as qol smh

2021-04-07 00:58 UTC, wesoda25 commented
.      .                  .             .            .   🌎       . .      
     .      .      ..  .       .    .       .      .      ..    .     .  . 

       🧑‍🚀
        /|\      |🇺🇸           ____________
   🤘|  🤙|               /                          \
        / \      |             /                             \
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2021-04-08 07:10 UTC, Mothblocks requested changes

2021-04-08 07:10 UTC, Mothblocks commented on _maps/kilostation.json
> +			"special_charter": 2
Make these use strings again, this isn't readable.

2021-04-08 07:10 UTC, Mothblocks commented on code/modules/jobs/job_types/captain.dm
> +	backpack_contents = list(/obj/item/melee/classic_baton/telescopic = 1) //removes normal charter
Use the initial value so it won't need to be in two places.

2021-04-08 07:10 UTC, Mothblocks commented on code/modules/jobs/job_types/captain.dm
> +			l_hand = /obj/item/station_charter/banner/asteroid
I'd rather not add a completely separate typepath if it's just going to be one value changed. Just change it on post_equip, or whatever it is.

2021-04-13 08:29 UTC, merged