Failed headrevs become enemies of the state
tgstation/tgstation pull request #58160
Opened 2021-04-05 00:20 UTC by tralezab

## About The Pull Request

Headrevs now gain a solo antagonist status if they are exiled instead of killed in a failed revolution. They have two objectives that conflict with eachother: exile (survive off zlevel and don't go to centcom) and hijack (steal the shuttle). They must pick one to be considered victorious.

## Why It's Good For The Game

Right now: Revolution ends, all revs are deantagged, exiled headrevs are now nonantagonists?? Admin headache because this headrev is not an antag but still facing the conseqences of being one

With this change: Revolution ends, exiled headrevs become enemies of the state. they have two options. Live it out off station as an exile, or one last big bang. Show Nanotrasen. Maybe the syndicate won't kill you with such a badass display of power?

## Changelog
:cl:
add: Headrevs become enemies of the state when the revolution is over!
/:cl:

2021-04-05 00:50 UTC, Mothblocks requested changes
As this seems to be built on top of policy, I'm going to pend head admin approval.

2021-04-05 00:50 UTC, Mothblocks commented on code/game/gamemodes/objective.dm
> +		if(!considered_alive(mind)) //dead
Useless comment.

2021-04-05 00:50 UTC, Mothblocks commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Stay alive off station. Do not go to centcom."
```suggestion
	explanation_text = "Stay alive off station. Do not go to CentCom."
```

2021-04-05 00:50 UTC, Mothblocks commented on code/game/gamemodes/objective.dm
> +		if(SSmapping.level_has_any_trait(alive_current.z, list(ZTRAIT_STATION, ZTRAIT_CENTCOM))) //went to centcom or ended round on station
This variable is unnecessary, you can just:

```suggestion
		if(SSmapping.level_has_any_trait(mind.current.z, list(ZTRAIT_STATION, ZTRAIT_CENTCOM))) //went to centcom or ended round on station
```

2021-04-05 00:50 UTC, Mothblocks commented on code/modules/antagonists/revolution/enemy_of_the_state.dm
> +	var/datum/objective/exile/choice_1 = new
`exile_choice`

2021-04-05 00:50 UTC, Mothblocks commented on code/modules/antagonists/revolution/enemy_of_the_state.dm
> +	var/datum/objective/hijack/choice_2 = new
`hijack_choice`

2021-04-05 07:28 UTC, necromanceranne commented
Be sure to update their hijack speed for them to be able to complete the objective.

2021-04-05 07:54 UTC, Mothblocks commented
they did

2021-04-07 23:30 UTC, Mothblocks requested changes

2021-04-07 23:30 UTC, Mothblocks commented on code/modules/antagonists/revolution/enemy_of_the_state.dm
> +	sleep(1)
:-1: Don't do this in on_gain, randomly yielding code is terrible. Just do it wherever the actual old antag datum is removed.

2021-04-09 09:51 UTC, Mothblocks commented on code/modules/antagonists/revolution/revolution.dm
> +			if(deconversion_reason == DECONVERTER_STATION_WIN)
Move this up to the beginning of `farewell`, it has no reason to be this deep in the chain.

2021-04-11 01:18 UTC, Mothblocks commented
Headmins gave approval over Discord.

2021-04-11 01:18 UTC, merged