TGUI: Command Reports
tgstation/tgstation pull request #58179
Opened 2021-04-05 20:12 UTC by MrMelbert

## About The Pull Request

Implements a TGUI window for the admin Create-Command-Report verb.

![image](https://user-images.githubusercontent.com/51863163/113621343-242dca80-9621-11eb-971d-bc907e6782ab.png)

[You can find a demonstration video of the window here.](https://streamable.com/86xsa5)

- The window comes with a few preset command names as well as the opportunity to use a custom command name.

- The user can also set a custom announcer sound effect to accompany their command report. This uses the list of announcer keys, so the sounds are automatically set for any station trait announcer.

- Lastly, they can check a box to determine if the report is to be announced or classified.

This PR also fixes the animes announcement line not functioning properly due to bad copy+paste.

## Why It's Good For The Game

Replaces some old input windows with TGUI and introduces some new functions to command reports for (b)admins to use. 

## Changelog
:cl: Melbert
refactor: TGUI Create-Command-Report window
admin: Admins can now set an announcement sound to accompany their command reports. 
fix: The anime announcement voice line now function properly again. This is not relevant to the above line whatsoever.
/:cl:

2021-04-05 21:09 UTC, tralezab reviewed
Here's some stuff to make your tgui better (you should test) ping me on discord if anything seems off

2021-04-05 21:09 UTC, tralezab commented on tgui/packages/tgui/interfaces/CommandReport.js
> +            mb={1}
just a tip and not a change, if you used stacks inside the section (stack and stack.item everything inside) you wouldn't have to bother with margins as much

2021-04-06 02:07 UTC, TheVekter commented
Nuuuuuut. Please continue murdering default pop-ups.

2021-04-06 08:27 UTC, Mothblocks commented
I think announce contents should be on its own line, as to both scale with more options being created and to let the submit report button be wide, due to its importance.

2021-04-06 08:29 UTC, Mothblocks requested changes

2021-04-06 08:29 UTC, Mothblocks commented on code/__DEFINES/sound.dm
> +	))
```suggestion
))
```

2021-04-06 08:29 UTC, Mothblocks commented on code/modules/admin/verbs/commandreport.dm
> +	return
This isn't necessary, return is implicit, though I think you should just use `return TRUE` in place of every `. = TRUE`.

2021-04-06 20:34 UTC, stylemistake commented on tgui/packages/tgui/interfaces/CommandReport.js
> +              <Stack vertical={1}>
This property is boolean, delete ={1}

2021-04-11 18:20 UTC, merged