knee jerk reaction PR
tgstation/tgstation pull request #58282
Opened 2021-04-10 02:28 UTC by wesoda25

Knee-jerk reflex, also called patellar reflex, sudden kicking movement of the lower leg in response to a sharp tap on the patellar tendon, which lies just below the kneecap. One of the several positions that a subject may take for the test is to sit with knees bent and with one leg crossed over the other so that the upper foot hangs clear of the floor. The sharp tap on the tendon slightly stretches the quadriceps, the complex of muscles at the front of the upper leg. In reaction these muscles contract, and the contraction tends to straighten the leg in a kicking motion. Exaggeration or absence of the reaction suggests that there may be damage to the central nervous system. The knee jerk can also be helpful in recognizing thyroid disease.

## About The Pull Request

This PR adds knee jerk reaction testing to the game. By right clicking someone's legs with a hammer related item, you will trigger a reaction. The style this reaction comes in is dependent upon the targets brain health, meaning this is a rudimentary way of checking brain damage. 

The reactions and what they mean are listed below.
Leg kicks out sharply: brain is healthy
Leg kicks out sharply after a moment: brain is mildly damaged
Leg weakly kicks out after a moment: brain is severely damaged
No reaction: brain is missing/dead

## Why It's Good For The Game

Knee jerk tests are important for checking on reaction time and keeping people healthy. 

## Changelog
:cl:
add: Knee-jerk reaction tests, right click someone's leg with a hammer-type item to check on their brain health!
/:cl:

2021-04-10 02:29 UTC, ShibaInuLord commented
thought he was gonna make ided but no this is based

2021-04-10 02:34 UTC, tralezab commented
Should this be a tool instead of an item flag?

2021-04-10 02:36 UTC, wesoda25 commented
> Should this be a tool instead of an item flag?

I was gonna do that at first but I felt this might be easier + make more sense 🤷

2021-04-10 02:37 UTC, SuperNovaa41 requested changes

2021-04-10 02:37 UTC, SuperNovaa41 commented on code/game/objects/items.dm
> +		playsound(D, 'sound/weapons/punchmiss.ogg', 20, TRUE, -1)
Where did D come from

2021-04-10 02:37 UTC, SuperNovaa41 commented on code/game/objects/items.dm
> +	var/obj/item/organ/brain/B = M.getorganslot(ORGAN_SLOT_BRAIN)
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

Change this to `target_brain` or something similar

2021-04-10 02:37 UTC, SuperNovaa41 commented on code/game/objects/items.dm
> +/obj/item/proc/kneejerk(mob/living/carbon/M, mob/living/carbon/user)
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

Change to `carbon_target` or something similar

2021-04-10 02:37 UTC, SuperNovaa41 commented on code/game/objects/items.dm
> +			var/BH = B.damage
Same as above. Make the variable name more specific.

2021-04-10 02:46 UTC, MrDoomBringer requested changes
Make patients have to actually take a seat. Doctors sprinting around whacking everyone's knees to check for brain damage seems funny but stupid.

2021-04-10 02:46 UTC, MrDoomBringer commented on code/_onclick/item_attack.dm
> +	if(item_flags & KNEE_JERK && (user.zone_selected == (BODY_ZONE_L_LEG || BODY_ZONE_R_LEG)) && LAZYACCESS(modifiers, RIGHT_CLICK))
```suggestion
	if(item_flags & KNEE_JERK && M.buckled && (user.zone_selected == (BODY_ZONE_L_LEG || BODY_ZONE_R_LEG)) && LAZYACCESS(modifiers, RIGHT_CLICK))
```

2021-04-10 02:50 UTC, ATH1909 commented on code/game/objects/items.dm
> +				return TRUE
```suggestion
			else //a dead/missing brain produces no reaction
				return TRUE
```

2021-04-10 02:50 UTC, ATH1909 commented on code/game/objects/items.dm
> +			if(!BH || BH < BRAIN_DAMAGE_MILD) //a healthy brain produces a normal reaction
```suggestion
			if(BH < BRAIN_DAMAGE_MILD) //a healthy brain produces a normal reaction
```

2021-04-10 05:50 UTC, ArcaneMusic commented
In real world medical use, this is often performed by a common tool called the babinski, or reflex hammer.

Not asking for any feature creep, but this might make for an easy advanced medical tool of some sort. Less of the head-bashing-cut-you-into-meatstrips and more the harmless medical tool category.

2021-04-10 10:34 UTC, Fikou commented on code/game/objects/items.dm
> +			return TRUE
```suggestion
			return TRUE
```

2021-04-10 12:02 UTC, Time-Green commented on code/game/objects/items.dm
> +				M.visible_message("<span class='danger'>[M]'s leg kicks out sharply!</span>", \
Could you add an extra parameter for the blind? This could actually be crazy useful for blind doctors since they can't use the health analyzer

2021-04-10 14:16 UTC, Farquaar commented
Low-tech station when?
I wanna run medbay where you need to use a penlight/stethoscope and mix chems from bottled reagents.

2021-04-10 21:52 UTC, Mothblocks requested changes
Please make this an element, we definitely should not be adding this onto the core attack chain. I figure you are just copying from EYE_STAB, but that really should've been an element too.

2021-04-12 01:22 UTC, wesoda25 commented
Sure I'll give that a try

2021-04-14 13:37 UTC, maxymax13 commented
declaring people dead by sawing their legs off and hitting their detached legs with a hammer and seeing no reaction

2021-04-20 04:39 UTC, wesoda25 commented
Alrighty, made it into an element and code is in a better place (still could be better though). Factored in Dooms suggestion on being buckled. Right now for timegreens I've made healthy reactions loud and brain damaged ones quiet as an audio cue for blind doctors. Will probably add some sort of message for them along with that. 

I'll undraft when it's ready.

2021-04-20 06:45 UTC, Mothblocks requested changes
Looking better, last few nitpicks.

2021-04-20 06:45 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +	if((user.zone_selected in list(BODY_ZONE_L_LEG, BODY_ZONE_R_LEG)) && LAZYACCESS(modifiers, RIGHT_CLICK) && target.buckled)
Do direct `==` checks, creating a list for this is needlessly expensive--I see this in a few other places and it's wrong.

Also, your comment is not needed--it's just writing out the code directly.

2021-04-20 06:45 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +	if((user.zone_selected in list(BODY_ZONE_L_LEG, BODY_ZONE_R_LEG)) && LAZYACCESS(modifiers, RIGHT_CLICK) && target.buckled)
Ideally alt attacks would be their own signal as well, but that's something I'll need to fix later (none of the secondary stuff calls `..()`, so not all signals are picked up).

2021-04-20 06:45 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +	if(ishuman(target))
Early return this.

2021-04-20 06:45 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +	id_arg_index = 2
There's no args, so this entire thing should just be `element_flags = ELEMENT_DETACH`.

2021-04-20 06:45 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +		if(target_brain) //do they have a brain?
Early return (and again, an unnecessary comment).

2021-04-21 02:02 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +			return
```suggestion
	if(selected_zone == BODY_ZONE_R_LEG && !r_leg)
		return
	if(selected_zone == BODY_ZONE_L_LEG && !l_leg)
		return
```

2021-04-21 02:03 UTC, Mothblocks commented on code/datums/elements/kneejerk.dm
> +	if(target_brain)
Early return this too.

2021-05-04 12:52 UTC, 81Denton commented
@wesoda25 This PR has been stale for a while, please ping me or any other maintainer when you're ready to address Mothblocks' reviews.

2021-05-19 04:39 UTC, wesoda25 commented
Now an audio cue for each reaction, healthier the brain, the louder the kick sound is

2021-05-28 01:20 UTC, Mothblocks commented
sorry

2021-05-28 01:20 UTC, merged