Centralized dummy lookalike generation
tgstation/tgstation pull request #58366
Opened 2021-04-12 20:39 UTC by TriggeredBoi

## About The Pull Request
Man I'm bad at PR names.
Anyways.
Since I used pretty much the exact same code to make dummies that copy people's appearance in my last two PRs, I decided to make a specialized proc for that. It also does it better.
Also squashed a bug while I was at it.

## Why It's Good For The Game

Less copypastas to achieve the same end result, I guess.

## Changelog
:cl: Trigg
fix: The Select Equipment menu now uses the UI owner's favorite outfits instead of the target mob's. Whoops.
/:cl:

2021-04-13 17:00 UTC, TriggeredBoi commented
In retrospect this PR is way too small and I probably should have snuck these changes in my last one. Too late now, though.

2021-04-15 18:13 UTC, Mothblocks requested changes

2021-04-15 18:13 UTC, Mothblocks commented on code/modules/mob/living/carbon/human/dummy.dm
> +	if(istype(target, /mob/living/carbon))
```suggestion
	if(iscarbon(target))
```

2021-04-15 18:13 UTC, Mothblocks commented on code/modules/mob/living/carbon/human/dummy.dm
> +			prefs.copy_to(copycat, icon_updates=TRUE, roundstart_checks=FALSE, character_setup=TRUE)
```suggestion
		prefs?.copy_to(copycat, icon_updates=TRUE, roundstart_checks=FALSE, character_setup=TRUE)
```

(or even kill the variable and just `target?.client?.prefs?.copy_to(...)`)

2021-04-15 19:50 UTC, TriggeredBoi commented
Also, I think a code improvement tag would be fitting; I didn't put anything about code in the changelog because it won't really affect anyone ingame.

2021-04-15 20:53 UTC, merged