Fixes ?. nonsense.
tgstation/tgstation pull request #58630
Opened 2021-04-23 06:04 UTC by AnturK

Latest 514 revealed these.

2021-04-23 06:22 UTC, Fikou requested changes

2021-04-23 06:22 UTC, Fikou commented on code/game/objects/items/toy_mechs.dm
> +			to_chat(target, "<span class='notice'>Your [attacker.name] is in combat.</span>")
```suggestion
		to_chat(target, "<span class='notice'>Your [attacker.name] is in combat.</span>")
```

2021-04-23 06:22 UTC, Fikou commented on code/game/objects/items/toy_mechs.dm
> +			to_chat(target, "<span class='notice'>[target.p_their()] [name] is in combat.</span>")
```suggestion
		to_chat(target, "<span class='notice'>[user.p_their()] [name] is in combat.</span>")
```
the fact that it uses your for the user but target's their for the target seems unintended?

2021-04-23 06:22 UTC, Fikou commented on code/game/objects/items/toy_mechs.dm
> +			to_chat(target, "<span class='notice'>[target.p_their()] [name] isn't ready for battle.</span>")
```suggestion
		to_chat(target, "<span class='notice'>[user.p_their()] [name] isn't ready for battle.</span>")
```

2021-04-23 06:22 UTC, Fikou commented on code/game/objects/items/toy_mechs.dm
> +			to_chat(target, "<span class='notice'>Your [attacker.name] isn't ready for battle.</span>")
```suggestion
		to_chat(target, "<span class='notice'>Your [attacker.name] isn't ready for battle.</span>")
```
```suggestion
		to_chat(target, "<span class='notice'>Your [attacker.name] isn't ready for battle.</span>")
```

2021-04-23 19:22 UTC, Cyberboss approved these changes

2021-04-23 19:22 UTC, Cyberboss commented
Lol who merged this

2021-04-24 01:03 UTC, Mothblocks commented
![image](https://user-images.githubusercontent.com/35135081/115942268-3f406d00-a45e-11eb-9f08-163010ba1eec.png)

https://www.youtube.com/watch?v=1p-DA0zvuQ8

2021-04-24 06:09 UTC, merged