Hypnoflashes are now a subtype of handheld
tgstation/tgstation pull request #58697
Opened 2021-04-25 08:34 UTC by tralezab

## About The Pull Request

fixes #54538

### "There are no consequences of making hypnoflashes a child of handheld"

![1984](https://user-images.githubusercontent.com/40974010/115986666-2ae79780-a566-11eb-8749-119e7bc4f1c3.gif)

## Changelog
:cl:
fix: hypnoflashes are now a subtype of handheld, which lets you do a few more things with them that normal flashes can.
/:cl:

2021-04-25 12:57 UTC, SuperNovaa41 commented
Borg hypnoflash eyes time

2021-04-26 06:18 UTC, XDTM commented
You didn't repath any of the functions under the hypnoflash though

2021-04-26 09:43 UTC, Mothblocks commented
> You didn't repath any of the functions under the hypnoflash though

this

also, if i remember right, the /handheld path shouldn't exist at all, its parent path is the only thing on it. this is a bad fix

2021-04-28 09:53 UTC, Mothblocks commented on code/modules/instruments/songs/_song.dm
> +/datum/song
uhhhhh

2021-04-28 09:54 UTC, Mothblocks commented on code/modules/instruments/items.dm
> +	var/datum/song/song
uhhhhhhhhhhhhhhhhhhh

2021-04-28 09:56 UTC, Mothblocks requested changes
Add it to https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths as well

2021-04-29 10:59 UTC, Mothblocks requested changes

2021-04-29 10:59 UTC, Mothblocks commented on code/modules/instruments/items.dm
> +	var/datum/song/song
yeah tihs is still here @tralezab

2021-04-30 10:40 UTC, Mothblocks commented
why did you undraft it has an outstanding review and is conflicting

2021-05-02 21:50 UTC, tralezab commented
HOW IS IT STILL THERE

2021-05-02 21:52 UTC, tralezab commented
pr is CURSED

https://discord.com/channels/326822144233439242/326831214667235328/838533132038701096

2021-05-02 21:52 UTC, closed without merging