Greyscale sombrero and shamebrero
tgstation/tgstation pull request #58854
Opened 2021-05-02 10:12 UTC by ninjanomnom

![image](https://user-images.githubusercontent.com/1234602/116809472-2f82f180-ab0c-11eb-99dc-b95e93e90b07.png)

Mostly I did this in the process of making a step by step guide for GAGS [on hackmd](https://hackmd.io/@tgstation/GAGS-Walkthrough). No player facing changes really, though an admin could more easily change the colors now if they wish.

2021-05-02 11:16 UTC, celotajstg requested changes

2021-05-02 11:16 UTC, celotajstg commented on code/datums/greyscale/json_configs/sombrero_base.json
> +			"color_ids": [ 2 ]
indentation

2021-05-02 11:16 UTC, celotajstg commented on code/datums/greyscale/json_configs/sombrero_lefthand.json
> +		},
same here and in some other places, would be good to re-check

2021-05-02 11:16 UTC, celotajstg commented on code/modules/clothing/head/misc.dm
> +	if(greyscale_colors)
no need for this, see: https://github.com/tgstation/tgstation/pull/58808/files#diff-c8ab5fbc20de60e202b839834b039649cbb69a1c4b99b27a5e467f3889442ccdR38

tl;dr - just assign greyscale_config_worn, greyscale_config_inhand_left and greyscale_config_inhand_right variables.

2021-05-04 23:24 UTC, Twaticus approved these changes

2021-05-06 13:19 UTC, merged