Updates the PDA painter so that it properly prints standard PDAs.
tgstation/tgstation pull request #58867
Opened 2021-05-03 01:35 UTC by Greniza

## About The Pull Request

Closes [58842](https://github.com/tgstation/tgstation/issues/58842#issue-873702774)

## Why It's Good For The Game

Minor bug-fix.

## Changelog
:cl:
fix: Made the PDA painter be able to paint PDAs into standard PDAs.
/:cl:

2021-05-03 17:25 UTC, Greniza commented
Of note: the failstate for improperly implementing a new PDA's interaction within `SSid_access.station_pda_templates` is moved from the PDA not being repainted to the PDA being painted to a standard PDA.

2021-05-04 17:49 UTC, celotajstg commented
waiting for https://github.com/Greniza/tgstation/pull/5 to get merged for a working fix

2021-05-04 21:13 UTC, celotajstg commented
Good to merge

2021-05-05 05:40 UTC, ninjanomnom requested changes

2021-05-05 05:40 UTC, ninjanomnom commented on code/game/machinery/PDApainter.dm
> +				stored_pda.update_greyscale()
```suggestion
				stored_pda.set_greyscale_config(initial(pda_path.greyscale_config), update=FALSE)
				stored_pda.set_greyscale_colors(initial(pda_path.greyscale_colors))
```

2021-05-07 01:37 UTC, merged