Improves Code Readability for Syndi grenades
tgstation/tgstation pull request #58979
Opened 2021-05-09 03:54 UTC by YakumoChen

## About The Pull Request
Gives vars better names
Gives me the GBP

## Why It's Good For The Game
Coding guidelines are cool

## Changelog
code improvement

2021-05-09 03:56 UTC, Mothblocks requested changes

2021-05-09 03:56 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
> +	for(var/turf/Turf in view(freeze_range,loc))
This is not a descriptive name.

You need to describe the *context* the variable is in. Re-read https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use-descriptive-and-obvious-names

Also, snake_case.

2021-05-09 03:56 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
> +			var/turf/open/floor/ItsAFloor = Turf
Same here.

2021-05-09 03:56 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
> +			for(var/mob/living/carbon/Victim in Turf)
snake_case

2021-05-09 04:05 UTC, YakumoChen commented
@Mothblocks is this better

2021-05-09 04:06 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
> +			var/turf/open/floor/its_floor = turf_affected
just `floor`

2021-05-09 04:06 UTC, Mothblocks commented
almost

2021-05-15 09:04 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
> +		if(isfloorturf(turf_affected))
Last thing, didn't notice this until now--sorry, chang this to `for (var/turf/open/floor/floor in view(freeze_range, loc))`.

If we're performing a type-check anyway, we might as well do it in the definition.

2021-05-15 10:51 UTC, Mothblocks commented on code/game/objects/items/grenades/syndieminibomb.dm
>  		if(isfloorturf(turf_affected))
You don't need this anymore.

2021-05-15 12:06 UTC, YakumoChen commented
@Mothblocks I assume changing it to floor_affected wouldn't work
Code standards are just confusing now.

2021-05-15 12:15 UTC, YakumoChen commented
I fucked up and am no longer sure how

2021-05-15 12:29 UTC, YakumoChen commented
it turns out deleting more code was the answer

2021-05-15 12:33 UTC, Mothblocks commented
usually is 😎

2021-05-15 12:33 UTC, Mothblocks commented
Sorry for delays, all good.

2021-05-15 12:33 UTC, merged