Makes the cybernetic voicebox use same saymods as silicons
tgstation/tgstation pull request #58981
Opened 2021-05-09 04:29 UTC by BootlegBow

## About The Pull Request

People with cybernetic voiceboxes now use 'queries' 'alarms' and 'declares' instead of 'asks' 'yells' and 'exclaims'

## Why It's Good For The Game

Cybernetic voiceboxes can perfectly replicate a human voice asking a question or yeling, but not talking normally... huh

## Changelog
:cl:
qol: cybernetic voiceboxes now use same saymods as silicons
/:cl:

2021-05-09 11:20 UTC, Fikou commented
have you tested this pr? there is no reason your code would work.

2021-05-09 20:19 UTC, BootlegBow commented
> have you tested this pr? there is no reason your code would work.

no i'm just a complete fucking idiot

2021-05-10 07:57 UTC, coiax requested changes

2021-05-10 07:57 UTC, coiax commented on code/modules/surgery/organs/tongue.dm
> +		M.dna.species.yell_mod = yell_mod
Bunch all of these together under a single `if(M.dna && M.dna.species)` branch.
Then undo the changes to the species datum, that this code does, in `Remove()`.

2021-05-11 01:40 UTC, closed without merging