Removes Revolutionaries becoming enemies of the revolution
tgstation/tgstation pull request #59015
Opened 2021-05-10 17:19 UTC by JohnFulpWillard

## About The Pull Request

> I haven't been able to test this due to not being able to open 3 instances of BYOND.

This removes the ability for Security/Command Revolutionaries from becoming Enemies of the Revolution upon a Rev victory. Command cannot be revs in any circumstance, so it only affects Security.

I'm marking this as fix for now, but I was told that this might've been intentional. If so, I can swap this out for balance, but it makes no sense why a Revolutionary would become an Enemy of the Revolution just for succeeding at their job.

## Why It's Good For The Game

step 1) implant removal surgery the warden
step 2) convert them to the revolution
step 3) watch them kill the HoS
step 4) kill them because now they're an enemy of the revolution

## Changelog
:cl:
fix: Security Revolutionaries will no longer become Enemies of the Revolution upon a Revolution victory.
/:cl:

2021-05-10 17:32 UTC, Cyberboss approved these changes

2021-05-10 17:34 UTC, Cyberboss requested changes

2021-05-10 17:34 UTC, Cyberboss commented on code/modules/antagonists/revolution/revolution.dm
> +			if (!(mind.has_antag_datum(/datum/antagonist/rev))
```suggestion
			if (!(mind.has_antag_datum(/datum/antagonist/rev)))
```

2021-05-10 17:42 UTC, Cyberboss approved these changes, later dismissed

2021-05-10 19:00 UTC, MrMelbert commented on code/modules/antagonists/revolution/revolution.dm
> +				continue
If i'm reading this right, this only adds "Enemy of the Revolution" if they ARE a rev, is this tested?
`(if mind does not have a rev antagonist datum, skip this player in the loop.)`

2021-05-10 19:46 UTC, MrMelbert commented
I'll also point out (not 100% certain) but I think it removes all rev antag datums by this point in the code so this check might not do anyhting

2021-05-10 19:56 UTC, JohnFulpWillard commented
> I'll also point out (not 100% certain) but I think it removes all rev antag datums by this point in the code so this check might not do anything

That was my original fear when I noticed I couldn’t test it locally

2021-05-14 20:47 UTC, ninjanomnom approved these changes

2021-05-14 20:47 UTC, merged