Buckling no longer gives people the immobile trait, allowing paraplegics to do more things
tgstation/tgstation pull request #59097
Opened 2021-05-14 01:07 UTC by RandomGamer123

## About The Pull Request

Buckling now doesn't give people TRAIT_IMMOBILIZED just for buckling. Being cuffed applies TRAIT_HANDS_BLOCKED anyways, so this doesn't allow buckle-cuffed people to use things like nanites or cult chat.

## Why It's Good For The Game

Fixes #59012 and also allows paraplegic people (and people buckled to chairs voluntarily) to do more things like use dermal buttons.

## Changelog
:cl:
fix: Being voluntarily buckled to a chair or wheelchair no longer prevents you from using dermal button nanites, cult chat, and more.
/:cl:

2021-05-14 02:33 UTC, optimumtact commented
have you done any analysis on what this will enable?

it must have been set for a reason.

2021-05-14 12:57 UTC, RandomGamer123 commented
I did some basic searches, and it was added by #52578, which added the trait to begin with, and it just seems like the immobilized trait has been used a bit too generally here

2021-05-14 13:07 UTC, RandomGamer123 commented
Actually I just checked every single use of TRAIT_IMMOBILIZED and mercury and lithium's random steps use it so yeah this doesn't really work, I'll see maybe if I can remove it for wheelchairs only

2021-05-14 15:49 UTC, RandomGamer123 commented
Lithium works for wheelchairs and it just makes the wheelchair and mob both move, so this should be fine now

2021-05-15 08:46 UTC, Mothblocks requested changes

2021-05-15 08:46 UTC, Mothblocks commented on code/modules/mob/living/living.dm
> +		if(!istype(buckled,/obj/vehicle/ridden/wheelchair))
Dumb way of doing this, hard-coded type paths are funky and this gives no explanation as to *why* this is here.

Make this a trait on wheelchairs instead that this checks for.

2021-05-15 08:46 UTC, Mothblocks commented
Your changelog is now out of date since it only affects wheelchairs.

2021-05-17 04:04 UTC, merged