contractor baton cyborg stunning now uses left/right clicks, not combat mode
tgstation/tgstation pull request #59110
Opened 2021-05-14 11:03 UTC by ATH1909

## About The Pull Request

Contractor batons will now stun cyborgs on a left click and harmbaton them on a right click, instead of stunning cyborgs if you're NOT in combat mode and harmbatonning them if you are.

Stunning a cyborg with a contractor baton now puts your contractor baton on cooldown, just like knocking a human down does. Don't worry, you can still easily chainstun/baton 'n' bash borgs with contractor batons.

Attempting to stun a cyborg with a classic baton or a telebaton will play a CLONGing noise, produce a special message, and put your baton on cooldown. Harmbatonning cyborgs with classic batons and telebatons still works, of course.

Accidentally hitting yourself due to clumsiness with a classic baton, a telebaton, or a contractor baton will now deal brute damage to you, knock you down, and deal stamina damage to you instead of dealing brute damage to you and hardstunning you for approximately 10 billion years. For comparison, the stun baton clumsiness effect knocks you down for longer than this new classic baton clumsiness effect does, but doesn't deal stamina damage or brute damage to you.

The code for classic batons, telebatons, and contractor batons has been doc'd slightly better and refactored a bit.

## Why It's Good For The Game

Contactor batons should determine whether they should stun or harmbaton a cyborg the same way that they determine whether they should knockdown or harmbaton a human. You also shouldn't need to turn off combat mode to stun a cyborg with a contractor baton, which is a pretty hostile action.

I have tested this PR, and the only oddity I've found is that attempting to stun a cyborg with a baton while it's on cooldown still produces sparks. This is a general issue with most objects that have nonzero force values and have a non-stamina damage type but also have a non-harmful effect when used on a cyborg, and I don't quite know how I would (safely) go about fixing it. I also just realized that I forgot to test the new clumsiness effect, but eh, it probably works.

## Changelog
:cl: ATHATH
qol: Contractor batons will now stun cyborgs on a left click and harmbaton them on a right click, instead of stunning cyborgs if you're NOT in combat mode and harmbatonning them if you are.
fix: Stunning a cyborg with a contractor baton now puts your contractor baton on cooldown, just like knocking a human down does. Don't worry, you can still easily chainstun/baton 'n' bash borgs with contractor batons.
soundadd: Attempting to stun a cyborg with a classic baton or a telebaton will play a CLONGing noise, produce a special message, and put your baton on cooldown. Harmbatonning cyborgs with classic batons and telebatons still works, of course.
qol: Accidentally hitting yourself due to clumsiness with a classic baton, a telebaton, or a contractor baton will now deal brute damage to you, knock you down, and deal stamina damage to you instead of dealing brute damage to you and hardstunning you for approximately 10 billion years.
refactor: The code for classic batons, telebatons, and contractor batons has been doc'd slightly better and refactored a bit.
/:cl:

2021-05-14 13:59 UTC, Sparkezel commented
Balance change :trollface:

2021-05-14 22:33 UTC, ATH1909 commented
> Balance change :trollface:. Weren't batons meant codewise to stun borgs too iirc? Or just steal the power from the batong? I think there was an early return somewhere in batong code....

????

Stun batons are not affected by this change at all.

2021-05-24 02:26 UTC, maxymax13 commented
> 
> 
> Balance change :trollface:. Weren't batons meant codewise to stun borgs too iirc? Or just steal the power from the batong? I think there was an early return somewhere in batong code....

???????????

2021-06-01 05:29 UTC, LemonInTheDark commented
![image](https://user-images.githubusercontent.com/58055496/120271178-b805c680-c25f-11eb-894c-c2afecda20a8.png)
Why?

2021-06-01 05:38 UTC, ATH1909 commented
> ![image](https://user-images.githubusercontent.com/58055496/120271178-b805c680-c25f-11eb-894c-c2afecda20a8.png)
> Why?

The 18 second hardstun was absolutely hideous. I can remove that change if you want, though.

2021-06-08 19:36 UTC, LemonInTheDark commented
I'd like that yeah

2021-06-09 08:33 UTC, ATH1909 commented
> I'd like that yeah

The absurdly long hardstun that someone probably just forgot to change when batons were changed to use stamina damage instead of hardstuns is back, as per your request.

2021-06-11 11:56 UTC, ATH1909 commented
*sigh*

2021-06-15 09:32 UTC, LemonInTheDark requested changes
There's more, but this is all I could muster tonight

2021-06-15 20:17 UTC, ATH1909 commented on code/game/objects/items/melee/misc.dm
> +	var/cooldown = 40
sure

2021-06-15 20:20 UTC, ATH1909 commented on code/game/objects/items/melee/misc.dm
>  	return
dunno, I think I might have accidentally removed it when resolving a merge conflict. I'll add it back.

2021-06-21 05:37 UTC, LemonInTheDark commented on code/game/objects/items/melee/misc.dm
> +
I hate this, but it's not your fault, you were failed by our past

2021-06-21 05:37 UTC, merged