Fixes lockers unlocking without distance checks
tgstation/tgstation pull request #59214
Opened 2021-05-20 21:00 UTC by RandomGamer123

## About The Pull Request
Lockers no longer unlock despite you not being next to them

## Why It's Good For The Game
Fixes #59208 , which was caused by #58774.

## Changelog
:cl:
fix: Lockers can now only be unlocked if you're next to them.
/:cl:

2021-05-20 23:06 UTC, maxymax13 commented
noo how will i release my monkey locker on sec now

2021-05-21 10:43 UTC, Qustinnus requested changes
this should instead be moved to whatever proc handles attack hand's secondary. @Mothblocks would know more probably

2021-05-21 12:17 UTC, Mothblocks commented
@Qustinnus Actually, it was originally, but I asked them not to since that doesn't preserve the old behavior (that I quite enjoy) of being able to lock it with your hands full, especially since you're often opening a locker to get stuff out of it.

2021-05-21 12:42 UTC, Qustinnus commented
ah yeah i remember now.

2021-05-23 03:29 UTC, ninjanomnom approved these changes

2021-05-23 03:29 UTC, merged