Converts some of mech actions into balloons
tgstation/tgstation pull request #59255
Opened 2021-05-22 09:03 UTC by InsaneRed

## About The Pull Request
part 1 converting of mech text into ballons

## Why It's Good For The Game
ballons look better and work better
## Changelog
:cl:
Converts most of the equipment on mechs into ballons
/:cl:

2021-05-22 09:09 UTC, Mothblocks commented
im making it async hold on

2021-05-23 08:16 UTC, Mothblocks requested changes
Very good work, thanks a lot.

I want to keep balloon alerts very short (since they're temporary), and lowercase (after seeing Arm's PR). I'm going to write a doc for this very soon, but thanks for helping me figure this out.

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/combat/durand.dm
> +		chassis.balloon_alert(owner, "Insufficient power; cannot activate defense mode.")
```suggestion
		chassis.balloon_alert(owner, "insufficient power")
```

1. Arm has made them lowercase, and I've decided I like that.
2. We already know we're activating the shield, so it's unnecessary to state it again. Normally it wouldn't matter, but balloon alrets are best kept short.

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/combat/durand.dm
> +		chassis.balloon_alert(owner, "Defense mode [chassis.defense_mode?"enabled":"disabled"]")
```suggestion
		chassis.balloon_alert(owner, "defense mode [chassis.defense_mode?"enabled":"disabled"]")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +	chassis.balloon_alert(owner, "Now taking air from [chassis.use_internal_tank ? "internal airtank" : "environment"]")
```suggestion
	chassis.balloon_alert(owner, "taking air from [chassis.use_internal_tank ? "internal tank" : "environment"]")
```

Short, succinct, lowercase.

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "No Equipment Available")
```suggestion
		chassis.balloon_alert(owner, "no equipment available")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "You select [chassis.selected]")
```suggestion
		chassis.balloon_alert(owner, "[chassis.selected] selected")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "You switch to no equipment")
```suggestion
			chassis.balloon_alert(owner, "switched to no equipment")
```

Again, I want to keep these very short (and lowercase).

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "You switch to [chassis.selected]")
```suggestion
			chassis.balloon_alert(owner, "switched to [chassis.selected]")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "This mechs lights are destroyed!")
```suggestion
		chassis.balloon_alert(owner, "mech lights are destroyed!")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +	to_chat(owner, "Toggled lights [chassis.mecha_flags & LIGHTS_ON ? "on":"off"]")
```suggestion
	to_chat(owner, "lights [chassis.mecha_flags & LIGHTS_ON ? "on":"off"]")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner,"You enable leg actuators overload.")
```suggestion
		chassis.balloon_alert(owner, "leg actuators overload enabled")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "You disable the leg actuators overload.")
```suggestion
		chassis.balloon_alert(owner, "leg actuators overload disabled")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "Your exosuit's hands form into fists.")
```suggestion
			chassis.balloon_alert(owner, "your exosuit's hands form into fists")
```

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "A torch tip extends from your exosuit's hand, glowing red.")
```suggestion
			chassis.balloon_alert(owner, "a torch tip extends from your exosuit's hand, glowing red")
```

(I can't really find a way to shorten this, but I worry it's too long).

2021-05-23 08:16 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +	chassis.balloon_alert(owner, "[chassis.phasing ? "Enabled" : "Disabled"] phasing")
```suggestion
	chassis.balloon_alert(owner, "phasing [chassis.phasing ? "enabled" : "disabled"]")
```

2021-05-23 17:03 UTC, tralezab commented
Actually it was tralezabs idea

2021-05-23 21:08 UTC, Mothblocks requested changes
Closer, but you missed a few of my suggestions from earlier.

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/combat/durand.dm
> +		chassis.balloon_alert(owner, "insufficient power.")
```suggestion
		chassis.balloon_alert(owner, "insufficient power")
```

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "you select [chassis.selected]")
```suggestion
		chassis.balloon_alert(owner, "[chassis.selected] selected")
```

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner,"you overload the leg actuators overload.")
```suggestion
		chassis.balloon_alert(owner,"leg actuators overloaded")
```

It's wordy.

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +		chassis.balloon_alert(owner, "you disable the overload.")
```suggestion
		chassis.balloon_alert(owner, "you disable the overload")
```

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "your punches will now do fire damage")
```suggestion
			chassis.balloon_alert(owner, "your punches will now deal burn damage")
```

2021-05-23 21:08 UTC, Mothblocks commented on code/modules/vehicles/mecha/mecha_actions.dm
> +			chassis.balloon_alert(owner, "your punches will now do brute damage")
```suggestion
			chassis.balloon_alert(owner, "your punches will now deal brute damage")
```

2021-05-24 08:29 UTC, merged