CONTRIBUTING.md has a new code standard about naming arguments passed to vars
tgstation/tgstation pull request #59368
Opened 2021-05-28 22:51 UTC by tralezab

## About The Pull Request & Why It's Good For The Game

Title. There has been some really hideous arg names for this situation of passing it into a var, for example:

`/datum/element/decal/Attach(atom/target, _icon, _icon_state, _dir, _cleanable=FALSE, _color, _layer=TURF_LAYER, _description, _alpha=255, mutable_appearance/_pic)`

Some of which aren't even matching the format of var = _arg...

![image](https://user-images.githubusercontent.com/40974010/120048567-4feb8200-bfcc-11eb-852a-862cf04c4088.png)

## Changelog
Not player facing

2021-05-28 23:17 UTC, TemporalOroboros commented
Honestly glad to have this cleared up.

2021-05-29 04:01 UTC, Mothblocks requested changes

2021-05-29 04:01 UTC, Mothblocks commented on .github/CONTRIBUTING.md
> +var/atom/thing/Initialize(mapload, enable_red)
```suggestion
/atom/thing/Initialize(mapload, enable_red)
```

2021-05-29 04:01 UTC, Mothblocks commented on .github/CONTRIBUTING.md
> +var/atom/thing/Initialize(mapload, _is_red)
```suggestion
/atom/thing/Initialize(mapload, _is_red)
```

2021-05-29 04:01 UTC, Mothblocks commented on .github/CONTRIBUTING.md
> +var/atom/thing/Initialize(mapload, is_red)
```suggestion
/atom/thing/Initialize(mapload, is_red)
```

2021-05-29 08:52 UTC, LemonInTheDark commented
if I'm honest I don't really like `src.varname = varname`, it seems like a bit of a mind flood. I do hate `varname =_varname` even more, but I'm not sure if we should insitute src.var as a rule.

Is there maintainer support for this? @Mothblocks you want this right?

2021-05-29 18:11 UTC, Mothblocks commented
Yes. 🙂

2021-05-29 21:29 UTC, tralezab commented
The alternates to _var are actually way worse, since the argument passed as a variable will only be used in a single line, yet require naming it as a synonym of the var set

2021-05-30 20:59 UTC, Mothblocks commented
CC @tgstation/commit-access 

This is something I've been enforcing for a while and it makes a lot of things, most often component code, a lot better.

2021-05-30 21:35 UTC, tralezab commented
everywhere i look

i find more cases of BOTH making it a synonym AND adding an underscore

![image](https://user-images.githubusercontent.com/40974010/120120752-412fd700-c154-11eb-88ba-48d8b73460a8.png)

2021-05-30 21:55 UTC, optimumtact commented
I refuse to use such ugly underscores, when src.var = var works perfectly fine

2021-05-30 23:08 UTC, Cyberboss commented
I hate named arguments to begin with and would rather see them all eliminated.

Since that's not going to happen though, I guess this is the next best thing.

2021-05-30 23:34 UTC, merged