Fixes amanitin dealing less damage than before
tgstation/tgstation pull request #59562
Opened 2021-06-08 15:57 UTC by RandomGamer123

## About The Pull Request
Metabolisation changes meant that REM was changed to 0.5, which makes amanitin much less deadlier, this fixes that and restores its original behavior.

## Why It's Good For The Game
Fixes #58654

## Changelog
:cl:
fix: Amanitin (destroying angel toxin) is now back to its original amount of deadliness prior to human metabolisation changes.
/:cl:

2021-06-08 16:26 UTC, TheBonded commented
Finally I can make stealthy delayed 200 toxin damage mixes. imagine a sleepy pen of this stuff

2021-06-08 19:03 UTC, Iamgoofball commented
who the fuck put all the traitor chemicals I added into botany plants

2021-06-08 20:23 UTC, TemporalOroboros commented
@Iamgoofball 
> who the fuck put all the traitor chemicals I added into botany plants

There are around a dozen toxins in the poison kit and only four of them show up in plants. Of the four, formaldehyde and cyanide can be made in chemistry and have been able to be made in chemistry since you added them. The other two -- amanitin and coniine -- were added to botany by @Lumipharon in #16266. They also added cyanide to poison berries, but I think that's fair since you ported deathweed in #19105. Formaldehyde was recently added to corpseflowers by @MrMelbert in #56024.

2021-06-08 22:09 UTC, Iamgoofball commented
damn guess i was wrong

2021-06-10 17:50 UTC, coiax requested changes

2021-06-11 17:18 UTC, RandomGamer123 commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +	var/toxdamage = current_cycle*3
Was the Life(dt) change after or before the REM change, since if it was before, then the pre-REM change behavior would be this as goofball mentioned?

2021-06-15 21:29 UTC, coiax requested changes

2021-06-15 21:29 UTC, coiax commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +	..()
```suggestion
	. = ..()
```

2021-06-15 21:29 UTC, coiax commented on code/modules/reagents/chemistry/reagents/toxin_reagents.dm
> +	var/metabolisationtime = 0
```suggestion
	var/delayed_toxin_damage = 0
```
Then change the `on_mob_life` to be `+= delta_time * 3`

2021-06-16 18:48 UTC, merged