Modifies right click logic so that it is not the same priority as modifier keys.
tgstation/tgstation pull request #59656
Opened 2021-06-14 05:45 UTC by Timberpoes

## About The Pull Request

Right clicking is up in priority above modifier keys. If a non-modifier right click ends the attack chain, all modifiers are ignored.

Unarmed right click is also higher in priority than armed right click, so unarmed right click actions can perform unarmed actions (such as opening containers) and end the attack chain without performing an item attack, even if you're holding an item.

This moves the logic down to the melee attack chain level. This modifies the logic to match ranged attacks and ranged secondary attacks, where either the item attack path is used or the unarmed attack path is used depending on if the active hand has an item or not.

This means you're no longer able to open containers by right clicking on them with an item in-hand and now you have to do it unarmed. However, this opens up behavour for right clicking on containers with items to do secondary effects such as inserting the item (the current default) or some other behaviour entirely (which I need this behaviour pattern to implement).

## Why It's Good For The Game

Items will be able to interact with containers again.

## Changelog
:cl:
qol: Right clicking containers while unarmed will open the container. Right clicking containers while armed will perform an item attack, broadly speaking inserting the item into the container but could unlock other behaviours too.
/:cl:

2021-06-14 10:08 UTC, Colovorat commented
If i am not retarded, and understand it right. If you have items in both hands, you can't open bag with right click? So when alt click will be removed, you will be able only to drag it on yourself(if you have items in hands), which is stupid

2021-06-14 13:12 UTC, Timberpoes commented
> If i am not retarded, and understand it right. If you have items in both hands, you can't open bag with right click? So when alt click will be removed, you will be able only to drag it on yourself(if you have items in hands), which is stupid

See the concerns expressed on https://github.com/tgstation/tgstation/pull/59565 before it was merged. Right click to open was considered a potential issue since it prevented item secondary effects and was tentatively merged knowing it could cause issues.

This brings the behaviour back a step. You can still right click to open but only with an empty hand. We'll revisit whether which behaviour we want to see in the future. There is nothing inherently wrong with alt click as a hotkey modifier that bypasses held item checks to perform an unarmed attack.

2021-06-14 17:06 UTC, Fikou commented
this shouldnt be in the game while having storage opening on right click at the same time

2021-06-14 19:03 UTC, Timberpoes commented
> 
> 
> this shouldnt be in the game while having storage opening on right click at the same time

sux

2021-06-14 19:08 UTC, Mothblocks requested changes, later dismissed
> Right clicking containers while unarmed will open the container. Right clicking containers while armed will perform an item attack, broadly speaking inserting the item into the container but could unlock other behaviours too.

Right-click should NOT be performing actions that left-click does. The fact that it does is a BYOND-ism that I aim to fix at some point. We've broken this compatibility in the past, such as with tool acts, where secondary tool acts don't force the primary tool act.

Your agent ID card PR should instead tell the normal right-click on container code not to perform that action, because this makes right-click-to-open-containers *awful*.

2021-06-14 19:09 UTC, Timberpoes commented
What I'm attempting to address was a known issue with the merging of #59565, giving full credit to Ath for bringing it up first:

![image](https://user-images.githubusercontent.com/24975989/121945487-bd790b80-cd4b-11eb-8f53-27d5337325da.png)

The PR was merged with the caveat that if this limited design space we could deal with it. I believe it's limiting design space because I have a use-case where I want to be able to secondary attack an item on a storage container and have the item attack the storage container instead of having the storage container cancel the attack chain before I have a chance to execute the item's secondary attack.

![image](https://user-images.githubusercontent.com/24975989/121945835-206aa280-cd4c-11eb-96ef-ae8d006d9441.png)

2021-06-14 19:11 UTC, Mothblocks commented
Limiting *individual item actions* was my concern--such as the fact that "oh, now I need to do a different action to open a container while it's in my hand*. It was *not* "now because of some niche interactions, I now can no longer *open a container at all with an item in my hand*".

2021-06-14 21:54 UTC, Mothblocks commented
If you want this you HAVE to revert right-clicking for lockers and right-clicking for storage containers, then provide a clear explanation in that PR as to the problem we are having with ambiguous interactions like this so we have something to point to.

Then, we need to work on an actual document to describe what key to use for what in order to *avoid* this ambiguous behavior in the future.

2021-06-15 02:27 UTC, Mothblocks commented
Screw it, nevermind, this is probably the best approach.

2021-06-15 02:38 UTC, Mothblocks commented
But remove the message saying alt-click is going to be removed, because I guess we'll never do it.

2021-06-15 02:56 UTC, YakumoChen commented
Revert right-click locking for lockers too, this makes no sense with that functionality in mind.

2021-06-15 02:59 UTC, YakumoChen commented
Also could you maybe mention what is so important you have to revert major functionality changes to storage so that you can enact it? Stop being vague.

2021-06-15 04:04 UTC, Mothblocks commented
It's the PR right above this one.

2021-06-15 04:05 UTC, Mothblocks commented
And the one that is mentioned here.

![image](https://user-images.githubusercontent.com/35135081/121991277-32504380-cd54-11eb-8005-ee663622d9a5.png)

The problem is ambiguity. It's a very annoying problem that means we have to make basic controls such as opening storage shittier, but it's a problem.

2021-06-15 22:22 UTC, Timberpoes commented
This has been radically altered from before. It now implements a system where items can get their behaviour in and end the attack chain before storage components take over. This allows items to, on a bespoke basis, sneak in some cheeky logic in pre attack procs and cancel the attack chain without the storage component hijacking secondary attacks to open and close themselves.

2021-06-24 17:30 UTC, merged