Added more complex AIs to carps when tamed.
tgstation/tgstation pull request #60027
Opened 2021-07-04 22:45 UTC by Watermelon914

## About The Pull Request

Adds carp AI and the ability to tame carps.
Carps are now considered flying so that they don't fall through zlevels.
Generally improved movement whilst transitioning zlevels whilst buckled to a mob.

Carps can be tamed with meat, which is a random chance. Once tamed, you can ride the carp and move around with it.
You can also set it to follow you or to attack an object, similar to how corgis would.

There are some other changes to the movement of buckled mobs, which include:
- Ability to stay buckled if the buckling object is flying/floating .
- Prevents dismounting to a buckling object if it cannot pass through something. Instead, the buckling object will not be able to go any further.

https://cdn.discordapp.com/attachments/326831214667235328/861374496949796894/2021-07-04_23-33-35.mp4

## Why It's Good For The Game

Adds similar AI from the corgi to other simple_animal mobs, making the interactions with them slightly more advanced. You can have pet carps now!

## Changelog
:cl:
add: Added a more complex AI to carps that allow you to tell them to attack people or to follow you. These carps can be tamed with raw meat, which'll then give you control over them if you succeed in taming them. A carp will only be tamed to 1 person.
/:cl:

2021-07-04 23:38 UTC, AMonkeyThatCodes commented on code/datums/ai/carp/carp_behaviors.dm
> +	if(!attack_target || !can_see(living_pawn, attack_target, length=AI_CARP_VISION_RANGE))
vision range should be a blackboard key. These behaviors should be generic and this entire behavior would be better off being more generic as it has no real reason to be only for carps as far as I can tell

2021-07-04 23:39 UTC, AMonkeyThatCodes commented on code/datums/ai/carp/carp_controller.dm
> +/datum/ai_controller/carp/proc/on_attack_by(datum/source, obj/item/food, mob/living/attacker, params)
all this stuff thats basically taming could should be on the mob.

2021-07-05 18:47 UTC, TheBonded commented
Can this be added to goliaths too, which you can also tame and ride?

2021-07-05 19:38 UTC, Watermelon914 commented
> Can this be added to goliaths too, which you can also tame and ride?

in a future pr, if you want to add it, then yes.

2021-07-12 02:53 UTC, IndieanaJones commented
The dragon already has the flying element.

2021-07-12 08:23 UTC, Watermelon914 commented
> The dragon already has the flying element.

It isn't considered actual flying, they will still fall through empty spaces.

2021-07-13 07:19 UTC, Kylerace requested changes

2021-07-13 07:19 UTC, Kylerace commented on code/game/objects/buckling.dm
> +		M.forceMove(loc)
why not just forceMove() here?

2021-07-15 08:34 UTC, Watermelon914 commented
for some reason I didn't get notifications you had posted this review

2021-07-15 08:35 UTC, Watermelon914 commented on code/game/objects/buckling.dm
> +		M.forceMove(loc)
it unmounts the user

2021-07-15 22:04 UTC, merged