Fix Tram ghost magnet and other cases of observer forceMove
tgstation/tgstation pull request #60026
Opened 2021-07-04 22:10 UTC by Wayland-Smithy

## About The Pull Request

Changes all the ghost `forceMove()` I could find which cause stuff like `COMSIG_ATOM_ENTERED` to fire and replaced it with `abstract_move()`

## Why It's Good For The Game

Fixes: #59376

## Changelog
:cl:
fix: Fixed Tram ghost magnet and other cases of observer forceMove.
code: Renamed some observer code vars for better readability.
/:cl:

2021-07-04 22:13 UTC, Kylerace requested changes

2021-07-04 22:13 UTC, Kylerace commented on code/datums/components/orbiter.dm
> +	for(var/atom/movable/movable_orbiter in orbiter_list)
as anything

2021-07-04 22:17 UTC, Wayland-Smithy commented on code/datums/components/orbiter.dm
> +	for(var/atom/movable/movable_orbiter in orbiter_list)
```suggestion
	for(var/atom/movable/movable_orbiter as anything in orbiter_list)
```

2021-07-04 23:18 UTC, Mothblocks commented
Don't put a colon after Fixes, if you write Fixes #XXXXX then GitHub will automatically close it.

2021-07-05 00:56 UTC, Wayland-Smithy commented
This might break ghosts using stairs? Or perhaps that was never intended and only a side effect of the forceMove.

2021-07-05 05:17 UTC, Wayland-Smithy commented
I'm considering overriding `forceMove()` for observers. Any objections?

The stairs thing unchanged, and one-way, just by orbiting them on the level below.

2021-07-09 01:11 UTC, merged