Finally moves godmode to a trait
tgstation/tgstation pull request #60048
Opened 2021-07-06 08:49 UTC by SmArtKar

## About The Pull Request

Moves GODMODE to a trait instead of status flag. Oh, and yeah, now aheals can heal through godmode

## Why It's Good For The Game

It's much easier to use and code is cleaner.

## Changelog
:cl:
fix: Aheals now work on mobs with godmode
refactor: Godmode is now a trait instead of status flag
/:cl:

2021-07-06 19:00 UTC, Watermelon914 commented
isn't this a refactor though? A code improvement would be changing the code to look better but this makes it easier to apply godmode and generally just makes godmode work in a more flexible way without changing how it works on the frontend.

2021-07-06 19:20 UTC, SmArtKar commented
> isn't this a refactor though? A code improvement would be changing the code to look better and easier to read but this makes it easier to apply godmode for different cases and generally just makes godmode work in a more flexible way without changing how it works on the frontend.

yeah and also I want my 10 GBP instead of 2 😅

2021-07-07 00:33 UTC, optimumtact commented
flags > traits long live binary flags

2021-07-08 20:18 UTC, coiax requested changes

2021-07-08 20:18 UTC, coiax commented on code/modules/mob/living/damage_procs.dm
> +	adjustBruteLoss(-brute, FALSE, forced = forced) //zero as argument for no instant health update
```suggestion
	adjustBruteLoss(-brute, FALSE, forced = forced)
```

This comment is probably for when it had a `0` instead of a `FALSE`.

2021-07-08 20:18 UTC, coiax commented on code/modules/mob/living/living.dm
>  		adjustToxLoss(-20, TRUE, TRUE) //slime friendly
can you put named arguments on these?

2021-07-08 20:18 UTC, coiax commented on code/modules/mob/living/living.dm
> +	setCloneLoss(0, 0, forced = TRUE)
Replace the 0 with FALSE, and use named arguments.

2021-07-11 00:38 UTC, Mothblocks requested changes

2021-07-11 00:38 UTC, Mothblocks commented on code/__DEFINES/traits.dm
> +#define TRAIT_GODMODE "godmode"
document this

2021-08-01 07:21 UTC, closed without merging