makes a bunch of lists that use typecacheof() static. doesnt find out why its overtiming at all but what the hell it helps
tgstation/tgstation pull request #60147
Opened 2021-07-10 11:04 UTC by Kylerace

## About The Pull Request
noticed typecacheof() had overtime in a round but for some reason windows explorer is hanging so ill have to get the screenshot later. i thought it was weird for it to be in the top 10 overtiming procs so i went through and i made a bunch of the lists that use it into static lists (at least for the ones in which it makes sense)

also the usual as anything's and better var names where i get annoyed enough to change them

## Why It's Good For The Game
speed? probably some.

2021-07-10 11:06 UTC, Mothblocks commented on code/modules/spells/spell_types/aimed.dm
> +	QDEL_NULL(lockon_component) //TODOKYLER: AAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
hm

2021-07-10 11:08 UTC, Kylerace commented on code/modules/spells/spell_types/aimed.dm
> +	QDEL_NULL(lockon_component) //TODOKYLER: AAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
oh right the todos

2021-07-10 11:10 UTC, Kylerace commented
fuck i knew i was forgetting something, pr will be fully unshittied tomorrow

2021-07-10 22:02 UTC, Kylerace commented on code/modules/spells/spell_types/aimed.dm
> +	QDEL_NULL(lockon_component) //TODOKYLER: AAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
todo gone

2021-07-12 20:36 UTC, Mothblocks requested changes

2021-07-12 20:36 UTC, Mothblocks commented on code/modules/research/experimentor.dm
> +	//var/banned_typecache // items that won't be produced
Don't leave commented out code.

2021-07-12 20:37 UTC, Mothblocks commented on code/modules/research/experimentor.dm
> +	//var/banned_typecache // items that won't be produced
```suggestion
```

2021-07-12 21:08 UTC, merged