Fixes e-bolas ignoring block chances and throw catches and not ensnaring flying mobs.
tgstation/tgstation pull request #60160
Opened 2021-07-10 19:52 UTC by Ghommie

## About The Pull Request
Title. Plus reduced indentation.

## Why It's Good For The Game
This will fix #56442.

## Changelog
:cl:
fix: Fixed e-bolas ignoring block chances and throw catches and not ensnaring flying/floating mobs (though it's kinda pointless because they ignore the slowdown).
/:cl:

2021-07-10 19:54 UTC, Mothblocks commented
I remember a 2nd PR on this--I deem not being able to catch the e-bola as a feature, if your PR alters that behavior, can you change that?

2021-07-10 19:56 UTC, ATH1909 commented
> I remember a 2nd PR on this--I deem not being able to catch the e-bola as a feature, if your PR alters that behavior, can you change that?

https://github.com/tgstation/tgstation/pull/58460

2021-07-10 20:12 UTC, Ghommie commented
> 
> I deem not being able to catch the e-bola as a feature

Give me one good reason why a parent call being wrongfully


> 
> 
> I remember a 2nd PR on this--I deem not being able to catch the e-bola as a feature, if your PR alters that behavior, can you change that?

Change what exactly? It currently calls ensnare() after being queued for deletion on throw_impact(), and ensnare() won't do jackshit because the mob is already ensnared by a previously spawned bear trap. It's shitcode imho. But even if it weren't, I'd still see no reason why they should be uncatchable and unblockable.

2021-07-10 20:22 UTC, Mothblocks commented
Just making sure since a previous PR made it so you can catch them, which I didn't like.

2021-07-12 06:07 UTC, LemonInTheDark commented
> Fixes e-bolas ignoring block chances and **throw catches**

What does this mean?

2021-07-13 14:20 UTC, Ghommie commented
> 
> 
> > Fixes e-bolas ignoring block chances and **throw catches**
> 
> What does this mean?

Rewrote the changelong entry to be more understandable.

2021-07-13 16:47 UTC, LemonInTheDark commented
@Mothblocks I think he's making it catchable

2021-07-13 19:31 UTC, Mothblocks commented
bro

2021-07-13 19:32 UTC, Mothblocks requested changes
Being uncatchable is not a bug. Keep it.

2021-07-20 23:06 UTC, moocowswag commented
What about making it so only things that can block energy projectiles can block it? Like the reflective trenchcoat?

2021-07-21 01:48 UTC, oklews commented
It's still a physical object, and you shouldn't be able to ignore the most commonly used bola by wearing armor. Block chance is the way to go IMO.

2021-07-30 19:33 UTC, Mothblocks commented on code/game/objects/items/handcuffs.dm
> +	ADD_TRAIT(src, TRAIT_UNCATCHABLE, TRAIT_GENERIC) /// People said energy bolas being uncatchable is a feature.
```suggestion
	ADD_TRAIT(src, TRAIT_UNCATCHABLE, TRAIT_GENERIC) // People said energy bolas being uncatchable is a feature.
```

`///` == doc comment

2021-07-30 19:42 UTC, merged