Adds the "To Number" circuit component
tgstation/tgstation pull request #60202
Opened 2021-07-13 06:57 UTC by TheSmallBlue

## About The Pull Request
While you can calmly turn a number into a string by just linking the number output and the string input, you cannot do the same with turning a string into a number. This will change with these super duper cash money 40 fucking lines of code hell yeah

## Why It's Good For The Game
Allows for taking stuff from a string, for example a message, and into other components like index list.
Example: 
https://youtu.be/IW03YapF0pk

## Changelog
:cl:
expansion: Added the To Number circuit component.
/:cl:

2021-07-13 07:13 UTC, Mothblocks commented
Shorten the name to just "To Number", I think the string is implied.

2021-07-13 07:18 UTC, TheSmallBlue commented
I'm kinda scared that people will think it takes in any value if I name it "To Number", since "To String" does exactly that, but sure.

2021-07-13 07:19 UTC, Mothblocks commented
They'll learn once they try 😄

2021-07-13 08:31 UTC, Watermelon914 commented on code/modules/wiremod/components/string/tonumber.dm
> +		return
set the output to null

2021-07-13 19:32 UTC, Watermelon914 commented on code/modules/wiremod/components/string/tonumber.dm
> +		return
in fact, just don't have this check at all. It'll be set to null anyways when it sets the output to output_value

2021-07-14 20:35 UTC, Mothblocks requested changes

2021-07-14 20:35 UTC, Mothblocks commented on code/modules/wiremod/components/string/tonumber.dm
> +	output.set_output(output_value)
```suggestion
	output.set_output(text2num(input_port.input_value))
```

2021-07-19 21:02 UTC, merged