Revives PR #58579; Sligh refactor to AI datums that allows for basic support of subtrees
tgstation/tgstation pull request #60249
Opened 2021-07-16 00:15 UTC by ma44

## About The Pull Request
Revival of #58579

## Why It's Good For The Game
Subtyped controllers is practically required to make simple mobs datumized without needing to redesign the entire system to work in AI datum's current configuration.

2021-07-16 00:16 UTC, ma44 commented
Needs some more documentation alongside another look at the subtyped behaviors to ensure they're equivalent to master branch.

2021-07-16 01:33 UTC, ike709 commented
Based

2021-07-17 06:11 UTC, tralezab commented
dopeness!

2021-07-19 02:42 UTC, ma44 commented
Going to need some conversion to LAZYLIST to address previous PR's comments alongside a relook at SUBTREE_RETURN_FINISH_PLANNING to have it's documentation actually function as it should.

2021-07-26 00:18 UTC, Kylerace requested changes

2021-07-26 00:18 UTC, Kylerace commented on code/datums/ai/_ai_controller.dm
> +		for(var/datum/ai_planning_subtree/subtree in planning_subtrees)
should be as anything

2021-07-29 00:56 UTC, merged