Adds on examine hints for constructing turrets similar to walls or mechs
tgstation/tgstation pull request #60454
Opened 2021-07-26 06:49 UTC by itseasytosee

## About The Pull Request
Just adds some on examine text depending on the turrets stage of construction to guide you on what do do while building a turret

## Why It's Good For The Game
People no longer have to open the wiki to make turrets

## Changelog
:cl: itseasytosee
qol: Adds some on examine instructions for constructing a turret
/:cl:

2021-07-26 18:30 UTC, MrDoomBringer requested changes

2021-07-26 18:30 UTC, MrDoomBringer commented on code/game/machinery/porta_turret/portable_turret_construct.dm
> +			. += span_notice("The turret requires an <b>proximity sensor</b> to fuction.")
Also you misspelled function

2021-07-26 18:30 UTC, MrDoomBringer commented on code/game/machinery/porta_turret/portable_turret_construct.dm
> +			. += span_notice("The turret requires an <b>energy based gun</b> to fuction, the armor is secured by <i>bolts</i>.")
```suggestion
			. += span_notice("The turret requires an <b>energy based gun</b> to function, the armor is secured by <i>bolts</i>.")
```

2021-07-26 18:30 UTC, MrDoomBringer commented on code/game/machinery/porta_turret/portable_turret_construct.dm
> +			. += span_notice("The turret's access hatch is <b>unscrewed</b>.")
Ditto 
```suggestion
			. += span_notice("The turret's access hatch is <b>unscrewed</b>. The proximity sensor could <i>be removed</i>.")
```

2021-07-26 18:44 UTC, itseasytosee commented
I did not know you could take the prox sensor out, go figure.

2021-07-28 19:12 UTC, Rohesie commented
Good PR!

2021-07-28 19:12 UTC, merged