Adds the library_report table
tgstation/tgstation pull request #60599
Opened 2021-07-31 20:41 UTC by nfreader

There's been a request for a more robust way to moderate the library, and this is part of an effort to work on that. These SQL changes are used by Statbus to handle books reported by players and deleted (or undeleted) by admins.

2021-08-01 05:48 UTC, Jordie0608 requested changes
Update the version defines.
https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/subsystems.dm#L14

2021-08-02 06:53 UTC, Jordie0608 requested changes

2021-08-02 06:53 UTC, Jordie0608 commented on SQL/database_changelog.txt
> +CREATE TABLE `library_action` (
Missed it before but you've got a different table name here on all the files.

2021-08-02 07:13 UTC, MrStonedOne requested changes
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0203 seconds.)

2021-08-02 07:13 UTC, MrStonedOne commented on SQL/tgstation_schema_prefixed.sql
> +DROP TABLE IF EXISTS `SS13_library_report`;
```suggestion
DROP TABLE IF EXISTS `SS13_library_action`;
```

2021-08-02 07:13 UTC, MrStonedOne commented on SQL/tgstation_schema.sql
> +DROP TABLE IF EXISTS `library_report`;
```suggestion
DROP TABLE IF EXISTS `library_action`;
```

2021-08-02 07:13 UTC, MrStonedOne commented on SQL/database_changelog.txt
> +DROP TABLE IF EXISTS `library_report`;
```suggestion
DROP TABLE IF EXISTS `library_action`;
```

2021-08-02 07:16 UTC, MrStonedOne approved these changes

2021-08-03 02:52 UTC, Jordie0608 approved these changes

2021-08-03 02:59 UTC, merged