Actually Quantifiably For Realsies This Time Fixes The Curse Of Hunger
tgstation/tgstation pull request #60620
Opened 2021-08-01 03:04 UTC by tralezab

## About The Pull Request

Curse of hunger no longer uses `slot_equipment_priority` as a considered var, now it just uses `slot_flags`.

slot_equipment_priority was insanely deprecated and unused so I just removed it. Now items that are being equipped are asked if they want to modify the default slot priority order

## Why It's Good For The Game

Good god man I just want this really cool component to work

## Changelog
:cl:
fix: For realsies this time: Curse of hunger WORKS.
/:cl:

2021-08-01 06:04 UTC, Watermelon914 commented
curse of hunger does work with the duffelbag though, I tested in my fix but didn't care to test for any admin related builds.

2021-08-01 06:05 UTC, Watermelon914 commented
curse of hunger does work with the duffelbag though, I tested in my fix but didn't care to test for any admin related contraptions.

2021-08-01 16:06 UTC, tralezab commented
Yeah I'm fixing the fantasy affix version 😋

2021-08-03 05:21 UTC, Mothblocks requested changes

2021-08-03 05:21 UTC, Mothblocks commented on code/modules/mob/mob.dm
> +	var/list/slot_priority = list(
Put this in a GLOB since you use it twice.

2021-08-03 05:21 UTC, Mothblocks commented on code/game/objects/items.dm
> +/obj/item/proc/get_autoequip_slot()
Explicitly `return null` at the end of this.

2021-08-03 05:21 UTC, Mothblocks commented on code/game/objects/items.dm
> +/obj/item/proc/special_slot_priority(list/slot_priority)
Don't have this mutate the list. Have it return a new list instead (defaulting to `return slot_priority`). This makes it much easier to reason about consumers.

2021-08-19 00:06 UTC, closed without merging