Circuits log their speech if they speak.
tgstation/tgstation pull request #60684
Opened 2021-08-03 17:38 UTC by ArcaneMusic

## About The Pull Request

Circuits now log their game speech when used in combination with a speech component. Shells-based circuits have it attached to the shell, other circuits have it attached to the physical part otherwise.

## Why It's Good For The Game

Fixes #60440.
Improves admin feedback when circuits are involved.

## Changelog
:cl:
admin: Circuits that talk are now logged.
/:cl:

2021-08-03 19:59 UTC, Mothblocks commented
I log circuit speech for BCIs, though not with this level of detail. Can you update that as well? You should be able to find it just in the BCI file.

2021-08-05 08:16 UTC, Mothblocks requested changes
Update the log in brain_computer_interface, you'll find it

2021-08-05 10:19 UTC, Watermelon914 commented
This will already log it for BCIs because it logs the trigger for the speech component, not the component using `say` itself, so it'll just leave a double log.

2021-08-05 10:22 UTC, Watermelon914 commented on code/modules/wiremod/components/action/speech.dm
> +			log_talk(message.input_value, LOG_SAY, tag="circuit speech | Built by [parent.get_creator()].")
These messages will be a bit misleading because it's in this format:
`shell_object (info on creator)`

2021-08-05 19:09 UTC, Mothblocks commented
@Watermelon914 It logs for BCIs because I tagged where it came from, but I didn't include get_creator(), which I should've

2021-09-06 00:37 UTC, ArcaneMusic commented
Yeah I'm both too unavailable to sit down and get this up to snuff, @Mothblocks Feel free to make the changes you wanted to make for this because as far as I can tell that would double log a lot of this but I'm not going to let this rot if someone else can get this done in a few days. 🤷‍♂️

2021-09-06 00:37 UTC, closed without merging