beer and ale headsmash fix
tgstation/tgstation pull request #60748
Opened 2021-08-07 03:39 UTC by manofpepsi

## About The Pull Request

repaths the beer and ale to allow bottle headsmashing with them.

fixes:#60594

## Changelog
:cl:Pepsiman0
fix: you can now smash a bottle of beer or ale on someone's head

2021-08-07 03:53 UTC, TemporalOroboros commented
Just a heads-up, but there's some office politics/drama going down right now. If someone starts a flame war in the comments feel free to ignore them. Things will calm down eventually.

2021-08-07 03:56 UTC, LemonInTheDark commented
Fixes for the fix lord

2021-08-07 12:13 UTC, Fikou commented
are you sure this wasnt intended? these bottles are smaller both in units and in sprite, they are cheaper in vendors and a lot easier to get than most headsmash thingies

2021-08-07 14:45 UTC, Ghommie reviewed
You forgot about their original volume.

2021-08-07 14:45 UTC, Ghommie commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +	list_reagents = list(/datum/reagent/consumable/ethanol/beer = 30)
```suggestion
	volume = 50
	list_reagents = list(/datum/reagent/consumable/ethanol/beer = 30)
```

2021-08-07 14:45 UTC, Ghommie commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +	list_reagents = list(/datum/reagent/consumable/ethanol/ale = 30)
```suggestion
	volume = 50
	list_reagents = list(/datum/reagent/consumable/ethanol/ale = 30)
```

2021-08-07 18:46 UTC, manofpepsi commented
> are you sure this wasnt intended? these bottles are smaller both in units and in sprite, they are cheaper in vendors and you can get 10 free ones from bartenders closet

well I do presume that the bottle smashing with beer and ale bottles was intended just not realized for some reason, some stuff like the inhand icon states for the /obj/item/reagent_containers/food/drinks/bottle have beer in their names, and it would be just inconsistent with the rest of the bottled drinks that look similarly to beer but you can use the to bottle smash someone. also the small glass bottle which can be currently used for bottle smashing costs less than the beer in the booze-o-mat.

2021-08-07 18:48 UTC, manofpepsi commented on code/modules/food_and_drinks/drinks/drinks/bottle.dm
> +	list_reagents = list(/datum/reagent/consumable/ethanol/beer = 30)
thanks for pointing that out

2021-08-12 17:05 UTC, Maurukas approved these changes

2021-08-12 19:26 UTC, ShizCalev requested changes

2021-08-23 00:17 UTC, merged