Fixes solar stacking
tgstation/tgstation pull request #60799
Opened 2021-08-10 15:02 UTC by MMMiracles

## About The Pull Request
Adds a check when applying glass to solar assemblies to see if a solar panel already exists on that turf so you can't stack them anymore.

Fixes #60565

## Why It's Good For The Game
Infinitely stackable solar sounds bad for the already poor power balance.

## Changelog
:cl: MMMiracles
fix: Solar assemblies can no longer be built on top of existing solar panels.
/:cl:

2021-08-12 05:49 UTC, Rohesie requested changes

2021-08-12 05:49 UTC, Rohesie commented on code/modules/power/solar.dm
> +				return
```suggestion
		if(locate(/obj/machinery/power/solar) in solarturf)
			to_chat(user, span_warning("[anchorcheck] is already assembled here."))
			return
```

2021-08-12 05:50 UTC, Rohesie commented on code/modules/power/solar.dm
> +	var/turf/solarturf = get_turf(src)
Why is this variable set in here, instead of right before it is used?

2021-08-20 13:55 UTC, Cyberboss approved these changes

2021-08-20 13:55 UTC, merged