Potted plants are no longer prone to wear the One Ring when trimmed and going invisible as a result
tgstation/tgstation pull request #60849
Opened 2021-08-13 23:02 UTC by GoldenAlpharex

## About The Pull Request
Potted plants shouldn't become invisible after being trimmed anymore.

## Why It's Good For The Game
Invisible plants are bad, need I say more?

## Changelog
:cl: GoldenAlpharex
fix: Potted plants are no longer self-concious about their appearance changing when trimmed and will now hopefully properly display themselves as a result.
/:cl:

2021-08-16 07:29 UTC, Mothblocks requested changes
I don't understand how this fixes it, but whatever

2021-08-16 07:29 UTC, Mothblocks commented on code/game/objects/structures/flora.dm
>  		random_plant_states += "plant-[number]"
```suggestion
		random_plant_states += "plant-[i]"
```

2021-08-31 00:09 UTC, closed without merging

2021-08-31 06:22 UTC, Mothblocks commented
you need to undraft your stuff

2021-09-01 11:10 UTC, AMonkeyThatCodes commented
> I don't understand how this fixes it, but whatever

noob the icon states dont have 0 in em

2021-09-01 11:20 UTC, Fikou commented
there are a lot of instances of potted plants on maps having var edited icon states. are you sure this doesnt fuck that up?

2021-09-01 12:10 UTC, GoldenAlpharex commented
> there are a lot of instances of potted plants on maps having var edited icon states. are you sure this doesnt fuck that up?

I'll look it up tonight, I guess. So long as this gets re-opened, at least. Damn GitHub notifications