Add some new posibrain names
tgstation/tgstation pull request #60932
Opened 2021-08-19 05:55 UTC by optimumtact

2021-08-19 06:03 UTC, optimumtact commented
dumb stripper action

2021-08-19 06:07 UTC, Zytolg commented
Is that a c*der reference?

2021-08-19 06:09 UTC, MrDoomBringer commented
No player references are allowed under current policy, please excise all of these and use appropriate names.

Thank you

2021-08-19 06:14 UTC, Mothblocks approved these changes

2021-08-19 06:16 UTC, Mothblocks approved these changes
i approve

2021-08-19 06:41 UTC, Fikou requested changes
Code looks bad

2021-08-19 06:48 UTC, MrDoomBringer commented
<img width="600px" src="https://user-images.githubusercontent.com/29008542/130021013-0c98952f-642a-4ca2-bda7-8a10c02f6f39.png"/>

2021-08-19 07:21 UTC, LemonInTheDark commented
![pepin-the-short-being-crowned-king-of-the-franks-by-st-boniface-in-751](https://user-images.githubusercontent.com/58055496/130025475-72a28871-3876-4e86-8f63-7eb25b7195d1.jpg)

2021-08-19 11:28 UTC, NamelessFairy commented
https://github.com/tgstation/tgstation/pull/60608

This is a content expansion, please wait until next month 🐈

2021-08-19 15:05 UTC, tralezab commented on strings/names/posibrain.txt
> +BLOK
this would be awesome, i think

```suggestion
BLOK
ARM
```

2021-08-19 15:36 UTC, Mothblocks commented
i got bad news about that entire file you guys

2021-08-19 15:43 UTC, MrDoomBringer commented
For anyone who wants to do further reading on this subject:
https://github.com/tgstation/tgstation/pull/12722
https://github.com/tgstation/tgstation/pull/19758
https://github.com/tgstation/tgstation/pull/12759

2021-08-19 16:19 UTC, Farquaar commented
*No description provided.*

2021-08-19 17:01 UTC, MrDoomBringer commented
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

Your changelog is also inaccurate, so please update it.

2021-08-19 17:50 UTC, Fikou commented on strings/names/posibrain.txt
> +MOTH
```suggestion
MOTH
CHESSE20
```

2021-08-19 17:50 UTC, Fikou commented on strings/names/posibrain.txt
> +CYBR
```suggestion
CYBR
FIK
```

2021-08-19 17:50 UTC, Fikou commented on strings/names/posibrain.txt
> +BLOK
```suggestion
BLOK
WLTR
```

2021-08-19 17:51 UTC, Fikou commented on strings/names/posibrain.txt
> +BLOK
```suggestion
BLOX
```

2021-08-19 17:51 UTC, Fikou commented on strings/names/posibrain.txt
> +BLOK
```suggestion
BLOK
LEMN
```

2021-08-19 18:06 UTC, Mothblocks commented on strings/names/posibrain.txt
> +MOTH
![image](https://user-images.githubusercontent.com/35135081/130121262-be0937dc-9eeb-4a3a-b783-fa57a4e37a62.png)

2021-08-20 00:59 UTC, optimumtact commented
the next son of a windows admin who posts on my github pr is getting a ban

2021-08-20 01:30 UTC, Tennessee116 commented
holy shit I didn't realize the posibrain names were coder names thats clever

2021-08-20 01:41 UTC, merged

2021-08-20 01:41 UTC, Bawhoppen commented
self-merge, dear god