QDEL_IN harddel prevention
tgstation/tgstation pull request #60937
Opened 2021-08-19 17:53 UTC by BraveMole

## About The Pull Request

QDEL_IN could hardel if the timer was greater than 5 minutes (time for the qdel queue)

we can use weakref to prevent this

## Why It's Good For The Game

## Changelog
:cl:
code: prevent possible QDEL_IN harddel
/:cl:

2021-08-19 17:57 UTC, MrStonedOne commented on code/controllers/subsystem/garbage.dm
> +	var/list/collection_timeout = list(GC_QDEL_IN_CUTOFF, 10 SECONDS) // deciseconds to wait before moving something up in the queue to the next level
I feel like you should change the name to make more sense in this or maybe add a second define and have one use the other

2021-08-20 01:56 UTC, LemonInTheDark commented on code/controllers/subsystem/garbage.dm
> +	var/list/collection_timeout = list(GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT, 10 SECONDS) // deciseconds to wait before moving something up in the queue to the next level
You should define both, and name them like GC_FILTER_QUEUE and GC_DEL_QUEUE or something that describes their purpose rather then just first and second

2021-08-20 01:57 UTC, LemonInTheDark commented on code/controllers/subsystem/garbage.dm
> +	var/list/collection_timeout = list(GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT, 10 SECONDS) // deciseconds to wait before moving something up in the queue to the next level
Or maybe something else, just keep it brief

2021-08-20 09:15 UTC, BraveMole commented on code/controllers/subsystem/garbage.dm
> +	var/list/collection_timeout = list(GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT, 10 SECONDS) // deciseconds to wait before moving something up in the queue to the next level
```suggestion
	var/list/collection_timeout = list(GC_FILTER_QUEUE, GC_DEL_QUEUE) // deciseconds to wait before moving something up in the queue to the next level
```

2021-08-20 09:15 UTC, BraveMole commented on code/__DEFINES/qdel.dm
> +#define GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT 5 MINUTES
```suggestion
#define GC_FILTER_QUEUE 5 MINUTES
#define GC_DEL_QUEUE 10 SECONDS
```

2021-08-20 09:15 UTC, BraveMole commented on code/__HELPERS/qdel.dm
> +#define QDEL_IN(item, time) addtimer(CALLBACK(GLOBAL_PROC, .proc/qdel, time > GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT ? WEAKREF(item) : item), time, TIMER_STOPPABLE)
```suggestion
#define QDEL_IN(item, time) addtimer(CALLBACK(GLOBAL_PROC, .proc/qdel, time > GC_FILTER_QUEUE ? WEAKREF(item) : item), time, TIMER_STOPPABLE)
```

2021-08-20 09:16 UTC, BraveMole commented on code/__DEFINES/qdel.dm
> +#define GARBAGE_QUEUE_FIRST_LEVEL_TIMEOUT 5 MINUTES
```suggestion
#define GC_FILTER_QUEUE 5 MINUTES
#define GC_DEL_QUEUE 10 SECONDS
```

2021-08-20 13:56 UTC, Cyberboss approved these changes

2021-08-20 14:16 UTC, MrStonedOne approved these changes

2021-08-20 15:51 UTC, Cyberboss requested changes

2021-08-20 15:55 UTC, MrStonedOne requested changes
fix up the qdel thing

2021-08-20 16:15 UTC, BraveMole commented on code/__HELPERS/qdel.dm
> +#define QDEL_IN(item, time) addtimer(CALLBACK(GLOBAL_PROC, .proc/qdel, time > GC_FILTER_QUEUE ? WEAKREF(item) : item), time, TIMER_STOPPABLE)
Yes https://github.com/tgstation/tgstation/pull/56171

2021-08-20 18:20 UTC, MrStonedOne approved these changes

2021-08-20 18:28 UTC, merged