Adds an admin signal handler circuit component
tgstation/tgstation pull request #61246
Opened 2021-09-04 19:13 UTC by Watermelon914

## About The Pull Request

Adds an admin signal handler circuit component that allows admin circuits to listen to events on objects and react accordingly. These events can only be stored on 1 datum per component.
Admins can register their own signal IDs by using the circuit component in their hand and filling in the necessary data. This is what the UI looks like:
![image](https://user-images.githubusercontent.com/37270891/132105256-38b7bd27-3317-426d-b5ac-58cfccb2c378.png)
There are presets for some signal ids for admins that don't know how to read the code to add signal ids.

## Why It's Good For The Game

Tooling for events

## Changelog
:cl:
admin: Adds the signal handler circuit component.
/:cl:

2021-09-04 20:00 UTC, Y0SH1M4S73R commented
I've wanted something like this so much I was tempted to code it myself. Love it.

2021-09-04 22:00 UTC, Ghommie commented
You have screwed your commit history.

2021-09-04 23:28 UTC, Watermelon914 commented
> You have screwed your commit history.

It gets squashed on merge. It's because the branch is from #61205

2021-09-04 23:33 UTC, Ghommie commented
Oh, I see.

2021-09-07 22:06 UTC, Mothblocks requested changes

2021-09-16 01:52 UTC, stylemistake commented on tgui/packages/tgui/interfaces/CircuitSignalHandler.tsx
> +                <Stack.Item basis="50%">
Each of the items should use flexible units `grow={1} basis={0}` instead of percentage units `basis="50%"`

2021-09-16 01:52 UTC, stylemistake commented on tgui/packages/tgui/interfaces/CircuitSignalHandler.tsx
> +              <Stack width="100%" height="100%">
```suggestion
              <Stack fill>
```

2021-09-16 13:13 UTC, merged