Rendering refactor P1: Plane unification and render relaying (pictures and video included)
tgstation/tgstation pull request #61286
Opened 2021-09-07 23:14 UTC by TiviPlus

## What does the PR do
This reworks how our rendering is handled, specifically moves away from plane masters as the end solution:
![image](https://user-images.githubusercontent.com/57223640/132421356-11d9b64c-0ac9-4f3a-bf2c-8dca0cd2827b.png)

Instead we replace plane masters rendering directly to client with planes that render multiple planes onto them as objects in order to be able to affect multiple planes while treating them as a single object. This is done by relaying the plane using a "render relay" onto a "render plate" which acts as a plane master of plane masters of sorts, and since planes are rendered onto it as single objects any filters we apply to them will render over the planes, treating them as a single unit
![image](https://user-images.githubusercontent.com/57223640/132421337-64e6b48f-3847-4da8-988e-3298ee4b3551.png)

Also cleaned up unused plane masters and render targets to reduce clutter, as well as removing a useless filter that was resulting from confusion due to said clutter.

Clientside performance testing showed no significant change, no effect on serverside performance as this is clientside.

P2 should introduce rendering one plane to multiple render_plates, but i want to get this done before I finish that,  though testing shows its feasible

### todo
- [ ] Less ghetto example than grav anomaly
- [ ] finish thorough testing
- [ ] Finish doccing

## Why It's Good For The Game

Allows more advanced effects.
As an example i made a grav anomaly effect in like 30 seconds for this video i will improve it once im awake properly:
https://streamable.com/lu98dz

## Changelog

:cl:
qol: grav anomalies now have a pretty effect
refactor: Rendering has been refactored, remember to report bugs
/:cl:

2021-09-07 23:23 UTC, AMonkeyThatCodes commented
![image](https://user-images.githubusercontent.com/20987591/132422529-9688e6c2-8d1c-4d83-8c83-9228043d6471.png)
tg after this pr

2021-09-08 05:25 UTC, SplinterGP commented
https://www.youtube.com/watch?v=VvFybK1Rz9Y

2021-09-15 09:21 UTC, Kylerace reviewed
great pr, makes me think about reducing the amount of screen objects though 🤔

2021-09-15 09:21 UTC, Kylerace commented on code/game/objects/effects/anomalies.dm
> +	var/atom/movable/warp_effect = new(src)
should this be a dedicated subtype?

2021-09-18 17:22 UTC, TiviPlus commented on code/game/objects/effects/anomalies.dm
> +	var/atom/movable/warp_effect = new(src)
changed

2021-09-20 06:55 UTC, Kylerace commented
![Screenshot_1325](https://user-images.githubusercontent.com/15794172/133965691-05859eee-cefd-4606-a7c1-526d516a6f93.png)
broken for both tivi and me, no idea why

2021-09-22 08:55 UTC, TiviPlus commented
Fixed

2021-09-22 22:51 UTC, Kylerace commented on code/modules/power/singularity/singularity.dm
> +	var/atom/movable/warp_effect = new(src)
you made a subtype for this effect specifically

2021-09-22 22:53 UTC, TiviPlus commented on code/modules/power/singularity/singularity.dm
> +	vis_contents += warp_effect//mandatory
```suggestion
		)
```

2021-09-24 01:10 UTC, Mothblocks reviewed
Can you see if #61672 is your fault? It's a similar bug I got until I forced all planes onto the preview.

2021-09-24 04:01 UTC, Mothblocks requested changes
On a round without this TM the character loaded properly, please fix that bug. I can help you navigate character_preview_view or whatever it's called if you need help.

2021-09-27 04:10 UTC, Mothblocks commented
Another bug--sec camera consoles look borked

![image](https://user-images.githubusercontent.com/35135081/134844251-2573d012-c53b-4893-bb10-a294201e7149.png)

2021-09-29 07:27 UTC, optimumtact commented
can i merge it

2021-09-29 09:44 UTC, TiviPlus commented
Works fine apart from #61756 which has no reproduction steps

2021-09-29 09:51 UTC, merged

2021-09-29 09:51 UTC, optimumtact commented
https://www.youtube.com/watch?v=hnxthIijnQ4