converts cows to basic mobs and ADDS MOONICORNS
tgstation/tgstation pull request #61446
Opened 2021-09-14 04:05 UTC by tralezab

## About The Pull Request

Cows are now basic mobs, pretty elementary stuff. Their speed may be slightly different because I couldn't convert `turns_per_move` into `speed` (and trust me i tried)

also, MOONICORNS. They attack with their beautiful unicorn horn, which pacifies on hit. As they walk they spread fairygrass. Aren't they wonderful? As it turns out, no, they're actually incredibly aggressive and their pacification is incredibly deadly as a result.

If you hold something they love, they'll stop attacking. Use this power for good and not evil!

## Why It's Good For The Game
<details>
  <summary>Spoiler warning</summary>
  
  ![image](https://user-images.githubusercontent.com/40974010/133193102-d317f5b2-c7dc-4691-9bec-cfb969cd3269.png)
  
</details>

okay but in all seriousness Moonicorns were a great encouragement to convert another mob to basic mobs while adding some dangerous cyto rewards.

## Changelog

:cl:
add: MOONICORNS. Watch out for their horn!
refactor: during a code refactor for cow, they may be SLIGHTLY faster or SLIGHTLY slower as an accidental result
/:cl:

2021-09-14 09:47 UTC, TemporalOroboros commented
Is charging a datum AI behavior yet? If it is I would recommend giving it to the moonicorns. They've got a giant spike rooted to their forehead.

2021-09-14 11:29 UTC, TemporalOroboros commented
Also, the left-facing moonicorn sprite appears to be missing the horn.

2021-09-14 11:47 UTC, AMonkeyThatCodes commented
can we please not mix refactors and content additions for basic mobs?

2021-09-14 11:48 UTC, AMonkeyThatCodes commented on code/__DEFINES/is_helpers.dm
> +#define iscow(A) (istype(A, /mob/living/basic/cow))
why does this exist

2021-09-14 11:48 UTC, AMonkeyThatCodes commented on code/__DEFINES/is_helpers.dm
> +#define iscow(A) (istype(A, /mob/living/basic/cow))
ok i checked its for one use by abductors. it made me laugh but its still dumb

2021-09-14 11:54 UTC, AMonkeyThatCodes commented on code/modules/mob/living/basic/farm_animals/cows.dm
> +/mob/living/basic/cow/proc/look_for_help(mob/living/carbon/tipper)
this is AI code, dont put it in the mob.

2021-09-14 19:31 UTC, tralezab commented
moonicorns are necessary for this pr because basic mobs are not fun to make

2021-09-14 19:40 UTC, AMonkeyThatCodes commented
just split things up in two prs in the future, its like a miniature extra step.

2021-09-15 01:31 UTC, AMonkeyThatCodes requested changes

2021-09-15 01:31 UTC, AMonkeyThatCodes commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
> +/datum/ai_behavior/tipped_reaction/finish_action(datum/ai_controller/controller, succeeded)
Finish action should have the Same optional arguments as perform (tipper_key at the end)

2021-09-15 01:31 UTC, AMonkeyThatCodes commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
> +	controller.blackboard[BB_BASIC_MOB_TIP_REACTING] = FALSE
Reset the tipper too

2021-09-15 01:37 UTC, Fikou commented
moo

2021-09-15 01:37 UTC, tralezab commented
moo

2021-09-15 01:39 UTC, AMonkeyThatCodes requested changes

2021-09-15 01:39 UTC, AMonkeyThatCodes commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
> +	controller.blackboard[BB_BASIC_MOB_TIPPER] = null
Use the argument ya filthy dog

2021-09-15 01:39 UTC, AMonkeyThatCodes commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
>  	controller.blackboard[BB_BASIC_MOB_TIP_REACTING] = FALSE
Make this an argument ya filthy dog

2021-09-15 01:41 UTC, tralezab commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
> +	controller.blackboard[BB_BASIC_MOB_TIPPER] = null
I DONT SEE MUCH POINT but ok

2021-09-15 01:41 UTC, tralezab commented on code/datums/ai/basic_mobs/basic_ai_behaviors/tipped_reaction.dm
>  	controller.blackboard[BB_BASIC_MOB_TIP_REACTING] = FALSE
I DONT SEE MUCH POINT but ok

2021-09-17 00:47 UTC, merged