Makes clown ops use their own darn defines and fixes nukie icon preference
tgstation/tgstation pull request #61488
Opened 2021-09-15 21:38 UTC by JohnFulpWillard

## About The Pull Request

1) Nukie's icon in the preferences menu has the 2 buddy operatives ABOVE the main one, making it look messy
2) Makes Clown ops use their own defines, like all the other antagonists do, in case you wanted to opt into one type of nukie only. This was possible before the preferences update but was lost, so I'm restoring it.

Before: 
![image](https://user-images.githubusercontent.com/53777086/133512919-20252c37-ae68-4bc2-9760-e5231a350f38.png)

After: ![image](https://user-images.githubusercontent.com/53777086/133512880-8179a1b7-d500-41de-897e-2330c695292c.png)

## Why It's Good For The Game

This used to be an option for people to opt into one type of nukie only, because some people like clown ops, while others don't, and the other way around. Also fixes the nukie icon so it doesnt overlap eachother.

## Changelog

:cl:
qol: Split Nukie and Clown operatives in antag preferences menu
qol: The nukie preference icon's background nukies no longer overlap with the main nukie.
/:cl:

I'm writing the second as QoL because it's not a spriteadd and I wouldn't consider it large enough to be a fix.

2021-09-15 22:12 UTC, Mothblocks commented
:-1: I intentionally didn't make clown ops their own preference--it's run so infrequently that it should just be a surprise, and unlike monkey clown ops is based off nuke ops.

2021-09-15 22:13 UTC, Mothblocks requested changes
I'm still figuring out if I want to block this or not, but it was intentional

2021-09-15 22:13 UTC, Mothblocks commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +	antag_preference = ROLE_CLOWNOP
Just remove this entirely.

2021-09-15 22:13 UTC, Mothblocks commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_CLOWNOP "Clown Operative"
You shouldn't need this because the antag_flag = ROLE_CLOWN_OPERATIVE, just use that instead.

2021-09-15 22:13 UTC, Mothblocks commented on code/__DEFINES/role_preferences.dm
> +	ROLE_CLOWNOP = 14,
ABC order, and use ROLE_CLOWN_OPERATIVE

2021-09-15 22:13 UTC, Mothblocks commented on tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/clownoperative.ts
> +export const OPERATIVE_MECHANICAL_DESCRIPTION = multiline`
Import it from operative instead.

2021-09-15 22:29 UTC, JohnFulpWillard commented
dealt with all the comments, I know it's a rare antag currently, but I know people who would like to opt out of default nukies while still playing clown ops because its a rare silly antag, and I also know people who don't want to play clown ops at all because they don't like the limited gear that comes with it.
It's also a config ruleset meaning that downstreams can have the weight increased, which makes the problem more visible there to people who will end up with 30% of their nukie rounds being as clowns when they would rather be crew than a clownie.

2021-09-16 00:05 UTC, MrDoomBringer commented
I don't see any real merit in trying to hide the fact that clown ops exist from players, especially given that by now everyone knows they've been done before and will likely be done again.

2021-09-16 00:24 UTC, Mothblocks commented on tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/clownoperative.ts
> +
```suggestion
```

2021-09-16 00:25 UTC, Mothblocks commented
Everyone who's experienced knows, but we get new players that stick around all the time!

2021-09-16 02:47 UTC, MrDoomBringer commented
I suppose! Another possibility could be an "Admin's Whim" type preference that says you're okay with admin-ran event antags that might not necessarily be balanced, for better or worse. Could include clown ops while also being used by admins to quickly check if players are likely up for some zany event

2021-09-16 06:49 UTC, wraith-54321 commented
I really hope cloon ops becomes its own pref, I have gotten them for my last 3 nukie games(which were a long time ago but still) it gets old

2021-09-16 07:22 UTC, MrDoomBringer commented
johnfulpwillard alt detected

2021-09-16 09:32 UTC, JohnFulpWillard commented
> johnfulpwillard alt detected

What?

2021-09-17 05:38 UTC, merged

2021-09-17 05:38 UTC, Mothblocks commented
Meh