Gets rid of all the direct /atom/movable subtypes
tgstation/tgstation pull request #61523
Opened 2021-09-17 14:21 UTC by Cyberboss

![image](https://user-images.githubusercontent.com/8171642/133798128-98d4f47a-929c-43b9-a0ac-6a16a1c3a709.png)

Changes all exist `/obj` overrides (aside from a couple lines in obj.dm) to `/obj/basic`.
Changes all direct `/atom/movable` subtypes to be subtypes of `/obj`

Regexes used:
`/obj/([a-zA-Z0-9_]+)(/|\()` -> `/obj/basic/$1$2`
`/atom/movable/((?!proc)[a-zA-Z0-9_]+)(/|\()` => `/obj/$1$2`

@tgstation/commit-access

2021-09-17 14:24 UTC, Timberpoes approved these changes

2021-09-17 14:24 UTC, Cyberboss commented on code/game/objects/obj.dm
> +	vis_flags = VIS_INHERIT_PLANE // when this be added to vis_contents of something it inherit something.plane, important for visualisation of obj in openspace.
Only non-regex change

2021-09-17 14:27 UTC, Cyberboss commented
Fucked up somewhere

2021-09-17 14:58 UTC, Cyberboss commented
VSC capped out when replacing the lines so it's still broken (specifically maps)
I'll leave it up for debate
will fix later

2021-09-17 16:03 UTC, AMonkeyThatCodes commented
whats the overhead on atom/movable? this PR explains nothing and for once I'd agree with MSO if he closed a pr.

2021-09-17 16:38 UTC, Watermelon914 requested changes

2021-09-17 16:38 UTC, Watermelon914 commented on code/_onclick/adjacent.dm
> +/obj/Adjacent(atom/neighbor, atom/target, atom/movable/mover)
```suggestion
/atom/movable/Adjacent(atom/neighbor, atom/target, atom/movable/mover)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/__HELPERS/icon_smoothing.dm
> +/obj/calculate_adjacencies()
```suggestion
/atom/movable/calculate_adjacencies()
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/_onclick/other_mobs.dm
> +/obj/can_interact(mob/user)
```suggestion
/atom/movable/can_interact(mob/user)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Initialize(mapload)
```suggestion
/atom/movable/Initialize(mapload)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Destroy(force)
```suggestion
/atom/movable/Destroy(force)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/update_overlays()
```suggestion
/atom/movable/update_overlays()
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/vv_edit_var(var_name, var_value)
```suggestion
/atom/movable/vv_edit_var(var_name, var_value)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Move(atom/newloc, direction, glide_size_override = 0)
```suggestion
/atom/movable/Move(atom/newloc, direction, glide_size_override = 0)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Move(atom/newloc, direct, glide_size_override = 0)
```suggestion
/atom/movable/Move(atom/newloc, direct, glide_size_override = 0)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Cross(atom/movable/AM)
```suggestion
/atom/movable/Cross(atom/movable/AM)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Crossed(atom/movable/AM, oldloc)
```suggestion
/atom/movable/Crossed(atom/movable/AM, oldloc)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Uncross()
```suggestion
/atom/movable/Uncross()
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Uncrossed(atom/movable/AM)
```suggestion
/atom/movable/Uncrossed(atom/movable/AM)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Bump(atom/A)
```suggestion
/atom/movable/Bump(atom/A)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +	CRASH("/obj/Uncrossed() was called")
```suggestion
	CRASH("/atom/movable/Uncrossed() was called")
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Exited(atom/movable/gone, direction)
```suggestion
/atom/movable/Exited(atom/movable/gone, direction)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/Entered(atom/movable/arrived, atom/old_loc, list/atom/old_locs)
```suggestion
/atom/movable/Entered(atom/movable/arrived, atom/old_loc, list/atom/old_locs)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/hitby(atom/movable/AM, skipcatch, hitpush = TRUE, blocked, datum/thrownthing/throwingdatum)
```suggestion
/atom/movable/hitby(atom/movable/AM, skipcatch, hitpush = TRUE, blocked, datum/thrownthing/throwingdatum)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/CanAllowThrough(atom/movable/mover, border_dir)
```suggestion
/atom/movable/CanAllowThrough(atom/movable/mover, border_dir)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/vv_get_dropdown()
```suggestion
/atom/movable/vv_get_dropdown()
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/vv_get_dropdown()
```suggestion
/atom/movable/vv_get_dropdown()
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/atoms_movable.dm
> +/obj/vv_do_topic(list/href_list)
```suggestion
/atom/movable/vv_do_topic(list/href_list)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/objects/buckling.dm
> +/obj/attack_hand(mob/living/user, list/modifiers)
```suggestion
/atom/movable/attack_hand(mob/living/user, list/modifiers)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/objects/buckling.dm
> +/obj/attackby(obj/item/W, mob/user, params)
```suggestion
/atom/movable/attackby(obj/item/W, mob/user, params)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/objects/buckling.dm
> +/obj/attack_robot(mob/living/user)
```suggestion
/atom/movable/attack_robot(mob/living/user)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/game/objects/buckling.dm
> +/obj/MouseDrop_T(mob/living/M, mob/living/user)
```suggestion
/atom/movable/MouseDrop_T(mob/living/M, mob/living/user)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/modules/keybindings/bindings_atom.dm
> +/obj/keyLoop(client/user)
```suggestion
/atom/movable/keyLoop(client/user)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/modules/lighting/lighting_atom.dm
> +/obj/set_opacity(new_opacity)
```suggestion
/atom/movable/set_opacity(new_opacity)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/modules/lighting/lighting_atom.dm
> +/obj/Moved(atom/OldLoc, Dir)
```suggestion
/atom/movable/Moved(atom/OldLoc, Dir)
```

2021-09-17 16:38 UTC, Watermelon914 commented on code/modules/shuttle/shuttle_rotate.dm
> +/obj/shuttleRotate(rotation, params)
```suggestion
/atom/movable/shuttleRotate(rotation, params)
```

2021-09-17 16:55 UTC, Gandalf2k15 commented
why

2021-09-17 17:33 UTC, Watermelon914 commented
here is why
https://www.byond.com/docs/ref/#/atom/movable

2021-09-17 18:31 UTC, AMonkeyThatCodes commented
byond ref also tells us to use sleep and spawn. Can some more info just be put into the pr body??

2021-09-17 19:16 UTC, ZephyrTFA commented
This seems unneeded. If you unironically trusted what the byond doc tells you is the best practice, you'd also be using sleep, spawn, and the ':' path operator

2021-09-17 19:28 UTC, nemvar commented
> The only reason we override `/atom/movable` subtypes instead of `/obj` subtypes is because we've polluted `/obj` so much we can't use it for anything else. This corrects that by moving all our existing `/obj` procs and vars to `/obj/basic`.

facts

2021-09-17 19:28 UTC, Watermelon914 commented
I have checked both the sleep and the spawn reference pages and they do not say you should be using them in place of timers.
The byond ref explicitly states and says that you shouldn't be creating /atom/movable instances.

Also, doing research will tell you that the byond ref does not recommend you to use `:`
![image](https://user-images.githubusercontent.com/37270891/133843376-316d9229-b6da-4394-bd07-590cdb242b6e.png)

2021-09-17 19:35 UTC, LemonInTheDark requested changes
This regex makes me nervous

2021-09-17 19:35 UTC, LemonInTheDark commented on code/modules/atmospherics/environmental/LINDA_turf_tile.dm
> -
I'm pretty sure this was here in an attempt to keep /atmospherics modular to some extent, similar to the turf vars at the top of the file. Should it stay with uh, less absolute pathing?

2021-09-17 21:53 UTC, AnturK commented
Elaborate shitpost

2021-09-17 22:58 UTC, Mothblocks commented
/obj/basic oml

2021-09-17 22:59 UTC, LemonInTheDark commented
Should be called /obj/simple if you ask me

2021-09-19 03:31 UTC, optimumtact commented
does this have a provable benefit?

Otherwise it's churn for OCD sake and is way too big for the result

2021-09-19 05:40 UTC, Kylerace commented
as far as im aware, /obj has no inbuilt differences from /atom/movable. i dont see the point in this. i like the convention of having /atom/movable more or less be abstract types and /obj be physical types even if we are nowhere near adopting that as a standard and a lot of old code not doing so. but in any case i seriously doubt there is any mechanical reason to use /obj over /atom/movable, they have the exact same vars, and the exact same procs. not to mention this is a mass replace of the father typepath of mobs and obj into just obj which makes me nervous.

2021-09-19 05:48 UTC, Kylerace commented
also if we're including our own addons to both: /atom/movable has significantly more procs than /obj. by my count: there are 23 vars on /obj and 79 procs, and 73 vars on /atom/movable and 141 procs. i dont see how we are polluting /obj

2021-09-19 07:49 UTC, Watermelon914 commented
Here is what lummox has to say about subtyping off of /atom/movable. The worst part, if he ever does it, is probably the last point he made.
![image](https://user-images.githubusercontent.com/37270891/133919715-2cc99c97-5f48-4a5b-8aef-5de604522264.png)

2021-09-19 08:32 UTC, Kylerace commented
this is still a LOT of churn to go through for a distant possibility. if it causes bugs with 51x then we dont update until its fixed or we go through this then.

2021-09-19 15:58 UTC, Cyberboss commented
Don't care anymore

2021-09-19 15:58 UTC, closed without merging