Cytology Adjacent Update #1: New pet food, made from pets. Buffs health of selected simple mobs.
tgstation/tgstation pull request #61532
Opened 2021-09-17 23:44 UTC by Krysonism

## About The Pull Request
This PR introduces a new craftable food: dog eat dog envirochow

Feeding this to a beast, bug or reptile increases its maximum health by 10 hp or 10% of what their maximum health was when the first stack was applied, whichever is greater.

It also heals them for 20hp or 20% of their maximum health, whichever is greater.

Maxium of 3 applications for a 30 hp or 30% health increase.

the recipe is:

2 corgi meat, 5 vitamin

The crafting category is meat. 

## Why It's Good For The Game
This PR adds some value to the corgi mob, which is interesting since it can be obtained through a several methods. 

Previously people who did cytology would almost exclusively try to grow the biggest meanest mob and disregard everything else. 

And even those who chose to make a utility creature, would probably choose to make cats since they are more profitable or carps since you can ride them and their meat is more useful.

This addition makes corgi farming a good side activity while you wait for sentience potions for your bigger mobs.

It also affirms the goal of cytology to make scientists create a few quality mob they are invested in, rather the quantity approach seen with gold slime strategies.

## Changelog

:cl:
add: Added new food, envirochow; it permanently increases the max hp of animals.
/:cl:

2021-09-17 23:45 UTC, Krysonism commented
nooooooo i accidentally tagged it as mechanic

2021-09-17 23:53 UTC, Krysonism commented
I want slimes and oozes to be able to use this in the future, but it turns there isn't a slime biotype yet.

2021-09-17 23:56 UTC, TemporalOroboros commented
Just so you know, the `MOB_BEAST` bit means this can be applied to goliath broodmothers. Otherwise, I look forward to the eventually inevitable swarm of 40 health bees.

2021-09-20 00:39 UTC, Twaticus approved these changes

2021-09-28 00:01 UTC, Bawhoppen commented
We get close to readding steal corgi meat objective every day

2021-09-28 11:15 UTC, tralezab requested changes
final note: thanks for cleaning up dmis a bit

2021-09-28 11:15 UTC, tralezab commented on code/datums/status_effects/buffs.dm
> +/datum/status_effect/limited_buff/health_buff/on_creation(mob/living/new_owner, ...)
you don't want to inherit that, exactly

```suggestion
/datum/status_effect/limited_buff/health_buff/on_creation(mob/living/new_owner)
```

2021-09-28 11:15 UTC, tralezab commented on code/datums/status_effects/status_effect.dm
> +/datum/status_effect/limited_buff/refresh(effect, ...)
same as above, you don't want to inherit that

```suggestion
/datum/status_effect/limited_buff/refresh(effect)
```

2021-09-28 11:15 UTC, tralezab commented on code/datums/status_effects/status_effect.dm
> +	. = ..()
since limited buffs don't have duration, you can actually probably cut this since it doesn't do anything

2021-09-28 23:32 UTC, tralezab requested changes
missed one last thing, everything else looks good

2021-09-28 23:32 UTC, tralezab commented on code/game/objects/items/food/misc.dm
> +						span_notice("You hear sloppy eating noises."))
only indent once for the visible message, kinda like how you don't want to over-indent for lists

2021-09-29 00:07 UTC, merged