Adds a new achievement and command report for cultists obliterating Centcom's shuttle corps
tgstation/tgstation pull request #61566
Opened 2021-09-19 08:22 UTC by Ryll-Ryll

## About The Pull Request
This is based on an occasional gag I like to do while adminning when cultists rapid-fire off 3 shuttle curses one after another, where I send a command report begging whatever's on the station to leave the shuttle workers alone. After all, seeing one case of a coworker mutilate themselves out of nowhere would be disturbing, but having 3 incidents happen almost simultaneously? That'd be a lot to bear!

If a cult uses all 3 of their shuttle curses within 10 seconds of the first one, all members of the cult who are currently connected will get the new achievement, named "WHAT JUST HAPPENED". In addition, a few seconds after the last use, Centcom will send a new report expressing shock and distress at whatever horrible scene just played out on their end.

[![dreamseeker_2021-09-19_04-20-09.png](https://i.imgur.com/XmxjuvRl.jpg)](https://i.imgur.com/XmxjuvR.png)

This PR also adds a few new curse announcement messages for good measure.

## Why It's Good For The Game
I think this is a pretty funny niche interaction that could totally catch players off guard for some good laughs.

## Changelog

:cl: Ryll/Shaps
add: Added a new achievement for cultists who like to mess with NT's shuttle corps, "WHAT JUST HAPPENED".
/:cl:

2021-09-19 08:26 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +		for(var/i in 1 to 3) // can't use pick_and_take() with json, so we just do 3 shots at pulling a message we haven't used yet, probably good enough
you could make this work but its not really necesasry ig uess

2021-09-19 08:27 UTC, Mothblocks commented on code/modules/antagonists/cult/cult_items.dm
> +		for(var/i in 1 to 3) // can't use pick_and_take() with json, so we just do 3 shots at pulling a message we haven't used yet, probably good enough
you'd just call `json_load(CULT_SHUTTLE_CURSE)`, save its curse_announce field somewhere, then pick'n'take that

2021-09-19 09:23 UTC, tralezab reviewed
beep boop good pr son

2021-09-19 09:23 UTC, tralezab commented on strings/cult_shuttle_curse.json
> +	]
requesting some form of CHELP

2021-09-19 09:23 UTC, tralezab commented on code/__DEFINES/misc.dm
> +#define CULT_SHUTTLE_CURSE "cult_shuttle_curse.json"
we should really eventually move either all the string path defines into their own file or files that make the most sense for them in the future

not something you have to do btw just food for thought

2021-09-19 09:23 UTC, tralezab commented on code/modules/antagonists/cult/cult_items.dm
> +			for(var/mob/iter_player in GLOB.player_list)
```suggestion
			for(var/mob/iter_player as anything in GLOB.player_list)
```
everything in the player list is a mob so should be fine

2021-09-19 10:13 UTC, Mothblocks commented on strings/cult_shuttle_curse.json
> +	]
;;;;;;;HELP

2021-09-25 10:54 UTC, Mothblocks requested changes
merge from upstream so ci can pass

2021-09-26 02:37 UTC, merged