Adds the Proximity Pinpointer component!
tgstation/tgstation pull request #61574
Opened 2021-09-19 21:37 UTC by TheSmallBlue

## About The Pull Request
This is a sort of remake of my old GPS-input PR (#60596). 
The old PR also had this but I wanna clarify it, this version takes sight into consideration. By that I mean that it doesn't just check for a range, it also checks whether the target is in sight. 

Almost absolutely nothing else in the entire codebase uses the same proc that I use to do the whole sight check thingie, which is VERY worrying, but I couldn't find an alternative so c'est la vie.

Here are a couple of videos of me testing it out (ignore the inconsistent file names ty):

https://user-images.githubusercontent.com/24967815/133943757-9d9df0da-e6c2-448f-9359-fe1e843ace42.mp4

https://user-images.githubusercontent.com/24967815/133943478-b935eb6c-b331-4a99-afd0-bcdea6c73bef.mp4
(notice on this one how clicking on the black tiles will not make me say anything, that's because I can't see there!)

## Why It's Good For The Game
Allows for further freedom when wanting to code cool circuits. Also Watermelon wanted this.

## Changelog

:cl:
add: Added the Proximity Pinpointer component, get the coordinates of any entity! (As long as its in view)
/:cl:

2021-09-19 22:24 UTC, Watermelon914 requested changes
Consider adding an On Error signal port for when it is unable to get the location of the target.

2021-09-19 22:27 UTC, LemonInTheDark commented
man this title threw me

2021-09-19 22:47 UTC, TheSmallBlue commented
@Watermelon914 Is that what you mean?

2021-09-20 14:50 UTC, Watermelon914 commented on code/modules/wiremod/components/atom/pinpointer.dm
> +
return TRUE here so that the output trigger doesn't get triggered.

2021-09-20 14:50 UTC, Watermelon914 commented on code/modules/wiremod/components/atom/pinpointer.dm
> +	if(isInSight(target_entity, parent.shell) && IN_GIVEN_RANGE(parent.shell, target_entity, max_range))
use get_turf instead of getting the parent's shell.

2021-09-20 15:53 UTC, TheBonded commented
This is extremely based, autonomous bots are finally going to be able to do things on their own

2021-09-20 19:19 UTC, Watermelon914 approved these changes

2021-09-22 00:12 UTC, merged