Getting hit by the tram will now smash people through lattice and unplated flooring
tgstation/tgstation pull request #61709
Opened 2021-09-26 03:28 UTC by Ryll-Ryll

## About The Pull Request
A common administrative issue and general gripe about Tramstation is the practice of players using lattice or floor tiles to cover up the big open pits people fall down when they're hit by the tram, making it so they're doomed to get hit again and again and again, racking up massive damage and quickly becoming lethal. This PR changes the tram to cause people it hits to smash right through lattice or unplated flooring, suffering some additional damage along the way. 

[![2021-09-25_22-58-58.png](https://i.imgur.com/USQgQzTl.jpg)](https://i.imgur.com/USQgQzT.png)

If you still want to see people get memed to hell, you can simply take the extra time to add plating to the floor tiles, but at least then admins know that you're purposely trying to get people killed and not just a naïve person thinking that keeping people from falling to the z-level below improves safety rather than massively decreases it.

[![Discord_2021-09-25_23-22-00.png](https://i.imgur.com/3ZOXZDsl.jpg)](https://i.imgur.com/3ZOXZDs.png)
Support from the resident tram expert, @tralezab 

## Why It's Good For The Game
Hopefully reigns in the tram's extreme lethality when players modify the environment in certain ways

## Changelog

:cl: Ryll/Shaps
balance: Getting hit by the tram and landing on lattice or unplated flooring (on the upper z-level) will now cause you to smash through it and fall to the z-level below at the cost of taking some extra damage. Note that floors with plating will still hold steady, so you can still use flooring to make getting hit by the tram insanely lethal, it just takes a bit more effort.
/:cl:

2021-09-26 03:32 UTC, Mooshimi commented
Your branch and merge names are funny, also I support this

2021-09-26 03:42 UTC, Mothblocks commented
![image](https://user-images.githubusercontent.com/35135081/134792656-f7e7e9d3-e7d9-454e-bba7-e3bafc2227c4.png)

u gotta fix ur snippie

2021-09-26 03:45 UTC, Mothblocks approved these changes
other than that good

2021-09-26 14:36 UTC, SmArtKar commented
I think that this won't fix the issue, people will just additionaly put tiles which will take them just a bit more time.

2021-09-26 17:24 UTC, iwishforducks commented
> I think that this won't fix the issue, people will just additionaly put tiles which will take them just a bit more time.

From the PR body:
> but at least then admins know that you're purposely trying to get people killed

2021-09-26 20:31 UTC, MMMiracles commented
i was against this until i saw you can still make the tram tunnel hyper-lethal with floor tiles, so this is a fine change

also that branch name lmao

2021-09-26 23:12 UTC, Mothblocks commented
To clarify, the problem Shaps is describing is something I've echoed with them for a long time.

People will frequently place tiles on the Tram tracks. This makes the tram super-deadly-no-coming-back-without-a-competent-and-bored-medbay deadly. Unlike something like people blowing it up with field generators, there is a good faith argument to be made that "oh well I just wanted it to be easier to cross the tracks". Whether they're lying or not, it's come up so often (more than half of all Tram rounds I've been in) that it becomes exhausting and I begged for something like this instead.

We are not (just) trying to stop griefers, we're making sure those bad faith griefers lose their good faith argument.

2021-09-28 03:32 UTC, Mooshimi commented
> Go go gadget floorbot
> B)

except they die whenever the tram goes by lmfao

2021-09-28 13:33 UTC, maxymax13 commented
the better solution is make it so trying to place stuff in the tiles the tram goes over instantly gibs and round removes you, gives you a bad note and job bans you from engineering permanently

2021-09-28 18:04 UTC, Mooshimi commented
> the better solution is make it so trying to place stuff in the tiles the tram goes over instantly gibs and round removes you, gives you a bad note and job bans you from engineering permanently

it's not engineers who do this most the time from what I've seen. anyone does it including borgs

2021-09-28 22:02 UTC, Mothblocks commented
@Ryll-Ryll Ready?

2021-09-30 05:28 UTC, Ryll-Ryll commented
ya sure

2021-09-30 05:32 UTC, Mothblocks requested changes

2021-09-30 05:32 UTC, Mothblocks commented on code/modules/mob/living/living.dm
> +			bye_bye.deconstruct(FALSE)
```suggestion
	for(var/obj/structure/lattice/lattice in loc)
		visible_message(span_danger("[src] is thrown violently into [lattice], smashing through it and punching straight through!"),
			span_userdanger("You're thrown violently into [lattice], smashing through it and punching straight through!"))
		apply_damage(rand(5,10), BRUTE, BODY_ZONE_CHEST)
		lattice.deconstruct(FALSE)
```

2021-10-02 07:03 UTC, LemonInTheDark commented
@Mothblocks I want this. Any reason not to go?

2021-10-02 08:39 UTC, Mothblocks commented
i was waiting for ci

2021-10-02 08:39 UTC, merged