Constructable Filing Cabinets
tgstation/tgstation pull request #61746
Opened 2021-09-28 03:58 UTC by 567Turtle

Construct filing cabinets for 4 metal sheets

## About The Pull Request

Literally just made it so you can construct a filing cabinet for 4 iron sheets

## Why It's Good For The Game

I constantly find myself going "Damn, if only there was a way I could make filing cabinets!" And now there is. For the cheap cheap price of 4 metal sheets. This was mostly made as a beginning practice for myself as I learn C and try to do some coding.

## Changelog

:cl: 567Turtle
add: Filing cabinets can be constructed for 4 metal sheets
/:cl:

2021-09-28 04:19 UTC, tralezab requested changes
make the price of constructing the cabinet the same as what you get from destroying it, please. otherwise good first pr

2021-09-28 04:19 UTC, tralezab commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new /datum/stack_recipe("filing cabinet", /obj/structure/filingcabinet, 15, time = 10 SECONDS, one_per_turf = TRUE, on_floor = TRUE), \
```suggestion
	new/datum/stack_recipe("filing cabinet", /obj/structure/filingcabinet, 15, time = 10 SECONDS, one_per_turf = TRUE, on_floor = TRUE), \
```

2021-09-28 04:57 UTC, 567Turtle commented
> make the price of constructing the cabinet the same as what you get from destroying it, please. otherwise good first pr

Did and done, it should be 2.

2021-09-28 05:15 UTC, tralezab approved these changes

2021-09-28 13:38 UTC, maxymax13 commented
hahaha nukies you fools, i have stolen your pinpointer! if you want to find the disk you will have to go in this room and open every one of these 500 filing cabinets until you find the disk, and there will be food items renamed with a pen to say "nuclear authentication disk"! have fun! wait what are you doing with that rocket launch

2021-09-29 03:55 UTC, Mothblocks commented
I constantly find myself going "Damn, if only there was a way I could make filing cabinets!"

2021-09-29 03:55 UTC, merged

2021-09-29 03:59 UTC, 567Turtle commented
![](https://cdn.discordapp.com/attachments/326831214667235328/892620912661237770/maxresdefault.png)