Moth Food: a Taste of the Fleet
tgstation/tgstation pull request #61743
Opened 2021-09-28 02:34 UTC by EOBGames

## About The Pull Request
In this thrilling sequel to #59412, Moths get the culinary overhaul they've needed for a while.
Adds somewhere in the region of 50 new foods, all tied together by a connection to Moths and their culture, as well as around 10 new drinks.
![image](https://user-images.githubusercontent.com/58124831/135012623-2f882da4-3ac9-4ddf-890f-cf22fe1de3c4.png)
As with #59412, this PR has three aims:
1. Introduce moth culture (as it exists in Common Core lore) to the game in a tangible way.
2. Give further variety to the chef and bartender, including some form of new cooking challenge for them.
3. To give some flavour (metaphorically and literally).

![image](https://user-images.githubusercontent.com/58124831/135012799-f3eb7183-9914-4057-81e9-03353be0edea.png)
This time, I actually will include a complete list of the new foods and their recipes: https://pastebin.com/2VLfUfDx
As a nomadic people, moths have a wide variety of foods from various cultures. In particular, they've adopted a lot from humanity. Expect a mix of stranger and more distinctly alien foods, along with some human classics that have underwent a mothic transformation.
![image](https://user-images.githubusercontent.com/58124831/135012988-fbb2df53-9a8d-462f-826b-97216c39c817.png)
Töchtaüse Berries
![image](https://user-images.githubusercontent.com/58124831/135013058-69a63013-d96d-4225-ad75-da68e98d3d68.png)
A popular food on the Mothic Fleet, töchtaüse berries are well known for being deeply unpleasant while raw: they're spicy, bitter, and filled with a mild poison that causes itching. Once heated to a sufficient temperature and mixed with sugar, however, they're a complex flavour that adds nicely to both sweet and savoury dishes.

## Why It's Good For The Game
The lizard food PR was a good first step in making Common Core lore better integrated with the game, but it was only that: a start. This is a continuation that should keep that trend going and making the universe deeper.

## Changelog

:cl:
add: The release of the new cookbook, "Mothic Cuisine: from Fleet to Flotilla" has brought Mothic food to the masses! Try out some new treats, like cheesecake balls, cheese soup, and five-cheese pizza at the kitchen today! There might even be some foods that don't have cheese, too!
add: To coincide with the new popularity of Mothic cuisine, Nanotrasen now stocks seeds for Töchtaüse Berries, a common ingredient in moth cooking, in the Megaseed vendors. Additionally, herbs and bell peppers have also made their way to the station's stock. Botanists, you know what to do.
/:cl:

2021-09-28 02:51 UTC, CRITAWAKETS commented
also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself

2021-09-28 02:56 UTC, EOBGames commented
> also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself

Sorry, I don't recognise the existence of the Quebecois. Not Quebec, it exists, just the Quebecois.

2021-09-28 02:59 UTC, CRITAWAKETS commented
> > also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself
> 
> Sorry, I don't recognise the existence of the Quebecois. Not Quebec, it exists, just the Quebecois.

you absolute buffoon, dont you fill silly, even a little stupid

I EXIST
therefore
THE QUEBECOIS EXIST
you can scream now

2021-09-28 03:02 UTC, CRITAWAKETS commented
> c'eci n'est pas un canadien

thats it, flooding your discord DMs with quebecois insults

2021-09-28 03:49 UTC, JohnFulpWillard commented
> 
> 
> also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself

Don't we already have poutine?

2021-09-28 08:14 UTC, Zytolg commented
> > also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself

Only he totally did. It's just not called Poutine.

2021-09-28 09:10 UTC, necromanceranne commented on code/game/machinery/computer/chef_orders/order_datum.dm
> +	name = "Yoghurt"
Is this meant to be here twice?

2021-09-28 09:13 UTC, necromanceranne commented
> > also you added cheese curds but you didnt add poutine, missed opportunity if i say so myself
> 
> Don't we already have poutine?

I'm pretty sure someone removed it or something.

2021-09-28 09:15 UTC, necromanceranne commented
Anyway I'm just happy we finally have bell peppers

2021-09-28 09:45 UTC, Fryzzie commented
I am disappointed there is no pizza with socks on it.

2021-09-28 11:29 UTC, Mothblocks requested changes
Revert your changes of rust_g.dll, you made them by mistake.

Close Dream Daemon when doing so, that is why you are getting permission errors.

2021-09-28 12:06 UTC, carshalash commented
Uhh, dude, you forgot to change the drink qualities. Baselines are fantastic while the cocktails are nice.

2021-09-28 18:11 UTC, EOBGames commented
> Uhh, dude, you forgot to change the drink qualities. Baselines are fantastic while the cocktails are nice.

Resolved. Curacao is no longer the best drink on station, it's only the best in real life now.

2021-09-28 20:40 UTC, ExcessiveUseOfCobblestone commented
when you say 50 new food items are you saying you added 50 new moth exclusive food items?

2021-09-28 23:38 UTC, Farquaar commented
I don't know. I expected their food to look more "insect-y". This just looks like human food with alien ingredients..

2021-09-29 04:49 UTC, EOBGames commented
> when you say 50 new food items are you saying you added 50 new **moth exclusive** food items?

I added around 50 new food items, of which the vast majority are also fine for the other species. There are only two which are explicitly "moth exclusive", because they use cotton and are therefore under the cloth foodgroup. About the only thing I'd say is that lizards won't get much mileage out of this food given how dairy and grain based it is, but given they just got the lizard food PR a few months back (which was similar to this in that not many of the foods were lizard-only) I don't think they'll be hurting for it.

2021-09-29 05:49 UTC, EOBGames commented
the merge conflict did not, in fact, go away

2021-09-30 04:49 UTC, EOBGames commented
this PR is killing me, it will return but this particular branch is a lost cause

sorry to anyone who was excited but I can't do this anymore

2021-09-30 04:49 UTC, closed without merging