Sentient Cheese Fix
tgstation/tgstation pull request #61765
Opened 2021-09-29 00:36 UTC by 567Turtle

I made it so Megafauna and other hostile foes will fight sentient animals.

## About The Pull Request

When making a corgi or whatsoever sentient before, the megafauna, or any other hostile, wouldn't attack them. This _should_ fix it.

## Why It's Good For The Game

Fix to issue #61702

## Changelog

:cl: 567Turtle
Made it so megafauna will attack sentient mobs.
/:cl:

2021-09-29 01:40 UTC, dondonpow commented
I was hoping this PR fix not being able to turn cheese wheels into sentient creatures. Sad!

2021-09-29 01:59 UTC, 567Turtle commented
> I was hoping this PR would fix not being able to turn cheese wheels into sentient creatures. Sad!

im sorry for the let down

2021-09-29 06:03 UTC, tralezab requested changes

2021-09-29 06:03 UTC, tralezab commented on code/modules/research/xenobiology/xenobiology.dm
> +		SM.faction = list("neutral")
you should include the mob's reference as a faction as well, all living mobs have a faction to themselves!

https://github.com/tgstation/tgstation/blob/c10e1e60db4bfba3e9c0ca543a24223a37a25304/code/modules/mob/living/living.dm#L1-L10

```suggestion
		SM.faction = list([REF(src)], "neutral")
```

2021-10-02 07:03 UTC, LemonInTheDark commented
Doesn't this mean sentient mobs will be hated by their peers? That's a bit of a shame

2021-10-24 00:10 UTC, closed without merging