Removes the augment painter, moves the function to spraycan rightclicking.
tgstation/tgstation pull request #61814
Opened 2021-10-01 04:16 UTC by zxaber

## About The Pull Request
Right-clicking a robotic body part with a spraycan will open a radial menu and allow for coloring the body part just like the augment painter did. This costs five charge off the spraycan, meaning a single can will paint six augments.

The augment painter has been removed from the game files and from all maps.

## Why It's Good For The Game
I can count on one hand the number of times I've *seen* anyone bother painting augments, and I play robotics more than any other role. Generally, the machine just sits in the way until I need the space and I shove it into the halls to get lost somewhere.

For anyone that does enjoy their colored robot parts, a spray can is obtainable from an autolathe.

## Changelog

:cl:
del: The augment painter has been removed from the game.
add: Spraycans can now change the visual style of robotic augments via right-click.
/:cl:

This time with an updated branch.

2021-10-01 05:18 UTC, Mothblocks commented on code/game/objects/items/crayons.dm
> +	. = ..()
Never return `..()` from secondary attacks, its behavior I'm going to remove someday.

```suggestion
	return SECONDARY_ATTACK_CONTINUE_ATTACK_CHAIN
```

2021-10-01 05:19 UTC, Mothblocks requested changes

2021-10-01 05:19 UTC, Mothblocks commented on code/game/objects/items/crayons.dm
> +		to_chat(user, span_warning("Take the cap off first!"))
```suggestion
		balloon_alert(user, "take the cap off first!"))
```

2021-10-01 06:00 UTC, Mothblocks commented on code/game/objects/items/crayons.dm
> +	return SECONDARY_ATTACK_CONTINUE_ATTACK_CHAIN
```suggestion
	return SECONDARY_ATTACK_CONTINUE_CHAIN
```

my bad

2021-10-01 07:51 UTC, AndroidMK2 commented
Would be nice to be able to change the augment color too rather than just it's style.

2021-10-03 15:03 UTC, Maurukas approved these changes

2021-10-06 12:21 UTC, merged