nitryl and stimulum merge in nitrium
tgstation/tgstation pull request #62061
Opened 2021-10-11 16:21 UTC by Ghilker

## About The Pull Request
Re-take of #57384 that i stopped cause i was busy

This PR is the first of a few were i'll be merging similar working gases into one.
This time is Nitryl and Stimulum. They'll be merged into Nitrium , a brown gas with both features of the two gases
The main scope is to add dept to atmos by removing bloated content and/or repeated content that has never seen the lights of the day (how many times have you seen both gases made and used at the same time?)
The PR so far:
-removed nitryl
-removed stimulum
-merged them into Nitrium (Nitrium is now made with trit, nitrogen and bz from a minimum temperature of 1500 K)
-made Nitrium have both gases features such as fast movements and sleep and stun immunity but increased damage taken
-Nitrium can make crystals that spread the chemicals with a cloud (is still far more efficient to just breathe the gas)

## Why It's Good For The Game
Less rare gases, going towards a better atmos gameplay loop

## Changelog

:cl:
del: removed nitryl
del: removed stimulum
balance: merged the two into nitryum that shares the two gases features and that can make a crystal of itself in the crystallizer, the gas is made with trit, nitrogen and bz at over 1500 K
balance: the gas effect can be chosen by the partial pressure of the gas, low pressure and you have the old nitryl effect, higher and you'll have both
/:cl:

2021-10-28 00:29 UTC, LemonInTheDark requested changes
I'm kind of curious about your particular reasons for doing this rather then removing one or the other, at least since gas count doesn't impact react cost anymore. You mind elaborating on that?

2021-10-29 20:11 UTC, Pickle-Coding commented
If it decomposes into hydrogen, it should release radiation.

2021-11-02 04:01 UTC, LemonInTheDark commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		"MAX_TEMP" = 45
yeah, but max of 45 means normal enviroments can take it

2021-11-02 04:05 UTC, LemonInTheDark commented on code/modules/atmospherics/gasmixtures/reactions.dm
> -		"MAX_TEMP" = 10000
I don't like changing things for weakish reasons if we don't know why they were done in the first place

2021-11-02 11:01 UTC, Ghilker commented on code/modules/atmospherics/gasmixtures/reactions.dm
> -		"MAX_TEMP" = 10000
I added that when doing the 5 new gases lol, just added it for the sake of it https://github.com/tgstation/tgstation/pull/53013#discussion_r479633090 just after this i made the commit and i added a min and max temp, no reason to it, just added it.

2021-11-03 00:03 UTC, LemonInTheDark commented on code/modules/atmospherics/gasmixtures/reactions.dm
> -		"MAX_TEMP" = 10000
lmao

2021-11-10 00:47 UTC, LemonInTheDark commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		"MAX_TEMP" = 45
Still not happy with this

2021-11-10 20:29 UTC, Ghilker commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		"MAX_TEMP" = 45
```suggestion
		"MAX_TEMP" = T0C + 70 //Pretty warm, explicitly not fire temps. Time bombs are cool, but not that cool. If it makes you feel any better it's close
```

2021-11-10 20:30 UTC, Ghilker commented on code/modules/atmospherics/gasmixtures/reactions.dm
> +		"MAX_TEMP" = 45
i've set it as nitryl was

2021-11-14 11:42 UTC, LemonInTheDark commented
On further thought, why merge the two? If the goal is to simplify things one gas with two sets of effects seems a bit unhelpful.

I realize we're in a bit of a funny position because stim is used as an endgame crafting tool, and nitryl is budget stim and all, but I'm not really sure what this accomplishes outside of just lowering the gas count. 
I'm happy to do that, I don't like the idea of many gases that are just straight upgrades of each other, mostly because atmos isn't the same as say chem, and we can't have big progression trees. But in this case it'd be done to make things easier to understand, and it seems like we're ending up with a frankengas

IDK maybe I'm overthinking this. What do you think?

2021-11-14 12:32 UTC, Ghilker commented
From the discord answer
I'm doing it because I'd like to reduce the gas count to have more do to with each gases (increase depth for each one of them) before adding more back. Stim and Nitryl have a similar effect that is to improve movement, so I started with merging them into one gas that has more in it than the two gases separated. I think it would be much better to reduce the gas number by merging them to increase the pool of usability for each one of them and reduce the gas doing the same thing (like H2 and Trit, was thinking of having only H2 but is debatable) before adding more.

> I'm happy to do that, I don't like the idea of many gases that are just straight upgrades of each other, mostly because atmos isn't the same as say chem, and we can't have big progression trees. 

This is the main goal, I don't want similar gases that are weak upgrades/downgrades to others, I just figured to start with these two

2021-11-17 09:56 UTC, merged