co2 SM a bit more dangerous
tgstation/tgstation pull request #62072
Opened 2021-10-12 10:55 UTC by Ghilker

## About The Pull Request
Increase the CO2 SM heat penalty to 6

## Why It's Good For The Game
CO2 SMs are too easy to set and forget, we should strive to have only the basic N2 setup to be set and forget or to have an actual effort to reach a mix and a setup that is basically set and forget (like plasma SM with a dynamic pressure release that you build)

## Changelog

:cl:
balance: Increase the CO2 SM heat penalty to 6
/:cl:

2021-10-14 03:07 UTC, daplanman12 commented
Yet another change that is unnecessary and only serves to make the game worse by forcing engineering to play how Ghliker thinks is correct. CO2 SMs are already more fragile and vulnerable to sabotage as a result of being closer to delam levels, no need to make them need to be babied so that players won't try to experiment with them.

2021-10-14 05:46 UTC, Pickle-Coding commented
Currently standard SM (replacing useless pumps only) can easily handle CO2 up to 5GeV, and near 7GeV if you add protection against anomalies. It having a heat penalty of 0.1 (it gets clamped to a minimum of 0.5) makes it produce the same heat as an N2 engine per eV, and has a higher specific heat than N2, making it a better coolant. It is much more stable than just adding extra emitters for even less effort.

You wouldn't need an extreme engine for this change unless you're planning to get above 9GeV, it will just make the roundstart setup not handle it so easily.

2021-10-16 06:45 UTC, LemonInTheDark requested changes

2021-10-17 09:50 UTC, FernandoJ8 commented
Good change, CO2s are way too stable and easy for how efficient they are

2021-11-02 10:49 UTC, Ghilker commented on code/__DEFINES/supermatter.dm
> +#define CO2_HEAT_RESISTANCE -2
i made some changes and the number will not go under 0. 
the SM doesn't take extra damage on something like 4500 MeV (the basic range of a CO2 SM)

2021-11-03 01:57 UTC, LemonInTheDark commented on code/__DEFINES/supermatter.dm
> +#define CO2_HEAT_RESISTANCE -2
If you want to disincentivize co2 sms why not tweak the things that already exist?

2021-11-06 16:11 UTC, Coastfront commented
Considering CO2 is meant to be one of the roundstart gasses that is difficult to run a sm on (so far the only super challenging ones is stuff like trit and plasma) yeah this is good.

2021-11-14 11:37 UTC, LemonInTheDark commented
Fuck it

2021-11-14 11:37 UTC, merged

2021-11-22 23:45 UTC, KareRott commented
This change does not add fun. I understand that you want to encourage people to make more interesting setups. But in reality, all this change really does is keep people from wanting to branch out from n2. This does not promote diversity.

However, I've a suggestion that might make this more interesting. Keep the heat value change but increase the co2 consumption and increase the potential plouxium output.  (I can imagine You'd still have to use other gasses and a very robust cooling setup in order to run such a loop. the crystal may even be on fire half the time because of the new heat penalty.)

There are many an atmos tech who dream of replacing the station's o2 with plouxium, but the task of such is absolutely gargantuan, and still would be with such a change. However, this would at the very least preserve the spirit and promote more diverse SM builds.

2021-11-22 23:53 UTC, KareRott commented
Oh uh, pure co2 setups are currently impossible by the way, not sure if that was really intended but you should really test a pure co2 loop with this current change to see what I mean. Like, if you intended to make it produce the same amount of eVs as an n2 setup, it just won't without delaming.