Changes Plasmamen belt tanks volume and the rate that their lungs consume plasma to 1/4 of the previous value.
tgstation/tgstation pull request #62081
Opened 2021-10-12 23:25 UTC by GuillaumePrata

## About The Pull Request
Plasmamen belt tank volume is 24, the extended engineering one is 6 and the emergency internals are 3.
The issue balance wise is that all of those have the same pocket size and can be printed at the same Research tier, this results on smart atmos/engineers printing a plasmamen belt tank and filling it with O2 so their internals can last for almost 2 hours instead of the 24 minutes of the extended O2.

Now they have the same volume but plasmamen lungs were rebalanced to consume plasma at a lower rate. To be clear, it will have no effect on how long the internal last for a plasmamen.

## Why It's Good For The Game
Removes a no skill trick that gives you internals that will last for all shift, you can still make those but it will take a tiny bit of effort now.

Also a small step to make internals balanced.

## Changelog

:cl: Guillaume Prata
balance: Plasmamen belt tanks volume and the rate that their lungs consume plasma got lowered to 1/4 to stop the easy 2 hour long O2 inside a plasmamen belt tank trick. It doesn't change how long the internals last for plasmamen.
/:cl:

2021-10-12 23:32 UTC, LemonInTheDark commented
> 
> 
> > If they're gonna breath differently then humans, add them to the unit test that checks to make sure that humans can actually breath internals please
> 
> Okay there goes the easy balance change, I will need to look up how to do this.

I'll give you gbp. <https://github.com/tgstation/tgstation/blob/master/code/modules/unit_tests/breath.dm>

2021-10-13 01:02 UTC, LemonInTheDark requested changes
Seems good outside of a few nitpicks, thank you

2021-10-13 01:05 UTC, Mothblocks requested changes

2021-10-13 01:43 UTC, Krysonism commented
It would be cooler if the plasmaman tanks were made unprintable but retained their greater volume.

Having a stronger but scarce item is in my mind preferable to just having another reskin.

2021-10-13 04:49 UTC, GuillaumePrata commented
> Come to think of it, plasmaman tanks are only really different from other tanks because of their size right?

As far as things that really affect balance, yes, only an increased volume.

2021-10-21 23:43 UTC, GuillaumePrata commented
> Why not just make the plasma tanks the same size as other tanks, but make the gas really cold so it's volume is really compact? As far as I know, plasmamen have resistance to low temperatures.

This would be a simple way to fix it without touching Plasmamen lungs but, while it can last the same time with some math for the right temp, it is a small nudge to push players to ultracool their internals which I think just destroy any semblance of internals balance that exists in the game and would go against the goal of the PR.

Finding the lowest magical number that your lungs can breath by reading the code and making internals on the edge of that is something I would like changed in the future already.

2021-11-02 09:06 UTC, merged