Moves hair gradients to the preferences menu
tgstation/tgstation pull request #62102
Opened 2021-10-13 21:13 UTC by Gandalf2k15

## About The Pull Request

Simply adds the hair gradient dyekit functions to the preferences menu in the most straightforward way possible.

![tVAicYetfg](https://user-images.githubusercontent.com/9026500/137213357-3e9f108d-98a8-4737-a01f-8c2e3bc90f2d.png)

## Why It's Good For The Game

Better customisation for people!

## Changelog

:cl:
qol: Added the dyekit functions to the character preferences menu.
/:cl:

2021-10-13 21:18 UTC, tralezab commented
great pr

2021-10-13 21:20 UTC, Acer202 commented
No more changing hair dye patterns on the go?

2021-10-13 21:22 UTC, Acer202 commented
> > No more changing hair dye patterns on the go?
> 
> Good point, I think I'll leave that in. I didn't think that through very far.

Thank ya. I like to dye my character's hair differently if I happen to spawn as the clown!

2021-10-13 21:30 UTC, stylemistake approved these changes

2021-10-13 23:03 UTC, Mothblocks requested changes

2021-10-14 02:55 UTC, Mothblocks approved these changes

2021-10-16 00:06 UTC, merged