Updates the Goon Source code objective item to be on par with all other high risk items.
tgstation/tgstation pull request #62142
Opened 2021-10-15 19:35 UTC by SuperNovaa41

## About The Pull Request

Currently, all it takes to ruin an antagonist's round (assuming they have this objective) is to walk into the server room, and break the master server, as this will delete the drive inside. It is extremely weak, a fire axe will break it in less than 15 seconds. 

Not only that, but the drive itself is also not resistant, making it relatively easy to lose it and have it destroyed in various station emergencies.
Compared to every other high risk item, this doesn't make much sense, as they are all supposed to be virtually impossible to get rid off. 

**This does not effect the ninja's objective of destroying the drive.**

This ups the integrity of the master server, making it take ~15s longer to break it with a wielded fire axe, than it does to just deconstruct it. It also adds resistances to the drive itself, which brings it up to the same level as every other high risk item.

Closes https://github.com/tgstation/tgstation/issues/62128

## Why It's Good For The Game

As with other traitor objectives, the item shouldn't be easily destroyed, if at all. It takes nearly no effort to ruin someone's greentext, if they were to have this objective. As far as I can tell, the idea thus far has been to prevent objective item destruction, so this PR aims to update this item to follow that.

If there is a reason that this specific item should be able to be destroyed so easily, I'm perfectly fine with closing this PR.

## Changelog

:cl:
balance: The Goon Source code item is now invulnerable to deletion (aside from ninja intervention), similar to every other high risk item.
/:cl:

2021-10-16 07:42 UTC, Mooshimi commented
> I didn't add Fix because it was intentionally done by Timber
oooh, okay! sorry!

2021-10-16 23:48 UTC, Cyberboss requested changes

2021-10-17 14:37 UTC, Cyberboss approved these changes

2021-10-17 14:37 UTC, merged

2021-10-17 18:49 UTC, SuperNovaa41 commented
> The true fix to this is to give the station consequences for destroying the server by tying important systems to it, like the tcomms array. This is a fine stopgap for now, but someone should get that done.

The consequences are halving the research speed, but thats probably far too inconsequential for a "master server"

2021-11-15 10:40 UTC, Gurkenglas commented
The master server's job could be to transport research points from the servers to the R&D consoles, which could in an emergency be done with a tech disk. Thus, instead of doubling science's waiting times, you add a fetchquest to the high-security low-temperature area. Incidentally this also gives counterplay to Cybersun/traitors using a console beyond your reach, with interactive countercounterplay in the latter case.