Cleanbots with knives now also stab when moving into your tile, +refactors and other fun changes
tgstation/tgstation pull request #62315
Opened 2021-10-24 04:49 UTC by Ryll-Ryll

## About The Pull Request
This is a long overdue follow up to #47590. Attaching a knife to a cleanbot usually ends up getting the cleanbot instantly murdered since they only trigger stabbing if you step onto them, so all you have to do to avoid them is stand still. Now, cleanbots will also stab people when they move into the person's tile, making them much more proactive. Hilariously enough, since it's possible for their stabs to give you cuts that bleed, and cleanbots like to clean blood, it's perfectly possible for the cleanbot to "chase" after you as you run away! Cleanbots won't stab you on moving into your tile if you're laying down or buckled.

Armed cleanbots with their safeties disabled will now have a chance to block or even parry attacks made against them by bleeding crewmembers that scales with how much you're bleeding (the cleanbot tries to clean up your blood and accidentally blocks/parries you with its weapon as a result)! Attacking it with a weapon is more likely to block the attack than to parry and attack back, but trying to punch the cleanbot with your bare hands is much more likely to proc a response, which will always be a parry. If you're not bleeding though, you won't have anything to worry about!

https://streamable.com/csh1i5

Other changes in no particular order:

- Items being attachable to cleanbots is now a trait, TRAIT_CLEANBOT_COMPATIBLE, which has been added to forks and scalpels! The admin-only super pointy tape also grants this trait, so you can use it to do fun things like attach the captain's saber to a cleanbot!
- Added a suffix for stabbing paramedics, E.M.T.
- Cleanbots will no longer have their initial names reset when gaining new titles

## Why It's Good For The Game
Knifebots are funny and all, but they're incredibly incredibly fragile and easy to defeat. They're still pretty easy to kill and mostly just minor nuisances, but they require a bit more forethought to kill now in melee.

## Changelog

:cl: Ryll/Shaps
balance: Cleanbots with knives taped to them can now stab people by moving into them, instead of only being able to stab people who step onto them! They will ignore people who are buckled or laying prone, however.
expansion: Cleanbots with knives who have their safeties disabled can now block or even parry attacks made on them by bleeding crewmembers, as the Cleanbot tries to clean up their gushing blood, and accidentally fighting back with their weapon along the way! The defense chance scales with how much the attacker is bleeding, and is much more likely to happen when the attacker uses their fists!
expansion: You can now attach forks and scalpels to cleanbots.
fix: Cleanbots should now retain their original name when they steal peoples' titles

/:cl:

2021-10-25 18:06 UTC, tralezab requested changes
love the emag defines

2021-10-30 06:55 UTC, Ryll-Ryll commented on code/modules/mob/living/simple_animal/bot/cleanbot.dm
>  	var/static/list/legal = list("Lawyer" = "Esq.")
added psychologist, but service roles don't really have ranks so

2021-10-30 06:55 UTC, Ryll-Ryll commented on code/modules/mob/living/simple_animal/bot/cleanbot.dm
> +	if(!(taped_weapon && user.combat_mode && emagged == BOT_EMAGGED_OVERDRIVE))
eh, that can be changed later if needed

2021-11-06 23:54 UTC, Ryll-Ryll commented
This should be good to merge by the way

2021-11-10 04:54 UTC, closed without merging