Fix long ban reasons breaking rolebans
tgstation/tgstation pull request #62408
Opened 2021-10-28 00:59 UTC by adamsong

## About The Pull Request
Port yogstation13/Yogstation#12550

Fixes long ban reasons breaking rolebans by adding a max length to the ban reason and making sure that the roleban_delimiter is present on a roleban.

## Why It's Good For The Game

Prevents admins from accidentally breaking things. 

## Changelog

:cl:
code: added check to make sure roleban_delimiter exists on a roleban
admin: max ban message length added
/:cl:

2021-10-28 13:28 UTC, Timberpoes reviewed
Can you give more details as to what the bug is? I've gotten no reports that long reasons are breaking role bans. And I like to write essays in the ban reason and have never had an issue with it.

What's the more specific error and why is this fix?

2021-10-29 19:44 UTC, Rohesie requested changes

2021-10-29 19:44 UTC, Rohesie commented on code/modules/admin/sql_ban_system.dm
> +	if(length(reason) > 600)
Could you turn this into a define, instead of a magic number?

One that is shared by same sources of limitation, if possible.

2021-10-30 17:38 UTC, Rohesie requested changes
Add an `#undef MAX_REASON_LENGTH` at the end of the file, since this is all contained in the same one, and set your PR as ready to review once you feel it is so.

We make them drafts until the changes are done to better signal which ones need reviews, but you can undo that yourself when appropriate.

2021-10-31 23:30 UTC, Rohesie approved these changes

2021-10-31 23:30 UTC, merged