Fixes halloween roundstart species
tgstation/tgstation pull request #62427
Opened 2021-10-28 18:14 UTC by Watermelon914

## About The Pull Request

Halloween roundstart species are bugged because the roundstart species list sometimes gets generated before ssevents initializes. This fixes that by letting holidays be fetched before ssevents initialization.

## Why It's Good For The Game

Hallowen is saved

## Changelog

:cl:
fix: Fixed halloween roundstart species not showing up.
/:cl:

2021-11-04 00:45 UTC, ShizCalev requested changes

2021-11-04 00:45 UTC, ShizCalev commented on code/modules/mapping/mapping_helpers.dm
> +	if(SSevents.get_holiday("Ian's Birthday"))
make this a macro.

2021-11-04 00:45 UTC, ShizCalev commented on code/modules/jobs/job_types/head_of_personnel.dm
> +	if(SSevents.get_holiday("Ian's Birthday"))
macro

2021-11-05 17:09 UTC, Watermelon914 commented
to be honest I have no intention of fixing this anymore because I think halloween species are actually pretty shit so I'm just going to close this PR

2021-11-05 17:09 UTC, closed without merging