Replaces a portion of C-style for loops with the more commonplace for loops, which are faster.
tgstation/tgstation pull request #62624
Opened 2021-11-06 17:15 UTC by Ghommie

## About The Pull Request
See title. Basically it replaces some instances of `for(var/i=value,value<=foo,value++)` with `for(var/i in 1 to value)`. In many cases, the `i` loop counter (also called `j` in nested loops, which are used for grids and mapping mostly) has been renamed in accordance with the contribution guidelines.
This doesn't cover every for loop in the code of course; for loops that don't use the less than (or equal to) operation as condition were excluded, like those that have an advancement that isn't an increment operation or that can modify one of the variables used in the condition in the performed statement (for example, when the condition is `iteration<=list.len` but new entries may be added or removed as it loops, increasing/decreasing the number of loops as a result). Many of the loops that qualify for this have also been skipped for the time being to make reviewing and the merging process easier. They may be included in a different PR.

## Why It's Good For The Game
These latter traditional for loops are faster and more user-friendly. Thanks to KylerAce for the for loops benchmark:
![h](https://cdn.discordapp.com/attachments/326831214667235328/906591418552844308/Screenshot_1495.png)

## Changelog
N/A. Code Improvement.

2021-11-06 20:51 UTC, Mothblocks commented
theyre also just actuially readable

2021-11-06 20:55 UTC, Mothblocks requested changes
Instead of renaming all the `i` to `iteration`, I'd recommend just naming them `_` if they're unused.

2021-11-06 20:55 UTC, Mothblocks commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	for(var/iteration in 0 to max_range)
```suggestion
	for(var/iteration in 1 to max_range + 1)
```

Same thing in the end (since `iteration` isn't used), but keeps `in 1 to`.

2021-11-06 23:58 UTC, MrStonedOne requested changes

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/items/storage/secure.dm
> +	for(var/iteration in 1 to STR.max_items - 2)
```suggestion
	for(var/i in 1 to STR.max_items - 2)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/items/tanks/watertank.dm
> +		for(var/iteration in 1 to 5)
```suggestion
		for(var/i in 1 to 5)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 3)
```suggestion
	for(var/i in 1 to 3)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 5)
```suggestion
	for(var/i in 1 to 5)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 2)
```suggestion
	for(var/i in 1 to 2)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 4)
```suggestion
	for(var/i in 1 to 4)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 5)
```suggestion
	for(var/i in 1 to 5)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 2)
```suggestion
	for(var/i in 1 to 2)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 3)
```suggestion
	for(var/i in 1 to 3)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 5)
```suggestion
	for(var/i in 1 to 5)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> +	for(var/iteration in 1 to 6)
```suggestion
	for(var/i in 1 to 6)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/game/objects/structures/crates_lockers/closets/syndicate.dm
> +	for(var/iteration in 1 to 2)
```suggestion
	for(var/i in 1 to 2)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/admin/verbs/SDQL2/SDQL_2.dm
> +		for(var/iteration in 1 to indent)
```suggestion
		for(var/i in 1 to indent)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/admin/verbs/adminhelp.dm
> +				var/word = ckey(L[iteration])
```suggestion
			for(var/i in 1 to surname_found-1)
				var/word = ckey(L[i])
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/abductor/equipment/abduction_gear.dm
> +			for(var/iteration in 0 to framestackamount)
```suggestion
			for(var/i in 0 to framestackamount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/abductor/machinery/dispenser.dm
> +		amounts[iteration] = rand(1,5)
```suggestion
	for(var/i in 1 to gland_types.len)
		gland_colors[i] = random_color()
		amounts[i] = rand(1,5)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/abductor/machinery/dispenser.dm
> +				amounts[iteration]++
```suggestion
		for(var/i in 1 to gland_colors.len)
			if(gland_types[i] == W.type)
				amounts[i]++
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/eldritch_cult/eldritch_magic.dm
> +	for(var/iteration in 0 to max_range)
```suggestion
	for(var/i in 0 to max_range)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/gang/handler.dm
> +		for(var/iteration in 1 to replacement_gangsters)
```suggestion
		for(var/j in 1 to replacement_gangsters)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/antagonists/traitor/equipment/contractor.dm
> +		var/datum/syndicate_contract/contract_to_add = new(owner, assigned_targets, to_generate[index])
```suggestion
	for(var/i in 1 to to_generate.len)
		var/datum/syndicate_contract/contract_to_add = new(owner, assigned_targets, to_generate[i])
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/clothing/shoes/_shoes.dm
> +		for(var/iteration in 1 to 3)
```suggestion
		for(var/i in 1 to 3)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/events/electrical_storm.dm
> +	for(var/iteration in 1 to lightsoutAmount)
```suggestion
	for(var/i in 1 to lightsoutAmount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/events/fake_virus.dm
> +		for(var/iteration in 1 to rand(1,defacto_min))
```suggestion
		for(var/i in 1 to rand(1,defacto_min))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/events/fake_virus.dm
> +		for(var/iteration in 1 to rand(1,defacto_min))
```suggestion
		for(var/i in 1 to rand(1,defacto_min))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/events/shuttle_loan.dm
> +				for(var/iteration in 1 to 10)
```suggestion
				for(var/i in 1 to 10)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/events/wormholes.dm
> +	for(var/iteration in 1 to number_of_wormholes)
```suggestion
	for(var/i in 1 to number_of_wormholes)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/food_and_drinks/recipes/food_mixtures.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/hydroponics/grown/replicapod.dm
> +		for(var/iteration in 1 to seed_count)
```suggestion
		for(var/i  in 1 to seed_count)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mapping/space_management/space_transition.dm
> +			point_grid[iteration_x][iteration_y] = P
```suggestion
	for(var/x in 1 to conf_set_len*2+1)
		for(var/y in 1 to conf_set_len*2+1)
			P = new/datum/space_transition_point(x, y, point_grid)
			point_grid[x][y] = P
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/meteors/meteors.dm
> +	for(var/iteration in 1 to number)
```suggestion
	for(var/i in 1 to number)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mining/abandoned_crates.dm
> +	for(var/iteration in 1 to codelen)
```suggestion
	for(var/i in 1 to codelen)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/carbon/carbon.dm
> +			for(var/iteration in 1 to range-1)
```suggestion
			for(var/i in 1 to range-1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/carbon/human/species_types/golems.dm
> +	for(var/iteration in 1 to rand(3,5))
```suggestion
	for(var/i in 1 to rand(3,5))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/carbon/human/species_types/golems.dm
> +	for(var/iteration in 1 to rand(3,5))
```suggestion
	for(var/i in 1 to rand(3,5))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/carbon/human/species_types/golems.dm
> +	for(var/iteration in 1 to rand(3,5))
```suggestion
	for(var/i in 1 to rand(3,5))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/simple_animal/slime/powers.dm
> +			for(var/iteration in 1 to 4)
```suggestion
			for(var/i in 1 to 4)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/living/simple_animal/slime/powers.dm
> +				if(iteration != 1)
```suggestion
				if(i != 1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/mob/transform_procs.dm
> +		for(var/iteration in 1 to number)
```suggestion
		for(var/i in 1 to number)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/power/lighting/light.dm
> +		for(var/iteration in 1 to amount)
```suggestion
		for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerator.dm
> +	for(var/iteration in lilZ to bigZ+offByOneOffset)
```suggestion
	for(var/i in lilZ to bigZ+offByOneOffset)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerator.dm
> +			theRadius = max(radius/max((2*abs(sphereMagic-iteration)),1),1)
```suggestion
		if(i != sphereMagic)
			theRadius = max(radius/max((2*abs(sphereMagic-i)),1),1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerator.dm
> +		map |= circle_range(locate(centerX,centerY,iteration),theRadius)
```suggestion
		map |= circle_range(locate(centerX,centerY,i),theRadius)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +			old_state[iteration_x][iteration_y] = rand(0,1)
```suggestion
	for(var/x in 1 to width)
		old_state[x] = new/list(height)
		for(var/y in 1 to height)
			old_state[x][y] = rand(0,1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +				current_state[iteration_x][iteration_y] = apply_rule(iteration_x, iteration_y)
```suggestion
		for(var/x in 1 to width)
			for(var/y in 1 to height)
				current_state[x][y] = apply_rule(x, y)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +			var/turf/T = locate(start.x+iteration_x-1,start.y+iteration_y-1,start.z)
```suggestion
	for(var/x in 1 to width)
		for(var/y in 1 to height)
			var/turf/T = locate(start.x+x-1,start.y+y-1,start.z)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +				T.ChangeTurf(type_map[current_state[iteration_x][iteration_y]+1])
```suggestion
				T.ChangeTurf(type_map[current_state[x][y]+1])
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +/datum/map_generator/ca/proc/apply_rule(index_x, index_y)
```suggestion
/datum/map_generator/ca/proc/apply_rule(x, y)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +			var/n_y = index_y+dist_y
```suggestion
			var/n_x = x+dist_x
			var/n_y = y+dist_y
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +	value -= old_state[index_y][index_y]
```suggestion
	value -= old_state[y][y]
```

Also this line is bugged. you use y in both but the old was i and j, so one of those should be an x.

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +		return old_state[index_x][index_y]
```suggestion
		return old_state[x][y]
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +	for(var/iteration in max(1, stored_ammo.len) to max_ammo)
```suggestion
	for(var/i in max(1, stored_ammo.len) to max_ammo)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
> +	for(var/iteration in 1 to max_ammo)
```suggestion
	for(var/i in 1 to max_ammo)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/projectiles/guns/energy.dm
> +		var/shottype = ammo_type[index]
```suggestion
	for (var/i in 1 to ammo_type.len)
		var/shottype = ammo_type[i]
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/projectiles/guns/energy.dm
> +		ammo_type[index] = shot
```suggestion
		ammo_type[i] = shot
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chem_splash.dm
> +		for(var/iteration in 1 to affected_range)
```suggestion
		for(var/i in 1 to affected_range)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chem_splash.dm
> +			for(var/turf/T in (orange(iteration, epicenter) - orange(iteration-1, epicenter)))
```suggestion
			for(var/turf/T in (orange(i, epicenter) - orange(i-1, epicenter)))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +				if(iteration-1 < drop_threshold)
```suggestion
			for(var/i in 1 to amount)
				if(i-1 < drop_threshold)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			for(var/iteration in 1 to amount)
```suggestion
			for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			for(var/iteration in 1 to amount)
```suggestion
			for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			for(var/iteration in 1 to amount)
```suggestion
			for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +			for(var/iteration in 1 to amount)
```suggestion
			for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes.dm
> +				for(var/iteration in 1 to rand(1, 3))
```suggestion
				for(var/j in 1 to rand(1, 3))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in 1 to created_volume)
```suggestion
	for(var/i in 1 to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in rand(1, created_volume) to created_volume) // More lulz.
```suggestion
	for(var/i in rand(1, created_volume) to created_volume) // More lulz.
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/chemistry/recipes/others.dm
> +	for(var/iteration in rand(1, created_volume) to created_volume)
```suggestion
	for(var/i in rand(1, created_volume) to created_volume)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/reagent_containers/spray.dm
> +	for(var/iteration in 1 to 3) // intialize sprays
```suggestion
	for(var/i in 1 to 3) // intialize sprays
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/reagents/reagent_containers/spray.dm
> +		..(the_targets[iteration], user)
```suggestion
		..(the_targets[i], user)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/research/xenobiology/crossbreeding/burning.dm
> +	for(var/iteration in 1 to amount)
```suggestion
	for(var/i in 1 to amount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/research/xenobiology/crossbreeding/burning.dm
> +			for(var/iteration in 1 to rand(1, 3))
```suggestion
			for(var/j in 1 to rand(1, 3))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/research/xenobiology/crossbreeding/industrial.dm
> +		for(var/iteration in 1 to itemamount)
```suggestion
		for(var/i in 1 to itemamount)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/research/xenobiology/crossbreeding/selfsustaining.dm
> +	for(var/iteration in 1 to 4)
```suggestion
	for(var/i in 1 to 4)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/ruins/spaceruin_code/hilbertshotel.dm
> +			for(var/iteration_y in 0 to hotelRoomTemp.height-1)
```suggestion
		for(var/x in 0 to hotelRoomTemp.width-1)
			for(var/y in 0 to hotelRoomTemp.height-1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/ruins/spaceruin_code/hilbertshotel.dm
> +						A.forceMove(locate(roomReservation.bottom_left_coords[1] + iteration_x, roomReservation.bottom_left_coords[2] + iteration_y, roomReservation.bottom_left_coords[3]))
```suggestion
						A.forceMove(locate(roomReservation.bottom_left_coords[1] + x, roomReservation.bottom_left_coords[2] + y, roomReservation.bottom_left_coords[3]))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/ruins/spaceruin_code/hilbertshotel.dm
> +					for(var/atom/movable/A in locate(room.bottom_left_coords[1] + iteration_x, room.bottom_left_coords[2] + iteration_y, room.bottom_left_coords[3]))
```suggestion
			for(var/i in 0 to hotelRoomTemp.width-1)
				for(var/j in 0 to hotelRoomTemp.height-1)
					for(var/atom/movable/A in locate(room.bottom_left_coords[1] + i, room.bottom_left_coords[2] + j, room.bottom_left_coords[3]))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/ruins/spaceruin_code/hilbertshotel.dm
> +		for(var/iteration_y in 0 to parentSphere.hotelRoomTemp.height-1)
```suggestion
	for(var/x in 0 to parentSphere.hotelRoomTemp.width-1)
		for(var/y in 0 to parentSphere.hotelRoomTemp.height-1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/ruins/spaceruin_code/hilbertshotel.dm
> +			for(var/atom/movable/A in locate(reservation.bottom_left_coords[1] + iteration_x, reservation.bottom_left_coords[2] + iteration_y, reservation.bottom_left_coords[3]))
```suggestion
			for(var/atom/movable/A in locate(reservation.bottom_left_coords[1] + x, reservation.bottom_left_coords[2] + y, reservation.bottom_left_coords[3]))
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/spells/spell.dm
> +			for(var/iteration in 1 to max_targets)
```suggestion
			for(var/i in 1 to max_targets)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/spells/spell_types/conjure.dm
> +	for(var/iteration in 1 to summon_amt)
```suggestion
	for(var/i in 1 to summon_amt)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/spells/spell_types/projectile.dm
> +	for(var/iteration in 1 to range-1)
```suggestion
	for(var/i in 1 to range-1)
```

2021-11-06 23:58 UTC, MrStonedOne commented on code/modules/vending/_vending.dm
> +						for(var/iteration in 1 to num_shards)
```suggestion
						for(var/i in 1 to num_shards)
```

2021-11-07 00:07 UTC, MrDoomBringer commented
should've done it in individual reviews to really pump up those profile contribution numbers

2021-11-07 03:45 UTC, MrStonedOne commented on code/modules/procedural_mapping/mapGenerators/cellular.dm
> +	value -= old_state[y][y]
this is wrong (it was wrong before my suggestion too)

2021-11-08 00:42 UTC, merged