Headset mousedrop like PDA
tgstation/tgstation pull request #62656
Opened 2021-11-07 20:40 UTC by jacklecroy

## About The Pull Request

Drag a headset onto you to open the frequency menu.

## Why It's Good For The Game

Easier to adjust frequencies without having to take off the headset. Useful for traitors with uplink in headset.

## Changelog
:cl: That REALLY Good Soda Flavor
tweak: You can drag a headset onto yourself to open the menu.
/:cl:

2021-11-07 20:41 UTC, tralezab requested changes, later dismissed
boop!

2021-11-07 20:41 UTC, tralezab commented on code/game/objects/items/devices/radio/headset.dm
> +	var/mob/M = usr
use descriptive var names, please

2021-11-07 20:41 UTC, tralezab commented on code/game/objects/items/devices/radio/headset.dm
> +	if((M == over) && usr.canUseTopic(src, BE_CLOSE, FALSE, NO_TK))
if you're going to typecast usr as a mob in line 83, then you should be calling canUseTopic on the typecasted var in 84

2021-11-07 20:55 UTC, datorangebottle commented
I honestly didn't know PDA mousedrop existed until I saw this PR.

2021-11-07 21:27 UTC, UnokiAs commented
Could be cool if you could adjust your headset frequency while wearing it with alt click having to put it in hands every time as traitor is annoying

2021-11-07 21:30 UTC, jacklecroy commented
> 
> 
> ~Could be cool if you could adjust your headset frequency while wearing it with alt click having to put it in hands every time as traitor is annoying~ Wait I'm dumb I didn't read the pr correctly

I think alt click is used to toggle high volume mode.

2021-11-07 21:49 UTC, optimumtact commented
an actual quality of life PR

2021-11-08 18:05 UTC, GoldenAlpharex commented
I think the tweak: tag was removed and turned into qol:, no?

2021-11-09 00:50 UTC, iwishforducks commented
Random thought: Are you able to change headset settings while in crit, allowing you to turn on hotmic and thus call for help?

2021-11-09 05:54 UTC, ShizCalev commented
@iwishforducks Already handled by canusetopic / TRAIT_UI_BLOCKED

2021-11-09 05:55 UTC, merged