Fixes yet another couple TK teleportation tricks.
tgstation/tgstation pull request #62925
Opened 2021-11-18 02:49 UTC by Ghommie

## About The Pull Request
Fixes airlock notes and cloth sheets cut from gauzes being teleported to the user because of TK.

## Why It's Good For The Game
This will fix #62780.

## Changelog

:cl:
fix: Fixed yet another couple TK teleportation tricks: airlock notes and cloth cut from gauzes.
/:cl:

2021-11-18 09:55 UTC, LemonInTheDark commented
Hello. You've been impacted by a spurious ci failure. Keep calm and pull latest master

2021-11-19 17:24 UTC, Watermelon914 requested changes

2021-11-19 17:24 UTC, Watermelon914 commented on code/game/machinery/doors/airlock.dm
> +		note.forceMove(location)
what if it just moved to the drop location of the tool?

2021-11-19 17:24 UTC, Watermelon914 commented on code/game/objects/items/stacks/medical.dm
> +		var/atom/location = telekinesis ? drop_location() : user.drop_location()
same thing here, you could just move it to the drop location of the tool.

2021-11-28 08:29 UTC, merged