NT Party Kit! Change your color on the go! REAL EDITION
tgstation/tgstation pull request #62955
Opened 2021-11-19 17:13 UTC by remuluson2

## About The Pull Request

Added a mechanic for custom skin tones that use Hex color instead of names. The so-called override_skin_tone is on its new layer between hulk skintone and normal one.

Added a NTP kit, a device straight from the wild Central Command parties for spicing up your look with infinite range of colors you can pick from! The color is waterproof and the used powder is both effective and safe!*
_*Nanotransen is not responsible for any injuries or/and lawsuits resulting from usage of NTP kit™._

At the moment the NTP kit can only paint humans. I might add the functionality if there will be a demand for it.
## Why It's Good For The Game

I love to color myself but I am really bummed out when I lose all my progress on coloring my stuff when I get hit by a single drop of water. Also the fact you can't spray paint your body with the color is another bummer.

And as many people say. If you want it, code it yourself.

## Changelog

:cl:
add: Added NTP kit, for changing your color semi-permanently with patented NT powder™.
/:cl:

2021-11-19 21:32 UTC, itseasytosee commented
![image](https://user-images.githubusercontent.com/55666666/142694260-64a9d751-a49b-4963-a571-362f082dc79d.png)
How are you gonna get them off nerd?

2021-11-19 22:17 UTC, remuluson2 commented
You just use the NTP kit again. It and only it can remove the color.

2021-11-19 22:20 UTC, remuluson2 commented
> ![image](https://user-images.githubusercontent.com/55666666/142694260-64a9d751-a49b-4963-a571-362f082dc79d.png) How are you gonna get them off nerd? (you might want to have it come off with space cleaner or something.)

Like I said. It and only it. Even space cleaner cant get it off. It's not even paint or spray. NTP kit is an inhaler.

2021-11-19 22:22 UTC, itseasytosee commented
> Like I said. It and only it. Even space cleaner cant get it off. It's not even paint or spray. NTP kit is an inhaler.

What if you drank space cleaner

2021-11-19 22:25 UTC, remuluson2 commented
> > Like I said. It and only it. Even space cleaner cant get it off. It's not even paint or spray. NTP kit is an inhaler.
> 
> What if you drank space cleaner

I T S   I N   Y O U R   S K I N

2021-11-19 23:37 UTC, Fikou commented
nt party kit is a dumb name

2021-11-20 00:17 UTC, remuluson2 commented
> nt party kit is a dumb name

I mean, its still nanotrasen after all. Even if they party.

2021-11-20 00:22 UTC, itseasytosee commented
> > > Like I said. It and only it. Even space cleaner cant get it off. It's not even paint or spray. NTP kit is an inhaler.
> > 
> > 
> > What if you drank space cleaner
> 
> I T S I N Y O U R S K I N

Okay what if you got injected with space cleaner

2021-11-20 00:26 UTC, remuluson2 commented
> > > > Like I said. It and only it. Even space cleaner cant get it off. It's not even paint or spray. NTP kit is an inhaler.
> > > 
> > > 
> > > What if you drank space cleaner
> > 
> > 
> > I T S I N Y O U R S K I N
> 
> Okay what if you got injected with space cleaner

I can tell you what is inside the NTP kit, but then I would have to kill you.

2021-11-20 00:54 UTC, itseasytosee commented
My honest opinion is it seems like a roundabout way to add wacky skin tones. We already have systems like genetics that could be reworked, or you could just add bodypaint.

2021-11-20 01:11 UTC, remuluson2 commented
> My honest opinion is it seems like a roundabout way to add wacky skin tones. We already have systems like genetics that could be reworked, or you could just add bodypaint.
This is the bodypaint. Just wacky.
Also genetics would need a grand rework to the core system of dna and how it is coded. That's why I went with this instead.

2021-11-20 04:02 UTC, NanoCats commented
> ![image](https://user-images.githubusercontent.com/55666666/142694260-64a9d751-a49b-4963-a571-362f082dc79d.png) How are you gonna get them off nerd? (you might want to have it come off with space cleaner or something.)

We literally have this exact reference in the form of spray-on-insuls.

They're not at all worth it ever since Ghilker ruined gloves by making them give your fingers the chunk trait.

2021-11-20 09:07 UTC, Fikou commented
> > nt party kit is a dumb name
> 
> I mean, its still nanotrasen after all. Even if they party.

wtf is party or nanotrasen about an item that changes your skin color

2021-11-20 15:06 UTC, necromanceranne commented
> > > nt party kit is a dumb name
> > 
> > 
> > I mean, its still nanotrasen after all. Even if they party.
> 
> wtf is party or nanotrasen about an item that changes your skin color

Halloween party with people who don't know what blackface is sounds like something an NT exec would think is a good idea.

2021-11-21 14:32 UTC, Likteer commented
You have the approval of Likteer

2021-11-22 07:39 UTC, Twaticus requested changes
in-game examples using the kit please
preferably an assortment of natural, unnatural, lightest, darkest, and some other extremes

2021-11-22 08:44 UTC, Kylerace requested changes
just code review

2021-11-22 08:44 UTC, Kylerace commented on code/game/objects/items/cosmetics.dm
> +		src.visible_message("[user] suddenly changes color!","You suddenly change color!")
```suggestion
		visible_message("[user] suddenly changes color!","You suddenly change color!")
```
src is implied here you dont need to use it

2021-11-22 08:44 UTC, Kylerace commented on code/game/objects/items/cosmetics.dm
> +	var/removal_mode = FALSE
doc this

2021-11-22 08:44 UTC, Kylerace commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/override_skin_tone = "" //Overrides normal skin_tone. Used for custom skin color. Uses Hex color.
use the autodoc format for this so that mousing over this var in vsc shows the documentation

2021-11-22 08:44 UTC, Kylerace commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +	var/override_skin_tone = ""
doc this

2021-11-23 08:17 UTC, optimumtact commented
https://www.youtube.com/watch?v=zA52uNzx7Y4

2021-11-24 03:01 UTC, Twaticus approved these changes
ty for the examples. its very wacky but i think its worth a shot. though the color selection may be tweaked in the future depending on if the game turns into a neon rainbow puke of characters 😄

2021-12-04 10:21 UTC, interestingusernam3 commented
Plasmemeface party

2021-12-19 00:11 UTC, closed without merging