The Tramstation Tram no longer shoves the handicapped out of their wheelchairs when moved
tgstation/tgstation pull request #63041
Opened 2021-11-24 05:49 UTC by MMMiracles

## About The Pull Request

Adds a mob trait that is used to prevent forcemoves from unbuckling mobs, which in turn fixes the tram's issue of unbuckling you from your seats when it moves. This trait is added when you are added to the list of items to move and you lose the trait as soon as you leave the tram itself, hopefully meaning this shouldn't have any unforeseen consequences. 

## Why It's Good For The Game

You can now buckle yourself into the seats on the tram and actually be in the chair. The crippled crew will no longer be bullied by the tram by being forced to crawl back into their wheelchair after departing.

## Changelog

:cl: MMMiracles
fix: The Tramstation Tram no longer force unbuckles you from chairs/vehicles when moving.
/:cl:

I've played around a bit locally to make sure you can't escape the tram with the buckle trait. The only issue I'm running into is that when you're mounted on rideables like the wheelchair, the seat lags behind due to what I assume is an issue with gliding or relaymove. The slower the vehicle, the worse the catchup (it still lets you move properly while mid-transit so it seems like mostly just a visual issue atm)

2021-11-24 07:14 UTC, Mothblocks requested changes

2021-11-24 07:14 UTC, Mothblocks commented on code/_globalvars/traits.dm
> +		"TRAIT_CANNOT_BE_UNBUCKLED" = TRAIT_CANNOT_BE_UNBUCKLED
```suggestion
		"TRAIT_CANNOT_BE_UNBUCKLED" = TRAIT_CANNOT_BE_UNBUCKLED,
```

2021-11-24 07:14 UTC, Mothblocks commented on code/game/objects/structures/industrial_lift.dm
> +		var/mob/living/hewhocannotbeunbuckled = AM
You don't need this variable

2021-11-24 07:14 UTC, Mothblocks commented on code/game/objects/structures/industrial_lift.dm
> +		var/mob/living/hewhocanbeunbuckled = potential_rider
You don't need this variable

2021-11-24 14:49 UTC, Ghommie commented
> The only issue I'm running into is that when you're mounted on rideables like the wheelchair, the seat lags behind due to what I assume is an issue with gliding or relaymove. The slower the vehicle, the worse the catchup.

It most surely has something to do with movables that have a riding component having their glide size set by said component any time they are moved and not only when they are driven/ridden. I'm on it.

2021-11-24 18:47 UTC, notfrying1pans commented
blessed

2021-11-24 20:48 UTC, Mothblocks approved these changes

2021-11-27 16:55 UTC, GoldenAlpharex commented
@MMMiracles Could you test just to be sure if this fixes the elevators going up and down crushing those poor people on wheelchairs? I feel like it will, but you can never be too sure.

2021-11-28 23:51 UTC, merged

2021-11-29 01:33 UTC, Ghommie commented
@81Denton I'd be glad if you could merge #63048 soon too so I don't have to edit a cl entry in that says vehicles won't lag behind inside trams anymore or something.