Magic mirror: Fixes changing races & code improvement
tgstation/tgstation pull request #63201
Opened 2021-12-02 01:44 UTC by JohnFulpWillard

## About The Pull Request

All mirrors now use the same Initialize(), with a var determining which flag to check.
Improves some of the code with better var names and early returns.
Moves pride ruin's mirror to the rest of the mirrors
Removes /curse() proc, replaces it with Pride's mirror just calling parent instead, since it was the only mirror that used it.
Also fixes not being able to change races with the mirror.

## Why It's Good For The Game

Bug fix and code improvement, I hated that pride's mirror used /New() while all other mirrors used /Initialize().

## Changelog

:cl:
fix: Magic mirrors will now allow you to swap species again.
/:cl:

2021-12-03 21:35 UTC, tralezab requested changes
great cleanup all around, didn't notice anything weird. also, thanks for removing the spaces on the defines

2021-12-03 21:35 UTC, tralezab commented on code/game/objects/structures/mirror.dm
> +	var/turf/T = get_turf(user)
heck make this descriptive too

2021-12-03 21:35 UTC, tralezab commented on code/game/objects/structures/mirror.dm
> +	var/turf/open/chasm/C = T
and this

2021-12-07 10:06 UTC, LemonInTheDark commented
@tralezab ready?

2021-12-07 20:14 UTC, tralezab commented
Yes.

2021-12-07 20:15 UTC, merged