Adds Bell Peppers and Toechtauese Berries to vending machines
tgstation/tgstation pull request #63352
Opened 2021-12-11 08:21 UTC by carshalash

## About The Pull Request

EoB accidentally forgot to add these to vending machines, this PR throws them in. 

## Why It's Good For The Game

Being able to access berries without calling the admins jannys and begging them for help is nice. 

## Changelog

:cl:
fix: Adds seeds to vending machines as intended
/:cl:

2021-12-11 16:45 UTC, EOBGames commented
Ah damn, I should have known I forgot something- I had them in the seed vendor on at least one of the three branches I had to work across, so I must have gotten mixed up with that and the final. Thanks for handling that.

The spaghetti in lasagne being cooked was deliberate, though- with dried lasagne sheets you need to boil them first, hence that got translated into the recipe. That said though, if that's too confusing or doesn't convey well, it's probably best with raw pasta.

2021-12-11 22:24 UTC, AdipemDragon commented
is.... is the herb bundles handled by this too or.

2021-12-11 23:14 UTC, carshalash commented
> is.... is the herb bundles handled by this too or.

Ah shit, I thought those were purposefully made to be ordered at the console. Thanks dragon.

2021-12-12 18:59 UTC, Mothblocks requested changes
Please update your changelog to include what seeds have been added

2021-12-12 18:59 UTC, Mothblocks commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_moth.dm
> +		/obj/item/food/spaghetti/boiledspaghetti = 2,
Undocumented change, please update your PR changelog

2021-12-12 21:05 UTC, optimumtact commented
> > is.... is the herb bundles handled by this too or.
> 
> Ah shit, I thought those were purposefully made to be ordered at the console. Thanks dragon.

@EOBGames are they?

2021-12-13 18:12 UTC, EOBGames commented
> > > is.... is the herb bundles handled by this too or.
> > 
> > 
> > Ah shit, I thought those were purposefully made to be ordered at the console. Thanks dragon.
> 
> @EOBGames are they?

The herbs are intended to be grown at botany, hence why they've got seeds- so adding them to the seed vendor is correct.

2021-12-14 02:12 UTC, EOBGames commented
Hey, a bug's come up: would you be able to put this variable:
`burns_in_oven = TRUE`
on the roasted bell pepper, so it doesn't catch fire once it's cooked.
(Yes, I feel stupid for missing that one)

2021-12-14 13:58 UTC, AdipemDragon commented
Well if this is just becoming a general "fix the moth food pr" pr, what about the baked cheese wheel? That's another one that's just not workin no matter what.

2021-12-15 11:53 UTC, carshalash commented
Pepper done, cheese done, lasagne done, seeds done.

Waiting on eob's approval to touch a recipe ratio then we're good to go.

2021-12-21 06:40 UTC, MrMelbert commented
> Waiting on eob's approval to touch a recipe ratio then we're good to go.

Did something come of this, or is this good to go now?

2021-12-21 07:25 UTC, merged