Mob Abilities
tgstation/tgstation pull request #63520
Opened 2021-12-20 18:37 UTC by Whoneedspacee

## About The Pull Request

[Video Showcase](https://www.youtube.com/watch?v=fE9AgxZXbPs)

This overhauls the cooldown action subtype to allow for shared cooldowns and for targeted abilities where you can queue up an ability and then click a target.

It's not a perfect system but it's way better than what is there currently by a longshot, and allows you to for example, add a charging action to any mob, not just simplemobs.

## Why It's Good For The Game

Allows for more easy mobs to be made or even allows for some custom mob creation by admins mid-round as opposed to most of these abilities just being hard-coded procs on the mobs.

## Changelog

:cl: Whoneedspacee
refactor: Refactors megafauna abilities to be mob actions which are grantable to any living mob.
admin: Added a verb under admin events which lets you grant mob actions to a marked living mob.
/:cl:

2021-12-20 20:56 UTC, Watermelon914 requested changes
A lot of variable names are 1 letter, they should ideally have a more descriptive name if you're going to refactor action code.

Since you've already got a lot of 1 letter variable names everywhere, I don't think it'd be fair to ask you to change it all, but please change the ones I've listed below

2021-12-20 20:56 UTC, Watermelon914 commented on code/__DEFINES/dcs/signals/signals_mob/signals_mob_simple.dm
> +#define COMSIG_LAVA_ARENA_FAILED "mob_lava_arena_failed"
needs documenting

2021-12-20 20:56 UTC, Watermelon914 commented on code/datums/action.dm
> +/datum/action/cooldown/Trigger(atom/A)
use more descriptive variable names

2021-12-20 20:56 UTC, Watermelon914 commented on code/datums/actions/mobs/charge.dm
> +	shake_camera(source, 2, 3)
use more descriptive variable names for atom and living here

2021-12-20 20:56 UTC, Watermelon914 commented on code/datums/actions/mobs/charge.dm
> +		INVOKE_ASYNC(src, .proc/do_charge, B, target_atom, delay, past)
needs more descriptive of a variable name, avoid one letter variable names like these

2021-12-20 20:56 UTC, Watermelon914 commented on code/datums/actions/mobs/dash.dm
> +	for(var/turf/open/O in RANGE_TURFS(dash_range, own_turf))
rename O to something more descriptive

2021-12-21 00:35 UTC, tralezab commented
i really like this decoupling

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
> +/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner/doom/Initialize()
```suggestion
/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner/doom/Initialize(mapload)
```

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
> +/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner/Initialize()
```suggestion
/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner/Initialize(mapload)
```

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +/mob/living/simple_animal/hostile/megafauna/colossus/Initialize()
```suggestion
/mob/living/simple_animal/hostile/megafauna/colossus/Initialize(mapload)
```

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/lobstrosity.dm
> +/mob/living/simple_animal/hostile/asteroid/lobstrosity/Initialize()
```suggestion
/mob/living/simple_animal/hostile/asteroid/lobstrosity/Initialize(mapload)
```

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
> +	var/datum/action/cooldown/mob_cooldown/transform_weapon/transform_weapon
These need to be handled in destroy

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
> +	var/datum/action/cooldown/mob_cooldown/projectile_attack/dir_shots/alternating/dir_shots
Same here

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +	var/datum/action/cooldown/mob_cooldown/projectile_attack/shotgun_blast/pattern/ice_shotgun
same here

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	var/datum/action/cooldown/mob_cooldown/charge/charge
same here

2021-12-21 06:06 UTC, MrMelbert commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/lobstrosity.dm
> +	var/datum/action/cooldown/mob_cooldown/charge/charge
same here

2021-12-21 06:07 UTC, MrMelbert commented on code/datums/actions/mobs/charge.dm
> +	var/expected_dir = next_move_allowed[source]
```suggestion
/datum/action/cooldown/mob_cooldown/charge/proc/on_move(atom/source, atom/new_loc)
	SIGNAL_HANDLER

	var/expected_dir = next_move_allowed[source]
```
Also NONE of your signal procs have signal handlers as far as I can see, you should check them all

2021-12-21 19:00 UTC, Whoneedspacee commented
update https://www.youtube.com/watch?v=ceKz0M9C8bE

2021-12-21 22:07 UTC, Mothblocks requested changes
Going to just assume the other stuff isn't yours, though there's plenty upsetting about them

2021-12-21 22:07 UTC, Mothblocks commented on code/__DEFINES/cooldowns.dm
> +//Shared cooldowns for actions
Can you put this with the rest of the cooldown keys at the top?

2021-12-21 22:07 UTC, Mothblocks commented on code/__DEFINES/dcs/signals/signals_mob/signals_mob_simple.dm
> +//Mob ability signals /datum/action/cooldown/mob_cooldown
Can you move a lot of these to their own file? Already not too happy about things like oozes being in here, now that I see it.

Something like signals_mob_abilities.dm or something.

2021-12-21 22:07 UTC, Mothblocks commented on code/__DEFINES/dcs/signals/signals_mob/signals_mob_simple.dm
> +//Mob ability signals /datum/action/cooldown/mob_cooldown
Also all of these need to document the proc they're called from, and what arguments are passed.

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +		for(var/datum/action/cooldown/C in owner.actions - src)
Better name

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +/datum/action/cooldown/proc/StartCooldown(override_cooldown_time, will_share_cooldowns = TRUE)
The boolean parameter shouldn't be here, this should just be two separate procs, with one being the process after this that starts the cooldown, and nothing else.

The two places in which you actually use `will_share_cooldowns = FALSE` you would call that directly. `StartCooldown()` itself would run the shared_cooldown stuff, though.

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +		for(var/datum/action/cooldown/C in owner.actions)
Better name

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +			to_chat(owner, "<b>[src] is no longer active</b>")
```suggestion
			to_chat(owner, "<b>[src] is no longer active.</b>")
```

In an ideal world these are not necessary at all, by the way. The icon itself should have some indication to whether or not its active. If it does, then these do not need to exist.

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +			to_chat(owner, "<b>You are now prepared to use [src]</b>")
```suggestion
			to_chat(owner, "<b>You are now prepared to use [src].</b>")
```

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +/datum/action/cooldown/proc/InterceptClickOn(mob/living/caller, params, atom/A)
Better variable name for `A` (such as `target`)

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +/datum/action/cooldown/proc/Activate(atom/target_atom)
Document

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +/datum/action/cooldown/proc/Activate(atom/target_atom)
Also this can just be `target`, `atom` is already in its typepath anyway.

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +			button.maptext = "<b>[round(time_left/10, 0.1)]</b>"
```suggestion
			button.maptext = MAPTEXT("<b>[round(time_left/10, 0.1)]</b>")
```

Maptext without this looks fairly bad.

2021-12-21 22:07 UTC, Mothblocks commented on code/datums/action.dm
> +		button.color = rgb(0,255,0)
```suggestion
		button.color = COLOR_GREEN
```

?

2021-12-31 23:55 UTC, Mothblocks requested changes
Just one thing but I'll self commit it

2021-12-31 23:55 UTC, Mothblocks commented on code/datums/action.dm
> +	return (..() && (next_use_time <= world.time))
```suggestion
	return ..() && (next_use_time <= world.time)
```

2021-12-31 23:56 UTC, merged