Fixes an exploit with the ablative trenchcoat
tgstation/tgstation pull request #63524
Opened 2021-12-21 01:26 UTC by SuperNovaa41

## About The Pull Request
Currently you can give yourself a permanent sechud with the trenchcoat.
Fixes https://github.com/tgstation/tgstation/issues/59000
Fixes https://github.com/tgstation/tgstation/issues/47636

## Why It's Good For The Game
blah

## Changelog

:cl:
fix: Fixes the ablative trenchcoat giving you a permanent sechud.
/:cl:

2021-12-21 01:54 UTC, Mothblocks commented on code/modules/clothing/suits/ablativecoat.dm
> +		to_chat(user, "You take off the hood, removing the visor in the process and disabling its integrated hud.") // send chat message here, since RemoveHood() is called a couple times
Bad fix, just send this chat message if they have `TRAIT_SECURITY_HUD` in `RemoveHood`.

2021-12-22 10:15 UTC, Watermelon914 commented on code/modules/clothing/suits/ablativecoat.dm
> +	. = ..()
do this at the end of the proc as `return ..()`

2021-12-22 10:16 UTC, Watermelon914 commented on code/modules/clothing/suits/ablativecoat.dm
> +	to_chat(user, "You take off the hood, removing the visor in the process and disabling its integrated hud.")
use balloon alerts here if you are changing this proc around

2021-12-22 15:08 UTC, Watermelon914 commented on code/modules/clothing/suits/ablativecoat.dm
> +	balloon_alert(user, "You take off the hood, and disable the HUD.")
avoid capitalization here, keep it all lowercase

2021-12-22 21:01 UTC, Mothblocks requested changes
more tiny bikeshed stuff, im gonna commit these myself then push

2021-12-22 21:01 UTC, Mothblocks commented on code/modules/clothing/suits/ablativecoat.dm
> +	balloon_alert(user, "you put on the hood, and enable the hud.")
```suggestion
	balloon_alert(user, "you put on the hood, and enable the hud")
```

2021-12-22 21:01 UTC, Mothblocks commented on code/modules/clothing/suits/ablativecoat.dm
> +	balloon_alert(user, "you take off the hood, and disable the hud.")
```suggestion
	balloon_alert(user, "you take off the hood, and disable the hud")
```

2021-12-22 21:01 UTC, merged

2021-12-28 09:43 UTC, timothymtorres commented
@SuperNovaa41 not sure if this is fixed due to #63668