Implements small labels to abductor glands to see what they do. Part 2.
tgstation/tgstation pull request #63738
Opened 2022-01-01 09:36 UTC by carshalash

## About The Pull Request

Abductors and observers will now be able to see what organ's do upon shift-clicking them. Uhhh, mothblocks was racist towards Australians and the AEST so I GUESS I had to remake this.

## Why It's Good For The Game

Uhhh, who the fuck thought having to check the wiki for every organ was a good idea? This allows for a better experience for abductor scientists and curious ghosts wanting to see what happens next.

## Changelog

:cl:
qol: Adds descriptions to abductor glands upon shiftclick. 
/:cl:

2022-01-01 09:40 UTC, tralezab requested changes
add periods to the end of the descriptions

2022-01-01 09:41 UTC, MrMelbert commented
![image](https://user-images.githubusercontent.com/51863163/147847959-3f559177-033c-4062-b6f2-51e10d887874.png)
arm baba, the examine message itself has the period

2022-01-01 09:41 UTC, carshalash commented
> add periods to the end of the descriptions

Done on purpose, leaving the sentence with two periods ended with double periods due to true_name var.

![image](https://user-images.githubusercontent.com/16896032/147847961-918349ce-7191-430e-9ad9-9808959f579a.png)

2022-01-05 20:06 UTC, MrMelbert requested changes
Honestly, just for readability on the code side + to sooth armhulen it may be better to
- move the period from the examine the messages themselves
- rename `true_name` to something like `abductor_hint` or something

2022-01-05 20:06 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/spider.dm
> +	true_name = "araneae cloister accelerator. Makes the abductee exhale spider pheromones and spawn spiderlings"
```suggestion
	true_name = "araneae cloister accelerator. The abductee occasionally exhales spider pheromones and will spawn spiderlings"
```

2022-01-05 20:06 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/transform.dm
> +	true_name = "anthropmorphic transmorphosizer. Makes the abductee occasionally change appearance and species"
```suggestion
	true_name = "anthropmorphic transmorphosizer. The abductee will occasionally change appearance and species"
```

2022-01-05 20:06 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/viral.dm
> +	true_name = "contamination incubator. Makes the abductee carrier of a random advanced disease - abductee is NOT affected"
```suggestion
	true_name = "contamination incubator. The abductee becomes a carrier of a random advanced disease - of which they are unaffected by"
```

2022-01-06 03:22 UTC, carshalash commented
Periods fixed for arm, did joey's suggestions too.

2022-01-06 08:32 UTC, MrMelbert requested changes
One last nit-pick

2022-01-06 08:32 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/gland.dm
> +	var/abductor_hint = "baseline placebo referencer"
Auto-doc this since you're here anyways?

2022-01-06 23:48 UTC, merged