Refactors playing cards + fixes some issues with them
tgstation/tgstation pull request #63774
Opened 2022-01-02 16:22 UTC by SuperNovaa41

## About The Pull Request
Currently the code is poopy + cards are created and qdel'd upon adding to or removing from a deck.
That's fucking stupid. It causes stupid issues like https://github.com/tgstation/tgstation/issues/53029 and probably undocumented ones.
Fixes that so that the decks are lists of cards. I'm fairly certain this won't be a performance loss, I didn't have any issues on local (but thats a given), and lemon seems to think this would be fine too.
Also adds a bunch of autodoc comments to make this 9+ year old code a little better

## Why It's Good For The Game
bug fix + refactor
Fixes https://github.com/tgstation/tgstation/issues/53029

## Changelog

:cl:
refactor: Decks of cards are actual lists of cards now + other improvements.
fix: You can now put X4/C4 onto playing cards, and put them into decks without deleting your explosive.
/:cl:

2022-01-02 16:30 UTC, SuperNovaa41 commented
fucking whiteship

2022-01-02 17:49 UTC, timothymtorres commented
Very nice!  Was planning to do this myself at some point once I got another computer.  

One thing I would like to point out is that there should be a possibility to remove cards from different decks and mix them together.  Due to this the top card of the deck should auto update the icon_state.

2022-01-02 23:29 UTC, SuperNovaa41 commented
> Very nice! Was planning to do this myself at some point once I got another computer.
> 
> One thing I would like to point out is that there should be a possibility to remove cards from different decks and mix them together. Due to this the top card of the deck should auto update the icon_state.

maybe in a different PR, i want to keep all the functionality the same

2022-01-06 21:30 UTC, tralezab requested changes
small things, great job overall

2022-01-06 21:30 UTC, tralezab commented on code/game/objects/items/toys.dm
>  	var/cooldown = 0
make this into our cooldown macros while you're here :)

2022-01-06 21:30 UTC, tralezab commented on code/game/objects/items/toys.dm
> +/obj/item/toy/cards/deck/proc/generate_card(name)
doc this proc!

2022-01-06 21:30 UTC, tralezab commented on code/game/objects/items/toys.dm
> + * update_sprite
i love it when dmdocs have this, nice

2022-01-08 18:38 UTC, Maurukas approved these changes
Mapping is fine

2022-01-09 22:12 UTC, merged