Makes the admin-only high frequency blade !FUN!
tgstation/tgstation pull request #63861
Opened 2022-01-05 18:47 UTC by Fikou

## About The Pull Request

Reworks the admin-only high frequency blade and unfucks the sprites
Video: https://streamable.com/wpnkm3

## Why It's Good For The Game

fukig ASESOME

## Changelog

:cl:
admin: The high frequency blade is now !FUN!
/:cl:

2022-01-05 18:51 UTC, Sealed101 commented
fikout pls stop teasing me with streamable clips its banned in russia for god knows what reason i beg you

2022-01-05 18:51 UTC, Fikou commented on code/game/objects/items/weaponry.dm
> +/obj/item/melee/moonlight_greatsword
ignore these changes i just put the sword at the end of the file

2022-01-05 22:09 UTC, JohnFulpWillard commented
nice icon diffs

2022-01-05 22:52 UTC, CRITAWAKETS commented
with the low base damage and how augs are a flat damage reduction, simply using an HOS trenchcoat and augs will... 
https://i.kym-cdn.com/entries/icons/original/000/018/016/You_may_not_have_parents_but_at_least_you_got__4427f3dea2c6ba880479abe5d36c9b4f.jpg
Oh, right.

IM FUCKIN INVINCIBLE

2022-01-05 23:19 UTC, Wallemations commented
https://user-images.githubusercontent.com/66052067/148303506-9e79426a-45f3-455c-bd8c-f4862d9a2316.mp4

2022-01-06 22:32 UTC, tralezab commented
i allow it

2022-01-06 22:32 UTC, tralezab commented
but not for free

2022-01-07 02:32 UTC, Krysonism approved these changes

2022-01-07 18:37 UTC, Fikou commented on code/game/objects/items/weaponry.dm
> +	animate(src, duration*0.5, color = COLOR_BLUE, transform = transform.Scale(2), alpha = 255)
if this doesnt work im suing you

2022-01-07 19:06 UTC, Fikou commented
waiting on some decomp stuff

2022-01-09 19:51 UTC, Kylerace requested changes
show me a good time jack

2022-01-09 19:51 UTC, Kylerace commented on code/game/objects/items/weaponry.dm
> +	var/previous_x
doc this and below

2022-01-09 19:51 UTC, Kylerace commented on code/game/objects/items/weaponry.dm
> +	var/atom/previous_target
you dont seem to handle this being deleted

2022-01-09 23:03 UTC, merged