Kills all unneeded uses of spawn()
tgstation/tgstation pull request #63876
Opened 2022-01-06 08:49 UTC by LemonInTheDark

## About The Pull Request
I saw people discussing this. Figured i'd nuke the remaining pointless uses.
Most of these were easy, dizzyness was a bit troublesome because of how jank relative animates are, but I got through it.

## Why It's Good For The Game

Hopefully none will ever need to do this again

2022-01-06 09:03 UTC, TemporalOroboros commented
Out of interest, what are the needed uses of spawn?

2022-01-06 09:10 UTC, LemonInTheDark commented
Similar to sleep. Anything that needs a delay, but can't rely on the timer subsystem existing
There are only 3 left now. One in logout, one in error handling, and one in client init

2022-01-06 15:03 UTC, SuperNovaa41 commented
Chad

2022-01-07 02:18 UTC, tralezab commented
> Similar to sleep. Anything that needs a delay, but can't rely on the timer subsystem existing There are only 3 left now. One in logout, one in error handling, and one in client init

should probably be a comment somewhere, maybe even on the last 3 uses

2022-01-07 02:54 UTC, LemonInTheDark commented
Good idea, thanks blazalert

2022-01-07 12:00 UTC, Mothblocks requested changes

2022-01-07 12:00 UTC, Mothblocks commented on code/modules/chatter/chatter.dm
> +			addtimer(CALLBACK(null, /proc/chatter_speak_word, speaker, letter_count, phomeme, length), delay)
```suggestion
			addtimer(CALLBACK(GLOBAL_PROC, /proc/chatter_speak_word, speaker, letter_count, phomeme, length), delay)
```

2022-01-08 22:29 UTC, LemonInTheDark commented on code/modules/chatter/chatter.dm
> +	addtimer(CALLBACK(null, /proc/chatter_speak, speaker, letter_count, phomeme), delay)
Yes.
It was even more sleeps before. I can cut down on it further now that I think about it

2022-01-08 22:29 UTC, LemonInTheDark commented on code/modules/mob/living/carbon/life.dm
> +			var/y_diff = amplitude * cos(old_dizzy * (time))
yeet

2022-01-08 22:30 UTC, LemonInTheDark commented on code/modules/mob/living/carbon/life.dm
> +			delay += 0.3 SECONDS // This counts as a 0.3 second wait, so we need to shift the sine wave by that much
I'm trying to communicate the idea of tracking the time that will have passed between each successive animate

2022-01-08 22:30 UTC, LemonInTheDark commented on code/modules/mob/living/carbon/life.dm
> +			animate(client, pixel_x = x_diff, pixel_y = y_diff, 3, easing = JUMP_EASING | EASE_OUT, flags = ANIMATION_RELATIVE)
Not always valid, since they're not the same thing

2022-01-08 22:30 UTC, LemonInTheDark commented on code/modules/chatter/chatter.dm
> +			addtimer(CALLBACK(null, /proc/chatter_speak_word, speaker, letter_count, phomeme, length), delay)
sure

2022-01-09 10:40 UTC, LemonInTheDark commented on code/modules/chatter/chatter.dm
> +	addtimer(CALLBACK(null, /proc/chatter_speak, speaker, letter_count, phomeme), delay)
S also not too horrible, it's 1 per word basically, we compress everything down into one timer delay

2022-01-11 07:22 UTC, merged