Boomerang behavior is now defined as a component.
tgstation/tgstation pull request #63949
Opened 2022-01-09 03:51 UTC by ArcaneMusic

## About The Pull Request

Fully refactors boomerang behavior to work as a component, so that a thrown boomerang will return back to it's thrower if within range. More than anything this modularizes the behavior for the backend, as the in-game behavior is intentionally the same as before, but shifts the majority of the behavior to the component for neater code.  For unique behavior when being caught or hitting targets, that should remain on the object.

## Why It's Good For The Game

I have a confession to make:
Oztek Boomerangs and the Clown Energy Shield use the exact same code, copied and pasted. I've wanted to move this over to a component for a long time, but wasn't exactly sure how to make that work, honestly. I just put 2 and 2 together on how to get this rolling while I was gone for Christmas and I just got it rolling now.

Plus, now admins have the ability to make anything a boomerang, if they so choose.

## Video

https://user-images.githubusercontent.com/41715314/148668590-fdb6ab8f-de8a-4cd2-b2ef-ce25594e7485.mp4

## Changelog

:cl:
refactor: Boomerang behavior has been moved to a component.
/:cl:

2022-01-09 04:11 UTC, MrMelbert requested changes
This is cool, a few stylistic things I noticed, i'll check out the code itself later

2022-01-09 04:11 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +		thrower_easy_catch_enabled = _thrower_easy_catch_enabled
- Don't bother saving `true_parent`, just cast it when needed
- underscore parameters are out of style, now parameters are usually just the same as the var name, and we use `src.var = var` to assign them (see the transforming component for an example)

2022-01-09 04:11 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +	//RegisterSignal(parent, COMSIG_CARBON_SUCCESSFUL_CATCH, .proc/BoomerangCooldown)
🤨

2022-01-09 04:11 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +/datum/component/boomerang/proc/PrepareThrow(datum/source, atom/thrown_thing, spin)
- Snake case not camel case please
- Auto-doc your procs for your signals

2022-01-09 04:11 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +	COOLDOWN_DECLARE(last_boomerang_throw)
Might as well doc the cooldown as well

2022-01-09 04:11 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +#define BOOMERANG_REBOUND_INTERVAL (1 SECONDS)
Also this define

2022-01-09 10:58 UTC, Ghommie commented
The cult mirror shield also possesses a similar boomerang behavior. Would it be possible to apply this component to it too?

2022-01-13 19:52 UTC, MrMelbert requested changes
Got around to looking at it, few concerns and notes

Namely keeping the hard reference to the throwing datum seems like a dangerous idea cause they're likely to perish

Changing the mirror shield to use this would be pretty neat as well

2022-01-13 19:52 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +	var/datum/thrownthing/thrown_boomerang
Can this be a weakref? Seems like it'll be disappearing often

2022-01-16 00:00 UTC, ArcaneMusic commented on code/datums/components/boomerang.dm
> +	thrown_boomerang = thrown_thing //Here we update our "thrownthing" datum with that of the original throw for each boomerang. We save it for the return throw.
Wow how did this even work the first time 👀

2022-01-17 19:55 UTC, ArcaneMusic commented
> The cult mirror shield also possesses a similar(-ish) boomerang behavior. Would it be possible to apply this component to it too?

Looking it it, it appears to use some rather tricky behavior, but it's a bit tricky since he uses more unique system to bounce the throw to new targets that might require more behavior than the current basic boomerang behavior. (Plus they're currently admin only)

2022-01-18 04:45 UTC, MrMelbert requested changes

2022-01-18 04:45 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +	//var/datum/weakref/thrown_boomerang
🥴

2022-01-18 04:45 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> + * * thrown_thing: The atom that has had the boomerang component added to it. Updates thrown_boomerang.
"The atom"

2022-01-18 06:14 UTC, ArcaneMusic commented on code/datums/components/boomerang.dm
> +	//var/datum/weakref/thrown_boomerang
I'll admit, I forgot I committed cringe, my B

2022-01-19 00:45 UTC, MrMelbert requested changes

2022-01-19 00:45 UTC, MrMelbert commented on code/datums/components/boomerang.dm
> +		COOLDOWN_START(src, last_boomerang_throw, BOOMERANG_REBOUND_INTERVAL)
Last thing before merging - this code seems to be copy+pasted between `return_hit_throw` and `return_missed_throw`, might be wise to reduce code duplication by moving it into a separate proc?

Also extremely minor nitpick but the `return` at the end isn't necessary

2022-01-21 08:19 UTC, merged