Adds circuit USB for reflectors
tgstation/tgstation pull request #64037
Opened 2022-01-12 19:09 UTC by Blevruz

## About The Pull Request

Reflectors get USB ports. You can put in an angle and, if the reflector is unlocked, it goes to that angle when the component is triggered.

## Why It's Good For The Game

Fun new uses for circuits! Fun new uses for the trig module!! We love lasers!!!

## Changelog

:cl:
add: Reflectors have been slotted with USB ports.
/:cl:

2022-01-12 20:32 UTC, Time-Green commented
This could be so nutty with some smart maths I love it

2022-01-14 02:39 UTC, moocowswag commented
Ive already found that emitters and reflectors make useful traps with circuits, making a turret might not be too hard, i dont think the math will be the hard part, itl be establishing a way to consistently get the entity variable/coords of whoever/whatever you want to target to even begin doing the math.


But that will most likely balance this out and make it the same as most other passive circuit systems (You dont die until your entity variable is uncovered from being silly and walking into a scanner gate and then you die instantly)

2022-01-14 07:26 UTC, Blevruz commented
yea imo th

> Ive already found that emitters and reflectors make useful traps with circuits, making a turret might not be too hard, i dont think the math will be the hard part, itl be establishing a way to consistently get the entity variable/coords of whoever/whatever you want to target to even begin doing the math.
> 
> But that will most likely balance this out and make it the same as most other passive circuit systems (You dont die until your entity variable is caught from being silly and walking into a scanner gate and then you die instantly)

yea i think this and the need for line of sight or the fairly-annoying-to-get x ray guns should be interesting obstacles in playing with this.

2022-01-22 23:36 UTC, LemonInTheDark requested changes

2022-01-22 23:36 UTC, LemonInTheDark commented on code/game/objects/structures/reflector.dm
> +	desc = "Allows to adjust the angle of a reflector."
Allows to -> Allows you to?

2022-01-22 23:41 UTC, Blevruz commented on code/game/objects/structures/reflector.dm
> +	desc = "Allows to adjust the angle of a reflector."
yeah that makes sense

2022-01-23 00:01 UTC, merged

2023-02-06 21:29 UTC, Lauwma commented
Except we don't have a square root module to convert cartesian into angular coordinates

2023-02-15 00:07 UTC, Lauwma commented
> > Except we don't have a square root module to convert cartesian into angular coordinates
> 
> 
> 
> you can just use arctan. tl;dr: tan(_a_) = (length of opposite side) / (length of adjacent side); if you know the position (_rx_, _ry_) of your reflector and the position (_tx_, _ty_) of your target you can get _a_ with arctan( (_rx_ - _tx_) / (_ry_ - _ty_) ) over a 180° arc (can trivially be patched for 360°). give it a shot! its quite fun.
> 
> 

You need R for this which is the distance between your two points and to calculate it you need Pythagorean equation o^2 + a^2 = r^2. To have r from r^2 you need to use sqrt

2023-02-16 15:15 UTC, Blevruz commented
> > > Except we don't have a square root module to convert cartesian into angular coordinates
> > 
> > 
> > you can just use arctan. tl;dr: tan(_a_) = (length of opposite side) / (length of adjacent side); if you know the position (_rx_, _ry_) of your reflector and the position (_tx_, _ty_) of your target you can get _a_ with arctan( (_rx_ - _tx_) / (_ry_ - _ty_) ) over a 180° arc (can trivially be patched for 360°). give it a shot! its quite fun.
> 
> You need R for this which is the distance between your two points and to calculate it you need Pythagorean equation o^2 + a^2 = r^2. To have r from r^2 you need to use sqrt

why do you need r?