Don't eat camera upgrades when applied in assembly
tgstation/tgstation pull request #64057
Opened 2022-01-13 04:38 UTC by mozi-h

## About The Pull Request

Security camera assemblies with upgrades lose them when finished and turned into a camera. This fixes that.

## Why It's Good For The Game

Bugfix. Also pleases our AI overlord.

Fixes #38591

## Changelog

:cl: mozi_h
fix: camera upgrades applied to an assembly will no longer be eaten by the void
/:cl:

2022-01-13 18:57 UTC, mozi-h commented
Also, propaganda campaign for https://github.com/tgstation/tgstation13.org/pull/72
I need MrStonedOne on that. Spread the word!

2022-01-15 03:00 UTC, ShizCalev commented
https://github.com/tgstation/tgstation/commit/9f165d204a0da289707adc8bdda19720fcf7d287#diff-6861e009e2ba31f36e35a3e3316ed490a174e522e36a5bc07548b9faa07530f5R62-R67

who touched my baby

2022-01-15 03:02 UTC, ShizCalev commented
https://github.com/tgstation/tgstation/blob/c5e3d7a4e70784870250b06cc2df56f69197fbd3/code/game/machinery/camera/camera.dm#L64-L83

2022-01-15 03:03 UTC, ShizCalev commented
That should all be handled during init, weird....

2022-01-15 03:04 UTC, ShizCalev commented on code/game/machinery/camera/camera_assembly.dm
> +		C.upgrades += CAMERA_UPGRADE_MOTION
this should all be handled during the camera's init using the proper procs. is this really broken? 
https://github.com/tgstation/tgstation/blob/c5e3d7a4e70784870250b06cc2df56f69197fbd3/code/game/machinery/camera/camera.dm#L64-L83

2022-01-15 03:06 UTC, ShizCalev requested changes

2022-01-15 03:06 UTC, ShizCalev commented on code/game/machinery/camera/camera_assembly.dm
> +
this should all be handled during the camera's init using the proper procs. is the assembly not being passed correctly? 

https://github.com/tgstation/tgstation/blob/c5e3d7a4e70784870250b06cc2df56f69197fbd3/code/game/machinery/camera/camera.dm#L64-L83

2022-01-15 03:08 UTC, ShizCalev commented
also #38591 should have actually been fixed by #41455

2022-01-17 19:13 UTC, ShizCalev commented
Perhaps this was cause by #60228 ?

2022-01-17 19:14 UTC, ShizCalev commented
found the issue.

2022-01-18 12:45 UTC, closed without merging