honkerative MODsuit theme, and paint-kit!
tgstation/tgstation pull request #64064
Opened 2022-01-13 06:29 UTC by capsaicinz

## About The Pull Request

you've all been waiting for it- clown operative MODsuits! clown operatives gain access to a MODsuit paint kit free of charge, and can use this to turn their boring old syndicate MODsuits into funny, clown-styled ones! this has no mechanical change whatsoever, aesthetics only.

![unknown](https://user-images.githubusercontent.com/84609863/149277129-ab725b2b-162b-455c-9796-22d5fb730227.png)

## Why It's Good For The Game

makes clown operatives slightly more distinguishable (and funny) from nuclear operatives.

## Changelog

:cl:
add: Honk Co. is proud to announce their new project: clown operative MODsuits! Adds the "Honkerative" theme to Syndicate MODsuits, and a paint kit module to clown operative uplinks. Honka honka.
/:cl:

2022-01-13 07:05 UTC, capsaicinz commented
aside from that mess there, @LemonInTheDark please label this with DO NOT MERGE until the modsuit files are reorganized, which should be happening in the very very near future..

2022-01-13 07:07 UTC, LemonInTheDark commented
I believe those are in a merge freeze regardless, so unless a rouge maintainer fucks you over you should be fine
if they do, s their problem not yours

2022-01-13 07:07 UTC, capsaicinz commented
COUGH COUGH actually, it's way sooner than i intended, so _no need for that_. just need to wait until it's merged hopefully by tonight.

2022-01-13 07:08 UTC, capsaicinz commented
> I believe those are in a merge freeze regardless, so unless a rouge maintainer fucks you over you should be fine if they do, s their problem not yours

thumbsu uppu

2022-01-13 09:39 UTC, Fikou commented on code/modules/mod/mod_types.dm
> +		)
put this at the bottom and make it an initialize_immediate skin instead, and give it to prefs menu clown outfits

2022-01-13 16:59 UTC, Ghommie requested changes
It seems you are accidentally deleting the paper_maker icon state in the objs/mod.dmi file with these changes. Please fix that, thank you.

2022-01-13 18:52 UTC, Fikou commented on code/modules/mod/mod_types.dm
> +INITIALIZE_IMMEDIATE(/obj/item/mod/control/pre_equipped/honkerative)
actually id just make this a subtype of syndicate empty since its a skin and itd inherit initialize immediate

2022-01-15 00:03 UTC, capsaicinz commented
![unknown](https://user-images.githubusercontent.com/84609863/149599971-a1313e97-e88b-4077-a38b-70b5019abfa0.png)

2022-01-15 08:14 UTC, merged