Safe code documentation
tgstation/tgstation pull request #64096
Opened 2022-01-14 06:33 UTC by dragomagol

## About The Pull Request
Adds better documentation and variable naming to safe code. Also removed one variable that hasn't done anything in years. 

## Why It's Good For The Game
Good documentation and good variable names makes better code

## Changelog
No player-facing changes. 

No player-facing changes.

2022-01-14 06:37 UTC, ExcessiveUseOfCobblestone requested changes
🐱

2022-01-14 06:37 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/storage/secure.dm
> +	/// Is this door hackable?
Please move new variables below inherited variables

2022-01-14 06:37 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/storage/secure.dm
> +	var/lock_code = null
Can you remove = null

2022-01-14 06:37 UTC, ExcessiveUseOfCobblestone commented on code/game/objects/items/storage/secure.dm
> +	var/entered_code = ""
Why not null? Cursed

2022-01-16 23:15 UTC, tralezab requested changes

2022-01-16 23:15 UTC, tralezab commented on code/game/objects/items/storage/secure.dm
>  // -----------------------------
get rid of the stupid fancy comment blocks

2022-01-16 23:15 UTC, tralezab commented on code/game/objects/items/storage/secure.dm
>  // -----------------------------
if there are any more in this file, blam them too.

2022-01-16 23:32 UTC, merged