Traitor Roboticists can now purchase the Springlock MODsuit Module from the uplink, due to being the man behind the slaughter.
tgstation/tgstation pull request #64224
Opened 2022-01-18 23:40 UTC by Iamgoofball

## About The Pull Request

Traitor Roboticists can now purchase the Springlock MODsuit Module from the uplink, due to being the man behind the slaughter.

## Why It's Good For The Game

![Purple_man](https://user-images.githubusercontent.com/4081722/150035820-457fd888-24a0-460f-88e5-e3590ed4b721.png)

## Changelog

:cl:
add: Traitor Roboticists can now purchase the Springlock MODsuit Module from the uplink, due to being the man behind the slaughter.
/:cl:

2022-01-18 23:40 UTC, Fikou commented on code/modules/uplink/uplink_items/job.dm
> +	name = "Springlock MODSuit Module"
```suggestion
	name = "Springlock MODsuit Module"
```

2022-01-18 23:40 UTC, MrDoomBringer commented
https://www.youtube.com/watch?v=3UiPmM9NBAs

2022-01-18 23:42 UTC, Bawhoppen commented
Best PR you'be made since the Tesla 👍

2022-01-19 06:34 UTC, tralezab commented
Genuinely could have some good uses for a roboticist to booby trap their own modsuits.

2022-01-19 10:29 UTC, Fikou requested changes
make it a version that either equips the suit instantly (or very fast) or can chameleon into other modules

2022-01-19 10:29 UTC, Fikou commented on code/modules/uplink/uplink_items/job.dm
> +	restricted_roles = list(JOB_ROBOTICIST)
the head of staff should get it too

2022-01-22 00:02 UTC, tralezab requested changes
overboard guys

2022-01-22 00:02 UTC, tralezab commented on code/modules/mod/modules/modules_antag.dm
> +	mod.wearer.add_atom_colour("#704b96", FIXED_COLOUR_PRIORITY)
too much, remove this part

2022-01-22 00:03 UTC, tralezab commented on code/modules/mod/modules/modules_antag.dm
> +	mod.wearer.add_atom_colour("#704b96", FIXED_COLOUR_PRIORITY)
both colorings, i mean

2022-01-22 00:45 UTC, merged