prevents smuggler satchels from spawning on catwalks
tgstation/tgstation pull request #64346
Opened 2022-01-23 07:41 UTC by magatsuchi

## About The Pull Request

fixes #64340

removes catwalk_plating from the find_satchel_suitable_turfs proc. you may say "tsu, but it alreadys checks for plating!" nope! catwalk_plating is a floor! and catwalk_floor is a plating! just a fun fact for you.

## Why It's Good For The Game

smuggler satchels should not be visible

## Changelog

:cl:
fix: removes catwalk satchels
/:cl:

2022-01-23 07:44 UTC, magatsuchi commented
that's not good

2022-01-23 07:45 UTC, magatsuchi commented
woops wrong path for the turf one second

2022-01-23 07:47 UTC, magatsuchi commented
okay hold on. i mightve just had a schizo moment.

2022-01-23 09:05 UTC, MrMelbert reviewed
Wondering if this could be generalized a bit more, since it happens to glass floors / reinforced glass floors, too.

2022-01-23 09:08 UTC, magatsuchi commented
> Wondering if this could be generalized a bit more, since it happens to glass floors / reinforced glass floors, too.

give me about 10 minutes

2022-01-23 09:15 UTC, magatsuchi commented
@MrMelbert fixed

2022-01-24 18:39 UTC, MrMelbert commented on code/controllers/subsystem/minor_mapping.dm
> +	var/list/unsuitable = list(/turf/open/floor/catwalk_floor, /turf/open/floor/glass)
```suggestion
	var/static/list/unsuitable = list(/turf/open/floor/catwalk_floor, /turf/open/floor/glass)
```
Static list here

2022-01-24 18:39 UTC, MrMelbert commented on code/controllers/subsystem/minor_mapping.dm
> +			if((isfloorturf(t) && !isplatingturf(t)) && !(t in unsuitable))
`t` is an instance of a turf, and `unsuitable` is a list of types, you're checking for an instance of a turf in a list of types

2022-01-24 18:51 UTC, MrMelbert requested changes
Try using something like `underfloor_visibility` to generalize it

2022-01-24 18:52 UTC, magatsuchi commented
got changes, will commit and test when at PC

2022-01-24 23:07 UTC, MrMelbert requested changes

2022-01-24 23:07 UTC, MrMelbert commented on code/controllers/subsystem/minor_mapping.dm
> +		for(var/turf/detected_turf in block(locate(1,1,z), locate(world.maxx,world.maxy,z)))
```suggestion
		for(var/turf/detected_turf as anything in block(locate(1,1,z), locate(world.maxx,world.maxy,z)))
```

2022-01-24 23:24 UTC, merged