Loader Class MODsuit
tgstation/tgstation pull request #64359
Opened 2022-01-23 15:16 UTC by Fikou

## About The Pull Request

Adds the Loader class MODsuit, a powered mobility harness for supplying cargo.
It is not spaceproof and offers no hazard protections, but it excels at mobility
It is supplied with:
A paper dispenser, for quick paper dispensing at any point.
An electronic stamp, able to switch between accept and deny modes.
A large capacity version of the hydraulic clamp. (it's also as fast as the normal one used to be, and the normal one is nerfed) 
A cargo magnet, able to launch crates and lockers towards you, create a strong pull between you and them, and then launch them away.
Hydraulic arms, able to charge you a distance into the air. https://streamable.com/tmgtcp

Also adds a disposal connector module that lets you select where you end up after you take a disposals ride, it is researchable in the BEPIS

Missing sprites and an extended description.

## Why It's Good For The Game

Opens the world of non-spaceproof suits in a fun way. Cargo was missing a suit, and i think this is a perfect fit for them.

## Changelog

:cl:
expansion: Loader Class MODsuit, equipped with hydraulic arms, available in your nearby cargo storage (or qm office on delta).
expansion: BEPIS MODsuit modules, currently available one lets you change your disposal destination.
/:cl:

2022-01-23 15:50 UTC, GoldenAlpharex commented
Nice MODsuit sprite too :)

2022-01-23 17:38 UTC, EricZilla commented
I've been waiting for this one, looks great

2022-01-23 18:38 UTC, Fikou commented
i made a drawing of it so i can plug it
![image](https://user-images.githubusercontent.com/23585223/150692882-01588cd3-5e9a-43f7-8d12-5017dc019b8f.png)

2022-01-23 21:06 UTC, optimumtact commented
Finally, what the ripley should have been.

2022-01-23 21:12 UTC, Serxule commented
i hope launching crates can crash into people like the admin spawn car does

2022-01-23 22:41 UTC, MrDoomBringer commented
> Also adds a disposal connector module that lets you select where you end up after you take a disposals ride, it is researchable in the BEPIS

This is amazing

2022-01-23 22:50 UTC, theta006 commented
you should make punching do more damage this is  a exosuit

2022-01-23 23:56 UTC, IndieanaJones commented
Adding this might be a little Risky.

2022-01-24 00:29 UTC, D4C-420 commented
Never before has punching lizards been so satisfying.

2022-01-25 09:01 UTC, necromanceranne commented
The inactivated suit is giving me Corpus vibes.

2022-01-26 17:44 UTC, SomeDongus commented
RIsk Of Spess

2022-01-28 04:16 UTC, Kylerace requested changes

2022-01-28 04:16 UTC, Kylerace commented on code/modules/mod/modules/modules_supply.dm
> +	if(!(target in view(mod.wearer)) || !istype(target, /obj/structure/closet))
switch these you want the cheapest check to be the first one executed so that the more expensive check doenst run if it cant change the answer

2022-01-28 04:16 UTC, Kylerace commented on code/modules/mod/modules/modules_supply.dm
> +	qdel(mod.wearer.GetComponent(/datum/component/strong_pull))
yuck, doesnt the component does this itself too, for the exact same signal this proc is registered to

2022-01-28 14:10 UTC, merged