[s] Makes used grenades slightly more obvious. Also prevents DOSing admins.
tgstation/tgstation pull request #64643
Opened 2022-02-03 08:29 UTC by TemporalOroboros

Adds a variable to tell whether a grenade can't detonate properly.
Examining can be used to tell if the grenade has already been used.
A flag on it is set when the grenade detonates so that used grenades can't be reused until it's reset.
It also prevents spamming admins with grenade primed messages since there's no point if the grenade won't work.

## About The Pull Request
Adds a variable to track whether a grenade has already been used.
If it has it prevents the grenade from detonating again until the grenade has been reset. (Resetting only implemented for chemical grenades.)
It also prevents priming the grenade/pulsing the grenades wires from messaging admins (but still lets them log) because there's no point in telling the admins if the grenade isn't going to do anything.
The status of the grenade shows up in the examine text.

## Why It's Good For The Game
1. Makes it slightly more obvious that the cleaner grenades in the halls have already been used.
2. Prevents DOSing admins with grenade logging spam. (Fixes #64640)

## Changelog

:cl:
qol: Used grenades now look used when examined.
fix: It should no longer be possible to DC admins by spamming grenades.
/:cl:

2022-02-03 18:24 UTC, TheVekter commented
Based, this should prevent this from happening.

![image](https://user-images.githubusercontent.com/7019927/152405257-89151d1c-a0d0-4b53-80b6-90b57a3e9407.png)

2022-02-03 21:00 UTC, tralezab requested changes
the rest looks good

2022-02-03 23:23 UTC, TemporalOroboros commented on code/game/objects/items/grenades/_grenade.dm
> +	var/dud = FALSE
Done.

2022-02-04 03:36 UTC, Elli-Skala commented
This takes into account the advanced release grenade right?

2022-02-06 12:21 UTC, merged