Blacklists all non-basic radios from the Radio Glove crafting recipe
tgstation/tgstation pull request #64641
Opened 2022-02-03 05:56 UTC by Wallemations

## About The Pull Request
Adds all subtypes of `/obj/item/radio/headset` to the crafting blacklist, leaving only the radio itself.

## Why It's Good For The Game
Some possibilities without this change were:
- Erasing encryption keys
- Erasing sec ear-protecting headsets
- Erasing intercoms

Makes it so this doesn't happen anymore.

## Changelog

:cl: Wallem
fix: Radio Gloves will no longer vacuum your earpieces when crafted.
/:cl:

2022-02-03 06:08 UTC, MrMelbert requested changes
I wonder if it also grabs stuff like radio implants. It might be wiser to generate the blacklist programmatically in `New()`.

2022-02-03 08:12 UTC, Wallemations commented
> I wonder if it also grabs stuff like radio implants. It might be wiser to generate the blacklist programmatically in `New()`.

You know I never really thought of that. On that same note, I wonder if it'll mess with the antenna mutation. I'll have to test these things tomorrow to see how they work and if it'll need to be fixed.
And what exactly do you mean by blacklisting them programmatically? Do you mean adding them to the blacklist individually instead of all at once? I'm having a little bit of an issue understanding exactly what you meant.

2022-02-03 09:06 UTC, MrMelbert commented
Instead of adding all subtypes of radios to the list automatically...
```
/datum/crafting_recipe/whatever/New()
   . = ..()
   blacklist = subtypesof(/obj/item/radio)
```

2022-02-03 16:29 UTC, Wallemations commented
> 
> ```
> 
> /datum/crafting_recipe/whatever/New()
> 
>    . = ..()
> 
>    blacklist = subtypesof(/obj/item/radio)
> 
> ```

I forgot that was a function we had, I'll try it out when I get home

2022-02-03 20:35 UTC, Wallemations commented
> (I have no idea if this will _actually_ work or not, but it should?)

It worked, epic

2022-02-06 19:12 UTC, Rohesie commented
This will work, yes, but we'd be better served by refactoring how recipes work and having a second variable of requirements that accept no children.

2022-02-06 19:13 UTC, merged