You can't talk on the radio while handcuffed or while stunned in some form.
tgstation/tgstation pull request #64689
Opened 2022-02-05 16:36 UTC by Iamgoofball

## About The Pull Request

Helps encourage stealthy antagonist gameplay by preventing ;HELP SCI MAINT while you're being murdered due to the lack of -GLORF, while also evening the gap between fast and slow typers.

Also fixes ;SHITSEC.

## Why It's Good For The Game
Helps encourage stealthy antagonist gameplay by preventing ;HELP SCI MAINT while you're being murdered due to the lack of -GLORF, while also evening the gap between fast and slow typers.

Also fixes ;SHITSEC.

## Changelog
:cl:
balance: You can't talk on the radio while handcuffed or while stunned in some form.
/:cl:

2022-02-05 16:38 UTC, Fikou commented
cult shackles explicitly mute you so you probably want to remove that

2022-02-05 16:41 UTC, willox commented
Does this stop people from using the radio while in a clown car?

2022-02-05 16:46 UTC, Iamgoofball commented
@willox That depends on what exactly clown cars do to their ~~victims~~passengers.

2022-02-05 16:52 UTC, SuperNovaa41 commented
This makes no sense, nor do you actually justify it

2022-02-05 17:31 UTC, CameronWoof commented
We currently have radio jammers, which cost TC to purchase and are contraband to own, which serves the purpose of enabling stealth antagonists to kidnap people without them being able to call for help. I don't agree with the ability of that item being rolled in to handcuffs automatically for no cost.

2022-02-05 18:51 UTC, Rohesie requested changes
I'm not married to this idea, but if implemented properly and not blocked by other maintainers I'm willing to give it a try.
The current implementation is not proper, though.

Don't use `TRAIT_HANDS_BLOCKED`, which is tied to a ton of behavior you probably don't want to carry along (such as any sealed vehicle including the clown car blocking speech, aggressive grabs and xeno nests as well), and it might get linked to even more in the future.
Instead, make a new trait, something like `TRAIT_EARS_USAGE_BLOCKED`, and add/remove as necessary. You can find all the 24 instances of adding the other trait with the `ADD_TRAIT\(.*TRAIT_HANDS_BLOCKED` regex, and you'll notice that most don't need to block ears usage.

Also, instead of handling things in `/mob/living/carbon/radio()` and `talk_into()` both you should handle it in `/mob/living/carbon/human/radio()`

2022-02-05 19:23 UTC, Iamgoofball commented
shit i hit the wrong button

2022-02-05 19:23 UTC, Iamgoofball commented
>I'm not sure if this is really compatible with the kind of gameplay loop we have in the LRP servers.

We do not care about players at LRP, they should be playing at MRP standards because oranges has declared us an MRP codebase.

2022-02-05 20:02 UTC, Donpedrito commented
Antagonists already have a number of tools at their disposal to prevent being called out over the radio. I’m not a fan of taking cult mute, muzzles, radio jammer, mute toxin, mute sting, disabling telecomms with TC, disabling telecomms with a bomb, abductor batons, and other tools and rendering them mostly useless because their functionality has been given to the funny stunbaton.

2022-02-05 20:34 UTC, moocowswag commented
Stun combat doesn`t need another massive direct buff, one of the main fundamental counters to it is receiving outside assistance since you will FULLY recover on your own as long as you`re protected in your incapacitated state.

This just enables antags to craft/steal stun batons and go around baton cuffing people and dragging them into maint to be killed without needing tcomms to be down or countered at all.

2022-02-05 23:41 UTC, D4C-420 commented
There's already a way all people have to prevent talking over comms. its called stealing their headset which anyone can do without much effort or prep.

2022-02-05 23:42 UTC, Thunder12345 commented
Or dropping a couple of TCs on a radio jammer for an easy, passive, AoE comms blackout

2022-02-06 00:42 UTC, Ryll-Ryll commented
this doesn't seem like a good idea for either LRP and MRP

2022-02-06 00:46 UTC, LemonInTheDark commented
I'm sorry roh, I don't want this. Violently.

Most of the fun of interactions in this game are tied to interacting with the sandbox. 
What you're doing here invalidates much of that, and makes many traitor items and general tactics pointless.

If the issue you're trying to address is people not using those tools, the solution is not to come in with a bulldozer make a expansive system totally irrelevant.
I really hate this kind of thing. Regardless of if people are radioing too much or not (not that I would know), this shit absolutely makes the game worse. I realize making a more in depth change is more tricky, but I will not live with this. Please don't do it in future, you're better then it.

2022-02-06 00:46 UTC, LemonInTheDark commented
Leaving this open for now, will close at 24 hours unless a maint comes for me

2022-02-06 00:54 UTC, moocowswag commented
> There's already a way all people have to prevent talking over comms. its called stealing their headset which anyone can do without much effort or prep.

If you can`t yell "help [insert location here]" In the time it takes for someone to stun you and watch a bar fill up as they take off your radio then thats kind of on you. 

> Or dropping a couple of TC

Exactly, youre paying to be able to do that, this pr makes it so that if you have a stun baton or flash or any other stun weapon you automatically have the additional advantage of instantly preventing your victim from talking as soon as you apply that weapon without needing to disable tcomms or purchasing something...

2022-02-06 08:45 UTC, ANAME593 commented
think about it tho if somebody cuffs you what stops you from talking into a headset same with being stamcritted by batons or disabler beams

2022-02-06 10:06 UTC, cacogen commented
What the fuck did the lizardpeople in charge of the code nowadays do to glorf anyway? I haven't seen it in a long time so I'm guessing they removed it. That was one of those additions of the future you never expected to see in the game. Like how does it know you're typing? It's a client side interaction with a text box and yet it does and it'll candlejack tha

2022-02-06 11:21 UTC, LemonInTheDark commented
We can't do it without the command bar, which is not what most people use

2022-02-06 12:34 UTC, cacogen commented
We can rebuild him https://github.com/tgstation/tgstation/pull/52341#issuecomment-660748051

2022-02-06 13:49 UTC, Thunder12345 commented
> We can rebuild him [#52341 (comment)](https://github.com/tgstation/tgstation/pull/52341#issuecomment-660748051)

Better get coding

2022-02-06 14:02 UTC, AnCopper commented
ITT: People do not know how manual radios work.

2022-02-06 15:11 UTC, cacogen commented
Yeah it's not voice activated you have to push your ear in like a secret service agent and the reason you can do this with both hands full is because you just use your knuckle stupid. You raise the entire potted plant to the side of your head and push on the headset with the back of your hand dummy.

2022-02-06 19:02 UTC, Rohesie commented
24 hours is up, this is being closed due to not being wanted by the maintainers.
Please get a maintainer to support it before re-opening it.

2022-02-06 19:02 UTC, closed without merging

2022-02-06 19:04 UTC, Addust commented
> > I'm not sure if this is really compatible with the kind of gameplay loop we have in the LRP servers.
> 
> We do not care about players at LRP, they should be playing at MRP standards because oranges has declared us an MRP codebase. I'm not entirely convinced that we should be catering to players who already refuse to use communication outside of validhunting.

terry will hate you

2022-02-06 20:18 UTC, Rohesie commented
Shaps expressed dislike and Potato blocked it.
Even if other maintainers agree, they'll have to convince Potato.
And, honestly, I'm not sure it's a good idea either.

2022-02-06 21:00 UTC, Iamgoofball commented
Maybe actually give it a shot for a few weeks and collect data?

2022-02-06 21:02 UTC, Rohesie commented
Try convincing Potato and Shaps.

2022-02-06 21:23 UTC, Mothblocks commented
> We do not care about players at LRP, they should be playing at MRP standards because oranges has declared us an MRP codebase.

this is not what the codebase is MRP means. there is a reason it is always followed up with the sentence "manuel is HRP"