Removes a pointless initial() call from chameleon changing
tgstation/tgstation pull request #64771
Opened 2022-02-08 17:15 UTC by ike709

## About The Pull Request

Calling `initial()` on a local var or proc arg just returns the current value. I added a compiler warning for this in OpenDream, which caught this.

2022-02-09 23:52 UTC, MrMelbert requested changes
`picked_item` is a typepath and not an instantiated object, and as such this check will never pass (though I doubt it ever worked in the first place?)

2022-02-10 02:35 UTC, ike709 commented on code/modules/clothing/chameleon.dm
> +		if(istype(item_target, /obj/item/clothing) && istype(picked_item, /obj/item/clothing))
```suggestion
		if(istype(item_target, /obj/item/clothing) && ispath(picked_item, /obj/item/clothing))
```

2022-02-10 02:37 UTC, ike709 commented
@MrMelbert I was hoping nobody would notice so I didn't have to deal with it. See https://github.com/ParadiseSS13/Paradise/pull/17392

2022-02-10 02:42 UTC, ike709 commented
And yeah, it never worked with or without the `initial()`

2022-02-11 09:46 UTC, merged