Mobs on the CentCom Z level will not be selected as valentines.
tgstation/tgstation pull request #64926
Opened 2022-02-14 20:49 UTC by JoshAdamPowell

## About The Pull Request

Mobs on the Centcom Z Level will not be selected as valentines.

## Why It's Good For The Game

I was testing things in the thunderdome and I got made a valentine to someone on the station. It's a bit sad that this player can't interact with this fun event cause I was messing around in centcom

fixes #64923 

## Changelog

:cl:
fix: Staff at Centcom are busy people! They are no longer allowed to go on valentines dates.

/:cl:

2022-02-14 20:49 UTC, Mothblocks approved these changes
it's called a long distance relationship

2022-02-14 20:50 UTC, cacogen commented
It affects Free Golems and Charlie Station as well, and at least the latter is not supposed to leave their z-level which limits their ability to uh "interact with this fun event" as you put it so maybe it should just be the station z levels?

2022-02-14 20:58 UTC, JoshAdamPowell commented
hm. Should mining get it? on the one hand ash lizards shouldn't but miners should.

2022-02-14 21:23 UTC, MrMelbert commented
This removes Nuke Ops valentines 👎

2022-02-14 22:36 UTC, Mothblocks requested changes
actually wait theyre all right, nuke ops valentines is funny and i want to keep that

can you limit this to just centcom AREAS?

2022-02-15 00:42 UTC, JoshAdamPowell commented
okie dokie, will do

2022-02-15 00:42 UTC, Bawhoppen commented
this is funny for everyone

2022-02-15 00:57 UTC, JoshAdamPowell commented
(I am trusting the onCentCom method is working as expected...)

2022-02-15 01:02 UTC, Mothblocks commented
that should work yeah

2022-02-15 01:02 UTC, Mothblocks approved these changes

2022-02-16 19:35 UTC, merged