Pyro bundle fix and slight buff to Anti-Tider
tgstation/tgstation pull request #64934
Opened 2022-02-15 01:28 UTC by Amrabol

## About The Pull Request
Pyro bundle was broken as when you brought it you would get modsuit and pyro backpack forcing you to either use armor or use backpack without fire protection(which modsuit has).
Anti-Tider on the other hand is rarely used(i have never seen it used when i was playing sec or observing) and needed a little buff so you can now carry it on suit storage slot but only using one of four clothes - Riot armor, Swat armor, Sec modsuit and HoS modsuit

## Why It's Good For The Game

## Changelog

:cl:
balance: Nanotrasen develops new rig for Anti-Tider backpack allowing it to be wear on suit slot of Riot armor, Swat armor and both sec modsuits
fix: Syndicate quickly steals design and applies it to their pyro backpack allowing it to be used with modsuit
/:cl:

2022-02-15 01:40 UTC, MrDoomBringer commented
Seeing an officer remove their entire backpack for a glorified pepperspray is hilarious, even moreso when it actually works. It has a certain charm to being a backpack-slot item and tbh there are cooler ways to balance it than letting everyone put it in their suit slot

2022-02-15 01:44 UTC, Amrabol commented
> Seeing an officer remove their entire backpack for a glorified pepperspray is hilarious, even moreso when it actually works. It has a certain charm to being a backpack-slot item and tbh there are cooler ways to balance it than letting everyone put it in their suit slot

Thats why its only allowed on 4 clothes. Im still thinking that swat was overkill in that regard but it forces them out of basic sec armor. So they have to sacrifice something to be able to wear it on suit slot

2022-02-15 06:43 UTC, tralezab requested changes
Just make them modsuit modules

2022-02-15 06:49 UTC, tralezab commented
And to specify: Pyro bundle is a default module on the included modsuit, anti tider backpack should still exist but also be a security modsuit module, your choice if default or research (but respect fikou if he decides on this)

2022-02-15 11:48 UTC, ATH1909 commented
> Just make them modsuit modules

aw, but then I can't do ghetto chemistry with them

2022-02-15 16:02 UTC, Fikou commented on code/modules/mod/mod_types.dm
> +		/obj/item/mod/module/flamethrower
```suggestion
		/obj/item/mod/module/flamethrower,
```

2022-02-15 19:08 UTC, Fikou commented on code/modules/mod/mod_theme.dm
> +	inbuilt_modules = list(/obj/item/mod/module/mister/security)
dont make this inbuilt, make it initial in the mod object

2022-02-15 19:10 UTC, Fikou commented on code/modules/research/designs/mechfabricator_designs.dm
> +/datum/design/module/mod_mister/atmos
you dont have a mod_mister path, just make this module/mister_atmos

2022-02-15 19:11 UTC, Fikou commented on code/modules/mod/mod_theme.dm
> +	inbuilt_modules = list(/obj/item/mod/module/mister/security)
same with the other

2022-02-15 21:17 UTC, Amrabol commented on code/modules/research/techweb/all_nodes.dm
> +		"mod_mister_atmos",
Will make it cost also 1000 silver, 1500 titanium and 500 uranium

2022-02-15 21:20 UTC, Amrabol commented
Will make it ready to review once i make it that Anti-Tider shoots at 3 tiles at once

2022-02-15 23:35 UTC, tralezab commented
Thanks for putting in the work

2022-02-16 08:44 UTC, Twaticus approved these changes

2022-02-16 12:31 UTC, Amrabol commented
I tried to make it that Anti-Tider shoots at 3 tiles at once, even found code that i could use for this. Yet i lack knowledge how to make that code work for Anti-Tider so for now i will just give Anti-Tider more volume(double of modsuit module(module has 500)). Will try to come back in future once i will make that code works

2022-02-16 12:46 UTC, Amrabol commented
I wanted to make it that every pepper spray item had its purpose:
-Pepper spray - hand hold, small, little range;
-Pepper spray mister module - works in modsuit, has bigger range and capacity than hand held one, can't be stolen from hand;
-Anti-Tider backpack - superior volume, superior range, can't be stolen from hand, slows user a little(was also supposed to shoot at 3 tile lines at once but it is currently beyond my capabilites(im writing this even when its fikou who did almost all the work(i wanted to do that myself but will try to comeback to it later))).

2022-02-16 21:01 UTC, merged