Fixes the inputs for the linear and exponential sustain settings of the song editor.
tgstation/tgstation pull request #65008
Opened 2022-02-18 21:53 UTC by Ghommie

## About The Pull Request
Fixes an issue that arose when the inputs for several settings of the song editor (instruments, basically) menu were changed to use TGUI.
Basically, the tgui numerical input always rounds down the submitted value to an integer in the current situation, and this messes up with the linear and exponential sustain settings of songs. To solve this problem I moved the round() call responsible of it behind a conditional operator tied to a new argument and variable called `round_value`.
Pretty straightforward stuff, the input will only be rounded down only if the arg is true now (which is by default, except for those two settings I talked about). This should fix the problem best.

## Why It's Good For The Game
This will fix #64992

## Changelog

:cl:
fix: Fixed the inputs for the linear and exponential sustain settings of the song editor (instruments UI).
/:cl:

2022-03-06 01:43 UTC, MrMelbert requested changes

2022-03-06 01:43 UTC, MrMelbert commented on code/modules/tgui/tgui_input_number.dm
> +	src.round_value = round_value
`round_value` should default to `TRUE` if no value is supplied, as the current behavior does

2022-03-06 01:46 UTC, MrMelbert commented on code/modules/tgui/tgui_input_number.dm
> +	src.round_value = round_value
Actually I've decided it doesn't really matter

2022-03-06 01:46 UTC, MrMelbert approved these changes

2022-03-06 01:52 UTC, merged

2022-04-07 14:33 UTC, Jamarkus127 commented
exact same issue. dunno what it could be though

2022-05-03 22:45 UTC, Jamarkus127 commented
@Ghommie Still the same issue, its still not fixed. Yeah, we can go to 0.1, but thats it. if we try0.5, it breaks and defaults to 5.

2022-05-15 00:58 UTC, Jamarkus127 commented
this is never gonna get fixed. is it...

2022-05-20 02:11 UTC, Jamarkus127 commented
OK. turns out instruments are still fucked. I tested with a synth and now the only decimal point I can go to is 0.1 and thats if I dont mess with the number. this is exactly like  #64992 Either this PR is now outdated, or it wasnt fixed to begin with.

2022-05-20 13:16 UTC, Ghommie commented
Ok, turns out this is an issue with the TGUI front end not allowing decimal inputs (it removes the dot so 1.05 would turn into 105 for example).