Makes lock access on tablet researching a var
tgstation/tgstation pull request #65121
Opened 2022-02-23 21:25 UTC by JohnFulpWillard

## About The Pull Request

Makes access needed to lock/unlock an RnD tablet app, a var on the app itself, much like the RnD console itself does.
Making this PR is how I found out locking/unlocking consoles requires RND access, not RD office, which I find really dumb, but I don't want to spend the GBP to change it.

## Why It's Good For The Game

Consistent between the two apps.
Honestly I'm confused why we have this system where we just had two of every app, one for tablets and one for its own separate computer. I'm sure there's a better way to go about this, but I'm kinda lazy?

## Changelog

Not needed.

2022-02-23 22:24 UTC, GuillaumePrata commented
By the looks of it this access is only used on the RND console and the windoor/shutters at the RND lab.
Feels like a very redundant access since everyone at Science has ACCESS_RND on top of their normal access.

2022-02-23 22:25 UTC, zxaber commented
Truth be told, the console could probably be removed enirely in favor of the app. We did that with the HoP's ID console I think.

2022-02-23 23:25 UTC, TrashDoxx requested changes
Add space before comment.
Pls. I'm dead inside.

2022-02-24 13:55 UTC, JohnFulpWillard commented
> Truth be told, the console could probably be removed enirely in favor of the app. We did that with the HoP's ID console I think.
> 
> > By the looks of it this access is only used on the RND console and the windoor/shutters at the RND lab. Feels like a very redundant access since everyone at Science has ACCESS_RND on top of their normal access.
> 
> There's a few non-science jobs like HoS and paramedic that have RESEARCH but not RND. This lets them access the science halls but not the console. My PR that allows science to download and run the science hub app also uses RND, not RESEARCH.

It's similar with SecurEye, Skill tracker, SignalCommander, and the arcade app. These all have non-tablet counterparts that basically just copy+paste eachother.
I'm thinking a possible solution would be to turn (at least in the case of arcade/secureye/rnd console) would be to make them all tablet computers that only have the one app.

2022-03-01 21:48 UTC, merged