makes circles and slappers huge
tgstation/tgstation pull request #65169
Opened 2022-02-25 21:38 UTC by JohnFulpWillard

## About The Pull Request

Makes circlehands and slappers huge, just like offhand is.
I dunno if it is worth adding a check to evidence bag for dropdel to not fit, because I don't know how much the flag is used, but I thought changing the hand's weights would be better in the long run for those specific items since this problem might not be limited to just evidence bags.

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/65168 and possibly more edgecases.

## Changelog

:cl:
fix: Slappers and circlehands don't fit in storage bags anymore.
/:cl:

2022-02-25 21:39 UTC, ArcaneMusic commented
As an additional safeguard, you should have evidence bags check of the object you're trying to add is abstract.

2022-02-25 21:40 UTC, JohnFulpWillard commented
> As an additional safeguard, you should have evidence bags check if the object you're trying to add is abstract.

![image](https://user-images.githubusercontent.com/53777086/155806803-a92774c1-5cb5-4df6-8edc-20fe42e59c06.png)

2022-02-25 21:55 UTC, Ghommie requested changes
Could you please use the `TRAIT_NO_STORAGE_INSERT` trait instead? Changing the `w_class` is a suboptimal solution because it won't stop the item from being inserted in a _hypothetical_ (unless I'm wrong, huge items cannot be inserted in the BoH anymore) storage item with a high enough `max_w_class`.

2022-02-27 21:51 UTC, MrMelbert requested changes
What Ghommie said, changing w_class is a bandaid 

`HAND_ITEM` flagged items probably shouldn't exist in a state which it's not held by a mob, anyways

2022-03-06 01:12 UTC, MrMelbert commented on code/game/objects/items/hand_items.dm
> +	w_class = WEIGHT_CLASS_HUGE
Leftover?

2022-03-06 01:13 UTC, JohnFulpWillard commented on code/game/objects/items/hand_items.dm
> +	w_class = WEIGHT_CLASS_HUGE
yeah my bad

2022-03-06 01:39 UTC, merged