EVA Varedited Cells
tgstation/tgstation pull request #65179
Opened 2022-02-26 08:53 UTC by Cheshify

## About The Pull Request
https://github.com/tgstation/tgstation/issues/65176
I was checking out the issue linked above, and I noticed that the cells were 15Mj in the screenshot, while high-capacity cells are only 10Mj. Well, I looked into it, and it turns out that Tram and Metastation have these random varedited high-capacity cells that are barely charged and have a 5Mj higher capacity for SOME REASON. It's not like this on Ice or Delta, so I just swapped the cells in Meta with 2 normal charged high-caps, and the one in tram with the same 2 charged high-caps.

## Why It's Good For The Game
Consistency's sake? I don't know why we even have these. Feel free to close if this is some game-critical feature we absolutely need to have, I'm just so confused.

## Changelog

:cl:
fix: Certain stations no longer contain slightly better high-capacity cells in their EVA Storage rooms.
/:cl:

2022-02-26 16:38 UTC, TheBonded commented
*with 0.7% charge

2022-02-28 00:06 UTC, Fikou commented
put "fixes #issue" so it automatically gets closed when this pr is merged

2022-02-28 01:49 UTC, Cheshify commented
> put "fixes #issue" so it automatically gets closed when this pr is merged

Didn't know I could even do that, hopefully it's done right?

2022-02-28 03:52 UTC, ShizCalev commented on _maps/map_files/MetaStation/MetaStation.dmm
> +/obj/item/stock_parts/cell/high,
/obj/item/stock_parts/cell/high/plus are 15k cells btw.

2022-02-28 03:53 UTC, ShizCalev requested changes
![image](https://user-images.githubusercontent.com/6209658/155921256-54b1fc64-26f9-4248-99fc-41097f60704e.png)
looking at it, this looks like it's just a bad copypasta that's been copypasta'd a lot more since.

fix all of them, please.

2022-03-06 06:35 UTC, cacogen commented
I made cells with charge set not have their charge updated to maxcharge in the cell's Initialize() recently, which prompted me to make https://github.com/tgstation/tgstation/pull/65114 after seeing these cells in EVA with yellow overlays but 0% charge and doing that has made the charge read 0.7% which drew people's attention to the fact these cells have map-edited vars.

2022-03-22 00:15 UTC, closed without merging