thermomachine upgrades
tgstation/tgstation pull request #65470
Opened 2022-03-14 20:42 UTC by Ghilker

## About The Pull Request
You can now upgrade the thermomachines by using 3 sheets of metallic h2 on them.
This upgrade allows them to consume all the heat without needing to connect the waste port to any gas source.

## Why It's Good For The Game
Upgradeable thermomachines and more uses for the metallic hydrogen

## Changelog

:cl:
expansion: thanks to the latest discoveries, metallic hydrogen can be installed inside the thermomachines to allow their use without needing a thermal port connected to a gas reservoir (a total of 3 metallic h2 sheets are required, obtain them from the local crystallizer, warranty void if applied to other machines)
/:cl:

2022-03-15 04:46 UTC, CRITAWAKETS commented
so is this like old freezer behaviour? if so, that's kinda based

2022-03-15 06:16 UTC, Colovorat commented
actual good ghilker pr wtf??????

2022-03-22 22:30 UTC, LemonInTheDark requested changes
I'm ok with this in theory. Not really sure there's a purpose to thermomachines having to manage cooling heat and all, but there's nothing inherently wrong with this, and that conversation is really tiring

2022-03-22 22:30 UTC, LemonInTheDark commented on code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm
> +		. += span_notice("Can be upgraded with 2 sheets of metallic hydrogen.")
2? or 3

2022-03-22 22:37 UTC, Ghilker commented on code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm
> +		. += span_notice("Can be upgraded with 2 sheets of metallic hydrogen.")
whoops is 3, i'll fix it

2022-03-22 22:37 UTC, Ghilker commented on code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm
> +		. += span_notice("Can be upgraded with 2 sheets of metallic hydrogen.")
```suggestion
		. += span_notice("Can be upgraded with 3 sheets of metallic hydrogen.")
```

2022-03-31 07:25 UTC, LemonInTheDark commented
Will likely walk this back totally in future, but it's good for now

2022-03-31 07:27 UTC, merged