Fixes airlock controller issues
tgstation/tgstation pull request #65540
Opened 2022-03-18 00:17 UTC by jlsnow301

## About The Pull Request
Fixed some issues related to airlock controllers (notably, incinerator)
It might've been entirely unnecessary to refactor it into TS but I did it anyway, it looks and functions the same.

## Why It's Good For The Game
Fixes #65377

## Changelog

:cl:
fix: Airlock controller TGUI windows should now display a window title and not pop up when closed (Go away!)
/:cl:

2022-03-22 07:05 UTC, stylemistake approved these changes

2022-03-26 22:39 UTC, LemonInTheDark commented on code/game/machinery/embedded_controller/embedded_controller_base.dm
> -	addtimer(CALLBACK(src, .proc/updateDialog), 5)
This is not dead code. The command prop is still used 
![image](https://user-images.githubusercontent.com/58055496/160259289-860151a9-64e6-40af-ac92-961efa3def79.png)

2022-03-26 22:39 UTC, LemonInTheDark requested changes
See above, the code you're removing ain't dead

2022-04-03 02:41 UTC, jlsnow301 commented
closed until further notice - more intricate than originally expected, don't have time to work with it

2022-04-03 02:41 UTC, closed without merging