re-adds the assistant traitor toolbox
tgstation/tgstation pull request #65703
Opened 2022-03-26 09:08 UTC by JohnFulpWillard

## About The Pull Request

Removed in https://github.com/tgstation/tgstation/pull/63588
![image](https://user-images.githubusercontent.com/53777086/160232666-33873485-6e60-467a-b3bd-8efd38d5a13e.png)

Not sure if its removal was intentional, so I'm gonna give it a shot and try to re-add it.

## Why It's Good For The Game

It's a cool traitor item and, although I dislike encouraging people to play Assistant, I still like seeing this item in game.
We also don't know if this removal was intentional or not, so I'm restoring previous features that might've been accidentally removed.

## Changelog

:cl:
fix: Assistant Traitors can now purchase the Ancient Toolbox again.
/:cl:

2022-03-26 09:22 UTC, Serxule commented
i think it was since.. yknow, unlimited TC (almost)

2022-03-26 12:00 UTC, Jolly-66 commented
> i think it was since.. yknow, unlimited TC (almost)

I don't know what the "cap" is for it, but I know at a certain amount of TC the toolbox becomes just absurdly stupid
I don't think its an issue in all honesty, at least assistants now have an incentive to do more objectives 

Greytide station wide baybeee

2022-03-26 16:29 UTC, Colovorat commented
> > i think it was since.. yknow, unlimited TC (almost)
> 
> I don't know what the "cap" is for it, but I know at a certain amount of TC the toolbox becomes just absurdly stupid I don't think its an issue in all honesty, at least assistants now have an incentive to do more objectives
> 
> Greytide station wide baybeee

iirc with 20 TC it 3 shots or even 2 shots

2022-03-27 04:47 UTC, SuperNovaa41 commented
> > > i think it was since.. yknow, unlimited TC (almost)
> > 
> > 
> > I don't know what the "cap" is for it, but I know at a certain amount of TC the toolbox becomes just absurdly stupid I don't think its an issue in all honesty, at least assistants now have an incentive to do more objectives
> > Greytide station wide baybeee
> 
> iirc with 20 TC it 3 shots or even 2 shots

i THINK it 3 shots but you can stack more than that to get it up to 2 (or 1 if you get enough)

2022-03-27 05:31 UTC, JohnFulpWillard commented
with 20 TC its 39 brute

2022-03-27 09:05 UTC, bluetshirtguy commented
Wasn't it thought that giving traitors tons of extra tc would make this item busted

2022-03-31 10:37 UTC, Mothblocks requested changes
you absolutely need to balance this somehow, i don't have a grasp on TC numbers so let's just say make 40 tc do what 20 tc did before

2022-03-31 21:27 UTC, merged