Confiscates the bounty hunter flamethrower, gives them a fire cycler shotgun + fire pistol
tgstation/tgstation pull request #65984
Opened 2022-04-06 00:54 UTC by Ryll-Ryll

## About The Pull Request
Some lovely person who will go unnamed decided 3 years ago that the flamethrowers would be a good weapon for some bounty hunters to use to hunt their quarry. This turned out to be a massive liability and cause lots of innocent people to get toasted, so this PR aims to give them a different fire-based arsenal that isn't so indiscriminate.

The armored bounty hunter role is now issued a cycler dual-tube shotgun that comes with one tube of rubbershot, and one tube of a new incendiary shotgun slug that leaves no fire trail, but still lights up their target. They also receive a 9mm Makarov loaded with fire bullets and one spare mag (these ones do leave a trail).

## Why It's Good For The Game
When an armored bounty hunter unloaded a flamethrower on the emergency shuttle trying to catch a fugitive, I thought for sure he was lying when he said that was the only weapon he got. Turns out he was right! Neither of the guns are as powerful as a flamethrower, but hopefully together they can be a good substitute.

## Changelog

:cl: Ryll/Shaps
balance: Armored bounty hunters are no longer being issued flamethrowers. Instead, they are now issued dual-tube shotguns filled with rubbershot and trailless incendiary slugs, as well as a 9mm Makarov loaded with fire bullets.
/:cl:

2022-04-06 00:55 UTC, tralezab commented
good!

2022-04-06 01:35 UTC, Cheshify commented
I was literally going to go in and rework all these loadouts, this is incredibly cool.

2022-04-08 17:39 UTC, Fikou commented on code/modules/projectiles/projectile/bullets/_incendiary.dm
> +	if(leaves_fire_trail)
early returns?

2022-04-08 17:50 UTC, Fikou commented
shotguns are already the gimmick of the hook bounty hunter, this feels like its making the armored one superior to the other ones which is kinda lame

2022-04-21 19:19 UTC, MrMelbert commented on code/modules/projectiles/guns/ballistic/shotgun.dm
> +	alt_mag_type = alt_mag_type || mag_type
```suggestion
	alt_mag_type ||= mag_type
```
if you wanna used a cursed operator

2022-04-26 00:40 UTC, MrMelbert requested changes

2022-04-26 00:40 UTC, MrMelbert commented on code/modules/projectiles/projectile/bullets/_incendiary.dm
> +	location.hotspot_expose(700, 50, 1)
`if(location)` has to be moved back

2022-05-01 22:10 UTC, tralezab requested changes
JUST SUPER QUICK

2022-05-01 22:10 UTC, tralezab commented on code/modules/antagonists/fugitive/fugitive_outfits.dm
> +		)
sorry to be a stickler but unindent this `)`

2022-05-01 22:20 UTC, merged