Block free golems from using shuttle consoles, other than to go home
tgstation/tgstation pull request #65991
Opened 2022-04-06 05:11 UTC by Mothblocks

## About The Pull Request
Block free golems from using shuttle consoles, as long as they are not already on the station.

## Why It's Good For The Game

The crippling changes to free golems have been met as a challenge by some, rather than as a blockade.

The changes exist specifically so that, if by some magic of gameplay, free golems *do* make it on the station, they are heavily crippled to the point that they should have no choice but to go back.

However, I didn't realize that "some magic of gameplay" includes just using the console. I was probably thinking of ash walkers not being able to do it?

## Changelog

:cl:
balance: Free golems can no longer use shuttle consoles, other than to go home.
/:cl:

2022-04-06 05:38 UTC, Colovorat commented
>The crippling changes to free golems have been met as a challenge by some, rather than as a blockade.

You surprised?

2022-04-06 06:18 UTC, githubuser4141 commented
> > The crippling changes to free golems have been met as a challenge by some, rather than as a blockade.
> 
> You surprised?

Well yeah, it's shocking but people who play golem are still playing a multiplayer 'role playing' game and a good chunk likely desire interaction with other people. So, yaknow, they probably don't like being stranded in the middle of nowhere because there's no interaction with anyone or anything. Wow.

2022-04-06 06:22 UTC, OperativeLyn commented
> > > The crippling changes to free golems have been met as a challenge by some, rather than as a blockade.
> > 
> > You surprised?
> 
> Well yeah, it's shocking but people who play golem are still playing a multiplayer 'role playing' game and a good chunk likely desire interaction with other people. So, yaknow, they probably don't like being stranded in the middle of nowhere because there's no interaction with anyone or anything. Wow.

The point of free golems **is** being stranded in the middle of nowhere with your fellow golems. If you actively seek the station as one you're doing it wrong and you're fail RPing.

2022-04-06 07:39 UTC, Mothblocks commented
Not interested in any free golem talk here as "free golems shouldn't be on station" is a policy issue that has been +1'd by this head admin term, the codebase is not where you change the mind of that.

2022-04-06 08:00 UTC, ZephyrTFA commented
@Mothblocks would having it so hazard area makes it also impossible to use machines outside your allowed area be a better change?

2022-04-06 08:14 UTC, Mothblocks commented
@ZephyrTFA Nah, the point of this was so that if they *do* manage to come onto the station somehow, they can get back.

2022-04-06 08:22 UTC, githubuser4141 commented
> > > > The crippling changes to free golems have been met as a challenge by some, rather than as a blockade.
> > > 
> > > 
> > > You surprised?
> > 
> > 
> > Well yeah, it's shocking but people who play golem are still playing a multiplayer 'role playing' game and a good chunk likely desire interaction with other people. So, yaknow, they probably don't like being stranded in the middle of nowhere because there's no interaction with anyone or anything. Wow.
> 
> The point of free golems **is** being stranded in the middle of nowhere with your fellow golems. If you actively seek the station as one you're doing it wrong and you're fail RPing.

Then the flavour text should be changed as it doesn't reflect that at all. Quote: ""In his infinite and divine wisdom, he set your clan free to travel the stars with a single declaration: \"Yeah go do whatever.\"". It literally says I'm free to travel the stars, why wouldn't I be able to walk onto a space station?

2022-04-06 08:33 UTC, Mothblocks commented
If you played free golems on any server other than 127.0.0.1station you would know that the policy text is different on live than it is in the codebase

https://tgstation13.org/parsed-logs/sybil/config/policy.json

> You should seek to build a home for your people upon the rocky soil below you, and should only briefly venture out beyond your homeland to trade or interact with others.

---

> And failRP is not a thing on the LRP servers anyway.

You're an idiot

2022-04-06 08:38 UTC, Mothblocks commented
To be clear when I said I'm not interested in any talk on the policy I meant it and will be completely ignoring any post you make, go to /tg/'s Policy Discussion board if you want to argue in favor of free golems on the station

2022-04-06 09:09 UTC, githubuser4141 commented
> 

Duly noted. I only looked up the brief description for golems on the github so I wasn't aware the player facing description had changed. That being said I don't think I'm an idiot for saying the LRP servers don't have any RP rules. It's nearly impossible to find someone who isn't obviously, blatantly underaged and isn't spouting some silly meme or phrase they heard online or in school.

The server text says 'the admin team is cracking down on memes spoken IC' but I can't recall the last time I saw someone (who wasn't obviously a non-English speaker, mind you) speak an actual coherent sentence. If anyone tries to speak dialogue it's 99% of the time quoted almost exactly from a sci-fi or from some fanfic they found online.

2022-04-06 20:11 UTC, cacogen commented
Artificial limitations like this aren't in the spirit of the game. There are ways to "yes, and..." golem players who want to visit the station while still disincentivising them from doing so if it's actually a problem. 

It's a security issue, all you have to do is alert security over comms when there's someone on an inbound shuttle who isn't part of the crew. 

That and make security aware of the fact they have carte blanche to deal with intruders how they wish. It's not exactly hard to spot a free golem on the station.

2022-04-06 20:32 UTC, ZephyrTFA commented
> To be clear when I said I'm not interested in any talk on the policy I meant it and will be completely ignoring any post you make, go to /tg/'s Policy Discussion board if you want to argue in favor of free golems on the station

@Mothblocks people can't read, consider locking the conversation.

2022-04-06 21:16 UTC, Serxule commented
> The point of free golems **is** being stranded in the middle of nowhere with your fellow golems. If you actively seek the station as one you're doing it wrong and you're fail RPing.

admins he's fail rping admins admins failrp failrp admins admins admins

2022-04-06 21:18 UTC, cacogen commented
>@Mothblocks people can't read, consider locking the conversation.

I'm not going to make a policy thread to comment on a code change.

2022-04-08 10:21 UTC, Kylerace requested changes

2022-04-08 10:21 UTC, Kylerace commented on code/modules/mob_spawn/ghost_roles/golem_roles.dm
> +		allowed_areas = typecacheof(list(/area/icemoon, /area/lavaland, /area/ruin))
you dont need to check for this it will assign the static var to the output of the proc once ever

2022-04-09 05:42 UTC, Kylerace requested changes

2022-04-09 05:42 UTC, Kylerace commented on code/modules/mob_spawn/ghost_roles/golem_roles.dm
> +		allowed_areas = typecacheof(list(/area/icemoon, /area/lavaland, /area/ruin))
```suggestion
	var/static/list/allowed_areas = typecacheof(list(/area/icemoon, /area/lavaland, /area/ruin))
```

2022-04-09 20:03 UTC, merged