[NO GBP] Resolves Golems not being allowed in the areas they created
tgstation/tgstation pull request #66000
Opened 2022-04-06 09:06 UTC by ZephyrTFA

## About The Pull Request

Creates a new signal that fires whenever a new area is created, or expanded, when using the create_area proc.
Also implements this signal in the Hazard Area component to allow new areas that are created to be considered non-hazardous if they meet the criteria for non hazardous areas.

## Why It's Good For The Game

If you build a room we should probably allow you to be in it

## Changelog

:cl:
fix: Golems can now exist in the rooms they themselves create, sorry about that.
/:cl:

2022-04-06 09:08 UTC, Mothblocks requested changes

2022-04-06 09:08 UTC, Mothblocks commented on code/__DEFINES/dcs/signals/signals_area.dm
> +#define COMSIG_AREA_CREATED "mob_created_area"
This needs to be formatted like the other global signals, and put in https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/dcs/signals/signals_global.dm

2022-04-06 09:08 UTC, Mothblocks commented on code/datums/components/hazard_area.dm
> +	area_created.Cut() // Lets not have hanging refs to areas thanks
Just setting it to null is fine.

2022-04-06 09:08 UTC, Mothblocks commented on code/datums/components/hazard_area.dm
> +		area_created -= overwritten // While its not guarenteed to be in the area_created list it's a good idea to ensure we dont have handing refs
```suggestion
		area_created -= overwritten // While its not guaranteed to be in the area_created list it's a good idea to ensure we dont have handing refs
```

2022-04-06 22:39 UTC, ZephyrTFA commented
Need to add survival pods to the area whitelist for golems

2022-04-10 00:58 UTC, merged

2022-04-13 02:19 UTC, Learner10 commented
Thank you.