Adds the Artifact of Kin as a station trait.
tgstation/tgstation pull request #66034
Opened 2022-04-07 05:23 UTC by TemporalOroboros

## About The Pull Request
Adds a station trait that makes dynamic pick a single antagonist for roundstart, latejoin, and midround.

## Why It's Good For The Game
I find the image of the station getting invaded by a steady stream of provocateurs amusing.

## Changelog

:cl:
expansion: Very occasionally a few types of antagonists will be chosen to be the only types of antagonists that shows up that shift.
balance: Very occasionally a few types of antagonists will be chosen to be the only types of antagonists that shows up that shift.
/:cl:

2022-04-07 05:37 UTC, IndieanaJones commented
I really like this.  A lot of station traits don't really do much of anything except offset things at roundstart, but this is the kind of round variation I think the system could really use.

2022-04-07 06:21 UTC, Colovorat commented
Shrine of Order moment

2022-04-07 07:13 UTC, Y0SH1M4S73R commented
> hmm yes which antags will be the only antags that can spawn during this Impending Doom round?
> Roundstart? Hmm... Thief
> Latejoin? How about..... Thief
> Midround? Let's go with......... Thief

On a more serious note, this trait rolling a heretic-centric round would be *very* interesting.

2022-04-07 07:24 UTC, SkeletalElite commented
What happens if the roll is something where 1 roll is hte max allowed like cult, nukies, revs? Will it allow additional rolls of those to occur?

2022-04-07 07:40 UTC, TemporalOroboros commented
> What happens if the roll is something where 1 roll is hte max allowed like cult, nukies, revs? Will it allow additional rolls of those to occur?

Given its current state. Yes.

2022-04-07 07:42 UTC, TemporalOroboros commented
There is a slight issue that will need to be fixed before merge. If the roundstart picker doesn't roll a high impact ruleset it's possible for latejoin or midround to roll one and lock itself out of spending threat. I'll need to figure out a way to prevent that from happening.

2022-04-07 07:44 UTC, TemporalOroboros commented
Basically:
1. Artifact of Kin station trait is enabled.
2. Roundstart picks traitors. All roundstart threat is spent on traitors. Since they are not a high impact ruleset latejoin and midrounds

2022-04-07 07:48 UTC, TemporalOroboros commented
Fat fingered close trying to comment. Ignore that.

2022-04-07 09:42 UTC, TemporalOroboros commented
That should make midrounds and latejoins picking high impact rulesets not lock themselves out.

2022-04-07 10:08 UTC, Mothblocks commented
Labelling DNM until [Dynamic 2022 Part 1](https://github.com/tgstation/tgstation/pull/65997) is merged

2022-04-07 10:11 UTC, Mothblocks requested changes
Does this respect LONE_RULESET?

This needs to be split out into a datum handler or similar that listens to signals so that we don't have all this code in Dynamic.

Also, depending on how this works, this is not going to function well with Dynamic 2022 at all, since Dynamic 2022's first midround is basically always a sleeper agent.

This needs some marker in the `dynamic.json` log output so I know to completely throw these out when analyzing rounds.

2022-04-07 10:11 UTC, Mothblocks commented on code/game/gamemodes/dynamic/dynamic.dm
> +	var/high_impact_ruleset_executed = NONE
You need to change the documentation for this to include that it is a bitfield, and then link to the flags it can use.

2022-04-07 10:11 UTC, Mothblocks commented on code/game/gamemodes/dynamic/dynamic.dm
> +						if (high_impact_ruleset_executed & (HAS_TRAIT(SSstation, STATION_TRAIT_ARTIFACT_OF_KIN) ? ~EXECUTED_LATEJOIN_HIGH_IMPACT_RULESET : ALL))
Combine these into one.

2022-04-07 15:52 UTC, Wallemations commented
Soon we'll get Artifact of Command
Choose Your Own Antag adventure

2022-04-07 16:38 UTC, D4C-420 commented
Artifact of swarms 
Twice the Antags

2022-04-08 07:43 UTC, Fikou commented
can we name it something that makes sense to people who didnt play a video game

2022-04-11 04:03 UTC, TemporalOroboros commented
I'm honestly going to wait on this until Dynamic 2022 is merged. Then I'll see where I can go with it.

2022-04-11 04:08 UTC, Mothblocks commented
Gonna anti-stale this until D2022

2022-04-29 21:15 UTC, Mothblocks commented
Artifact of kin PR is that way #66034

2022-05-02 15:12 UTC, TemporalOroboros commented
> Artifact of kin PR is that way #66034

I don't think this is doing much good here.

2022-05-02 20:51 UTC, Mothblocks commented
God damnit

2022-05-05 08:04 UTC, TheSilverNuke commented
> can we name it something that makes sense to people who didnt play a video game

What game is this even from

2022-05-13 06:02 UTC, Annihilit commented
> God damnit

Well now you hopefully see how i managed to mess it up in the first place lol

2022-05-16 02:13 UTC, private-tristan commented
> What game is this even from


 [Risk of Rain](https://riskofrain.fandom.com/wiki/Kin)

2022-05-19 10:37 UTC, TemporalOroboros commented
Alright. Let's give this another go.

2022-05-19 10:42 UTC, TemporalOroboros commented
Needs mapping and spriting.

2022-05-19 17:19 UTC, TemporalOroboros commented
> > Also, depending on how this works, this is not going to function well with Dynamic 2022 at all, since Dynamic 2022's first midround is basically always a sleeper agent.
> 
> This is still a pretty nasty gotcha I think

Yeah. I've set it to just pick a ruleset for midrounds and then ensure that only that midround can spawn. The result should be less weighted towards sleeper agents than locking in the first picked ruleset. This is still not optimal, since it's possible for it to pick something like nuke ops and then the station has to sit around for the heavy chance to build up high enough for it to roll. Haven't put much thought into how the middle ground would be implemented, but I'm sure there is one.

2022-05-19 17:20 UTC, TemporalOroboros commented
On the other hand. Rolling something expensive and waiting for the director to roll it does line up pretty nicely with the RoR experience.

2022-06-07 03:24 UTC, closed without merging