[NO GBP] Fix girder construction balloon_alert runtimes
tgstation/tgstation pull request #66079
Opened 2022-04-09 02:52 UTC by timothymtorres

## About The Pull Request

Fixes this:

![unknown](https://user-images.githubusercontent.com/5195984/162553746-8dd84531-3d27-4b40-8b3a-e49145a6b036.png)

`balloon_alert` was creating runtimes from missing a user arg.

## Why It's Good For The Game

Bugfixes.

## Changelog

:cl:
fix: Fix girder construction runtimes
/:cl:

2022-04-09 03:28 UTC, Mothblocks requested changes
I'm getting bored of this but I didn't catch these the first time:

1. Just do `balloon_alert`, so it comes from the *object*
2. Remove any balloon alert that already has visual feedback

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +		user.balloon_alert(user, "slicing apart...")
```suggestion
		balloon_alert(user, "slicing apart...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +			user.balloon_alert(user, "sliced apart")
```suggestion
```

Don't need this at all since you already have the visual feedback.

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +			user.balloon_alert(user, "wall already present!")
```suggestion
			balloon_alert(user, "wall already present!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +			user.balloon_alert(user, "need floor!")
```suggestion
			balloon_alert(user, "need floor!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "need tram floors!")
```suggestion
				balloon_alert(user, "need tram floors!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] rods!")
```suggestion
					balloon_alert(user, "need [amount] rods!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "concealing entrance...")
```suggestion
				balloon_alert(user, "concealing entrance...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "entrance concealed")
```suggestion
```

There's already visual feedback

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] rods!")
```suggestion
					balloon_alert(user, "need [amount] rods!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "adding plating...")
```suggestion
				balloon_alert(user, "adding plating...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "plating added")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] sheets!")
```suggestion
					balloon_alert(user, "need [amount] sheets!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "concealing entrance...")
```suggestion
				balloon_alert(user, "concealing entrance...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "entrance concealed")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "need plasteel sheet!")
```suggestion
				balloon_alert(user, "need plasteel sheet!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] sheets!")
```suggestion
					balloon_alert(user, "need [amount] sheets!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "adding plating...")
```suggestion
				balloon_alert(user, "adding plating...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "plating added")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] sheets!")
```suggestion
					balloon_alert(user, "need [amount] sheets!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "adding plating...")
```suggestion
				balloon_alert(user, "adding plating...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "plating added")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "need [amount] sheets!")
```suggestion
					balloon_alert(user, "need [amount] sheets!")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "concealing entrance...")
```suggestion
				balloon_alert(user, "concealing entrance...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "entrance concealed")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "adding plating...")
```suggestion
				balloon_alert(user, "adding plating...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "plating added")
```suggestion
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +				user.balloon_alert(user, "reinforcing frame...")
```suggestion
				balloon_alert(user, "reinforcing frame...")
```

2022-04-09 03:28 UTC, Mothblocks commented on code/game/objects/structures/girders.dm
> +					user.balloon_alert(user, "frame reinforced")
```suggestion
```

2022-04-10 02:45 UTC, Mothblocks commented
make sure u get to the ones i didnt comment i jsut got tired

2022-04-10 03:19 UTC, timothymtorres commented
I'm aware.  Just waiting until tmrw to knock them out.

2022-04-11 03:39 UTC, Mothblocks commented
thx

2022-04-11 03:39 UTC, merged