Helium now makes your speech small!
tgstation/tgstation pull request #66165
Opened 2022-04-13 09:28 UTC by SnoopCooper

## About The Pull Request
Breathing helium now makes your voice appear small in the chat.
![helium_text](https://user-images.githubusercontent.com/5685102/163145546-1cd58ca8-b028-4a4e-90c5-eb1685301bbc.PNG)

## Why It's Good For The Game
Adds a funny interaction to helium.

## Changelog

:cl:
expansion: Gives helium a minor funny interaction
/:cl:

2022-04-17 05:14 UTC, ShizCalev commented
does #66156 affect this

2022-04-22 00:10 UTC, Kylerace requested changes

2022-04-22 00:10 UTC, Kylerace commented on code/modules/surgery/organs/lungs.dm
> +		breath_gases[/datum/gas/helium][MOLES]-=gas_breathed
```suggestion
		breath_gases[/datum/gas/helium][MOLES] -= gas_breathed
```

2022-04-28 19:08 UTC, Ghilker commented
Great pr, but you added the Bz reaction rework in this one

2022-04-28 19:08 UTC, SnoopCooper commented
> Great pr, but you added the Bz reaction rework in this one

I know, trying to fix

2022-04-28 19:38 UTC, SnoopCooper commented
I just made a big mess. Gonna redo this PR.

2022-04-28 19:38 UTC, closed without merging