Allow canisters, portable pumps and portable scrubbers to have their gas content react even if connected to a port
tgstation/tgstation pull request #66207
Opened 2022-04-15 12:26 UTC by Ghilker

## About The Pull Request
See title

## Why It's Good For The Game
Having portable atmos machines not having their content react has always felt weird and inconsistent, especially for newer players that don't understand why the canister don't react while the pipes its connected to keep on going.

## Changelog

:cl:
balance:Allow canisters, portable pumps and portable scrubbers to have their gas content react even if connected to a port
/:cl:

2022-04-15 12:47 UTC, Ghilker commented
prevents this 
![image](https://user-images.githubusercontent.com/42839747/163572464-ddaab201-eb83-41a8-83b1-eb2f7cb236c8.png)
![image](https://user-images.githubusercontent.com/42839747/163572490-1efa0a7b-a0d8-471f-bfd9-c099f5c029c7.png)

2022-04-15 14:59 UTC, RandomGamer123 commented
I think this behavior is quite useful actually, back in the can fusion days, it provided a way to easily stop the fusion reaction, and I would say it's still useful nowadays as you can stop reactions before they make your canister blow up, or be able to fix mistakes more easily (eg. stopping the reaction if you accidentally cool down a finished freon reaction canister with bz still in it too much and you start turning the freon into healium). Despite its inconsistency, it's more forgiving to be able to turn on and off a reaction by simply wrenching the canister to a port.

2022-04-15 16:12 UTC, Pickle-Coding commented
Canisters not reacting when connected is not very intuitive, and it's funny when shit blows up.

2022-04-18 07:15 UTC, LemonInTheDark requested changes
I'm mildly concerned about people using portable atmos to farm react calls, but I guess they really could be considered a second pipenet in that sense, since there's a connector between them and the main mix.

I don't think intentionally stalling reactions is a good enough bit of reasoning for this, it's really unintuitive, shouldn't be a feature.

2022-04-18 07:15 UTC, LemonInTheDark commented on code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
> -	SSair.start_processing_machine(src)
The fuck, why are you removing the event based processing from this?

2022-04-18 07:57 UTC, Ghilker commented
Oh wait I should have closed this, wasn't interested in this anymore, sorry about that

2022-04-18 07:57 UTC, closed without merging

2022-04-18 20:29 UTC, LemonInTheDark commented
what changed?

2022-04-18 20:32 UTC, Ghilker commented
> what changed?

The current canister update is basically overlapping this one because process atmos keep on going but only for canisters. Tho I might change it