Fixes mulligan not randomizing ethereal color
tgstation/tgstation pull request #66229
Opened 2022-04-16 15:41 UTC by wesoda25

## About The Pull Request

Judging from code this is a fix, although I initially thought it would be a feature. It tried to update color but there was nothing in ethereal code to make that do anything. Now it does.

Moth wings also do not update. I tried to figure it out but species code makes me want to hit my head against a wall so I gave up on that.

## Why It's Good For The Game

bug bad

## Changelog

:cl:
fix: Mulligan now properly randomizes ethereal color
/:cl:

2022-04-16 15:42 UTC, wesoda25 commented on code/modules/mob/living/carbon/human/species_types/ethereal.dm
> +		var/new_color = H.dna.features["ethcolor"] //can I just replace the default color here?
Leaving a draft due to this. Can I just set the default to equal the new color, or should I keep this as is (or do it a different way?)

2022-05-01 21:28 UTC, wesoda25 commented on code/modules/mob/living/carbon/human/species_types/ethereal.dm
> +		var/new_color = H.dna.features["ethcolor"] //can I just replace the default color here?
This was discussed on discord. Default color isn't actually used anywhere, so the way I did it is good.

2022-05-05 01:51 UTC, wesoda25 commented
fuckin FUCK

2022-05-05 01:59 UTC, wesoda25 commented
Removed default_color as @optimumtact requested, since it wasn't used anywhere, except with a slight change - I made it a unique ethereal var since ethereals _do_ use it and I didn't see a better available substitute.

This PR should be ready.

2022-05-08 18:06 UTC, tralezab requested changes
just housekeeping

2022-05-08 18:06 UTC, tralezab commented on code/modules/admin/create_mob.dm
> +	H.dna.species.spec_updatehealth(H)
can you switch `H` to a better var name since you used it? thanks

2022-05-08 18:06 UTC, tralezab commented on code/modules/mob/living/carbon/human/species_types/ethereal.dm
> +		var/new_color = H.dna.features["ethcolor"]
same situation here. use the bad var name, improve it while you're there

2022-05-10 01:38 UTC, merged

2022-05-10 01:39 UTC, GolfinhoVoador commented
true