falling on punji sticks now impales you
tgstation/tgstation pull request #66263
Opened 2022-04-17 20:33 UTC by Fikou

## About The Pull Request

Falling on punji sticks from multi-z impales you on them, doing a lot of damage, you need a few seconds to remove yourself from it.

## Why It's Good For The Game

![image](https://media0.giphy.com/media/NkFQ8T5EizNqE/giphy.gif)

## Changelog

:cl:
expansion: Falling on punji sticks impales you.
/:cl:

2022-04-17 21:10 UTC, MrMelbert requested changes

2022-04-17 21:10 UTC, MrMelbert commented on code/modules/hydroponics/grown/towercap.dm
> +	to_chat(buckled_mob, span_warning("You begin climbing out of [src].</span>"))
```suggestion
	to_chat(buckled_mob, span_warning("You begin climbing out of [src]."))
```

2022-04-17 21:10 UTC, MrMelbert commented on code/modules/hydroponics/grown/towercap.dm
> +		to_chat(buckled_mob, span_userdanger("You fail to detach yourself from [src]."))
Early return the doafter?

2022-04-17 21:10 UTC, MrMelbert commented on code/modules/hydroponics/grown/towercap.dm
> +	var/mutable_appearance/stab_overlay
Auto-doc

2022-04-17 22:58 UTC, datorangebottle commented
finally, i can fill tram underpass with punji sticks and deliberately hit people with the tram so that they fucking die.

2022-04-18 02:39 UTC, MrMelbert approved these changes

2022-04-18 22:48 UTC, merged