Blind people can no longer read newspapers and id cards
tgstation/tgstation pull request #66291
Opened 2022-04-18 09:00 UTC by timothymtorres

## About The Pull Request

This was split off of https://github.com/tgstation/tgstation/pull/65668 into its own separate PR.

This removes inconsistencies with blind mobs and objects that require reading.

## Why It's Good For The Game

Being blind is a severe disability that should be very difficult to play with. There is a reason it's -16 points in the quirk menu.

## Changelog

:cl:
balance: Blind people can no longer read newspapers or ids
/:cl:

2022-04-18 13:42 UTC, Zytolg commented
Newspapers? That's reasonable.
ID's? Add Braille. Those should be readable to some degree by the blind given how important they are. 
I've gone over your other blind PR's explaining more in depth the reasons for this, but to summarize here, if something is important towards the aspect of performing a job (and I would consider ID cards to fit into that category), then it shouldn't be left completely inaccessible to the person performing that job. Changes that make jobs less fun without necessarily adding anything unique to the aspect being changed aren't always necessarily good changes.

2022-04-18 14:05 UTC, RandomGamer123 commented
> Newspapers? That's reasonable. ID's? Add Braille. Those should be readable to some degree by the blind given how important they are. I've gone over your other blind PR's explaining more in depth the reasons for this, but to summarize here, if something is important towards the aspect of performing a job (and I would consider ID cards to fit into that category), then it shouldn't be left completely inaccessible to the person performing that job. Changes that make jobs less fun without necessarily adding anything unique to the aspect being changed aren't always necessarily good changes.

I would say ID cards aren't critical, since the examine functionality here only tells you a bit more information (eg. age, credits left) that isn't critical, even the HOP since they can use their computer (provided #66285 isn't merged) to view access-related information, with one exception: 
Some of these examine texts are instructions (eg. "Alt-Click the ID to pull money from the linked account in the form of holochips.") and those should be kept to prevent cases where people (especially new players) get temporarily blinded and end up missing out on important instructions. So these instructions should be added back in a way (eg. braille as described above).

2022-04-18 20:26 UTC, MrMelbert requested changes
Newspapers is fine

I specifically allowed blind people to examine things in #52727 because we keep a lot of meta-information, such as keybindings*, in examine messages, so you shouldn't remove that in any case. 

\* Note that contextual screentips can help with this, but it's still a very pointless change regardless

Reduce this PR to just newspapers and it's fine, i'll even remove the balance tag if you do so

2022-04-18 22:07 UTC, closed without merging

2022-04-18 22:13 UTC, timothymtorres commented
Updated "Why It's Good For The Game" section.

2022-04-18 22:42 UTC, optimumtact commented
cool but I dont' care

2022-04-19 01:45 UTC, timothymtorres commented
It wasn't directed at you.  It was for the several people saying it needed a "Why It's Good For The Game" section.  

I wasn't spamming these PRs on my own violation either.  I specifically asked Melbert if it was okay to group the blindness PRs together and he told me to split them all apart.  The other PRs I was asked by Kyler to separate as well.  

I spent +3 months working on the DLC and now I'm trying to salvage whatever makes the cut.

2022-04-19 03:16 UTC, optimumtact commented
next time just ignore mrmelbert and you wont' fall afoul of the voters