Makes the blood filter not suck so much
tgstation/tgstation pull request #66325
Opened 2022-04-19 16:42 UTC by GoblinBackwards

## About The Pull Request
Adds a whitelist to the blood filter, you can use it in hand to bring up a UI similar to the plumbing filters. When using the blood filter for surgery it will only filter out chems in the whitelist, unless the list is empty in which case it will filter all chems.

Makes the surgery loop when completed unless the patient has no chems in them, similar to tend wounds.

Holding a health analyzer in your off hand while using the blood filter will display a chem scan of the subject after each surgery step similar to tend wounds.

## Why It's Good For The Game
In its current state the blood filter is just awful to use. It does nothing unique, is flat out worse at its job that most purging chems, you have to click the patient after every use even though it usually takes a lot of steps to actually filter out all the chems from someone, and you can't even see how much more you have to filter without pausing the surgery to swap to a health analyzer to chem scan separately.

## Changelog

:cl:
add: Added a whitelist to blood filters, unless the list is empty they will only remove chems in this whitelist. You can edit the list by using the filter in your hand
qol: Blood filter surgery now automatically does a chem scan after each step if you're holding a health analyzer.
qol: Blood filter surgery now automatically loops if the patient has any chems in them
/:cl:

2022-04-19 16:46 UTC, stylemistake approved these changes

2022-04-23 01:57 UTC, MrMelbert requested changes

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +/datum/surgery_step/filter_blood/proc/has_whitelisted_chems(mob/living/carbon/target, obj/item/blood_filter/bf)
Auto doc this proc

Also, better variable name than "`bf`".

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +	if(!target.reagents?.reagent_list.len)
```suggestion
	if(!length(target.reagents?.reagent_list))
```

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +	if(!bf.whitelist_ids.len)
```suggestion
	if(!length(bf.whitelist_ids))
```

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +	for(var/datum/reagent/chem in target.reagents.reagent_list)
```suggestion
	for(var/datum/reagent/chem as anything in target.reagents.reagent_list)
```

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +	var/obj/item/blood_filter/bf = tool
Better variable name.

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/tools.dm
> +	var/list/whitelist_english = list()
These need auto-doc comments as well.

2022-04-23 01:57 UTC, MrMelbert commented on code/modules/surgery/blood_filter.dm
> +			if(!bf.whitelist_ids.len || bf.whitelist_ids.Find(chem.type))
```suggestion
			if(!length(bf.whitelist_ids) || chem.type in bf.whitelist_ids)
```

2022-04-23 21:35 UTC, merged