[WIP] Excising the fat: Splicing areas.dmi into multiple files, also some minor repathing
tgstation/tgstation pull request #66406
Opened 2022-04-21 23:07 UTC by Jolly-66

## About The Pull Request
Areas.dmi right now houses *all* of our mapped turfs icons (which is roughly 400 icons). Not an issue, but it's *incredibly* large and clunky to navigate right now. This isn't an issue for the average coder and/or player code diving, but it is for mappers wanting to add new turfs. Currently, the file has *some* organization, but its still an overall mess. This PR aims to slice the behemoth with multiple .dmi files corresponding to specific areas, such as the following:
- Station related areas
- Cent Comm-Z related turfs (wiz ship, syndie base, ect)
- Ruins for space and Lavaland*
- Away missions/gateways 
- Misc
*Lavaland may not be its own file, instead, I may opt to just condense space ruins into one file.

I also plan to repath `/area/*` -> `/area/station/*` for **station turf** only. This is to clean it up, as most other turfs follow this format (that being `/area/turf_zone/*`). 

I'm also writing an update paths file as I go along.

Jollys shit to test because it will break

- [ ] Convert *all* station turfs to `/area/station/*`
- [ ] Finish the update paths txt file
- [ ] Ensure type paths are updated correctly for Stations
- [ ] Ensure icons for "Less" important maps are there (Shuttles, ruins, ect)
- [ ] Ensure icons for Station maps are there
- [ ] Add unused/delete turf icons to the archive depot, if the spritetainers so desire

## Why It's Good For The Game
None of this player facing, but the bugs arising from it may be. Consistency, ease of access for mappers and coders alike is much appreciated. I don't know what to put for the CL explicitly, so yell at me about that.

## Changelog

:cl: Jolly
code: The typepath used for station turfs has been changed from /area/* to /area/station/* for clarity and consistency. 
/:cl:

2022-04-24 20:43 UTC, Fikou commented on code/modules/awaymissions/cordon.dm
> +	icon = 'icons/turf/areas/areas_station.dmi'
cordons arent for the station

2022-04-24 20:44 UTC, Fikou requested changes
areas being in the turf folder made sense when it was just 1 file. theres a bunch now so i think it should just be a new subfolder in icons

2022-04-24 20:53 UTC, Jolly-66 commented
> areas being in the turf folder made sense when it was just 1 file. theres a bunch now so i think it should just be a new subfolder in icons

Are you suggesting that instead of what it is now (/icons/areas/turf/)
It should probably be like `/icons/turf`?

2022-04-26 22:48 UTC, Jolly-66 commented
For the most part, everything is fine.
Ruins turf used those old random colored turf icons, its not an inherent issue now (unless we really want something that isn't a checkerboard), I'm saying this PR is ready to go.

2022-04-26 22:51 UTC, Jolly-66 commented
Fucking maps augh

2022-05-04 02:26 UTC, Jolly-66 commented
Icebox is breaking this PR I have 0 fucking idea whats going on

The codes fine here
The codes fine on my local
The map is fine in the map editor

2022-05-04 22:32 UTC, Imaginos16 approved these changes
I have no idea why a spritetainer needs to give approval on a mass rework of area sprites which are things that don't touch visual aesthetics of the game, but here it goes.

By god you're absolutely deranged for pulling this off.

2022-05-04 22:36 UTC, Fikou commented
> > areas being in the turf folder made sense when it was just 1 file. theres a bunch now so i think it should just be a new subfolder in icons
> 
> Are you suggesting that instead of what it is now `/icons/areas/turf/` It should probably be like `/icons/turf`?

yes

2022-05-05 01:28 UTC, Kapu1178 requested changes

2022-05-05 01:28 UTC, Kapu1178 commented on code/modules/surgery/bodyparts/_bodyparts.dm
> -	var/plaintext_zone
?????????????

2022-05-05 01:35 UTC, san7890 commented on code/modules/surgery/bodyparts/_bodyparts.dm
> -	var/plaintext_zone
we're having some conflict problems

2022-05-05 01:36 UTC, Jolly-66 commented
This is a goddamn nightmare

2022-05-05 01:37 UTC, Jolly-66 commented
Ok you know what I'll just fucking redo this when I'm done my finals

2022-05-05 01:37 UTC, closed without merging