Remaps meta's ordnance take two
tgstation/tgstation pull request #66454
Opened 2022-04-23 17:13 UTC by vincentiusvin

## About The Pull Request
<details>
<summary>
Click me!
</summary>
<img src="https://user-images.githubusercontent.com/54709710/164916459-f0bddd89-b204-46be-8403-d7c9f1db5136.png"/>
</details>

Redo of https://github.com/tgstation/tgstation/pull/65807 but by sticking closer to the old layout. Some folks were very fond of parts of the old meta sci & scimaint that i had to do away with if i were to continue with the layout in the linked PR. So i did less changes overall except for the chamber room, ordnance office and maint rerouting.

Oh and rearranged disposals a bit to be nicer.

I honestly prefer my old layout more than this one, since there are distinct feels from different maps, with meta being the most "linear" of all the others and icebox being the most open. But I'm content with this.

Yes this one is very similar to the delta one.

## Why It's Good For The Game
Adds a freeze chamber, adding oxygen to the chamber is more obvious, nicer loop, computers, etc.

## Changelog
:cl:
expansion: Remapped meta's ordnance.
/:cl:

2022-04-24 01:41 UTC, Zytolg commented
Hey, thanks for playing around with my suggestions. There are many changes, but this iteration still manages to preserve the identity what I set out to accomplish back in the winter of 2020. The layout is strong and I have no qualms, so I'll move into the minor things that'll help this PR pass. 

Starting in the top left, there are a few things to note. You don't need the plasma glass here. I don't foresee players messing around with high temperatures in this room and even in the rare even that a fire does break out, the Heavy Firelocks will do the job of these windows just fine. I'd replace them with Reinforced Glass. 
Moving immediately south, I see an empty room. I am going to assume that this space might be intended as a blank workspace, given that this is where your primary burn chamber is. I'd try to fill that space with something that plays into what you want people to be doing in this room. I know the chemfactory does this, and meta atmos does it too, but I'm currently on changing the latter, and some maintainers have strong feelings about the former- which is to say that it's not good justification for it. 

Now moving to the right; actually this looks perfect. The usage of space here is on point, and everything seems like its placed right. The room might benefit from some aesthetic wall mounts, but I'll leave those to your creativity. 

I love the maint. You did a fantastic job iterating on it, and I believe that our players will have even more fun with this design than they did the last. Great work.

2022-04-24 03:07 UTC, vincentiusvin commented
A bunch of them applied. Thanks for your time.

2022-04-26 22:28 UTC, vincentiusvin commented
Cant find anything nice to put in the middle, ill just leave it like this it doesnt look that bad.

2022-05-06 05:46 UTC, san7890 requested changes
<details>
<summary>Click For Review Images</summary>

![image](https://user-images.githubusercontent.com/34697715/167071233-972e54c5-ce2b-42a7-8b2e-e9a1120092f4.png)

This should all be maintenance rather than Ordnance Hall... preferably Lesser Aft Maintenance.

![image](https://user-images.githubusercontent.com/34697715/167071429-47e9d46d-92c2-44ca-92be-84e5fb465d30.png)

Should these three blast doors have space underneath, or should they be vacuum flooring? Not sure.

![image](https://user-images.githubusercontent.com/34697715/167071674-4398a983-650c-4781-9ef8-fc43b09ff048.png)

This room could use an intercom.

![image](https://user-images.githubusercontent.com/34697715/167071749-7771049a-f7f1-4705-9937-e313d9e7def4.png)

In the other PRs, this would typically have a glass window+windoor barrier which is absent here Is this intentional? Would probably benefit from having that put in for dealing with the airless chamber.

![image](https://user-images.githubusercontent.com/34697715/167071814-69c3135e-98f9-4ffd-83d1-9435dbf0250b.png)

Not sure why this screen is here, just delete it/place it elsewhere.

![image](https://user-images.githubusercontent.com/34697715/167072019-5d02e3a0-4a83-48f1-8e1a-523ea9db0d4b.png)

Rather silly to have a button be "blocked" should the firelocks close, put it elsewhere? Also, that room portion to the right (east) of the firelock gating does not have a fire alarm. Might be worth getting rid of one of these two caution signs:

![image](https://user-images.githubusercontent.com/34697715/167072141-f3fddd15-80ad-4ef5-9c04-2baf8702fd37.png)

...to allow wall space for that.

![image](https://user-images.githubusercontent.com/34697715/167072203-6c9dafca-2ec4-4462-b689-fea34e972afb.png)

This room lacks an air alarm.

![image](https://user-images.githubusercontent.com/34697715/167072225-8e450730-dbaa-469a-a0b2-8863457dba8a.png)

Weird break in decalling.

![image](https://user-images.githubusercontent.com/34697715/167072287-abd771d0-72b4-4c37-b3a2-69f98ba933ce.png)

Move the requests console down a tile since that looks ugly to ghosts/the AI/me.

![image](https://user-images.githubusercontent.com/34697715/167072401-cdfe5ab2-f7da-4a67-89b5-cba597e3cf34.png)

This room lacks a camera.

![image](https://user-images.githubusercontent.com/34697715/167072755-fbf2692a-50c7-488d-a66e-46330a81be8f.png)

This area is pretty abnormally dark, put a lightbulb in?

![image](https://user-images.githubusercontent.com/34697715/167073879-b4c72c7a-1626-4630-ab30-b97899701cc9.png)

Also, I forgot to update my local version, so I'm happy to see you put in the access helpers. Doesn't this chamber need those, though?
</details>

Also, throw in some generic event spawners in as well as some scientist spawners here-and-there. You also used the "any" access helpers for doors that only required one access... please use the "all" access helpers for those doors since that'll help us in later audits of stuff. They don't functionally matter beyond that for doors that you only need one type of access for.

Also, one thing you probably missed out on, we're incorporating "unrestricted" mapping helpers on airlocks so that people can easily/readily escape maintenance. Just use `/obj/effect/mapping_helpers/airlock/unres` to have a "flow" into the central primary hallway. Feel free to ask if you're confused on this.

Overall, good work on an interesting design. I think you've had enough time to field feedback from other people about this, so let me know when you've addressed all of the points here.

2022-05-06 06:54 UTC, san7890 commented
![funny-old-man](https://user-images.githubusercontent.com/34697715/167081970-22aa6f24-e570-489d-acaa-1c0fc6dfeede.gif)

2022-05-06 06:55 UTC, merged