Burdened and Honorbound are now traumas, not mutations.
tgstation/tgstation pull request #66471
Opened 2022-04-24 04:01 UTC by tralezab

## About The Pull Request

It was a terrible idea to make them mutations. You'll notice minute differences, maybe a different background on the honorbound declaration of guilt, but the biggest one is this:

## Why It's Good For The Game: PLASMAMEN CAN BE BURDENED AND HONORBOUND

Yep, that's right, because they didn't have genes they were not allowed to be these things. And all for entirely code reasons! Stupid stupid stupid.

## Changelog

:cl:
expansion: Burdened and Honorbound can now be chosen by plasmamen. Sorry boys!
/:cl:

2022-04-24 08:55 UTC, ATH1909 commented
okay but won't plasmamen still be unable to get any of the positive or negative mutations from the burdened sect?

2022-04-26 19:17 UTC, tralezab commented
> okay but won't plasmamen still be unable to get any of the positive or negative mutations from the burdened sect?

true, but better than nothing.

2022-05-04 05:47 UTC, MrMelbert requested changes

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/burdened/burdened_trauma.dm
> +		qdel(src)
```suggestion
	var/datum/dna/dna = owner?.dna
	if(!dna)
		qdel(src)
		return
```
Should probably quit out on the proc if you're qdeling yourself

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/burdened/burdened_trauma.dm
> +	..()
```suggestion
	return ..()
```

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/burdened/burdened_trauma.dm
> +	..()
```suggestion
	. = ..()
```

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/burdened/burdened_trauma.dm
> +	lose_text = "<span class='warning'>You no longer feel the need to burden yourself!</span>"
i think span macros work in this if you care, i don't really (up to you)

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/honorbound/honorbound.dm
> +	"Sinners must be silenced ...",)
```suggestion
	ritual_invocations = list(
		"A good, honorable crusade against evil is required.",
		"We need the righteous ...",
		"... the unflinching ...",
		"... and the just.",
		"Sinners must be silenced ...",
	)
```

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/honorbound/honorbound_trauma.dm
> +	lose_text = "<span class='warning'>You feel unshackled from your code of honor!</span>"
same here re: macros

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/honorbound/honorbound_trauma.dm
> +	//spell
Nice comment

2022-05-04 05:47 UTC, MrMelbert commented on code/modules/religion/honorbound/honorbound_trauma.dm
> +	var/obj/effect/proc_holder/spell/pointed/declare_evil/declare = /obj/effect/proc_holder/spell/pointed/declare_evil
Why do you even hold this reference? cause you don't handle the reference in `on_loss` or `destroy`
It doesn't seem necessary at all

2022-05-05 19:42 UTC, tralezab commented on code/modules/religion/honorbound/honorbound_trauma.dm
> +	//spell
spell

2022-05-09 06:18 UTC, Coastfront commented
Finally, plasmamen oppresion from gods has ended. Now plasmamen get rewarded for all their mutilation by having their god do absolutely fucking nothing for them, instead of just not letting them in the gates at all.

2022-05-24 00:20 UTC, closed without merging