Separates robot_items.dm and cleans up the code
tgstation/tgstation pull request #66519
Opened 2022-04-25 19:56 UTC by SuperNovaa41

I want to do a refactor for an item here, but I'd rather split all of
this up first, so as not to have a boat load of changes to review all
together. as well this is all five year old code and frankly kinda sucks

WHY ITS GOOD

good code, cleans up some ancient messes, documents a lot of old variables and procs

:cl:
code: yeah
/:cl:

2022-04-25 19:58 UTC, SuperNovaa41 commented
Probably going to do some more work on the code but i've got things to do, and figured i'd put it up for review

2022-04-26 04:51 UTC, ATH1909 commented
> fix: Fixes an issue with service borg apparatuses getting multiple beakers in it's contents.

could you elaborate on this?

2022-04-26 04:54 UTC, SuperNovaa41 commented
> > fix: Fixes an issue with service borg apparatuses getting multiple beakers in it's contents.
> 
> could you elaborate on this?

the borg beaker apparatus creates a beaker on init, and then sets `stored` to equal that.
the service borg has a subtype of that which creates a glass and sets it to `stored`, however the other beaker is still stored in its contents (its just inaccessible)

2022-05-02 04:07 UTC, MrMelbert requested changes
double check your var names I only saw these but there may be more

2022-05-02 04:07 UTC, MrMelbert commented on code/game/objects/items/robot/items/food.dm
> +			return FALSE
`turf` is no more descriptive var name than `t`, same with `atom` and `obj`

2022-05-02 04:07 UTC, MrMelbert commented on code/game/objects/items/robot/items/food.dm
> +		into_hands = mob.put_in_hands(food_item)
Same here

2022-05-02 04:07 UTC, MrMelbert commented on code/game/objects/items/robot/items/generic.dm
> +		var/mob/living/carbon/human/human = mob
Same here

2022-05-02 20:09 UTC, merged