Titanium and plastitanium shards and weapons + missing textures.
tgstation/tgstation pull request #66544
Opened 2022-04-26 22:55 UTC by Comxy

## About The Pull Request

## Why It's Good For The Game
Ever been bothered by why titanium glass and plastitanium glass do not drop their own shard types? Well this is the perfect PR for you! Titanium and plastitanium glass shards never existed, and it is probably because the person who made glass way back in the day didn't have time to add these shards. Luckily I decided to add them after all this time. Every piece of code created has been carefully considered and copied form other code, so then you know it is good code.
![promo1](https://user-images.githubusercontent.com/25363960/165405164-c2de794c-c70a-41aa-b9d0-26ad58c3bfa7.PNG)
![promo2](https://user-images.githubusercontent.com/25363960/165405171-1c9b210c-99e3-4ad5-927a-5cf5338aff4c.PNG)

## Changelog
- Adds titanium glass shards
- Adds plastitanium glass shards
- Adds plasma glass shiv
- Adds titanium glass shiv
- Adds plastitanium glass shiv
- Adds titanium glass spear
- Adds plastitanium glass spear
- Adds time for the creation of shards in stronger glass types

:cl:
add: Added titanium and plastitanium glass shards as well as spears and shivs for their types, including plasma glass shivs.
imageadd: Sprites for plasma, titanium and plastitanium glass shards when hold in hand.
/:cl:

2022-04-26 23:24 UTC, TemporalOroboros commented
As someone who's static is digi I am in pain, but I approve nonetheless.

2022-04-26 23:34 UTC, tralezab requested changes
Codewise, some things need to be cleaned up

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			user.put_in_hands(S)
you copy paste this entire thing three times, just make it part of `/obj/item/shard`. Keep it DRY! Don't Repeat Yourself!

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +/obj/item/shard/plasma/attackby(obj/item/I, mob/user, params)
a better variable name than `I`, please

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +		var/obj/item/stack/sheet/cloth/C = I
a better variable name than `C`, please

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			var/obj/item/knife/shiv/plasma/S = new /obj/item/knife/shiv/plasma
a better variable name than `S`, please

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +/obj/item/shard/titanium/attackby(obj/item/I, mob/user, params)
these have the same issues but you'll just move this into `/obj/item/shard` behavior anyway

2022-04-26 23:34 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +/obj/item/shard/plastitanium/attackby(obj/item/I, mob/user, params)
these have the same issues but you'll just move this into `/obj/item/shard` behavior anyway

2022-04-26 23:35 UTC, tralezab commented
On the balance side of things I worry a little bit about reintroducing "spears breaking doors" meta with the plasmashard spear breaking doors when thrown but maybe it's annoying enough to get that it's fine. I dunno if anyone here has tried to break a plasmaglass window but it fuckin blooooows

2022-04-27 01:09 UTC, itseasytosee commented
Ungodly

2022-04-27 09:39 UTC, TheBonded commented
are titanium spears having 1 higher throwforce than plasma spears (but 1 lower force) intended?

2022-04-27 10:42 UTC, thgvr commented
tralezab, we already have spears that can break airlocks. Bamboo spears have 22 throwforce, same as these new ones

2022-04-27 13:26 UTC, Comxy commented
I changed some things. I made sure titanium glass spears cannot break doors, and increased some other stats to make it different. Also, you cannot get plastitanium shards anymore by crafting with sheets, since it is too hard to break. Now you can get is by breaking a plastitanium window instead, so it is harder to get. Also I fixed the code up.

2022-04-27 17:04 UTC, bruhlookatthisdood commented
i have never seen a "large shard"

2022-04-27 17:19 UTC, VladinXXV reviewed
this pr is swag

2022-04-27 17:19 UTC, VladinXXV commented on code/game/objects/items/knives.dm
> +	force = 8
Isn't it redundant to have `force = 8` here? It inherits the exact same damage from the base shiv, no? Same stuff for the following in all three of them:
`icon = 'icons/obj/shards.dmi'`
`lefthand_file = 'icons/mob/inhands/weapons/swords_lefthand.dmi'`
`righthand_file = 'icons/mob/inhands/weapons/swords_righthand.dmi'`

2022-04-27 19:44 UTC, TheBonded commented
> i have never seen a "large shard"

they dont have any actual differences other than their sprite as far as i know, youve probably seen one and just didnt pay attention since its still just called "Glass Shard" in game

2022-04-28 19:50 UTC, Comxy commented
It should be ready to get merged, the code is fine now, the balancing is very good, feel free to merge it any day.

2022-04-28 20:08 UTC, TheBonded commented
> It should be ready to get merged, the code is fine now, the balancing is very good, feel free to merge it any day.

![image](https://user-images.githubusercontent.com/58570888/165836584-7e590aa7-726d-4f64-87af-e2451ae53ca0.png)
## when your pr is ready to be re-reviewed and merged:

in the top of the pr, where it shows reviewers, be sure to press the little circle to re-request a review from anyone who requested changes when you are ready for the pr to be checked and merged again.

## that way you dont end up with ugly red circles on your PR like this!
![image](https://user-images.githubusercontent.com/58570888/165836836-cad3c8cc-f83b-4cf9-87ea-0b618321441a.png)

2022-04-28 20:09 UTC, TheBonded commented
(this is obviously not required for your pr to be merged but it does look nice and notify the people who reviewed that you requested them to come back and review the pr again)

2022-05-02 16:57 UTC, TheBonded commented
resolves https://github.com/tgstation/tgstation/issues/66658

2022-05-03 01:35 UTC, bruhlookatthisdood commented
(why is the plasma shards slightly darker than the plasma shiv)

2022-05-03 18:51 UTC, Comxy commented
> (why is the plasma shards slightly darker than the plasma shiv)

That is probably shading and there are more cracks in the shiv one.

2022-05-05 04:20 UTC, ATH1909 commented on code/game/objects/items/knives.dm
> +	desc = "A makeshift titanium infused glass shiv."
```suggestion
	desc = "A makeshift titanium-infused glass shiv."
```

2022-05-05 04:20 UTC, ATH1909 commented on code/game/objects/items/knives.dm
> +	desc = "A makeshift plasma glass shiv."
```suggestion
	desc = "A makeshift plasmaglass shiv."
```

2022-05-05 04:20 UTC, ATH1909 commented on code/game/objects/items/knives.dm
> +	desc = "A makeshift titanium infused plasma glass shiv."
```suggestion
	desc = "A makeshift titanium-infused plasmaglass shiv."
```

2022-05-05 04:21 UTC, ATH1909 commented on code/game/objects/items/stacks/sheets/glass.dm
> +	new/datum/stack_recipe("plasma glass shard", /obj/item/shard/plasma, time = 20, on_floor = TRUE) \
```suggestion
	new/datum/stack_recipe("plasmaglass shard", /obj/item/shard/plasma, time = 20, on_floor = TRUE) \
```

2022-05-05 04:22 UTC, ATH1909 commented on code/game/objects/items/stacks/sheets/glass.dm
> +				to_chat(user, span_notice("You wrap the [cloth] around the [src] forming a makeshift weapon."))
```suggestion
				to_chat(user, span_notice("You wrap the [cloth] around the [src], forming a makeshift weapon."))
```

2022-05-05 04:22 UTC, ATH1909 commented on code/game/objects/items/stacks/sheets/glass.dm
> +				to_chat(user, span_notice("You wrap the [cloth] around the [src] forming a makeshift weapon."))
```suggestion
				to_chat(user, span_notice("You wrap the [cloth] around the [src], forming a makeshift weapon."))
```

2022-05-05 04:23 UTC, ATH1909 commented on code/game/objects/items/stacks/sheets/glass.dm
> +				to_chat(user, span_notice("You wrap the [cloth] around the [src] forming a makeshift weapon."))
```suggestion
				to_chat(user, span_notice("You wrap the [cloth] around the [src], forming a makeshift weapon."))
```

2022-05-05 04:23 UTC, ATH1909 commented on code/game/objects/items/stacks/sheets/glass.dm
> +				to_chat(user, span_notice("You wrap the [cloth] around the [src] forming a makeshift weapon."))
```suggestion
				to_chat(user, span_notice("You wrap the [cloth] around the [src], forming a makeshift weapon."))
```

2022-05-08 00:13 UTC, Ebb-Real commented
This could probably be turned into GAGS if you're up for it. Would maybe be a bit difficult to get the texture and color right though.

2022-05-08 09:02 UTC, Comxy commented
> This could probably be turned into GAGS if you're up for it. Would maybe be a bit difficult to get the texture and color right though.

What do you mean with GAGS?

2022-05-08 11:50 UTC, Ebb-Real commented
> > This could probably be turned into GAGS if you're up for it. Would maybe be a bit difficult to get the texture and color right though.
> 
> What do you mean with GAGS?

GAGS is a way to assemble a sprite with layers and assigned colors. This means if you have multiple sprites that are just recolors of the original you can turn them into GAGS and just have one or two sprites that is white with shading and assign colors to them with code and it will color it for you, the assigned color's brightness will be adjusted by the shading you added to the GAGS sprite.

This is good because its easy to recolor sprites (in this case if someone adds a new type of glass they just gotta assign the color of the new glass) and because you need less sprites that are just variations of the first one, so you can just have one sprite that covers them all. GAGS also allows for sprites to be recolored mid-game this is how the color customizable items from vendors work, these include: bandana, beret and shoes.

Here's an example: For bandanas you would need a separate sprite for all of these
![image](https://user-images.githubusercontent.com/95765134/167294628-c4a3519e-31e4-4ca7-8681-1729316a9267.png)

but instead you just need these sprites and can assemble the layers in different ways and different colors:
![image](https://user-images.githubusercontent.com/95765134/167294703-8f1aec79-84f4-4c5d-a9bb-428f475925f2.png)
![image](https://user-images.githubusercontent.com/95765134/167294720-bb463897-b4da-4587-8015-c761f5af0f3a.png)
![image](https://user-images.githubusercontent.com/95765134/167294729-d8f0af03-85ed-4a54-9269-2e191d2634f2.png)



Here's a guide on how to do it: https://hackmd.io/@tgstation/GAGS-Walkthrough

2022-05-08 18:10 UTC, Comxy commented
GAGS seem like a cool idea, but I will pass on it for now. Maybe someone else will do it or I'll revisit this idea but I'll see if this PR gets merged first as it is right now.

2022-05-08 18:16 UTC, tralezab requested changes
okay lets go on to actual code stuffs

2022-05-08 18:16 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +				user.put_in_hands(shiv)
Just have the shard have a var for what it should turn into when you apply cloth, and then we don't need to have all this repeating code. do_after times can also be like that

2022-05-08 18:16 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			if(do_after(user, 140, target = src))
```suggestion
			if(do_after(user, 14 SECONDS, target = src))
```

2022-05-08 18:16 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			if(do_after(user, 70, target = src))
```suggestion
			if(do_after(user, 7 SECONDS, target = src))
```

2022-05-08 18:16 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			if(do_after(user, 70, target = src))
```suggestion
			if(do_after(user, 7 SECONDS, target = src))
```

2022-05-08 18:16 UTC, tralezab commented on code/game/objects/items/stacks/sheets/glass.dm
> +			if(do_after(user, 35, target = src))
```suggestion
			if(do_after(user, 3.5 SECONDS, target = src))
```

2022-05-08 21:10 UTC, tralezab approved these changes
awesome possum

2022-05-08 21:11 UTC, merged