Use filters for changing human height
tgstation/tgstation pull request #66644
Opened 2022-05-01 23:35 UTC by jacklecroy

## Changelog

Tau Ceti Station added height preferences. https://github.com/TauCetiStation/TauCetiClassic/pull/8179 This can be added in a later change.

Six height levels are available, and one is used for dwarfism now.
![](https://i.imgur.com/DjvOR2P.png)

:cl: That REALLY Good Soda Flavor
tweak: Changed how dwarf appearance is created.
add: Admins can adjust a human mob's height in VV menu.
/:cl:

2022-05-01 23:41 UTC, carshalash commented
Aww, I wanted manlets of every species.

2022-05-01 23:48 UTC, jacklecroy commented
It should work for any species including monkey.

2022-05-01 23:52 UTC, theta060 commented
time to become short just so its harder to click on me (and to mirror myself ingame)

2022-05-02 01:28 UTC, tralezab commented
![image](https://user-images.githubusercontent.com/40974010/166174034-39439237-d556-43c1-857d-65c095e8818e.png)
"mom said it was my turn to use the insulated gloves"

2022-05-02 06:41 UTC, axietheaxolotl commented
I can SEE the mixels in the screenshot

2022-05-02 12:22 UTC, Fikou commented
the tweak label does not exist anymore

2022-05-02 14:18 UTC, Fikou reviewed
these break any sprite that would go above 32x32 (including huds), do you have any solution to that?
![image](https://user-images.githubusercontent.com/23585223/166249747-c021563c-d9b5-4dc4-9e3a-40c824042d20.png)
![image](https://user-images.githubusercontent.com/23585223/166249768-f623745c-2eec-4313-8620-f95ad4ff1ee2.png)

2022-05-03 01:28 UTC, jacklecroy commented
> these break any sprite that would go above 32x32 (including huds), do you have any solution to that? ![image](https://user-images.githubusercontent.com/23585223/166249747-c021563c-d9b5-4dc4-9e3a-40c824042d20.png) ![image](https://user-images.githubusercontent.com/23585223/166249768-f623745c-2eec-4313-8620-f95ad4ff1ee2.png)

I will look into increasing the size of the filter and see if that works. I was having trouble adding a filter to mutable appearances, but I will look into that and then the HUD could be ignored.

2022-05-03 15:23 UTC, TheBonded commented
![image](https://user-images.githubusercontent.com/58570888/166483723-f952b73b-54b4-471e-bc22-c90c93f33bb7.png)
why do they not have legs

2022-05-06 03:15 UTC, jacklecroy commented
I can't figure out any way to make the sprite not cut off at 32px.

2022-05-06 04:58 UTC, Mothblocks requested changes
Why has filters moved to datums? That does not make any sense, filters are an atom-level concept.

2022-05-06 04:58 UTC, Mothblocks commented on code/__DEFINES/mobs.dm
> +#define CARBONHEIGHT_TALLEST  "tallest height"
No alignment indentation. https://github.com/tgstation/tgstation/blob/master/.github/guides/STYLE.md#tabs-not-spaces

Also, rename to CARBON_HEIGHT, two words.

2022-05-07 02:17 UTC, jacklecroy commented
> Why has filters moved to datums? That does not make any sense, filters are an atom-level concept.

To apply them on an image or mutable appearance.

2022-05-08 03:12 UTC, tralezab commented
> I can't figure out any way to make the sprite not cut off at 32px.

This is a really big killer for the pr, having height cut off any overlays on a mob that is entirely built out of overlays that currently has items that extend beyond the 32x32 bounds is just too much. If there's a solution I'm down but that's pretty big killer for me since we need to stop supporting bigge (tm) items and overlays, which can currently be done

2022-05-08 03:12 UTC, closed without merging

2022-05-08 12:22 UTC, DarthSidiousPalpatine commented
I am the author of the original PR on the Tau Ceti build. You just missed the one thing I did.

Make two procs, one will apply filter on image regarding the height parameter.
Second will apply pixel_y offset on image regarding the height parameter.

So, when you assemble your body (torso, legs, hands) + body uniform/clothes - you apply filters to them via the first proc.
Then, when you assemble head, masks, inhand items, helmets, tails, hair and etc - you have to apply pixel_y offset via the second proc.
Also, apply appearance flag "KEEP_APART " to your hud images or something like that.

Sorry, I'm too lazy to puzzle out your build and exactly how you assemble your human sprite, so, I just can help with advice.

2022-05-08 23:51 UTC, jacklecroy commented
> I am the author of the original PR on the Tau Ceti build. You just missed the one thing I did.
> 
> Make two procs, one will apply filter on image depending the height parameter. Second will apply pixel_y offset on image depending the height parameter.
> 
> So, when you assemble your body (torso, legs, hands) + body uniform/clothes - you apply filters to them via the first proc. Then, when you assemble head, masks, inhand items, helmets, tails, hair and etc - you have to apply pixel_y offset via the second proc. Apply filters and offset directly to the separate overlay images before they combined into a human. Also, apply appearance flag "KEEP_APART " to your hud images or something like that.
> 
> Sorry, I'm too lazy to puzzle out your build and exactly how you assemble your human sprite, so, I just can help with advice.
> 
> The REAL problem with that is, a photos are kinda "broken", just because GetFlatIcon works just by picking an actual object's icon, without any filters that are "client-side". So, you will get strange and weird hair that floats above your human or pushed in your head, weird offsetting and etc. I heard BYOND devs want to refactor how GetFlatIcon or something like that will work, but I'm trying to solve this with completely new and separate photography mechanic that will work with images instead of icons, but its kinda scetchy now. Nevermind, its a small issue.
> 
> Sorry for my English, its kinda ugly and bad sometimes.

I will look into that! I think tg has a different method for GetFlatIcon. That function is notoriously bad, so I don't think it will matter much.