Adds an ancient altar to maintenance.
tgstation/tgstation pull request #66666
Opened 2022-05-02 22:31 UTC by Fikou

## About The Pull Request

Adds an ancient cult altar to the depths of maintenance.
It can print products woven by the ancient cultists.

## Why It's Good For The Game

More fascinating stuff to find in maintenance is nice.

## Changelog

:cl: Fikou, sounds by Floyd
add: Maintenance now contains an ancient altar.
/:cl:

2022-05-02 22:31 UTC, jlsnow301 commented
666666 get

2022-05-03 00:09 UTC, Shadowflame909 commented
>Clock Cult Sounds
>RED Paints

Ratvars corpse is rolling in his grave

2022-05-03 16:47 UTC, bruhlookatthisdood commented
the fact that this is pull request 66666 makes me think that you waited for this pr number

2022-05-03 23:04 UTC, MrMelbert requested changes

2022-05-03 23:04 UTC, MrMelbert commented on code/modules/antagonists/cult/cult_structures.dm
> +	var/use_cooldown_duration = 5 MINUTES
you moved `use_cooldown_duration` down a level but not `COOLDOWN_DECLARE(use_cooldown)`

though if you ask me you could totally make the altar an item_dispenser subtype I think it has the ability to support that

2022-05-05 03:10 UTC, ATH1909 commented on code/game/objects/structures/maintenance.dm
> +	desc = "What is this? Who put it on this station? And why does it eminate <span class='hypnophrase'>pants energy?</span>"
```suggestion
	desc = "What is this? Who put it on this station? And why does it emanate <span class='hypnophrase'>pants energy?</span>"
```

2022-05-05 03:10 UTC, ATH1909 commented on code/game/objects/structures/maintenance.dm
> +	desc = "What is this? Who put it on this station? And why does it eminate <span class='hypnophrase'>pants energy?</span>"
also, I think mentioning "pants energy" kind of spoils the surprise, but maybe that's just me

2022-05-05 03:11 UTC, ATH1909 commented on code/game/objects/effects/spawners/random/structure.dm
> +		/obj/structure/destructible/cult/pants_altar = 10,
imo, this should probably be put in the oddity loot pool, not a normal loot pool like the crate spawner one

2022-05-05 03:12 UTC, ATH1909 commented on code/game/objects/structures/maintenance.dm
> +	desc = "What is this? Who put it on this station? And why does it eminate <span class='hypnophrase'>pants energy?</span>"
maybe only cultists should be able to see that it radiates pants energy, since they can see the exact functions of other cult structures (IIRC)?

2022-05-05 03:14 UTC, ATH1909 commented on code/game/objects/structures/maintenance.dm
> +		mob.add_confusion(10)
minor nitpick, but don't we have the disgust system for handling nausea?

2022-05-05 03:14 UTC, ATH1909 commented on code/game/objects/structures/maintenance.dm
> +	desc = "A pair of pants. They do not look natural. They smells like fresh blood."
```suggestion
	desc = "A pair of pants. They do not look natural. They smell like fresh blood."
```

2022-05-05 21:40 UTC, CourageTheCat commented
wait so does it make pants exclusively

2022-05-08 01:47 UTC, tralezab requested changes
stuffs

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +	break_message = "<span class='warning'>The structure shatters, leaving only a demonic screech!</span>"
are you sure this couldn't be the macro?

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +		to_chat(user, "<span class='notice'>[src] is creating something, you can't move it!</span>")
use the span macro

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +				to_chat(usr, "<span class='warning'>[src] is not ready to create something new yet...</span>")
use the span macro, also, there really is no reason to use usr here.

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +	visible_message("<span class='warning'>[src] starts creating something...</span>")
use the span macro

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +	for(var/mob/living/mob in viewers(7, src))
while you're doing other stuff, might as well improve this var name which is kinda meh

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +/obj/structure/destructible/cult/pants_altar/proc/pants_stageone()
doc the proc! doesn't have to be a lot, just a quick blurb

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +/obj/structure/destructible/cult/pants_altar/proc/pants_stagetwo()
doc the proc! doesn't have to be a lot, just a quick blurb

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +/obj/structure/destructible/cult/pants_altar/proc/pants_stagethree()
doc the proc! doesn't have to be a lot, just a quick blurb

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +	for(var/mob/living/mob in viewers(7, src))
better var name if you so decide

2022-05-08 01:47 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +	for(var/mob/living/mob in viewers(7, src))
better var name if you so decide

2022-05-08 17:22 UTC, tralezab approved these changes
you...... piece.... i'll just commit this for you

2022-05-08 17:22 UTC, tralezab commented on code/game/objects/structures/maintenance.dm
> +		viewingmob.blur_eyes(10)
```suggestion
		viewing_mob.blur_eyes(10)
```

2022-05-08 17:36 UTC, merged