New mob fire!
tgstation/tgstation pull request #66705
Opened 2022-05-05 01:52 UTC by Gandalf2k15

## About The Pull Request

This is a port of TauCeti's pending fire icons, I really like them, and have been given spritetainer approval to port these.

This PR also changes how fire is handled, or at least, returns the way it used to be handled, while also updating it to use species to choose what kind of fire overlay to use. This variable was set before... but never used...

... This resulted in monkeys not having the correct fire overlay! Unbelivable. That's been fixed however!

Here's a preview:

https://user-images.githubusercontent.com/9026500/166853221-8d8b2370-b5a9-4664-9369-1ad5b59d08c0.mp4

Small fire:
![image](https://user-images.githubusercontent.com/9026500/166853248-a76a2777-c3c0-422f-b182-f16389fbe365.png)

Big fire:
![image](https://user-images.githubusercontent.com/9026500/166853282-c9a28da5-065b-45f6-9be4-36f0aedeea9a.png)

Monke!
![image](https://user-images.githubusercontent.com/9026500/166853305-af1205b5-5c05-4ea2-9bae-6fd35c105356.png)

Original PR: https://github.com/TauCetiStation/TauCetiClassic/pull/9238

Creator: DarthSidiousPalpatine
Credits go to them for these pretty awesome sprites.

## Why It's Good For The Game

Well, I think these look good, it also fixes some strange behavior with the update fire system.

## Changelog
:cl:
imageadd: Mob fire sprites have been updated!
refactor: The way mobs update fire has been refactored. If you spot any anomalies, please report them.
fix: Monkeys will now actually show the correct fire sprite!
/:cl:

2022-05-05 01:54 UTC, dawsonkeyes commented
YES I'M ON FIRE

2022-05-05 01:55 UTC, Imaginos16 approved these changes
hot

2022-05-05 01:56 UTC, Gandalf2k15 commented
I'm aware the layer is incorrect, I will fix it shortly.

2022-05-05 01:59 UTC, Kapu1178 requested changes

2022-05-05 01:59 UTC, Kapu1178 commented on code/modules/mob/living/carbon/carbon_update_icons.dm
> +			fire_override = "human"
```suggestion
		fire_override |= "human"
```

2022-05-05 01:59 UTC, Kapu1178 commented on code/modules/mob/living/carbon/carbon_update_icons.dm
> +		overlays_standing[FIRE_LAYER] = small_fire_overlay
```suggestion
		overlays_standing[FIRE_LAYER] = mutable_appearance('icons/mob/onfire.dmi', "[fire_override]_small_fire", -FIRE_LAYER, appearance_flags = RESET_COLOR)
```

2022-05-05 01:59 UTC, Kapu1178 commented on code/modules/mob/living/carbon/carbon_update_icons.dm
> +			overlays_standing[SECONDARY_FIRE_LAYER] = big_fire_overlay
```suggestion
			overlays_standing[SECONDARY_FIRE_LAYER] = mutable_appearance('icons/mob/onfire.dmi', "[fire_override]_big_fire", -SECONDARY_FIRE_LAYER, appearance_flags = RESET_COLOR)
```

2022-05-05 01:59 UTC, Kapu1178 commented on code/modules/mob/living/carbon/carbon_update_icons.dm
> +		var/fire_override = dna?.species?.fire_overlay
```suggestion
		var/fire_override = dna?.species.fire_overlay
```
DNA should never be null here but sanity is fine here. Species will NEVER be null if dna is present I don't believe.

2022-05-05 05:13 UTC, SmArtKar commented
Conflicts with datumized fire over here https://github.com/tgstation/tgstation/pull/66573

2022-05-05 05:14 UTC, SmArtKar commented
Conflicts with datumized fire over here https://github.com/tgstation/tgstation/pull/66573

2022-05-05 10:59 UTC, Fikou commented
minecraft fire

2022-05-06 03:55 UTC, UDaV73rus commented
> Creator: DarthSidiousPalpatine
> Credits go to them for these pretty awesome sprites.

@DarthSidiousPalpatine - code for TauCeti
@UDaV73rus (oh, its me!) - sprites

I can sprite for you gradations of fire, if you need it.
Will include in next bunch of fire sprites

2022-05-06 04:54 UTC, Mothblocks requested changes
Nit

2022-05-06 04:54 UTC, Mothblocks commented on code/modules/mob/living/carbon/carbon_update_icons.dm
> +		fire_override ||= "human"
```suggestion
		var/fire_override = dna?.species.fire_overlay || "human"
```

2022-05-06 04:54 UTC, Mothblocks commented on code/__DEFINES/mobs.dm
> +#define MOB_BIG_FIRE_STACK_THRESHOLD 3
Document this

2022-05-06 05:21 UTC, dragomagol commented
Does this fix #12605 ?

2022-05-06 05:37 UTC, Farquaar commented
I hope the big fire keeps that "totally engulfed in flames" look in-game, but it looks great in the IconDiffBot

2022-05-06 13:06 UTC, closed without merging