Mindshock/mindshield modifications
tgstation/tgstation pull request #66727
Opened 2022-05-05 18:52 UTC by Rhials

## About The Pull Request

Reduces the length of the brainwashing from six minutes to two. Adds a second charge to the mindshock gland to compensate.

Makes it so that having a mindshield will protect you from the effects of a mindshock gland. The includes the passive effects that mindshock glands have on people near them, as well as the brainwash command from the mental interface device.

Since the implant itself is handling the brainwash broadcast, it will still succeed in broadcasting the message even if the gland holder is mindshielded.  Mindshields only prevent you from _receiving_ the brainwash message. Tinfoil hat functionality is untouched and remains the only way to block the message from being broadcast.

Very open to feedback on this one, please let me know what you think.

## Why It's Good For The Game

The entire purpose of mindshields are to protect from brainwashing. If it can shield you from mutineer flashes, traitor hypnoflashes, and the eldritch influence of Nar'Sie herself, it should be able to protect you from alien brainwashing. You already have very little way of seeing it coming, and it can control an entire room of people (like a packed medbay trying to remove abductor glands), so there should be some form of counterplay if the crew knows what the abductors are up to.

As for the length of the hypnosis being shortened, six minutes really starts to drag on when you're at the receiving end of the brainwashing. Abductors still have brainwash surgery for their long-term bits, and with the second charge the mindshock brainwash is a bit more flexible in its short-term comedy potential.

## Changelog

:cl:
balance: The mindshock gland mind control has been changed from a single, six-minute command to two, two-minute long commands. Also, those who are mindshielded will resist the brainwashing effects and the brain-melting waves the gland passively emits.
/:cl:

2022-05-05 22:40 UTC, MrMelbert requested changes

2022-05-05 22:40 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/mindshock.dm
> +	mind_control_duration = 1200
You should put this in `seconds` or `minutes`. 
`120 SECONDS` or `2 MINUTES`.

2022-05-05 22:40 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/mindshock.dm
> +			to_chat(H, span_notice("You hear a faint hum fill your ears, which quickly dies down."))
You can use an early continue here. 
```
if(HAS_TRAIT(H, TRAIT_MINDSHIELD))
	to_chat(H, span_notice("You hear a faint hum fill your ears, which quickly dies down."))
	continue

...
```

2022-05-05 22:40 UTC, MrMelbert commented on code/modules/antagonists/abductor/equipment/glands/mindshock.dm
> +			to_chat(H, span_notice("You hear a low drone as something foreign attempts to enter your mind, but the noise fades after a few moments."))
And you can do an early continue here as well. 
```
if(HAS_TRAIT(H, TRAIT_MINDSHIELD))
	to_chat(H, span_notice("You hear a low drone as something foreign attempts to enter your mind, but the noise fades after a few moments."))
	continue
	
...
```

2022-05-06 08:05 UTC, SkeletalElite commented
Abductors can just remove your mindshield though, right? Rather than making them do more surgery, maybe just make the mind shield implant break?

2022-05-07 16:16 UTC, ATH1909 commented
> Abductors can just remove your mindshield though, right? Rather than making them do more surgery, maybe just make the mind shield implant break?

that'll give your abductee nature away, though

2022-05-07 19:31 UTC, tralezab requested changes
balance wise I think this is fine enough to make, mindshield should at least work intuitively. I remember historically the rename from loyalty to mindshield was done for player intuition towards what the implant actually does.

codewise just a little housekeeping

2022-05-07 19:31 UTC, tralezab commented on code/modules/antagonists/abductor/equipment/glands/mindshock.dm
>  	for(var/mob/living/carbon/H in orange(4,T))
if we use the variable, we should rename bad vars while we're here. change H (and places that use it) to something better!

2022-05-09 16:19 UTC, merged