removes permeability, rolling it into bio armor
tgstation/tgstation pull request #66742
Opened 2022-05-06 10:00 UTC by Fikou

## About The Pull Request

closes #66721
refactors our disease code a tiny bit
removes permeability_coefficient variable from clothing, it decided how much stuff like chems or disease passed through your clothes, while BIO armor only decided how much you could spread diseases yourself, making it pretty much laaughable
permeability_coefficient is now fully rolled into bio armor, so your bio protecting stuff will now protect you from other biological hazards like blobs

![image](https://user-images.githubusercontent.com/23585223/167110330-8e5c5c46-43e0-40cd-a430-e327f115868f.png)
![image](https://user-images.githubusercontent.com/23585223/167110349-587f28e7-a3fb-4da1-8e30-247640ffedf7.png)

this pr semi-works, i just need to go through all the items to set their bio armor to values similar to their old permeability

## Why It's Good For The Game

replaces a weird variable with simpler to understand armor, generalizes bio armor as the standard armor against biohazards.

## Changelog

:cl:
balance: some items may protect more or less against diseases now
/:cl:

2022-05-06 11:40 UTC, Colovorat commented
>permeability

i really hate english sometimes

2022-05-08 00:42 UTC, Ryll-Ryll commented
I'm sti not sold on the benefit of bio armor

2022-05-08 01:57 UTC, tralezab commented
>mini vacationhulen — Today at 6:55 PM
@Ryll-Ryll i'm gonna merge the permeability coeff pr, i agree that bio armor is bad but there is no world where permeability coeff should exist as an overcomplicated mechanic that is at the least worse than bio armor

2022-05-08 01:59 UTC, tralezab requested changes
minor things though which is convenient though because it gives ryll and i time to BROOD over the pr

2022-05-08 01:59 UTC, tralezab commented on code/datums/components/infective.dm
>  		var/obj/item/I = parent
if you use the var you gotta give it a proper name pardner

2022-05-08 01:59 UTC, tralezab commented on code/datums/components/infective.dm
>  		var/obj/item/I = parent
same as above, use the var = give it a good name

2022-05-08 01:59 UTC, tralezab commented on code/datums/diseases/_MobProcs.dm
>  		var/mob/living/carbon/human/H = src
use the var = give it a good name

2022-05-08 01:59 UTC, tralezab commented on code/datums/diseases/_MobProcs.dm
> +	if( ((D.spread_flags & DISEASE_SPREAD_AIRBORNE) || force_spread) && prob((50*D.spreading_modifier) - 1))
D > disease like you did above

2022-05-08 17:10 UTC, merged