Advanced tools are medium sized now.
tgstation/tgstation pull request #66900
Opened 2022-05-11 20:08 UTC by GuillaumePrata

## About The Pull Request
Makes the tier 2 tools be Medium sized instead of Small.

To be clear, this doesn't affect them being carried inside belts in any way.

## Why It's Good For The Game
Oh boye here comes a long Item Economy talk sponsored by "Being sick and doing something "meaningful" as distraction"!

We have multiple ways to balance an Item "desirability" and I feel the advanced tools score too high on that field.
But lets explain that "desirability" properly first, it would be some weird equation between intended use/effectiveness, cost to acquire and cost to use.

- 1: Intended use/effectiveness is a giant can of worms and different for each item but I'm sure you get it's core.
- 2: Cost of acquiring on SS13 is a few things, material cost, research cost, credit cost to purchase, time to acquire AKA asking/stealing/just walking to a vending machine, etc.
- 3: Cost to use would be energy/ammo, cooldowns, limited use/replacing, weight to carry, etc.

Now let's look at the Tier 2 tools and... Most of them don't have a cost that the end user actually cares about, so they are meaningless to them...

- Intended use... they score high on that, print 30 jaws of life/laser saws and put them outside the bar, see how quickly they get grabbed by people. It's pseudo AA or a 17 force sharp weapon that goes into your pocket.
- Material cost is something that miners deal with, research is with science, lathe tax to print is too small.
- They don't use energy/ammo, have no cooldown, don't degrade...

So what the end user has to deal with is their weight... Which is basically nothing since you can carry 49 of them in a bag at the moment. No one is making the hard decision of to carry or not to carry a Jaws of Life in a round, they just do it.

With this change, going for an upgraded tier 2 tool won't be an 100% improvement for everyone at every time and instead a choice that you have to make and will change from round to round. You might have room to keep a laser saw for self defense in a shift and opt to throw it away for a baton in another instead of just keeping the baton **AND** the laser saw inside your box.

## Changelog

:cl: Guillaume Prata
balance: Tier 2 tools (Jaws of life/Laser scalpel/Experimental welder) are changed from Small to Medium sized so now you can't carry 49 Jaws of life in your backpack. 
/:cl:

2022-05-11 20:31 UTC, TemporalOroboros commented
Will this still permit a full toolset in the relevant belt/a toolbox?

2022-05-11 20:44 UTC, GuillaumePrata commented
> Will this still permit a full toolset in the relevant belt/a toolbox?

It won't affect toolbelts but it will affect toolboxes as they are a generic box basically.

2022-05-11 21:39 UTC, Gandalf2k15 commented
Toolboxes should probably be able to hold powertools

2022-05-11 21:50 UTC, GuillaumePrata commented
> Toolboxes should probably be able to hold powertools

They are just reskined boxes code wise at the moment, if they should be buffed to carry medium sized items or just eng gear like toolboxes do it should be in another PR defending reasons to do that.

I do think it would be a nice change tho.

2022-05-11 22:13 UTC, kopoba commented
I read this request 3 times and still don't understand why its good for the game. Can you say it more simple way without wall of text please.

2022-05-11 22:16 UTC, GuillaumePrata commented
> I read this request 3 times and still don't understand why its good for the game. Can you say it more simple way without wall of text please.

Fucking fair point and I will fix that lol

2022-05-11 22:55 UTC, D4C-420 commented
This looks like it affects the nukies version of the jaws of life. Given how much nukies already carry I don't think that their jaws of life should be made larger . 
Also this will just lead to people finding and grabbing belts to carry advanced tools instead.

2022-05-11 22:59 UTC, GuillaumePrata commented
> This looks like it affects the nukies version of the jaws of life. Given how much nukies already carry I don't think that their jaws of life should be made larger .

Good point on the nukies, I will fix that.

> Also this will just lead to people finding and grabbing belts to carry advanced tools instead.

You can't print 30 toolbelts from a lathe so I don't see this as an issue for this case specifically.
The belt has it's own pros/cons and price to acquire.

2022-05-12 00:24 UTC, ilikesaying commented
> You can't print 30 toolbelts from a lathe so I don't see this as an issue for this case specifically. The belt has it's own pros/cons and price to acquire.

Public Botany

2022-05-12 01:20 UTC, GuillaumePrata commented
> Public Botany

If people want to spend a few minutes growing toolbelts at public botany, power to them.
Even with a toolbelt you are still forcing yourself to carry a medium sized item (the toolbelt) instead of a small sized item inside a box so the goal still is achieved either way.

2022-05-12 01:55 UTC, private-tristan commented
medical nerf :(
can no longer jam my gamer gear into my medkit and still have some stuff in there

2022-05-12 02:11 UTC, GuillaumePrata commented
> medical nerf :(
can no longer jam my gamer gear into my medkit and still have some stuff in there

It actually won't affect them (as much) because they work like toolbelts and have an allowed list.

2022-05-12 04:46 UTC, Shadowflame909 commented
Is this actually a problem? The only one with jaws of life are usually just the CE/Engi.

With multiple ways of getting into a department, by the time this is printable. Someone going around jaws of lifing doors shouldn't be an issue, because the shift should be either extended lite. Or on the verge of destruction and its necessary to have such power-tools.

2022-05-12 10:05 UTC, GuillaumePrata commented
> Is this actually a problem? The only one with jaws of life are usually just the CE/Engi.
With multiple ways of getting into a department, by the time this is printable. Someone going around jaws of lifing doors shouldn't be an issue, because the shift should be either extended lite. Or on the verge of destruction and its necessary to have such power-tools.

This has nothing to do with to goal of the PR, tools are meant to be used and if people are using Jaws of life and others to survive/make their lives easier, they are working as intended.
If making less people use it was the goal, a PR making them harder to unlock/print or bulky sized would be the right move.
This PR was made to push a decision into the end player, if they will "expend" a slice of their inventory that is more in line with the power of those tools or not.

2022-05-12 10:40 UTC, Palpetinus commented
I don't really understand. Why can't an upgrade just be an upgrade? Why do upgrades need drawbacks for some reason?
What's the drawback (after printing etc.) of t4 stock parts? Crew Pinpointer over Proximity Crew Pinpointer? BS Body Bag? Advanced Health Analyzer? To go further, advanced wound tending surgeries are also just upgrades without drawbacks. Advanced Plasmacutter? Mining Satchel of Holding?

They're time gated, cost more resources, need Sci to cooperate, need Mining to not sit on its hands this shift and after all that.. they're not even just upgrades anymore, but tradeoffs? Weird, definitely leaves a sour taste in my mouth just thinking about it.

2022-05-12 11:12 UTC, GuillaumePrata commented
> I don't really understand. Why can't an upgrade just be an upgrade?

You are missing the point of the PR, most of your examples are useful only for 1 department.
They aren't something that 99% of the players would want to have on them all the time so there is a decision making into opting to carry an advanced plasma cutter/crew pinpointer/BS bodybag.
There is no decision making on a Jaws/Laser saw, they are too valuable for anyone that can get one regardless of job.

2022-05-12 11:38 UTC, Palpetinus commented
> they are too valuable for anyone that can get one regardless of job

They are valuable _because_ they can fit into boxes easily. Nobody will take a laser scalpel anymore for 17 force, they'll take a saw for 15 because it's easy to get or a spear for 18-20 instead. I already see them used very rarely because it still needs people to tide into medbay, hope the research is done and hope the miners actually mined.
Jaws of Life are just a tool for convenience, hacking and knowing which wire to pulse is de facto faster than the jaws, so jaws are just noob bait anyway
And all of this doesn't even address the rest: I get the scalpel for force or jaws for convenience, but the hand drill? Nobody would ever get a tool over just a box with two tools and 5 spare spaces. Same with the experimental welding tool, sure it's infinite but in its place I could just carry an industrial welding tool and have - again - 6 spare spaces for other small items. I could go on.
All this PR will ultimately do is punish players that later into the round just want to help where they can by storing a full set of tools in boxes and helping out other departments.
You're seeing a problem where there is only one on paper by just comparing a few items in a vacuum, instead of seeing the full picture. Besides Jaws - which arguably could be normal, that one I agree on - none of the advanced tools are used by people outside of the department, unless they specifically want to fill that department's role.

I suppose if this goes through, I'll have to roundstart tide the departments for belts (one of which is very limited). Oh well.

2022-05-12 11:57 UTC, Pickle-Coding commented
The problem is everyone can get every tool easily and fit them into their storages easily, then be able to do everything. Hopefully toolbelts are bulky one day, because it's really cringe seeing a security officer with a full set of engineering and medical tools fit into their bag.

Just because something is convenient, doesn't mean it's good for the game. Sometimes you shouldn't be able to get everything with no cost, and it would be better if people had to make choices if they wanted to powergame with their tools, instead of fitting an entire workshop and hospital in their bag.

2022-05-12 14:16 UTC, GuillaumePrata commented
> They are valuable _because_ they can fit into boxes easily.

Thanks for defending my PR.

2022-05-12 15:52 UTC, Palpetinus commented
> Thanks for defending my PR.

Sooo.. you're just trying to make some tools near useless? Weird. I don't see how this positively adds to the game, or ever could.

2022-05-12 17:32 UTC, SkeletalElite commented
So your logical conclusion to the problem that the Jaws of Life are overpowered ("de facto all access") is to nerf _every_ power tool so hard that the jaws of life are the only one anyone who doesn't have a toolbelt will even consider carrying?

The experimental welder and the hand drill will literally never be used unless the person has a toolbelt, they have minor benefits, but they are not worth the lost space at all.

2022-05-12 17:34 UTC, wesoda25 commented
Being able to load boxes with essential gear (and then fill your bag with many of those) is stupid and will undoubtedly be nerfed one day.

2022-05-12 17:42 UTC, JohnFulpWillard commented
> What's the drawback (after printing etc.) of t4 stock parts?

The higher parts in a machine, the more power it needs to run, it was part of Ghilker's power rebalancing.
It seems like after we learned our lesson, recent PRs actually DO give drawbacks to lategame stuff, rather than just being 'thing but better in every single way with no downsides'.

2022-05-12 17:56 UTC, GuillaumePrata commented
> So your logical conclusion to the problem...

No.

My logical conclusion is that 3/6 advanced tools are beneficial for every single job on the station on every single shift and they only need to trade 6ish % of their inventory to carry them.
So I'm increasing the size of those 6 to not play the "pick and choose" game, avoiding the extra can of worms.

2022-05-12 18:08 UTC, Palpetinus commented
> My logical conclusion is that 3/6 advanced tools are beneficial for every single job on the station

Which? 
Jaws of life are only good to tide, if you have good intentions you can just ask the AI
Laser Scalpel is only good for combat and even then, in this stun combat meta there's far better options
You never mentioned a third

>not play the "pick and choose" game
Saws and surgical drills are already normal sized because they're commonly used as weapons. If you actually knew what you're trying to do, you'd know that and find no issue with picking and choosing

2022-05-12 19:05 UTC, SkeletalElite commented
> Jaws for the utility, Welder and Laser Scalpel for combat.

The welder and laser scalpel are hardly premium weapon, and this change does nothing to change the scenario you mentioned they're widely used in (blob) because the go to for fighting a blob will still be to print 50 of these the only thing that changes is once the blob is dead everyone will just throw them away because the regular welder is better. Hell the regular welder is probably even better for fighting a blob since you don't have to wait on it to charge its fuel and instead just click a welding fuel tank and be full again.

2022-05-12 19:18 UTC, GuillaumePrata commented
> The welder and laser scalpel are hardly premium weapons, and this change does nothing to change the scenario you mentioned they're widely used in (blob) because the go to for fighting a blob...

Good thing I'm not trying to change the balance of crew/blob and just pointed out a reason (based on the previous comment that they are shitty weapons in the stun meta) that everyone wants these 2 weapons, which you agree.
So thanks for defending the PR I guess?

> Hell the regular welder is probably even better for fighting a blob since you don't have to wait on it to charge its fuel and instead just click a welding fuel tank and be full again.

Did you know that you can refill the Experimental Welder too?

2022-05-12 19:23 UTC, SkeletalElite commented
> that everyone wants these 2 weapons,

They don't want them though, they want to use them in one specific scenario after which they will promptly dumpster them like they don't exist because someone decided to balance a tool like a weapon. If they are too useful as weapons, nerf their damage, but nerfing the space they take up makes them worse than their tier 1 counterpart at their primary purpose, a tool.

2022-05-12 19:29 UTC, GuillaumePrata commented
> nerf their damage

I like when the crew uses weapons that are available to their job and would never nerf their effectiveness to enable more of the stun baton meta.

I will repeat myself a last time, the issue isn't about how effective they are as weapons, I already decided to NOT balance them around their weapon status like the saw/drill work.
The issue is their low price for _**anyone**_ to carry.

2022-05-12 22:24 UTC, Pandarsenic commented
If the material and research costs are _really_ negligible, then we can take those out as part of this change, right?

2022-05-12 22:36 UTC, NoxVS commented
There are like 3 tools that tend to be used for reasons other than their actual purpose (Welding torch, jaws of life, laser scalpel) that I could see you wanting to nerf. This also nerfs all the other experimental tools that are bought solely to save space and be more convenient. Hand drills, mechanical pinches, searing tools - All of these are slightly faster but tend to be made just because its easier to handle and manage your inventory. If you are in engineering there isn't even a whole lot of a point in clearing up belt space because aside from like cable coils you usually have nothing else to put in the now empty spaces.

This even makes it so the searing tool, the advanced version of the cautery, is pretty much just straight up a downgrade. The searing tool combines a cautery and surgical drill, the latter of which is almost never used meaning the searing tool just becomes a more unwieldy cautery that is slightly faster. A benefit that is practically useless when the cautery/searing tool is used a grand total of from 0 to 1 times per surgery.

2022-05-12 22:52 UTC, LemonInTheDark commented
I've been kinda tempted to up normal tool sizes, this is chill tho

2022-05-13 01:20 UTC, GuillaumePrata commented
> If the material and research costs are really negligible, then we can take those out as part of this change, right?

Feel free to make that PR if you think so because again, that isn't exactly what I said but at least it has been quite funny to talk here to be fucking honest.

2022-05-13 02:55 UTC, Pandarsenic commented
> > If the material and research costs are really negligible, then we can take those out as part of this change, right?
> 
> Feel free to make that PR if you think so because again, that isn't exactly what I said but at least it has been quite funny to talk here to be fucking honest.

> Material cost is something that miners deal with, research is with science, lathe tax to print is too small.

If the item is being balanced around the end user not caring about those costs, then the irrelevant costs should be removed so that lacking miners, R&D focusing on other branches of research, etc., doesn't become a burden on the end user, no?

Because, sure, I've thought that maybe Jaws of Life _should_ be larger, not for balance reasons but for fluff reasons (their IRL size and their SS13 ability to force open an airlock that can fit a mech through it). But if they're being bigger primarily because minerals and research aren't a concern, why not just make the mineral costs not be a thing, or make it titanium only so someone sufficiently determined can disassemble a pod's walls for it if there are no miners around?? Or move the doorjack function to, say, a power cell or gas tank stored in the Jaws?

(Also, re: Welder/LaserScalpsaw as weapons, I would posit that they're only so desirable because so many things have been nerfed so aggressively that anything reaching even basic combat efficacy. Few items you can obtain have the force of the laser scalpsaw, at ANY size. Just a general lack of anything in the force bracket between the T1 Saw/Drill and the spear. The experimental welding tool isn't even significantly better as a weapon than the basic welding tool, with fuel basically never being a serious limiting factor in a fight between carbons. If there is a problem to address there, it's a lack of real weapons in the crew's hand, not the size of the improved surgical tools.)

2022-05-13 05:40 UTC, CMDR-Gungnir commented
Why can't an upgrade just be an upgrade?

2022-05-13 06:16 UTC, Orchian commented
I don't quite agree with enlarging the majority of the T2 tools. However, I see no issue with enlarging the T2 welder. I think you should go further with the Jaws (Large perhaps?), and I feel that it'd be better to nerf the laser scalpel by making it require batteries as opposed to increasing its size

2022-05-13 08:27 UTC, Palpetinus commented
I find it funny how you keep contradicting yourself in circles

\>They are desirable for the crew because they are good weapons
\>But I am not considering them as weapons, but tools
\>Despite this, I will still nerf them because they are good weapons

So what is it now, are you nerfing them because they are good weapons or do you not want to consider them weapons? You can't have both. Literally, in the same comment, you say "everyone gets them for combat" and "not everything revolves around combat". You're contradicting yourself here.

2022-05-13 10:01 UTC, Miczu555PL commented
> > They are valuable _because_ they can fit into boxes easily.
> 
> Thanks for defending my PR.

I disagree that this statement defends your PR.

I mean they are more valued BECAUSE they are UPGRADE? Making them take more space literally nullfies that upgrade. And WHY would that be changed?

And yes, nearly everyone wants to powergame one jaws for themselves, because no one likes to die to atmos issues due to lack of airlock access or three separate tools. (tiding aside) That's cringe.

Any more uses for the Jaws?

2022-05-13 10:26 UTC, GuillaumePrata commented
> I find it funny how you keep contradicting yourself in circles...

No, you just keep bending what I say because you want to win the internet argument but let's go over your points again:

>They are desirable for the crew because they are good weapons

This is a fact and I agree.

>But I am not considering them as weapons, but tools

This is wrong, I said I'm not balancing them around their weapon values as it was suggested to nerf their damage because I like when crew uses job specific weapons to fight instead of stealing the almighty baton.

>Despite this, I will still nerf them because they are good weapons

Wrong again, I said it pretty cleanly, the change is good because they are a desirable item for everyone regardless of their job.

> So what is it now, are you nerfing them because they are good weapons or do you not want to consider them weapons? You can't have both. Literally, in the same comment, you say "everyone gets them for combat" and "not everything revolves around combat". You're contradicting yourself here.

"Everyone gets them for combat" and "Not everything in the game revolves around combat" are both correct and I don't see why you can't understand it.
Again, I'm rebalancing them because they are an item that everyone would have on every shift if they can opt in.

When Ghilker nerfed the Insuls (another desirable item by 99% of the crew) by giving them chonky fingers... do you think that instead they should have nerfed it's item slap damage?
Oh no... they should have nerfed it's shock resistance because that is what everyone uses it for by your logic and then everyone would suffer, including the engineers that use it for their job.

2022-05-13 10:53 UTC, Palpetinus commented
>because they are a desirable item for everyone regardless of their job

>"Everyone gets them for combat" and "Not everything in the game revolves around combat" are both correct and I don't see why you can't understand it.

Wrong. People who simply do not care about combat will also not care about laser scalpels and such. I'd say that on the MRP servers, the majority doesn't care much about combat and on LRP, still about half the crew doesn't. I know there's this meme that every player is just a validhunter waiting to valid someone, but that's clearly just another case of the loud minority being noticed the most.

>they are an item that everyone would have on every shift if they can opt in

Hard to prove or disprove. If you look at the numbers, present them in the hallways and tell everyone "this is better than a butcher's cleaver and here's one for free" then absolutely. However, most of the crew doesn't know of its force and even less will go out of their way to, for example, go into medical and print one even if the way is bolted open. People simply do not care this much about minmaxing their damage/inventory.
There are so many more items that are relatively easy to get and everyone who cares about minmaxing will take one if offered. Health analyzers, BS body bags, magboots, ATMOS holofans, combat knives, pepper spray,..
Just "if someone could opt into getting one, they'd take it" isn't a very good argument considering there's dozens of those items.

>insuls

Entirely irrelevant here. Insuls are a roundstart item that had absolutely no effort (except gotta tide) or drawbacks involved, it's not comparable. Everyone beelined for them because there wasn't a single drawback to wearing them. Experimental tools need research, the right materials (=effort) and have no discernable drawbacks _because_ they are hard to get upgrades.

Maybe I simply cannot comprehend your arguments. I just play this game daily and I have yet to see a single shift where people are mass-outfitted with either of the tools you're nerfing. Their high material costs often make them a well-kept treasure by their respective department, so even in a blob situation, people tend to print industrial welding tools instead of experimental ones from engineering.

I do, however, 100% agree on the Jaws. Their functionality (1 small item AA) heavily outweighs the cost.

2022-05-13 11:03 UTC, GuillaumePrata commented
> Entirely irrelevant here.

Sure, let's see how the argument goes then.

> Insuls are a roundstart item that had absolutely no effort (except gotta tide) or drawbacks involved

So the difference is just that one needs research, got it.

> Everyone beelined for them because there wasn't a single drawback to wearing them.

Exactly like tier 2 tools, got it.

> Experimental tools need research, the right materials (=effort) and have no discernable drawbacks because they are hard to get upgrades.

And this is again, something I said at the main post, the average crew member that wants a tier 2 tool doesn't do the research or the mining for it and that is why I'm adding something they actually will care about on their decision making, inventory management.

2022-05-13 11:06 UTC, kopoba commented
> Wrong again, I said it pretty cleanly, the change is good because they are a desirable item for everyone regardless of their job.
And?
Crowbar is "desirable item for everyone" are you gonna nerf it too in next pr so more spacemens die from suffocation or burns behind fire airlock?
I know this game about suffering but where is the line beyond which survival rate drops to 0?


PR is not about advanced tools is good weapon. who the heck use jaw of life as weapon? Circular saw and laser scalpel have 15 and 16 damage wich is like no difference at all.

Its not about all access pass. Since you can hack faster.
So whats the point?

> When Ghilker nerfed the Insuls
This is worst change that affect only engineers that is working with computer consoles to monitor SM and powernet.

2022-05-13 11:10 UTC, CMDR-Gungnir commented
But why can't an upgrade just be an upgrade? I can't tell you the last time I had T2 Surgery or Engineering tools outside of being in that department, being given them, or Actively Helping The Department (all of those being cases where I SHOULD have them anyway).

Palp's entirely right, you're punishing the vast majority of the playerbase for the actions of the minority.

How does this benefit the game? What exactly makes an 'upgrade' if it's got just as major of a downside as its benefit? What's the point of the mineral and research requirement if they aren't better than the roundstart stuff?

2022-05-13 11:51 UTC, GuillaumePrata commented
> But why can't an upgrade just be an upgrade?

It still is just an upgrade over the basic tools, if you have a toolbelt, so I don't know what you are going on about "you're punishing the vast majority of the playerbase" when it was made to not hurt the main department in any way and instead discourage people that have a full set of engineering + medical tools inside a cardboard box.

It's literally the second line in the PR but imagine reading.

2022-05-13 12:06 UTC, CMDR-Gungnir commented
> It's literally the second line in the PR but imagine reading.

I'll imagine reading if you imagine making a good PR.

2022-05-13 12:07 UTC, GuillaumePrata commented
> I'll imagine reading if you imagine making a good PR.

lol

2022-05-13 12:23 UTC, SkeletalElite commented
Where are all these people running around with full sets of upgraded engineering and medical tools in a single box. Most people aren't even running around with a set of regular tools, much less upgraded ones. I can't help but feel this is a change trying to address a non-existent problem.

2022-05-13 14:44 UTC, JohnFulpWillard requested changes
let them fit in toolboxes and I'll be happy with this

2022-05-13 14:44 UTC, JohnFulpWillard commented on code/game/objects/items/tools/crowbar.dm
>  	desc = "A re-engineered copy of Nanotrasen's standard jaws of life. Can be used to force open airlocks in its crowbar configuration."
please add a note mentioning that the size is smaller than average

2022-05-13 14:58 UTC, GuillaumePrata commented
> let them fit in toolboxes and I'll be happy with this

I will change the size of items that they can carry to medium them as they are still worse than a generic bag when carried by hand.

2022-05-13 16:34 UTC, merged