Stun batons now deactivate when put into a bag/storage, and take 5 seconds to turn on.
tgstation/tgstation pull request #67044
Opened 2022-05-16 18:02 UTC by Iamgoofball

## About The Pull Request
Stun batons now deactivate when dropped, placed into storage, taken out of storage, or put into an inventory slot, and take 5 seconds to turn on.

## Why It's Good For The Game

Made after Watermelon suggested some form of mechanic for this instead of making stun batons bulky.

We want people to talk more and RP more, and that's simply impossible to get players to do when they're worried about surprise stun batons, since you only need to hit someone with a stun baton once to win the fight. This gives people being chased by a stun baton an opportunity to react and see it coming, rather than being completely blindsided by someone who's hotkey game is on point instantly equips, activates, and batons them.

## Changelog
:cl:
balance: Stun batons now deactivate when dropped, placed into storage, taken out of storage, or put into an inventory slot, and take 5 seconds to turn on.
/:cl:

2022-05-16 18:05 UTC, SuperNovaa41 commented
I think 5 seconds is a little extreme

2022-05-16 18:33 UTC, FernandoJ8 commented
5's overdoing it a bit. I'd say 1 to 2 seconds, though it's hard to say because I can't think of any precedent on this kind of thing.
5 is still definitely too much to be practical though and would lead to stun baton use dropping in favour of some other tool like flashes or disablers. We want to balance the meta, not create a new one.

2022-05-16 19:44 UTC, private-tristan commented
new meta: grab 2 disablers, turn on combat mode, pull 2 out of backpack and click 2-3 times from 1-2 tiles away, die because you didn't notice they had ablative on.

2022-05-16 20:06 UTC, Mothblocks requested changes
I will choose to believe you missed my post on your bulky stun batons PR, so I will post this part of it again: **One of SS13's largest problems is that the most fun way to play an antagonist is stealthily, but the best way to play an antagonist is to go loud.**

This PR punishes stealth antagonists far too heavily, and I **do not want a stun baton nerf if it means stealth antagonists are made substantially weaker**.

Your "why it's good for the game" does not address that concern, similar to the bulky stun batons PR.

2022-05-16 20:38 UTC, Iamgoofball commented
give thieves a sap or something if you want them to do fighty shit, last i heard the design goal of thief is "do not fight unless you absolutely have to"
obsessed is its own ballpark but obsessed can usually acquire job specific ways to take people down
changelings have a variety of takedown methods
traitors have a fucking uplink of 500 goddamn ways to attack people and take them down
wizards have a literal spellbook of tricks
revs have flashes that mute people temporarily
i know heretics have a funny hand equivalent and so do cultists
families doesn't need stealth they're an open in the air antag
nuke ops have CQC and shit and even more stun options

people in any jobs usually have some form of combat weapon that induces some form of stun in some way

all antags either
1. have some way to stun/takedown people they can acquire via their gear or mechanics tree
2. aren't supposed to be doing direct combat like Thief
3. don't have gear as part of the challenge(ie. Obsessed, Fugitive)

2022-05-16 20:43 UTC, private-tristan commented
> I know heretics have a funny hand equivalent

have you never played heretic? it's literally impossible to stamcrit using heretic hand (alone), the only use it has is applying mark and its knockdown, and maybe using stamina but if you have other ways to deal stamina you'd just use those instead of "I  AM VALID TO KILL" hand

2022-05-16 20:53 UTC, Iamgoofball commented
i have not gotten lucky enough to roll heretic yet no sorry

2022-05-16 23:02 UTC, private-tristan commented
> i have not gotten lucky enough to roll heretic yet no sorry

heretics have been in the game for nearly 2 years #51199, did you forget to check your antag prefs for 2 years to turn it on?? it's not like they're rare every other shift has heretics

2022-05-16 23:15 UTC, necromanceranne commented
> This PR punishes stealth antagonists far too heavily, and I **do not want a stun baton nerf if it means stealth antagonists are made substantially weaker**.

Wouldn't it make more sense at that point to give antagonists alternatives to the baton rather than worry about the balance of batons in their hands? Heretics already have this, and traitors used to have something similar in contractor (ebow is kind of a good runner up). Only lings do not, and that's probably something that could be resolved (they used to have parasting for a reason).

I think lumping batons into a limbo state of 'it is or isn't an antagonist weapon depending on the cycle of the moon' does not help this, and someone needs to come to a conclusion as to where these weapons are meant to exist.

Obviously the geared antagonists are not the only ones we have (bb's, revs, etc.), but overfocusing on their use by antagonists neglects who is meant to be using them in the first place and weighing a significant amount of balance on it's shoulders.

2022-05-17 00:26 UTC, Farquaar commented
"We want people to talk more and RP more"
John Sex: "HELP JANE DOE CHAPEL"

2022-05-17 01:10 UTC, closed without merging

2022-05-17 01:22 UTC, Iamgoofball commented
If you refuse to accept that the ability to go from adjacent to someone to "that person is dead" using a common, freely available item that every assistant has in their backpack, then you will never make this an RP game again, Mothblocks.

2022-05-18 11:25 UTC, Palpetinus commented
If this PR gets merged, we'll see sec mass-ordering the traditional equipment crate in cargo to turn them into det-batons.