Adds the Ninja MODsuit
tgstation/tgstation pull request #67220
Opened 2022-05-22 21:17 UTC by Fikou

## About The Pull Request

Adds the ninja MODsuit, converting all the ninja abilities into modules and cleaning them up in the meantime.
![image](https://user-images.githubusercontent.com/23585223/169715901-def8ee5d-1adc-4625-b420-561b80a7eed8.png)
![image](https://user-images.githubusercontent.com/23585223/169715909-9fcccede-fcbb-4b9e-b834-cc73507b2924.png)
Removes block tracking and touches from helmets and gloves respectively, use signals for that.
makes the ninja power cell not a varedited high capacity cell
fixes dash beams not working
fixes double anime phobia
adds a new ninja mask and jumpsuit (sprites arent finished yet)
![image](https://user-images.githubusercontent.com/23585223/169716061-48ab9e2f-567d-48a2-b883-4512ba88891d.png)

- [ ] better descriptions for modules/the suit
- [ ] sprites for the ninja mask/jumpsuit
- [ ] making the ninja glove draining stuff work
- [ ] removing the old space suit

## Why It's Good For The Game

Ninja code is pretty bad, I think it's best to move away into nice modular stuff instead.

## Changelog

:cl: Fikou, PositiveEntropy, Nerevar
refactor: the ninja space suit is now a modsuit
fix: fixes dash beams not working
/:cl:

2022-05-22 21:29 UTC, VladinXXV commented
Are we losing any functionality here, or is the plan for it to effectively just be a better ninja suit? The first thing that comes to mind is draining power from wires/apcs/etc, it'd be a big ninja nerf if they had to change their cell or hide in a borg charger any time they got low on power.

2022-05-22 21:31 UTC, Fikou commented
> Are we losing any functionality here, or is the plan for it to effectively just be a better ninja suit? The first thing that comes to mind is draining power from wires/apcs/etc, it'd be a big ninja nerf if they had to change their cell or hide in a borg charger any time they got low on power.

it can do anything the ninja suit can

2022-05-22 22:09 UTC, MrMelbert commented on code/modules/events/shuttle_loan.dm
> +				new /obj/item/clothing/shoes/jackboots/fast(T)
Thanks I hate it

2022-05-23 04:08 UTC, MetalClone commented
Does it still blow up non-ninjas if they try to wear it? Or does it just get deleted when the ninja self destructs?

2022-05-23 05:34 UTC, Fikou commented
> Does it still blow up non-ninjas if they try to wear it? Or does it just get deleted when the ninja self destructs?

both

2022-05-23 07:47 UTC, MetalClone commented
Fantastic, awesome work again Fikou

2022-05-23 18:30 UTC, Cenrus commented on code/modules/mod/modules/modules_ninja.dm
> +	mod.wearer.say(pick_list_replacements(NINJA_FILE, "lines"), forced = type)
If you want to make this even more modular, it'd be great if the voice lines only trigger when the suit wearer is a ninja

2022-05-27 22:48 UTC, MrMelbert requested changes

2022-05-28 01:09 UTC, Fikou commented on code/modules/mod/modules/modules_ninja.dm
> +/obj/item/mod/module/stealth/ninja
no

2022-05-28 01:09 UTC, Fikou commented on code/modules/mod/modules/modules_ninja.dm
> +	living_user.gib()
meh

2022-05-31 18:20 UTC, AnturK requested changes

2022-05-31 18:20 UTC, AnturK commented on code/modules/mod/mod_control.dm
> +	. += span_notice("<i>You could examine it more thoroughly...</i>")
This feels like something that should be automated, but i guess that's for another PR

2022-05-31 18:20 UTC, AnturK commented on code/modules/mod/mod_control.dm
> +	if(!istype(picked_module))
Why the check removal here ?

2022-05-31 18:20 UTC, AnturK commented on code/game/objects/items.dm
> +	if(SEND_SIGNAL(src, COMSIG_MOVABLE_IMPACT, hit_atom, throwingdatum) & COMPONENT_MOVABLE_IMPACT_NEVERMIND)
Did you check that current uses of this all return flag values

2022-05-31 18:20 UTC, AnturK commented on code/modules/ninja/ninjaDrainAct.dm
> +/obj/machinery/power/apc/proc/ninjadrain_charge(mob/living/carbon/human/ninja, obj/item/mod/module/hacker/hacking_module)
I don't see this one flag value, and they all should.

2022-05-31 21:25 UTC, merged