Head of Personnel Resprite & New HoP Coat
tgstation/tgstation pull request #67286
Opened 2022-05-25 11:47 UTC by axietheaxolotl

## About The Pull Request

You can read the title, can't you? This should be the first part of a whole resprite of the Service department (the best department).

![image](https://user-images.githubusercontent.com/86872535/170254034-8aac87b2-6386-471e-859c-ac261f5323a9.png)

As you can very graciously see in that screenshot, the HoP, now has a brand new coat to wear. Which is a lot more interesting then just a plain armour vest, which this replaces.

Also, also, I resprited the ID Painter. Why? idk cause I could.

## Why It's Good For The Game

Stuff look better = good

## Changelog

:cl:
add: Brand new HoP coat!
imageadd: New sprites for HoP's uniform, skirt, cap, and the ID Painter.
fix: HoP starts with laceups, not brown sneakers.
/:cl:

2022-05-25 11:47 UTC, axietheaxolotl commented
![image](https://user-images.githubusercontent.com/86872535/170254891-59eaf8e2-6c43-4590-8ef4-41dfcd2f1272.png)
![image](https://user-images.githubusercontent.com/86872535/170254908-10a73fac-0bfd-4e09-8db0-80cf1b266079.png)

2022-05-25 12:11 UTC, axietheaxolotl commented
and my fucking git is screwed up kill me now

2022-05-25 12:15 UTC, Sheits commented
I think the shadow on the lower backs, especially the cloak is too big. The arch of the back could cast a shadow like that in the middle with super dramatic lighting but it flattens out the whole sprite in my opinion, and is also inconsistent with the side sprites. Same deal with the front facing state on the jumpsuit, though it does make sense on the jumpskirt with the breasts casting a shadow, the side sprites feel inconsistent. Overall super good work thoe

2022-05-25 15:05 UTC, Likteer commented
Colors not vibrant enough

2022-05-25 16:00 UTC, VladinXXV commented
I think the coat looks kinda weird but I'm diggin the suit and PDA, good stuff.

2022-05-25 16:10 UTC, Imaginos16 approved these changes
Disregarding that minor nitpick, the sprites are most definitely good. Nice work.

2022-05-25 16:56 UTC, Pepsilawn commented
Alt should be changed in code to keep the chest covered if it will only fold in the sleeves.
![image](https://user-images.githubusercontent.com/25415050/170318643-5d1c3e11-a78a-4c24-b354-1e1176d3a2fa.png)

2022-05-25 20:45 UTC, CRITAWAKETS commented
Why is the back of the coat unshaded?

2022-05-25 22:48 UTC, MrDoomBringer commented
Definitely an improvement, though the dark red accents make me think this is some kind of sec-related role. Maybe change to a brown-shade, as that to me evokes cargo/service? Just a thought.

2022-05-26 00:11 UTC, castawaynont commented
a bit evocative of the warden's jacket, looks good

2022-05-26 20:59 UTC, SethLafuente commented
I like this sprite it looks new other than the fact that the hair sticks out of the hat probably a separate issue unrelated to the PR.

I like the current HoP suit couldn't this be an alternative suit like Captain, HoS and RD have alt ones I always opened the HoP dress thing and find it to be a bit small compared to other heads so I see no reason why adding more outfits is a bad idea.

I would say otherwise if this was a remaster of the old suit but this is pretty much an entirely different suit

2022-05-27 20:32 UTC, tralezab requested changes

2022-05-27 20:32 UTC, tralezab commented on code/modules/clothing/suits/armor.dm
> +	name = "\improper Head of Personnel's coat"
```suggestion
	name = "head of personnel's coat"
```

2022-05-27 20:33 UTC, tralezab commented
i'll just commit that for you and merge once checks pass

2022-05-28 10:26 UTC, merged