Potentially fixes a cowboy boot snake harddel
tgstation/tgstation pull request #67293
Opened 2022-05-25 16:29 UTC by SmArtKar

## About The Pull Request

![image](https://user-images.githubusercontent.com/44720187/170313806-5588fac6-b325-48cf-a985-67ebe733fc73.png)
Yeeeeeah

Cowboy boots didn't have any proc for dumping occupants upon being destroyed so it caused a harddel. I think.

## Changelog

:cl:
fix: Potentially fixed a cowboy boot snake harddel
/:cl:

2022-05-26 19:01 UTC, Mothblocks requested changes
![image](https://user-images.githubusercontent.com/35135081/170557951-7626be28-a661-4074-8aad-0a0997fcf1fc.png)

This PR will not be merged until you add a regression test to make sure this doesn't happen again. You should have done this before writing the code for the fix.

This is, luckily, easy. Add a variable that determines whether or not the random chance rolls consistently.

Then, in the create_and_destroy test, add a new section at the bottom like so, because if we are doing our jobs then we will eventually fill a LOT of these:

```dm
// These are type paths that exist for the purpose of reproducing inconsistent behavior

/// Cowboy boots that consistently spawn a snake in the boot
/obj/item/clothing/shoes/cowboy/consistent
    consistent_snake_in_boot = TRUE
```

2022-05-26 19:20 UTC, Mothblocks commented
> Cowboy boots didn't have any proc for dumping occupants upon being destroyed so it caused a harddel. I think.

A great reason for everything I just said--you literally don't even know if this works

2022-05-26 21:18 UTC, LemonInTheDark commented on code/modules/clothing/shoes/cowboy.dm
> +		occupant.forceMove(loc)
Assertion: The snake is already inside our contents, and thus will already be qdeleted on destroy.
So the issue here is the occupants list failing to update. 
You should use Exited to remove the snake from the list when it leaves, that way there's no potential gottchas for deleting the snake or something

2022-06-04 09:22 UTC, Mothblocks commented
OP said they can't make the time to fix this so I'm reopening the branch I was working on

2022-06-04 09:22 UTC, closed without merging