Slime Stasis state gas changed to Nitrous from Bz
tgstation/tgstation pull request #67364
Opened 2022-05-28 15:07 UTC by Dmeto

## About The Pull Request

Slimes will now enter their sleep state by Nitrous Oxide rather then Bz, Maps have been updated to include Nitrous Cans in Xenobio where old Bz cans were.
This also effects Anomaly Red Slimes and other Sentent Slimes.Very minor edits to alert messages.

## Why It's Good For The Game

Prior to #66738 Xenobio would always receive a Bz canaster to be used for slime stasis. After Toxins to Ordinance changes were made these canasters were often taken to complete Bz Shell experiments and Noblium formation whether those doing Xenobio  wanted them or not to quote the one of the comments in #66738 which really summed it up well.

> Years of Atmosian Culture die today, our younglings will never know the joy of speedrunning that BZ can and bashing a Xenobiologist's skull in for getting in the way... Memery aside, this is a good change. 

I also don’t believe that Ordinance will provide Xenobio with Bz as there is no advantage for Ordinance to do and will just add more work for them when they could be making bombs or core compressions. Ordinance is not Atmosphrics and Atmosphrics wont do it for the same reason as Ordinance wont.

If Bz is supplied to Xenobio from Ordinance it will have been too late in the round for it to matter due to it being slow to produce with t3 or better lasers needed and slow formation speed. It will also be even later if its used in Nobilium formation first.

Why Nitrous..

Cheaper and easier to acquire than BZ with it being one of the starting Atmosphic gasses. 
It already has a similar reaction with Carbon Mobs.
Makes Xenobio sabotage/malpractice much more interesting and effective.
Slime persons alread have this reaction and etherals which are from the same planet as Slimes also do.

## Changelog

:cl:

balance: Slimes will now enter their sleep state by Nitrous Oxide rather then Bz. Xenobio on maps changed to reflet this.

/:cl:

2022-05-28 16:18 UTC, GuillaumePrata commented
Xenobio players when they need to cooperate.

2022-05-28 16:46 UTC, Dmeto commented
> Xenobio players when they need to cooperate.

And science in general

2022-05-28 16:51 UTC, Sealed101 commented
who would have thought that a player in a powergaming/empty department having to rely on players from a different powergaming/empty department in a space station paranoia simulator wasn't that good of an idea

having a way to stasis slimes from the get go is nice, no matter the funny air flavor

2022-05-28 18:11 UTC, MetalClone commented
Perfect rebalance for xenobio.

2022-05-28 22:21 UTC, XDTM commented
I think the point of that was to have at least one positive use of bz to allow for plausible deniability for having it around.

2022-05-28 22:36 UTC, Son-of-Space approved these changes
The map edit portion of this looks good. Just changing some file paths to make default canisters into nitrous oxide canisters.

2022-05-28 22:50 UTC, Dmeto commented
> The map edit portion of this looks good. Just changing some file paths to make default canisters into nitrous oxide canisters.

Thanks. Ive only used a map edditor once and it was for preping for this pr. hopefuly i can do some more bug fixing now im aquainted with Strong.

2022-05-29 21:12 UTC, bluetshirtguy commented
> Xenobio players when they need to cooperate.

no one wants to cooperate with atmos, no one.

2022-05-30 04:09 UTC, LemonInTheDark requested changes
Ordinance is quite literally tailor made to produce bz easily and quickly. 
You're also speaking as if these are two different jobs, when both are the same access. 

This decision was made intentionally, why should it be walked back?

2022-05-30 05:05 UTC, Arctrooper8 commented
> Ordinance is quite literally tailor made to produce bz easily and quickly. You're also speaking as if these are two different jobs, when both are the same access.
> 
> This decision was made intentionally, why should it be walked back?

Because having hibernating slimes is an important part of Xenobiology from start to finish. Making BZ isn't something that would take the entire round, but it also isn't a quick and easy prep thing. There is also the fact that not everyone knows toxins, nor do they even want to know toxins. In the situation where there is nobody doing toxins the Xenobiologist is forced to do something they don't want to do and maybe aren't even sure how to do it. There is also no incentive at all for whoever is doing Toxins to actually put in the effort of helping Xenobio. BZ's interaction with slimes is also not exactly common knowledge for anyone who hasn't gone in-depth into Xenobio.

Overall, there isn't gonna always be someone who can make BZ fast. And even if there is there's no incentive for them to store that BZ and send it to Xenobio.

2022-05-30 12:02 UTC, Dmeto commented
> All of Arctrooper8 said
All completely true and that’s only half of it.

Lets say we go this route and Bz is to be supplied by Ordinance,

- We somehow speedruned the necessary t3 components 10 mins by doing all assist experiments while making sure no one else spent points (Heads Engineering and very angry miners for what we have done)
We optimised the freezer/ distro /scrub
![Space Station 13 2022-05-30 124644](https://user-images.githubusercontent.com/75919495/170988174-7057b43c-f5d5-4b8a-ae6d-2b94eedcc9a2.png)

Because round start Ordinance freezer can’t make Bz because heat-exchanging pipes cant get the temp low enough for pressure and this take another 5 mins.

- We run the freezer .. and we run .. and we run .. and we run .. at average 70kpa and cold as we can get half an hour we are only 1500moles in collective canaster and 350ish moles in pipe and we cant even use it yet as it will kill slimes if used as is because its colder then the round start slime euthanize frige.
Not enough for Xeno on single or multi z, not fast enough to keep within our expected round times and we have used most of our resources for a department that can’t assist ordinance in anyway while not fulfilling the main point of Ordinance i.e. make bombs/shells/compressions.

Maybe I’m not the best at toxin mixing, but I say I’ve got intermediate knowledge and il say this cant be done nor should it be done.
Its Atmospherics job to supply gases in this manner not Ordinance and you can’t supply BZ in large amounts at correct temp at round start or mid game.

2022-05-30 15:46 UTC, Dmeto commented
I don’t want to see in a years’ time someone asking for BZ cans to be inserted in Xeno again using the reasoning above while we have the access and shell experiments the same, it will open up Bz tiding again which is dead but not buried, it will be buried with this pull.
Reopening your review LemonInTheDark

2022-05-31 00:43 UTC, LemonInTheDark commented
I don't actually play this game, so I decided to give making some bz a shot, on tram.
I'm setting my production target at 240 moles, because a slime needs its tile to be 5% bz to go into stasis, and the lower room on tram is double deckered, so it needs twice as much gas

See my attempt below.

https://file.house/hSdj.mp4

Here's my step by step.
```
Spawn, walk to toxins.
Grab the tools I want. RPD, wrench, analyzer, and holofans for easier measuring (bodes)
Walk to bz chamber, set its input to like 10ls. This is because our chamber will need to be low pressure, so we want to slowly feed it.
Set the freezer next to the chamber to as low as it goes
Drag some plasma up to the freezer, wrench it down. This will be what the freezer actually cools, or our coolent for the chamber. Plasma cause it resists temp change quite well
Drag some plasma and n2o to the mixers near the air? supply tank. Set em to be 50/50, since that's what bz needs.
Accidentally open valve before you're done setting up filtering
Forget to grap analyzer, go get it.
Go check chamber's pressure......
Place a filter that feeds into the burn chamber's input (remember to turn that damn pump off). 
Fuck up a few times.
Set the filter going to pull out everything except bz (damn you ghil it's too easy)
Acquire bz.
It's actually a bit too hot right now, bring it down to temp with the other thermomachine.
Drag canister to xeno, turn on
Hit maybe 12% bz, not bad.
```

Took me maybe 9 minutes, and I had some uh, shall we say inefficiencies in my process. 
For what it's worth, this is my second try, and I did formally play atmos like 2 years ago. First go took 15 min or so.

I feel like this could use a wiki guide for what it's worth, mostly so people know about the cooling pipes. 
I don't think it's an overly large thing to ask people to do tho, especially because bz is also required for some research.

Something to note, you mentioned that 1000 moles of bz wouldn't be enough. I checked and what I have worked to sleep some slimes, but I may be missing some use.

2022-06-02 04:08 UTC, LemonInTheDark commented
Being honest with you, my thoughts on sci papers are still about the same as they were like a month ago.
I don't really mind what they block so long as they block something significant. I mostly care about making them more approachable.

Part of that means I want a world where xeno needing bz is solved by xeno asking for/making bz, rather then xeno just having bz roundstart. Cause I want a world where that's a reasonable expectation to have, and the best way I can think of to achieve that is to just A/B test it until we get it right.

I know that atmos can be a very convoluted system, and it's typically explained really poorly. It's very obvious that this new setup needs a good tutorial for instance.
I'm convinced that problem can be at least in theory solved.

Something I'm slightly less sure of is making it fun. I think the thing to shoot for here is something like old 50k rushing, or things of that nature. That or make the work smooth enough that it's not a major commitment.
Not quite sure how to do the first one, mostly cause most of these reactions don't really have a lot of wow factor. I think the second is achievable for BZ, and maybe the first two if you made radballs less 2000k brain'd.

What I don't want to do is lessen up that "pressure". More then the idea of atmos being hard to use I hate the idea of it being pointless. There's so much content in this game that's like this, stuff we added, and then immediately obsoleted. I think of atmos kinda like that, at least before like 2020 or so. 

I'd like to fix that, for both the system and the role. And what you're proposing here is just obsoleting bz production, outside of for the purposes of rcd fabrication, so it's never gonna be something I'm good with. It's a bad pattern. 
That's why I think most experiments should be mandatory. Right now any bad experiments aren't painpoints, they're just ignored. So there's no incentive to improve them, and they just become unused, features that are "in the game" but are never touched.

I'm personally convinced that BZ fab at least is in a good place right now. Maybe I'm wrong about that, and there's no motivation and such, but I much prefer forcing myself/others to fix it to just letting it gather dust on the wall.

2022-06-02 04:08 UTC, closed without merging

2022-06-05 21:25 UTC, Dmeto commented
I might bring this PR up again in a few months once Ordinance has settled down, and there is a need for Bz that is not getting fulfilled. I’m tired of Arguing for this PR it was supposed to be a Xenobio facing change but Ordinance is an issue that I cant debate against and have better things to be working on.