Add dyslexia (illiteracy quirk) as a genetic mutation or disease symptom
tgstation/tgstation pull request #67388
Opened 2022-05-29 11:34 UTC by timothymtorres

## About The Pull Request

This is an expansion of #66648. The illiterate quirk is being added to genetics and virology as side effects named dyslexia.

## Why It's Good For The Game

More ways to gain and interact with the new quirk.

## Changelog

:cl:
add: Add dyslexia (illiteracy quirk) as a genetic mutation or disease symptom.
/:cl:

2022-05-29 11:48 UTC, Time-Green commented
You might be shocked to hear that people with dyslexia can actually read and write

2022-05-29 12:13 UTC, timothymtorres commented
> You might be shocked to hear that people with dyslexia can actually read and write

I have it and I can read and write fine however there are severe forms that can prevent people from being literate.

Not everyone that has Tourette's syndrome curses outloud.  Exaggerating disabilities for SS13 is silly but part of the memes.

2022-05-29 17:22 UTC, SkeletalElite commented
Maybe make it a brain trauma instead of a genetic mutation and call it alexia

2022-05-29 18:03 UTC, tralezab commented
Your pr does not do what it says it does.

2022-05-29 20:19 UTC, timothymtorres commented
Dyslexia is already a brain trauma from the original illiteracy PR.  I'll be adding the disease symptom later tonight.

2022-05-30 02:47 UTC, ATH1909 commented
> > You might be shocked to hear that people with dyslexia can actually read and write
> 
> I have it and I can read and write fine however there are severe forms that can prevent people from being literate. Not everyone that has Tourette's syndrome curses outloud. Exaggerating disabilities for SS13 is silly but part of the memes.

maybe label it as "severe dyslexia" or "crippling dyslexia", then?

2022-06-02 15:47 UTC, SuperNovaa41 requested changes

2022-06-03 03:17 UTC, timothymtorres commented on code/datums/diseases/advance/symptoms/confusion.dm
> +	return TRUE
Refactored with 047fa9004439664c634f84a8dd06895e6d0e1149

2022-06-14 05:04 UTC, merged