Venus human trap fix 3.0: Allow ghosts to possess them even when obscured, use better spawning system
tgstation/tgstation pull request #67418
Opened 2022-05-30 16:44 UTC by RandomGamer123

## About The Pull Request
Moves venus human traps to use the /obj/effect/mob_spawn/ghost_role/ system of spawning similar to things like spiders. Effects of this include: Having a notification to ghosts when one is ready to be spawned, having venus human traps respect role bans, and allowing them to be possessed from the ghost role menu.
Also adds poll ignore and role defines for venus human traps.

## Why It's Good For The Game
![ThingAN1953](https://user-images.githubusercontent.com/31096837/171025068-19d8b300-366c-4a69-9032-241ce98baae3.png)

To clarify in more detail: Venus human traps spawn by flowering kudzu (with a 10% chance). However, they spawn immediately under the kudzu and can't be clicked on (even with the alt-click menu), so they can only be possessed by a ghost only if the kudzu above them gets destroyed or they get moved out of the kudzu.
Instead of just fiddling around with layers, moving venus human traps to the same ghost role system used by other ghost roles helps centralize them and make it more obvious that a) you can possess them to begin with, and b) how to possess them

## Changelog

:cl: RandomGamer123, bug originally reported by Murmic#2120 on Discord
qol: Makes it more clear that venus human traps can be possessed in the first place
fix: Makes it so that venus human traps can be possessed even if they are underneath kudzu
refactor: Moved venus human traps to the same spawning system that spiders used, now, a notification pops up when one is ready to be possessed, and you can possess it by using the ghost role menu, the link in chat, or by clicking on the notification
admin: Venus human traps now respect role bans (for ROLE_LAVALAND as its the default for ghost roles)
/:cl:

2022-05-31 00:43 UTC, BlueMemesauce commented
Can you do the same thing for spider eggs too?

2022-05-31 00:47 UTC, RandomGamer123 commented
> Can you do the same thing for spider eggs too?

What do you mean by "the same thing"? Most of this code is based on spider egg code to begin with, so they already have most of the features here

2022-05-31 02:14 UTC, BlueMemesauce commented
I thought spider eggs had a similar problem nevermind then

2022-06-08 22:12 UTC, RandomGamer123 commented
@tralezab I guess since you merged the previous kudzu-related PR

2022-06-18 23:24 UTC, LemonInTheDark requested changes
> Venus human traps now respect role bans (for ROLE_LAVALAND as its the default for ghost roles)

Is it default for ghost roles like spiders? or things that are actually on lavaland like golems

2022-06-18 23:24 UTC, LemonInTheDark commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +		spawner = null
Why do we need to clear the flower_bud variable? shouldn't qdeling the spawner do that?

2022-06-18 23:24 UTC, LemonInTheDark commented on code/modules/mob_spawn/ghost_roles/venus_human_trap.dm
> +		flower_bud = null
similar question here

2022-06-18 23:24 UTC, LemonInTheDark commented on code/modules/mob_spawn/ghost_roles/venus_human_trap.dm
> +	if(!.)
Good protection against href exploits, +1

2022-06-19 15:20 UTC, RandomGamer123 commented
> > Venus human traps now respect role bans (for ROLE_LAVALAND as its the default for ghost roles)
> 
> Is it default for ghost roles like spiders? or things that are actually on lavaland like golems

```
///which role to check for a job ban (ROLE_LAVALAND is the default ghost role ban)
	var/role_ban = ROLE_LAVALAND
```
And looking at the code, ROLE_LAVALAND is also used for things like golems and fugitive hunters

> Why do we need to clear the flower_bud variable? shouldn't qdeling the spawner do that?

After testing this, yes this is not needed and removing it does not cause hard deletes.

2022-06-27 23:35 UTC, RandomGamer123 commented
Bump, @LemonInTheDark if you would want to take a look at this again now you're back

2022-07-07 03:54 UTC, JohnFulpWillard commented on code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
> +		spawner = null
You think we can use QDEL_NULL here instead?

2022-07-13 18:39 UTC, RandomGamer123 commented
Bump to stop stale

2022-07-21 09:22 UTC, merged