[MDB Ignore] Port over Zoomba Cyborg sprite
tgstation/tgstation pull request #67465
Opened 2022-06-01 21:16 UTC by Mooshimi

## About The Pull Request
Ports cyborg sprites in the "Zoomba" model from Skyrat for:

<details><summary>- Janitor</summary>
<p>

<img src="https://user-images.githubusercontent.com/85910816/177429088-164c1bcd-e6eb-4de1-88f1-8b564d50ddfb.png" alt="image" style="max-width: 100%;">

</p>
</details>
( Credit for sprites to [Verkister](https://github.com/Verkister) and [Very-Soft](https://github.com/Very-Soft).  ) 

## Why It's Good For The Game

More cyborg icon is good.

(not the janitor sprite)
![dreamseeker-17 14 41 458](https://user-images.githubusercontent.com/85910816/171503035-3567eede-1f86-4176-93ba-18731db8d1c1.png)

## Changelog

:cl: Mooshimi, Sprites by Verkister and Very-Soft
add: Ported in Zoomba sprite for janiborgs
/:cl:

2022-06-01 21:17 UTC, thgvr commented
I pray there is a god.

2022-06-01 21:18 UTC, Mooshimi commented
I did a good amount of testing to make sure the sprites work alright with the lights!

2022-06-01 21:33 UTC, MrMelbert requested changes
I'd be ok with these if you limit it to just janiborg and maybe the service model.

2022-06-01 22:02 UTC, Jolly-66 commented
Don't forget to attribute your CL for the spriters

2022-06-01 22:31 UTC, LemonInTheDark commented
More reskins?

2022-06-01 22:42 UTC, Iamgoofball commented
These need to be way, way bigger to click on. They're already an issue at Skyrat due to sprite size. Give them an enlarged hitbox or something.

2022-06-01 23:26 UTC, Iamgoofball commented
>Do you still think this with only the janitor sprite included??

yes

2022-06-02 00:34 UTC, Mooshimi commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +		"Tophat" = list(SKIN_ICON_STATE = "tophat", special_light_key = NONE, SKIN_HAT_OFFSET = INFINITY),
The light sprite didn't work with the SKIN_LIGHT_KEY but the var created by Fikou in the refactor special_light_key seen at the top of the file worked fine, I updated these thinking they had the same goal in mind

2022-06-02 00:35 UTC, Mooshimi commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +	robot_owner.pixel_y = base_y + rand(-13, 7)
the image above with the firehat, the cyborg is low on the tile.

2022-06-03 00:44 UTC, Mooshimi commented
> These need to be way, way bigger to click on. They're already an issue at Skyrat due to sprite size. Give them an enlarged hitbox or something.

So how in the world would you do this, my boy?

2022-06-03 01:43 UTC, Iamgoofball commented
254 alpha pixels around it in the shape of a normal cyborg

2022-06-06 04:03 UTC, LemonInTheDark commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +		"Tophat" = list(SKIN_ICON_STATE = "tophat", special_light_key = NONE, SKIN_HAT_OFFSET = INFINITY),
It won't actually
`list(variablename = "value")`
is parsed as `list["variablename"] = value` in what the reference calls a "convenient shorthand"
![image](https://user-images.githubusercontent.com/58055496/172092571-a669dd99-e26d-4875-9b4e-11ae75f58618.png)

2022-06-06 15:25 UTC, Dorsisdwarf commented
Gonna be real this looks like a robotics bot, not a cyborg.

2022-06-06 16:40 UTC, davethwave commented
Sprite definitely needs to be larger, too many players would choose this just for the smaller size to make getting flashed or hurt harder.

2022-06-07 19:10 UTC, Mooshimi commented on code/modules/mob/living/silicon/robot/robot_model.dm
> +		"Tophat" = list(SKIN_ICON_STATE = "tophat", special_light_key = NONE, SKIN_HAT_OFFSET = INFINITY),
Reverted the unrelated borgs i touched but the roomba sprite did not work with lights using SKIN_LIGHT_KEY during my testing so I will keep that as-is unless given further reason

2022-06-28 02:52 UTC, Twaticus approved these changes
i didnt realize this was up for so long, apologies

2022-07-01 05:36 UTC, JohnFulpWillard commented
this looks way closer to a bot than a Cyborg to me, I personally would rather see this as some version of the cleanbot instead.

2022-07-01 06:09 UTC, Twaticus commented
yeah i agree with john, itd be cute as a reskin for the various bots. 
but as an easily accessible playable mob thats meant to replace a normal human? that sounds like a bad idea. theyre ridiculously small and no alpha pixels to expand the hitbox will remedy that

2022-07-01 19:19 UTC, Iamgoofball commented
we literally expanded the hitbox with alpha pixels and players like these skins for cyborgs, why don't we try it before writing it off

2022-07-11 18:36 UTC, JohnFulpWillard commented
> we literally expanded the hitbox with alpha pixels and players like these skins for cyborgs, why don't we try it before writing it off

Their hitbox was irrelevant to my point.

You can feel free to re-PR this as a bot/bot-skin, rather than a cyborg. I don't think Borgs, who have an entire toolset including a flash and the ability to pick people up, should look like small bots that can only move around and clean stuff.

2022-07-11 18:36 UTC, closed without merging