Lets people light cigarettes in lava.
tgstation/tgstation pull request #67587
Opened 2022-06-06 22:06 UTC by Wallemations

## About The Pull Request
Lets people light cigarettes in lava. There's only a _small_ chance of burning your entire arm off, so it's fine!

## Why It's Good For The Game
I was surprised when I attempted to light a cigarette in lava and nothing happened. Even the plasmacutter has an interaction with cigs, but not lava. This fixes that.

## Changelog

:cl: Wallem
add: For the brave smokers out there, legends tell of a new lighting technique involving molten stone from the planet's core. Only the brave are advised to attempt this.
/:cl:

2022-06-06 22:44 UTC, MrMelbert requested changes

2022-06-06 23:03 UTC, Wallemations commented
done

2022-06-07 01:04 UTC, Colovorat commented
basic chance of failing is 25, and with clumsy it's 50% if i understand it correctly?

2022-06-07 01:50 UTC, Wallemations commented
> basic chance of failing is 25, and with clumsy it's 50% if i understand it correctly?

yes, playing with lava is a dangerous game.

2022-06-07 05:38 UTC, ArcaneDefence commented
Can you do something to account for icemoon's liquid plasma, as that's `/turf/open/lava/plasma`, but it's not hot?

2022-06-07 05:56 UTC, Colovorat commented
> > basic chance of failing is 25, and with clumsy it's 50% if i understand it correctly?
> 
> yes, playing with lava is a dangerous game.

add achievment for destroying your arm with lava trying to light cig?

2022-06-07 18:06 UTC, Sealed101 commented
how will this work with tk

2022-06-07 18:10 UTC, Wallemations commented
> how will this work with tk

Idk how ANYTHING works with TK
I don't know what else might check for TK, or how it does it.

2022-06-07 18:52 UTC, Wallemations commented
> > Can you do something to account for icemoon's liquid plasma, as that's `/turf/open/lava/plasma`, but it's not hot?
> 
> I'm not really sure how I'd make something not work for a subtype. I could try I guess?

```
/turf/open/lava/plasma/attackby(obj/item/I, mob/user, params)
	var/obj/item/reagent_containers/glass/C = I
	if(C.reagents.total_volume >= C.volume)
		to_chat(user, span_danger("[C] is full."))
		return
	C.reagents.add_reagent(/datum/reagent/toxin/plasma, rand(5, 10))
	user.visible_message(span_notice("[user] scoops some plasma from the [src] with \the [C]."), span_notice("You scoop out some plasma from the [src] using \the [C]."))
```
The plasma doesn't call their parent when hit by any item, so it **_should_** be fine.

2022-06-08 00:38 UTC, merged