Fixes Reagent Dispensers Not Removing Reagents
tgstation/tgstation pull request #67611
Opened 2022-06-07 23:03 UTC by 13spacemen

Fixes https://github.com/tgstation/tgstation/issues/67329
tested and works with fuel, large fuel, foam, water, large water, etc.
stops leaking reagents at  =<10 reagents

:cl:
fix: Reagent dispensers will actually remove reagents upon leaking
/:cl:

2022-06-08 02:37 UTC, tf-4 commented on code/modules/reagents/reagent_dispenser.dm
> +	//volume modifier for reagent procs
Autodoc

2022-06-08 02:37 UTC, tf-4 commented on code/modules/reagents/reagent_dispenser.dm
> +	var/volumemod
```suggestion
	var/volume_mod
```

2022-06-16 08:18 UTC, Mothblocks requested changes

2022-06-16 08:18 UTC, Mothblocks commented on code/modules/reagents/reagent_dispenser.dm
> +		return TRUE
```suggestion
		return TRUE
	return FALSE
```

```suggestion
```

Generally, everything should return a value or shouldn't return a value. Pick one.

2022-06-16 08:18 UTC, Mothblocks commented on code/modules/reagents/reagent_dispenser.dm
> +	tank_leak()
```suggestion
	tank_leak()

```

2022-06-16 08:40 UTC, merged