Clarify guidelines around use of role pings in discord
tgstation/tgstation pull request #67639
Opened 2022-06-08 22:26 UTC by optimumtact

This apparently  is not clear to people.
cc @Mothblocks @ninjanomnom @MrStonedOne

2022-06-08 22:32 UTC, Ryll-Ryll commented
Requires another grammatical pass

2022-06-08 22:32 UTC, Ryll-Ryll requested changes
Requires another grammar pass

2022-06-08 22:41 UTC, san7890 reviewed
grammar pass i guess

feel free to disregard all of this if it's not what you're looking for

2022-06-08 22:41 UTC, san7890 commented on .github/CONTRIBUTING.md
> +## Using the maintainer role ping in discord
```suggestion
## Using the Maintainer Role Ping in Discord
```

2022-06-08 22:41 UTC, san7890 commented on .github/CONTRIBUTING.md
> +This role is pingable as a compromise reached with the server host mso over the auto staling system. It should be used only to ping maintainers when your PR has had the stale label applied. Using it
```suggestion
This role `@Maintainer` is pingable as a compromise reached with the server host MrStonedOne over the auto-staling system we presently have in the codebase. It should be used only to ping Maintainers when your PR has had the "Stale" label applied. Using it before then can be met with escalating timeouts and referral to /tg/station's Discord moderators for further infractions.
```

2022-06-08 22:41 UTC, san7890 commented on .github/CONTRIBUTING.md
> +Feel free to engage in general in coding general without the role ping, before your PR goes stale to build interest and get reviews.
```suggestion
Feel free to engage and obtain general feedback in the Coding General channel without the role ping before your PR goes stale to build interest and get reviews.
```

2022-06-08 22:51 UTC, Mothblocks approved these changes

2022-06-09 18:45 UTC, MrStonedOne commented on .github/CONTRIBUTING.md
> +This role `@Maintainer` is pingable as a compromise reached with the server host MrStonedOne over the auto-staling system we presently have in the codebase. It should be used only to ping Maintainers
```suggestion
This role `@Maintainer` is pingable as a compromise reached with the server host MrStonedOne over the auto-stale system we presently have in the codebase. It should be used only to ping Maintainers when your PR has had the "Stale" label applied. Using it before then can be met with escalating timeouts and referral to /tg/station's Discord moderators for further infractions.
```

staling is more grammatically correct, but even after a nights sleep it kept reading it as scaling or stalling.

maybe my brain just hates the word stale.

2022-06-09 18:45 UTC, MrStonedOne approved these changes

2022-06-10 01:54 UTC, merged