Add magic reactions to hydroponics plants
tgstation/tgstation pull request #67724
Opened 2022-06-12 04:32 UTC by timothymtorres

## About The Pull Request

This gives magical reactions when plants are hit by the following spells:
- Bolt of resurrection - Heals and revives plants
- Bolt of death - Kills plants (and weeds)
- Bolt of polymorph - Mutates plant into a random seed 

## Why It's Good For The Game

Seeing a bunch of botanists hunt down a wizard with hatchets for loot will be hilarious.

## Changelog

:cl:
add: Add magical reactions when hydroponics plants are hit with polymorph, death, or resurrection magic.
/:cl:

2022-06-12 05:06 UTC, MrMelbert requested changes

2022-06-12 06:50 UTC, datorangebottle commented
>Seeing a bunch of botanists hunt down a wizard with hatchets for loot will be hilarious.

But none of these interactions will ever happen because of the staff nerf that made it so only wizards can properly use the staffs.

2022-06-12 07:56 UTC, the-orange-cow commented
If it weren't for the fact that the entire job is about to get nuked I'd say it would be cool to apply these to xenobio as well.

2022-06-12 10:42 UTC, timothymtorres commented on code/modules/hydroponics/hydroponics.dm
> +	if(!myseed || plant_status == HYDROTRAY_PLANT_DEAD || (!polymorph && !LAZYLEN(myseed.mutatelist))
Applied with https://github.com/tgstation/tgstation/pull/67724/commits/3f541aa73913f24c1db7b0de1341f1c05e1a817b

2022-06-12 10:43 UTC, timothymtorres commented on code/modules/projectiles/projectile/magic.dm
> +		if(target.myseed.get_gene(/datum/plant_gene/trait/anti_magic))
Refactored with https://github.com/tgstation/tgstation/pull/67724/commits/9baaca88858df241b9b70bfd6287158b41d86a9c

2022-06-12 10:43 UTC, timothymtorres commented on code/modules/projectiles/projectile/magic.dm
> +		return
Refactored with https://github.com/tgstation/tgstation/pull/67724/commits/9baaca88858df241b9b70bfd6287158b41d86a9c

2022-06-12 10:43 UTC, timothymtorres commented on code/modules/projectiles/projectile/magic.dm
> +	if(!isliving(target) && !istype(target, /obj/machinery/hydroponics))
Refactored with https://github.com/tgstation/tgstation/pull/67724/commits/9baaca88858df241b9b70bfd6287158b41d86a9c

2022-06-12 10:44 UTC, timothymtorres commented on code/modules/projectiles/projectile/magic.dm
> +	if(!isliving(target) && !istype(target, /obj/machinery/hydroponics))
Refactored with https://github.com/tgstation/tgstation/pull/67724/commits/9baaca88858df241b9b70bfd6287158b41d86a9c

2022-06-13 00:44 UTC, Shadowflame909 commented
> If it weren't for the fact that the entire job is about to get nuked I'd say it would be cool to apply these to xenobio as well.

the slimes are staying. So polymorph turning slimes into other slimes could work

But then again, regular polymorph can already make any type of slime. So that'd be a big polymorph nerf for anyone trying to turn back into a human/something-else if they get slimed

2022-06-17 08:31 UTC, IndieanaJones commented
I would probably say that anything related to xenobio is probably out of scope for this PR, and maybe best to be handled after the pending rework

2022-06-23 04:02 UTC, merged