Fixes holographic swords doing a clumsy check
tgstation/tgstation pull request #67743
Opened 2022-06-12 23:41 UTC by SuperNovaa41

The holographic sword was doing a clumsy check when it opens, meaning it
was hurting people... as a holograph

Fixes https://github.com/tgstation/tgstation/issues/67739

:cl:
fix: Fixes holographic swords dealing damage to clumsy people.
/:cl:

2022-06-12 23:51 UTC, Shadowflame909 commented
Only clowns can find a way to kill themselves with a holographic sword

2022-06-13 00:17 UTC, Mothblocks commented
Random seed probably is consistently hitting the .4% chance (on one of them)

https://github.com/tgstation/tgstation/pull/67746

2022-06-13 00:19 UTC, Mothblocks commented
Nvm you just clicked the wrong button to rerun

2022-06-14 05:20 UTC, MrMelbert requested changes
keep the clumsy check on holo-e-swords just fix transforming item clumsiness causing brute regardless of damage type

2022-06-24 06:32 UTC, SuperNovaa41 commented
Too lazy to fix

2022-06-24 06:32 UTC, closed without merging