Limits pill names to 30 characters
tgstation/tgstation pull request #67744
Opened 2022-06-12 23:55 UTC by SuperNovaa41

Limits pill names to be no more than 30 characters. Currently there is no limit and it can be used to flood chat with extremely lengthy names.

Fixes https://github.com/tgstation/tgstation/issues/67738

## Changelog

:cl:
fix: Pill names now have a cap at 30 characters to prevent chat spam.
/:cl:

2022-06-13 00:22 UTC, jehnicat commented
make it match the character limit of the chem master 3000 for consistency.

2022-06-13 01:08 UTC, MrMelbert requested changes
What they said, use `MAX_NAME_LEN`

2022-06-13 02:20 UTC, MrMelbert approved these changes

2022-06-14 05:35 UTC, merged

2022-06-14 20:33 UTC, jehnicat commented
Reflect the new character limit in the actual UI of the chem press. At the moment it shows no indication of a character limit or limits you from making a too-long name at all.