Fixes space tackling + mothcurity buff
tgstation/tgstation pull request #67791
Opened 2022-06-15 04:25 UTC by GuillaumePrata

## About The Pull Request
Space tackling was a silly but quite efficient means of space travel that is fixed here.
I tried to add a check so people can still tackle in no gravity if they can push an object like a wall or locker (the standard no gravity movement behavior) but after 2 hours of trying it I just got tired, another day perhaps...

To not just completely remove tackling inside the station when the gravity falls, you can still tackle if you have wings and atmosphere to use as propulsion.

Just remember that since tackling distances are extended in no gravity... don't miss your target if you like your spine...

And since I was here buffing mothcurity indirectly, I though it would be a nice time to push tackling to interact with a few more variables so:
1 - Moths with wings will have a better tackle (+2, same as riot armor or gigantism mutation)
2 - Moths without or burnt wings will have a worse tackle (-2, same as dwarfism or clumsy)
3 - Fly people have a higher chance of breaking their spine after splatting themselves into a window/wall (+6 same as clumsy)

## Why It's Good For The Game
The bug fix part is well... a bug fix...

As I said, completely disabling tackling if the gravity falls would make an already niche and dangerous, but extremely funny, tool that security has even worse.
Mothcurity is probably the worst species to play as security as your fellow officer's flashbangs will ruin your day, with this change they have a small niche above other officers, just like how plasmamen is an interesting species to play as security with their unique pros and cons. (horrible at direct confrontation against antags/resilient against environmental antags).

## Changelog

:cl: Guillaume Prata
fix: You can no longer tackle in deep space or if you are not affected by gravity unless you have wings and enough atmosphere, same values that allow flight.
balance: Moths get modifiers to their tackling values if they have/don't have wings.
balance: Fly people don't like splatting themselves on windows/walls and have a higher chance to get a bad result from that.
/:cl:

2022-06-15 04:28 UTC, SinfulBliss commented
Moths having a +2 tackle buff is a lot, basically equivalent to them wearing riot and having gorilla gloves with normal grippers. It also doesn't really make sense, moths are soft bugs why do they have good tackles?

2022-06-15 04:38 UTC, GuillaumePrata commented
> Moths having a +2 tackle buff is a lot, basically equivalent to them wearing riot and having gorilla gloves with normal grippers. 

No? It means that a Moth without a riot suit will be as good as another species with a riot suit, I don't know why you're bringing gloves into the math since they have their own set of unique modifiers.

> EDIT: Also, plasmamen are worse to play as sec than moths. I don't see why moths are special in getting buffed.

As I said, plasmamen suck at combat but they are still immune to a lot of the dangers of indirect combat like atmos or diseases.
Plasmamen have passive pros and passive cons, now moths have active pros and passive cons ONLY if they opt in to using tackling and open themselves to all the risks of tackling.

2022-06-15 05:06 UTC, OneAsianTortoise commented
~~Moth tackle buff only to the targets holding flashlight~~

2022-06-15 05:22 UTC, Palpetinus commented
Oh oh, species discussion, Ethereals take a whopping 25% more Brute and are therefore even worse security!!

Jokes aside, +2 might be a tad too much buuut calling them "soft bugs" isn't really valid either. You know what bugs have? Exoskeletons. You're having up to 100kg of pure chitin flying into your face.
It's funny and gimmicky, I don't think we'll see a tacklemoth meta emerge from this.

2022-06-15 05:34 UTC, Shadowflame909 commented
Im just hoping this change will see gorilla gloves actually used.

People don't like launching themselves at the danger and potentially getting stunned if they miss

2022-06-15 07:11 UTC, Mooshimi commented
> Im just hoping this change will see gorilla gloves actually used.
> 
> People don't like launching themselves at the danger and potentially getting stunned if they miss

I doubt this, since if you're wearing the gloves and try to throw something, you tend to go flying after it. 
This has actually caused my death in maintenance while trying to throw a body,  I directly flew into a wall and was easy pretty for the heretic I had tried to hit.
It's too much of a risk to wear them for a lot of sec frankly.

2022-06-15 13:41 UTC, SinfulBliss commented
> As I said, plasmamen suck at combat but they are still immune to a lot of the dangers of indirect combat like atmos or diseases. Plasmamen have passive pros and passive cons, now moths have active pros and passive cons ONLY if they opt in to using tackling and open themselves to all the risks of it.

Then why is a moth buff being tagged on in an unrelated tackle bugfix? The issue is tackles let you traverse space. Moths have nothing to do with this.

Moths being weak to flashes is simply part of playing moth, and it makes sense for their species. They already get passive buffs like their wings allowing them to fly over holes and the negation of fall damage. A riot-armor level tackle boost doesn't make sense and just seems to be giving them special treatment. 

Plasmamen absolutely have it worse as sec - taking 2x brute damage, needing plasma internals, and getting husked after being stripped or decapped - is worlds apart from taking a friendly fire flashbang on occasion.

2022-06-15 18:48 UTC, rellyreri commented
>  taking a friendly fire flashbang on occasion.

actually moths can still be flashed with normal flashes, which is why you rarely see mothsec because anyone with a flash can instantly chainstun them. they also can't use the stationary flashers or flashbangs

2022-06-15 21:14 UTC, GuillaumePrata commented
> Then why is a moth buff being tagged on in an unrelated tackle bugfix?

Don't even know why you're bringing this point when the PR is clearly labeled as balance and already explained on the PR.

> giving them special treatment

Yes, that is what a balance change is, you give something to a species to change how people act in game.
Now when you see Officer Flufflyson you can still walk to them, grab, flash and win the fight in 1 second if you have a flash but if you don't and know that Moths are better at tackling, you can bait them into doing that for your advantage.

> Plasmamen absolutely have it worse as sec... friendly fire flashbang on occasion

This is my point, what you pointed out about plasmamen are all generic issuee to any job they play as.
Flashbang is a tool that you lose if you play as Moth, it's a job unique issue, fighting against a Moth Officer will be different than other species by that alone which is good IMO and expanded on this PR.

2022-06-15 23:52 UTC, SinfulBliss commented
> > Then why is a moth buff being tagged on in an unrelated tackle bugfix?
> 
> Don't even know why you're bringing this point when the PR is clearly labeled as balance and I already explained why on the PR.
> 
Because it’s two completely unrelated issues. There’s a bug/exploit fix for tackles which is an objective, unarguable issue that needs a fix. And then there is the subjective change that moths need a buff as security. The first issue needs to be fixed and shouldn’t be tied to buffing moths as a result.

2022-06-16 02:01 UTC, GuillaumePrata commented
> Because it’s two completely unrelated issues...

And I already explained my reasoning in the PR body, explained why I couldn't make the fix fully atomic making it a clearly labelled balance PR from the get go and why I'm using this indirect buff my fix caused to propose a direct buff.

If you have an issue with the moth +2 buff, talk about it directly instead of going on a tangent about gorilla gloves (a complete different math within tackling), moths being soft (lol), plasmamen being worst sec in your opinion so moths don't deserve changes, etc.

2022-06-16 14:13 UTC, SkeletalElite commented
+2 is a pretty big tackle buff for just existing basically, being in riot armor and tackling isn't strictly benefical either since riot armor increases the stamina cost of tackling.

2022-06-17 01:32 UTC, GuillaumePrata commented
The max cap of tackling is 5 (technically between 2 and 8 since there is a rng window of -3 to +3) against a target without modifiers, these values are not as meaningful until you stack all the way to 8 and it becomes a consistent result (rocket gloves give 7 alone), the easy way to compare this buff is against a human with the same exact gear to see the difference.

On this example what is consistent is that moths will often do 1 tier of tackle above other species on the middle tier of tackles.
The window of values between tackles are on values of 2 (-1 or 0 for a decent hit, 1 or 2 for solid hit, 3 or 4 for a good hit, 5 to infinity for the best tackle)

What I mean is that if Moths have only +1, on more than 50% of their tackles it will be exact the same as any other species.
+2 is the minimum value to give to a tackle modifier or it often achieves nothing.

2022-06-17 02:07 UTC, ShizCalev requested changes
atomize please.

2022-06-17 02:08 UTC, GuillaumePrata commented
Sure

2022-06-17 02:08 UTC, closed without merging