Fixes wizard's spellbook becoming inaccessible
tgstation/tgstation pull request #67844
Opened 2022-06-17 17:37 UTC by CoffeeDragon16

## About The Pull Request

Wizard spellbooks have a mechanic that binds the book to their first user, so other people can't use it. However, it binds the spellbook to the wizard's body, not their mind. This makes it so the spellbook is inaccessible to the wizard after becoming a lich or mindswapping, which doesn't seem to be intended. The PR just makes the spellbook check for the mind, not the body, to fix this. Fixes #64927 and #56216

## Why It's Good For The Game

Wizards shouldn't be punished for using their own tools, nor does it seem to be said anywhere that mindswaps and lichdom make your spellbook inaccessible. Fixes the bug.

## Changelog

:cl:
fix: switching bodies, such as becoming a lich or mindswapping will no longer revoke a wizard's access to their spell book
/:cl:

2022-06-17 18:01 UTC, MrMelbert requested changes
the `owner` var on the book is still casted to `/mob/living/carbon/human`, be sure to change that 

Also you may want to check that the user had a mind before binding the book, juuuust in case.

2022-06-17 18:10 UTC, tralezab requested changes

2022-06-17 18:10 UTC, tralezab commented on code/modules/antagonists/wizard/equipment/spellbook.dm
> +		owner = user.mind
owner is typecasted as `var/mob/living/carbon/human` and user.mind is `/datum/mind`.
Retype owner, dmdoc it, and make sure to check the rest of the code for what changing owner might matter for.

2022-06-21 15:04 UTC, merged

2022-07-19 17:05 UTC, timothymtorres commented
@CoffeeDragon16 please make sure you [autolink fixed issues properly](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

That means when you are fixing multiple issues you need to either do it like this:

Fix #56216 
Fix #64927

Or like this:

Fix #56216 Fix #64927