Roller beds and bodybags are folded with right click now
tgstation/tgstation pull request #67893
Opened 2022-06-20 13:44 UTC by GuillaumePrata

## About The Pull Request
This, and you can cut the bodybag tag with any sharp object too!

## Why It's Good For The Game
MouseDrop is just pain and is probably one small annoyance that pushes people to not use roller beds and bodybags as much... well they use the bluespace one for murder but...

The only way to remove a tag from a bodybag was a wirecutter, this cuts down on doctors needing to loot tools for something minor and let them use their scalpel instead.

## Changelog

:cl: Guillaume Prata
qol: You fold roller beds and bodybags with a right click instead of click and dragging into you.
qol: You can use any sharp object to cut a bodybag's tag instead of being forced to use a wirecutter.
/:cl:

2022-06-20 13:57 UTC, Shadowflame909 commented
I hope we get a funny CL like "A lazy doctor has realized they could cut bodybag tags with a scalpels and other sharp items lying around and this method has spread to your station."

2022-06-20 19:11 UTC, YakumoChen commented
I didn't even know bodybagd had tags. The more you know.

2022-06-21 04:15 UTC, MrMelbert requested changes

2022-06-21 11:39 UTC, GuillaumePrata commented on code/game/objects/structures/crates_lockers/closets/bodybag.dm
> +		return
Done, tested and it works in game without issues but would be nice to know if I missed something else.

2022-06-21 11:39 UTC, GuillaumePrata commented on code/game/objects/structures/beds_chairs/bed.dm
> +/obj/structure/bed/roller/attack_hand_secondary(mob/user, list/modifiers)
Ditto

2022-06-22 16:33 UTC, CoffeeDragon16 commented
Don't forget wheelchairs, those fold up too

2022-07-07 03:47 UTC, merged

2022-07-10 03:28 UTC, Mothblocks commented
This should have had contextual screentips.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/beds_chairs/bed.dm
> +		return FALSE
`attack_hand_secondary` does not return TRUE/FALSE.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/beds_chairs/bed.dm
> +		return FALSE
`attack_hand_secondary` does not return TRUE/FALSE.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/beds_chairs/bed.dm
> +	qdel(src)
This means `..()` is being returned from `attack_hand_secondary`, which it never should be.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/beds_chairs/bed.dm
> +		return
This should be `return .` or `return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN` as per dot style guidelines.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/crates_lockers/closets/bodybag.dm
> +		return
`attack_hand_secondary` does not return TRUE/FALSE.

2022-07-10 03:29 UTC, Mothblocks commented on code/game/objects/structures/crates_lockers/closets/bodybag.dm
> +	qdel(src)
This means `..()` is being returned from `attack_hand_secondary`, which it never should be.