Ladders take left/right clicks to go up or down instead of a radial menu now
tgstation/tgstation pull request #67913
Opened 2022-06-21 15:55 UTC by Ghommie

## About The Pull Request
See the title. You now left click to climb up and right click to climb down a ladder. A delay of 1 second has also been added, since otherwise it'd take only one click to immediately move vertically and would be much more spammable.

Ghosts still use the old radials, because their right clicks are bound to the default byond popup menu.

## Why It's Good For The Game
QOL, bringing down the clicks necessary to climb a ladder up and down from 2 to 1. It has been tested on a local server.

## Changelog

:cl:
qol: Ladders take left/right clicks to go up or down instead of a radial menu now.
balance: Because otherwise it'd be way more spammable, a delay of 1 second has been added (also it makes sense).
/:cl:

2022-06-21 16:19 UTC, Colovorat commented
> Seems like this might be a little unintuitive. Does it mention on examine?

it doesn't

2022-06-21 19:01 UTC, Ghommie commented
> Contextual screentip is definitely necessary

Yeah, sounds like a good idea.

>though I would agree that I don't think this is very intuitive

I could argue the effort to understand how it works is also minimal and having a radial menu for something that won't have more than two options is not much better overall.
But yes, there will be some struggle as older player uncommit what they had previously memorized, but it'll be nothing compared to deconstruction and tool_acts of several structures currently being split between left and right clicks without much of a common denominator for each, or the change from intents to combat mode.

Also, I'm marking this as a draft until I've time to fix the code smells and implement the screentip suggestion, which probably won't be happening before the day after tomorrow.

2022-06-21 19:33 UTC, Mothblocks commented
If you want a weird idea, I think the best way is actually:

1. Left click keeps radial (thus adding zero learning requirement for new players)
2. Double click goes up
3. Right click goes down

2022-06-21 23:22 UTC, Mothblocks commented
I would definitely promote my concern, yeah. I really don't want to add an extra learning step here.

2022-06-22 03:39 UTC, MrDoomBringer commented
@Mothblocks Right clicking is the secondary action. New players will figure this out incredibly quickly and apply it to ladders intuitively. 

Having the screen tip at the top is more than enough. New players will learn very quickly to look up at those if they don't know how to work something. If you're really insistent, have a balloon alert appear when someone tries to left-click up a top-floor ladder telling them "Hey you're at the top floor already, right-click to go down"

Having a double-click action and a radial menu AND a right click action is ridiculous.

2022-06-22 07:20 UTC, Mothblocks commented
> If you're really insistent, have a balloon alert appear when someone tries to left-click up a top-floor ladder telling them "Hey you're at the top floor already, right-click to go down"

Okay I'm fine with that

2022-06-22 18:37 UTC, ATH1909 commented
how will this affect zombies, borgs, simplemobs, etc.?

2022-06-23 21:48 UTC, Ghommie commented
> will this make romerol zombies unable to climb ladders? were they unable to climb ladders before this PR?

You can use ladders while holding items, so unless the abstract item that's zombie claws had been changed for the worse, they should be able to use ladders.

2022-06-23 23:50 UTC, Ghommie commented
Ok, I've added screen context, examine info and balloon messages as suggested, and radial menus to help move through 3+ stories tall ladders. It should be now ready for an actual code review.

2022-06-24 09:21 UTC, Mothblocks commented
> You can use ladders while holding items, so unless the abstract item that's zombie claws had been changed for the worse, they should be able to.

Can you double check this? Not for zombies but just for having items in your hands. `attack_hand_secondary` isn't called when you have something in your hand, for instance.

2022-06-24 09:21 UTC, Mothblocks commented
Oh wait nevermind I see you're using `attack`

2022-06-24 09:22 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +/obj/structure/ladder/attack_slime(mob/user, list/modifiers)
Can you replace these with some more core `attack_secondary`? I want to get rid of all the RIGHT_CLICK checks.

2022-07-05 14:25 UTC, Ghommie commented
Ok, I've had to refactor unarmed attack code a little to fit your request in without filling the file with copypasta.
Due to this fact, until I test and confirm it's working as intended this is still a draft PR, but feel free to review the design.

2022-07-12 23:31 UTC, Ghommie commented
Ok, it should be ready now.

2022-07-17 08:30 UTC, Mothblocks requested changes

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +/atom/proc/attack_animal_secondary(mob/user, list/modifiers)
Doc-comment

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +		CRASH("resolve_right_click_attack did not return a SECONDARY_ATTACK_* define.")
```suggestion
		CRASH("resolve_right_click_attack (probably attack_hand_secondary) did not return a SECONDARY_ATTACK_* define.")
```

Be useful

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +/atom/proc/attack_alien_secondary(mob/living/carbon/alien/user, list/modifiers)
Doc-comment

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +/atom/proc/attack_larva_secondary(mob/user, list/modifiers)
Doc-comment

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +/atom/proc/attack_slime_secondary(mob/user, list/modifiers)
Doc-comment

2022-07-17 08:30 UTC, Mothblocks commented on code/_onclick/other_mobs.dm
> +/mob/living/simple_animal/drone/resolve_right_click_attack(atom/target, list/modifiers)
Doc-comment

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +		balloon_alert(user, span_warning("Doesn't lead anywhere!"))
```suggestion
		balloon_alert(user, span_warning("doesn't lead anywhere!"))
```

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +		balloon_alert(user, span_warning("Can't go any further [going_up ? "up" : "down"]."))
```suggestion
		balloon_alert(user, span_warning("can't go any further [going_up ? "up" : "down"]!"))
```

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +	user.balloon_alert_to_viewers("climbing [up_down] [src]", "climbing [up_down] [src]")
```suggestion
	user.balloon_alert_to_viewers("climbing [up_down]...")
```

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +		to_chat(user, span_warning("[src] doesn't seem to lead anywhere that way!"))
```suggestion
		balloon_alert(user, "there's nothing that way!")
```

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +	user.balloon_alert_to_viewers("climbed [up_down]", "climbed [up_down]")
```suggestion
	user.balloon_alert_to_viewers("climbed [up_down]")
```

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +	user.visible_message(span_notice("[user] climbs [up_down] [destination] from [going_up ? "below" : "above"]."), span_notice("You climb down [src]."))
```suggestion
```

Don't have both

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +		travel(user, FALSE, TRUE)
Named parameters

2022-07-17 08:30 UTC, Mothblocks commented on code/game/objects/structures/ladders.dm
> +		travel(user, TRUE, TRUE)
Named parameters

2022-07-17 08:30 UTC, Mothblocks commented on code/modules/awaymissions/mission_code/Cabin.dm
> +	user.balloon_alert_to_viewers("warped in", "warped in")
```suggestion
	user.balloon_alert_to_viewers("warped in")
```

2022-07-17 08:30 UTC, Mothblocks commented on code/modules/awaymissions/mission_code/Cabin.dm
> +	user.visible_message(span_notice("[user] warps in over [src]."), span_notice("You warp in over [src]."))
```suggestion
```

Don't have both

2022-07-17 08:30 UTC, Mothblocks commented on code/modules/awaymissions/mission_code/Cabin.dm
> +	user.balloon_alert_to_viewers("activating [src]", "activating [src]")
```suggestion
	user.balloon_alert_to_viewers("activating...")
```

2022-07-17 08:30 UTC, Mothblocks commented
Closer, thanks

2022-07-19 12:13 UTC, Ghommie commented
Done. Can you add a refactor tag to it now by the by? Your sensible request for more attack_*_secondary procs had me refactoring the click sequence a bit to minimize the bloat.

2022-07-28 00:30 UTC, Fikou commented
moth is on holiday so ill merge this

2022-07-28 00:40 UTC, merged

2022-10-16 17:38 UTC, RikuTheKiller commented
I've hated this for ages now and I finally feel like making a PR to remove the delay. (Later ofc, procrastination.)

Stairs don't have a delay either and moving around generally shouldn't have delays at all except for doors.

It's such a fucking sequence break to go up a ladder only for it to glitch out, send me back down only for me to have to wait another few useless seconds because "but muh immersion..." PRs like this exist.

2022-10-16 20:41 UTC, Mothblocks commented
I'm fine removing the delay FWIW

2022-10-17 14:16 UTC, Ghommie commented
Feel free to remove the delay if you want to. It wasn't the main scope of this PR.

2022-11-03 16:40 UTC, RikuTheKiller commented
Will do.

2022-11-03 16:45 UTC, Mothblocks commented
Sounds like you should fix those bugs instead? The changelog provides a good motivation for the radial menu existing

2022-11-04 18:16 UTC, RikuTheKiller commented
> Sounds like you should fix those bugs instead? The changelog provides a good motivation for the radial menu existing

That's true.