Makes the changeling tentacle power function like its description says it does
tgstation/tgstation pull request #68023
Opened 2022-06-26 18:39 UTC by VioletN

## About The Pull Request

This is the current description of the changeling tentacle power:

> We can use it once to retrieve a distant item. If used on living creatures, the effect depends on the intent: In our neutral stance will simply drag them closer, Shove will grab whatever they're holding instead of them, in our Combat stance will put the victim in our hold after catching it, and will pull it in and stab it if we're also holding a sharp weapon. Cannot be used while in lesser form.

According to this description, using the tentacle on someone with combat mode **off** should simply drag someone towards you, while using the tentacle on someone with combat mode **on** should put them in an aggressive grab, and, if you're holding a sharp object, stab the target with it. In-game, however, this is currently reversed; you will put someone in an aggressive grab only if combat mode is off, while having combat mode on will simply drag them towards you and stab them if you're holding a sharp object.

This PR simply tweaks a few lines of code to make the tentacle function like the description says it does, meaning you'll be able to put someone in an aggressive grab and stab them if you use it on them in combat mode while holding a sharp object. I also slightly reworded the description to make it more clear how it functions and clean up some grammatical weirdness.

## Why It's Good For The Game

At the moment, the tentacle power's description is misleading, which I imagine could lead to some frustration if a player attempts to use it in combat. The described effects of the tentacle are also much more intuitive than the actual effects - it makes sense that having combat mode on would put someone in an aggressive grab and potentially hurt them.

## Changelog

:cl:
fix: The changeling tentacle power now properly functions the way its description says it does.
/:cl:

2022-06-26 18:51 UTC, Shadowflame909 commented
Any chance you can update the text desc too. Since intents don't exist anymore

2022-06-27 21:07 UTC, ShizCalev requested changes

2022-06-27 21:07 UTC, ShizCalev commented on code/modules/antagonists/changeling/powers/mutations.dm
> +		tentacle_stab(H, C)
this is only called by tentacle_grab(), may as well just make it a single proc.

2022-06-28 20:49 UTC, ShizCalev requested changes

2022-07-07 17:54 UTC, merged