Improves ambience
tgstation/tgstation pull request #68041
Opened 2022-06-27 20:34 UTC by Kapu1178

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl: Kapu1178, Baystation12
sound: Deaf mobs will no longer hear ambience.
sound: Ambience is now sourced from the environment instead of sent directly to the client.
sound: Space is now silent, and Lavaland is more lava-y.
sound: APCs changing powerstate is accompanied by a breaker switch sound.
sound: Maintenance now has its own droning loop, as well as more random sounds that play more often.
/:cl:

2022-06-27 20:42 UTC, JohnFulpWillard commented on code/controllers/subsystem/ambience.dm
> +/area/maintenance
this area doesn't exist

2022-06-27 20:45 UTC, Kapu1178 commented on code/controllers/subsystem/ambience.dm
> +/area/maintenance
cock

2022-06-27 21:20 UTC, Acer202 commented
Silent space? No more dilbert tunes to vibe to?

2022-06-28 18:11 UTC, Mothblocks requested changes
> Deaf mobs will no longer hear ambience.

I think this is a bad change and would hurt game feel a lot for the sake of realism. Currently walking around somewhere like medbay while deaf is actually pretty thematic, like a subtle hum.

2022-06-28 19:39 UTC, Kapu1178 commented
random sql failure rerun pls

2022-07-07 08:17 UTC, merged

2022-07-07 20:54 UTC, Shadowflame909 commented
oh gosh what an important PR that went overlooked by the majority of the playerbase

The new sounds are very startling and sounds almost like you got some sort of new fangled antag. I most compare it to changeling. Distracting and not at all ambience-like. More like OST!

Very sad!