Revisiting The Goliath: Or, that time I dripped out the SBC Starfury just because
tgstation/tgstation pull request #68126
Opened 2022-07-01 03:16 UTC by unit0016

## About The Pull Request
Drips the SHIT out of the SBC Starfury while not completely overhauling it. Touches everything NOT in engineering or southward (because I love how scuffed that part is and refuse to touch it on principle) - Also converts one map varedit into a real boy subtype, and moves tiny fans to their own file.

<details open>
<summary>Mandatory disclosure on the gameplay changes:</summary>

Fighters 1 and 3 are now NOT in the hangar, and are now attached to the formerly unused gunnery rooms.
Cryo now works. Yeah. I know.
You can actually open the anesthetic closet now.
Everyone now shares three spawners. This doesn't reduce the amount of people who can play when this rolls, as I've adjusted `var/uses` in accordance: it just reduces clutter.
A few of the horizontal double airlocks have been compacted into glass_large airlocks.
The bar windows now actually have grilles like they were meant to.
Four turbines have shown up. They aren't functional*, they just look like gunnery and conveniently fit in the spots. I'm sure this is space OSHA compliant.
The map is ever so slightly smaller, vertically. _This should distance us from an edge case where somehow all space levels are too cluttered for this to spawn properly, for the time being._

*Technically there's nothing stopping you from using them besides the amount of time it'd take for the operatives to kick your ass
</details>

<details open>
<summary>The Updated Map</summary>

![2022 06 30-23 10 37](https://user-images.githubusercontent.com/50649185/176816076-68b6c93c-f0bf-46a1-8809-56b4fd94ca42.png)

</details>

Feel free to poke holes or request additional changes, this is primarily cosmetic.

## Why It's Good For The Game
This map was originally designed wayyy back before we even have the computer sprites we have now, (https://github.com/tgstation/tgstation/pull/27760 is you want to see SOUL) and it shows. While it will never have it's SM again, we can at least make the thing much nicer to look at.

## Changelog

:cl:
add: The SBC Starfury has been ever-so-slightly tweaked! Two of the shuttles are now where the gunnery bays used to be, and the rest of the differences are largely cosmetic. Largely.
code: Survival pod fans have been split off into their own file.
/:cl:

2022-07-01 03:18 UTC, ANAME593 commented
could this be a potential alternative to https://github.com/tgstation/tgstation/pull/68057

2022-07-01 03:19 UTC, unit0016 commented
linter fix time

2022-07-01 03:20 UTC, unit0016 commented
> could this be a potential alternative to #68057

nope, entirely unrelated

2022-07-08 02:40 UTC, san7890 requested changes
Hey there, looks very nice to me.

<details>
<summary>Click Me For Images</summary>

![image](https://user-images.githubusercontent.com/34697715/177902125-e2d62003-72ee-472e-8937-b00e485fb03d.png)

I really like the placement of this sign, nice work.

![image](https://user-images.githubusercontent.com/34697715/177902162-a61b2d76-bc43-4d38-9e16-5a0d93d96c8c.png)

Please move this scrubber out from under the table.

![image](https://user-images.githubusercontent.com/34697715/177902258-5ef669f2-26cc-446a-ab4f-fbe98cb7cd40.png)

Would rather you use the physical tinyfan structure that shows up in game.

![image](https://user-images.githubusercontent.com/34697715/177902540-c40760a5-83ab-4cfb-b47b-d412ab37e2c5.png)

Use a passive vent here.

![image](https://user-images.githubusercontent.com/34697715/177902999-629d5af6-d909-4ae1-8d80-281863425dac.png)

This corner could use a small bit of light I feel, it's the main hanger and you don't want people tripping on potential slights.

![image](https://user-images.githubusercontent.com/34697715/177903064-e8ffc1f8-ed1a-4575-9f87-8d9cf52aa8fc.png)

Need lights here.

![image](https://user-images.githubusercontent.com/34697715/177903113-69b5456f-b35a-4b07-a5ff-7d6005911380.png)

The docks for fighters One and Three end-caps have this really odd (unintentional?) look to them due to the smoothing, would you look into something that better fits this?

![image](https://user-images.githubusercontent.com/34697715/177903440-eacf16f0-13f9-4121-8b5d-5b299032f91a.png)

Would like if you could either move the vent or the mop+bucket.

![image](https://user-images.githubusercontent.com/34697715/177903554-3ac07fc0-07eb-4d17-80bd-c58b8c5ba5e1.png)

Fighter 3 has these cameras that 1+2 do not have, is this intentional?

![image](https://user-images.githubusercontent.com/34697715/177904733-9edddd31-ed75-4c94-b576-0a02c34817f6.png)

They also look _really_ bizarre in game.

![image](https://user-images.githubusercontent.com/34697715/177903669-51373e43-8370-432c-a5ab-ca187f2aec3b.png)

Do they even have a defibrillator? I couldn't find one, not much sense having a mount for a non-existent bit of kit.

![image](https://user-images.githubusercontent.com/34697715/177903761-30174a4c-5a0b-4fc3-8978-71e7f98adb8f.png)

Yeah, this room is _really_ messy atmospherics wise, but could you try again to get the vent out from underneath the computer? Here's what I might try and do:

![image](https://user-images.githubusercontent.com/34697715/177903953-4d8bdf05-115c-48a6-9df5-3229b92e9b57.png)

That may or may not work for you.

![image](https://user-images.githubusercontent.com/34697715/177904222-407e8d7d-e38f-4533-b879-188ede98744b.png)

A small light bulb here (as well as on its symmetrical counterpart) would do a whole world of good.

![image](https://user-images.githubusercontent.com/34697715/177904404-60b939f2-4ad4-4fda-b217-1b1b210c9002.png)

The corvette seems to kinda... go _over_ the landing zone? Just feels a bit silly to me personally, is there a way to modify either the corvette or the bay to have it fit better? No worries if you can't figure it out, but it kinda hampers some aesthetics.

![image](https://user-images.githubusercontent.com/34697715/177904572-72ec0ebc-837a-460f-bf77-b2a795f69168.png)

These tables blend, FYI. Might wanna make it all plastitanium?

![image](https://user-images.githubusercontent.com/34697715/177905178-88126d33-31c0-41f8-ba43-4eaf420c0db6.png)

Odd blending here if you can figure it out, no worries otherwise.

![image](https://user-images.githubusercontent.com/34697715/177905239-b7ac339b-ba0a-4be7-99bd-193362f221ad.png)

Plating here makes the pipes visible which feels silly, could you make this some sort of floor over? I think catwalk floors might look nice (might be a bit excessive though).

![image](https://user-images.githubusercontent.com/34697715/177905351-5f681645-5409-4f3d-96f9-adc3b6e705b6.png)

I'd honestly rather not have any pod windows, feels too excessive and cluttered. Your call though.

![image](https://user-images.githubusercontent.com/34697715/177905943-dc19c02e-2f4e-45e6-91dd-a3f5db570ece.png)

Doesn't really make sense for the button for these shutters to be in a completely separate room. Would be nice if you had a button for the "exterior" as well as the "interior" of that "SM" room.
</details>

I'm not sure if all of the external airlocks _should_ have tiny fans, since some are missing some (notably the ones that start with shuttles). Up to you.

Otherwise, solid bit of mapping. I'll be marking this PR as a Draft as a way to manage the PRs we have on our plate, feel free to mark it as "Ready for Review" again when this has been addressed.

2022-07-08 02:40 UTC, san7890 commented on code/game/objects/structures/fans.dm
> +//Invisible, indestructible fans
```suggestion
	. = ..()

//Invisible, indestructible fans
```
New line for clarity.

2022-07-08 15:31 UTC, unit0016 commented
Gonna see what I can do here. The airlocks having tiny fans is gross and I wasn't aware of that, not my doing.

2022-07-08 19:52 UTC, merged