Removes the 10 second hardstun from Xeno Queen neurotoxin because it's not 2012 anymore and we don't do one hit instant hard stuns anymore.
tgstation/tgstation pull request #68243
Opened 2022-07-07 05:39 UTC by Iamgoofball

## About The Pull Request

Removes the 10 second hardstun from Xeno Queen neurotoxin because it's not 2012 anymore and we don't do one hit instant hard stuns anymore. 
Neurotoxin spit is no longer a 10 second hardstun.
Neurotoxin spit is now a ranged acid application method.

## Why It's Good For The Game

Fuck one hit ranged hardstuns. It's not 2012 anymore. Xeno queens should not be able to solo the crew in one on one combat and you're supposed to operate with backup from your hive.

## Changelog
:cl:
qol: Neurotoxin spit is no longer a 10 second hardstun.
balance: Neurotoxin spit is now a ranged acid application method.
/:cl:

2022-07-07 05:44 UTC, tgent007 commented
This is an amazing change.

2022-07-07 05:52 UTC, Iamgoofball commented
at least it's 2 hits instead of 1 then

2022-07-07 05:56 UTC, private-tristan commented
at least name it acid spit or something? 😕 

maybe just make it like a reskinned ebow shot so that you're knocked down and take hefty stamina damage?
I feel there's so many better ways to handle this other than "you spit corrosive acid instead"

2022-07-07 06:17 UTC, RegJackson commented
unironically based idedpr?

2022-07-07 06:25 UTC, DemoCrack commented
Based Goof PR, Xenos Mad.

2022-07-07 07:13 UTC, TemporalOroboros commented
Alternatives to the acid:
1. Copy the ebow affects. See above, probably the most simple. Could be done with a simple repath.
2. Make it a syringe shot that's preloaded with chems. I recommend neurotoxin at 5-10u, fentanyl at higher volumes, or some other incapacitating toxin.

The acid stats from the acid vomit action were for consistently melting through walls, not for applying to people. The obj/turf filter was missed when it was converted to an on-click action from a prompt.

2022-07-07 07:32 UTC, optimumtact commented
![image](https://user-images.githubusercontent.com/2544323/177717481-dc3c350b-8868-4fda-9ff0-4adaf1b8f1c1.png)

2022-07-07 08:12 UTC, Mothblocks requested changes
> Xeno queens should not be able to solo the crew **in one on one combat** and you're supposed to operate with backup from your hive.

I wholy disagree.

I think xenomorphs are one of the last bastions of antagonists that bring true paranoia and require a team takedown from the crew. Ranged hard stuns like tasers are bad because they're easily accessible by the crew, xenomorphs are rare and *meant* to be a heavy impact threat--giving them the upper hand with powerful attacks is completely fine. I want stronger reasoning for this because believe it or not I quite like that xenomorphs are as threatening as they are.

I also separately disagree this is in any way a QoL change

2022-07-07 08:57 UTC, LemonInTheDark commented
I want xenos to win

2022-07-07 09:04 UTC, Iamgoofball commented
xenos should be scary because they're scary not because they have the gamer button(stuns)

2022-07-07 09:31 UTC, Mothblocks commented
> > xenomorphs are rare
> 
> no they aren't we just had 2 fucking xeno rounds back to back on manuel and the players are saying xenos are constant

The full context:

> Ranged hard stuns like tasers are bad because they're easily accessible by the crew, xenomorphs are rare 

I am referring to tasers, which are ever present and acquirable by any crew member.

> xenos should be scary because they're scary not because they have the gamer button(stuns)

I would not oppose a larger rework of xenos (I wanted @IndieanaJones to do it for quite some time for a while) but the point of the matter is that I only fear xenos because I know that it takes them no time at all to pop me out of the round and I think that's a good thing

2022-07-07 09:37 UTC, Colovorat commented
> > xenomorphs are rare
> 
> players are saying xenos are constant

they lied to you 😈

2022-07-07 10:21 UTC, Dawson1917 commented
>xenos should be scary because they're scary not because they have the gamer button(stuns)

They stopped being scary when their ability to pick off isolated crewmembers and drag them into vents was removed

2022-07-07 16:47 UTC, Shadowflame909 commented
Xenos should be able to one shot you unless you have gamer gear.

IMO Xenos are the pinnacle of evolution. So you kind of have to have the pinnacle of powercreep to beat them.

Like Cargo swat crats with telescopic batons from sec. Or Hulk with pressure adap from genetics. Or A mech from robo since it counters all of the stuff xenos can do. Or a simple mob from xenobio since they are immune to stuns too, and can match xenos speed. Or gat-fruit from xenobio...

Yeah Xenos are OP, I agree. But I feel like thats the point, and if you aren't OP too it means the end of the round for good reason.

2022-07-08 03:03 UTC, IndieanaJones commented
This is a real oaf-tier change.  You do realize that you're taking away the sentinel's ability to stun outside of disarms, right?  Just make it deal heavy stam damage, but have it be negated by wearing bio-protection armor.

2022-07-08 11:19 UTC, closed without merging