Refactors admin PMs to be hopefully more resilient
tgstation/tgstation pull request #68344
Opened 2022-07-11 07:51 UTC by LemonInTheDark

## About The Pull Request

MSO got me curious, so I refactored admin help code doin my best to follow https://github.com/tgstation/tgstation/pull/68324#issuecomment-1179773970
The basic idea is try and make behavior as clear as possible, and keep data extraction separate from logic
Also fail loud, in this case meaning any operation that would cause the pm to fail to send should send an error message to the sender.

I'm splitting the main proc up into subsections, in an attempt to make it easier to reason about and work with.
As a side effect of this, some operations need to be done more then once to avoid potential debugger escalation.

Related to this, I'm also no longer directly passing around client references through the procs. I instead pass the result of a pretty basic proc into each, to avoid issues with sleeping and such.

Changes the backup for replying to someone who logs out, instead of using the first person to send something to the ticket as our backup, we use the recipient's ckey.

Converts all uses of the linkify span to a macro. One of these doesn't have a closing span, not sure if that's a bug or a feature

Also I just cleaned things up, because the old state of things really bothered me. Too hard to read/understand meaning, and too verbose.
I've also fixed some logic errors, like being unable to respond to tgs ahelps, or a few runtimes in tgs handling.
Did you know secret ckeys, despite claiming to be unique, weren't? 
The hope is this will prevent failure in the tickets system in future

## Why It's Good For The Game

I really don't want to go back to walking up and down stairs trying to get the sand bug to trigger, guess it starts tomorrow.

## Changelog

:cl:
admin: Wooooo spoooky ADMIN HELP BACKEND HAS CHANGED. If you run into any strange behavior or dropped messages, REPORT THEM
/:cl:

2022-07-11 08:24 UTC, TrashDoxx commented on code/__DEFINES/span.dm
> +#define span_linkfiy(str) ("<span class='linkify'>" + str + "</span>")
ehh.. linkfiy? isn't that a mistake? here and further in the code.

2022-07-11 08:46 UTC, TrashDoxx commented on code/__DEFINES/span.dm
> +#define span_linkfiy(str) ("<span class='linkify'>" + str + "</span>")
me too

2022-07-11 14:29 UTC, san7890 commented on code/modules/admin/verbs/adminpm.dm
> +	var/raw_messsage = log_message
Typo? Here and subsequent lines.

2022-07-11 22:28 UTC, jlsnow301 commented
i love that you've used _lad_ and _boi_ as mob var names here, getting tired of thinking up crafty names myself

2022-07-12 21:45 UTC, MrStonedOne approved these changes
Thanks for the insanely fast turn around on this.

2022-07-12 22:01 UTC, san7890 commented on code/modules/admin/verbs/adminpm.dm
> +	var/messsage = input(src, message_prompt, request) as message|null
even more messsage spellcheck here and subsequent lines

2022-07-13 00:05 UTC, LemonInTheDark commented
> Thanks for the insanely fast turn around on this.

I got bored and it sounded fun, thanks for the interesting problem

2022-07-21 05:34 UTC, Kylerace requested changes

2022-07-26 23:17 UTC, Mooshimi commented
Don't let the bot close this... it's too vital 👀

2022-08-02 03:58 UTC, merged