Be polite! While on walk intent you won't bump, swap places or push other people now.
tgstation/tgstation pull request #68493
Opened 2022-07-16 22:46 UTC by GuillaumePrata

## About The Pull Request
Just the title

## Why It's Good For The Game
We might be used to the jank at this point, but our movement system is kinda atrocious...
You don't have much control on how your character moves around, it feels floaty, people slingshot around the place a lot bumping, swapping or pushing others for 30 tiles down a hallway...

So this is a small change to add some precise control to our characters that is completely optional as the only time we need to walk in game for a mechanical reason that I can remember is wet tiles.

With this change you can be polite and not shove people around and interrupt their tasks, I personally will enjoy walking and asking others to walk inside the medbay so they stop pushing doctors around.

Also, thanks Goof for bringing up a point about spessman movement on discord, is what made me stop being lazy for an hour and see how the code works to do this PR.

## Changelog

:cl: Guillaume Prata
balance: Be polite! While on walk intent you won't bump, swap places or push other people now.
/:cl:

2022-07-16 22:47 UTC, SuperNovaa41 commented on code/modules/mob/living/living.dm
> +	if(src.m_intent == MOVE_INTENT_WALK)
```suggestion
	if(m_intent == MOVE_INTENT_WALK)
```
pointless

2022-07-16 22:48 UTC, GuillaumePrata commented on code/modules/mob/living/living.dm
> +	if(src.m_intent == MOVE_INTENT_WALK)
Done and thank you.

2022-07-16 22:49 UTC, Iamgoofball commented
Make sure that you can't walk past someone with combat mode on, so that combat mode still requires you to rest to get around, putting yourself into a vulnerable state.

2022-07-16 22:52 UTC, GuillaumePrata commented
> Make sure that you can't walk past someone with combat mode on, so that combat mode still requires you to rest to get around, putting yourself into a vulnerable state.

I can test it but nothing should change when compared to other players, you just won't try to swap/push people if you are on walk intent regardless of your, or theirs, combat mode.

2022-07-17 03:12 UTC, Farquaar commented
It's polite, yes. But is it efficient? Does it coincide with having a plan to kill everyone you meet?

2022-07-18 00:49 UTC, Mothblocks requested changes
Please confirm that someone with combat mode on still can't be moved past without resting/being grabbed or wahtever.

2022-07-18 12:46 UTC, Palpetinus commented
>The only time we need to walk in game for a mechanical reason, that I can remember, is over wet tiles

Holobarriers

2022-07-18 17:16 UTC, GuillaumePrata commented
> Please confirm that someone with combat mode on still can't be moved past without resting/being grabbed or wahtever.

Nothing changes on that end.
And you can still swap/push people that are on walk intent if they are not on combat mode.

2022-07-18 23:51 UTC, Mothblocks commented
Okay I will take your word for it

2022-07-18 23:51 UTC, merged