You can no longer attach C4 to ghosts
tgstation/tgstation pull request #68513
Opened 2022-07-17 05:15 UTC by CoffeeDragon16

## About The Pull Request

Prevents C4 from being attachable to ghosts.

## Why It's Good For The Game

While it is **_hysterical_**, the targets can't defend themselves in the slightest. It would be very easy to abuse this. Is confirmed to be an exploit by Mothblocks.

## Changelog

:cl:
fix: you can no longer attach C4 to ghosts.
/:cl:

2022-07-17 05:40 UTC, Kapu1178 commented
FEATURE. FEATURE. FEATURE.

2022-07-17 06:06 UTC, the-orange-cow commented
Litteraly 1984.

2022-07-17 06:22 UTC, Shadowflame909 commented
I'm guessing wizard + traitor made this possible

Surprised that the ghosts didn't just orbit the traitor to bomb them

2022-07-17 08:23 UTC, Fikou commented on code/game/objects/items/grenades/plastic.dm
> +	if(isobserver(bomb_target))
check for invisibility instead? people could put c4 on hidden revenants, or supermatter timers etc

2022-07-17 09:59 UTC, timothymtorres commented
The real question is what happens to the ghost after the c4 detonates?  Does the player get disconnected?

2022-07-17 15:56 UTC, ShizCalev requested changes
Add incopreal_movement and phased_mob checks too please

2022-07-17 21:53 UTC, Mooshimi commented
It requires such rare circumstances that it doesn't seem like a issue to prioritize.
1 Wizard to actually make ghosts visible.
2 Traitor to trust a ghost to not bomb them/ do that they want.

(This is an ided pr.)

2022-07-17 23:38 UTC, Bawhoppen commented
Emergent gameplay

2022-07-18 03:22 UTC, JohnFulpWillard commented
Where was this confirmed to be an exploit? Don't see an issue report saying so

2022-07-18 05:20 UTC, Mooshimi commented
> 

![image](https://user-images.githubusercontent.com/85910816/179449434-d2618753-3fe2-45d1-9534-0b2e75e07e8d.png)

2022-07-18 14:11 UTC, Dawson1917 commented
There's a 79% chance the ghost you attach C4 to will deliberately orbit you for shits and giggles. This is too funny to remove

2022-07-18 16:30 UTC, CoffeeDragon16 commented
😃I see people really like this interaction! Thanks for letting me know.
I made the PR because I found it lame that you're defenseless to it, and it could be easily exploited. However from what I'm seeing, this never really gets abused, given it's quite a niche interaction. 
I'll close this to keep it in, as people seem to enjoy this. I may re-open it if more people learn about the interaction and every visible ghost round has people getting C4'd by ghosts without the ability to defend themselves.

2022-07-18 16:30 UTC, closed without merging