Adds achievement rewards for serving tourists.
tgstation/tgstation pull request #68758
Opened 2022-07-26 08:32 UTC by orthography

## About The Pull Request

Serving 3000 tourists in either the bar or the kitchen will award you with a golden version of your job's primary tool.

Bartenders receive the golden shaker

Cooks receive the golden knife.

## Why It's Good For The Game

Gives purpose to the tourists served achievement, especially as during slow shifts (more so for bartenders) there is nothing to encourage players to use the tourist bots. This should make the gameplay loop a little more player sided giving an actual objective for service staff to achieve to flex their expertise and devotion to the job, ~and then have the item stolen in the first 5 minutes by Tider McToolbox~

## Changelog

:cl:
add: Nanotransen has begun a culinary awards program, high achieving service staff will receive a solid gold trophy to use during their shifts to thank them for their tireless work. Please do not break it.
imageadd: adds golden versions of the knife and shaker.
code: adds achievement checks in the bartender.dm and cook.dm
/:cl:

2022-07-26 08:59 UTC, Colovorat commented
GAGSify those sprites 😈

2022-07-26 09:08 UTC, Pepsilawn commented
Cooks don't normally start with knives as they must be bought from the vendor, I'm not sure that's the right item to give them

2022-07-26 14:39 UTC, orthography commented
> Cooks don't normally start with knives as they must be bought from the vendor, I'm not sure that's the right item to give them

Since knifes are so incredibly cheap for chefs, and it's so necessary for their job, I personally don't see an issue with them spawning with it.

It'd be hell, but I *could* try making an item that converts the knife/shaker into the gold variant.

2022-07-26 18:46 UTC, wesoda25 commented
Encourages single player gameplay 👎

2022-07-27 07:30 UTC, MrMelbert requested changes

2022-07-27 16:08 UTC, orthography commented on code/game/objects/items.dm
> +	var/goldenw = FALSE
https://github.com/tgstation/tgstation/pull/68758/commits/0cfc54cb5b2d1f66febf7e9690fc4067fea3b7a2

2022-07-27 17:06 UTC, orthography commented on code/modules/jobs/job_types/_job.dm
> +		backpack_contents[/obj/item/achievement_potion/hardcore] = 1
https://github.com/tgstation/tgstation/pull/68758/commits/6da0254f4d83863ada166602074ed60275e0df61

2022-07-27 18:37 UTC, MrMelbert requested changes

2022-07-28 03:50 UTC, orthography commented on code/modules/jobs/job_types/bartender.dm
> +/datum/outfit/job/bartender/pre_equip(mob/living/carbon/human/H, visualsOnly)
https://github.com/tgstation/tgstation/pull/68758/commits/9598d1ee1661ed7ed1c5196905b4d22ab6a51033

2022-07-28 03:50 UTC, orthography commented on code/modules/jobs/job_types/_job.dm
> +	. = ..()
https://github.com/tgstation/tgstation/pull/68758/commits/9598d1ee1661ed7ed1c5196905b4d22ab6a51033

2022-07-28 04:56 UTC, orthography commented on code/game/objects/items/kitchen.dm
> +		new /obj/item/knife/gold(loc)
https://github.com/tgstation/tgstation/pull/68758/commits/05bbeb29a246397adc9ec6b2142c1e1e7341b64a

2022-07-30 08:47 UTC, ShizCalev commented on code/game/objects/items/kitchen.dm
> +	var/obj/item/knife/golden = new(drop_location())
transformations should be loc

2022-07-30 09:41 UTC, NamelessFairy commented
I really like the concept, I agree with your suggestion about making these into converters rather than spawning with the item, (latejoin cooks spawning armed isn't a cosmetic change). I'm not a fan of the goals for the bartender/cook though, it should be something more interactive, maybe mix 10 of every possible drink or just mix x number of drinks overall (I can see this being exploited though) By doing an objective like this your effectively engaging in the same thing that your job tasks people with but this time its not exclusive to feeding NPCs. Also would like to know how difficult the 3 of these objectives are, I don't play any of them but how long are these realistically going to take.

2022-07-30 14:41 UTC, orthography commented
> I really like the concept, I agree with your suggestion about making these into converters rather than spawning with the item, (latejoin cooks spawning armed isn't a cosmetic change). I'm not a fan of the goals for the bartender/cook though, it should be something more interactive, maybe mix 10 of every possible drink or just mix x number of drinks overall (I can see this being exploited though) By doing an objective like this your effectively engaging in the same thing that your job tasks people with but this time its not exclusive to feeding NPCs. Also would like to know how difficult the 3 of these objectives are, I don't play any of them but how long are these realistically going to take.

Hi, I could understand your concern with the knife which is why it's attached to a potion now. As of now, there are about 4 /tg/ players who have unlocked the golden wheelchair doing hardcore random, it is definitely supposed to be a hard task, and because of that I don't feel comfortable changing the requirements without the original owners permission. (https://github.com/tgstation/tgstation/pull/50606)

The tourists were achievements that already existed keeping score in a (relatively) fair way, the more complex the drink, the more points you get. Furthermore, they're a dependable source of points. As mentioned above, especially for bartender, it's unlikely that you get much action at all during your shift. Unless you turn to bounties or NPCs, you might have the mime ask for silencer, and sec as for quad.

Hope that clarifies it a bit more.

2022-07-30 14:45 UTC, Twaticus approved these changes

2022-08-04 21:37 UTC, optimumtact commented
@Mothblocks @ninjanomnom thoughts?

I'm mixed on this, especially as we already have skill cloaks.

2022-08-05 09:03 UTC, NamelessFairy commented
> @Mothblocks @ninjanomnom thoughts?
> 
> I'm mixed on this, especially as we already have skill cloaks.

With the exception of the playtime skill cloak the skill cloaks are per round, I don't know the exact numbers but e.g. mine x number of rocks during a shift get a skill cloak for that shift, you do not get the skill cloak next shift and need to earn it again. These are larger Multi-round objectives that give you a permanent cosmetic item.

2022-08-05 12:19 UTC, Mothblocks commented on code/game/objects/items/kitchen.dm
> +	var/obj/item/knife/golden = new(drop_location())
This doesn't look like you're using the golden subtype?

2022-08-05 12:22 UTC, Mothblocks commented
@optimumtact Skill capes aren't really equivalent in the moment I don't think because they're temporary, and aside from hyper-gaming strats, you usually only obtain them when the round is already nearing its conclusion (obviously adjustable).

I think the way I would best prefer to see these is with challenging, but more reachable, requirements, and if it expires after a while, like a week or so.

Also a bit negative about attaching it to the bar bots, which although I'm generally a fan of them, I don't think I want to see them have a stronger presence since I don't want to give people a reason to prefer them over real human players. Maybe even just attaching them to the actual skills would be a good idea if we go with my expiration suggestion.

2022-08-05 16:35 UTC, orthography commented
> @optimumtact Skill capes aren't really equivalent in the moment I don't think because they're temporary, and aside from hyper-gaming strats, you usually only obtain them when the round is already nearing its conclusion (obviously adjustable).
> 
> I think the way I would best prefer to see these is with challenging, but more reachable, requirements, and if it expires after a while, like a week or so.
> 
> Also a bit negative about attaching it to the bar bots, which although I'm generally a fan of them, I don't think I want to see them have a stronger presence since I don't want to give people a reason to prefer them over real human players. Maybe even just attaching them to the actual skills would be a good idea if we go with my expiration suggestion.

I totally understand your concerns with the barbots. My issue is that, especially for bartenders, there is almost no action in their shifts (interaction, antag potential, fights, etc). I was already looking into a way to make some of these lesser played jobs, (bartender, psych, curator) more active either by a harder injection into the round, or through giving them their own shit to do.

I could look into attaching the both the knife and shaker to more crew centric objective if you have one off the top of your head.

2022-08-05 16:48 UTC, orthography commented
Whoops! Furthermore, especially unless they're not attached to bar bots, it seems unwise to make them expire. There was already some expressed concern in this PR that it could cause more single player gameplay than actual round engagement, which I could understand if it had to be renewed every shift.

Unless there are some divergent ideas, for the knife and shaker unlocks.

The possibilities, by mothblock points are.

Reward preservance.

- Keep it permanent
- Renew it every week
- Renew every month
- Renew every shift
- Must be top (x) on the leaderboard


New obtain methods.

- Start of shift bartender or chef must make some over the top drink/food and have at least one bite out of it. (Super burger, jungle juice, mega pie, narsie memosas, etc)
- Make x amount of drinks/food (by complexity.
- Serve x amount of crew mates
- Serve x amount of bar bots.

2022-08-15 21:47 UTC, closed without merging

2022-08-16 03:30 UTC, LemonInTheDark commented
sall good, you gonna reopen the pr?