blind people know when things happen to them
tgstation/tgstation pull request #68950
Opened 2022-08-03 07:09 UTC by Mooshimi

## About The Pull Request

Fixes: #67815
Gives a vague chat alert to blind people who are being stripped of something/something is being put on them, thrown and hits them/hits them in general, being fed something

## Why It's Good For The Game

It's more realistic than not noticing at all if you're blind.

## Changelog

:cl:
fix: Blind support added to some actions like stripping, being hit, and force-feeding.
/:cl:

2022-08-03 07:17 UTC, Mooshimi commented
will fix tomorrow don't yell at me

2022-08-04 16:49 UTC, Kapu1178 commented on code/datums/elements/strippable.dm
> +		blind_message = "You hear rustling.",
```suggestion
		blind_message = span_hear("You hear rustling."),
```

2022-08-05 13:59 UTC, Mothblocks requested changes, later dismissed

2022-08-05 13:59 UTC, Mothblocks commented on code/_onclick/item_attack.dm
> +	if(src.is_blind())
```suggestion
	if(is_blind())
```

2022-08-05 13:59 UTC, Mothblocks commented on code/datums/elements/strippable.dm
> +			else if(victim_human.is_blind()) //blind support
Don't need this comment, it's obvious from the `is_blind()`

```suggestion
			else if(victim_human.is_blind())
```

2022-08-05 13:59 UTC, Mothblocks commented on code/datums/elements/strippable.dm
> +		else if(victim_human.is_blind())//blind support
```suggestion
		else if(victim_human.is_blind())
```

2022-08-05 13:59 UTC, Mothblocks commented on code/modules/projectiles/projectile.dm
> +			to_chat(L, span_userdanger("You're shot by \a [src][organ_hit_text]!"), )
```suggestion
			to_chat(L, span_userdanger("You're shot by \a [src][organ_hit_text]!"))
```

2022-08-06 00:25 UTC, merged

2022-08-06 19:58 UTC, ZeroMODE0 commented
Bless