Bileworm post-merge feedback and qol
tgstation/tgstation pull request #69007
Opened 2022-08-05 18:35 UTC by tralezab

## About The Pull Request

* Adds a death message to the bileworm!
  * some extra coder stuff about this: moved deathsound up from /mob to /living as it is a var for dying on a type that doesn't die, and moved deathmessage down from /simple_animal to /living as /simple_animal isn't where mobs learn to die! Also, they're snake case now, which is why this pr looks so big.
* Bileworms now give up their target if they attempt to resurface near them but cannot.
* Bileworms controlled by players can now see in the dark!

## Why It's Good For The Game

Just went around to various servers asking how people were feeling. From watching people fight bileworms, I'm really happy with how they turned out, but there is room for improvement!

## Changelog

:cl:
qol: Bileworms possessed by players can now see in the dark!
qol: Bileworms now have a death message!
balance: Bileworms will now give up their targeting if they fail to burrow to you. If they can still see you, they might regain aggro, but now moving say, to the mining station/big lava lake/hirophant is a good way to de-aggro them.
/:cl:

2022-08-05 19:22 UTC, LemonInTheDark requested changes

2022-08-05 19:22 UTC, LemonInTheDark commented on code/datums/actions/mobs/adjust_vision.dm
> +/datum/action/adjust_vision.Remove(mob/living/remove_from)
arm wtf

2022-08-05 19:22 UTC, LemonInTheDark commented on code/datums/actions/mobs/adjust_vision.dm
> +	grant_to.see_in_dark = initial(grant_to.see_in_dark)
armmmmmmmm COMPILE

2022-08-05 19:22 UTC, LemonInTheDark commented on code/datums/actions/mobs/adjust_vision.dm
> +	living_owner.sight = initial(sight_flags)
AGHHHHHHHHHH

2022-08-05 19:38 UTC, tralezab commented
uhhh dont peek at those resolved reviews

2022-08-08 21:25 UTC, JohnFulpWillard commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	death_message = "[src] blows apart!"
who the fuck set this on initialize

2022-08-08 21:27 UTC, tralezab commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	death_message = "[src] blows apart!"
LOL

2022-08-08 21:40 UTC, merged