Cleans up update_icons, makes the update_icon_updates_onmob element bespoke, updates CODEOWNERS
tgstation/tgstation pull request #69179
Opened 2022-08-13 03:45 UTC by Kapu1178

## About The Pull Request
- Renames & autodocs all mob update icons procs
- Makes the update_icon_updates_onmob bespoke. You pass what slots you want to update into it. Also can update bodyparts but it's unused right now.
- Expands my CODEOWNERS reach to `/organs` and `/human_update_icons.dm`

2022-08-13 04:10 UTC, Kapu1178 commented
I HATE regenerate_icons

2022-08-13 05:10 UTC, Kapu1178 commented
fuck you im going to bed

2022-08-13 08:32 UTC, LemonInTheDark commented
![box](https://user-images.githubusercontent.com/58055496/184475959-52ad83fd-8891-4b07-b73e-01ecd2c4deca.jpg)

2022-08-16 17:20 UTC, SuperNovaa41 requested changes
everything else looks fine

2022-08-16 17:20 UTC, SuperNovaa41 commented on code/datums/elements/update_icon_updates_onmob.dm
> +	var/update_body = FALSE
doc comments

2022-08-16 17:31 UTC, Kapu1178 commented on code/datums/elements/update_icon_updates_onmob.dm
> +	var/update_body = FALSE
```suggestion
	///The ITEM_SLOT_X flags to update on the parent mob. (Ex: ITEM_SLOT_HANDS|ITEM_SLOT_FEET)
	var/update_flags = NONE
	///Should the element call [/mob/proc/update_body()] in addition to clothing updates?
	var/update_body = FALSE
```

2022-08-16 17:50 UTC, merged

2022-08-19 01:52 UTC, ShizCalev commented
obv not tested lol.

2022-08-19 23:09 UTC, tnekohue commented
It appeared to fix #69303 for a while