Necropolis Tendrils now need to be interacted with to drop their loot, and multiple people can receive multiple chests.
tgstation/tgstation pull request #69193
Opened 2022-08-13 21:10 UTC by tralezab

## About The Pull Request

Tendrils no longer immediately drop their chests, they will drop it once you have used an empty hand on the collapsing tendril. You can only spawn a chest once, but every unique mob that interacts can spawn one chest.

## Why It's Good For The Game

This is a buff to coop mining. Mining with a friend and attacking a tendril now opens the possibility to get 2x the loot, or more. I find that coop mining historically hasn't been worth it and it's much more productive to split everyone up and clear the map that way. That's sad, I hate that! We should encourage working together because the social and cooperative aspect of ss13 is fun and unfortunately not viable as-is.

## Changelog

:cl:
balance: Tendrils now drop their loot when you interact with them during the collapse.
balance: But they can be interacted with by multiple people, so mining with a friend brings more loot!
/:cl:

2022-08-13 21:12 UTC, tralezab commented
I'll also make the interaction auto-pull the loot to hopefully trip people up a bit less.

2022-08-13 21:13 UTC, zxaber commented
As a counter idea, what if you tracked the number of recent (client'd) attackers on the tendril and just made the one box have an extra item per extra attacker?

2022-08-13 21:13 UTC, tralezab commented
> As a counter idea, what if you tracked the number of recent (client'd) attackers on the tendril and just made the one box have an extra item per extra attacker?

Without autopulling, it seems a lot more squabbling over who has what secured

2022-08-13 21:20 UTC, MrMelbert requested changes

2022-08-13 21:20 UTC, zxaber commented
Well, I mean, there's a fresh pit right there if someone's being an asshole.

Really, it just seems like a mess to me to have multiple people trying to grab multiple chests within a short time before the pit eats everything in a 5x5.

2022-08-13 21:28 UTC, the-orange-cow commented
Consider extending the collapse timer to accommodate the addition input required.

2022-08-13 21:57 UTC, tralezab commented
> Consider extending the collapse timer to accommodate the addition input required.

I've removed pulling, but added clicking on the tendril. It should be pretty much the same action, you clicking on the tendril.

2022-08-13 22:03 UTC, anclandor commented
> > Consider extending the collapse timer to accommodate the addition input required.
> 
> I've removed pulling, but added clicking on the tendril. It should be pretty much the same action, you clicking on the tendril.

How does it remove pulling?  Does it pull the chest when you click it?

2022-08-13 22:11 UTC, tralezab commented
yep! so you click on the tendril, and you're already pulling the tendril. Only change is that you're leftclicking instead of ctrlclicking which might actually help

2022-08-14 00:59 UTC, Shadowflame909 commented
The power of friendship being used more on mining is a win. Might allow those dual-tendril legion/watcher + goliath spawns to actually be actively fought and not cheesed. Also increases the likely hood of the stasis beds to be used.

Also opens up the option of making tougher tendrils/adding the new fauna to spawn from tendrils like brim-demons and stuff. If co-op miners get too good.

2022-08-14 07:05 UTC, private-tristan commented
when this PR gets merged there will inevitably be multiple miners wondering what happened when they killed a tendril and no chest spawned

maybe a balloon alert saying to grab it out of the tendril before it collapses? or maybe making the tendril not collapse until at least 1 chest is taken out (or something like a 30 second timer passes)?

2022-08-14 19:22 UTC, Mooshimi commented
seems like more of a refactor than a balance to me? please correct if wrong

2022-08-14 20:24 UTC, Fikou commented
> seems like more of a refactor than a balance to me? please correct if wrong

this is not a refactor at all. refactors increase the quality of the code while not changing functionality. this just rebalances tendrils to have different functionality.

2022-08-15 00:54 UTC, CCC23 commented
Mining Buff :)

2022-08-15 01:54 UTC, tralezab commented
> when this PR gets merged there will inevitably be multiple miners wondering what happened when they killed a tendril and no chest spawned
> 
> maybe a balloon alert saying to grab it out of the tendril before it collapses? or maybe making the tendril not collapse until at least 1 chest is taken out (or something like a 30 second timer passes)?

Totally happy to do that, I can in a day or so

2022-08-15 03:50 UTC, 567Turtle commented
good change 🙂

2022-08-15 22:10 UTC, bluetshirtguy commented
seems cool although it may just lead to miners screaming at eachother and being toxic over touching a tendril early.

2022-08-15 23:13 UTC, ShizCalev commented
> > when this PR gets merged there will inevitably be multiple miners wondering what happened when they killed a tendril and no chest spawned
> > maybe a balloon alert saying to grab it out of the tendril before it collapses? or maybe making the tendril not collapse until at least 1 chest is taken out (or something like a 30 second timer passes)?
> 
> Totally happy to do the balloon alert since I'm trying to minimize confusion, I can in a day or so

do it faster

2022-08-15 23:18 UTC, the-orange-cow commented
> seems cool although it may just lead to miners screaming at eachother and being toxic over touching a tendril early.

![miner_reee](https://user-images.githubusercontent.com/76538214/184737011-9cad3136-66c8-44bb-92f3-56c2f465f69d.jpg)

2022-08-16 13:41 UTC, rasepretep commented
I feel like this PR should also remind miners that the Wormhole Jaunter exists, and how it's used. A lot of miners don't even know about it, almost everyone that does just doesn't use it. New-ish miners especially might appreciate the extra safety net if they have to be around chasms more.

2022-08-16 17:45 UTC, tralezab commented
> > > when this PR gets merged there will inevitably be multiple miners wondering what happened when they killed a tendril and no chest spawned
> > > maybe a balloon alert saying to grab it out of the tendril before it collapses? or maybe making the tendril not collapse until at least 1 chest is taken out (or something like a 30 second timer passes)?
> > 
> > 
> > Totally happy to do the balloon alert since I'm trying to minimize confusion, I can in a day or so
> 
> do it faster

i was on vacation ok working now

2022-08-16 23:39 UTC, Mooshimi commented
> I feel like this PR should also remind miners that the Wormhole Jaunter exists, and how it's used. A lot of miners don't even know about it, almost everyone that does just doesn't use it. New-ish miners especially might appreciate the extra safety net if they have to be around chasms more.

Not even related besides the tangential existence of a chasm I think?

2022-08-17 05:25 UTC, Shadowflame909 commented
> I feel like this PR should also remind miners that the Wormhole Jaunter exists, and how it's used. A lot of miners don't even know about it, almost everyone that does just doesn't use it. New-ish miners especially might appreciate the extra safety net if they have to be around chasms more.

when they stopped working on the miner chest-rig/belts. they became useless too me. Too many medipens and legion cores need to be held rather then give up the storage!

2022-08-18 17:41 UTC, merged