Add silicon human spremacy override config, fixes #68957
tgstation/tgstation pull request #69293
Opened 2022-08-18 13:01 UTC by RandomGamer123

## About The Pull Request
See title

## Why It's Good For The Game
Fixes #68957 

## Changelog

:cl:
fix: Asimov supremacy shows up as a human perk for default servers
config: Added a config option to make Asimov supremacy show up as a perk for humans even if the default lawset is not Asimov (intended for use with Asimov variants, notably Asimov++)
/:cl:

2022-08-19 07:11 UTC, Mothblocks commented on config/game_options.txt
> +SILICON_HUMAN_SUPREMACY_OVERRIDE
```suggestion
## Uncomment this out to make "Asimov Supremacy" show up as a perk for humans
# SILICON_HUMAN_SUPREMACY_OVERRIDE
```

2022-08-19 07:11 UTC, Mothblocks requested changes

2022-08-19 07:11 UTC, Mothblocks commented on config/game_options.txt
> +SILICON_HUMAN_SUPREMACY_OVERRIDE
All of this should be "Asimov Superiority", which is what it's actually called.

2022-08-19 07:11 UTC, Mothblocks commented on code/controllers/configuration/entries/game_options.dm
> +/datum/config_entry/flag/silicon_human_supremacy_override
Document it

2022-08-23 01:21 UTC, dragomagol commented on code/controllers/configuration/entries/game_options.dm
> +/datum/config_entry/flag/silicon_asimov_superiority_override // Controls if Asimov Superiority appears as a perk for humans even if standard Asimov isn't the default AI lawset
The doc should be above the var, and begin with `///`
https://github.com/tgstation/tgstation/blob/master/.github/guides/AUTODOC.md

2022-08-24 06:20 UTC, merged