Fixes #69020, stops export datums processing unneededly
tgstation/tgstation pull request #69294
Opened 2022-08-18 13:04 UTC by RandomGamer123

## About The Pull Request
This was an interesting bug, it turned out to be caused by the processing code multiplying the price by roughly 1.0011 per second while clamping it at its original price, which meant that for most exports which have a original sale price that's positive, nothing changes. However, for exports with negative sale prices, this means that the price grows more negative in an exponential manner over time.

## Why It's Good For The Game
Fixes #69020

## Changelog

:cl:
fix: Stops the export value for erroneous manifests from decreasing into the deep negatives exponentially over time
/:cl:

2022-08-20 19:53 UTC, SuperNovaa41 requested changes

2022-08-20 19:53 UTC, SuperNovaa41 commented on code/modules/cargo/exports.dm
>  	/// cost includes elasticity, this does not.
remove this

2022-08-20 19:53 UTC, SuperNovaa41 commented on code/modules/cargo/exports.dm
>  	return ..()
just remove the entire override

2022-08-31 12:21 UTC, RandomGamer123 commented
bump

2022-09-01 04:15 UTC, JohnFulpWillard commented
Want to point you to the PR that added it: https://github.com/tgstation/tgstation/pull/27099

2022-09-01 21:51 UTC, optimumtact commented
> Want to point you to the PR that added it: #27099

SAY WHY YOU FUCKING APE @JohnFulpWillard

2022-09-01 22:09 UTC, JohnFulpWillard commented
I left this as a comment while on a rush, I saw the double ``return round(cost * amount)`` and thought something was up.
Looking at it now that I have time, I have one comment about it, otherwise it's fine, ``k_elasticity`` is used in get_cost.

2022-09-01 22:10 UTC, JohnFulpWillard commented on code/modules/cargo/exports.dm
>  /datum/export/proc/get_cost(obj/O, apply_elastic = TRUE)
Can you fix this up, check for ``apply_elastic && k_elasticity!=0`` to avoid doing else twice for the same thing.

2022-09-02 01:12 UTC, RandomGamer123 commented
Actually I think I made a bit of a mistake here, since this patch would break elasticity

2022-09-12 23:23 UTC, SuperNovaa41 commented
Feel free to open if you want to come back to it

2022-09-12 23:23 UTC, closed without merging