Displays a popup if you're converted into a shade who needs to follow instructions
tgstation/tgstation pull request #69319
Opened 2022-08-19 17:52 UTC by Jacquerel

## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/68918
A week or so ago I soulstoned someone and they just spent the whole time yelling at people to try and get me killed until I got tired of it and chucked them into some lava. After that they actually noticed the text telling them they were supposed to have been my new spectral pal.
Then I looked at the issue list and noticed someone else had this problem.

Text is easy to miss, so I made it display a big popup instead.
It looks like this.
![image](https://user-images.githubusercontent.com/7483112/185677291-76443c87-452c-4153-ba42-a69edc6b7878.png)
<details>
  <summary>Example with a longer name</summary>

![image](https://user-images.githubusercontent.com/7483112/185677634-bd099652-a511-4f1a-9892-65f9c8aded3e.png)
</details>

## Why It's Good For The Game

If you've suddenly gained a restriction similar to an AI law, it should be as obvious as possible, especially if it's potentially to be the friend of someone who just killed you.

## Changelog

:cl:
qol: Newly created Shades will be told much more clearly that they're supposed to be bound to their master, if they have one.
/:cl:

2022-08-19 18:16 UTC, Jacquerel commented
Why am I getting a linter error on a file I didn't change 😔

2022-08-19 18:52 UTC, tralezab commented
Perhaps this should just be an antag datum at the point where you're following orders that may or may not be antagonistic

2022-08-19 22:11 UTC, Jacquerel commented
> Perhaps this should just be an antag datum at the point where you're following orders that may or may not be antagonistic

I would be happy to do this, the only reason I originally didn't was in case this intersects with policy in some way where "being an antagonist" is a more open role than "being a shade created by the chaplain" is supposed to be.
That would make this implementation easier though probably.

2022-08-19 22:44 UTC, MrMelbert requested changes

2022-08-20 21:37 UTC, Jacquerel commented
Alright it took me a while to untangle the various ways that people can use soulstones on shades and what it normally prints to those shades but I _think_ that the presence of this new datum will now match anything that would previously (and still is) be printed into the chat log.

2022-08-22 11:45 UTC, Jacquerel commented on code/modules/antagonists/shade/shade_minion.dm
> +	var/datum/mind/master
I don't know why I did it that way when this way is much simpler.

2022-08-22 12:52 UTC, Jacquerel commented
I am not too proud to say that I do not know how to satisfy the linter here.
The call stack seems to be upset that the Trigger proc in a different typepath than the one I am calling it on sleeps, even though that typepath cannot be involved.
Am I just not able to have ui_interact trigger inside of this proc due to the no sleep requirement in the chaplain rite? Do I need to refactor the xemo slime clothing change input to not sleep? What do I do about this?

2022-09-01 21:52 UTC, merged