Bananas now have a 1% chance of spawning with the boomerang component
tgstation/tgstation pull request #69325
Opened 2022-08-19 23:55 UTC by Rhials

## About The Pull Request

Bananas now have a 1% chance to be bananarangs on initialization. The description is altered to make it slightly easier to notice, but otherwise there is no indication beyond throwing it.

## Why It's Good For The Game

bananarang hehe :)

Can be used for entertainment, bargaining, or engaging with a rarely seen component within the sandbox. 

## Changelog

:cl:
add: Bananas now have a 1% chance to be boomerang-bananas. These look identical to normal bananas, aside from a slightly unique examine text. Make sure to check your bananas before peeling it to slip the HOS, you may just have a rare item on your hands.
/:cl:

2022-08-19 23:58 UTC, MrMelbert requested changes

2022-08-20 00:01 UTC, Rhials commented on code/modules/hydroponics/grown/banana.dm
> +		desc += " The curve one looks particularly acute."
I swear to god I looked this over like 10 times before submitting how is there a typo

2022-08-20 00:41 UTC, IHateGeese commented
This is the best request i have ever seen, merge now.

2022-08-20 00:44 UTC, drIcepop commented
So when does the banana explode into a maxcap?

2022-08-20 01:06 UTC, Shadowflame909 commented
Clown Buff = fun things to work towards 

I love clown

2022-08-20 03:25 UTC, SuperNovaa41 commented on code/modules/hydroponics/grown/banana.dm
> +		AddComponent(/datum/component/boomerang, throw_range + 4, TRUE)
```suggestion
		AddComponent(/datum/component/boomerang, boomerang_throw_range = throw_range + 4, thrower_easy_catch_enabled = TRUE)
```

2022-08-20 04:44 UTC, Wallemations commented
My favorite kind of PR
The hyper-specific rare random event with little game impact but big comedic value

2022-08-20 13:35 UTC, timothymtorres commented
What happens if you have the squish or prickly trait?  Will the banana detonate on the mob that threw it?

2022-08-22 14:53 UTC, Wallemations commented
> What happens if you have the squish or prickly trait?  Will the banana detonate on the mob that threw it?

If they do I think that's extremely funny

2022-08-22 21:52 UTC, Greenfire575 commented
merge right now

2022-08-23 01:10 UTC, merged

2022-08-31 12:00 UTC, SinfulBliss commented
Do boomerang banana's peels retain this component? That would be pretty epic.