buff the illegal rollingpin
tgstation/tgstation pull request #69340
Opened 2022-08-20 21:37 UTC by TheBoondock

## About The Pull Request
chef has an illegal rollingpin in his vendor but its the same as the regular, so i simply made a subtype with higher force (subject to change)

## Why It's Good For The Game
![image](https://user-images.githubusercontent.com/92416224/185766772-59cb8382-d4eb-4751-aced-ab9ff83bfe73.png)

## Changelog

:cl:
balance: the contraband rollingpin in chef's vendor is actually more powerful than the regular one now
/:cl:

2022-08-20 21:38 UTC, JohnFulpWillard commented on code/game/objects/items/kitchen.dm
> +	force = 20
```suggestion
	force = 60
```

2022-08-20 21:38 UTC, san7890 commented on code/game/objects/items/kitchen.dm
> +	force = 20
.

2022-08-20 21:39 UTC, MrMelbert requested changes
if you're serious make it 12 or 15 force, 10 wound bonus, and give it a unique name at least (i'd like a sprite like a metal rolling pin but w/e)

2022-08-20 21:55 UTC, ArcaneMusic commented
> if you're serious make it 12 or 15 force, 10 wound bonus, and give it a unique name at least (i'd like a sprite like a metal rolling pin but w/e)

The Roller Pin? (Like it's an industrial conveyor belt roller)

2022-08-20 21:58 UTC, Shadowflame909 commented
Sprite edit and change it from tan to black. Now its a syndicate rolling pin

2022-08-21 02:09 UTC, ATH1909 commented
needs a different name to distinguish it from a normal one

2022-08-21 07:55 UTC, newfren commented
20 is so fucking high lmao

2022-08-23 20:55 UTC, wesoda25 commented
No no it's good, this will introduce a new rolling-pin centric meta to the game

2022-09-14 02:28 UTC, optimumtact commented
if this goes stale again ur dead melb

2022-09-15 03:17 UTC, MrMelbert requested changes

2022-09-15 16:07 UTC, TheBoondock commented on code/game/objects/items/kitchen.dm
> +	force = 12
Idk bro the handle kinda insulated it no?

2022-09-18 23:17 UTC, MrMelbert approved these changes

2022-09-18 23:33 UTC, merged