Food Expansion 4! The great salad update and more
tgstation/tgstation pull request #69355
Opened 2022-08-21 09:55 UTC by MidoriWroth

## About The Pull Request

This is my fourth food expansion PR, adding and changing quite a few things.
This PR will:

- Add 7 different types of salads
- Add a new ingredient supply beacon box called 'Salads', which includes ingredients used for the salad recipes
- Give honey and cherry jelly their own containers, and allow both of them to be ordered from the produce console
- Make cherry jelly actually nourish you when consumed
- Add paçoca, a Brazilian peanut candy requested by @GuillaumePrata 
- Add mashed potatoes
- Add shepherds pie
- Add Cullen skink

![image](https://user-images.githubusercontent.com/18170896/185785574-a1980483-83c5-48aa-8a63-2c21c4daf1ba.png)

## Why It's Good For The Game

Not only is there a severe lack of salad-type foods, but the majority of the currently craftable salads are either gimmicks or get you high from space drugs when eaten, which is a bit silly. This PR will add a big variety of actual popular salads for the vegetarian and health-conscious station dwellers.

Honey is an ingredient I do not see used often, partially because it can be an annoying slog to get from botany. Allowing it to be ordered will encourage more people to make honey-based foods, such as the honey-nut bar and honey sweetroll. Cherry jelly is not hard to come by, but I see no reason for it to not be ordered as well since it is now getting more use from my previous PRs.

And of course, more foods add more variety and creativity to chef menus

## Changelog

:cl:
add: Added 7 new types of various salads. Vegetarians rejoice!
add: Added mashed potatoes
add: Added shepherds pie, because station dwellers gotta grow big and strong somehow
add: Added Cullen skink
add: Added paçoca, a Brazilian peanut desert
add: Honey and cherry jelly have their own containers which can be ordered from a produce console or made at a chem master
add: Consuming jelly now actually nourishes you
imageadd: Added sprites for all the new tasty foods
/:cl:

2022-08-21 13:19 UTC, BlueMemesauce commented
I don't think honey should be orderable as it is quite a powerful chem

2022-08-21 13:46 UTC, Jacquerel commented
I also think that you should need to do beekeeping to get honey, but I like the rest of the salads.

2022-08-21 15:40 UTC, GuillaumePrata commented
> I don't think honey should be orderable as it is quite a powerful chem

The real issue IMO is that honey is a stupidly good general medical chem where it should have stayed as cooking/flavorful chem instead.
I'm not an expert but a quick google fu told me that honey is good for healing wounds and burns, would be a nice ghetto way to deal with wounds instead of our version now which is a boring weaker Omnizine.

2022-08-21 17:55 UTC, Jacquerel commented
Even if honey wasn't a powerful healing chemical I think it is good for it to only be produced by beekeeping, we don't need the chef to be able to make every single kind of food available without interacting with other departments.
If that means they get made less often that's fine.

2022-08-21 18:25 UTC, MidoriWroth commented
Very well, I’ll make it unorderable, but I’m keeping the bottle in for condimaster purposes =)

2022-08-21 18:49 UTC, MrDoomBringer commented
Could you make the honey and jelly bottle a bit smaller (e.g. closer to salt/pepper shaker size)? A condiment bottle's sprite taking up an entire tabletop always looks a bit weird to me

2022-08-21 23:16 UTC, MidoriWroth commented
> Could you make the honey and jelly bottle a bit smaller (e.g. closer to salt/pepper shaker size)? A condiment bottle's sprite taking up an entire tabletop always looks a bit weird to me

![image](https://user-images.githubusercontent.com/18170896/185814960-33bcd307-94fd-4ab0-82d7-f02d5dd0d6b4.png)
How's that?

2022-08-22 05:02 UTC, optimumtact commented
just remove the healing from honey it's stupid

2022-08-22 16:28 UTC, MrDoomBringer commented
@MidoriWroth Looks good 👍

2022-08-22 21:35 UTC, dragomagol requested changes
Also, do we need the honey png if we're not adding it to the order console?

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +		/obj/item/food/seaweedsheet = 1
```suggestion
		/obj/item/food/seaweedsheet = 1,
```
This list should still end with a comma 
![image](https://user-images.githubusercontent.com/66640614/186022695-b3d419f3-4335-481e-bc4a-17ae192ae212.png)

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +		/datum/reagent/consumable/milk = 1
```suggestion
		/datum/reagent/consumable/milk = 1,
```

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
> +		/datum/reagent/consumable/salt = 2
```suggestion
		/datum/reagent/consumable/salt = 2,
```

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
> +		/obj/item/food/grown/garlic = 1
```suggestion
		/obj/item/food/grown/garlic = 1,
```

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
> +		/datum/reagent/consumable/quality_oil = 2
```suggestion
		/datum/reagent/consumable/quality_oil = 2,
```

2022-08-22 21:35 UTC, dragomagol commented on code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
> +		/datum/reagent/consumable/quality_oil = 5
You get the idea, these should all have trailing commas

2022-08-23 00:11 UTC, MidoriWroth commented
Ah okay, every other food has the last ingredient not with a comma, so I just followed that pattern.

2022-08-23 04:22 UTC, VladinXXV commented
I like your greek salad, but why no olives? The sprite is missing them and so is the recipe. #67239 added olives, so I think you should be able to add them in there.

2022-08-23 06:45 UTC, MidoriWroth commented
> I like your greek salad, but why no olives? The sprite is missing them and so is the recipe. #67239 added olives, so I think you should be able to add them in there.

oops lmao, i had it in my pre-planned recipe but i never included it in the code, thanks!

2022-08-23 23:45 UTC, dragomagol commented on code/game/objects/items/food/soup.dm
> +	desc = "A thick Scottish soup made of smoked fish, potatoes and onions.."
```suggestion
	desc = "A thick Scottish soup made of smoked fish, potatoes and onions."
```

2022-08-23 23:46 UTC, dragomagol commented on code/game/objects/items/food/soup.dm
> +	desc = "A thick Scottish soup made of smoked fish, potatoes and onions.."
Other than this one thing, lgtm

2022-08-23 23:55 UTC, dragomagol approved these changes

2022-08-25 04:11 UTC, Imaginos16 approved these changes
Its fine.

2022-08-25 04:16 UTC, merged