More obvious hijacker
tgstation/tgstation pull request #69377
Opened 2022-08-22 11:15 UTC by necromanceranne

## About The Pull Request

Let's everyone know who is attempting to hijack the shuttle once a stage is completed.

## Why It's Good For The Game

While the chaos of finding out who did it is fun, maybe you should try and cause a little more chaos in that cockpit before attempting to hijack. Currently you can just sorta get away with it a bit since nobody around you is informed about your hacking attempts. That seems entirely unrealistic and not exactly user friendly.

## Changelog

:cl:
balance: Sends a chat alert to those nearby when someone completes a stage of a hijack.
/:cl:

2022-08-22 13:50 UTC, exymian commented
"[user.name] appears to be tampering with [src]."

is the message

2022-08-22 21:17 UTC, ATH1909 commented
shouldn't this be BEFORE the do_after(), since finishing a hacking stage already makes a big announcement that's broadcast to everyone?

2022-08-24 02:41 UTC, necromanceranne commented
It does make a big announcement but not who did it. That's the issue to resolve for anyone nearby.

I would at it to the start, but I think this is fairer.

2022-08-24 21:47 UTC, ShizCalev requested changes

2022-08-24 21:47 UTC, ShizCalev commented on code/modules/shuttle/emergency.dm
> +	if(!HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
did you test this

2022-08-25 21:24 UTC, necromanceranne commented on code/modules/shuttle/emergency.dm
> +	if(!HAS_TRAIT(user, TRAIT_HANDS_BLOCKED))
Oops

2022-08-30 02:05 UTC, merged