Asking critters to identify themselves works
tgstation/tgstation pull request #69371
Opened 2022-08-22 05:41 UTC by tralezab

## About The Pull Request

Asking basic or simple mobs to identify themselves will now actually get them to say their REAL name

![image](https://user-images.githubusercontent.com/40974010/185847204-22cb8237-4f09-456b-ade0-3e9cf3fd1fe1.png)

## Why It's Good For The Game

~IDENTIFY
the kid named cockroach:~

I like this as a small easter egg functionality, being able to defacto name critters stuff.

## Changelog

:cl:
add: You can now ask critters their name with voice of god. Their ACTUAL name.
/:cl:

2022-08-22 05:47 UTC, GoldenAlpharex commented
No more Cockroach spam........ 😔
![image](https://user-images.githubusercontent.com/58045821/185847971-5f31704e-b546-4698-85f1-4e4891495f3a.png)

2022-08-22 06:25 UTC, Shadowflame909 commented
we love more cross-feature interaction

2022-08-22 06:57 UTC, MrMelbert requested changes

2022-08-22 15:37 UTC, Watermelon914 requested changes

2022-08-22 15:37 UTC, Watermelon914 commented on code/datums/voice_of_god_command.dm
> +	if(isanimal_or_basicmob(target) && target.name == initial(target.name) && target:gold_core_spawnable == FRIENDLY_SPAWN)
you should just properly typecast here instead of using :

2022-08-23 19:19 UTC, ShizCalev commented on code/datums/voice_of_god_command.dm
> +	if(isanimal(target))
```suggestion
	else if(isanimal(target))
```

2022-08-23 19:20 UTC, ShizCalev approved these changes

2022-08-23 19:41 UTC, merged

2022-09-10 23:27 UTC, LePiromano commented
https://user-images.githubusercontent.com/55637865/189505091-081b4f26-6cc1-4f80-aee2-0d2ad95ef6f0.mp4