[MDB IGNORE] Fix ticket machines breaking, behaving unexpectedly and causing runtimes
tgstation/tgstation pull request #69406
Opened 2022-08-23 14:15 UTC by distributivgesetz

## About The Pull Request

The ticket machine used to desynchronize very easily due to out of bounds list accesses when trying to access the current ticket. The list that keeps track of tickets has been repurposed more into a queue, pushing all elements to the front with .Cut(1,2), compared to before where it would leave a space of nothingness where tickets used to be. 

Also, there was a ticket machine in a ruin in icebox which had the default id, causing an id collision.

## Why It's Good For The Game

bgug fix

## Changelog

:cl:
fix: HoPs all around the Spinward Sector scream in joy as their beloved ticket machine finally rises back from the dead.
qol: Add more examines to ticket machines and tickets, giving info about people's spot in queue and so on.
/:cl:

2022-08-24 21:40 UTC, ShizCalev commented on code/modules/paperwork/ticketmachine.dm
> +	src.number = number
name the arg something else, src.number makes me very sad.

2022-08-24 21:41 UTC, ShizCalev requested changes

2022-08-24 21:41 UTC, ShizCalev commented on code/modules/paperwork/ticketmachine.dm
> +	src.number = number
name the arg something else, src.number makes me very sad.

2022-08-24 21:59 UTC, distributivgesetz commented
what

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	if(machine.current_ticket == null)
```suggestion
	if(isnull(machine.current_ticket))
```

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
>  		return
Should emagged ones also call ``update_appearance()``? Maybe we can just remove this return if so.

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	if(number != null)
```suggestion
	if(!isnull(number))
```

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +// ???????????????
maybe you can move this piece of code to paper?

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	///To whom are we linked?
Linked to what? please clarify here

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	var/datum/weakref/linked
weakref vars should preferably end in ``_ref`` so it's easier to know they're a weakref, please do so if you have the time.

2022-08-25 02:55 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	var/obj/item/ticket_machine_ticket/theirticket = new /obj/item/ticket_machine_ticket(get_turf(src), ticket_number)
```suggestion
	var/obj/item/ticket_machine_ticket/theirticket = new (get_turf(src), ticket_number)
```

2022-08-25 02:56 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +		maptext = saved_maptext
This should be in ``Initialize()``

2022-08-25 02:56 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +	if(number != null) // dont make a zero ticket or ill cry
```suggestion
	if(!isnull(number)) // dont make a zero ticket or ill cry
```

2022-08-25 09:29 UTC, JohnFulpWillard commented on code/modules/paperwork/ticketmachine.dm
> +/obj/item/ticket_machine_ticket/Initialize(loc, num)
```suggestion
/obj/item/ticket_machine_ticket/Initialize(mapload, num)
```

2022-08-25 11:16 UTC, JohnFulpWillard commented
Thank you for all your work

2022-08-25 11:18 UTC, merged

2022-08-25 11:19 UTC, distributivgesetz commented
Thanks for the fast reviews, I swear I'll learn this language someday lmao