Adds two modes for BuildMode
tgstation/tgstation pull request #69428
Opened 2022-08-24 04:51 UTC by AnywayFarus

## About The Pull Request

Adds two modes for BuildMode, with personal icons

- Tweak Components Rating - for easier upgrade of machinery.
- ProcCall - for fast ProcCall on objects.

## Why It's Good For The Game

This can help the staff in carrying out all sorts of events, all sorts of in-game tests, because it provides a convenient and nimble toolkit.

## Changelog

:cl: Vishenka0704
add: Added "ProcCall" & "Tweak Components Rating" modes in buildmode
/:cl:

2022-08-30 23:25 UTC, san7890 reviewed
Minor things.

2022-08-30 23:25 UTC, san7890 commented on code/modules/buildmode/submodes/tweakcomps.dm
> +			to_chat(target_client, span_warning("That machinery don't have components"))
```suggestion
			to_chat(target_client, span_warning("This machinery doesn't have components!"))
```

Grammar.

2022-08-30 23:25 UTC, san7890 commented on code/modules/buildmode/submodes/tweakcomps.dm
> +		Left Mouse Button on machinery = Sets components choosen rating.\n\
```suggestion
		Right Mouse Button on buildmode button = Choose the rating of the components.\n\
		Left Mouse Button on machinery = Sets the chosen rating of the components on the machinery.\n\
```

Grammar, this one might be a bit lengthy though?

2022-08-30 23:25 UTC, san7890 commented on code/modules/buildmode/submodes/tweakcomps.dm
> +		to_chat(target_client, span_warning("This object is not machinery!"))
```suggestion
		to_chat(target_client, span_warning("This isn't machinery!"))
```

We can afford to be a little less verbose here, I feel.

2022-08-30 23:25 UTC, san7890 commented on code/modules/buildmode/submodes/proccall.dm
> +		to_chat(target_client, "<font color='red'>Error: callproc_datum(): type [object.type] has no proc named [proc_name].</font>", confidential = TRUE)
```suggestion
		to_chat(target_client, "span_warning(Error: callproc_datum(): type [object.type] has no proc named [proc_name].)", confidential = TRUE)
```

No need to manually set the color when we have spans that do the heavy lifting for us.

2022-09-01 21:55 UTC, Arturlang commented
Any chance of adding zone saving from bee or somesuch?

2022-09-01 22:18 UTC, AnywayFarus commented
> Any chance of adding zone saving from bee or somesuch?

I have no idea what you mean to be honest :)

2022-09-02 14:02 UTC, Arturlang commented
@AnywayFarus If you're not being sarcastic, I mean using build mode for saving certain parts of the map to client's disk as a DMM. I'm fairly sure bee already has this
https://github.com/BeeStation/BeeStation-Hornet/pull/1522

2022-09-02 19:10 UTC, AnywayFarus commented
> @AnywayFarus If you're not being sarcastic, I mean using build mode for saving certain parts of the map to client's disk as a DMM. I'm fairly sure bee already has this [BeeStation/BeeStation-Hornet#1522](https://github.com/BeeStation/BeeStation-Hornet/pull/1522)

maybe in another PR :(

2022-09-04 04:33 UTC, ShizCalev commented on code/modules/buildmode/submodes/proccall.dm
> +	if(!object || !is_valid_src(object))
is_valid_src handles !object

2022-09-06 17:18 UTC, SuperNovaa41 requested changes

2022-09-06 17:18 UTC, SuperNovaa41 commented on code/modules/buildmode/submodes/proccall.dm
> +		to_chat(target_client, "span_warning(Error: callproc_datum(): type [object.type] has no proc named [proc_name].)", confidential = TRUE)
```suggestion
		to_chat(target_client, span_warning("Error: callproc_datum(): type [object.type] has no proc named [proc_name].)", confidential = TRUE)
```

2022-09-06 17:19 UTC, AnywayFarus commented on code/modules/buildmode/submodes/proccall.dm
> +		to_chat(target_client, "span_warning(Error: callproc_datum(): type [object.type] has no proc named [proc_name].)", confidential = TRUE)
hah.

2022-09-07 23:08 UTC, tralezab requested changes
some stuff

2022-09-07 23:08 UTC, tralezab commented on code/modules/buildmode/submodes/tweakcomps.dm
> +	else
if the function ends, you don't need an else case

2022-09-07 23:08 UTC, tralezab commented on code/modules/buildmode/submodes/tweakcomps.dm
> +	var/rating = null
document this var

2022-09-07 23:08 UTC, tralezab commented on code/modules/buildmode/submodes/tweakcomps.dm
> +	else
same as above, return ends a function so don't put an else case

2022-09-07 23:08 UTC, tralezab commented on code/modules/buildmode/submodes/tweakcomps.dm
> +			return
```suggestion
		if(!object.component_parts)
			to_chat(target_client, span_warning("This machinery doesn't have components!"))
			return
		for(var/obj/item/stock_parts/P in object.component_parts)
			P.rating = rating
		object.RefreshParts()
		
		SSblackbox.record_feedback("nested tally", "admin_toggle", 1, list("Machine Upgrade", "[rating]")) //If you are copy-pasting this, ensure the 2nd parameter is unique to the new proc!
```

2022-09-08 00:49 UTC, merged