"What are you in for?" Prisoners can now select their capital offense.
tgstation/tgstation pull request #69446
Opened 2022-08-24 23:44 UTC by tralezab

## About The Pull Request

New preference, like security department, but for prisoners. They can pick why they're in prison, and they'll get a record about it roundstart.
Classified and Other are for people who want to build their own background, that none of the options currently fit.

Current options:
* Abhorrent Criminal Negligence = Incompetently risked numerous lives.
* Attempted Development of Cloning = Attempted illegal research in the cloning sphere. Cloning, cloning construction, and cloning-related R&D was outlawed in 2560.
* Attempted Murder = Attempted to maliciously kill someone.
* Classified = Consult Legal.
* Corporate Espionage = Conducted espionage against Nanotrasen for commercial purposes.
* Counterfeiting = Engaged in widespread fraud.
* Enemy of the Corporation = Acted as or knowingly aided an enemy of Nanotrasen.
* Grand Sabotage = Engaged in malicious destructive actions seriously threatening Nanotrasen employees and or infrastructure.
* Grand Theft = Stole items of high value or sensitive nature.
* Identity Theft of High-Ranking Figure = Impersonated a high-ranking figure.
* Murder = Maliciously killed someone.
* Mutiny = Attempted to overthrow/subvert Chain of Command.
* Other = Consult Legal.
* Tampering of Artificial Intelligence = Uploaded malicious negligent or otherwise blacklisted directives to an Artificial Intelligence.
* Worship of Blacklisted Deities = Practiced worship of blacklisted deities.

## Why It's Good For The Game

Suggested by https://tgstation13.org/phpBB/viewtopic.php?p=650605#p650605
And I agree with their post:
> It's really dumb whenever I ask them "Well what are you in the prison for?" and they just say some dumb shit like "Oh I just started there.".

This should be a nice little bit of flavor for a mostly roleplay-centric job.

## Changelog

:cl:
add: Prisoners can now select their crime in their character preferences.
/:cl:

2022-08-24 23:50 UTC, ArcaneDefence commented
Where the fuck is tax evasion?

2022-08-24 23:51 UTC, CRITAWAKETS commented
I think it needs a few silly ones like "Excessive Jaywalking"

2022-08-24 23:52 UTC, tralezab commented
> I think it needs a few silly ones like "Excessive Jaywalking"

I tried to keep it serious but kept the option open for Other, basically

2022-08-25 00:08 UTC, Mothblocks requested changes

2022-08-25 00:08 UTC, Mothblocks commented on code/modules/client/preferences/prisoner_crime.dm
> +/datum/preference/choiced/prisoner_crime/is_accessible(datum/preferences/preferences)
This should probably check if your highest job is prisoner, just like AI core display: https://github.com/tgstation/tgstation/blob/d91390a4474e511279b6ee7525c5982266b9a858/code/modules/client/preferences/ai_core_display.dm#L18-L22

2022-08-25 00:08 UTC, Mothblocks commented on code/modules/client/preferences/prisoner_crime.dm
> +	return pick(GLOB.prisoner_crimes)
This block shouldn't be necessary, this is the default.

2022-08-25 00:08 UTC, Mothblocks commented on code/_globalvars/lists/flavor_misc.dm
> +GLOBAL_LIST_INIT(prisoner_crimes, list(
Doc comment both these lists

2022-08-25 00:29 UTC, MrMelbert requested changes

2022-08-25 01:17 UTC, CursedBirb commented
Could you add something like Malpractice = Stolen limbs and organs of several crewmembers

2022-08-25 01:40 UTC, timothymtorres commented
This is cewl but please add kidnapping and narcotics to the list

2022-08-25 02:27 UTC, Farquaar commented
Any way to ask for a random crime so I don't know what I've done until I spawn in?

2022-08-25 03:06 UTC, the-orange-cow commented
Consideration: maybe something along the lines of "Biological Terrorism = Created and released a lethal biological agent/lifeform", for all the botanists, virologists, geneticists, xenobiologists, and cytologists out there.

I suppose that grand sabotage/murder covers this, but it has a bit more personalized flair to it.

2022-08-25 04:47 UTC, Jezzared commented
Considering we have a "Protective Custody" alt title, i recommend a background to go with it.

2022-08-25 05:16 UTC, Mothblocks commented
arm youve just invented a new brain damage json file for everyone to add onto what have you done

2022-08-25 20:26 UTC, tralezab commented
> Any way to ask for a random crime so I don't know what I've done until I spawn in?

will add

> arm youve just invented a new brain damage json file for everyone to add onto what have you done

LOOK I DIDNT MEAN TO

2022-08-25 20:26 UTC, tralezab commented
> Consideration: maybe something along the lines of "Biological Terrorism = Created and released a lethal biological agent/lifeform", for all the botanists, virologists, geneticists, xenobiologists, and cytologists out there.
> 
> I suppose that grand sabotage/murder covers this, but it has a bit more personalized flair to it.

will add

2022-08-25 20:37 UTC, tralezab commented
> Any way to ask for a random crime so I don't know what I've done until I spawn in?

oh and this, will do as well

2022-08-26 02:32 UTC, Mothblocks commented on code/modules/jobs/job_types/prisoner.dm
> +/datum/job/prisoner/proc/add_pref_crime(datum/datacore/source, mob/living/carbon/human/injected_human, list/new_records)
Needs SIGNAL_HANDLER

2022-08-29 19:24 UTC, merged