Make hulks orkier
tgstation/tgstation pull request #69469
Opened 2022-08-25 21:46 UTC by optimumtact

RED WUNZ GO FASTA

2022-08-25 21:47 UTC, LemonInTheDark requested changes
they have to waaaaaaaagh over the radio too, otherwise this is a balance change

2022-08-25 21:47 UTC, san7890 commented on code/datums/mutations/hulk.dm
> +	source.say("WAAAAAAAAAAAAAAGH!", forced="hulk")
```suggestion
	source.say(";WAAAAAAAAAAAAAAGH!", forced="hulk")
```

they gotta yell it over common player

2022-08-25 21:47 UTC, optimumtact commented
> they have to waaaaaaaagh over the radio too, otherwise this is a balance change

No they dont, I'm headcoder

2022-08-25 21:48 UTC, LemonInTheDark commented
yes boss

2022-08-25 21:48 UTC, LemonInTheDark approved these changes

2022-08-25 21:48 UTC, san7890 commented
*sadly salutes*

2022-08-25 21:48 UTC, san7890 approved these changes

2022-08-25 22:55 UTC, DAKKA-WAAAGH commented
### **BASED**

2022-08-26 00:47 UTC, Shadowflame909 commented
we become orks..but now no one can shit on hulk outside of its mechanical design

based. Ork Smash with giant wooden club. (science end-game tech)

2022-08-26 06:16 UTC, Colovorat commented
![image](https://user-images.githubusercontent.com/35225170/186835148-b47a5414-ac76-4207-9c40-2d5ff5793145.png)

2022-08-26 11:45 UTC, Dorsisdwarf commented
I think that the radio scream is a pretty important tool for avoiding stealthy hulks smashing into places undetectably.

2022-08-26 12:09 UTC, Shadowflame909 commented
> I think that the radio scream is a pretty important tool for avoiding stealthy hulks smashing into places undetectably.

fair opinion but simple mobs can do the same thing as hulks + hulks arms now break from smashing walls + this is only being made because its the 3rd main cause of hulk seethe other then "my stun baton no worke"

It will be fine for balance!!

2022-08-26 16:47 UTC, drIcepop commented
GREEN IZ BEST

2022-08-26 21:10 UTC, optimumtact commented
> I think that the radio scream is a pretty important tool for avoiding stealthy hulks smashing into places undetectably.

counterpoint it's annoying

2022-08-27 09:22 UTC, merged

2022-08-27 09:22 UTC, Timberpoes commented
Shit my finger slipped I didn't mean to post the changelog into the commit comment and merge it oh well nothing to be done now it's permanently in the game and will never be removed. uwu

2022-08-27 09:24 UTC, optimumtact commented
> Shit my finger slipped I didn't mean to post the changelog into the commit comment and merge it oh well nothing to be done now it's permanently in the game and will never be removed. uwu

changelogs come from the PR body though, not the commit log

2022-08-27 09:24 UTC, optimumtact commented
also I just noticed I put orks instead of hulk

2022-08-27 09:33 UTC, LemonInTheDark commented
bad news besties, you failed to place a space after 🆑, so this change will go totally undocumented in the changelog