mecha logs are now accurate
tgstation/tgstation pull request #69595
Opened 2022-08-31 18:32 UTC by magatsuchi

## About The Pull Request

mecha logs now accurately give information to the current occupant of the mecha in combat logs (and adds a disclaimer if there are multiple occupants in said mecha (and at that point its an admin issue))

## Why It's Good For The Game

logging good

## Changelog

:cl:
admin: mecha combat now has accurate logging
/:cl:

2022-08-31 18:40 UTC, dragomagol approved these changes

2022-09-01 00:48 UTC, ShizCalev requested changes

2022-09-01 00:48 UTC, ShizCalev commented on code/modules/projectiles/projectile.dm
> +		var/mob/occupant = chassis.occupants[1]
mecha can have multiple people in it controlling different systems. (ie one is a pilot, one controls weapons, ect)

this needs to be taken up to isvehicle() regardless. 

use `vehicle.return_controllers_with_flag(VEHICLE_CONTROL_EQUIPMENT)` for a list of mobs that have equipment (weapons) access.

2022-09-02 00:38 UTC, ShizCalev commented
@magatsuchi updated my comment w/ the needed code for ya.

2022-09-06 01:48 UTC, closed without merging