Fixes police hats covering your hair.
tgstation/tgstation pull request #69643
Opened 2022-09-01 18:05 UTC by JohnFulpWillard

## About The Pull Request

Makes police hats a subtype of Warden's hats, so they still are security-level armor, without covering your hair like helmets do.
This was gone unnoticed because the item is very limited in-game. I've been in this place before https://github.com/tgstation/tgstation/pull/66872 ...

I also renamed the gravity generator updatepaths because it's been inconsistent with the rest of the updatepaths for a while now.

## Why It's Good For The Game

I hate it when a hats that don't cover your head end up turning you bald.

## Changelog

:cl:
fix: Police hats no longer turn you bald while worn.
/:cl:

2022-09-01 18:12 UTC, Kapu1178 commented
this works but you can also just remove the HIDEHAIR flag

2022-09-01 18:14 UTC, JohnFulpWillard commented
> this works but you can also just remove the HIDEHAIR flag

I don't want to do that because I hate snowflake solutions.

2022-09-01 18:41 UTC, san7890 commented on tools/UpdatePaths/Scripts/69643_police_hat.txt
> +/obj/item/clothing/head/helmet/police : /obj/item/clothing/head/warden/police
```suggestion
/obj/item/clothing/head/helmet/police : /obj/item/clothing/head/warden/police{@OLD}
```

Did you update the DMM manually?

2022-09-02 21:15 UTC, ShizCalev requested changes

2022-09-02 21:15 UTC, ShizCalev commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/warden/police
pssst.

helmet.dm

2022-09-02 21:37 UTC, Iamgoofball commented
sorry bro im just gonna say it, it's more snowflake to repath it to warden helmet than to make it hide the hair

2022-09-02 22:28 UTC, ShizCalev commented
![image](https://user-images.githubusercontent.com/6209658/188242533-7f9d0d1c-4e24-45d5-82f4-0eb01e7d46dd.png)
![image](https://user-images.githubusercontent.com/6209658/188242553-5ffb5e84-aad2-4c19-a236-49daa59ae796.png)
![image](https://user-images.githubusercontent.com/6209658/188242592-03522ef4-f13e-4a30-b7d0-6fd98110a120.png)
balance change?

2022-09-02 22:58 UTC, JohnFulpWillard commented
> sorry bro im just gonna say it, it's more snowflake to repath it to warden helmet than to make it hide the hair

The sprite is a hat, it's called a hat, I don't see why it should be treated like a helmet.
I also found out they share the same icon and icon state as the warden's default hat, so the only difference between the two was their name, and description.

2022-09-06 17:47 UTC, merged