Unit tests say signal gets the correct list passed with it
tgstation/tgstation pull request #69854
Opened 2022-09-12 05:16 UTC by MrMelbert

## About The Pull Request

#63939 broke this once, #69844 almost broke this again, so I decided to unit test this

`COMSIG_MOB_SAY` signal handlers override the arglist it is passed to change parameters of the say. Such as changing the message (adding a stutter or capslocking), changing language, adding spans, etc. 

This means it needs to get the arglist, exactly, by reference - not a copy of it or anything, otherwise the overriding parameter aspect won't work and a lot of say stuff breaks 

In the meanwhile I learned some byond knowledge, in that every child call of a proc-call has its own arglist, which is its own reference. So, attempting to use a dummy mob instead of doing it on the `/living` level results in two different refs. 

## Why It's Good For The Game

Making sure message modifiers work is pretty neat

2022-09-12 15:26 UTC, timothymtorres commented on code/modules/mob/living/living_say.dm
>  	var/sigreturn = SEND_SIGNAL(src, COMSIG_MOB_SAY, args, message_range)
Appending args by adding them to the end of the parameters does not work.  I tested this on tg master (not my hivemind branch)

![Code_yXIlmidcjY](https://user-images.githubusercontent.com/5195984/189693736-d3988125-22d2-4b1a-b74d-0cbf55defdea.png)

The `message_range` arg does not get added to args.  It gets thrown away.

2022-09-14 02:05 UTC, Mothblocks requested changes
This is my first time seeing people mutate args through signals and honestly I hate it, no wonder this keeps breaking, it's insane

2022-09-14 02:05 UTC, Mothblocks commented on code/modules/unit_tests/say.dm
> +	TEST_ASSERT_EQUAL(REF(say_args), source.last_say_args_ref, "Say signal didn't get the argslist of say as a reference. \
The juggling here shouldn't be necessary. if `REF(say_args) == source.last_say_args_ref`, then the lists would equal each other too.

2022-09-16 15:00 UTC, Mothblocks commented
Mutating lists through signals is whatever but specifically doing it to args is insane

2022-09-16 15:01 UTC, merged