Adds pronoun identifier to voice of god
tgstation/tgstation pull request #70102
Opened 2022-09-24 04:22 UTC by pootispense

## About The Pull Request

Heya there! I was playing this game with my friend and we were playing with lavaland loot and I recently had the idea that you could improve on one of the orders from Colossus... hmmm. You see, in the spaceman game, examining will give you their preferred pronouns... Getting this information doesn't make much sense if you approach it just by being in this universe. No one has publicly stated how they want to be addressed, it's just meta information. So, let's squeeze this information out of them to make sure we perfectly treat these meek people as we channel God's voice.

## Why It's Good For The Game
I don't know what to put here other than what I put above, but although I think it's a good idea to get that information (which you are otherwise unable to get via meta-methods and the examine box), I just thought it would be fun if everyone followed your orders and gave the way they wanted to be identified. I thought about having it give all their details like bank account numbers or work at the station which would be fun, but when you think about other species it can get confusing quickly (not to mention just how overpowered that one loot would then become).

btw sorry if I screwed up somewhere, I read a bunch of the guidelines and I hope this works even though I didn't set up git. sorry if the justification isn't great either I don't mind if this doesn't make it into the game I just thought it was a good idea and spent too long combing through the code to figure out how this could work to not throw it up

## Changelog

:cl:
add: New change to the voice of God command: Using the "Identify" phrase will now force the targets to say their preferred pronouns along with their name.
/:cl:

2022-09-24 04:51 UTC, itseasytosee commented
> I thought about having it give all their details like bank account numbers or work at the station which would be fun, but when you think about other species it can get confusing quickly

This would be pretty easy to implement. You just need a `ishuman` check if you want to make sure they are a human or human subtype, you can also use the get_bank_account() which works on all living subtypes.

2022-09-24 12:22 UTC, JohnFulpWillard requested changes
Make it a separate command please

2022-09-24 23:58 UTC, Mothblocks commented
lol

2022-09-25 00:16 UTC, optimumtact commented
I don't think this is a real PR, so feel free to contribute some fixes instead.

2022-09-25 00:16 UTC, closed without merging

2022-09-25 01:09 UTC, Toastgoats commented
![pronouns](https://user-images.githubusercontent.com/63932673/192123984-b97d521f-9044-482f-8417-0b8c0a003125.JPG)