Adds Balloon Alerts To Valve Open/Closing
tgstation/tgstation pull request #70138
Opened 2022-09-26 02:39 UTC by san7890

## About The Pull Request

Hey there,

I was talking with someone trying to get the hang of atmospherics, and they were a bit confused on why their digital valve didn't seem to be "on". Well, the thing is that it was on, they just didn't know to peek at that small little green dial on the digital valve. Although the animations are quite explanatory to someone like me who's been doing this for 3+ years, I definitely can see how it's more confusing to someone new. So, let's toss in a small balloon alert (that only plays after the animation is complete, as to not interfere with the nice spritework) to provide a nice alert as to what exactly they're doing.

## Why It's Good For The Game

![image](https://user-images.githubusercontent.com/34697715/192183100-d477c5a8-e368-47e5-b5f3-ddaeeea4985c.png)

![image](https://user-images.githubusercontent.com/34697715/192183113-e897a05d-5382-424e-87e7-7d5d078fb293.png)

Pretty helpful, I think. You can argue it increases the "hand-holding" of atmospherics in some way, but it's complicated enough for new people, man.

## Changelog

:cl:
qol: Whenever you open or close an atmospherics valve, you should now get a balloon alert notifying you of that exact action.
/:cl:

2022-09-26 03:15 UTC, LemonInTheDark approved these changes
too much justification, not enough doing more of this

2022-09-26 09:12 UTC, Colovorat commented
![image](https://user-images.githubusercontent.com/35225170/192238821-6b091f1f-4750-4c8f-a9cf-97342366ecf7.png)
change pump to valve

2022-09-26 15:48 UTC, Mothblocks commented
I am your strawman that argues it increases the hand holding of atmospherics Blaaaaagh Buuuurgh Aaaagh

2022-09-27 15:28 UTC, Mothblocks commented on code/modules/atmospherics/machinery/components/binary_devices/valve.dm
> +		balloon_alert_to_viewers("valve opened")
any reason these are to all viewers? most balloon alerts dont do this because it clutters the screen

2022-09-27 17:28 UTC, Mothblocks requested changes
I think they should only show to the usr like other balloon alerts

2022-09-27 23:13 UTC, san7890 commented
> I think they should only show to the usr like other balloon alerts

The issue is that I wrote it like this in case a circuit (which doesn't have a usr) triggers and opens the valve that someone in the vicinity could still get the feedback that the valve is indeed changing. I also wanted it to show to everyone to be more "teachable", such that everyone surrounding a pump could clearly see and articulate what is going on.

2022-09-27 23:26 UTC, Mothblocks commented
That's weird but ok

2022-09-27 23:26 UTC, merged

2022-09-29 13:47 UTC, calliophis-maculiceps commented
NOOOOOOO NOW COLORBLIND PEOPLE CAN PLAY ATMOS, STEALTH BUFF!