Nuclear Operatives Can Now Correctly Get Servant Golems
tgstation/tgstation pull request #70142
Opened 2022-09-26 05:45 UTC by san7890

## About The Pull Request

Hey there,

This was a funny issue a while back caused by how golems inherit antagonist datums, and how the Nuclear Operative Antagonist Datum would _always_, without fail, make you a human. So, let's fix that up a bit by ensuring we cram a cheeky early return in to ensure we don't humanify those golems.

We don't give the golems any equipment because that makes zero logical sense.

## Why It's Good For The Game

![image](https://user-images.githubusercontent.com/34697715/192202054-f5f47400-b547-48c2-a9b2-a944899e3eff.png)

Fixes #67376.

I thought it was pretty funny, but it had to go some time.

## Changelog

:cl:
fix: When a Nuclear Operative makes a golem, they no longer immediately turn into a fully functioning reinforcement.
/:cl:

2022-09-26 05:46 UTC, JohnFulpWillard commented
by allah we have to allow non human nukies

2022-09-26 05:48 UTC, san7890 commented
> by allah we have to allow non human nukies

balance change unfortunately :(

2022-09-26 07:21 UTC, Fikou requested changes
i think the cleaner solution here rather than coding a specific check just for golems is returning if `nukeop_outfit` is false. enslaving minds sets that variable to null.

2022-09-26 07:22 UTC, Fikou commented
also does this fix new golems being made by the previous golems not inheriting the antag status?

2022-09-26 17:52 UTC, san7890 commented
> also does this fix new golems being made by the previous golems not inheriting the antag status?

I changed the check per your feedback and I was able to create a servant golem as a servant golem, which did get the Antagonist Panel + Datum (lost the screenshot)

2022-09-30 13:20 UTC, Fikou approved these changes

2022-09-30 13:21 UTC, merged