Removes ghost check for battlecruiser objective
tgstation/tgstation pull request #70194
Opened 2022-09-28 21:19 UTC by Salex08

## About The Pull Request

Removes the ghost check for the battlecruiser objective

## Why It's Good For The Game

The codeowner has stated he doesnt like the check because it narrows the objective more to appear then needed.

## Changelog

:cl:
balance: rebalanced something
/:cl:

2022-09-28 21:20 UTC, Watermelon914 approved these changes

2022-09-28 21:45 UTC, private-tristan commented
#68057 tried doing this and it was shot down because 'it needed to feel like a full team' or something like that, even though I have played since progtot came out and still have never seen the battlecruiser objective. 
![image](https://user-images.githubusercontent.com/54422837/192894315-d8ff62e2-9027-485c-9587-2f53840bd377.png)

2022-09-28 21:51 UTC, Watermelon914 commented
> #68057 tried doing this and it was shot down because 'it needed to feel like a full team' or something like that, even though I have played since progtot came out and still have never seen the battlecruiser objective.

It was a bad solution, it should've outright removed the check. I don't support these kind of volatile checks for final objectives because you can only get a final objective once.

2022-09-28 22:54 UTC, Mothblocks commented
CC @optimumtact

2022-09-28 22:58 UTC, Salex08 commented on code/modules/shuttle/battlecruiser_starfury.dm
>  				candidates.Splice(1, 2)
I think its to shorten the list

2022-09-28 23:01 UTC, Salex08 commented on code/modules/shuttle/battlecruiser_starfury.dm
>  				candidates.Splice(1, 2)
ahh yeah good that you point it out I forgot to add it in the if clause

2022-09-29 00:12 UTC, Salex08 commented on code/modules/shuttle/battlecruiser_starfury.dm
>  				candidates.Splice(1, 2)
ok fixed it much better

2022-09-29 14:03 UTC, Watermelon914 commented on code/modules/shuttle/battlecruiser_starfury.dm
>  				candidates.Splice(1, 2)
You need to edit and add custom behaviour to the ghost roles that spawn when the roles aren't completely allocated out to every ghost.

2022-09-29 14:05 UTC, Watermelon914 requested changes

2022-09-29 14:06 UTC, Watermelon914 commented on code/modules/mob_spawn/ghost_roles/space_roles.dm
> +	if(!(user.key in antag_team.players_spawned))//one per person unless you get a bonus spawn
you may also want to consider including players from the poll in here

2022-09-29 18:31 UTC, Salex08 commented on code/modules/mob_spawn/ghost_roles/space_roles.dm
> +	if(!(user.key in antag_team.players_spawned))//one per person unless you get a bonus spawn
I thought they get added here
![grafik](https://user-images.githubusercontent.com/33989683/193114131-25be1a57-727b-462f-b5f1-b5c25d318cf7.png)

2022-09-29 18:59 UTC, Salex08 commented on code/modules/mob_spawn/ghost_roles/space_roles.dm
> +	if(!(user.key in antag_team.players_spawned))//one per person unless you get a bonus spawn
alright done

2022-09-29 21:22 UTC, Mothblocks commented
pls stop force pushing if you can help it it makes the notifications maints get harder to interpret

2022-09-29 21:26 UTC, Salex08 commented
> pls stop force pushing if you can help it it makes the notifications maints get harder to interpret

I forgor to sqash

2022-09-29 21:40 UTC, Mothblocks commented
you dont need to squash we squash on merge

2022-09-29 21:52 UTC, merged