Adds some chilling hallucinations
tgstation/tgstation pull request #70253
Opened 2022-10-01 21:27 UTC by Wallemations

## About The Pull Request
Adds some new ice-based hallucinations
The basic freeze lasts about 6 seconds

https://user-images.githubusercontent.com/66052067/193428664-102250a5-202d-4d32-95a4-a9b9371e383d.mp4

The ice sound can also play at random as its own hallucination

The other hallucination adds-

https://user-images.githubusercontent.com/66052067/193428738-bcd319b5-7855-48d4-9481-9f7a3e25f573.mp4

You have a small window to run, but it never helps.

All [sounds](https://freesound.org/people/cognito%20perceptu/sounds/38693/) from [freesound](https://freesound.org/people/InspectorJ/sounds/420875/).org

## Why It's Good For The Game
[More hallucination variety](https://youtu.be/nC8zz95rm8s)

## Changelog

:cl: Wallem
add: A new ice-based hallucination has been added to the game
/:cl:

2022-10-01 21:51 UTC, MrMelbert requested changes

2022-10-01 21:53 UTC, Wallemations commented on code/modules/hallucination/ice_cube.dm
> +	play_ice_sound = FALSE
Initially I did that, but it ended up just making the entire thing not work at all. Making it a subtype was the fix

2022-10-01 21:57 UTC, Wallemations commented on code/modules/hallucination/fake_sound.dm
> +	random_hallucination_weight = 0 // Reserved for The Freezer (& subsidiaries)
sure thing

2022-10-01 22:03 UTC, Wallemations commented on code/modules/hallucination/ice_cube.dm
> +	hallucinator.throw_alert(ALERT_TEMPERATURE, /atom/movable/screen/alert/cold, override = TRUE)
I wanted to make sure it lasted the full time of the freeze, and I forgot I could pass args through the hallucination

2022-10-01 22:04 UTC, Wallemations commented on code/modules/hallucination/ice_cube.dm
> +	var/ice_icon_state = "ice_cube"
sure thing

2022-10-01 22:05 UTC, Wallemations commented on code/modules/hallucination/ice_cube.dm
> +	play_ice_sound = FALSE
oh my god I forgot to put `src.` before the vars

2022-10-01 22:16 UTC, Wallemations commented on code/modules/hallucination/ice_cube.dm
> +	play_ice_sound = FALSE
Alright that should be all the changes in the review handled

2022-10-03 13:10 UTC, bruhman8ghughug commented
RDS miners gonna cry

2022-10-06 05:54 UTC, merged