Fixes mail changing existing nuke codes
tgstation/tgstation pull request #70435
Opened 2022-10-10 18:55 UTC by GoblinBackwards

## About The Pull Request
Fixes an issue with the mail which reveals part of the nuke code that meant it could change the code for the station nuke even it one had already been generated.

## Why It's Good For The Game
bug moment

## Changelog

:cl:
fix: Fixed mail being able to change the stations nuke code when it had already been generated.
/:cl:

2022-10-11 04:11 UTC, optimumtact commented on code/game/objects/items/mail.dm
> +	message_admins("Through junkmail, the self-destruct code was set to \"[self_destruct.r_code]\".")
this needs to be indented

2022-10-11 19:25 UTC, Mothblocks requested changes

2022-10-11 19:25 UTC, Mothblocks commented on code/game/objects/items/mail.dm
> +	if(self_destruct.r_code == "ADMIN")
For this and everywhere that uses "ADMIN", change it to a define somewhere in __DEFINES.

2022-10-11 20:23 UTC, Mothblocks requested changes
One last nit

2022-10-11 20:23 UTC, Mothblocks commented on code/__DEFINES/nuclear_bomb.dm
> +#define DEFAULT_NUKE_CODE "ADMIN"
1. Can you rename it to something like `NUKE_CODE_UNSET` or something to be clear that this is an invalid code meant specifically for this purpose?
2. Auto doc it (triple slashes above the define)

2022-10-11 21:15 UTC, Mothblocks commented on code/game/objects/items/mail.dm
> +	if(self_destruct.r_code == "ADMIN")
```suggestion
	if(self_destruct.r_code == NUKE_CODE_UNSET)
```

2022-10-11 22:20 UTC, Mothblocks approved these changes

2022-10-12 02:57 UTC, merged

2022-10-12 04:26 UTC, timothymtorres commented
Interesting.  I wonder if this is what was causing #70419

2022-10-12 05:07 UTC, Mothblocks commented
@timothymtorres In the round given, the random_nukecode proc is only called once. Not likely.

2022-10-12 21:38 UTC, Mothblocks commented
profiler.json