new ai lawset: repurposed syndOS laws for station use
tgstation/tgstation pull request #70491
Opened 2022-10-13 00:29 UTC by etherware-novice

## About The Pull Request
Adds a new lawset for ai, "Command Control". Its similarly worded to the syndicate lawset, but instead targets command staff, the logic being that command is the most important for running the station, thus protect them from rogue crew, and the command staff can appoint others to be "important" to the ai in case of emergency.

Also you can use the circuitboard in hand to replace the command staff with anything you want, from a certain department to people wearing masks

## Why It's Good For The Game
Adds a bit more chaos, makes the command staff more protected, modifying it with the circuitboard can lead to zany situations like rouge medical

## Changelog

:cl:
add: new ai lawset: command control
/:cl:

2022-10-13 20:29 UTC, Fikou commented
how is this different from just using asimov inhand to change target to "member of x group"?

2022-10-13 23:06 UTC, MrStonedOne commented
it can be made a random lawsuit via the config and/or station traits.

2022-10-13 23:31 UTC, etherware-novice commented
lawsuit

2022-10-14 22:58 UTC, MrMelbert requested changes
I think the lawset is unnecessary when we have our asimov boards, but these should be addressed at the very least

2022-10-15 06:56 UTC, etherware-novice commented on code/game/objects/items/AI_modules/full_lawsets.dm
> +	..()
asimov attack_self has the same issue, i just copied from that

2022-10-26 02:15 UTC, etherware-novice commented
@MrMelbert Hello, can you review this pr again?

2022-11-04 00:25 UTC, etherware-novice commented
please rereview

2022-11-04 07:47 UTC, Mothblocks commented
It does not look like any maintainer is interested in this PR and we have too many open PRs

2022-11-04 07:47 UTC, closed without merging