Removes the infinite pocket a-heal from the Wand Belt to shake up the Wizard meta
tgstation/tgstation pull request #70640
Opened 2022-10-18 22:22 UTC by Iamgoofball

## About The Pull Request

Removes the infinite pocket a-heal from the Wand Belt to shake up the Wizard meta

## Why It's Good For The Game

Infinite pocket a-heal is boring and this made the wand belt the most purchased wizard item as per maintainer statements on the matter.

## Changelog
:cl:
del: Removes the infinite pocket a-heal from the Wand Belt to shake up the Wizard meta
/:cl:

2022-10-18 22:28 UTC, Fikou requested changes
u need to set max amount of wands to 5 from 6 if youre even doing this

2022-10-18 22:52 UTC, msgerbs commented
Please put the actual name of the wand you're removing in the CL, even if you're meming too hard to do it in the PR title...

2022-10-18 23:08 UTC, weesnaw-ops commented
but it’s not infinite

2022-10-18 23:21 UTC, Iamgoofball commented
@weesnaw-ops what is Charge for 500

2022-10-18 23:55 UTC, Shadowflame909 commented
Healing might be boring, but it's a necessary evil for the wizard who is going against 30+ other players. 

This will just up the amount of forced lich wiz's because they don't want to die in 30 seconds to the first bomb-spear/chaplain once announced!

The true way to fix this is to add a more unique heal. Maybe some sort of damage transfer spell/wand?

2022-10-19 00:52 UTC, weesnaw-ops commented
> @weesnaw-ops what is Charge for 500 points

charge has a chance to destroy the wand

2022-10-19 04:37 UTC, ATH1909 commented
> @weesnaw-ops what is Charge for 500 points

charge has an 80% chance per casting to permanently reduce the maximum number of charges that the recharged item can hold by 1

2022-10-19 05:17 UTC, Shadowflame909 commented
I would also like to compare this to a similar antag, being nukies. Nukies are known to commonly grab shielded hardsuit to prevent damage, or a medical borg to recover from damage. You could remove the shielded hardsuit to shake up the meta, but its simply missing the forest for the trees for why they buy that item in the first place. 

Also, I feel like wizards have a lot more self-destructive weaponry which might explain why this item is necessary. For example fireball will ohko the wizard if he uses it in an obstructed situation like a borg just ran in front of them, or he's stunned and left without any options. Rod form can send the wizard through walls and cause them to accidentally space themselves, and vials of slaughter demons/laughter demons have no qualms with killing the wizard who summoned them.

Don't get me started on how common but also very dangerous it is for the wizard to use the wand of polymorph that also comes in the same belt this wand of healing comes with! So even ignoring all of the players the wizard must go through, healing is a necessity and removing that just doesn't make much sense.

2022-10-19 08:27 UTC, Helg2 commented
Didnt add anything in exchange just delete. I wonder if "shake up the meta" is just an excuse for your saltiness. If you want to change something dont do it throught deleting everything, it'll be even more boring.

2022-10-19 12:26 UTC, Fikou commented
> > @weesnaw-ops what is Charge for 500 points
> 
> charge has an 80% chance per casting to permanently reduce the maximum number of charges that the recharged item can hold by 1

minimum 55 uses, theoretically infinite 😃

2022-10-19 12:39 UTC, weesnaw-ops commented
> > > @weesnaw-ops what is Charge for 500 points
> > 
> > 
> > charge has an 80% chance per casting to permanently reduce the maximum number of charges that the recharged item can hold by 1
> 
> minimum 55 aheals, theoretically infinite 😃
> 
> > charge has a chance to destroy the wand
> 
> no it doesnt

0 charges remaining destroys magical items and turns them into ash I believe. At least it does with books.

like I said an apprentice is also infinite aheals (PLUS a guy who can cast forcewall, use charge on anything you want (including an egun for themselves) and go robeless with no consequences!!!) so this is not nearly as bad as you think

wizard is a rare solo antag that’s meant to be strong and a bitch to kill. There are still counters to the wand meta (disarm).

2022-10-19 12:40 UTC, Jackal-boop commented
I don't like this. If you need to remove a largely used item from wizards, make an attempt to replace it or solve the underlying issue
Suggestions:
A wand that upon first use, lowers the wizards maximum health drastically, but each successful hit on someone raises their maximum health eventually above normal
A wand that begins an over time aoe heal around the wizard, now the wizard has a chance of healing the people trying to kill him
A wand that plants a healing pylon, long cooldown
A wand that siphons health from enemies
A wand that shoots soap and heals for every slip
A wand that becomes sentient and can heal the wizard on its own accord, it cannot be stored

2022-10-19 12:55 UTC, JohnFulpWillard commented
![image](https://user-images.githubusercontent.com/53777086/196694864-6378ccb0-c5bf-4041-95b0-791610d0db45.png)


For a serious answer, I don't want to see full removal of this, Wizards are fine to be strong, and the main thing I think of when thinking of Wizards is wands, which they currently they don't that many compared to the rest of the spellbook. 

Also this seems oddly specific:
- Wand itself is 2 points
- Charge is 1 point
- Summon item is 1 point (assuming they dont want the wand stolen)
- Jaunt is 2 (assuming they want to not get stuck and killed)

That leaves 4 points to get actual wizard things, which means the Wizard likely has nothing good to fight with, and is still beatable like this. It would be hard, but that's kinda what happens when a Wizard spends more than half their spellbook on their own life.

You also haven't yet dealt with Fikou's response yet, so I'm gonna close this now. You are free to try to open an alternative way of fixing the issue, instead of full removal.

2022-10-19 12:55 UTC, closed without merging