Moves special hug interactions that rely on bodyparts and special organs into signals
tgstation/tgstation pull request #70793
Opened 2022-10-25 17:20 UTC by tralezab

## About The Pull Request

Made this so @Thunder12345 could see how to add special item interactions with hugs without clogging up the help chain with more if else checks on niche items. And that's what I do now!

## Why It's Good For The Game

The if else chain in help act should only increase when base human things happen, we can now have special interactions for certain heads and tails... could be cool!

## Changelog

:cl:
refactor: Refactored hugging code, make an issue if you notice anything weird but it should be the same!
/:cl:

2022-10-25 17:31 UTC, Kapu1178 approved these changes

2022-10-25 17:37 UTC, tralezab commented on code/modules/surgery/organs/external/tails.dm
> +	SIGNAL_HANDLER
imagine being a signal but NOT having signal handler could not be me

2022-10-25 18:48 UTC, MrMelbert requested changes

2022-10-25 18:49 UTC, Mothblocks commented on code/modules/clothing/head/animalears.dm
> +				null, span_hear("You hear a ripping sound."), DEFAULT_MESSAGE_RANGE, list(helper, helped))
```suggestion
		null, span_hear("You hear a ripping sound."), DEFAULT_MESSAGE_RANGE, list(helper, helped))
```

Only ever indent up one, no tab alignment

2022-10-25 18:49 UTC, Mothblocks commented on code/modules/clothing/head/animalears.dm
> +				null, span_hear("You hear a ripping sound."), DEFAULT_MESSAGE_RANGE, list(helper, helped))
But probably this:

```suggestion
	helper.visible_message(
		span_danger("[helper] pulls on [helped]'s tail... and it rips off!"), \
		null,
		span_hear("You hear a ripping sound."),
		DEFAULT_MESSAGE_RANGE,
		list(helper, helped),
	)
```

2022-10-25 18:49 UTC, Mothblocks commented on code/modules/surgery/bodyparts/head.dm
> +				null, span_hear("You hear a soft patter."), DEFAULT_MESSAGE_RANGE, list(helper, helped))
Same

2022-10-25 18:50 UTC, Mothblocks commented on code/modules/surgery/organs/external/tails.dm
> +				null, span_hear("You hear a soft patter."), DEFAULT_MESSAGE_RANGE, list(helper, helped))
Same

2022-10-25 20:44 UTC, Time-Green approved these changes

2022-10-25 22:51 UTC, Kapu1178 approved these changes

2022-10-26 05:41 UTC, Time-Green approved these changes

2022-10-26 05:42 UTC, Kapu1178 approved these changes

2022-10-26 05:43 UTC, Time-Green approved these changes

2022-10-26 05:45 UTC, Kapu1178 approved these changes

2022-10-26 05:47 UTC, Time-Green approved these changes

2022-10-26 05:48 UTC, Kapu1178 approved these changes

2022-10-26 07:14 UTC, Mothblocks commented
stop

2022-10-26 20:17 UTC, Fikou approved these changes

2022-10-26 22:26 UTC, tralezab commented
ban that guy for at least 5 minutes

2022-11-04 07:50 UTC, Mothblocks commented
As we have an abnormally large number of open PRs, I am closing all ones that have been marked stale. Please reopen the PR when it is ready and you have an interested maintainer

2022-11-04 07:50 UTC, closed without merging