Makes it more clear that supermatter pulls are because of the SM crystal itself and not because of atmos movement around the crystal, as this used to be the case and now isn't.
tgstation/tgstation pull request #70808
Opened 2022-10-26 04:03 UTC by Iamgoofball

## About The Pull Request
Makes it more clear that supermatter pulls are because of the SM crystal itself and not because of atmos movement around the crystal, as this used to be the case and now isn't.

## Why It's Good For The Game

Players were incorrectly assuming that the movement around the supermatter crystal itself was due to airflow being manipulated by the crystal, resulting in players putting up atmospherics tools to mitigate the airflow to stand around the crystal without realizing that it's not actually the airflow that's pulling you towards the crystal, it's the crystal physically moving you towards it.

The movement USED to be due to airflow, but it isn't anymore, but we never actually communicated that change to players in a way they would find out in any way other than code diving.

## Changelog

:cl:
fix: Makes it more clear that supermatter pulls are because of the SM crystal itself and not because of atmos movement around the crystal, as this used to be the case and now isn't.
/:cl:

2022-10-26 04:44 UTC, MrMelbert requested changes
I think this is better as a visible message, though in either usage it'll be spammy, since this message is in a for loop that can potentially toss dozens of atoms at once.

2022-10-26 06:17 UTC, scriptis commented
Not a fan of the balloon alerts either--you'll get _lots_ of things near a crystal or shard at a time, especially if somebody dumps a shard in a crowded area. What if the atoms just did a flip animation, like admin throws/singularity pulls? That'd make it easy to discern it's not atmos.

2022-10-26 07:54 UTC, LemonInTheDark commented
anything you put here will be ironically really high load, because fuckers just cannot resist the pill sm.
I think best case is a visual effect that does animated distortion, scaled to be as large as the sm's pull size

2022-10-27 13:26 UTC, Fikou commented
make it a vfx thats a circle that shrinks towards the middle

2022-10-27 21:32 UTC, Iamgoofball commented
so which one of you is paying the spriter?

2022-11-01 10:06 UTC, LemonInTheDark commented
You don't need to
Make an effect, spawn it on the sm's tile for idk maybe like 0.5 seconds (that or use an image or something, ideally we'd have a way to make this visible through walls. image would do that it'd just be a tad annoying. I think flick_overlay (actually uses images) would work for this?)
Give it an icon state that's a ring that distorts towards the center https://www.byond.com/docs/ref/#/{notes}/filters/displace using a mix of red and green to shift things in
Draw it to the distortion plane, so it'll actually distort the game world.
if you do this in like, a proper editor you can make frames of that ring growing outwards, or getting thinner
then animate its transform/position to grow out to the effect range

maybe add some tendrils or ditthering if you wanna be fancy

2022-11-17 00:27 UTC, closed without merging