Big Paperwork: Adds the Paperwork loan offer, paperwork fraud, and ancient paperwork!
tgstation/tgstation pull request #70863
Opened 2022-10-28 20:01 UTC by Rhials

## About The Pull Request

Adds paperwork -- an indecipherable mess of papers that only a seasoned department head could hope to decipher. If processed and sent to Central Command via the cargo shuttle, the budget gets a bonus.

Paperwork is distributed through a new Shuttle Loan offer. A nearby station needs some paperwork reviewed. Do you have what it takes to handle BIG PAPERWORK?

Processing paperwork is relatively simple. You can inspect it to see which head of staff it "belongs" to, and you can use their stamp to complete it. You get a lot of these, so the bonuses can add up if you get them all in. Just be careful not to return any unprocessed paperwork.

With big paperwork comes big paperwork fraud, and big fines.

![image](https://user-images.githubusercontent.com/28870487/198452450-86712aff-440e-4a66-88ea-69094f401986.png)

You can photocopy your completed paperwork to double-dip with Central Command and squeeze out a little bit more money. The more paperwork fraud you commit, the higher the chance you'll be caught and fined.

On top of that:

![tboi unlock](https://user-images.githubusercontent.com/28870487/198710944-7479078b-0426-4f7f-9360-40d3b0b03c74.png)

Some say that in the long forgotten halls of maintenance, there lies _ancient paperwork_. Documents whose importance has long since passed, but are still important for bookkeeping at Central Command. With a keen eye, you might spot one of these while scouring through maintenance. Make sure it gets forwarded to the right person, cargo will thank you.

## Why It's Good For The Game

More shuttle loans offers means more event variation.

Provides convenient access to the bottom layer of hell (Fraud) for cargo staff. 

Adds some rare maintenance loot that, with a tiny bit of effort, benefits the crew. It's like a side quest for assistants.

## Changelog

:cl:
add: Paperwork! Huge paperwork. Gigantic. You can stamp it and send it to Centcom via cargo for BIG MONEY.
add: New shuttle loan event variant -- You get a bunch of paperwork!
add: Ancient paperwork has appeared in the maintenance tunnels!
/:cl:

2022-10-28 20:07 UTC, private-tristan commented
The Binding of Spessmen

2022-10-28 20:27 UTC, MrMelbert requested changes

2022-10-29 12:16 UTC, GuiltyNeko commented
I love this it's absolutely fantastic, please merg.
Also I noticed that these all have the same first detailed description line, is it possible to do code magic to just write that once and have it apply to all of them to reduce the line count? Or would that be too "point A and point B too far separated from each other and now confusing"?

2022-10-29 15:46 UTC, Jackal-boop commented
Holy shit rhials

2022-10-31 10:01 UTC, bruhman8ghughug commented
i love when stuff in the lore (tax fraud) gets reflected on gameplay

2022-11-15 04:02 UTC, Twaticus requested changes
![chrome_Yr860DJIig](https://user-images.githubusercontent.com/46540570/201823515-1708c028-2d4e-4509-b398-2e36454e9884.png)

2022-11-16 03:12 UTC, Twaticus approved these changes

2022-11-20 22:23 UTC, MrMelbert requested changes
Very small things but looks good to merge after

2022-11-22 07:04 UTC, Mothblocks commented on code/modules/events/shuttle_loan.dm
> +						shuttle_spawns.Add(new_paperwork)
```suggestion
				shuttle_spawns += subtypesof(/obj/item/paperwork) - typesof(/obj/item/paperwork/photocopy) - typesof(/obj/item/paperwork/ancient)
```

2022-11-23 14:16 UTC, GuiltyNeko commented on code/modules/paperwork/paperwork.dm
> +	detailed_desc += span_info(" Your begin scanning over the document. This is a standard Nanotrasen NT-435Z3 form used for requests to Central Command.")
Your Begin

2022-12-03 20:48 UTC, merged

2022-12-03 20:51 UTC, DAKKA-WAAAGH commented
YEAAAAHHH!!