Sets a default list of ruleset enemies / Fixes Latejoin Provocateur being very common(?)
tgstation/tgstation pull request #70870
Opened 2022-10-28 23:15 UTC by MrMelbert

## About The Pull Request

- Adds a default list of enemies to all rulesets. 

![image](https://user-images.githubusercontent.com/51863163/198749102-bb9e9fbc-8aa8-47cf-a804-3188d890d4c7.png)

So, everyone's noticed latejoin revs being very common right? I believe this is the issue.

At a certain point of remaining threat, it becomes impossible to purchase Latejoin Heretic or Traitor

It seems as if this is because these rulesets do not have any enemies set, and 1 enemy is required to roll. 

So, I set all rulesets to have a unified default list of enemies. This list was copied around places, which I reduced to the first definition.

## Why It's Good For The Game

Fixes provocateur rolling every round?

## Changelog

:cl: Melbert
fix: Fixes Latejoin Revolution from triggering very commonly
/:cl:

2022-10-28 23:51 UTC, Mothblocks requested changes
Do we have any idea when this regressed? This has absolutely not always been the case. I can pull the data later maybe

2022-10-28 23:51 UTC, Mothblocks commented
I meant to approve

2022-10-28 23:51 UTC, Mothblocks approved these changes
See

2022-10-29 19:22 UTC, flowercuco commented on code/game/gamemodes/dynamic/dynamic_rulesets.dm
> +	var/list/enemy_roles = list(
Should this include the Warden also?

2022-10-30 05:54 UTC, merged