Fixes the universal scanner's sprites and adds contextual screentips.
tgstation/tgstation pull request #70926
Opened 2022-10-30 17:28 UTC by ArcaneMusic

## About The Pull Request

This PR fixes a minor icon_state name discrepancy when switching to the sales tagger mode (I forgot to add a space to the icon_state, which carried over to the radial).

I then read #70909 which brings up several issues with the item, and after actually testing it, everything works as intended. The issue it appears that it's not clear enough that the functionality is the same as it was previously, so we've added contextual screentips to all 3 modes of the scanner.

![image](https://user-images.githubusercontent.com/41715314/198892524-65845906-736c-4859-87b2-304278b0c7a6.png)

## Why It's Good For The Game

Fixes #70909. Improves player feedback on the three modes of the universal scanner through context.

## Changelog

:cl:
fix: The universal scanner now properly show all three options in the radial with sprites, due to a missing space.
qol: The universal scanner now has contextual screentips within all three of its modes.
/:cl:

2022-10-30 18:56 UTC, ShizCalev commented on code/modules/cargo/universal_scanner.dm
> +	//	return NONE
Can remove this if you're not using it.

2022-10-30 18:56 UTC, ShizCalev commented on code/modules/cargo/universal_scanner.dm
> +	. = ..()
Don't need `. = ..()`

2022-10-31 11:08 UTC, TetrakoHateThis commented
We noticed an issue downstream that the Universal Scanner lacks recipes for printing out on lathes (auto and cargo). No idea if that's also an issue up here or not but figured I'd post about it.

2022-11-04 08:06 UTC, Mothblocks requested changes

2022-11-04 08:06 UTC, Mothblocks commented on code/modules/cargo/universal_scanner.dm
> +		. += span_notice("The current custom price is set to [new_custom_price] cr. <b>Right-Click</b> to change.")
```suggestion
		. += span_notice("The current custom price is set to [new_custom_price] cr. <b>Right-click</b> to change.")
```

2022-11-04 08:06 UTC, Mothblocks commented on code/modules/cargo/universal_scanner.dm
> +		to_chat(user, span_notice("\The [src] will now give things a [new_custom_price] cr tag."))
```suggestion
		to_chat(user, span_notice("[src] will now give things a [new_custom_price] cr tag."))
```

"The" is implicit.

2022-11-04 08:06 UTC, Mothblocks commented on code/modules/cargo/universal_scanner.dm
> +	//	return NONE
```suggestion

```

2022-11-04 08:07 UTC, Mothblocks commented on code/modules/cargo/universal_scanner.dm
> +	. = ..()
```suggestion
```

2022-11-04 09:27 UTC, merged