Builds logic that manages turfs contained inside an area
tgstation/tgstation pull request #70966
Opened 2022-11-01 02:30 UTC by LemonInTheDark

## About The Pull Request

Area contents isn't a real list, instead it involves filtering
everything in world
This is slow, and something we should have better support for.

So instead, lets manage a list of turfs inside our area. This is simple,
since we already move turfs by area contents anyway

This should speed up the uses I've found, and opens us up to using this
pattern more often, which should make dev work easier.

By nature this is a tad fragile, so I've added a unit test to double
check my work

I'm not posting speed changes cause frankly they're gonna be a bit scattered and I'm scared to.
@Mothblocks if you'd like I can look into it. I think it'll pay for itself just off `reg_in_areas_in_z`

## Why It's Good For The Game

Less stupid, more flexible, more speed

2022-11-01 02:32 UTC, san7890 commented on code/controllers/subsystem/mapping.dm
> +	if(space_guarenteed)
```suggestion
/datum/controller/subsystem/mapping/proc/build_area_turfs(z_level, space_guaranteed)
	// If we know this is filled with default tiles, we can use the default area
	// Faster
	if(space_guaranteed)
```

spellcheck

2022-11-01 02:46 UTC, Mothblocks requested changes
i think its fine as long as youre sure the memory isnt going to be a problem

how does it work with, say, user created areas?

2022-11-01 02:46 UTC, Mothblocks commented on code/__DEFINES/turfs.dm
> +#define ALL_TURFS(...) block(locate(1, 1, 1), locate(world.maxx, world.maxy, world.maxz))
Needs doc-comment

2022-11-01 02:46 UTC, Mothblocks commented on code/modules/unit_tests/area_contents.dm
> +/// Quite slow, but needed
If it's slow, then put it in a later priority (probably doesn't need to be its own, just a "slow" priority is fine)

2022-11-01 02:46 UTC, Mothblocks commented on code/modules/unit_tests/area_contents.dm
> +		for(var/turf/thing as anything in lad.contained_turfs)
bro real names

2022-11-01 02:46 UTC, Mothblocks commented on code/controllers/subsystem/mapping.dm
> +	for(var/turf/lad as anything in Z_TURFS(z_level))
real name

you are using "lad" both to mean area in one place and turf to mean other

this is just x but longer

2022-11-01 04:51 UTC, LemonInTheDark commented
> i think its fine as long as youre sure the memory isnt going to be a problem
> 
> how does it work with, say, user created areas?

At 255^2 turfs per z, with a ballpark cost of 8 bytes per list entry I expect 520kb per z level, or about 6 megabtyes for our standard ~11/~13 level count

It works as expected. we just hook into the same bit of code inside `/proc/create_area` that actually moves the turf over, and additionally register it. that's what I've done for this whole pr really

2022-11-01 09:04 UTC, LemonInTheDark commented
Currently adds like 20 seconds to init
Fortunately, I am highly competent, so that number can go down significantly

2022-11-02 08:55 UTC, LemonInTheDark commented
alternates between 0.7 seconds slower and 2 seconds faster then master, depending on the position of the stars and the relationship between mercury and jupiter

I think it's worth it, up to you

2022-11-02 08:59 UTC, Mothblocks commented
I think you at the very least need to figure out why there's such a crazy disparity

2022-11-02 08:59 UTC, Mothblocks commented
Especially since there are more straight forward ways of reducing the cost of `reg_in_areas_in_z()` by investigating its consumers without this

2022-11-02 09:17 UTC, LemonInTheDark commented
The trouble is I KNOW it reduces the cost of many problem children, far more then it itself costs in terms of generation.
But it's very hard for me to profile the gain of the changes, just because of variablility in cost between tests and the scope of the change.
Sometimes master will init in 59 seconds while the changes init in 57.7, sometimes master inits in 58.2 when we init in 58.7 (I think this was the cost of ssassets being weird, something is fucky with the preferences json)

2022-11-02 09:31 UTC, Mothblocks commented
Please try to investigate because that seems like enough noise to make this very hard to truly weigh the costs of

2022-11-02 21:20 UTC, msgerbs commented
Does this have any performance improvement for anything with shuttles? I'm having a busy week so haven't had a chance to look myself.

2022-11-02 22:21 UTC, LemonInTheDark commented
I'm unsure. it touches on a proc in the shuttle chain, but that's on load not move.

2022-11-05 03:04 UTC, LemonInTheDark commented
init time comparison between potato_contents and master, on the same master commit
I'd sample a branch, checkout the other branch, and repeat alternating
the last 4 were done with no other backround programs running, steam, discord, firefox, etc. they're much more consistent
```
master:
57.9
60.8
59.8
59.4
57.9
post focusing:
56.4
56.9
58.6 
56.5
potato_contents:
58.3
56.4
62.1
59.9
60.4
post focusing:
55.5
55.6
55.7
55.5
```
it seems to save about a second of init

2022-11-05 03:13 UTC, merged