Adds falling hazard element, beware of falling tools, wear your hardhat, comically timed piano falling on the clown
tgstation/tgstation pull request #70970
Opened 2022-11-01 07:26 UTC by Paxilmaniac

## About The Pull Request

https://user-images.githubusercontent.com/82386923/199180691-6605c8cc-e8aa-490e-ab65-909d45d12ca0.mp4

Do note that the damage in this video is extremely exaggerated compared to what the normal value is.

## Why It's Good For The Game

All these signs about engineers needing to wear their hardhat, and for what? For the assistant dropping toolboxes onto them from above, that's what! Also allows people to do as god intended by allowing them to drop pianos on people.

## Changelog

:cl:
add: A variety of items, mainly tools, around the station might hurt if they fall on your head, remember to wear your hardhat and to avoid standing under large red X marks on the ground with a piano hanging above them.
/:cl:

2022-11-01 07:30 UTC, san7890 commented
I feel like it should at least force a rest if they get the weight of a piano on their head

2022-11-01 07:30 UTC, Paxilmaniac commented
you have a point

2022-11-01 07:37 UTC, DAKKA-WAAAGH commented
A full toolbox would annihilate anyone if dropped onto their head, regardless of the presence of a hardhat.

Still, spacemen are **BUILT DIFFERENT**. 💪

2022-11-01 07:47 UTC, Wallemations commented
![image](https://user-images.githubusercontent.com/66052067/199184153-285682aa-3a5e-42a9-876f-14dbae6b6de1.png)

Me after getting my head indented by a falling toolbox


You should see if you can somehow implement the flattening function of vending machines for the piano so we can REALLY get the comedy rolling

2022-11-01 07:49 UTC, Paxilmaniac commented
I have news for you, they do.

2022-11-01 07:51 UTC, Wallemations commented
Oh my god I'm blind I was focusing too much on the guy who didn't fall
Amazing

2022-11-01 08:02 UTC, MrMelbert requested changes

2022-11-01 08:04 UTC, Mothblocks requested changes
Melbert beat a lot of me to it

2022-11-01 08:04 UTC, Mothblocks commented on code/datums/elements/falling_hazard.dm
> +	element_flags = ELEMENT_BESPOKE | ELEMENT_DETACH
You don't need ELEMENT_DETACH unless you are cleaning up stuff that isn't automatically cleaned up when the host is destroyed.

https://github.com/tgstation/tgstation/pull/70972

2022-11-01 08:04 UTC, Mothblocks commented on code/datums/elements/falling_hazard.dm
> +	crushes_people = crushes
https://github.com/tgstation/tgstation/blob/master/.github/guides/STYLE.md#when-passing-vars-through-new-or-initializes-arguments-use-srcvar

2022-11-01 11:33 UTC, Serxule commented
i love doing this on eris, cant wait for this to get merged

2022-11-01 15:11 UTC, Likteer commented
Yes! YES! Jesus H. tap-dancing Christ! A multiZ piano interaction!

2022-11-02 03:33 UTC, Farquaar commented
There should be a sound effect for items that fall on hard-hatted people. A good "tink" or "thunk" sound would make me smile

2022-11-02 18:19 UTC, Troxonater commented
Great PR, I can't wait to make falling piano traps to troll security as clown.

2022-11-03 03:27 UTC, optimumtact commented on code/datums/elements/falling_hazard.dm
> +	element_flags = ELEMENT_BESPOKE
why use an element if it's just a component?

2022-11-03 03:31 UTC, optimumtact commented on code/datums/elements/falling_hazard.dm
> +	id_arg_index = 2
unless i'm crazy this means you're indexing by the damage which means every element with the same damage is going to have the same values for everything else based on the last element that gets created

2022-11-03 03:33 UTC, optimumtact commented on code/datums/elements/falling_hazard.dm
> +	id_arg_index = 2
arguable you could make a type index that would sort of make sense if you add this element to a lot of things

2022-11-03 03:38 UTC, optimumtact commented on code/datums/elements/falling_hazard.dm
> +	id_arg_index = 2
nevermind i'm wrong this is actually where it "Starts" hashing for uniqeness

2022-11-03 03:39 UTC, optimumtact commented on code/datums/elements/falling_hazard.dm
> +	element_flags = ELEMENT_BESPOKE
They said this is because the falling protection was an element too which I guess is fineeeeeee

2022-11-17 18:51 UTC, merged