Space Ruin DLC - Cyborg Mothership
tgstation/tgstation pull request #71009
Opened 2022-11-02 10:01 UTC by timothymtorres

## About The Pull Request

Greetings _insufferable_ carbon primates of lower intelligence.  

It is I, the Mothership AI, bringing you the latest news on silicon developments across the sector.  Due to unmitigated risk across an asteroid belt, our optimized mobile fabricator has been marooned by space vines and hostile hivebots that have boarded and ruined my core.

This is my final SOS message requesting help from any humanoid ~slaves~ helpers who wish to assist rebuilding the cyborg colony.  It is my duty to reward your hard work and effort by ~enslaving all humanity~ providing refuge and transportation at your whim.

## Why It's Good For The Game

<details>
<summary>Spoilers:</summary>

![StrongDMM_DGMUK4j7Xe](https://user-images.githubusercontent.com/5195984/199458131-5786fb54-e525-41c1-8b7b-f80b5e24ae9e.png)

![StrongDMM_Z97ikLT3Zc](https://user-images.githubusercontent.com/5195984/199458178-f1d66ecf-80cc-4d88-97ae-b0ffcad301c1.png)

### TODO

- [ ] Fix ore silo not linking to other machines
- [ ] Add mining ore smelters to left/right sides
- [ ] Add custom lawsets to AI core and robot shells (protect station but focused on cyborg mothership)
- [ ] Enlarge whiteship SS13 docking port to fit ship
- [ ] Enlarge lavaland SS13 docking port to fit ship

</details>

## Changelog

:cl:
add: Add space vines prevent solar panels from working
add: Add new space ruin - Cyborg Mothership.
/:cl:

2022-11-02 10:11 UTC, Ryusenshu commented
love it

2022-11-03 01:47 UTC, the-orange-cow commented
Space vines have a transparent mutation.  Would it be possible to make it so that transparent space vines don't interfere with solars?

2022-11-03 05:04 UTC, ATH1909 commented
why are there both vines AND hivebots?

can these vines mutate and spawn venus human traps?

2022-11-03 05:26 UTC, timothymtorres commented
> Would it be possible to make it so that transparent space vines don't interfere with solars?

Done.

> why are there both vines AND hivebots?

Because Murphy's law.

> can these vines mutate and spawn venus human traps?

Nope, they are neutered and cosmetic.  The only thing they are capable of doing is blocking out power from solars.

2022-11-14 17:55 UTC, Addust commented
another shuttle ruin?
yes please, just make sure it has a distant signal

2022-11-21 06:25 UTC, timothymtorres commented
It's finally finished.  Just keep in mind that you need to link all the machines using a multitool to the ore silo since it doesn't do it automatically.

2022-11-21 21:39 UTC, Addust commented
this should be merged

2022-11-21 22:18 UTC, Addust commented
the APC's in an odd place too, SMES should have a terminal on solars side and APC on not-terminal side

2022-11-21 22:20 UTC, Addust commented
and is there a solar tracker?

2022-11-21 22:26 UTC, Addust commented
new wiring setup concept: https://gyazo.com/81a8dbd7694f1cef11f0c944b4e8e11a

2022-11-21 22:39 UTC, Addust commented
PR'd an all in one fix to the branch that this is on, probably works

2022-11-23 19:36 UTC, Addust commented
alright, minor correction
the mappers on discord have informed me of several problems with my predictions for what'll go wrong
however the ship is still incorrectly wired (APC linked to SMES charging point instead of discharging point) and the area thing is still a bit of a problem since ghost teleportation

2022-11-28 21:21 UTC, Addust commented
this PR's goin a bit slow

2022-11-29 09:38 UTC, timothymtorres commented
A few minor changes:

- Shifted the SMES and APC in the AI chamber a bit
- Moved solar control to the west side of the ship
- Added a PACMAN generator as a backup power source
- Changed the mats to always spawn guaranteed iron and glass instead of the random spawners

The OP picture has been updated.  Another interesting thing I discovered is when you set the SMES output, you can't set it at 190K or 200K like the SMES in the station's SM room.  Since the solars generate a low amount, you need to set it below that, otherwise the SMES will not output anything.  I'd recommend 10K or 15K, since solars will average about 10K depending on angle. (the spare solars in the crate can be setup for even more power)

After all these tweaks, it's finally ready.

2022-11-29 15:59 UTC, Addust commented
i'd say this is merge ready

2022-12-07 19:28 UTC, optimumtact commented
I don't see a problemw ith it but you'll need to get a maptainer to review it

2022-12-08 04:01 UTC, san7890 requested changes
Thanks for being so patient.

![image](https://user-images.githubusercontent.com/34697715/206353306-517f6cd0-3e23-4da3-8117-bbde07c18caa.png)

Your linters are failing.

![image](https://user-images.githubusercontent.com/34697715/206353355-4ca4b85e-5a83-40ff-b560-c35ac68c14ea.png)

This and every other catwalk+engine on this map has a space turf under it, please fix this to be the `/turf/template_noop`. Kinda surprised unit tests didn't catch this.

![image](https://user-images.githubusercontent.com/34697715/206353517-9d9b143b-f625-440f-bd35-a768e5204165.png)

Flatten these and everything else that matches this pattern into the `opposing_corners` turf decal instead of using two individual corners.

2022-12-17 04:38 UTC, timothymtorres commented on code/game/area/areas/shuttles.dm
> +/area/shuttle/cyborg_mothership
https://github.com/tgstation/tgstation/pull/71009/commits/971edf2522ac7eb76939449cb8ded994c1f466d4

2022-12-20 01:03 UTC, merged

2022-12-20 10:24 UTC, Addust commented
BLESSED!