Make Del the World tests process the filter queue
tgstation/tgstation pull request #71095
Opened 2022-11-05 12:43 UTC by out-of-phaze

## About The Pull Request
Makes Del the World ensure that all objects have left the filter queue before checking the check queue, and update start_time to be more accurate.

## Why It's Good For The Game
The filter queue was added two months after DtW and kind of throws a wrench in the whole thing. Usually the filter queue is pretty fast, but sometimes it can get bogged down with large numbers of items and can theoretically take a variable amount of time, meaning some items might not be in the check queue at all by the time we're running through it, leading to a premature end to the test.

More problematic, the first `start_time` value is checked against the check queue, but set while items are still in the filter queue! Every time something graduates to a new queue, its `qdeld_at` time is reset to the current `world.time`. This means we might get a lot of false negatives because things have a later time than we expect. If we ensure that the filter queue is done when we set (or re-set) `start_time`, then we know that we have a reasonable upper-bound on the `qdeld_at` time for all the items we care about.

2022-11-05 23:15 UTC, LemonInTheDark commented
@MrStonedOne Assertion:
why set qdeleted more then once, on queue insert?

2022-11-06 04:57 UTC, MrStonedOne commented
`qdeleting()` during destroy so things can block delet**ed** things but allow delet**ing** things while ensuring that any runtime or stackoverflow in the process can't leave the object in a state where it has destroy()ed but is not marked as having done so.

2022-11-06 05:00 UTC, MrStonedOne commented
Stack overflows the biggest threat infrastructure code has to contend with. if you call widely overridden procs that you know are likely to all call widely overridden procs you have to assume this will happen, and defensively code against it by setting state then doing the thing the state is indicating instead the reverse.

Just like how certain logs (topic/tgui) write the log before doing the thing the log is about so if a crash happens we have a wider chance to know who or what caused it.

2022-11-06 22:59 UTC, LemonInTheDark commented
> `qdeleting()` during destroy so things can block delet**ed** things but allow delet**ing** things while ensuring that any runtime or stackoverflow in the process can't leave the object in a state where it has destroy()ed but is not marked as having done so.

I mean
set qdeleted pre insert
set qdeleted on insert
set qdeleted once the first queue has finished with it, and passed it into the second

2022-11-10 22:24 UTC, out-of-phaze commented
So where are we on this? I don't want it to get marked as stale.

2022-11-10 23:05 UTC, Mothblocks commented
We're in a code freeze right now unfortunately.

2022-11-11 01:31 UTC, LemonInTheDark commented
I'm not entirely happy with this solution, waiting for mso to get back to me

2022-11-11 20:09 UTC, MrStonedOne commented
In sort, we need to track on the datum 2 things:

a sentry value to be checked with the list to detect `\ref` reuse.

the fact the datum is qdeleted.e

and on the list we need to track 3 things:

the \ref
the time it was queued.
the sentry value.

doing it this way lets it use 1 variable on the datum and 2 list indexes. instead of 2 vars on the datum and 3 list indexes.

but you could avoid setting anything on the datum at all during queue events if you used 3 list indexes. i just don't think its worth it.

2022-11-11 22:57 UTC, LemonInTheDark commented
> oh!
> 
> its because `\ref` ids get reused. you need some sort of sentry value on both the list and the item so you know when it's the same object and that you aren't looking at the new owner of the refid when you locate() it.
> 
> using qdelete and the queue time to cover both keeps us from having to have too many root /datum vars.
> 
> the only other option is to make a new sentry value, set a new var for it, and also add it as a 3rd item in the list of lists since the sentry value has to be both on the datum and "next to" the `\ref`.
> 
> The memory and cpu costs will outweigh any benefits.

ah that is annoying, ok this'll do then (can't wait for pulling refcount to be too expensive to use for some reason)

2022-11-11 23:00 UTC, LemonInTheDark requested changes

2022-11-11 23:00 UTC, LemonInTheDark commented on code/modules/unit_tests/create_and_destroy.dm
> +	var/filter_queue_finished = FALSE
why is this a var?

2022-11-11 23:00 UTC, LemonInTheDark commented on code/modules/unit_tests/create_and_destroy.dm
> +			break
like couldn't this just be while length()

2022-11-11 23:00 UTC, LemonInTheDark commented on code/modules/unit_tests/create_and_destroy.dm
> +			break
and this just be break

2022-11-11 23:00 UTC, LemonInTheDark commented on code/modules/unit_tests/create_and_destroy.dm
>  	var/time_needed = SSgarbage.collection_timeout[GC_QUEUE_CHECK]
pull out time needed later, it messes the flow here

2022-11-11 23:00 UTC, LemonInTheDark commented on code/modules/unit_tests/create_and_destroy.dm
> +		if(world.time > start_time + GC_FILTER_QUEUE + 2 MINUTES) // This is much faster than the check queue.
would prefer to use the variable from ssgarbage rather then the define, since it covers more cases

2022-11-11 23:08 UTC, MrStonedOne commented
wait, hold on, whats the goal here? because i think there might be a smarter way to handle this.

like, if you manually edit `Master.current_ticklimit` to `99999999` and `SSgarbage.collection_timeout[Filter]` to `0`, you can just manually call `handleQueue` on garbage to have it filter thru everything without pausing.

if you do that again with the main queue you will have a final queue that has all the things that failed to gc, waiting for a hard delete.

if you make this a proc on SSgarbage, you can even make sure it gets updated when the queues change.

if you call this in SSgarbage shutdown, you can even have it more correctly find failed to gc things still in the queue during round end.

2022-11-12 00:26 UTC, out-of-phaze commented
> wait, hold on, whats the goal here? because i think there might be a smarter way to handle this.
> 
> like, if you manually edit `Master.current_ticklimit` to `99999999` and `SSgarbage.collection_timeout[Filter]` to `0`, you can just manually call `handleQueue` on garbage to have it filter thru everything without pausing.
> 
> if you do that again with the main queue you will have a final queue that has all the things that failed to gc, waiting for a hard delete.
> 
> if you make this a proc on SSgarbage, you can even make sure it gets updated when the queues change.
> 
> if you call this in SSgarbage shutdown, you can even have it more correctly find failed to gc things still in the queue during round end on normal rounds.

That sounds like it'd be another potential solution, yeah, and could also be generalised if the queue count changes in the future. Might make a PR with that if no one else gets around to it.

The only potential issue is that this change came from a port of Del the World to a Bay codebase, where they raised the concern that this test meddled pretty heavily with SSgarbage's internals. Still, if you make it a proc on SSgarbage, that'd be less of an issue, so I think it's okay.

2022-11-12 00:26 UTC, closed without merging

2022-11-12 00:57 UTC, LemonInTheDark commented
> wait, hold on, whats the goal here? because i think there might be a smarter way to handle this.
> 
> like, if you manually edit `Master.current_ticklimit` to `99999999` and `SSgarbage.collection_timeout[Filter]` to `0`, you can just manually call `handleQueue` on garbage to have it filter thru everything without pausing.
> 
> if you do that again with the main queue you will have a final queue that has all the things that failed to gc, waiting for a hard delete.
> 
> if you make this a proc on SSgarbage, you can even make sure it gets updated when the queues change.
> 
> if you call this in SSgarbage shutdown, you can even have it more correctly find failed to gc things still in the queue during round end on normal rounds.

This fails to account for leniency towards byond refs that take time to clear, and our own timed refs that we only manage if enough time has passed.

2022-11-12 00:58 UTC, LemonInTheDark commented
Also I want harddels to happen so I can sic the reftracker on them

2022-11-12 03:06 UTC, MrStonedOne commented
you can do all of that, i just think this test tries to reinvent the wheel of what ss garbage does when its internals work in such a way that it can just tweak the behavior of the subsystem into submission.

like, the end result of my method is that the final queue would hold everything that failed to qdel when manually speedran. you can then do whatever filtering you want on that then/and/or sick the reftracker on them

2023-06-05 16:51 UTC, out-of-phaze commented
Reopening for CI, to see if it replicates some occasional CI failures due to harddels downstream. Specifically, harddels due to upstream code that don't appear upstream.