Adds chromosome effects to Cryokinesis, Shocktouch, Chameleon, and Webbing mutations.
tgstation/tgstation pull request #71118
Opened 2022-11-05 22:51 UTC by moocowswag

## About The Pull Request
Cryokinesis base cooldown up by 1 second (from 15 to 16) now accepts energetic chromosomes (8 seconds when applied)

Shock touch instability up to by 5 (from 30 to 35) now accepts both energetic and power chromosomes 

Shock touch does a weak 5000 power (I`ve seen it hit from 2-6 damage) tesla shock with range of 7 when used on a viable target (extra damage does not apply to target, no you cant use it on yourself, no you cant use it on someone that is shock immune, yes you have to put yourself in harms way to apply the tesla shock.)

(The vars for the tesla shock can be edited by admins for events/abuse)

Chameleon now accepts power chromosomes to fully stealth about 3 seconds faster.

## Why It's Good For The Game
1. Genetics needs to do something after they find mutations and chromosome farming can greatly expand the time that geneticists spend doing genetics.

2. Only 1 beneficial mutation uses power and energetic chromosomes and that is firebreath, (and arguably void magnet but nobody else uses that no matter how hard I try to get people to try it)

3. We have a whole chromosome system that most mutations cant even use and several mutations are unused because they are simply too weak or irrelevant for anyone to give a damn about them.

This pr kills 3 birds with one stone, geneticists will have more to do, the chromosome system will see more use, and the underused mutations will see more use rather than being bloat.

## Changelog

:cl:
add: Cryokinesis, Shocktouch, Chameleon, and Webbing mutations now have a higher potential
balance: Cryokinesis and Shock touch appear to be weaker and unstable by default
/:cl:

2022-11-07 07:32 UTC, Shadowflame909 commented
genetics mains eating with more job content.

love when genetics gets more love

2022-11-07 20:49 UTC, MrMelbert requested changes

2022-11-07 22:14 UTC, moocowswag commented
Testing changes, also upping tesla shock power from 5,000 to 7,500 and testing that because it was consistently hitting for 3 damage when its intended to more consistently hit for around 6 and people kept saying it was too weak.

2022-11-07 22:24 UTC, moocowswag commented
Shock touch continues to update properly with addition and removal of power chromosome.

2022-11-07 22:39 UTC, moocowswag commented
Webbing properly updates, shocktouch still does too.

2022-11-07 22:44 UTC, moocowswag commented on code/datums/mutations/touch.dm
> +	var/zap_flags = ZAP_MOB_DAMAGE
Auto-doc as in?

2022-11-08 07:50 UTC, Sealed101 commented on code/datums/mutations/touch.dm
> +	var/zap_flags = ZAP_MOB_DAMAGE
`///text goes here`
this is an autodoc

2022-11-17 02:04 UTC, moocowswag commented
pass checks plz <3

2022-11-17 04:20 UTC, moocowswag commented
tested after rebase, it all still seems to work.

2022-11-17 04:25 UTC, merged