Surgery code improvements
tgstation/tgstation pull request #71182
Opened 2022-11-09 05:48 UTC by JohnFulpWillard

## About The Pull Request

* Changes a lot of things about surgeries to hopefully bring it up to more modern code standards.
* Removes a ton of single-letter vars used in checking surgeries on people.
* Makes use of continue/break in for() loops.
* Properly documents the vars on surgeries
* Turns 'ignore clothes', 'self operating', 'lying required', 'require limb' and 'require real limb' from vars into surgery flags
* Removes a lot re-defines of target_mobtype being set to human, as that's the base anyways.
* Also tries to organize the vars on each surgery a bit.
* Makes the surgery initiator hopefully a little bit more sane
* Removes the surgery's can_cancel and stomach pump's accumulated_experience vars, as they were entirely unused.

## Why It's Good For The Game

I looked at surgery code and couldn't stand it, this is hopefully helping bring it to something we can stand.
This however doesn't touch the individual surgery steps.

## Changelog

im exhausted i don't know if this has in-game effects

2022-11-09 05:50 UTC, JohnFulpWillard commented on code/datums/components/surgery_initiator.dm
> -	if (surgery.requires_bodypart == isnull(affecting_limb))
if(TRUE == TRUE)

2022-11-12 17:18 UTC, ExcessiveUseOfCobblestone commented
I'm making a soyface rn

2022-11-16 07:46 UTC, Mothblocks requested changes

2022-11-16 07:46 UTC, Mothblocks commented on code/modules/surgery/surgery.dm
> +	///Selection: SURGERY_IGNORE_CLOTHES | SURGERY_SELF_OPERABLE | SURGERY_REQUIRE_RESTING | SURGERY_REQUIRE_LIMB | SURGERY_REQUIRES_REAL_LIMB
Comment what the file that has these is so you can read the documentation there as well

2022-11-16 07:46 UTC, Mothblocks commented on code/modules/mob/living/carbon/alien/special/alien_embryo.dm
> +			AttemptGrow(0)
Named parameter + probably FALSE?

2022-11-16 07:46 UTC, Mothblocks commented on code/modules/surgery/healing.dm
> +			span_notice("[user] attempts to patch some of [target]'s [woundtype]."))
Needs to be one higher.

Multi-line procs should be written like:

```dm
proc_on_one_line(
    arg1,
    arg2,
    arg3_with_trailing_comma,
)
```

2022-11-21 07:22 UTC, merged

2022-11-22 06:22 UTC, RikuTheKiller commented
Uh oh surgery broke