Excercise Equipment is now craftable
tgstation/tgstation pull request #71190
Opened 2022-11-09 16:56 UTC by flowercuco

## About The Pull Request

Imagine if you will a humble chaplain who wants nothing more than for all of the spiritual folk on the station to get as massive gains as they can, after finding that they can not just make more exercise equipment and that the station does not have any in public places, they go annoy security enough to get into permabrig only to find out that they cant even unwrench the equipment and move it to the church!!! 

NOT ANYMORE!!!

![jS2aBMBa0B](https://user-images.githubusercontent.com/116288367/200889423-f1b6365c-24c4-4f45-8ca4-c96c9085cf27.png)
crafting recipies

![dreamseeker_O4BgBRsFa8](https://user-images.githubusercontent.com/116288367/200889002-8dd7c927-0745-46a9-a4bc-578c7279042a.gif)
demonstrating unwrenching and wrenching equipment

![dreamseeker_hCFQJZdzoS](https://user-images.githubusercontent.com/116288367/200889019-5f4c8399-d539-4d84-8a3f-7735c3ba1f68.gif)
crafting a punching bag and punching it

Now you can craft as much exercise equipment as you want! May everyone on the station get as strong as possible and not just prisoners. 

Also I changed the message that plays when you try to use exercise equipment someone else is using into a balloon alert.
![dreamseeker_PwNesmcR1f](https://user-images.githubusercontent.com/116288367/200890964-4f9fa3ee-ce07-4e6e-815c-a3f4593d06b1.png)

## Why It's Good For The Game

Access to exercise equipment on some maps is limited to static positions and is currently mostly only for prisoners as every map does not have public exercise equipment. Expanding the access means that you can have a Drill Sargent Head of Security or Captain who commands people use these or allows a psychologist to prescribe healthy exercise habits to their patients. 

I think having the potential for exercise equipment on every map is more fun and also if prisoners get their hands on tools they should be allowed to mess with these to annoy security or aid in their escape.

## Changelog
:cl:
add: the punching bag, bench press, and chest press are all able to be crafted and unanchored.
add: crafting recipes for the above
qol: changed a chat message into a balloon alert
/:cl:

2022-11-09 17:48 UTC, Farquaar commented
Can't wait to set up a clown-gym in the bar!

2022-11-09 17:54 UTC, Jackal-boop commented
> Can't wait to set up a clown-gym in the bar!
Bonus points If you bug the bartender for energy drinks

2022-11-09 18:12 UTC, Wallemations commented
Unsecuring a punching bag and it remaining on the roof is a cursed visual

2022-11-09 22:05 UTC, Mothblocks requested changes
You should also add contextual screentips for tools. Let me know if you need help on that

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("unsecuring"))
```suggestion
		balloon_alert(user, "unsecured")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("securing"))
```suggestion
		balloon_alert(user, "secured")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +	balloon_alert(user, ("deconstructing"))
```suggestion
	balloon_alert(user, "deconstructing...")
```

... = pending action

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("unsecure first"))
```suggestion
		balloon_alert(user, "unsecure first!")
```

! == failed

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("Wait your turn!"))
```suggestion
		balloon_alert(user, "wait your turn!")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("unsecuring"))
```suggestion
		balloon_alert(user, "unsecured")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("securing"))
```suggestion
		balloon_alert(user, "secured")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, ("unsecure first"))
```suggestion
		balloon_alert(user, "unsecure first!")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +	balloon_alert(user, ("deconstructing"))
```suggestion
	balloon_alert(user, "deconstructing...")
```

2022-11-09 22:05 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +/obj/structure/punching_bag/wrench_act(mob/living/user, obj/item/tool)
All of these should support `_act_secondary` as well--we want to formalize *de*construction being on right-click, not left-click.

2022-11-09 23:10 UTC, Mothblocks commented on code/game/objects/structures/gym.dm
> +		balloon_alert(user, "unsecure")
unsecured--past tense, same with tha others

2022-11-10 00:07 UTC, flowercuco commented
thank you for the help! i've added the screentips for barehand and right mouse with the proper tools and changed the wrench stuff and crowbar stuff to right clicking. let me know if i messed up here haha

2022-11-10 00:55 UTC, Mothblocks approved these changes
Cute pfp btw

2022-11-10 01:54 UTC, flowercuco commented
thank you very much!

2022-11-15 05:39 UTC, WEWLAD2222 commented
Hey buddy, I think you got the wrong gym. Cargonia's Crossfit Corner is three doors down.

2022-11-16 06:02 UTC, merged