Throws a bunch of parenthesis around to ensure dear Aunt Sally is always properly excused.
tgstation/tgstation pull request #71281
Opened 2022-11-15 18:53 UTC by ShizCalev

Similar vein to #37116

This is supposed to be standard, yet here we are.

SHOULDN'T change anything, but there's likely something out there that's bound to behave different because of it. 

These were done manually, regex to find things that MIGHT need to be corrected;
`^#define.+\+((?!\)).)*$`
`^#define.+-((?!\)).)*$
`^#define.+\*((?!\)).)*$`
`^#define.+\/((?!\)).)*$` (yeah that's a lot of stuff.)
`^#define.+%((?!\)).)*$`

2022-11-15 21:17 UTC, JohnFulpWillard commented
It was recently added to our standards I think

2022-11-15 23:57 UTC, LemonInTheDark requested changes
seems odd to apply this to seconds defines

2022-11-15 23:57 UTC, LemonInTheDark commented on code/__DEFINES/blob_defines.dm
> +#define OVERMIND_STARTING_AUTO_PLACE_TIME (6 MINUTES) // After this time, randomly place the core somewhere viable
this seems silly

2022-11-15 23:57 UTC, LemonInTheDark commented on code/__DEFINES/qdel.dm
> +#define GC_DEL_QUEUE (10 SECONDS)
this too

2022-11-18 19:35 UTC, ShizCalev commented
Do you want me to remove all of these that presently exist in the code then?
![image](https://user-images.githubusercontent.com/6209658/202787295-433d4318-cc35-4b81-bc3d-a1e4473cde3a.png)
![image](https://user-images.githubusercontent.com/6209658/202787310-12efa08e-609b-47e0-bc04-2a3681345094.png)

Seems weirder to cherry pick that one define when ultimately it's still performing math.

2022-11-18 21:41 UTC, LemonInTheDark commented
There aren't many operators with higher priority then *, and it seemed strange to apply the pattern to seconds instances knowing that.
I guess there's **, so it could save some suffering

2022-11-18 23:54 UTC, JohnFulpWillard commented
https://github.com/tgstation/tgstation/blob/master/.github/guides/STYLE.md#put-macro-segments-inside-parentheses-where-possible

2022-11-22 04:52 UTC, Mothblocks commented
i think its worth being consistent for seconds

2022-11-22 04:53 UTC, merged