Adds unique pda ringtones for jobs
tgstation/tgstation pull request #71317
Opened 2022-11-17 07:36 UTC by etherware-novice

## About The Pull Request
Bringing back a feature of legacy pdas that was criminally underutilized!

Every job that spawns with a pda besides assistants now have a unique ringtone. Also, refactored update_ringtone to make it more consistent to set a ringtone on a pda

## Why It's Good For The Game
Fun mixup, and it would be nice to see more than just \*\*beep** since nobody sets their ringtone

## Changelog

:cl:
add: Job-specific ringtones
refactor: update_ringtone was modifed to accept strings, moving the old functionality to update_ringtone_pref
/:cl:

2022-11-17 07:52 UTC, MrMelbert reviewed
I like giving more jobs a unique PDA tone (i was a "boom" ringtone enjoyer) - But ALL jobs is excessive IMO. Imagine chameleon disguising as a job and getting outed because your PDA is the default "beep"

2022-11-17 07:54 UTC, etherware-novice commented
> I like giving more jobs a unique PDA tone (i was a "boom" ringtone enjoyer) - But ALL jobs is excessive IMO. Imagine chameleon disguising as a job and getting outed because your PDA isn't the default "beep".

maybe chameleoning also sets the ringtone? again its not like anyone ever uses a custom ringtone so

2022-11-17 07:58 UTC, Mothblocks commented
i agree that all jobs is excessive, you should fix the regression but not add more

2022-11-17 07:58 UTC, etherware-novice commented
maybe it could be like a 50% chance to set the tone?

2022-11-17 07:58 UTC, Mothblocks commented
thats not what i said

2022-11-17 07:59 UTC, Sealed101 commented
this sets the job-specific ringtones before being overridden by pref's custom ringtone if there is one set, yeah? i don't want to set my ringtone to [B]azinga every shift

2022-11-17 08:04 UTC, etherware-novice commented
> this sets the job-specific ringtones before being overridden by pref's custom ringtone if there is one set, yeah? i don't want to set my ringtone to [B]azinga every shift

the job ringtone is overriden by your custom ringtone yes

2022-11-17 08:05 UTC, etherware-novice commented
also nice ringtone

2022-11-17 08:36 UTC, Mothblocks requested changes
only bring back ringtones, dont add more

2022-11-17 11:11 UTC, Jolly-66 commented
Department based would be cooler.
Captain can go suck it while HoP gets "bark".

2022-11-17 14:32 UTC, etherware-novice commented
> only bring back ringtones, dont add more

i dont know what the legacy ringtones are

2022-11-17 16:04 UTC, Sealed101 commented
> > only bring back ringtones, dont add more
> 
> i dont know what the legacy ringtones are

https://github.com/tgstation/tgstation/blob/36958aab6d4d98a04b10177bfbe9d5cb77e264d2/code/game/objects/items/devices/PDA/PDA_types.dm

look for ttone

2022-11-17 16:33 UTC, etherware-novice commented
```ttone = assist``` thats not a sound either wat

2022-11-17 16:54 UTC, Mothblocks commented
that one sucks but its also for pais so im not sure how often people even heard it

2022-11-17 16:58 UTC, etherware-novice commented
can i keep some of the custom ringtones tho?

2022-11-17 17:30 UTC, Mothblocks commented
not urs

2022-11-18 01:51 UTC, optimumtact commented
You have 7 open pr's of which six are features and several are going stable.

don't open more until you've cleared your backlog by either getting them merged or closing them

2022-11-19 07:14 UTC, Mothblocks requested changes

2022-11-19 07:14 UTC, Mothblocks commented on code/__DEFINES/modular_computer.dm
> +#define MESSENGER_RINGTONE_SHITCURITY "justice"
Remove all these defines because you don't use them

2022-11-19 07:14 UTC, Mothblocks commented on code/modules/jobs/job_types/atmospheric_technician.dm
> +
Why

2022-11-19 07:14 UTC, Mothblocks commented on code/modules/jobs/job_types/janitor.dm
> +	job_tone = "slip"  // scrub scrub scrub
```suggestion
	job_tone = "slip"
```

2022-11-19 07:14 UTC, Mothblocks commented on code/modules/jobs/job_types/scientist.dm
> +	job_tone = "boom"  // toxins is gone again
```suggestion
	job_tone = "boom"
```

2022-11-19 07:14 UTC, Mothblocks commented on code/modules/jobs/job_types/scientist.dm
> +	job_tone = "boom"  // toxins is gone again
We shouldn't clutter the code with these

2022-11-19 07:14 UTC, Mothblocks commented on code/modules/modular_computers/computers/item/tablet.dm
> +		return
This should be an error

```suggestion
		CRASH("Expected a text for ringtone, received [new_ringtone]")
```

2022-11-21 07:01 UTC, Mothblocks commented on code/modules/modular_computers/computers/item/tablet.dm
> +		CRASH("Expected a text for ringtone, received [new_ringtone]")
Ugh, this SHOULD be an error, but looks like everything does it right now. Either fix that or change this back to a return.

2022-11-21 07:58 UTC, merged

2022-11-21 07:59 UTC, etherware-novice commented
here comes the \*boom\*