Carp Migration: Immersive Fish AI Expansion
tgstation/tgstation pull request #71421
Opened 2022-11-21 23:46 UTC by Jacquerel

## About The Pull Request

We have this project to "replace simple mobs with basic mobs" and reading the AI documents sounded kind of cool so I thought I would try my hand at it.
Everyone else with this idea seems to have picked some kind of small and unassuming maintenance critter with no behaviour, I decided to do Space Carp. 
When I started this I thought "space carp essentially just move towards you and attack you" which makes them a great candidate for getting some additional behaviour, which is true but it turned out there's a few other things they do as well.

Where possible I have attempted to make things I added here into reusable components, AI controllers, or behaviours. 
Some things were too specific, or got tangled in object inheritance in a way that I couldn't puzzle my way out of. 
Obviously as these are meant to be reusable they better be good, so don't hold back on telling me how they aren't.

Here's a list I compiled of things carp used to do:

- Move towards targets and bite them
- Bite structures which are between them and their target
- Ignore people wearing carp costumes
- Become tame if fed raw meat and (not terribly responsively) follow instructions given in speech or by alt clicking on them
- Smash walls incredibly quickly (but only when controlled by players, because their AI would not target walls)
- Hunt down six pack rings and try to eat them, hurting themselves in the process
- Mega Carp (the large sharks) regenerate health after not taking damage for six seconds which was news to me because they didn't print any visible feedback that they were doing this.
- Magicarp would be assigned a spell and cast it towards humans, regardless of what the spell does.

They now still do all of that... and more

"Magicarp" from the wizard event will now try to intelligently target their spells if they have ones which aren't for use on people.
Door Carp will turn nearby walls into doors, Animating Carp will animate objects rather than trying to animate humans, and Reviving Carp will automatically fire their bolts at dead or dying mobs who share their faction. Chaos magicarp just shoot at people because not even they know what they are about to do.
As wizard events almost never happen you're more likely to see these from gold slime cores I guess. If you tame them with meat, you can order them specifically to use their spells on pointed targets.

"Regenerating after six seconds" is now a general carp trait and has its own component. You can tell that it is happening because the carp will gain a glowing outline. When carp are injured they will attempt to retreat to take advantage of this, although a determined crewmember can often kill a _regular_ carp before they have the chance to do this because they have very little health.

All carp also have a new ability "Lesser Carp Rift". This lets them teleport up to six tiles on a minute cooldown, and leaves a rift at their original location which other carp will automatically path towards in order to follow them. 
Carp are space-travelling creatures and already have the ability to arrive from great distances away through rifts during the Space Dragon event

The reason I gave them this is because I also updated the Carp Migration event, and made it so that the carp will now actually try to migrate through the station (or more specifically... to a random indoor point on their z level, and then from there to the edge of space opposite where they spawned).
I think they _used_ to do this until it was disabled for causing too many breaches. Giving the carp the ability to traverse through walls without breaking things means they can return to appearing in your workspace _without_ removing all of the air.
Presently the event just spawns some carp around the outside of the station who generally speaking won't do anything for the rest of the round. Ghosts are alerted that a big shark has spawned, but the shark will often not encounter anyone at all unless some nuke ops or space explorers (or rarest of all, someone setting up solar panels) chance to come that way. 

Carp will use this ability if:
- They're trying to migrate and find an obstacle in their way.
- They can see a target but can't reach it.
- They are under 50% health and it's not on cooldown (to try and get away).
They will prioritise entering a rift made by a different carp over making a new one.

There isn't any way to induce a carp to do this other than punching it or luring it with your body, but as anyone can enter a rift while it's there, clever or risk-taking players might be able to take advantage of it to break into areas they're not supposed to be.

Other things this pull request adds:

- Cayenne's ability to be a nuclear operative is now a component you can theoretically put onto any other mob in order to give it the ability to carry and deposit the disk. Maybe you can recruit Ian?
- An element for smashing walls, rather than being a var such as it is on simple mobs.
- "Retaliate" AI behaviour, attached to Lia. This AI doesn't target seek but will take revenge on anyone who has wrong it, at least until it loses sight of them. This may temporarily make Lia the most robust pet on the station. This was a widely used subtype of `hostile` so I assume it will see more use.
- Lia will also attempt to return to her "home" if displaced, this is to avoid her teleporting away from an aggressor and then getting permanently lost in space, but might be useful for other things.
- An attempt at making the "tamed mob commands" system into a series of modular components. Let me know what you think about this, I think that it's a nice way to mix and match what you can order pets to do and might lead to that system being applied to more mobs, but also it might be a bit much in terms of swelling component count on one atom.
- Probably a bunch of other shit I forgot about, this turned out to be a much deeper rabbit hole than I ever expected when I started.

I am sorry for dropping so much code at once, it simply turned out that Basic Mobs were missing more pieces than I thought and this was how much I had to write in order to represent the original behaviour... well that plus my additions. I couldn't think of a reasonable place to atomise, but if this is too much I can try and split "new" behaviour out into a different PR.
Please tell me how it sucks so I can fix it.

I'll attach videos on request if you want to see something, at this moment in time I am too carp brained to know what would be of interest.

## Why It's Good For The Game

Carp are an iconic space animal but also quite boring, which this hopefully remedies.
Puts some bite back into a fairly unimpactful random event.
Might give an underused traitor item a little more love (although probably not, it's still not amazing), and the same for chaplains or curators who choose a gimmick of going around and taming carp.
Hopefully a lot of these components can be reused to convert other mobs more easily, if I didn't write them badly.
Might give space dragon ghost-controlled carp some slightly more interesting behavioural decisions in how they can make hit-and-run attacks.

## Changelog

:cl:
refactor: Space Carp are now "basic mobs" instead of "simple mobs" and use a new system for AI built from reusable components.
add: Space Carp seem to have begun associating the station with food and attempting to enter from the outside, rather than simply congregating around solar panels. Employees are advised that these are wild animals, and should not be fed.
add: All space carp will now regenerate after not taking damage for six seconds, rather than just space sharks, plus you can see when they're doing it.
add: Space Carp can intermittently teleport short distances, leaving a short lived rift which other nearby carp will be attracted to follow them through.
balance: Space Carp will try and take advantage of their new capabilities by teleporting towards targets they can't reach, or away from targets who are  [...]

2022-11-22 00:05 UTC, Mothblocks requested changes

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/components/regenerator.dm
> +	/// If this is active we can't regenerate health
What is "this"? This should be more obvious it's taking a timer id (though I don't know why you're doing that in the first place?)

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/components/tameable.dm
> +			living_parent.faction += "[REF(tamer)]"
```suggestion
			living_parent.faction += REF(tamer)
```

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/elements/ai_retaliate.dm
> +	UnregisterSignal(source, list(COMSIG_PARENT_ATTACKBY, COMSIG_ATOM_ATTACK_HAND, COMSIG_ATOM_ATTACK_PAW, COMSIG_ATOM_ATTACK_BASIC_MOB, COMSIG_ATOM_ATTACK_ANIMAL, COMSIG_MOB_ATTACK_ALIEN, COMSIG_ATOM_B
You should have all these signals on their own line, this line is too long.

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/elements/ai_retaliate.dm
> +	if((attacker.combat_mode || LAZYACCESS(modifiers, RIGHT_CLICK)))
```suggestion
	if(attacker.combat_mode || LAZYACCESS(modifiers, RIGHT_CLICK))
```

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/elements/basic_eating.dm
> +	var/heal_amt
`heal_amount`--avoid abbreviations

2022-11-22 00:05 UTC, Mothblocks commented on code/datums/elements/wall_smasher.dm
> +	. = COMPONENT_HOSTILE_NO_ATTACK
Everywhere after this you should `return .` so that it's obvious we are returning a value, or `return COMPONENT_HOSTILE_NO_ATTACK` explicitly.

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	set_greyscale(colors= list(pick_weight(carp_colors)))
```suggestion
	set_greyscale(colors = list(pick_weight(carp_colors)))
```

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	spin(20, 1)
Named parameters

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +		"#aba2ff" = 7,
These should all be sourced from colors.dm

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +		ai_controller.blackboard[BB_MOB_HOME_AREA] = get_area(src)
Indented up way too high

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp_abilities.dm
> +		COMSIG_ATOM_ENTERED = .proc/on_entered)
```suggestion
		COMSIG_ATOM_ENTERED = .proc/on_entered,
	)
```

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp_abilities.dm
> +	do_teleport(entered_atom, destination, channel = TELEPORT_CHANNEL_MAGIC,)
```suggestion
	do_teleport(entered_atom, destination, channel = TELEPORT_CHANNEL_MAGIC)
```

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp_abilities.dm
> +	playsound(get_turf(firer), projectile_sound, 100, TRUE)
```suggestion
	playsound(get_turf(firer), projectile_sound, 100, vary = TRUE)
```

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp_ai_rift_actions.dm
> +	if (QDELETED(target))
Just check null instead

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/carp_ai_rift_actions.dm
> +	if(QDELETED(target))
Just check null, here and everywhere else

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/magicarp.dm
> +	)
Only indent up once

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/magicarp.dm
> +#define XENOBIOLOGY_MAGICARP_SPELL_LIST list(\
These should be global lists that are set on initialize, not defines that are set in typedef

2022-11-22 00:05 UTC, Mothblocks commented on code/modules/mob/living/basic/space_fauna/carp/magicarp.dm
> +		/obj/projectile/magic/animate = "#fd6767",
These should be colors.dm

2022-11-22 00:06 UTC, Mothblocks commented
This should ideally be split into several different refactor PRs by the way, this is huge and hard to review

2022-11-22 00:11 UTC, Jacquerel commented
> This should ideally be split into several different refactor PRs by the way, this is huge and hard to review

Absolutely sympathise with this, but not sure how to split it up without leaving two copies of the mob in the code for a while, which I didn't want to do.
I can try and at least branch it into "stuff which is exactly the same as old stuff" and "stuff which they did not previously do" tomorrow.

2022-11-22 00:18 UTC, Mothblocks commented
That's fair, is it possible for instance to have the pet command stuff be in its own PR that works with simple carp? None of this is required but it's stuff you maybe want to keep in mind for the future

2022-11-22 00:22 UTC, Mothblocks commented on code/modules/mob/living/basic/farm_animals/cow/_cow.dm
> +	AddElement(/datum/element/basic_eating/heal, food_types, 10)
All these DCS subtypes are sus btw

2022-11-22 00:25 UTC, Mothblocks commented on code/datums/components/pet_commands/pet_command.dm
> +/// How close your pet must be to you or to a pointed target in order to acknowdlege a command
```suggestion
/// How close your pet must be to you or to a pointed target in order to acknowledge a command
```

2022-11-22 00:26 UTC, Mothblocks commented
You don't have to do this if you don't want to but here's some stuff that could be split into different PRs:

- Mega carp GAGS
- New basic AI behaviors (I'm starting to be more sympathetic towards PRs that add code that we don't use right away as long as it's from someone we trust to use it later on)
- Regenerator component
- Nuclear bomb operator component probably would've worked with simples?)
- Pet commands component (especially since this needs some work done on it to de-subtype it)
- The /mob/living/basic/revive thing
- The actual simple -> basic transition

2022-11-22 00:33 UTC, Jacquerel commented
> You don't have to do this if you don't want to but here's some stuff that could be split into different PRs:
> 
>     * Mega carp GAGS
> 
>     * New basic AI behaviors (I'm starting to be more sympathetic towards PRs that add code that we don't use right away as long as it's from someone we trust to use it later on)
> 
>     * Regenerator component
> 
>     * Nuclear bomb operator component probably would've worked with simples?)
> 
>     * Pet commands component (especially since this needs some work done on it to de-subtype it)
> 
>     * The /mob/living/basic/revive thing
> 
>     * The actual simple -> basic transition

Thanks, I will implement the reviews above and then see about doing that.

2022-11-22 00:54 UTC, private-tristan commented
> Smash walls incredibly quickly (but only when controlled by players, because their AI would not target walls)

wouldn't this just lead to sentient space carp breaking every single wall on station, especially on the exterior of the station?

2022-11-22 01:12 UTC, Pumpkinoe commented
> wouldn't this just lead to sentient space carp breaking every single wall on station, especially on the exterior of the station?

it says this is something carps USED to do, not 'adds'
in fact it incentivizes this not happening by giving carps the ability to teleport

2022-11-22 10:45 UTC, Jacquerel commented on code/datums/components/pet_commands/pet_commands_menu.dm
> +	SEND_SIGNAL(parent, COMSIG_REQUESTING_PET_COMMAND_RADIAL, radial_options)
You are right, but I couldn't think of any other way to achieve it without getting components by type directly which seems worse. 
The idea here is something like how you can extract tooltip context from components, except I want to be able to build a radial menu which has as many segments as you have commands. I will see if I can think of something better before this gets its own PR, after datumising commands more.

2022-11-22 13:04 UTC, Jacquerel commented
Alright time to start atomising.

2022-11-22 13:04 UTC, closed without merging

2023-01-29 09:36 UTC, Acer202 commented
Well, I was trying to see which PR made carp so horrifically daunting to deal with on longer shifts, and this must be the starting point! It might be unintended based on what I'm reading here, but carp cause lots of breaching and firelock hellscapes on Campbell shifts. The rifting ability has ended with some comically tragic deaths and rendered the station uninhabitable many times recently. Any tips on what might make a good passive counter to these? They run amok in the station, breaking everything to get to every floorbot/medibot/SSD person/monkey and it's a nightmare! Stupid fishe...

2023-01-29 11:37 UTC, Mothblocks commented
...you think the pr that wasn't merged is the starting point?

2023-01-29 19:01 UTC, Acer202 commented
> ...you think the pr that wasn't merged is the starting point?

Well, seeing as they closed this one and opened a series of PRs later to modularize it to achieve the same behavioral changes that this was aiming to...
Yes? Is that unreasonable?