Adds finger snapping
tgstation/tgstation pull request #71450
Opened 2022-11-22 19:33 UTC by Hardly3D

## About The Pull Request
This PR adds the finger snapping emote, ported from Beestation (and NSV), https://github.com/BeeStation/BeeStation-Hornet/pull/1208 and https://github.com/BeeStation/NSV13/pull/338

https://user-images.githubusercontent.com/66234359/203344246-6f42a23f-93bd-4dfc-9c1c-e1324dadd5d4.mp4

## Why It's Good For The Game
Many uses for it, such as snapping at assistants and getting someone's attention.
Also RP

## Changelog
Allows you to snap your fingers

:cl: Cenrus, ported by Hardly
add: Added *snap emote
/:cl:

2022-11-22 19:34 UTC, Imaginos16 commented
INSANELY BASED

2022-11-22 19:39 UTC, xPokee commented
Based

2022-11-23 00:17 UTC, Oranggu commented
I honestly cant think of a reason this should not be added lol

2022-11-23 00:26 UTC, JohnFulpWillard commented
> I honestly cant think of a reason this should not be added lol

lack of gbp sorry

2022-11-23 01:08 UTC, Oranggu commented
> lack of gbp sorry

Shits fucked

2022-11-23 01:21 UTC, Wallemations commented
The sound effect should have you snap twice in a row so you can do advanced Intruder RP

2022-11-23 04:52 UTC, datorangebottle commented
Snapping repeatedly should get the attention of nearby pets. Except cats, who should sometimes run away from you if you snap repeatedly because cats are fickle like that.

2022-11-24 01:36 UTC, Mothblocks requested changes
Move it to carbon and check if you have hands.

2022-11-24 15:37 UTC, Hardly3D commented
Should be good for review now.

2022-11-24 19:28 UTC, Mothblocks commented on code/modules/mob/living/carbon/emote.dm
> +		return pick('sound/misc/fingersnap1.ogg', 'sound/misc/fingersnap2.ogg')
```suggestion
		return pick('sound/misc/fingersnap1.ogg', 'sound/misc/fingersnap2.ogg')
	return null
```

2022-11-24 19:50 UTC, merged