Fermentation and barrel refactoring
tgstation/tgstation pull request #71475
Opened 2022-11-23 15:28 UTC by MTandi

## About The Pull Request

The barrel was essentially a grinder that also added a lot of wine on top of other reagents. Now it converts only nutriment and vitamin into the wine.

Also the Auto-Distilling Composition plant gene didn't make wine and gave only half of the drink volume.

Now the fermentation is consistent and it happens in one place - the `ferment()` proc of the plant. Both the gene and the barrel use it.

Also added some sounds and ballon alerts.

Also increased the barrel volume to 600, as other stationary reagent containers have even more.

https://user-images.githubusercontent.com/3625094/203582992-8d31cff6-15bd-416f-b2fb-c7a0f6cfbcb4.mp4

## Why It's Good For The Game

Barrels are cute, we should use them more.

## Changelog

:cl:
qol: barrel works with the plant bag now
balance: barrel volume increased to 600 units
fix: barrel now properly converts nutriments into wine
refactor: barrel logic and fermentation refactoring
/:cl:

2022-11-23 17:39 UTC, Oranggu commented
Not a very big change but a nice cute one. Looks cool hope this gets merged 🙏

2022-11-25 19:32 UTC, Mothblocks requested changes

2022-11-25 19:32 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		to_chat(user, span_warning("The barrel can't hold any more fruits!"))
balloonies

2022-11-28 05:35 UTC, Mothblocks approved these changes

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +				balloon_alert(user, "Added [inserted_fruits] fruit\s")
```suggestion
				balloon_alert(user, "added [inserted_fruits] fruit\s")
```

Balloonies are all lowercase

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +			balloon_alert(user, "Added fruit")
```suggestion
			balloon_alert(user, "added fruit")
```

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "Closed the lid")
I actually don't think you need either of these balloon alerts (or to_chats) since the icon change is obvious

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "Opened the lid")
Same here

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "The barrel is full!")
```suggestion
		balloon_alert(user, "it's full!")
```

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "Can't ferment this!")
```suggestion
		balloon_alert(user, "can't ferment this!")
```

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "Can't take from the bag!")
```suggestion
		balloon_alert(user, "can't take from bag!")
```

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +		balloon_alert(user, "Can't take the fruit!")
```suggestion
		balloon_alert(user, "can't take fruit!")
```

2022-11-28 05:35 UTC, Mothblocks commented on code/modules/hydroponics/fermenting_barrel.dm
> +	if(!locate(/obj/item/food) in contents)
```suggestion
	if(!(locate(/obj/item/food) in contents))
```

`in` precedence is scary, I'm not even sure your old code worked

2022-11-28 05:36 UTC, Mothblocks requested changes
meant reject but whatever

2022-11-28 08:48 UTC, MTandi commented
> meant reject but whatever

Eh? Why? It's just bugfixes and qol tweaks.

2022-12-01 19:23 UTC, Overuseddart commented
I love barrels

2022-12-02 03:38 UTC, merged