This kills the deep fried foods holder. Refactors deep frying to just make the thing edible but still functional.
tgstation/tgstation pull request #71551
Opened 2022-11-26 19:13 UTC by MrMelbert

## About The Pull Request

Refactors deepfrying, removing the gross Deep Fried Foods Holder Object and replacing it with the edible component. 

Now, deep frying a food will simply make the item edible directly. This means it's still functional and doesn't become a dead item. 

This follows the same method that grilling uses when applying its effects. Tweaks grilling a bit so they line up better. Also, silver foods can make grilled items. 

![image](https://user-images.githubusercontent.com/51863163/204105022-ee66889b-f843-4dc2-b0dc-5f1eb5ba19c3.png)

I swear this is unrelated to the other 2 fried foods related PRs. I started this a few weeks ago.

## Why It's Good For The Game

Tangibly better code (doesn't have to copy a million vars! Less abusable!) at the price of removing a soulful piece of code. Also means that deep frying an item doesn't irreversibly make it unusable / dead. This is sad, but... damn the holder object sucks. 

Unfortunate side effect is that anything that overrides `attack` to not send signal will *not* be edible when deepfried. Maybe this encourages better signal use? 

Either that or fried foods can override `pre_attack` to hook directly into eating. I can do that as well. 

## Changelog

:cl: Melbert
refactor: Refactored deep fried foods. Deep fried foods are still ""usable"" as their normal item, but are just edible.
qol: Silver Slime stuff can spawn grilled as well as fried. 
/:cl:

2022-11-26 19:55 UTC, ATH1909 commented
wow, I was just about to ask why we hadn't done this yet

<img width="1439" alt="deep fried disabler" src="https://user-images.githubusercontent.com/42606352/204106800-969e690c-b715-4c00-a941-5702ab22ddaf.PNG">

:salute:

2022-11-26 21:38 UTC, Jacquerel commented
This may be the end to deep fried Ian, alas.

2022-11-27 03:17 UTC, Mothblocks requested changes

2022-11-27 03:17 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +		rgb(166, 103, 54),
These should be color defines, it's impossible for me to know what these are on web without looking them up

2022-11-27 03:17 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +		foodtypes = FRIED)
```suggestion
	this_food.AddComponent( \
		/datum/component/edible, \
		bite_consumption = 2, \
		food_flags = FOOD_FINGER_FOOD, \
		junkiness = 10, \
		foodtypes = FRIED,
	)
```

2022-11-27 03:17 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +	ADD_TRAIT(this_food, TRAIT_FOOD_FRIED, "kfc")
Make "kfc" a define or just use `REF(src)` instead

2022-11-27 03:17 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +	// We will not bother making it un-edible again, it will get too messy
👀❓ I don't think it's that bad to just qdel the edible component even if you don't yet verify where it's from

2022-11-27 03:17 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +	// We will not bother making it un-edible again, it will get too messy
You can also save a list of weakrefs of edible components added by the element and check if the `GetComponent` result is one of those before qdel'ing. That will require adding `ELEMENT_DETACH_ON_HOST_DESTROY` though.

2022-11-27 07:05 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +	// We will not bother making it un-edible again, it will get too messy
Right

2022-11-27 07:06 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +		"#996666",
Color defines, aka the ones in colors.dm

2022-11-27 07:06 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +		"#996666",
We probably have some of these already or at least close to them

2022-11-27 09:06 UTC, TemporalOroboros commented
A few notes:
1. Most of the things on the oilfry blacklist are there because of the frying rendering them unusable, such as containers. If that's being changed it can probably be trimmed a bit.
2. This will kill the primary method of creating recursive food. If you want to preserve that you're going to want to take a look at custom reagent holders.
3.

2022-11-27 10:32 UTC, Mothblocks commented on code/datums/elements/food/fried_item.dm
> +		"#996666",
You should add the brown defines then

2022-11-27 12:21 UTC, Colovorat commented
An end of an Era

2022-11-27 20:18 UTC, moocowswag commented
is this a balance pr or was using deep frying to disable people`s items an exploit.

2022-11-28 04:05 UTC, Mothblocks commented on code/__DEFINES/dcs/signals/signals_food.dm
> -#define COMSIG_ITEM_FRIED "item_fried"
Can you keep the signal, even if you have no consumers? It is the best way to implement #71550.

2022-11-30 15:17 UTC, private-tristan commented
Thank you melbert now a clown with cooking oil and 3 seconds in the armory no longer destroys every single gun 👍

2022-12-01 00:23 UTC, merged

2022-12-01 04:21 UTC, ATH1909 commented
> It unironically is a big gameplay change for jani borgs since their main asimov tool is filling their drying agent sprayer with frying oil and spraying weapons after slipping people mid lethal combat to prevent human harm.

you have a trash bag, my dude

2022-12-01 19:20 UTC, Overuseddart commented
> is this a balance pr or was using deep frying to disable people`s items an unintended exploit.
> 
> It unironically is a big gameplay change for jani borgs since their main asimov tool is filling their drying agent sprayer with frying oil and spraying weapons after slipping people mid lethal combat to prevent human harm.
> 
> Maybe a way to wash fried items to restore them could also be on the table cause the permanent change to sprite + permanently edible is kind of oof? Maybe like with soap or something so you can make even normally edible food inedible and dont have to worry about checking for if the item was originally a non edible or not.

You could always just run away with it while they are trying to get up

2023-02-22 11:36 UTC, Mothblocks commented
did you figure it out yesterday too

2023-02-22 11:36 UTC, Mothblocks commented
i think the feature removal is unfortunate but i also dont really mind