Legitimizes BOMBGERs. Add grenades to burgers and assistants will still eat it.
tgstation/tgstation pull request #71552
Opened 2022-11-26 19:21 UTC by tralezab

## About The Pull Request

Here's the changes to custom food:
- Can now accept grenades
- If you add something larger than the custom food, the custom food becomes that size
- Biting down on food with grenades in them triggers the grenades

## Why It's Good For The Game

We're trying so hard to remove getting around this whole bombger thing but wait it's actually based as hell. Why don't we just cut the fat of what doesn't work (getting around sanity checks with deep frying) and legitimize what does?

## Changelog

:cl:
add: You can add grenades to food
add: Grenades explode when accidentally bitten into
balance: Adding something large to custom food will make it, too, also large
/:cl:

2022-11-26 19:27 UTC, flowercuco commented
i posted the initial bug report on the server of the downstream i play on in hopes of someone doing it in a round before we merged whatever fix happened so legitimizing it definitely sounds fun

2022-11-26 19:27 UTC, MrMelbert requested changes

2022-11-26 19:40 UTC, tralezab commented on code/datums/components/food/edible.dm
> +		bombger_ingredient.detonate()
shore

2022-11-26 20:39 UTC, EuclidianGeometer commented
you can make a few custom foods which are sliceable. what happens then?

2022-11-26 20:43 UTC, tralezab commented
> you can make a few custom foods which are sliceable. what happens then?

I'll make them go boom on slice

2022-11-26 21:17 UTC, Wallemations commented
Remind me, do custom burgers tell you what's in them if you examine them?

2022-11-26 21:42 UTC, Serxule commented
> Remind me, do custom burgers tell you what's in them if you examine them?

only in the name afaik but they can be renamed

2022-11-26 21:56 UTC, tralezab commented
> Remind me, do custom burgers tell you what's in them if you examine them?

Name and description, for most things.
![image](https://user-images.githubusercontent.com/40974010/204110391-8e7bd323-8ccb-44eb-b230-6b8799f11878.png)

2022-11-26 23:36 UTC, RikuTheKiller commented
Yes, YES, YESSSS!

2022-11-27 01:15 UTC, Pickle-Coding commented
I think adding fried TTVs should add a unique overlay, to keep it recognizable and not concealed so easily.

2022-11-27 09:51 UTC, RikuTheKiller commented
> I think adding fried TTVs should add a unique overlay, to keep it recognizable and not concealed so easily.

Good idea.

2022-11-27 12:13 UTC, Shadowflame909 commented
as long as it is made with love i will eat it

clown lube bomb soup soon

2022-11-28 20:37 UTC, Overuseddart commented
The Captain after eating my burger with 5 badmin payloads and a c4:

2022-11-29 10:10 UTC, datorangebottle commented
> > I think adding fried TTVs should add a unique overlay, to keep it recognizable and not concealed so easily.
> 
> Seconded, a full TTV should at least have some sort of tell compared to a grenade. I think visibly showing a TTV between two buns is the ultimate comedy moment.

Honestly, if someone handed me an extremely obvious TTV burger, I would stand next to them while eating it.

2022-11-30 08:28 UTC, Time-Green requested changes

2022-11-30 08:28 UTC, Time-Green commented on code/game/objects/items/grenades/_grenade.dm
> +/obj/item/grenade/proc/ingredient_detonation(datum/source, mob/living/target, mob/living/user, bitecount, bitesize)
Can you doc these?

2022-11-30 08:28 UTC, Time-Green commented on code/game/objects/items/grenades/_grenade.dm
> +/obj/item/grenade/proc/on_used_as_ingredient(datum/source, atom/used_in)
And doc this one?

2022-11-30 08:28 UTC, Time-Green commented on code/datums/components/customizable_reagent_holder.dm
> +	if(isgrenade(ingredient))
Could you make this look for a trait instead? TRAIT_BURGERABLE_NON_FOOD or something so this doesn’t devolve into a list of istype checks whenever someone else wants to add make non-food object be addable to food

2022-11-30 08:30 UTC, Time-Green commented
Could you also show a picture of how a bombger looks like in-game?

2022-11-30 18:35 UTC, Overuseddart commented
Can we stack as many bombs as we can ingredients? I want to stack 99 syndibombs and 1 c4 to see what happens

2022-12-01 19:19 UTC, tralezab commented
one frag in the fragburger to the right, 10 frags to the left
![image](https://user-images.githubusercontent.com/40974010/205140778-9e080f0f-6f14-4230-9f05-9241e169eb6e.png)

2022-12-01 19:53 UTC, Time-Green commented
> Can you still fire bombgers into someone’s mouth with a pneumatic cannon, causing them to eat it?

new meta

2022-12-01 20:03 UTC, merged