Adds ear surgery for fixing ears/deafness.
tgstation/tgstation pull request #71644
Opened 2022-12-01 10:27 UTC by Higgin

## About The Pull Request

Adds ear surgery for fixing ears/damage-induced deafness.

## Why It's Good For The Game

Losing access to your senses means losing access to a lot of useful information for engaging with the game, and restoring people towards a certain baseline of function (or something approaching it) is sort of the 'game' for medical. Except, if you have a corpse that's been dead for ten minutes, or a clown that's been clusterbanged to non-functional hearing, you're in trouble if you don't have inacusiate or an upgraded chem fridge. Why?

Having a nonchemical way to fix hearing consistent with the nonchemical way of fixing eyesight, eye surgery, offers a slower but guaranteed and reliable way of addressing deafness alongside blindness. 

Having people more able to access information for engaging with the game (with other people contributing to that through surgery even when they don't necessarily have chems/tech) is good. 

## Changelog

:cl:
add: Surgeons can now conduct ear surgery, targeted at the head, to fix ear damage and resulting deafness.
/:cl:

2022-12-01 11:27 UTC, distributivgesetz commented on code/modules/surgery/ear_surgery.dm
> +	user.visible_message(span_notice("[user] successfully fixes [target]'s ears!"), span_notice("You succeed in fixing [target]'s ears."))
double `visible_message` call here and in `display_results`?

2022-12-01 20:03 UTC, Time-Green requested changes
Looks good! Super minor nitpicks this is ready
Also what @distributivgesetz said

2022-12-01 20:29 UTC, Redrover1760 commented
Good pr

2022-12-01 23:57 UTC, closed without merging

2022-12-02 01:24 UTC, optimumtact commented
rough morning huh