Goliath dna infusion
tgstation/tgstation pull request #71657
Opened 2022-12-02 05:27 UTC by GuillaumePrata

## About The Pull Request
Firstly, this is unfinished (I need to fix the eye and organ colors as an example.) but I can only work on it properly again on Sunday so I will open as draft so any code issue could be bought up so I can fix it in time.
And I might change the organs' effect around based on feedback.

Now, this PR adds goliaths to the DNA infuser at genetics. It gives 4 organs and a final bonus effect.

1- Goliath eyes: Simple mostly filler organ that gives night vision.
2- Goliath lungs: Allow miners to breath either lavaland or the default air mix. As a side effect, but can't breath pure O2 anymore so internals can't be used. Stay away from N2O or use your gas mask properly.
3- Goliath heart: Give miner ash storm protection
4- Goliath brain: Turns one of the miner's arm into a tendril goliath hammer that can be used to mine. Like the mounted chainsaw it cannot be dropped, deals 20 damage by default and a bonus 80 to lavaland fauna, it also acts as a baseball bat against fauna so you can dodge being hit back with good timing.
As a side effect, you can't equip gloves as your hand is a big ass hammer...

Also also, I'm not happy with the hammer codersprite, I tried to make it be a tentacle at first but I just can't make it work like that so I will try a goliath plate looking hammer hand instead, I need to work more on it but again, Sunday...

The extra effect for having all 4 organs is lava immunity.

## Why It's Good For The Game
This add some useful tools for miners if they opt into asking genetics for help and bother to bring goliath corpses to it.
The organs can be useful on the station, but they will only really shine at lavaland.

We were brainstorming more things that miners can get from the station on their downtime waiting the cargo shuttle bring their bought gear, this would be a simple and easy power up for miners that can have some small (ignoring the hammer arm) bonus to miners, but small power ups pile up.

I can also write a giant ass list of different features I tried/would add to goliath organs but I should write a HackMD for it later as that is just easier to communicate my goals and reasons than a PR.
Something something Sunday... sorry...

## Changelog

:cl: Guillaume Prata
add: Goliath DNA infusion. I will add a more detailed changelog later...
/:cl:

2022-12-02 05:35 UTC, tralezab approved these changes
great addition, full review when done

2022-12-02 05:35 UTC, tralezab commented on code/game/machinery/dna_infuser/organ_sets/goliath_organs.dm
> +	AddElement(/datum/element/noticable_organ, "small tendrils grow on their back.", BODY_ZONE_HEAD)
don't forget to change body zone on this

2022-12-02 05:35 UTC, tralezab commented on code/game/machinery/dna_infuser/infuser_entries.dm
> +	)
might wanna mention the air breathing.

2022-12-02 06:01 UTC, Striders13 commented
kinetic crusher fans are left out, fucked up.

2022-12-02 06:07 UTC, GuillaumePrata commented
> kinetic crusher fans are left out, fucked up.

And MODsuit fans.

2022-12-02 11:14 UTC, Jacquerel commented
There are many beasties on Lavaland, I’m sure a different one could provide a different role if you wanted one which enhanced your equipment.  
This doesn’t seem so much like it’s for PKA OR Crusher users but supplants both, which is good and fun.

2022-12-02 12:58 UTC, Shadowflame909 commented
Mining - genetics departmental cooperation. Two departments both lacking in communication shall now communicate with each other. Amazing PR that I hope gets merged as soon as its done

2022-12-02 16:11 UTC, DaydreamIQ commented
The hammer seems a bit too overtuned considering the 'downside' is just not being able to have gloves. When the Crusher requires two hands and does less damage while requiring you to also shoot the fauna/backstab to get more damage out of it, this seems wildly imbalanced. Plus giving the crew access to free 20 force nodrop armblades with no real downsides is just gonna lead to powergaming out the ass

2022-12-02 16:30 UTC, Overuseddart commented
The fauna damage is a bit high though, it out damages the crusher while making it so you dont have to go for a backstab

2022-12-02 16:33 UTC, Overuseddart commented
Is there any interaction between the Goliath eyes and the eye of god? Could be fun.

2022-12-02 17:49 UTC, GuillaumePrata commented
> The hammer seems a bit too overtuned considering the 'downside' is just not being able to have gloves.

Another downside is that your hand is always stuck being a weapon and you can't use two handed items like the crusher.

The comparison to the crusher is good, the crusher does 20 damage + 50 extra if the target is marked and it can be upgraded further with different perks without needing to interact with any department which makes the upgrades quite consistent overall.

The tendril hand does 20 damage and an extra 80 to mining and bosses with a small knockback, but it takes twice as long to "recharge" an attack so you can do the next one. (I forgot to put the slower atk spd on the PR so that is on me)
It will lose to basically any other weapon on a DPS race and that was the goal, you walk in, slap the monster to show their place and it is out of range to being counterattacked if it is a melee monster.

If punching every fauna becomes an issue balance wise we can always slow the atk speed further to reward using it in a combo with another weapon like the PKA.

2022-12-04 06:35 UTC, GuillaumePrata commented
I tried to fix the linter issue three times but it hates me for some reason so I need some help with it (if it is even important...)

2022-12-04 18:38 UTC, private-tristan commented
seeing how these give you organs, it'll be intresting to see if miners decide to harvest the organs so that they can get the effects they want (through a med doc implanting the organs) instead of getting all of them. quite interesting

2022-12-06 00:14 UTC, Oranggu commented
This is cool

2022-12-07 17:12 UTC, gueba14 commented
any plans on doing any other megafauna?

2022-12-07 19:26 UTC, Overuseddart commented
An interaction between Goliath eyes and Eye of God could be something like, upon applying eye of god effect a square of 4x4 tentacles appears, dealing 80 damage to fauna and stunning humanoids. Could be fun as Goliath eyes would just grant mostly the same effects as the eye.

2022-12-15 05:41 UTC, CCC23 commented
:(

2022-12-15 18:40 UTC, gueba14 commented
this is sad, it was a good concept that was going on with the new stuff

2022-12-18 19:40 UTC, catrock31 commented
man this looks so cool i can't wait for it to be in

2022-12-20 01:11 UTC, catrock31 commented
i am vibrateing just waiting for it

2022-12-21 03:40 UTC, Livrah commented
Genetics is always lacks things to do and interactions, this looks really good.

2022-12-21 16:53 UTC, catrock31 commented
> Genetics is always lacks things to do and interactions, this looks really good.

yeah and the design doc has more that wants to be done after this one so even more interactions

by the way are you the cool mime on youtube?

2022-12-24 20:35 UTC, tralezab requested changes
small things

2022-12-24 20:35 UTC, tralezab commented on code/game/machinery/dna_infuser/organ_sets/goliath_organs.dm
> +	AddElement(/datum/element/noticable_organ, "small tendrils grow on their back.", BODY_ZONE_CHEST)
You're going to want to reword this, it'll come out wrong.

2022-12-24 20:35 UTC, tralezab commented on code/game/machinery/dna_infuser/organ_sets/goliath_organs.dm
> +	bonus_deactivate_text = span_notice("Your DNA is once again mostly yours, and so fades your ability to survive on lava...")
Would prefer a better description for the first part, "Your DNA is once again mostly yours". I set a bad pattern by making them generic, would prefer if they all had a unique DNA loss message for the first half.

2022-12-24 20:35 UTC, tralezab commented on code/game/machinery/dna_infuser/organ_sets/goliath_organs.dm
> +	AddElement(/datum/element/noticable_organ, "small tendrils grow on their back.", BODY_ZONE_CHEST)
"His small tendrils grow on their back"

2022-12-24 20:35 UTC, tralezab commented on code/game/machinery/dna_infuser/organ_sets/goliath_organs.dm
> +	AddElement(/datum/element/noticable_organ, "thick hide plates are growing under the skin", BODY_ZONE_CHEST)
"His thick plates are growing under the skin"

2022-12-28 00:55 UTC, merged

2022-12-28 00:56 UTC, adamkad1 commented
How do I upgrade mah hammerarm tho