Adds card reader to autolathe
tgstation/tgstation pull request #71700
Opened 2022-12-04 08:19 UTC by YakumoChen

## About The Pull Request
title

## Why It's Good For The Game
It got removed from general protolathe designs, and it's a very basic roundstart part for useful machines (service and bounty stuff), I think having it be in autolathe is good as an alternative.

## Changelog

:cl:
qol: card readers can be printed from autolathes
/:cl:

2022-12-04 20:54 UTC, Fikou requested changes
this doesnt work

2022-12-04 20:54 UTC, Fikou commented
> It got removed from general protolathe designs

no it didnt

2022-12-05 00:35 UTC, YakumoChen commented
You can't print card readers from protolathes that don't have the Stock Parts category, which is all of them but sci and engi

They used to be available in every protolathe but that's just not the case now.

2022-12-05 00:40 UTC, YakumoChen commented
![image](https://user-images.githubusercontent.com/10399117/205526157-f92392bc-0c07-4167-b17a-d0d79786691c.png)

2022-12-06 01:46 UTC, Mothblocks commented
this doesnt work? @Fikou

2022-12-10 07:32 UTC, JohnFulpWillard commented
Working or not I think it would be better to just put this back in the techfabs, autolathes are lame in comparison, it's needed for stuff like the chef's vending tray

2022-12-11 20:00 UTC, YakumoChen commented
why not both?
If card reader being absent is a bug, that requires another fix anyway

2022-12-22 20:36 UTC, optimumtact commented
science and engineering can print it, I do not see why this is needed.

2022-12-22 20:36 UTC, closed without merging