Add some logging for cargo pods
tgstation/tgstation pull request #71726
Opened 2022-12-05 02:03 UTC by optimumtact

Does what it says.

2022-12-05 02:07 UTC, Timberpoes commented
I'm not particularly well-versed with this code, but would this be a candidate for having the `/datum/supply_pack` handle the logging? Are there any things you can order from the various consoles that don't come from `/datum/supply_pack`?

If all the various cargo-interacting consoles use are supply_packs, it would centralise all logging and prevent an issue like this reoccurring.

Ignore me if I don't know what I'm talking about.

2022-12-05 02:09 UTC, optimumtact commented
it's possible, I'll look tonight

2022-12-05 02:16 UTC, Timberpoes commented
Genuinely have no clue. I was looking at this code:
![image](https://user-images.githubusercontent.com/24975989/205534398-82a23696-3722-4a14-a098-48f2ff137101.png)
![image](https://user-images.githubusercontent.com/24975989/205534660-20cd7060-2d57-42d3-b4b2-0ca231d8e369.png)

And these comments:
![image](https://user-images.githubusercontent.com/24975989/205534481-22cb9a14-ed8f-464d-96a0-12b792810f08.png)

And figured this datum was basically the source of all the cargo entries and the spawn source of all filled crates.

It seemed like the most central code to handle logging (I.e. - If this is the code that spawns (and later fills) the physical crate, it's probably the best candidate for logging)

2022-12-09 21:04 UTC, ShizCalev requested changes

2022-12-09 21:04 UTC, ShizCalev commented on code/modules/cargo/expressconsole.dm
> +						investigate_log("[key_name(usr)] launched an emagged supply pod at [AREACOORD(LZ)] of type [SO.pack.type]", INVESTIGATE_CARGO)
compile

2022-12-18 02:45 UTC, closed without merging