Roundend report has a meter for showing relative escape numbers
tgstation/tgstation pull request #71728
Opened 2022-12-05 02:28 UTC by etherware-novice

## About The Pull Request
Roundend report has a ascii bar for showing the relative number of people to escape on shuttle, escape on pod, be stranded, or die in the round

![image](https://user-images.githubusercontent.com/73374039/205536255-006be897-cb58-4fb8-ab8e-ceb02385a49e.png)

## Why It's Good For The Game
Fancy graphic, lets you see at a glance how much of a bloodbath the round was or how proactive people were at getting to the shuttle.

## Changelog

:cl:
add: roundend survival meter
/:cl:

2022-12-05 02:32 UTC, optimumtact commented
I don't believe you

2022-12-05 02:36 UTC, Mothblocks requested changes

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +#define ROUNDEND_BAR_SIZE 20
undef at the end

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +		var/barSections = list()
snake_case

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +			popcount[POPCOUNT_ESCAPEES] - popcount[POPCOUNT_SHUTTLE_ESCAPEES])  // non shuttle escapees
```suggestion
			barSections += list(
				popcount[POPCOUNT_ESCAPEES],
				popcount[POPCOUNT_ESCAPEES] - popcount[POPCOUNT_SHUTTLE_ESCAPEES],  // non shuttle escapees
			)
```

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +		var/list/renderedBar = generate_aggregate_bar(ROUNDEND_BAR_SIZE, barSections, totalSize = total_players)
snake_case

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +		<span class=[ROUNDEND_BAR_COLOR[4]]>Dead</span></B>"
indent one

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/text.dm
> +/proc/generate_aggregate_bar(numSquares, list/sectionSize, totalSize=null)
autodoc. snake_case

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/text.dm
> +	var/list/returnList = list()
snake_case

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/text.dm
> +		var/repeatAmount = FLOOR(( section / totalSize ) * numSquares, 1)
```suggestion
		var/repeatAmount = FLOOR((section / totalSize) * numSquares, 1)
```

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/text.dm
> +		returnList += sectionRender
```suggestion
		return_list += repeat_string(repeat_amount, "#")
```

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/text.dm
> +		returnList += sectionRender
repeat_string

2022-12-05 02:36 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +		barSections += (total_players - popcount[POPCOUNT_SURVIVORS])  // dead
no two spaces

2022-12-05 02:37 UTC, etherware-novice commented on code/__HELPERS/text.dm
> +		returnList += sectionRender
wow i wish i knew that existed before

2022-12-05 02:37 UTC, etherware-novice commented on code/__HELPERS/roundend.dm
> +		barSections += (total_players - popcount[POPCOUNT_SURVIVORS])  // dead
for the comments?

2022-12-05 02:40 UTC, Mothblocks commented on code/__HELPERS/roundend.dm
> +		barSections += (total_players - popcount[POPCOUNT_SURVIVORS])  // dead
yes

2022-12-05 02:55 UTC, blackdav123 commented
ascii is SOUL

2022-12-11 03:07 UTC, Mothblocks commented
i keep looking at this and it just looks ugly sorry

2022-12-11 03:07 UTC, closed without merging

2022-12-11 05:01 UTC, etherware-novice commented
you...do know..you can just ask me to redesign it right???

2022-12-11 05:01 UTC, etherware-novice commented
@Mothblocks like what do you think would be a good design

2022-12-11 05:33 UTC, Mothblocks commented
oranges did and you told him no

2022-12-11 09:18 UTC, etherware-novice commented
??? i dont know how tgui works though, i couldve changed the character used to make it look more appealing

2022-12-11 21:09 UTC, Mothblocks commented
but if its just an ascii thing its always going to look ugly thats why i closed it

2022-12-11 21:10 UTC, etherware-novice commented
thats subjective also therws plenty of ascii bars in the game already

2022-12-11 22:25 UTC, Mothblocks commented
There shouldn't be

Yes it's subjective and the job of the maintainer is to make subjective decisions