Rats can attack obstacles between them and their target
tgstation/tgstation pull request #71741
Opened 2022-12-05 13:58 UTC by Jacquerel

## About The Pull Request

Fixes #71568 
I wrote this for basic mob carp but it will be needed in a lot of places.
Rats used to be able to attack windows or dense objects between them and their target, but basic mobs didn't have this capability.
Now they do.

## Why It's Good For The Game

Restores accidentally removed behaviour.
Will likely be required for future basic mob development.

## Changelog

:cl:
fix: Rats will once again attempt to attack windows or other dense objects separating them from their targets.
/:cl:

2022-12-05 17:24 UTC, Jacquerel commented on code/datums/ai/basic_mobs/basic_ai_behaviors/melee_attack_target_and_obstacles.dm
> +/datum/ai_behavior/basic_melee_attack/attack_obstacles
You aren't wrong, I had already been encoutering problems like this just inside carp subtypes.
Your `AI_BEHAVIOR_CAN_PLAN_DURING_EXECUTION` implementation might be the piece I was missing when I first wrote this, I will see if I can think of a sensible way for it to replan itself without losing its target.

2022-12-14 13:48 UTC, ShizCalev requested changes

2022-12-14 13:48 UTC, ShizCalev commented on code/datums/ai/basic_mobs/basic_subtrees/attack_obstacle_in_path.dm
> +	if(!target || QDELETED(target))
```suggestion
	if(QDELETED(target))
```

QDELETED() includes !target

2022-12-18 16:23 UTC, tralezab approved these changes

2022-12-18 16:24 UTC, merged