Shuffles bedsheet attack actions a wee bit
tgstation/tgstation pull request #71865
Opened 2022-12-09 16:04 UTC by flowercuco

## About The Pull Request
my friends been doing makeshift surgery and gets mad about having to do harm intent to start surgery and then having to turn it off to do every single other surgery step and i agree, thats silly

instead, now, the bedsheet attack does not check for harm and ALWAYS COVERS with left mouse button and ALWAYS PREPARES SURGERY with right mouse button

## Why It's Good For The Game

while obviously a lot of the time makeshift surgery IS about harming someone else its inconsistent with how all other surgery tools function and also isn't very clear at all. the screentip in addition to having them be separate buttons means that bedsheets two functions are overall much clearer and its surgery drape function will no longer lead to an assistant accidentally knifing someone when theyre trying to save someones life

## Changelog

:cl:
qol: added makeshift surgery screentip
qol: you no longer have to go in and out of harm intent to do surgery with a bedsheet
/:cl:

2022-12-09 16:06 UTC, dalmationer commented
yippee!

2022-12-10 09:14 UTC, MrMelbert requested changes

2022-12-11 09:58 UTC, JohnFulpWillard commented
I don't think I want surgery to be on right click, it would make it inconsistent with the surgical drapes.

2022-12-11 13:04 UTC, flowercuco commented
> I don't think I want surgery to be on right click, it would make it inconsistent with the surgical drapes.

I agreed with you and melbert and current implementation is tucking ppl in is on right mouse click and all three surgery initiators prepare surgery on left mouse click

2022-12-12 02:22 UTC, MrMelbert requested changes

2022-12-12 03:32 UTC, flowercuco commented on code/datums/components/surgery_initiator.dm
> +	RegisterSignal(parent, COMSIG_ITEM_REQUESTING_CONTEXT_FOR_TARGET, PROC_REF(add_item_context))
ok! i think i set it correctly?

2022-12-20 15:45 UTC, merged