Removes ++ and -- in conditionals
tgstation/tgstation pull request #71925
Opened 2022-12-11 11:21 UTC by Time-Green

I hate this and apparently so does mothblocks

See ##71887

no changelog

(There's also a few in main.dm but I prefer not to touch it since most of that is optimized code)

2022-12-11 11:23 UTC, Time-Green commented
three seconds I based it on the wrong branch

2022-12-11 19:34 UTC, MrMelbert requested changes

2022-12-11 20:00 UTC, Time-Green commented on code/modules/hallucination/battle.dm
> +		shots_left++
Fuck I meant --
Good catch cause this would've been not fun to fix

2022-12-12 10:49 UTC, Autisem commented
*rants about how technicaly  prefixes are more optimized because they have 1-2 less lines of assembly code*

![meme](https://media.tenor.com/TP_eEPV33yUAAAAd/magiclenstv-fast.gif)

2022-12-12 19:02 UTC, jlsnow301 commented
Accessibility over efficiency

2022-12-12 19:02 UTC, merged