you can now flip eyepatches + blindfolds mix eye colors
tgstation/tgstation pull request #71932
Opened 2022-12-11 17:15 UTC by Fikou

## About The Pull Request

you can flip eyepatches using them inhand (or an action button)
blindfolds now blend your eye colors, like the colors says they do

## Why It's Good For The Game

not a great eyepatch if it only works for one eye.

## Changelog

:cl:
add: you can flip eyepatches
fix: blindfolds now take into consideration both eye's colors for their color
/:cl:

2022-12-11 21:28 UTC, Imaginos16 approved these changes
Fucking finally.

2022-12-11 21:28 UTC, CMDR-Gungnir commented
FINALLY

2022-12-12 19:26 UTC, Overuseddart commented
Let me wear two eyepatches PLEASE

2022-12-14 08:27 UTC, Twaticus commented
huge

2022-12-14 13:46 UTC, Watermelon914 requested changes

2022-12-14 13:46 UTC, Watermelon914 commented on code/modules/clothing/glasses/_glasses.dm
> +	icon_state = icon_state == "eyepatch_flipped" ? "eyepatch" : "eyepatch_flipped"
this really shouldn't be hardcoded. Use a variable for the flipped and non-flipped states

2022-12-14 13:46 UTC, Watermelon914 commented on code/modules/clothing/glasses/_glasses.dm
> +	icon_state = icon_state == "eyepatch_flipped" ? "eyepatch" : "eyepatch_flipped"
same thing here

2022-12-14 13:46 UTC, Watermelon914 commented on code/modules/clothing/glasses/hud.dm
> +	icon_state = icon_state == "hudpatch_flipped" ? "hudpatch" : "hudpatch_flipped"
and here

2022-12-14 14:18 UTC, merged