[WIP] Refactors armor into dedicated subtypes
tgstation/tgstation pull request #71986
Opened 2022-12-14 01:41 UTC by ZephyrTFA

## About The Pull Request

See title.

## Why It's Good For The Game

Code is cleaner, and more readable/intuitive
Technically closes https://github.com/tgstation/dev-cycles-initiative/issues/8

## Changelog

:cl:
refactor: armor, from the ground up basically
/:cl:

2022-12-14 04:32 UTC, CRITAWAKETS commented on code/datums/armor/armor_types.dm
> +	bullet = 320
i dont think this is meant to have 320 armor

2022-12-15 12:42 UTC, Fikou requested changes
i dont know if its in your plans already but the armor files are unreadable and need a lot more splitting up (to categories like structures, machines, armor vests, winter coats, boots, modsuits etc)

2022-12-19 07:22 UTC, Mothblocks commented
IMO one thing I was going to ask for was for the armor datums to be defined next to the objects themselves. Lowers surface area.

2022-12-19 07:22 UTC, Mothblocks commented on code/__DEFINES/combat.dm
> +#define ARMOR_LIST_DAMAGE list(BIO, BOMB, BULLET, ENERGY, LASER, MELEE)
List datums should be `(...)` (this and the other two)

2022-12-19 07:23 UTC, Mothblocks commented on code/datums/armor/_atom_armor.dm
> +/atom/proc/GetArmor()
snake_case

2022-12-19 07:23 UTC, Mothblocks commented on code/datums/armor/_atom_armor.dm
> +/atom/proc/GetArmorRating(damage_type)
snake_case

2022-12-19 07:23 UTC, Mothblocks commented on code/datums/armor/_atom_armor.dm
> +/atom/proc/SetArmor(datum/armor/armor)
snake_case

2022-12-19 07:23 UTC, Mothblocks commented on code/datums/armor/_atom_armor.dm
> +/atom/proc/SetArmorRating(damage_type, rating)
snake_case

2022-12-23 09:12 UTC, Mothblocks requested changes
I'm assuming everything else isn't worth reviewing

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +	. = list()
You don't need this, nothing in your proc errors, but if you want to keep it, `return .` at the end

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +GLOBAL_LIST_INIT(armor_by_type, __generate_armor_cache())
If this is used anywhere else, define it

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +/proc/__generate_armor_cache()
Dunders are really ugly, just remove them

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +		var/mult_all = multipliers[ARMOR_ALL]
`multiplier` etc

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +			stack_trace("Attempt to call generate_new_with_modifiers with illegal modifier '[mod]'! ignoring it")
```suggestion
			stack_trace("Attempt to call generate_new_with_modifiers with illegal modifier '[mod]'! Ignoring it")
```

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +		if(!(mod in all_keys)) // Did you know that the false block evaluates faster than the true block?
Invert it, `if(!x) else` can be hard to interpret and the speed buff here is barely even noticeable in space init, much less here

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +/datum/armor/proc/get_rating(rating)
Make sure all these procs are documented

2022-12-23 09:12 UTC, Mothblocks commented on code/datums/armor/_armor.dm
> +/datum/armor/proc/get_rating(rating)
They are overridden so it is useful

2022-12-23 09:14 UTC, Mothblocks commented
I think they're all going to get re-requested when undrafted that's shit

2022-12-23 12:12 UTC, NamelessFairy commented
Just wanted to ask since I spotted this PR, how will this change modifying armor values ingame using VV?

2022-12-23 14:52 UTC, ZephyrTFA commented
> Just wanted to ask since I spotted this PR, how will this change modifying armor values ingame using VV?

moves it to the atom level, other than that it doesn't

2022-12-24 00:20 UTC, Mothblocks commented
@NamelessFairy You already should never have been VV'ing the armor directly, that didn't work to begin with because of how weird the armor system was

2022-12-24 00:21 UTC, merged

2022-12-24 23:22 UTC, NamelessFairy commented
> @NamelessFairy You already should never have been VV'ing the armor directly, that didn't work to begin with because of how weird the armor system was. There's a modify armor dropdown in VV that you should be using instead

Thank, didn't know about the VV dropdown and that would explain a lot

2022-12-25 07:59 UTC, Mothblocks commented
The edit button on armor really should offer to open that first it's a footgun I've seen a lot

2022-12-29 10:31 UTC, timothymtorres commented
This PR appears to have spammed a ton of duplicate armor datums to every single object in the game.  #72348 is one example, but after code diving it does this with every armor... yikes.