Ignore codeowners that got previously removed from review
tgstation/tgstation pull request #72007
Opened 2022-12-14 20:46 UTC by Gamer025

## About The Pull Request
**Only merge this after the following 2 PRs got merged!**
https://github.com/tgstation/RequestReviewFromUser/pull/5
https://github.com/tgstation/RequestReviewFromUser/pull/6

Makes it so that codeowners no longer get notified if they got removed from review previously in the PRs lifetime
Requested by @Mothblocks 

## Why It's Good For The Game
Apparently no means no and the action constantly re-adding you as owner after you remove yourself is annoying

## Changelog

2022-12-15 18:25 UTC, Mothblocks commented
Why is this an opt in configuration? I can't imagine anyone ever wanting this off

2022-12-15 21:02 UTC, Gamer025 commented
> Why is this an opt in configuration? I can't imagine anyone ever wanting this off

Because if I made it a default I would have needed to increase the version number to 2 because it would be a breaking change, which would have also meant needing to make a V2 branch, because of how Github actions works

2022-12-16 03:54 UTC, Mothblocks commented
I think it's a bug fix more than a breaking change tbh

2022-12-21 18:07 UTC, Wayland-Smithy commented
> needing to make a V2 branch

Neat. I didn't know you could do that with branches. I have always gone the tag route or to be extra safe used the exact commit hash.

2022-12-21 19:07 UTC, Gamer025 commented
> > needing to make a V2 branch
> 
> Neat. I didn't know you could do that with branches. I have always gone the tag/release route or to be extra safe used the exact commit hash.

Yeah I got the idea from https://github.com/actions/toolkit/issues/214
While the official docs recommend just moving the V1 tag I really don't like the idea of moving already published tags

2022-12-21 21:46 UTC, Mothblocks commented
I'm gonna close this since we agreed (I think) on coderbus that this should be considered a bug fix and require no config changes

2022-12-21 23:57 UTC, Mothblocks requested changes

2022-12-21 23:57 UTC, Mothblocks commented on .github/workflows/codeowner_reviews.yml
> +          ignoreRemovedUsers: true
gamer025 wants me to test something

2022-12-21 23:59 UTC, closed without merging