Gives admins the ability to enable hostile environments at will.
tgstation/tgstation pull request #72018
Opened 2022-12-15 14:13 UTC by NamelessFairy

## About The Pull Request

Adds a new admin verb that allows admins to create a blob/revolution style hostile environment preventing the shuttle from leaving. Also allows admins to clear all hostile environments, I've had a blob hostile environment exist without a living blob in the past and its rather troublesome to debug live if you don't know what your doing.
## Why It's Good For The Game

Sometimes admins want to stop the crew from leaving but in a more thematic way then centcoms just not sending you an escape shuttle, especially if the shuttle is already called.
## Changelog
:cl:
admin: Admins can now enable a custom hostile environment that prevents the shuttle from leaving.
/:cl:

2022-12-15 14:35 UTC, Fikou commented on code/modules/admin/verbs/adminevents.dm
> +				SSshuttle.registerHostileEnvironment("Admin")
these are datums not strings

2022-12-15 14:36 UTC, Fikou commented on code/modules/admin/verbs/adminevents.dm
> +			return
you dont need this

2022-12-15 15:27 UTC, Serxule commented
im not an admin but this sounds great for gimmicks

2022-12-15 18:07 UTC, Fikou commented on code/controllers/subsystem/shuttle.dm
>  			hostile_environments -= d
if youre touching this change the name please

2022-12-23 03:39 UTC, jlsnow301 requested changes

2022-12-23 03:39 UTC, jlsnow301 commented on code/modules/admin/verbs/adminevents.dm
> +	switch(tgui_alert(usr, "Select an Option", "Hostie Environment Manager", list("Enable", "Disable", "Clear All")))
```suggestion
	switch(tgui_alert(usr, "Select an Option", "Hostile Environment Manager", list("Enable", "Disable", "Clear All")))
```

2022-12-23 16:17 UTC, merged