Master Init but Faster
tgstation/tgstation pull request #72043
Opened 2022-12-16 17:49 UTC by ZephyrTFA

Cuts the delay for the Master Controller from one second to one tick.
References and Closes https://github.com/tgstation/dev-cycles-initiative/issues/30

2022-12-16 17:50 UTC, ZephyrTFA commented
CC @MrStonedOne

2022-12-16 17:53 UTC, Mothblocks requested changes
Two things:

1. Should be a define
2. That define should document why we delay at all, which is to give wiggle room for the massive amounts of reconnects at roundstart

2022-12-16 17:57 UTC, ZephyrTFA commented
done

2022-12-16 18:14 UTC, MrStonedOne requested changes
You should force push away your first commit because i take MASSIVE issue with the fact you called 1ds a `tick` when a tick is configurable and defaults to 0.5ds on ss13 and even old ss13 defaulted it to 0.9ds

2022-12-16 18:23 UTC, MrStonedOne commented on code/__DEFINES/MC.dm
> + */
i know mothblocks told you to do this here, but this comment should be in the codedoc for master/Initialize, not here.

2022-12-16 21:53 UTC, Mothblocks commented
We don't save the commit descriptions anymore anyway so if you change your PR body to call it a decisecond rather than a tick then the squash commit should be good

2022-12-17 19:07 UTC, MrStonedOne commented
> We don't save the commit descriptions anymore anyway so if you change your PR body to call it a decisecond rather than a tick then the squash commit should be good

The current pr is 1 tick (0.5 ds).

the old commit was 1ds (2 ticks).

**Please pay attention and if this pr is merged saying it has 1ds when its 1tick (0.5ds) i will blow a gasket.**

also I'm placing an embargo on @ZephyrTFA working on anything further related to the mc until i am confident they understand the difference between a game tick, a dedisecond, and a subsystem tick.

Knowing the units of time is a prerequisite to working on the MC.

2022-12-17 20:43 UTC, ZephyrTFA commented
> snip

I'm terribly sorry you think I pinged you on this PR so that you could fume and get unreasonably angry over something I literally CC'd you on so any mistakes could be caught.

In the future I will make sure that instead of pinging the appropriate people I will simply assume my code works without fault!

2022-12-17 20:43 UTC, ZephyrTFA commented
Oh, and make the PR yourself.

2022-12-17 20:43 UTC, closed without merging