Makes `flags_inv` better at actually hiding things when used on non-suit clothing
tgstation/tgstation pull request #72107
Opened 2022-12-20 02:44 UTC by MrMelbert

## About The Pull Request

`flags_inv` contains a series of flags which dictate which items can be seen / which items are rendered when it is worn. This lets you hide things that shouldn't be visible, stops weird bugs

Right now it really doesn't work to hot. Most of the flags aren't checked so a lot of silly things happen.

Here's an example, which was broken for 2 reasons

![image](https://user-images.githubusercontent.com/51863163/208569339-6bc07fb2-ccd4-4251-9aef-77f53afd7c5c.png)

1. it was using the wrong var
2. nowhere checked that the shoes were hidden

So, I went through and made the `update_x` procs consistently check when the slot is actually hidden.

![image](https://user-images.githubusercontent.com/51863163/208569388-a6cefe71-9b41-4263-95b7-24fee2d76e63.png)

Much better?

~~It's actually still broken. It's hiding the arms for some reason. But that's for another PR?~~

## Why It's Good For The Game

Flags that exist should work as expected.

## Changelog

:cl: Melbert
fix: Wedding dresses no longer render their shoes over the dress
fix: Things which have inv flags set should more consistently actually hide the things they mean to hide
/:cl:

2022-12-20 10:30 UTC, Mothblocks commented on code/modules/mob/living/carbon/human/human_update_icons.dm
> +		if(check_obscured_slots(TRUE) & ITEM_SLOT_ICLOTHING)
named param for true

2022-12-20 10:30 UTC, Mothblocks commented on code/modules/mob/living/carbon/human/human_update_icons.dm
> +		if(check_obscured_slots(TRUE) & ITEM_SLOT_GLOVES)
same

2022-12-20 10:31 UTC, Mothblocks commented on code/modules/mob/living/carbon/human/human_update_icons.dm
> +		if(check_obscured_slots(TRUE) & ITEM_SLOT_SUITSTORE)
same and everywhere else

2022-12-20 22:34 UTC, Mothblocks approved these changes

2022-12-27 03:24 UTC, Kylerace requested changes

2022-12-27 03:24 UTC, Kylerace commented on code/modules/mob/living/carbon/human/human_update_icons.dm
> +			icon_file = 'icons/mob/clothing/mask.dmi'
this doesnt change anything

2022-12-27 05:59 UTC, merged