Fixes strange geyser and geyser regen
tgstation/tgstation pull request #72221
Opened 2022-12-24 11:49 UTC by Time-Green

Called the random reagent code after it was initialized
Registered the reagent del/remove signal on the geyser, not the reagent datum of the geyser

:cl:
fix: Strange geysers have random reagents again
fix: Geysers regen reagents again
/:cl:

2022-12-25 21:44 UTC, optimumtact commented
you should add unit test

2023-01-02 07:39 UTC, Time-Green commented
Yeah yeah I’ll get to it

2023-01-02 21:31 UTC, Time-Green commented
I got to it

2023-01-03 02:23 UTC, Mothblocks requested changes

2023-01-03 02:23 UTC, Mothblocks commented on code/modules/unit_tests/geyser.dm
> +///Geysers listen to reagent signals to know when to start processing, which is very cool, smart, optimized and fragile
You should explain better waht this is actually testing

2023-01-03 02:23 UTC, Mothblocks commented on code/modules/unit_tests/geyser.dm
> +/datum/unit_test/geyser/Run()
```suggestion
/datum/unit_test/geyser

/datum/unit_test/geyser/Run()
```

We want to document the test, not `Run()`

2023-01-03 02:23 UTC, Mothblocks commented on code/modules/unit_tests/geyser.dm
> +		while(time_passed < 30 SECONDS)
1. You have to change the priority of the test, or you hold up smaller tests which makes running tests locally more annoying
2. You already shouldn't really be sleeping in tests, but 30 seconds is definitely too high IMO. I'm not thrilled with how long our tests are but the ones that are long catch very common regressions, this is definitely past my limit. What are we doing here?

2023-01-03 02:24 UTC, Mothblocks commented
Ideally the way you do time based unit tests is to create subtypes/traits for things to say "do this significantly faster"

2023-01-03 07:34 UTC, Time-Green commented
> Ideally the way you do time based unit tests is to create subtypes/traits for things to say "do this significantly faster"

Aargh thats what I did at first, okay

2023-01-03 08:49 UTC, Time-Green commented
@Mothblocks I took the easy way out and now just fire the subsystem directly to skip waiting completely

2023-01-18 20:13 UTC, merged