Hologram Projectors for TGC! (WIP)
tgstation/tgstation pull request #72226
Opened 2022-12-24 19:28 UTC by NamelessFairy

## About The Pull Request

Once finished this PR will add a new holodeck layout for playing TGC, it'll feature holographic projectors that project images of your creature cards on a field alongside their attack and resolve values.
Example:
![image](https://user-images.githubusercontent.com/40036527/209448756-240aa3f7-7ff2-4b3d-a3ab-f8cc065bb386.png)

## Why It's Good For The Game

TGC is a significantly more complicated game then the other ones we have like UNO and CAS and is extremely messy to play on a table ingame, this provides a much clearer way of visualizing the game by having all active creature stats on full display at all times without having to rely on inspecting cards to check.

## Changelog

:cl:
add: Introducing a new holodeck map, the TGC Arena, featuring hologram projectors for your trading cards.
fix: Janitor and Intern TGC cards are now considered creatures rather than just humans.
/:cl:

2022-12-24 19:45 UTC, Wallemations commented
I wanted to try something similar by making a dual disk or something like that but the cards felt so complicated that I couldn't wrap my head around it
Props to you for figuring out a way to do it

2022-12-24 23:29 UTC, Fikou commented on code/game/objects/items/tcg/tcg.dm
> +	///Below vars are used for displaying holographic summons
this isnt an autodoc

2022-12-27 00:01 UTC, NamelessFairy commented on code/game/objects/items/tcg/tcg.dm
> +	///Below vars are used for displaying holographic summons
Resolving this as this code was removed

2022-12-27 01:18 UTC, Troxonater commented
This is really cool. Perhaps we should look into making trading cards persist between rounds for a character for shits and giggles? Trying to get good cards for your deck could be a fun thing to do for assistant mains between antag rolls. BTW I know nothing about the actual trading card game so tell me if this is a dumb idea or somehow already implemented.

2022-12-28 07:24 UTC, Wallemations commented
If you're putting the holograms on a dark background, the color for the blue text should be much lighter to contrast better

2022-12-28 11:42 UTC, NamelessFairy commented
> If you're putting the holograms on a dark background like the screenshot shows, the color for the blue text should be much lighter to contrast better

I'd changed the resolve color in the commit before your comment, it now looks like this, I was concerned using a brighter color would clash with the AI sprite but this is actually more visible on the AI (although still not "easy" to read unfortunately)

![image](https://user-images.githubusercontent.com/40036527/209806625-48c82849-f5b0-40b3-a0bf-22ae5e3974de.png)

2023-01-02 02:10 UTC, Twaticus approved these changes

2023-01-07 03:40 UTC, ArcaneMusic requested changes
Eyes pogging face TCG revival 2023?

2023-01-07 03:40 UTC, ArcaneMusic commented on code/game/objects/items/tcg/tcg_machines.dm
> +	var/team_color = "#77abff"
Autodoc these if you would, nothing too crazy

2023-01-07 03:40 UTC, ArcaneMusic commented on code/game/objects/items/tcg/tcg_machines.dm
> +#define DEFAULT_RESOLVE_COLOR "#231ac0"
Move to the top of the file for legibility if you would for consistency

2023-01-07 17:53 UTC, ArcaneMusic approved these changes
We agreed on qnty and cost of packs over DMS, It's time to d- d- du-du- DUDUDUDUDUEL

2023-01-07 17:53 UTC, merged