STAY IN THE LIGHT: Adds terrify Nightmare spell, terrified status effect, and a reason to mind the shadows
tgstation/tgstation pull request #72282
Opened 2022-12-27 05:36 UTC by Rhials

## About The Pull Request

Adds the Terrify spell, and its associated status effect, Terrified. This new spell is given to antagonist nightmares, as a part of their brain. The spell only works in those surrounded by darkness, and will apply the Terrified status effect if successful. Upon being Terrified, victims will passively gain **Terror Buildup** if they remain in the dark. As buildup increases, so do the negative effects, including tunnel vision, panic attacks, dizziness, and more.

There are two primary methods for mitigating terror buildup. The first is moving into the light, which will reverse the passive terror buildup and eventually make it go away. The other method is by getting a hug from a friendly hand, which will reduce buildup significantly.

Getting a hug from an UNfriendly hand (a nightmare, for instance) will cause the victim to freak out and be briefly knocked down. This can be spammed on targets who are caught alone in the dark, keeping them in an unfavorable position (sideways) and adding to the victim's terror buildup considerably. Escape into the light as soon as possible, or you'll be pushed to MAXIMUM TERROR BUILDUP.

To what end? Heart failure. Past the soft terror cap (which limits how much passively generated terror you can make) exists the hard terror cap. Bypassing that threshold will cause a stress induced heart attack and knock you unconscious (embarrassing!)

https://user-images.githubusercontent.com/28870487/209616319-e21d1815-7a59-430e-876c-4a6f62cfc766.mp4

In summary -- Nightmares can terrify victims they catch in the dark. This causes panic and makes them easy to trip up during combat. If you panic too hard, you'll have a heart attack. STAY IN THE LIGHT.
## Why It's Good For The Game

Gives Nightmares a sharp advantage when fighting single targets within their territory. Applies pressure on combatants to back out of a fight, and allows Nightmares to bully unprepared targets into submission. (I also wanted to make an objective for giving X crewmembers fear-induced heart attacks, but I don't want to be the guy who gives objectives to Nightmares).

Encourages those hunting nightmares to group up and take care of each other. Gives something interesting to play strategically around, and will hopefully present a dilemma to even the most seasoned of hunters.

Most importantly, it gives something fun for nightmares to do when they're not murdering people. Go forth and be spooky! Give people heart attacks! Be a MENACE!
## Changelog
:cl: Rhials
add: Adds the Terrify spell and Terrified status effect. Terrified victims will suffer increasingly detrimental effects until they're calmed down.
balance: Nightmares can now cast the Terrify spell on victims to plague their prey with. Attacking a Terrified human with your open hand will trip them up.
imageadd: Adds status effect and spell icons for Terrify/Terrified.
spellcheck: fixes a typo in the message for consuming a nightmare heart.
/:cl:

2022-12-27 05:37 UTC, san7890 commented on code/datums/status_effects/debuffs/terrified.dm
> +#define TERROR_HEART_ATTACK_THRESHOLD 600 //If you actively terrorize someone already at the darkness threshold, you can cause a heart attack and knock them out.
transition all of these to dmdoc :)

```txt
/// Amount of terror passively generated (or removed) on every tick based on lighting.
#define DARKNESS_TERROR_AMOUNT 10
```

2022-12-27 05:39 UTC, san7890 commented on code/modules/spells/spell_types/pointed/terrorize.dm
> +		to_chat(owner, span_notice("[cast_on] cannot be terrorized!"))
might be nice to have this be a balloon alert like "can't be terrorized!"? seems more useful to me

2022-12-27 05:47 UTC, san7890 commented
061a11506b5c41a13107512c22e11e96f099d038 - i don't believe the spaces are needed but i do it that way because it looks cleaner to my eyes. whatever really

2022-12-27 06:12 UTC, MrMelbert requested changes

2022-12-27 06:41 UTC, ATH1909 commented
what's the duration on this? does it go away when your terror hits 0?

2022-12-27 07:12 UTC, private-tristan commented
terrify -> hug -> shove is a 2 second stun 👀

2022-12-27 08:37 UTC, IndieanaJones commented
While Nightmare does need buffs to better enable him to do his job, this probably won't do much of anything. Nobody hunting nightmares will be travelling without a light, dragging a light, or using miner lights, so the chance to actually get to use this only really applies to people the nightmare can easily kill as it is now.

That being said, this is flavorful and fun. I like it.

2022-12-27 09:07 UTC, KittyNoodle commented
make people cry when they have panic attacks

2022-12-27 12:17 UTC, Shadowflame909 commented
The true nightmare counter is not powergaming.

It's bar rp

2022-12-27 16:47 UTC, Bluedino1025 commented
It’d be neat if phobia’s also caused terror build up

2022-12-27 19:13 UTC, Serxule commented
i think the rest of this find, but having hugs basically be a telebaton doesnt sound very balanced

2022-12-27 20:29 UTC, IndieanaJones commented
> i think the rest of this find, but having hugs basically be a telebaton doesnt sound very balanced

The fact this only works on people in the dark essentially negates it usability. Also, even if that fact weren't considered, you can always use any sort of stun you possess on the Nightmare, who is completely and utterly susceptible to them.

2022-12-27 23:25 UTC, CMDR-Gungnir commented
> It’d be neat if phobia’s also caused terror build up

Maybe someone could make a PR for that once the status effect exists.

2022-12-28 01:00 UTC, MrDoomBringer commented
I don't really see the need for this. Once you're in the dark without a light you're already screwed. Nightmare needs an aoe-destroy-nearby-lightsources action or something to counter people dragging in 15 lamps in a box to fight him, not more buffs for already being in the dark.

2022-12-28 05:27 UTC, githubuser4141 commented
Does this affect people with NVGs, and people in enclosed mechs? I think people in enclosed mechs should still be *spooked*, but be shielded from the gradual terror buildup that a non-enclosed person would experience. Ala, you're freaked out, but you're physically isolated when you're viewing it through your mecha's sensor slits so it doesn't get to you as bad.

2022-12-28 12:00 UTC, Fikou requested changes
your terrorize spell hard deletes

2022-12-29 23:57 UTC, Fikou commented on code/modules/antagonists/nightmare/nightmare_organs.dm
> +	return ..()
no, only delete the spell if the eyes are deleted (in Destroy), this will runtime if the eyes are removed and inserted into someone

2023-01-02 01:43 UTC, Twaticus approved these changes

2023-01-07 11:02 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +			owner.visible_message(span_warning("[owner] drops to the floor for a moment, clutching their chest."), span_alert("Your heart lurches in your chest. You can't take much more of this!"), span_hear(
```suggestion
			owner.visible_message(
				span_warning("[owner] drops to the floor for a moment, clutching their chest."),
				span_alert("Your heart lurches in your chest. You can't take much more of this!"),
				span_hear("You hear a grunt."),
			)
```

2023-01-07 11:02 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +		owner.visible_message(span_warning("[owner] clutches [owner.p_their()] chest for a moment, then collapses to the floor."), span_alert("The shadows begin to creep up from the corners of your vision,
```suggestion
		owner.visible_message(
			span_warning("[owner] clutches [owner.p_their()] chest for a moment, then collapses to the floor."), 
			span_alert("The shadows begin to creep up from the corners of your vision, and then there is nothing..."), 
			span_hear("You hear something heavy collide with the ground."),
		)
```

2023-01-07 11:02 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +			owner.visible_message(span_warning("[owner] recoils in fear as [hugger] waves [hugger.p_their()] arms and shrieks at [owner.p_them()]!"), span_boldwarning("The shadows lash out at you, and you dro
```suggestion
			owner.visible_message(
				span_warning("[owner] recoils in fear as [hugger] waves [hugger.p_their()] arms and shrieks at [owner.p_them()]!"),
				span_boldwarning("The shadows lash out at you, and you drop to the ground in fear!"),
				span_hear("You hear someone shriek in fear. How embarassing!"),
			)
```

2023-01-07 11:02 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +			addtimer(CALLBACK(src, PROC_REF(freak_out), HUG_TERROR_AMOUNT))
Do we want this to be a chain-stun? If not, then maybe it will only affect people standing up?

2023-01-16 23:31 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +	if(is_species(hugger, /datum/species/shadow/nightmare)) //hey wait a minute, that's not a comforting, friendly hug!
```suggestion
	if(isnightmare(hugger)) //hey wait a minute, that's not a comforting, friendly hug!
```

2023-01-16 23:32 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +			addtimer(CALLBACK(src, PROC_REF(freak_out), HUG_TERROR_AMOUNT))
That's fair, just wanted to make sure it was thought-out.

2023-01-16 23:36 UTC, JohnFulpWillard commented on code/datums/status_effects/debuffs/terrified.dm
> +	return
Don't need to return here, it's end of the proc

2023-01-17 00:07 UTC, merged