RCD cant destroy indestructible windows fix
tgstation/tgstation pull request #72289
Opened 2022-12-27 16:06 UTC by Salex08

## About The Pull Request

closes: https://github.com/tgstation/tgstation/issues/72271

I tested on a local server to see if there are more indestructible things the rcd can destroy couldnt find any further.

## Why It's Good For The Game

bug fix

## Changelog

:cl:
fix: RCD cant destroy indestructible windows anymore
/:cl:

2022-12-27 16:06 UTC, Fikou commented
can ya fix it for fire axes too?

2022-12-27 16:13 UTC, Salex08 commented
> can ya fix it for fire axes too?

you mean firelocks?

2022-12-27 16:22 UTC, Fikou commented
> > can ya fix it for fire axes too?
> 
> you mean firelocks?

no, fire axes can break indestructible windows

2022-12-27 16:23 UTC, Salex08 commented
> > > can ya fix it for fire axes too?
> > 
> > 
> > you mean firelocks?
> 
> no, fire axes can break indestructible windows

ahhh sorry, thats weird I will be on it

2022-12-27 16:47 UTC, SyncIt21 commented
I KNEW IT!!

A lot of other PR's have been failing for the exact same reason

![Screenshot (70)](https://user-images.githubusercontent.com/110812394/209696547-108c4fae-3d72-4960-88f2-926d47a404b6.png)

I have a strong feeling it was caused by #72033

2022-12-27 16:59 UTC, Salex08 commented
> I KNEW IT!!
> 
> A lot of other PR's have been failing for the exact same reason
> 
> ![Screenshot (70)](https://user-images.githubusercontent.com/110812394/209696547-108c4fae-3d72-4960-88f2-926d47a404b6.png)
> 
> I have a hunch it was caused by #72033 but it also doesn't make sense cause all tests were passing yesterday

well am i supposed to empty commit until it eventually stops giving me unrelated error?

2022-12-27 16:59 UTC, Salex08 commented
> > > can ya fix it for fire axes too?
> > 
> > 
> > you mean firelocks?
> 
> no, fire axes can break indestructible windows

ok done

2022-12-27 17:02 UTC, SyncIt21 commented
> > I KNEW IT!!
> > A lot of other PR's have been failing for the exact same reason
> > ![Screenshot (70)](https://user-images.githubusercontent.com/110812394/209696547-108c4fae-3d72-4960-88f2-926d47a404b6.png)
> > I have a hunch it was caused by #72033 but it also doesn't make sense cause all tests were passing yesterday
> 
> well am i supposed to empty commit until it eventually stops giving me unrelated error?

Did that didn't work.  Have to wait until the guy whie messed up magic cards or something else gets here.
U have nothing to worry about

2022-12-27 18:20 UTC, Mothblocks commented
its not you ill deal with it latre

2022-12-27 19:48 UTC, Jacquerel commented
> its not you ill deal with it latre

I think #72266 fixes it

2022-12-28 22:10 UTC, ZephyrTFA requested changes

2022-12-28 22:10 UTC, ZephyrTFA commented on code/game/objects/items/fireaxe.dm
> +			if(!A.resistance_flags && INDESTRUCTIBLE)
```suggestion
			if(!(A.resistance_flags & INDESTRUCTIBLE))
```

2022-12-28 22:10 UTC, ZephyrTFA commented on code/modules/awaymissions/mission_code/murderdome.dm
> +
```suggestion
	return FALSE
```

2022-12-30 08:08 UTC, lessthnthree commented
So if the tram currently has
resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF

Is that going to make it actually indestructible now? That's not ideal and would have to change.

2022-12-30 14:27 UTC, Salex08 commented
> So if the tram currently has resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF
> 
> Is that going to make it actually indestructible now? That's not ideal and would have to change.

no it doesnt look closely at code

`if(istype(A, /obj/structure/window) || istype(A, /obj/structure/grille))`

2022-12-30 14:31 UTC, ZephyrTFA commented
> So if the tram currently has resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF
> 
> Is that going to make it actually indestructible now? That's not ideal and would have to change.

I'm confused as to where you've supposedly seen this

2022-12-30 14:31 UTC, ZephyrTFA approved these changes

2022-12-30 14:38 UTC, merged