Minor detectives spawn with a candy cigarette and
tgstation/tgstation pull request #72422
Opened 2023-01-02 16:45 UTC by NamelessFairy

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-01-02 16:46 UTC, NamelessFairy commented
I misclicked enter oh fuck

2023-01-02 16:47 UTC, Fikou requested changes

2023-01-02 16:47 UTC, Fikou commented on code/modules/vending/wardrobes.dm
>  		)
```suggestion
	)
```

2023-01-02 16:47 UTC, Fikou commented on code/modules/jobs/job_types/detective.dm
> +	if (H.age < AGE_MINOR)
use descript variable names

2023-01-02 16:47 UTC, Fikou commented on code/modules/clothing/head/jobs.dm
> +	var/flask = /obj/item/reagent_containers/cup/glass/flask/det
new vars at the bottom, needs documentation, change name to flask_path

2023-01-02 16:51 UTC, Bawhoppen commented
https://www.youtube.com/watch?v=FhUixnJU2-Y

2023-01-02 17:12 UTC, Fikou commented on code/modules/clothing/head/jobs.dm
> +	//Path for the flask that spawns inside their hat roundstart
```suggestion
	///Path for the flask that spawns inside their hat roundstart
```
three slashes mean autodoc, two just mean a comment

2023-01-02 18:44 UTC, Mothblocks approved these changes
cute

2023-01-03 03:58 UTC, bluetshirtguy commented
They deserve to be in jail for playing as a young detective tbh.

2023-01-03 04:16 UTC, Bawhoppen commented
They should get a plastic "Honorary Detective" badge, like the kind kids get at county fairs or when the cops talk to the kids at school

2023-01-03 05:57 UTC, Shadowflame909 commented
Now this is the Soulful coding that makes this space station feel more alive

2023-01-03 13:33 UTC, JohnFulpWillard commented
> They should get a plastic "Honorary Detective" badge, like the kind kids get at county fairs or when the cops talk to the kids at school

Detectives don't even have any badges currently (though they should so I can play as M. Vonel)

2023-01-03 18:19 UTC, Bawhoppen commented
Instead of ID cards maybe they could get badges

2023-01-04 01:21 UTC, Livrah commented
Replace .38 with a toy gun.

2023-01-07 10:47 UTC, merged