Fixes being able to instantly create dense grilles
tgstation/tgstation pull request #72449
Opened 2023-01-03 20:44 UTC by Iamgoofball

:cl: 
fix: Fixes being able to instantly create dense grilles
/:cl:

2023-01-03 20:49 UTC, dragomagol commented on code/game/objects/structures/grille.dm
> +	if(istype(W, /obj/item/stack/rods) && broken && do_after(user,20, target = src))
```suggestion
	if(istype(W, /obj/item/stack/rods) && broken && do_after(user, 2 SECONDS, target = src))
```

2023-01-03 20:50 UTC, NamelessFairy commented
Really massive slowdown for building windows. If the issue is creating hard stun traps could we just make it so that they don't get electrified until after a delay?

2023-01-03 20:51 UTC, Fikou requested changes
needs to take as much time (or less, maybe you can put that behind tinkerer gloves) as building them, not more

2023-01-03 20:52 UTC, Fikou commented
> Really massive slowdown for building windows

why are you building windows off broken grilles

2023-01-03 21:07 UTC, NamelessFairy commented
> > Really massive slowdown for building windows
> 
> why are you building windows off broken grilles

Nevermind was under the impression this was nerfing placing them in the first place after seeing the video earlier

2023-01-03 21:32 UTC, NamelessFairy commented
Anyways now that that mixup is cleared up, gonna suggest reducing it down to a second so its the same as actually building them from scratch.

2023-01-04 03:18 UTC, ATH1909 commented
"fixes"

2023-01-04 06:25 UTC, improvedname commented
> the title of this PR is very misleading; this actually applies to repairing existing, broken grilles. why is repairing them being instant a problem?

2023-01-04 10:03 UTC, CRITAWAKETS commented
why two entire seconds

2023-01-05 07:48 UTC, moocowswag commented
This is a fix?

2023-01-05 13:30 UTC, improvedname commented
skillbased exploirs fr

2023-01-05 13:31 UTC, improvedname commented
d

> This is a fix?
> 
> so anyone that was using instant grilles was exploiting?

not a bug, oversight.
bugs are like being able to infinitely stack ka cooldowns

2023-01-07 13:13 UTC, merged