Fixes and buffs Metal Hydrogen golems
tgstation/tgstation pull request #72482
Opened 2023-01-05 03:38 UTC by dawsonkeyes

## About The Pull Request

Metal Hydrogen golems as of now are quite literally not even immune to _space_ and _the cold_, despite their description insinuating the exact opposite and their manner of creation being more time-intensive than any other golem. This PR fixes that, putting them on-par with all other golems in regards to temperature and space immunity, whilst also _hugely_ buffing them so they're not simply an antimagic version of adamantine golems - instead, they're now most metal golems rolled into one power-wise, with the armor of diamond golems as is befitting.

Also, I fixed their colors and wording (metal hydrogen isn't a _mineral_, it doesn't naturally occur)

## Why It's Good For The Game

Creating metal hydrogen golems is not wholly difficult if you understand atmospherics and practice safety in doing so, but compared to all other golems they are _woefully_ underpowered and nigh-useless in most practical applications. Adamantine golems are better in effectively every way, and they're the standard for easily-created golems. Properly fixing them and buffing them to ensure they're worth making is an effective way to make metal hydrogen a more worthy endeavor for atmospherics, and also metal hydrogen is simply cool.

## Changelog

:cl:
fix: metal hydrogen golems no longer die to low pressures and cold temperatures
balance: metal hydrogen golems are also now REALLY strong
/:cl:

2023-01-05 04:27 UTC, Serxule commented
definitely needed, afaik (havent seen them in game ever) they are literally just chaplains doing the fire path

2023-01-05 04:36 UTC, improvedname commented
wasnt the whole gimmick of metla hydrogen golems they are tanky af but they get fucked up in atmos

2023-01-05 04:43 UTC, Serxule commented
> wasnt the whole gimmick of metla hydrogen golems they are tanky af but they get fucked up in atmos

the wiki says they're fire and heat proof and immune to magic, and thats it, that is literally all they apparently have. not space or pressure proof

2023-01-05 04:55 UTC, dawsonkeyes commented
> wasnt the whole gimmick of metla hydrogen golems they are tanky af but they get fucked up in atmos

That's the intended gimmick! Unfortunately as of now they're actually the exact same as cardboard golems with none of the gimmick.

2023-01-05 06:23 UTC, dawsonkeyes commented
Extra funny fact: they had _blood_, as golems, for whatever reason.

2023-01-05 06:57 UTC, ATH1909 commented on code/modules/mob/living/carbon/human/species_types/golems.dm
> +	info_text = "As a <span class='danger'>Metallic Hydrogen Golem</span>, you were forged in the highest pressures and the highest heats. Your unique material makeup makes you immune to magic, most env
```suggestion
	info_text = "As a <span class='danger'>Metallic Hydrogen Golem</span>, you were forged in the highest pressures and the highest heats. Your unique material makeup makes you immune to magic and most environmental damage. You also take less damage from attacks."
```

2023-01-05 09:59 UTC, Serxule commented
> is this a wizard buff

honestly if you want a wizard counter use plasteel golems

2023-01-05 17:15 UTC, dawsonkeyes commented
> is this a wizard buff

It would be, if they didn’t have magic immunity (which as of now is the only thing they have over cardboard golems)

2023-01-08 09:31 UTC, Mothblocks requested changes
If the color change is intentional it must be in the changelog as it is a player-visible change

2023-01-08 19:44 UTC, SinfulBliss commented
good PR, just made metal h2 golems and they can't even walk over shards since their feet are counted as bare and they can't wear shoes since they're golems. much needed fix

2023-01-08 20:30 UTC, dawsonkeyes commented
> If the color change is intentional it must be in the changelog as it is a player-visible change

👍

2023-01-08 20:33 UTC, dawsonkeyes commented
> good PR, just made metal h2 golems and they can't even walk over shards since their feet are counted as bare and they can't wear shoes since they're golems. much needed fix

this gives them TRAIT_PIERCEIMMUNE like most other non-soft golems, so it fixes this

2023-01-12 17:58 UTC, jlsnow301 commented
sounds pretty strong but requires cooperative and competent departments to create so i'll allow it

2023-01-12 17:58 UTC, merged