makes organs a mapped out variable on species, culling out stuff like mutanteyes, mutantheart etc
tgstation/tgstation pull request #72498
Opened 2023-01-05 23:43 UTC by Fikou

## About The Pull Request

what the title says, every species has an explicitly filled out list of organs
in addition, we remove organ_status because its useless when synthetic_organ flag exists (also gives it to robotic wings)
also, fixes ethereal heart revives not having their downsides
removes get_availability
changes some regenerate_organs behavior (needs testmerge), adminhealing someone will no longer remove all their unique organs

## Why It's Good For The Game

cool

## Changelog

:cl:
fix: ethereal hearts will now heal stuff they should instead of everything
admin: admin heals will no longer remove unique organs
/:cl:

2023-01-05 23:51 UTC, Kapu1178 requested changes
![image](https://user-images.githubusercontent.com/75460809/210901834-e39745ee-cb43-4f1f-9c1c-ffa4d87e1f9d.png)

2023-01-07 11:45 UTC, Time-Green requested changes

2023-01-07 11:45 UTC, Time-Green commented on code/modules/mob/living/carbon/human/species.dm
> +		ORGAN_SLOT_XENO_EGGSAC = NO_ORGAN,
This is a massive maintainability hazard. Either make NO_ORGAN implicit, or do what @MrMelbert did in #72080 and turn it into a getter proc that returns the default organ loadout that you can overwrite/adjust so you reduce massive amounts of copypaste.

2023-01-07 11:45 UTC, Time-Green commented on code/modules/mob/living/carbon/human/species.dm
> +		ORGAN_SLOT_XENO_EGGSAC = NO_ORGAN,
I'll review the rest later

2023-01-18 20:05 UTC, Time-Green reviewed
Documentation. Code looks fine, gonna conflict a lot though and you still need to change how you store the species organ data (see previous review)

2023-01-18 20:05 UTC, Time-Green commented on code/modules/mob/living/carbon/human/species.dm
> +/datum/species/proc/get_organ_paths(internal = FALSE, external = FALSE)
Autodoc

2023-02-01 15:27 UTC, Fikou commented
lol

2023-02-01 15:27 UTC, closed without merging

2023-02-01 15:33 UTC, Time-Green commented
coward

2023-06-26 15:56 UTC, ChungusGamer666 commented
soon you'll be revived my friend

soon