Basic Mob Refactor and Bad Pattern Avoidance: Removes Temp and Atmos and Sentience type vars, enforces considering them
tgstation/tgstation pull request #72524
Opened 2023-01-06 22:24 UTC by tralezab

## About The Pull Request

Recently, a pr #71817 attempted to fix the fact that a lot of basic mobs have accidentally been implemented without proper environmental values, but they did it in a way very antithetical to basic mobs, they made them
🤮 DEFAULT 🤮 VARIABLES 🤮 
We're trying to avoid bloating basic mobs like that, it goes against the reason we're componentizing this behavior in the first place. It could have a valid reason, basic mobs... HAVE VARIABLES, obviously, but in this case it was setting default behavior for atmos component because people were forgetting to add it. The answer to forgetting is not bloating our variables, it is forcing contributors to consider environmental factors the mob is either immune or weak to with unit testing!

- Adds unit tests to make sure you've either flagged a mob as non-temp/atmos/sentience OR you have given them the correct components.
- Componentizes sentience options, as I thought that was relevant, but I need to revisit that as it isn't copying behavior from the old right now well, letting mobs not intended to be sentienced get sentienced.

- [ ] Reconsider removing sentience defines for now or think of a different solution for flag checking

## Why It's Good For The Game

Removes needless variables for things that may or may not be on the mob at the base level of basic mobs, godobjecting the tree.

## Changelog

:cl:
refactor: Refactors environment behavior for some mobs, report any mobs that shouldn't be surviving in space but are and vice versa. Or things that shouldn't be able to be sentienced by a potion. Sorry in advance...
/:cl:

2023-01-06 22:27 UTC, tralezab commented
This should now fail on every mob that wasn't given consideration on their environment elements, which is intended

2023-01-06 22:31 UTC, MrMelbert requested changes

2023-01-07 03:03 UTC, kawoppi commented
![image](https://user-images.githubusercontent.com/94711066/211128474-361744be-cd18-4285-9f37-8b786fe32f67.png)

2023-01-07 08:35 UTC, Mothblocks commented on code/__DEFINES/basic_mobs.dm
> +#define BASIC_ATMOS_REQUIREMENTS string_assoc_list(list("min_oxy" = 5, "max_oxy" = 0, "min_plas" = 0, "max_plas" = 1, "min_co2" = 0, "max_co2" = 5, "min_n2" = 0, "max_n2" = 0))
This is a surprisingly expensive amount of work. You should make this a GLOB instead.

2023-01-07 08:35 UTC, Mothblocks commented
youre going to want named params for all those elements that are just numbers

2023-01-07 17:45 UTC, tralezab commented
> #37793 is old but maybe this PR can address it properly.

Sure, since every mob will at least be forced to consider environment elements

2023-01-16 07:15 UTC, ATH1909 commented
will this cause a flame war in the comments section of any pr that adds a new basic mob over whether that mob should/shouldn't have sentience?

2023-01-29 17:06 UTC, tralezab commented
okay we're officially on the worst timeline i'll come back to this maybe during the freeze

2023-01-29 17:06 UTC, closed without merging