RCDs can build computer & machine frames on tiles containing directional windows
tgstation/tgstation pull request #72593
Opened 2023-01-09 15:32 UTC by SyncIt21

## About The Pull Request

If a turf has a directional window or a reinforced directional window it now won't stop, you from making a machine/computer frame on that turf with the RCD

Fixes #59507

## Changelog

:cl:
fix: Directional windows won't block construction of machine & compute frames by the RCD
/:cl:

2023-01-12 06:31 UTC, SyncIt21 commented
Merge/Review anyone?

2023-01-14 17:23 UTC, Time-Green requested changes

2023-01-14 17:23 UTC, Time-Green commented on code/game/objects/items/RCD.dm
> +		var/list/directional_windows = list()
Can you name this something more generic? Like ignored atoms

2023-01-15 07:08 UTC, SyncIt21 commented
@Time-Green good to see you :)

2023-01-15 08:51 UTC, merged

2023-01-15 08:51 UTC, Time-Green commented
> @Time-Green good to see you :)

:)