Fixes Log Globally Being Called On Victim Procs
tgstation/tgstation pull request #72643
Opened 2023-01-11 06:49 UTC by san7890

## About The Pull Request

Victim procs would cause a [runtime, click on me for a link to the runtimebus entry](https://runtimes.moth.fans/runtime/Invalid%20individual%20logging%20type%3A%20524288.%20Defaulting%20to%204096%20(LOG_GAME).%20(code%2F__HELPERS%2Flogging%2F_logging.dm%3A120)_______%2Fproc%2F_stack_trace) when you tried to put a victim log in globally. This was the runtime error for future reference, via https://tgstation13.download/parsed-logs/manuel/data/logs/2023/01/06/round-197717/runtime.condensed.txt -

```
The following runtime has occurred 3155 time(s).
runtime error: Invalid individual logging type: 524288. Defaulting to 4096 (LOG_GAME). (code/__HELPERS/logging/_logging.dm:120)
proc name:  stack trace (/proc/_stack_trace)
  source file: stack_trace.dm,4
  usr: 0
  src: null
```

`524288` is the bitflag for `LOG_VICTIM`.

I added in a custom error message for passing in LOG_VICTIM without adding log_globally just so that we can pick up on it faster without having to look up the bitflags. I think I prefer it failing loudly as opposed to just returning, so that people can much more easily pick up on this behavior being a wrong one. The pattern across the codebase prior to this PR was pass in log_globally as false along with LOG_VICTIM in the args to `log_message()`, so I decided to enforce doing that in this PR. Alternative fix could be to just early return on LOG_VICTIM, but that would leave a larger footprint and might be better suited for a different PR, preferably after this one at least gets all of our ducks in a row.

## Why It's Good For The Game

runtimes bad, actual logging of important stuff good.

apologies if i screwed up how LOG_VICTIM is meant to be used, but something is definitely wrong and should be addressed. i'm pretty sure victim logs are only done in addition to a proper log that gets sent globally, and this is good just for visibility?

## Changelog

Nothing that players would notice.

2023-01-11 06:51 UTC, san7890 commented
might also be nice to include some sort of grep or linter against this but i'll leave that for someone else (or if we decide to early return on calling `LOG_VICTIM` in a later PR)

2023-01-11 06:52 UTC, san7890 commented
actually wait i think i'm doing something wrong i'm going to draft this until i can figure it out

2023-01-11 06:53 UTC, san7890 commented
oh i see, i wasn't doing anything wrong. phew

2023-01-11 07:02 UTC, dragomagol requested changes
If these lines are not logged elsewhere, then making them not global will remove them from any post-game logs. In my opinion this has a couple solutions:
- Change the log type to LOG_ATTACK and set `color="orange"` (this means that it'll appear as a victim log in the player's logs, as those are just orange (this should probably be a define or something but that is for another time))
- Have LOG_VICTIM also write to the attack log if it is being logged globally

If they are logged elsewhere, feel free to disregard, and this solution is fine. But I think it makes less sense to have a stack trace for this specific case rather than linting for it.

2023-01-11 07:15 UTC, Mothblocks commented
> Have LOG_VICTIM also write to the attack log if it is being logged globally

This is my preferred solution IMO, this is too easy to mess up and not see in CI because these aren't the kinds of procs we have coverage over in tests

2023-01-11 07:32 UTC, san7890 commented
i reviewed all of the instances of LOG_VICTIM where log_globally was not already added, and only one of them made logical sense to log globally (or at the very least, was not logged anywhere else or was not feasible to log anywhere else). the behavior should now be changed to add it to attack log as well, if you want me to make another proc that handles it outside of the switch statement let me know.

2023-01-11 18:48 UTC, dragomagol requested changes

2023-01-11 18:48 UTC, dragomagol commented on code/__HELPERS/logging/_logging.dm
> +			// ensure that it gets placed in attack log (for post-round storage) just to ensure we don't lose out on information.
Comment should be more concise; what info would a coder _need_ to know here? Probably just that this is an atypical log type used primarily for the player panel.

In a sad twist of fate this doesn't even make the player panel log orange.

2023-01-11 18:48 UTC, dragomagol commented on code/__HELPERS/logging/_logging.dm
> +			log_attack(transcribed_victim_log)
```suggestion
			log_attack(log_text)
```

2023-01-11 18:48 UTC, dragomagol commented on code/__HELPERS/logging/_logging.dm
> +			log_attack(transcribed_victim_log)
It's not important that we know that this was a victim log; could do `if(LOG_ATTACK || LOG_VICTIM)`

2023-01-12 00:58 UTC, dragomagol approved these changes

2023-01-12 18:12 UTC, merged