Refactors crew records
tgstation/tgstation pull request #72725
Opened 2023-01-15 02:15 UTC by jlsnow301

## About The Pull Request
I have attempted or otherwise started this project at least 4 times. I am sick of it being on my calendar. The code needs it. I need it.

- This makes crew records a proper datum rather than assigning properties record.fields.
- General, medical, and security records are merged.
- Did some slight refactoring here and there for things that looked obvious.
- Wanted states are now defined (and you can suspect someone through sechud)
- pAI (unrelated but annoying) had some poorly named exported types that i made more specific
- Job icons are moved back to the JS side (I wanted to get icons for initial rank without passing trim)

<details>
<summary>previews</summary>

Editable fields & security console
![CM6d74brnC](https://user-images.githubusercontent.com/42397676/213950290-af6cfd76-eb8b-48e9-b792-925949311d9a.gif)

Medical records
![bFJErsvOaN](https://user-images.githubusercontent.com/42397676/214132534-59af1f8c-9920-4b51-8b27-297103649962.gif)

Look and feel of the more current version
![cxGruQsJpP](https://user-images.githubusercontent.com/42397676/214132611-0134eef0-e74c-4fad-9cde-328ff7c06165.gif)

</details>

## Why It's Good For The Game
TGUI'd some of the worst UIs in the game.
Creating new records is made much simpler. 
Manifest_inject is made readable.
Probably bug fixes

## Changelog

:cl:
refactor: Crew records have been refactored.
refactor: Medical records -> TGUI
refactor: Security records -> TGUI
refactor: Warrants console -> TGUI
qol: Players are now alerted when their fines are paid off.
qol: Cleaned up sec hud examination text.
qol: Adding and deleting crimes is easier.
qol: Writing crimes in the console sets players to arrest.
qol: You can now mark someone as a suspect through sec hud.
/:cl:

2023-01-15 02:39 UTC, ShizCalev requested changes
these are really vague and are better off with ACTUALLY READABLE NAMES.

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	crim = list(),
please fucking kill `crim`.

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	p_stat = "Active",
what the fuck is `p_stat`

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	m_stat = "Stable",
what the fuck is `m_stat`.

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	mi_dis = "None",
`mi_dis`

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	ma_dis = "None",
`ma_dis`

2023-01-15 02:39 UTC, ShizCalev commented on code/datums/records/record.dm
> +	id = "000000",
`id_number`

2023-01-15 02:41 UTC, jlsnow301 commented
@ShizCalev these awful var names are on the chopping block for sure. just getting it sorted before i start mass renaming vars

2023-01-15 04:56 UTC, jlsnow301 commented
just going to redo the security, medical, records consoles idc

2023-01-15 10:49 UTC, timothymtorres commented on code/datums/records/record.dm
> +	mi_dis = "None",
minor disability

2023-01-15 10:49 UTC, timothymtorres commented on code/datums/records/record.dm
> +	ma_dis = "None",
major disability

2023-01-18 08:45 UTC, timothymtorres commented
You should post the gifs you shared on the discord to the OP.  Also you are doing god's work man!

2023-01-19 18:19 UTC, jlsnow301 commented
Should be good for TM / review

2023-01-20 05:04 UTC, TheSmallBlue commented
A very common complaint I hear in game that I 100% agree with: Why take away the ability to search by name/job on both consoles? It makes everything way harder than it has to be...

2023-01-20 07:28 UTC, jlsnow301 commented
> A very common complaint I hear in game that I 100% agree with: Why take away the ability to search by name/job on both consoles? It makes everything way harder than it has to be...

jobs search is now in. in addition to the icons, added earlier. you can now search job/name/dna or job/name/fingerprint respective of console

2023-01-20 18:17 UTC, jlsnow301 commented
Ready. Reviews appreciated

2023-01-21 19:45 UTC, ArthuroPep commented
SEChud seems to not work properly now

2023-01-22 17:20 UTC, OverwatchVoice commented
Some errors / omissions I noticed:

- Attempting to interface with the security records console as an AI throws an NTOS crash.
- Adding notes to crew in medical records doesn't show who made that note, as far as I can tell.

2023-01-22 20:24 UTC, jlsnow301 commented
> * Attempting to interface with the security records console as an AI throws an NTOS crash.
> * Adding notes to crew in medical records doesn't show who made that note, as far as I can tell.
> * No way to add / remove / edit security / medical record entries

The first two, fixed.
The last: Not sure about yet. Especially adding new records: How will I get images? 
Though I may reimplement editing and deleting, the problem is that they're linked and directly affect one another.
Medical records have no login && users could simply delete security records (faster than ever)

2023-01-22 20:40 UTC, JohnFulpWillard requested changes
Problems I have:

1. security record consoles log out automatically if someone without access opens it
2. medical records don't need to log in to see people's medical records, only the notes
3. people's information is not editable (age, species, gender, DNA, job), this is a big problem because it ruins things like adding people to the manifest.
4. there's no way to remove people from the manifest, there used to have a mass delete button to delete all records too. Removing people from the manifest is important because silicon with crew-based lawsets would be countered by removing people from the manifest.
5. Setting a crime on someone will set them to arrest but the UI will still say they aren't

2023-01-23 00:53 UTC, jlsnow301 commented
> Problems I have:
> 
> 1. security record consoles log out automatically if someone without access opens it
> 2. medical records don't need to log in to see people's medical records, only the notes
> 3. people's information is not editable (age, species, gender, DNA, job), this is a big problem because it ruins things like adding people to the manifest.
> 4. there's no way to remove people from the manifest, there used to have a mass delete button to delete all records too. Removing people from the manifest is important because silicon with crew-based lawsets would be countered by removing people from the manifest.
> 5. Setting a crime on someone will set them to arrest but the UI will still say they aren't

outside of adding entirely new records (confused about this), you can now purge and delete specific records, also add information to currently existing ones (all fields text editable)

2023-01-23 19:32 UTC, jlsnow301 commented
You can now create new records by uploading a photo. This is ready

2023-01-24 18:34 UTC, tralezab approved these changes
We'll do it live! (It's now documented, and I didn't notice anything outrageously wrong)

2023-01-24 18:34 UTC, merged

2023-01-24 23:31 UTC, JupiterJaeden commented
I would ask three things: First, that you remove the new character limit on crime names; it's way too short. Second, that you please remove the "quality of life" change of automatically setting suspects to arrest. There are several reasons you might not want someone set to arrest automatically when you put in a crime; perhaps you only want them set to suspected, perhaps you are filling it in retroactively after already having arrested them. 

And finally, PLEASE get the bugs under control. Particularly the rampant visual glitches with SecHUDs; sometimes it's either not showing arrest status at all, or sometimes it IS showing arrest status; except when it's set to "none", in which case the last status set beforehand is still visible (i.e. they still appear to be "arrest" even though it is now set to "none"). This second bug seems to be the most recent one.

2023-01-25 01:18 UTC, jlsnow301 commented
the name portion is intentional, literally why have a description section which is 1024 characters when you could just type the name out of the entire crime. the box says "BRIEF DESCRIPTION".  

the name has the chance to clip on the rapsheet printout and the collapsibles of multiple UIs

please make an issue report for the other stuff

2023-01-25 02:52 UTC, jlsnow301 commented
wb vandalism

2023-01-27 03:16 UTC, JupiterJaeden commented
My point on the automatically setting to arrest thing is that it's not really a quality of life change. It just adds something you have to remember whenever you touch the security records to avoid accidentally setting someone to arrest; which I've already seen happen.