Replace most uses of say() on tape recorder with balloon alerts to reduce spam
tgstation/tgstation pull request #72784
Opened 2023-01-18 04:11 UTC by cacogen

## About The Pull Request
The tape recorder would spam the chat with multiple spoken lines when Play was pressed on an empty tape or when playback ended. This fixes that by replacing them with balloon alerts only visible to people within one tile of the recorder.

## Why It's Good For The Game
Less chat spam

## Changelog

:cl:
qol: Tape recorder uses balloon alerts instead of chat messages to reduce spam
fix: You can no longer get a tape stuck in the tape recorder by unspooling it before inserting
/:cl:

2023-01-18 08:12 UTC, Iamgoofball commented
this makes it impossible to play a tape recorder into a radio :-1:

2023-01-18 13:03 UTC, Mothblocks requested changes
I'll review the rest later but make sure you follow those rules throughout everything else

2023-01-18 13:03 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +		balloon_alert_to_viewers("no tape!", vision_distance = 1)
```suggestion
		balloon_alert(user, "no tape!")
```

2023-01-18 13:03 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +		balloon_alert_to_viewers("stop the tape first!", vision_distance = 1)
```suggestion
		balloon_alert(user, "stop the tape first!")
```

2023-01-18 13:03 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +	balloon_alert_to_viewers("ejected [mytape]!", vision_distance = 1)
```suggestion
	balloon_alert(user, "ejected tape")
```

2023-01-18 15:30 UTC, VladinXXV commented
> Playback still uses say().

Playback still uses say(), according to the description, so I don't see how this changes?

2023-01-18 15:31 UTC, VladinXXV commented
> this makes it impossible to play a tape recorder into a radio 👎

Playback still uses say(), according to the description, so I don't see how this changes?

2023-01-18 16:30 UTC, BlueMemesauce commented
I see how it could be confusing if you only read the changelog. It should say something like qol: Tape recorder actions (starting/stopping playback) now use balloon alerts to reduce spam

2023-01-18 17:00 UTC, VladinXXV commented
> I see how it could be confusing if you only read the changelog. It should say something like qol: Tape recorder actions (starting/stopping playback) now use balloon alerts to reduce spam

Good point, yeah, that changelog is confusing.

2023-01-19 05:54 UTC, cacogen commented on code/game/objects/items/devices/taperecorder.dm
> +		balloon_alert_to_viewers("inserted [mytape]!", vision_distance = 1)
Thanks

2023-01-22 04:14 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +				balloon_alert(usr, "[(max - used) / 10] seconds left")
```suggestion
				balloon_alert(usr, "[(max - used) / 10] second\s left")
```

2023-01-22 04:14 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +			sleep(1 SECONDS) //prevents multiple balloon alerts covering each other
```suggestion
			stoplag(1 SECONDS) //prevents multiple balloon alerts covering each other
```

2023-01-22 04:15 UTC, Mothblocks requested changes

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +		balloon_alert(user, "[src] is empty!")
```suggestion
		balloon_alert(user, "it's empty!")
```

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +		balloon_alert(usr, "[mytape] is empty!")
```suggestion
		balloon_alert(usr, "tape is empty!")
```

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +	balloon_alert(usr, "transcript printed, [page_count] pages")
```suggestion
	balloon_alert(usr, "transcript printed\n[page_count] page\s")
```

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +			balloon_alert(usr, "data corrupted, cannot print!")
```suggestion
			balloon_alert(usr, "data corrupted, can't print!")
```

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +				balloon_alert(user, "flipped [src]")
```suggestion
				balloon_alert(user, "flipped tape")
```

2023-01-22 04:15 UTC, Mothblocks commented on code/game/objects/items/devices/taperecorder.dm
> +				balloon_alert(user, "unspooled [src]")
```suggestion
				balloon_alert(user, "unspooled tape")
```

2023-02-03 04:06 UTC, merged