[WEBEDIT INCOMING]Allows any atom that is not an effect to increase supermatter matter power on consumption.
tgstation/tgstation pull request #73029
Opened 2023-01-29 00:29 UTC by Pickle-Coding

If the consumed_object does not pass the isitem check, then it increases the matter_increase by half of consumed_object.max_integrity, capped at 4000.

# WEBEDIT INFORMATION
This is indeed a webedit, but I tested the changes on local.

## About The Pull Request
If the atom is not an item, the matter power increase will be half of the object's max integrity, up to a maximum of 4GeV (in case some object has an absurd amount of integrity).

## Why It's Good For The Game
When a physical object gets consumed by the supermatter, people expect it to do what it does for items, to give it trickled power over time. It's confusing when it doesn't increase the power.

## Changelog

:cl:
fix: Objects that are not items can increase supermatter power on consumption.
/:cl:

2023-01-29 00:31 UTC, TheVekter commented
Can we do something about the kind of lag these set-ups cause before actually making it more attractive to set them up? Someone did a pill SM on Manuel last round and looking at it tanked the hell out of my response time.

2023-01-29 00:32 UTC, TemporalOroboros commented
Most of the lag is probably from the irradiation/hallucination pulses. It should be pretty trivial to buffer them until the next tick or something like that.

2023-01-29 00:36 UTC, Pickle-Coding commented
> Most of the lag is probably from the irradiation/hallucination pulses. It should be pretty trivial to buffer them until the next tick or something like that.

Radiation pulses check tick. Not sure about hallucination pulses, but I could probably merge hallucination pulses with radiation pulses for processing in a different PR, as I imagine the hallucination pulses are a unique form of radiation.

2023-01-29 00:38 UTC, Pickle-Coding commented
> Can we do something about the kind of lag these set-ups cause before actually making it more attractive to set them up? Someone did a pill SM on Manuel last round and looking at it tanked the hell out of my response time.

Is there a case where someone could easily produce a bunch of atoms that are not items?

2023-02-02 00:27 UTC, LemonInTheDark requested changes
What are you imagining this to cover? also does this mean mobs double count

2023-02-02 00:27 UTC, LemonInTheDark commented on code/datums/components/supermatter_crystal.dm
> +			matter_increase += min(0.5 * consumed_object.max_integrity, 4000)
please max this lower

2023-02-02 00:33 UTC, Pickle-Coding commented
> What are you imagining this to cover? also does this mean mobs double count

Like crates, loose girders, vehicles, and other stuff. Are mobs a subtype of atom?

2023-02-02 00:38 UTC, LemonInTheDark commented
Anything that exists in the world is an atom

2023-02-02 00:38 UTC, Pickle-Coding commented on code/datums/components/supermatter_crystal.dm
> +		else
```suggestion
		else if(!isliving(consumed_object))
```

2023-02-02 00:38 UTC, Pickle-Coding commented on code/datums/components/supermatter_crystal.dm
> +			matter_increase += min(0.5 * consumed_object.max_integrity, 4000)
```suggestion
			matter_increase += min(0.5 * consumed_object.max_integrity, 1000)
```

2023-02-02 00:38 UTC, LemonInTheDark commented on code/datums/components/supermatter_crystal.dm
> +	if(!iseffect(consumed_object))
just do the check up here

2023-02-02 00:39 UTC, Pickle-Coding commented on code/datums/components/supermatter_crystal.dm
> +	if(!iseffect(consumed_object))
Oh.

2023-02-02 00:45 UTC, Pickle-Coding reviewed
lol

2023-02-02 00:45 UTC, Pickle-Coding commented on code/datums/components/supermatter_crystal.dm
> +			matter_increase += min(0.5 * consumed_object.max_integrity, 1000)
```suggestion
	if(!iseffect(consumed_object) && !isliving(consumed_object))
		if(isitem(consumed_object))
			var/obj/item/consumed_item = consumed_object
			object_size = consumed_item.w_class
			matter_increase += 70 * object_size
		else
			matter_increase += min(0.5 * consumed_object.max_integrity, 1000)
```

2023-02-02 08:41 UTC, LemonInTheDark commented
If this dusts ghosts I will bully you so hard

2023-02-02 08:42 UTC, merged