Seed Extractor stores the extracted seeds in the machine rather than spewing them out on the turf
tgstation/tgstation pull request #73128
Opened 2023-02-01 09:04 UTC by SyncIt21

## About The Pull Request
Say you attack the seed extractor with a pumpkin, and it extracts 4 pumpkin seeds. Rather than dumping those 4 seed packets on the turf it will now store them in the machine.

## Why It's Good For The Game
Saves you the manual work of picking up those packets from the turf and again putting them in the machine. Keeps the turf clean.

## Changelog
:cl:
qol: seed extractor will keep the extracted seeds in the machine and saves you the work of manually picking them up from the ground & again storing them in the machine
/:cl:

2023-02-01 09:22 UTC, SyncIt21 commented
> I don't think I like this, if I want a seed from a plant I don't want to have to extract it, open up the UI, then search through hundreds of seeds to find the exact sample I just took. I just want to pick it up off the top.

I mean there is a search bar in the UI to find what your looking for. 
Maybe I make it optional then say if I right click on the machine with the plant then I store it in the machine but if I left click then it does the normal stuff?

2023-02-01 09:24 UTC, SyncIt21 commented
> That sounds preferable, just make sure it comes with screentips and the like

I'll do that then

2023-02-01 22:16 UTC, MrMelbert requested changes

2023-02-02 04:14 UTC, SyncIt21 commented on code/modules/hydroponics/seed_extractor.dm
> +
Ohh right I forgot to remove this after i learnt about  click params. Thanks for pointing it out

2023-02-02 04:15 UTC, SyncIt21 commented on code/modules/hydroponics/seed_extractor.dm
> +				add_seed(to_store, null)
It's an added bonus that is picks up all seeds.  But yeah I'll try to filter them out using seedify

2023-02-02 07:17 UTC, SyncIt21 commented
There is a bug here. max_seeds doesn't limit the number of seeds you can store here. It only checks against how many seeds you are trying to insert but it doesn't check against how many seeds are actually in the machine. I'm gonna fix this

2023-02-02 07:30 UTC, SyncIt21 commented
Done

2023-02-06 04:25 UTC, SyncIt21 commented
I have no pending work on this. Ready for Merge/Review

2023-02-09 22:35 UTC, ExcessiveUseOfCobblestone commented
why WOULDNT you want this as baseline? If its that pressing you could just put the first seed into your hand and the rest go thru UI.

If we are talking clicks having to manually put all seeds into the extractor is more clicks than what it would take to pull out those if they would go into the machine, not to mention the location of where you clicking doesnt change on the UI unlike ground > extractor for storage.

2023-02-10 04:09 UTC, SyncIt21 commented
> why WOULDNT you want this as baseline? If its that pressing you could just put the first seed into your hand and the rest go thru UI.
> 
> If we are talking clicks having to manually put all seeds into the extractor is more clicks than what it would take to pull out those if they would go into the machine, not to mention the location of where you clicking doesnt change on the UI unlike ground > extractor for storage.
> 
> Maybe im blessed by RNG but I always get multiple seeds, which is usually a pain to put them in to clean up the area (I usually just resort to portable for this reason anyways).

We can make both sides happy.  Right clicking on the extractor will put all seeds into the machine and wont cause a mess and left click is for everyone else who doesn't care about the mess.
Making it a baseline would have caused others to complain so might as well take this route

2023-02-17 09:04 UTC, SyncIt21 commented
Merge/Review anyone? I have no pending work on this

2023-02-21 06:08 UTC, MrMelbert requested changes
Two small things, otherwise looks good

2023-02-21 08:09 UTC, SyncIt21 commented
Done

2023-02-23 00:09 UTC, merged