Refactors species mutanthands into human component
tgstation/tgstation pull request #73286
Opened 2023-02-07 04:31 UTC by MrMelbert

## About The Pull Request

Mutanthands is now a component, which handles ensuring the mob always has their mutant hands equipped to their right slots at all times. 

Alternative to #73282 
Fixes #73034 

## Why It's Good For The Game

Cleaner and more consistent code, Ensures mutant hand mobs always have their correct hands. 

## Changelog

:cl: Melbert
fix: It should be way harder to lose your special hands as a zombie or shattered risen ghoul.
refactor: Refactored mutanthands for zombies and shattered risen.
/:cl:

2023-02-11 22:59 UTC, ChungusGamer666 commented
it's good that this is a component, but shouldn't mutant hands be handled by bodyparts instead of species?

2023-02-11 23:21 UTC, ChungusGamer666 commented
meh i guess i'll do yet another limb improvement pr once this is merged to avoid family guy funny moments

2023-02-13 22:43 UTC, san7890 requested changes

2023-02-13 22:43 UTC, san7890 commented on code/datums/components/mutant_hands.dm
> +			message_admins("[hand_slot] can be dropped safely")
Are these `message_admins` stuff for debugging, or do you actually want to pass this feedback along to admins? seems quite vague to be useful in production imo, would need to include more context to be useful.

2023-02-13 22:43 UTC, san7890 commented on code/datums/components/mutant_hands.dm
> + * (Technically speaking, the component doesn't require you use this type. B.ut it's here for posterity)
```suggestion
 * (Technically speaking, the component doesn't require you use this type. But it's here for posterity)
```

2023-02-13 22:43 UTC, san7890 commented on code/modules/mob/living/carbon/examine.dm
clean up this single-letter var while in the area :)

2023-02-13 22:43 UTC, san7890 commented on code/modules/mob/living/carbon/human/examine.dm
ditto single letter var

2023-02-13 22:43 UTC, san7890 commented on code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
> +		. += "It has [I.get_examine_string(user)] in its [get_held_index_name(get_held_index_of_item(I))]."
ditto single letter var

2023-02-15 00:24 UTC, merged