Fix a potential runtime in uplink implants
tgstation/tgstation pull request #73345
Opened 2023-02-10 06:52 UTC by Absolucy

## About The Pull Request

Literally just https://github.com/tgstation/tgstation/pull/63283, except I actually filled out the PR outline 2 years later.

## Why It's Good For The Game

if anyone ever implements something like my good ol' infiltration gamemode (where an outfit gave ppl uplink implants), they won't run into this error.

also less errors > more errors.

## Changelog

:cl:
fix: Fixed a potential runtime error with uplink implants. The chances of said error happen are basically zero during normal gameplay, but 0% theoretical errors are better than 0.0001% theoretical errors.
/:cl:

2023-02-10 16:45 UTC, ZephyrTFA commented on code/datums/components/uplink.dm
> +	owner = user ? user.key : target?.key
```suggestion
	owner = user?.key || target?.key || CRASH("Uplink created without an owner!")
```

2023-02-11 14:52 UTC, ZephyrTFA commented on code/datums/components/uplink.dm
> +	owner = user?.key || target?.key || CRASH("Uplink created without an owner!")
```suggestion
	owner = user?.key || target?.key
	if(!owner)
		CRASH("Uplink created without an owner!")
```
Turns out BYOND doesn't like C# exception throwing syntax

2023-02-12 22:08 UTC, Mothblocks commented
lol you didnt even need to fill out the pr template for that pr

2023-02-12 22:09 UTC, Mothblocks requested changes
what i'd like to see more than a non-player facing changelog that im gonna remove and a fluff why is this good for the game is what the runtime actually is

2023-02-12 22:09 UTC, Mothblocks commented on code/datums/components/uplink.dm
>  	if(owner && !purchase_log)
```suggestion
	if(!purchase_log)
```

2023-02-13 02:41 UTC, Absolucy commented
@Mothblocks I don't have the runtime on hand (this is something I fixed a long time ago on a fork), but I can explain how it would occur.

Example outfit that would trigger the runtime:
```
/datum/outfit/example_outfit
	implants = list(/obj/item/implant/uplink)
```

Outfit implant handling code: https://github.com/tgstation/tgstation/blob/master/code/datums/outfit.dm#L254C15-L257
```
		if(implants)
			for(var/implant_type in implants)
				var/obj/item/implant/I = SSwardrobe.provide_type(implant_type, H)
				I.implant(H, null, TRUE)
```

This would result in `user` (the second argument) being null, which seems to be correct behavior (as it is the game giving the user the implant, not any sort of mob)
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/implants/implant.dm#L104
In this case, the arguments of the call to `implant` would be passed to the signal handler, and well, `arguments[2]` would be null.

There are obvious alternative solutions to this problem, but they would break the assumption in code that the `user` argument would always be the one who actually implanted the target:

 1. Replacing `I.implant(H, null, TRUE)` with `I.implant(H, H, TRUE)`
 2. Something along the lines of this in `/obj/item/implant/proc/implant` (which would be more 'universal', but imo the code is butt-ugly):
```
var/list/implant_args = args.Copy()
if (LAZYLEN(implant_args) > 1)
	if (!implant_args[1])
		CRASH("Implant created without a target")
	implant_args[2] = implant_args[2] || implant_args[1]
```

I hope this explanation suffices.

2023-02-13 03:28 UTC, Absolucy commented
Upon further testing, this doesn't runtime anymore.
I'm kind of confused as to why, but whatever, no runtime = no runtime.

2023-02-13 03:28 UTC, closed without merging