Tramstation updates 02/20
tgstation/tgstation pull request #73576
Opened 2023-02-21 04:47 UTC by lessthnthree

## About The Pull Request
- Updates various sprites to 3/4 perspective (tram indicator/button, elevator indicator/panel/button)
- Moves button lighting to base typepath
- Renames player facing objects consistently to 'elevator' instead of a mix of 'elevator' and 'lift'
- NTOS theme on elevator panel
- Reduced light power/range of tram indicator sign
- Removed odd wall left in cargo lower floor
- Science elevator panel no longer sitting on a table
- Science keycard auth now directional
- Updates to various mapping helpers
<details>
<summary>Pictures</summary>
  
![image](https://user-images.githubusercontent.com/83487515/220248178-f7d2812a-2025-447b-8600-1c96a6ed712d.png)
![image](https://user-images.githubusercontent.com/83487515/220248215-43005369-7fa1-4df5-af52-50d759ed3679.png)
![image](https://user-images.githubusercontent.com/83487515/220248366-c348580e-a1f1-440e-b187-ea48b653011d.png)

</details>
## Why It's Good For The Game
3/4 sprites for when wallening happens. Minor map fixes. Naming consistency.

## Changelog
:cl: LT3
imageadd: New tram and elevator sprites
code: lighting capability for all buttons
spellcheck: All elevator components are now 'elevator'
code: Reduced brightness on tram platform signs
fix: Fixed odd wall in cargo department
fix: Science elevator panel not laying on a table anymore
fix: Science keycard auth can only be done from RD office
code: More Tramstation mapping helpers
/:cl:

2023-02-26 11:19 UTC, MMMiracles approved these changes

2023-03-01 07:06 UTC, san7890 requested changes

2023-03-01 07:06 UTC, san7890 commented on code/game/machinery/buttons.dm
> +	var/light_mask = null
Move this to be with the other new args.

2023-03-03 04:02 UTC, LemonInTheDark commented on code/modules/industrial_lift/tram/tram_machinery.dm
>  	light_color = LIGHT_COLOR_DARK_BLUE
why override range and color here aren't they already inherited?

2023-03-03 11:48 UTC, LemonInTheDark commented on code/modules/industrial_lift/tram/tram_machinery.dm
> -	light_power = 1
why?

2023-03-03 23:45 UTC, LemonInTheDark requested changes

2023-03-03 23:45 UTC, LemonInTheDark commented on code/game/machinery/buttons.dm
> +		. += emissive_appearance(icon, light_mask, src, alpha = alpha)
alpha won't do anything but it should so just leave it for now

2023-03-03 23:45 UTC, LemonInTheDark commented on code/modules/industrial_lift/elevator_panel.dm
> +MAPPING_DIRECTIONAL_HELPERS(/obj/machinery/elevator_control_panel, 31)
why 31?

2023-03-05 22:40 UTC, Maurukas approved these changes
Maps are good.

2023-03-07 22:36 UTC, merged