Resolves mutant species keeping old organs they shouldn't have
tgstation/tgstation pull request #73728
Opened 2023-03-01 19:07 UTC by ZephyrTFA

## About The Pull Request

regenerate organs never removed invalid organs when regenerating

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/73640

## Changelog

:cl:
fix: Plasmamen don't have hearts, again
/:cl:

2023-03-02 10:19 UTC, ZephyrTFA commented
> Can this get a test?

done

2023-03-03 02:19 UTC, ATH1909 commented
is this gonna cause weirdness for people who change species while they have, say, upgraded organs from robotics? a toolset implant? mutant organs from that one genetics machine?

2023-03-09 00:20 UTC, san7890 requested changes
also your CI is failing don't know if you noticed

2023-03-09 00:20 UTC, san7890 commented on code/modules/unit_tests/mutant_organs.dm
> +		)
```suggestion
	)
```

2023-03-09 00:20 UTC, san7890 commented on code/modules/unit_tests/mutant_organs.dm
> +			if(!actual_organ)
could we use `isnull()` here (and elsewhere) instead?

2023-03-09 00:26 UTC, ZephyrTFA commented on code/modules/unit_tests/mutant_organs.dm
> +			if(!actual_organ)
```suggestion
			if(isnull(actual_organ))
```

2023-03-09 00:26 UTC, ZephyrTFA commented on code/modules/unit_tests/mutant_organs.dm
> +				if(!expected_type)
```suggestion
				if(isnull(expected_type))
```

2023-03-09 00:26 UTC, ZephyrTFA commented on code/modules/unit_tests/mutant_organs.dm
> +				if(expected_type)
```suggestion
				if(!isnull(expected_type))
```

2023-03-09 07:19 UTC, san7890 commented
![image](https://user-images.githubusercontent.com/34697715/223948931-0021776c-9d09-4a33-a7c0-fab2a92400cc.png)

```txt
 [00:49:41] Runtime in _external_organs.dm,357: bad color
    proc name: color image (/datum/bodypart_overlay/mutant/pod_hair/color_image)
    src: /datum/bodypart_overlay/mutant... (/datum/bodypart_overlay/mutant/pod_hair)
    call stack:
    /datum/bodypart_overlay/mutant... (/datum/bodypart_overlay/mutant/pod_hair): color image(, -6, the robotic head (/obj/item/bodypart/head/robot))
    /datum/bodypart_overlay/mutant... (/datum/bodypart_overlay/mutant/pod_hair): get overlay(-6, the robotic head (/obj/item/bodypart/head/robot))
    the robotic head (/obj/item/bodypart/head/robot): get limb icon(null, null)
    the robotic head (/obj/item/bodypart/head/robot): get limb icon(null, null)
    John Doe (/mob/living/carbon/human/consistent): update body parts(null)
    the podperson hair (/obj/item/organ/external/pod_hair): Insert(John Doe (/mob/living/carbon/human/consistent), 1, 0)
    Podperson (/datum/species/pod): regenerate organs(John Doe (/mob/living/carbon/human/consistent), Plasmaman (/datum/species/plasmaman), 1, null, 0)
    Podperson (/datum/species/pod): on species gain(John Doe (/mob/living/carbon/human/consistent), Plasmaman (/datum/species/plasmaman), 0)
    John Doe (/mob/living/carbon/human/consistent): set species(/datum/species/pod (/datum/species/pod), 1, 0)
    John Doe (/mob/living/carbon/human/consistent): set species(/datum/species/pod (/datum/species/pod), 1, 0)
    /datum/unit_test/mutant_organs (/datum/unit_test/mutant_organs): Run()
    RunUnitTest(/datum/unit_test/mutant_organs (/datum/unit_test/mutant_organs), /list (/list))
    RunUnitTests()
    /datum/callback (/datum/callback): InvokeAsync()
```

i wonder why this is fucking us over

2023-03-09 19:36 UTC, ZephyrTFA commented
merging master and hoping that resolves it

2023-03-17 23:58 UTC, Kapu1178 commented on code/modules/unit_tests/mutant_organs.dm
> +	species -= /datum/species/dullahan // the head is detached from the body
```suggestion
	var/list/ignore = list(
		/datum/species/dullahan,
	)
	var/list/species = subtypesof(/datum/species) - ignore
```

2023-03-18 01:43 UTC, merged