Calomel Rework
tgstation/tgstation pull request #73762
Opened 2023-03-03 12:28 UTC by Comxy

## About The Pull Request
This transforms the Calomel now into a better version called Ammoniated Mercury and brings the old Calomel back. Calomel purges all chemicals again and Ammoniated Mercury purges toxins. Calomel deals toxin damage until you have less than 100 health in which case it starts doing to opposite. Ammoniated Mercury heals toxin damage if you do not have enough brute or fire damage.

## Why It's Good For The Game
I always used to use Calomel back in the day to get rid of all chemicals. Multiver does the same but has very weird conditions, so now I split the old and new Calomel into two chemicals for both uses to become available. I have never seen anyone use Calomel so now it can be used to fix overdoses again.

## Changelog

:cl:
add: Adds Ammoniated Mercury, a chemical to the game.
qol: Calomel now purges all chemicals again, and now Ammoniated Mercury only purges toxins.
/:cl:

2023-03-03 21:12 UTC, Iamgoofball commented
👍 i always enjoyed goon calomel because it was a fun chemical that had an obvious effect and an obvious side effect

2023-03-03 22:59 UTC, ATH1909 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	description = "Quickly purges the body of all chemicals except itself. The more health a person has, the more toxin damage it will deal"
needs a period and needs to mention that it can heal the tox damage of people who are at low enough health

2023-03-03 23:01 UTC, ATH1909 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			affected_mob.reagents.remove_reagent(target_reagent.type, 1 * REM * delta_time)
should mention this in the description

2023-03-03 23:01 UTC, ATH1909 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	description = "Quickly purges the body of toxic chemicals. Heals toxin damage when in a good condition. When hurt with brute or fire damage, it can deal a great amount of toxin damage."
should mention that "good condition" only refers to brute and burn damage

2023-03-04 18:31 UTC, JohnFulpWillard reviewed
Paramedics currently spawn with Calomel and Formaldehyde, they don't have a health analyzer and I don't know if we should expect them to always have one, so this makes Calomel pretty useless for them as they cannot estimate what action they should do based off of MedHUD.

2023-03-05 00:54 UTC, Iamgoofball commented
@JohnFulpWillard could just hand them the renamed-new-calomel then instead

2023-03-11 04:44 UTC, san7890 requested changes

2023-03-11 04:44 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	. = TRUE
```suggestion
	return TRUE
```

same exact meaning

2023-03-11 04:44 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	. = TRUE
```suggestion
	return TRUE
```

ditto

2023-03-11 04:44 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	ph = 1
ammonia is a base? why does it have an acidic pH? if it's for some in-game mechanical reason that's fine but i'd rather not have to suspend reality like this if we can help it

2023-03-11 04:44 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	. = TRUE
```suggestion
	return TRUE
```

ditto

2023-03-11 04:44 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	. = TRUE
```suggestion
	return TRUE
```

2023-03-13 19:00 UTC, san7890 requested changes
last stuff

2023-03-13 19:00 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			affected_mob.reagents.remove_reagent(target_reagent.type, 3 * REM * delta_time)
```suggestion
	for(var/datum/reagent/target_reagent in affected_mob.reagents.reagent_list)
		if(istype(target_reagent, /datum/reagent/medicine/calomel))
			continue
		affected_mob.reagents.remove_reagent(target_reagent.type, 3 * REM * delta_time)
```

early continue works better here imo

2023-03-14 01:31 UTC, san7890 commented
might want to update the wiki

2023-03-14 01:31 UTC, merged