Updates the dynamic config's midround options to add in new additions
tgstation/tgstation pull request #73784
Opened 2023-03-04 22:12 UTC by CRITAWAKETS

## About The Pull Request

This PR updates the dynamic.json file to add in entries for midround rulesets which got added later in the code but never added to the config. Also, gives them the _proper_ ascii art in the code, which aids in navigation.

## Why It's Good For The Game

No need for server hosts to scratch their heads at why some dynamic rulesets just aren't present in the configuration for some reason.

## Changelog
:cl:
config: All dynamic midround rulesets are now properly accounted for in the dynamic.json config.
/:cl:

2023-03-04 22:17 UTC, CRITAWAKETS commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +//////////////////////////////////////////////
i love em :(

2023-03-04 23:46 UTC, Vect0r2 commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +//////////////////////////////////////////////
I like them, it helps me, as a new coder find shit, and also looks nice.

2023-03-05 00:48 UTC, MrStonedOne requested changes
replacing autodoc (`///`) comments with header comments is liking breaking autodoc for these datums.

autodoc is the system for grabbing comments above things and showing them in vscode when you hover over a symbol that uses that thing. (https://codedocs.tgstation13.org/)

2023-03-05 03:08 UTC, Mothblocks requested changes

2023-03-05 03:08 UTC, Mothblocks commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +//////////////////////////////////////////////
Do not add these. They are banned because they are hideous and break auto-docs.

2023-03-05 03:08 UTC, Mothblocks commented on config/dynamic.json
> +		}
You didn't add commas. This doesn't work.

2023-03-05 03:08 UTC, Mothblocks commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +//////////////////////////////////////////////
I am the one that asked for all these to be removed from the newest rulesets.

2023-03-12 22:05 UTC, CRITAWAKETS commented
hi i got super sick and forgot about this PR for a bit
things are now in the autodoc format and the config actually works now

2023-03-12 23:01 UTC, merged