Removes bad `nodamage` var from projectiles, fixes Juggernaut / Rust Walker projectiles doing zero damage
tgstation/tgstation pull request #73806
Opened 2023-03-06 06:03 UTC by MrMelbert

## About The Pull Request

- Juggernaut and Rust Walker projectiles were subtyped off of magic, which is `nodamage`.

- The juggernaut actually had a copy+paste error with their type `on_hit` which caused none of their special effects on hit ("relative patching catches this")

- Then I realized projectiles have this var `nodamage` which is, for all intents and purposes, just `damage > 0`. it's not checked for pacifism, it's just that. This is dumb. So very dumb, so I removed it. 
    - There are, however, a few situations which used it in a unique way, such as the blast wave cannon. This is why I replaced it with a proc, `is_hostile_projectile`, for certain situations to actually find out if the projectile is damaging. Projectiles can override this on a per type basis by default, damaging projectiles = hostile. 
    - This has a chance to break some things, but I ... kinda doubt it will. 

Fixes #73756

## Why It's Good For The Game

Projectiles that act as they should, less dumb vars

## Changelog

:cl: Melbert
fix: Fixes Juggernaut / Rust Walker projectiles doing zero damage
fix: Fixes Juggernaut projectiles not doing bonus damage to nearby structures
code: Removed projectile nodamage var, replaces it with just checking for damage 
/:cl:

2023-03-06 06:37 UTC, VladinXXV commented
>  ...basis by buy default, 

...basis but by default,

2023-03-06 20:51 UTC, timothymtorres commented
Does this fix #49885

2023-03-07 04:16 UTC, san7890 commented on code/game/objects/items/robot/items/tools.dm
> +	for(var/obj/projectile/projectil as anything in tracked)
man this var name sucks

2023-03-07 04:19 UTC, san7890 requested changes
nit because you're probably the first to touch this code since whenever these were first implemented or something

2023-03-07 04:19 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/herald.dm
> +	name ="golden bolt"
```suggestion
	name = "golden bolt"
```

2023-03-11 00:51 UTC, merged