Adds a new felinid mutation
tgstation/tgstation pull request #73856
Opened 2023-03-08 23:54 UTC by Boopideedoo

## About The Pull Request
This pr adds a new mutation for felinids to have fun with

### Mapping March

Ckey to recieve rewards: N/A

## Why It's Good For The Game
This adds something to make up for the lack of mutations the feline species has compared to every other species. The first reason its good is it makes felinds have something that the others dont have for the first time.
Second reason, For too long have Felinids not had anything for fun but now they will atleast have something even if its not as great as hulk.

## Changelog

:cl:
add:uwuspeech mutation for felinids
/:cl:

2023-03-08 23:57 UTC, ZephyrTFA requested changes

2023-03-08 23:57 UTC, ZephyrTFA commented on .vscode/launch.json
> +
what happened here?

2023-03-08 23:57 UTC, ZephyrTFA commented on code/datums/mutations/speech.dm
> +	if(..())
Make these
```
. = ..()
if(.)
  return .
```

2023-03-08 23:57 UTC, closed without merging

2023-03-08 23:58 UTC, Boopideedoo commented
> ![image](https://user-images.githubusercontent.com/34697715/223879861-b00e47b4-71e2-4738-8499-620c4c34aee3.png)
> 
> via https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#banned-content
> 
> I do not believe you have received any approval prior to opening this PR. I will be closing it until someone else is okay with it (specifically @optimumtact)

I didnt know it was supposed to be approved my bad

2023-03-08 23:59 UTC, JohnFulpWillard commented
I don't think genetic mutations fall under that category, however this was attempted in https://github.com/tgstation/tgstation/pull/59802 and was denied

2023-03-09 00:00 UTC, san7890 commented
>Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

Adding a felinid-only quirk _definitely_ falls under this category.

2023-03-09 00:15 UTC, ZephyrTFA commented
I'm gonna go ahead and just give a hard no on this.

2023-03-09 05:35 UTC, Sealed101 commented
local coder asks in coderbus whether uwuspeech would be a good idea, gets several notices including from oranges that it would definitely not, PRs it anyway

real human bean