Adds the Smoking Room icebox surface ruin
tgstation/tgstation pull request #73876
Opened 2023-03-09 21:48 UTC by Rhials

## About The Pull Request

My contribution to the March Into Mapping/Mapness event -- The forlorn homestead of mister Charles Morlbaro, a high-brow individual with a taste for cigarettes. This ruin spawns on the surface level of Icebox.

![image](https://user-images.githubusercontent.com/28870487/224414415-6bacf208-9a39-43e4-8f79-60d142049a17.png)

A local of the ice planet, Morlbaro lived a peaceful life at home, until an _incident_ compromised one of his windows. Fearing the cold and unable to keep anything larger than a cigarette lit, he sequestered himself in his private smoking room, and hasn't been seen since.

...

Oh, right, the loot. That's the most important part for some of you guys.

![image](https://user-images.githubusercontent.com/28870487/224161740-cc25f84e-3aaf-4f78-9ea9-06c79e376cdb.png)

Where there's smoke, there's fire, and where there's cigarettes, there's lighters. Mister Morlbaro collected novelty lighters, which have to be worth something to someone, right? You might be able to find some if you dig around in his belongings. Just try not to disturb him if you choose to enter his smoking room.

### Mapping March

Ckey to recieve rewards: theduffelbag

## Why It's Good For The Game

Ruin variety is nice. This one doesn't have any particularly spectacular loot, but it's a surface ruin.

Bro space ruins are sooooo 2020 bro, it's all about icebox ruins now bro.

## Changelog

:cl: Rhials
add: Adds the Smoking Room icebox ruin, found on the station level!
/:cl:

2023-03-09 22:23 UTC, VladinXXV commented
can i convince you to throw the slime zippo in there too? i think it's pretty neat. good ruin overall.

2023-03-09 22:46 UTC, MrMelbert requested changes
You do not appear to have the githooks setup, as your map does not have the header
`//MAP CONVERTED BY dmm2tgm.py THIS HEADER COMMENT PREVENTS RECONVERSION, DO NOT REMOVE` (that is to say it wasn't converted to TGM format)

2023-03-09 23:17 UTC, Fikou commented on code/game/objects/items/cigs_lighters.dm
> +	..()
you need to include return value

2023-03-10 03:06 UTC, ArcaneMusic requested changes

2023-03-10 03:06 UTC, ArcaneMusic commented on code/game/objects/items/cigs_lighters.dm
> +	custom_price = PAYCHECK_CREW * 6
This doesn't give it a sale value, you'll need to make a cargo export datum for it to be worth that much in cargo.
Check the `cargo/exports` folder for examples.

2023-03-13 17:07 UTC, Loafin34 commented
If only I knew modsuit code, So I could make a lighter module... alas.

2023-03-14 01:21 UTC, Maurukas requested changes
The ruin itself looks good, however you're saving in .dmm format. You need to convert the map to tgm format. You can do this by setting up the git hooks, or by opening the map in StrongDMM2 and going to File -> Preferences and changing the Save Format to TGM (then saving).

2023-03-15 01:36 UTC, Maurukas approved these changes
Maps look good. However, the smoke effect on the corpse is runtiming for me.

[18:30:14] Runtime in remains.dm,42: Cannot read /datum/reagent/consumable/nutr... (/datum/reagent/consumable/nutraslop).name
  proc name: release smoke (/obj/effect/decal/remains/human/smokey/proc/release_smoke)
  usr: Maurukas/(Vire-Sartri)
  usr.loc: (Smoking Room (226,211,4))
  src: the remains (/obj/effect/decal/remains/human/smokey)
  src.loc: the carpet (226,211,4) (/turf/open/floor/carpet/blue)

I'm not immediately sure why it's doing this, I would bother a coder.

2023-03-15 05:01 UTC, merged

2023-03-17 05:05 UTC, LemonInTheDark commented on code/game/objects/effects/decals/remains.dm
> +	visible_message(span_warning("[smoke_releaser] disturbs the [src], which releases a huge cloud of gas!"))
worth noting you coulda used initial(that_shit_that_killed_sadam.name), it's how you access non list vars off typepaths