Pizza Party Ruin Revamp
tgstation/tgstation pull request #73924
Opened 2023-03-11 22:33 UTC by MMMiracles

## About The Pull Request
Revamps the original pizza party ruin into something with more detail and variety, as the original is fairly bland and boring by modern mapping standards.

### Mapping March

Ckey to recieve rewards: lol

## Why It's Good For The Game
I originally made this ruins years ago and our mapping event seems like a better time than any to give it a fresh coat of paint and some other goodies to show our new mappers some fun ideas.

## Changelog

:cl: MMMiracles
balance: Little Timmy's lavaland pizza party has gotten an overhaul to be a bit more interesting.
/:cl:

![image](https://user-images.githubusercontent.com/9276171/224514355-68f4a2f6-8b4d-44cd-8ddb-586b1c1eedcd.png)
The turfs use VV'd gas mixes atm since I had this dumb idea while on break and wanted to whip it up real quick. I'll make the turfs a proper subtype once I'm home properly along with some final touches.

2023-03-11 22:47 UTC, NamelessFairy commented
Just a warning, that cake ingredients spawner is coded to only spawn items during the birthday station trait, I probably should have named it more clearly.

2023-03-14 02:39 UTC, wesoda25 commented
Looks nice but important question: is the rainbow crown still there?

2023-03-18 20:56 UTC, Maurukas requested changes
Something in the unit tests really isn't liking this turf you've created. It appears to be trying to create a broken state for it, but failing as part of the testing. 
It looks like it's having issues with `/turf/open/floor/grass/broken_states()` but I'm having a hard time telling as it's wrapped in so many macros.

2023-04-04 00:33 UTC, Maurukas approved these changes

2023-04-04 00:33 UTC, merged