March Mapping Madness - New space ruin
tgstation/tgstation pull request #73978
Opened 2023-03-13 23:37 UTC by Astrogem2

I have made a new space ruin which is based off of the game Prey, cause mimics are cool, and I think some variety in space ruins would be swell

## About The Pull Request

This pull request is about a new ruin I have made, which I have taken inspiration on by the hit 2017 game Prey, which I enjoy.

### Mapping March

Ckey to receive rewards: Astrogem2

## Why It's Good For The Game

We don't have that many Ruins out in space, and some new ones would be nice to see.

## Changelog

:cl:

add: New space ruin.

/:cl:

2023-03-14 00:02 UTC, VladinXXV commented
Can you include pictures of the ruin in the PR body please? You might also want to expand your changelog entry.

2023-03-14 00:03 UTC, Astrogem2 commented
ight

2023-03-14 01:14 UTC, san7890 commented
that asteroid is way too big for so much regular rock, trim down the overall map size or just splinter that big asteroid into a bunch of smaller ones

2023-03-14 01:30 UTC, Astrogem2 commented
got it

2023-03-14 01:53 UTC, san7890 commented
be sure to edit your PR body with the latest version of the map to ensure that newer people who come in and see this PR don't give feedback on an outdated version of the map, thanks

2023-03-14 02:37 UTC, wesoda25 commented
Love the little simple ones like this 👍

2023-03-14 20:57 UTC, Addust commented
plating under the windows
hivelords, holy shit rare

2023-03-14 20:58 UTC, Addust commented
also it needs a ruin config thingymajig (check other ruin PRs!)

2023-03-14 21:38 UTC, Valorium-RB commented
The foam force crossbow should be renamed to the Huntress Boltcaster, to complete the reference.

2023-03-14 21:54 UTC, Astrogem2 commented
damn i’m gaming right now, i’ll do these after

2023-03-15 00:31 UTC, Astrogem2 commented
ok i've done that now i'm pretty sure.

2023-03-15 00:32 UTC, san7890 commented
they aren't in your PR. push your commit to remote, or commit your staged changes and then push to remote.

2023-03-15 00:34 UTC, Astrogem2 commented
uhhhhh, ill try to do that i guess.

2023-03-15 00:34 UTC, Astrogem2 commented
wait i think i made another pr for that by mistake

2023-03-15 00:48 UTC, Astrogem2 commented
ok this time its sure to work im pretty sure, i hope

2023-03-15 01:13 UTC, Astrogem2 commented
oh christ

2023-03-15 01:17 UTC, Astrogem2 commented
this might fix the one linter error.

2023-03-15 02:16 UTC, Astrogem2 commented
ok im praying that this works now.

2023-03-18 07:37 UTC, san7890 commented
fix your conflicts, and also add a `/obj/effect/baseturf_helper/asteroid/airless` into the ruin's area (maybe making a new area for it as well, it's not that hard) such that if anyone decides to use a grenade, it'll only scrape away the walls of the ruin, and not punch a hole into space.

2023-03-21 00:32 UTC, Maurukas requested changes
Looks good. Please fix the file name.

If you'd like, you can give the terminal custom text. Look at `code/modules/mapfluff/ruins/spaceruin_code/dangerous_research.dm` and `TheDerelict.dm` for examples.

2023-03-21 00:32 UTC, Maurukas commented on code/datums/ruins/space.dm
> +	suffix = "prey_pod"
```suggestion
	suffix = "prey_pod.dmm"
```

This needs to be the filename

2023-03-22 01:43 UTC, Maurukas commented on config/spaceruinblacklist.txt
> +#_maps/RandomRuins/SpaceRuins/dangerous_research.dm
```suggestion
#_maps/RandomRuins/SpaceRuins/dangerous_research.dmm
```

2023-03-22 01:44 UTC, Maurukas approved these changes

2023-03-22 02:04 UTC, merged