Atmosia Asteroid Space Ruin
tgstation/tgstation pull request #74164
Opened 2023-03-22 00:14 UTC by ZAMODA

## About The Pull Request
This PR adds a new space ruin, the atmos asteroid!
It contains a small atmos setup with some engineering tools, as well as some RPD upgrades.
![image](https://user-images.githubusercontent.com/36141254/226769720-9a071dd4-112f-4cce-a495-e92598d60047.png)

### Mapping March

Ckey to receive rewards: Z Man Wit Z Plan

## Why It's Good For The Game
Space deserves some more ruins.

## Changelog

:cl:
add: Added a new space ruin, the Atmos Asteroid!
/:cl:

2023-03-22 00:18 UTC, Fikou commented on code/datums/ruins/space.dm
> +	name = "Atmos Astroid"
it's "Asteroid"

2023-03-22 00:18 UTC, Fikou commented on code/datums/ruins/space.dm
> +	description = "A dead atmos tech in a continuously presurizing ruin"
```suggestion
	description = "A dead atmos tech in a continuously pressurizing ruin."
```

2023-03-22 00:29 UTC, ZAMODA commented
Spelling should be fixed!

2023-03-22 01:12 UTC, san7890 commented
This must be added to the configuration, see https://github.com/tgstation/tgstation/blob/master/.github/guides/MAPS_AND_AWAY_MISSIONS.md#configuration

2023-03-22 01:35 UTC, ZAMODA commented
> This must be added to the configuration, see https://github.com/tgstation/tgstation/blob/master/.github/guides/MAPS_AND_AWAY_MISSIONS.md#configuration

Done

2023-03-23 08:34 UTC, ZAMODA commented
Since I got all the issues above fixed I'll wait for any more feedback and if I don't get anything I'll un-draft this PR and set it to open again.

2023-03-23 08:39 UTC, ZAMODA commented
Oh God why is GitHub being dumb

2023-03-23 20:07 UTC, ZAMODA commented
> Looks good now, but out of curiosity....
> 
> Since the lore of it is that they suffocated themselves, have you considered making it so that the interior of the ruin spawns highly pressurized / filled with CO2?

If i knew how to change the atmos of turfs/add gases directly then i could, but at the moment the best I could do was the broken CO2 miner

2023-03-23 20:09 UTC, ZAMODA commented
> > Looks good now, but out of curiosity....
> > Since the lore of it is that they suffocated themselves, have you considered making it so that the interior of the ruin spawns highly pressurized / filled with CO2?
> 
> If i knew how to change the atmos of turfs/add gases directly then i could, but at the moment the best I could do was the exposed CO2 miner

wait no i might have figured it out, give me a minute

2023-03-30 01:13 UTC, MMMiracles requested changes
I'm personally a bit iffy on the existence of every major gas miner sitting all in the same ruin since they aren't used that often in the first place due to balance concerns. If some weird meta pops up around the ruin this will probably need revisited but for now it probably wouldn't hurt to see what happens.

As for the ruin itself, mind adding something like a cyclelink_helper to that airlock so it can cycle and at least prevent large amounts of air leakage? 
![image](https://user-images.githubusercontent.com/9276171/228702226-494e3226-cf51-4ea0-9189-07f522cf724d.png)
'/obj/effect/mapping_helpers/airlock/cyclelink_helper' is the path for it, the arrows just need to face the airlock you want it to link to for proper cycling. Add that and it should be fine enough for a merge.

2023-03-30 02:02 UTC, ZAMODA commented
> As for the ruin itself, mind adding something like a cyclelink_helper to that airlock so it can cycle and at least prevent large amounts of air leakage?

Done! Hopefully that works!

2023-03-30 02:51 UTC, merged