Access Keys list and destroy proc
tgstation/tgstation pull request #74181
Opened 2023-03-22 21:17 UTC by lessthnthree

## About The Pull Request

- Puts recently added access key rings into the janitor devices list
- Access key rings unregister their department signal when destroyed

## Why It's Good For The Game
Management of access key rings.

## Changelog

:cl: LT3
code: Access key rings added to list on creation
code: Access keys unregister signal when destroyed
/:cl:

2023-03-23 00:36 UTC, san7890 requested changes

2023-03-23 00:36 UTC, san7890 commented on code/game/objects/items/janitor_key.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-03-24 01:23 UTC, merged

2023-03-26 09:16 UTC, LemonInTheDark commented on code/game/objects/items/janitor_key.dm
> +	UnregisterSignal(SSdcs, COMSIG_ON_DEPARTMENT_ACCESS)
I missed this so I'm necroposting 

You shouldn't unregister on destroy, unless you're a /turf. Signals will clean themselves up just fine you don't need to do it manually. Leads to overly verbose and potentially confusing code

2023-03-26 15:55 UTC, lessthnthree commented
Okay, I'll take it out today.

On Sun, 26 Mar 2023, 02:17 LemonInTheDark, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In code/game/objects/items/janitor_key.dm
> <https://github.com/tgstation/tgstation/pull/74181#discussion_r1148513096>
> :
>
> > @@ -22,6 +22,12 @@
>  /obj/item/access_key/Initialize(mapload)
>  	. = ..()
>  	RegisterSignal(SSdcs, COMSIG_ON_DEPARTMENT_ACCESS, PROC_REF(department_access_given))
> +	GLOB.janitor_devices += src
> +
> +/obj/item/access_key/Destroy()
> +	UnregisterSignal(SSdcs, COMSIG_ON_DEPARTMENT_ACCESS)
>
> I missed this so I'm necroposting
>
> You shouldn't unregister on destroy, unless you're a /turf. Signals will
> clean themselves up just fine you don't need to do it manually. Leads to
> overly verbose and potentially confusing code
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/74181#pullrequestreview-1357979030>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT46WGZWPVEHAOE7KXEITQLW6ACQ3ANCNFSM6AAAAAAWELXKVI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>