March into Mapness: The Waystation
tgstation/tgstation pull request #74192
Opened 2023-03-23 09:38 UTC by Singul0

## About The Pull Request
Adds a waystation under attack by syndicate operatives! Will you be able to dislodge the syndicate off their recently claimed station and claim it as your own?

Big-big thanks to @Cheshify for answering all of my dumb questions.
### Mapping March

Ckey to receive rewards: humanlike

## Why It's Good For The Game
A new medium-sized space ruin inspired by caravan ambush and deep storage combining both of their main ideas. A space ruin bristling with heavily armed enemies that once cleared out and looted could serve as a base of operation for your space exploring or whiteship needs.

It has some tidbit of lore in papers and holodisk that ground the ruin and an explanation of why the syndicate chose to attack this far-off waystation.

Full map:
![2023 03 23-16 20 34](https://user-images.githubusercontent.com/127663818/227159889-c0897a91-c84f-4981-afe3-6ae3100d74c2.png)

List of remarkable loot:
1.WT-550 with 2 magazines
2. M1911
3. Mindshield Implant
4. Standard Firing Pins
5. Night Vision Goggles
7. Top Secret Nanotrasen Document
8. Bluespace Navigation Beacon

The ruin is heavily guarded by 5 syndicate stormtroopers and 4 turrets. I understand if the loot might be too much and I can adjust it as needed.

## Changelog

:cl:
add: Adds a new space ruin, A Waystation under attack!
/:cl:

2023-03-23 11:38 UTC, YuliceTheDruid commented
Looks neat! Would be cool if there was a set point to dock at it with the whiteship, a la the station, lavaland, and KS13, especially since it looks like it already has a cargo dock.

2023-03-23 11:41 UTC, Singul0 commented
> Looks neat! Would be cool if there was a set point to dock at it with the whiteship, a la the station, lavaland, and KS13, especially since it looks like it already has a cargo dock.

I really like that idea! It's what i'm trying to do with the bluespace navigation beacon. i'll try and actually add a docking port proper..

2023-03-23 12:11 UTC, Singul0 commented
Adding whiteship support is far more straight-forward than I thought it would be.

2023-03-23 15:59 UTC, Addust commented
let the syndicate ship fly and give it seperate power

2023-03-23 18:36 UTC, MrMelbert requested changes
- Don't really like standard firing pins - a few ruins recently have been putting "outback firing pins" in their guns which I like, and this works against that by allowing someone to easily replace them. 

- Building off of above, maybe the WT would benefit if it had an "outback firing pin" in it. Would be easily justifiable as it's an off the beaten path waystation - and also keep us from introducing more guns for space explorers to exploit in rounds without security's help

- Mindshield implant is an interesting one! It does entirely open up disguising as security without any hassle with is certainly a concern, but if it's suitably hard to get (I can't tell where it is from the file but I assume it's behind a bolted vault door) I think it can sneak past

2023-03-24 01:52 UTC, Singul0 commented
> * Don't really like standard firing pins - a few ruins recently have been putting "outback firing pins" in their guns which I like, and this works against that by allowing someone to easily replace them.
> 
>     * Building off of above, maybe the WT would benefit if it had an "outback firing pin" in it. Would be easily justifiable as it's an off the beaten path waystation - and also keep us from introducing more guns for space explorers to exploit in rounds without security's help
> 
>     * Mindshield implant is an interesting one! It does entirely open up disguising as security without any hassle with is certainly a concern, but if it's suitably hard to get (I can't tell where it is from the file but I assume it's behind a bolted vault door) I think it can sneak past


I changed the firing pin on the WT-550 and replaced the box on firing pins with 3 explorer firing pins. Also added 3 viscerator for good measure

2023-03-24 12:48 UTC, Singul0 commented
Here is what it looks like in-game:
![image](https://user-images.githubusercontent.com/127663818/227525353-58eff945-e43b-453c-964c-779572dc09c1.png)

2023-03-25 13:09 UTC, Addust commented
what the fuck is this wiring also 3 RTGs do NOT justify 2 SMES units, make a giantass solar array or some fancy method of powergen
<img width="347" alt="image" src="https://user-images.githubusercontent.com/80979251/227719119-5a8a498a-e381-463b-a8fc-512f1357a81f.png">

2023-03-25 16:42 UTC, nukularpower commented
Looks cool to me!  Just a random thought, not related to this specifically, but lots of these new ruins are adding syndi loot.  Thats cool and all but it would be really nice to get another ruin with an Ancient Protolathe board - I always go hunting for one for science, but currently the only way to get one without stealing from ghost roles is to find the one AI mothership that does not have a beacon. 

Just a thought, like I said!   looking forward to checking this place out

2023-03-26 02:55 UTC, Singul0 commented
![2023 03 26-09 39 29](https://user-images.githubusercontent.com/127663818/227752572-a4cbeede-e11d-40d8-87df-25833a0afe4c.png)

The final version of the map, i'm happy with the map as is and fixed all the mistakes that I found. will need a second pass by a maptainer though.

2023-03-26 21:23 UTC, Maurukas reviewed
Very nice looking. Good use of some of the mapping goodies, including the holodisk. 

It looks like this has been gone through pretty carefully. I could find only one minor issue.

<details>
<summary> This pressure tank is not hooked up to the adjacent pipe as it is on a different layer </summary>

![image](https://user-images.githubusercontent.com/66576896/227805132-5712761c-b694-4ff9-9cbc-9f7ab4252fea.png)
</details>

2023-03-30 00:07 UTC, Maurukas approved these changes

2023-03-30 00:07 UTC, merged