Felinids can actually eat mice and don't gross out
tgstation/tgstation pull request #74234
Opened 2023-03-25 10:13 UTC by Kush1Push1

## About The Pull Request

Removed "RAW" flag from dead mice.
Since humans still dislike "GORE" as well as some other races, it shouldn't cause issues.

## Why It's Good For The Game

A fix for #71138

## Changelog

:cl: SishTis
qol: Felinids can eat dead mice and don't gross out.
/:cl:

2023-03-25 10:49 UTC, Ghilker commented
this makes no sense, it is raw meat, felinid code should be the one doing the proper checks

2023-03-25 11:02 UTC, Fikou requested changes
its a raw mouse, this is not an acceptable solution

2023-03-25 11:04 UTC, Kush1Push1 commented
> this makes no sense, it is raw meat, felinid code should be the one doing the proper checks
> its a raw mouse, this is not an acceptable solution

In practice many other types of food have "raw" tag, such as dough. After all, it's just a tag to point-out food preferences. 
From gameplay side, other races, but felinids, will keep their preferences over dead mices.

2023-03-25 11:06 UTC, Kush1Push1 commented
I actually don't see a solution without massive overhaul if "RAW" should be must-have for raw objects, even if in gameplay they keep their natural state (felinids eat dead mice, others (most) don't).

2023-03-25 15:20 UTC, Thunder12345 commented
Why would felinids eat raw mice, they're civilised people like you and me, not feral animals

2023-03-25 15:44 UTC, Ghilker commented
> I actually don't see a solution without massive overhaul if "RAW" should be must-have for raw objects, even if in gameplay they keep their natural state (felinids eat dead mice, others (most) don't).

You'll have to do that, just removing raw won't be enough.

2023-03-25 22:50 UTC, Jacquerel commented
I think it was me who messed this up (previously you could eat these with Deviant Tastes, now you can't), but I don't think this is an acceptable fix either.
Either Felinids are happy to eat uncooked raw food or they aren't. You would either remove RAW from the disliked food list (meaning they are happy with eating weirder things in general) or remove GORE from the liked food list again to revert a change I made (so Deviant Tastes felinids are the ones who are happy to eat dead mice and raw corpses in general).

Felinids probably already have essentially the most permissive food list in game so I don't know if making it even nicer is a good idea, I don't know how important food enjoyment balance is but it's worth mentioning.

2023-03-26 13:49 UTC, Draggeru commented
> Why would felinids eat raw mice, they're civilised people like you and me, not feral animals

Wrong

![unknown-35](https://user-images.githubusercontent.com/81540056/227780222-fdab1d02-64b0-4846-9c16-506144c5540f.png)

2023-03-26 22:16 UTC, ZephyrTFA requested changes
This is not the correct way to fix the "problem" of felinids not liking dead mice. See previous comments, although I personally prefer the callback method.

2023-04-03 02:57 UTC, san7890 commented
This has been marked as Do Not Merge for a week and has now staled out, please apply the requested changes to your PR and seek out a maintainer to re-open this.

2023-04-03 02:57 UTC, closed without merging