Adds The Sturdy Shako (HoS Hat)
tgstation/tgstation pull request #74277
Opened 2023-03-26 19:22 UTC by Thunder12345

## About The Pull Request

Adds a new craftable HoS shako, made from the standard peaked cap and some plasteel and gold.

![shako](https://user-images.githubusercontent.com/5479091/227799392-ad2ea145-5c58-45d7-8763-a76e9323ec09.png)

Moves the HoS cap into a subtype `/obj/item/clothing/head/hats/hos/cap` to avoid catching the beret in the crafting recipe, the base type `/obj/item/clothing/head/hats/hos` is now a generic subtype which should never exist.

(Yes there's a TF2 reference included with the hat)

## Why It's Good For The Game

Adds an additional level of style for an HoS willing to put a little effort into gathering the required materials. As it is crafted as a one-to-one trade with another headgear there is no additional spare headgear introduced. 

## Changelog

:cl:
add: The NanoTrasen Costuming Department has released specifications for how to convert the Head of Security's cap into a shako.
/:cl:

2023-03-26 19:23 UTC, san7890 commented
2 ref

2023-03-26 20:03 UTC, Likteer commented
Tough chance, but could I ask for a novelty version?

2023-03-26 20:24 UTC, Thunder12345 commented
> Tough chance, but could I ask for a novelty version?

No, make a real one

2023-03-26 21:11 UTC, Time-Green commented on code/datums/components/crafting/tailoring.dm
> +		/obj/item/stack/sheet/plasteel = 2, //Stout shako for two refined
thank you

2023-03-26 21:15 UTC, Jacquerel requested changes

2023-03-26 21:15 UTC, Jacquerel commented on code/modules/clothing/head/jobs.dm
> +	strip_delay = 80
```suggestion
	strip_delay = 8 SECONDS
```
Just while you happen to be here

2023-03-27 03:36 UTC, Fikou requested changes

2023-03-27 03:36 UTC, Fikou commented on code/modules/clothing/head/jobs.dm
> +	desc = "Please contact the NanoTrasen Costuming Department if found."
```suggestion
	desc = "Please contact the Nanotrasen Costuming Department if found."
```

2023-03-27 19:37 UTC, merged