Lavaland Monster Sprite Update
tgstation/tgstation pull request #74299
Opened 2023-03-27 19:19 UTC by Mey-Ha-Zah

Updates most Lavaland mob sprites, merges some icon files and adjusts the pathing.

## About The Pull Request

Updates Most Lavaland Mob Sprites with work provided by Sheets.
Merges, splits, and moves a few icon files and icons to adjust for the new icons.
Repaths the dmi locations and pixel shifts for the adjusted sprites.

## Why It's Good For The Game

Better quality sprites are better to look at.
Putting sprites that are the same type in the same file is much saner.

## Changelog

:cl:
imageadd: added new lavaland sprites, moved some sprites to a new location, adjusted pixel shift for the updated sprites, adjusted the name of some sprites.
/:cl:

2023-03-27 19:20 UTC, Cheshify commented
Can we see what they look like?

2023-03-27 19:21 UTC, Mey-Ha-Zah commented
yes, I'm gonna add some icons in a minute

2023-03-27 20:02 UTC, Sealed101 commented on icons/mob/simple/lavaland/lavaland_monsters.dmi
mapping helper's sprite was removed but not replaced
![image](https://user-images.githubusercontent.com/75863639/228053004-144d56bc-0843-4157-978c-3f8bb6d44632.png)

2023-03-27 20:05 UTC, Sealed101 commented
fuckin' baller sprites, sheets is putting in the good work.
also most crusher trophies would need to be updated as to not fall behind the new n flashy bitz

2023-03-27 20:35 UTC, IndieanaJones commented
Holy shit, I love the elite sprites.

2023-03-27 20:36 UTC, Imaginos16 approved these changes
Holy based

2023-03-27 21:23 UTC, Helg2 commented
Color of dragon horns kinda blend in with the floor color.

2023-03-28 01:22 UTC, AverageUser67 commented
*inhale
MERGE!!!!
(after updating hierophants arena)

2023-03-28 15:38 UTC, Wallemations commented
I heard some of these were animated but I can't see them on mobile, could you show those animated gif versions?

2023-03-28 15:47 UTC, LSommers commented
Old Heiro looked like an animated, clearly artificial club
This just looks like a generic... something.

Ash Drake is now a dragon from the hit Bethesda title Skyrim by Todd Howard, I can't wait to buy it again (this is a joke and a complain about how you took it from four limbs + wings classic style of dragon to the post-skyrim "wings as front limbs" deal)

Watcher looks fine.

No idea what else was changed and can't be assed to figure out how to look at it. Not a fan overall.

2023-03-28 15:51 UTC, Jacquerel commented
The checks tab (icondiffbot) will show any animated changes, though as Wallem said it usually doesn't function for me on mobile.
This is the animated Hierophant.
![image](https://camo.githubusercontent.com/e0a4406f172f0c192386c853941ecd314f0f4e2b6764f353d7747347e9867483/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37343239392f333835393537343434393237363138363833342e676966)

2023-03-28 16:10 UTC, Mey-Ha-Zah commented
> Old Heiro looked like an animated, clearly artificial club This just looks like a generic... something.
> 
> Ash Drake is now a dragon from the hit Bethesda title Skyrim by Todd Howard, I can't wait to buy it again (this is a joke and a complain about how you took it from four limbs + wings classic style of dragon to the post-skyrim "wings as front limbs" deal)
> 
> Watcher looks fine.
> 
> No idea what else was changed and can't be assed to figure out how to look at it. Not a fan overall.

The drake change was inspired by an artwork piece, and the heirophant is part of something larger, just wait and see.

2023-03-28 16:36 UTC, Helg2 commented
> No idea what else was changed and can't be assed to figure out how to look at it.

https://github.com/tgstation/tgstation/pull/74299/checks
Click on the details.

2023-03-28 17:05 UTC, Thunder12345 commented
Drake should spread its wings when flying, it's not a hovercraft

2023-03-28 19:00 UTC, Sealed101 commented
> (why is his eye now a mouth?) 

retconned lmao

2023-03-28 19:20 UTC, Mey-Ha-Zah commented
> Drake should spread its wings when flying, it's not a hovercraft

Might ask for a sprite for this in a future PR. But that is for later.

2023-03-28 21:21 UTC, Fikou requested changes
sentient_creature.dm renders the pandora box now, because the broodmother icon is missing, you need to either make this intentional by replacing the broodmother with pandora there, or use the icon file that has the broodmother.

I also worry about possible balance implications of how small baby goliaths are, and that brimdemons are much less expressive in their attack. (also the beam ending looks weird but thats just personal opinion)

lastly idk if you forgot or if they arent made but herald and ancient goliaths are missing directionals unlike everything else (goliaths used to have em)

2023-03-28 21:44 UTC, Mey-Ha-Zah commented
I'll discuss the sprite changes with Sheets, and as for the sentient creature dm, I'll deal with that... if I can figure out how.

2023-03-28 21:57 UTC, Jacquerel commented
> I'll discuss the sprite changes with Sheets, and as for the sentient creature dm, I'll deal with that... if I can figure out how.

That change is simply in `sentient_creature.dm`, another instance of "the file or icon state name changed".

2023-03-28 23:09 UTC, Shadowflame909 commented
Hey that's pretty good!

2023-03-29 03:28 UTC, Mey-Ha-Zah commented
Alright, might be a week before I get the sprites you want Fikou.
I'm open to ideas about changes, some good ones I've seen on discord are easy enough I could do them myself.
If you have anything that's a minor nitpick (And not changing a large part of the sprite) or a small idea that can easily be done, just type it out, or message me on discord.

2023-03-29 10:02 UTC, Pumpkinoe commented
these are awesome, great sprites
looks like the hierophant club sprite remains unchanged though?

2023-04-02 19:23 UTC, Furrior commented
Will Hiero's staff be resprited too to match new style?

2023-04-03 18:42 UTC, Mey-Ha-Zah commented
> Will Hiero's staff be resprited too to match new style?

All items will be updated in a future PR. This is specifically the Creatures themselves.

2023-04-03 18:49 UTC, Helg2 commented
> All items will be updated in a future PR. This is specifically the Creatures themselves.

That's just half done work then.

2023-04-04 00:40 UTC, Fikou approved these changes
code looks good

2023-04-05 23:42 UTC, Imaginos16 approved these changes
Yeah checked again since apparently one approval by yours truly wasn't enough. Still good just merge it already.

2023-04-05 23:58 UTC, merged

2023-04-06 03:57 UTC, Toastgoats commented
All of these are really cool but the ash drake looks like a sprite rip from a completely different game, I'd really prefer it if you did a revamp like the other megafauna sprites instead of this.