Makes eyestabbing, neck slicing and kneecapping a little easier to use.
tgstation/tgstation pull request #74307
Opened 2023-03-27 21:04 UTC by Helg2

## About The Pull Request
Neck slicing warning is completely useless and annoying, so i deleted it. Everytime i sliced someone's neck i needed to turn off combat mode just to continue killing them which is annoying as hell.

Eye stabs warnings are too completely useless and annoying. If you're in the fight you definitely don't want to read warnings about them being alien or their eyes being covered.
Also made it's code a little bit prettier?

Also fixed that you could kneecap someone when their legs are already broken to rubble.

## Why It's Good For The Game
Easier to fight with those things.

## Changelog

:cl:
qol: you will no longer gain useless message, when you're harming someone in agro-grab in the head with their neck already slicen, instead of continuing killing them.
qol: you will no longer gain irritating messages, when trying to stab someone in the eye, instead of just stabbing them with screwdriver.
fix: you can no longer aim for the knees to break them if they're already broken completely.
/:cl:

2023-03-27 21:08 UTC, MrMelbert requested changes

2023-03-27 21:12 UTC, Helg2 commented on code/datums/elements/eyestab.dm
>  		return
I'm not sure if you can attack brains, so i left it here xd. I'll check it in a min.

2023-03-27 21:26 UTC, Helg2 commented on code/datums/elements/eyestab.dm
>  		return
Okay, didn't know.

2023-03-27 21:32 UTC, Helg2 commented on code/datums/elements/eyestab.dm
>  		return
Thinking about it, does this part has it's use at the moment even?

2023-03-27 21:34 UTC, Helg2 commented on code/datums/elements/kneecapping.dm
> +			return
I'll try to add just the screams if they are already broken then.

2023-03-27 23:21 UTC, Helg2 commented on code/datums/elements/kneecapping.dm
> +			return
Added

2023-03-27 23:26 UTC, Helg2 commented
Can someone remove the "Fix" and add the "Feature" then please?

2023-03-31 13:39 UTC, Jacquerel requested changes
One nitpick then we're good to go.

2023-03-31 15:45 UTC, merged