The outlet - calebs Krazy clothing outlet
tgstation/tgstation pull request #74319
Opened 2023-03-28 06:11 UTC by Donglesplonge

## About The Pull Request

This PR adds in a new space ruin, known as the outlet. the outlet is a clothing store in disrepair over its time drifting through space, why was it abandoned in the first place? explore and find out! i've spent my fair share of time meandering around space looking at ruins for fun, so i figured with mapping march going on i'd throw out my own ruin for fun. 

<details> 
<summary> SDMM screenshots of the map </summary>

![map overview with areas](https://user-images.githubusercontent.com/120208006/228141828-4a7311c9-8ce7-4107-9514-3e4b3f2457db.PNG)

![map overview without areas](https://user-images.githubusercontent.com/120208006/228141870-7df3b532-a83f-491a-b7ea-fbc483e6ee90.PNG)

</details>

<details>
<summary> in game screenshots of parts of the map </summary>

![storefront](https://user-images.githubusercontent.com/120208006/228142049-f6a6f660-8dcb-4599-9d38-45b2a22993b3.PNG)

![research rooms](https://user-images.githubusercontent.com/120208006/228142087-e728ce11-4dbd-4c71-9999-04abb3e4675f.PNG)

![cultinfluence](https://user-images.githubusercontent.com/120208006/228142120-9fe2475a-6317-4560-b794-1252347743be.PNG)

</details>

Big ups to chesh, vire, and the people of the coding channel for helping me out with questions i had about github, i appreciate you all greatly for it.

Ckey to receive rewards: Donglesplonge

## Why It's Good For The Game

space is a fun place to be sometimes, if the station goes down the toilet and you just want peace and to be alone for a part of the round you don an EVA suit and jump out an airlock and drift, adding more substance to it would help make people feel happy about being in it, and i hope to help accomplish that with this ruin addition. It has sustainable atmospherics and a powernet to help it stay up in case you need a breather from some of the more dangerous places.

## Changelog

:cl:
add: central commands meteorological divsion has picked up a new asteroid drifting in NT space, what secrets could it hold?
/:cl:

2023-03-28 07:41 UTC, Donglesplonge commented
i'm marking this under draft instead of review so i can continue working on it, as apparently i couldn't catch all the errors using VSC, sorry for the inconvenience.

2023-03-28 08:07 UTC, Donglesplonge commented
i overreacted a bit making it a draft thinking i had a large amount of errors but it turns out it wasn't

2023-04-06 01:00 UTC, Maurukas requested changes
<details>
<summary>The coldroom has atmos/firealarm issues</summary>

There is no fire alarm inside this room.
You're using `/turf/open/floor/iron/kitchen_coldroom/freezerfloor`, which starts with cold atmos. When this room is opened it instantly sets off the fire alarms. `/turf/open/floor/iron/freezer` would be a better choice here, as it's the same sprite, but without the cold atmos.

![image](https://user-images.githubusercontent.com/66576896/230245970-77552c59-a5b2-41b4-8fb8-e144c26750a6.png)
</details>

Only thing that came up. Otherwise, this looks fantastic.

2023-04-07 01:16 UTC, Maurukas approved these changes

2023-04-07 01:16 UTC, merged