Adds the Dark Matt-eor when you emag a stupid amount of meteor shields
tgstation/tgstation pull request #74330
Opened 2023-03-28 21:21 UTC by tralezab

## About The Pull Request

<details>
  <summary>Dark Matt-eor Image</summary>
  
  ![image](https://user-images.githubusercontent.com/40974010/228368755-34ae5f89-e1bb-498b-bbf8-a14ff4240dc0.png)

</details>

> A barely visible blur in the cosmic darkness, like a ghostly shadow on a moonless night. A piercing howl in the vacuum of space, as if it were tearing the fabric of reality. A twisted halo of light around it, bending and breaking the rays of distant suns. A shower of quantum sparks, flickering and fading in its wake. A dark matter meteor (dark matt-eor) is a wonder to witness, and to dread.

> A sudden impact, like a hammer blow to the heart of the station. A violent tremor, shaking and shattering the metal walls and windows. A deafening roar, as the air rushes out of the breached hull. A blinding flash, as the dark matter meteor unleashes its hidden energy. A tiny black hole, forming and growing in the center of the station. A relentless pull, dragging everything towards the abyss. A dark matter meteor is incredibly deadly.

Emagging too many meteor shields will summon a dark matt-eor. This comes with several warnings, and after awhile, warns the station that someone is trying to summon a dark matteor.

The dark matt-eor itself is not that damaging in its impact, but drops a singularity in its final resting place.

## Why It's Good For The Game

It's a new way to terrorize a round as an antagonist. Before, emagging a lot of meteor shields would basically make meteor showers the only event that can run, which is cool, but since constant meteor waves are going to destroy the station, let's also throw in the mother of all meteors!

This also adds warnings to spamming emagging meteor shields, which imo needs it. The round ends when someone spams emagged meteor shields, and since they're meteor shields nobody is going to reasonably check on them.

## Changelog

:cl:
add: The Dark Matt-eor.
balance: emagging a lot of meteor shields warns the station, but emagging enough of them summons a Dark Matt-eor.
/:cl:

2023-03-28 21:29 UTC, Fikou commented on code/modules/station_goals/meteor_shield.dm
> +			priority_announce()
nice announcement

2023-03-28 21:29 UTC, tralezab commented on code/modules/station_goals/meteor_shield.dm
> +			priority_announce()
oops i already fixed this locally...

2023-03-28 21:32 UTC, Fikou commented on code/game/machinery/satellite/satellite_control.dm
> +/obj/machinery/computer/sat_control/proc/toggle(id)
mind touching this and the one below to use descriptive var names?

2023-03-28 21:35 UTC, flowercuco commented
no one throws spaghetti at the wall like you tralezab thank you so much

2023-03-28 21:38 UTC, Fikou commented
> When he designs a traitor final objective, but just puts it behind the emag instead...

just build a bsa to stop the singulo

2023-03-28 21:43 UTC, tralezab commented
## I'm just enjoying watching the dang thing

![image](https://user-images.githubusercontent.com/40974010/228373515-9ec46ca4-f67d-406b-a5da-6ac60ad58889.png)

2023-03-28 21:43 UTC, Fikou commented
> Fikou when you can't order the BSA and Meteor Sats on the same round

yeah you can when its extended

2023-03-28 21:59 UTC, ATH1909 commented
what's the purpose of the warnings when you can just construct 10 meteor sats in a remote location and emag them all in a row to instantly summon a singularity meteor?

2023-03-28 22:02 UTC, ATH1909 commented
> ATHATH i _just_ said I was considering that. BRO

okay hear me out here

instead of making this an effect for emagging too many meteor shields, you make this an actual traitor final objective that can only be given if the station has a meteor shields objective. make it, like, a device you strap onto one of the shields or something.

2023-03-28 22:04 UTC, ATH1909 commented
> ATHATH i _just_ said I was considering that. BRO
> 
> ![image](https://user-images.githubusercontent.com/40974010/228376738-d1c85878-bb0a-43b2-987e-1159addf6d73.png)

o

2023-03-28 22:07 UTC, tralezab commented
This is a neat final traitor objective, sure I'll add it as one since it's pretty adaptable into one

2023-03-28 22:23 UTC, Kubisopplay commented
Please let me throw that as an admin smite

2023-03-28 22:53 UTC, tralezab commented
Changes to avoid abuse and keep it a FUN feature:
- 1 minute cooldown on emagging
- always announces the dark matteor avoiding some edge cases where it collides before the announce can find it
- all hacked meteor shields give off a gps signal

2023-03-28 23:43 UTC, TheSmallBlue commented
Should have like, a 10% chance of being named "The Big Chip" instead

2023-03-28 23:46 UTC, LemonInTheDark commented
Ran out from sidewalk into 6 lane road/10
Pogged up

2023-03-29 00:07 UTC, DevinShafer commented
> > When he designs a traitor final objective, but just puts it behind the emag instead...
> 
> just build a bsa to stop the singulo

Just, throw a bluespace bag at it, If the codes still there I believe it "shrinks" it still.
or you know, throw the clown, the clown has fun interaction

either way I am to blame for this PR to be existent and I love it

2023-03-29 04:12 UTC, Pumpkinoe commented
copyrighted pumpkin0 2023 its my idea i swear

2023-03-29 05:38 UTC, Singul0 commented
> > ATHATH i _just_ said I was considering that. BRO
> 
> okay hear me out here
> 
> instead of making this an effect for emagging too many meteor shields, you make this an actual traitor final objective that can only be given if the station has a meteor shields objective. make it, like, a device you strap onto one of the shields or something.
> 
> this will satisfy the slow cook-enjoyers who just wanna bring back the meteors gamemode, still add the cool dark matter meteor to the game, and prevent people from raging over some doofus summoning a singulo 20 minutes into the round.

that assumes people actually do station goals. this will make the objective more annoying and harder to do than any other final objjectives since the traitor need to buy and build a meteorshield beforehand.

2023-03-29 05:49 UTC, nianjiilical commented
who is dark matt and what have we done to incur his wrath

2023-03-29 15:58 UTC, Watermelon914 approved these changes

2023-03-29 15:58 UTC, Watermelon914 commented on code/datums/components/singularity.dm
> +	if(iscarbon(target))
you should early return here

2023-03-29 18:56 UTC, Fikou requested changes

2023-03-29 18:56 UTC, Fikou commented on code/datums/components/singularity.dm
> +		carbon_target.visible_message(span_notice("[carbon_target] gets a nosebleed."), span_notice("You get a nosebleed."))
```suggestion
		carbon_target.visible_message(span_notice("[carbon_target] gets a nosebleed."), span_warning("You get a nosebleed."))
```

2023-03-29 18:56 UTC, Fikou commented on code/game/machinery/satellite/satellite_control.dm
> +/obj/machinery/computer/sat_control/ui_data()
on this proc use descriptive var names too

2023-03-29 18:56 UTC, Fikou commented on code/game/objects/items/toys.dm
> +	item_flags = NO_PIXEL_RANDOM_DROP
inherited from parent

2023-03-29 18:56 UTC, Fikou commented on code/modules/meteors/meteor_dark_matteor.dm
> +	SSsecurity_level.set_level(previous_security_level)
check if its still on red here

2023-03-29 18:56 UTC, Fikou commented on code/modules/meteors/meteor_dark_matteor.dm
> +	SSsecurity_level.set_level(SEC_LEVEL_RED)
what happens if its already red

2023-03-29 19:48 UTC, merged

2023-03-31 18:31 UTC, Loafin34 commented
this is the first maia roentgen reference in code. very surprising.

2023-04-02 11:26 UTC, carshalash commented
There's seriously no warning or anything for this?

2023-04-02 11:32 UTC, Draggeru commented
> There's seriously no warning or anything for this?

There is unless an admin forces it.