Adds pillow bonus for sleeping.
tgstation/tgstation pull request #74349
Opened 2023-03-29 21:05 UTC by Helg2

## About The Pull Request
There is bedsheet bonus, but no pillow bonus.

## Why It's Good For The Game
Healthy sleep.

## Changelog

:cl:
add: Sleeping with a pillow restores more health.
/:cl:

2023-03-29 21:08 UTC, MrMelbert requested changes

2023-03-29 22:29 UTC, Helg2 commented on code/datums/status_effects/debuffs/debuffs.dm
> +		for(var/obj/item/pillow/pillow in range(owner.loc,0))
Okay, i think it was left that way because of `break`. I still wonder if it's even abusable with those limitations.

2023-03-29 22:32 UTC, MrMelbert reviewed
Copy paste error

2023-03-30 06:22 UTC, Shadowflame909 commented
The more non suspicious things to do in dorms the better!

2023-04-01 04:28 UTC, merged