Fixes body purist headrevs from getting mad at their implant by making them unaware of it
tgstation/tgstation pull request #74346
Opened 2023-03-29 19:44 UTC by tralezab

## About The Pull Request

Body purists no longer mind implants with a special trait for "hidden implants". This special trait is replacing the "syndicate implant" variable and was just used to hide certain implants from medical scanners.

## Why It's Good For The Game

fixes #74180

## Changelog

:cl:
fix: Body purist headrevs having a bad time with their implant
/:cl:

2023-03-29 22:37 UTC, MrMelbert requested changes

2023-03-29 22:39 UTC, MrMelbert requested changes

2023-03-29 22:39 UTC, tralezab commented
yeah uuuh theres some bad issues i have fixed i'll push up commits in a bit

2023-04-17 19:35 UTC, tralezab commented
reviving...

2023-04-17 20:15 UTC, tralezab commented
ready!

2023-04-17 20:40 UTC, tralezab commented on code/modules/surgery/organs/augments_eyes.dm
> +	organ_flags = ORGAN_HIDDEN
😭

2023-04-17 21:38 UTC, merged