Adds "Cargonian Heavy Freighter" Escape Shuttle
tgstation/tgstation pull request #74361
Opened 2023-03-30 07:43 UTC by EkarusRyndren

## About The Pull Request
Adds a larger, gaudy shuttle with some belts for moving freight and a large cargo bay. Additionally, there is a teleporter onboard (with a hidden gigabeacon) for transporting cargo. A small, unstaffed bar as well as a medical bay and private lounge for cargo staff takes up the nose of the shuttle while the rest of command and security are stuffed in the back.

## Why It's Good For The Game
A gimmick shuttle mostly meant to annoy the crew for wasting a large amount of money on a shuttle with very, very little seating (six total belt-able seats not behind doors with an additional eighteen in locked areas that will likely go unused). To offset it's extremely high price (and gaudy nature) it features a functional teleporter and beacon- The crew just has to remember to use it. The onboard belts could prove amusing in moving the crew on to (or off of) the shuttle or just used for their intended purpose. (Move freight.)

## Changelog

:cl:
add: Added "Cargonian Heavy Freighter" escape shuttle.
/:cl:

2023-03-30 09:01 UTC, Singul0 commented
Nanotrasen hires out independence revolutionaries as sub-contractors now? sounds about right.

2023-03-31 01:39 UTC, BrandonSmith6 commented
I would love to see this in-game 👍

2023-03-31 03:29 UTC, san7890 requested changes
it's garish to look at, but i suppose that's the point

you must add this to the configuration, see https://github.com/tgstation/tgstation/blob/master/.github/guides/MAPS_AND_AWAY_MISSIONS.md#configuration for more information

2023-03-31 05:00 UTC, san7890 commented
![image](https://user-images.githubusercontent.com/34697715/229026906-24916010-1fe6-4342-b4be-ac5c291d3f94.png)

forgot to mention this, feel free to hit this button when you're ready for this PR to be reviewed again. i just marked it as draft for organization purposes

2023-03-31 16:59 UTC, EOBGames commented
I just have to be honest, this goes beyond gaudiness into just being eyesearing. Additionally, this sorta steps into the same territory as the Cruise Shuttle and the Luxury Shuttle. Taken together, I just don't want this one ingame.

The idea of a cargo-style shuttle is a neat concept, but I'd rather it be done with a lower budget and a more industrial feel.

2023-03-31 16:59 UTC, closed without merging