The North Star Expeditionary Vessel - A Second Wind
tgstation/tgstation pull request #74371
Opened 2023-03-30 16:33 UTC by Cheshify

## About The Pull Request
A new map for TGstation, in the works! It has 4 fucking Z levels, a massive expansive maintenance with unique designs, and some unique code features in the works.

To Do:
- [ ] Update the Map to Modern TG
- [ ] Work on Map Optimizations
- [ ] Run Live Tests

Fikou has greatly helped with creating an important flavour aspect of this map, Trek Uniforms on anyone who joins! See the forum thread for more. This includes the framework for innate station traits, station traits loaded as long as it's in a map's json

Here's the forum dev thread there are screenshots there.
https://tgstation13.org/phpBB/viewtopic.php?p=657252#p657252

### Mapping March

Ckey to receive rewards: Cheshify

## Why It's Good For The Game
So, this is the North Star. An effort taking multiple mappers and of 9~ months of hard work. This map was not initially designed for TGstation, but always designed for TGstation code. The process of retooling the map for TGstation was an absolute joy and I feel like the map definitely has it's niche as a massive and unique experience for it's players.

I adore this map, it's gorgeous, has a unique aesthetic, and a number of very funny interactions with multi-Z. The PR comes packed with unique mechanics for future mappers (innate station traits!), a number of map-fitting shuttles, and a fun spacefaring uniform gimmick for the crew.

**This is my second attempt at bringing this map into rotation. It was initially closed due to concerns about maptick and performance, as I wasn't willing to push for a map to be added to the repository if it didn't function to my own standards. I've been informed by a number of coders far better than I that optimizations are arriving and enroute, so I think it's time to dust her off and set sail for another journey.**

## Changelog
:cl: Cheshify, Fikou, Blue-Berry, Zytolg, InfiniteGalaxies, Striders, Sylphet, Riggle, Soal, Andry, Crit, and Deranging.
add: Nanotrasen's Newest Exploratory Vessel is now available! Meet the North Star!
code: Raised the number of possible level render to 4, check your preferences if needed to be reduced.
code: Adds a system for map-loaded station traits. Used by the North Star to give people exploratory uniforms.
/:cl:

2023-03-30 16:55 UTC, Mothblocks commented on code/datums/shuttles.dm
> +	suffix ="northstar"
```suggestion
	suffix = "northstar"
```

2023-03-30 17:02 UTC, MrStonedOne approved these changes

2023-03-30 17:06 UTC, Fikou commented on code/game/area/areas/station.dm
> +	icon_state ="escape_pods"
```suggestion
	icon_state = "escape_pods"
```

2023-03-30 18:36 UTC, Cheshify commented
There's only so much I can do with the ship right now. For the moment, there's no overmap or exploration, but once a number of optimization issues with the map are made, I'm comfortable with trying to expand what it can do ship-wise.

Right now it's a ship in style and in construction, but not mechanically.

2023-03-31 01:41 UTC, Cheshify commented
I guarantee that there are some mild map issues, but it passes CI.

2023-03-31 01:49 UTC, Cheshify commented
Don't want this test-merged without me or before I've done local tests, please.

2023-03-31 03:26 UTC, RegJackson commented
![northstar](https://user-images.githubusercontent.com/91390185/229015339-96509ebc-97a1-492d-9b2f-7b453cf90c89.gif)

2023-03-31 06:58 UTC, Rex9001 commented
Return of the king! I played this once whilst it was tmd and the sheer size and fun of this map remains unrivaled on TG

2023-03-31 14:41 UTC, Cheshify commented
There's still some issues, probably, minor ones, but I'd say she's ready for a *TEST* merge. I'd still like to be notified and present if that's the case so I can handle all map error reports.

2023-03-31 22:54 UTC, theta060 commented
tracking someone as a heretic will be really shitty

2023-04-01 15:38 UTC, Cheshify commented on code/datums/station_traits/innate_traits.dm
> +		crewmember.equip_to_slot_if_possible(uniform, ITEM_SLOT_ICLOTHING, disable_warning = TRUE, initial = TRUE)
@Fikou You might have a better insight on this. From what I read, it might delete them depending on how and when accessories are added.

2023-04-01 18:10 UTC, Cheshify commented
Man, I almost forgot how hard it is to keep a testmerged map up to date.

2023-04-02 22:31 UTC, Cheshify commented
Had an issue with sparring sect chaplains, apparently since the chapel used the ``/monastery`` subtype it runtimed.

2023-04-03 02:08 UTC, Cheshify commented
Aside from tests and polish, I don't know what else the map really needs.

2023-04-03 06:44 UTC, Rex9001 commented
Small feedback: Cargo employees get the same outfit assistants get roundstart, a greenish star treck suit. Idk if this is intended

2023-04-03 17:00 UTC, Cheshify commented
> Small feedback: Cargo employees get the same outfit assistants get roundstart, a greenish star treck suit. Idk if this is intended

Assistants start in grey, cargo + service starts in green. Either there's an issue with the code, or you may be slightly colorblind.

2023-04-03 19:25 UTC, Cheshify commented
Just checked, cargo starts wearing green!

2023-04-03 23:12 UTC, Cheshify commented
I don't even know why it had the tools tag

2023-04-04 03:06 UTC, Cheshify commented
> Small feedback: Cargo employees get the same outfit assistants get roundstart, a greenish star treck suit. Idk if this is intended

![image](https://user-images.githubusercontent.com/73589390/229676650-5debbe5c-d36b-47ac-a7d8-1502f1d1c389.png)

On testing, I'm afraid I don't know what you're talking about. Cargo wears green, assistants wear grey.

2023-04-04 03:15 UTC, san7890 commented on code/datums/station_traits/innate_traits.dm
> +	trait_type = STATION_TRAIT_NORANDOM
@MrStonedOne FYI - This trait is automatically applied to this map by default via the JSON, which does bypass the `#GREY_ASSISTANTS` configuration. I don't think it matters too much at the end of the day, but given that you both introduced it and are the final say on configurationy stuff, do you think it matters?

2023-04-04 18:15 UTC, Cheshify commented
![image](https://user-images.githubusercontent.com/73589390/229881886-1d1304e3-0899-4aed-9e81-079758268581.png)
Removed that line, I want to force players to interact with the coolant system

2023-04-04 19:25 UTC, theta060 commented
what are you even talking about coolent system i remember you saying stuff about them in the TMs just dump waste into space or a lone tile

2023-04-04 19:37 UTC, Cheshify commented
> what are you even talking about coolent system i remember you saying stuff about them in the TMs just dump waste into space or a lone tile

If you want to waste the SM gas, you can set it up in-round yourself. I don't want to encourage it by having it be a system, I'd rather give atmos techs actual job content and gas to use in said job content.

2023-04-04 20:01 UTC, Cheshify commented
Minor tangent but that comment really sucks. With that mindset, why do anything? Why not just have every map just be the same clone of each other where you're never tasked with anything, why have randomness even be an element, why have anything aside from the most basic boring and simple design where you're never challenged to try something new.

2023-04-04 20:47 UTC, Rex9001 commented
> > Small feedback: Cargo employees get the same outfit assistants get roundstart, a greenish star treck suit. Idk if this is intended
> 
> ![image](https://user-images.githubusercontent.com/73589390/229676650-5debbe5c-d36b-47ac-a7d8-1502f1d1c389.png)
> 
> On testing, I'm afraid I don't know what you're talking about. Cargo wears green, assistants wear grey.

Huh might just have been someone stealing, sorry for the trouble

2023-04-04 21:03 UTC, Cheshify commented
> Huh might just have been someone stealing, sorry for the trouble

Don't apologize! It got me to finally add armor values to the trek uniforms.

2023-04-04 22:59 UTC, optimumtact commented
I don't want more alternate uniforms and I don't see how to resolve this issue

2023-04-05 03:40 UTC, thgvr commented
The uniforms are already in the game

2023-04-05 04:10 UTC, Cheshify commented
> The uniforms are already in the game

There are eight uniforms (all made via gags) added in with the PR. The assistant grey and the service/cargo greens.

2023-04-05 10:00 UTC, Rex9001 commented
I dont really understand, is it just the outfits that make this massive map DNM or is it the map itself? Either case its kinda dumb, this map vastly outshines a lot of the in-rotation maps.

2023-04-05 11:06 UTC, LemonInTheDark commented
he's got an issue (debatable or not) with the outfits. doesn't apply to the map itself, and doesn't mean the map is dead.
It exists to prevent like eob from going "oh cool job's done" and just sending it before that issue gets resolved.

2023-04-05 14:13 UTC, Cheshify commented
Just waiting on a conversation with oranges. I pinged him in the player's project thread on the tgcord. I'm sure this'll be quick to resolve.

2023-04-05 19:24 UTC, optimumtact commented
I'm not sure it will be easy to resolve, I have concerns about setting a precedent that a different map gives wholesale approval to change the basic visual look of every job on the station with a different uniform, and I worry about where that will lead to, if we say yes to this one here now, just because the rest of the map is excellent, we are unable to say no later to others.

There are two aspects to this concern

First, maintainability - this adds a new variable to the massive ball of complexity that is debugging issues, a pretty mild one here since it's just uniforms, but one can easily imagine a uniform specific bug occurring only on this map

more importantly it's just asking for spriters to feel like they have to resprite two entire sets of uniforms anytime they want to make a visual change to a specific dept, because now there are two sets of specific uniforms in use.

The second concern is for new players, it's hard enough for htem to have to deal with an entirely new map layout from round to round, I think loading on top of that the fact that they also have to learn an entirely new set of uniforms and visual designs is asking too much and will lead to too much confusion that might turn them away from an already notoriously hard to pick up game.

Ultimately my view is that mappers have a lot of creative leeway with many things, but I do not believe that they get carte blanche to change the visual look of something as basic as the uniform of jobs just because it's a different map.

Unfortunately I do not think I am willing to compromise on this point, I think it's important to set a precedent here going forward, so it will be up to @ninjanomnom and @Mothblocks to decide if they want to overrule me on this

2023-04-05 20:02 UTC, TheSmallBlue commented
If I may give my 2 cents, I don't think it's that big of a deal.

The reason why North Star has differing uniforms is not "just because cesh could", it's because it's different from every other map we've had so far, North Star isn't a station, it's a ship, an entirely different setting from the space station one. If out intention is to have a Star Trek like retro space visual aesthetic, it's sensible and expected for ship and station uniforms to look and feel completely different. I heavily doubt we'll have more ship maps, so I heavily doubt this will be an issue that'll repeat itself, but even if we did it'd make sense if said ship map used the same trek uniforms for consistency and lore reasons. 

The uniforms themselves are just clothes, they function exactly like the default jumpsuits, the only way they could be broken are if all jumpsuits are broken, which has nothing to do with now north start itself implements them. The only way a north star specific uniform bug can come up is when the map is setting up and it applies the trek uniform trait or whatever it uses, in which case that would only affect north star. 

The uniforms themselves are clearly based on the star trek uniforms, and they're supposed to keep that aesthetic. If an artist wants to update the station science jumpsuit's aesthetic, they have no reason to do the same for the trek suits, since they're not supposed to be unique designs at all, they're supposed to stay a clear callback to star trek.

Saying that players will be turned away from the game just because they have a different piece of clothing is absurd. Again, the trek jumpsuits work exactly the same as the normal ones. You understand one, you understand the other. No player will leave because "I don't get why this spefic corner of my screen looks different than usual". By the same logic, make every job wear the same jumpsuit! Otherwise new players that are trying the janitor job will be very confused by the fact that the previously gray jumpsuit is now purple!

In my opinion, the pros of having an unique aesthetic to make the north star stand out even more than it already does (which in of itself brings in a breath of fresh air to what many consider the dull normal space station environment) heavily outweigh the con of "it might be hard to debug"

2023-04-05 21:14 UTC, Cheshify commented
> First, maintainability - this adds a new variable to the massive ball of complexity that is debugging issues, a pretty mild one here since it's just uniforms, but one can easily imagine a uniform specific bug occurring only on this map

> more importantly it's just asking for spriters to feel like they have to resprite two entire sets of uniforms anytime they want to make a visual change to a specific dept, because now there are two sets of specific uniforms in use.

This is a point I'm willing to somewhat agree on. It is a new set of uniforms, but you yourself say it's mild. I personally believe that for the sake of aesthetic design, the possible future potential of a mild bug is warranted? After all, we have plenty of feature PRs that can possibly add mild bugs, I'm not sure what makes this one any different. However, more workload for spriters is a concern that I can agree with. Spriters do a LOT of work in keeping the game looking good, and giving them more to do is worrying. I'll take this into account for possible compromises (I'm sure there are possible compromises here)

> The second concern is for new players, it's hard enough for htem to have to deal with an entirely new map layout from round to round, I think loading on top of that the fact that they also have to learn an entirely new set of uniforms and visual designs is asking too much and will lead to too much confusion that might turn them away from an already notoriously hard to pick up game.

This, SmallBlue put well. It's absurd to think that staying power will be an issue when crew uniforms are very mildly changed to reflect the setting. Nobody is going to look at a different uniform and outright leave and never come back, especially when vendors supply the job-standard uniforms.

> Ultimately my view is that mappers have a lot of creative leeway with many things, but I do not believe that they get carte blanche to change the visual look of something as basic as the uniform of jobs just because it's a different map.

I can respect this, though I think it's important to discuss WHY I chose this design. Apologies for sounding a bit like a pretentious artist type here, though this is the mindset I am in when working on this map,

When blocking out, designing, and eventually reworking parts of the map, my goal has always been to provide the distinct feeling of being "within an exploratory vessel". The uniforms are a minor but not insignificant part of that. They give players a tie that anchors themselves to the setting, using Star Trek as a 'subtext' for putting players in the mindset that they're in a different kind of environment. I think they add to the overall flavour of the map, and are also just fun to wear.

My intention has never been able to get away with "carte blanche" changes, but to provide players with that authentic experience. You'll see through the history of this project that I've struggled with "Metastationisms", where I catch myself (and others) suggesting that maybe things should be a little more standard, and I've fought to distance myself from it, in order to give players what I think is the best shipmap experience. I like the normal jumpsuits, they're iconic, well-sprited, and overall fun. I just think that when I'm going to make an authentic ship, we need something a little more exploratory.

----------Line Break This Is A Lot Of Writing----------

Okay, now. I know you said compromises weren't possible, but that's not something I can readily agree with. Here's a few thoughts and possible compromises.

- Remove the randomly chosen aspect of the uniforms, have one set of colored trek-inspired uniforms in order to make spriter's jobs significantly easier

- Remove the service and assistant uniforms, these are the only ADDED uniforms, the rest already exist within the game, I was told this could be a "too many sprites" issue, but that doesn't seem to be a part of your post.

- Finally, if all else fails. I'd be willing to rework or find some visual alternative to the uniforms

To note, I would VERY MUCH like to keep the innate station trait code. Having a system for mappers and coders to help differentiate maps beyond just having different layouts is a significant boon.

2023-04-06 00:57 UTC, Mothblocks commented
after some discussion i disagree with oranges on this point so we're throwing it to @ninjanomnom

2023-04-06 02:51 UTC, Iamgoofball commented
headcoder votes be like
![Multiple](https://user-images.githubusercontent.com/4081722/230260333-1caed5b5-6d77-4b8f-a820-dec8e1a94ec2.png)

2023-04-06 03:00 UTC, ninjanomnom commented
I've been thinking about this since yesterday when some of the technical concerns were being discussed in coderbus regarding the rsc costs. That's basically a non issue and were that the only consideration I would be fine with alternate uniforms per map. What oranges brings up though I find myself agreeing with, the maps we have in the repo should all follow similar designs graphically for consistency and maintenance sake.

We should not have alternate uniforms or any other such automatic resprites depending on the selected station map.

2023-04-06 03:04 UTC, Cheshify commented
Alright, and for keeping the innate station trait code?

2023-04-06 03:28 UTC, Cheshify commented
I have been informed that I cannot keep the framework.

2023-04-06 03:38 UTC, Fikou commented
Very disappointing decision.

2023-04-06 03:53 UTC, optimumtact commented
> I have been informed that I cannot keep the framework.

Who told you this? and can they please put their reasoning here.

2023-04-06 04:28 UTC, Cheshify commented
> > I have been informed that I cannot keep the framework.
> 
> Who told you this? and can they please put their reasoning here.

Mothblocks told me that since it would be unused here, it would need to be a separate PR to add innate station trait framework.

2023-04-06 04:43 UTC, CMDR-Gungnir commented
> What oranges brings up though I find myself agreeing with, the maps we have in the repo should all follow similar designs graphically for consistency and maintenance sake.
> 
> We should not have alternate uniforms or any other such automatic resprites depending on the selected station map.

But the thing is though, this creates the framework FOR that. This is a Ship, rather than a Station, so it has different shift-start uniforms. Then, if another Ship Map is made, they can share the expeditionary uniforms. We could have that consistency. But at the moment, this is our only Ship Map, and that's why it stands out on that front.

2023-04-06 04:53 UTC, optimumtact commented
please complain about the choice in a forum thread lets try to keep this to actionable things.

2023-04-06 13:16 UTC, spockye reviewed
![image](https://user-images.githubusercontent.com/79304582/230387789-69284183-74d3-4231-8183-57b7dcc74fcc.png)

missing pipe (departures)

![image](https://user-images.githubusercontent.com/79304582/230388494-5e1107bb-587a-45a9-ae27-19f145efb0d0.png)

missing pipes (3rd floor central starboard maints)

![image](https://user-images.githubusercontent.com/79304582/230388933-97cb7529-1e14-4687-bc4f-c32e59398c75.png)

missing wires (armoury)

![image](https://user-images.githubusercontent.com/79304582/230389248-88642dbf-a9ce-4e72-8640-86dec30eb598.png)

missing wire (entertainment centre)

![image](https://user-images.githubusercontent.com/79304582/230416801-c4371410-340a-4e91-b37b-2b61cc3cacc1.png)

missing wire (cargo bay)

![image](https://user-images.githubusercontent.com/79304582/230416967-4c7b63f3-5aa4-49fc-9359-66522be3ef03.png)

wacky wires (cargo bay)

![image](https://user-images.githubusercontent.com/79304582/230418008-d2e16336-45b2-400c-8989-7fc3e9464cc2.png)

missing zone (might just be on my side)

![image](https://user-images.githubusercontent.com/79304582/230422250-fafc6a1e-5b2a-4635-a717-43886db7f4a7.png)

zone fuckery

![image](https://user-images.githubusercontent.com/79304582/230418864-ed25dd72-aa44-49c5-a721-9d7d441e2973.png)

disposals fuckery (second floor fore hallway)

![image](https://user-images.githubusercontent.com/79304582/230419229-c80f36f5-e19a-4900-8ce6-642e54eba936.png)

disposals fuckery (chapel)

![image](https://user-images.githubusercontent.com/79304582/230419369-4cd8f9c3-62ae-4ad1-939f-9f868e07e59d.png)

missing disposals (ordenance testing lab)

![image](https://user-images.githubusercontent.com/79304582/230419930-26968aa6-d1a9-46c1-8fa3-2a181205dc68.png)

shouldn't there be nearstation on this?


the map looks rad. Amazing work man!

2023-04-06 17:47 UTC, Cheshify commented
> the map looks rad. Amazing work man!

I greatly appreciate the review, I'm putting out a fix for all of these right now

2023-04-06 17:54 UTC, Cheshify commented
OH, a few of those wire issues are because I use the shocked grille spawner! So they're not really broken.
![image](https://user-images.githubusercontent.com/73589390/230457710-e84b8a7c-bfd4-4ef7-affa-0d8bafbd52dd.png)

2023-04-06 18:13 UTC, Cheshify commented
Added some "emergent gameplay opportunities" to the armory.

2023-04-06 19:22 UTC, 13spacemen commented
Please fix the shutters on this map, all of them are facing south even though shutters have directions
![shutters1](https://user-images.githubusercontent.com/46101244/230475005-f4ed2bac-99af-4f3b-9baa-d00975565d8a.png)
![shutters2](https://user-images.githubusercontent.com/46101244/230475016-1e8a0f9b-377e-47f9-8ab0-b2e90c12a549.png)


For an example of correct shutter dirs you can see Metastation

The shutters here should be facing North and West but they're all South

2023-04-06 19:25 UTC, Cheshify commented
We have directional shutters now? Sure.

2023-04-06 20:14 UTC, Cheshify commented
There are a few shutters I didn't rotate just because I didn't think they looked good, but I did a few you pointed out

2023-04-06 21:15 UTC, Mothblocks commented on code/modules/clothing/under/trek.dm
> +
```suggestion
```

2023-04-06 21:15 UTC, Mothblocks commented
Removing DNM since alternate outfits are removed

2023-04-06 22:29 UTC, spockye reviewed
![image](https://user-images.githubusercontent.com/79304582/230503455-1118c00a-045a-4e09-9018-90a41b0f8872.png)

im pretty sure this should be the public version of the console (it's also locked behind an access door)

![image](https://user-images.githubusercontent.com/79304582/230505088-27cae7a0-5eec-41e9-a50a-e4f86d4ce8d0.png)

(hot tip hot tip!!!) a pretty nice way of creating a effect of railings being above something, is to set it's layer to 3.1 (4.1 to also be above plants)

2023-04-06 23:06 UTC, Cheshify commented
> im pretty sure this should be the public version of the console (it's also locked behind an access door)
> 
> (hot tip hot tip!!!) a pretty nice way of creating a effect of railings being above something, is to set it's layer to 3.1 (4.1 to also be above plants)

Another fantastic review, all changes made!

2023-04-07 03:48 UTC, Cheshify commented
Whoops! Minor issue with wiring I caught last-minute. I was always wondering why the SMES charged slow and why the shocked grilles would instakill sometimes...

Well, it's been fixed luckily

2023-04-07 12:59 UTC, Addust commented
> Please fix the shutters on this map, all of them are facing south even though shutters have directions ![shutters1](https://user-images.githubusercontent.com/46101244/230475005-f4ed2bac-99af-4f3b-9baa-d00975565d8a.png) ![shutters2](https://user-images.githubusercontent.com/46101244/230475016-1e8a0f9b-377e-47f9-8ab0-b2e90c12a549.png)
> 
> For an example of correct shutter dirs you can see Metastation
> 
> The shutters here should be facing North and West but they're all South

irrelevent but Funni Terry In-Round Pictures of Me Having A Fucking Skill Issue

2023-04-07 15:20 UTC, Cheshify commented
Alright, got rid of those files I didn't touch but were changed anyhow.

2023-04-07 19:47 UTC, Rex9001 commented
Cargo techs can access the grav gen for some reason.... but this might not be map specific and just a general access bug

2023-04-07 19:58 UTC, Cheshify commented
> Cargo techs can access the grav gen for some reason.... but this might not be map specific and just a general access bug

fixed

2023-04-08 01:37 UTC, Maurukas requested changes
Alright. This has already been polished quite a bit, and that shows. There's a lot that's different here and a lot that I like. I managed to find a few things, largely cosmetic as I went through.

I'll poke eob about things.

The SM is bolted at roundstart. While engineers can play with wires, a button to unbolt it nearby seems to me like it would be a good addition.

<details>
<summary>There's a fax machine on the floor of engineering next to second fax machine</summary>

![image](https://user-images.githubusercontent.com/66576896/230696442-9ffeea88-3ce3-4ba5-aec2-f2ac03443e60.png)
</details>

<details>
<summary>Some pressure sensors in the SM waste handling would be appreciated</summary>

This is non-standard and increased visibility into what's happening in the pipes would be helpful.

![image](https://user-images.githubusercontent.com/66576896/230696567-ffc29172-672f-4d7a-8904-bf4ef5693ac6.png)
</details>

<details>
<summary>These air supply pipes should be visible</summary>

![image](https://user-images.githubusercontent.com/66576896/230697126-04b4cf77-c81c-425a-a934-0e167024357c.png)
</details>
<details>
<summary>The.. uh. Tinting didn't work</summary>

![image](https://user-images.githubusercontent.com/66576896/230697241-594b538c-1c3e-48a9-8cbf-f0dc06d53ccf.png)
</details>

2023-04-08 02:47 UTC, Cheshify commented
Requested changes made:
I also removed the extra fax and made those two pipes visible.

<details>
<summary>Theater bathroom made grimier and now with a door bolt. Tossed some more posters around too.</summary>

Red arrows point from actual position to viewed position.
![image](https://user-images.githubusercontent.com/73589390/230699769-8a0ada45-cbdf-4564-a626-2a619e75de64.png)

</details>

<details>
<summary>SM chamber has a door bolt.</summary>

![image](https://user-images.githubusercontent.com/73589390/230699862-f96e9204-fc3b-45be-8d3d-7c3f72f7f170.png)

</details>

<details>
<summary> SM waste now has some meters so you can easily check up on coolant temperature and siphoned gas</summary>

I also added some comms-building stuff in the little telecomms storage nearby, just to fill out an empty rack
![image](https://user-images.githubusercontent.com/73589390/230699941-3b41bbef-7ba8-4778-9ce1-426c7aeef2f5.png)

![image](https://user-images.githubusercontent.com/73589390/230699881-30761493-fdcd-4339-a7e7-36ef3d6941ac.png)

</details>

When this is merged, could I make a secondary PR for a map plaque detailing date of merge?

2023-04-08 19:35 UTC, Time-Green commented
There are only 2 deepspace z-levels, which are completely oversaturated with ruins (I couldnt find a clean bit of space that didnt have ruins)
![image](https://user-images.githubusercontent.com/7501474/230739489-4017ea0d-7834-49a6-b3a4-ea254858b24f.png)

2023-04-08 20:09 UTC, optimumtact commented
probably need to be able to set a per map ruin budget to avoid this issue since most other maps have way more deep space z's

2023-04-08 22:27 UTC, Cheshify commented
> There are only 2 deepspace z-levels, which are completely oversaturated with ruins (I couldnt find a clean bit of space that didnt have ruins)
> 
> picture

I wouldn't have issues with just removing the extra space levels honestly. The map is plenty large as is and keeping the action focused to the station + lavaland may be smart?

2023-04-08 22:27 UTC, Cheshify commented
I'll wait on maptainer input

2023-04-09 03:00 UTC, CMDR-Gungnir commented
The Bartender's mini-kitchen's fridges aren't unlockable by said Bartender. Also, while I get that it's meant to be a MINI kitchen, it lacks an oven, which would make a pastry-cafe extremely difficult.

2023-04-09 03:50 UTC, Cheshify commented
> The Bartender's mini-kitchen's fridges aren't unlockable by said Bartender. Also, while I get that it's meant to be a MINI kitchen, it lacks an oven, which would make a pastry-cafe extremely difficult.

Fixed the access on the fridges. An oven is a bit too much for the minikitchen. I'd suggest working with chefs to see that done.

2023-04-09 04:07 UTC, MrStonedOne commented
> probably need to be able to set a per map ruin budget to avoid this issue since most other maps have way more deep space z's

just a modifier. make it say 0.3-0.4 for north star.

2023-04-10 00:06 UTC, DATA-xPUNGED commented
There is a door that goes from the main cargo to the ORM that miners can't acces, but they CAN access the door that goes from the decontamination chamber to the ORM, so i have to go around it every time.

2023-04-10 06:26 UTC, MrrFiish commented
Over by the arrivals shuttle on the left side and then a bit down there's a floating lightbulb in maints, literally unplayable wtf.

2023-04-10 22:37 UTC, Cheshify commented
Got some complaints about the cargo barriers so there's a new subtype to buff em up.

2023-04-11 16:55 UTC, 13spacemen commented
The green bridge pipes in atmos are rotated vertically instead of horizontally and dont connect
Also the window shutters in Incinerator should be rotated to face west

2023-04-11 18:52 UTC, Cheshify commented
> Had an issue with space ruins not spawning at all on the TM. Zero distant signals on GPS and, for as much of the deep space levels I could sweep, they were completely empty.

Intentional, I don't really want offstation content being the focus when the ship is so large, and some kind of bug was causing ruins to spawn jam-packed next to eachother. Disabled for now, maybe I'll bring back ruins later.

2023-04-11 18:56 UTC, Cheshify commented
> The green bridge pipes in atmos are rotated vertically instead of horizontally and dont connect Also the window shutters in Incinerator should be rotated to face west

![image](https://user-images.githubusercontent.com/73589390/231261567-f43c42c0-0822-4015-8e90-f341dc516960.png)
I don't know what you mean about the bridge pipes for atmos, they're all hoz. to me?

The shutters look a bit off when rotated like that, I'll try it out for now but I'm not exactly sure if I'll keep it.

2023-04-11 19:05 UTC, Cheshify commented
> > Intentional, I don't really want offstation content being the focus when the ship is so large, and some kind of bug was causing ruins to spawn jam-packed next to eachother. Disabled for now, maybe I'll bring back ruins later.
> 
> Maybe in a future PR space travel could be added as the only mean to reach ruins

That sounds awesome

2023-04-11 19:09 UTC, Cheshify commented
> > > Had an issue with space ruins not spawning at all on the TM. Zero distant signals on GPS and, for as much of the deep space levels I could sweep, they were completely empty.
> > 
> > 
> > Intentional, I don't really want offstation content being the focus when the ship is so large, and some kind of bug was causing ruins to spawn jam-packed next to eachother. Disabled for now, maybe I'll bring back ruins later.
> 
> Didn't one of the reviewers say something along the lines of that ruin spawns should be reduced, not removed?
> 
> For one, certain research isn't possible unless certain things are found. But even if you throw a few alien/experimentals in maintenance, just cutting out a gameplay loop like that is pretty callous. A bit like if you decided, say, a virology area isn't needed because who plays that and with a pandemic machine in chemistry means you're covered for cures.

Space Loot isn't a mandatory piece of content. It's fun optional side content. The map is 4 levels tall and has a very fun maint to explore. Lavaland still exists for ruin delving.

2023-04-11 19:16 UTC, YehnBeep commented
Very little content is mandatory ultimately. I just had higher hopes that you wouldn't cut stuff because people aren't playing the way you want them too. But oh well, I suppose.

2023-04-12 00:31 UTC, Cheshify commented
If someone else complains about something being non-standard or different than meta, or complains about maint being too dangerous I'm adding more land mines to maint.

2023-04-12 00:42 UTC, TribeOfBeavers commented
Good map! ^-^
Very unique, I've enjoyed all the rounds I've played on it so far (And I've only played like 2 departments in that time) 

My one suggested change would be having the doors leading into engineering only be linked to the ones further in from them instead of all of them, if that makes sense. As it is, when people are trying to use the parallel sets of doors they end up closing them on each other a bunch and it gets annoying getting groups of people in or out. 

For example:

A--B
-----
C--D

Have A and B linked, and C and D linked. As is, opening A and then C will cause A to close early. But it would maybe be a little more streamlined if A only closed B (Or B and D I suppose, if that's possible). Or is there a specific reason they're set up the way they are?

2023-04-12 02:13 UTC, HalfAwake691 commented
I dislike how disconnected chem is from the rest of medical, Sometimes people dont even comeby because of how off to the side it is. Plus the walk from pharma/Chem is waaaaay to long just to deliver chems. I wish that reception desk was pharma instead sometimes so ican at least help people/open doors for them if needed and people can order stuff and what not.

2023-04-12 02:16 UTC, Cheshify commented
> after getting used to it, I can definitely say that it's goddamned awesome and the best map I've seen in literal years.
> 
> re the security outposts though, they don't have prisoner lockers. they really don't.
> 
> ![4wXmLpsEn2](https://user-images.githubusercontent.com/39802339/231325787-babd7de7-7469-4b0c-bb94-48f215f1d622.png)

I just added them.

2023-04-12 02:18 UTC, Cheshify commented
> I dislike how disconnected chem is from the rest of medical, Sometimes people dont even comeby because of how off to the side it is. Plus the walk from pharma/Chem is waaaaay too long just to deliver chems. I wish that reception desk was pharma instead sometimes so i can at least help people/open doors for them if needed and people can order stuff and what not.
> 
> * Emerald Bromson

Pharmacy is like a 20 tile walk to the treatment room, and it has an access desk to the hall. I don't know what you mean by "too far away".

2023-04-12 02:28 UTC, Cheshify commented
Also I severely nerfed how many grilles are in maint, so you may be playing on an old commit.

2023-04-12 02:39 UTC, HalfAwake691 commented
> > I dislike how disconnected chem is from the rest of medical, Sometimes people dont even comeby because of how off to the side it is. Plus the walk from pharma/Chem is waaaaay too long just to deliver chems. I wish that reception desk was pharma instead sometimes so i can at least help people/open doors for them if needed and people can order stuff and what not.
> > 
> > * Emerald Bromson
> 
> Pharmacy is like a 20 tile walk to the treatment room, and it has an access desk to the hall. I don't know what you mean by "too far away".

It's like the only pharma thats not connected to the front lobby its just kinda pushed off to the side, I would like to see the front desk area made into pharma at least personally. Add a door that leads into the front like kilo and it would be 10/10 imho.

![image](https://user-images.githubusercontent.com/121485469/231333870-5c461be7-40c3-4450-8fb5-e2c5e2dacccb.png)

2023-04-13 18:58 UTC, optimumtact commented
Say good bye map tick

2023-04-13 18:59 UTC, merged

2023-04-13 19:01 UTC, TheVekter commented
WE'RE SO BACK

2023-04-13 19:06 UTC, DAKKA-WAAAGH commented
IT'S NOT OVER

2023-04-13 19:11 UTC, Cheshify commented
We're so fucking back boys

2023-04-13 19:36 UTC, Zonespace27 commented
HOLY SHIT ITS HERE WOOOOOOOOOOOOO

2023-04-14 01:50 UTC, Pumpkinoe commented
WE ARE SO FORWARD