Adds a prisoner transport space ruin
tgstation/tgstation pull request #74418
Opened 2023-03-31 23:39 UTC by Zonespace27

## About The Pull Request
Adds a new ruin to the game, a crashed prisoner transport.
Thanks to the shuttle's lack of reverse thrusters, the folks driving the shuttle rammed head-on into a stay asteroid! What're the odds, right? Now the presumably-important prisoners they were transporting are dead. Too bad.

<spoiler>

![image](https://user-images.githubusercontent.com/41448081/229250365-7f8bf075-9956-4c65-89f8-dbeaece74669.png)

![image](https://user-images.githubusercontent.com/41448081/229250478-4999bce5-1969-4223-8d54-59402e3ace6f.png)

</spoiler>

## Why It's Good For The Game
More ruins, and my (not-quite-late) submission for mapping march.

### Mapping March

Ckey to receive rewards: Zonespace

## Changelog

:cl:
add: Added a crashed prisoner transport space ruin.
/:cl:

2023-03-31 23:40 UTC, tralezab commented
Ok, TECHNICALLY late but I use my fake executive powers to grandfather you in

2023-04-16 21:58 UTC, Maurukas requested changes
You've got a random indestructible turf at (5,7) in the middle of the shuttle. Swap that out and it looks good.

2023-04-25 18:26 UTC, Addust commented
this looks like a ship from goon?? also the fuck are those WALLS, get them fixed

2023-04-26 00:06 UTC, Maurukas approved these changes

2023-04-26 00:06 UTC, merged