Adds a new solo fugitive backstory: The Invisible Man
tgstation/tgstation pull request #74415
Opened 2023-03-31 21:39 UTC by Rhials

## About The Pull Request

A disgruntled scientist, formerly the project lead at an experimental cloaking technology lab, now on the run for stealing the very prototypes they helped create. 

![image](https://user-images.githubusercontent.com/28870487/229234117-ef2d3951-4f57-4d62-9001-6d17808e2799.png)

You start off with a toggleable cloaking implant (makes you a bit more invisible than a cloaked ninja), and some Stabilized Saturn-X injectors (Which turn you COMPLETELY invisible). 

The three Saturn-X injectors grant you a cumulative 30 minutes of total invisibility (with the caveat and associated complications of you having to be naked and not able to just take them all at once consequence-free). It may not be as powerful as Waldo and his almighty Knock spell, but don't underestimate how much the camouflage can do for you in the dark. 

![image](https://user-images.githubusercontent.com/28870487/229234660-7d8ded61-8997-4536-8c13-a326a1635d03.png)

So go on, blend in with the crew. When the hunters come looking, shed your uniform and disappear...

The color of this PR is: **Purple**.
## Why It's Good For The Game

Adds some variety to solo fugitive selections (Waldo is still a bastard). Gives the opportunity for High-End SS13 Stealth Gameplay.
## Changelog
:cl: Rhials
add: New solo fugitive backstory: The Invisible Man!
spriteadd: New purple medipen and admittedly bad camouflage icon hud button sprite.
/:cl:

2023-03-31 22:26 UTC, VladinXXV commented
hey cool pr but can we get some screenshots that actually include this so-called invisible man? all you've posted are the pens laying on the ground and an empty maints shaft.

2023-04-01 01:42 UTC, tralezab commented
super cool fugitive, and a good reminder that I should really datumize them

2023-04-01 05:19 UTC, san7890 commented on code/modules/antagonists/fugitive/fugitive_outfits.dm
> +		)
```suggestion
	backpack_contents = list(
		/obj/item/reagent_containers/hypospray/medipen/invisibility = 3,
	)
```

lets do it right if we're going to multiline

2023-04-01 05:19 UTC, san7890 commented on code/modules/antagonists/fugitive/fugitive_equipment.dm
> +	if(prob(15 * severity))
should we have a `min()` here with some kind of default value (created as a define)

2023-04-01 08:52 UTC, SomeoneYouProbablyKnow commented
30 minutes? Damn, considering fugitives spawn later in the round 30 minutes might more than enough. In any case this is cool, although i wish goof finished his stories PR so that we had a framework for this sort of stuff

2023-04-01 16:29 UTC, ATH1909 commented on code/modules/antagonists/fugitive/fugitive_equipment.dm
> +	desc = "An autoinjector containing a stabilized Saturn-X compound. Produced for use in tactical stealth operations, by operatives were presumably comfortable with nudity."
```suggestion
	desc = "An autoinjector containing a stabilized Saturn-X compound. Produced for use in tactical stealth operations by operatives who were presumably comfortable with nudity."
```

2023-04-01 16:30 UTC, ATH1909 commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +	description = "A chemical extract originating from the Saturn-X compound, stabilized and safer for tactical use. After the recipe was discovered it was planned to be put into mass production, but th
```suggestion
	description = "A chemical extract originating from the Saturn-X compound, stabilized and safer for tactical use. After the recipe was discovered, it was planned to be put into mass production, but the program fell apart after its lead disappeared and was never seen again."
```

2023-04-01 16:31 UTC, ATH1909 commented
this guy should probably get a free storage implant or something to hold his other two pens with, or else he'll be very visible while in SaturnX mode because he has to hold the other two pens for later.

2023-04-02 08:16 UTC, Time-Green commented
> this guy should probably get a free storage implant or something to hold his other two pens with, or else he'll be very visible while in SaturnX mode because he has to hold the other two pens for later.

That’s kinda the point though. They’re forced to stash two pens somewhere on the station ahead of time. If they could stay invisible for 30m with no risk, it wouldn’t be much of a fugitive

2023-04-02 13:23 UTC, Shadowflame909 commented
This is cool. I hope to see fugitives more often

2023-04-04 01:49 UTC, san7890 commented on code/modules/antagonists/fugitive/fugitive_equipment.dm
> +	if(prob(15 * severity))
alright wasn't sure

2023-04-06 22:32 UTC, san7890 requested changes

2023-04-06 22:32 UTC, san7890 commented on code/modules/antagonists/fugitive/fugitive_equipment.dm
> +		return
We should return `FALSE` here instead of null to be nicer to consumers.

2023-04-08 01:33 UTC, merged