[MDB IGNORE] UpdatePaths to convert directional pane windows to their proper subtypes, also creates the /south spawner for consistency
tgstation/tgstation pull request #74517
Opened 2023-04-05 00:38 UTC by Jolly-66

## About The Pull Request
Title.

## Why It's Good For The Game
1. This nukes a lot of silly var edits, and cleans up maps
2. The south spawner *isn't* really needed, but having it is nice for consistency and clarity
3. Sometime ago I forget which map but one of them had var edited directional subtypes and that made me cry

## Changelog

:cl: Jolly
fix: Maps internally had the code for the "directional" windows altered a bit. If you see stacked window panes or things look incorrectly, please file a bug report as that isn't intentional!!
/:cl:

2023-04-05 02:24 UTC, Fikou commented
we've gone too far.

2023-04-05 10:32 UTC, Jolly-66 commented
Ita joever for you fikou

2023-04-07 19:31 UTC, san7890 requested changes

2023-04-07 19:31 UTC, san7890 commented on code/game/objects/structures/window.dm
> +
we should really change these over to be `MAPPING_DIRECTIONAL_HELPERS()` with an offset of 0.

2023-04-10 00:20 UTC, merged