Brings back ORM part upgrades
tgstation/tgstation pull request #74513
Opened 2023-04-04 19:33 UTC by Xander3359

## About The Pull Request

Re-adds ORM upgrades, however each part now increases gain by 20% instead of the old 35%, making it not as effective as it previously was.
Also adds upgrading the ORM to 2 new Experiments, adding something for Scientists to gain out of upgrading it.

## Why It's Good For The Game

Miners have been having a harder and harder time, especially as new players, to properly survive Lavaland.
This, on top of helping Miners become more dependent on Station jobs, will make it easier for Miners to properly do the job that so many people complain they can't do well anymore.

It also helps clear up confusion, as the machine has tiered parts, but they currently do absolutely nothing, making it a noob trap to upgrade.

## Changelog

:cl:
balance: The ORM can be upgraded again, and gives a 20% bonus mat/point gain per tier.
/:cl:

2023-04-04 19:39 UTC, san7890 commented
@ArcaneMusic I know you wanted you rein in the material economy a bit, and this feels like a step away from that goal- what do you think.


CC: @JohnFulpWillard since you've done a bit of mining point research which invariably involves ore production

2023-04-04 19:40 UTC, Fikou commented
> Since Miners now have incentive to go through the Cargo shuttle for their equipment, then giving them more points to order more things will help people who bother to work with other departments, get more survival items.

and... it will also help people who dont bother to work with other departments get more survival items? i dont see the point in this argument

2023-04-04 20:00 UTC, Xander3359 commented
> and... it will also help people who dont bother to work with other departments get more survival items? i dont see the point in this argument, it essentially boils down to "makes mining easier" which i dont think is inherently a good thing

People who are good at mining are able to get everything they need on their own, they generally are not the people who need ORM upgrades. I meant that this is more helpful towards the new players, to make them still able to provide materials for the round and have a better chance of surviving.

2023-04-04 20:00 UTC, GuillaumePrata commented
> "makes mining easier"

And in a really boring way.
I'm all for making mining more approchable to new players as it is really badly designed on that field, but just giving them extra points *if* the ORM is upgraded only help miners at the 20ish minute mark, and by that time new miners are probably dead already...

2023-04-04 20:14 UTC, Fikou requested changes
undecided on point multiplier but ore multiplier has to go

2023-04-04 20:17 UTC, JohnFulpWillard commented
I disagree with *only* having point increase, it should be both or nothing.

2023-04-04 20:34 UTC, Pickle-Coding commented
Typically there are around 29,200 ore in lavaland. Miners get an extremely powerful plasmacutter that would make it feasible to mine the entirety of lavaland in a round. I don't think miners are struggling to supply the station if they put an actual attempt in mining.

I'm not a fan of upgrades that just straight up multiply material. No longer a one to one mapping. Could also bring conservation if someone decides to add something such as reverse smelting, turning iron sheets to ore.

2023-04-04 21:10 UTC, moocowswag commented
Not everything needs to be balanced around players playing perfectly. 

Yes resource scarcity is a compelling way to make players interact with eachother, hording whats left, thinking outside the box.

But resource scarcity being likely / norm due to miners not being very good gets old and boring and this alone can cause people to want to just call shuttle and roll for better miners.

At the end of the day it doesnt matter how upgraded the orm is and how many resources the station has access to, it only takes one antag at any printer connected to the silo to drain the entire station of resources and horde it all.

Meanwhile if we have orm upgrades, itl make it easier for the players who go to lavaland with a pickaxe to get the ore that they desperately need to function.

2023-04-04 21:11 UTC, LemonInTheDark commented
We've tried it before and it's never worked.
If you want to make mining more gentle/rewarding after working with the station, expand on tools like the advanced plasmacutter. Just a straight multiplier is really boring, and prone to stupid shit

2023-04-04 21:15 UTC, moocowswag commented
> expand on tools like the advanced plasmacutter. Just a straight multiplier is really boring, and prone to stupid shit

I dont know why but this made me realize there is probably a way to get plasma cutters without even interacting with cargo so I might take back my previous statement if I can figure it out and then get enough people to learn how to do that when they want matts.

2023-04-04 21:16 UTC, Zonespace27 commented
I could see this causing a return to miners not dropping off much/anything until the ORM gets upgraded

2023-04-04 21:16 UTC, ArcaneMusic commented
I am not interested in this PR at this time.

The reasons why:
* As it stands, as previously mentioned, lavaland produces far more minerals that a single round could ever concieveably use in an hour, or even several hours on a good day. This will further encourage arcade style gameplay if we offer more reward for less actual mining.
* Material costs of items in-round are beyond fucked to even consider bringing more ores into the material economy. Items that are critical to round progression are either free or negligable to the crew after a single or more ore deposits. I want to see items getting a real look over in terms of their material costs before we flood the balance even worse.
* Upgrading the ORM being the only step to improving mineral resources is just kinda boring from a gameplay perspective but that's a personal gripe so don't lay as much credence to that.

Closing after 24 hours.

2023-04-04 22:50 UTC, Jolly-66 commented
Honestly if we were to get the ore efficiency upgrades back, it really should only be that, and be minor in the process.

There shouldn't be a "reward" for the ORM being upgraded for miners, but rather, it should encourage miners to and continue to mine, while resources (more-so the rarer shit) are a little more hearty.

And when I say small, I mean a max of 1.2x, or even 1.1x.

2023-04-04 23:23 UTC, Petnavis commented
Ah yes, the "balance for the sake of balance with no mind of how fun it would make the game" police arrive. Yes, I love all the miners dying early on because you guys decided to "Balance" the broken things you've designed and gave to miners by making everything as tedious as possible so all the newbie miners die while the powergamers just get loot and don't mine.

It may not be the thing mining _needs_, but it's definitely something that helps the station as a whole and alleviates the issue that has been created by the powercreep lavaland has gone through throughout the years. Hell, I remember I tried mining a while back after not doing it since my break from a long while ago and finding out you guys decided to force miners to click on the tendrils to get the chest - an absolutely _vital_ change that totally doesn't exist just to make mining more tedious as it already is, especially for new miners.

You've _already_ "incentivized" miners to mine by locking skeleton keys behind points except you've completely missed the fact that some of the best gear miners can get does not require them to mine at all besides their initial load so unless a miner is gunning for something specific from the chests they'll just go out and kill megafauna by cheesing them.

Just remove the point gain so miners still want to mine and let the material increase be. What's the worst thing that happens? There's more HONK mechs? Miners already either die killing megafauna or get their loot and fuck off and never mine again. You all should just make the loot in crates purchasable at insane point prices balancing around points per minute mining while time locking them and do something else with tendrils. At least then miners will be mining more often

In fact, I'm surprised you guys haven't overhauled lavaland again in your goal to make it worse by having megafauna drop materials (like drakes) and having to buy the recipe to craft the item from the vendor at a super marked up price

2023-04-05 00:02 UTC, davethwave commented
While I am not justifying anything. Just letting you know the tendril click thing allows for multiple miners to benefit out of a single tendril kill, allowing multiple chests per tendril if you kill them in a group.

2023-04-05 00:58 UTC, AlamoTurtle commented
I just wish the ORM had cooler upgrades, such as those that cameras can get. A proximity sensor to relink to a nearby ore silo automatically upon either device being disassembled/broken if it's within a certain tile radius, for instance. This PR's cool and all, and I like the idea of being able to do something yourself that is able to make a difference if you use public mining, but the ORM, despite being an integral part of the station, is very lackluster in itself, mostly due to it just being a vacuum/hopper for the ore silo.

2023-04-05 01:58 UTC, tralezab commented
@Petnavis You sound like you genuinely care about the game a lot, you should contribute to the codebase with us. HMU if you need a guide to get your local dev environment set up

2023-04-05 02:07 UTC, tralezab commented
and before you think this is a joke post or something it's not. one of ussss

2023-04-05 03:42 UTC, moocowswag commented
> While I am not justifying anything. Just letting you know the tendril click thing allows for multiple miners to benefit out of a single tendril kill, allowing multiple chests per tendril if you kill them in a group.

Ive killed so many tendrils as a mining borg and couldnt figure out how to bring the chest back to the crew.

2023-04-05 05:32 UTC, Sealed101 commented
>a way to get plasma cutters

upload a plasma cutter design disk to an autolathe :)

2023-04-05 05:37 UTC, moocowswag commented
> > a way to get plasma cutters
> 
> upload a plasma cutter design disk to an autolathe :)

That + breaking down round start plasteel to fuel it

2023-04-07 00:47 UTC, GuillaumePrata commented
You don't even need to mess with the autolathe and designs disks, engineering's protolathe can make plasma cutters and their lathe is definitely the most accessible on the station.

2023-04-13 00:23 UTC, JohnFulpWillard commented
> I dont think thats true i checked the pr. also i use autolathe downloads all the time now when i play so if it was removed and i start playing again, nobody will hear the end of it.

Pretty sure it was, you can't upload nodes to the disks anymore, unless you're able to use techweb disks to upload entire webs to it but I saw nothing to indicate that's a thing.

2023-04-13 04:55 UTC, ArcaneMusic commented
I'm not particularly interested in extra points, and after taking some further feedback, it sounds like the rest of the team isn't either. Sorry 🤷

2023-04-13 04:55 UTC, closed without merging

2023-04-13 08:55 UTC, Xander3359 commented
Alrighty.