Slightly simplifies overlay lighting by just directly rendering it on the lighting plate
tgstation/tgstation pull request #74554
Opened 2023-04-06 14:05 UTC by ChungusGamer666

## About The Pull Request

Instead of doing a weird little stupid filter thing, it just renders on the lighting plate, on top of turf lighting.

## Why It's Good For The Game

Simpler code and visually I don't think it made any difference.
![image](https://user-images.githubusercontent.com/82850673/230401936-015c2721-c5d0-4cce-9c54-c703af66db2c.png)

## Changelog

Not player facing

2023-04-06 17:11 UTC, san7890 commented
CC: @Kylerace on this as well

2023-04-06 22:37 UTC, LemonInTheDark requested changes

2023-04-06 22:37 UTC, LemonInTheDark commented on code/_onclick/hud/rendering/plane_master.dm
> +	blend_mode_override = BLEND_ADD
this breaks colored overlay lights, which is why a filter is used in the first place.
I think you might be able to get a better effect using both a blend multiply and a blend add, but at that point you're just doing the filter again, and we'd also have issues with multiz unless we add a intermediary step.

2023-04-06 22:38 UTC, LemonInTheDark commented
actually I guess it's just not gonna work. I'll leave it open so you can test and yell at me if I'm wrong, but I'll be closing this soon

2023-04-06 23:26 UTC, ChungusGamer666 commented
> actually I guess it's just not gonna work. I'll leave it open so you can test and yell at me if I'm wrong, but I'll be closing this soon

I will test colored overlay lights soon, please do not close this in the meantime.

2023-04-07 18:10 UTC, ChungusGamer666 commented
@LemonInTheDark 
Before this update
![image](https://user-images.githubusercontent.com/82850673/230654349-06194e37-e758-4a86-b898-eeac8d1f5b57.png)
![image](https://user-images.githubusercontent.com/82850673/230654474-55b80217-4b8f-4ba5-a6af-8193836c4169.png)

After this update
![image](https://user-images.githubusercontent.com/82850673/230655522-1aa5e297-8ea9-41f2-9f18-3fb164518b6b.png)
![image](https://user-images.githubusercontent.com/82850673/230655604-5af0c138-d344-4cde-99c0-f85f8c539f77.png)

Sadly, this seems to be in fact a flop. I do think it looks nicer but I'm not sure others would agree.

2023-04-07 18:10 UTC, closed without merging

2023-04-07 18:15 UTC, ChungusGamer666 commented
Applying the filter on the turf lighting plane master instead does work, but at this point I think the final result is essentially the same so it's pointless.
![image](https://user-images.githubusercontent.com/82850673/230657565-790e5fc4-8a8b-4be1-85c5-2f0a3647a815.png)

2023-04-07 18:19 UTC, ChungusGamer666 commented
> Applying the filter on the turf lighting plane master instead does work, but at this point I think the final result is essentially the same so it's pointless. ![image](https://user-images.githubusercontent.com/82850673/230657565-790e5fc4-8a8b-4be1-85c5-2f0a3647a815.png)

Although, thinking about it, there are some advantages to not drawing any lighting on the game plane...

@LemonInTheDark What do you think?

2023-04-07 21:16 UTC, LemonInTheDark commented
can't mask against turfs because of multiz transforms. you could mask and draw the overlays onto the render plate, but it changes the look a bit so I've always been a bit weary of it

2023-04-07 21:18 UTC, ChungusGamer666 commented
i dont see how multiz transforms would be affected by masking, would the mask somehow not get scaled while the plane itself does?

2023-04-07 23:29 UTC, LemonInTheDark commented
you can't draw a "base" plane master (non render plate) onto another base plane master
it'd lead to an effect being double scaled by transforms, which leads to real stupid shit.