Fixes a runtime in simple_animal/hostile
tgstation/tgstation pull request #74706
Opened 2023-04-13 16:04 UTC by vinylspiders

## About The Pull Request

Attempting to fix this flaky test that has been cropping up from the Icebox tests. It is annoying.

From what I can tell, the mob was getting qdeleted while it was doing its loop of finding a target. This can happen at any time, because many simple mobs (including the one causing the issues) get qdeleted on death.

Added some more checks to make sure we don't do certain actions if the mob gets qdeleted midway through execution of its AI routine. It really could happen anywhere so we must be vigilant.

```
create_and_destroy: [02:24:31] Runtime in stack_trace.dm,4: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait (code/controllers/subsystem/timer.dm:583)
proc name:  stack trace (/proc/_stack_trace)
src: null
call stack:
stack trace("addtimer called with a callbac...", "code/controllers/subsystem/tim...", 583)
addtimer(/datum/callback (/datum/callback), 300, 8, null, "code/modules/mob/living/simple...", 595)
the demonic watcher (/mob/living/simple_animal/hostile/asteroid/ice_demon): GainPatience()
the demonic watcher (/mob/living/simple_animal/hostile/asteroid/ice_demon): GiveTarget(the mi-go (/mob/living/simple_animal/hostile/netherworld/migo))
the demonic watcher (/mob/living/simple_animal/hostile/asteroid/ice_demon): FindTarget(/list (/list))
the demonic watcher (/mob/living/simple_animal/hostile/asteroid/ice_demon): AIShouldSleep(/list (/list))
the demonic watcher (/mob/living/simple_animal/hostile/asteroid/ice_demon): handle automated action() at stack_trace.dm:4
```

On top of that, there is signal handling in place to LoseTarget() when a mob that is already a target gets qdel'd and sends `COMSIG_PARENT_QDELETING`. Shown below.

https://github.com/tgstation/tgstation/blob/4c48966ff80915ee0b4f796994a0ab6616cab31b/code/modules/mob/living/simple_animal/hostile/hostile.dm#L655-L666

However there is nothing stopping a target that is not null but that has been qdeleted from being considered as a target in the first place.

This PR just aims to fix that problem by making sure that  a) a hostile ai that gets qdeleted midway through does not keep doing stuff that can cause issues and b) an atom that is being qdeleted never makes its way into the targets list of a hostile ai.

Simple mobs/AI are due for a wider refactor honestly but this really ought to be done in the meantime so we don't get spammed by CI failures over nonsense.

Fixes https://github.com/tgstation/tgstation/issues/73032
Fixes https://github.com/tgstation/tgstation/issues/74266
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/18964
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/19749
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/18964
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/19322
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/18974
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/19296
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/19294

## Why It's Good For The Game

Bugfix, stops the icebox test from failing as much.

## Changelog
:cl:
fix: fixes hostile mobs sometimes being able to target an atom that has been marked for deletion and then becoming confused, and in a similar vein fixes mobs sometimes still running their AI while being marked for deletion. 
/:cl:

2023-04-13 17:50 UTC, ShizCalev commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +		return 0
Is this not true/false?

2023-04-14 18:47 UTC, san7890 requested changes
yeah simple animals are weird but until we go over to basic we may as well keep dressing up that pig

2023-04-14 18:47 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +		return FALSE
```suggestion
	if(isturf(the_target) || QDELETED(the_target) || QDELETED(src)) // bail out on invalids
		return FALSE
```

QDELETED will do effectively the same thing as `!` in this instance, so let's just do it right and condense all the checks

2023-04-14 18:47 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +	if(!QDELETED(target) && target != null)
```suggestion
	if(!QDELETED(target))
```

QDELETED checks `isnull()` so this appears to be redundant.

2023-04-14 18:47 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +			. = TRUE
```suggestion
			return TRUE
```

2023-04-14 18:47 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
>  				toggle_ai(AI_ON) //Wake up for more than one Life() cycle.
```suggestion
				toggle_ai(AI_ON) //Wake up for more than one Life() cycle.
				return TRUE
```

may as well fix this while we're in the area. if we runtime we really shouldn't be returning a "positive" result anyways

2023-04-14 18:47 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +				. = FALSE
```suggestion
				return FALSE
```

2023-04-16 03:31 UTC, merged