Tackling critical failure modifiers now take into account your suit and head's melee protection, not typechecks
tgstation/tgstation pull request #74797
Opened 2023-04-17 17:46 UTC by carlarctg

## About The Pull Request

Tackling critical failure modifiers now take  into account your suit and head's melee protection, not typechecks.

Total protection is the melee armor halved, as it's reasonably close to the hard hat's value original final protection value (6, now 15/2 = 7.5). Can be reduced if requested.

## Why It's Good For The Game

The purely hypothetical scenario in which someone could accidentally tackle into an airlock and become a permanent paraplegic while wearing berserker armor with the hood on is no longer possible. This proc shouldn't check for types, just melee protection in general, else from the player side of things some items just arbitrarily protect for no good reason.

## Changelog

Still not sure what this would count as. Fix?

:cl:
code: Tackling critical failure modifiers now take into account your suit and head's melee protection, not typechecks
/:cl:

2023-04-17 18:13 UTC, Fikou commented
its a hardhat it should protect u mang

2023-04-17 21:51 UTC, carlarctg commented
> This make Beretcurity safe at tackling. Huge sin.
> 
> Memery aside, being helmet locked is a nice balance lever, only caring about armor just increases the value of the highly armored pieces of headwear, while removing value from lower end helmets.

Except I got paraplegic with a berserker _helmet_. How is a player meant to tell the difference between a helmet that's subtyped off security helmets and one that's subtyped off something else? It just fucks them over and makes people even less likely to use the fun tackling gloves. 

On the beret thing, I can very easily make it so that there's a 'floor' above a certain amount of melee protection for it to count. Like, say, you need at least 15 melee protection for it to defend, if you want.


All I want in this PR is consistency and not needing to use friggin typechecks

2023-04-17 21:52 UTC, carlarctg commented
> its a hardhat it should protect u mang

whuh? It does protect you now as well. Hard hats have 15 melee armor so they're still just as useful in resisting a smash.

2023-04-18 00:39 UTC, GuillaumePrata commented
> On the beret thing, I can very easily make it so that there's a 'floor' above a certain amount of melee protection for it to count. Like, say, you need at least 15 melee protection for it to defend, if you want.

You can't do that because berets have the same armor values as the default security helmets.

I agree on the clarity for the user, what makes a tackling safer for themselves is not explained well IC.

But right now, if you see a security officer with riot gear you know they might be a tackler user and this interaction between Antagonists trying to predict and dodge tackles is the fun side of the feature, more if security risks their safery and tries to surprise someone by not wearing any tackling enchancement gear for the unexpected factor.
If it is just armor value, tackling becomes something invisible and that you can't predict and interact, there will be no more mind games around tackling.

2023-04-18 05:10 UTC, ATH1909 commented
> But right now, if you see a security officer with riot gear you know they might be a tackler user. This interaction between Antagonists trying to predict/dodge tackles is the fun side of the feature, more if security risks their safery and tries to surprise someone by not wearing any tackling enchancement gear for the unexpected factor. If it is just armor value, tackling becomes something invisible and that you can't predict and interact, there will be no more mind games around tackling.

you can... see the gloves, no? optimizing tackling (instead of just yeeting yourself and praying) also comes with some pretty significant visual tells (gigantism, riot armor, etc.).

helmets are a part of standard sec gear, so even if helmets were a major tell, how are you supposed to tell a tackler apart from someone who simply hasn't switched off of the default sec loadout?

2023-04-18 10:38 UTC, carlarctg commented
> > On the beret thing, I can very easily make it so that there's a 'floor' above a certain amount of melee protection for it to count. Like, say, you need at least 15 melee protection for it to defend, if you want.
> 
> You can't do that because berets have the same armor values as the default security helmets.
> 
> I agree on the clarity for the user, what makes a tackling safer for themselves is not explained well IC.
> 
> But right now, if you see a security officer with riot gear you know they might be a tackler user. This interaction between Antagonists trying to predict/dodge tackles is the fun side of the feature, more if security risks their safery and tries to surprise someone by not wearing any tackling enchancement gear for the unexpected factor. If it is just armor value, tackling becomes something invisible and that you can't predict and interact, there will be no more mind games around tackling.



> > On the beret thing, I can very easily make it so that there's a 'floor' above a certain amount of melee protection for it to count. Like, say, you need at least 15 melee protection for it to defend, if you want.
> 
> You can't do that because berets have the same armor values as the default security helmets.
> 
> I agree on the clarity for the user, what makes a tackling safer for themselves is not explained well IC.
> 
> But right now, if you see a security officer with riot gear you know they might be a tackler user. This interaction between Antagonists trying to predict/dodge tackles is the fun side of the feature, more if security risks their safery and tries to surprise someone by not wearing any tackling enchancement gear for the unexpected factor. If it is just armor value, tackling becomes something invisible and that you can't predict and interact, there will be no more mind games around tackling.

How about this: Changing how the proc works so that the crit fails can still happen, but there just won't be any permanent damage as long as you have hardhat or better protection.

2023-04-29 18:30 UTC, MrMelbert requested changes
I like this PR but the numbers are bad

2023-05-17 00:05 UTC, closed without merging