UDDERAPALOOZA: Moo-ving the udder component to the atom level, and subtyping the living requirements for a more dairy-able and cow-laborative codebase!
tgstation/tgstation pull request #74815
Opened 2023-04-18 02:27 UTC by tralezab

## About The Pull Request 🥛 

Refactors the cow component to be atom level since surprisingly, only two checks were stopping it from going lower. I like it! It’s udderly amazing! And instead of doing that pattern I really don’t like where you check the types of 10 billion items and conditionally hook signals, I’ve just made the living requirements a subtype. This way, it’s more moo-dular and easier to maintain. No bull!

## Why It's Good For The Game

Add an udder to a toolbox

## Changelog

:cl:
refactor: udder component is now atom level, with a subtype for living requirements
/:cl:

2023-04-18 02:29 UTC, tralezab commented
I know some people don't like component subtypes, but the alternative is uglier and there are no sacred cows when it comes to making clean code

2023-04-18 02:33 UTC, san7890 requested changes
nits

2023-04-18 02:33 UTC, san7890 commented on code/datums/components/udder.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-04-18 02:33 UTC, san7890 commented on code/datums/components/udder.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-04-18 02:33 UTC, san7890 commented on code/datums/components/udder.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-04-18 02:34 UTC, tralezab commented
> nits

Don't have a cow! I'll get right on it.

2023-04-18 03:59 UTC, the-orange-cow commented
Something about this seems udderly cursed.

2023-04-18 05:01 UTC, tralezab commented
Cow puns till the cows come home

2023-04-18 13:21 UTC, Fikou commented on code/datums/components/udder.dm
> +
i'd rather you make these a callback or an istype() check

2023-04-18 17:27 UTC, Wallemations commented
I feel like half of the reason you made this PR was just for the puns

2023-04-18 19:48 UTC, Ziiro commented
cowa-pun-ga, dude

2023-04-25 18:23 UTC, Addust commented
i never want to see you attempt any form of comedy **ever again**

2023-05-11 00:14 UTC, closed without merging