Adds book burning
tgstation/tgstation pull request #74873
Opened 2023-04-20 15:10 UTC by ChungusGamer666

## About The Pull Request

For some reason, unlike other paper items, you couldn't ignite books with a lighter or other hot item.
Now, you can!

## Why It's Good For The Game

Consistency. 
~~Burning copies of WGW.~~

## Changelog

:cl:
add: Books can now be burned just like any other
/:cl:

2023-04-20 16:04 UTC, Helg2 commented
What about Codex Cicatrix? Its not pathed like a book from what i remember

2023-04-20 16:23 UTC, ChungusGamer666 commented
> What about Codex Cicatrix? Its not pathed like a book from what i remember

yeah it ain't, but it ain't flammable either so it doesn't matter

2023-04-20 23:32 UTC, Wallemations commented
I think it would be funny if the Bible (and all of its subtypes) had some sort of effect when you burned them, not anything too big but at least some form of visual effect?

2023-04-21 00:09 UTC, Helg2 commented
Does flame bible burns?

2023-04-21 00:21 UTC, ChungusGamer666 commented
> I think it would be funny if the Bible (and all of its subtypes) had some sort of effect when you burned them, not anything too big but at least some form of visual effect?

Hilarious suggestion, I have something in mind but it will have to be done in a separate PR after this one

2023-04-21 00:21 UTC, ChungusGamer666 commented
> Does flame bible burns?

It probably does, I don't think any bible is fireproof.
Honestly, it would be fitting if anything.

2023-04-21 04:05 UTC, OneAsianTortoise commented
No way, fahrenheit 451

2023-04-21 19:09 UTC, san7890 requested changes
it's reallllyyyy silly to have a null/TRUE dichotomy so let's at the very least patch out the dot operator and make a proper TRUE/FALSE boolean proc. if you are spooked about runtimes in this proc (lol) then just use `return .` in those spots

2023-04-21 19:09 UTC, san7890 commented on code/modules/paperwork/paper.dm
>  	. = TRUE
this makes the whole proc really fucking silly so while we're here let's fix this in the best way possible

```suggestion
```

2023-04-21 19:09 UTC, san7890 commented on code/modules/paperwork/paper.dm
> +		return
```suggestion
		return FALSE
```

2023-04-21 19:09 UTC, san7890 commented on code/modules/paperwork/paper.dm
>  		return
```suggestion
		return FALSE
```

2023-04-21 19:09 UTC, san7890 commented on code/modules/paperwork/paper.dm
>  		return
```suggestion
		return TRUE
```

2023-04-21 19:09 UTC, san7890 commented on code/modules/paperwork/paper.dm
> +	fire_act(attacking_item.get_temperature())
```suggestion
	fire_act(attacking_item.get_temperature())
	return TRUE
```

2023-04-21 19:38 UTC, DATA-xPUNGED commented
THANK YOU

2023-04-21 20:53 UTC, ATH1909 commented
have you tested this with, say, hollow bibles?

2023-04-21 22:11 UTC, ChungusGamer666 commented
> have you tested this with, say, hollow bibles?

No i haven't

2023-04-22 12:21 UTC, Hardly3D commented
An amazing addition. I'd love to see this added to paintings to deal with copies of awooga art.

2023-04-23 23:26 UTC, merged