[MDB Ignore] Adds a unit test for typepaths that are required to be mapped onto each station map
tgstation/tgstation pull request #74985
Opened 2023-04-26 04:30 UTC by MrMelbert

## About The Pull Request

Inspired by #74967 and #68459 , and the fact that Tramstation regresses very often - 

Adds a unit test, `required_map_items`, which ensures that certain typepaths which should definitely be mapped onto every map is mapped onto every map 

It can also be used to ensure that items which should not be mapped in multiple times are not, among other things. 

I included a few examples - 
- Min 1, max inf of each head of staff stamps
- Min 1, max 1 departmental order consoles
- Min 1, max inf comms console
- Min 1, max 1 Pun Pun
- Min 1, max 1 Poly
- Min 1, max 1 Ian

If, in the future, a mapper decides they (for some reason) do not want a certain previously-required item on their map, the test can be adjusted such that it allows excluding or something, but currently it should be for items which require conscious thought about. 

#### QA: Why not make this a linter?

I attempted to make this a linter before realizing two things
1. Someone might make a spawner which spawns the items, or they might get placed in a locker, in any case this accounts for everything on init
2. Linters run on every map, non-station maps included

So I went with a test

## Why It's Good For The Game

#50468
#61013
#74967

Why is it always the CMO stamp?

## Changelog

Not necessary (unless I find a map missing something, then this will be updated)

2023-04-26 04:41 UTC, JohnFulpWillard commented on code/modules/unit_tests/required_map_items.dm
> +	expected_types += /mob/living/basic/pet/dog/corgi/ian
There's also ``/mob/living/basic/pet/dog/corgi/puppy/ian``

2023-04-26 06:05 UTC, Rex9001 commented
At last, there will be no fourth lack of CMO stamp pr

2023-04-26 11:46 UTC, ZephyrTFA approved these changes
Don't forget to put the CMO stamp onto Tramstation

2023-04-26 12:36 UTC, Rex9001 commented
> Don't forget to put the CMO stamp onto Tramstation

https://github.com/tgstation/tgstation/pull/74967

2023-04-27 20:14 UTC, Mothblocks commented
this really really really should not include debug maps

2023-04-27 21:36 UTC, Mothblocks commented
@MrMelbert My idea was two tests. One for fluff items and one for actual important mechanics. Something like every boss stamps shouldn't be needed on Runtime.

2023-05-02 04:24 UTC, Zytolg commented
There are a million and one things you can forget to add or fail to consider when making a map. 
For instance: station pets needing to be located within their departments (sorry birdboat!) or the captain needing their medals. 
This is a great idea provided it stays current with a list of strictly necessary items.

2023-05-04 20:47 UTC, san7890 requested changes

2023-05-04 20:47 UTC, san7890 commented on code/modules/unit_tests/required_map_items.dm
> +	ASSERT(length(GLOB.required_map_items) > 0, "No required map items were found!")
```suggestion
	TEST_ASSERT(length(GLOB.required_map_items) > 0, "No required map items were found!")
```

since it's in the context of a test

2023-05-04 20:47 UTC, san7890 commented on code/modules/unit_tests/required_map_items.dm
> +	ASSERT(length(required_map_items) == 0, "The following paths were found in required map items, but weren't checked: [english_list(required_map_items)]")
```suggestion
	TEST_ASSERT_EQUAL(length(required_map_items), 0, "The following paths were found in required map items, but weren't checked: [english_list(required_map_items)]")
```

this should work? i don't know if this is too ugly a message so it's probably okay to just do a TEST_ASSERT

2023-05-04 21:20 UTC, merged