Removes the random prosthetic quirk from the character preview page
tgstation/tgstation pull request #75050
Opened 2023-04-30 03:18 UTC by vinylspiders

## About The Pull Request

The prosthetic limb quirk chooses a random limb to make prosthetic at roundstart. 

It was extremely buggy with the way quirks are displayed and the way the dummy preview works and would frequently carry over to other characters and not update correctly. 

<details>
<summary>Eventually you end up getting this if you switch enough times
</summary>

![hDq983y2T0](https://user-images.githubusercontent.com/13398309/235334283-d4fc4c1f-c1de-4460-b6f7-7ef95a587cb4.gif)

</details>

I started fixing the issue when I realized this really shouldn't be shown on the dummy to begin with, because what you see on the dummy will not necessarily be what you get at roundstart. It's misleading. 

I did however leave part of the fix that I was working on, because I think it is useful to be able to undo the quirk via adminnery.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/issues/20791

## Why It's Good For The Game
## Changelog
:cl:
fix: prosthetic limb quirk will no longer display a prosthetic on your character preview because it is buggy and hardly ever matches what you end up getting upon spawning
code: removing the prosthetic limb quirk will restore your original limb
/:cl:

2023-04-30 03:49 UTC, san7890 requested changes

2023-04-30 03:49 UTC, san7890 commented on code/datums/quirks/negative_quirks.dm
> +	var/obj/item/bodypart/old_limb
new vars should go after vars declared on parent, can you re-arrange this since you're adding a new var in this PR?

2023-05-01 21:56 UTC, Jezzared commented
Can we make this a pref for a specific limb and then draw that limb specifically?

2023-05-02 01:31 UTC, Jezzared commented
> > Can we make this a pref for a specific limb and then draw that limb specifically?
> 
> 'We' can, but I'm certainly not going to. Yes it would be neat, but--
> 
> Adding a whole limbs pref UI is beyond the scope of this PR and not something I'm really interested in doing/have the time for right now. That is a whole different thing from this quirk.

Fair!

2023-05-02 02:13 UTC, merged