Minor updates to the Occupational Corruption Device
tgstation/tgstation pull request #75122
Opened 2023-05-02 19:27 UTC by Rhials

## About The Pull Request

This PR makes a few changes to the Occupational Corruption Device, the job-specific traitor item that allows you to summon a bureaucratic error event. Largely untouched for years, even across the change from standard to progression traitor.

It now triggers directly from the uplink, which means no more self-deleting remote. Now, it functions like the comms blackout/grid check "viruses".

This, however, led me to a major problem -- No remote means there is no longer an "Occupational Corruption Device", abandoning the pun intended by the original author.

To remedy this, the Occupational Corruption Device is now the "Organic Capital Disturbance virus". Different words, same stupid acronym. (The description is a bit more direct now too).

![image](https://user-images.githubusercontent.com/28870487/235769244-7632b5f7-d3eb-4f92-8128-a20f5bec36d0.png)

The event running has been moved to the force_event() helper, which I must have missed in #74904.

There is now a paltry 5 minute progression timer behind it, like the clown car.
## Why It's Good For The Game

Brings this traitor item more mechanically/codeilly in line with the other "buy a random event" options.

This is an item that's value scales with how early into the round it is used, but I feel like having a minor grace period would be fair to players who miss roundstart. 
## Changelog
:cl:
balance: The Occupational Corruption Device (now the "Organic Capital Disturbance" virus) now triggers directly from the uplink, rather than spawning a remote.
balance: The OCD now has a very small progression requirement behind it.
/:cl:

2023-05-03 03:44 UTC, san7890 commented
would you kindly spell out what "OCD" stands for in at least one of your changelog entries - it's one of my pet peeves when people don't elaborate on what their acronym means. thanks

2023-05-03 03:46 UTC, san7890 requested changes

2023-05-03 03:46 UTC, san7890 commented on code/modules/uplink/uplink_items/job.dm
> -	surplus = 5
why'd you nuke the surplus value to 0? i don't think it's a bad change and this is already a Balance PR but why'd you do it

2023-05-04 19:46 UTC, san7890 commented on code/modules/uplink/uplink_items/job.dm
> -	surplus = 5
ah okay then

2023-05-05 04:46 UTC, JohnFulpWillard commented on code/modules/uplink/uplink_items/job.dm
> +	name = "Organic Capital Disturbance virus"
```suggestion
	name = "Organic Capital Disturbance Virus"
```
I think it looks bad otherwise

2023-05-10 18:53 UTC, merged