Makes organ harvester drop circuitboard on deconstruct.
tgstation/tgstation pull request #75195
Opened 2023-05-06 04:38 UTC by Xander3359

## About The Pull Request
Closes https://github.com/tgstation/tgstation/issues/75160
Nulls the circuit board so it doesn't get QDEL by /destroy after deconstruct.

## Why It's Good For The Game
Bugfix

## Changelog

:cl:
fix: Organ harvester board drops on deconstruct.
/:cl:

2023-05-06 06:32 UTC, SyncIt21 commented
I'm confused. Since you are applying this fix to `_machinery.dm` file shouldn't that mean all machines don't drop circuit boards when deconstructed? why is this problem unique only to organ harvester? Something doesn't add up

2023-05-06 06:51 UTC, SyncIt21 commented
Ohhh i get it now, It's a big indirection, in `deconstruct()` It start's when we move the circuit board out of the machine here
https://github.com/tgstation/tgstation/blob/046a5cbe01e5c8a06337b7fbdc376e4765e94b18/code/game/machinery/_machinery.dm#L817

Since the circuit board is part of the machine's contents, when it gets moved out it triggers the machines `Exited()` proc. This nulls the circuit board and removes it from the machines component parts
https://github.com/tgstation/tgstation/blob/046a5cbe01e5c8a06337b7fbdc376e4765e94b18/code/game/machinery/_machinery.dm#L1160-L1162

So that's why all machines properly deconstruct except for the organ harvester because the organ harvester overrides the `Exited()` but it doesn't call it's super proc
https://github.com/tgstation/tgstation/blob/046a5cbe01e5c8a06337b7fbdc376e4765e94b18/code/game/machinery/harvester.dm#L192-L195
It's not calling `return ..()`. So this is the actual fix, make sure to add that along with your changes as well because we don't want to qdel an null object.

I don't like the way this was set up with all this indirection when it should have been a simple fix, maybe we should just not null the circuit when it's moved out of the machine because this changes the length of this for loop.

https://github.com/tgstation/tgstation/blob/046a5cbe01e5c8a06337b7fbdc376e4765e94b18/code/game/machinery/_machinery.dm#L811

mid iteration and I already had this problem with the lighting subsystem PR. @LemonInTheDark maybe you have experience with this?

2023-05-06 08:49 UTC, Mothblocks commented on code/game/machinery/_machinery.dm
> +	if(!isnull(circuit))
you do not need this check, QDEL_NULL(null) is not only benign but something lemon wants to make faster in the future

2023-05-07 19:39 UTC, Mothblocks requested changes
Because `_machinery.dm` now has no meaningful changes, I'd like for you to not touch it in this PR

2023-05-07 20:01 UTC, Xander3359 commented
Did I fuck up checks? It looks like messages or something is breaking but I haven't touched that at all.

2023-05-07 20:05 UTC, Mothblocks commented
Merge skew, not your fault

2023-05-08 21:18 UTC, merged