Requests console helpers
tgstation/tgstation pull request #75224
Opened 2023-05-07 14:38 UTC by Profakos

## About The Pull Request

This PR adds mapping helpers for requests consoles. Two of them set up if the console can receive ore updates, and if it can make announcements, flipping their relevant variables to TRUE. The other three adds the consoles to their relevant department console lists during late initialize. This allowed me to remove three variables directly from the consoles themselves.

![image](https://user-images.githubusercontent.com/2676196/236684121-3170259c-b4a0-4b1a-869c-40beae45eff6.png)

They look like this, with their first letter shown, except for announcements, which shows a megaphone due to assistance already having taken A.

## Why It's Good For The Game

Less var edits, easier to see a console's type at a glance.

## Changelog

:cl:
qol: Most request console varedits have been moved to mapping helpers.
/:cl:

2023-05-07 15:26 UTC, Profakos commented
> Runtime in mapping_helpers.dm,1241: Cannot read null.type
  proc name: LateInitialize (/obj/effect/mapping_helpers/requests_console/LateInitialize)
  src: the request console supplies r... (/obj/effect/mapping_helpers/requests_console/supplies)
  src.loc: the science crate (/obj/structure/closet/crate/science)
  call stack:
  the request console supplies r... (/obj/effect/mapping_helpers/requests_console/supplies): LateInitialize(null)

A crate ate my mapping helper??

2023-05-07 15:41 UTC, Profakos commented
![image](https://user-images.githubusercontent.com/2676196/236687680-7605ed0d-35e2-4e43-b3a2-5af2f48ac071.png)

Yeah its the anchored crate in deltastation robotics. Apparently crates suck up everything under atom/movable, so it will eat mapping helpers too. I am afraid moving the console would just mask the issue.

2023-05-07 17:01 UTC, Profakos commented
I elected to do the simplest solution for now, which is anchoring mapping helpers, same way as jobstart landmarks are anchored. I don't want to increase the scope of this PR to refactor how crates eating items during initialization works.
In the meanwhile, @CoiledLamb offered to make new sprites for the mapping helpers, so I am leaving it drafted until they are ready.

2023-05-08 23:36 UTC, Profakos commented
New sprites are done! Ready for review.

2023-05-15 22:56 UTC, san7890 requested changes
I was wondering when someone would finally take care of these! I'll just assume direct control since these are just very nitty

2023-05-15 22:56 UTC, san7890 commented on code/modules/mapping/mapping_helpers.dm
> +	return
```suggestion
```

redundant

2023-05-15 22:56 UTC, san7890 commented on code/modules/mapping/mapping_helpers.dm
> +	return
```suggestion
```

2023-05-15 22:56 UTC, san7890 commented on code/modules/mapping/mapping_helpers.dm
> +	return
```suggestion
```

2023-05-15 22:56 UTC, san7890 commented on code/modules/mapping/mapping_helpers.dm
> +	return
```suggestion
```

2023-05-15 22:56 UTC, san7890 commented on code/modules/mapping/mapping_helpers.dm
> +	return
```suggestion
```

2023-05-15 23:08 UTC, merged