New air alarm sprite take two
tgstation/tgstation pull request #75262
Opened 2023-05-08 12:48 UTC by MTandi

![air_alarm](https://user-images.githubusercontent.com/3625094/236828143-e08a8694-2315-4af7-a118-6eb8c52f21bb.png)

## About The Pull Request

Reopen of #74932 

Resprites the air alarm and adds a new sprite that will be needed for an air alarm that is remotely connected to a sensor via #75187 

## Why It's Good For The Game

Newer, more compact sprite. 

It will make it easier for map makers to stack remotely connected air alarms on a tile to make an air monitoring wall.

## Changelog

:cl:
image: New air alarm sprite
/:cl:

2023-05-08 13:16 UTC, zxaber commented
Does this still make it so north-facing air alarms no longer flip?

2023-05-08 13:26 UTC, MTandi commented
> Does this still make it so north-facing air alarms no longer flip?

Yes, like APC.

![image](https://user-images.githubusercontent.com/3625094/236836354-727d5119-651d-4534-bce1-5ed37cc4543a.png)

2023-05-08 13:47 UTC, zxaber commented
Still heavily dislike that. I dislike it for APCs too, but they're close to being square so the difference is minor.

Rotating Air Alarms is super helpful when you can see multiple rooms and need to find the Air Alarm to *this* room because oh fuck it's siphoning and people are gonna die and also they're gonna blame you because EMPs are a bitch.

Considering how unique the sprite is (like the old sprite), I can't really see a good argument *against* the rotation effect.

2023-05-08 14:02 UTC, MTandi commented
> Still heavily dislike that. I dislike it for APCs too, but they're close to being square so the difference is minor.
> 
> Rotating Air Alarms is super helpful when you can see multiple rooms and need to find the Air Alarm to _this_ room because oh fuck it's siphoning and people are gonna die and also they're gonna blame you because EMPs are a bitch.
> 
> Considering how unique the sprite is (like the old sprite), I can't really see a good argument _against_ the rotation effect.

I did it for consistency, because it looks weird when supply request consoles, APCs, fire extinguisher cabinets and most of other wall equipment is not rotated, while air alarm is. Also it's bad to rotate something that has text.

It may be true that the directional one works better in this particular edge case of a AI role, but I don't think that it justifies to add 4 times more sprites and make things look worse for everyone else.

Also the Wallening is comming, this sprite will be replaced and you will have even more issues finding and clicking that air alarm. So this is mostly a temporary thing or for downstreams that won't accept Wallening.

2023-05-09 12:00 UTC, Dorsisdwarf commented
Amazing looking sprite, a perfect update to an old icon that was more than showing its age

2023-05-11 02:13 UTC, potato1234x commented
this sprite is eye candy

2023-05-12 07:35 UTC, NotSoEpikName commented
no way TG Sriters can do realy good shit unstead of bullshit?
imposible
yet still hey good work i like the sprites

2023-05-23 00:57 UTC, san7890 requested changes
damn this PR got buried, just one nit

2023-05-23 00:57 UTC, san7890 commented on code/modules/atmospherics/machinery/air_alarm/_air_alarm.dm
> +	. = ..()
```suggestion
	return ..()
```

2023-05-23 21:33 UTC, MTandi commented
> damn this PR got buried, just one nit

Please merge it, I can't handle the urge to keep polishing my PRs while they're open for too long.

2023-05-23 21:53 UTC, zxaber commented
Please make them rotate, I don't know I can deal with fire alarms take two.

2023-05-23 22:08 UTC, MTandi commented
> Please make them rotate, I don't know I can deal with fire alarms take two.

Man, it's one of the main reasons for this PR. I made the sprite smaller and close to the edge of wall to make sure that you won't have issues with finding air alarm in the room. APC already follows the same logic and this being non-directional is for consistency.

And object overlapping is a general mapping issue, not related to air alarms. Mappers should avoid placing wall objects on the same tile, even on the opposite sides of the wall, and we need to resolve these separately.

Please try how this works and make a PR with directions if it really feels much worse.

2023-05-23 22:17 UTC, zxaber commented
>Please try how this works and make a PR with directions if it really feels much worse.

Alright, this is fair. I will give it an honest trial.

2023-05-23 22:41 UTC, zkxs commented
Given @zxaber's concerns with how this might look for AI or other players who can see multiple sides of a wall, I figured I'd load up MetaStation with this PR merged and see how things look as an AI. I've attached some screenshots of areas I found interesting due to their high air alarm density. 

<details>
<summary>A bunch of screenshots (click to expand)</summary>

You fool! Now my single comment takes up tremendous quantities of vertical space in the page!

![EVA Storage](https://github.com/tgstation/tgstation/assets/1807509/f74b49af-307a-49da-b54e-335d28fde1e8 "EVA Storage")

![Virology](https://github.com/tgstation/tgstation/assets/1807509/18449843-b0df-4a62-ba02-c477aa7cefd3 "Virology")

![Permabrig](https://github.com/tgstation/tgstation/assets/1807509/970f87d6-10d9-4c9f-a2d4-bdcafe199fe0 "Permabrig")

![Freezer](https://github.com/tgstation/tgstation/assets/1807509/d0ec6dec-6a13-436e-94c1-50aa0c76b79b "Freezer")

![Grav gen](https://github.com/tgstation/tgstation/assets/1807509/30db26fc-8be3-41d5-8abb-cd1dc865aad1 "Grav gen")

</details>

Surprisingly, the side of the walls air alarms are on is much less ambiguous than I'd thought it would be, although in hindsight I shouldn't be because during my AI gameplay I don't struggle too much with APCs, and it's basically the same situation as this.

2023-05-27 22:39 UTC, merged