Adds a blacklist for putting guns in turrets
tgstation/tgstation pull request #75263
Opened 2023-05-08 13:03 UTC by Thunder12345

## About The Pull Request

Fixes #75197

Adds a global list of gun types banned from being added to turrets. Adds dueling pistols to the banned list as they can freely round remove people when in turrets without the usual restrictions.

## Why It's Good For The Game

Instakill turrets are an undesirable outcome.

## Changelog

:cl:
fix: Dueling pistols can no longer be fitted in turrets to instantly kill people.
/:cl:

2023-05-08 13:25 UTC, Fikou commented on code/__DEFINES/is_helpers.dm
> +#define isForbiddenTurretGun(O) (is_type_in_typecache(O, GLOB.forbidden_turret_guns))
```suggestion
#define is_forbidden_turret_gun(O) (is_type_in_typecache(O, GLOB.forbidden_turret_guns))
```

2023-05-08 18:36 UTC, MrMelbert requested changes

2023-05-08 23:36 UTC, optimumtact commented
this should probably be an allow list instead of a deny list

2023-05-13 12:23 UTC, Fikou requested changes

2023-05-13 12:23 UTC, Fikou commented on code/game/machinery/porta_turret/portable_turret_construct.dm
> +				if(E.gun_flags & TURRET_INCOMPATIBLE)
you must use descriptive variable names, not E.

2023-05-18 22:04 UTC, Fikou commented
good enough

2023-05-18 22:04 UTC, merged