Fixes spiderlings having no density
tgstation/tgstation pull request #75381
Opened 2023-05-12 03:34 UTC by SethLafuente

Basically making it so they stop other big creatures and each other from moving

## About The Pull Request
they block each other and bigger mobs they arent meant to structure spiderlings didn't do this for a reason

## Why It's Good For The Game

## Changelog

:cl:
fix: fixes spiderlings having density
/:cl:

2023-05-12 03:38 UTC, ZephyrTFA requested changes
I highly disagree with them being non dense.
You should instead make it to where they allow other spiders to pass through them.

2023-05-12 03:39 UTC, SethLafuente commented
> I highly disagree with them being non dense. You should instead make it to where they allow other spiders to pass through them.

gona be honest thats pretty fucking stupid 

1. Cockroaches AND MICE are not dense same kind of bug should apply
2. this is also a problem with every single mob not only spiders a fucking spiderling stops a whole as human from moving

2023-05-12 03:42 UTC, SethLafuente commented
> I highly disagree with them being non dense. You should instead make it to where they allow other spiders to pass through them.

![image](https://github.com/tgstation/tgstation/assets/84478872/ed390ca5-36fb-4944-acfa-c66bf6a14690)
![image](https://github.com/tgstation/tgstation/assets/84478872/b50dcc69-acf2-4427-b86b-2958dfce6a1d)

2023-05-12 03:45 UTC, moocowswag commented
Seth, you are referring to the very tiny black spiders or the very large player spiders

2023-05-12 03:45 UTC, SethLafuente commented
> Seth, you are referring to the very tiny black spiders or the very large player spiders

very tiny spiderlings

2023-05-12 03:46 UTC, moocowswag commented
watch im gonna remove the do not merge label

2023-05-12 09:58 UTC, Jacquerel commented
Even if you think it is self-explanatory please actually fill in why this is good for the game.
Doing so quite likely would have avoided any of the above comments from happening.

2023-05-13 17:26 UTC, SethLafuente commented
so is this gona get merged or...

2023-05-16 23:58 UTC, merged