Dump honeycomb into the reagent grinder
tgstation/tgstation pull request #75433
Opened 2023-05-14 04:05 UTC by Peliex

## About The Pull Request

Added second function call to check for honeycomb in bag inventory, food items are prioritized.
This allows for the all-in-one grinder to accept honeycomb in bags, instead of having to dispense them from the bag and insert them into the grinder one by one.

## Why It's Good For The Game

This is a simple quality of life change that is intended only to help improve the bee mechanics slightly, as they are not exactly well understood or documented and them being able to stack in plant bags but not dispense into the grinder is inconsistent and unintuitive.

## Changelog

:cl:
qol: all-in-one grinders now accept honeycomb from bags
/:cl:

2023-05-15 03:49 UTC, san7890 requested changes

2023-05-15 03:49 UTC, san7890 commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +				holdingitems[i] = TRUE
This is suspicious, does `/obj/item/food/grown` stuff still work? It doesn't look like it'll be outputting the message anymore for grown items, let me know if I'm going senile.

2023-05-15 04:46 UTC, san7890 commented
feel free to hit the "Ready for review" button when you've addressed the above in one way or another

2023-05-16 03:34 UTC, closed without merging

2023-05-16 03:36 UTC, Peliex commented
i'm going to make additional revisions and push a more substantial PR, I will fix the logic so that the message displays properly in both scenarios