Kuma tgss13test
tgstation/tgstation pull request #75487
Opened 2023-05-17 01:25 UTC by KingkumaArt

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-05-17 01:27 UTC, ExcessiveUseOfCobblestone commented
hi!

2023-05-17 03:20 UTC, newfren commented
sol dry in the soda dispenser is so helpful it's such a pain in the ass using cans

2023-05-17 05:42 UTC, Likteer commented
You may have overdone it with complexity, I don't think these will se much use chief.
And the prerequisites are mothic drinks?

2023-05-17 15:16 UTC, KingkumaArt commented
> sol dry in the soda dispenser is so helpful it's such a pain in the ass using cans

Main reason I added it was I was getting sick of buying cans during testing for the dark & stormy lmao

2023-05-17 18:47 UTC, KingkumaArt commented
> The prerequisites are mothic drinks?

These aren't meant to be etherial drinks in the way moffic drinks are, I just picked those two as they fit the theming - dark&stormy being themed around thunderstorms, and admiralty being the closest I could think of to a nanotrasen-inspired cocktail.

2023-05-17 19:02 UTC, ExcessiveUseOfCobblestone commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	if(istype(stomach))
You should check the type prior to assuming the stomach is said type.

2023-05-17 19:02 UTC, ExcessiveUseOfCobblestone commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	if(istype(stomach))
same here

2023-05-17 19:53 UTC, KingkumaArt commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +/datum/reagent/consumable/ethanol/telepole/expose_mob(mob/living/exposed_mob, methods=TOUCH, reac_volume) //can't be on life because of the way blood works.
> im confused by this statement why do you want it on life?
According to the code for liquid electricity, the etherial food thing doesnt work on touch

2023-05-20 08:07 UTC, Twaticus approved these changes

2023-05-26 00:39 UTC, san7890 requested changes
two minor things and this looks good to me

2023-05-26 00:39 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	ADD_TRAIT(affected_mob, TRAIT_FEARLESS, type)
use `add_traits()` instead

2023-05-26 00:39 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +	REMOVE_TRAIT(affected_mob, TRAIT_TESLA_SHOCKIMMUNE, type)
use `remove_traits()` instead. you could also get away with having a list of these traits on the reagent as well to slim down on copypasta

2023-05-26 22:10 UTC, KingkumaArt reviewed
I hope I did the syntax right on the add_traits

2023-05-27 23:00 UTC, merged