Removes a lot of boilerplate from hydroponics apply, adds a mushroom mechanic for milk as implied by comments
tgstation/tgstation pull request #75491
Opened 2023-05-17 03:06 UTC by MrMelbert

## About The Pull Request

- Removes a ton of boilerplate from `on_hydroponics_apply`
    - Replaces `chems.get_reagent_amount(type)` with `volume`. The former is a roundabout way of accomplishing the latter, the only thing the proc did was add un-necessary iterating and also round to the chemical quantisiation level, which wasn't really necessary as most locations rounded anyways. 

- While doing this, I saw th is comment: `Milk is good for humans, but bad for plants. The sugars cannot be used by plants, and the milk fat harms growth. Not shrooms though. I can't deal with this now...` This was super easy to just throw in so I did it. 

- Additionally, I noticed Uranium and Radium had this var, `tox_damage`, which was ... the same for both, but one used REM and one didn't, but it shouldn't have been using REM since it was multiplied by REM in the proc... so I removed the REM from the latter, making it doubly strong (0.5 -> 1). I did this just because I could use it nicely for the hydro proc but... I unno.

## Why It's Good For The Game

Makes it a bit clearer on working with hydro chems

## Changelog

:cl: Melbert
balance: Milk no longer harms the potency of mushrooms. Apparently it's good for them?
balance: Radium now does slightly more tox damage than Uranium
code: Removed a ton of boilerplate from chem hydro interactions
/:cl:

2023-05-17 09:10 UTC, MTandi commented
@MrMelbert this also seems like a mistake:

![image](https://github.com/tgstation/tgstation/assets/3625094/10a3a5ee-3f6b-452f-9c10-72c130728d79)

2023-05-17 18:09 UTC, MrMelbert commented
> MrMelbert This also seems like a mistake:
> 
> ![image](https://user-images.githubusercontent.com/3625094/238895413-10a3a5ee-3f6b-452f-9c10-72c130728d79.png)

That one is a little sus I won't touch it in this PR

2023-05-17 19:05 UTC, ExcessiveUseOfCobblestone commented
I think the comment is wrong and the code is correct, not to say i wouldnt want to see those chems get btfod which i was looking at.

2023-05-17 19:11 UTC, ExcessiveUseOfCobblestone commented
brain farting rn, with checktray removed is there an inherited way of btfoing micro (<1) doses?

2023-05-17 20:03 UTC, MrMelbert commented
> brain farting rn, with checktray removed is there an inherited way of btfoing micro (<1) doses?

I moved it to here https://github.com/tgstation/tgstation/blob/4882b3f9035e12764ffb2c9279a8bd617bbefd8d/code/modules/hydroponics/hydroponics_chemreact.dm#L9-L12

2023-05-24 18:14 UTC, san7890 requested changes
spacing nits. some of them are adjacent to code you touched but you may as well patch it up now since no one else is gonna open up these files for the next three years

2023-05-24 18:14 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
>  	//It has stable IN THE NAME. IT WAS MADE FOR THIS MOMENT.
```suggestion
//It has stable IN THE NAME. IT WAS MADE FOR THIS MOMENT.
```

2023-05-24 18:14 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
>  	// why, just why
```suggestion
// why, just why
```

2023-05-24 18:15 UTC, san7890 commented
fuck it we assume direct control

2023-05-24 18:28 UTC, merged