Refactored the TTS subsystem to more properly handle message garbling. Added a volume preference for TTS.
tgstation/tgstation pull request #75559
Opened 2023-05-20 12:15 UTC by Watermelon914

## About The Pull Request

TTS subsystem now uses datums to handle requests. Also removed the DM-side caching since it wasn't really all that useful compared to the complexity it added to the entire system.

Messages will no longer play at the same time the request was received. This is so that the TTS audio files don't play out of order.
Also adds a preference for players to adjust the volume of TTS sounds.
Additionally adds a debug verb to re-establish connection to the TTS server.

## Why It's Good For The Game

Fixes message garbling. Also gives players a way to control the volume of TTS messages for themselves.

## Changelog

:cl:
fix: Fixed message garbling. TTS messages won't play in the wrong order anymore.
qol: Added a way for players to change the volume of TTS.
/:cl:

2023-05-20 12:29 UTC, Watermelon914 commented
Needs python server updates before this can be TM'd

2023-05-21 20:26 UTC, MrStonedOne requested changes
Goof made this not work on linux because he forgot case matters in filenames on linux.

2023-05-21 20:26 UTC, MrStonedOne commented on tools/tts/tts/tts.py
> +letters_to_use = "abcdefghijklmnopqrstuvwxyz1234567890"
```suggestion
letters_to_use = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
```

2023-05-21 20:26 UTC, MrStonedOne commented on tools/tts/tts/tts.py
> +	text = request.json.get("text", "")
```suggestion
	text = request.json.get("text", "").upper()
```

2023-05-21 20:26 UTC, MrStonedOne commented on tools/tts/tts/tts.py
> +					tts.tts_to_file(text=value.upper() + ".", speaker=voice, file_path="samples/" + voice + "/" + value + ".wav")
```suggestion
					tts.tts_to_file(text=value + ".", speaker=voice, file_path="samples/" + voice + "/" + value + ".wav")
```

2023-05-22 13:29 UTC, merged