[NO GBP]Graves can be closed again
tgstation/tgstation pull request #75563
Opened 2023-05-20 13:58 UTC by SyncIt21

## About The Pull Request

Fixes #75553

Graves can closed again but "only" with a shovel and not instantly by hand which was the previous behaviour(which was dumb and nonsensical), to put stuff in the grave you must throw them in, this is so you cannot destroy graves by hitting them with stuff except while digging them out with a shovel

## Changelog
:cl:
fix: graves can be closed again, but only with a shovel and not by hand.
/:cl:

2023-05-22 04:03 UTC, san7890 requested changes
those are all meant to be booleans they were just done wrong

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +			return 1
```suggestion
			return TRUE
```

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +		return 1
```suggestion
		return TRUE
```

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
>  			return 1
```suggestion
			return TRUE
```

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +			return 1
```suggestion
			return TRUE
```

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +		return 1
```suggestion
		return TRUE
```

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +		to_chat(user, span_notice("You remove \the [src]  completely."))
```suggestion
		to_chat(user, span_notice("You remove \the [src] completely."))
```

spacing is wonky here

2023-05-22 04:03 UTC, san7890 commented on code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
> +	var/dug_closed = FALSE
would you mind dmdoccing all of these while you're here?

2023-05-22 09:51 UTC, SyncIt21 commented
Done

2023-05-24 14:05 UTC, SyncIt21 commented
@san7890 ready for merge?

2023-05-26 00:28 UTC, merged