Massive Spraycan and Crayon Powercreep: smaller graffiti cost less to draw.
tgstation/tgstation pull request #75588
Opened 2023-05-22 15:50 UTC by Ghommie

## About The Pull Request
Currently, drawing a small circle on the floor consumes as much charge as any other drawable but the larger horizontal ones that cost five times as much, which is a bit dull for players having to burn through a ton of spraycans to cover the floor in several small dots for their floor drawings.

This PR aims to reduce the cost of some of the smaller drawables, like "shortline", "smallbrush", "pawprints" etc., in virtue of the smaller area they cover. The balances changes may seem bit of an arbitrary and not include ones that are a bit on the edge between "small" and not "small", but I'd rather keep it simple than have other values such like "semi-small" integrated and snowball this balance PR into a more finnicky, disputable or not agreeable with version of itself.

This also covers re-coloring and existent graffiti. Currently it always costs 2 charges to change its color regardless if it costed 1 or 5 to spray in the first place. With this PR, the costs should match that of when they were drawn. To boot, It also takes into account the tagger quirk now.

Code had to be cleaned up and improved a bit for a smoother implementation of these changes.
A fairly unrelated but small change: Trying to suicide with an empty spraycan will now fail, because it's empty. It's that simple.

## Why It's Good For The Game
Enables non-cyborg players to engage in jolly floor-vandalizing-art in a more consistent, slightly more enjoyable way.

## Changelog

:cl:
balance: Drawing small graffiti like paw/foot/claw prints, small brush dots and short lines should cost half as many charges off your spraycan or crayon.
balance: The cost of recoloring graffiti decals is now consistent with that of drawing them.
balance: Trying to suicide with an empty spraycan will now fail, because it's empty. It's just that simple.
/:cl:

2023-05-22 18:05 UTC, Jackal-boop commented
Could you also buff paint cans? Paint cans only have 6 uses before running dry

2023-05-22 18:37 UTC, Ghommie commented
> Could you also buff paint cans? Paint cans only have 6 uses before running dry

I'm afraid that's out of the scope of this PR. Paint cans are pretty unrelated to crayons and spraycan as far as typepath and procs go.
However I too opine paint cans should be improved, though in this case merely by raising its number of uses wouldn't be enough. As a feature they're clearly superseded by colorful reagent and crayon powder in its current state, but that's something you shouldn't expect me to do anyway.

2023-05-23 09:39 UTC, carlarctg commented
please make text like this too pray emoji

2023-05-23 22:34 UTC, san7890 requested changes

2023-05-23 22:34 UTC, san7890 commented on code/game/objects/items/crayons.dm
> +				balloon_alert(user, "a color that dark on this? surely not.")
balloon alerts shouldn't end in a single period and this is way too long anyways... it's clever but unfortunately a to_chat is  probably the way to go in this context

2023-05-24 18:06 UTC, merged