Generic and crew-available status readout module
tgstation/tgstation pull request #75708
Opened 2023-05-28 17:52 UTC by Stalkeros2

## About The Pull Request
Ninja's health-and-nutrition-and-such status readout module is no longer ninja-exclusive; added to the advanced medical research techweb. As such, its description has been slightly edited to affect its status.
![image](https://github.com/tgstation/tgstation/assets/42087567/a6fc6a43-fcd0-469f-bede-c7a33e0de404)

## Why It's Good For The Game
This module always felt like it shouldn't be locked behind and thus only use by a relatively rare antagonist: it was, just, super convenient, and useful for uuuh... I'd say anyone on station, to view their accurate health status on the spot. And with the health analyzer module doing the exact same thing, and more, -being able to check other people's health whoa!-, I don't think it'd be out of the norm to make the ninja's module station-available too.

## Changelog

:cl: Stalkeros
add: Status readout module: now generic, additionally station-available.
/:cl:

2023-05-28 19:59 UTC, Fikou requested changes
This shouldn't render the operation time and number (a ninja subtype should do that), and it shouldn't be in the ninja file
Also add a flatline sound effect on death coward

2023-05-28 19:59 UTC, Fikou commented on code/modules/research/techweb/all_nodes.dm
> +		"mod_statusreadout"
```suggestion
		"mod_statusreadout",
```

2023-05-28 19:59 UTC, Fikou commented on code/modules/research/designs/mechfabricator_designs.dm
> +
```suggestion
```

2023-06-14 00:29 UTC, JohnFulpWillard commented
This PR looks done but it's marked as draft, was this ready to review or not? @Stalkeros2

2023-06-14 15:05 UTC, Stalkeros2 commented
> This PR looks done but it's marked as draft, was this ready to review or not? @Stalkeros2

IRL stuff happened; afaik one of the maintainers (maybe it was you even. Or Fikou. Likely Fikou.) asked me to make the Operation Number and Operation Time parts of the UI ninja-only, so I was trying to do exactly that; and eventually, forgot about this PR. Otherwise, it's entirely done.

2023-06-30 00:05 UTC, closed without merging