Added advanced magboots module to ERT engineer
tgstation/tgstation pull request #75903
Opened 2023-06-07 05:50 UTC by rageguy505

Added advanced magboots/tether to ERT engineer

## About The Pull Request
Adds advanced magboots and a tether to the ERT engineer's modsuit. 
I tested and it works.

## Why It's Good For The Game
Magboots is really important gear when working with the SM. 
These get the advanced kind since they're kind of rare and ERT modsuit gear is usually a cut above. I could downgrade if you want.

## Changelog

:cl:
add: ERT engineers now come with advanced magboot modules.

/:cl:

2023-06-07 06:14 UTC, Farquaar commented
Aren't the advanced magboots supposed to be super secret rare tech though? That's why they're sometimes a traitor objective to steal.

2023-06-07 06:32 UTC, rageguy505 commented
> Aren't the advanced magboots supposed to be super secret rare tech though? That's why they're sometimes a traitor objective to steal.

It's the module that can't be removed, not the actual boot

2023-06-07 07:33 UTC, Fikou requested changes
> I tested and it works.

it doesnt. you override the already set value one line above, thats not how variables work

2023-06-07 09:15 UTC, rageguy505 commented
huh weird, ill look at it later

2023-06-07 13:20 UTC, distributivgesetz requested changes

2023-06-10 23:19 UTC, rageguy505 commented
I might change it to regular magboots instead of advanced, there's no slowdown so no reason to turn it off and only having the ERT engineer being immune to slipping is a bit weird.

2023-06-25 00:06 UTC, closed without merging