Food gets stink lines when about to go rotten
tgstation/tgstation pull request #76038
Opened 2023-06-13 21:15 UTC by ChungusGamer666

## About The Pull Request

Title says it all, food that decomposes gets stink lines halfway through.
![image](https://github.com/tgstation/tgstation/assets/82850673/87fd9861-2abf-4f1a-9316-cd20c524fb43)
![image](https://github.com/tgstation/tgstation/assets/82850673/c982055d-ed69-4935-bda5-7851836fad2c)

## Why It's Good For The Game

1. It's funny
2. It's a visual indicator for food going bad which is kinda nice

## Changelog

:cl:
add: Food now gets stink lines when going bad. Uh oh, stinky.
/:cl:

2023-06-13 23:42 UTC, Fikou commented
quite pungent

2023-06-14 00:17 UTC, Singul0 commented
brap fetish, no fetish content is allowed in this codebase, especially not brap.

2023-06-14 02:48 UTC, Wallemations approved these changes
As the person that made decomposition I can't believe I didn't think of this

2023-06-14 03:39 UTC, ArcaneMusic commented
Might I suggest a different visual, like perhaps a little clock, or maybe flies instead?

2023-06-14 04:55 UTC, ChungusGamer666 commented
> Might I suggest a different visual, like perhaps a little clock, or maybe flies instead?

no, stink lines are funnier

2023-06-14 21:12 UTC, ChungusGamer666 commented
> no, stink lines are funnier

![why are you booing me](https://github.com/tgstation/tgstation/assets/82850673/9a82d463-3b95-43a6-91e8-c3df9920e41a)

2023-06-15 03:51 UTC, BlueMemesauce commented
The issue is that it just looks like a green worm in the bread
Shouldnt the stink lines be surrounding it rather than touching it? https://www.youtube.com/watch?v=4ILKyggzDLM

2023-06-15 10:52 UTC, ChungusGamer666 commented
> The issue is that it just looks like a green worm in the bread Shouldnt the stink lines be surrounding it rather than touching it? https://www.youtube.com/watch?v=4ILKyggzDLM

it's particles, it floats up :)
i was gonna make an mp4 showing it instead of a screenshot but i am a lazy ass

2023-06-16 20:16 UTC, san7890 requested changes

2023-06-16 20:16 UTC, san7890 commented on code/datums/components/food/decomposition.dm
> +		PROC_REF(dropped))
```suggestion
		PROC_REF(dropped),
	)
```

2023-06-16 20:16 UTC, san7890 commented on code/datums/components/food/decomposition.dm
> +		PROC_REF(picked_up))
```suggestion
	RegisterSignals(parent, list(
		COMSIG_ITEM_PICKUP, //person picks up an item
		COMSIG_ATOM_ENTERED), //Object enters a storage object (boxes, etc.)
		PROC_REF(picked_up),
	)
```

multiline should be odne correctly

2023-06-17 01:53 UTC, Wallemations approved these changes
much better

2023-06-19 00:29 UTC, merged