SPECIES NUKING 2023: Refactors a bunch of species traits into flags for the head bodypart
tgstation/tgstation pull request #76074
Opened 2023-06-15 16:07 UTC by ChungusGamer666

## About The Pull Request

Title. 
I saw a comment on psyker code complaining about these species traits (which admittedly, they suck) and heeded the call to turn all of this crap into something defined almost entirely by the head bodypart.

## Why It's Good For The Game

Potential to simplify species code further in the future, by delegating more visuals to bodyparts, which is where most of them should be handled.

## Changelog

Should not be player facing, unless I fucked up.

2023-06-15 16:33 UTC, ChungusGamer666 commented
![image](https://github.com/tgstation/tgstation/assets/82850673/223c25c5-a307-4ba5-a3fc-8849ecc4fd44)
pref menu is OK
![image](https://github.com/tgstation/tgstation/assets/82850673/1547a46e-6637-4dd0-9167-d939927635dc)
ingame humie is OK

2023-06-15 16:36 UTC, ChungusGamer666 commented
![image](https://github.com/tgstation/tgstation/assets/82850673/2f05bb7d-2ff1-4fc3-9ce6-8f1fafdba844)
liggers are OK

thank you screenshot tests, time to fix the rest

2023-06-15 18:27 UTC, ChungusGamer666 commented
yeah i uhhh have no clue why a bunch of species get no eyes in the screenshots, i'll need some help man

2023-06-15 18:43 UTC, ChungusGamer666 commented
I FIGURED IT OUT!!!

2023-06-15 19:15 UTC, ChungusGamer666 commented
![image](https://github.com/tgstation/tgstation/assets/82850673/306e2d7d-e841-49e3-a30f-de504ef84cf3)
EVERYTHING FUCKING WORKS NOW, I HAD FUCKED UP THE ICON RENDER KEY LOL

2023-06-15 19:16 UTC, ChungusGamer666 commented
![goodwillalwaystriumph](https://github.com/tgstation/tgstation/assets/82850673/551bd4da-66d6-4771-bb21-acbe35f70cc8)

2023-06-16 01:26 UTC, ATH1909 commented
did you test HARS with this?

2023-06-16 01:47 UTC, ChungusGamer666 commented
> did you test HARS with this?

no, will test

2023-06-16 02:31 UTC, ChungusGamer666 commented
it will work with HARS

2023-06-16 03:35 UTC, ChungusGamer666 commented
head rendering code is still an absolute shitshow, but we have to start somewhere.
i'll try to keep working to make it not a shitshow after this is merged, if i did all i want to do at once this would be a nightmare for maintainerheads.

2023-06-16 04:32 UTC, ChungusGamer666 commented
![image](https://github.com/tgstation/tgstation/assets/82850673/079aee42-e987-4cbc-8b45-7c2f2923b3cc)
lipstick looks like dogshit (due to human resprite, i assume), someone should resprite this blunder
but hey lipstick code works

2023-06-16 06:03 UTC, ChungusGamer666 commented
holy fuck lois im cumming

2023-06-19 01:29 UTC, ChungusGamer666 commented
yep
merge conflicts

2023-06-19 22:31 UTC, ChungusGamer666 commented
please mark this pr as a refactor, goofy bot is goofy

2023-06-20 07:35 UTC, ChungusGamer666 commented
this pr will actually kill me

2023-06-20 21:13 UTC, ChungusGamer666 commented
there is no merge conflict no more bitch

2023-06-20 21:29 UTC, ChungusGamer666 commented
can any maintainer label this properly as a refactor and remove the merge conflict label
k thanks

2023-06-21 00:48 UTC, ChungusGamer666 commented
@Time-Green you reviewed my previous species datum related pr, so this might interest you

2023-06-21 06:09 UTC, Time-Green commented
> @Time-Green you reviewed my previous species datum related pr, so this might interest you

It do, I was just waiting for this to be finished. I’ll review it when I have some time

2023-06-21 16:29 UTC, Time-Green requested changes
Great work! Minor nitpicks/questions. Eyes, hair and lips should just be moved to bodypart_overlays, but that's for another day

2023-06-21 16:29 UTC, Time-Green commented on code/modules/religion/burdened/psyker.dm
> -	new_head_owner.dna.species.species_traits |= NOEYESPRITES //MAKE VISUALS TIED TO BODYPARTS ARGHH
Nature is healing

2023-06-21 16:29 UTC, Time-Green commented on code/modules/surgery/bodyparts/head.dm
> +	return .
```suggestion
	return 
```
'.' is default, no need to specifiy

2023-06-22 08:23 UTC, Time-Green commented on code/modules/mob/living/carbon/human/_species.dm
> +/datum/species/proc/check_head_flags(check_flags = NONE)
I'm gonna imagine you had an amazing counter argument

2023-06-22 08:23 UTC, merged