Build Mode Preview + better help text
tgstation/tgstation pull request #76095
Opened 2023-06-16 18:14 UTC by dragomagol

## About The Pull Request
Gives `Adv Build Mode` and `Fill` an item preview, and puts the help text for build mode modes into an examine block.

![image](https://github.com/tgstation/tgstation/assets/66640614/3f6fe986-1767-4639-94d3-523f1039c947)

![image](https://github.com/tgstation/tgstation/assets/66640614/a7eae938-a575-46bd-b00e-865f04e0de20)

## Why It's Good For The Game
It's good to see what you're doing. 

## Changelog
:cl: Tattle
admin: build mode help text is in an examine block
admin: adv build mode and fill now have item previews
/:cl:

2023-06-16 18:15 UTC, TheVekter commented
YES PLEASE

2023-06-22 05:59 UTC, san7890 requested changes

2023-06-22 05:59 UTC, san7890 commented on code/modules/buildmode/buildmode.dm
> +	// item preview for selected item
```suggestion
	/// item preview for selected item
```

dmdoc is better, wish the rest of the datum had it but at the very least the new stuff should

2023-06-22 05:59 UTC, san7890 commented on code/modules/buildmode/buildmode.dm
> +	if(!preview)
```suggestion
	if(isnull(preview))
```

`isnull()` is more explicit here, and like 0.001 CPU cycles faster. nice.

2023-06-22 05:59 UTC, san7890 commented on code/modules/buildmode/buildmode.dm
> +	preview = null
```suggestion
	QDEL_NULL(preview)
```

same thing, just in a neater macro

2023-06-24 02:04 UTC, merged