Makes tongues handle taste instead of species datum
tgstation/tgstation pull request #76204
Opened 2023-06-20 21:53 UTC by ChungusGamer666

## About The Pull Request

WIP

## Why It's Good For The Game

WIP

## Changelog

:cl:
refactor: Liking/disliking food is now handled by the tongue organ, not the species.
/:cl:

2023-06-20 22:25 UTC, ChungusGamer666 commented
three fucking species datum gutting prs at once lets fucking go
species nuke 2023

2023-06-20 22:54 UTC, MTandi commented
Uh, not sure. They say that there is a gene responsible for loving bitter coffee and dark chocolate.

2023-06-20 23:25 UTC, ChungusGamer666 commented
> Uh, not sure. They say that there is a gene responsible for loving bitter coffee and dark chocolate.

I know that this isn't really accurate in any way to real life, but being able to swap tongues and get the person's tastes for food is just a really cool, emergent gameplay thing.
I'll consider keeping some functionality in the species datum if I have to, but gameplay wise there is just a lot of potential to deferring most - if not all - tastes to the tongue.

2023-06-21 03:35 UTC, Kapu1178 commented
Personally this makes more sense in the Stomach. Since it also defines what is toxic to them.

2023-06-21 03:37 UTC, ChungusGamer666 commented
> Personally this makes more sense in the Stomach. Since it also defines what is toxic to them.

Thought about moving toxic foodtypes to the stomach, but then I realized that toxic food just behaves as well, food you hate.
Will keep it as a tongue thing.

2023-06-21 04:32 UTC, ChungusGamer666 commented
![image](https://github.com/tgstation/tgstation/assets/82850673/a5c79840-33f8-4ba2-af00-f51ad26169cc)
it be working

2023-06-21 05:14 UTC, ChungusGamer666 commented
it's OVER

2023-06-21 05:16 UTC, ChungusGamer666 commented
unit test failures that aint my fault, love that shit

2023-06-21 05:28 UTC, ChungusGamer666 commented
bullshit!!!

2023-06-21 06:17 UTC, ChungusGamer666 commented
can a maintainer rerun tests ok thx

2023-06-21 08:23 UTC, ZephyrTFA commented
stop breaking shit

2023-06-22 01:28 UTC, YakumoChen commented
Does that mean if you remove your tongue you can eat basically anything? 

I think the stomach makes a lot more sense, taste and appetite are far more linked to the guts in real life, the tongue just gets signals based on those preferences.

2023-06-22 06:12 UTC, MisterBomb7 commented
How does this work with the voicebox tongue?

2023-06-24 10:13 UTC, Time-Green requested changes
Looks good, minor nitpicks

2023-06-24 10:13 UTC, Time-Green commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +	var/original_felinid = TRUE //set to false for felinids created by mass-purrbation
Autodoc :)

2023-06-24 10:13 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/_cup.dm
> +	if(last_check_time + 50 > world.time)
```suggestion
	if(last_check_time + 5 SECONDS > world.time)
```

2023-06-24 10:13 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/_cup.dm
> +// all this copypaste from the edible component is quite deplorable, why the fuck does this not use the edible component?
Please just replace with a normal autodoc comment (you can still recommend putting it on edible component)

2023-06-24 15:28 UTC, ChungusGamer666 commented
> Does that mean if you remove your tongue you can eat basically anything?

No. Toxic foodtypes without a tongue default to TOXIC.

> I think the stomach makes a lot more sense, taste and appetite are far more linked to the guts in real life (the gut flora, to be exact), the tongue just gets signals based on those preferences.

I don't agree. Ultimately, your tongue is what receives taste, and this is how I implemented it. The assumption is that every species evolved a tongue that likes certain types of food because it suits their stomach regardless.

> Also removing your stomach means you can't just bypass food restrictions.

If you go through the effort of removing your tongue just to be able to eat your disliked foodtypes... I am fine with it. Also this is the behavior with tongues before this PR, as tongues already apply ageusia when removed. So the precedent is set already.

2023-06-24 15:29 UTC, ChungusGamer666 commented on code/datums/quirks/neutral_quirks.dm
> +	tongue.liked_foodtypes = initial(tongue.liked_foodtypes)
absolutely, this gave me a bit of a headache

2023-06-24 16:36 UTC, YakumoChen commented
> I don't agree. Ultimately, your tongue is what receives taste, and this is how I implemented it. The assumption is that every species evolved a tongue that likes certain types of food because it suits their stomach regardless.

I don't agree with this. The tongue handles speech, which it's always done, and the stomach handles food. We shouldn't be having one organ do both. Changing your tongue shouldn't give you the burden of another species's foodtypes.

2023-06-24 16:58 UTC, ChungusGamer666 commented
> 
> I don't agree with this. The tongue handles speech, which it's always done, and the stomach handles food. We shouldn't be having one organ do both. Changing your tongue shouldn't give you the burden of another species's foodtypes.

At this point, it's up to maintainers. But I think the precedent has been set very strongly by the existing tongue ageusia mechanic.

2023-06-24 18:24 UTC, ChungusGamer666 commented
> How does this work with the voicebox tongue?

Default human tastes.

2023-06-24 19:29 UTC, Time-Green commented
You can just fix the merge conflicts on one of the species PR and then ping me on it, to avoid headaches

2023-06-24 20:46 UTC, ZephyrTFA commented
I'm fine with liked foods being dictated by what your tongue is even if it may not actually match what is actually toxic to you.
It makes sense and is also realistic.

2023-06-24 20:53 UTC, Time-Green commented
oh yeah probably shouldve specified but im fine with it too

2023-06-26 06:17 UTC, merged