Lavaproof tracks fix
tgstation/tgstation pull request #76258
Opened 2023-06-22 17:46 UTC by GPeckman

## About The Pull Request

There is an upgrade for mining borgs called lavaproof tracks. As the name implies, it allows them to safely traverse lava. This PR makes the tracks also protect from liquid plasma, fixing #76107.

## Why It's Good For The Game

Liquid plasma is the Icebox equivalent of lava, it stands to reason that something that protects against lava should also protect against liquid plasma. 

## Changelog

:cl:
fix: The lavaproof tracks cyborg upgrade now protects against liquid plasma, the Icebox equivalent of lava.
/:cl:

2023-06-22 17:51 UTC, Ryusenshu commented
Dope

Maybe a rename of them aswell to make it more clear ingame?

Weatherproof Tracks?
Reinforced Tracks?
Hazardproof Tracks?

2023-06-22 17:56 UTC, GPeckman commented
Based on bug report, people seem to assume that lava and liquid plasma are basically the same. In fact I didn't know there was a mechanical difference until I saw the bug report.

I changed the description of the tracks ("...enabling them to withstand exposure to molten rock **and liquid plasma**"). I think that's enough, but a name change is totally feasible if it isn't.

2023-06-22 18:04 UTC, Sealed101 commented
`fixing` won't link the issue to the PR, please change the wording to `Fixes #76107`

_For future reference, [these](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) are all the keywords that can be used to link issues/PRs._

2023-06-24 02:21 UTC, san7890 requested changes

2023-06-24 02:21 UTC, san7890 commented on code/game/objects/items/robot/robot_upgrades.dm
> +		ADD_TRAIT(R, TRAIT_SNOWSTORM_IMMUNE, type)
use `add_traits()` proc

2023-06-24 02:21 UTC, san7890 commented on code/game/objects/items/robot/robot_upgrades.dm
> +		REMOVE_TRAIT(R, TRAIT_SNOWSTORM_IMMUNE, type)
use `remove_traits()` proc

2023-06-26 23:51 UTC, merged