Adds a new passive changeling ability - the Defibrillator Grasp. Adds support for 0 cost changeling abilities.
tgstation/tgstation pull request #76301
Opened 2023-06-24 19:41 UTC by MrMelbert

## About The Pull Request

![image](https://github.com/tgstation/tgstation/assets/51863163/190d0dda-6899-468d-9a3e-5df05d7b1414)

- Adds a new PASSIVE changeling ability, totally not stolen from The Thing, called Defibrillator Grasp. If someone attempts to defibrillate your body while you are in stasis or dead, you will instantly be revived at full strength. Additionally, the person doing the defibbing will have both of their arms removed (or if they're a cyborg they'll just be stunned). 

- Adds support for 0 cost changeling abilities. DNA sting is now 0 cost / optionally learned. 

## Why It's Good For The Game

The intent of this ability to add a new avenue for stealthier changelings to spring upon their victims - faking their death only to get brought to medical, then springing up like a bat out of hell and pouncing upon a now vulnerable medical doctor.

Or maybe pretending to be another type of criminal to get brought to the brig medbay and revived, then suddenly jumping up and striking out.

As for the DNA sting change - Ling gets a ton of buttons to start and people don't often use a lot of them. DNA sting is a prime example. By moving some to just "zero cost, optional", trims down on some action ability bloat. 

## Changelog

:cl: Melbert
add: Added a new 0 cost passive changeling ability, the Defibrillator Grasp. 
add: DNA sing is now no longer innate, but 0 cost, allowing changelings to not take it if they don't plan on using it. 
/:cl:

2023-06-24 20:02 UTC, Jackal-boop commented
is this toggleable?

2023-06-24 20:03 UTC, MrMelbert commented
> is this toggleable?

it's a passive

2023-06-24 20:15 UTC, Jackal-boop commented
> > is this toggleable?
> 
> it's a passive

doesnt this mean that sec can ID changlings by just killing someone and reviving them

2023-06-24 20:19 UTC, MrMelbert commented
> doesnt this mean that sec can ID changlings by just killing someone and reviving them

considering it's optional, IE not all changelings will have it, no, I don't think this will happen

2023-06-24 22:43 UTC, chemistrymain2 commented
> > doesnt this mean that sec can ID changlings by just killing someone and reviving them
> 
> considering it's optional, IE not all changelings will have it, no, I don't think this will happen

should still be a toggleable even if it's a passive so that you can't get ling tested w it and be fucked just because you bought it

2023-06-24 23:49 UTC, githubuser4141 commented
> > > doesnt this mean that sec can ID changlings by just killing someone and reviving them
> > 
> > 
> > considering it's optional, IE not all changelings will have it, no, I don't think this will happen
> 
> should still be a toggleable even if it's a passive so that you can't get ling tested w it and be fucked just because you bought it

yeah and you might not want it active in all situations, this is definitely a 'time and place' ability

2023-06-25 00:19 UTC, MrMelbert commented
Didn't want it to be a toggle, the idea behind it was requiring some form of commitment. 
Someone suggested allowing a free refund of it which I'm more keen on.

2023-06-25 00:40 UTC, ATH1909 commented
dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase

2023-06-25 01:08 UTC, MrMelbert commented
> dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase

95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)

2023-06-25 01:25 UTC, DATA-xPUNGED commented
> > dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase
> 
> 95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)

How do i use it right, then?

2023-06-25 01:32 UTC, AviiCinders commented
> > > is this toggleable?
> > 
> > 
> > it's a passive
> 
> doesnt this mean that sec can ID changlings by just killing someone and reviving them

I think that becomes a policy issue afterwards

2023-06-25 02:07 UTC, blackdav123 commented
> > > dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase
> > 
> > 
> > 95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)
> 
> How do i use it right, then?

sting only useful disguises so that you dont end up getting to many and losing your original body's identity

2023-06-25 07:34 UTC, BlueMemesauce commented
> > dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase
> 
> 95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)

I don't feel that this is a good idea, since DNA sting is like the whole point of changeling. The reason why most people don't use it is that it's difficult to pull of well. Why would we want to further discourage people from using it? The more people actually decide to use the ability the role is based around, the better.

2023-06-25 09:51 UTC, jughu commented
> > > dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase
> > 
> > 
> > 95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)
> 
> I don't feel that this is a good idea, since DNA sting is like the whole point of changeling. The reason why most people don't use it is that it's difficult to pull of well. Why would we want to further discourage people from using it? The more people actually decide to use the ability the role is based around, the better.

Because its button bloat the role is orginally intended to be around dna absorptions to complete their objectives but you can complete it with dna stings if anything this encourages lings to absorb more, lings in the past had the upside of getting traitor uplinks etc when you absorbed somoene but since the memory system rework this is not the case anymore leaving dna absorption absolute useless

2023-06-25 11:56 UTC, SomeoneYouProbablyKnow commented
Isn't this extra incentive for medical to be even slower when reviving people and just not reviving suspicious bodies with belt defibs? Just stick to metaprotected sec as cmo or get your armes chopped

2023-06-25 17:39 UTC, MrMelbert commented
> Isn't this extra incentive for medical to be even slower when reviving people and just not reviving suspicious bodies with belt defibs? Just stick to metaprotected sec as cmo or get your armes chopped

I cannot imagine there is a reality that an optional purchase for a rarer antagonists that does not often come in dead to medical results in medical working slower. 
I highly encourage people to look at the broader picture

2023-06-25 18:16 UTC, jughu commented
I think this would really shine if you could re-adapt or pick you abilities while your dead you can only re-adapt with dna absorptions and will give dna absorbtions a better reason to be use

2023-06-26 02:06 UTC, CCC23 commented
I love this

2023-06-28 13:34 UTC, moocowswag commented
> > dna seems really important for lings, not sure if it's a good idea to hide it behind a (0 cost) purchase
> 
> 95% of lings either don't use DNA sting at all or use it wrong (sting everyone in sight)

Its not wrong if it causes half the station to mald / rq while ai no longer recognizes them as human.

2023-06-28 18:13 UTC, MrMelbert commented
> Its not wrong if it causes half the station to mald / rq while ai no longer recognizes them as human.
> 
> dna sting is the single most straightforward way to impact a round as a ling you dont need it for stealth or trickery
> 
> youre basically a weaker version of a wizard running around with polymorph staff

Wrong sting. You're talking about transformation sting.

2023-07-01 18:32 UTC, Jacquerel requested changes
Great add, don't have anything to mention except to be picky

2023-07-01 18:32 UTC, Jacquerel commented on code/modules/antagonists/changeling/powers/fakedeath.dm
>  	var/revive_ready = FALSE
Be a dear and document these variables

2023-07-01 18:32 UTC, Jacquerel commented on code/modules/antagonists/changeling/powers/defib_grasp.dm
> +/datum/action/changeling/defib_grasp/proc/remove_arms(mob/living/carbon/changeling, mob/living/defibber, obj/item/shockpaddles/defib)
These procs too

2023-07-02 02:44 UTC, merged