SPECIES NUKING 2023: Moves speed modifier to bodyparts
tgstation/tgstation pull request #76336
Opened 2023-06-26 02:17 UTC by ChungusGamer666

## About The Pull Request

As we all know, speed is stored in the legs.

## Why It's Good For The Game

Potential for more medical abominations.
Potential for adding augmented legs that make you speedier (?)

## Changelog

:cl:
refactor: Species speed is now stored in the bodyparts.
/:cl:

2023-06-27 04:03 UTC, san7890 requested changes
i would rather you not include a changelog at all for this PR unless changing the way speed is calculated for things like zombies/snailpeople is changed in a way where it's noticeably slower or faster.

if it's approximately the same (or as close as you can possibly manage here) maybe something like "the way speed is calculated for snailpeople/zombies/etc. has been updated slightly, expect to see some changes" would work for a changelog since that is appropriate information to be player-facing

2023-06-27 04:03 UTC, san7890 commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +		BODY_ZONE_R_LEG = /obj/item/bodypart/leg/right/zombie/infectious
```suggestion
		BODY_ZONE_R_LEG = /obj/item/bodypart/leg/right/zombie/infectious,
```

2023-06-27 04:07 UTC, ChungusGamer666 commented
@san7890 updated the changelog, i think this is pretty player facing since now getting legs from a snail for example will impact your speed as if you were one

2023-06-27 04:34 UTC, ChungusGamer666 commented
but like it could go either way, i can remove the changelog if this is still unnecessary in your opinion

2023-06-27 22:51 UTC, san7890 commented
that's better thanks

2023-06-29 04:57 UTC, ATH1909 commented on code/modules/surgery/bodyparts/species_parts/misc_bodyparts.dm
> +	speed_modifier = 0.75 //big big fungus
```suggestion
	speed_modifier = 0.75 //big fungus big fungus
```

2023-06-29 04:57 UTC, ATH1909 commented
this seems like it could have major powergaming repercussions

e.g. getting your legs swapped out as a snail to become turbo

2023-06-29 05:10 UTC, ChungusGamer666 commented
fucking wack ass integration tests

2023-06-29 05:12 UTC, ChungusGamer666 commented
> this seems like it could have major powergaming repercussions
> 
> e.g. getting your legs augged as a snail to become turbo

I mean, that is kind of the point, letting technology fix your terrible terrible inborn deficiencies

2023-06-29 15:41 UTC, merged

2023-06-29 15:44 UTC, Time-Green commented
We might have to rethink this later if we get speed species