Better TTS voice test line
tgstation/tgstation pull request #76399
Opened 2023-06-29 02:05 UTC by YakumoChen

## About The Pull Request

Changes the TTS test sentence to a longer, better one

## Why It's Good For The Game

It has a wider range of sounds that give an overall better impression of the voice, probably

## Changelog

:cl:
spellcheck: The spoken line for testing TTS voices has been improved
/:cl:

2023-06-29 02:30 UTC, GoldenAlpharex requested changes

2023-06-29 02:30 UTC, GoldenAlpharex commented on code/modules/client/preferences/middleware/tts.dm
> +	INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), user.client, "I used to be a space man like you, then I took a golden bolt in the knee.", speaker = speaker, pi
Why not go for something a bit more thorough, while you're at it?
```suggestion
	INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), user.client, "The quick brown fox jumps over the lazy dog.", speaker = speaker, pitch = pitch, local = TRUE)
```

2023-06-29 02:37 UTC, GoldenAlpharex commented on code/modules/client/preferences/middleware/tts.dm
> +	INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), user.client, "I used to be a space man like you, then I took a golden bolt in the knee.", speaker = speaker, pi
We went for something less obscure after all.

2023-06-29 07:51 UTC, Likteer commented
`INVOKE_ASYNC(SStts, TYPE_PROC_REF(/datum/controller/subsystem/tts, queue_tts_message), user.client,` **"I used to be a space man like you, then I took a toolbox in the knee.",** `speaker = speaker, pitch = pitch, local = TRUE)`

Sir, it's been 12 years

2023-06-29 09:17 UTC, YakumoChen commented
not when they release a new version every year

2023-06-29 16:28 UTC, Watermelon914 commented
this isn't necessarily better, the cost of having a longer sentence is that it takes longer to find a voice you like or want.

2023-06-29 18:36 UTC, YakumoChen commented
Alas, humour is subjective

2023-06-29 18:36 UTC, closed without merging

2023-06-29 18:51 UTC, Likteer commented
Self-close. Commendable.

2023-07-04 03:39 UTC, Neskah commented
Nah.