RPED can carry & install computer circuit boards and complete computer frames
tgstation/tgstation pull request #76516
Opened 2023-07-03 13:09 UTC by SyncIt21

## About The Pull Request
Read Tin

- If you have multiple computer circuit boards in the RPED a tgui input is displayed asking you which specific one you want to install in the computer frame
- If you have cable & glass inside the RPED it will attempt to install them in the computer frame as well

You still have to use a screwdriver to turn the computer on as usual

## Why It's Good For The Game
RPED already has the ability to carry cable & glass sheets which is required to complete a computer frame, now after adding the ability to carry & install computer circuit boards we can build computers much faster without the need for manual clicking.

## Changelog
:cl:
add: RPED can carry & install computer boards and complete computer frames
/:cl:

2023-07-03 14:35 UTC, SyncIt21 commented
> Does this apply to the bluespace RPED as well?

Yes

2023-07-03 16:27 UTC, TheVekter commented
> > Does this apply to the bluespace RPED as well?
> 
> Yes

This is interesting. I'm wondering if this will have balance implications? I can't think of any off the top of my head, though, so maybe I'm just being paranoid.

2023-07-03 17:21 UTC, ExcessiveUseOfCobblestone commented
> This is interesting. I'm wondering if this will have balance implications? I can't think of any off the top of my head, though, so maybe I'm just being paranoid.

paranoid, youd need TK to start worry about a wonky interaction.

only thing I can think of would be a bug that actually replaced the board while an existing computer exists, but I dont see anything here that would create the scenario.

2023-07-03 19:16 UTC, YuliceTheDruid commented
How will this affect engi borgs (I hate having to ask about silicons)

2023-07-03 19:20 UTC, SyncIt21 commented
> How will this affect engi borgs (I hate having to ask about silicons)

Same benifits

2023-07-03 19:23 UTC, zxaber commented
>How will this affect engi borgs

Engiborgs have an upgrade on the same research tier that carries a single circuit board for machines and computers. There's no real balance adjustment here. But I was very proud of the circuit apparatus, so this makes me sad that it's basically the same benefit but better.

2023-07-03 23:46 UTC, optimumtact commented
I don't think I want this without a cohesive construction overhaul such as the RAT tbh.

2023-07-04 11:31 UTC, SyncIt21 commented
> I don't think I want this without a cohesive construction overhaul such as the RAT tbh.

The RPED can carry a maximum of 30 glass sheets & cable coil so even though you can carry a large number of circuit boards you can only install a maximum of 6 computers[each one takes 5 cable & 2 glass sheets] before you have to refill the RPED for cable.

Compare that to the duffle/construction bag which can carry a maximum of 12 circuit boards & 30 glass sheets + 60 cable[2 stacks] the RPED is pretty insignificant & underwhelming. It's either that or people should carry a separate bag just for cable & glass if they ever want to build a large number of computers

And then we have additional storage cost of carrying around iron sheets to make the actual computer frames the maximum number of computers we can actually build are very much limited by all these factors So you know the construction implications aren't that bad

This is really convenient, hopefully you will consider this.

2023-07-05 00:56 UTC, optimumtact commented
I'm sure someone will

2023-07-25 03:04 UTC, SyncIt21 commented
This had been sitting for a while. @Time-Green maybe you are interested in this feature :) ?

2023-07-25 08:37 UTC, Time-Green commented
> This had been sitting for a while. @Time-Green maybe you are interested in this feature :) ?

I'm sorry Sync, I don't feel strongly enough about this. I don't really know any maintainers/headcoders very into construction (except Oranges' design doc)

2023-07-25 09:16 UTC, SyncIt21 commented
> > This had been sitting for a while. @Time-Green maybe you are interested in this feature :) ?
> 
> I'm sorry Sync, I don't feel strongly enough about this. I don't really know any maintainers/headcoders very into construction (except Oranges' design doc)

Thats fair. On the flip side he and no one else has any strong opinions against this, also no balance implications from the above mentioned comments so no one would have problems if this got merged and is beneficial for engi players like me so...? It's fine all upto you friend.

2023-07-29 03:49 UTC, SyncIt21 commented
It's been a month :( . This is a really sweet feature, I need somebody to give it just a little attention.

@jlsnow301 since you upvoted this PR maybe you would like to merge/review this :) ? pretty please?

2023-07-29 14:14 UTC, Time-Green requested changes
I have looked deep within myself, and I do like the feature. I don't think anyone is currently working on the construction rework, so I don't see it fair to neglect our current system yet. 

Man construction code has a lot of istype checks

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +			else if(!circuit && istype(P, /obj/item/circuitboard))
This is the third !circuit check in a row, could you branch it out?

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +				if(!cable.tool_start_check(user, amount=5))
```suggestion
				if(!cable.tool_start_check(user, amount = 5))
```

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +				if(cable.use_tool(src, user, istype(P, /obj/item/storage/part_replacer) ? 0 : 20, volume=50, amount=5))
```suggestion
				if(cable.use_tool(src, user, istype(P, /obj/item/storage/part_replacer) ? 0 : 20, volume = 50, amount = 5))
```

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +				//serach for glass sheets which can either be the attacking item or inside an rped
```suggestion
				//search for glass sheets which can either be the attacking item or inside an rped
```

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +				if(!glass_sheets.tool_start_check(user, amount=2))
```suggestion
				if(!glass_sheets.tool_start_check(user, amount = 2))
```

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/computer/buildandrepair.dm
> +				if(glass_sheets.use_tool(src, user, istype(P, /obj/item/storage/part_replacer) ? 0 : 20, amount=2))
```suggestion
				if(glass_sheets.use_tool(src, user, istype(P, /obj/item/storage/part_replacer) ? 0 : 20, amount = 2))
```

2023-07-29 14:14 UTC, Time-Green commented on code/game/machinery/constructable_frame.dm
> +			else if(!circuit && istype(P, /obj/item/circuitboard))
Ditto on the !circuit checks

2023-07-29 14:14 UTC, Time-Green commented on code/modules/research/stock_parts.dm
> +/obj/item/storage/part_replacer/proc/has_an_circuitboard(board_type)
anbelievable

2023-07-29 14:14 UTC, Time-Green commented on code/modules/research/stock_parts.dm
> +	return !isnull((locate(board_type) in contents))
```suggestion
	return (locate(board_type) in contents)
```

I don't uhhhhhh... What?

2023-07-29 14:18 UTC, Time-Green commented on code/modules/research/stock_parts.dm
> +	return !isnull((locate(board_type) in contents))
Oh wait nvm I get it, you're boolerizing the return value

2023-07-30 13:02 UTC, SyncIt21 commented
@Time-Green any further changes?

2023-07-30 14:28 UTC, merged

2023-07-30 14:29 UTC, Time-Green commented
> @Time-Green any further changes?

You're free

2023-07-30 14:44 UTC, SyncIt21 commented
> > @Time-Green any further changes?
> 
> You're free

:)