Fixes silly siding sprites
tgstation/tgstation pull request #76586
Opened 2023-07-05 20:38 UTC by norsvenska

## About The Pull Request

Detaches siding code from the macro in #74171 because it wasn't doing its job properly. I tried to fix it, but I'm not a very good coder and opted to manually define each of the variations of siding. So this is more of a bandaid fix than anything.

## Why It's Good For The Game

Fixes both #76195 and #75059
Correct turf decals look better than wrong ones

look at how much nicer this corner looks now
![image](https://github.com/tgstation/tgstation/assets/73006946/39e78e69-e26f-4456-ac87-fecfe4d288ef)

## Changelog

:cl:
image: Siding now uses the correct sprite on corners and endpieces.
/:cl:

2023-07-05 21:48 UTC, Jolly-66 commented
Honestly, I was thinking of doing this but it doesn't come off to me as a proper fix, more of a temp fix to a bigger issue with the macro. I tinkered with trying to fix it but I kept running into dead ends.

Thats just my two cents.

2023-07-05 21:54 UTC, norsvenska commented
> Honestly, I was thinking of doing this but it doesn't come off to me as a proper fix, more of a temp fix to a bigger issue with the macro. I tinkered with trying to fix it but I kept running into dead ends.

Yeah, that's how I felt. This is by no means a permanent fix, it's a bandaid one, like I said. I did try working with the macro but kept getting errors and decided to do it the long way.

2023-07-05 23:21 UTC, Jolly-66 commented
Regardless,
Bless you for fixing this my inner mapper says thank you.

2023-07-06 07:21 UTC, Wallemations approved these changes

2023-07-06 17:38 UTC, san7890 requested changes

2023-07-06 17:38 UTC, san7890 commented on code/game/objects/effects/decals/turfdecal/markings.dm
> +// } this is broken. also there was a backslash at the end of each line, was throwing errors when commented out. just fyi, future coder
if it's broken, delete it. i thought it worked fine when i made it but just delete this if it's going to be completely unused

2023-07-06 17:38 UTC, san7890 commented on code/game/objects/effects/decals/turfdecal/markings.dm
> +//#undef SIDING_SUBTYPE_HELPER
delete this too

2023-07-06 18:56 UTC, merged