Nightmare vision goggles give you mare vision
tgstation/tgstation pull request #76604
Opened 2023-07-06 18:13 UTC by ChungusGamer666

## About The Pull Request

Daniel: https://github.com/tgstation/tgstation/pull/76600
The cooler daniel:
![image](https://github.com/tgstation/tgstation/assets/82850673/7cb2fc12-1b1e-4c07-8555-2da7fa052e72)

## Why It's Good For The Game

Neigh
![image](https://github.com/tgstation/tgstation/assets/82850673/e67b9d5b-ac4d-4871-8ca3-b0d00364f59d)

## Changelog

:cl:
add: Nightmare vision goggles now give you mare vision
/:cl:

2023-07-06 18:22 UTC, Jolly-66 commented
no way the virtual boy

2023-07-06 18:49 UTC, Fikou commented
neeigghhhh

2023-07-06 19:20 UTC, nukularpower commented
plz replace psyker vision with this

2023-07-06 22:52 UTC, ArcaneMusic requested changes

2023-07-06 22:52 UTC, ArcaneMusic commented on code/modules/clothing/glasses/_glasses.dm
> +	var/datum/hallucination/stored_hallucination
Autodoc var?

2023-07-06 22:55 UTC, ChungusGamer666 commented on code/modules/clothing/glasses/_glasses.dm
> +	var/datum/hallucination/stored_hallucination
ok whatever

2023-07-07 03:56 UTC, san7890 commented
this is funny but i feel like you lose out on the whole "WOAH THAT'S MARES" with the complete red/black bullshittery going on. ultimately whatever since it's a meme but it's really hard to tell that's meant to be a mare with the bichromal vision

2023-07-08 17:49 UTC, MrMelbert reviewed
It might be better to make this like a 1/50 chance when you equip the goggles rather than every time, just enough to make you question your sanity

2023-07-08 17:49 UTC, MrMelbert commented on code/modules/clothing/glasses/_glasses.dm
> +		QDEL_NULL(stored_hallucination)
```suggestion
	QDEL_NULL(stored_hallucination)
```

2023-07-08 17:49 UTC, MrMelbert commented on code/modules/clothing/glasses/_glasses.dm
> +		QDEL_NULL(stored_hallucination)
```suggestion
	QDEL_NULL(stored_hallucination)
```

2023-07-08 18:05 UTC, ChungusGamer666 commented
> It might be better to make this like a 1/50 chance when you equip the goggles rather than every time, just enough to make you question your sanity

Will do

2023-07-08 21:31 UTC, san7890 commented on code/modules/clothing/glasses/_glasses.dm
> +			"[src]", \
```suggestion
			src.name, \
```

we could also just do `name` but this is a bit more explicit...

2023-07-10 17:43 UTC, merged