Elementises mining mob resistance to being attacked from off screen
tgstation/tgstation pull request #76625
Opened 2023-07-07 13:33 UTC by Jacquerel

## About The Pull Request

Converts the bullet_act`/`hitby` overrides on `simple_animal/hostile/asteroid` into an element,
This is currently "reused" in that it's also applied to its equivalent on `basic/mining` although some day hopefully the `hostile/asteroid` subtype will stop existing.

This is a specific-ass component but it's not totally impossible something else will want it some day.

## Why It's Good For The Game

I'm a little mixed on this one honestly, I did this because I am adapting some old code but I would be open to the idea that this should just be left where it is (`bullet_act`/`hitby` overrides) and just copied/pasted onto `basic/mining`. 
I am also open to the idea that we don't need this at all and should just delete it, it seems unecessarily protective to me but I wasn't around at the time and maybe people really _were_ chucking hundreds of floor tiles at goliaths and that was a problem.

If it _is_ a problem then I guess this extends those protections to Bileworms now, because they need to be more durable and less possible to take down using non-mining tools, obviously.

## Changelog

:cl:
fix: Bile/Vileworms now have the same projectile and thrown weapon resistances of other mining mobs.
/:cl:

2023-07-08 12:31 UTC, DustanHache commented
hold up, why are lavaland mobs resistant to thrown weaponry? that’s stupid because as ashwalker you have only two options initially for hunting, kiting and throwing. everything else is reliant on numbers that may not be available. why penalize a ghost role for existing when the issue stems from a completely different source?

2023-07-08 13:38 UTC, Jacquerel commented
> hold up, why are lavaland mobs resistant to thrown weaponry? that’s stupid because as ashwalker you have only two options initially for hunting, kiting and throwing. everything else is reliant on body numbers that may not be available. why penalize a ghost role for existing when the issue stems from a completely different source?

They're specifically resistant to thrown weaponry which is weaker than a spear, a spear isn't weaker than a spear and so is still fully effective.

2023-07-08 23:29 UTC, san7890 requested changes

2023-07-08 23:29 UTC, san7890 commented on code/game/atoms_movable.dm
> +	if((impact_signal && (impact_signal & COMPONENT_MOVABLE_IMPACT_NEVERMIND)))
```suggestion
	if(impact_signal && (impact_signal & COMPONENT_MOVABLE_IMPACT_NEVERMIND))
```

2023-07-11 00:03 UTC, san7890 requested changes
you forgot some trailing commas but instead of sending you to the shadow realm i'm just going to webedit them in and automerge

2023-07-11 00:03 UTC, san7890 commented on code/datums/elements/ranged_armour.dm
> +	throw_blocked_message = "bounces off"
```suggestion
	throw_blocked_message = "bounces off",
```

2023-07-11 00:03 UTC, san7890 commented on code/modules/mob/living/basic/lavaland/mining.dm
> +			drop_immediately = basic_mob_flags & DEL_ON_DEATH\
```suggestion
			drop_immediately = basic_mob_flags & DEL_ON_DEATH,\
```

2023-07-11 03:15 UTC, merged