Clarifies some silicon interactions via examine, also converts some stuff to balloon alerts
tgstation/tgstation pull request #76690
Opened 2023-07-09 18:53 UTC by nikothedude

## About The Pull Request

APCs, fire alarms, and holopads now communicate a few more hotkeys for interaction with silicons via examine. Ex. APCs now tell silicons they can disable lighting with shift-click. 

## Why It's Good For The Game

1. Balloon alerts are cool.
2. UX is also cool.

## Changelog

:cl:
qol: APCs, fire alarms, and holopads now communicate some more of their silicon interactions via their examine text.
qol: APCs, fire alarms, holopads and turret control panels now use balloon alerts for more of their notifications.
/:cl:

2023-07-09 19:22 UTC, Mothblocks requested changes
Small nits, looks good

2023-07-09 19:22 UTC, Mothblocks commented on code/_onclick/ai.dm
> +		balloon_alert(user, "environment power toggled [on_or_off]")
Nit: I usually like `enabled/disabled` in balloon alerts

2023-07-09 19:22 UTC, Mothblocks commented on code/_onclick/ai.dm
> +		balloon_alert(user, "lighting power toggled [on_or_off]")
Same nit, it makes these nicer to read

2023-07-09 19:22 UTC, Mothblocks commented on code/game/machinery/firealarm.dm
> +		. += span_notice("Ctrl-Click the fire alarm to toggle thermal sensors, which controls auto-activation.")
This should be a contextual screentip. We should add those to fire alarms if we don't already

2023-07-09 19:22 UTC, Mothblocks commented on code/game/machinery/firealarm.dm
> +	//to_chat(user, span_notice("You [ my_area.fire_detect ? "enable" : "disable" ] the local firelock thermal sensors!"))
Commented code?

2023-07-09 19:22 UTC, Mothblocks commented on code/modules/power/apc/apc_power_proc.dm
> +		balloon_alert(user, "power toggled [on_or_off]")
Same nit

2023-07-09 19:22 UTC, Mothblocks commented on code/modules/power/apc/apc_main.dm
> +		. += span_notice("Shift+Ctrl-Click the APC to toggle environment power.")
These should be contextual screentips

2023-07-09 19:51 UTC, nikothedude commented on code/game/machinery/firealarm.dm
> +	//to_chat(user, span_notice("You [ my_area.fire_detect ? "enable" : "disable" ] the local firelock thermal sensors!"))
whoopsie

2023-07-09 20:07 UTC, Dorsisdwarf commented
as an ai who likes to turn the lights out to save power thank you so much.

2023-07-09 20:32 UTC, nikothedude commented
> as an ai who likes to turn the lights out to save power thank you so much.

didnt add the hotkey, just adding some UX to display it

2023-07-09 20:49 UTC, nikothedude commented
all done

2023-07-09 20:53 UTC, Mothblocks approved these changes

2023-07-09 20:53 UTC, Mothblocks commented on code/modules/power/apc/apc_main.dm
> +			SCREENTIP_CONTEXT_CTRL_SHIFT_LMB = "Toggle environment power"
```suggestion
			SCREENTIP_CONTEXT_CTRL_SHIFT_LMB = "Toggle environment power",
```

2023-07-13 01:29 UTC, merged

2023-07-16 20:55 UTC, Dorsisdwarf commented
> > as an ai who likes to turn the lights out to save power thank you so much.
> 
> didnt add the hotkey, just adding some UX to display it

yeah but I didnt know it