Makes sure viruses check for virus immunity BEFORE attempting to infect.
tgstation/tgstation pull request #76884
Opened 2023-07-16 10:50 UTC by necromanceranne

## About The Pull Request

Ensures that TRAIT_VIRUSIMMUNE is checked before attempting to infect.

Adds CanContractDisease() checks to the CRISPR and miasma breath code.

Fixes https://github.com/tgstation/tgstation/issues/76640

## Why It's Good For The Game

Immunity is immunity.

## Changelog

:cl:
fix: Ensures virus immune creatures are properly immune to viruses, even if something tries to force it to be infected with a virus.
/:cl:

2023-07-16 19:20 UTC, MrMelbert requested changes
Don't think these checks should be in `try_infect`

`try_infect` should not be called outside of the virus besides through `ForceContractDisease` 

So those uses should be changed

2023-07-16 19:22 UTC, MrMelbert commented
(Case in point, adding those trait checks makes the `bypass_immunity` var nonfunctional)

2023-07-17 00:48 UTC, necromanceranne commented
Hmm alrighty

2023-07-17 17:30 UTC, MrMelbert approved these changes

2023-07-17 17:33 UTC, merged