Starlight colors with parallax, small parallax code clean-up
tgstation/tgstation pull request #77020
Opened 2023-07-22 13:18 UTC by Time-Green

The space gas parallax now colors starlight in the color of the gas: 

![image](https://github.com/tgstation/tgstation/assets/7501474/18b5554f-6357-473e-8f43-64aad1517be0)

I also cleaned up parallax random code a bit, making it easier to add new parallaxes and add minor effects to them

The radioactive nebula parallax thing has also been moved to SSparallax to make it easier and a bit more sane to change

:cl:
sprite: Starlight will color with space gas parallax
code: Cleans up random parallax code / radioactive nebula parallax code
/:cl:

## Why it's good for the game

We can change the starlight color now (mostly thanks to lemon), so I thought it'd be fun to actually do! If people hate it, I'll turn it off we can just call this a code clean-up PR

2023-07-22 13:42 UTC, AdipemDragon commented
finally! I've been waiting for this literally ever since the first pr that gave space light!

2023-07-22 14:36 UTC, Time-Green commented on code/controllers/subsystem/processing/station.dm
> +	SSparallax.random_layer.apply_global_effects() //Apply station effects that parallax might have
This seemed the most sensical place to put this? SSparallax inits before globals do, so we can't really change anything there. SSstation is already used for stuff like this with station traits (and I'm familiar with it)

2023-07-22 19:49 UTC, Dorsisdwarf commented
god bless the pisslight shall be real

2023-07-22 23:50 UTC, Wallemations commented
We in a Corsair k55 RGB gaming keyboard now

2023-07-28 14:45 UTC, Jacquerel requested changes
I want to see if this makes it easier to make space look cool during aurora caelis (or if it's too slow) 
Not directly related to this pr though

2023-07-28 14:45 UTC, Jacquerel commented on code/controllers/subsystem/parallax.dm
> +	random_layer = new picked_parallax(null, null, TRUE) //rip no named params, but we set template to TRUE so we don't del without a hud owner
```suggestion
	random_layer = new picked_parallax(null, null, /* template = */ TRUE) //rip no named params, but we set template to TRUE so we don't del without a hud owner
```
Mothblocks has suggested this pattern before where named args are not possible, would be nice to add all 3

2023-07-29 08:11 UTC, Time-Green commented
@Jacquerel I've added the inline comments for the params!

2023-07-29 12:21 UTC, merged

2023-07-30 01:56 UTC, LemonInTheDark commented
PISSLIGHT PISSLIGHT (fuck you the blue was soo pretty, that green's alright tho. Might be worth making starlight a bit less vibrant then the parallax color, could use that generically with HSV I think)

2023-07-30 07:59 UTC, Time-Green commented
> PISSLIGHT PISSLIGHT (fuck you the blue was soo pretty, that green's alright tho. Might be worth making starlight a bit less vibrant then the parallax color, could use that generically with HSV I think)

Default starlight still happens when there's no gas-clouds, but yeah maybe the saturation of the space-light could be turned down for the colored gas-clouds

2023-07-30 08:46 UTC, Time-Green commented
@Jacquerel we could probably do RGB parallax / aurora caelis by coloring the gas cloud and punting the appropriate light settings into a background subsystem