Adds a Heresy phobia, replacing the supernatural phobia on heretic sacrifices
tgstation/tgstation pull request #77048
Opened 2023-07-23 21:15 UTC by DATA-xPUNGED

## About The Pull Request

This is a rebase of #72563
This adds a new "Heresy" phobia, which replaces the supernatural phobia on heretic sacrifices. However, sacrificing another heretic does not give them this phobia, but makes them not able to use spells until they do a Mansus Restoration ritual.
I am doing this as a draft for now because i need HELP with the code. I've been copy pasting my way into PRs up until now.

## Why It's Good For The Game

Makes wizards, chaplains, heretics, and cultists able to keep playing the video game as their role when they're sacrificed.

## Changelog

:cl:
add: Added a phobia of heresy, which replaces the phobia of the supernatural on heretic sacrifices
/:cl:

2023-07-23 21:33 UTC, Profakos commented
Aw dang I never got around to do my version.

2023-07-23 22:29 UTC, Helg2 commented
Please don't copypaste code from the pr except phobia part, it's just won't work and i'm feeling like a shittone of shame

2023-07-23 23:59 UTC, DATA-xPUNGED commented
> Please don't copypaste code from the pr except phobia part, it's just won't work and i'm feeling like a shittone of shame

as it is a rebase, i've pretty much copied everything, i am trying to figure out how to MAKE IT work

2023-07-24 12:05 UTC, DATA-xPUNGED commented
> Aw dang I never got around to do my version.

If you have idea on how to help feel free to PR it

2023-07-24 12:27 UTC, Helg2 requested changes

2023-07-24 12:27 UTC, Helg2 commented on code/_globalvars/phobias.dm
> +	"heresy",
Redundant "heresy"

2023-07-24 12:27 UTC, Helg2 commented on code/_globalvars/phobias.dm
> +	)),
Redundant and non-alphabetical

2023-07-24 12:27 UTC, Helg2 commented on strings/phobia.json
> +"falling": [
non alphabetical too

2023-07-24 12:27 UTC, Helg2 commented on code/modules/antagonists/heretic/knowledge/sacrifice_knowledge/sacrifice_knowledge.dm
> +
Linters are probably failing because of a space here

2023-07-24 12:28 UTC, DATA-xPUNGED commented on code/_globalvars/phobias.dm
> +	"heresy",
I knew i missed one

2023-07-24 12:28 UTC, Helg2 commented on code/_globalvars/phobias.dm
> +	"heresy",
```suggestion
```

2023-07-24 12:29 UTC, Helg2 commented on code/_globalvars/phobias.dm
> +	)),
```suggestion
```
redundant and non-alphabetical

2023-07-24 13:51 UTC, nukularpower commented
why not have this linked to the hand dodging minigame?   like dodging some number of hands like 80-100% makes it so you dont get the trauma or something like that

2023-07-24 14:03 UTC, DATA-xPUNGED commented
> why not have this linked to the hand dodging minigame? like dodging some number of hands like 80-100% makes it so you dont get the trauma or something like that

The trauma is an replacement for the old interaction where it just fucking gibbed you on sacrifice. So instead it effectively round removes you in the heretic's eyes. With that in mind i don't think that's a good idea

2023-07-29 14:18 UTC, DATA-xPUNGED commented
I've got no idea why those unit tests are failing tbh, i didn't touch head.dm

2023-08-01 23:00 UTC, DATA-xPUNGED commented
Everyone who i have pestered to try and find out why the unit test isn't working has NO IDEA why it isn't, i give up, I'm manually rebasing this again

2023-08-01 23:00 UTC, closed without merging