Adds an Indebted negative quirk to the game.
tgstation/tgstation pull request #77138
Opened 2023-07-26 18:25 UTC by Ghommie

## About The Pull Request
This Pull Request brings a new negative quirk to the list of negative quirks: Indebted. As the title suggests, you start the round with a pretty high debt of roughly 15.000 credits (give or take up to 1.250 credits), and everytime the account balance would increment, 75% of what's earned will be pushed toward solving it instead.

Unlike other quirks, it shown by medical HUDS and the health analyzers, because I frankly believe it's quite a stretch putting it on the same plane as other quirks which are of a more "psycho-physical" nature. However, examining the records desc will return a remark on how the quirk holder has had some difficulties paying the checkup bill in full. Examining their ID accurately will also report the debt.

Currently a draft, since I still have to add an achievement (name pending) for successfully paying off the whole debt. I am also welcoming suggestions.

## Why It's Good For The Game
I think it's cool to have a quirk that affects players from an angle different than most of the others. It doesn't affect the mob directly, brings no positive or negative moodlet, gives items, but it does cripple what they can do with their own bank account. Sure, it can be circumverted by "borrowing" another player mob's ID card, but frankly it has a mild negative value on par with "Family Heirloom" so it's not a big deal.

## Changelog

:cl:
add: Added an Indebted negative quirk to the game, which gives the holder's bank account a debt averaging at 15000 credits and forces 75% of all earnings towards solving it.
/:cl:

2023-07-26 18:32 UTC, Sealed101 commented
could use something from Resettear for the cheevo name, but probably not the Capitalism, Ho! quote 🤔

2023-07-26 18:35 UTC, the-orange-cow commented
Is there a way to manually send in funds to pay off the debt?

2023-07-26 18:42 UTC, Ghommie commented
> Is there a way to manually send in funds to pay off the debt?

Not yet, but I'll make sure sure to add one.

> Edit: also, does this affect round start funds?

No, the initial 5 paychecks worth of funds are deposited before the quirk is added. I suppose it's ok to keep it that way, since it's going to be just a fraction of the whole debt whatsoever.

2023-07-26 19:18 UTC, Mickyan commented
This is wildly out of scope but what would make this quirk so much more fun is if instead of getting a fixed number, your debt increases a bit every round but the amount you owe is saved through persistence (with a cap probably)

2023-07-26 20:35 UTC, AtomTheProphet commented
> This is wildly out of scope but what would make this quirk so much more fun is if instead of getting a fixed number, your debt increases a bit every round but the amount you owe is saved through persistence (with a cap probably)

This would be _very_ nice.

2023-07-26 23:29 UTC, VladinXXV commented
I think it'd be funny to just make the achievement name "Outdebted". In-debted => out-debted.

2023-07-27 01:14 UTC, EricZilla commented
I think having a way to pay it off other than passively will make this just free points for certain jobs, but maybe you could have it also deduct from bounties as a method of actively paying it off? Like it takes 25% of bounties too

2023-07-28 02:58 UTC, san7890 commented on code/datums/quirks/negative_quirks/negative_quirks.dm
> +		quirk_holder.client.give_award(/datum/award/achievement/misc/debt_extinguished, quirk_holder)
maybe something about garnishment for the name? idk

2023-07-29 10:48 UTC, YakumoChen commented
> I think having a way to pay it off other than passively will make this just free points for certain jobs, but maybe you could have it also deduct from bounties as a method of actively paying it off? Like it takes 25% of bounties too

`			. += span_warning("The account is currently indebted for [registered_account.account_debt] cr. [100*DEBT_COLLECTION_COEFF]% of all earnings will go towards extinguishing it.")`

It takes off from any money you receive, not just paycheques, given the PR title says 75% that means it takes 3/4ths of every bounty you do too.

2023-08-02 21:54 UTC, Sealed101 commented
magnificent

2023-08-07 16:39 UTC, Jacquerel requested changes
One small change and it looks good to go

2023-08-07 16:39 UTC, Jacquerel commented on code/datums/records/manifest.dm
> +		major_disabilities = person.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, TRUE),
Name these arguments please

2023-08-07 16:39 UTC, Jacquerel commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +			render_list += "<span class='info ml-1'>Subject Major Disabilities: [carbontarget.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, TRUE)].</span>\n"
These too

2023-08-07 16:39 UTC, Jacquerel commented on code/modules/mob/living/carbon/human/human.dm
> +				var/quirkstring = get_quirk_string(TRUE, CAT_QUIRK_ALL, TRUE)
And here

2023-08-07 16:41 UTC, Ghommie commented on code/datums/records/manifest.dm
> +		major_disabilities = person.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, TRUE),
```suggestion
		major_disabilities = person.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, from_scan = TRUE),
```

2023-08-07 16:41 UTC, Ghommie commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +			render_list += "<span class='info ml-1'>Subject Major Disabilities: [carbontarget.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, TRUE)].</span>\n"
```suggestion
			render_list += "<span class='info ml-1'>Subject Major Disabilities: [carbontarget.get_quirk_string(FALSE, CAT_QUIRK_MAJOR_DISABILITY, from_scan = TRUE)].</span>\n"
```

2023-08-07 21:21 UTC, merged

2023-08-08 10:59 UTC, VladinXXV commented
![image](https://github.com/tgstation/tgstation/assets/44104681/671ea318-ae8d-46cf-924f-44407871654d)
done

2023-08-08 11:03 UTC, Sealed101 commented
what a sweatlord smh