Added Omen Spontaneous Combustion and light tube and mirror effects
tgstation/tgstation pull request #77175
Opened 2023-07-28 03:43 UTC by carlarctg

## About The Pull Request

Cursed crewmembers can randomly, extremely rarely, spontaneously combust for no reason.

Cursed crewmembers can get zapped by nearby light tubes.

Cursed crewmembers can freak out when passing by mirrors.

To make up for these, triggering a cursed effect is slightly less than half as likely now when walking around now.

## Why It's Good For The Game

Cursed is fun as hell, but after a certain point it gets kind of monotonous - it's airlocks, vending machines, and the rest is too rare to count. We need more ways to comically get hurt in the game.

You might dislike the 'reduced effects' bit but trust me it is incredibly frickin' common to have shit happen to you. Add to the occasional vending machine and airlock crushes the near-constant light tubes all over the station? Yeah, that needs a toning down else it will be just a tad too miserable to be funny. Also cause the poor janitor unneeded stress.

## Changelog

:cl:
add: Cursed crewmembers can randomly, extremely rarely, spontaneously combust for no reason.
add: Cursed crewmembers can get zapped by nearby light tubes.
add: Cursed crewmembers can freak out when passing by mirrors.
add: To make up for these, triggering a cursed effect is slightly less than half as likely now when walking around now.
/:cl:

2023-07-28 04:25 UTC, MrMelbert commented on code/datums/components/omen.dm
> +	if((rand(10000) == 10000) && (living_guy.stat != DEAD)) // You hit the lottery! Kinda.
```suggestion
	if(prob(0.001) && (living_guy.stat != DEAD)) // You hit the lottery! Kinda.
```

2023-07-28 14:05 UTC, carlarctg commented on code/datums/components/omen.dm
> +	if((rand(10000) == 10000) && (living_guy.stat != DEAD)) // You hit the lottery! Kinda.
Wasn't sure if prob handled decimals

2023-07-28 20:03 UTC, Ghommie commented on code/datums/components/omen.dm
> +		living_guy.adjust_fire_stacks(6)
```suggestion
		living_guy.adjust_fire_stacks(20)
```
It's the frikkin jackpot, come on. :joy:

2023-08-02 12:49 UTC, Time-Green requested changes

2023-08-02 12:49 UTC, Time-Green commented on code/datums/components/omen.dm
> +			if(!permanent && !prob(66.6))
```suggestion
			if(!permanent && prob(33.3))
```

2023-08-04 23:55 UTC, carlarctg commented on code/datums/components/omen.dm
> +				to_chat(living_guy, span_warning("You feel lucky, somehow."))
```suggestion
				to_chat(living_guy, span_notice("You feel lucky, somehow."))
```

2023-08-05 12:04 UTC, merged