Adds in the Tactical Deniability Implant for nukeops.
tgstation/tgstation pull request #77214
Opened 2023-07-29 17:48 UTC by CRITAWAKETS

## About The Pull Request

This PR adds in the Tactical Deniability Implant to the nuclear operative uplink for 6 TC. It's new version of the minibomb, implanted directly into your brain.
It disables softcrit and hardcrit, making it extremely powerful... For about 10.7 seconds (without stacked minibombs), before you realize what the increasing beeping is for, and proceed to explode. Even atropine can't save you from this one.

There is kind of a buff in that the delay of mini/macrobombs can no longer reach 30 seconds, since it just makes things a lot more interesting with a time cap (and also you'd need like 4 macrobombs to reach it so it mostly only impacts this new feature)

## Why It's Good For The Game

It's an interesting tradeoff where you can survive for a bit after critical condition, but whenever it triggers you've effectively sealed your own fate. Even if a helpful operative comes along to heal you, you WILL explode.

## Changelog

:cl:
add: The Syndicate has begun rolling out new Tactical Deniability Implants for their Nuclear Operative teams. It seems these implants are designed to make teams "fight harder" by "giving incentives for fighting to the bitter end", whatever they're talking about.
/:cl:

2023-07-29 17:51 UTC, Sealed101 commented on code/game/objects/items/implants/implant_explosive.dm
> +	desc = "An enchanced version of the microbomb that directly plugs into the brain. No downsides, promise!"
```suggestion
	desc = "An enhanced version of the microbomb that directly plugs into the brain. No downsides, promise!"
```

2023-07-29 18:34 UTC, Sealed101 commented on code/game/objects/items/implants/implant_explosive.dm
> +/obj/item/implant/explosive/proc/explode()
might as well make use of this proc in `activate()`, L81

2023-07-29 21:41 UTC, TheObserver-sys commented
This inspires the pure CEO mindset into any and all syndicate operatives. Encourages them to invest, to have a 10 year plan, demonstrates the fact they have the soul of an emperor when they live through an operation, that they have kept their divine light intact.

2023-08-02 12:33 UTC, Time-Green requested changes
Could you just move this stuff into explode() aswell? 
![image](https://github.com/tgstation/tgstation/assets/7501474/316fa510-48a7-4888-8df9-311186c84a13)

Remind me that all the sleep-while code needs to be murdered

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +				qdel(other_implant)
Could you put the explosion merging into it's own proc? Then you wont have to copypaste it in the next block

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			sleep(delay / 5)
```suggestion
			sleep(delay * 0.2)
```

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			delay -= delay / 5
```suggestion
			delay -= delay * 0.2
```
Multiplication is preferred when possible

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			var/beep_volume = 35
I don't see the point in this var

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			var/beep_volume = 35
Ditto

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			playsound(loc, 'sound/items/timer.ogg', beep_volume, FALSE)
```suggestion
			playsound(loc, 'sound/items/timer.ogg', vol = 35, vary = FALSE)
```

Use named params for readability

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			playsound(loc, 'sound/items/timer.ogg', beep_volume, FALSE)
```suggestion
			playsound(loc, 'sound/items/timer.ogg', vol = 35, vary = FALSE)
```

Ditto

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +/obj/item/implant/explosive/deniability
Autodoc the type

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +	target.add_traits(list(TRAIT_NOSOFTCRIT, TRAIT_NOHARDCRIT), IMPLANT_TRAIT)
I don't think this should be applying on failed implanting

2023-08-02 12:33 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +	target.remove_traits(list(TRAIT_NOSOFTCRIT, TRAIT_NOHARDCRIT), IMPLANT_TRAIT)
Should this be getting removed on failed removal?

2023-08-02 12:33 UTC, Time-Green commented on code/modules/uplink/uplink_items/nukeops.dm
> +/datum/uplink_item/implants/macrobomb
Macrobomb?

2023-08-02 12:33 UTC, Time-Green commented on code/modules/uplink/uplink_items/nukeops.dm
> +	item = /obj/item/storage/box/syndie_kit/imp_macrobomb
Macrobomb?

2023-08-02 12:53 UTC, Time-Green commented on code/game/objects/items/implants/implant_explosive.dm
> +			var/beep_volume = 35
Oh, I missed that

2023-08-08 13:35 UTC, CRITAWAKETS commented
Hi, I've been sick a while, so it took a bit for me to get to fixing this up.

If anyone has any suggestion for the sleep-while code to be replaced with something which provides the same effect (a rapidly increasing beeping, dependant on delay) but isn't as poorly done, please do tell. I hate sleep() with a burning passion.

2023-08-08 15:17 UTC, merged