Biogenerators can be unwrenched
tgstation/tgstation pull request #77366
Opened 2023-08-04 06:18 UTC by carlarctg

## About The Pull Request

Biogenerators can be unwrenched

## Why It's Good For The Game

If significantly more round impacting things like smoke machines and hydro trays that drop plants that turn into meth bath salts krokodil smoke can be unwrenched i dont see why this cant

## Changelog

:cl:
qol: Biogenerators can be unwrenched
/:cl:

2023-08-04 18:39 UTC, san7890 requested changes
> > I believe it is used as a wall machine on some maps, so you should probably copy the logic from smartfridge to make it require unwelding before unwrenching.
> 
> nah

you should at the very least copy the atmos blocking logic from the smartfridge because otherwise lemoninthedark will smash your skull in with a wrench

2023-08-04 20:34 UTC, carlarctg commented
> > > I believe it is used as a wall machine on some maps, so you should probably copy the logic from smartfridge to make it require unwelding before unwrenching.
> > 
> > 
> > nah
> 
> you should at the very least copy the atmos blocking logic from the smartfridge because otherwise lemoninthedark will smash your skull in with a wrench. i don't recall if biogenerators are still placed within walls, but if they are you'll likely have to fix that across the maps because that is really stupid. you can ignore this if they aren't placed in walls, but i think they should still have atmos blocking some way (even if it's not in this PR)

siiiiiiiiigh.............................................

2023-08-04 23:54 UTC, carlarctg commented
@san7890

2023-08-09 11:17 UTC, Ghommie requested changes

2023-08-09 11:17 UTC, Ghommie commented on code/modules/hydroponics/biogenerator.dm
> +	if(!tool.use_tool(src, user, delay=100, volume=100))
```suggestion
	if(!tool.use_tool(src, user, 10 SECONDS, volume=100))
```
10 seconds seem a tad much, but I'm not against the option of securing it in place in any way.

2023-08-09 11:17 UTC, Ghommie commented on code/modules/hydroponics/biogenerator.dm
> +		if(!tool.use_tool(src, user, delay=100, volume=100))
```suggestion
		if(!tool.use_tool(src, user, 10 SECONDS, volume=100))
```

2023-08-09 20:35 UTC, merged