New sprites for bottles
tgstation/tgstation pull request #77365
Opened 2023-08-04 02:27 UTC by MTandi

![image](https://github.com/tgstation/tgstation/assets/3625094/addf5876-0b62-474a-9d92-0ed6f8216e5b)

## About The Pull Request

Updates sprites of many bottles.

Combined effort of three:
Most of these are donated by Kryson. 
I tweaked them and added the missing bottles. 
Zeckle provided the base for the Voltaic Wine Bottle.

## Why It's Good For The Game

They look more consistent with other 3/4 items.

## Changelog

:cl: Kryson, MTandi, Zeckle (Mike)
image: New bottle sprites
/:cl:

2023-08-04 02:33 UTC, Loafin34 commented
the soul of captain's flask....... smh my head....

2023-08-04 02:35 UTC, Cheshify commented
The inubashiri sake is a specific touhou reference. I don't see the same in the new sprite?

2023-08-04 02:38 UTC, MTandi commented
> The inubashiri sake is a specific touhou reference. I don't see the same in the new sprite?

Didn't know that. Will address.

2023-08-04 02:46 UTC, Cheshify commented
[]((https://en.touhouwiki.net/wiki/Momiji_Inubashiri))
It's literally some wolf girl from touhou 10. The OG bottle's icon has her "tokin" (little red hat). Maybe adding a maple leaf or similar design to the new bottle could work?

2023-08-04 02:48 UTC, CoiledLamb commented
does the ethereal flask still have an animation?

2023-08-04 02:53 UTC, MTandi commented
> does the ethereal flask still have an animation?

It doesn't.

2023-08-04 02:55 UTC, CoiledLamb commented
> > does the ethereal flask still have an animation?
> 
> It doesn't.

all good. might add one later when this gets merged (something smaller scale, maybe the same effect but on the face on the front rather than the whole bottle)

2023-08-04 02:57 UTC, JohnFulpWillard commented
> The inubashiri sake is a specific touhou reference. I don't see the same in the new sprite?

it is morally correct to remove touhou references

2023-08-04 03:06 UTC, Wallemations requested changes
No comment on the Touhou reference, but the sabered champagne bottle should have its neck more crooked to emphasize the slice, like the original had.

2023-08-04 04:01 UTC, carshalash commented
Fellow bombay sapphire enjoyer

2023-08-04 04:07 UTC, carshalash commented
Can you explain the lizard wine sprite?  Isn't there meant to be some indication of a tail in the bottle? 

Also, is the absinthe one meant to be green fairy?

2023-08-04 06:02 UTC, Loafin34 commented
@carshalash it looks like there's a seraka mushroom instead, the tiziran mushroom thing that that one cook PR added

2023-08-04 06:05 UTC, AdipemDragon commented
slightly sad about the shaker's loss of what little ornatability it had, specially on the comemorative NT one, but yeah the bottles are _nice,_ more a reason to make a bottle display like how pubby had one by default

2023-08-04 07:15 UTC, Jezzared commented
I concur with adipem. The commemorative shaker was always a fun surprise and now i might not even notice it.

If you wanna keep the simple NT logo on it instead of the "I <3 NT", maybe some NT-blue bands?

2023-08-04 08:25 UTC, bluetshirtguy commented
Turning a lot of the different designs/art on the bottles labels with generic "text" is pretty boring.

2023-08-04 08:59 UTC, Likteer commented
I really like the Extra strong absinthe.
The skull on the label got squashed in a previous resprite.
Now the tiny wall of text fits all the random warnings they get in the name.

2023-08-04 09:13 UTC, MTandi commented
> No comment on the Touhou reference, but the sabered champagne bottle should have its neck more crooked to emphasize the slice, like the original had.

![image](https://github.com/tgstation/tgstation/assets/3625094/d6ca892f-6baa-4292-bb7a-cd83d01f6728)

> [https://en.touhouwiki.net/wiki/Momiji_Inubashiri#Design] It's literally some wolf girl from touhou 10. The OG bottle's icon has her "tokin" (little red hat). Maybe adding a maple leaf or similar design to the new bottle could work?

I thought it's some specific bottle like with voltaic wine. How is this supposed to be a reference? Looks like a clump of pixels to me. I have no clue how to refer this character in a bottle design, so leaving this up to you or whoever else who is willing to put this reference back.

> Can you explain the lizard wine sprite? Isn't there meant to be some indication of a tail in the bottle?
> 
> Also, is the absinthe one meant to be green fairy?

These are from @Krysonism, I'm not sure.

2023-08-04 10:07 UTC, Sealed101 commented
![derp](https://github.com/tgstation/tgstation/assets/75863639/dc3aa51a-01c3-4b16-8b54-8eb737775c8f)

is icondiffbot drunk of off all these drinks or did you not animate the blazaam phasing in and out of view

2023-08-04 10:16 UTC, MTandi commented on code/modules/reagents/reagent_containers/cups/glassbottle.dm
> +	make_froth(offset_x = 0, offset_y = sabraged ? 7 : 14, intensity = froth_severity) //the y offset for sabraged is lower because the bottle's lip is smashed
![image](https://github.com/tgstation/tgstation/assets/3625094/86456b94-9852-41a1-bd87-74552ab221eb)

I'm not sure what it supposed to do? Looks fine to me whatever it is.

2023-08-04 10:16 UTC, MTandi commented
> ![derp](https://user-images.githubusercontent.com/75863639/258390312-dc3aa51a-01c3-4b16-8b54-8eb737775c8f.gif)
> 
> is icondiffbot drunk of off all these drinks or did you not animate the blazaam phasing in and out of view

IconDiffBot thing

![image](https://github.com/tgstation/tgstation/assets/3625094/a1688953-92c3-427f-9c06-91bfb4c8024d)

2023-08-04 10:18 UTC, MTandi commented on code/modules/reagents/reagent_containers/cups/glassbottle.dm
> +	make_froth(offset_x = 0, offset_y = sabraged ? 7 : 14, intensity = froth_severity) //the y offset for sabraged is lower because the bottle's lip is smashed
I reverted these values and adjusted the sprite to make the holes at the same level as before.

2023-08-04 13:55 UTC, MTandi commented
Changed holy water flask and made a separate sprite for unholy water flask

![image](https://github.com/tgstation/tgstation/assets/3625094/b371225b-bfd2-40ba-bd63-e7f1401dc08a)

2023-08-04 17:32 UTC, Wallemations approved these changes
Much better on the sabered one

2023-08-05 07:32 UTC, Twaticus commented
yeahhh YEAHHHH

2023-08-05 07:55 UTC, LSommers commented
Banger sprite updates that actually look like what they're updating
This is a certified MTandi classic

2023-08-05 13:13 UTC, merged

2023-08-05 13:16 UTC, MTandi commented on code/modules/reagents/reagent_containers/cups/glassbottle.dm
> +	make_froth(offset_x = 0, offset_y = sabraged ? 7 : 14, intensity = froth_severity) //the y offset for sabraged is lower because the bottle's lip is smashed
Forth seems to be broken, i've seen that there are effects that are supposed to spawn in the icons, but it doesn't happen in-game.

2023-08-05 13:40 UTC, Sealed101 commented on code/modules/reagents/reagent_containers/cups/glassbottle.dm
> +	make_froth(offset_x = 0, offset_y = sabraged ? 7 : 14, intensity = froth_severity) //the y offset for sabraged is lower because the bottle's lip is smashed
![cover3](https://github.com/tgstation/tgstation/assets/75863639/65ee686b-305f-496a-98f7-fbf28d9c8639)


smellbert curse you #71810 PR MURDER BARELY A MONTH IN REEEE