Mixological Masterful: Makes shaking drinks a thing
tgstation/tgstation pull request #77557
Opened 2023-08-12 11:21 UTC by EOBGames

## About The Pull Request
Changes up shakers to be shakeable, and adds a shaking requirement to a series of drinks.

Alt-click caps and uncaps the shaker. While it's sealed, clicking inhand shakes. While uncapped, stuff can be poured out or in.

Shaken drinks:
- Vodka Martini
- Pan-Galactic Gargle Blaster
- Toxins Special
- Beepsky Smash
- Irish Cream
- Margarita
- Bahama Mama
- Antifreeze
- Painkiller
- Changeling Sting
- Devil's Kiss
- Banana Honk
- Silencer
- Thirteen Loko
- Whiskey Sour
- Eggnog
- Quadruple Sec
- Grasshopper
- Quintuple Sec
- Alexander
- Sidecar
- Between the Sheets
- Kamikaze
- Branca Menta
- Jack Rose
- Blazaam
- Mauna Loa
- Amaretto Alexander
- Yuyakita
- Banzai Ti
- Imperial Mai Tai
- Konococo Rumtini
- Blue Hawaiian
- Maui Sunrise
- Protein Blend
- Sea Breeze
- Salt and Swell
- Tich Toch
- Tropical Storm

Drinks were chosen based on a few factors- any real life drink that is shaken was added, and for fictional drinks, I generally picked anything that had an emulsifier (egg white or blood, mostly), pineapple juice or citrus juice since these are general telltales for shaking.

Big thanks to Melbert for providing the shake code; without it, this PR would really not exist.

## Why It's Good For The Game
Gives a little more tactile authenticity to the bartender.

## Changelog

:cl: EOBGames, MrMelbert
add: Shake to your heart's content with the new working shakers! Certain drinks will now need shaken before they're ready to enjoy; for a full list, see the PR.
/:cl:

2023-08-12 11:46 UTC, EricZilla commented
How satisfying is the shake sound, is what we all want to know (probably just me)

2023-08-12 12:03 UTC, CRITAWAKETS commented
I'd prefer my drinks _stirred_, not shaken, thank you.

2023-08-12 12:26 UTC, SomeoneYouProbablyKnow commented
Is the shaker the only implement you can use to shake drinks? Can you circumvent it in some way? But really locking the funny sec heal drink behind the shaker is pretty neat, no more mute sec robbing bar.

2023-08-12 12:46 UTC, AdipemDragon commented
could the reaction search function also say if something needs shaking, just so there's an ingame way to check besides just making your drink and watching it not mix

2023-08-12 19:11 UTC, private-tristan commented
does this mean that bartender is effectively unable to make half their drinks if their shaker gets stolen roundstart/before they join?

2023-08-12 20:16 UTC, MrMelbert commented
> does this mean that bartender is effectively unable to make half their drinks if their shaker gets stolen roundstart/before they join?

you can print shakers in the lathe

2023-08-12 20:36 UTC, san7890 commented
add gravy i've been wanting people to be able to mix gravy in a bottle for at least 14 months now

![image](https://github.com/tgstation/tgstation/assets/34697715/78363d24-2f8e-43ad-8324-5fb351408051)

2023-08-12 20:55 UTC, Justice12354 commented
> add gravy i've been wanting people to be able to mix gravy in a bottle for at least 14 months now
> 
> (image)
> 
> this (was) on the the official blender bottle site btw https://web.archive.org/web/20220629005500/https://www.blenderbottle.com/blogs/recipes/never-fail-blenderbottle-gravy

Make it so when people shake gravy, they say "Oh, so smooth!"

2023-08-13 03:00 UTC, Loafin34 commented
i need the gravy drink. be sure to give it a special interaction with being splashed on people by letting other people eat them for 5 brute damage (because the gravy makes them smell so good)

2023-08-13 04:31 UTC, Wallemations commented
I thought the entire lid's supposed to come off, but only the straining cap gets opened at any time
It's really just up to you, but imo if you removed the whole lid it would make it more visibly obvious which state it's in?

2023-08-13 06:03 UTC, Livrah commented
Can you still make those cocktails with service-chem plumbing?

2023-08-13 09:54 UTC, EOBGames commented
> I thought the entire lid's supposed to come off, but only the straining cap gets opened at any time It's really just up to you, but imo if you removed the whole lid it would make it more visibly obvious which state it's in?

On a real cobbler, yeah, it would ordinarily open up fully- that said, that's also more shading and really general sprite quality to worry about, which is why I didn't do it.

2023-08-13 13:05 UTC, newfren commented
it would be nice if there was a way to shake these without relying solely on the shaker - maybe the mix setting of a grinder?

2023-08-13 23:01 UTC, OmegaDarkPotato commented
Just to be certain- service borgs are still able to produce these drinks with their shaker, yes?

2023-08-14 01:33 UTC, carshalash commented
Controls seem pretty reasonable and accessable to handle. Doesn't interfere with normal drink transference rates which is good.

Only recipe i'm questionable about is changeling sting, isn't that one made with a soda?

2023-08-16 18:25 UTC, Jacquerel requested changes
> could the reaction search function also say if something needs shaking, just so there's an ingame way to check besides just making your drink and watching it not mix

I think this would be a pretty valuable thing to add before the PR is mergeable, although IDK what form it would take.

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +	if(!is_drainable())
```suggestion
	if(is_drainable())
		return ..()
```

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +		to_chat(user, span_warning("You must remove the cap before you can do that!"))
```suggestion
		balloon_alert(user, "remove the cap!")
```

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +		to_chat(user, span_warning("You must remove the cap before you can do that!"))
```suggestion
		balloon_alert(user, "remove the cap!")
```

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +		addtimer(VARSET_CALLBACK(src, shaken, FALSE), 2 SECONDS)
```suggestion
		addtimer(VARSET_CALLBACK(src, shaken, FALSE), 2 SECONDS, TIMER_DELETE_ME)
```
Actually don't know if this is required but might stop something funny happening if you delete the shaker in the 2 seconds before the timer fires.

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +		balloon_alert(user, "cap removed...")
```suggestion
		balloon_alert(user, "cap removed")
```
Ellipses are only for progress bars.

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +		balloon_alert(user, "cap added...")
```suggestion
		balloon_alert(user, "cap added")
```

2023-08-16 18:25 UTC, Jacquerel commented on code/modules/reagents/reagent_containers/cups/drinks.dm
> +	var/mutable_appearance/cap_overlay
Document these vars

2023-09-01 00:09 UTC, closed without merging

2024-04-17 04:08 UTC, randy10122 commented
genuinely considering learning how to work with dm just to finish up this pr. this is too cool to be forgotten

2024-04-20 07:40 UTC, san7890 commented
Good luck