makes ninjas unable to hack more than one borg/scramble security records once
tgstation/tgstation pull request #77578
Opened 2023-08-13 08:15 UTC by zeroisthebiggay

## About The Pull Request

Adds a check to see if a ninja's already hacked a cyborg and scrambled the security records when they try to do it again. If it's already been done, they can't.

## Why It's Good For The Game

Ninjas being able to disrupt the round by creating a fucking miniature army of assault cyborgs is so immesiely powerful I'm questioning why it was never patched out before this. I did it when I ported newja to Citadel, and thought it'd be getting done to here not too long after it.

## Changelog

:cl:
balance: makes ninjas unable to hack more than one borg/scramble security records once
/:cl:

2023-08-13 08:22 UTC, mc-oofert commented
ided pr

2023-08-13 08:42 UTC, zeroisthebiggay commented
> ided pr

ided pr from `September 19, 2021` i took too long to port

2023-08-13 09:10 UTC, Helg2 commented
I understand the nerf but restricting hacking ability just to 1 borg seems kinda lame

2023-08-13 10:31 UTC, Rex9001 commented
1 Borg seems like too little, maybe 2 or 3 or letting people choose their Borg maybe?

2023-08-13 10:33 UTC, zeroisthebiggay commented
> 1 Borg seems like too little, maybe 2 or 3 or letting people choose their Borg maybe?

i could steal code from downstream that lets people pick their module
but infiniborgs is busted

2023-08-13 12:19 UTC, Helg2 commented
Adding a cooldown for hacking borgs, for lets say 5 minutes, will solve most of the issues with borg armies and won't be too lame to ruin fun.

2023-08-13 14:15 UTC, Fikou commented on code/modules/antagonists/ninja/ninjaDrainAct.dm
> +		return
why aren't you returning NONE here

2023-08-13 14:17 UTC, Fikou reviewed
sec record change good idk about borg yet

2023-08-13 16:31 UTC, IndieanaJones commented
Sec record change I think is fine, but the cyborg change I disagree with. Ninja is a heavy threat antagonist, which means supposed strength parity with blob, space dragon, xenomorphs, etc...

If the crew has a lot of cyborgs, then they should be responsible for making sure the ninja doesn't get their hands on them. As strong as ninja is, the crew has the tools to respond in kind (lasers, batons, telecrystal bullshittery) and hacking the borg requires you to stay still for a certain amount of time, opening themselves up for retaliation.

2023-08-13 20:29 UTC, zeroisthebiggay commented on code/modules/antagonists/ninja/ninjaDrainAct.dm
> +		return
fixed in next commit

2023-08-13 20:30 UTC, zeroisthebiggay commented
> Adding a cooldown for hacking borgs, for lets say 5 minutes, will solve most of the issues with borg armies and won't be too lame to ruin fun.

i'm trying to implement this idea because i think it's a god compromise but i'm having a stroke trying to add charges to the hacker module and giving `ninjaDrainAct` a way to use them actually

2023-08-14 03:07 UTC, Jackal-boop commented
Could you also remove the ninjas door hack requirement

2023-08-14 18:19 UTC, san7890 requested changes
I agree with the notion that there could be some balancing, but I believe there should be extensive cooldowns to balance this instead of having "one and done". Try using the `COOLDOWN_DECLARE()` (`cd_index`) system and make it so that they can only transform a borg every `5 MINUTES` or something of that matter (this is an example time, not sure what a good one would be). We can also feed that information to them via the stat panel or something like that using `DisplayTimeText()` or something of that nature.

2023-08-15 03:08 UTC, moocowswag commented
There are so many other ways this can be solved, cooldown, limiting the ammo of the war borgs, increasing threat cost of ninja (the plant charge objective gets shuttle called and ends the round half the time anyway thanks to lazy heads)

And if a ninja is allowed to make his own borgs to hack maybe the station has bigger problems than a ninja

2023-08-22 08:25 UTC, zeroisthebiggay commented
i'll redo this later

2023-08-22 08:25 UTC, closed without merging