Dismemberment moodlets are cleared when recovering your limbs.
tgstation/tgstation pull request #77581
Opened 2023-08-13 09:49 UTC by FernandoJ8

## About The Pull Request

What it says on the tin.
However, the way I've done it, to that ensure replacing a leg when you're missing 4 limbs doesn't clear the moodbuff, has the entertaining side effect of **allowing dismemberment moodlets to stack for each limb you've lost, and being cleared separately.**
I honestly kind of like it.

## Why It's Good For The Game

It doesn't make much sense for your character to continue lamenting the loss of their arm/leg after they've already acquired a replacement.
I also like that this makes losing multiple limbs worse than losing just one, as someone who's been nugget-ed would have a far worse day than someone who has simply lost an arm.

Closes #77388.

## Changelog

:cl:
fix: dismemberment moodlets are cleared when you recover the limb in question.
bal: dismemberment moodlets can now stack for each limb you lose, and are cleared separately.
/:cl:

2023-08-13 09:52 UTC, FernandoJ8 commented
Could a kind soul add the balance tagged? I fucked up the formatting.

2023-08-13 12:21 UTC, HoodMilk commented
Finally

2023-08-13 23:50 UTC, MrMelbert reviewed
The mood event should change description depending on what was removed (`"AHH! I WAS USING THAT LEG!"` / `"AHH! I WAS USING THAT ARM!"`)

Also I'd think losing a limb would be traumatizing even beyond the point to which you regain it at least for a little while

2023-08-13 23:50 UTC, MrMelbert commented on code/modules/surgery/bodyparts/dismemberment.dm
> +	limb_owner.add_mood_event("[body_zone]", /datum/mood_event/dismembered)
```suggestion
	limb_owner.add_mood_event("dismembered_[body_zone]", /datum/mood_event/dismembered)
```

2023-08-13 23:50 UTC, MrMelbert commented on code/modules/surgery/bodyparts/dismemberment.dm
> +	new_limb_owner.clear_mood_event("[body_zone]")
```suggestion
	new_limb_owner.clear_mood_event("dismembered_[body_zone]")
```

2023-08-14 07:44 UTC, FernandoJ8 commented
> The mood event should change description depending on what was removed (`"AHH! I WAS USING THAT LEG!"` / `"AHH! I WAS USING THAT ARM!"`)

Sure! That's good flavour.

> Also I'd think losing a limb would be traumatizing even beyond the point to which you regain it at least for a little while

An alternative idea would be to only clear the moodlet if the new limb is of the same type as the original one (Either specifically the same item or simply the same type? Not sure, the first one might be a nightmare to implement), so getting your old limb or an equivalent would still feel relieving, but if you get it replaced with a cybernetic prosthetic or, god forbid, become a cross-species frankenstein you still lament the loss of your old arm/leg. I think it'd be a neat way to get people to try and recover their old limbs rather than just letting them rot in a hallway.

2023-08-14 17:46 UTC, FernandoJ8 commented
> > An alternative idea would be to only clear the moodlet if the new limb is of the same type as the original one...
> 
> This is a neat idea but let's put a pin in this for a future PR, it might end up being a bit contentious (esp. for people who augment themselves).

It would need some considerations for those cases, certainly.

2023-08-14 22:21 UTC, MrMelbert commented
Subtypes not necessary, all you have to do is override `add_effects` to change the description while passing in the bodypart's plaintext zone or w/e. We have a few mood events that do similar.

2023-08-15 08:53 UTC, FernandoJ8 commented
> Subtypes not necessary, all you have to do is override `add_effects` to change the description while passing in the bodypart's plaintext zone or w/e. We have a few mood events that do similar.

Alright, after the latest commit:
- The description will include what limb was lost
- Rather than clearing the moodlet entirely, it will be replaced by a weaker and shorter one.

2023-08-15 11:12 UTC, FernandoJ8 commented
Should this even be labelled as a fix anymore? It closes the linked issue, but...

2023-08-16 11:50 UTC, Ghommie requested changes
Past simple of fall.

2023-08-16 11:50 UTC, Ghommie commented on code/datums/mood_events/generic_negative_events.dm
> +	description = "Ouch! My limb feels like I feel asleep on it."
```suggestion
	description = "Ouch! My limb feels like I fell asleep on it."
```

2023-08-16 11:50 UTC, Ghommie commented on code/datums/mood_events/generic_negative_events.dm
> +		description = "Ouch! My [limb.plaintext_zone] feels like I feel asleep on it."
```suggestion
		description = "Ouch! My [limb.plaintext_zone] feels like I fell asleep on it."
```

2023-08-16 13:16 UTC, merged