Adds a unit test to check items are dropped when the arm holding them is dismembered.
tgstation/tgstation pull request #77646
Opened 2023-08-15 16:14 UTC by FernandoJ8

## About The Pull Request

What it says on the tin. First time ever making a unit test, so critiques and feedback are very much appreciated.
If anyone thinks of other relevant edge cases, please do bring them up.

## Why It's Good For The Game

Requested in #77613, as the fact it broke again is a regression. Will fail until that PR is merged, as you might expect.

2023-08-15 21:35 UTC, san7890 requested changes

2023-08-15 21:36 UTC, san7890 commented
i updated your PR to have the commit hash of the associated fix pr

2023-08-16 19:03 UTC, san7890 commented
undraft when ready for review/merge

2023-08-16 19:28 UTC, FernandoJ8 commented
> undraft when ready for review/merge

I'm going to be honest with you, I push the last commit and made a mental note to undraft it when the tests passed... and forgot.

2023-08-19 13:12 UTC, Ghommie approved these changes

2023-08-19 13:12 UTC, merged