Fixes vents having "infinite" pressure caps.
tgstation/tgstation pull request #77686
Opened 2023-08-17 02:46 UTC by GuillaumePrata

## About The Pull Request
Unary vents didn't have a pressure cap on either pressuring or siphoning mode.
This allowed 2 unintended behaviours that are now fixed:

The first is that unary vents on pressuring mode would work as "better" Injectors, there is some small pros and cons to each, but we shouldn't have 2 atmos devices that achieve the same goal of "put as much pressure as you have available gas" into a tile.

The second is that we could bypass the pressure caps other atmos pressure/volume pumps have and "put as much pressure as you have available gas" into pipelines, canisters, etc.

## Why It's Good For The Game

Atmos has a lot of cheese strats that we can use to achieve goals, it is part of the charm in mastering the system for a lot of players and it does add some interesting mentoring scenarios where an Elder Atmosian teaches Eldritch pipe knowledge to new players.

But then it comes the problem that a lot of these are unintented and thus are not taken in consideration when doing important balance changes, contradict other "atmos logic", are secret club knowledge that can only be passed from player to player, etc, etc.

The "put infinite pressure on a tile" change is not that important, as that is the injectors' job already.

Now the "put infinite pressure on a pipeline" is something unique (As far as I'm aware since I purposely avoid learning Eldritch atmos tricks) and it is used to achieve a few goals like high temperature/pressure burns.

This one is kinda sad to lose, but if we are going to have an atmos machinery that allows us to "put infinite pressure on a pipeline" that should be in the tin, new players should look into the device and know what atmos goals they can achieve with it, future coders should take that balance in consideration, etc, etc.

I personally want to make that device, but I want discussions if that device is balanced, has good code, good sprites, etc, etc, on another PR.

## Changelog

:cl: Guillaume Prata
fix: Unary vents have a pressure cap on both their pressuring and siphoning mode now, preventing the bypass trick of putting "infinite" pressure on tiles/pipelines.
/:cl:

2023-08-17 03:46 UTC, mikederkan commented
This kills atmos. You should add the proposed machinery alongside this fix.

2023-08-17 03:47 UTC, Pickle-Coding commented
I think the consensus (just Ghilker lol) on this was to add a replacement if we're going to do this. I suppose you could let overclocked volume pumps truly have no pressure limits. They leak a portion of the gas so it would take roughly the same amount of setup and space as unary vents.

2023-08-17 04:31 UTC, GuillaumePrata commented
> I suppose you could let overclocked volume pumps truly have no pressure limits. They leak a portion of the gas so it would take roughly the same amount of setup and space as unary vents.

This would be the simple fix, but the side effect of the volume pump is so trivial to be removed by an atmos tech that I don't even see why it would be needed, simpler to just let volume pumps have no cap with no side effect.

2023-08-17 04:45 UTC, YehnBeep commented
...Aside from how it affects atmos gameplay, this could also make default-setup SM delam recovery more difficult - in that the plasma-oxygen burn, both gases supplied by the SM, might put chamber pressure to the point where the newly-limited vents can't pump in cooling gas anymore and scrubbers can't pull the high-temperature gas out fast enough. In particular, there's a danger of it snowballing since a total cut on the supply of coolant is working to limit an in-progress delam.

Of course the upgraded/optimal setup already uses injectors, this just could make it more unforgiving for running the default setup.

I'd recommend testing to see the practical effect, especially for late-delam recoveries.

2023-08-17 05:23 UTC, GuillaumePrata commented
> I'd recommend testing to see the practical effect, especially for late-delam recoveries.

There are so many different SM setups that I don't know which ones would be viable to test.

The basic roundstart with no changes can get clogged if the SM burns with offline pumps for a minute, but outside of that, 4 pipelines need to clog including the cooling loop.

Don't take me wrong, it will happen, but to get at that point it is crew failure and totally fine, unless we finally decide to update the SM to not be horrible at roundstart.

2023-08-17 05:28 UTC, YehnBeep commented
What I would recommend testing specifically is the roundstart setup with pumps replaced with pipes. The low effort setup most commonly used on TG's main servers, or at least that I see used most often. That's where I'm concerned this change could reduce recoverability by cutting coolant inflow.

2023-08-17 05:31 UTC, GuillaumePrata commented
> What I would recommend testing specifically is the roundstart setup with pumps replaced with pipes. 

If the pipeline goes all the way from the scrubbers into the cooling loop, and somehow keeps it cloged above 5000kpa, that is a really funky delam.

This prep alone should cut basically any clogging from scrubbers and vents.

2023-08-17 05:34 UTC, YehnBeep commented
It's chamber pressure that's my concern above pipe pressure (particularly if the delam isn't caught early), but if you have faith that it won't be a problem, then consider the concern resolved.

2023-08-17 08:55 UTC, rdragan commented
Vents should never have been allowed to siphon in the first place. 
As for killing atmos or the SM - somehow atmos existed before vent siphoning and we managed to fix the SM too. Mainly because there's other ways to achieve the exact same result but I won't be spreading eldritch atmos knowledge on github.

@GuillaumePrata you should just remove vent siphoning wholesale

2023-08-17 14:53 UTC, FlufflesTheDog commented
It's pretty trivial to test how this will effect the supermatter, even if you're on a public server. Setting the vents to external checked, max pressure, I believe matches the proposed behavior.

It's really not great. Turning off the inlet/breaking a pipe to restrict nitrogen, it takes only a handful of seconds (well before the first radio announcement) for enough hot waste to pile into the chamber that **no** new coolant can be added. And being able to put nitrogen into the chamber is a MASSIVE factor in dealing with delaminations, because a hot sm with a high waste multiplier can easily outproduce what even the typical pumpless setup can handle.

It is possible to deal with still, but requires what would have otherwise been last resorts, such as running in with a fire extinguisher, which is a death wish if you're not well prepared.

I'm not too sure how injectors compare to vents in this case, but just swapping to those in the chamber might be enough to avoid these problems.

2023-08-17 16:47 UTC, Pickle-Coding commented
I think vents, scrubbers, and any volume based pump should be able to have a pressure limit (if not lower than their default limit) a bit higher (or equal if that makes Lemon mad) than whatever the pressure inside their input node is. Could allow players to place pumps near the vents to raise pressure and let nitrogen through the chamber if chamber pressure gets too high. Might be more interesting than straight pipe = win, allowing people to trade off between ability to move large amounts of gas or allow gas to efficiently get cooled at reasonable volume.

I will say though that being able to scrub all of the plasma and oxygen in atmos into a pipenet, then connecting into distro is absurdly, extremely powerful, and can cause dense plasmafloods that release enough energy to melt the floor. An overclocked pump might just be too subtle for something that powerful, so it might not actually be a good idea to let overclocked pumps have no pressure limits.

2023-08-18 14:31 UTC, YehnBeep commented
> I think vents, scrubbers, and any volume based pump should be able to have a pressure limit (if not lower than their default limit) a bit higher (or equal if that makes Lemon mad) than whatever the pressure inside their input node is. Could allow players to place pumps near the vents to raise pressure and let nitrogen through the chamber if chamber pressure gets too high. Might be more interesting than straight pipe = win, allowing people to trade off between ability to move large amounts of gas or allow gas to efficiently get cooled at reasonable volume.

It would need to be based on moles, not pressure, to stand any kind of chance. Cold coolant is never going to approach the pressure of a plasma fire in a chamber unless you have just a stupid amount of gas in there, even 100k+ (about 30 roundstart cans of nitrogen) moles likely would not be enough.

But that introduces its own problems because the SM is also sensitive to number of moles its exposed to, so even this approach has knock-on balance considerations.

2023-08-18 17:43 UTC, ZephyrTFA requested changes
I hate to say that this has been the case for so long that it's now a status quo. If you are going to fix it you need to implement the functionality in the same PR.

2023-08-19 01:02 UTC, GuillaumePrata commented
> I hate to say that this has been the case for so long that it's now a status quo. If you are going to fix it you need to implement the functionality in the same PR.

Done, overclocked volume pumps have no cap anymore as that is the most new player friendly and streamlined way to achieve infinite pressure.

2023-08-19 03:57 UTC, ZephyrTFA approved these changes

2023-08-21 13:02 UTC, OverwatchVoice commented
This fixes an unintuitive bug / exploit while simultaneously implementing a variant that people can use more easily, with trade-offs.
I like it!

2023-08-27 02:04 UTC, merged

2023-08-28 22:32 UTC, YehnBeep commented
Well, I'll say it's pretty fun watching the fireworks from this change.

2023-09-12 02:07 UTC, iprice commented
Yeah this definitely heavily impacts SM recovery on TG code, the vents can no longer push any coolant into the engine once a full on 6k temps plasma fire is in progress.  I've sat there on a couple of shifts now as an admin watching and helping guide low pop engineers through fixing the engine and for the life of me couldn't work out why any of the conventional fixes were working, even with the loop fully optimised the N2 level never went above 0.01%.

The only way I could shift this is to forcibly adjust the temperature (as admin) of the gasses in the SM chamber, the lowered resultant pressure would allow some N2 to seep in and once this approaches 50% gas content the system will usually stabilise, but as is, short of massive ammounts of fire extinguishing (also a physics glitch that 'deletes' heat from existence), a job best only done by people with magnetic traction, the high pressure fire/delam situation is far more difficult to recover from than before.