Adds green jester shoes for the green jester outfit.
tgstation/tgstation pull request #77721
Opened 2023-08-18 04:26 UTC by DeerJesus

## About The Pull Request

I went back and did a few fixes for GBP to do this.
This adds a set of green jester shoes to the game and to the autodrobe, since for some reason, while we HAVE jester shoes in the game, it's only for the alternative set of yellow jester clothes. These shoes don't waddle but they do jingle a bit.

## Why It's Good For The Game

There are 0 good shoes that go with the green jester outfit since it's lacking an entire third of the costume for some inconceivable reason. Here are some shoes that go with it and jingle.

## Changelog

:cl:
add: Adds green jester shoes that jingle to the autodrobe!
/:cl:

2023-08-18 21:08 UTC, Wallemations commented
![image](https://github.com/tgstation/tgstation/assets/66052067/3f942147-88d3-4b2e-8dc7-80916ca10b8b)


?

2023-08-18 21:09 UTC, Wallemations requested changes
Fix those icon states

2023-08-18 21:10 UTC, DeerJesus commented
That’s odd, it’s not doing that at all on my end. I’ll try that again.

On Fri, Aug 18, 2023 at 4:09 PM Wallem ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Fix those icon states
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/77721#pullrequestreview-1585225947>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZXNHNWKMLEHXN53A7WQJDXV7K2NANCNFSM6AAAAAA3U7D7TM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-18 21:15 UTC, DeerJesus commented
> Fix those icon states

fixed. apparently i hit save in dream maker editor and save in vscode and it just overrid me fixing the shoes earlier my bad. fix'd

2023-08-19 01:24 UTC, Wallemations approved these changes
Am I allowed to approve sounds? I don't know. The sprites look fine though

2023-08-20 23:50 UTC, Ghommie requested changes
The sound file isn't mono and the project rate is 48000, not 44100. The file is already an .ogg however.
You can easily fix that in Audacity. [Here are the instuctions](https://github.com/tgstation/tgstation/blob/master/sound/standard.md).

2023-08-21 06:09 UTC, DeerJesus commented
Thanks ghommie! I’ll have that fixed in a jiffy

On Sun, Aug 20, 2023 at 6:50 PM Ghom ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The sound file isn't Mono and the project rate is 48000, not 44100. The
> file is already an .ogg however.
> You can easily fix that in Audacity. Here are the instuctions
> <https://github.com/tgstation/tgstation/blob/master/sound/standard.md>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tgstation/tgstation/pull/77721#pullrequestreview-1585981916>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZXNHOPCUU5NAMVMD5SHF3XWKPGBANCNFSM6AAAAAA3U7D7TM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-21 11:17 UTC, Ghommie commented
Oh, by the by, I'd assume the sound is public domain (cc 0), but if not then an attribution should be included in the attributions text file inside the sounds folder.

2023-08-21 13:45 UTC, DeerJesus commented
> Oh, by the by, I'd assume the sound is public domain (cc 0). If not then an attribution should be included in the attributions text file inside the sounds folder.

I added an attribution.

2023-08-21 13:51 UTC, DeerJesus commented
> The sound file isn't mono and the project rate is 48000, not 44100. The file is already an .ogg however. You can easily fix that in Audacity. [Here are the instuctions](https://github.com/tgstation/tgstation/blob/master/sound/standard.md).

This is now done.

2023-08-21 14:00 UTC, Ghommie commented on sound/attributions.txt
> +jingle.ogg is from Zapsplat (CC 4)
```suggestion
jingle.ogg is from Zapsplat (https://www.zapsplat.com/license-type/standard-license/)
```
It doesn't say it's actually CC 4, though it's similar.

2023-08-21 15:42 UTC, merged