Engineers now start with canary
tgstation/tgstation pull request #77740
Opened 2023-08-18 22:12 UTC by Vincent983

## About The Pull Request

Engineers now start with the canary program.

## Why It's Good For The Game

It's annoying having to download it roundstart every game, and it should hopefully inform engineers about it's existence so they can find breaches faster.

## Changelog

:cl:
balance: engineers now start with the canary app preinstalled on their PDAs

/:cl:

2023-08-18 23:22 UTC, JohnFulpWillard requested changes
Atmos techs should have supermatter monitor

Command intentionally does not have card monitor because they each have ID management consoles in their offices.

2023-08-18 23:26 UTC, Vincent983 commented
oh, alright, by the way can I add atmozphere to the engineer PDA as well?

2023-08-19 00:39 UTC, lessthnthree commented
can HoP please get Plexagon Access Management as well?

2023-08-19 01:18 UTC, the-orange-cow commented
It might be prudent to specify which jobs get which apps in your change log.

2023-08-19 02:50 UTC, Jackal-boop commented
I think you can mark this as QOL

2023-08-19 02:53 UTC, Vincent983 commented
fair

2023-08-19 04:02 UTC, carlarctg commented
Give the bounty program to assistants - it was originally meant to but the author didn't know how that worked, and it will let assistants assist.

2023-08-19 04:27 UTC, Vincent983 commented
@carlarctg which bounty program? I'm lookin at the code and they appear to have the bounty board program preloaded, unless is it broken?

2023-08-19 17:29 UTC, carlarctg commented
> @carlarctg which bounty program? I'm lookin at the code and they appear to have the bounty board program preloaded, unless is it broken?

I suppose it 'is' broken, then, or probably more accurately needs to be accessed and 'networked' first for bounties to show up, rather than it being a passive 'New bounty!' thing like it should be. Shame, and out-of-scope for this PR. Ignore me unless you want to put extra effort into this.

2023-08-20 16:35 UTC, JohnFulpWillard commented on code/modules/modular_computers/computers/item/disks/role_disks.dm
> +		/datum/computer_file/program/supermatter_monitor,
This is now just the same as the engineering data disk. Remove one and keep the other

2023-08-20 16:36 UTC, JohnFulpWillard commented
> oh, alright, by the way can I add atmozphere to the engineer PDA as well?

yea sure idk its just an analyzer

2023-08-21 02:59 UTC, dieamond13 commented
I think scientists should also get the science research hub too

2023-08-21 03:43 UTC, Vincent983 commented
god dammit

2023-08-25 00:56 UTC, san7890 requested changes
you can get an extension for vscode that helps you alphabetize with a simple key-command, no reason to do it manually

2023-08-25 00:56 UTC, san7890 commented on code/modules/modular_computers/computers/item/role_tablet_presets.dm
>  		/datum/computer_file/program/budgetorders,
alphabetize this list

2023-08-25 00:56 UTC, san7890 commented on code/modules/modular_computers/computers/item/disks/role_disks.dm
>  		/datum/computer_file/program/alarm_monitor,
alphabetize

2023-08-25 00:56 UTC, san7890 commented on code/modules/modular_computers/computers/item/role_tablet_presets.dm
> +		/datum/computer_file/program/atmosscan,
alphabetize

2023-08-25 00:56 UTC, san7890 commented on code/modules/modular_computers/computers/item/role_tablet_presets.dm
>  		/datum/computer_file/program/atmosscan,
alphabetize

2023-08-25 00:56 UTC, san7890 commented on code/modules/modular_computers/computers/item/role_tablet_presets.dm
>  		/datum/computer_file/program/atmosscan,
alphabetize

2023-08-25 00:56 UTC, san7890 commented on tools/UpdatePaths/Scripts/77740_delete_atmos_disk.txt
> +/obj/item/computer_disk/atmos : @DELETE
this helps thanks

2023-08-25 15:21 UTC, nukularpower commented
nt frontiers for scientists please

2023-08-25 20:33 UTC, Vincent983 commented
there's a disk in the toxins lab that has NT frontiers on it, just slot it into your PDA

2023-08-28 21:29 UTC, Ghommie approved these changes

2023-08-28 21:29 UTC, merged