Several common 'household' reagents can be used as improvised medicine treatment. Updated first aid analyzer information.
tgstation/tgstation pull request #77746
Opened 2023-08-19 04:01 UTC by carlarctg

## About The Pull Request

Several common 'household' reagents can be used as improvised medicine treatment.

Drinking tea will help mend (non-bone) wounds over time.

Flour and corn starch may be splashed onto wounds to help dry them up, though they'll have a negative effect on burn wounds.

Added a new reagent, saltwater, made by combining table salt with water.

Table salt and saltwater can be splashed onto wounds as well, reducing bleeding and improving sanitization and disinfection significantly. However, the coarse undiluted salt will irritate the wounds, reducing clot rate and flesh healing, and both of the reagents will increase a burn wound's infestation rate.

Altered Table Salt's recipe to just need sodium and chloride. Changed the recipe of Pentetic Acid and Heparin to need table salt (sodium x chloride) and thus slightly altered the total output of those reagents (pentacid went from 5u per reaction to 4u, heparin 4u->3u)

Saline-Glucose Solution now needs 2u of saltwater and 1u of sugar, meaning the overall recipe should be completely unchanged in practice. Contact me on discord if any issues arise from these chemical changes!

First aid analyzers now give easy-to-understand direct information, with the specific recommended treatments bolded in the analysis text. They also have a 'unique' extra bit of info, telling you about improvised ways to remedy your wound.

## Why It's Good For The Game

Wounds have a very poor amount of interaction with the rest of the game and have not had much added to them post-merge, especially in 'improvised' ways to help Not Die to a wound while you crawl your way to a emergency medkit or medbay. I researched info on this and found some interesting ideas - some of them I'll have to leave for later because this PR kept growing out of scope (Improvised bone gel, ice on wounds which turned into wound temperature mechanics, crutches, a 'suture item' component refactor...)

As for what this actually does to benefit the game, it allows more dynamic wound Gameplay as people use first aid analyzers to get information on treatment when medbay blows up, helps them stabilize by splashing flour onto themselves before looking for some actual treatment, helps traitors realize how they can self-treat many crippling wounds (at risk, of course). It expands treatment options to things beside medkits and medbay, but always does so in ways that have downsides that make them not ideal as _treatment_, and more beneficial as stabilizing before seeking true professional help. This thus significantly increases the rather shallow depth of wounds as a system to interact with.

> Several common 'household' reagents can be used as improvised medicine treatment.

From what I could tell by looking at several sources for each 'realistic' treatment, these are indeed semi-reasonable things that are done to wounds by some people as household treatment.

It goes without saying that you should **not do any of these things in real life** without consulting a doctor unless your blood is also spilling out by the gallon into the floor. All these 'realistic treatments' have drastic downsides and are meant for the short-term only. Except the tea.

> Drinking tea will help mend (non-bone) wounds over time.

Tea is healthy, we all know that.

> Flour and corn starch may be splashed onto wounds to help dry them up, though they'll have a negative effect on burn wounds.

Flour and apparently starch dries wounds up but risks infection. That's not a thing for blood wounds yet but oh well.

> Table salt and saltwater can be splashed onto wounds as well, reducing bleeding and improving sanitization and disinfection significantly. However, the coarse undiluted salt will irritate the wounds, reducing clot rate and flesh healing, and both of the reagents will increase a burn wound's infestation rate.

Salt kills bacteria via osmosis, but it also kills your own cells, and some bacteria like salt.

> Added a new reagent, saltwater, made by combining table salt with water.

> Altered Table Salt's recipe to just need sodium and chloride. Changed the recipe of Pentetic Acid and Heparin to need table salt (sodium x chloride) and thus slightly altered the total output of those reagents (pentacid went from 5u per reaction to 4u, heparin 4u->3u)

> Saline-Glucose Solution now needs 2u of saltwater and 1u of sugar, meaning the overall recipe should be completely unchanged in practice. Contact me on discord if any issues arise from these chemical changes!

I wish I hadn't had to mess with reagents like this, but I needed to because just adding mixing salt and water caused the saline glucose recipe to basically split itself into half saltwater half glucose. 

I removed the water requirement for table salt (Why did it even have that, salt ain't wet bro?), made saline-glucose need 2u saltwater and 1u sugar, and altered relevant recipes so they didn't also cause unwanted table salt to react from their sodium and chloride ingredients.

A happy side-effect is that saline glucose solution is even easier to make now as an improvised chem by mixing salt, water, and sugar, which fits pretty perfectly (especially as a temporary blood substitute)

> First aid analyzers now give easy-to-understand direct information, with the specific recommended treatments bolded in the analysis text. They also have a 'unique' extra bit of info, telling you about improvised ways to remedy your wound.

You might notice that as the wounds get more serious the text gets more direct and concise and reluctantly hands out more and more improvised treatment options, so that's fun. As for the improvised section itself, it helps people be actually aware of these ways to help treat themselves rather than delegating it to hyper-gamer knowledge.

The bolded treatment bit is pretty neat and means your eyes can inmediately focus on what you can do to save yourself - very useful if you have a weeping avulsion and no bandages.

## Changelog

:cl:
add: Several common 'household' reagents can be used as improvised medicine treatment.
add: Drinking tea will help mend (non-bone) wounds over time.
add: Flour and corn starch may be splashed onto wounds to help dry them up, though they'll have a negative effect on burn wounds.
add: Added a new reagent, saltwater, made by combining table salt with water.
add: Table salt and saltwater can be splashed onto wounds as well, reducing bleeding and improving sanitization and disinfection significantly. However, the coarse undiluted salt will irritate the wounds, reducing clot rate and flesh healing, and both of the reagents will increase a burn wound's infestation rate.
add: Altered Table Salt's recipe to just need sodium and chloride. Changed the recipe of Pentetic Acid and Heparin to need table salt (sodium x chloride) and thus slightly altered the total output of those reagents (pentacid went from 5u per reaction to 4u, heparin 4u->3u)
add: Saline-Glucose Solution now needs 2u of saltwater and 1u of sugar, meaning the overall recipe should be completely unchanged in practice. Contact me on discord if any issues arise from these chemical changes!
qol: First aid analyzers now give easy-to-understand direct information, with the specific recommended treatments bolded in the analysis text. They also have a 'unique' extra bit of info, telling you about improvised ways to remedy your wound.
/:cl:

2023-08-19 04:38 UTC, Wallemations commented
I'm pretty sure the wounds system was partly implemented to make you go _into_ medbay, but this seems to be trying to take you out of it
I'm not entirely opposed to things like the corn starch thing giving a slight boost, but the tea one is a bit much imo. Tea already cures toxin damage, physical wounds is a bit much for it.

Another question; how do these compare to actual medical remedies? Are these slower, and if so how much?

2023-08-19 04:49 UTC, carlarctg commented
> I'm pretty sure the wounds system was partly implemented to make you go _into_ medbay, but this seems to be trying to take you out of it

My man! Everything here is meant to STABILIZE you. Not to fix your wounds instantly. I know the wounds system is designed so that people don't just self treat everything. This is why blood loss reduction is clamped for salt. This is why salt increases infestation rate by a quite large amount, which is deadly if left to fester.

These things help people Not Die, it doesn't help them fix every issue immediately.

> I'm not entirely opposed to things like the corn starch thing giving a slight boost, but the tea one is a bit much imo. Tea already cures toxin damage, physical wounds is a bit much for it.

It's healthy. The numbers are honestly pretty goofy but I got tired of stat tuning- I should probably go back and make it just slowly increase clot rate and decrease infestation rate.

> Another question; how do these compare to actual medical remedies? Are these slower, and if so how much?

Again pretty much missing the point - none of these treat the wound, they prevent death. Space cleaner is a third as effective as sterilizine, and nothing is more effective than scanning, bandaging, and ointment or suturing.

2023-08-19 04:50 UTC, carlarctg commented on code/datums/wounds/_wounds.dm
> +	/// Simple description, shortened for clarity if defined. Otherwise just takes the normal desc in the analyzer proc.
forgot to implement

2023-08-19 04:58 UTC, carlarctg commented
> You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Not really sure what to do here. Mantainers please give me ideas. Bug hunters pick the low hanging fruit and I'm not sure what might be fun to refactor. Something I have planned is reworking sutures and meshes into a component that can be applied onto any item (Bone gel for skellies!)

2023-08-19 05:03 UTC, Wallemations commented
If you want more gbp just help turn some mobs to basic mobs or something, do some QOL stuff like swapping chat alerts to bubble ones, etc

2023-08-19 05:06 UTC, Wallemations commented
> > I'm pretty sure the wounds system was partly implemented to make you go _into_ medbay, but this seems to be trying to take you out of it
> 
> 
> 
> My man! Everything here is meant to STABILIZE you. Not to fix your wounds instantly. I know the wounds system is designed so that people don't just self treat everything. This is why blood loss reduction is clamped for salt. This is why salt increases infestation rate by a quite large amount, which is deadly if left to fester.
> 
> 
> 
> These things help people Not Die, it doesn't help them fix every issue immediately.
> 
> 
> 
> > I'm not entirely opposed to things like the corn starch thing giving a slight boost, but the tea one is a bit much imo. Tea already cures toxin damage, physical wounds is a bit much for it.
> 
> 
> 
> It's healthy. The numbers are honestly pretty goofy but I got tired of stat tuning- I should probably go back and make it just slowly increase clot rate and decrease infestation rate.
> 
> 
> 
> > Another question; how do these compare to actual medical remedies? Are these slower, and if so how much?
> 
> 
> 
> Again pretty much missing the point - none of these treat the wound, they prevent death. Space cleaner is a third as effective as sterilizine, and nothing is more effective than scanning, bandaging, and ointment or suturing.

I admit I misinterpreted the pr, but again I stand by the tea part not making much sense beyond just "it's healthy". Yes it's healthy, which is why it fixes toxin damage, because that's what tea is said to do IRL. 
I'm not a code maint so I won't comment on any of that other stuff or any balance things, but you get my point about the tea.

2023-08-19 08:05 UTC, githubuser4141 commented
> 

'Stabilize' in /tg/'s medical system is a bit meh because lethal vs non-lethal is based on how much damage numbers you have. If it's 100 or above, you ded. If not, you fine. /Tg/'s medic system is bizarre where things that'd be trivial irl can easily kill you (e.g., scratching at an itch! x10), irl scratching nonstop is harmful but it's not instantly deadly - it COULD technically kill you via long-term causes I guess, and OTOH things that'd be very dangerous IRL can be easily stabilized and treated like gunshot wounds, slashing open someone's arteries, having an entire armoured vehicle falling on your head, etc. In /tg/, you're more likely to die from 'oops I mislicked and touched a hot lightbulb when bandgaging myself at 99 damage' then the actual wounds which caused 99 damage. 

Also source on the tea curing toxin damage irl? If you had a very small dosage of poison you might be able to get away with it by drinking large quantities of tea because it'd be diluted, but this goes for water too. If you're actually dying from poison induced damage then I'm sorry but tea isn't going to help

2023-08-19 08:58 UTC, Likteer commented
![obraz](https://github.com/tgstation/tgstation/assets/68878861/573afd8d-a272-4133-8ebd-e2b34a8f2fbf)

2023-08-19 10:10 UTC, Dorsisdwarf commented
Im not quite sure how saltwater works? it disinfects and reduces infection, but also speeds up infections on the only wound type that can be infected? How do all those interact? 

also saltwater recipe will break porridge and electron soup recipies, those both use water and salt as reagants

2023-08-19 15:46 UTC, BlueMemesauce commented
Just change everything that uses salt and water to use saltwater instead

2023-08-19 18:15 UTC, carlarctg commented
> Im not quite sure how saltwater works? it disinfects and reduces infection, but also speeds up infections on the only wound type that can be infected? How do all those interact?
> 
> also saltwater recipe will break porridge and electron soup recipies, those both use water and salt as reagants

Thanks, I'll change that up 

> Just change everything that uses salt and water to use saltwater instead

Yeah I did that with sodium and chloride

> ![obraz](https://user-images.githubusercontent.com/68878861/261788916-573afd8d-a272-4133-8ebd-e2b34a8f2fbf.png)

uhhhh ok?

> > 
> 
> 'Stabilize' in /tg/'s medical system is a bit meh because lethal vs non-lethal is based on how much damage numbers you have. If it's 100 or above, you ded. If not, you fine. /Tg/'s medic system is bizarre where things that'd be trivial irl can easily kill you (e.g., scratching at an itch! x10), irl scratching nonstop is harmful but it's not instantly deadly - it COULD technically kill you via long-term causes I guess, and OTOH things that'd be very dangerous IRL can be easily stabilized and treated like gunshot wounds, slashing open someone's arteries, having an entire armoured vehicle falling on your head, etc. In /tg/, you're more likely to die from 'oops I mislicked and touched a hot lightbulb when bandgaging myself at 99 damage' then the actual wounds which caused 99 damage. I could stabilize my wounds with epi, salt water, flour, dirt, inhaling cattle medicine and maybe the odd orange juice IV but I'd still die from a random itch, or from a mouse biting your jackbooted toe.

What is this insane rant. I can't fix tg medical system in one small PR (Or at all). The 'stabilizing' in this case is just making sure your burn wounds don't get septic before you reach medbay or making sure you don't lose so much blood before the wound is fixed that you fall unconscious and die before you can get proper treatment and blood replenishment.

> Also source on the tea curing toxin damage irl? If you had a very small dosage of poison you might be able to get away with it by drinking large quantities of tea because it'd be diluted, but this goes for water too. If you're actually dying from poison induced damage then I'm sorry but tea isn't going to help

There is no source. Tea is healthy.

2023-08-19 19:38 UTC, san7890 requested changes

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	description = "Water, but salty. Smells like... Central command shuttle docking?"
```suggestion
	description = "Water, but salty. Smells like... the station infirmary?"
```

i think your current description is way too meta but this one has a nice double meaning

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +
```suggestion
	// When some nerd adds infection for wounds, make this increase the infection
```

no need for the redundant return

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	return
```suggestion
	// When some nerd adds infection for wounds, make this increase the infection
```

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +	return
```suggestion
```

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		iter_wound.on_saltwater(reac_volume, carbies)
```suggestion
	for(var/datum/wound/iterable_wound as anything in carbies.all_wounds)
		iter_wound.on_saltwater(reac_volume, carbies)
```

this is faster and cleaner. if `all_wounds` carries things that aren't types of `/datum/wound` then remove the `as anything`.

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +		iter_wound.on_starch(reac_volume, carbies)
ditto type + `as anything`

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +		var/datum/wound/iter_wound = i
ditto `type` and `as_anything`

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/food_reagents.dm
> +		iter_wound.on_salt(reac_volume, carbies)
ditto type and `as anything`

2023-08-19 19:38 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
> +		var/datum/wound/iter_wound = i
ditto type and `as anything`

2023-08-19 19:38 UTC, san7890 commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +		if(simple_scan == TRUE)
```suggestion
		if(simple_scan)
```

no need to explicitly match a boolean value if we know it's a boolean

2023-08-19 19:38 UTC, san7890 commented on code/datums/wounds/burns.dm
> +	for(var/datum/reagent/reagent in victim.reagents.reagent_list)
would `as anything` work here?

2023-08-19 19:38 UTC, san7890 commented on code/datums/wounds/_wounds.dm
> +	var/homemade_treat_text = "Remember to drink lots of water!"
spell out what `s` might be, so `simple_desc` and `simple_treat_text`. letters are free.

2023-08-20 02:11 UTC, carlarctg commented
@san7890 Aside from the code nitpicks, do you like the idea of the PR?

2023-08-20 17:02 UTC, lordpidey commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +	taste_description = "water"
Should probably mention that it tastes salty.

2023-08-20 17:25 UTC, san7890 commented
> @san7890 Aside from the code nitpicks, do you like the idea of the PR?

i don't see why it's a bad idea given how common medical supplies are on a station already

2023-08-20 22:33 UTC, carlarctg commented on code/datums/wounds/burns.dm
> +	for(var/datum/reagent/reagent in victim.reagents.reagent_list)
i dont see why not

2023-08-21 02:33 UTC, MrMelbert commented on code/__DEFINES/maths.dm
> +#define VALUE_PER(value, per) value / per
```suggestion
#define VALUE_PER(value, per) (value / per)
```
always wrap your macros

2023-08-21 05:27 UTC, carlarctg commented on code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
> -	affected_mob.adjust_bodytemperature(-5 * REM * TEMPERATURE_DAMAGE_COEFFICIENT * seconds_per_tick, affected_mob.get_body_temp_normal())
wtf

2023-08-21 18:27 UTC, epochayur commented
With all of Tea's functionality (it adjusts body temp AND heals tox AND heals wounds), it should really have an OD threshold at this point, seeing as people are already routinely going and drinking 3000u of tea roundstart BEFORE it gets a huge buff.

2023-08-22 11:54 UTC, Dorsisdwarf commented
> With all of Tea's functionality (it adjusts body temp AND heals tox AND heals wounds), it should really have an OD threshold at this point, seeing as people are already routinely going and drinking 3000u of tea roundstart BEFORE it gets a huge buff.

OD makes you english

2023-08-26 23:03 UTC, RikuTheKiller commented
Just realized a massive problem. This fucks up EVERY single chemical recipe buffer that most chemists have saved for the sake of simplifying a few chems. That's not worth it at all. Buffer recipes rely entirely on the pH of the ingredients and that will shift after this change, resulting in all chemists having to painstakingly redo a shit ton of work.

2023-08-27 06:00 UTC, carlarctg commented
> Just realized a problem. This will fuck up buffers for purity stuff due to saltwater.

...How?

2023-08-27 11:41 UTC, RikuTheKiller commented
> ...How?

Saltwater replaces chlorine + water, meaning all recipes that use chlorine + water will have the total pH of their ingredients altered. This means the other reagents you have to add to make the recipe result in a pure product will change and due to weird shit, it may change for other recipes as well. Basically, changing existing chemical recipes is risky.

In other words, chemists will have to redo a bunch of boring stuff they did ages ago, most of us keep around a list of buffers for specific recipes or use an online one, all of which will have to be partially redone after this PR for the sake of condensing a couple recipes.

2023-09-02 19:03 UTC, carlarctg commented
> > ...How?
> 
> Saltwater replaces chlorine + water, meaning all recipes that use chlorine + water will have the total pH of their ingredients altered. This means the other reagents you have to add to make the recipe result in a pure product will change and due to weird shit, it may change for other recipes as well. Basically, changing existing chemical recipes is risky.
> 
> In other words, chemists will have to redo a bunch of boring stuff they did ages ago, most of us keep around a list of buffers for specific recipes or use an online one, all of which will have to be partially redone after this PR for the sake of condensing a couple recipes. Some online ones simply aren't maintained (or aren't maintained that well), so those will stay outdated for ages.
> 
> You could make saltwater require a bit of heat to react since salt needs heat to dissolve in water anyway. That's not hard to acquire through the use of a welder or an igniter and would leave all existing recipes intact. Saline doesn't need heating and is barely exothermic.

I'ma be real with you I just don't care enough about that, sorry. Fermichem is a cancer. You're free to suggest changes to my code or PR further ones but I can't bring myself to care about the fine tuning of purity.

2023-09-03 20:59 UTC, Loafin34 commented
> > 
> 
> 'Stabilize' in /tg/'s medical system is a bit meh because lethal vs non-lethal is based on how much damage numbers you have. If it's 100 or above, you ded. If not, you fine. /Tg/'s medic system is bizarre where things that'd be trivial irl can easily kill you (e.g., scratching at an itch! x10), irl scratching nonstop is harmful but it's not instantly deadly - it COULD technically kill you via long-term causes I guess, and OTOH things that'd be very dangerous IRL can be easily stabilized and treated like gunshot wounds, slashing open someone's arteries, having an entire armoured vehicle falling on your head, etc. In /tg/, you're more likely to die from 'oops I mislicked and touched a hot lightbulb when bandgaging myself at 99 damage' then the actual wounds which caused 99 damage. I could stabilize my wounds with epi, salt water, flour, dirt, inhaling cattle medicine and maybe the odd orange juice IV but I'd still die from a random itch, or from a mouse biting your jackbooted toe.
> 
> Also source on the tea curing toxin damage irl? If you had a very small dosage of poison you might be able to get away with it by drinking large quantities of tea because it'd be diluted, but this goes for water too. If you're actually dying from poison induced damage then I'm sorry but tea isn't going to help

we need a balance PR where rats cannot bite through jackboots

2023-09-05 00:22 UTC, san7890 requested changes

2023-09-05 00:22 UTC, san7890 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +/datum/reagent/medicine/mine_salve/on_burn_wound_processing((datum/wound/burn/flesh/burn_wound))
```suggestion
/datum/reagent/medicine/mine_salve/on_burn_wound_processing(datum/wound/burn/flesh/burn_wound)
```

linters are failing

2023-09-11 20:44 UTC, merged

2023-09-11 21:28 UTC, nikothedude commented
FUCK

MY WOUNDS