Replaces the decloning virus clone damage with a strike system
tgstation/tgstation pull request #77824
Opened 2023-08-21 11:14 UTC by distributivgesetz

## About The Pull Request

Simply replaces the decloning virus's dependency on clone loss with a strike system. The strike system goes down in the same fashion as clone damage does and is replenished with mutadone. The only thing that's taken away is the ability to how far a person is into their strikes, which probably has to be added in some way like a status effect.

## Why It's Good For The Game

Explanation from #77569:

> Clone damage is a damage type that shouldn't exist anymore, it's a relic left from the era of cloning and it's so specific of a damage type that it rarely gets used as a result. It really should be a type of affliction (wound etc) instead of its own damage counter.

What's changed since then is that I don't think clone damage should not exist at all anymore. It only affects one department and a few odd situations anyways.

This PR should actually change very little about decloning, as it works with the same numbers as it did before, and since cloneloss healing is just as easy to come by as taking mutadone is.

## Changelog

:cl:
add: Replaces decloning clone damage with a strike system that you can replenish with Mutadone.
/:cl:

2023-08-21 11:35 UTC, distributivgesetz commented
refactoring the decloning dust part into a status effect as that gives me better user feedback

2023-08-21 13:18 UTC, Time-Green commented
Honestly feel free to take whatever creative liberty you want, I’m pretty sure I added this as a genetic meltdown effect and nothing else

2023-08-21 13:31 UTC, distributivgesetz commented
Genetic meltdown seems to be the precondition to decloning, this here would be a second status effect that focuses on complimenting the virus with alerts and examine text for better user feedback

2023-08-22 16:30 UTC, san7890 requested changes

2023-08-22 16:30 UTC, san7890 commented on code/datums/dna.dm
> +				ForceContractDisease(new/datum/disease/decloning()) //slow acting, non-viral GBS
```suggestion
				ForceContractDisease(new /datum/disease/decloning) //slow acting, non-viral GBS
```

may as well clean it up

2023-08-22 16:30 UTC, san7890 commented on code/datums/status_effects/debuffs/decloning.dm
> +		)))
```suggestion
		to_chat(owner, span_danger(pick(
			"Your body is giving in.",
			"You feel some muscles twitching.",
			"Your skin feels sandy.",
			"You feel your limbs shifting around.",
		)))
```

don't need these in modern byond

2023-08-22 16:30 UTC, san7890 commented on code/datums/status_effects/debuffs/decloning.dm
> +			return span_warning("<b>[owner.p_Their()] body looks severely deformed!</b>")
```suggestion
			return span_boldwarning("[owner.p_Their()] body looks severely deformed!")
```

2023-08-22 16:30 UTC, san7890 commented on code/datums/status_effects/debuffs/decloning.dm
> +		You are going to need treatment soon."
```suggestion
	desc = "Your body is deforming, and doesn't feel like it's going to hold up much longer. You are going to need treatment soon."
```

doesn't feel worthy of multilining

2023-08-23 16:50 UTC, san7890 commented on code/datums/diseases/decloning.dm
> +				affected_mob.apply_status_effect(/datum/status_effect/decloning)
the status effect won't stack up multiple times on the same person if these fire, right?

2023-08-25 00:53 UTC, merged