Makes railings easier to construct, while making them easier to destroy.
tgstation/tgstation pull request #77894
Opened 2023-08-23 20:29 UTC by iwishforducks

## About The Pull Request

Changes the cost of railings from 6 metal rods to 2 metal rods.
The time to construct has been reduced from 3.6 to 1 second to be in-line with the grille.
The health of railings has been reduced from 75 to 25.
Armor of railings have been reduced as well by about 30%.

I'm not positive on whether or not it should cost 1 metal rod or 2. I decided to play it safe and make it 2. If some maintainer is interested in making it only cost 1 rod then I will gladly do so- but this was my compromise.

Also changes decaseconds/ticks to seconds in the rod construction code to make it look better.

## Why It's Good For The Game

Railings look nice and it's an absolute pain in the ass that they cost 6 metal rods.

They're also currently substantially stronger than grilles for whatever reason. Grilles have 50 health, while railings have 75.
The armor of railings makes this health of 75 to a whopping effective health of 150.

Railings shouldn't be stronger than full-tile grilles. They should be fairly flimsy.
They also shouldn't take a wrench AND wirecutters to deconstruct. Grilles only take wirecutters and we should mirror that.

## Changelog

:cl:
balance: Railings now only cost 2 rods and are much easier to construct. But they can now be destroyed much easier and cut with wirecutters without unwrenching.
/:cl:

2023-08-23 21:03 UTC, nianjiilical commented
its probably out of scope of this pr but it'd be nice if we could get more expensive reinforced railings, since its nice to use them to cordon off dangerous things

2023-08-24 02:12 UTC, Elli-Skala commented
For context they were originally 3 rods but upped to 6 after they got spammed rapidly for the thether + anti grav module  combo which lead to blocked walls

Being able to remove them in one click with wire cutters is a much better solution 👍

2023-08-24 07:56 UTC, ophaq commented
This is a good change. Now if only we could construct rail endings too lol.

2023-08-24 08:11 UTC, iwishforducks commented
> This is a good change. Now if only we could construct rail endings too lol.

i forgot about this as well i'll fix this too

2023-08-24 09:19 UTC, ZephyrTFA commented
change is ok, your gbp makes me sad though

2023-08-24 09:40 UTC, iwishforducks commented
> change is ok, your gbp makes me sad though

i have 2 other fix prs up rn if that turns your frown upside down

2023-08-25 15:13 UTC, ArcaneMusic requested changes
Do this and I'll merge by end of today

2023-08-25 15:13 UTC, ArcaneMusic commented on code/game/objects/structures/railings.dm
Mind adding some screentips to railings while you're here?

2023-08-26 00:35 UTC, ArcaneMusic approved these changes

2023-08-26 00:35 UTC, merged