Nonhuman Nukies 2023:
tgstation/tgstation pull request #77970
Opened 2023-08-27 15:51 UTC by Rhials

## About The Pull Request

![image](https://github.com/tgstation/tgstation/assets/28870487/cbfbf18a-b4cb-44d1-97ef-430fc4404128)

When #16075 was created in the ancient year of 2016, it was a stopgap solution to plasmamen spawning in with a regular nukie outfits and burning to death. As a result, nukies have been human-only for the past seven years. I come to you today to remove the stopgap, and once again enable non-human nukies.

This was approved in the past (#59590), and I'm assuming that approval is still valid. Let's take a look at how things work:

Spawning in as a Nuclear Operative (leader included), Lone Operative, Clown Operative, or Reinforcement will now set your species to the one if your prefs. That means lizard, cat, plasma, and ethereal nukies are all on the table now.

Plasmamen now have their own syndicate envirohelm/suit combo. It doesn't look fantastic (it's just a palette swapped roboticists envirosuit) but I think it's serviceable at least. When the operative antag datum is given, and the owner is a plasmamen, they will instead be given an alternate outfit with these equipped. Loneop plasmamen will instead be given a MODsuit with the plasma stabilizer MODule installed.

**But what about the AI?** Fortunately for the balancebrains in the crowd, there is a preference (enabled by default!) to always roll human as an operative. The AI still has to reasonably assume that nukies are human until proven otherwise so please don't think this will affect the rules of engagement for anyone not _directly opting into it._

![image](https://github.com/tgstation/tgstation/assets/28870487/f4ba8e6d-bfb8-40cb-abcb-95e8ea224a95)

(This pref will only appear if you have a nukie job enabled in the antag menu!)

Huge thanks to Melbert who let me peek at his code on a branch trying to do the same thing. My approach ended up being entirely on the antag datum, with nothing on the job datum.

## Why It's Good For The Game

Rectifies a curious change made long long ago. Expands customization to nukies while not affecting balance for those who care.

## Changelog

:cl:
add: Nuclear operatives have expanded the scope of their hiring practices. Members of all species can now roll nukie!
qol: The preferences menu now has an option to always be human when being selected for a nuclear operative role. Check it out!
image: Plasmaman operative envirosuits.
/:cl:

2023-08-27 15:55 UTC, Jackal-boop commented
this is good

2023-08-27 16:30 UTC, mc-oofert commented
if my leader was a nonhuman i would probably call it a guaranteed flukeop

2023-08-27 19:16 UTC, Livrah commented
Like flukie teammates wasn't bad enough already, some races take extra dmg.

2023-08-27 20:19 UTC, Ticklezcat commented
> Like flukie teammates wasn't bad enough already, some races take extra dmg.

Securities weakest lasers vs. The Syndicate's strongest moff.

2023-08-27 21:55 UTC, DaydreamIQ commented
As a human-only player, this is pretty funny. Plasmeme ops might be weaker but it makes their win all the stronger.

2023-08-27 22:55 UTC, MrMelbert requested changes

2023-08-27 22:55 UTC, MrMelbert commented on code/modules/antagonists/nukeop/nukeop.dm
> +		operative.equipOutfit(plasmaman_outfit)
This should not be a hardcoded thing, it should defer to the species, IE via `pre_equip_species_outfit`. 
If we (or downstreams) wish to add a new species which requires its own unique outfits, we shouldn't have to come back to this to add `isplasmaman, elsif snowflakeman, elseif fishman, else...`

(this is the reason why I used jobs datums, it worked with that proc nicely)

2023-08-27 22:58 UTC, MrMelbert commented on code/modules/antagonists/_common/antag_spawner.dm
> +		nukie.set_species(species_type)
This feels backwards or unnecessary. 
`safe_transfer_prefs_to` should already set them to their pref species.

2023-08-28 14:23 UTC, bruhlookatthisdood commented
i feel like you should be able to choose what species you play as

2023-08-28 16:13 UTC, moocowswag commented
non human nukies do have advantages though, lizard gets tackle resistance so its slightly safer to go desword / shielded modsuit.

plasmameme can try to do a singuloose/tesloose sm delam and try to avoid direct combat all together and just make the station a bad time for the crew.

Plasmameme`s downside is also irrelevant if played safely with shielded modsuit...atleast until bombs come into play.

Ethereal....cant revive crystal because nukies gib themselves on death :(

Don`t moffs see better in the dark?

2023-08-28 17:16 UTC, Rex9001 commented
> non human nukies do have advantages though, lizard gets tackle resistance so its slightly safer to go desword / shielded modsuit.
> 
> 
> 
> plasmameme can try to do a singuloose/tesloose sm delam and try to avoid direct combat all together and just make the station a bad time for the crew.
> 
> 
> 
> Plasmameme`s downside is also irrelevant if played safely with shielded modsuit...atleast until bombs come into play.
> 
> 
> 
> Ethereal....cant revive crystal because nukies gib themselves on death :(
> 
> 
> 
> Don`t moffs see better in the dark?
> 
> 
> 
> And felinids can catch the lasers for the other nukies like a cat trying to chase a laser pointer that kills them.

You can disable the microbomb implant with the atropine injector in your box

2023-08-28 21:26 UTC, Googles-Hands commented
Mirror NT's Head of Staff and restrict nuke ops leaders to human only. :)

2023-08-28 23:10 UTC, san7890 commented
ready for review when dehardcoding is done

2023-08-29 01:50 UTC, necromanceranne commented
Woo, plasmaman ops!

Besure to have plasmaman ops spawn with plasma stabilizers to put into their modsuits.

2023-08-29 08:54 UTC, SimplySmiley123 commented
> non human nukies do have advantages though, lizard gets tackle resistance so its slightly safer to go desword / shielded modsuit.
> 
> plasmameme can try to do a singuloose/tesloose sm delam and try to avoid direct combat all together and just make the station a bad time for the crew.
> 
> Plasmameme`s downside is also irrelevant if played safely with shielded modsuit...atleast until bombs come into play.
> 
> Ethereal....cant revive crystal because nukies gib themselves on death :(
> 
> Don`t moffs see better in the dark?
> 
> And felinids can catch the lasers for the other nukies like a cat trying to chase a laser pointer that kills them.

Honestly adds some variety with some downsides to boot.
Like ethereals and plasmamen taking more direct damage and all of the non-humans not being protected from Shitsimov.

2023-08-30 17:41 UTC, Fritzlschnitzel commented
The syndicate has fallen.

2023-08-30 19:47 UTC, ExcessiveUseOfCobblestone commented
> Some players play hardcore random as antagonists already, doubt taking a lizard specie is gonna do any worse then having a paraplegic and blind leader with a brain tumor and blood deficiency.

intentionally sandbagging your team seems like something that should be curbed or at least agreed upon by the people who have to deal with it. could care less for solo antags but not a fan of people taking purposefully debilitating traits on the team mode.

2023-08-30 20:57 UTC, Rhials commented
I've pushed a solution that doesn't require any funky if checks on the outfit distribution side.

The current solution comes in two parts, the outfit_override_registry list and the equip_species_outfit proc.

The outfit_override_registry is a list, wherein the key is a default outfit path, and the value is the outfit you'd like to replace it with when equipping a species holder with the key outfit.

For instance, in the plasmaman registry the key/value pair is `/datum/outfit/syndicate/reinforcement = /datum/outfit/syndicate/reinforcement/plasmaman`, so when the reinforcement outfit is equipped via `equip_species_outfit()` proc, it will equip the `/datum/outfit/syndicate/reinforcement/plasmaman` outfit instead of the default.

This solution should be scalable to other species, and other use cases, without any issue.

Testing hasn't shown any differences in functionality -- this worked WAY better than I expected it to.

2023-08-30 22:12 UTC, san7890 requested changes

2023-08-30 22:12 UTC, san7890 commented on code/modules/mob/living/carbon/human/inventory.dm
> +	if(!outfit_to_equip)
`isnull()` here

2023-08-30 22:12 UTC, san7890 commented on code/modules/mob/living/carbon/human/species_types/plasmamen.dm
> +		/datum/outfit/syndicate/full = /datum/outfit/syndicate/full/plasmaman,
alphabetize for better extensibility?

2023-08-31 16:29 UTC, san7890 commented on code/modules/antagonists/nukeop/nukeop.dm
> +	if(!operative.client || operative.client.prefs.read_preference(/datum/preference/toggle/nuke_ops_species))
```suggestion
	if(isnull(operative.client) || operative.client.prefs.read_preference(/datum/preference/toggle/nuke_ops_species))
```

didn't see this my bad

2023-08-31 17:01 UTC, merged

2023-08-31 20:29 UTC, Livrah commented
Can non human species get a macro bomb implant instead of regular one?