Adds a sound effect for hypospray/medipen injections
tgstation/tgstation pull request #77979
Opened 2023-08-28 03:02 UTC by carlarctg

## About The Pull Request

Adds a sound effect for hypospray/medipen injections. Doesn't affect sleepy pens or HMS injectors

## Why It's Good For The Game

> Adds a sound effect for hypospray/medipen injections. Doesn't affect sleepy pens or HMS injectors

Satisfactory, visceral feedback of injection. Sounds nice. Makes stealth injections less noticeable, I guess, not that there's any good candidates for that with medipens.

## Changelog

:cl:
sound: Adds a sound effect for hypospray/medipen injections. Doesn't affect sleepy pens or HMS injectors
/:cl:

2023-08-28 03:06 UTC, MrMelbert commented on code/modules/reagents/reagent_containers/hypospray.dm
> +			playsound(get_turf(affected_mob), 'sound/items/hypospray.ogg', 50, TRUE)
```suggestion
			playsound(affected_mob, 'sound/items/hypospray.ogg', 50, TRUE)
```
it don't matter

2023-08-28 07:19 UTC, Helg2 commented
Can you give a sound example?

2023-08-28 17:16 UTC, Helg2 commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	var/stealthy = FALSE
Just add the var to hypospray not medipen.

2023-08-29 22:59 UTC, moocowswag commented
its lowkey a balance change but a welcome one.

2023-08-30 07:00 UTC, MrMelbert commented
Do you have credit for the source of this sound effect? I know I've heard it on other servers before

2023-08-30 15:17 UTC, DrDiasyl commented
> Do you have credit for the source of this sound effect? I know I've heard it on other servers before

This sound is used at Colonial Marines.

2023-08-31 18:55 UTC, ExcessiveUseOfCobblestone requested changes
Source of sound needs to be present in PR description for traceability and to verify any licensing issues, otherwise good to go

2023-08-31 20:32 UTC, carlarctg commented
> > Do you have credit for the source of this sound effect? I know I've heard it on other servers before
> 
> This sound is used at Colonial Marines.

Somehow I forgot to say that, but yeah, that's where it's from, same with the health analyzer noise I PRed a bit ago.

2023-08-31 20:33 UTC, carlarctg commented
@ExcessiveUseOfCobblestone

2023-09-03 14:08 UTC, Ghommie commented
Umh, the sound is used on several other servers and I don't see it in any attributions text file so I can only suppose this is yet another of those ok to use sounds. 🤷

2023-09-03 14:08 UTC, merged