Changes stop drop and roll into a knockdown
tgstation/tgstation pull request #78017
Opened 2023-08-30 04:45 UTC by Bm0n

## About The Pull Request

Changes stop drop and roll from a 6 paralyze stun to a 6 second knockdown unspammable knockdown.

This idea comes from Paradise and is basically identical in implementation.
https://github.com/ParadiseSS13/Paradise/pull/21500
## Why It's Good For The Game

I don't like the fact that this still hardstuns, I think we should make this a knockdown instead since stuns kind of suck in this day and age of TG.

Besides that it's stop drop and _roll_, right? You should still be able to roll around.
## Changelog

:cl:
balance: Changed stop drop and roll from stun to knockdown.
/:cl:

2023-08-30 07:02 UTC, MrMelbert commented
Sound idea but I'd be a little worried about people stop/drop/rolling and just resuming combat, IE immediately drawing your disabler and opening fire

2023-08-30 07:21 UTC, Bm0n commented
> Sound idea but I'd be a little worried about people stop/drop/rolling and just resuming combat, IE immediately drawing your disabler and opening fire

I think it's fine, you'd be on the floor so very slow plus the knockdown itself drops whatever it is you are currently holding. It's already easy enough to get away from someone in a knockdown, especially one that lasts 6 seconds.

Also don't think anyone stop drops and rolls on purpose mid-combat. Almost any time that does happen it's by accident and I think getting yourself into a knockdown is a fairer punishment over a hardstun. Most people in combat rather run for an extinguisher than drop and roll.

2023-08-30 14:27 UTC, Pickle-Coding commented
Being on fire is already very weak when people can instantly extinguish themselves, or just tank it due to dumb armour values. It would be absolutely meaningless if you can stop drop and roll while doing combat.

2023-08-30 17:46 UTC, Bm0n commented
> You haven't provided a justification here other than "stuns are bad". The difference between a stun and a knockdown is that you cannot move or take actions. Moving and taking actions are both things it doesn't, to me, make sense for you to be doing while taking _this_ action.
> 
> You said that you don't think people _would_ take actions while doing it, but in that case what is the benefit in changing it to explicitly allow them to do so?

Well, my opinion is that you should be able to roll around and take action on the floor while stop dropping and rolling, being fully incapacitated for 6 seconds is just not fun gameplay.  I don't see any reason why you wouldn't be able to, I think it's only set to a full stun because dropping and rolling is ancient and predates knockdowns.

So in combat, no one would willingly want to do this unless they're maybe in a big group of people, but even then that's leaving yourself vulnerable to an acceptable level when I think it is fair. I don't think there's really much of a balance concern for this PR, there are fire extinguishers that are better in almost every way all over the place, on the walls, in lockers, etc. I think a buff to dropping and rolling is acceptable.

If you still feel strongly about this not being the case I could decrease the amount of firestack dropping and rolling removes, but I do not think it should be changed back into a stun.

2023-08-30 18:45 UTC, Iamgoofball commented
@Pickle-Coding being on fire is NOT "very weak" it immediately starts destroying every worn item you've got that isn't explicitly fireproof

2023-08-31 19:32 UTC, ExcessiveUseOfCobblestone commented
This means someone can move you and you will, despite rolling on the screen, not lose any fire stacks.

Im just not a fan of the PR tbh, I dont think there is anything wrong with the hardstun. The change allows you to react uncharacteristically while youre rolling (IE pulling out a gun and shooting someone while trying to stop drop and roll) where now it requires you to think before choosing to get the fire off you (because you will not be able to react).

2023-08-31 19:36 UTC, ExcessiveUseOfCobblestone requested changes
^

2023-08-31 20:34 UTC, Bm0n commented
> ^

What changes are you requesting other than you not agreeing with this PR? Do you want me to find a way to cancel out the spin animation if the do_after is interrupted?

2023-08-31 23:17 UTC, Ghommie reviewed
Personally, I'd rather see a way that adds the `TRAIT_HANDS_BLOCKED` trait to the user for the duration of the knockdown... It'd be more reliable than a `do_after` check, except we can't just use something like `addtimer(TRAIT_CALLBACK_REMOVE(src, TRAIT_HANDS_BLOCKED, TRAIT_SOURCE_NAME_HERE), 6 SECONDS)` to remove the trait, because the knockdown may end earlier (from stimulants, shaking someone up etc.), so that's a bit of a pickle.

2023-09-01 16:03 UTC, ExcessiveUseOfCobblestone commented
> > ^
> 
> What changes are you requesting other than you not agreeing with this PR? Do you want me to find a way to cancel out the spin animation if the do_after is interrupted?

nothing i just wanted other maints to not merge this without talking to me first but im likely going to close unless I see someone say I really want this from the maint team.

I am ok with, as part of the animation, your character moving to simulate actually rolling as opposed to stationary spinning. I am not sold on why players need to have control during the time they are performing this action.

2023-09-02 08:35 UTC, Bm0n commented
> > > ^
> > 
> > 
> > What changes are you requesting other than you not agreeing with this PR? Do you want me to find a way to cancel out the spin animation if the do_after is interrupted?
> 
> nothing i just wanted other maints to not merge this without talking to me first but im likely going to close unless I see someone say I really want this from the maint team.
> 
> I am ok with, as part of the animation, your character moving to simulate actually rolling as opposed to stationary spinning. I am not sold on why players need to have control during the time they are performing this action.

Alright, I'll hold off on any changes until you and your team decide. 

I think Ghommie has the right idea with the block hands trait.

2023-09-07 15:06 UTC, Jacquerel commented
there was some talk about this on discord and then nobody actually said anything on the pr, fucked up
i think me and melbert both agreed "it's good to be able to cancel it when it turns out it's actually making your situation worse, it would be great if you only had to press the button once and it will subtract x firestacks per animated roll until extinguished or cancelled rather than the existing multiple clicks"
@ExcessiveUseOfCobblestone I am not sure if you ever actually expressed an opinion past that point is that a acceptable concept to you

2023-09-10 22:12 UTC, Bm0n commented
> there was some talk about this on discord and then nobody actually said anything on the pr, fucked up i think me and melbert both agreed "it's good to be able to cancel it when it turns out it's actually making your situation worse, it would be great if you only had to press the button once and it will subtract x firestacks per animated roll until extinguished or cancelled rather than the existing multiple clicks" @ExcessiveUseOfCobblestone I am not sure if you ever actually expressed an opinion past that point is that a acceptable concept to you

that sounds like a better idea than what I had, so long as coby isn't merge blocking it I'd like to try to do it

2023-10-09 05:36 UTC, san7890 commented
It has been a month and this PR has remained at the bottom of the tracker with zero activity and CI failing. Please feel free to make a new PR with your desired changes should you want to come back to this at a later date.

2023-10-09 05:36 UTC, closed without merging