Medical/roller beds
tgstation/tgstation pull request #78078
Opened 2023-09-01 23:11 UTC by lessthnthree

## About The Pull Request

'medical beds' in the game were just varedited survival pod beds. This creates a proper medical bed subtype plus its own sprite for regular and roller beds. Cleans up little bits of the bed code and adds context helpers.

- Medical/roller bed is now constructable with titanium and plastic after research
- Patients will face the correct direction when buckled and pulled on roller beds
- Movable beds can have 'brakes' toggled with alt-click

![medical_bed_1](https://github.com/tgstation/tgstation/assets/83487515/dd197e24-cf72-4240-ac5a-8cdf575eca00)

![para_bed_1](https://github.com/tgstation/tgstation/assets/83487515/8ad5103e-57be-4dca-8a32-33bdabbeb82e)

## Why It's Good For The Game

Medical gets their own bed, new sprites, cleans up varedits on maps.

## Changelog

:cl: LT3
image: New medical bed and emergency roller bed
code: Added context hints for medical beds
/:cl:

2023-09-02 00:17 UTC, EricZilla commented
These are adorable

2023-09-02 09:18 UTC, OrionTheFox commented
Tangentially related and very humble request:
Would it be possible and/or in-scope to make bodybags buckleable to the rollerbeds? I remember another codebase had it and ever since I've kept trying and trying to buckle the bag onto the rollerbed here to no avail...

2023-09-02 10:34 UTC, lessthnthree commented
> I love the new sprites, very fitting! And god bless for adding locks... do those change the icon state at all?
> 
> Tangentially related and very humble request: Would it be possible and/or in-scope to make bodybags buckleable to the rollerbeds? I remember another codebase had it and ever since I've kept trying and trying to buckle the bag onto the rollerbed here to no avail...

I was going to revisit these later and add buckling IVs to the bed, so could look at this as well. We don't really have any good code for attaching nonmobs to objects.

2023-09-02 13:50 UTC, FlufflesTheDog commented
I can't help but feel like the price (two titanium and three plastic for the emergency bed) is a little bit steep for what you're getting

Very much looking forward to using these in-game, though.

2023-09-02 16:39 UTC, lessthnthree commented
> I can't help but feel like the price (two titanium and three plastic for the emergency bed) is a little bit steep for what you're getting
> 
> Very much looking forward to using these in-game, though.

That's fair, I mainly wanted it to not cost iron given it's mobile and foldable. I'll reduce the cost.

2023-09-02 22:20 UTC, Wallemations approved these changes
good sprites

2023-09-03 08:09 UTC, Time-Green requested changes
Good change! Some small nitpicks. I don't see the point in the `occipied` var though, it seems to be made completely redundant by the pre-existing `buckled` var

2023-09-03 08:09 UTC, Time-Green commented on code/game/objects/structures/beds_chairs/bed.dm
> +	return CONTEXTUAL_SCREENTIP_SET
```suggestion
/obj/structure/bed/medical/add_context(atom/source, list/context, obj/item/held_item, mob/living/user)
	. = ..()

	context[SCREENTIP_CONTEXT_ALT_LMB] = "[anchored ? "Release brakes" : "Apply brakes"]"
	if(!isnull(foldable_type) && !buckled)
		context[SCREENTIP_CONTEXT_RMB] = "Fold up"

	return CONTEXTUAL_SCREENTIP_SET
```

This seems to be mostly copypasta from the parent proc. I prefer you call the parent with `..()` so the parent code can just be reused

2023-09-03 08:09 UTC, Time-Green commented on code/game/objects/structures/beds_chairs/bed.dm
> +	icon_state = "[base_icon_state]_up"
If you want to change the icon_state (and in this case the pixel_y), do it in update_icon_state() and check for `buckled`
(this is already called when you call update_appearance)

2023-09-03 08:09 UTC, Time-Green commented on code/game/objects/structures/beds_chairs/bed.dm
> +	update_appearance()
Ditto, use update_icon_state and check for `buckled` in there

2023-09-03 08:09 UTC, Time-Green commented on code/game/objects/structures/beds_chairs/bed.dm
```suggestion
```

2023-09-03 08:11 UTC, Time-Green commented on code/game/objects/structures/beds_chairs/bed.dm
> +	build_stack_amount = 1
People who know mats, how likely is this to become an infinite material exploit? These can be printed as well for 1,5 materials, but I'm not entirely sure how the conversions works at tier 4

2023-09-03 17:52 UTC, lessthnthree commented on code/game/objects/structures/beds_chairs/bed.dm
> +	var/occupied = FALSE
Oh, I didn't notice a bucked var. Yeah that'd make this redundant.

2023-09-03 19:44 UTC, lessthnthree commented on code/game/objects/structures/beds_chairs/bed.dm
> +	build_stack_amount = 1
Thanks, I forgot to check that. I raised the material costs so that even at tier 4 you can't exploit it.

2023-09-04 18:53 UTC, merged

2023-09-06 01:36 UTC, LSommers commented
A few things:
If you're going for realism, a gurney/stretcher (which is what these are) wouldn't have a pillow, as it's padded itself and meant more for getting people around than long-term laying.

The folded state is literally the old sprite with a single area recolored, which is... less than ideal considering how radically the unfolded sprite was changed.

The unfolded sprite has an unfortunate tendency to blend in with tiles, but other than that and the pillow is pretty solid.

Making it craftable and fixing the direction issues is something that should have been done a while ago, and giving it a brake is a nice touch.

2023-09-06 16:13 UTC, lessthnthree commented
> A few things: If you're going for realism, a gurney/stretcher (which is what these are) wouldn't have a pillow, as it's padded itself and meant more for getting people around than long-term laying.
> 
> The folded state is literally the old sprite with a single area recolored, which is... less than ideal considering how radically the unfolded sprite was changed.
> 
> The unfolded sprite has an unfortunate tendency to blend in with tiles, but other than that and the pillow is pretty solid. Also, might want to make the padding blend a little less with the frame- round it out a bit at the corners similar to the old sprite, maybe?
> 
> Making it craftable and fixing the direction issues is something that should have been done a while ago, and giving it a brake is a nice touch.

I'll keep this in mind for a second pass.

2023-09-07 13:43 UTC, Quink-Fix commented
As suggested before, allowing an IV to be attached to these would be amazing.

2023-09-07 17:29 UTC, lessthnthree commented
> As suggested before, allowing an IV to be attached to these would be amazing.

As mentioned above, it's something I'll add. Probably once I'm done my tram refactor.