buffs embed pulling with hemostats, allows wirecutters to pull embeds too
tgstation/tgstation pull request #78256
Opened 2023-09-11 06:57 UTC by Hatterhat

## About The Pull Request
I should probably make pulling something with wirecutters cause some, but comparatively less, damage than hand pulling, but I'll address that in the morning because I want to get this up now and address the fallout later.

Anyways -
- Wirecutters or tools with wirecutter behaviors are now valid for plucking embeds.
- Pluck speed no longer **starts** at 2.5 seconds, which is a pretty dang long time, especially if you have bad embed RNG. I'll do the math and run some more tests in the morning.
- Wirecutters have a speed malus in regards to plucking shrapnel. I should probably make it worse to account for, like, jaws of life or something.

## Why It's Good For The Game
Embeds kinda suck to deal with. This is intentional - I get that.

However, hemostat pulling is kind of... kind of bad. Awful, really. 2.5 seconds is a lot of time. I know it's not supposed to be the best option, but if you've got a tool, I'd at least like to think it'd be slightly less bad than shoving your fingers into your wound?

## Changelog

:cl:
balance: Pulling embedded items e.g. shrapnel with hemostats is now a lot faster, and scales appropriately with toolspeed.
balance: You can now pull embedded items with wirecutters, at a speed penalty.
/:cl:

2023-09-14 20:05 UTC, carlarctg commented
Making pull out slow is dumb, no matter how ghetto. At a certain level there's just no point to wasting your time with it when you can use those seconds to actually seek medical attention. It should have drawbacks and downsides that are not related to a low effort 10 second delay that makes it irrelevant.

2023-09-14 20:19 UTC, norsvenska commented
why is it faster to remove embedded objects with alien wirecutters compared to alien hemostat? shouldn't it be the other way around?

2023-09-15 02:20 UTC, Ghommie requested changes

2023-09-15 02:20 UTC, Ghommie commented on code/datums/components/embedded.dm
> +	to_chat(user, span_notice("You [tweezer_safe ? "safely" : "unsafely, but"] successfully pluck [weapon] from [victim]'s [limb.plaintext_zone]."))
```suggestion
	to_chat(user, span_notice("You [tweezer_safe ? "" : "unsafely, but"] successfully pluck [weapon] from [victim]'s [limb.plaintext_zone]."))
```
I don't think the `safely` adverb is needed, plus you've forgot to add a conjuction between it and `successfully` anyway.

2023-09-15 02:20 UTC, Ghommie commented on code/datums/components/embedded.dm
> +	to_chat(victim, span_notice("[user] [tweezer_safe ? "safely" : span_warning("painfully")] plucks [weapon] from your [limb.plaintext_zone]."))
```suggestion
	to_chat(victim, span_notice("[user] [tweezer_safe ? "" : span_warning("painfully")] plucks [weapon] from your [limb.plaintext_zone]."))
```

2023-09-15 03:57 UTC, Hatterhat commented
> why is it faster to remove embedded objects with alien wirecutters compared to alien hemostat? shouldn't it be the other way around?

funny thing is this only happens because wirecutters have toolspeed 0.1 while the hemostats have toolspeed 0.25, so the math is just always in the wirecutters' favor

2023-09-15 04:31 UTC, merged