Intercom Resprite
tgstation/tgstation pull request #78366
Opened 2023-09-15 17:27 UTC by DrDiasyl

## About The Pull Request

Changes the sprites of the Station Intercom, Command Intercom, and Prison Intercom to the next ones:
![new intercom](https://github.com/tgstation/tgstation/assets/42353186/0fc0a0e7-911c-47cb-8ba9-7663b07891da)
![new command intercom](https://github.com/tgstation/tgstation/assets/42353186/8537a81a-db41-4ffb-ab82-2e5661d5c229)
![prison intercom](https://github.com/tgstation/tgstation/assets/42353186/73d899ba-69da-412c-81d6-ca2642291ceb)

Now Station Intercom and Command Intercom descriptions are changed to tell more about their real functionality.
Command Intercom now has High-Volume settings like heads headsets.

There is now a memo with frequencies of every channel on the station, the memo is placed near the Command Intercom and in the Telecommunications Room.

## Why It's Good For The Game

Intercoms are part of the "old wall-mount" sprites that were never touched, besides the brief addition of overlays.
Replacing them to design more familiar of other wall-mounts will make it less ancient.

Making the Command Intercom and Prison Intercom look unique ensures players (especially new ones) can distinguish them by just glancing without needing to examine them.
The Command Intercom having a High-Volume setting makes it even more unique as an item that is only met in one room at the station, also makes any Command orders given through an intercom (during Telecomunnications outages) more noticeable.

The description change gives more useful information about Station Intercom and Command Intercom. Now players (especially new ones) can understand that Station Intercoms are usable during telecommunications outages, and Command Intercoms can be set to any frequency.

The memo will help players (especially new ones) understand what numbers they should input to access certain channels using Command Intercom, as right now, the only way to find out the frequencies is through wiki or directly checking servers.

## Changelog

:cl:
qol: The Command intercom now has a High-Volume setting like command headsets
qol: A memo telling frequencies of station radio channels are now present near the Command intercom and T-Comms room
image: Station, Command, and Prison intercoms have received new sprites
spellcheck: Station and Command intercom descriptions have been changed to tell about their functionality
/:cl:

2023-09-15 17:27 UTC, mc-oofert commented
i dont think this is any better than the prior sprites

2023-09-15 17:31 UTC, Serxule commented
this is a downgrade honestly, its slightly better in quality but much less clear in what it is and what it does, its also very bland and would be very hard to notice compared to current ones

2023-09-15 17:33 UTC, DrDiasyl commented
> this is a downgrade honestly, its slightly better in quality but much less clear in what it is and what it does, its also very bland and would be very hard to notice compared to current ones

The old intercom sprite had much more colour shifting in pixels, as such it was more of a pixel blob than this one.
I can't agree that it became less clear, but I can see how some people might notice them on the walls. But I guess the red buttons and the blue screen must give it away.

2023-09-15 17:33 UTC, DrDiasyl commented
> > this is a downgrade honestly, its slightly better in quality but much less clear in what it is and what it does, its also very bland and would be very hard to notice compared to current ones
> 
> The old intercom sprite had much more colour shifting in pixels, as such it was more of a pixel blob than this one. I can't agree that it became less clear, but I can see how some people might not notice them on the walls. But I guess the red buttons and the blue screen must give it away.

2023-09-15 17:34 UTC, EuSouAFazer commented
Good change, looks a lot better. Don't let the soul argument get to you

2023-09-15 17:53 UTC, CoiledLamb commented
> > this is a downgrade honestly, its slightly better in quality but much less clear in what it is and what it does, its also very bland and would be very hard to notice compared to current ones
> 
> The old intercom sprite had much more colour shifting in pixels, as such it was more of a pixel blob than this one. I can't agree that it became less clear, but I can see how some people might not notice them on the walls. But I guess the red buttons and the blue screen must give it away.

if you're conflicted about it, it might be worth posting some images of how it looks in game?
I think they're fine though, personally. might be worth sampling colors from the wallening ver if you didn't make your own palette

2023-09-15 18:16 UTC, Mothblocks commented on code/modules/paperwork/paper_premade.dm
> +	* Supply - 134.7"}
Indent up one

2023-09-15 18:17 UTC, Mothblocks commented
wut

https://github.com/tgstation/tgstation/assets/35135081/728868f9-66d8-41e1-80b5-2cda1b3754be

2023-09-15 18:17 UTC, Mothblocks commented
also plz dont add new "-p" sprites especially since you have the variable now, give it a complete name "powered? unpowered?"

2023-09-15 18:18 UTC, Mothblocks commented
also lets see it in game on some walls since someone said they wonder if it will look bland on them

2023-09-15 18:36 UTC, Sealed101 commented
> wut

diffbot has been freaking out for a few weeks like this, iirc aa was informed at some point

2023-09-15 19:50 UTC, DrDiasyl commented
> also lets see it in game on some walls since someone said they wonder if it will look bland on them

![image](https://github.com/tgstation/tgstation/assets/42353186/38462a2d-a415-4597-b115-937c0b6f6bbb)

2023-09-15 19:50 UTC, DrDiasyl commented
oh great wrong one, here is the right one
![Intercoms](https://github.com/tgstation/tgstation/assets/42353186/9fd6cbb4-ead3-4653-90c4-411b5a960bbd)

2023-09-15 19:59 UTC, CoiledLamb commented
damn that palette does flow directly into the wall in places

2023-09-15 20:19 UTC, DATA-xPUNGED commented
I'm gonna be real with u didn't knew there were specific command intercoms

2023-09-15 21:37 UTC, EricZilla commented
Love this as an independent sprite but it really needs to not blend with iron walls, maybe tone all the grey up a bit?

2023-09-16 01:23 UTC, Serxule commented
> oh great wrong one, here is the right one

is it not multidirectional or

2023-09-16 02:12 UTC, CoiledLamb commented
> > oh great wrong one, here is the right one
> 
> is it not multidirectional or

current one is not multidirectional, you might be thinking of the wallening one.
I don't think multidirectional wallmounts have a great chance of approval either

2023-09-16 03:55 UTC, Wallemations reviewed
Why are you making these individual icons instead of just adding overlays to a normal sprite?

2023-09-16 05:05 UTC, DrDiasyl commented
> Why are you making these individual icons instead of just adding overlays to a normal sprite?

Good question. Just intercoms already have overlays, but I _think_ overlay bloat doesn't exist.

2023-09-16 05:40 UTC, Serxule commented
> > > oh great wrong one, here is the right one
> > 
> > 
> > is it not multidirectional or
> 
> current one is not multidirectional, you might be thinking of the wallening one. I don't think multidirectional wallmounts have a great chance of approval either

i think what looks off to me is that its not centered anymore

also, i'd like to add, this one looks less like a radio by using blue, green/orange are much more iconic and recognizeable as a "radio" color

2023-09-16 06:53 UTC, DrDiasyl commented
> > > > oh great wrong one, here is the right one
> > > 
> > > 
> > > is it not multidirectional or
> > 
> > 
> > current one is not multidirectional, you might be thinking of the wallening one. I don't think multidirectional wallmounts have a great chance of approval either
> 
> i think what looks off to me is that its much more offcentered
> 
> also, i'd like to add, this one looks less like a radio by using blue, green/orange are much more iconic and recognizeable as a "radio" color

Surprisingly the old sprite was the one off-centred, I actually have centred it. Also, the original Intercom sprite had a blue screen, hence this one does too.

2023-09-16 16:02 UTC, DrDiasyl commented
> The sprites themselves look alright, but some in-game screenshots would help.

I posted some in the comments

2023-09-18 18:42 UTC, epochayur commented
Blends in with the walls WAY too much

2023-09-18 18:47 UTC, HalfPunch commented
Now the intercoms look like grandfathers radio
![image](https://github.com/tgstation/tgstation/assets/91390177/089c4847-59cc-4b51-86ea-9f4f0efa43e9)

2023-09-18 18:48 UTC, DrDiasyl commented
> Blends in with the walls WAY too much

Just like the old one's though.

2023-09-19 07:27 UTC, CoiledLamb commented
> > Blends in with the walls WAY too much
> 
> Just like the old one's though.

is a fixable issue. what is the point of a resprite if it has the same issues as what it's respriting?

2023-10-05 00:13 UTC, Wallemations requested changes
You have really zoomed in screenshots, but can we just get a game screenshot with a character in there? Maybe just load up some map and stand in the middle of a hallway & take a 6x6 tile screenshot or something to get the whole picture.

I wanna see how it looks in conjunction with other objects rather than just the one.

2023-10-07 08:58 UTC, DrDiasyl commented
> You have really zoomed in screenshots, but can we just get a game screenshot with a character in there? Maybe just load up some map and stand in the middle of a hallway & take a 6x6 tile screenshot or something to get the whole picture.
> 
> I wanna see how it looks in conjunction with other objects rather than just the one.

@Wallemations here you go
![image](https://github.com/tgstation/tgstation/assets/42353186/1243e295-aaf3-44a7-b829-839f5ca05021)
![image](https://github.com/tgstation/tgstation/assets/42353186/9ddae778-c6a3-435a-91ee-4c3757f52eda)
![image](https://github.com/tgstation/tgstation/assets/42353186/0d6e723c-77ce-4ab4-89b4-f8eb2b0ac255)
![image](https://github.com/tgstation/tgstation/assets/42353186/fd758122-ef6e-4437-a409-1f2e872fbba4)

2023-10-08 08:56 UTC, Wallemations commented
I like them on the north and south but nudge them a little more in for the side walls, it looks like they're peeking a pixel or three out

2023-10-21 15:09 UTC, Ghommie requested changes
Sorry for the late review. Fix the intercom_receive icon state and the conflicts, and you're good to go. Also what Wallemations said.

2023-10-23 10:57 UTC, DrDiasyl commented
> Sorry for the late review. Fix the intercom_receive icon state and the conflicts, and you're good to go. Also what Wallemations said.

All done @Ghommie

2023-10-23 11:45 UTC, merged