clown bomb payload is now properly named and somewhat better summon payload dispersion
tgstation/tgstation pull request #78458
Opened 2023-09-20 04:58 UTC by mc-oofert

## About The Pull Request

renamed clown bomb payloads and gave them a description so they arent just "badmin payload"

also spawn_and_random_walk now has an option to walk in diagonals too

## Why It's Good For The Game

![2023-09-20 06_54_12-Window](https://github.com/tgstation/tgstation/assets/70376633/077497c5-9f32-4e5f-af1b-51a2ade890f8)

## Changelog

:cl:
fix: clown bomb payload is no longer named badmin payload and no longer disperses clowns in cardinal directions only
/:cl:

2023-09-20 13:49 UTC, Jacquerel commented
whats up with the health huds in that screenshot?

2023-09-20 13:50 UTC, mc-oofert commented
> whats up with the health huds in that screenshot?

simple animal clowns did this for a long time

2023-09-22 12:47 UTC, Jacquerel requested changes

2023-09-22 12:47 UTC, Jacquerel commented on code/__HELPERS/mobs.dm
> +				step(X, cardinals_only ? pick(NORTH, SOUTH, EAST, WEST) : pick(NORTH, SOUTH, EAST, WEST, NORTHWEST, NORTHEAST, SOUTHEAST, SOUTHWEST))
```suggestion
				step(X, cardinals_only ? pick(GLOB.cardinals) : pick(GLOB.alldirs))
```

2023-09-22 14:28 UTC, merged