Dead bodies cool to room temp
tgstation/tgstation pull request #78572
Opened 2023-09-25 02:48 UTC by yorii

## About The Pull Request

Fixes #78508

## Why It's Good For The Game

There was already code for heating dead bodies up with room temperature, now there is also code to cool dead bodies to room temperature.

## Changelog

:cl:
fix: dead bodies now cool down to room temperature over time
/:cl:

2023-09-25 03:22 UTC, yorii commented on code/modules/mob/living/carbon/life.dm
>  	if(!on_fire || areatemp > bodytemperature) // If we are not on fire or the area is hotter
Should this really have !on_fire?

2023-09-25 04:26 UTC, yorii commented
I'm not sure if this current commit is preferable over the previous commit...?

2023-09-25 04:42 UTC, yorii commented
Changed it back to the first edit, there were some side effects from just altering the second if-statement.

2023-09-25 04:48 UTC, Kapu1178 requested changes
Humans never call the carbon level handle_environment() proc. Something is wrong here.

2023-09-25 11:32 UTC, ABS-Helmet commented
Do they warm up the room a bit too?

2023-09-26 09:59 UTC, yorii commented
> Do they warm up the room a bit too?

Haha no I don't think there's any such mechanic, other than a body being set on fire :p

2023-09-28 01:56 UTC, ninjanomnom approved these changes

2023-09-28 02:02 UTC, merged