Adds warden to default required enemies for dynamic rulesets
tgstation/tgstation pull request #78610
Opened 2023-09-26 04:20 UTC by Higgin

## About The Pull Request

The parent/default for rulesets had all the other metaprotected roles except warden. Adds warden to the list as I suspect this was an oversight.

## Why It's Good For The Game

It's an edge case, but if you're using the default required enemies for some reason, you probably should count the other guy with access to all the guns too.

## Changelog

:cl:
fix: Added warden to list of default required enemies for rulesets. 
/:cl:

2023-09-26 04:22 UTC, Mothblocks approved these changes

2023-09-26 04:23 UTC, Mothblocks commented
wait, are we sure we want this? the warden is not actively investigating antagonists like everyone else is

2023-09-26 05:42 UTC, Vincent983 commented
to be fair, warden is guarding one of the biggest antag targets (armory) and is important in revolutions where a lot of crates need armory access

2023-09-26 15:31 UTC, moocowswag commented
You can literally just hack into brig and loot armory if you check your pda round start and see that no warden is present because hos / sec team are out validhunting.

There is no rotating shifts of people guarding brig just sec team looting it round start and leaving, the players that watch the brig the most in the absence of warden are probably ais with multicam

2023-09-26 18:19 UTC, BlueMemesauce commented
the armory isnt even that powerful anyway, antags hardly even care about it. i play warden sometimes and the last time anyone broke in was a while ago. i dont think the warden should be counted because he does basically nothing

2023-09-27 08:13 UTC, Higgin commented
> wait, are we sure we want this? the warden is not actively investigating antagonists like everyone else is

at least on lowpop, the warden is as much if not more an effective person to have around for dealing with threats - if you're going to have a security officer or the captain fill the role, it'd seem natural to me to have the warden in the middle there too

2023-09-30 02:17 UTC, Ghommie requested changes
You need to edit the enemy list for [paradox clones](https://github.com/tgstation/tgstation/blob/ef18c748e99fcb84555af1db99e58711567ac052/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm#L865) and [nuclear operatives](https://github.com/tgstation/tgstation/blob/ef18c748e99fcb84555af1db99e58711567ac052/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm#L356) too.

2023-09-30 13:00 UTC, merged