Makes the reverse revolver better hidden.
tgstation/tgstation pull request #78660
Opened 2023-09-28 06:35 UTC by lizardqueenlexi

## About The Pull Request

Fixes #78639

Changes the description of the reverse revolver to match the Syndicate revolver, so you can't tell them apart.

## Why It's Good For The Game

The reverse revolver is supposed to look like a normal Syndicate revolver until you shoot yourself in the face with it. Having an obvious tell is bad.

## Changelog

:cl:
fix: The reverse revolver now looks like a normal Syndicate revolver on inspection.
/:cl:

2023-09-28 09:45 UTC, Fikou requested changes
make it use 515 typepath copying stuff so its always the same as the syndie one

2023-09-28 16:36 UTC, MrMelbert commented
> make it use 515 typepath copying stuff 

i don't think we can use that yet

it'd probably be easier to make the "reverse" aspect an element then we could just make a syndie revolver subtype with it

2023-09-28 18:58 UTC, Fikou commented
> > make it use 515 typepath copying stuff
> 
> i don't think we can use that yet
> 
> it'd probably be easier to make the "reverse" aspect an element then we could just make a syndie revolver subtype with it

then just grab from initial like the bite of 87 springlock

2023-09-29 20:37 UTC, ninjanomnom approved these changes

2023-09-29 20:37 UTC, merged