Fixes a few runtimes with TTS and skips some code if TTS isn't enabled.
tgstation/tgstation pull request #78713
Opened 2023-10-01 17:31 UTC by Iamgoofball

## About The Pull Request

Fixes a few runtimes with TTS and skips some code if TTS isn't enabled.

## Why It's Good For The Game

fixes...good???
## Changelog
:cl:
fix: Fixes a few runtimes with TTS and skips some code if TTS isn't enabled.
/:cl:

2023-10-03 11:05 UTC, Ghommie requested changes

2023-10-03 11:05 UTC, Ghommie commented on code/modules/mob/living/living_say.dm
> +		if(voice && found_client && !message_mods[MODE_CUSTOM_SAY_ERASE_INPUT] && !HAS_TRAIT(src, TRAIT_SIGN_LANG) && !HAS_TRAIT(src, TRAIT_UNKNOWN))
Just add `SStts.tts_enabled &&` before everything else in the second check so that we avoid further indentation.

2023-10-07 20:44 UTC, MrMelbert commented on code/modules/mob/living/living_say.dm
> +				if(human_speaker.wear_mask && istype(human_speaker.wear_mask, /obj/item/clothing/mask))
```suggestion
				if(istype(human_speaker.wear_mask, /obj/item/clothing/mask))
```

2023-10-08 06:35 UTC, Ghommie commented on code/modules/mob/living/living_say.dm
> +			if(human_speaker.wear_mask && istype(human_speaker.wear_mask, /obj/item/clothing/mask))
```suggestion
			if(istype(human_speaker.wear_mask, /obj/item/clothing/mask))
```

2023-10-10 13:37 UTC, merged