Basic Mob Flesh Worm
tgstation/tgstation pull request #78744
Opened 2023-10-03 13:45 UTC by Jacquerel

## About The Pull Request

Converts the Flesh Worm (Armsy) into a Basic Mob.
Most of its behaviour has been moved into a component which we can use to make arbitrary mobs into linked lists of mobs.
To accomplish this I added a signal which is sent when you call any `adjustXLoss` proc, let me know if my implementation is "calling the same signal from several places" by a backdoor, I wanted to avoid registering to 6 signals but I'll change it if I must.

While I was here I killed the unused "lesser" variant because we stopped using it. Resultingly, Ascended Armsy doesn't need to distinguish itself by inflating the sprite, so it doesn't. This means that now flesh worms are using their sprites as intended to be displayed, but if people really miss all of its segments being poorly scaled by the byond engine then I guess I can restore it.

## Why It's Good For The Game

![dreamseeker_p8vOpZGXII](https://github.com/tgstation/tgstation/assets/7483112/3389d3a9-16cd-4e1e-938e-dfa18d0da0af)

## Changelog

:cl:
refactor: Flesh Worms are now basic mobs. Please report any unexpected behaviour.
sprite: Flesh Worms are a little bit slimmer.
/:cl:

2023-10-03 13:55 UTC, Sealed101 commented
closes #68614?

2023-10-03 14:46 UTC, Jacquerel commented
> closes #68614?

![dreamseeker_KTk7o7dpYG](https://github.com/tgstation/tgstation/assets/7483112/37653d9e-350a-404e-a50e-0f602649cdc7)
Looks a bit weird but seems fixed.

2023-10-03 23:17 UTC, san7890 requested changes
nits iirc

2023-10-03 23:17 UTC, san7890 commented on code/modules/admin/verbs/debug.dm
> +	var/attempted_target_path = input(
making worms out of people isn't an admin-critical tool (sadly), make this `tgui_input` instead. you use `tgui_input_number` later on so lets be consistent

2023-10-03 23:17 UTC, san7890 commented on code/modules/admin/verbs/debug.dm
> +	if (!check_rights(R_DEBUG))
`R_FUN` instead imo (or both) (people with `R_DEBUG` can give themselves fun but shhh)

2023-10-03 23:17 UTC, san7890 commented on code/modules/antagonists/heretic/structures/knock_final.dm
> +		/mob/living/basic/heretic_summon/armsy,
alphabetize

2023-10-03 23:17 UTC, san7890 commented on code/datums/components/mob_chain.dm
> +/datum/component/mob_chain
human centipede simulator just in time for halloween (no change)

2023-10-05 19:20 UTC, merged

2023-10-05 23:36 UTC, LemonInTheDark commented
> I added a signal which is sent when you call any `adjustXLoss` proc, let me know if my implementation is "calling the same signal from several places" by a backdoor, I wanted to avoid registering to 6 signals but I'll change it if I must.

I think that'd be a better pattern TBH. You aren't the only one who might want to access this info, and they might want it split up by type. Plus you could just feed them all into one proc, so it's just a RegisterSignals and not RegisterSignal

2023-10-06 00:10 UTC, Jacquerel commented
I'll go back and do it

2023-10-06 00:15 UTC, LemonInTheDark commented
I appreciate it. don't have to if you don't wanna. I won't hold it against you I just saw this on the bus and was like "wait this is bad", and wanted to say somethin when I got to computer.