replaces the engineering outpost on icemoon with a new ruin, unlucky engineer.
tgstation/tgstation pull request #78758
Opened 2023-10-04 01:29 UTC by CoiledLamb

## About The Pull Request
fully wip while i resolve some things
old ruin:
![image](https://github.com/tgstation/tgstation/assets/110322848/c360a6a8-e997-4b15-abcc-d254e840b8e7)
new ruin: 
![2023-10-03 20 24 28](https://github.com/tgstation/tgstation/assets/110322848/48512d2b-8003-4150-967f-3a1860f052d0)

## Why It's Good For The Game
empty for now

## Changelog

:cl:
add: replaces engineering outpost on icemoon with unlucky engineer
/:cl:

2023-10-04 02:02 UTC, Maurukas requested changes
First pass review for issues mentioned in mapping general.

* You have an active turf problem, primarily due to the use of `/airless` turf subtypes instead of `/icemoon` subtypes. This causes them to spawn with a vacuum on them at roundstart. You can use the in-game mapping tools to track them down.
* Please remember to delete `_maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm`, as you're deleting it's map datum and replacing it with a new file.

2023-10-04 02:04 UTC, CoiledLamb commented on code/datums/ruins/icemoon.dm
> +	always_place = TRUE
👍 will do

2023-10-04 18:36 UTC, mc-oofert commented
![image](https://github.com/tgstation/tgstation/assets/70376633/369b7d5c-d8e3-4f50-82db-32c1f050b86e)
among us

2023-10-18 00:14 UTC, Maurukas requested changes

2023-10-18 00:14 UTC, Maurukas commented on code/game/area/areas/ruins/icemoon.dm
> -
This area still exists somewhere and causing CI failures. Check your map files.

2023-10-27 18:47 UTC, CoiledLamb commented
i'm doing the caves of qud mod jam this week so i'll fix this one up when that finishes

2023-11-06 06:36 UTC, san7890 commented
this staled out three separate times just make a new PR when you're ready again

2023-11-06 06:36 UTC, closed without merging

2024-05-26 11:10 UTC, Addust commented
that's just syndicate lavaland engineering