Midround slaughter demons are back on the menu (after roughly four years)
tgstation/tgstation pull request #78753
Opened 2023-10-03 20:51 UTC by Ghommie

## About The Pull Request
Slaughter demons used to be part of a rare, late-round random event before dynamic was ported from /vg/.

Then this happened
https://github.com/tgstation/tgstation/blob/5670e238aa9d87c5416a157cf90be258aa4641c2/code/modules/events/ghost_role/slaughter_event.dm#L8
...and people slowly but surely forgot it was a thing.

So, slaughter demons have been brought back; tweaked a little so they don't roll when less than 30 (from 20) players are around, since they can easily pick players off one by one with hit and run tactics. Required round time reduced a smidge too, because dynamic runs on a budget that might get exhausted sooner or later. Coincidentally, that's also when heavy over light midround rulesets are guaranteed.

## Why It's Good For The Game
Fixes a long-standing oversight that made the game a smidge less chaotic.

## Changelog

:cl:
fix: Midround slaughter demons are back on the menu! (They used to be a random event before 'dynamic' was a thing)
/:cl:

2023-10-03 21:28 UTC, Sealed101 commented
the slaughter demon sweep in the screenshot trsts is hilarious. would vote next president

2023-10-03 21:53 UTC, Ghommie commented on code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
> +	weight = 1 //very rare
So, should I bump it up or down?

2023-10-03 22:24 UTC, nukularpower commented
Does this include laughter demons?  If not, pretty please make it so :D

2023-10-03 22:44 UTC, Ghommie commented
> Does this include laughter demons?

It does.

2023-10-03 23:16 UTC, optimumtact commented
headadmins said they didn't want it and i don't see any reason to override them.

So this will be closed in 24 hours.

2023-10-03 23:20 UTC, optimumtact commented
note you might be able to rescue this PR's code if you make them default to never being picked so they canb e configured on by a future term, but im' not dynamic expert.

2023-10-03 23:26 UTC, Ghommie commented
Easy as changing the requirements to 101.

2023-10-03 23:41 UTC, IndieanaJones commented
You could just remove the dynamic_should_hyjack line and revert it to the original behavior of insanely rare event spawn.

2023-10-03 23:48 UTC, Ghommie commented
> You could just remove the dynamic_should_hyjack line and revert it to the original behavior of insanely rare event spawn.

Antags picked by the game should generally cost threat points, and I don't think having a slaughter demon spawn regardless of overall threat, spent nor unspent, is a good idea.

2023-10-04 02:06 UTC, Mothblocks requested changes
I don't want this in the codebase even off by default because we don't have any way to hide the preference icon even if the ruleset is completely unused, which would just create clutter. I think we should instead just save this for when head admins want it because it's not much code at all to add

2023-10-04 02:28 UTC, closed without merging