Kills `spec_updatehealth`, replaces it with use of `COMSIG_LIVING_HEALTH_UPDATE`
tgstation/tgstation pull request #78772
Opened 2023-10-04 19:20 UTC by MrMelbert

## About The Pull Request

Quick refactor, replaces `spec_updatehealth` with use of `COMSIG_LIVING_HEALTH_UPDATE`.

`spec_updatehealth` was only used by one species, ethereals, and it was used in a (in my opinion) janky way by calling `spec_updatehealth` constantly. 

This has one downside - `COMSIG_LIVING_HEALTH_UPDATE` is NOT sent if the mob is in godmode, while `spec_updatehealth` was, which means godmoded ethereals may not update 100% accurately according to their health before entering godmode, but I doubt this will come into play often at all.

- [x] I tested this PR

## Why It's Good For The Game

`updatehealth` is kinda hot, not turbo hot but a little hot, so this helps performance a bit. 

## Changelog

:cl: Melbert
refactor: Refactors how ethereals update their color when damaged. 
/:cl:

2023-10-05 01:05 UTC, san7890 requested changes

2023-10-05 01:05 UTC, san7890 commented on code/modules/mob/living/carbon/human/species_types/ethereal.dm
> +	UnregisterSignal(former_ethereal, COMSIG_LIVING_HEALTH_UPDATE)
lol do you think we should just fix this and the five other `UnregisterSignal()` calls to do a list of five signals (multilined). pretty ridiculous to keep tacking onto this pattern

2023-10-05 23:27 UTC, LemonInTheDark commented
Don't do it for speed, do it because the old method was dumb

2023-10-06 00:30 UTC, MrMelbert commented
it was because the old reason was dumb, losing some proc call overhead :tm: is just a bonus

2023-10-06 22:03 UTC, merged