Orm Welds to the Floor 2: Weld Harder
tgstation/tgstation pull request #78863
Opened 2023-10-08 11:08 UTC by RedBaronFlyer

## About The Pull Request
I was always a bit surprised about how the ORM could be unwrenched to move, as every other machine requires a multistep process to move. This, combined with most maps having the ORM be in the wall leads to maps such as icebox, tram, birdshot, and especially metastation being a wrench away from being tided into.

After experiencing a round where cargo got tided into nearly ten times (this was on Manuel, MRP moment) I decided to sit down and bother to get this working.

## Demonstration (I wasn't able to get this to fit down into a size of 10 MBs or less, sorry):
https://www.youtube.com/watch?v=k5rWaAinFxs

## Why It's Good For The Game

1. Cargo will now be as secure as other departments (such as botany) that have a similar setup with a machine in the wall by the door.

2. It will bring the ORM in line with other machines. Nearly every other machine in the game currently requires either:
A. Welding and then wrenching (Chef/Botanist/Chemist/Coronor fridges)
B. Deconstructing the entire machine (autolathe, department lathe, microwaves, etc.)

## Changelog

The ORM now requires welding it prior to unwrenching it, bringing it in line with other similar machines such as the chef's fridge vendor.

:cl:
balance: The ORM now requires welding it prior to wrenching it, similar to Chef/Botanist/Chemist/Coronor fridges.
/:cl:

2023-10-08 11:11 UTC, RedBaronFlyer commented
I'm keeping this as a draft at the moment just incase anything weird pops up. I somehow deleted part of line 381 prior to uploading this so I'm trying to be safe.

I didn't know what tag would fit best so I put balance.

2023-10-08 11:12 UTC, mc-oofert commented
how does this improve security of said department theres like 20 welding tools free on the map roundstart

2023-10-08 11:14 UTC, RedBaronFlyer commented
> how does this improve security of said department theres like 20 welding tools free on the map roundstart

It gives cargo a bigger window to stop someone from trying to tide as opposed to how it is right now where you can unwrench the ORM in less than three seconds.

2023-10-08 11:17 UTC, GuillaumePrata commented
> how does this improve security of said department theres like 20 welding tools free on the map roundstart

One day we will have tools be medium sized so not everyone and their mom have a full break in toolset inside a box, inside their bag, every single round.

For now, making it be slight slower is the best we can do.

2023-10-08 11:47 UTC, Fikou commented
why is it even movable if we removed the reason its moved

2023-10-08 19:23 UTC, GPeckman commented
> how does this improve security of said department theres like 20 welding tools free on the map roundstart

In fairness, welding masks are a lot less common and also harder to carry due to being normal-sized.

2023-10-08 20:42 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +	if(welded_down)
Check `silent`

2023-10-08 20:43 UTC, Mothblocks requested changes

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +		to_chat(user, span_warning("[src] is welded to the floor!"))
Balloon alert

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +	air_update_turf(TRUE, anchorvalue)
Named parameter for TRUE

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +		)
balloon_alert_to_viewer

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +		to_chat(user, span_notice("You cut [src] free from the floor."))
balloon_alert

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +		to_chat(user, span_warning("[src] needs to be wrenched to the floor!"))
you must be noticing a pattern here. here and everywhere else

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +	if(!tool.use_tool(src, user, delay=100, volume=100))
```suggestion
	if(!tool.use_tool(src, user, delay = 10 SECONDS, volume=100))
```

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +		balloon_alert(user, "cancelled!")
don't need this balloon alert because the do_after already has a visual tell

2023-10-08 20:43 UTC, Mothblocks commented on code/modules/mining/machine_redemption.dm
> +	if(held_item.tool_behaviour == TOOL_WELDER && !istype(src, /obj/machinery/mineral/ore_redemption))
When would this istype ever pass? This doesn't make any sense

2023-10-09 03:48 UTC, Loafin34 commented
@GuillaumePrata what about pocket crowbars/screwdrivers? why would these be normal-sized and only fit in toolbelts? the welding tool and wrench and wirecutters make some sense, but pocket crowbars are.. pocketable

2023-10-09 05:00 UTC, mc-oofert commented
> why is it even movable if we removed the reason its moved

also this is a fair point why not just make it not unanchorable

if someone deconstructs it to tide you can call them an antag because thats an objective and legally lynch them

2023-10-09 05:46 UTC, GuillaumePrata commented
> @GuillaumePrata what about pocket crowbars/screwdrivers? why would these be normal-sized and only fit in toolbelts? the welding tool and wrench and wirecutters make some sense, but pocket crowbars are.. pocketable

We simply... remove the pocket crowbars from the game and just keep the medium sized ones...
Screwdrivers are whatever and so are multitools and wirecutters, not every tool needs to be medium sized to end the break in kit in a box which costs a whooping 1/49th of a player backpack per tool.

I went on a tangent so to go back on topic, the PR that made Rwalls be "slightly" harder to break in was one of the best changes in the game IMO, meaningful break ins make the round drama a lot more interesting, and the game will benefit from a slightly harder to break in cargo.

2023-10-09 06:02 UTC, zxaber commented
Can it still be deconstructed with a screwdriver and crowbar, or does being welded prevent that?

Does anyone actually use the ORM to dispense mats? Does it even need to be public facing anymore?

2023-10-09 08:47 UTC, zxaber commented
>It can still be deconstructed with a screwdriver and a crowbar, though you would also need to wrench the machine frame and move it out of the way

I would bet cash money that this will lead to it being deconstructed most rounds, and now you'll have to deal with tiders in cargo *and* rebuilding/re-syncing the ORM.

Can we add a check in the deconstruction proc to fail if it's welded?

2023-10-09 10:22 UTC, RedBaronFlyer commented
> > It can still be deconstructed with a screwdriver and a crowbar, though you would also need to wrench the machine frame and move it out of the way
> 
> I would bet cash money that this will lead to it being deconstructed most rounds, and now you'll have to deal with tiders in cargo _and_ rebuilding/re-syncing the ORM.
> 
> Can we add a check in the deconstruction proc to fail if it's welded?

I'll see what I can do.

2023-10-09 22:25 UTC, RedBaronFlyer commented
Alright, so this vastly went over my head in no time flat. So the plan was just to copy over the code that the smartfridge uses so that cargo didn't get tided into every round. I wasn't expecting to need to update things to comply with modern TG coding standards, though I completely understand why this would be requested of me. There is also the aforementioned issue of tiders breaking down the ORM as opposed to welding it. I simply lack the ability to get this working in a way that I would find satisfactory and in a manner that would be acceptable to TG coding standards.

I fully get that, and I am not blaming anyone but myself for what I got myself into.

Anyone else can pick this up in the future if they want.

2023-10-09 22:25 UTC, closed without merging