Fixes a bug with the scope getting stuck on mobs that get dusted or ghost
tgstation/tgstation pull request #78941
Opened 2023-10-12 00:57 UTC by vinylspiders

## About The Pull Request

If you ghost while mid-scope (or similarly, if you get dusted/your mob gets deleted) the mob's cursor would get all messed up due to some oversights. This just clears up some of these logic errors and ensures everything gets cleaned up properly.

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/24189
Fixes https://github.com/tgstation/tgstation/issues/78756

## Why It's Good For The Game

Fixes a bug. I don't think scopes are even in use here but they are downstream.

<details>
<summary>Deleted and being dusted resets perspective and cursor properly</summary>

![dreamseeker_SSU4YnEK4n](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/dcaa5238-0067-4923-a956-24c6ba4aa2b3)

![dreamseeker_GZEhuSJSGS](https://github.com/Skyrat-SS13/Skyrat-tg/assets/13398309/2b88db21-6560-486d-94d3-9773fa543c50)

</details>

<details>
<summary>So does ghosting</summary>

![dreamseeker_7n3uXZvDSI](https://github.com/tgstation/tgstation/assets/13398309/08f6272d-baba-4e8e-ae0b-db23331982f7)

</details>

## Changelog

:cl:
fix: being killed or ghosting while being scoped will no longer cause the cursor offset to persist in a bugged state
/:cl:

2023-10-12 11:40 UTC, SyncIt21 commented
Fixes #78756?

2023-10-16 23:28 UTC, san7890 requested changes
small nits, moderate code concerns/considerations

2023-10-16 23:28 UTC, san7890 commented on code/datums/components/scope.dm
> +/datum/component/scope/proc/zoom(mob/living/user)
why is this on the `living` level? feels like a hurtful typecast when we aren't even sure that it is a living mob or not.

2023-10-16 23:28 UTC, san7890 commented on code/datums/components/scope.dm
> +	RegisterSignal(user, COMSIG_QDELETING, PROC_REF(stop_zooming))
```suggestion
	RegisterSignals(user, list(COMSIG_MOB_SWAP_HANDS, COMSIG_QDELETING), PROC_REF(stop_zooming))
```

2023-10-16 23:28 UTC, san7890 commented on code/datums/components/scope.dm
> +	UnregisterSignal(user, COMSIG_QDELETING)
```suggestion
	UnregisterSignal(user, list(COMSIG_MOB_SWAP_HANDS, COMSIG_QDELETING))
```

yes it is `UnregisterSignal`

2023-10-16 23:28 UTC, san7890 commented on code/datums/components/scope.dm
>  	if(!user.client)
```suggestion
	if(isnull(user.client))
```

may as well

2023-10-17 19:08 UTC, merged