Blackout qol
tgstation/tgstation pull request #78965
Opened 2023-10-13 01:27 UTC by TheBoondock

## About The Pull Request
This pr improves the gameplay of blackout drunk character via:
-Add hiccup sound cues and emote
-Add warning for duration running out
-Makes it more reasonable for blackout character to survives
-Makes it harder for blackout character to sleep
Balance changes:
-Blackout char will have random 10 seconds bouts of inability to interact with advance tools, computer, tools, scanner etc..
-Blackout char will gain some buff in exchange (TBD): pls give suggestion in comment 
To-do
- [ ] Add some sort of buff for blackout character

## Why It's Good For The Game
Makes it so blackout character gameplay is more enjoyable than just getting sleep for 90 seconds, plus more feedback for the surrounding player to know that they are blackout. The penalty is added so that its harder for player to majorly grief i.e assembling the ttv, or turning off power/sm cooling, wont stop them outright tho.

## Changelog

:cl:
qol: improves blackout drunk character gameplay
fix: fixed improper prob() placement that caused blackout character to be forced sleep
sound: added hiccup sound
/:cl:

2023-10-13 01:49 UTC, EricZilla commented
You should make them waddle like the clown too lmao

2023-10-13 20:46 UTC, Wallemations commented
You could increase their wound resistance, since I don't think we have any form of pain in the code

2023-10-19 04:21 UTC, TheBoondock commented
> You could increase their wound resistance, since I don't think we have any form of pain in the code

Staminadmg is sort of our pain system so thats what im giving em

2023-10-20 17:04 UTC, Ghommie requested changes

2023-10-20 17:04 UTC, Ghommie commented on code/datums/brain_damage/split_personality.dm
> +	if(prob(30))
Might be hiccupping a tad too frequently.

2023-10-20 22:28 UTC, TheBoondock commented on sound/effects/sf_hiccup_male_01.ogg
liscense is CC BY 3

2023-10-21 01:22 UTC, Ghommie commented on sound/effects/sf_hiccup_male_01.ogg
Then include it in the attribution file.

2023-10-21 17:13 UTC, Ghommie commented on code/datums/status_effects/debuffs/drunk.dm
> +			owner.slip(1 SECONDS)
Hey, can you move this check before the gain_trauma line? That may fix #79138, but at the least we won't constantly attempt to give the trauma when the mob already has it. Also remove the `else` from the `if` control statement, it's unnecessary around `return` statements.

2023-10-23 23:56 UTC, TheBoondock commented on sound/effects/sf_hiccup_male_01.ogg
oops sorry the producers uses a unique liscense which im sure is available under section 4 of their aggreement https://www.soundfishing.eu/licence-LESF.html

2023-10-24 01:08 UTC, merged