Basic Constructs: Artificer
tgstation/tgstation pull request #79015
Opened 2023-10-15 09:53 UTC by lizardqueenlexi

## About The Pull Request

Really getting into the meat of the constructs now. Artificers have become basic mobs.

On the whole, this was a pretty rote conversion, with no significant gameplay changes other than the switch to using healing hands rather than a unique heal ability. The player experience as an artificer is more or less identical.

The _interesting_ part comes with the AI for the seldom-used "hostile" variant. Hostile artificers, being squishy and laughably weak, are now a dedicated "medic" role for constructs. They will perform triage, always seeking the most wounded construct (or shade!) to give healing to. They will not attack at all, but they _will_ flee with great speed if attacked and not busy healing. If they are healing another construct, they will remain even if they are beaten to death.

I've added some more AI functionality that may come in handy in the future:
- An "attack wounded only" option for targetting datums. If true, non-wounded living targets will be ignored entirely. Useful for a medic AI, as seen here, or for a theoretical mob that only hunts those who are already weakened.
- A planning subtree for finding targets that will always select the most heavily wounded living target that the mob can see (or rather, the one with the least health). Useful again for medical triage, or for making a particularly cruel mob that always attacks whoever is easiest to kill. I plan to use this for NPC wraith constructs when I convert them.

In addition, this PR fixes a pair of bugs from #78807 that I didn't catch:
- Healing constructs can now actually heal shades. Turns out I forgot to add the correct biotype.
- Healing hands, when set to print the target's remaining health, no longer does so as a visible message.

The one thing I didn't do that I kind of wanted to is make NPC artificers heal themselves when wounded and not busy doing something else, but it ended up being kind of annoying to make a mob willingly target itself. NPC artificers never had this behavior before, so I consider it okay, but maybe I'll circle back to it later.

## Why It's Good For The Game

Another basic conversion, another 5 items off the checklist. Very little should change in-game, though I think the new NPC AI could make for interesting challenges in ruins or bitrunning or something.

## Changelog

:cl:
refactor: Artificer constructs have been converted to the basic mob framework. This should change very little about them, but please report any bugs. NPC artificers are now smarter, and will focus on healing nearby wounded constructs - if you see them, take them out first!
/:cl:

2023-10-15 14:36 UTC, Jacquerel requested changes

2023-10-15 14:36 UTC, Jacquerel commented on code/datums/ai/basic_mobs/targetting_datums/basic_targetting_datum.dm
> +	var/wounded_only = FALSE
I don't know if I love this being a flag on all instances of this behaviour, maybe we need a `check_valid_living` proc you can extend or something. 
Frankly a few of these should be on the blackboard too, ideally don't want to start proliferating subtypes with inheritance largely based on different combinations of booleans.

2023-10-15 14:36 UTC, Jacquerel commented on code/datums/ai/basic_mobs/targetting_datums/basic_targetting_datum.dm
> +/datum/targetting_datum/basic/attack_wounded_only/same_faction
Here's some examples of subtypes which should preferably just be blackboard key behaviour (including the stat_attack ones you didn't add)

2023-10-15 14:36 UTC, Jacquerel commented on code/modules/antagonists/cult/runes.dm
> +		if(istype(user, /mob/living/simple_animal/hostile/construct/wraith/angelic) || istype(user, /mob/living/simple_animal/hostile/construct/juggernaut/angelic) || istype(user, /mob/living/basic/constru
This is an awful check which should be a trait, but you didn't add it so ignore it if you want.

2023-10-15 14:36 UTC, Jacquerel commented on code/modules/mob/living/basic/constructs/artificer.dm
>  /////////////////////////////Artificer-alts/////////////////////////
Minor but can we remove the big comment headers to just use `//` ?
It fucks with autodocs

2023-10-15 14:36 UTC, Jacquerel commented on code/modules/mob/living/basic/constructs/construct_ai.dm
> +		return .
```suggestion
	if(isconstruct(the_target) || istype(the_target, /mob/living/simple_animal/shade))
		return ..()
```
no point doing the super call if we know we're returning false

2023-10-15 17:31 UTC, Yobrocharlie commented
Good PR

2023-10-17 05:07 UTC, lizardqueenlexi commented
Drafting because fucking with targetting datums has caused some problems I need to fix.

2023-10-20 03:06 UTC, san7890 commented
conflicts

2023-10-20 05:03 UTC, merged