fixes oxyloss not knocking people out at 50
tgstation/tgstation pull request #79036
Opened 2023-10-16 16:00 UTC by Higgin

## About The Pull Request

be it far from me to explain why the args not getting put in directly broke this, but reinserting them into the check_passout stuff from #78657 fixes it.

should close #79034 but I have no clue if other similar changes to how args were being handled might not have problems elsewhere.

## Why It's Good For The Game

atmospheric simulator, breathing mechanics good, also chems and i guess bleeding and whatnot

## Changelog

:cl:
fix: automatic breathers rejoice. oxyloss now knocks people out again.
/:cl:

2023-10-16 17:55 UTC, vinylspiders requested changes
This doesn't sound right. Prior to https://github.com/tgstation/tgstation/pull/78657 `.` would be set to `oxyloss` (aka the mob's _oxyloss_ BEFORE applying damage--which was wrong to begin with but it worked, sort of).

Then in https://github.com/tgstation/tgstation/pull/78657 I changed it so `.` is the _net change_ in oxyloss. So with your change you will now only get knocked out if you took 50 or more oxyloss damage in _one go_. I'm not sure how you tested this but yeah..

I think the following changes should fix the issue?

I should really add another unit test for this.

2023-10-17 00:28 UTC, Higgin commented
> This doesn't sound right. Prior to #78657 `.` would be set to `oxyloss` (aka the mob's _oxyloss_ BEFORE applying damage--which was wrong to begin with but it worked, sort of).
> 
> Then in #78657 I changed it so `.` is the _net change_ in oxyloss. So with your change you will now only get knocked out if you took 50 or more oxyloss damage in _one go_. I'm not sure how you tested this but yeah..
> 
> I think the following changes should fix the issue?
> 
> I should really add another unit test for this.

I tested it by walking up to a medical kiosk, turning my internals on at 0 kPa, and waiting. It caused me to KO over 50 (I think it hit 52 on that tick.) It worked.

I'll try out these changes and post an update.

2023-10-17 01:11 UTC, Higgin commented
Works. Left the !(isnum(mob_oxyloss) check because I'm scared.

2023-10-19 21:37 UTC, merged

2023-10-19 21:38 UTC, Ghommie commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	else if(mob_oxyloss < 50)
fuck, this should've been `HAS_TRAIT_FROM(src, TRAIT_KNOCKEDOUT, OXYLOSS_TRAIT)`.

2023-10-19 22:35 UTC, Ghommie commented on code/modules/mob/living/carbon/carbon_defense.dm
> +	else if(mob_oxyloss < 50)
yea