Adds Custom Announcement Dividers
tgstation/tgstation pull request #79071
Opened 2023-10-18 05:40 UTC by san7890

This ports a whole bunch of various PRs and commits from https://github.com/effigy-se/effigy-se , with heavy refactoring to keep it fresh for /tg/'s code standards.

## About The Pull Request

The whole slew of announcement touchups lately (as in #78995 (37db1ecbf8d7ceeaeb134c56b403339555f44cea) / #79052 (12308dbd3dae702a1c7b9f7f80d7859aea085c82)) have made me realize how much this stuff sucks. The author of these new spans was advertising these in coding general, so I sat down and coded it. Look at the spans, they're much nicer than what we had going on:

<details>
<summary>Dark Mode</summary>
![image](https://github.com/tgstation/tgstation/assets/34697715/7d31d2f9-31e2-4fb1-850a-f02cbe83a040)
![image](https://github.com/tgstation/tgstation/assets/34697715/33ef1bca-8074-4c6e-9a88-5841129297fb)
</details>

<details>
<summary>Light Mode</summary>
![image](https://github.com/tgstation/tgstation/assets/34697715/9efcfaa4-e177-428e-8189-b2dbafc370b3)
![image](https://github.com/tgstation/tgstation/assets/34697715/11a5fcc8-6155-439b-95c6-4a45fb2d4d7a)
</details>

This PR also features

* Major announcement code handling cleanup! There was a lot of copypasta so let's distill it all down into one proc
* Better cacheing! We were doing a shit load of new string generation needlessly! That's fixed now.
* Better string concatenation! Lists are better for string tree reasons. It still works just as well, as you can see from the screenshots above. Best of all, no fucking `<br>` dogshit everywhere!
* All of our string mangling stuff is now all span macros! I love macros.

## Why It's Good For The Game

In the same vein of adding examine blocks (#67937 (b864589522f4f14183270a62dbea3df8028d2eb6)) because it used to suck really hard, I think this is a really nice way to draw attention to announcements in the chat box without needing a shit load of line breaks that just really look ugly. You can look at the PRs/commits I linked above for an idea of just how ugly it could be getting.

## Changelog

:cl: LT3, san7890
add: Announcements have gotten a fresh coat of paint! They should be popping with splendid new colors and should have a lot less ugly linebreaks, while still managing to keep your attention at the screen.
/:cl:

I know we didn't need to port all the CSS themes but I added them anyways in case admins wanna have some fun.
There can probably be more improvements, just figured I'd crack it out while I had time.

2023-10-18 06:11 UTC, lessthnthree requested changes

2023-10-18 06:11 UTC, lessthnthree commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +.minor_announcement_text {
```suggestion
.minor_announcement_title {
```

2023-10-18 06:11 UTC, lessthnthree commented on code/__HELPERS/priority_announce.dm
> +#define MINOR_ANNOUNCEMENT_TITLE(string) ("<span class='minor_announcement_text'>" + string + "</span>")
```suggestion
#define MINOR_ANNOUNCEMENT_TITLE(string) ("<span class='minor_announcement_title'>" + string + "</span>")
```

2023-10-18 06:12 UTC, lessthnthree commented on tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
> +.minor_announcement_text {
```suggestion
.minor_announcement_title {
```

2023-10-18 06:13 UTC, lessthnthree commented on code/__HELPERS/priority_announce.dm
> +#define MINOR_ANNOUNCEMENT_TITLE(string) ("<span class='minor_announcement_text'>" + string + "</span>")
missed changing this in a few spots

2023-10-18 06:13 UTC, lessthnthree commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +.minor_announcement_text {
here too

2023-10-18 06:13 UTC, lessthnthree commented on tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
> +.minor_announcement_text {
one more

2023-10-18 22:30 UTC, san7890 commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +}
I'll ponder on this but I think this can also be done later. If I have time I'll see if I can confangle a demo but I'm no CSS ninja

2023-10-18 22:30 UTC, san7890 commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +.chat_alert_default {
Yeah I think this one should definitely be done, thanks for the mockup

2023-10-19 04:49 UTC, san7890 commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +}
yeah implementing something like this is beyond the reach of my skill. it doesn't seem possible to do it in a really clean way from what I was reading about this stuff online, especially now that we've macroized the css classes per the other review. this is a challenge for another day.

2023-10-20 16:09 UTC, lessthnthree commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +@each $color-name, $color-value in $alert-stripe-colors {
> Neither of us are very good at this, but would it be possible for this to have its own module, which is then included on both style sheets? Not necessary, but it'd be a plus.

Dark and light sheets need different values due to background color.

2023-10-20 16:14 UTC, Ghommie commented on tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
> +@each $color-name, $color-value in $alert-stripe-colors {
That's also true.

2023-10-20 17:32 UTC, san7890 commented on code/__HELPERS/priority_announce.dm
> +		if(length(title) > 0)
No but it's a codehint pattern that tends to be more explicit. I critiqued some other guys with that same point (implying there's a potential negative text length) over this and they said it just felt better to be more explicit, which I conceded

I dont care either way

2023-10-20 19:35 UTC, merged