Fixes magic mirrors not being able to change your race (?)
tgstation/tgstation pull request #79075
Opened 2023-10-18 07:07 UTC by MrMelbert

## About The Pull Request

Not sure why this exactly was happening but I just changed around some vars and it fixed

![image](https://github.com/tgstation/tgstation/assets/51863163/2d8c3d17-593d-4df2-bb67-b18f70a73add)

Also it was assigning a qdeling datum to a mob. Bad bad bad

## Changelog

:cl: Melbert
fix: Magic Mirrors can change your race again (?)
/:cl:

2023-10-18 07:09 UTC, MrMelbert commented
![image](https://github.com/tgstation/tgstation/assets/51863163/ce4fea18-7a43-44cc-bf38-228d7869d375)

2023-10-18 07:27 UTC, GPeckman commented
So even though `meme["yeah"]` is just a typepath, byond sees `meme` and assumes it is a list?

2023-10-18 19:49 UTC, vinylspiders requested changes

2023-10-18 20:07 UTC, MrMelbert commented on code/game/objects/structures/mirror.dm
> +		qdel(newrace)
1. We only need to qdel it if we don't end up using it.
2. `set_species` takes instantiated species as well as a species typepath, so both are valid.

2023-10-18 20:56 UTC, JohnFulpWillard commented
3rd time magic mirrors broke in recent memory let’s shoot for 5 by the end of the year

2023-10-18 23:52 UTC, ATH1909 commented
do magic mirrors still do that thing where they run the normal mirror code before the prompt for the magic mirror selection menu? like, you get prompted to change your hair, beard, etc. first and THEN the big prompt that lets you change things like species.

2023-10-19 02:38 UTC, MrMelbert commented
> do magic mirrors still do that thing where they run the normal mirror code before the prompt for the magic mirror selection menu? like, you get prompted to change your hair, beard, etc. first and THEN the big prompt that lets you change things like species.

No someone made them into radial

2023-10-19 04:50 UTC, merged