Better looking ghost notifications
tgstation/tgstation pull request #79139
Opened 2023-10-21 08:24 UTC by jlsnow301

## About The Pull Request
![image](https://github.com/tgstation/tgstation/assets/42397676/39812cc2-06b6-4eb3-85b9-cbc2fc625263)

Cleaned up some code around the proc itself - really needed some TLC. That, and added an arg to minor announcements to override colors.

## Why It's Good For The Game
More obvious. Code really needed some TLC also

## Changelog

:cl:
add: Ghost announcements are now in announcement blocks.
/:cl:

2023-10-21 17:47 UTC, jlsnow301 commented on code/modules/mob/mob_helpers.dm
> -		if(!alert_overlay)
There has to be another way to do all of this, this is all so cursed

2023-10-22 00:37 UTC, san7890 requested changes

2023-10-22 00:37 UTC, san7890 commented on code/__HELPERS/priority_announce.dm
> +/proc/minor_announce(message, title = "Attention:", alert = FALSE, html_encode = TRUE, list/players, sound_override, should_play_sound = TRUE, color_override)
add your new argument to the documentation

2023-10-22 00:37 UTC, san7890 commented on code/modules/mob/mob_helpers.dm
> +		)
```suggestion
		var/atom/movable/screen/alert/notify_action/toast = ghost.throw_alert(
			category = "[REF(source)]_notify_action",
			type = /atom/movable/screen/alert/notify_action,
			new_master = source,
		)
```

no need for these

2023-10-22 00:37 UTC, san7890 commented on code/modules/mob/mob_helpers.dm
> +) //Easy notification of ghosts.
```suggestion
/proc/notify_ghosts(
	message,
	ghost_sound,
	enter_link,
	atom/source,
	mutable_appearance/alert_overlay,
	action = NOTIFY_JUMP,
	flashwindow = TRUE,
	ignore_mapload = TRUE,
	ignore_key,
	header,
	notify_suiciders = TRUE,
	notify_volume = 100
)
```

no need for backslashes when it's a proc, we only really need backslashes in macro-wrapped stuff like `AddComponent` and `AddElement`. BYOND-standard stuff works natively with multilining. Also that comment is not useful so let's axe it.

2023-10-22 01:52 UTC, jlsnow301 commented on code/modules/mob/mob_helpers.dm
> +		)
wew

2023-10-22 04:57 UTC, merged