Fishing-related bounties.
tgstation/tgstation pull request #79136
Opened 2023-10-21 05:50 UTC by Ghommie

## About The Pull Request
This PR adds three basic/assistant bounties for shipping fish. They've above par rewards when compared to other bounties, however, each shipped fish that is either dead or comes from a case (bought from cargo, cause that's lazy) will reduce the payout by a portion of it.

The three bounties are the following: One for any kind of fish, another for fish of matching water type (freshwater, saltwater, sulphuric water), and lastly, one for specific types of fish, which could be easy money if RNG is with you.

## Why It's Good For The Game
I wanted to add something slightly diffrent from most grimy assistant/basic bounties, where you either just print the stuff from the nearby autolathe for little money or go fetch it also for spare changes. Also, this provides another outlet to fishing, I guess.

## Changelog

:cl:
add: Added a few fish related bounties.
/:cl:

2023-10-22 04:20 UTC, Cadunkus commented
Now to fix fishing so it isn't complete trash!

2023-10-24 16:37 UTC, Jacquerel requested changes
How do you deliver a live fish? Just do it quickly? Or is there some equipment I have forgotten about which preserves them?

2023-10-24 16:37 UTC, Jacquerel commented on code/modules/cargo/bounties/assistant.dm
> +	if(!choosable_fishes)
```suggestion
	if(isnull(choosable_fishes))
```

2023-10-27 23:53 UTC, Ghommie commented
> How do you deliver a live fish? Just do it quickly? Or is there some equipment I have forgotten about which preserves them?

Fish cases, though it seems there's currently only one way to get them and that is buying fish from cargo. Guess I'll have to add a design so that they can be printed from lathes.

2023-10-28 20:53 UTC, merged