GMM & Cargo budget handling tweaks
tgstation/tgstation pull request #79145
Opened 2023-10-21 12:32 UTC by SyncIt21

## About The Pull Request
- Fixes #79115

This PR is a 2-part solution as specified by the last paragraph of the above-mentioned issue.

> but also, for you to be prevented from adding more to an order that you don't reasonably have the funds in that account to afford 

The GMM will now not add stacks to an existing order if it exceeds the available (private or cargo depending on the mode of ordering) budget. Every time it appends stacks to your order it will display a message and if it exceeds the available budget, it will display a message for that too as follows.
![Screenshot (329)](https://github.com/tgstation/tgstation/assets/110812394/3ce588f0-429a-492e-9203-68d234a73149)

But this is not enough. The below example will explain why.

Say you have a budget of 500 cr in both private & cargo.
1. Place an order of materials worth 500 cr be it private or by cargo budget.
2.  Now go spend that budget on something such that it falls below 500 cr, say in this example you overspend, and the available budget becomes 0(you broke)
3. Now go call the shuttle. The order gets rejected but it's left hanging in the cargo checkout queue and will only be cleared till you raise your budget above 500 cr and again recall the shuttle.

This example just applies to 500 cr but with larger amounts you order will be hanging in the queue indefinitely till your broke... makes the available budget to finally purchase it

To fix this we go to the 2nd part of the paragraph

> An ideal fix would be for GMM orders to be cancellable.

cargo will now **"remove/cancel"** this order and will not leave it hanging in the queue indefinitely. So, this way if you by accident made a material order way beyond your available budget cargo will forgive you and clear you of that debt so you can start a fresh order.

## Changelog
:cl:
fix: Cargo will remove/cancel orders from its cart if that order exceeds the available budget (both private or cargo) and the player cannot cancel this order manually.
fix: Galactic material market will deny appending stacks to your existing order if it exceeds the available (private or cargo depending on the mode of ordering) budget.
/:cl:

2023-10-21 12:33 UTC, SyncIt21 commented
@ArcaneMusic

2023-10-27 06:21 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/MatMarket.tsx
> +  orderingPrive: BooleanLike; // you will need to import this
can you remove this comment please lol. why is this still here

2023-10-28 08:27 UTC, ArcaneMusic requested changes
What I could pick out tonight, a few things

2023-10-28 08:27 UTC, ArcaneMusic commented on code/modules/cargo/materials_market.dm
> +					say("There is not enough sheets in the market! Please wait for them to arrive before ordering more.")
```suggestion
					say("There aren't enough sheets on the market! Please wait for more sheets to be traded before adding more.")
```

2023-10-28 08:27 UTC, ArcaneMusic commented on code/modules/cargo/materials_market.dm
> +				say("Order appended, total cost is [current_order.get_final_cost()] cr.")
![image](https://github.com/tgstation/tgstation/assets/41715314/2dc764b5-c142-494c-883b-e2bc58ff3a6e)


This is extremely effective at spamming the chat. I would recommend either using a non-dynamic message, using a dynamic messages and maybe a cooldown for how often they appear, or keeping the dynamic message as is and swapping to to_chat instead.

2023-10-28 11:58 UTC, SyncIt21 commented on code/modules/cargo/materials_market.dm
> +		current_cost = current_order.get_final_cost()
The actual cost should be adjusted in the supply order & pack level so even cargo knows about it. I'll adjust it there

2023-10-28 11:58 UTC, SyncIt21 commented on code/modules/cargo/materials_market.dm
> +		current_cost = current_order.get_final_cost()
Crate value added to `/datum/supply_pack/custom/minerals/get_cost()`

2023-10-30 16:03 UTC, Jacquerel requested changes
Couple of little spelling things, couple of implementation notes.

2023-10-30 16:03 UTC, Jacquerel commented on code/modules/cargo/materials_market.dm
> +					say("There is already 10 stacks of sheets on order! Please wait for them to arrive before ordering more.")
```suggestion
					say("There are already 10 stacks of sheets on order! Please wait for them to arrive before ordering more.")
```

2023-10-30 16:03 UTC, Jacquerel commented on code/modules/cargo/materials_market.dm
> +					say("Order exceeds available budget!. Please send it before purchasing more.")
```suggestion
					say("Order exceeds available budget! Please send it before purchasing more.")
```

2023-10-30 16:03 UTC, Jacquerel commented on code/modules/cargo/materials_market.dm
> +	addtimer(CALLBACK(src, PROC_REF(update_value)), 5 MINUTES)
```suggestion
	addtimer(CALLBACK(src, PROC_REF(value_warning)), 2.5 MINUTES, TIMER_DELETE_ME)
	addtimer(CALLBACK(src, PROC_REF(update_value)), 5 MINUTES, TIMER_DELETE_ME)
```
Just to make sure we clean these up promptly on item destruction.

2023-10-31 01:49 UTC, merged