Improves the deployable component
tgstation/tgstation pull request #79199
Opened 2023-10-22 23:55 UTC by Paxilmaniac

## About The Pull Request

The deployable component had a few random things I noticed when I tried actually using it that kinda sucked so I'm:

Making the examine message more generic, we did NOT need to make it that complicated.
Letting anything with hands deploy stuff, because mobs other than humans can hold things.
Giving the option to let something be deployed more than once.
Letting direction setting be optional.
Tweaking the check for if something can be placed somewhere to be a bit better.

## Why It's Good For The Game

I want to use the deployable component for stuff but I made it awful.

## Changelog

:cl:
code: the deployable component has been tweaked and improved with some new options to it
/:cl:

2023-10-24 17:18 UTC, Jacquerel requested changes

2023-10-24 17:18 UTC, Jacquerel commented on code/datums/components/deployable.dm
> +	var/new_direction
```suggestion
	// The object we are going to create
	var/atom/deployed_object
	// The turf our object is going to be deployed to
	var/turf/deploy_location
	// What direction will the deployed object be placed facing
	var/new_direction
```
Minor but I think dmdocs in the middle of a proc will confuse it into thinking these apply to the next proc

2023-10-24 17:18 UTC, Jacquerel commented on code/datums/components/deployable.dm
> +	examine_list += span_notice("It can be used <b>in hand</b> to deploy into \a [deployed_name].")
Another very minor thing, but if `multiple_deployments` makes an item more of a "thing dispenser" the word into maybe doesn't make sense there? 
Might want it to be `deploy a [thing]` or `deploy into a [thing]` based on the properties.

2023-10-27 23:42 UTC, Paxilmaniac commented
Where's that gif of "monkey business when it sees a pr without failing checks" again

2023-10-28 00:25 UTC, merged