Basic Shades
tgstation/tgstation pull request #79469
Opened 2023-11-02 01:12 UTC by lizardqueenlexi

## About The Pull Request

Makes shades into basic mobs. As they are solely player-controller and have no AI, this was a very simple conversion.

Things of note:
- I've made shades use the same "theme" system as constructs, to determine their drops and coloration - as opposed to these things being manually set by the type of soulstone they're held in.
- I've reorganized files slightly, putting both constructs and shades in a new "cult" basic mob folder.

That's more or less it. As I said, shades are simple.

## Why It's Good For The Game

Basic-izes another mob and cleans up the code a little. Removes the last cult-related simplemob, too.

## Changelog

:cl:
refactor: Shades now use the basic mob framework. Please report any bugs.
/:cl:

2023-11-02 15:35 UTC, Jacquerel requested changes
Not anything you should change for this PR which is a good pure refactor, but it's always been weird to me that shades are so boring. 
They're ghosts? But ones which are stopped by walls and can... ventcrawl. I guess they're made of some kind of evil gas.

2023-11-02 15:35 UTC, Jacquerel commented on code/modules/mob/living/basic/cult/shade.dm
> +	if(!isnull(theme))
If theme can be null here then wouldn't `remains_by_theme[theme]` earlier runtime?

2023-11-02 20:51 UTC, lizardqueenlexi commented
> Not anything you should change for this PR which is a good pure refactor, but it's always been weird to me that shades are so boring. They're ghosts? But ones which are stopped by walls and can... ventcrawl. I guess they're made of some kind of evil gas.

Literally the only thing they have going for them is that they're extremely fast, but I'm really not sure what they're _for_. Being annoying?

2023-11-03 14:52 UTC, Jacquerel commented
Resolve conflicts and hopefully that won't disable automerge

2023-11-03 19:46 UTC, san7890 commented
it will disable auto-merge because any push from someone who doesn't have write access will turn it off. it worked the other day because I have write access

2023-11-03 22:39 UTC, merged