[NO GBP] Final precision rounding for reagent volumes
tgstation/tgstation pull request #79571
Opened 2023-11-07 07:36 UTC by SyncIt21

## About The Pull Request
- Fixes #79566

This applies mostly to plumbing reaction chambers but to implement that fix some rounding operations had to be carried over to `holder.dm`(which will benefit everything in general)

I'm pulling out all the stops here. Rather than checking "are we close enough" plumbing reaction chambers will now check if we and i quote "absolutely insanely precisely there". This means volumes like 49.9999 should become 50 period.

Note this is a high probability & not a definite fix. i.e. now theoretically 100% of the time you should not get this problem but if it still happens then as of now i have no solution and have to go back to the drawing board on this one but i am very confident this should be the end of all plumbing related problems i.e. at least problems with volumes not getting rounded to whole numbers

## Changelog
:cl:
fix: plumbing factories should not rarely/randomly brick at volumes like 0.9999(when in fact it should have been 1)
/:cl:

2023-11-07 07:40 UTC, SyncIt21 commented
@MidoriWroth go ahead.

2023-11-07 15:44 UTC, MidoriWroth commented
i'll give it a go when i get home from work in a bit

2023-11-07 15:45 UTC, SyncIt21 commented
> i'll give it a go when i get home from work in a bit

Yup. This will remain drafted till you say so

2023-11-07 19:41 UTC, MidoriWroth commented
well i tested it and let the factory run for a while, seems to have no actual issues and works fine.

2023-11-07 20:24 UTC, MidoriWroth commented
oh actually i noticed the new table salt recipe (sodium + chlorine) wasn't working, so i checked the reagent search and it was this: 
![5ilvWyR](https://github.com/tgstation/tgstation/assets/18170896/cd43f9b6-aa26-4d95-9920-0b695e899e53)

Is that supposed to be the new recipe now? seems kinda wild if so lmao

2023-11-07 20:26 UTC, CliffracerX commented
> oh actually i noticed the new table salt recipe (sodium + chlorine) wasn't working, so i checked the reagent search and it was this: ![5ilvWyR](https://user-images.githubusercontent.com/18170896/281173472-cd43f9b6-aa26-4d95-9920-0b695e899e53.png)
> 
> Is that supposed to be the new recipe now? seems kinda wild if so lmao

During my testing I found that Sodium + Chlorine still works, this seems to be a bug with the reaction search helper.

2023-11-08 03:10 UTC, SyncIt21 commented
> well i tested it and let the factory run for a while, seems to have no actual issues and works fine.

Yeeeaah!!! Thank you for your patience. If you want me yo undraft it just give the word

2023-11-08 03:12 UTC, MidoriWroth commented
yeah go ahead, seems fine now

2023-11-08 03:13 UTC, SyncIt21 commented
> oh actually i noticed the new table salt recipe (sodium + chlorine) wasn't working, so i checked the reagent search and it was this: ![5ilvWyR](https://user-images.githubusercontent.com/18170896/281173472-cd43f9b6-aa26-4d95-9920-0b695e899e53.png)
> 
> Is that supposed to be the new recipe now? seems kinda wild if so lmao

- #79499 

Did change some values. That or some other PR but not mine

2023-11-08 03:14 UTC, SyncIt21 commented
Anyway if you want to test some more go ahead or if you me to draft just let me know.

2023-11-08 03:15 UTC, SyncIt21 commented
> yeah go ahead, seems fine now

Yup time to undraft

2023-11-08 20:21 UTC, Jacquerel requested changes

2023-11-08 20:21 UTC, Jacquerel commented on code/modules/plumbing/plumbers/reaction_chamber.dm
> +			return
```suggestion
					return TRUE
			return FALSE
```
If this is your intention then we should make it clear.

2023-11-08 20:21 UTC, Jacquerel commented on code/modules/plumbing/plumbers/reaction_chamber.dm
> +			return
Same in both following cases.

2023-11-08 20:34 UTC, GPeckman commented
I unironically think that it would be best to store reagent volume as an integer in the code (e.g. 1u to a player is stored as 100 internally, 0.01u is just 1) and avoid floating point nonsense altogether. Material code in protolathes and such already does this, and as far as I know there hasn't been any issues like this there.

2023-11-09 03:51 UTC, SyncIt21 commented
> I unironically think that it would be best to store reagent volume as an integer in the code (e.g. 1u to a player is stored as 100 internally, 0.01u is just 1) and avoid floating point nonsense altogether. Material code in protolathes and such already does this, and as far as I know there hasn't been any issues like this there.

That was my first thought however a lot of stuff in-game trickle in very small fractional values over time and if we round them to whole numbers then their effect can dissapear especially when they are very close to the target.

I don't want to take that risk so we'll see how far this goes. Material lathes and stuff don't have this problem because literally everything costs well about 1 unit however when chems react we can't round of that precision else we risk losing data so let's see where this takes us.

2023-11-09 14:45 UTC, merged