Emergency hotfix for engi crossbow [NO GBP]
tgstation/tgstation pull request #79606
Opened 2023-11-08 22:10 UTC by KingkumaArt

Hadnt added these commits when the PR got merged due to not expecting it oops

## Why It's Good For The Game

See above, used to make my last pr actually function as intended.

## Changelog

:cl:
fix: fixed engi crossbow being able to be used onehanded + ability to craft with sci inducers
/:cl:

2023-11-08 22:10 UTC, Jacquerel commented
Please draft your PRs when you don't want them to be merged :p

2023-11-08 22:10 UTC, Jacquerel requested changes

2023-11-08 22:10 UTC, Jacquerel commented on code/datums/components/crafting/ranged_weapon.dm
> +	/obj/item/inducer/sci,
```suggestion
		/obj/item/inducer/sci,
```

2023-11-08 22:12 UTC, KingkumaArt commented
> Please draft your PRs when you don't want them to be merged :p

Sorry I didnt think it could be merged as I hadnt heard back from melbert

2023-11-10 00:17 UTC, deathrobotpunch commented
also the xbow and it’s ammo isn’t craftable as far as I know (checked code and crafting menu)

2023-11-10 01:30 UTC, KingkumaArt commented
> also the xbow and it’s ammo isn’t craftable as far as I know (checked code and crafting menu)

yeah ive noticed this, and im thinking its a merge weirdness thing

2023-11-10 14:08 UTC, Ghommie approved these changes

2023-11-10 14:08 UTC, merged