Flips the supermatter filters on Birdshot to have them work like other maps.
tgstation/tgstation pull request #79669
Opened 2023-11-11 17:36 UTC by CRITAWAKETS

## About The Pull Request

![image](https://github.com/tgstation/tgstation/assets/13697285/4d32f467-c417-4600-bdbb-96ff94569889)

This PR flips the ~~bird~~ filters on the Birdshot Supermatter engine. Now they work like other maps, where the filtered gas is the one that says in the engine, rather than getting filtered out.

## Why It's Good For The Game

Currently like half the rounds on Birdshot (I actually wonder if I'm even hyperbolic or if its not actually lowballing it) happen to have a supermatter delamination early into the round because the design has a critical part that's so different to other maps.

I didn't make an inverse filter by default since it makes the maps a bit more consistent, but more importantly, makes bad-faith players intentionally sabotaging the supermatter way, way more obvious.

## Changelog
:cl:
qol: The supermatter filters have been flipped on BirdshotStation to work like the supermatters on every round, meaning the filtered gas goes in, and the non-filtered gas comes out.
/:cl:

2023-11-11 23:47 UTC, YakumoChen commented
Soul removal

As the original supermatter map (when Our Lord still reigned), terrible cooling design and delamination wasn't just inevitable and tradition, it was a way of life

2023-11-12 01:53 UTC, GuillaumePrata commented
This is not just a good QoL, it removes noob traps from the game and the SM already is the king of spookying new players out of the department.
It should be a design goal to make the SM being completely harmless and simple to an experienced player and an eldrith horror for new players.

I would just use this opportunity to take this one step further and remove the triple filters, it confuses new players for no reason since the change to make them filter multiple gases at once.

2023-11-12 08:31 UTC, MrMelbert approved these changes
I asked for them to do this in the original Birdboat PR and they never did.

Anyways this is good so new players stop blowing up the engine

2023-11-15 02:11 UTC, Maurukas requested changes
Cyan pipes are looping into a bit mess here:
![image](https://github.com/tgstation/tgstation/assets/66576896/789296f9-a33e-4159-b941-21e52995cc7f)

2023-11-15 12:44 UTC, CRITAWAKETS commented
![image](https://github.com/tgstation/tgstation/assets/13697285/08d26f3c-c133-4226-9af1-52944ef4a29a)
fixed by changing the pipes leading to the internal area to pink, which isn't the best but might also end up being a small lesson to new players on pipe colors.

2023-11-16 00:41 UTC, Maurukas approved these changes
That works fine. Other than the distro and waste loops there are no formal conventions for what color pipe has to be used for what purpose

2023-11-16 00:41 UTC, merged