loopable looms
tgstation/tgstation pull request #79680
Opened 2023-11-12 04:24 UTC by jjpark-kb

## About The Pull Request
makes the looms `loom_me` proc loop for stackable items (such as cotton).

## Why It's Good For The Game
its a looping do_after, which is satisfying (and you don't need to click as much).

## Changelog

:cl:
qol: looms will now attempt to loop through stackable items (cotton as an example)
/:cl:

2023-11-12 05:39 UTC, ninjanomnom requested changes

2023-11-12 05:39 UTC, ninjanomnom commented on code/datums/elements/loomable.dm
> +			if(!do_after(user, loom_time, target))
Put this first in the loop and remove the do_after at the start of the proc

2023-11-14 01:01 UTC, san7890 requested changes

2023-11-14 01:01 UTC, san7890 commented on code/datums/elements/loomable.dm
> +	if(!spawning_amount)
```suggestion
	if(spawning_amount == 0)
```

we reserve `!` and its use to booleans, so would rather you hard match to `== 0` here instead as `spawning_amount` is an integer.

2023-11-14 20:57 UTC, merged