Fixes baseturf helpers
tgstation/tgstation pull request #79697
Opened 2023-11-13 01:22 UTC by jlsnow301

## About The Pull Request
Baseturf helpers do this:
![image](https://github.com/tgstation/tgstation/assets/42397676/f73887cc-10b1-4b24-b123-dc99c02ad45a)

And they also do this (up to 3x):
![Screenshot 2023-11-12 164334](https://github.com/tgstation/tgstation/assets/42397676/ac555d9a-785b-4e02-b85d-e90ded3b08ad)

When trying to debug `PlaceOnBottom` I couldn't help but notice it's trying to encompass use cases that simply aren't used anywhere. YAGNI - this makes it much more complex than it needs to be. 

## Why It's Good For The Game
Fixes weird baseturf handling
Fixes #41147
FIxes #79172

## Changelog

N/A nothing player facing

2023-11-13 01:28 UTC, jlsnow301 commented
This solution just seems to deceptively simple that I feel I'm overlooking things, reviews are welcome here

2023-11-13 08:15 UTC, Mothblocks requested changes

2023-11-13 08:15 UTC, Mothblocks commented on code/game/turfs/baseturfs.dm
> +	)
Inline the list instead

2023-11-13 14:23 UTC, Singul0 commented
god bless you 🙏  I can start working on my syndicate waystation assault map again

2023-11-14 03:09 UTC, san7890 commented
the unit test didn't break so i'll trust this works

2023-11-14 03:09 UTC, merged