Codifies male goats not having an udder
tgstation/tgstation pull request #79722
Opened 2023-11-14 03:07 UTC by san7890

## About The Pull Request

This was addressed in #78759 (1b1fde4908826ef5c54ffc0734e74028270af3fd) and reviewed (and merged even though I didn't respond to it, oh well), but I half-assed it because the whole point was to prevent male goats from having an udder, but I only added it to the subtype of Pete i made in that PR. Let's expand that to all male goats now.

## Why It's Good For The Game

It doesn't make biological nor morphological sense as to why a male goat can provide milk. Ideally this should be like this for all animals (because that's real life) but that's a later issue with further balance implication. 

I think it's still an interesting idea that Nanotrasen will just send you any old goat despite it being "useless" beyond being very good at eating plants. Maybe cargo should have a way to guarantee getting a female goat? It's just like real life where zoos and farms have to constantly dealw ith female animals (such as giraffes or other exotic stuff) tending to be far rarer/cost far more than their male variants due to the potential to generate offspring (there's more nuance to husbandry than this but just play along)... and in space, every animal is "exotic".

It still remains possible to biogenerate milk, which tends to be far faster than feeding/milking goats- which is something that the cook should have access to anyways.

## Changelog

:cl:
balance: Male Goats should no longer spawn with an udder, instead of it just being Pete.
/:cl:

2023-11-14 03:46 UTC, carshalash commented
![image](https://github.com/tgstation/tgstation/assets/16896032/da975a05-a344-4f61-8ff1-0b53d7f79e9b)

2023-11-14 03:47 UTC, san7890 commented
stop smearing vaseline on your photos

2023-11-14 03:47 UTC, carshalash commented
> stop smearing vaseline on your photos

It's better this way.

2023-11-14 03:54 UTC, Ghommie commented
father of lies... goat milk in disguise...

2023-11-14 04:01 UTC, Ghommie requested changes

2023-11-14 04:01 UTC, Ghommie commented on code/modules/mob/living/basic/farm_animals/goat/goat_subtypes.dm
> +	gender = FEMALE
```suggestion
/mob/living/basic/goat/pete/add_udder()
	if(gender == MALE)
		return //no thank you
	return ..()

/mob/living/basic/goat/pete/petricia // A female Pete!
	name = "Petricia"
	gender = FEMALE
```

2023-11-14 04:28 UTC, EricZilla commented
Pete is just transfem you absolute buffoons

2023-11-14 04:32 UTC, optimumtact commented
Remove whatever petricia is, pete is a reference to a specific person.

2023-11-14 04:33 UTC, san7890 commented
> Remove whatever petricia is, pete is a reference to a specific person.

okay

2023-11-14 05:47 UTC, Time-Green commented
Make Pete a woman then I want GOAT MILK

2023-11-14 06:21 UTC, san7890 commented
buy a goat from cargo. i also hear there's a popular game show that will give you a goat behind two of three doors

2023-11-14 07:02 UTC, Jacquerel commented
ill be honest im still vaguely fond of being able to milk male goats (and specifically this being pete's job) as an ss13-ism which i prefer to realism, but not enough that i want to block this
soul removal 😔

2023-11-14 08:13 UTC, san7890 commented
Pete's job is to eat kudzu and be a burger i fear- I've always used the biogenerator for milk after kicking his shit in

2023-11-14 13:42 UTC, Fikou commented
its 2550 bro we genetically modified male goats to produce milk

2023-11-14 13:45 UTC, kawoppi commented
if Pete doesn't have an udder then what have i been making cheese with?

2023-11-14 14:23 UTC, HoodMilk commented
They're space goats they all make milk.

2023-11-14 19:58 UTC, Loafin34 commented
this makes pete sad.... at least add breeding components with other goats by using grass or something

2023-11-15 03:36 UTC, Namwty commented
☝️ 🤓 Akchually, if we being completely correct, same as humans, animal would need to go trough pregnancy to produce milk!

Which means even female ( _shudders_) goats wouldn't just produce milk randomly, they would need PETE or something like that along with em! Explain that non-magic  biological nor morphological sense realism enjoyer.

Just repalce all cargo goats with Pete clones, in 2550 all goats were replaced with Pete's clones, rest... exterminated.

2023-11-15 10:00 UTC, githubuser4141 commented
> ☝️ 🤓 Akchually, if we being completely correct, same as humans, animal would need to go trough pregnancy to produce milk!
> 
> Which means even female ( _shudders_) goats wouldn't just produce milk randomly, they would need PETE or something like that along with em! Explain that non-magic biological nor morphological sense realism enjoyer.
> 
> Just repalce all cargo goats with Pete clones, in 2550 all goats were replaced with Pete's clones, rest... exterminated.

It's completely possible barring genetic or chemical modification (it's FIVE HUNDRED years in the future ffs) that all cattle that are on or can be shipped to the station have already been impregnated and given birth because that's like 1000% more convenient? It's kind of like how shop milk comes pre-cooked and gas station gas comes pre-refined.

2023-11-15 10:06 UTC, Time-Green commented
Pete could also just be trans

2023-11-15 20:58 UTC, merged