New closets
tgstation/tgstation pull request #79774
Opened 2023-11-16 18:08 UTC by MTandi

![image](https://github.com/tgstation/tgstation/assets/3625094/3d5517f0-db04-4475-a139-4a6dbc4a0327)

![image](https://github.com/tgstation/tgstation/assets/3625094/28e7ef2e-4b25-493c-8f2f-c7ebc240cff7)

## About The Pull Request

Resprites the existing closets and adds new ones.

TODO:

- [ ] Resprite cabinets
- [ ] Split wardrobe cabinets into unique closets
- [ ] Add new sprites for some closets that use generic style as a fallback
- [ ] Update the cursed closets and fridges for the new dimensions

## Why It's Good For The Game

Making them in the same style as the crates.

## Changelog

:cl:
image: New locker sprites
image: Added new lockers
/:cl:

2023-11-16 18:15 UTC, CoiledLamb commented
what's up with the doors not matching the lockers? it's a weird design choice once, but like, i'm seeing it 6-7 times

2023-11-16 18:22 UTC, mc-oofert commented
i think lockers should remain as tall as they were prior but thats your choice so

2023-11-16 18:23 UTC, MTandi commented
> what's up with the doors not matching the lockers? it's a weird design choice once, but like, i'm seeing it 6-7 times

Made the heads` lockers have the black base with golden hooks, and biosuit lockers to be in a similar style, while not looking like some department lockers. Please suggest how I can improve this if you think it looks weird.

2023-11-16 18:27 UTC, MTandi commented
> i think lockers should remain as tall as they were prior but thats your choice so

Will consider lowering them a couple pixels down.

2023-11-16 18:29 UTC, Mothblocks requested changes
I really like the small height difference

2023-11-16 18:29 UTC, Mothblocks commented on code/game/objects/structures/crates_lockers/closets.dm
> +		. += emissive_appearance(icon, icon_broken, src, alpha = src.alpha)
```suggestion
		. += mutable_appearance(icon, icon_broken, alpha = alpha)
		. += emissive_appearance(icon, icon_broken, src, alpha = alpha)
```

2023-11-16 18:40 UTC, Acantharctia commented
Looks amazing, but the engineering lockers lacking a door will look the same like the example above it?

2023-11-16 18:42 UTC, Acantharctia commented
> Looks amazing, but the engineering lockers lacking a door will look the same like the example above it?

And what's up with the security lockers. I like the green design you've added, but unsure of their purpose.

2023-11-16 19:23 UTC, MTandi commented
> Looks amazing, but the engineering lockers lacking a door will look the same like the example above it?

It's just me being lazy copying the doors for the preview, please ignore.

>And what's up with the security lockers. I like the green design you've added, but unsure of their purpose.

It's the armory lockers. Right now they all have the same style, as a red security locker.

I want to change their style into a military one, like that crate that I have added. And also add icons to differentiate them in the armory by glance.

![image](https://github.com/tgstation/tgstation/assets/3625094/ae1e8976-b7de-4528-a522-2f57a41363de)

2023-11-16 20:48 UTC, iwishforducks commented
I think they look too shiny here. The shine on the crates was fine since the crates had so much depth, but it kinda looks a bit overbearing on the much more shallow lockers. It would be annoying to have to give new colors for these though so I understand why.

I don't like that they're taller than a tile but /shrug - that's just a personal thing

2023-11-16 21:04 UTC, SimplySmiley123 commented
Honestly, liking these.
A bit better looking while not overly complicated and still recognisable at a glance.

2023-11-16 21:42 UTC, YakumoChen commented
Really great

Only curiosity is why the tool storage lockers have locks on them now?

2023-11-16 21:46 UTC, YakumoChen commented
Also the HoP locker looks slightly out of place as the only non-captain head locker without the black and gold base

2023-11-16 21:49 UTC, SomeoneYouProbablyKnow commented
Reminds me of the cursed unity station lockers. But these are not nearly as big.

They look nice, although mixing up doors and frames makes em look kinda funky. The contrast is a bit harsh. Donno what's to be done about that.

One more thing. Basic grey locker and safe grey locker look too similar from far away now that you added top grilles both. Maybe they'll look more distinct with the light but more readability is always good.

2023-11-16 22:13 UTC, DATA-xPUNGED commented
i like how they're bigger actually, it was one lf the major positives of Viro's for me

2023-11-16 22:41 UTC, YakumoChen commented
Other minor nitpicks:
I know S is for science. But I think it would be better to keep the R on Research lockers for absolute clarity (colourblindless and whatnot)

Same with the cargo lockers, since captain uses C
QM should maybe have a Q instead of a C and use the Head base as well?

2023-11-16 22:53 UTC, DaydreamIQ commented
These look amazing, though the shotgun one is a little hard to get at a glance. Is it supposed to be a shell with a pile of gunpowder next to it? Might just be a me issue there though.

2023-11-16 22:57 UTC, EEASAS commented
they look very nice, i just request a slight change
re-add the tiny pickaxe on the shaft miner's locker

2023-11-16 23:04 UTC, MTandi commented
Made them 2 pixels lower, changed the colors.

![dreamseeker_4S2bLx4Ytk](https://github.com/tgstation/tgstation/assets/3625094/b974bd5f-9d60-418e-a598-e2a23710d66a)

2023-11-16 23:15 UTC, MTandi commented
> Only curiosity is why the tool storage lockers have locks on them now?

Mistake, fixed.

>One more thing. Basic grey locker and safe grey locker look too similar from far away now that you added top grilles both. Maybe they'll look more distinct with the light but more readability is always good.

Changed.

>These look amazing, though the shotgun one is a little hard to get at a glance. Is it supposed to be a shell with a pile of gunpowder next to it? Might just be a me issue there though.

Yes, a pile of rubber balls though.

>re-add the tiny pickaxe on the shaft miner's locker

I want them to be consistent. Unfortunately, the ID icons are too big to be used on all lockers. Will consider.

2023-11-16 23:57 UTC, SinfulBliss commented
Why are they bigger than one tile?

2023-11-17 03:11 UTC, excalisword commented
Honestly, I am just glad that these don't have the weird shading that Viro's lockers had. Though I still think their shading is a little weird given how the door is darker than the top of the locker itself.

2023-11-17 05:44 UTC, Draggeru commented
Compared to the last locker PR these pass the Drag vibe check in terms of accessibility.

The little dots on the lockers with darker colors are a little hard to see, but thats just a me problem and I'm not necessarily the one being peddled to.

I like the lockers with the differently colored doors, it adds a layer of visual depth and helps me visually differentiate where the door starts and ends on the sprite.

2023-11-17 10:25 UTC, jughu commented
i wish we kept the hud icons for the lockers instead the first letter of the job

2023-11-17 10:32 UTC, SomeoneYouProbablyKnow commented
> i wish we kept the hud icons for the lockers instead the first letter of the job

Yeah. Some of em still have that. But the problem is we have more lockers than jobs. A lot of these use pictographs and that's very cool.

Biggest outliers are security but this change makes a good frame (🥁 ) work for anyone who'd want to change that.

2023-11-17 10:33 UTC, OrionTheFox commented
![image](https://github.com/tgstation/tgstation/assets/76465278/34171b57-2322-4546-9b82-bd15e212d46a)
Is the Syndie locker meant to be so tall

2023-11-17 11:02 UTC, MTandi commented
>Is the Syndie locker meant to be so tall Or is that image just outdated

Already fixed

2023-11-18 00:01 UTC, MTandi commented
New cabinet 

![image](https://github.com/tgstation/tgstation/assets/3625094/0c2a802e-09b5-40f6-b62a-1c0273d2d28c)

2023-11-18 19:16 UTC, Wallemations commented
Can we see how the wardrobes look? The lockers with all the same-colored clothes
You only posted the door, so is the door the only different part of them?

2023-11-18 20:09 UTC, atlasle commented
> New cabinet and guncase
> 
> 
> 
> ![image](https://github.com/tgstation/tgstation/assets/3625094/0c2a802e-09b5-40f6-b62a-1c0273d2d28c)
> 
> 
> 
> ![image](https://github.com/tgstation/tgstation/assets/3625094/6b45cf1a-94a0-4e23-b090-aecbf8362335)
> 
> 
> 
> 

that cabinet is absolutely wonderful, you need to remake the dresser in the same style

2023-11-18 21:54 UTC, MTandi commented
> Can we see how the wardrobes look? The lockers with all the same-colored clothes You only posted the door, so is the door the only different part of them?

Yes, they use the base gray frame, similar to the bio lockers. Only the lasertag use the rack base with bars inside, as in the armory lockers.

2023-11-19 02:18 UTC, Wallemations commented
> > Can we see how the wardrobes look? The lockers with all the same-colored clothes You only posted the door, so is the door the only different part of them?
> 
> Yes, they use the base gray frame, similar to the bio lockers. Only the lasertag use the rack base with bars inside, as in the armory lockers.

Can you show one/two of those?
Could just be an edit or in-game, I don't care which, just wanna see how it looks.

2023-11-19 02:41 UTC, DAKKA-WAAAGH commented
Damn, these sprites are top-notch! Merge ASAP

2023-11-19 09:19 UTC, Sheits commented
yum yum yum yum

2023-11-19 11:18 UTC, MTandi commented
> Can you show one/two of those? Could just be an edit or in-game, I don't care which, just wanna see how it looks.

![image](https://github.com/tgstation/tgstation/assets/3625094/b0bae07f-0c9d-4397-a826-a24eb5146423)

2023-11-19 14:56 UTC, Wallemations commented
Why are there scanlines on some of the icons on the doors?

2023-11-19 15:35 UTC, MTandi commented
> Why are there scanlines on some of the icons on the doors?

I liked how it looks on ID cards and thought that it would be nice style for white icons. Do you want me to make them flat white?

2023-11-19 19:27 UTC, Wallemations commented
The reason they were there on the ID cards is because those are tiny little screens right?

I don't think it makes sense on the lockers. Flat would be better imo

2023-11-19 22:48 UTC, MTandi commented
> The reason they were there on the ID cards is because those are tiny little screens right?
> 
> I don't think it makes sense on the lockers. Flat would be better imo

I'm not sure about the reasoning on IDs, I just thought that it would make it look like some kind of 3D objects on top of the door with a texture. Sure, I'll make them flat.

2023-11-20 13:42 UTC, Fikou commented
maybe make the normal colored wardrobes still have an icon? like the W or like a t shirt or smth

2023-11-20 17:33 UTC, MTandi commented
> maybe make the normal colored wardrobes still have an icon? like the W or like a t shirt or smth

They are used not only for clothing.

2023-11-20 18:07 UTC, Wallemations commented
> > maybe make the normal colored wardrobes still have an icon? like the W or like a t shirt or smth
> 
> 
> 
> They are used not only for clothing.

Either way they are still rather bare, and my own main concern with that is the grey one specifically, as it looks pretty much 1:1 with the normal locker.

2023-11-20 18:22 UTC, MTandi commented
Well they are bare by design. I can remove the gray locker and replace it with the generic one, but that will require path updates. Please suggest the solution.

2023-11-21 04:51 UTC, merged