Removes heretic ascension
tgstation/tgstation pull request #79788
Opened 2023-11-17 08:46 UTC by Jacquerel

## About The Pull Request

Sorry San the pan wasn't enough, Xemo is going to have to make a git account for something else.

This PR is pretty simple in concept: It removes the ascension end goal from Heretics. 
The main sad thing about this is obviously that ascensions are very cool. I largely haven't removed the _content_ of the ascensions, they're just inaccessible to players. Not sure what avenues they could possibly return in, but I guess for now at least admins will still have them in their back pocket?

But why would I do this anyway?

## Why It's Good For The Game

Last night some of the head admins and maintainers were chatting about how antagonists are right now and there was a sort of collective dissatisfaction about some elements at play (although the exact same interpretation was not shared by everyone).

Heretics are the biggest offender, although there's also some problems with Traitors.
The basic problem is multifaceted, but essentially the way I see antagonists is that we have sort of three main types.

Traitor, Changeling, and the more recent newcomer Heretic are the "common" antagonist types which we end up creating some combination of in basically every round and often come in multiples.
Nightmares, Obsessed, and maybe Ninja are weird nusiances who are rarely the main focus but add some spice (we should add more of these).
Wizard, Revolution, Nuke Ops, Space Dragons, Xenos, Spiders, Blob, Cult, etc are big events which can carry a round (apart from Space Dragon they might have been their own gamemode when we had those).

Ultimately I have come to the conclusion that I think anything in this first category _shouldn't_ come equipped with some kind of button it can work towards to instantly end the round.
I think that the effect of this on player behaviour (both antagonists and crew) has been negative as players tunnel-vision towards the big prize we dangled in front of them rather than exercising creativity in what they want to do in a round, and the crew become conditioned to the fact that they _must_ annihilate every antagonist they meet because if they give them any amount of slack they'll come back as a living storm or station-consuming worm or some such.

This doesn't mean that traitors and heretics and changelings _shouldn't_ be ending rounds (obviously we want rounds to end and these roles are the main vehicle) but I'd rather they like... did that themselves rather than following a script we wrote for them. 

So in short:
- They pigeonhole Heretics into largely only doing one thing (ascending or failing to do so).
- After removing them it is no longer the case that any Heretic you don't completely remove from the round will eventually become a virtually unstoppable round-ending event.
- They don't really present an exciting interactive event, they're jut a victory lap for one guy.

This is not the _only_ Heretic change I would like to make and I think the role has other problems going on which sort of limit the amount of creativity you can leverage from it, but this is the easiest change I can make _right now_. The rest are going to require me to do some thinking and write up a design document and who has time for that?

What will you do as a Heretic after losing the ability to become a spooky monster?
Answer: whatever you want. You're free now. Pursue a grudge with a specific player, cover the whole station with rust, use your powers to troll people (they need more utility powers which can enable this), take on the station in a way which _doesn't_ require them to toss TTVs at you... use your imagination.

If you do not like this change and are worried about how I invoked the spectre of a shadowy cabal of powerful individuals who agree with me: don't worry this change is still just one I am making because I personally think it's a good idea and there's no guarantee it will be merged.

## Changelog

:cl:
balance: Heretics can no longer ascend, and will have to figure out for themselves how they want to end the round.
/:cl:

2023-11-17 08:48 UTC, mc-oofert commented
arent heretics also just virtually unstoppable before they get to the point of ascension with the amount of shit they unlock

2023-11-17 08:50 UTC, necromanceranne commented
Maybe we can balance heretics a bit in light of the ascension no longer being around. Thank fuck, early heretic is a drag till you get some knowledge

2023-11-17 08:50 UTC, Jacquerel commented
> arent heretics also just virtually unstoppable before they get to the point of ascension with the amount of shit they unlock

They can be yeah. They're perfectly capable of ending the round _without_ turning into a big worm.

2023-11-17 08:51 UTC, Draggeru commented
I feel like it would be better to disable heretic until the antagonist can be reworked, this nerfs heretic to be a magic traitor and it makes the antagonist overall just less engaging. Why bother being a heretic if you don't have an end goal? Even if security catches you on good faith its very likely you're just going to get the axe anyways because dynamic perpetuates a high stress cycle that encourages security to remove one threat so they can deal with another.

2023-11-17 08:52 UTC, Jacquerel commented
> I feel like it would be better to disable heretic until the antagonist can be reworked, this nerfs heretic to be a magic traitor and it makes the antagonist overall just less engaging. Why bother being a heretic if you don't have an end goal? Even if security catches you on good faith its very likely you're just going to get the axe anyways because dynamic perpetuates a high stress cycle that encourages security to remove one threat so they can deal with another.

Why bother to be a traitor or changeling if you don't have an end goal? You're a spooky wizard, use your powers to fuck with people. If you don't want to, then turn it off.
I ultimately think that we _shouldn't_ be giving commonly spawned antagonists specific end goals. Deciding what your goal is should be _your_ job.

2023-11-17 08:53 UTC, necromanceranne commented
Heretic is just fine without the ascension, just a bit clunky. I don't think we need to disable them before a rework

2023-11-17 08:55 UTC, Draggeru commented
> > I feel like it would be better to disable heretic until the antagonist can be reworked, this nerfs heretic to be a magic traitor and it makes the antagonist overall just less engaging. Why bother being a heretic if you don't have an end goal? Even if security catches you on good faith its very likely you're just going to get the axe anyways because dynamic perpetuates a high stress cycle that encourages security to remove one threat so they can deal with another.
> 
> Why bother to be a traitor or changeling if you don't have an end goal? You're a spooky wizard, use your powers to fuck with people. If you don't want to, then turn it off. I ultimately think that we _shouldn't_ be giving commonly spawned antagonists specific end goals. Deciding what your goal is should be _your_ job.

Then remove progtot final objectives. The same argument could be made there, and an end goal is helpful to guide the players who aren't gimmick machines or the players who just want to do their anticipated end goal.

The only place this argument works is for changling, but changlings end up being murderbone machines when they're caught anyways because the response to deal with a changeling is to cremate them,

2023-11-17 08:56 UTC, Jacquerel commented
> > > I feel like it would be better to disable heretic until the antagonist can be reworked, this nerfs heretic to be a magic traitor and it makes the antagonist overall just less engaging. Why bother being a heretic if you don't have an end goal? Even if security catches you on good faith its very likely you're just going to get the axe anyways because dynamic perpetuates a high stress cycle that encourages security to remove one threat so they can deal with another.
> > 
> > 
> > Why bother to be a traitor or changeling if you don't have an end goal? You're a spooky wizard, use your powers to fuck with people. If you don't want to, then turn it off. I ultimately think that we _shouldn't_ be giving commonly spawned antagonists specific end goals. Deciding what your goal is should be _your_ job.
> 
> Then remove progtot final objectives. 

Yeah you're going to like my next PR.

2023-11-17 09:05 UTC, AtomTheProphet commented
Maybe we could get something to raise the amount of knowledge points one could reasonably get if we can no longer ascend?

2023-11-17 09:08 UTC, Rex9001 commented
I think traitor final objectives are much more egregious in this aspect, this really to me fucks with the entire flavour of heretic and ruins the build up of every path. You would have to rewrite all the flavour texts since they are all building up to this cool moment were you accomplish the goal you have been aiming for with every path. I strongly dislike removing the round ending aspect of the heretic and I instead think we should be looking towards traitor to find a way easier antagonist that more frequently ends rounds (at least in my experience). Heretics are made with this cool endgame in mind and ultimately I think its good that they have it, if anything you could nerf the ascensions and not just remove them. If heretic is in such a dire state a rework would be better than this which is just ripping the heart out from them.

2023-11-17 09:13 UTC, SimplySmiley123 commented
> > I feel like it would be better to disable heretic until the antagonist can be reworked, this nerfs heretic to be a magic traitor and it makes the antagonist overall just less engaging. Why bother being a heretic if you don't have an end goal? Even if security catches you on good faith its very likely you're just going to get the axe anyways because dynamic perpetuates a high stress cycle that encourages security to remove one threat so they can deal with another.
> 
> Why bother to be a traitor or changeling if you don't have an end goal? You're a spooky wizard, use your powers to fuck with people. If you don't want to, then turn it off. I ultimately think that we _shouldn't_ be giving commonly spawned antagonists specific end goals. Deciding what your goal is should be _your_ job.

Problem is, this is TG, no matter what you do you ain't removing the player behavior from this server.
Players here _will_ go for most chaotic option every single time, even if you start chipping away at it they'll find different ways to fuck over the round.

Also, as a side note, if you really want to start chipping away at round ending threats, start with traitors, not heretics.
Traitors are _way_ more common and reach their final objectives _way_ faster then Heretics. Plus a lot of Heretic stuff does build up for the Ascension, from flavor texts to paths and their abilities themselves. Plus, traitors weren't designed with the round ending goals in mind initially and had it hamfisted into 'em for sake of progtot.

2023-11-17 09:22 UTC, SimplySmiley123 commented
> arent heretics also just virtually unstoppable before they get to the point of ascension with the amount of shit they unlock

Not really. Up until ascension all it takes is one baton to murder you as anything but the Blade path pretty much.
And honestly for most of the paths lategame abilities just, aren't used whatsoever outside of using them for hell of it, you unlock 'em too late for 'em to matter. All you really need to do well as heretic is mansus grasp, your blade, and security gear once your identity goes public, everything else bar stuff that upgrades your grasp and blade, and the ascension, feel like fluff added for sake of progression.

2023-11-17 09:43 UTC, lizardqueenlexi commented
It's about time. An antagonist that centers itself on speedrunning objectives to become the Big Murderman is not, like. A good one. I look forward to new directions heretic can grow in when freed from its boring conclusion.

2023-11-17 09:51 UTC, Time-Green commented
What about the ascension achievements?

2023-11-17 09:53 UTC, Jacquerel commented
> What about the ascension achievements?

they will remain on the database but won't display in game

2023-11-17 09:57 UTC, Time-Green commented
> > What about the ascension achievements?
> 
> they will remain on the database but won't display in game

Then the achievement scoreboard is dead 😔

2023-11-17 10:07 UTC, zxaber commented
I can't really disagree with the PR, but I hate that we're losing the cool thematic conclusion for heretics.

Station-wide permanent ash storm is dumb, but perhaps ascensions could return with more of a focus on narrow-target effects and spells? Something like a path-themed wizard?

2023-11-17 10:10 UTC, Xackii commented
If the idea is to give the heretics creativity and choose what to do in round, then removing the ascension contradicts this opinion. I can decide for myself whether in this round I want to troll people, make a gimmick or just have fun, and the fact that I can ascend in no way prevents me from choosing, and the opportunity ascension only adds another option for how I can have a fun round (and ascend of a heretic is not so easy). With this PR, heretics will lose the uniqueness of their role and they will simply become a weak version of the Wizard who just runs around and kills everyone without any idea.

2023-11-17 10:19 UTC, Livrah commented
Oh boy, back to use heretic rolls as just grief/murderbone pass.
> I think anything in this first category shouldn't come equipped with some kind of button it can work towards to instantly end the round.
Are you talking about Prog Tot's final obj? Cos every single ascention but flesh is dying to a bomb/syringe.
Also 100% agree with the comment above.

2023-11-17 10:25 UTC, YakumoChen commented
Why not just like, scale back the ascensions super hard?

Have the big worm be on a timer and can't regenerate, have the rust storm just be a regular ability that doesn't destroy the whole station as much, the lock thing can just be an instant summon of one or two mobs, etc

2023-11-17 10:29 UTC, Livrah commented
> Why not just like, scale back the ascensions super hard?
> 
> Have the big worm be on a timer/cooldown and can't regenerate, have the rust storm just be a regular ability that doesn't destroy the whole station as much, the lock thing can just be an instant summon of one or two mobs, etc

Better solution for this "issue" will be to make the ascension into server config and turn it off on our special server.

2023-11-17 10:29 UTC, Jacquerel commented
> I can't really disagree with the PR, but I hate that we're losing the cool thematic conclusion for heretics.
> 
> Station-wide permanent ash storm is dumb, but perhaps ascensions could return with more of a focus on narrow-target effects and spells? Something like a path-themed wizard?

I dont like inherently hate the concept of having some final conclusive thing in principle but I dislike the results in practice, and suspect that even if it's weaker people are generally going to ignore anything else in favour of the mechanically incentivised power boost we put in front of them. 

Oh yeah in _theory_ anyone _can_ just ignore the ability to turn themselves into a huge worm it's just that because we have so many systems pointing them towards doing it, they probably aren't going to.
If we put a button on the traitor uplink which gave you a free revolver you would have the _choice_ not to press it but you would find that quickly traitors would become "the revolver antagonist".
This _still_ largely holds true if you replace "free" with "complete some small series of tasks". This is largely how mobile games in general function, or MMOs, or quite a lot of games designed largely to waste your time by putting a treadmill in front of gamers and dangling a carrot at the end. I don't think the treadmill is something we actually want to have.

(Does this sound like a critique of progression antagonists generally? That is because it is).

And I dislike the consequences that round-ending final outcomes have _now_ sufficiently that I'd rather snip that part off in advance rather than wait until there is a replacement. I don't think any replacement is an essential component, and if you wanted to wait for _my_ version of a heretic rework it probably wouldn't have one (if this incentivises someone else to do the work first, that's also a pro in my book).

2023-11-17 11:05 UTC, Fikou commented
I think heretic ascensions are important for the antag to guide players forward, heretic not having tools to use with the sandbox is a larger issue with heretic, not with ascensions, you aren't going to magically make heretics "fuck around and do fun stuff" just by removing an announcement and their final kit additions

> They pigeonhole Heretics into largely only doing one thing (ascending or failing to do so).

I think you're not improving this, heretics will still probably want to do their unchanged objectives which they previously had to do to ascend, the only difference is whether or not they get to finish their "story arc" and bring stuff to a conclusion, they are just gonna get abilities and continue getting abilities until they feel they have the proper kit to bone

> After removing them it is no longer the case that any Heretic you don't completely remove from the round will eventually become a virtually unstoppable round-ending event.

This is just a fact of a magic antag like heretic. Unless you use methods that could also work for an ascended heretic (like chem implants or something) They can just come back and murder all of sec, ascension or not. They also aren't virtually unstoppable (maybe ignoring the flesh one), since they are still carbons and can be worked around

> They don't really present an exciting interactive event, they're jut a victory lap for one guy.

I disagree, I think it's similar to stuff like plasma fires which are great for interaction between crew as everything goes to poopoo

2023-11-17 11:23 UTC, SomeoneYouProbablyKnow commented
> If the idea is to give the heretics creativity and choose what to do in round, then removing the ascension contradicts this opinion.

If this was true why would we ever need to design anything in the game? Maybe you're built different (t. you have way too many hours logged) but most players are not.

The problem is that heretic ascension is not a thematic crescendo for the round. It's one guy who ambushed 4 people half a station away going on a pretty slow rampage.

I wish ascensions were more like... idk late-round gamemode? Kidna like zombies final objective.

> Yeah you're going to like my next PR.

Whoops, Rip tator final objectives. Guess it's time to bring back romerol (at like 40 TC due to inflation)

But It would be nice to give heretic some of their ascension tools back in the form of lower power spells. Give ash their fire immunity and let flesh boys turn into centepedes on a big CD or something (yeah it's a lot of work but those are COOL)

2023-11-17 11:28 UTC, Jacquerel commented
> But It would be nice to give heretic some of their ascension tools back in the form of lower power spells. Give ash their fire immunity and let flesh boys turn into centepedes on a big CD or something (yeah it's a lot of work but those are COOL)

I think these are things we should definitely do (including making heretics _stronger_ at roundstart, shifting more of their power forwards because we don't need to worry about them exploding later so much) just I don't think they need to come at the same time as this change.

2023-11-17 11:42 UTC, Dorsisdwarf commented
I dont understand the people who say "traitors are way more common than heretics", like the vast majority of roundend reports i see have three or more heretics and the background gameplay of sec is constantly hunting signs of heretic activity because theyre incredibly dangerous, leave obvious signs of activity behind, and are in almost every round. Even if there are more actual traitors, the station is driven significantly more by heretic activity, especially as traitors tend to keep their noses down unless their gimmick is cuban pete / station coup.

Reworking heretics to be an always-potent less common antag that its a surprise to see instead of Magical Traitor seems like a good idea too I guess.

2023-11-17 11:46 UTC, SomeoneYouProbablyKnow commented
> Even if there are more actual traitors, the station is driven significantly more by heretic activity

Not the station. Security is driven by heretic activity, yes. The station as a whole sees more traitors precisely because security is busy kicking in the skulls of heretics who forgot to use gloves, and the heretics who avoid sec do so by killing everyone by ambushing them in maints.

2023-11-17 11:55 UTC, Samag5 commented
I have feeling that removing one major objective for heretics on lrp would lead to some people just doing murderbone, cuz they now have no idea what to do, not everyone doing gimmicks every round. We already have lings for murderbone, so I don't think that's good idea,

2023-11-17 12:03 UTC, plutori commented
Heavily disagree with this PR. The entire premise of progression traitor and heretic is that they're threats that are weak early but grow strong later, giving the station and regular crewmen the ability to set up and get prepared for issues. If you remove their grand finale, firstly, it will reinforce current issues on servers where people ignore antagonists (Basically, you will see an uptick in Bar-RP traitors, or rather, Bar-RP Heretics), because the crew will not feel urgency to have them dealt with, and secondly, you're massively screwing over Heretics by keeping it so they still have their weak early game, but now they don't even get the payoff in the end for dealing with that.

If this removal were coupled with a MASSIVE buff to Heretic early game, I still would be very upset and very unhappy by the change, but I would at least concede it was a more balanced change, but as it is, you're giving Heretic all the negatives of being a progression antagonist but removing the payoff.

Do not merge.

2023-11-17 12:04 UTC, SomeoneYouProbablyKnow commented
> I have feeling that removing one major objective for heretics on lrp would lead to some people just doing murderbone

As opposed to what? You get to ascension by muderboning and after you ascend your get is to murderbone more

2023-11-17 12:16 UTC, Angoryskaven commented
I feel like this PR is, in all honesty, not good, either for MRP or LRP: for LRP players, the Ascension is the final reward for their efforts, and, in lore(and for MRP players), the culmination of every despicable sacrifice and research done by the Heretic for their dark gods. 
Furthermore, Heretics, unlike Traitors (who can immediately buy some funny items like sleepy pens) or Changelings (which are an immediate danger), start off VERY weak, with the power level of a mildly dangerous tider. The Ascension, as I said before, is the reward for managing to avoid capture by security, and completing your objectives, or concluding your RP story in a proper way.

As for the gimmicks: Heretic had some, once, when Heretic potions were able to be drank by all crew, seeing as now any cauldron potion injects the non heretic with hurty water. If you want to give MRP players more options, give the Heretic new tools, DONT take existing things away. Hell, take a page out of Lifeweb, give the option to the Heretic to go for a more Thanati cult like experience: recruit people, make them drink weird water, turn them into minor heretics, perform weird rituals with the help of your new followers, start a turf war with the Narsian cultists or Revolutionaries as security tries to understand what is going on and why the robed crackheads are stabbing eachother in maints. Or just sell potions to the crew.

In short: add gimmick options for MRP players, whilst not taking away something that is fine as it is.

2023-11-17 12:21 UTC, Fikou requested changes
dont remove the achievements until we have a system to remove them from the db

2023-11-17 12:26 UTC, DAKKA-WAAAGH commented
I can't really disagree with any of these points because heretic has always felt off to me, and I would likely still not enjoy having them around even after your expected changes.

Of whatever choices you decide to make, please make them fit more into the game somehow.

2023-11-17 12:31 UTC, plutori commented
Also, what do you even expect Heretics to do now? Before, the whole idea was go after targets and sacrifice them so you could ascend. So people generally just stuck to killing their targets. Do you just want them to sacrifice a few targets for points to get strong and then run around murderboning everyone now? Or do you want them to Bar RP? Because without ascension they don't have any direction, really.

2023-11-17 12:44 UTC, GuillaumePrata commented
People commenting about Heretics, and traitors, not having a goal and just doing random boning are forgetting that progression antag is something quite new on the codebase.

We had more freedom with antags for years without any major issue (as far as I am aware) so the antag meta won't be ruined by removing the end goals, things will just slowly move back to how they were.

And by that, I mean that the antagonists and crew will interact in a healthy way, antagonists won't see the crew as a staircase they need to murder throw to get to the fun at the top, the crew won't treat every traitor and heretic with the same violence as a wizard.

Traitors and Heretics will go back to interacting with their job content more as you don't need to be "on the grind" all the time or lose the fun at the end of the staircase, you can just go back to your medbay job for half an hour if you want and then go back to being an antagonist any time you want, nice indirect buff for the stealth part of both antagonists.

But most importantly, they will interact with the coworkers/crew more, the treadmill gameplay we gave to heretics and traitors made them just leave their job behind 95% of the time, they had to if they want to win.
Now they can just vibe in peace at their department making the place feel lively, stealthy murder someone in the corner, come back and help the new player, etc.

2023-11-17 12:46 UTC, Jacquerel commented
> People commenting about Heretics, and traitors, not having a goal and just doing random boning are forgetting that progression antag is something quite new on the codebase.

The longer I am around the more I think that progression is best kept short and not as impactful as it is.
Traitors would actually be fine as-is with progression removed and this antagonist already exists in the game as midround traitor, you don't _need_ more than 20 TC.

Heretic needs more work to get to that condition, and this PR does not fix that. But if I am going to do anything about it, it's going to be atomically over time and not all at once.

2023-11-17 12:56 UTC, Samag5 commented
> > I have feeling that removing one major objective for heretics on lrp would lead to some people just doing murderbone
> 
> As opposed to what? You get to ascension by muderboning (or rather maint camping which is worse) and after you ascend your get is to murderbone on a very uneven playing field (which is eh) Actual murderbones are fun and good tho

Well, on Terry it works just like that: you almost always die trying to get an ascension if it's not a black orbit where there is a lot of other traitors that can cause a lot of deaths of your targets. I've rarely see any ascension on other orbits + high pop(On low pop every antag can kill lot's of people cuz even if you don't have any antag items you can still use game mechanics and it's unlikely that someone would validhunt you). Also heretic can be the reason of the murderbone, only at the end of the round, cause lasers + batons would be more powerful than him until his ascension. I see no problem with funny murderbone, but heretic can do it only if he ascend, wich is an extremely unlikely event in a standard round, so removing ascension cuz it's just murderbone thing is kinda weird, delete traitors final objectives then, lot's of them just round end.

2023-11-17 13:15 UTC, SimplySmiley123 commented
> And by that, I mean that the antagonists and crew will interact in a healthy way, antagonists won't see the crew as a staircase they need to murder throw to get to the fun at the top, the crew won't treat every traitor and heretic with the same violence as a wizard.
> 
> Traitors and Heretics will go back to interacting with their job content more as you don't need to be "on the grind" all the time or lose the fun at the end of the staircase, you can just go back to your medbay job for half an hour if you want and then go back to being an antagonist any time you want, nice indirect buff for the stealth part of both antagonists.
> 
> But most importantly, they will interact with the coworkers/crew more, the treadmill gameplay we gave to heretics and traitors made them just leave their job behind 95% of the time, they had to if they want to win. Now they can just vibe in peace at their department making the place feel lively, stealthy murder someone in the corner, come back and help the new player, etc.

I dunno what to tell you, but MRP isn't the majority on TG.
A lot of TG players will still see antag status as murderbone pass. They won't interact with their job unless it provides them with gear or whatever else helps them with their objectives _or_ with their murderbone. Removing finals and ascensions won't do shit against that.
And crew is still gonna be a roadblock, big or small, depends on the amount of players on the server pretty much, for traitors and heretics, no matter what you do, crew on TG will go after antagonists one way or another _unless_ you're on Manuel, and even then I seen validhunting happen on Manuel.

You can code bandaid solutions, but you can't get rid of TG in TG players.

2023-11-17 13:20 UTC, zoomachina commented
> People commenting about Heretics, and traitors, not having a goal and just doing random boning are forgetting that progression antag is something quite new on the codebase.
Heretics had ascensions from the moment they were added
> We had more freedom with antags for years without any major issue (as far as I am aware) so the antag meta won't be ruined by removing the end goals, things will just slowly move back to how they were.
For traitors maybe; but this pr removes a core part of heretics as antags
> And by that, I mean that the antagonists and crew will interact in a healthy way, antagonists won't see the crew as a staircase they need to murder throught to get to the fun at the top, the crew won't treat every traitor and heretic with the same violence as a wizard.
Removing ascension or final objectives won't stop traitors/heretics from being a deadly threat to the crew, because that's what being an antag means (and that's why antags is an interesting part of the game)
> Traitors and Heretics will go back to interacting with their job content more as you don't need to be "on the grind" all the time or lose the fun at the end of the staircase, you can just go back to your medbay job for half an hour if you want and then go back to being an antagonist any time you want, nice indirect buff for the stealth part of both antagonists.
Traitors and heretics already have that option, final objectives existing doesn't stop them from doing that
> But most importantly, they will interact with the coworkers/crew more, the treadmill gameplay we gave to heretics and traitors made them just leave their job behind 95% of the time, they had to if they want to win. Now they can just vibe in peace at their department making the place feel lively, stealthy murder someone in the corner, come back and help the new player, etc.
What you're saying is that there will be less conflict (less of the reason antags exist)

2023-11-17 13:30 UTC, GuillaumePrata commented
> Removing ascension or final objectives won't stop traitors/heretics from being a deadly threat to the crew...

Yes, that was never my point and I'm sure it is no one's goals.

> Traitors and heretics already have that option, the existence of final objectives doesn't stop them from doing that

They do not, if you don't grind, you lose the end goal.

> What you're saying is that there will be less conflict (less of the reason antags exist)

Yes, and I see that as a positive in this particular angle.
Antags are meant to move the round forward, but not all of them should be aiming to end the round.
Traitors still brought a lot of conflict before progtot was added, but it was healthier conflict IMO.

2023-11-17 13:30 UTC, SomeoneYouProbablyKnow commented
> I have feeling that removing one major objective for heretics on lrp would lead to some people just doing murderbone
> Well, on Terry it works just like that...
Yeah i know. You said "oh they'll just murderbone instead" like it's a bad thing so i pointed out that they already do that.

Murderboning isn't bad, but i personally would like them to be something people do boldly and in the open (also beheading culture can fuck off) not the maint crawling heretic to OP ascended heretic (or yes more likely dead heretic). That is the issue for me not the killing, antags be antags.

> delete traitors final objectives then, lot's of them just round end.

Heh, here's an quote from earlier in the conversation

> Then remove progtot final objectives. 
> > Yeah you're going to like my next PR.

> You can code bandaid solutions, but you can't get rid of TG in TG players.

I mean you can but that would require changes to core systems. Like drastically increasing TTK for instance. And if you can't TG out Player why's everyone so up in arms about this when Jacq already said that early heretic should be made stronger to complemsate and ascension like abilities should come back in a different form.

2023-11-17 13:36 UTC, Pepsilawn commented
> But most importantly, they will interact with the coworkers/crew more, the treadmill gameplay we gave to heretics and traitors made them just leave their job behind 95% of the time, they had to if they want to win. Now they can just vibe in peace at their department making the place feel lively, stealthy murder someone in the corner, come back and help the new player, etc.

That is absolutely not the case for heretics. A roundstart heretic is barely stronger than an average crew member and absolutely less than any active security team. You can get extremely lucky with your free essence spawn points but even then if there is more than just one heretic chances are you won't be grabbing more than 2-3 points.
Whilst traitors are encouraged to leave ASAP to rank up, an early game heretic has to work with what they have to reliable jump a sacrifice which depending on the job, they will be getting from the workplace.
I believe removing the end goal would actually have the reverse effect as people would have less motivation to do so.

2023-11-17 13:37 UTC, GuillaumePrata commented
> I dunno what to tell you, but MRP isn't the majority on TG.

If I wasn't lazy, I would post a print of one of the hundreds of times I have seen the headcoders say the TG codebase is meant to be MRP.
But that isn't even important to this conversation anyway, interacting with other players in a non murder way should not be a MRP thing.

> A lot of TG players will still see antag status as murderbone pass.

And that is all fine for me, if they want to go the murder way, have fun.
As long as we don't punish the players that want to take their antag round in another angle, like we do now by blocking a lot of the fun features behind ascension/final obj, all is fine.

2023-11-17 13:39 UTC, SomeoneYouProbablyKnow commented
> That is absolutely not the case for heretics. A roundstart heretic is barely stronger than an average crew member and absolutely less than any active security team.

I (Manus' strongest heretic) Cast Fireball (Singletank) at security officer (Sinner)

2023-11-17 13:40 UTC, GuillaumePrata commented
> That is absolutely not the case for heretics. A roundstart heretic is barely stronger than an average crew member

This was brought on the PR body already, I am sure most would agree that buffing roundstart Heretics would be beneficial, with or without this PR being merged.
They are literally a guy with only a knife and funny hand running around in maints until they ascend in 90% of the shifts.

2023-11-17 13:41 UTC, SomeoneYouProbablyKnow commented
> But that isn't even important to this conversation anyway, interacting with other players in a non murder way should not be a MRP thing.

Side-note : Interacting with other players in a murder wat should not be a LRP only thing.

2023-11-17 13:46 UTC, zoomachina commented
> Yes, that was never my point and I'm sure it is no one's goals.

so why does it matter whether heretics have the ascension or not? ascension or not, they can still end the round in a far less cool way
> They do not, if you don't grind, you lose the end goal.

why do they need it if they are doing their own thing? there's still non-ascension greentext if that's what you're concerned about, and the hard parts are pretty much doing all the things ascension wants you to, excluding the final ritual
> Yes, and I see that as a positive in this particular angle.
Antags are meant to move the round forward, but not all of them should be aiming to end the round.
Traitors still brought a lot of conflict before progtot was added, but it was healthier conflict IMO.

ok

2023-11-17 13:46 UTC, Fikou commented
i'm willing to put my foot down (unless the headcoders object)
I think the theming and a proper ending of a heretic path with unique stuff for the players to experience matters more than the antags not feeling rushed to compete with all of the station. 
if you want heretics to interact with the sandbox more then give them tools that interact with the sandbox, if players had lots of cool stuff to mess around with things that arent ascensions then they would, im not a big fan of prs that cripple a system for someone else to fix it later

2023-11-17 13:50 UTC, GPeckman commented
> This is not the only Heretic change I would like to make and I think the role has other problems going on which sort of limit the amount of creativity you can leverage from it, but this is the easiest change I can make right now. The rest are going to require me to do some thinking and write up a design document and who has time for that?

If you want to give heretics more sandbox tools, one easy thing to start with would be to remove the focus requirement that exists on most of their spells. Currently, it means that most spells can't even be used without wearing an item that screams "I'm valid."

2023-11-17 14:34 UTC, SimplySmiley123 commented
> > I have feeling that removing one major objective for heretics on lrp would lead to some people just doing murderbone
> 
> > Well, on Terry it works just like that...
> 
> Yeah i know. But "oh they'll just murderbone instead" is not a solid argument as they already do that. So i just pointed that out
> 
> Murderboning isn't bad, but i personally would like them to be something people do boldly and in the open (also beheading culture can fuck off) not the maint crawling heretic to OP ascended heretic (or yes more likely dead heretic). That is the issue for me not the killing, antags be antags.
> 
> > delete traitors final objectives then, lot's of them just round end.
> 
> Heh, here's an quote from earlier in the conversation
> 
> > Then remove progtot final objectives.
> > > Yeah you're going to like my next PR.
> 
> Fingers crossed for old romerol
> 
> > You can code bandaid solutions, but you can't get rid of TG in TG players.
> 
> I mean you can but that would require changes to core systems. Like drastically increasing TTK for instance. And if you can't TG out Player why's everyone so up in arms about this when Jacq already said that early heretic should be made stronger to complemsate and ascension like abilities should come back in a different form.
> 
> > I think these are things we should definitely do (including making heretics stronger at roundstart, shifting more of their power earlier because we don't need to worry about them exploding later so much, and spending less time as essentially a guy with a funny hand and a knife which often feels like about 50% of the round) just I don't think they need to come at the same time as this change.

Thing is that the removal doesn't help with the murderbone happening, it jsut makes it _bland_ murderbone.
That's the thing. It's still gonna be the same no matter what you do about the finals and ascensions.

And no, you really can't get rid of TG in a TG player.
If you change the core aspects, they'll find their way to achieve what they want anyway. Just LRP things my man.

2023-11-17 14:45 UTC, Redrover1760 commented
You should go the way of wizards and make spells usable but have longer cooldowns without a focus.

2023-11-17 14:48 UTC, Jacquerel commented
Just to be clear as I have seen this mentioned a couple of times; I don't _care_ if antagonists are killing people, to an extent that is why we put them in the game. 
What I find problematic about "final reward" types of progression are the effects it has on game flow.

When you put a big, impressive reward in front of a player then they will want to earn that reward and experience the satisfaction of completing a task, as well as the enjoyment of utilising the reward.
This means that they are much _more_ likely to do this at the detriment of doing anything else, but that's fine as long as the things we task them to do along the way still cause outcomes we want.

The problems come due to the _interpersonal_ and _psychological_ effects of creating such a skinner box design.

If the focus becomes achieving the reward rather than just playing the role playing game, the focus becomes doing that as efficiently as possible even if it is at the detriment of gameplay enjoyment on the way there.
Once _non-antagonists_ notice that any antagonist whom they leave alone will eventually summon a battlecruiser or create an infinite portal of mobs, they will start to wonder why they should do anything when encountering an antagonist but react as violently as possible.
In fact they will start to do this proactively, because they don't want _their_ plans to be spoiled by the sudden arrival of a Star Gazer.
In response to this, antagonists who _weren't_ focused on completing their objectives as efficiently as possible to achieve the final reward suddenly start to feel squeezed. They _need_ the additional power granted by efficiently performing tasks in order to cope wth increased scrutiny and aggression from the other players, so it has a chilling effect on people who wanted to do _anything else_ as well.

This is feedback I see from Security players _all the time_, that they have no time to do anything but deal with threats and do so as punitively as possible, because if they don't those threats will destroy the station. I don't think that pressure is good for the game.

If the outcome is that this is merged and then people just accumulate powers and use them to kill people _I do not consider that to be a failure_ because they are independently chasing what they want to do (kill people) and if they succeeded in ascending that is what they would have done anyway.
But now they're doing it because they want to not because we designed a channel that they flow down, and because the crew now know that they _aren't_ guaranteed to become a station-consuming worm if left alone then it can allow people to relax a little bit.

2023-11-17 15:07 UTC, SomeoneYouProbablyKnow commented
> And no, you really can't get rid of TG in a TG player.
If you change the core aspects, they'll find their way to achieve what they want anyway. Just LRP things my man.

If that is the case game design would not exist. It's really easy to influence players with systems. Yeah SOME might bypass or exploit it to the detriment of themselves and everyone else but on the large scale it would have an effect.

LRP is the way it is because the people who didn't like it left. If mechanics change drastically so will the playerbase due to the same effect. 
Not that i want this but "just LRP being LRP" is a nothing statement. 

Frankly making heretics less ascension dependant would make for BETTER murderbones where both sides have to think and use interesting tools to win. 
Instead of 
1) camp maints for intern enginners
2) Become death, destroyer of worlds

2023-11-17 15:36 UTC, Higgin commented
@Ghommie made this point on the progtot PR and it applies just as well to heretics, so I'm going to by in large copy what I wrote there.
> There's little incentive to do otherwise spare the occasional "big brain" play; they're all in all a liability to keep alive.

This is hard to encourage as long as there's effectively no ceiling on what antags can do and no enforced commitment to staying below a certain level of violence or disruption. A heretic who says 'I'm just playing with rifts bro' can turn around and kill you fifteen minutes later - good faith is unfortunately a bad play.

Beside that, this and its sibling are good PRs, and this is a good step towards addressing a big problem: progression antags scale in a positive feedback loop. They win so they then win harder. This makes the final objectives or ascension, by the time they appear, much less a matter of drama or climactic tension as a foregone conclusion. 

_With heretic in particular, this happens after an early game a lot of people feel is too weak by comparison - you get shut down early or you get your flash-resistant armor, space immunity, free blocks, AA, various CC/jaunts/escapes, etc._

Even if there's no ceiling on what people can do, progression antags' ability to go dummy at basically any threat level in combination with - justified by - this scaling, which has them out kicking down doors, kicking puppies, and accumulating power left and right, massively raises the stakes on dealing with them whether it's a blue star or a black orbit. There's no inherent limit to the threat level that tells players 'play differently' - so they don't, on either side, and it reinforces the most brutal tendencies of play for everyone to the detriment of doing anything less.

I'd suggest that this PR be part of a larger program doing the following: 

1. Put a threat-level limit below which heretics cannot ascend or, given that's kind of their whole deal and ascensions are cool, do not appear. 
2. Potentially scale the availability of rifts and the cost of advancement with the threat level. 
3. When somebody rolls heretic, give them a popup that does the following: give them the threat level, tell them what their limits are, and give them a choice of whether or not to accept the roll, refund it, or maybe even trade into some other antag type. 
4. When heretics are in-game, require that **every other ascension-eligible heretic (read: one who hasn't set a custom goal) be dead before they can ascend.** When they get to their final ritual, replace their Living Heart targets with all other living targets. This sets them up to be self-limiting with cool magic-user-on-magic-user battles at the end of the day, invites the crew to play politics between heretics instead of largely straight against heretics (who can be flatly oppressive when they team up, like a lot of antags,) and still admits the possibility of bringing them back in as ghouls for the dominant heretic.

2023-11-17 15:43 UTC, D4C-420 commented
If the 2 main problems with heretic ascensions is:
1. They give a common antagonist a way to definitely end the round 
2. They are the main focus of heretics at the expense of not interacting with anything

> I think heretic ascensions are important for the antag to guide players forward, heretic not having tools to use with the sandbox is a larger issue with heretic

I largely agree with fikou on this idea. Heretics are defined by their paths ascension and everything in it is either made to reach that goal, or to be enchanted by it.  

You could kill two birds with one stone if you change the ascensions to go from an excellent murderbone tool to instead a somewhat gimmicky hammer to interact with the sandbox more (while being a decent muder tool). 

E.g rather than just giving rust the ability to be nigh immortal on rust and have them remove the whole station, let ascension instead give them a spell which is basically a supped up RCD and let them start building things out of rust. Let them make walls, doors, machines, etc so they can turn whatever is on rust into a death trap. 

Rather than having void start one giant snow storm, let them start messing with atmos, spewing cold air all over, ruining peoples internals. 

I think you get the idea.

2023-11-17 16:19 UTC, Jacquerel commented
> Make the chievs still be visible in game, even if they're no longer unlockable There's a strong precedent for limited-time achievements in games

I think I did this already

2023-11-17 16:25 UTC, excalisword commented
I would be more fine with removing final objectives than the heretic ascension, but I would rather we keep both. The main difference in gimmick potential between traitor and heretic is that traitor has more gimmicky items to buy and has more leeway to just get his items taken away rather than killed. However, the heretic gets abilities, items, and minions that hold three purposes. 

1. One, the purpose of helping you towards your ascension which means more murdery minions, items, and powers. 
2. Two, more defensive abilities and items that help you protect yourself from retribution such as blade breaks, eldritch ID, lock grasp, and the shield wall book. 
3. And three, items that help you disrupt the crew, which can also be used to disrupt attackers. I can think of none of these off the top of my head, but I know some of the items function like purpose number three.

Now the problem with removing the ascension part for the heretic is that you leave in all the purposes of the items, abilities, and minions that you can get as a heretic. This means that heretic is still designed to be confrontational with crew if they play using the abilities they are given, but they don't have to worry about getting caught unless they just want more of these types of abilities, items, or minions. This is because the ascension kinda, from my experience anyway, forces the heretic to be not as bold due to the very real possibility of getting shutdown early and not being able to get the sweet final ascension.

2023-11-17 16:38 UTC, moocowswag commented
Instead of disabling ascensions i think each ascension power be brought into line and balanced among eachother , they are definitely not created equal (the paths having a weaker or stronger early game doesnt really matter because you dont use spells until you have strong enough spells to be worth outing your antag status anyway, not to mention you can take stuff from every other path)

2023-11-17 16:48 UTC, excalisword commented
> Instead of disabling ascensions i think each ascension power be brought into line and balanced among eachother , they are definitely not created equal (the paths having a weaker or stronger early game doesnt really matter because you dont use spells until you have strong enough spells to be worth outing your antag status anyway, not to mention you can take stuff from every other path)

Honestly, I feel like most ascensions should be more like flesh in terms of power and that flesh should have better damage transfer between the worm form and human form. Then we can make it so that killing the heretic in all occasions stops the effect of the ascension without worrying about people just ganking the heretic and killing him immediately due to a lack of power.

2023-11-17 16:57 UTC, Overuseddart commented
Heretic doesn’t have gear on the level of tots or lings until ascension, a tot with a 1tc baton can wipe the floor with a near ascension heretic if they play right. Why would anyone choose to play heretic when nearly every antag is stronger? You don’t get a dramatic and fun ascension and instead you get worse gear and die to a baton an hour in.

2023-11-17 17:49 UTC, TheVekter commented
While I agree with your rhetorical goals, I don't think this is the solution to the problem. Heretics don't feel like they have any kind of direction if they aren't moving towards ascension. I think you'd honestly need to completely redesign them from the ground up if you remove ascension, otherwise they don't make any narrative or gameplay sense.

I like the idea of us moving away from hard-set win conditions on common antags, but I don't think just stripping them out and calling it a day solves any actual problem. It's throwing the baby out with the bathwater.

2023-11-17 17:52 UTC, GuillaumePrata commented
> Heretic doesn’t have the tools to make any gimmicks, they cannot interact with a sandbox because their kit is all combat oriented. There’s very few gimmicks a heretic can do that a normal crew member cannot.

For the last 2 or so years, heretic design had a singular focus: Ascension.

If this problem is out of the way, we can slowly change Heretics into being more aligned with the sandbox interactions of the game, giving them funnier and more powerful tools without having to woory too much about any power given to heretics resulting in shorter rounds due to ascension.

Our best features were not built in a singular PR, they were slowly built over time, taking feedback from players, getting QoLs, etc.
Keeping Ascension around until an eventual full rework shows up will just make designing new tools for heretics be harder.

2023-11-17 17:57 UTC, TheVekter commented
> > Heretic doesn’t have the tools to make any gimmicks, they cannot interact with a sandbox because their kit is all combat oriented. There’s very few gimmicks a heretic can do that a normal crew member cannot.
> 
> For the last 2 or so years, heretic design had a singular focus: Ascension.
> 
> If this problem is out of the way, we can slowly change heretics into being more aligned with the sandbox interactions of the game, giving them funnier and more powerful tools without having to worry too much about any power given to heretics resulting in shorter rounds due to ascension.
> 
> Our best features were not built in a singular PR, they were slowly built over time, taking feedback from players, getting QoLs, etc. Keeping Ascension around until an eventual full rework shows up will just make designing new tools for heretics be harder.

Then we should have those things in place instead of asking players who enjoy that content to be patient while we un-fuck it over the course of a year. Don't gut something with the nebulous goal of turning around and fixing it. Fix it first.

2023-11-17 18:00 UTC, zoomachina commented
> For the last 2 or so years, heretic design had a singular focus: Ascension.

what makes you believe that?

2023-11-17 18:02 UTC, excalisword commented
Just a question Prata, but what should the focus of heretics be if not ascension? The only other focus I can think of that would make sense is just general screwing around with the crew, but that is already what heretic abilities do and while you can argue that we should lean into that, what's stopping players from killing the heretic for being too annoying to deal with?

2023-11-17 18:26 UTC, zxaber commented
@Jacquerel 
>Once non-antagonists notice that any antagonist whom they leave alone will eventually summon a battlecruiser or create an infinite portal of mobs, they will start to wonder why they should do anything when encountering an antagonist but react as violently as possible.
In fact they will start to do this proactively, because they don't want their plans to be spoiled by the sudden arrival of a Star Gazer.

I would still pin this not on us having a reward at all, but on us having ascensions being so very powerful. Consider Progtot, where you *do* need to go through the steps to get the reward of buying dangerous, loud gear. No one really sweats it that a traitor *could* buy an energy sword or a makarov, because those are threats that can be handled with a small group of crew working together.

Heretic ascensions are treated the way they are *because* they gain such an advantage they can be nearly unkillable for most crew members, even when working together.

2023-11-17 18:41 UTC, excalisword commented
I mean, heretics have to deal with a lot more stuff to get to the point of ascension due to the multiple avenues by which heretics can get caught unlike prog tot which can do multiple things that are stealthier than what heretics have to do. Ascension should be comparable more to how round ending syndicate battlecruiser can be in terms of death. It's why a lot of people don't go for the void and ash ascension from what I've seen, because those two ascensions, in comparison to the other ones, are weaker overall when ascended in my opinion than rust, flesh, lock, or blade.

2023-11-17 19:45 UTC, saprasam commented
heretics do not have much leeway in the way of gimmicks even without ascension, as most, if not all of their gear is directly related to just killing somebody instantly
it also requires changes to the lore, because heretic is built towards that big payoff at the end, there's no incentive to do anything besides ascend because that IS heretic's goal. removing it creates an antag that exists only to grief

2023-11-17 20:12 UTC, dalmationer commented
This is a good PR and I think it opens a path for more freeform and less railroaded gameplay as heretic. Heretics are often dealt with extremely lethally because of how dangerous they can be if you don't nip them in the bud, and how difficult they are for sec to contain. I don't play heretic, really, but I do play sec, and there's a big pressure to just kill a confirmed heretic. I'd like if there was less pressure to do that, so that I could get some more RP with them and feel less pressure to just round remove.

2023-11-17 20:38 UTC, optimumtact commented
> i'm willing to put my foot down (unless the headcoders object)

unless you have a concrete credible plan of action to sooth the headadmins on this, you cant.

2023-11-17 20:49 UTC, moocowswag commented
I thought that was a headmin that was putting his foot down

2023-11-17 21:25 UTC, GuillaumePrata commented
> what makes you believe that?

The simple fact that heretic features rarely interact with the sandbox to the point a good slice of the player base would say they feel empty without the ascension part.

> Don't gut something with the nebulous goal of turning around and fixing it. Fix it first.

If a feature is bad, it should be removed regardless if it will have a future rework or not.
We shouldn't keep bad things around until we get a replacement, we should just remove them.

Again, ignoring that removing ascension makes designing for future design goals a lot easier.

2023-11-17 21:33 UTC, Overuseddart commented
If the player base wouldn’t play heretic and say that heretic would be empty without ascension, instead of just removing ascension you may as well remove heretic instead of just removing what makes a heretic a heretic

2023-11-17 21:44 UTC, GuillaumePrata commented
> the antag itself would be the bad design,

Disagree, most features that are loved today started small and grew up.
Ascensionless heretics might feel empty for some people right now, but it is salvageable, just need to design it forward with tools to improve on their new gameplay goals.

2023-11-17 21:51 UTC, GuillaumePrata commented
> but what should the focus of heretics be if not ascension?

Each branch of heretic should have their own focus.
Now what each should be, no idea, I honestly don't even know what each branch of heretic does right now outside of their ascension as everything feels pointless outside of that.

Imagine if every uplink item was mostly useless and people o lu remembered what the FO did, basically that.

> what's stopping players from killing the heretic for being too annoying to deal with?

Nothing, and that is good, they are antagonists after all and should be a thorn on the crew side.
The issue with ascensions is that even if you just want to be a gimmicky heretic right now, people will treat you as a round ender.

Pre progtot traitors could easily plasma flood the station or do any other round ending trick, but a big slice of the player base still treated them as a low threat antag by default as that is what the average traitor was.

2023-11-17 22:11 UTC, SimplySmiley123 commented
> Each branch of heretic should have their own focus. Now what each should be, no idea, I honestly don't even know what each branch of heretic does right now outside of their ascension as everything feels pointless outside of that.

The thing is they do have their niches already outside of ascensions.

Ash is your good all-rounder path that isn't particularly strong at anything, nor particularly bad at anything while giving a decent mix of utility and offensive capabilities. Can do stealth, can go loud, just versatility.

Flesh is a path where you focus down on self-made minions and ghouls to help you out with difficulty of the path relying more on capabilities of the crew you turned into your minions or whichever ghost took over your summoned monstrosity.

Void revolves goes a bit into stealth side of things with easier to access space protection, a lot of cheese on this path thanks to that.

Rust is your loud approach heretic path that's particularly bad at helping you on the loud approach, even after you ascend you're easy to take down. Allows to one-tap annoying borgs and combat mechs though so crew can't rely on a high-speed, never slowing down murder machine to wittle them down.

Blade same as Rust focuses on being loud, but narrows it down into 1 on 1 skirmishes instead and fucking over seccies over-relying on batons (my beloved path for that sole reason)

Cosmic which revolves around crowd control by managing the star marks and relying mostly on your mediocre spells to help you get out of incoming death at hands of the crew.

Knock path which consists mostly of easing your way into places and having to figure out combat without the, already not that amazing, heretical powers.

Still doesn't change their abilities are, to be honest, way too situational for most of 'em. And not even in a fun gimmicky way you can play around.

2023-11-17 22:13 UTC, moocowswag commented
Keep in mind everything i said about heretic also loosely applies to ling and  alot of their abilities and they get by just fine just because their niche is they are harder to kill so they can actually dip into and play with the sand (use department / non antag content) while still being persistently harder to kill (virus/wound wiping and self revival)

in practice this is usually lings that try to tip the game into heavy pve since they are immune to it (plasmafires/viruses/shitmos sabotage stuff and just so happen to have the tools (identity swapping) to get away with it

Its nowhere near directly interacting with the sandbox with your own flavor of sand tho ( lings example if they could use their chemical abilities on beakers that would instantly unlock alot of gimmicks)

if ash heretic could heat up containers (gas and chems) and void heretic could cool them down that immediately opens the door for atmos savvy heretics, especially if later on they could upgrade it to do it from a slight range.

if rust heretic could rust items to make them jagged and hard for others to pick up without hurting their hands they immediately can start looking into trying to get unique items like hand tele since itl be hard to take from them

If blade heretic had a pocket dimension called “mom’s basement” where they spend their time “mastering the blade” they can safely craft and prepare items in there (make it 2x3 area or something so they cant draw rune), supports limited power (50kw) and has bad internet bandwidth (no connection to station radio or research servers)

2023-11-17 22:25 UTC, excalisword commented
>Each branch of heretic should have their own focus. Now what each should be, no idea, I honestly don't even know what each branch of heretic does right now outside of their ascension as everything feels pointless outside of that.

Along with what Smiley said, all of your paths focus on different ways to help you get to your ascension. Flesh has minions to help cause chaos to help you get sacrifices, void has silence to help you be quiet while you grab your sacrifice, ash allows you to apply status effects to your target that whittle down their health to allow you to grab them, cosmic has star marks to help them stop their target from leaving, rust has the ability to flat out destroy there way to their target, knock has the ability to grant you access to your target while denying your target easy escape, and blade allows you to more easily 1 v 1 your targets without worrying about the great equalizer that is stuns.

2023-11-17 22:32 UTC, SomeoneYouProbablyKnow commented
What's up with heretic discussions and people listing things?

But anyway, the problem here is that ascensions are all achived via the same means so to do them you need roughly the same tools.

If rust ascension asked you to get... idk every head remote instead of dead bodies it would incentivise its own playstyle

if void ascension asked you to vent the atmos out of 5 rooms on station and not for dead bodies it would play differently etc etc

These particular ideas are shite i came up with in 3 seconds but you get the point.

2023-11-17 23:07 UTC, DATA-xPUNGED commented
I do understand the point behind this but damn it makes me sad

2023-11-17 23:22 UTC, GPeckman commented
> If a feature is bad, it should be removed regardless if it will have a future rework or not.
> We shouldn't keep bad things around until we get a replacement, we should just remove them.

If that was the way that the code base was run, then virology, cult, genetics, and xenobiology would have been removed a long time ago.

2023-11-17 23:45 UTC, AtomTheProphet commented
> > If a feature is bad, it should be removed regardless if it will have a future rework or not.
> > We shouldn't keep bad things around until we get a replacement, we should just remove them.
> 
> If that was the way that the code base was run, then virology, cult, genetics, and xenobiology would have been removed a long time ago.

Well the cult isn't really that bad, just mildly controversial.

2023-11-18 00:19 UTC, zoomachina commented
> > what makes you believe that?
> 
> The simple fact that heretic features rarely interact with the sandbox to the point a good slice of the player base would say they feel empty without the ascension part.

how about: ascensions don't "interact with the sandbox" a whole lot either, but at least they end the round. The path itself is often even more unique than the ascension, so people who made it must've spent a lot of brain juice on it, but when it's mostly self-contained or a creative way to murder, it's not gonna "interact with the sandbox". Adding more of that is considered to be okay since all the rest of the heretic stuff is the same, which is why it feels empty. 
If "interacting with the sandbox" should be a thing for heretics, why not enforce that when adding new paths instead of removing ascensions?

2023-11-18 00:51 UTC, GuillaumePrata commented
> If that was the way that the code base was run, then virology, cult, genetics, and xenobiology would have been removed a long time ago.

All of these are way more important to the codebase than just the slice of ascension of heretics.
And we still see constant discusions about removing/reworking them, but they are in an odd place where you need some heavy maintainer backing for any small changes and IMO that is the main reason they have been stagnant.
Not overall bad design like how Ascension leads to "skinner box" like gameplay for players.

It is easy to point out the outliners, but I can bring as many job features/antagonists that were outright removed to defend that this *IS* how the codebase works at large.

Nanites, cloning, clock cult, swarmers, Singulo/Tesla/Others, thieves, families, shadowling, roundstart blob/xenos, circuits, final objective for late join tots, and the list can go on.

2023-11-18 01:59 UTC, excalisword commented
I mean, from my understanding @GuillaumePrata,  clock cult was removed due to how no one was working on it, no one wanting to work on it, and it taking up a bunch of meaningless code bloat, so I think that situation is different than removing heretic because people are actively working on heretic. Removing ascension means reworking literally everything about heretic paths as a whole due to the fact that, as me and Smiley somewhat pointed out, each path is built towards helping a certain play style ascend.

2023-11-18 02:07 UTC, zxaber commented
Clock cult had other issues. Primarily, the end-game was a forced siege of Clocktown on a timer, and something like a fifteen minute timer before the clocks won. So if the crew was unable or unwilling to attack (or were all already converted), the server as a whole had to just wait it out until the round could end.

2023-11-18 02:12 UTC, excalisword commented
> Clock cult had other issues. Primarily, the end-game was a forced siege of Clocktown on a timer, and something like a fifteen minute timer before the clocks won. So if the crew was unable or unwilling to attack (or were all already converted), the server as a whole had to just wait it out until the round could end.

Interesting to know since I wasn't around for the clock cult days, but that's besides the point. I still think the clock cult situation is different enough that it really shouldn't be lumped in with the rest of what he mentioned, and hell those too might be unrelated to what he's describing since I never really got a chance to play any of those either.

2023-11-18 03:52 UTC, GuillaumePrata commented
> I mean, from my understanding @GuillaumePrata, clock cult was removed due to how no one was working on it

Someone working on something or not is not an issue, we have things that go unchanged for years because they are not an issue at the current time.

Clock Cult was badly designed, and it was removed, we could sit on it and say "No remove please polish" as a lot of people are saying on this PR, but... that almost never works in the codebase for multiple different reasons.

My Clock Cult comparisson still works, if something is bad, remove it.
If the removed thing has value, it can be reworked at any time someone is interested on doing it, while we don't keep features that are an issue in the meantime.

A good example are circuits, it was removed and eventually reintroduced when someone was interested on it, and it is a way better feature that it would be if we had to consider the old circuit system was still around and had build on top of its shakey structure.

2023-11-18 04:17 UTC, excalisword commented
I'll concede on the clock cult issue, but I will still argue that ascensions aren't bad. They are your reward for dealing with sacrifices, for going against the odds and beating the crew. I am honestly just afraid that heretic will turn into traitor but magic instead of tech instead of being its own unique thing. And for removing the ascension, you would still need to rework everything else about heretic to be more in line with the stated vision of Jaq's, which means months of heretic being incomplete as the maintainers and coders talk about how best to balance heretic's abilities, because almost every single heretic thing will have to be reworked for this new vision due to their innately conflictive nature with crew not aligning with them wanting to have more "heretic gimmicks" which may just leave heretic in a spot of feeling unoriginal instead of being unique.

2023-11-18 04:44 UTC, GuillaumePrata commented
> but I will still argue that ascensions aren't bad

By itself, they are flavorful as fuck.
As a reward for heretics, which we have multiple on a single shift, which has most of their features aimed at ascensions resulting in non ascended gameplay to be really boring, which the average crew won't even see antagonizing before ascension, or that the average crew will have no chance to fight against as they are unfair *by design*...

It's pretty bad...

Heretics IMO is the classic example of "I like antag X (in this case wizard) and want more of it in the game" going wrong.
Maybe if heretics were as rare as wizards, and had a fast staircase into ascension, ascension as a mechanic could work.

2023-11-18 05:02 UTC, excalisword commented
I honestly haven't seen that many ascensions, although I don't play that often. To counter the too often ascension point though, Melbert currently has a PR open that provides data that attributes the more ascension rate to the side path points part of the recent heretic buff.

2023-11-18 05:13 UTC, CliffracerX commented
This is a code bandaid on a player behaviour problem.  Anyone can end a round without needing a big flashy way of doing it, or murderbone without special tools - but we give antags flashy endings and special tools precisely because it makes them something out of the ordinary & more threatening than your average greytider with a toolbox.  Ascensions being *unfun to fight against* and acting as effective round-ends as a result is a problem; but it's one that can be solved with polishing the system rather than gutting it outright and hoping someone else comes in to pick up the pieces.

Regular tot finales already give a good path for an ascension rework; each one is *unique* in its consequences, and *unique* in how you can *stop it* as a member of the crew.  Battlecruiser summon works around the comms console, so you hunker down and protect the bridge & tech storage - and the crew can still *fight the cruiser* when it arrives.  AI virus works around Upload, and just functions as spawning a Malf AI that the crew can fight.  Dark Matteor is engineering sabotage, and a halfway competent team should be able to tear apart the satellites with ease.  Romerol is elusive Medbay content & brings a fricken *zombie plague* for the crew to rally against.  Space Dragon is arguably the most similar to existing ascensions, given it turns you into a super-mob - but it's really the *only one* that stands out as a little iffy.  Finally, the Supermatter Cascade requires you to get to Engineering, deploy the crystal, *and* sabotage the engine beyond the maintenance capabilities of your local giga-chadmosians - no easy feat when a handful of block-heads with fire extinguishers can keep the engine on life support for the precious minutes needed for the repair team to get the engine stabilized.

That in mind, ascensions being *reworked* to be unique, *dangerous*, but not unstoppable, and coupled with changes to heretic progression to give them more sandbox tools and less reasons to turtle in early-game would be infinitely better - and with the unique paths, the basis is already *there* to shake things up with flavor.  Off the top of my head, some loose ideas:
 - Ash becoming the hand of the Necropolis, spreading its burning grasp on the station.  Isolate the corruption, destroy the part of the station that's fallen if you have to, and be unafraid to unleash the ice-cold grasp of hard vaccuum if it's what it takes to stop the station from being corrupted beyond repair.
 - Flesh heretics becoming an amalgamate body-horror with their minions but counterable with bioterror on Medbay/Chemistry's part or Atmosia flooding the station to purge these unnatural lifeforms - but all at risk of losing good crew who weren't prepared for the hell that was about to be unleashed.
 - Void perhaps stands as the inverse of Ash, creating a growing network of tears that they can travel through to evade trouble whilst also drawing the atmosphere out of the area.  R&D or Engineering stand to fight them the easiest - be that by closing the rifts, or walling them off and pumping a plasmafire into them to scour the whole network (and the heretic if they're still inside!)
 - Rust gathers the broken heaps of the silicons they felled and rebuilds them into new, savage machines filled with dark magicks - but they're still **made of rust**, which is hardly the picture of structural integrity & even a greytider with could jukes could knock one down with a toolbox or weld its joints to uselessness - not to mention a quick H2O leak all but guaranteeing they become naught but very ugly statues from additional oxidization locking things up.
 - Blade should maybe explicitly get to become a god-tier warrior, *but* become bound by an unholy code of honor that punishes them if they try to play cheap and bully the crew too hard- if not straight-up giving them an alternate route where they have to atone for their sins against the crew by seeking to become the station's defender from the shadows, dueling other antags 'till they finally fall to their better.
 - Cosmic probably just gets to make funny anomalies and annoy R&D while converting the station from light tubes to light prisms.  I'm not really able to see much interesting here.
 - Knock's whole gimmick being "go places you shouldn't" seems likely to simply share the fun, getting to fry access requirements across the board & forcing the crew to grapple with their newfound all-access & the question of whether or not they use it in good faith...or just go honk bikehorns on the bridge to piss the Captain off, all while the Ascendant can kick back, relax, eat popcorn & watch the chaos unfold.  Bonus points if they unwittingly give nukies AA in the process!

2023-11-18 05:15 UTC, gorillion commented
if you actually spectate the game you will know that a grand majority of people who get solo antagonists will not do anything with said antagonist powers until the absolute end of the shift (like bombing the shuttle) (if they EVER do anything at all). this goes for heretics too. most do not have any sacrifices by the end of the shift. removing ascensions isnt going to do anything but take the incentive to play well away from players who actually bother to do objectives. same thing goes for tot final objectives. i'd probably guess i've only seen 5 different statics EVER reach tot final objectives. i don't get where you're getting the idea that a very rare event where an antag can really put pressure on the station is bad for the game. if anything, objectives + progression need tuning to make the large amount of people who get antag actually able to/willing to complete some objectives to get the ball rolling.

2023-11-18 05:19 UTC, SethLafuente commented
oh this is bad....

2023-11-18 05:37 UTC, GuillaumePrata commented
> I honestly haven't seen that many ascensions. To counter the too often ascension point though

I think most people want this change over how often ascensions happen.
Melbert's PR has data shows it is around 5% to 10%

And that just pushes the point further, an antagonist should not be balanced around something that happens around 5%-10% of the shifts.

How often it happens is not that important for the main point of the PR, which is that Ascensions are round ending and low threat antags should not have a built in way to end the round, as this brings multiple other issues to the table.

2023-11-18 05:59 UTC, excalisword commented
I don't know how that is the silver bullet you're looking for given how, from my understanding of percentages, that just means around every 100 rounds, around 5 to 10 has someone ascend which seems pretty fair for an antagonist that appears in the threat a lot of the time. 
>How often it happens is not that important for the main point of the PR, which is that Ascensions are round ending and low threat antags should not have a built in way to end the round, as this brings multiple other issues to the table.

I mean, what else is the point of progression antagonists? To start off low power, or low threat, then build up towards being more powerful threats. Also, I see only a few statics most of the time, really good ones at that, achieve ascension.

2023-11-18 06:40 UTC, GuillaumePrata commented
> I mean, what else is the point of progression antagonists?

In my opinion, to be a mistake.

2023-11-18 06:48 UTC, excalisword commented
> > I mean, what else is the point of progression antagonists?
> 
> In my opinion, to be a mistake.

 They are supposed to be warlocks, not just traitor but with magic instead of tech. They are supposed to be deepening their connection with their chosen god, gaining more power from them, which means it should logically be that the more they do deepen their bond, the more powerful they get.

2023-11-18 07:02 UTC, GuillaumePrata commented
> They are supposed to be warlocks, not just traitor but with magic instead of tech. They are supposed to be deepening their connection with their chosen god, gaining more power from them, which means it should logically be that the more they do deepen their bond, the more powerful they get.

This is just flavor soup and it doesn't make the gameplay be good for anyone involved.

2023-11-18 07:30 UTC, Deultus commented
the antagonist that was created and balanced so that he can provide a greater threat only after elevation, loses one of his main chips from which he ballanced from the very beginning, and that is why he basically poses a threat and demands his elimination, the antagonist that literally at the beginning of the round shows himself to the team through the cracks at the station (and this happens when he is very weak), and a bunch of other signs, he loses his main chip. you might as well have just deleted it. although in fact, any other antagonist can be the end of the round if he just kills everyone

2023-11-18 15:29 UTC, Jacquerel commented
Thanks for all of your feedback. I'm glad to see that there are some people identifying the same issues with our skinner box design as I am (though I will not pretend they're the majority!) and I still generally think that we've tapped into a vein of something here with both heretics and (to a lesser degree) traitor progression which ultimately creates a negative feedback loop in our game design...

But it's also obvious that if I want to do anything about it then I will need to make greater adjustments to Heretics _first_, so that's what I'm going to go away and start working on. 
It's very valid to suggest that without ascensions heretics don't really have anything else _to_ do, as the tools available to them right now are almost exclusively about effectively killing people, that they don't have support for causing other kinds of trouble on the station, and that I wouldn't be the first person to make a sweeping change with the promise of other supporting changes later and then not do the other changes.

My future efforts are going to be aimed at making Heretics a more versatile antagonist in general, shifting the balance of power a little from late in the game to early (such that you're not spending most of the round as a glorified assistant and unlock most of your cool abilities just as you no longer need them), and perhaps also lowering the intentionally high skill floor.
I have an idea for another pretty easy win that I can implement _right now_ and relatively quickly which I hope will prove more popular than this one. Other more substantial reworks are obviously going to take more time.

In the meanwhile, I believe @Fikou is going to try fucking with heretic's dynamic config to see if just making them less common or hacing a cap on the number per round improves things for servers which have been having problems with players. That's admin stuff, nothing to do with me.

2023-11-18 15:29 UTC, closed without merging