Barsign Wallmounts and Cargo Pack
tgstation/tgstation pull request #79837
Opened 2023-11-19 02:15 UTC by Rhials

## About The Pull Request

My apologies to Lief.Nobody, whose contest I was unable to submit a barsign sprite for. Hopefully this contribution will suffice.

This gives bar signs their own wallmount, allowing for them to be deconstructed, moved, or replaced from a cargo pack.

**BEHOLD: MULTI-BARSIGN ACTION!**

![image](https://github.com/tgstation/tgstation/assets/28870487/37d0fe72-bdb7-4974-8e7e-3ebd4077d095)

The cargo pack is expensive, because bar signs are SPECIAL and shouldn't be thrown around the station willy-nilly.

Now that bar signs are replaceable, they have been made fully destructible and will be destroyed after taking enough damage, rather than just being disabled.

They can also be removed via opening the panel and wrenching (for 10 seconds, so the bartender has time to gun down sign thiefs!)

## Why It's Good For The Game

With all the recent barsign related PRs, they could definitely use with a tad more depth on the code side. 

Honestly, I just saw the "Bargonia" bar sign and realized "there's no way a cargo bar could actually set this up as a decoration" and set out to fix that.

## Changelog

:cl: Rhials
qol: Bar signs can now be purchased from cargo. Neat!
qol: Bar signs can now be deconstructed with a screwdriver and wrench.
qol: Bar signs can now be smashed to pieces, rather than just disabled.
/:cl:

2023-11-19 02:36 UTC, BlueMemesauce commented
Barsigns rename the area they're in when changed. I would recommend changing this functionality so cargo can't rename all the rooms in the station "Maid Cafe"

2023-11-21 03:20 UTC, san7890 requested changes

2023-11-21 03:20 UTC, san7890 commented on code/game/machinery/barsigns.dm
> +		return TOOL_ACT_TOOLTYPE_SUCCESS
```suggestion
	if(!do_after(user, (10 SECONDS), target = src))
		return FALSE

	tool.play_tool_sound(src)
	deconstruct(disassembled = TRUE)
	return TOOL_ACT_TOOLTYPE_SUCCESS
```

2023-11-21 04:33 UTC, Wallemations approved these changes
Icon looks fine.

Additional question:

How viable would it be for finding a way to link multiple barsigns to each other, so changing one changes the rest?
It would help with the mild annoyance of finding all the different signs in each map and manually swapping each of them.

Don't worry about doing this yourself, it was more a question for anyone who knows anything about code more than I do.

2023-11-21 17:25 UTC, Rhials commented
> Barsigns rename the area they're in when changed. I would recommend changing this functionality so cargo can't rename all the rooms in the station "Maid Cafe"

Addressed, barsigns now only rename the area they occupy if they were built into the map.

2023-11-25 06:59 UTC, san7890 commented
hm i liked the potential interaction of having bar signs easily change names of areas because that is funny to me. maybe if the panel is open and it's "registered" on the station's blueprints (hardmatch to the ones the CE has) it'll retain its area-name changing properties? figure i should mention it now while this mechanic is still fluid

2023-11-25 18:32 UTC, Wallemations commented
> hm i liked the potential interaction of having bar signs easily change names of areas because that is funny to me. maybe if the panel is open and it's "registered" on the station's blueprints (hardmatch to the ones the CE has) it'll retain its area-name changing properties? figure i should mention it now while this mechanic is still fluid

That kinda negates the blueprints tbh

2023-11-26 00:06 UTC, san7890 commented
it doesn't negate the blueprints if you're limited to only a certain number of area names

2023-11-27 21:34 UTC, merged