Removes virology, the virologist and related advanced diseases content
tgstation/tgstation pull request #79849
Opened 2023-11-19 15:59 UTC by Time-Green

## About The Pull Request

**This PR removes features related to virology, which are:**
- The Virologist 
- Advanced Diseases. These are the custom diseases that the virologist can create or that can be created through events or miasma etc
- Sentient Disease: The antagonist, that uses advanced diseases to function.
- Advanced disease event: The event that spawns a random combination of symptoms on a disease and gives it to a few players.

**This PR does not remove the following:**
- Simple diseases. Fly, Pierrots throat, beesease, flu, cold, etc
- The pandemic. It's still needed to make cures against the above simple viruses
- Simple disease spawning event
- Simple disease crates
- Floor virusses. The carpeliosis, tritgas etc viruses were technically advanced, but have been converted to simple diseases. 
- Virology clothing and outfits. The whole style of virology is pretty dope, so I don't see the harm. You can still buy their clothes or have their vendrobes mapped in. 

**Related tweaks:**
- The DNA injector CRISPR thing now relies on cold or flu to give a crispr charge. I don't think these are even retroviruses, but otherwise the CRISPR feature would have to be excised completely. This still leaves it possible to use by ordering a virus crate.
- Virology room: This needs to be converted into a small room for just the pandemic and some basic cure creation that MD's or CMO's can defer to. Otherwise the rest of the satellite is now free for whatever (psychologist asylum, corgi pen part 2 etc). Ideally the satellite is not removed so the space can be repurposed if we ever create a new virologist or other medical job. 

## Why It's Good For The Game

In short:

Virology is an invisible and extremely unfair system from a time where death was trivial. Viruses spread incredibly fast and can become so incredibly lethal or obnoxious that very little fun is had. You're doing your job, but unbeknowst to you someone sneezed and now you can barely move and are marked for death. Your only hope is cryo or stasis to prolongue death, or to pray that chemistry is still functioning (and optionally manned). When you factor in traitor virologist, who can stack multiple lethal viruses quite trivially, a round can end before it began and there is no mechanically interesting counterplay.

You can protect yourself from plasmafloods, you can fight back against murderboners, you can hide from the alien infestation and you can flee the station when Nar'Sie is summoned, but the moment you get infected, you're fucked and the only means of survival is the chemistry dispensers working and not too many people trying to use them at once. 

[This is my full reasoning in hackmd.](https://hackmd.io/br9pmyp3Q3yWn4_VSnm8jg) 

<details>
  <summary>Or in a spoiler because I also don't like clicking links</summary>
  
# Complete Virology Removal
Completely removes virology and all virology content

**Why is this good for the game?**
You are John Assistant. You walk through a hallway. Someone sneezes. You are now coughing, screenshaking and on fire and there is nothing you can do except either delaying death through cryo or stasis, or breaking into chemistry or hoping there's someone left to make a cure. 

The problems, dissected are:

**1. Invisible**
Viruses are an invisible system. Someone sneezes near you, or you walk through blood, and you are now marked for death (or madness if it's a coughstun/screenshake virus). You are not told you are infected until it starts affecting you. 

**2. Unavoidable**
You can't dodge it, you can't avoid it, and there is no measures you can take against it, short of putting on a biosuit with internals (or other equipment that protects against the environment completely). The exponentional spread of viruses usually means that by the time it's known, you are already too late to protect yourself. Singularities and plasma floods are a lot more imminently visible and can be escaped from or protected against.

**3. Stackable**
Symptoms can be stacked to create extremely obnoxious diseases. Confusion virus, coughing virus, burning virus, etc all in one that is not fun or interesting to deal with at all. 

**4. Virology**
There is a job on the station whose entire goal is to ~~cure~~ make viruses. The job is very isolated and doesn't really engage outside of using a dropper and looking at the pandemic, and then becoming a doctor when you finished doing that. It's easy and results are guaranteed. This leads into the next problem...

**5. Spammability**
You can make a virus for every symptom combination, and they will have (usually) their own cure. This means a traitor virologist can make ~10 variations of the same virus and never have to worry about the crew curing it. If the virologist goes through the effort to destroy the pandemic and the chem dispensers, the few people who are able to do something about it will not be able to do something about, now needing to get new equipment while likely dying from the virus.

**Why now?**
When virology was added, cloning was still in so anyone with a deadly virus could clone themselves and it'd be fine. Now that death is more meaningful, and virology hasn't, a severe rift has formed between effort and result. Very little effort can be used to wipe the whole station, and unlike murderboners, singularities or plasma flood, it is silent and acutely lethal. 

**Positive viruses**
I don't think they're very interesting. You get sneezed on and now have passive regen or anti-death. The symptoms themselves, like plasma fixation and radiation healing, are kind of cool, and could probably be readded later to different systems (such as surgery or maybe genetics). 

They're less of a problem than lethal viruses, since at least everyone benefits from it, but I don't think much would be lost by taking away easy global regen. 

# Options

There's a few different ways virology exists:

1. Advanced diseases. The stuff virology makes that can have different combinations of symptoms.
2. Virus event. This spawns an advanced disease with random symptoms. 
3. Sentient disease. The antag that spawns and evolves random symptoms. 
4. Single symptom diseases, such as beaseese and the flu.

Ideally at least virology and advanced diseases are removed. Sentient disease and advanced disease are so incredibly interwoven, it's not possible to keep it. Single symptom diseases are usually fine, they're gimmicky, rare and not outright lethal or extremely frustrating.

# Aftermath
I'm not opposed to a new form of virology, but it'd need to be radically different. No mass infections and no symptom stacking. Perhaps turning virology into a pathologist and adding new viruses that aren't infectious, are avoidable and have some mechanics that can be gamed around would be cool. But I believe virology is so inherently toxic to the game that it would be better to tear it out completely first. 

# Corgi pen is back and now a satelite
Let's fucking go
  
</details>

<details>
  <summary>For mappers/mapping enthousiasts</summary> 
  Some remapping needs to be done to accomodate this removal. I've made a list below:

- [ ] Birdshot virology
- [ ] Deltastation virology
- [ ] Metastation virology
- [ ] Iceboxstation virology
- [ ] North star virology
- [ ] Trammstation virology

- [ ] Lavand syndibase virology
- [ ] Interdyne pirates virology
- [ ] Nuke base virology

If you're interested in remapping any of these, please @ me on discord (or here if not possible) and I'll put you next to the list. 

There's only two requirements: Leave the Pandemic so simple diseases can still be cured (doesn't necessarily need to be in virology) and don't outright nuke the whole sattelite. It could become near impossible to readd viro if it's ever completely redone or to give it to some other job. 

I'm sure there's some fun things to do with the empty space. Abandoned virology, psychologist insanity ward, corgi pen part 2, whatever you can imagine

</details>

<details>
  <summary>Fut [...]

2023-11-19 16:11 UTC, Jacquerel commented
Is this pr ready as of itself or should it be drafted pending map changes?

2023-11-19 16:13 UTC, DrDiasyl commented
This is a crucial step to open possibility to recreate the virology from scratch, the removal of it would totally incentive some people 👍

I think Virology should become more focused on curing then destruction, but for this we need a more interesting disease system then we have right now.

2023-11-19 16:16 UTC, Time-Green commented
> Is this pr ready as of itself or should it be drafted pending map changes?

Yeah good point I'll draft it. It can totally be merged, but it'd just be a dead room with dead machines with dead equipment. Also I probably killed some unit tests I need to resolve first

2023-11-19 16:23 UTC, Time-Green commented
> Is this pr ready as of itself or should it be drafted pending map changes?

Actually I think it's fine. If it's merged now, it's just a dead room, but I've already gotten some interested mappers so worst case scenario the room is dead for a few days (this is what you already said in discord but just to give full context for others)

2023-11-19 16:25 UTC, Yobrocharlie commented
Good PR, Viro is a job where you either find out they’re a traitor or not 40 minutes in by either instantly kicking the bucket to a cyanide virus or seeing a semi-useless good virus go around.

2023-11-19 16:33 UTC, Ghommie commented
One of the few good removal PRs. I look forward the remapping of it.

2023-11-19 16:44 UTC, ATH1909 commented
as an ex-viro main, damn.

would this open up the possibility for a self-respiration mutation, then, since viro can't provide that anymore?

2023-11-19 17:01 UTC, Time-Green commented
> as an ex-viro main, damn.
> 
> would this open up the possibility for a self-respiration mutation, then, since viro can't provide that anymore?

I think a lot of these are fit to be moved elsewhere, yeah. Although I'd personally rather see self-resp be turned into super sci-fi lungs or something, but that's a different discussion we can have then

2023-11-19 17:01 UTC, HoodMilk commented
Virology is annoying from all angles. Whether it be dying due to a narcolepsy fire virus you never even knew you got, or as a virologist yourself trying to roll RNG to get the one symptom you want and failing over and over again. Glad to see it go, it never felt like it added much to the game other than a headache.

2023-11-19 17:09 UTC, JupiterJaeden commented
How does this affect the interdyne pirates, and nukies that decide to use fungal TB?

2023-11-19 17:10 UTC, ATH1909 commented
I suppose it's worth asking: would removing the good kill symptoms (autophago, ARDS, alkali) be enough? if the doomviruses are inconveniencing you instead of killing you in ~2 minutes, that sounds much more palatable.

2023-11-19 17:14 UTC, Thlumyn commented
Maybe the negative effects need to be nerfed a bit or virologists but not to the extent of removing a whole job. Healing viruses are crucial for spacetiding, helpful for mining, and fun to make, along with adding an interesting roleplay aspect to the station because having pathologist is just something that makes sense. Not all jobs need to be the same level of action and I enjoy a job where I can work for a bit and then do whatever. There's a lot that players can do when a virus happens, like having mediborgs with their virus immunity and built in HUDs looking around for patient zero, or wearing their internals or using medical blocker viruses from the virologist. All good healing viruses are below the transmission threshold so taking them has to be a conscious choice, not just "somebody sneezed on you and now you have passive regen". This seems like more of a player issue with people using virology to grief and I don't think the solution to such is to remove virology, that would be like removing ordnance because some people use max caps to grief.

2023-11-19 17:22 UTC, Time-Green commented
> I suppose it's worth asking: would removing the good kill symptoms (autophago, ARDS, alkali) be enough? if the doomviruses are inconveniencing you instead of killing you in ~2 minutes, that sounds much more palatable.

No, I don´t think reconsiliation is possible anymore. Virologies job is spreading diseases, it´s inherently problematic. Even if every lethal and annoying symptom is removed, we´re still left with what can barely be considered a job with questionable round influence. I'd rather see it removed and completely redone than leave it neutered and useless to the point where nobody is interested in touching it

2023-11-19 17:38 UTC, Thlumyn commented
> > I suppose it's worth asking: would removing the good kill symptoms (autophago, ARDS, alkali) be enough? if the doomviruses are inconveniencing you instead of killing you in ~2 minutes, that sounds much more palatable.
> 
> No, I don´t think reconsiliation is possible anymore. Virologies job is spreading diseases, it´s inherently problematic. Even if every lethal and annoying symptom is removed, we´re still left with what can barely be considered a job with questionable round influence. I'd rather see it removed and completely redone than leave it neutered and useless to the point where nobody is interested in touching it

I don't think that nobody would interested if negative symptoms were removed; I play on a downstream where players aren't allowed to make harmful viruses and virology is full up nearly every round.

2023-11-19 17:51 UTC, Sinestia commented
Removing negative symptoms would honestly make virology even more of a negative drag on gameplay, as it would leave its typical effect on the round as merely being "healing virus :3" without even the risk of a rogue viro fucking you up badly. 

That is, essentially, a big part of what got nanites thrown into a pit.

2023-11-19 17:57 UTC, KingkumaArt commented
I'm ok with this.
On the best day viro gives you self resp.
On the worst 2/3s of the station is blind and randomly on fire.
The best rounds they take part in they may not exist, while the worst is just a round that there's a round ending threat where the average crewmember cant really counter it, and you wait in medibay in crit or dead for 30 minutes.

2023-11-19 18:15 UTC, XDTM commented
I wonder if a possible iteration of lethal viruses could involve an automatic global station announcement once a person is infected, so people are able to shift into paranoid germaphobe mode and enact social distancing to counterplay the disease. If they still get infected after that, it's carelessness, or just being outplayed. Maybe an extra announcement once the virus is eradicated so the round doesn't get slowed down unnecessarily.

2023-11-19 18:16 UTC, ju45he commented
Maybe a nerf in some areas, but breaking into atmospherics and flooding with a gas is much faster, has blame onto the AI instead of you, and is never fully fixed since the shuttle call is practically inevitable. 
Atmos is better at killing a ton of people, virology is more for making people die more slowly while being a slight bit more stealthy.

2023-11-19 18:17 UTC, ChungusGamer666 commented
The justification for removing virology is literallly all skill issues. I can't believe John Doe, the useless assistant, has to rely on other crewmembers for medical help when he gets infected with leprosy! That is so unfair you guys!

2023-11-19 18:20 UTC, Higgin commented
Viro and advanced diseases suck because 

-the counterplay on transmission short of "wear a space suit with internals" is unintuitive as fuck, 
-the frustratingly disruptive or punishingly deadly effects basically continue forever, freely, inflicted by someone you never even saw,
-requiring chemistry to fix, which is pretty much a one-sided operation dependent on medical in the worst cases,
-loading the ability to shit out permutations of diseases onto the station over and over again on a department that might not be there, get blown up, or just not know what the fuck they're doing, with no counter.

Everything that sucks about how you play into viro still sucks with simple diseases even if at smaller scale.

Don't go halfway with this. Take the axe to all of them. 

I may put up an alternative PR that tries to address the problems above when I get home tonight.

If nobody does now, and this gets let through, it's probably not coming back even with a rework. All people will remember is their worst rounds and most frustrating experiences.

The problem being: some degree of frustrating, threatening, impersonal mass death, where your fellow spacemen are more than just possibly evil but may inadvertently threaten you by getting you sick, being on the table - and the cool permutations of healing viruses or weird combos you can come with - are a valuable part of the game's depth and atmosphere.

This is a loss if it gets through, but I can understand why people object.

2023-11-19 18:22 UTC, Dawnseer commented
Have you considered simply... Using the various tools that protect you from disease? Masks and gloves for touch and air transmission? Not walking in knee deep gore all the time and instead, actually getting a janitor to clean it? Not letting Unknown jab you with a syringe for giggles?

2023-11-19 18:23 UTC, ChungusGamer666 commented
> Have you considered simply... Using the various tools that protect you from disease? Masks and gloves for touch and air transmission? Not walking in knee deep gore all the time and instead, actually getting a janitor to clean it? Not letting Unknown jab you with a syringe for giggles?

Nope, according to TG maintainers, seeing someone scratching their skin until it bleeds and coughing is somehow an invisible threat.

2023-11-19 18:24 UTC, DrDiasyl commented
> Maybe a nerf in some areas, but breaking into atmospherics and flooding with a gas is much faster, has blame onto the AI instead of you, and is never fully fixed since the shuttle call is practically inevitable. 
> Atmos is better at killing a ton of people, virology is more for making people die more slowly while being a slight bit more stealthy. 

You can survive the Atmospheric Sabotage by yourself, but with viruses once you're infected- you're doomed.

2023-11-19 18:25 UTC, Dawnseer commented
> You can survive the Atmospheric Sabotage by yourself, but with viruses once you're infected- you're doomed.

That's the case for a lot of things. John Syndicate sleepy penned you? Slit your throat and left your body in a locker in maintenance with no suit on? Woah! Doomed. No counterplay! Better remove traitor.

2023-11-19 18:26 UTC, DrDiasyl commented
> Have you considered simply... Using the various tools that protect you from disease? Masks and gloves for touch and air transmission? Not walking in knee deep gore all the time and instead, actually getting a janitor to clean it? Not letting Unknown jab you with a syringe for giggles?

You usually get infected before you're even acknowledged of virus existence, by some random passer by who happened to "*cough" near you

2023-11-19 18:27 UTC, DrDiasyl commented
> > You can survive the Atmospheric Sabotage by yourself, but with viruses once you're infected- you're doomed.
> 
> That's the case for a lot of things. John Syndicate sleepy penned you? Slit your throat and left your body in a locker in maintenance with no suit on? Woah! Doomed. No counterplay! Better remove traitor.
> 

You can at least robust the John Syndicate in most scenarios, but the only way to win a virus is by praying to Chemical

2023-11-19 18:27 UTC, Dawnseer commented
> You usually get infected before you're even acknowledged of virus existence, by some random passer by who happened to "*cough" near you

And that's when you visit medbay, use the kiosk that lets you find out what the cure is. That, and eat some spaceacilin. Which makes the virus do fuck all to you, makes you not spread it, and go about waiting on or waiting for, a cure.

2023-11-19 18:32 UTC, private-tristan commented
> And that's when you visit medbay, use the kiosk that lets you find out what the cure is. That, and eat some spaceacilin. Which makes the virus do fuck all to you, makes you not spread it, and go about waiting on or waiting for, a cure.

except, that only works if the virus you're infected with doesn't kill you before you can. with some viruses you will literally be critted 1 minute after John Tideman passes you in the hallway and bumps into you (contact transmission).

2023-11-19 18:35 UTC, AdmiralPancakes1 commented
Been a long time coming, this one.

One concern though, won't this also remove being able to make blood with chem factories?

2023-11-19 18:41 UTC, lessthnthree commented
As the person who wrote the current Disease Outbreak: Advanced, even I agree.

For a while I've wanted to redo the event so it's only focused on diseases that have entertainment potential.

There's a place for disease events, but they should be handcrafted strains, not left up to RNG to create hell viruses that just get unleashed.

2023-11-19 18:43 UTC, KingkumaArt commented
> And that's when you visit medbay, use the kiosk that lets you find out what the cure is. That, and eat some spaceacilin. Which makes the virus do fuck all to you, makes you not spread it, and go about waiting on or waiting for, a cure.|

You aren't wrong, but the optimal solution being to "sit and wait for chem to do something" for most crew isn't very engaging nor does it add anything to the round. I feel viro could make a comeback, but it would need an actual use outside of making self resp every round or making fire death virus. Maybe something akin to toxins giving sci points?

2023-11-19 18:56 UTC, jlsnow301 commented
Solo slot machine in a hidden room: The job

2023-11-19 19:13 UTC, Time-Green commented
> Been a long time coming, this one.
> 
> One concern though, won't this also remove being able to make blood with chem factories?

Huh, yeah it does. That's a whole can of worms for another time, I'll fix it

2023-11-19 19:13 UTC, MrStonedOne requested changes
There have been prs that created some of the problems this is complaining about.

__I will not allow a removal to hit the servers until reverting those prs is tried.__

The coderbus trend of ruining game mechanics by merging power creep prs and than removing the entire department because of said powercreep is getting realllllllllllly fucking annoying.

Just revert the power creep prs.

For instance. Viruses used to not be stackable, you could only have 1 advance/custom virus and 1 hardcoded virus. They were made stackable because people kept using this to remove bad viruses by overwriting it with a neutral virus.

Some of the bad symptoms people don't like used to not exist.

The positive symptoms used to be weaker.

2023-11-19 19:14 UTC, softcerv commented
The removal of malicious diseases isn't something that is much of an issue, but the positive symptoms will be sorely missed. Maybe they could be reintegrated into the game somehow later down the line, either through genetics or some other means. Self-resp is really useful, and the other conditional healing symptoms (aside from nocturnal regen/starlight condensation) can lead to interesting gameplay.

>One concern though, won't this also remove being able to make blood with chem factories?

This is a pretty important concern.  The removal of blood duping would end up changing how chemists make chemicals like synthflesh.

2023-11-19 19:18 UTC, DaxDupont commented
Improve, don't remove.

2023-11-19 19:19 UTC, Timberpoes commented
DNM tagged pending someone with a more full care cup than I have sorting MSO's issues out.

2023-11-19 19:22 UTC, Jacquerel commented
> The removal of malicious diseases isn't something that I think many will weep for, but the positive symptoms will be sorely missed. Maybe they could be reintegrated into the game somehow later down the line, either through genetics or some other means. Self-resp is really useful, and the other conditional healing symptoms (aside from nocturnal regen/starlight condensation) can lead to interesting gameplay.

That's certainly the plan, although as we now are not able to merge this PR I am uncertain whether to go through with my PR adding the same thing being simultaneously available from two sources or sit on our hands for two months.

2023-11-19 19:23 UTC, Yobrocharlie commented
![](https://r72.cooltext.com/rendered/cooltext447516848540705.png)

2023-11-19 19:25 UTC, Yobrocharlie commented
![IMG_0072](https://github.com/tgstation/tgstation/assets/126765898/2a32ed53-5dfa-4e07-b210-b216262cedd7)

2023-11-19 19:27 UTC, Yobrocharlie commented
> > You can survive the Atmospheric Sabotage by yourself, but with viruses once you're infected- you're doomed.
> 
> That's the case for a lot of things. John Syndicate sleepy penned you? Slit your throat and left your body in a locker in maintenance with no suit on? Woah! Doomed. No counterplay! Better remove traitor.

You can powergame past the retard pen by carrying multiver right after being penned, that’s why I carry multiver **cause I hate that fucking pen with a burning passion** (and because I always like being at 100% :3)

2023-11-19 19:32 UTC, Time-Green commented
> There have been prs that created some of the problems this is complaining about.
> 
> **I will not allow a removal to hit the servers until reverting those prs is tried.**
> 
> The coderbus trend of ruining game mechanics by merging power creep prs and than removing the entire department because of said powercreep is getting realllllllllllly fucking annoying.
> 
> Just revert the power creep prs.
> 
> For instance. Viruses used to not be stackable, you could only have 1 advance/custom virus and 1 hardcoded virus. They were made stackable because people kept using this to remove bad viruses by overwriting it with a neutral virus.
> 
> Some of the bad symptoms people don't like used to not exist.
> 
> The positive symptoms used to be weaker.
> 
> The rest of the arguments are arguments against a paranoida game, and fall on deaf ears

Even if every one of those "powercreep" PRs over the last 10 years is reverted, what do you have? A job whose job it is to make others sneeze? There is frankly nothing there. You spent 10-30m making a super healing virus, and then your job is complete.

I must also point out that your example of virus stacking can't happen in-game. Virology viruses (and by extension advanced viruses) do not ever stack with themselves. I was referring to virology spreading multiple diseases at once, meaning if you cure one, you'll be immediately infected by the next virus from your surroundings, viruses on your clothes or other people. 

What do you think virology would look like without "powergaming" PRs? As I see it, it is systematically broken, and no single PR is truly to blame

2023-11-19 19:35 UTC, TheVekter commented
I agree with the idea of seeing if we can un-powercreep viro. Worst-case scenario we fart around for a month and Time ends up being right so we just remove it anyway. Best-case we save it as a mechanic, and I don't hate the idea of keeping it.

@MrStonedOne  Would you be okay with a PR _just_ removing Sentient Disease? I feel like its issues (lack of interesting interaction, extremely binary 'feast-or-famine' power level) can't be fixed by fixing the issues plaguing virology.

2023-11-19 19:39 UTC, ChungusGamer666 commented
Patiently waiting for Time-Green to remove cargo because it is a job where you sit around and order guns and to remove xenobiology because it is a job where you sit around and breed gelatinous blobs...

2023-11-19 19:40 UTC, nikothedude commented
> Patiently waiting for Time-Green to remove cargo because it is a job where you sit around and order guns and to remove xenobiology because it is a job where you sit around and breed gelatinous blobs...

dont be mistaken dude xenobio _is_ on the chopping block and has been for a while

2023-11-19 19:40 UTC, SomeoneYouProbablyKnow commented
Virogoly been real silent after this PR dropped

2023-11-19 19:43 UTC, softcerv commented
> > The removal of malicious diseases isn't something that I think many will weep for, but the positive symptoms will be sorely missed. Maybe they could be reintegrated into the game somehow later down the line, either through genetics or some other means. Self-resp is really useful, and the other conditional healing symptoms (aside from nocturnal regen/starlight condensation) can lead to interesting gameplay.
> 
> That's certainly the plan, although as we now are not able to merge this PR I am uncertain whether to go through with my PR adding the same thing being simultaneously available from two sources or sit on our hands for two months.

You could always just work on that and then keep it drafted or ready to release once this whole fiasco is over.  Depending on the source and symptom, I could see things being simultaneously available not being a bad thing.

2023-11-19 19:52 UTC, MrStonedOne commented
> I must also point out that your example of virus stacking can't happen in-game. Virology viruses (and by extension advanced viruses) do not ever stack with themselves. I was referring to virology spreading multiple diseases at once, meaning if you cure one, you'll be immediately infected by the next virus from your surroundings, viruses on your clothes or other people.

The symptoms cap used to be 4, not 8, and it used to be most viruses had one of 6 cures, and it used to be much harder to make spreadable viruses. in fact, when i played viro nearly all healing viruses required direct injection, but i could maybe get that to touch infection if i just forwent a type of healing.

Same for bad viruses. coughing and/or vomiting would make it super easy to cure while taking up a slot. i would often have to do one of the longer and more noticeable harmful symptoms to make up for it. and people would still just be able to cure it with oj.

2023-11-19 19:56 UTC, MrStonedOne commented
>I must also point out that your example of virus stacking can't happen in-game.

i think i was kinda wrong? and that it used to be that viruses would overwrite each other keeping the virus flood from happening?

2023-11-19 19:59 UTC, softcerv commented
> The symptoms cap used to be 4, not 8, and it used to be most viruses had one of 6 cures, and it used to be much harder to make spreadable viruses. in fact, when i played viro nearly all healing viruses required direct injection, but i could maybe get that to touch infection if i just forwent a type of healing.

`#define VIRUS_SYMPTOM_LIMIT 6`
I think the symptom cap for advanced viruses (manmade) are 6 symptoms.

2023-11-19 20:00 UTC, Time-Green commented
> > I must also point out that your example of virus stacking can't happen in-game.
> 
> i think i was kinda wrong? and that it used to be that viruses would overwrite each other keeping the virus flood from happening?

They do overwrite each other, but I'm not entirely sure on their mechanics, just that the end result is still immediate reinfection upon curing by a different disease. This is not really my main problem though, just a symptom (pun) of the way virology is designed (it's not designed)

2023-11-19 20:01 UTC, TheSilverNuke commented
I'm incredibly grateful for MSO's input in this case. It's gratifying to see that the 'remove don't improve' tendencies TG coders tend to have is recognized.

I'll say this much; with how virology is implemented it either steamrolls because everyone competent is dead or it is snuffed out in the early stages of the virus. Viruses will inconvenience everyone for maybe about 10 minutes if you don't take measures to cripple the crew first.

Starting with the Sentient Virus: it's nearly impossible to spread and gain mutations in enough time before a robust chemist main crafts up the two chems needed to snuff you out. Even more so if an existing virologist already spread a virus. Even if said virus has -1000 resistance it doesn't matter. If you don't have any transmission spread or resistance yourself, as you will either be unable to gain an initial host or will get deleted as soon as the one person you can find who is uninfected touches someone.

As an antagonist virologist you have to take extreme measures to attempt to curtail robust chemists or CMO's. If you're lucky and are a traitor you can get a power sink which will drain the entire station, allowing you to spread it further before someone cuts off an APC and cures it anyway. If you aren't a traitor then good fucking luck. Every other antag has to remove the medlathe, the spare board in tech storage, the spare protolathe in the CMO's locker, the holodeck, the sci circuit printer, the engineering circuit printer, the 3 chem dispensers chemistry has, the one botany probably has, and then if not botany then the spare board in tech storage.

TL;DR you have to take extreme measures to avoid your virus getting killed early because otherwise it'll get countered immediately by a CMO or chemist. If you're lucky and these measures are successful or if medical staff lacks robust chemists then you win. But only in those situations.

2023-11-19 20:05 UTC, SomeoneYouProbablyKnow commented
> I'm incredibly grateful for MSO's input in this case. It's gratifying to see that the 'remove don't improve' tendencies TG coders tend to have is recognized.

Me gardening and improving not removing all the weeds. 

> TL;DR you have to take extreme measures to avoid your virus getting killed early because otherwise it'll get countered immediately by a CMO or chemist. If you're lucky and these measures are successful or if medical staff lacks robust chemists then you win. But only in those situations.

The problem here is that while that is true it's not engaging for 90% of the station. It's like successful stealth nuckies. Nuckies get to play mission impossible, 3 random dudes and the cap get to die out of nowhere and the rest of the station gets to "oh well go again"

2023-11-19 20:06 UTC, Zytolg commented
Huh, that's why I'm getting DM's. 
Alright since this ruined my morning, I'm obliged to add in my 2 cents. Here we go.

Virology on tgstation is in what I would call a deprecated state. It hasn't been meaningfully touched in ages, and what does currently exist only provides at best surface level game play. To go into a greater example using xenobiology:
> When you get a lot of dead monkies, eventually you create a perpetual miasma machine and if you breathe that gas, then you're going to get a virus- eventually. At first, it starts off as a nuisance, then it becomes a sort of issue, and then finally by the time you make your way to medbay, you stand a fair chance of actually probably dying if nothing is done. 

There are 2 things you can do about this.
1. Virology takes a blood sample and makes antibodies
2. Chemistry manufactures the virus's cure

You can basically bypass Virology completely and a lot of people do. But if we DO have a virologist, then they can basically play what amounts to be another version of Slimes. It's not engaging gameplay, and you only need 1 person to do it. 

Now, this isn't to say that getting viruses are bad. I like the idea of getting sick, but in its current form, it might be getting in the way a little bit too much of the game. Having to interrupt what you're doing to go and wait 10 minutes for a cure isn't fun. If it were just annoying, that would be one thing, but it can go to deadly fast. Secondly, the actual job mechanics suck and need a revisit like genetics got its rework, but maybe more to it. The ideas and themes are there, but the system sucks. Sentient Disease antag is meh, but still has potential, so I hard disagree with removing that (look into having this be the sole vector of advanced disease traits). Symbiotic Viruses, aka the good heal-y stuff is also a good end goal for virologists, it makes a difference and a good one at that. 
IF the maintainer train decides they don't want it, then I'll fix up Birdshot. If they decide that it needs to stay but in a different form, then I'll still fix up Birdshot. Virology on all stations is large enough to accommodate any change to this island of a mechanic so I don't foresee any problems in regards to that.

Now with my words inputted into the Gitmachine, I'm going to get Brunch.

2023-11-19 20:10 UTC, datorangebottle commented
Power creep really isn't the problem here. Virology has been an unengaging system for years now, and reverting PRs powercreeping it will leave it an unengaging system. 

Scenario 1: Deliberate virologist sabotage.
A player sits in a secure room. They sit there for god knows how long, pushing buttons; there's a significant amount of RNG involved, but they get so many attempts at such high speed that they will eventually succeed. After anywhere from a single minute to upwards of forty, they get to force the entire rest of the crew to not play the game.
What do I mean by this?
The spread of a virus is countered by isolating yourself from people, medication, and vaccines.
This means your options for not catching Lethal Turbo Death Flu are:

- continue working and wait for someone else to do their job (it's almost guaranteed some ass will barge in and get you sick)
- hide and wait for someone else to do their job (you are now playing the waiting room for ss13 instead of ss13)
- sit in medbay and wait for someone else to do their job (see previous statement about the waiting room)
- go out and get one of maybe six biosuits on the station, then do one of the above (extremely risky)
- try to do someone else's job yourself, slowing down the process for everyone else who is doing one of the above

Who is this fun for? The chemist, who has the entire crew breathing down their neck to make some obscure chemical to cure the disease? The crew, who get to sit there randomly burning/sneezing/coughing to death? I don't even see how it's fun for the Virologist, who has to go into hiding while avoiding their own disease.

Scenario 2: Sentient Disease/Random Advanced Disease
The game decides that people are having too much fun playing SS13 today, and spawns a virus, sentient or no. In the case of nonsentient, the virologist's entire job has just been invalidated by a random number generator; he typically can't even cure the virus himself, he mostly relies on chemistry to do it for him.  Once the cure is out, he can distribute the vaccine. That's about where his interaction with this starts and ends.
If it's sentient, now the SD player gets to sit there and wait for people to stand in specific places, while praying that the crew is too incompetent to deal with their bullshit.  Their reward for this? They don't get to interact with anyone outside of the disease mechanics. In a largely social sandbox game. They do get to actually watch the fiasco occurring, which is still an upgrade from Virologist's scenario, but it's largely uninteresting for everyone involved. 
The Disease boredly sits there waiting for someone to stand in front of their host, while praying they don't get countered in some way. They tick boxes in a window, on occasion, but there's no gameplay or roleplaying to be had.
The Virologist waits for chemistry to do their job, or takes over and does it themselves if chemistry is nonfunctional.
The Chemist tabs back and forth between a wiki and the chemp dispenser while annoying assholes shove them around and fuck with the dispenser, making them start over.
The victims suffer, mostly, though some of them try to take it into their own hands and make things worse for everyone.
Nobody wins here. Even if the SD greentexts, they don't win- they just spent a huge amount of time boxed away from the rest of the game they ostensibly wanted to play.

2023-11-19 20:17 UTC, MrStonedOne commented
https://tgstation13.org/wiki/index.php?title=Infections&oldid=12299

- viruses used to require one 1 of 11 chems to cure based purely on resistance level. not one of 40 randomly picked.
- trying to add more than 3 symptoms would sometimes randomly replace one.
- the cap was 6, not 4, but more than 4 was really hard to get because of the above
- there was no way to isolate symptoms
- there was no way to neuter symptoms so you couldn't make your positive viruses better with bad symptoms.
- all positive symptoms had negative resistance such that **eating anything would almost always cure them.**
- spreadability would subtract the num of symptoms (from the wiki this seems to no longer be the case?)
- sneezing was a cheap trick around this, but giving it neg resistance would fix that.

2023-11-19 20:20 UTC, Iamgoofball commented
@MrStonedOne what are your thoughts on putting a different job in place of virology? we've joked about fish doctor in the past but at this point there's enough simple mobs on station to justify an actual Veterinarian job

2023-11-19 20:23 UTC, CPTANT commented
The reasoning here seems to be a balance issue, which can be fixed with balance changes, not removal.

I would like to see the virologist job merged with the doctor job, but for completely other reasons than this PR as I believe the job is too niche.

2023-11-19 20:27 UTC, moocowswag commented
Almost every reason for removing virology would also work for removing toxins, atmos techs, and silicons, being able to indirectly mass kill the entire station with the requirement to survive being items that protect you from atmos and shocks. (and for toxins thats just the aftermath of the explosions)

2023-11-19 20:37 UTC, SomeoneYouProbablyKnow commented
The reasoning is not balance it's design, it's the kind of situations viro creates. 
When an atmos tech plasmafires you get to do something, you run, hide in maints, try to extinguish it etc etc.
When sillicones shock doors you get to do something, throw IDs, disposal yourself, break windows to escape.
When viro makes the virus if you're not medical all you can do is hoard healing items and wait. You can also start avoiding people... that's bad, that's a behaviour we want, i don't think.
Also toxins exists for antags to make bombs. Bombs are funny. That's why it's not catching strays.

2023-11-19 20:43 UTC, Erwbrad commented
## About The Pull Request
 **This PR removes features related to SS13, which are:**
 
 * The Command Department
 * The Security Department
 * The Medical Department
 * The Service Department
 
 **This PR does not remove the following:**
 
 * Virginity of Time-Green
 
 **Related tweaks:**
 
 * Time-Green now has a black boyfriend named Tyrone that creampies him anally
 
 There's a few dead objects, like Time-Green's anus, that I'd prefer to pulverize later for the ease of life. Right now they just exist without purpose.
 
 ## Why It's Good For The Game
 In short:
 
 The entire station's departments sit and do nothing all day like the average SPLURT-station player. Also removing Time-Green would be good for the world, overall.
 
 [This is my full reasoning in hackmd.](https://www.blackpeoplemeet.com/)
 
 Or in a spoiler because I also don't like clicking links
 For mappers/mapping enthousiasts
 Future
 ## Changelog
 🆑 Time-Green, mc-oofert del: The wicked bitch is dead. del: Time-Green (the custom sharted one) is completely removed.
 
 It's ready for review. Even if it's merged without the life changes, Time-Green will just be a dead moron (although I doubt this is going to affect his pathetic lifespan)

2023-11-19 20:44 UTC, Erwbrad commented
> ###
> **[Erwbrad](/Erwbrad) ** commented [Nov 19, 2023](#issuecomment-1817972022)

2023-11-19 20:48 UTC, moocowswag commented
So for atmos you say the counter is...

>hide in maints 

While viro its the exact same thing...

>When viro makes the virus if you're not medical all you can do is hoard healing items and wait..

Also that is just plain not true go to holodeck and set it to emergency medbay tf???

>Bombs are funny. That's why it's not catching strays

sneeze viruses that knock you back are funny...

2023-11-19 20:54 UTC, SomeoneYouProbablyKnow commented
> While viro its the exact same thing...

The core difference is during a plasmaflood other people are hiding in maints and you might try to survive together.
During an outbreak you'll stay away from each other, making the interaction less fun.

> sneeze viruses that knock you back are funny...

True.  Not AS funny as bombs tho. Most of them get old fast. 

> Also that is just plain not true go to holodeck and set it to emergency medbay

Funnily enough that doesn't happen, people just... don't. And they are the ones you are designing for, not yourself who'd go to holodeck, not me who's built different and wouldn't get sick but the majority of players.
They should go to the holodeck yea but as is they stand in front of medbay and die.

2023-11-19 20:57 UTC, moocowswag commented
> Funnily enough that doesn't happen, people just... don't. And they are the ones you are designing for, not yourself who'd go to holodeck

I dont go to holodeck i build my own chemistry station.

people having access to counterplay and instead just afking shouldnt be something we design around yet apparently we cant get enough of that. cult has an overbloated kit simply because half of the converts just sit in the base ssd

2023-11-19 21:05 UTC, SomeoneYouProbablyKnow commented
> people having access to counterplay and instead just afking shouldnt be something we design around yet apparently we cant get enough of that.

i mean... that's what game design is? Not afking but if your players feel so hopeless they afk with a counter in the game you fucked up somewhere.
Yeah fuck cult tho. Although i'm like 90% sure it was created like that. A bloated abomination. 

> Ive literally worked together with other uninfected people during a virus outbreak as nonmedical staff to help make a cure in maintenance before....

Based. I remember we bolted down cargo and did not let anyone in. While the station was dying to some fucked up virus we just chilled.

Fun stuff like that CAN happen but our goal here is to increase how common based stuff like that is.

2023-11-19 21:19 UTC, moocowswag commented
The solution is that viruses are instantly spread from a single contact instance and doesn't need to overwhelm anyones immune system, it should be a formula taking into account of how healthy a spaceman and how many times something has recently tried to infect them and weakened their immune system as a result.

Basically immune system magic hp number boosted by good things and slowly tries to regenerate to a magic number.

infection attempts lower this number until infection attempt passes.

This way you dont instantly get a virus from some shitter running up to you and coughing on you and if they are persistently staying close to you, you beat their ass with a blunt weapon (no blood spreading) or shove and run away.

2023-11-19 21:25 UTC, SomeoneYouProbablyKnow commented
> The fact that you can be INSTANTLY infected and your immune system can be INSTANTLY overwhelmed by the smallest wiff of someone that ran onto your screen and into you within a single second is the mistake YOU CANT EVEN LOOK AT SOMEONE WITH EXAMINE IN THAT TIME FRAME

The fact that we have unreasonably fast movement speed is NOT helping. It takes like 20 seconds for a dude to run out of medbay and be halfway across the station infecting engineering

2023-11-19 21:29 UTC, wesoda25 commented
> @MrStonedOne what are your thoughts on putting a different job in place of virology? we've joked about fish doctor in the past but at this point there's enough basic mobs on station that belong to crew and heads of staff to justify an actual Veterinarian job

if we do this route ill code a space rabies random event and tie it into vet content

2023-11-19 21:32 UTC, moocowswag commented
To get into more detail about the infection attempts


It would probably be transmission strength or a new virus stat that impacts the virus's ability to fight someones immune system.

Infections via blood contact and contaminated food (if we support that) would obviously be the highest density infections and would be a 1.0 multipliar of the infection strength stat vs the infectee's  immune system to see if the infection passes.

Infections via skin contact would be like 0.5-0.75 of the infection strength stat

Passive air transmission would be the lowest density of like 0.1-0.2 strength although coughing and sneezing could be much higher.

Someones immune system could be boosted by things like a combination of your mood (yes someones mood does impact their immune system and health) and just generally not being a beat up person with 20+ damage to most of their limbs. (Also sepsis/burn wounds would obviously tank your immune system's defense stat)

2023-11-19 21:46 UTC, moocowswag commented
This solution would also make virologists trying to infect the entire station more involved, they would likely need a good chem grenade with foam or smoke spreading their virus to get several high dosage infection attempts on a crowd of people and that crowd of people wouldnt no longer need a single person to run laps around the station to spread their infection , everyone would have to.

2023-11-19 21:47 UTC, CliffracerX commented
Throwing in my $0.02 here, starting with a TL;DR: improve, don't remove.  Viruses as a concept are great on paper & the game *is lesser* without them as part of its larger atmosphere of "everything can kill you, even a hug from your best friend" - but virology as a job is in a pretty poor place, being entirely "press the RNG button until you get the output you want" & leaving you a glorified M.D. or Chemist without the status or access of either once you've finished with beneficial viruses/successfully helped cure a negative virus.

To that end, what Virology needs is probably killing the Virologist as a job (although their drip should stay, both for style reasons & so people can gear up if they want to go into Virology) and letting MDs & maybe Chemists access Virology in their place; gives them more things to do in-between patching up Joe Spacetider or John Secoff, and means that when the need *for* virologists has passed, they can fully return to their regular job without issue.  Following that, a rework to the Virology *mechanics* so that making viruses - be they beneficial *or* dangerous - is more interesting.

For *that*, I'd look to Genetics for both theme & the basics of the UI; giving viruses a genome that you can sequence to *discover* symptoms *and* change their strengths, weaknesses, and indeed functionality; each would-be symptom having a chunk of the sequence, with part of it dedicated to what symptom it is (or if it's simply garbled), then random pairs that could buff/debuff specific stats for the virus (e.g, resistance, stealth) depending on if you set them correct, as well as a random pair that can neuter the symptom whilst retaining its symptom modifiers.  If you just want to make a quick Self-Resp, all you need to do is discover the symptom with a little bit of tinkering - but if you want to make an advanced healing virus, you'll need to take the time to discover the buff/debuff pairs and neuter dangerous symptoms as before, but this time instead of having to spam tiny doses of chems on blood bottles (and go beg the chemists/coroner for more when you run out), everything is in a centralized UI and tools like the Joker could help you discover the stat/neutering pairs.

You could even go a step further and make different viral bases (e.g, the cold/flu is *not* the same as an advanced version of fungal TB would be is not the same as a base that can infect *plasmamen*) that impact how it can be transmitted, how many sequences you have to work with (thus limiting symptom count), the *length* of its sequences (adding more stat pairs but making it harder to find the ones you want), its base stats, *and* the layout of its DNA - picking the right base for the job becomes a large part of the virus-making process; Can it affect the majority of the crew?  Does it have enough symptoms for the effects you want?  Will its base stats & stat-pair count give you enough room to buff the stats you need for best effectiveness?  Will chugging Starkist cure it because it traded symptom count for resistance & most anything that could boost your immune system nukes it?

All of this would come together to be a rework to the experience that makes it more engaging to play with for the ones *making* viruses, and by putting more focus on trade-offs in the process, you *can't* just make an impossible kill-virus without also making it so weak that chugging OJ or Spaceacillin will nuke it from orbit & grant immunity.  If you went a step further and added some basic immunity simulation per the other comments, it adds even more layers of content for *fighting* viruses- and if you integrated viral bases into that process (e.g, once you've recovered from something based on a cold/flu virion, it's easier to fight off future infections from other cold/flu-based viruses) the layers continue to grow.

All of this can still more or less *work* with the current system for handling advanced viruses, with the tools for building the new virus sequencer being there via Genetics, and things like immunity needing a new subsystem & some datums for carbons to handle their immune system.  Simply nuking it all means that whoever wants to try and implement a rework like this now has to reinvent the wheel for how viruses work & rebuild all from scratch, all the while Virology remains a dead zone where sad medical players twiddle their thumbs and reminisce of better times.

2023-11-19 21:56 UTC, KingkumaArt commented
> The issue is that viruses are instantly spread from a single contact instance and doesn't need to overwhelm anyones immune system, it should be a formula taking into account of how healthy a spaceman is and how many times something has recently tried to infect them and weakened their immune system as a result.

I do worry that you could make an ultra weak but subtle virus that doesnt show many symptoms to weaken the crew's immune system, and then 5 min later follow up with the blind+burning death virus in a sort of wombo combo. I'm still in the "remove it" camp (though theres nothing stopping the job/code being stored somewhere for future reference.) That said, if anyone has a concept to make non-antag virology actually serve more of a purpose than making a selfresp+regen coma and then becoming a MD after 20 minutes, I can see myself switching to the "improve" camp

2023-11-19 21:57 UTC, SomeoneYouProbablyKnow commented
nah man that's way more than 0.02 $. Time to get my reading glasses.
But before that "improve don't remove" isn't an axiom. Sometimes the best improvement you can make is to remove something that's not helping the overwhole loop. Is this such a case? debateble, but i'm tired of TG people reacting to "removal" like vampires to a cross.

2023-11-19 22:10 UTC, SomeoneYouProbablyKnow commented
> part of its larger atmosphere of "everything can kill you, even a hug from your best friend"

Up to a point. You don't want people scared of standing next to a wall...

> but this time instead of having to spam tiny doses of chems on blood bottles (and go beg the chemists/coroner for more when you run out), everything is in a centralized UI and tools like the Joker could help you discover the stat/neutering pairs.

Genetics is also not that great. It's an okay minigame but it will get stale without more variables (read : other players) involved

> All of this would come together to be a rework to the experience that makes it more engaging to play with for the ones making viruses

The issue is not just the virolgy experience, it's how the crew experiences it as well.

> Simply nuking it all means that whoever wants to try and implement a rework like this now has to reinvent the wheel for how viruses work & rebuild all from scratch, all the while Virology remains a dead zone where sad medical players twiddle their thumbs and reminisce of better times.

If you made a square wheel you should try and reinvent that. Fully nuking it would affort more freedom to anyone making new virology (the freedom to make it an RnD job).
Amd it's not like there's nothing to do in medical without viruses it's like
70% combat injuries
10% pandemics
20 % being exploded
100% tram injuries

2023-11-19 22:12 UTC, ATH1909 commented
@MrStonedOne 

Viro semi-expert here:

> * trying to add more than 3 symptoms would sometimes randomly replace one.
> * the cap was 6, not 4, but more than 4 was really hard to get because of the above

I was the guy who removed that and made the cap always 6. This was just tedium, not an actual balancing factor.

How the system used to work was that every time you altered a virus, its symptom cap would become a random number between 4 and 6. If that number was less than your current symptom count, symptoms would be randomly removed until it was below the cap. This did not actually meaningfully influence the viro meta, as if you wanted a virus with symptoms A, B, C, D, E, and F, you could simply:
1. Make a virus with symptoms A, B, C, and D.
2. Make a virus with symptoms A, E, and F.
3. Repeatedly mix samples of those two viruses until they became a virus with a symptom cap of 6 (with symptoms A, B, C, D, E, and F).

It was just an extra, unintuitive knowledge barrier, and I stand by my decision to remove it in https://github.com/tgstation/tgstation/pull/53879.

> there was no way to neuter symptoms so you couldn't make your positive viruses better with bad symptoms.

So... what're viros supposed to make, then? People will lynch you if you put anything remotely resembling a downside into your self-spreading virus; I've had doctors unironically get mad at me for putting self-resp in my virus bc it preventing them from being able to do CPR. Stats don't really matter on positive viruses, so under your proposed no neutering environment, people would just... slap 6 good symptoms into one virus and ignore any further optimization/deeper planning. Our threshold system, for example, would be pretty much impossible to interact with.

> * spreadability would subtract the num of symptoms (from the wiki this seems to no longer be the case?)

I was also the guy who changed this (**and adjusted the transmission thresholds to compensate**). This... doesn't really have a meaningful impact, since you're always going to go for a 6 symptom virus if you can and any 5 symptom virus would still be improved by adding a symptom that gives a good chunk of stats, including transmission. The previous system heavily encouraged viros to either pump transmission really high or dump it, with no in-between; a virus with -8 transmission and a virus with 8 transmission would have the exact same list of transmission vectors. You can see more information here: https://github.com/tgstation/tgstation/pull/46730.

None of the reverts you've proposed here would actually fix any of the core, fundamental problems with virology that Time-Green has brought up.

2023-11-19 22:23 UTC, ATH1909 commented
> I don't even see how it's fun for the Virologist, who has to go into hiding while avoiding their own disease.

The viro here doesn't actually have to avoid their own disease; they know the cure already, so they can just make it for themselves before sabotaging all of the P.A.N.D.E.M.I.C.s/chem equipment and releasing the virus.

> In the case of nonsentient, the virologist's entire job has just been invalidated by a random number generator; he typically can't even cure the virus himself, he mostly relies on chemistry to do it for him. 

Technically, the viro can create an anti-virus virus by just adding 5 1u doses of virus food to a bottle of sneezing or coughing, then adding several drops of formaldehyde to neuter all of that virus's symptoms. The result is a virus with monstrous stats that pretty much no random virus or sentience disease can contest and which will swiftly overwrite them (due to its high transmission and airborne spread) and resist being overwritten (due to its high res).

That said, yeah, outside of that trick, viros ironically are very dependent on chemists for curing viruses.



> The Disease boredly sits there waiting for someone to stand in front of their host, while praying they don't get countered in some way. They tick boxes in a window, on occasion, but there's no gameplay or roleplaying to be had.

Hot take: sentient disease gameplay would be immensely improved if they had the ability to mind control their hosts (as in, directly assuming control, not brainwashing). Mind control was a very interesting power that sadly wasn't explored much by hivemind because of the existence of funny pink man, but I think it'd be really cool in the hands of sentient diseases, as they'd actually be able to communicate with their hosts and interfere with the process for curing them.

It... could also just result in a sentient disease playing like a normal murderboner who has free respawns, though. Hm.

2023-11-19 22:25 UTC, Autisem commented
>     * spreadability would subtract the num of symptoms (from the wiki this seems to no longer be the case?)

If I recall this now effects stealth instead but it may actuely still effect both. but im not certain

2023-11-19 22:25 UTC, ATH1909 commented
> > ```
> > * spreadability would subtract the num of symptoms (from the wiki this seems to no longer be the case?)
> > ```
> 
> If I recall this now effects stealth instead but it may actuely still effect both. but im not certain

No.

2023-11-19 23:29 UTC, MrStonedOne commented
> @MrStonedOne

> I was the guy who removed that and made the cap always 6. This was just tedium, not an actual balancing factor.


based on the merged pr list, cap is 8 right now. unless the pr to raise it to 8 was reverted

2023-11-19 23:50 UTC, softcerv commented
> > @MrStonedOne
> 
> > I was the guy who removed that and made the cap always 6. This was just tedium, not an actual balancing factor.
> 
> based on the merged pr list, cap is 8 right now. unless the pr to raise it to 8 was reverted

Check [the disease define file](https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/diseases.dm), the define `VIRUS_SYMPTOM_LIMIT`, which controls the maximum amount of symptoms a disease can have, is currently set to `6`

2023-11-20 03:00 UTC, YakumoChen commented
> > > I suppose it's worth asking: would removing the good kill symptoms (autophago, ARDS, alkali) be enough? if the doomviruses are inconveniencing you instead of killing you in ~2 minutes, that sounds much more palatable.
> > 
> > 
> > No, I don´t think reconsiliation is possible anymore. Virologies job is spreading diseases, it´s inherently problematic. Even if every lethal and annoying symptom is removed, we´re still left with what can barely be considered a job with questionable round influence. I'd rather see it removed and completely redone than leave it neutered and useless to the point where nobody is interested in touching it
> 
> I don't think that nobody would interested if negative symptoms were removed; I play on a downstream where players aren't allowed to make harmful viruses and virology is full up nearly every round.

global buffs that make the crew near-unkillable because someone did their job for 20 minutes is not, in fact, interesting or balanced gameplay. We already had that tried out with nanites. 

Especially on a server that bans virology from being antag, that makes it even less interesting or, as the game is supposed to embody, paranoid.

2023-11-20 04:23 UTC, 567Turtle commented
Improve don't remove

2023-11-20 04:51 UTC, ZephyrTFA approved these changes
virology was never a good department to begin with imo, we removed nanites for basically the same reason

2023-11-20 05:05 UTC, Deultus commented
replace virology with fishing

2023-11-20 05:24 UTC, Time-Green commented
> replace virology with fishing

This is what’s been done with syndicate lavabase virology

2023-11-20 06:12 UTC, EricZilla commented
I think it would be cool if the health scanners didn't instantly tell you the cure to the disease, and there was some sort of symptom based process for curing stuff, maybe have a random chem act as not a cure but a medicine to slow the growth of the virus, while the virologist has to work with a few sick people to figure out what their current list of symptoms is, then create a cure based on the total symptoms.
Like say each symptom had its own chem, some sharing the same one like cough and sneeze could both be orange juice, and the cure requires you to make a tonic that has every symptom chem together and drink that.

Another thought is, Viro and Chemist have so much overlap they really should be the same job, so why not merge them into a pharmacist?

2023-11-20 06:18 UTC, imsxz commented
only a few more departments to remove before ss13 is perfect

2023-11-20 10:27 UTC, MTandi commented
The random diseases from rotting gibs must stay, it's cool that having rotting flesh in the halls has drawbacks and someone should actually bother cleaning it. I've never seen these viruses being lethal.

Just remove the job, and symptom mutation mechanic with reagents. On the maps it can be an abandoned department until the moment when we rework it for something better.

2023-11-20 12:03 UTC, Leviathan21 commented
someone got owned

2023-11-20 12:04 UTC, SinfulBliss commented
A job doesn’t need to be good for roleplay to be a good job. Also doesn’t need to have a mountain of content to be a good job.

It’s okay for a job to just be something players try out for a couple dozen hours, learn, then leave. The concept of having viruses in the game, which can even be tinkered and worked on a micro level, is a cool concept and worth preserving. Even if the gameplay itself isn’t mechanically fun, the results or concept can make it fun, see genetics, chemistry, xenobio, etc.

It‘s throwing out the baby with the bathwater to completely remove the department instead of trying to fix the issues you see in it, especially when all of the issues in the “why it’s good for the game” section are issues not with the Virology Department itself but with infections, which can nerfed trivially.

2023-11-20 12:11 UTC, Exester509 commented
This is a good PR, not only allowing people to re-implement virology in a completely new way instead of trying to keep a messy system, but introducing the fearsome Syndicate Fish Division.
I can't think of a single drawback to merging this

2023-11-20 12:16 UTC, SomeoneYouProbablyKnow commented
> It’s okay for a job to just be something players try out for a couple dozen hours, learn, then leave. 

We have a solution for that. Like what we have with toxins, toxins is not a job it's a thing in RnD scientists can do. Virology the job doesn't need to exist. (By that logic chemist should also be removed, which is right, fuck the chemist job)

> It‘s throwing out the baby with the bathwater to completely remove the department instead of trying to fix the issues you see in it, 

Keeping virology is like taking half a course of a antibiotics and then stopping once you feel better. (PSA : take the full prescribed course)

> especially when all of the issues in the “why it’s good for the game” section are issues not with the Virology Department itself but with infections, which can nerfed trivially.

The issues are not with the department (why do people keep calling it that it's a single job??) nor is it with infections it's with the system and the gameplay loop of virology (mostly on the reciving end of it)

2023-11-20 13:05 UTC, mc-oofert commented
![68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f333233343938372f31383833393439383037352f6d2f5f6d6170735f52616e646f6d5275696e735f4c6176615275696e735f](https://github.com/tgstation/tgstation/assets/70376633/6fc9b590-dfd6-4f7b-bac3-994c1b53bbc1)

2023-11-20 13:10 UTC, SomeoneYouProbablyKnow commented
Cayenne lore!!!!! Finally

2023-11-20 16:45 UTC, HalfPunch commented
> Just remove the job, and symptom mutation mechanic with reagents.

We still need blood duplication reaction for some advanced plumbing factories

2023-11-20 16:51 UTC, Time-Green commented
> > Just remove the job, and symptom mutation mechanic with reagents.
> 
> We still need blood duplication reaction for some advanced plumbing factories

I made sure to specifically keep that in while removing the rest

2023-11-20 18:27 UTC, Nabski89 commented
If we can have jobs like Coroner and psychologist, why does virologist have to get axed as a job. Please don't do that it will make me sad.

"We've had virology for at least 11 years, and no one ever bothered to change virology" This is a lie.

2023-11-20 19:01 UTC, Autisem commented
You could port some viro stuff from bee, it got some nice changes there

2023-11-20 19:07 UTC, cnleth commented
> You could port some viro stuff from bee, it got some nice changes there

Virology is also in the process of being removed on bee right now https://github.com/BeeStation/BeeStation-Hornet/pull/10153

2023-11-20 19:24 UTC, Exester509 commented
> If we can have jobs like Coroner and psychologist, why does virologist have to get axed as a job. Please don't do that it will make me sad.
> 
> "We've had virology for at least 11 years, and no one ever bothered to change virology" This is a lie.

One could argue that Coroner and Psychologist are more RP-focused jobs like Lawyer, Prisoner, or Curator to an extent.

Virologist, however, involves pretty much locking yourself in your dungeon for half the round to either:
A. Release a bioweapon that will start exterminating everything on the station
B. Release a helpful virus that will give everyone superpowers

2023-11-20 19:27 UTC, SomeoneYouProbablyKnow commented
> One could argue that Coroner and Psychologist are more RP-focused jobs 

Coroner less so but also the general consensus is that it's not good. But even then it's not as disruptive as viro.

It's weird how viro is a whole seperate job and not just under general medical purview. Kinda like toxins in RnD

2023-11-20 20:21 UTC, DanielSchmitz1 commented
Waiting for Time-Green to remove cargo and xenobiology because they're also jobs where you wait around and push buttons

2023-11-20 23:10 UTC, ophaq commented
Someday the game will be played as its intended purpose: assistants vs the security department. There will be no other department, just greyshirts and redshirts. /s

On a serious note, I don't like removing virology entirely. Reworking disease stacking such as implementing "similar diseases" to be cured by the same antibody type could be a thing. Sentient disease needs an entire rework as a lot of its symptom stats don't even match current ones and its basically a "rush to cure" upon seeing it antag. I would like diseases to be added to maint pills, like on monkestation so that we can get fungal TB in maint pills that kill half the station. That would be fun.

2023-11-20 23:14 UTC, Loafin34 commented
i'm all for removing virology. the purpose of it is to be a bane upon the station, which makes it suitable for pirates or nukies, but not when there's some bored crewmember deciding to ruin everyone's day. Why would space stations require virology as a wing in medbay, when the entire way to 'cure' viruses is through chemistry? it's just a dumb system that gives nothing to the virologist, and provides no engagement for the station. You can't do gimmicks with harmless virology viruses, and the beneficial viruses are garbage, as nobody really wants them. The purpose of virology is to hard-counter sentient diseases, and spread their own viruses. there is no interactivity with other departments, it's bad, and I want it gone

2023-11-21 00:22 UTC, YakumoChen commented
would like to see it replaced with /vg/ virology down the line, they actually have interesting content and virus cures aren't chemistry-related (one of the ways to cure a virus is to set the patient on fire until the disease is literally cooked out)

2023-11-21 06:56 UTC, SomeoneYouProbablyKnow commented
> (one of the ways to cure a virus is to set the patient on fire until the disease is literally cooked out)

Fun Fact : That's what a fever is, your own body heating itself up in an attempt to cook the infection before it cooks you

2023-11-23 23:34 UTC, Higgin commented
Warning: Parasite detected
Name: Carpellosis.
Type: .
Stage: 5/5.
Possible Cure: Carpet

might've lost the parent on type for display name

2023-11-29 01:19 UTC, deathrobotpunch commented
that is true

2023-12-07 05:46 UTC, san7890 commented
it's been dnm for three weeks (and also just staled out i don't know why the label was removed there has been no commits on this PR for two weeks) and MSO is okay with removing the job virologist but not much else (e.g. advanced virus content).

i think the discourse on this PR has been mainly coursed around removing _everything_- it would be in everyone's best interest that if/when/should someone finally muster up the willpower to remove the job virologist + defend their changes it should be on a clean slate rather than have someone have to click on 80 different "hidden message" chains about something that isn't relevant anymore.

i would like to see the new virus framework play out more before i become supportive of removing the job virologist (virology the department would still be there and open to all medical doctors for access) but i'm calling it a hung PR.

2023-12-07 05:46 UTC, closed without merging

2023-12-07 05:49 UTC, Time-Green commented
> it's been dnm for three weeks (and also just staled out i don't know why the label was removed: there have been no commits on this PR for two weeks) and MSO is okay with removing the job virologist but not much else (e.g. advanced virus content).
> 
> i think the discourse on this PR has been mainly coursed around removing _everything_- it would be in everyone's best interest that if/when/should someone finally muster up the willpower to remove the job virologist + defend their changes it should be on a clean slate rather than have someone have to click on 80 different "hidden message" chains about something that isn't relevant anymore (as well as all the clutter from deleted messages).
> 
> i would like to see the new virus framework play out more before i become supportive of removing the job virologist (virology the department would still be there and open to all medical doctors for access) but i'm calling it a hung PR.

See you next month