Poly speech/memory fix.
tgstation/tgstation pull request #79851
Opened 2023-11-19 19:23 UTC by shwb1

## About The Pull Request
Simple fix for Poly's AI, Read Memory was returning null into a list used for Poly's speech causing a stack error. I changed the returned value to the empty returnable list to negate this problem.

Fix of: #79844

First time making a pull request on github, please bear with me if i make any mistakes.

## Why It's Good For The Game
Less errors on the servers side. Probably saving the headache of debugging from some other poor soul.

2023-11-19 20:35 UTC, san7890 requested changes
Thanks! There is one thing we should do to make this more explicit since we aren't modifying `returnable_list` beforehand just to make it very obvious that we are returning an empty list.

That's really strange how the langserver didnt' catch it, I was under the impression that `RETURN_TYPE(/list)` would lint it somehow

2023-11-19 20:35 UTC, san7890 commented on code/modules/mob/living/basic/pets/parrot/poly.dm
> +			return returnable_list
```suggestion
			return list()
```

2023-11-20 02:53 UTC, SyncIt21 commented
Thanks, make sure to link the issue properly in your PR body . Type

> Fixes #79844

And not

>Fix of #79844

2023-11-20 17:22 UTC, SyncIt21 commented
> Fixes: https://github.com/tgstation/tgstation/issues/79844, https://github.com/tgstation/tgstation/issues/79859

This won't work you should add them as separate lines like so

> Fixes #79844
> Fixes #79859

> about syncing that won't add blank commits/ force a check every time?

It's fine, whenever you make a commit tests will run, it's not under your control, merging with master is by default a blank commit and not an error so it's all good on your end.

2023-11-20 17:33 UTC, shwb1 commented
Updated. And thanks for the info!

2023-11-21 01:17 UTC, merged