Fixes cyborged heretics seeing influences
tgstation/tgstation pull request #79868
Opened 2023-11-20 19:16 UTC by SuperNovaa41

## About The Pull Request

They simply weren't being removed from the influence list

Fixes https://github.com/tgstation/tgstation/issues/79510

## Why It's Good For The Game

cyborgs aren't supposed to see these things

## Changelog

:cl:
fix: Fixes cyborged heretics seeing influences.
/:cl:

2023-11-20 20:05 UTC, Time-Green commented
I thought it was pretty cool tbh, a fragment of their old lives

2023-11-21 18:23 UTC, MrMelbert commented
> If the cyborg then gets deconstructed, and the brain placed back into a human body, will they regain the ability to see influence? Because I'm pretty sure they'll still have all the other heretic abilities.

not in the current implementation of this pr

2023-11-21 20:23 UTC, AtomTheProphet commented
> > If the cyborg then gets deconstructed, and the brain placed back into a human body, will they regain the ability to see influence? Because I'm pretty sure they'll still have all the other heretic abilities.
> 
> not in the current implementation of this pr

That seems like an issue that needs to be fixed.

2023-11-21 22:23 UTC, Ghommie requested changes
Make sure that they can see the influences once again if un-borged.

2023-11-21 22:27 UTC, GPeckman commented
> not in the current implementation of this pr

I kinda feel like the PR is fundamentally flawed, then. Borging does not and should not remove antag datums, but being able to see influences does really seem like it should be tied to heretic antag datum.

2023-11-23 04:58 UTC, SuperNovaa41 commented
Sure

2023-11-23 09:48 UTC, MrMelbert commented
if you want an easy solution, just hide them in heretic `apply_innate_affects` if current `issilicon`, and don't if not

2023-11-25 05:37 UTC, merged