[prototype only] ports vite
tgstation/tgstation pull request #79875
Opened 2023-11-21 02:29 UTC by jlsnow301

## About The Pull Request
don't mind the tremendous file diff, vite doesn't like jsx files as .js. Huge number of renames here

## Why It's Good For The Game
Catapults tgui build tools into 2023. Significantly faster

## Changelog

N/A

2023-11-21 03:35 UTC, Mothblocks commented
Let's split js -> jsx into its own PR.

1. If this PR doesn't work out, we will want that regardless
2. It makes reading this PR significantly easier

2023-11-22 15:50 UTC, MrStonedOne commented
Would you mind explaining wtf vite is in the pr body?

2023-11-22 15:51 UTC, MrStonedOne commented
Also you can not use age, "legacy" or "modern" to justify a change. you have to actually spell out why it its better besides "its newer"

2023-11-22 15:52 UTC, MrStonedOne commented on dependencies.sh
> +export NODE_VERSION_PRECISE=20.9.0
Node has to be be version 14 for windows 7 reasons.

2023-11-22 16:00 UTC, MrStonedOne requested changes
vite dropped support for node 14 and 15 in version 3.0 and node 14 is the highest we can go to and still support windows 7. (maybe node 15 but it requires some hacks.)

Until the client and all dev tools work on linux this PR is dead on arrival unless you want to make it work with vite 2

2023-11-22 19:50 UTC, jlsnow301 commented
> Would you mind explaining wtf vite is in the pr body?
> Also you can not use age, "legacy" or "modern" to justify a change. you have to actually spell out why it its better besides "its newer"

sure thing mso


<details>
<summary>what the fuck is vite</summary>

vite is a newer build tool that is written in Go. it yields significant performance gains over webpack. for instance, over the traditional react application (create-react-app), it shaves dev build speed from ~13 seconds down to sub-second times. it's so fast that it started a war to create the fastest build tools for web dev. even the creator of webpack chimed in to write turbopack in rust. vite basically deprecated create-react-app as the web standard for scaffolding react applications within a week.

outside of performance, its all-inclusive architecture means that we no longer have to include babel, webpack, and all of its plugins. the config file is stupidly easy and its polyfills for ie11 are managed within @vitejs/plugin-legacy. 

</details>

2023-11-22 22:02 UTC, jlsnow301 commented
i might have something that works with both

2023-11-22 22:02 UTC, closed without merging