Fixes? / Removes stagger shoving animation on corpses.
tgstation/tgstation pull request #79985
Opened 2023-11-27 19:58 UTC by Higgin

## About The Pull Request

Appears to have been intended, but I'm guessing its scale and time were not. 

## Why It's Good For The Game

Shoving dead bodies was causing them to spasm for longer than described and frankly made it obnoxious both judging whether or not you were dealing with a dead body and clicking on them after doing it (which should probably be redundant with a dead body.)

## Changelog

:cl:
del: Stagger animation no longer fires longer than it should on dead bodies or on dead bodies period.
/:cl:

2023-11-29 20:45 UTC, SuperNovaa41 commented
Not sure why your tests are failing, I'll try rerunning them

2023-11-30 23:51 UTC, Ghommie requested changes

2023-11-30 23:51 UTC, Ghommie commented on code/datums/status_effects/debuffs/staggered.dm
> +		return FALSE
```suggestion
```
Add a condition to the `/tick` proc so that the mob doesn't do the stagger animation when dead instead.

2023-11-30 23:51 UTC, Ghommie commented on code/datums/status_effects/debuffs/staggered.dm
>  	if(owner.stat == DEAD)
```suggestion
	//you can't stagger the dead.
	if(owner.stat == DEAD)
```
Keep the comment.

2023-12-01 05:27 UTC, Higgin commented
Trying this out! Thank you for the suggestions!

2023-12-02 22:01 UTC, Ghommie commented
You haven't done what was asked yet. Also, on second thought, it should be a `if(owner.stat == DEAD || HAS_TRAIT(owner, TRAIT_FAKEDEATH))` check, not just a `if(owner.stat == DEAD)` one.

2023-12-06 03:11 UTC, Higgin commented
> You haven't done what was asked yet. Also, on second thought, it should be a `if(owner.stat == DEAD || HAS_TRAIT(owner, TRAIT_FAKEDEATH))` check, not just a `if(owner.stat == DEAD)` one.

Should actually be good now. I put it in the /tick and in the on_apply for the odd edge case I can imagine where somebody might die mid-effect and still be wobbling around. Is that prudent or unnecessary here?

2023-12-06 03:57 UTC, merged