Ventcrawling mobs now get a warning when crawling into hazardous pipenets
tgstation/tgstation pull request #80496
Opened 2023-12-21 18:15 UTC by Rhials

## About The Pull Request

Attempting to ventcrawl into a pipenet full of harmful air (above/below the heat/cold temp thresholds of your mob) will give a pop-up warning.

![image](https://github.com/tgstation/tgstation/assets/28870487/062fb219-7c1f-4d59-afb8-355f6d48f4d8)

It's a bit blunt, but it works. Maybe giving the exact temperature is a bit much, idk. I might change it.

## Why It's Good For The Game

Handles yet another way that xenos (and other ventcrawlers) can accidentally throw their roll while ventcrawling.

Dying without warning sucks, doubly so when your body then gets stuck in a pipe! Lame!

## Changelog

:cl: Rhials
qol: Attempting to ventcrawl into a pipe with hazardous air will give a pop-up warning and the option to confirm entry.
/:cl:

2023-12-21 18:37 UTC, SyncIt21 commented
But why even show a alert? Most players will select "No" and save themselves so might as well prevent ventcrawling entirely if conditions are hazardous.

2023-12-21 18:39 UTC, DaCoolBoss commented
Needs to check pressure too. Pressure damage is more common than temperature damage when vent crawling.

2023-12-21 19:36 UTC, MrMelbert requested changes

2023-12-21 19:36 UTC, MrMelbert commented on code/modules/mob/living/ventcrawling.dm
> +					return
You will require sanity checks after this alert, otherwise you can input stall to enter the vent from the opposite side of the map.

2023-12-21 20:00 UTC, Livrah commented
I bet this pop up would kill more than ticking dmg (with hud indicators of it)

2023-12-21 21:12 UTC, MrMelbert commented
I imagine we can just change the "you start crawling into the vent" text to "as you crawl into the vent, you feel a very hot breeze come out" and make it danger text or w/e

2023-12-21 22:25 UTC, LemonInTheDark commented
Do we want to protect people from this so... bluntly?
Feels kinda garbage ngl. Just asking people "are you sure you wanna die" seems like a shit pattern.

2023-12-22 00:56 UTC, Deadgebert commented
I think a forced stop prompt is a bad, but I love the idea. 

There is already a vent crawl timer, maybe tack on a big, red, and bold warning message in chat instead and leave it up to the user. There are a lot of reasons to take the chip damage over an unfavorable fight and if you're forced to stop and click OK, you're going to be at a greater disadvantage.

2023-12-22 17:49 UTC, Rhials commented
> Needs to check pressure too. Pressure damage is more common than temperature damage when vent crawling.

Good catch, will do.

> I bet this pop up would kill more than ticking dmg (with hud indicators of it). Maybe a better solution will be Examine text about temperature, like filled tanks have.

I'm definitely going to change this from a pop-up to something else. I originally chose the pop-up as it requires direct acknowledgement from the player. Some people might not think to look before they leap, but I guess that's their fault if they do. 

> I imagine we can just change the "you start crawling into the vent" text to "as you crawl into the vent, you feel a very hot breeze come out" and make it danger text or w/e

I considered this, but wasn't sure if an in-chat message would catch the user's attention in the single second it takes to enter. I also wasn't sure if this was a valid use case for balloon alerts.

2023-12-25 02:37 UTC, zeroisthebiggay commented
> I considered this, but wasn't sure if an in-chat message would catch the user's attention in the single second it takes to enter. I also wasn't sure if this was a valid use case for balloon alerts.

use a balloon alert

2023-12-27 20:02 UTC, Rhials commented
I'm gonna do this again later wish me luck

2023-12-27 20:02 UTC, closed without merging