QOLs balloon alerts to the armour booster module
tgstation/tgstation pull request #80680
Opened 2023-12-30 20:13 UTC by YakumoChen

## About The Pull Request
Adds balloon alerts for the armour booster module on toggle
![image](https://github.com/tgstation/tgstation/assets/10399117/cf50abbd-4618-4d74-aefe-7b461051e727)

## Why It's Good For The Game

The simple clarity is helpful and it works if you somehow get the module on a suit that doesn't normally get it (where there's no helmet icon differences)
Also makes it extra clear for newer players who probably don't understand how it works (like fluke ops)

## Changelog

:cl:
qol: Toggling an armour booster module on a MODsuit now gives a balloon alert making the tradeoffs more clear.
/:cl:

2023-12-30 20:23 UTC, JohnFulpWillard commented
armor*

2023-12-30 21:03 UTC, Mothblocks requested changes
considering the item in game is called armor, changing armour to armor would be preferred but not required

2023-12-30 21:03 UTC, Mothblocks commented on code/modules/mod/modules/modules_antag.dm
> +	balloon_alert(mod.wearer, "armour boosted, EVA lost!")
```suggestion
	balloon_alert(mod.wearer, "armour boosted, EVA lost")
```

exclamation point is for failure

2023-12-30 21:03 UTC, Mothblocks commented on code/modules/mod/modules/modules_antag.dm
> +		balloon_alert(mod.wearer, "armour retracts, EVA ready!")
```suggestion
		balloon_alert(mod.wearer, "armour retracts, EVA ready")
```

exclamation point is for failure

2023-12-30 21:16 UTC, RikuTheKiller commented
It's a bit long and since balloon alerts stick around for a while, I'd rather not stick that on my screen mid-fight, but oh well.

2023-12-30 21:39 UTC, Mothblocks commented
in combat is where they're some of the most important compared to chat, because you need to keep your eyes on the combat

2023-12-30 21:39 UTC, Mothblocks commented
shortening would be ok though

2023-12-31 03:48 UTC, YakumoChen commented
I don't really know how I'd shorten it since both the armour and EVA aspects are pretty important game information

2024-01-01 20:15 UTC, merged