[GBP NO UPDATE] Hub time timezone fix
tgstation/tgstation pull request #81053
Opened 2024-01-22 16:58 UTC by 13spacemen

## About The Pull Request
While browsing the hub I noticed Psychonaut Station the Turkish TG always had "Time:" with a value of many hours. I thought they had long rounds until I joined the server and noticed the actual time was 3 hours behind

Turns out time2text() has a timezone arg which defaults to server timezone

I have set it to UTC+0 so it is always consistent since world.time is UTC

## Changelog

:cl:
fix: The hub time should be accurate for servers with different timezones
/:cl:

2024-01-24 01:58 UTC, san7890 commented
yeah I don't know what MSO will think of this but I think that the value should be configurable somehow... I know we have a bunch of timezone-defines in our code but do those have a config entry anywhere?

2024-01-24 06:45 UTC, 13spacemen commented
@san7890 this is for the round time (since game started and everyone has gone in game in jobs)
it should always start from 00:00
if it changes according to timezones you get weird values, like when the roundstart it'll say 05:00 and that makes you think in the hub that their round has been going on for 5 hours

2024-01-24 13:08 UTC, MrStonedOne requested changes
this will do what you want, but it has a few other edge cases this doesn't account for. ROUND_TIME() how ever will do what you want and account for the timezone stuff. its what the status tab uses.

2024-01-24 13:08 UTC, MrStonedOne commented on code/game/world.dm
> +			new_status += "<br>Time: <b>[time2text(STATION_TIME_PASSED(), "hh:mm", 0)]</b>"
```suggestion
			new_status += "<br>Time: <b>[ROUND_TIME()]</b>"
```

2024-01-24 13:12 UTC, MrStonedOne commented
oh wait i see why you did it that way. one second.

2024-01-24 13:16 UTC, MrStonedOne commented on code/game/world.dm
> +			new_status += "<br>Time: <b>[time2text(STATION_TIME_PASSED(), "hh:mm", 0)]</b>"
```suggestion
			new_status += "<br>Time: <b>[gameTimestamp("hh:mm", STATION_TIME_PASSED())]</b>"
```

2024-01-25 08:41 UTC, LemonInTheDark commented
*it was not one second*

2024-01-25 08:54 UTC, 13spacemen commented
@MrStonedOne @LemonInTheDark  I'm not against using gametimestamp, just wondering, is it necessary?
not a pro coder but from searching timezoneoffset, i don't think it's even used anywhere or does anything
could be wrong though

2024-01-25 14:07 UTC, merged

2024-01-25 14:37 UTC, MrStonedOne commented
timezoneoffset is how we used to have to do it until they added the timezone argument, really all of this code needs to be unified up in a more sane matter, and to use the new timezone argument, but its all unimportant.

either way both versions break once you hit a day anyways. only ROUND_TIME handles 24 hour+ rounds properly, but it doesn't actually account for lobby time like it implies it does in the macro.

the fault here is that we are using date formatting byond functions for time durations which is already wrong, we really should make a proc to handle converting a number of seconds/dediseconds into dd:hh:mm:ss.ds format with math instead of displaying a duration as a time of the current date, which is what all of these byond procs do. (if you feed it something like `900ds` it turns that into current date at 00:01:30 am, which we use to display just the mm:ss part of the time, and this is why timezones fuck us, because we are having byond display the time part of an absolute datetime, as if it were a duration, instead of making proper duration proc)