Mining Bluespace Survival Capsule's "Stand back!" alert now actually has meaning
tgstation/tgstation pull request #81193
Opened 2024-01-30 21:25 UTC by MrMelbert

## About The Pull Request

- Standing in range of a Bluespace Survival Capsule being deployed will now toss you away from the deployed location of the pod, to roughly 2 tiles away.

## Why It's Good For The Game

I always found it weird (and a little misleading) that triggering a survival capsule alerts people to "Stand back!", but it's actually harmless to stand on top of it and even smart in some contexts since you phase into it like nothing happened. 

So I added the missing flavor. 

This also has some potential shenanigans involving antagging, as you can time it perfectly so that you toss it just in time to throw people away from it.

Note: The Luxury Elite pod is so large, that even after being thrown away, you may still end up inside the pod by the time it deploys, but I think that's funny. So. 

## Changelog

:cl: Melbert
add: Shaft Miner's Bluespace Survival Capsules will now throw people away from it when it deploys. Be sure to heed the warning to "Stand back". 
/:cl:

2024-01-31 00:59 UTC, san7890 requested changes
nit

2024-01-31 00:59 UTC, san7890 commented on code/modules/mining/equipment/survival_pod.dm
> +	for(var/mob/living/did_not_stand_back in range(loc, "[width]x[height]"))
i feel like this whole chunk would be better off in another prompt for clarity purposes (e.g. this proc can be easily read for template spawning/handling, and any behavior relating to "throwing mobs" can be read in the separate proc)

2024-01-31 09:56 UTC, the-orange-cow commented
If possible, maybe the bar capsule would not behave like this?  It is a high price item, so maybe they added special safety features to it?

2024-01-31 13:53 UTC, Admiral-Gigaton commented
> If possible, maybe the bar capsule would not behave like this? It is a high price item, so maybe they added special safety features to it?

yeah, instead it just breaks your leg, but has complementary bone repair meds in the bathroom (joke)

2024-01-31 15:13 UTC, atlasle commented
> If possible, maybe the bar capsule would not behave like this?  It is a high price item, so maybe they added special safety features to it?

no it should be stronger and toss you even farther since it's a larger building, respect safety measures!

2024-01-31 18:10 UTC, MrMelbert commented
> If possible, maybe the bar capsule would not behave like this? It is a high price item, so maybe they added special safety features to it?

Well I mentioned it in the PR body but the bar capsule is so large that sometimes, despite throwing you, you will get caught by its walls, so we can call that a feature

2024-02-02 18:38 UTC, Exester509 commented
> If possible, maybe the bar capsule would not behave like this? It is a high price item, so maybe they added special safety features to it?

Money can't get you away from OSHA

2024-02-10 12:38 UTC, projectkepler-ru commented
You should make it have the Trauma Team 'Stand Clear' holoprojector effect like in cyberpunk

2024-02-10 19:01 UTC, ArcaneMusic requested changes
minor nits

2024-02-10 23:12 UTC, Ghommie approved these changes

2024-02-10 23:13 UTC, merged