Assembly bomb rework
tgstation/tgstation pull request #81218
Opened 2024-02-01 12:38 UTC by SapphicOverload

Alternative to #81197

## About The Pull Request & Why It's Good For The Game

Something that's always disappointed me about assembly bombs is how incredibly simple and easy they are to make as powerful as possible, with no room for doing anything new.

This PR changes that by reworking assembly bombs to react their contents and use the reaction energy to determine explosion size, rather than requiring a specific gas at specific temperature thresholds. This means if you want to obliterate someone with as much sheer destructive force as before, you need more energetic reactions using higher quantities of harder to obtain gases.

Additionally, condensers can now be used in place of an igniter to cool the contents instead of heating them, and multitools can change the ignition/condensation temperature of igniters and condensers.

This solves the issue of being able to mass produce extremely powerful bombs with almost no effort, while also allowing the possibility of unique reactions like BZase to be used in them to do cool things besides exploding.

Also, /obj/item/onetankbomb is finally dead. Assembly bomb explosions are now handled by the tank itself instead of creating an invisible separate item for it.

## Changelog

:cl:
balance: Assembly bombs now use the energy of reactions happening inside them when ignited to determine explosion size, instead of requiring a specific gas at specific temperature thresholds.
add: Condensers can now cool gases inside a tank when used in an assembly bomb.
add: Using a multitool on an igniter or condenser can change its ignition/condensation temperature.
code: Removes /obj/item/onetankbomb, assembly bombs are now handled by the tank itself.
/:cl:

2024-02-01 12:43 UTC, mc-oofert commented
this wont do anything because it would take 2 days for everyone to get informed of the new optimal recipe

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/modules/assembly/igniter.dm
> +		balloon_alert(user, "[name] set to [heat] K")
```suggestion
		balloon_alert(user, "set to [heat]K")
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/modules/assembly/igniter.dm
> +	var/new_heat_setting = tgui_input_number(user, "Set new temperature:", "[capitalize(name)]", heat, max(ROOM_TEMP, initial(heat)))
```suggestion
	var/new_heat_setting = tgui_input_number(user, "Set new temperature", "[capitalize(name)]", heat, max(ROOM_TEMP, initial(heat)))
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +		to_chat(user, span_warning("[assembly] is stuck to your hand!"))
These could also be balloon alerts

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +			igniter_count += 1
```suggestion
	for(var/obj/item/assembly/igniter/attached_assembly in assembly.assemblies)
		igniter_count++
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +	sleep(1 SECONDS)
Not obligatory since this isn't your code but it would be nice if you got rid of the sleep here

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +		to_chat(user, span_notice("A pressure hole has been bored to [src]'s valve. \The [src] can now be ignited."))
You should keep either the balloon alert or chat message

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +			balloon_alert(user, "something is already attached!")
```suggestion
			balloon_alert(user, "something already attached!")
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +	return
```suggestion
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +	update_icon(UPDATE_OVERLAYS)
```suggestion
	update_appearance(UPDATE_OVERLAYS)
```

2024-02-01 13:06 UTC, JohnFulpWillard commented on code/game/objects/items/tanks/tanks.dm
> +	update_icon(UPDATE_OVERLAYS)
```suggestion
	update_appearance(UPDATE_OVERLAYS)
```

2024-02-01 13:12 UTC, mc-oofert commented
> > this wont do anything because it would take 2 days for everyone to get informed of the new optimal recipe
> 
> It's not about preventing most people from being able to make assembly bombs, it's about making it take far more time and effort for one that's on the same level as before.

reporting to you in a two days if this gets merged with total time to make recipe

2024-02-01 13:32 UTC, jughu commented
i like to do assembly bombs cuz it requires less effort then chem bombs and i can make 100x auntity kf it

2024-02-01 13:55 UTC, SyncIt21 requested changes
Nits

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +		return TRUE
```suggestion
		return ITEM_INTERACT_SUCCESS
```
Use the new attach chain values

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +		return TRUE
```suggestion
		return ITEM_INTERACT_SUCCESS
```

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +		return TRUE
```suggestion
		return ITEM_INTERACT_SUCCESS
```

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +	..()
```suggestion
	. = ..()
```
We need the return value for something

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +	user.transferItemToLoc(assembly, src)
This proc can return false and fail. Check for it and take the required actions

2024-02-01 13:55 UTC, SyncIt21 commented on code/modules/assembly/igniter.dm
> +		return TRUE
```suggestion
		return ITEM_INTERACT_SUCCESS
```

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +		tank_assembly.Move()
Move() takes the an location as an argument right? Does this work without any?

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +		. += span_warning("There is some kind of device <b>rigged</b> to the tank!")
```suggestion
		. += span_warning("There is some kind of device [EXAMINE_HINT("rigged")] to the tank!")
```

2024-02-01 13:55 UTC, SyncIt21 commented on code/game/objects/items/tanks/tanks.dm
> +	if(tank_assembly)
If condition is unessassary because QDEL_NULL does an no op for null values

2024-02-01 15:25 UTC, SomeoneYouProbablyKnow commented
Has this done anything to ttvs? They have a reaction, you need to theory craft them and know some atmos.

An optimal recipe will be known in less than a week and it'll either be
a) very easy, nothing changed
b) Mildly difficult nothing changed for the people getting exploded expect the knowledge the atmos tech had to nerd out for 20 minutes
c) it's so difficult it kills the item

it's a static system there's not much skill in recreating a recipe be it plasma at 674 OR half oxy half plasma half nitrogen at 698

2024-02-01 15:54 UTC, SapphicOverload commented
> Has this done anything to ttvs? They have a reaction, you need to theory craft them and know some atmos.
> 
> An optimal recipe will be known in less than a week and it'll either be a) very easy, nothing changed b) Mildly difficult nothing changed for the people getting exploded expect the knowledge the atmos tech had to nerd out for 20 minutes c) it's so difficult it kills the item
> 
> it's a static system there's not much skill in recreating a recipe be it plasma at 674 OR half oxy half plasma half nitrogen at 698

It at least raises the amount of effort required to easily gib people enough that you can't just make one that strong in less than a minute almost roundstart like you can now. I think it's a step in the right direction to at least require more effort than heating up a bit of plasma to achieve that kind of power.

2024-02-01 18:38 UTC, GuillaumePrata commented
Having an easy bomb that gibs people is not the main issue with the item, it is how easy it is to have multiple on you at once.

Between this PR and the Bulky one, the bulky PR fixes the issue of spam gibbing people, this one just makes the knowledge gate for antag shenanigans higher and rewards more Atmos secret club recipe sharing just like a few months ago with the single tank recipes spam being an issue.

2024-02-01 20:48 UTC, LemonInTheDark commented
Correct me if I'm wrong but how is this any different from a ttv (except it gets one chance to react and not more)

2024-02-02 03:31 UTC, SapphicOverload commented
> Having an easy bomb that gibs people is not the main issue with the item, it is how easy it is to have multiple on you at once.
> 
> Between this PR and the Bulky one, the bulky PR fixes the issue of spam gibbing people, this one just makes the knowledge gate for antag shenanigans higher and rewards more Atmos secret club recipe sharing just like a few months ago with the single tank recipes spam being an issue.

That's a fair point actually.

2024-02-02 03:40 UTC, SapphicOverload commented
Removed the balance stuff, kept the code improvements.

2024-02-03 08:24 UTC, merged

2024-02-05 22:41 UTC, optimumtact commented
@mc-oofert it's been 3 days where you at.

2024-02-06 05:16 UTC, mc-oofert commented
What for