Converts random bedsheets to spawners + 3 bedsheets I made long time ago.
tgstation/tgstation pull request #81435
Opened 2024-02-11 21:43 UTC by Ghommie

## About The Pull Request
Yeah, random bedsheets aren't spawners but their own snowflake. This changes that.

I'm taking the opportunity to add the Runtime, pirate and gondola bedsheets I made long time ago on Citadel.

## Why It's Good For The Game
Code improvement? I dunno. 1 in a 80 chance of any given dorms bedsheet to be made of gondola hide? Sure, why not.

## Changelog

:cl:
add: Added three new 'special' bedsheets. One of them is quite rare and made from gondola hide.
/:cl:

2024-02-12 11:59 UTC, Singul0 commented
that's odd. must have been from before spawners were a thing / commonly used?

2024-02-12 23:17 UTC, Wallemations approved these changes

2024-02-13 06:44 UTC, san7890 requested changes

2024-02-13 06:44 UTC, san7890 commented on code/game/objects/structures/bedsheet_bin.dm
> +	dream_messages = list("do whatever you wants",
```suggestion
	dream_messages = list(
		"do whatever you wants",
```

this list should also be alphabetized

2024-02-13 06:44 UTC, san7890 commented on code/game/objects/effects/spawners/random/bedsheet.dm
> +		/obj/item/bedsheet/blue = 8,
also fix the list formatting on this (is it intentional for the base bedsheet type to not have a weight associated with it? please add one otherwise)

2024-02-16 08:46 UTC, merged