Facehuggers no longer knock you out for 2 minutes straight and instead will paralyze you and cause you to scream, allowing counterplay to exist beyond just being a prophet and having future sight to know when a xeno is gonna pop out of a vent. I mean, damn, I get fired today and decide ok I'll play some Space Station 13 and what do I gotta deal with? The same trash unfixed broken antag mechanic that's been in the game for 15 years that you people won't let us remove because soul or something, this shit just ruined my entire night, fuck xenos, fuck this antag type, and fuck 2 minute hard stuns with zero counter that can be applied instantly by someone who just spent the last 5 minutes sitting in a vent camping to ruin someone's round
tgstation/tgstation pull request #81533
Opened 2024-02-17 16:45 UTC by Iamgoofball

## About The Pull Request

Facehuggers no longer knock you out for 2 minutes straight and instead will paralyze you and cause you to scream, allowing counterplay to exist beyond just being a prophet and having future sight to know when a xeno is gonna pop out of a vent. I mean, damn, I get fired today and decide ok I'll play some Space Station 13 and what do I gotta deal with? The same trash unfixed broken antag mechanic that's been in the game for 15 years that you people won't let us remove because soul or something, this shit just ruined my entire night, fuck xenos, fuck this antag type, and fuck 2 minute hard stuns with zero counter that can be applied instantly by someone who just spent the last 5 minutes sitting in a vent camping to ruin someone's round.

Every time I play this fucking game xenomorphs ruin it for me. I swear to god. Every single time.

## Why It's Good For The Game

Facehuggers no longer knock you out for 2 minutes straight and instead will paralyze you and cause you to scream, allowing counterplay to exist beyond just being a prophet and having future sight to know when a xeno is gonna pop out of a vent. I mean, damn, I get fired today and decide ok I'll play some Space Station 13 and what do I gotta deal with? The same trash unfixed broken antag mechanic that's been in the game for 15 years that you people won't let us remove because soul or something, this shit just ruined my entire night, fuck xenos, fuck this antag type, and fuck 2 minute hard stuns with zero counter that can be applied instantly by someone who just spent the last 5 minutes sitting in a vent camping to ruin someone's round.

## Changelog

:cl:
balance: Facehuggers no longer knock you out for 2 minutes straight and instead will paralyze you and cause you to scream, allowing counterplay to exist beyond just being a prophet and having future sight to know when a xeno is gonna pop out of a vent. I mean, damn, I get fired today and decide ok I'll play some Space Station 13 and what do I gotta deal with? The same trash unfixed broken antag mechanic that's been in the game for 15 years that you people won't let us remove because soul or something, this shit just ruined my entire night, fuck xenos, fuck this antag type, and fuck 2 minute hard stuns with zero counter that can be applied instantly by someone who just spent the last 5 minutes sitting in a vent camping to ruin someone's round
/:cl:

2024-02-17 16:47 UTC, Ghommie commented
Biggest "i ded" PR I've ever seen. The title says all.

2024-02-17 17:03 UTC, Jacquerel commented
> Biggest "i ded" PR I've ever seen. The title says all.
> 
> On a itsy more serious note, please refrain from making such absurdly long PR titles in the future. You can vent in the comment for it.

Might want to edit the changelog too, on the other hand it is kinda funny.

2024-02-17 17:04 UTC, Iamgoofball commented
the changelog provides context for players questioning the change

2024-02-17 17:27 UTC, Rhials commented
Shoulda wore a helmet!

2024-02-17 17:36 UTC, GuillaumePrata commented
This punishes, but won't stop the annoying vent meta we have with Xenos, they can still throw a hugger on you and leave again, spending 5 seconds of their time to force the crew to run to medbay or be round removed, while nerfing hard on their nest defense.

We should just make that Xenos can't go on vents while carrying a hugger, they can still throw huggers at people assaulting the nest or the random assistant ~~valid hunting~~ exploring maints, but it would completely end the annoying hit and run tactics Xenos do with vents and huggers.

Swarmers were removed in part because of this, vent hit and run tactics drag the round to a halt and make people give up on beating the antags and just calling the shuttle instead, we should just remove these ~~xenomorphs~~ strats.

2024-02-17 18:43 UTC, ExcessiveUseOfCobblestone commented
Also dont @ me but vents should act as "closed" when turned off, which makes some mobs have unable to pass through the vent or require them to pry it open which gives a delay and sound cue. There should be an intermediate between wide open and welded shut that isnt such a pain to fix after the threat is eliminated, but doesnt hardstop the threat from utilizing the unwelded vent.

2024-02-17 20:26 UTC, MrMelbert requested changes
I am not opposed to this but it could use a few tweaks to make it less dead easy to immediately slam `; XENOS MEDBAY MAINT` after being hugged

Such as
- You can't talk while facehugged, or all talking gets muffled (`; MMM MMMM MMM`)
- You can talk, but you can't use your radio
- Same as above but it forces you to use whisper 
- Any combination of above (forced whisper + muffled + no radio sounds funny to me) 

And
- You can't remove a facehugger from your face by yourself without help until it's dead

2024-02-17 20:29 UTC, MrMelbert commented
(If ur lazy you can just give facehuggers `BLOCKS_SPEECH` like muzzles but that's kinda boring)

2024-02-17 21:25 UTC, IndieanaJones commented
I would just make it so they can't ventcrawl while holding an item like monkeys.

2024-02-18 19:57 UTC, bigfatbananacyclops commented
i dont typically advocate 'ided' prs. but xenos are in fact, and have been broken for 15 years. it wouldnt be bad to atleast be able to stop a hugger.

2024-02-18 22:10 UTC, Zenog400 commented
> i dont typically advocate 'ided' prs. but xenos are in fact, and have been broken for 15 years. it wouldnt be bad to atleast be able to stop a hugger.

You know that spacesuit helmets and bio suit helmets all stop them, right?

2024-02-19 00:13 UTC, bigfatbananacyclops commented
> > i dont typically advocate 'ided' prs. but xenos are in fact, and have been broken for 15 years. it wouldnt be bad to atleast be able to stop a hugger.
> 
> 
> 
> You know that spacesuit helmets and bio suit helmets all stop them, right?

Yes i know and i know more than you. But this will atleast help relieve the immense power xenos have.

2024-02-24 19:10 UTC, ExcessiveUseOfCobblestone commented
They're not intended to be a fair fight, theyre meant to be used to wrap up the round.

2024-02-24 19:52 UTC, Iamgoofball commented
@ExcessiveUseOfCobblestone getting killed fast is fine, staring at a black screen for 2 minutes is boring as shit

2024-03-09 04:16 UTC, Ghommie requested changes

2024-03-09 04:16 UTC, Ghommie commented on code/modules/mob/living/carbon/alien/special/facehugger.dm
> +		M.Paralyze(MAX_IMPREGNATION_TIME/0.3) //something like 25 ticks = 20 seconds with the default settings
Please update the comment.

2024-03-17 00:06 UTC, closed without merging