Buffs the SC/FISHER Saboteur Handgun.
tgstation/tgstation pull request #81553
Opened 2024-02-18 17:06 UTC by Ghommie

## About The Pull Request
The saboteur gun will now silence pAIs, toggle off radio broadcasting (won't auto-relay nearby speech), disable turrets, chill out secbots a little, and turn off APCs like power outages do. 
The disrupt duration has also been buffed from 10/20 to 15/25 for ranged and point-blank respectively.
Removed a conspicious chat message from an otherwise inconspicious gun.
Brought the code up to date.

## Why It's Good For The Game
The concept is cool, alas it's also undermined by how much of a joke it's right now, and the game has plenty already.
The amount of interactions it has with things is underwhelming, so you could barely consider it a stealth tool. The duration is also quite scarce, I pointed that out in the original PR too.

Basically, I want to make the item cooler.

## Changelog

:cl:
balance: Buffer the duration of the SC/FISHER Saboteur Handgun's disruption effects.
add: Added saboteur interactions with radios, pAIs, turrets, secbots and APCs.
/:cl:

2024-02-18 17:51 UTC, EuclidianGeometer commented
Removing the chat message isn't in the changelog, but it's one of the more important changes here.

2024-02-18 17:55 UTC, Ghommie commented
> Removing the chat message isn't in the changelog, but it's one of the more important changes here.

Done.

2024-02-18 19:54 UTC, Admiral-Gigaton commented
Can you fix the part where it can't shoot floor lights, but can still melee them?

Also, making it so players with flashlights of any kind, when shot or hit with the gun, have their light turned off. Like a nightmare, but without the breaking of the light. Just shuts it off

2024-02-18 20:37 UTC, Eronymun commented
Random suggestion: If you make it turn off (but not lock/discharge) stun batons, I think that would be very silly.

2024-02-18 23:54 UTC, rageguy505 commented
> Can you fix the part where it can't shoot floor lights, but can still melee them?
> 
> Also, making it so players with flashlights of any kind, when shot or hit with the gun, have their light turned off. Like a nightmare, but without the breaking of the light. Just shuts it off

It already does the second part

2024-02-19 13:36 UTC, Admiral-Gigaton commented
> > Can you fix the part where it can't shoot floor lights, but can still melee them?
> > Also, making it so players with flashlights of any kind, when shot or hit with the gun, have their light turned off. Like a nightmare, but without the breaking of the light. Just shuts it off
> 
> It already does the second part

Tested on a recent round (last night) it did not, in fact, seem to disable their lights (plasmaman helmet, flashlights, PDA) while they held them

2024-02-19 14:00 UTC, Ghommie commented
> 
> Tested on a recent round (last night) it did not, in fact, seem to disable their lights (plasmaman helmet, flashlights, PDA) while they held them

I'm pretty sure it disables flashlights, but only the ones that can be toggled on/off, so not the fancy subtypes like flares and glowsticks, but I'll take care of stuff like hard hats, plasmaman helmets and PDAs.

2024-02-19 14:58 UTC, Admiral-Gigaton commented
> > Tested on a recent round (last night) it did not, in fact, seem to disable their lights (plasmaman helmet, flashlights, PDA) while they held them
> 
> I'm pretty sure it disables flashlights, but only the ones that can be toggled on/off, so not the fancy subtypes like flares and glowsticks, but I'll take care of stuff like hard hats, plasmaman helmets and PDAs.

MODsuit lights too? If possible. Things like eye flashlights wouldn't go on the list tho, as shooting someone's eyes would be a hard task and much more noticeable. 

Mech lights?

2024-02-19 19:38 UTC, Admiral-Gigaton commented
should we buff the time for camera EMP? it feels really short, only good for like running across a room

2024-02-19 20:07 UTC, Eronymun commented
Haha nice batong go bzzt

2024-03-13 22:14 UTC, Jacquerel requested changes

2024-03-13 22:14 UTC, Jacquerel commented on code/game/objects/items/melee/baton.dm
> +
```suggestion
	if(!active)
		return
	toggle_light()
	active = FALSE
	update_appearance()
	return COMSIG_SABOTEUR_SUCCESS
```

2024-03-13 22:25 UTC, merged