Grilles dont break by just walking into them under any circumstances
tgstation/tgstation pull request #81594
Opened 2024-02-20 18:55 UTC by mc-oofert

## About The Pull Request

you can no longer just walk into a grille to destroy it rather fast
also single letter variable cleanup from that proc

## Why It's Good For The Game

this is a bug and bugs are bad

## Changelog

:cl:
fix: Grilles dont break by just walking into them under any circumstances
/:cl:

2024-02-20 21:06 UTC, lessthnthree requested changes
Didn't know this was a bug, the window smash proc assumes the grille break.

In fixing it, can you please add this to /datum/element/window_smashing/proc/flying_window_smash in code/datums/elements/window_smash.dm (line 27)

```
for(var/obj/structure/grille/grille in target_turf)
		grille.smash_and_injure(flying_mob, old_loc, direction)
```

2024-02-22 03:21 UTC, san7890 requested changes

2024-02-22 03:21 UTC, san7890 commented on code/game/objects/structures/grille.dm
> +			sparks.start()
this should really use early returns instead so we can cut down on how wack the indentation is (as well as the needless if/else)

```
if(isnull(cable_node)) // more explicit than ! so it's better
 return FALSE

if(!electrocute_mob(...))
 return FALSE

// do the prob(50) and the sparks spawner here
return TRUE

2024-02-28 07:23 UTC, LemonInTheDark commented on code/game/objects/structures/grille.dm
> +	. = FALSE
Please return explicitly this is worse

2024-02-28 07:25 UTC, LemonInTheDark approved these changes

2024-02-28 07:32 UTC, LemonInTheDark commented
Tested

2024-02-28 07:38 UTC, merged