Added a new moth customisation set to the character setup
tgstation/tgstation pull request #81718
Opened 2024-02-27 17:23 UTC by DaliIsTaken

## About The Pull Request

This PR adds a new moth customisation set and makes it available in the character setup menu. 

Introducing, the lightbearer moth!
![image](https://github.com/tgstation/tgstation/assets/161269765/d683fe9c-1dea-44bd-b378-09ae57bbb839)
![image](https://github.com/tgstation/tgstation/assets/161269765/4750affe-4f95-4199-abe7-82da500e0dff)

Setup menu preview:

![image](https://github.com/tgstation/tgstation/assets/161269765/deb27899-6f6e-471e-bd76-f27470845bb0)
![image](https://github.com/tgstation/tgstation/assets/161269765/e9463543-87cd-4e44-9997-840f3169c735)
![image](https://github.com/tgstation/tgstation/assets/161269765/4c492e1b-cb66-436f-95c4-e44ddf7d6f29)

## Why It's Good For The Game

Adds more variety to moth customisation!

## Changelog

:cl:
add: added the lightbearer moth set, available in the character setup.
image: added icons for the lightbearer set; new moth wings, antennae and markings.
/:cl:

2024-02-27 22:38 UTC, ArcaneDefence commented
![image](https://github.com/tgstation/tgstation/assets/51932756/073ed6fd-11cc-4615-ad0e-f2d3200ef796)
It's covering the arm here

2024-02-27 22:50 UTC, SomeoneYouProbablyKnow commented
CUTE!!! A cool bright moth set. Very nice

2024-02-27 23:18 UTC, ZephyrTFA commented
did you get approval from a maintainer for this

2024-02-28 02:30 UTC, Jacquerel commented
They now have permission from me because I don't think new sprites for species body parts that we already have is a feature you should need much or really any approval for 

(Still also needs sprite lead approval though)

2024-02-28 11:29 UTC, DaliIsTaken commented
Thank you jacquerel. I am not very aware of the spriting approval process.

2024-02-28 11:39 UTC, DaliIsTaken commented
> ![image](https://private-user-images.githubusercontent.com/51932756/308358256-073ed6fd-11cc-4615-ad0e-f2d3200ef796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjAwMDAsIm5iZiI6MTcwOTExOTcwMCwicGF0aCI6Ii81MTkzMjc1Ni8zMDgzNTgyNTYtMDczZWQ2ZmQtMTFjYy00NjE1LWFkMGUtZjJkMzIwMGVmNzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjAyZDBmYWQ1OTI4M2E4YWNlNmZjYjYzMmUxZmRiYzc3Y2RkMTY4YTdkYWMxYmRjYzdjZTM5YTQ1MzJhY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u2llHOiDc-87w-ta7LQ15NxgWpE3XewVg9xMvqw8LL0) It's covering the arm here

Hello, the pixel placement at the arm is meant to be consistent with the other wings in profile (though some of the wings do diverge from this). I'll exemplify with the atlas wings: 
![image](https://github.com/tgstation/tgstation/assets/161269765/07095b5d-5d1d-40f7-9602-296be12660fc)

2024-03-01 22:25 UTC, Wallemations approved these changes

2024-03-04 00:06 UTC, Wallemations commented
not really sure if I'm allowed to merge this one

2024-03-04 13:24 UTC, Jacquerel requested changes

2024-03-04 13:24 UTC, Jacquerel commented on code/datums/sprite_accessories.dm
> +	icon_state = "lightbearer"
```suggestion
	icon_state = "lightbearer"

```

2024-03-04 13:35 UTC, merged