Universalizing ruin names
tgstation/tgstation pull request #81737
Opened 2024-02-28 15:59 UTC by Zergspower

## About The Pull Request

This is not player-facing, however it's a good QOL that i made for downstream modular ruins. The pick-list of maps makes it a bit.. annoying to really grab a ruin quickly - so all this does is add an ID to the front of them for Space, Lava and Ice respectively.

![image](https://github.com/tgstation/tgstation/assets/22140677/76ab2850-02a1-45d8-a8f9-2e4ad421b2c1)

## Why It's Good For The Game

## Changelog

:cl:Zergspower
admin: renames ruin names to have an identifier in front of it
/:cl:

2024-02-28 16:12 UTC, Admiral-Gigaton commented
i assume that screenshot is of this downstream? never heard of "abductor reproduction facility" or... really any of those, besides the ghost ships and broken shuttle, which i may know what they are talking about

2024-02-28 16:23 UTC, Jacquerel commented
I don't know if `Lava Ruin` or `Space Ruin` or `Ice Ruin` need to be hyphenated but also its not like a big deal

2024-02-28 16:24 UTC, Zergspower commented
> i assume that screenshot is of this downstream? never heard of "abductor reproduction facility" or... really any of those, besides the ghost ships and broken shuttle, which i may know what they are talking about

ah shit you right, i pasted the wrong image

2024-02-28 16:26 UTC, Zergspower commented
> I don't know if `Lava Ruin` or `Space Ruin` or `Ice Ruin` need to be hyphenated but also its not like a big deal

i wont lose sleep if it's asked to be removed, in my mind it was a 'designation' break 'actual namel'

2024-02-28 18:00 UTC, Zergspower commented
I kinda fully disagree, mainly due to ruins not always being named similarly to what their file is. This makes them grouped alphabetically right there with 1 button press. Especially if you're trying to find a ruin you dont exactly remember what the name of it is.

2024-02-29 17:48 UTC, MrMelbert requested changes
Can you make the place ruin / jump to ruin verbs use `tgui_list_input`, since you're making it a tad more difficult to navigate?

2024-03-01 03:03 UTC, Zergspower commented
> Can you make the place ruin / jump to ruin verbs use `tgui_list_input`, since you're making it a tad more difficult to navigate?

Sure, have an example i could look at to copy? I'm mostly a mapper and am not super great with code i've not seen before

2024-03-01 21:39 UTC, MrMelbert commented
> Sure, have an example i could look at to copy? I'm mostly a mapper and am not super great with code i've not seen before

Literally any `tgui_input_list` is an example, but if you want a specifically relevant one, look at `/client/proc/force_load_lazy_template()`

2024-03-04 15:38 UTC, Zergspower commented
> > Sure, have an example i could look at to copy? I'm mostly a mapper and am not super great with code i've not seen before
> 
> Literally any `tgui_input_list` is an example, but if you want a specifically relevant one, look at `/client/proc/force_load_lazy_template()`

that was - far less painful than i expected??? what???  lol

![image](https://github.com/tgstation/tgstation/assets/22140677/d7f4b8ff-61f8-4d44-913a-8a8de0640792)

2024-03-04 22:17 UTC, merged

2024-04-20 09:31 UTC, LemonInTheDark commented
I kinda think this is worse. You've made it harder to tell scrolling what ruin is what, and you just like, left the existing deliminators in the list, and since it's sorted now they just float at the top doing nothing? 
![image](https://github.com/tgstation/tgstation/assets/58055496/6797e843-6894-47cf-99cb-1404595fe49b)

2024-04-20 09:49 UTC, LemonInTheDark commented
Also a lot of now redundant sorting code that just gets wiped out by the final sort list. don't like this at least as is