Adjusts some of the contraband weights for Contraband Crates.
tgstation/tgstation pull request #81771
Opened 2024-03-01 20:50 UTC by necromanceranne

## About The Pull Request

This makes getting Contraband Plus (the better stuff with more interesting effects), slightly higher in probability out of contraband crates.

It also removes the completely redundant narcotics roll, and the truly awful permabrig contraband roll, from Contraband Plus.

## Why It's Good For The Game

The weights were a little uninteresting. You rarely if ever saw the effects of the contraband crate change with the current values. It was kind of lame to see a shiv in a contraband crate knowing that it was a wasted Contraband Plus roll. This hopefully stops that from happening too often.

## Changelog

:cl:
balance: Adjusts the values and contents of the Contraband Crate's item loot table.
/:cl:

2024-03-02 21:56 UTC, san7890 requested changes
let's be consistent

2024-03-02 21:56 UTC, san7890 commented on code/game/objects/effects/spawners/random/contraband.dm
> +		/obj/item/reagent_containers/cup/blastoff_ampoule =5,
```suggestion
		/obj/item/reagent_containers/cup/blastoff_ampoule = 5,
```

2024-03-03 07:05 UTC, dalmationer commented
I believe this also cuts out the syndicate mask, right? Any chance that could be left in, as it lets you complete the look if you get the turtleneck too!

2024-03-03 20:05 UTC, necromanceranne commented
The mask is in normal contraband.

2024-03-09 03:57 UTC, Ghommie approved these changes

2024-03-09 03:57 UTC, merged