Skittish will no longer re-lock lockers you've dived into.
tgstation/tgstation pull request #81853
Opened 2024-03-05 23:18 UTC by Iamgoofball

## About The Pull Request

Skittish will no longer re-lock lockers you've dived into.

## Why It's Good For The Game

Amount of times I've walked into a security locker this week and wasted 2 minutes of my time each time is immense. Plus, if you can't unlock a locker from inside of it, how are you locking it from inside of it? It doesn't make sense.

## Changelog
:cl:
balance: Skittish will no longer re-lock lockers you've dived into.
/:cl:

2024-03-05 23:32 UTC, KingkumaArt commented
And this was how I ended up getting brigged as a cargo tech by complete accident

2024-03-05 23:32 UTC, 00-Steven commented
okay but, it's *really* funny when I accidentally dive into the lockable locker/crate with mute/soft-spoken/somesuch

2024-03-05 23:55 UTC, deathrobotpunch commented
soul removal

2024-03-06 00:22 UTC, MrMelbert requested changes
Keep the toggle but ONLY if you have the proper access to lock/unlock it

2024-03-06 05:12 UTC, githubuser4141 commented
It should work if you've access to it, just not if you don't, especially not if it's a special cargo crate which can literally round-remove you because you can't RESIST out of those ones (it just says - failed).

2024-03-09 12:09 UTC, DrDiasyl commented
You can unlock lockers from inside, all you need to do is right-click

2024-03-09 21:51 UTC, Iamgoofball commented
you cannot, i have tried multiple times

2024-03-09 21:58 UTC, DrDiasyl commented
> you cannot, i have tried multiple times

Then this means you have no access to the locker, or it's a skittish only bug.
I've always locked and unlocked the locker when I went SSD.

2024-03-10 07:50 UTC, Iamgoofball commented
it's gotta be a skittish bug then because the amount of times as a sec officer ive walked into a sec locker by accident and not been able to get out without smashing the lock is unreal

2024-03-14 19:35 UTC, FlufflesTheDog commented
> you cannot, i have tried multiple times

you absolutely can
one thing that comes to mind is that pushing the resist button gives you a god awful click delay cooldown, so attempting to unlock it during that literal 10 seconds following results in nothing happening

also my personal opinion is that this is a pretty fun/interesting interaction, trying to get someone to let you out

2024-03-29 00:05 UTC, closed without merging