Blesses the codebase with Blahaj
tgstation/tgstation pull request #81862
Opened 2024-03-06 09:31 UTC by Draggeru

## About The Pull Request

Adds the Shark and Shork Costume to the game, craftable via carp scales.
In addition, adds the ability to use a shark costume to craft a shark plushy.

![ge1uucdAYn8xAAAAABJRU5ErkJggg](https://github.com/tgstation/tgstation/assets/81540056/52d66419-4946-4c0e-8061-8b03e6858a53)
![J2YyKAAI2pNXkXCAyMAAI0sAajuhAYE4FeBciufHkQc53Vij1rxorYmNyadxkKAQRo3lII0FBclnqOiQAChACNyZ95l4ER6FWAbFjkcSrxraha5Q7MF6guBHongADNkZcQvt5bkwIhMDACCBACNDCXpbpjItCrAI0JHO8CAQikE0CA0hliAQIQ6EgAAeoIjmwQgEA6gf8Bgzt4GlTrNLUAAAAASUVORK5CYII](https://github.com/tgstation/tgstation/assets/81540056/a2691688-b6e9-493d-99ec-ef729cf6cb06)

Upon crafting a shark costume, there is a 1/10 chance to instead craft a shork costume. This increases to a 50/50 chance if the player crafting the item has the clumsy trait.

## Why It's Good For The Game

Good and funny costumes that give an additional use to pre-existing crafting materials = good
Giving players another way to craft the shark plushie = good
Giving a unique interaction with clumsy = good 

Todo:
- [ ] Make sure shit wont break
- [ ] Add the crafting recipe for the costume
- [ ] Add the crafting recipe for the shark plushie
- [ ] Add the random chance to make a shork costume instead
- [ ] Profit??

## Changelog

:cl: Drag
add: Adds the Shark and Shork costume. Blahaj lovers rejoice!
/:cl:

2024-03-06 09:50 UTC, another-expler commented
Fqmboy update

2024-03-06 12:25 UTC, san7890 requested changes
I like the idea but you screwed up some code so I'll mention it now

2024-03-06 14:04 UTC, Admiral-Gigaton commented
Wuh... which is uh... the shork...

2024-03-06 16:01 UTC, Draggeru commented
> Wuh... which is uh... the shork...

Shork is the very fucked up MS paint looking costume

2024-03-06 16:01 UTC, Draggeru commented on code/modules/clothing/suits/costume.dm
> +	inhand_icon_state = "sharkcursed"
Officially hate it here

2024-03-06 18:37 UTC, Draggeru commented
After vibe checking my imagination with my skill level instead of it being a random chance it is now just a craft to get the shork costume.

2024-03-06 20:00 UTC, ExcessiveUseOfCobblestone commented on code/modules/clothing/suits/costume.dm
> +	inhand_icon_state = "sharkcursed"
```suggestion
	inhand_icon_state = "labcoat"
```

2024-03-06 23:36 UTC, Wallemations commented
Show shark plushie icon in pr please

2024-03-07 00:16 UTC, Draggeru commented
> Show shark plushie icon in pr please

The plushie is the one that already exists in the code base

2024-03-07 02:52 UTC, Admiral-Gigaton commented
> > Wuh... which is uh... the shork...
> 
> Shork is the very fucked up MS paint looking costume

Both... do...

2024-03-07 14:05 UTC, Jackraxxus commented
Katy Perry left shark

2024-03-08 18:37 UTC, merged

2024-03-16 18:53 UTC, relativelysmalllebowski commented
mistake