Refactored admin backup saving. No longer at round end, more data backed up
tgstation/tgstation pull request #81891
Opened 2024-03-08 07:46 UTC by MrStonedOne

Admin verified connections now cache all verified connections for all admins. (Rather then just the last connection data of the currently connected admins)

Sync with the db now happens at admin load time, not at round end. (this was causing annoyances because servers with long rounds could override the admin db with old/stale data overwritting the fresher data that was written by a server with a shorter round)

Fix backup verification not working if the db thinks it still connected but its not actually still connected.

@Mothblocks @Jordie0608

2024-03-08 15:03 UTC, ZephyrTFA requested changes, later dismissed

2024-03-08 15:03 UTC, ZephyrTFA commented on code/modules/admin/admin_ranks.dm
> +	for(var/datum/admin_rank/R in GLOB.protected_ranks)
```suggestion
	for(var/datum/admin_rank/R as anything in GLOB.protected_ranks)
```

2024-03-08 15:03 UTC, ZephyrTFA commented on code/modules/admin/admin_ranks.dm
> +	for(var/datum/admin_rank/R in GLOB.admin_ranks)
```suggestion
	for(var/datum/admin_rank/R as anything in GLOB.admin_ranks)
```

2024-03-08 15:03 UTC, ZephyrTFA commented on code/modules/admin/admin_ranks.dm
> +	for(var/datum/admin_rank/R in GLOB.protected_ranks)
also can you change these to not be single letter var names

2024-03-08 15:03 UTC, ZephyrTFA commented on code/modules/admin/admin_ranks.dm
> +		sql_admins += list(list("ckey" = A.target, "rank" = A.rank_names()))
```suggestion
	for(var/holder_ckey in GLOB.protected_admins)
		var/datum/admins/holder = GLOB.protected_admins[holder_ckey]
		sql_admins += list(list("ckey" = holder.target, "rank" = holder.rank_names()))
```

2024-03-08 15:03 UTC, ZephyrTFA commented on code/modules/admin/admin_ranks.dm
> +	for(var/datum/admin_rank/R in GLOB.admin_ranks)
```suggestion
	for(var/datum/admin_rank/R as anything in GLOB.admin_ranks)
```

2024-03-17 01:01 UTC, san7890 commented
Would this solve #59823 btw

2024-04-02 05:31 UTC, Jordie0608 commented
rip

2024-04-02 05:50 UTC, merged