Adds a persistent piggy bank to the vault.
tgstation/tgstation pull request #81900
Opened 2024-03-08 18:58 UTC by Ghommie

## About The Pull Request
This PR adds a **persistent** piggy bank to the station vault that, while it can hold up to a relatively meager amount of 2000 credits, carries stored cash between shifts.

## Why It's Good For The Game
I put some effort coding persistent piggy banks when making a PR for the museum away mission a while ago (which apparently isn't enabled yet because the key holders forgot ig). It'd be a shame of all the existing code were only used for that specific instance.

## Changelog

:cl:
add: Added a persistent piggy bank to the vault, which can carry up to a modest 2000 credits worth of dosh between rounds.
/:cl:

2024-03-08 19:20 UTC, san7890 requested changes

2024-03-08 19:20 UTC, san7890 commented on code/game/objects/items/piggy_bank.dm
> +	desc = "A pig-shaped money container made of porkelain, and containing the station's emergency savings, carried between shifts, oink. <i> Do not throw.</i>"
```suggestion
	desc = "A pig-shaped money container made of porkelain, and containing the station's emergency savings, carried between shifts, oink. <i>Do not throw.</i>"
```

spacing will look wack

2024-03-08 22:20 UTC, EricZilla commented
Thats friggen hilarious, stowing some credits for later on a wealthy shift for lowpop hours to buy iron

2024-03-09 20:22 UTC, SomeoneYouProbablyKnow commented
Wish you could increase the capacity but any more would just be too abusable. The 1 2 punch of non antag shift make a bunch of money antag shift speed buy 20 sm shadds. 
Maybe with a limit on how much you can put in every shift a higher max could work. But this is really neat either way

2024-03-14 17:47 UTC, merged