Puts Deathmatch map names, keys in line with each other (WARNING: LETHAL DOSES OF SNAKECASE INSIDE)
tgstation/tgstation pull request #81970
Opened 2024-03-12 18:16 UTC by Rhials

## About The Pull Request

This does a bunch of cleaning up with regards to Deathmatch map names, keys, filenames, etc.

Quick summary -- Filenames/map keys now have underscore spacing and have been mostly. Deathmatch now has its own root folder instead of just being in map_files (this might not really be necessary idk why I did this). Map filenames and map keys should be consistent now in terms of spacing, capitalization, and what they actually refer to. 

Some of the capitalization changes to filenames wouldn't go through. The cause of this problem is probably much bigger than me but it didn't cause any issues in testing so whatever.

## Why It's Good For The Game

"Backalley" is actually called "raidthebase" internally. Arenastation doesn't use the "Arena" map, instead using the one called "Star Wars" (The underground thunderdome uses the "Arena" map, actually). Guess which one was internally called "chinatown" and get a prize!

This makes a lot of the map stuff related to Deathmatch easier to read and less inconsistent. I know consistency isn't super important but it annoys me personally and I need to address it.

## Changelog

:cl: Rhials
code: Deathmatch files, map names, and keys should all be consistent now.
/:cl:

2024-03-12 18:58 UTC, ZephyrTFA requested changes

2024-03-12 18:58 UTC, ZephyrTFA commented on _maps/Deathmatch/Maint_Mania.dmm
lowercase the dmm files and sub-directory

2024-03-12 20:38 UTC, Rhials commented on _maps/Deathmatch/Maint_Mania.dmm
I'm trying but github desktop won't recognize case changes in file names aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

2024-03-13 16:19 UTC, EEASAS commented
thanks for renaming the map files, when i was creating backalley i had different plans but then just decided to make backalley instead

2024-03-18 20:31 UTC, Ghommie approved these changes

2024-03-18 20:36 UTC, merged