Adds an automatic speech system in hypno grenades that automatically blurts out an hypnotic command that you can set.
tgstation/tgstation pull request #82078
Opened 2024-03-18 15:03 UTC by Singul0

## About The Pull Request
Makes it so that you can set a specific phrase/command/message that is uttered automatically immediately after the hypnotic grenade triggers hypnotic stupors in people, This makes it far less clunky and risky to use on masses of people (it's intended purpose) before a rogue message from the area or radio takes the phrase hold.

## Why It's Good For The Game
Hypnotic grenades, with it's steep cost of 12 TC (1TC MORE of that of the **syndicate bomb**), at it's current state. is extremely clunky and risky to use. since it's very easy to blurt out your hypnotic phrase too early or too late (remember, without protection. you yourself are suceptible to to it's effect and stun) before someone says something stupid, it doesn't even have to be in-person but through the radio too.

This is especially important since it's intended to be used on groups of people, whereas the more conventional and harder to use hypno flash is used on individuals primarily.

This PR makes it so that it's far more easy and less clunky to use hypnotic grenades.

## Changelog

:cl:
qol: made hypno grenades far more easier to use, by making it so that you can set an hypnotic text that blurts out when the grenade is triggered
/:cl:

2024-03-18 15:10 UTC, Singul0 commented
> I think the fact that you use it to affect large groups of people is _why_ it can easily be subverted by someone saying "Ling maints" at the wrong time.

Is it not intended to be used for groups of people? If you want to limit hypnotizing people to be on an individual basis, the hypnoflah already exists, and doesn't affect you yourself if you don't have protection. By the hypnogrenade being so volatile to use on it's sole purpose is an intended effect. it kinda makes it useless to use

2024-03-18 15:12 UTC, the-orange-cow commented
Sunglasses and earmuffs are relatively easy to get to protect yourself, and I think there is something that can block comms in a short range in the tot shop.

2024-03-18 15:32 UTC, Jacquerel commented
It is difficult to use because it can convert a room full of people (you can net quite a lot, as recently demonstrated, by using it in conjunction with the crab phone) into pseudo-antagonists. This is why it has a chance of failure.
I'd actually be _happier_ with you making it cheaper than making it more reliable.

I think that if this item said "throw this into a room and it will turn most of the people in there into revs" it would be obviously regarded as a bad idea even for 12tc. That is functionally what this would be, if you could always reliably guarantee that they would definitely hear exactly what they want you to hear without any other prep.

2024-03-18 15:38 UTC, Singul0 commented
> It is difficult to use because it can convert a room full of people (you can net quite a lot, as recently demonstrated, by using it in conjunction with the crab phone) into pseudo-antagonists. This is why it has a chance of failure. I'd actually be _happier_ with you making it cheaper than making it more reliable.
> 
> I think that if this item said "throw this into a room and it will turn most of the people in there into revs" it would be obviously regarded as a bad idea even for 12tc. That is functionally what this would be, if you could always reliably guarantee that they would definitely hear exactly what they want you to hear without any other prep.

Eh, i'm honestly fine with it being implemented as it was intended to be in it's original design. where it's unreliable and volatile but at a relatively cheap price (6TC). Though that is kind-of a bit cheap. maybe in-line with the hypnoflash 7TC and a warning for it's volatility?

2024-03-18 16:24 UTC, MrMelbert commented
![image](https://github.com/tgstation/tgstation/assets/51863163/55e155d2-1fdd-4a35-8e09-0e3ecfafb58d)

2024-03-18 16:35 UTC, moocowswag commented
Just use it with radar jammer or after sabotaging tcomms to reduce interference. Hypnogrenade has a very high (round altering) pay out at the expense of a very high skill ceiling and no skill floor

2024-03-18 16:42 UTC, Profakos commented
Its not just radio interference. I have fond memories of a round when someone uneffected by it said "oh no", setting this as the command for every hypnotized victim. Honestly more fun than the alternative would have been, with the usual of declaring yourself as the captain.

2024-03-18 17:07 UTC, Jacquerel commented
I'm not going to pick for you exactly what to do to buff this item as then I could just make the PR myself, but I'm happy with a number of the things you have mentioned that aren't what the existing PR is

2024-03-18 18:15 UTC, Profakos commented
> I'm not going to pick for you exactly what to do to buff this item as then I could just make the PR myself, but I'm happy with a number of the things you have mentioned that aren't what the existing PR is

Oh sorry, I should have clarified that I am against this PR because it would make this too easy to use for its potential strength, and would make the situation I described not exist.

2024-03-18 18:16 UTC, Jacquerel commented
> > I'm not going to pick for you exactly what to do to buff this item as then I could just make the PR myself, but I'm happy with a number of the things you have mentioned that aren't what the existing PR is
> 
> Oh sorry, I should have clarified that I am against this PR because it would make this too easy to use for its potential strength, and would make the situation I described not exist.

I should have clarified via quoting that I was talking to the PR author 😅

2024-03-18 22:32 UTC, SimplySmiley123 commented
> Just use it with radio jammer or after sabotaging tcomms to reduce interference. Hypnogrenade has a very high (round altering) pay out at the expense of a very high skill ceiling and no skill floor
> 
> Raising the skill floor would force nerfs to the skill ceiling

The interferance is other people talking with each other.
You wanna use it on a group of people.
Groups of people, do talk with each other more often then not.

2024-03-19 00:14 UTC, ATH1909 commented
> > Just use it with radio jammer or after sabotaging tcomms to reduce interference. Hypnogrenade has a very high (round altering) pay out at the expense of a very high skill ceiling and no skill floor
> > Raising the skill floor would force nerfs to the skill ceiling
> 
> The interferance is other people talking with each other. You wanna use it on a group of people. Groups of people, do talk with each other more often then not.

being sent into a trance mutes you, although people with ear or eye protection wouldn't be muted.

2024-03-19 00:24 UTC, Singul0 commented
Removed the automatic hypno phrase system altogether, reduced the cost and added warnings with how finnicky it is

2024-03-19 00:36 UTC, Jacquerel requested changes

2024-03-19 00:36 UTC, Jacquerel commented on code/game/objects/items/grenades/hypno.dm
> +		It seems you can set an hypnotic phrase that's uttered when triggered"
```suggestion
	desc = "A modified flashbang which uses hypnotic flashes and mind-altering soundwaves to induce an instant trance upon detonation."
```

2024-03-19 00:36 UTC, Jacquerel commented on code/modules/uplink/uplink_items/device_tools.dm
> +		Ensure proper protection and instant uttering of hypnotic command before triggering the grenade."
```suggestion
	desc = "A modified flashbang grenade able to hypnotize targets. The sound portion of the flashbang causes hallucinations, and will allow the flash to induce a hypnotic trance to viewers. \
		Equipment to protect yourself from the effects are not provided. Ensure you are ready before pulling the pin."
```
I don't think the wording as you provided it works for the in-character uplink, in fact I think your wording is actively misleading (it sounds like you should say the command before triggering the grenade).

2024-03-19 00:50 UTC, Higgin commented
might want to change the PR title to reflect the shift in direction, but making them cheaper in quantity and putting in a warning are both positive changes

2024-03-19 07:33 UTC, XDTM commented
Don't forget the changelog as well

2024-03-19 10:29 UTC, Singul0 commented
>If those are your issues with it just make it into a box which has earmuffs sunglasses the grenade itself and a voice recorder for easier messaging and maybe a short one use comms jammer.

That just removes all the short quests you usually do to use the item effectively, IMO that just serves the same purpose in my original pr without addressing the problems that lies with said implemention. except it's down from 100% reliable on non-protected targets to 95% and you're also stuck with a surprising amount of leftover tools you get after using the singleuse grenade.

>6 TC is also neat but let me tell you right now it will be too strong. There are ways to use it well, it's just most older players don't bother because stun click with esword till dead. You make it 6 TC and get ready for it to be an annoying mainstay item.
> I sentence you to relax and use your next traitor roll to get a surplus crate instead of the same "efficient" loudout you've been using for years.

chief, the reason i'm pushing this PR so intensely is because of how fine-tuned the meta for traitors are, mostplayers would stick to your regular old surface level mechanic weapons like eswords, guns to murderbone instead of engaging with deeper mechanics and interactions of the game (people usually pick the boring old meta instead of spending time to do gimmicks that's uncertain to work) by making these niche gimmicks gadgets actually bearable to use is one step to decrease that prevalence of boring murderbone meta-gear.

Also, i'm willing to bet it's not going to be a meta-mainstay item. at least not to the point of eswords, revolvers. The meta you usually see are powerful standard weapons and QoL gadgets. These kinds of stuff have never ever been popular to the playerbase (case and point the hypnoflash. a pretty powerful item only being used occassionally). If it does get too much of a meta item. limiting it to 2-3 purchases only is enough of a fix. you gotta remember that this shit costs a lot for a single use items. whereas most other items at traitors disposal are tools that can be used multiple times

2024-03-20 14:40 UTC, Dawnseer commented
Because if there's anything we've learned from recent discussions, it's that not enough hypnosis is going on.

2024-03-20 19:15 UTC, optimumtact commented
this change smells like salt to me.

2024-03-20 19:15 UTC, closed without merging

2024-03-21 04:28 UTC, Singul0 commented
Eh, it wasn't oh well