Colossus and icemoon megafauna no longer dust
tgstation/tgstation pull request #82134
Opened 2024-03-20 22:33 UTC by 1393F

## About The Pull Request
continuation of https://github.com/tgstation/tgstation/pull/77731

colossus no longer dusts, this also applies to the icemoon megafauna as they use a subtype of colossus projectiles

## Why It's Good For The Game
>shaft miners are already hard to recover(or impossible in the case of dusting), having to go through lavaland and likely near the megafauna itself. This should still be punishing enough for losing to a megafauna as it removes their heart, lungs and liver from their body while still leaving it intact, just easier to recover.

this is still true for icemoon, and colossus. Getting a miner out of the demonic-frost miner arena, let alone the wendigo arena is near impossible without the hand tele, as you have to kill said megafauna to escape, if their corpse didn't get dusted to begin with.

## Changelog

:cl:
balance: colossus, wendigo, and demonic-frost miner no longer dust with their projectile attacks
balance: the above megafauna will also heal from their projectile kills
/:cl:

2024-03-21 00:43 UTC, optimumtact commented
hugbox change :-1:

2024-03-21 01:13 UTC, 1393F commented
> hugbox change 👎 leave colossus alone, he is the final boss of lavaland.

Could you elaborate further? Do you only care about colossus regarding this change?

2024-03-21 01:16 UTC, optimumtact commented
yes i only care about colossus, and I think he should dust you still.

2024-03-21 01:36 UTC, the-orange-cow commented
> hugbox change 👎 leave colossus alone, he is the final boss of lavaland.

I'm completely impartial to this PR, but as a fact check, Wendigo and demonic frost miner are way harder than colossus.

2024-03-21 01:45 UTC, optimumtact commented
right but that doesn't not make colossus the final boss of lavaland it just makes them and him poorly balanced.

2024-03-21 02:16 UTC, newfren commented
isn't the legion the final boss it has the bridge and the door and shit

2024-03-21 02:30 UTC, 1393F commented
colossus is no longer effected by this change

2024-03-21 02:45 UTC, optimumtact commented
> isn't the legion the final boss it has the bridge and the door and shit

legion is pretty cringe

2024-03-22 00:55 UTC, san7890 requested changes

2024-03-22 00:55 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/megafauna/demonic_frost_miner.dm
> +		return
this is some insanely bad indentation. you can definitely add some early returns in here

2024-03-22 00:55 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
> +	if(isliving(target))
ditto on adding early returns... also couldn't you make a common proc on `/obj/projectile` or something where you could just invoke it and listen for the result?

2024-03-22 00:57 UTC, san7890 commented on code/modules/mob/living/simple_animal/hostile/megafauna/wendigo.dm
> +	if(isliving(target))
just anything to cut down on the copypaste really because stuff like this tends to desync from each-other fast

2024-03-22 09:43 UTC, closed without merging