Bumping into a door in a stealth implant opens the door (if you have access)
tgstation/tgstation pull request #82224
Opened 2024-03-25 16:01 UTC by Xander3359

## About The Pull Request
Bumping into a door in a stealth implant opens the door (if you have access)

## Why It's Good For The Game
![image](https://github.com/tgstation/tgstation/assets/66163761/d00bf8b6-5a60-4c64-8035-27c400b1960d)
Reduces jank by allowing stealth boxes to open doors.

## Changelog

:cl:
qol: You can now open airlocks (That you have access to) while inside a stealth implant box
/:cl:

2024-03-25 19:39 UTC, moocowswag commented
I wanna call it balance since it removes those moments of exposure that was probably intended but the fact of the matter is it is pretty tedious to have to do that at every airlock.

2024-03-26 03:28 UTC, san7890 requested changes

2024-03-26 03:28 UTC, san7890 commented on code/game/objects/items/implants/implant_stealth.dm
> +			A.Bumped(mob_in_box)
```suggestion
	if(istype(A, /obj/machinery/door))
		for(var/mob/mob_in_box in contents)
			A.Bumped(mob_in_box)
```

`contents` is not guaranteed to be a list of only mobs so let's avoid `as anything` and err on the side of caution with the typecheck. probably really wasteful to have to call Bumped() on useless stuff like that too

2024-03-26 06:23 UTC, YakumoChen commented
Does this just affect the implant and not all boxes? It really should.

2024-03-29 20:25 UTC, DrAmazing343 commented
It does feel like this should affect all boxes, but overall a solid change. When I use box, often the exposure isn't the nervous part, it's the waiting game of standing outside til nobody's around and then reboxing ad-infinium depending on how many airlocks I need to go through. This'll make life easier.

2024-03-29 21:05 UTC, Xander3359 commented
> It does feel like this should affect all boxes, 

The code can easily be moved down a level, but I was only asked to add it here.

2024-03-30 00:01 UTC, merged