Improved lathe error message
tgstation/tgstation pull request #82260
Opened 2024-03-27 05:49 UTC by lessthnthree

## About The Pull Request

Improves the auto/protolathe low charge error message. Instead of simply saying low power, it will tell you how long until it has enough charge to print.

![image](https://github.com/tgstation/tgstation/assets/83487515/a2aebd3e-b7bf-4a13-ae7a-6c1cc14c9057)

## Why It's Good For The Game

Less mashing the lathe over and over with no idea how much APC charge it needs to start printing again

## Changelog

:cl: LT3
qol: Lathes will now tell you the wait time until they're ready to print
/:cl:

2024-03-27 06:18 UTC, Pickle-Coding commented
Cool concept. I think the calculation for the time for an APC to reach a certain amount of energy from charging could be a machine and apc proc (bonus points if there's an argument that reduces the energy target by the grid energy).

2024-03-27 06:19 UTC, lessthnthree commented
> Cool concept. I think the calculation for the time for an APC to reach a certain amount of energy from charging could be a machine and apc proc (bonus points if there's an argument that reduces the energy target by the grid energy).

Yeah there's nothing in the calculation specific to the lathes, I can move it to the APC.

2024-03-28 16:51 UTC, san7890 requested changes

2024-03-28 16:51 UTC, san7890 commented on code/modules/power/apc/apc_main.dm
> +		return round(energy_to_power(required_joules / trickle_charge_power) * SSmachines.wait + SSmachines.wait, SSmachines.wait)
```suggestion
		return round(energy_to_power(required_joules / trickle_charge_power) * SSmachines.wait + SSmachines.wait, SSmachines.wait)
	
	return null
```

let's be explicit here so people who need to create new consumers of this proc know what to expect

2024-04-02 09:31 UTC, merged