Admins must now complete math problems to admin
tgstation/tgstation pull request #82341
Opened 2024-03-31 12:34 UTC by ZephyrTFA

## About The Pull Request

See title.
![image](https://github.com/tgstation/tgstation/assets/12817816/6a289161-0103-419b-b194-44629c99b901)

## Why It's Good For The Game

We need to ensure that the admins on the server are fully mentally prepared to administrate. As such we can ensure this by giving them math problems that they need to solve.

## Changelog

:cl:
admin: Admins are now required to complete math problems before being allowed to admin.
/:cl:

2024-03-31 12:38 UTC, jlsnow301 approved these changes
it's about time someone takes this issue seriously

2024-03-31 13:16 UTC, Higgin commented
it's over

2024-03-31 17:27 UTC, Draggeru commented
I just spent 500 dollars on plushies, I don't think I'm cut out for adminning anymore

2024-03-31 19:04 UTC, atlasle commented
which tramstation train arrives first

2024-03-31 21:54 UTC, LemonInTheDark requested changes

2024-03-31 21:54 UTC, LemonInTheDark commented on code/modules/admin/admin_math.dm
> +	if(ckey in failure_timers)
it is more efficent to do [] then in

2024-04-02 07:23 UTC, ZephyrTFA reviewed
turns out admins can't do math

2024-04-02 07:23 UTC, closed without merging