[april fools] Makes robotics more realistic
tgstation/tgstation pull request #82351
Opened 2024-03-31 19:54 UTC by NamelessFairy

## About The Pull Request

SS13 mech construction is extremely unrealistic, you just print parts at the mechfab and stick them together. This PR remedies this and helps put a greater enthesis on realism.

## Why It's Good For The Game

Gives players a sense of pride and accomplishment when assembling a mech.

## Changelog

:cl:
qol: Players familiar with IRL robot construction will now be able to apply their experience to the ingame version
/:cl:

2024-03-31 21:39 UTC, Wallemations approved these changes
My set didn't ship with

2024-03-31 21:52 UTC, LemonInTheDark requested changes

2024-03-31 21:52 UTC, LemonInTheDark commented on code/modules/vehicles/mecha/mecha_parts.dm
> +	if(runner == TRUE)
why do you do if(runner) in some places and if(runner == true) in others

2024-03-31 21:52 UTC, LemonInTheDark commented on code/modules/vehicles/mecha/mecha_parts.dm
> +			underlays.Cut()
please don't

2024-03-31 21:52 UTC, LemonInTheDark commented on code/modules/vehicles/mecha/mecha_parts.dm
> +	if(color)
what's it for?

2024-04-01 02:11 UTC, ArcaneMusic commented
Oh god damnit it's a gundam reference

2024-04-02 09:20 UTC, closed without merging