Explosions Part I - Directional Explosions
tgstation/tgstation pull request #82429
Opened 2024-04-03 16:22 UTC by Thunder12345

## About The Pull Request

Adds the ability for explosions to be directional. This is achieved by adding an angle check to `prepare_explosion_turfs()` to drop any turfs outside the cone of the explosion. If the arc covers a full 360 degrees, as is the default, it will accept all the turfs without performing the angle check.

Uses this functionality to rework both rocket launcher backblast and X4 explosions. Rocket launcher backblast has been changed from a shotgun of indendiary bullets to a directional explosion of similar length. X4 now uses a directional explosion to "ensure user safety".

Apparently the old method of moving the explosion one tile away didn't even work, as it blew up `target` before trying to check its density for the directional behaviour.

https://youtu.be/Mzdt7d7Le2Y

## Why It's Good For The Game

Directional explosions - Useful functionality for a range of potential use cases, which can be implemented with minimal extra processing cost (Worst case scenario being very large directional explosions)

Backblast - Looks way cooler than a bunch of projectiles, and should be significantly more functional in high-lag situations where projectile code tends to get fucky

X4 - More predictable for players wanting to use it as a breaching charge, you can actually stand near the charge and not have to worry about being hoist upon your own petard.

## Changelog

:cl:
add: Added support for directional explosions.
add: Rocket launcher backblast is now 271% more explosive, check your six for friendlies!
add: X4 charges now explode in a cone away from the user when placed on a sufficiently solid object.
fix: X4 charges will now behave correctly when placed on dense atoms (note: don't try to read a variable from an atom you just blew up)
/:cl:

2024-04-03 17:25 UTC, Rhials commented on code/__DEFINES/explosions.dm
> +///
You're missing a comment!!!!!!

2024-04-03 18:43 UTC, Paxilmaniac commented
Directional explosions sounds like I can get up to a lot of trolling with rocket launcher code, this will be bad for the space carp season.

2024-04-03 21:59 UTC, Dawnseer commented
Now here's hoping someone will bring this new advanced directional technology to pipebombs, so I can finally make my IED with a lovely 'this side towards tiders' stickers slapped on

2024-04-07 12:21 UTC, Time-Green requested changes
Nice work! Some small suggestions to help with clarity

2024-04-07 12:22 UTC, Time-Green commented on code/controllers/subsystem/explosions.dm
> +	var/first_angle_limit = WRAP(explosion_direction - explosion_arc/2, 0, 360)
I forgot to explain but multiplication is just faster in byond

2024-04-07 13:11 UTC, DrDiasyl commented
We now need to give Nukies claymores so they can have true CoD experience

2024-04-08 04:51 UTC, carlarctg commented
Nominative Determinism strikes again

2024-04-09 02:35 UTC, deathrobotpunch commented
TG: THE CLAYMORE UPDATE

2024-04-09 18:26 UTC, merged