adds prefrences to transhumanist
tgstation/tgstation pull request #82435
Opened 2024-04-03 23:54 UTC by Skeleton-In-Disguise

## About The Pull Request
You may remember this, that's because I accidentally deleted it before while trying to change things. Anyways! 
Adds drop-down selections and new options to transhumanist. also fixes a minor typo
Previously, you could choose your replaced limb by taking prosthetic limb, setting what you want changed, and then switching to transhumanist, since they used the same preference previously.

## Why It's Good For The Game

Transhumanist felt strange because it was hypothetically a voluntary operation, but the augmentation clinic just spun the wheel on what you got replaced. From a role-playing perspective, being unable to choose is uninteresting and confusing. Also it always says your limb being was being replaced with a robotic arm and that annoyed me. Now that you are able to select your replacement part, I've added two new options, the robotic voice box, good for a more prominent change then a limb that will be hidden for most of a round, and flashlight eyes, for when you are truly committed to being rushed directly to robotics seeing the bright future ahead of humanity!

## Changelog
:cl:
add: Transhumanist now allows you to select your augmentation
add: Transhumanist can now provide a robotic voice box, or flashlight eyes
spellcheck: Transhumanist's roundstart text has been re-written to not be wrong
/:cl:

2024-04-04 00:19 UTC, newfren commented
flashlight eyes might be a noob trap?

2024-04-04 00:25 UTC, san7890 requested changes
this is why your code is failing to compile

2024-04-04 00:25 UTC, san7890 commented on code/datums/quirks/neutral_quirks/transhumanist.dm
> +		slot_string = [new_bodypart.plaintext_zone]
```suggestion
		slot_string = new_bodypart.plaintext_zone
```

2024-04-04 00:25 UTC, san7890 commented on code/datums/quirks/neutral_quirks/transhumanist.dm
> +			slot_string = [new_organ.name]
```suggestion
			slot_string = new_organ.name
```

2024-04-04 01:21 UTC, 00-Steven commented
o7

2024-04-04 05:19 UTC, dopamiin0 commented
> flashlight eyes might be a noob trap?

ok but it's a really funny one and its not like its that hard to go get a fresh pair of eyes installed

2024-04-05 01:06 UTC, san7890 commented
i think "flashlights for eyes" is pretty descript enough, i was apprenhensive about it at first glance but it's not "flashlight eyes", the `for` does the heavy lifting there. also this will affect literally one round at most if people don't particularly like it, this is a game with a lot of zaniness (it would be sad if they got filtered by this but like... c'mon now there's far worse things) and one round of out of hundreds that any given player might partake in will not matter very much

2024-04-06 21:19 UTC, merged