[no gbp] sleeping carp gloves also work on mind init
tgstation/tgstation pull request #82599
Opened 2024-04-11 15:56 UTC by mc-oofert

## About The Pull Request

sleeping carp gloves also work on mind init

this means for the sake of deathmatch you dont have to put them off and on

## Why It's Good For The Game

fixes #82321

## Changelog

:cl:
fix: you no longer need to put your sleeping carp gloves off and on in Deathmatch to get the martial art
/:cl:

2024-04-11 18:22 UTC, Jacquerel commented
why are you denying yourself gbp for what seems like a fix to a bug you didnt add

2024-04-12 04:45 UTC, mc-oofert commented
> why are you denying yourself gbp for what seems like a fix to a bug you didnt introduce

i made the loadout AND the item bro

2024-04-12 09:17 UTC, Jacquerel commented
if you made the item several years ago nobody is going to give a shit about you fixing a bug now but you may hold fast to your honour if you so desire

2024-04-16 01:22 UTC, MrMelbert reviewed
If this is an issue with these gloves it is likely an issue with all the other items which grant martial arts on equip. Maybe we should make this a component?

2024-04-16 07:14 UTC, mc-oofert commented
> If this is an issue with these gloves it is likely an issue with all the other items which grant martial arts on equip. Maybe we should make this a component?

ok

2024-04-17 05:43 UTC, san7890 requested changes
these don't need SIGNAL_HANDLER because they don't directly receive signals, and since we invoke them with procs that already have `SIGNAL_HANDLER` then it's already audited for sleeps regardless

2024-04-17 05:43 UTC, san7890 commented on code/datums/components/martial_art_giver.dm
> +	SIGNAL_HANDLER
```suggestion
```

2024-04-17 05:43 UTC, san7890 commented on code/datums/components/martial_art_giver.dm
> +	SIGNAL_HANDLER
```suggestion
```

2024-04-17 17:52 UTC, merged