Slightly reduces stun chance and increases ripping limb off time for …
tgstation/tgstation pull request #82796
Opened 2024-04-21 07:05 UTC by NexusLeader

About The Pull Request
Makes gorillas have a cooldown to rip people's limbs off.

Why It's Good For The Game
Gorillas should not be able to rip a person's limb off in 0 seconds. Yes,, they may be strong, but seriously? Maybe a hulked gorilla can do it, if we ever add that.

Changelog

-Gorillas spend time ripping limbs off.

(accidently removed this shit.. uh... oops, first PR.)

2024-04-21 07:17 UTC, NexusLeader commented
-realising i'm drowsy and my ass doesn't wanna do screenshots right now

2024-04-21 07:35 UTC, jlsnow301 commented
please fix your PR formatting so it will show in game

2024-04-21 13:15 UTC, DaydreamIQ commented
So why did you also nerf the punch stun chance without mentioning that in the PR at all?

2024-04-21 15:32 UTC, Jacquerel commented
It would also be useful to expand your "why it is good for the game" reasoning as currently what you have written is basically "this is self-evidently a good change"
Gorillas have delimbed people on attacking them for years, so it actually isn't self-evident why it needs changing now

2024-04-21 17:12 UTC, NexusLeader commented
testing pr today

2024-04-21 17:14 UTC, NexusLeader commented
> It would also be useful to expand your "why it is good for the game" reasoning as currently what you have written is basically "this is self-evidently a good change" Gorillas have delimbed people on attacking them for years, so it actually isn't self-evident why it needs changing now
> 
> and as implied in the previous comment, it contains no justification for altering a stun chance at all

it's because gorillas are wayy too overpowered in their current state of being able to rip a limb off. That includes, the head. You can kill someone in less then a second by ripping off their head. And yes, the stun chance? It was mostly about the gorilla ripping off time. I will edit that.

2024-04-21 17:33 UTC, NexusLeader commented
tested - no issues; going to republish draft
![image](https://github.com/tgstation/tgstation/assets/137661332/ee789046-ab34-4860-b3b7-bf25eaf20c4d)

2024-04-21 18:36 UTC, Jacquerel commented
Please like... open a new PR, copy the template from that, and then reformat your stuff to fit into it.
The changelog part is important because we have a bot that scrapes the PR body and if you haven't formatted it as the template tells you to, it won't work and the in-game changelog won't be updated with your change.

2024-04-21 22:18 UTC, IndieanaJones commented
Pretty sure gorillas can't tear people's heads off, just their limbs.

2024-04-21 22:56 UTC, Jacquerel commented
> Pretty sure gorillas can't tear people's heads off, just their limbs.

`list/target_zones = list(BODY_ZONE_L_ARM, BODY_ZONE_L_LEG, BODY_ZONE_R_ARM, BODY_ZONE_R_LEG)`
This is correct

2024-04-22 23:52 UTC, jlsnow301 requested changes
Fix your PR template

2024-05-08 00:05 UTC, closed without merging