Removes the stun from longfall modules activating.
tgstation/tgstation pull request #82824
Opened 2024-04-22 09:48 UTC by necromanceranne

## About The Pull Request

What it says on the tin. When you fall with the longfall module active, you do not get stunned. If you fall from more than one z-level, however, you will be staggered from the fall, with a length based on the number of levels fallen.

## Why It's Good For The Game

I noticed that while using these as a felinid that I actually was stunned utilizing them. dropping the equipment I was carrying and being rooted in place for a bit. And I thought to myself 'wait, hang on, by taking this thing out, out I'm actually WAY better off than if I kept them in, what gives?'

They just got powercreeped, unfortunately. Freerunner and being a catgirl is stronger than this very niche module, because they're equipment independent and also not a hard stun (I know faceplanting with freerunner is still a bit of a stun, but you can still move and potentially avoid losing equipment by falling while prone). 

And maybe it functions a lot stronger in situations where those two traits just don't apply (or apply in a very negative fashion in the case of felinids), I don't see why they shouldn't be superior to those traits. You have to have a modsuit, and you need to be on a map that makes use of multi-z. And additionally be in gravity. Typically, I would think equipment benefits should be stronger than innate/roundstart features.

Most of the time, it is easier and more beneficial to be in constant flight while using a modsuit than to prepare for longfalling.

So let's just make it better overall. I don't know how many people would even use it, but I know I will and I love tossing myself into the void below.

## Changelog
:cl:
balance: Longfall modules no logner stun you when they activate.
balance: Falling from a height greater than one z-level while using the longfall module will still stagger you.
/:cl:

2024-04-22 16:22 UTC, MrMelbert commented
I always thought this stun was to mimic a Superhero Landing

2024-04-22 17:51 UTC, carlarctg commented
The longfall module as a concept is very cool. Tactically dropping onto lower ground to gain an advantage over enemies is sick.

This is completely ruined if it has a 4-second stun, what the shit. Please fix ❤️

2024-04-23 01:38 UTC, ZephyrTFA requested changes
I would rather we make other long falls, such as the species one, have this stun.
And then make this long fall module onlyhave 10% of the normal stun duration.
Power creep is bad and that's what this is.

2024-04-23 02:53 UTC, necromanceranne commented
I'm not doing a felinid balance pr, zephyr.

2024-04-23 11:46 UTC, Fikou commented
> I always thought this stun was to mimic a Superhero Landing

it was, but i agree with anne if we have made options that are stronger than this thing you have to specifically slot in to your suit with your limited complexity, usable on only specific maps, that you have to print out first its kind of a fail.

2024-04-24 00:51 UTC, merged