The armoury contraband locker guns have a chance to be rigged.
tgstation/tgstation pull request #83167
Opened 2024-05-09 23:29 UTC by Pickle-Coding

## About The Pull Request
Gives a 10% chance for the handguns in the armoury to be rigged.

## Why It's Good For The Game
Improves contraband locker RP.

## Changelog

:cl:
balance: There are reports of malfunctioning guns being confiscated.
/:cl:

2024-05-09 23:57 UTC, Helg2 commented
Pr is funny, but "rigged" isn't quite informative.

2024-05-10 05:11 UTC, SomeoneYouProbablyKnow commented
A glace at the changes shows that it's just the big revolver and it has a 10% chance to be reversed. 

I think that's not a good way of doing this. It's subject to easy checking and metagaming (just the things the type of player to loot armour roundstart is going to do). You don't have to worry about any other gun like the makarov or the shotgun or whatever and as long as you shoot it once you can be certain it won't backfire on you later.

I know it's more work but if you want to do this right the backfire should be a % chance akin to modified det gun and should effect most guns that spawn in the locker. That way testing or metagming this feature is much harder.

2024-05-10 11:18 UTC, mc-oofert commented
the contraband locker shouldnt even start with guns anyway

2024-05-10 11:44 UTC, Jackal-boop commented
Meh. I don't like this. Easily meta game able and could fuck over antags raiding the armoury

2024-05-10 12:23 UTC, Jacquerel commented
I don't know what I would do instead of this but I don't think this solution effectively solves any problems, nor does it really make any sense.
You also failed to actually write a "why is this good for the game section" which is the actual reason I am applying this label: that isn't optional. Tell us what problem you think this _is_ solving and why this is the right solution, because right now I do not see it.

2024-05-10 12:54 UTC, Pickle-Coding commented
> A glace at the changes shows that it's just the big revolver and it has a 10% chance to be reversed.

The other guns (except the combat shotgun since that's not necessarily syndicate, but maybe I could add that in since it's in the contraband locker for a reason) can spawn with a clown firing pin. At minimum it would humiliate the user, and worst case scenario for them they get exploded.

> I think that's not a good way of doing this. It's subject to easy checking and metagaming (just the things the type of player to loot armour roundstart is going to do). You don't have to worry about any other gun like the makarov or the shotgun or whatever and as long as you shoot it once you can be certain it won't backfire on you later.
> 
> I know it's more work but if you want to do this right the backfire should be a % chance akin to modified det gun and should effect most guns that spawn in the locker. That way testing or metagming this feature is much harder.

I might look into that.

> I don't know what I would do instead of this but I don't think this solution effectively solves any problems, nor does it really make any sense. You also failed to actually write a "why is this good for the game section" which is the actual reason I am applying this label: that isn't optional. Tell us what problem you think this _is_ solving and why this is the right solution, because right now I do not see it.

Problem: People are too trustworthy of the gear they pick up in the contraband locker. The syndicate managing to trick security to confiscate rigged weapons to backfire them in a future operation sounds like something they would do.

Solution: Rig the weapons in the contraband locker. If someone was too trustworthy of the syndicate gear they are playing with, now they found out. If people are being wary over the syndicate gear in the contraband locker, well now they're treating it like contraband, which is fine.

2024-05-10 13:08 UTC, SomeoneYouProbablyKnow commented
> The other guns (except the combat shotgun since that's not necessarily syndicate, but maybe I could add that in since it's in the contraband locker for a reason) can spawn with a clown firing pin. At minimum it would humiliate the user, and worst case scenario for them they get exploded.

Kickass, only like 5 people know how to remove firing pins anyway.

> Problem: People are too trustworthy of the gear they pick up in the contraband locker. The syndicate managing to trick security to confiscate rigged weapons to backfire them in a future operation sounds like something they would do.

Dios mio, a "realism and lore" justification!

2024-05-10 13:13 UTC, Pickle-Coding commented
> In the PR body please, rather than halfway down the page 😅 Instead of the two sentences you wrote which neither explain what the feature is nor why we should merge it.

Is this enough?

2024-05-10 18:19 UTC, DaydreamIQ commented
This is a funny change but anyone who even remotely knows it exists will just swap out the firing pins anyways. Unless you can somehow make the pin unremovable

2024-05-10 18:40 UTC, DaCoolBoss commented
Lame solution to a non existent problem.

2024-05-10 19:09 UTC, SomeoneYouProbablyKnow commented
> Lame solution to a non existent problem.
Armoury looting seccie detected, deploy point and laugh squadrons.
But really, it's a funny half measure (People sometimes shoot themselves in the face) for a very minor issue (Security looting that locker for no other reason than they can)

2024-05-10 22:04 UTC, SimplySmiley123 commented
> > Lame solution to a non existent problem.
> 
> Armoury looting seccie detected, deploy point and laugh squadrons. But really, it's a funny half measure (People sometimes shoot themselves in the face) for a very minor issue (Security looting that locker for no other reason than they can)

Not like they already loot whatever traitor and now also spy gets caught. Often times for something more impactful then a makarov.
All this is is just flavor.

2024-05-10 22:40 UTC, Iamgoofball commented
definitely make the pins unremovable

2024-05-10 23:08 UTC, Pickle-Coding commented
Done!~ :3

2024-05-10 23:36 UTC, moocowswag commented
Good change, security getting a weapon that 1 or 2 shots people due to round start rng is a meme. Now its a bigger gamble

2024-05-13 22:43 UTC, Pickle-Coding commented
The pin is always unremovable, even if it's not rigged.

2024-05-15 00:36 UTC, Ghommie requested changes

2024-05-15 00:36 UTC, Ghommie commented on code/game/objects/effects/spawners/random/contraband.dm
> +		/obj/item/gun/ballistic/revolver/reverse/mateba = 0.1,
I don't think pick_weight() support decimals. If that's the case, multiply every value in the list by 10.

2024-05-15 05:25 UTC, merged