Adds Minecarts
tgstation/tgstation pull request #83175
Opened 2024-05-10 19:39 UTC by MrMelbert

## About The Pull Request

Designed for use in #83163 , not implemented anywhere else currently. 

Mining cars (existing crate reskin) now have a hefty drag slowdown. 
Click-dragging them onto a minecart rail (new), however, will negate this slowdown, allowing you to drag them at nearly full speed. 
This also gives you the opportunity to give them a bump to push them down the tracks at a decent pace. 

https://github.com/tgstation/tgstation/assets/51863163/293adbfb-e2bd-49ba-beef-c998c388ecf0

Other notes: 
- Running a cable underneath a minecart (underfloor allowed) will power the rail, keeping its momentum, or boosting it slightly if it falls below certain thresholds. 
- If the minecart comes to an abrupt stop with a decent amount of speed, it will chuck all of its contents ahead a few tiles. 
- Break rails also exist, and stop the cart instantly (and with no contents chucking) when powered with cable.
- The cart does hurt people who are standing in the way if it's moving with moderate speed. 
- And it also hurts people lying on the tracks. 

## Why It's Good For The Game

I was struggling to come up with a method of bulk transferring items for the linked PR that didn't seem too contrived (bluespace BS, pods), wouldn't require work refactoring an existing system (transit tubes), and wasn't a tram, and I realized we have mine carts but no rails. 

So I added rails and made the minecarts work on the rails. This gives a method of shipping items from point A to point B that fits well in certain settings, such as the lower areas of Icebox, or maybe in space ruins. 

I also think it would be fun to give miners some tools to construct rails, to let them ship boulders back to the station via railway rather than using teleportation. 

## Changelog

:cl: Melbert
add: Adds Minecarts, (possibly admin only depending on when this PR is merged in relation to the Icebox Bar PR) 
/:cl:

2024-05-10 20:17 UTC, CRITAWAKETS commented
there should be a "launching rail" or something that allows people to click on it for the rail to give the cart a speed boost in a specific direction, just for rideable cart systems.

waiting for when these become buildable so i can make the worst station fast-travel system ever

2024-05-10 20:37 UTC, tralezab commented
this is dope, can't wait to see what kind of horrible maint creation you're cooking

>waiting for when these become buildable

kinda surprised it's not buildable wow

2024-05-10 22:29 UTC, Sadboysuss commented
Would be great if you could buckle people to the rails, finally the tram dilemma in ss13

2024-05-10 23:12 UTC, Wallemations commented
> Minecarts w/ powered rails

 Craftbros, did we win?

2024-05-11 01:24 UTC, MrMelbert commented
I forgot I was gonna add ramps before PRing this so it can go up Z-levels

2024-05-12 12:51 UTC, carlarctg commented
one step closer to vents turning into the extraction mission from drg

2024-05-13 00:48 UTC, Admiral-Gigaton commented
does hitting someone knock them back out of the way? and if so, can you make sure it launches them sideways? that way i cant just get someone on a rail, and infinitely do damage and kill them by them getting launched forwards, in the direction of the minecart (like how the tram throws your corpse typically sideways)

2024-05-13 11:41 UTC, norsvenska requested changes

2024-05-13 14:22 UTC, Admiral-Gigaton commented on code/modules/mining/mine_items.dm
> +	name = "cart rail break"
> should be 'brake', not 'break'

Minor spelling mistake
![Uploading 5xjp.gif…]()

2024-05-13 14:55 UTC, scrunklershrungle932 commented
are rails or minecarts craftable ATM?

2024-05-15 07:12 UTC, MrMelbert commented on code/modules/mining/mine_items.dm
> +	name = "cart rail break"
It's called break because it breaks the speed
```suggestion
	name = "cart rail brake"
```

2024-05-15 07:12 UTC, MrMelbert commented
> does hitting someone knock them back out of the way? and if so, can you make sure it launches them sideways?

Already does

> are rails or minecarts craftable ATM?

No

2024-05-17 05:34 UTC, merged