Adds an element which allow for stuff to have unique sprites depending on whether they are in the inventory or on the floor, and utilizes it
tgstation/tgstation pull request #83199
Opened 2024-05-12 00:02 UTC by YesterdaysPromise

## About The Pull Request

Put it all in the title really, but to specify; balloons, wrenches and surgery tools are done so far, from which balloons already had it for themselves, I just swapped to using the element, and the surgery tools are largely taken from the medicart overlay sprites, just adjusted. I will get the proper pictures when my internet starts cooperating and allows me to run my code, cope with these.

![image](https://github.com/tgstation/tgstation/assets/122572637/4842c33b-708d-43f0-9379-78d76b9128c4)
![image](https://github.com/tgstation/tgstation/assets/122572637/4c160abd-01da-44d3-94f5-5871799fde49)

Going to sleep for now

## Why It's Good For The Game

A lot of the sprites have the issue of looking fine in hand but massively over-sized once you drop them on put them on the table, frequently leading to massive overlaps you gotta navigate through by using shift to search through the pile, and using the resize element ain't perfect for all cases.

## Changelog

:cl:
image: The following will now how unique, downsized sprites while out of the inventory: All wrench variants. All surgery tools, and all their variants.
/:cl:

2024-05-12 00:10 UTC, Jacquerel commented
I'm not totally convinced that we actually _want_ this for most of the things you have put it on.
I can imagine that there are theoreticaly some situations where we want differing inhand and inworld sprites- but I don't think scalpels are one of them.

The in-world sprite is, frankly, the _more_ important of the two to be large.
An item in your hand is already in your hand and under your control, you can basically forget it exists in most cases (except when clicking something in-hand does something).

An item in the world needs to be seen to be visible, and needs to be able to be clicked on.
Hence: They're much larger than you would expect.

That tiny scalpel may be "more accurate to the scale" of the art, but it's hard to see and hard to click. These are both not very desirable traits; we want people to be able to see a scalpel on a table and pick it up without having to hunt individual pixels with their mouse.

2024-05-12 00:16 UTC, dwasint commented
> I'm not totally convinced that we actually _want_ this for most of the things you have put it on. I can imagine that there are theoreticaly some situations where we want differing inhand and inworld sprites- but I don't think scalpels are one of them.
> 
> The in-world sprite is, frankly, the _more_ important of the two to be large. An item in your hand is already in your hand and under your control, you can basically forget it exists in most cases (except when clicking something in-hand does something).
> 
> An item in the world needs to be seen to be visible, and needs to be able to be clicked on. Hence: They're much larger than you would expect.
> 
> That tiny scalpel may be "more accurate to the scale" of the art, but it's hard to see and hard to click. These are both not very desirable traits; we want people to be able to see a scalpel on a table and pick it up without having to hunt individual pixels with their mouse.

to add onto this, if this becomes standard to make world objects scaled down disarm meta would be even worse because of the added difficulty of picking items up

2024-05-12 09:21 UTC, atlasle commented
holy shit this is all i always wanted, also since people have been complaining about the problem in picking up things/seeing things on the ground, what if holding a certain key made sprites on the ground have their larger in hand sprites, and maybe to avoid lag it would only be in an area around your cursor, i feel like that would solve these problems

2024-05-12 16:21 UTC, Watermelon914 requested changes

2024-05-12 16:21 UTC, Watermelon914 commented on code/datums/elements/item_storage_state.dm
> +	src.original_state = original_state
redundant

2024-05-12 16:21 UTC, Watermelon914 commented on code/datums/elements/item_storage_state.dm
> +	original_state = target.icon_state
Set the original_state to base_icon_state or have it passed in as an arg. Latter is probably more preferable since it gives more control.

2024-05-12 20:23 UTC, ZephyrTFA commented on code/datums/elements/item_storage_state.dm
> +	target.update_appearance()
why are we calling update_appearance
We already update the icon_state

2024-05-12 20:23 UTC, ZephyrTFA commented on code/datums/elements/item_storage_state.dm
> +	if(isturf(target.loc))
this needs to be marked as a signal handler
(put `SIGNAL_HANDLER` at the top of the proc body)

2024-05-12 21:12 UTC, thgvr commented
World icons are an incredible workload, and it's really bad if you only have it for a couple things.

2024-05-12 21:15 UTC, thgvr commented
> I'm not totally convinced that we actually _want_ this for most of the things you have put it on. I can imagine that there are theoreticaly some situations where we want differing inhand and inworld sprites- but I don't think scalpels are one of them.
> 
> The in-world sprite is, frankly, the _more_ important of the two to be large. An item in your hand is already in your hand and under your control, you can basically forget it exists in most cases (except when clicking something in-hand does something).
> 
> An item in the world needs to be seen to be visible, and needs to be able to be clicked on. Hence: They're much larger than you would expect.
> 
> That tiny scalpel may be "more accurate to the scale" of the art, but it's hard to see and hard to click. These are both not very desirable traits; we want people to be able to see a scalpel on a table and pick it up without having to hunt individual pixels with their mouse.

One of the solutions I've come to is to give small/hard to click on things a "border" of 1 alpha pixels of varying width, essentially just increasing the clickable area.

2024-05-12 22:59 UTC, Dorsisdwarf commented
> One of the solutions I've come to is to give small/hard to click on things a "border" of 1 alpha pixels of varying width, essentially just increasing the clickable area.

Given that the purpose of making them small is so they take up less space, wont an invisible clickable bubble around them defeat that, and in fact make things worse??

2024-05-12 23:15 UTC, Wallemations requested changes
I honestly don't feel like something large like wrenches are great to use for this
Rather than making big things small this should be used to make small things big
More specifically, bullets and casings could really benefit from having large sprites in-inventory

Having this as an option is good but for wrenches I'm not so sure

2024-05-13 17:59 UTC, thgvr commented
> > One of the solutions I've come to is to give small/hard to click on things a "border" of 1 alpha pixels of varying width, essentially just increasing the clickable area.
> 
> Given that the purpose of making them small is so they take up less space, wont an invisible clickable bubble around them defeat that, and in fact make things worse??

Only visual noise matters really

2024-05-13 21:07 UTC, Dorsisdwarf commented
> Only visual noise matters really

If you can't click an item because another item's invisible bubble is on top of it so you pick that one up, that seems like its kinda an issue is all.

2024-05-13 21:07 UTC, YesterdaysPromise commented
Given the response to this has been overwhelmingly negative, I think I might just close it.

2024-05-18 07:13 UTC, PKPenguin321 commented
worth noting that if youre just rotating and shrinking the sprites that can probably be done with code rather than making individual icons for everything
could make the element configurable so you can set rotation and scale per item
could make it configurable so players can turn it off
could even keep a value to add custom sprites if someone wants to make real ones for certain items idk

2024-05-18 23:34 UTC, closed without merging