[TM ONLY] Hijacked Revision Date for v3 TGS Api
tgstation/tgstation pull request #83227
Opened 2024-05-14 09:42 UTC by ZephyrTFA

Adds revision date generation for the v3 TGS Api.
Because of float precision it usually be within +-8 minutes.
This is better than not having it at all and is something I need for CompileMon

2024-05-14 21:00 UTC, Cyberboss submitted a review, later dismissed
Bruh, the bot is gonna stomp this. Just do it in `getrev.dm` if the major version is 3.

2024-05-14 21:00 UTC, Cyberboss commented on code/modules/tgs/v3210/api.dm
>  			commit = logs[2]
If >= 5 should be after this line

2024-05-14 21:27 UTC, ZephyrTFA commented
did you not read the TM Only line.
This will never get merged and if someone does I will revert it.
This PR will exist until TG updates TGS

2024-07-07 22:14 UTC, optimumtact commented
Figure out a way to make this a compile time define or something I dont want this TM sitting here foreever.

2024-07-08 21:44 UTC, Cyberboss requested changes
If this is going to be merged, do away with the TGS internals hack and handle it in getrev.dm https://github.com/tgstation/tgstation/blob/62edc2f93fd25a4c29cb4f8483199b0c82a80df3/code/datums/helper_datums/getrev.dm#L13

If `world.TgsVersion().major == 3`

2024-07-11 18:54 UTC, closed without merging