Micro-optimizes _SendSignal a bit
tgstation/tgstation pull request #83244
Opened 2024-05-15 16:52 UTC by Watermelon914

## About The Pull Request

Instead of iterating over an assoc list and doing a list access, which has a complexity of O(nlog(n)), it is better to just store a 2 tuple and access that to get a complexity of O(n)
Check code to see what I mean.

## Why It's Good For The Game

![image](https://github.com/tgstation/tgstation/assets/37270891/1e5d68fa-2e19-473c-a870-e1e0277cbacc)
This is a very hot proc and it's worth micro-optimizing where we can.

## Changelog

2024-05-15 22:13 UTC, Mothblocks commented on code/datums/signals.dm
> +	// This should be faster than the other method of iterating over a list
Nit: There's like 5 ways to iterate lists in BYOND, be specific

2024-05-15 22:14 UTC, Mothblocks requested changes
Can you split this into a 50/50 A/B test so we can check on an actual round if its faster/slower? I'm a bit skeptical and want more than just a basic BYOND bench

2024-05-15 22:20 UTC, Mothblocks commented
As in:
```dm
/datum/proc/RegisterSignal(etc)
  var/static/x = 0
  if (++x % 2 == 0)
    RegisterSignal_ORIGINAL(etc)
  else
    RegisterSignal_NEW(etc)

/datum/proc/RegisterSignal_ORIGINAL(etc)
  // original

/datum/proc/RegisterSignal_NEW(etc)
  // new
```

2024-05-16 11:52 UTC, Watermelon914 commented
ok

2024-05-17 01:54 UTC, Watermelon914 commented
Results over around 14 rounds of testmerge:
![image](https://github.com/tgstation/tgstation/assets/37270891/afd5085c-bce7-4e67-9e09-bdf5e8e68d7d)

The speed increase isn't super significant, it's marginally faster but the new algorithm has a better time complexity so it'll fare better as we register more signals of the same type onto the same object.

2024-05-17 05:22 UTC, LemonInTheDark requested changes

2024-05-17 05:22 UTC, LemonInTheDark commented on code/datums/signals.dm
> +		. |= call(queued_calls[i*2-1], queued_calls[i*2])(arglist(arguments))
```suggestion
	for(var/i in 1 to length(queued_calls) step 2))
		. |= call(queued_calls[i], queued_calls[i + 1])(arglist(arguments))
```

2024-05-17 05:22 UTC, LemonInTheDark commented on code/datums/signals.dm
> +		. |= call(queued_calls[i*2-1], queued_calls[i*2])(arglist(arguments))
should be about as or faster, and s cleaner

2024-05-17 05:22 UTC, LemonInTheDark commented on code/datums/signals.dm
> +		queued_calls.Add(listening_datum, listening_datum._signal_procs[src][sigtype])
you... might? get something by preallocating queued_calls's length, but that'd likely only really matter for large lists which are not a common case, would prob slow us down normally

2024-05-17 15:35 UTC, Watermelon914 commented on code/datums/signals.dm
> +	for(var/i in 1 to length(queued_calls) step 2))
```suggestion
	for(var/i in 1 to length(queued_calls) step 2)
```

2024-05-17 22:23 UTC, merged

2024-05-18 00:06 UTC, LemonInTheDark commented on code/datums/signals.dm
> +		queued_calls.Add(listening_datum, listening_datum._signal_procs[src][sigtype])
to clarify I mean in context of list expansion, but these lists are small so it doesn't matter/would maybe hurt