Gondolas are now basic mobs
tgstation/tgstation pull request #83451
Opened 2024-05-25 06:18 UTC by JohnFulpWillard

## About The Pull Request

This PR turns gondolas into basic mobs and does some fiddling with gondola pods
Their verbs are now action buttons which they lose upon delivering. If set to stay, they won't have their abilities afterwards (or wont get them in the first place if the delivery is already done).
Lets them survive without a pod requirement in case admins want to spawn one for their own stuff, so I also removed it from the snowflake checks to exclude them from stuff.

Also replaced the hardcoded "cant speak" with simply giving the mute trait, so admins can make gondolas speak if they want to for any reason.

## Why It's Good For The Game

The pet level of simple animals can finally be killed off, also gives admins more control over gondola-related stuff if they so wish.

## Changelog

:cl:
refactor: Gondolas (including gondola pods) are now basic mobs.
/:cl:

2024-05-25 12:39 UTC, Jacquerel requested changes

2024-05-25 12:39 UTC, Jacquerel commented on code/modules/mob/living/basic/pets/gondolas/gondolapod.dm
> +	desc = "Open your pod and release any contents stored within."
You forgot to update these vars

2024-05-28 19:56 UTC, Higgin commented
:DDD

2024-05-28 20:00 UTC, san7890 requested changes
very cool, thank you, just need to remove an HTML tag that doesn't work anymore

2024-05-31 21:58 UTC, Maurukas approved these changes
Mapdiff bot has been fixed so if you push a new commit of any type it will rerun.

This is just a replace paths though, so you don't really need to.

2024-05-31 22:48 UTC, merged