Cuffed people can sign (to a limited degree), signing tone emotes improvemed
tgstation/tgstation pull request #83501
Opened 2024-05-26 23:09 UTC by Metekillot

## About The Pull Request

Currently, if you handcuff someone and they only have sign language available to speak in (mute, no tongue, nearby people are deaf, you have bronchitis(?)), they are rendered totally unable to communicate with anything but emotes. This is stifling to trying to roleplay with nearby people who want to keep you cuffed for whatever reason (security, antagonists, weirdos who keep hugging you, etc).

So instead, I've made it so that if you use sign language while handcuffed, you are still able to sign, but to a much more limited degree (3 - 5 words per message).

If you're put in a straightjacket, you're still totally unable to use sign language.

Additionally, I spruced up the messages that sign language uses to signify tone (?, !) and added one for EXCLAIMED QUESTIONS?! I also made the emotes work as emotes, rather than the small (easily missable) messages in the chat box. These emotes will not fire if you sign with tone while cuffed, to avoid you becoming a spam machine.

## Why It's Good For The Game

It lets cuffed sign language users communicate, which is usually a pretty good thing when it comes to improving a scene for both them and the people they're playing with.

It improves the descriptiveness of the inquisitive and exclamatory tone messaging for sign language users, and also adds one for a combination of the two tones.

## Changelog

:cl:
qol: Sign language users can now sign in cuffs, but to a very limited degree. They also have more descriptive emotes for questions, exclamations, and a combination of the two.
/:cl:

2024-05-27 14:53 UTC, 00-Steven commented on code/datums/components/sign_language.dm
> +/// Changes our message based on criteria.
A bit nondescriptive of a comment, I think it'd be better if we'd keep it as at least saying when it changes our message- _What_ criteria?

2024-05-28 20:16 UTC, san7890 requested changes
mostly documentation nits and some code nicety we can do

2024-05-28 20:16 UTC, san7890 commented on code/datums/components/sign_language.dm
> +/// Defines to determine the tone of the signer's message.
```suggestion

// Defines to determine the tone of the signer's message.
```

dmdoc for section dividers makes the next line more confusing

2024-05-28 20:16 UTC, san7890 commented on code/datums/components/sign_language.dm
> +#define TONE_INQUISITIVE_EMPHATIC 3 // a bit of both
```suggestion
#define TONE_NEUTRAL 0 //! a statement
#define TONE_INQUISITIVE 1 //! a question
#define TONE_EMPHATIC 2 //! an exclamation
#define TONE_INQUISITIVE_EMPHATIC 3 //! both a question and an exclamation (interrobang)
```

A) doing `//!` in documentation on that line is the same as doing `///` on the preceding line. so let's do that here.
B) "a bit of both" on it's own is rather confusing so let's be a bit more wordy so it stands on its own.

2024-05-28 20:16 UTC, san7890 commented on code/datums/components/sign_language.dm
> +/// that limit or alter our ability to communicate
```suggestion
/// Changes our message based on conditions that limit or alter our ability to communicate 
```

formatting a bit bad otherwise

2024-05-28 20:16 UTC, san7890 commented on code/datums/components/sign_language.dm
> +	// Determine tone based on punctuation
```suggestion
```

this isn't the part where we determine tone, we already did that six lines up. this can live without a comment

2024-05-28 20:16 UTC, san7890 commented on code/datums/components/sign_language.dm
> +/datum/component/sign_language/proc/emote_tone(mob/living/carbon/carbon_parent, emote_tone)
```suggestion

/// Send a visible message depending on the tone of the message that the sender is trying to convey to the world.
/datum/component/sign_language/proc/emote_tone(mob/living/carbon/carbon_parent, emote_tone)
```

2024-05-28 20:16 UTC, san7890 commented on code/modules/mob/mob_helpers.dm
> +	var/num_words
```suggestion
	var/num_words = 0
```

so we can "type" it as a integer value

2024-06-01 22:01 UTC, merged