Replaces `move_on_shuttle` with a trait
tgstation/tgstation pull request #83550
Opened 2024-05-28 21:07 UTC by san7890

## About The Pull Request

`move_on_shuttle` was a variable that existed on `/mob` despite only ever being used by cameras. This PR downgrades the variable to only exist on `/mob/camera` types, but have the only thing that variable do is add a trait that blocks movement on shuttles if not allowed. This allows us to check the variable without casting to camera, which is what some code was un-necessarily doing. This also retainst the ability to add the trait later on to different mobs who we may not want to be on shuttles that aren't `/mob/camera`.

## Why It's Good For The Game

There's no point for this variable to live on `/mob` if all it can do is clog up the VV screen, especially if the current utilization for it is only cameras. Let's move it off `/mob` and turn it into a trait so it still has the similar utilization on a global level without typecasting.

## Changelog

Irrelevant.

2024-05-29 19:36 UTC, Time-Green requested changes

2024-05-29 19:37 UTC, Time-Green commented on code/modules/shuttle/on_move.dm
> +	if(!HAS_TRAIT(src, TRAIT_BLOCK_SHUTTLE_MOVEMENT))
Im tired but these look inverted

2024-05-29 22:25 UTC, san7890 commented on code/modules/shuttle/on_move.dm
> +	if(!HAS_TRAIT(src, TRAIT_BLOCK_SHUTTLE_MOVEMENT))
you're right whoops

2024-05-29 22:26 UTC, san7890 commented on code/modules/shuttle/arrivals.dm
> +	for(var/mob/player in GLOB.player_list)
i was scared of potentially qdeleted mobs but i think destroy handles this list well enough so sure

2024-05-30 06:54 UTC, Time-Green commented on code/modules/shuttle/arrivals.dm
> +	for(var/mob/player in GLOB.player_list)
It didn’t check before so it’s probably fine?

2024-05-30 06:54 UTC, merged