Fix access in the wawa station bridge and replace the empty medkit
tgstation/tgstation pull request #83778
Opened 2024-06-07 01:30 UTC by projectkepler-ru

## About The Pull Request
closes #83772

we really should add a unit test to make sure the access on door or whatever actually exist

## Why It's Good For The Game
closes #83772 

## Changelog

:cl:
fix: Wawastation bridge now has the correct access on their suit storage and medkit now actually starts filled
/:cl:

2024-06-10 23:37 UTC, Maurukas requested changes

2024-06-10 23:37 UTC, Maurukas commented on _maps/map_files/wawastation/wawastation.dmm
> +	name = "suit storage"
This name varedit is causing the linters to fail

2024-06-19 05:27 UTC, projectkepler-ru commented
sitll waiting on revieww

2024-06-20 02:33 UTC, Maurukas approved these changes

2024-06-20 02:33 UTC, merged