Flatpacker
tgstation/tgstation pull request #83836
Opened 2024-06-09 09:38 UTC by mc-oofert

## About The Pull Request

adds the flatpacker, it flatpacks machines
![2024-02-08 19_47_34-Window](https://github.com/tgstation/tgstation/assets/70376633/331c85e2-cdac-4ebe-9aac-d83c514bcd23)
it is unlocked at industrial engineering
the default print time is 4.5 seconds, reduced by the servo tier divided by 2
matter bins increase material capacity
better servos decrease material cost, and the flatpacker cannot print a machine if it contains parts that are of a tier larger than the servos tier

explained in this vid

https://github.com/tgstation/tgstation/assets/70376633/c26e4379-f49b-4b1d-a70c-61f1ba96a9e0

## Why It's Good For The Game

machine construction sucks, this should be more convenient, this does not replace machine construction at all
compared to machine frames while this is faster and more convenient, it is significantly more costly in materials, and a better servo is needed to use higher tier parts, and the printed machines are always the lowest required tier

## Changelog
:cl:
add: the flatpacker, a machine unlocked at industrial engineering
/:cl:

2024-06-09 11:52 UTC, SyncIt21 requested changes

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	)
```suggestion
	materials = AddComponent( \
		/datum/component/material_container, \
		SSmaterials.materials_by_category[MAT_CATEGORY_SILO], \
		0, \
		MATCONTAINER_EXAMINE, \
		container_signals = list(COMSIG_MATCONTAINER_ITEM_CONSUMED = TYPE_PROC_REF(/obj/machinery/flatpacker, AfterMaterialInsert)) \
	)
```

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +/obj/machinery/flatpacker/proc/analyze_cost(type, costs)
Autodoc with arguments

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +/obj/machinery/flatpacker/proc/start_build()
Autodoc

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +/obj/machinery/flatpacker/proc/finish_build(board)
Autodoc

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +		return FALSE
```suggestion
		return ITEM_INTERACT_BLOCKING
```

Here & everywhere else where there is `return FALSE`

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	return TRUE
```suggestion
	return ITEM_INTERACT_SUCCESS
```

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +/obj/machinery/flatpacker/attackby(obj/item/attacking_item, mob/living/user, params)
replace `attackby()` with `item_interaction_with()`, along with the new return values `ITEM_INTERACT_SUCCESS` or `ITEM_INTERACT_BLOCKING`. you can also return `NONE` if you don't want to handle that item interaction, see the docs

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	creation_efficiency = max(1.2,efficiency)
```suggestion
	creation_efficiency = max(1.2, efficiency)
```

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	flatpack_time = initial(flatpack_time) - servo.tier/2 // T4 = 2 seconds off
```suggestion
	flatpack_time = initial(flatpack_time) - servo.tier / 2 // T4 = 2 seconds off
```

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +		mat_capacity += new_matter_bin.tier * (25*SHEET_MATERIAL_AMOUNT)
```suggestion
		mat_capacity += new_matter_bin.tier * 25 * SHEET_MATERIAL_AMOUNT
```

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +
```suggestion
```

Remove the excess space between these vars

2024-06-09 11:52 UTC, SyncIt21 commented on code/controllers/subsystem/research.dm
> +			item_to_design[initial(DN.build_path)] += DN
```suggestion
		var/build_path = initial(DN.build_path)
		if(!isnull(build_path))
			if(!(build_path in item_to_design))
				item_to_design[build_path] = list()
			item_to_design[build_path] += DN
```

Don't use `initial()` too many times

2024-06-09 11:52 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	return data
```suggestion
	return materials.ui_static_data()
```

2024-06-09 11:57 UTC, GuillaumePrata commented
This should be prebuild on the engineering foyer.

Industrial engineering is nothing research wise, it's done at the start of every single shift.

Having to build it is repetitive, it is a knowledge check for new players and having the material cost fluctuate is another annoying thing as a machine costs X in a shift and Y in another.

The goal is good, but this should be simplified a lot, there is no reason to complicate the machine made to simplify construction.

2024-06-09 12:54 UTC, Dawnseer commented
Where can this board be printed? Just engineering? Science and cargo too?

2024-06-09 13:39 UTC, mc-oofert commented
drafting for fortnut reasons

2024-06-09 15:07 UTC, MTandi commented
We already have RCDs deploying a machine frame with wires and RPEDs that can be loaded with circuits and required parts to make machine building effortless. So this doesn't really change much in that regard.

On the other hand, this is a balance change. You can pack a bunch of emitters into these boxes of WEIGHT_CLASS_NORMAL and spam build emitters next to the blob.

Machine building shouldn't be trivialized so much. Construction should require time, engineering tools and brainpower to shuffle between rcd, rped, screwdriver.

2024-06-09 15:08 UTC, mc-oofert commented
> We already have RCDs deploying a machine frame with wires and RPEDs that can be loaded with circuits and required parts to make machine building effortless. So this doesn't really change much in that regard.
> 
> On the other hand, this is a balance change. You can pack a bunch of emitters into these boxes of WEIGHT_CLASS_NORMAL and spam build emitters next to the blob.
> 
> Machine building shouldn't be trivialized so much. Construction should require time, engineering tools and brainpower to shuffle between rcd, rped, screwdriver.

didnt ask sorry

2024-06-09 20:10 UTC, munchyi commented
very nice idea hope it becomes real oen day

2024-06-09 22:37 UTC, Ilgradhr commented
I have contradictory feelings about this one. From one side as a person who does construct a lot of things I feel happy from this PR and on other side this PR could lead to a lot of griefing as was with the carts/cars that could do holoprojections of machines. 
On the side of positive input in this PR you should have the ability to select the level of the parts. What if the Flatpacker is upgraded and then you use up all the mats and there is no more diamonds or uranium for the high tier parts and like with BS artilery it should be locked on the t4 parts. Idk about the tier of the parts being linked to the parts of the flatpacker maybe a link to r&d servers?

2024-06-10 00:38 UTC, Sakamoto4ka commented
Rped📉
Headache📉
Autolathe hopline📈

2024-06-10 13:43 UTC, Dorsisdwarf commented
It's called the flatpacker, but the packs are cubes. Immersion ruined, gamebreaking PR.

2024-06-10 16:38 UTC, SyncIt21 requested changes
`has_materials()` & `use_materials()` alows you to pass `creation_efficiency` into them so you don't need to scale your needed mats manually

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +		if(!materials.has_materials(needed_mats))
```suggestion
		var/disableReason = ""
		var/has_materials = materials.has_materials(needed_mats, creation_efficiency)
		if(!has_materials)
```

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +			"canPrint" = materials.has_materials(needed_mats) && print_tier <= max_part_tier,
```suggestion
			"canPrint" = has_materials && print_tier <= max_part_tier,
```

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +		CREATE_AND_INCREMENT(needed_mats, /datum/material/glass, (SHEET_MATERIAL_AMOUNT / 20) * creation_efficiency)
```suggestion
		CREATE_AND_INCREMENT(needed_mats, /datum/material/iron, (SHEET_MATERIAL_AMOUNT * 5 + (SHEET_MATERIAL_AMOUNT / 20)))
		CREATE_AND_INCREMENT(needed_mats, /datum/material/glass, (SHEET_MATERIAL_AMOUNT / 20))
```

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +		CREATE_AND_INCREMENT(costs, mat_type, (mat_list[mat] * creation_efficiency) * inserted_board.req_components[type])
```suggestion
		CREATE_AND_INCREMENT(costs, mat_type, mat_list[mat] * inserted_board.req_components[type])
```

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	if(!materials.has_materials(needed_mats))
```suggestion
	if(!materials.has_materials(needed_mats, creation_efficiency))
```

2024-06-10 16:38 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	materials.use_materials(needed_mats)
```suggestion
	materials.use_materials(needed_mats, creation_efficiency)
```

2024-06-10 17:30 UTC, mc-oofert commented
> If you are facing linter issues with typescript follow the instructions in [#76296 (comment)](https://github.com/tgstation/tgstation/pull/76296#issuecomment-1605957155)

thats like great and all but if it worked i wouldve done it

2024-06-10 17:59 UTC, Deadgebert commented
i love this. The deploy time might be a bit too fast though, I could see people using flatpacked machines to set up quick barricades at this speed.
Good work

2024-06-10 21:30 UTC, optimumtact commented
This doesn't even match our rapid construction design document https://hackmd.io/@tgstation/rJjgKJEYc

2024-06-11 00:41 UTC, GuillaumePrata commented
Our Rapid construction document has been stuck in limbo for 2 years with no one making progress.

At some point we should just push it aside and prioritize the things people actually want to work on right now to improve the game today.

2024-06-11 03:22 UTC, SyncIt21 commented
> At some point we should just push it aside and prioritize the things people actually want to work on right now to improve the game today.

Or just scrap the design doc entirely. Docs should be revised yearly to keep up with player demands so it requires a rework at this point

2024-06-11 03:29 UTC, optimumtact commented
If we just give up on design documents then there's no point even having them in the first place.

2024-06-11 04:59 UTC, SyncIt21 commented
> If we just give up on design documents then there's no point even having them in the first place.

Not give up, as in revise them. The requirements they listed back then may not be valid today with all the new features added.

Of course if the changes to be made are too many then just scrap it and create a new design doc from scratch.

2024-06-11 12:30 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	update_static_data_for_all_viewers()
```suggestion
```
Nothing to update inside `ui_static_data()`

2024-06-12 15:35 UTC, SyncIt21 requested changes

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	. = TRUE
```suggestion
```

Don't force the return value if we haven't handled it yet. returning true always will update the UI needlessly

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	return FALSE
```suggestion
```

Not required because the return value has already been set by `..()`

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	inserted_board = null // this could be destroyed but the relevant refactor isnt in yet
```suggestion

/obj/machinery/flatpacker/Destroy()
	QDEL_NULL(inserted_board)
	. = ..()
```

You should delete it. The board gets ejected out when you deconstruct the machine anyway but if an admin deletes it then no side effects should be present

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +				return TRUE
```suggestion
				return FALSE
```

If we have invalid arguments then returning FALSE will not update the UI, which is what we want

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	qdel(board)
```suggestion
	QDEL_NULL(board)
	. = ..()
```

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	. = ..()
```suggestion
	. = NONE
```
the parent proc does nothing

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	qdel(board)
```suggestion
```

the board gets deleted inside `Destroy()` when you do `qdel(src)` towards the end anyway

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +
```suggestion
```

2024-06-12 15:35 UTC, SyncIt21 commented on code/game/machinery/flatpacker.dm
> +	if(istype(attacking_item, /obj/item/flatpack))
```suggestion
	if(istype(attacking_item, /obj/item/flatpack))
```
early return this

2024-06-14 20:33 UTC, jlsnow301 commented
No negative feedback however

![image](https://github.com/tgstation/tgstation/assets/42397676/b97da4bd-f732-4192-b859-e65bfa58f95c)

2024-06-14 20:39 UTC, merged