Makes Portable scrubbers repairable.
tgstation/tgstation pull request #83869
Opened 2024-06-11 00:15 UTC by EnterTheJake

## About The Pull Request

Atmos scrubbers are now repairable.

## Why It's Good For The Game

Quality of life for atmos tech, you can repair your scrubbers if they get damage while sipping spicy gas.

Also because it doesn't really make sense why you shouldn't.

## Changelog

:cl:

qol: You can now repair portable scrubbers.
/:cl:

2024-06-11 03:09 UTC, SyncIt21 requested changes
Add an examine and screentip and you should be good

2024-06-11 03:19 UTC, MrMelbert commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +		return ITEM_INTERACT_SUCCESS
```suggestion
		return ITEM_INTERACT_BLOCKING
```

2024-06-11 03:20 UTC, MrMelbert commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +	return ITEM_INTERACT_BLOCKING
```suggestion
	return ITEM_INTERACT_SUCCESS
```

2024-06-11 03:20 UTC, MrMelbert commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +		to_chat(user, span_notice("You repair some of the damage in [src]..."))
Should use balloon alerts

2024-06-11 03:20 UTC, MrMelbert commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +		return
```suggestion
		return NONE 
```
or
```suggestion
		return ITEM_INTERACT_SKIP_TO_ATTACK
```

2024-06-13 18:03 UTC, MrMelbert reviewed
It should have screentips and/or examine text yes

2024-06-13 18:03 UTC, MrMelbert commented on code/modules/atmospherics/machinery/portable/scrubber.dm
> +			balloon_alert(user, "repaired!")
```suggestion
			balloon_alert(user, "repaired")
```

2024-06-13 22:16 UTC, EnterTheJake commented
Having quite a few integration issues, can't seem to know why.

2024-06-15 05:48 UTC, merged