Event Horizon Anti-Existential Beam Rifle. The ultimate conclusion to the arms race and the sniper's art.
tgstation/tgstation pull request #83934
Opened 2024-06-13 03:56 UTC by necromanceranne

## About The Pull Request

Replaces the Particle Acceleration Rifle, or the Beam Marksman Rifle, with the Event Horizon Anti-Existential Beam Rifle.

In short, it shoots black holes.

It takes five cores to make.

It pretty much kills everything you point it at and their immediate bystanders as well.

You can do this from the relative safety of a whole four screens away thanks to it having a scope.

## Why It's Good For The Game

Firstly; the beam rifle? Awful. Jank code. Bad performance. Ancient balancing considerations. Just too strong to bring out regularly against specifically blobs.

So I'm hitting all these problems at once. I reduced a 600 line file to less than 60. I've removed all that bad code. I've also made it specifically unable to combat blobs at all because singularities send blobs off to safety.

Secondly; this is maybe the first example of 'more cores = bigger power'. The rifle was already utterly trash to have around, and I just didn't think the way it worked currently could really excite anyone enough to go on a big ol' quest to get it. Solution?

You will cause a shuttle call if you get this weapon.

## Changelog

:cl:
add: Replaces the Particle Acceleration Rifle with the Event Horizon anti-existential beam rifle. It shoots black holes. You can make this in-game. That's right, YOU!
/:cl:

2024-06-13 03:57 UTC, necromanceranne commented
Don't merge this before https://github.com/tgstation/tgstation/pull/83892

2024-06-13 04:04 UTC, carlarctg commented
> Only one vortex anomaly can be made in a round.

kinda dislike how this cucks the use of vortex anomalies for other things

what if it just turned the core into a random different core instead of refusing to make it

2024-06-13 04:05 UTC, necromanceranne commented
Sounds like a good feature to me. You're welcome to make it, but this is actually the way the anomaly restrictions are meant to work.

2024-06-13 04:07 UTC, Astrogem2 commented
could we get a video to showcase this?

2024-06-13 04:08 UTC, Vect0r2 commented
This is actually so fucking cool I am quite honestly in shock
https://cdn.discordapp.com/attachments/705679956021215264/1250662515357253662/close_range.mp4?ex=666bc1bb&is=666a703b&hm=d9114e8560d160d2cbb70d949b8508faedd4f47894381b1bab5d756d4ce13ca0&

2024-06-13 04:11 UTC, CCC23 commented
Time to detonate NERDS with the FUNNY WEAPON

2024-06-13 04:18 UTC, Vect0r2 commented
> Time to detonate NERDS with the FUNNY WEAPON

if you are making this YOU are the nerd

2024-06-13 04:43 UTC, ATH1909 commented on code/modules/research/designs/weapon_designs.dm
> +	desc = "The kit that produces a weapon made to end your foes on an existsential level. Why the fuck can you make this?"
minor spelling mistake

i win

2024-06-13 04:44 UTC, ATH1909 commented on code/modules/projectiles/guns/energy/beam_rifle.dm
> +		To look upon this existential maleficence is to know that the pursuit of profit has consigned all life to this pathetic conclusion. The destruction of reality itself."
```suggestion
		To look upon this existential maleficence is to know that the pursuit of profit has consigned all life to this pathetic conclusion: the destruction of reality itself."
```

2024-06-13 04:51 UTC, DaydreamIQ commented
Would this replace any that happen to already be spawned in? I ask cause there's at least one bitrunner sim that has a particle rifle

2024-06-13 05:27 UTC, Vect0r2 commented
> 

it does

2024-06-13 05:30 UTC, necromanceranne commented
> video?

vectOr posted one in the comments

2024-06-13 07:23 UTC, TagGamerGang22 commented
Something important to note is that cores can be ordered for free roundstart by scientists via their departmental order. If they're the RD then they get a ~6k departmental budget to spend roundstart which I believe will usually always be enough (or near enough) to order all 5 vortex cores.

2024-06-13 07:28 UTC, necromanceranne commented
That's fine.

2024-06-13 07:46 UTC, necromanceranne commented
Okay, more seriously; the design mandate for anomalies cores is currently 'if the amount of a given core is more limited, and an item needs more cores to work, then the item itself can become disproportionately stronger than normal gear as a result'.

It doesn't matter how easy it is, right now, to make five different cores and put it together to make the AEBR. That's a dial that can be adjusted as needed. But the end result can always be as overpowered as necessary, based on the amount of cores used, to justify the effort put in making all those cores and the potential for it to get swept out from under you by random chance or in-round circumstance.

The hurdles include;
1) Making the cores.
2) Getting the tech.
3) Getting the kit out of security's protolathe
4) Having enough minerals to print the kit.

If you don't want to encounter something that, potentially, you simply do not have an answer too while on the other side...well, in the spirit of absurdity, that's tough luck.

2024-06-13 09:39 UTC, Exester509 commented
This is absurd, stupidly powerful, a drain on station resources and extremely unwieldy to use without causing massive collateral damage.

Instant merge

2024-06-13 10:15 UTC, moocowswag commented
Vortex armor is the best one so looks like this is never getting made.

2024-06-13 10:34 UTC, Sadboysuss commented
> Vortex armor is the best one so looks like this is never getting made.

Pyro core does the same thing for reactive armor, L

2024-06-13 12:28 UTC, GPeckman commented
> Would this replace any that happen to already be spawned in? I ask cause there's at least one bitrunner sim that has a particle rifle

Feature TBH

2024-06-13 12:29 UTC, necromanceranne commented
No, all the ones mapped in have been replaced.

2024-06-13 13:03 UTC, CRITAWAKETS commented
there is the issue that if you can refine one core usually you can refine 'em all, but whatever this thing looks really fun

2024-06-13 13:30 UTC, Singul0 commented
balancing this thing by limiting one of the core types to just one seems.... unwise for future PR's that will inevitably comes (core item PR's are really picking up steam after that omnibelt addition). barring an entire core type to just one functionality means the core gotta be super busted

2024-06-13 13:34 UTC, DATA-xPUNGED commented
Soulful as fuck PR speedmerge, can't wait to never actually see this in practice

2024-06-13 14:11 UTC, moocowswag commented
> Pyro core does the same thing for reactive armor, L

Thats placeholder

2024-06-13 14:43 UTC, Sadboysuss commented
> > Pyro core does the same thing for reactive armor, L
> 
> Thats placeholder

vortex core making stealth armor is also a placeholder and doesn't make sense

2024-06-13 15:48 UTC, moocowswag commented
> > > Pyro core does the same thing for reactive armor, L
> > 
> > 
> > Thats placeholder
> 
> vortex core making stealth armor is also a placeholder and doesn't make sense

Vortex always made stealth , pyro armor was op so core was made to make stealth

This pr will incentivize someone making yet another attempt at pyro armor being balanced since it hinges on void being valuable

2024-06-13 17:45 UTC, MrMelbert commented
> Don't merge this before #83892

2024-06-13 21:17 UTC, ZephyrTFA approved these changes
pr of the year

2024-06-13 22:02 UTC, necromanceranne commented
> balancing this thing by limiting one of the core types to just one seems.... unwise for future PR's that will inevitably comes (core item PR's are really picking up steam after that omnibelt addition).

Actually, I do have a solution for that. I could change the number of required vortexes to make a AEBR always equivalent to the maximum number of vortex cores.

2024-06-14 03:00 UTC, necromanceranne commented
I did that

2024-06-14 03:09 UTC, necromanceranne commented
> Vortex always made stealth , pyro armor was “op” so core was made to make stealth aswell
> 
> This pr will incentivize someone making yet another attempt at pyro armor being balanced since it hinges on void being valuable

Not for nothing, but maybe this should incentivize making stealth armor to compensate for the greater scarcity of the core.

2024-06-14 03:21 UTC, Loafin34 commented
This is the Event Horizon Anti-Existential Beam Rifle. It is a 150 pound, 5 foot long "rifle" that shoots an unfocused, undefinable mass of dark matter. It is a non-briggable item only because sec gave it a sporting exemption as a joke as if anybody is going to hunt with this. This thing would be overkill for hunting Nar'Sie.

I would like to paint a picture for you. It's 2AM and you hear a window break in your armory. This is the worst day this could happen, as every single one of your guns was lost in a tragic skateboarding accident this morning. All were lost except for one. You look across your room in dread at your anti-admin rifle. You know what you have to do, but you don't know if you have the strength to do it, both literally and figuratively.

Heaving the rifle into your arms, you charge the vortex core and begin to waddle towards the door. Your feet make a loud “thud” as you take each 6″ step. You know the spessmen hear you. You hope they do, for perhaps they will run and spare the world the suffering that is about to befall it.

You try to set the abomination down, but end up clipping your bedroom door and it is immediately knocked off its hinges by this battering ram in your hands. You attempt to round the corner, bonking the charging array against the airlock and adjacent wall across the hall at least 4 times. To your horror, a changeling and a traitor stand there at the end of the hall.

With a heavy heart, you raise the rifle to your shoulder while making inhuman grunting noises from the strain of attempting some semblance of a shooting position. The spessmen simply stare in disbelief, unable to process the situation they are witnessing, as if in a dream. You cannot physically aim it down sights, as the last time you fired it, it sucked your $3000 SecHUD GAR glasses in. You simply hold it at an angle that appears correct and fire.

You are immediately knocked to the floor as if hit by a chemist going 20 MPH. The shot connected with the ling and it erased him from existence. Even the memories of him have been destroyed and you're wondering why you just shot into an empty hallway. The shot continues to travel through space, taking at least half of perma, a solar array, and the cargo shuttle before being flung far away by a panicked admin, never to be seen again.

It is at this point, you realize you cannot hear. The surviving traitor can't hear either but he's also missing an arm from the blast and is currently vacating your brig. You don't care. Your shoulder is dislocated and there is a hole in your brand new secway You're crying now. The engiborgs arrive and, upon seeing the scene, start laughing. You start crying harder.

2024-06-14 10:48 UTC, necromanceranne commented
>This thing would be overkill for hunting Nar'Sie.

Actually, you just reminded me that this gun can, in fact, kill Nar'sie.

Nice.

2024-06-14 18:02 UTC, Astrogem2 commented
The last thing a tider breaking into science after I spend an hour making this rifle:

![Rifle-ezgif com-optimize](https://github.com/tgstation/tgstation/assets/101240878/f7c41189-a718-4f86-9dd6-d18d650c87ab)

2024-06-14 19:50 UTC, Jacquerel commented
Double check this to make sure it still does what you want it to do

2024-06-15 06:33 UTC, necromanceranne commented
I'll have to make a new version of the black hole, so it might be best to put this on draft for now, I've got an important thing I have to prepare for this weekend.

2024-06-15 06:56 UTC, Admiral-Gigaton commented
Balancing idea: take a page from paradise and make it take energy and ammo, said ammo being some bullshit like bluespace crystals or whatever, just so blac jhole can't rapid fire a fucking infinite mass object at Chang ling without running TGMC martini levels of skill

2024-06-15 07:45 UTC, DrAmazing343 commented
> Balancing idea: take a page from paradise and make it take energy and ammo, said ammo being some bullshit like bluespace crystals or whatever, just so blac jhole can't rapid fire a fucking infinite mass object at Chang ling without running TGMC martini levels of skill

I think it's perfect as it is. It's not meant to be balanced, it's meant to be a fucking world-ender predicated upon the fact that you spent like an hour tracking down the goddamn Dragon Balls to put together fucking Exodia

2024-06-15 14:25 UTC, Jacquerel commented
Not sure what if anything you would want to do about this but it might be worth remembering that it is completely possible for 3/5 of the desired cores to have spawned at roundstart in science, you can (I think?) order the fourth basically immediately from the supply console, and so only need to buy one core. This still leaves you making 5 bombs but seems a lot less of a hurdle than you might expect from a 5 core requirement.

2024-06-15 14:45 UTC, necromanceranne commented
The tech is fairly deep into the tree, and locked behind a few toxins experiments. To get there quickly and not get beaten to a pulp by the other scientists, you would have to actually engage in the toxins content itself as well.

This is also on top of mineral limits, and the major component needed, the kit, has to be printed out of security.

Not quite as simple as just the base five cores, otherwise, the rounds natural passive time gates will hopefully keep it in check.

2024-06-18 13:39 UTC, Jacquerel requested changes

2024-06-18 13:39 UTC, Jacquerel commented on code/datums/components/crafting/guncrafting.dm
> +	name = "\improper Event Horizon anti-existnetial beam rifle part kit (DOOMSDAY DEVICE, DO NOT CONSTRUCT)"
```suggestion
	name = "\improper Event Horizon anti-existential beam rifle part kit (DOOMSDAY DEVICE, DO NOT CONSTRUCT)"
```

2024-06-18 13:39 UTC, Jacquerel commented on code/datums/components/crafting/guncrafting.dm
> +	desc = "What fevered minds wrought this terrible construction kit? To create a frame to harness the strange enemies that flow through the Spinward Sector towards such horrible acts of violence? \
```suggestion
	desc = "What fevered minds wrought this terrible construction kit? To create a frame to harness the strange energies that flow through the Spinward Sector towards such horrible acts of violence? \
```

2024-06-18 13:39 UTC, Jacquerel commented on code/datums/components/crafting/guncrafting.dm
> +		If you are unsound of mind, heed this. One vortex anomaly. One bluespace anomaly. Two flux anomalies. One gravity anomaly. And, maybe, if you believe in it, your soul itself. That is the price paid
May never come up but if we're making the potential cost in vortex cores variable, do we want to reference a specific number in the description?

2024-06-18 13:58 UTC, necromanceranne commented on code/datums/components/crafting/guncrafting.dm
> +	name = "\improper Event Horizon anti-existnetial beam rifle part kit (DOOMSDAY DEVICE, DO NOT CONSTRUCT)"
Didn't I already fix this?

2024-06-20 12:58 UTC, merged

2024-06-20 14:56 UTC, adamkad1 commented
Cool, we got a new blob instakilling weapon

2024-06-21 04:07 UTC, optimumtact commented
There will be no changes to anomaly cores/refined cores design so stop asking.

They are designed for a very specific purpose and all powerful weapons like this will be locked behind them.

it's not something that is up for debate unless headcoders (and them alone) want to do something with it.

2024-06-21 21:32 UTC, CCC23 commented
The throngler shall destroy all the healthes (security officers) in my holy domain (anywhere within a five mile radius)