Deleting characters
tgstation/tgstation pull request #83989
Opened 2024-06-14 15:41 UTC by AnywayFarus

## About The Pull Request

Adds a button to delete characters, and when deleted it flips to the nearest character, wow(the last character can't be deleted(I guess)).

## Why It's Good For The Game

Not really too sure how useful this could be within a TG build, but on downstream builds I think it's a very cool feature.

## Changelog

:cl: Vishenka0704
qol: Ability to delete characters(yourself)
/:cl:

2024-06-14 18:21 UTC, san7890 requested changes

2024-06-14 18:21 UTC, san7890 commented on code/modules/client/preferences.dm
> +			if(confidence_check == params["name"])
turn this into an early return so we don't have to worrk about indentation here

```dm
if(confidence_check != params["name"])
 return FALSE
```

2024-06-14 18:21 UTC, san7890 commented on code/modules/client/preferences.dm
> +				if(remove_character(pickedSlot))
this can also be an early `return FALSE`.

2024-06-14 18:21 UTC, san7890 commented on code/modules/client/preferences.dm
> +			var/pickedSlot = params["slot"]
```suggestion
			var/picked_slot = params["slot"]
```

prefer `snake_case`

2024-06-14 21:51 UTC, MrMelbert requested changes
It's kind of a weird place to put a delete character button, leaves a bunch of empty space

The desert
![image](https://github.com/tgstation/tgstation/assets/51863163/036b60e4-d818-47b4-bdaf-88daf1224948)

At the very least I would keep the button always-shown and just disable it when it's unusable.

2024-06-14 21:52 UTC, MrMelbert commented
@Mothblocks Got an opinion on where it should go?

2024-06-15 00:03 UTC, optimumtact commented
Does this button have a safety feature?

it should make you type the character name.

2024-06-15 00:34 UTC, ZephyrTFA approved these changes

2024-06-15 05:42 UTC, AnywayFarus commented
> It's kind of a weird place to put a delete character button, leaves a bunch of empty space
> 
> The desert ![image](https://private-user-images.githubusercontent.com/51863163/339910594-036b60e4-d818-47b4-bdaf-88daf1224948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDIyMTksIm5iZiI6MTcxODQwMTkxOSwicGF0aCI6Ii81MTg2MzE2My8zMzk5MTA1OTQtMDM2YjYwZTQtZDgxOC00N2I0LWJkYWYtODhkYWYxMjI0OTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDIxNTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZGRlZDMxNjE2ZTBiZWQyZDFlMTRhODk3MGI1NWQ4ZjBkMmM4ZDAwMDEzMjM0ZTU4ZGMxOGRhZWIzZTlmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJyW0Kc-bCUrbc1IYnsRqC_SlxYlri3k0Mm9mm4bJfk)
> 
> At the very least I would keep the button always-shown and just disable it when it's unusable.

![image](https://github.com/tgstation/tgstation/assets/78199449/1f49b821-1540-48d3-b765-90e9d958d526)

2024-06-18 05:46 UTC, LemonInTheDark requested changes
see above

2024-06-18 10:19 UTC, ZephyrTFA commented
if your justification is the downstream wants it.
publish it downstream

2024-06-18 10:23 UTC, AnywayFarus commented
> if your justification is the downstream wants it. publish it downstream

But no one above, except you two, has said you don't need this feature.
I came to you, not because you have to keep maintaining it, but in case you need it, that's how opensource works, no?

2024-06-18 10:24 UTC, AnywayFarus commented
> Your justification is bad. Why should we maintain this if we don't want it. We are not a library. Also why does it not update the ui on delete in your video.

Well, as you coded, that's how it works :).
Manual update used to break styles (and rarely even the whole pref-menu).

2024-06-18 10:25 UTC, mc-oofert commented
I use 1 slot

2024-06-18 10:25 UTC, ZephyrTFA commented
> > if your justification is the downstream wants it. publish it downstream
> 
> But no one above, except you two, has said you don't need this feature.
> I came to you, not because you have to keep maintaining it, but in case you need it, that's how opensource works, no?

Your WIGFTG clearly says you are adding this for downstreams.

2024-06-18 10:28 UTC, AnywayFarus commented
> > > if your justification is the downstream wants it. publish it downstream
> > 
> > 
> > But no one above, except you two, has said you don't need this feature.
> > I came to you, not because you have to keep maintaining it, but in case you need it, that's how opensource works, no?
> 
> Your WIGFTG clearly says you are adding this for downstreams.
All the features that I've added here are necessary for me specifically, only on downstreams.
But I'm sharing them on the premise that you might find it useful.

2024-06-18 19:19 UTC, LemonInTheDark commented
> But no one above, except you two, has said you don't need this feature. I came to you, not because you have to keep maintaining it, but in case you need it, that's how opensource works, no?

I'm not looking to close this pr, I just want you to justify it in a way that is relevant to this codebase. I do not think the idea is inherently bad but your justification read as "This likely isn't useful to you but it is for me". I'm not sure if that was intended though.

You need some reason for us to potentially want this. Since you don't play here the reason you want it for downstream would work, it's possible that would fit some aspect of our project.

2024-06-18 19:21 UTC, LemonInTheDark commented
> if your justification is the downstream wants it. publish it downstream

I do not think this was justification to close, just justification to block since it's something we can discuss and resolve.

> I don't like that we are setting precedents here where I feel the need to warn folks against using the magic word 'downstream' whenever they try to make a PR here.

If someone makes a pr here (or an issue report) it needs to be in the context of this project. I get many people come from downstream but if they're justifying something they need to justify it for THIS codebase. That's it. Can mention a downsteam while also doing that.

2024-06-18 19:50 UTC, LemonInTheDark commented
Spoke to zypher, reopening conditional on some new justification

2024-06-18 20:47 UTC, LemonInTheDark commented
> Cool. I don't mean to be a pain about this, but it's just something I noticed and felt the need to speak up about because it seemed a bit over the top. And hate to see another potential regular contrib be scared off over something silly

If it makes you feel better it was not because of what you said

2024-06-18 23:09 UTC, san7890 commented
the value is apparent for our codebase anyways since it's easier to start from scratch on rebalancing quirks or inventory loadouts. i understand the pr author needs to make those changes but i still have interest in this PR - would have merged it already if it weren't for some concerns on the UI layout

2024-06-19 08:56 UTC, AnywayFarus commented
Uh-oh-oh.
I've gotten better results already on the downstream itself, I'll try to transfer a similar thing here as well.
It's just a different format. of the character list, you have buttons and they have a drop-down list.
I found a solution for auto-updating... which kind of improves the interaction itself a hundredfold, and I think it would fit in here too.

However, I haven't figured out a better place for the TG than the button at the bottom.

2024-06-19 08:58 UTC, AnywayFarus commented
And in general, after translation (or maybe in your language originally) it looked quite rude, like, I offered you qol, instead of saying that "thank you, but we need", they say "why the hell are you trying to put it in our hands".

2024-06-19 09:20 UTC, AnywayFarus commented
Updated the functionality itself, updated the video with the current functionality, updated WIGFTG

2024-06-19 21:48 UTC, merged