New Tech Tree
tgstation/tgstation pull request #84024
Opened 2024-06-15 18:47 UTC by MTandi

## About The Pull Request

Reshuffles the tech tree nodes, adding reagent purity and cybernetic organ scan experiments. The total point requirements barely changed.

<details> 
  <summary>New tech tree</summary>
  <img width="4329" alt="Tech New" src="https://github.com/tgstation/tgstation/assets/3625094/f3f8f508-b859-4478-a0eb-a0ca04df489b">
</details>

## Why It's Good For The Game

- Breaks bloated general nodes into more specialized nodes, making the tree more balanced
- Combines scattered nodes dedicated to a single design into specialized nodes, reducing the number of nodes
- Reshuffles the unlocks within specialized tree to adjust progression on some trees to follow the idead: Cheap nodes first, then nodes that require experiments or nodes of neighbouring trees, then expensive nodes with end-game tech.
- You no longer need a dissection experiment to unlock a microwave, every experiment is relevant to the tree unlocked by it
- With specialized nodes, it is easier to pick a node for the new things that people add
- Better foundation for potential per-department point system. It will be easier to put it on top of a cleaner tree
- The nodes are separated in tiers, with progressively increasing costs, so that early tech is cheap and easy to research with just points, but later tech is more expensive, making the discount experiments for those more likely to be performed.

## Changelog

:cl:
balance: Reshuffled tech tree, making nodes more specialized
add: Introduced reagent purity scan experiments (required for Cryostasis node)
add: Introduced synthetic organ scan experiment (required for top tier cyber organs)
del: Removed machinery and material scanning experiments from the tech tree
/:cl:

2024-06-15 18:56 UTC, MTandi commented
Drafted for feedback.
Note the discord dev project discussion: https://discord.com/channels/326822144233439242/1248189914449973258

2024-06-15 18:56 UTC, DATA-xPUNGED commented
![image](https://github.com/tgstation/tgstation/assets/44149906/3f6c3aa6-fdfd-4f22-8041-b436b332d20e)
I think you copied the wrong thing here

2024-06-15 18:58 UTC, MTandi commented
> ![image](https://private-user-images.githubusercontent.com/44149906/340020651-3f6c3aa6-fdfd-4f22-8041-b436b332d20e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NzgxMDcsIm5iZiI6MTcxODQ3NzgwNywicGF0aCI6Ii80NDE0OTkwNi8zNDAwMjA2NTEtM2Y2YzNhYTYtZmRmZC00ZjIyLTgwNDEtYjQzNmIzMzJkMjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE4NTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZTM2N2M1MDc1NWU1ZmFiNzU5ZDJjZjMxYjZlOTI3OWU1MzU0MWRkM2VhOTM0YjRlZmY5MzhjZWE3MGEzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t29OztqFuvNgmE1rSg2s8e0eC4RoWDuXxicrApkKyVs) I think you copied the wrong thing here

The image is just for referrence, I'm lazy to paint every single detail into the chart. These nodes are the same as in the old tree.

2024-06-15 20:00 UTC, ZephyrTFA requested changes

2024-06-15 20:00 UTC, ZephyrTFA commented on code/modules/research/techweb/all_nodes.dm
alphabetize all of the lists.
no comment headers
split up into subfiles

2024-06-15 20:11 UTC, zoomachina commented
Maybe the plasma cutter shouldn't be hidden behind 6 nodes

2024-06-15 20:36 UTC, Vect0r2 commented
I don't like how genetics is behind two other experiments that they have no control over.

2024-06-15 20:54 UTC, MTandi commented
> Maybe the plasma cutter shouldn't be hidden behind 6 nodes

It is about the same as before in terms of points due to industrial engineering needing 12 500 points

2024-06-15 20:57 UTC, zoomachina commented
> > Maybe the plasma cutter shouldn't be hidden behind 6 nodes
> 
> It is about the same as before in terms of points due to industrial engineering needing 12 500 points

Industrial engineering has the easiest experiment with a 10k discount, it's practically 2.5k if scientists have the smallest amount of experience. This won't be the same here, even if all of these nodes can be paid for with experiments

2024-06-15 20:58 UTC, MTandi commented on code/modules/research/techweb/all_nodes.dm
> +		"razor",
They're ordered manually to appear grouped in UI, so this is on purpose.

2024-06-15 21:17 UTC, MTandi commented
> I don't like how genetics is behind two other experiments that they have no control over.

You can do both of them in sci:

![image](https://github.com/tgstation/tgstation/assets/3625094/eb209397-7dd4-4f9c-9b5d-963cc6ba2bc4)

You can make a slime by taking biopsy from mapspawn slimes, and grow one with protein from tofu.
And the plant can be grown on this patch. There is a maint garden nearby with seeds and left4z, or you can mutate a random weed that spawns on this patch.

Besides, geneticists already have everything needed roundstart, so they don't need this node early anyway.

2024-06-15 21:19 UTC, MTandi commented
> Industrial engineering has the easiest experiment with a 10k discount, it's practically 2.5k if scientists have the smallest amount of experience. This won't be the same here, even if all of these nodes can be paid for with experiments

Will probably move it to Controlled Plasma to avoid backlash, or introduce discounts on the way. But personally I believe it is in the right place in terms of balance.

2024-06-15 22:20 UTC, zoomachina commented on code/modules/research/techweb/all_nodes.dm
> +	required_experiments = list(/datum/experiment/scanning/reagent/cryostaline)
cryostaline -> cryostylane

2024-06-15 22:36 UTC, githubuser4141 commented
Shouldn't the basic mech firearms be researched later, not sooner? The ULTRA-AC2 and Scattershot are incredibly deadly and have the highest DPS in most situations, the AC2 being the best general mech weapon (60 damage a burst, 1200 bullets, 1 second delay). Mech lasers/ions are underwhelming, the standard mech laser fires a single laser at a slow rate of fire, the cannon (40 damage) actually has less DPS due to being twice as slow to fire as the basic laser (25 damage).

The 'heavy' mech weapons are actually fairly worse in combat. Rockets only explode if they strike a solid object like a mech or a wall, otherwise they have 6 shots with no spare magazine, have a long cooldown and only do 20 damage to a person. The flashbang/clusterbang is occasionally useful but still suffers from lack of ammo and flashbangs that seem to blind a person in a mech.

2024-06-15 23:15 UTC, CRITAWAKETS commented
Some of these are a little strangely placed in the higher tiers, like why are Bitrunning, regular RCD upgrades and Engi/Mining Cyborg upgrades all going to cost 10000 points? That's a bit nuts. Especially the engi/mining borg upgrades, given how mining borgs shine more in the early game.

2024-06-15 23:31 UTC, atlasle commented
can you put that tech tree visual in the game

2024-06-16 01:28 UTC, MTandi commented
> can you put that tech tree visual in the game

I've built the tree keeping in mind that we can visualize it with nodes that we have for circuits later. That's why some techs have forced tier - to make sure that all required nodes are on a lower or the same tier.

But I'm not the best to code this into the game as I'm not familiar with node component.

2024-06-16 07:32 UTC, Exester509 commented
I feel like some researches are too late into the tech tree, namely plasma cutters and engineering cyborg upgrades.
MODsuit nodes are also weirdly renamed into exosuits, which used to be the mechs, but that isn't really a concern.

Finally, why is illegal tech gatekept _behind_ unregulated bluespace research and not the other way around? The desynchronizer is one of the most powerful items science can produce, being able to accomplish true inmortality. There's a reason why it's so rare

2024-06-16 10:21 UTC, moocowswag commented
Im okay with where shield gens were put

2024-06-16 11:23 UTC, MTandi commented
> I feel like some researches are too late into the tech tree, namely plasma cutters and engineering cyborg upgrades. 
Will be moved closer

>MODsuit nodes are also weirdly renamed into exosuits, which used to be the mechs, but that isn't really a concern.
There is a confusion between modsuits and exosuits, as in scifi, piloted robots are more commonly called "Mech" and anything with "-suit" is about armored exoskeletons. Took the liberty to call all piloted robots "Mech" and MOD suits as "Exosuit". The other in-game machines are also inconsistent in this naming.

> Finally, why is illegal tech gatekept _behind_ unregulated bluespace research and not the other way around? The desynchronizer is one of the most powerful items science can produce, being able to accomplish true inmortality. There's a reason why it's so rare
Error in the chart graphics, it's the same as before.

2024-06-16 11:28 UTC, MTandi commented
> 10k points for polybelt and all the prerequisites are going to kill it though.

Will merge into the Advanced Anomaly Shells and plan to introduce an anomaly scan discount experiment.

> T4 parts coming earlier in the tree is probably going to be the biggest impact.

Considering updating machine scanning experiments to accept ANY machine with the previous tier parts to unlock the bluespace part.

> Oh wow wait exotic ammunition is also no longer soft removed??? this means tech shells are probably going to see consistent usage in rev cult and nukie rounds.

Considering an experiment to unlock them, requiring side research, or moving to the later part of the tree to cost more

> Engineering and mining borg upgrades becoming a 10k point research thats far down the tree with many prerequisites ... these are tools that are meant to use longterm, you dont want to wait till the round is over to suddenly get the ability to mine better or build machines.

Moving closer.

2024-06-16 16:39 UTC, norsvenska commented
what if the chromatography machine was the thing that did the purity experiments? it makes more sense imo than the regular experiscanner

2024-06-16 16:55 UTC, MTandi commented
> what if the chromatography machine was the thing that did the purity experiments? it makes more sense imo than the regular experiscanner plus, it would give it another use. i haven't seen many people use it.

Good idea. Please code it to do so.

2024-06-16 16:56 UTC, MTandi commented
Updated the tree and introduced some new experiments.

2024-06-16 20:09 UTC, CRITAWAKETS commented
Advanced plasma cutters should probably not be in the same tier as the regular plasma cutter. Honestly putting it in advanced mining with a discount experiment would likely work great, especially since advanced mining currently has the issue of only being attractive if you know a secret gamer technique and nothing else.

2024-06-16 20:26 UTC, moocowswag commented
Bcis should be another separate branch alongside drone shells and programmed servers rather than being gated behind drone shells, research is not meant to be what gatekeeps circuits as they themselves are their own subdepartment that requires alot of undivided attention to work on, comparable to genetics and viro. There is no "passively wait on progress" you have to invest a large portion of the round into making them and get them early.

Or just add discount experiments to them related to making an easy circuit

I can already see myself getting lynched because this pr makes me spend ALOT more points to get bcis which only i'll be using, currently I spend 3k research points TOTAL throughout an entire round on circuits because im able to just grab the starting tech and bci and i dont touch drones or server shell and i still get yelled at.

2024-06-16 22:16 UTC, MTandi commented
> Advanced plasma cutters should probably not be in the same tier as the regular plasma cutter. Honestly putting it in advanced mining with a discount experiment would likely work great, especially since advanced mining currently has the issue of only being attractive if you know a secret gamer technique and nothing else.

Advanced one is on tier 3 together with the mech variant. Regular is on tier 2 now. 
Advanced mining is appealing at least in the diamond drill that breaks reinforced walls. I don't know the secret gamer technique, but I think that diamond drills and jackhammer should be buffed or given a secondary utility, as they're not nearly as good as plasma cutters for mining.

2024-06-16 23:12 UTC, MTandi commented
> TLDR: Just remove drone shells/programmed bot as a prerequisite for bci and maybe add a discount experiment.

![image](https://github.com/tgstation/tgstation/assets/3625094/77093286-01c0-4822-a133-81e0d706ea30)

2024-06-17 05:23 UTC, moocowswag commented
So usually scan both roboticists/the rd/engies/alot of jobs really or use the entertainment vendor to get the toy skillchips

2024-06-17 08:03 UTC, Maximal08 commented
I don't really like the option with the bluespace rped only when studying 4 tiers of parts, because the usual rped is not the most convenient thing, and such a late study of a more convenient alternative will make the life of those who assemble machinery more difficult.

2024-06-17 09:56 UTC, MTandi commented
> So usually scan options are both roboticists/the rd/engies/alot of jobs really or use the entertainment vendor to get the toy skillchips

Any skillchips, so you can just scan a clown and a roboticist.

2024-06-17 11:01 UTC, MTandi commented
> I don't really like the option with the bluespace rped only when studying 4 tiers of parts, because the usual rped is not the most convenient thing, and such a late study of a more convenient alternative will make the life of those who assemble machinery more difficult. but on the other hand, 4 thousand details appear earlier.

It's a purpose of tech tree to make people use less convenient things, do research, unlock more convenient things one by one and be happy that what they did just became more convenient with the research. 

That's why I'm a fan of moving plasma cutters to the later nodes. But I don't want to be that guy that made miners suffer more than before this PR. Let maintainers decide this kind of balance things.

2024-06-17 11:08 UTC, Maximal08 commented
> > I don't really like the option with the bluespace rped only when studying 4 tiers of parts, because the usual rped is not the most convenient thing, and such a late study of a more convenient alternative will make the life of those who assemble machinery more difficult. but on the other hand, 4 thousand details appear earlier.
> 
> It's a purpose of tech tree to make people use less convenient things, do research, unlock more convenient things one by one and be happy that what they did just became more convenient with the research.
> 
> That's why I'm a fan of moving plasma cutters to the later nodes. But I don't want to be that guy that made miners suffer more than before this PR. Let maintainers decide this kind of balance things.
> 
> You don't usually need to upgrade more than a couple of machines for your job, so you won't die if you have to use a screwdriver a couple of times. And parts provide linear efficiency boost, rather than an instant milestone like plasma cutters. So it is fine to not have the t4 with bluespace RPED unlocked ASAP.

I generally like these changes, although advanced and conventional cutters in the same technology raise questions, and I'm looking forward to it in the game with the goal of seeing what happens.

2024-06-17 11:09 UTC, MTandi commented
> I generally like these changes, although advanced and conventional cutters in the same technology raise questions, and I'm looking forward to it in the game with the goal of seeing what happens.

The regular one is T2 (Controlled plasma node), the upgraded one is T3 (Plasma beam mining). The one next to it is a mech variant.

2024-06-17 11:17 UTC, Maximal08 commented
> > I generally like these changes, although advanced and conventional cutters in the same technology raise questions, and I'm looking forward to it in the game with the goal of seeing what happens.
> 
> The regular one is T2 (Controlled plasma node), the upgraded one is T3 (Plasma beam mining). The one next to it is a mech variant. Wrong icon in the tree.

a funny mistake, which is why this change seemed strange to me.

2024-06-17 17:21 UTC, ZephyrTFA commented
fuck it

2024-06-17 17:21 UTC, merged

2024-06-17 22:28 UTC, LSommers commented
This PR is great if only because I can laugh at people salting in OOC that Research and Development has to Research and Develop now.