Add valve opening sound to manual valve
tgstation/tgstation pull request #84049
Opened 2024-06-16 20:18 UTC by TheBoondock

## About The Pull Request
Adds a squeaky turning sound and hissing sound to opening valve

## Why It's Good For The Game

https://github.com/tgstation/tgstation/assets/92416224/811b0470-a63c-41ae-a854-b1037d3ed9ac

## Changelog

:cl:
sound: added squeaky turn and gas hissing sound to gas valve
/:cl:

2024-06-16 20:45 UTC, CRITAWAKETS commented
Two questions.
1) Does the gas hissing sound play even if there's no gas in the pipe?
2) Do the digital valves also play this sound?

2024-06-16 21:20 UTC, TheBoondock commented
> Two questions.
> 
> 1. Does the gas hissing sound play even if there's no gas in the pipe?
> 2. Do the digital valves also play this sound?

yes to both, ill see what i can do about the gas presence part maybe seperating the sounds instead. Digital valve should squeak too cause why should the silicon gets oiled valve, no they should be getting neglected valve the same as us.

2024-06-16 23:37 UTC, DATA-xPUNGED commented
The squeak should be done DURING the spinning animation, not after

2024-06-16 23:50 UTC, TheBoondock commented
> The squeak should be done DURING the spinning animation, not after

Done! plus i split up the sound so its more natural

2024-06-17 04:25 UTC, moocowswag commented
Make it so opening/triggering a ttv does this too lol

2024-06-17 18:34 UTC, san7890 requested changes

2024-06-17 18:34 UTC, san7890 commented on code/modules/atmospherics/machinery/components/binary_devices/valve.dm
> +		playsound(src, 'sound/effects/valve opening.ogg', 50)
```suggestion
		playsound(src, 'sound/effects/valve_opening.ogg', 50)
```

2024-06-17 18:34 UTC, san7890 commented on sound/effects/valve opening.ogg
change the name of this file to be `valve_opening.ogg` because i'm pretty sure some server operator will kill you for having a filename with whitespaces in it

2024-06-17 22:25 UTC, merged