Send signal on help intent checks before handling fire
tgstation/tgstation pull request #84134
Opened 2024-06-19 09:51 UTC by Ephemeralis

## About The Pull Request

Noticed this when doing work downstream - `help_shake_act` dies on the `on_fire` check before it fires the signal, meaning that any signal-related help intent behavior related to fire can basically never be written. Very simple rearrangement to fix this.

Hopefully should be little player facing result.

## Why It's Good For The Game

Allows for better, less spaghetti-code handling of fire-related behaviors using signals instead of horrific overrides or drop-in edits.

2024-06-19 09:54 UTC, LemonInTheDark requested changes
I'm not sure I agree with this. Most consumers of the signal involve the mob acting on the relevant carbon with like, their hands, and being blocked by fire makes sense for that. Can you justify why being on fire should allow the signal in a bit more detail?

2024-06-19 09:58 UTC, Ephemeralis commented
> Most consumers of the signal involve the mob acting on the relevant carbon with like, their hands, and being blocked by fire makes sense for that. Can you justify why being on fire should allow the signal in a bit more detail?

If I wanted to write a mutation that for example, allowed "frost hands" or something to use a human mob's hands to help put out fire, I'd have to write a override of the entire proc to achieve that instead of doing the sane thing and passing the functionality off to a signal handling proc.

The consumers of the signal should check to see whether fire is appropriate for their behavior instead of it being an explicit "no, you can never override any behavior related to help-intent on things that are on fire". It's sensical, right?

2024-06-25 02:44 UTC, ShizCalev requested changes

2024-06-25 02:44 UTC, ShizCalev commented on code/modules/mob/living/carbon/carbon_defense.dm
> +		to_chat(helper, span_warning("You can't put [p_them()] out with just your bare hands!"))
this absolutely is a player facing change - you can now do CPR on someone who's on fire lol

just add another signal. 
```suggestion
/mob/living/carbon/proc/help_shake_act(mob/living/carbon/helper)

	if(SEND_SIGNAL(src, COMSIG_CARBON_ATTEMPT_MISC_HELP, helper) & COMPONENT_BLOCK_MISC_HELP)
		return	
	if(on_fire)
		to_chat(helper, span_warning("You can't put [p_them()] out with just your bare hands!"))
		return

	if(SEND_SIGNAL(src, COMSIG_CARBON_PRE_MISC_HELP, helper) & COMPONENT_BLOCK_MISC_HELP)
		return	

```

2024-06-25 11:43 UTC, closed without merging

2024-06-26 00:29 UTC, LemonInTheDark commented
?