Fixes the visor of the welding mask going down when you use internals
tgstation/tgstation pull request #84135
Opened 2024-06-19 11:10 UTC by combustor

## About The Pull Request
The visor of the welding mask no longer goes down when you enable internals

## Why It's Good For The Game
You'll no longer go semi-blind when you activate internals while using this mask
Fixes #83728 

## Changelog
:cl: Guestify
fix: The visor of the welding mask no longer goes down when you enable internals
/:cl:

2024-06-19 11:45 UTC, Fikou requested changes
this is a snowflake fix. you need to make it generic - apply it to all masks that don't need to be adjusted to have their internals work

2024-06-19 12:29 UTC, combustor commented
Would this be okay? I didn't find any other mask that requires this exemption

2024-06-23 22:13 UTC, san7890 requested changes

2024-06-23 22:13 UTC, san7890 commented on code/_globalvars/bitfields.dm
> +	"INTERNALS_ADJUST_EXEMPT" =INTERNALS_ADJUST_EXEMPT,
```suggestion
	"INTERNALS_ADJUST_EXEMPT" = INTERNALS_ADJUST_EXEMPT,
```

2024-06-23 22:13 UTC, san7890 commented on code/modules/clothing/masks/gasmask.dm
> +	clothing_flags = MASKINTERNALS | INTERNALS_ADJUST_EXEMPT
```suggestion
	clothing_flags = parent_type::clothing_flags | INTERNALS_ADJUST_EXEMPT
```

this is to ensure we don't desynce from any changes on parent types.

2024-06-25 03:51 UTC, merged