Adds pen clicking, changes most pen typechecks into writing implement checks
tgstation/tgstation pull request #84186
Opened 2024-06-20 23:17 UTC by SmArtKar

## About The Pull Request

Fixes #84170 
Adds pen clicking and changes some of edagger and pendriver code to use it instead.
Also replaces most pen typechecks to writing implement checks where it makes sense, so now you can rename things with everything you can write with (crayons)

![3d6NwcATNp](https://github.com/tgstation/tgstation/assets/44720187/f6b3ba2f-f3de-4e40-827f-2bad153a92f4)

Twisting pen caps (for traitor uplinks) has been moved to ctrl + click instead.

## Why It's Good For The Game

Fixes a bug, makes sense that you'd be able to rename stuff with crayons, and clicking is annoying.
Clicky sound included.

## Changelog

:cl:
add: You can now click pens! Clickity clickery click!
fix: E-Daggers can now break lockers/other renamable objects, and pendrivers can now extract their electronics.
code: Most pen typechecks now check for writing implements.
/:cl:

2024-06-21 03:48 UTC, MrMelbert requested changes
Maybe we should have a helper macro for checking if something is a writing utensil

`#define IS_WRITING_UTENSIL(thing) (thing.get_writing_implement_details()?["interaction_mode"] == MODE_WRITING)`?

2024-06-21 03:48 UTC, MrMelbert commented on code/game/objects/structures/signs/_signs.dm
> +	if(is_editable && held_item.get_writing_implement_details()?["interaction_mode"] == MODE_WRITING)
Be careful, you changed some checks like this from something null-safe to something that will runtime

`istype(null, pen)` works, this does not. 

Add context is namely what you should be worried about, attackby and co are safe

2024-06-21 03:48 UTC, MrMelbert commented on code/modules/paperwork/pen.dm
> +		return null
Get component >:(

Just check `TRAIT_TRANSFORM_ACTIVE`

2024-06-21 03:48 UTC, MrMelbert commented on code/modules/paperwork/pen.dm
> +		return
This var is weird, just have its own proc `setup_transforming` which subtypes can override

2024-06-21 03:48 UTC, MrMelbert commented on code/modules/paperwork/pen.dm
> +	var/can_click = TRUE // If this pen can be clicked in order to retract it
Autodoc this (`///` above the comment)

2024-06-21 04:16 UTC, optimumtact commented
you should make it so if someone clicks conseuctively 100,000 times without being interrupted they get an achievement + they get greentext (and become valid)

2024-06-21 21:39 UTC, LSommers commented
> you should make it so if someone clicks consecutively 100,000 times without being interrupted they get an achievement + they get greentext (and become valid)

Every click above 100 in a row should give an ever-higher chance of making your arm blow off from the stress, but make the 100,000 clicks a per-round counter.

Make them earn that achievement.

2024-06-24 21:08 UTC, merged

2024-07-06 00:58 UTC, SmArtKar commented
> you cant open pen uplinks with this change

you can, been moved to ctrl + click functionality