Refactors genetic meltdowns into datums
tgstation/tgstation pull request #84558
Opened 2024-07-01 18:26 UTC by SmArtKar

## About The Pull Request

Genetic meltdowns now use datums instead of a prob and switch monstrocity, making them far more readable. Requested by Jacquerel on discord.

Additionally, removed 0.83% chance for a meltdown to turn you into a dullahan, as those are extremely broken right now.

## Why It's Good For The Game

This system is much nicer, readable and more extendable than the current one.

## Changelog

:cl:
del: You can no longer get turned into a dullahan by a genetic meltdown
refactor: Refactored genetic meltdown code into datums, making it more extendable.
/:cl:

2024-07-01 19:02 UTC, EuSouAFazer commented
thank god fuck dullahams

2024-07-01 20:02 UTC, moocowswag commented
Broken as in doesnt work/not maintained or unbalanced, cause it seems in line with arcade pulse pistol, rare maint loot, die of fate, etc

2024-07-01 20:37 UTC, Jacquerel requested changes

2024-07-01 20:37 UTC, Jacquerel commented on code/datums/instability_meltdown.dm
> +	var/meltdown_weight = 0
If almost all of these are `1` why didn't you default it to 1?

2024-07-01 20:37 UTC, Jacquerel commented on code/datums/instability_meltdown.dm
> +	var/obj/item/organ/O = pick(elligible_organs)
While you're touching this give it a better var name

2024-07-01 20:37 UTC, Jacquerel commented on code/datums/instability_meltdown.dm
> +	var/meltdown_weight = 0
I am not 100% sure what adding something with a weight of 0 does but I don't think it actually makes it _totally_ impossible for it to roll, unintuitively.
If this is to support the abstract fatal type, you might need to add an abstractness check as well (`var/abstract_type = typepath` then check against that path is a pattern we often use, so it doesn't need to be overridden in all children)

2024-07-01 20:40 UTC, Jacquerel commented
> Broken as in doesnt work/not maintained or unbalanced, cause it seems in line with arcade pulse pistol, rare maint loot, die of fate, etc
> 
> Nevermind i read the linked issue, im too used to the league of legends context of “broken”

Dullahans have only been barely functional most halloweens, often nonfunctional, and get worse every time.

2024-07-03 10:51 UTC, Time-Green requested changes
Very nice! Minor suggestions

2024-07-03 10:51 UTC, Time-Green commented on code/datums/dna.dm
> +			valid_meltdowns[meltdown_type] = initial(meltdown_type.meltdown_weight)
tbh if you're caching all this you might as well cache this as well. Keep the possible types as a static list, and only generate it the first time by checking the length

2024-07-03 10:51 UTC, Time-Green commented on code/datums/instability_meltdown.dm
> +/datum/instability_meltdown
Autodoc the type please

2024-07-03 10:51 UTC, Time-Green commented on code/datums/instability_meltdown.dm
> +	var/obj/item/bodypart/BP = victim.get_bodypart(pick(BODY_ZONE_CHEST,BODY_ZONE_HEAD))
```suggestion
	var/obj/item/bodypart/part= victim.get_bodypart(pick(BODY_ZONE_CHEST, BODY_ZONE_HEAD))
```
write the varnames out ('part' or something is fine)

2024-07-03 10:51 UTC, Time-Green commented on code/datums/instability_meltdown.dm
> +	victim.physiology.damage_resistance -= 20000 //you thought
can you log this btw? its pretty severe

2024-07-03 16:01 UTC, Time-Green commented on code/datums/dna.dm
> +	var/static/list/meltdown_cache = typecacheof(/datum/instability_meltdown, ignore_root_path = TRUE)
you can drop this cache now btw, its only used once

2024-07-03 17:17 UTC, Time-Green commented on code/datums/dna.dm
> +	if(!LAZYLEN(dna.nonfatal_meltdowns))
```suggestion
	if(!dna.nonfatal_meltdowns.len)
```
Lazylen is only if you don't know if there's a list instance, but you instantiate it as a list() so .len is 'better' here

2024-07-03 18:25 UTC, merged