Creates an EMP act for Jetpacks + minor buffs to sec modsuits
tgstation/tgstation pull request #84582
Opened 2024-07-02 15:18 UTC by EnterTheJake

## About The Pull Request

Jetpacks are now vulnerable to EMP, they get disabled for a few seconds after getting hit by an EMP blast.

Sec modsuits now start with the jetpack module preinstalled and their starting powercell has been upgraded.

## Why It's Good For The Game

It's no secret that regular jetpacks and your run of the mill eva suit see far more use than actual security issued equipment.

Having your best option being available from the start of the shift is just boring, and doesn't encourage the crew to even engage with Modsuits in any way.

With this PR i'm introducing a weakness to jetties by having em turn of for 4 seconds if you get hit by a pulse, while making sec mods a bit more suited for their job, by making them spawn with a better cell and jetty module.

## Changelog

:cl:

balance: Jetpacks are now briefly disabled by EMP.
balance: Security modsuits now spawn with a better cell and the jetpack module preinstalled.
/:cl:

2024-07-02 15:29 UTC, zoomachina commented
You give up a backpack slot to use a jetpack from EVA storage, if modsuit jetpacks are somehow worse than normal ones it's because they're really weak

2024-07-02 15:40 UTC, EnterTheJake commented
> You give up a backpack slot to use a jetpack from EVA storage, if modsuit jetpacks are somehow worse than normal ones it's because they're really weak

Insignificant, you can still carry a bag around with you.

 It's annoyng but more than makes up not having to deal with all the tradeoffs of wearing a modsuit.
 
 And i do agree they are weak, that's why i'm buffing em.

2024-07-02 15:58 UTC, DaCoolBoss commented
Randomise the movement + slowdown instead of forcing a full stop, because 4 seconds of them being unable to move without throwing items makes it trivial to combo EMP + any ranged weapon to instawin space combats. Especially with an EMP proof modsuit and ballistic gun. 

Also not sure about making this affect old school jetpacks at all? Losing bag slot is a huge deal, bag needs to be dropped or stashed to use a 2 handed gun. Doesn't really match the flavour either, jetpacks don't use electronics besides pressure readouts on some sprites.

2024-07-02 16:31 UTC, moocowswag commented
Does this only effect electrical/ion  jetpacks 
and not mechanical ones that use gasses?

2024-07-02 17:24 UTC, EnterTheJake commented
> Randomise the movement + slowdown instead of forcing a full stop, because 4 seconds of them being unable to move without throwing items makes it trivial to combo EMP + any ranged weapon to instawin space combats. Especially with an EMP proof modsuit and ballistic gun.
> 
> Also not sure about making this affect old school jetpacks at all? Losing bag slot is a huge deal, bag needs to be dropped or stashed to use a 2 handed gun. Doesn't really match the flavour either, jetpacks don't use electronics besides pressure readouts on some sprites.



> Does this only effect electrical/ion jetpacks and not mechanical ones that use gasses? (The makeshift one for example)
> 
> if you are flying through space with a jetpack and you get hit by emp do you continue going through space at the same or similar speed or do you just suddenly stop?

It effects all jetpacks, upon being hit you root for 4 seconds but can still change z level.

2024-07-02 17:27 UTC, moocowswag commented
I dont think it should delete your velocity if youre on a space turf atleast

2024-07-02 17:27 UTC, EnterTheJake commented
> Randomise the movement + slowdown instead of forcing a full stop, because 4 seconds of them being unable to move without throwing items makes it trivial to combo EMP + any ranged weapon to instawin space combats. Especially with an EMP proof modsuit and ballistic gun.
> 
> Also not sure about making this affect old school jetpacks at all? Losing bag slot is a huge deal, bag needs to be dropped or stashed to use a 2 handed gun. Doesn't really match the flavour either, jetpacks don't use electronics besides pressure readouts on some sprites.

No, that's entirely the point, a modsuit should be better in space  than an eva suit with a jetpack.

2024-07-02 18:16 UTC, zoomachina commented
> No, that's entirely the point, a modsuit should be better in space than an eva suit with a jetpack.

1. Why?
2. Modsuit hit by EMP might suffer even worse problems
3. If you really think that, why won't you make modsuit jetpack better instead of making normal jetpack worse and calling it a buff to the former?

2024-07-02 18:28 UTC, EnterTheJake commented
> > No, that's entirely the point, a modsuit should be better in space than an eva suit with a jetpack.
> 
> 1. Why?
> 2. Modsuit hit by EMP might suffer even worse problems
> 3. If you really think that, why won't you make modsuit jetpack better instead of making normal jetpack worse and calling it a buff to the former?



> > No, that's entirely the point, a modsuit should be better in space than an eva suit with a jetpack.
> 
> 1. Why?
> 2. Modsuit hit by EMP might suffer even worse problems
> 3. If you really think that, why won't you make modsuit jetpack better instead of making normal jetpack worse and calling it a buff to the former?



> > No, that's entirely the point, a modsuit should be better in space than an eva suit with a jetpack.
> 
> 1. Why?
> 2. Modsuit hit by EMP might suffer even worse problems
> 3. If you really think that, why won't you make modsuit jetpack better instead of making normal jetpack worse and calling it a buff to the former?

1) Because modsuits are specifically designed to be the go to option for going to space, having to carry a bag it's a minor inconvenience when you don't need to manage your power, modules or the suit slowdown.
2) Modsuits emp act is fairly forgiving, it can randomly pulse a few wires but that's about it, besides with the tech rework you can gain access to emp shielding in the first 10 minutes of the shift, go to robotics and ask for an upgrade.
3) There is no need, the jetpack module is good as it is, maybe a bit power hungry, but that's about it.

2024-07-02 19:11 UTC, zoomachina commented
> 1. Because modsuits are specifically designed to be the go to option for going to space, having to carry a bag it's a minor inconvenience when you don't need to manage your power, modules or the suit slowdown.

Objectively wrong, modsuits are specifically designed to be modular, i.e. being useful for a variety of purposes depending on the module set, whereas jetpacks' only purpose is to be used for spacefaring (and even then they take up a bag slot, even if you refuse to acknowledge it's a major drawback). I think it makes sense for the jack-of-all-trades option to be weaker than specialist one. 
Furthermore, both security modsuits and jetpacks are available roundstart, so 
> Having your best option available from the start of the shift is just boring (c) "Why It's Good For The Game"

makes no sense in the context of justifying your pr.
> 3. There is no need, the jetpack module is good as it is, maybe a bit power hungry, but that's about it.

It's also slower than a normal jetpack (as it should be)

2024-07-02 19:47 UTC, Higgin commented
Secmod having a jetpack stock is a good change  Unfortunately, free space tiding is still a thing, in spite ending that being one of the goals of MODsuits, and they're overdue for what should rightly be considered a piece of necessary kit.

2024-07-02 20:13 UTC, SomeoneYouProbablyKnow commented
"Minor buffs to sec"
look inside
Doubles the amount of jetpacks easily accessible to security

Considering how stupid jetpack speed is and how often nuckies disable grav gen this is a crazy buff.
It's not like a jetpack is only useful outside the station and the minor emp effect does nout outweigh the buff that makes sec even more self sufficient.

2024-07-02 20:24 UTC, moocowswag commented
I dont think sec modsuits should have better cells for the sake of having better cells, they should already be encouraged to get better cells and by extension, get their gun rechargers upgraded, probably the best excuse for warden to be out of brig.

2024-07-02 20:27 UTC, EnterTheJake commented
@zoomachina 

Modsuits are designed to be modular with the ability to specialize in one area.

 Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.

Both jetties and mods are available round start, modsuits however need to be mantained and upgraded, jetties have no need of such a thing.

 As you've described Jetpacks are already faster than the modules and become even more desired once adaptations or hypernob crystals have been obtained as you don't even need to wear an eva suit anymore.

2024-07-02 20:30 UTC, moocowswag commented
> Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.

the pepper spray defense module , which is useless against someone with eva gear

2024-07-02 20:38 UTC, SomeoneYouProbablyKnow commented
> Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.

There would be if they had jetpacks. 

And yes you can take the limited eva jetpacks or order them or craft improvised jetpacks but doing any of that is part of the game. Security shouldn't get everything handed to them because "their job is to hunt valids"

2024-07-02 20:39 UTC, EnterTheJake commented
> > Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.
> 
> the pepper spray defense module , which is useless against someone with eva gear, but thats the only contradiction i think



> > Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.
> 
> the pepper spray defense module , which is useless against someone with eva gear, but thats the only contradiction i think



> > Sec modsuits were specifically made to hunt criminals in space, as there's not much of a reason to ever use em on station.
> 
> There would be if they had jetpacks.
> 
> And yes you can take the limited eva jetpacks or order them or craft improvised jetpacks but doing any of that is part of the game. Security shouldn't get everything handed to them because "their job is to hunt valids"

The idea was for sec to go to robotics to requested a module, admittedly they should probably have had something so crucial to their job at roundstart.

2024-07-02 21:25 UTC, DaydreamIQ commented
> "Minor buffs to sec" look inside Doubles the amount of jetpacks easily accessible to security
> 
> Considering how stupid jetpack speed is and how often nuckies disable grav gen this is a crazy buff. It's not like a jetpack is only useful outside the station and the minor emp effect does not outweigh the buff that makes sec even more self sufficient.
> 
> The emp effect is neat, not TOO debilitating but sufficiently annoying

This wont affect nukies in the slightest. Sec get ion jetpacks which are considerably slower, Nukies get advanced ones which have the same speed as EVA jetpacks. One of the most annoying things to deal with as sec is someone in space because you literally cannot catch up to anyone with a jetpack which leads to really awkward baton jousting that you're never going to be able to capitalize on

2024-07-02 22:37 UTC, SimplySmiley123 commented
> > Randomise the movement + slowdown instead of forcing a full stop, because 4 seconds of them being unable to move without throwing items makes it trivial to combo EMP + any ranged weapon to instawin space combats. Especially with an EMP proof modsuit and ballistic gun.
> > Also not sure about making this affect old school jetpacks at all? Losing bag slot is a huge deal, bag needs to be dropped or stashed to use a 2 handed gun. Doesn't really match the flavour either, jetpacks don't use electronics besides pressure readouts on some sprites.
> 
> No, that's entirely the point, a modsuit should be better in space than an eva suit with a jetpack.

And this does not fix a damn thing about that but make it overall much more annoying for everyone.
People would still pick regular jetpack and space suit over the hassle of a modsuit anyway.

2024-07-02 22:40 UTC, SimplySmiley123 commented
> "Minor buffs to sec" look inside Doubles the amount of jetpacks easily accessible to security
> 
> Considering how stupid jetpack speed is and how often nuckies disable grav gen this is a crazy buff. It's not like a jetpack is only useful outside the station and the minor emp effect does not outweigh the buff that makes sec even more self sufficient.
> 
> The emp effect is neat, not TOO debilitating but sufficiently annoying

Modsuit jetpacks are slow as hell, and the EMP effect is a killer, 4 seconds with no momentum preservation sucks hard with how easy it is to get EMPs.

2024-07-02 22:48 UTC, SimplySmiley123 commented
> 
> 1. Because modsuits are specifically designed to be the go to option for going to space, having to carry a bag it's a minor inconvenience when you don't need to manage your power, modules or the suit slowdown.
> 2. Modsuits emp act is fairly forgiving, it can randomly pulse a few wires but that's about it, besides with the tech rework you can gain access to emp shielding in the first 10 minutes of the shift, go to robotics and ask for an upgrade.
> 3. There is no need, the jetpack module is good as it is, maybe a bit power hungry, but that's about it.

1) Supposed to be, but the way they are now no one wants to use them because of how big of  a pain it is compared to literally any other EVA methods.
2) It's not forgiving, you got an RNG roll of a dice deciding wether or not you'll be able to take your suit off at all or interact with it without shocking yourself.
3) It's not, it's slow as hell and power hungry, you're better off with a makeshift jetpack then the jetpack module.

2024-07-02 22:56 UTC, SomeoneYouProbablyKnow commented
> This wont affect nukies in the slightest. Sec get ion jetpacks which are considerably slower, Nukies get advanced ones which have the same speed as EVA jetpacks. 

I'd much rather have that than not. That way i'd have at least have a chance. So it's not insignificant especially considering how scarce jetpacks are to begin with (Yes there are ways to get more but no one ever does)

> One of the most annoying things to deal with as sec is someone in space because you literally cannot catch up to anyone with a jetpack which leads to really awkward baton jousting that you're never going to be able to capitalize on

If the antag goes out of his way to acquire a jetpack, they deserve to run circles around sec at least untill they get their own. Don't want the heat, don't follow them into space.
You're not entitled to having all the countermeasures in brig ready for you, security is not 'easy hunt antags' mode.
Running to eva for a jetpack to get a perp in space is litererally THE game.

But yes jetpack speed combat is awful. Wish there was less of it not more

2024-07-03 02:22 UTC, Jackal-boop commented
These changes should be split into distinct PRs

2024-07-03 02:51 UTC, Blacklist897 commented
remove advanced ions and make all forms of jetpack (apart from the jet harness and the modsuit fitting captains pack) the same speed

2024-07-03 03:42 UTC, CRITAWAKETS commented
This currently makes the EMP effect work on the captain's jetpack and the syndicate jet harness. Probably shouldn't do that.

2024-07-03 06:21 UTC, Exester509 commented
I'm pretty sure the mirage module, as well as the pepper shoulders, cannot be printed from R&D. This would make them unobtainable.

Aditionally, it makes zero sense that an EMP can affect manual valves.

2024-07-03 07:05 UTC, projectkepler-ru reviewed
If you seriously want to buff sec modsuit I'd advise making them able to put the old security oxygen jetpack onto their suit slot and putting the jetpack into those bulky suit storage that doesnt even recharge the cell
Or give them a roundstart tether, an outright jetpack is rediculous. Yes, a lot of antag has space capability or rapid movement in space, but security make up for it is their numbers, coordination and they're generally allowed to use equipment freely

2024-07-03 07:57 UTC, EnterTheJake commented
> I'm pretty sure the mirage module, as well as the pepper shoulders, cannot be printed from R&D. This would make them unobtainable.
> 
> Aditionally, it makes zero sense that an EMP can affect manual valves.

They still have electronics in them.

2024-07-03 22:25 UTC, Skebulba commented
Weird for sec to get roundstart jetpacks in their suits but not engi imo

2024-07-04 19:12 UTC, alien3301 commented
The EMP effect on jetpacks is fine. Just move around environment stuff if enemies have emp.

2024-07-04 19:13 UTC, alien3301 commented
> Weird for sec to get roundstart jetpacks in their suits but not engi imo

Engi don't need those as much as sec. The modsuit is for pressure protection during breaches and setting up solars. In both cases you 99% of the time have grav or stuff to push off of.

2024-07-08 15:34 UTC, Fikou commented on code/game/objects/items/tanks/jetpack.dm
> +	var/full_speed = TRUE
this has been removed

2024-07-08 15:34 UTC, Fikou requested changes
put mirage grenade dispensers into rnd please

2024-07-08 20:06 UTC, merged