Maddening science
tgstation/tgstation pull request #84725
Opened 2024-07-06 20:46 UTC by Lufferly

## About The Pull Request

Added the genetically modified xenomorph crate to cargo, unlocked for purchase after science researches xenobiology. The facehugger inside can create a xenomorph, but said xenomorph will be infertile and only be able to create sterile facehuggers. Infertile queens do not count towards the queen cap, but will still weaken the hive when they die.
As incentive for science to buy and raise a xenomorph, added an experiment for scanning pre-larval xenomorph lifeforms (eggs, facehuggers, and embryos), unlocked for experimentation after researching xenobiology. Scanning enough grants a hefty 500 research points.

## Why It's Good For The Game

Main inspiration was to add some department interaction between cargo and science, and add a slightly dangerous but rewarding project for the entire science department. If science wants the points, or just the challenge, they can try their hand at setting up containment for a xenomorph. If they fail its bad, but not round ending since an escaped xenomorph wont go on to create an army. Either way its bound to add some tension to the shift.

## Changelog

:cl: Seven
add: You can now buy a genetically modified facehugger from cargo, unlocked after science researched xenobiology.
add: Added a science experiment for scanning pre-larval xenomorph lifeforms.
/:cl:

2024-07-06 22:18 UTC, Loafin34 commented
this sounds really cool, but what if you could operate on a xeno to make it sterile?

2024-07-06 23:09 UTC, CRITAWAKETS commented
Can you still take the queen's organs if you do this? If so, powergamers are veeery likely to start raising these xenos in 1x1 reinforced wall boxes in order to get the organs, leading to the most boring gameplay ever. This already sometimes happens with the random xenobio egg spawn, if the scientist actually wants to do this.

2024-07-06 23:56 UTC, Iamgoofball commented
absolutely not holy shit

2024-07-06 23:57 UTC, carlarctg commented
they spaye the god damnf acehugger

2024-07-07 01:16 UTC, nianjiilical commented
the funny thing is, without the ability to reproduce i dont think most players would even go queen

if you're going to be the only xeno anyway just go hunter or *maybe*p praetorian

2024-07-07 02:29 UTC, Lufferly commented
> Can you still take the queen's organs if you do this? If so, powergamers are veeery likely to start raising these xenos in 1x1 reinforced wall boxes in order to get the organs, leading to the most boring gameplay ever. This already sometimes happens with the random xenobio egg spawn, if the scientist actually wants to do this.

Cant think of a clean way to counter this. If this is isnt already against the rules and likely to be a problem then this probably shouldnt get merged.

2024-07-07 03:08 UTC, MrMelbert commented
Looking at the code, you tied the sterility to the organs, so that should mean people can't kill the queen to raise an army, right?

2024-07-07 03:57 UTC, Lufferly commented
> Looking at the code, you tied the sterility to the organs, so that should mean people can't kill the queen to raise an army, right?

Correct, the queens will get a sterile eggsac which can only create sterile facehuggers.

2024-07-07 05:34 UTC, zoomachina commented
this sounds good but
> unlocked for purchase after science researches xenobiology

why this restriction?
> will still weaken the hive when they die

that hive would apparently be produced by some other queen, so why should this happen?

2024-07-07 07:05 UTC, MrMelbert commented
On one hand I think this is cool because I think science experimenting on aliens (not necessarily just xenos and slimes mind you, but aliens in general) is cool, so encouraging it = good

On the other hand it'll make the 1% egg spawn less special which is sad

2024-07-07 08:48 UTC, SomeoneYouProbablyKnow commented
There should be a way to make the xeno not-sterlie. Clearly it should be an emag_act.

2024-07-07 14:35 UTC, SimplySmiley123 commented
> > Can you still take the queen's organs if you do this? If so, powergamers are veeery likely to start raising these xenos in 1x1 reinforced wall boxes in order to get the organs, leading to the most boring gameplay ever. This already sometimes happens with the random xenobio egg spawn, if the scientist actually wants to do this.
> 
> Cant think of a clean way to counter this. If this is isnt already against the rules and likely to be a problem then this probably shouldnt get merged.

I mean, the egg laying gland could just be making sterlie facehugger eggs instead of real ones and a majority of crew going after the xeno organs would miraculously not care anymore, would just be the ones looking for the xeno eyes left.

2024-07-07 14:35 UTC, SimplySmiley123 commented
> There should be a way to make the xeno not-sterlie. Clearly it should be an emag_act.

How
       how do you swipe an emag on a xenomorph

2024-07-07 14:36 UTC, SomeoneYouProbablyKnow commented
Yes, we need more emag acts, double the already insane amount we already have. You should be able to emag every single items ever

2024-07-07 16:07 UTC, Exester509 commented
> > Can you still take the queen's organs if you do this? If so, powergamers are veeery likely to start raising these xenos in 1x1 reinforced wall boxes in order to get the organs, leading to the most boring gameplay ever. This already sometimes happens with the random xenobio egg spawn, if the scientist actually wants to do this.
> 
> Cant think of a clean way to counter this. If this is isnt already against the rules and likely to be a problem then this probably shouldnt get merged.

It's not really against the rules (unless you're that one person spamming it every single round) and it's definetely going to be abused. Best thing you can do is make the organs melt when the xeno dies because a flaw in their new genetics floods them with potent acid when they die or whatever. It has to be balanced, not explainable

2024-07-07 22:11 UTC, optimumtact commented
> There should be a way to make the xeno not-sterlie. Clearly it should be an emag_act.

Stop trolling

2024-07-08 00:28 UTC, Iamgoofball commented
@optimumtact anomaly core

2024-07-08 00:55 UTC, LSommers commented
I mean, if you gave it a variant organ to solve _one_ issue, you could always like.
Just.
Do it again? In a way that makes anyone trying to organ harvest cry when they realize all the organs are actually terrible and the RD is now going to beat them to death for killing their specimen?

2024-07-08 20:39 UTC, Lufferly commented
Alien acid glands now release acid and destroy the internal organs of the holding mob, on all xenos (not just bought ones). How the crew is supposed to harvest the queens organs now is left as an exercise for the reader.

2024-07-08 21:03 UTC, norsvenska commented
and so the domestication of the xenomorph begins

2024-07-13 08:05 UTC, shellspeed1 commented
Not sure I'm a big fan. This PR is massively affecting how a crew can respond to xenomorph infestations (Using hive nodes typically to see if any are still alive). This can make it very difficult for crews to catch xenomorphs that are out on the prowl  in order to figure out where a hive might be and monitor for the existence of further xenomorphs.

Another point, this is effectively an antag that can be purchased by anyone looking to cause grief or a distraction for 10k. All you need to get the xenomorph once you have the crate is a monkey which can be done with relative ease. There isn't even really a chance of the xenomorph turning on you as you can just walk away and let it do its thing. Boom, that is an antag with vent crawl that can and will do stuff like destroying the ore silo, telecomms, and becoming the entire focus of the security department until people get used to it in which case it makes actual xenomorph hives absolute round enders.

The last issue I have with this PR is that its not going to exactly add the tension that it is advertising as the experiments focus on larval xenos (Huggers and embryos) instead of fully grown ones. There is zero containment risk here as you can once again just let a monkey get infected and just rip it out. If you want an actual containment risk, you should aim for xenomorphs that are more evolved for the scans.

On one last tidbit, 99% of the work for xenomorph containment is already done for you in xenobiology. This isn't exactly hard to do if you aren't eating crayons like the marines normally sent to deal with these issues.

2024-07-16 23:42 UTC, ATH1909 commented
> Alien acid glands now release acid and destroy the internal organs of the holding mob on death, on all xenos (not just bought ones). How the crew is supposed to harvest the queens organs now is left as an exercise for the reader.

Not a fan of this happening for all xenos, I liked being able to borg them and create human-queen hybrids.

2024-07-21 19:57 UTC, Addust commented
imo:
- organ melt should only apply to neutered xenos (dna fuckery and what have you) instead of wild ones so if you kill an actual queen you get to do organ fuckery
- the hive node should be a domestic hive node that communicates on a different channel so people cant just instantly meta "ooga unga xeno base in viro" every time

2024-08-12 12:07 UTC, Exester509 commented
> imo:
> 
> * organ melt should only apply to neutered xenos (dna fuckery and what have you) instead of wild ones so if you kill an actual queen you get to do organ fuckery
> * the hive node should be a domestic hive node that communicates on a different channel so people cant just instantly meta "ooga unga xeno base in viro" every time

Agreed. Melting actual antag xeno organs isn't a good thing because to get them a xeno infestation has to roll, you gotta kill a xeno, and then harvest its organs. It's a much less controlled environment than xenobio being observed by five scientists and a secoff with a laser.

2024-08-21 14:48 UTC, Jacquerel requested changes
Code notes are mostly just nitpicks. Sorry this has been sat so long without any attention.

I am a _little_ wary of this idea but willing to give it a go, but there are some things I would like change or reassurance on first:

Firstly, I think melting all xeno organs including from other xenos is a little sad, getting random people implanted with xeno organs is fun and would be a shame to lose.
I understand the concern about people using this to farm xeno organs, but (correct me if I am wrong) I think that would usually be _mostly_ fine when they can't lay eggs? 
Alternately go with someone else's suggestion and give them a full variant organ set I guess.

Secondly, just to be sure... is it clear to a player being offered this role that they are being offered the role of a xenomorph guinea pig which cannot lay eggs? It's not going to trick people into thinking they're going to get to play as a real xeno right?
To be honest it might even be better to have these facehuggers produce NPC xenomorphs but it depends if people actually enjoy "captive alien" RP more than I think they do.

Thirdly, maybe the one you might dislike most... I don't love that this is a queen and the side effects of it being a queen hurting an actual hive in the round. I don't know if this would ruin the fun for you but making it so that this larvae can only become a sentinel or hunter might fix some issues and still be neat for R&D players. I also suspect (though no promises) that admins are much more likely to be forgiving of people letting their alien puppy out of its cage to see what happens if it's a sentinel rather than a queen.

2024-08-21 14:48 UTC, Jacquerel commented on code/game/objects/structures/aliens.dm
> +			child.sterile = TRUE
Can just do 
```suggestion
		child.sterile = sterile
```

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/alien.dm
> +		new_xeno.infertile = TRUE
```suggestion
	new_xeno.infertile = infertile
```

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/adult/caste/praetorian.dm
> +		new_queen.organs += new_eggsac
Does `Insert` not add it to this list automatically?

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/organs.dm
> +		organ.Remove(owner)
Can organs have item flags which make them acidproof? Might be worth checking against those (and then applying them to this organ so you can skip the src check)

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/special/alien_embryo.dm
> +		new_xeno.infertile = TRUE
```suggestion
	new_xeno.infertile = genetically_modified
```

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/special/facehugger.dm
> +				embryo.genetically_modified = TRUE
```suggestion
			embryo.genetically_modified = TRUE
```

2024-08-21 14:48 UTC, Jacquerel commented on code/modules/mob/living/carbon/alien/organs.dm
> +		organ.Remove(owner)
Also TBH I think being able to remove xeno organs from most xenos is like... intentional.

2024-08-29 03:39 UTC, Lufferly commented
I dont got time for this rn, someone can pick it up or I may come back to it later

2024-08-29 03:39 UTC, closed without merging