Using a multitool inhand tells you where the area APC is
tgstation/tgstation pull request #84738
Opened 2024-07-07 09:52 UTC by carlarctg

## About The Pull Request

Using a multitool inhand tells you where the area APC is

## Why It's Good For The Game

Sometimes it's a bit of a pain to find it. No need to keep it sikret when map knowledge is a thing.

## Changelog

:cl:
qol: Using a multitool inhand tells you where the area APC is
/:cl:

2024-07-07 14:58 UTC, ZephyrTFA requested changes

2024-07-08 19:58 UTC, ZephyrTFA approved these changes

2024-07-08 20:08 UTC, Ghommie requested changes

2024-07-08 20:08 UTC, Ghommie commented on code/game/objects/items/devices/multitool.dm
> +	COOLDOWN_DECLARE(next_apc_scan)
Document these vars (and perhaps the others too.

2024-07-08 20:14 UTC, merged