Fixes welding helmet and hardhat pepperspray protection
tgstation/tgstation pull request #84742
Opened 2024-07-07 14:07 UTC by JackEnoff

## About The Pull Request

Welding helmet/hardhat will now properly protect against pepperspray while its down

## Why It's Good For The Game

Fixes uhhh... apparently the guy that made the issue report got gitbanned or something?? Idk man, but it fixes that issue where welding helmets and hardhats protected against pepperspray while up and didnt while down.

## Changelog

:cl:
fix: Welding helmet and hardhat will now properly protect against pepperspray while its down
/:cl:

2024-07-07 17:00 UTC, MrMelbert requested changes

2024-07-07 17:00 UTC, MrMelbert commented on code/modules/clothing/head/hardhat.dm
> +	visor_vars_to_toggle = VISOR_FLASHPROTECT | VISOR_TINT | PEPPERPROOF
You definitely can't use the same `PEPPERPROOF` flag in `visor_vars_to_toggle`, you would need to define a new `VISOR_PEPPERPROTECT`

2024-07-07 17:01 UTC, MrMelbert commented on code/modules/clothing/clothing.dm
> +	var/pepper_protect = FALSE //Toggles pepper protection when an item is ajusted up/down
You also shouldn't *need* a whole var for this, when a visor toggles it uses `^=`, which literally toggles the bit on or off

2024-07-07 17:06 UTC, MrMelbert requested changes
Actually, looking at it again, none of the code changes should be necessary, all you must do is move `PEPPERPROOF` from `visor_flags_cover` to `flags_cover`

The bug seems to be that the flags are reversed mistakenly

2024-07-07 18:59 UTC, JackEnoff commented
> Actually, looking at it again, none of the code changes should be necessary, all you must do is move `PEPPERPROOF` from `visor_flags_cover` to `flags_cover`
> 
> The bug seems to be that the flags are reversed mistakenly

This actually was one of the first things I tried in hopes that it fixed it, but it broke them even further, either making the welding helmet never pepperproof and the hardhat always pepperproof, or straight up making them pepperproof always. I assume `flags_cover` straight up doesnt like when its toggled and `visors_flags_cover` doesnt actually work for visors as intended.

2024-07-08 14:23 UTC, JackEnoff commented
ok apparently applying `PEPPERPROOF` to `flags_cover` fixed it now? im genuinely going mental... I should probably not work on stuff at like 8 in the morning...

2024-07-08 17:10 UTC, MrMelbert approved these changes

2024-07-08 20:09 UTC, merged