Fixes mod paint kit
tgstation/tgstation pull request #84835
Opened 2024-07-09 19:31 UTC by GPeckman

## About The Pull Request

After all the attack chain refactors, the modsuit paint kit was bugged. If you tried to use it on a modsuit that had storage installed, then the paint kit would simply be inserted into the modsuit instead of allowing you to change the skin/color.

Fixes #84620 
Fixes #84490 
## Changelog
:cl:
fix: The modsuit paint kit is no longer broken.
/:cl:

2024-07-09 20:08 UTC, MrMelbert approved these changes
This fix is OK but we should still find a better solution to this at some point

2024-07-09 20:34 UTC, GPeckman commented
I'm curious what a better solution would look like? The docs for `tool_act` list overriding the target's storage as one of the actual use cases for the proc

2024-07-09 21:08 UTC, MrMelbert commented
One does not exist at the moment which is why I said we should find one

2024-07-11 00:21 UTC, Ghommie requested changes

2024-07-11 00:21 UTC, Ghommie commented on code/modules/mod/mod_control.dm
> +				return ITEM_INTERACT_BLOCKING
```suggestion
```

2024-07-11 00:21 UTC, Ghommie commented on code/modules/mod/mod_control.dm
> +				return ITEM_INTERACT_BLOCKING
```suggestion
		if(active || activating)
			balloon_alert(user, "suit is active!")
			return ITEM_INTERACT_BLOCKING
		if(LAZYACCESS(modifiers, RIGHT_CLICK)) // Right click
```

2024-07-11 16:00 UTC, merged