Fix Tongue Based Speech Modifiers Being Applied To Users Native Languages
tgstation/tgstation pull request #84952
Opened 2024-07-14 01:32 UTC by FearfulFurnishing

## About The Pull Request
This change allows tongue based speech modifications to be ignored if the user is speaking in a native language or using hand signs, putting it back to where it was functionally before moving to speechmod components.

## Why It's Good For The Game
This is correcting some of the speaking code to how it was working prior to speechmods, meaning lizard people won't be elongating there s's in draconic. Fly people are the other species with a tongue based speech modifier and receive the same fix. This also corrects  tongue based speech mods getting applied to sign language. Speech modifiers are still applied if the user is talking in a non-native language, same as it was pre speechmod.

Before:
![speechmod_demo_before](https://github.com/user-attachments/assets/86d9bca0-2d1d-44fe-8448-b8aebde8957e)
After:
![speechmod_demo_after](https://github.com/user-attachments/assets/9f071df5-0a60-4898-9aae-e8b8edd0db9e)

## Changelog

:cl:
fix: fixing speech modifiers being applied to a tongue's native languages.
/:cl:

2024-07-14 01:54 UTC, MrMelbert commented
This should probably have a unit test

2024-07-14 02:30 UTC, SmArtKar requested changes

2024-07-14 02:30 UTC, SmArtKar commented on code/datums/components/speechmod.dm
> +	var/datum/callback/should_modify_speech
You should null this on destroy, else you get a hanging ref

2024-07-14 17:35 UTC, FearfulFurnishing commented
> This should probably have a unit test

Test case added now

2024-07-15 01:30 UTC, Ghommie approved these changes

2024-07-15 01:30 UTC, Ghommie commented on code/datums/components/speechmod.dm
> +	if(!isnull(should_modify_speech) && !should_modify_speech?.Invoke(source, speech_args))
```suggestion
	if(!isnull(should_modify_speech) && !should_modify_speech.Invoke(source, speech_args))
```
should_modify_speech being null has already been checked earlier in the same conditional.

2024-07-15 02:33 UTC, merged