Special radio channels now use bitflags instead of individual vars
tgstation/tgstation pull request #85150
Opened 2024-07-20 23:35 UTC by Rhials

## About The Pull Request

Radios/encryption keys now use a `RADIO_SPECIAL_XXXXX` bitflag for behaviors related to "special" radio channels (Binary, Centcom, Syndie).

I decided to do this because I wanted to add a radio channel for pirates and hunters (hence the branch name), but it felt weird adding two more variables. The more I look at the changes I've made here the more I realize that the effort was probably not worth the utility but whatever.

This also subtypes some varedited intercoms and makes them their own objects.

## Why It's Good For The Game

Compresses a whopping three (3!) variables into a single one. Easier to scale (I guess?). I felt like adding a fourth/fifth variable and just moving on with the original project, but decided "lets do this the unnecessarily hard way instead".

## Changelog

:cl: Rhials
code: Radios/encryption keys now use a single variable for "special" frequencies. Please report if you experience any strangeness with accessing/being unable to access the Centcom, Syndicate, or Cyborg radio.
/:cl:

2024-07-24 03:45 UTC, Rhials commented
Well, it looks like it's passing the unit tests. I'd like an extra careful review of my last commit because I feel like I've messed up my understanding of bitwise operators somewhere in here.

2024-07-31 16:57 UTC, AnturK requested changes
A few operator errors

2024-07-31 16:57 UTC, AnturK commented on code/game/objects/items/devices/radio/radio.dm
> +	special_channels &= RADIO_SPECIAL_SYNDIE
|=

2024-07-31 16:57 UTC, AnturK commented on code/game/objects/items/devices/radio/radio.dm
> +	if(is_within_radio_jammer_range(src) && special_channels & RADIO_SPECIAL_SYNDIE)
Missing !

2024-07-31 16:57 UTC, AnturK commented on code/modules/admin/verbs/borgpanel.dm
> +					borg.radio.keyslot.special_channels &= RADIO_SPECIAL_SYNDIE
|=

2024-07-31 16:57 UTC, AnturK commented on code/modules/admin/verbs/borgpanel.dm
> +					borg.radio.keyslot.special_channels &= RADIO_SPECIAL_CENTCOM
|=

2024-07-31 16:57 UTC, AnturK commented on code/modules/capture_the_flag/ctf_classes.dm
> +		headset.special_channels &= RADIO_SPECIAL_CENTCOM
|=

2024-08-18 21:01 UTC, Ghommie requested changes

2024-08-18 21:01 UTC, Ghommie commented on code/modules/pai/say.dm
> +	return FALSE
```suggestion
	return (radio?.special_channels & RADIO_SPECIAL_BINARY)
```

2024-08-18 21:23 UTC, merged