soap for maints drones!
tgstation/tgstation pull request #85243
Opened 2024-07-25 10:50 UTC by deathrobotpunch

## About The Pull Request

adds soap to maint drones' internal storage

## Why It's Good For The Game
eliminates the hell that is no soap spawning on station meaning you are unable to clean at all.

## Changelog

:cl:

qol: drones now have soap in their internal storage!
/:cl:

2024-07-25 15:47 UTC, norsvenska commented
what happens when the soap runs out

2024-07-26 00:05 UTC, Loafin34 commented
inf soap in chemistry

2024-07-26 00:14 UTC, deathrobotpunch commented
> what happens when the soap runs out
> 
> also you should add it to the populatecontents

I didn’t think of that lol, I’ll update it

2024-07-26 00:26 UTC, deathrobotpunch commented
Ok I gave them the cyborg soap module which shouldn’t run out and added it to populate contents

2024-07-26 00:52 UTC, deathrobotpunch commented
turns out I did an oopsie and made a blank populate item var

2024-07-26 05:03 UTC, deathrobotpunch commented
turns out that cyborg soap had a limited amount of uses and had to be restocked by a charger. so I created a soap for drones specifically.

this version has a stupidly large amount of uses so you shouldn’t run out of it.

though I changed the wash speed to be on par with syndie soap (0.5 seconds), if any maints have an issue with it I’m willing to change it.

2024-07-28 19:47 UTC, Time-Green requested changes
Small remarks. Also dronemaid powercreep strikes again

2024-07-28 19:47 UTC, Time-Green commented on code/game/objects/items/clown_items.dm
> +	uses = 999999999 //turns out cyborg soap has limited uses so I summon stupidly large number
```suggestion
	uses = INFINITY
```

2024-07-28 19:47 UTC, Time-Green commented on code/modules/mob/living/basic/drone/drone_tools.dm
> -	builtintools += new /obj/item/analyzer(src)
Analyzer removal intended?

2024-07-29 00:21 UTC, deathrobotpunch commented on code/modules/mob/living/basic/drone/drone_tools.dm
> -	builtintools += new /obj/item/analyzer(src)
nope, readded it

2024-07-29 00:24 UTC, deathrobotpunch commented
> Small remarks. Also dronemaid powercreep strikes again

changes made!

2024-07-29 05:01 UTC, merged