You can sell stuff on the blackmarket now.
tgstation/tgstation pull request #85464
Opened 2024-07-31 18:23 UTC by Ghommie

## About The Pull Request
The idea came up during the last blackmarket-related PR (#85066), when the original creator @TheChosenEvilOne said the LTSRBT was supposed to allow players to sell stuff on the blackmarket. I replied saying it has some potential, and some other github users followed, also saying it's a good idea.

So, here we are, adding another feature to the LTSRBT, to let you sell (and fool) other players by selling potentially knock-offs and fraudulent (or genuinely honest) items on the blackmarket.

How you do it is fairly simple: left click the machine to open it, place the item inside, then right-click to open the UI. From there you can adjust the name, description and price of the market item. Finally, click on the "Place on Market" button twice, pay a 30 credits fee, and it's done. You have an item on the market, and once it's sold, 85% or the earnings (the price) will be sent to your account.

By the by, the icon of the item you're trying to sell will also show up on the market. You should get a picture of what you're getting before falling for an obvious scam.

## Why It's Good For The Game
This fits the design of the LTSRBT and blackmarket in general. Screenshoot coming soon.

## Changelog

:cl:
add: You can sell items on the blackmarket with the LTSRBT now.
/:cl:

2024-07-31 21:07 UTC, Paxilmaniac commented
its peak

2024-08-01 02:02 UTC, jlsnow301 requested changes
> .jsx

2024-08-01 02:02 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/LTSRBT.jsx
> +  const { act, data } = useBackend();
please destructure `data` after this line rather than using `data.*`

2024-08-01 05:08 UTC, Dawnseer commented
Time to get a new hobby as a cargo tech

2024-08-01 07:13 UTC, Ghommie commented
> step 1 ian (uncontained) step 2 99999999cr step 3 ian contained (forever)

you cannot sell things containing mobs (pai, mob holders, bluespace body bags with people, soulshard), because of some complications with sending mobs to nullspace. and there's a cap of 9999 credits by the by,

2024-08-01 16:56 UTC, CCC23 commented
SELLING NUKE DISK 20 CR buy today

2024-08-02 00:24 UTC, deathrobotpunch commented
> SELLING NUKE DISK 20 CR buy today

I think sending the nuke disk to null space resets it

2024-08-03 15:59 UTC, moocowswag commented
> > SELLING NUKE DISK 20 CR buy today
> 
> I think sending the nuke disk to null space resets it

Can someone still buy it on black market ui? does it dupe / move the item again?

2024-08-03 20:06 UTC, jlsnow301 approved these changes

2024-08-04 02:35 UTC, ArcaneMusic commented
I'm going to spend a minute to go through this for balance purposes before merge if that's alright, just clearing up some wallening stuff at the second.

2024-08-04 08:41 UTC, Ghommie commented
> > > SELLING NUKE DISK 20 CR buy today
> > 
> > 
> > I think sending the nuke disk to null space resets it
> 
> Can someone still buy it on black market ui? does it dupe / move the item again?

Nope. If the item cannot be contained by the machine or is deleted orgoes back on the station when we try to sell it, it won't appear in the market ui at all.

2024-08-05 17:08 UTC, CCC23 commented
selling totalyl real diskie 2000 cr buy now please trust me guys its real

2024-08-06 07:10 UTC, shellspeed1 commented
Any chance this can be setup to sell multiple items for the sake of packing large amounts of drugs or meds into it?

2024-08-06 08:07 UTC, Dawnseer commented
> Any chance this can be setup to sell multiple items for the sake of packing large amounts of drugs or meds into it?

Wouldn't you be able to do this just by selling a box full of the stuff you want to sell? Let the customers decide if they're willing to take the risk of an empty box. Or that they have to pay the price for the full package.

2024-08-10 05:43 UTC, billiumbillious commented
is there a way to give additional pictures of the thing your selling?  imo it'd be quite convenient for selling stuff in boxes

2024-08-16 01:04 UTC, ArcaneMusic requested changes
Two small things, otherwise looks good

2024-08-16 01:04 UTC, ArcaneMusic commented on code/modules/cargo/markets/market_telepad.dm
> +			user.put_in_hands(change)
In testing, this seems to produce a 1 holocredit chip when trying to restock the market with no-holocredit money sources. Tested via c10000 bills on the machine as well as with smaller bills.

2024-08-16 14:15 UTC, ArcaneMusic approved these changes

2024-08-16 16:47 UTC, merged

2025-02-26 01:02 UTC, Thommi2191 approved these changes