new aquarium ui and few new additions
tgstation/tgstation pull request #85627
Opened 2024-08-05 10:11 UTC by Ben10Omintrix

## About The Pull Request

 gives the aquarium a new ui:
![image](https://github.com/user-attachments/assets/e00b16dd-e457-4742-95c3-c68dfeac9bc5)
u can now also pet and nickname ur fish  through this interface. petting them will have them do a small dance and increase their happiness 
![image](https://github.com/user-attachments/assets/150528f0-befc-47ea-8dbc-01052bfb702d)

the hearts indicate how happy the fish is with the tank's living conditions and if theyve been petted recently.

## Why It's Good For The Game

 gives aquariums a better UI making it easier to use

## Changelog

:cl:
qol: gives aquariums a new easier to use UI
/:cl:

2024-08-05 10:53 UTC, AnturK commented on code/modules/fishing/aquarium/aquarium.dm
> +			fish.name = chosen_name
Needs sanitizing

2024-08-07 05:04 UTC, deathrobotpunch commented
I love petting fishies

2024-08-07 10:48 UTC, Ghommie commented
Nice. I think you should make happiness affect the anger mechanic of chasm chrabs / lobstrosities if possible.

2024-08-12 06:17 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/Aquarium.tsx
> +type fish_data = {
types are pascal case

2024-08-12 06:17 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/Aquarium.tsx
> +type prop_data = {
same

2024-08-12 06:17 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/Aquarium.tsx
>  export const Aquarium = (props) => {
this component is massive, and should be broken up into more parts. components are ideally 30-100 lines each, and files are no larger than 500

2024-09-04 03:51 UTC, jlsnow301 requested changes

2024-09-04 03:51 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/Aquarium.tsx
> +type fishData = {
```suggestion
type FishData = {
```
pascal case for types

2024-09-04 03:51 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/Aquarium.tsx
> +type propData = {
same here

2024-09-04 13:44 UTC, merged

2024-09-04 16:28 UTC, jlsnow301 commented
@Ben10Omintrix in your most recent commit [335bd55],(https://github.com/tgstation/tgstation/pull/85627/commits/335bd55011b4912479b43359b74cdeb53be297d4) you also pascal cased the list name incoming from dm, but this is not reflected in the typescript side. you are instead sending two duplicate lists,  fishData & FishData (same with props) and expecting only the former.

with my ask for pascal casing the type - that's just the type, not the actual var name on either side. thus, this change was not needed and should just be `fishData` and `propData`

see the code here:
https://github.com/tgstation/tgstation/blob/master/code/modules/fishing/aquarium/aquarium.dm#L313-L328

2024-09-04 17:58 UTC, Ben10Omintrix commented
> @Ben10Omintrix in your most recent commit [335bd55](https://github.com/tgstation/tgstation/pull/85627/commits/335bd55011b4912479b43359b74cdeb53be297d4) you also pascal cased the list name incoming from dm, but this is not reflected in the typescript side. you are instead sending two duplicate lists,  fishData & FishData (same with props) and expecting only the former.
> 
> 
> 
> with my ask for pascal casing the type - that's just the type, not the actual var name on either side. thus, this change was not needed and should just be `fishData` and `propData`
> 
> 
> 
> see the code here:
> 
> https://github.com/tgstation/tgstation/blob/master/code/modules/fishing/aquarium/aquarium.dm#L313-L328
> 
> 

whoops

2024-09-04 18:57 UTC, Ben10Omintrix commented
> @Ben10Omintrix in your most recent commit [335bd55](https://github.com/tgstation/tgstation/pull/85627/commits/335bd55011b4912479b43359b74cdeb53be297d4) you also pascal cased the list name incoming from dm, but this is not reflected in the typescript side. you are instead sending two duplicate lists, fishData & FishData (same with props) and expecting only the former.
> 
> with my ask for pascal casing the type - that's just the type, not the actual var name on either side. thus, this change was not needed and should just be `fishData` and `propData`
> 
> see the code here: https://github.com/tgstation/tgstation/blob/master/code/modules/fishing/aquarium/aquarium.dm#L313-L328

its all fixed now