portable gravity machine
tgstation/tgstation pull request #85694
Opened 2024-08-08 12:18 UTC by mc-oofert

## About The Pull Request

https://github.com/user-attachments/assets/98aa2177-ee0f-48d0-bbd4-83d01e688b54

it makes gravity in a radius
you may order it from cargo
may take power from wire instead
## Why It's Good For The Game

good for like space bases and stuff

## Changelog

:cl:
add: portable gravity unit, bought at cargo
/:cl:

2024-08-08 16:45 UTC, moocowswag commented
High quality af

2024-08-08 18:45 UTC, Loafin34 commented
is there a zone where there's high gravity?

2024-08-09 00:45 UTC, Dawnseer commented
Can we increase the gravity it provides? For fitness, that is.

2024-08-09 01:46 UTC, Wallemations commented
Any method we could use to visualize the field? Maybe a subtle outline or some subtle falling particles?

2024-08-09 04:23 UTC, Xackii commented
Put it somewhere roundstart please

2024-08-09 08:37 UTC, mc-oofert commented
> is there a zone where there's high gravity?

it can produce deadly gravity if emagged but it can normally produce nonlethal high gravity

also it couldve made negative grav but thats broken as fuck

2024-08-09 16:49 UTC, CCC23 commented
Finally I can make the crunchinator and obliterate anyone who walks nears bones

2024-08-09 21:57 UTC, CRITAWAKETS commented
this is really cool but a max gravity range of 12 (with full part upgrades) seems a little low for space base shenanigans to use

2024-08-10 05:51 UTC, mc-oofert commented
> this is really cool but a max gravity range of 12 (with full part upgrades) seems a little low for space base shenanigans to use

144 tiles is a lot

2024-08-11 19:44 UTC, Wallemations requested changes
> Any method we could use to visualize the field? Maybe a subtle outline or some subtle falling particles?

Should have made this part of a review, oops

2024-08-12 06:11 UTC, jlsnow301 requested changes
why did you make this lowercase?

2024-08-12 06:11 UTC, jlsnow301 commented on tgui/packages/tgui/interfaces/portagrav.tsx
> +export const portagrav = (props) => {
why is this lower case? react components, and their containing files, are pascal case

2024-08-12 16:03 UTC, Wallemations commented
> ![image](https://github.com/user-attachments/assets/7ac2d337-a24e-491e-a55f-759c9de3e3a1)
> 
> 

Not a fan tbh
I think just spawning a couple falling particles on each tile would work tbh
Either that or changing the sprite you used for this to instead be falling glowing pixels
That way they're clearly showing it's gravity through downward motion

Also, how do peacekeeper borgs make those rings around themselves? If it's code-based you could try that
Unless it's just a really big sprite lmao

2024-08-12 16:19 UTC, mc-oofert commented
> Not a fan tbh I think just spawning a couple falling particles on each tile would work tbh Either that or changing the sprite you used for this to instead be falling glowing pixels That way they're clearly showing it's gravity through downward motion Hell I'll make the sprite for you if you want me to

my ass sucks at spriting so that could do although im not so sure about the other gravity options like (disabled because broken) -1G or 0G

2024-08-12 18:27 UTC, Wallemations commented
> > Not a fan tbh I think just spawning a couple falling particles on each tile would work tbh Either that or changing the sprite you used for this to instead be falling glowing pixels That way they're clearly showing it's gravity through downward motion Hell I'll make the sprite for you if you want me to
> 
> my ass sucks at spriting so that could do although im not so sure about the other gravity options like (disabled because broken) -1G or 0G

I don't see those sprites in your icon diffs, so idk where exactly you're gonna put 'em either

I'll figure out the other options, shouldn't be too hard tbh

2024-08-13 02:20 UTC, Wallemations commented
Alright I made some border sprites and am working on some particles, what's your discord so I can shuffle those files to you?

2024-08-13 07:42 UTC, mc-oofert commented
> Alright I made some border sprites and am working on some particles, what's your discord so I can shuffle those files to you?

actuallyjimmyl, youll have to send a friend request because im permad

2024-08-13 19:54 UTC, mc-oofert commented
https://github.com/user-attachments/assets/e54707c8-4eaa-42b4-8980-df43527a7f4c

2024-08-13 22:34 UTC, Wallemations approved these changes

2024-08-15 17:03 UTC, jlsnow301 approved these changes
Ui is fine

2024-08-17 14:42 UTC, Ghommie requested changes

2024-08-17 14:42 UTC, Ghommie commented on code/game/machinery/portagrav.dm
> +	if(istype(tool, /obj/item/stock_parts/power_store/cell))
early return

2024-08-17 14:43 UTC, Ghommie commented
Also, how does it work with the wallening?

2024-08-17 16:17 UTC, mc-oofert commented
> Also, how does it work with the wallening?

it probably works

2024-08-17 19:12 UTC, merged