fix drop shadows appearing in space
tgstation/tgstation pull request #85860
Opened 2024-08-15 13:09 UTC by Ben10Omintrix

## About The Pull Request

 drop shadows will no longer be appearing in space turfs

## Why It's Good For The Game

 fix drop shadows appearing in space

## Changelog

:cl:
fix: fix drop shadows appearing in space
/:cl:

2024-08-15 13:14 UTC, Ghommie requested changes

2024-08-15 16:39 UTC, Jacquerel commented
I put off implementing this in this way because I'm worried about the impact of additionally checking the moved turf of every mob on every movement, I was hoping we could come up with some sort of rendering-based solution.
That said, I know absolutely nothing about that area of our codebase or whether that's even possible.

2024-08-16 03:50 UTC, optimumtact commented
don't do it based on turfs at all, just use area/entered and have someone manually flag the areas if htey're space or not.

2024-08-16 21:34 UTC, Ben10Omintrix commented
> don't do it based on turfs at all, just use area/entered and have someone manually flag the areas if htey're space or not.

could work but one thing that worries me is having floor breaches in station areas (or building floors in space areas) in which case the shadow would incorrectly be hidden/displayed on

2024-08-16 23:05 UTC, Ghommie commented on code/__DEFINES/is_helpers.dm
> +GLOB_LIST_INIT(shadowless_turfs, typecacheof(list(
```suggestion
GLOBAL_LIST_INIT(shadowless_turfs, typecacheof(list(
```

2024-09-03 15:54 UTC, closed without merging