Captain no longer requires hours played or command experience, as they teach new players how to pick up items and put them in their backpack or pockets.
tgstation/tgstation pull request #85965
Opened 2024-08-19 01:55 UTC by Iamgoofball

## About The Pull Request

Captain no longer requires hours played or command experience, as they teach new players how to pick up items and put them in their backpack or pockets.

## Why It's Good For The Game

Captain is the best job for brand new players.
It teaches you how to pick up items.
It teaches you how to put items in your inventory, aka using items on other items.
it teaches you about the station because you can walk anywhere and people won't tell you to leave because you're the Captain.

It's basically perfect for new players. Why didn't we do this sooner?

## Changelog

:cl:
qol: Captain no longer requires hours played or command experience, as they teach new players how to pick up items and put them in their backpack or pockets.
/:cl:

2024-08-19 01:59 UTC, Astrogem2 commented
Finally, assistant+

2024-08-19 02:01 UTC, tontyGH approved these changes
The great thing about /tg/ is that they aren't afraid to push boundaries

2024-08-19 02:03 UTC, Watermelon914 requested changes
Needs at least a minimum timelock to prevent evading griefers from doing a lot of damage as cap.

2024-08-19 02:07 UTC, Iamgoofball commented
i added a 2 day timelock

2024-08-19 02:10 UTC, NotNotADev commented
2 day timelock is excessive in my opinion, but I can see arguments for it. should be merged!

2024-08-19 02:16 UTC, san7890 commented
this is overwritable in config so i don't particularly see the point of having this be edited in the codebase if it's changeable at will by a server operator, nor do i really agree with the reason for dropping the time limits below what the previous suggestion was at

2024-08-19 02:33 UTC, Metekillot commented
Do this for HoP instead! New players learning TGUI taking a really long time absolutely feeds svul because it makes people dread the access request line

2024-08-19 08:31 UTC, Sadboysuss commented
Let him cook

2024-08-21 05:05 UTC, projectkepler-ru commented
He has a good point actually, as stupid and as absurd as it sound
New player need to get accustomed to map layout, this is something you can only do by forcing the player to grueling play each and every role for that department 

I'm now actually curious if there's a way to assist new players- like some sort of tutorial function using the deathmatch mini-game that lets the player join a temporarily created area that you can learn stuff like SM, Chem, Weapon Usage/Crafting?
I don't know
but this is not necessarily a bad start

2024-08-23 16:59 UTC, Timberpoes commented
Feels like a meme or shitpost PR. I have no interest in seeing it merged, this role is advanced with authority over other players and departments and the AI not just on tgstation but on our downstreams too almost universally.

Individual server ops that feel Captain is a good new player role can configure this on a more granular level, until they recover from their wild acid trip and return it back to normal.

Whatever argument, debate or discussion prompted this PR I do not know, but it probably sucked.

2024-08-23 16:59 UTC, closed without merging

2024-08-26 06:53 UTC, Xackii commented
> Feels like a meme or shitpost PR. I have no interest in seeing it merged, this role is advanced with authority over other players and departments and the AI not just on tgstation but on our downstreams too almost universally.
> 
> Individual server ops that feel Captain is a good new player role can configure this on a more granular level, until they recover from their wild acid trip and return it back to normal.
> 
> Whatever argument, debate or discussion prompted this PR I do not know, but it probably sucked.

captain is literally role for fun