New maintenance hazard: Smokey Remains
tgstation/tgstation pull request #86016
Opened 2024-08-21 17:51 UTC by Rhials

## About The Pull Request

![tboi unlock](https://github.com/user-attachments/assets/c1cc3d10-85b1-450b-b404-1b00eeb5715b)

This implements a new rare maintenance spawn, smokey remains. Piles of bones that used to be Nanotrasen employees, still packed with whatever reagent finally did them in.

Rarely replacing a crate spawn (7/1007 chance per crate spawn if I'm doing the math right), these act as landmines for uncareful travelers in maintenance. When you get too close, one will release a cloud of a randomly generated reagents into the air (the same reagent every time, unique to the instance of remains). You can (mostly) avoid this by walking instead of running. These will "re-arm" themselves after 4-6 minutes. They're decals, so you can just sweep them away if they're a problem.

This also slightly tweaks the original iteration of this, which I used in my Smoking Room ruin. Don't worry about it.

I'm open to adjusting the rarity, cooldown, and selection of reagents if need be.

## Why It's Good For The Game

Makes maintenance a bit more spicy. Maybe dangerous, maybe beneficial, maybe it's baldium. Who knows! Better be careful just in case!

There's plenty of boring chemicals that could roll, but an interesting one could be a nice injection of uniqueness into an otherwise dull round. It's an infinite supply, but can only be dispensed infrequently (at a fixed location) and would be extremely difficult to harvest.

The rarity, combined with the variety of reagents that can be picked, make it unlikely that these will have any serious impact on a round (it's still possible, but rarely, which is good).

## Changelog

:cl: Rhials
add: Smokey remains have appeared in maintenance. Make sure to walk when near them!
/:cl:

2024-08-21 17:58 UTC, SomeoneYouProbablyKnow commented
Neat. Make sure you can't turn those into chem factories for some fucked up chemicals, or say that's an intended use case.

2024-08-21 18:02 UTC, Time-Green commented
> Neat. Make sure you can't turn those into chem factories for some fucked up chemicals, or say that's an intended use case.

Only chems in the stomach can be "recovered". The only other way is through gibbing and extracting it from the meat, which I kinda respect

2024-08-21 18:51 UTC, Rhials commented
> Neat. Make sure you can't turn those into chem factories for some fucked up chemicals, or say that's an intended use case.

It's intended, since if someone wants to go through all that effort to squeeze out a few units every couple of minutes, I'd say that's the sandbox being well-leveraged. That's also the reason for the delay.

2024-08-21 21:04 UTC, EricZilla commented
Spooky

2024-08-21 23:14 UTC, norsvenska commented
chemical warfare: maintenance pill edition

2024-08-22 07:50 UTC, Dawnseer commented
I am looking forward to stepping on one and getting dozed with adminordrazine

2024-08-22 14:10 UTC, Time-Green commented
> I am looking forward to stepping on one and getting dozed with adminordrazine

At no point in this game have random reagents ever allowed adminordrazine

2024-08-22 14:48 UTC, Terra1 commented
Romerol?

2024-08-22 15:03 UTC, Time-Green requested changes

2024-08-22 15:03 UTC, Time-Green commented on code/game/objects/effects/decals/remains.dm
> +	return picked_reagent
Please use get_random_reagent_id() instead. You can make it respect a blacklist to get the same effect (or flags or something, but blacklist is probably easiest)

2024-08-22 20:27 UTC, Dawnseer commented
> At no point in this game have random reagents ever allowed adminordrazine

Just crush my dreams why don't you

2024-08-23 03:58 UTC, DrAmazing343 commented
this that shit that killed john nanotrasen

2024-08-28 17:58 UTC, Time-Green requested changes

2024-08-28 17:58 UTC, Time-Green commented on code/game/objects/effects/decals/remains.dm
> +	that_shit_that_killed_saddam = get_random_reagent_id(blacklist = blocked_reagents)
You can just use subtypesof on the consumable and medicine typepaths
```suggestion
	var/list/blacklisted_reagents = subtypesof(/datum/reagent/medicine) + subtypesof(/datum/reagent/consumable)
	that_shit_that_killed_saddam = get_random_reagent_id(blacklist = blacklisted_reagents)
```
(you can also put it directly in the proc I don't really care)

2024-08-28 19:50 UTC, merged