Wallening Revert
tgstation/tgstation pull request #86026
Opened 2024-08-22 07:23 UTC by actioninja

# About this PR
![image](https://github.com/user-attachments/assets/64fb9f7d-c63f-4623-b69b-a2a8aee22811)

:cl:
del: soul
/:cl:

2024-08-22 20:59 UTC, atlasle commented
why is this happening?

2024-08-22 21:28 UTC, norsvenska commented
> why is this happening?

![image](https://github.com/user-attachments/assets/e2989ab4-cec5-4421-b633-0ea9db545aff)

2024-08-22 22:19 UTC, CliffracerX commented
Watching this PR with great interest.  This was the right call for the server, even if a painful one.

2024-08-23 13:59 UTC, Timonkeyn commented
the un-wallening

2024-08-25 18:09 UTC, Ghommie requested changes
Not bad! I thought this would have been a much messier process but apparently it is not.

2024-08-25 18:09 UTC, Ghommie commented on code/modules/mob/living/emote.dm
> +	animate(pixel_y = user.pixel_y - 4, time = 0.1 SECONDS)
I'd still like this to use pixel_z because of the SIDE_MAP map format.

2024-09-03 08:56 UTC, SyncIt21 commented
superseded by #86161

2024-09-03 09:18 UTC, closed without merging