Spelling Fixes
tgstation/tgstation pull request #86056
Opened 2024-08-25 00:11 UTC by klorpa

## About The Pull Request
Fixes several errors to spelling, grammar, and punctuation.

## Why It's Good For The Game
Improves readability and user experience.

## Changelog

:cl:
spellcheck: fixed a few typos
/:cl:

2024-08-25 01:36 UTC, norsvenska requested changes

2024-08-25 01:36 UTC, norsvenska commented on code/game/objects/items/defib.dm
> +/// Called whenever the paddles successful shock something
successfully

2024-09-05 13:09 UTC, Ghommie commented
Conflicts.

2024-09-05 20:59 UTC, Cyberboss approved these changes

2024-09-06 09:45 UTC, Ghommie approved these changes

2024-09-10 15:04 UTC, merged