Decouples free vending machine behavior from the 'onstation' var
tgstation/tgstation pull request #86548
Opened 2024-09-07 22:59 UTC by vinylspiders

## About The Pull Request

The `onstation` var was being used for too many things (AI brand intelligence + whether the products are free or not), and was overcomplicating the logic. 

On top of that it makes things like trying to make a vending machine that is considered offstation for purposes of the brand intelligence event but that still dispenses free goods needlessly difficult.

This PR just decouples the two behaviors and gives the 'free' behavior its own var.

As a result, the majority of the of `onstation` map varedits are no longer necessary

Tested with various edge cases, all seem working as intended:

<details><summary>arrivals (onstation, all_free_products = null / FALSE)</summary>

![dreamseeker_bkpGCsXoaN](https://github.com/user-attachments/assets/3f92a454-ac04-41f8-9235-281a0c8dd309)

</details>

<details><summary>arrivals (onstation, all_free_products = TRUE)</summary>

![dreamseeker_7Osn49NoHg](https://github.com/user-attachments/assets/374e2632-c727-44e3-aa47-f31d5db375ca)

</details>

<details><summary>spacehotel (not onstation, all_free_products = null)</summary>

![dreamseeker_dtQFNIRlxl](https://github.com/user-attachments/assets/1dc859d9-ac8d-4d38-946f-8070f1176915)

</details>

<details><summary>hauntedruins (not onstation, all_free_products = FALSE)</summary>

![dreamseeker_JLcsJCaOIK](https://github.com/user-attachments/assets/02948139-615a-477e-b0c5-f0da8d721cae)

</details>

<details><summary>silverscale shuttle (not onstation, all_free_products = TRUE)</summary>

![dreamseeker_FNgw2JILVg](https://github.com/user-attachments/assets/7deef056-e331-48e6-88a8-fdfd22d706d4)

</details>

<details><summary>labor camp (not onstation, all_free_products = FALSE)</summary>

![dreamseeker_NWT6dxYV9d](https://github.com/user-attachments/assets/ea0c3ddd-a4dd-477a-8838-ae1ddf8ad198)

</details>

## Why It's Good For The Game

Less complicated vending machines, less varedits in our maps. Less confusing code. Ability to spawn a vending machine and varedit it to be free without affecting any other systems.

## Changelog
N/A

2024-09-08 06:32 UTC, SyncIt21 commented
There conflicts with #86518 although I favor this one more

This should also fix #86514 making that PR obsolete?

2024-09-08 06:58 UTC, ZephyrTFA requested changes, later dismissed

2024-09-08 06:58 UTC, ZephyrTFA commented on code/game/objects/items/circuitboards/circuitboard.dm
>  	///determines if the circuit board originated from a vendor off station or not.
Change this comment to match

2024-09-13 11:44 UTC, merged

2024-09-17 04:19 UTC, MortoSasye commented
An oversight: the tribal vendors are no longer free due to this pr.