Self-Gorillafication Nerf
tgstation/tgstation pull request #86588
Opened 2024-09-10 05:40 UTC by IndieanaJones

## About The Pull Request

So, I buffed gorillas a while back for traitors to get more mileage out of them, and outside of needing to adjust that one wizard spell I've been overall pleased with the results. However, while I knew that Geneticists were capable of turning themselves into gorillas without the magilitis injector, I thought it came with great difficulty but hoo boy I was wrong. Turns out, its quite easy to turn yourself into a gorilla with the three roundstart genetics setups you start with, and all you need a little bit of toxin-healing chems (which don't really have a downside and can stack!) or a medibot to pull it off. People have been using this to validhunt as the newly buffed gorillas as early as 7 minutes or less into the round, which I think sucks! So I'm here to change it.

While becoming a gorilla is still possible, I've moved that nice jungle-themed goalpost back quite a bit. The changes I made are as follows:

- Genetic damage required to become a gorilla increased from 2500 to 12500 (Note that 500 damage in code is equal to 100 damage on the genetic console, so in-game you're actually aiming for 2500% genetic damage as opposed to 500%
- Chance you'll become a gorilla per second once requirements are met are reduced by half (0.25 > 0.125)
- Genetic damage done by modifying genetic makeup cut in half (100 to 250 > 50 to 75)

Ideally, this should make becoming a gorilla with roundstart utilities nigh impossible, and require effort into building more genetic machines (ideally this will take some time) in order to achieve the goal of becoming a prime simian.

## Why It's Good For The Game

It's very easy to become a gorilla right now with little to no effort and to great effect, seeing as gorillas are pretty strong now. Its also quite fast, which is something I don't think we want for a feature like this. Ideally, by increasing the values required in order to transform, we force players who want to do this to spend more time preparing and actually focusing on achieving this goal as opposed to it being handed to them with little to no effort required.

Further nerfs can and probably will be implemented if these changes prove not sufficient.

## Changelog

:cl:
balance: Made it harder to become a gorilla via genetic damage.
/:cl:

2024-09-10 06:39 UTC, Xkallubar commented
Man, I have to set up 10 genetics setups in a row, get clever and telekinesis, and spam genetic damage for a whole hour before becoming a gorilla. Now it's going to take even longer.

2024-09-10 07:21 UTC, Vect0r2 commented
The techweb changes that puts genetics tech behind xenobio & botany have made it so it's extremely hard to get a ton of genetic damage quickly.

2024-09-10 12:33 UTC, Ghommie requested changes
Just make a slightly weaker version of the gorilla for the self-gorillafication. Don't make it a total pain in the ass to get to begin with, because there's no fun in that.

2024-09-10 15:56 UTC, IndieanaJones commented
Ok, so here's the problem. There's nothing stopping you from making a bunch of genetic scanners right now to achieve gorillafication in extremely short time (every use gives 100 - 250 genetic damage, cooldown is 60 seconds per machine), they're very easy to make and you work in the department where you can get everything you need to build them. Its so easy though right now you don't even need extra to pull it off.

If we make it transform you into a weaker gorilla, we have this weird moment where there's already a weaker gorilla in the code base, but it's that much weaker that nobody would want to turn into it. So we either then make a new gorilla subtype for this one instance and have two weaker gorilla subtypes, or we varedit the resulting gorilla from gorillize() to achieve our desired results.

Thoughts?

PS. For the record, I don't think having people build a bunch of genetic consoles to pull this off is bad, considering if you're doing this, this is probably the only project you're going to pull off this shift. They already build them anyway because it makes this already short process on live even shorter and DNA consoles are cheap.

2024-09-10 16:32 UTC, BlueMemesauce commented
Currently, gorillafication is so fast that I don't think you could even research and build more DNA scanners in that time. If it was made slower, people probably would build more to speed up the process.

2024-09-10 17:39 UTC, moocowswag commented
This was already nerfed , you keep saying a geneticist can easily become a gorilla but if it was then the previous set of double nerfs that both oranges and timbertoes oversighted had failed this whole time

A long endeavor/process is not easily, 5 minutes is more than 10% of the avg round and we dont even have an avg time to become gorilla from 0 genetic damage.

2024-09-10 22:50 UTC, IndieanaJones commented
> This was already nerfed , you keep saying a geneticist can easily become a gorilla but if it was then the previous set of double nerfs that both oranges and timbertoes oversighted had failed this whole time
> 
> A long endeavor/process is not easily, 5 minutes is more than 10% of the avg round and we dont even have an avg time to become gorilla from 0 genetic damage and still needing to gather anti toxin
> 
> the 400 seconds a previous comment estimated alone is over 6 mins and thats after instability is reached
> 
> and building extra scanners, whats wrong with that? Its a further resource and research investment.

Yeah, it is incredibly easy for people to currently become gorillas and none of the previous nerfs actually stunted how quickly you could pull this off at all. I do not consider 5 - 8 minutes to be a long process in the slightest, especially considering how strong it is and how easily a crew gorilla can molleywhop most antagonists in a 1v1 with no problem at all.

I personally had no problems with creating more scanners, and ideally I'd prefer people have to build them to get a good reward with effort as opposed to nerfing the gorilla granted by genetics outright, thus giving a medicore reward for medicore effort. I'd basically be a soft removal as opposed to enforcing a good amount of effort go into a good reward.

However, that's what I'm going to do now.

2024-09-11 00:57 UTC, IndieanaJones commented
The PR has been changed entirely. Please read the new description.

2024-09-11 01:32 UTC, zoomachina commented
Hold on, are you saying it's extremely easy to become gorilla because you've seen it happen or because you did some numbers in your head and figured it is?

2024-09-11 03:27 UTC, ATH1909 commented
> EDIT: Genetics Gorilla stats:
> 
> * 180 health (from 220)
> * Melee damage 15-18 (from 25-30)
> * Obj Damage 25 (from 40)
> * Speed 0.1 (from -0.1)
> * Paralyze chance 0 (from 20)
> * No limb ripping

Don't these new stats, uh, suck? Why would a geneticist ever want to do this? You're slower than your prey and your meaty gorilla fists are... about as effective as a cleaver. Am I missing something here?

2024-09-11 04:23 UTC, IndieanaJones commented
> Hold on, are you saying it's extremely easy to become gorilla because you've seen it happen or because you did some numbers in your head and figured it is?

I've seen it and done it myself. It really isn't hard to procure some anti-toxin meds and walk between the genetic consoles netting genetic damage.

2024-09-11 05:22 UTC, excalisword commented
They also have health regeneration.

2024-09-11 05:55 UTC, Eronymun commented
There needs to be some sort of visual distinction between these weaker gorillas and the stronger kind, conveying that kind of info is good for gameplay. Maybe have the weaker gorillas be like orangutans instead of silverbacks?

2024-09-11 07:07 UTC, IndieanaJones commented
> There needs to be some sort of visual distinction between these weaker gorillas and the stronger kind, conveying that kind of info is good for gameplay. Maybe have the weaker gorillas be like orangutans instead of silverbacks?

They have different names, descriptions, and are slightly smaller (0.9x scale)

2024-09-12 03:22 UTC, IndieanaJones commented
> Do the nerfs make them identical to prebuffed gorillas? If so thats fair

The health and melee damage is lower than prebuff gorillas, along with losing paralyze chance, but object damage and movement speed is higher. I imagine speed is the big one here, as having more health or dealing slightly more damage per swing doesn't matter if you're hopelessly outpaced to begin with.

2024-09-12 04:42 UTC, Xackii commented
Why should someone spend 2 hours of a round to become a basic mob that will die from laser spam? 
Sounds like a useless mechanic that just exists

2024-09-12 04:44 UTC, IndieanaJones commented
> Why should someone spend 2 hours of a round to become a basic mob that will die from laser spam? Sounds like a useless mechanic that just exists

It takes like 5 to 8 minutes to do become a gorilla

2024-09-12 04:53 UTC, Xackii commented
> It takes like 5 to 8 minutes to become a gorilla

This is the first time I’ve heard about such a mechanic and I still don’t understand how to do it.

2024-09-13 01:29 UTC, Ravellon commented
The wiki says that it's 25% chance to become gorilla once you hit 2500 genetic damage.
The wiki is wrong. In actuality it's 0.25% and it has been this way since the beginning. I have no idea how you can become a gorilla in 5 minutes without unrealistic amount of luck.

2024-09-13 02:03 UTC, BlueMemesauce commented
> The wiki says that it's 25% chance to become gorilla once you hit 2500 genetic damage. The wiki is wrong. In actuality it's 0.25% and it has been this way since the beginning. I have no idea how you can become a gorilla in 5 minutes without unrealistic amount of luck.
> 
> Which also tells me this is not a problem that exists in the game currently, this is purely theoretical problem.

According to this calculator, it's a 52.5% chance to become a gorilla within 5 minutes

![image](https://github.com/user-attachments/assets/b57ec666-c524-40c0-9c3e-a363783296d5)
https://www.omnicalculator.com/statistics/binomial-distribution

2024-09-13 02:14 UTC, Ravellon commented
Then something else is going on because on local I had been waiting for an hour and no gorillafication

2024-09-13 03:18 UTC, Xackii commented
@IndieanaJones Maybe you should remove the randomness in getting the gorilla and make the method of getting it more interesting? Because this all sounds like a forgotten mechanic that 1/1000 people will do because they have nothing to do.

2024-09-14 14:46 UTC, ATH1909 commented
> with how they are right now gorillas are both fun and strong enough to not be just a gimmick which imo is not a bad thing considering once you turn into one you cant revert to human (and i believe you cant communicate in human language anymore), you get round removed if you die and it is pretty tedious to become one. i dont think this change is needed at all.

you don't get round-removed when you die- someone can lazarus injector you, strange reagent you, or butcher your corpse to generate a brain that can then be shoved into a human body.

2024-09-14 14:57 UTC, Ghommie requested changes

2024-09-14 14:57 UTC, Ghommie commented on code/modules/mob/living/basic/farm_animals/gorilla/gorilla.dm
> +	transform *= 0.9
```suggestion
```

2024-09-14 14:57 UTC, Ghommie commented on code/modules/mob/living/basic/farm_animals/gorilla/gorilla.dm
> +	paralyze_chance = 0
```suggestion
	paralyze_chance = 0
	current_size = 0.9
```

2024-09-14 20:29 UTC, Ghommie approved these changes

2024-09-14 20:44 UTC, merged