What you wear and on what chair you sit on can now influence fishing difficulty
tgstation/tgstation pull request #86646
Opened 2024-09-14 00:05 UTC by Ghommie

## About The Pull Request
A foreword, I had to refactor a few bits of shitcode my past self added first. For context, the "gone fishing" and "actively fishing" traits only had one source, which is the fishing challenge itself, ad there was no way to access the challenge from outside its code, outside a few weakrefs beings used as sources for the aforementioned traits (the shitcode in a nutshell). There were also a few signals that I didn't like because they were being sent to the harder-to-access challenge datum rather than the user. So I scrapped the traits for a couple signals sent to the user, then added a global list to actually access the challenge datum, and finally changed the code to accomodate the titled feature (and also to allow the challenge to recalculate their difficulty DURING the minigame phase) 

Moving on to the actual feature: I've added a component that can be added to objects on which mobs can be buckled to or items. When equipped in the right slots or buckled to, the object will adjust the difficulty of current and future fishing challenges by a certain amount (more often than not positive, but there're many exceptions) as long as the object isn't equipped or the user is unbuckled.

I've been having some fun adding component to a ton of clothes in the game as well as chairs. Way too many objects to enumerate, so I'll give you the general idea:
- each carp-themed article provides a slight positive modifier (easier)
- some (not all) doctor-related garbs provide a marginal positive modifier each (fish doctor jokes)
- floortile camo clothes have positive modifiers
- Tuxedo, laceups, gowns provide negative modifier (more difficult)
- utility garbs such as bio/bomb/rad hoods and suits are quite bad. Riot armor too.
- boxing gloves are very, very bad. Insulated gloves and haul gauntlets are also very bad, to a lesser degree.
- **tackle** gloves are good. (pun intended)
- wizard garbs are good, because wizards are good at casting. (also a pun)
- magboots slightly bad. Space suits bad.
- Blindfolds and welding protection are also bad. Gas masks marginally bad.
- Pirate attire is nice to have. (I just vibed a little on this one)
- plastic chairs are quite versatile because it can be carried around, but the mime chair is the best, followed by the ratvarian chair.
- Fishing toolboxes, analyzers and the fish catalog, all of which can be held.
- And the fishing hat, obviously (not as great as you'd think)

Some of these may be subject to change depending on what people say.

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-14 02:25 UTC, Loafin34 commented
at this rate we need a new material called fishtonium

2024-09-15 08:22 UTC, DrAmazing343 commented
mimeta too strong... in all truth I fucking adore this pr because it is the essence of what most people call soul. it is the little tiny interactions and entirely too complex system nested within a feature and all of it oozing with puns, witty irony, and a little bit of necessary practicality to play foil to both of those.

Thank you Ghommie!!

2024-09-16 13:39 UTC, ninjanomnom requested changes

2024-09-16 15:59 UTC, Loafin34 commented
can you add in a thing for the mime chair that says something like "summons a luxuriously comfortable chair. You get a feeling of piscine superiority emanating from it."

2024-09-17 22:20 UTC, ninjanomnom requested changes

2024-09-17 22:20 UTC, ninjanomnom commented on code/modules/mod/modules/modules_general.dm
>  		gloves.AddComponent(/datum/component/profound_fisher, equipped)
shouldn't it be with the other AddComponent if gloves can be null?

2024-09-17 22:31 UTC, ninjanomnom approved these changes

2024-09-17 22:33 UTC, merged