Vore victims no longer get digested instantly when you evolve
tgstation/tgstation pull request #86722
Opened 2024-09-17 08:34 UTC by SmArtKar

## About The Pull Request
Partially handles #86685
Moving all organs/contents is a pretty bad idea and I'm not sure if there's a cleaner way to do it for the first point in the issue.

## Changelog

:cl:
fix: Vore victims no longer get digested instantly when you evolve
/:cl:

2024-09-17 09:17 UTC, carlarctg commented
bro how am i supposed to get gbp when u scoop every bug

2024-09-18 12:56 UTC, ninjanomnom requested changes

2024-09-18 12:56 UTC, ninjanomnom commented on code/modules/mob/living/carbon/alien/alien.dm
> +			frying_pan.consume_thing(melting_pot.stomach_contents[1])
A runtime in consume_thing() or just a difference in organ capabilities could easily cause an infinite loop here. It's dangerous to use a while loop like this when not all the code called inside is well known ahead of time. You can use a for loop just fine, anything that doesn't move over after attempting to consume it once will just end up getting left behind like before.

2024-09-18 14:09 UTC, ninjanomnom approved these changes

2024-09-18 14:33 UTC, merged