Intentional *scream is audible again
tgstation/tgstation pull request #86782
Opened 2024-09-20 00:16 UTC by Likteer

Removed the only instance of only_forced_audio = TRUE in /tg/. The variable is still there in case someone needs it.

## About The Pull Request
The variable was introduced in https://github.com/tgstation/tgstation/pull/42216
likely to prevent spamming. 
However, all audible emotes already have a cooldown and spamming is punishable.

I discussed this change on the forums, previously assuming it was server config
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=37131
and people seemed receptive to the idea, spam being the only concern.

## Why It's Good For The Game

As silly is it may sound, I think audible emotes bring life into the game and enable more roleplay on the LRP servers.
Most people wouldn't give you the time of day, unless you somehow grab their attention.

Screaming (and previously screeching - the monkey counterpart) is the only emote that uses the variable.
It sticks out, doesn't make sense realisticly, and we have other tools in place against spamming.

## Changelog

:cl:
del: Intentional screaming has been unmuted.
/:cl:

2024-09-20 00:17 UTC, Likteer commented
Bot is right, but all my PRs are tiny 1-line changes. Please have mercy.

2024-09-20 00:23 UTC, MrMelbert commented
![image](https://github.com/user-attachments/assets/1c4a1970-39f0-4f97-ac9e-af9315e24bea)

2024-09-20 00:37 UTC, Likteer commented
@MrMelbert I see, but I simply am not experienced enough. My best guess is to just punish them for now.

2024-09-20 18:34 UTC, TheVekter commented
If this gets merged I am immediately PRing a lengthy cooldown because I'm not dealing with this getting constantly spammed the way cyborg *deathgasp was

2024-09-20 20:03 UTC, Likteer commented
@TheVekter 
This restriction is seemingly a relic from an era when emote audio had no cooldown.

I get borg *deathgasp needing extra, it's a longer, jarring sound.
I get if you'd like extra on *scream too.

But I really don't like this current barrier. It's stupid. It fucked my wife. Do away with it.

2024-09-21 04:06 UTC, TheVekter commented
> I get borg *deathgasp needing extra, it's a longer, jarring sound. I get if you'd like extra on *scream too.
> 
> But I really don't like this current barrier. It's stupid. It fucked my wife. Do away with it.

I really don't think you're going to get what you want out of this PR as much as you're just going to see idiots walking through the hall spamming it every 5 seconds because they think it's funny, but I can always just PR to increase the cooldown if we need to later.

2024-09-22 04:31 UTC, ExcessiveUseOfCobblestone commented on code/modules/mob/living/carbon/human/emote.dm
> +	cooldown = (5 SECONDS)
you want `audio_cooldown`

2024-09-22 04:35 UTC, ExcessiveUseOfCobblestone commented
> ![image](https://private-user-images.githubusercontent.com/51863163/369211931-1c4a1970-39f0-4f97-ac9e-af9315e24bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5Nzk5MDgsIm5iZiI6MTcyNjk3OTYwOCwicGF0aCI6Ii81MTg2MzE2My8zNjkyMTE5MzEtMWM0YTE5NzAtMzlmMC00Zjk3LWFjOWUtYWY5MzE1ZTI0YmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA0MzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYzM3ZjllYmUyYjg1YzBhZjYzNGU0MzBmMGNkOGI3NjI1ZjI2Mjc0OGUxNTU1OTY1OWFiODYxYTNkOWNlZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qm9VxG_7m_YkxELTHmGYz5hUQXJxek69zRtreCvbbaQ)

what if we just make the audio cooldown not type-specific so any emote-based sound shares a cooldown with all other emote-based sound?

https://github.com/tgstation/tgstation/blob/7b5dfc514f5d0f4305efe6b8635e23a09dbde8f9/code/datums/emotes.dm#L103-L104

2024-09-22 04:37 UTC, ExcessiveUseOfCobblestone requested changes
my review

2024-09-22 15:15 UTC, Likteer commented on code/modules/mob/living/carbon/human/emote.dm
> +	cooldown = (5 SECONDS)
Sir yessir

2024-09-22 16:12 UTC, Ghommie commented
I'm merging on the basis that the restriction was dictated in a time when the `audio_cooldown` variable didn't exist so we couldn't have easily had a less restrictive countermeasure to it.

2024-09-22 16:13 UTC, merged