Polished Syndicate Teleporter effects
tgstation/tgstation pull request #86807
Opened 2024-09-21 00:25 UTC by carlarctg

## About The Pull Request

Altered the blood loss on teleportation. Instead of silently always losing ten blood, you now lose ~forty 25% of the time, fitting in with the teleporter's random design. In practice this usually evens out, but the immediate side-effects when it does happen will be much more noticeable. The rest of the time you'll still lose a tiny bit.

Improved the visible effects when using the teleporter. On teleporting, it causes a tiny blood red wave at the destination, which is slightly larger and more vibrant red if you lose blood. Telefragging someone now throws them a random turf away alongside the stun.

Fixed NOBLOOD check missing from non-emergency teleport bloodloss.

## Why It's Good For The Game

> Altered the blood loss on teleportation. Instead of silently always losing ten blood, you now lose ~forty 25% of the time, fitting in with the teleporter's random design. In practice this usually evens out, but the immediate side-effects when it does happen will be much more noticeable. The rest of the time you'll still lose a tiny bit.

The design of the teleporter is basically gambling your life away in exchange for a powerful escape/entry device. I think it's a lot more fitting if the blood lost is more random with this in mind - you could use up all the charges without any real damage, or you could suddenly lose 80 blood and need to regain your juice before using it again. In the end the blood cost is the same, but this way it'll be more immediately impactful when it does happen.

> Improved the visible effects when using the teleporter. On teleporting, it causes a tiny blood red wave at the destination, which is slightly larger and more vibrant red if you lose blood. Telefragging someone now throws them a random turf away alongside the stun.

Basically just visual polish that I think looks cool. The throwing is becaue the effect's kinda lame.

## Changelog

:cl:
add: Altered the blood loss on teleportation. Instead of silently always losing ten blood, you now lose ~forty 25% of the time, fitting in with the teleporter's random design. In practice this usually evens out, but the immediate side-effects when it does happen will be much more noticeable. The rest of the time you'll still lose a tiny bit.

qol: Improved the visible effects when using the teleporter. On teleporting, it causes a tiny blood red wave at the destination, which is slightly larger and more vibrant red if you lose blood. Telefragging someone now throws them a random turf away alongside the stun.

fix: Fixed NOBLOOD check missing from non-emergency teleport bloodloss.
/:cl:

2024-09-21 00:30 UTC, EnterTheJake commented
Eeeeeeh, not sure about this one chief, experi-teleporter is already fairly dependant on RNG, one bad roll can get you gibbed. losing all of your blood in a few charges kind of sucks.

2024-09-21 01:06 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +		if(blood_ejection)
Why not use the return value of `make_bloods`, and check noblood there (if noblood return false)

2024-09-21 01:57 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +/// Visual effect spawned when the bioscrambler scrambles your bio
Nice comment

2024-09-21 01:57 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +	else return FALSE
```suggestion
	return FALSE
```

2024-09-21 04:56 UTC, Ghommie commented
I agree with EnterTheJake, the syndicate teleporter is already a high-stakes item which warrants extensive knowledge of the station design, a pair of meson googles and/or anti-bloodloss reagents, if not being a boodless humanoid like plasmamen (which have their own drawbacks btw), however these are still fairly consistent dangers that you can control; being smited by RNG in 2/3 taps meanwhile not much so, and it's frankly 'bullshit' design.

2024-09-21 18:31 UTC, carlarctg commented
okay changed

now you always lose 5 blood

and lose 15 blood 25% of the time

2024-09-23 08:31 UTC, MrMelbert requested changes

2024-09-23 08:31 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +		if(blood_ejection)
```suggestion
		if(make_bloods(current_location, destination, user))
```

2024-09-23 08:31 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +		if(blood_ejection)
```suggestion
		var/blood_ejection = FALSE
		if(!HAS_TRAIT(user, TRAIT_NOBLOOD))
			blood_ejection = make_bloods(destination, emergency_destination, user)
		if(make_bloods(destination, emergency_destination, user))
```

2024-09-23 08:31 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
>  		return
```suggestion
		return FALSE
```

2024-09-23 08:31 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
>  /obj/item/syndicate_teleporter/proc/make_bloods(turf/old_location, turf/new_location, mob/living/user)
```suggestion
/obj/item/syndicate_teleporter/proc/make_bloods(turf/old_location, turf/new_location, mob/living/user)
	if(HAS_TRAIT(user, TRAIT_NOBLOOD))
		return FALSE
```

2024-09-23 08:31 UTC, MrMelbert commented on code/game/objects/items/teleportation.dm
> +		to_chat(user, span_warning("Blood visibly spurts out of your skin as [src] fails to teleport your body coherently!"))
Maybe should be a visible message?

2024-09-28 22:57 UTC, Ghommie commented
Ok, blood is no longer an issue now.

2024-09-28 22:58 UTC, merged