(bounty) you no longer need ALL parts deployed to use a modsuit (limbless welcome!)
tgstation/tgstation pull request #86825
Opened 2024-09-21 16:45 UTC by mc-oofert

## About The Pull Request

you no longer need all parts deployed to activate a modsuit
in order to use a module it needs its required part deployed, eg magnetic attachment = boots needed
passive effects from a module dont work unless the relevant parts are deployed

video todo

## Why It's Good For The Game

todo

## Changelog

:cl:
balance: you no longer need all parts deployed to activate a modsuit, you can use them limbless
/:cl:

2024-09-21 16:50 UTC, Fikou requested changes
thanks i wanted to do this for a while

2024-09-21 16:58 UTC, Fikou commented on code/modules/mod/mod_activation.dm
>  		if(do_after(wearer, activation_step_time, wearer, MOD_ACTIVATION_STEP_FLAGS, extra_checks = CALLBACK(src, PROC_REF(get_wearer)), hidden = TRUE))
this should be its own proc now and you should run it whenever someone tries to extend/retract a part of the turned on suit. also when turning on the suit the control unit should turn on first now (though when turning off the suit the control unit should still be last)

2024-09-23 02:52 UTC, DrAmazing343 commented
HOOOOLY SHIT IT'S PEAK

2024-09-24 07:09 UTC, Xackii commented
This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.

2024-09-24 09:09 UTC, mc-oofert commented
> This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.

still has balance implications

2024-09-24 12:09 UTC, Fikou commented
> This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.

this is a balance change also fuck you

2024-09-24 18:44 UTC, Xackii commented
> > This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.
> 
> this is a balance change also fuck you

In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.

2024-09-25 11:42 UTC, mc-oofert commented
> > > This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.
> > 
> > this is a balance change also fuck you
> 
> In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.

the title is a little misleading because you can use it limbless because deploying parts is now optional 
(still needed for relevant module and pressureproofing)

2024-09-25 15:23 UTC, Xackii commented
> > > > This is not a balance, this is a fix. Creator should have fixed this as soon as they started talking about this problem rather than leaving the problem open for 3 years.
> > > 
> > > 
> > > this is a balance change also fuck you
> > 
> > 
> > In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.
> 
> the title is a little misleading because you can use it limbless because deploying parts is now optional (still needed for relevant module and pressureproofing)

Yes, I like it. I don’t like that you don’t get space proof if you don’t wear all the pieces. It's a little annoying when you're forced to replace almost all of your slots with pieces of a mod. Even if the mod doesn’t give me insuls if I’m not wearing mod gloves, but the fact that it won’t give space proof if you don’t put it on completely, which forces you to completely hide your drip in order to get space proof, is probably the main reason why I’ll take eva instead mod.

2024-09-25 16:14 UTC, mc-oofert commented
> Yes, I like it. I don’t like that you don’t get space proof if you don’t wear all the pieces. It's a little annoying when you're forced to replace almost all of your slots with pieces of a mod. Even if the mod doesn’t give me insuls if I’m not wearing mod gloves, but the fact that it won’t give space proof if you don’t put it on completely, which forces you to completely hide your drip in order to get space proof, is probably the main reason why I’ll take eva instead mod.

ok you do you

2024-09-25 17:56 UTC, Xackii commented
> > Yes, I like it. I don’t like that you don’t get space proof if you don’t wear all the pieces. It's a little annoying when you're forced to replace almost all of your slots with pieces of a mod. Even if the mod doesn’t give me insuls if I’m not wearing mod gloves, but the fact that it won’t give space proof if you don’t put it on completely, which forces you to completely hide your drip in order to get space proof, is probably the main reason why I’ll take eva instead mod.
> 
> ok you do you

AAAAAAAAAAAAAA!!!!!!

2024-09-25 19:38 UTC, Fikou commented
> In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.

because it wasnt coded to, it was coded to turn off if any part retracts back into the suit

2024-09-26 03:20 UTC, Xackii commented
> > In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.
> 
> because it wasnt coded to, it was coded to turn off if any part retracts back into the suit

In that case, why wasn’t this balance mechanic written about here? 
https://github.com/tgstation/tgstation/pull/59109

2024-09-26 09:27 UTC, mc-oofert commented
> > > In that case, why doesn't mod tell you to fuck off, armless, and doesn't run away from you when you lose your arm? Unfinished.
> > 
> > because it wasnt coded to, it was coded to turn off if any part retracts back into the suit
> 
> In that case, why wasn’t this balance mechanic written about here? 
> https://github.com/tgstation/tgstation/pull/59109

I'm sorry to tell you but it seems you have no clue what you're talking about

2024-09-26 13:16 UTC, Dawnseer commented
Will this make it so that if you get your arm or leg blown off by whatever that the modsuit won't disable? Will it still cover one leg/arm Or will the still remaining arm/leg become uncovered?

2024-09-26 13:43 UTC, mc-oofert commented
> Will this make it so that if you get your arm or leg blown off by whatever that the modsuit won't disable? Will it still cover one leg/arm Or will the still remaining arm/leg become uncovered?

you cant wear gloves or boots on 1 arm yet
however if your arm gets cut off and you can no longer wear gloves that part gets retracted and modsuit will still be on

2024-10-18 05:20 UTC, mc-oofert commented
i havent seen an issue report about MODs yet

2024-10-19 14:58 UTC, Fikou commented
alright i have time to deal with this now

2024-10-23 10:48 UTC, Fikou requested changes, later dismissed
my game wont compile so this for now but more soon

2024-10-25 00:09 UTC, merged