Bring your pet to work day!
tgstation/tgstation pull request #86879
Opened 2024-09-24 19:41 UTC by Ben10Omintrix

## About The Pull Request

 Adds a new neutral station traits where people are able to bring their personal pets to show off to the rest of the crew (or to donate to the chef). Before joining, players will be able to customize their pets

https://github.com/user-attachments/assets/5a5cda18-e551-4f87-b649-67a6940ffc6a

u can set their name, gender, pet carrier color, and  teach them give them a unique dance sequence trick. if players dont wish to opt in, they also have the choice not to

## Why It's Good For The Game

adds a new station trait which people can RP around, whether its by competitively comparing pets, or resolving conflicts around pets being killed/kidnapped. Ive also GAGsified pet carriers, so people can now have the option to recolor those too

## Changelog

:cl:
add: adds a new station trait, "bring your pet to work" day
/:cl:

2024-09-24 20:15 UTC, MrMelbert commented on code/modules/mob/living/basic/pets/pet_designer.dm
> +				selected_path = pet_type
Sanity check that the passed pet type is one of the valid pets

2024-09-24 20:16 UTC, MrMelbert commented on code/__DEFINES/basic_mobs.dm
> +GLOBAL_LIST_EMPTY(customized_pets)
Needs an auto doc

2024-09-24 22:27 UTC, Admiral-Gigaton commented
"magnumopus" is the best name for a little dance trick. best PR showing of the year.

2024-09-24 22:49 UTC, DaydreamIQ commented
Humbly requesting a pet mouse as an option for all the rodent loving homies out there

2024-09-25 06:11 UTC, necromanceranne commented
In contrast to the mouse request, what about duct spiders :3

2024-09-25 06:52 UTC, Wallemations approved these changes
Cute!

2024-09-25 07:10 UTC, SomeoneYouProbablyKnow commented
1. I'd be nice to have a random option.
2. This makes it possible to bring a Corgi named Ian and replace the actual Ian with this. I think this is a very funny interaction but I am bringing attention to it still
3. Parrots, need parrots

2024-09-25 21:18 UTC, Loafin34 commented
1. exotic corgi
2. sholean grapes
3. blob spore
please

2024-09-26 03:35 UTC, krookodilehunter commented
puppies and kittens too?

2024-09-26 03:56 UTC, Y0SH1M4S73R commented
what about false carp (the ones spawned by the shuttle event)

2024-09-26 11:08 UTC, OneAsianTortoise commented
that's a dog

2024-09-26 14:40 UTC, theselfish commented
![361606158-68166997-cc4d-46a4-ac26-be2e484f4460](https://github.com/user-attachments/assets/e7558aca-5d16-47e1-acf1-7f6c51b1779b)

2024-09-27 10:55 UTC, theselfish commented
> 1. I'd be nice to have a random option.
> 
>     2. This makes it possible to bring a Corgi named Ian and replace the actual Ian with this. I think this is a very funny interaction but I am bringing attention to it still
> 
>     3. Parrots, need parrots

If someone Ship of Theseus' Ian, they deserve an award.

2024-10-01 07:00 UTC, Ben10Omintrix commented
https://github.com/user-attachments/assets/2479e33f-c82e-4e33-92ea-59fde1e667a3

ive added some new pets based on the requests from here

2024-10-01 16:50 UTC, OneAsianTortoise commented
> newpets.mp4 
> ive added some new pets based on the requests from here

where turtle

2024-10-01 17:43 UTC, Wallemations requested changes
If you want the GAGS colors to work best for the underside, remove the blue tint & make it purely white & grey. That way the color is 100% the one you pick.

2024-10-02 17:52 UTC, TheSmallBlue commented
Frog! Frog! Put frog under vermins please!!

2024-10-02 22:15 UTC, Admiral-Gigaton commented
lizard pet? crabs? penguin?

2024-10-03 18:55 UTC, Twaticus commented
how does a pet have some alternate gender lol

2024-10-03 20:58 UTC, iliyaxox commented
> how does a pet have some alternate gender lol

youll see once i bring my non binary cat to the station

2024-10-04 00:06 UTC, Loafin34 commented
cockroach please

2024-10-07 20:57 UTC, merged