Sound mixer part 1
tgstation/tgstation pull request #86932
Opened 2024-09-27 16:48 UTC by Sadboysuss

## About The Pull Request
![image](https://github.com/user-attachments/assets/77cc81da-a6f1-4f95-b362-b9783fa6896a)

## Why It's Good For The Game
gives players more control over how loud they want certain sounds to be

## Changelog

:cl: grungussuss
sound: the volume that ship ambience, ambience, radio noise and announcements play at can now be tweaked in preferences, check your preferences!
/:cl:

2024-09-27 20:27 UTC, StrangeWeirdKitten commented
Absolutely fucking based

2024-10-13 21:03 UTC, Ghommie requested changes

2024-10-13 21:03 UTC, Ghommie commented on code/modules/client/preferences/sounds.dm
> +/datum/preference/toggle/sound_ambience_volume/apply_to_client(client/client, value)
```suggestion
/datum/preference/numeric/sound_ambience_volume/apply_to_client(client/client, value)
```

2024-10-13 21:03 UTC, Ghommie commented on code/modules/client/preferences/sounds.dm
> +/datum/preference/toggle/sound_lobby_volume/apply_to_client_updated(client/client, value)
```suggestion
/datum/preference/numeric/sound_lobby_volume/apply_to_client_updated(client/client, value)
```

2024-10-13 21:03 UTC, Ghommie commented on code/modules/client/preferences/sounds.dm
> +/datum/preference/toggle/sound_ship_ambience_volume/apply_to_client_updated(client/client, value)
```suggestion
/datum/preference/numeric/sound_ship_ambience_volume/apply_to_client_updated(client/client, value)
```

2024-10-13 22:45 UTC, W4rd3nn commented
Just gonna bring this up, but could you also do a volume setting for announcements? like the "meteors have been detected" kind. they can be pretty grating but turning them off completely also causes you to miss them.

2024-10-14 22:56 UTC, closed without merging

2024-10-15 13:16 UTC, Ghommie commented
What gives?