Vendored Node checksum is now validated
tgstation/tgstation pull request #86997
Opened 2024-10-01 08:11 UTC by ZephyrTFA

Hey you. Yes you.
Have you ever experienced Access Denied when trying to compile the codebase for seemingly no reason?
Tried to fix it and gave up?
Its because Windows sucks ass and node will corrupt when you run it if closed improperly.

Well now the build scripts verify that its not corrupt!

2024-10-01 11:19 UTC, Cyberboss approved these changes

2024-10-02 20:00 UTC, ZephyrTFA commented on tools/bootstrap/node_.ps1
> +		exit
```suggestion
```

2024-10-02 21:19 UTC, Cyberboss requested changes
add `tools/bootstrap/**` to the TGS test triggers so we can validate it

2024-10-02 22:25 UTC, Cyberboss approved these changes

2024-10-02 23:16 UTC, merged