Add a separate preference for hearing AI VOX announcements
tgstation/tgstation pull request #87097
Opened 2024-10-08 02:49 UTC by Absolucy

## About The Pull Request

This adds a new preference, "Enable AI VOX announcements", which allows you to toggle hearing the vocal AI VOX announcements.

Previously this was handled by the "Enable announcement sounds" setting, but tbh having it lumped in with that sucks because it's very reasonable to be okay with announcement dings, while not wanting to hear voxtest or some shit.

## Why It's Good For The Game

I DO want to hear the normal announcement dings, but I ***never*** want to hear the vocal AI announcements, and spamming "Stop Sounds" for every single word to skip past it is annoying as hell.

## Changelog

:cl:
add: Added a separate preference for hearing vocal AI announcements (also known as VOX), as opposed to lumping it into the "Enable announcement sounds" preference.
/:cl:

2024-10-08 20:09 UTC, tontyGH requested changes
This made me realize that AI voxes iterate over players for every single word and I think that's funny

2024-10-09 08:25 UTC, ElGitificador commented
i captain comdom pr?

2024-10-15 10:18 UTC, SmArtKar commented on code/modules/mob/living/silicon/ai/ai_say.dm
> +				if(!player_mob.can_hear() || !(safe_read_pref(player_mob.client, /datum/preference/toggle/sound_ai_vox)))
You could make VOX play an announcement sound if the player has vox turned off but announcements turned on?

2024-10-15 18:00 UTC, Ghommie requested changes
I'm with SmArtKar on this.

2024-10-19 21:26 UTC, Absolucy commented on code/modules/mob/living/silicon/ai/ai_say.dm
> +				if(!player_mob.can_hear() || !(safe_read_pref(player_mob.client, /datum/preference/toggle/sound_ai_vox)))
Done! Coded it in a way where future things can also do something similar with `minor_announce` and `dispatch_announcement_to_players` without special code too.

2024-10-24 02:13 UTC, Ghommie approved these changes
The callback stuff is a little odd for some but I suppose it works. Nothing better comes to my mind.

2024-10-24 02:14 UTC, merged