Magazines now lazyload their contents in order to save on gun init times
tgstation/tgstation pull request #87224
Opened 2024-10-14 05:46 UTC by SmArtKar

## About The Pull Request
Ammo boxes, this includes magazines and magazines inside of guns, now lazyload their ammo in order to save on init times by keeping it as types in their ammo list and initializing them as needed. As a side effect, you can only use get_round to access rounds now, direct array access will probably not work.
Should be TMed first because guncode is a fuck.

## Why It's Good For The Game

trying to save on init times and delay death of guncode by a tiny bit

## Changelog

:cl:
code: Magazines now lazyload their contents in order to save on gun init times. Please report any broken/non-functional guns!
/:cl:

2024-10-14 05:51 UTC, LemonInTheDark commented
https://github.com/tgstation/dev-cycles-initiative/issues/4
also https://github.com/tgstation/dev-cycles-initiative/issues/19

2024-10-14 09:22 UTC, necromanceranne commented
Nice nice

2024-10-21 20:26 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
needs the default case of return FALSE right?

2024-10-21 20:33 UTC, LemonInTheDark requested changes

2024-10-21 20:33 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +	for (var/casing in stored_ammo)
why type other iterations but not this?

2024-10-21 20:33 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
>  /obj/item/ammo_box/magazine/proc/ammo_list()
what calls this?

2024-10-21 20:33 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
> +		if(istype(bullet) && bullet.loaded_projectile)
why not !istype in the first conditional here? two birds one stone

2024-10-21 20:33 UTC, LemonInTheDark commented on code/modules/projectiles/guns/ballistic/revolver.dm
> +	chambered = magazine.get_round(!spin_cylinder)
be explicit about args here

2024-10-21 20:33 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
> +/obj/item/ammo_box/magazine/internal/cylinder/get_round(keep = FALSE)
this seems a bit clunky, ideally we'd have two procs, one that hands back the top round and one hands back an unowned top round

2024-10-21 20:34 UTC, LemonInTheDark commented
Does this actually save time? profiled?

2024-10-22 00:54 UTC, necromanceranne commented
> Does this actually save time? profiled?

I swear didn't mothblocks already do that? I distinctly remember her talking about this as something affecting init times because of the guns at centcom

2024-10-22 01:11 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +/obj/item/ammo_box/proc/fetch_round()
get_and_rotate? name is non ideal

2024-10-22 01:12 UTC, LemonInTheDark commented on code/modules/projectiles/boxes_magazines/_box_magazine.dm
> +/obj/item/ammo_box/proc/fetch_round()
cannot come up wth a better one tho

2024-10-22 07:46 UTC, LemonInTheDark commented
we need to work out wtf is going on with revolvers here and why the proc names have to suck

2024-10-29 05:57 UTC, merged