The Supermatter Resizing: How a crystal can fit into hand
tgstation/tgstation pull request #87232
Opened 2024-10-14 22:06 UTC by MelokGleb

## About The Pull Request
adds supermatter sword craft made out of:
20 adamantium
2 vortex cores
actual sm
6 minutes of crafting
announcement on fourth minute
shrinking wand

first of all, you need to craft adamantium pedestal (2 min)
![image](https://github.com/user-attachments/assets/3a24611d-ddce-4438-9b9f-7283458b0791)

then, you should combine it with shrink wand and sm (2 min) (announcement once you craft it) (it has a gps signal)
![image2](https://github.com/user-attachments/assets/667a58d5-1b3b-49bc-a781-45f84cdaf2b7)

and the last one, small sm and 2 vortex cores (2 min) (dont forget about gps signal)
![image1](https://github.com/user-attachments/assets/ae432269-af3d-4e14-ab80-f42f558e3d46) ![image3](https://github.com/user-attachments/assets/313033f1-f375-43d3-a8d5-f7307713e69e)

## Why It's Good For The Game
wiz needs more challenges and fun
craft is very hard and challenging, but the reward is powerfull as fuck
## Changelog
:cl: MelokGleb and KREKS
add: very hard wiz-only sm sword craft
sprite: sm sword resprite
/:cl:

2024-10-15 00:02 UTC, Admiral-Gigaton commented
hey, wouldnt it make more sense for it to be a hyper noblium stand, considering its... well, an SM shard? I think I read somewhere that the SM starts out with a coating of hyper noblium while engies set it up, and hyper nob keeps SM mega stabilized when its used in it, though I guess balancing wise its hard for a wizard to get hyper noblium

2024-10-15 05:26 UTC, ZephyrTFA commented
They say a good pr only comes around once in a blue moon.

2024-10-15 05:26 UTC, ZephyrTFA approved these changes

2024-10-15 05:27 UTC, Metekillot commented
6 minutes seems a little long. Give your average greytider a crowbar and they can breach the armory in 3 minutes

2024-10-15 12:29 UTC, xKREKSx commented
Could you at least write in the PR that I drew the sprites? :eyes:

2024-10-15 14:38 UTC, Admiral-Gigaton commented
> What are the sources for adamantium btw?

mainly xenobio but I think fishing can spawn it

2024-10-15 17:15 UTC, Loafin34 commented
can it be either adamantium or metallic hydrogen?

2024-10-18 00:32 UTC, carlarctg commented
nooo hypernoblium is used for sm pedestaaals not adamantiuuum or hyydrogennn that's logically inconsistent and breaks established conventiooooonssss!!!!

2024-10-25 00:17 UTC, Ghommie approved these changes

2024-10-25 00:17 UTC, Ghommie commented on code/datums/components/crafting/structures.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:17 UTC, Ghommie commented on code/datums/components/crafting/structures.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:17 UTC, Ghommie commented on code/datums/components/crafting/melee_weapon.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:28 UTC, Ghommie requested changes
Oh, yeah, I can't make the edits if it isn't a requested change grrrrr....

2024-10-25 00:28 UTC, Ghommie commented on code/datums/components/crafting/melee_weapon.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:28 UTC, Ghommie commented on code/datums/components/crafting/structures.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:28 UTC, Ghommie commented on code/datums/components/crafting/structures.dm
> +	time = 120 SECONDS
```suggestion
	time = 2 MINUTES
```

2024-10-25 00:30 UTC, merged

2025-01-25 10:21 UTC, MoonDeer728 commented
> can it be either adamantium or metallic hydrogen?

no