Felinid mood fix
tgstation/tgstation pull request #87230
Opened 2024-10-14 15:29 UTC by mamiipolat

![resim](https://github.com/user-attachments/assets/35ce028c-0ed0-4ea2-89f3-77acc15693ac)

## About The Pull Request
Showering will add negative mood effect to felinids

## Why It's Good For The Game
there was a status effect that drops stamina for felinids on shower but at the same time it boosts mood i decided to make it better

:cl: Mamaii
add: shower will give felinids negative mood effect
/:cl:

2024-10-14 15:33 UTC, Sadboysuss commented on code/datums/mood_events/needs_events.dm
> +	timeout = 6 MINUTES
6 minutes is too much

2024-10-14 15:33 UTC, Sadboysuss commented on code/datums/mood_events/needs_events.dm
> +	mood_change = -4
-4 is too much

2024-10-14 15:36 UTC, mamiipolat commented on code/datums/mood_events/needs_events.dm
> +	timeout = 6 MINUTES
positive event was 5

2024-10-14 15:36 UTC, mamiipolat commented on code/datums/mood_events/needs_events.dm
> +	mood_change = -4
positive one was +4

2024-10-14 17:28 UTC, Striders13 commented
the status effect seems broken if you wanna fix it also

2024-10-14 18:55 UTC, ZephyrTFA commented
This should be a flag on the species datum and not a snowflake isfelinid check

2024-10-14 21:50 UTC, Ghommie requested changes
No snowflake species checks when we have equivalent traits.

2024-10-14 21:50 UTC, Ghommie commented on code/game/objects/structures/shower.dm
> +	if(!isfelinid(target))
```suggestion
	if(!HAS_TRAIT(target, TRAIT_WATER_HATER) || HAS_TRAIT(target, TRAIT_WATER_ADAPTATION))
```

2024-10-15 15:24 UTC, Ghommie approved these changes

2024-10-15 15:24 UTC, merged