Examining monster organs gives you a vague estimate of time until decay
tgstation/tgstation pull request #87266
Opened 2024-10-17 07:45 UTC by Hatterhat

(alt. title: to hold a still-beating heart)
## About The Pull Request
You can examine monster organs to ~~check their vibes~~ get a really rough estimate on how long you have to use them. The timer-related message disappears when the timer is deleted, which occurs when the organ is stabilized or when the organ decays.

![image](https://github.com/user-attachments/assets/76e9b53f-25c2-4822-b2a1-6b0504fd43ab)

## Why It's Good For The Game
sometimes you don't have a backpack full of legion cores and you need to know which ones to burn and which ones to dump, i guess?

## Changelog

:cl:
qol: Nanotrasen employees have been given a quick primer on how specialized fauna organs (brimdust sacs, rush glands, regenerative cores) look in varying states of decay corresponding to lifespan (read: you can now examine monster organs to get a vague idea of how long they have left before decaying and becoming useless).
/:cl:

2024-10-17 07:58 UTC, the-orange-cow commented
Idea: what if they just despawned when they decay completely?  If it's utterly useless, why keep it around at all.

2024-10-20 15:16 UTC, Ghommie requested changes

2024-10-20 15:16 UTC, Ghommie commented on code/modules/mining/equipment/monster_organs/monster_organ.dm
> +	if(decay_timer)
early return

2024-10-20 15:16 UTC, Ghommie commented on code/modules/mining/equipment/monster_organs/monster_organ.dm
> +			. += span_warning("Signs of decay have set in, but not totally. It's probably about to become unusable really quickly.")
Can we have a switch() statement here?

2024-10-22 22:59 UTC, merged