Ports pixelshifting from monkestation
tgstation/tgstation pull request #87376
Opened 2024-10-22 15:58 UTC by Sadboysuss

## About The Pull Request
port of https://github.com/Monkestation/Monkestation2.0/pull/2850 with some minor changes, namely V as the pixel shift keybind and shift+V as the item pixel shift keybind as the defaults.
Note: I don't think it warrants wall leaning removal as that one has other benefits like fov vision increase and cigarette fluff, plus wall leaning is faster than pixel shifting.

## Why It's Good For The Game
I think it adds a neat RP mechanic, you can lean on machines, then accidentally fall over and break it, lean into people's faces to scream at them, lean over a railing. For a sandbox roleplaying game I think it's a must.

## Changelog

:cl:
add: Living mobs can now pixel shift their character, the default keybind for this is V!
add: Living mobs can now pixel shift items they are dragging, the default keybind for this is Shift+V!
/:cl:

2024-10-22 15:58 UTC, JohnFulpWillard commented
If this gets added, it should probably replace leaning

2024-10-22 15:59 UTC, Sadboysuss commented
> If this gets added, it should probably replace leaning

>> Note: I don't think it warrants wall leaning removal as that one has other benefits like fov vision increase and cigarette fluff, plus wall leaning is faster than pixel shifting.

2024-10-22 16:01 UTC, Jacquerel commented on code/datums/keybinding/living.dm
> +	SEND_SIGNAL(user.mob, COMSIG_KB_LIVING_ITEM_PIXEL_SHIFT_DOWN)
This isn't really how we should use signals; this is just a proc call and not an event.
It also isn't clear to me why this is a component in the first place though to be honest.

2024-10-22 17:29 UTC, Hexflash24 commented
I like this, it creates many fun ways of expressing yourself,  as long as your position resets when you move around so its not abused in combat.

2024-10-22 18:07 UTC, DrAmazing343 commented
> but why is this needed

> I think it adds a neat RP mechanic, you can lean on machines, then accidentally fall over and break it, lean into people's faces to scream at them, lean over a railing. For a sandbox roleplaying game I think it's a must.

literacy is at an all time low. I am sorry for your loss.

2024-10-22 18:11 UTC, mc-oofert commented
> > but why is this needed
> 
> > I think it adds a neat RP mechanic, you can lean on machines, then accidentally fall over and break it, lean into people's faces to scream at them, lean over a railing. For a sandbox roleplaying game I think it's a must.
> 
> literacy is at an all time low. I am sorry for your loss.

i think this has no real purpose much like leaning aside from pretending to have sex on spessmans or introducing more visual bugs and if someone says that its going to be used for roleplay theyre going to be wrong in a month

2024-10-22 18:37 UTC, JupiterJaeden commented
Can Manuel truly be trusted with this? We already had an epidemic of catpeoppe kissing each other after wall leaning…. xD

2024-10-22 18:58 UTC, Sadboysuss commented
The rule 8 violations will happen regardless of if this change is merged or not, the people that do it don't do it because there is wall leaning or pixel shifting, they do it because they don't care about the rule and nothing will change that, pixel shifting or not. I think it's an administrative issue, just because some people like to ruin others' experience doesn't mean everyone should be punished for it.

2024-10-22 19:59 UTC, SomeoneYouProbablyKnow commented
Sorry but this looks ugly. Granted i think leaning looked ugly too (although to a lesser extend mostly because theres less movement) so it just might be my sensibilities.
I also don't see how it would meaningfully impact anyone. Like yes

> I think it adds a neat RP mechanic, you can lean on machines, then accidentally fall over and break it, lean into people's faces to scream at them, lean over a railing. For a sandbox roleplaying game I think it's a must.

You provided those example but... just use the M command? In most cases M works better than a wonky visual effect anyway. If you're around people who wanna read your M actions anyway. If they are not then shifting won't help either, it'd just be used as a funny fortnight dance. Look at him go.

Smoking near a plasma filled room is cool roleplay because something can come out of it. Ignoring nuckies to clean blood of the floor as jani is roleplay. Blocking 1 wide hallway with mime walls is roleplay. 

What i'm trying to say is roleplay comes out of mechanics not what's essentially a visual gag. I'll take a spessmen doing something interesting in the round over one just spinning in circles any day now.

2024-10-22 21:17 UTC, SmArtKar commented
I think we should just stick with leaning and not add pixel shifting, just need to bring component-based leaning back

2024-10-22 21:36 UTC, Rex9001 commented
I think this is really cool and great for items, but I dont think it works on mobs

2024-10-22 21:56 UTC, LemonInTheDark requested changes
I am not interested in the mob portion of this, it breaks perspective and feels janky. We have problems with lying about a mob's actual position as is and this will make that even worse. I already kinda hate leaning and this extends those problems to everywhere.

The ux for item shifting is bad, need a better way then pullin the thing. I'm not 100% if it's a good idea either because you can shift shit into walls and potentially cause conflict/visual hell. have not decided on this. also this should likely be using pixel_w/z rather then pixel_x/y, would need to test to say for sure.

2024-10-22 22:03 UTC, Sadboysuss commented
Aight, if I end up wanting to make item shifting, it will be a selerate pr

2024-10-22 22:03 UTC, closed without merging

2024-10-22 22:52 UTC, CliffracerX commented
Considering Wallening already set a precedent for shifting literally everything off-tile I think the ship has sailed with lying about a mob's position.  Better to unify lean under something entirely user-controlled & easily tweakable than let even more snowflake code come in that'll mess up the next incarnation there-of.

2024-10-22 23:11 UTC, Jacquerel commented
> Considering Wallening already set a precedent for shifting literally everything off-tile I think the ship has sailed with lying about a mob's position. Better to unify lean under something entirely user-controlled & easily tweakable than let even more snowflake code come in that'll mess up the next incarnation there-of.

When it happened during the Wallening everyone hated it and the project was withdrawn from the servers. That ship sailed, hit some rocks inside the port, and was immediately returned to drydock.

2024-10-23 02:55 UTC, LemonInTheDark commented
> Considering Wallening already set a precedent for shifting literally everything off-tile I think the ship has sailed with lying about a mob's position. Better to unify lean under something entirely user-controlled & easily tweakable than let even more snowflake code come in that'll mess up the next incarnation there-of.

shifting position up and shifting position in a random direction because fuck you are different things