Track subsystem runtimes via usr
tgstation/tgstation pull request #87448
Opened 2024-10-25 01:46 UTC by Absolucy

## About The Pull Request

This adds a dummy "subsystem tracker" mob to every subsystem - which is set to `usr` during SS preinit, init and fire. (surely this can't go wrong at all)

If `usr` is a subsystem tracker during a runtime, it'll replace `usr: blahblahblah` in the runtime text with `subsystem: SSwhatever (/datum/controller/subsystem/whatever)`

Also, this makes a `/mob/abstract` type, and repaths `/mob/oranges_ear` to `/mob/abstract/oranges_ear`, so that it can share the "technically this is mob but it's not *really* a mob" behavior with the dummy tracker mob.

blame @MrStonedOne

## Why It's Good For The Game

makes runtimes slightly easier to read

![2024-10-24 (1729820355) ~ dreamseeker](https://github.com/user-attachments/assets/251020d5-5dda-4d30-838b-3d5a3301df70)

## Changelog

... this isn't user facing at all.

2024-10-25 03:10 UTC, tgstation-server commented
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Terry

##### Merged By
Auto\mrstonedone

##### Revision
Origin: 26361ae5656fd4241634ffead9f31b7d651677b9
Pull Request: 59455f63a9b0b8c2f8a95511c5acc7e0ebc5729d
Server: 747a6fa0635313afa6f6b0f24a01e202f7288936

##### Comment
Lets test a thing
[GitHub Deployments](https://github.com/tgstation/tgstation/deployments/activity_log?environment=TGS%3A+Terry)
</details>

2024-10-25 04:02 UTC, Absolucy commented
why would you-

2024-10-25 08:30 UTC, tgstation-server commented
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Terry

##### Merged By
Auto\mrstonedone

##### Revision
Origin: cded23b51a2264d636a336bd645f4714bdb1e82e
Pull Request: 59455f63a9b0b8c2f8a95511c5acc7e0ebc5729d
Server: e03295d3beea8cfb4da573956b9377761107206c

##### Comment
Lets test a thing
</details>

2024-10-25 08:34 UTC, Thunder12345 commented
> why would you-

Guess what, Terry wouldn't restart by himself at round end after having a draft PR implanted in his brain

2024-10-25 09:06 UTC, tgstation-server commented
#### Test Merge Removed

2024-10-25 10:02 UTC, MrStonedOne commented
> why would you-

I had to test the new tgsv6 server's fancy features some how.

2024-10-25 22:17 UTC, Absolucy commented
that's fair

2024-11-03 05:54 UTC, Absolucy commented
lmao this might actually work

2024-11-05 12:26 UTC, ZephyrTFA requested changes

2024-11-05 12:26 UTC, ZephyrTFA commented on code/controllers/tracker.dm
> +/mob/abstract/subsystem_tracker/New(datum/controller/subsystem/subsystem)
```suggestion
/mob/abstract/subsystem_tracker/New(loc, datum/controller/subsystem/subsystem)
```

2024-11-05 12:26 UTC, ZephyrTFA commented on code/controllers/tracker.dm
> +	if(!istype(subsystem))
```suggestion
	if(loc != null)
		CRASH("Tried to create a subsystem tracker outside of null space!")
	if(!istype(subsystem))
```

2024-11-05 12:26 UTC, ZephyrTFA commented on code/__DEFINES/MC.dm
> +		src.tracker = new(src); \
```suggestion
		src.tracker = new(null, src); \
```

2024-11-07 06:46 UTC, Absolucy commented
i don't care enough tbh. anyone else is fully free to pick this up if they care to

2024-11-07 06:46 UTC, closed without merging