makes the ai detector tool display the vague area the AI is looking at
tgstation/tgstation pull request #87457
Opened 2024-10-25 14:49 UTC by mc-oofert

## About The Pull Request

https://github.com/user-attachments/assets/3c2b2fd4-6c82-4986-bb90-d9954d48e671

the ai detector multitool has been slightly redone and the HUD silently removed by #68301 is back
no action button, use inhand to toggle hud

**area displayed by hud does not account for camera static, i dont know how to bring this part of the feature back so any help would be appreciated**

## Why It's Good For The Game

fixes #87414
also this feature was silently removed

## Changelog

:cl:
fix: brings back the AI detector HUD that was silently removed by a PR 3 years ago
/:cl:

2024-10-25 15:23 UTC, TheVekter commented
Good change, I used to use this all the time and wonder why it wasn't fucking doing anything.

2024-11-02 13:19 UTC, Ghommie requested changes

2024-11-02 13:19 UTC, Ghommie commented on code/game/objects/items/devices/multitool.dm
> +	apc_scanner = FALSE //we want to toggle hud, not check for APC
the apc scanning function should be assigned to one of the two click procs but not both. I'd suggest setting the variable to FALSE on compile and have the action done in attack_self_secondary() instead.

2024-11-02 13:46 UTC, mc-oofert commented
i still have no clue how to bring back the "see AI static but like almost transparent" part that was removed idk how it works
as far as i can AIs just get images from camera chunks now or something

2024-11-02 14:30 UTC, mc-oofert commented
actually im about to cook hold on

2024-11-02 15:36 UTC, mc-oofert commented
https://github.com/user-attachments/assets/3583f6e6-cc53-4162-a611-5870b938d11e

new thing

2024-11-02 17:08 UTC, merged