You can now place material iron tiles in space
tgstation/tgstation pull request #87602
Opened 2024-10-31 12:30 UTC by Aliceee2ch

## About The Pull Request

After #87587 i considered that players (especially newbies) can consufe iron tile and material iron tile.

## Why It's Good For The Game

This PR removes barely noticeable difference between iron tile and material iron tile, since they use the same amount of the same material and should therefore act the same.
![image](https://github.com/user-attachments/assets/3236ab63-6086-4c4b-973f-866efeaab9d6)

## Changelog

:cl:
fix: you can now place material iron tiles in space like regular iron tiles
/:cl:

2024-10-31 12:39 UTC, Fikou requested changes
we are not doing name checks. look if the iron material is actually there.

2024-11-01 03:17 UTC, SyncIt21 requested changes

2024-11-01 03:17 UTC, SyncIt21 commented on code/game/turfs/open/space/space.dm
> +	else if(istype(C, /obj/item/stack/tile/iron) || istype(C, /obj/item/stack/tile/material) && C.has_material_type(/datum/material/iron))
```suggestion
	else if(C.has_material_type(/datum/material/iron))
```

Both tile types have iron.

2024-11-01 08:24 UTC, SyncIt21 requested changes
I made a mistake in my last review.

2024-11-01 08:24 UTC, SyncIt21 commented on code/game/turfs/open/space/space.dm
> +	else if(C.has_material_type(/datum/material/iron))
```suggestion
	else if(istype(C, /obj/item/stack/tile) && C.has_material_type(/datum/material/iron))
```

My bad. We don't want any item made of iron but only tiles made of iron to be used.

2024-11-01 10:20 UTC, Fikou requested changes
revert syncits suggestions, they allow stuff like catwalks or reinforced glass tiles to work.

2024-11-01 12:05 UTC, merged