[IDED] Syndicate shuttle .50 BMG turrets' bullets now self-disintegrate before hitting a nukie
tgstation/tgstation pull request #87720
Opened 2024-11-06 21:38 UTC by carlarctg

## About The Pull Request

![image](https://github.com/user-attachments/assets/701284a4-3519-4b0b-b3cb-021c61d26847)

## Why It's Good For The Game

The amount of times these have caused my death as a nukie op is crazy. I see it all the time, either a nukie takes damage or a cyborg does. Last Terry round TWO CYBORGS lost all their modules and were left to flounder around helplessly because this dumb fuck turret noticed some jackass through a wall and annihilated our health.

These things are a huge hassle and 95% of the time some funnyman comes in with smart foam to hard counter them anyways. At least let them not be a net negative to nuclear operatives.

## Changelog

:cl:
balance: Syndicate shuttle .50 BMG turrets' bullets now self-disintegrate before hitting a nukie
/:cl:

2024-11-07 02:29 UTC, Pickle-Coding commented
Don't like this and it's anti-sandbox. Getting shot is a consequence of the bullet colliding with you. If you don't want to get shot, avoid the bullet colliding with you. Get out of the way. I haven't observed this phenomenom being a major issue for operatives either. Never heard of anyone report this until now, so I don't believe it's a significant concern unless there's evidence to the contrary.

2024-11-07 02:30 UTC, Loafin34 commented
turn off the turrets

2024-11-07 02:46 UTC, Fikou requested changes

2024-11-07 02:46 UTC, Fikou commented on code/modules/projectiles/projectile/bullets/sniper.dm
> +	if(IS_NUKE_OP(our_target))
no direct antag checks find a better method

2024-11-07 06:10 UTC, SomeoneYouProbablyKnow commented
Yea... too bad? This would allow for what's essentially easier turret camping. Turrets are already plenty unfun if you dont have the right gear to take em on.
If they are a net negative, turn em off. The one time this might be a reasonable change might the the assault drop pod.

2024-11-07 06:55 UTC, carlarctg commented on code/modules/projectiles/projectile/bullets/sniper.dm
> +	if(IS_NUKE_OP(our_target))
ur mom

2024-11-07 07:59 UTC, mc-oofert commented
make them just avoid firing if theres a nuclear operative in the way problem solved

2024-11-07 17:16 UTC, moocowswag commented
They should have a manual operation mode and limited ammo (or require power to self fabricate ammo)

2024-11-07 18:50 UTC, carlarctg commented
> make them just avoid firing if theres a nuclear operative in the way problem solved

is there a meaningful difference here tho

2024-11-08 00:44 UTC, Jacquerel commented
> > make them just avoid firing if theres a nuclear operative in the way problem solved
> 
> is there a meaningful difference here tho

An extremely significant one, which is that dissolving bullets is stupid and a turret not firing when it detects friendlies in the way makes sense.

2024-11-08 05:27 UTC, Kapu1178 commented
ided

2024-11-10 19:22 UTC, Redrover1760 commented
> They should have a manual operation mode and limited ammo (or require power to self fabricate ammo)
> 
> i would also argue that certain nukie armors should have way more ballistic protection than even laser or melee prot since thats what they specialize in while nanotrasen specializes in laser and anti laser tech.

They already do. Elite nukie suit gets bullet 6 and nukie suit gets bullet 5, which is their best protection stats. Good for mitigating friendly fire.

2024-11-14 12:53 UTC, carlarctg commented
will use los check whwen my other pr is meged

2024-11-17 23:16 UTC, closed without merging

2024-11-17 23:16 UTC, carlarctg commented
if both maints and players dont liek it then theres no point