Aliens cannot be husked
tgstation/tgstation pull request #87771
Opened 2024-11-08 23:32 UTC by carlarctg

## About The Pull Request

Xenomorphs now innately have the UNHUSKABLE trait.

## Why It's Good For The Game

Xenomorphs behave rather uniquely compared to humans, especially in their health department. Various stupid oddities in it result in the fact that xenomorphs almost always husk nigh-instantly after death - they have 300+ burn or whatnot, when a normal human has 200 burn at the point of death. This is annoying for some niche interactions, such as reviver implant, which works on xenos, never being able to do its job because it can't revive husks.

That's the walance bit. The other bit is that, uh, how do you husk an exoskeleton. I dunno seems odd.

TL;DR: It arises from buggy behavior, breaks niche interactions, and makes no 'realistic' sense anyways.

## Changelog

:cl:
code: Aliens cannot be husked
/:cl:

2024-11-09 00:17 UTC, Vect0r2 commented
How... How is this a code improvement?

2024-11-09 00:36 UTC, carlarctg commented
> How... How is this a code improvement?

sometimes i dont know how to label prs

2024-11-09 01:05 UTC, AtomTheProphet commented
This seems closer to a fix of an oversight to me, tbh.

2024-11-13 18:21 UTC, MrMelbert requested changes
I would rather the husk threshold be changed to be based off of health / total limb health than aliens just be made outright unhuskable

2024-11-13 18:23 UTC, MrMelbert commented
(Aliens have unique husked sprites and seeing a bunch of toasted aliens when someone goes wild with a flamethrower is fun)

![image](https://github.com/user-attachments/assets/5fa3f538-4e94-4824-ba05-bb338b552441)

2024-11-14 12:31 UTC, carlarctg commented
how ui toast exdoskeleotn thats lrp

2024-11-14 12:46 UTC, carlarctg commented
this whole thing is fucking shitcode i have worse things to do with my time

2024-11-14 12:46 UTC, closed without merging