Refactor shield satalites to use proximity_monitor making them more reliable
tgstation/tgstation pull request #87799
Opened 2024-11-09 18:52 UTC by Autisem

## About The Pull Request

Refactors the meteor satalites to use proximity_monitor making them MUCH more reliable

## Why It's Good For The Game

Previvously it would process and check if meteor is in range every 0.2 seconds via subsystem. This made it very possible that meteor flew past it before it even got detected, bypassing the shield. For it being station objective that feels rather silly. Especialy when meteors can actuely HIT THE SAT AND DESTROY IT

Also slight delay in toggleing on so you cant spam toggle it

## Changelog

:cl:
refactor: NanoTrasen has introducted new upgrades into the aging station shield statalites, they require a but longer to toggle on however
/:cl:

2024-11-11 08:03 UTC, Absolucy commented
my downstream code where i did effectively the same thing may be useful: https://github.com/Monkestation/Monkestation2.0/tree/master/monkestation/code/modules/meteor_shield

i also implemented multi-z coverage, tracking which turfs are covered, and making debris drift towards the station.

also tbh i disagree with making them take time to toggle on as a "trade-off" for making them actually reliable - the reliability was not an intended feature, it was just because using process() to loop thru meteors was a horrible idea, bc meteors that make it thru would cause explosions, which would cause the sats to skip ticks, allowing more meteors through to cause more explosions, causing the sats to skip more process ticks, and so on.

2024-11-17 03:58 UTC, Ghommie requested changes

2024-11-17 03:58 UTC, Ghommie commented on code/modules/station_goals/meteor_shield.dm
> +		src.balloon_alert(user, "you're looking for the [active ? "off" : "on"] button on the [src]")
```suggestion
		balloon_alert(user, "looking for [active ? "off" : "on"] button")
```
Balloon messages short be fairly short.

2024-11-17 03:58 UTC, Ghommie commented on code/modules/station_goals/meteor_shield.dm
> +		return FALSE;
```suggestion
		return FALSE
```
DM oft doesn't need a statement separator on new lines outside of the precompiler iirc.

2024-11-19 20:36 UTC, ZephyrTFA requested changes

2024-11-19 20:36 UTC, ZephyrTFA commented on code/modules/station_goals/meteor_shield.dm
> +	proximity_monitor = new(src,0)
0... what? use a named param here please

2024-11-19 20:36 UTC, ZephyrTFA commented on code/modules/station_goals/meteor_shield.dm
> +	if(istype(proximity_check_mob, /obj/effect/meteor))
this should be inverted to be an early return

2024-12-05 01:12 UTC, Ghommie commented on code/modules/station_goals/meteor_shield.dm
> +	proximity_monitor = new(src,0)
```suggestion
	proximity_monitor = new(src, /* range = */ 0)
```

2024-12-05 01:45 UTC, merged