Refactors projectile dampeners and adds some new visuals
tgstation/tgstation pull request #87913
Opened 2024-11-14 12:12 UTC by Ben10Omintrix

## About The Pull Request

 this pr completely rewrites projectile dampener logic, to make it look alot smoother and for performance's sake. Here's a before vs after of the field visuals movement.
 
before:
https://github.com/user-attachments/assets/d5cf0762-fbdf-45b2-a70e-ebbd45a27a2d

after:
https://github.com/user-attachments/assets/719e47d5-cc13-4787-8503-c909e3759754

ive also added some new visual effects when a bullet enters the field, where itll sort of glitch out
https://github.com/user-attachments/assets/5cd0765d-2ac0-4739-ab99-70924dcf92cc

## Why It's Good For The Game

 this improves projectile dampener performance by a significant much. here's a cost comparison after 6000 steps with each activated
![image](https://github.com/user-attachments/assets/1216db7b-d57f-4757-bc6e-3986327b60ae)
also i noticed that projectile dampeners were looping over range() on fast processing. which defeats the purpose of a proximity monitor to begin with. this pr removes the need for that
closes #84793

## Changelog

:cl:
refactor: projectile dampeners have been refactored. please report any bugs 
/:cl:

2024-11-14 12:46 UTC, SmArtKar requested changes
Looks sane to me? But please doc projectile_dampener.dm, there's no comments and its quite complex

2024-11-14 12:46 UTC, SmArtKar commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener.dm
> +	var/static/image/generic_edge = image('icons/effects/fields.dmi', icon_state = "projectile_dampen_generic")
this is really ugly, you recon you can turn this into an assoc list with bitflags?

2024-11-14 13:52 UTC, Fikou commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener.dm
> +	determine_wobble(location)
the projectile is not holographic

2024-11-14 15:22 UTC, Sealed101 commented
some issues
- #77093
- #83682

2024-11-17 10:33 UTC, Ben10Omintrix commented
> some issues
> 
> * [Peacekeeper borgs' fields get dragged away in space #77093](https://github.com/tgstation/tgstation/issues/77093)
> * [Hyperkinetic Dampening projector (peacekeeper cyborg) invisible after activation #83682](https://github.com/tgstation/tgstation/issues/83682)

just tested these. seems they arent an issue anymore

2024-11-20 18:35 UTC, Ghommie requested changes

2024-11-20 18:35 UTC, Ghommie commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener.dm
> +	for(var/atom/interesting_atom in target)
```suggestion
	for(var/atom/interesting_atom as anything in target)
```

2024-11-20 18:35 UTC, Ghommie commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener.dm
> +	for(var/atom/interesting_atom in target)
```suggestion
	for(var/atom/interesting_atom as anything in target)
```

2024-11-20 18:35 UTC, Ghommie commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener_effects.dm
> +	bullet.speed = bullet::speed
These are going to cause some quirks with projectiles that assume different properties and values on runtime.

2024-11-20 18:35 UTC, Ghommie commented on code/modules/mob/living/silicon/robot/robot.dm
> +	for(var/mob/living/buckled_mob in buckled_mobs)
As anything...

2024-11-23 12:07 UTC, SmArtKar requested changes

2024-11-23 12:07 UTC, SmArtKar commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener_effects.dm
> +	var/projectile_speed_multiplier = 2.5
Should be inverted to
```suggestion
	var/projectile_speed_multiplier = 0.4
```

now that #87740 is merged

2024-11-23 12:07 UTC, SmArtKar commented on code/datums/proximity_monitor/fields/projectile_dampener/projectile_dampener_effects.dm
> +	projectile_speed_multiplier = 1.5
```suggestion
	projectile_speed_multiplier = 0.66
```

2024-11-23 13:50 UTC, merged