welding hats play the visor up/down sfx instead of MOD hiss
tgstation/tgstation pull request #87920
Opened 2024-11-14 21:33 UTC by Sadboysuss

## About The Pull Request
changes the visor up/down sfx for welding hats to be `SFX_VISOR_UP`/`SFX_VISOR_DOWN`

## Why It's Good For The Game
It makes much more sense

## Changelog

:cl: grungussuss
sound: changed the welding hat toggle sfx
/:cl:

2024-11-14 23:06 UTC, MrMelbert reviewed
If it were me I'd format them as `playsound(src, up ? SFX_VISOR_UP : SFX_VISOR_DOWN, 50, TRUE)`, but I don't mind that much

2024-11-14 23:06 UTC, MrMelbert commented on code/modules/clothing/spacesuits/plasmamen.dm
> +		playsound(src, SFX_VISOR_DOWN, 50, TRUE) //Visors don't just come from nothing
```suggestion
		playsound(src, SFX_VISOR_DOWN, 50, TRUE) 
```

2024-11-15 17:44 UTC, Sadboysuss commented on code/modules/clothing/spacesuits/plasmamen.dm
> +		playsound(src, SFX_VISOR_DOWN, 50, TRUE) //Visors don't just come from nothing
[done](https://github.com/tgstation/tgstation/pull/87920/commits/c59ac5da15feee274457af7bfe21462b7c9d0faf)

2024-11-16 19:20 UTC, Ben10Omintrix requested changes

2024-11-16 19:20 UTC, Ben10Omintrix commented on tgstation.dme
> +#include "code\__DEFINES\tracy.dm"
```suggestion
```
think something mightve gone wrong

2024-11-16 21:08 UTC, Sadboysuss commented on tgstation.dme
> +#include "code\__DEFINES\tracy.dm"
merge skew it seems

2024-11-17 00:55 UTC, merged