This vendor is suspicious!
tgstation/tgstation pull request #88183
Opened 2024-11-24 21:20 UTC by Sadboysuss

## About The Pull Request
- emagging a vendor now makes it hostile like in the rampant brand intelligence event
it doesn't spread to other vendors though.

## Why It's Good For The Game
I think it's really funny and fits the emag action, also a great method to make death traps.

## Changelog

:cl: grungussuss
add: vendors can now be emaged to make them hostile
/:cl:

2024-11-24 22:00 UTC, Jacquerel commented
I'm a little wary of this as an emag function given how you'd be able to pretty rapidly do it to every vending machine you walk past, but on the other hand while they're very harmful they're also reasonably easy to stop if anyone has tools

2024-11-24 23:01 UTC, Ghommie commented on code/modules/vending/_vending.dm
> +	addtimer(CALLBACK(src, PROC_REF(become_hostile)), rand(10, 30))
```suggestion
	addtimer(CALLBACK(src, PROC_REF(become_hostile)), rand(1 SECONDS, 3 SECONDS))
```

2024-11-25 00:30 UTC, Loafin34 commented
pssh emags are barely seen anymore and this is way better than just "contraband". you can get contraband easy, and the emag's supposed to wreck havoc!

2024-11-25 05:52 UTC, SomeoneYouProbablyKnow commented
The big danger here is that emaging a bunch of vendors will flatten unsuspecting new players on accident, kinda like how using a bunch of dehydrated carps isnt gonna get anyone but the most vulnerable players who you werent aiming to kill... but eh, that's life.

Another potential use is to sneakily emag a vendor which is next to someone. The splat stun is LONG. If they are distracted enough it's enough to allow for a full kill. But... that's also probably fine.

2024-11-25 08:38 UTC, Sadboysuss commented
> The big danger here is that emaging a bunch of vendors will flatten unsuspecting new players on accident.

- mfw antag item is dangerous

- mfw new players die to antags

- mfw new players die to rampant brand intelligence event

2024-11-25 18:46 UTC, DaCoolBoss commented
I don't like it because it goes against what the emag's established purpose, which is breaking locks and overriding safeties. If someone swipes an emag on a vendor, they will expect access to the contraband menu, or free goodies, or removing ID requirements. This is more like uploading a virus to a vendor.

2024-11-25 23:14 UTC, SimplySmiley123 commented
> I don't like it because it goes against what the emag's established purpose, which is breaking locks and overriding safeties. If someone swipes an emag on a vendor, they will expect access to the contraband menu, or free goodies, or removing ID requirements. This is more like uploading a virus to a vendor.

Counterargument:
Bots and borgs exist and get the "turned into something pretty lethal" treatment.

Plus from in-game perspective, sentient vendors event exists and implies all vendors are capable of deciding to waddle around crushing people and that by default they don't do that. Emag removing safeties preventing that would fit your definition.

2024-11-26 12:30 UTC, SmArtKar requested changes
I think that this is a step in the right direction (E-MAG being a tool of sabotage, not a power up), but this indeed is quite strong. Maybe give it a change (40%?) to make vendors shoot items instead, like rampant AI does?

2024-11-26 13:03 UTC, closed without merging