"AAAAAAAAAAAAAAAAAA", the cyborg said calmly.
tgstation/tgstation pull request #88203
Opened 2024-11-25 21:20 UTC by Sadboysuss

## About The Pull Request

https://github.com/user-attachments/assets/06ffa832-1b68-4a8f-b078-baf6aeeefd9a

## Why It's Good For The Game

![dalek-daleks](https://github.com/user-attachments/assets/45c9e13d-8db9-440e-aaec-a15c5b798464)

## Changelog

:cl: PixelShader and grungussuss
sound: cyborgs now have a scream sound
/:cl:

2024-11-25 21:48 UTC, DrAmazing343 commented
This is gonna get abused SO HARD LMFAOOOO

Speedmerge.

2024-11-25 22:23 UTC, MrMelbert commented
I think it's too high pitched

2024-11-25 22:25 UTC, MrMelbert commented on code/modules/mob/living/emote.dm
> +		return 'sound/mobs/non-humanoids/cyborg/cyborg_scream.ogg' //if you add more sounds for living scream - do the same thing human emotes do for get_sound
```suggestion
	if(iscyborg(user))
		return 'sound/mobs/non-humanoids/cyborg/cyborg_scream.ogg' //if you add more sounds for living scream - do the same thing human emotes do for get_sound
	return ..()
```

2024-11-25 22:25 UTC, MrMelbert requested changes
Any chance it could be adjusted to roughly the same pitch as the trailing part of the borg deathsound?

2024-11-25 22:49 UTC, MrMelbert commented
Yeah the last half second of that just sounds like a normal dude screaming

2024-11-25 23:01 UTC, Sadboysuss commented
> Yeah the last half second of that just sounds like a normal dude screaming 

It's intended

If you think it isn't good , go ahead and close it, I have no attachments to it. Will just have to go back to the drawing board

2024-11-26 00:18 UTC, MrMelbert commented
Yeah I'm still not a fan, I'd prefer if the sound was closer to that of the cyborg deathsound

2024-11-26 00:18 UTC, closed without merging