Icemoon lavaloops now look different.
tgstation/tgstation pull request #88235
Opened 2024-11-26 22:21 UTC by Ghommie

## About The Pull Request
Lavaland lavaloops and icemoon variant look exactly the same, with the only difference being the boomerang effects, yet they have two different entries in the index of catchable fishes, which has been noticed by a few other players.

This PR differentiates the two, giving the latter new name, sprite, temperature requirements, including two evolution datums for lavaloops to plasmaloops and viceversa.

This also fixes a couple logic errors with the evolution requirements tooltip and the moonfish evolution size/weight reqs.

## Why It's Good For The Game
Having two exact looking lavaloop entries in the fish index is kinda confusing.

## Changelog

:cl:
add: Icemoon lavaloops fish now look different.
/:cl:

2024-11-28 17:27 UTC, Wallemations approved these changes
Looks good but it failed a check, feel free to merge it once you fix that

2024-11-28 21:52 UTC, Ghommie commented
@Wallemations all check pass now.

2024-11-28 22:53 UTC, Wallemations commented
> @Wallemations all check pass now.

![image](https://github.com/user-attachments/assets/a8b1ca65-57b7-4d72-a09b-8a72c738da22)

?

2024-11-29 16:37 UTC, SmArtKar requested changes

2024-11-29 16:37 UTC, SmArtKar commented on code/modules/fishing/fish/fish_evolution.dm
> +		else if(required_temperature_max < INFINITY)
```suggestion
		else if(required_temperature_max == INFINITY)
```

2024-11-29 17:31 UTC, merged