Fixing/reworking explosive interactions with organ manip and fishing
tgstation/tgstation pull request #88232
Opened 2024-11-26 18:59 UTC by Ghommie

## About The Pull Request
I have grown to dislike the previous implement of explosive fishing. It was particurly broken around fish sources that checked if the fishing spot was of a specific type, and the FISH_SOURCE_FLAG_EXPLOSIVE_MALUS flag only really worked around turfs because of the gap between pooling the spawn locations and spawning the loot, which would have made trying it on movables quite unsafe since they're moved to nullspace when deleted.

This has lead me to rework how explosive fishing malus/exhaustion accumulates in a simplier and more effiient way. Fish are now spawned immediately, and the counter for the malus goes up by one each call, and decays over time at a rate of 1 every 5.5 seconds.

This also fixes #88227.

## Why It's Good For The Game
Easier implementation of explosive fishing and bugfix.

## Changelog

:cl:
fix: Bombing someone during organ manipulation no longer summons new organs.
/:cl:

2024-11-26 19:48 UTC, Dawnseer commented
When will we be able to sync our fishing portal to someone's chest if we multitool em during organ manipulation surgery?
Lizards gotta eat

2024-11-26 21:32 UTC, Ghommie commented
> When will we be able to sync our fishing portal to someone's chest if we multitool em during organ manipulation surgery? Lizards gotta eat

I had thought that was already possible. If it is not, it's probably due to the different proc-chains for attacking mobs, and I'll get to it soon.

2024-11-28 11:08 UTC, Time-Green requested changes

2024-11-28 11:08 UTC, Time-Green commented on code/modules/fishing/sources/_fish_source.dm
> +			multiplier = 1/(explosive_fishing_score**EXPLOSIVE_FISHING_MALUS_EXPONENT)
```suggestion
			multiplier = explosive_fishing_score**-EXPLOSIVE_FISHING_MALUS_EXPONENT
```
Unnecessary division

2024-11-28 15:43 UTC, Ghommie commented on code/modules/fishing/sources/_fish_source.dm
> +			multiplier = 1/(explosive_fishing_score**EXPLOSIVE_FISHING_MALUS_EXPONENT)
Aaaah, goofy ass forgot about math properties moment.

2024-11-28 18:28 UTC, merged