NEW SMITE: Retcon, also refactors temporary_atom element
tgstation/tgstation pull request #88275
Opened 2024-11-28 23:15 UTC by DATA-xPUNGED

## About The Pull Request

Added a new smite called Retcon, which fades the victim into nothing after a configurable set of time (default being 5 seconds), they can still move and act and stuff while they're fading, which will probably lead to funny shenanigans
Also refactors the `temporary_atom` element into an atom-level proc called `fade_into_nothing()`

## Why It's Good For The Game

more admin abuse opportunities for the smite, and the element really wasn't doing anything element-ish, so why have it be an element in the first place?

## Changelog

:cl:
admin: Admins can now Retcon people out of existence.
refactor: refactored the temporary_atom element into the fade_into_nothing() proc
/:cl:

2024-11-28 23:27 UTC, Jacquerel requested changes

2024-11-28 23:27 UTC, Jacquerel commented on code/__HELPERS/fade_into_nothing.dm
> +/atom/proc/fade_into_nothing_animate(datum/weakref/target_ref, fade_time)
```suggestion
		addtimer(CALLBACK(src, PROC_REF(fade_into_nothing_animate), WEAKREF(target), fade_time), life_time - fade_time, TIMER_DELETE_ME)

/// Actually does the fade out, used by fade_into_nothing()
/atom/proc/fade_into_nothing_animate(datum/weakref/target_ref, fade_time)
```

These two proc names don't match.

2024-11-28 23:27 UTC, Jacquerel commented on code/__HELPERS/fade_into_nothing.dm
> +/atom/proc/fade_into_nothing(var/atom/target = src, life_time = 5 SECONDS, fade_time = 3 SECONDS)
If this is to be an atom proc, it probably doesn't need the first argument.
You could alternately make it a global proc and retain the first argument.

2024-11-28 23:27 UTC, Jacquerel commented on code/__HELPERS/fade_into_nothing.dm
> +	var/atom/target = target_ref?.resolve()
We also don't need to pass the target as a weakref and resolve it if this is an atom proc, it should presumably just be `src`

2024-11-28 23:27 UTC, Jacquerel commented on code/modules/admin/smites/retcon.dm
> +	var/fade_out_timer //the time it takes to actually do the fade out animation, the victim will always have some time still fully visible
```suggestion
	/// how long until the thing attacked by this smite gets deleted
	var/timer 
	/// the time it takes to actually do the fade out animation, the victim will always have some time still fully visible
	var/fade_out_timer 
```
Triple-slashed comments above var or proc declarations are picked up by our auto-documenter.
Use `//` for comments or stuff in the middle of a proc, `///` for documenting what a variable is for.

2024-11-28 23:31 UTC, Jacquerel requested changes

2024-11-29 05:10 UTC, DrAmazing343 commented
Being able to Build Mode the temporary_atom effect is so peak actually

2024-11-29 11:36 UTC, distributivgesetz commented
a `visible_message` about the target being removed from the story would be awesome for added RP tbh

2024-11-29 13:10 UTC, Jacquerel commented
Your code still doesn't compile, let me know on Discord if you need some help untangling why as that seems more sensible than writing it for you using review notes 😅

2024-11-29 20:58 UTC, Ghommie commented
I personally think retcon smite should also remove them from the crew manifest, remove any memory datum from other mobs' minds that reference them, delete their bank account, scrub them from antagonists objectives that reference the target and reopen up their job slot. We've plenty of smites and this is just some fade out, but I'm not going to pretend you'll even accomplish half of what I suggest.

2024-11-30 13:51 UTC, DATA-xPUNGED commented
> Your code still doesn't compile, let me know on Discord if you need some help untangling why as that seems more sensible than writing it for you using review notes 😅

yeah i'm having issue with the weakref part, i'll ping you when i have free time

2024-11-30 13:52 UTC, DATA-xPUNGED commented
> I personally think retcon smite should also remove them from the crew manifest, remove any memory datum from other mobs' minds that reference them, delete their bank account, scrub them from antagonists objectives that reference them and finally reopen up their job slot. We've plenty of smites and this is just some fade out, but I'm not going to pretend you'll even accomplish half of what I suggest.

I should make them scream with such timing that the scream gets cut off...

2024-12-23 00:36 UTC, closed without merging