fixes basic mobs playing body drop sfx
tgstation/tgstation pull request #88431
Opened 2024-12-09 01:07 UTC by Sadboysuss

## About The Pull Request
closes https://github.com/tgstation/tgstation/issues/88426

## Changelog

:cl: grungussuss
fix: basic mobs don't play body drop sfx on death anymore
/:cl:

2024-12-09 06:00 UTC, mc-oofert commented
cant you just exclude it via type check or something

2024-12-10 20:05 UTC, Ghommie commented on code/modules/mob/living/basic/basic.dm
> +	ADD_TRAIT(src, TRAIT_NO_BODY_DROP_SFX)
```suggestion
	ADD_TRAIT(src, TRAIT_NO_BODY_DROP_SFX, INNATE_TRAIT)
```

2024-12-11 06:34 UTC, mc-oofert commented
I think a trait for this is dumb

2024-12-13 20:31 UTC, LemonInTheDark requested changes
pull and update tests are failing

2024-12-13 20:31 UTC, LemonInTheDark commented on code/__DEFINES/traits/declarations.dm
> +#define TRAIT_NO_BODY_DROP_SFX "NO_BODY_DROP_SFX"
this doesn't make any sense to me it's applied on init. also the motivation doesn't seem tied to it at all

2024-12-13 21:57 UTC, closed without merging