airlocks and computers are leanable
tgstation/tgstation pull request #88478
Opened 2024-12-11 02:37 UTC by Sadboysuss

## About The Pull Request
- added a signal - `COMSIG_ATOM_DENSITY_CHANGED`, is sent when set_density is called and doesn't early return
- changed all manual assignments of .density to use `set_density` so the signal is sent
- airlocks get the leanable component, if the airlock opens while you are leaning on it - you will fall
- computers get the leanable component

## Why It's Good For The Game
can lean on more stuff, roleplay! Immersion!
*John Tider leans on the airlock*

## Changelog

:cl: grungussuss
add: computers and airlocks are now leanable
refactor: changed how density/collision of some objects is changed, report any oddities!
/:cl:

2024-12-11 02:58 UTC, norsvenska commented
you should fall down if the airlock is opened while you're leaning on it

2024-12-11 03:17 UTC, MrMelbert commented on code/game/machinery/_machinery.dm
> +	/// For performance reasons and to cut down on init times we are "lazy-loading" the leaning component when someone drags their sprite onto us, and then calling dragging code again to trigger the com
This comment seems like lies

2024-12-11 03:44 UTC, MrMelbert commented
I don't think this was tested actually

2024-12-11 13:05 UTC, Sadboysuss commented
Oh actually I forgot to commit all my changes and this isn't the entire thing

2024-12-11 16:34 UTC, Sadboysuss commented on code/game/machinery/_machinery.dm
> +	/// For performance reasons and to cut down on init times we are "lazy-loading" the leaning component when someone drags their sprite onto us, and then calling dragging code again to trigger the com
oh because it's old, see new code

2024-12-11 16:34 UTC, Sadboysuss commented
https://github.com/user-attachments/assets/f269d8b9-0d25-4916-af28-650e468370a7

2024-12-22 18:01 UTC, SyncIt21 requested changes
Leaning code has slightly changed since #88494

2024-12-22 18:07 UTC, Sadboysuss commented
> Leaning code has slightly changed since #88494

I see, thanks for helping adapt it to your changes

2024-12-22 18:07 UTC, Sadboysuss commented
I'm gonna test this later, when I do - I'll take it out of draft

2024-12-24 14:34 UTC, Sadboysuss commented
it works

2024-12-28 05:35 UTC, Ghommie approved these changes

2024-12-28 05:36 UTC, Ghommie commented
Conflicts.

2024-12-29 07:53 UTC, merged