Kissing while you have the ink infusion ability off cooldown gives you an ink kiss
tgstation/tgstation pull request #88556
Opened 2024-12-17 04:19 UTC by carlarctg

## About The Pull Request

Kissing while you have the ink infusion ability off cooldown gives you an ink kiss.

This ink kiss behaves identically to a normal kiss but also creates a ink spit projectile and calls on_hit(target) on its own on_hit (not on_harmless_hit)

## Why It's Good For The Game

I think it's funny to kiss people and splat them with ink.

I did not test this because apparently worktrees dont work with pressing f5

## Changelog

:cl:
add: Kissing while you have the ink infusion ability off cooldown gives you an ink kiss
/:cl:

2024-12-17 23:59 UTC, Ghommie requested changes

2024-12-17 23:59 UTC, Ghommie commented on code/modules/mob/living/emote.dm
> +		ink_action.StartCooldown()
```suggestion
	if(ink_action?.IsAvailable())
		kiss_type = /obj/item/hand_item/kisser/ink
		ink_action.StartCooldown()
	else
		ink_action = null
```

2024-12-17 23:59 UTC, Ghommie commented on code/modules/mob/living/emote.dm
> +		ink_action.ResetCooldown()
```suggestion
		ink_action?.ResetCooldown()
```

2024-12-23 06:44 UTC, carlarctg commented
tested

2024-12-23 19:36 UTC, merged