Circuit Wirenet Components + Assembly Shell Tweaks
tgstation/tgstation pull request #88593
Opened 2024-12-19 01:43 UTC by Y0SH1M4S73R

## About The Pull Request

Assembly shells now use power from whatever machine/borg/mech/modsuit they are attached to the wires of, instead of their own shell, when appropriate.

As for the meat of this PR, circuit wirenet components function like NTnet and NFC components, but their signals are transmitted across whatever cable network the shell (or in the case of assembly shells, the machine or button it's inserted into) is connected to. These components are available with roundstart tech.

## Why It's Good For The Game

Provides a somewhat intuitive way to make circuit networks that aren't dependent on external factors to continue functioning.

NTnet components require a functional NTnet relay, which usually means they need telecomms to be working. NFC components have a range limit, and you need to provide a specific reference to the circuit being communicated with. Wirenet components, on the other hand, just need the shell to be anchored (or for assembly circuits, the thing whose wire it is attached to), and for the shell to have a cable under it.

Also might indirectly provide a reason to use cable layers other than the default one.

## Changelog

:cl:
add: Adds circuit wirenet components, allowing data to be transmitted and received over cable networks.
qol: When attached to a machine, mech, modsuit, or borg, assembly circuit shells will use power from those instead of the circuit's own battery.
/:cl:

2024-12-19 06:28 UTC, francinum commented
![hahahahaha](https://file.house/Hldb0Nruv4WoBjUJBGFlmA==.png)

2024-12-19 06:45 UTC, Y0SH1M4S73R commented
Nothing's stopping you from doing this with ntnet components (and to a slightly lesser extend, nfc components).

Furthermore, admins will punt you into the sun if you try this on a live server.

2024-12-24 15:08 UTC, moocowswag commented
So an assembly shell on an airlock wire doesnt need a charged cell and one on a grenade wire does?

2024-12-24 23:51 UTC, Y0SH1M4S73R commented
> So an assembly shell on an airlock wire doesnt need a charged cell and one on a grenade wire does?

yes, I thought it kinda annoying how assembly shells always needed a cell

2025-01-04 12:59 UTC, Watermelon914 requested changes

2025-01-04 12:59 UTC, Watermelon914 commented on code/modules/wiremod/components/wirenet/send.dm
> +		SEND_SIGNAL(connected_powernet, COMSIG_POWERNET_CIRCUIT_TRANSMISSION, list("data" = data_package.value, "enc_key" = enc_key.value, "port" = WEAKREF(data_package)))
not a huge fan of this, you're treating COMSIG_POWERNET_CIRCUIT_TRANSMISSION as a proc rather than as an event. Could you instead call a proc on the connected_powernet datum that then does some stuff?

2025-01-04 12:59 UTC, Watermelon914 commented on code/modules/wiremod/components/wirenet/send_literal.dm
> +		SEND_SIGNAL(connected_powernet, COMSIG_POWERNET_CIRCUIT_TRANSMISSION, list("data" = list_output.value, "enc_key" = enc_key.value, "port" = WEAKREF(list_output)))
Same thing here

2025-01-13 16:16 UTC, merged

2025-04-22 22:16 UTC, moocowswag commented
tried assembly shell on apc wire and it didnt pull power from it