Removes spamming during closet breakout
tgstation/tgstation pull request #88682
Opened 2024-12-23 15:46 UTC by SyncIt21

## About The Pull Request
- Fixes #88657

When you begin resisting you can't resist again till either the breakout was successful or failed. This also lead to the shake animation being reapplied multiple times causing additional shaking on top of it already shaking

## Changelog
:cl:
fix: breaking out of a closet won't spam chat or shake like it's having a seizure
/:cl:

2024-12-23 15:48 UTC, SyncIt21 commented
The removal tag does not apply here. Removing it would be appreciated

2024-12-26 09:52 UTC, Ghommie requested changes
I think a simple `DOING_INTERACTION_WITH_TARGET()` check would be better than a new variable.

2024-12-26 10:31 UTC, SyncIt21 commented
> DOING_INTERACTION_WITH_TARGET

Thanks I learnt something new

2024-12-26 10:31 UTC, SyncIt21 commented
> DOING_INTERACTION_WITH_TARGET

Thanks I learnt something new

2024-12-27 23:46 UTC, merged