Adds a new area flag, LOCAL_TELEPORT, given to virtual domains and deathmatch arenas.
tgstation/tgstation pull request #88756
Opened 2024-12-27 16:06 UTC by carlarctg

## About The Pull Request

Adds a new area flag, LOCAL_TELEPORT.

This flag allows teleports ONLY in the same area that the teleport is used. This allows for short range hijinks without enabling long range exploits, and thus it's given to DMs and domains.

Changed almost all area_flags & NO_TELEPORT checks to use check_teleport() (as now areas may use local_teleport instead, and this lets them check for multiple things instead)

Thus I re-added Void Phase to the heretic scribe in DM and shuffled some stuff around

(realizing now i neglected to doublecheck if blade breaking tps you to station. need to check just in case)

## Why It's Good For The Game

It sucks you can't use teleporting abilities in temporary areas, so this is a good way to allow this to still happen without opening the way for gamebreaking exploits.

## Changelog

:cl:
code: Adds a new area flag, LOCAL_TELEPORT, given to virtual domains and deathmatch arenas.
code: Re-added Void Phase to Heretic Scribes in Deathmatch's Ragnarok map.
/:cl:

2024-12-27 19:57 UTC, ZephyrTFA requested changes
This needs to check for a valid path from A to B; ensuring the path does not cross through any other areas.

2024-12-28 18:43 UTC, carlarctg commented
> This needs to check for a valid path from A to B; ensuring the path does not cross through any other areas.

i dont see anything wrong with that?

2025-01-05 17:12 UTC, ZephyrTFA approved these changes

2025-01-05 17:12 UTC, ZephyrTFA commented on code/datums/actions/items/vortex_recall.dm
> +		return
if the only way for this to be on a different item is admin interference; I say let it work.

2025-01-05 17:12 UTC, ZephyrTFA commented on code/datums/actions/items/vortex_recall.dm
> +		return FALSE
although I suppose that would make this check difficult

2025-01-06 13:55 UTC, merged