You can chug glowstick fluid to get glowing eyes
tgstation/tgstation pull request #88760
Opened 2024-12-27 20:29 UTC by SmArtKar

## About The Pull Request

Glowsticks now contain some luminescent fluid (amount equal to their duration, in minutes) which, when drank, makes your eyes glow in the dark and gives you minor (meson level) night vision. When above 20u are taken at once (or when you have more than 20u in your body) the glow becomes strong enough to project a beam of light in front of you. Overdosing (50u threshold) will make the glowing effect permanent (not the flashlight part though).

![3DEeEjJ](https://github.com/user-attachments/assets/cd03609e-d8ce-4278-9619-81ca84aedbea)

As this creates a flashlight inside of the mob, nightmares can stop the glowing effect with their light eater.

## Why It's Good For The Game

A funny gimmick reagent with a rather minor impact. Same effects can be achieved with mesons, flashlights or eye implants, so I don't see this being a major issue. Could probably be used for some devious shenanigans, but I don't see any ways to pull it off myself. Adds sovl.

## Changelog

:cl:
add: You can chug glowstick fluid to get glowing eyes
/:cl:

2024-12-27 20:30 UTC, distributivgesetz commented
del: Removed eyeglow effect from drinking glowstick fluid because glowsticks contain glass shards and toxic chemicals in real life.

2024-12-27 20:34 UTC, SmArtKar commented
> del: Removed eyeglow effect from drinking glowstick fluid because glowsticks contain glass shards and toxic chemicals in real life.

we're not Mojang

2024-12-27 21:49 UTC, DrAmazing343 commented
Peak cartoon shit. Love it.

2024-12-27 21:58 UTC, norsvenska commented
breaking a bone while it's in your system should make your character glow until it's gone

2024-12-27 23:16 UTC, Steel-Serperior commented
Peak and sovl

2024-12-28 05:54 UTC, uaioy commented
isnt masons giving night vision unintended

2024-12-28 05:59 UTC, krookodilehunter commented
do the different colors of glowsticks affect the glow color?

2024-12-28 06:34 UTC, SmArtKar commented
> isnt masons giving night vision unintended

Nope, its pretty intentional

> do the different colors of glowsticks affect the glow color?

Yeah your eyes glow the same color as glowstick juice you've just chugged

2024-12-28 20:18 UTC, SomeoneYouProbablyKnow commented
Wait did we fix mason vision exploiting? Or is it still used by powergamers with cranked up brightness? Cos imagining glow eyes + huds powergamers is... ugh

Yea obviously people who might drink glowstick liquid... nothing is gonna save them in the long run. 
But i just think chugging straight out of it is too silly. The game works best when normal parts of the station are at least somewhat realistic (not actually realistic but more so realistic-feeling), gives good contrast to the actually wacky shit.
Why not make it an easy bar cocktail CONTAINING glowstick liquid. Then there's a nice separation between those.

2024-12-28 22:34 UTC, kassori commented
You beautiful bingus, I've been asking for this for years, my god

2024-12-29 12:04 UTC, SmArtKar commented
> Wait did we fix mason vision exploiting? Or is it still used by powergamers with cranked up brightness? Cos imagining glow eyes + huds powergamers is... ugh
> 
> Yea obviously people who might drink glowstick liquid... nothing is gonna save them in the long run. 
> But i just think chugging straight out of it is too silly. The game works best when normal parts of the station are at least somewhat realistic (not actually realistic but more so realistic-feeling), gives good contrast to the actually wacky shit.
> Why not make it an easy bar cocktail CONTAINING glowstick liquid. Then there's a nice separation between those.

Mesons giving minor night vision is intended, its not an exploit. These do not stack however.

2024-12-30 19:49 UTC, Loafin34 commented
can you wash glowsticks with crayons to change the color?

2024-12-31 21:48 UTC, SmArtKar commented
Slightly adjusted night vision strength to the point where you can still see, but its difficult to figure out smaller details (10 vs 15 of mesons), and made it have a slight (8% per second) chance to deal 1 toxloss per second.

2025-01-01 09:59 UTC, SyncIt21 requested changes
It still amounts to 1 cause tick is every 2 seconds not 1

2025-01-01 09:59 UTC, SyncIt21 commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		if(affected_mob.adjustToxLoss(1, updating_health = FALSE))
```suggestion
		if(affected_mob.adjustToxLoss(1 * REM * seconds_per_tick, updating_health = FALSE))
```

2025-01-01 10:49 UTC, SmArtKar commented on code/modules/reagents/chemistry/reagents/other_reagents.dm
> +		if(affected_mob.adjustToxLoss(1, updating_health = FALSE))
No, this is correct as we're already accounting for it in SPT_PROB

2025-01-02 10:26 UTC, Time-Green commented on code/game/objects/items/devices/flashlight.dm
> +		bite_consumption = round(reagents.total_volume / (rand(20, 30) / 10)),\
```suggestion
		bite_consumption = round(reagents.total_volume / (rand(2, 3))),\
```
This would lose a decimal point, but does that matter here?

2025-01-02 10:26 UTC, Time-Green commented on code/game/objects/items/devices/flashlight.dm
> +		bite_consumption = round(reagents.total_volume / (rand(20, 30) / 10)),\
```suggestion
		bite_consumption = round(reagents.total_volume / (rand(20, 30) * 0.1)),\
```
If you want to keep the decimals.
I know this isn't a requirement anymore, but this more readable

2025-01-02 10:26 UTC, Time-Green commented on code/game/objects/items/devices/flashlight.dm
> +	reagents.expose_temperature(amount * temp_per_fuel)
ooga booga boomstick

2025-01-02 12:40 UTC, SmArtKar commented on code/game/objects/items/devices/flashlight.dm
> +	reagents.expose_temperature(amount * temp_per_fuel)
I guess you could use it for some funny chemical reactions, you recon this could become a problem? Their volume is pretty small, so m not sure

2025-01-02 14:01 UTC, merged