Caps the amount of free credits cargo gains from department orders
tgstation/tgstation pull request #88797
Opened 2024-12-29 12:59 UTC by Profakos

## About The Pull Request

Departmental orders are a neat feature, but some of the available packs had problems economywise. The cooldown of range from 10 to 20 minutes, with 10 minutes being the base for anything costing less than 320 credits, and 20 minutes at 3000 credits. I have no problem with the lower cap, but the upper cap has issues, as recently, a 20k crate was added to cargo, which means it is possible to dump quite a large amount of funds into cargo every 20 minutes.

Departmental orders probably need a bigger overhaul, and this solution is imperfect, but I have talked with @ArcaneMusic  about this as an interim stop gap measure.

This PR also autodocs a proc, and moves some values to global defines, for ease of balancing.

This PR affects the following crates, with the uncapped crate values in brackets.

Armoury

- Combat Shotguns (3500 credits)
- Energy Guns (3600 credits)
- NT BR-38 Crate (20,000 credits)

Engineering

- BSA parts (6000 credits)
- DNA Vault Parts (4800 credits)

Engine Construction
- HFR Crate (4800)
- Supermatter Shard Crate (4000)

Materials

- BZ Crate (9000 credits)
- Nitrous Oxide (9000 credits)
- Water Vapor Crate (3010 credits)

Toys
- Collectible Hats Crate (8000 credits)

## Why It's Good For The Game

Instantly awarding 20k to cargo every 20 minute, in addition to 27k from the other consoles (if both engineering and science orders BZ, service orders collectible hats, and medical orders something around 1000), is a bit too much. The money gained should be along a much more predictable and expected value. With this chance, the most they can get is 13k every 20 minutes across all departments.

## Changelog

:cl:
balance: To discourage frivolous spending, fulfilling department orders will not award cargo more than 3000 credits.
/:cl:

2024-12-29 13:07 UTC, necromanceranne commented
Nice nice.

2024-12-29 14:07 UTC, YuliceTheDruid commented
May want to keep in mind the impact this can have on things like War Ops, since initially cargo was balanced around having about a ~10k budget, and that was removed when departmental orders got added.

2024-12-29 15:14 UTC, SyncIt21 requested changes
Small nitpicks

2024-12-29 15:14 UTC, SyncIt21 commented on code/modules/modular_computers/file_system/programs/dept_order.dm
> +	time_y = DEPARTMENTAL_ORDER_COOLDOWN_TIME * time_y
```suggestion
	time_y *= DEPARTMENTAL_ORDER_COOLDOWN_TIME
```

2024-12-29 15:14 UTC, SyncIt21 commented on code/datums/elements/deliver_first.dm
> +		cargo_account.adjust_money(min(payment,DEPARTMENTAL_ORDER_MAX_PAYOUT))
```suggestion
		cargo_account.adjust_money(min(payment, DEPARTMENTAL_ORDER_MAX_PAYOUT))
```

2024-12-29 15:14 UTC, SyncIt21 commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_CREDITS_MIN CARGO_CRATE_VALUE * 1.6
```suggestion
#define DEPARTMENTAL_ORDER_COOLDOWN_CREDITS_MIN (CARGO_CRATE_VALUE * 1.6)
```

2024-12-29 15:14 UTC, SyncIt21 commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_CREDITS_MAX CARGO_CRATE_VALUE * 15
```suggestion
#define DEPARTMENTAL_ORDER_COOLDOWN_CREDITS_MAX (CARGO_CRATE_VALUE * 15)
```

2024-12-29 15:14 UTC, SyncIt21 commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_TIME 10 MINUTES
```suggestion
#define DEPARTMENTAL_ORDER_COOLDOWN_TIME (10 MINUTES)
```

2024-12-29 15:14 UTC, SyncIt21 commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_MAX_PAYOUT CARGO_CRATE_VALUE * 15
```suggestion
#define DEPARTMENTAL_ORDER_MAX_PAYOUT (CARGO_CRATE_VALUE * 15)
```

2024-12-29 16:26 UTC, Profakos commented
> May want to keep in mind the impact this can have on things like War Ops, since initially cargo was balanced around having about a ~10k budget, and that was removed when departmental orders got added.

Still achievable with this change (and in fact, you could get multiples of ~10k in the current iteration)

2024-12-29 18:57 UTC, Jackraxxus commented
imo these already arent used enough.
also the words 'predictable and expected' should be kept as far away from ss13 as possible

2024-12-29 19:44 UTC, carlarctg commented
honestly the absurd price of the battle rifle crate is the issue, not the rest

2024-12-29 22:03 UTC, CCC23 commented
Yea this seems mainly like a problem with the battle rifle (also balancing cargos ability to make money is fighting the air) department orders do serve as a nice early source of cash but it's on about the same level as grabbing all the plasma generators on the station or selling artifacts

2024-12-30 00:31 UTC, GuillaumePrata commented
The long term solution to this is a fixed value and cooldown per crate unrelated to the value of the order itself, this way there will be no interest on the cargo techs/dept crew to min max money and instead focus on just ordering what is needed the most at the current situation.

Cargo should be about supplying the station with what is needed, not spreadsheet simulator for the most bank.

Seeing people fight over cheap dept order is cringe and we should just nip that at the bud.

2024-12-30 02:17 UTC, necromanceranne commented
I gave BRs a high price as a restriction, only to then realize that making something expensive inversely turns it into a free money generator for cargo. We've lost even a minor limiting factor on crates as a consequence of these consoles. I hate the fact that I had to make the import category just to circumvent this shit, and I don't want to stick anything I would prefer being limited into it.

Why am I the only person who seems to think that this has entirely undermined crate price as a possible limiting factor? At the very least this PR makes it so that there isn't a recursive money generation taking place, where ordering from the departmental consoles then allows for the purchase of an additional crates worth of value. 

Though ordering the most expensive item is still almost always the best option for money generation. And it still gives the ordering department free stuff. Whatever. This is a fucking mess.

2024-12-30 21:24 UTC, LSommers commented
> I gave BRs a high price as a restriction, only to then realize that making something expensive inversely turns it into a free money generator for cargo. We've lost even a minor limiting factor on crates as a consequence of these consoles. I hate the fact that I had to make the import category just to circumvent this shit, and I don't want to stick anything I would prefer being limited into it, because that'd almost always be a hacky solution.
> 
> Why am I the only person who seems to think that this has entirely undermined crate price as a possible limiting factor? At the very least this PR makes it so that there isn't a recursive money generation taking place, where ordering from the departmental consoles then allows for the purchase of an additional crates worth of value.
> 
> Though ordering the most expensive item is still almost always the best option for money generation. And it still gives the ordering department free stuff. Whatever. This is a fucking mess.

Make departmental orders just give a free crate instead of a free crate AND free money?

2024-12-30 21:26 UTC, CCC23 commented
> > I gave BRs a high price as a restriction, only to then realize that making something expensive inversely turns it into a free money generator for cargo. We've lost even a minor limiting factor on crates as a consequence of these consoles. I hate the fact that I had to make the import category just to circumvent this shit, and I don't want to stick anything I would prefer being limited into it, because that'd almost always be a hacky solution.
> 
> > 
> 
> > Why am I the only person who seems to think that this has entirely undermined crate price as a possible limiting factor? At the very least this PR makes it so that there isn't a recursive money generation taking place, where ordering from the departmental consoles then allows for the purchase of an additional crates worth of value.
> 
> > 
> 
> > Though ordering the most expensive item is still almost always the best option for money generation. And it still gives the ordering department free stuff. Whatever. This is a fucking mess.
> 
> 
> 
> Make departmental orders just give a free crate instead of a free crate AND free money?

But my free moneie?

2024-12-31 13:38 UTC, Profakos commented
> May want to keep in mind the impact this can have on things like War Ops, since initially cargo was balanced around having about a ~10k budget, and that was removed when departmental orders got added.

This seems to be not fully correct. It looks like before free departmental orders were added, cargo had 5k points, as 35k has been divided between seven departments (now divided between six).

2024-12-31 13:39 UTC, Profakos commented
> imo these already arent used enough. also the words 'predictable and expected' should be kept as far away from ss13 as possible

Too late for that, the research, economy and dynamic antag systems has been made with this in mind for years now.

2024-12-31 15:23 UTC, Dawnseer commented
So what I'm hearing is we'll be forced to use the market? Because this is only imagining the scenario where all departments actually use their departmental orders. Which is from my experience, fucking never.
at least 95% of the time, you've got maybe 1-2 departments that actually use orders.

2024-12-31 16:59 UTC, Profakos commented
> So what I'm hearing is we'll be forced to use the market? Because this is only imagining the scenario where all departments actually use their departmental orders. Which is from my experience, fucking never. at least 95% of the time, you've got maybe 1-2 departments that actually use orders.

Are you saying the entire round's cargo credit income comes from scientists ordering canisters of BZ?

2024-12-31 17:03 UTC, Profakos commented
Most of the armoury ones barely exceed 3000 credits. NT-BR is a new crate that was not the lynchpin of the economy before it was ordered. The engineering ones are either not available every round, or are needed for highly specific engine/atmos expansion.

So the biggest outliers here is the BZ and N2O canisters, and the collectible hats crate, and I can't fathom that the economy would hinge ordering one of these every 20 minutes.

2025-01-05 21:03 UTC, Jackal-boop commented
Hey man where are you playing where every department consistently is using the order console off cooldown and only buying the most expensive crate

2025-01-05 22:25 UTC, Profakos commented
In the coding discord, we have discussed that the cap should be replaced with a logarithmic plot, with the formula being 120 * log(price)^1.5.

https://www.desmos.com/calculator/ktnpem0h8e You can play around with it here to see the sample values.

Drafted it until I can update the code, and write a new PR description.

2025-01-09 20:30 UTC, Profakos commented
I have added the log scalings. Keeping this in draft, until the values are examined and approved/sent back for tweaking.

2025-01-14 02:44 UTC, ArcaneMusic requested changes
Some numbers tweaks and nits

2025-01-14 02:44 UTC, ArcaneMusic commented on tgui/packages/tgui/interfaces/NtosDeptOrder.tsx
> +    (cost >= COST_MEDIUM_BOUND && 'moderate') ||
I would consider tweaking the way we're representing the time on the console. As an example, ordering a BZ canister versus a recovered employee is a 12 minute versus 18 minute cost at current. However, the employee is labeled as "short" while the BZ is considered long.

Also you'll want to re-assess this following the other review's comments on tweaking the cooldown formula

2025-01-14 02:44 UTC, ArcaneMusic commented on code/__DEFINES/cargo.dm
> +//At 320 it's 9.8 minutes, at 1400 it's 13.18 minutes,  at 3000 (around gun crates) it's 14.5 minutes, at 8000 (hat crate) 17 minutes, at 9000 (expensive atmos cans) it's 17.3 minutes, and at the 20k
Check my math here but is this comment accurate? 200*log(320)^1.2 is 602, so in seconds it's an even 10 minutes and 2 seconds. Same for the 3k estimate, I got 14.87 minutes.

2025-01-14 02:44 UTC, ArcaneMusic commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_POWER 1.2
Based on discussion on discord, proposing changing the coefficient to 60 and exponent to 2.2, so as to not punish players for requesting less expensive crates.

2025-01-14 08:00 UTC, Profakos commented on code/__DEFINES/cargo.dm
> +//At 320 it's 9.8 minutes, at 1400 it's 13.18 minutes,  at 3000 (around gun crates) it's 14.5 minutes, at 8000 (hat crate) 17 minutes, at 9000 (expensive atmos cans) it's 17.3 minutes, and at the 20k
You are correct, I probably have not updated the comment values properly.

2025-01-14 08:01 UTC, Profakos commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_POWER 1.2
I shall do so.

2025-01-14 08:05 UTC, Profakos commented on code/__DEFINES/cargo.dm
> +#define DEPARTMENTAL_ORDER_COOLDOWN_POWER 1.2
Also I completely forget that is what it is called in english, changing power to exponent in the define names.

2025-01-14 08:46 UTC, Profakos commented
Requested value changes done, I will deal with the order console later.

2025-01-14 19:41 UTC, Profakos commented on tgui/packages/tgui/interfaces/NtosDeptOrder.tsx
> +    (cost >= COST_MEDIUM_BOUND && 'moderate') ||
Altered.

2025-01-15 08:20 UTC, Profakos commented
I have also updated the changelog, as the old one was outdated.

2025-01-15 13:21 UTC, merged

2025-01-18 13:48 UTC, Dawnseer commented
So a departmental order that costs 20k, doesn't even give 1k of profit now. Surely you tested this before it got merged, right? It wasn't just pure numbers crushing, right? I sure love being forced to have to interact with the minerals market!

2025-01-18 17:38 UTC, ArcaneMusic commented
> So a departmental order that costs 20k, doesn't even give 1k of profit now. Surely you tested this before it got merged, right? It wasn't just pure numbers crushing, right? I sure love being forced to have to interact with the minerals market!

Of course I tested this, don't be ridiculous.

I think the disconnect here is what problem this is intended to solve. Contrary to what you may think, this wasn't as much to solve "Players clicking one button at the start of the shift and then getting 20,000 credits instantly", which is egregious and showcases an oversight into the departmental supplies system. No, the issue is more that when you're using the system to get free supplies for free, the reward was never supposed to be the number of credits that come back into the cargo department. The reward is the supplies. That the orderer, supposedly, wants to use. 

Cargo is supposed to be reimbursed for their *time*, not for the value of the free supplies that the station already needs.

If the numbers need to be tweaked further going forward, that's now as easy as a 2 line balance PR.

~~And for the record mineral market needs to be taken out back and beaten with wrenches at present, it is by no means supposed to be the primary money making method in cargo, just an available method.~~