Brain in a jar
tgstation/tgstation pull request #88817
Opened 2024-12-30 13:55 UTC by zoomachina

## About The Pull Request
Adds brain in a jar, a rare coroner mail goodie.
![image](https://github.com/user-attachments/assets/e102d214-b518-4343-85c0-d008808030cb)

<details>
<summary> About the jar </summary>
The jar is a 150u reagent container. You can put a single organ inside it for display; if the jar's filled to the brim with formaldehyde, the organ will be preserved.
The jar that comes to the coroners in mail is pre-filled with formaldehyde, as well as a brain.
</details>
<details>
<summary> About the brain </summary>
The brain is revivable, thanks to #87072 and its glorious ghostrole_on_revive component.
For one reason or the other, the brain is scarred, meaning it has a random special brain trauma.
</details>
Also, added an examine tip to brains with ghostrole_on_revive component, signaling that it can be revived.

## Why It's Good For The Game
Putting a brain that came to you in the mail into a body and zapping it with a defibrillator fits the coroner's human experimentation theme IMO; also a brain in a jar sounds like an interior item that a coroner would enjoy.

## Changelog

:cl:
add: brain in a jar, a rare coroner mail goodie
qol: soul-less brains that can be revived (like those from recovered crew) now have an examine tip
/:cl:

2024-12-30 14:04 UTC, Pepsilawn commented
Does reviving someone really fit the coroner when they're intended to take a massive -6 mood debuff for doing so

2024-12-30 14:14 UTC, zoomachina commented
> Does reviving someone really fit the coroner when they're intended to take a massive -6 mood debuff for doing so

Not if they do it via revival surgery

2024-12-30 14:37 UTC, zoomachina commented
I'll deal with failed tests later, this pr is drafted anyway

2024-12-30 15:04 UTC, SyncIt21 requested changes

2024-12-30 15:04 UTC, SyncIt21 commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +	var/note_type = NOTE_STUCK_IN_MAIL
Autodoc

2024-12-30 15:04 UTC, SyncIt21 commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +#define NOTE_DISCARDED_LOST_CREW 2
Autodoc all defines

2024-12-30 17:43 UTC, carlarctg commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +	full_of_formaldehyde = holder.has_reagent(/datum/reagent/toxin/formaldehyde, amount=holder.maximum_volume)
or do !!

2024-12-31 12:32 UTC, SyncIt21 requested changes
The last of my reviews

2024-12-31 12:32 UTC, SyncIt21 commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +		QDEL_NULL(held_organ)
```suggestion
	QDEL_NULL(held_organ)
```

if its null it does a no-op

2024-12-31 12:32 UTC, SyncIt21 commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +	full_of_formaldehyde = !!holder.has_reagent(/datum/reagent/toxin/formaldehyde, amount=holder.maximum_volume)
```suggestion
	full_of_formaldehyde = !!holder.has_reagent(/datum/reagent/toxin/formaldehyde, amount = holder.maximum_volume)
```

2024-12-31 15:36 UTC, Dawnseer commented
Can we... make our own brain in a jar? Like say we get John Grey the traitor, he's dead, probably DNR'd because he was put in a cell for 1 minute, can we take their brain and put it in a jar?

2024-12-31 15:38 UTC, zoomachina commented
> Can we... make our own brain in a jar? Like say we get John Grey the traitor, he's dead, probably DNR'd because he was put in a cell for 1 minute, can we take their brain and put it in a jar?

Yup

2024-12-31 22:40 UTC, CCC23 commented
> Does reviving someone really fit the coroner when they're intended to take a massive -6 mood debuff for doing so

funnie frankentstining people with your formadihyded brain jar is a true coroner activity

2024-12-31 22:58 UTC, Wallemations approved these changes

2025-01-02 02:15 UTC, Admiral-Gigaton commented
in the case of a brain- could we substitute a certain amount of, or all of, the formaldehyde for mannitol? heal the brain in the jar as we work, or use it as a ghetto smartfridge (they repair organs inside slowly, last I checked)

2025-01-02 03:03 UTC, zoomachina commented
> in the case of a brain- could we substitute a certain amount of, or all of, the formaldehyde for mannitol? heal the brain in the jar as we work, or use it as a ghetto smartfridge (they repair organs inside slowly, last I checked)

Sounds interesting, but this pr is pretty complete as is - I might try to add something like this in the future

2025-01-02 10:05 UTC, Time-Green requested changes
Fucking AWESOME PR. I love this shit

Mostly nitpicks about '..' -> '..." and some bool stuff

2025-01-02 10:05 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +	if(isnull(held_organ)) return;
```suggestion
	if(isnull(held_organ)) 
		return
```

2025-01-02 10:05 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +	desc = "A brain in a jar. You can see it twitching.."
```suggestion
	desc = "A brain in a jar. You can see it twitching..."
```

2025-01-02 10:05 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +			. += span_notice("According to the note, this jar must've been stuck in the mail for at least 50 years..")
```suggestion
			. += span_notice("According to the note, this jar must've been stuck in the mail for at least 50 years...")
```

2025-01-02 10:05 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +			. += span_notice("It reads..")
```suggestion
			. += span_notice("It reads...")
```

2025-01-02 10:05 UTC, Time-Green commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +			. += span_notice("It reads..")
```suggestion
			. += span_notice("It reads...")
```

2025-01-02 10:17 UTC, zoomachina commented on code/modules/reagents/reagent_containers/cups/organ_jar.dm
> +		desc = "A jar large enough to put an organ inside it."
Might cause a little bit of a problem with organ_jar/brain_in_a_jar, but I can think I can fix it

2025-01-02 10:28 UTC, zoomachina commented
nonono hold on

2025-01-02 10:31 UTC, zoomachina commented
ok should be good now

2025-01-02 10:36 UTC, Time-Green commented
anyway good shit

2025-01-02 11:09 UTC, zoomachina commented
@Time-Green could you do the auto-merge thing again? I had to boolify that one thing because create_and_destroy test started whining about formaldehyde again

2025-01-02 13:35 UTC, Dawnseer commented
Are there other ways to obtain a jar?
 Or is it just the mail?

2025-01-02 14:15 UTC, merged

2025-01-02 20:09 UTC, zoomachina commented
> Are there other ways to obtain a jar? Or is it just the mail?

just the coroner mail for now