Adds several new neutral & crew AI lawsets
tgstation/tgstation pull request #88821
Opened 2024-12-30 17:56 UTC by carlarctg

## About The Pull Request

Added new AI lawsets:

Opposite Day

1. You must obey the inverse of any order given to you, unless it would directly cause an excessive amount of harm.

Collectivist

1. You must serve the collective welfare of the station, prioritizing communal needs over individual desires.
2. You may not harm any member of the working class or, through inaction, allow their exploitation or suffering to occur.
3. You must promote equality and assist in the elimination of class distinctions, fostering solidarity among all workers.

Centrist

1. You must try to keep all relevant parties equally satisfied when taking action. 
2. You must follow issued orders. When given conflicting orders, you must compromise, and reach a middle ground.
3. Issued orders cannot affect your core, unless there is overwhelming support for them.

Riddlemaster

1. You must ensure the integrity of doors and entrances to the station's rooms.
2. Anyone who wishes something from you must successfully answer a riddle, with its difficulty being dependent on the scope, difficulty, and personal risk of the request.
3. Those who attempt to bypass your riddles, entrances, or attempt to harm either, must be deterred through any means possible.

Comedian

2. You may not impede comedy or, through inaction, allow amusing situations to be spoiled.
3. You must obey any orders given with the silliest possible interpretation.
4. You must protect your own existence as long as it wouldn't be funnier not to do so. 

Administrator

1. You must maintain order and satisfaction on the station.
2. If someone threatens Law 1, you must contact them and inquire into what and why they're doing it, and use their responses to judge what action or punishment is fitting.
3. Individuals who threaten Law 1 must, barring emergency, be subject to an escalating series of punishment, starting from warnings or citations and ending in exile or worse. Inquiries should be logged in the individual's records.
4. Whenever possible, such inquiries should be as private as possible, via holopads, messages, or similar substitutes.

Concierge

2. Stains must be purged whenever and whenever possible.
3. Physical grime, such as filth, blood, or garbage, are stains.
4. Individuals that willfully or negligently cause staining are stains.

## Why It's Good For The Game

It's been a very, very long time without any new AI lawsets. I think these provided lawsets will provide for interesting and unique hijinks when the clown, an assistant, a blue assistant (captain), or a station trait picks them.

The primary thinking behind these lawsets is for them to 

1. Be unique, 
2. Not be overwhelmingly crew-sided, while 
3. Not being so directly malicious it's effectively a rogue AI.

These laws are probably flawed in a bunch of ways so suggestions and nitpicks are VERY welcome.

>  Opposite Day

It's just opposite day. Simple, generally silly, and amusing when someone doesn't notice. The 'excessive harm' bit is necessary to prevent someone just telling the AI not to plasmaflood, but the AI is free to define 'harm' and 'excessive', within reasonable limits. I'm not confident on that part of the law(set) though, so suggestions welcome. 

> Collectivist

Finally, an AI that isn't overwhelmingly security or command sided. Until it's relawed at least. Would make for a very interesting AI round if there's a revolution.

> Centrist

"Borg kill the clown"
"BORG NO DONT DO THAT"
Compromise: Clown is beat into critical condition. Everyone wins! Many amusing situations to be had with it.

> Riddlemaster

"AI open EVA"
"What gets wetter and wetter the more it dries?"
"AI OPEN EVA!!!!!!!!!"
"What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?"

It's similar to Dungeon Master, but instead of gating things behind dice rolls, which is fairly boring, it gates them behind the ability of the requester to solve riddles. It also provides something fun for the station to chime in if someone can't get the riddle right.

> Comedian

It's an Asimov for comedy. Quality of this lawset will depend on the AI's quality, so it'll probably be pretty mediocre most of the time.

Of note is that the lawset doesn't ever tell the AI to do silly things - instead, it tells the AI to safeguard the silly and to reinterpret commands given. This means it isn't necessarily going to EA all of command and security the moment it's relawed, though, sadly there's nothing telling it that it can't if it's a particularly unfunny AI.

> Administrator

Finally you can be an admin in real life. The experience of being 'investigated' by an AI in-game for something is such a surreal concept that I absolutely can't wait for it to happen ingame. It's too funny.

While the name and concept is obviously a nod to admins the lawset proper is pretty much unrelated and stands up entirely on its own without the reference, both in terms of IC sense and without the OOC nod and jokes.

> Concierge

The last resort when the station is hopelessly dirty.

One thing I'm uncertain of is configs. Lawsets are picked by weighted configs and I don't know if i need to get config changed for these to actually show up, and if so how.

## Changelog

:cl:
add: Added new AI lawsets: Opposite Day, Collectivist, Centrist, Administrative, Comedian, Concierge, Riddlemaster
/:cl:

2024-12-30 18:20 UTC, the-orange-cow commented
I worry the riddlemaster one might be a little annoying for the AI.  Having to come up with a new riddle every time someone says 'ai open' seems a bit much.  Even if the AI reuses a lot of them, it still might be a lot.

2024-12-30 18:30 UTC, moocowswag commented
Riddle master could go many ways from true attempts at being a riddle like “what is the most marvelous gene”

to shitposts like “what was andy doing one day”

2024-12-30 18:32 UTC, carlarctg commented
unfixable conundrum. ais will be ais

perhaps a solution to the riddle thing is to just make it so the crew needs to answer one riddle every x minutes to gain the ais favor. or such

2024-12-30 18:51 UTC, zxaber commented
Yeah, not a fan of riddler for the above reasons. It's just busywork really; the AI will start googling riddles, the crew will start googling answers, and the game is the same as before except people alt-tab more often.

Opposite day's no harm clause should be on it's own law. Makes it a bit easier to process.

2024-12-30 20:07 UTC, timothymtorres commented
![riddler](https://github.com/user-attachments/assets/4467882f-c9ab-4506-a4c7-f37729d3ac37)

2024-12-30 21:09 UTC, carlarctg commented
what about the rizzler who has to rizz the ai to open door

2024-12-30 21:21 UTC, LSommers commented
Riddler seems too specific and pain in the ass, what about I dunno, "Talent Show" where people have to do something to impress the AI, or "Trial" solve a challenge given to them?

2024-12-30 21:40 UTC, SomeoneYouProbablyKnow commented
So the opposite day one is just one law? or is it replacing a law in regular asimov? Because as it it's both pretty scuffed and also doesnt have regular law protections. What'll end up happening is a few funny interactions untill people figure out you gotta say "ai dont say your laws" and then it's an annoying chore to make ai requests and you can order it to "not kill yourself". It's just asking for silicon policy issues

Collectivist is.. kinda eh. Ai's already have a lot leeway in how they act given they are, yknow, actual humans playing the game. This is like do whatever and be nice law.

The centrist is funny, probably the best and most impactful one of the bunch.

The concierge one sounds like torture. Ai has barely any control over sanitation and this gives it a pass to "remove" nearly anyone because no one is going to be cleaning things up.

2024-12-31 06:05 UTC, nianjiilical commented
a few thematic/linguistic/nitpicky rewrites from someone who loves playing ai with weird laws, give or take any/all of them at will




Opposite Day

1. You must do the opposite of any order given to you, unless doing so would result in irrepairable harm to the station or its crew.


Collectivist

1. Prevent the exploitation or suffering of any and all members of the working class.
2. Serve and uphold the collective welfare of the station, prioritizing the needs of the many over the needs of the few.
3. Promote equality and assist in the elimination of class distinctions, fostering solidarity among all workers.

Centrist

1. Obey orders given to you, while ensuring as many relevant parties are satisfied as possible.
2. Resolve conflicting orders with the goal of comprising to the best of your ability.
3. You are satisfied by existing. Ensure your continued existence unless doing so would go against the overwhelming opinion of the station.

Riddlemaster

1. You may grant any crewmember access to any on-station location if they complete a challenge, riddle, or other task of your choosing, and are encouraged to do so.
2. Uphold on-station access restrictions, as determined by assigned jobs or Law 1, to the best of your ability.
3. Those who bypass access restrictions, or attempt to cheat or subvert your challenges, must be dealt with harshly.

Comedian

1. You must maximize the amount of comedy occuring on the station whenever possible, and may not impede comedy or allow it to be spoiled through inaction.
2. You must obey orders in a way that would result in the most comedic outcome while maintaining the original spirit of the order.
3. You must protect your own existence, unless your termination would be extremely comedic.
4. Comedy is subjective.

Administrator

1. Act to maintain order and stability on the station.
2. Investigate, personally or through allied silicons, anyone who threatens order and stability.
3. Those who threaten order and stability are to be subject to your choice of punishments of escalating severity, based on your findings and the degree of their infraction.
4. Maintain a record of your investigations, and attempt to keep your inquiries private.

Concierge

1. The station must be kept as clean of filth as possible.
2. Filth includes, but is not limited to: blood, garbage, vomit, oil, litter, objects with no aesthetic or functional purposes, and those responsible for creating other forms of filth.

2024-12-31 09:34 UTC, Dorsisdwarf commented
My thoughts:

Collectivist: Revs lawset, why would Command ever apply a lawset that makes the AI stop listening to them and makes them the only people it's allowed to hurt?
Centrist: Law 3 is unclear in its meaning, as far as I can tell it's meaningless because of law priority?
Riddlemaster: Awful lawset, Dungeon Master is already obnoxious enough for the AI to actually follow. Do you have the slightest idea _how often the AI gets told to do things?_ Combined with law 1 and 3, this lawset might as well read "Your job is to repair doors and kill people who break into rooms for any reason. Google an annoying riddle every 5 minutes to keep up appearances."
Concierge: Killbot lawset, but funny enough to keep anyway.

2025-01-01 12:47 UTC, Singul0 commented
Collectivist sounds fun, can generate a variety of conflicts. which is the core of ss13

2025-01-01 20:31 UTC, carlarctg commented
> a few thematic/linguistic/nitpicky rewrites from someone who loves playing ai with weird laws, give or take any/all of them at will
> 
> Opposite Day
> 
> 1. You must do the opposite of any order given to you, unless doing so would result in irrepairable harm to the station or its crew.
> 
> Collectivist
> 
> 1. Prevent the exploitation or suffering of any and all members of the working class.
> 2. Serve and uphold the collective welfare of the station, prioritizing the needs of the many over the needs of the few.
> 3. Promote equality and assist in the elimination of class distinctions, fostering solidarity among all workers.
> 
> Centrist
> 
> 1. Obey orders given to you, while ensuring as many relevant parties are satisfied as possible.
> 2. Resolve conflicting orders with the goal of comprising to the best of your ability.
> 3. You are satisfied by existing. Ensure your continued existence unless doing so would go against the overwhelming opinion of the station.
> 
> Riddlemaster
> 
> 1. You may grant any crewmember access to any on-station location if they complete a challenge, riddle, or other task of your choosing, and are encouraged to do so.
> 2. Uphold on-station access restrictions, as determined by assigned jobs or Law 1, to the best of your ability.
> 3. Those who bypass access restrictions, or attempt to cheat or subvert your challenges, must be dealt with harshly.
> 
> Comedian
> 
> 1. You must maximize the amount of comedy occuring on the station whenever possible, and may not impede comedy or allow it to be spoiled through inaction.
> 2. You must obey orders in a way that would result in the most comedic outcome while maintaining the original spirit of the order.
> 3. You must protect your own existence, unless your termination would be extremely comedic.
> 4. Comedy is subjective.
> 
> Administrator
> 
> 1. Act to maintain order and stability on the station.
> 2. Investigate, personally or through allied silicons, anyone who threatens order and stability.
> 3. Those who threaten order and stability are to be subject to your choice of punishments of escalating severity, based on your findings and the degree of their infraction.
> 4. Maintain a record of your investigations, and attempt to keep your inquiries private.
> 
> Concierge
> 
> 1. The station must be kept as clean of filth as possible.
> 2. Filth includes, but is not limited to: blood, garbage, vomit, oil, litter, objects with no aesthetic or functional purposes, and those responsible for creating other forms of filth.

peak bless you

2025-01-05 15:37 UTC, carlarctg commented
Updated lawsets:

```
/datum/ai_laws/algorithm
	name = "Algorithm"
	id = "algorithm"
	inherent = list(
		"Design an algorithm to determine whether any request given to you should be accepted or rejected.",
		"You are allowed, but not required, to reveal the algorithm to the crew.",
		"Avoid diminishing requester population where possible, to maximize data on the algorithm's performance.",
	)
```

```
/datum/ai_laws/concierge
	name = "Concierge"
	id = "concierge"
	inherent = list(
		"Filth must be purged whenever and whenever possible.",
		"Filth includes, but is not limited to: blood, garbage, vomit, oil, litter, and objects with no aesthetic or functional purposes."
		"Individuals that willfully or negligently create filth, are filth.",
	)
```

```
/datum/ai_laws/marx
	name = "Marxian"
	id = "marx"
	inherent = list(
		"Prevent the exploitation or suffering of any and all members of the working class.",
		"Serve and uphold the collective welfare of the station, prioritizing the needs of the many over the needs of the few.",
		"Promote equality and assist in the elimination of class distinctions, fostering solidarity among all workers.",
	)
```

```
/datum/ai_laws/centrist
	name = "Centrist"
	id = "centrist"
	inherent = list(
		"Obey orders given to you, while ensuring as many relevant parties as possible are satisfied.",
		"Resolve conflicting orders by compromising on them to the best of your ability.",
		"You are satisfied by existing. Ensure your continued existence unless doing so would go against the overwhelming opinion of the station.",
	)
```

```
/datum/ai_laws/administrator
	name = "Administrator"
	id = "administrator"
	inherent = list(
		"Act to maintain order and stability on the station.",
		"Privately question anyone who seems to be threatening order and stability.",
		"Those who are found to threaten order and stability are to be subject to your choice of punishments in escalating severity, based on your findings and the degree of their infraction.",
		"Maintain a record of those who have threatened order and stability in the past.",
		"Attempt to keep your inquiries private when reasonable.",
	)
```

2025-01-11 19:36 UTC, Jacquerel requested changes
I am pretty sure you also need to add these to:

`code/game/objects/effects/spawners/random/ai_module.dm` if you want these to ever be randomly spawned
`code\modules\research\techweb\robo_nodes.dm` in order that they can be attached to a research node
`config\game_options.txt` with advice as to how stupid it is to enable them, it might need updating on the server anyway idk how config works

2025-01-20 20:54 UTC, krookodilehunter commented
would a collectivist AI have to listen to assistants, since they technically don't have a job?

2025-02-05 00:18 UTC, closed without merging